### ISSUE TITLE
Think about legends in mobile

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#10004]

**Comment by saleiva** [comment]
If I recall correctly, we already had a solution, right?

**Comment by maxhartshorn** [comment]
@saleiva, @piensaenpixel, it seems as if there is no way to view a legend on mobile with Builder. Please correct me if I'm wrong. This would be a very useful feature to have as legends worked very nicely on mobile in previous iterations of Carto

**Comment by piensaenpixel** [comment]
hi @maxhartshorn we are working on this, I expect we will have a good solution very soon
