### ISSUE TITLE
'Tracts' setting is applied in distance AOI analysis

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#10001]
# STR

- Create a points map with the builder
- Add AOI analysis
- Open `Time` type parameters and set `2` tracts

![screen shot 2016-10-04 at 12 01 37](https://cloud.githubusercontent.com/assets/10940006/19070193/666960c4-8a2a-11e6-9fda-a723b3861a08.png)

- Go back to `Units` type settings, change anything (or not) and Apply the analysis. The result is showing **2 tracts** even if the setting is not present for that type of AOI analysis.

![screen shot 2016-10-04 at 12 03 32](https://cloud.githubusercontent.com/assets/10940006/19070274/bc961b22-8a2a-11e6-8287-c18c1ee02d30.png)

## What's expected

Either the `tracts` setting should only apply on the `Time` AOIs.

Or the `tracts` setting should also be available for `Units` AOIs

## .carto file to reproduce the issue

[Populated Places (on 2016-10-04 at 10.07.48).carto.zip](https://github.com/CartoDB/cartodb/files/508148/Populated.Places.on.2016-10-04.at.10.07.48.carto.zip)

**Comment by javierarce** [comment]
The tracts option (called `isolines` internally) appears in both [`buffer`](https://github.com/CartoDB/camshaft/blob/master/reference/versions/0.44.0/reference.json#L105) (Units) and [`trade-areas`] (https://github.com/CartoDB/camshaft/blob/master/reference/versions/0.44.0/reference.json#L1082) (Time) analyses… so I'll make the tracts option available for both of them.

**Comment by javierarce** [comment]
The tracts option (called `isolines` internally) appears in both [`buffer`](https://github.com/CartoDB/camshaft/blob/master/reference/versions/0.44.0/reference.json#L105) (Units) and [`trade-areas`] (https://github.com/CartoDB/camshaft/blob/master/reference/versions/0.44.0/reference.json#L1082) (Time) analyses… so I'll make the tracts/isoline option available for both of them.

CC: @dgaubert
