### ISSUE TITLE
Legend bubble when styling by size fails

### ISSUE THREAD

**Issue by nobuti** [CartoDB/cartodb#10018]
### STR

1. Create a map of points
2. Style one layer by size, choosing a numeric column
3. The legends doesn't show up. Instead the loading never stops.
4. Open the console and you'll see the next error:
`rule-to-bubble-legend-adapter.js:14 Uncaught TypeError: Cannot read property 'unshift' of undefined`

![bubble_legends](https://cloud.githubusercontent.com/assets/1366843/19082434/70217f50-8a5e-11e6-9b3a-c1d9bf412475.gif)

cc @xavijam @alonsogarciapablo

**Comment by alonsogarciapablo** [comment]
Have you tried this in production?
