### ISSUE TITLE
Ramping polygon-opacity in Builder with Turbo Carto is not working

### ISSUE THREAD

**Issue by makella** [CartoDB/cartodb#10017]
In Builder I get an error if I ramp opacity. For example, if I try something like 
`polygon-opacity: ramp([r_total], 0.1,0.9, quantiles);`

I get this error:
![screen shot 2016-10-04 at 9 49 31 am](https://cloud.githubusercontent.com/assets/1566273/19081659/4ae13b4a-8a18-11e6-8acd-3096c4c6f430.png)

If I do the same styling in this [Turbo Carto block](http://bl.ocks.org/rochoa/raw/4e67ec932e8bb6b17831e0f4a2e0e55d/), it works:

![screen shot 2016-10-04 at 9 49 55 am](https://cloud.githubusercontent.com/assets/1566273/19081676/61703d0c-8a18-11e6-8ad8-3cc131303636.png)

Any ideas why?

cc @rochoa

**Comment by rochoa** [comment]
The builder validates the CartoCSS (turbo-carto) client side, it uses torque-reference from https://github.com/CartoDB/carto/blob/f17aea8657ea27f2a660db15dd13b57127e823f9/lib/carto/torque-reference.js#L309-L315. That property does not support expressions as opposed to, for instance, polygon-fill.

The validation would work if we make that property expression friendly:

```patch
diff --git a/lib/carto/torque-reference.js b/lib/carto/torque-reference.js
index 0b9f204..65cb946 100644
--- a/lib/carto/torque-reference.js
+++ b/lib/carto/torque-reference.js
@@ -311,7 +311,8 @@ var _mapnik_reference_latest = {
                 "type": "float",
                 "doc": "The opacity of the polygon",
                 "default-value": 1,
-                "default-meaning": "opaque"
+                "default-meaning": "opaque",
+                "expression": true
             },
             "gamma": {
                 "css": "polygon-gamma",
```

Probably we need to start considering generating a turbo-carto-reference so we can say what properties are expression friendly.

**Comment by xavijam** [comment]
Agree with @rochoa about the reference.

**Comment by makella** [comment]
So is this something you guys would consider making expression friendly? (_**pretty please!!**_) 

I will help with the reference!

So we can make maps like this -- with a single line!

![screen shot 2016-10-04 at 10 44 06 am](https://cloud.githubusercontent.com/assets/1566273/19083491/8ea022c2-8a1f-11e6-880c-2ab50fe081eb.png)

**Comment by saleiva** [comment]
+1!

**Comment by ramiroaznar** [comment]
Ramping `builder-fill` is also getting the same error. It would be great to have this feature, check it out!

![buildings_bcn](https://cloud.githubusercontent.com/assets/5215798/19856816/6a90683a-9f7b-11e6-8912-79afc9dcee7c.png)

**Comment by craigmmills** [comment]
+1

**Comment by saleiva** [comment]
somehow related with https://github.com/CartoDB/cartodb/issues/8142

**Comment by makella** [comment]
Was excited the other day to figure out a hack for ramping opacity so thought I'd share here if anyone is interested in trying it out until we have the ability to do it in Builder. 

Since we can use `rgba()` you can do something like this. Of course, you have to figure out the opacity for each class break manually and convert any hex values to rgb, but at least you can use a classification method to do it without having to figure out how to get the class breaks. 

You can use a batch hex > rgb converter on any color scheme with a tool like this: http://www.zonums.com/online/color_converter/

Example syntax: 
```
  polygon-fill: 
    ramp([perc_owner], 
    (rgba(196,230,195,0.2),
    rgba(128,199,153,0.3),
    rgba(77,162,132,0.5),
    rgba(45,121,116,0.7),
    rgba(29,79,96,0.9)), 
    quantiles);
``` 

@ramiroaznar thought this would mostly be exciting for you :)

**Comment by ramiroaznar** [comment]
The initial issue is solved.

**Comment by makella** [comment]
really?? SUPER EXCITING
