### ISSUE TITLE
Wroing text on Widget UI Refering for the description

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10010]
![screen shot 2016-10-04 at 16 22 30](https://cloud.githubusercontent.com/assets/132149/19077971/d005530c-8a4e-11e6-93d6-4721e43f121b.png)

Looks like something is wrong with the i8n labels. On the description it says "DEFINE HOW YOUR WIDGET INTERACTS WITH THE DATA" but it should say, "Description"

**Comment by MariaCheca** [comment]
Duplicated https://github.com/CartoDB/cartodb/issues/9784
