### ISSUE TITLE
Implement new Add Analysis modal

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#10014]
Working branch: `add-analysis-animation`

- [ ] Improve and cleanup CSS for the animations & the modal.
- [x] Adds autoplay to info pane view.
- [x] Add analysis info page.
- [x] Add 'all' tab.
- [x] Add tabs for the different categories.
- [x] Add amazing animations.

Related issues:

- [[DESIGN] Revise Add analysis screen](https://github.com/CartoDB/cartodb/issues/8066)
- [Revise Add analysis screen](https://github.com/CartoDB/design/issues/107)

CC: @piensaenpixel

**Comment by xavijam** [comment]
cc @piensaenpixel
