### ISSUE TITLE
SQL appears when dragging out the original layer node from an analysis

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#10025]
### STR

1. Select a dataset and click on "CREATE MAP".
2. Add an analysis to that layer. For instance, "Create Areas of Influence".
3. Drag out and drop the original layer from the analysis. 
4. An unexpected behaviour happens, the layer node shows that there is an `SQL` query applied. When checking, just the schema is added. You can click on "CLEAR" to remove this addition.

**Comment by javitonino** [comment]
Adding a detail, it appears it only happens with usernames with hyphens in the name :confused:

**Comment by javitonino** [comment]
Patch deploying. Should fix it for new layers created from dragging operations. Sadly, it won't fix it for existing layers.
