### ISSUE TITLE
Sync table Layout seems broken on the title

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10035]
![screen shot 2016-10-05 at 13 06 10](https://cloud.githubusercontent.com/assets/132149/19110822/87a0c1b0-8afc-11e6-91e0-c1729b19aef2.png)

When importing from https://data.cityofnewyork.us/api/geospatial/e2f7-cs7i?method=export&format=GeoJSON

**Comment by xavijam** [comment]
@MariaCheca, those are details we have to pay attention, please.

**Comment by MariaCheca** [comment]
Fixing ASAP.

**Comment by xavijam** [comment]
Thanks a lot
