### ISSUE TITLE
When no maps, analysis or API calls affected, we shouln't mention them on the delete dataset confirmation modal

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10033]
![screen shot 2016-10-05 at 12 54 19](https://cloud.githubusercontent.com/assets/132149/19110580/1157deea-8afb-11e6-9ff9-69264a479598.png)

**Comment by xavijam** [comment]
Agree, we should change the title.

**Comment by xavijam** [comment]
I feel we will fix this problem in https://github.com/CartoDB/cartodb/issues/10147.

**Comment by javisantana** [comment]
#MG04
