### ISSUE TITLE
add support for transparent colors for color picker when styling by value

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#10043]
**feature request**

- I'd love to be able to set a transparent color in a ramp, by editing the opacity of the colors

**description**

I wanted to categorize an OSM export by landuse, so I used the style by value, but there was a "others" category too much prominent

<img width="1680" alt="screen shot 2016-10-05 at 13 43 15" src="https://cloud.githubusercontent.com/assets/36676/19112648/48c7d334-8b06-11e6-99cf-18112a954a8d.png">

my first idea was to apply some opacity to it, but I think this is constrained in the UI by the colorpicker, wich won't let you edit the opacity

however, I've checked with @rochoa this is possible, and tried with the following cartocss

<img width="1679" alt="screen shot 2016-10-05 at 14 10 41" src="https://cloud.githubusercontent.com/assets/36676/19112522/8672c122-8b05-11e6-9c3b-4e89cdb33cdb.png">

but I still wanted to do this through the colorpicker so I fiddled a bit, and removing the disabled attribute I managed to apply a "0" opacity to the color (and the rest of rgb values), which translates into a "transparent" value in the hex field

<img width="1680" alt="screen shot 2016-10-05 at 14 13 55" src="https://cloud.githubusercontent.com/assets/36676/19112615/0c5d1c74-8b06-11e6-8618-adfa9533f206.png">

the sad part is when opening the colorpicker again it returns an error (as anybody would expect)

<img width="1680" alt="screen shot 2016-10-05 at 14 14 55" src="https://cloud.githubusercontent.com/assets/36676/19112636/2f8977ce-8b06-11e6-80f8-3cd5d7806c71.png">

/cc @javierarce @saleiva @xavijam

**Comment by saleiva** [comment]
Duplicated!
