### ISSUE TITLE
Double-line sentence on Histogram widget metadata 

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#10047]
When I add a histogram widget that has a large amount of numbers in the MIN, AVG and MAX fields, the "Null rows" field creates two lines. 

![screen shot 2016-10-05 at 15 59 06](https://cloud.githubusercontent.com/assets/16247628/19116184/dbe4448c-8b14-11e6-98b8-f92b7caf854c.png)

I used [this dataset](https://team.carto.com/u/arianaescobar/tables/police_service_areas_psa/public) and `count_vals_density` on the column field to create the widget.

Also, the first two values below the graph are so long that they look like a single value.

**Comment by xavijam** [comment]
Issue moved to [CartoDB/deep-insights.js #456](https://github.com/CartoDB/deep-insights.js/issues/456) via [**ZenHub**](https://www.zenhub.com/)
