### ISSUE TITLE
Aggregating by admin level should apply an style by value (agg_value_density) by default

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10053]
Right now it aggregates the data, but it doesnt apply the correct style.

#SMOKE_MG26

**Comment by xavijam** [comment]
If we do so we will need to apply a ramp by default, any advice @makella?

**Comment by makella** [comment]
@xavijam of course! But in order for the best advice, can you let me know if I can test? Thanks!

**Comment by javisantana** [comment]
@makella you can test it right now, just apply an aggregation per admin level and style it by the `agg_value_density`

I guess we'd want to use any of the quantitative ones in cartocolor, right?

**Comment by makella** [comment]
Quantiles, 5 bins, `cartocolor(Emrld)`

think that should be good for now.

**Comment by xavijam** [comment]
:+1:
