### ISSUE TITLE
Heatmaps ramps arent there on the aggregation per pixel.

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10054]
cc/ @makella

**Comment by makella** [comment]
@saleiva which map type? 

I see the two palettes showing in the drop-down for hexbins, rectangles, torque heatmap, and pixel. They aren't available in the Aggregation None option.

**Comment by xavijam** [comment]
I don't get it, do we have specific ramps for the heatmap style?

**Comment by makella** [comment]
@xavijam yes, we have two ramps specifically for aggregation (hexbin, rectangle, torque>heatmap, and pixel)

`ag_sunset`: https://github.com/CartoDB/CartoColor/blob/master/cartocolor.js#L836-L879

`ag_GrnYl`: https://github.com/CartoDB/CartoColor/blob/master/cartocolor.js#L444-L486

**Comment by saleiva** [comment]
yeah, the rest of the ramps doesnt make so much sense
