### ISSUE TITLE
Datasets dashbord not working for a msaenz user

### ISSUE THREAD

**Issue by jmartinter** [CartoDB/cartodb#10060]
After user msaenz imported a couple of datasets into his account on builder, they don't appear on his dashboard. The dashboard shows the shared dataset list by default and we you click on the '3 datasets' link, nothing happens. 

![seleccion_001](https://cloud.githubusercontent.com/assets/6340904/19145694/73a86078-8bb0-11e6-932b-544e50f0bae9.png)

These datasets (nyc_blocks, dominos_data, sf_trees) seem to be imported successfully because you can access them searching by name.

@xavijam @msaenzde11

**Comment by jmartinter** [comment]
I don't see this behaviour in my own account

**Comment by javitonino** [comment]
It works for me. Have you tried deleting the browser cache?

**Comment by xavijam** [comment]
Yeah, it is likely that problem.

**Comment by msaenzde11** [comment]
Not working.. However it turns out it only happens in my team account, because if I log in with my user account, I can get into the tab.

**Comment by jmartinter** [comment]
@msaenzde11 Team account uses new builder while your personal account should use old editor. They are different apps.

**Comment by xavijam** [comment]
It is working, already checked. You need a full refresh of the browser.

Chrome in Mac: CMD + shift + r

**Comment by javitonino** [comment]
Fixed by running `localStorage.clear()` in the JS console and refreshing. For some reason, Firefox's button to delete the local storage didn't work.

**Comment by msaenzde11** [comment]
Congrats guys! And thanks ;)
