### ISSUE TITLE
Different cross icons on the dashboard when uploading a dataset and once it's uploaded

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#10062]
There are different cross icons on the window that pops-up when you're adding a dataset on the dashboard. The expected one is the blue one below. 

![screen shot 2016-09-30 at 17 59 23](https://cloud.githubusercontent.com/assets/16247628/19148668/1c58c1c4-8bbe-11e6-8eab-e3e279885a30.png)

Easy to replicate, just drag and dropping dataset files on the dashboard.

**Comment by xavijam** [comment]
That doesn't belong to the Builder itself, let me remove the label and the milestone, 💋 .
