### ISSUE TITLE
Feature request: Filter by column value for strings should allow multiple values to be selected

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartodb#10072]
Currently the "Filter by column value" analysis, when working with strings, only allows filtering by one value at a time. Many users will need to filter by multiple values at a time. The multiple selector, like that used in "Predict trends and volatility" or the JOIN analysis, would be perfect here.

This format is more common:
`SELECT * FROM awesome_stuff WHERE name IN ('andy', 'jamon', 'raul')`

Currently something like this is happening through camshaft:
`SELECT * FROM awesome_stuff WHERE name = 'jamon'`

By allowing for multiple string values to be selected, the user will have options more similar to what is offered in the float version, which allows ranges to be selected.

To make it more advanced, we could do something like 'strings beginning or ending with...'

The origin of this request is through a client.

cc @xavijam @rochoa

**Comment by rochoa** [comment]
This is already supported at analysis level. I guess we just need to incorporate it to the UI.

**Comment by saleiva** [comment]
cc @javierarce

**Comment by andy-esch** [comment]
cc @arianaescobar

**Comment by arianaescobar** [comment]
yasss! 

Maybe we could prepare the UI and the RT could implement it @ramiroaznar

**Comment by andy-esch** [comment]
Here's a related one on fuzzier searches: https://github.com/CartoDB/cartodb/issues/9382

**Comment by arianaescobar** [comment]
Don't push it, Andy 😛

j/k, that would be cool too

**Comment by ramiroaznar** [comment]
I have also this one https://github.com/CartoDB/solutions/issues/943 but notice that RT top priority is fixing urgent and client stuff, I am going to try to group all requests from same features into one and pass it to @alonsogarciapablo

**Comment by alonsogarciapablo** [comment]
@ramiroaznar we can open a single issue on this repo with those two enhancements to the "Filter by column" analysis. It might be a "small" enough issue to go through the RT if you think it's important.

**Comment by alrocar** [comment]
Stale issue. Closing 👋
