### ISSUE TITLE
feature request: expand 'other' in category widget

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/cartodb#10071]
Currently it's hard to know the contents of the "Other" category in the Category widgets. It would be more useful if a user could click on Other to get a drop down, where a user could check the less common items to use in the filtering of this widget. The search option requires the user to have some knowledge of the possible categories, which can be an unfair expectation on usability.

cc @xavijam

**Comment by xavijam** [comment]
Moving to deep-insights, where widgets are generated 💋 .

**Comment by xavijam** [comment]
Issue moved to [CartoDB/deep-insights.js #458](https://github.com/CartoDB/deep-insights.js/issues/458) via [**ZenHub**](https://www.zenhub.com/)
