### ISSUE TITLE
add more aggregation options in 'centroid from geometries'

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartodb#10077]
Currently the "Centroid from geometries" analysis only allows for one column to be aggregated. Oftentimes a user will need to aggregate multiple columns for the final output.

Currently this is the option:
<img width="332" alt="screen shot 2016-10-06 at 22 16 08" src="https://cloud.githubusercontent.com/assets/1041056/19176941/bb8ea0d4-8c12-11e6-9fef-2bf17fb7a365.png">

It would be very useful to have the ability to add an arbitrary number of "Aggregate By..." fields for the analysis.

cc @xavijam

**Comment by saleiva** [comment]
can you tell us an usecase? :)

**Comment by ohasselblad** [comment]
This analysis only carries over the_geom and the aggregated variable. I
needed another variable to carry over as well so I could style my shiny new
centroids by size (for the first aggregate) and color by value (for the
second aggregate).

The only workflow I could think to do to accomplish this would be doing the
complete workflow twice--once for each aggregate--and then join them, which
would then require an analysis chain that is hidden/not visualized, and
only referenced in the original analysis == too many gymnastics for the
user!

**Comment by mehak-sachdeva** [comment]
I am trying to make a map with with directional arrows for margin of victory for elections and I need the percentages of victory for parties and the angles for moving the markers along in carto-css after. I currently have polygons so it would really help if I could convert them to centroids while retaining these multiple columns too!

**Comment by saleiva** [comment]
For that we would need the Calculate column one as well, right?

**Comment by mehak-sachdeva** [comment]
So I have all the columns calculated that I would need, but the moment I apply the centroid analysis they go away, since there is no way to select and keep them in the current option. Just an equivalent of this actually:
```
SELECT ST_Centroid(the_geom) the_geom, the_geom_webmercator, cartodb_id, dem, fips, gop, grn, lib, others, state_winner, total_votes, pct_dem, pct_gop, pct_green, pct_lib, county_winner, pct_r, pct_d, angle, d_yn, r_yn FROM election_2016_counties
```

**Comment by ohasselblad** [comment]
An important thing here is the option to use centroid analysis not as an
aggregate function, which may be the moat common use case.

Other functionality is ST_PointOnSurface
