### ISSUE TITLE
category maps fails to generate when all the values are null

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#10079]
- Load this table https://team.carto.com/u/javi/tables/map_points_1/public?redirected=true
- style by color using cartodb_id (it works as expected)
- now style by places

you get a javascript error.

- If you select cartodb_id again the legend is not responsive

```
tracker.js:10 legend of type 'choropleth' couldn't be updated: Cannot read property 'toString' of null
```

![screen shot 2016-10-07 at 10 35 08 am](https://cloud.githubusercontent.com/assets/30147/19183672/bf06b366-8c79-11e6-9aae-7bffda31bc16.png)

**Comment by nobuti** [comment]
The error is fixed in https://github.com/CartoDB/cartodb.js/commit/a9c0d37136586f39bcd784f4a67ec6f78259ce8a. Also some others checks will be added in cartodb side to improve consistency.
