### ISSUE TITLE
Feature request: cap the amount of digits in a legend

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#10086]
I have this elevation numbers in a legend, they're super long numbers and it would be nice if we could cap the amount of digits or round them up.

![screen shot 2016-10-07 at 12 27 27](https://cloud.githubusercontent.com/assets/16247628/19187036/932e62ec-8c89-11e6-8b96-9c7020afe3f4.png)

Because if I add prefixes or suffixes like that, this is how it looks: 

![screen shot 2016-10-07 at 12 29 09](https://cloud.githubusercontent.com/assets/16247628/19187090/e20099f8-8c89-11e6-9afc-4e3f60aa3d5e.png)

Let me know if you'd like that dataset to test it.

**Comment by xavijam** [comment]
That belongs to CartoDB.js, moving it there.

**Comment by xavijam** [comment]
Issue moved to [CartoDB/cartodb.js #1434](https://github.com/CartoDB/cartodb.js/issues/1434) via [**ZenHub**](https://www.zenhub.com/)
