### ISSUE TITLE
bubble maps fails to generate the legend

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#10081]
- load this carto [Untitled Map 3 (on 2016-10-07 at 08.54.04).carto.zip](https://github.com/CartoDB/cartodb/files/515668/Untitled.Map.3.on.2016-10-07.at.08.54.04.carto.zip)
- go to points layer and style size by cartodb_id

it raises a javascript error (same than #10079). 

It can't be reproduced consistently :(

**Comment by nobuti** [comment]
Same issue as #10079.
