### ISSUE TITLE
Bubble legend color sync might lead to confusion

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#10085]
![screen shot 2016-10-07 at 12 17 59](https://cloud.githubusercontent.com/assets/4222826/19186766/20e39b7c-8c88-11e6-80c8-cf145c8771cc.png)

STR:

0. You have a bubble map
1. Add a bubble legend
2. The color of the bubble in the legend is the one in map style
3. Change the color of the map style
4. Legend bubble remains of original color.

I think users expect the legend bubble to follow the map style color. If the user wants to customise the color to something other that map color (weird, but a use case I guess) then the bubble should remain that color no matter what (which is what happens now). However, unless the user modifies the bubble color, it should be synced with the style changes.

Spoke to @nobuti about it and we'd value your input on the matter @saleiva 

Thanks!

**Comment by nobuti** [comment]
![bubble-color](https://cloud.githubusercontent.com/assets/1366843/19210928/97511a02-8d30-11e6-8b92-67dd8f256b1b.gif)

Fixed in https://github.com/CartoDB/cartodb/commit/e7b604b99ec84180d40bf6d34b023b8ec2f5e299

**Comment by gfiorav** [comment]
Working on a Saturday 👎🏻

This fix 👍🏻

Thank you ❤️
