### ISSUE TITLE
Bubble legend breaks when aggregation is reversed (Min. > Max.)

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#10097]
![screen shot 2016-10-07 at 18 36 50](https://cloud.githubusercontent.com/assets/4222826/19198024/19f493cc-8cbd-11e6-8dce-0492666ee842.png)

**STR**

0. You have a map
1. Add bubble legend
2. Reverse aggregation in style (set min higher than max)

**Expected result**

The legend renders correctly.

**Actual result**

Legend breaks (see pic)

cc/ @xavijam

**Comment by nobuti** [comment]
Fixed in https://github.com/CartoDB/cartodb.js/commit/8d137f40f28d902d866a5b97849ad755db51f28d
