### ISSUE TITLE
analysis: switch button for origin <=> target

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#10094]
feature request:

when doing a filter points in polygon, or intersect second layer analysis I have a hard time guessing which should be the origin and the target, and several times I had to recreate the whole "create analysis process"

![screen shot 2016-10-07 at 15 16 35](https://cloud.githubusercontent.com/assets/36676/19196549/4f398bb6-8cb6-11e6-8991-00f2975956ed.png)

it would be great to have a _switch_ button, in order to better change the columns in this analysis, a la google maps

<img width="407" alt="screen shot 2016-10-07 at 17 45 55" src="https://cloud.githubusercontent.com/assets/36676/19196495/242815e6-8cb6-11e6-9ae7-f9a97f3d710d.png">

feel free to close/reassign if necessary

/cc @CartoDB/design

**Comment by saleiva** [comment]
Yes I love it, but I´m afraid that there is also a problem on how we implemented the analysis. @javierarce u think this would be possible right now?

**Comment by saleiva** [comment]
Closing since we will revamp this when supporting multi-geom analysis
