### ISSUE TITLE
Legends should hide when their layer is hidden 

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#10093]
Right now, if I hide a layer, the legend keeps on showing. 

![screen shot 2016-10-07 at 17 45 39](https://cloud.githubusercontent.com/assets/16247628/19196455/f168d33e-8cb5-11e6-97c4-3e6babf0c288.png)

The expected behaviour is that whenever I hide a layer, the legends of that layer should hide as well.

**Comment by xavijam** [comment]
Yeah, totally agree, we haven't taken into account that behaviour. We used to not let the user "interact" with the layer-selector in the previous editor, but know the layer selector "works" in the private Builder and we should take into account.

cc @alonsogarciapablo @nobuti

**Comment by saleiva** [comment]
hey, one thing that might do things easier. What if we just show the layer selector when the user is on the ´settings´section? That is closer to the desired behaviour.

**Comment by xavijam** [comment]
Well, not sure it will make things easier, we would need to bind the change in any case if the user clicks over the layer selector in order to "test" it.

**Comment by xavijam** [comment]
Hey, @arianaescobar, but when a layer is hidden, the legend should keep being visible but with the grey colors.

**Comment by arianaescobar** [comment]
Why? 

I would hide them completely. I also asked @saleiva last week and he said the same.

**Comment by xavijam** [comment]
Let me make the same question, why not? 😂 . In the public view I feel it is super common to hide a layer just a second to see if there is any data below and then click again. Is it harmful to have the legend disabled when the layer is not enabled?.
Adding @piensaenpixel @alonsogarciapablo to the discussion because they implemented in that way.

**Comment by nobuti** [comment]
Also, I find confusing the fact that layer selector affects layers visibility too, but in this case, the legend keeps visible in order to let the user to click again in the layer selector.

**Comment by alonsogarciapablo** [comment]
The way it worked initially was... when the a layer was hidden:
  - Check for that layer in the "layer selector" got unchecked.
  - Legends for that layer got grayed out.

Isn't this the behaviour anymore?

**Comment by alonsogarciapablo** [comment]
Here's an screenshot of what I just described:

![screen shot 2016-10-10 at 16 54 21](https://cloud.githubusercontent.com/assets/390398/19240332/3cd9f78e-8f0a-11e6-8fa7-750776fdf0b9.png)

**Comment by arianaescobar** [comment]
We all (design team) just spoke about it and we agree that the best behaviour is: 

1. If I hide a layer on the Builder, the legend hides as well (not faded). 
2. If I turn off a layer in the Layer Selector, the legend hides (not faded) [only the leyend, not leyend + selector]. If I turn off that layer again on the Layer Selector, the legend appears.

**Comment by xavijam** [comment]
:(

**Comment by saleiva** [comment]
Still think we should only show the layer selector on the ´settings´part. We already have this funcionality on the layer list.

**Comment by arianaescobar** [comment]
Answering your questions:

**Is it harmful to have the legend disabled when the layer is not enabled?.**

It's not that it's harmful, but unnecesary and might even be annoying. if it's not a matter of a few seconds to check something, but that you actually want to hide a layer for a while, having a leyend occupying a premium location on the screen, that's it's faded (so, not in optimal reading conditions)  and not being able to collapse/hide it, it might be too much. Specially with longer legends. 

**but in this case, the legend keeps visible in order to let the user to click again in the layer selector.**

Our proposal it's only hiding the legend, not the layer selector. You can turn the layer and legend back on in any moment by clicking again on the layer selector checkbox. 

**Isn't this the behaviour anymore?** 

We think [this should be the behaviour](https://github.com/CartoDB/cartodb/issues/10093#issuecomment-252649237)

_____

+
I completely agree on only showing the layer selector on the settings + public view @saleiva
