### ISSUE TITLE
Viewer seats tests - bugs

### ISSUE THREAD

**Issue by micagm** [CartoDB/cartodb#10090]
hey guys,

- [x] Wrong redirection for datasets (username.carto.lan...). Not an actual issue. There's a double redirection that is valid (although @javitonino is on it at another PR and we might get rid of it). -> #10102

- [x] When a viewer account clicks on a shared dataset and opens it, he sees the "Create Map" button, which leads to an error when clicking on it. We may want to take that out.
![screen shot 2016-10-07 at 15 26 25](https://cloud.githubusercontent.com/assets/13415884/19191440/bdda4eac-8ca2-11e6-864a-b27424de13f2.png)

- [x] Still inside the dataset view, if you click on "preview", you see again the "create map" button
![screen shot 2016-10-07 at 15 27 00](https://cloud.githubusercontent.com/assets/13415884/19191480/ebce20b8-8ca2-11e6-9a00-b28b51e13fd2.png)

- [x] On another note, the admin shared a few maps with me, and none of them appear in my dashboard
![screen shot 2016-10-07 at 15 38 26](https://cloud.githubusercontent.com/assets/13415884/19191778/215ef0da-8ca4-11e6-9e47-9022781e0215.png)

**Comment by juanignaciosl** [comment]
@micagm I've added the "Wrong redirection for datasets (username.carto.lan...)" issue as well (and added checkboxes :-) ). On it now.

**Comment by juanignaciosl** [comment]
@micagm I can't reproduce the last bug. Could you double check, please? This is a screenshot from that account right now:

![screen shot 2016-10-10 at 13 45 00](https://cloud.githubusercontent.com/assets/932968/19235088/c99c4b42-8eef-11e6-944a-5a56ecc82e44.png)

Maybe you didn't scroll :-) As _you_ don't have maps, the "welcome placeholder" is still there. I'll remove the "welcome placeholder" if you have shared maps though.

**Comment by micagm** [comment]
hey @juanignaciosl you are completely right :o 
I didn't scroll, my bad! Your suggestion to take the welcome message out if there are shared maps sounds good to me, thanks!

**Comment by micagm** [comment]
hey @juanignaciosl , Miguel noticed that from a viewer seat map/dataset if you click on the upper left logo of CARTO, it redirects you to carto.com instead of going back to the dashboard (it was my first issue in my first comment). Looks like that bug still exist.
