### ISSUE TITLE
Custom legends labels no displaying 

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#10096]
![screen shot 2016-10-07 at 18 33 34](https://cloud.githubusercontent.com/assets/4222826/19197891/97171268-8cbc-11e6-8d92-ea8482587949.png)

**STR**

0. You have map
1. Add a custom legend
2. Add a custom label with text
3. Refresh

**Expected result:**

The legend still displays the text label.

**Actual result:**

No text is shown (the color is there though).

cc/ @xavijam

**Comment by nobuti** [comment]
Fixed in https://github.com/CartoDB/cartodb.js/pull/1437/commits/9c89a12892128b09c153056308c8b8c4b9faa0ef

![custom-legend-migration](https://cloud.githubusercontent.com/assets/1366843/19214117/c3016d5e-8d7c-11e6-8939-48b95f320090.gif)
