### ISSUE TITLE
Legends still appearing even tho I'm turning them off in Map Options

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#10091]
There's no error on the Console (nothing happens, really) and the legends are still there even tho I'm turning them off. 

![screen shot 2016-10-07 at 17 27 26](https://cloud.githubusercontent.com/assets/16247628/19195862/8f967046-8cb3-11e6-80ee-4f2b84280bab.png)

I'm not sure if this is the correct repo, sorry if it isn't!

**Comment by xavijam** [comment]
Already being tackle by @gfiorav.

**Comment by arianaescobar** [comment]
That was fast!
