### ISSUE TITLE
modify infowindow html breaks infowindow

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#10105]
1. create a layer and customize a infowindow with html
2. remove top div class ("CDB-infowindow CDB-infowindow--light js-infowindow")

the infowindow breaks.

We should not allow people to change the infowindow container

**Comment by xavijam** [comment]
That's the same behaviour we already have in the previous editor, but it doesn't mean it is the correct one.

**Comment by javisantana** [comment]
Ok, let's keep this for later

**Comment by inigomedina** [comment]
Hey @matallo, could this issue still make sense?

**Comment by matallo** [comment]
it does, not a priority tho
