### ISSUE TITLE
Layer selector titles won't hide if the layer has a legend

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#10106]
![legends](https://cloud.githubusercontent.com/assets/16247628/19233243/9a2d14fa-8ee4-11e6-8899-55f8dc1470e5.gif)

If you add a legend and then turn off the Layer selector on the Map Options, only the checkboxes and names of layers without legends will hide, but the name of the layer with a legend won't.

**Comment by xavijam** [comment]
That's a decision we took with @saleiva. Could we try this behaviour and if we think it doesn't make sense in a few days, change it?

**Comment by arianaescobar** [comment]
Oh. If that's the case, shouldn't we fix the left margin when the layer selector is off then?

**Comment by xavijam** [comment]
That's a ticket (I can't find it now) for that in CartoDB.js, assigned to @piensaenpixel.
