### ISSUE TITLE
Legend does not fade out when disabling view from layer list

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#10109]
### STR

* Add a legend to a layer via changing its style.
* Disable layer view. The layer selector checkbox is disabled, but the legend does not fade out (as you can check in this [embed](https://solutionscdb.carto.com/u/cdbsol-admin/builder/9c060f60-8ee0-11e6-b675-0ee66e2c9693/embed)). 
* In addition, when turning on the checkbox on the layer selector, the layer continues to be on "non-view" status. So it looks like the layer selector and the layer views are not quite well connected.

**Comment by nobuti** [comment]
Related to https://github.com/CartoDB/cartodb/issues/10093
