### ISSUE TITLE
Options for centering map on filtered data / layer data

### ISSUE THREAD

**Issue by urbanphes** [CartoDB/cartodb#10116]
Relate to https://github.com/CartoDB/design/issues/59

**Comment by hacheka** [comment]
Reopening.

When the dataset name is large, it pushes the icon to the right.

![image](https://cloud.githubusercontent.com/assets/1078228/20670981/c5389170-b57b-11e6-9baf-ccca40b104ba.png)

**Comment by xavijam** [comment]
Closing due to it is already live 💋, thanks @hacheka.
