### ISSUE TITLE
sql_wrap in Builder does not include case for NULL

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#10113]
STR:
 1. Import a dataset with a column with some NULL values
 2. Create map with that dataset
 3. Style the layer: Animated, fill by value based on the column with NULLs

sql_wrap looks like:
`"select *, (CASE WHEN "conversion" = 0 THEN 1 WHEN "conversion" = 1 THEN 2  END) as value FROM (<%= sql %>) __wrapped"`
It should be
`"select *, (CASE WHEN "conversion" = 0 THEN 1 WHEN "conversion" = 1 THEN 2 WHEN "conversion" IS NULL THEN 3 END) as value FROM (<%= sql %>) __wrapped"`

**Comment by xavijam** [comment]
Thanks man!
