### ISSUE TITLE
update cartodb

### ISSUE THREAD

**Issue by Baguewi** [CartoDB/cartodb#10129]
I made a cartodb installation, I am cary out an upgrade but for 3.0.0 -> 3.1.0 if I launch the bundle exec rake cartodb:overlays:create_overlays he turned around
rake aborted!
Don't know how to build task 'cartodb:overlays:create_overlays'

(See full trace by running task with --trace)

and for 2.x -> 3.0 .0 
- bundle exec rake cartodb:db:create_default_vis_permissions  pass
  but
- bundle exec rake cartodb:db:populate_permission_entity_id
  rake aborted!
  Don't know how to build task 'cartodb:db:populate_permission_entity_id'

(See full trace by running task with --trace)

Does someone can explain to me the problem I have for this upgrade
I use postgre 9.5 and postegis 2.2.3

**Comment by ramiroaznar** [comment]
Closing this. I recommend posting OS installation problems [on this Google Group](https://groups.google.com/forum/#!forum/cartodb).
