### ISSUE TITLE
Editing SQL in a read only dataset triggers wrong requests

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#10126]
STR
1. User A shares table T with user B in read-only mode.
2. User B opens the dataset and changes the SQL.

Query works, but it also triggers a PUT to layers endpoint and a POST to metrics endpoint. Both fail because user doesn't own the visualization, which I think that is ok, but probably those requests shouldn't be done.

cc @CartoDB/builder-backend @xavijam

**Comment by xavijam** [comment]
Fixed in https://github.com/CartoDB/cartodb/pull/11691. 👏
