### ISSUE TITLE
Geometry Management

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#10124]
Designs are here: https://projects.invisionapp.com/share/HK8NV15DB#/screens/195548487
- [ ] Adding a feature (drawing) - 5
  - Icon and modal to select the type of geometry that will be drawn.
  - While in "drawing" mode... display an "Edit Geometry" form (displays attributes fields)
  - When Geometry is "complete", fill in the geoJSON and enable de Accept button on the form.
  - If "Cancel" is clicked, discard the geometry
  - if "Accept" is clicked, persist GeoJSON and attributtes using SQL API.
  - Reload map.
- [ ] Editing a feature (Form -> UI) - 7
  - When a feature is clicked, determine if it's editable (shouldn't be editable if layer has some   analysis)
  - Display "Edit" button icon next to the point where user has clicked and editable feature
  - When "Edit" button is clicked:
    - Fetch info about the feature using the SQL API
    - Display "Edit Geometry" form with info about the geometry
    - Add editable geometry to the map using CARTO.js
    - Upon clicking "Save":
      - Persist changes using SQL API
    - Remove geometry via CARTO.js
    - Re-load map
- [ ] Editing a feature (UI -> Form) - 2
  - While in "Edit feature mode".
  - When the user modifies the geometry (drag and drop):
    - Update the form
    - Update the GeoJSON of the geometry (debounced)

cc: @xavijam @rochoa @javisantana @matallo

**Comment by xavijam** [comment]
cc @matallo

**Comment by saleiva** [comment]
Closing this since its being tracked in many others
