### ISSUE TITLE
custom baselayer not added to user custom baselayer collection when importing .carto

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#10127]
**steps to reproduce**

- export .carto from a map with a custom basemap (i.e. mapbox)
- import .carto into another account which doesn't have such custom basemap
- enter in basemap panel in layer list

**expected behaviour**

- the custom basemap should be added in the respective custom basemap category

**actual behaviour**

as custom basemaps are currently three different geared parts working together:
- user custom baselayer collection (where the basemap isn't yet)
- custom baselayers collection for panel (which consists in default baselayers from config and custom baselayers from ^^^)
- baselayer in layer collection of map

the baselayer in the map is set indeed (thus we can properly see the map), but the custom baselayer isn't added to the user custom baselayers, and we can't deselect and select it again (see attached)

![screen shot 2016-10-11 at 11 15 17](https://cloud.githubusercontent.com/assets/36676/19265420/64b7e77a-8fa5-11e6-9b78-22a88a0e8182.png)

we should, at the moment of map import, create a custom baselayer for the user

/cc @xavijam

**Comment by xavijam** [comment]
That's a good one, what do you think @CartoDB/builder-backend?

**Comment by juanignaciosl** [comment]
I agree with @matallo .

**Comment by javitonino** [comment]
I agree with creating the custom basemap. We also should try to check if that basemap already exist to avoid duplicating existing custom basemaps (best effort only).

**Comment by matallo** [comment]
totally! in that case if the basemap already exists (checking the classname) there's nothing else to do :)

**Comment by juanignaciosl** [comment]
@matallo could you please specify which tiled layers should be added? For example, which categories should be imported. That logic is currently at frontend :_)

**Comment by matallo** [comment]
**short answer:** "Custom"

**long answer:**

no prob! https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb3/editor/layers/basemap-content-views/basemaps-collection.js#L45-L49

now you mention it is tricky as there's no way to know which of those categories the custom basemap falls under (unless we replicate the frontend logic, god no) so I'd just add it as "Custom" basemap

That category still exists for xyz basemaps (we have the url template from the layer definition), or even add it as if it was an old basemap (with no category) and deal with it as such, for example:

```
layers: [
{
options: {
visible: true,
type: "Tiled",
urlTemplate: "https://stamen-tiles-{s}.a.ssl.fastly.net/watercolor/{z}/{x}/{y}.png",
attribution: null,
maxZoom: 21,
minZoom: 0,
name: "Custom basemap 17",
tms: false,
className: "httpsstamentilessasslfastlynetwatercolorzxypng",
order: 17
},
kind: "tiled",
infowindow: null,
tooltip: null,
id: "a5401323-c0f7-4ee1-9ac6-9f631189445d",
order: 17
}
],
total_entries: 1
}
```

**Comment by juanignaciosl** [comment]
Perfect, that custom categories list is what I needed, thanks!
