### ISSUE TITLE
Error selecting "category" quantification in density maps

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#10134]
STR:
1. Create a new builder map
2. Style the layer
   1. Aggregation: hexabins/squares
   2. Fill -> By value (on agg_value)
   3. Quantification: category

It crashes. The error seems to be in a request to the SQL API to get the common values for categories, it says the `agg_value` column does not exist:

`q=SELECT+*+FROM+(SELECT+agg_value,+count(agg_value)+FROM+(SELECT+*+FROM+walmart_latlon)+_table_sql+GROUP+BY+agg_value+ORDER+BY+count+DESC+LIMIT+11)+__wrapped'`

I guess it should be wrapping with `sql_wrap` for that query, so it can access the aggregated values.

**Comment by xavijam** [comment]
It is true that it fails, but not sure if it makes sense to provide the category way...

**Comment by xavijam** [comment]
Same for heatmap...

**Comment by xavijam** [comment]
Roger = doble con patatas, oido cocina!

**Comment by javitonino** [comment]
Kill it with :fire:

**Comment by inigomedina** [comment]
Close now as it doesn't make sense anymore.

**Comment by ramiroaznar** [comment]
This is still happening:

![image](https://user-images.githubusercontent.com/5215798/34947393-410c5614-fa0a-11e7-929a-3997b3637bf9.png)

Users should not be allowed to chose category fields from the `OPERATION` input or chose `Category` from the STYLE BY VALUE option.

**Comment by VictorVelarde** [comment]
@ramiroaznar Please just confirm the aggregations without Category are Squares, Hexabins AND REGIONS

**Comment by ramiroaznar** [comment]
Yes, it does not make sense to style by categories aggregation values.

**Comment by VictorVelarde** [comment]
All right then, this will be included with the rest of the work on split size/color at CartoDB/cartodb#14017
