### ISSUE TITLE
Log directory creation

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#10136]
There's been a couple of issues lately regarding user creation and log directory. Example: CartoDB/cartodb-postgresql/issues/278. `lib/carto/http/response_logger.rb` creates the logger (`Logger.new(log_file_path('http_client.log'))`) without taking into account that the path might not exist.

Alternatives:
- Make `Carto::Configuration` methods create directories if it doesn't exist.
- Code that creates new `Logger` instances should take into account that (maybe wrapping, even generalizing `CartoDB::Logger` to support random files).

cc @CartoDB/builder-backend @jgoizueta @rafatower @xavijam

**Comment by juanignaciosl** [comment]
A `Carto::Configuration` directory methods are just query methods ("give me X directory") keeping them simple is better. I'll probably try to initialize them at application initializator. cc @CartoDB/builder-backend

**Comment by rafatower** [comment]
I wouldn't add logic to the configuration class either. The app initialization looks like a good place for it.
