### ISSUE TITLE
Image Export fails with 'Private' maps [EDITOR]

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#10130]
### Remember: EDITOR
- Create a new map by dragging a dataset to the Maps dashboard (it will make the new map Private)
- Enter the new map and try to Export an image from it. You will get 

![screen shot 2016-10-11 at 13 06 02](https://cloud.githubusercontent.com/assets/10940006/19268231/7d69fe80-8fb3-11e6-8c24-57fb6b2510b6.png)
- Change the maps privacy to public/with link
- Retry the export. It should work this time
## guess
- An `auth_token` is added to the map template when privacy is set to 'Private'
- The Image Export map instantiation seems to fail due to not including this `auth_token` in the instantiation call
- making the map public removes the token from the template, allowing the Image Export to instantiate the map

**Comment by xavijam** [comment]
Closing since image export is gonna be implemented in Builder.
