### ISSUE TITLE
Torque heatmap displaying as black square

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#10132]
Sometimes, when opening the builder to edit a heatmap map, instead of the heatmap loading, it shows a black square, like this:

![screenshot_20161011_145102](https://cloud.githubusercontent.com/assets/7569673/19270856/5582b79a-8fc2-11e6-824b-a51ed9e23606.png)

This happens in Firefox, about 50% of the time I open a heatmap. No luck reproducing in Chrome.

Just scrolling the map a bit (or changing tabs, resizing the window), fixes the problem and the heatmap displays.

**Comment by xavijam** [comment]
Not priority right now.

**Comment by javitonino** [comment]
This is still reproducible. 

STR, using firefox
1. Create a builder map with a few hundred points
2. Style with heatmap (static is fine)
3. F5 Builder a few times. (cross your fingers beforehand)

It's random in nature, hard to reproduce, and only affects one browser and is fixed by reloading the page, so maybe we don't want to focus too much on it. But maybe worth a look. It seems to be a race condition of some kind, opening the dev tools makes it harder/impossible to reproduce, which may be because the loading is slower.

cc @ivanmalagon
