### ISSUE TITLE
Minimize precission on numbers on legends.  

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10145]
We should use the same approach than in the widgets. Numbers with decimal look very bad,

**Comment by xavijam** [comment]
Moving to cartodb.js.

**Comment by xavijam** [comment]
Issue moved to [CartoDB/cartodb.js #1444](https://github.com/CartoDB/cartodb.js/issues/1444) via [**ZenHub**](https://www.zenhub.com/)
