### ISSUE TITLE
Pagination is being shown over the map sometimes

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10146]
![screen shot 2016-10-11 at 19 43 26](https://cloud.githubusercontent.com/assets/132149/19281559/0ec2b2dc-8feb-11e6-88bb-8b09a37cfe39.png)

STR
- Do a query wich gives you no data
- Go back to the map
- Change the query to one which gives you some data
- The pagination will be shown.

**Comment by ernesmb** [comment]
Those STR worked for me, but I've also found the following, which also make the pagination appear over the map: 

### STR
- Create a map from a dataset (I used `populated places` from data library)
- Apply an AOI analysis
- Open the table preview
- Go back to the map
- Change analysis parameters (radius, for example)
- Run analysis

### current result

pagination appears over the map as soon as the analysis is finished

### expected result

pagination should only appear over the table preview


cc/ @arianaescobar

**Comment by xavijam** [comment]
This should be already fixed, could you check it please?

**Comment by ernesmb** [comment]
yes, it's fixed. _closing_
