### ISSUE TITLE
Deleting a dataset doesnt show the affected maps anymore on the warning modal

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10147]
# SMOKE_MG04

**Comment by xavijam** [comment]
<img width="1069" alt="screen shot 2016-10-12 at 18 58 57" src="https://cloud.githubusercontent.com/assets/132146/19319628/f6798ef8-90ad-11e6-95b1-730625b627c0.png">

It is working for me, from the dashboard, but it is true this behaviour is not implemented in the new dataset view :(.

**Comment by saleiva** [comment]
Yep, sorry. I meant on the new modal.

**Comment by xavijam** [comment]
I'll tell you what we still need in this @hacheka. 💋
