### ISSUE TITLE
No option for color ramp opacity in styling wizard

### ISSUE THREAD

**Issue by makella** [CartoDB/cartodb#10150]
Right now, there is no way to assign transparency color ramp wide when using the styling wizard. 

In addition, even if you click on each color individually for a "Custom color set" the Alpha option is grayed out:

![screen shot 2016-10-11 at 2 20 15 pm](https://cloud.githubusercontent.com/assets/1566273/19287198/f7d26a68-8fbd-11e6-940a-8e83e699b3f4.png)

As of now, it looks like the only two options to adjust the transparency of a color ramp are to go to the CartoCSS view and adjust `polygon-opacity` or change each color in the ramp so the Alpha is no longer grayed out in the styling wizard.

**Comment by xavijam** [comment]
Duplicated one https://github.com/CartoDB/cartodb/issues/8142
