### ISSUE TITLE
Carto parser fails with conditionals in autostyling

### ISSUE THREAD

**Issue by donflopez** [CartoDB/cartodb#10159]
When set autostyling, the maps api fails in some cases like this example:

```
#layer {
 [mapnik-geometry-type=point] {
    marker-fill: #FF6600;
    marker-opacity: 1;
    marker-width: 12;
    marker-line-color: white;
    marker-line-width: 3;
    marker-line-opacity: 0.9;
    marker-placement: point;
    marker-type: ellipse;marker-allow-overlap: true;
  }
 }
```

With the autostyling it is changed to this:

```
#layer { polygon-fill: ramp([type], (#7F3C8D, #11A579), ('FRANCE', 'ESPAÑA')); 

 [mapnik-geometry-type=point] {
    marker-opacity: 1;
    marker-width: 12;
    marker-line-color: white;
    marker-line-width: 3;
    marker-line-opacity: 0.9;
    marker-placement: point;
    marker-type: ellipse;marker-allow-overlap: true;
  }
 }
```

If you remove the conditional [] in the initial styles it seems to work and if you copy and rewrite the variable with the devtools it works too with exactly the same string.

Could it be an encoding error?

**Comment by donflopez** [comment]
It is an encoding error, with the ASCII character [160](http://stackoverflow.com/questions/1461907/html-encoding-issues-%C3%82-character-showing-up-instead-of-nbsp).

It seems to be in the whole project, there is 99 in @CartoDB/cartodb.

We can avoid it, but it is very common... you can put it with alt + space

**Comment by xavijam** [comment]
:joy:, oh god, let's clean that character when apply the CartoCSS or the SQL, but we will need to do it in the autostyle part too, just in case, right?

**Comment by donflopez** [comment]
Ok! I'll do a PR replacing all of them.

**Comment by donflopez** [comment]
This is the PR [#464](https://github.com/CartoDB/deep-insights.js/pull/464)

**Comment by saleiva** [comment]
Remember it also failed when having the '#' char.

**Comment by donflopez** [comment]
@saleiva but the error with the '#' char is in a field of the table, this is a CartoCSS problem.

I can't reproduce the #463 issue as I explained there.
