### ISSUE TITLE
Pulling out analysis method breaks map

### ISSUE THREAD

**Issue by makella** [CartoDB/cartodb#10155]
Hello I'm going through the steps to recreate our website maps and I am running into issues when pulling out an analysis layer. Details below
- I have a dataset (https://team.carto.com/u/mamataakella/dataset/table_29_2_1)
- First, I run Cluster analysis with 6 clusters
- Next, I run Weighted Centroid categorized by `cluster_no` and weighted by `customer_value`
- Next, I pull out Centroid above or below to build the next part of the analysis chain, everything breaks
  - The B Centroid layer is not accessible by clicking on it
  - If I click on the B layer from the original table, I get a blank panel
  - At this point, the only option I have is to go back to my dashboard and start over
    ![styling-basemap](https://cloud.githubusercontent.com/assets/1566273/19314070/ff91574e-9055-11e6-86f6-8f0aa95810f4.gif)

cc: @saleiva @rochoa

**Comment by makella** [comment]
@xavijam happened again when pulling Centroid above.

here is what the console shows and how the layer panel looks
![screen shot 2016-10-12 at 12 30 31 pm](https://cloud.githubusercontent.com/assets/1566273/19322829/db425a88-9077-11e6-8524-0014b34f305d.png)

**Comment by ramiroaznar** [comment]
This has been fixed.
