### ISSUE TITLE
Weirdness when importing a .carto file with a SQL query

### ISSUE THREAD

**Issue by csobier** [CartoDB/cartodb#10156]
I imported a .carto file and it correctly imported the dataset and map. I can open and view the the dataset from my datasets dashboard.  BUT, when I try to view the dataset from the map layer in the Builder, it only opens the profile page of the map creator, not the imported dataset.

The .carto file is incorrectly showing the SQL query, trying to reference the data from the map creators' account, not the imported dataset.
![image](https://cloud.githubusercontent.com/assets/13319925/19316402/45580138-906f-11e6-9183-f0ca39552c9a.png)

Ping me if you want to test with the .carto file.

**Comment by xavijam** [comment]
Take a look @javitonino when you have a gap please.

**Comment by javitonino** [comment]
STR:
 1. Create map from shared dataset
 2. Export it -> it includes the map and the shared dataset
 3. Import it

We import the dataset and the map correctly. However, we are not rewriting the query/table_name of the map layer in this case, so it still points to the shared dataset.
