### ISSUE TITLE
Textfields do not work on full-screen mode in the Chrome browser

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#1016]
When having the fullscreen control and the searchbox on a visualisation and entering the fullscreen mode:

- On Firefox, the searchbox works as expected (text can be entered and searches can be made).

- On Chrome, no text can be entered on the searchbox. Additionally, when being on the visualisation editor and fullscreenmode, the table name cannot be edited (text can be removed but not entered).

- On Safari, same issue as with Chrome.

Investigating, I found out that there could be a possible solution by changing one single character of the webkitRequestFullScreen method: http://stackoverflow.com/questions/15898459/keyboard-keys-not-working-in-chrome-app-when-in-full-screen

**Comment by jqnatividad** [comment]
Can confirm this is still a problem.
In Chrome, the infowindow are offset, in Firefox, it works as expected, and in Safari, it doesn't work at all.
E.g.
http://data.beta.nyc/dataset/inside-airbnb-data/resource/9d64399b-36d6-40a9-b0bb-f26ae0d9c53f?view_id=33b9a800-4ed6-4d41-8f87-494c6c8582eb

**Comment by xavijam** [comment]
Hey jqnatividad, that's other bug, in any case, could you check that problem still happens with last CartoDB.js versions?.

**Comment by xavijam** [comment]
Further to search in fullscreen mode, it is working now, so closing.
