### ISSUE TITLE
Widgets lack geometry data

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#10160]
Building a map with several widgets, widgets apparently decouple from their data and thus show the "Your dataset lacks of geometry data and it's not possible to add a widget" message on the Add Widget left bar. 

Even in this situation widgets still to appear in Builder right bar and seem to work alright. In public view some of them are there but are not rendering data, tho.

[Carto Camp Madrid (on 2016-10-13 at 08.46.37).carto.zip](https://github.com/CartoDB/cartodb/files/526608/Carto.Camp.Madrid.on.2016-10-13.at.08.46.37.carto.zip)

![captura de pantalla 2016-10-13 a las 10 41 11](https://cloud.githubusercontent.com/assets/70603/19342476/4b05b544-9132-11e6-8f2b-0f2d3cc8eee2.png)

**Comment by xavijam** [comment]
I feel it comes from https://github.com/CartoDB/cartodb/pull/10114, but guys, if we don't have steps to reproduce, we are a bit lost.

**Comment by xavijam** [comment]
Already merged the thing described above, let me close this one. If the thing happens again, let's open a new one 💋 .
