### ISSUE TITLE
Shapefiles are downloaded as folders (not zips) in Safari

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#10161]
### STR

* Go to a public dataset.
* Click on download. 
* Select download as `shapefile` format.
* The file is download as a folder, not a zip.

**Comment by xavijam** [comment]
It is not related with the Builder itself, it is related with the export functionality.

**Comment by saleiva** [comment]
arent you sure is not that safari unzips files when downloading them?

**Comment by ramiroaznar** [comment]
@ernesmb @oriolbx could you reply to @saleiva? I have a Linux machine.

**Comment by ernesmb** [comment]
yes, it looks more like that

![screen shot 2016-10-17 at 09 53 20](https://cloud.githubusercontent.com/assets/10940006/19429366/a15a8562-944f-11e6-81b5-957bfa9d9358.png)

closing this
