### ISSUE TITLE
Color dot dissapears when adding a custom label

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#10170]
### STR

* Add legend.

![legend1](https://cloud.githubusercontent.com/assets/5215798/19349906/d19e057a-9155-11e6-87af-534b4f806a35.png)

* Add a custom label.

![legend2](https://cloud.githubusercontent.com/assets/5215798/19349918/dff9e724-9155-11e6-914b-6d51caa72136.png)

The color disappears from the legend dot.

**Comment by xavijam** [comment]
Could you take a look @nobuti please 💋 ?
