### ISSUE TITLE
Launch 'Joined organization' events

### ISSUE THREAD

**Issue by jmartinter** [CartoDB/cartodb#10178]
Launch a new type of segment event ('Joined organization') every time a user joins an org.
If user is the org owner, we should launch the event as well.
Besides the common attributes to all events, we should track the following new ones:
- 'organization_name'
- 'organization_builders'
- 'organization_builders_quota'
- 'organization_viewers'
- 'organization_viewers_quota'
- 'is_org_owner' (true / false if the user owns the organization)

Please, let me know if any doubts

@xavijam, this is not an urgent issue

**Comment by javitonino** [comment]
Hey @jmartinter 

Do you have a list of the default properties you mentioned? I ask before the defaults are not exactly the same for events generated from central than from the box.

**Comment by jmartinter** [comment]
They should be the same :thinking: 
They are the attributes under 'Common attributes to all events'
https://docs.google.com/document/d/1AOdfVMbuXmmS1zhbDq8SxgiewyEGDU0evX1pf3JwQ8Q/edit#heading=h.v8l4j6173xlm
