### ISSUE TITLE
Autostyle makes legend to give an error on this map (bubble map)

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10186]
https://team.carto.com/u/noguerol/builder/6afab814-9190-11e6-ba33-0e3ebc282e83/embed

cc/ @xavijam

**Comment by nobuti** [comment]
Could you share the dataset (or the .carto) please? I see an error thrown by turbocarto: `Failed to process "marker-fill" property: unable to compute ramp, column "no_transactions" does not exist` but I need to dig deeper.

**Comment by saleiva** [comment]
@noguerol can you help @nobuti plz_

**Comment by xavijam** [comment]
I'll assign it myself, when "autostyle" new stuff is done, legend will not fail because it will be disabled.

**Comment by noguerol** [comment]
[1.3 - ATM Network Performance (on 2016-11-21 at 09.56.43).carto.zip](https://github.com/CartoDB/cartodb/files/603223/1.3.-.ATM.Network.Performance.on.2016-11-21.at.09.56.43.carto.zip)
