### ISSUE TITLE
Default avatars not working in local installations

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#10181]
- [ ] Default path at app_config.yml should be /assets/unversioned/images/avatars/.
- [ ] Even though you fix that path, it seems to use some avatars that are no longer being generated (such as `avatar_stars_blue.png`).

cc @CartoDB/builder-backend @xavijam

**Comment by javitonino** [comment]
Pinging @MariaCheca as I think she worked on this recently. Maybe she remembers a bit more about the changes.

**Comment by MariaCheca** [comment]
Yep, this issue has been there for months, we could do something about it.

**Comment by juanignaciosl** [comment]
Default value is something that I can take care of, but I was surprised about the "missing"? default avatars. Let me know if I can help with that.

**Comment by juanignaciosl** [comment]
Closing automatically because of inactivity. If anybody considers that this still important, please reopen and it'll be prioritized.
