### ISSUE TITLE
Torque.js & Firefox animation hangs

### ISSUE THREAD

**Issue by joeyklee** [CartoDB/cartodb#10208]
Hi Carto!

Just wanted to bring attention to a bug I found in firefox using torque. It appears the animations are hanging. The result is correct in Chrome. Thanks!

see: https://joeyklee.carto.com/viz/ccb4fe1e-9449-11e6-a906-0e3ff518bd15/map

![screen shot 2016-10-17 at 11 15 22](https://cloud.githubusercontent.com/assets/3622055/19432802/5aa09d5a-945e-11e6-99ec-4c358db33d77.png)

**Comment by saleiva** [comment]
Hi @joeyklee this should be tracked in the Torque repo https://github.com/CartoDB/torque. We will take a look at it
