### ISSUE TITLE
maps should not published by default

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#10201]
- create a map
- open it in a incognito window 

it shows the embed and it should not show until it's published

**Comment by gfiorav** [comment]
Yup! We should show redirect to 404 or private map error. Which one makes more sense?

**Comment by xavijam** [comment]
404

**Comment by saleiva** [comment]
Hi guys, we need to prioritize this, since is against the new pricing and the way the builder works. @xavijam any chance we have this before the 24th?

**Comment by javitonino** [comment]
Do we also need to remove unpublished map from public pages listings?

Also, this will break embeds when migrating maps from the editor to the builder, and existing builder maps that have not been published.

**Comment by javisantana** [comment]
@javitonino don't worry about the previous maps, if they are published it's fine

**Comment by javitonino** [comment]
Yeah, but if they are not published, the embed should break according to this. And I'm sure we have some non-published (non-mapcapped) maps embedded in the blog right now.

**Comment by javisantana** [comment]
but those maps are still in the editor, right? (a different endpoint I mean)

**Comment by javitonino** [comment]
There are maps made by the builder before we created the publishing feature, that are using the builder embed, but are not published. If we made the simple change of just 404'ing the embed if it has not been published, we will break all the builder embeds before mapcaps were done.

The editor maps are a different problem, in the sense that when you open them with the builder, the old embed will get redirected to the new builder embed until they publish.

**Comment by juanignaciosl** [comment]
Open, important, question then: how should we deal with existing published Builder maps?
a) Force owners to publish them.
b) Run a rake that publish unpublished ones.
c) From now on, mark new maps as "unpublished" somehow by default, and only return 404 for those.
d) Ugly patch hardcoding a date to force publishing. This could be removed in the future, I guess.

As a breaks published and b can raise privacy concerns, I'd do c, although it's redundant. a) can be an option, but we should gather unpublished map owners and tell them to publish.

**Comment by juanignaciosl** [comment]
PS: c) is redundant, but if this change triggers a new "I want _live_ maps back" (@xavijam mentioned it), it fits.

**Comment by juanignaciosl** [comment]
@javisantana FYI b) is being done:
- Rake task mapcapping non-mapcapped builder visualizations.
- Require mapcapping #10212.

**Comment by juanignaciosl** [comment]
This is almost ready, but I have a concern that I'd like to discuss, after talking to @xavijam:

This feels like providing private visualizations to all users, including free ones.

This might've made sense for the Editor, which was mainly a map publishing platform. Nevertheless, we're not only a maps provider platform now, we're mostly an analysis tool. So, with this change, without automatic publishing of new visualizations, we're effectively, de facto, granting private analyses to all users.

Maybe we should only do this for users with private maps enabled.

What do you think, @javisantana , @saleiva ?

**Comment by saleiva** [comment]
Business team did an analysis regarding plans and privacy so even sounding risky, I think we should go for it. Think that if a user wants to share a map (the link or the embed) he will need to publish it, so... 

On the other hand, they dont have private datasets, so its very unlikely that a user will share a map with public data.

**Comment by juanignaciosl** [comment]
Ok! I've also spoken to @javisantana about this, so let's go.
