### ISSUE TITLE
Rename Source and Target layer in the intersection analysis

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#10200]
As reported by @saleiva, some people are having a hard time understanding both names and suggests these options:

- Base Layer
- Intersecting layer

or

- Base layer
- Analyzed layer

**Comment by saleiva** [comment]
I prefer the 1st one

**Comment by javierarce** [comment]
We have two analysis with the same pattern:

- Filter points in polygons
- Aggregate intersection

I'd apply the change to both of them.

Also, I'm afraid that "Intersection layer" is too long:

![screen shot 2016-10-17 at 14 24 02](https://cloud.githubusercontent.com/assets/4933/19437447/c6fb50f0-9475-11e6-9b9b-38f90d6c3576.png)

Would it make sense to call it "Intersect layer"?

cc @ohasselblad

**Comment by javierarce** [comment]
I'll go with "Intersect layer".
