### ISSUE TITLE
Some config for external services fail if they have no value

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#1021]
At *CartoDB*, there are some parts of the code that assume that the configuration keys and values for some external (and *no essential*) services  exists. And they fail with very hard to debug errors if they don't exists.

Also, if they have no value, the applications itself doesn't fail, but it tries to connect with the external service and fail de connection. It's not important fail, but they're some unnecessary and failing connections that the application tries over and over.

Some of the services are:
* *Google Analytic*
* *tumblr*
* *Common data*

**Comment by juanje** [comment]
The main issue here is that at the [application helper](https://github.com/CartoDB/cartodb/blob/master/app/helpers/application_helper.rb) the config keys doesn't get checked.

Here some examples of keys that will crash the app if the parent config key is missing:
```ruby
def frontend_config
    config = {
      ...
      gdrive_api_key:             Cartodb.config[:gdrive]['api_key'],
      gdrive_app_id:              Cartodb.config[:gdrive]['app_id'],
      oauth_dropbox:              Cartodb.config[:oauth]['dropbox']['app_key'],
      oauth_gdrive:               Cartodb.config[:oauth]['gdrive']['client_id'],
      oauth_instagram:            Cartodb.config[:oauth]['instagram']['app_key'],
      oauth_mailchimp:            Cartodb.config[:oauth]['mailchimp']['app_key'],
      ...
      tumblr_api_key:             Cartodb.config[:tumblr]['api_key'],
      ...
    }
...
end
```

For example, if the key `:tumblr` is missing at `app_config.yml`, it will fail trying to access to `[:tumblr]['api_key']` and rails will raise a error `500`.
The same goes for `[:oauth]['mailchimp']`. If that sub-key is missing, it will fail trying to access to its child `[:oauth]['mailchimp']['app_key' ]`.

A posible solution is to define a default value (something the code where this is used will understand that the key is deactivated or `nil` equivalent) and use the method `try`, like is already done for other keys:

[Example](https://github.com/CartoDB/cartodb/blob/master/app/helpers/application_helper.rb#L80):
```ruby
watcher_ttl:                Cartodb.config[:watcher].try("fetch", 'ttl', 60)
```

[Example](https://github.com/CartoDB/cartodb/blob/master/app/helpers/application_helper.rb#L93-L98):
```ruby
    if Cartodb.config[:cdn_url].present?
      config[:cdn_url] = {
        http:              Cartodb.config[:cdn_url].try("fetch", "http", nil),
        https:             Cartodb.config[:cdn_url].try("fetch", "https", nil)
      }
    end
```
