### ISSUE TITLE
Legends showing pretty small values seem broken

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10225]
![screen shot 2016-10-18 at 08 47 01](https://cloud.githubusercontent.com/assets/132149/19467087/88173486-950f-11e6-82b8-914519e098dc.png)

Easy to reproduce when aggregating by provinces (on the style options) and showing the legend for the agg_value_density

cc/ @xavijam

**Comment by xavijam** [comment]
And what do you propose @saleiva? 0 to 0? 0 to 0.1?

**Comment by saleiva** [comment]
Like we do in widgets, we should round, yeah.

**Comment by xavijam** [comment]
Moving to CartoDB.js, where labels are generated.

**Comment by xavijam** [comment]
Issue moved to [CartoDB/cartodb.js #1456](https://github.com/CartoDB/cartodb.js/issues/1456) via [**ZenHub**](https://www.zenhub.com/)
