### ISSUE TITLE
Add new layer modal shows broken styles

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#10229]
![screen shot 2016-10-18 at 10 10 32](https://cloud.githubusercontent.com/assets/4933/19469382/6958ba40-951b-11e6-81f6-088d293056b7.png)

cc: @piensaenpixel

**Comment by xavijam** [comment]
cc @javitonino

**Comment by xavijam** [comment]
I feel it could be happening in the old editor too, take into account please 💋 .

**Comment by javierarce** [comment]
@xavijam: the old editor seems to be unaffected, but thanks for pointing that out!

**Comment by javitonino** [comment]
Backend seems fine for this one, only one geometry type is being returned and the CSS class is correctly applied. Looks like a missing width for the icon or something like that.
