### ISSUE TITLE
Legends for pixel aggregated maps don't work.

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10224]
No data available.

It should be the same than the choropleth legend.

#SMOKE_MG31

cc/ @xavijam

**Comment by nobuti** [comment]
The maps api doesn't return rules for this kind of aggregation, because it doesn't have turbo-cartocss properties. I spoke to @rochoa and we need a further discussion on how we should solve this.

**Comment by javisantana** [comment]
The way we are doing legends is using metadata that relates color/size with values. In the case of heatmaps there is no way to have that mapping so the standard way to do legends (which is the right one) does not work here

The right way to do this kind of maps would be to get the values, normalize and get the mapping.

For me the hacky way to do this would be to set a custom (and fixed) legend in the builder so cartodb.js bascally does nothing (does not update it).

Said this, this would be a hack and will hit in our faces in some months

**Comment by javisantana** [comment]
@nobuti what do you think?

**Comment by nobuti** [comment]
It works for me, I'll work on it with that premise.
