### ISSUE TITLE
CUSTOM legend categories don't get refreshed when deleting an item

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10226]
But they do when dragging an item for example.

![screen shot 2016-10-18 at 08 50 34](https://cloud.githubusercontent.com/assets/132149/19467164/f3d68596-950f-11e6-9856-c1a90e18a4b2.png)

cc/ @xavijam

**Comment by nobuti** [comment]
@saleiva it's working for me, can you reproduce it consistently? STR?
