### ISSUE TITLE
The red dot that signals an error on an analysis is missing the tooltip message

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10222]
#SMOKE_MG39

Updated by @javierarce: 
Image of the original tooltip that is missing now: 

![image](https://cloud.githubusercontent.com/assets/4933/19593562/80d89aba-9781-11e6-884c-dda95fbbd211.png)

**Comment by javierarce** [comment]
Weird, I don't even see the red dot :/

**Comment by saleiva** [comment]
It dissapeared long time ago, there was an issue for that as well

**Comment by javisantana** [comment]
the tooltip shouldn't show a meaningful message?

For example, in "enrich from data observatory" analysis when you run out of quota the message is the default message but it does not help

On the other hand the message we show on the bottom is hard to understand for a user (and the same message should be shown in the tooltip from my point of view) 

![screen shot 2016-10-27 at 6 47 41 am](https://cloud.githubusercontent.com/assets/30147/19754845/6dc50cda-9c11-11e6-9560-88b8b56bdb9f.png)

**Comment by javisantana** [comment]
Looks like the pattern is not really a pattern
![screen shot 2016-10-27 at 10 10 09 am](https://cloud.githubusercontent.com/assets/30147/19759501/a4343bd0-9c2d-11e6-95e9-feacd2fa2f03.png)
![screen shot 2016-10-27 at 10 14 58 am](https://cloud.githubusercontent.com/assets/30147/19759627/4158f39c-9c2e-11e6-97a7-0ad9fbef732d.png)

**Comment by javisantana** [comment]
well, could do:

```
"asdasdasd Exception: test".split(/Exception:/)
["asdasdasd ", " test"]

"Analysis A0 failed: function.....".split(/Analysis [A-Z][0-9] failed:/)
["", " function....."]
```

**Comment by javisantana** [comment]
cc @rafatower what kinf of errors DS are raising? it'd be useful to have a pattern

**Comment by rafatower** [comment]
Typically it's something like
```
"cdb_dataservices_client._cdb_mapzen_isochrone(6): [cartodb_user_a6f0d0fe-4f4f-4217-8150-22b0010fe409_db] REMOTE ERROR: spiexceptions.ExternalRoutineException..."
```
E.g: https://github.com/CartoDB/dataservices-api/issues/122#issue-143010335

**Comment by saleiva** [comment]
+1
