### ISSUE TITLE
Google signup shouldn't require username

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#10242]
STR

1. Go to /signup
2. Leave username empty and press Google signup button.

Username should not be required. It should try with the email username first and fail only if there's a collision (at least, this  was the previous behaviour and I don't know that it has changed on purpose).

cc @MariaCheca @javitonino @xavijam

**Comment by javitonino** [comment]
We didn't change that on purpose, maybe I broke it when we added GH integration.

**Comment by javitonino** [comment]
Broken with some style fixes: https://github.com/CartoDB/cartodb-central/pull/1460
