### ISSUE TITLE
AOI analysis with dissolved parameter does not work

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#10258]
### STR

* Add `Create areas of influence` analysis to a layer.
* Set `BOUNDARIES` as `Dissolved`.
* The analysis does not work. An error appears in the UI saying "The map cannot be rendered" and when opening the console, in the Network tab the error points to that there is not `cartodb_id` (see screenshot below).

![error](https://cloud.githubusercontent.com/assets/5215798/19522600/1db9dc1a-9618-11e6-9ee8-f6e805cd8db6.png)

cc @tbirdman86 @CartoDB/support

**Comment by xavijam** [comment]
I have no idea what's happening with this analysis, could you give us some light here @rochoa?

**Comment by xavijam** [comment]
The error just says that `cartodb_id` is not defined, but it is there, I don't know :(.

**Comment by rochoa** [comment]
It's buggy, the analysis with that option is not returning the cartodb_id for each row. Probably, it was working before because the interactivity was not used by default.

Reference: https://github.com/CartoDB/camshaft/issues/212.

**Comment by xavijam** [comment]
Hey guys, it is related with camshaft, let me close this one, it is already opened there.
