### ISSUE TITLE
sharing a map with a team mate raise instanciation error

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#10259]
- create a map
- keep it private and share with a team mate
- open the map as the team mate

you have access to it but it raises and instanciation error

#SMOKE_MM07

**Comment by javisantana** [comment]
cc @CartoDB/backend

**Comment by javitonino** [comment]
The problem is the visualization is mapcapped, and it doesn't trigger named maps updates.
https://github.com/CartoDB/cartodb/blob/master/app/models/visualization/member.rb#L706 should also return true when changing sharing settings, not just privacy.
