### ISSUE TITLE
Mark visualizations using Google Maps

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#10261]
We need to mark the visualizations using Google Maps in order to avoid migrating those to the builder.

Instead of marking them (as we did with vizjson v2 maps), I propose just checking the basemaps when opening the builder, where the migration decision is made, and just sending the user to the editor if we see google maps in there.
That way we always have the most current data. What do you think? @javisantana @xavijam @juanignaciosl

**Comment by juanignaciosl** [comment]
LGTM as long as we only need to know that when a user opens a visualization in the builder.

I'd add a safety check at `Carto::VisualizationMigrator` though.

**Comment by javisantana** [comment]
sounds fine :D

**Comment by javitonino** [comment]
Filtering based on `Layer.kind == 'gmapsbase'` looks promising. There are a few others which may be google and do not have that kind, but it appears they are from users using custom basemaps with google urls.
