### ISSUE TITLE
Metadata modal cropped

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#10279]
Metadata modal is cropped (it looks like `Modal-inner Modal-inner--grid u-flex u-justifyCenter` div width is wrong).

![screen shot 2016-10-20 at 16 10 05](https://cloud.githubusercontent.com/assets/932968/19563328/d388e15e-96df-11e6-9a17-5655c9de45a1.png)

cc @xavijam

**Comment by xavijam** [comment]
I'm almost sure it is due to last changes over Analysis modal, please @piensaenpixel and @javierarce could you take a look?

**Comment by xavijam** [comment]
Happening the same in the dataset metadata modal.

**Comment by javierarce** [comment]
We pushed some changes for the `.Modal` class (just the height)… so not sure about that, but we'll look into that.

**Comment by piensaenpixel** [comment]
Nah the problem was that we needed to add the overflow for fixing the scrollbar in firefox, but i've just fixed

**Comment by javierarce** [comment]
👌  :)
