### ISSUE TITLE
analysis reported as running when it's actually pending

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#10284]
<img width="977" alt="screen shot 2016-10-20 at 6 41 48 pm" src="https://cloud.githubusercontent.com/assets/30147/19569166/0d77aeb2-96f5-11e6-96f4-3b14c13c1969.png">

**Comment by saleiva** [comment]
This was already fixed, right?

**Comment by javisantana** [comment]
cc @xavijam
