### ISSUE TITLE
Prefix and suffix on legends should be overriden when applying an auto-style

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10289]
If widget contains prefix or suffix, those should also be applied to the legend.

**Comment by xavijam** [comment]
Those data doesn't come from the tiler, that's not possible right now, legends doesn't know anything from widgets or autostyle.

**Comment by saleiva** [comment]
I know, but being a suffix or a prefix, we can know where to put that text, right? Its like with the legend subtitle

**Comment by xavijam** [comment]
That could only happen in the private view, with black magic, but it will not work in the public view. As I have pointed, there is no connection between widgets and legends, and legends don't know if an style has changed due to an auto-style action.

**Comment by saleiva** [comment]
ok to remove from this milestone, but we will need to think how to do this...
