### ISSUE TITLE
Remove links to docs in Builder UI

### ISSUE THREAD

**Issue by asimcox** [CartoDB/cartodb#10285]
Hi Jamon! 

Based on our conversation in this [docs ticket #1102](https://github.com/CartoDB/docs/issues/1102#issuecomment-255146266), we'd like to remove the links to documentation. We audited the Builder for all current links and documented it in [docs ticket #1102](https://github.com/CartoDB/docs/issues/1102#issuecomment-255146266). Once we have more Map Academy content live, we'll do an exercise of adding new links within the Builder UI where appropriate.

cc' @michellechandra @csobier @saleiva

**Comment by xavijam** [comment]
:+1:
