### ISSUE TITLE
Error GPX import

### ISSUE THREAD

**Issue by Vertux** [CartoDB/cartodb#10286]
If I try to import a GPX file it always fails with an **_Unknown (99999)_** error, here is the debug information: 

[debug_gpx_import.txt](https://github.com/CartoDB/cartodb/files/542725/debug_gpx_import.txt)

This path (beside /tmp): **_/tmp/imports/20161020-120352-1of1i2i/jammertal-rundwanderweg_tracks.gpx_** does not exist. But even if I create /imports with all rights (777) I get the same error. I am running a very basic CartoDB installation/configuration, my diagnosis page looks like that:
![bildschirmfoto 2016-10-20 um 20 22 10](https://cloud.githubusercontent.com/assets/10457918/19575327/4b7a8810-970e-11e6-9d33-689071047e93.png)

Here is my **_config/app_config.yml_**:

[app_config.txt](https://github.com/CartoDB/cartodb/files/542749/app_config.txt)

 If you need further information please tell me.

**Comment by saleiva** [comment]
Hi @Vertux as the error says, the best is that you post your question on the Google Group.
Thanks!

**Comment by Vertux** [comment]
Hi @saleiva, I have posted it already on the google groups - [here](https://groups.google.com/forum/#!msg/cartodb/cpiCc92JokU/_6UssUljAAAJ;context-place=forum/cartodb)
