### ISSUE TITLE
Auto-styling on a widget would put the widget name as the title of the legend (if this exists)

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10288]

**Comment by xavijam** [comment]
Same as https://github.com/CartoDB/cartodb/issues/10289, legends don't know anything from autostyle or widgets, it only knows about style or tiler.

**Comment by saleiva** [comment]
This is a must. Makes the legends very difficult to understand. Think that layer name doesn't change and that you can have more than one legend per layer. If legends doesn´t reflect what they are referring to, they make no sense.

**Comment by xavijam** [comment]
:+1:, let's talk about it later but if we need such level of connection between builder styles, widgets, widgets autostyle and legends, we have to rethink the auto-style first.

**Comment by xavijam** [comment]
Hey, we decided to remove legends when autostyle is enabled, so this doesn't make sense for the moment.

**Comment by saleiva** [comment]
That was for v1 on autostyle. Removing this from the actual version, but keeping it open for whenever we attack this properly
