### ISSUE TITLE
Unable to apply/run analysis after error

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb#10280]
## STR

1. Create a map with a points dataset.

1. Add analysis: Calculate clusters of points.

1. Apply.
![screen shot 2016-10-20 at 15 55 19](https://cloud.githubusercontent.com/assets/45346/19562841/1f41d2e2-96de-11e6-930e-12adc327ee4e.png)

1. The analysis fails due to a statement timeout limit.

## Current result

1. There is no error message associated with the failed status.
![2](https://cloud.githubusercontent.com/assets/45346/19563615/f0c19b98-96e0-11e6-8863-45ccead54f64.png)

1. It is no longer possible to apply the analysis with other parameters.
![3](https://cloud.githubusercontent.com/assets/45346/19563631/0550cfa2-96e1-11e6-85f3-6681f3611caa.png)

1. After reloading the builder, the message failed status message appears.
![4](https://cloud.githubusercontent.com/assets/45346/19563987/5006109c-96e2-11e6-9e75-fe05f28d5d76.png)

1. However, it's still not possible to apply an analysis with different parameters.
![5](https://cloud.githubusercontent.com/assets/45346/19564020/721f4aae-96e2-11e6-8d20-e1de8cea17a8.png)

## Expected result

1. I would like to see the failed status error message without reloading.
1. I would like to apply the analysis with different parameters, with and without reloading the builder.

cc @javisantana @xavijam

**Comment by javierarce** [comment]
Thanks for the thorough error report, @rochoa!
