### ISSUE TITLE
Error message for analysis limits exceeded

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/cartodb#10295]
Now we are limiting the maximum space that can be taken by analysis cache tables, so an analysis can fail because of this. The error message that is attached to the node that caused the excess is "Analysis cache space limits exceeded":

``` json
{
  "node_id":"42af7bf7f0992d254b962b8eca49752f71cfe437",
  "status":"failed",
  "updated_at":"2016-10-20T13:38:07.118Z",
  "error_message":"Analysis cache space limits exceeded"
}
```

This is correctly shown in the UI (bottom left corner, for just a few seconds) when the problem occurs or when we reopen a map that was left with this problem:

![image](https://cloud.githubusercontent.com/assets/5909/19592760/7a5d650c-977d-11e6-8edd-678ecdd2a602.png)

Then the analysis is marked as failed with a red dot:

![image](https://cloud.githubusercontent.com/assets/5909/19592840/e7162274-977d-11e6-9cc3-9d584650afee.png)

But if we open an embed for a map that has failed no error message is shown (and presumably it isn't either if the problem surfaces while an embed is being rendered, I have to check this), and the affected layers are just not shown.

In any case, the error message will be puzzling for the user (and he/she may miss it), so we should handle this case specially: we should have a more visible explanation of the problem (possibly a modal) in the builder and should also handle this in embeds.

/cc @javisantana

**Comment by javisantana** [comment]
@javierarce @xavijam this is the error I was talking about where you just can contact support (for now, we will change this)

**Comment by jgoizueta** [comment]
FYI: you can force this happening by changing the analysis cache factor (which multiplied by the user's nominal quota gives the space allotted for analysis cache tables), for example setting it to 0 will always trigger the error: (you'll need a priviledged users for this)

```sql
SELECT cartodb.CDB_Conf_SetConf('analysis_quota_factor', '0');
```

But be aware that for organizations the factor will affect all of the users of the org, so take care with `team`!
