### ISSUE TITLE
Changing a column type doesn't regenerate styles

### ISSUE THREAD

**Issue by nobuti** [CartoDB/cartodb#10296]
## STR
- Style a string column by color. The legend generated is a category one.
- Next, open the dataset view and change the type of that column to number.
#### Expected:

The styles are reset by this change of column's type, so the legend is generated properly too.
#### Actual behaviour:

Nothing changes. You need to force a style change manually in order to generate a choropleth.

Not sure if this a bug or a a feature, because actually the legend is kind of correct, because it's like you were generating a category quantification legend. In fact, if you open the fill component again, it shows it so.

What do you think @xavijam @saleiva?

**Comment by alrocar** [comment]
Stale issue. Closing 👋
