### ISSUE TITLE
Add tip explanation to inner and outer type of join

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10292]
On the analysis UI

**Comment by javierarce** [comment]
We don't have "outer join", right?

What about something like this?

For inner: 
> Returns the result of #1 intersecting #2 (i.e. the inner part of a Venn diagram intersection)

For left: 
> Returns all rows from #1, with the matching rows in #2 or NULL when there is no match.

![screen shot 2016-10-21 at 10 51 06](https://cloud.githubusercontent.com/assets/4933/19592493/56bc01a4-977c-11e6-83c7-63f49856d42b.png)
![screen shot 2016-10-21 at 10 51 12](https://cloud.githubusercontent.com/assets/4933/19592495/570e42d4-977c-11e6-92e1-7ac3266d3c2a.png)

/cc @xavijam @javisantana
