### ISSUE TITLE
Fix legends margins

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10291]
As you can see in the screenshot, margins are decompensated now.

![screen shot 2016-10-21 at 08 06 09](https://cloud.githubusercontent.com/assets/132149/19588531/aa313702-9766-11e6-95d1-bdb61e66a950.png)

![screen shot 2016-10-21 at 08 27 18](https://cloud.githubusercontent.com/assets/132149/19588776/3bdbaa24-9768-11e6-9856-0136d11ebb56.png)

**Comment by piensaenpixel** [comment]
![image](https://cloud.githubusercontent.com/assets/1214201/19684322/e00521c4-9ab6-11e6-8d93-247430c99f3f.png)

**Comment by piensaenpixel** [comment]
Fixed :)
