### ISSUE TITLE
Changing a map from LINK to PUBLIC makes it un-openable --> error 400

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb#10304]
Like this one: https://team.carto.com/u/abel/builder/be1cf860-0d66-42c5-9470-fb99f93cc086/embed

**Comment by javitonino** [comment]
@AbelVM We are now hiding non-published maps. Just publish it and it should show up again. The fact that it worked as link privacy is a bug (fixed in #10260). There is also a ticket to improve user feedback to the user: #10243

**Comment by AbelVM** [comment]
Roger that! Thank U!

**Comment by javitonino** [comment]
Should be fixed now.
