### ISSUE TITLE
Wrong brand when using Google Auth

### ISSUE THREAD

**Issue by santisaez** [CartoDB/cartodb#10312]
We're showing the old logo and "CartoDB" string when using Google Auth:

![google_auth](https://cloud.githubusercontent.com/assets/223956/19644194/c8037d1e-99ee-11e6-9d67-54b4a038f633.png)
# SMOKE_OB02

**Comment by andrewbt** [comment]
+1 just saw this too

**Comment by saleiva** [comment]
@MariaCheca assuming you know how to change this easily. If not, @juanignaciosl help us here!

**Comment by juanignaciosl** [comment]
I have the credentials, if @MariaCheca gives me a suitable 120x120 logo I'll change it.

**Comment by juanignaciosl** [comment]
Changed

https://cloud.githubusercontent.com/assets/132149/5737393/7ae5665e-9be0-11e4-8a71-c2a3aae465f2.png

to

https://cloud.githubusercontent.com/assets/132149/5737393/7ae5665e-9be0-11e4-8a71-c2a3aae465f2.png

![screen shot 2016-11-08 at 11 44 18](https://cloud.githubusercontent.com/assets/932968/20096133/bf5fd264-a5a8-11e6-8565-639c6b845fea.png)

**Comment by javitonino** [comment]
It still shows "CartoDB" (don't know if that's changeable)

**Comment by juanignaciosl** [comment]
![screen shot 2016-11-08 at 11 47 24](https://cloud.githubusercontent.com/assets/932968/20096232/39710c58-a5a9-11e6-8d79-43f66fb83e3b.png)

Heavy caching, it's changed now:

![screen shot 2016-11-08 at 11 47 41](https://cloud.githubusercontent.com/assets/932968/20096233/3cb143ba-a5a9-11e6-9e52-d0dc9b1c2af8.png)

/shrug

**Comment by javitonino** [comment]
\o/

**Comment by MariaCheca** [comment]
Oh wait @juanignaciosl, did you used the link to the s3 resource or another one uploaded to github?
