### ISSUE TITLE
'JOIN from 2nd layer' analysis breaks when changing parameters

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#10310]
An already applied 'JOIN from 2nd layer' analysis breaks after any parameter is changed from the UI.

**Use this file to reproduce
[p_places_JOIN_w_borders (on 2016-10-24 at 10.26.39).carto.zip](https://github.com/CartoDB/cartodb/files/547506/p_places_JOIN_w_borders.on.2016-10-24.at.10.26.39.carto.zip)**

## STR

1 - Create a map from 'populated places' dataset
2 - Add 'join columns from 2nd layer' analysis
3 - chose the following params: 
  - input 2: world borders
  - foreign keys: 
    - populated places: `adm0_a3`
    - world borders: `iso3`
  - columns: 
    - populated places: `cartodb_id`, `name`, `pop_max`
    - world borders: `name`, `area`, `pop2005`

4 - Apply the analysis. **NOTE: using the `.carto` file attached gets you directly to this point**

----

5 - Change any parameter in the analysis configuration: join type, columns selected on any input dataset, whatever
6 - Apply the changes: the map breaks with a PostGIS error: 
```
"Postgis Plugin: ERROR:  transform: couldn't project point (180 -90 0): tolerance condition error (-20)↵↵in executeQuery Full sql was: 'SELECT ST_AsTWKB(ST_Simplify(ST_RemoveRepeatedPoints("the_geom_webmercator",1e-05),1e-05,true),5) AS geom FROM (SELECT ST_Transform(the_geom, 3857) the_geom_webmercator, cartodb_id, left_cartodb_id, name, pop_max, right_name, right_area, right_pop2005↵FROM (SELECT _cdb_analysis_right_source.cartodb_id as cartodb_id, _cdb_analysis_right_source.the_geom as the_geom, _cdb_analysis_left_source.cartodb_id as left_cartodb_id, _cdb_analysis_left_source.name, _cdb_analysis_left_source.pop_max, _cdb_analysis_right_source.name as right_name, _cdb_analysis_right_source.area as right_area, _cdb_analysis_right_source.pop2005 as right_pop2005↵FROM↵  (SELECT * FROM ernestomb.populated_places) AS _cdb_analysis_left_source↵  INNER JOIN↵  (SELECT * FROM world_borders_1) AS _cdb_analysis_right_source↵ON _cdb_analysis_left_source.adm0_a3 = _cdb_analysis_right_source.iso3) _cdb_analysis_query) as cdbq WHERE "the_geom_webmercator" && ST_MakeEnvelope(-20037508.3,20037508.25881302,-20037508.25881302,20037508.3,3857)'↵"
```

![screen shot 2016-10-24 at 12 44 54](https://cloud.githubusercontent.com/assets/10940006/19642879/b646df1e-99e7-11e6-9a94-6f73002e2dc8.png)

cc/ @saleiva @CartoDB/support

**Comment by xavijam** [comment]
I feel this is a problem with the Maps API, cc @dgaubert before moving it there.

**Comment by dgaubert** [comment]
This is a well known [bug](https://github.com/CartoDB/camshaft/issues/134), those datasets that have some geometry near Antarctica (y = -90) cannot be projected. The fix is `cartodbify` analyses tables.

**Comment by xavijam** [comment]
Ok, closing and leaving in camshaft, thanks @dgaubert 💋 .
