### ISSUE TITLE
Auto-style is wrong when coloring with a category widget and numeric values

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10317]
STR,

- Take a points dataset.
- Create clusters
- Add a widget to the clusters node
- Make it a category widget.
- Use the auto-style

#SMOKE_WD23

**Comment by xavijam** [comment]
That's not related with the Builder, it is related with deep-insights.

**Comment by xavijam** [comment]
Issue moved to [CartoDB/deep-insights.js #472](https://github.com/CartoDB/deep-insights.js/issues/472) via [**ZenHub**](https://www.zenhub.com/)
