### ISSUE TITLE
Improve feedback when not having quota

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10323]
Ther are two scenarios that we are not controlling now.
a. User has not quota assigned. We should be more direct and say something like: "To get access to the Data Observatory/Routing/whatever function, [contact our team](link to contact)"

b. User has consumed all quota assigned, but has $0/1000 price for extra credits: "You have consumed all your credits during this billing cycle. Contact us to get some more".

Right now, the error is quite confusing :)

![slack-imgs com](https://cloud.githubusercontent.com/assets/132149/19675512/0506932c-9a8f-11e6-8ea9-754d0c7e260c.jpeg)

**Comment by xavijam** [comment]
Agree.
