### ISSUE TITLE
Carto logo in Builder map-view redirects to website instead of user's dashboard

### ISSUE THREAD

**Issue by micagm** [CartoDB/cartodb#10329]
When sub-users member of an org open a map with the Builder, the toolbar on the left has the Carto logo at the top. On clicking on that logo, a new tab opens in the browser to carto.com

![screen shot 2016-10-25 at 11 26 06](https://cloud.githubusercontent.com/assets/13415884/19681172/c4210af8-9aa8-11e6-8f85-ff494a092c09.png)

However, when an admin, or a user without an org attached, clicks on the same logo while in the map-view (Builder), it takes him to his account's dashboard (expected behaviour).

**Comment by xavijam** [comment]
Issue moved to [CartoDB/deep-insights.js #474](https://github.com/CartoDB/deep-insights.js/issues/474) via [**ZenHub**](https://www.zenhub.com/)
