### ISSUE TITLE
Legend fields do not change when changing the field on the Style 

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#10331]
### STR

* Create a map with a point layer.
* Click on layer `STYLE`.
* Set the marker width or fill to `BY VALUE`. Select a field. Now the legend is showing the field name.
* Select a different field. The legend is still showing the old field name.

### Expected result

* The legends should show the new field name.

cc @CartoDB/support 

#SMOKE_MG27
#SMOKE_MG28

**Comment by nobuti** [comment]
@ramiroaznar you mean the legend's title right?

**Comment by ramiroaznar** [comment]
@nobuti Yes!

**Comment by ramiroaznar** [comment]
![legends](https://cloud.githubusercontent.com/assets/5215798/19683124/3e6d01f6-9ab1-11e6-9a15-2b937f56449a.gif)

**Comment by ramiroaznar** [comment]
![legend](https://cloud.githubusercontent.com/assets/5215798/19685306/2e0b431c-9abc-11e6-8605-76af9056b61e.png)
