### ISSUE TITLE
'map instantiation failed' after running 'enrich from data observatory'

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/cartodb#10337]
## Steps to reproduce

* Import this dataset: eschbacher.cartodb.com/api/v2/sql?q=SELECT%20*%20from%20lightrailstations&format=geojson&filename=lightrailstations
* Create a map from it
* Add analysis "Enrich from data observatory"
    * Call the column `num_carfree`
    * Select `United States`
    * Select `Transportation`
    * Select `Car-free households`
* Analysis seems to complete

## Result

A couple of different things can happen now. 

1. The map is not rendered (the points go away)
2. Clicking on table view, there's a spinner which doesn't go away unless the page is reloaded
3. Reloading the page, and checking the table view, the table is intact and the new column has reasonable/expected values
4. Checking the console, you see this:
<img width="748" alt="screen shot 2016-10-25 at 09 30 56" src="https://cloud.githubusercontent.com/assets/1041056/19688010/c6c639ee-9a95-11e6-9625-7c4aedd1e7ef.png">
5. The map is never drawn

cc @xavijam

**Comment by xavijam** [comment]
Could you check the error before taking a look please? If you need help I feel @oriolbx or @ernesmb can help you.

**Comment by ohasselblad** [comment]
Is this sufficient, or would you like something else?

<img width="1163" alt="screen shot 2016-10-25 at 09 47 13" src="https://cloud.githubusercontent.com/assets/1041056/19688546/3b3f48b8-9a98-11e6-80bc-bc6d4736a857.png">

**Comment by xavijam** [comment]
No, that's not the proper error, could you check network tab and get more details?

**Comment by ohasselblad** [comment]
Error I see through maps api is:

```
Postgis Plugin: ERROR:  transform: couldn't project point (-176.85 -90 0): tolerance condition error (-20)↵↵in executeQuery Full sql was: 'SELECT ST_AsTWKB(ST_Simplify(ST_RemoveRepeatedPoints("the_geom_webmercator",10),10,true),-1) AS geom FROM (SELECT ST_Transform(the_geom, 3857) the_geom_webmercator, cartodb_id, pid, name, address, autos, racks, lockers, district, shelters, carfree↵FROM (select * from analysis_a08f3b6124_8296ac7b90ed4d19e8d75a2ae0a8fc9b39f856dd) _cdb_analysis_query) as cdbq WHERE "the_geom_webmercator" && ST_MakeEnvelope(-11745619.51441332,4769670.564994998,-11696699.81631081,4818590.263097512,3857)'↵```

**Comment by ernesmb** [comment]
That error message is similar to the one from #10310

**Comment by ohasselblad** [comment]
After filtering out the offending point, everything runs as expected.

**Comment by xavijam** [comment]
If it a well known bug in camshaft -> https://github.com/CartoDB/camshaft/issues/134. Closing this one, thanks @ohasselblad for the feedback and report 💋 .
