### ISSUE TITLE
Lack of information about how CartoCSS and legends work

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#10349]
It would be great that legends can be generated via scenario 2. But if it is not possible more information (modals, docs...) would be needed to let users be aware of this issue.
### Scenario 1
- You use the wizard to size points and the legend shows up,
- next, you modify the Turbo Carto,
- the legend updates.
### Scenario 2
- You go straight to CartoCSS editor and write Turbo Carto for marker-width,
- you now don’t have the option to add a legend for size.

cc @javisantana @makella

**Comment by xavijam** [comment]
The only thing I feel we can do is creating an academy, or a video, blog post or improve the onboarding, what do you think @saleiva?

**Comment by saleiva** [comment]
If using turbo carto, couldn't we generate the legend anyway?

**Comment by ramiroaznar** [comment]
I think we can close this.
