### ISSUE TITLE
Wrong brand when connecting dataset from Dropbox

### ISSUE THREAD

**Issue by hacheka** [CartoDB/cartodb#10346]
We show the old branding when connecting Carto to Dropbox.

1) New dataset
2) Click on Dropbox icon
3) Click on Connect
#SMOKE_DS04

![screen shot 2016-10-25 at 17 11 03](https://cloud.githubusercontent.com/assets/1078228/19691978/83657688-9ad6-11e6-9893-e4da4ee9584b.png)

**Comment by juanignaciosl** [comment]
Done. Application name can't be changed, though.

**Comment by juanignaciosl** [comment]
Many thanks to @MariaCheca , The Asset Provider :-)
