### ISSUE TITLE
Confirmation after assigning a second animated layer seems inverted

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#10345]
STR

0. Create a map with 2 points layer.
1. Set an animated layer.
2. Try to set the other layer as animated, This confirmation message appears:

![screen shot 2016-10-25 at 17 00 20](https://cloud.githubusercontent.com/assets/932968/19691582/0407bd3e-9ad5-11e6-9de5-487c92c24e51.png)

If you press "continue", nothing seems to happen. Nevertheless, if you press "cancel", the second layer becomes the torque one, resetting first one styles.

cc @matallo @xavijam

**Comment by xavijam** [comment]
I'm 99% sure this is due to the thing we changed in the infobox about the buttons and the actions. cc @MariaCheca and @nobuti.

**Comment by nobuti** [comment]
On it!
