### ISSUE TITLE
ADD hover tip for tracts parameter on AOI Analysis

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10352]
To explain what they are and how they work

**Comment by javierarce** [comment]
@ohasselblad could you help me figuring out how to explain the tracts?

**Comment by ohasselblad** [comment]
Sure, what's the word/character limit?

**Comment by ohasselblad** [comment]
Tracts: "Number of AOIs evenly spaced between 0 and RADIUS"

**Comment by javierarce** [comment]
Regarding your question, around 90/95 characters would be ok… but that description is great :)

**Comment by ohasselblad** [comment]
Great :) Are you going to be add hover tips to the distances like km (kilometers), mi (miles), etc. just in case someone doesn't know?

**Comment by javierarce** [comment]
Mmm… I hadn't thought of that, they seem pretty obvious to me… do you think it would help our users?

**Comment by ohasselblad** [comment]
it's obvious to me. One thing that could make it more obvious is if "Units" were changed to "Distance". If there's not enough space, maybe "Dist." with a hover over for 'distance'?

**Comment by javierarce** [comment]
Oh, but we already have "Distance" next to the acronyms :)

![screen shot 2016-11-07 at 17 46 43](https://cloud.githubusercontent.com/assets/4933/20066552/3749e4a0-a512-11e6-9acc-a8cbc3702179.png)

**Comment by javierarce** [comment]
Now that I think of that, maybe this would make more sense, right?

![screen shot 2016-11-07 at 17 49 22](https://cloud.githubusercontent.com/assets/4933/20066639/870a354e-a512-11e6-87cd-26928c98ec58.png)

**Comment by ohasselblad** [comment]
haha, exactly what i was writing! perfect now 👍

**Comment by javierarce** [comment]
Haha, sorry then! I'll make the change… thanks!
