### ISSUE TITLE
Default number of bins for all BY VALUE numeric field options should be 5

### ISSUE THREAD

**Issue by makella** [CartoDB/cartodb#10357]
If possible, please set the default number of bins to **5** for all BY VALUE numeric column options.

Every default for classification would be best at Quantiles, **5 bins**.

**Comment by javierarce** [comment]
Wow, that's a bunch of smoke right there! :D A solution is on the way!

**Comment by makella** [comment]
:) awesome!

**Comment by makella** [comment]
@javierarce thank you, thank you... this is great.
