### ISSUE TITLE
Minimum Symbol Size for Points > BY VALUE is too small

### ISSUE THREAD

**Issue by makella** [CartoDB/cartodb#10358]
The default minimum symbol size for 'bubble' map ranges is too small.

If possible, please set the minimum to 5 px. 2px is too small to see on most maps.

Related discussion:
https://github.com/CartoDB/cartodb/issues/8853
# SMOKE_MG20
# SMOKE_MG21

**Comment by makella** [comment]
@hacheka thank you!!

**Comment by makella** [comment]
Just to be clear, this wasn't a request to change the initial simple point size.

This request is specifically for style by value > size for point symbols.

**Comment by hacheka** [comment]
It's clear. The thing is that when modifying the minimum size for points when using a range value I affected also the minimum for a fixed one. They're related in the codebase.

I'll dig deeper in the code to see if we can set different minimum values for each one, fixed and by value.

Reopening the issue...

**Comment by makella** [comment]
Wanted to add an additional comment here about why this is important.

Our default `line-width` is 1 so if you have a 2px marker, you really lose those points, particularly if they are colored by value and/or on Positron. 

For example, you can't see the lowest classed points on this map... i have highlighted a couple of them but there are many more if you look closely:

![screen shot 2017-03-21 at 10 48 51 am](https://cloud.githubusercontent.com/assets/1566273/24141490/df0e0a2a-0e23-11e7-95d2-ac6b95458899.png)

**Comment by ramiroaznar** [comment]
Fixed.
