### ISSUE TITLE
AOI's 'time' analysis fails with REMOTE ERROR

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#10355]
## STR
- Create a map from a point dataset
- add AOI analysis
- use 'Time' settings. I have managed to reproduce it with several combinations, both `car` and `walking`, different times and number of tracts... I'd say the specifics are not relevant
![screen shot 2016-10-25 at 18 09 20](https://cloud.githubusercontent.com/assets/10940006/19694073/2e34fabe-9ade-11e6-8871-7ec8147f5fa6.png)
- apply the analysis and wait
- after some time running, it will fail with this error: 
```
"cdb_dataservices_client._cdb_isochrone(6): [cartodb_user_a6f0d0fe-xxxx-xxxx-xxxx-22b0010fe409_db] REMOTE ERROR: spiexceptions.ExternalRoutineException: spiexceptions.ExternalRoutineException: Exception: Error trying to get mapzen isolines"
```

**Comment by rafatower** [comment]
what's the provider?

**Comment by rafatower** [comment]
never mind: I see in the trace it is mapzen

**Comment by rafatower** [comment]
This could be a duplicate of https://github.com/CartoDB/dataservices-api/issues/293

**Comment by ethervoid** [comment]
Yup, looks like the same problem

**Comment by ethervoid** [comment]
Should be fixed by now @ernesmb

**Comment by ernesmb** [comment]
![screen shot 2016-10-26 at 17 09 58](https://cloud.githubusercontent.com/assets/10940006/19731903/3fc02fc6-9b9f-11e6-957a-2f2a3655fc33.png)

fixed! closing :)
