### ISSUE TITLE
Deleting a layer incorrectly resets styles

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#10366]
# STR
1. Import [carto.zip](https://github.com/CartoDB/cartodb/files/552918/carto.zip). You get something like:

![screenshot_20161026_115028](https://cloud.githubusercontent.com/assets/7569673/19721450/8ac6d4ac-9b72-11e6-855e-d5b5bf0e5988.png)
1. Drag A1 to a new layer, you will see the points + the centroids

![screenshot_20161026_115044](https://cloud.githubusercontent.com/assets/7569673/19721453/8fcf7080-9b72-11e6-9e85-027769f2ade1.png)
1. Delete layer B
# Result

The recently deleted layer (points) is displayed

![screenshot_20161026_115058](https://cloud.githubusercontent.com/assets/7569673/19721468/9f9e0d1e-9b72-11e6-9643-e649697cf1bc.png)

After refreshing the builder (or touching some styles) it goes back to working as expected.
# Expected

The original layer (centroids) is displayed

cc @xavijam

**Comment by javitonino** [comment]
Also, while the incorrect layer is displayed, if you mouse over the map, you get tons of:

map-cursor-manager.js:39 Uncaught TypeError: Cannot read property 'cid' of undefined

**Comment by xavijam** [comment]
Related: https://github.com/CartoDB/cartodb/issues/10542
