### ISSUE TITLE
Type guessing on import for GEOJSON

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#1036]
We should contact the same guy that helped us with csv.
cc/ @javisantana

**Comment by saleiva** [comment]
So, @rafatower ?

**Comment by rafatower** [comment]
Current status:
-[x] the gdal feature is implemented and the `ogr2ogr2` binary containing it is in production.
-[ ] the ruby code must make use of it, pretty much like for csv

@javisantana, what's exactly the expectation of this feature? according to [doc](http://trac.osgeo.org/gdal/wiki/rfc50_ogr_field_subtype) this is the only change regarding GeoJson:
> Changes in drivers
> GeoJSON: can read/write OFSTBoolean

**Comment by javisantana** [comment]
guessing on boolean and dates

**Comment by rafatower** [comment]
The [geojson specification](http://geojson.org/geojson-spec.html#geojson-objects) only mentions these types:
> The value of the type member must be one of: "Point", "MultiPoint", "LineString", "MultiLineString", "Polygon", "MultiPolygon", "GeometryCollection", "Feature", or "FeatureCollection". The case of the type member values must be as shown here.

Currently dates are imported correctly. Working my way through the code to enable `ogr2ogr2` for geojson and boolean values.

**Comment by rafatower** [comment]
I'm getting this error with `ogr2ogr2`:
```
2015-01-20 14:57:51 UTC: ogr2ogr output:    ERROR 4: Unable to open EPSG support file gcs.csv.
Try setting the GDAL_DATA environment variable to point to the
directory containing EPSG csv files.
ERROR 4: Unable to open EPSG support file gcs.csv.
Try setting the GDAL_DATA environment variable to point to the
directory containing EPSG csv files.
Failed to process SRS definition: EPSG:4326

2015-01-20 14:57:51 UTC: ogr2ogr exit code: 256
```
I think that means we lack one file in the deb package

**Comment by rafatower** [comment]
To recap:
- I had some problems with the package, but managed to fix it. The work is done [here](https://github.com/rafatower/gdal/compare/rafatower:ogr2ogr2_2.0.0+svn.28306-precise1ubuntu1...ogr2ogr2_2.0.0+svn.28306-precise1ubuntu2)
- The new package is uploaded to [launchpad](https://launchpad.net/~cartodb/+archive/ubuntu/gis-testing) but needs a fix in gdal@trunk. Package shall be easy to update once it is fixed.
- The bug has been reported to our gdal contact and is a BLOCKER
- Short PR for ruby code https://github.com/CartoDB/cartodb/pull/1906 - DONE

**Comment by rafatower** [comment]
And released!
