### ISSUE TITLE
Editor allows you to create two Torque layers

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#10367]
STR
1. Create a new map with two layers _in the editor_.
2. Click the Torque wizard for the first layer.
3. Click the Torque wizard for the second. Although the wizard displays a "only one Torque layer is allowed" message, once you click, layer becomes a (second) Torque layer.

cc @nobuti @MariaCheca

**Comment by nobuti** [comment]
Editor? not Builder?

**Comment by juanignaciosl** [comment]
Yes, _editor_. I haven't been able to reproduce it in the builder. _Yesterday_ I managed through builder + export + import, but it might've been related to #10345. Today I tried to break the Builder Torque assignment but I didn't succeed.

**Comment by inigomedina** [comment]
Hey @juanignaciosl, does this issue still make sense?

**Comment by juanignaciosl** [comment]
Well... it still happens and it might be a problem (we don't support having two torque layers in a map). But it's Editor. If we're fixing Editor bugs, we should fix it. Otherwise, we can ignore it. Anyway, after one year and a half, it's obviously not a priority.
