### ISSUE TITLE
Scrollbars in builder (Firefox)

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#10375]
Using Firefox you get scrollbars on the builder. I am pretty sure, this has only started happening recently. Embed is OK.

![screenshot_20161026_141817](https://cloud.githubusercontent.com/assets/7569673/19725660/21045cd2-9b87-11e6-97a3-51a6a26c6700.png)

cc @xavijam

**Comment by piensaenpixel** [comment]
under control :)

**Comment by piensaenpixel** [comment]
Fixed via https://github.com/CartoDB/cartodb/pull/10384
