### ISSUE TITLE
Changing the join analysis parameters does not reset styles

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#10373]
# STR
1. Import this map [join.zip](https://github.com/CartoDB/cartodb/files/553064/join.zip) which does a join between a point layer and a polygon layer. It is currently styled by polygon.
2. Got to A1, and set "Geometry from" to  "A0 Source (ec_kvy)"
# Expected

Styles are reset to an appropriate style for points.
# Actual

Styles are not reset.

**Comment by xavijam** [comment]
Fixed with https://github.com/CartoDB/cartodb/pull/10462. 💃
