### ISSUE TITLE
Custom Legends are not persistent

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#10390]
### STR

- Create a new map 
- Use `STYLE` tab to assign some "by value" styles. The legend should appear
- Go to `LEGEND` tab
- Select "custom" and apply some changes (labels, title, etc)
- Select the default legend (or "none")
- Select "custom" again ==> **editions are gone**

**Comment by nobuti** [comment]
@xavijam the custom legend inherits colors from style by default, is this still valid?

**Comment by xavijam** [comment]
with those steps, the user doesn't select any other style, only changes between legend types. So the custom legend should be able to get the colors from the style, shouldn't it?

**Comment by nobuti** [comment]
But the user selects the `none` legend, and when she/he selects the custom again, the legend reads from the style, and the form is reset with those colors.

**Comment by xavijam** [comment]
Ah, if that works, then we can't expect any other thing. We will not store any previous user edition if it selected other type.

**Comment by xavijam** [comment]
In fact, we didn't support that in the previous editor, I don't know why we expect that @ernesmb .

**Comment by ernesmb** [comment]
Yes, you're totally right, it wasn't persistent in the Editor either, I got confused. 

Sorry for the noise 🙏

**Comment by xavijam** [comment]
💋
