### ISSUE TITLE
legends with custom html fail to be migrated

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#10396]
1) create a visualization using the editor, add a layer with points and create a choropleth (attached)
2) add a legend and then edit it (add some text)
3) enable builder and open that visualization with the builder

THe builder shows a choropleth legend but not the custom html

[migrate (on 2016-10-27 at 06.53.31).carto.zip](https://github.com/CartoDB/cartodb/files/555126/migrate.on.2016-10-27.at.06.53.31.carto.zip)

#SMOKE_MG33

**Comment by gfiorav** [comment]
Solved via https://github.com/CartoDB/cartodb/pull/10406
