### ISSUE TITLE
Importing .carto error message

### ISSUE THREAD

**Issue by csobier** [CartoDB/cartodb#10392]
@CartoDB/builder-backend

As per our docs, "If the .carto file contains a dataset with the same name as an existing dataset, it will generate a new dataset with a number suffix to avoid overwriting data. For example, if my_table is an existing dataset in your account, importing a .carto file with a dataset named “my_table”, is imported as my_table_1. However, the map included as part of the .carto file will use the original dataset my_table, not my_table_1. As an alternative, you can rename the dataset to a unique name before exporting"

1. Try importing the following .carto files (most of you will probably have these datasets, available from our public Data Library) 
   - [ne_10m_populated_places_simple map (on 2016-10-26 at 14.09.22).carto.zip](https://github.com/CartoDB/cartodb/files/553647/ne_10m_populated_places_simple.map.on.2016-10-26.at.14.09.22.carto.zip)
   - [Projections, the_geom and the_geom_webmercator (on 2016-10-13 at 17.47.24).carto.zip](https://github.com/CartoDB/cartodb/files/553652/Projections.the_geom.and.the_geom_webmercator.on.2016-10-13.at.17.47.24.carto.zip)

2. I get the following import error. I've tested this with a few .carto files that I know I already have tables for

![image](https://cloud.githubusercontent.com/assets/13319925/19731502/9be8b284-9b6b-11e6-925a-92ce00984262.png)

Is this a under misunderstanding on my part? Or are there more export/import rules I should know about?

**Comment by javitonino** [comment]
It's not related to the importer, seems related to stale tables -> https://github.com/CartoDB/cartodb/issues/8785
