### ISSUE TITLE
Handle Invalid analysis (and other analysis creation errors)

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/cartodb#10391]
If an analysis is not valid or an error occurs while creating it (prior to registration, execution, etc.) no error appears in the UI. The analysis is left with the progress icon. (we cannot easily generate this situation currently before tampering with the code, so this is not a bug, but please keep reading 😬 )

These are cases in which the map instantiation (GET `.../api/v1/map?config=...`) responds with a 200 and this kind of payload:

``` json
{
  "errors": [
    "Invalid analysis, cycle found"
  ],
  "errors_with_context": [
    {
      "type": "analysis",
      "message": "Invalid analysis, cycle found",
      "analysis": {
        "id": "a1",
        "type": "filter-category"
      }
    }
  ]
}
```

This may seem not very important for the invalid analysis case (because the UI should not allow building an invalid analysis in the first place) but other errors may occur during the analysis creation, and in particular we're working in [pre-checking the analyses](https://github.com/CartoDB/camshaft/issues/209) and this seems like a good way to make them fail if they limits are exceeded.

cc/ @rafatower

**Comment by rafatower** [comment]
In order of priorities: better to fail silently than starving all resources with a huge analysis. That said, I think Builder is gonna work on improving UI feedback to the user.

**Comment by xavijam** [comment]
cc @alonsogarciapablo and @javierarce

**Comment by alonsogarciapablo** [comment]
I've tried to replicate what @jgoizueta is describing (manually "breaking" an analysis through the console) and it's working for me. Example, if I add a Filter analysis and I unset the `max` and `min` properties, I get the following response from the maps API when the map is loaded:

```
{
  "errors": [
    "Range filter expect to have at least one value in min or max numeric params"
  ],
  "errors_with_context": [
    {
      "type": "analysis",
      "message": "Range filter expect to have at least one value in min or max numeric params",
      "analysis": {
        "id": "b1",
        "node_id": "b1",
        "type": "filter-range"
      }
    }
  ]
}
```

@jgoizueta comparing this response to the one you posted, I've noticed that there's no `analysis.node_id` in yours, which [is basically what cartodb.js uses](https://github.com/CartoDB/cartodb.js/blob/v4/src/windshaft/error.js#L17) to assign that error to the corresponding analysis node.

@jgoizueta is this happen locally? If so, would you please try this after you upgrade `node-windshaft` to the latest version? thx!

**Comment by alonsogarciapablo** [comment]
Issue moved to [CartoDB/Windshaft-cartodb #584](https://github.com/CartoDB/Windshaft-cartodb/issues/584) via [**ZenHub**](https://www.zenhub.com/)

**Comment by alonsogarciapablo** [comment]
Talked to @dgaubert about this. As we saw in @jgoizueta's comment, `Invalid analysis, cycle found` errors are not including the ID of the analysis node (`node_id`), and that's why the error is not be assigned to a node in the BUILDER.
