### ISSUE TITLE
Responsive layout is overlaping the title and the legends

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10400]
![screen shot 2016-10-27 at 10 15 42](https://cloud.githubusercontent.com/assets/132149/19759676/708806bc-9c2e-11e6-9bf9-b404bfab7c2a.png)

**Comment by xavijam** [comment]
We have a problem here because the title belongs to deep-insights and the legends to cartodb.js :S.

**Comment by piensaenpixel** [comment]
Temporal fix for public view

https://github.com/CartoDB/deep-insights.js/pull/482

**Comment by piensaenpixel** [comment]
Temporal fixed. And we'll work on this one in this ticket https://github.com/CartoDB/cartodb/issues/10402
