### ISSUE TITLE
Logo over the map should link to carto.com

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10401]

**Comment by xavijam** [comment]
Which logo, in private or public view?

**Comment by xavijam** [comment]
Ok, I've seen the problem @piensaenpixel.

<img width="377" alt="screen shot 2016-10-27 at 10 39 59" src="https://cloud.githubusercontent.com/assets/132146/19760366/c251ce58-9c31-11e6-8af6-a4fd7e9a70e4.png">


For me this is pretty important...

**Comment by xavijam** [comment]
Issue moved to [CartoDB/cartodb.js #1468](https://github.com/CartoDB/cartodb.js/issues/1468) via [**ZenHub**](https://www.zenhub.com/)
