### ISSUE TITLE
Unlock dataset modal view is not migrated to new modal design

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#10404]
![screen shot 2016-10-27 at 11 14 36](https://cloud.githubusercontent.com/assets/132146/19761656/216f5d92-9c37-11e6-87f1-50c1ce4154a8.png)

**Comment by xavijam** [comment]
Already done I feel 💋

**Comment by piensaenpixel** [comment]
yes sorry i dont close it :(
