### ISSUE TITLE
Style UI should be updated after applying a query with geom transformation

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#10413]
### STR
- Apply a query which transforms the layer geometry (from polygons to points) such as this one:

``` sql
select
cartodb_id,
st_centroid(the_geom) as the_geom,
st_centroid(the_geom_webmercator) as the_geom_webmercator
from
table_name
```
- Go to style.
- Style UI displays polygon styling instead of points styling.
### Expected results

Style UI should display the right geometry styling, so after applying a query such as that one, style UI should be updated.
#SMOKE_WD14
#SMOKE_WD15

**Comment by xavijam** [comment]
@saleiva @javisantana, we used to reset styles when a query was applied in the previous editor. I'm going to do the same with the Builder.

**Comment by saleiva** [comment]
well... I think we might want to be a bit smarter. I'd reset the styles if the schema changes doesn't let you to keep the same styles only. Imagine filtering a view with a query and having to re-apply the styles everytime

**Comment by xavijam** [comment]
I've just changed that, gimme some minutes. If the query "changes" the geometry type, the styles are resetted. If not, they will keep the same ones. Sounds ok?

**Comment by saleiva** [comment]
well, think on the columns that you use on the styles... thats the second part of the equation that we need to control

**Comment by xavijam** [comment]
Sincerely, we don't have the "chiringuito" ready to start comparing schemas, I have to think about it.

**Comment by xavijam** [comment]
Thinking about it, it is a bit difficult to manage that problem when the style and query are custom.
We should use the CartoCSS parser in order to get the columns involved in the style.
cc @javisantana

**Comment by xavijam** [comment]
branch: issue-10409
