### ISSUE TITLE
Infowindow template only appears and replaces values if fields are previously selected

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#10423]
This works in the Editor, not in the Builder. Appeared here but it's a different problem: #10407.

STR

1. Create a new map with the builder.
2. Select "light" infowindow without fields.
3. Edit the HTML and add a field (`{{my_column}}`).

^ **Infowindows should be enabled, but they're not**.

4. Go back and select light infowindow and one field.
5. Edit the HTML and add a second column (not previously selected.

^ ** Infowindow won't display the value of the second column

cc @matallo @alonsogarciapablo  @javisantana @piensaenpixel @xavijam

**Comment by alonsogarciapablo** [comment]
Issue moved to [CartoDB/cartodb.js #1475](https://github.com/CartoDB/cartodb.js/issues/1475) via [**ZenHub**](https://www.zenhub.com/)
