### ISSUE TITLE
Custom legend should allow free HTML. 

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10436]
In custom legend, since its not dynamic, we should let HTML to be customizable always. If not, there is no way of creating a custom legend actually...

**Comment by saleiva** [comment]
This is needed for the migration of the pending legends

**Comment by nobuti** [comment]
We need to take in mind that it could be users using the custom html (append/prepend) approach, so in addition to this issue, we need to:
- look for users using this functionality already
- remove these fields for this kind of legend (custom). Not sure if we should merge those fields into the core html.

**Comment by xavijam** [comment]
cc @gfiorav

**Comment by xavijam** [comment]
Assigning to @nobuti, he will take care of it.
