### ISSUE TITLE
Front end error is missing when messing with two tables after applying query

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#10432]
### STR

* Create a map with `table1` dataset.
* Style `table1` layer based upon `field1`.
* Change query from `select * from table1` to `select * from table2`. Where `table2` does not have `field1`.
* Apply. The visualization breaks (styles, legends...). The console points out the error:

```javascript
{
error: [
"column "field1" does not exist"
],
hint: "Perhaps you meant to reference the column "table2.field2"."
}
```

But the UI does not tell you what is happening.

### Expected results

UI should show error and hint.

**Comment by ramiroaznar** [comment]
It looks like the query is stuck in another layer analysis node.

![captura](https://cloud.githubusercontent.com/assets/5215798/19804099/832e3b5e-9d0c-11e6-822b-63da52c13bbf.png)

**Comment by xavijam** [comment]
Ok, we will improve the error reporting but, take into account that, if you choose a column like cartodb_id for styling, and then you select another dataset which it contains the same column, nothing will fail, the only thing is that the style will be not the correct one, but that's another story.

If the column doesn't appear in the schema of the table selected, we will show the error in the layers list.

**Comment by xavijam** [comment]
One of the problems found -> https://github.com/CartoDB/cartodb.js/pull/1478

**Comment by xavijam** [comment]
Moved your last comment to a new ticket @ramiroaznar, ok? 💋
