### ISSUE TITLE
Widgets interactivity "breaks" in the embed after applying a query

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#10431]
### STR

* Add widgets
* Share/publish.
* Modify query from `select * from table` to `select * from table where field <> value`, for instance.
* Update.
* Get the link. 
* In the embed widgets have no data and interactivity (empty). According to the console, there is an error when calling the grid.json:

`/**/ typeof grid === 'function' && grid({"errors":["Tileset has no interactivity"],"errors_with_context":[{"type":"unknown","message":"Tileset has no interactivity"}]});`

### Expected result

Widgets should work fine after applying query.

**Comment by xavijam** [comment]
We have checked that it is working, so if you haven't been able to reproduce again, we should close it.
