### ISSUE TITLE
'DATA' tab does not show statistics for converted columns

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#10445]
### STR
- Create a map from a table that has at least one column with numeric data
- In `DATA` tab for the layer, it should show the usual stats

![screen shot 2016-10-28 at 17 39 05](https://cloud.githubusercontent.com/assets/10940006/19812512/166b38bc-9d36-11e6-9979-3a55325c435b.png)
- Then go to the table view and change the data type of that column to `string`
- Reload the map, it now shows it's a string column

![screen shot 2016-10-28 at 17 39 41](https://cloud.githubusercontent.com/assets/10940006/19812538/3e9e85aa-9d36-11e6-95ef-134b0323cdd9.png)
- And if you add it as a widget, it will be a category one

![screen shot 2016-10-28 at 17 41 00](https://cloud.githubusercontent.com/assets/10940006/19812547/4a968128-9d36-11e6-82ef-ae73d60e091c.png)
- go to table view and convert again to `number`. The `DATA` tab shows it's a number, but the preview histogram is gone. Also the column is now at the bottom of the list

![screen shot 2016-10-28 at 17 40 12](https://cloud.githubusercontent.com/assets/10940006/19812644/b6e958fa-9d36-11e6-967a-587dd5e02f34.png)
- If you add it as a widget, it will be a histogram

![screen shot 2016-10-28 at 17 47 35](https://cloud.githubusercontent.com/assets/10940006/19812698/ed83e902-9d36-11e6-9c8d-18ca08cc4488.png)
- The column is correctly recognised as number, but statistics and preview histogram is not shown. After creating a new map from the same dataset, the `DATA` tab still don't show the preview histogram or the stats

Please ping me if the instructions to reproduce are not clear

**Comment by saleiva** [comment]
Prioritizing this since it's happening a lot. Lots of columns are not being correctly rendered.

**Comment by alrocar** [comment]
Stale issue. Closing 👋
