### ISSUE TITLE
map api errors to meaningful messages in the UI

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#10444]
1) set user batch timeout to 100ms
2) run an analysis that takes more than 100ms

you get this mesage:

```
Analysis B1 failed: RuntimeError: Execution of function interrupted by signal. 
```

It would be nice to translate to something meaningful for the user

Other messages:

```
Analysis B1 failed: canceling statement due to statement timeout. 
```

**Comment by javierarce** [comment]
Related to: https://github.com/CartoDB/cartodb/issues/10222
