### ISSUE TITLE
Drawing lines from point dataset to different categorized & weighted centroids dataset fails

### ISSUE THREAD

**Issue by namessanti** [CartoDB/cartodb#10443]
Drawing lines from a filtered point dataset, to another dataset (To source), containing in-depth analysis workflow ending in finding weighted centroids of clusters, fails.

![draw_lines_bug](https://cloud.githubusercontent.com/assets/9421671/19810286/dfc75e2a-9cfa-11e6-9e30-ecd24a71cadd.gif)

Layer 1:
Polygon data>Filtered by column>Connected to Layer 3 polygons for filtering>Centroids by the_geom>Clusters x16>Centroids by clusters weighted by population
Layer 2:
Points layer>Connected to Layer 3 polygons for filtering>Draw lines to categorized, weighted centroids in layer 1 **FAILS**

Note: The same analysis works _sometimes_ approx 1 of every 10 times tried, but then histogram widget querying fails.

**Comment by saleiva** [comment]
cc/ @javisantana

**Comment by namessanti** [comment]
[Optimum Vaccination Clinic Locations, Kenya (on 2016-10-28 at 15.30.42).carto.zip](https://github.com/CartoDB/cartodb/files/558783/Optimum.Vaccination.Clinic.Locations.Kenya.on.2016-10-28.at.15.30.42.carto.zip)  << .carto file for reproducing.

**Comment by dgaubert** [comment]
![gamusino](https://cloud.githubusercontent.com/assets/1936888/20010843/e6e82b08-a2a9-11e6-92b4-2e959053ac3b.gif)

hunted!

**Comment by namessanti** [comment]
Sorry @dgaubert, Still failing when querying with widgets and re-drawing lines.

![draw_lines_bug_2](https://cloud.githubusercontent.com/assets/9421671/20061317/6215b94c-a4cd-11e6-93da-b83ea7f0b4d5.gif)

**Comment by dgaubert** [comment]
Have you checked the error using dev-tools?. Maybe we have another issue...

![screen shot 2016-11-07 at 15 42 11](https://cloud.githubusercontent.com/assets/1936888/20061670/14981f50-a501-11e6-836b-0c30f957f431.png)

**Comment by dgaubert** [comment]
Ok, we've reached the limit of the payload for batch-queries. This analysis is too complex... 🤔 @javisantana, should we raise the limit??

> [2016-11-07 14:49:26.914] [ERROR] console - EXCEPTION REPORT: Error: Your payload is too large: 12658 bytes. Max size allowed is 8192 bytes (8kb). Are you trying to import data?. Please, check out import api http://docs.cartodb.com/cartodb-platform/import-api/

**Comment by javisantana** [comment]
yes

**Comment by dgaubert** [comment]
16Kb ??

**Comment by javisantana** [comment]
let's do it but review it when @rochoa is back

**Comment by dgaubert** [comment]
👍 IIRC we talked to raise it to 16Kb.

**Comment by saleiva** [comment]
about this limit, we need to figure out how to eplain it well to the users, since fixing it in their side can be tricky

**Comment by dgaubert** [comment]
Hey @namessanti, try again please!! It should work now!

**Comment by namessanti** [comment]
Works great, thanks!  Are these limitations being tracked somewhere? Echoing @saleiva, I think from a user experience standpoint we need to be upfront and clear or it could be a turn off for new adopters.

**Comment by rochoa** [comment]
I want to be crystal clear here: this is a leaky abstraction. We are exposing a technical limitation in the wrong place, to the wrong actor.

To fix this quickly we can keep raising the limit, but to do it properly we need to change the way we communicate/create the analyses from camshaft through Batch queries.

**Comment by dgaubert** [comment]
> To fix this quickly we can keep raising the limit, but to do it properly we need to change the way we communicate/create the analyses from camshaft through Batch queries.

👍
