### ISSUE TITLE
Enable add icons when styling points

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10452]
@urbanphes can you upload the designed workflow please?

**Comment by urbanphes** [comment]
These are the visuals to add any icons when styling points.

- The input now have 3 areas; 1 Size, 2 Img and 3 Color. If you clicking on "img" this is the dropdown to choose any icon (bu default will be "NONE" as a Pop-ups)
![01 layers - 02-08 style](https://cloud.githubusercontent.com/assets/14546701/19926230/b1097c6a-a0f3-11e6-8aa2-3b416c06b4d7.png)

- If you select any icon this will be selected with the color chosen.
![01 layers - 02-09 style](https://cloud.githubusercontent.com/assets/14546701/19926234/bd2f8a5c-a0f3-11e6-863c-f78d209c9125.png)

- This is the modal when clicking on "Show full collection"
![60-00 mod marker library](https://cloud.githubusercontent.com/assets/14546701/19926252/d7c2e7a6-a0f3-11e6-98eb-0f52a166971d.png)

cc/ @saleiva

**Comment by urbanphes** [comment]
Here the flow when we select a category and we want a different icons for each category.

![add icon - category](https://cloud.githubusercontent.com/assets/14546701/19936630/65933944-a11e-11e6-9c0b-ae39b4d99525.png)

cc/ @saleiva

**Comment by urbanphes** [comment]
Design in #303

**Comment by xavijam** [comment]
In my opinion, we should start working on this.

**Comment by urbanphes** [comment]
I've updated the modals when you make a click in "Show full collection" on a dropdown.

![input solid img](https://cloud.githubusercontent.com/assets/14546701/20606933/badd9324-b274-11e6-8f52-38278f9c248f.png)


In this modal we have 3 tabs. The first with our collection, on the second "Your uploads" and the last one the posibilitty to connect with yor dropbox account. 
To try not to hide the upload we make the link with the literal in the subtitle in this way we can do it more evidence. 

![60-00 mod marker library](https://cloud.githubusercontent.com/assets/14546701/20607051/919ca4ae-b275-11e6-8d2d-8aed1cba73bc.png)
![60-01 mod marker library](https://cloud.githubusercontent.com/assets/14546701/20607053/9913756e-b275-11e6-9727-24ab8a3f8724.png)
![60-02 mod marker library](https://cloud.githubusercontent.com/assets/14546701/20607055/9edce3ae-b275-11e6-86e9-8996b9e91811.png)

cc/ @saleiva @javierarce

**Comment by saleiva** [comment]
I propose we leave the dropbox tab out of scope

**Comment by MariaCheca** [comment]
This ticket seems to be solver, should we close it?

**Comment by javierarce** [comment]
+1

**Comment by xavijam** [comment]
Ok, it is  merged and new tickets have been created, so closing :+1:. 💋
