### ISSUE TITLE
Incorrect text on Enrich Analysis

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10456]
![screen shot 2016-10-31 at 10 12 20](https://cloud.githubusercontent.com/assets/132149/19849981/586e787e-9f56-11e6-9f60-8a3cb6d53e96.png)

Look at european_union.

**Comment by javierarce** [comment]
I think this shouldn't be fixed in the frontend, because in this case we just show whatever comes from the data observatory table.

**Comment by saleiva** [comment]
@talos can you take a look then?

**Comment by talos** [comment]
@saleiva fixed.

We will continue to have issues with this happening until we finish the pipeline connecting OBS metadata to the UI without touching observatory.cartodb.com, which should be used for test data only.  See https://github.com/CartoDB/dataservices-api/issues/287.
