### ISSUE TITLE
Error when openning a previously edited map

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10453]
https://team.carto.com/u/saleiva/builder/9fe40876-75c7-11e6-a491-0e3ff518bd15 (within the builder)
tracker.js:26 Uncaught Error: TrackJS Caught: Cannot read property 'palette' of undefined

Analysis node appear as loading forever but nothing happens.

**Comment by saleiva** [comment]
Problem is that my map is completely broken and cannot be edited anymore.

cc/ @javisantana

**Comment by saleiva** [comment]
Duplicating it, creates the same map but working.

**Comment by xavijam** [comment]
Checked your error in TrackJS, it is an error related with the autostyle in the histogram (deep-insights). Please @donflopez, could you take a look with @saleiva?

palette@node_modules/cartodb-deep-insights.js/src/widgets/auto-style/histogram.js 20:0

```js
…
getColorLine: function(sym) {
 var shape = this.dataviewModel.getDistributionType(
   this.dataviewModel.getUnfilteredDataModel().get('data')
 );
 var scales = HistogramAutoStyler.SCALES_MAP[sym][shape];
 return sym + ': ramp([' + this.dataviewModel.get('column') +
   '], cartocolor(' + scales.palette + ', ' + this.dataviewModel.get('bins') +
   ')), ' + scales.quantification + ');';
 }
 });
…
```

**Comment by donflopez** [comment]
Yes! But I can see the map linked by @saleiva

**Comment by saleiva** [comment]
but even without the auto style, there are not requests for tha analysis, so they keep loading forever.

**Comment by saleiva** [comment]
After openning it this morning I got

chart.js:1006 Uncaught TypeError: Cannot read property '0' of null_addHoverToStylesheet @ chart.js:1006_generateBars @ chart.js:1018_generateChartContent @ chart.js:378render @ chart.js:65_renderMiniChart @ content-view.js:204_initViews @ content-view.js:49render @ content-view.js:135_onFirstLoad @ content-view.js:75(anonymous function) @ backbone.js:328(anonymous function) @ underscore:890s @ backbone.js:371r @ backbone.js:356m @ backbone.js:155k.trigger @ backbone.js:346set @ backbone.js:515a.success @ backbone.js:593k @ jquery:3099fireWith @ jquery:3211c @ jquery:8264(anonymous function) @ jquery:8605

tracker.js:26 Uncaught Error: TrackJS Caught: Cannot read property '0' of nullwrapError @ tracker.js:26d.util.hasFunction.f.(anonymous function) @ tracker.js:4

**Comment by donflopez** [comment]
This [PR](https://github.com/CartoDB/deep-insights.js/pull/481) fix it
