### ISSUE TITLE
Select all popup fields when users use a custom popup template

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#10460]
As mentioned in https://github.com/CartoDB/cartodb.js/pull/1476#issuecomment-257257350, when users select a custom template for a popup (click or over) and use some fields in the template (eg: `{{ name }}`), CartoDB.js will raise an error if the field wasn't previously selected... In the Editor, we "checked" all fields in this situation, so that all fields are available in custom templates. We should do the same in the BUILDER.

cc: @matallo

**Comment by ramiroaznar** [comment]
I think we can close this one, right @alonsogarciapablo?
