### ISSUE TITLE
ghost node error

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#10469]
**`.carto` file to reproduce:** [ghost node (on 2016-10-31 at 17.02.56).carto.zip](https://github.com/CartoDB/cartodb/files/562430/ghost.node.on.2016-10-31.at.17.02.56.carto.zip)

### STR
- create a map with a point layer **[A]** + polygon layer **[B]**
- add a distance AOI analysis to **[A]** 

![screen shot 2016-10-31 at 18 10 35](https://cloud.githubusercontent.com/assets/10940006/19863713/9663c0fa-9f95-11e6-95b1-ceabada4d14c.png)

- add an Intersection analysis to **[B]**. Select **[A1]** as Intersect layer

![screen shot 2016-10-31 at 18 09 35](https://cloud.githubusercontent.com/assets/10940006/19863630/36236902-9f95-11e6-8c2d-62b351c7a03b.png)

- the layers panel should look like: 

![screen shot 2016-10-31 at 18 00 27](https://cloud.githubusercontent.com/assets/10940006/19863737/b2b53748-9f95-11e6-8b67-486da894e035.png)

**NOTE:** Use the `.carto` attached to get directly to this point

- Drag **[A1]** node out to get a different layer
- The UI 'breaks' and we cannot do anything

![screen shot 2016-10-31 at 18 17 04](https://cloud.githubusercontent.com/assets/10940006/19863902/50d66712-9f96-11e6-83be-4ba8d9249983.png)

- Reload the page. The UI is lost, the map is not rendered and we cannot do anything else

- We can see several errors in the console: 
```
sourceId 'c1' doesn't exist
```

```
Error: Map instantiation failed(…)
```

```
Uncaught TypeError: Cannot read property 'queryGeometryModel' of undefined(…)
```

**Comment by xavijam** [comment]
Happily fixed in https://github.com/CartoDB/cartodb/pull/10557/.

**Comment by ernesmb** [comment]
vamos! 💪
