### ISSUE TITLE
forms: datetime input

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#10468]
review design for datetime input: currently, in order to keep consistency between table cell edition (see attached)

![screen shot 2016-10-31 at 16 41 17](https://cloud.githubusercontent.com/assets/36676/19860408/e0524c16-9f88-11e6-85ac-9731a746641e.png)

and attribute form (see attached) we show an editor dialog, with a collection of inputs 

![screen shot 2016-10-31 at 16 36 23](https://cloud.githubusercontent.com/assets/36676/19860289/78dbd322-9f88-11e6-9d98-debe88d2dba2.png)

ideally we should have the collection of inputs in the input itself, saving one click and the box dialog waterfall, that in this specific case I had to do a quick fix to position

**Comment by urbanphes** [comment]
I think we should reach something like this _(enhancement)_:

![captura de pantalla 2016-11-02 a las 14 16 25](https://cloud.githubusercontent.com/assets/14546701/19930073/fc066562-a106-11e6-87c3-a4cd1ffb0324.png)
