### ISSUE TITLE
Be able to use a column for ranges in AOIs

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#10467]
[SB ticket](https://cartodb.supportbee.com/tickets/10358810)

Currently, isodistance functions can only accept an array of fixed values as range. The same range is used for every row:

```
SELECT (
  cdb_isodistance(
    the_geom, 
    'walk', 
    ARRAY[300, 600, 900]::integer[])
  ).the_geom 
FROM untitled_table_1
```
That query returns three different isolines at 300, 600 and 900 seconds for each row. 

It would be nice if we could use a column as range parameter, so each point could have a different `range` value and therefore produce a unique isoline: 

```
SELECT (
  cdb_isodistance(
    the_geom, 
    'walk', 
    string_to_array(range,',')::integer[])
  ).the_geom 
FROM untitled_table_1
```

If we had this feature, the query above would take the string in `range` (which should be something like `300,600,900`), create an integer array from it and use the values to request isolines with a varying range. 

It currently fails with: 

```
Error in SQL query: cdb_dataservices_client._cdb_isodistance(6): [cartodb_user_a6f0d0fe-xxxx-xxxx-xxxx-22b0010fe409_db] REMOTE ERROR: spiexceptions.ExternalRoutineException: spiexceptions.ExternalRoutineException: Exception: Error trying to get mapzen isolines.
```

**Comment by kevin-reilly** [comment]
@noguerol This came up again today.  Is this an easy thing that we should slot into the Response Team?  Is there a reason we limit the selection options?

**Comment by noguerol** [comment]
Makes sense, but I would love to understand the use case first.

**Comment by saleiva** [comment]
There are different use cases for this. One could be having different AOIs ranges depending on the category of the feature (imagine police stations for example). Bigger police stations might have a stronger force to create bigger AOIs than smaller ones.

I believe this is a dupe anyway, This has come up several times when talking to clients and prospects.

**Comment by kevin-reilly** [comment]
Is there a downside to this feature?  Does it impact performance in some
way?

--
*Kevin Reilly*
SVP Product
*CARTO <https://carto.com/> | kevin@carto.com <kevin@carto.com>*
(917) 375-2168

**Comment by saleiva** [comment]
nope, it shouldn't affect that much, and changes in the UI should be quite easy. @CartoDB/design didn't we have something for this already in the mockups?

**Comment by noguerol** [comment]
@CartoDB/design ping

**Comment by urbanphes** [comment]
This is the 1st approach. 
The idea is to put a selection before the rest of parameters and It depends on selection it will appear an information or another. If the user select “Manual” the parameters will be that we have now and If it selected column appears a column selector where the user can select the column where is this kind of info.

We should review the texts!

Here is the InVision project:
https://invis.io/SPCR7ERJY

**Comment by arianaescobar** [comment]
@urbanphes How about moving that input to the second step? It could be clearer that you first need to select that, which would affect the following step.

In terms of copy, I suggest:

- Changing `Controller` for `Range`
- `Select Column` for `Select a column`
- `Distance` should be `Units`, like on production right now

**Comment by saleiva** [comment]
Uhm... be careful,
The only field that we should change is the radius one, since the other parameters will still be needed.

Also, I'm not sure that Controller works as a name. I think we should move the field closer to the radius one, and call it "type" (fixed \ variable) or something like that

**Comment by urbanphes** [comment]
Thanks for the feedback, mates!

I’ve been working on a second approach.
- I’ve changed the texts that @arianaescobar suggested.
- Now the decision is taken when the user is on radius selection: 
    - _"Manual"_ with the slider we have now
    - _"Column"_ selecting a column in the table


Here is the InVision project:
https://invis.io/SPCR7ERJY

**Comment by urbanphes** [comment]
Ping @saleiva & @noguerol

**Comment by noguerol** [comment]
Purrfect imo.

**Comment by saleiva** [comment]
I'd propose other texts
"MANUAL" -> "FIXED"
"COLUMN" -> "VARIABLE"

**Comment by urbanphes** [comment]
The texts have been changed.

Here is the InVision project:
https://invis.io/SPCR7ERJY

**Comment by urbanphes** [comment]
Close and promote ¿?

**Comment by alrocar** [comment]
Stale issue. Closing 👋
