### ISSUE TITLE
Fixes on Sequential Connect with lines Analysis

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10482]
- [ ] Order shouldn't be optional, it should be mandatory, as well as DESC or ASC.
- [ ] We should switch the order of the fields to make the GROUP BY one the last one since its optative.

**Comment by hacheka** [comment]
How do you prefer to show the Order fields, now that they're mandatory?

Option A: nested form

![screen shot 2016-11-07 at 10 42 38](https://cloud.githubusercontent.com/assets/1078228/20053084/3e1666fe-a4d7-11e6-98a2-cc74adc4e6a0.png)

Option B: at root level

![screen shot 2016-11-07 at 10 41 01](https://cloud.githubusercontent.com/assets/1078228/20053098/4f643b48-a4d7-11e6-9770-f86d7de52d01.png)

**Comment by hacheka** [comment]
Option B has been chosen.

Created the issue https://github.com/CartoDB/camshaft/issues/223 to reflect this change in the Camshaft analysis reference.
