### ISSUE TITLE
Editing the style of a layer reset's its legend's titles [DEPENDS ON #10904]

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#10481]
**STR**

0. Have map with legends
1. Set a custom title for a legend
2. Change styles of that layer (color or whatever)

**Expected result:**

Styles change and maybe the legend has to change as well, but the title stays the same.

**Actual result:**

The legend is reset and the title is as well.

I guess it's debatable but it has given me some frustration today. What do you guys think? Bug or feature?

cc/ @xavijam

**Comment by xavijam** [comment]
That's a good one, it opens the 🍉  about if we need states in the properties in order to store if the user took the decision of changing the title it was auto-generated due to whatever.

**Comment by xavijam** [comment]
As @nobuti pointed in the PR, not merge until #10904.

**Comment by ivanmalagon** [comment]
Brought back from `acceptance` to `development`.

The fix works perfectly when we modify the title of a gradient legend. If we modify the styling after changing the title, it saves the last title. OK

Nevertheless, the next scenario happens:

1. Choose a custom legend.
2. Check title and modify it.
3. Modify the style. For instance, select another color palette.
4. Builder changes the legend from `custom` to `gradient`
5. The given title is lost.

![legend-problem](https://cloud.githubusercontent.com/assets/1078228/20892557/02abc9bc-bb0f-11e6-8cf4-e29a613e0d9c.gif)

After discussing this with @xavijam we concluded that there are two issues here:

A. Should Builder change the custom legend to a gradient one after changing only the color palette?
B. Should Builder keep the title between changes of legend type?

A is not clear for us if it's a good approach. @saleiva has to tell us if it's the desired behaviour or it's a bug.

B is a bug and should be adressed in this issue. When changing between the two types of legends, the title has to be kept.

**Comment by nobuti** [comment]
A bug? Really? It's not the same legend, not sure how to tackle.

**Comment by xavijam** [comment]
Holidays means holidays @nobuti.

**Comment by nobuti** [comment]
We need to define the specs, I think there will be more cases and we'll have to decide what to do.

**Comment by nobuti** [comment]
Should B be applied when the user change between legends using the form? I guess we want this only by legend type (color or size) right?

**Comment by nobuti** [comment]
Fixed and ready for another pass.

**Comment by ivanmalagon** [comment]
Local acceptance 👍 
Staging acceptance at 08 :+1:
