### ISSUE TITLE
Polygons with boolean fields cannot be edited

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10480]
It gives a 400 error on the PUT request
{"errors":["PG::Error: ERROR:  invalid input syntax for type boolean: \"\""]}

**Comment by saleiva** [comment]
Not working correctly in https://matatageom.carto-staging.com/builder/0faf585a-a371-11e6-804b-04014675d001

STR.

- Click on a polygon with the boolean column equals null
- Set boolean to False (Button doesnt get activated)
- Set boolean to True (Button gets activated by very often when clicking on SAVE its get back to null)

**Comment by alonsogarciapablo** [comment]
Working like a charm now! Thanks @matallo!
