### ISSUE TITLE
Empty Dataset workflow fails

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10491]

**Comment by alonsogarciapablo** [comment]
- Draw geometry buttons:
  - [ ] If QuerySchemaModel is not fetched/fetching... some sort of loader must be displayed.
  - [ ] Once the QuerySchemaModel is fetched, buttons should only be displayed if:
    - Layer doesn't has a `source` analysis
    - `source` analysis doesn't have a custom query applied.
- [ ] When the query of the source changes -> re-render buttons
- [ ] When the AnalysisDefinitionNodeModel the layer is pointing to changes (a new one is added, is removed, etc.) -> re-render buttons.
