### ISSUE TITLE
Editor-HeaderInfo-title may not have the proper margin

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#10494]
when using the utility class `.u-bSpace--m` along with `.Editor-HeaderInfo-title` it has no effect, also we shouldn't use modifiers without the modified class itself

![screen shot 2016-11-02 at 13 00 52](https://cloud.githubusercontent.com/assets/36676/19928026/f529acf4-a0fc-11e6-8a18-023feddae3bc.png)

doing a search for `<div class="Editor-HeaderInfo-title u-bSpace--m">` returns

```47 matches across 35 files```

**Comment by piensaenpixel** [comment]
Fixed in 10124-geom-panel thanks @matallo
