### ISSUE TITLE
context menu position is not consistent

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#10495]
I've been struggling for a while with the context menu, I already noticed it didn't position correctly between layers panel and layer panel, and it is still more evident in the edit geometry panel

![meatball menu](https://cloud.githubusercontent.com/assets/36676/19929769/484434a6-a105-11e6-8ff9-a190b10a5cac.gif)

the markup for the `ContextMenuFactory` is different for the markup in the header, and while being the same in layers panel and edit geometry panel it position the menu vertically centered so it varies depending on the height of the header

ideally we should use the same markup for this element, as well as the same markup for the three headers

involved templates
https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb3/editor/layers/layer-header.tpl
https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb3/components/context-menu-factory-view.js
https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb3/editor/editor-header.tpl

**Comment by piensaenpixel** [comment]
fixed!, but i'll take a look for consolidate some components, thanks @matallo
