### ISSUE TITLE
[Legends] Line width legend

### ISSUE THREAD

**Issue by carlostallon** [CartoDB/cartodb#10493]
more info here: https://github.com/CartoDB/design/issues/296#issuecomment-257516402

![](https://cloud.githubusercontent.com/assets/1566273/19731724/9e808ffe-9b5b-11e6-928a-be25201f77f0.png)

**Comment by saleiva** [comment]
For the time being we shouldnt implement the hover state.

**Comment by xavijam** [comment]
This is for the next milestone right? If not we will not have time to finish the autostyle thing.

**Comment by saleiva** [comment]
This is for v1 of the legends, can be next milestone, yeah. You guys tell me.

**Comment by xavijam** [comment]
In my opinion, after a deep thought, let's finish all the legends pending things and then polish and finish autostyle v0.1.

**Comment by piensaenpixel** [comment]
this is ready in cartodb.js so... all yours @nobuti

**Comment by alrocar** [comment]
Stale issue. Closing 👋 

Fun fact, we included this legend in CARTOframes / Airship three years later :)
