### ISSUE TITLE
Track 'Added widget' event

### ISSUE THREAD

**Issue by jmartinter** [CartoDB/cartodb#10501]
We'd like to monitor how users use widgets in their dashboards.

This new segment event should include (if possible) all the common event attributes in addition to these specific ones:
- vis_id: id of the derived visualization
- widget_type: type of the widget (histogram, ...)
- ~rows: number of rows in dataset (in the moment of widget creation)~

cc'ed @xavijam

**Comment by xavijam** [comment]
Aren't we doing it that already? cc @gfiorav.
BTW, we can't provide the number of rows from any widget.

**Comment by gfiorav** [comment]
Nope, @xavijam, we haven't done that until now.

+1 on number of rows in dataset.

**Comment by jmartinter** [comment]
Ok, no # of rows

**Comment by gfiorav** [comment]
Hey @jmartinter , do you want only "Added analysis" or also "Deleted analysis" and "Modified analysis"?

**Comment by jmartinter** [comment]
@gfiorav I think 'Added widget' event is enough for now

**Comment by javitonino** [comment]
Working as expected: 

```
Analytics.track(
  user_id: '66dbec9d-e9a4-4e0e-9b2a-238eb486e590',
  event: 'Created widget',
  properties: {
    creation_time: DateTime.iso8601('2016-12-19T13:05:32.000Z'),
    email: '-------',
    event_origin: 'Builder',
    lifetime: 2.760875388366053,
    object_created_at: DateTime.iso8601('2016-12-16T18:49:52.000Z'),
    organization: ,
    plan: 'FREE',
    privacy: 'public',
    type: 'derived',
    user_active_for: 179.90440301359754,
    user_created_at: DateTime.iso8601('2016-06-22T15:23:11.000Z'),
    username: '----------',
    vis_id: '6dd31b1e-c3c0-11e6-8c8b-0401a71f2f01',
    widget_type: 'histogram'
  }
)
```

It triggers even when the widget is auto-created (animated torque layers).
