### ISSUE TITLE
Race condition found in demo creating analysis

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10504]

**Comment by javitonino** [comment]
If the PUT layer arrives after the PUT analysis, the analysis return will not include the latest state.

**Comment by javitonino** [comment]
It should be mitigated with latest changes. It's not foolproof, I might have missed it somewhere, but I'll close for now and reopen if we can replicate the issue (adding a new analysis and removing it inmediately resets styles) or something similar.
