### ISSUE TITLE
Geocoding fails if no geocoding block price is assigned

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#10507]
app/models/geocoding.rb#price:

```ruby
211   def price
212     return 0 unless used_credits.to_i > 0
213     (user.geocoding_block_price * used_credits) / ::User::GEOCODING_BLOCK_SIZE.to_f
214   end # price
```

It fails if `geocoding_block_price` is null (open source users, for example).

cc @CartoDB/dataservices

**Comment by rafatower** [comment]
A meta question: what should be the behavior if any block_price is null? cc/ @CartoDB/dataservices

**Comment by juanignaciosl** [comment]
I'd consider that it's 0. I would've just added `.to_i`, but I thought that you should agree before :-)

**Comment by saleiva** [comment]
When no price is defined, we should disable this.

**Comment by javitonino** [comment]
Shouldn't this be better handled by @CartoDB/dataservices? I read the referenced issues and I think they have better awareness about what effects a change like this (pricing) might have.

**Comment by javitonino** [comment]
Fixed for existing users, and created a patch that should block soft geocoding if price is not set (just to be future-proof, this should not happen anymore).
