### ISSUE TITLE
Buttons to draw new geometries are not positioned correctly when time series widget is present

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#10505]
![screen shot 2016-11-02 at 16 00 59](https://cloud.githubusercontent.com/assets/390398/19934047/b7ae7e86-a115-11e6-9e40-a28d61c5d0fd.png)

cc: @matallo

**Comment by matallo** [comment]
:'D on it

**Comment by saleiva** [comment]
Still happening
<img width="1162" alt="screen shot 2016-11-09 at 16 09 51" src="https://cloud.githubusercontent.com/assets/132149/20142908/0073708c-a697-11e6-824e-5ebf90483159.png">

**Comment by matallo** [comment]
on it, they changed since the original issue

**Comment by matallo** [comment]
<img width="1265" alt="screen shot 2016-11-09 at 16 19 15" src="https://cloud.githubusercontent.com/assets/36676/20143194/4f6af61e-a698-11e6-8f1c-293bc9310b8a.png">

**Comment by saleiva** [comment]
Its not only when animated, also when selected. I think we should force the widget to have always the same height. cc/ @piensaenpixel
