### ISSUE TITLE
Track 'Failed analysis' event

### ISSUE THREAD

**Issue by jmartinter** [CartoDB/cartodb#10503]
It would be really interesting tracking when an analysis fails and relating it with the user.

This new segment event should include (if possible) all the common event attributes in addition to these specific ones:
- analysis_id: Id of analysis (at present is same as natural id but it will change in the future)
- analysis_natural_id: Id of análysis as seen by user (allows to identify the analysis pipeline)
- analysis_type: type of performed analysis
- failure_cause: reason of failure (I don't know if we can get this info)
- vis_id: id of the derived visualization
- object_created_at: visualization creation timestamp
- lifetime: lifetime of map (in days)
- privacy: privacy of map
- type: always 'derived' for this type of event

cc'ed @xavijam, @gfiorav

**Comment by noguerol** [comment]
@rochoa is this still a good approach?

**Comment by alrocar** [comment]
Stale issue. Closing 👋
