### ISSUE TITLE
Modal showing analysis results overlaps side panel

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#10512]
On my laptop (1280 x 800) this what happened after adding a new AOI analysis:

<img width="1440" alt="screen shot 2016-11-02 at 18 38 27" src="https://cloud.githubusercontent.com/assets/390398/19940051/a853ddee-a12b-11e6-91fb-716bd15d3c42.png">

cc: @javierarce @piensaenpixel

**Comment by javierarce** [comment]
:( 👌

**Comment by javierarce** [comment]
@alonsogarciapablo: I've tried to replicate the problem, but I always get a nice overlay. Is this issue consistent?

**Comment by alonsogarciapablo** [comment]
Yes, it's consistent.

Here're the steps to reproduce (I should have included them originally, sorry):

1. Click on a layer.
2. Add an analysis that takes some time.
3. While the analysis is running, go to the Data tab and switch to the SQL mode (quickly, and before the analysis ends).
4. Hold your horses until the analysis finishes.
5. You should see that the left side panel is now wider (due to the length of the query `select * from analysis_2f13a3dbd7_5efccb1d6be402fd068f1f5ab00aa48cf587d634` ?) and the overlapping modal.

**Comment by javierarce** [comment]
Ah, great, I thought you changed to the panel after the analysis was done. Thanks!
