### ISSUE TITLE
changing base map in Builder.

### ISSUE THREAD

**Issue by mapsgeek** [CartoDB/cartodb#10513]
the base map doesn't change, it will load but the old one will still overlay it, so for example ( dark) base map changed to ( nokia satellite ), it will stay the dark one and the nokia one will load underneath it. 
![capture](https://cloud.githubusercontent.com/assets/10188264/19947763/4865d79e-a152-11e6-9c3e-1d32b0e3cc7a.JPG)

**Comment by saleiva** [comment]
hi @mapsgeek can you confirm this is happening always? Not being able to replicate it

**Comment by mapsgeek** [comment]
@saleiva yeah it was happening to me the whole day i submitted the issue but then i'm not able to experience it again and works fine.
