### ISSUE TITLE
Options menu in dataset view opens to the left

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#10514]
In the dataset view, the options menu opens to the left, so the options are cut off with short table names:

![screenshot_20161103_095807](https://cloud.githubusercontent.com/assets/7569673/19960264/0e38e9e4-a1ac-11e6-8c86-c510a2b8f643.png)

**Comment by xavijam** [comment]
This is already fixed in `magic-positioner`  branch, @MariaCheca could you take care of it?

**Comment by javitonino** [comment]
\o/
