### ISSUE TITLE
Make our internal geocoder to use admin data from the DO

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10515]

**Comment by rafatower** [comment]
@talos what would it take for the DO to fulfill the `cdb_geocode_admin*` function signatures?

**Comment by talos** [comment]
@rafatower I'm not sure, but I can do some research in the next sprint to give an estimate of feasability.

**Comment by rafatower** [comment]
:+1: I'd appreciate it if we talked face to face about this on a broad sense in Malaga :)

**Comment by talos** [comment]
That would be great! 👍 definitely.
