### ISSUE TITLE
Edit geometry panel looks wrong when loaded while editing sql or styles

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#10529]
![edit-geometry-while-on-dark-panel](https://cloud.githubusercontent.com/assets/390398/19966857/eaaca75a-a1cd-11e6-8073-34db5bded23a.gif)

cc: @matallo @nobuti

**Comment by nobuti** [comment]
This seems related with editorModel in edition mode. @matallo I can check it if you want.

**Comment by matallo** [comment]
no prob, I'll take it
