### ISSUE TITLE
Query failing when we auto-prepend account name without dataset name to column

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#10538]
Hi @rafatower assigning to you in case it's related to [this](https://github.com/CartoDB/cartodb/issues/5813) but would you please re-assign if needed? Thank you.

@CartoDB/support please notify client when fixed.

S/B 10384220

When Enterprise organization member applies SQL query our system is auto-prepending their seat account name to WHERE clause column, without also prepending the dataset name & is causing query failure.

## Context
Enterprise client applies SQL query and gets this error even though FROM clause is included:

![screen shot 2016-11-03 at 3 05 32 pm](https://cloud.githubusercontent.com/assets/1779444/19981131/04d15e7e-a1d7-11e6-86db-3d3c03ffe133.png)

When I test with same (public) dataset in my team account everything works as expected without error.

Client has given us permission to test inside their account with [this dataset](https://dsl-ur.carto.com/u/digitalscholarshiplab/tables/holc_polygons_nov1st_fortest).

## Process
1. From within client's account, apply this query in Editor SQL panel of holc_polygons_nov1st_fortest dataset:

    `SELECT * FROM holc_polygons_nov1st_fortest WHERE holc_id = 'C1'`

## Expected result

![query_test](https://cloud.githubusercontent.com/assets/1779444/19981219/6ef6ef8a-a1d7-11e6-8178-09131c51ecf8.gif)

## Current result

* Applied query automatically re-writes itself with account name prepended to dataset name and column name:
    `SELECT * FROM digitalscholarshiplab.holc_polygons_nov1st_fortest WHERE digitalscholarshiplab.holc_id = 'C1'`

* If I correct ^^ by adding dataset name between account & column names in the WHERE clause & clicking Apply the query applies properly:

    `SELECT * FROM digitalscholarshiplab.holc_polygons_nov1st_fortest WHERE digitalscholarshiplab.holc_polygons_nov1st_fortest.holc_id = 'C1'`

## Related
Since this behavior is not happening in my team account w/same process & data, maybe it's related to [this](https://github.com/CartoDB/cartodb/issues/5813)? Although in this case organization has dash in the name, not seat account.

**Comment by rafatower** [comment]
Nothing to do with the issue you mention above as it was about the importer.

This one is SQL editor => Editor => Builder

Assigning to @xavijam for proper dispatching. Thanks for the thorough report.

**Comment by javitonino** [comment]
The problem here is the user has a table named `holc`. The editor code tries to qualify all table names in the query (in case it's a JOIN) and does so by simple matching of all table names. So when it sees `holc_id` and it knows there is table named `holc` it (incorrectly) qualifies it.

This is an old issue (2014), only happens in the editor (the builder is safe from this) and is restricted to some specific scenarios where table names partially match column names. So I don't think it's a priority. @xavijam?

**Comment by rafatower** [comment]
IMHO is not a priority cause it's a rather rare case and there's a workaround to it: rename the table or the column.

**Comment by ztephm** [comment]
Thank you all! I gave client work-around for now & closing since this won't be an issue in Builder.
