### ISSUE TITLE
When editing geom in form, geometry editor won't update

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#10530]
**steps to reproduce**

- click on edit geometry
- drag point (for example)
- put lat: "0"
- put lng: "0"
- tiles update but geometry editor keeps in the same place

![screen shot 2016-11-03 at 13 59 06](https://cloud.githubusercontent.com/assets/36676/19967316/0edb7956-a1d0-11e6-9e0e-ea36c812756e.png)

**Comment by alonsogarciapablo** [comment]
Fixed via https://github.com/CartoDB/cartodb/pull/10544 and https://github.com/CartoDB/cartodb.js/pull/1488.
