### ISSUE TITLE
Intersect fails when points are located near higher latitudes

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#10540]
### STR

* Create a map with `world_borders` and `populated_places`.
* Add `Intersect second layer` analysis to `world_borders` layer.
* Set `populated_places` layer to "INTERSECT LAYER" and `COUNT` as "OPERATION".
* Apply.

### Result

* The analysis is done.
* No geometries are displayed/rendered.
* After refreshing a PostGIS error is displayed: `Postgis Plugin: ERROR:  transform: couldn't project point (180 -90 0): tolerance condition error (-20)↵↵in executeQuery Full sql was: 'SELEC...`

### Expected result

* The UI should not say "the analysis was succesful done".
* I could not replicate, but once I got this UI error:

![error](https://cloud.githubusercontent.com/assets/5215798/20000702/24b44970-a279-11e6-92b0-efdb6739c709.png)

* This error should be showed always.

**Comment by xavijam** [comment]
I feel this is a problem from the API, what do you think @dgaubert ?

**Comment by ramiroaznar** [comment]
I have filtered by megacities (which are not in higher latitudes) and reapply the intersect. 

![error2](https://cloud.githubusercontent.com/assets/5215798/20001172/39ba2284-a27b-11e6-98a5-cdb0bb892b6f.png)

The analysis is done, geometries are rendered but as you can observe something has gone wrong. I do not know if it is related, and if the problem is that `world_borders` geometries are malformed.

**Comment by ramiroaznar** [comment]
This las issue is solved when using `WHERE ST_IsValidReason(the_geom) ILIKE 'Valid Geometry'`

**Comment by rochoa** [comment]
This is related to https://github.com/CartoDB/camshaft/issues/200.

**Comment by ramiroaznar** [comment]
Still an issue.
