### ISSUE TITLE
Check migration for layer-selector

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#10551]
Looks like we are displaying the old layer selector in the builder.

cc @alonsogarciapablo

**Comment by xavijam** [comment]
cc @nobuti

**Comment by nobuti** [comment]
Confirmed

![screen shot 2016-11-04 at 15 25 09](https://cloud.githubusercontent.com/assets/1366843/20008976/f0a291da-a2a2-11e6-9fea-9e5f298578e9.png)

**Comment by nobuti** [comment]
The good news is that in the embed both work like a charm :)

**Comment by xavijam** [comment]
:joy:

**Comment by xavijam** [comment]
Check what are the necessary steps to fix it please, and if you need backend migration, @CartoDB/builder-backend are your men.

**Comment by nobuti** [comment]
@CartoDB/builder-backend we need some migrations here. If a user with a map created in the old editor had the layer selector enabled, we need it enabled in the Builder too. As you remind, this setting is using now the map api created for it.

**Comment by juanignaciosl** [comment]
@nobuti ok, I'll do it! cc @CartoDB/builder-backend
