### ISSUE TITLE
Some histogram widgets get empty when added

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10562]
Not happening 100% of the times, but very frequently (at least in my account).

STR:
- Create a new map with a big dataset if possible (https://team.carto.com/u/saleiva/dataset/trafikoa)
- Click on the DATA tab of the layer.
- Start adding histogram widgets with the checkboxes

See attached
<img width="1680" alt="screen shot 2016-11-05 at 16 28 51" src="https://cloud.githubusercontent.com/assets/132149/20031280/39e5405e-a375-11e6-877c-7c88ca5a3204.png">

No errors, no nothing.
cc/ @nobuti @donflopez @javisantana

**Comment by nobuti** [comment]
Closed by https://github.com/CartoDB/deep-insights.js/pull/489
