### ISSUE TITLE
Tiles doesn't get invalidated after editting/deleting a feature 100% of the times

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10566]
Often after editing or removing a feature tiles doesn't get invalidated correctly even though the row has been updated correctly

**Comment by alonsogarciapablo** [comment]
@saleiva I'm not able to reproduce this (using http://matatageom.carto-staging.com) 😲 

I've checked some requests, and tiles are not being cached for me (with catching enabled of course):

![screen shot 2016-11-07 at 11 43 07](https://cloud.githubusercontent.com/assets/390398/20054983/6ad951e4-a4df-11e6-8cad-309e3ca6ac68.png)

Also, talked to @dgaubert and it seems that the machine we're testing on doesn't have TIS (The Invalidation Service) enabled, so it's probably using our previous, trigger based, method for invalidating tiles.

Anyway, let's keep an eye on this.

**Comment by saleiva** [comment]
Just doing a bunch of edits and deletes (more than 20), one after the other

**Comment by saleiva** [comment]
Closing since Im not being able to reproduce in staging

**Comment by alonsogarciapablo** [comment]
👍
