### ISSUE TITLE
3 points options in edit geometry panel are wrongly placed

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10569]
<img width="558" alt="screen shot 2016-11-05 at 17 10 59" src="https://cloud.githubusercontent.com/assets/132149/20031631/f9e63890-a37a-11e6-9b75-3171b6c0a275.png">

**Comment by alonsogarciapablo** [comment]
Pixel perfect @piensaenpixel:

![three-points](https://cloud.githubusercontent.com/assets/390398/20094978/da359150-a5a3-11e6-8537-579bb5cfa3e4.gif)

:clap:
