### ISSUE TITLE
Search box is not appearing on Category Widget

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10565]
<img width="565" alt="screen shot 2016-11-05 at 16 33 30" src="https://cloud.githubusercontent.com/assets/132149/20031312/a3942e7a-a375-11e6-8389-9585d492b674.png">

cc/ @donflopez

**Comment by xavijam** [comment]
Private or public views?

**Comment by donflopez** [comment]
It happens in private views, I didn't check in public... It happens with the autostyle flag and without it.

**Comment by donflopez** [comment]
I can't reproduce it again

**Comment by xavijam** [comment]
Could you take a look @nobuti in case it is a problem related with last changes in deep-insights? 💋

**Comment by saleiva** [comment]
Not able to reproduce. Closing

**Comment by nobuti** [comment]
I've seen another occurrence yesterday, in this map: https://team.carto.com/u/saleiva/builder/b3d39636-c6bb-11e6-9c0f-0ef24382571b. The widget only receives the right values when it's filtered. And if you apply the query `SELECT * FROM cartodb_query where 1 = 1`, it works as well. Pretty crazy. Not sure if overviews it's something to do with the problem.
