### ISSUE TITLE
When saving a geometry the notification text is wrong

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10568]
It says, adding widget instead of adding feature

**Comment by alonsogarciapablo** [comment]
Fixed in https://github.com/CartoDB/cartodb/pull/10137/commits/bbaee0d94e7e2f894eaa0c298d34e239453467ba.

![screen shot 2016-11-07 at 11 59 39](https://cloud.githubusercontent.com/assets/390398/20055531/d4866742-a4e1-11e6-836a-9b091f626be2.png)
