### ISSUE TITLE
Do we support Transactions?

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#10561]
cc @javisantana 
S/B 10399055

## Context
Support client wants to know if we support [Transactions](https://www.postgresql.org/docs/8.3/static/tutorial-transactions.html)

## Process
I tested by pasting this into browser tab:

https://stephaniemongon.carto.com/api/v2/sql?q=BEGIN; UPDATE batch_test SET name = 3 WHERE cartodb_id = 3; SAVEPOINT my_savepoint; UPDATE batch_test SET name = 4 WHERE cartodb_id = 3; ROLLBACK TO my_savepoint; UPDATE batch_test SET name = 4 WHERE cartodb_id = 4; COMMIT;&api_key=mykey

## Result
[Dataset](https://team.carto.com/u/stephaniemongon/dataset/batch_test) was updated properly:

![screen shot 2016-11-04 at 2 43 19 pm](https://cloud.githubusercontent.com/assets/1779444/20018194/2421f0f6-a29d-11e6-9a27-6448bde016bb.png)

but response in browser included 'total rows: 0':
![screen shot 2016-11-04 at 2 47 13 pm](https://cloud.githubusercontent.com/assets/1779444/20018310/977a7f46-a29d-11e6-9d54-82b9340af7d4.png)

I understand 'total_rows:0' refers to rows affected by last query - but if data's being overwritten instead of creating new rows then it's proper for total rows to = 0, right?

Double-checking b/c client is interested in:
* if we fully support Transactions
* if one query fails would the others execute (I let him know re: Batch API but wondering re: Transactions)

**Comment by javisantana** [comment]
Issue moved to [CartoDB/CartoDB-SQL-API #380](https://github.com/CartoDB/CartoDB-SQL-API/issues/380) via [**ZenHub**](https://www.zenhub.com/)
