### ISSUE TITLE
Record edition validation

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#10576]
We're getting a few `Max update_row! retries reached ` errors.

https://rollbar.com/vizzuality/CartoDB/items/20905/

Those are caused at record edition, often because of type changes.

cc @matallo @CartoDB/builder-backend

**Comment by gfiorav** [comment]
I've been able to reproduce this by manually sending an incorrect data type.

There's no real way to know what happened in those cases as no trace of type is left in the operation.

There are only 9 occurrences of this and there is no guarantee of what exactly happened. I'm not sure how to (or if to) fix this. I could theorise that it's a peace condition where front thinks the type has changed but the operation has failed and then an incorrect type data is sent, causing this error.
