### ISSUE TITLE
Table view not loading if EITHER `the_geom`, `the_geom_webmercator` OR `cartodb_id` is not selected

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#10582]
### Context
This bug appears when applying custom queries from the table view, opening a dataset, expanding the SQL panel and applying the queries there. 
### STR
1 - Login to CARTO account
2 - Go to `Your datasets`
3 - Click on `NEW DATASET` and connect this one: [dummy_dataset_1.csv.zip](https://github.com/CartoDB/cartodb/files/575265/dummy_dataset_1.csv.zip). This error also reproduces with other datasets, but just for clarity.
4 - Once the import is finished, expand the SQL panel.
5 - Apply this query: 
```
SELECT a,b,c FROM dummy_dataset_1
```
6 - The table does not appear and this keeps spinning: 

![screen shot 2016-11-07 at 13 12 19](https://cloud.githubusercontent.com/assets/10940006/20057464/e614a4d8-a4eb-11e6-8558-4be547c81129.png)
7 - Add **any of this three columns** to the query: 
  - `the_geom`
  - `the_geom_webmercator`
  - `cartodb_id`

8 - The table is showed just fine: 

![screen shot 2016-11-07 at 13 14 52](https://cloud.githubusercontent.com/assets/10940006/20057504/3128c1e8-a4ec-11e6-96ff-387ff7da6699.png)

9 - Sometimes, hitting 'refresh' will also make the table appear, but it's not always and I wasn't able to find a consistent pattern, sorry :( 

### expected result

The table view should show any column selected regardless of `the_geom`, `the_geom_webmercator` or `cartodb_id`

### current result

The table view is failing to show results if one of the above columns is missing.

**Comment by saleiva** [comment]
This should be tested on the smoke tests
