### ISSUE TITLE
Filters applied by widget persist if the widget is deleted

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/cartodb#10585]
### Context

If a widget is used for filtering a layer and then the widget is removed, the filter persists.
 

### Steps to Reproduce

1. Create a map in the Builder
2. Add a widget that allows filtering (e.g. a Category or Histogram widget)
3. Filter the data with the widget (e.g. click on a category or select a range in the histogram)
4. Remove the widget (click "Delete..." on it's menu)

### Current Result

The map remains filtered (showing only the category or range selected in the widget not longer present)
 
### Expected result

The filter should be removed and all the data visible.

**Comment by xavijam** [comment]
This is not happening anymore :dancer:.
