### ISSUE TITLE
feature request: add more controls for display of onboarding

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/cartodb#10586]
Currently the 'onboarding' screens for analyses disappear after a user opts out of not seeing them. Oftentimes, though, you want to take a look at them again. I see a couple of options:

1. be able to 'show onboarding screen' from any analysis UI
2. 'don't show' only affects the current map, and not global all maps in a user's account as it seems to do currently

**Comment by saleiva** [comment]
1. Will be done in a different way, in the details screen of the analysis. (cc @javierarce)
2. I agree
