### ISSUE TITLE
Viewport is fixed to width

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#10583]
### Steps to Reproduce

1. Create a map with data
2. Zoom into any data where you have a reference at the horizontal edges of the screen
3. Open embed

### Current Result

The zoom is fixed to the horizontal width that you selected previously.

### Expected result

The zoom is grabbed according to the vertical length.

Not really sure that is the ideal thing, but it has changed for sure.

cc/ @xavijam

**Comment by javitonino** [comment]
Can you re-check this? We just did some changes that may help.
