### ISSUE TITLE
Builder Time Series widget showing 3 letter month abbrev for 1st month, then full month name for 2nd month

### ISSUE THREAD

**Issue by nygeog** [CartoDB/cartodb#10584]
### Context
Builder Time Series widget showing 3 letter month abbrev for 1st month, then full month name for 2nd month
 
![screen shot 2016-11-07 at 8 49 50 am](https://cloud.githubusercontent.com/assets/2790599/20060051/4bb35476-a4c7-11e6-9fbb-eb7443288a78.png)

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Upload time series data w/ 2 months of data
2. Set time as Torque col

### Current Result
*Please describe here below the current result you got*
Seeing *Oct* for first month, then *November*
 

### Expected result
*Please describe here below what should be the expected behaviour*
Should both be 3 letter abbrev. 

### Browser and version
*What internet browser (Chrome, Firefox, etc) and version was you using and version* 
Chrome. 
 
### .carto file
*Don't forget to rename .carto file to .zip file to be able to upload to github*

[Tech Touch Map (on 2016-11-07 at 13.52.52).zip](https://github.com/CartoDB/cartodb/files/575492/Tech.Touch.Map.on.2016-11-07.at.13.52.52.zip)

### Additional info
*Please add any information of interest here below*

**Comment by xavijam** [comment]
Moving it to deep-insights, where it should be fixed.

**Comment by xavijam** [comment]
Issue moved to [CartoDB/deep-insights.js #491](https://github.com/CartoDB/deep-insights.js/issues/491) via [**ZenHub**](https://www.zenhub.com/)
