### ISSUE TITLE
Error notification doesn't get removed correctly

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10592]
### Context
When applying a query which gives an error, fixing and applying again, the error on the code editor keeps being visible while it says loading in the bottom.

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Go to the SQL editor
2. Apply a query which gives an error
3. Fix the query and apply again

### Current Result
Error is shown until the query finishes

### Expected result
Error show dissapear when clicking on apply

### Browser and version
Chrome

 

### .carto file
*Don't forget to rename .carto file to .zip file to be able to upload to github*

 

### Additional info
*Please add any information of interest here below*

**Comment by ramiroaznar** [comment]
Fixed.
