### ISSUE TITLE
Concurent imports from map get stuck in "pending" state

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#10593]
### Context
Running smoke tests and trying to set up a map with an org users.

 

### Steps to Reproduce
1. Create an empty map
2. Click on "ADD" to add a new layer
3. Click on "CONNECT DATASET" and select a file.
4. Repeat steps 2 and 3 a couple of times, do not wait for the imports to finish.

### Current Result
I saw a brief error message, then the first import did not succeed and the other two are stuck in "pending" state.

### Expected result
All 3 layers are imported correctly

### Browser and version
```
Google Chrome	49.0.2623.87 (Official Build) (64-bit)
OS	Linux
```
 

### .carto file
I could not export the map. I created a separate ticket for it: https://github.com/CartoDB/cartodb/issues/10594
 

### Additional info
* I don't really know if it can be reproducible. It may be a race condition.
* user: `smoke711-4`
* It probably has nothing to do with the Builder but with the import API. I'll investigate it.

#SMOKE_MG03

**Comment by rafatower** [comment]
False alarm. What I found in the logs:
```
2016-11-07 17:21:03 UTC: ogr2ogr call:            OSM_USE_CUSTOM_INDEXING=NO PG_USE_COPY=YES PGCLIENTENCODING=UTF-8  /usr/bin/ogr2ogr2.1 -f PostgreSQL...
2016-11-07 17:21:03 UTC: ogr2ogr output:          ERROR 1: PQconnectdb failed.
could not fork new process for connection: Cannot allocate memory
```

but this can be a blocker for testing. cc/ @javisantana @luisbosque

**Comment by javitonino** [comment]
This is running in a staging which sometimes gives memory problems while deploying. Maybe its related? If it becomes a blocker for testing at some point, let's deploy to another server.

**Comment by rafatower** [comment]
I'd deploy somewhere else for sure. Double-checking because of this is just very time-consuming. It is for me but could be worse if somebody less technical open issues and we need to confirm them.
