### ISSUE TITLE
Changing table def'n under widget is bad

### ISSUE THREAD

**Issue by pramsey** [CartoDB/cartodb#10601]
### Context
* I was trying to build a chloropleth map, but where the input data were not in %

### Steps to Reproduce
* Load a file and make a map w/ it
* Add a widget to the map, based on a column you like
* Go to the SQL pane, and change the definition of the data such that the column you based your widget on no longer exists

In my case the SQL was

    SELECT
        the_geom, the_geom_webmercator, cartodb_id, 
        100.0 * ndp/vtotal as ndp_pct 
    FROM va_2013_carto WHERE vtotal > 0

### Current Result
* The map part of the map renders, but the widget part is blank(ish) *and* more importantly cannot be removed. There is no option on the widget to delete it or in the data panel to delete it.

![screenshot_58](https://cloud.githubusercontent.com/assets/113883/20073780/74e323e2-a4e2-11e6-9b9b-792dca079ed9.png)

### Expected result
* Uh... either the widget just disappears when the column backing it disappears, or the dead widget offers an option to delete it.

### Browser and version
* OSX Chrome

**Comment by ramiroaznar** [comment]
Hey @pramsey. I could not be able to replicate the error. I think the rendering error is related to a previous SQL query applied. When applying the query from the screenshot, the widget shows "REFRESH" warning, but then you are able to go to WIDGETS and delete it.
