### ISSUE TITLE
Show Blue Bar - Users Cannot Find Social Media Sharing Options

### ISSUE THREAD

**Issue by michellechandra** [CartoDB/cartodb#10607]
### Context
A user has shared via Twitter and Support Bee that the interface is not intuitive for finding social media sharing buttons. In the UI, this option is called "show blue bar" under Map Options. 

![screen shot 2016-11-07 at 15 02 22](https://cloud.githubusercontent.com/assets/5423288/20079784/35d93204-a4fb-11e6-8c26-e0e6a3347afd.png)
 
Support Bee: 10431432

### Additional info
Suggest renaming the "show blue bar" option or provided more info about social media sharing in the UI.

**Comment by xavijam** [comment]
IMHO feedback should go to design-

**Comment by xavijam** [comment]
Issue moved to [CartoDB/design #327](https://github.com/CartoDB/design/issues/327) via [**ZenHub**](https://www.zenhub.com/)
