### ISSUE TITLE
MM04: Cartofante branding still present at private map /embed

### ISSUE THREAD

**Issue by andrewbt** [CartoDB/cartodb#10604]
### Context
*Please explain here below what you were doing when the issue happened*

I made a map, published it, set it to private, and then copied the link and added /embed at the end, and tried to open that at an Incognito window. The map successfuly did not display but Cartofante is still there.

<img width="862" alt="screen shot 2016-11-07 at 9 39 53 pm" src="https://cloud.githubusercontent.com/assets/2013555/20075091/206f6162-a533-11e6-8461-53f4b6033229.png">

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Make map
2. Publish
3. Set to private
4. Open in incognito window, say hello to Cartofante :)

### Current Result
*Please describe here below the current result you got*

 Cartofante

### Expected result
*Please describe here below what should be the expected behaviour*

CARTO or no Cartofante

### Browser and version
*What internet browser (Chrome, Firefox, etc) and version was you using and version* 

 Chrome, v53

### .carto file
*Don't forget to rename .carto file to .zip file to be able to upload to github*

 

### Additional info
*Please add any information of interest here below*

#SMOKE_MM04

**Comment by saleiva** [comment]
Facy preparing something quick for this?

**Comment by MariaCheca** [comment]
cc @CartoDB/design

**Comment by josecruz** [comment]
@saleiva sure!

**Comment by josecruz** [comment]
Done, attaching final design! Not showing logo or brand colors because we want to keep it as off-brand as possible due this screen can be shown on the media
![1440 - 04-03 - private deleted](https://cloud.githubusercontent.com/assets/596509/20175183/da6308d4-a741-11e6-83c3-fc79603e24bf.png)

**Comment by josecruz** [comment]
heyhey! what's the status of this? :D
