### ISSUE TITLE
Disconnecting Github account after signing up with it is odd/buggy

### ISSUE THREAD

**Issue by andrewbt** [CartoDB/cartodb#10602]
### Context
*Please explain here below what you were doing when the issue happened*

I was performing smoke OB03 on staging and decided to do some extra QA. So you sign-up with the Github button, and get directed to your dashboard. That's OK. But if you go to your Account settings page https://andrewbt.carto-staging.com/account, you won't see any "Github connection" setting. All you'll see is a "Disconnect your Google+ Account". But I don't have a Google account connected, I have a Github account connected!

<img width="985" alt="screen shot 2016-11-07 at 5 51 30 pm" src="https://cloud.githubusercontent.com/assets/2013555/20074224/ab0cf216-a52f-11e6-88d3-f1f3daab9f25.png">

Furthermore, if you click that option, which I should not be able to because I _have not yet set a password_, the changes save fine:

<img width="649" alt="screen shot 2016-11-07 at 9 18 12 pm" src="https://cloud.githubusercontent.com/assets/2013555/20074244/bbf8cd8e-a52f-11e6-8c07-bf75dab00942.png">

Oddly enough, even after disconnecting, I am still able to logout and log back in again. So at least that's not broken.

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Create an account with github login
2. Go to account settings, see there is no section about github auth but instead one about Google+ (first bug)
3. Click "Disconnect from Google+" (which is really github and shouldn't be available anyway because you have set no password, second and third bugs) and save changes.

### Current Result
*Please describe here below the current result you got*

 See above...

### Expected result
*Please describe here below what should be the expected behaviour*

A github-linked account should talk about "disconnecting from Github" in it's account settings, not Google. Additionally, this should be prohibited if the account has set no password. This expected behavior _is_ present for Google-linked accounts.

### Browser and version
*What internet browser (Chrome, Firefox, etc) and version was you using and version* 

 Chrome, version 53

### Additional info
*Please add any information of interest here below*

# SMOKE_OB03

**Comment by juanignaciosl** [comment]
cc @CartoDB/builder-backend

**Comment by javitonino** [comment]
Thanks for the detailed report Andrew! This is a mix of unimplemented functionality (disconnecting GitHub accounts) and a bug (it shows the disconnect Google instead).

**Comment by gfiorav** [comment]
I'm taking over this since I have the time now. Will post updates.

**Comment by gfiorav** [comment]
Ok so this is what I gathered:

There is no way of disconnecting a GitHub account from CARTO currently. To fix it we need to increase the level of access required. It might no be worth it. We can forget the Github account id though.

We'd need a design for it in any case.

**Comment by gfiorav** [comment]
Ok so I think that this issue if out of scope for now since we don't have a way to disconnect Github accounts and the bugs described can be attributed to misleading UI rather that actual feature bugs.

When product decides we implement this we'll make a ticket for it. Feel free to reopen if you disagree.

Thanks!
