### ISSUE TITLE
Are we maintaining this?

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#10606]
### Context
cc @jsanz 

hi @javierarce - looks like you worked on [this](https://github.com/CartoDB/oldweather_wwi) a few years ago. 

The Guardian contacted us re: possibly using it - but is this a quick fix? I've made some updates but there are still issues - we're trying to decide if it should be maintained or retired based on how much work is involved to update it?

![e3adc042-9237-11e6-9986-d36b427a811f](https://cloud.githubusercontent.com/assets/1779444/20078272/d8da1fce-a50d-11e6-9ad3-0f9c7cd220d6.png)

**Comment by michellechandra** [comment]
hey @javierarce  - Steph is out for the next two weeks, so I am following up on this issue. Have you had a moment to review? Should I assign to someone else? Thank you!

**Comment by javierarce** [comment]
Hi, @michellechandra & @ztephm: I pushed a fix for the issue… it should work fine now. Sorry for the delay in getting back to you!
