### ISSUE TITLE
Categorical coloring not honored when category filters in place

### ISSUE THREAD

**Issue by pramsey** [CartoDB/cartodb#10605]
### Context
* Making a categorically colored map of political donors
* each donor should get a color according to the party of the donation
* parties have specific "known" colors, so they should not get swapped around, regardless of what the filter is doing

### Steps to Reproduce
* Make a categorical coloring
* Add a categorical widget
* change the filter in the widget
* see if the legend and the map continue to respect your initial categorical coloring

![screenshot_354](https://cloud.githubusercontent.com/assets/113883/20078022/bc3d6840-a4f3-11e6-8182-ebbf26eb57af.png)

**Comment by pramsey** [comment]
Conservatives should be Blue, everyone knows that :) and the "By Value" coloring specifies it, too.

**Comment by ramiroaznar** [comment]
Autostyling is a WIP. Product team is fixing bugs and adding widget customization. This issue is expected to be fixed really soon. :-)
