### ISSUE TITLE
Analysis does not get removed when it's delete while running

### ISSUE THREAD

**Issue by luisbosque** [CartoDB/cartodb#10610]
### Steps to Reproduce

1. Try to create a connect with lines all to all
2. Try to delete the analysis while still running

### Current Result

The analysis is not deleted nor stopped from the DB. However it's removed from the map UI

### Expected result

Delete the analysis from UI but also stop it and delete from the DB

#SMOKE_AN12

**Comment by xavijam** [comment]
How could we do that between Builder <> CARTO.js <> Maps API?
cc @alonsogarciapablo @rochoa @dgaubert.

**Comment by rochoa** [comment]
Duplicates https://github.com/CartoDB/cartodb/issues/8052.
