### ISSUE TITLE
Import stuck in pending state if resque dies at the beginning

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#10613]
### Context
Running smoke tests in a flaky server
 

### Steps to Reproduce
1. Instrument the code to make resque fail when it takes the job. I think it can be done around these lines (but haven't tried it): https://github.com/CartoDB/cartodb/blob/3ea0309cb09d020c43272631c220bc66027d2019/app/models/data_import.rb#L181
2. Import a layer from the Builder UI

### Current Result
- The import gets stuck in `pending` state.
- The UI doesn't stop polling for the state (you can open the network console of the browser and check the requests to get the UI)

### Expected result
Either the import finishes or it is marked as failed.

### Browser and version
Any

**Comment by juanignaciosl** [comment]
Happening today: https://rollbar.com/vizzuality/CartoDB/items/1128/

**Comment by jvillarf** [comment]
Happening today: https://rollbar.com/carto/CartoDB/items/1128/?item_page=0&item_count=100&#instances
