### ISSUE TITLE
When a user goes table overquota generic error is shown in the ui #DT18

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#10616]
### Steps to Reproduce
- create an account with table limit
- try to duplicate a table

it goes over the limit but it shows the generic error (the api returns the right error)

#SMOKE_DT18

**Comment by javisantana** [comment]
@juanignaciosl i think it's not backend, the api returns the right thing 

```json
get_error_text:{title: "Over account table limit, please upgrade",…}
source:"user"
title:"Over account table limit, please upgrade"
what_about:"To upgrade your account, go to your Dashboard and click Settings. Click 'Upgrade your server'. Follow the directions for choosing a larger size and setting up your payment information."
```

**Comment by javitonino** [comment]
There is no table quota in any current plan and only a few old users (looks like tests) have it. Maybe we can just remove the quota altogether.
