### ISSUE TITLE
layers without geometries should be shown in some analysis

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#10627]
This is a wide topic, some of the use cases I found mix tables with geometry and without geometry. For example imagine this case:

- dataset with country names + more info
- dataset with country geometries

imagine I want to do an aggregation per country but be able to filter by some attributes in the first dataset.

I'd use a "filter by second layer" analysis but I'm only able to filter with datasets with geometry

That a case but in general we should take this into account for all the analysis that take more than one input

cc @saleiva @xavijam

**Comment by saleiva** [comment]
Completely agree

**Comment by javisantana** [comment]
BTW, this is not an easy thing, widgets only work well with geometry (because of the bbox) filter so for widgets attached to layers without geometry we should disable the filter (which is possible at api level cc @rochoa)
