### ISSUE TITLE
Dropbox & GDrive connector dataset list does not look how it should

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#10624]
# Dropbox Connector

### Context
When importing a dataset from dropbox the list does not look how it should

### Steps to Reproduce

1. Click Add button inside the builder
2. Click Connect Dataset
3. Connect from Dropbox
4. Authorise Dropbox
5. Wait for the dataset list to charge

### Current Result
![screen shot 2016-11-08 at 11 41 44](https://cloud.githubusercontent.com/assets/596509/20096310/8f4e3ede-a5a9-11e6-90b4-a63b72090050.png) 

### Browser and version
Chrome Version 54.0.2840.71 (64-bit)
 

### Additional info
SMOKE_DS04

------

# GDrive Connector

### Context
When importing a dataset from GDrive the list does not look how it should

### Steps to Reproduce

1. Click Add button inside the builder
2. Click Connect Dataset
3. Connect from GDrive
4. Authorise GDrive
5. Wait for the dataset list to charge

### Current Result
![screen shot 2016-11-08 at 11 56 41](https://cloud.githubusercontent.com/assets/596509/20096602/ea1fc87c-a5aa-11e6-98c0-64c44257b460.png)

### Browser and version
Chrome Version 54.0.2840.71 (64-bit)
 

### Additional info
#SMOKE_DS05

**Comment by xavijam** [comment]
Please @MariaCheca, take care of it.

**Comment by MariaCheca** [comment]
Good one @josecruz!
