### ISSUE TITLE
Thumbnail in dashboard is not refreshed after changing map style

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#10625]
### Context
Running smoke tests.

### Steps to Reproduce
1. Create a new map on top of a polygons table
2. Style it with a choropleth (layer->style->by value)
3. Tweak it a little, change colors to make it very visible
4. Click on the left arrow to get back to the dashboard
(5. Refresh)

### Current Result
The preview thumbnail in the dashboard remains the same.
 
![image](https://cloud.githubusercontent.com/assets/1914276/20096534/9663cbca-a5aa-11e6-82a3-273ac1a6a4a9.png)

### Expected result
The preview thumbnail in the maps dashboard is refreshed and in sync with the style changes.
![image](https://cloud.githubusercontent.com/assets/1914276/20096561/c11a2a30-a5aa-11e6-804b-fbb1ab6bcd4e.png)

### Browser and version
```
Google Chrome	49.0.2623.87 (Official Build) (64-bit)
Ubuntu 14.04 LTS
```
 

### .carto file
[Trump Kills a kitten everytime you edit somebody else's map (on 2016-11-08 at 10.51.17).zip](https://github.com/CartoDB/cartodb/files/577915/Trump.Kills.a.kitten.everytime.you.edit.somebody.else.s.map.on.2016-11-08.at.10.51.17.zip)

 

### Additional info
#SMOKE_MG18

**Comment by javitonino** [comment]
I tried to reproduce, but after a refresh of the dashboard it updated correctly. Also, have logged in to the smokes account and I see the correct thumbnail for that map (similar to the second image, but in blue). Maybe it's just an eager browser cache?

**Comment by rafatower** [comment]
I had my devtools opened and browser cache disabled. The result should be shown with a red palette of colors but cannot guarantee that because somebody was modifying some of my maps.

**Comment by saleiva** [comment]
I confirm this happens to me quite a lot.

**Comment by inigomedina** [comment]
Hey @rafatower, does this issue still make sense?

**Comment by rafatower** [comment]
I could reproduce it again (the image seems cached in the browser), so for some people it makes sense, yes.
