### ISSUE TITLE
Geojson Copy is not centered in the visual design Icon 

### ISSUE THREAD

**Issue by asimcox** [CartoDB/cartodb#10622]
### Context
*Please explain here below what you were doing when the issue happened*
I was trying to upload a geojson dataset and I noticed that the copy is not centered in the box inthe  visual design.
 

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Go to dataset view
2. Drag or browse to upload a geojson dataset
3. Press connect and see that in the icon to the left, the Geojson copy is not centered.

### Current Result
*Please describe here below the current result you got*

 ![screen shot 2016-11-08 at 11 21 37 am](https://cloud.githubusercontent.com/assets/16105514/20096279/7c25403c-a5a9-11e6-8383-6be4e00069a1.png)

### Expected result
*Please describe here below what should be the expected behaviour*

### Browser and version
*What internet browser (Chrome, Firefox, etc) and version was you using and version* 
Chrome, Icognito, Version 54.0.2840.71 
 

### .carto file
*Don't forget to rename .carto file to .zip file to be able to upload to github*

 

### Additional info
*Please add any information of interest here below*

#SMOKE_DT11

**Comment by saleiva** [comment]
Extension was GEO before

**Comment by inigomedina** [comment]
Hey @asimcox, does this issue still make sense?

**Comment by asimcox** [comment]
Hey! @inigomedina - sorry I haven't had time to personally retest this. If it's not reproducible based on the steps in my original ticket, I'd say that it's safe to close :)
