### ISSUE TITLE
Just allow COUNT operation for category widget when a string column is selected

### ISSUE THREAD

**Issue by dgaubert** [CartoDB/cartodb#10621]
### Context
Category widget over string column should show only COUNT operation

### Steps to Reproduce
1. Create a map.
2. Add category widget over a string column.
3. Select AVG, SUM, MIN or MAX operation.
4. Widget fails

### Current Result
![screen shot 2016-11-08 at 11 33 49](https://cloud.githubusercontent.com/assets/1936888/20095815/4fc8de7e-a5a7-11e6-894d-3579129502ef.png)

API returns: 
```
{
    "errors": ["function sum(text) does not exist"],
    "errors_with_context": [{
        "type": "unknown",
        "message": "function sum(text) does not exist",
        "name": "error",
        "length": 196,
        "severity": "ERROR",
        "code": "42883",
        "hint": "No function matches the given name and argument types. You might need to add explicit type casts.",
        "position": "433",
        "file": "parse_func.c",
        "line": "523",
        "routine": "ParseFuncOrColumn"
    }]
}
```

### Expected result
UI must show only COUNT operation for string columns

### Browser and version
Google Chrome Version 54.0.2840.71 (64-bit)
 
### .carto file
N/A
 
### Additional info
#SMOKE_WD20

cc @javisantana @xavijam

**Comment by nobuti** [comment]
Closing in favor of https://github.com/CartoDB/cartodb/issues/10773
