### ISSUE TITLE
Color by category can crash when column contains arbitrary strings

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#10630]
### Context
Running tests:
> Create a legend for a color/category map
 

### Steps to Reproduce

1. Import the .carto
2. Go to the analysis -> maps_multipolygons... -> style -> fill
3. Change the category column to `other_tags`

### Current Result
It issues this error:
```
map_multipolygons_test: style0:3:1 Missing closing ] of filter.
```

### Expected result
It colors the map according to the different values in the columns.
 

### .carto file
[test categories (on 2016-11-08 at 12.47.03).zip](https://github.com/CartoDB/cartodb/files/578172/test.categories.on.2016-11-08.at.12.47.03.zip)

 

### Additional info
#SMOKE_MG29

**Comment by xavijam** [comment]
Could you take a look @javierarce please 💋 ?

**Comment by javierarce** [comment]
I'm afraid this error doesn't belong to frontend.

The style for the column generated correctly: 

```#layer {
  polygon-fill: ramp([other_tags], (#5B3F95, #1D6996, #129C63, #73AF48, #EDAD08, #E17C05, #C94034), category(7));
  line-width: 1;
  line-color: #FFF;
  line-opacity: 0.5;
}```

but if it's applied using the style editor, the tiler returns the error mentioned in the description of this issue: `map_multipolygons_test: style0:3:1 Missing closing ] of filter.`.

![screen shot 2016-11-08 at 16 26 04](https://cloud.githubusercontent.com/assets/4933/20104930/1a93399c-a5d0-11e6-9e12-cf54f9df5d8d.png)
![screen shot 2016-11-08 at 16 26 16](https://cloud.githubusercontent.com/assets/4933/20104931/1a96481c-a5d0-11e6-8d72-4b423ee45c8c.png)

**Comment by javierarce** [comment]
cc: @dgaubert

**Comment by ramiroaznar** [comment]
Fixed!
