### ISSUE TITLE
Improve Loading state of analysis modal

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10632]
### Context
Apart of implementing the new loading modal, text should be other than the one on the screenshot.

### Steps to Reproduce
Just add an analysis with low speed connection

### Current Result

<img width="392" alt="screen shot 2016-11-08 at 14 04 25" src="https://cloud.githubusercontent.com/assets/132149/20100155/7a3cd7fe-a5bc-11e6-872e-3ac257acda0f.png">
 

### Expected result
I propose instead of "Loading Columns..." we say something like "Getting analysis for your data..."

### Browser and version
Chrome

 

### .carto file
*Don't forget to rename .carto file to .zip file to be able to upload to github*

 

### Additional info
*Please add any information of interest here below*

**Comment by arianaescobar** [comment]
This is the same issue as this one: https://github.com/CartoDB/cartodb/issues/10776 

We should decide which message is the correct one (and close one of the issues).

**Comment by piensaenpixel** [comment]
We are going to maintain this one
