### ISSUE TITLE
Deleting an user doesn't delete its layers

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#10635]
When deleting an user, its layers do not get deleted:
 - In `User.before_destroy` the maps are destroyed, but that doesn't destroy the layers. Deleting a visualization works (because there is layer deletion on visualization destruction)
 - Custom basemaps (user layers) are disassociated but not deleted.

cc @CartoDB/builder-backend

**Comment by gfiorav** [comment]
What about this line? https://github.com/CartoDB/cartodb/blob/master/app/models/user.rb#L370

**Comment by javitonino** [comment]
Those are user layers (aka: custom basemaps), and they are only getting unlinked, not removed.
