### ISSUE TITLE
Geocoder fails with Russian cities 

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#10639]
### Context

* A user is trying to geocode a set of Russian cities in BUILDER without success.
* @ernesmb and I have checked that some of the city names are on the dataset from "alternative names" from the "data services" account.

### Steps to Reproduce

1. Create a map with that dataset.
2. Add Georeferencing analysis.
3. Select `City name`, set `city` column as CITY, and COUNTRY as "Russia".
4. Apply.

### Current Result
 
* `0` rows are geocoded.

### Expected result

* All (or most of) the city names should be geocoded.

### Browser and version

* Google Chrome v54.

### .carto file

[russiancities.zip](https://github.com/CartoDB/cartodb/files/578436/russiancities.zip)

### Additional info

* SB:10426790
* CSV file: [russiancitiescsv.zip](https://github.com/CartoDB/cartodb/files/578453/russiancitiescsv.zip)

cc @CartoDB/dataservices @CartoDB/support

**Comment by ramiroaznar** [comment]
Still an issue.

**Comment by ethervoid** [comment]
Have you tried this? Right now the named places georeference is using the street level geocoder

**Comment by ramiroaznar** [comment]
BOOM!

![image](https://user-images.githubusercontent.com/5215798/36543291-a6b3ca00-17e3-11e8-9035-42e36f1a232a.png)
