### ISSUE TITLE
Can set 0 buckets for histogram/time-series

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#10645]
### Steps to Reproduce
1. Create a map
2. Add an histogram widget
3. Set the buckets to 0

### Current Result
The option is saved and the widget displays an error.

### Expected result
It's not possible to select 0 buckets as an option. Maybe we shouldn't let selecting 1 as well, as that's pretty pointless.

**Comment by saleiva** [comment]
Min buckets should be 2 at least.
