### ISSUE TITLE
Enabling builder for org whose owner is not builder yields builder for subs but not owner

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#10640]
### Steps to Reproduce

0. You have an org whose owner is editor
1. Enable builder for org from central

### Current Result

Owner is still editor although org users see builder.

### Expected result

Owner is builder, along with other org members.

cc/ @CartoDB/builder-backend

**Comment by javitonino** [comment]
Unless I'm missing something, this is expected behaviour!

**Comment by gfiorav** [comment]
Thanks for clarifying!
