### ISSUE TITLE
Enterprise User Management API v3 (EUMAPIv3)

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#10647]
**Motivation:**

This is a feature that gets more attention that we give it. The main flaw in v2 is that it's not synchronous. I think it's faster to make a v3 that also improves on RESTness than fixing v2 and breaking existing scripts. I'll leapfrog this if there's no roadmap space for it.

**Goals:**

- [ ] Full REST
- [ ] Batch API (for asynchronous creation/deletion) (https://github.com/CartoDB/cartodb/issues/9791)
- [ ] Groups support (https://github.com/CartoDB/solutions/issues/650)
- [ ] v2 will still work

cc/ @CartoDB/builder-backend @xavijam

**Comment by juanignaciosl** [comment]
Closing automatically because of inactivity. If anybody considers that this still important, please reopen and it'll be prioritized.
