### ISSUE TITLE
Null values getting colored with Turbo Carto class break implementation

### ISSUE THREAD

**Issue by makella** [CartoDB/cartodb#10655]
### Context

When making a choropleth map, null values are getting colored with the default color that in theory should belong to the lowest class break. 

The reason this is happening is because Turbo Carto is making one less class break in the output CartoCSS so anything that does not fall explicitly within the defined ranges gets the default color.
 
### Steps to Reproduce

1. Style by value on the attribute `poverty_per_pop` with the default `Quantiles, 5`
2. Make a pop-up on that attribute
3. Click on Prospect Park or Green Wood Cemetery you'll see the value is null

Turbo Carto output:
`polygon-fill: ramp([poverty_per_pop],cartocolor(Magenta),quantiles)`

Turbo Carto broken down using [this viewer](http://bl.ocks.org/rochoa/raw/4e67ec932e8bb6b17831e0f4a2e0e55d):
- You'll notice that there are only **4 explicitly defined class breaks** and everything else gets the default `polygon-fill: polygon-fill: #f3cbd3;`

```
#brooklyn_poverty {
  
	polygon-fill: #f3cbd3;
  
	[ poverty_per_pop > 0.08955616473399425 ] {
		polygon-fill: #e498b4;
	}
  
	[ poverty_per_pop > 0.1540617568153065 ] {
		polygon-fill: #ca699d;
	}
  
	[ poverty_per_pop > 0.226669708123785 ] {
		polygon-fill: #a24186;
	}
  
	[ poverty_per_pop > 0.3426566252834025 ] {
		polygon-fill: #6c2167;
	}
  	line-color: white;
  	line-width: 0.25; 	
}
```

### Current Result

The result is that null values are getting the default fill color that in theory should be assigned to the lowest class break.

![screen shot 2016-11-08 at 12 32 48 pm](https://cloud.githubusercontent.com/assets/1566273/20113892/8904f9e0-a5af-11e6-8b00-118f15971991.png)

### Expected result

For null values to not get symbolized because they aren't part of the breaks in the data. If you recreate this same map in Editor, you will notice that the null values do not get colored.

### Browser and version
Chrome

### .carto file

[brooklyn_poverty map (on 2016-11-08 at 19.35.40).zip](https://github.com/CartoDB/cartodb/files/579199/brooklyn_poverty.map.on.2016-11-08.at.19.35.40.zip)

### Additional info
I've also put this issue in the Turbo Carto repo referencing here also
https://github.com/CartoDB/turbo-carto/issues/56

**Comment by xavijam** [comment]
Closing this one in favour of https://github.com/CartoDB/turbo-carto/issues/56.
