### ISSUE TITLE
"Other" color in default category ramp "Prism" should be neutral gray, not red

### ISSUE THREAD

**Issue by makella** [CartoDB/cartodb#10656]
### Context
The color for "other" in the default ramp `Prism` should not be that bright red. This was **my mistake** and this is a request to please merge my PR from the CartoColor repo.

The PR is here:
https://github.com/CartoDB/CartoColor/pull/15

### Steps to Reproduce
1. symbolize anything by value > category with the max amount of colors

### Current Result
Other is that bright, horrible red. When actually, it should be a gray and pushed more to the background.

### Expected result
Gray instead of red for "other".

### Browser and version
Chrome

**Comment by makella** [comment]
new PR here based off convo with @rochoa 

https://github.com/CartoDB/CartoColor/pull/16

**Comment by saleiva** [comment]
This should be closed, right?

**Comment by rochoa** [comment]
This one: yes. However we still have some issues that we are tracking in https://github.com/CartoDB/cartodb/issues/11065.
