### ISSUE TITLE
TurboCarto style with conditional styling fails

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10652]
### Context
When applying zoom conditionals to cartocss together with TurboCarto ramps it fails.

### Steps to Reproduce

1. Go to a map
2. Style by value > any category column
3. Go to the CartoCSS panel
4. Change a property (it should work correctly).
5. Now apply a zoom conditional such as 
```#layer{
  marker-width: 0;
  marker-fill: #222;
  marker-fill-opacity: 1;
  marker-allow-overlap: true;
  marker-line-width: 0;
  marker-line-color: #FFF;
  marker-line-opacity: 1;
}

#layer[zoom>=13]{
	marker-width: 1;
}

#layer[zoom>=14]{
	marker-width: 2.5;
}

#layer[zoom>=15]{
	marker-width: 5;
  marker-fill: ramp([primary_type], (#5B3F95, #1D6996, #129C63, #73AF48, #EDAD08, #E17C05, #C94034, #BA0040, #8E1966, #6F3072, #DC1721), category(10));
}
```

### Current Result
It fails giving the following error 
```
crimes_2015: style0:3:2 Invalid code: marker-fill: ramp([primary_type], (#5B3F95 , #1D6996 , #129C63 , #73AF48 , #EDAD08 , #E17C05 , #C94034 , #BA0040 , #8E1966 , #6F3072 , #DC1721 ), category(10));
```
But without the conditional the same line works like a charm.

### Expected result
The style should work/

### Browser and version
Chrome

### .carto file
*Don't forget to rename .carto file to .zip file to be able to upload to github*

 

### Additional info
*Please add any information of interest here below*

**Comment by saleiva** [comment]
cc @javisantana @xavijam @rochoa

**Comment by xavijam** [comment]
Tested in production and for me it is working:
<img width="1440" alt="screen shot 2016-11-08 at 19 38 53" src="https://cloud.githubusercontent.com/assets/132146/20112051/050ee97a-a5eb-11e6-9017-3ae23db5b015.png">

**Comment by saleiva** [comment]
try with a style with hex colors

**Comment by xavijam** [comment]
<img width="1433" alt="screen shot 2016-11-09 at 10 43 52" src="https://cloud.githubusercontent.com/assets/132146/20133858/7795fb54-a669-11e6-9217-d7d8d2376262.png">

**Comment by saleiva** [comment]
but hey, the style on the map doesnt correspond to the one on the Cartocss panel, right? It´s not working

**Comment by rochoa** [comment]
Can you share a .carto?

![screen shot 2016-11-10 at 13 01 57](https://cloud.githubusercontent.com/assets/45346/20176012/f4d4a6ec-a745-11e6-9b8a-30bcf9a6fbd8.png)

![screen shot 2016-11-10 at 13 02 00](https://cloud.githubusercontent.com/assets/45346/20176017/f79306a8-a745-11e6-9084-fa784ba56fb6.png)

![screen shot 2016-11-10 at 13 02 03](https://cloud.githubusercontent.com/assets/45346/20176019/fb336186-a745-11e6-96d8-0ef9194f45a9.png)

**Comment by saleiva** [comment]
will send yo in slack. Its too heavy
