### ISSUE TITLE
Error when running SQL query on Table view

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10650]
### Context
An error should be shown, but looks like the query is loading forever

 

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Create an empty dataset
2. Apply this query
```
INSERT INTO untitled_table (the_geom, name)
SELECT * 
FROM OBS_GetBoundariesByGeometry(
  st_makeenvelope(-87.97027587890624,41.63443345243482,-87.36259460449219,41.98807738309159, 4326),
  'us.census.tiger.census_tract_clipped'
) As m(the_geom, geoid)
```

### Current Result
No error is shown. Only loading all the time

### Expected result
An error, right?

### Browser and version
Chrome

 

### .carto file
*Don't forget to rename .carto file to .zip file to be able to upload to github*

 

### Additional info
*Please add any information of interest here below*

**Comment by saleiva** [comment]
Not happening always.

**Comment by xavijam** [comment]
I can't make it fail in my prod account 😱 .

**Comment by nobuti** [comment]
I can't reproduce it either. Not sure if it would be a good idea to add a `timeout` to that request, but I guess it's not going to be easy to choose the right number.
