### ISSUE TITLE
Cartodb_id set as null when adding new features

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10666]
### Steps to Reproduce

1. Add a feature
2. Try to save or look at the cartodb_id field in the form

### Current Result
It is null, so saving the feature raises an error

### Expected result
Cartodb_id should be an incremental value automatically added

**Comment by alonsogarciapablo** [comment]
![cartodb_id](https://cloud.githubusercontent.com/assets/390398/20144215/345342ba-a69c-11e6-8d1f-b6d8cb0f6f15.gif)

**Comment by alonsogarciapablo** [comment]
I've been able to reproduce this :(

STR:

- Draw a new geometry.
- Update any of the fields.
- Click `Add`
- 💥 

Working on a fix.
