### ISSUE TITLE
Migrated custom infowindow close button doesn't work

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#10669]
### Context
- Close button doesn't work, because it doesn't contain the necessary class `js-close`.

### Steps to Reproduce
0. Choosing a user with the builder disabled.
1. Create a map in the editor, with a dataset of points, for example.
2. Add things in a string column if needed.
3. Add a popup adding any column to it.
4. Make that popup a custom one, selecting it as HTML, save it.
5. Enable the builder.
6. Go to the map in the builder and open a popup.

### Current Result
It works, but you can't close the popup.
 
### Expected result
We should be able to close it

### Browser and version
Any

**Comment by xavijam** [comment]
We should make several things:

- In the close button element, it is an `A` element in the editor infowindow, we have to add a `js-close` class.
- In order to make the scroll work, we have to ass the class `js-content` to the element with class `cartodb-popup-content`.

**Comment by juanignaciosl** [comment]
Alternative: make cartodb.js close the popup for `.cartodb-popup-close-button.close` as well. This is safer, as it doesn't involve parsing, modifying and storing html server side.

**Comment by xavijam** [comment]
yeah, totally agree 👍
