### ISSUE TITLE
Loading bar not appearing on the DATA tab

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10667]
### Context
Sometimes the DATA tab within a layer takes a long time to load. We should show the loading bar there.

### Current Result
The bar is not shown, and only a white area is there.
<img width="403" alt="screen shot 2016-11-09 at 16 42 07" src="https://cloud.githubusercontent.com/assets/132149/20144073/b3bd4b14-a69b-11e6-95aa-21cf64087422.png">

 ### Expected result
We should use the same loader we use everywhere and maybe a couple of placeholders

**Comment by piensaenpixel** [comment]
uhm it's working for me :(
![loader](https://cloud.githubusercontent.com/assets/1214201/20177857/2eaaaa66-a74f-11e6-8c0f-62b80768444d.gif)

**Comment by saleiva** [comment]
It looks like there is a portion of time that the bar is not shown. In staging that happened very often

**Comment by ramiroaznar** [comment]
I was not able to replicate the issue. Closing, we will open it again if this behavior is spotted again.
