### ISSUE TITLE
Applying hexbins over layers with overviews returns an error

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#10662]
### Context
We should wrap the error and check why it is failing
 

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Import the .carto added at the end.
2. Go to style and apply hexbins type.
3. See the error.

### Current Result
It fails and the error is huge.
 
### Expected result
We should check the error itself, but also we should wrap that error.

### .carto file
https://dl.dropboxusercontent.com/u/931536/Vasque%20Country%20Traffic%20Incidents%20%28on%202016-11-09%20at%2014.44.13%29.carto

**Comment by saleiva** [comment]
Only happening with layers with overviews

**Comment by javierarce** [comment]
Ok, pushed a fix for the long error message in the branch `10662-hexbins-error`

**Comment by xavijam** [comment]
Ok, let's close it for the moment, if we see it again, let's open a new one. 💋
