### ISSUE TITLE
Phantom "required" flag during "Join with Second Layer"

### ISSUE THREAD

**Issue by michellemho** [CartoDB/cartodb#10674]
### Context
- While joining with second layer, I noticed a red "required" flag appear and disappear on the top left of the Builder.
- I don't think it's a critical issue, but wanted to point it out! I captured a screen recording here:

[phantom "required" flag.zip](https://github.com/CartoDB/cartodb/files/581720/phantom.required.flag.zip)

 

### Steps to Reproduce
1. Analysis --> Join columns from Second Layer
2. Select a Second Layer
3. Red "Required" flag appears briefly on top left of screen then disappears

### Current Result
- "Required" flag briefly appears then disappears

### Expected result
- No "required" flag should appear

### Browser and version
Chrome Version 52.0.2743.116 (64-bit)
 
### .carto file
[Election 2016 (on 2016-11-09 at 20.04.20).carto.zip](https://github.com/CartoDB/cartodb/files/581726/Election.2016.on.2016-11-09.at.20.04.20.carto.zip)
 

### Additional info
*Please add any information of interest here below*

**Comment by ramiroaznar** [comment]
Closing in favor of https://github.com/CartoDB/cartodb/issues/12098
