### ISSUE TITLE
When latitude or longitude are edited in the input fields, marker in the map is not updated with the new position

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#10672]

**Comment by alonsogarciapablo** [comment]
Working for me right now:

![lat-lng](https://cloud.githubusercontent.com/assets/390398/20151005/cf3b19a8-a6b8-11e6-9d00-f7f0e8ea9e6b.gif)

**Comment by matallo** [comment]
can't reproduce, either

**Comment by xavijam** [comment]
Have you tried with a new point?

**Comment by matallo** [comment]
yeppers, still no clue

**Comment by xavijam** [comment]
## STR

1. Create a map with an empty dataset.
2. Click over the layer in order to add a new feature.
3. Choose the point.
4. Place it in the map.
5. Go to the lat field and change it.
6. It doesn't change in the map.

**Comment by matallo** [comment]
![screen shot 2016-11-10 at 10 10 17](https://cloud.githubusercontent.com/assets/36676/20170784/f77d59d8-a72d-11e6-8b07-458adcdec84d.png)

The feature is updated ok for me (the 0 value was my change), but it's true the geometry editor still remains in the same place. I'll take a look with @alonsogarciapablo

**Comment by xavijam** [comment]
Minor compared with the cid problem, so no rush.
