### ISSUE TITLE
Be able to override legend labels

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10687]
Designs in https://github.com/CartoDB/design/issues/284

**Comment by saleiva** [comment]
This is a requirement for migrating more and more users.
Take this in consideration for migrating legends with custom labels

cc/@xavijam @gfiorav

**Comment by saleiva** [comment]
Just noticed we also have prefix and suffix. Those should be disabled if you override the labels

**Comment by nobuti** [comment]
@saleiva does it make sense we keep the avg label for custom labels in choropleths? should we hide it in this case?

**Comment by saleiva** [comment]
Yes plz!
