### ISSUE TITLE
Error adding layers is not specific when over limit

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#10689]
### Context
Adding a layer to a map using the builder when it is already at its maximum amount of layers. 

### Steps to Reproduce
1. Create a map with 8 layers
2. Add a layer using the add layer button

### Current Result
Generic error:
![screenshot_20161110_162747](https://cloud.githubusercontent.com/assets/7569673/20182649/c5c4ad12-a762-11e6-82ba-fdfee5dc168c.png)

### Expected result
 - Disabling the Add layer button when already at layer limit
 - A more specific error (such as the one that popups when dragging a node while at layer limit)
![screenshot_20161110_162935](https://cloud.githubusercontent.com/assets/7569673/20182683/e7c4a304-a762-11e6-9d66-bde7eb2f91eb.png)

**Comment by urbanphes** [comment]
We finish the ticket on CartoDB/Design
https://github.com/CartoDB/design/issues/634

#### Solve

- On the navbar, we can add the indicator (n/n) next to the item. Like this "LAYER (2/8)". It's a small detail that can help as user a know the limit in all moment.

- When the user add the latest (8) It shows an InfoBox Alert informing about the fact and we give them the possibility to upgrade their plan.

- When the user add the latest (8), the "Add Button" pass to disabled. In this way, we avoid the error on the modal window.

**Comment by saleiva** [comment]
closing since this is being attacked in #12167
