### ISSUE TITLE
Try to not expose layers pointing to non-existant nodes

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#10684]
As we have talked, we will check if there is a broken layer pointing to a non-valid (ghost?) node. If so, we will "recover" the layer pointing to the previous valid source. If there is no previous source, because that layer only had one node, that layer will not be returned. Also, we want to show the error with a notification, so the user at least will notice why that node/layer is not present.

@gfiorav is making his magic, stay tuned.

cc @CartoDB/support @CartoDB/solutions 

Thanks @xavijam! The way I see it (just to expand a bit):

# Synopsis

We want to fix the inconsistencies between layer's `source_id` and the analysis definition. So it's 2 problems to be solved: 

1. Detect inconsistencies.
2. Fix inconsistencies.

## Detect inconsistencies 

The problem is that when you add/remove/edit a `source_id`, two objects need to be updated:

+ Layer
+ Analysis definition

In that event, if you want to "correct" any inconsistencies, you can do it:

1. When updating a layer
2. When updating a definition
3. When presenting a layer

The problem with 1 and 2 is that it's likely that you'll wan't to validate the integrity of a layer or definition when the other part hasn't yet been updated. We can solve this with any regular transaction id protocol-like fix, but it's too much since this is a temporal fix.

So we're left with 3. 3 is a pretty bad solution since it implies modifying things (altering or even destroying Layers based on a definition) on presentation. Since it's a temporal fix, this concern is mitigated. 

## Fix inconsistencies 

The easiest way to do it until the analysis logic lives in the back (and all of this is unnecessary) is to send the previous `source_id` in the layer options. That way when an inconsistency is detected, we can switch back to the previous `source_id`. This won't work for the "drag" case but it's better than nothing.

**Comment by xavijam** [comment]
@gfiorav, edit/add/remove whatever you consider please, it is likely I'm wrong 💋 .

**Comment by ramiroaznar** [comment]
AFAIK this issue with ghost nodes is fixed.
