### ISSUE TITLE
Cannot edit geometry

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#10694]
### Context
In organization users, using the builder, you cannot edit geometries, and the table view in the builder is readonly, due to a conflict with query defaults.

### Steps to Reproduce
1. In an org user, create a map
2. Go to the layer, and try to edit geometry

### Current Result
Readonly (query not default) 

### Expected result
Be able to edit it

### Additional info
Likely related to #10510

**Comment by saleiva** [comment]
Can we prioritize this?

**Comment by javitonino** [comment]
Only waiting for CR, we'll probably deploy tomorrow :)
