### ISSUE TITLE
Delete cached analysis when deleting the visualization

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#10690]
It would be nice to be able to delete unused cache tables when deleting a visualization. However, this might be difficult to do, due to the how the cache tables are stored (per node, not per visualization).

No need to do it now, just something to keep in mind, and maybe talk over when the chance arises.

cc @CartoDB/builder-backend @CartoDB/platform @CartoDB/dataservices

**Comment by juanignaciosl** [comment]
Closing this. This is currently addressed by automatic deletion of unused tables.
