### ISSUE TITLE
Enrich from Data observatory analysis removes '_' from new column name

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10698]
### Context
Since postgresql supports '_' on column names we should respect them if those are entered in the UI.

### Steps to Reproduce

1. Enter to a map
2. Enrich your data
3. Add 'hello_world' as the new column name
3. Apply the analysis.

### Current Result
Analysis runs correctly, but '_' get removed from the hello_world column name when saving

 
### Expected result
Analysis runs correctly, but respecting '_'  on the hello_world column name when saving.

**Comment by ramiroaznar** [comment]
After the changes implemented in this analysis UI, this is not happening anymore.
