### ISSUE TITLE
Filter points in polygons shouldn´t be available for point datasets

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10699]
### Context
This analysis can be only applied to polygons as a source layer

 
### Steps to Reproduce

1. Enter to a map containning a points layer
2. Add an analysis on the point layer
3. Click on filter points in polygons

### Current Result
You can click the analysis even if it will not work

 
### Expected result
Analysis box should be disabled in the modal window

**Comment by arianaescobar** [comment]
It shouldn't be available for line datasets either.

**Comment by ramiroaznar** [comment]
@arianaescobar Don't you think it would be better to apply this analysis to the (target) points layer instead of the (template) polygons layer? For me, as @jsanz [exposed here](https://github.com/CartoDB/solutions/issues/974), it is very unnatural.

**Comment by arianaescobar** [comment]
That sounds more natural to me too, definitely. Although I don't know if there are other constraints to explain why it was originally implemented like this...

**Comment by rubenmoya** [comment]
In production! 🚀
