### ISSUE TITLE
Problem downloading a .carto with asian characters

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#10701]
@CartoDB/builder-backend

**Comment by javitonino** [comment]
This is S3 specific. The problem is that the content-disposition header must be encodable in ISO-8859-1 for some reason (maybe this is configurable).

```
<Error>
<Code>InvalidArgument</Code>
<Message>
Header value cannot be represented using ISO-8859-1.
</Message>
<ArgumentName>response-content-disposition</ArgumentName>
<ArgumentValue>
attachment;filename="倉xxxxxxxxxxxxxcarto"
</ArgumentValue>
<RequestId>B27724418BCC477F</RequestId>
<HostId>
xxxxxxxxxxxxxxxxxxxxxxxx
</HostId>
</Error>
```

**Comment by gfiorav** [comment]
Outch!

How can we address this issue? If we can know before hand, we can host those files in our own infrastructure instead of S3. Although there must be some way for S3 to handle this right?

**Comment by javitonino** [comment]
The problem is just with the header that indicates the downloaded filename. I'd just do something like replace all non-encodeable characters in that header by `-` or something along these lines.

**Comment by gfiorav** [comment]
It _might_ be interesting to try and support those characters. Something that little _could_ give us the upper hand in a very big market.

**Comment by javitonino** [comment]
I think the problem is a limitation with the HTTP protocol (as it doesn't have a way to specify the encoding used in the headers) so I don't have high hopes for a better solution. But agreed, we should try to keep the exported filename in the original form if at all possible.

**Comment by xavijam** [comment]
If the name is correctly set "inside" the .carto, there should not be a problem right?
Could someone take care of this issue during this sprint?
