### ISSUE TITLE
Analysis that not changes the schema shouldn't reset the Styles, infowindows and legends

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10700]
### Context
Not sure if its a dupe. Reseting the styles when applying a new analysis that doesn't change the schema of the data can be very frustrating. A good example is the filter analysis, the AOI analysis on polygons or the Enrich from Data Observatory one.

### Steps to Reproduce

1. Go to a map with a points dataset and customize the style of them
2. Apply a filter analysis to them

### Current Result
Styles are reset

 
### Expected result
Styles, infowindows and legends should be the same

**Comment by xavijam** [comment]
Yeah, that's the thing I have to work on next.

**Comment by xavijam** [comment]
Please, whoever takes this issue should code it with me, pretty please 🙏 .

**Comment by alrocar** [comment]
Stale issue. Closing 👋
