### ISSUE TITLE
Builder tooltip doesn't disappear after mouseover on input

### ISSUE THREAD

**Issue by MariaCheca** [CartoDB/cartodb#10717]
After applying an analysis and changing view in the Builder panel, the tooltip below keeps appearing.

<img width="391" alt="screen shot 2016-11-15 at 10 53 52" src="https://cloud.githubusercontent.com/assets/2141690/20302349/352d79b4-ab27-11e6-9eee-ec536493ac95.png">

cc/ @xavijam

**Comment by ramiroaznar** [comment]
Fixed.
