### ISSUE TITLE
Heatmaps should be done by other values than just point_agg

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10719]
### Context
Heatmaps are very powerful when showing aggregations of values, but right now we only show density on the wizards

 ### Expected result
We should have the aggregation methods available on the style form so we play with the value parameter on cartocss

### Additional info
Rel to https://github.com/CartoDB/cartodb/issues/2125

**Comment by alrocar** [comment]
Stale issue. Closing 👋
