### ISSUE TITLE
Link enter key to the main action in add analysis modal

### ISSUE THREAD

**Issue by MariaCheca** [CartoDB/cartodb#10718]
Maybe we could make the main action respond to the `Enter` key in the 'add analysis' modal.

cc @xavijam

**Comment by arianaescobar** [comment]
ping @alonsogarciapablo 

This is a forgotten great idea, maybe the RT could help us with it at some point.

**Comment by alonsogarciapablo** [comment]
Thanks @arianaescobar! We're in the process of reviewing and categorising all existing issues.
