### ISSUE TITLE
Add style by value to the line width form input

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10716]
### Context
Sometimes is useful to change line-width depending on a value

It should behave exactly in the same way we do the bubble one on the UI, but with different defaults (min = 0.5, max = 1.5).

Pending confirmation from @makella

**Comment by makella** [comment]
Yes! 

We need this for point feature outlines and polygon feature outlines.

**Comment by ramiroaznar** [comment]
Fixed!
