### ISSUE TITLE
Geometries are null when dataset is exported as .gpkg and re-imported

### ISSUE THREAD

**Issue by danicarrion** [CartoDB/cartodb#10714]
### Context

Trying to upload a gpkg dataset previously downloaded with our SQL API
 

### Steps to Reproduce

1. Download the dataset as a gpkg file: https://USER.carto.com/api/v1/sql?q=select * from MY_DATASET&format=gpkg&api_key=MY_API_KEY
2. Then go to the "New dataset" view on the builder and import that file.

### Current Result

Dataset is created alright, except all geometries are null.
 

### Expected result

Geometries should have been kept.

### Browser and version

Chrome 54.0.2840.71 (Linux 64-bit)

**Comment by juanignaciosl** [comment]
@danicarrion I can't reproduce. This is likely to be a dataset-related bug. Could you please send me the dataset in another format?

**Comment by danicarrion** [comment]
I've investigated a little bit. Geometries are _not_ null. It's simply that they appear as null on the dataset view, but you can see the points on the map or see the geometries by doing `SELECT the_geom FROM mytable`.

Anyway, I've tried with a different dataset, and I can't reproduce, so I guess it's dataset-related in any case, so I'm closing this.
