### ISSUE TITLE
Adding a new row should take you to the last page

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10720]
### Context
When adding a new row through the UI, the row is added at the bottom of the current table view, resulting in a Cartodb_id sequence of 38, 39, 40, 15321.  This might confuse some less experienced users – if possible, it might be more intuitive to also automatically navigate to the last 40 rows of the dataset to maintain continuity of the cartodb_id column

### Steps to Reproduce

1. Add a new row when being on the first page
2. Look at the cartodb_id

### Current Result
The row is added at the bottom of the current table view, resulting in a Cartodb_id sequence of 38, 39, 40, 15321. 

### Expected result
We should paginate and add the row there.

**Comment by Jesus89** [comment]
Closed by https://github.com/CartoDB/cartodb/pull/14139

In production! :rocket:
