### ISSUE TITLE
Legend title is not saved after refreshing or embed

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#10723]
### Context

Legend title is not saved after refreshing or embed.

### Steps to Reproduce

1. Create a map.
2. Add a legend.
3. Change title from "pop_max" to "Population".
4a. Publish. Get the embed link.
4b. Refresh the page.

### Current Result

The change is not saved. The legend title is showing "pop_max" instead of "Population".

### Expected result

The legend should display "Population" instead "pop_max".

### Browser and version

Google Chrome v54

### .carto file

* Carto file: [citieslines.zip](https://github.com/CartoDB/cartodb/files/592609/citieslines.zip)
* Link: https://team.carto.com/u/ramirocartodb/builder/45f618e6-a4c4-11e6-aa9a-0ee66e2c9693/embed?

**Comment by saleiva** [comment]
Yep, happening to me as well

**Comment by nobuti** [comment]
The update fails because of #10722.
