### ISSUE TITLE
Icons on custom legends [v0.1]

### ISSUE THREAD

**Issue by urbanphes** [CartoDB/cartodb#10726]
Possibility to add an icon for custom legends.

It would not be possible to implement it until #10746 is implemented.
Design ticket: https://github.com/CartoDB/design/issues/304

**Comment by xavijam** [comment]
This will be done after https://github.com/CartoDB/cartodb/issues/10452.

**Comment by matallo** [comment]
support for cartodb.js already done https://github.com/CartoDB/cartodb.js/pull/1545

**Comment by nobuti** [comment]
PR seems good, but I need more context to understand it fully. I left a comment, waiting for response.

**Comment by nobuti** [comment]
@matallo I'm putting it back to development, I left some comments it would be nice to address, but feel free to obvious them if you consider it's not worth.

**Comment by nobuti** [comment]
Works like a charm 🚀

**Comment by xavijam** [comment]
Tested with and without the feature flag enabled?

**Comment by nobuti** [comment]
Yes, working great in both scenarios.

**Comment by xavijam** [comment]
:+1:
