### ISSUE TITLE
no option to add geometry in polygon layer on a builder map

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartodb#10729]
### Context
For some maps with polygon layers, it appears the option to add geometry by drawing on the map but for others it doesn't.

The polygons layers doesn't have analysis. The error is not always happening, if I add twice the same polygon layer, and for the first layer (a0) CARTO does not allow me to add geometry on the map and for the second layer (c0) it allows me to add a geometry on the map

### Steps to Reproduce

1. Create map
2. Add polygon layer
3. The option/icon  to add geometry on the map does not appear.

### Current Result
![screen shot 2016-11-16 at 19 44 40](https://cloud.githubusercontent.com/assets/11177693/20361107/9fbb4eea-ac36-11e6-8c36-8d4fe4f46779.png)

### Expected result

![screen shot 2016-11-16 at 19 45 15](https://cloud.githubusercontent.com/assets/11177693/20361130/bc66874e-ac36-11e6-8fc8-af872956c08b.png)

**Comment by javitonino** [comment]
Is this an organization user? If it is, then it's very likely related to #10694

**Comment by oriolbx** [comment]
It is, thanks @javitonino !

**Comment by michellechandra** [comment]
S/B: 10533494

**Comment by javitonino** [comment]
Deploying the fix now! https://github.com/CartoDB/cartodb/pull/10708
