### ISSUE TITLE
[analysis] no filter value in layers list 

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#10728]
### Context
from https://github.com/CartoDB/cartodb/issues/7688 

> no visual cue of current selected column

### Steps to Reproduce

1. create a map
1. apply a filter analysis by column value

### Current Result

while in the layer list there is the column name by which the layer has been filtered, there's no hint on the value itself (find attached) 

in this case "arrondissement"
 
<img width="1506" alt="screen shot 2016-11-16 at 16 31 02" src="https://cloud.githubusercontent.com/assets/36676/20353425/11062c08-ac1b-11e6-963c-973531402994.png">

### Expected result

the column value should appear in the layer list

### .carto file

[Untitled Map (on 2016-11-16 at 15.31.21).carto.zip](https://github.com/CartoDB/cartodb/files/595049/Untitled.Map.on.2016-11-16.at.15.31.21.carto.zip)

/cc @javierarce @xavijam @CartoDB/design please attach or point to the designs

**Comment by alrocar** [comment]
Stale issue. Closing 👋
