### ISSUE TITLE
being able to have pluggable frontends

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#10724]
We should be able to have different frontends in the builder so each user can use one.

- Each frontend should be able to change both styling (imagines and fonts included), logic and texts (translations). 

- There should be a main frontend (the one we have) and the others should inherit from it. A proposal could be to have a folder based thing
```
assets/carto_base-4.0.1/...
assets/VENDOR-VERSION/...
```

- each user can use different frontend vendor and version and can be changed at runtime
- it should be possible to develop with both at the same time (so grunt dev should take care of all the frontends)
- all the frontends should work with the available backend
- in the ideal world there should be possible to run it with a static html

**Comment by matallo** [comment]
done, later work adding missing folders in https://github.com/CartoDB/cartodb/pull/11099

**Comment by danicarrion** [comment]
A few caveats:

* Only the `cartodb3` folder is included in this process, but still part of the UI lives on the `cartodb` folder.
* Part of the UI lives in Ruby templates too.
* It's easy to add new items to a locale file, but there's no way to modify existing items without virtually copying the whole file.

I've worked around these problems, but the result is of course something that is not as easy to maintain as expected.

And also, less important, the `watch` task seems to hang after a while, at least for me, so I need to be restarting it manually quite often.

**Comment by javisantana** [comment]
hey @danicarrion could you point to a ruby template where you'd need to change stuff?

**Comment by matallo** [comment]
as per previous discussions `app/views/admin/shared/_footer.html.erb`

**Comment by jorgesancha** [comment]
guys, I'm creating a new issue with the things that Dani mentions to prioritize it before it's too late... Otherwise BCG will easily go down the same road of not being able to merge the master branch

cc/ @saleiva @xavijam

**Comment by danicarrion** [comment]
also: `app/views/admin/shared/_private_header.erb` and I guess there'll be others as we keep going.

thanks!

**Comment by jorgesancha** [comment]
One comment @danicarrion :

> In respect to other assets, only CSS seems to be included, but not fonts or images for instance.

Not sure I understand this one. If you can change HTML and CSS, what prevents you from referring to other images and/or font-faces? Can you provide an example?

**Comment by matallo** [comment]
fonts overrides are definitely included in the bundle

we left images out as Builder has no images in the stylesheets (it can be easily replicated, actually I implemented it and discarded it in the end)

**Comment by danicarrion** [comment]
sorry fonts are indeed included, my bad

**Comment by danicarrion** [comment]
Another thing is how (some) Sass variables are named. For instance, I need links to be green. The color of those links are defined by the variable $cBlue. So I need to either make the $cBlue variable hold a green color value or I need to refactor that variable.

**Comment by matallo** [comment]
both cases are covered, you can use the same variable with a diferent value, as in https://github.com/CartoDB/cartodb/blob/10724-assets-path-example/app/assets/client/stylesheets/variables/colors.css.scss#L1

or you can change where that variable is being used for the proposed value, depending on how fine control do you want

**Comment by danicarrion** [comment]
I know, I know, it was more a remark than an actual issue. Thanks!
