### ISSUE TITLE
Infinite scrollbar in the basemap 

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#10721]
### Context
Scroll is infinite.

### Steps to Reproduce
1. Just go to a builder map.
2. Click over the basemap layer.
3. Go to the last option of the scrolled list.

### Current Result

<img width="464" alt="screen shot 2016-11-15 at 12 04 53" src="https://cloud.githubusercontent.com/assets/132146/20303501/ee161342-ab2b-11e6-847a-74b25c9c930a.png">

### Browser and version
Chrome 54.0.2840.98 (64-bit)

cc @matallo @piensaenpixel

**Comment by ramiroaznar** [comment]
Fixed!
