### ISSUE TITLE
Builder: legend style differences

### ISSUE THREAD

**Issue by lfgreenfield** [CartoDB/cartodb#10736]
@saleiva
### Context
I was working on a map in Builder. I had the goal to create a legend of data which is symbolized based on "category" (it is a data set of social service organizations and each falls under a "service category"). In the Legend > Style window, the legend appears to show the color symbols left-aligned in the legend window. However, when I add the legend, the color symbols are right-aligned in the window. See screenshot below:

![image](https://cloud.githubusercontent.com/assets/10607130/20441524/db7388e6-ad92-11e6-9564-b5f318b62c8f.png)
 

### Steps to Reproduce

1. In Builder, add layer which can be symbolized by value
2. Symbolize that layer by value
3. Add a legend

### Current Result
The legend that was added to the map is different than the legend style that appears in the Legend > Style window, see screenshot below. 

![image](https://cloud.githubusercontent.com/assets/10607130/20441524/db7388e6-ad92-11e6-9564-b5f318b62c8f.png)
 
### Expected result
I expected that the legend added to the map would be formatted the same way as it appeared in the Legend > Style window (with the color symbols left-aligned)

### Browser and version
Firefox 50.0
 

### .carto file
n/a, I don't think this was an issue with a particular file

 

### Additional info
*Please add any information of interest here below*

**Comment by ramiroaznar** [comment]
Moving this issue to Design repo https://github.com/CartoDB/design/issues/350 
Thanks @lfgreenfield for the feedback!
