### ISSUE TITLE
Gradient Legend Not Working - Builder (Style By Column Value)

### ISSUE THREAD

**Issue by michellechandra** [CartoDB/cartodb#10731]
### Context
Gradient legends for maps styled by column value are not working, they do not appear on map when selected as option.

### Steps to Reproduce
Create a map and style by a column value.  
![screen shot 2016-11-17 at 13 29 27](https://cloud.githubusercontent.com/assets/5423288/20408387/172a8b92-acca-11e6-984a-2016a382fa00.png)

Enable legends and choose a gradient legend option. No legend will appear on the map.
![screen shot 2016-11-17 at 13 29 46](https://cloud.githubusercontent.com/assets/5423288/20408397/20be1e76-acca-11e6-83d7-96d62221db10.png)

Choose the custom legend option. However, how does the user know what numbers to input for the gradient with the custom legend? The form is blank.
![screen shot 2016-11-17 at 13 29 37](https://cloud.githubusercontent.com/assets/5423288/20408441/57358c14-acca-11e6-82e4-cf63c27c6447.png)

### Current Result
No legend appears on map when choose gradient legend option. When choose custom legend option, no values are filled in for the gradient options.

cc @CartoDB/support 

S/B: 10530210
S/B: 10532630

**Comment by feihugis** [comment]
It may be due to the browser compatibility issue.
