### ISSUE TITLE
entering three rgb values for basemap color is awkward

### ISSUE THREAD

**Issue by rgdonohue** [CartoDB/cartodb#10737]
### Context

Trying to change the basemap color. The interface currently doesn't allow me to simply enter the three values, but updates the map and closes the element with each value. Would be better to enter a value, tab to the next to enter that value, etc.

![basemap-style-values](https://cloud.githubusercontent.com/assets/1952205/20457940/64596d6c-ae54-11e6-8039-986e7ad21b64.gif)
 

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Go to change the color of the basemap (non-tiled basemap)
2. Select style with the color widget
3. Try entering different values

### Browser and version
*What internet browser (Chrome, Firefox, etc) and version was you using and version* 
 Chrome

**Comment by ramiroaznar** [comment]
Another related behavior is when entering hex value, the UI does not allow you to type the number by number. You have to copy and paste the whole number. Seen during @makella workshop. cc @saleiva

**Comment by ramiroaznar** [comment]
This is fixed.
