### ISSUE TITLE
Can we edit the list of values that appears in a category Widget?

### ISSUE THREAD

**Issue by csobier** [CartoDB/cartodb#10732]
Support reported issue, when adding a category widget:
- CARTO starts applying OTHER as the category name, starting from the 6th option, otherwise you have to use the Search in # category feature (which is hard, if you do not know other available categories to choose from).

![image](https://cloud.githubusercontent.com/assets/13319925/20409155/8b94d23c-ace6-11e6-9c01-6e32c71d6ed2.png)

In this users' case, he only has six categories total from his dataset.

 ### Steps to Reproduce
1. Add a category widget with more than six categories
2. You cannot modify the order of which categories appear from the Widgets? I tried changing the widget operation but that didn't work.

Is there a way to customize the "OTHER" text, and/or change which categories appear?

**Comment by michellechandra** [comment]
S/B: 10520595

**Comment by saleiva** [comment]
We are not planning on customizing the different categories in a way that is not data-driven. We always try to show the most relevant information on the map depending on the aggregation operation. For showing custom items, you can always filter your data and leave only the ones that interest you the most (for example).

What we will implement in the mid-term is the pagination on the widget, so more than 5 categories can be shown there.

**Comment by blobon** [comment]
Sorry, saleiva, but in the CARTOS gallery, there is a sample with well custom items in the widget: https://carto.com/gallery/urban-reviewer/ How did they do???
