### ISSUE TITLE
Builder: Action/tracking notifications "X" close button not functioning

### ISSUE THREAD

**Issue by lfgreenfield** [CartoDB/cartodb#10734]
@saleiva

### Context
As I was working with multiple layers in a single map in Builder, I noticed that the action/tracking notifications were starting to stack on top of each other (see screenshot 1 below). I tried to close out of them (using the "X" as a close button) but the notification was not removed.

Screenshot 1:
![image](https://cloud.githubusercontent.com/assets/10607130/20441035/b46c76a6-ad90-11e6-9906-e23869957816.png)

### Steps to Reproduce
1. In Builder while working on a map, complete multiple actions (adding layer, renaming layer, etc.) and notice the action/tracking notifications appear
2. Try to close out of the action/tracking notification by clicking the "X"
3. Try refreshing the page

### Current Result
I was unable to close-out of the action/tracking notifications. I tried refreshing the page and this only removed the notifications sometimes. Eventually, this was the result from the action/tracking notifications building up (screenshot 2 below):

Screenshot 2:
![image](https://cloud.githubusercontent.com/assets/10607130/20441142/409ec7aa-ad91-11e6-8dc3-1dd8551c38a7.png)

### Expected result
I expected for the action/tracking notifications to close

### Browser and version
Firefox 50.0
 

### .carto file
n/a, not an issue with the files themselves

**Comment by ramiroaznar** [comment]
I was not able to replicate this behavior (I got a message saying "you cannot add more layers, please upgrade your account"), @lfgreenfield could you please share with us the .carto file? I am using also Firefox v50.
