### ISSUE TITLE
Builder: Non-specific error message

### ISSUE THREAD

**Issue by lfgreenfield** [CartoDB/cartodb#10735]
@saleiva
### Context
I was working on a map in Builder with multiple layers. I had 8 layers loaded into the map and tried to add another. I was adding the same layer over and over and filtering the data set differently each time. When I tried to add the layer for a 9th time, I received this error, shown below. I can imagine why this error occurred (the map can only handle a certain number/size of data sets/layers) but am wondering if this message could be written more specifically.

![image](https://cloud.githubusercontent.com/assets/10607130/20441240/b9ca536a-ad91-11e6-9fbe-e7651be6e0cf.png)

 
### Steps to Reproduce

1. Keep adding layers to a map in Builder until you receive this message. I am not sure if this message is because you can only have 8 datasets in Builder or it is limited due to file size capacity.
2. As the error suggests, try to reload the page again. This does not work because I believe the error is due to the amount/size of layers I was trying to add in Builder

### Current Result
This was a non-specific error issue. I could guess that the error was due to the fact that I was trying to add too many layers or too large of layers to the map in Builder. However, the error is non-specific so it did not tell me this. Instead, it suggested I reload, which does not work. 

### Expected result
I did not expect a page reload to work, as the error message suggests. Could this message be written more specifically?

### Browser and version
Firefox 50.0 

### .carto file
n/a, this wasn't an issue with a file itself, just a non-specific error message. 
 

### Additional info
*Please add any information of interest here below*

**Comment by ramiroaznar** [comment]
I was not able to replicate this behavior (I got a message saying "you cannot add more layers, please upgrade your account"), @lfgreenfield could you please share with us the .carto file? I am using also Firefox v50.

**Comment by ramiroaznar** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/5215798/36415433-28a01326-1626-11e8-8c8c-6f933d3776be.png)

**Comment by lfgreenfield** [comment]
Great!! Thank you so much for your time and energy on this.
