### ISSUE TITLE
Choropleth legends does not work

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#10748]
### Steps to Reproduce

1. Create a map
2. Click on layer
3. Click on STYLE
4. Style color by value

### Current Result

* Legends are not generated. When clicking on LEGEND, and add color legend nothing happens as well.

* Error in Network console: `"Definition The property '#/' did not contain a required property of 'prefix' in schema 2b86ee61-584b-53ba-b537-740fa5da34f5#, The property '#/' did not contain a required property of 'suffix' in schema 2b86ee61-584b-53ba-b537-740fa5da34f5#"` 

### Expected result

* Legends should be generated.

### Browser and version

* Google Chrome v54.

**Comment by nobuti** [comment]
Duplicated https://github.com/CartoDB/cartodb/issues/10731
