### ISSUE TITLE
Lost D.O. total measures

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb#10756]
### Context
Measures like total people, total foreigners, etc. are lost from the combo box. At least in **Spain**.

### Steps to Reproduce
Just try to add a Population measure to a points dataset in Spain. The option is not there 

### Additional info
Looks like the values eventually tagged as potential denominators for normalizing are not being offered as measures in the combo. But then you have 'Total dwellings' within 'Housing' category, so this theory hace aguas.

cc @talos @danicarrion

**Comment by saleiva** [comment]
cc @rafatower @ethervoid

**Comment by AbelVM** [comment]
Btw, these measures are available through the API.

**Comment by ethervoid** [comment]
The dataservices function is returning all the data but seems like the builder is not parsing it correctly and doesn't show all the options.

**Comment by ethervoid** [comment]
The problem comes from the group policy used by the `OBS_LegacyBuilderMetadata` function which creates multiples objects for the same tag. 

In the case of Spain, there are 5 different `tags.age_gender` objects and the builder instead of accumulating them, override the key and only the last one is shown.

We should fix the `legacybuildermetadata` to make it group by tag

// @talos

**Comment by ethervoid** [comment]
I'm working on a fix in the builder part to aggregate it instead of override just in case

**Comment by talos** [comment]
Just opened a PR for observatory-extension v1.1.4, which should fix this bug.

**Comment by ethervoid** [comment]
Deployed new version of the observatory with the fix for this bug. @AbelVM could you please re-check if it's all ok, thx! :)

**Comment by AbelVM** [comment]
I see the same options under `age&gender` :(

**Comment by talos** [comment]
@AbelVM could you post a screenshot of the menu with missing measures? It appears to be working for me:

<img width="366" alt="screen shot 2016-11-22 at 10 10 02 am" src="https://cloud.githubusercontent.com/assets/415831/20528910/099a7c0a-b09c-11e6-992b-cf97123a410d.png">

**Comment by AbelVM** [comment]
Looks like it's working ok now, so let's close it.

Thanks mates!
