### ISSUE TITLE
Allow customization of the default icon set per organization

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10754]

**Comment by ivanmalagon** [comment]
Is this somehow related with https://github.com/CartoDB/cartodb/issues/10724 ?

CC @matallo

**Comment by javitonino** [comment]
@ivanmalagon AFAIK, no. This is the possibility for organization to upload assets (for map markers) and all the users in the org can use them. Righ now, marker assets are only uploaded per-user.

**Comment by javitonino** [comment]
Ready to deploy, needs to split migration to own PR
