### ISSUE TITLE
feature request: "add column" prompt for name and type

### ISSUE THREAD

**Issue by michellemho** [CartoDB/cartodb#10765]
## Context

During workshops, we often need people to add columns to existing tables.  This is cumbersome because they have to perform three actions:

1. Add column
2. Scroll to the column, click the column name, enter new text, confirm
3. Scroll to the column again, press the options button, find "change data type", find the necessary data type, confirm

Those three steps are a full ten clicks for the user.  We always lose some people's attention when a few columns need to be added, plus this is very tedious.

## Suggested solution

When "add column" is selected, a full-window popup like what already happens after "change data type" should appear.  This full-window popup should prompt them for a column name and data type immediately.  They can default to the existing defaults, so confirming immediately yields the current behavior.

For most users, that would spare a lot of point-and-click tediousness.  It would also make leading workshops much easier!

**Comment by talos** [comment]
👍 This has been an ongoing interruption since the Editor for me, and has made me generally add columns using SQL API instead of the interface, including during training sessions (because it's way, way faster to use the SQL API).
