### ISSUE TITLE
No way to make category widgets aggregated

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb#10773]
### Context
Let's say you have several restaurants (different brands) and their revenues, and you want to make a "hall of fame" widget with the restaurants by revenue.

### Steps to Reproduce

1. Get any dataset with at least 2 columns like brand (**string**) and revenue (**number**) 
2. Make a map from it
3. Try to add a category widget for the revenue, aggregated (SUM) by the brands
4. Frustration :(

### Current Result
The UI only lets you select COUNT when aggregating by a string column. If you try and try and try, you may find a race condition in wich it lets you use the right combination of values, and it may eventually work. Or not

![image](https://cloud.githubusercontent.com/assets/9017165/20520798/94669a42-b0a8-11e6-9d9b-532d6ef46765.png)

### Expected result

![image](https://cloud.githubusercontent.com/assets/9017165/20520774/8220191c-b0a8-11e6-87d9-7688ed8f0ae6.png)

cc @xavijam @nobuti

**Comment by AbelVM** [comment]
Now, I can aggregate through the UI, but if the value comes form a query instead of being directly available at the dataset, the result is like

![image](https://cloud.githubusercontent.com/assets/9017165/20565124/808c8d68-b190-11e6-8eef-077fb6a9f07a.png)

**Comment by AbelVM** [comment]
Looks like the problem is the order! The nulls on top of the list.

**Comment by saleiva** [comment]
did that happen before? if so, it should be tracked in a separated issue

**Comment by xavijam** [comment]
As I talked with @AbelVM, it is likely it is related with the way we return the data, not with the widgets UI.

**Comment by saleiva** [comment]
Closing since we cannot replicate.
