### ISSUE TITLE
Histogram Filter not working on Microsoft Edge

### ISSUE THREAD

**Issue by jsanz** [CartoDB/cartodb#10777]
### Context
* Using BUILDER UI or the embed the histograms don't filter at all on Edge

 ### Steps to Reproduce
* Take any dashboard and open it with Microsoft Edge
* Try to filter a layer with a histogram widget

### Current Result

* Filters are not applied. `ZOOM` and `CLEAR` labels also not showing up.

![2016-11-22_13 49 12-selection](https://cloud.githubusercontent.com/assets/188264/20524356/8139c7ca-b0ba-11e6-8dfe-4c251d29ee0b.png)

### Expected result

* Filters being applied on the map

### Browser and version

* Microsoft Edge `38.14393.0.0`

**Comment by xavijam** [comment]
Any JS error?

**Comment by xavijam** [comment]
:(

**Comment by jsanz** [comment]
Sory @xavijam, my fault there you go. Also (just in case it's useful) the [HAR file](https://github.com/CartoDB/cartodb/files/606679/edge.har.zip).

![2016-11-22_15 41 58-selection](https://cloud.githubusercontent.com/assets/188264/20527925/7499116e-b0ca-11e6-9afb-5b8ea96f8608.png)

**Comment by miguelarias** [comment]
This is pretty important for an existing customer we are trying to upsell. They will all be using Edge only.

**Comment by xavijam** [comment]
Ok, taking a look right now

**Comment by xavijam** [comment]
Could you @jsanz provide me the .carto?

**Comment by xavijam** [comment]
Moving to deep-insights, where the bug is located.

**Comment by xavijam** [comment]
Issue moved to [CartoDB/deep-insights.js #495](https://github.com/CartoDB/deep-insights.js/issues/495) via [**ZenHub**](https://www.zenhub.com/)
