### ISSUE TITLE
Limits of widgets forms not triggered when changing type of widget

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#10774]
### Context
Switching between widgets edition can surpass the validation limits set in the forms.

![switch widget bug](https://cloud.githubusercontent.com/assets/1078228/20520868/d4b4d690-b0a8-11e6-964e-55b41475b1bd.gif)

 

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Create a widget on a numeric column.
2. Select `Type: time series`
3. In Data section, move `buckets` to the maximum (256).
4. Change to `Type: histogram``
5. As you can see, `buckets` is set to 256. This is an error, since the maximum buckets allowed for histograms are 30.
6. If you move the buckets slider the number is corrected. If you do nothing, it gets saved with 256.

**Comment by ramiroaznar** [comment]
Because the time series widget edition options have changed, it is not happening anymore.
