### ISSUE TITLE
Suggestion for "Join columns from 2nd layer" analysis interface

### ISSUE THREAD

**Issue by mehak-sachdeva** [CartoDB/cartodb#10788]
### Context
While using `Join columns from 2nd layer` analysis, it is often the case that the user would want all columns in the resulting table from the participating tables. The scroll-down and selection of all individual columns within the table is non-intuitive and very cumbersome.

### Suggestion
Add an option to "select all columns" within the `Columns` option for each table to finish merging and retaining all columns in way fewer clicks.

Reference screenshot:

![screen shot 2016-11-22 at 12 14 40 pm](https://cloud.githubusercontent.com/assets/14189245/20540252/5a0304ee-b0ad-11e6-81fa-cc851e14248b.png)

**Comment by saleiva** [comment]
Duplicated! https://github.com/CartoDB/cartodb/issues/9502
