### ISSUE TITLE
Style ramp classification values don't auto-populate legend

### ISSUE THREAD

**Issue by rgdonohue** [CartoDB/cartodb#10785]
### Context
*Please explain here below what you were doing when the issue happened*

When using the custom legend, the classification values from the ramp() function should auto-populate these fields.

![image](https://cloud.githubusercontent.com/assets/1952205/20534423/689df9d2-b09e-11e6-9d2c-1791a950f838.png)

 Also, it's difficult to enter them in manually now given they were generated dynamically within the Style panel.

**Comment by saleiva** [comment]
Interesting. Out of curiosity, Why would you like to use a custom legend in this case and not the available one?

**Comment by rgdonohue** [comment]
If it's important to derive specific values about a particular feature (or area), then having the class ranges explicitly displayed in the legend helps? Like this: [http://bl.ocks.org/rgdonohue/e4754efc6733b456cd59a163c77ef641](http://bl.ocks.org/rgdonohue/e4754efc6733b456cd59a163c77ef641)

Specific values could also be retrieved through a popup, but seeing the class ranges can also give an additional sense of the distribution of the data.

The available legend works well too, but more so for providing the user with a sense of the general distribution.
![image](https://cloud.githubusercontent.com/assets/1952205/20542694/f0e16132-b0bf-11e6-8a57-ef692f5089fc.png)

**Comment by saleiva** [comment]
Understood, exactly what we were thinking. It got out of scope for the first version but we will implement this. We will pre-populate custom legends with buckets values as we did on the Editor. Thanks!

**Comment by michellechandra** [comment]
S/B: 10628876

**Comment by ramiroaznar** [comment]
S/B: 15794108

**Comment by ztephm** [comment]
Enterprise client (15794108) is checking in re: timing for a resolution, are we able to prioritize this?

**Comment by ztephm** [comment]
Hi @ramiroaznar do we have an update re: if this will or will not be prioritized in the near future? Enterprise client is checking in again.

**Comment by ramiroaznar** [comment]
No update. This is an enhancement, so there is no ETA for adding this.

**Comment by alrocar** [comment]
Stale issue. Closing 👋
