### ISSUE TITLE
Action buttons in map are wrong positioned in narrow window

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#10795]
### Context
when in the map view the action buttons (change to table view, add geometry, ...) are wrong positioned if you narrow the viewport
 

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. open a map
2. make the viewport narrow-er

### Current Result

buttons are not aligned with zoom/search 

### Expected result

buttons should be aligned with zoom/search 

### Additional info

![50014fec-a79c-47f0-bb83-f4bec5bd7c80](https://cloud.githubusercontent.com/assets/36676/20558641/596fd8d0-b171-11e6-85fe-e2f6366e895d.png)
![fad51cc2-541c-4fba-b17e-4a51ab7f514d](https://cloud.githubusercontent.com/assets/36676/20558642/59756354-b171-11e6-86ad-b093180fa4a2.png)

**Comment by rubenmoya** [comment]
Not happening anymore, closing!
