### ISSUE TITLE
Destroy visualizations before users to avoid state fk issue

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#10792]
### Context

The state model has an FK relation with the visualisation model. This means that when removing a user, if visualizations with states are still present, an error is produced.

**Comment by javitonino** [comment]
Fixed more or less by accident in https://github.com/CartoDB/cartodb/pull/10816, by deleting all visualizations before destorying the user.

**Comment by gfiorav** [comment]
How does this work when a layer comes from a shared table? Is it deleted as well?

**Comment by javitonino** [comment]
Yup, with the latest commit.

**Comment by gfiorav** [comment]
Can this be closed @javitonino ?

**Comment by javitonino** [comment]
Yup ✨
