### ISSUE TITLE
Allow deletion through EUMAPI

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#10797]
### Context
* If an organization user is not in Central API deletion won't work.

### Steps to Reproduce
1. Create a user.
2. Drop his entry manually only from Central (a delete at the console).
3. Try to delete it with the EUMAPI.

### Current Result
* Crashes with `CartoDB::CentralCommunicationFailure: Application server responded with http 200: {"errors":["No organization user found with username <USERNAME>"]}`

### Expected result
* User is deleted. Even though This Should Not Happen™ some errors or experiments do lead to some inconsistencies.

### Known workaround
* Although EUMAPI fails, deleting it at the organization owner UI works. In fact, we should consider moving that logic downstream to a common point at the code.

cc @xavijam @CartoDB/builder-backend @CartoDB/community @CartoDB/research @CartoDB/solutions

**Comment by gfiorav** [comment]
I'd make this a feature of EUMAPIv3. Here's the meta ticket: https://github.com/CartoDB/cartodb/issues/10647

**Comment by juanignaciosl** [comment]
IMHO it's a bug, because it's not consistent with the UI. Not hard to change.

**Comment by gfiorav** [comment]
I'll admit I read it wrong, this should be fixed. Any how it's pretty low priority from my point of view. v3 might arrive earlier (though this should still be fixed for v2 users)
