### ISSUE TITLE
Language inconsistency for blue side panel bar

### ISSUE THREAD

**Issue by namessanti** [CartoDB/cartodb#10803]
### Context

In the main _tour of builder_ screen that walks you through the basics of using the builder, the blue bar is referred to as the _Toolbar_ but in the options screen it's referred to as _show blue bar_ 
![screen shot 2016-11-22 at 10 24 28 am](https://cloud.githubusercontent.com/assets/9421671/20567704/cbfc67e2-b167-11e6-9d66-a1edc5e79514.png)

![screen shot 2016-11-22 at 10 25 20 am](https://cloud.githubusercontent.com/assets/9421671/20567722/d1ba1c6a-b167-11e6-85e5-444f3d386f9f.png)

### Additional information
I believe _toolbar_ is more descriptive than _blue bar_

@saleiva

**Comment by saleiva** [comment]
plz!

**Comment by brittanymicek** [comment]
+1 to _Toolbar_
