### ISSUE TITLE
Looks like the category widgets are displaying the NULLs on top

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb#10806]
![image](https://cloud.githubusercontent.com/assets/9017165/20573187/ece1c8ca-b1ae-11e6-915e-c72e0e433ce6.png)

**Comment by AbelVM** [comment]
As described here https://github.com/CartoDB/cartodb/issues/10773#issuecomment-262584795

**Comment by saleiva** [comment]
Only after doing a query, right?

**Comment by AbelVM** [comment]
Looks like even with plain datasets `SELECT * FROM mytable`

**Comment by saleiva** [comment]
closing since we cannot replicate, but keep an eye on it
