### ISSUE TITLE
Time series widget overly exact about ranges

### ISSUE THREAD

**Issue by pramsey** [CartoDB/cartodb#10807]
### Context
I have data for 12 years. When I draw a range on the time-series, it tells me the start/end times to the second.

![screenshot_73](https://cloud.githubusercontent.com/assets/113883/20573328/1aafb49c-b164-11e6-95d5-4898a8c2c78e.png)

### Expected result
One of the configurations on the time series widget should be the granularity of display for the times. (In my case, a granularity of a day would be fine, or maybe even a month)

**Comment by saleiva** [comment]
Asbolutely, the open issue - that of course I cannot find now - was asking to do that granularity guess automatically based on the range of the data, but having a parameter sounds good.

**Comment by xavijam** [comment]
Blocked until design is ready (and if it is done, mockup is done).

**Comment by arianaescobar** [comment]
_Here the visuals™_

![2a77ce90-fd19-11e6-8293-e257aaf869c6](https://cloud.githubusercontent.com/assets/16247628/23502958/036831d2-ff3a-11e6-89b2-6cd4407205c9.png)

**Comment by ivanmalagon** [comment]
Aggregation to be done in https://github.com/CartoDB/cartodb/issues/12088

**Comment by xavijam** [comment]
Already deployed! 💃
