### ISSUE TITLE
Category widget filtering/styling behavior

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#10805]
### Context
When using a Category widget to filter features, the category style changes dynamically, along with the legend bullets. It does so by assigning the first color in the ramp to the first category in the current selection, second color in the ramp to second selected category, etc

However, this leads to a situation where the map categories change drastically from what was designed in the first place (through `STYLE` tab), and for example red can become green or vice-versa, making the map difficult to read

Having the style adapt dynamically to widget filtering is great, but maybe it makes more sense for histogram widget/choropleth visualizations than for categories. 

### Steps to Reproduce
1. Create a map and assign a category style
2. Add a category widget for the same column
3. Filter data

### Current Result
Map features and legend bullets change dynamically to the current filtering, overriding the category style 

### Expected result
In category widgets, respect the color assigned to each category

### Additional info
I know this isn't an easy topic, as it has been discussed before and there are a lot of things to take into account, but maybe it's worth revisiting

**Comment by saleiva** [comment]
Assigning to this sprint just in case we tackle the auto-style fixes

**Comment by xavijam** [comment]
It is not related with auto-style things.

**Comment by saleiva** [comment]
It should right?

**Comment by saleiva** [comment]
Feel free to change the tags or reassign/whatever

**Comment by rochoa** [comment]
So what we want is to have the old editor behavior when creating a category map, don't we?

**Comment by saleiva** [comment]
yep yep

**Comment by rochoa** [comment]
Does that mean we want to have _static_ legends for categories?

**Comment by saleiva** [comment]
From my understanding, if we have a way to say windshaft render this color for this category, the legend would work, right?

**Comment by rochoa** [comment]
But once your data changes you are trapped to the fixed colors you decided in the first place. You don't want that.

All countries:
https://team.carto.com/u/rochoa/builder/17bb226c-b592-11e6-92b3-0ecd1babdde5/embed

vs

All countries but top 3:
https://team.carto.com/u/rochoa/builder/17bb226c-b592-11e6-92b3-0ecd1babdde5/embed?state=%7B%22map%22%3A%7B%22ne%22%3A%5B-87.94096618407002%2C-196.171875%5D%2C%22sw%22%3A%5B87.9535588895499%2C196.171875%5D%7D%2C%22widgets%22%3A%7B%2280d35c35-8b28-4fbc-ac2e-36f483c2fa61%22%3A%7B%22acceptedCategories%22%3A%5B%22Brazil%22%2C%22Canada%22%5D%7D%7D%7D

Now, imagine I filter out the top 10 countries but I fixed the first 10 colors, what would you get for the new top 10 countries (11th-20th countries from whole dataset)? If you don't assign colors dynamically based on the filtering you won't be able to assign any color to those countries.

Probably, we want to provide an option to make colors fixed/hardcoded when you don't want them to change based on filters, but I'm not very inclined.

**Comment by xavijam** [comment]
cc @nobuti

**Comment by xavijam** [comment]
PR: https://github.com/CartoDB/cartodb/issues/10972.

**Comment by nobuti** [comment]
Waiting a window to deploy to staging.

**Comment by xavijam** [comment]
Closed! thanks @nobuti.
