### ISSUE TITLE
Getting the sharing link requires opening map in edit mode?

### ISSUE THREAD

**Issue by pramsey** [CartoDB/cartodb#10808]
### Context
I have a nice map, it's been shared at "link" level. I forget what the link was and I want to send it to a friend or twitter it.

![screenshot_76](https://cloud.githubusercontent.com/assets/113883/20573740/277891b0-b166-11e6-8906-38c408ad599f.png)

If I click the "Link" box, I get the sharing options, which is fine, but the Link sharing option doesn't allow me to copy the actual link.

![screenshot_75](https://cloud.githubusercontent.com/assets/113883/20573756/3ca3ed3c-b166-11e6-85bc-074c3fc1ceb5.png)

The only way I've self-discovered to get the link is to open the map in edit, and then republish it, at which point I get the link copy option. 

It seems like getting the link should be part of the dashboard level info, not require entering the editor.

**Comment by saleiva** [comment]
good spot. We are planning the redesign of the dashboard, we will attack this then! Thanks!

**Comment by alrocar** [comment]
Stale issue. Closing 👋
