### ISSUE TITLE
map does not adapt map view to show all information of infowindows

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartodb#10810]
### Context
If you enable the Popups option of a Builder map and click on a geometry that is located at the corner of the screen, when you click on the geometry and the infowindow appears, the view of the map does not adapt the center view for the infowindow, part of the infowindow is hided by the limits of the screen.

 
### Steps to Reproduce

1. Create a map with CARTO
2. Enable the infowindow popup
3. Click on a geometry that is near the limits of the screen/map view
4. Part of the infowindow is hided by the limits of the screen/infowindow and you need to change the map view manually to see all the information of the infowindow.

### Current Result
This is the current result when you click on a geometry that is near the limits of the screen/map view.

![screen shot 2016-11-24 at 10 51 55](https://cloud.githubusercontent.com/assets/11177693/20594156/6ea5ff30-b235-11e6-9bb3-34651b8b4ddc.png)

 
### Expected result
It is expected that the center view of the map will change in order to show all the information of the infowindow

**Comment by xavijam** [comment]
That's a problem from CARTO.js, reassigning and moving there @alonsogarciapablo.

**Comment by xavijam** [comment]
Issue moved to [CartoDB/cartodb.js #1509](https://github.com/CartoDB/cartodb.js/issues/1509) via [**ZenHub**](https://www.zenhub.com/)
