### ISSUE TITLE
Importing a csv prefers lat/long columns over the_geom

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#10814]
### Context
Importing a csv file with polygons in `the_geom` and also a `latitude` and `longitude` columns.

### Steps to Reproduce
1. Import `counties_ny_latlng.csv` (attached)

### Current Result
The geometry is a point taken from latitude and longitude columns.

### Expected result
The geom is a polygon taken from `the_geom` column.

### Data: 
[counties_ny.zip](https://github.com/CartoDB/cartodb/files/611277/counties_ny.zip)

Also contains `counties_ny_no.csv` which has the latitude and longitude columns renamed and imports fine.

**Comment by rafatower** [comment]
it shouldn't do that if you don't set the type guessing flag on

**Comment by rafatower** [comment]
I checked it and worked as expected (just uncheck the "Let CARTO automatically guess data types and content on import" ). I'd close this unless you really think this has an impact on users. Otherwise that might happen in the next trip to Malaga :D

**Comment by javitonino** [comment]
The problem then is that you get everything as text fields (e.g: no autodetection of integer fields), but I agree it is a decent workaround. If it's not an easy fix, let's close this (or send it to backlog).

This came up using a migration script that exports to csv from one carto account and then reimports to a different one. Using csv might not have been the best idea, can you suggest what the best format would be for that?

**Comment by rafatower** [comment]
I see your point. Isn't `.carto` more suitable for that?

**Comment by rafatower** [comment]
(or gpkg)

**Comment by javitonino** [comment]
Yep, `.gpkg` I think is the better format for lossless export+import. I didn't use it because of https://github.com/CartoDB/cartodb/issues/9559 (it adds a fid column after export+import, and does funky stuff if the original dataset had an fid column). With `.carto` using gpkg as default, maybe we should address that.

**Comment by rafatower** [comment]
I'm still lacking a bit of background info, cause I think systems already got a reliable migration script to move user tables around but, in any case I'll prioritize #9559 over this ticket :+1:

**Comment by javitonino** [comment]
As discussed in the comments, we solved the original issue by fixing the `.gpkg` import/export process so it is lossless.

This makes sense as it is (behaviour depends on content-guessing flag) and no user has complained. I withdraw my complaint, I think we can close this.
