### ISSUE TITLE
Widget configuration error when `DYNAMIC` is set to `NO`

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#10817]
### Context
The bullet point to set the `DYNAMIC` parameter to either `YES` or `NO` in widget's configuration breaks after selecting `NO` 

### Steps to Reproduce

1. On a map, add a widget of any kind
2. Set `DYNAMIC` to `NO`

![screen shot 2016-11-24 at 14 48 39](https://cloud.githubusercontent.com/assets/10940006/20601969/9a982034-b25b-11e6-96d6-02cc3743a06c.png)

3. Go back to exit the widget configuration
4. Open widget configuration again, there is no bullet point, although the widget continues behaving as expected 

![screen shot 2016-11-24 at 14 55 33](https://cloud.githubusercontent.com/assets/10940006/20602025/d058c656-b25b-11e6-8577-16176cfecd5a.png)

### Current Result
Bullet point disappears after setting `NO`

 

### Expected result
Bullet point should show the current setting

**Comment by michellechandra** [comment]
S/B: 10720998

**Comment by noguerol** [comment]
Already fixed.
