### ISSUE TITLE
Open discussion: Legends appearing automatically

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#10818]
Hey everyone :)

I (with the support of @piensaenpixel and @urbanphes) would like to reopen a discussion about legends appearing automatically on Builder. From an UX standpoint, it's quite annoying and I strongly believe we shouldn't make them appear on its own. 

Thoughts? @xavijam @saleiva

**Comment by urbanphes** [comment]
I agree with @arianaescobar. It's a bit strange that the legends showed when I don't configure it.
