### ISSUE TITLE
Color picker bug when hitting 'Enter' in custom ramps

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#10828]
### Context
When creating a custom color ramp, hitting 'enter' in the color picker closes `by value` screen and moves to `solid` without applying the change

### Steps to Reproduce
1. Open a map and go to `STYLE` in a layer
2. Click on the color bar and select `by value` and select a column
3. Select 'Custom color set'
4. Select any bucket of the ramp and enter a HEX color code, as `#FABADA`
5. Hit enter

### Current Result
The color picker **moves to `SOLID`** and applies the color to all features, not only to the bucket we were setting up 

### Expected result
Hitting enter should apply changes but don't close the window or move to `SOLID` parameters

### Additional info
Hitting 'Enter' is a rather automatic gesture, that applies the changes without closing the window in other parts of the application. 

This bug could lead to some frustration after manually configuring each bucket in the ramp and accidentally hitting 'enter' at the end

**Comment by ramiroaznar** [comment]
Fixed. @ernesmb please reopen it if needed.
