### ISSUE TITLE
Export as an image

### ISSUE THREAD

**Issue by urbanphes** [CartoDB/cartodb#10822]
This is one of the pending functionalities from Editor. Basically the user could export the map viewport to an image. There will be several options to be chosen like:

- The size (width and height) by typing the pixel size.
- Drag handles of the export bounding box to manually resize the image.
- Image extension.
- ~Show legends~ -> not for the moment.
- ~Show widgets~ -> not for the moment.

Of course the creation of the map image will need some time, that's the reason why we need a loading modal window. Similar to the export map functionality.

## Some tips

- Map controls should not be present in the image or in the preview.
- Map attribution should appear YES or YES in the right bottom corner (check design).
- We should not remove anything from the map in the preview (like legend, widgets, map controls,...), we could "hide" (tricky way) those and when user finishes with image-export, display again those elements.
- Take care of image exports when a torque style (animated or pixel) is applied, would it work?.

---
Design: https://github.com/CartoDB/design/issues/340
PR: https://github.com/CartoDB/cartodb/pull/11789

**Comment by jorgesancha** [comment]
Note that the strict requirement is to export to PNG. If adding JPG is hard, we should wait to see if it makes sense to prioritise or not.

**Comment by xavijam** [comment]
It is already implemented in the Maps API, so no difficulty added.

**Comment by xavijam** [comment]
Also, https://carto.com/docs/carto-editor/maps#export-image.

**Comment by javierarce** [comment]
One question regarding this ticket. Technically, for maps that use Google Maps basemaps we can generate an image that shows the geometries, but not the basemap below… should we want to warn users about this somehow?

**Comment by xavijam** [comment]
cc @noguerol @saleiva @asimcox

**Comment by javisantana** [comment]
good news -> https://developers.google.com/maps/documentation/tile/

**Comment by javisantana** [comment]
but, for that case google maps has a static maps api so we could reach that api and merge frontend side

**Comment by rochoa** [comment]
Bad news.

Yesterday I talked with @javierarce and @xavijam about how to solve this using existing static images from named maps (as we do for the dashboard previews). The named maps static images can use zoom, longitude, and latitude params.

However, that doesn't consider applied filters to the map and will export images with no filters applied, so we cannot rely on that functionality for exporting the images. We will need to use the current map instance to retrieve the adequate version (with filters applied) of the map in sight.

**Comment by javierarce** [comment]
Ok, we'll need to use `cdb.Image`, but it seems it was removed some time ago (because it didn't work?):  https://github.com/CartoDB/cartodb.js/commit/2834c95959a09b1ad57500b6c0f4eff75ab6b1e3

cc: @alonsogarciapablo

**Comment by javierarce** [comment]
After talking with @rochoa, @alonsogarciapablo & @xavijam last week, we decided to reenable the static image generation functionality that we previously had in the current v4 version of cartodb.js. Initially, we won't be supporting the exact same API that `cdb.Image` had, just the minimum methods to generate an image from a visualization.

We also decided not to support static maps with basemaps with google maps at this moment, so the static maps in that particular case will only show geometries. @urbanphes and @noguerol: we should see if in that particular case we should show a message to our users.

**Comment by noguerol** [comment]
So, considering the last comment, we probably have a problem regarding the current Google + image export use case we should attend, right @javisantana?

**Comment by javierarce** [comment]
@alonsogarciapablo tells me that in the case of a private dataset, we'll need to use the API key. I imagine that we won't want to expose it in the UI (a user could accidentally pick the URL and paste it in a website). 

What should we do in that case? Should we hide the URL when the map is private and only allow to download the image?

**Comment by alonsogarciapablo** [comment]
Also, we should take into account that the image URL will "expire" (i.e: not work) after some time. IMHO, we shouldn't expose it in the UI.

**Comment by javierarce** [comment]
I agree, although don't know if the use case is to have a URL, download the image or both, @noguerol.

If it's just having an image, we could use the same solution as in the previous version of this feature: the URL that appeared linked to the image object (see bottom of the page), so in the regular case it wasn't possible to grab the URL (only when using the advanced mode was possible to get it)

![screen shot 2017-03-14 at 15 43 48](https://cloud.githubusercontent.com/assets/4933/23906028/226ce4be-08cd-11e7-8ca2-d2c4db3ac7ee.png)

**Comment by noguerol** [comment]
We should not expose the API key. We can enforce the image download via html, right?

**Comment by noguerol** [comment]
@alonsogarciapablo those temporal urls could work without being logged in? Because in that case this could be a liability and we should think about a way to obscure the url.

**Comment by javierarce** [comment]
>> We can enforce the image download via html, right?

Yes, see the attached picture in my previous [comment](https://github.com/CartoDB/cartodb/issues/10822#issuecomment-286443744).

**Comment by alonsogarciapablo** [comment]
> @alonsogarciapablo will those temporal urls work without being logged in?

Yes, they are "public" URLs.

**Comment by javierarce** [comment]
Here's a summary of the things we've talked offline between us: 

- We'll implement the integration with the Static Google Maps in the frontend/builder side and not cartodb.js.
- The implementation will be tracked on its own issue.
- We'll add a feature a flag for this feature and release it without the Static GMap integration, to speed up the release of the feature.

**Comment by noguerol** [comment]
Problem to the url issue is we can not have users sharing images with third parties with an exposed api key. I propose we get rid of the final download modal window and we directly trigger download from the "export" button in the export pane.

**Comment by javierarce** [comment]
Ok, another change we've discussed offline with @noguerol & @urbanphes:

- Since we can't expose the URLs, that makes the modal unnecessary… we are going to get rid of it and download the image when users click on the export button (while the image is being generated, we'll disable the Export button)
- @urbanphes will create a ticket to design a button with a loader (but we won't be using it in the first iteration of this feature)

**Comment by urbanphes** [comment]
We have a button loading that we can use for this case.
When you update the map, this button has a loading icon inside the button.


![pasted image at 2017_03_16 11_36 am](https://cloud.githubusercontent.com/assets/14546701/23992389/f560ebb6-0a3c-11e7-9861-d6b9a507b102.png)


cc/ @javierarce @noguerol

**Comment by xavijam** [comment]
Oh, that's true, good catch 💋

**Comment by noguerol** [comment]
Oh nice @javierarce what do you think

**Comment by javierarce** [comment]
I think is time to implement it ;)

**Comment by saleiva** [comment]
:*

**Comment by noguerol** [comment]
Chavales, this is looking good. Some things: 

1. We are including our logo in the images, as @xavijam suggested, but this goes to another ticket
2. Out of bounding box image crop should be provided, specially because our low resolution users will probably be the ones using more this feature. We are showing an "out of viewport" notification with a reset button next to the size input, as @xavijam suggested cc @urbanphes 
3. Maps with custom color basemaps only export geometries cc @alonsogarciapablo

**Comment by saleiva** [comment]
About point 2. that was second version if I don't recall wrong

**Comment by alonsogarciapablo** [comment]
> 3. Maps with custom color basemaps only export geometries cc @alonsogarciapablo

@javierarce is going to update CartoDB.js cause it was a bit behind. Let's try again with latest changes.

**Comment by noguerol** [comment]
@saleiva true, but we had to give support to that in order to support crop selection free movement, which is required, but this opens a UI conflict with crop areas out of the viewport bounds.

**Comment by saleiva** [comment]
I don't get the dependency @noguerol. I'd just force the crop selection area to be inside the viewport.

**Comment by noguerol** [comment]
Well, then I'm happy we have already developed it out of the scope, even if it was by accident, as it will be much of a need for corporate low res scenarios.

**Comment by xavijam** [comment]
It is blocked until we don't have https://github.com/CartoDB/cartodb.js/pull/1598 merged in CARTO.js.

**Comment by saleiva** [comment]
@noguerol apart from you, @urbanphes should also pass acceptance here :)

**Comment by xavijam** [comment]
Ok, I didn't know but we have two dependencies:

- [ ] [Windshaft-cartodb](static-maps-layers-filter) `static-maps-layers-filter` branch.
- [ ] [CARTO.js](https://github.com/CartoDB/cartodb.js/pull/1598) PR with new export image functionality.

**Comment by xavijam** [comment]
Deploying frontend changes, but ticket will keep opened until we have all pieces in production 🤗 .

**Comment by xavijam** [comment]
CARTO.js problem fixed and in production, thanks @alonsogarciapablo 💋 .

**Comment by rochoa** [comment]
Maps API changes have been promoted to production 🎉 .

**Comment by xavijam** [comment]
MÁQUINAS!
