### ISSUE TITLE
Summarize map view stats when attempting to delete a map

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#10824]
@saleiva commented on [Wed Nov 09 2016](https://github.com/CartoDB/design/issues/333)

https://github.com/CartoDB/cartodb/issues/10664

---

@arianaescobar commented on [Wed Nov 23 2016](https://github.com/CartoDB/design/issues/333#issuecomment-262486750)

@saleiva at this stage maybe?
 
![screen shot 2016-11-23 at 12 09 36](https://cloud.githubusercontent.com/assets/16247628/20559629/c4eab838-b175-11e6-8d64-1f38c6aaf55b.png)

---

@arianaescobar commented on [Wed Nov 23 2016](https://github.com/CartoDB/design/issues/333#issuecomment-262488323)

Also, besides map views and likes, is there any other stat we can/want to give? 

---

@saleiva commented on [Wed Nov 23 2016](https://github.com/CartoDB/design/issues/333#issuecomment-262494988)

Yep, but that's not the last version of the modal. Try to delete from inside a map to see the last version

---

@arianaescobar commented on [Wed Nov 23 2016](https://github.com/CartoDB/design/issues/333#issuecomment-262523626)

This is what I propose:

![105 delete map warn](https://cloud.githubusercontent.com/assets/16247628/20564832/429f01da-b18f-11e6-9b40-84e704f97069.png)

tagging @brittanymicek @vuxita for copy review 

---

@saleiva commented on [Wed Nov 23 2016](https://github.com/CartoDB/design/issues/333#issuecomment-262589039)

Total map views are not so relevant, since a map that was very popular 2 years ago can be irrelevant now. ( I imagine the poor map sitting alone in the middle of nowhere in the deep web).

Why don't we use icons for illustrating likes and mapviews? I just love ❤️ s

---

@brittanymicek commented on [Thu Nov 24 2016](https://github.com/CartoDB/design/issues/333#issuecomment-262667428)

Hola @arianaescobar !

Here is some updated copy! Let me know what you think/questions!

## Are you sure you want to delete: "Populated places on Earth"?[1]
This map was **created on **May 6, 1987**** and has **4,670 views**, **35 likes**, and **0 shares**. [2]
**NOTE:** You can export {name of map} as a .CARTO file to {reason they might want to export the viz}. Once your map is deleted it cannot be recovered. Please be sure before proceeding. [3]

[CANCEL] [YES, DELETE]

1. This question should lead and be in the largest font. It allows the user to skip reading the remaining content that is not necessarily relevant (since they have decided to delete the map and the below copy is just informational). Additionally, the question corresponds with the answer options of: CANCEL and YES, DELETE.

Providing the sharing stat might be useful information in helping a user decide whether or not to delete their map. Maybe they want to share this map but hadn't considered it or maybe despite the amount of views the map still wasn't shared or was shared quite a bit. Additionally, adding a date of creation or a time estimate ("This map is 6 months young") might be a helpful stat.

2. To @saleiva 's suggestion - icons: creation: a calendar or clock; views: eyeball; likes: heart; shares: recycle symbol. I'm sure you'll think of cooler ones! ;)

3. I am not sure what the point of telling them that they can export the map as a .CARTO file is. Why would someone be at this stage and want to export their map as a .CARTO file? Are we assuming they are deleting the viz for more space and exporting the map will allow them to save the viz in some way? Also this is important information and should be higher positioned as well as the same font as the rest of the copy in the body.

xoB

---

@arianaescobar commented on [Thu Nov 24 2016](https://github.com/CartoDB/design/issues/333#issuecomment-262804527)

Thank you @brittanymicek!! 

A few comments:

- In case we'd like to add a date, I would suggest adding when it was last updated rather than when it was created. I think it has more value than the creation date. @saleiva thoughts?

- If we have the information about shares (which I think Luis has), I don't see why not adding it. Although let's be careful on when so much information it's too much information. 

- I'm worried that with those changes we're delegating the most key sentence to the end "once is deleted, it cannot be recovered" and that might led to more people not reading it and the trouble that could create. 

- About why adding the option to export the map: it's a form of backup. You might wan't to delete your map, but exporting the .CARTO file you'll have a backup in case you wan't to recover it in the future. In my humble opinion, I don't think this is more important than the following sentence and I don't think we should change the order of the message.

---

@arianaescobar commented on [Thu Nov 24 2016](https://github.com/CartoDB/design/issues/333#issuecomment-262804685)

@saleiva how about "recent map views", is there such a thing?

I'll add some icons! :) 

---

@saleiva commented on [Thu Nov 24 2016](https://github.com/CartoDB/design/issues/333#issuecomment-262824194)

Map views in the last XX days?

---

@arianaescobar commented on [Thu Nov 24 2016](https://github.com/CartoDB/design/issues/333#issuecomment-262825861)

Feedback applied:

![delete map warn](https://cloud.githubusercontent.com/assets/16247628/20607368/e0008244-b277-11e6-8b35-cb246f63e843.png)

---

@saleiva commented on [Thu Nov 24 2016](https://github.com/CartoDB/design/issues/333#issuecomment-262846227)

Number of shares will be challenging. I´d remove it and close and promote.

---

@arianaescobar commented on [Fri Nov 25 2016](https://github.com/CartoDB/design/issues/333#issuecomment-262917822)

![105 delete map warn](https://cloud.githubusercontent.com/assets/16247628/20620850/0eb67eb6-b2fc-11e6-97eb-c1938d45afb6.png)

**Comment by xavijam** [comment]
Love it

**Comment by brittanymicek** [comment]
+1 Thank you @arianaescobar !!! <3

One thing (copy edit/fix):
"Before deleting your map, you can export it as a .CARTO file."*

* add "it", "a", and a full stop (.)

xoB

**Comment by arianaescobar** [comment]
Still valid
