### ISSUE TITLE
Centering map option in widgets

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#10839]
After adding the option for centering map in the layer menu, we should add the same feature to widgets.

The center option was added in #10833. Please refer to that PR to get more info about that feature.

Please @urbanphes , could you add here a screenshot of the center icon in widgets? Thanks

cc @xavijam @saleiva

**Comment by urbanphes** [comment]
Hey, at the beginning we thought in something similar to the widgets. You could center the map if any widget was filtering.

![02 center map - filtered widget](https://cloud.githubusercontent.com/assets/14546701/20747163/6349a7aa-b6e9-11e6-9362-2499a7564bf9.png)


IMHO this option has more sense.
