### ISSUE TITLE
Zoom controls hidden when multiple legends & timeseries visible (Builder)

### ISSUE THREAD

**Issue by allthesignals** [CartoDB/cartodb#10834]
### Context
When having multiple legends and a timeseries widget, the zoom and search controls are covered with no option to scroll. 

### Steps to Reproduce
1. Add multiple legends with enough symbols to stretch
2. Add a timeseries widget

### Current Result
<img width="400" alt="screen shot 2016-11-25 at 12 29 26 pm" src="https://cloud.githubusercontent.com/assets/5004319/20632349/dd706ae2-b30a-11e6-826c-6fb25493e87c.png">

### Expected result
Possible option to scroll the legend or change which corner zoom controls can appear.

### Browser and version
Chrome 55

**Comment by xavijam** [comment]
Don't we have scroll in the legend @piensaenpixel?

**Comment by xavijam** [comment]
BTW, moving to CartoDB.js, where the bug is happening.

**Comment by xavijam** [comment]
Issue moved to [CartoDB/cartodb.js #1511](https://github.com/CartoDB/cartodb.js/issues/1511) via [**ZenHub**](https://www.zenhub.com/)
