### ISSUE TITLE
Several issues with Join columns from 2nd layer analysis

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10850]
### Context
Although the analysis work correctly, the UX of this form is not smooth. This issue summarizes a set of improvements to be done on it. This analysis is in the top3 of most used analysis.

### Steps to Reproduce

1. Using an account with many datasets imported (more than 200) apply the Join columns from 2nd Layer analysis.
2. Once it is applied, go to the layer list and go to edit the applied analysis.

### Current Result
- [x] Input 2 selector is loading although the layer was already selected before (this might be the root cause of some other issues described below).
- [x] While loading the UI seems broken (image attached)
- [x] After loading the node names is wrong, and the label for the inputs from the 2nd layer is wrong as well. Seems to be adding the node id instead of the dataset/layer name
 

### Expected result
The UI shouldn't seem broken and it shouldn't reload the 2nd layer.

You can import this .CARTO in order to test this faster.
[Where we work in Madrid (on 2016-11-28 at 13.53.18).carto.zip](https://github.com/CartoDB/cartodb/files/616486/Where.we.work.in.Madrid.on.2016-11-28.at.13.53.18.carto.zip)

cc/ @xavijam

**Comment by xavijam** [comment]
Deployed!
