### ISSUE TITLE
`time` data field not recognized by hover pop-up style wizard

### ISSUE THREAD

**Issue by dannguyen** [CartoDB/cartodb#10853]
### Context

I am trying to customize the __Hover__ Pop-Up for datapoints by including a few fields. I noticed that the pop-up wizard doesn't seem to handle a column named `time`. Here it is as one of 3 data columns selected:

![image](https://cloud.githubusercontent.com/assets/121520/20671748/77c032a6-b533-11e6-9766-3f6076179bd5.png)

Here it is as the lone column selected; Carto acts as if no columns at all were chosen for display (i.e. by showing "No Data Available" in the popup):

![image](https://cloud.githubusercontent.com/assets/121520/20671810/ac6c837e-b533-11e6-8f3f-c75e068f54cb.png)

Bizarrely enough, the __Click__ style wizard works just fine:

![image](https://cloud.githubusercontent.com/assets/121520/20671954/5ec77a88-b534-11e6-9853-0023d66b5a7c.png)

 

### Steps to Reproduce

1. Create a map with a Dataset based on the USGS earthquake data: https://padjo2016student.carto.com/dataset/us_quakes
2. Attempt to style the layer's **hover** pop-ups
3. Select the `time` column for display

### Browser and version

Chrome 54 on Mac OS X
 

### .carto file

[example-broken-time-hover-popup.carto.zip](https://github.com/CartoDB/cartodb/files/616585/example-broken-time-hover-popup.carto.zip)

**Comment by juanignaciosl** [comment]
Happened today to me ☝️

**Comment by matallo** [comment]
And me too, yesterday, I found a workaround casting the field to a string
in the sql panel
