### ISSUE TITLE
CARTO icon displayed when a viewer user opens a map links to carto.com

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#10873]
From #10090 cc @micagm 

### Context
* Organization with viewer user.

 

### Steps to Reproduce

1. Share a (Builder) map with a viewer user.
2. Open the map with the viewer.

### Current Result

Top left CARTO icon is a link to carto.com.

 

### Expected result

Top left CARTO icon is a link to user dashboard.

### Additional info

As viewer opens the embed, the icon link is the normal one.

cc @xavijam @CartoDB/builder-backend

**Comment by javitonino** [comment]
The embed always links to carto.com. I think the problem here is that we don't have a public view for the builder maps yet, so we are working around by using the embed. Maybe it's worth it to do a quick fix (at least for viewers) until we have the public views?

**Comment by juanignaciosl** [comment]
Public view will probably face the same issue if it's used as the view for a viewer user.

We could add an optional parameter to the Javascript that generates the UI for the back link, maybe.

Or a new icon, so we'll keep CARTO for carto.com and other for going back. Maybe this is a call for @CartoDB/design team?

**Comment by saleiva** [comment]
cc/ @carlostallon

**Comment by arianaescobar** [comment]
The ideal scenario will be that if you're logged in as a Viewer (or as a Builder!), and you're looking at the public view of a map, when you click on the CARTO icon on the top left, you'll be taken back to your dashboard. On the other hand, if you're not logged in, that icon would take you to www.carto.com instead. 

Is that realistic from your side?

**Comment by javitonino** [comment]
Keep in mind we only have the embed for now, so the behaviour we use for the public view will also apply to the embeds. That is, with @arianaescobar suggestion, if you click the carto icon in an embed in a random page, it would take you to your dashboard if you are logged in. Not sure if we want that.

**Comment by juanignaciosl** [comment]
@javitonino that's not completely true. We could parametrize the target of the link so it becomes a link to your dashboard if there's a open session. I suggested considering a second icon because from a UI design point of view having the same button linking to different places depending on current user might be not perfect, but I think that @arianaescobar can be made.

**Comment by arianaescobar** [comment]
Hmm... interesting. Yeah, we probably wouldn't want that for the embeds...  

What do you think @carlostallon?

**Comment by juanignaciosl** [comment]
@javitonino sure. We can make the link depend on the referral as well, making it a link to the dashboard if it was opened at the dashboard, or to carto.com otherwise.

**Comment by javitonino** [comment]
I don't think that's trivial to do (thinking about redirections from old embed to new embed) but you are right that could probably work.

**Comment by carlostallon** [comment]
hi guys, i'm working on the designs for the new builder public pages, that will replace the embed view that we are using right now. You can take a look here: 
https://invis.io/3K9IX8GPN#/208750252_Builder_Public_Page_-_Snapshot

So, from my point of view, I would leave the embed link pointing to carto.com and the top-left logo of the new design proposal pointing to the user dashboard.

To make it easy I don't think it's worth changing the link right now because we will implement the builder public pages really soon.

**Comment by saleiva** [comment]
Closing til the public page is done :)
