### ISSUE TITLE
Change of URL on the Add Datasets modal

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#10876]
### Context

I suggest changing the url on the **see all formats** link on the Add Datasets mobile from https://carto.com/docs/carto-editor/datasets/ to https://carto.com/docs/carto-engine/import-api/importing-geospatial-data/#supported-geospatial-data-formats 

It takes a few steps of navigation to get to the actual list of supported formats and some people might not even get there. Let's make it easier for them :) 

### Steps to Reproduce

1. Open Add Dataset modal
2. Click on **see all formats** link

### Current Result

Link goes to https://carto.com/docs/carto-editor/datasets/

### Suggested result

Link goes to https://carto.com/docs/carto-engine/import-api/importing-geospatial-data/#supported-geospatial-data-formats

**Comment by xavijam** [comment]
Hey, it is a super easy task in the Builder, perfect for starting to contribute :).

**Comment by arianaescobar** [comment]
![screen shot 2016-11-29 at 14 39 22](https://cloud.githubusercontent.com/assets/16247628/20711787/b466c95e-b641-11e6-8b22-a40bb53dc5e4.png)
