### ISSUE TITLE
Increase the spec coverage of the icon styling part of the Fill component

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#10875]
Right now that area of the fill component lacks of a proper spec coverage. We should add some tests to ensure nothing gets broken as we continue developing and adding more features.

**Comment by jorgesancha** [comment]
@javierarce When you have a mo, please can you provide some more info for this ticket?

**Comment by javierarce** [comment]
Done! This issue was more of a note to self that I created before we introduced the new workflow.

**Comment by xavijam** [comment]
Done!

**Comment by xavijam** [comment]
Ouch, it should be closed.
