### ISSUE TITLE
Public Table View style is broken

### ISSUE THREAD

**Issue by Vangaufre** [CartoDB/cartodb#10883]
![image](https://cloud.githubusercontent.com/assets/20445530/20719723/0b988a30-b65d-11e6-90e4-67b7dbe182e1.png)

#SMOKE_PD06

**Comment by saleiva** [comment]
Does this happen only in the on-prem version or in the cloud as well?

**Comment by Vangaufre** [comment]
Only in the on-prem version

**Comment by javisantana** [comment]
this ticket does not apply anymore
