### ISSUE TITLE
Edit date in line has some weird behavior

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#10897]
#SMOKE_ MG12

### Context
Editing a line and try to change the date
 
### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*
1. Add a line layer
2. Edit line
3. Try change the date

### Current Result
- I can't add single digit for the day
- When I save the date, it saves one day before

### Expected result
Save the right date

### Browser and version
*What internet browser (Chrome, Firefox, etc) and version was you using and version* 

### .carto file
*Don't forget to rename .carto file to .zip file to be able to upload to github*

 

### Additional info
*Please add any information of interest here below*

**Comment by xavijam** [comment]
This is the same as https://github.com/CartoDB/cartodb/issues/10903

**Comment by matallo** [comment]
the same issue in different parts, reopening
