### ISSUE TITLE
HTML edition in Infowindow on hover doesn't work 

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#10892]
#SMOKE_ MG44
#SMOKE_MG45

### Context
It happens in on premise's smokes if you need how test in my machine ping me.

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Create a points layer
2. Go to the Layer / Pop-up Tab
3. Go to Hover option

### Current Result
I can't create a infowindow on hover

### Expected result
Form should appear and could change to HTML edition

### Browser and version
*What internet browser (Chrome, Firefox, etc) and version was you using and version* 

 

### .carto file
*Don't forget to rename .carto file to .zip file to be able to upload to github*

 

### Additional info
*Please add any information of interest here below*

**Comment by javisantana** [comment]
hey, there were a javascript error in the console, could you paste it?

**Comment by piensaenpixel** [comment]
now it's working :(

**Comment by nobuti** [comment]
It's something like content is required for codemirror, I've seen it before but it's hard to isolate.

**Comment by xavijam** [comment]
Yep, closing until we have some solid steps to reproduce it :(.

**Comment by nobuti** [comment]
Same as https://github.com/CartoDB/cartodb/issues/10988
