### ISSUE TITLE
Each time you click on the date, the date decreases one day

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#10903]
![ghost2](https://cloud.githubusercontent.com/assets/1214201/20756345/a716167a-b712-11e6-859f-7f8de883f75a.gif)

**Comment by xavijam** [comment]
This is another thing, because that date column is not with time zone and it gets rid of it when it is saved. cc @gfiorav @javitonino

**Comment by javitonino** [comment]
Deploying to ded05 for testing

**Comment by ivanmalagon** [comment]
**Acceptance passed**

UI workings flawlessly.

Edited datetimes in different formats via SQL API. It gets transformed to UTC and then treated like that for the next operations. No more weird behaviours when editing the date via UI.

Ship it! :shipit:

**Comment by ivanmalagon** [comment]
Deployed to Production.

**Comment by matallo** [comment]
BOOM
