### ISSUE TITLE
Accessibility issues

### ISSUE THREAD

**Issue by urbanphes** [CartoDB/cartodb#10900]
### Context
I find this support ticket interesting to review

> Hi there,
I am a developer that is working on creating a web app for a customer using Carto. Our customer needs to adhere to certain web accessibility standards in all of their apps and one of the key accessibility issues is ensuring that every image on a page has an alt text on it. When I run a web accessibility tool over the app it gives me errors saying that the img's that make up the map do not have alt text, is there any way to add those in?
Thanks,
Jake.d*

**Comment by ramiroaznar** [comment]
cc @alonsogarciapablo

**Comment by alonsogarciapablo** [comment]
While we could add alt texts to some of the images in the UI, it would be really hard to add alt texts to map images... On the other hand, I don't think accessibility is one of our goals. Closing for now!
