### ISSUE TITLE
"Old" embeds with Google Maps basemaps are not loading

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#10927]
Here's a map that is failing:

http://manhack.carto.com/viz/7eb12856-131d-11e3-a78b-6116c58b5d17/embed_map

And here're the [messages in track.js](https://my.trackjs.com/messages/filtered?hash=77c707b092f01ba8).

We are loading the Google Maps API with:

`<script type="text/javascript" src="//maps.googleapis.com/maps/api/js?sensor=false&v=3.12&"></script>`

But we should be using something like:

` <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap"`

[We basically need to provide an API KEY](https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error) to the Google Maps API script. We load the script [in many different files](https://github.com/CartoDB/cartodb/search?utf8=%E2%9C%93&q=sensor%3Dfalse).

cc: @xavijam

**Comment by alonsogarciapablo** [comment]
There's another warning in the console:

```
util.js:210 Google Maps API warning: RetiredVersion
https://developers.google.com/maps/documentation/javascript/error-messages#retired-version
```

From [the link they provide](https://developers.google.com/maps/documentation/javascript/error-messages#retired-version):

> You may have supplied a retired version in your script element. The versions 3.0 - 3.24 have been retired, and you might be receiving 3.25 instead. Please update your application to use one of the available versions.

We're trying to load "3.12"...

**Comment by xavijam** [comment]
Ouch, shit... 😱  cc @javisantana

**Comment by javisantana** [comment]
know problem, ops is taking care manually

**Comment by alonsogarciapablo** [comment]
What's the status of this? I see it's still not fixed yet (eg: http://manhack.carto.com/viz/7eb12856-131d-11e3-a78b-6116c58b5d17/embed_map).

Is this being tracked in another issue? Thanks!
