### ISSUE TITLE
Option for a 'keep all geometries' for 'intersect second layer' analysis

### ISSUE THREAD

**Issue by carlostallon** [CartoDB/cartodb#10924]
### Context
If someone intersects points and polygons, only the polygons which intersect points show up in the map which leaves holes that you don't always want

This proposal is to keep all polygons, even if they don't intersect the points, and give the aggregation value of zero to those.

design issue related: https://github.com/CartoDB/design/issues/62#issuecomment-263943132

### Mockup
![01 layers - 06-31 analysis - intersection filter - keep geometries](https://cloud.githubusercontent.com/assets/1712650/20759374/0f49ac2a-b71d-11e6-9c22-238b84291f48.png)

**Comment by ramiroaznar** [comment]
This is already implemented.
