### ISSUE TITLE
Consolidate close actions

### ISSUE THREAD

**Issue by urbanphes** [CartoDB/cartodb#10921]
### Context

Related to https://github.com/CartoDB/design/issues/372
(This feature has been worked on CartoDB/design)

**Comment by nobuti** [comment]
Picking this

**Comment by nobuti** [comment]
@urbanphes how about the quota infoboxes?

![3f5888f4-e8a1-11e6-83a0-1f110c7b1ea8](https://cloud.githubusercontent.com/assets/1366843/23157466/ad901a2e-f81b-11e6-83cb-7afa5f7b00b9.png)

**Comment by nobuti** [comment]
also in this infobox:

![screen shot 2017-02-22 at 06 59 07](https://cloud.githubusercontent.com/assets/1366843/23199086/78d37054-f8cc-11e6-8c77-c9f23ea9696b.png)

should we add the close button? does it replace it the confirm?

**Comment by xavijam** [comment]
@CartoDB/design ^^^??

**Comment by urbanphes** [comment]
@nobuti the infobox now have the action to close/cancel on an icon "x" on the right top corner.

The normal inboxes are like this:
![9 infoboxes](https://cloud.githubusercontent.com/assets/14546701/23204766/1f435768-f8e8-11e6-981f-af4849ef8a14.png)

The quota infoboxes are like this:
![11 quota warnings](https://cloud.githubusercontent.com/assets/14546701/23204796/328a91d8-f8e8-11e6-86a6-4e7c5b5a0b3e.png)

**Comment by nobuti** [comment]
@urbanphes so the cartocss one, should we keep two actions plus the close button?

**Comment by piensaenpixel** [comment]
@nobuti continue is replace by close they have the same action

**Comment by xavijam** [comment]
In production!
