### ISSUE TITLE
Give a comprehensive error message for when invalid geometries are used in an analysis

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#10943]
When running an intersection, Builder returns this error: lwgeom_area_spher(oid) returned area < 0.0

.carto can be downloaded here: https://drive.google.com/open?id=0B0nG__Cq6i-7elRjenRZazZoZW8

**Comment by saleiva** [comment]
@rochoa is this still happening?

**Comment by rochoa** [comment]
Yes. In general, it happens whenever you have an invalid geometry, for some "Self-intersection" and "Hole lies outside shell" reasons as ST_Area(geom_column::geography) fails with that error.

**Comment by saleiva** [comment]
But we should then give a more explanatory error and that's it, right?

**Comment by rochoa** [comment]
Yes. Bear in mind that this might happen in any analysis, not this particular error, but the scenario.

**Comment by saleiva** [comment]
yeah, ok cool.

**Comment by alrocar** [comment]
Stale issue. Closing 👋
