### ISSUE TITLE
Visualizations with clusters migrated to Builder are broken

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/cartodb#10953]
### Context

Some maps that use the clusters wizard break when migrated to Builder.

This is different from #10917 (it happens with or without overviews) but could have a similar cause (possibly related to the `sql_wrap` property of layers with clusters).

It occurs when the map configuration has references to columns of the table
 
### Steps to Reproduce

1. With an Editor user create a new map with a points dataset
2. With the default styles (simple wizard), set the hover pop-up to show some column of the data 
3. Change the style with the Cluster wizard
4. Publish the map
5. Migrate the user to the Builder
6. Open the map

### Current Result

The map has a horrible error message:

![image](https://cloud.githubusercontent.com/assets/5909/20840283/02b7e118-b8b0-11e6-95f1-5d64ac68d611.png)

The problem, which occurs with the query the tiler is executing, is that the base query (the very complex clusters query) doesn't include all the table columns, but the wrapper added by Mapnik references them. This could be related with the different approach to generate the Mapnik configuration when analyses are present and the presence of `sql_wrap`.

Note that if step 2 is omitted, the map is rendered correctly in Builder with clusters.

### Expected result

No error on the map and the clusters layer shown.

### Browser and version

Google Chrome Version 54.0.2840.98 (64-bit)

**Comment by jgoizueta** [comment]
cc @rochoa

**Comment by jgoizueta** [comment]
The only difference between map configurations that cause the problem and others that don't seems the presence of columns other than `cartodb_id` in  `interactivity` passed to the Mapnik renderer.

**Comment by jgoizueta** [comment]
I've traced the problem down to this:

If the popup has been configured using some column before applying the clusters wizard, the map configuration that the tiler receives from the Builder has those columns in the  `interactivity` property of the layer. The editor didn't produce any  `interactivity` property in those cases.

Since the clusters visualization (an others) introduce a SQL query in the layer that doesn't select all the columns of the base table this causes an error when sent by the tiler to the db (because Mapnik wraps the query selecting the interaction columns).

**Comment by alonsogarciapablo** [comment]
Closing this for now.
