### ISSUE TITLE
Show 422 errors in UI when post/update fails for legends

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#10961]
Currently, nothing is shown in the UI when a request to the legend endpoints fails in the builder.

cc/ @nobuti

**Comment by xavijam** [comment]
Who could I replicate that behaviour?

**Comment by gfiorav** [comment]
Modify the payload of a request so the definition is missing, for example

**Comment by gfiorav** [comment]
Any luck with this one?
