### ISSUE TITLE
Button to edit sync options present in map layer for shared datasets

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#10967]
**STR:**
 1. Create a sync dataset and share it with the org
 2. From another org user, create a map with that dataset
 3. Go to the layer view, at the top you should see "View options" for the sync
 4. Click that and change the sync period
**Actual:** It fails (forbidden, as expected) because you do not have permission to modify the sync for another user.
**Expected:** The button to view options is not there.

![out](https://cloud.githubusercontent.com/assets/7569673/20888265/674219b4-bafe-11e6-8812-4b782bfe3798.gif)

cc @xavijam

**Comment by xavijam** [comment]
Something I've noticed is, after adding a dataset which is synced, that info doesn't appear in the layer list unless you reload the browser. If it is possible, let's address that problem with this issue please.

**Comment by ivanmalagon** [comment]
Couldn't reproduce issue mentioned by @xavijam . After adding a new synced dataset, the icon shows up.

**Comment by xavijam** [comment]
It is likely a problem with one of my synced datasets 😱 .

**Comment by ivanmalagon** [comment]
Additional issue found: sync header doesn't refresh.

Steps
1. Edit a synced layer. The `view options` button is shown at the header.
2. Apply an analysis.
3. The button should be hidden.
4. In fact, if we exit and then enter again the layer, the button is not there, as expected.

![sync header problem](https://cloud.githubusercontent.com/assets/1078228/20976397/aa1d92cc-bca2-11e6-987e-7c44e214040d.gif)

**Comment by ivanmalagon** [comment]
Passing to CR phase.

Both issues fixed:

1. When using a synced dataset from another user in the organization, we don't show `view options` anymore.
2. When adding an analysis to an owned synced dataset, the `view options` gets hidden. When removing the analysis the button shows again. To sum it up, only showing `view options` when the layer top node is a synced dataset.

Vamos!

**Comment by xavijam** [comment]
💪
