### ISSUE TITLE
Unexpected error when running an UPDATE command on a shared dataset with write permissions

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#10979]
### Context

Going through smoke tests (Smoke tests BUILDER onrpremise (2016/12/05) - OG09 in particular).
 
### Steps to Reproduce

1. Login to an on-premise version of the BUILDER.
2. Open a shared dataset with read-write permissions (you'll need to share a dataset between two accounts if you don't have one).
3. Open the SQL editor.
4. Try to run an UPDATE SQL statement (something simple like `UPDATE carto.barrios SET nombre='CARTO' WHERE cartodb_id=1`).

### Current Result
I'm getting the following error: `permission denied for function _cdb_userquotainbytes`.

<img width="1280" alt="screen shot 2016-12-07 at 13 16 19" src="https://cloud.githubusercontent.com/assets/390398/20967537/4df0f52e-bc80-11e6-9ddf-5cee2c1ade79.png">

### Expected result
Since I have write permissions on the dataset, I should be able to run an `UPDATE`.

### Browser and version
Chrome Version 54.0.2840.98 (64-bit) for Mac.
 

### .carto file

You can test with the following dataset:

[barrios.csv.zip](https://github.com/CartoDB/cartodb/files/636580/barrios.csv.zip)

### Additional info
I couldn't run the `UPDATE` command on the the shared dataset, but a `DELETE` command worked fine.

#SMOKE_OG09

**Comment by luisbosque** [comment]
I've reproduced it

/cc @xavijam

**Comment by javitonino** [comment]
I cannot reproduce it 🤔

**Comment by javitonino** [comment]
Ok, this only happens when the dataset is owned by the admin, and the subuser tries to run the UPDATE, not the other way around.

**Comment by javitonino** [comment]
Replicated in dev environment using the same user creation tasks as onpremise:

```
SUBDOMAIN="oadmin" PASSWORD="12345678" EMAIL="oadmin@example.com" ORG="oorg" bundle exec rake cartodb:db:setup_user                            
bundle exec rake cartodb:db:create_new_organization_with_owner \ 
    ORGANIZATION_NAME=oorg \
    ORGANIZATION_DISPLAY_NAME=Org \
    ORGANIZATION_SEATS=100 \
    ORGANIZATION_QUOTA=$((1000 * 1024 * 1024)) \
    BUILDER_ENABLED=true \
    USERNAME=oadmin
```

**Comment by javitonino** [comment]
Also happens when creating users via superadmin API

**Comment by javitonino** [comment]
Just waiting for 🍏

**Comment by alonsogarciapablo** [comment]
:clap: @javitonino
