### ISSUE TITLE
Table not getting filtered when applying a filter on a widget

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#10976]
### Context

While doing the smoke test WD26 `Filter using a widget and check the table view of the filtered layer.` I filtered a Category widget and then checked the table view and the column of that widget wasn't filtered. 
 
### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. I uploaded this dataset on the on-premise smoke test : [crime_incidents_2016 (1).csv.zip](https://github.com/CartoDB/cartodb/files/636253/crime_incidents_2016.1.csv.zip)
2. Created a map with it
3. Added a Category widget with the `voting_pre` column
4. Filtered the map by "Precint 140" 
5. Checked the Table view

### Current Result

The column `voting_pre` showed the unfiltered data

### Expected result

The column `voting_pre` should have only shown the filtered data

### Browser and version

Chrome Version 54.0.2840.71 (64-bit)

### .carto file

 [Untitled Map (on 2016-12-07 at 10.07.38).carto.zip](https://github.com/CartoDB/cartodb/files/636283/Untitled.Map.on.2016-12-07.at.10.07.38.carto.zip)

### Additional info

Smoke tests BUILDER onpremise (2016/12/05) #WD26

**Comment by xavijam** [comment]
Hey, this smoke test is not correct @luisbosque @arianaescobar (cc @javisantana), because the table view doesn't get info from the filtered results, it gets the data from the SQL API. So it is impossible (right now) to show the same info from the map and table if it is filtered by a widget.

**Comment by javisantana** [comment]
I think this was more a FR that we never implemented

**Comment by xavijam** [comment]
Yeah, I said not correct but I should say it doesn't work in that way right now.
