### ISSUE TITLE
Hover Pop-Up UI is missing

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#10988]
### Context
S/B 10709224

When client tries to enable Hover Pop-Ups he's unable to see the UI panel with Style and Show items sections - I can replicate, looks like he's taken into the Custom/HTML view automatically.

### Steps to Reproduce

1. Import a points dataset with a string-type column that can be used for categories. Create map.
2. Click into layer & choose STYLE tab. 
3. Click on Fill color bar & choose BY VALUE. Specify the dataset's string-type category column. Leave the default category color palette.
4. Click on the POP-UP tab. Click on HOVER.

### Current Result
Looks like we're taken to the Custom code panel automatically:

![screen shot 2016-12-07 at 5 52 04 pm](https://cloud.githubusercontent.com/assets/1779444/20990669/f3690e2a-bca7-11e6-94c9-6313b5e4cb3c.png)

### Expected result
We should see a HOVER panel like this:

![screen shot 2016-12-07 at 6 07 54 pm](https://cloud.githubusercontent.com/assets/1779444/20990697/1e1fa778-bca8-11e6-97d3-b75cb66432dc.png)

### Browser and version
* me: Chrome 55.0.2883.75 on OSX
* client: Widows 10, OS Build 14393.447 | Google Chrome Version 55.0.2883.75 | Microsoft Edge 38.14393.0.0

### .carto file
[largecategories.zip](https://github.com/CartoDB/cartodb/files/638021/largecategories.zip)

* This is really hard to replicate consistently! In first test I started with a polygon layer, then added the points dataset with Categories & was able to replicate when trying the points layer hover Pop_Up...but then I deleted the polygon layer & didn't have the problem any more.

* I was able to replicate when I made a new map that started with a different polygon layer, and the same points dataset as 2nd layer - until I changed the datasets from Private to Public, then I didn't have the problem any more either.

### Additional info
When I have less than 11 categories the hover UI appears as expected:

![screen shot 2016-12-07 at 6 16 08 pm](https://cloud.githubusercontent.com/assets/1779444/20990883/41ac254e-bca9-11e6-895f-d737fdd5fa81.png)

test w/few categories:
[small_test.zip](https://github.com/CartoDB/cartodb/files/637988/small_test.zip)

**Comment by nobuti** [comment]
Thank you @ztephm, I was chasing this bug for a while but I couldn't get a consistent way to reproduce it! 🙏
