### ISSUE TITLE
Autostyle not appearing on On-Premises 2.0

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#10981]
### Context

When passing **Smoke tests BUILDER On-Premise (2016/12/05)**, specifically WD14 `Apply auto-style on the widget and check the results - filter as well. Deactivating auto-style should get the prev. styles back` and WD23 `Apply auto-style on the widget and check the results - filter as well. Deactivating auto-style should get the prev. styles back` I realized that the autostyle option is not appearing on the widgets. 

### Steps to Reproduce

1. Add any dataset
2. Add a histogram or category widget 

### Current Result

There's not autostyle options on the widgets

### Expected result

The autostyle option should appear on the widgets

### Browser and version

Chrome Version 54.0.2840.71 (64-bit)

### Additional info

SMOKE_WD14
SMOKE_WD23

**Comment by xavijam** [comment]
Autostyle is not present for this on-premise release unless we enable it (through its proper feature flag).

**Comment by arianaescobar** [comment]
That was fast :O
