### ISSUE TITLE
Maps lose state when you hit browser back

### ISSUE THREAD

**Issue by andrewbt** [CartoDB/cartodb#10999]
![mapcap_back_bug](https://cloud.githubusercontent.com/assets/2013555/21052368/ab89cb02-bdf2-11e6-9182-33526b450d8c.gif)

re conversation at #10992

(before recording): I had applied a red color ramp and a “railroad” widget to the map; hit back, and they were all gone
1 (at recording start): The map at that point. Default styling, “never published” mapcap
2. I add some styling and a histogram widget
3. I hit back
4. I hit forward
5. styling is gone
6. I hard refresh the page, on a lark (mid recording :angel: ) - and my old styling and widget come back! But the old styling conflicts with the new styling and the legend is there but the dots are blue :thinking_face:

**Comment by javitonino** [comment]
Looks like a browser cache issue.

Reproduced in Chrome (Mac & Linux). Does not happen in Firefox (Linux).

**Comment by saleiva** [comment]
I think this is totally depending on the browser...

**Comment by javitonino** [comment]
Still an issue (aggressive chrome caching), not sure if we can do anything though. Maybe @ivanmalagon wants to take a look.
