### ISSUE TITLE
Provide the possibility to recover a state of a map

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#10992]
It would be great if we had the possibility to get back to a previous version of a map. I feel we had something in the first designs for the Builder, but not 100% sure. In any case it would be a super nice feature for the future and it would be tackle with Snapshots.

cc @CartoDB/builder-backend @CartoDB/design

**Comment by javitonino** [comment]
Somewhat related to this is to add the possibility to export the published copy of a map: #10303

From backend, this should be relatively easy to implement, as we designed mapcaps with this in mind. I think exporting a mapcap can be done with a minor (one line) modification but it is untested, and restoring the mapcap should not be too hard either, we just need to be careful to not change the id's of the various elements.

**Comment by andrewbt** [comment]
Can't users just refresh/leave the page and any edits since the map cap are gone? This happens to me a number of times when I accidentally Chrome "multi-touch back swipe", and you go back to Builder and all your edits are gone because you didn't "mapcap" them. It's annoying sometimes but in this case it's more a "feature" than a "bug", no? Or is this ticket something different?

**Comment by javitonino** [comment]
@andrewbt Uhm, that shouldn't be happening. All changes are automatically and immediately saved (you can see the requests in the network console). Publishing saves a static copy for the embed, but the builder works on the latest changes.

What you are describing sounds like a bug. Can you report it? Do you have more details? The more likely causes are some of the requests failing silently, or a browser cache issue.

**Comment by andrewbt** [comment]
@nygeog wasn't this exactly what I unfortunately accidentally did to your gas stations map yesterday evening? We hit the back button and you lost all your analyses and such? I'll see if I can get some more detail @javitonino . Definitely happens to me fairly regularly.

**Comment by javitonino** [comment]
As mentioned, this could be implemented with mapcaps, but AFAIK, we are not doing anything with it. If the need arises, we can revisit.
