### ISSUE TITLE
Analysis onboarding doesn't cover the whole map when viewport is small

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#10998]
![screen shot 2016-12-09 at 15 13 48](https://cloud.githubusercontent.com/assets/132146/21051832/4b55910a-be22-11e6-89e4-86fced9b5aa9.png)

cc @piensaenpixel

**Comment by juanignaciosl** [comment]
I'm not sure if it's the same case, but now it covers the map but the left panel is on top:

![captura de pantalla 2017-03-03 a las 13 24 57](https://cloud.githubusercontent.com/assets/932968/23551132/21b642a6-0015-11e7-8811-1e1cdb9889a2.png)

**Comment by xavijam** [comment]
Ha! I forgot this, yeah, now it is working properly 💃 . Thanks to @ivanmalagon 's work.
