### ISSUE TITLE
feature request: view locked maps as a viewer, with option to edit it as builder

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/cartodb#10990]
To currently look at a locked map within an account, it has to be unlocked even if you don't want to edit it. A different workflow that could save time/confusion is: 

1. click on a locked map
1. either:
    1. be taken to the map as a viewer role, and have a prominent button for being able to edit it (i.e., become a builder for the map)
    1. be presented with a screen for either entering the map as a viewer or a builder
3. if a user re-publishes the map, have a button for locking the map, which then locks the map and exits to the user dashboard

cc @saleiva

**Comment by saleiva** [comment]
Rethinking the blocking functionality. Closing until then!
