### ISSUE TITLE
Implement icons preview list in organization profile

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#11006]
Images for context:

![screen shot 2016-12-12 at 12 31 42](https://cloud.githubusercontent.com/assets/132146/21097984/733eb394-c067-11e6-8e12-35d4092ae13b.png)

![screen shot 2016-12-12 at 12 32 01](https://cloud.githubusercontent.com/assets/132146/21097983/733ccb2e-c067-11e6-85ed-96c6cb96e312.png)

We should show the list of icons that the organization offers to its users. We should manage several things:

- List should show last (20?) uploaded icons.
- If there isn't any icon we should show something, like a hint (state empty).
- Possibility to select and remove one or several icons at the same time: this behaviour should be *implemented independently*, because it will be used in the assets modal (check design ticket).
- When an icon is removed, we should fetch more icons to complete the list.

Things related to design: https://github.com/CartoDB/design/issues/352

**Comment by ivanmalagon** [comment]
Talked with @piensaenpixel and he can help with CSS part in this issue. Ping him when this issue gets started.

**Comment by MariaCheca** [comment]
Hey mates, I would like to do this ticket. Ping me if at some point it gets really urgent and it can't wait more :)

**Comment by ivanmalagon** [comment]
@MariaCheca I'll take it if you don't mind. Icon styling needs some pushing, I think.

**Comment by ivanmalagon** [comment]
One remark / question.

According to the UI, it seems that the user can make any changes and they're not saved until she clicks on `Save changes`.

In the case of icons, if we upload icons and delete them through the list, those changes will be effective even if `Save changes` button is not clicked.

That is, icons are set independently of clicking on `Save`or not. Is this the desired behaviour?

**Comment by nobuti** [comment]
@urbanphes could you please throw some light?

**Comment by ivanmalagon** [comment]
Another implication.

This UI allows to delete a marker file that could be referenced in a number of maps. Since the CartoCSS style saved with the map refers directly to the file, the system won't be able to render it.

I've made a test about this and the user will see this error and won't see any marker in the map.

![image](https://cloud.githubusercontent.com/assets/1078228/21894115/4cbd1b7c-d8de-11e6-8ec8-742b35996d86.png)

Just for you to know. Allowing to delete markers outside the own map that it's using it can break visualizations.

@saleiva @xavijam @jorgesancha

**Comment by saleiva** [comment]
Yep, we know that.... If I don't remember wrong, this was technically very hard to prevent. I would open an enhancement issue for that

**Comment by jorgesancha** [comment]
@saleiva aren't we shooting ourselves on the foot with that? If we allow it, we are literally introducing a bug along with this feature: it will be impossible for the user to know what is causing those visualizations to break (or whether she has broken any when removing the icon).

Ideally we could check before deleting if that icon is being used somewhere else (and maybe even prevent the deletion); if that's not possible, we should at least warn the user: "Are you sure you want to delete this marker? Any other map using it would stop working" (kind of thing)

And if we allow deleting icons that might be present on other maps, is it possible to know why the rendering failed and show another message?

**Comment by saleiva** [comment]
It is the actual behaviour, so it will not be a bug. Again, I would love to warn the user before deleting it, but @javisantana did a clear statement in the good old days about how hard it was so we had to choose.

**Comment by ivanmalagon** [comment]
I think Sergio is right. Knowing is someone is using a particular icon would be difficult.

Anyway, a warning modal just informing the user that she could break visualizations is simple. I'd go for that.

**Comment by javisantana** [comment]
it's not "that hard" to check it, just check urls in cartocss for that organization. I don't think it worths.

we could also add a placeholder instead of breaking the map at maps api level but I'd consider that a low priority enhancement

**Comment by jorgesancha** [comment]
Just talking to @javisantana, @matallo, @javitonino and @ivanmalagon now, here is another option:

- When deleting the file, we don't actually remove it from the DB or S3. We do a soft delete in the DB and leave it in S3. That way maps that might be using it won't break and we won't lose track of the icons completely.

If this is not hard, I'd very much like to avoid introducing a situation where maps will fail and the user won't know why or how to fix them.

If we go ahead, we might need a different issue for the backend part of this and also to test that one can re-add the same icon again after deleted.

**Comment by saleiva** [comment]
Sounds good to me although it can lead to some confusion since the icon
will be still shown. Anyway it's better than nothing.

**Comment by xavijam** [comment]
Already reviewed once. I'll let other mate to review the second time 💋 .

**Comment by nobuti** [comment]
Taking a look

**Comment by ivanmalagon** [comment]
Code review comments fixed. Waiting for @nobuti to give the green light. 🚦

**Comment by juanignaciosl** [comment]
There are several PRs linked to this issue, I think that only #11292 must be accepted, isn't it?

**Comment by xavijam** [comment]
Yep!
