### ISSUE TITLE
Migrate all CSS code related with organizations to the new Builder system

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#11008]
In order to start using the same Builder asset modal in Bulider and in Organization pages (https://github.com/CartoDB/cartodb/issues/11009), we should migrate all the current code to the Builder one, it could imply:

- Start using only Builder CSS code.
- Remove unnecessary classes added in the templates.

It is true we should not have a bad time doing this ticket after the work done for the release by @MariaCheca and @piensaenpixel (:kiss:).

**Comment by saleiva** [comment]
This would be a great moment to dedicate a few hours to fix some visual bugs in those pages cc/ @piensaenpixel

**Comment by piensaenpixel** [comment]
it could be great.

**Comment by ivanmalagon** [comment]
Blocked for the same reasons as #11007 

If issue #11007 this must be blocked as well.

**Comment by noguerol** [comment]
ping for either pushing or closing this.
