### ISSUE TITLE
[Google Maps Support] Add Google Maps basemaps to the basemap selector

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#11000]
TBD.

**Comment by saleiva** [comment]
What do you need from @CartoDB/design here? Just the assets, right?

**Comment by alonsogarciapablo** [comment]
I'm not sure yet. For other providers, like Leaflet, we use tiles as icons. Not sure if we can do that for Google Maps too.

**Comment by josecruz** [comment]
We made this approach for BCG:
![01 layers - 04-01 legend copy](https://cloud.githubusercontent.com/assets/596509/21272630/121e949c-c38e-11e6-928e-c29bec1458bc.png)

**Comment by josecruz** [comment]
We made this but using the maps tiles:
![-01 layers - 05-03 basemap google](https://cloud.githubusercontent.com/assets/596509/21272751/90b64994-c38e-11e6-990a-c56410d29141.png)

**Comment by saleiva** [comment]
If not, we will get an screenshot and use it.

**Comment by josecruz** [comment]
I don't know if it helps but on their map styling tool they use basemaps tiles as thumbnails:
![image](https://cloud.githubusercontent.com/assets/596509/21272875/f85c764a-c38e-11e6-8683-559ab36258c8.png)

**Comment by alonsogarciapablo** [comment]
Thanks guys!

**Comment by noguerol** [comment]
@alonsogarciapablo is this already tackled?

**Comment by alonsogarciapablo** [comment]
Ouh yeah!
