### ISSUE TITLE
Labels not rendered in Pixel aggregated legends

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#11015]
### Context
Custom labels are not rendered in Pixel aggregated legends.

![screen shot 2016-12-12 at 15 27 42](https://cloud.githubusercontent.com/assets/1078228/21102737/ae9fafb6-c07f-11e6-87ab-68bf506fc0d5.png)

 

### Steps to Reproduce

1. Aggregate a layer by Pixel.
2. Edit the legend.
3. Check LEFT LABEL and write something. The label is not written in the legend.
4. Check RIGHT LABEL and write something. The label is not written in the legend.
 

### Additional info
#SMOKE_MG31

cc @luisbosque @xavijam

**Comment by luisbosque** [comment]
Confirmed

**Comment by javierarce** [comment]
It looks like we need to make a couple of changes both in this repo and in cartodb.js, because the legend template and view there is not actually rendering the left and right labels: https://github.com/CartoDB/cartodb.js/blob/v4/src/geo/ui/legends/custom-choropleth/legend-template.tpl

**Comment by xavijam** [comment]
Ahhh that's a good one, let's do it then @javierarce.

**Comment by javierarce** [comment]
PR: https://github.com/CartoDB/cartodb/pull/11030

**Comment by javitonino** [comment]
After merging dependencies, like a charm ✨

**Comment by xavijam** [comment]
Doing that with @ivanmalagon.
