### ISSUE TITLE
Datepicker not shown in NASA basemaps

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#11017]
### Context

If choosing a NASA basemap based on date, clicking on the date picker doesn't show it properly.

![nasa bug](https://cloud.githubusercontent.com/assets/1078228/21103780/1f70205a-c084-11e6-87ae-a611fc32224f.gif)

### Steps to Reproduce

1. Click on basemap layer.
2. In `source` select `NASA`.
3. Click on the date picker.
4. The calendar doesn't show up

### Additional info
#SMOKE_MG40

cc @luisbosque  @xavijam

**Comment by luisbosque** [comment]
Confirmed

**Comment by xavijam** [comment]
this ticket should be merged into on-premises release branch when it is done 💋 .

**Comment by xavijam** [comment]
Aceptao!
