### ISSUE TITLE
HTML rendered in legends

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#11014]
### Context
While editing a label in an admin aggregated layer, some HTML is rendered under certain circumstances.

![screen shot 2016-12-12 at 15 17 05](https://cloud.githubusercontent.com/assets/1078228/21102342/178107de-c07e-11e6-9b00-474801a76f47.png)

 

### Steps to Reproduce

1. Aggregate a layer in admin. regions.
2. Go to LEGEND tab.
3. Check TITLE and LEFT LABEL.
4. Write something only in LEFT LABEL.
5. Some HTML is shown in the legend.

### Additional info
#SMOKE_MG30

CC @luisbosque @xavijam

**Comment by luisbosque** [comment]
Reproduced

**Comment by MariaCheca** [comment]
As this issue occurs in Cartodb.js, I duplicated it in its right repo: https://github.com/CartoDB/cartodb.js/issues/1533

**Comment by xavijam** [comment]
Great! Don't close this one please 💋

**Comment by MariaCheca** [comment]
@ivanmalagon @nobuti CRd it here: https://github.com/CartoDB/cartodb.js/pull/1535

**Comment by ivanmalagon** [comment]
Updating `shrinkwrap`for getting the last changes in `cartodb.js` Related PR: https://github.com/CartoDB/cartodb/pull/11033

**Comment by xavijam** [comment]
Deploying with new package, closing!
