### ISSUE TITLE
Adding custom country not allowed when geocoding by postal code if there is not string column

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#11012]
### Steps to Reproduce

1. Create a map with a dataset with just a numeric column containing postal codes
2. Add "Georeference" analysis to the layer
3. Select "Postal Codes" as `TYPE`
4. Try to type a custom country

### Current Result

* Typing a custom country is currently not allowed. 
* The dropdown menu is inactive because there is not a string column.

### Expected result

* It would be great you could type without the need to have a string column.

### Browser and version

* Google Chrome v54

**Comment by saleiva** [comment]
We should then add the component we have in the address geocoding that lets you type custom values

**Comment by michellechandra** [comment]
S/B: 11241218

**Comment by noguerol** [comment]
Same as https://github.com/CartoDB/cartodb/issues/12334 so closing
