### ISSUE TITLE
Enable icon styling with categories

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#11019]
Extend the icon styling feature to support adding an icon to each category.

> Creating a category icon map would be possible by choosing the BY VALUE option when clicking on the color input. If selecting an string column, the UI will offer different buttons to assign an icon to every category (remember we give 10 results as max).

> This functionality will let the user to select an icon and a color - if the icon format is svg - for every category plus a style for the OTHERS category in case it exist. 

See the discussion for the workflow and design for this feature in [this ticket](https://github.com/CartoDB/design/issues/303). Final design is [here](https://github.com/CartoDB/design/issues/303#issuecomment-262497147)

Contact @urbanphes or @javierarce if you have doubts with the workflow or design of this feature.

The current icon styling feature is hidden with a feature flag. Once this ticket is completed, talk to @javierarce or @xavijam to enable this feature to everybody.

**Comment by jorgesancha** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Style With Icons](https://trello.com/c/ehXyg2nE/1-style-with-icons)

**Comment by javierarce** [comment]
Moving this back to development so we can fix the problems found in the CR [here](https://github.com/CartoDB/cartodb/issues/11187)

**Comment by MariaCheca** [comment]
I'll take care of it asap.

**Comment by jorgesancha** [comment]
very thorough CR @javierarce 👏  👏

**Comment by nobuti** [comment]
Back to acceptance.

**Comment by MariaCheca** [comment]
Deployed in ded04, ready to test!

**Comment by jorgesancha** [comment]
Vamos!

**Comment by juanignaciosl** [comment]
For the record, I'm testing in ded06 because I triggered the deployment before and we agreed upon deployment being done by the one who accepts ;-)
