### ISSUE TITLE
Map not refreshed after editing line or multipolygon feature.

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#11010]
### Context
After editing manually the geometry of a line, the map is not refreshed. We still see the same line as before.

Same thing happened to me when editing a multipolygon.

![smoke line bug](https://cloud.githubusercontent.com/assets/1078228/21101085/c72bc1d0-c077-11e6-9e41-090f310da3fb.gif)

### Steps to Reproduce
Please watch the GIF above for a clip of the bug.

1. Edit a custom line.
2. Move the line points to get a different line.
3. Change the name field.
4. Save the line.
5. The drawn line is the previous one. You can check it editing the line again: the geometry is the modified one.
6. After refreshing the line is properly drawn.

### Additional info

#SMOKE_MG12
#SMOKE_MG14

CC @luisbosque @xavijam

**Comment by luisbosque** [comment]
When you edit the line, the geometry appears updated. However if you edit the line and before saving you edit the form too (for example the Name field) the geometry doesn't get updated. You need to reload in order to see the updated geometry

**Comment by xavijam** [comment]
PR: https://github.com/CartoDB/cartodb/pull/11029

**Comment by xavijam** [comment]
Merge it for on-premises release branch please 💋 .

**Comment by javitonino** [comment]
On premise PR: https://github.com/CartoDB/cartodb/pull/11035

Waiting for tests to pass, and doing acceptance on the on-premise branch, as the merge was a bit difficult and I may have broken it.

**Comment by javitonino** [comment]
Merged to onpremise branch!

**Comment by xavijam** [comment]
💋
