### ISSUE TITLE
Implement has:profile_geo for GNIP 2.0

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/cartodb#11024]
has:profile_geo operator [has been added](http://support.gnip.com/changelog/#user-content-nov-10-16) to GNIP 30 days search in the 2.0 version. We need to add it in order to have more geocoded tweets results as we have in the v1.0 version.

This is an easy to add feature because mimic the v1 business logic that we currently still have behind a feature flag.

**Comment by ethervoid** [comment]
At the end of this ticket the `gnip_v2` should be removed

**Comment by ethervoid** [comment]
## Acceptance tests

- [ ]   Check that import works using the twitter connector with the following parameters and we have multiple results (4):
  - Category 1: carto
  - Dates: 21/02/2017 11:45:00 - 21/02/2017 12:00
- [ ]   Check that import works using the twitter connector with the following parameters and we have multiple results (15) for both terms:
  - Category 1: carto
  - Category 2: gis
  - Dates: 21/02/2017 11:45:00 - 21/02/2017 12:00
- [ ] Check the name of the table has the terms in it
- [ ] Import the same datasets using production and check the difference between the two imports. The new should have more results than the current one

**Comment by jgoizueta** [comment]
:+1: works like a charm!

**Comment by ethervoid** [comment]
\o/ many many thanks man :)

**Comment by ethervoid** [comment]
Deployed and working
