### ISSUE TITLE
Add file upload support for the icon styling feature

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#11020]
Extend the icon styling feature with a user file upload.

We need to port the old functionality of the Editor so users can upload their icons and use them in their maps.

- In the old code there's an API endpoint to retrieve the uploaded icons.
- Talk to @urbanphes to ask for the designs of the remove icon, icon loader and disable states.

![screen shot 2016-12-12 at 16 40 23](https://cloud.githubusercontent.com/assets/4933/21105186/976561d8-c089-11e6-90e5-7536a8ad8d35.png)

See workflow and design in [this issue](https://github.com/CartoDB/design/issues/303). 
Final design is [here](https://github.com/CartoDB/design/issues/303#issuecomment-262497147)

PR: https://github.com/CartoDB/cartodb/pull/11450

**Comment by gfiorav** [comment]
Just a note for the future. The backend endpoint created for the feature already supports this. PR: https://github.com/CartoDB/cartodb/issues/11034

You must specify resource: param as an url or an upload stream.

**Comment by ivanmalagon** [comment]
About the feature of allowing an organization to upload it’s own icon set through its organization dashboard, do we have any design / mockup?

So far, the only designs I’ve seen are related to Builder, to allow the user to upload her own icons but no one for the organization side.

cc @saleiva

**Comment by ivanmalagon** [comment]
Ok. Icon uploading for organizations is in this issue https://github.com/CartoDB/cartodb/issues/11006

**Comment by xavijam** [comment]
Moving to TODO column because it is necessary in order to release style-with-icons feature.

**Comment by xavijam** [comment]
Which is the PR?

**Comment by matallo** [comment]
I just updated the PR description with reference link

**Comment by javitonino** [comment]
Waiting for deploy to finish...
