### ISSUE TITLE
Edit UI text when using the Edit Geometry Feature with a synced dataset

### ISSUE THREAD

**Issue by csobier** [CartoDB/cartodb#11025]
### Context
Was trying to use the "Edit Geometry Feature" with a synced dataset.

### Current Result
The following UI text appears.

![image](https://cloud.githubusercontent.com/assets/13319925/21108847/97856552-c064-11e6-9345-762db2e70560.png)

 

### Expected result
I think what you are trying to say is?

"You cannot edit a geometry that is synced to real-time data. To edit the map layer, change the Sync dataset options to Never"

@saleiva , is this related to a work-in-progress feature?  Otherwise, can you edit the UI text as suggested, to clarify what is actually happening?  (I would have committed a PR myself, but it looks like the text in line#2046 of https://github.com/CartoDB/cartodb/edit/master/lib/assets/locale/en.json is linked to a layer status?)

Tagging @namessanti for awareness.

**Comment by saleiva** [comment]
@matallo shouldn't this work as expected?

**Comment by matallo** [comment]
it works as expected, currently there's only three possibilities, from https://github.com/CartoDB/cartodb/blob/master/lib/assets/locale/en.json#L2057-L2059

- analysis
- custom-sql
- sync

**Comment by namessanti** [comment]
Just to note, soon the terminology Wiki will be up in Learn. Let's make sure we have parody between the product and how we communicate it. Also please have a native english speaker, preferably Christa, review text going into the product. "Feature edition" is one of a few mistakes put into the product that are not proper english and makes us look like rookies : (
