### ISSUE TITLE
Ability to easily set widget states via embed url

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#11023]
cc @nobuti 

### Context
Enterprise client wants to set widget filter states via embed url parameters.

Right now we have access to widget states via the url that loads when you put one of our Publish/'Get the link' urls in a browser tab, but it's not easy for clients to identify the widgets & state settings. Also they want to do it via embed url.

Can we add easily-identifiable widget parameters to our 'Get the link' and 'embed' urls, so clients can change widget settings without having to go back into UI?

### Steps to Reproduce
1. Add a histogram widget, a category widget, and a time-series widget to a map.
2. Publish the map & copy it's 'Embed it' url.
```
<iframe width="100%" height="520" frameborder="0" src="https://team.carto.com/u/stephaniemongon/builder/0f1c0c39-9abe-48a1-bec7-a1f06b0d365c/embed" allowfullscreen webkitallowfullscreen mozallowfullscreen oallowfullscreen msallowfullscreen></iframe>
```
3. Paste into html page you want to embed the map in.

### Current Result
Widgets are filtered properly according to current settings we choose within the Builder interface.

However there's no way for client to change the widget settings from the embed url - they would have to go back into their account and change the widget filters via interface.

### Expected result
Can we add recognizable widget settings as url parameters to our Publish links?
 
### .carto file
[cartofile.zip](https://github.com/CartoDB/cartodb/files/646584/cartofile.zip)

### Additional info
We can set widget filters via UI and they appear properly when we 'Get the link' url loads in browser tab:

https://team.carto.com/u/stephaniemongon/builder/0f1c0c39-9abe-48a1-bec7-a1f06b0d365c/embed?state=%7B%22map%22%3A%7B%22ne%22%3A%5B0.5273363048115169%2C-173.671875%5D%2C%22sw%22%3A%5B67.47492238478702%2C-15.292968749999998%5D%7D%2C%22widgets%22%3A%7B%22c4d80dc3-e267-411a-8973-bc5eca8abc90%22%3A%7B%22normalized%22%3Atrue%2C%22min%22%3A5429999.999999997%7D%2C%22a12e2617-42fa-4f87-b147-933638fcc536%22%3A%7B%22acceptedCategories%22%3A%5B%22BNSF%22%5D%2C%22autoStyle%22%3Atrue%7D%7D%7D

But it's not easy for client to identify for example which above is total_dama histogram widget:

![screen shot 2016-12-12 at 11 49 20 am](https://cloud.githubusercontent.com/assets/1779444/21107844/127a5f14-c061-11e6-9cab-fe6553caae79.png)

**Comment by danmayer** [comment]
actually when I first made this request, it wasn't possible at all via params....

```
For example this map, has state passed in like zoom and center. I assume there is a way to pass in filter last_name=X, but I can't seem to guess it or find it in the documentation.

https://offgridelectric.carto.com/u/oge-dev-owners/builder/a9ac6b7e-96f0-11e6-a6ca-0e233c30368f/embed?id=497&state=%7B%22map%22%3A%7B%22center%22%3A%5B-3.373769667016016%2C36.70429229736328%5D%2C%22zoom%22%3A13%7D%7D

Could you point me to documentation or let me know how to embed with a filter selection. Or would we have to embed with JS, which no longer seems to be an option from our share menu?
```

I attempted to change in url and even inspected the JS at the time and nothing would set state (Oct 20th). 

I was just pinging on the original request. we don't need a nicer interface long as the params are exposed we can build a valid URL to set the filters as we need. I just checked and this works on our map embeds now, while previously it did not. 

So I don't think we need anything other than I didn't know this feature had been addressed since I requested it. Thanks this will open up a lot of interesting usage for us.

**Comment by danmayer** [comment]
obviously a nicer interface could be good but for now it looks like `state=#{URI.encode(json_data)}`

some example JSON would be like so

`state = {"map":{"ne":[-6.468151012664202,32.16796875],"sw":[-2.943040910055132,37.1337890625]},"widgets":{"e6a76bd5-1ed6-41dd-9a8f-7dc60e7718a4":{"acceptedCategories":["2730","8147"]}}}`

` state = %7B%22map%22%3A%7B%22ne%22%3A%5B-6.468151012664202%2C32.16796875%5D%2C%22sw%22%3A%5B-2.943040910055132%2C37.1337890625%5D%7D%2C%22widgets%22%3A%7B%22e6a76bd5-1ed6-41dd-9a8f-7dc60e7718a4%22%3A%7B%22acceptedCategories%22%3A%5B%222730%22%2C%228147%22%5D%7D%7D%7D`

Adding these comments as documentation for anyone else running into it.

**Comment by nobuti** [comment]
Thanks @danmayer, those are great ideas for a future api that we certainly will take them in mind when we tackle it.
