### ISSUE TITLE
Reordering layers hide legends

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#11037]
![legend reorder](https://cloud.githubusercontent.com/assets/1078228/21148761/8ac7ec9a-c159-11e6-8434-e3643cdb1332.gif)

### Steps to Reproduce
1. Edit a map with several layers.
2. Go to the top layer.
3. Create a legend. In the GIF above I created one for color and another one for size.
4. Check that the legend is visible.
5. Go back to the layer list.
6. Go to the bottom one.
7. Create a legend for that layer.
8. Check that now we have a legend for three different values.
9. Go back to the layer list.
10. Reorder the layers. Grab the top one and move it one position down, for instance (like in the GIF above).
11. The two legends of the top layer disappear!!
12. If you edit that layer, you can notice that the legends are still there, but they're not visible anymore.

**Comment by nobuti** [comment]
Picking this

**Comment by nobuti** [comment]
Ready for code review.

**Comment by ivanmalagon** [comment]
Acceptance passed. Local 👍  Ded02 👍
