### ISSUE TITLE
Carto embedded does not show on IE11 [Waiting for user]

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#11038]
@coquiaspiazu commented on [Tue Dec 13 2016](https://github.com/CartoDB/cartodb.js/issues/1536)

I get the screen error below on IE 11.

What I find surprising is that it was working until yesterday. And I can still see the embed on Edge, Chrome, etc. Is this a bug? or was something upgraded between yesterday and today?

![error screen](https://cloud.githubusercontent.com/assets/8021492/21155983/2d34cbc8-c142-11e6-963b-4934bfe8989d.png)

**Comment by xavijam** [comment]
Hum, weird, that's true, it should work...

**Comment by xavijam** [comment]
I'd like to check this one with one Backend 💋  please.

**Comment by javitonino** [comment]
Uhm, we are detecting old IE with `msie [0-9]\.` (so MSIE + one digit + a dot). The most likely cause is using compatibility view mode in IE 11, which has the following user agent: `Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.3; Trident/7.0; .NET4.0E; .NET4.0C)`

@coquiasplazu Can you check that you have compatibility view mode disabled? Maybe this helps: https://support.microsoft.com/en-us/help/17472/windows-internet-explorer-11-fix-site-display-problems-compatibility-view

**Comment by javitonino** [comment]
Closing as we have no answer from the reporter.

@coquiaspiazu, feel free to reopen if this is still an issue after you check the previous comment. Thanks!
