### ISSUE TITLE
Render private embed view when visualization does not exists (instead of redirecting to 404)

### ISSUE THREAD

**Issue by MariaCheca** [CartoDB/cartodb#11049]
### Issue

We've found that when a map is removed by the user the embed present in an external site shows our generic 404 page. This is an issue because of two things:

- First an embed 404 page should have another design more adapted as it is present in an external source.
- Second, GA record doesn't specify what kind of object isn't available.

### Solution

- Render a different view when the error comes from the embeds controller.
- Set the GA code for embeds in that view, so metrics will follow the correct path.

cc/ @beloneys @arianaescobar @xavijam @juanignaciosl

**Comment by xavijam** [comment]
In my opinion, we should show the same "template" we use for private embeds but with a different message, what do you think?

**Comment by javitonino** [comment]
After a quick talk about this, we cannot render two different contens for carto.com/404 (since it's a static url). Our proposal is to use the same template as the "embed is private" error, but changing the text. The URL would be the same as the embed (i.e: no redirection will happen).

So we can change the content of the error page at will, but the URL will remain the same. I don't know how this affects metrics tracking. Can you work with it? We could add a different tracking JS to the embed error than the actual embed if it's helpful (don't know exactly how that works).

cc @beloneys

**Comment by beloneys** [comment]
ok so ga script will remain (UA-20934186-10) as it is in embeds. For the text, it's a pity to miss the opportunity to get attention to CARTO, isn't possible to add a specific design with a CTA?

In case it's not possible, you can add the following text and publish it, in case it's possible, let me know and I'll bring another text. Thanks!

It looks like this is a private or nonexistent map. Create your own at carto.com

Belén

**Comment by javitonino** [comment]
We are splitting this task:
 - This ticket will remain as rendering the embed error when the visualization does not exists
 - The design ticket will remain to improve the private/non-existant embed page, maybe adding a CTA to sign up for CARTO :)

**Comment by javitonino** [comment]
Acceptance for this: check the possible embed return errors, for both builder and editor:
 - Visualization not found
 - Visualization is not published
 - Visualization is private (and you are not the owner)
 - Visualization is password protected

Check that the ga code is correct as specified here: https://github.com/CartoDB/cartodb/issues/11049#issuecomment-267059844

**Comment by javierarce** [comment]
I've created and shared a map in staging, but I can't see any ga scripts rendered in the HTML. Is it an error or is it a staging feature? :)

**Comment by javitonino** [comment]
Oh, embeds tracking is disabled in staging :(. I did check for GA (which is there in general) but not for the embed specific code. Oh well, I guess we'll have to test in production then, no biggie.

**Comment by javitonino** [comment]
Deployed to production and the GA code is correct ✅

**Comment by javierarce** [comment]
Yay!
