### ISSUE TITLE
Going from CartoCSS editor to SQL editor when moving between tabs

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#11042]
### Steps to Reproduce

* This issue come from here: https://github.com/CartoDB/design/issues/406

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Click on layer
2. Go to STYLE tab
3. Activate CartoCSS console
4. Go to DATA tab

### Current Result

* It goes to `VALUES` mode.

![third](https://cloud.githubusercontent.com/assets/5215798/21176306/69e57ac8-c1e6-11e6-916f-5e3a0af1a571.png)

### Expected result

* It should go to `SQL` mode.

![first](https://cloud.githubusercontent.com/assets/5215798/21176333/83d5f78c-c1e6-11e6-9e70-c93b0accd172.png)

### Browser and version

* Google Chrome v54.

cc @CartoDB/support

**Comment by xavijam** [comment]
Why do we want that behaviour? I don't get it sorry :S.

**Comment by ramiroaznar** [comment]
It makes sense being in "pro" mode when navigating among tabs. First, you are working with SQL. Then you go to STYLE, so the CartoCSS panel is displayed (everything OK). Then you come back to DATA but instead of going back to the SQL panel, the VALUE mode is displayed (not OK).

**Comment by xavijam** [comment]
Uhm... not sure about it, 🤔 .

**Comment by saleiva** [comment]
Yes, I do agree with @ramiroaznar

**Comment by xavijam** [comment]
So this opens a new thing in the Builder, basic or advanced mode, 👍 .

**Comment by ramiroaznar** [comment]
Still an issue. cc @arianaescobar

**Comment by arianaescobar** [comment]
Yup, 100% agree

**Comment by alrocar** [comment]
Stale issue. Closing 👋
