### ISSUE TITLE
'Average' dot staying on size legend when using custom labeling

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#11040]
Hello,

I modified a size legend to have custom titles instead of the numeric values. You'll notice that the dark gray point for where the average value usually is, didn't go away:

![screen shot 2016-12-01 at 9 35 26 am](https://cloud.githubusercontent.com/assets/1566273/20802526/8c8aacf2-b7a9-11e6-9abd-1e470cbe0c37.png)

**Comment by xavijam** [comment]
Yeah, @ivanmalagon spotted doing smoke tests, did you open a ticket for that friend?

**Comment by ivanmalagon** [comment]
Yep.

Opened in `cartodb.js` repo -> https://github.com/CartoDB/cartodb.js/issues/1530

**Comment by xavijam** [comment]
Greeeeeat, thanks, closing this one then 💋
