### ISSUE TITLE
Latitude is incorrect when adding a point

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#11050]
### Context
re: https://github.com/CartoDB/cartodb/issues/10881

### Steps to Reproduce

1. create a map
2. add a point out of latitude bounds
3. point is added inside bounds
4. drag point outside bounds

### Current Result

there is no validation of latitude in lnglat feature form

### Expected result

there should be validation of latitude in lnglat feature form "Latitude is out of bounds"

### Additional info

![screen shot 2016-12-14 at 13 35 10](https://cloud.githubusercontent.com/assets/36676/21182247/5669d3ce-c202-11e6-94b0-79a43694bf4c.png)

**Comment by xavijam** [comment]
Duplicated https://github.com/CartoDB/cartodb/issues/10881 ❤️

**Comment by javierarce** [comment]
PR: https://github.com/CartoDB/cartodb/pull/11060

**Comment by xavijam** [comment]
Hey #10881 is already merged :).

**Comment by javierarce** [comment]
Thanks!
