### ISSUE TITLE
"Info about analysis" page inside Analysis modal

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#11057]
### Context

Heyhey! We're changing the info about analysis modal because of breadcrumbs problems inside that view (weird behavior when you enter the info about analysis modal) so we decided to create a simplified version of the analysis card:

![412 add analysis](https://cloud.githubusercontent.com/assets/596509/21189800/d65ecb1c-c1ed-11e6-9226-ee4c69c215a1.png)

![- 414 info about analysis](https://cloud.githubusercontent.com/assets/596509/21189799/d65bcc32-c1ed-11e6-8edb-0b7a47dd02a4.png)

### Changes:

- We're enriching the page with more information about analysis (will work on it on the implementation process)
- You can add that analysis directly from the "Info about analysis" view (see footer button on the 2nd screenshot)

Original design issue: https://github.com/CartoDB/design/issues/334

**Comment by arianaescobar** [comment]
Closing this issue since we're removing that +info part of this modal.
