### ISSUE TITLE
Errors when styling BY VALUE with a "date" column

### ISSUE THREAD

**Issue by csobier** [CartoDB/cartodb#11059]
### Context
Selecting a "date" column when styling BY VALUE.
 

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Open the .carto file in Builder and select the STYLE tab
2. Keep the default AGGREGATION=NONE
3. Click the FILL color to open the color properties. The SOLID tab appears by default.
4. Click BY VALUE and select a date column "updated or time"
     **Tip:** I enter "date" in the _Search by column_ input field to search for date column types.

### Current Result
The following error appears: `california_earthquakes: Failed to process "marker-fill" property: invalid number of arguments`

![image](https://cloud.githubusercontent.com/assets/13319925/21190426/b41cca16-c1ef-11e6-95e7-2bf074bf8468.png)

### Expected result
I assume that the error should say something like, "You must select the ANIMATED aggregation method before selecting a date column". Or, you wouldn't be able to view/select any date columns at all.

### Browser and version
Google Chrome, Version 54.0.2840.98 (64-bit)

### .carto file
[california_earthquakes map (on 2016-12-14 at 16.12.03).carto.zip](https://github.com/CartoDB/cartodb/files/652238/california_earthquakes.map.on.2016-12-14.at.16.12.03.carto.zip)
 

### Additional info
If I go back and change the AGGREGATION= ANIMATED, and select a date column, the follow error also appears:  `california_earthquakes: TorqueRenderer: column "2016-10-24T00:28:56Z" does not exist`

![image](https://cloud.githubusercontent.com/assets/13319925/21190613/66779a1a-c1f0-11e6-9be5-a3f3a01eebdc.png)

After trying this a few times, I also get a page unresponsive, Kill or Wait, dialog.  @xavijam , is this the expected behavior? Maybe I am not using my data correctly. Can these errors and/or workflows be improved based on this use case?

**Comment by saleiva** [comment]
I do think we should remove the date type columns from the dropdown for the time being

**Comment by ramiroaznar** [comment]
Fixed here https://github.com/CartoDB/cartodb/issues/7873
