### ISSUE TITLE
Fixes for geometry edition when latitude/longitude is out of bounds

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#11052]
From https://github.com/CartoDB/cartodb/pull/11048#issuecomment-267012424

When adding/editing geometry we check that the longitude is in the [-180,180] range. However, we do not fix it automatically, so if you scroll the map a bit to the east (so it wraps around) before adding geometries, you will get errors.

 - [ ] I propose automatically wrapping geometries when adding them graphically, while keeping the validation for manually edited geometries (writing the geojson). I think that is a nice addition to user-friendliness, but of course, not critical.

 - [ ] Also confusing when editing an existing feature if you have moved the map a lot, as the edition point will appear just in the center [-180,180] interval. So if you have moved your map and click edit feature, the edition pointer will not appear.

 - [ ] Also, in the [original issue](https://github.com/CartoDB/cartodb/issues/10881#issuecomment-267034837), we didn't add validation for lines/polygons, only for points. Validation for other geom types should also be added.

cc @xavijam

**Comment by juanignaciosl** [comment]
![screen shot 2017-01-17 at 10 13 20](https://cloud.githubusercontent.com/assets/932968/22014386/b61d7464-dc9d-11e6-85ce-024b0e4559bf.png)

Yes, Builder should know that Earth is not flat :-)

**Comment by matallo** [comment]
I'm starting to add validation for rest of geometries here https://github.com/CartoDB/cartodb/pull/12397 however I'm not quite convinced about wrapping the geometries

take for example adding a polygon, you'd add the first point in the offset map (i.e. `[0,0]` in the real map) so when adding the next vertexes the leaflet drawing tool would link to the real`[0,0]` from the offset map, crossing the 180th Meridian, which would be weird at the moment of drawing (if I'm not wrong you can't have a geometry in the leaflet map and another one in the featureModel)

please give your opinion

**Comment by nobuti** [comment]
Deployed.
