### ISSUE TITLE
Map not refreshed after creating new polygon

### ISSUE THREAD

**Issue by luisbosque** [CartoDB/cartodb#11062]
### Context
After drawing a new geometry, for example a polygon, and cliking Add button, the geometry is not updated in the map. It is stored though. After reloading the page the geometry appear.

![polygon-update-bug](https://cloud.githubusercontent.com/assets/93268/21201000/979c8462-c249-11e6-874c-b34e932caf7b.gif)
 

### Steps to Reproduce

1. Create a new polygon
2. Click Add

### Current Result
The polygon is not updated in the map. The page needs reload
 

### Expected result
The polygon should get refreshed in the map without needing to reload

### Comments

Maybe is it related somehow to the fix of https://github.com/CartoDB/cartodb/issues/11010?

/cc @jorgesancha @xavijam

**Comment by nobuti** [comment]
Picking this

**Comment by jorgesancha** [comment]
@nobuti 🚀

**Comment by nobuti** [comment]
In production!
