### ISSUE TITLE
Join analysis does not work in IE11 (W10)

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#11066]
### Context

* This came from an SB ticket: https://cartodb.supportbee.com/tickets/10786552
* Basically "Join" analysis does not work in IE11 with W10, but it works with Edge.

### Steps to Reproduce

1. Add an analysis to a layer
2. Select "Join columns from 2nd layer"
3. Click on "ADD ANALYSIS"

### Current Result

* After trying a couple of times. The pattern is as follows: the first click do nothing, and the second sends you to a blank page (see screenshot).

![join](https://cloud.githubusercontent.com/assets/5215798/21227935/34d36c5e-c2dc-11e6-8ca5-39c460599b4f.png)

### Expected result

* Join analysis should open.

### Browser and version

* IE11 in W10.
 
cc @CartoDB/support

**Comment by xavijam** [comment]
Hey, is it still happening? We tried in the surface and it is working properly.

**Comment by xavijam** [comment]
Again, tested in IE11 under surface, it seems to work pretty 👌 , closing it. If we find that there is still an issue with it, let's face it in another ticket.
