### ISSUE TITLE
SAML logout

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#11072]
See https://github.com/onelogin/ruby-saml#single-log-out

**Comment by javitonino** [comment]
Some quick notes I discovered after installing a SAML server this morning:
 - Both parties (SAML and CARTO) can initiate logout.
 - To initiate from simplesaml, go to `localhost:5000/saml2/idp/SingleLogoutService.php?ReturnTo=` (also an easier way to reset the simplesaml session). To support this kind of logout, we would need session invalidation.
 - To initiate from CARTO, I guess there is a gem method.
