### ISSUE TITLE
SAML login

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#11076]
### Context

We're integrating SAML authentication for organizations.

*We need some _product decisions_ about login interaction*.

Happy path: when a user goes to `/login`, and there is a SAML header that matches an existing user he will be redirected to his dashboard.

Other scenarios that should be taken into account (for organizations with SAML authentication enabled):

- What happens if the request doesn't contain the user identity?
  - ~It will display the login page with the other authentication mechanisms that the organization has enabled (or an error if no other is enabled).~
  - He won't be able to login. Login page for SAML organizations redirect to SAML identity server.

Additional notes:
- SAML support will first be with server-wide configuration, for onpremise, but in the future, it will probably be configurable within organization options, see #11074.

**Comment by javisantana** [comment]
> SAML support will first be with server-wide configuration, for onpremise, but in the future, it will probably be configurable within organization options, see #11074.

I'd be really careful with this, I think we should try to do per org from the beginning

**Comment by juanignaciosl** [comment]
I'm thinking about this: first, an organization has SAML if there's SAML configuration in `app_config.yml`. This is almost done (see #11047 PR). Next (#11074), an organization will have SAML if there's SAML configuration in `app_config.yml` _or_ there's SAML configuration in the `organizations` table for that organization.

How does it sound? That way I can merge the file approach first, and then add the DB one. Anyway, I can discard the file approach and add it in the DB from the very beginning.

PS: I've updated #11073 as well. You might want to take a look at it. It's currently scheduled for phase III ("future").

**Comment by javisantana** [comment]
that incremental approach sounds good but I'd try to have only one in the final version

**Comment by juanignaciosl** [comment]
Ok, I'll first release the configuration-based approach, which is almost ready, and in #11074 we'll delete it.

**Comment by juanignaciosl** [comment]
This will be closed when #11047 is deployed.
