### ISSUE TITLE
SAML automatic user creation

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#11073]
If the request contains the identity but it doesn't match any organization user, the user will be automatically created.

Please note that the same organization signup rules still apply. The normal SAML scenario would be that no domain is whitelisted so signup page will be disabled.

**Comment by gfiorav** [comment]
I've divided this task in 2:

- [ ] Refactor SAML service so it doesn't return a user but an email, and fetch user outside (https://github.com/CartoDB/cartodb/pull/11129)
- [ ] Create user outside if user with returned email doesn't exist. (Pending development)

**Comment by juanignaciosl** [comment]
Developed both in the same PR.
