### ISSUE TITLE
Change order of widget custom ramp and widget custom color fields and remove checkbox from the custom ramp one.

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#11086]
After using it for a while, I think it would be better to have the custom ramp before the custom colors of the bars.

Also, I don't think we should use the _checkboxy_ type of component for the ramps, since it would be quite explanatory to see the ramp even before customizing it.

**Comment by xavijam** [comment]
About last phrase, ok about that, but we will not provide the possibility to reset to the default auto-style ramp.

**Comment by saleiva** [comment]
That's fine.

**Comment by xavijam** [comment]
I've found a problem here, there isn't a default ramp for the widget, it depends on the data we are seeing in that moment. So that info is not "located" anywhere, it could change each time the user moves the map.

**Comment by saleiva** [comment]
So what are we doing finally?

**Comment by xavijam** [comment]
I'm waiting your thoughts from my comment...

**Comment by saleiva** [comment]
Then, lets leave as it is right now for the time being. Closing!
