### ISSUE TITLE
[Depends on #10420] Custom ramp value is not correctly reflected on the style panel

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#11085]
### Context
Somehow the ramp that gets into the style panel when applying auto-style in the histogram widget is not in-sync with the values applied.

### Current Result
When clicking on auto-syle a ramp is applied but within the style panel another ramp is shown in the dropdown.
<img width="1680" alt="screen shot 2016-12-16 at 10 08 22" src="https://cloud.githubusercontent.com/assets/132149/21267324/cf58a014-c377-11e6-8c94-ff9a8cd72e6a.png">
 
### Expected result
Style input should reflect the same ramp that is being applied.

### .carto file
*Don't forget to rename .carto file to .zip file to be able to upload to github*
[bicimad_locations map (on 2016-12-16 at 15.09.19).carto.zip](https://github.com/CartoDB/cartodb/files/657529/bicimad_locations.map.on.2016-12-16.at.15.09.19.carto.zip)

**Comment by nobuti** [comment]
Fixed by https://github.com/CartoDB/cartodb/pull/10420/commits/a55490317cdcaa9f7bd55ebe853eb2b81610d23e and https://github.com/CartoDB/deep-insights.js/pull/502/commits/237d8b149d8d7c754d1ffa5c02dc2a5417260f08. Heading to ded08 for acceptance.
