### ISSUE TITLE
[Depends on #10420] Styling from widget removes variable size when having a point layer styled by size and color

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#11084]
### Steps to Reproduce

1. Create a map with a points layer
2. Style that layer by color and size using columns
3. Add two widgets, one based on a numeric column and another one based on a string column
4. style using one of the widgets

### Current Result
Variable size is not applied anymore.

### Expected result
Variable size should be kept.

**Comment by saleiva** [comment]
It just worked as expected, not being able ton consistently replicate

**Comment by nobuti** [comment]
Spotted, and fixed in https://github.com/CartoDB/deep-insights.js/pull/502

**Comment by nobuti** [comment]
In ded08, with the rest of autostyle changes.
