### ISSUE TITLE
Analysis/Widgets saving doesn't properly invalidate vizjson

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#11082]
### Context
From https://github.com/CartoDB/cartodb-management/issues/4755, the vizjson cache was not correctly updated.

### Steps to Reproduce
1. Create a map
2. Mapcap it
3. Edit the analysis (or do something with widgets)

### Current Result
The vizjson cache is not invalidated. 

### Expected result
The vizjson cache should be invalidated.

### Additional info
Fix: `::Map[visualization.map.id].invalidate_vizjson_varnish_cache`

The issue is that analysis `after_save` calls `notify_map_change`, which does nothing if the map is mapcapped. Compare with layer's after_save, which calls `force_notify_change`.

IMHO: We should deprecate `notify_map_change`. I don't think it makes sense anymore. The reason is that now, `force_notify_map_change` correctly handles the case with mapcap anyway (it invalidates the vizjson and updates the named map using the mapcap).

Also, a quick comment. The vizjson invalidation works with mapcaps, but is fragile. The reason is that:
 - The builder uses `generate_anonymous_map_vizjson3` to generate vizjsons for the live version of the map.
 - The embed uses `generate_named_map_vizjson3` to generate vizjsons for the mapcapped version of the map.

cc @CartoDB/builder-backend

**Comment by javitonino** [comment]
Same happens with widgets https://github.com/CartoDB/cartodb/issues/11091

**Comment by juanignaciosl** [comment]
Fixed with #11092
