### ISSUE TITLE
Category widgets search filter doesn't show the right value until it's applied

### ISSUE THREAD

**Issue by MariaCheca** [CartoDB/cartodb#11080]
### Context

Using category widgets in Builder, filtering a particular value shows a `1` value by default, but when the user clicks on "Apply" it shows the right value.

<img width="858" alt="screen shot 2016-12-16 at 12 26 29" src="https://cloud.githubusercontent.com/assets/2141690/21261532/5cd7f052-c38c-11e6-9f6f-a53a3cd4f353.png">

![untitled](https://cloud.githubusercontent.com/assets/2141690/21261459/d62f1922-c38b-11e6-8cac-4f8e33559a0b.gif)

### Steps to reproduce
(Same steps appear in the gif above)
1. Open a map in Builder and create a category widget
2. In second step "Data" aggregate by any column and choose a SUM operation with a numeric column value
3. Go to the widget and click on "Search in x categories"
4. Search for a category, and the value from the SUM operation should be 1
5. Now click on "Apply", and the correct SUM operation will appear

cc @CartoDB/frontend

**Comment by ramiroaznar** [comment]
Fixed.
