### ISSUE TITLE
Regresion Error importing this file

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#11083]
### Context
There is an unknown error when trying to import this file https://data.cityofchicago.org/Health-Human-Services/Food-Inspections/4ijn-s7e5 as CSV. It was working not so long ago.

 cc/ @ethervoid @rafatower

**Comment by rafatower** [comment]
Have you tried importing the link in Export -> Download As -> CSV?

https://data.cityofchicago.org/api/views/4ijn-s7e5/rows.csv?accessType=DOWNLOAD

I did and worked like a charm:

https://team.carto.com/u/rtorre/tables/food_inspections/public?redirected=true

**Comment by saleiva** [comment]
That was not working. If it's working now, closing!
