### ISSUE TITLE
Autostyle does not hide/update legends in embed

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#11098]
### Context
Testing autostyle. In the embed, legends are not disabled when applying autostyle. And in the case of bubbles, the color is not updated.
Split from #10420
 
### Steps to Reproduce
1. Create a map
2. Style by value, so a legend is created
3. Add a widget to the same column
4. Publish the map
5. Go to the embed
6. Click autostyle in the widget

### Current Result
The legend is shown 

### Expected result
The legend disappears

### Additional info
https://github.com/CartoDB/cartodb/pull/10420#issuecomment-267952816
https://github.com/CartoDB/cartodb/pull/10420#issuecomment-267519787

**Comment by saleiva** [comment]
I know this is tricky but AFAIK, we agreed to attack this issue. Remember auto-style is specially useful on the embeds, way more than within BUILDER

**Comment by nobuti** [comment]
![autostyle-embed](https://cloud.githubusercontent.com/assets/1366843/21426728/dba2ea22-c850-11e6-974f-7c9d19f0d586.gif)

**Comment by xavijam** [comment]
Reviewed, we are super close, just some minor changes 💋 .

**Comment by xavijam** [comment]
Being deployed in ded03 for acceptance.

**Comment by matallo** [comment]
acceptance passing again, like a charm (with new `layersData`)

**Comment by xavijam** [comment]
👍

**Comment by matallo** [comment]
fixed latest changes spotted with `initialStyle`
