### ISSUE TITLE
Widgets don't invalidate VizJSON cache

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#11091]
### Context

When a Widget is created/updated/destroyed, the VizJSON is not invalidated. This results in widgets added (or removed) to disappear (or reappear) after refresh.

### Steps to Reproduce

1. Create a widget on a map
2. Publish map
3. Refresh

### Current Result

The widget disappears.

### Expected result

The widget is preserved.

cc/ @CartoDB/builder-backend 

@juanignaciosl Please review this on Monday to decide if it should go in the board.

**Comment by javitonino** [comment]
Same as https://github.com/CartoDB/cartodb/issues/11082 but for widgets

**Comment by javitonino** [comment]
P.S: would be nice to write tests + smokes about this

**Comment by saleiva** [comment]
This is critical

**Comment by saleiva** [comment]
Changing the style working correctly as well

**Comment by juanignaciosl** [comment]
Fixed with #11092.
