### ISSUE TITLE
Change color of the histogram bars following the ramp. 

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#11095]
Because the category widget is becoming the legend, when you are in auto-style mode you want the hitogram widget to become the legend as well. We should color the bars with the color ramp used on the styling.

AFAIKl this was started by @fdansv some time ago.

**Comment by saleiva** [comment]
After the first tests and thoughts I am starting to think that this should be considered a must if the legends dissapear.

**Comment by saleiva** [comment]
![01 copy](https://cloud.githubusercontent.com/assets/132149/21399497/3a3391e0-c7ac-11e6-8478-00741ea66e77.png)

**Comment by xavijam** [comment]
Merged in deep-insights, now in the process to have it in CartoDB and production finally.
