### ISSUE TITLE
Improve Timeseries widget behaviour with overviews

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/cartodb#11101]
In #10783 the use of overviews was disabled for timeseries widgets because overviews have no information for date columns (they're NULL). For large tables this may lead to execution of time consuming queries to generate the histogram data (the result size will be small though: number of buckets).

If we aggregate date columns in the overviews we may be able to use this information for more efficient time series histograms.

Other point to look at is that  cartodb.js (histogram-data-model.js) will cause an an error if it receives a empty set of bins for a histogram.

**Comment by javisantana** [comment]
I think it's too advanced taking into account the our current state, won't fix and let's see in the future
