### ISSUE TITLE
Notifications when new limits appear

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#11104]
Create this issue only for being able to create the PR

This issue is related this https://github.com/CartoDB/design/issues/425

![image](https://cloud.githubusercontent.com/assets/1214201/21346748/05b9cf9e-c6a6-11e6-8ea5-ccf61972bb67.png)

Let's start with.

"Your analysis has taken too long (your account limit is Xs). Try to sample your data or contact us for further assistance"

cc @saleiva @rochoa @javisantana

**Comment by rochoa** [comment]
cc @xavijam We need to know if it's going to be possible to load the limit within Builder.
