### ISSUE TITLE
Signup "Industry questions" layout broken in Safari

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#11109]
### Steps to Reproduce

You need to do this in Safari.

1. Visit carto.com/signup
2. Fill in the required info to create a new user
3. Submit

### Current Result

Some industry questions are asked but the layout is broken.

![screen shot 2016-12-20 at 15 15 58](https://cloud.githubusercontent.com/assets/4222826/21353926/65734448-c6c8-11e6-90fc-bda34b3a7896.png)

### Expected result

Layout is ok (like in Chrome).

![screen shot 2016-12-20 at 15 18 34](https://cloud.githubusercontent.com/assets/4222826/21353940/73505902-c6c8-11e6-85b0-c7db3848a4f1.png)

### Browser and version

Safari Version 10.0.1 (12602.2.14.0.7)

cc/ @juanignaciosl

**Comment by xavijam** [comment]
Have you checked @ivanmalagon if that is still happening after our last changes for signup form?

**Comment by xavijam** [comment]
Issue moved to [CartoDB/cartodb-central #1776](https://github.com/CartoDB/cartodb-central/issues/1776) via [**ZenHub**](https://www.zenhub.com/)
