### ISSUE TITLE
Deleting a column using ALTER TABLE sql doesn't get that column to dissapear from the UI

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#11114]
### Steps to Reproduce

1. Go to a map, enter to a layer click on the table view.
2. Delete multiple columns using a SQL statement such as `ALTER TABLE table DROP COLUMN col1, DROP COLUMN col2;`

### Current Result
Columns seems deleted but still appear on the UI

### Expected result
Columns shouldn't appear on the UI

**Comment by rochoa** [comment]
Schema changes don't invalidate cached results. I cannot find the issue associated with this problem, but this is a known issue.

The current workaround is to `select cartodb.cdb_tablemetadatatouch('user_name.table_name');` after you have changed the schema.

**Comment by nygeog** [comment]
I saw something like this yesterday when doing an `ADD COLUMN`.
