### ISSUE TITLE
Query applied indicator doesn't appear when entering to a dataset page and having a query applied

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#11111]
### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Apply any valid/error'ed query to a dataset within the dataset view
2. Go back to dashboard
3. Enter the dataset view again

### Current Result
Although a query is applied, the indicator doesn't show up so the data in the table can be missleading if the user doesn't remember that she applied a query.

### Expected result
Query applied indicator should be shown.

**Comment by xavijam** [comment]
This is not happening anymore 💃
