### ISSUE TITLE
Missing data from Central reporting API request

### ISSUE THREAD

**Issue by jmartinter** [CartoDB/cartodb#11119]
### Context
After last changes in Central reporting API, 'organization' field in response is missing.

### Steps to Reproduce
1. curl "https://user:pwd@carto.com/api/users/saleiva/metrics?

### Current Result
The returned json doesn't include an "organization" field as expected

cc'ed @javitonino

**Comment by javitonino** [comment]
`organization` should contain the organization name, right?

**Comment by jmartinter** [comment]
Yes

### Bonus
Taking advantage we have to modify this code, it would be really useful to add a new 'Builder' field to the API response that returns a boolean (True if user is builder, False if user is viewer)
