### ISSUE TITLE
Deleting a feature doesn't invalidate the cache

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#11124]
### Steps to Reproduce

1. Open a visualization with lines.
2. Delete a line. It's deleted, great!
3. Load the page again.

### Current Result

The feature appears again.

### Expected result

It shouldn't be there.

### Additional info

- A hard reload (Cmd + shift + r) reloads the visualization without the feature, so it's a caching issue.

cc @CartoDB/builder-backend @matallo @rochoa @xavijam

**Comment by jorgesancha** [comment]
Hey @rochoa 

Could this issue be related to https://github.com/CartoDB/cartodb/issues/11094? @saleiva suspects it might be the same thing. If so, let us know and we'll close this one

**Comment by rochoa** [comment]
It's related as we use the same approach for this case, but it's a different instance of the same problem.

**Comment by jorgesancha** [comment]
Gotcha - so nothing for Builder team to do (other than maybe reviewing when the problem is addressed) right?

**Comment by rochoa** [comment]
This is now prioritized along #11094, so nothing from Builder. I would include someone from the team to do the acceptance. Hope that works.

BTW, it would be interesting to understand what triggered this behavior.

**Comment by rochoa** [comment]
As per same changes described at https://github.com/CartoDB/cartodb/issues/11094#issuecomment-270171101, this issue is now solved.

**Comment by jorgesancha** [comment]
You are a rock star 🤘

**Comment by saleiva** [comment]
Uh ah!
