### ISSUE TITLE
StrongPasswordValidator escapes characters unnecessarily 

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#11127]
The development is done in: https://github.com/CartoDB/cartodb/pull/11128

This issue can go straight to CR.

### Context

Since some characters are escaped unnecessarily, they're companion `\` is also taken as a valid character. Also, the space character wasn't properly escaped and not counted as a symbol

NOTE: This was fixed as part of another PR, but was extracted to it's own.

### Steps to Reproduce

1. Try to signup for an org with Strong passwords activated
2. Choose a password containing `\` and complying with all other requirements.

### Current Result

The password is accepted.

### Expected result

The password shouldn't be accepted.

### Acceptance:

Create an org with strong passwords and test a few different ones to make sure that requirements are met (length, number of numbers or symbols, etc).

**Comment by javitonino** [comment]
We are finally not merging this. The reported issue was only a problem when suggesting password (which is not merged), but password verification works fine.
