### ISSUE TITLE
Changing the metadata of a feature doesn't apply style change

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#11125]
### Steps to Reproduce

1. Open a polygon map and set style per category with a value of the feature.
2. Map gets styled.
3. Edit the data of the feature which style is based on.

### Current Result

- Feature style doesn't change.

### Expected result
- Feature style should change.

### Additional info

- A normal reload of the page displays the right feature color.

cc @matallo @xavijam

**Comment by saleiva** [comment]
is this still happening?

**Comment by juanignaciosl** [comment]
Yes
