### ISSUE TITLE
SAML login only within the organization

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#11120]
[SAML service should only get a user within the organization](https://github.com/CartoDB/cartodb/blob/master/lib/carto/saml_service.rb#L39) .

**Comment by jorgesancha** [comment]
Can you explain this a bit better @juanignaciosl ? Also, which of the SAML milestones does this one belong to?

**Comment by juanignaciosl** [comment]
This was a bug that @gfiorav spotted, and I wrote it down so it wouldn't be forgotten. In fact he fixed it as part of #11129 (I just linked it as he forgot to). As it was a bug I didn't add it to any milestone, maybe I should've done it. It will be closed when the PR is.

**Comment by jorgesancha** [comment]
So it is done, does this need to be in the ToDo column at all?

**Comment by juanignaciosl** [comment]
It should be moved to CR, indeed, because that's where the issues related to that PR are. Honestly, I'm not sure about what to do in this situations.

**Comment by jorgesancha** [comment]
Issue #11073 is already in Code Review and the PR (https://github.com/CartoDB/cartodb/pull/11129) already addresses this issue, so having two issues I think would just confuse things.

Adding a comment in the PR so that whoever Code Reviews bears this in mind and removing this one from the TODO column

**Comment by juanignaciosl** [comment]
Cool, thanks. As GitHub closes automatically issues if you say "this closes ..." or "this fixes...", I had already updated the description with "This closes #11073 and #11120.".

**Comment by jorgesancha** [comment]
Yes, I saw 👍
