### ISSUE TITLE
Auto starting services on server bootup

### ISSUE THREAD

**Issue by ClintonKimsing** [CartoDB/cartodb#11131]
Hi,

I'm rather new to Carto and ubuntu and trying to figure out, after having gotten the Carto local instance to run, how can I set things up so that the commands:

- bundle exec script/resque
- bundle exec thin start --threaded -p 3000 --threadpool-size 5
- node app.js production

startup after the server boots up?

I have tried creating 'Upstart' scripts:

description "resque"
author "Clinton Kimsing <Clinton.Kimsing@mapdataservices.com.au>"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]
respawn

chdir /home/ubuntu/cartodb
exec bundle exec script/resque

But this starts and stops and nothing loads when accessing the carto web page.

You assistance or direction would be greatly appreciated

**Comment by juanignaciosl** [comment]
Hi, @ClintonKimsing . As this question is related to system configuration and not cartodb code, could you please write to cartodb@googlegroups.com, including services logs? Thanks!
