### ISSUE TITLE
Remove second back button from fill by category

### ISSUE THREAD

**Issue by MariaCheca** [CartoDB/cartodb#11138]
## Current status

We have two back actions in the fill by category view to edit the color: the first one to the list of categories, the second one to the list of columns.

<img width="316" alt="screen shot 2016-12-27 at 16 19 43" src="https://cloud.githubusercontent.com/assets/2141690/21502470/4e9ec1c4-cc50-11e6-8b47-4593e9da5b51.png">

## Steps to reproduce

1. In Builder enter a layer with point geometries and go to the style tab.
2. Style with no aggregation and in the 'Style' step, introduce a fill by value.
3. Select a string type column to filter by categories, and once the list of categories appear select one of them.
4. You should see something similar to the image above. 

## Expected result

There should be only one back action to the list of categories.

Updated by @javierarce: as mentioned by @saleiva, we should hide the complete title row.

cc @CartoDB/frontend

**Comment by javierarce** [comment]
Back to CR!
