### ISSUE TITLE
Add intermediate step to select category ramp for string column

### ISSUE THREAD

**Issue by MariaCheca** [CartoDB/cartodb#11139]
We need to add the step to select the ramp for string columns. Right now what happens is that a custom ramp is selected and, after choosing the column to filter by, it leads directly to the categories list.

Right design is here: https://projects.invisionapp.com/share/EA9FCD8ZV#/screens/212560201

cc @xavijam

**Comment by noguerol** [comment]
@CartoDB/design can you provide an updated mockup for this?

**Comment by piensaenpixel** [comment]
sure, adding to our kanban.

**Comment by urbanphes** [comment]
I can't find this project inside our InVision account (the project could have been erased)

But this ticket is about:
When the user selects a "column string" instead of appears the ramp color by default should appear the ramps color selector with this kind of ramps that we have con CARTO-Colors:

<img width="990" alt="captura de pantalla 2017-10-16 a las 9 34 31" src="https://user-images.githubusercontent.com/14546701/31600047-41a6f518-b255-11e7-93c8-4112744e11ca.png">




The same way that if the user select a "column number"; we offer a different ramps color to select.

Is it about that?

**Comment by noguerol** [comment]
Yup

**Comment by urbanphes** [comment]
We've made the same solution that we use when the user selects a "column number". In this case, we offer the ramps for this kind of columns.

Here is the Invision Project:
**https://invis.io/D4E5FQB2E**

cc/ @noguerol

**Comment by urbanphes** [comment]
@CartoDB/design any doubts or any comment about that?

**Comment by piensaenpixel** [comment]
+1 I think it's perfect :)

**Comment by piensaenpixel** [comment]
cc @noguerol

**Comment by arianaescobar** [comment]
Could we change the default ramp (the first one on the list) to a _prettier_ one? 🙃

Maybe @makella could help us pick the best one to put at the top. (I remember her saying that she wanted to change the order of the ramps because the default one for number columns wasn't the best one)

**Comment by piensaenpixel** [comment]
Sure, waiting for @makella then

**Comment by makella** [comment]
so amazing!! can't wait for this thank you thank you.

i think our default now of "Prism" is a good option. I have a feeling what will happen is that they will be read in as they are organized in cartocolor.js... so "Antique" which you have there in your mock-up is the first in the alphabetical list of `qualitative` schemes.... UGH.

If we can (fingers really crossed) let's keep it at `Prism` for default (that's how it is now).

thanks for checking!
mamata

**Comment by makella** [comment]
I would say let's default to `Bold` but that is what we default with category > auto-style so don't want to repeat.

**Comment by urbanphes** [comment]
On the visual design, I’ve used the ramp “Prism” as a default ramp and the list could be:
1. Prism
2. Antique
3. Bold
4. Pastel
5. Safe
6. Vivid

On this page, are all ramps with their names.
https://github.com/CartoDB/CartoColor/wiki/CARTOColor-Scheme-Names

<img width="711" alt="captura de pantalla 2017-10-30 a las 17 05 57" src="https://user-images.githubusercontent.com/14546701/32181439-a7242452-bd94-11e7-95ad-35be467777f8.png">


Here is the Invision Project:
**https://invis.io/D4E5FQB2E**

**Comment by piensaenpixel** [comment]
I see it perfect! :)
close and moving to promote
