### ISSUE TITLE
add scrollbar for add WMS basemap menu

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartodb#11132]
### Context
When adding a WMS basemap within CARTO, once that you add the WMS URL and clicked on "GET LAYERS" options,  if the URL contains several layers, they are not completely displayed on the screen. You need to zoom out the browser view in order to see all of the layers. 

A scrollbar would be need to move across all the WMS layer options of the CARTO menu.

### Steps to Reproduce

Taking this URL as example: `https://services.slip.wa.gov.au/public/services/Landgate_Public_Services/Admin_Public_Services/MapServer/WMSServer`

Initial zoom level of the browser Chrome (Version 55.0.2883.95 (64-bit)) is 90%.

1. Add basemap using WMS option
2. Click on the "GET LAYERS" option in order to see all avaiable layers to add on the map.
3. CARTO shows the message "9 layers found, 9 layers available", but there are only 6 layers displayed on the list. If you try to scroll down, the list does not continue.

![screen shot 2016-12-27 at 11 45 01](https://cloud.githubusercontent.com/assets/11177693/21498114/f13ef7fe-cc29-11e6-9d9d-1d4897eb4eeb.png)

4. If you zoom out the browser view until 50%, you can see all the 9 layers

![screen shot 2016-12-27 at 11 46 39](https://cloud.githubusercontent.com/assets/11177693/21498136/311b1790-cc2a-11e6-8c59-e257fe076f78.png)

**Comment by MariaCheca** [comment]
Closed in https://github.com/CartoDB/cartodb/pull/11291

**Comment by xavijam** [comment]
Hey, we should not close the ticket until it is deployed.

**Comment by xavijam** [comment]
It is not deployed yet, so please (again), let's not move it to DONE column.

**Comment by javitonino** [comment]
Now truly deployed, after some issues were fixed :)

**Comment by xavijam** [comment]
Much appreciated!
