### ISSUE TITLE
Sync table 1103 error

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb#11148]
This URL: 

http://www.mambiente.munimadrid.es/opendata/horario.txt 

is loading ok, and was set up as sync table. But 4h ago, it started giving me this error

![image](https://cloud.githubusercontent.com/assets/9017165/21523176/fb57eb14-cd0b-11e6-9c93-247451b4f339.png)

**Comment by saleiva** [comment]
cc/ @rafatower

**Comment by rochoa** [comment]
This is an expected error, see https://github.com/CartoDB/cartodb/blob/89ea62c9d57be71f6fc4640f91eabde8834cebbb/lib/cartodb/import_error_codes.rb#L142-L146.

If you think we might need to include more details with that "what_about" description, feel free to open another issue.

**Comment by AbelVM** [comment]
Just a comment, as it may help: 
When this file fails, only fails when retrieved from CARTO as sync table. The proxified version at https://scuf2hwap4.execute-api.us-east-1.amazonaws.com/dev works ok
