### ISSUE TITLE
Improve discoverability of suggested analysis

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#11147]
### Context
Some users have reported issues when on-boarding on the new UI, not finding some analysis that are key under some circumstances (such as georeferencing).

Proposed solution is designed at https://github.com/CartoDB/design/issues/354

Depending on the nature of the data, we propose the following ones

**Non-georeferenced data:**
Georeference
Join columns from 2nd layer.

**Points:**
Enrich from Data Observatory.
Areas of influence.
Create cluster of points.

**Polygons:**
Intersect second layer.
Enrich from Data Observatory.
Join columns from 2nd layer.

**Lines:**
Areas of influence
Join columns from 2nd layer.

**Comment by alrocar** [comment]
Stale issue. Closing 👋
