### ISSUE TITLE
Cannot save added geometry if attributes are filled

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartodb#11145]
### Context

When opening a map with a layer of points without widgets or analysis applied, if you add a new geometry by clicking on the map and filling some of the attributes, CARTO returns an error like this:

```
 error `PG::Error: ERROR:  invalid input syntax for type timestamp with time zone: ""↵LINE 1: ..., NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '') RETURN...↵                                                             ^↵"`
```

That does not happen if you try to add a geometry by clicking on the map without adding any attribute. 

However, if you try to add a geometry with attributes and CARTO returns an error, then you must go to the maps dashboard and enter again to the map in order to add the geometry without attributes, otherwise CARTO will return another error.

Tested with a point geometry layer.

### Steps to Reproduce

1. Open the map, click on the layer and click on the button to add a geometry.
2. Click on the map to add the new geometry, fill one of the attributes. For example, add a custom value to a field which is a String type. Adding `miau` to the String field `name`

![screen shot 2016-12-28 at 16 05 01](https://cloud.githubusercontent.com/assets/11177693/21524772/0b935baa-cd19-11e6-9c13-bc269a8b6044.png)

3. CARTO returns the error:

```
 error `PG::Error: ERROR:  invalid input syntax for type timestamp with time zone: ""↵LINE 1: ..., NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '') RETURN...↵                                                             ^↵"`
```

The expected result would be to add a new geometry on the map with the added attributes.

**Comment by oriolbx** [comment]
yes, there are 3 date columns created_at, updated_at and _year

**Comment by saleiva** [comment]
Ouch, this is back :(

**Comment by juanignaciosl** [comment]
This was reproduced while testing other issue. You can easily reproduce it with "T3chFest at Twitter" dataset: adding by clicking works, adding with the left form doesn't.

**Comment by nobuti** [comment]
Picking this

**Comment by nobuti** [comment]
Indeed, the date fields can't be null/empty. So in order to workaround this I think we have these choices:
- to fill all the fields affected with a date placeholder, I guess the current timestamp.
- to not allow to save the fields unless those fields are filled.

thoughts? @xavijam @saleiva

**Comment by nobuti** [comment]
In an unexpected turn of events, I found another simpler solution.

**Comment by nobuti** [comment]
Ready for CR.

**Comment by javitonino** [comment]
🚀
