### ISSUE TITLE
add WMS basemap layer returns 500 error

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartodb#11151]
### Context
When adding WMS map from this URL `https://services.slip.wa.gov.au/public/services/Landgate_Public_Services/Admin_Public_Services/MapServer/WMSServer`.

CARTO get the different WMS layers,  but when you add one of the layers to the map,for example `Local Government Authority (LGA) Boundaries (LGATE-006)`, CARTO returns several 500 errors. 
For example this one:

```
https://cartodb-wms.global.ssl.fastly.net/mapproxy/services_slip_wa_gov_au_7_EPSG_3857/wmts/map/webmercator/6/30/24.png Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```

![screen shot 2016-12-29 at 16 49 45](https://cloud.githubusercontent.com/assets/11177693/21547542/0ddc3728-cde7-11e6-98c5-67128fbbec6b.png)

However, the WMS layers are opened correctly in a software Desktop like QGIS

**Comment by ztephm** [comment]
@CartoDB/support let S/B 10905663 know when closed

**Comment by javitonino** [comment]
I think this is an issue with some kind of WMS proxy.

This is a tile from the upstream WMS server (works):
https://services.slip.wa.gov.au/public/services/Landgate_Public_Services/Admin_Public_Services/MapServer/WMSServer?FORMAT=image%2Fpng&LAYERS=2&TRANSPARENT=false&ANTIALIAS=none&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&SRS=EPSG%3A4326&BBOX=123.75,-33.75,135,-22.5&WIDTH=256&HEIGHT=256

When we add an WMS basemap, we register it with a map proxy. And in this case, after registering the layer, the map proxy fails even to display the metadata about that layer:
https://cartodb-wms.global.ssl.fastly.net/mapproxy/services_slip_wa_gov_au_7_EPSG_3857

pinging @CartoDB/systems to see if this is something they can help with

**Comment by javitonino** [comment]
I tracked it with @zenitraM to an issue with using HTTPS as the WMS url. Using http works. However, as that server is already registered as https, it won't work with this workaround, until we fix the underlying issue.

Moving to platform -> https://github.com/CartoDB/cartodb-platform/issues/2954
