### ISSUE TITLE
"Center map on layer" change is not correctly updated when publishing

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb#11159]
Looks like it stores 

`embed_zoom=builder_zoom-1`

Builder:
![image](https://cloud.githubusercontent.com/assets/9017165/21567267/450f1944-ceab-11e6-851c-133450ddfa66.png)

Embed:
![image](https://cloud.githubusercontent.com/assets/9017165/21567270/4ad5579e-ceab-11e6-9911-b1b2d7ce6799.png)

**Comment by AbelVM** [comment]
May be related to https://github.com/CartoDB/cartodb/issues/11158

**Comment by ramiroaznar** [comment]
Fixed!
