### ISSUE TITLE
embed: filter layersdata to only provide layerstyle

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#11160]
we're exposing way too much info in the `layersdata` var of the embed view, thus we should filter that in order to provide only what we need, in our case https://github.com/CartoDB/cartodb/pull/11121/files#diff-5b973e80628d9f6ee2347253d83d3e2a

```    if (d.options.tile_style) {
      attrs.cartocss = d.options.tile_style;
    }
    if (d.options.style_properties) {
      attrs.style = d.options.style_properties;
    }
```

ideally, we'd have a layerstyle with `cartocss`, `style`, and `id`

@juanignaciosl how feasible would it be to have this for https://github.com/CartoDB/cartodb/pull/11121 ?

thanks!

**Comment by juanignaciosl** [comment]
This shouldn't be a problem. Assigning @xavijam for prioritization. cc @CartoDB/builder-backend

**Comment by matallo** [comment]
after https://github.com/CartoDB/cartodb/pull/11121/commits/f13e2749eb9d4fd11acbc5a9aadf61110cae09d8 this doesn't seem to be needed anymore, closing then!

**Comment by javitonino** [comment]
As this has been reopened, does it need further work?

**Comment by matallo** [comment]
yeah, if I'm not wrong we'd only need the `cartocss` and `id` in the `layerStyle` https://github.com/CartoDB/cartodb/pull/11121/files#diff-5b973e80628d9f6ee2347253d83d3e2a so the rest of attributes can be discarded

**Comment by matallo** [comment]
like a charm!

**Comment by xavijam** [comment]
Closing since it is has been done and merged in the proper branch.
