### ISSUE TITLE
Text overflow in cartocss errors container

### ISSUE THREAD

**Issue by MariaCheca** [CartoDB/cartodb#11167]
In the Builder cartocss editor, when there's an error with large text it overflows the container.

<img width="492" alt="screen shot 2016-12-30 at 12 04 48" src="https://cloud.githubusercontent.com/assets/2141690/21589990/dd56404e-d0f7-11e6-8b25-443e7c2b09e2.png">

cc @CartoDB/frontend

**Comment by ramiroaznar** [comment]
Not happening anymore.

![image](https://user-images.githubusercontent.com/5215798/38198985-28b56256-368f-11e8-987a-48f0c5bae353.png)
