### ISSUE TITLE
Automatically casting boolean on import

### ISSUE THREAD

**Issue by peterdesmet** [CartoDB/cartodb#1116]
Since a short while CartoDB got a lot better at automatically casting fields (i.e. setting data type) on import. Dates and numbers are cast very well! :+1: Which is why I find it odd that boolean values are not.

This file has 4 ways to write boolean values:

```
string_1,number_1,date_1,boolean_1,boolean_2,boolean_3,boolean_4
hello,1,2014-03-21,TRUE,True,true,1
goodbye,2,2014-03-22,FALSE,False,false,0
```

But `boolean_1` to `boolean_3` are interpreted as `strings` and `boolean_4` as a number. I understand the latter one (keep numbers as numbers), but it would be nice if at least `boolean_1` was cast correctly. This is especially useful for synchronized tables, where one cannot manually cast fields after import. There is a workable solution to always cast them in select queries with `::boolean`, but still... there's room for improvement. :smiley:

**Comment by rafatower** [comment]
I checked type guessing is done correctly for cases 1,2,3. Type 4 is probably not implemented in gdal or would require a bigger input anyway to determine it's a bool column. I'm closing this FTM.
