### ISSUE TITLE
Widgets ordering lost when editing one widget

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb#11164]
### Context
Editing a widget "forgets" widget ordering
 

### Steps to Reproduce
1. You have several widgets, change the order of them. 
2. Enter in one of them and change a setting or the name of it. 
3. Go back. 
4. The widgets are now ordered in the original order

**Comment by saleiva** [comment]
Duplicated with #10302 but leaving this since it cointains better STR

**Comment by javierarce** [comment]
PR for this fix is here: https://github.com/CartoDB/cartodb/pull/11209
