### ISSUE TITLE
HEX color picker autocomplete

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#11169]
### Context
When entering a HEX color code using the color picker tool, it autocompletes rather quickly, making it difficult to enter the code manually. Especially for slow typers

### Steps to Reproduce

1. Create any simple map 
2. Open STYLE tab and try to select a color
3. Use the HEX code input field to type `#123`

  ![screen shot 2017-01-03 at 12 12 17](https://cloud.githubusercontent.com/assets/10940006/21606164/f8fb1d54-d1ad-11e6-8e8f-ed602ecd169f.png)

4. It will autocomplete to `#112233`

  ![screen shot 2017-01-03 at 12 12 38](https://cloud.githubusercontent.com/assets/10940006/21606168/0267e4c6-d1ae-11e6-81c2-df1958249a4f.png)

### Current Result
Currently, the color is autocompleted quickly, converting `#123` to `#112233` without any confirmation from the user

### Expected result
Autocompletion should happen after the user leaves the input field, rather than automatically

**Comment by saleiva** [comment]
It happens the same with the alpha decimals values

**Comment by saleiva** [comment]
Fields shouldn't autocomplete within this component
