### ISSUE TITLE
Changing the number of bins, changes the color ramp but does not refresh the map

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#11179]
### Context
Testing https://github.com/CartoDB/cartodb/issues/11095, I changed the bins of a widget with autostyle applied.

### Steps to Reproduce

1. Create a map with the tornado dataset
2. Add a histogram to the stf column
3. Apply autostyle over that widget
4. Change the number of bins in that widget from 10 to 11

### Current Result
The color ramp changes. The widget updates but the map does not. 

### Expected result
The widget and map are consistent

### Browser and version
Firefox 50 / Linux 

### .carto file
[Untitled Map 10 (on 2017-01-04 at 10.43.26).carto.zip](https://github.com/CartoDB/cartodb/files/684410/Untitled.Map.10.on.2017-01-04.at.10.43.26.carto.zip)

### Additional info
Not sure what the solution is here, maybe the ramp should be independent of the number of bins, or maybe we should refresh the map when changing bins.

cc @xavijam

**Comment by saleiva** [comment]
but the map ramp is independent from the number of buckets of the ramp, right?

**Comment by javitonino** [comment]
No, it isn't. The distribution can change depending on the number of bins, so a different ramp can be chosen depending on bins. 

Exaggerated example: Think of a two-tailed distribution. With many bins it looks like a two-tailed distribution. With just two bins, it looks like a uniform distribution.

**Comment by saleiva** [comment]
But the style is calculated based on the data not in the widgets buckets... In the future, number of buckets for widgets will be also calculated automatically

**Comment by javitonino** [comment]
AFAIK (looking at network requests), the data used for autostyle calculation is given in bins (the number of bins set by the user). You do not get all the data for detecting the distribution, just the aggregations (counts) for each of the bins.

**Comment by alrocar** [comment]
Stale issue. Closing 👋
