### ISSUE TITLE
Visibility changes cause CartoCSS syntax errors

### ISSUE THREAD

**Issue by Nikituh** [CartoDB/cartodb#11175]
### Context
I was changing the visibility of layers of an old editor map imported to builder.
Visualization id: bc1736a2-bb1a-4706-85e7-5621b7dd2591

### Steps to Reproduce
Rapidly turn on/off the visilibity of 'Colleges' or 'HUB Zones'

### Current Result
*Colleges: Failed to process "marker-fill" property: `=` requires more or same values than filters to work.*

*HUB Zones: Failed to process "polygon-fill" property: `=` requires more or same values than filters to work.*
 
Creates invalid CartoCSS ramp property:
`  polygon-fill: ramp([hubzone_st], (#A6CEE3, #1F78B4, #B2DF8A, #33A02C), (Not Qualified, Qualified, Redesignated until Jan. 2018, Redesignated until Mar. 2019), "=");`

Reverting changes it to:
```
#hubzone[hubzone_st="Qualified"] {
   polygon-fill: #1F78B4;
}
#hubzone[hubzone_st="Redesignated until Jan. 2018"] {
   polygon-fill: #B2DF8A;
}
#hubzone[hubzone_st="Redesignated until Mar. 2019"] {
   polygon-fill: #33A02C;
}
```

and then the issue disappears.

### Browser and version
Chrome Version 55.0.2883.95 (64-bit)

**Comment by javitonino** [comment]
Hey @Nikituh, can you also include a .carto file. Just "Export map" from Builder and upload it here (if there is no private data). It would be very useful for trying to reproduce.

**Comment by Nikituh** [comment]
Uh, the map is 73mb. Can't upload it to Github.

**Comment by javitonino** [comment]
Nevermind then 😆
