### ISSUE TITLE
Markov use should be limited to actual tables.

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb#11171]
Markov analysis only works with actual tables that exist in the database, it can't work against queries.

There should be a warning in Builder UI, or just block the user from using this analysis to a node that's not a source node with a query like `SELECT * FROM mytable`

cc @ohasselblad @saleiva

**Comment by saleiva** [comment]
Isn't this a bug and not an enhancement?

**Comment by AbelVM** [comment]
It's this way by design as of today. Andy can add more details. 

Right now if you try to run Markov on a node (or if every row have at least one `null` value in the time series), the analysis won't work... and won't end.

**Comment by saleiva** [comment]
Then I think we should fix it in the analysis and not in the UI :). That
goes against the general paradigm of the analysis workflows

**Comment by ohasselblad** [comment]
It's by design and part of the limitations we've experienced with PL/Python.. We've struggled with function signatures which are flexible enough to pass database data through to a Python environment, and settled on the current form which queries against the database with the Python portion, which doesn't allow for CTEs to be used. 

Some of the functions like kmeans and segmentation can get around it because they only need the column info passed as arrays, but markov, moran, gwr and spatial interactions (as PRs now) need to construct more complicated objects about the spatial neighborhood that we couldn't find an easy way to cram it into the signature of a pl/python function.

**Comment by saleiva** [comment]
summoing @javisantana

**Comment by AbelVM** [comment]
Btw, is this behaviour replicated in any other analysis? Moran?

**Comment by javisantana** [comment]
Umh, I see it accepts SQL queries: https://github.com/CartoDB/camshaft/blob/master/lib/node/nodes/sql/moran.sql#L5

**Comment by javisantana** [comment]
sorry: https://github.com/CartoDB/camshaft/blob/master/lib/node/nodes/sql/spatial-markov-trend.sql#L7

**Comment by AbelVM** [comment]
But the query **MUST** be like `SELECT * FROM my_real_table` in order to work

**Comment by ohasselblad** [comment]
it can be an arbitrary query

**Comment by javisantana** [comment]
@AbelVM could you provide a non-working example?

**Comment by AbelVM** [comment]
```sql
WITH tmp AS(
    SELECT * FROM my_real_table
)
SELECT * FROM tmp
```

does not work :(

**Comment by javisantana** [comment]
what is the error?

**Comment by AbelVM** [comment]
no message back, it just stays there... running forever

**Comment by ohasselblad** [comment]
This works from my account same as not doing the CTE. 
```
SELECT * FROM cdb_crankshaft.cdb_spatialmarkovtrend('WITH cte as (select * from zip_zhvi_singlefamilyresidence_nyc_region) select * FROM cte', Array['_2015_01', '_2015_02', '_2015_03', '_2015_04', '_2015_05', '_2015_06', '_2015_07'])
```

@AbelVM, is that an actual table with valid columns? Looks like there's a different problem with error reporting on the existence of columns/tables.

**Comment by AbelVM** [comment]
what if you create the `_2015_XX` columns on the fly?

On the other hand, the real value test here would be running the analysis from Builder, not SQL.

**Comment by ohasselblad** [comment]
on the fly meaning with 'alter table .. add column _2015_XX' and then run the analysis? as long as the column exists in that table at the time of the analysis running, all should be ok

**Comment by AbelVM** [comment]
Following our Slack chat, this pseudocode query should fail:

```sql
WITH
tmp1 AS(
    SELECT 
    *, 
    col1 as c1, 
    col2 as c2,
    ... 
    colN as cN 
FROM my_real_table
),
tmp2 AS(
    SELECT * FROM tmp1
)
SELECT * FROM tmp2
```
when applying Markov to columns **c1** to **cN**

**Comment by ohasselblad** [comment]
Yep, that'll fail. If there's a create table in there and it's cartodbfy'd (or has an appropriate id column and valid geoms in 4326) it should work.

**Comment by AbelVM** [comment]
So the thing is that it's not the table the one that should be a real table, but the columns that should be REAL columns, am I right?

**Comment by ohasselblad** [comment]
Yep, you're right. Whatever query is passed should have the columns specified in the second argument. Otherwise it should fail and report that the column doesn't exist. Just opened a ticket about that: https://github.com/CartoDB/crankshaft/issues/156

**Comment by AbelVM** [comment]
Same behavior in Moran, from this simplest node:

```sql
SELECT
*,
column_A as column_B
FROM myDataset
```
You can not apply Moran to `column_B`. It does not fail, gives no message back, but it keeps running forever and ever.
