### ISSUE TITLE
Fallback mechanism for Locales in "pluggable frontends" functionality

### ISSUE THREAD

**Issue by jorgesancha** [CartoDB/cartodb#11177]
Continuing with the "pluggable frontends" work implemented in #10724, we should improve how locale literals are overwritten.

Currently it's easy to add new items to a locale file, but there's no way to modify existing items without virtually copying the whole file.

It should be possible to update just a few literals without modifying the core file and without needing to duplicate the whole core file. It should be a fallback mechanism, such that, if a literal is present in the customized version, it gets picked up; otherwise, it falls back to the core locale file to look for the literal.

Please review and update issue if necessary @danicarrion @matallo @xavijam @javisantana

**Comment by matallo** [comment]
it's true that it was easy to _append_ new i18n strings, but not that easy to replace (without losing siblings)

I modified a bit the example, and replaced the underscore's `_.defaults` with jquery's `$.extend` which can do a deep extend

find the implementation in https://github.com/CartoDB/cartodb/pull/11180
