### ISSUE TITLE
Allow multiple admins in organizations

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#11170]
### Context
https://docs.google.com/a/cartodb.com/document/d/1e9mtqIFaxmkL-S0UCJGpzZc8eUKbSmmUqtWsHgy2PCY/edit?usp=sharing

**Comment by juanignaciosl** [comment]
@CartoDB/builder-backend when this gets prioritized, we should come up with *the simplest solution* that allows the following for admin users:

- they can access org admin
- the can not add admin users
- the can login as other users (so we don't need any special database permission)

PS: although this also requires UI design, backend work can begin before that.

**Comment by gfiorav** [comment]
On the side question: Will they have access to EUMAPI? 

> they can access org admin

This is the admin panel?

> the can login as other users (so we don't need any special database permission)

This is something that not even the org admin can do right now right?

**Comment by juanignaciosl** [comment]
- EUMAPI: I'd say so (although it's not be needed in the first step).
- Yes, admin panel.
- No, they can't right now. Impersonation is discussed in another thread.

**Comment by javitonino** [comment]
Left a comment in the doc, but the question is: are builder/viewer and owner/admin/user two separate rolesets? I mean, can an admin user be a viewer and a builder? I think yes, it makes sense to me to have account management permissions separate from application use permissions, but I could not find this explicitly specified.

**Comment by juanignaciosl** [comment]
@saleiva should this be addressed now, then?

**Comment by juanignaciosl** [comment]
@saleiva just told me that this has left the short term scope, so I'll close this until we have more information about what is needed.
