### ISSUE TITLE
CartoDB should automatically take care of basemap attributions

### ISSUE THREAD

**Issue by cquest** [CartoDB/cartodb#1118]
Many CartoDB users/customers are not attributing the basemap they use properly, especially OpenStreetMap based ones.

OpenStreetMap requires proper attribution on the map itself, not behind a link that contains a liste of "possible" source of map data.

In many cases, we even find a CartoDB logo + a cartodb attribution link... and nothing regarding OpenStreetMap.

Here is an example (it may have been updated since this issue has been written): http://www.eca-watch.org/node/3637
- CartoDB logo
- Leaflet attribution
- Mapbox attribution
- CartoDB second attribution

CartoDB must address this recurring issue directly in its software stack as most users/customers do not understand all this and fail to comply with data related licenses.

Chrstian Quest - OpenStreetMap France president

**Comment by jsanz** [comment]
Hi closing this ticket as CartoDB shows attribution of datasets if they have the proper metadata as per #5216 .
