### ISSUE TITLE
provide a mechanism to override cartoassets in plugable frontends

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#11182]
@danicarrion is trying to modify assets in cartoassets submodule but looks like there is no way (if there is and we don't know please answer this ticket)

proposed solutions:
- working on branches in a fork of cartoassets and point the submodule to the right thing
- carto assets take precedence over cartoasset ones

cc @matallo @jorgesancha

**Comment by matallo** [comment]
just add the file under the client cartoassets folder and the styles will be overriden, as in the next example

https://github.com/CartoDB/cartodb/blob/10724-assets-path-example/app/assets/client/stylesheets/cartoassets/typography.scss

**Comment by saleiva** [comment]
can we close?

**Comment by matallo** [comment]
yay!
