### ISSUE TITLE
Issuer is not properly defined in saml.rake

### ISSUE THREAD

**Issue by rporres** [CartoDB/cartodb#11199]
In https://github.com/CartoDB/cartodb/blob/master/lib/tasks/saml.rake#L17 `saml_issuer` should be named `issuer`

cc @javitonino

**Comment by javitonino** [comment]
cc @juanignaciosl

**Comment by javitonino** [comment]
We'll take care of this with https://github.com/CartoDB/cartodb/issues/11153
