### ISSUE TITLE
Ensure all analysis onboarding screens link to carto.learn guides

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#11193]
A link in the  "join from 2nd layer" analysis onboarding is pointing to an old map academy sql lesson instead of the new guide (https://carto.com/learn/guides/analysis/join-column-from-second-layer). 

We should change the link to point to right resource.

See the linked issue for a detailed discussion of the problem and reference screenshot.

**Comment by javierarce** [comment]
cc: @saleiva

**Comment by saleiva** [comment]
+1

**Comment by mehak-sachdeva** [comment]
Looks great to me - thanks @xavijam !

**Comment by nobuti** [comment]
Closed by #11706.
