### ISSUE TITLE
Remove toggle option from widgets

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#11192]
### Context
Running a research on how many people uses this feature and for what. 
So far, only 4% of our users are using this feature, and very often they get the widgets to the default state very soon. Will update the numbers after some days more of monitoring.

Removing this option would clean up slightly the deep-insights code as well :)

**Comment by xavijam** [comment]
It wil need work in deep-insights before.

**Comment by saleiva** [comment]
Confirmed, with a sample of 1000 users, less than 9% used this feature and they toggle back the widget in most of the cases after a while.

**Comment by nobuti** [comment]
This could be a good issue to take contact with DI for new hires.

**Comment by saleiva** [comment]
before starting with this, LMK so I can check the metrics back

**Comment by saleiva** [comment]
Removing next until we got another try to the metrics
