### ISSUE TITLE
Make layer panel scrollbar wider

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#11190]
### Context
When not using a trackpad or a mouse scroll wheel, it is very hard to scroll the layers. Also, it doesn't appear until scrolling which is very unintuitive

**Comment by saleiva** [comment]
I would do the same we did with the horizontal scrollbars on the carrousels @piensaenpixel

**Comment by piensaenpixel** [comment]
I can take care...

**Comment by nobuti** [comment]
After talking to @piensaenpixel, and taking in mind the hack we already did in deep insights to support the same this functionality, IMO this belongs to the scroll library we are using as dependency, and we should fork the library and augment it, including the proper PR. This will allow us more flexibility, avoiding code repetition.

**Comment by nobuti** [comment]
I unassigned me to prioritise other issues, no work has been done. I'm leaving it in the development column though.

**Comment by nobuti** [comment]
@piensaenpixel topic branch 11190-scrollbar

**Comment by nobuti** [comment]
The modifications to the library are here: https://github.com/nobuti/perfect-scrollbar/pull/1, and the wip PR is https://github.com/CartoDB/cartodb/pull/11233

**Comment by nobuti** [comment]
This is ready for CR.

**Comment by nobuti** [comment]
Adding the `do not merge yet` label until the PRs in deep-insights and cartodb are merged.

**Comment by xavijam** [comment]
Deployed!
