### ISSUE TITLE
Category widget is failing when aggregating not by COUNT

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb#11198]
1. Simple map
2. Add category widget 
![image](https://cloud.githubusercontent.com/assets/9017165/21688468/3700e4e2-d36d-11e6-8d7f-dcc6e8ac78c4.png)
3. change the aggregation to any other than COUNT, over a numeric column
![image](https://cloud.githubusercontent.com/assets/9017165/21688493/59437f7e-d36d-11e6-8a3e-16ffa98c04c9.png)
4.The widget is now like
![image](https://cloud.githubusercontent.com/assets/9017165/21688508/6789d06a-d36d-11e6-959b-f0644bf082a8.png)

Looks like the reason is that the NULL values in the column fuck up the aggregations. We should set null values aside before aggregating

cc @saleiva

**Comment by AbelVM** [comment]
cc @javisantana

**Comment by AbelVM** [comment]
cc @rochoa

**Comment by AbelVM** [comment]
Rochoa found the cause: the sorting in the frontend is setting NULL above all the other values!!!

**Comment by rochoa** [comment]
Two issues: we are not taking out `null` values, there are categories with just `null` values.

```
postgres=# \pset null '(null)'
Null display is "(null)".
postgres=# with numbers as (select 1 as n UNION ALL select null)
postgres-# select * from numbers order by n desc;
   n
--------
 (null)
      1
(2 rows)
```

JavaScript is the other way around:

```js
> [null, 1].sort()
[ 1, null ]
```

We need to remove nulls. Similar to https://github.com/CartoDB/Windshaft-cartodb/issues/497  and https://github.com/CartoDB/Windshaft-cartodb/issues/496.

**Comment by jorgesancha** [comment]
The removal of the nulls will be prioritised in Engine's board.

Apart from removing the null values, should we sort in the Javascript differently to ensure that whatever the results they are always sorted equally?

**Comment by AbelVM** [comment]
```javascript
my_array = [1,2,null,5,-1, null,12, null, 9999, -23, 53.21];

my_array.sort(function(a,b){
    return (b == null)? -1 : ((a == null) ? 1 : b-a);
});

// result:
// [9999, 53.21, 12, 5, 2, 1, -1, -23, null, null, null]
```

**Comment by jorgesancha** [comment]
Unblocking this to solve the "Frontend" sorting issue (independently of the Backend issue which will be solved by Engine)

**Comment by nobuti** [comment]
There is a PR in cartodb.js trying to fix this https://github.com/CartoDB/cartodb.js/pull/1546

**Comment by nobuti** [comment]
This is in ded03.

**Comment by nobuti** [comment]
Almost there, PR in cartodb.js is closed to be accepted.

**Comment by nobuti** [comment]
Ready for acceptance.
