### ISSUE TITLE
Infinite scroll on horizontal widget list on builder

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#11194]
### Steps to Reproduce

1. Create a map
2. Make your browser window small (< 1200px width) so the widget layout goes to bottom
3. Add a lot of widgets (the minimum I've been able to reproduce is 6)
4. Scroll to the right on the widget list

### Current Result
No scrolling limit

![screenshot_20170105_125915](https://cloud.githubusercontent.com/assets/7569673/21679903/c9f326d8-d346-11e6-9f4e-7cebbd35db55.png)
 
### Expected result
Scrolling stops after the last widget

### Browser and version
Firefox and Chrome on Linux

cc @xavijam (the trick is in the number of widgets, minimum of 6 to reproduce)

**Comment by nobuti** [comment]
The improvements on perfect-scrollbar library on https://github.com/CartoDB/cartodb/issues/11190 fix this. I'm adding it to the list to check.
