### ISSUE TITLE
Time-series widget + Pixel aggregation: widget labels error

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#11196]
### Context
When using a *PIXEL* aggregation to visualize data, if a *time-series* widget is added, it shows incorrect labels
 
![screen shot 2017-01-05 at 14 35 01](https://cloud.githubusercontent.com/assets/10940006/21682588/bebe97e8-d355-11e6-8669-934024c9c953.png)

### Steps to Reproduce

1. Create a map from a point's layer with a timestamp column
2. Choose *PIXEL* aggregation
3. Add a *time-series* widget using the timestamp column

**OR**

* Import this `.carto` file: 
[pixel_agg-timeseries_widget_labels.carto.zip](https://github.com/CartoDB/cartodb/files/687355/pixel_agg-timeseries_widget_labels.carto.zip)

### Current Result

Widget's labels are incorrect, showing `1.5G` in all buckets
 

### Expected result
Labels should be showing timestamp information

### Additional info

S/B: 10988489

**Comment by oriolbx** [comment]
SB/11083745 has the same problem too

**Comment by saleiva** [comment]
similar to https://github.com/CartoDB/cartodb/issues/11345

**Comment by oriolbx** [comment]
what is the status of this issue? @saleiva @xavijam

**Comment by saleiva** [comment]
@oriolbx we are going to start working on this fixes very very soon.

**Comment by xavijam** [comment]
Screenshots with the data and working properly:

![screen shot 2017-08-08 at 11 43 20](https://user-images.githubusercontent.com/132146/29066232-e748dfb6-7c2e-11e7-8ac9-a8a3b524584a.png)
![screen shot 2017-08-08 at 11 43 33](https://user-images.githubusercontent.com/132146/29066233-e74a89b0-7c2e-11e7-857a-72d74aee97ac.png)

Although there is something not working properly. When we select heatmap (static one, not the animated) and then we add the time-series, it adds an animated one. That's not correct and it is a bug. Let me open a ticket.

**Comment by oriolbx** [comment]
Thanks ! Should I close this one then? @xavijam

**Comment by xavijam** [comment]
Yes! closing this one, opening https://github.com/CartoDB/cartodb/issues/12571.
