### ISSUE TITLE
No pagination/scroll when adding custom WMS basemap

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#11216]
### Context
When adding a custom WMS basemap from a server with several layers, there is no way to get past the first few layers.

### Steps to Reproduce
1. Go to builder, create a new map
2. Change the basemap, choose custom and WMS
3. Enter a WMS url with multiple layers, e.g: https://services.slip.wa.gov.au/public/services/Landgate_Public_Services/Admin_Public_Services/MapServer/WMSServer

### Current Result
The listing of the layers is very limited, as there is no scroll nor pagination:

![screenshot_20170110_175447](https://cloud.githubusercontent.com/assets/7569673/21815782/24fb8884-d75e-11e6-8e7c-5b843ee0a1a0.png)
 

### Expected result
All layers should be displayed somehow:

![screenshot_20170110_175502](https://cloud.githubusercontent.com/assets/7569673/21815795/2dee9544-d75e-11e6-8355-67f673d86b93.png)

### Browser and version
Firefox and Chrome, Linux 

cc @saleiva @jorgesancha

**Comment by saleiva** [comment]
Duplicated! https://github.com/CartoDB/cartodb/issues/11132
