### ISSUE TITLE
Wrong dashboard load after signinup up with SAML into an org

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#11215]
### Steps to Reproduce
1. Signup into an organization using SAML

### Current Result
After signing up via SAML, and account creation finishes, you are shown a corrupted dashboard:

 
![screenshot_20170110_172157](https://cloud.githubusercontent.com/assets/7569673/21814355/59861f92-d759-11e6-8bca-52799b63f424.png)
![screenshot_20170110_172124](https://cloud.githubusercontent.com/assets/7569673/21814373/670badda-d759-11e6-9041-ed76bcb0a41c.png)
![screenshot_20170110_172143](https://cloud.githubusercontent.com/assets/7569673/21814359/5cb97fd8-d759-11e6-8ff3-74182755a5c7.png)
 

All requests authenticated via cookie return 401.

After refreshing the page (F5), you get redirected through the login process like this:

![screenshot_20170110_172441](https://cloud.githubusercontent.com/assets/7569673/21814457/aebcab34-d759-11e6-8bd3-2f8a5dfbe102.png)

And you finally get to the dashboard, correctly.

### Expected result
You are correctly authenticated and the dashboard loads fine.

### Browser and version
Tested Firefox and Chrome

### Additional info
It seems like cookies are not set correctly upon account creation. I suspect a mixup of user and organization scopes.

**Comment by juanignaciosl** [comment]
Moved to TODO cc @saleiva @xavijam @jorgesancha

**Comment by javitonino** [comment]
Confirmed that this is also happening for Google signups. Note that in staging/production the dashboard loads correctly, but you can still see the requests failing in the network console, until you refresh the dashboard.
