### ISSUE TITLE
Filter by layer analysis requests visualizations unnecessarily

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#11218]
### Context
When adding a filter by layer analysis, only other nodes can be selected as targets. However, a request is made to list all the tables the user has access to.

### Steps to Reproduce
1. Create a map
2. Add an analysis, select filter by layer

### Current Result
A request is made to the visualization endpoints (which is slow, see #11217) 

### Expected result
We avoid the request.

**Comment by alrocar** [comment]
Stale issue. Closing 👋
