### ISSUE TITLE
Bug in Local organisation assets

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#11234]
### Context

@ivanmalagon is implementing organization assets front and while S3 is working, local has a bug where a variable `public_uploads_path` is missing. This variable should be `public/uploads` and must have been removed by accident in a refactor. The fix is a one-liner.

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Upload an asset without configuring s3.

### Current Result

500 error complains about the missing variable.

 

### Expected result

The asset is stored in local.

**Comment by juanignaciosl** [comment]
Added directly to CR because it's a quick fix for a bug that was blocking for @ivanmalagon cc @jorgesancha

**Comment by ivanmalagon** [comment]
Did the acceptance in `11006-org-icons-preview` development branch, where we have UI to test this issue.

Icons uploaded to local storage when configured that way. For instance, the result of uploading an icon to local storage has been `http://localhost.lan:3000/uploads/organization_assets/c210c579-0780-4ccd-83a8-7bf9fee11b34/asset_download_148430500720170113-24519-w0cjen`

🇯🇲
