### ISSUE TITLE
Cannot choose an alternate name in google signup if only google is used

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#11238]
### Context
Similar to #11236

When using google signup and only this signup method is enabled, there is now way to choose an alternate username if it fails. This only affects org signups (Central works).
 

### Steps to Reproduce
1. Create an organization with only google auth enabled
2. Try to sign in with a google account that will conflict with an existing username (but not email)

### Current Result
No way to choose alternative username:
![screenshot_20170112_120632](https://cloud.githubusercontent.com/assets/7569673/21887268/92637014-d8bf-11e6-9943-c68c02222507.png)

 ### Expected result
Display username field to be able to change it

**Comment by saleiva** [comment]
I'd consider this an enhancement.

**Comment by MariaCheca** [comment]
Moving back to development due to a bunch of things that should be reviewed https://github.com/CartoDB/cartodb/pull/11256#issuecomment-272889881

**Comment by javierarce** [comment]
👍  
![image](https://cloud.githubusercontent.com/assets/4933/22014404/c92ff720-dc9d-11e6-9890-58af29c737e8.png)
