### ISSUE TITLE
Copy Change in the UI "Behavior  

### ISSUE THREAD

**Issue by asimcox** [CartoDB/cartodb#11232]
### Context
In the widgets pane, need to change behavior from British English to American English to be consistent with all of our other marketing materials/best practices. 

behaviour --> behavior 
 
### Steps to Reproduce
Login and add widgets and look at left hand pane.

### Current Result
*Please describe here below the current result you got*

 <img width="1264" alt="copy edit in ui" src="https://cloud.githubusercontent.com/assets/16105514/21860475/beddf680-d7fe-11e6-978f-7832a74ee721.png">

### Expected result
*Please describe here below what should be the expected behaviour* <--- hahaha

cc' @vuxita  based on our quick chat ^

**Comment by xavijam** [comment]
💋

**Comment by xavijam** [comment]
In production!
