### ISSUE TITLE
Persistent Notifications in Builder UI

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#11244]
### Context
There are certain actions that trigger notifications in Builder UI. Sometimes these notifications are impossible to close by clicking on *X* button, with no errors appearing in the console. 

This bug [has already been reported](https://github.com/CartoDB/cartodb/issues/10734), but without clear STR. 

I've found some STR that work, but bear in mind that this bug may still appear in different situations. 

### Steps to Reproduce

1. Create a map with one layer *A*
2. Style that layer *BY VALUE* in order to make a legend appear
3. Open *Map Options*
4. Turn *LEGENDS* **off**
5. Turn *LEGENDS* **on** again (this may look silly, but I couldn't reproduce the issue without this step)
6. Add a second layer *B*
7. From the layer list, hide *A* by clicking on the 'eye' icon
8. Open *Map Options* and enable the *LAYER SELECTOR* 
9. Use the layer selector to **activate** layer *A*
10. Use the layer selector to **deactivate** layer *A*
11. Open *LAYERS* pane, see notification below
12. Click *X* to close notification

### Current Result
The notification doesn't close

 

### Expected result
The notification should close

### Browser and version
Tested in Chrome v55

cc/ @saleiva

**Comment by saleiva** [comment]
I have seen this same problem in other random situations. I think it would be worth to take a look at this logic

**Comment by saleiva** [comment]
spotted this a few times more

**Comment by nobuti** [comment]
Picking this.

**Comment by nobuti** [comment]
Ready for CR

**Comment by ivanmalagon** [comment]
Deployed to produ.
