### ISSUE TITLE
autostyle not working when rows have `'` character

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#11246]
### Context
When trying to autostyle a map, the next error will appear in the notifications:

> rutas_pirineos_tracks_posets_por_refugio_angel_orus_waypoints: Failed to parse expression: "([mapnik::geometry_type] = 1) and ([name] = 'Cascada d\\'Espigantosa')" in style '91cd9fd0-e625-4191-b869-1b28d82b9a4e' in Style

![10a04654-ed90-4aef-afc3-47060b5e0473](https://cloud.githubusercontent.com/assets/36676/21901771/5ae74e5a-d8f9-11e6-928b-104af5615cac.png)

it will happen randomly as not always the same values will appear in a widget

no error will be shown in the console

### Steps to Reproduce

1. create a map
2. fill a row with the `'` character
3. add a widget
4. click autostyle

### Current Result
cartocss error
 
### Expected result
applied autostyle
 
### .carto file

[Rutas Pirineos Tracks Posets Por Refugio Angel Orus Waypoints (on 2017-01-12 at 17.55.30).carto.zip](https://github.com/CartoDB/cartodb/files/702473/Rutas.Pirineos.Tracks.Posets.Por.Refugio.Angel.Orus.Waypoints.on.2017-01-12.at.17.55.30.carto.zip)

**Comment by xavijam** [comment]
That's a good one, let me take a look meanwhile I'm with other bug in the autostyle.

**Comment by matallo** [comment]
all yours man, it caused the worst demo ever 😞

**Comment by xavijam** [comment]
It should be fixed with https://github.com/CartoDB/deep-insights.js/pull/512 in deep-insights. Demo will be back to life, promise :).

**Comment by MariaCheca** [comment]
Acceptance passing in https://github.com/CartoDB/deep-insights.js/pull/512
