### ISSUE TITLE
Serve `public/uploads` files with CORS

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#11243]
### Context

This was discovered by @ivanmalagon when testing locally stored organisation assets.  

### Steps to Reproduce

1. Use a locally stored asset in front

### Current Result

```
settings:1 Access to Image at 'http://localhost.lan:3000/uploads/organization_assets/up…0780-4ccd-83a8-7bf9fee11b34/asset_download_148421623820170112-17158-n63s3l' from origin 'http://globex.localhost.lan:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://globex.localhost.lan:3000' is therefore not allowed access. The response had HTTP status code 404.
```
 

### Expected result

The asset is displayed.

**Comment by juanignaciosl** [comment]
On development and acceptance, please check that this feature works if you use `RAILS_PUBLIC_UPLOADS_PATH` environment variable.

**Comment by javitonino** [comment]
That URL seems very very wrong! It includes the complete local path. Are we showing that in the presenter? Also, the URL probably should include a subdomain.

**Comment by gfiorav** [comment]
Hey @javitonino , ignore that. We copied the an example from a previous experiment. The real one doesn't look like that at all 😂

**Comment by javitonino** [comment]
😅 You had me scared for a second there ;)

**Comment by gfiorav** [comment]
But, regarding the subdomain: should it? I vouched no when I implemented it. Why should it have a subdomain?

**Comment by javitonino** [comment]
For one, it's the easiest way to fix CORS issues.

**Comment by gfiorav** [comment]
Good point, hehe. I think it would be nice to support the icons loading outside of the subdomain, as there is no inherent reason why the shouldn't. I mean, I know it sounds perfect since it's an organization bound thing, but we might want them to load outside of that subdomain in some embed or in subdomainless.

**Comment by javitonino** [comment]
The embeds use the same domain as the organization so not an issue there. Subdomainless should not be an issue as everything is under the same domain. URL generation for the assets should be done using the helpers that take the configuration into account, so it adds the subdomain only if subdomainless is disabled.

**Comment by gfiorav** [comment]
Ok, but remember that this URL is stored in db. 

Two options:

1. Store without subdomain and have front add it if needed.
2. Store with org domain.

**Comment by javierarce** [comment]
👍  Acceptance passed. 

I tested uploading an asset with and without using the `RAILS_PUBLIC_UPLOADS_PATH` param and also with and without org subdomain.
