### ISSUE TITLE
Change of text color in the navigation of expert mode

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#11257]
### Context

Right now the text color in the expert mode nav is incorrect. Links should always be white, like everywhere else on expert mode, but in the nav the links are grey. 

Design issue: https://github.com/CartoDB/design/issues/489#issuecomment-272486407

### Current Result

<img width="535" alt="screen shot 2017-01-16 at 14 09 42" src="https://cloud.githubusercontent.com/assets/16247628/21984266/72f45fac-dbf5-11e6-8d61-0d383acfa239.png">

### Expected result

![3e596f72-d9a6-11e6-8673-b61ecb5188d7](https://cloud.githubusercontent.com/assets/16247628/21984116/a9a6c5ae-dbf4-11e6-8c6e-66534aac5702.png)

**Comment by Jesus89** [comment]
Closed by CartoDB/cartodb#14140

In production! :rocket:
