### ISSUE TITLE
Add an analysis will fail if autostyle is applied

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#11252]
### Context

* This bug was found doing the "Risk Analysis Demo".

### Steps to Reproduce

1. Create a map with two layers (points - A, and polygons - B).
2. Add Intersect analysis to B layer.
3. Add histogram widget from "sum_value".
4. Autostyle.
5. Add Outliers & Clusters analysis.

### Current Result

* An error related to CartoCSS pops up and the analysis fails.

`US Counties: style0:18:2 Invalid code: polygon-fill: ;style0:19:2 Invalid code: polygon-opacity: ;`

![error](https://cloud.githubusercontent.com/assets/5215798/21978723/1889ac70-dbdc-11e6-8ad9-145c15260757.png)

### Expected result

* Analysis should run OK.

### Browser and version

* Google Chrome v54.

### .carto file

* [Risk Analysis Demo (on 2017-01-16 at 10.04.16).carto.zip](https://github.com/CartoDB/cartodb/files/707973/Risk.Analysis.Demo.on.2017-01-16.at.10.04.16.carto.zip)

**Comment by xavijam** [comment]
In fact, after a deep look, if autostyle is selected and we apply a new analysis on top of the layer where the autostyle is applied, the map instantiation will fail. Changing the title @ramiroaznar.

**Comment by nobuti** [comment]
Back to development, some errors with lines raised.

**Comment by xavijam** [comment]
:+1:, taking care of it, thanks man 💋

**Comment by MariaCheca** [comment]
Merged https://github.com/CartoDB/cartodb/pull/11261
