### ISSUE TITLE
Hiding a layer while it is autostyled, persists the autostyle

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#11258]
### Context
Found while doing acceptance for https://github.com/CartoDB/cartodb/issues/11137 

### Steps to Reproduce
1. Create map
2. Add a category widget
3. Autostyle using the widget
4. Hide the layer
5. Refresh the builder
6. Unapply autostyle

### Current Result
The autostyle is kept 

### Expected result
Style is reset to original.

cc @xavijam

**Comment by xavijam** [comment]
Well, for me it is related with #11137, isn't it?

**Comment by javitonino** [comment]
Yeah, talking with @nobuti. Not sure if you guys prefer to address it in the same PR or as a different ticket.

**Comment by nobuti** [comment]
This will be tackled in #11137.
