### ISSUE TITLE
layer selector does not hide properly the layer with pixel aggregation style 

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartodb#11265]
### Context
If we create a layer using the `aggregation pixel` style to create a heatmap and enable the `layer selector` option in the CARTO map. 

When you click on the checkbox to hide the layer, you need to click two times to uncheck the checkbox, the first click hides the layer and the second click uncheck the checkbox.
 

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Create map from point dataset.
2. In the style menu of the layer, set the aggregation to `pixel` 
3. Enable layer selector

![screen shot 2017-01-16 at 17 53 17](https://cloud.githubusercontent.com/assets/11177693/21991923/c5b752ac-dc14-11e6-8769-4276d1dc04f5.png)

4. click on the checkbox of the layer selector to hide the layer, the layer is hidden but the checkbox is still with `checked` option

![screen shot 2017-01-16 at 17 53 24](https://cloud.githubusercontent.com/assets/11177693/21991928/c958026c-dc14-11e6-87da-430a172145ce.png)

5. Click again on the checkbox to uncheck it completely.

![screen shot 2017-01-16 at 17 53 35](https://cloud.githubusercontent.com/assets/11177693/21991934/cd96c0c0-dc14-11e6-850a-23ac8474d052.png)

6. Click again on the checkbox, the layer is shown correctly.

**Comment by saleiva** [comment]
id prioritize this

**Comment by oriolbx** [comment]
Are there any updates regarding this issue?

**Comment by saleiva** [comment]
dupoe! https://github.com/CartoDB/cartodb/issues/11280

**Comment by oriolbx** [comment]
This is still happening. @saleiva this is not the same issue as https://github.com/CartoDB/cartodb/issues/11280  afaik.

**Comment by saleiva** [comment]
ah ok! sorry!

**Comment by oriolbx** [comment]
It looks like that it's fix :) Closing issue, open again if needed !
