### ISSUE TITLE
It's impossible to open click POP-UPS within Builder interface

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#11264]
### Context
When you click on a feature, the Geometry Editing button appears every time. This prevents click POP-UPS from appearing, making them impossible to preview before publishing
 

### Steps to Reproduce

1. Create a map
2. Set a click POP-UP
3. Click on any feature

### Current Result
Geometry Editing button appears, but not the POP-UP

![screen shot 2017-01-16 at 17 38 08](https://cloud.githubusercontent.com/assets/10940006/21991373/a26411de-dc12-11e6-9b94-2308fc369338.png)

 

### Expected result
There should be a way to open a click POP-UP within Builder interface, without showing Geometry Editing button

**Comment by xavijam** [comment]
@alonsogarciapablo is taking a look, there is a JS error.

**Comment by alonsogarciapablo** [comment]
@ernesmb this should be fixed now! Thanks!

**Comment by xavijam** [comment]
Thanks @alonsogarciapablo 💋

**Comment by ernesmb** [comment]
it is! thanks!! 🚀 

![screen shot 2017-01-17 at 12 42 49](https://cloud.githubusercontent.com/assets/10940006/22019140/85ef4e2e-dcb2-11e6-88c0-c30d463808f8.png)
