### ISSUE TITLE
Import error email visuals don't fit the message

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#11269]
From CartoDB/design/issues/491

The visual language is a bit confusing:

![image](https://cloud.githubusercontent.com/assets/9017165/21980951/87c42094-dbe5-11e6-9ddd-6f2f9713be9e.png)

Looks like everything went fine, instead of raising an error

It looks like current import mail code doesn't support error messages.

cc @AbelVM @saleiva @xavijam @MariaCheca

**Comment by juanignaciosl** [comment]
![screen shot 2017-01-17 at 11 21 33](https://cloud.githubusercontent.com/assets/932968/22016594/290a9e58-dca7-11e6-936c-fcfe93b5e02c.png)

Some errors trigger the right visuals. @AbelVM do you know what triggered your original error mail?

**Comment by AbelVM** [comment]
Inconsistent **cartodb_id**. It was an import from query, so (my fault) there were some duplicated values for primary key.

**Comment by juanignaciosl** [comment]
![screen shot 2017-01-17 at 11 43 54](https://cloud.githubusercontent.com/assets/932968/22017340/4772ca98-dcaa-11e6-8a18-9af23ac8a670.png)

I can't reproduce with repeated `cartodb_id` values. I'l keep trying, please let me know if you come up with other possible problem.

**Comment by AbelVM** [comment]
```sql
SELECT * FROM mytable
UNION ALL
SELECT * FROM mytable
```

And then, "create dataset from query"

**Comment by juanignaciosl** [comment]
Oh, great, thanks! This uses a different workflow than normal importing. Your steps reproduce the error 👍

**Comment by juanignaciosl** [comment]
Two actual issues here:
- Error display is decoupled from errors itself.
- Duplicating a dataset doesn't store created tables metadata.

**Comment by javitonino** [comment]
Did acceptance, everything seems to work fine. Just a question: Are synchronization imports supposed to send emails? I did not receive an email for those (neither for ok and failure cases).

**Comment by javitonino** [comment]
Imports from data library also do not trigger emails. Not sure if it is intended.

**Comment by saleiva** [comment]
I think yeah @javitonino, both should trigger emails

**Comment by javitonino** [comment]
@juanignaciosl @saleiva There is the following in the code:
```
      def should_notify?
        import_time >= MIN_IMPORT_TIME_TO_NOTIFY && @data_import.synchronization_id.nil?
      end
```

So no email will be sent for synchronizations (also not for data library, as those are syncs).

So for me, this is ✅ in acceptance as the issue in question has been fixed.

@saleiva If you feel we should send email when a synchronization imports, feel free to open a different ticket. Not sure if it makes much sense, as I think the email is not sent for a good reason (to avoid spamming the user every time it resyncs), but maybe it's worth it for the initial import?

**Comment by juanignaciosl** [comment]
No, those are not meant to send emails, as code says. The syncs would be too spammy (but I'm just guessing the original intention of avoiding those emails).

**Comment by AbelVM** [comment]
No, please, sync tables should not send emails :open_mouth:
