### ISSUE TITLE
can't import datasets with the same file name

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#11279]
**str**

- import attached `.gpx`
- try to import again

[RUTAS-PIRINEOS-tracks-posets-por-refugio-angel-orus.gpx.zip](https://github.com/CartoDB/cartodb/files/711231/RUTAS-PIRINEOS-tracks-posets-por-refugio-angel-orus.gpx.zip)

**Comment by ethervoid** [comment]
Error comes because of an existing type:

```
2017-01-17 14:10:29 UTC: Before moving schema 'rutas_pirineos_tracks_posets_por_refugio_angel_orus_waypoints_2' from cdb_importer to XXX
2017-01-17 14:10:29 UTC: Exception: PG::Error: ERROR:  type "_rutas_pirineos_tracks_posets_por_refugio_angel_orus_waypoints_" already exists in schema "XXX"
```

Checked that the type already exists:

```
cartodb_user_6b304b59-2c86-4d7b-a8a2-dc98a5a35d48_db=# select exists (select 1 from pg_type where typname = '_rutas_pirineos_tracks_posets_por_refugio_angel_orus_waypoints_');
 exists
--------
 t
(1 row)
```

but I can't find it, requires further investigation when time comes.

**Comment by ramiroaznar** [comment]
This is not happening anymore.

![image](https://user-images.githubusercontent.com/5215798/34719243-4a3b945e-f53a-11e7-98c0-f1ec4bc946f5.png)
