### ISSUE TITLE
Where to inject custom javascript?

### ISSUE THREAD

**Issue by milovanderlinden** [CartoDB/cartodb#11289]
### Context
I am trying to implement i18next.js so I can experiment with localization of the javascript components
 

### Steps to Reproduce
1. Loading i18next.js from CDN
2. Need a place to run the i18n  init
3. Don't understand how the application handles window.onload() or where and how I should position a function that needs to be started when the page is fully loaded

### Additional info
Any information you can give me regarding the starting sequence of the javascript in Carto will be highly appreciated.

**Comment by xavijam** [comment]
Hi @milonvanderlinden, we already use a library for internationalization in the javascript. It is [Polyglot.js](http://airbnb.io/polyglot.js/), by AirBnb. The locale file is placed in `/lib/assets/core/locale/en.json`. Hope it helps.

**Comment by milovanderlinden** [comment]
Ah great! I removed the CDN for i18next again and am now playing with the ACTIVE_LOCALE variable.

Thanks for getting me back on track!

**Comment by xavijam** [comment]
No problem, a pleasure!.
