### ISSUE TITLE
Title changes are not applied to HTML popup

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#11284]
### Context

* This issue come from SB BUILDER feedback.

### Steps to Reproduce

1. Create a map with `populated_places` dataset.
2. Add click or hover popup
3. Activate any field, change title
4. Open `HTML` panel

### Current Result

* Changes are not applied to the `HTML`

### Expected result

* Changes should be applied.

### Browser and version

* Google Chrome v54.

**Comment by Jesus89** [comment]
Closed by: https://github.com/CartoDB/cartodb/pull/14148

**Comment by Jesus89** [comment]
:rocket:
