### ISSUE TITLE
layer selector of published map does not display name of heatmap/torque layer

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartodb#11280]
### Context
If you create a map, style the layer with the aggregation option "pixel", enable the layer selector and publish the map. The name of the heatmap layer does not appear on the layer selector

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Create map
2. Style layer with aggregation option "pixel"
3. Enable layer selector
![screen shot 2017-01-17 at 15 33 25](https://cloud.githubusercontent.com/assets/11177693/22024446/51519894-dcca-11e6-83b2-cf0ecee7b2ed.png)

4- Publish the map

![screen shot 2017-01-17 at 15 33 18](https://cloud.githubusercontent.com/assets/11177693/22024449/54413cc6-dcca-11e6-902e-074ed9efad5d.png)

The same problem happens with the published map if we change the style to "animated".

![screen shot 2017-01-17 at 15 37 55](https://cloud.githubusercontent.com/assets/11177693/22024667/fb9d84e8-dcca-11e6-9442-6d2f25f8af02.png)

**Comment by saleiva** [comment]
Xavijam should we prioritize this?

**Comment by oriolbx** [comment]
Is there some update on this issue?

**Comment by xavijam** [comment]
Nothing new yet @oriolbx, sorry.

**Comment by saleiva** [comment]
Is this only failing with heatmaps?
As a pretty obvius bug I'd think on attacking this soon

**Comment by xavijam** [comment]
Checked that probably is a problem from layer presenter. Backend.
To be clear, this is not a regression problem.

**Comment by xavijam** [comment]
It is likely `layer_name` is not promoted in torque layers.

**Comment by javitonino** [comment]
Giving back to frontend. The thing is `layer_name` is not being used in any Layer presenter (it's not persisted). It is only used in the vizjson v2 (not v3), and is calculated as `options.table_name_alias || options.table_name`.

Given that the frontend already has logic for this in the layer model, it seems better to fix it there, although we could make the change in backend presenters if it turns out it is needed after all.

**Comment by javitonino** [comment]
Hold your horses! It seems it is used in vizjson3 after all, but only on non-torque layers. Will add it there and it should solve at least the issue in embeds. I will also test if it is needed for Builder to work.
