### ISSUE TITLE
If image is not selected in the category list, we should not add marker-file attribute in the generated cartocss code

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#11283]
![screen shot 2017-01-17 at 16 30 35](https://cloud.githubusercontent.com/assets/132146/22026910/6b15cbb2-dcd2-11e6-8796-7fe0b7f4e6ad.png)

**Comment by nobuti** [comment]
Ready for CR.

**Comment by ivanmalagon** [comment]
Deployed to production.
