### ISSUE TITLE
When you are in "advanced UI" and edit a widget the UI keeps advanced colors

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb#11307]
You have a dashboard with widgets, then you click the "advanced" switch in any panel (style, sql, infowindow, legend...)

![image](https://cloud.githubusercontent.com/assets/9017165/22115055/d4bebb7e-de6b-11e6-9e62-7c6f8679e927.png)

Then you go to a widget and click on its 3 dots and select the edit option

![image](https://cloud.githubusercontent.com/assets/9017165/22115069/edee67de-de6b-11e6-8f13-c44456a4d710.png)

You get something like this:

![image](https://cloud.githubusercontent.com/assets/9017165/22115079/fe5134b2-de6b-11e6-8482-ca07954d6a88.png)

And you can move around Builder and the UI stays that way

![image](https://cloud.githubusercontent.com/assets/9017165/22115125/32efb8b0-de6c-11e6-8494-68abd37c0d06.png)

Till you go back to the very same switch and disable the "advanced mode"

**Comment by ramiroaznar** [comment]
Fixed!
