### ISSUE TITLE
Validate in legends endpoint that it is not possible to have two legends of the same type per layer

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#11305]
We implemented in the frontend a logic for the legends per layer, and it is:

**"IT IS POSSIBLE TO HAVE TWO LEGENDS PER LAYER, BUT ONLY ONE PER TYPE"**

That means, there are two types of legends, by color and by size. Already "described" in the UI:

![screen shot 2017-01-19 at 16 40 10](https://cloud.githubusercontent.com/assets/132146/22113280/087d1812-de66-11e6-9fca-f439714bd366.png)

By color:
- ~None~.
- Category.
- Choropleth.
- Custom choropleth.
- Custom.

By size: 
- ~None~.
- Bubble.

So having that check, only one type of legend per layer, we could have this type of legend:

![screen shot 2017-01-19 at 16 42 30](https://cloud.githubusercontent.com/assets/132146/22113378/5b8924b0-de66-11e6-9354-42e14f0541eb.png)

IMHO, we should implement the same behaviour in the backend in order to preserve the logic in both places.

cc @CartoDB/builder-backend

**Comment by nobuti** [comment]
Just a thing, `none` is not a type.

**Comment by gfiorav** [comment]
@nobuti +1

It should be really easy to do, just adding validation. :)

**Comment by xavijam** [comment]
Thanks @nobuti :dancing_men:, edited.

**Comment by nobuti** [comment]
Added category and custom choropleth.
