### ISSUE TITLE
DO measures for points only show US and France

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb#11318]
If you add a DO analysis to a **points** node, you can only choose US or France

![image](https://cloud.githubusercontent.com/assets/9017165/22150126/b4712788-df17-11e6-9eec-3f282afda726.png)

And once there, you can only select a subset of all the available measures:

![image](https://cloud.githubusercontent.com/assets/9017165/22150153/d64e395e-df17-11e6-8065-1250bc98d68e.png)

![image](https://cloud.githubusercontent.com/assets/9017165/22150158/df589378-df17-11e6-835f-bdcd4d4abd68.png)

**This behavior doesn't affect polygon nodes.**

cc @ethervoid

**Comment by ethervoid** [comment]
Introduced by this change: https://github.com/CartoDB/cartodb/commit/735a89ca9613e0306eec42b75a2aaed7e510c19a#diff-01419ea49914454d67c389bff840cf96

Instead of pass empty string ('') we've to pass no arguments in case the geometry type is not a polygon

**Comment by ethervoid** [comment]
### Acceptance tests

0. Make sure you are testing in the **cloud staging** (rui1-rui2), with the **data observatory enabled** and **obs general quota credits** (10000 credits should be enough).
1. Create a new map in Builder with a points datasets and another with a polygons dataset (you could use data library for it)
2. Open the Chrome Dev tools and open the network tab
3. Add a data observatory analysis for the points dataset
4. Look for the following request url `Request URL:https://your_user.carto-staging.com/api/v2/sql?q=select%20*%20from%20obs_legacybuildermetadata()`
5. Verify in the obs_legacybuildermetadata() that there are no arguments
6. Repeat from step 3 for the polygon dataset and in the `request url` check that the `'sum'` parameter is sent
