### ISSUE TITLE
ArcGIS server connector fails to import because of missing id field

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#11317]
### Context

* This come from a SB ticket.

### Steps to Reproduce

1. New dataset
2. Select ArcGIS Server connector
3. Type this URL: https://api.cityofkingston.ca/gis/rest/services/Carto/CapitalProjects_Carto/MapServer/1
4. Submit
5. Connect dataset

### Current Result
 
* Importation fails. The import error log says: `Missing data: key not found: "objectIds"`.

### Expected result

* Dataset should be connected to CARTO.

### Browser and version

* Google Chrome v54

**Comment by rafatower** [comment]
mm, sounds familiar to me. @ethervoid could you please take a quick look to see if this is related to gdal/ogr or to any other open ticket?

**Comment by ethervoid** [comment]
The client has the Query capabilities disabled or not supported. To execute queries is mandatory for us in [order to get the `objectsids`](https://github.com/CartoDB/cartodb/blob/master/services/datasources/lib/datasources/url/arcgis.rb#L370) .

If you try to do a query to get the `objectsids` you get the following error:

```
{
  "error": {
    "code": 400,
    "message": "Requested operation is not supported by this service.",
    "details": [
      "The requested capability is not supported."
    ]
  }
}
```

and you should receive something like this:

```
{"objectIdFieldName":"OBJECTID","objectIds":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15...]}
```

My suggestion is to talk with the client and told them that we they have to open the Query operation

**Comment by rafatower** [comment]
We should add a ticket to provide a proper error message to the user, shouldn't we? Something like:
```ruby
    12345 => {
      title: 'ArcGIS server misconfiguration',
      what_about: 'We could not import your data from the ArcGIS server because we got a "not supported" error when trying to query the `obectids`. Please contact your ArcGIS server administrator.',
      source: ERROR_SOURCE_USER
    },
```

What do you think, @ethervoid ? is that an accurate message?

Also this may be dependent on the server version and I think the only thing we have in written is that we support 10.1 or above. Do we know what's the server version, @ramiroaznar ?

**Comment by ramiroaznar** [comment]
No idea. Let me check that with the user and/or investigating a little bit on that url.

**Comment by ethervoid** [comment]
Absolutely, we should improve our feedback about this. I'll put:

```
12345 => {
      title: 'ArcGIS server misconfiguration',
      what_about: 'We could not import your data from the ArcGIS server because your server doesn't support to execute queries. Please contact your ArcGIS server administrator.',
      source: ERROR_SOURCE_USER
    },
```

Server  version is 10.31 so I'm pretty sure they have the Queries option disabled

**Comment by rafatower** [comment]
I'd go for `'We could not import your data from the ArcGIS server because the server has the "execute queries capability" disabled. Please contact your ArcGIS server administrator.'` and have Christa review the copy.

I created the related ticket: https://github.com/CartoDB/cartodb/issues/11544
