### ISSUE TITLE
Design Recurly pay form

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#11310]
### Context

Up to now, we were using Recurly's own form to process the customers paying information. Since it's being deprecated, we need to design our own form for it. 

This is how the old one looked:

![screen shot 2017-01-19 at 18 08 50](https://cloud.githubusercontent.com/assets/4222826/22116943/645968c8-de72-11e6-8845-f8ab3b9dc87a.png)

We need to design a form with the same filed but with our own look and feel.

**Comment by saleiva** [comment]
How urgent is this?

**Comment by juanignaciosl** [comment]
It's not urgent, @saleiva . This comes from
