### ISSUE TITLE
Cleanup after downloader refactor hotfix

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#11313]
After merging https://github.com/CartoDB/cartodb/pull/11253, there was an issue with synchronizations which was hotfixed here: https://github.com/CartoDB/cartodb/pull/11312

Here is the relevant trace: https://rollbar.com/vizzuality/CartoDB/items/21579/
 
Now that the issue is fixed, we need to cleanup and make sure it doesn't repeat:
- [x] Check why no test failed, and write a test that would have failed.
- [x] Check the `attr_reader`s, they should not be needed.
- [x] This should have been caught in acceptance. Review our procedures to see what can be improved --> this will be taken into account in an internal meeting.

**Comment by javitonino** [comment]
So about the acceptance comment, I don't think this would have been easy to catch, unless we start making acceptance to check rollbar.

The code in question is updating metadata after the sync:
```
      def set_success_state_from(importer)
        log.append_and_store     '******** synchronization succeeded ********'
        self.log_trace      = importer.runner_log_trace
        self.state          = STATE_SUCCESS
        self.etag           = importer.etag
        self.checksum       = importer.checksum
        self.error_code     = nil
        self.error_message  = nil
        self.retried_times  = 0
        self.run_at         = Time.now + interval
        self.modified_at    = importer.last_modified
        geocode_table
      rescue => exception
        CartoDB::Logger.error(exception: exception,
                                message: 'Error updating state for sync table',
                                sync_id: self.id)
        self
      end
```

It failed in `etag`, so all metadat below that line was not updated. Also Automatic Geocoding was not run. But, as this method only sets the metadata, but it is saved in the caller, the sync actually worked and reported success.

We only broke automatic geocoding and some minor metadata, so not too bad 😅

**Comment by ivanmalagon** [comment]
Deployed to production
