### ISSUE TITLE
Update delete and downgrade account flow to better understand the reasons behind

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#11314]
### Context

In order to understand churn, we should be able to gather some info about why people are downgrading/deleting their account.

Design issue: https://github.com/CartoDB/design/issues/426

# Delete flow

This is the current flow for deleting an account:

![delete account - current flow](https://cloud.githubusercontent.com/assets/16247628/22105092/b67888f8-de42-11e6-9c72-62f7358d118a.png)

This is the new flow: 

![delete account - new flow proposal](https://cloud.githubusercontent.com/assets/16247628/22105096/bc254f5c-de42-11e6-9ab8-e9f234f634e5.png)

## First step (Settings page):

![settings](https://cloud.githubusercontent.com/assets/16247628/22105110/cd15aba4-de42-11e6-9454-79d44d3ec39b.png)

Changing the "Are you sure?" sentence for **"Please consider downgrading to a Personal account instead so you don’t lose all your work and data."**. And adapting the message to the type of account, so if you have an Enterprise account it will say "downgrade to Personal" and if you have a Personal account it'll say "downgrade to Free". 

## Second step (Delete account modal):

![delete account v3](https://cloud.githubusercontent.com/assets/16247628/22147237/fa20c56e-df07-11e6-818b-e70e6e7b0eea.png)
![delete account v3 - better tool selected](https://cloud.githubusercontent.com/assets/16247628/22147238/fa2934ce-df07-11e6-802f-faecb778c573.png)
![delete account v3 - other selected](https://cloud.githubusercontent.com/assets/16247628/22147236/fa1fcc7c-df07-11e6-9fef-6eeee313bef1.png)

## Third step (Confirmation page):

Instead of just sending the user to our homepage from the modal, let's add a confirmation page to notify the user that the account was successfully deleted. 

![confirmation](https://cloud.githubusercontent.com/assets/16247628/22105409/1d9465b0-de44-11e6-859a-c23dce3829dd.png)

# Downgrade

This is the current flow for downgrading an account:

![downgrade account - current flow](https://cloud.githubusercontent.com/assets/16247628/22110825/6b758c8c-de5d-11e6-82b6-9168a802ba1e.png)

This is the new flow: 

![downgrade account -new flow proposal](https://cloud.githubusercontent.com/assets/16247628/22110830/729bda2a-de5d-11e6-8e95-4800ec89b6de.png)

## First step (Settings page):

We're not changing this part (beyond at some point being able to update it so the table looks like the one on the /pricing page).

## Second step (Delete account modal): 

![downgrade account - step 3](https://cloud.githubusercontent.com/assets/16247628/22110898/b433a3e6-de5d-11e6-9ba8-9741f12931fa.png)

![downgrade account - step 3 1](https://cloud.githubusercontent.com/assets/16247628/22110897/b43106f4-de5d-11e6-87bd-137b4e66164e.png)

![downgrade account - step 3 2](https://cloud.githubusercontent.com/assets/16247628/22110896/b4265d62-de5d-11e6-97da-89e455a1b9ff.png)

## Third step (Confirmation page):

Instead of just sending the user to the dashboard from the modal, let's add a confirmation page to notify the user that the account was successfully downgraded. And, once they close that modal, it will take them back to the settings page in which they started the process.

![downgrading account](https://cloud.githubusercontent.com/assets/16247628/22111069/4661d5da-de5e-11e6-95cb-3dfae4407172.png)

![confirmation](https://cloud.githubusercontent.com/assets/16247628/22111068/4656a980-de5e-11e6-820c-18bef0a097e4.png)

![plans](https://cloud.githubusercontent.com/assets/16247628/22111284/19f5c5c8-de5f-11e6-900f-27423950de71.png)

**Comment by xavijam** [comment]
cc @juanignaciosl

**Comment by arianaescobar** [comment]
This is still valid. We might need to update it to remove every mention of the Free plan though.  

cc @alonsogarciapablo

**Comment by alonsogarciapablo** [comment]
Thanks @arianaescobar. It's indeed interesting. I wonder if we're already doing something like this via email. cc: @jorgesancha
