### ISSUE TITLE
call to action in shared dataset email is not visible

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#11323]
related: https://github.com/CartoDB/cartodb/issues/11320

![screen shot 2016-11-29 at 20 20 59](https://cloud.githubusercontent.com/assets/36676/22153234/c0972cd8-df26-11e6-8e76-4ad54f046738.png)
![screen shot 2016-11-29 at 20 21 22](https://cloud.githubusercontent.com/assets/36676/22153235/c0b24086-df26-11e6-835b-c3db0250c6a8.png)

/cc @CartoDB/design

**Comment by ramiroaznar** [comment]
I think this is fixed.
