### ISSUE TITLE
add layer/add widget share same button and can be confusing

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#11325]
### Context
in the editor panel I've started to add a new widget when trying to add a new layer, because I find it confusing they share the same button (see attached)

![screen shot 2016-12-07 at 11 55 28](https://cloud.githubusercontent.com/assets/36676/22153411/828d9ab6-df27-11e6-8d28-7c7cdfa91804.png)
![screen shot 2016-12-07 at 11 55 37](https://cloud.githubusercontent.com/assets/36676/22153412/82911452-df27-11e6-8499-4c854f7cdf15.png)
 

### Steps to Reproduce

1. go to builder panel in a map
2. click in widgets tab
3. click add

### Current Result
 start to add widgets

### Expected result
as I am used to click on the add button to add layers, I expect it to add layers, not widgets

### Additional info
I propose to add the buton *below* the navigation menu, as it can increase affordance and it can even stress the kind of element you are adding, we're already doing this for analysis, and upload (dashed line)

![screen shot 2016-12-07 at 15 07 47](https://cloud.githubusercontent.com/assets/36676/22153463/bef2bc02-df27-11e6-8602-5ad04ef1a22e.png)

![screen shot 2016-12-07 at 11 56 51](https://cloud.githubusercontent.com/assets/36676/22153460/b8ad42e0-df27-11e6-9ffd-568e85e0bbed.png)

it is the same interaction than adding a new layer in the old editor

finally I'd suggest setting an A/B test, and a user session with the two versions

/cc @CartoDB/design

**Comment by saleiva** [comment]
I have another Idea that I'd love to show you, give me some days!

**Comment by arianaescobar** [comment]
FYI, this is getting tackled here: https://github.com/CartoDB/design/issues/1071

**Comment by matallo** [comment]
I can't believe it `*___*`

**Comment by ramiroaznar** [comment]
Closing this!
