### ISSUE TITLE
organization owner: dropdowns in public profiles have wrong links

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#11322]
### Context
when logged in as organization owner, the links in the dropdown of an public profile are wrong
 

### Steps to Reproduce
1. log in as organization owner
1. go to any public profile

### Current Result
- the dropdown is different from those in organization view, and dashboard view (see attached)
- you can't go to organization page from public profile
- the link in the own public profile to the own public profile doesn't make much sense 
 

### Expected result
- the dropdown must be the same
- a link to the organization must appear in the dropdown
- maybe add links to dashboard in organization view

### Additional info

![screen shot 2016-11-29 at 20 09 29](https://cloud.githubusercontent.com/assets/36676/22153099/1fa67630-df26-11e6-89f9-eb419008eebb.png)
![screen shot 2016-11-29 at 20 09 43](https://cloud.githubusercontent.com/assets/36676/22153098/1fa62842-df26-11e6-9385-50712459208f.png)
![screen shot 2016-11-29 at 20 09 56](https://cloud.githubusercontent.com/assets/36676/22153100/1fa95620-df26-11e6-874a-f7f919a51c1b.png)

related: https://github.com/CartoDB/cartodb/issues/4400

/cc @CartoDB/design

**Comment by saleiva** [comment]
related with https://github.com/CartoDB/design/issues/467

**Comment by arianaescobar** [comment]
This is still valid but we'll define the design first here https://github.com/CartoDB/design/issues/467
