### ISSUE TITLE
marker icon in icon picker is colored but doesn't apply opacity

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#11326]
### Context
when applying a custom icon with an icon picker the icon is colored but the opacity is not changed
 

### Steps to Reproduce

1. go to a map and go to custom legend or custom marker 
2. select "IMG"
3. change color
4. change opacity

### Current Result
the color of the marker in the icon picker is fixed
 
### Expected result
the color of the marker in the icon picker hould have opacity

### Additional info

<img width="285" alt="screen shot 2017-01-05 at 18 40 09" src="https://cloud.githubusercontent.com/assets/36676/22154237/02fd7c90-df2b-11e6-999b-de3010a299f5.png">

feel free to reassign

**Comment by Jesus89** [comment]
@ramiroaznar ready to test: https://icon-color.carto-staging.com (icon-color123)

**Comment by Jesus89** [comment]
Closed by: https://github.com/CartoDB/cartodb/pull/14144

In production! :rocket:
