### ISSUE TITLE
Update org invite email layout

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#11320]
### Context
when receiving an invitation to an organization the call to action is below the fold in the popup window (gmail web client), also when scrolling I don't think the action is clear enough as it appears like the other links above.

![screen shot 2016-11-29 at 20 06 18](https://cloud.githubusercontent.com/assets/36676/22151183/3ff6e63a-df1d-11e6-828c-4549ae131ca3.png)
![screen shot 2016-11-29 at 20 06 57](https://cloud.githubusercontent.com/assets/36676/22151184/3fff5aae-df1d-11e6-8808-4d7f5fda07f1.png)
 

### Steps to Reproduce

1. create an organization
2. invite some user

### Current Result
link with CTA is below the fold
 

### Expected result
link with CTA to be clearly differenciated in the mail body, and above the fold
 

### Additional info
in order to better test this I'd add some tracking links for analytics

/cc @CartoDB/design

**Comment by arianaescobar** [comment]
moved it to design

**Comment by arianaescobar** [comment]
## New layout and styling 

![37668173-2049e82e-2c64-11e8-99f2-bea206104ddf](https://user-images.githubusercontent.com/16247628/37768331-7ce18cb2-2dcd-11e8-9ec4-a49437eebf6c.png)

## Properties

Logo:
```
width: 92px;
height: 36px;
```
[Logo.zip](https://github.com/CartoDB/cartodb/files/1837307/Logo.zip)

Title:
```
font-family: Montserrat-SemiBold;
font-size: 32px;
color: #2E3C43;
letter-spacing: 0;
line-height: 48px;
```

Body:
```
font-family: OpenSans-Regular;
font-size: 16px;
color: #2E3C43;
letter-spacing: 0;
line-height: 24px;
```

Links: 
```
font-family: OpenSans-Bold;
font-size: 16px;
color: #1785FB;
letter-spacing: 0;
line-height: 24px;
```

Button:
```
background: #1785FB;
border-radius: 4px;
```

Button text:
```
font-family: Montserrat-SemiBold;
font-size: 12px;
color: #FFFFFF;
letter-spacing: 1px;
line-height: 16px;
```

@javitonino let me know if you need anything else :)

**Comment by javitonino** [comment]
I'll pass this to frontend (cc @ivanmalagon), since finally there were really no backend changes (same content, just reordered it a bit).
