### ISSUE TITLE
There is no way to access DO normalized segments (percent values)

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb#11331]
At the DO catalog we have 4 values per segment:

![selection_010](https://cloud.githubusercontent.com/assets/9017165/22198476/f4d7c976-e156-11e6-841b-57fa9e6d9aee.png)

But there is no way to access those percent values from Builder, we miss a checkbox to retrieve "normalized" values

![selection_012](https://cloud.githubusercontent.com/assets/9017165/22198563/543711c4-e157-11e6-8e01-814279d9568f.png)

And they are not even listed in the combo, so selecting them as a different segment is not even possible
![selection_011](https://cloud.githubusercontent.com/assets/9017165/22198565/58679584-e157-11e6-9d3d-58f077c93709.png)

cc @ethervoid @talos

**Comment by noguerol** [comment]
From an UX perspective this would probably work better with the checkbox suggested by Abel @saleiva

**Comment by saleiva** [comment]
This UI is being completely redesigned including normalization. it's on the kanban ritgh now
