### ISSUE TITLE
Multiple columns on the Enrich from DO analysis and DO UI fixes

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#11333]
### Context

Allow for multiple selection of columns within the existing interface.  For example, if someone wants to obtain `Population`, `Male Population` and `Female Population` at the same time.

Design issue: https://github.com/CartoDB/design/issues/432

### Mockups

![analysis - enrich from data observatory 01](https://cloud.githubusercontent.com/assets/16247628/22242527/fb32a4bc-e223-11e6-9601-418c2dd7d0a4.png)
![analysis - enrich from data observatory 02](https://cloud.githubusercontent.com/assets/16247628/22242530/fb3570de-e223-11e6-8c15-e038d9ddfa3e.png)
![analysis - enrich from data observatory 03](https://cloud.githubusercontent.com/assets/16247628/22242528/fb32e026-e223-11e6-91e3-b62a35593e50.png)
![analysis - enrich from data observatory 04](https://cloud.githubusercontent.com/assets/16247628/22242529/fb34639c-e223-11e6-8ae5-4b2056f3f294.png)
![analysis - enrich from data observatory 05](https://cloud.githubusercontent.com/assets/16247628/22242531/fb38d058-e223-11e6-8ce9-5806739d2847.png)
![analysis - enrich from data observatory 06](https://cloud.githubusercontent.com/assets/16247628/22242532/fb3b78ee-e223-11e6-9677-ee9dcd405488.png)
![analysis - enrich from data observatory 07](https://cloud.githubusercontent.com/assets/16247628/22242533/fb478a94-e223-11e6-8a58-363d8e66808f.png)

The quota warning message appears once you have filled all the inputs:
![analysis - enrich from data observatory 08](https://cloud.githubusercontent.com/assets/16247628/22242534/fb483e30-e223-11e6-8b30-390683cf8f14.png)
![analysis - enrich from data observatory 09](https://cloud.githubusercontent.com/assets/16247628/22242535/fb4b6e66-e223-11e6-9b6c-eeb503e29fc4.png)

This is how it woud look before filling all the inputs:
![analysis - enrich from data observatory 10](https://cloud.githubusercontent.com/assets/16247628/22242536/fb50e5ee-e223-11e6-82c9-3e9c2485f03e.png)

**Comment by saleiva** [comment]
hey @talos we've prioritized the option without groups of measurements for phase 1, ok?

**Comment by AbelVM** [comment]
... I really love this upcoming DO UI... :heart_eyes:

**Comment by talos** [comment]
Yes!! ❤️ ❤️

**Comment by saleiva** [comment]
Be sure you check some of the implementation details on the design ticket

**Comment by saleiva** [comment]
Closing this since this is already being attacked!
