### ISSUE TITLE
Two time series widgets added when styling a layer by Torque

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#11339]
### Context

I styled a layer of tweets with Torque and it created two time-series widgets.

### Steps to Reproduce

1. Searched tweets from #womensmach and created a map with it 
2. Entered the only layer (with the tweets) who where styled as points and changed it to torque
3. It gave me an error, nothing showed on the map, and it created a time-series widget that didn't load a thing:

![1](https://cloud.githubusercontent.com/assets/16247628/22251228/4b5beb94-e24a-11e6-8ce6-96edb34f745a.png)

4. I refreshed the tab and the torque animation appeared on the map and a second time-series widget appeared but none showed data:

![2](https://cloud.githubusercontent.com/assets/16247628/22251244/5899487e-e24a-11e6-8ba7-f89207e56ff4.png)

5. I refreshed a second time and both widgets finally showed their data:

![3](https://cloud.githubusercontent.com/assets/16247628/22251308/91c1a894-e24a-11e6-8826-d579fb475775.png)

### Current Result

https://team.carto.com/u/arianaescobar/builder/20034d80-e221-11e6-ae82-0ef7f98ade21

### Expected result

Torque animation showing up and just one time-series added with loaded data once the style got switched to Torque without needing to refresh the tab. 

### Browser and version

Chrome Version 55.0.2883.95 (64-bit)

### .carto file

The .carto file is 46,5MB, I can't upload it here. If whoever is working on this needs it, let me know and I'll send it through slack or something.

**Comment by AbelVM** [comment]
I can confirm

**Comment by saleiva** [comment]
Adding to next since this is quite explicit

**Comment by nobuti** [comment]
Picking this.

**Comment by nobuti** [comment]
Ready for CR

**Comment by xavijam** [comment]
Thanks @nobuti for the fix 💋

**Comment by saleiva** [comment]
@arianaescobar check it!

**Comment by arianaescobar** [comment]
Works perfectly now 👌 ✨
