### ISSUE TITLE
Visualization of that user does not exist

### ISSUE THREAD

**Issue by SimonMuraya** [CartoDB/cartodb#11330]
**When i run this http://documentation.cartodb.com/api/v2/viz/4f131d46-d3d8-11e6-891f-0ee66e2c9693/viz.json i get the error below:**

*{"errors":"Visualization of that user does not exist"}*

**How can i fix this?**

**Comment by saleiva** [comment]
cc/ @csobier

**Comment by SimonMuraya** [comment]
**Solved it**

*the url has the username parameter "documentation" - http://{username}.cartodb.com/api/v2/viz/4f131d46-d3d8-11e6-891f-0ee66e2c9693/viz.json is supposed to be replaced by my cartodb account username*
