### ISSUE TITLE
.carto files fail on import

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#11334]
### Context

We've noticed some `.carto` files fail on import with `Unsupported/Unrecognized file type (1002)` error. 

This only happens when there are spaces or other special characters on the file's name. 

### Steps to Reproduce

1. Try and import this `.carto` file 
[populated places with spaces (on 2017-01-24 at 11.34.34).carto.zip](https://github.com/CartoDB/cartodb/files/726512/populated.places.with.spaces.on.2017-01-24.at.11.34.34.carto.zip)

2. It will fail with `Unsupported/Unrecognized file type (1002)`
3. Import this other `.carto` (is the same one, but renamed) 
[populatedplaces.carto.zip](https://github.com/CartoDB/cartodb/files/726514/populatedplaces.carto.zip)

### Current Result

Import of `.carto` files with spaces or `(` `_` characters fails

 As `.carto` files are generated with both spaces and parenthesis or their name, this bug makes them 'unusable' unless the user renames the file before importing. 

### Expected result

Default `.carto` file name shouldn't prevent the file from being imported.

**Comment by saleiva** [comment]
This should have an automated test asociated as well

**Comment by juanignaciosl** [comment]
On it
