### ISSUE TITLE
Change of bar fill color on Time series widget not getting reflected on the embedded map

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#11346]
### Context

I've changed the bar fill color of [this map](https://team.carto.com/u/arianaescobar/builder/7887d6f1-ab77-4e46-a096-0e3983e60abc/embed) to be pink and published the changes, but when I look at it from the /embed it displays the original orange color instead of the pink. 

### Steps to Reproduce

1. Create a map with [this dataset](https://team.carto.com/u/arianaescobar/tables/twitter_womensmarchhasgeo/public)  
2. Create a time-series widget with the postedtime column
3. Change fill color
4. Publish changes
5. Take a look at the embedded map 

### Current Result

<img width="1193" alt="screen shot 2017-01-25 at 11 54 07" src="https://cloud.githubusercontent.com/assets/16247628/22287915/002eab74-e2f5-11e6-8c7a-9aba75e29966.png">

https://team.carto.com/u/arianaescobar/builder/7887d6f1-ab77-4e46-a096-0e3983e60abc/embed

### Expected result

<img width="1232" alt="screen shot 2017-01-25 at 11 54 28" src="https://cloud.githubusercontent.com/assets/16247628/22287932/0f76ed6c-e2f5-11e6-828e-48d63c95b37b.png">

### Browser and version

Chrome Version 55.0.2883.95 (64-bit)

**Comment by xavijam** [comment]
It is working now after last changes with aggregations.
