### ISSUE TITLE
Add warning/info on privacy settings button for shared datasets

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartodb#11342]
### Context

My colleague shared a dataset with me that is set to 'private'. Another colleague wanted access, so i attempted to click "PRIVATE" (see img below) but the button was inactive. My first thought was that my mouse or browser were acting incorrectly, so I tried it in other browsers and same effect. Then I realized that I don't have access to change the permissions of the dataset since I am not the original owner.

<img width="316" alt="screen shot 2017-01-24 at 10 18 15" src="https://cloud.githubusercontent.com/assets/1041056/22253133/742faf78-e21e-11e6-9c58-52e914ac9639.png">

### Steps to Reproduce

1. Share a private dataset with a colleague
2. Ask the colleague to attempt to change the privacy settings
3. Colleague will not be able to do this (expected behavior).

### Current Result

The button is inactive (expected), but visually it looks no different than an active button.

### Expected result

Change the UI/UX so that it's obvious that changing permissions is not allowed for shared datasets when the user is not the owner.

What would be great is if the following happened instead:

1. A warning that you cannot change the permissions on a dataset owned by someone else
1. The privacy button that looks inactive

### Browser and version

Chrome 55.0
Safari 10.0.2

 

### .carto file

I don't think it's possible to share a .carto file that allows me to reproduce this.

 

### Additional info

Thanks!

**Comment by saleiva** [comment]
Super +1

Prioritizing it

**Comment by josecruz** [comment]
Hey what do you think about this tooltip?

Following Builder guidelines, the most natural solution was showing a tooltip from the deactivated tag:
![image](https://cloud.githubusercontent.com/assets/596509/22294166/86931a3e-e312-11e6-86bd-7b4c44f0a7d6.png)

**Comment by ohasselblad** [comment]
Looks good! What about including the owner name in that tooltip?
"You're not able to change the privacy of this dataset. Contact the owner '{ownername}'."

**Comment by josecruz** [comment]
Totally agree @ohasselblad! Doing that we're opening one path for the user instead of letting it totally blocked. Thanks for pointing that out. 

Would you put the email that they used to sign up in CARTO?

**Comment by ohasselblad** [comment]
Including the email sounds good, but would they be able to copy & paste the email from the tooltip? What about clicking the button copies the email of the owner to the clipboard?

**Comment by josecruz** [comment]
I like the idea you're suggesting but I don't think that clicking and copying the email is the expected behaviour when clicking the inactive button. So, I would just show the email or username of the owner.

![image](https://cloud.githubusercontent.com/assets/596509/22295535/9007bd68-e317-11e6-86b5-b100e7a059bb.png)
Honestly I would use the CARTO username of the owner to avoid exposing any emails, does that makes sense?

**Comment by ohasselblad** [comment]
Agree, looks great like that :)

**Comment by saleiva** [comment]
Like! !

**Comment by noguerol** [comment]
Smart solution. When solved I would expand the scope in the future a little bit: https://github.com/CartoDB/design/issues/509

**Comment by xavijam** [comment]
_Using this ticket for hiring_

**Comment by rubenmoya** [comment]
In production 🚀 !

**Comment by andy-esch** [comment]
Looks great!! :)

Just realized that there are share settings in the shared dataset dashboard that could be similarly confusing since the share buttons act differently between shared and non-shared datasets:
![privacy-shared](https://user-images.githubusercontent.com/1041056/29829772-46d1a2bc-8cae-11e7-8881-2aa8ef5031b7.gif)

**Comment by noguerol** [comment]
Thats probably because we don't have to put any label on the "shared with you" datasets.

**Comment by andy-esch** [comment]
There might still be value in showing the privacy settings. For example, knowing whether a user can do authenticated SQL API calls against a dataset or not.

**Comment by noguerol** [comment]
But then it makes no sense to change anything, right? There is no need for a modal window in other's tables.
