### ISSUE TITLE
Legend doesn't appear with custom CartoCSS

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#11349]
### Context
when applying custom CartoCSS code to a layer, the legend isn't automatically generated, even if a `ramp()` function is used. 
 

### Steps to Reproduce
1. Create a new map with one layer 
2. Use the slider in _STYLE_ tab to switch to _CARTOCSS_
3. Apply the following: 
  ```
  #layer {
  marker-width: 7;
  marker-fill: ramp([pop_min], (#ffc6c4, #ee919b, #cc607d, #9e3963, #672044), quantiles);
  marker-fill-opacity: 1;
  marker-allow-overlap: true;
  marker-line-width: 1;
  marker-line-color: #FFF;
  marker-line-opacity: 1;
  }
  ```
### Current Result
Legend is not produced

 

### Expected result
Legend should appear when a `ramp()` function is used

### .carto file
[Untitled Map 1 (on 2017-01-25 at 13.09.21).carto.zip](https://github.com/CartoDB/cartodb/files/729743/Untitled.Map.1.on.2017-01-25.at.13.09.21.carto.zip)

**Comment by xavijam** [comment]
Yes, it is already reported by @ramiroaznar in https://github.com/CartoDB/cartodb-management/issues/4809.

**Comment by xavijam** [comment]
And the main comment is here -> https://github.com/CartoDB/cartodb-management/issues/4809#issuecomment-274051504.

**Comment by xavijam** [comment]
Let me close it due to there is another one.

**Comment by maxhartshorn** [comment]
@xavijam Can you please provide an update here? Both of those links are 404ing for me. As far as I can tell there is no way to add a legend after applying a custom ramp function via CartoCSS
