### ISSUE TITLE
Organization settings tab links URLs are wrong

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#11343]
![captura de pantalla 2017-01-25 a las 11 02 52](https://cloud.githubusercontent.com/assets/932968/22285965/ebef61e6-e2ed-11e6-8a0c-170eddd282f3.png)

These links have this pattern: 

http://organization-admin.localhost.lan:3000/organization/auth

Nevertheless, it should be

http://organization.localhost.lan:3000/u/organization-admin/organization/auth

**Comment by ivanmalagon** [comment]
Passed acceptance.

- [x] Tabs inside organizations setting
- [x] Org user management: link to go back from the new user screen
- [x] Org user management: link to go back from the edit user screen
- [x] Mobile apps: link to go back from the new app screen
- [x] Mobile apps: link to go back from the edit app screen
- [x] Mobile apps: link to go from the app list to an app details

**Comment by ivanmalagon** [comment]
Deployed. :1st_place_medal:
