### ISSUE TITLE
Time Series widget showing wrong "tick" data

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#11345]
### Context

I have [this map with tweets](https://team.carto.com/u/arianaescobar/builder/7887d6f1-ab77-4e46-a096-0e3983e60abc/embed) with a time series widget showing the `postedtime` column of the tweets dataset but the "ticks" of the horizontal axis are all showing "1.5G" instead of something related to the data or time.   

### Steps to Reproduce

1. Create a map with [this dataset](https://team.carto.com/u/arianaescobar/tables/twitter_womensmarchhasgeo/public)  
2. Create a time-series widget with the postedtime column

### Current Result

<img width="1235" alt="screen shot 2017-01-25 at 11 49 20" src="https://cloud.githubusercontent.com/assets/16247628/22287767/569e2fb2-e2f4-11e6-967b-3e977189dd04.png">

https://team.carto.com/u/arianaescobar/builder/7887d6f1-ab77-4e46-a096-0e3983e60abc/embed

### Expected result

The ticks of the horizontal axis should show time of day or the date or both. 

### Browser and version

Chrome Version 55.0.2883.95 (64-bit)

**Comment by javisantana** [comment]
map is gone, could you share it again?

**Comment by arianaescobar** [comment]
Oh, looks like I deleted it :( 

You could recreate it with the steps to reproduce and the dataset I linked in my original comment tho...

**Comment by xavijam** [comment]
Fixed a tope thanks to [aggregations](https://github.com/CartoDB/cartodb/issues/12347) release 💃 .
