### ISSUE TITLE
Array column type in dataset is not correctly parsed

### ISSUE THREAD

**Issue by MariaCheca** [CartoDB/cartodb#11348]
This issue is related to https://github.com/CartoDB/cartodb/issues/11328

Looks like the application returns a different data structure depending on what column is being updated, and that the column type with an array/matrix is not parsed properly.

### Steps to reproduce
0. Use Builder.
1. Upload a dataset with a `number[]` column type, or any type that implies an array or matrix (i.e. https://data.rennesmetropole.fr/explore/dataset/topologie-des-stations-le-velo-star0/download?format=geojson&timezone=Europe/Berlin&use_labels_for_header=true).
2. Go to the dataset editor view and try to edit that column. It will return an error message:
```
row identified with 1 not found
```
This is what the request sends:
![screen shot 2017-01-25 at 13 35 10](https://cloud.githubusercontent.com/assets/2141690/22290805/3b26c85c-e303-11e6-99e1-4368996453af.png)

3. Now try to edit another column. It will return an error like this one:
```
Error editing adressevoie with cartodb_id 1: PG::Error: ERROR: column "coordonnees" is of type double precision[] but expression is of type record
```
The request now sends:
![screen shot 2017-01-25 at 13 37 24](https://cloud.githubusercontent.com/assets/2141690/22290852/7ac35070-e303-11e6-8c65-62031abd6698.png)

cc @javitonino @xavijam

**Comment by javitonino** [comment]
Just to complement the description, the correct format is probably the array as that is what is returned by both SQL API and the records controller. However, the records controller only takes as an input things between brackets like `{123,456}`, but it then returns an array.

The direct solution would imply changes in front (consistent behaviour that does not depend on which column are you editing) and backend (to ensure it accepts the same format as it returns).

Alternatively, we could start thinking about phasing out the use of records controller, and have the dataset view work directly against the SQL API for write operations.
