### ISSUE TITLE
Improve affordance of layer item

### ISSUE THREAD

**Issue by urbanphes** [CartoDB/cartodb#11359]
### Context
Related to https://github.com/CartoDB/design/issues/473
_(This feature has been worked on CartoDB/design)_

- [x] Update clckeable areas
- [x] Add "Edit layer" item to the contextual menu which basically enters to the layer panel (like clicking on the title)
- [x] Be sure we propagate this to the basemaps layer

**Comment by saleiva** [comment]
Take basemaps layer in consideration as well.

**Comment by matallo** [comment]
already advancing on this, when referring to table view, which of the options below do you mean?

![452737b2-f687-49c1-8ec5-e4cfc8c04839](https://cloud.githubusercontent.com/assets/36676/22927753/5250f1e6-f2b3-11e6-9dc7-92ca36837913.png)
![d2d1fcc9-ca58-4e7e-a981-5a23a00758d2](https://cloud.githubusercontent.com/assets/36676/22927754/52554d9a-f2b3-11e6-9037-5656943b35b6.png)

**Comment by matallo** [comment]
another case I stumbled upon, when the layer has several analyses indeed (see attached)

![screen shot 2017-02-14 at 12 48 22](https://cloud.githubusercontent.com/assets/36676/22927908/f717bc50-f2b3-11e6-9707-7c4a19fddb8c.png)

isn't it redundant to prompt the number of analyses when they appear below (I can see there are two analyses there) just to confirm before moving on

**Comment by saleiva** [comment]
That's an open question but having that there also helps to show that we have analysis. I promise we will revisit this soon. For the time being I'd keep going! 💪

**Comment by matallo** [comment]
sure! already pushed the changes, and made the tests pass, I still have the question about the table view

finally, I'd give some love to the drop icon, will ping somebody from design for this, this is the current status

![screen shot 2017-02-14 at 16 50 06](https://cloud.githubusercontent.com/assets/36676/22937994/9fb86d16-f2da-11e6-8d2d-50ab557ea284.png)

if there is no geom to style the icon won't appear

**Comment by xavijam** [comment]
I'd go to the dataset url view...

**Comment by saleiva** [comment]
reopenning since we've noticed today that point 2 and 3 are still missing.

**Comment by jorgesancha** [comment]
How come we missed this in acceptance, team?

**Comment by xavijam** [comment]
That's a good one, because there is a long thread about it...
https://github.com/CartoDB/cartodb/pull/11534

**Comment by matallo** [comment]
oop I must have missed it as I focused too much in the image captures ><

anyways, I added the edit layer option, and the basemap title underline when hovering the block

**Comment by xavijam** [comment]
By the way, I remember that analyses items (in layers list) should not have grey background, right @saleiva or @urbanphes?

**Comment by xavijam** [comment]
Deployed!
