### ISSUE TITLE
Allow possibility to modify opacity *per color* when styling by value

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#11354]
### Context
right now there's only the possibility to change opacity when being a fixed color, or *per scale*, Ideally I would like to modify each color of the scale so it has its own opacity

the UI is ready for this change

### Steps to Reproduce

1. have a map with a layer of points
1. click style
1. style by value
1. choose a column
1. click on a value/color

### Current Result
opacity is disabled and it's not possible to change opacity for current color

### Expected result
change opacity for current color

### Additional info

![screen shot 2017-01-25 at 17 23 20](https://cloud.githubusercontent.com/assets/36676/22300731/af718768-e328-11e6-9aa4-e0ab8f5b57bf.png)

ps: the cartocss allows this

![screen shot 2017-01-25 at 18 08 47](https://cloud.githubusercontent.com/assets/36676/22301038/cc0596ac-e329-11e6-9511-ad6ec0e59aff.png)

/cc @CartoDB/design

**Comment by xavijam** [comment]
What about moving this ticket to the design repo?

**Comment by matallo** [comment]
actually it's already designed, we just need to implement the opacity slider as it is above

**Comment by michellechandra** [comment]
S/B: 13138235

Is there an update on this issue?

**Comment by saleiva** [comment]
IMO, response teaam!

**Comment by alrocar** [comment]
Stale issue. Closing 👋
