### ISSUE TITLE
Autostyle throws an error when the cartocss has rules for the incorrect geometry type

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#11363]
Discovered during acceptance of https://github.com/CartoDB/deep-insights.js/pull/514

### Steps to Reproduce
1. Create a point map
2. Apply an style for a polygon (you see where this is going). For example: `#layer { polygon-fill: #FFB927; }`
3. Add an histogram widget
4. Click autostyle

### Current Result
:boom: goes the dynamite 

### Expected result
It doesn't break

cc @xavijam

**Comment by xavijam** [comment]
This is not 💥  anymore 💃 .
