### ISSUE TITLE
Update organization icons modal copy

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#11360]
### Context
When deleting organization icons in `Your organization` dashboard area, we display a modal dialog warning the user of the outcomes of that operation.

After reviewed, the copy need to be changed to:

```
You are deleting 4 icons from your organization.
Once icons are deleted they cannot be recovered. Any maps within the organization that use these icons will be adversely affected. Please be sure before proceeding.
```

Just for the record, the current wrong copy is:

![modal](https://cloud.githubusercontent.com/assets/1078228/22292023/a335f368-e309-11e6-9833-6a4ef9686b62.png)

**Comment by saleiva** [comment]
hey @brittanymicek can you take a look at this?

**Comment by ivanmalagon** [comment]
@saleiva This issue was opened because @brittanymicek already checked the previous copy, the one in the screenshot. The proposed text is the one that she wrote.

**Comment by saleiva** [comment]
Ossom, sorry !

**Comment by ivanmalagon** [comment]
Deployed to production
