### ISSUE TITLE
analysis node persists in template after deletion in map

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#11368]
### Context
This error was reported by a user who has been giving us very good pieces of feedback. 

SB/10304841

The user sent us a `.carto` file that reproduces the error (see the link at the end of the issue)
 

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Import `.carto` file
2. Publish the map
3. Open embed map
4. See errors on map instantiation: 

![screen shot 2017-01-26 at 17 18 44](https://cloud.githubusercontent.com/assets/10940006/22339803/861ad7de-e3eb-11e6-8f74-a78813583ab7.png)

5. If you open [the named map template](https://github.com/CartoDB/cartodb/files/732817/template.json.zip) you'd see there is an `e0` node that is causing the error, although the node is not present on the map. 

```
{"id":"e0","type":"source","params":{"query":"SELECT * FROM s_bahn_brandenburg_1"}}
```

### Current Result

* Reference to an inexistent node is present on the named map template, although not on the map within Builder interface. The embed map is generated using the named map template and it fails, due to the table not existing

* `.carto` export does not include the node/dataset, but the named map template keeps it, even after trying to invalidate/regenerate it
 

### Expected result

* named map template should not keep reference of removed nodes
 

### .carto file
[utf-8__barrierefreie_Bahnh_fe_in_Berlin__on_2017-01-24_at_09.34.22_.carto.zip](https://github.com/CartoDB/cartodb/files/732813/utf-8__barrierefreie_Bahnh_fe_in_Berlin__on_2017-01-24_at_09.34.22_.carto.zip)

 

### Additional info

Please let me know if this is not clear enough and we can review it quickly

**Comment by xavijam** [comment]
That's a good one, it reminds me the problem that @gfiorav tried to solved once but @CartoDB/builder-backend agreed that it was a frontend problem and the PR was closed (not merged).

**Comment by juanignaciosl** [comment]
@xavijam assign Backend tag and prioritize if you think that it might not be a backend issue.

**Comment by ernesmb** [comment]
Issue moved to [CartoDB/cartodb-management #4823](https://github.com/CartoDB/cartodb-management/issues/4823) via [**ZenHub**](https://www.zenhub.com/)
