### ISSUE TITLE
Cannot select columns on merge analysis of two concrete tables

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#11369]
### Context
Discovered during acceptance of https://github.com/CartoDB/cartodb/pull/11367 

### Steps to Reproduce
1. Import "Railsroads of the world" and "US States in 1860"
2. Create a map using the railroads dataset
3. Add a merge analysis, select US States 1860 as the second table

### Current Result
![screenshot_20170126_175839](https://cloud.githubusercontent.com/assets/7569673/22341439/1996f22c-e3f1-11e6-8018-44396733eb25.png)

### Expected result
It works.

### Browser and version
Firefox Linux

**Comment by javitonino** [comment]
This is still happening:

![screenshot_20180220_095113](https://user-images.githubusercontent.com/7569673/36414799-d5d15b02-1623-11e8-9b0c-fb7e3de2a2e6.png)

However, after reproducing it again, it seems the problem is that the query to obtain the column listing is slow and can time out. The problem is that it retrieves all rows (with heavy geometries), when it just needs to get the header. Adding `LIMIT 0` here could be a solution.

cc @ivanmalagon @ramiroaznar It's should be an easy fix to improves performance, so maybe worth it.

**Comment by ramiroaznar** [comment]
Good catch!

**Comment by ramiroaznar** [comment]
@rubenmoya LGTM!

**Comment by rubenmoya** [comment]
In production! 🚀
