### ISSUE TITLE
TurboCARTO error while editing widget

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#11365]
### Context

This error appear when we try to edit some widget properties and this widget has autostyle activated

### Steps to Reproduce

1. Use [this dataset](https://github.com/CartoDB/cartodb/files/732593/dummy_dataset_0.csv.zip) to create a map 
2. From _DATA_ tab, use the checkbox to add a widget on column `c`
3. Click the droplet to enable autostyle on the widget, see the two points style accordingly
4. Pan/zoom the map to a region where there are NO features, the widget should be empty
5. Click on _EDIT_ to open widget options
6. Click on _PREFIX_ checkbox
7. This message appears: 
  
  ```
  dummy_dataset_0: style0:1:70 Invalid value for marker-fill, the type color is expected. 
  undefined (of type keyword) was given.
  ```
8. Go to _STYLE_ tab and switch to _CARTOCSS_
9. See the `ramp()` function, it's missing two arguments. 

  ```
   #layer ['mapnik::geometry_type'=1] { marker-fill: ramp([c], (), ());  }
  ```

### Current Result

- `ramp()` function is not correctly generated
- could this be related to the widget not knowing the actual data range (as there are no features in sight?) 
 

### Expected result

- `ramp()` function should be called with parameters
- or maybe autostyle be disabled when there are no features in the map view? 

cc/ @josecruz

**Comment by xavijam** [comment]
Yeah, that's the problem, there is no range, so it can't calculate the colors.

**Comment by xavijam** [comment]
In fact, if you move the map and there is no points, the autostyle button disappears...

**Comment by ernesmb** [comment]
so the bug is that the style is not reset after losing sight of features?

**Comment by xavijam** [comment]
No, the bug is we should not let the user edit anything when the autostyle is applied. If not, when a new change is made over the widget, it is refreshed (data, colors, style, etc) and it could fail. There are two possibilities, or not allow edit the widget or disable autostyle when something is edited.
What do you think @saleiva?

**Comment by saleiva** [comment]
I think we should be a bit "smarter" here. Why cannot we enable editing of widgets? Widget should be edited when auto-style (imagine changing the ramp it applies).

I don't think adding a prefix should break things
