### ISSUE TITLE
Support for annotations/overlays in Builder

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#11374]
> Maps with annotations/overlays (titles, text, annotations....) will import. Those overlays will appear in the v2.0 map, though they will not be editable or moveable, so not the best case.

This is a current limitation of Builder. In addition, there might be risk of losing the annotations/overlays if you edit the map, as it's not supported (but I'm just guessing).

**Comment by juanignaciosl** [comment]
Not supported yet.

**Comment by noguerol** [comment]
@juanignaciosl I removed this from the milestone, so we can have a clearer picture of what's to be done
