### ISSUE TITLE
Heatmaps imported with .carto files won't render

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#11376]
> Maps using the heatmap style wizard import, and the cartocss is there, but the map is not rendered.

**Comment by juanignaciosl** [comment]
Not supported yet.

**Comment by xavijam** [comment]
Hey, we support it, old heatmap wizard is now the pixel one:

- Old one, in the editor:

![screen shot 2017-02-01 at 12 23 02](https://cloud.githubusercontent.com/assets/132146/22504965/32d86ba8-e879-11e6-8f58-b89a670727a0.png)


- New one, in BUILDER:

![screen shot 2017-02-01 at 12 23 22](https://cloud.githubusercontent.com/assets/132146/22504978/3dfb014e-e879-11e6-9f42-38335664546b.png)


We just need to set the proper ramp (because the default one has changed), and done.

**Comment by gfiorav** [comment]
I think I can infer the context and str from the description, but if you find the time, please update it to reflect more info :)

**Comment by andrewbt** [comment]
@gfiorav STR:

1. Make a map with a point dataset in Editor / Onpremise 1.3 and apply the "heatmap" wizard
2. Export that map as a .carto file
3. Import said .carto file into Builder / Onpremise 2.0. Observe rendering problems that appear.

**Comment by juanignaciosl** [comment]
@andrewbt Thanks for the STR :-) Could you please attach some screenshots?

I've made a quick test in master, enabling and disabling Builder, and it looks ok. So, maybe the problem is not the migration itself.

<img width="899" alt="captura de pantalla 2017-02-02 a las 10 39 54" src="https://cloud.githubusercontent.com/assets/932968/22544227/2f75ede4-e934-11e6-8275-11b19a045f4c.png">

<img width="1132" alt="captura de pantalla 2017-02-02 a las 10 40 21" src="https://cloud.githubusercontent.com/assets/932968/22544233/327c98ee-e934-11e6-9bbd-760c807bf50b.png">

**Comment by javitonino** [comment]
1.3.0
![screenshot_20170202_164514](https://cloud.githubusercontent.com/assets/7569673/22556902/fae87e04-e968-11e6-954c-e5aaaaca181b.png)
[[1.3] Heatmap (on 2017-02-02 at 15.45.51).zip](https://github.com/CartoDB/cartodb/files/748252/1.3.Heatmap.on.2017-02-02.at.15.45.51.zip)

2.0.0
![screenshot_20170202_164935](https://cloud.githubusercontent.com/assets/7569673/22556899/f7fbc2be-e968-11e6-9311-c3d98a4a8361.png)

**Comment by juanignaciosl** [comment]
@andrewbt could you review this and tell us what you think, please? Unless we can actually reproduce it we should close this.

**Comment by javierarce** [comment]
Sorry for adding noise, I just wanted to mention that the selection of labels for this particular issue is on fleek:

![screen shot 2017-02-09 at 10 28 34](https://cloud.githubusercontent.com/assets/4933/22777131/8f776c08-eeb2-11e6-9e4c-029a5e57605a.png)

**Comment by juanignaciosl** [comment]
:D

Closing this because it wasn't reproducible.
