### ISSUE TITLE
Importing Torque layers with .carto files has some errors

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#11378]
> Torque layers seem to import OK, but they do not render successfully in v2.0, and the "timeseries widget" is broken - fixated on the first bin and will not animate. Torque Category layers import the CartoCSS and legends OK, but have the same problems with rendering and the timeseries widget.

**Comment by javitonino** [comment]
Everything looks to me. Maps render fine and the timeseries widget works perfectly.

Torque animated 1.3.0
![screenshot_20170203_114444](https://cloud.githubusercontent.com/assets/7569673/22588953/41b4f8a4-ea08-11e6-9d31-6fa29aaa7940.png)
[[1.3] Torque animated (on 2017-02-03 at 10.42.18).zip](https://github.com/CartoDB/cartodb/files/750225/1.3.Torque.animated.on.2017-02-03.at.10.42.18.zip)


2.0.0
![screenshot_20170203_114835](https://cloud.githubusercontent.com/assets/7569673/22588964/52f519e6-ea08-11e6-9f97-0f81bb40357f.png)


Torque cat 1.3.0
![screenshot_20170203_114428](https://cloud.githubusercontent.com/assets/7569673/22588969/59048a6a-ea08-11e6-9337-7f94c3acb397.png)
[[1.3] Torque cat (on 2017-02-03 at 10.43.52).zip](https://github.com/CartoDB/cartodb/files/750227/1.3.Torque.cat.on.2017-02-03.at.10.43.52.zip)


2.0.0
![screenshot_20170203_114855](https://cloud.githubusercontent.com/assets/7569673/22588973/5e1f8edc-ea08-11e6-9e08-b81a471f01a1.png)

@andrewbt Any suggestion on how to reproduce this?

**Comment by juanignaciosl** [comment]
@andrewbt could you review this and tell us what you think, please? Unless we can actually reproduce it we should close this.

**Comment by juanignaciosl** [comment]
Closing this because it wasn't reproducible.
