### ISSUE TITLE
Legend migrator should remove `url(` from icon legends

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#11371]
### Context
From investigation of https://github.com/CartoDB/cartodb-management/issues/4815#event-939084200

If you migrate an editor map with icon legend to Builder, the legends will not render correctly. The migrated version sets `"icon": "url(http......)", and Builder expects `"icon": "http...."`. This behaviour changed here: https://github.com/CartoDB/cartodb.js/commit/1a01cbe0cc73c01ed45357449be56d8b558de1c4#diff-30d6f484d6f47d6e1d8ba3ea13211260

### Steps to Reproduce
1. Create a map in editor
2. Style by icons
3. Add a legend
4. Migrate to Builder

### Current Result
Icons in legend do not load. It tries to load an incorrect URl including `url(` as part of the URL 

### Expected result
The legend renders

### Additional info
The migration code is around here: https://github.com/CartoDB/cartodb/blob/b4bb9e41e3e6692c37bddc2dfb1fa537ff749fb3/lib/carto/legend_migrator.rb#L73

We should also write a script to fix affected maps in production. Maybe use `MapcappedVisualizationUpdater`.

cc @xavijam

@matallo has asked to take this one if possible.

**Comment by matallo** [comment]
on hold waiting for https://github.com/CartoDB/cartodb.js/pull/1562

**Comment by xavijam** [comment]
CartoDB.js thing checked, tested and approved.

**Comment by gfiorav** [comment]
Closed via https://github.com/CartoDB/cartodb/issues/11391
