### ISSUE TITLE
Deleting a dataset does delete the layer but not the analyses [LOOK AT PR#11422 ONLY] [DEPLOY ON MONDAY]

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#11381]
### Context
When deleting a dataset, layers from related maps are deleted. However, analyses are not. When sending the named map, all analyses (including not-referenced ones) are sent to the tiler, so it results in a map instantiation error. 

### Steps to Reproduce
1. Create map
2. Add a second layer from a different dataset
3. Publish and check the embed works
4. Delete one of the datasets
5. Republish the map and go to the embed

### Current Result
Map instantiation error. The dataset does not exist. This is caused because the analyses node was not deleted (although it is not used). 

### Expected result
It works.

### .carto file
See https://github.com/CartoDB/cartodb-management/issues/4823 

### Additional info
Two approaches here:
 - Delete the related analysis nodes when deleting a dataset
 - Do not send unreferenced nodes to the tiler

cc @juanignaciosl

**Comment by juanignaciosl** [comment]
I'd try the delete approach as long as there are guarantees that it won't break anything.

**Comment by javitonino** [comment]
Note that the deletion thing needs to be pretty smart, i.e: implement the deleteLayer action for frontend, that can imply renaming analysis, moving analysis node "ownership" from layer to layer, etc. It's not going to be easy.

This could be pretty nice as a first step towards moving user actions to the backend though, but I suggest we have a little discussion with frontend to understand how this works before starting to work on it.

**Comment by javierarce** [comment]
Deployed and tested in production. It seems to work fine.
