### ISSUE TITLE
Ability to optionally exporting/importing ids at .carto files

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#11387]
.carto currently doesn't export or import ids. Doing it can be interesting for migrations, so known URLs doesn't change. Consider exporting/importing every id or only those that are used in public URLs (vizjson, for example).

Exporting/importing should be optional, and it can't be enabled in the SaaS (raise a 400 error, as it's not a valid request).

**Comment by gfiorav** [comment]
I have mixed feeling about this!

If you're migrating an account, should you really expect ids to have stayed the same? I fear that adding this to the format is adding complexity that only a 1% will use. Maybe we get some mischief going on with it as well.

**Comment by juanignaciosl** [comment]
@danicarrion , @javisantana , do you think that keeping ids is needed? Within the SaaS it's certainly not, but for onpremises and OS it depends on the amount of development effort on top of CARTO instances.

The main concern would be the vizjson URL. Maybe we could export only that id.

Maybe for the future we should provide a mechanism for permanent URLs.

**Comment by juanignaciosl** [comment]
Closing as won't fix, as this makes no sense for SaaS.

**Comment by javisantana** [comment]
About the viz.json urls: if you are moving visualizations around the viz.json url is going to change anyway so I don't see that as a big problem. 

Agree on closing

**Comment by danicarrion** [comment]
URLs may not change onprem if they keep the same hostname

**Comment by juanignaciosl** [comment]
@danicarrion currently the id change would break the URL, but it's something that is not useful for the SaaS. Is it ok for now, or should this be addressed? Currently there's no API that would allow you to keep the URL.

**Comment by danicarrion** [comment]
It's hard to say, at this moment. This basically impacts people who want to migrate (onprem) cartodb.js apps to the new (onprem) carto.js, but that's not going to happen any time soon, so I don't really know what to answer.

**Comment by javisantana** [comment]
but if they migrate visualizations they will need to redo their carto.js applications so changing an id (or an url) is not big deal, right?

**Comment by andrewbt** [comment]
@javisantana that's a good point.

I bet some Onprem cartodb.js users are probably using self-written MapConfig objects into the apps rather than viz.json's, too, so the ID wouldn't matter in that case either.

**Comment by juanignaciosl** [comment]
Good to know. Let's keep this out of the milestone then. If a use case needing this appears, we'll address it.
