### ISSUE TITLE
link to vimeo videos cartodb channel needs fixing

### ISSUE THREAD

**Issue by rsignell-usgs** [CartoDB/cartodb#11393]
The link to the Vimeo cartodb channel (http://www.vimeo.com/channels/cartodb) in the [Readme.md](https://github.com/CartoDB/cartodb/blob/master/README.md) doesn't work.  

Is one of these the correct link?
https://vimeo.com/search/channel?q=cartodb

**Comment by ohasselblad** [comment]
@rsignell-usgs, since we did the name change, our channel is now here:
http://www.vimeo.com/channels/carto

**Comment by andy-esch** [comment]
Looks like this was fixed: https://github.com/CartoDB/cartodb/blob/master/README.md
