### ISSUE TITLE
Remove all auto-style feature flag logic

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#11392]
After opening all auto-style stuff for everybody, we should remove all traces about user feature flag, logic, and so on. Those changes will be needed in Deep-Insights and in Builder.

cc @nobuti

**Comment by ivanmalagon** [comment]
Deployed to production.

**Comment by xavijam** [comment]
We have to remove the feature flag, so let's leave this ticket in deploy please :kiss:

**Comment by javitonino** [comment]
Feature flag deleted, closing and moving to done.

**Comment by juanignaciosl** [comment]
Reopened: embeds still use it. The FF check is done by backend and written to the embed code as the autoStyle variable.

**Comment by xavijam** [comment]
Totally my fault because I didn't change that part and also I didn't warn the reviewer, so my apologies :(.

**Comment by xavijam** [comment]
@ivanmalagon will take care of it please 💋 .

**Comment by javitonino** [comment]
Deployed latest changes and removed FF!
