### ISSUE TITLE
Reproducible error in Builder while dragging layers

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#11397]
![out](https://cloud.githubusercontent.com/assets/7569673/22433543/05bdd394-e719-11e6-8cb7-3d8dbd515bea.gif)

### Steps to Reproduce
1. Create a points map
2. Add two subsample analyses (A1 and A2)
3. Drag A2 from A -> Creates a new layer B (B1 -> A1) and rewrites A (A1 -> A0)
4. Drag B1 from B -> Creates a new layer C (C1 -> A1) and rewrites B (A1)
5. Drag A1 from A -> Creates a new layer D but 💥 the rest of layers
6. Refresh: builder does not load

cc @xavijam

**Comment by xavijam** [comment]
I was checking this one yesterday, and it is not an easy one, needs a good debugging 😱 . As we know, it comes from the user-actions stuff.

**Comment by xavijam** [comment]
Related to ghost nodes.

**Comment by rubenmoya** [comment]
In production! 🚀
