### ISSUE TITLE
[Google Maps] Add support for Google Maps basemaps

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#11390]
- [x] Google Maps library should be loaded, using the user's API_KEY.
- [x] Upon clicking on a Google Maps basemap, BUILDER should talk to cartodb.js (this is being implemented in https://github.com/CartoDB/cartodb.js/pull/1561) and:
  - Update the baselayer.
  - Create/update the labels layer.
  - Switch the map provider.
- [x] If user/org (not sure how this is implemented) has support for Google Maps, Google Maps basemaps should be an option in the basemap selector.

**Comment by xavijam** [comment]
Something to take into account @saleiva @noguerol 

![screen shot 2017-02-20 at 14 44 39](https://cloud.githubusercontent.com/assets/132146/23127388/2f24018c-f77b-11e6-9413-017d3f1673c6.png)
