### ISSUE TITLE
Inconsistent state if deleting a dataset fails

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#11409]
### Context
From multiple support tickets, but finally managed to consistently reproduce. When deleting a dataset, if something fails, the database will be in an inconsistent state, where the user table and map are deleted, but the visualization is not, so it shows as a ghost table in the dashboard. 

### Steps to Reproduce
1. Create a dataset
2. Create a view over the dataset (`CREATE VIEW wadus AS SELECT * FROM table`)
3. Delete the dataset

### Current Result
Error, but the user table is deleted and the visualization is kept. 

### Expected result
Error, but all metadata objects are kept.

**Comment by gfiorav** [comment]
Hi, how come the ghost tables routine is not detecting this?

I ask because there is a check for it IIRC.

**Comment by javitonino** [comment]
Because the user table is there. It's only the map missing. Ghost tables only checks usertables AFAIK
