### ISSUE TITLE
Rails logs are using debug level instead of info

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/cartodb#11403]
See https://github.com/CartoDB/cartodb/pull/11382#discussion_r98634738

In our configurations we have

> config.log_evel = :info

But the loggers used end up having level 0 (debug) instead of 1 (info). (You can check this with `Rails.logger.level`).

The reason is that `config.log_level` is only [effective](https://github.com/rails/rails/blob/3-2-stable/railties/lib/rails/application/bootstrap.rb#L38) if a logger is [not explicitly assigned](https://github.com/rails/rails/blob/3-2-stable/railties/lib/rails/application/bootstrap.rb#L25) to `config.logger`, which is what we do in all our environments (e.g. see for [production](https://github.com/CartoDB/cartodb/blob/09d7ce60cad11e05114a329542f6b559232d4e29/config/environments/production.rb#L30)).

As a result all the SQL statements executed are echoed to our logs. [UPDATE: only those from Sequel; ActiveRecord uses `ActiveRecord::Base.logger` instead of `Rails.logger`]

We should use `config.logger.level = :info` after having assigned the logger (`Rails.logger.level` can be also used outside of the configuration block to change it)

```ruby
CartoDB::Application.configure do
  # ...
  config.logger = ActiveSupport::TaggedLogging.new(ActiveSupport::BufferedLogger.new(Carto::Conf.new.log_file_path('production.log')))
  config.logger.level = 1 # :info
  # ...
end
```

Note that we also have [this](https://github.com/CartoDB/cartodb/blob/09d7ce60cad11e05114a329542f6b559232d4e29/config/initializers/sequel.rb#L12) for some reason. [UPDATE: to have SQL statements from ActiveRecord appear in the log; otherwise we would have only those of Sequel]

~~This also affects central so I'll open a ticket there too.~~

cc @CartoDB/backend

**Comment by jgoizueta** [comment]
I have a question about this: what log level do we desire for the development environment. I think for production and staging it should be `:info` (as seems the intention in our current configuration). I think we could leave it at `:debug` in development (but not very important, as developers will adjust as needed).

**Comment by jgoizueta** [comment]
Ignore my question. I thought we had `config.log_level = :info` in development.

**Comment by ethervoid** [comment]
So if we create our logger as:

```
config.logger = ActiveSupport::TaggedLogging.new(ActiveSupport::BufferedLogger.new(Carto::Conf.new.log_file_path('production.log'), 'INFO'))
```

should work isn't it?

**Comment by jgoizueta** [comment]
Yes @ethervoid, that looks much better than my example. 

One small detail, looking at the docs I think the level has to be a numeric value:

```
config.logger = ActiveSupport::TaggedLogging.new(ActiveSupport::BufferedLogger.new(Carto::Conf.new.log_file_path('production.log'), ActiveSupport::BufferedLogger::Severity:INFO))
```

or

```
config.logger = ActiveSupport::TaggedLogging.new(ActiveSupport::BufferedLogger.new(Carto::Conf.new.log_file_path('production.log'), 1))
```

**Comment by juanignaciosl** [comment]
I just removed this from our TODO column because we must focus on some improvements for .carto. It's still centre stage, but feel free to assign it to any of you if you have a slot.

**Comment by jgoizueta** [comment]
This has been fixed here: https://github.com/CartoDB/cartodb/pull/11382
