### ISSUE TITLE
Broken users when deleting them

### ISSUE THREAD

**Issue by jsanz** [CartoDB/cartodb#11407]
### Context

* I use EUMAPI to create batches of users for workshops and then remove them too.

### Steps to Reproduce

I call repeatedly the call using a bash script (with 10 seconds sleep) to remove all the users, but some of them finish in a kind of broken status because even they appear at the organization tab I can't remove or use them anymore.

### Current Result

* Take a look on the `cartoworkshops` enterprise account and you'll see many users in this broken state like `cdmx05`, `cdmx13`, etc. 

### Expected result

* EUMAPI should work like a true batch API and users should be removed correctly from the account.

**Comment by javitonino** [comment]
Took a quick look. Summary: the user has unregistered tables, and we do not delete user that have database objects we are not aware of. See https://github.com/CartoDB/cartodb/issues/11026

Do you guys think it makes sense for EUMAPI to be more aggressive removing things than the normal user deletion? I know in the context of workshops, it does make a lot of sense, but I am not sure if we might break something for enterprise users that are using this API.

**Comment by jsanz** [comment]
OK I understand then that users creating manually tables or sharing them with others should not be removed but the issue then is that they got in a "corrupted" status. If I try to change the password I got this:

`There was a problem while updating this user. Please, try again and contact us if the problem persists. There was a problem with authentication server. No organization user found with username 'cartocamp29'`

**Comment by javitonino** [comment]
Yeah, they were deleted from Central but not the box. I feel like we get periodical problems about this, sometimes the user is deleted in the box but not central, and sometimes it's the reverse.

If you are OK with the deletion failing with tables, I'll just take a look to make sure the deletion does not leave inconsistent users.

**Comment by jsanz** [comment]
Sure, I'm OK with a process failing because of a legit reason. From the
EUAPI point of view a "force" parameter would be an enhancement but that's
it.

**Comment by javitonino** [comment]
For now, I'm working on fixing the inconsistent state part, and returning better errors, so you can get some idea of what happened (right now it returned a generic 500).
