### ISSUE TITLE
Unavailable analysis description has grammar errors.

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#11406]
### Context

On the Add analysis modal, when you can't apply certain analysis because of the type of data on your layer, the description shown in each analysis has some errors. 

### Current Result

![screen shot 2017-01-31 at 12 14 36](https://cloud.githubusercontent.com/assets/16247628/22462814/26978b3c-e7af-11e6-99d5-76b6324bfb8e.png)

### Expected result

"Your layer's geometries are unknown and this analysis needs points or polygons."
or
"Your layer's geometries are unknown and this analysis needs points."

**Comment by csobier** [comment]
@matallo, this one is auto-generated by a script so I can't edit the front-end text. Can you fix the parsing?

https://github.com/CartoDB/cartodb/search?utf8=%E2%9C%93&q=requiredInputGeometries&type=

**Comment by rubenmoya** [comment]
No more `unknown` geometries! To deploy! :shipit: 

![screen shot 2017-12-21 at 12 52 54](https://user-images.githubusercontent.com/905225/34254781-feb4ad72-e64d-11e7-839c-83ef90bb9340.png)

**Comment by matallo** [comment]
in production! 🚀
