### ISSUE TITLE
Edit the size and position of legends

### ISSUE THREAD

**Issue by csobier** [CartoDB/cartodb#11418]
### Context
@saleiva , we received a Learn inquiry about legends from a GIS Coordinator at Metro Area Planning Agency (MAPA). I know you already confirmed the existing behavior in the Design channel, thank you!

@namessanti asked me to create an issue, and tag @zingbot since he has received similar inquiries from clients.

See his comment below:
 "I'm updating a few maps that I made in the previous version of Carto and I've noticed that the legend isn't working for me visually any more.  Is there any way to reposition or resize the legend?  It currently takes up about 1/4 of the data frame when I embed a map into webpage which is incredibly unappealing from a cartographic perspective.  Ideally this would be dynamic, something a user could click on to expand and contract as desired."

Current Solution:
I suggested and promoted that he use widgets as an alternative for interacting with his data, and told him how to enable/disable legends with the Map Options as another option.

**Comment by saleiva** [comment]
Thanks @csobier there is already a design for fixing this -> https://github.com/CartoDB/design/issues/302 So we will fix it as soon as we can implement it! We expect legends to be smarter about how the grow and position!
