### ISSUE TITLE
Data Observatory Error needs to be simplified

### ISSUE THREAD

**Issue by csobier** [CartoDB/cartodb#11410]
### Context
@xavijam , Applied the _Enrich from Data Observatory_ analysis to the dataset _ne_50m_populated_places_simple_ (available from the Data Library), and received a hairy error.

 

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Connected to the _ne_50m_populated_places_simple_ from the Data Library and created a map.
2. Select the _Enrich from Data Observatory_ analysis
3. I tried several times with different parameters, and get the error every time. For example:
  - NEW COLUMN NAME= test
  - COUNTRY= United States
  - MEASUREMENT= Education
  - SEGMENT=Less than high school graduate

### Current Result

![image](https://cloud.githubusercontent.com/assets/13319925/22467791/011ac2f4-e794-11e6-9f53-a1226136933f.png)

 

### Expected result
When working with this dataset and this analysis, something is wrong with the projection, and is related to PostGIS. As a novice user, I wouldn't know what SQL workaround to apply. Perhaps Builder could prevent me from adding the analysis, or clarify that certain rows of data are problematic?  Open to suggestions.

### Browser and version
Google Chrome, version 55

**Comment by xavijam** [comment]
That's a problem with points "out of the world", already discussed in Windshaft, doesn't it @rochoa?

**Comment by rochoa** [comment]
Duplicates https://github.com/CartoDB/cartodb/issues/10540.
