### ISSUE TITLE
Add ellipsis to layer name on legends

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#11415]
### Context

Missing ellipsis in the legends for super long layer names. 

### Steps to Reproduce

1. Rename a layer with a super long title
2. Add a legend about that layer
3. Take a look at the title

### Current Result

![0bd3eed6-e7ae-11e6-9e5a-f8bfc08f0a48](https://cloud.githubusercontent.com/assets/16247628/22473569/976e63f6-e7d9-11e6-8e53-0fa78afe3d8e.png) 

### Expected result

Layer name should have an ellipsis on the legend to avoid that overflow and horizontal scroll bar.

**Comment by xavijam** [comment]
Already fixed -> https://github.com/CartoDB/cartodb.js/pull/1567.
