### ISSUE TITLE
Change "Cancel" link placement on the Analysis UI for consistency purposes

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#11414]
### Context

We'd like to move the Cancel link to the footer of the toolbar for the sake of consistency with other Builder screens.  

### Current Result

![01](https://cloud.githubusercontent.com/assets/16247628/22473369/f83799ec-e7d8-11e6-93d4-2a8fce55737d.png)

### Expected result

![02](https://cloud.githubusercontent.com/assets/16247628/22473358/f3614882-e7d8-11e6-98ca-6e5326feaa20.png)

**Comment by arianaescobar** [comment]
Related to this ticket: https://github.com/CartoDB/design/issues/541 

New location for the Measurement licenses on the Enrich from DO analysis UI.

**Comment by xavijam** [comment]
For me it would be a bit confusing, don't you think that?

**Comment by arianaescobar** [comment]
The cancel link or the license?

**Comment by xavijam** [comment]
The cancel link.

**Comment by xavijam** [comment]
Take into account that cancel button only appears when the analysis is not applied yet. So, if it is applied, `cancel` will turn into a `delete` option 😱 .

**Comment by xavijam** [comment]
Ping!

**Comment by arianaescobar** [comment]
Sorry that I forgot to reply to this! 

I believe it's ok. In every other screen, we have the **Cancel** there so I believe it's more confusing having this one in a different location. Regarding when it changes to **Delete**, I still think it's a good place for it. 

The only thing that makes me wonder a bit now that you've brought it up, is that our users may get wary with that action since they might believe that it will delete the whole analysis workflow. 

Now we have it right next to the "Analysis XX" thing, so it's more clearly related to the node, so maybe we might want to the change the copy to "Delete XX" or "Delete Analysis node" or something like that. What do you guys think @CartoDB/design?

**Comment by Jesus89** [comment]
When the Cancel button changes to Delete, does the color need to change to red? @arianaescobar

**Comment by rubenmoya** [comment]
In production! 🚀
