### ISSUE TITLE
Aggregation by Admin Region > including polygons with no overlapping data

### ISSUE THREAD

**Issue by makella** [CartoDB/cartodb#11416]
### Context
Using the Aggregation > Admin Region styling method on a point dataset puts polygons with no overlapping data into the lowest class on the map.  When there are datasets that cover some but not all of the admin regions around the world, a map like the default we have can be very misleading.

A proposed solution is to assign any polygon without overlapping data into a `no data` value and appropriate color (like grey). 

### Steps to Reproduce
1. Add points to a map
2. Choose the option for Aggregation > Admin Region
3. Select Provinces for the Admin Level
4. Choose any Operation, they all produce the same result

### Current Result
The point dataset only covers the US: 

![screen shot 2017-01-31 at 9 33 43 am](https://cloud.githubusercontent.com/assets/1566273/22474149/596f5cc2-e798-11e6-9c18-4540756cd454.png)

When I aggregate by Admin Region > Province, every place with no data, gets binned into the lowest class of `agg_value_density`:

![screen shot 2017-01-31 at 9 35 38 am](https://cloud.githubusercontent.com/assets/1566273/22474266/ac81a41a-e798-11e6-93c9-aaf8bf516d9a.png)

### Expected result
A `no data` value and appropriate color (like grey).

**Comment by alrocar** [comment]
Stale issue. Closing 👋
