### ISSUE TITLE
Color scheme not clickable on color properties dropdown

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#11413]
### Context

On the color properties dropdown, on the following step after you select a color scheme, the scheme selected, represented fully at the top, is not clickable. And it should be. 

### Current Result

![2fa372a6-e7c6-11e6-975a-925f89876f79](https://cloud.githubusercontent.com/assets/16247628/22471353/5fb37e44-e7d2-11e6-9b22-5fb7fa8651b4.png)

### Expected result

It can always be clicked.

![547da7b8-e7c6-11e6-9b47-55ba5efbbf9e](https://cloud.githubusercontent.com/assets/16247628/22471344/597e0b8e-e7d2-11e6-973d-e8f74ac3d60f.png)

**Comment by nobuti** [comment]
Picking this.

**Comment by nobuti** [comment]
Ready for CR.

**Comment by ivanmalagon** [comment]
Acceptance not passed.

Reasons:

1. I think the whole row should be clickable, not only the color ramp.

1. The clickable state should be shown with the pointer cursos.

1. `NEWS.md` should be filled.

Moving this back to `development` and assigning this to myself to do these minor fixes.

**Comment by xavijam** [comment]
Innnn production. Thanks mates!
