### ISSUE TITLE
Focus state doesn't show on some inputs

### ISSUE THREAD

**Issue by urbanphes** [CartoDB/cartodb#11412]
### Context

This state (with blue border) doesn't show in all inputs. 

This is the state:

![captura de pantalla 2017-01-31 a las 15 31 50](https://cloud.githubusercontent.com/assets/14546701/22468910/7c1465ec-e7ca-11e6-87c0-5dfa81a00484.png)

Only appears in some:

<img width="306" alt="captura de pantalla 2017-01-31 a las 15 33 24" src="https://cloud.githubusercontent.com/assets/14546701/22469022/d3655202-e7ca-11e6-87ef-704435e5fa5d.png">

<img width="330" alt="captura de pantalla 2017-01-31 a las 15 33 53" src="https://cloud.githubusercontent.com/assets/14546701/22469029/d9668bda-e7ca-11e6-9d44-df8eb3f5e18d.png">

... and doesn't show in the rest

<img width="313" alt="captura de pantalla 2017-01-31 a las 15 33 39" src="https://cloud.githubusercontent.com/assets/14546701/22469073/00f81100-e7cb-11e6-8cc3-3a625e846b2e.png">
<img width="340" alt="captura de pantalla 2017-01-31 a las 15 34 24" src="https://cloud.githubusercontent.com/assets/14546701/22469078/03990ac2-e7cb-11e6-8926-f0fed16c879d.png">

**Comment by arianaescobar** [comment]
Fixed!
