### ISSUE TITLE
Adding join analysis and choosing the_geom as output column makes the instantiation fail

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#11429]
### Steps to Reproduce
1. Create a map with two layers
2. Add a join analysis
3. In the output columns, select `the_geom` for one of the two layers

### Current Result
Map instantiation fails 

### Expected result
You cannot choose a `the_geom` column there. It is already added by the previous combo (which layer to take geometries from)

Probably the reason that we filtered geometries columns in that analysis. See https://github.com/CartoDB/cartodb/pull/11367

**Comment by matallo** [comment]
![screen shot 2017-02-02 at 12 02 25](https://cloud.githubusercontent.com/assets/36676/22546936/7ef41e58-e93f-11e6-8d0b-2ce913538d79.png)

Indeed the error appearing is `column reference "the_geom" is ambiguous`

**Comment by javitonino** [comment]
Duplicate of https://github.com/CartoDB/cartodb/issues/11184, I'll close this one.
