### ISSUE TITLE
UI updates for the Georeference analysis

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#11426]
## Context

We'd like to make a few adjustments to the Georeference analysis UI to avoid confusions in our users.

Design issue: https://github.com/CartoDB/design/issues/534

### General

- [x] On the second step: change description to "Select data type"
- [x] ~Change the required notifications color to black (like the normal tooltip) and keep the input in its default style~ -> Bug fixed.

### If "Lon/Lat Columns" type is selected, change the following placeholder texts:

- [x] _Lon/Lat Columns_ to **Longitude and Latitude**
- [x] _Select a latitude_ to **Select a latitude column**
- [x] [In the dropdown] _Search by latitude_ to **Search by column name**
- [x] _Select a longitude_ to **Select a longitude column**
- [x] [In the dropdown] _Search by longitude_ to **Search by column name**

### If "City" type is selected, change the following placeholder texts:

- [x] _City names_ to **Cities**
- [x] _Select a city_column_ to **Select a city column**
- [x] [In the dropdown] _Search by city_column_ to **Search by column name**
- [x] _Select a admin_region_ to **Select an admin. region column**
- [x] [In the A. Regions's dropdown] _Search by admin_region_ to **Or enter region name**
- [x] [In the A. Regions's tooltip] _In which column are your country names stored?_ to **Specify an admin. region or select a column with region names**
- [x] _Select a country_ to **Select country column**
- [x] [In the Country's dropdown] _Search by country_ to **Or enter country name**
- [x] [In the Country's tooltip] _In which column are your country names stored?_ to **Specify a country or select a column with country names**

### If "Country names" type is selected, change the following placeholder texts:

- [x] _Country names_ to **Countries**
- [x] _Select a country_column_ to **Select a country column**
- [x] [In the dropdown] _Search by country_column_ to **Search by column name**

### If "Admin Region" type is selected, change the following placeholder texts:

- [x] _Select a admin_region_column_ to **Select a admin. region column**
- [x] [In the dropdown] _Search by admin_region_column_ to **Search by column name**
- [x] _Select a country_ to **Select country column**
- [x] [In the Country's dropdown] _Search by column_ to **Or enter country name**
- [x] [In the Country's tooltip] _In which column are your country names stored?_ to **Specify a country or select a column with country names**

### If "Postal Codes" type is selected, change the following placeholder texts:

- [x] _Select a postal_code_column_ to **Select a postal code column**
- [x] [In the dropdown] _Search by postal_code_column_ to **Search by column name**
- [x] _Select a country_ to **Select country column**
- [x] [In the Country's dropdown] _Search by column_ to **Or enter country name**
- [x] [In the Country's tooltip] _In which column are your country names stored?_ to **Specify a country or select a column with country names**

### If "IP Addresses" type is selected, change the following placeholder texts:

- [x] _COL. IP AD._ to **IP Address**
- [x] _Select a ip_address_ to **Select an IP address column**
- [x] [In the dropdown] _Search by ip_address_ to **Search by column name**

### If "Street Addresses" type is selected, change the following placeholder texts:

- [x] _COL. STREET AD._ to **Street Address**
- [x] _Select a street_address_colum_ to **Select a street ad. column**
- [x] _Select a city_ to **Select city column** | 
- [x] [In the City's dropdown] _Search by city_ to **Or enter city name**
- [x] [In the City's tooltip] _In which column are your city names stored?_ to **Specify a city or select a column with city names**
- [x] _Select a state_ to **Select state column** 
- [x] [In the State's dropdown] _Search by state_ to **Or enter state name**
- [x] [In the State's tooltip] _In which column are your state names stored?_ to **Specify a state or select a column with state names**
- [x] _Select a country_ to **Select country column**
- [x] [In the Country's dropdown] _Search by column_ to **Or enter country name**
- [x] [In the Country's tooltip] _In which column are your country names stored?_ to **Specify a country or select a column with country names**

**Comment by xavijam** [comment]
Hey, this is an enormous job, thanks for that team.

**Comment by ivanmalagon** [comment]
PR submitted.

Instead of changing notification style, we've fixed the bad behaviour of validating the form when switching georeference type.

![georeference](https://cloud.githubusercontent.com/assets/1078228/23058831/1645521e-f4f7-11e6-9b9a-5d7b78443fa5.gif)

**Comment by nobuti** [comment]
Already in production. Closed by #11548.

**Comment by arianaescobar** [comment]
Thank you guys! ❤️  And sorry for the super long ticket.
