### ISSUE TITLE
Styling falsy categories is not working properly

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#11421]
### Steps to Reproduce

1. You have a points map where you want to style a numeric column by category.  
2. Make sure one the values of that column is 0. You can use a SQL Update query to change one of the values to zero.
3. Style by value, selecting the above column and category as quantification.
4. Builder assigns a color per category. Change the color of a category that falls under the one with 0. For instance, the column with value X (this depends on your data).

### Current Result
The points that reflect this color change are not the one assigned to value X. You can check this with a pop-up.

The generated CartoCSS doesn't write the falsy category in the `marker-fill` so there's a mismatch between number of colors and number of categories.

Same happens with text categories that are null or empty string.

### Expected result
There's no mismatch between the number of colors and categories, so when modifying a category, the modification is reflected on the right category.

### .carto file
[Madrid (on 2017-02-01 at 10.44.00).carto.zip](https://github.com/CartoDB/cartodb/files/744591/Madrid.on.2017-02-01.at.10.44.00.carto.zip)

In this map, the bright green points are supposed to be `place 6` according to the category styling, but if you click on them you'll see that they're `place 7`

cc @xavijam

**Comment by xavijam** [comment]
Deployed!
