### ISSUE TITLE
Style is reset after modifying SQL

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#11436]
### Steps to Reproduce

1. Create a map
2. Edit SQL, adding a `WHERE` clause for instance
3. Style layer with the UI based upon a numeric value field
3. Edit CartoCSS
4. Edit SQL, removing the `WHERE` clause

### Current Result

* Style is reset as the one applied with the UI (style options).

### Expected result

* Style should not be reset.

### Browser and version

* Google Chrome v54.

### Additional info

* Maybe related to this issue: https://github.com/CartoDB/cartodb/issues/11308.

cc @ivanmalagon

**Comment by saleiva** [comment]
this is a dupe if I am not wrong -> https://github.com/CartoDB/cartodb/issues/10700

**Comment by ramiroaznar** [comment]
Well, not sure about that... I was talking about changing SQL, not analysis...

**Comment by ramiroaznar** [comment]
^^ @saleiva @xavijam

**Comment by ramiroaznar** [comment]
Guys this is happening again, not just after modifying the SQL, but also adding or removing a popup.

**Comment by saleiva** [comment]
The popup thing worries me... does it happen always? cc/ @xavijam

**Comment by xavijam** [comment]
I've tried with a SQL with a `WHERE` clause or adding/removing a popup and I haven't suffered that problem. Could you still reproduce it @ramiroaznar? If so, gimme even better steps please 💋 .

**Comment by xavijam** [comment]
ping pong!

**Comment by ramiroaznar** [comment]
It looks like it is fixed! :-)

**Comment by xavijam** [comment]
I don't trust in auto-fixed things :joy: (taking into account we haven't "touched" anything about this stuff), so if you find it again, please re-open this issue. Of course, with steps to reproduce would be great.
