### ISSUE TITLE
[popups] using field value as title when title is empty (hover and click)

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#11430]
### Context
when adding a popup and the user wants to remove the title from the field in a popup (both hover and click) she needs to remove the text in the form, however when proceeding the title appears and takes the field value
 
this is probably related to cartodb.js

### Steps to Reproduce

1. create a map of points 
2. add popups and select a field
3. remove the title string

### Current Result
the value of the field appears as the title
 

### Expected result
there should not be any title

### .carto file
https://matallo.carto.com/builder/4a9dc2fe-e939-11e6-a57f-0e3ff518bd15/embed
 

### Additional info

![edf09df7-f212-4328-a4ea-b8460548479c](https://cloud.githubusercontent.com/assets/36676/22547675/0849b2dc-e943-11e6-8e2c-e5e5f890685d.png)

**Comment by saleiva** [comment]
I'd prioritize this to the kanban guys

**Comment by matallo** [comment]
@xavijam ^^^
