### ISSUE TITLE
Base layer is saved twice when switching to a plain base layer and UI shows error message

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#11445]
### Context

I was working on adding support for Google Maps Basemaps and I stumbled upon this problem when doing some QA.
 
### Steps to Reproduce

1. Open a map in BUILDER.
2. Click on the basemap layer.
3. Select one of the CARTO basemaps.
4. Change the basemap to a plain color by clicking on COLOR and selecting a color.

### Current Result
- Base layer is being saved twice ([here](https://github.com/CartoDB/cartodb/blob/master/lib/assets/core/javascripts/cartodb3/editor/layers/basemap-content-views/basemap-select-view.js#L81) and [here](https://github.com/CartoDB/cartodb/blob/master/lib/assets/core/javascripts/cartodb3/editor/layers/basemap-content-views/basemap-form-model.js#L45)). The first request is being cancelled, and causes the UI to show an error message temporarily:

  ![basemap-color](https://cloud.githubusercontent.com/assets/390398/22588550/a0c6afb0-ea06-11e6-8631-8576e5a4c69c.gif)

### Expected result
- Base layer should only be changed once (only one network request).
- Message should change from "Saving new basemap" to "Basemap saved successfully."

### Browser and version
All.

**Comment by xavijam** [comment]
Already fixed! with https://github.com/CartoDB/cartodb/issues/11934

**Comment by alonsogarciapablo** [comment]
👏 👏 👏
