### ISSUE TITLE
Don't let add a new geometry (point, line or polygon) when a query is applied over a source

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#11442]
## STR
- Create a map of points.
- Apply a query over that layer.

## Current behaviour
- Check that "add new feature" button is still there.
- 💥 .

## Expected behaviour
- We should disable the "add new feature" button, we can't provide that.

Problem found thanks to https://github.com/CartoDB/cartodb/issues/11356.

**Comment by nobuti** [comment]
Picking this.

**Comment by xavijam** [comment]
I'm adding all the checks we need before starting the acceptance (just in case).

**Comment by nobuti** [comment]
Already in production.
