### ISSUE TITLE
Batch _CDB_populate_the_geom_webmercator_from_the_geom at table.rb

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#1144]
cartodb._CDB_populate_the_geom_webmercator_from_the_geom query timeouts for some users

**Comment by iriberri** [comment]
Related: https://github.com/CartoDB/cartodb/issues/7047
Related: https://github.com/CartoDB/cartodb/pull/7042
Related: https://github.com/CartoDB/cartodb/issues/6991

**Comment by iriberri** [comment]
Closing, this is performed now by cartodbfycation and the code does no longer live in there. Timeouts in cartodbfycation are controlled.
