### ISSUE TITLE
Not possible to edit dataset metadata if it is synced

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#11458]
### Steps to reproduce it
- Create a dataset from the data library.
- Visit that dataset.
- Try to add a label or change the description.
- Option is not available.

**Comment by saleiva** [comment]
Worth a test

**Comment by xavijam** [comment]
Fixing this as part of my Friday's leapfrog.

**Comment by nobuti** [comment]
Closed by #11635.
