### ISSUE TITLE
Long column name gets render outside the box in the popup component

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#11451]
### Steps to Reproduce

1. Style a layer by value
2. Select a very long column name
3. 

### Current Result
![screen shot 2017-02-03 at 16 35 47](https://cloud.githubusercontent.com/assets/132149/22597204/f56670fa-ea2e-11e6-903b-74c121ffeaa8.png)

### Expected result
We should add a ellipsis on this text when being so long.

**Comment by xavijam** [comment]
Added to UI fixes, 👍  or 👎  ?

**Comment by jorgesancha** [comment]
IMO, I think this is Nice To Have™️, but not a blocker for Free users migration. What do you think @noguerol ?

**Comment by saleiva** [comment]
It is not

**Comment by noguerol** [comment]
let's push that migration asap

**Comment by javierarce** [comment]
This appears in acceptance but the PR is already merged? Should we move it to the deploy column?

**Comment by nobuti** [comment]
It was @piensaenpixel doing the cowboy, I think so.

**Comment by javierarce** [comment]
Haha… where's the kanban police when you need them? :_

**Comment by saleiva** [comment]
:sanchismo:
