### ISSUE TITLE
Torque rendering problem with Firefox

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#11466]
### Context
Torque visualizations don't work well in Firefox v51. 

Tiles are rendered, but for some of them are not 'cleared' and the result is similar to having the 'cumulative' option enabled. 

This happens only in Firefox, and not on every tile, as some of them work as expected. 
 

### Steps to Reproduce

1. Make sure you're using Firefox v51
2. Open this map https://team.carto.com/u/ernestomb/builder/cd37d292-ec93-11e6-9e93-0e3ebc282e83/embed
3. Check that markers are not cleared and they start accumulating, but only on some of the tiles

### Current Result

Torque maps aren't working well on Firefox

![screen shot 2017-02-06 at 18 51 37](https://cloud.githubusercontent.com/assets/10940006/22659278/57ee3c9c-ec9d-11e6-80f7-2c706eceda14.png)

 

### Expected result

Markers should be cleared from the map 

### Browser and version

 Firefox v51

**Comment by xavijam** [comment]
This ticket should be moved to torque repository.

**Comment by xavijam** [comment]
cc @rochoa
