### ISSUE TITLE
Fix Description input in Formula widgets

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#11469]
### Context

Right now the Description input of the Formula widget has the label "DEFINE HOW YOUR WIDGET INTERACTS WITH THE DATA" when it should only say "Description". 

Also, we'd like to move that input to the second step, below the Suffix input. 

### Current Result

<img width="417" alt="screen shot 2017-02-06 at 19 13 15" src="https://cloud.githubusercontent.com/assets/16247628/22660056/5af8d2f0-eca0-11e6-9ee2-2e9f0b1ce182.png">

### Expected result

![screen shot 2017-02-06 at 19 17 21](https://cloud.githubusercontent.com/assets/16247628/22660192/ea030a06-eca0-11e6-9f25-1f9ec7661347.png)

**Comment by nobuti** [comment]
hey @piensaenpixel, in order to achieve the layout above for the textarea `align-items: flex-start;` it's not enough, we need to add some padding to the label. Not sure if we should tackle it in this issue or on the other hand, consolidate it in another issue.

**Comment by piensaenpixel** [comment]
hey @nobuti this was a problem we have had :(

But I think we can fix it:

- Change `.Editor-formInner { align-items: center: }` to `.Editor-formInner { align-items: flex-start: }` We align all the elements to the top
-  FIx legend's align with `.CDB-Legend {min-height: 32px; display: flex; align-items: center }` Vertical align for the legends with a min-height
- And fix the step's maker with `.Editor-formInner--nested .CDB-Legend::before { top: 50%; transform:  translateY(-50%)}`

does it sound good?

**Comment by nobuti** [comment]
Sounds great :kiss:

**Comment by ivanmalagon** [comment]
Deployed to produ.
