### ISSUE TITLE
Enable the possibility to select an icon previously uploaded by the organization admin

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#11462]
So the use case is:

- The organization admin uploads an icon, in order to be used in any map by any organization user.
- Any organization user should start using it from its map view, selecting it from the assets modal.

We are enabling the possibility to upload any kind of asset in order to be used like a marker (https://github.com/CartoDB/cartodb/pull/11450), but we have realized that I didn't specify the need of adding the `Organization icons` panel in that new modal view.

So instead of making the PR even bigger, I'm opening this ticket.

cc @saleiva @jorgesancha

**Comment by xavijam** [comment]
Great @matallo we have this in CR 💋

**Comment by saleiva** [comment]
@noguerol can you also participate on this one?

**Comment by noguerol** [comment]
Is this on staging already?

**Comment by javierarce** [comment]
@noguerol Yes, I'll answer you in private.
