### ISSUE TITLE
Overflow text on BY VALUE modal

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#11463]
### Context
When applying a _BY VALUE_ style, if the column name is too long, there is a text overflow

 

### Steps to Reproduce

1. Import [dummy_dataset_0.csv.zip](https://github.com/CartoDB/cartodb/files/754721/dummy_dataset_0.csv.zip)
2. Go to _STYLE_ and click on the fill bar
3. Select _BY VALUE_ 
4. Select the column with the long name

### Current Result
![screen shot 2017-02-06 at 14 39 53](https://cloud.githubusercontent.com/assets/10940006/22649446/365e7b9a-ec7b-11e6-8837-c1391f9061d5.png)

 

### Expected result
Column name text shouldn't overflow

**Comment by xavijam** [comment]
I feel it is already reported, let me look for it.

**Comment by xavijam** [comment]
https://github.com/CartoDB/cartodb/issues/11451
