### ISSUE TITLE
Update text of Widget tooltips

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#11467]
## Context

We'd like to add the complete label name of the following inputs to their tooltips. Since we don't see the alt name when hovering because we're showing the tooltip instead, let's add the complete label name to it. 

We also want to change the tooltip text. 

### Category widget options

**New text:**
Custom ramp: colors used when Autostyle (drop icon) is applied. 

<img width="419" alt="screen shot 2017-02-06 at 18 42 48" src="https://cloud.githubusercontent.com/assets/16247628/22658996/573e6110-ec9c-11e6-971e-041139416a70.png">

### Histogram widget options 

**New text:**
Custom ramp: colors used when Autostyle (drop icon) is applied. 

<img width="414" alt="screen shot 2017-02-06 at 18 42 36" src="https://cloud.githubusercontent.com/assets/16247628/22658999/5b0e755a-ec9c-11e6-9ec8-3bbbdb6046b8.png">

**Comment by rubenmoya** [comment]
The new tooltip text for the category widget is also "Custom ramp" or that's a typo @arianaescobar?

**Comment by ivanmalagon** [comment]
Shipped! 🚀
