### ISSUE TITLE
Uglify task slowness

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb#11465]
Review the recent degradation of uglify task. It seems related to tangram integration and some problems with the uglify version we have.

See https://github.com/mishoo/UglifyJS2/issues/321

cc @xavijam @luisbosque @jorgesancha @javisantana

**Comment by xavijam** [comment]
cc @javitonino

**Comment by javitonino** [comment]
Created a PR for my little experiment updaing uglifyJS -> https://github.com/CartoDB/cartodb/pull/11471

**Comment by donflopez** [comment]
Thanks @javitonino! I'll try it in staging :)

**Comment by donflopez** [comment]
It seems to be working properly, closing!
