### ISSUE TITLE
Animated map keeps reproducing even when filtered (on embed)

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#11464]
### Steps to Reproduce

1. Go to this map https://twitter-maps.carto.com/u/twitterdata2/builder/2b9dc202-ec0c-11e6-b0df-0e3ff518bd15/embed?state=%7B%22map%22%3A%7B%22ne%22%3A%5B23.60426184707018%2C-125.72753906249999%5D%2C%22sw%22%3A%5B47.90161354142077%2C-53.30566406249999%5D%7D%7D
2. Filter using the time-series widget

### Current Result
It keeps reproducing the animation

### Expected result
It should stop the animation and show the filtered data

**Comment by xavijam** [comment]
Not happening anymore, fixed with last changes done over time-series widget 🎉 .
