### ISSUE TITLE
Activate for all and remove icon-styling feature flag

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#11478]

**Comment by xavijam** [comment]
Icon styling right?

**Comment by saleiva** [comment]
style by icon, sorry

**Comment by nobuti** [comment]
Picking this.

**Comment by xavijam** [comment]
Are we ready for this @saleiva?
Probably we want to block it until we merge all the pending things... or am I wrong?

**Comment by nobuti** [comment]
Adding the `don't deploy` to put it on hold once developed.

**Comment by nobuti** [comment]
Already in production. Closed by #11502.
