### ISSUE TITLE
Importing the same .carto file or dataset produce maps with identical names

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#11472]
### Context

While doing the acceptance for [this PR](https://github.com/CartoDB/cartodb/pull/11435) we discovered that importing the same .carto file (or the same CSV) produce maps with the exact same name.

Since it's not possible to rename a map with the same name of another existing map, I believe this should considered a bug.

### Steps to Reproduce
1. Create a map using a .carto (or CSV file)
2. Repeat #1 several times

### Current Result

![screen shot 2017-02-06 at 18 12 03](https://cloud.githubusercontent.com/assets/4933/22687993/96d3a07c-ed2a-11e6-9276-db16ad469fa7.png)

### Expected result
I believe we should have consecutive names (Untitled Map 1, Untitled Map 2, etc.)

**Comment by xavijam** [comment]
Uhm, what do you think @juanignaciosl? Should we add any difference?

**Comment by juanignaciosl** [comment]
TBH I've never liked the "every map import should be `Untitled map` by default. I would, for `my_dataset.csv` dataset import, name the map as "My Dataset Map".

Nevertheless, for .carto imports, as there's an explicit `title` inside .carto metadata, I'd keep it unchanged, even if there's a name collision.

But I'm not the one who ask to about this :_)

**Comment by juanignaciosl** [comment]
Closing automatically because of inactivity. If anybody considers that this still important, please reopen and it'll be prioritized.
