### ISSUE TITLE
Remove simple and pin iconsets

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#11479]
@noguerol and @urbanphes found the problem described below, and we have decided to remove Simple and Pin iconsets from the new upload-asset modal. Only maki icons support the stroke.

### Context
When styling with icons, their stroke alpha is not rendered at 1 by default, even the settings say so.
 

### Steps to Reproduce
1. Style a point layer with any icon
2. Tweak the stroke size to a more obvious value

### Current Result
Stroke is rendering semi transparent even tho alpha setting is default 1

![image](https://cloud.githubusercontent.com/assets/70603/22707685/de40d74c-ed73-11e6-8bde-f96572de7fda.png)

### Expected result
Stroke should render at alpha 1, like in normal bubbles

### Browser and version
Chrome 55.0.2883.87

**Comment by saleiva** [comment]
This is a dependency of how the incons are made I'm afraid.

**Comment by xavijam** [comment]
Yes, already checked, and that's a limitation of the maki icons.

**Comment by javierarce** [comment]
Yesterday we talk about getting rid of the Pin and Simple icons… are we still planning to do that?

**Comment by saleiva** [comment]
I think yes

**Comment by xavijam** [comment]
Hey, let's remember to open a ticket in website mentioning to remove the attribution to those iconsets when it happens.
https://carto.com/attribution (scroll down, there is no direct link).

**Comment by saleiva** [comment]
We cannot, they are still there on editor.

**Comment by javierarce** [comment]
I tried to use http://fontawesome.io/icons, but they don't show a border either :(

**Comment by xavijam** [comment]
ouch :(, ok. Changing name of the title guys.

**Comment by nobuti** [comment]
Ready for CR.

**Comment by noguerol** [comment]
About this, did we remove the "maki" name from the tab as we agreed?

**Comment by xavijam** [comment]
Yes
