### ISSUE TITLE
Autostyling and CartoCSS Filters not Working Together

### ISSUE THREAD

**Issue by makella** [CartoDB/cartodb#11470]
### Context

CartoCSS filters are not being respected by Autostyling. CartoCSS filters are similar to SQL filters and should be respected in the same way with Autostyling. 

Filters are used regularly to introduce features through zoom, style a subset of the data, etc using:
- zoom level filters 
  - `#layer [zoom>=5]{...}` 
- numeric filters 
  - `#layer [amount>800]{...}`
- text filters 
  - `#layer [store='Walmart']{...}`
- or any combination of filters
  - `#layer [store='Walmart'][amount>800]{...}`

You can probably imagine more complex filters for styling a subset of features by zoom:
```
#layer 
[zoom>0][amount>800],
[zoom>3][amount>600],
[zoom>4][amount>400],
[zoom>5][amount>200],
[zoom>6]{
  ...
}
```
### Steps to Reproduce
1. Add points to a map
2. Style with any one of the filter types listed above
3. Add a Widget
4. Turn on Autostyling, notice that all features draw regardless of the CartoCSS filter

### Current Result
When someone clicks the option to Autostyle, the way the Autostyling CartoCSS is added to the existing CartoCSS is causing the problem. 

For example, if I styled points with a filter of `amount > 800`:
```
 #layer [amount>800] {
    marker-width: 7;
    marker-fill: purple;
    marker-line-color: #FFF;
    marker-allow-overlap: true;
}
```
The map looks like this (not so many records meet the filter):
![screen shot 2017-02-06 at 1 43 42 pm](https://cloud.githubusercontent.com/assets/1566273/22665508/39a0591c-ec72-11e6-9475-287acf9e5dbf.png)

If I choose to symbolize with Autostyle, features that aren't part of the filtered result draw:
![screen shot 2017-02-06 at 1 46 05 pm](https://cloud.githubusercontent.com/assets/1566273/22665629/aa739d84-ec72-11e6-8103-ca70573fd9eb.png)

The Autostyling CartoCSS (in this case) is overriding for two reasons:
- we remove `marker-fill` from the main block (makes sense)
- and then add the Autostyle CartoCSS as another `#layer` on top so the filter never gets considered
```
 #layer ['mapnik::geometry_type'=1] { marker-fill: ramp([state], ("#11A579", "#F2B701", "#7F3C8D", "#3969AC", "#E73F74", "#A5AA99"), ("CA", "TX", "NY", "FL", "VA"));  }  

#layer [amount>800] {
  marker-width: 7;
  marker-fill-opacity: 0.9;
  marker-line-color: #FFF;
  marker-allow-overlap: true;
}
```
### Expected result
The expected result is for only the features with the filters to get Autostyled. 

Since we are removing the `marker-fill` property (in this case) I think it is as easy as putting the Autostyling `marker-fill` styling directly into the block of CartoCSS:

```
#layer [amount>800] {

  marker-width: 7;
  marker-fill-opacity: 0.9;
  marker-line-color: #FFF;
  marker-line-width: 1;
  marker-line-opacity: 1;
  marker-placement: point;
  marker-type: ellipse;
  marker-allow-overlap: true;

  marker-fill: ramp([state], ("#F2B701", "#7F3C8D", "#3969AC", "#E73F74", "#11A579", "#A5AA99"), ("TX", "NY", "FL", "VA", "IL"));    
}
```
The resulting map (when Autostyling is activated) would look like:
![screen shot 2017-02-06 at 2 18 03 pm](https://cloud.githubusercontent.com/assets/1566273/22666734/0ad8be1c-ec77-11e6-8827-77eea85a2bc7.png)

### Additional Information
I definitely think we need to look into the syntax in more detail when the map is filtered and Autostyled between widgets.

For example, when styled using a histogram widget, the syntax looks a little different from traditional TurboCARTO:

`#layer ['mapnik::geometry_type'=1] { marker-fill: ramp([amount], cartocolor(SunsetDark, 10), jenks); }`

I'm guessing that `cartocolor(SunsetDark,10)` is for 10 class breaks to match the histogram widget. This is also not working properly with CartoCSS filtered data even if it is inside of the styling block.

**Comment by xavijam** [comment]
Right now it works different. Any "fill" attribute is being removed from any CartoCSS filter and only one fill rule is added in the main #layer declaration if it is defined.
I feel this problem is not happening anymore but not sure if this is the best possible behaviour :S. What do you think?

**Comment by makella** [comment]
The behavior has changed, still with an error, and I'm not exactly sure what is going on.

using the same CartoCSS as above:
```
 #layer [amount>800] {
    marker-width: 7;
    marker-fill: purple;
    marker-line-color: #FFF;
    marker-allow-overlap: true;
}
```
and adding a category widget for `state`:

![screen shot 2018-02-27 at 2 37 07 pm](https://user-images.githubusercontent.com/1566273/36756248-b94b4724-1bcb-11e8-949e-3f25667dd99f.png)

When autostyle is activated, all points default to Mapnik default blue. If you look at the Autostyle CartoCSS you'll see that `marker-fill` is completely removed

```
#layer [amount > 800]{
  marker-width: 7;
  marker-fill-opacity: 1;
  marker-allow-overlap: true;
  marker-line-width: 1;
  marker-line-color: #FFFFFF;
  marker-line-opacity: 1;
}
```
![autostyle-conditions](https://user-images.githubusercontent.com/1566273/36757247-5626ad02-1bce-11e8-8498-d929114b3454.gif)

Another confusing piece is that if I add a histogram widget, there is no option for Autostyle like there is for category. 

Even though this option is not available (I'm assuming because of the CartoCSS condition) two things are happening:

- you can still see the customization options for the histogram widget are still editable (even though Autostyle is not available)
![screen shot 2018-02-27 at 3 00 48 pm](https://user-images.githubusercontent.com/1566273/36757568-2c620916-1bcf-11e8-97bd-fa967c07f8b8.png)

- the data distribution of the histogram widget and the count of features in the category widget are not respecting my CartoCSS condition (`amount>800`):

![screen shot 2018-02-27 at 3 01 16 pm](https://user-images.githubusercontent.com/1566273/36757595-404bc6d8-1bcf-11e8-9247-5f94a5309121.png)
