### ISSUE TITLE
Circle icons in Maki icon set are redundant

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#11481]
### Context
The two first icons of the Maki icon set are redundant, as same result cloud be obtained with plain bubbles. This is specially confusing because we're previewing that iconset and those two icons as the first options on the fill dropdown.
 

### Steps to Reproduce

1. Style any point map with icons
2. Paw! you don't know if style with bubbles or icon bubbles.

### Current Result
When selecting IMG as point styling, the two maki icons bubbles are previewed
![image](https://cloud.githubusercontent.com/assets/70603/22708015/ffeb6b18-ed74-11e6-96db-3454901acc07.png)

### Expected result
No bubble icons anymore.

### Browser and version
Chrome 55.0.2883.87

**Comment by saleiva** [comment]
Not sure we can change the order since the idea was to keep the icon set as it is by default

**Comment by noguerol** [comment]
I think we should get rid of them.

**Comment by saleiva** [comment]
Again, that would mean maintaining special rules on how maki (3rd party library maintained by other people) is used within CARTO which IMO adds a lot of implications. How are we ordering them @xavijam ?

**Comment by xavijam** [comment]
We have the list of maki icons here: 

https://github.com/CartoDB/cartodb/blob/master/lib/assets/core/javascripts/cartodb3/components/form-components/editors/fill/input-color/assets/maki-icons.js

We can do whatever you want, move, remove, add,...

**Comment by saleiva** [comment]
cool! Then let's remove what @noguerol says!

**Comment by nobuti** [comment]
Picking this.

**Comment by nobuti** [comment]
Ready for CR.

**Comment by gfiorav** [comment]
Closed via https://github.com/CartoDB/cartodb/issues/11501
