### ISSUE TITLE
CSS3 Selektor not working in CartoCSS namedMap (invalid code)

### ISSUE THREAD

**Issue by braintuts** [CartoDB/cartodb#11489]
Hello,

I pushed a namedMap to CartoDB with a new CSS-Code. After I call that namedMap i received an error:
`    "errors": [
        "style0:26:8 Invalid code: [abc_number *= '150'] {\n"
    ],
    "errors_with_context": [
        {
            "type": "unknown",
            "message": "style0:26:8 Invalid code: [abc_number *= '150'] {\n",
            "layerIndex": 0
        }
    ]`

before I used the CSS3 syntax "*=" to get a wildcard search  I used the example below, which worked without problems: 

I did it like that
```
#test [abc_number = '150'] 
// style here
#test [abc_number = '150K'] 
// same style here
#test[abc_number = '150KF'] 
// same style here
```
to have a specified style. However I noticed that its far more comfortable to use CSS3 like this:
`#test [abc_number *= '150'] `
to get the same result.

So my question is - Does Carto not support this CSS3 feature?

It would be very nice to get it to work with this feature because It's just too much effort to do it without.

**Comment by xavijam** [comment]
Hi @braintuts, CartoCSS is similar to CSS syntax, but it is not the same, so it is possible all filters you are used to with CSS are not available. A better documentation about selectors in CartoCSS is [here](https://tilemill-project.github.io/tilemill/docs/guides/selectors/).
