### ISSUE TITLE
No image size limit in organization assets

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#11484]
### Context
If you try to upload a huge image to the user assets endpoint (> 1024x1024) you get an error back. This validation is not performed for organization assets.

This has no impact now, but will probably be important when we remove the icon styling feature flag. We should decide if we need a similar limit (or even a smaller one, since org assets are only used for markers right now).

### Steps to Reproduce
1. Go to organization settings
2. Try to upload an image larger than 1024x1024

### Current Result
It is uploaded 

### Expected result
It should fail

**Comment by juanignaciosl** [comment]
Closing automatically because of inactivity. If anybody considers that this still important, please reopen and it'll be prioritized.
