### ISSUE TITLE
Optional Type guessing at import UI

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#1148]
Right now, the only way to avoid it is using the Import API, but this workaround is not easy for some users.

We've had multiple tickets about this, for example:
https://cartodb.supportbee.com/tickets/3727186
https://cartodb.supportbee.com/tickets/3615729
https://cartodb.supportbee.com/tickets/3570980
...

This provokes for example issues with zipcodes, as it removes the zeroes at the left.

**Comment by saleiva** [comment]
Designed in the new dashboard

**Comment by saleiva** [comment]
![screen shot 2015-01-29 at 16 11 15](https://cloud.githubusercontent.com/assets/132149/5959812/7907bac4-a7d1-11e4-9894-8cd4201df5e8.png)

cc @xavijam
