### ISSUE TITLE
When styling by icon and category, clicking on the icon takes you to the color picker

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#11499]
### Steps to Reproduce

1. Create a map styling by category and using icons on them
2. After styling the points, click on the small icon close to the color indicator.

### Current Result
It takes you to the color picker until you click on the icon on top right again

### Expected result
Clicking on the icon should take you to the icon picker.

**Comment by matallo** [comment]
it's working as expected, the only thing happening is the target not being large enough so if you click in the whole you show the color picker (see attached)

![colorpicker](https://cloud.githubusercontent.com/assets/36676/22878252/63e49884-f1d9-11e6-84f8-83e48d7258b4.gif)

**Comment by saleiva** [comment]
Ok, so it should be easy right?

**Comment by nobuti** [comment]
Picking this

**Comment by nobuti** [comment]
Already in production. Closed by https://github.com/CartoDB/cartodb/commit/c2f8b2480110213a7f81d75046b422f42e4f45c5.
