### ISSUE TITLE
Exponentially / power law distributed  datasets don't work well with histograms/legends 

### ISSUE THREAD

**Issue by stuartlynn** [CartoDB/cartodb#11495]
### Context
*Please explain here below what you were doing when the issue happened*

Adding a histogram widget to a dataset that is exponential in nature means that the first bin tends to contain all the instances of the variable. This makes the histogram widget particularly useless and isn't resolved by zooming (because of the nature of exponentials)  

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Add a widget for an exponential dataset 
2. 
3. 

### Current Result
*Please describe here below the current result you got*
The first bin if the histogram contains 99.9% of the data points which makes filtering and auto styling pretty usless
 

### Expected result
*Please describe here below what should be the expected behavior*

To see a more sensible distribution, usually in data analysis we would apply log based bins rather than equal interval bins to the histogram construction. This allows a more natural view of the data 

### Browser and version
*What internet browser (Chrome, Firefox, etc) and version was you using and version* 

 Doesn't matter

### .carto file
*Don't forget to rename .carto file to .zip file to be able to upload to github*

 

### Additional info
*Please add any information of interest here below*

**Comment by saleiva** [comment]
I believe this is a dupe. Poor @AbelVM has been crying for this for a long time now...

**Comment by stuartlynn** [comment]
Do we have any plans to resolve it? Would be a relatively quick fix. Just a log tab on the histogram widget interface and some slightly different binning logic

**Comment by saleiva** [comment]
yep, there is something designed around... will look for it

**Comment by stuartlynn** [comment]
Thanks

**Comment by AbelVM** [comment]
You can check the FR at https://github.com/CartoDB/solutions/issues/684
