### ISSUE TITLE
Widgets/styling to interact with Array and JSON properties

### ISSUE THREAD

**Issue by stuartlynn** [CartoDB/cartodb#11496]
The widgets and CARTO in general assume that each geometry has only one value for each column for example a table which looks like: 

|cartodb_id| the_geom| some_category| magnitude|
|----------|-----------|---------------|------------|
| 1               |   geom1     | cat_1               | 10               |
| 2              |  geom1     | cat_2               | 20               |
| 3              |   geom2     | cat_1               | 3                 |
| 4              |  geom2    | cat_2               | 4                 |

This has always struck me as unfortunate because it feels like there should be one row per geographic entity with serial attributes like this stored as JSON, hstore or Arrays. A few problems with the current set up are:

- First, it duplicates geometries, which becomes an issue when the underlying data is complex polygons or lines (think road networks). It blows up the size of the dataset and impacts rendering time pretty badly. 

- It means we can't do AND type selections with the category widget, for example, filter and show me where a point has both category_1 and category_2 as each row only specifies one category but multiple rows actually represent the same semantic location (store, district etc)

- It means data gets hidden on overlapping polygons, so if we are styling by category, we only see the one that happens to be on top of the map. 

- For high cadence time series where the geometry locations don't change it causes us to store a lot of redundant geometries. 

One solution to this would be to make Arrays or JSON objects first class citizens in CARTO. Allow a table to look like 

|cartodb_id| the_geom| magnitude_for_cat| 
|----------|-----------|---------------|
| 1               |   geom1     |{ cat_1 : 10, cat_2 : 3} |
| 2              |   geom2     |{ cat_1 : 3, cat_2 : 4}      |

or alternatively 

|cartodb_id| the_geom|cat_names| cat_values |  
|----------|-----------|---------------|--------|
| 1               |   geom1     |[cat_1, cat_2 | [10,3] 
| 2              |   geom2     |[cat_1, cat_2 | [3,4] |

It moves us away from the simplicity of a pure row based setup but I think it opens up some use cases that we currently have to work around by having many rows for each geom. 

Would love to discuss how this might work and if there is any appetite to build this out on CARTO

**Comment by andrewbt** [comment]
@saleiva @noguerol As roadmap feedback, this would be directly relevant to the Domo / Clear Channel opportunity @joepringle and @SebastienBu are currently working on reeling in for us.

**Comment by stuartlynn** [comment]
Would be really useful for DO as well

**Comment by andrewbt** [comment]
@SebastienBu has another opportunity (Native Touch - mobile ads company) where this would be relevant

**Comment by saleiva** [comment]
Thanks @andrewbt, for the time being we will keep this on the backlog as we have many many other things prioritized as well. Please, if you think this is gaining relevance, let's talk about it during next what's next meeting

**Comment by andrewbt** [comment]
@saleiva understood, just recording specific deals here for future reference/prioritization. Are the "what's next" meetings open to Solutions? Thought it was just leadership, but would love to attend!

**Comment by saleiva** [comment]
Sure they are! @danicarrion is your man there!

**Comment by andrewbt** [comment]
JSONB and Hstore in CARTO vamos!

@hannahblue @inigomedina @alonsogarciapablo I'd rank this one pretty highly and I'm sure Stuart / Data team would too. Let's not let it turn stale.

**Comment by hannahblue** [comment]
This would be useful for Data Observatory data. The functionality would be more of an Engine/Builder thing though, @inigomedina

**Comment by andrewbt** [comment]
+1

**Comment by alrocar** [comment]
Won't fix
