### ISSUE TITLE
Styling with icon should change the point size if it's smaller than 20

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#11498]
### Context
Right now, if styling with icons without having a big marker size, you can't even see the change.

### Steps to Reproduce

1. Enter to a points map with default styling
2. Select an icon to style with

### Current Result
You can barely appreciate the changes

### Expected result
I'd expect my markers to get bigger.

**Comment by matallo** [comment]
In case you edit the style "per value", you can have mixed markers and images, and currently I think we only support a common marker width/height for them all (see attached).

Shall we have bigger markers in this case?

![screen shot 2017-02-13 at 11 02 13](https://cloud.githubusercontent.com/assets/36676/22878928/f075cd98-f1db-11e6-8e73-6ef0c97a3ba2.png)

**Comment by saleiva** [comment]
I think so...

**Comment by saleiva** [comment]
I can do this one, assigning to me :)

**Comment by xavijam** [comment]
💃
