### ISSUE TITLE
Removed icon doesn't disappear if you don't select a new one

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#11510]
### Context
When removing a custom icon that has been previously uploaded, icon persists in the map if you close the modal without selecting a new one.
 

### Steps to Reproduce
1. Style a point layer with a custom icon by opening the modal window, uploading and selecting it
2. Open the modal window, remove the icon, close the modal

### Current Result
The removed icon is still rendered on the map

### Expected result
The map should be rendered with a default bubble

### Browser and version
Chrome 56.0.2924.87 (64-bit)
 

### .carto file
 
[John Snow Test Map (on 2017-02-10 at 15.47.01).zip](https://github.com/CartoDB/cartodb/files/767129/John.Snow.Test.Map.on.2017-02-10.at.15.47.01.zip)

**Comment by matallo** [comment]
this is also happening with custom Basemaps, I don't see it exactly as a _bug_, but as an _enhancement_, as similar as they can seem they are a bit different things for me (at least in code)

**Comment by noguerol** [comment]
How this could be an enhancement? I mean, the "lets not break things" rule only makes sense when deleting an asset affects unforeseen dependencies, so we prevent users complaining about unexpected broken maps. But when an icon is removed not from the organizational view but for a map, it makes sense the action is bond to that map and because of that immediately reflected.

**Comment by javierarce** [comment]
I think icons are cached, but that would mean that they would persist only for a given time. I agree with @noguerol and think that this is issue is correctly labeled as bug, but maybe I'm missing something, @matallo.

**Comment by matallo** [comment]
ok then, just raising my concerns regarding the code [1], in that case I think we should revisit the basemaps which behave in the same way:

1. add custom basemap
1. remove custom basemap

the basemap is applied when adding the custom basemap but remains in the map once is removed, even if it is not under the custom basemaps category anymore

---

[1] not the UI, where I'd agree that change makes sense, the code is not breaking now, when I said I saw it as an enhancement I meant that is something just not implemented yet

**Comment by nobuti** [comment]
Already in production. Closed by https://github.com/CartoDB/cartodb/commit/c27faf3a279c512f49c840f8c47abbfc2b35e600.
