### ISSUE TITLE
Use TIS instead of Varnish for invalidation

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#11513]
We have not moved from Varnish to TIS invalidation in Rails yet.

- [ ] Remove calls to Varnish.
- [ ] Remove `net-telnet` gem (see #11453).

cc @rochoa @xavijam @CartoDB/builder-backend

**Comment by rochoa** [comment]
What kind of rails-varnish invalidations do we do?

**Comment by juanignaciosl** [comment]
For example, user vizjsons are invalidated on user or visualization changes.

**Comment by javitonino** [comment]
This is definitely something we want to do at some point. Keeping it open for now.

**Comment by javitonino** [comment]
We got this inside a project. Closing.
