### ISSUE TITLE
Go directly to the custom icon tab of the modal if the user has a custom one selected

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#11519]
### Context

Right now the icon modal shows the Icon tab (the one that shows the Maki icons) in all the cases. It would be nicer to show the custom tab if the user has a custom icon selected.
 
### Steps to Reproduce

1. Style by a custom marker
2. Close the modal
3. Open the icon modal again

### Current Result
The modal shows the list of default icons

### Expected result
The modal should show the tab of custom icons ('Your uploads').

**Comment by xavijam** [comment]
That's a good one!
