### ISSUE TITLE
Georeference by lat/lon analysis should only accept numeric columns

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#11511]
If you try to create a georeference analysis by latitude/longitude, you can choose the longitude/latitude columns from any column in the dataset.

However, if you select anything that is not numeric, map instantiation will fail:
`[{"type":"analysis","message":"function st_makepoint(text, text) does not exist","analysis":{"id":"b1","type":"georeference-long-lat"}}]});`
 
The error occurs because the `st_makepoint` function only takes numbers. An easy, nice to have fix, but nothing critical, of course.

**Comment by javitonino** [comment]
Still an issue. cc @ivanmalagon @ramiroaznar

**Comment by piensaenpixel** [comment]
yes please! it's a bit frustrating

**Comment by rubenmoya** [comment]
In production! 🚀
