### ISSUE TITLE
Column selector does not save unless click outside the popup

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#11521]
### Context
When selecting columns to be joined in a _Join columns from 2nd layer_ analysis, the columns selected by the user are lost if you click on _APPLY_ before clicking outside the column selector.
 
This is frustrating for the user, especially if they had manually selected a lot of columns

### Steps to Reproduce

1. Create a map with two layers that could be joined. You could use [this .carto file](https://github.com/CartoDB/cartodb/files/771535/easy_join_example.on.2017-02-13.at.15.50.04.carto.zip)

2. Add the JOIN analysis and go forward with the analysis setup
3. If you're using the attached .carto, select `sov_a3` and `iso3` from populated places and world borders respectively as foreign key
4. Select some columns to be joined and hit _APPLY_ **before clicking outside the popup**

### Current Result
Selected columns defaults to `0` if you don't click outside the popup before clicking _APPLY_
 

### Expected result
Selected columns should persist even if the popup wasn't closed before the user clicks on _APPLY_ 

### .carto file
[easy_join_example.carto.zip](https://github.com/CartoDB/cartodb/files/771535/easy_join_example.on.2017-02-13.at.15.50.04.carto.zip)
 
cc/ @saleiva

**Comment by saleiva** [comment]
This is soooo frustrating :D

**Comment by xavijam** [comment]
In prooooduction!

**Comment by saleiva** [comment]
VAMOS!

**Comment by ernesmb** [comment]
🚀
