### ISSUE TITLE
Geometry edition button not disappearing

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#11524]
### Context

Certain user actions may produce the geometry edition button to remain on the map, even after clicking on other parts of the screen. 

 

### Steps to Reproduce

1. Create a map
2. Click on the layer and open _POP-UP_ tab, select a popup template to see the list of columns to be shown
3. Click on any map feature to see the geometry edition button
4. Click on a checkbox to activate a column
5. Click on the text input and drag the cursor from the input to a zone **inside the map** 

In order to reproduce the issue, the key is clicking only in the checkbox and dragging the cursor directly on the map. Any other action will make the button disappear

### Current Result

Geometry edition button does not disappear

 

### Expected result

The button should disappear when clicking anywhere on the screen. 

 
cc/ @saleiva

**Comment by rubenmoya** [comment]
I've been doing some research, and removing [this preventDefault()](https://github.com/CartoDB/cartodb/blob/master/lib/assets/core/javascripts/cartodb3/editor/layers/layer-content-views/infowindow/infowindow-field-view.js#L92) solves the problem, but just for the checkbox, not for the slider for example, which has the same problem.

I'm not sure if the preventDefault is needed in this case, but I don't think that removing it is the best solution.

Let's wait and talk about it with @xavijam.

**Comment by nobuti** [comment]
This is not as easy as it seems, in addition to the elements mentioned above, there are others that prevent the default's event and avoid propagation.

**Comment by xavijam** [comment]
Yeah ^^^. I'd not pay so much attention to this issue right now. Let me remove it to the Kanban for the moment. Let's tackle it when needed.
