### ISSUE TITLE
Delete dataset doesn't display the preview of the maps

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#11526]
### Steps to Reproduce

1.  Create a new map (dropping the attached file is good enough).
[guess_country_reduced.csv.zip](https://github.com/CartoDB/cartodb/files/773672/guess_country_reduced.csv.zip)
2. Go to Dashboard --> Dataset
3. Delete the dataset

### Current Result

The modal is opened, but the preview of the map doesn't work.

### Expected result

There's a preview.

### Additional info

It fails because a 403 error:

![captura de pantalla 2017-02-14 a las 10 47 09](https://cloud.githubusercontent.com/assets/932968/22923878/5f0d46c4-f2a3-11e6-9b6d-c44930a765e0.png)
![captura de pantalla 2017-02-14 a las 10 47 16](https://cloud.githubusercontent.com/assets/932968/22923881/609e8c96-f2a3-11e6-9639-136443eac59d.png)

@xavijam I haven't done more triage, I don't know if it's back or front yet.

**Comment by xavijam** [comment]
Hey, I don't understand the steps.
> Go to dashboard --> Datasets.

How do you delete a map from datasets section?

**Comment by juanignaciosl** [comment]
Fixed title and steps, sorry (`comment.gsub(/map/i, 'dataset')`).

**Comment by xavijam** [comment]
:+1:

**Comment by juanignaciosl** [comment]
It uses a map link `https://team.carto.com/u/juanignaciosl/viz/fff8f65e-fa7e-11e6-b264-0ecd1babdde5/map` instead of the preview.
