### ISSUE TITLE
Recognize more date formats when importing data

### ISSUE THREAD

**Issue by rbrtmrtn** [CartoDB/cartodb#11537]
### Context
*Please explain here below what you were doing when the issue happened*

 I was importing a CSV file via the Carto web interface.

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Import a new dataset from file

### Current Result
*Please describe here below the current result you got*

 Dates, for example `09/17/1993 00:00:00`, were imported as strings.

### Expected result
*Please describe here below what should be the expected behaviour*

It would be very helpful if the column were created as a `TIMESTAMP`.

### Browser and version
*What internet browser (Chrome, Firefox, etc) and version was you using and version* 

 n/a

### .carto file
*Don't forget to rename .carto file to .zip file to be able to upload to github*

 n/a

### Additional info
*Please add any information of interest here below*

**Comment by saleiva** [comment]
cc @rafatower

**Comment by rafatower** [comment]
Hey @rbrtmrtn thanks for your report.

Where the type guessing takes place is in the underlying [CSV GDAL driver](http://www.gdal.org/drv_csv.html) we use to import CSV files and many other formats. It is done through the `AUTODETECT_TYPE` option and IIRC the dates are meant to be in one of these formats to be recognised:
> Date (YYYY-MM-DD), Time (HH:MM:SS+nn), DateTime (YYYY-MM-DD HH:MM:SS+nn)

(I think the rails side of things used to have some heurisitics for date/datetime recognisition that we removed in favor of gdal detection. See the [Typecaster](https://github.com/CartoDB/cartodb/blob/fca87ab3b7c44529553cd1b059b0eaaa82d55004/services/importer/lib/importer/typecaster.rb). Mind that that apporach is much slower than gdal approach)

@saleiva it is up to you whether we should push to support other types as a new feature/enhancement.

**Comment by saleiva** [comment]
@rafatower guessing is a key part of our workflow. I'd love to keep advancing on this, but of course it really depends on the cost. Can we open an issue in the correct repo and keep talking there?

**Comment by rafatower** [comment]
The right repo is this one: https://trac.osgeo.org/gdal

@rouault I tried to create a ticket there but I no longer have TICKET_CREATE privileges. Here's the content of the ticket I wanted to create:
```
Support more date and datetime formats for AUTODETECT_TYPE option

The `AUTODETECT_TYPE` option of the CSV driver does a great job figuring out the types of the columns of an input CSV file but can be improved by adding more formats to it.

At present and if I'm not mistaken, the algorithm for type detection only supports the ISO 8601 Notation.

Here are the types supported by PostgreSQL:
https://www.postgresql.org/docs/current/static/datatype-datetime.html#DATATYPE-DATETIME-DATE-TABLE

The algorithm could be tweaked to support those formats that do not have ambiguity with other types (integer or float), so that, for instance, the following CSV would recognise the column mydate as of type datetime:
{{{
id,mydate,value
1,09/17/1993 13:20:51,42
2,09/17/1994 13:27:40,43
}}}

I think the code implementing it is around these lines:
https://trac.osgeo.org/gdal/browser/trunk/gdal/ogr/ogrsf_frmts/csv/ogrcsvlayer.cpp?rev=37371#L1160
```

What do you think? we can keep the discussion about feasibility and estimates off this public repo

**Comment by rouault** [comment]
@rafatower Are you properly authenticated as 'rtorre' in Trac ? If so, you should have TICKET_CREATE privileges. Supporting more datetime format seems reasonable although that in the above example there might be an ambiguity if it was 02/03/1993 instead. Would it be month day year or day month year ? The link to the postgres doc mentions several modes YMD, DMY, MDY, so perhaps we should have an option to specify this date mode as well in case there are ambiguities ?

**Comment by rbrtmrtn** [comment]
Thanks @rafatower @saleiva , makes sense now that the API (or GDAL) is expecting more of a well-known format. I could do a little munging to get those dates into ISO-8601, but just wanted to bring this up as a potential/future enhancement as it would make some of our workflows a bit easier.

**Comment by rafatower** [comment]
@rouault thanks a lot for your comments, some answers in line:

> Are you properly authenticated as 'rtorre' in Trac ? If so, you should have TICKET_CREATE privileges.

Yes. Basically I'm experiencing the exact same problem I had the last time: I can log in as `rtorre`, it let's me fill the new ticket form but when I submit it it returns a 403 Forbidden with the text "TICKET_CREATE privileges are required to perform this operation on Ticket #None. You don't have the required permissions." and I appear to be logged out.

> Supporting more datetime format seems reasonable although that in the above example there might be an ambiguity if it was 02/03/1993 instead. Would it be month day year or day month year ? The link to the postgres doc mentions several modes YMD, DMY, MDY, so perhaps we should have an option to specify this date mode as well in case there are ambiguities ?

You're right. This is the most extreme case (from the postgres link above):

```
01/02/03	January 2, 2003 in MDY mode; February 1, 2003 in DMY mode; February 3, 2001 in YMD mode
```

@saleiva this kind of ambiguity cannot be solved without making risky assumptions or letting the user add a bit of metadata (format, locale, whatever). I see the following options here:

- Leave it as it is and sick to current ISO 8601 (YYYY-MM-DD) (we should improve our docs a little in this regards)
- Use ISO 8601 and assume MDY, or the machine locale, or any other configurable date style in the case of ambiguity (in our setups, postgres assumes MDY, and it is used when a column is cast from text to date/datetime).
- Let the user add that metadata (format or locale). Or better let the user define the type of the columns and the format of the dates (types of columns are nicely covered by [GeoCSV format](https://giswiki.hsr.ch/GeoCSV), not format of dates though).This reminds me of this ticket https://github.com/CartoDB/cartodb/issues/4282

I'd love to hear your input before requesting any enhancement in GDAL.

@rbrtmrtn thanks for the feedback, much appreciated.

**Comment by rouault** [comment]
> Yes. Basically I'm experiencing the exact same problem I had the last time: I can log in as rtorre, it let's me fill the new ticket form but when I submit it it returns a 403 Forbidden with the text "TICKET_CREATE privileges are required to perform this operation on Ticket #None. You don't have the required permissions." and I appear to be logged out.

How did we solve the issue last time ? Can't remember. Anyway I've explictly granted you TICKET_CREATE rights. Hopefully that should work

**Comment by rafatower** [comment]
> How did we solve the issue last time ? Can't remember. Anyway I've explictly granted you TICKET_CREATE rights. Hopefully that should work

You created a ticket for me and Sandro fixed it: https://trac.osgeo.org/osgeo/ticket/1745

Also I couldn't post comments in that ticket at the time, so I sent the contents of the comments I wanted to make through mail to you and Sandro, with the subject `Re: [OSGeo] #1745: Authenticated user cannot create ticket on GDAL Trac`.

I suggest to reopen and keep tracking trac issues there if needed (no pun intended).

I'm not opening any ticket in trac yet, until we figure out the requirements and scope. We can keep the discussion about "high level" (product) requirements here and once that's clear I can write up the requirements for gdal csv driver in a trac ticket.
