### ISSUE TITLE
Clicking the label on a checkbox should activate/deactivate it

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#11535]
### Context
We've seen lots of user clicking on labels for activating/deactivating checkboxes lately. Although it's not a blocker (they end up clicking on the checkbox) it generates some friction.

### Expected result
Clicking on checkboxes should act like clicking on the checkbox itself.

cc/ @noguerol

**Comment by xavijam** [comment]
That's a typical one and I agree we should "fix" it.
