### ISSUE TITLE
Changing widget type to histogram doesn't show up the error field on column selector even if it's empty

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#11536]
### Steps to Reproduce

1. Add a formula widget 
2. Change type to histogram

### Current Result
Widget don't show anything because column input is not specified.

![screen shot 2017-02-14 at 18 37 09](https://cloud.githubusercontent.com/assets/132149/22941210/e7145738-f2e4-11e6-9b69-6ab65fb0c7a9.png)

### Expected result
We should show an error status on that input, to show the user that if column is not selected, widget will not work. Another option is to select another _numeric_ column by default.

**Comment by ivanmalagon** [comment]
Shipped! 🚀
