### ISSUE TITLE
Add standard deviation as an aggregation method on Formula widgets

### ISSUE THREAD

**Issue by stuartlynn** [CartoDB/cartodb#11538]
Often it's important not just to know the mean of a variable but its standard deviation. Would be really cool if the formula widget had the ability to show the standard deviation of a variable. This can be calculated with the stddev_pop(expression)function in PostgreSQL.

This would allow a user to create both a mean and standard deviation widgets that give a fuller understanding of the dataset.

**Comment by talos** [comment]
👍

**Comment by saleiva** [comment]
You mean as an aggregation method? Sounds pretty good!

**Comment by stuartlynn** [comment]
Yeah totally.

**Comment by saleiva** [comment]
hey @javisantana @rochoa what do you guys think about this?
