### ISSUE TITLE
Expose Google Maps API in embeds

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#11541]
From #11447. Branch upon `google-maps`.

Expose visualization owner `google_maps_key`. After talking to @alonsogarciapablo , probably the better way is at a window-level `var googleMapsKey`, just like `authTokens` is.

`user.google_maps_key` already takes into account returning user's or organization's key.

PS: in addition, check if there's a quick fix for `var authTokens = JSON.parse('null');` that [is generated in this map](https://juanignaciosl.carto.com/builder/fb4b07b8-b401-4b59-9197-7f0f88625e79/embed?state=%7B%22map%22%3A%7B%22ne%22%3A%5B28.844673680771795%2C-27.70751953125%5D%2C%22sw%22%3A%5B48.42920055556841%2C10.590820312499998%5D%7D%2C%22widgets%22%3A%7B%22064e4344-50a5-40f4-ac8c-ef6ef1611d18%22%3A%7B%22normalized%22%3Atrue%7D%7D%7D), which doesn't seem right.

**Comment by javitonino** [comment]
Should this be exposed only for embed? Or Builder as well?

**Comment by alonsogarciapablo** [comment]
[We've access to `current-user` in the case of Builder](https://github.com/CartoDB/cartodb/pull/11447/files#diff-88095d79eb397b7ebbf5ddbe214e53d7R21), so we're good there.

**Comment by juanignaciosl** [comment]
@alonsogarciapablo currently `google_maps_key` contains a query string such as `"client=<client id>"` or `"client=<client id>&channel=<channel id>"`. Please confirm that it's suitable for Google Basemaps or it needs some parsing (it should be done in backend).

**Comment by alonsogarciapablo** [comment]
Yes, that should still work (you can read about it [here](https://developers.google.com/maps/documentation/javascript/get-api-key#client-id))

**Comment by javitonino** [comment]
Well, we also have `google_maps_private_key` which has the api key, but I guess we prefer to use the clientid + domain registration (the client would have to whitelist *.carto.com)

**Comment by alonsogarciapablo** [comment]
From reading the documentation (https://developers.google.com/maps/documentation/javascript/get-api-key), clients could potentially use any of the two methods for authentication. I guess it's up to them. I didn't know we had both options... Perhaps we could do the following:

- If user has `google_maps_key` -> use it.
- Else 
  - If user has `google_maps_private_key` -> use it.
  - Else
    - Do not load the script (and provide some visual feedback, as suggested in https://github.com/CartoDB/cartodb.js/issues/1577)

What do you guys think?

**Comment by alonsogarciapablo** [comment]
Whatever we decide, we should do it for embeds and BUILDER. Perhaps worth extracting this logic into a helper/partial...

**Comment by javitonino** [comment]
In the editor, we only used the query string. Using the API key could be dangerous, as that gives access to a whole bunch of stuff. IMHO, we should be imposing best practices in our users and I would go for the client_id only route.

**Comment by javitonino** [comment]
I think we also need to add this to the datasets view, as there is a "preview" button there that displays the canonical map (and it does not appear to be an iframe). Am I right? @xavijam

**Comment by javitonino** [comment]
Confirmed that the dataset preview map is rendered directly in the page with cartodb.js (createVis on the canonical vizjson). So we need google there as well.

**Comment by juanignaciosl** [comment]
@alonsogarciapablo , could you confirm that? ^ In some conversations you said that cartodb.js doesn't always need it.

**Comment by alonsogarciapablo** [comment]
Yes, we'll also need to load the Google Maps library:

- [ ] In user's public pages (eg: https://team.carto.com/u/mamataakella/me)
- [ ] In user's public maps pages (eg: https://team.carto.com/u/mamataakella/maps)
- [ ] In user's public datasets pages (eg: https://team.carto.com/u/mamataakella/datasets)
- [ ] In public dataset views (eg: https://team.carto.com/u/mamataakella/tables/usdm_20151103/public)

Good catch @javitonino!

**Comment by javitonino** [comment]
@alonsogarciapablo Good ones! Those already had the api loaded (since they are old pages and they are already prepared for Google). Only difference is they use v3.12 of the API, but they use cartodb.js v3 as well, so I think it's okay if we leave them as is until we redo the public pages.

**Comment by alonsogarciapablo** [comment]
@dgaubert just found another place where we need to load the Google Maps library:

- [ ] Current user's dashboard (eg: https://team.carto.com/u/mamataakella/dashboard)

**Comment by alonsogarciapablo** [comment]
Actually, we use static images there, so forget about it.

**Comment by javitonino** [comment]
Why do we need it in the dashboard? I cannot find any map there, only static images of them.

**Comment by javitonino** [comment]
Ooops, cross posting. ✨

**Comment by alonsogarciapablo** [comment]
We discovered that we're loading the previous version of the library (v3.12) in the user's dashboard. It's not required so we can :fire: it. The v3.12 version of the library is deprecated and trying to load it raises a JS error, which pops up in the console:


v3.12

**Comment by alonsogarciapablo** [comment]
Taking about trying to load v3.12... There's an issue which is closed but still not fixed (https://github.com/CartoDB/cartodb/issues/10927). Perhaps this is a good opportunity to kill 2 birds with one stone... cc: @xavijam. Nobody is complaining about it so it's probably not really important but I just wanted to point it out since it's related.

**Comment by javitonino** [comment]
But those error are because the visualization owner doesn't have a google api key set, nothing to do with the version I think.

I took a quick look, and the problem is that the old code checks: <% if @visualization.map.provider == 'googlemaps' %> to see if it should load Google, but if the keys are missing, then that error happens. I think that's good behaviour, maybe the new code should also check the map provider, not only the api key availability. 🤔 Opinions?

**Comment by alonsogarciapablo** [comment]
The thing is that the map provider might be Leaflet when BUILDER is loaded, but the user might want to switch to a Google Maps basemap, and the Google Maps library should be loaded in that case.

**Comment by javitonino** [comment]
Ok, so:
- For builder we need to load google maps if the user has it configured
- For embed and dataset, we can load it only when the corresponding map has google maps provider

Is that right?

**Comment by alonsogarciapablo** [comment]
Yep.
