### ISSUE TITLE
Disable geometry edition button in read-only layers

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#11543]
After a small discussion in #10905, @saleiva suggested to show always the geometry edition buttons but disabling them in case of read-only layers. Comment link: https://github.com/CartoDB/cartodb/issues/10905#issuecomment-278362912

![image](https://cloud.githubusercontent.com/assets/1078228/22969763/f790e186-f36f-11e6-9e1a-55f13047b421.png)

Current result is that we hide that button.

![image](https://cloud.githubusercontent.com/assets/1078228/22969802/16295cfe-f370-11e6-9038-53952232e5d7.png)

A read only layer can be obtained doing an analysis on that layer.

Not sure if we have a defined style for disabling those kind of button. Summoning here @CartoDB/design

**Comment by saleiva** [comment]
I don't think so, @urbanphes ?

**Comment by noguerol** [comment]
i would make it dissapear. let's go for the cleaner option.

**Comment by noguerol** [comment]
But, to make this clearer, in the layer onboarding i'll draw a fake add geometry button that appears in that step, so we can also give a hint to those users that unfortunately trigger the onboarding with a readonly layer

**Comment by urbanphes** [comment]
@ivanmalagon the method for disabled buttons is low the opacity to 24%.

![5 buttons](https://cloud.githubusercontent.com/assets/14546701/23994037/5d822574-0a43-11e7-9cba-48255681af36.png)

... but in this case can be a bit of weird because on the background we have the basemap.


I agree with @noguerol about disappear the button instead of disabled the button. IMHO is better to offer to the user only that they can do.

**Comment by saleiva** [comment]
I would not remove the buttons so we embrace visibility and discovery of the UI.

**Comment by noguerol** [comment]
IMO hiding a layer is an active action and a need for certain use cases, in which case I don't find a need for either encouraging that user to make it visible nor discover the rest of the UI, while I agree with @juanma that offering what is not available is normally frustrating.

**Comment by saleiva** [comment]
It's not an active action, this also happens when a layer is sync (for example)

**Comment by noguerol** [comment]
Hiding is still an action. If a layer is synced it makes no sense either to show the buttons. But hey, let's not block this: @saleiva your call

**Comment by saleiva** [comment]
The thing is that showing this kind of actions gives us a possibility to explain the steps needed to enable those options. In this case a) sync tables can be edited if being changing options to non-sync and b) read-only tables can be edited if duplicated in the users account.

**Comment by noguerol** [comment]
ok.

**Comment by nobuti** [comment]
Deployed
