### ISSUE TITLE
Proper error message when ArcGIS server does not support query capability

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#11544]
### Context

Trying to import using the ArcGIS connector, from an ArcGIS server that actually has the needed methods for the import to succeed disabled in its configuration.

### Steps to Reproduce

1. New dataset
2. Select ArcGIS Server connector
3. Type this URL: https://api.cityofkingston.ca/gis/rest/services/Carto/CapitalProjects_Carto/MapServer/1
4. Submit
5. Connect dataset

**Note**: mind that the server configuration can change anytime. If that's the case it should be testable by mocking the response to [this URL](https://github.com/CartoDB/cartodb/blob/c32b92e4ba6fd9a7230c05b78bb2f6392b25284e/services/datasources/lib/datasources/url/arcgis.rb#L20) with this:

```js
{
  "error": {
    "code": 400,
    "message": "Requested operation is not supported by this service.",
    "details": [
      "The requested capability is not supported."
    ]
  }
}
```

### Current Result
 
Import fails. The user gets a [1011 error code](https://github.com/CartoDB/cartodb/blob/c32b92e4ba6fd9a7230c05b78bb2f6392b25284e/lib/cartodb/import_error_codes.rb#L67), which is wrong.

The import error log says: `Missing data: key not found: "objectIds"`.

### Expected result

The user should receive proper feedback to let him fix the issue on their side, something in the lines of:
```ruby
  12345 => {
      title: 'ArcGIS server misconfiguration',
      what_about: 'We could not import your data from the ArcGIS server because the server has the "execute queries capability" disabled. Please contact your ArcGIS server administrator.',
      source: ERROR_SOURCE_USER
    },
```

**Comment by rafatower** [comment]
@jorgesancha this is a stereotypical example of what an enhancement is IMHO.

**Comment by jorgesancha** [comment]
:+1:
