### ISSUE TITLE
Join analysis form render a ghost error tooltip

### ISSUE THREAD

**Issue by nobuti** [CartoDB/cartodb#11550]
### Context

![screen shot 2017-02-15 at 17 07 04](https://cloud.githubusercontent.com/assets/1366843/22983120/6e0fc102-f3a1-11e6-9fad-b5c10b663fa8.png)

### Steps to Reproduce

1. Select a join analysis
2. Change join type to left

### Expected result
Only one tooltip should be shown

**Comment by ramiroaznar** [comment]
Duplicated https://github.com/CartoDB/cartodb/issues/12098 (closing this because the other has more detail)
