### ISSUE TITLE
Uploaded file remains in `/tmp/imports` after import

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#11551]
### Context

This was discovered **in staging** during acceptance of https://github.com/CartoDB/cartodb/pull/11516

When import a dataset from an url for example, the file is downloaded onto the box and then imported into the user's db. It's expected that once the import to the user's db is successful, the file is deleted. This is not the case apparently.

### Steps to Reproduce

1. Upload a dataset

### Current Result

The uploaded dataset remains in `/tmp/imports`

### Expected result

The uploaded dataset is removed once imported into the user's db.

**Comment by javitonino** [comment]
This is known in SaaS and there are scripts that clean up this periodically. Maybe this is needed for onpremise, but maybe it's better to use the same approach (cleaning script). cc @rporres in case he can provide more info.

@guido: does this happens always? or only when the import fails? maybe only when it is a compressed format?

**Comment by rporres** [comment]
If I understand correctly, `/tmp/imports` corresponds to `imports.unp_temporal_folder` key, the third copy of the upload file :scream:

There's indeed a script in the SaaS to delete that, so we could follow the same approach, although I prefer software that cleans its own mess

**Comment by juanignaciosl** [comment]
We should review this, but there should only be 2 copies: the uploaded file, and the S3 one (needed for the queues). In fact for the SaaS [upload could be done to S3 from the browser](http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingHTTPPOST.html).

If there's no reason to keep it we can improve the codebase to remove it, although the cleanup script is still useful, just in case something breaks.

**Comment by javitonino** [comment]
There are three copies if S3 is disabled:
- Temporal uploaded file (Rack)
- File in /uploads directory (can be in S3 if configured)
- Temporal file for the queue (created by downloader, needed as the queue can't work directly off S3)

About cleaning up temporal files, I would check with @rafatower first. Maybe it's useful to have the temporal importer file to stick around for debugging purposes. In that case, maybe a config flag is the best bet.

**Comment by rafatower** [comment]
I'm ok with deleting those temp files. For debugging if you don't own the file, you should ask the owner instead of relying on lurking temp files.

**Comment by gfiorav** [comment]
Very much agree with @rafatower 

Let's make the software clean up after itself :)
