### ISSUE TITLE
Incorrect copy in delete icon feature under Organizational settings

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#11565]
### Context
Under organizational settings, the copy for deleting an icon is in plural ("delete icons"), while it only deletes one icon, misguiding the user as it seems it will erase them all
 
### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. As an organizational admin, login into settings page
2. Upload an icon
3. You can only delete the icon through the "delete icons" cta

### Current Result
CTA states "delete icons"
 
### Expected result
it should be in singular: "delete icon"

**Comment by javierarce** [comment]
Where's the PR for this ticket?

**Comment by nobuti** [comment]
Oops, fixed 🙈
