### ISSUE TITLE
Failed request when showing color picker

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#11569]
### Context
When we show the color picker we request an image even when it's not needed. In cases of ramps when no marker applies (no categories but other intervals).

![404 issue](https://cloud.githubusercontent.com/assets/1078228/23064609/488c6ce8-f511-11e6-854a-67d5386c5644.gif)

**Comment by nobuti** [comment]
Ready for CR.

**Comment by javierarce** [comment]
Acceptance 👍

**Comment by ivanmalagon** [comment]
Deployed to produ.
