### ISSUE TITLE
JS error setting style by value

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#11578]
### Steps to Reproduce

1. Create a map (based on `twitter_t3chfest_reduced` dataset, for example).
2. Style by value based on `verb`.

### Current Result

There's a error in the JS console:

`undefined:1 GET https://team.carto.com/u/juanignaciosl/builder/undefined?req=markup 404 (Not Found)`

### Additional info

Everything seems to work despite that error.

**Comment by xavijam** [comment]
Well, it is not a JS error, it is a non-desired HTTP request, but in any case, it is duplicated https://github.com/CartoDB/cartodb/issues/11569. Thanks for reporting mate! 💋

**Comment by juanignaciosl** [comment]
Oh, I looked for it but it didn't appear, sorry!
