### ISSUE TITLE
Error size button "ADD ANALYSIS"

### ISSUE THREAD

**Issue by urbanphes** [CartoDB/cartodb#11580]
### Context
On an Analysis Screen when you don't have any analysis (empty case) the button shown below "ADD ANALYSIS" has a size of 36px height and we don't use this size. This button should be 32px height.

 
### Production
The button with 36px heights

<img width="445" alt="captura de pantalla 2017-02-20 a las 12 01 26" src="https://cloud.githubusercontent.com/assets/14546701/23122508/c9e7a190-f764-11e6-848c-9a36cd6382e9.png">

### Mockup
The button with 32px heights

![captura de pantalla 2017-02-20 a las 12 01 59](https://cloud.githubusercontent.com/assets/14546701/23122528/d5cf3a54-f764-11e6-9d00-bf2debe1a5f0.png)

**Comment by xavijam** [comment]
:dancing_men:
