### ISSUE TITLE
UI Problems in Time Series widget

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#11588]
### Options menu
- [x] DONE

For consistency, this menu should be added back to this widget.
The options that we would need on it are
- Show Totals
- Edit
- Delete.

### Widget title
- [x] DONE

For consistency, widget title should be shown
- Show play button on the left when animated
- Show filter range after the name

### XXX SELECTED and CLEAR
- [x] DONE

For consistency, we would need both options on the right

### Add 1px white border to the scrub bar (the needle)
- [x] DONE

As shown in the designs.

### Dragable area

- [x] DONE

When filtered, enable drag and drop of the whole data range to move the filter (this would apply to histograms as well)

---

Refreshed designs are here
https://github.com/CartoDB/design/issues/597

**Comment by urbanphes** [comment]
Finished the ticket on design
https://github.com/CartoDB/design/issues/597

**Comment by noguerol** [comment]
Regarding the last point, the selection is currently draggable but only from a very narrow pixel range.

**Comment by ivanmalagon** [comment]
Split this issue in four smaller ones to ease tracking and development.

**Comment by xavijam** [comment]
Closing this one because all of them have been implemented, great job everybody!
