### ISSUE TITLE
Layer onboarding minor detail when layer is synced

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#11583]
We forgot in the matrix of possible cases when the layer is synced.

![screen shot 2017-02-20 at 12 59 30](https://cloud.githubusercontent.com/assets/132146/23124298/8a525f40-f76c-11e6-80bd-a3de4d0874eb.png)

**Comment by arianaescobar** [comment]
Also: 

<img width="532" alt="screen shot 2017-02-20 at 14 34 46" src="https://cloud.githubusercontent.com/assets/16247628/23127179/5a338c54-f77a-11e6-9e9a-ef2eb2c2f949.png">

**Comment by ivanmalagon** [comment]
Ready for code review.

📄  👀

**Comment by xavijam** [comment]
NICE!

**Comment by xavijam** [comment]
Done! 💋 . Great job @ivanmalagon 👏 .
