### ISSUE TITLE
Break down deep-insights-integration class

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#11581]
Although `deep-insights-integration` JS class is a marvellous idea to connect Builder and CARTO.js interactions, we have realized it is growing and growing without control (almost ~1000 lines of code), and we should split it in several parts in order to make it manageable (it includes tests).

**Comment by xavijam** [comment]
Work started in branch `deep-insights-integration-split` for Friday's leapfrog.

**Comment by nobuti** [comment]
We need to pass smokes before to merge.
