### ISSUE TITLE
Fix UI links

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#11587]
- Basemap's layer should be underlined
![image](https://cloud.githubusercontent.com/assets/1214201/23134462/384c35c6-f795-11e6-9008-f0f75805fd69.png)

- Layer's title shouldn't be underlined when we hover on the icons
![image](https://cloud.githubusercontent.com/assets/1214201/23134361/d3f95770-f794-11e6-8a62-937e73cc29e3.png)

**Comment by ivanmalagon** [comment]
This has been already implemented and it's live.
