### ISSUE TITLE
Category "OTHER" is not calculated using the selected agg function

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb#11590]
When a category widget displays data aggregated by any functio, the OTHER category still sums the values of the not displayed categories. 

Graphically (aggregating by **AVG(my_column)**):

![image](https://cloud.githubusercontent.com/assets/9017165/23159659/ed5cb092-f823-11e6-9722-dba344c59eee.png)

The expected result should be that the OTHER value should be calculated using the very same aggregating function the widget is using.

In the example above, OTHER should display the average value of the categories not shown in the TOP5, instead of summing? counting? the leftovers

**Comment by xavijam** [comment]
uhm, not sure if it is a frontend bug or a Maps API bug... could you check the request in order to confirm it?

**Comment by AbelVM** [comment]
You're right:

![image](https://cloud.githubusercontent.com/assets/9017165/23172899/b0eabe90-f857-11e6-90e1-8a47111a2ac4.png)

**Comment by saleiva** [comment]
cc/ @rochoa
