### ISSUE TITLE
Dropdowns are missing their gradients and scroll bars

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#11598]
### Context

All the dropdowns are missing their gradients and scroll bars so it's not clear when there's more content on them. 

### Current Result

Looks like there's nothing else there,

<img width="460" alt="screen shot 2017-02-21 at 16 41 47" src="https://cloud.githubusercontent.com/assets/16247628/23172122/0310d7d4-f855-11e6-9482-b15c9e3bcbe7.png">

but...

<img width="445" alt="screen shot 2017-02-21 at 16 41 56" src="https://cloud.githubusercontent.com/assets/16247628/23172130/08314492-f855-11e6-8455-da35a73a2355.png">

 (Notice that the scroll bar is only appearing when you scroll...)

### Expected result

Dropdowns with more content than what they can show, need a visible scroll bar at all times, as well as a gradient on the bottom part.

**Comment by xavijam** [comment]
I opened mine first 😛  -> https://github.com/CartoDB/cartodb/issues/11597

**Comment by xavijam** [comment]
Hey, what about if we follow the same behaviour we already have in the infowindows? No gradient, but scroll bar visible always.

**Comment by xavijam** [comment]
If we start adding gradients also in dropdowns, we could have performance problems due to we should listen all scroll movements in all dropdowns.

**Comment by javierarce** [comment]
Where's the PR for this ticket?

**Comment by javierarce** [comment]
Found it: https://github.com/CartoDB/cartodb/pull/11609

**Comment by xavijam** [comment]
Ouch sorry, already referenced :(.
