### ISSUE TITLE
Connect with lines Analysis  - Only 2 steps but the second step says 3 step

### ISSUE THREAD

**Issue by urbanphes** [CartoDB/cartodb#11591]
### Context
When you are on the Connect with lines analysis there are 2 steps but the 2nd step says 3 step. We should change this number by 2.

Here the screen

<img width="419" alt="captura de pantalla 2017-02-21 a las 11 27 32" src="https://cloud.githubusercontent.com/assets/14546701/23161144/36227262-f829-11e6-83e6-5bead6efe935.png">

**Comment by xavijam** [comment]
Ha, good catch!
