### ISSUE TITLE
histogram widget selection does not work as expected when clicking on a bucket

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartodb#11593]
### Context
When clicking on a bucket of the histogram, the selection of the histogram selects another range of values.

### Steps to Reproduce

1. Create a map using the `populated_places` dataset from the data library
2. Create a histogram widget using the column `pop_max`
3. Click on the first bucket in the left, the selection is done at another range:

![screen shot 2017-02-21 at 11 48 05](https://cloud.githubusercontent.com/assets/11177693/23161981/826d7aa6-f82c-11e6-9b59-49d61db4f188.png)

![screen shot 2017-02-21 at 11 48 10](https://cloud.githubusercontent.com/assets/11177693/23161986/860e2318-f82c-11e6-8013-5b56bb5c57b2.png)

4. When I click on the last bucket, the one that is located at the right, it does not select anything:

![screen shot 2017-02-21 at 11 53 31](https://cloud.githubusercontent.com/assets/11177693/23162010/a77ba840-f82c-11e6-8a91-8b12f0f0cff8.png)

![screen shot 2017-02-21 at 11 53 42](https://cloud.githubusercontent.com/assets/11177693/23162014/aacd0afc-f82c-11e6-8947-6c4781f4ac34.png)

5. I can only do a selection of values from the histogram if I apply a range, but not if I select a bucket.

![screen shot 2017-02-21 at 11 58 56](https://cloud.githubusercontent.com/assets/11177693/23162157/25979a54-f82d-11e6-9f3c-324c46563d78.png)

### Browser and version

 Broswer: Chrome Version 56.0.2924.87 (64-bit)

**Comment by xavijam** [comment]
Already checked, and it is a problem related with the browser zoom. If the user has applied a zoom different than the normal, filtering over the widget doesn't work as expected.

**Comment by xavijam** [comment]
Opening another ticket in the proper repository, deep-insights.js.
