### ISSUE TITLE
Walkthrough pages appear even after I say "Don't show me again"

### ISSUE THREAD

**Issue by talos** [CartoDB/cartodb#11603]
### Context

Working on a map

### Steps to Reproduce

1. Add a layer to a map
2. Add an analysis
3. When prompted for the walkthrough, choose not to and select "Do not show me again"
4. Delete the analysis
5. Add a different sort of analysis

### Current Result

After adding the analysis again, I see the walkthrough notice a second time, even though I asked never to see it again.

### Expected result

I should never see the walkthrough notice again in that account, ever.

### Browser and version

Firefox v51.0.1 (up-to-date as of Feb 21 2017)

**Comment by xavijam** [comment]
It will be fixed with https://github.com/CartoDB/cartodb/issues/11586.

**Comment by xavijam** [comment]
Thanks @talos .
