### ISSUE TITLE
Static maps do not display with Google basemaps

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#11605]
Static maps API is unable to generate images for maps with google basemaps. There are multiple issues here (token-protected URLs, different URL format) which make it very difficult to do without their JS. But we should at least display something (instead of erroring out).

We discussed possible solutions and the simplest one seems to exclude google maps base layers from named maps. That way, the preview image is generated without a basemap, but at least the data is shown. We did a quick manual test and it seems to work without breaking the embed (as cartodb.js takes the base layer from the vizjson).

cc @CartoDB/builder-backend @xavijam

**Comment by xavijam** [comment]
Deployed
