### ISSUE TITLE
Create special slider for DO boundaries

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#11617]
The upcoming update for the DO analysis needs several new components, one of them is a special slider (check image), in order to select the boundaries. If you need more context, check the [main issue](https://github.com/CartoDB/cartodb/issues/9991).

![screen shot 2017-02-23 at 10 25 01](https://cloud.githubusercontent.com/assets/132146/23253259/246054ea-f9b4-11e6-9d46-b8e114e944d1.png)

I encourage to create a new special component for Backbone.Forms. Create and test it and leave it ready for the [integration](https://github.com/CartoDB/cartodb/issues/11619).

---
*Design: https://invis.io/5G9YKGISB.

**Comment by saleiva** [comment]
This component will be used in more forms in the future

**Comment by javierarce** [comment]
How does the component work? 

From the screenshot I imagine that each of the ticks are associated with a title (that is presented to the users) and a value (that's submitted with the form)… is that right? 

If that's true, I'll propose to make it very generic, supporting any type of value (numbers, strings, booleans, etc.). Plus, the component should allow to customize the grey bar through a CSS class.

**Comment by xavijam** [comment]
Fine by me, but take into account we have the number input where the slider appears. But I agree to create a new generic one 👍 . @noguerol or @saleiva could you help @javierarce?

**Comment by javierarce** [comment]
@xavijam yes, I think we could extend from that one or make it more generic, supporting both the simple case and the complex one.

**Comment by xavijam** [comment]
Not sure about extend the number one, I'd go for the other way around. Create a generic one, and then extend then number from that one. But in any case, review the use cases and apply your magic, you know better than me the best solution 💋 .

**Comment by nobuti** [comment]
This is already in master. Closed by #11668.
