### ISSUE TITLE
Stop button instead of Play in torque animations using Firefox

### ISSUE THREAD

**Issue by arredond** [CartoDB/cartodb#11610]
### Context
*Please explain here below what you were doing when the issue happened*

When making an animation on Firefox, a "Stop" button appears where there should be a "Play" one (as there is in Chrome).
![bug_play_animation_firefox](https://cloud.githubusercontent.com/assets/19406854/23212197/ecf13df2-f905-11e6-871b-6620895f8890.png)

This happens on any dataset.

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1.  Create a map from any dataset.
2.  In Style > Agregation choose Animated.
3.  Pause the time-scale under the map and observe the issue.

### Current Result
*Please describe here below the current result you got*

 

### Expected result
*Please describe here below what should be the expected behaviour*

### Browser and version
*What internet browser (Chrome, Firefox, etc) and version was you using and version* 

 

### .carto file
*Don't forget to rename .carto file to .zip file to be able to upload to github*

 

### Additional info
*Please add any information of interest here below*

**Comment by rjimenezda** [comment]
This was fixed while doing #12387
