### ISSUE TITLE
Master testing broken

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#11613]
Seems like it is due to the Ruby 2.4 PR changes:

```spec/spec_helper.rb:13:in `remove_const': constant ActiveRecord::TestFixtures not defined (NameError)```

cc @juanignaciosl

**Comment by juanignaciosl** [comment]
I'd love to know how come tests passed back then >_<

**Comment by xavijam** [comment]
:|

**Comment by javitonino** [comment]
Confirmed 🍏
