### ISSUE TITLE
Create special dropdown for DO measurament

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#11618]
The upcoming update for the DO analysis needs several new components, one of them is this new special dropdown, where the current measurament and segment are in the same component.

**OLD FORM:**

![screen shot 2017-02-23 at 10 46 44](https://cloud.githubusercontent.com/assets/132146/23253710/ccfd5aca-f9b5-11e6-818d-4566430c961f.png)

![screen shot 2017-02-23 at 10 46 39](https://cloud.githubusercontent.com/assets/132146/23253589/64545c08-f9b5-11e6-9a72-77c235ee73dd.png)

**NEW FORM:**

![screen shot 2017-02-23 at 10 25 01](https://cloud.githubusercontent.com/assets/132146/23253259/246054ea-f9b4-11e6-9d46-b8e114e944d1.png)

- Step 1 (measurament):
![screen shot 2017-02-23 at 10 25 29](https://cloud.githubusercontent.com/assets/132146/23253307/57adf2ee-f9b4-11e6-80f9-8b3888ffae1a.png)

- Step 2 (segment):
![screen shot 2017-02-23 at 10 25 33](https://cloud.githubusercontent.com/assets/132146/23253308/58002514-f9b4-11e6-95ee-027648eb570d.png)

I encourage to create a new special component for Backbone.Forms. Create and test it and leave it ready for the [integration](https://github.com/CartoDB/cartodb/issues/11619). If you need more context, check the [main issue](https://github.com/CartoDB/cartodb/issues/9991).

---
*Design: https://invis.io/5G9YKGISB.

**Comment by nobuti** [comment]
@saleiva @noguerol some questions about the interaction:
- The second step of the dropdown, is it only accessible if the user clicks on `Filters`?
- what happens if the user clicks on `Filters` with no item being selected in the first place? Should we hide it until one item is selected?
- what does it mean the number between parenthesis?

**Comment by saleiva** [comment]
- Filters only filter the view in the first step not the other way around. Take that second step like just a way of filtering some items on the first one.
- Number is number of measurement for that region within that filter

**Comment by nobuti** [comment]
So we should hide the filters button until one item is selected, right?

**Comment by jorgesancha** [comment]
Blocked waiting for answers to these questions (https://github.com/CartoDB/cartodb/issues/11663#issuecomment-284008026) and decisions on the DO API (https://github.com/CartoDB/observatory-extension/issues/263)

**Comment by xavijam** [comment]
Already merged, ready for next iteration!
