### ISSUE TITLE
Basemap does not update

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#11625]
### Steps to Reproduce

1. Create a map from a dataset
2. Change basemap from Positron to Dark Matter

### Current Result

* The new basemap is not updated, so it shows the former.

![basemap](https://cloud.githubusercontent.com/assets/5215798/23264331/3ebca8c0-f9e1-11e6-9a42-13a5f28e3a0f.png)

### Expected result

* The new basemap should show after changing from one to another.

### Browser and version

* Google Chrome v56.

### .carto file

[Untitled Map 7 (on 2017-02-23 at 14.59.45).carto.zip](https://github.com/CartoDB/cartodb/files/796788/Untitled.Map.7.on.2017-02-23.at.14.59.45.carto.zip)

### Additional info

* The basemap is changed after refreshing the browser. And after that, if you change again the basemap, it works correctly.

**Comment by xavijam** [comment]
cc @alonsogarciapablo

**Comment by alonsogarciapablo** [comment]
@ramiroaznar are you using an account with Google Maps enabled (eg: team account)?

**Comment by ramiroaznar** [comment]
Yes, `team` account, `ramirocartodb` user. @geocaron also experienced the same issue (`team` account) as well.

**Comment by alonsogarciapablo** [comment]
Talked to @ramiroaznar about this. This is only happening when creating a map from an existing dataset.

**Comment by xavijam** [comment]
:+1:

**Comment by alonsogarciapablo** [comment]
## Acceptance

1. Create a map from an existing dataset.
2. You will probably see the Positron base layer.
3. Change the base layer to one in the same category and it should work.
4. Try to change the basemap to one from a different category/group (including Google Maps).
5. Make sure 4. also works with existing maps and new empty maps.

Thanks!
