### ISSUE TITLE
Google Basemaps Option Enabled for User Accounts

### ISSUE THREAD

**Issue by michellechandra** [CartoDB/cartodb#11627]
### Context
A user has reported in Support that he can see the Google Basemaps option in his account when editing a map. When he selects Google basemap, his map freezes/breaks. 

Were Google basemaps mistakenly enabled for user accounts?
 
### Steps to Reproduce
**Test user account:** ztephm

Create a map
Choose basemap layer
In basemap options, Google maps shows as an option

![screen shot 2017-02-23 at 09 05 17](https://cloud.githubusercontent.com/assets/5423288/23270011/3beb4c44-f9a7-11e6-96a8-66dd25c3a076.png)

### Current Result
Selecting Google basemaps causes an error and the map breaks.

Google basemaps should not show on the front end as an option at all.

cc @CartoDB/support

**Comment by xavijam** [comment]
Fixed thanks to https://github.com/CartoDB/cartodb/issues/11628.
