### ISSUE TITLE
Changes for embed view

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#11623]
This is the list of pending things for the embed view. Unfortunately it requires changes over CARTO.js, Deep-Insights.js and Builder. There is a link to the design at the bottom:

- [ ] Delete blue bar from embed view (deep-insights.js).
- [ ] Remove blue bar map option from CARTO Builder (Builder).
- [ ] Move social buttons to CARTO.js.
- [ ] Create new component (A) where **title**, **description** and **legend** will be placed (CARTO.js).
- [ ] Create new title and description components (CARTO.js).
- [ ] Create title and description map options in Builder (Builder).
- [ ] Make possible to show/hide legends (CARTO.js).
- [ ] Move legends within component A (CARTO.js).
- [ ] Delete social actions in mobile view (CARTO.js).
- [ ] Delete zoom bottoms in mobile view (CARTO.js).
- [ ] Create slide component for showing legend in mobile (CARTO.js).
- [ ] Show in a different way the click popups in mobile (CARTO.js).

---
*Design: https://invis.io/HUAAC2GSV

**Comment by saleiva** [comment]
The last point 'Show in a different way the click popups in mobile (CARTO.js).' should be evaluated. Is an awesome feature but might be a bit tricky for this phase. I'd say that we need to think deeply about the scope of this

**Comment by urbanphes** [comment]
Last update:
- All resolution sizes have the same structure for the component (Title + Description + Legend).
- The case when the user won't show the title or description.
- Including a visual that how the legends work.

Here the final visual on InVision project:
https://invis.io/HUAAC2GSV

**Comment by arianaescobar** [comment]
Closing this ticket since the invision prototype is outdated and we're starting to track this project [from here](https://github.com/CartoDB/cartodb-management/issues/5082)
