### ISSUE TITLE
Prepare all licenses and descriptions for all measurements & segments

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#11629]
Basically we have to specify all measurement licenses.

<img width="330" alt="screen shot 2017-02-23 at 23 12 17" src="https://cloud.githubusercontent.com/assets/132146/23281509/da7c02e2-fa1d-11e6-9fef-a30605dfd18e.png">

And all measurement and segment texts.

<img width="388" alt="screen shot 2017-02-23 at 23 14 54" src="https://cloud.githubusercontent.com/assets/132146/23281536/f2cb4a1a-fa1d-11e6-8539-57f8d505fe99.png">

**Comment by xavijam** [comment]
@talos, are those licenses and descriptions available somewhere?

**Comment by talos** [comment]
@xavijam Which license it is and the name is included with metadata, in terms of linking out we have linkability to the [Catalog's license page](https://cartodb.github.io/bigmetadata/licenses.html).

We should not hard-code any of the licenses in the code, but get them all from metadata as they change frequently.

**Comment by xavijam** [comment]
@noguerol and @saleiva, should we link to that license page then?

**Comment by noguerol** [comment]
Yes.

**Comment by xavijam** [comment]
Closing it because it is already working and if there is any change, it will be faced in DO repositories.
