### ISSUE TITLE
Color mismatch when map has null category

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#11632]
### Context
Styling a map by category with a lot of categories (more than 10), one of the valid categories has a value of `null`. In the category style we can see that it's valid category with its own color. The `others` category has the right color, a grey one.

In the legend, the `others` category get mistaken for the `null` one, showing a wrong color, not the gray one.

I haven't done any research so I don't know if this is a bug in `cartodb` or `cartodb.js`. Please move the issue to the right repo once that gets clarified. 

### Steps to Reproduce

1. Import the attached .carto file.

1. Style by value choosing the `line` column.

Here's a recording of the problem.

![null category](https://cloud.githubusercontent.com/assets/1078228/23296750/cb0374fe-fa76-11e6-88c2-1ba4fccd6486.gif)

### Files

[Leer solo (on 2017-02-24 at 08.52.14).carto.zip](https://github.com/CartoDB/cartodb/files/798739/Leer.solo.on.2017-02-24.at.08.52.14.carto.zip)

**Comment by nobuti** [comment]
Possibly related to https://github.com/CartoDB/cartodb/issues/11421

**Comment by javierarce** [comment]
Acceptance: 👍

**Comment by nobuti** [comment]
This is still happens after #11421.

**Comment by xavijam** [comment]
Deployed
