### ISSUE TITLE
Legend don't reflect category icons

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#11630]
### Context
When assigning an icon to a category, we create automatically a legend. That legend don't show the icon.

![legend problems](https://cloud.githubusercontent.com/assets/1078228/23296343/d3502b90-fa74-11e6-8006-c83599b3f3c6.gif)

 
### Steps to Reproduce

1. Style a layer by value. A legend is shown.

 
1.  Select an icon for one of the categories.

### Current Result

The legends gets rebuilt but the category don't show the icon.

### Expected result

The legend show the icon for that category.

**Comment by xavijam** [comment]
For @Jesus89, let's talk before starting with it.

**Comment by rubenmoya** [comment]
In production 🚀 !
