### ISSUE TITLE
Allow to override S3 endpoint

### ISSUE THREAD

**Issue by luisbosque** [CartoDB/cartodb#11631]
If builder is using S3 to store exported visualizations or temporal data imports it would be great to be able to override the endpoint. By default the aws-sdk gem uses internally AWS S3 endpoint. However there are some other storage services with a S3 compatible API.

Being able to override the endpoint url will alow to use these services as an alternative

**Comment by luisbosque** [comment]
Suggested PR: https://github.com/CartoDB/cartodb/pull/11614

**Comment by xavijam** [comment]
Deployed!
