### ISSUE TITLE
Layer user table deadlocks

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#11641]
A couple of cases that occurred lately.

https://rollbar.com/vizzuality/CartoDB/items/21820/occurrences/22048121241/
This is a case where two layers where being updated simultaneously. There are updates for layer A and one layer B.
- Layer A depends on 11 user_tables (woah!).
- Layer B depends on 5 user tables.
- There are 4 user tables in common.

Queries in the lock:
- `SELECT "user_tables".* FROM "user_tables" INNER JOIN "layers_user_tables" ON "user_tables"."id" = "layers_user_tables"."user_table_id" WHERE "layers_user_tables"."layer_id" = 'A' FOR UPDATE`
- `SELECT "user_tables".* FROM "user_tables" INNER JOIN "layers_user_tables" ON "user_tables"."id" = "layers_user_tables"."user_table_id" WHERE "layers_user_tables"."layer_id" = 'B' FOR UPDATE`

---

https://rollbar.com/vizzuality/CartoDB/items/21445/occurrences/21848774689/
Not sure what happened here. There are two competing queries for the same layer:
- Update on `layers`
- Delete from `layers_user_table` (for an specific user_table)

Seems to be a case of a layer update.
- `UPDATE "layers" SET "options" = '{...}', "updated_at" = '2017-02-24 14:19:17.777658', "infowindow" = {...}, "tooltip" = '{...}' WHERE "layers"."id" = 'uuid'`
- `DELETE FROM "layers_user_tables" WHERE "layers_user_tables"."layer_id" = 'uuid' AND "layers_user_tables"."user_table_id" = 'XXX'`

---
https://rollbar.com/vizzuality/CartoDB/items/21820/occurrences/22155123597/
https://rollbar.com/vizzuality/CartoDB/items/21855/occurrences/22155123123/

Queries are `SELECT "user_tables".* FROM "user_tables" INNER JOIN "layers_user_tables" ON "user_tables"."id" = "layers_user_tables"."user_table_id" WHERE "layers_user_tables"."layer_id" = 'X' FOR UPDATE` with three different layer ids.

Theory is that it's a conflict between layer update and analysis update (which triggers an update in all layers). Potential solution, lock for all layers in `Map.update_dataset_dependencies`.

**Comment by juanignaciosl** [comment]
I've marked as resolved [21445](https://rollbar.com/vizzuality/CartoDB/items/21445) and [21855](https://rollbar.com/vizzuality/CartoDB/items/21855) because they haven't occurred in more than one month.
