### ISSUE TITLE
Add Zeus support

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#11645]
See https://github.com/CartoDB/cartodb/issues/11643

**Comment by nobuti** [comment]
One (newbie) question, are we using spring? I was told that spring was the milk.

**Comment by javitonino** [comment]
Spring is for Rails 4.2+ only, as it does a lot of rails specific magic. Zeus is a very similar idea, but works with any ruby program, so we can use it with our Rails version. Otherwise, they are both pretty much the same thing (preloading the environment and then forking processes). From the alternatives I researched, Zeus seemed the better suited for our use case since it's more flexible and easier to combine with our parallel testing setup.
