### ISSUE TITLE
Allow moving through the timeline of a Time Series widget without selecting a time range

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#11649]
Right now when you click on a time series widget, the timeline gets filtered, selecting a range, instead of just "moving the needle" that reproduces the widget. 

We would like to change that behavior so that when you **just click** on the timeline, the needle would just move to where you clicked and it will keep moving through the timeline from that point and when you **click and drag** is when you'll select a range.

**Comment by xavijam** [comment]
Hum, right now it would be more difficult than expected because we use the same "component" for histogram and for time series.

**Comment by saleiva** [comment]
Nope, wait. There is a difference.
That behaviour that @arianaescobar is saying is only applicable when the map is animated.

**Comment by xavijam** [comment]
Yep, I understood that. But the component behind is the same for both (user events included). But hey, no problem, I didn't say we can't do it 😅 .

**Comment by arianaescobar** [comment]
The sky is the limit! (right?) 🚀

**Comment by xavijam** [comment]
And beyond!

**Comment by matallo** [comment]
this has already been addressed in https://github.com/CartoDB/cartodb/issues/12180

closing, then
