### ISSUE TITLE
Time Series widget's date range not getting properly updated when selecting other columns

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#11651]
### Context

If you add a Time Series widget selecting a particular column, and then, once added, you change the column selected, the time range of the widget doesn't get properly updated with the new data (unless you refresh the window)

### Steps to Reproduce

1. Add a Time Series widget with any column
2. Change the column on the widget settings  
3. Take a look at how the graph looks 
4. Refresh the window and take another look (the graph will be different). 

### Current Result

Right now the widget tries to show the new column data in the same time range from the previously selected column.  

### Expected result

The widget should always refresh completely, updating the time range so the new column data will be displayed properly on the widget. 

### Example 

Time series widget with `plant_date` column added from "Add widget" modal

<img width="817" alt="screen shot 2017-02-27 at 16 37 06" src="https://cloud.githubusercontent.com/assets/16247628/23367816/00b8c512-fd0c-11e6-90be-4903de483060.png">

Time series widget with `plant_date` column selected from widget options after initially being created with another column:

<img width="807" alt="screen shot 2017-02-27 at 16 39 01" src="https://cloud.githubusercontent.com/assets/16247628/23367849/1bb787a4-fd0c-11e6-90ee-dcd0c8f5f0c4.png">

**Comment by rjimenezda** [comment]
Similar error case:

1. Create a table with a few points, no need for date information
2. Add a time-series with cartodb_id, it should render correctly.
3. Change the SQL to something like `SELECT *, to_timestamp(1036800000 + (cartodb_id * 100)) as date  FROM untitled_table_1` which should convert to dates and push them 32 years forward
4. Apply SQL
5. Widget doesn't refresh, range will show incorrect  dates.
6. Refresh
7. Everything looks great

Probably same case as switching the column

**Comment by xavijam** [comment]
It has been solved after merging [aggregations](https://github.com/CartoDB/cartodb/pull/12347)! 💃 .
