### ISSUE TITLE
improve loaders visibility

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#11652]
Improve the visibility of the loader mainly when is over the map.
Related - https://github.com/CartoDB/design/issues/601

2px (height) -> Notification and widget loader.
3px (height) -> Map loader.

Framer - https://framer.cloud/PVDCY/

**Comment by xavijam** [comment]
This ticket should go in CartoAssets, but it is ok 👍 .

**Comment by piensaenpixel** [comment]
You're right @xavijam i can take care, i miss it :P

**Comment by piensaenpixel** [comment]
PR - https://github.com/CartoDB/CartoAssets/pull/160

**Comment by saleiva** [comment]
BOOM
