### ISSUE TITLE
"force" user deletion for EUMAPI

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#11654]
### Context
From #9789. Organization user deletion through EUMAPI fails with unregistered tables.

 

### Steps to Reproduce

1. Create a table with the SQL with a non-owner organization user. Don't login with him afterwards.
2. [Delete him with EUMAPI](https://carto.com/docs/carto-enterprise/enterprise-api#delete-users-with-the-enterprise-api)

### Current Result

You get a error similar to this:

```bash
User couldn't be deleted: PG::Error: ERROR:  cannot drop schema juanignaciosl-ded-06-7 because other objects depend on it
DETAIL:  table "juanignaciosl-ded-06-7".wadus depends on schema juanignaciosl-ded-06-7
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
```
 
### Additional info

EUMAPI user deletion should support a `force` parameter. In that case, the users should be successfully deleted even in case of unregistered tables.

**Comment by javitonino** [comment]
Note: nowadays, this should probably take full organization deletion into account.
