### ISSUE TITLE
Carto::User does not fallbacks to user Google api key if organization is blank

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#11659]
From https://github.com/CartoDB/cartodb/issues/11655

STR
1. Set an organization google key to `''` (empty string)
2. Set the user api key to something
3. Open Builder, you should be able to see the google maps script being loaded

This is currently broken in the AR model only:
```
  def google_maps_api_key
    if has_organization?
      self.organization.google_maps_key || self.google_maps_key
    else
      self.google_maps_key
    end
  end
```

If the organization key is blank but not nil, the organization key will be used, even if the user has a proper one. The old models handles this correctly.

**Comment by javitonino** [comment]
Reviving this. This has affected enterprise users in the past, although there doesn't seem to be anyone affected now. But we should address this. Maybe RT if there is a slot there, if not, we'll get to this eventually in Backend.

cc @ramiroaznar

**Comment by ramiroaznar** [comment]
Let's move this to RT then.

**Comment by alrocar** [comment]
Isn't this already fixed [here](https://github.com/CartoDB/cartodb/pull/11925/files#diff-fa92a465f56fbdc69b8d224e66bd61a9R188)?

**Comment by ramiroaznar** [comment]
^^ @javitonino ?

**Comment by javitonino** [comment]
Yeah! :tada:
