### ISSUE TITLE
Don't activate the Apply button on "Filter by column value" analysis until all required inputs are filled

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#11658]
### Context

Right now the "Apply" button is getting activated right after you select the column, but if you don't fill the remaining inputs, the analysis will fail. Let's not activate the button until all the required inputs are correctly filled. 

### Steps to Reproduce

1. Add a Filter by column value analysis
2. Click Apply

### Current Result

![screen shot 2017-02-28 at 11 01 16](https://cloud.githubusercontent.com/assets/16247628/23400840/b244bb80-fda5-11e6-84ee-c355c7da99f4.png)

![screen shot 2017-02-28 at 11 01 54](https://cloud.githubusercontent.com/assets/16247628/23400831/aa069402-fda5-11e6-8f2c-8776f7428e94.png)

**Comment by nobuti** [comment]
Closed by #12802
