### ISSUE TITLE
Don't prompt error tooltips automatically while filling the Filter by Layer inputs 

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#11656]
### Context

Similar to [this](https://github.com/CartoDB/cartodb/issues/11426#issuecomment-280595279), on the Filter by Layer analysis our UI is also prompting error tooltips while you're filling the required inputs which can get intrusive and annoying. Could we fix it like we did with the Georeference one? 

### Steps to Reproduce

1. Add a Filter by Layer analysis 
2. Fill the Source column input

### Current Result

![screen shot 2017-02-28 at 10 44 12](https://cloud.githubusercontent.com/assets/16247628/23400427/45af9fea-fda4-11e6-8eda-644d1820d3c4.png)

**Comment by alrocar** [comment]
Stale issue. Closing 👋
