### ISSUE TITLE
Add tooltips to show bucket data when hovering on a Time Series widget

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#11650]
We'd like to implement tooltips on our Time Series widgets so when users hover their buckets they can see the represented data. 

<img width="369" alt="screen shot 2017-02-27 at 16 33 21" src="https://cloud.githubusercontent.com/assets/16247628/23367448/8fc92c76-fd0a-11e6-8d97-35252804cfeb.png">

**Comment by saleiva** [comment]
And the histogram right?

**Comment by arianaescobar** [comment]
Yeah!

**Comment by xavijam** [comment]
Hum, we missed this one @ivanmalagon @rubenmoya @rjimenezda when we touched the time-series 😱  .

**Comment by Jesus89** [comment]
Now the histogram tooltips show the formatted frequency. What should it show instead?

@arianaescobar

**Comment by arianaescobar** [comment]
What do you mean with formatted frequency? 🤔  They should show the bucket data just like the histogram does. 

Histogram bucket hovered in production:
<img width="344" alt="screen shot 2017-08-31 at 11 52 46" src="https://user-images.githubusercontent.com/16247628/29917699-02a787dc-8e43-11e7-98ec-fb93afcdb910.png">

Time-Series bucket hovered in production:
<img width="270" alt="screen shot 2017-08-31 at 11 53 08" src="https://user-images.githubusercontent.com/16247628/29917700-02ae6426-8e43-11e7-94d2-e7d4abac4340.png">

**Comment by Jesus89** [comment]
I supposed that the histogram tooltips need to change. The histogram shows the bucket data. I would like to know if I need to add extra info in the tooltip, like the type as seen in your design: "627K **Transactions**"

**Comment by arianaescobar** [comment]
For now, let's just add the tooltip with the data and we'll create a new ticket to add that extra info in the future :)

**Comment by Jesus89** [comment]
Ok. Thanks for the clarification! :smile:

**Comment by arianaescobar** [comment]
Anytime!

**Comment by ivanmalagon** [comment]
Shipped! 🚀
