### ISSUE TITLE
BUILDER only shows GM basemaps

### ISSUE THREAD

**Issue by arredond** [CartoDB/cartodb#11655]
### Steps to Reproduce

1. Create map from dataset
2. Check basemaps

### Current Result

* BUILDER only shows GM basemaps.
* An error related to GM library shows in the console:

![selection_003](https://cloud.githubusercontent.com/assets/19406854/23399871/2d79bdea-fda2-11e6-913d-ab910b3ac450.png)
 
### Expected result

* GM basemaps should not appear. Standard basemaps should appear.

### Browser and version

* Google v56.

### .carto file

* [masas_sup_v map 1 (on 2017-02-28 at 09.37.22).carto.zip](https://github.com/CartoDB/cartodb/files/806264/masas_sup_v.map.1.on.2017-02-28.at.09.37.22.carto.zip)
 
### Additional info

* User: `aarredondo-carto`
* Org: `team`

**Comment by arredond** [comment]
I just found out that I am not able to visualize any services from OpenStreetMap, not just on Carto, so the problem might be mine and not Builder's

**Comment by xavijam** [comment]
Looks like the `<script>` is not being rendered.

**Comment by javitonino** [comment]
This should be working now. I fixed it for the team organization and opened a follow up issue: https://github.com/CartoDB/cartodb/issues/11659
