### ISSUE TITLE
Having a bubbles legend, if you apply an analysis, JS error is thrown

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#11666]
**STR**
- Create a map of points (I've used `paradas_metro_madrid` one).
- Style size by value, it should create a bubbles legend automatically.
- Style color by value, it should create a categories legend automatically.
- Reload the page.
- Open the browser console.
- Go to the points layer and add a new analysis (subsample for example 💃 ).
- Apply the analysis.
- 💥 .

It fails because it needs a color for the bubble legend but in this moment the style model doesn't have one because `none` type is applied, so everything fails, and the worst thing, this is one of the reasons of a ghost node.

**Comment by javitonino** [comment]
Deployed 🚀
