### ISSUE TITLE
Load infowindows on click by default

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#11660]
### Context
Infowindows or now called popups are not used as much as they used to due to the fact that the CTA doesn't appear when clicking on them, but instead of replicating that behaviour we are thinking on a new idea.

### Current Result
When adding a layer, there is no popup on this layer.

### Expected result
When adding a layer, popups on click should be automatically added containing those fields with less than 10% of nulls on them. It will be always possible for the user to configure it layer, but having them from the beginning will improve map onboarding.

**Comment by xavijam** [comment]
It is a good idea, but if you want to keep your data private, doing that, we could "leak" the information and the user could not notice it.

**Comment by saleiva** [comment]
For that you have your maps private, right? If you are in a FREE account, you have to accept that it's public (per our terms)

**Comment by ramiroaznar** [comment]
Do you think this is still valid? @arianaescobar

**Comment by arianaescobar** [comment]
Yeah, but at the same time as this one: https://github.com/CartoDB/cartodb/issues/11903

**Comment by ramiroaznar** [comment]
If this is an onboarding issue, then let's summon @matallo @alonsogarciapablo

**Comment by arianaescobar** [comment]
It's a minor one. I'd say we have more pressing issues onboarding-wise.

**Comment by alrocar** [comment]
Stale issue. Closing 👋
