### ISSUE TITLE
Mail notifications

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#11679]
When a notification is created or updated, a mail should be sent.

Needed: design.

cc @saleiva

**Comment by noguerol** [comment]
cc @asimcox to clarify this

**Comment by saleiva** [comment]
please, it sounds like this shouldn't be done.

**Comment by juanignaciosl** [comment]
The requirements doc, in the notification section, mentions that

> _the system_ will send email notifications to users for the following events:"
>   - When a new account is activated.
>   - When an account is manually enabled ...
>   ... (some others related to charge codes)

Maybe this doesn't need to be supported and notifications are only within CARTO, without an email.

**Comment by asimcox** [comment]
Email Notification requirements correspond to this [client-facing BCG repo ticket: #57](https://github.com/CartoDB/BCG/issues/57) 

Email Notifications are a part of the Feature List in the SOW, but was always under the assumption this was a solutions task. cc' @danicarrion for awareness

@juanignaciosl - where are you referencing those requirements from? I just want to make sure you're referencing the source of truth.

**Comment by noguerol** [comment]
@cc danicarrion to confirm whether is Solutions the ones doing this.

**Comment by juanignaciosl** [comment]
After talking to @asimcox , it's clear that _manual_ notifications, the ones that are handled in this milestone (https://github.com/CartoDB/cartodb/milestone/136), *do not* trigger emails. Only "automatic notifications" do.
