### ISSUE TITLE
I think an analysis broke my map

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#11673]
### Context

Sorry for the shitty title but I'm not sure on how to describe this error. From my dashboard I entered one of my maps (that until yesterday was working just fine) and instead of going to Builder, this is what got loaded: 

<img width="1675" alt="screen shot 2017-03-01 at 12 22 02" src="https://cloud.githubusercontent.com/assets/16247628/23457927/34dc0074-fe7a-11e6-9d76-7258821829b3.png">

With all these errors on the console: 

![screen shot 2017-03-01 at 12 22 33](https://cloud.githubusercontent.com/assets/16247628/23457937/3fff1838-fe7a-11e6-8291-666523fc5b14.png)

The map is called `SF Trees Import` on my team account, `arianaescobar`

### Steps to Reproduce

I have no idea on how to reproduce this error... sorry that I can't be more helpful :( 

### Browser and version

Google Chrome Version 56.0.2924.87 (64-bit)

**Comment by xavijam** [comment]
Although you think it was working, there was a problem in any of the actions and it created a "ghost node". Once you reload the map it shows the cake. Do you want us to recover it?

**Comment by javitonino** [comment]
We fixed it, but had to delete the `B` layer entirely. Classic ghost nodes problem (analysis was removed, but layer was not).

**Comment by xavijam** [comment]
Thanks man!

**Comment by arianaescobar** [comment]
Thank you, guys! I don't really mind if that map breaks, I reported it in case it helped to prevent that happening again to more users. 

Does that happen often?
