### ISSUE TITLE
Instrumentate DO new UI for proper measuring

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#11670]
### Context

In order to keep track of the changes we do and how the UI performs in terms of UX we are going to need some extra classes on the CSS (happy to hear other solutions) so we can track usage of different elements using the actual tools.

From now on I propose we do 2 main things:
- start using class names with no css properties but that help us tracking different elements, and under a new namespace. Something like 'trk--typeElement--qualifiers(n)'.
- start using class names for groups of fields so we can focus on particular states of the UI. 

For example with the new DO UI it should be something like...

<img width="746" alt="do_instr" src="https://cloud.githubusercontent.com/assets/132146/23855429/dc345a5e-07f5-11e7-9ba6-823ef7317d64.png">

With this information we can generate funnels so we see how many people is completing the different steps of the analysis. Sounds this feasible?

On the other hand, it looks like our current stack would require us to trigger a fake click event when some particular elements are shown, so we can calculate rate of completion from shown to first required action. Too hacky? It's the official solution that our provider suggest...

This would need to be added to all analysis (and to all the UI) at some moment

**Comment by saleiva** [comment]
cc/ @noguerol @xavijam @CartoDB/design

**Comment by xavijam** [comment]
cc @nobuti

**Comment by xavijam** [comment]
> On the other hand, it looks like our current stack would require us to trigger a fake click event when some particular elements are shown, so we can calculate rate of completion from shown to first required action. Too hacky? It's the official solution that our provider suggest...

I don't understand it. Which elements would need that?

**Comment by saleiva** [comment]
Every screen. Think that funnel should be tracked since the moment somebody enters to a screen.

**Comment by javierarce** [comment]
A note about the class names used to do the tracking:

In the Image Export feature we decided to use this structure:

`.track-FeatureName`: to name the main feature.
`.track-action`: to track buttons, links, or anything that users can interact with.

For example, the export button has the the classes:

`track-ImageExport track-export`

For other examples see: 
https://github.com/CartoDB/cartodb/search?utf8=%E2%9C%93&q=track-ImageExport

**Comment by saleiva** [comment]
yeah, we should update this according to the changes you forced me to
accept :P

**Comment by matallo** [comment]
blocked until #11802 is finished

**Comment by nobuti** [comment]
I guess we can close this in favour of #12095.
