### ISSUE TITLE
"Edit this cell" box not opening when double-clicking an empty cell

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#11687]
### Context

In the table view, you can edit cells by double-clicking on them but when the cell is empty, it doesn't work. 

### Current Result

![7536dee4-fe7c-11e6-85aa-6af0b1ea8bbe](https://cloud.githubusercontent.com/assets/16247628/23503577/9790d06a-ff3c-11e6-96dc-20b0f776880b.gif)

### Expected result

The "Edit this cell" box should always appear on double-clicks.

**Comment by xavijam** [comment]
Fixed thanks to https://github.com/CartoDB/cartodb/pull/11691.
