### ISSUE TITLE
Triangle icon has noticeable artifact

### ISSUE THREAD

**Issue by makella** [CartoDB/cartodb#11684]
### Context
Symbolizing points by icon

### Steps to Reproduce
1. Add points
2. Style by img
3. Choose the fourth icon in the set the solid triangle 
`https://s3.amazonaws.com/com.cartodb.users-assets.production/maki-icons/triangle-18.svg`

### Current Result
There is a small line on top of the triangle that is being rendered as part of the outline. By default, you won't notice it on Positron because we have a white outline against the light map.

If, however, you change the line-width or the line-color, you will notice it:

![screen shot 2017-03-01 at 1 22 55 pm](https://cloud.githubusercontent.com/assets/1566273/23479545/0a4c4366-fe82-11e6-957d-2f3758b3c7ba.png)

### Expected result
To not have that bar on top of the triangles.  I tested some of the other icons and haven't noticed this happening with them. But it might be worth a more detailed look at each icon to make sure.

### Browser and version
Chrome

### .carto file
[Icon Artifact (on 2017-03-01 at 20.25.19).carto.zip](https://github.com/CartoDB/cartodb/files/811948/Icon.Artifact.on.2017-03-01.at.20.25.19.carto.zip)

**Comment by xavijam** [comment]
That is a problem that comes from [Maki icons](https://www.mapbox.com/maki-icons/).

**Comment by makella** [comment]
Right, so I looked at the triangle icon from the Maki icon link and also downloaded the version we have. The icons have been updated so for example, there is no longer a `triangle-18` it is replaced with `triangle-15` in the new set (15x15 pixels).

- First question: are we using the latest set or are these the same ones from Editor? I had noticed issues with those ones with regards to outlines as well (https://github.com/CartoDB/design/issues/145).

- To test, I brought both versions into illustrator to see the difference in outlines (green in the outline color)

  + The one I downloaded from `https://s3.amazonaws.com/com.cartodb.users-assets.production/maki-icons/triangle-18.svg` looks like this (I think the outer box gets considered with the outline):
![screen shot 2017-03-02 at 7 31 04 am](https://cloud.githubusercontent.com/assets/1566273/23511478/6d8be0f6-ff1a-11e6-8902-f375ba6e7a40.png)

  
  + While the triangle-15.svg from the new set (the link you reference), looks like this:
![screen shot 2017-03-02 at 7 34 57 am](https://cloud.githubusercontent.com/assets/1566273/23511537/96f0d03c-ff1a-11e6-95fb-fd27b8a2b8e3.png)

**Comment by xavijam** [comment]
It is likely we are not using the last version of them :(. Bad thing is I don't know if we can update them without having a problem. Let me check it.

**Comment by makella** [comment]
@xavijam another option (if we can't get the updated set in) is to have no outline, by default, on the icons...

**Comment by makella** [comment]
@xavijam maybe something is going on with that particular triangle icon... using icons now and seeing this:

![screen shot 2017-03-02 at 10 21 32 am](https://cloud.githubusercontent.com/assets/1566273/23518828/f114fbc6-ff31-11e6-8f18-61098efe4a80.png)
