### ISSUE TITLE
Support running all engine tests within rspec

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#11689]
- [ ] As a consequence of #11688, `/gears` will contain engines, each one with its tests. Currently, adding this to `Makefile` doesn't work:

```
check-carto-gears-api:
	cd gears/carto_gears_api && RAILS_ENV=test bundle exec rspec
```

It doesn't work because of `generateSpecFull.sh`, which `grep`s based on the `.rb` extension. For #11688 it will be workarounded by adding the file explicitly, but adding a new test at a gear shouldn't force to edit the `Makefile`.

- [ ] Adding a new engine shouldn't force to modify the `Makefile` either. It should loop over `/gears/*` and run `bundle exec rspec`.

cc @javitonino

**Comment by javitonino** [comment]
`make check-gears` does this :tada:
