### ISSUE TITLE
Mark notification as read API

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#11680]
Tentative API:

A)

- [ ] `POST /api/v1/users/:user_id/notifications/:id/reads`.

B)

- [x] `PUT /api/v1/users/:user_id/notifications/:id`. Including a `read_at` date or similar.

**Comment by juanignaciosl** [comment]
@xavijam what do you think?

**Comment by xavijam** [comment]
If the notification is created, PUT in my opinion, but as you wish guys 🤗 . It is true that we will need to get all current notifications and then play with them, so... PUT sounds better.

**Comment by juanignaciosl** [comment]
The thing about `PUT` is that a user can only modify whatever marks it as read (either a flag or a read date), which is somehow implicit. Neverthess, a "`POST` on the reads of a notification" is explicit on that (and implicitly marks as read). But it's not too common.

PS: note that the persistence won't match the API, as the notification is likely to be shared with all users, so the "read status per user" will be stored somewhere else. Storage can be also change depending on #11678 open questions.
