### ISSUE TITLE
Colors reset, when I click on styles value fill

### ISSUE THREAD

**Issue by mroswell** [CartoDB/cartodb#11683]
### Context
*Please explain here below what you were doing when the issue happened*
I wanted to tweak the colors
 

### Steps to Reproduce
1. Navigate to builder > layer > Style > Values
2. Click on Fill box with colored entries

### Current Result
The styles switch to default colors, and lose the carefully selected colors. Poof, all gone.

 

### Expected result
I expect my existing colors to remain, and then I could selectively make changes in an individual color option.

### Browser and version
Chrome
 
### Additional info
My user name is 'map'. Happy to switch to mroswell if that fixes the problem.

UPDATE: I spoke to other Carto users today who all signaled that they had encountered the same problem.

**Comment by xavijam** [comment]
Hi Marjorie! Thanks for coming to Github and opening these issues 🤗 . About the problem, sorry but I don't get the issue, probably I'm missing something, but in any case, I've prepared some possible scenarios:

1. If you select a number column, ramp list appear, and how to edit a ramp (or you can select any other).

![style-ramp](https://cloud.githubusercontent.com/assets/132146/23502567/9620f88a-ff38-11e6-92a3-8ca565f6ff5d.gif)
 
2. If you select a style column, categories list appear, and how to edit each category.

![style-categories](https://cloud.githubusercontent.com/assets/132146/23502601/a8b432b4-ff38-11e6-95c1-a19c943638e8.gif)

3. In case you are using "by value" tab and accidentally "solid" tab is clicked, you can get back to a previous style (we feel it is a great addition).

![styles-problem](https://cloud.githubusercontent.com/assets/132146/23502657/dfd75c26-ff38-11e6-8ed3-0ea429ffdfa7.gif)

**Comment by xavijam** [comment]
Issue solved?

**Comment by mroswell** [comment]
No, not resolved. Was just at a conference with extremely limited internet access for a week. (At the conference I met several other users who mentioned the same issue.) I was working on a choropleth map... maybe the issue doesn't show up for dots? The reset colors issue occurs when clicking category colors next to Fill

I am reluctant to make a video, because I don't want to mess up my colors again, but I'm curious as to the tool you used for making the animated gifs?

I hope you're able to replicate the issue... it's real.

**Comment by xavijam** [comment]
For GIFs we usually use http://www.cockos.com/licecap/. About the problem, you can create a another map and reproduce the bug (recording it with the tool mentioned). I'm not saying the bug is not there, but I'd like to know how you are having that bad time and fix it asap.
