### ISSUE TITLE
Requesting different favicon for builder edit vs. builder embed page

### ISSUE THREAD

**Issue by mroswell** [CartoDB/cartodb#11682]
### Context
I am making two maps, and I need at least four tabs open. It would be great if the favicon for the builder embed page were easily distinguished from the edit pages. 

I like the favicon by the way, but maybe the embed URL could be a different color?

**Comment by xavijam** [comment]
That's a great idea, thanks!

**Comment by mroswell** [comment]
Probably also good to add a different color for datasets, too, vs maps vs embeds
