### ISSUE TITLE
Automatic notification on new organization user

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#11681]
When a new organization user is created, new notification is created (and an email is sent).

Open questions:
- Both in organization signup and organization settings page? @saleiva 
- Can't this be disabled? I don't think that this should be broadcasted, for example, at universities. It's likely to be disabled by default, IMHO. @saleiva 
- What information does the notification contain? @saleiva 
- Design needed @saleiva 

cc @xavijam

**Comment by noguerol** [comment]
Notifications about account activation and charge codes are per user, not broadcasted to the whole organization.

cc @asimcox for clarifying the points about the content of notifications and emails themselves

**Comment by saleiva** [comment]
yep. This has nothing to do with the notifications. Notifications are always broadcasted

**Comment by asimcox** [comment]
Hi Gang - few comments:

**UI Notifications** - pls reference the client business and functional requirements in this [client-facing BCG Repo ticket 60](https://github.com/CartoDB/BCG/issues/60) and the [Associated Design ticket](https://github.com/CartoDB/design/issues/582).

To clarify, there are two types of UI Notifications:
1. Automated Notifications
@noguerol is correct. Automated notifications about "charge codes, account activation, account disabled, account extension' will only appear in a particular user's dashboard. (see ticket for all notification states/scenarios)

2. Manual Notifications (created and sent by the Admin)
These notifications will get broadcasted across the entire organization, depending on the group that Admin selected: All; Builder; Viewer.

**Email Notifications** - pls reference the client business and functional requirements in this [client-facing BCG Repo ticket 57](https://github.com/CartoDB/BCG/issues/57)

let me know if you have more questions!

**Comment by juanignaciosl** [comment]
After talking to @asimcox , it's clear that _manual_ notifications, the ones that are handled in this milestone (https://github.com/CartoDB/cartodb/milestone/136), *do not* trigger emails. Only "automatic notifications" do.

**Comment by noguerol** [comment]
So, recapping:

1. Both in organization signup and organization settings page? **I don't get this question**
Can't this be disabled? **No**
2. What information does the notification contain? **manual notifications are custom text with limited amount of characters (TBD by @CartoDB/design) and automated notifications are predefined, with copywriting provided by @asimcox** 
3. Design needed --> **emails are handled by @CartoDB/solutions so I assume also their templates**

**Comment by juanignaciosl** [comment]
1. The document says "(it) will send email notifications (...) When a new account is activated.". There's no such "account activation" within CARTO, so I assume that it's the same than "when a new _organization_ account is **created**. You can create organizations accounts in two ways: organization settings (by the owner) and organization signup page (`/signup`), by the user. So, if a mail is meant to be sent on user creation, we should know in which of those scenarios. Pinging @danicarrion , as email notifications are on their side.
2. Ok.
3. My question was about the email, which I hadn't seen.
4. Ok (this also answers 3).
