### ISSUE TITLE
Email CARTO Gear API

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#11692]
#In order to enable creating notifications and emails from Rails engines, we must provide an API for that:

- [ ] ~Remove ActiveRecord from CartoGearsAPI classes. Maybe add some documentation about creating wrappers for domain models that can be used in forms?~
- [ ] ~Notifications write API: #11677. Only creation is needed.~ Moved to #11850
- [ ] ~Creation: `POST /notifications`. Authentication: user. This is meant to be used as an external API, not through the UI. Probably not needed as a REST API. Check #11692 and talk to @AleGoiko and @danicarrion about this.~ Moved to #11850 
- [ ] Email API.

As automatic notifications are a limited set, consider reusing notifications: instead of "creating a new notification" semantics, "send a known notification".

cc @danicarrion @AleGoiko @javitonino @asimcox

**Comment by juanignaciosl** [comment]
@asimcox who are automatic notifications sent to? The notification API for manual notifications (#11677) supports notifications for all/builder/viewer within an organization, but I think that automatic notifications are sent to specific users, so the API should be improved in order to support "per user" notifications. Could you please confirm?

cc @danicarrion

**Comment by asimcox** [comment]
@juanignaciosl automatic notifications are dependent on an individual users' 'account' status and actions. Please see the various Auto-generated UI Notification States in the reference ticket *66* above.  Does that answer your question?

**Comment by juanignaciosl** [comment]
Not really. I don't mind _when_ are automatic notifications triggered. I need to know which user should read them. What "ticket 66" are you talking about? Above tickets are #11676 and #11677, and they're about manual notifications, not automatic ones.

**Comment by juanignaciosl** [comment]
Ok, now I see: a single user _can_ receive a notification, through the API. I've updated #11677 👍 

As the notification is "automatic" I'm not sure about the authentication of that endpoint, so for the moment I've written down that it has "user authentication", meaning that the API should use user's API key cc @danicarrion
