### ISSUE TITLE
Add geometry keeps in edit mode after saving it

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#11696]
### Steps to Reproduce

1. New Map --> New Empty Map
2. Go to the empty layer and draw a polygon.
3. Press save

### Current Result

Geometry is saved, but if you click in the map, you keep adding points.

 

### Expected result

Geometry is saved, and if you click in the map, you begin creating a new geometry.

**Comment by saleiva** [comment]
cc/ @noguerol

**Comment by xavijam** [comment]
That was a decision we took (good or bad) when we implement it. If we think we should change it, let's go for it! :).
