### ISSUE TITLE
Modify font style for the "You have run out of quota" module

### ISSUE THREAD

**Issue by csobier** [CartoDB/cartodb#11690]
I received this dialog while testing today, not a showstopper but the font style is not the same as the other modules. I thought that I would let Design know. @saleiva 

![image](https://cloud.githubusercontent.com/assets/13319925/23524843/6211e758-ff5a-11e6-8acf-65670f556514.png)

**Comment by saleiva** [comment]
Thanks @csobier !

**Comment by saleiva** [comment]
Prioritizing since it's a long hanging fruit and such an important CTA

**Comment by xavijam** [comment]
:+1:

**Comment by javitonino** [comment]
Production ready!
