### ISSUE TITLE
Remove Builder activation notification for new users

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#11709]
### Context
Builder activation message currently shows on every new user, while it only should on users coming from Editor. 
 

### Steps to Reproduce

1. Create a new account

### Current Result
You get the "CARTO Builder has been activated on your account (...)" notification
 

### Expected result
No notification should appear, as Builder is now our only product.

**Comment by saleiva** [comment]
PLEASE

**Comment by xavijam** [comment]
Deployed!
