### ISSUE TITLE
Torque + choropleth issues

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#11719]
### Context

* As I understand Torque + TurboCARTO category ramps work fine, but it is another issue when you select other classification methods ramps (choropleth). But surprisingly, at the beginning, it looks like the later works in BUILDER, but then after refreshing or getting the embed the map breaks.

### Steps to Reproduce

1. Create a map using `all_day` dataset (earthquakes)
2. Select `ANIMATED` style
3. Style `BY VALUE`
4. Select other classification method but `Category`
5. Publish

### Current Result

* At the beginning Torque works, showing a choropleth color ramp. But it shows an error:

![seleccion_003](https://cloud.githubusercontent.com/assets/5215798/23699699/60abed1a-03f0-11e7-9f11-b1d7e0f8b390.png)

* However after refreshing it does not work. Logically, [the embed](https://solutionscdb.carto.com/u/ramirocdb/builder/bc9b039a-03e6-11e7-aa11-0e233c30368f/) does not work either.

![seleccion_004](https://cloud.githubusercontent.com/assets/5215798/23699807/cc6f6aae-03f0-11e7-84df-2fbcfcad5c52.png)

### Expected result

* If Torque + some classification methods are not supported, we should not allow users to implement it from BUILDER UI.

### Browser and version

* Google Chrome v56.

### .carto file

* [all_day map (on 2017-03-08 at 10.10.16).carto.zip](https://github.com/CartoDB/cartodb/files/827279/all_day.map.on.2017-03-08.at.10.10.16.carto.zip)

### Additional info

* This come from [a tweet](https://twitter.com/giannagruen/status/839407107535417344), we should contact her on SB later.

**Comment by AbelVM** [comment]
Looks like a duplicated of https://github.com/CartoDB/cartodb/issues/10947
