### ISSUE TITLE
Editor video tutorials on new accounts

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#11710]
### Context
On new users on-boarding, users are still offered with Editor "video tutorials"

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Create a new account
2. Follow the steps for creating a new map with the wizard

### Current Result
On the "add dataset" modal, you get a "Or you can start with a video tutorial" link that drives to another window with Editor video tutorials

![captura de pantalla 2017-03-06 a las 16 45 49](https://cloud.githubusercontent.com/assets/70603/23622991/177478c4-02a1-11e7-9203-2ab2ba341443.png)
 
### Expected result
We should link to /learn guides

**Comment by saleiva** [comment]
that section should be removed forever ASAP.

**Comment by csobier** [comment]
This issue can probably be closed. (See Dup issue here specifically about the [Add Dataset](https://github.com/CartoDB/cartodb/issues/8679) module, which was fixed awhile ago).

[New issue here](https://github.com/CartoDB/learn/issues/361), but I think I remember @saleiva saying he wanted to remove all those video links regardless? Can't find that issue though...

**Comment by xavijam** [comment]
Closing this one in favor of https://github.com/CartoDB/learn/issues/361. Thanks @csobier!
