### ISSUE TITLE
geometry edition available on aggregated styles

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#11714]
### Context
With an aggregated style applied, you can click on one of the grid cells and the geometry edition icon will appear. 

It will also let you edit properties from the underlying points layer, but the feature selected is totally inaccurate
 

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Create a point's map and use an aggregated style visualization (Import [this .carto](https://github.com/CartoDB/cartodb/files/824860/geometry.edition.on.agg.styles.on.2017-03-07.at.14.12.28.carto.zip) to have it directly) 

2. click on a grid cell the geometry edition button should appear
3. click on the geometry edition button, the left panel will update with info from an (apparently) random geometry

### Current Result
geometry edition is available for aggregated styles

![screen shot 2017-03-07 at 14 59 32](https://cloud.githubusercontent.com/assets/10940006/23663552/28ef5472-0353-11e7-843d-50a9e02cd007.png)

### Expected result
aggregated styles shouldn't allow geometry edition

### .carto file

[geometry edition on agg styles (on 2017-03-07 at 14.12.28).carto.zip](https://github.com/CartoDB/cartodb/files/824860/geometry.edition.on.agg.styles.on.2017-03-07.at.14.12.28.carto.zip)

**Comment by rjimenezda** [comment]
Whenever the edit geometry button is disabled, it displays an error like this:

"Feature editing is disabled in %{disabledLayerType}. To edit the data, export this layer and import it as a new layer."

@brittanymicek would 'layers with aggregated styles' work as the copy in this case?

**Comment by brittanymicek** [comment]
@rjimenezda Can you give me context as to where you'd like the clause, 'layers with aggregated styles' to fit within that error message?

Here are some examples, based on intuition, but I am not sure if they meet you need:
- "Sorry but feature editing is disabled in %{disabledLayerType}. To edit data layer(s) with aggregated styles, export this layer and import it as a new layer."

Question: when the user exports the layer and imports it as a new layer, are they just re-importing the old layer (sort of like a refresh) or are they importing an edited/styled new layer?

- "Sorry but feature editing has been disabled in %{disabledLayerType}. To include layers with analysis nodes, ______"

- "Sorry but feature editing has been disabled in %{disabledLayerType}. To include layers with applied custom SQL, _____"

**Comment by rjimenezda** [comment]
Sorry about lack of context 😅  

The 'layers with aggregated styles' goes in the %{disabledLayerType}

This is how it looks:

![screen shot 2017-06-07 at 17 39 11](https://user-images.githubusercontent.com/446970/26887440-5085b42a-4ba8-11e7-87b6-5f5134fc1780.png)

About the question, maybe that 'export and import' bit does not make any sense in this case 🤔  If you export a layer with aggregated styles and you import it again, it's just a new layer with the same points.
