### ISSUE TITLE
Double escape of HTML entities in widget prefix/suffix

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#11726]
### Steps to Reproduce
1. Create a map
2. Add a formula widget
3. Set a prefix with HTML content, e.g: `<`

### Current Result
The `<` is converted to `&lt;`
![screenshot_20170308_165213](https://cloud.githubusercontent.com/assets/7569673/23711295/b4bea81e-041f-11e7-9743-8ed62f99d3d4.png)
 
### Expected result
`<` is displayed

**Comment by javitonino** [comment]
Still present. cc @ivanmalagon @ramiroaznar

**Comment by ramiroaznar** [comment]
Moved to the RT kanban.

**Comment by elenatorro** [comment]
In production 🚀
