### ISSUE TITLE
Placement property doesn't update CartoCSS code

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#11728]
### Context

when trying to set up labels for a polygon layer, _PLACEMENT_ setting on the UI doesn't update the CartoCSS code accordingly, and the map is not reloaded
 

### Steps to Reproduce

1. Create a map with a polygon layer
2. Go to _STYLE_ tab and click on the _LABELS_ checkbox
3. Change value in _PLACEMENT_ input

### Current Result
* The map is not re-instantiated
* If you change to CartoCSS view, there has not been any change on the `placement` property

### Expected result

CartoCSS code should be updated with the _PLACEMENT_ settings, and the map should be re-instantiated with the proper `placement` CartoCSS property

cc/ @saleiva

**Comment by ramiroaznar** [comment]
This was fixed here https://github.com/CartoDB/cartodb/issues/13015
