### ISSUE TITLE
Mapzen isoline tracts support

### ISSUE THREAD

**Issue by nobuti** [CartoDB/cartodb#11723]
Mapzen isolines support, by now, a max of 4 contours (tracts). You can check it with this request:

```
http://matrix.mapzen.com//isochrone?json={"locations": [{"lat": 40.42028, "lon": -3.70568}], "costing": "pedestrian", "polygon": true, "contours": [{"color": "tbd", "time": 5}, {"color": "tbd", "time": 15}, {"color": "tbd", "time": 20}, {"color": "tbd", "time": 25}, {"color": "tbd", "time": 30}]}&api_key={{matrix_api_key}}
```

the result for that request is:

```
{
  "error_code": 152,
  "error": "Exceeded max contours:4",
  "status_code": 400,
  "status": "Bad Request"
}
```

We need to apply this constraint in the UI for the isolines analysis form. Right now, the maximum is 6 no matter which the provider it is (mapzen or heremaps).

**Comment by xavijam** [comment]
Hey, take into account we don't know anything about providers in the frontend...

**Comment by xavijam** [comment]
I strong believe frontend side should not know anything about providers.

**Comment by saleiva** [comment]
guysm let's put 4 as max for the time being for everything

**Comment by jorgesancha** [comment]
Is there a way for us to see how many times we are getting that error? It should be fixed anyhow, but I want to get a sense of how big of a problem this is

**Comment by xavijam** [comment]
4 set!
