### ISSUE TITLE
Organization notifications basic UI

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#11729]
Basic UI for #11676 

Must-have:
- [x] Feature-flag based tab.
- [x] Textarea.
- [x] User types.
- [x] Notification type
- [x] Submission.

Nice-to-have:
- [x] Listing (erb or `GET /api/v2/organization/:id_or_name/notifications`). Authentication: org owner. The UI will always request the 12 last ones, and backend should default to page 1, size 12, but we can build a normal paged endpoint, as it's straighforward. This is not needed if the UI is implemented with an ERB.

- [x] Icon.
- [ ] Full support for markdown (styles get overriden).
- [x] Resend.
- [x] Remove.

**Comment by saleiva** [comment]
about markdown support, if it makes easier, I'd just strip everything from the parsed HTML but the links.
