### ISSUE TITLE
hex & rgba labels in colorpicker have the wrong font

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#11730]
### Context

hex & rgba labels have serif font, while they are supposed to be sans serif
 

### Steps to Reproduce

1. go to a map
2. go to a points layer, or create one
3. open color picker

### Current Result

labels font is serif
 

### Expected result

labels font should be sans serif

### Additional info

![group](https://cloud.githubusercontent.com/assets/36676/23745470/a74f97a8-04b8-11e7-8f06-72a763751b0c.png)

**Comment by saleiva** [comment]
Good catch mate.

**Comment by xavijam** [comment]
Which font would it be @CartoDB/design ?

**Comment by matallo** [comment]
I'd bet `.CDB-Text` will do the trick

**Comment by arianaescobar** [comment]
font-family: OpenSans;
font-size: 9px;
color: #CBCED3;
line-height: 12px;

:)

**Comment by nobuti** [comment]
Fixed in https://github.com/CartoDB/cartodb/pull/9795
