### ISSUE TITLE
Layer UI disappears after analysis selection when not having cdb_service_quota_info

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb#11745]
### Context
*Please explain here below what you were doing when the issue happened*

 

### Steps to Reproduce && Current Result

 
![cdb_service_quota_info](https://cloud.githubusercontent.com/assets/45346/23855436/e2395a3a-07f5-11e7-8863-9e7daf8acef4.gif)

### Expected result
Don't fail when `cdb_service_quota_info` function does not exist if the analysis doesn't require it.

### Browser and version
Google Chrome Version 56.0.2924.87 (64-bit)

**Comment by xavijam** [comment]
In production!
