### ISSUE TITLE
Change button copy of the quota pre-check

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb#11749]
It should be "Confirm" instead of "Apply" since the title of the infobox is "Confirm your analysis"

From https://github.com/CartoDB/camshaft/issues/238
![](https://cloud.githubusercontent.com/assets/16247628/22514946/3f5888f4-e8a1-11e6-83a0-1f110c7b1ea8.png)

Supersedes https://github.com/CartoDB/camshaft/issues/271.

cc @xavijam @noguerol @arianaescobar

**Comment by xavijam** [comment]
😂 , thanks @rochoa, already @arianaescobar has warned us about it. Seriously, 🤗 .

**Comment by xavijam** [comment]
What is the PR?

**Comment by xavijam** [comment]
Deployed
