### ISSUE TITLE
map is not being refreshed after row deletion in layer view

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#11759]
### Context
when removing a row with geometry neither the panel nor the map is being refreshed

if the url is reloaded the map works as expected 

### Steps to Reproduce

1. create a map
2. enter an empty layer
3. add a feature (point)
4. go to table view (bottom right action button)
5. remove row with geometry
6. go to map view (bottom right action button)
 

### Current Result
panel has point forms, and point is still represented in the map

### Expected result
map should refresh and style panel should warn the layer has no geometry, no errors in the console

### Additional info

![5a403d75-1f2b-46fd-aa51-01b234afe44d](https://cloud.githubusercontent.com/assets/36676/23902152/6a040148-08c0-11e7-9a03-90407ca0fa68.png)
![b271e3f2-7590-4fe2-8c98-fac80d7ec8f7](https://cloud.githubusercontent.com/assets/36676/23902153/6a058d10-08c0-11e7-9ee1-9d701c4ba186.png)

/cc @xavijam this is happening in production, indeed

**Comment by nobuti** [comment]
Implemented here: https://github.com/CartoDB/cartodb/pull/12125/commits/e548811446923a6d5b2a8c586f9660bdbecb92db
