### ISSUE TITLE
Trigger an event when a user is created

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#11751]
In order to be able to build features on user creation, it should trigger an event.

The reader of the event should be able to distinguish the following:

- [ ] User creation through external API.
- [ ] User creation through organization owner page.
- [ ] User signup at organization page.

- [ ] Document it.

cc @danicarrion

**Comment by juanignaciosl** [comment]
This is already done: #11878

cc @javitonino @danicarrion @AleGoiko

**Comment by xavijam** [comment]
💃
