### ISSUE TITLE
Rake Task to set max_import_file_size and max_import_table_row_count

### ISSUE THREAD

**Issue by rporres** [CartoDB/cartodb#11756]
### Context

Working on community edition of builder. I would like to have a rake task to set `max_import_file_size` and `max_import_table_row_count` to some chosen values
 

### Additional info

I'm very willing to write this myself if necessary and have it reviewed. I would need some additional info, though

* Should the rake task fail if we try to set up `max_import_file_size` greater than `quota_in_bytes`? I'd say yes, but just want to check
* We should clarify what the rake should do in case user belongs to an org. Currently builder sets those limits to the owner for every org user created, so the task would take into account.

Finally this is something we may not want to do...

**Comment by juanignaciosl** [comment]
About your questions:
- Maybe, but that's not rake concern but model one. Let's address it in #11758.
- Assign it to an organization user will override the one previously copied from the organization owner. IMHO, that might make sense for special users, so I wouldn't treat an organization user as an special case.

**Comment by juanignaciosl** [comment]
@rporres single user, by username?

**Comment by rporres** [comment]
That should work, @juanignaciosl

**Comment by javitonino** [comment]
This is in acceptance in Builder board. @rporres do you want to test it yourself? Also, I'd like to learn more about this community edition, I'll grab you at some random point and shoot some questions your way.

**Comment by juanignaciosl** [comment]
@rporres can you do the acceptance, as this was your need? No hurry, but we'd like to know :-)

**Comment by rporres** [comment]
hey, sorry. I had forgotten to answer.

Sure I will do the acceptance. It will be delayed maybe one or two days. Is that ok?

**Comment by juanignaciosl** [comment]
Yes, no problem, I just wanted to know :-) I'll assign it to you so we know the reason for the delay.

Thanks!

**Comment by jvillarf** [comment]
## CR and review

**PR:** https://github.com/CartoDB/cartodb/issues/11772

- **Test1:** modify existing users (Organization owner included)

```` bash
cartodb_production=# select username,max_import_file_size,max_import_table_row_count from users;
 username | max_import_file_size | max_import_table_row_count 
----------+----------------------+----------------------------
 user1    |            157286400 |                     500000
 carto    |            157286400 |                     500000

carto_rake "cartodb:set_import_limits["user1",1057286400,1000000]"
carto_rake "cartodb:set_import_limits["carto",1057286400,1000000]"

postgres cartodb_production -c "select username,max_import_file_size,max_import_table_row_count from users;"
 username | max_import_file_size | max_import_table_row_count 
----------+----------------------+----------------------------
 user1    |           1057286400 |                    1000000
 carto    |           1057286400 |                    1000000
(2 rows)
````

- **Test2**: Create a new user and check it properly inherits Org Owner limits

```` bash
root@omnibus-i-builder-dataservices-rhel6-user-jvillarf:/opt/carto/builder-tools/embedded/bin# psql -U postgres cartodb_production -c "select username,max_import_file_size,max_import_table_row_count from users;"
 username | max_import_file_size | max_import_table_row_count 
----------+----------------------+----------------------------
 limitok  |           1057286400 |                    1000000
 user1    |           1057286400 |                    1000000
 carto    |           1057286400 |                    1000000
(3 rows)
````

So, the rake task works fine. Thanks a lot!

@javitonino @juanignaciosl you can move this ticket to the next phase!

**Comment by rporres** [comment]
Thx for taking care, @jvillarf

**Comment by javitonino** [comment]
Merged!
