### ISSUE TITLE
Wrong heatmap template

### ISSUE THREAD

**Issue by iglosiggio** [CartoDB/cartodb#11765]
### Context
When the heatmap template is used via the wizard the CartoCSS generated throws this error
```
line 15: Invalid value for marker-fill-opacity, the type float is expected. 0.4*[value] (of type field) was given.
```

**Comment by xavijam** [comment]
Hi @iglosiggio, you mean in the editor?.

**Comment by iglosiggio** [comment]
@xavijam exactly!

**Comment by xavijam** [comment]
Unfortunately we don't provide editor support anymore (in favor of Builder). I encourage you to write in our [Google Group](https://groups.google.com/d/forum/cartodb) in case any other user has found this problem.

**Comment by iglosiggio** [comment]
Oh, well then. Closing this.
