### ISSUE TITLE
CartoCSS property text-wrap-width not working

### ISSUE THREAD

**Issue by makella** [CartoDB/cartodb#11768]
### Context
Using the property `text-wrap-width` to wrap long text labels

### Steps to Reproduce
1. Label features
2. Add the text property `text-wrap-width` with a value to the labeling CartoCSS

### Current Result
<img width="516" alt="screen shot 2017-03-15 at 12 05 00 pm" src="https://cloud.githubusercontent.com/assets/1566273/23945650/96e28b32-0977-11e7-9ee5-98a4981a7abf.png">

### Expected result
<img width="477" alt="screen shot 2017-03-15 at 12 05 18 pm" src="https://cloud.githubusercontent.com/assets/1566273/23945638/8844417e-0977-11e7-856a-f43a54c240dc.png">

### Browser and version
Chrome

cc @dgaubert

**Comment by xavijam** [comment]
I feel this ticket should not be here, should it be in windshaft @dgaubert?

**Comment by michellechandra** [comment]
SB: 12077178 

@dgaubert - is there any update on this issue? an Enterprise user is asking regarding this property not working.

**Comment by dgaubert** [comment]
> I feel this ticket should not be here, should it be in windshaft @dgaubert?

My bad, I told her to open the issue here. I've just created a [new one in windshaft](https://github.com/CartoDB/Windshaft/issues/547), also r0choa was assigned to put it in the queue. So.. @xavijam feel free to close this one.

**Comment by xavijam** [comment]
Thanks man 💋
