### ISSUE TITLE
toggle layer visibility with context menu, doesn't affect analysis panel

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#11767]
### Context
when you are inside a layer and make a layer hidden the analysis panel is not disabled and the infobox don't appear until you refresh

this works properly in other panels like style

### Steps to Reproduce

1. go to a map
2. enter a layer
3. go to analysis panel
4. click in hide layer in context menu

### Current Result
the panel remains the same

### Expected result
disable overlay and infobox should appear

### Additional info

see captures of the str

![85159a46-f0bc-440c-b98e-ef13671b3876-1](https://cloud.githubusercontent.com/assets/36676/23944875/bb926b1c-0974-11e7-89ff-4902593b9aa7.png)
![20715594-80fe-4b7f-a10c-2cdb636a6ee1-1](https://cloud.githubusercontent.com/assets/36676/23944876/bbc4e8f8-0974-11e7-8540-d16261ed3fa4.png)
after refresh
![e92b8311-e759-41c5-8c51-351aa0c0a437](https://cloud.githubusercontent.com/assets/36676/23944996/1eb6814c-0975-11e7-8688-cb90560c6563.png)

**Comment by ivanmalagon** [comment]
Shipped! :shipit:
