### ISSUE TITLE
Context menu view not being correctly disposed

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#11778]
### Context
While passing tests, we ran into a weird random problem that left orphan DOM nodes. After doing some research and thanks to the magic touch of @xavijam we discovered the source of the problems.

`context-menu-view` is used as a subview of `data-layer-view`. When hiding the context menu, we call `remove` instead of `clean`. This leaves context menu events attached to document.

Current function
```
  _hideContextMenu: function () {
    this._menuView.remove();
    this.removeView(this._menuView);
    delete this._menuView;
  }, 
```

Tasks:
1. Change that `.remove` call to `clean`

1. Look in other views that hides the context menu in the same way and refactor them also.

Note:
Changing `.remove` to `.clean` fixed the problem, but it's fixed in another research branch. That's why I've opened this ticket, to fix it as soon as possible in the regular codebase.

**Comment by xavijam** [comment]
Merged and deployed!
