### ISSUE TITLE
LDAP settings style is outdated

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#11774]
In a organization with LDAP settings, the styling (auth tab) is wrong:

![captura de pantalla 2017-03-15 a las 16 56 51](https://cloud.githubusercontent.com/assets/932968/23957831/a37dc838-09a0-11e7-87bf-31a4c3a10998.png)

**Comment by juanignaciosl** [comment]
Oh, while doing a refactor for #11729 I've found an elegant fix for this:

![captura de pantalla 2017-03-16 a las 11 53 30](https://cloud.githubusercontent.com/assets/932968/23993005/3fc1f112-0a3f-11e7-813b-4b4a40cdaca8.png)

^ is this enough, @xavijam ? @azamorano have you ever seen this page? I have not. If this was the previous appearance, I'll just keep this.

**Comment by xavijam** [comment]
Well, we have our great inputs and so on. Could we use them?

**Comment by juanignaciosl** [comment]
It's not meant to be editable. I mean, this is obviously super minor, I think that returning to the previous look and feel is good enough.

**Comment by saleiva** [comment]
Non editable should be reflected as disabled inputs IMO

**Comment by xavijam** [comment]
Agree with @saleiva. It should be easy @juanignaciosl, so don't worry about that.

**Comment by azamorano** [comment]
I had never seen it before @juanignaciosl.
