### ISSUE TITLE
Enable Google Maps export for "Export as an image"

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#11775]
Currently the "Export as an image" feature doesn't export Google Maps basemaps. We should enable this so we always export geometries and the underneath basemap.

See [this issue](https://github.com/CartoDB/cartodb/issues/10822) for some hints on how to implement this feature using Google's Static Map API.

- [x] Export defaults / non-styled Google Maps basemaps.
- [x] Export styled Google Maps basemaps.
- [x] Allow panning the basemap when the image export widget is active.
- [x] Apply Google Maps limits in the export image form and warn the users.
  - [x] For regular users.
  - [x] For Google Maps Premium users.
- [x] Add attribution to the exported image.
- [x] Add CARTO logo to the exported image.
- [x] Remove menu in the export image form header. 

PR: https://github.com/CartoDB/cartodb/pull/11891

**Comment by xavijam** [comment]
So, we have discussed it offline, but we should not be worried about Google's Premium Plan members because there are not that type of customers.
But in any case, we could use the current "fields" in order to add new params and make use of them wherever we want.

**Comment by noguerol** [comment]
Talked offline, just updating the ticket:

· Only users with a "pay-as-you-go" license should use a digital signature
· Digital signatures could be appended if needed to the API key as a single text string, so changes are needed in the admin panel

Besides, there are image size limits: https://developers.google.com/maps/documentation/static-maps/usage-limits

· Free and pay-as-you-go: 640x640px
· Premium annual plan: 2048x2048px

**Comment by javierarce** [comment]
Capture with our logo and the attribution. What do you think? 

![untitled map 1](https://cloud.githubusercontent.com/assets/4933/24395591/74424bf2-13a0-11e7-82c1-c42cdc8ed666.png)

**Comment by xavijam** [comment]
I love it :dancer:!

**Comment by javierarce** [comment]
In certain cases, when the license of the Google Maps is very long, we could end up having this issue:

![untitled map 1 17](https://cloud.githubusercontent.com/assets/4933/24397530/c3e0ecda-13a6-11e7-9718-23a468180097.png)

… so a solution is to check for the width of the attribution in the html and apply a tiny margin:

![untitled map 1 21](https://cloud.githubusercontent.com/assets/4933/24398258/26005476-13a9-11e7-9b1a-5862e80704f9.png)
![untitled map 1 20](https://cloud.githubusercontent.com/assets/4933/24398260/2610dd28-13a9-11e7-886b-7deb2226c6b6.png)

**Comment by xavijam** [comment]
:+1:

**Comment by xavijam** [comment]
hey guys, I've just realized that, our tiles could hide Google logo and attribution.

![kortkort](https://cloud.githubusercontent.com/assets/132146/24514638/44739102-1575-11e7-98ba-79cdf27e674a.png)

**Comment by javierarce** [comment]
:( We could add their logo and the attribution like we do with ours, but we'll need to match the position so it doesn't look bad.

**Comment by saleiva** [comment]
I'd not block the release because of this. I'd keep this open as an bug for the future

**Comment by jorgesancha** [comment]
+1

**Comment by xavijam** [comment]
Yep yep, violent agreement.

**Comment by xavijam** [comment]
Ticket added https://github.com/CartoDB/cartodb/issues/11896, out of milestone 💋 . _circulen_

**Comment by saleiva** [comment]
should I do acceptance on this?

**Comment by noguerol** [comment]
I have some more concerns about cross marks, which should be limited to the max size limits, cause:
a) Is weird to drag a bigger crop area even tho it will not work
b) When exceding size limits in manual input, the crop should resize to the max allowed value, while now it sizes itself to an unknown range
c) When exporting that unknown but out of the limits range, a same ratio image is exported, but that of a different part of the map

**Comment by xavijam** [comment]
All yours @javierarce for tomorrow morning :kick_scooter: .
