### ISSUE TITLE
Rake task for soft geocoding limits

### ISSUE THREAD

**Issue by jvillarf** [CartoDB/cartodb#11777]
Hi guys,

related with ticket https://github.com/CartoDB/onpremises/issues/273 it would be nice to have a **rake task** to set **soft geocoding** limit values per user:

````
soft_here_isolines_limit
soft_obs_general_limit
soft_obs_snapshot_limit
soft_mapzen_routing_limit
````

Thanks!

**Comment by rochoa** [comment]
Hello @jvillarf 👋 ,

Do we need this for an specific release (date) of onpremises?

**Comment by jvillarf** [comment]
Helloooooooooo my dear friend @rochoa :)

We still don't have an official date, but we expect to have a tentative one soon (today), so i'll update the ticket once we know it :+1:

**Comment by jvillarf** [comment]
Hi @rochoa we don't have an official date yet, but if it would be great if it could be finished for April, 7th. How does it sound? Thanks!

**Comment by rafatower** [comment]
PR: https://github.com/CartoDB/cartodb/pull/11917

**Comment by jgoizueta** [comment]
Acceptance plan has been added in [PR](https://github.com/CartoDB/cartodb/pull/11917#issuecomment-292204324).

This and #11823 should be accepted together.

**Comment by jgoizueta** [comment]
Here's the documentation for the new rake tasks: https://github.com/CartoDB/cartodb/blob/master/doc/manual/source/operations/configure_data_services.rst#soft-limits
