### ISSUE TITLE
Toggled widget covers up the widget menu

### ISSUE THREAD

**Issue by mbforr** [CartoDB/cartodb#11770]
### Context

If a widget is toggled to off and you click on the menu (blue dots), you cant see the menu.
 

### Steps to Reproduce

- Toggle a widget
- Click the menu

### Current Result

![screen shot 2017-03-15 at 10 11 24 am](https://cloud.githubusercontent.com/assets/4828460/23952403/c7c2b444-0967-11e7-9278-a612f553efee.png)

### Expected result

- Should be able to see the menu

### Browser and version

Chrome

**Comment by xavijam** [comment]
Duplicated https://github.com/CartoDB/cartodb/issues/11790.
