### ISSUE TITLE
[SMOKES] Making a loading decision, raster or vector?

### ISSUE THREAD

**Issue by donflopez** [CartoDB/cartodb#11783]
### Context
We are loading vector tiles under a flag, with the beta release we have to set VT by default, but we are a step behind raster in some scenarios.

1. [tangram-cartocss not supported features](https://docs.google.com/spreadsheets/d/1zvFU4F07u_RLW605AB7u8qbjZNMKbnRaF3QfmFXNGHo/edit#gid=1244395638)

2. cartocss dynamic features not suported in tangram.

3. Huge amount of shapes to draw where tangram rendering can take a lot of time.

4. Drastic visual differences between raster and vector.

Based on those reasons, we need a dynamic decision maker, allowing us to bring the best user experience in those different scenarios.

### Options:

All of them can be combined.

|Action|Side| Type & Fix|Benefit|Cost|
|------|-----|-----------|-------|-----|
| Send the total amount of data to make a decision | server / client | Preventive - Fix 3 | Have a good performance | Medium |
| Run tangram-cartocss to detect not supported features | server / client | Preventive - Fix 1 & 2 | Have a good UX | Medium |
| Raster fallback if the map fails | client | Palliative - Fix 1 & 2 | Not seem broken as last resource | Medium |
| Let the user choose in the meantime | server & client | Preventive - fix everything (new maps or edited ones) | To have freedom | Medium |
| Run tangram and raster and compare screenshots to see huge differencies automatically | server | Preventive - Fix 4 (old maps) | Have a good UX | High |

NOTE: add here other solutions ^^

cc/ @javisantana & @rochoa

**Comment by javisantana** [comment]
Some comments: 

about 4, shouldn't it be based on cartocss? is there any other thing that adds differences between raster and vector?

**Comment by donflopez** [comment]
Yeah @javisantana, they're mainly cartocss problems, we have 2 factors from cartocss but the 3rd is out of it.

1. Unsupported features (the best).
2. Dynamic features supported as static in tangram.
3. Differences at rendering level, ex: textures, border point (now fixed).

**Comment by donflopez** [comment]
After looking this in detail we have some conclusions for the first step:

1.- Take the rendering decision on the client side (we have more information there).
2.- Send from the server features statistics of each layer, at the start the number of vertex per layer.
3.- This info will be sent next to the instance of the map.
4.- We'll check the number of features and  cartocss compatibility.

Some new ideas that have appeared are:
- Send the precision with the tile request.
- Get feature density from PSQL statistics.
- Implement a pipeline to aggregate data to raw geometries.

Am I missing something? Is it correct?

cc/ @javisantana & @rochoa

**Comment by alonsogarciapablo** [comment]
I talked with @donflopez and this is quite a change in the internals of CartoDB.js. But hey, we're embracing this challenge and we'll try to create something good! 👍 

We're going to spend some time to prototype this and see what issues we encounter along the way, and the different approaches that we can follow. Here's a list of "requirements" for this prototype:

- CartoDB.js will create an instance of the "map" right after the vizjson is loaded, and before 
instantiating the Leaflet / Google Maps map and layers.
- Depending on the total amount of data returned by Maps API, it'll decide whether to render CartoDB layers using raster or vector, and it'll then render the map.
- In addition to using the total amount of data returned by Maps API to decide wether to use Raster or Vector, it'll make use of tangram-cartocss to detect features that are not supported in Vector.
- ^^ This decision will need to be taken every time that a new instance of the "Map" is created (in the Maps API), and it might affect the way CartoDB layers were previously rendered (eg: perhaps CartoDB.js used raster initially but, after user filtered some data, CartoDB.js can start rendering using vector).

(:point_up: @donflopez anything else?)

Also, let's think about internal concepts that might be outdated/missing (and which might make sense to expose as part of the API).

**Comment by javisantana** [comment]
some questions comments:

- about the first point: I though we have instanciation and rendering already split. In other words, we could instanciate the map without having any view

- The 4th point is really good. I think once we have instabciated the map for the first time it should use the same decision. It'd be kind of weird if we would recreate the whole map view because of a filter. What do you think?

**Comment by alonsogarciapablo** [comment]
> about the first point: I though we have instanciation and rendering already split. In other words, we could instanciate the map without having any view.

No, we don't.

> The 4th point is really good. I think once we have instabciated the map for the first time it should use the same decision. It'd be kind of weird if we would recreate the whole map view because of a filter. What do you think?

I guess we could just replace the affected layer, but I agree that it'd create a weird effect (and of course, It'd be harder to implement).

**Comment by alonsogarciapablo** [comment]
As discussed offline, let's forget about:

> 4. ^^ This decision will need to be taken every time that a new instance of the "Map" is created (in the Maps API), and it might affect the way CartoDB layers were previously rendered (eg: perhaps CartoDB.js used raster initially but, after user filtered some data, CartoDB.js can start rendering using vector).

**Comment by donflopez** [comment]
Basic decision diagram:

![decisions](https://cloud.githubusercontent.com/assets/463462/24710818/884eea2c-1a1e-11e7-9f6b-50d977a9c2d6.png)

**Comment by javisantana** [comment]
in that diagram when the analysis change we would be deciding again raster vs vector?

**Comment by donflopez** [comment]
Yes, having the most basic approach... is to decide every time that the worst case changes.

**Comment by javisantana** [comment]
I do think we should avoid changing everything, I'd stick to the original decision to avoid making this harder

**Comment by donflopez** [comment]
I agree! The behaviour of the app can change after a refresh?

**Comment by javisantana** [comment]
yes, I'm just talking when the user is still working on the map

**Comment by donflopez** [comment]
Short description of the actual approach:

- The decision is only taken at start time.
- We only make two checks:
   1. number of vertexes (100k at the moment).
   2. valid CartoCSS.
- We are going to send statistics:
   1. Time to map (TTM).
   2. Map render time.

**Comment by alonsogarciapablo** [comment]
**Acceptance criteria**

1. Deploy the following braches to staging (it might be deployed already, ask #engine):
  - BUILDER: `SMOKES-vector-decision`
  - TILER: `664-layergroup-stats`

2. Check that BUILDER uses raster, EMBED uses vector when map has LESS THAN 100k features.
  2.1. Create a map from a dataset (with less than 100k features).
  2.2. Check that BUILDER renders using raster images (check that .png tiles are requested).
  2.3. Setup click and hover popups.
  2.4. Add a widget.
  2.5. Publish the map and visit embed.
  2.6. Check that EMBED uses vector tiles (check that .mvt tiles are requested).
  2.7. Filter data using the widget and check that map is indeed filtered.
  2.8 Check that clicking and hovering features work.

3. Check that BUILDER users raster, EMBED uses raster when map has MORE THAN 100k features.
  3.1. Add a BIG dataset to the map (look for one with more than 100k features in the library).
  3.2. Check that BUILDER renders using raster images (check that .png tiles are requested).
  3.3. Publish the map and visit embed.
  3.4. Check that EMBED renders using raster images (check that .png tiles are requested).
  3.5. Filter data using the widget and check that map is indeed filtered.
  3.6. Check that clicking and hovering features work.

4. Check that BUILDER users raster, EMBED uses raster when using some unsupported cartoCSS:
  4.1. **Remove the layer pointing to the BIG dataset.**
  4.2. Go edit style of the layer that you first added.
  4.3. Add the following property: `marker-spacing: 100;`
  4.4. Publish the map and open embed.
  4.5. Check 3.4, 3.5 and 3.6.

**Comment by alonsogarciapablo** [comment]
We found a little timing issue while testing this in staging. Before: we rendered the map and then sent the request to Maps API so when widgets got a URL they could get the Bounding Box from the map view. In this PR we're changing the order of these things and we need to ensure that widgets don't fetch unless they have access to the bounding box (ie: map view has been created and bounds have been set in the map model). (cc: @donflopez @xavijam)

**Comment by alonsogarciapablo** [comment]
☝️ This is related to https://github.com/CartoDB/cartodb.js/issues/1610.

**Comment by xavijam** [comment]
That's great. Will it affect Google and Leaflet maps?

**Comment by alonsogarciapablo** [comment]
Yes. Hopefully this will fix CartoDB/cartodb.js#1610 👍

**Comment by xavijam** [comment]
marvellous!
