### ISSUE TITLE
GME users could change to any other basemap

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#11785]
That means, they could have available all rest of basemaps apart from Google Maps. Like Stamen, CARTO, Here, etc.

**Comment by xavijam** [comment]
cc @noguerol @saleiva

**Comment by javitonino** [comment]
What should be the default basemap then?

**Comment by xavijam** [comment]
Google maps user -> Google maps basemap
Non google maps user -> Positron basemap
