### ISSUE TITLE
Histogram triggers JS error when zooming in/out and changing number of buckets

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#11798]
### Context
I was running some smoke tests.

 ### Steps to Reproduce

1. Create a map and add a layer with some features.
2. Add an histogram widget (you can select `cartodb_id` as the column)
3. Change the number of buckets, zoom in an out and change number of buckets in between.

### Current Result
There's a JS error in the console:
```
Uncaught TypeError: Cannot read property 'max' of undefined
    at N.d._getMaxValueFromBinIndex (common_editor3.js:12)
    at N.d._calculateDataDomain (common_editor3.js:12)
    at N.d._generateFillGradients (common_editor3.js:12)
    at N.d._setupFillColor (common_editor3.js:12)
    at N.d._onChangeData (common_editor3.js:11)
    at s (vendor_editor3.js:38)
    at r (vendor_editor3.js:38)
    at m (vendor_editor3.js:38)
    at N.d.k.trigger (vendor_editor3.js:38)
    at N.d.set (vendor_editor3.js:38)
```

I found this error in track.js too -> https://my.trackjs.com/messages/filtered?hash=238bd01efd1edeab

### Expected result

Histogram works like a charm and there're no JS errors.

cc: @noguerol @xavijam 

#WD13#

**Comment by xavijam** [comment]
I feel this ticket should go in deep-insights...

**Comment by alonsogarciapablo** [comment]
Yes, this is definitely a deep-insights.js issue.

**Comment by alonsogarciapablo** [comment]
But, I guess we can leave it here since it's linked to the smoke tests spreadsheet.

**Comment by xavijam** [comment]
Well, up to you, but take into account this problem is not related with any smoke tests pass, it is happening right now in production.

**Comment by alonsogarciapablo** [comment]
Yes, I tried in production too and it's also failing.

**Comment by nobuti** [comment]
Fix already merged, PR created to update dependencies.

**Comment by xavijam** [comment]
Deployed!
