### ISSUE TITLE
Default style is not rendered back after clicking on more than 1 auto-style buttons without unchecking them

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#11795]
### Steps to Reproduce

1. Add a layer.
2. Add 2 widgets from that layer.
3. Click on auto-style
4. Without unchecking, click in auto-style on the other widget
5. Uncheck auto-style

### Current Result
Style from prev. selected widget is shown

 ### Expected result
Default style should be shown.

**Comment by nobuti** [comment]
Picking this :cowboy_hat_face:

**Comment by nobuti** [comment]
This only happens in Builder btw.

**Comment by xavijam** [comment]
Deployed
