### ISSUE TITLE
Clipped widget contextual menu

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#11790]
### Context
Contextual menus in widgets are clipped
 

### Steps to Reproduce

1. Add a widget
2. Trigger its menu

### Current Result
Menu appears clipped

![captura de pantalla 2017-03-17 a las 17 40 45](https://cloud.githubusercontent.com/assets/70603/24053407/3f2cc39e-0b39-11e7-9551-477be6086ecc.png)

### Browser and version
Chrome

**Comment by xavijam** [comment]
Deployed.
