### ISSUE TITLE
Wrong style on new layer with data import

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#11799]
### Steps to Reproduce

1. Create a map with any dataset.
2. Click "Add" (layer).
3. Select "Connect dataset" and drag a new file with polygons such as [guess_country_reduced.csv.zip](https://github.com/CartoDB/cartodb/files/858156/guess_country_reduced.csv.zip).

It gets imported with blue:

![captura de pantalla 2017-03-21 a las 14 01 35](https://cloud.githubusercontent.com/assets/932968/24148414/f6de8ee8-0e3e-11e7-8dc0-df08f59d6c3e.png)

Nevertheles...

### Current Result

Fill is yellow-ish.

![captura de pantalla 2017-03-21 a las 14 01 41](https://cloud.githubusercontent.com/assets/932968/24148418/fefbf322-0e3e-11e7-833d-19507c18445d.png)

 

### Expected result

Blue-ish.

cc @xavijam

**Comment by xavijam** [comment]
I feel it is a frontend problem, taking a look.

**Comment by xavijam** [comment]
Hey guys, is it possible that table endpoint has changed something? @CartoDB/builder-backend

**Comment by juanignaciosl** [comment]
We're constantly changing a lot of core stuff. Nothing specifically for this comes to my mind, but the change that broke #11800 might've broken this as well. If you can't find the problem, we'll take a look later.

**Comment by xavijam** [comment]
No, problem found, I'll describe in the PR. And, as a 🎁 , I'll request your CR :joy:.

**Comment by javitonino** [comment]
Deployed
