### ISSUE TITLE
Warn about layer/map deletion on dataset deletion

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#11800]
### Steps to Reproduce

1. Import a file dragging it to Maps section.
2. Delete the dataset from the dataset list (select + delete dataset...).

### Current Result

You aren't  warned about map deletion.

 

### Expected result

You should be warned about map deletion.

**Comment by javitonino** [comment]
The maps are correctly deleted. The problem is the lack of user feedback. The problem is in the visualization presenter in the `https://team.carto.com/u/javitonino/api/v1/tables/:uuid` is returning the incorrect data (an empty string instead of an array of dependent visualizations :/)
