### ISSUE TITLE
new notifications component in the header pulling from org. notifications

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#11807]
- Check and make appear the new notifications appear under the notifications component in the header.

- When organization users visit her/his notifications, we should send a request setting that the notification has been read.

![group](https://cloud.githubusercontent.com/assets/132146/23479826/027783c8-fec6-11e6-81a5-1c3e0570a3eb.png)

current proposal is to get rid of localStorage for these notifications

**Comment by matallo** [comment]
actually, we can't easily get rid of localStorage for some notifications such quotas, specifically https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/common/views/dashboard_header/notifications/view.js#L103-L165

we can do it with other notifications though, which we will expose them via a window js object, and instead of remove them from localStorage we'll update the read attribute with the api https://github.com/CartoDB/cartodb/issues/11680

waiting for the presenter to form properly the array where we'd pull to reset the collection (no rush at all) /cc @javitonino

**Comment by javitonino** [comment]
- The presenter is part of https://github.com/CartoDB/cartodb/issues/11680 (under CR).
- At some point, it would be nice to move the local storage notifications to the same system as the onboarding, but that's a story for another time.

**Comment by matallo** [comment]
BOOM, thanks for the comments

**Comment by xavijam** [comment]
Hey @urbanphes or any other @CartoDB/design member, could you take a look to this today please?

**Comment by urbanphes** [comment]
I just review the feature with the user _newmatataded01org_ and I found:
- The numbered lists appear cut on the left side.
<img width="672" alt="captura de pantalla 2017-04-04 a las 16 03 00" src="https://cloud.githubusercontent.com/assets/14546701/24661294/4b32ec0a-1952-11e7-973f-f9bc22d65775.png">


I test over the old changes and all is OK.

**Comment by xavijam** [comment]
Well, that's great, but I was mentioning about last changes in the notifications part. What does it mean? -> https://github.com/CartoDB/cartodb/pull/11842

**Comment by xavijam** [comment]
Being deployed in ded01 man 💋

**Comment by xavijam** [comment]
DEPLOYED!
