### ISSUE TITLE
#MG25 pixel aggregation doesn't work

### ISSUE THREAD

**Issue by AleGoiko** [CartoDB/cartodb#11806]
### Context
*Please explain here below what you were doing when the issue happened*

Performing smoke test #MG25

 
### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. upload dataset(http://s3.amazonaws.com/cartodb/static/learn/forest_fires.zip)
2. create new map
3. choose dataset layer
4. click style, chose pixel

### Current Result
*Please describe here below the current result you got*

a blank map (just the basemap) and a couple of js errors:

`Uncaught TypeError: L.DomUtil.getTranslateString is not a function`
`Uncaught TypeError: this._map._getNewTopLeftPoint is not a function`

 

### Expected result
*Please describe here below what should be the expected behaviour*

a map with the aggregation of ocurrences per location

### Browser and version
*What internet browser (Chrome, Firefox, etc) and version was you using and version* 

chrome  56.0.2924.87

 
### .carto file
*Don't forget to rename .carto file to .zip file to be able to upload to github*

http://s3.amazonaws.com/cartodb/static/learn/forest_fires.zip
 

### Additional info
*Please add any information of interest here below*

**Comment by xavijam** [comment]
I feel this problem should go in CartoDB.js repository 💋 
cc @alonsogarciapablo @donflopez .

**Comment by alonsogarciapablo** [comment]
This is failing for the same reason as https://github.com/CartoDB/cartodb/issues/11804 so I'll close it (great catch @AleGoiko).
