### ISSUE TITLE
#MG22 Time aggregation doesn't work.

### ISSUE THREAD

**Issue by AleGoiko** [CartoDB/cartodb#11804]
### Context
*Please explain here below what you were doing when the issue happened*

Performing smoke test MG22
 

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. upload dataset(such as https://s3.amazonaws.com/cartodb/static/learn/bird_tracking.zip)
2. create map
3. on dataset layer, click style and chose animation
4. chose date_time column

### Current Result
*Please describe here below the current result you got*

blank map with no animation nor column histogram

 

### Expected result
*Please describe here below what should be the expected behaviour*

animated points on map and histogram of the chosen column

### Browser and version
*What internet browser (Chrome, Firefox, etc) and version was you using and version* 

chrome 56.0.2924.87

 

### .carto file
*Don't forget to rename .carto file to .zip file to be able to upload to github*

https://s3.amazonaws.com/cartodb/static/learn/bird_tracking.zip

 

### Additional info
*Please add any information of interest here below*

**Comment by alonsogarciapablo** [comment]
This should be fixed now.
