### ISSUE TITLE
Orchestrate all requests involved for a DO measurement

### ISSUE THREAD

**Issue by nobuti** [CartoDB/cartodb#11802]
After https://github.com/CartoDB/cartodb/issues/11617 and https://github.com/CartoDB/cartodb/issues/11618, we need to handle some more request in order to feed a measurement form group. Take this [gist](https://gist.github.com/talos/554c7759bafe53faafd23a9711305220) as an example of api's usage.

**Comment by nobuti** [comment]
Blocking this until we get a clear idea about the new column field and how camshaft deals with the data from the UI.

**Comment by xavijam** [comment]
Blocking again due to new camshaft analysis is not supporting yet `boundaries`, `normalize` and `timestamp` attributes. For context (https://github.com/CartoDB/camshaft/compare/data-observatory-multiple-measures).

**Comment by nobuti** [comment]
Normalisation is integrated already, waiting for the final node in camshaft.

**Comment by talos** [comment]
@nobuti is there some specific code you would like me to review?

**Comment by talos** [comment]
Found the PR, working on a review.

**Comment by xavijam** [comment]
Blocked until new issues are fixed.

**Comment by xavijam** [comment]
So, ladies and gentlemen, say hello to the new DO UI 😄  ❤️  💋
