### ISSUE TITLE
Wrong value shown when georeferencing on georeference analysis

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#11812]
### Steps to Reproduce

1. Add a layer
2. Georeference it by street adress
3. Apply

### Current Result
![screen shot 2017-03-21 at 17 44 39](https://cloud.githubusercontent.com/assets/132149/24158976/2ab363d2-0e5e-11e7-8581-c28085eddb22.png)

TYPE Dropdown is showing a wrong value (and growing more than supposed to do).

 
After going to the layer list, and entering back to the analysis, it looks correct

**Comment by xavijam** [comment]
Have we fixed this one in the new street geocoding PR @matallo ?

**Comment by matallo** [comment]
yes!

**Comment by xavijam** [comment]
Hey, it should be fixed thanks to the thing mentioned before. Closing it and if we find it again, let's open a new one 💋 .
