### ISSUE TITLE
Legend color bar gets small

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#11825]
### Steps to Reproduce

1. Get a map with a category widget. 
2. Select a layer and create a legend in it. A custom one, for example.
3. The legend form shows a color bar with a proper size.
4. Go to the category widget and select one of the categories.
5. The color bar gets very small and it keeps this size even when exiting the layer edition and coming back.

### Current Result

This is what happens.

![peque-barra](https://cloud.githubusercontent.com/assets/1078228/24207580/889fc13e-0f21-11e7-89bc-989d599fc655.gif)

### Expected result

The color bar remains equal when selecting a category. Its size should not be affected.

**Comment by nobuti** [comment]
This is because there is a disable-overlay component (div) inside a `ul`, that is flex. I feel in somewhere we are adding this overlay inside the `js-content` selector.

**Comment by nobuti** [comment]
Fixed in https://github.com/CartoDB/cartodb/commit/4107e51346db4c9d4fd1b9dc6675830e57900a4d.
