### ISSUE TITLE
Support mapzen_routing_quota on set_org_quota rake

### ISSUE THREAD

**Issue by jvillarf** [CartoDB/cartodb#11823]
## Description

**Related ticket**: https://github.com/CartoDB/onpremises/issues/273

Hi,

we've realized today that the following rake tasks are outdated, since they doesn't support ```mapzen_routing_quota```:
- ```set_user_quota```: https://github.com/CartoDB/cartodb/blob/master/lib/tasks/services.rake#L64
- ```set_org_quota```: https://github.com/CartoDB/cartodb/blob/master/lib/tasks/services.rake#L90

Would you please update them to support ```mapzen_routing_quota```? I'm not sure if there is any other **quota** variable that i could be missing. Is there any for **mapzen isolines**?

The parent ticket belongs to the **Onpremises LDS** milestone, so if possible, this ticket should be implemented by April, 7th.

Thanks a lot.

**Comment by jvillarf** [comment]
Would you please assign the ticket to the right team/kanban board? Thanks.

cc/ @rochoa @juanignaciosl

**Comment by jvillarf** [comment]
Hi,

sorry for chasing, but this ticket hasn't been added to any kanban board yet.

Thanks.

**Comment by juanignaciosl** [comment]
Ups, I was going to add this to our panel but it's already at Engine's, sorry.

**Comment by rafatower** [comment]
PR here: https://github.com/CartoDB/cartodb/pull/11917

**Comment by jgoizueta** [comment]
Acceptance plan has been added in [PR](https://github.com/CartoDB/cartodb/pull/11917#issuecomment-292204324).

This and #11777 should be accepted together.

**Comment by jgoizueta** [comment]
The missing service has been added to the rake tasks; here's the documentation: https://github.com/CartoDB/cartodb/blob/master/doc/manual/source/operations/configure_data_services.rst#quotas
