### ISSUE TITLE
Add extra parameter to keep/exclude points when filtering points in polygon

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#11820]
### Context
Very often you would like to use Filter points in polygon analysis to not only know which points intersect a particular polygon (such as an AOI) but also to know which points NOT intersect those areas (such as points within safe areas).

This could be enabled by adding a new parameter (like we do in the filter by column value) to choose if you want to keep or exclude the points intersecting the polygons

 

cc/ @noguerol

**Comment by xavijam** [comment]
Do we have this implemented in camshaft @dgaubert ?

**Comment by noguerol** [comment]
@dgaubert ping

**Comment by dgaubert** [comment]
Hey!

Sorry for the delayed response. I've just checked it and the answer is NOT, we don't have nothing implemented related to exclude points in polygons.

If we want this to be prioritised, I'd like to tackle it.

**Comment by noguerol** [comment]
Is this a one day thing or a one week thing, @dgaubert ?

**Comment by dgaubert** [comment]
From point of view of backend, one day.

**Comment by alrocar** [comment]
Stale issue. Closing 👋
