### ISSUE TITLE
Join analysis is applied even with no row coincidence

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#11829]
### Context
If you select incompatible type foreign keys on a join analysis, analysis is apparently ran even though no final table is generated
 

### Steps to Reproduce

1. Add Join analysis
2. Select two non-matching (type) key columns 
3. Select the output columns and run de analysis

### Current Result
Analysis is ran with no error but the result is an empty table
 

### Expected result
An error should pop up when selecting the foreign keys columns warning the user that they might have the same data type.

**Comment by AbelVM** [comment]
Same behavior when using "Filter by Layer"

**Comment by javierarce** [comment]
> An error should pop up when selecting the foreign keys columns warning the user that they might have the same data type.

Wouldn't it be "…that they have different data types" instead?

**Comment by javierarce** [comment]
> An error should pop up when selecting the foreign keys columns warning the user that they might have the same data type.

@noguerol: wouldn't it be "…that they have different data types" instead?

**Comment by saleiva** [comment]
is it easy to fix in Filter by layer at the same time? If not, let's create another issue for that

**Comment by saleiva** [comment]
did we also fix on the other analysis @matallo ?

**Comment by matallo** [comment]
yep, writing the tests for that now

**Comment by ivanmalagon** [comment]
Deployed to production.
