### ISSUE TITLE
Rake for cleaning unused external visualizations

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#11830]
Given a start and end date (number of days, maybe), for free users that haven't logged in in that period of time...

- [ ] removes the unused remote visualizations (data library ones).
- [ ] sets `last_common_data_update_date` to `null`.

"Haven't logged" should be based on `dashboard_viewed_at` date. Also, if `dashboard_viewed_at` is `null` and `created_at` is older than a given time.

Acceptance:
- Link a data library entry (without creating a map).
- Create a map with another data library entry.
- Clean that user.
- Log in again with the user. Both datasets, and the map, should be there. And Data Library gets repopulated (it might take a minute).

PS: the start-end date is a suggestion for running this in small batches, to avoid large rewritings of the table.

**Comment by javitonino** [comment]
I would also delete all visualizations with `user_id` set to `NULL` (or an id not present in the `users` table). Those are also unreachable and last I checked represented about 15% of the visualizations.
