### ISSUE TITLE
Auto-style not working on Google enabled Builder embeds

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#11838]
### Context
Autostyle is not working on embeds coming from Google enabled Builder accounts.
 

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Make a map with both a google basemap and some widgets
2. Click on the autostyle button in the embed view

### Current Result
Geometries in the map doesn't change
 

### Expected result
Geometries get auto styled

This comes from: https://github.com/CartoDB/support/issues/577

**Comment by ivanmalagon** [comment]
Deployed.
