### ISSUE TITLE
Add a case sensitive tooltip in filter by column value analysis

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#11844]
### Context
According to https://github.com/CartoDB/design/issues/669#issuecomment-288991034 users are experiencing issues when writing a string for the filter by column value because they don't know is case sensitive.
To tackle that in the easy way we're adding a tooltip to the "input" field in "Parameters" that says. "Select or write your text. Note that this field is case sensitive."
 

### Steps to Reproduce

1. Add and Filter by column value analysis
2. Select a string column
3. Write a custom text

### Current Result
There is no warning that no values will be returned if the text is written in a different case
 
### Expected result
A warning should be

**Comment by piensaenpixel** [comment]
pleaseeeeeeeeeee

**Comment by alrocar** [comment]
Stale issue. Closing 👋
