### ISSUE TITLE
Changing a basemap takes too long

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#11840]
### Steps to Reproduce

1. Enter to any map
2. Change the basemap a few times

### Current Result
It takes more than a second and even more than 10 seconds sometimes

**Comment by saleiva** [comment]
I'd try to take a look at this soon since this is a very used feature, and it's very challenging for demos

**Comment by juanignaciosl** [comment]
Let's take a look. Maybe we should instrument the code for metrics, to check if the problem is at Rails or at Maps API.

**Comment by javitonino** [comment]
Seems like a slow update of the named maps on the tiler side. Some recent examples:

![screenshot_20170328_110941](https://cloud.githubusercontent.com/assets/7569673/24397616/1dc3733a-13a7-11e7-8fc6-59f63ccc4721.png)

I matched an specific example in my account, and the Rails time matched the Tiler time (plus a bit extra), so I think it makes sense.

**Comment by juanignaciosl** [comment]
cc @rochoa and @javisantana , as the latter has just talked to me about a problem that might be related.

**Comment by javitonino** [comment]
When a basemap change is triggered, we do the following:
- `PUT /layers`
  - Does a `GET` and then a `PUT` to named maps API. We need the `GET` to decide whether to follow it up with a `POST` or a `PUT`.
- `PUT /maps` 
  - Again, `GET` + `PUT` to named maps.
- There is an extra request (which triggers two named map updates) in the case of a layers on top basemap.

So, we are doing 4-6 tiler requests (2 gets and 2 puts) to the tiler's named maps API on each basemap change, but there is little we can do from Rails as it is.
- @rochoa we talked at some point about an "upsert" API for named maps, did we finally implement anything?
- From frontend side, maybe we could skip the update to maps if the provider is not updated. Or from backend side, be a little clever and do not update named maps if the update did nothing

**Comment by javisantana** [comment]
Issue moved to [CartoDB/cartodb-management #4912](https://github.com/CartoDB/cartodb-management/issues/4912) via [**ZenHub**](https://www.zenhub.com/)
