### ISSUE TITLE
Remove feature flag `static-maps` when export as image functionality is merged

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#11847]
When `export as image` is released, we should remove the checks we have for showing or not the option under the dropdowns + remove the feature flag.

**Comment by jorgesancha** [comment]
I suggest we delay this one until we are absolutely sure Image Export is [hunky dory](http://www.urbandictionary.com/define.php?term=hunky+dory&defid=230242)

cc @noguerol

**Comment by xavijam** [comment]
Added to TODO column in order to "enable" the functionality for everybody.

**Comment by juanignaciosl** [comment]
Ey, @noguerol , how come I've been assigned in acceptance for this?

**Comment by xavijam** [comment]
It was a mistake for sure, _circulen_.

**Comment by javitonino** [comment]
Code deployed and FF nuked 💥
