### ISSUE TITLE
Replace NPM use by Yarn

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#11856]
Basically, after a quick test done by @rochoa, we checked that installing our dependencies took 30 seconds with yarn instead of ~120 using NPM.
Why?
[Yarn](https://yarnpkg.com/en/) is faster because it uses parallelization and caches every package. 
Also it uses its own "shrinkwrap", called `yarn.lock`.

- [ ] Replace use of NPM and start using Yarn in:
  - [x] CI tests.
  - [ ] Development environment: basically checks our grunt tasks.
  - [ ] Staging environment: check deploys are correct, basically the grunt build task.
- [x] Change all documentation, like CONTRIBUTING.
- [x] Compare results from old (npm) to new (yarn).
- [ ] Migrate duplicated dependencies checker to new Yarn.lock*.

*About last bullet: we have a "checker" made by @rochoa and @javisantana (if I'm not wrong), where we check if the same dependency is used in other place with a different version. So, we should keep this checker but using the new `yarn.lock` file instead of the `npm-shrinkwrap.json`.

**Comment by xavijam** [comment]
Some work done in this [PR](https://github.com/CartoDB/cartodb/pull/11882).

**Comment by rochoa** [comment]
What is the status of this one? Are you actively working on it?

**Comment by xavijam** [comment]
I work on it in my free time :(. It would be great if you have anything to add please 🙏 .

**Comment by jorgesancha** [comment]
Hi guys,

after discussing with @rochoa and @CartoDB/systems and to avoid delaying LDS ON Premise, we are going to continue using NPM for the time being. We'll aim to use YARN for the next LDS On Premise release.

Removing from TODO column

**Comment by xavijam** [comment]
So, are we ready to start using it @jorgesancha then?

**Comment by jorgesancha** [comment]
The only reason to delay it (if I remember correctly) was because we didn't want to include it in this onprem release yet. 

@rporres @jvillarf do you see any problem to get this going and to keep it in mind for the next onprem release?

**Comment by rporres** [comment]
The problem with `yarn` for onpremise is the lack of support for `--build-from-source` when compiling windshaft

**Comment by jorgesancha** [comment]
So is the answer "No way" then? Or is it something along the lines of "Not sure how to do it, we have to investigate"?

If you could give us a bit more info on what the options are (if any) to use this onprem so that we can decide whether it makes sense to go ahead with this or not, that'd be great. 

Thanks!

**Comment by rporres** [comment]
As far as node-windshaft is concerned, the answer is "no way". As far as we know and we have tested, `yarn` does not support `--build-from-source`.

That doesn't mean we cannot use `yarn` to compile assets in onprem. We would have to live with different node packagers/builders for the different projects. But we are already doing that with sql-api and windshaft.

**Comment by xavijam** [comment]
cc @luisbosque

**Comment by luisbosque** [comment]
I believe yarn got stuck in a limbo. I believe we use it somewhere but it's not the "standard" at CARTO.
@ivanmalagon @dgaubert what can you say about it?

**Comment by xavijam** [comment]
Come on! yarn 👍 !

**Comment by Jesus89** [comment]
We use it in the new projects:
- https://github.com/CartoDB/carto-vl
- https://github.com/CartoDB/airship

In my opinion, the developer's experience is generally better/faster using yarn.

Note: here is a [nice PR](https://github.com/CartoDB/carto.js/pull/2053) to use `yarn` in CARTO.js in case you decide to go for it.

**Comment by ivanmalagon** [comment]
We were waiting for OnPremises 2.2 to be officially released. We didn't want to mess anything. OP 2.2 is still pending so this in on hold.

**Comment by jvillarf** [comment]
@ivanmalagon we have finally released the new onprem version, so this is no longer a blocker. Thanks for waiting for us.
