### ISSUE TITLE
oembed imput stopped working

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#11854]
### Context

related issue: https://github.com/CartoDB/cartodb/issues/1965

endpoint to oEmbed stopped working at some point presumably when migrating cartodb => carto

trying with different combinations of builder/editor embed urls, on cartodb and carto domains don't return the intended responses

see http://oembed.com/

### Steps to Reproduce

```
$ curl -I http://cartodb.com/api/v1/oembed?url=https://matallo.carto.com/builder/5a1cecc2-f8d3-11e3-95ab-0e230854a1cb/embed
HTTP/1.1 400 Bad Request
Server: nginx
Date: Mon, 27 Mar 2017 14:35:18 GMT
Content-Type: text/html
Content-Length: 264
Connection: keep-alive
```

sending a request to `http://carto.com/api/v1/oembed` returns 404 directly, `HTTPS` requests don't work either

### Current Result

sending an http request to the oembed endpoint, the response is `400 Bad Request` 

### Expected result

it should return the code for an iframe to embed in an external resorce, as per the oembed specification http://oembed.com/

**Comment by javitonino** [comment]
Uhm, did `carto.com` (without subdomain) ever work?

It works fine with the subdomain (so the request gets routed to the cartodb app)
https://matallo.carto.com/api/v1/oembed?url=https://matallo.carto.com/builder/5a1cecc2-f8d3-11e3-95ab-0e230854a1cb/embed

If it did, then it is probably some redirection at systems level.

**Comment by matallo** [comment]
oh, summoning @CartoDB/systems then, thanks for the tip! shame on me for not checking it

**Comment by javitonino** [comment]
The actual URL that should be used `https://services.carto.com/oembed?url=https://matallo.carto.com/builder/5a1cecc2-f8d3-11e3-95ab-0e230854a1cb/embed`
