### ISSUE TITLE
No geometry messages are displayed after a new geometry is drawn

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#11857]
### Context
I was testing something else.
 

### Steps to Reproduce

1. Create a new empty map.
2. Click on the new layer.
3. Draw any geometry.

### Current Result
Unless I refresh, I'm seeing the following messages/things:

<img width="929" alt="screen shot 2017-03-27 at 17 15 43" src="https://cloud.githubusercontent.com/assets/390398/24363845/51a212c4-1311-11e7-9557-eb8178d59d0d.png">
<img width="819" alt="screen shot 2017-03-27 at 17 13 20" src="https://cloud.githubusercontent.com/assets/390398/24363846/51a550a6-1311-11e7-86cc-f96f4a758377.png">
<img width="641" alt="screen shot 2017-03-27 at 17 14 02" src="https://cloud.githubusercontent.com/assets/390398/24363847/51b10108-1311-11e7-9488-13413d372406.png">
 
### Expected result
Since I just drew a new geometry, I shouldn't see any of those messages and I should only be able to draw geometries of the same type I just drew.

**Comment by xavijam** [comment]
In production?

**Comment by alonsogarciapablo** [comment]
Yep.

**Comment by saleiva** [comment]
Can you guys get involved @josecruz in this one too? Even if it looks apparently a simple fix, I really want designers to be doing more acceptance so new stuff can appear!

**Comment by nobuti** [comment]
Of course, @josecruz count me in for whatever you need, I'll ping you
tomorrow to deploy it to staging.

**Comment by josecruz** [comment]
Ok so I see this working! I've found another user but is not related with this on (https://github.com/CartoDB/cartodb/issues/11898)

So from my side, :bandera:!

**Comment by nobuti** [comment]
Closed by #11875.
