### ISSUE TITLE
[MG06] Error adding polygon

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#11869]
### Context

Tried to add another polygon to a layer even tho it gets properly reflected on the map, it doesn't show on the table. 

### Steps to Reproduce

1. Add a polygon layer
2. Use the _Add geometry_ feature to add another polygon to that layer
3.Take a look at the table

### Current Result

![screen shot 2017-03-28 at 12 25 03](https://cloud.githubusercontent.com/assets/16247628/24400676/a1e98096-13b1-11e7-9bfa-e44f2ee978bd.png)

![screen shot 2017-03-28 at 12 25 12](https://cloud.githubusercontent.com/assets/16247628/24400677/a1f21d8c-13b1-11e7-8de7-6f35effa1107.png)

Notice how there's not cartodb_id 4 on the table (or 3!) 

### Expected result

The added polygon should be properly reflected on the table. 

### Browser and version

Chrome Version 56.0.2924.87 (64-bit)

### .carto file

[Untitled map (on 2017-03-28 at 10.17.29).carto.zip](https://github.com/CartoDB/cartodb/files/875284/Untitled.map.on.2017-03-28.at.10.17.29.carto.zip)

### Additional info

Smoke test MG06

**Comment by xavijam** [comment]
Same problem than https://github.com/CartoDB/cartodb/issues/11857. Already reported.
