### ISSUE TITLE
Color picker changes to picked color

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#11868]
### Context
If you edit a feature and you go to the Red color, the color picker saturation box got refreshed to the picked color. 

 

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Create empty layer
2. Draw polygon 
3. Style polygon

### Current Result
![bug1](https://cloud.githubusercontent.com/assets/596509/24400688/a743ac42-13b1-11e7-9d26-1ecb10f06c51.gif)

### Expected Result
The color picker saturation box should not change, depending on the position

### Browser and version
Chrome 56.0

**Comment by donflopez** [comment]
Thanks @josecruz!! 

This is not related with https://github.com/CartoDB/cartodb.js/issues/1603

**Comment by nobuti** [comment]
Fixed in https://github.com/CartoDB/cartodb/pull/9795/commits/df1a406c4c1377696afc9203eaab871c86bee3ac
