### ISSUE TITLE
[MG05] Layer still looks like if it were empty after adding a point 

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#11867]
### Context

I added a point with the _Add geometry_ feature on an empty layer and even tho the points gets saved, and it gets properly represented on the map, the layer still shows as it were still empty. 

### Steps to Reproduce

1. Add an empty layer
2. Add a point anywhere on the map with the _Add geometry_ feature
3. Save the point 
4. Take a look at the layer 

### Current Result

![screen shot 2017-03-28 at 12 09 58](https://cloud.githubusercontent.com/assets/16247628/24400332/4ec27eb4-13b0-11e7-8e00-f7deb8bb8322.png)
![screen shot 2017-03-28 at 12 10 06](https://cloud.githubusercontent.com/assets/16247628/24400333/4ec786ac-13b0-11e7-91c6-e80d01f6e39e.png)
![screen shot 2017-03-28 at 12 10 22](https://cloud.githubusercontent.com/assets/16247628/24400334/4ecbb858-13b0-11e7-90f2-bda4f1893c94.png)

### Expected result

The layer should become a point layer and display the correct information of the point added. 

### Browser and version

Chrome Version 56.0.2924.87 (64-bit)

### .carto file

[Untitled map (on 2017-03-28 at 10.17.29).carto.zip](https://github.com/CartoDB/cartodb/files/875284/Untitled.map.on.2017-03-28.at.10.17.29.carto.zip)

### Additional info

Smoke test MG05

**Comment by xavijam** [comment]
Same problem than https://github.com/CartoDB/cartodb/issues/11857. Already reported.
