### ISSUE TITLE
Change copy "Select a text" to "Select a value" in the "Filter by column value" analysis

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#11861]
### UI Update

- [x] Change every `Select a text` message for `Select a value`. This makes more sense given that the analysis is called filter by column **value** and that you can select not only text but also numbers. 

~~- [ ] Add "(case sensitive)" to the following dropdown (design ticket https://github.com/CartoDB/design/issues/669):~~

![screen shot 2017-03-27 at 18 06 00](https://cloud.githubusercontent.com/assets/16247628/24366116/6c114204-1318-11e7-93ce-824bdce74052.png)

**Comment by matallo** [comment]
fixed in https://github.com/CartoDB/cartodb/pull/12199

**Comment by Jesus89** [comment]
Hi @arianaescobar. Now the search dropdown is case insensitive, so if we prefer to keep this behavior the text "(case sensitive)" is not needed.

**Comment by arianaescobar** [comment]
Well, that was our original request (for it to not be case sensitive), so even better! :)

Still, I would like to understand how we went [from this](https://github.com/CartoDB/design/issues/669#issuecomment-289071434) to where we are now, just out of curiosity... cc @noguerol

**Comment by nobuti** [comment]
Hey @arianaescobar, I think that comment is still valid, but I'm pretty sure there was some kind of misunderstanding. We implement the filtering case insensitively in the front, but we don't turn the value the user introduces. This value remains as it is, and that is how we send to the backend. I think Raul meant it's tricky to manage values case insensitive at analysis level. But to be clear, that change is at front level.

**Comment by arianaescobar** [comment]
Thanks for the clarification @nobuti! 

So, just to be clear, if I have a column named "Cities" and I type "cities" in the search box, that said column will appear, right?

**Comment by nobuti** [comment]
It will appear in the dropdown, as `Cities`, yes.

**Comment by arianaescobar** [comment]
Awesome :)

**Comment by nobuti** [comment]
Closed by #12803
