### ISSUE TITLE
Improve onboarding for when user adds an empty layer

### ISSUE THREAD

**Issue by urbanphes** [CartoDB/cartodb#11876]
### Context
Design ticket https://github.com/CartoDB/design/issues/612

### Additional info
Here's the Invision Project (linked)
https://invis.io/6QAZN3JSR

**Comment by jesusbotella** [comment]
Moved this from `In Progress` to `Deploy` because we are going to release the improvement without the context switcher thing that will be addressed in another issue. Go [here](https://github.com/CartoDB/cartodb/pull/13377) for more context.

**Comment by jesusbotella** [comment]
It is needed to fix one behaviour when an analysis is applied, because `isEmpty` method does not return the correct value.

**Comment by alrocar** [comment]
Stale issue. Closing 👋
