### ISSUE TITLE
Problem when user filters a widget and it was displaying the widget form view

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#11874]
We have a problem with the widget form and related when the user filter something in the category/histogram widget (@saleiva @noguerol @jorgesancha). Due to it, we have had a big impact of JS errors yesterday. Fortunately, we have researched a bit and found the problem.

## STR
- Create a map of points.
- Add an analysis (subsample is enough).
- Add a category widget pointing to that analysis node.
- Go to edit this widget.
- Filter by the first result of the widget.
- Check that the carousel of the widget form is not providing several options, only one.
- Try to change the color of the auto-style.
- 💥 .

This is a problem simiilar to https://github.com/CartoDB/cartodb/pull/11822.

**Comment by xavijam** [comment]
Hey @javierarce, I feel we should talk about this, do you want to have a quick recap?

**Comment by xavijam** [comment]
Also, I started some work in `11874-issue` branch.

**Comment by xavijam** [comment]
Recapping what I have talked with some frontenders. @saleiva found a problem where panels were not reacting to changes coming from widgets (https://github.com/CartoDB/cartodb/issues/11819). That opened a box we didn't know, so we decided to just listen to query changes in several views and make the necessary requests in order to "update" the query objects (`query-schema-model`, `query-geometry-model` and `query-rows-collection`). That doesn't scale, so we have to find another way to update those models/collections in an effective way.

A possible solution would be to update those models when an "updated" node is ready in the builder side (info coming from CARTO.js), and make those requests.

But there are several concerns about it:

- We should only request those models from the top node of the layer. It is not necessary to request all nodes data because we only "visualize" the data referenced to the last/top node.
- We must not request the models data at the beginning. We don't need it (although geometry info, but it is requested in other way), and it could provoke 3x the analyses the map has. 5 analyses x 3 objects (QSM, QGM, QRQ) = 15 requests :|

**Comment by javierarce** [comment]
What does 💥  mean exactly? Errors in the console, lack of updates, both?

Also: I've been unable to get the step #5 of your list (`Check that the carousel of the widget form is not providing several options, only one.`). I'm always presented all the options for widgets.

**Comment by xavijam** [comment]
💥  -> JS error in the console.

If you have doubts, I'll show you live 😬 .

**Comment by javierarce** [comment]
Yes, please, I'm probably doing something wrong, because I can't reproduce it on my machine or in production.

**Comment by xavijam** [comment]
Sorry, my bad. The description was not that accurate.

**Comment by xavijam** [comment]
Well, yep, but that is not solving all the described [here](https://github.com/CartoDB/cartodb/issues/11874#issuecomment-292944611), have you found any problem or block to doing that?

**Comment by matallo** [comment]
indeed, when having an analysis > adding a widget to the analysis node > applying autostyle > edit style > 💥

investigating further

**Comment by matallo** [comment]
actually, adding a widget > autostyle > change color is already 💥 in prod

no analysis involved 😕

**Comment by matallo** [comment]
besides changing the fill color in the layer > style tab, I can't find anything else not working in the dev branch already started, like @javierarce 

waiting for more insights on this issue

**Comment by xavijam** [comment]
I described the main problem in a comment above. The issue is solved but it should be addressed properly. Also @matallo we discussed the thing days ago in front of the whiteboard.

**Comment by matallo** [comment]
:thu

**Comment by xavijam** [comment]
Checked, when a widget is filtered, panel views are not rendered again. Back to development, taking a look 💋 .

**Comment by nobuti** [comment]
I've found an issue, the created analysis notification is shown whit every filtering action in the widget:

![widget-analysis](https://cloud.githubusercontent.com/assets/1366843/25174008/54a1b528-24f6-11e7-97d9-5fba4d4ff71b.gif)

**Comment by matallo** [comment]
maybe this is silly: can it be the case that the widget is for the source layer, then it affects further analyses in the consequent layers?

**Comment by nobuti** [comment]
After taking a bit with @xavijam, the notification issue is something that is happenning right now in production, not related with this issue, https://github.com/CartoDB/cartodb/issues/12023. I'm going to fix the loader position.

**Comment by nobuti** [comment]
Accepted! Does anyone else to give it a try? @xavijam

**Comment by nobuti** [comment]
Deployed.
