### ISSUE TITLE
[MG07] Error adding line

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#11870]
### Context

Tried to add a line but, even tho it gets properly reflected on the map, it doesn't show on the table. 

### Steps to Reproduce

1. Add a line layer or an empty layer
2. Use the _Add geometry_ feature to add a line to that layer
3.Take a look at the table

### Current Result

![screen shot 2017-03-28 at 12 27 53](https://cloud.githubusercontent.com/assets/16247628/24400854/39b2a72c-13b2-11e7-874a-843dc49b79e0.png)

![screen shot 2017-03-28 at 12 28 07](https://cloud.githubusercontent.com/assets/16247628/24400855/39bc441c-13b2-11e7-8127-3efce2f13929.png)

### Expected result

The added line should be properly reflected on the table. 

### Browser and version

Chrome Version 56.0.2924.87 (64-bit)

### .carto file

[Untitled map (on 2017-03-28 at 10.17.29).carto.zip](https://github.com/CartoDB/cartodb/files/875284/Untitled.map.on.2017-03-28.at.10.17.29.carto.zip)

### Additional info

Smoke test MG07

**Comment by xavijam** [comment]
Same problem than https://github.com/CartoDB/cartodb/issues/11857. Already reported.
