### ISSUE TITLE
Error tracker doesn't take starting errors and it makes the app provide other falsy errors

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#11872]
After checking a pick of TrackJS errors, I've noticed that if there is a JS error that happens at the beginning, TrackJS doesn't take it because it is not loaded, so it is not tracked there.
Let's try to move the script to the top of the scripts (http://docs.trackjs.com/tracker/installation) in order to fix this problem.

**Comment by xavijam** [comment]
cc @CartoDB/frontend and @nobuti because we saw this in the past.

**Comment by xavijam** [comment]
I'm thinking how to test this and I'm wondering if we could "enable" (basically add the trackjs credentials) in any staging server and test it there. Would it be possible @CartoDB/builder-backend?

**Comment by javitonino** [comment]
We can do it for all staging servers (via chef), or we can do it for one server temporarily (disabling chef, and adding credentials manually). Shouldn't be a problem either way, we know how to cook.

**Comment by xavijam** [comment]
It would be great if we can add them for a while, at least for this acceptance...

**Comment by javitonino** [comment]
Done in ded07 for a few days. Remember to tell us to undo it when done :)

**Comment by nobuti** [comment]
@javitonino already tested, you can undo your balck magic.

**Comment by javitonino** [comment]
Magic undone. Welcome to the regular boring non-magical world. Hope you are happy.

**Comment by nobuti** [comment]
Shipped.
