### ISSUE TITLE
When export image fails, there is no error provided

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#11887]
Basically, if you have the `export-image` flag enabled in your account:

- Open a map.
- Check map options and click over export image.
- Click over Export image.
- It should fail right now due to https://github.com/CartoDB/cartodb.js/issues/1606 but there is no feedback about the problem...

What do you suggest @CartoDB/design @javierarce? Maybe use the current notifier with the error state?

**Comment by javierarce** [comment]
I agree, let's use the same method as we do with other forms.

**Comment by noguerol** [comment]
I'm not able to induce the error, so unasigning myself.

**Comment by xavijam** [comment]
I've tested it in my local environment, stopping maps api, for example, and the error works like a charm. Moving it to deploy column, to be done on Monday 💃 .

**Comment by xavijam** [comment]
DEPLOYED
