### ISSUE TITLE
Incorrect behaviour in Analysis tab

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#11899]
### Context

If you already have an analysis added and you add a new one but you cancel it before applying it, the interface doesn't move to the previous analysis UI. 
 
### Steps to Reproduce

1. Apply an analysis to a map
2. Add a second analysis (don't apply it)
3. Cancel the analysis 

### Current Result

Notice how the steps below stay the same when you cancel the analysis, and the previous analysis doesn't get selected automatically. 

![analysis](https://cloud.githubusercontent.com/assets/16247628/24547083/715e2b20-160e-11e7-93d5-b89a6a26166d.gif)
 
### Expected result

The previous analysis should be selected automatically after cancelling the other analysis. 

### Browser and version

Chrome Version 57.0.2987.110 (64-bit)

**Comment by nobuti** [comment]
For new hires.
