### ISSUE TITLE
Problem with bounding box in maps with google basemaps and widgets

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#11894]
If the user creates a map with basemap of Google, adds a widget, and then reloads the map, a "state" stored with wrong bounding box will be saved :(.

## STR
- Create a map.
- Change basemap to a Google basemaps (of course, you have to have it enabled 😬 ).
- Add a widget.
- Move the map wherever you want.
- Reload the map.
- Everything should work.
- Reload again the map.
- Center is moved to [0,0][0,0].

More info: https://github.com/CartoDB/support/issues/590#issuecomment-290451205
Support ticket for context: https://github.com/CartoDB/support/issues/590.

**Comment by xavijam** [comment]
@noguerol @jorgesancha, this is important for migrations.
cc @alonsogarciapablo

**Comment by jorgesancha** [comment]
Please check it out first and let's get a sense of effort. I assume this
affects everyone with widgets and google basemaps, right?

**Comment by xavijam** [comment]
I've just seen this in CARTO.js https://github.com/CartoDB/cartodb.js/blob/v4/src/geo/gmaps/gmaps-map-view.js#L146

```js
  getBounds: function () {
    if (this._isReady) {
      var b = this._gmapsMap.getBounds();
      var sw = b.getSouthWest();
      var ne = b.getNorthEast();
      return [
        [sw.lat(), sw.lng()],
        [ne.lat(), ne.lng()]
      ];
    }
    return [ [0, 0], [0, 0] ];
  },
```

**Comment by saleiva** [comment]
Are we fixing the other issue together with this? the one for saving zoom and x,y instead of bbox?

**Comment by xavijam** [comment]
Blocking it until we have something we agree in DI, where the source of the problem is placed.

**Comment by xavijam** [comment]
PR about DI -> https://github.com/CartoDB/deep-insights.js/pull/533

**Comment by xavijam** [comment]
So, there are two PR:
- Builder: https://github.com/CartoDB/cartodb/pull/11901#discussion_r109371772
- DI: https://github.com/CartoDB/deep-insights.js/pull/533

If we check everything is 👍 , we should:
- Merge deep-insights PR into master.
- Change package to point to master and update dependencies in the Builder PR.
- Push it and wait for a 🍏 .

**Comment by xavijam** [comment]
Deployed
