### ISSUE TITLE
Replace edit geometry component

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#11903]
### Context
We've been discussing how Edit Geometry behaves. The idea of this improvement is to let the user Add/Edit a popup and Geometry in a more explicit way and gaining some space on the map. 

Design ticket: https://github.com/CartoDB/design/issues/653

### States
![image](https://cloud.githubusercontent.com/assets/596509/24603259/5b5905d0-1860-11e7-8eab-84006c677479.png)
Basically, the Edit Geometry button will be replaced with a popup like this:

* When there's no Pop-up activated/Activated but empty:
![slice 7](https://cloud.githubusercontent.com/assets/596509/24602982/65fb5390-185f-11e7-90e8-733d8c78f5b9.png)

* With info normal size:
![slice 7](https://cloud.githubusercontent.com/assets/596509/24603159/0066ffc4-1860-11e7-8ada-54a2dbb26563.png)

* With Info white big:
![slice 7](https://cloud.githubusercontent.com/assets/596509/24603130/e7faac92-185f-11e7-8fc3-a87523ebb244.png)

* Dark Version:
![slice 7](https://cloud.githubusercontent.com/assets/596509/24603234/40068f46-1860-11e7-8008-ebf0680ad5f1.png)

* With image:
![slice 7](https://cloud.githubusercontent.com/assets/596509/24603656/fb595aac-1861-11e7-859f-5e2c357aae78.png)

* When Edit Feature is disabled:
![slice 8](https://cloud.githubusercontent.com/assets/596509/24653294/850ba70e-1935-11e7-92aa-81ca39b0cc0a.png)

We should attack also this one, which is related to pop-ups: 

- [ ] https://github.com/CartoDB/cartodb/issues/11871

- [ ] https://github.com/CartoDB/cartodb/issues/11660

Also, just in case: This edition mode will be able only for Builder, on the public page the pop-ups won't have any change.

cc @noguerol

**Comment by ztephm** [comment]
S/B 12603505

re: EDIT FEATURE - client is requesting ability to change characters in Edit panel's Attribute fields without having to re-type a whole new value & select it via "Add a custom value". We can give steps to reproduce but is it better to open a different GitHub issue for this?

**Comment by noguerol** [comment]
@ztephm this is solved by the suggested interaction by Jose, right? If that's the case, you can answer the client we're working on it. No ETA but will probably be available next Q

**Comment by ztephm** [comment]
@noguerol not sure if this is included - here's problem example:

1. Client clicks ![image](https://cloud.githubusercontent.com/assets/596509/24603259/5b5905d0-1860-11e7-8eab-84006c677479.png) button
2. Client wants to change Name field's "poly one" to "poly ones". Right now that means re-typing the whole thing & selecting Add custom value:

  ![edit_1](https://user-images.githubusercontent.com/1779444/27609166-ff325ece-5b57-11e7-94cd-133e7f61b380.gif)

  Client wants ability to edit this field the same way you can in Data View:

  ![edit_2](https://user-images.githubusercontent.com/1779444/27609347-83546e9a-5b58-11e7-9791-dda03e5d96bc.gif)


Not a big deal to re-type everything if values are short, but it becomes a problem when clients are using paragraphs or have many similar options to search through.

**Comment by ztephm** [comment]
@CartoDB/support please notify S/B 12603505 when issue is closed.

**Comment by michellechandra** [comment]
Please also notifiy S/B: 13051645 re: editing notes feature of the Add Geometry tool

**Comment by alrocar** [comment]
Stale issue. Closing 👋
