### ISSUE TITLE
Adding contextual help to Analysis UI

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#11907]
### Context

We'd like to add a few links to Learn from Builder, as contextual help, to help users understand analysis better. For more context about this, please take a look at the [design issue](https://github.com/CartoDB/design/issues/657). 

Let us know whenever you start working on this so we can all have a kickoff together.   

### Design 

The link says "More info" and it's placed below the analysis name, on the second step of each analysis:

![contextual-help_02_analysis](https://cloud.githubusercontent.com/assets/16247628/24609991/3933f858-187d-11e7-8d54-55aca248375a.png)

We are also changing the "Info about analysis" link to "More info" in the Add analysis modal and moving it below the analysis description in uppercase. In the cases where there's no guide for that analysis yet, we just don't show any link on the card.

![contextual-help_01_add-analysis](https://cloud.githubusercontent.com/assets/16247628/24609990/392f1afe-187d-11e7-9885-837e56369db9.png)

This means that we are only linking to Learn and removing this second step of that modal window:

![screen shot 2017-04-03 at 15 01 42](https://cloud.githubusercontent.com/assets/16247628/24610342/7bdce984-187e-11e7-97d7-bebb2b3ae4ee.png)

And thanks to that we could close these other issues:

- https://github.com/CartoDB/cartodb/issues/11057
- https://github.com/CartoDB/research/issues/169

### Measurement 

Could you add a class to those links (one for the links on the analysis UI and another for the modal links) so we could measure their performance? 

### Links

- **Enrich from Data Observatory:** https://carto.com/learn/guides/analysis/enrich-from-data-observatory
- **Filter by Layer:** https://carto.com/learn/guides/analysis/filter-by-layer
- **Georeference:** https://carto.com/learn/guides/analysis/georeference
- **Join Columns from 2nd Layer:** https://carto.com/learn/guides/analysis/join-column-from-second-layer
- **Intersect Second Layer:** https://carto.com/learn/guides/analysis/intersect-second-layer
- **Create Areas of Influence:** https://carto.com/learn/guides/analysis/areas-of-influence
- **Find Centroid of Geometries: https://carto.com/learn/guides/analysis/find-centroid-of-geometries**
- **Group points into polygons: https://carto.com/learn/guides/analysis/group-points-into-polygons**
- **Filter by Column Value: https://carto.com/learn/guides/analysis/filter-by-column-value**
- **Filter points in polygons: https://carto.com/learn/guides/analysis/filter-points-in-polygons**
- **Connect with Lines:** https://carto.com/learn/guides/analysis/connect-with-lines
- **Subsample percent of rows: https://carto.com/learn/guides/analysis/subsample-percent-of-rows**
- **Calculate Clusters of Points:** https://carto.com/learn/guides/analysis/calculate-clusters-of-points
- **Detect Outliers and Clusters:** https://carto.com/learn/guides/analysis/detect-outliers-and-clusters
- **Predict Trends and Volatility:** https://carto.com/learn/guides/analysis/predict-trends-and-volatility

@namessanti could you confirm us if that list is correct?

___

Regarding the Design team, I'm the owner of the project, so please ping me if there's any doubt or question about the issue 🙃

**Comment by namessanti** [comment]
@arianaescobar Looks good.

FYI
Two of those analysis that don't have guides are ready to be merged in the [Learn design pipeline project](https://github.com/CartoDB/learn/projects/5):
Centroids of Geometry: https://github.com/CartoDB/learn/pull/285
Group Points into Polygons: https://github.com/CartoDB/learn/pull/306

The remaining outstanding analysis guides progress is tracked here: https://github.com/CartoDB/learn/issues/312

Looking forward to rolling this out.

**Comment by saleiva** [comment]
Thos are already in the kanban! @csubira is just landing (HA!) so expect an speed increase during the next few weeks

**Comment by nobuti** [comment]
To whoever to take this. In order to add the measurement css class, let's take the component forms as an example, so those links should be something like `track-[analysis name]-form-learn` and `track-[analysis name]-modal-learn` for instance.

**Comment by Jesus89** [comment]
Hi @arianaescobar, what about the "Find nearest" link?

**Comment by arianaescobar** [comment]
@Jesus89 https://carto.com/learn/guides/analysis/find-nearest

**Comment by arianaescobar** [comment]
@Jesus89 I updated the original list of links because we already have guides for every analysis.

**Comment by Jesus89** [comment]
OK Thanks!

**Comment by Jesus89** [comment]
One more question @arianaescobar. The link must be opened in a new tab, right?

**Comment by arianaescobar** [comment]
yes!

**Comment by Jesus89** [comment]
I have checked that the analysis modal has no the same style as the design:

![selection_023](https://user-images.githubusercontent.com/2227572/30536573-9b66072e-9c66-11e7-92ea-0113cb63b4a6.png)

@arianaescobar Can I fix that (border, paddings, etc)?

**Comment by arianaescobar** [comment]
That would be amazing! Maybe let's leave the padding differences for later, the most urgent changes from our point of view are the following ones: 

![add analysis modal](https://user-images.githubusercontent.com/16247628/30537613-a3fe2142-9c6a-11e7-8752-872b88a8f9ae.png)

(left: mockup / right: production)

**Comment by namessanti** [comment]
@csobier for visibility & asset update (soon)

Nice work design guys/gals

**Comment by nobuti** [comment]
Closed by #12814
