### ISSUE TITLE
Pop-ups aren't respecting right margins when the content is too long

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#11900]
### Steps to Reproduce

1. Activate pop-ups on a layer
2. Add a column that has long content 
3. Check out the pop-up

### Current Result

![screen shot 2017-03-30 at 18 50 38](https://cloud.githubusercontent.com/assets/16247628/24555341/1a8ffe18-1631-11e7-8656-7fb240f42aeb.png)

### Expected result

We should add an ellipsis to the value to avoid these situations.

**Comment by xavijam** [comment]
This ticket is in CartoDB.js (CARTO.js) repository, thanks 💋 .

**Comment by piensaenpixel** [comment]
But, be careful with this because if we add the ellipsis we can cut the
fields with more than one line

**Comment by arianaescobar** [comment]
@xavijam You mean I should move this to that other repo?

**Comment by xavijam** [comment]
Yes.
