### ISSUE TITLE
Typo in Builder

### ISSUE THREAD

**Issue by arredond** [CartoDB/cartodb#11918]
@arredond commented on [Wed Apr 05 2017](https://github.com/CartoDB/support/issues/614)

### Context

There's a small typo in Builder when running an analysis

### Steps to Reproduce

*Please break down here below all the needed steps to reproduce the issue*

1. Run an _Intersect by second layer_ analysis
2. **Without** selecting an _Intersect layer_, click on COUNT (Operation) and change to any other operation, such as SUM.
3. The following text appears: "There is no column items"

### Current Result

The text says "There is no column items"

![typo_are](https://cloud.githubusercontent.com/assets/19406854/24696739/c7ff1950-19ea-11e7-8484-e5e07762853c.png)

 
### Expected result

It should say "There _are_ no column items"

---

@xavijam commented on [Wed Apr 05 2017](https://github.com/CartoDB/support/issues/614#issuecomment-291795178)

Hey, please, if there is no customer information related, could we open those tickets in the CartoDB repository? @jsanz 

---

@arredond commented on [Wed Apr 05 2017](https://github.com/CartoDB/support/issues/614#issuecomment-291797393)

Sure, sorry about that!

**Comment by xavijam** [comment]
Merged!
