### ISSUE TITLE
AOI Buffer Analysis with Tracts yields duplicate cartodb_id's for multiple rows rendering further analysis as problematic as cartodb_id should be unique

### ISSUE THREAD

**Issue by nygeog** [CartoDB/cartodb#11916]
### Context
*Please explain here below what you were doing when the issue happened*

AOI Buffer Analysis with Tracts yields duplicate cartodb_id's for multiple rows rendering further analysis as problematic as cartodb_id should be unique. cartodb_id should be unique. This affects many of the Analysis tools after the Radial Buffer (AOI) Tract is run.

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. AOI Radial Buffer Analysis
2. Set a number of Tracts Greater than 1 
3. Run Data Obs. 

### Current Result
*Please describe here below the current result you got*

Multiple rows w/ same cartodb_id which should be unique. 

### Expected result
For it to assign DO to geoms

### Browser and version
*What internet browser (Chrome, Firefox, etc) and version was you using and version*

Chrome

### .carto file
*Don't forget to rename .carto file to .zip file to be able to upload to github*

[Data.Obs.Test.20170403.on.2017-04-04.at.03.10.55.zip](https://github.com/CartoDB/cartodb/files/893607/Data.Obs.Test.20170403.on.2017-04-04.at.03.10.55.zip)

### Additional info
*Please add any information of interest here below*

cc @AbelVM y @talos

**Comment by talos** [comment]
👍 AoI is a super common input before DO, but it's impossible for us to assign data to the correct geometry if we don't have a unique identifier.

**Comment by noguerol** [comment]
@rochoa, thinking about time, do you think this is a candidate for the response team?

**Comment by rochoa** [comment]
Up to you!

**Comment by noguerol** [comment]
No. I mean if this could be solved in a two week time span.

**Comment by rochoa** [comment]
This specific case, yes. Having a general solution for the whole duplicated cartodb_id situation, I don't know.

**Comment by oleurud** [comment]
The fix is already in production and working well :)
