### ISSUE TITLE
Map state not properly after zoom

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#11926]
### Steps to Reproduce
Please see attached GIF for a graphical explanation of these steps:

1. Zoom to deep levels. In the GIF you can see that we start from zoom level 18 to level 21.

2. Refresh the page

3. The map shows zoom level 20. The previous one.

![zoom bug](https://cloud.githubusercontent.com/assets/1078228/24704734/265e79aa-1a09-11e7-875b-fb1d6c0b8e7f.gif)

**Comment by xavijam** [comment]
I feel it is related with https://github.com/CartoDB/cartodb/issues/11486 and due to the function we have in CARTO.js in order to calculate the zoom for the bounds https://github.com/CartoDB/cartodb.js/blob/v4/src/geo/map.js#L451-L480.
cc @alonsogarciapablo
