### ISSUE TITLE
Hover infowindow does not update its content

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#11921]
### Steps to Reproduce

1. Add a hover pop-up to a map.
2. Check some columns to show in the pop-up.
3. Hover on some items on the map.
4. The popup content does not update properly.

It doesn't trigger any request to `/api/v1/map` API.

### Current Result

![hover](https://cloud.githubusercontent.com/assets/1078228/24701664/9ab1e19c-19fb-11e7-99b4-67158f8876ca.gif)

**Comment by xavijam** [comment]
Already fixed as described in the PR above (^^^).
