### ISSUE TITLE
Custom widget opacity (for Auto style) not applied?

### ISSUE THREAD

**Issue by csobier** [CartoDB/cartodb#11928]
- Create a Category or Histogram widget.
- Edit the widget options and apply a custom color scheme to the data, to be applied when _Auto style_ is selected.
- Use the opacity slider, or the opacity input field, to change the opacity for the auto style color scheme. 

The modified opacity correctly appears from the widget behavior options, but does not appear on the visualization when _Auto style_ is applied.

![image](https://cloud.githubusercontent.com/assets/13319925/24706032/49bc49fe-19dc-11e7-9826-136bcaa18642.png)

**Note:** I tested the same opacity behavior from the STYLE tab (when styling by value) and it works correctly there. This is specific to modifying the opacity for widget auto style color schemes. 

@saleiva, is this just not implemented yet, a bug, or unintended behavior?

**Comment by saleiva** [comment]
I'll research on this soon cc/@noguerol

**Comment by noguerol** [comment]
csobier, a bug indeed, as autostyle has no opactity implemented.

**Comment by michellechandra** [comment]
S/B: 13138235

**Comment by michellechandra** [comment]
Is there an update on this issue?

**Comment by saleiva** [comment]
this should be a candidate for the response team

**Comment by ramiroaznar** [comment]
Should I reassign this then to @noguerol?

**Comment by rubenmoya** [comment]
I've been trying to reproduce it and I don't see the opacity selector:

![screen shot 2017-07-27 at 09 29 43](https://user-images.githubusercontent.com/905225/28659058-4c8dcb00-72ae-11e7-96fa-50de19e55958.png)

Has this been fixed already? cc @CartoDB/frontend

**Comment by ramiroaznar** [comment]
Hey @rubenmoya you need to click on the colors:
* Histograms:

![histo](https://user-images.githubusercontent.com/5215798/28660455-3d2a9eb8-72b3-11e7-8d9f-7852e54f3832.png)

* Categories:

![cat](https://user-images.githubusercontent.com/5215798/28660444-363472be-72b3-11e7-8e13-2d17ed16f48e.png)

**Comment by rubenmoya** [comment]
In production! 🚀
