### ISSUE TITLE
Upgrade Node.js version to current LTS one

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb#11935]
In order to not depend on a deprecated/not supported version of Node.js, we need to upgrade to a recent, LTS, version.

CartoDB-SQL-API and Windshaft-cartodb projects are already migrated. However, some of the frontend tools rely upon, and enforce, the use of Node.js v0.10.x and NPM 2.14.x versions.

To complete the migration we need to test, fix, and adapt any tool that relies on Node.js or NPM.

The Node.js target version is v6.x.

cc @CartoDB/frontend @CartoDB/systems @jorgesancha

**Comment by xavijam** [comment]
Added to frontend bundle assets improvement milestone.

**Comment by xavijam** [comment]
@CartoDB/systems will we have that new version in the CI machines as well right?

**Comment by xavijam** [comment]
We have to block it until we have tests passing in our CI, comented [here](https://github.com/CartoDB/cartodb/pull/11941#issuecomment-292908800) and with @luisbosque offline.

**Comment by jvillarf** [comment]
@xavijam yes, we are fully aware of this blocking and currently working on a solution :)

**Comment by xavijam** [comment]
I've checked if it is possible to install with node 0.10 the dependencies specified with 6.9.2 and it is not working :(. I feel we will need to make the "thing" with the two shrinkwraps.

**Comment by rochoa** [comment]
What is the "thing"?

**Comment by xavijam** [comment]
@luisbosque proposed to have two npm-shrinkwrap versions. One generated by `v0.10` and another for `6.9.2`.

**Comment by xavijam** [comment]
Adding blocked label again until we can test it in staging and CI tests can pass.

**Comment by jvillarf** [comment]
- CI testing should work (https://github.com/CartoDB/cartodb-platform/issues/3232): we are ready to move **CI testing** nodes to **node6**
- Regarding **staging**, there are only a few servers pending, mainly **ded0X** and we should be good to go (https://github.com/CartoDB/cartodb-platform/issues/3228)

**Comment by nobuti** [comment]
Deploying.

**Comment by nobuti** [comment]
Deployed
