### ISSUE TITLE
Exporting an image form working when it's not valid

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#11949]
### Context
Export an image of a map.

### Steps to Reproduce

1. Set basemaps to Google (it has a lower limit)
2. Set the size of the image to something bigger than limits (1000x1000 for a Google basemap, for instance).
3. The form warns the user that the limit has been surpassed.

### Current Result

The button to export the image is enabled, allowing the user to export the map.

### Expected result

The button is disabled, disallowing the user to export the map.

### Browser and version
Seen in Chrome 57.

**Comment by ivanmalagon** [comment]
![image](https://cloud.githubusercontent.com/assets/1078228/24857233/e1836b6e-1de7-11e7-9c91-870c0c774c1b.png)

**Comment by xavijam** [comment]
This is important, and in my opinion, we should fix it before release the feature. 
cc @noguerol @saleiva

**Comment by saleiva** [comment]
Absolutely.
BTW is that 640 x 640 limitation something fixed? I'm afraid that will not work for some use cases

**Comment by xavijam** [comment]
640x640 is a Google Maps limitation, it is ok.

**Comment by saleiva** [comment]
but... our clients are paid Google clients, so we can go to bigger sizes, right?

**Comment by xavijam** [comment]
It depends if they are premium plans, if so, yes, it works of course. It is defined by a paramater. All info is here, but @javierarce already did a [nice analysis](https://github.com/CartoDB/cartodb/issues/11775#issuecomment-288425323) and implemented with that https://developers.google.com/maps/documentation/static-maps/intro.

**Comment by saleiva** [comment]
ok!

**Comment by xavijam** [comment]
Closing since it is in production.
