### ISSUE TITLE
Remove feature-flag code/checks for new org notifications functionality

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#11947]
That means, we should:

- [x] Remove the **feature flag checker** in order to show/hide the notifications panel.
- [x] Remove the **feature flag** (don't forget to remove it from production and staging).

**Comment by xavijam** [comment]
@noguerol and @saleiva, when you decide.

**Comment by saleiva** [comment]
IMO, we should open this right now.

**Comment by juanignaciosl** [comment]
Ey, you can open it to everybody just unchecking the "restricted" flag at superadmin. The tasks at this issue are just for code cleanup.

**Comment by xavijam** [comment]
It is already opened yep, we want to remove the code, yes.

**Comment by xavijam** [comment]
Changed title, sorry for the mixed up.

**Comment by javitonino** [comment]
Although this is ready, I am holding because I found a couple of UI bugs during acceptance that I think should be fixed before opening this to the public: https://github.com/CartoDB/cartodb/issues/11957

**Comment by xavijam** [comment]
Added in the TODO column due to the fact that it belongs to a current milestone.
