### ISSUE TITLE
Autoload Gears API

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#11948]
We should consider eager loading Gears API, instead of forcing the user to do requires, in order to be consistent with the rest of the code. Could also help with our initialization issues in production: https://github.com/CartoDB/cartodb-platform/issues/3206

Some reading: http://blog.arkency.com/2014/11/dont-forget-about-eager-load-when-extending-autoload/

**Comment by javitonino** [comment]
<🦆>

I took some time to understand how Rails autoloading works. Hard to explain here, so I'll write some highlights. I am testing all of this with loading `CartoGearsApi::Users::UsersService`.

- If you disable `threadsafe!'  (btw, that doesn't exist in Rails 4, everything is threadsafe, always), then you get the expected behaviour, that is, writing `CartoGearsApi::Users::UsersService` in the console works without requiring it.
  - This works because Rails installs a `const_missing` handler that autodetects the file to load based on Rails convention.
  - This loading of stuff is not threadsafe, so in that case, the previous hook is installed, the initializers are run, and then the hook is uninstalled. This allows autoloading to work for all classes that are somehow loaded during initialization (which includes everything under `app`).
- The previous can be worked around by adding the diectory to `config.eager_load_paths` which basically creates an initializer that loads everything in that folder during startup. This is what Rails does for the `app` directory.

I'm doing some testing but, if we add all relevant paths to `autoload_paths` (reloading in development environment) and `eager_load_paths` (preloading), we should be able to remove all `require_dependency`es from the code.
</:duck:>

**Comment by juanignaciosl** [comment]
1.- Are you speaking about CARTO Gears API, or the full project?
2.- Would that explicit load (`eager_load_paths`) fix CartoDB/cartodb-platform/issues/3206 ?

I must say that I like the approach of having `/app` contain Rails-related code, and keeping any other thing at `/lib`, but I don't really know. In addition, I'm also thinking about adopting Trailblazer patterns (even without using the gem), and that includes directories.

**Comment by javitonino** [comment]
1.- A bit about both. The same thing about needing `requires` for Gears API applies to everything in `/lib`. We are breaking some Rails conventions by putting stuff in `lib` and loading using `requires` instead of relying on autoloading. We should have added `lib` to autoloading instead of using requires.

2.- Not sure as it is hard to reproduce. I think it would base on analyzing the reloading code, but I cannot be sure. The cannot find helpers thing looks into the `autoload_paths` to determine where to search for stuff, and this is only set for the development environment. In fact, I just realized (:heart: rubberducking), this should not be working at all. I think it works because `bundle` adds the `gem_path/lib` directory to the search path. 🤔 

3.- This is only for the main application. The only problem with `/lib` is that it's shared with frontend and Rails doesn't have a way to exclude subdirectories from the autoloading. Something like `/lib/rails` would work, or moving the assets outside of `/lib`.

**Comment by juanignaciosl** [comment]
1.- I really have mixed feelings about autoloading. I wanted to tackle this issue in order to discuss this, indeed. I know that I'm Java biased, but I'm good with explicit dependencies. For example, I recently made a unit test that break because the class under test had an implicit dependency to Rails. I don't see that much value on avoiding three or four requires on top, and it helps to perceive a class that depends on 20 files as a probable smell. Whatever we chose, I wouldn't change it for the main app.

2.- I think that it works [because of this loading at application.rb](https://github.com/CartoDB/cartodb/blob/bf91ea1b623e82faf241d1714b644ac883406ab4/config/application.rb#L198).

3. I must admit that I don't know what's wrong with the assets.

**Comment by javitonino** [comment]
2.- That makes sense. I'll take a look around that.
3.- Basically, for development, it makes the Rails server file system watcher awfully slow to detect changes (in order to reload classes) and that is run on every request. Also, Rails traverses the `lib` directory looking for matches when requiring a thing (but that should not be minor, as it doesn't do a depth-first search).

1.- The big one.
First, I like explicit loading. Specially in languages that enforce it. I don't like that in Ruby, if you have required a file in class A, you do not need to require it again in class B (assuming the load order is A, then B). A lot of stuff depends on loading order.

That said, I hate to say that I think we should go for autoloading if we use Rails. I'll link to the [docs about `require_dependency`](http://guides.rubyonrails.org/autoloading_and_reloading_constants.html#require-dependency) but that whole page have some interesting points. Basically, Rails has its own class loader based on `const_missing` to load the class in first use, and matching filenames with classnames, you know the drill. The problem (as always) is that Rails is very opinionated and really hates when you do things in a different way. It really likes to screw if you do something special. 

But, there is nothing broken with our current approach, so maybe we can keep it. Some ideas to incrementally improve:
- Use Rails variables for configuration (instead of touching `$LOAD_PATH` and `ActiveSupport::Dependencies` directly)
- Move some of the initialization from the main application to the engine itself (its configuration is added to the parent). Maybe a `Gear` class that subclasses `Rails::Engine`? This allows us to have different eager_loading policies for different gears (we may want to preload CartoGearsApi since it's called from the main code, but maybe not some other gears that don't have this requirement).

That's all very speculative, but maybe the seeds for some discussion.

**Comment by juanignaciosl** [comment]
2.- Ok.
3.- Oh, we're speaking about that issue (I haven't suffered it again). Now your previous sentence about assets makes sense to me. What if we move to [Trailblazer folder structure](https://github.com/trailblazer/trailblazer#concepts-over-technology)? That fixes this issue, provides structure to the catchall that `/lib` became, and eases a future transition to Trailblazer if we decide to do it. I'd only do for the Gears API now, though.

1.- Disagree:

>  if you have required a file in class A, you do not need to require it again in class B (assuming the load order is A, then B). A lot of stuff depends on loading order.

That's true, but if you don't require it, it won't work. So, saying that "Ruby enforces explicit loading, _at runtime_" is more accurate. Not needing it if somebody has previously loaded it is a harmful side effect of its dynamic nature.

That said, I could still embrace the Rails way if there's a clear benefit (other than not requiring `require.*`). Meanwhile, your suggestions look nice.



PS: I've been searching for a consensus about "require best practices", but I didn't get to any valuable conclusion. Ruby certainly did not encourage autoloading, but Rails has screwed almost everything. Of course, I've found a ["Every file should require what it needs to operate" opinion](https://www.reddit.com/r/ruby/comments/3341zm/require_best_practices/cqhuw9r/), but this is the Internet and I could've found anything that I wanted to.

**Comment by javitonino** [comment]
As a comment, Trailblazer avoids autoloading by preloading everything, it doesn't seem to use explicit requires either. It seems the Ruby community really dislikes having to require stuff before use (like you said, Rails has a lot of influence in Ruby's direction).

I think we are in more agreement than this discussion seems to suggest. But anyway, I think we both agree in my suggestions of trying to configure Gears autoloading using Rails auto/eager loading, instead of manually tweaking the load paths.

I'll give it a try and see if we get something useful out of that change. In any case, I've learned a lot about autoloading, and I'll keep it in my thoughts for a few days to see if I came up with something interesting.

**Comment by juanignaciosl** [comment]
_waiting for a CartoLearn talk about autoloading :D_

**Comment by javitonino** [comment]
Two options here, talking only about autoloading of gears:
- Enable autoloading. This removes the requirement of adding `require_dependency` everywhere. It also allows to have circular dependencies like in https://github.com/CartoDB/cartodb/pull/11892/commits/fc55f7cfa3983f471115d2694ec010c1319d32cc, which could be interesting for `carto_gears_api`.
- Do not enable autoloading, pretty much opposite consequences. Main advantage is that the code is more explicit.

My favorite option here is to, in CARTO initialization code, instantiate the gear `Engine` class. This allows the gear to add configuration to the main application, in this case, the Gear creator can decide whether to use autoloading or not. In this case, my approach would be to use autoloading in `CartoGearsApi` and other gears that tightly integrate with Rails code. And to use normal ruby requires (no autoloading) for the rest (mainly gears that are built on top of CartoGearsAPI).

This approach is compatible with both proposed solutions to the [reload problem](https://github.com/CartoDB/cartodb-platform/issues/3206#issuecomment-294744074). What do you think?

**Comment by juanignaciosl** [comment]
I like your proposal 👍  _Open to extension, closed for modification_™

**Comment by juanignaciosl** [comment]
Let's keep it for the moment. If everything goes as expected in production, then we'll clean it.
