### ISSUE TITLE
Markdown links in new tab

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#11940]
### Context
One the issues pointed out by @noguerol in this PR https://github.com/CartoDB/cartodb/pull/11842 was that links should open in a new tab. The HTML code generated from Markdown is done in backend.

### Steps to Reproduce

1. Create a notification with a link in Markdown `[carto](https://carto.com)`
2. Click on the notification
3. The link gets opened in the same page.

### Expected result

Link gets opened in a new tab.

**Comment by xavijam** [comment]
@noguerol, you requested this for the new notifications and we have decided to create a new ticket for that. If you consider it is important we will prioritize it next week. @juanignaciosl.
