### ISSUE TITLE
Issues with org notifications UI

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#11957]
I think these issues block removing the FF and opening up to the public! cc @xavijam 

1. Firefox and Chrome. Pressing cancel in delete a notification dialog, removes it anyway
![out-a](https://cloud.githubusercontent.com/assets/7569673/24899540/f98171c0-1ea0-11e7-872a-7600a7719640.gif)

2. Only Firefox. You have to press "Send" twice for the notification to be sent
![out-b](https://cloud.githubusercontent.com/assets/7569673/24899556/03d118e2-1ea1-11e7-969e-ab7e2b9d0fc8.gif)

**Comment by javitonino** [comment]
Hey @saleiva! Not only Firefox. The deletion dialog thing happens in Chrome as well. Also, I know the issue title sucks, and I should have opened two of them, but seemed like a waste for such minor issues).

**Comment by xavijam** [comment]
Deployed!
