### ISSUE TITLE
Exporting a big image doesn't trigger an image download

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#11950]
### Context

Exporting a image of a map.

### Steps to Reproduce

1. Set image limits to something big, like 8192x8192.
2. Export image.
3. After some time, the request is finished, the button re-enabled but the image doesn't download.

### Browser and version

Tested in Chrome 57

**Comment by xavijam** [comment]
That's a good example about if we want to let the users export an image bigger than the browser.

**Comment by xavijam** [comment]
I'd like to take a look with @rochoa, just in case. Because the image generated gives a 200 but looks like it is bad formed, not 100% sure.

**Comment by ramiroaznar** [comment]
Closing > https://github.com/CartoDB/support/issues/970
