### ISSUE TITLE
[Style with icons] No multiple file upload through "upload file" tab

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#11952]
### Context
Multiple icon upload though the "upload file" tab doesn't let users upload multiple files at once (in comparison to "your icons" tab or organizational settings upload)

### Steps to Reproduce

1. Open the the style with icon modal window
2. Try to upload several images through the "upload file" tab

### Current Result
You cannot select multiple files

### Expected result
But you should

cc @asimcox

**Comment by nobuti** [comment]
Up and running.
