### ISSUE TITLE
Invalid geometry error when trying to edit a value in table view

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#11979]
### Context
When trying to edit a value in table view, an invalid geometry error appears.

### Steps to Reproduce

1. Clic on table view
2. Manually edit a value

### Current Result
![captura de pantalla 2017-04-12 a las 12 59 53](https://cloud.githubusercontent.com/assets/70603/24954699/ac71a414-1f80-11e7-8abb-8e6d500c109d.png)

### Expected result
Value could be edited

**Comment by saleiva** [comment]
When you mean a value, you mean any cell?

**Comment by xavijam** [comment]
Already reported https://github.com/CartoDB/cartodb/issues/11855.
