### ISSUE TITLE
remove org. notifications: dialog view is not removed from DOM

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#11976]
when closing "remove org. notifications" dialog we should destroy the view, as we do in asset picker

https://github.com/CartoDB/cartodb/blob/master/lib/assets/core/javascripts/cartodb/organization/icon_picker/icons/organization_icons_view.js#L249

dialogs are not being removed after close, and new views keep adding to the DOM

![screen shot 2017-04-12 at 12 09 59](https://cloud.githubusercontent.com/assets/36676/24952887/8703a01c-1f79-11e7-817c-1d1d479544c7.png)

**Comment by xavijam** [comment]
Hey, we have been working in this modal, why not add it here https://github.com/CartoDB/cartodb/issues/11957?

**Comment by matallo** [comment]
👍 for me, I didn't want to bloat the issue with more stuff now it passed CR already

**Comment by matallo** [comment]
tacked https://github.com/CartoDB/cartodb/pull/11961

**Comment by xavijam** [comment]
Nice!

**Comment by xavijam** [comment]
Closed because it is already done.
