### ISSUE TITLE
Source / Attribution Markdown support not consistent

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#11977]
### Context

During #11940 [a bigger refactor was suggested](https://github.com/CartoDB/cartodb/pull/11968#issuecomment-293516438), so every Markdown rendering is done with the same code. When I tested it I found a small inconsistency on Markdown support.

This is the dataset metadata modal. As you see, only the description declares support for Markdown:

![captura de pantalla 2017-04-12 a las 12 19 31](https://cloud.githubusercontent.com/assets/932968/24953092/5b545d84-1f7a-11e7-9ffa-c92ab28d53ac.png)

Nevertheless, the source (at the bottom, of the next screenshot) is also rendered with Markdown, but the attribution is not (at map bottom right corner):

![captura de pantalla 2017-04-12 a las 12 21 10](https://cloud.githubusercontent.com/assets/932968/24953165/98a304f6-1f7a-11e7-8bf1-dd211f40f74c.png)

### Steps to Reproduce

1. Set description, attribution and source for a dataset, all with some Markdown.
2. Open the public view.

### Current Result

I don't actually know. I'd suggest to explicitly add the Markdown icon at source field so everybody knows that it has Markdown, while attributions hasn't, but I can't say. cc @noguerol @xavijam

**Comment by xavijam** [comment]
IMHO, it express that only description accepts markdown.

**Comment by xavijam** [comment]
No idea why source supports markdown, i have to say.

**Comment by noguerol** [comment]
Only description should support markdown, so we should include the markdown tag inside the text field and disable its support for the `source` field.
