### ISSUE TITLE
Time series widget does not include max (min) value in upper (lower) range

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartodb#11970]
### Context

Working with a client today, we tried to create a simple time series widget that showed the number of counts for each year. We tried two columns:

1. One had years (**original column**): 2000, 2001, 2002, ..., 2012 (13 in total)
2. The other was converted to dates (using `to_date(time_col, 'yyyy')` -- 'convert to time' converted it to seconds after the epoch so had to do the SQL way): 2000-01-01T00:00:00Z, 2001-01-01T00:00:00Z, ..., 2012-01-12T00:00:00Z

As such, you would expect that creating a time series widget with any number of bins would have a lower range of `2000-01-01T00:00:00Z` and an upper range of `2012-01-01T00:00:00Z`

Instead, the upper range does not include the max value of `2012-01-01T00:00:00Z`:
<img width="657" alt="screen shot 2017-04-11 at 16 58 22" src="https://cloud.githubusercontent.com/assets/1041056/24930640/26a64022-1ed8-11e7-9c9e-22fdda675897.png">

And the lower range goes below the minimum value:
<img width="674" alt="screen shot 2017-04-11 at 17 18 43" src="https://cloud.githubusercontent.com/assets/1041056/24931354/f6454aa6-1eda-11e7-8ea8-8f4ff092c54e.png">

Get a mock dataset I made here: https://team.carto.com/u/eschbacher/tables/mock_time_data/public.

Trying this out with datasets with more complex timestamps (e.g., [earthquakes in my account](https://team.carto.com/u/eschbacher/tables/eschbacher.all_month_3/public)), I get similar results.

### Steps to Reproduce

1. Import the time data (https://team.carto.com/u/eschbacher/tables/mock_time_data/public) and create a map
2. Add a time series widget and select the `year_date` column, and set the number of bins to 13
3. Filter the highest category to observe that the max time stamps (`2012-01-01T00:00:00Z`) are not in the range, perform the same operation for the lowest time stamp.

### Current Result

Max value does not appear to show up on the widget. Min value of dataset is larger than the min value displayed in the time series widget.

### Expected result

The bin with the highest values should include the max value as the upper range when filtering. Similarly, filtering in the bin with lowest values should have the lowest range when filtering.

### Browser and version

Chrome Version 56.0.2924.87 (64-bit), macOS Sierra 10.12.4

### .carto file

* Data: https://team.carto.com/u/eschbacher/tables/mock_time_data/public

### Additional info

None

**Comment by noguerol** [comment]
cc @rochoa as this is maybe rooted in Engine

**Comment by rochoa** [comment]
The data returned from the server side is in the original data timezone, but the representation at the client side is in the browser/user timezone.

So, with that dataset, I get a different result when seeing it with the Madrid timezone.

![madrid-timezone](https://cloud.githubusercontent.com/assets/45346/25230751/7a4af3a4-25d5-11e7-9c3f-bb1a7bfaba90.png)

This is consistent with Torque behavior. If we want to change this behavior, we should also address the Torque situation.

**Comment by noguerol** [comment]
Updating with what we agreed offline: we process time columns internally in UTC but then aggregate the time series widget based on a selectable time zone in the widget configuration, which by default shows the browser timezone.

**Comment by andy-esch** [comment]
+1 to selectable time zone :) 

If the time data is going to be transformed in any way, we need to make sure that that transformation is conveyed on the widget to the end user (e.g., the time displayed shold show the timezone -- GMT, EDT, etc.). Otherwise, we are misrepresenting the data and the user could be making incorrect assumptions.

In my opinion, the default behavior should be to display the raw timestamp -- that is, let the data retain it's original form -- and show that original timezone in the widget. My guess is that if you are looking at a map of events in a certain geography, you expect the time to correspond to what is happening in that geography. This obviously gets tricky if the data spans multiple timezones. But I'm thinking that people might be opting into a data transformation that they're not aware of.

Let's say that someone in Hawaii is looking at a map of events happening at 11 a.m. in Germany (which is 12 hours ahead of Hawaii). If the widget is displaying local Hawaii time, that user might be led to believe that the German events are actually happening at 11 p.m. German time, which tells a completely different story.

**Comment by stuartlynn** [comment]
Hey guys

Just my two cents but I think that the time zone should be selectable not on the configuration end but in the end user UI. So if you are a viewer and looking at the timeseries, you have a small dropdown to pick the timezone you would like to see the data. The top choices on that drop down could be "My Timezone","The Datas Timezone" and then a list of all timezones under that.

That means that we have complete transparency and the end user of the LI app gets to pick how they would like to see the data.

**Comment by noguerol** [comment]
Both settings sound very reasonable, so we've splitted this into to different tickets: https://github.com/CartoDB/cartodb/issues/12087 and https://github.com/CartoDB/cartodb/issues/12088

**Comment by xavijam** [comment]
Mates, those tickets have been addressed and properly deployed into master 💋 .
