### ISSUE TITLE
Data view doesn't update with custom geometries

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#11978]
### Context
When adding custom geometries, data view is not updated nor provided in the case it was originally empty.

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Create a new map with an empty layer
2. Add some points via geometry edition
3. Switch to table view

### Current Result
No data

### Expected result
The resulting point table should be shown

**Comment by noguerol** [comment]
Adding new points on a layer with previous geometries also fails in updating the table view.

**Comment by xavijam** [comment]
This is already reported, let me find it.

**Comment by xavijam** [comment]
@matallo, do you remember that ticket? I feel you opened it, didn't you?.

**Comment by matallo** [comment]
not sure it is the same, but it can be related https://github.com/CartoDB/cartodb/issues/11759

**Comment by xavijam** [comment]
Yep @matallo, take a look @nobuti while you fix this one.
