### ISSUE TITLE
{"error":["schema \"cdb_dataservices_client\" does not exist"]}

### ISSUE THREAD

**Issue by CHENXINGYU8** [CartoDB/cartodb#11971]
### Context
Setup development server with docker image, with self assign ssl
setting up development on Ubuntu 12.04.5 LTS on aws ec2

### Steps to Reproduce

1.When creating a new map with any dataset, the error starts to appear with jquery:8630 bad request. {"error":["schema \"cdb_dataservices_client\" does not exist"]}

### Current Result
Bad request, error 400 
 {"error":["schema \"cdb_dataservices_client\" does not exist"]}

![screen shot 2017-04-12 at 10 06 46 am](https://cloud.githubusercontent.com/assets/15316779/24938112/d24b15bc-1f67-11e7-8ea9-145b4b6f989f.png)

**Comment by alexcmrcrk** [comment]
Did you find a solution to this? I am having the same thing. I built my docker with CartoDB/cartodb version 5.0.0.
