### ISSUE TITLE
Subsample analysis is not accurate

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#11988]
### Context
On a 30 point table a 10% subsample outputs 0 results and a 50% subsample, 23.

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Create a map from this csv

[30_points_nyc.csv.zip](https://github.com/CartoDB/cartodb/files/916826/30_points_nyc.csv.zip)

2. Add a subsample analysis

cc @rochoa

**Comment by rochoa** [comment]
Yes, it's supposed to be not accurate. It uses [PostgreSQL's random function](https://www.postgresql.org/docs/9.5/static/functions-math.html#FUNCTIONS-MATH-RANDOM-TABLE) to determine if a row must be part of the sample or not.

cc @javisantana

**Comment by rochoa** [comment]
BTW, does it make sense to sample a 30 rows table?
