### ISSUE TITLE
Time series widget not intuitively giving correct binning 

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartodb#11985]
### Context

Working with a client yesterday, we had a data set of thousands of points, each with a `year` attribute: 2000, 2001, ..., 2012. She wanted to create a simple Time Series widget to filter her map by year, but the result was the following (which must be milliseconds after the epoch?):
<img width="873" alt="screen shot 2017-04-12 at 08 44 28" src="https://cloud.githubusercontent.com/assets/1041056/24958146/51c9b5ac-1f5c-11e7-888e-9fa28509190c.png">

Converting this column to `time` through the dataset interface changes these values to timestamps in 1970, so the values are interpreted as milliseconds. Using SQL to manually convert using `to_date(time_column, 'yyyy')` produces values like `2000-01-01T00:00:00Z`. Creating a time series widget off this column gives:
<img width="817" alt="screen shot 2017-04-12 at 09 23 17" src="https://cloud.githubusercontent.com/assets/1041056/24959797/b6f7ad3a-1f61-11e7-9afa-ef001b71c867.png">

Which is an improvement, but doing any of the filtering quickly gives ranges that are not appropriate:
<img width="896" alt="screen shot 2017-04-12 at 08 50 00" src="https://cloud.githubusercontent.com/assets/1041056/24958358/0a46bb3e-1f5d-11e7-9237-f45e7e36651f.png">

The expectation here would be that the first bin would be `2000-01-01T00:00:00Z` to `2001-01-01T00:00:00Z`. I understand that I could jump through some more hoops in the data prep with SQL to manually create the ranges I want, but this seems like a lot of work for a very common use case.

We next tried creating a histogram widget but the x-axis displayed the values as follows:
<img width="295" alt="screen shot 2017-04-12 at 08 54 09" src="https://cloud.githubusercontent.com/assets/1041056/24958538/9edd015e-1f5d-11e7-941c-a56e1889a472.png">

Here, the lack of precision in displaying the numbers is a problem.

Finally, we did a category widget:
<img width="299" alt="screen shot 2017-04-12 at 08 55 30" src="https://cloud.githubusercontent.com/assets/1041056/24958596/d3ca03ee-1f5d-11e7-98c1-51d17b59057f.png">

This is the closest, but the user needed the full range of data to be displayed on the widget like in the time-series widget. She also needed it to be ordered from 2000 upward like on the time series widget.

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Import my mock dataset and create a map: https://team.carto.com/u/eschbacher/tables/mock_time_data/public
2. Create a time series widget using the `year` column to see the unix timestamp conversion
3. Create a time series widget using the `year_date` and choose 13 as the number of bins. 
4. Filter by time ranges to see that the bin edges do not line up based on expectations
5. Create a histogram widget to see the x-axis precision (`2k` for values 2000 through 2012)

### Current Result

1. Time series does not give intuitive ranges for input values
2. Histogram x-axis rounds too much to give user a sense of the range in values
3. Category widget does not extend to show all values, and does not let you order them correctly

### Expected result

Creating a time series widget off of a column that has a numeric value for year only should automatically have year bins without bleeding into other years.

### Browser and version

Chrome Version 56.0.2924.87 (64-bit), macOS 10.12.4

### .carto file

Just this dataset: https://team.carto.com/u/eschbacher/tables/mock_time_data/public

### Additional info

Work with a client

**Comment by stuartlynn** [comment]
Hey just want to chime in here. This and #11970 are big deal for clients like Two Sigma who work a lot in the time domain. If they aren't seeing accurate results from something like the time series widget they lose confidence in the accuracy of other parts of the product as well. Getting these things precise is really important for data scientists or anyone else who is trying to make informed decisions of the data.

**Comment by jorgesancha** [comment]
cc @rochoa

**Comment by rochoa** [comment]
The problem with the `year` time series is that we are doing a time series around a numeric column, we are using numbers going from 2000 to 2012, not actual dates. That's why the representation is so weird. Should we allow the creation of time-series widgets over not date columns?

When transforming the `year` column into a real date column, we are facing the problem described in https://github.com/CartoDB/cartodb/issues/11970#issuecomment-295717706. The server side returns the data in UTC, but the client represents the dates in the browser timezone.

About the histogram, it's a formatting issue in the client. That's something we can improve by not rounding those x-axis ticks when the start and end bins are so close.

**Comment by jorgesancha** [comment]
cc @xavijam

**Comment by rochoa** [comment]
From here it's more a product decision than a technical one, reassigning to @jorgesancha for coordination.

**Comment by andy-esch** [comment]
Big thumbs up for time series off of numeric columns (or even text columns). Time data often comes in numeric or text forms: years as integers (e.g., 2000-2017), months as integers (1-12) or strings ('January', 'February', 'March', ...), days as integers (1-365), etc. We can't count on our users to know how to convert it, especially since we can't do the column conversion from a number to a date in the Builder:
<img width="410" alt="screen shot 2017-04-24 at 11 33 43" src="https://cloud.githubusercontent.com/assets/1041056/25345074/fffd297c-28e1-11e7-9af0-eb52460666a2.png">

What seems like the easiest option to me is letting the user specify the format of the date. They may need to use a month column and a year column to combine into a timestamp. Or I could see a user wanting to use named months in the time column, or even more complicated strings-based dates. Doing `year_column::timestamp` (which is what I assume is happening in the background) only handles a minority of cases.

Creating a Torque map from a numeric column puts on a time series widget that shows the numeric values instead of dates. I tried it with a few datasets in my account with the `cartodb_id`:

<img width="908" alt="screen shot 2017-04-24 at 11 42 47" src="https://cloud.githubusercontent.com/assets/1041056/25345467/2e1e037a-28e3-11e7-8842-342967292c34.png">

That looks fine, but the problem is what happens when trying to change the number of bins: the scrubber updates but the underlying histogram doesn't change.

For the case of the server-side/client-side display, I think that should be a behavior that the end user opts into, otherwise it misrepresents the data and people in different timezones will unknowingly be seeing different 'answers' without any apparent reason for the differences.

cc @stuartlynn 

---

As a side note, there were actually two different behaviors: creating a time series widget from a numeric column coerced it into a date, while creating a torque map (which added the time series widget) adds the widget and does not seem to coerce the numeric column into a date.

**Comment by saleiva** [comment]
we supported animated (or time-based) maps by numeric columns before, so I'm afraid we should keep going in the same way. Plus there are a few use cases where this is useful.

I'd separate both issues. That issue with timezones should be addressed (finally) in a separated issue.

I do think that this could be partially fixed by doing what @xavijam was suggesting in another issue (that I cannot find now :_( ) which is adding the time-granularity selector as part of the widget UI.
![036831d2-ff3a-11e6-89b2-6cd4407205c9](https://cloud.githubusercontent.com/assets/132149/25347052/eff747f0-2919-11e7-986b-147e5cfb74a2.png)

**Comment by andy-esch** [comment]
@saleiva, this issue? https://github.com/CartoDB/cartodb/issues/10807

**Comment by xavijam** [comment]
That one!! ^^^

**Comment by noguerol** [comment]
Updating with what we agreed offline: related to the solution proposed in https://github.com/CartoDB/cartodb/issues/11970 , in the widget config we will implement a column type selector between "time stamp" and "numeric", being the latter the proposed solution for this ticket.

**Comment by andy-esch** [comment]
One way to make it easier for the user could be `bin by (year|month|day|hour|...)` if they choose "time stamp". This has the benefit that the user doesn't need to calculate the number of bins the would need given the range of their data.

**Comment by xavijam** [comment]
Good news! Aggregations has been released and look at the results with your dataset @andy-esch  ❤️  💋 .

![screen shot 2017-08-08 at 11 19 45](https://user-images.githubusercontent.com/132146/29065236-be194f70-7c2b-11e7-8cb8-cbe9a82d413e.png)
![screen shot 2017-08-08 at 11 20 06](https://user-images.githubusercontent.com/132146/29065237-be40fb2e-7c2b-11e7-8813-e32220854c5d.png)
![screen shot 2017-08-08 at 11 19 58](https://user-images.githubusercontent.com/132146/29065238-be468b7a-7c2b-11e7-8f27-9aabe3b28aca.png)
![screen shot 2017-08-08 at 11 20 14](https://user-images.githubusercontent.com/132146/29065239-be4684c2-7c2b-11e7-8f7c-8484f1825fe0.png)
![screen shot 2017-08-08 at 11 20 21](https://user-images.githubusercontent.com/132146/29065240-be500a24-7c2b-11e7-8770-27c87471d524.png)
![screen shot 2017-08-08 at 11 21 51](https://user-images.githubusercontent.com/132146/29065258-d3ba35ba-7c2b-11e7-91c7-a13390954fd6.png)

**Comment by xavijam** [comment]
What @noguerol commented (about timezones) will be implemented (and it is close to be released) in https://github.com/CartoDB/cartodb/issues/12088. Closing this one for the moment 💃 .
