### ISSUE TITLE
Popups do not update for new fields

### ISSUE THREAD

**Issue by mroswell** [CartoDB/cartodb#11997]
### Context
*Please explain here below what you were doing when the issue happened*

I was modifying the HTML of a popup. When I enter in a different field (not originally included in the UI checkoffs), it does not get included in the popup

This issue is different from #11921 (which I'm also still experiencing)

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. us the UI to add fields,
2. switch to HTML mode to customize
3. decide to change a field, i.e. {{not-that-field-this-one}}

The new field (which exists in the dataset) does not display. 

### Current Result
*Please describe here below the current result you got*

The popup windows (whether click or hover) just have a blank spot where the data should be.

### Expected result
*Please describe here below what should be the expected behaviour*
The expected behavior is that if I include {{mydata}} in a template, it displays.

### Browser and version
*What internet browser (Chrome, Firefox, etc) and version was you using and version*
Google Chrome 11921

### .carto file
*Don't forget to rename .carto file to .zip file to be able to upload to github*

### Additional info
*Please add any information of interest here below*

I consider this to be a very significant bug, along with the other two I've reported.
I can resolve by going back to the UI clicking approach, and basically starting over, but it is a big barrier to have to start over each time I want to make a change. In any tool, I'd expect to have access to the full compliment of fields in the template.

**Comment by ztephm** [comment]
Pinging @xavijam b/c this is also happening for Enterprise client S/B 12455959

**STR:**
1. Import [this dataset](https://team.carto.com/u/stephaniemongon/dataset/biking_sheet1_save) & create a map from it.
2. Click on map's layer to open & click on layer's POP-UP tab
3. Choose these settings in POP-UP panel:
![screen shot 2017-05-23 at 2 58 11 pm](https://cloud.githubusercontent.com/assets/1779444/26371293/4fe98528-3fc8-11e7-9473-688662ca8861.png)
4. Set POP-UP toggle to HTML
5. Replace default HTML with this:
    ```html
    <div class="CDB-infowindow CDB-infowindow--dark js-infowindow" style="background:#2E3C43">
      <div class="CDB-infowindow-close js-close"></div>
      <div class="CDB-infowindow-container">
        <div class="CDB-infowindow-bg">
          <div class="CDB-infowindow-inner">
            <ul class="CDB-infowindow-list js-content">
              <li class="CDB-infowindow-listItem">
                <h4 class="CDB-infowindow-title">SLOTS: {{slots}}</h4>
              </li>
            </ul>
          </div>
        </div>
        <div class="CDB-hook">
          <div class="CDB-hook-inner"></div>
        </div>
      </div>
    </div>
    ```

    works: 
    ![screen shot 2017-05-23 at 3 02 51 pm](https://cloud.githubusercontent.com/assets/1779444/26371488/e83bb882-3fc8-11e7-9c91-43c91de0f4cf.png)

6. Duplicate the li & h4 elements and replace text & mustache code with the name of another column in the dataset:
    ```html
    <div class="CDB-infowindow CDB-infowindow--dark js-infowindow" style="background:#2E3C43">
      <div class="CDB-infowindow-close js-close"></div>
      <div class="CDB-infowindow-container">
        <div class="CDB-infowindow-bg">
          <div class="CDB-infowindow-inner">
            <ul class="CDB-infowindow-list js-content">
              <li class="CDB-infowindow-listItem">
                <h4 class="CDB-infowindow-title">SLOTS: {{slots}}</h4>
              </li>
	    	  <li class="CDB-infowindow-listItem">
                <h4 class="CDB-infowindow-title">BIKES: {{bikes}}</h4>
              </li>
            </ul>
          </div>
        </div>
        <div class="CDB-hook">
          <div class="CDB-hook-inner"></div>
        </div>
      </div>
    </div>
    ```
    fails to pull data from second mustache code column:
    ![screen shot 2017-05-23 at 3 03 57 pm](https://cloud.githubusercontent.com/assets/1779444/26371543/0f85f75e-3fc9-11e7-839a-8a27c87ae8f0.png)

**Carto file**

[biking_sheet1 map (on 2017-05-23 at 18.54.42).zip](https://github.com/CartoDB/cartodb/files/1023429/biking_sheet1.map.on.2017-05-23.at.18.54.42.zip)

**Comment by xavijam** [comment]
You need to select the popups you want to show in the popup before using it in the HTML. Go back, select all and then customize the HTML.
