### ISSUE TITLE
Alter Table Add column doesn't get the column to appear in the UI

### ISSUE THREAD

**Issue by mroswell** [CartoDB/cartodb#11995]
### Context
*Please explain here below what you were doing when the issue happened*
alter table map_data
add column map5_t text, 
add column map4_t text, 
add column map3_t text,
add column map2_t text, 
add column map1_t text

I tried again with varchar. the UI doesn't update, as described in the post and comments on #11114   

turns out all 10 fields were there, but I had to manually add a new field to see them. 

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. alter a table to add one or several columns
2. check the dataset. scroll left and right.
3. the new columns do not appear

### Current Result
*Please describe here below the current result you got*

The new columns do not appear by default. I only saw them after manually adding a column via the UI

### Expected result
*Please describe here below what should be the expected behaviour*
I expect that when I refresh the screen after issuing an alter table add column query, that the new columns display. Actually, I don't expect to have the manually refresh the screen, but after refreshing, the new columns still did not appear.

### Browser and version
*What internet browser (Chrome, Firefox, etc) and version was you using and version*

Chrome Version 57.0.2987.133 (64-bit)

### .carto file
*Don't forget to rename .carto file to .zip file to be able to upload to github*

### Additional info
*Please add any information of interest here below*

This bug is of a degree that it makes me lose some confidence in the product. I love carto, and don't want to leave it, but I've been losing a lot of time to bugs like this. Issue #11114 mentioned this, and was already closed, but the problem--at least with adding columns--is still there. Hence this new issue.

**Comment by csobier** [comment]
+1
