### ISSUE TITLE
Add disclaimer saying that legends and widgets will not get exported when exporting an image

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#12009]
### Context
User testing reveals that users try to do image exports in a way that legends fit. This is because they think they will get exported.

### Expected result
Add an infobox disclaimer at the bottom (one of the grey ones) saying something like "Nor legends and widgets will be exported as image".

cc/ @urbanphes @noguerol 

PR: https://github.com/CartoDB/cartodb/pull/12024

**Comment by jorgesancha** [comment]
It should be "Neither legends nor widgets will be exported as part of the image" ...

**Comment by nobuti** [comment]
Deployed.

**Comment by nobuti** [comment]
It seems this wasn't deployed after all. Reopening to deploy on mondays.

**Comment by nobuti** [comment]
Double checkes, it's in production now.
