### ISSUE TITLE
Check table ownership issue on organization creation

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#12008]
Today, we found that the creation of an organization set _some_ of the tables ownership to `postgres` instead of keeping the original role.

I haven't found any related error, and the migration itself is an `alter table ... set schema`, which shouldn't change the ownership at all.

Maybe some triage with possible causes might be worthwile.

cc @CartoDB/builder-backend

**Comment by javitonino** [comment]
Did we know if the owner was correctly set before migrating?

**Comment by juanignaciosl** [comment]
Nope, but maps worked. I think that there's no permission audit/history in PG, isn't it?

**Comment by javitonino** [comment]
Not by default. Some boring reading on that: https://www.crunchydata.com/postgres-stig/PGSQL-STIG-9.5+.pdf
