### ISSUE TITLE
Filter "Group points into polygons" fails

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb#12013]
### Context
Trying to make a concave hull

### Steps to Reproduce
* Any layer
* Add analysis "Group points into polygons"
* Select "Concave Hull"
* categorize by... 
* Percent value <= 98.0

### Current Result
![image](https://cloud.githubusercontent.com/assets/9017165/25136709/0507ed7a-2456-11e7-9cae-20e981328798.png)

### Expected result
The convex hull

### Browser and version
any

### .carto file
not relevant

**Comment by alrocar** [comment]
Stale issue. Closing 👋
