### ISSUE TITLE
Improve race condition handling in Ghost Table Manager

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#12016]
We regularly get race condition while running ghost table in users with lots of tables which run over 10 minutes long: https://github.com/CartoDB/cartodb/issues/12012

My proposed solution in order to avoid this is to add a new method to `Carto::Bolt` to indicate activity, that goes to redis and refreshed the TTL. This can be called after each table operation from ghost tables manager. We could also reduce the TTL a bit. This way:
- We don't need to increase the TTL for bigger users (be it in a fixed amount, or heuristics based on number of tables).
- We get a lower TTL, that will expire if the process is truly stuck, but will keep refreshing if it is doing something (even it it takes a while).

cc @juanignaciosl

**Comment by gonzaloriestra** [comment]
Already fixed.
