### ISSUE TITLE
Wrong size in geometry edition numerical text fields

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#12026]
### Context
When editing a geometry, numerical text fields have a wrong size

### Steps to Reproduce

1. Edit a point in a table with a numerical column

![image](https://cloud.githubusercontent.com/assets/70603/25192431/7010a598-2533-11e7-9c8e-2436276b6685.png)

### Current Result
Those text fields have a wrong width

**Comment by xavijam** [comment]
deployed
