### ISSUE TITLE
Exporting isochrones analysis as SHP exports points, not lines

### ISSUE THREAD

**Issue by fernando-carto** [CartoDB/cartodb#12022]
### Context

* Exporting an isochrones analysis from Builder as an SPH file export only points.

### Steps to Reproduce

1. Create a map with points and add AOI analysis to the layer

![untitled](https://cloud.githubusercontent.com/assets/19906145/25176768/a7c7b9a6-24ff-11e7-9949-0048cc6d789c.png)

2. Export the layer as SHP

![untitled-2](https://cloud.githubusercontent.com/assets/19906145/25176783/b3f73f30-24ff-11e7-93d7-725c875bacd0.png)

3. Import it again to CARTO

![untitled-3](https://cloud.githubusercontent.com/assets/19906145/25176788/ba85e6c6-24ff-11e7-8b52-734b8f46d836.png)

### .carto

* [AOI and shp (on 2017-11-02 at 14.15.09).carto.zip](https://github.com/CartoDB/cartodb/files/1438079/AOI.and.shp.on.2017-11-02.at.14.15.09.carto.zip)

### export files

* Shapefile: [layer_shp.zip](https://github.com/CartoDB/cartodb/files/1438077/layer_shp.zip)
* GeoJSON: [layer_geojson.zip](https://github.com/CartoDB/cartodb/files/1438075/layer_geojson.zip)

**Comment by ramiroaznar** [comment]
@fernando-carto a workaround is downloading it as GeoJSON.

*Do notice that isolines are *polygons*.

**Comment by fernando-carto** [comment]
I know that if I export as GeoJSON it exports the polygons.

What happens? SHP files don't support polygons?

**Comment by amartinj** [comment]
I've followed the steps and when I export and reimport I get the layer imported as a set of polygons:
![image](https://user-images.githubusercontent.com/1821052/32841076-ba18edcc-ca19-11e7-97d7-684b94c7d6e2.png)
The only thing I can come up with is to try and repdroduce it with your map and analysis

**Comment by amartinj** [comment]
We found the issue. For isolines analyses we are keeping two geometries:
- the isoline itself
- the center of the isoline

Due to format restrictions (not 100% sure though), it only accepts one geometry per row and it was getting the center instead of the isoline.

See the related pull request for progress ;)

**Comment by fernando-carto** [comment]
Well spotted guys!

**Comment by amartinj** [comment]
Fixed!
