### ISSUE TITLE
subsample analysis: submit form with same value, makes analysis enqueue

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#12031]
### Context
analysis gets stuck when submitting analysis with same value, this shouldn't be the case as UI is disabled preventing this but there are some ways to do this

### Steps to Reproduce

1. create a map
2. add subsample analysis
3. select 10% > apply (button is disabled)
4. move slider to 20% (button is enabled) > move slider back to 10% (button is still enabled) > apply

### Current Result
analysis is enqueued

### Expected result
analysis should be immediate (or return an error)

![analysis-button](https://cloud.githubusercontent.com/assets/36676/25285011/128f5702-26b9-11e7-9b08-980395f3479d.gif)

/cc @nobuti

**Comment by xavijam** [comment]
I'm not sure this is a Builder related problem, we should check it.

**Comment by matallo** [comment]
it looks like, as reloading fixes the problem, I'd bet it's frontend

**Comment by xavijam** [comment]
Have you checked the polling states? Are CARTO.js sending the proper states?

**Comment by ramiroaznar** [comment]
I was not able to replicate the issue. Is still happening @matallo ?

**Comment by nobuti** [comment]
As far as I can remember, this issue was fixed by @rjimenezda, I think we can close it.
