### ISSUE TITLE
Change pricing for Basemaps in this page: https://carto.com/location-data-services/basemaps

### ISSUE THREAD

**Issue by miguelarias** [CartoDB/cartodb#12033]
### Context

In order to avoid the hassle of selling basemaps to very small customers, we have taken out from our ratecard the sales of basemaps under 12 million/year. Hence we need 2 changes in this paragraph in our website (marked bold for reference):

COMMERCIAL API KEY
Our commercial offering extends the capabilities of the free service with enterprise capabilities. Additionally you will need a commercial API KEY in case of:
**You use the basemap service for commercial purposes.** The basemap is used inside an application or website that requires payment, is private or is used for asset-tracking.
You require a Service Level Agreement on the basemap service. We do not provide any SLA’s on our free offering.
You require more than 75,000 mapviews per month, which is the limit for our free service.
You require a custom map design. On our free service we provide 2 map designs, Dark Matter and Positron for raster.
When you get a commercial license you will get an api_key to attach to your tile requests. Our commercial basemap service starts at **$6000/year** for non asset tracking applications. Contact us to get a quote and discuss different possibilities.

**Where it says $600/year it should state $6,000/year** 

Thanks!

**Comment by xavijam** [comment]
Issue moved to [CartoDB/website #3817](https://github.com/CartoDB/website/issues/3817) via [**ZenHub**](https://www.zenhub.com/)

**Comment by xavijam** [comment]
Moved to website, where it belongs 🤗
