### ISSUE TITLE
CartoGearsApi::Events::UserLoginEvent firing on every login event

### ISSUE THREAD

**Issue by AleGoiko** [CartoDB/cartodb#12034]
subscribed to `CartoGearsApi::Events::UserLoginEvent` and it seems to be firing for every login, not just the first one.

**Comment by juanignaciosl** [comment]
@AleGoiko feature, not bug. There's a `first_login?` method that you can use to check whether it's the first login or not. Triggering a complete login event seemed like a low hanging fruit.

**Comment by AleGoiko** [comment]
Oh perfect! didn't notice that method! thanks! :)
