### ISSUE TITLE
Upgrade to Rails 4

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#12038]
@javitonino has invested several leapfrogs in adding Rails 4 support: #11735 . The sooner we push this forward, the better :psycho:

@javitonino you mention that you "think it should be compatible with Rails 3, can be applied without updating Rails.". Nevertheless, the PR also changes the Gemfile. Do you think that upgrading Rails 4-compatible code and then upgrading to Rails 4 is worthwhile? On one hand, is safer. On the other, it might require hacks and it requires twice the testing effort.

cc @jorgesancha @luisbosque

**Comment by xavijam** [comment]
🎉

**Comment by javitonino** [comment]
I mention a lot of changes that can be done in Rails 3 safely (tagged with `[R3C]` in the listing). Some examples:
- Upgrading some gems (rails-sequel or state-machine) to slightly newer versions so they are compatible with Rails 4, but they are backwards compatible with Rails 3.
- Updating AR scopes. In Rails 3 there are two ways to specify them, but in Rails 4 they deprecated one of them (the one we use, of course)

But there are plenty of changes that need to be updated together:
- The upgrade to Rails 4 gems itself
- Protected attributes and Strong parameters
- Replacing barttssl-requirement with a Rails 4 built-in
- Changes in AR handling of PostgreSQL fields and arrays (remove old compatibility gems, and change the serializers we use)

So, my proposal here would be:
1. Cherry-pick small changesets from the big PR, for those things that are compatible. This allows smaller and focused CRs and acceptances.
2. Once we cannot port anything else, prepare a PR with all the big changes. This will be much smaller than the current one. I think this one will require a comprehensive set of smokes.

**Comment by javitonino** [comment]
Still alive and kicking

**Comment by javitonino** [comment]
This is finally done! :tada:

**Comment by luisbosque** [comment]
VAMOS!

Ey @javitonino maybe we should send a product update or, at least, a comment in slack or something. This is the type of things that are very good from the tech debt and progress perspective and that makes developers especially happy.

**Comment by luisbosque** [comment]
I missed the comm. Great! nothing else to see here :)

**Comment by xavijam** [comment]
That's epic! Congratulations 👏

**Comment by javitonino** [comment]
Thanks @xavijam. You are epic! :heart:
