### ISSUE TITLE
UI Notifications - Markdown italics not rendering

### ISSUE THREAD

**Issue by asimcox** [CartoDB/cartodb#12045]
### Context
*Please explain here below what you were doing when the issue happened*

From Admin Org UI -> Create a notification to all users with markdown text as follows
Try Markdown

After I hit send, the notifications show up with this text as plain text instead of being in Italics. But when I see this notification in my Admin Org UI sent notifications list, it shows in Italics - see image in referenced ticket below.

**Comment by noguerol** [comment]
cc @xavijam

**Comment by nobuti** [comment]
Up and running
