### ISSUE TITLE
Delete organization account in on-premise

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#12049]
An organization owner (and only org owners) can delete the organization account. The UI to delete the organization is equivalent to the delete account one, where it asks for confirmation with password and so on.

- [x] Delete organization account.
- [x] Not available in SaaS.
- [x] Document onpremise smoke test.

cc @xavijam

**Comment by xavijam** [comment]
Available onlly for organization owner or for both, owner and admin?

**Comment by juanignaciosl** [comment]
Only for owners, as "*and only org owners*" says :-)

**Comment by juanignaciosl** [comment]
Consider adding at least the backend side of #11654 so organization can be deleted if a user has shared entities.

**Comment by noguerol** [comment]
So, for addressing the questions we had around this action, I summarize what had been talked offline: we put it in the form of a link in the bottom of the `Organization settings` page, that replicates the aspect and behavior of the `Delete account` link currently at the bottom of `Account` settings but with the following text in the confirmation modal window:

`You are about to delete your organization`
`Remember, once you confirm it there is no going back. Users will not be deleted, but all the organizational settings will be lost. If you want to proceed, type your password:`

**Comment by juanignaciosl** [comment]
In the SaaS this feature will not be available.
