### ISSUE TITLE
Google basemap API signature fail on image export

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#12043]
### Context
Image export on with Google basemaps fails because of missing signature on the API key string.

### Steps to Reproduce

1. Login with an account with GMaps support enabled
2. Try and export an image
3. You'll get this error:
![captura de pantalla 2017-04-24 a las 19 50 26](https://cloud.githubusercontent.com/assets/70603/25351011/63139a42-2927-11e7-9a1a-24856184c9bd.png)

Inspecting network tab:

`The Google Maps API server rejected your request. Unable to authenticate the request. Missing the 'signature' parameter. Learn more: https://developers.google.com/maps/documentation/business/webservices/auth`

Following that link, looks like we need to use the client's private key to generate a signature for each URL

**Comment by nobuti** [comment]
I think this is still valid: https://github.com/CartoDB/support/issues/650#issuecomment-297433048?

**Comment by xavijam** [comment]
We already commented yep, closing it.
