### ISSUE TITLE
UI Notifications distorted pop up

### ISSUE THREAD

**Issue by asimcox** [CartoDB/cartodb#12044]
### Context
*Please explain here below what you were doing when the issue happened*

Showing a weird cut popup on IE browser. See referenced ticket below for more detail and screenshot.

related to #11676

**Comment by AleGoiko** [comment]
looks like this: 
![](https://cloud.githubusercontent.com/assets/25391188/25313690/8ca86e0e-2801-11e7-9ffa-e707dcb48b7b.png)

**Comment by xavijam** [comment]
Added in Builder TODO.

**Comment by nobuti** [comment]
In production.
