### ISSUE TITLE
Admin user actions

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#12048]
Organization admins can, in addition to what normal users can do:

- Create and invite users.
- See existing users. An admin tag beside each admin user should appear in that list.
- Delete non-admin users. Only the owner of the organization can delete admin users.
- Edit users: an admin user can't edit other admin users.
- Manage groups.
- Send notifications.

Note that admins can't change organization details or authentication options.

cc @xavijam

**Comment by xavijam** [comment]
Oooook!

**Comment by juanignaciosl** [comment]
This might contain #12053, but I'm not sure.

**Comment by ivanmalagon** [comment]
Added ticket for documentation update / fixes. https://github.com/CartoDB/docs/issues/1205

**Comment by juanignaciosl** [comment]
Adding @noguerol to acceptance, but another developer should take a look as well.

**Comment by juanignaciosl** [comment]
Added @ivanmalagon as asked by @xavijam .

**Comment by xavijam** [comment]
To be deployed on tuesday gentleman, good job mates! 💃  cc @asimcox
