### ISSUE TITLE
Create user button not correctly disabled

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#12051]
### Context
As an organization owner, the "Create User" button is not correctly disabled. Graphically it is disabled, but you can still click the button:

![screenshot_20170425_132630](https://cloud.githubusercontent.com/assets/7569673/25383126/f4c7e4f0-29ba-11e7-85e4-db6f838c6569.png)

### Steps to Reproduce
1. Set the number of seats of the organization (both builder and viewer) to the current usage
2. Try to create a new user

### Current Result
Button shows as disabled, but is clickable

### Expected result
Button is not clickable

### Browser and version
Chrome and Firefox

P.S: This kind of error keeps popping up in different places. Recently, notifications and image export.

cc @xavijam

**Comment by juanignaciosl** [comment]
I just experienced this while testing #12101.

**Comment by javitonino** [comment]
Still an issue. @ivanmalagon @ramiroaznar for priorization (or not)

**Comment by ramiroaznar** [comment]
LGTM!

**Comment by jesusbotella** [comment]
Deployed! 🚀
