### ISSUE TITLE
We should add another label for organization admin within user list

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#12055]
Basically only in this view (organization > configuration) appears any info about the "owner" of the organization.

<img width="1132" alt="screen shot 2017-04-25 at 16 08 13" src="https://cloud.githubusercontent.com/assets/132146/25389660/81ad522c-29d1-11e7-8ffd-b15a88716e0b.png">

**Comment by saleiva** [comment]
What is that cross on the searchbar? 🗡

**Comment by juanignaciosl** [comment]
This is included in #12048.
