### ISSUE TITLE
Documentation for multiple admin feature

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#12078]
This should be the last task in the milestone.

UI: https://carto.com/docs/carto-enterprise/owners
EUMAPI: https://carto.com/docs/carto-enterprise/enterprise-api

cc @csobier @noguerol

**Comment by csobier** [comment]
Ok, keep me posted on the details. Thanks for giving me a heads up!

**Comment by juanignaciosl** [comment]
Docs changes: CartoDB/docs/pull/1206.
