### ISSUE TITLE
© character in export image attribution

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#12074]
### Context

Attribution in exported image has wrong © character `&copy;`

![untitled map](https://cloud.githubusercontent.com/assets/36676/25536541/8c8aa53e-2c3b-11e7-87ce-c68498bbc29d.png)

### Steps to Reproduce

1. create a map
2. export image

### Current Result

instead of © character, the html code will appear in the attribution

### Expected result

© character should appear properly in the beginning of the attribution

**Comment by alrocar** [comment]
Related to CartoDB/cartodb-bcg#91

**Comment by Jesus89** [comment]
Duplicated: https://github.com/CartoDB/cartodb/issues/13411 and already fixed.
