### ISSUE TITLE
Time-series config time zone enhancements

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#12087]
### Context

This is a ticket for summarizing the time-zone related solutions proposed in https://github.com/CartoDB/cartodb/issues/11970 and in https://github.com/CartoDB/cartodb/issues/11985 for the config view in Time Series widgets.

In short, the changes consist in integrating in the UI a new column type selector between `Time stamp` and `Numeric`.

The first one (`Time stamp`) will enable a

1. **Time-zone drop-down** menu that is **defaulted in the local time-zone** in the column and a
2. **Time-granularity drop-down** menu with aggregations per Minutes, Hours, Days, Months and Years and an `Auto` value that automatically selects the aggregation value . 

The second one (`Numeric`) will enable the `Buckets` slider, that will be otherwise disabled if `Time stamp` is selected. 

According to https://github.com/CartoDB/cartodb/issues/11970 in order to do this we will internally start processing the timeseries column in UTC and the aggregate it depending on the options selected in the new dropdowns. 

cc @CartoDB/design for getting this design ready

**Comment by urbanphes** [comment]
When the user select a specific column (timestamp or numeric) the inputs below will be:
- Timestamp: Time zone + Aggregation
- Numeric: Bucket

Here’s the InVision project:
https://invis.io/A9BKH4DED

**Comment by saleiva** [comment]
About the time-zone customization in the "public view", why don't we simplify the number of options and let viewers to select between the timezone choosen by the creator, or the timezone present in the viewer browser.

I don't see any use case were I'd like to select a different timezone to the one defined by the builder or my browser.

**Comment by noguerol** [comment]
Agreed. https://github.com/CartoDB/cartodb/issues/12088 updated.

**Comment by noguerol** [comment]
Design ready but blocked until we decide wether we have to go with or without the column type selector.

**Comment by saleiva** [comment]
Hi guys, we should promote this to the definitive file. Moving to prototype again

**Comment by urbanphes** [comment]
@saleiva can you review it now?

**Comment by urbanphes** [comment]
Promoted to the main file.
