### ISSUE TITLE
Add unit selector to analysis calculating distances

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#12084]
### Context
Some users are asking to be able to calculate distances in different units (meters or miles) in the connect with lines and the find nearest analysis. (Am I missing something?).

### Current Result
There is no way to know which unit is being used without looking at the specific docs. Also, it's always being calculated in meters, which makes some of our users to have to use excel afterwards.

### Expected result
Having a radiobutton selector as one of the parameters for "m" or "mi" – meters selected by default, would solve both issues. Would give feedback about the unit that is being calculated in, and also provide a way to calculate miles directly.

Since this is directly related to the just released Find closest analysis, I'd consider to make this soone.

cc/ @noguerol @jorgesancha

**Comment by ztephm** [comment]
@CartoDB/support please notify S/B 11562737 when implemented.

**Comment by michellechandra** [comment]
Is the connect with lines analysis result being returned in meters? From [this issue](https://github.com/CartoDB/camshaft/issues/295) it seems sometimes it is returned in different units?

**Comment by saleiva** [comment]
pinging again @noguerol and @kevin-reilly to prioritize!

**Comment by noguerol** [comment]
Not a lot of room right now for this kind of enhancements. Let's wait a couple of weeks.

**Comment by alrocar** [comment]
Stale issue. Closing 👋
