### ISSUE TITLE
Possibility to instrumentate any analysis form for tracking

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#12095]
Feature doc: https://goo.gl/Ot8cU5.

Basically, we should enable the possibility to add the necessary track classes over all components when analysis form is rendered. Also, the "apply" button (in analysis-quota-info) should have the main class there (example below).

![find_nearest_instrumentation](https://cloud.githubusercontent.com/assets/70603/25742865/c999fad2-3191-11e7-8d1d-21a010ae376f.jpg)

cc @nobuti

**Comment by saleiva** [comment]
Hi @noguerol, after the last review done by builder folks, they decided to tall the elements depending on the action and not on the nature of the element (I think that was mentioned in the google doc). Following that "rule" we would have:
- .track-changeTarget
- .track-checkCategorized
- .track-changeCategorized
- .track-changeNofResults

Am I right @xavijam ?

**Comment by xavijam** [comment]
No, we decided to do it like it is described in the design above. In fact, in image-export it is specified like `track-ImageExport track-typePNG` -> https://github.com/CartoDB/cartodb/blob/master/lib/assets/core/javascripts/cartodb3/editor/export-image-pane/export-image-form-model.js#L16.

**Comment by saleiva** [comment]
can you update the document then? I didn't know about that.

**Comment by xavijam** [comment]
We all agree that in (I don't remember where) a ticket. Nothing new, trust me.

**Comment by saleiva** [comment]
But you signed off the document! please, let's update the doc and keep
going.

**Comment by noguerol** [comment]
I've already updated the doc.

**Comment by xavijam** [comment]
Thanks @noguerol. In order to implement this for any analysis, let me change the title, add some description, and link the feature doc. cc @CartoDB/frontend

**Comment by xavijam** [comment]
Could you @noguerol or @saleiva take the acceptance of this?

**Comment by xavijam** [comment]
Already deployed, could you check that it is working as expected @noguerol @saleiva ?

**Comment by saleiva** [comment]
sure!

**Comment by xavijam** [comment]
We should review the document a bit @noguerol, because the classes are:

.track-_name-of-the-analysis-in-camshaft_-analysis: .track-georeference-street-address-analysis
.track-name-of-the-componentComponentType: .track-typeSelect
