### ISSUE TITLE
There's a "Required" label appearing at the top left of the screen

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#12098]
### Context

Whenever I run an analysis and a field prompts a required label, a second label appears at the top of the screen. Then it stays there until I refresh the page but it can also disappear on its own. 

### Steps to Reproduce

1. Add an analysis and find a way to prompt a required label

### Current Result

![sacasc](https://cloud.githubusercontent.com/assets/16247628/25753818/3fc85778-31bd-11e7-95f9-95b7ab4df8c3.gif)

### Expected result

There's should only be one label, to the right of its own field.

**Comment by elenatorro** [comment]
I have made a fix in the tooltip component and added some tests. I have only seen this bug in the "Join columns from 2nd layer" filter.

<img width="1232" alt="captura de pantalla 2018-01-09 a las 16 18 51" src="https://user-images.githubusercontent.com/3824953/34727967-cfd966c2-f558-11e7-9d1e-84cdb793567e.png">

**Comment by ramiroaznar** [comment]
^^ @arianaescobar :tada:

**Comment by arianaescobar** [comment]
Yay!!
