### ISSUE TITLE
Add explanation tooltip to the categorize label on the Find Near analysis

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#12100]
### Context
We've received some feedback about how easy is to understand what categorize does in this analysis.

@AbelVM is going to suggest the text for the tooltip.

**Comment by xavijam** [comment]
Waiting for tooltip description :D.

**Comment by AbelVM** [comment]
What about just swapping "CATEGORIZE" with "PER CATEGORY"?

**Comment by xavijam** [comment]
@saleiva 👍   or  👎 ?

**Comment by saleiva** [comment]
PER CATEGORY is over the limits of characters that the UI supports. Sorry :_(

**Comment by AbelVM** [comment]
PER CLASS

PER TYPE

PER KIND

...

**Comment by saleiva** [comment]
anyway, I do think we should add the explanation text for the tooltip

**Comment by AbelVM** [comment]
> Classify the results so the analysis retrieves N result per category, instead of globally

**Comment by noguerol** [comment]
Let's go for both: we change `Categorize` for `Per group` and we add `Calculate results per each category of the chosen column` for the tooltip.

**Comment by xavijam** [comment]
Roger!

**Comment by ivanmalagon** [comment]
Shipped! :shipit:
