### ISSUE TITLE
Tap on iOS10 mobile embed jumps to page bottom

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#12105]
### Context
One tap over an embed on mobile iOS10 jumps the browser (Safari) until the page bottom. If you scroll back to the embed, the normal double tap zoom interaction works as expected. This is not happening with Editor embeds. 

Comes from: https://github.com/CartoDB/support/issues/660

### Steps to Reproduce

1. Open[ this](http://www.michellechandra.com/lorem/) on iOS10 Safari.
2. Tap on the second embed, generated with Builder

### Current Result
Browser jumps to the bottom

### Expected result
Normal zoom double tap

**Comment by xavijam** [comment]
Moving to its right place.

**Comment by xavijam** [comment]
Issue moved to [CartoDB/cartodb.js #1652](https://github.com/CartoDB/cartodb.js/issues/1652) via [**ZenHub**](https://www.zenhub.com/)
