### ISSUE TITLE
Broken permissions break visualization listing

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#12104]
Today we detected that wrong data around permissions and shared entities break visualization listing. More specifically...

- If `visualization.permission.owner_id` has a id of a nonexisting user, listing those shared entities will crash.
- If a shared visualization has a `user_id` of a nonexisting user, listing those shared entities will crash.

Unless we can grant data integrity, we should have a graceful degradation for those scenarios.

cc @CartoDB/builder-backend

**Comment by juanignaciosl** [comment]
@ramiroaznar just told me that he hasn't been able to reproduce the issue. That's good news because, at least, it's not straightforward to reproduce.

In addition, it _might_ have been caused by _really_ old, corrupted data (he was reusing an old organization).

**Comment by javitonino** [comment]
Also to note, we have done some ugly things to that organization, including manually deleting users from Rails console and so on. So there might be some broken stuff there from previous failed deletions. We have improved this a lot lately and added a bunch of tests, so it is a relief to hear that they cannot reproduce anymore :)

**Comment by ramiroaznar** [comment]
Is this still an issue?
