### ISSUE TITLE
Metadata lacks styling

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#12102]
### Context
Maps metadata apparently lacks CSS styling according to https://github.com/CartoDB/support/issues/684

Related to https://github.com/CartoDB/cartodb/issues/11977

### Steps to Reproduce
After pasting some markdown validation text, the public page correctly layouts the html elements but apparently with no styling:

![captura de pantalla 2017-05-09 a las 16 41 42](https://cloud.githubusercontent.com/assets/70603/25856620/d16e50bc-34d6-11e7-95cc-21b5d2e194cd.png)

**Comment by nobuti** [comment]
I guess we need special styles in order to maintain the visual hierarchy, at least in the case of headings, is that correct @piensaenpixel? Do we have those styles?

**Comment by piensaenpixel** [comment]
After the talk with noguerol, we only should support:

- H... 
- Lists
- Bold
- Italic
- Links

![image](https://cloud.githubusercontent.com/assets/1214201/25993125/4c712f76-3709-11e7-98d7-43b7cf95d3f4.png)

does it sound good?

**Comment by nobuti** [comment]
LGTM, any special treatment in term of font sizes for headings?

**Comment by nobuti** [comment]
All text has 16px, headings too. These are in semibold and have custom color.

**Comment by xavijam** [comment]
This should be in deep-insights. Be careful because that component will be merged in CARTO.js as soon as possible.

**Comment by xavijam** [comment]
Issue moved to [CartoDB/deep-insights.js #542](https://github.com/CartoDB/deep-insights.js/issues/542) via [**ZenHub**](https://www.zenhub.com/)
