### ISSUE TITLE
Widget titles

### ISSUE THREAD

**Issue by erodespons** [CartoDB/cartodb#12112]
### Context
I was playing with a Builder embed...

### Steps to Reproduce
Here: http://residential.jll.co.uk/new-residential-thinking-home/research/bank-of-mum-and-dad-2017/avg-help-per-child-map

### Current Result
And realized that there is no way to see the full title of a widget if its text is longer than the space that the UI allocates to represent it:
![image](https://cloud.githubusercontent.com/assets/7283363/25955733/4e0d9936-366a-11e7-9dd2-376682bfa63e.png)

### Expected result
It would be nice to be able to see the entire text with a hover window or by clicking on the title.

**Comment by xavijam** [comment]
It appears when you hover the title and wait a few seconds...
