### ISSUE TITLE
After adding a Time Series widget, any other type of widget won't appear once added

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#12123]
### Context

If you first add a Time Series widget to a map, and then any other type of widgets, those widgets appear as added on the widget list of the left but the actual widget doesn't appear on the right. You have to refresh the browser for them to appear. 

### Steps to Reproduce

1. Add a Time Series widget without having any other widget added.
2. Add any other type of widget.

### Current Result

![screen shot 2017-05-11 at 18 14 18](https://cloud.githubusercontent.com/assets/16247628/26001541/ffefa8de-372c-11e7-9d3b-8461d9f8838a.png)

### Expected result

Every widget should appear once added, without having to refresh the browser.

**Comment by Jesus89** [comment]
Duplicated: https://github.com/CartoDB/cartodb/issues/12123
