### ISSUE TITLE
Start using CSS GRID

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#12122]
I think we could improve the layout in the layer view using CSS GRID, yesterday i was playing with it a bit, and it's really amazing. Also, the support has improved a lot http://caniuse.com/#search=grid
what do you think?
Maybe i could do a fast test.

@xavijam @matallo @nobuti @ivanmalagon

**Comment by nobuti** [comment]
Count me in!

**Comment by xavijam** [comment]
:+1:

**Comment by piensaenpixel** [comment]
I  did a small test

https://gist.github.com/piensaenpixel/95e27c463854d1c837cdc6c0132a36c
