### ISSUE TITLE
Time Series widget doesn't shrink when switching to any advanced mode

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#12124]
### Context

If you have a map with a time series + any other type of widget and you switch to either the CartoCSS or SQL editor, the interface will move to the right, cutting a piece of the widgets. 

I believe that is related to the time series widget, that won't adjust its size. 

Note: If you resize the browser window, it fixes itself.

### Steps to Reproduce

1. Create a map and add a time series + any other type of widget
2. Open the CartoCSS or SQL editor

### Current Result

![screen shot 2017-05-11 at 18 14 38](https://cloud.githubusercontent.com/assets/16247628/26001843/fb02828c-372d-11e7-88d3-0c61d8bc5e12.png)

**Comment by Jesus89** [comment]
Related to: #12655

**Comment by Jesus89** [comment]
Done with https://github.com/CartoDB/cartodb/issues/12655. So it can be closed
