### ISSUE TITLE
Metadata markdown tag to "Supported markup"

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#12126]
### Context
Related to https://github.com/CartoDB/cartodb/issues/12102 and similar to https://github.com/CartoDB/cartodb/pull/12090 we need to replace the "Markup supported" link to a `Supported markup` tag in map's public view metadata, inside the `Description` text field, as no full markdown is supported but only H1, emphasis and lists. In this case when hovered a `#Headers, *italic*, **bold** and *lists supported` tooltip should appear.

![captura de pantalla 2017-05-12 a las 17 32 24](https://cloud.githubusercontent.com/assets/70603/26005416/37c4ca80-3739-11e7-96d4-6273e84078c4.png)

**Comment by alrocar** [comment]
Stale issue. Closing 👋
