### ISSUE TITLE
Users list endpoint is slower than expected

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#12130]
When you are owner or admin of an organization, and you want to check your users, the first page load takes around 4.9-5 seconds in production to display the first users page. Could it be related to the last changes over multiple-admin feature?

cc @CartoDB/builder-backend

**Comment by juanignaciosl** [comment]
Yep, maybe we can get rid of heaviest data fetching for that request, just like we did with tables one.

**Comment by javitonino** [comment]
Yep. The visualization/table count is being used (and the query looks efficient, a count(*) with indexed filters), but I think we can get rid of the database size which could help.

**Comment by javitonino** [comment]
Tested in production. Loading time down to 1.5s. ~3.5x improvement! It's still a bit slow, and we could further optimize it by using a custom query for the list (that preloads the visualizations counts). But for now, I think this is sufficient.
