### ISSUE TITLE
Redesign how "Your maps" dashboard displays LEARN MORE content

### ISSUE THREAD

**Issue by csobier** [CartoDB/cartodb#12135]
### Context
From _Your maps_ dashboard in CARTO, extra map tiles appear with links to LEARN MORE. The text that appears here auto-rotates and comes from a template. (Yes, I know where to edit this text)

![image](https://cloud.githubusercontent.com/assets/13319925/26110866/86c2fd06-3a21-11e7-97e8-1c259816ef9e.png)

### Current Result
When you click on the LEARN MORE button, a video splash screen appears. 

![image](https://cloud.githubusercontent.com/assets/13319925/26111405/0b5e8bf6-3a23-11e7-8d4f-80f239939470.png)

(Template=https://github.com/CartoDB/cartodb/blob/fca87ab3b7c44529553cd1b059b0eaaa82d55004/lib/assets/javascripts/cartodb/common/map_templates.js)

If you click the back arrow, located from the upper-left hand corner of the splash screen, the following module appears:

![image](https://cloud.githubusercontent.com/assets/13319925/26111029/f8a4ec7c-3a21-11e7-85d8-6d5e7d1e6cb4.png)

### Expected result
We would like to remove the "Create a map with a video tutorial" module, and remove the example video splash screen that appears.

Ideally, we would like to be able to just edit the descriptive text that appears in the map tile, and add a url to a Learn More button - but this may require some redesign of all these templates?

(Template=https://github.com/CartoDB/cartodb/blob/fca87ab3b7c44529553cd1b059b0eaaa82d55004/lib/assets/javascripts/cartodb/dashboard/maps/placeholder_item.jst.ejs)

### Additional info
Let me and @noguerol know if you have any questions.  I have more descriptive images too, if that helps. Related to this [Learn issue](https://github.com/CartoDB/learn/issues/361).

**Comment by noguerol** [comment]
cc @juanignaciosl

**Comment by juanignaciosl** [comment]
We could help if needed, but this is pure frontend cc @xavijam

**Comment by xavijam** [comment]
In short:

- We remove that modal with the videos and so on.
- Those "placeholder" items will be static, so max 2.
- Texts will be provided by christa and they will point to any learn guide we decide.
- If we need to change the icons, @CartoDB/design will provide them.

Be careful with the link to that old modal in the connect-dataset dialog.

**Comment by noguerol** [comment]
Yes, summarizing: 

1. We remove the two modals that come after clicking the button
2. We change the behavior of the button, now points to an specific guide for each map module

@csobier we need to choose the two guides and copywriting for those two modules.
@CartoDB/design we need to figure out what we do with the icon. Either we use the guide's header image in a similar fashion than maps or we choose a single icon for these guide modeules.

**Comment by urbanphes** [comment]
Maybe we can use an icon as a tutorial, learn or something like so.

**Comment by csobier** [comment]
We can test using the following copy and links:
Description: Merge your current dataset with another, existing dataset
Link: https://carto.com/learn/guides/analysis/join-column-from-second-layer

Description: Style your layer based on column values
Link: https://carto.com/learn/guides/styling/style-by-value

**Comment by arianaescobar** [comment]
What if we use the icons we use on Learn right now to represent each category?

![dashboard](https://cloud.githubusercontent.com/assets/16247628/26411696/c94df21c-40a6-11e7-8acd-bb8d85f7d7cf.png)

**Comment by josecruz** [comment]
For me, totally makes sense!

**Comment by arianaescobar** [comment]
Cool, good to go on our end. Ping us if you need anything else from us!

**Comment by xavijam** [comment]
For new hires!

**Comment by rjimenezda** [comment]
@xavijam Should I remove *all* video tutorial functionality? I saw the link on the connect-dataset view, but there's a lot of code around, stuff like embedding a video so you can watch it while using the app & so on.

**Comment by xavijam** [comment]
Yes, burn it.

**Comment by ivanmalagon** [comment]
Shipped! 🚀
