### ISSUE TITLE
Once you open an operators component, you can't edit it anymore

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#12133]
Spotted in this [PR](https://github.com/CartoDB/cartodb/pull/12106), but it is happening right now in production.

## STR
- Create a map of points (with just a few is enough).
- Go to style tab.
- Apply a "squares" style.
- Change the aggregation options and select `operation` by `sum` `cartodb_id`.
- Done that, try to change the aggregation option again.
- Dropdown doesn't appear again.

**Comment by xavijam** [comment]
![screen shot 2017-05-16 at 13 28 56](https://cloud.githubusercontent.com/assets/132146/26103855/a0c97b70-3a3b-11e7-8d9c-7467859ec32f.png)

**Comment by xavijam** [comment]
Deployed!

**Comment by AleGoiko** [comment]
@asimcox i dont think so, it should be on carto staging though
