### ISSUE TITLE
Loading button

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#12132]
We need to implement the new loader button
- Related: https://github.com/CartoDB/design/issues/658

All the code is merged in CartoAssets
https://github.com/CartoDB/CartoAssets/pull/161

If you have any questions ping me :)

**Comment by xavijam** [comment]
Could you enumerate the places where we should start using it?

**Comment by piensaenpixel** [comment]
sure they are here https://github.com/CartoDB/design/issues/658
but this is the list
- [ ] Run analysis.
- [ ] Update the map.
- [ ] Export as an image.
- [ ] Apply CSS.
- [ ] Apply SQL.

**Comment by xavijam** [comment]
Hey @nobuti, I feel we will need a small explanation about how to update cartoassets package and npm-shrinkwrap thing.

**Comment by rubenmoya** [comment]
- [ ] Run analysis.
- [ ] Update the map.
- [x] Export as an image.
- [ ] Apply CSS.
- [ ] Apply SQL.
- [ ] Publish

**Comment by rubenmoya** [comment]
Since we're showing the loading icon, we won't show the "loading", "publishing", "exporting" texts anymore, right?

**Comment by xavijam** [comment]
@piensaenpixel @urbanphes  ^^^ ?

**Comment by piensaenpixel** [comment]
yeah that's right @rubenmoya

**Comment by rubenmoya** [comment]
@piensaenpixel For the run analysis case, should it show the loading indicator as long as the analysis has not finished?

**Comment by nobuti** [comment]
Deployed.

**Comment by xavijam** [comment]
NICE!

On Tue, May 23, 2017 at 15:30, Buti <notifications@github.com> wrote:
Closed #12132 [https://github.com/CartoDB/cartodb/issues/12132] .

**Comment by piensaenpixel** [comment]
\o/
