### ISSUE TITLE
Connect dataset file browser not shown in UI

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#12140]
### Context
Trying to import a file in Builder.

### Steps to Reproduce

1. Log in
2. Click on `Your datasets -> NEW DATASET`
3. Click on `BROWSE` button

### Current Result
Nothing happens.

### Expected result
The file browser is shown.

### Browser and version
```
Google Chrome	58.0.3029.110 (Official Build) (64-bit)
Revision	691bdb490962d4e6ae7f25c6ab1fdd0faaf19cd0-refs/branch-heads/3029@{#830}
OS	Linux
JavaScript	V8 5.8.283.38
Flash	25.0.0.171 /home/rtorre/.config/google-chrome/PepperFlash/25.0.0.171/libpepflashplayer.so
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
Command Line	/usr/bin/google-chrome-stable --flag-switches-begin --flag-switches-end
Executable Path	/opt/google/chrome/google-chrome
Profile Path	/home/rtorre/.config/google-chrome/Default
```

### Additional info
Actually the link is misplaced and the file browser can be shown by clicking on **or**:
![image](https://cloud.githubusercontent.com/assets/1914276/26144614/cf8d1fd0-3ae9-11e7-9fdf-b52944bc7fa4.png)

#SMOKE_DS01

**Comment by xavijam** [comment]
It was fixed 5 days ago, and in production is not happening. If you are suffering in on-premise, I encourage you to merge that PR.

**Comment by jvillarf** [comment]
It's only a few commits ahead of the one we are using. New commit to point at: https://github.com/CartoDB/cartodb/commit/cd0c6ae3560bd2fef72220ea5809a3ca05fa516d

cc @rporres
