### ISSUE TITLE
Dashboard "sync options" modal needs a facelift 💄 (old styles)

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#12145]
### Steps to Reproduce
1. Create a sync from any url (not from data library)
2. Go to the dashboard, dataset listing
3. Click on the sync icon (small circle to the top-right of the geometry type icon)

### Current Result

![screenshot_20170517_155155](https://cloud.githubusercontent.com/assets/7569673/26157168/c8c88886-3b18-11e7-8d2a-3183bb01b034.png)

### Expected result
Something pretty 💖 

cc @xavijam

**Comment by saleiva** [comment]
Argh.

**Comment by xavijam** [comment]
Nah, don't worry, easy peasy.

**Comment by xavijam** [comment]
Uhm... wait a minute, if I click over the icon in the datasets list, it just selects the dataset, it doesn't open any sync options :S.

**Comment by xavijam** [comment]
And I can't reproduce it with Firefox either @javitonino :joy:.

**Comment by javitonino** [comment]
One minute, let me record a gif

**Comment by javitonino** [comment]
![out](https://cloud.githubusercontent.com/assets/7569673/26210660/a263c7c2-3bf0-11e7-8a92-029e9c34f9d7.gif)

**Comment by xavijam** [comment]
Ahh, I was trying to open it with a data-library dataset, 👍 , thanks buddy.

**Comment by javitonino** [comment]
Yeah, I also figured that out (I think I wrote it in the ticket). For some reason, that button doesn't work for data library imports. I guess we blocked it, since data library is a special kind of sync.

**Comment by xavijam** [comment]
Ok, for new hires!

**Comment by xavijam** [comment]
Reopening because those styles are not the correct ones

**Comment by ivanmalagon** [comment]
Shipped! 🚀
