### ISSUE TITLE
The layerDefinitionModel model is not correct when the basemap is google maps

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#12155]
Basically when we build that `layerDefinitionModel` model in the dataset view, we are not taking into account that a basemap could be a GMaps one.

[Context](https://github.com/CartoDB/cartodb/blob/master/lib/assets/core/javascripts/cartodb3/dataset.js#L60-L63):

```js
var layerDataModel = layersCollection.find(function (mdl) {
  var kind = mdl.get('kind');
  return kind !== 'tiled' && kind !== 'plain';
});
```

TrackJS error: https://my.trackjs.com/messages/filtered?hash=f484e536ab6b4d80

**Comment by nobuti** [comment]
Deployed!
