### ISSUE TITLE
When creating an organizational admin user, admin rights are not correctly set

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#12159]
### Context
As an owner, when creating a new organizational admin user, admin rights are not correctly set

### Steps to Reproduce

1. Create a new user
2. Assign admin rights

### Current Result
User is created, but not with admin right, requiring an edit to the user settings.

### Expected result
An admin user is created

cc @kevin-reilly

**Comment by kevin-reilly** [comment]
I was just trying to test this in staging again but I don't see the "admin" option when creating a user for my account anymore.  

I'm looking here: https://kevinsband.carto-staging.com/u/kreilly/organization/users/new

**Comment by javitonino** [comment]
@kevin-reilly that's more or less expected. We have several different servers in staging, and we deploy new functionalities to each of them to test. Most likely, the server where your user is, doesn't have this functionality deployed right now.

If you want to test it, please let us know in #builder so we can prepare a staging server for you with the correct code branch.
