### ISSUE TITLE
Don't allow to add new layer when limit is reached

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#12167]
Everything is explained [here](https://github.com/CartoDB/design/issues/634#issuecomment-284705838), but in any case, let me add an images for context.

![f8cf6dc4-0337-11e7-96f3-9a51d08f711f](https://cloud.githubusercontent.com/assets/132146/26298822/05c9bbba-3ed9-11e7-89b3-d7035c68923f.png)

**Comment by rjimenezda** [comment]
@saleiva 

The infobox shows an 'upgrade your account', but:

- Is it always possible to upgrade? Is there a case where user has reached the total max number of layers we offer (10?)
- Which URL should it load?
- Should it open on the same tab, or on a new one?

**Comment by saleiva** [comment]
I'd always open this type of links in a new tab.
@urbanphes take a look at @rjimenezda questions please!

**Comment by xavijam** [comment]
BTW, several scenarios here:

- If user belongs to an organization -> Offer the possibility to write an email to the organization admin/owner.
- If user is the owner of the org -> email to support in order to upgrade his/her conditions.
- If user is a regular one (free, basic, whatever,...) -> offer the upgrade link.
- If user has a custom install of cartodb -> don't show up the upgrade stuff.

**Comment by saleiva** [comment]
More info at -> https://github.com/CartoDB/cartodb/issues/10689

**Comment by urbanphes** [comment]
@rjimenezda I'm going to try to answer your questions

1. Not always is possible to upgrade the account. For that people and for the case where the limited have been reached we should offer an alternative to contact us. This way we can know the requirements of the user.
2. In the case of "upgrade account" should be load the section inside the dashboard where it is possible to upgrade. In the case of "contact us" should be load the contact form.
3. This kind of situations where the links/button aims outside the tool, always on a new tab. This way never we loosing the focus.

If you have any question, tell me.
