### ISSUE TITLE
Viewer users cannot acces their own maps if marked as private

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#12171]
### Steps to Reproduce
1. As a builder
2. Create a map, make it private
3. Convert your user to viewer
4. Try to open your map (from dashboard)

### Current Result
Map does not exist or is private error

### Expected result
You can view your map.

cc @juanignaciosl

**Comment by mayoral** [comment]
I've tested on both on domainless and domainfull users and orgs, but I can't reproduce the behaviour, it always works as expected: the viewer can see his private map.

Closing this issue, but I'll keep an eye on this.
