### ISSUE TITLE
Review and make an analysis about what is failing within "Filter by value" analysis form

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#12176]
There are several bugs described in [this milestone](https://github.com/CartoDB/cartodb/milestone/142), but we should check if the current implementation could be valid and good for the future or we should redone it.

In my opinion, we should, at least, add those necessary tests we don't have right now. Apart from that, fix those ugly JS bugs we have in some scenenarios. But in any case, a small research and analysis about what should be changed is necessary.

cc @matallo @nobuti

**Comment by saleiva** [comment]
There are also some features missing such as getting the TOP / BOTTOM X results based on a numeric column.

**Comment by matallo** [comment]
I added the missing tests for filter by value in https://github.com/CartoDB/cartodb/pull/12199, but as the implementation is likely to change, they would probably change too

`¯\_(ツ)_/¯`

**Comment by alrocar** [comment]
Stale issue. Closing 👋
