### ISSUE TITLE
Viewer users can change sharing permissions in dataset view but not dashboard

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#12172]
### Context
Testing https://github.com/CartoDB/cartodb/issues/12129 I noticed that viewer users cannot grant/revoke sharing permissions from dashboard. However, they can do it from inside the dataset view.

### Steps to Reproduce
1. Be a builder in an org
2. Create a dataset
3. Convert to viewer
4. Go to the dashboard, try to edit permissions for the dataset, you can't
5. Click the dataset and enter the dataset view, try to edit sharing permissions, you can

### Expected result
Consistent behaviour

cc @juanignaciosl

**Comment by juanignaciosl** [comment]
You shouldn't be able to edit permissions.

**Comment by javitonino** [comment]
Nor privacy?

We should also check the Builder map view, it's probably affected by the same thing as the dataset one.

**Comment by juanignaciosl** [comment]
We're keeping the simplest approach possible for viewer users. IMHO, they're RO, period. Although we allow builders to become viewers, and that adds complexity, as changing permissions is _editing_, they shouldn't be able to.

Pinging @saleiva to confirm.

**Comment by javitonino** [comment]
Now (static dashboard) it's even worse. You can try to edit privacy in both dashboard and dataset views. However, it will fail at backend level (API 403).

cc @ivanmalagon
