### ISSUE TITLE
Time-series UI - Selection texts

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#12179]
Split from https://github.com/CartoDB/cartodb/issues/11588

- Show number of filtered selected items and clear selection options.

![image](https://cloud.githubusercontent.com/assets/1078228/26354386/a50840e8-3fc4-11e7-9501-f22d4d26e40b.png)

**Comment by ivanmalagon** [comment]
Blocked until https://github.com/CartoDB/cartodb/issues/12177 is finished. I'm doing major changes to the widget and it's better to wait until it's done to continue working on it.

**Comment by xavijam** [comment]
Deployed
