### ISSUE TITLE
Graphs for "Filter by column" analysis are not working

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#12175]
Apart from those graphs are not appearing anymore, we should redo that work because all the logic for rendering that graph is placed in the `analysis-form-view`, and it should not be there.

In my opinion, that graph should be a different Backbone.Form editor component, and it should be rendered when the column attribute has changed.

![example](https://cloud.githubusercontent.com/assets/14546701/16919322/7ab25f08-4d09-11e6-979a-dc3b94624a0b.png)

**Comment by alrocar** [comment]
Stale issue. Closing 👋
