### ISSUE TITLE
Time-series UI - Add widget title

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#12178]
Split from https://github.com/CartoDB/cartodb/issues/11588

**Widget title**

- Add widget title: now in some cases there is no title at all.
- Show play / pause button always in the torque subtype, besides the histogram.

**Out of scope**
- The selection tags above range filter are out of scope on this ticket. That work is in https://github.com/CartoDB/cartodb/issues/12291
- The node information has an already open issue to tackle it. https://github.com/CartoDB/cartodb/issues/9956 It has to be developed for all widgets, not only this one.

![image](https://cloud.githubusercontent.com/assets/1078228/26354337/7cce6990-3fc4-11e7-836e-62ce5bb11cf6.png)

**Comment by ivanmalagon** [comment]
Blocked until https://github.com/CartoDB/cartodb/issues/12177 is finished. I'm doing major changes to the widget and it's better to wait until it's done to continue working on it.

**Comment by rjimenezda** [comment]
I am sort of doing this on #12291 since I needed the space for the tooltips in any case.
