### ISSUE TITLE
Time-series UI - Add context menu

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#12177]
Split from https://github.com/CartoDB/cartodb/issues/11588

**CONTEXT MENU**

Add context menu to time-series widget. The options that we should show are:
- Show totals: in the same way that it does in the histogram widget, it should show the total values in gray bars and normalizes the height of the yellow ones.
- Edit
- Delete

**Comment by kevin-reilly** [comment]
Please let me know when these enhancements are available on staging and how I might access them.  Thanks.

**Comment by ivanmalagon** [comment]
Just sent you a mail with the steps to enter staging, @kevin-reilly

**Comment by nobuti** [comment]
Deployed.
