### ISSUE TITLE
columnType is null when loading the page, because columnsCollection is not available

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#12188]
### Context
when having a filter analysis, and trying to change the type it uses the `columnType` to format the schema. `columnType` is `null` when loading the page, because `columnsCollection` is not available at that moment

### Steps to Reproduce
1. add filter by value analysis (type: category)
1. reload
1. change column (type: boolean)

### Current Result
min and max fields appear and it throws a js error with a failed sql request

### Expected result
shcema should be set properly for boolean column

**Comment by alrocar** [comment]
Stale issue. Closing 👋
