### ISSUE TITLE
Unify Scrollbars

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#12184]
### Context
Original issue: https://github.com/CartoDB/design/issues/660
The design team found different versions of the scrollbars so basically we wanted to unify them all to keep the consistency between them and also enhance the usability of it.

We made changes and different behaviours to horizontal and vertical scrolls changing its position and, in vertical scrolls, the interaction:

#### Behaviour changes
- When clicking on the arrows, items will pass one by one.
- Size will not change on hover (it's going to change only on vertical scrolls)
- Hovering the arrows will change its colors to a darker one.
![](https://cloud.githubusercontent.com/assets/596509/26316208/c55677c2-3f13-11e7-95db-29e2b5c6e861.png)

#### Behaviour changes
- When hovering the scrollbar, it'll increase its size to 8px (this is to make it easily clickable)
- Sitcked on the borders.

![](https://cloud.githubusercontent.com/assets/596509/26315803/93a5358e-3f12-11e7-9c25-6a8b4f407093.png)
![embed-640x520-04-legend-big](https://cloud.githubusercontent.com/assets/596509/26366651/297b963c-3fec-11e7-8ee1-3636ef510ef9.png)
(note: that's actually a horizontal scroll but will behave the same way as verticals does)

### Components test:
We did a small test on few of our components, here you have how it will look like (let me know if you need anything more):
![artboard copy](https://cloud.githubusercontent.com/assets/596509/26366721/67974934-3fec-11e7-942f-29b2416cfdca.png)

**Comment by xavijam** [comment]
First of all, agree to unify the scrollbars, superb idea. But I have to say that I'm not a good friend of the horizontal arrows, but it is true we can improve the thumbnails slider, could we try something @saleiva suggested (if someone scroll, horizontal or vertical, it moves the slider) instead of adding that?.

Another thing, I'm a really big fan of the new popup/infowindow scroll, it is super nice. Could we keep it? 😸

**Comment by noguerol** [comment]
Birras on me if you add a scroll wheel event for horizontal scrollbars.

**Comment by josecruz** [comment]
+1000 to scrolling vertically and move the slider horizontally. @CartoDB/design what do you think about keep the current scrollbars on the popups?

**Comment by urbanphes** [comment]
But instead of keeping the current horizontal scroll bars for the carousel we can test with the new design more square, removing the arrows. not¿? It would be the same behavior that the vertical scroll bars.

**Comment by noguerol** [comment]
@CartoDB/design is this design ready?

**Comment by josecruz** [comment]
@noguerol yes, as talked before the only change will be the arrows that will be removed on horizontal scroll (for now)

![image](https://user-images.githubusercontent.com/596509/30379954-73fdf2ae-9898-11e7-8cc8-105db175e19a.png)

**Comment by Jesus89** [comment]
I take this one. What about the scrollbar on the popups?

**Comment by noguerol** [comment]
They're also included on the original mockups. What is concerning you?

**Comment by Jesus89** [comment]
Just the @xavijam comment about popup scroll

**Comment by josecruz** [comment]
@Jesus89 Yep, as talked yesterday with @piensaenpixel we agreed to change them as well due the goal of the ticket was to unify them (sooorry @xavijam)

**Comment by Jesus89** [comment]
I have seen that the cursors are different in each scroll. @CartoDB/design what is the proposal for that?

**Comment by josecruz** [comment]
@Jesus89 I'd use always the default one. Just as macOS does

**Comment by Jesus89** [comment]
Thanks @josecruz. Btw, what is the design for the scroll in the COLOR and IMAGE popups?

**Comment by Jesus89** [comment]
Please, check here the final result: https://github.com/CartoDB/cartodb/pull/12877

**Comment by Jesus89** [comment]
Deployed in ded10

**Comment by nobuti** [comment]
In production.
