### ISSUE TITLE
Big circle loader is not in a correct place

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#12183]
![bad-thing](https://cloud.githubusercontent.com/assets/132146/26361191/857eef7c-3fda-11e7-9788-1c032ead3d01.png)

Have we changed something about that recently in CartoAssets?
cc @piensaenpixel @CartoDB/frontend

**Comment by nobuti** [comment]
For new hires.

**Comment by xavijam** [comment]
Added in another ticket with other small UI fixes. https://github.com/CartoDB/cartodb/issues/12227
