### ISSUE TITLE
Time-series UI - Draggable changes

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#12180]
Split from https://github.com/CartoDB/cartodb/issues/11588

  - Add 1px white border to the scrub bar (the needle)
  - One click on the histogram should move the visualization to that point in time.
  - If dragged, instead of moving the scrub bar a selection is triggered.
  - If a selection is active, clicking inside the selection should make it draggable.

**Comment by ivanmalagon** [comment]
Blocked until https://github.com/CartoDB/cartodb/issues/12177 is finished. I'm doing major changes to the widget and it's better to wait until it's done to continue working on it.

**Comment by nobuti** [comment]
Changing this by DO. Whoever pick this I made some work on `12180-timeseries-draggable` branch. Only second point is pending.

**Comment by matallo** [comment]
carried on `12180-timeseries-draggable--12291-range-filter-tags` branch, thanks @nobuti @rjimenezda !

**Comment by rjimenezda** [comment]
This issue is a superset of: #11649

**Comment by rjimenezda** [comment]
Back 2 development, forgot the tests

**Comment by xavijam** [comment]
Deployed mates! 👏
