### ISSUE TITLE
SMOKE_OB07 On boarding not working in layers

### ISSUE THREAD

**Issue by rubenmoya** [CartoDB/cartodb#12192]
### Context
The on boarding of data and style inside layers is only showing step 1, when you click on "Next" it closes the on boarding.

### Steps to Reproduce
1. Create a new layer with a dataset (or without dataset and add a geometry)
2. Enter in the layer, it should open the on boarding of the style tab
3. Click "Take the tour"
4. Click "Next"

### Current Result
It closes the on boarding

### Expected result
It shows step 2 of the on boarding

### Browser and version
Google Chrome Version 58.0.3029.110 (64-bit)

**Comment by xavijam** [comment]
If you use the arrows, it works.

**Comment by xavijam** [comment]
For new hires ;).
