### ISSUE TITLE
SMOKE_DS03 contact-us link not appearing when being close to the limits

### ISSUE THREAD

**Issue by rubenmoya** [CartoDB/cartodb#12196]
### Context
When the user is close to the limits a contact-us message should appear

### Current Result
There is no contact-us message
![screen shot 2017-05-24 at 16 53 52](https://cloud.githubusercontent.com/assets/905225/26409802/e4b0e816-40a1-11e7-80bf-e75f00e3d04f.png)

### Expected result
A contact-us message is shown

### Browser and version
Google Chrome Version 58.0.3029.110 (64-bit)

**Comment by xavijam** [comment]
Well, I feel there is no upgrade message in that component. But it could be there, yeah.
