### ISSUE TITLE
Google geocoder clientID/privateKey not saved in redis

### ISSUE THREAD

**Issue by jvillarf** [CartoDB/cartodb#12197]
## Description

**Product:** ```onpremises-2.1.0```

Enabling google **ClientID and PrivateKey** using ```google services rake``` (https://github.com/CartoDB/cartodb/blob/master/lib/tasks/google_services.rake#L72) is using a **read model**, that ends up not updating the suitable **redis key values**.

### How to reproduce it

1- Use the rake task to set a pair of keys **ClientID/PrivateKey**
```` bash
carto_rake "cartodb:services:external:google:enable_for_organization[test_client,test_key,organization]"
````
2- Check redis keys
```` bash
# redis-cli -n 5 hgetall rails:orgs:organization
 1) "id"
 2) "ec7e2f18-4422-40ad-a225-daea35932e5a"
 3) "geocoding_quota"
 4) "400000"
 5) "here_isolines_quota"
 6) "20000"
 7) "obs_snapshot_quota"
 8) "400000"
 9) "obs_general_quota"
10) "999999999"
11) "mapzen_routing_quota"
12) "20000"
13) "google_maps_client_id"
14) "client=test_client"
15) "google_maps_api_key"
16) "test_key"
17) "period_end_date"
18) "2017-05-24 08:22:40 +0000"
19) "geocoder_provider"
20) "google"
21) "isolines_provider"
22) ""
23) "routing_provider"
24) ""
````
3- Use the same rake to update the Privatekey
```` bash
carto_rake "cartodb:services:external:google:enable_for_organization[test_client,test_key_2,organization]"
````
4- check redis keys
```` bash
# redis-cli -n 5 hgetall rails:orgs:organization
 1) "id"
 2) "ec7e2f18-4422-40ad-a225-daea35932e5a"
 3) "geocoding_quota"
 4) "400000"
 5) "here_isolines_quota"
 6) "20000"
 7) "obs_snapshot_quota"
 8) "400000"
 9) "obs_general_quota"
10) "999999999"
11) "mapzen_routing_quota"
12) "20000"
13) "google_maps_client_id"
14) "client=test_client"
15) "google_maps_api_key"
16) "test_key"
17) "period_end_date"
18) "2017-05-24 08:22:40 +0000"
19) "geocoder_provider"
20) "google"
21) "isolines_provider"
22) ""
23) "routing_provider"
24) ""
````

**Redis key** ```google_maps_api_key``` is not updated at all.

@ethervoid is aware of this issue and how to tackle it.

This issue is currently blocking the **onpremise 2.1.0** release.

Thanks a lot.

#OSERV17

**Comment by ethervoid** [comment]
We're using the `read models` in this rake and we should use the `write` models. For example [here](https://github.com/CartoDB/cartodb/blob/master/lib/tasks/google_services.rake#L76)

// @juanignaciosl

**Comment by juanignaciosl** [comment]
Good catch. FYI, finishing the model refactor is our 1st priority, so this can't happen in the future. Scheduled in TODO.
