### ISSUE TITLE
Widgets, legend and popups are not working after publishing the map with less than 100k features

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#12202]
Performing smoke tests #MG47

Map is correctly working at Builder private side, but in the embed is not rendering anything, just the points and the color is not correct. Images below, link available in the account provided for the smoke tests under "Jamón's map, don't touch it".

<img width="1280" alt="screen shot 2017-05-24 at 19 24 58" src="https://cloud.githubusercontent.com/assets/132146/26416607/ca2c1a50-40b6-11e7-8788-66248106445b.png">
<img width="1280" alt="screen shot 2017-05-24 at 19 25 03" src="https://cloud.githubusercontent.com/assets/132146/26416608/ca364250-40b6-11e7-910a-a3faaa71841a.png">

**Comment by donflopez** [comment]
I tried to reproduce and It's working for me. Can you show it to me @xavijam?

Thank you!

**Comment by xavijam** [comment]
Well, after taking a look with you, we haven't suffered again, so closing it!
