### ISSUE TITLE
analysis filter by value: replace text/selector editor in boolean field with boolean editor

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#12200]
### Context
when applying a filter by column value analysis, we should show a Boolean editor for boolean columns, instead of a Selector editor

### Steps to Reproduce
1. create a map
1. add filter by column value analysis
1. select a boolean column
1. click on input

### Current Result
1. a Selector editor appears

![screen shot 2017-05-24 at 19 04 43](https://cloud.githubusercontent.com/assets/36676/26415941/86b03b96-40b4-11e7-8204-69c4f75cde16.png)

### Expected result
1. a Boolean editor should appear

![screen shot 2017-05-22 at 18 36 40](https://cloud.githubusercontent.com/assets/36676/26415930/7e42ca46-40b4-11e7-9adb-4947c7272d32.png)

**Comment by alrocar** [comment]
Stale issue. Closing 👋
