### ISSUE TITLE
analysis filter by column value: add null to results in accept/reject analysis

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#12201]
### Context
null values aren't being taken into account when filtering by true/false, also you can't accept nor reject null values

### Steps to Reproduce
1. add filter by column value analysis
1. select a boolean column
1. click on input field

### Current Result
1. null is missing from the options for the editors, only true and false appear, this should be done along with https://github.com/CartoDB/cartodb/issues/12200

### Expected result
1. it should be possible to select null as the value to filter

also, if you choose any of the rest of the options, the results won't include rows with null values

**Comment by alrocar** [comment]
Stale issue. Closing 👋
