### ISSUE TITLE
SMOKE_MG26 - Error in Aggregate points per admin regions

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#12208]
### Context
Aggregate points per admin regions and change aggregation method and ramp doesn't work

![46f74cc4-4145-11e7-8150-7b1f73f57665](https://cloud.githubusercontent.com/assets/132146/26587938/2374223c-4554-11e7-8464-961c2647563f.png)

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Create a map
2. Add populated places
3. change aggregation method to admin regions

**Comment by josecruz** [comment]
It also happened the same to me in for Squares Aggr. method but refreshed and couldn't replicate it again.

**Comment by xavijam** [comment]
I've tested in production and it works with datasets/nodes with not so many points (325 in this case). But if you try with more it fails.

![screen shot 2017-05-30 at 16 17 58](https://cloud.githubusercontent.com/assets/132146/26587822/be3e11de-4553-11e7-951f-c6381ce5d25d.png)
![screen shot 2017-05-30 at 16 18 12](https://cloud.githubusercontent.com/assets/132146/26587825/bf60a98c-4553-11e7-9d92-041e319a3b7d.png)

**Comment by rafatower** [comment]
I'd say it may be a timeout in the query but don't know much about the inner workings of that

**Comment by ethervoid** [comment]
This part relay in FDW to connect to the aggregation tables of the dataservices_db. In which server are we testing this Smokes? staging cloud? user?

**Comment by ethervoid** [comment]
Ping @piensaenpixel

**Comment by ethervoid** [comment]
Fixed, was a configuration problem
