### ISSUE TITLE
Organization deletion triggers errors in notification code

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#12204]
You get a bunch of Rollbar warnings about sending visualization-unshared notifications ([1](https://rollbar.com/vizzuality/CartoDB/items/23107/), [2](https://rollbar.com/vizzuality/CartoDB/items/23109/), [3](https://rollbar.com/vizzuality/CartoDB/items/23110/)). It would be nice to reduce this noise, but it's not very important as it doesn't break the flow.

### Steps to Reproduce
1. Create a organization with a couple of users
2. Import and share datasets and maps between the two accounts
3. Delete the organization

**Comment by javitonino** [comment]
cc @juanignaciosl (I just realised that you wanted to be pinged in order to prioritize this)

**Comment by ramiroaznar** [comment]
Ey @ethervoid we fixed this with https://github.com/CartoDB/cartodb/pull/13136 right?

**Comment by ethervoid** [comment]
Nope, could be related but they're different issues
