### ISSUE TITLE
[OBS] Boundaries query templates need parenthesis fix

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#12206]
While resolving some questions about OBS functions and integration we found out an issue with one of the query templates. These templates with the `OR` clause:

https://github.com/CartoDB/cartodb/blob/d8614f137cab6980a9fe8fd18f5d6a833ec98a66/lib/assets/core/javascripts/cartodb3/data/data-observatory/boundaries-collection.js#L5-L11

shall include parenthesis to enforce the correct precedence:
```sql
SELECT * FROM OBS_GetAvailableGeometries(
  ST_MakeEnvelope(-74, 41, -73, 40, 4326),
  NULL,
  <numer_id>,
  <denom_id>, 
  <timespan_id>
) denoms
WHERE valid_numer IS TRUE
 AND (valid_denom IS TRUE OR <denom_id> IS NULL) -- edited
 AND valid_timespan IS TRUE
```
as explained in https://github.com/CartoDB/dataservices-api/issues/370#issuecomment-303959407

**Comment by nobuti** [comment]
Something weird happens, if I include the parenthesis, the request returns an empty rows array. It seems to work without them.

**Comment by rafatower** [comment]
Sorry, I misplaced the parenthesis. My bad.

Instead of
```
(AND valid_denom IS TRUE OR <denom_id> IS NULL)
```

it should read
```
AND (valid_denom IS TRUE OR <denom_id> IS NULL)
```

Fixed in the description.

I corrected it. Also noticed the construct `AND (valid_denom IS TRUE OR <denom_id>)` is to be used (with parenthesis as well), to get timespans: https://gist.github.com/talos/554c7759bafe53faafd23a9711305220#timespan

Could you please apply those and check if that works as is meant?

Sorry again for my mistake.

**Comment by nobuti** [comment]
No, it's not that, I fixed the parenthesis. This query:
```
SELECT * FROM OBS_GetAvailableGeometries((SELECT ST_SetSRID(ST_Extent(the_geom), 4326) FROM (<%- query %>) q), NULL, {{{ measurement }}}, {{{ normalize }}}, {{{ timespan }}}) denoms WHERE valid_numer IS TRUE AND (valid_denom IS TRUE OR {{{ normalize }}} IS NULL) AND valid_timespan IS TRUE ORDER BY numgeoms DESC
```
doesn't return any result, but without parenthesis it works. However I can't see any problem for timespans. Insane.

**Comment by rafatower** [comment]
Okay, let me check it with @talos and I'll get back to you. This week I'm meeting him in person a couple times so we can check it.

FTM leave it without parenthesis and let's keep this ticket open.

**Comment by nobuti** [comment]
👍

**Comment by rafatower** [comment]
wait! it is not `OR {{{ normalize }}} IS NULL` but `OR {{{ denom_id }}} IS NULL` or whatever name you used for that var in the template

**Comment by nobuti** [comment]
Yes, internally `denom_id` is `normalize` :)

**Comment by rafatower** [comment]
After second thought, I think what's happening is the following: `{{{ denom_id }}}` may be evaluated to the empty string or to the string `"NULL"`, which is not null and evaluates everything to false, producing an empty set.

One possibility to fix it would be to completely remove the AND clause related to `denom_id` if we don't pass a specific one. What do you think, @nobuti ?

**Comment by rafatower** [comment]
Got confirmation on the parenthesis usage. Actually other params should have that guard as well when they are null. E.g: `AND (valid_timespan IS TRUE or timespan IS NULL)`.

**Comment by nobuti** [comment]
Ok, I'll remove that part of the query if not value, but it worries me that the other query it works, with the same logic.

**Comment by nobuti** [comment]
Here are the queries fixed, I've been testing them and it seems they work, could you take a look?
https://github.com/CartoDB/cartodb/blob/f3b45e02dbb7dbf725169e592ae12248b4b5729f/lib/assets/core/javascripts/cartodb3/data/data-observatory/boundaries-collection.js#L5-L43
https://github.com/CartoDB/cartodb/blob/f3b45e02dbb7dbf725169e592ae12248b4b5729f/lib/assets/core/javascripts/cartodb3/data/data-observatory/boundaries-collection.js#L5-L43

Let me know if you see something wrong.

**Comment by rafatower** [comment]
:+1: They look fine to me. There's some room for improvement (I'm thinking about wrapping up some of that logic in lower layers) but for the moment they will do the trick :clap: :clap:

**Comment by xavijam** [comment]
Could we close this then?
