### ISSUE TITLE
Time-series widget glitch on IE 11

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#12217]
@ernesmb commented on [Thu May 25 2017](https://github.com/CartoDB/support/issues/726)

### Context

Time-series widget doesn't show the bars correctly on IE 11. 

### Steps to Reproduce

1. Add a Time-Series widget to the map 
2. See the bars doesn't fill all the horizontal space
3. Change browser zoom level to check it's not being rendered well

### Current Result

![screen shot 2017-05-25 at 17 13 00](https://cloud.githubusercontent.com/assets/10940006/26457312/faf2227e-416f-11e7-92f4-3c9328ef7e3f.png)
 
### Expected result

![screen shot 2017-05-25 at 17 31 56](https://cloud.githubusercontent.com/assets/10940006/26457332/13b5da4e-4170-11e7-9747-facb9a9d7934.png)

### Browser and version

Internet Explorer 11 on a Windows7 virtual machine

**Comment by nobuti** [comment]
@ernesmb I can't reproduce it, do you have a .carto?

**Comment by ernesmb** [comment]
hey @nobuti I just tried with IE11 on a Windows7 VM and got this: 

with browser's zoom at 75%: 

![screen shot 2017-09-13 at 12 36 12](https://user-images.githubusercontent.com/10940006/30373114-83d0ec08-9880-11e7-8c4f-781eb8456e57.png)


zoom at 100% 

![screen shot 2017-09-13 at 12 36 30](https://user-images.githubusercontent.com/10940006/30373122-8a6cec1a-9880-11e7-8521-83ea5b590b4f.png)


zoom at 125%

![screen shot 2017-09-13 at 12 36 41](https://user-images.githubusercontent.com/10940006/30373131-91741d76-9880-11e7-9d78-365c381ffc86.png)


Testing with Chrome on my Mac, I got similar glitches, but only with zoom != 100% 

This is the zipped .carto file of the map I was trying with, but I believe that any other one will do 

[IE11_timeseries_glitch (on 2017-09-13 at 10.39.31).carto.zip](https://github.com/CartoDB/cartodb/files/1299130/IE11_timeseries_glitch.on.2017-09-13.at.10.39.31.carto.zip)

**Comment by nobuti** [comment]
Changing the `shape-rendering` style fixes all the issues in chrome, safari and firefox. But not in ie11. It's weird because "it seems" the histogram is rendered with `crispEdges` in IE. I'll keep investigating.

**Comment by ivanmalagon** [comment]
Shipped! 🚀
