### ISSUE TITLE
Blending mode not affecting to Stroke

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#12211]
### Context
*Please explain here below what you were doing when the issue happened*

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Go to layer style
2. Add a fill color
3. Add a 4px or more stroke (to properly see it)
4. Change Blending mode to overlay
5. See how it's not affecting to the stroke

### Current Result
https://www.dropbox.com/s/0swe9lk7ohw5qm2/Kapture%202017-05-25%20at%2015.03.28.gif?dl=0
(too big for GH 😞 )

### Expected result
Comp-op affecting to line + fill

### Additional info
SMOKE_MG17

**Comment by xavijam** [comment]
That's a "problem" in the Maps API (windshaft repository), not here.

**Comment by xavijam** [comment]
Issue moved to [CartoDB/Windshaft-cartodb #692](https://github.com/CartoDB/Windshaft-cartodb/issues/692) via [**ZenHub**](https://www.zenhub.com/)
