### ISSUE TITLE
Upgrade CTA when user is close to the limits is not placed correctly

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#12220]
Failing in any page, profile, account, api-keys, ...

![screen shot 2017-05-26 at 11 53 23](https://cloud.githubusercontent.com/assets/132146/26490042/05e02862-420a-11e7-8a5e-0c2c9d716111.png)

**Comment by xavijam** [comment]
Being fixed in https://github.com/CartoDB/cartodb/pull/12174/commits/8b9d08d7c16c38471903ce316687d1e709eb075c.

**Comment by javitonino** [comment]
Uhm... that staging user... 👮
