### ISSUE TITLE
org_admin missing parameter keeps null value

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#12229]
### Steps to Reproduce

1. Create a user with EUMAPI without `org_admin` parameter. Try again, with `false`.

### Current Result

- Returns `null` for `org_admin`.

### Expected result

- Should return and set `false`. 

### Additional info

- Check that all the new CartoDB/docs/pull/1206 documentation is consistent with EUMAPI logic.
- Check PUTs as well.

**Comment by juanignaciosl** [comment]
cc @jorgesancha @jvillarf 

This is _really_ minor. As it's not documented yet, I wouldn't worry about it for onpremise release.

**Comment by javitonino** [comment]
We have the exact same behaviour with `viewer`. Will take a look at fixing that as well.

**Comment by jvillarf** [comment]
Yes, i'd say we don't have to include it in this Onpremise release, but thanks for the warning :)

**Comment by rubenmoya** [comment]
I tried creating and updating users with `org_admin` and `viewer` with 3 cases: `empty`, `null` and `false`.

In all cases the response was false, so it looks good to me! 🙌
