### ISSUE TITLE
Removing an organization redirects to the 404 error page.

### ISSUE THREAD

**Issue by skgsergio** [CartoDB/cartodb#12226]
### Context
When an org admin removes its org he gets redirected to the logout and then to the 404 error page.

This is probably due the logout process redirect the user to its (non existent) public page.

This issue is non blocking for the release.

### Steps to Reproduce
1. Login with the organization admin user.
2. Go to the organization settings.
3. Click the "delete organization" link.

### Current Result
After the org and users deletion the user gets redirected to the 404 error page.

### Expected result
The user should get redirected elsewhere, for example to the login page.

### Browser and version
Chrome Version 58.0.3029.110 (64-bit)
Onpremises 2.1.0-pre5: https://github.com/CartoDB/cartodb/tree/4.1.0.1

**Comment by javitonino** [comment]
cc @juanignaciosl (not a blocker, normal priority)

Redirection is: `DELETE organization -> /logout -> 404`

**Comment by juanignaciosl** [comment]
It also happens from time to time with user deletion.
