### ISSUE TITLE
Filtering with widget config panel visible makes the panel to dissapear

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#12239]
### Steps to Reproduce

https://fsty.io/v/dXR5KY

### Current Result
The widget panel config dissapears when filtering using the widget.

**Comment by nobuti** [comment]
I can't reproduce it following the same steps. I see the user has some console errors, I feel something else is going on here.

**Comment by saleiva** [comment]
Closing until we can reproducce it @noguerol
