### ISSUE TITLE
Support aggregations on time-series

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#12241]
### Context
There is a common need on time-series (coming from this issue https://github.com/CartoDB/cartodb/issues/10809) on not only counting a number of features but to aggregate a numeric column. Before doing so in the histogram, we should start with the time-series widget.

In the UI we would just have the same aggregation UI that we have in the analysis nodes (such as the intersect points in polygons)

More information in the original issue https://github.com/CartoDB/cartodb/issues/10809

**Comment by noguerol** [comment]
@rochoa does this requires from your team's time?

**Comment by rochoa** [comment]
Yes. Don't forget about https://github.com/CartoDB/cartodb/issues/10809#issuecomment-263947026.

**Comment by rochoa** [comment]
Questions:

 - Do we want to support it for histograms associated with date columns (aka time-series) or for all histograms?
 - The aggregation (avg, sum, min, max, count) is over any other numeric column in the dataset, and not over the column that we are computing the bins for, right?

**Comment by noguerol** [comment]
@rochoa any blockers here?

**Comment by rochoa** [comment]
Just my two questions in the previous comment.

**Comment by noguerol** [comment]
haha, my bad, I didn't read those 🎉 

1. Only time-series for the moment
2. Being only time series I understand we are making those operations over the temporal bins selected by the user, right @stuartlynn ?

**Comment by alrocar** [comment]
Stale issue. Closing 👋
