### ISSUE TITLE
Replace jquery-ui use in Builder

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#12247]
We are using a super old version of jquery-ui, in fact it is not provided from npm source. Apart from that, it is being added "magically" to our editor3 bundle, and that's not good. IMHO we should get rid of it and start using other alternatives.

Bad things are:
- Tag-it plugin needs it in order to work properly, so we will need to replace it by another dependency (https://bevacqua.github.io/insignia/, https://github.com/developit/tags-input - by @nobuti).
- We make use of the slider, although we are replacing it right now thanks to @nobuti work in DO update.
- We use the `sortable` and `draggable` options in several places (like reorder layers, or create a new layer from a node), so we will need to find a replace for that (https://bevacqua.github.io/dragula/).

cc @CartoDB/frontend

**Comment by nobuti** [comment]
For the drag and drop we can use https://bevacqua.github.io/dragula/

**Comment by xavijam** [comment]
I remember to try it without luck, but I feel it was due to the context, not about the plugin.
