### ISSUE TITLE
Optimize speed for the squares/hexbins aggregations

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#12244]
### Context
Very often it takes a while to aggregate points data into grids or hexbins. Sometimes it gets so slow that it looks like something is broken. 

### Steps to Reproduce
1. Import a dataset with more than 50k points
2. Aggregate by squares/hexbins

### Expected result
We can either try to optimize this or to deactivate those wizards when we detect that number of features is higher than XX but that wouldn't be ideal, since this aggregation methods are specially useful when working with lots of points.

cc/ @rafatower

**Comment by javisantana** [comment]
same than: https://github.com/CartoDB/cartodb/issues/949
