### ISSUE TITLE
feature request: add publishing options (scrollwheel zoom, etc.) to Publish page

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartodb#12243]
Since a user may not think about 'map options' like search box, zoom controls, scroll wheel zoom, etc. until they are publishing, it would shave off some good time if the map options were also included in the Publish page.

That is, having the following options
<img width="294" alt="screen shot 2017-05-30 at 15 23 42" src="https://cloud.githubusercontent.com/assets/1041056/26601007/488865cc-454c-11e7-8279-cf7f8d1acdb2.png">

listed here too:
<img width="1041" alt="screen shot 2017-05-30 at 15 25 06" src="https://cloud.githubusercontent.com/assets/1041056/26601015/4e60d358-454c-11e7-9ca9-67f4b4a5702e.png">

**Comment by saleiva** [comment]
This is being unified in a new version of the UI. Great minds think alike!

**Comment by saleiva** [comment]
just in case, here is the proposal https://github.com/CartoDB/design/issues/225
