### ISSUE TITLE
User rename

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#12255]
We want to support renaming users.

Some things to consider:
- User model
- Permissions (`owner_username`)
- Layers (`options.user_name` ...)
- SQL queries
- Redis keys

**Requirements**
- Data is kept and is accessible
- Maps keep working (see limitations about SQL queries)
- Users can be renamed multiple times
- Old usernames can be reused (we don’t leave garbage behind)

**Limitations**
- Some SQL queries could be incorrectly transformed after the rename (in order to account for the new DB schema)
- Endpoints will change (because of the subdomain change). Old links (e.g: embeds) will break
- Downtime while DNS propagates. There could be a time where none of the account names are accessible.

**Comment by alrocar** [comment]
🤷‍♂
