### ISSUE TITLE
Switching to an unsaved analysis node with changes doesn't enable apply button

### ISSUE THREAD

**Issue by rjimenezda** [CartoDB/cartodb#12257]
As reported by @xavijam 

![](https://cloud.githubusercontent.com/assets/132146/26633309/3ef6f4a2-4613-11e7-8418-2d1d03c6e645.gif)

We should either:

- Show the stored values instead of the previously entered ones
- Mark Form models as _dirty_ and enable the apply button accordingly

If we do the latter, be careful when applying, since we have to selectively remove attributes so they don't end up in the AnalysisDefinitionNode

**Comment by nobuti** [comment]
Also, if you left the form in an invalid state, the error is not shown again when you come back to this form.

**Comment by rubenmoya** [comment]
Not happening anymore since we changed the analysis workflow view.
