### ISSUE TITLE
Migrate legacy modals CSS from editor to editor-3

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#12256]
Right now we are using several CSS from "old" editor (example: onboarding, modals,...) that we need for new editor-3. We should not rely on those old CSS and migrate (copy-paste?) to our new editor-3.

It doesn't include the CSS related to the only "shared" dialog, the connect-dataset one.

**Comment by alrocar** [comment]
Stale issue. Closing 👋
