### ISSUE TITLE
Problem with analysis tooltip and error

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#12250]
@xavijam commented on [Wed May 31 2017](https://github.com/CartoDB/design/issues/798)

Checking some behaviors with analyses, I've found this problem:

<img width="368" alt="screen shot 2017-05-31 at 15 05 32" src="https://cloud.githubusercontent.com/assets/132146/26633158/b988c7dc-4612-11e7-8d76-455c9f47ddb4.png">

Should we remove the analysis-name tooltip when there is an error in the analysis node?

Assigning @arianaescobar because she opened the ticket in CartoDB repository 😬 
cc @rjimenezda @rubenmoya 

---

@arianaescobar commented on [Wed May 31 2017](https://github.com/CartoDB/design/issues/798#issuecomment-305192214)

I'd say that's the fastest solution, yeah. 

But, just wondering, is it possible to "merge" both tooltips in a single one in those cases? Like "Centroid analysis failed"? 

---

@xavijam commented on [Wed May 31 2017](https://github.com/CartoDB/design/issues/798#issuecomment-305193780)

Sure!

---

@xavijam commented on [Wed May 31 2017](https://github.com/CartoDB/design/issues/798#issuecomment-305194033)

But take into account that the error could change and provide more info. It could be like:

`Centroid (A2): column whatever is not longer available`

What do you think?

---

@arianaescobar commented on [Wed May 31 2017](https://github.com/CartoDB/design/issues/798#issuecomment-305196064)

Love it.

**Comment by xavijam** [comment]
@arianaescobar should we make the tooltip red? Suggested by @urbanphes.

**Comment by arianaescobar** [comment]
Yes, totally!

**Comment by rjimenezda** [comment]
Closed via #12259

**Comment by rjimenezda** [comment]
In production 👍
