### ISSUE TITLE
Animated style for a points layer breaks other styles

### ISSUE THREAD

**Issue by AleGoiko** [CartoDB/cartodb#12251]
### Context
Trying to switch among different styles for a points layer.

### Steps to Reproduce

1. Click on the airports layer
2. Click on style
3. Click on animated
4. Click on adm. regions

### Current Result
Error in tiles requests on activating the adm. regions style after the animated style is active for a points layer

### Expected result
It should work :)

### Browser and version
Any

### .carto file
[airports (on 2017-04-20 at 11.56.51).zip](https://github.com/CartoDB/cartodb-bcg/files/942816/airports.on.2017-04-20.at.11.56.51.zip)

### Additional info
After activating the animated style this error appears on the Javascript console of the browser:

```
common_editor3.js:32 Uncaught TypeError: this.model.getTileURLTemplate is not a function
    at i._onModelUpdated (common_editor3.js:32)
    at s (vendor_editor3.js:38)
    at r (vendor_editor3.js:38)
    at m (vendor_editor3.js:38)
    at N.d.k.trigger (vendor_editor3.js:38)
    at N.d.set (vendor_editor3.js:38)
    at i.<anonymous> (common_editor3.js:37)
    at vendor_editor3.js:67
    at Function.u.each.u.forEach (vendor_editor3.js:67)
    at i._updateLayerModels (common_editor3.js:37)
```

Something similar happens with the "Aggregation pixel" style...

**Comment by xavijam** [comment]
As far as I know you have to have the FDW enabled in order to make it work. Am I wrong @ethervoid? (I remember you commenting the same in other issue)

**Comment by AleGoiko** [comment]
Sorry, that error was happening on my install and i was checking the wrong tab (thought it was the cloud and it wasnt). We've noticed some weird things with google basemaps but i cant quite put them well enough into words as for an issue. If they pop up again i'll ping you. Thanks and sorry for the false alarm!

**Comment by xavijam** [comment]
Ooook, closing it then 💋 .
