### ISSUE TITLE
Investigate root cause of privacy change with no map issue

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#12264]
From https://github.com/CartoDB/cartodb/issues/12137

This is happening in development, but not production. We improved logging, but no luck.

Changing `after_create :create_canonical_visualization` to `after_create { create_canonical_visualization }` fixes it. Seems to be some weird callback ordering issue.

Also, try to write a test (might be impossible, see below). The original PR had a bug that broke all imports locally. Fixed in https://github.com/CartoDB/cartodb/commit/e1e1c1ffc848bdb56af643f9206098fc1c69d361

The fact that it only happens in development, smells like some kind of auto-reloading detail, and the difference between passing callbacks as symbols or as blocks.

**Comment by javitonino** [comment]
Confirmed it has to do with the environment. Changing the environment to production locally, works all the time.

**Comment by javitonino** [comment]
I did not manage to find the actual reason why this happens. But, symbol and block callbacks use slightly different code paths, and build callbacks with slight difference in options that are likely to be the cause. Using the same kind of callbacks (see PR), fixes the problems, so I think we should just keep to use symbol-based callbacks, and that's it.

**Comment by juanignaciosl** [comment]
FYI this happens with a brand-new installation. Not urgent now, though.

**Comment by javitonino** [comment]
Is it possible that you were using the `update_gemfile_lock` at the time? I just took a look, and that branch did not have the fix for this. Please accept my apologies 🙏. I will be more aggressive checking out master before branching from now on.

**Comment by juanignaciosl** [comment]
It might be. I just retried with an updated branch and it works ✨
