### ISSUE TITLE
this._tooltipTitle is not a function

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#12279]
Since merging https://github.com/CartoDB/cartodb/commit/0bdf4a6f7b20d347d96aee93d229205092172f44 we are getting every now and then the error `this._tooltipTitle is not a function` related to `editor-pane.js' line 206.

More info on 
https://my.trackjs.com/messages/filtered?hash=8bf772edd23f337d&sort=serverTimestamp%7casc

I think it just prevent the tooltip from appearing so no critical. But it's happened a thousand times since it was deployed one week ago so it'd be nice to fix it.

**Comment by rjimenezda** [comment]
I can't reproduce it, but we can protect against calling a non-existing function.

**Comment by rjimenezda** [comment]
Never mind, just add a widget & roll over the button while on the widget tab, it happens then.
