### ISSUE TITLE
Disable geocoding options

### ISSUE THREAD

**Issue by Xatpy** [CartoDB/cartodb#1227]
Remove the options (in local install version):
-By City Names
-By Admin. Regions
-By Postal Codes
-By IP Addresses

**Comment by saleiva** [comment]
bump!

**Comment by Xatpy** [comment]
Yep, sorry, I'll work on it from tomorrow now that Carla is also with Support.

**Comment by saleiva** [comment]
bump!

**Comment by Xatpy** [comment]
pr just done:
https://github.com/CartoDB/cartodb/pull/1500

**Comment by Xatpy** [comment]
Merged.
The feature flag name is:
*georef_disabled*
