### ISSUE TITLE
500 when rejecting Dropbox oauth modal

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#12286]
### Steps to Reproduce
1. Disconnect from Dropbox (if your account is connected)
2. Go to import a new dataset
3. Select connect to dropbox
4. In the oauth popup, choose "cancel"

### Current Result
A 500 error page in the popup and https://rollbar.com/carto/CartoDB/items/23479/?item_page=0&item_count=100&#instances

### Expected result
A cleaner failure.

cc @juanignaciosl

**Comment by ramiroaznar** [comment]
@javitonino can we close this?

**Comment by javitonino** [comment]
I don't think so, I have not worked on it yet.
