### ISSUE TITLE
Improve visualization exporter: dataset and sync support

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#12283]
We need to improve the visualization exporter to support more usecases. We are only concerned by the metadata part. We need the following:
- Export and restore visualization ids (done in #12271)
- Export and restore permissions -> export acl, we can regenerate `shared_entities`. We will keep user uuids, so no need for transformations.
- Export and restore syncs
- Export and restore datasets (this appears to be only be a question of relaxing a check) (done in #12271)

The following are nice-to-have, but not a requirement as of now:
- Export and restore data imports
- Export and restore external data imports
- Export and restore mapcaps (as they might be different from live metadata)

Lack of that will mean that we lose import logs and the match between an imported data library visualization and the source material, but that is acceptable for now.

**Comment by gfiorav** [comment]
Hey, would it help if .carto files supported sync table exports?

**Comment by javitonino** [comment]
We had a talk regarding this. What Guido is working on is not useful for this part, but could be useful when we reach the point where we need to export maps depending on common data visualizations. So for now, each of use will keep working on our things, and we can catch-up later, when working with common data. Thanks @gfiorav 💌
