### ISSUE TITLE
[Purple] Remote sources in .carto

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#12280]
### Context

This feature would involve allowing "Sync tables" and other remote types to be exported to a .carto, as opposed to exporting a full dataset dump. A piece of metadata information would be present in the exported layer, indicating that a remote type dataset must be created for it (be it a sync table with a url and a refresh time or something else like a FDW).

A formal specification is made available here: [Coming soon]

### Parts

I. `.carto` metadata structure
II. Importer capabilities to create Sync tables on import
III. Exporter capability to generate sync table exports
IV. Export API supports exporting remote sources

#### Part I: `.carto` metadata structure

The proposed change to the layer JSON, would include information about sources:

```json
{
    "options": {
        "default": false,
        "url": "https://cartodb-basemaps-{s}.global.ssl.fastly.net/light_nolabels/{z}/{x}/{y}.png",
        "subdomains": "abcd",
        "minZoom": "0",
        "maxZoom": "18",
        "name": "Dark matter (lite)",
        "className": "dark_matter_lite_rainbow",
        "attribution": "&copy; <a href=\"http://www.openstreetmap.org/copyright\">OpenStreetMap</a> contributors",
        "labels": null,
        "urlTemplate": "https://cartodb-basemaps-{s}.global.ssl.fastly.net/dark_nolabels/{z}/{x}/{y}.png",
        "type": "Tiled",
        "tms": false,
        "category": "CARTO",
        "selected": true,
        "val": "dark_matter_lite_rainbow",
        "label": "Dark matter (lite)",
        "highlighted": true
    },
    "kind": "tiled",
    "infowindow": null,
    "tooltip": null,
    "widgets": [],
    "legends": [],
    "data": {
        "source": {
            "type": "synchronization",
                "configuration": {
                    "url": "http://spatialkeydocs.s3.amazonaws.com/FL_insurance_sample.csv.zip",
                    "refresh_interval_in_seconds": 900
                }
            }
        }
    }
}

**Comment by javitonino** [comment]
@gfiorav FYI, we will be working on something similar very soon, so let's see if there is something in common. In particular, we are working on exporting full user metadata (basically, user mover v2) which includes exporting all visualizations, including datasets. Although the current code support datasets, we will be adding the information from the sync model as well.

Here's our ticket https://github.com/CartoDB/cartodb/issues/12283
