### ISSUE TITLE
Time-series UI - Range filter tags and widget title

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#12291]
Split from https://github.com/CartoDB/cartodb/issues/11588

- Add selection tags above range filter limits.

![image](https://cloud.githubusercontent.com/assets/1078228/26354337/7cce6990-3fc4-11e7-836e-62ce5bb11cf6.png)

The current behaviour is showing a text in the header section. 

![image](https://user-images.githubusercontent.com/1078228/26934197-007c781c-4c69-11e7-95e2-aa8c01fe8246.png)

Perhaps we should tackle this before https://github.com/CartoDB/cartodb/issues/12178 to give space for the latter issue.

Please check the different behaviours in the design tickets, specially the comment about what to do when the two labels are very close -> https://github.com/CartoDB/design/issues/597#issuecomment-285003447

**Different positions**

Label above Play button
![image](https://user-images.githubusercontent.com/1078228/26935933-9457a058-4c6d-11e7-8dd9-6ac17f492018.png)

Label in the rightmost position
![image](https://user-images.githubusercontent.com/1078228/26935959-a3bc8a68-4c6d-11e7-8ec5-a6573c01d557.png)

Label in the middle
![image](https://user-images.githubusercontent.com/1078228/26935973-ab99a400-4c6d-11e7-8332-332dcbd84e50.png)

Label in the leftmost position
![image](https://user-images.githubusercontent.com/1078228/26935993-b5ec14e2-4c6d-11e7-82b5-2a9eef863527.png)

Very close labels
![image](https://user-images.githubusercontent.com/1078228/26936015-c048ec30-4c6d-11e7-8b20-8b5ec1eec621.png)

**Comment by xavijam** [comment]
Thoughts about this ticket:

- Tipsy tooltip is available neither in DI nor in CARTO.js, we should create one to be used there (from _cosecha propia_ IMHO, but you decide).
- Be careful with the edges of the widget, tooltip will need to work properly :dancer:.

**Comment by rjimenezda** [comment]
- There's a tooltip view already, it's used, for instance, on the regular histogram.
- Will do

**Comment by rjimenezda** [comment]
@urbanphes On the screenshots above, the handles for the range selection are different from the ones we have right now. They are a big pill from top to bottom, without the line across it.

The full height actually works better for a tooltip, but should we change them for the regular histogram as well, or should they be different?

**Comment by rjimenezda** [comment]
Leaving this here as a reminder, cause it's causing issues with the tooltips

https://github.com/d3/d3/issues/1604

**Comment by urbanphes** [comment]
Sorry for the delay 🙏. 
Today I've been talking with @rjimenezda and the doubt is resolved. 

This is the ticket, we are working now https://github.com/CartoDB/design/issues/597

**Comment by rjimenezda** [comment]
Moved back to code review cause I added a lot of code to address the issues, sorry about that.

**Comment by rjimenezda** [comment]
@CartoDB/design @noguerol going to deploy this soon™️ 

Next step will be moving the play button & adapting more of the responsive changes. #12387 

💋 

PS: The ability to drag the selection and click to go to a certain point is almost finished too (#12180)
