### ISSUE TITLE
Add Mapzen client keys to rails configuration

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#12296]
From https://github.com/CartoDB/cartodb.js/issues/1669 (see https://github.com/CartoDB/cartodb.js/issues/1669#issuecomment-307345025).

cc: @juanignaciosl

**Comment by juanignaciosl** [comment]
@alonsogarciapablo you only need a `mapzen_api_key`, isn't it? Where should it be placed for you to use it? I only see references to cartodb.js.

**Comment by juanignaciosl** [comment]
I'll create `geocoder.mapzen.api_key` configuration parameter, and I'll output it with `cdb.config.set('client_mapzen_api_key', '<%=MAPZEN_CLIENT_KEYS %>')
we` at embed/public page [as santana suggest](https://github.com/CartoDB/cartodb.js/issues/1669#issuecomment-307343503).

@alonsogarciapablo , @javitonino please confirm that `geocoder.mapzen.api_key` is a good key path ([it seems to be an API key](https://github.com/CartoDB/cartodb.js/blob/7ea6457edc3dcb5f37d6dfe047943443f02d5f28/src/geo/geocoder.js#L85) and it's only used in the geocoder right now) so I can deploy the configuration change even before deploying the code.

**Comment by alonsogarciapablo** [comment]
@juanignaciosl yes, we only need the key, which is currently harcoded [here](https://github.com/CartoDB/cartodb.js/blob/v4/src/geo/geocoder/mapzen-geocoder.js#L12).

Instead of `cdb.config.set` I'm planning to make it an option to `createDashboard` because that's how we're currently setting up api keys, auth tokens, etc. I can take care of that part.

**Comment by nobuti** [comment]
In production
