### ISSUE TITLE
Inputs not getting default values

### ISSUE THREAD

**Issue by rubenmoya** [CartoDB/cartodb#12308]
### Context
![widget-radio-buttons](https://user-images.githubusercontent.com/905225/27040497-7081cc04-4f91-11e7-8163-094613563173.gif)

### Steps to Reproduce
1. Set dynamic to false in a widget
2. Open widget's context menu and click edit

### Current Result
Dynamic is neither 'yes' nor 'no'

### Expected result
Dynamic is 'no'

### Browser and version
Safari Version 10.1.1 (12603.2.4)

**Comment by ramiroaznar** [comment]
This is already reported and fixed [here](https://github.com/CartoDB/support/issues/890).
