### ISSUE TITLE
[Model refactor] Remove `Visualization::Member` usages from json/visualizations_controller

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#12309]
Remove the remaining 6 `Member` usages from `Api::Json::VisualizationsController`. One of them, `set_next_id`, can be removed, because we currently don't support Odyssey. The rest of them (and the constants) can be changed to `Carto::Visualization`.

In order to do it, move the methods to `Carto::VisualizationsController`. We usually match `Carto::` controllers with `Carto::` models, primarily as convention, so we know what models should be used in each controller.

There are tests for like methods. That can be a nice first step. You should do tests for the other methods.

If any of the changes become unexpectedly difficult, split this issue in many.

**Comment by javitonino** [comment]
Addendum: It would be nice to move this to `Carto::VisualizationsController`. We usually match `Carto::` controllers with `Carto::` models, primarily as convention, so we know what models should be used in each controller.
