### ISSUE TITLE
Cannot create a static map from a viz.json with a Torque layer

### ISSUE THREAD

**Issue by iaindillingham** [CartoDB/cartodb#12306]
### Context
Cannot create a [static map][] from a viz.json with a Torque layer.

[static map]: https://carto.com/docs/carto-engine/carto-js/static-maps

### Steps to Reproduce
Paste the following into a new HTML file.
```
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="http://libs.cartocdn.com/cartodb.js/v3/3.15/themes/css/cartodb.css">
  </head>
  <body>
    <div id="map"></div>
    <script src="http://libs.cartocdn.com/cartodb.js/v3/3.15/cartodb.js"></script>
    <script>
      var url = "https://vm-gis.carto.com/api/v2/viz/bbff1084-146c-11e7-a697-0e3ff518bd15/viz.json";
      cartodb.Image(url).size(256, 256).write();
    </script>
</html>
```
### Current Result
See your browser's developer console. Two requests -- one post, one get -- that originate within _cartodb.js_ 404. The response from the post request reads _layergroup GET needs a "config" parameter_.

### Expected result
I expected the `script` tag to be replaced with an `image` tag.

### Browser and version
Firefox 53.03.

**Comment by xavijam** [comment]
Hi @iaindillingham, but that functionality belongs to our JS library CartoDB.js. Let me move the ticket to the proper repository 🤗 .

**Comment by xavijam** [comment]
Issue moved to [CartoDB/cartodb.js #1679](https://github.com/CartoDB/cartodb.js/issues/1679) via [**ZenHub**](https://www.zenhub.com/)

**Comment by iaindillingham** [comment]
Thank you @xavijam.
