### ISSUE TITLE
Time-series UI - Range filter doesn't reset when changing buckets

### ISSUE THREAD

**Issue by rubenmoya** [CartoDB/cartodb#12307]
### Context
![time-series](https://user-images.githubusercontent.com/905225/27038466-67514124-4f8b-11e7-8786-9dc759e00f5e.gif)

### Steps to Reproduce
1. Filter the data in the widget 
2. Change the number of buckets

### Current Result
The filter doesn't reset properly it ends up filtering the first bucket. You can press play although it seems filtered, and it goes trough all the data.

### Browser and version
Safari Version 10.1.1 (12603.2.4)

**Comment by ramiroaznar** [comment]
Hey @rubenmoya should we close this issue? The time series widget UI now is different.

**Comment by rubenmoya** [comment]
Yeah, let's close it :)
