### ISSUE TITLE
CartoDB::SQLApi::SQLError: cannot determine type of empty array

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#1232]
https://rollbar.com/vizzuality/CartoDB/items/4521/
```
CartoDB::SQLApi::SQLError: CartoDB::SQLApi::SQLError
1 File "/home/ubuntu/www/production.cartodb.com/releases/20141121082751/services/sql-api/sql_api.rb", line 48 in raise_if_error
2 File "/home/ubuntu/www/production.cartodb.com/releases/20141121082751/services/sql-api/sql_api.rb", line 35 in handle_response
3 File "/home/ubuntu/www/production.cartodb.com/releases/20141121082751/services/sql-api/sql_api.rb", line 28 in fetch
4 File "/home/ubuntu/www/production.cartodb.com/releases/20141121082751/services/table-geocoder/lib/internal_geocoder.rb", line 59 in download_results
5 File "/home/ubuntu/www/production.cartodb.com/releases/20141121082751/services/table-geocoder/lib/internal_geocoder.rb", line 40 in run
6 File "/home/ubuntu/www/production.cartodb.com/releases/20141121082751/app/models/geocoding.rb", line 88 in run!
7 File "/home/ubuntu/www/production.cartodb.com/releases/20141121082751/lib/resque/geocoder_jobs.rb", line 9 in block in perform
8 File "/home/ubuntu/www/production.cartodb.com/releases/20141121082751/lib/resque/base_job.rb", line 19 in call
9 File "/home/ubuntu/www/production.cartodb.com/releases/20141121082751/lib/resque/base_job.rb", line 19 in run_action
10 File "/home/ubuntu/www/production.cartodb.com/releases/20141121082751/lib/resque/geocoder_jobs.rb", line 9 in perform
```

**Comment by rafatower** [comment]
See https://github.com/CartoDB/cartodb/issues/3024

**Comment by rafatower** [comment]
I think this one should be easy to reproduce and fix. Most likely the SQL API call is just fed with empty data (as the trace suggest). The fix would be not to send that request to the `geocoding` account in that case.

**Comment by iriberri** [comment]
Reproduced. My first guess comes with the size of the information that is being sent. In one of the cases, it was `131204` chars in a single row. I still need to check SQL API logs but after seeing this, we might want to limit the chars per row that we are sending both in each column and in free text inputs.

**Comment by iriberri** [comment]
One crazy example that reproduces the problem:
![image](https://cloud.githubusercontent.com/assets/1730320/11441142/62b01d9a-9509-11e5-8550-031a2623720f.png)

**Comment by iriberri** [comment]
I can't reproduce the empty array error. As the occurrence is from >1 year ago, we are not logging it anymore so we don't know from which options it came from in order to guide us further.

I have not seeing this array error occurrence again in Rollbar in the stored occurrences.

**Comment by rafatower** [comment]
It seems like we're still having some failure responses from SQL API (`response_code != 200` without an error message). See https://github.com/CartoDB/cartodb/blob/master/services/sql-api/sql_api.rb#L49-L53

A bit too unspecific to have this issue as an actionable item. Closing this FTM (feel free to reopen if disagree).
