### ISSUE TITLE
Ampersands invalid in Layer or Map names

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#12322]
@arredond commented on [Wed Jun 14 2017](https://github.com/CartoDB/support/issues/776)

### Context

When adding an ampersand (&) to a layer or map name, it gets parsed with its HTML entitiy name: **'&amp**. This doesn't happen for other special characters tested: / \ · ( ) [ ] $ % ¬ ª º ^` + * + { } ç

### Steps to Reproduce

1. Add an ampersand (&) to a layer or map name
2. The symbol will be replaced by its HTML entity name ('&amp)
3. The naming may or may not fail

![ampersand](https://user-images.githubusercontent.com/19406854/27125102-781385bc-50f3-11e7-830b-175f4a63199c.gif)

**Comment by Jesus89** [comment]
It also happens with "<" and ">":

```
< & >
&lt; &amp; &gt;
```

**Comment by Jesus89** [comment]
This bug comes from https://github.com/CartoDB/bug-bounty/issues/152.

I found that notifications and widget's source also require a sanitizeHTML:

![sanitize-notification-widgets](https://user-images.githubusercontent.com/2227572/30020161-2d7280fc-9163-11e7-86fd-d573fa786b31.png)

**Comment by xavijam** [comment]
👍

**Comment by Jesus89** [comment]
I will fix also the following bug:
- Source in widget is not updated when Layer name changes

**Comment by xavijam** [comment]
Niiiiiice!

**Comment by rubenmoya** [comment]
In production 🚀
