### ISSUE TITLE
Could we "freeze" a copy of maps that use viz.json v2?

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#12336]
As you might now, some clients haven't been migrated to BUILDER because they have or are still using viz.json v2.

Yesterday, @jsanz had an idea to migrate these users... After they are migrated, if they open an Editor map with BUILDER, we could create a copy of the map so that the old one remains locked / non-editable / hidden?. Any change would then be saved on the new copy. This way, "old" maps would still be accesible from custom apps using CartoDB.js 3.15.X and viz.json v2, and clients would be able to start playing with BUILDER.

Would this be feasible? (cc: @xavijam @juanignaciosl @javitonino @javisantana )

@kevin-reilly still, once they are migrated:

1. The wouldn't be able to edit those "old" maps. So if they have a custom app and want to change something, they are screwed 😢 .
2. They wouldn't be able to use CartoDB.js and build custom apps until we release a new version of the library with support for viz.json v3. Unless we provide the fallback described in https://github.com/CartoDB/cartodb.js/issues/1675.

**Comment by javitonino** [comment]
There is already something pretty similar to this. When a user tries to open a map with incompatible Builder features (such as overlays) in Builder, we offer him three options:
- Cancel (do not open the map)
- Open the map anyway (with a big warning)
- Duplicate the map, and open the copy (keep the original intact).

For now, when trying to open a map which is being used in a cartodb.js 3 application, we still open them in editor to allow edition. They can edit with editor, or duplicate it to edit with builder. If we want to phase out editor completely, we could make them behave as other incompatible map (as described in my 1st paragraph) with minimal effort.

**Comment by juanignaciosl** [comment]
_Edited because jtorres edited in the middle. @alonsogarciapablo , please, mention only me, or only him, not both, this happens all the time :D. One will ping the other if needed :D _

Although the current approach that javitonino mentions is good, I guess that the problem with cartodb.js is that users want to keep ids and so on. If the current "worarounds" are not enough, maybe we could adapt Mapcaps to do something like this. When a visualization is going to be migrated, we could create a snapshot with it, and use it for v2.

On the other hand, that kind of hidden freezes might be confusing.

**Comment by alonsogarciapablo** [comment]
Thanks for your input guys!

>  @alonsogarciapablo , please, mention only me, or only him, not both, this happens all the time :D. One will ping the other if needed :D _

Sorry about that! 🙏

**Comment by alonsogarciapablo** [comment]
> For now, when trying to open a map which is being used in a cartodb.js 3 application, we still open them in editor to allow edition. They can edit with editor, or duplicate it to edit with builder. If we want to phase out editor completely

So both Editor and BUILDER are working together in some accounts with maps that we think are being used from CartoDB.js 3.X (I'm guessing we do this by checking if they've had accessed the viz.json v2 endpoint)? Thanks!

**Comment by juanignaciosl** [comment]
Yes. For users with builder, this check is performed when a visualization is loaded:

```
  def open_in_editor?
    !builder? && (uses_vizjson2? || layers.any?(&:gmapsbase?))
  end

  def builder?
    version == VERSION_BUILDER
  end

  VERSION_BUILDER = 3
````

If `open_in_editor?` returns `true`, user is redirected to the editor.

**Comment by alonsogarciapablo** [comment]
Thanks! So I guess we could potentially migrate every remaining user to BUILDER and old maps would still be opened with Editor, but then those users wouldn't be able to create new maps with Editor and they wouldn't be able to create new custom apps with CartoDB.js 3.X (cc: @kevin-reilly).
