### ISSUE TITLE
wrong export image size limitations for premium google accounts

### ISSUE THREAD

**Issue by AleGoiko** [CartoDB/cartodb#12332]
### Context
Resizing an image export from a premium account (one with signed api calls)

### Steps to Reproduce

1. Go to any map
2. click export image
3. try to resize height or with to anything larger than 640px

### Current Result
Invalid dimension(640x640px)

### Expected result
Being an enterprise account it should go up to 2048px

cc/@asimcox

**Comment by asimcox** [comment]
Connected to this client facing ticket: CartoDB/BCG-testing/issues/115

**Comment by xavijam** [comment]
Hey mates, I've checked in production and in development and that validation is not present in the SaaS version:

<img width="1742" alt="screen shot 2017-06-16 at 08 23 26" src="https://user-images.githubusercontent.com/132146/27214516-3faf39b6-526d-11e7-85a2-74ab9a1a86b8.png">
<img width="1741" alt="screen shot 2017-06-16 at 08 23 35" src="https://user-images.githubusercontent.com/132146/27214515-3fad6032-526d-11e7-9003-8f79abb45c50.png">

The limit for the form image is always 8192px x 8192px (no matter the basemap type). Could you check you have the latest code please?

**Comment by xavijam** [comment]
cc @ernesmb in case you are not aware of my last comment 🤗 .

**Comment by AleGoiko** [comment]
Don't worry folks, it's all good now ;) You can close this.
