### ISSUE TITLE
[feature request] Import API: specify schema in POST

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartodb#12330]
Being able to specify the schema in the POST with the Import API would be really helpful.

The way I do it now is use the Import API with no type guessing, and afterwards use the SQL API with `ALTER TABLE .. ALTER COLUMN .. TYPE` statements. The main advantage I see is more transparency on column naming so the mapping between the original data source and the resultant carto table is more explicit. This gets tricky, though, when the column names are normalized. I opened another ticket about that: https://github.com/CartoDB/cartodb/issues/12331

cc @juanignaciosl

**Comment by juanignaciosl** [comment]
Most of what I just said at #12331 applies to this issue as well. Changing the database schema is hardly a concern of the Import API but of SQL API.

Nevertheless, we might be speaking (again) about the need for a mapping between "user columns" and "actual columns". In fact, this is one of the customizations that some customers have made on top of CARTO.

cc @stuartlynn @kevin-reilly
