### ISSUE TITLE
Country can be checked but not selected in Postal Code Geocoding

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#12334]
In Postal Code geocoding, user can check the analysis Parameters COUNTRY box but the country field is inactive if postal code column is number-type. Country field is active if column is string-type.

If this is expected behavior can we indicate that via the interface? 

### Steps to Reproduce

1. Unzip this file & drag/drop it onto Maps dashboard: [epsilon_age.zip](https://github.com/CartoDB/support/files/1078573/epsilon_age.zip)
2. Click map's data layer to open it. It should be on STYLE tab by default w/message to georef. Click Georeference button. 
3. Use this setup:
    
    ![screen shot 2017-06-15 at 2 25 20 pm](https://user-images.githubusercontent.com/1779444/27195883-7f8da9ec-51d6-11e7-8e0c-5fef5bd79ce8.png)

4. Click in the country field that says `Select country column`

### Current Result
Inactive country field even though box is checked:

![number_zips](https://user-images.githubusercontent.com/1779444/27196055-051d6bce-51d7-11e7-8ebe-347f36dbde35.gif)

### Expected result

![string_zips](https://user-images.githubusercontent.com/1779444/27196144-59bfd07c-51d7-11e7-8939-57a4bb29d455.gif)

### Browser and version

Version 59.0.3071.86 (Official Build) (64-bit)

### .carto file
[epsilon_age_map__on_2017-06-15_at_16.10.33_.zip](https://github.com/CartoDB/support/files/1078606/epsilon_age_map__on_2017-06-15_at_16.10.33_.zip)

**Comment by xavijam** [comment]
The component should be enabled although current node schema doesn't contain any string column.

**Comment by saleiva** [comment]
Country should be mandatory on this, so we should remove the checkbox. You should always select a country or introduce a text.

**Comment by noguerol** [comment]
Currently geocoding fails if the column is not _string_ --> https://github.com/CartoDB/cartodb-management/issues/4834 a behavior we should change both in the analysis and the template (this ticket). 
@saleiva is making reference to this --> https://github.com/CartoDB/cartodb/issues/12403 so let's keep the conversations independent

**Comment by matallo** [comment]
as a heads up, I'm currently on this

**Comment by saleiva** [comment]
BOOM
