### ISSUE TITLE
Postgis Plugin error when deleting an analysis with a Pop-Up enabled

### ISSUE THREAD

**Issue by csobier** [CartoDB/cartodb#12342]
@xavijam, can you advise if this is by design?

### Context
Error message when deleting an analysis from a layer that has POP-UP enabled.

### Steps to Reproduce
1. Create a map and run any analysis
2. Enable a click or hover pop-up column for the same layer (Do not use any analysis result columns)
3. Delete the analysis... 

### Current Result
A big fat error message appears. For example:

`Nearest Food to Metro: Postgis Plugin: ERROR: column "cuisine" does not existLINE 1: ...cator",0.001),0.001,true),3) AS geom,"cartodb_id","cuisine",... ^in executeQuery Full sql was: 'SELECT ST_AsTWKB(ST_Simplify(ST_RemoveRepeatedPoints("the_geom_webmercator",0.001),0.001,true),3) AS geom,"cartodb_id","cuisine","name" FROM (SELECT * FROM lineas_metro_madrid_3) as cdbq WHERE "the_geom_webmercator" && ST_SetSRID('BOX3D(-20037508.3 20037508.29613578,-20037508.29613578 20037508.3)'::box3d, 3857)`

![image](https://user-images.githubusercontent.com/13319925/27285889-33a26844-54cc-11e7-9e5c-d810421d35a2.png)

**Workaround**: If I change the POP-UP to NONE, the error goes away.

### Expected result
Perhaps there is a way to avoid seeing such an error, or at least soften the message? Or is this by design?

### Browser and version
Chrome, Version 58.0.3029.110 (64-bit)

**Comment by ramiroaznar** [comment]
@csobier can you share the .carto of that map to test it?

**Comment by csobier** [comment]
There should be an error included with this .carto file: [SF Trees Import (on 2017-11-02 at 12.35.30).carto.zip](https://github.com/CartoDB/cartodb/files/1437699/SF.Trees.Import.on.2017-11-02.at.12.35.30.carto.zip)

**Comment by xavijam** [comment]
This is an error that happens also if you apply a CartoCSS code using one of the columns generated by the analysis. If you remove it, the map fails. That's something not easy to fix, and it needs to think how to proceed, aka not for response team.

**Comment by ramiroaznar** [comment]
Good to know. Another one to the bucket.
