### ISSUE TITLE
Improve histograms with outliers

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb#12340]
It's not quite uncommon to have datasets with outliers.

However, using histograms with that kind of datasets, sometimes, is not as good as it could be. The outliers affect too much the representation and make the filtering completely useless.

As an alternative, we should provide an option to show/hide the outliers from the histogram. That will improve the visualization of the distribution and, also, the filtering capabilities of the widget.

An example of a histogram with outliers:

![screen shot 2017-06-16 at 18 13 03](https://user-images.githubusercontent.com/45346/27235176-15f1c26c-52c0-11e7-84e1-61d2e5402c81.png)

The same histogram removing the top and bottom 1 percent:

![screen shot 2017-06-16 at 18 13 10](https://user-images.githubusercontent.com/45346/27235225-3c4d02be-52c0-11e7-8a37-f0686cecbca2.png)

**Comment by saleiva** [comment]
When talking about this the other day, we proposed an idea having an option for this on the "..." submenu.

**Comment by javisantana** [comment]
In these cases autostyle should be really smart and style using outliers styling -> https://github.com/CartoDB/turbo-carto/issues/32

A "see outliers" filter would be also nice

**Comment by AbelVM** [comment]
Same as (or hightly related to) https://github.com/CartoDB/solutions/issues/684, isn't it? :thinking:

**Comment by saleiva** [comment]
yep @AbelVM

**Comment by AbelVM** [comment]
Then... I'm not comfortable with the "range shrinking" proposed here. I'd like to have all my data there, but higher LOD (x-axis) in the range where most of the values live, as described in the issue above

**Comment by saleiva** [comment]
I understand, and that's another option. Anyway a logarithmic scale wouldn't fix this problem always neither, so we will experiment first.

**Comment by AbelVM** [comment]
As inspiration, here you have some 3rd party examples of semi-log histograms, using different data sources:

* Mathematica
![image](https://user-images.githubusercontent.com/9017165/27530967-23800978-5a5b-11e7-9a6c-2209a2e3a453.png)

* Matlab
![image](https://user-images.githubusercontent.com/9017165/27531389-b4eea5c6-5a5c-11e7-99d0-0ff6be753cea.png)

* SAS
![image](https://user-images.githubusercontent.com/9017165/27530976-2cd8903a-5a5b-11e7-9dfb-9aef6aee969b.png)
![image](https://user-images.githubusercontent.com/9017165/27530983-31aee4ba-5a5b-11e7-8fcd-481d9a6ddcf5.png)

* R
![image](https://user-images.githubusercontent.com/9017165/27531260-3d156846-5a5c-11e7-94af-382407180715.png)

**Comment by rochoa** [comment]
It's important to not forget that histograms should keep a consistent binning when data is filtered in other dimensions. Having a variable bucket width makes more difficult to keep that consistency in place.

**Comment by javisantana** [comment]
:(
