### ISSUE TITLE
Using the same measurement twice - even with different options - doesn't enable the button

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#12348]
## STR
- Create a map of SF neighborhoods (present in data library).
- Create a DO analysis with a measurement of "Area with solar energy potencial".
- Don't select anything else and add another measurement, again "Area with solar energy potencial".
- Select the only option in the timespan.
- Try to apply the analysis but it doesn't work.

**Comment by nobuti** [comment]
The validation for this happens using the column names returned by the api. So even if the user didn't select a timespan, the api select a default timespan, so it could happen (it's happening indeed) the final column values end being the same.

**Comment by nobuti** [comment]
On the other hand, I'm pretty sure this will be fixed with https://github.com/CartoDB/cartodb/issues/12349

**Comment by nobuti** [comment]
This is fixed as part of https://github.com/CartoDB/cartodb/pull/12358. Moving to acceptance.

**Comment by xavijam** [comment]
Yep, fixed in https://github.com/CartoDB/cartodb/pull/12358, closing! \o/.
