### ISSUE TITLE
We shouldn't let add a new measurement after the last one is valid

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#12351]
## STR

- Create a map of SF neighborhoods (present in data library).
- Create a DO analysis.
- Add a new measurement item.

We should not let the user add a new measurement until the previous one is selected and valid.

### Caveats
- If it is necessary, we will display a required tooltip. But we don't think we will needed.

**Comment by nobuti** [comment]
This is closely related to Backbone Forms and nested components forms. Right now, this same component is used in custom legend form as well.

**Comment by xavijam** [comment]
Merged into main branch!
