### ISSUE TITLE
Support signed logout requests in SAML

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#12355]
Out current SAML implementation only supports unsigned logout requests. Some SAML implementations (e.g: ADFS) require this request to be signed. This option is supported by our gem, but we need to generate a certificate for CARTO and configure it on the IdP (this should be easy with SAML metadata).

Relevant Gem documentation: https://github.com/onelogin/ruby-saml#signing

As a bonus, since this increase configuration difficulty: we should test that the metadata file works for autoconfiguring with multiple providers. Right now, it works with simplesamlphp, but it doesn't work very well with ADFS, since it insists in adding `federationmetadata.xml` to the URL for some reason (probably because our route doesn't end in `.xml`).

cc @juanignaciosl

**Comment by mayoral** [comment]
## Identity provider

I've used a Windows 2012 Server inside a VirtualBox VM. I've configured locally to resolve `adfs.cartodb.com` with the IP of the VM.

I generated a custom, self-signed, certificate for `adfs.cartodb.com`:

```
openssl genrsa 2048 > private.pem
openssl req -x509 -new -key private.pem -out public.pem
# In the wizard, set common name to adfs.cartodb.com
openssl pkcs12 -export -in public.pem -inkey private.pem -out adfs_cartodb_com.pfx
```

And copied it to the VM.

After tested a minimal Active Directory setup I've installed Active Directory Federation Services, and configured it following the SAML guide. TL;DR:

- I went to the Server Manager, and on the top bar, clicked on Manage -> Add roles and features. Followed the wizard, using the defaults, and selecting Active Directory Federation Services in the Server Roles page. Clicked through the rest of the wizard and wait for ADFS to be installed.
- In the Server Manager, I clicked on the flag on the top bar and selected the option to Configure the federation service on this server. During the wizard, keep selecting defaults when provided. You will need to manually select the following:
  - SSL certificate: I imported the one previously generated.
  - Federation Service Display Name: You can use any text here.
  - Service account: I used directly the Administrator user.

I opened the ADFS console, and then navigated to AD FS -> Trust Relationships -> Relying Party Trusts. I added a new one with the following setup:

- Select Data Source: Choose to enter the data manually.
- Specify Display Name: Choose any name
- Choose Profile: Select AD FS profile (not 1.0/1.1)
- Configure Certificate: Leave blank
- Configure URL: Enable SAML 2.0 WebSSO and configure your organization URL: https://localhost.lan:3000/u/myorg/saml/finalize
- Configure Identifiers: Add the following URL: https://localhost.lan:3000/u/myorg/saml/metadata
- Configure Multi-factor auth: No
- Choose Issuance rules: Permit all users
- Finish: Choose to open the Edit Claims Rules configuration

Where myorg is a local org I've setup on Carto for this. In the claim rules window, I used the following setup:

- Select Send LDAP Attributes as Claims
- Chose a rule name
- Select Active Directory as Attribute store
- In the table view, choose User-Principal-Name for the left column, and E-mail address for the right column.

This is all we need to setup the Windows machine.

## Service Provider (Carto)

The config here is pretty straightforward. After creating the myorg organization, I run the following command:

```
ORGANIZATION_NAME=myorg SAML_IDP_METADATA_FILE=https://adfs.cartodb.com/federationmetadata/2007-06/federationmetadata.xml SAML_EMAIL_ATTRIBUTE=http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress bundle exec rake cartodb:saml:create_saml_configuration
``` 

Then, I went to the Rails console, loaded the organization and removed the `name_identifier_format` field from the auto-generated saml configuration. To that hash in the database, I added the following fields:

```
   {logout_requests_signed: true, logout_responses_signed: true,metadata_signed:true}
```

That it's equivalent to add in the saml gem the following:

```
    settings.security[:logout_requests_signed] = true
    settings.security[:logout_responses_signed] = true
    settings.security[:metadata_signed] = true
```

I also created a self-signed certificate for the Carto server, with:

```
openssl req -x509 -newkey rsa:2048 -keyout sp_private.key -out sp_certificate.pem -days 3650 -nodes
```

And then added in the `saml_settings` method of `saml_service.rb` this:

```
settings.private_key = File.read("#{Rails.root}/sp_private.key")
settings.certificate = File.read("#{Rails.root}/sp_certificate.pem")
```

I edited some metods to force ssl in development, and started the app using this command:

```
bundle exec thin start --port 3000 --ssl
```

## Progress so far

Users can log in, but when trying to log out, they get the following error:

```
MSIS7074: SAML authentication request for the WebSSO profile must specify an issuer with no NameQualifier, SPNameQualifier or SPProvidedId properties.

This request failed.

User Action

Verify that the message issuer configuration in the AD FS configuration database is up to date.
Configure the signing certificate for the specified issuer.
Verify that the issuer's certificate is up to date.
Verify the issuer and server message signing requirements.
```

**Comment by juanignaciosl** [comment]
For future reference, we've scheduled @javitonino and @mayoral pairing tomorrow. If we don't get any action path, we'll set this issue aside in order to focus on other priorities.

**Comment by javitonino** [comment]
We managed to get it working with the following changes:

CARTO: [saml.diff.txt](https://github.com/CartoDB/cartodb/files/1189906/saml.diff.txt)
AD:
- Relying party configuration:
  - Endpoints, add the logout endpoint (POST worg.localhost.lan/logout)
  - Signature, add the certificate created for CARTO (sp_certificate.pem). converted to .cer: `openssl pkcs12 -export -in cert.pem -out cert.cer -nokeys`
  - Configure a name ID as per http://doc-internal.cartodb.net/platform/onpremises/adfs_saml.html?highlight=saml#configuring-nameid-and-logout-service (restore the name id config in CARTO)

And that should be it. Take a look and see if you can reproduce it 💪

**Comment by mayoral** [comment]
Successfully reproduced in my machine.

Now working on modifying `saml_configuration` method and other parts in the code to support both unsigned and signed logout requests on an easily configurable way. Also adding these configuration params to the rake task.
