### ISSUE TITLE
Make the Region dropdown mandatory

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#12354]
Right now we have this implementation:

<img width="349" alt="screen shot 2017-06-20 at 10 39 24" src="https://user-images.githubusercontent.com/132146/27324252-e0d7e5f6-55a4-11e7-9f28-cc8fd855b404.png">

After the yesterday's agreement, we should not let the user select a measurement until a region is selected. So our proposal here is don't display the measurements list until a region is selected.
What do you think @saleiva? 
cc @nobuti

**Comment by saleiva** [comment]
+1 to that @nobuti @xavijam

**Comment by xavijam** [comment]
Merged into main branch
