### ISSUE TITLE
Clicking on the cross icon exits the analysis

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#12353]
We should not display that icon, basically.

![screen_shot_2017-06-20_at_10 36 05](https://user-images.githubusercontent.com/132146/27324116-61d0110c-55a4-11e7-9c47-3d10d6e66a26.png)

cc @CartoDB/design because we agreed to have it and make it work as it is now.

**Comment by nobuti** [comment]
This was made as part of this: https://github.com/CartoDB/cartodb/issues/10921

**Comment by saleiva** [comment]
Sorry guys, 
we've agreed that we don't show that cross button on confirmation boxes.

**Comment by xavijam** [comment]
👍 , no problem 💋 .
