### ISSUE TITLE
Broken organization metadata service tests in master

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#12364]
https://ci.cartodb.net/job/CartoDB-master-testing/868/console

I confirmed that this reproduces when running `make check-spec-helper-min` but not when running the test independently. I suspect `period_end_date`, but it's just speculation.

cc @juanignaciosl

**Comment by javitonino** [comment]
Replicated during https://github.com/CartoDB/cartodb/pull/12380, fixing it there.

**Comment by juanignaciosl** [comment]
Marked as blocked because [this is now failing because of a frontend issue](https://ci.cartodb.net/job/CartoDB-master-testing/895/console). We were not lucky with the timing :-) As soon as @matallo merges some fixes, it should be back to green again.

**Comment by matallo** [comment]
just rebase your dev branch with master 🙇

**Comment by mayoral** [comment]
Latest master build is now running green :)
