### ISSUE TITLE
Custom Icon Markers - CSS broken in IE

### ISSUE THREAD

**Issue by asimcox** [CartoDB/cartodb#12361]
### Context
IE 11 (Who loves QAing in IE!? haha)

This is a small bug we found while testing uploading custom icon markers via 'Style'. Looks to be an isolated issue to IE.

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Create a Map
2. Upload a point dataset
3. Go to Style > Show full collections > Upload a custom Icon 
4. Click back into the style box and you'll see:

### Current Result

![27341712-4e1ee4b4-55de-11e7-8b51-6f82230adb09](https://user-images.githubusercontent.com/16105514/27347934-60c2498a-55c0-11e7-8410-615c301736ef.png)

### Expected result
*Please describe here below what should be the expected behaviour*
![screen shot 2017-06-20 at 1 56 49 pm](https://user-images.githubusercontent.com/16105514/27347975-7c576f54-55c0-11e7-9ebb-7be64452a984.png)

### Additional info
*Please add any information of interest here below*

**Comment by ramiroaznar** [comment]
Duplicated https://github.com/CartoDB/support/issues/727
