### ISSUE TITLE
Remove javascripts that require internet connection from static files

### ISSUE THREAD

**Issue by luisbosque** [CartoDB/cartodb#12383]
Some of the static html files we have in public (https://github.com/CartoDB/cartodb/tree/master/public) are loading javascripts from internet or javascripts that try to send requests to internet.
One example is analytics javascripts.

This is something that is hard to change with variables for different installations so I think it's better to just remove them from the static htmls

**Comment by dppascual** [comment]
Removed references to javascript files https://github.com/CartoDB/cartodb/pull/13543.

**Comment by dppascual** [comment]
Merged https://github.com/CartoDB/cartodb/pull/13543 by @ivanmalagon
