### ISSUE TITLE
Change play/pause button place and look&feel

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#12387]
Title change has been addressed in this [ticket](https://github.com/CartoDB/cartodb/issues/12178), but unfortunately we haven't changed the play/pause button, so it will be managed here.

![New widget](https://cloud.githubusercontent.com/assets/1078228/26354337/7cce6990-3fc4-11e7-836e-62ce5bb11cf6.png)

**Comment by xavijam** [comment]
Also, let's take care of the responsive behaviour here too 💋 .

**Comment by rjimenezda** [comment]
This issue should solve an issue with selection ranges on touch interfaces with small screens.

**Comment by ivanmalagon** [comment]
@rjimenezda Could you please tackle this issue https://github.com/CartoDB/cartodb/issues/11610 along with this development? It seems quite related.

**Comment by rjimenezda** [comment]
Yep, I replaced the triangle via CSS border-magic with real™️ SVG, so it should look fine now.

**Comment by rjimenezda** [comment]
In order to keep things agile, we won't do the responsive changes here. I'll open a ticket and merge this asap, all features are done, and like 75% of the range playback too.

**Comment by xavijam** [comment]
In production 👏 , great job @roman.
