### ISSUE TITLE
label's basemaps render are broken

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#12384]
### Context
Zoom 13, Madrid Area

![image](https://user-images.githubusercontent.com/1214201/27540095-3090bf9e-5a7f-11e7-8382-d2cd87f70239.png)

**Comment by saleiva** [comment]
@makella is taking care of this.

**Comment by noguerol** [comment]
Duplicated: https://github.com/CartoDB/support/issues/816
