### ISSUE TITLE
Create a new map from multiple datasets in multiple searches from dashboard

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb#12389]
I'm not fully sure if this is expected or not.

But as opposed to the dialog from "Your maps", where you can select several datasets, as per:

![select-datasets-for-map-your-maps](https://user-images.githubusercontent.com/45346/27551655-93f09ecc-5aa4-11e7-91a5-2f9158a46727.gif)

In the "Your datasets" dialog to create a map, it's not possible to select multiple datasets, as per:

![select-datasets-for-map-your-datasets](https://user-images.githubusercontent.com/45346/27551682-b3ccd936-5aa4-11e7-9f82-f961e271c285.gif)

**Comment by alrocar** [comment]
Stale issue. Closing 👋
