### ISSUE TITLE
Category widget doesn't change to blue when filtered.

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#12394]
### Context
When filtering a category with a widget, the color doesn't changes to blue. 

### Steps to Reproduce

1. Map, category widget, filter it.
2. No blue

### Current Result
No blue

![image](https://user-images.githubusercontent.com/70603/27585700-9b83c968-5b3d-11e7-8185-0b22d3a1bf3f.png)

### Expected result
Blue

**Comment by matallo** [comment]
can't reproduce, do you have the .carto?

![pageshot of untitled map carto 2017-06-03-1742 19](https://user-images.githubusercontent.com/36676/27646560-3726956c-5c29-11e7-8e5a-439c6c0e3282.png)

**Comment by noguerol** [comment]
[McDondalds (on 2017-06-28 at 15.58.41).carto.zip](https://github.com/CartoDB/cartodb/files/1109351/McDondalds.on.2017-06-28.at.15.58.41.carto.zip)

There you go

**Comment by matallo** [comment]
🙇

**Comment by matallo** [comment]
spotted, for some reason at the moment of exporting the map the `styles.widget_style.definition.color.fixed` is set with the `#9DE0AD` color (it should be `undefined`)

already working on preventing this

**Comment by noguerol** [comment]
For the record: widgets with **no custom color** or with **no autostyle** applied should always look green with unfiltered, blue when filtered. For custom color / autostyle the same color is applied.

**Comment by matallo** [comment]
*unless the user has specifically set the green color on purpose (even if the same color as default) which would look green when filtered, too
