### ISSUE TITLE
Error when ordering a dataset by the_geom_webmercator

### ISSUE THREAD

**Issue by Algunenano** [CartoDB/cartodb#12390]
### Context
It happens when browsing a dataset

### Steps to Reproduce
1. Open any dataset
2. Open the SQL console and send any query. The column "the_geom_mercator" will appear (it doesn't appear normally)
3. Use the UI control to order by that column. 

### Current Result
An error appears:
![captura de pantalla 2017-06-27 a las 10 37 57](https://user-images.githubusercontent.com/664253/27578782-6602a72c-5b25-11e7-9283-64f8f45b1eec.png)

### Expected result
The dataset is ordered by the column or that column doesn't appear to be used for ordering.

### Browser and version
Tested with Chrome 59.0.3071.109 for OSX in current carto.com and local installation (4.1.0.r903.73e671bec4-1)

**Comment by rubenmoya** [comment]
Column `the_geom_mercator` is not appearing anymore, so this shouldn't happen anymore, should we close it?

**Comment by Algunenano** [comment]
I think so
