### ISSUE TITLE
Add new analysis modal layout bug

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#12398]
### Context
In the new analysis modal, under "info about analysis" links, the header shows a broken layout:

1. Upper tabs should remain unchanged
2. Analysis img renders without module and is not left-aligned
 

### Steps to Reproduce

1. Click on "info about analysis" on any analysis inside the "add analysis" Builder modal window

### Current Result
Bad layout, no tabs, bad alignment.

![image](https://user-images.githubusercontent.com/70603/27633027-e17c4858-5bfd-11e7-88b5-cdf6d2cfe812.png)

### Expected result
Good layout with the same tabs, img module and correct alignment. 

![image](https://user-images.githubusercontent.com/70603/27632996-c48465fa-5bfd-11e7-870f-a659a0acd65e.png)

![image](https://user-images.githubusercontent.com/70603/27633000-c8fca142-5bfd-11e7-84ee-626c84888e2d.png)

**Comment by nobuti** [comment]
This second step is going to be removed in https://github.com/CartoDB/cartodb/issues/11907. Closing this.
