### ISSUE TITLE
Multiple time-series widgets at the same time

### ISSUE THREAD

**Issue by rjimenezda** [CartoDB/cartodb#12395]
### Steps to Reproduce
1. Add a time series widget for a numeric / date column
2. Add a histogram widget
3. Edit that widget and set the type to time-series
4. GOTO 2

### Current Result
Multiple time series are added, and nothing works as expected.

### Expected result
It's not possible to edit and switch to time series if there's already a time series widget available

### Browser and version
Chrome 59,  4.8.16

### Additional info
![Pics or it didn't happen](https://user-images.githubusercontent.com/446970/27591175-3140a6fc-5b51-11e7-84ab-a3bd3c0774e7.png)

**Comment by xavijam** [comment]
:+1:

**Comment by noguerol** [comment]
I love this one. And also for the record: this is also happening with the pseudo time series in torque maps.

**Comment by rjimenezda** [comment]
I haven't checked, but I think the edit workflow ignores a lot of the restrictions there are in place.

**Comment by xavijam** [comment]
We should not allow the user to change a widget to a time-series type when there is already one selected.

**Comment by saleiva** [comment]
That solution can be tricky from the user feedback point of view. How are we planning to inform users then?

**Comment by rjimenezda** [comment]
Hiding the time-series icon would be simple, but I think it would cause confusion.

Since the widget edition has no 'confirm' action, we should probably disable the widget type button. Visually bring the opacity down or make the icon Black & White, or both. We should probably show a tooltip too.

**Comment by xavijam** [comment]
I agree with @rjimenezda, we should turn it into a disable state + a tooltip.

**Comment by saleiva** [comment]
@urbanphes, @josecruz  fancy taking a quick look?

**Comment by urbanphes** [comment]
I agreed with this kind of solutions:

If we have a TimeSeries widget added we can remove the option on the carrousel for change by TimeSeries. This way we avoid this kind of problem that somebody can change a histogram widget by TimeSeries.

**Comment by noguerol** [comment]
Let's go for it then

**Comment by xavijam** [comment]
If you have time, please @Jesus89, take care of this.

**Comment by Jesus89** [comment]
I have also this ones:

1. It would be nice to create a Widget (continue) with `Enter` (You can delete it with `Enter`)
2. (Bug) Creating any (Category|Histogram|Formula) widget after a TimeSeries do not refresh the map panel size

![multi-widgets](https://user-images.githubusercontent.com/2227572/29704377-dca5402e-8979-11e7-81d7-fd25bba3164e.gif)

**Comment by Jesus89** [comment]
I think we should show a message if there is already a TimeSeries when a new TimeSeries is created. Something like: "Your current TimeSeries would be replaced" ?

cc @urbanphes @josecruz

**Comment by Jesus89** [comment]
Also found:
- When the AddWidgetView is created, it is not focused so `Enter` key refreshes the view (init, render, render) until it is focused. I think this is a bug
- After creating a TimeSeries, the selected radiobutton is not reset for future AddWidgetViews

**Comment by josecruz** [comment]
Hey @Jesus89 nice catch!

Due we're not showing those "yes/no" warnings (that would require an extra screen) I'd keep it simple by showing on the infobox something like this:

![image](https://user-images.githubusercontent.com/596509/29708704-e9cd5678-8989-11e7-885a-07e4dd2ce32a.png)

**Comment by Jesus89** [comment]
Now it shows: "Widget succesfully added". Should the new message replace this one @josecruz?

May be a better message would be: "Widget succesfully replaced" ?

**Comment by noguerol** [comment]
Hey guys, didn't we agree that when one time series is active there is no way for adding / replacing it? That is why we remove the TS option from the carrousel in that scenario, right?

@Jesus89 nice catches! please report them on different tickets.

**Comment by Jesus89** [comment]
Ok! I will create a new ticket for the text replacement in the notification :+1: 
I have already implement the `Enter` fix :P

**Comment by noguerol** [comment]
Why do we need a replacement text for?

**Comment by Jesus89** [comment]
@noguerol this is the new issue: https://github.com/CartoDB/cartodb/issues/12653

**Comment by nobuti** [comment]
Closed by #12654.
