### ISSUE TITLE
Issue with user mover and raster data

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#12391]
During #4960, we discovered the following issue withg `pg_restore` and rasters: http://trac.osgeo.org/postgis/ticket/2485

_Note: this error looks like this for us:_

```
pg_restore: [archiver (db)] Error while PROCESSING TOC:
pg_restore: [archiver (db)] Error from TOC entry 4715; 0 697887 TABLE DATA o_2_q37866 cartodb_user_9be99c95-2fa3-4c2a-9e64-60282a40874d
pg_restore: [archiver (db)] COPY failed for table "o_2_q37866": ERROR:  function st_bandmetadata(public.raster, integer[]) does not exist
LINE 1: ...(round(nodatavalue::numeric, 10))::numeric[] FROM st_bandmet...
^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

It was solved in postgis 2.3.0 ([changelog](https://github.com/postgis/postgis/blob/svn-trunk/NEWS#L67)), but in postgis 2.2.2 ([changelog](https://github.com/postgis/postgis/blob/svn-trunk/NEWS#L111)) there is a hacky script to fix this, see section 10.1 in http://postgis.net/docs/manual-2.2/RT_FAQ.html#faq_raster_data_not_restore-%20#3426,%20failing%20POINT%20EMPTY%20tests%20on%20fun%20architectures

For the migration, I ran the following script after creating the database and extension, but before importing the data:
```
ALTER FUNCTION _raster_constraint_pixel_types(raster) SET search_path=pg_catalog,public,postgis;
ALTER FUNCTION _raster_constraint_nodata_values(raster) SET search_path=pg_catalog,public,postgis;
ALTER FUNCTION _raster_constraint_out_db(raster) SET search_path=pg_catalog,public,postgis;
ALTER FUNCTION _raster_constraint_info_regular_blocking(name, name, name) SET search_path=pg_catalog,public,postgis;
ALTER FUNCTION _overview_constraint(raster, integer, name, name, name) SET search_path=pg_catalog,public,postgis;
```

Although this works, it would be great if we could use the official script.

In order to be able to run that script "after creating the database and extension, but before importing the data" you can add a `sleep(10)` [between those steps](https://github.com/CartoDB/cartodb/blob/eac21689505ef78d0bdcc7e8436ae99494891567/services/user-mover/import_user.rb#L513) (after line 513).

**Comment by skgsergio** [comment]
For the https://github.com/CartoDB/tech-ops/issues/252 issue, I just waited till' the importer created the user database and in that moment I loaded the script postgis says in their FAQ:

```
cartodb_user_c0d3271d-5dce-49c3-9c9f-04bc09543a5c_db=# \i /usr/share/postgresql/9.5/contrib/postgis-2.2/rtpostgis_proc_set_search_path.sql
DO
```

**Comment by juanignaciosl** [comment]
This happened again: CartoDB/tech-ops/issues/292

@skgsergio , did you just monitor the log and when the database was created you connected to it in order to run the script, or did you run the steps manually?

**Comment by javitonino** [comment]
I wrote https://github.com/CartoDB/cartodb-management/issues/5080 as a more generic ticket for user mover problems, since it turns our many of them are related.

**Comment by javitonino** [comment]
It seems we are trying to move forward with a proper fix in postgis, so parking this for now.

**Comment by javitonino** [comment]
This was already solved
