### ISSUE TITLE
Country dropdown should be mandatory in postal code georeference

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#12403]
### Context
Postal codes georrrrreference has an optional `Country` input field but the analysis won't resolve without it so it's mandatory. We should then remove the checkbox and validate the field as mandatory.

![image](https://user-images.githubusercontent.com/70603/27650823-74e2cf3a-5c36-11e7-9fb1-e07e5f320069.png)

### Steps to Reproduce

1. Georeference with postal codes
2. Don't select any country
3. Run the analysis

### Current Result
BOOM, error.

### Expected result
The analysis should not be validated to be ran until a country is provided.

**Comment by matallo** [comment]
fixd in https://github.com/CartoDB/cartodb/issues/12334

closing then
