### ISSUE TITLE
Deleting a dataset field with a linked widget lead to weird behaviour

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb#12417]
### Context
Decoupled embed / Builder widgets when the column used is deleted or renamed

### Steps to Reproduce
1. Create a map with  a layer, with a query like
```sql
SELECT
*,
cartodb_id as myfield
FROM mydataset
```
2. Create any widget linked to that field
3. Publish and check the embed
4. Go back to Builder
5. Change the layer query to 
```sql
SELECT
*,
cartodb_id as mynewfield
FROM mydataset
```
so the column is now `mynewfield` instead of `myfield`
6. Update the embed
8. Go to embed and refresh the page

### Current Result
The widget has disappeared from Builder, because `myfield` is not there anymore, but it's still there in the Embed. And you can't delete or edit it, because it's not in Builder!!

**Workaround:** force-refresh (refreshing cached data) Builder and publish again

### Expected result
Delete the widget both in Builder and Embed views

### Browser and version
any

### .carto file
any

### Additional info
none

**Comment by ramiroaznar** [comment]
Now there is a `column "field name" does not exist. Both in BUILDER and embed.

![image](https://user-images.githubusercontent.com/5215798/33389129-2a38ddc4-d532-11e7-9b7d-1efd5a0c6d50.png)

Closing this issue. Please @AbelVM feel free if this is happening again.

**Comment by AbelVM** [comment]
That's a side effect, so the issue is not fixed at all, IMHO

**Comment by ramiroaznar** [comment]
The widget is not disappearing anymore and gives you a message error. So this is another different issue. AFAI understand you are suggesting that widgets adapt to changes in the column names. Don't know how that is a good decision (you can change more than the name, add new fields... when changing the SQL...), anyway let's keep it open then.

**Comment by ivanmalagon** [comment]
I've followed the STR with the current version in production and the widget does not dissapear from Builder, so you can delete it or change its configuration.

Does this change the expected result or the scope of this issue?

**Comment by AbelVM** [comment]
F U Stale Bot :joy:
