### ISSUE TITLE
Use ::outline for line properties in CartoCSS for polygons

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb#12411]
Context: https://github.com/CartoDB/cartodb/issues/7723.

In order to speed up and make the styles compatible between vector and raster, we need to use the `::outline` approach for the CartoCSS `line-*` properties.

However, the current approach only allows to use flat styles, see https://github.com/CartoDB/cartodb/blob/ed553a8b34fedbb0f9a7ab429615b437ad6c9fb3/lib/carto/styles/polygon.rb + https://github.com/CartoDB/cartodb/blob/ed553a8b34fedbb0f9a7ab429615b437ad6c9fb3/lib/carto/styles/style.rb#L32.

**Comment by mayoral** [comment]
@rochoa: Do we plan to support more nesting in the future? Something like:

``` css
my_class {
  foo: 'bar';
  ::outline {
    bla: 'bla';
    second_level {
      something: 'wadus';
      third_level {
        another: 'thing';
      }
    }
  }
}

Or one level of nesting (to support outline) is enough?

**Comment by xavijam** [comment]
I don't know if it is a common thing (I don't think so), but it could be possible so I'd try to cover as many cases as possible. But @rochoa knows more than anyone.

**Comment by rochoa** [comment]
I don't think so.

How does it impact your changes? Is it way more complicated to have several levels than one?

**Comment by rochoa** [comment]
You can always workaround it with:

```css
#layer {
  polygon-fill: red;
  ::outline {
    line-color: white;
  }
  ::outline-override {
    ...
  }
}
```

Keep it simple for now, just one level.

**Comment by mayoral** [comment]
@rochoa if we want to support multiple levels of nesting, the best option is to parse these levels recursively. If we only need to support the first level (for the properties inside `::outline` we can take a much simpler approach).

Let's go for one level for now then. We always have time in the future to add the recursion if needed :)

Thanks!

**Comment by juanignaciosl** [comment]
Marked as blocked because of the need for synchronizing merge with another PR ([see @xavijam comment about this in the PR](https://github.com/CartoDB/cartodb/pull/12444#issuecomment-314138829)).

**Comment by xavijam** [comment]
Ready to merge frontend part, what about tomorrow morning guys? 🙏

**Comment by juanignaciosl** [comment]
@xavijam I just did the acceptance of the second backend issue, I think we're ready as well. Could you please check that all issues are done? AFAIK only #12411 and #12410 were needed from our side.

**Comment by xavijam** [comment]
Yes, only those are necessary from the Backend side, so great! 💃
