### ISSUE TITLE
Use ::outline for line properties in CartoCSS for polygons

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb#12412]
Context: https://github.com/CartoDB/cartodb/issues/7723.

In order to speed up and make the styles compatible between vector and raster, we need to use the `::outline` approach for the CartoCSS `line-*` properties.

However, the current approach only allows to use flat styles, see https://github.com/CartoDB/cartodb/blob/ed553a8b34fedbb0f9a7ab429615b437ad6c9fb3/lib/assets/core/javascripts/cartodb3/editor/style/style-converter.js.

There could be more places where we need to apply the same approach, as in: https://github.com/CartoDB/cartodb/blob/ed553a8b34fedbb0f9a7ab429615b437ad6c9fb3/lib/assets/core/javascripts/cartodb3/data/camshaft-reference.js.

**Comment by xavijam** [comment]
We should block this one until https://github.com/CartoDB/cartodb/issues/12413 is also solved.

**Comment by xavijam** [comment]
Deployed!
