### ISSUE TITLE
Update the copy of the 'Join columns from 2nd layer' analysis

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#12418]
We want to update the copy of this analysis to make it more easily understandable for non-dev users and more cohesive with other similar analysis. 

[Design ticket](https://github.com/CartoDB/design/issues/740#issuecomment-311339494)

![slice](https://user-images.githubusercontent.com/16247628/27586553-1033a1e0-5b41-11e7-87fd-9f59c28a1c3b.png)

**Comment by xavijam** [comment]
Response team? @noguerol

**Comment by Jesus89** [comment]
What about the "Append" and "Intersect" tooltips? @arianaescobar 

![Append](https://user-images.githubusercontent.com/2227572/30203593-d0f3a66c-9482-11e7-8fb8-b7e5e00abe48.png)

![Intersect](https://user-images.githubusercontent.com/2227572/30203597-d5bd6b88-9482-11e7-95de-6817bdaf9fa8.png)

**Comment by nobuti** [comment]
Closed by #12762.
