### ISSUE TITLE
Deep-Insights.js AutoStyle integration and ::outline polygon properties

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb#12413]
Context: https://github.com/CartoDB/cartodb/issues/7723. For some CartoCSS polygon properties, we want to use them within a `::outline` scope.

Once the auto-style part of Deep-Insights decides what is the best CartoCSS, it sets it, and Builder has to understand it to reflect that into the interface components. This is half broken right now, as some of the properties are behind `mapnik::geometry_type` filters.

We might need changes in the way detect `::outline`d properties as we rely on regular expressions, so we can reflect them in the Builder interface. See https://github.com/CartoDB/cartodb/blob/ed553a8b34fedbb0f9a7ab429615b437ad6c9fb3/lib/assets/core/javascripts/cartodb3/deep-insights-integrations.js and https://github.com/CartoDB/cartodb/blob/ed553a8b34fedbb0f9a7ab429615b437ad6c9fb3/lib/assets/core/javascripts/cartodb3/editor/style/style-definition-model.js#L39 for context.

However, we should take this as an opportunity to change the way the Deep-Insights – Builder integration works. So instead of leaving the room open to change the CartoCSS from Deep-Insights directly, making Builder responsible for understanding all the changes to reflect them on the interface, we should define a model to change the style from outside so the interface is easier to update and the CartoCSS is still easy to generate.

Also important, there is an [existing PR working on big changes in `deep-insights-integrations.js`](https://github.com/CartoDB/cartodb/pull/12265) wich will conflict with any change done in this area.

**Comment by xavijam** [comment]
Deployed!

**Comment by alonsogarciapablo** [comment]
👏

**Comment by rochoa** [comment]
🎉 !
