### ISSUE TITLE
custom markers with Torque maps throw errors

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#12422]
### Context

using custom markers with Torque maps are throwing errors in the Dev Tools console

```
Uncaught TypeError: Cannot read property 'value' of undefined
```

I don't think we're supporting custom markers with Torque maps, but it's possible to do so with the CartoCSS editor panel

this is happening in the next embed map
https://ouestfrance.carto.com/u/ouest-france/builder/bba4252d-0f3a-4045-ba8a-b6eef835e018/embed

**Comment by xavijam** [comment]
Hey, what about this issue?

**Comment by rjimenezda** [comment]
So...I can't reproduce it on my maps (haven't tried too hard) but I know _why_ it happens.

CartoCSS has something like this in the parsing code:

`var value = def.rules[u].value.value[0].value[0].value.value;`

To locate the URL of the marker. On most maps that works but something in that train map's css produces a different structure.

I have a function that does it more generically, but my concern is, that the code is [3 years old](https://github.com/CartoDB/carto/commit/f91ac22bfc924fa6469e3a14dfe3c01f194a4261), and it doesn't seem to break that often. Should we change it?

Sorry for the ping, but I'd like some input @xavijam @matallo

**Comment by xavijam** [comment]
I don't think it is the right moment for touching that. If it is not happening by default with our Builder UI I'd prioritize other things first.
