### ISSUE TITLE
Notifications are not displayed if cartodb_com_hosted is true

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#12421]
### Context

I think that this should affect OS and onpremises installs.

### Steps to Reproduce

1. Set `cartodb_com_hosted` configuration parameter at app_config.yml to `true`. That means "this is self hosted, a local installation, not the CARTO SaaS".
2. Go to the dashboard

### Current Result

Notification icon next to the avatar doesn't show up (it's hidden, as "guides" and "documentation" are).

### Expected result

Notification icon appears.

### Additional notes

[Caused by this check](https://github.com/CartoDB/cartodb/blob/f746eba8c0dd1d856810a66ea0bcb935ffad0113/app/views/admin/shared/_private_header.erb#L31).

cc @xavijam @danicarrion

**Comment by xavijam** [comment]
This is pure frontend, taking care of it.

**Comment by xavijam** [comment]
Deployed!
