### ISSUE TITLE
Async select editor

### ISSUE THREAD

**Issue by nobuti** [CartoDB/cartodb#12427]
### Context

In #12386, we discovered that the component is rendered twice if the user is editing the form. This is because of the use of the `setSchema` we do, with the fact we need to wait to the queryGeometryModel to be fetched before to request all the regions. This is working but is inefficient, two renders and duplication of some requests, and annoying, it provokes some flickering in the UI.

So in order to fix this properly, we need to revamp the select editor to make it async-aware, in charge of auto render when the collection is fetched, avoiding the whole form's render.

Select editor is extensively used across the Builder, that's the reason to tackle this issue independently.

**Comment by xavijam** [comment]
Merged into main branch! 💃
