### ISSUE TITLE
[Data observatory] Color of the select options is not right

### ISSUE THREAD

**Issue by nobuti** [CartoDB/cartodb#12426]
This comes from #12386:

@saleiva commented:
> hi guys, there is something I've spotted while doing acceptance.
> Options on any dropdown should be blue (for example in the region dropdown they are black now).

Waiting for @urbanphes clarification about the measurements dropdown.

**Comment by urbanphes** [comment]
Yes, It is Blue 👍

**Comment by xavijam** [comment]
Merged then!
