### ISSUE TITLE
Improving sources on widget options and list

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#12441]
Coming from this issue https://github.com/CartoDB/cartodb/issues/9956. The idea is to also add the source type to the sources elements in both the widget options header...

<img width="567" alt="screen shot 2017-07-06 at 15 00 55" src="https://user-images.githubusercontent.com/16247628/27913965-ffc3b1e2-6261-11e7-9481-cd7ddd447cfc.png">

...and the widgets list.

<img width="632" alt="screen shot 2017-07-06 at 14 54 53" src="https://user-images.githubusercontent.com/16247628/27913977-0c5fda84-6262-11e7-9d13-0dd2e3ad48bc.png">

And as a plus, lowering the source element on the header 5px down

![source](https://user-images.githubusercontent.com/16247628/27914044-4bbab96a-6262-11e7-9d40-7ff31b41b801.gif)

**Comment by xavijam** [comment]
Wouldn't you add the delete icon in the widget item?

**Comment by arianaescobar** [comment]
That's a nice idea, but we should think it through. Would you open a ticket for us in design?

**Comment by xavijam** [comment]
>  That's a nice idea, but we should think it through. Would you open a ticket for us in design?

On my way!

**Comment by arianaescobar** [comment]
This is getting developed in another ticket :)
