### ISSUE TITLE
Pixel Aggregation button 

### ISSUE THREAD

**Issue by csobier** [CartoDB/cartodb#12442]
@saleiva , just noticed this weirdness today (which is definitely new behavior since I know this appeared fine before). The PIXEL button appears to have some extra junk on top of it.

- From the LAYERS pane, click on a map layer.
- From the STYLE tab, scroll and select PIXEL.

Notice the button?

![image](https://user-images.githubusercontent.com/13319925/27919540-ee699406-623f-11e7-808f-600e4476efbd.png)

**Comment by saleiva** [comment]
IMO response team.
cc/ @noguerol

**Comment by xavijam** [comment]
Please, could you provide more info? Browser and version, OS,...
I've tested it in my account with Chrome and it is being displayed properly.

**Comment by csobier** [comment]
Browser: Chrome, Version 59.0.3071.115 (Official Build) (64-bit)
Mac OS: XEL Capitan version 10.11.6 (15G31)

**Comment by ivanmalagon** [comment]
Fix deployed to production.

@csobier Can you check that the icon now is well displayed on your browser? Thanks

**Comment by csobier** [comment]
Looks good, back to normal. Thank you!
