### ISSUE TITLE
Edit field in Custom Value dropdowns

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#12451]
### Context
Based on @ztephm comments on https://github.com/CartoDB/cartodb/issues/11903 we need to enable a field edit feature in the Custom Value dropdowns that enables users to edit the field and not only rewriting it from scratch. 

![image](https://user-images.githubusercontent.com/70603/28068666-ca3c7750-6646-11e7-807c-66affae11897.png)

### Steps to Reproduce

1. Look for a Custom Value dropdown (e.g. in infowindows)
2. Try to edit a previous value

### Current Result
No way to edit the field without rewriting it entirely

### Expected result
Be able to edit the content, like, for example, in the table view.

**Comment by xavijam** [comment]
Don't you think it should start in design, trying to find a way to do it, and then move it to development?

**Comment by xavijam** [comment]
Also I have doubts about if it should be tackled in the response team...

**Comment by noguerol** [comment]
This is a bug, as the component was originally designed to be editable. But summoning @urbanphes so he can shed more light. 

cc @saleiva

**Comment by saleiva** [comment]
There is nothing else to design. When you've entered a custom value, you should be able to edit it by editing the content of the input directly. That would be reflected on the dropdown as well.

**Comment by xavijam** [comment]
When you enter a custom value and it is applied, it is not a custom value anymore!. So it is not that easy to edit it.

**Comment by noguerol** [comment]
For the dropdown component clicking on the already written value an filling the text field with it (so you're able to edit it) should work. That said, I can't find a reason for using that component in Geometry edition; you should be able to directly edit the value in the text field itself, right?

**Comment by saleiva** [comment]
@noguerol remember that functionality of autocompleting is very useful when working on categorized maps – which is quite common when creating datasets from scratch

**Comment by noguerol** [comment]
True. Then we can fix the component as I said.

**Comment by rjimenezda** [comment]
On production
