### ISSUE TITLE
403 Password Map Error - Iframe Embeds

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#12469]
Directly copied from https://github.com/CartoDB/support/issues/849 and also based on https://github.com/CartoDB/support/issues/848

----

Context

As reported by @micagm here, password protected maps embedded on a webpage in an iframe error out to a 403 page when the password is entered.

The error was reproduced in Internet Explorer 11 browser on a Windows 7 virtual machine.

Steps to Reproduce

Create a Builder map

Password protect the map and publish

Embed in an iframe on a webpage

In IE 11 / Win 7 environment, enter the password of the map embedded on the webpage

403 error page will occur

![image](https://user-images.githubusercontent.com/70603/28219491-78449f54-68bc-11e7-8bec-6b87faa3fe2e.png)

Same error does not occur from the direct embed map link after entering the password

![image](https://user-images.githubusercontent.com/70603/28219496-80423ff4-68bc-11e7-9e17-5fc10f6bb62e.png)

Map URL tested with. Password is "map".

No error messages in the console when tested.

**Comment by micagm** [comment]
Any update/idea when this will be fixed @noguerol ? It's directly affecting our client RATP ($18k ARR).

**Comment by noguerol** [comment]
Prioritized
