### ISSUE TITLE
Time-series widget not saving filter state in embed maps

### ISSUE THREAD

**Issue by rubenmoya** [CartoDB/cartodb#12463]
### Context
When a use changes the filters in embed maps, the state is saved in the url. In the histogram widget, if you change the filter, copy the url and open it in another window, it keeps the filter, with the time-series widget, in the other hand, it's not keeping it.

### Steps to Reproduce
1. Create a time-series widget and publish it
2. Visit the embed map and filter the widget
3. Copy the URL and open it in another tab/window

### Current Result
The filter is not applied

### Expected result
The filter is applied

### Browser and version
Chrome Version 59.0.3071.115

### Additional info
It seems only happens with time-series widget

**Comment by ramiroaznar** [comment]
This is already fixed!
