### ISSUE TITLE
Change style of the "styles reset" message and prevent from showing the "None" aggregation bucket

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#12476]
### Context

I had a curious behavior this weekend on a map, which I sadly can't reproduce but I do have a screenshot of what happened. 

Apparently, my layer styling was reset and I got the following message and UI state as a notification.

### Current Result

![screen shot 2017-07-14 at 21 27 32](https://user-images.githubusercontent.com/16247628/28260897-58d9a056-6add-11e7-862a-ebe2bbf9d821.png)

### Expected result

Two things: 

1. We should find that copy and make that message appear as an infobox, which would be the correct styling for that type of message. 

2. We shouldn't show that "None" aggregation bucket and instead, it should've fallen back into the default points aggregation.  

### Browser and version

Chrome Version 59.0.3071.115 (Official Build) (64-bit)

### Additional info

Sorry that I can't give you more information 😥  but if there's something else I can help with, let me know!

**Comment by ramiroaznar** [comment]
Hey @arianaescobar can you give us a better STR or .carto file? If not we would need to close this issue.

**Comment by arianaescobar** [comment]
Hey @ramiroaznar, 

As I said on the ticket, I couldn't reproduce it. But I'm guessing we can search the code for that copy and find out where it is to change it.
