### ISSUE TITLE
[vector] vector=true is not working on embeds

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#12478]
STR:
- go to an embed with vector=true in the url like this. https://javi.carto.com/builder/74bb971d-5554-459a-b67d-92834dec63a0/embed?vector=true
- open chrome console and print `vizJSON.vector`, it should be true

When adding the flag vector=true the viz.json should contain `vector:true` so carto.js tries to render the map with vector.

Checking the code looks like it's not doing it: https://github.com/CartoDB/cartodb/blob/master/app/controllers/carto/builder/public/embeds_controller.rb#L67

I also think when `vector` param is present should take precedence over the feature flag: the reason is that would allow to test user maps. Right now is just setting that to nil

**Comment by javisantana** [comment]
@kevin-reilly again, a quick fix that should give us the ability to test vector maps

**Comment by juanignaciosl** [comment]
This was the old behavior for that flag. When the new vector approach was implemented that was removed. We'll bring it back.
