### ISSUE TITLE
Histogram UI: Do not show "NULL ROWS" value if it is not received

### ISSUE THREAD

**Issue by Algunenano** [CartoDB/cartodb#12477]
### Context
When working in query optimisations sometimes it is too expensive to calculate the number of NULL rows (for the value it gives, that is), so we might stop returning the value it in certain cases (big datasets).
Here is an example of a response without it:
[response.txt](https://github.com/CartoDB/cartodb/files/1151966/response.txt)

It'd great if, instead of showing 0 as the value, the item was hidden / not showing.

### Current Result
Right now the UI shows "0 NULL ROWS":
![null_rows_current](https://user-images.githubusercontent.com/664253/28260544-d4f74df2-6adb-11e7-9ec6-0f4cf1771521.png)

### Expected result
![null_rows_expected](https://user-images.githubusercontent.com/664253/28260556-db14aff4-6adb-11e7-9cf5-d95bf45b3a70.png)

### Browser and version
*Tested with chromium 59.0.3071.115 and firefox 54.0.1*

**Comment by nobuti** [comment]
PRs open [here](https://github.com/CartoDB/deep-insights.js/pull/563) and [here](https://github.com/CartoDB/cartodb.js/pull/1702).
