### ISSUE TITLE
Sidebar UI tweaks

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#12479]
### Context

Our current sidebar on production has a few UI issues: 

- [x] The pencil icon
- [x] The margin-top of the marker
- [x] The marker proportion (between the inner circle and its halo)
- [x] The margins of the pencil icon within its own box 

### Current Result

![screen shot 2017-07-17 at 11 41 47](https://user-images.githubusercontent.com/16247628/28263147-095e4d70-6ae6-11e7-850a-399e54f27ece.png)

![screen shot 2017-07-17 at 11 44 30](https://user-images.githubusercontent.com/16247628/28263342-a8654f22-6ae6-11e7-87d1-f44055ef90b7.png)

### Expected result

- Correct pencil icon: [pencil.svg.zip](https://github.com/CartoDB/cartodb/files/1152157/pencil.svg.zip)
- Marker's proportion at that size: Halo is 32x32px while the inner circle is 11x11px 
- Marker's margin top should be 20px, instead of 24px
- Pencil icon's margins within its own box: 8px at all sides

**Comment by ivanmalagon** [comment]
For new hires?

**Comment by Jesus89** [comment]
Hi @arianaescobar.

Now Pencil icon's box is 24px. Do you mean _4px_ margin at all sides?
Also, I can not visualize the attached SVG file. Could you add it with [this format](https://github.com/CartoDB/CartoAssets/blob/master/icon-font/svgs/icon-font_67_Pencil.svg?short_path=281770c)?

Thanks.

**Comment by Jesus89** [comment]
New requirements (from @josecruz):

- [ ] Sidebar icons should be 16x16px
- [ ] Sidebar separation between marker and icon should be 48px
- [ ] Sidebar color is: #1785FB (yep, we were using a wrong blue)

![image](https://user-images.githubusercontent.com/596509/29516397-7dcba180-8670-11e7-9642-767c79b02a15.png)

**Comment by xavijam** [comment]
In production!
