### ISSUE TITLE
Cursor should change to hand cursor throughout the whole slider

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#12499]
Right now the hand cursor only appears on top of the dragging circle, but since you can click throughout the whole slider, the hand should always appear. 

Like this:  

![screen shot 2017-07-21 at 15 07 30](https://user-images.githubusercontent.com/16247628/28464624-58254bb4-6e26-11e7-93c2-63ed82c5d91d.png)

**Comment by ivanmalagon** [comment]
For new hires.

**Comment by rubenmoya** [comment]
In production 🚀
