### ISSUE TITLE
Update dialogue when receiving error messages

### ISSUE THREAD

**Issue by alexsroth** [CartoDB/cartodb#12497]
### Context

When users get an import error, the dialogue that pops up instructs them to email support@carto.com, and send us the error code they see. 

I would like this to be updated to say send us the error code **AND their username**. This is a quick fix that will make the support process more efficient by having them confirm what account they are using right away, as the email addresses being used to contact us is not always tied to the account they found the error in. 

An additional enhancement could be bringing a search feature to superadmin to be able to search the unique error codes that are generated.

### Steps to Reproduce

1. Go to the dataset dashboard
2. Click to add a new dataset
3. Select ArcGIS Server
4. Enter any URL, hit submit, and then connect to dataset
5. When the error message pops up, click to show more

### Current Result

![screen shot 2017-07-20 at 11 22 49 am](https://user-images.githubusercontent.com/29546714/28426015-ee141cc8-6d3f-11e7-9538-bc49a2c68838.png)

### Expected result

Add a new line that asks the users to include the username of the account where the error happened in their email to support.

**Comment by noguerol** [comment]
@juanignaciosl possible, right?

**Comment by juanignaciosl** [comment]
Of course.
