### ISSUE TITLE
Placeholder text change in label settings 

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#12498]
`Select a attribute` (which has a typo, because it should be "an") should really be called `Select a column` since the label of that input is Column. 

<img width="506" alt="screen shot 2017-07-21 at 14 59 57" src="https://user-images.githubusercontent.com/16247628/28464397-4c3d1e7c-6e25-11e7-872c-ba8e2fb48b8b.png">

**Comment by ivanmalagon** [comment]
For new hires

**Comment by nobuti** [comment]
Closed by #12611.
