### ISSUE TITLE
Histograms are almost unusable in mobile

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#12504]
### Context
After the last changes in the histograms, they've become very hard to use in mobile devices.

### Steps to Reproduce

1. Go to any map with histograms from your phone
2. Start filtering using the histogram

### Current Result
Interaction is quite bumpy. Whenever you try to filter, you move the widgets band, and it's also very hard change the range of the filter

### Browser and version
Tested with Android and Chrome

cc/ @noguerol @kevin-reilly

**Comment by rubenmoya** [comment]
I had a look at it, seems like you have to tap exactly in the white bar to move it, which make sense, but if you have big fingers like me, you end up tapping in the sides which leads to that weird behaviour.

I'm not sure what the fix could be, because if we increase the area were you can tap you won't be able to select the next bin, for example. The only thing I can think of is making the tooltips draggable.

**Comment by rjimenezda** [comment]
This one's interesting. I noticed this right after we deployed the changes to look & feel of handles and added the tooltips. It got fixed immediately (a month ago or so), but it got caught in one the long deep-insights pull requests, which got merged one day after sergio reported it.

https://github.com/CartoDB/deep-insights.js/pull/561

I've checked and the horizontal scroll definitely does not happen. I also suffer from sausage fingers and a bigger handle wouldn't hurt, but I still could change the filter, or move the window.

I'll move this to acceptance and ping an _innocent hand_ 

@noguerol would you kindly test this on production with a phone? This map for example

https://team.carto.com/u/roman-carto/builder/4b71ac86-3ad8-11e7-b939-0ecd1babdde5/embed

**Comment by noguerol** [comment]
Tested that map, they're working well at least in Safari and Chrome on iPhone, so maybe is an Android thing.

We do however have a clipped label in the time series:

![df366da0-ec75-4082-a113-943575169b13](https://user-images.githubusercontent.com/70603/29083407-e93e918c-7c68-11e7-8ecd-bc2a5923e65a.PNG)

**Comment by rjimenezda** [comment]
Matallo's going to deploy the responsive improvements to the time series, so it should fix the clipping.

I tested on two Androids and it works, so maybe it was just a matter of timing.

**Comment by noguerol** [comment]
Closing this then, thanks mates.
