### ISSUE TITLE
Errors creating common data for viewer signups

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#12516]
https://rollbar.com/carto/CartoDB/items/24122/
during the creation of this user: https://rollbar.com/carto/CartoDB/items/8630/occurrences/28193048834/

I was not able to reproduce. The thing that seems to happen is that the user was created as a viewer (following an invitation to join org as a viewer seems like the way). We should take a look and see if we can reproduce this after fixing https://github.com/CartoDB/cartodb/issues/12514

Tentative STR:
1. As an org admin, invite a new user to join the org as a viewer
2. In a different browser, join the organization using the provided invitation

Check the logs, there should be no errors regarding common data.

**Comment by juanignaciosl** [comment]
Checked this after fixing #12514.

There are 4 ways to create a viewer user:
- [X] Organization settings.
- [X] Invitation.
- [X] Superadmin.
- [X] EUMAPI.

Neither creating the user nor login and opening the dashboard triggers those errors. Closing for the moment.
