### ISSUE TITLE
Preview dataset is not working anymore

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#12513]
A JS error is appearing:

![screen shot 2017-07-26 at 10 04 12](https://user-images.githubusercontent.com/132146/28610773-cfce78d6-71e9-11e7-91c4-d4cffeff894f.png)

**Comment by juanignaciosl** [comment]
This only happens for users with `vector_vs_raster` flag enabled. On it.

**Comment by rubenmoya** [comment]
In production 🚀
