### ISSUE TITLE
Allow image (only) for asset loading at Editor

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#12522]
### Context

Testing #12521.

### Steps to Reproduce

1. Add a png to your Dropbox account.
2. Click connect to Dropbox.

### Current Result

Images are listed for importing.

### Expected result

Images should not be listed for importing.

### Additional info

Connectors should be able to get images, for assets, but not for dataset importing.

PS: it'd be nice if, given the new API, we could fetch all possible datasets in a single request, instead of iterating through file formats.

**Comment by Algunenano** [comment]
As part of https://github.com/CartoDB/support/issues/1192 I've removed the png and jpg/jpeg files from the Dropbox import. After seeing this issue I wonder where is the assets imports taking place? Could it have been broken by my changes (no longer showing images)?

cc/ @juanignaciosl

**Comment by juanignaciosl** [comment]
Damn...

I CR'd your fix, which was nice, and checked that we don't support uploading assets, neither for avatars, nor organization icons or Builder... but I overlooked Editor :( Editor allows uploading assets from Dropbox. We should fix that :(

**Comment by juanignaciosl** [comment]
cc @ramiroaznar to move this to RT.

The current issue is "allow image (only) for asset loading at Editor".

**Comment by Algunenano** [comment]
This is currently worked as expected, at least in local and staging machines.

Dropbox imported works using `cartodb/lib/assets/javascripts/cartodb/common/dialogs/map/image_picker/dropbox_view.js` which limits the filetypes to `acceptFileTypes:  ['png','svg','jpeg','jpg'],`. BTW, this Chooser it's what I proposed for Builder in #13259.

@juanignaciosl or @ramiroaznar  Can you confirm it's working for you too?

**Comment by juanignaciosl** [comment]
Oh, you're right! This should be closed, then.

**Comment by ramiroaznar** [comment]
:boom:
