### ISSUE TITLE
Animation issues with filtered histograms

### ISSUE THREAD

**Issue by rjimenezda** [CartoDB/cartodb#12527]
Might be related to #12480

This doesn't always happen, but if you filter a histogram while there's a time series, the playback range is limited to where the data is. This might be acceptable, although I don't think it used to behave like this. Problem comes up when you clear the filter, playback might get out of bounds.

![bug](https://user-images.githubusercontent.com/446970/28667998-384e1b02-72ce-11e7-84e3-15e974f278ba.gif)

**Comment by xavijam** [comment]
I feel it should be fixed with last changes from aggregation guys @rubenmoya @ivanmalagon.

**Comment by rjimenezda** [comment]
Currently digging my way out of this, I'm quite close to the cause of the problem.

If someone complains about this, a temporary fix is to resize the browser window.

**Comment by rjimenezda** [comment]
Fix:

https://github.com/CartoDB/cartodb.js/pull/1685/commits/fe8daaf2b0369b96030d40cbea38a1e832be3022

**Comment by rubenmoya** [comment]
I was trying to do the acceptance and I found this: #12567

**Comment by rubenmoya** [comment]
Seems like the last issue only happens with some datasets. I used a different one and tried to reproduce this but I can't, so let's deploy it :)

Also, I think the changes are already in the time-series-aggregation branch.

**Comment by xavijam** [comment]
Yep, so... going there!

**Comment by xavijam** [comment]
Deployed!
