### ISSUE TITLE
Display bug in list of files to connect from Dropbox

### ISSUE THREAD

**Issue by mayoral** [CartoDB/cartodb#12525]
### Context

When selecting a file to import from a Dropbox connected account, the last two items are shown together instead of having an space like the rest of the listing.

### Steps to Reproduce

1. Select "New map".
2. From the "Connect dataset" option, select Dropbox and wait until it lists all the files in the account.
3. Scroll to bottom, until you can see something like:

![captura de pantalla 2017-07-27 a las 12 01 13](https://user-images.githubusercontent.com/5371/28665666-b1c4911e-72c4-11e7-85e3-515b3b658291.png)

### Browser and version

Tested against Chrome 60.

**Comment by ivanmalagon** [comment]
Suitable for new hires.

**Comment by alrocar** [comment]
Stale issue. Closing 👋
