### ISSUE TITLE
Improving affordance of Delete icon

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#12531]
Design issue: https://github.com/CartoDB/design/issues/898

We would like to improve the affordance of the delete icon everywhere inside Builder by: 

- [x] Changing the bin icon to an X (8x8px)
- [x] Painting it blue instead of grey 
- [x] Tweaking the area that makes it appear

![new delete icon](https://user-images.githubusercontent.com/16247628/28712355-2e992fda-738b-11e7-97bb-ded5eb9c1aa3.png)

Let us know if you have any question :) 

cc/ @noguerol

**Comment by Jesus89** [comment]
@arianaescobar I have added a 8px padding to the "X" so there is no discontinuity between the form and the "X" and it is easier to select. OK?

![show-x](https://user-images.githubusercontent.com/2227572/29459399-a9d03d9e-8423-11e7-8aa9-5f83cf2dbad8.gif)

**Comment by arianaescobar** [comment]
Looks great :)

**Comment by Jesus89** [comment]
I have also added a padding to the listFieldsOrder.
Before:
![show-dots-before](https://user-images.githubusercontent.com/2227572/29460159-2ee11b0e-8427-11e7-87df-f1ca3de04e74.gif)
After:
![show-dots-after](https://user-images.githubusercontent.com/2227572/29460163-36132bd8-8427-11e7-9ac3-3d7637835ca4.gif)

**Comment by arianaescobar** [comment]
Awesome!

**Comment by noguerol** [comment]
🎉

**Comment by nobuti** [comment]
Closed by #12624
