### ISSUE TITLE
VQB query by name without user_id nor org_id

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#12538]
### Context

[trace](https://rollbar.com/carto/CartoDB/items/16320/).

From time to time, this condition is true at `VisualizationQueryBuilder` and message is logged: `@name && !(@id || @user_id || @organization_id || @owned_by_or_shared_with_user_id || @shared_with_user_id)`

During #12536 [we decided](https://github.com/CartoDB/cartodb/pull/12536#discussion_r130287858) to address the issue instead of removing the message, because it's a wrong situation and it has some impact at DB load.

No STR yet.

**Comment by ramiroaznar** [comment]
Hey @juanignaciosl is this still a pending issue?

**Comment by ramiroaznar** [comment]
Ping?

**Comment by juanignaciosl** [comment]
I was on vacation, sorry.

Yes, it is. If you open the linked trace, you'll see "Last seen: 1 day ago", meaning that it still happens.

**Comment by ramiroaznar** [comment]
Thank @juanignaciosl! Hope you enjoy your time off. ;-)
