### ISSUE TITLE
Don't change (and save) the layer source until that node is already created in the definition

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#12548]
@javisantana has realized when we drag out a node from a layer when we create the new layer with the node moved, it is saved first until the backend knows about that node. So we should make first the "analysis-definition" request and when it is finished, layer should be stored pointing to that "new" node.

## How to check that?
- Create a map of points.
- Add a subsample analysis.
- Open the browser console.
- Clear all network requests.
- Drag out the subsample analysis.
- Check the console.

**Comment by nobuti** [comment]
Picking this

**Comment by nobuti** [comment]
Closed by #12592.
