### ISSUE TITLE
Too many "Deleting Overviews" Messages

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/cartodb#12561]
We are logging (into Rollbar) an info message "Deleting Overviews" every time a sync is updated, regardless of whether it has overviews or not.

This is the Rollbar message: https://rollbar.com/carto/CartoDB/items/24226/?item_page=0&item_count=100&#instances

And this is where we log it: https://github.com/CartoDB/cartodb/blob/4cb56db847c329b199aef375357d7e92fb3989db/services/importer/lib/importer/overviews.rb#L63

The problem is that the `delete_overviews!` method is called for every sync (as part of the overviews update process) even if it doesn't have overviews and we log the message before we know if overviews exist and are going to be deleted.

The message is useless as is and is wasting Rollbar space. We should log only the cases where overviews are actually being deleted (or remove the message is this is not easy to do; note that we always call as SQL function `CDB_DropOverviews` which checks if overviews exist and removes them).

**Comment by juanignaciosl** [comment]
🔥 it!

**Comment by jgoizueta** [comment]
Note: I'm not removing the "Create overviews" message as well because it is emitted only when overviews are actually created (so we have on average < 20 per day) and it can be useful to determine how many large tables with overviews are being imported.

**Comment by jgoizueta** [comment]
No more traces of that error in Rollbar \o/
