### ISSUE TITLE
Scrub bar in time-series widget disappearing

### ISSUE THREAD

**Issue by rubenmoya** [CartoDB/cartodb#12567]
### Context
The scrub bar in time-series widget does not appear.

### Steps to Reproduce
1. Create a map
2. Change the style to animated

### Current Result
The scrub bar does not appear

### Expected result
The scrub bar appears

### Browser and version
- Safari 10.1.1 (12603.2.4)
- Chrome 59.0.3071.115

**Comment by xavijam** [comment]
Could you add more details @rubenmoya ? JS error? have you tried with other dataset? It is important we provide as many details as possible.

**Comment by rjimenezda** [comment]
That's very weird, the range should be withing the limits 😞 

I had some code that I didn't end up commiting that would hide the scrub bar while it was fetching, but it was too unreliable

**Comment by rubenmoya** [comment]
I used a different dataset and it works... so it doesn't happen always

**Comment by rubenmoya** [comment]
It happened to me again, and it seems it's only happening when the time series is using `date` columns
