### ISSUE TITLE
Strip inline comments in CartoCSS

### ISSUE THREAD

**Issue by rubenmoya** [CartoDB/cartodb#12574]
### Context
When using inline comments `// Something` in CartoCSS, the map breaks.

It's related to [this file](https://github.com/CartoDB/deep-insights.js/blob/master/src/widgets/auto-style/style-utils.js#L11).

We have to use the [postcss-stripe-inline-comments](https://www.npmjs.com/package/postcss-strip-inline-comments) plugin for PostCSS as we do in [Grainstore](https://github.com/CartoDB/grainstore/blob/master/lib/grainstore/paths/from23To30.js).

### Steps to Reproduce
1. Create a map
2. Write an inline comment (`// Inline comment`) in the CartoCSS

### Current Result
The map breaks ([example](https://team.carto.com/u/maps-for-all/builder/c6ee83ca-3e1c-11e6-8dc5-0e787de82d45/embed?state=%7B%22map%22%3A%7B%22center%22%3A%5B40.73112880602221%2C-73.93695831298828%5D%2C%22zoom%22%3A11%7D%2C%22widgets%22%3A%7B%2257d18786-618f-4796-8c62-8988f4deb4a7%22%3A%7B%22normalized%22%3Atrue%7D%2C%226c3d7a52-bc63-4136-baf2-33206764ccb8%22%3A%7B%22normalized%22%3Atrue%7D%7D%7D)).

![screen shot 2017-08-08 at 13 16 17](https://user-images.githubusercontent.com/905225/29069590-d15cc8ea-7c3b-11e7-9900-6b000e2de9b8.png)

**Comment by xavijam** [comment]
In production thanks to @alonsogarciapablo.
