### ISSUE TITLE
Time-series does not render

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#12570]
### Context
Based on https://github.com/CartoDB/learn/issues/411 the new time series widget doesn't render in this map 

[Washington DC Crime Data (on 2017-08-07 at 15.04.31).carto.zip](https://github.com/CartoDB/cartodb/files/1205239/Washington.DC.Crime.Data.on.2017-08-07.at.15.04.31.carto.zip)

### Steps to Reproduce

1. Open the .carto
2. Add 'reportdate' column as a time series

### Current Result
Widget is added but doesn't render

![captura de pantalla 2017-08-07 a las 17 10 46](https://user-images.githubusercontent.com/70603/29032881-6419b2be-7b93-11e7-8da3-fdff9c490d34.png)

**Comment by xavijam** [comment]
The response of the widget "request" says:

```
{
errors: [
"column reference "start_date" is ambiguous"
],
errors_with_context: [
{
type: "unknown",
message: "column reference "start_date" is ambiguous",
name: "error",
length: 106,
severity: "ERROR",
code: "42702",
position: "1549",
file: "parse_relation.c",
line: "769",
routine: "colNameToVar"
}
]
}
```

**Comment by xavijam** [comment]
cc @dgaubert @rochoa

**Comment by ivanmalagon** [comment]
I'm with @dgaubert and he says that he knows what's happening and he'll solve asap.

**Comment by dgaubert** [comment]
Sure thing!

Wait for it..!

**Comment by dgaubert** [comment]
This issue is fixed in https://github.com/CartoDB/Windshaft-cartodb/releases/tag/3.11.0

In production:
![screen shot 2017-08-08 at 12 20 40](https://user-images.githubusercontent.com/1936888/29067746-18796d30-7c34-11e7-9f05-f4c2a0645a31.png)
