### ISSUE TITLE
"Old" maps can't be rendered using vector unless named map template is updated with real layer ids

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#12589]
Some "old" maps cannot be rendered using vector rendering. The Named Map templates associated with some of these maps use old layer ids (eg: "layer0", "layer1", etc.) but then CartoDB.js passes real layer ids (eg: af39c976-c408-43ef-8af8-3029017297fd) to Tangram. This is preventing Tangram from being able to get data from .mvt tiles.

The following maps from @javisantana were not working because of this reason:

- https://javi.carto.com/builder/5e8101bc-76d1-11e6-97f1-0ee66e2c9693/embed
- https://javi.carto.com/builder/13b55ffc-95e9-11e6-8a2f-0e98b61680bf/embed

We manually changed and re-published these maps (so that the Named map template is updated) and everything started working like a charm 👍 .

There might be some more maps failing for this exact reason (when rendering with vector) so perhaps we should find a way to update/re-create their named map templates (eg: a rake task).

cc: @noguerol @kevin-reilly @javisantana

**Comment by kevin-reilly** [comment]
Assigning @javitonino to include on the Backend kanban in @juanignaciosl's absence.

We should research the impact of this and decide if what Pablo suggests is the correct approach.

cc: @noguerol

**Comment by javitonino** [comment]
@alonsogarciapablo Some questions.
- Do you know of another map with this problem? If not, some SQL magic can probably find them.
- Is only the named map affected? Or there is also something incorrect in the metadata (layer.options I suppose)? In case of the latter, can you point out for me what needs to be changed metadata-wise?

Thanks!

**Comment by javitonino** [comment]
Moved to Response Team Kanban (bottom of TODO). Feel free to prioritize it there by moving up if necessary.

**Comment by alonsogarciapablo** [comment]
> Do you know of another map with this problem? If not, some scripting magic can probably find some more example.

Sadly, I don't know other maps with this same problem. It would be as "easy" as finding maps whose named map template include "layer0", "layer1", etc. Also, maps that were created before the maps that I included in the description and that haven't been modified in the description, might have the same problem.

> Is only the named map affected? Or there is also something incorrect in the metadata (layer.options I suppose)? In case of the latter, can you point out for me what needs to be changed metadata-wise?

Good question. Not sure about that. Re-generating the named map template from BUILDER fixed the problem with the ids, not sure if it changed some other metadata too.

--

This work should be taken care of before we enable vector rendering to everyone. Not sure this should go through the response team or through regular backend work.

**Comment by javisantana** [comment]
I think we should forget about this: I have some maps with this problem because I created some maps during BUILDER development

If we find more users with this problems I'd consider doing something but if not is a better to invest time on doing other things

my 2 cents

**Comment by rochoa** [comment]
Quick question: what is the source of truth for cartodb.js to decide what is the ID for a layer? The viz.json or the response from the Maps API?

**Comment by alonsogarciapablo** [comment]
> Quick question: what is the source of truth for cartodb.js to decide what is the ID for a layer? The viz.json or the response from the Maps API?

Cartodb.js doesn't rely on any layer ids (that's why these maps will work in raster). Cartodb.js just "forwards" whatever it gets from the viz.json to the Maps API when using anonymous maps. It looks like Tangram needs layer indexes declared in the scene to match with those present in the .mvt tiles.

I just opened the issue so that we're aware of this but, as @javisantana said, I have no clue how important this is.

**Comment by noguerol** [comment]
I say we deprioritize this and freeze it until we get more feedback

**Comment by AbelVM** [comment]
This one https://github.com/CartoDB/support/issues/917 maybe

**Comment by ethervoid** [comment]
@noguerol  So, we should move this out of the response team TODO? or even [close it](https://github.com/CartoDB/cartodb/issues/12589#issuecomment-321765809)?
