### ISSUE TITLE
Display "error" notification when limits are being reached in API

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#12593]
Basically, if any limit is being hit by the current user, APIs request will start returning 4XX errors, and Builder should display a proper notification.

But for accomplishing that, we need to "receive" the error from CARTO.js (or DI.js). So we need first changes there, tackled in https://github.com/CartoDB/cartodb.js/issues/1714).

**Comment by piensaenpixel** [comment]
after the 'meeting', we decide to show the infobox only in the layer list :)
Thanks guys

**Comment by rubenmoya** [comment]
Right now the error is:

![screen shot 2017-10-04 at 16 13 43](https://user-images.githubusercontent.com/905225/31180470-05d6a928-a91f-11e7-8392-ddfff7860d20.png)

But what happens if the tiles are working and the limit error is thrown by any other thing? Widget/Interaction/SQL... should this message be more generic?

**Comment by xavijam** [comment]
Merged!

**Comment by xavijam** [comment]
Reopening due to https://github.com/CartoDB/cartodb/issues/12968. But we need to enable them again because if not the user will not have any clue about the errors those appear over the map. Unfortunately, we don't have enough information about the source of the "error", so the options are:

- Make a new request (no idea where but from Builder) in order to collect the necessary error info. If the problem comes from limits, we should display the infobox we used to have.
- Display an infobox with another message, more standard, not providing anything about upgrade and pointing to our docs (like the overlay does in the CARTO.js side).

If you ask me, I'd go with the second option.

@noguerol @matallo @rjimenezda @rubenmoya

**Comment by rubenmoya** [comment]
I'll go for the second option too, and change the documentation so it doesn't show only information about pricing but also show that it could be a connection problem or our servers being down

**Comment by rjimenezda** [comment]
The first one is not realistic, and wouldn't work on an offline / shoddy connection scenario, which also causes a tile error.

I'd go with the second one, we can point the CTA towards the same places as the 'Learn more' on the Overlay, but the message has to be decided by someone. Currently:

> Looks like you are over your limits when trying to render some of your tiles. Try to:

As @rubenmoya pointed out this morning, hopefully on other scenarios (wax, mvt, torque) we can emit a more specific error, and display it. But for raster tiles we're pretty much limited to a generic error.

**Comment by matallo** [comment]
while ideal I agree it's not realistic to get further information just for the raster errors, who shall confirm the new literal @xavijam ?

**Comment by xavijam** [comment]
I'd write something like: 

`Something happened and some tiles were not displayed. If the problem persists contact us or check our docs.`

**Comment by rjimenezda** [comment]
I'll put that temporarily.

So if we're not sure what exactly caused this, should the CTA still take the user to the pricing page? Should we point to some specific docs page? Should we remove the button altogether?

**Comment by noguerol** [comment]
Hey, just a comment. It doesn't matter how good is the msg if the error still pops up a lot of times. Prior to any decision: is there any way we can now the number of users that are seeing it?

CTA should point to the docs, yes. My suggestion for the msg is `Some tiles were not displayed. If the problem persists check our docs or contact us`

**Comment by piensaenpixel** [comment]
Hey, +1 to noguerol's suggestion

**Comment by rjimenezda** [comment]
I am no expert, but we can probably add some event (FS?).

This error will show for any user that has a problem loading as little as one tile (for whatever reason).
(Right now, nobody will see it because we removed it on a previous PR.)

Is pointing to carto.com/docs enough?

**Comment by matallo** [comment]
> I am no expert, but we can probably add some event (FS?).

we can

> Is pointing to carto.com/docs enough?

there's an open issue for that https://github.com/CartoDB/learn/issues/425

**Comment by noguerol** [comment]
We cannot measure this in FS because every free user is currently using vector maps. But even without metrics I still feel we cannot afford to have such a visible generic tile error, so I suggest we either

a) Figure out a way to only activate this notifications for vector users (via a feature flag or somehow discriminating sources; dunno if that is even technically possible)
b) Delay the re-deploy of these notifications until every user is using vector maps, which should happen shortly.

**Comment by xavijam** [comment]
The button should be gone. About @noguerol message, sounds good to me, but it is your call mates. And about the stat, yes, we can take those stats, but it will be ambiguous, because the causes are different...

**Comment by noguerol** [comment]
The stats will ve valid as long as the error message is generic. So @matallo tell me is a) is feasible and if its not, then we go for b)

**Comment by rjimenezda** [comment]
We're already showing a very subtle error on the map view, which coupled with the striped tiles gives a clear impression of 'something's not right'.

I would keep this very "in-your-face" error for things that we can 100% identify and point the user  towards a solution. As a matter of fact, the other error that is displayed on that area is the one for maximum number of Layers reached, which is something we can tell the user how to fix.

**Comment by matallo** [comment]
we left this at PR https://github.com/CartoDB/cartodb/pull/12974 with a more generic message and the rest of the requested changes

bear with me, why should we only show this for vector maps? just want to wrap my head around this

**Comment by noguerol** [comment]
This is what we've agreed to do: 
Only show notifications/error tiles for vector maps until @CartoDB/design works in a much subtle version of the last one, which will be then implemented at least for raster. In other words, we:

1. Work on a light tile error version
2. Disable notifications for raster maps and implement the light tile error
3. Notifications/Tile error for vector remains the same until we decide the implications of activating limits

**Comment by josecruz** [comment]
What about one of our firsts approaches on this?

![01](https://user-images.githubusercontent.com/596509/31939828-26d1339e-b8bc-11e7-90e9-fecc804c191c.png)
![02](https://user-images.githubusercontent.com/596509/31939831-290defbc-b8bc-11e7-9bc3-dc0688f0ddff.png)
![03](https://user-images.githubusercontent.com/596509/31939837-2bba942c-b8bc-11e7-91d7-985e10f1e1e2.png)

**Comment by piensaenpixel** [comment]
Hi @josecruz can we talk later about this?

**Comment by piensaenpixel** [comment]
I think this is the best approach cc @noguerol

**Comment by rjimenezda** [comment]
Thanks!

Just to be safe, by 'The current behaviour for vector' do we mean:

<img width="711" alt="screen shot 2017-10-24 at 17 19 32" src="https://user-images.githubusercontent.com/446970/31951893-8b38b58c-b8df-11e7-987f-bbf321b572ca.png">

Warning + Infobox + orange tile?

**Comment by piensaenpixel** [comment]
Vector is not available in builder so ... :(

**Comment by matallo** [comment]
not yet, but it can be detected, unlike raster (whenever the implementation for it is finished)

@rjimenezda as we can differentiate between the limits error, and the general error I think in that case we should go on with the limit error we left in the `en.json`

as @piensaenpixel suggested, for any raster error **no tile, no infobox, just overlay warning, thrown via img.onError event**

**Comment by inigomedina** [comment]
I start to be part of the project, talking to @matallo to understand internals and roll-up. Specifically those things that are pretty linked to Engine.

But in terms of the global user experience, and that doesn't understand about our separations between Builder/Engine and so on, I wonder how we will communicate them about the limits. Well, I see we have plans for displaying alerts about errors and limits, but where can be found that information about limits.

@noguerol 
Is there any part on the dashboard giving information about that?
Is there any part on documentation explaining those limits? Is that documentation dynamically connected to the limits configuration, so that when one part is updated the other one reflects it?
Is there any part of the rollup taking care about that but on future steps?

**Comment by rubenmoya** [comment]
Hi! As you know I've been in the response team last week so I'm kind of lost here. Right now we're showing a generic message and the orange tile, if I've read correctly we want to stop showing both of them, and just keep the map overlay (the yellow button in the bottom left corner) is that correct? The PRs are already open, should I prioritize this?

@noguerol @inigomedina

**Comment by rubenmoya** [comment]
We've been talking in the standup and the backend will send us the error tile, so finally what we're doing is:

- No infobox
- Map overlay
- Tile error sent by backend

**Comment by inigomedina** [comment]
It is worth to get back this issue created by @saleiva for the design team, looking for a solution to upsell from these kind of errors: https://github.com/CartoDB/design/issues/800
