### ISSUE TITLE
Wrong margin in DO Dropdown

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#12598]
### Current Result
we have 8px more in the right side when some filter is applied

![image](https://user-images.githubusercontent.com/1214201/29210418-ce10964e-7e93-11e7-8f22-e44c98951ba3.png)

**Comment by nobuti** [comment]
For new hires

**Comment by ramiroaznar** [comment]
We can group this one with this other #12860

**Comment by alrocar** [comment]
Stale issue. Closing 👋
