### ISSUE TITLE
Decide what to do with static map previews when user reaches its limits

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#12595]
As we discussed, we decided to better render the Limits "error" tiles in the Frontend side instead of letting them come from the Maps API. That's great, but it opens a problem for the Static Maps API. For example, in the dashboard we render the maps previews, and if there is a problem we could render any error tile and done. But what about public pages? We just render an png, for example:

![https://cartocdn-ashbu.global.ssl.fastly.net/xavijam/api/v1/map/static/named/tpl_93f4baea_9ec3_11e6_b132_0ef24382571b/1200/630.png](https://cartocdn-ashbu.global.ssl.fastly.net/xavijam/api/v1/map/static/named/tpl_93f4baea_9ec3_11e6_b132_0ef24382571b/1200/630.png)

From: 
`https://team.carto.com/u/xavijam/builder/93f4baea-9ec3-11e6-b132-0ef24382571b/embed`

```html
<meta property="og:image" content="https://cartocdn-ashbu.global.ssl.fastly.net/xavijam/api/v1/map/static/named/tpl_93f4baea_9ec3_11e6_b132_0ef24382571b/1200/630.png">
```
Places where it is being used:

- Dashboard map previews.
- Public pages, where it is being requested for generating link previews.
- Export image.

@CartoDB/engine

**Comment by rochoa** [comment]
What do we do to handle current/existing error cases? Do we just don't display the image? Or do we use a fallback image?

**Comment by xavijam** [comment]
yeah, that's the thing. IMO we should return an error code always (as we discussed previously in other thread). And, with that:

- Dashboard previews: we should display the error image if that limit error comes.
- Public pages: image will not be available, it is ok.
- Export image: we will display the error in the notification, all good.

I feel we are ok, what do you think?

**Comment by rochoa** [comment]
I'm lost. Do we handle errors in those cases?

**Comment by noguerol** [comment]
@CartoDB/design any concerns for the dashboard previews? The other two cases are already covered, right?

**Comment by rubenmoya** [comment]
Since we're going back to the backend rendering the limit error tiles I don't think this is needed anymore so closing it!
