### ISSUE TITLE
Duplicate shared maps

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#12603]
### Context
Currently the only way to have your own copy of a map is importing a .carto, which implies long waiting times in those workflows where the procedure is often or the files are large. Implementing a "Duplicate map", similar to the "Duplicate dataset" in the shared data view, will prevent this problem. 

### Steps to Reproduce

1. Go to the shared maps view in the Dashboard

### Current Result
There is no selected map behavior nor its options when clicking a map, a thus there is no way to duplicate it

### Expected result
Implement an options behavior similar to the ones in "my maps" with a "duplicate map" option.

**Comment by noguerol** [comment]
After talking with @javitonino several two options seem to be possible:

1. Make this internally exporting and reimporting a .carto. The easiest to implement, but also not very quick. We can expect a times in minutes rather than seconds for big datasets (+100mb)

2. Make this by directly copying tables in the database, faster but also more laborious. 

Based on .carto's functionality, only the datasets previously shared with that user will be part of the duplicated map, so we also need to figure out a way of notifying the user about it.

**Comment by javitonino** [comment]
-> https://github.com/CartoDB/cartodb-platform/issues/3525
