### ISSUE TITLE
Animated time-series widget out of viewport in mobile

### ISSUE THREAD

**Issue by rubenmoya** [CartoDB/cartodb#12609]
### Context
When using an animated time-series widget in mobile the chart gets out of the viewport. It only happens in mobile and with an animated widget.

### Steps to Reproduce
1. Create a map with animated styles
2. Open it in a mobile

### Current Result
The chart get's out of the viewport.

![screen shot 2017-08-17 at 13 05 31](https://user-images.githubusercontent.com/905225/29409553-0a7c4192-834d-11e7-91fc-705a29c59b85.png)

### Expected result
It doesn't get out of the viewport.

**Comment by rjimenezda** [comment]
Deployed 🚢
