### ISSUE TITLE
Stuck dark matter labels

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#12612]
### Context
Coming from the same support ticket than https://github.com/CartoDB/support/issues/927 , Dark Matter labels are stuck in the layers panel despite what basemap is selected

### Steps to Reproduce

1. Select Dark matter
2. Select positron (lite)

### Current Result
Dark matter labels is still shown

![image](https://user-images.githubusercontent.com/70603/29418242-14f40118-836c-11e7-9dd1-db3e509b9aee.png)

**Comment by xavijam** [comment]
Hey @noguerol, with those steps, it is not happening to me. Could you be more specific please?
