### ISSUE TITLE
Change icon/color position on Category Legends

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#12619]
### Context
Re: https://github.com/CartoDB/design/issues/739

We'd like to move the color/icon of the Category Legends to the left so that way we can relate more the data with its icon:

![](https://user-images.githubusercontent.com/14546701/29173025-300fc0e8-7de2-11e7-92bb-e702dd052922.png)

cc @noguerol

**Comment by xavijam** [comment]
I like this one and it is great for new hires. Sounds good @Jesus89?

**Comment by xavijam** [comment]
And by the way, if we can fix https://github.com/CartoDB/cartodb.js/issues/1639 in the same PR, it would be great 😬 .

**Comment by Jesus89** [comment]
@josecruz What are the expected sizes and distances for the legend?

![selection_001](https://user-images.githubusercontent.com/2227572/29570774-b8226cd2-8757-11e7-864f-6dd465ef0dc2.png)

**Comment by josecruz** [comment]
Hey @Jesus89, as talked in person I post here the distances and sizes (sorry, my bad):

![image](https://user-images.githubusercontent.com/596509/29576419-fcd0e6dc-8767-11e7-9a75-1a1fce967847.png)

As we said, when combining an icon with the default circled icon, we may need to move it 1px so visually they look centered

**Comment by Jesus89** [comment]
I think we should add 2px in both sides of the Circle icon, to get 12px:

<----------12px----------->  <-8px-> TITLE
<-2px-><-8px-><-2px->  <-8px-> TITLE

**Comment by josecruz** [comment]
Perfect @Jesus89, go ahead!

**Comment by xavijam** [comment]
Production!
