### ISSUE TITLE
Fix Mobile Time Series Widget behaviour

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#12616]
### Context
From this ticket: https://github.com/CartoDB/cartodb/issues/12470

We thought we can make the TS bar more interactive on mobile by doing this slight changes.

1. Activate `Show totals` by default so that way we can show some data over the bar
2. Make the handlers appear by default

![](https://user-images.githubusercontent.com/596509/29361698-0e4daf96-8289-11e7-95d0-01c8a6943b43.png)
to
![](https://user-images.githubusercontent.com/596509/29361683-f9cbb84c-8288-11e7-84ce-a762791e09c4.png)

**Comment by xavijam** [comment]
1. Not sure if we should enable by default "show totals" check. It depends on the data and the part of the world you are visualizing, so, IMHO, we should let the user select it.
2. About handlers, I like that and we should enable by default in mobile view :+1:.

**Comment by josecruz** [comment]
Sounds good @xavijam!

**Comment by josecruz** [comment]
Sounds good @xavijam!

**Comment by ramiroaznar** [comment]
This button is not working in Firefox Focus, Firefox or Chrome in Android. It works in Safari in iOs.

**Comment by ramiroaznar** [comment]
@ivanmalagon Can @elenatorro take this one? We can then close (almost) all mobile issues?

**Comment by alrocar** [comment]
Stale issue. Closing 👋
