### ISSUE TITLE
Legend items not properly created/removed

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/cartodb#12629]
### Context
The bugs appear when legend items are:
- Created with Enter
- Removed with X

### Steps to Reproduce

1. Create a legend
2. Enter the item input and press Enter: a new item is created but the map's legend is not updated
3. Type a title for the current legend: the map's legend is updated
4. Now delete the second legend item without adding a title: the map's legend is not updated
5. Finally type a character to update the map's legend

### Current Result

I think we have two bugs here:
1. New legend items are created with Enter
2. Map's legend is not updated when an Untitled item is removed

### Expected result

1. Pressing Enter creates new legend items but it should focus on the created item input and refresh the map's legend
2. Map's legend must be updated when an Untitled item is removed

### Browser and version

Tested with Chromium v60

### Additional info

![legen-bug](https://user-images.githubusercontent.com/2227572/29571936-f6fd007c-875a-11e7-86bb-c55400398eb0.gif)

**Comment by xavijam** [comment]
Leaving for @Jesus89

**Comment by nobuti** [comment]
Closed by #12650
