### ISSUE TITLE
Show entire map title in embeds

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#12626]
I'm not sure if we want to get into this or wait until we develop the public pages, but... given the amount of space available, we should show the entire map title here:

![screen shot 2017-08-21 at 11 12 41](https://user-images.githubusercontent.com/16247628/29518037-23729c9a-8678-11e7-9b0d-3dfb8468138f.png)

**Comment by xavijam** [comment]
Issue moved to [CartoDB/deep-insights.js #578](https://github.com/CartoDB/deep-insights.js/issues/578) via [**ZenHub**](https://www.zenhub.com/)
