### ISSUE TITLE
Filtering doesn't reflect the timezone offset in aggregated time-series

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#12637]
### Context

When filtering, we send our already timezone translated values to the API. With aggregation by hour or minute the offset can make a difference in the range of data we request to the API. Those limits seem to be wrong since they don't filter correctly the data.

![filter timezone](https://user-images.githubusercontent.com/1078228/29617002-97680d6e-8813-11e7-9c75-a7439b3ca4c7.gif)

I suspect the API needs the data in UTC, but I've tried to send the limits offset corrected to translate them to UTC and it didn't work neither.

The person responsible for this changes in the API was @dgaubert so it'd be nice to sit with him, check what the API expects and make the correspondent changes.

### Steps to reproduce
In the attached `.carto` file toggle `local timezone` in the time-series widget.

### .carto file
[1970 (on 2017-08-23 at 13.03.38).carto.zip](https://github.com/CartoDB/cartodb/files/1245449/1970.on.2017-08-23.at.13.03.38.carto.zip)

**Comment by alrocar** [comment]
Stale issue. Closing 👋
