### ISSUE TITLE
Get requests with nested SQL generated by .setSQL() blocked by university networks

### ISSUE THREAD

**Issue by duhaime** [CartoDB/cartodb#12630]
### Context

Network requests for Carto SQL endpoints that contain nested Select statements fail on particular networks when those networks are configured to prevent SQL attacks (e.g. Yale University's network).

### Steps to Reproduce

1. Join Yale University wifi network.
2. Use `.setSQL()` methods that generate a get request for (e.g.)
`http://photogrammar2.carto.com/api/v1/sql?q=select "city" from (SELECT * FROM photogrammar2.fsadata_2014 ) as _cartodbjs_alias where cartodb_id = 45336&callback=_cdbi_layer_attributes"` (after uri encoding)
3. Observe network warning message about SQL attack

### Current Result

The firewall displays a warning screen indicating that the user was attempting to download a virus and times out the user from future network connections for roughly 2 mins

### Expected result

JSON payload for get request

### Browser and version

Any

### Additional info

Requests without nested sql come through fine: (e.g.) `curl http://photogrammar2.carto.com/api/v1/sql?q=SELECT%20*%20FROM%20photogrammar2.fsadata_2014%20&callback=_cdbi_layer_attributes`

Requests with nested sql do not come through fine: 

```
curl 'http://photogrammar2.carto.com/api/v1/sql?q=select%20%22city%22%2C%22cnumber%22%2C%22county%22%2C%22fips%22%2C%22husco_name%22%2C%22icpsrfip%22%2C%22latitude%22%2C%22longitude%22%2C%22lotnum%22%2C%22month%22%2C%22pname%22%2C%22state%22%2C%22year%22%20from%20(SELECT%20*%20FROM%20photogrammar2.fsadata_2014%20)%20as%20_cartodbjs_alias%20where%20cartodb_id%20%3D%2045336&callback=_cdbi_layer_attributes'
<html>
<head>
<title>Virus Download Blocked</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<META HTTP-EQUIV="PRAGMA" CONTENT="NO-CACHE">
<style>
#content{border:3px solid#aaa;background-color:#fff;margin:40;padding:40;font-family:Tahoma,Helvetica,Arial,sans-serif;font-size:12px;}
  h1{font-size:20px;font-weight:bold;color:#196390;}
  b{font-weight:bold;color:#196390;}
</style>
</head>
<body bgcolor="#e7e8e9">
<div id="content">
<h1><img src="http://its.yale.edu/sites/all/themes/itsomega/logo.png" alt="Yale ITS" width="357" height="30"></h1>
<h1>Virus Download Blocked</h1>
<p>To help guard against malicious activity on the Yale networks, access to the virus you were trying to download has been blocked in accordance with Yale policy.</p>
<p>If you have any questions or believe you have received this message in error,  please contact your <a href="http://its.yale.edu/services/computer-and-device-support/getting-help">local support provider</a> or the ITS Help Desk at 203-432-9000 or <a href="mailto:helpdesk@yale.edu">helpdesk@yale.edu</a>. Visit the ITS website to <a href="http://its.yale.edu/news/known-malicious-websites-will-be-blocked-starting-nov-27">learn more</a>.</p>
<p><b>File name:</b> sql </p>
</div>
</body>
</html>
```

One potential solution would be an argument users could pass to their `.setSQL` calls that would indicate they don't want to include SQL in their GET request (they'd rather URI encode the SQL params, which some Carto middleware would convert to proper SQL).

**Comment by ramiroaznar** [comment]
Hi @duhaime, CARTO is working on the new API version. Do not see that our Product team is going to prioritize this issue. Thanks for your feedback anyway! Feel free to close the issue. :-)

**Comment by duhaime** [comment]
Thanks for your response @ramiroaznar. Will the new API be capable of accepting SQL params in the body of a POST request? It's not as pretty, but if end-users could query in that fashion, others in a similar situation would be better positioned to avoid the SQL injection blocker documented above...
