### ISSUE TITLE
Edit widget in advance mode doesn't show normal interface

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#12636]
STR:
1. Create a map with widgets
2. Enter into CSS editor
3. Edit widget

![edit-widget](https://user-images.githubusercontent.com/1214201/29615576-b7c71b22-880e-11e7-9f93-3a1311af06af.gif)

**Comment by xavijam** [comment]
Hey @piensaenpixel, be careful, you have your disk almost full 😂 .

**Comment by xavijam** [comment]
Fixed!
