### ISSUE TITLE
Disable DO for users without quota

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#12648]
From @noguerol in https://github.com/CartoDB/bigmetadata/issues/230#issuecomment-322814359
> To be confirmed: does the credit removal enables DO access to free and personal accounts? In case it does we should prevent it.

I tested [this change](https://github.com/CartoDB/cartodb/pull/12573) (master) and it seems to open DO for everyone, including users with DO quota = 0. As we block in the backend side, users will get all requested values as null.

The desired behaviour is:
obs_general_quota = 0 && soft_limit = false -> Upselling message (or maybe analysis disabled)
obs_general_quota >= 1 || soft_limit = true -> No quota checking

cc @nobuti @xavijam

**Comment by nobuti** [comment]
Do we have any screen to follow @CartoDB/design?

**Comment by xavijam** [comment]
Uhm... there is no upgrade state for disabled analyses. About the other thing, there was a decision about opening DO for everybody, what did happen with that? @noguerol @kevin-reilly

**Comment by ethervoid** [comment]
@xavijam as @noguerol requested we've removed the quota check for all the users that can use DO but FREE and PERSONAL accounts should not be able to use it so I think the best way to block them or show an upselling message is when they're going to select DO analysis

**Comment by xavijam** [comment]
Guys, there is no such "upselling" thing, either designed or implemented (or taken into consideration). Why are we adding that now?

**Comment by noguerol** [comment]
Please, guys, check more info here: https://github.com/CartoDB/bigmetadata/issues/215#issuecomment-324609879

**Comment by juanignaciosl** [comment]
@xavijam final decision (see CartoDB/cartodb-platform/issues/3547#issuecomment-325320198):

> obs_general_quota = 0 && soft_limit = false -> *Hide analysis*
> obs_general_quota >= 1 || soft_limit = true -> No quota checking

Let me know if you need anything from our side. This is the last step before public release 🤗 

cc @jorgesancha @kevin-reilly @noguerol

**Comment by xavijam** [comment]
:+1:

**Comment by juanignaciosl** [comment]
@xavijam this is already deployed, isn't it?

**Comment by xavijam** [comment]
Yes

**Comment by nobuti** [comment]
Already in production. Closed by https://github.com/CartoDB/cartodb/pull/12682.
