### ISSUE TITLE
When histogram widget is filtered, and user changes its buckets, it doesn't remove the filter

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#12645]
### STR
- Create a map of points.
- Add a histogram widget.
- Filter that widget.
- Go to edit that widget.
- Change the number of buckets.
- 💥 .

![screen shot 2017-08-24 at 12 46 11](https://user-images.githubusercontent.com/132146/29663232-6de587f2-88ca-11e7-97c4-23af9dbe5eb3.png)

**Comment by ivanmalagon** [comment]
Fixed at https://github.com/CartoDB/deep-insights.js/pull/577/commits/f0cab097d60ef72cfde224d224cd13f421ba165f
