### ISSUE TITLE
Replace time-series notification text

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/cartodb#12653]
### Steps to Reproduce

1. Create a Time Series widget
2. Select another Time Series attribute
3. Check the notification text

![ts-notification](https://user-images.githubusercontent.com/2227572/29713907-0f752a24-89a1-11e7-86df-fd7cd5b44a19.gif)

### Current Result

"Widget succesfully added"

### Expected result

"Widget succesfully replaced"

cc @josecruz

**Comment by rubenmoya** [comment]
In production 🚀 !
