### ISSUE TITLE
Panel overflow when creating widgets

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/cartodb#12655]
### Steps to Reproduce

1. Start from 0 widgets (reload after remove them all)
2. Create a time-series widget
3. Create other widget (Category, Histogram or Formula)

![widgets-overflow](https://user-images.githubusercontent.com/2227572/29714136-06f64c2e-89a2-11e7-9f46-b7fcc0b12962.gif)

### Current Result

The second widget is created without resizing the map panel

### Expected result

Force the window refresh after adding the widget, as happens when you add a time-series

**Comment by Jesus89** [comment]
There is also a related bug, when a sidebar widget is removed

![remove-sidebar-widget](https://user-images.githubusercontent.com/2227572/29769192-8b63b750-8be9-11e7-92cd-c7656f287ad6.gif)

**Comment by nobuti** [comment]
Closed by #12663
