### ISSUE TITLE
Histogram range slider sticks on buckets

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#12661]
### Context
On histograms and time series, when selecting a range you can position the slider above a bucket and it won't fix its position to either sides.

### Steps to Reproduce

1. Create an histogram or time series
2. Select a range
3. Drag one of the sliders on top of the bucket

### Current Result
The slider will remain in that position

![1](https://user-images.githubusercontent.com/70603/29771388-ca9be51e-8bf3-11e7-965f-4dca8ec5a9c9.JPG)

![2](https://user-images.githubusercontent.com/70603/29771389-caa4191e-8bf3-11e7-8b31-8ccb0f3de0c0.JPG)

### Expected result
The slider should snap to the nearest bucket side

**Comment by xavijam** [comment]
It could be related with https://github.com/CartoDB/cartodb/issues/12641, taking a look for both.

**Comment by nobuti** [comment]
Closed by #12701
