### ISSUE TITLE
Highlight new column

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#12662]
### Context
When someone adds a new column in a dataset the first thing they usually do is renaming this column. So, my proposal is that when someone adds a new column we activate the title input for renaming the column.

![image](https://user-images.githubusercontent.com/1214201/29771887-4af14914-8bf6-11e7-8153-f9152b41c4ac.png)

**Comment by xavijam** [comment]
Scroll to the new column and focus in the input, makes sense.

**Comment by piensaenpixel** [comment]
'Scroll to the new column' I think it's happening now.

**Comment by xavijam** [comment]
Yeah yeah, I was highlighting the complete behaviour 💋 .

**Comment by nobuti** [comment]
Closed by #12798
