### ISSUE TITLE
Weird line between steps in Legends

### ISSUE THREAD

**Issue by urbanphes** [CartoDB/cartodb#12660]
### Context
Between 1st step and 2nd step appears a line. I think can be by the horizontal scroll but if the 1st step doesn't have more options it should not appear anything

### Steps to Reproduce
Add a Legend and see the line between 1st and 2nd steps.

### Current Result
No line if the 1st step doesn't have more options.

### Expected result
Without line.

### Browser and version
- Chrome - Versión 60.0.3112.101
- Safari - Versión 10.1.2

### Additional info
![artboard](https://user-images.githubusercontent.com/14546701/29768471-acd5e8e8-8be6-11e7-9fdd-97a203270777.png)

**Comment by ramiroaznar** [comment]
Hey @urbanphes I was not able to replicate this issue. Can you share the .carto file?

**Comment by ramiroaznar** [comment]
Closing this because I do not see the line in Chrome. Feel free to open if you are still experiencing this issue.
