### ISSUE TITLE
add feature flag to redirect nginx traffic to static directory

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#12666]
discuss several strategies to redirect users with `static_frontend` feature flag to static directory, and decide one to be deployed to production

/cc @CartoDB/systems

**Comment by luisbosque** [comment]
Should we have a meeting for this? It will probably much faster. After that we can write in the issue the chosen approach

**Comment by matallo** [comment]
that would be ideal, this will be tackled when new squads are effectively setup, and today we're meeting to confirm the proposed plan and proceed

let's arrange a meeting to decide on the best approach

**Comment by matallo** [comment]
removing this from the milestone, as this will be tackled *after* the split as a separate task

**Comment by juanignaciosl** [comment]
@elenatorro should this be kept in Charlie's triage?

**Comment by elenatorro** [comment]
You are right @juanignaciosl, we should remove this, as it is said in this comment: https://github.com/CartoDB/cartodb-platform/issues/3798#issuecomment-356237847

> Nginx does not know anything about feature flags or something similar from the application. So, at the moment we deploy the static pages and the changes in nginx everyone will be, first trying to use the static pages and fallback to rails if it's not found. The feature flag in production/staging won't have any effect anymore.
