### ISSUE TITLE
make forms work with static pages

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#12669]
take profile form as the first form to split from backend, this will be replicated with the rest of the forms

to take into account:
- [x] JSON API for users https://github.com/CartoDB/cartodb/issues/12726
- [x] ~~CSRF~~
- [x] flash notices
- [x] validation
- [x] tests

**Comment by matallo** [comment]
I'm getting to the point where I can actually submit the profile form. However the form is failing as the json API endpoint for the users is not ready (404).

![screen shot 2017-09-04 at 18 37 24](https://user-images.githubusercontent.com/36676/30034344-0ad9b8e2-91a1-11e7-80bd-c9e434fd9149.png)

Also, if I wanted to add the CSRF to the form, we should expose `session[:_csrf_token]` through `/api/v3/me` but I'm not really sure, reading from Rails docs [1]:

> We may want to disable CSRF protection for APIs since they are typically designed to be state-less. That is, the request API client will handle the session for you instead of Rails.

However, **we are relying on the Rails session already in the API client**, so we'd probably need it.

Thus, we'll need to add this field to `/api/v3/me` endpoint, and also support API requests to users.

[1] http://api.rubyonrails.org/classes/ActionController/RequestForgeryProtection.html

**Comment by mayoral** [comment]
Most of our API controllers are inheriting from `Api::ApplicationController`. This controller already skips CSRF token validation as long as the format of the request is JSON, as you can see in:

https://github.com/CartoDB/cartodb/blob/master/app/controllers/api/application_controller.rb#L10

Also, most of the controllers that still don't inherit from `Api::ApplicationController` add their own skip token validation.

So I think that, for now, we don't need to add the token to the /me request. Instead, we need to check the controller whenever you get any error implementing requests via frontend, to ensure that the skip token validation is done in that API call.

**Comment by alrocar** [comment]
Stale issue. Closing 👋
