### ISSUE TITLE
Add "static_frontend" feature flag in superadmin

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#12671]
Remove `static_frontend` feature flag, create `static_dashboard`, `static_profile` and `static_account created`, and activate them for "team" organization in superadmin.

**Comment by matallo** [comment]
oop, finally to make the rollout more progressive I changed the name of FeatureFlags, being `static_dashboard` [1], `static_profile` [2], and `static_account` [3] the ones I've already worked on

In any case, I added this to the PRs description

[1] https://github.com/CartoDB/cartodb/pull/12680
[2] https://github.com/CartoDB/cartodb/pull/12704
[3] https://github.com/CartoDB/cartodb/pull/12749

**Comment by juanignaciosl** [comment]
Ok, then `static_frontend` should be deleted and `static_dashboard`, `static_profile` and `static_account` created?

**Comment by matallo** [comment]
indeed, sorry for not keeping this issue up to date with the latest changes

**Comment by juanignaciosl** [comment]
Description updated and all of them created (production and staging) and assigned to team. I haven't deleted `static_frontend` in staging.
