### ISSUE TITLE
 add "user_frontend_version", and "asset_host" columns to User model

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#12672]
in order to be able to override user assets version we need to add a new column to the User model (and run migrations).

we can probably get rid of asset host, and just leave it in `StaticConfig`, but it will be interesting to keep the assets version for the User

this can be extracted from https://github.com/CartoDB/cartodb/pull/12607

**Comment by juanignaciosl** [comment]
Removing this from the Backend/DO panel because the split for the migration should happen after acceptance of the main one.
