### ISSUE TITLE
Change "Aggregations" label to "Buckets" in Time Series

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#12684]
### Context
In time series Histogram's "Buckets" slider is replaced by an "Aggregations" dropdown when a time column is selected. If we label those "Aggregations" into "Buckets" we will make a more coherent relation between these two ways of binning data.

**Comment by xavijam** [comment]
Hey @kevin-reilly and @noguerol, I know this is only a text change, but the feature has been there last two months. Is it really that important?

**Comment by noguerol** [comment]
<3

**Comment by noguerol** [comment]
cc @csobier for updating the guides

**Comment by csobier** [comment]
Just an FYI that also use the term "buckets' in the UI when referring to classification methods (identifying the number of "buckets" when styling BY VALUE) and Histogram widgets (The selected range is distributed across your map in "buckets", to display groups of data).  Is this change going to affect those items too or no?

**Comment by xavijam** [comment]
AFAIK, no, it isn't @csobier, only in the widgets panel.

**Comment by xavijam** [comment]
In production!
