### ISSUE TITLE
time series' widget allows to select a non-date column

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#12693]
I created this map, and I found a small issue

https://team.carto.com/u/piensaenpixel/builder/529fa644-7bd6-4ae4-b4a3-3948b985d2b0/embed

I created a time series widget with a non-date column (a numeric one). It works and it's lovely, but in the mobile public view 'the histogram' doesn't show the columns bar

![image](https://user-images.githubusercontent.com/1214201/29876337-c7b84400-8d9c-11e7-82cc-8ceedb60f1b5.png)

Maybe the solution it's to not allow to select a time series with a non-date column.

@noguerol ?

**Comment by noguerol** [comment]
I find no reason for not doing it, right @xavijam ?

**Comment by xavijam** [comment]
I don't think we should "restrict" time-series widget to only date columns. There are several use cases where the customers don't want to aggregate dates.

**Comment by noguerol** [comment]
Which use cases are those? Because if it means people using TS as a big histogram, then we should rather disable this behavior and start thinking about enhancing the Histogram itself.

**Comment by ramiroaznar** [comment]
I can imagine one. Instead of having dates, you can have any order number or id that for the user make sense to have a temporal sequence. Regarding the original issue, we will need to check if this is also happening when using timestamp columns.

**Comment by noguerol** [comment]
But that data won't be temporarily aggregated, so I can't see the advantage.

**Comment by ramiroaznar** [comment]
@noguerol True.

**Comment by noguerol** [comment]
So, if we can't find use cases (cc @xavijam) I suggest we restrict TS widgets to timestamp columns.

**Comment by xavijam** [comment]
Not sure about that, because I remember several examples with only data (I remember a typical one with only `cartodb_id`). Let me give it a try (to my mind).

**Comment by noguerol** [comment]
Labeling this as a bug unless someone throws some evidence of the opposite.

**Comment by matallo** [comment]
we won't be able to make these kind of maps 😛 

http://bl.ocks.org/andrewxhill/8544392

on a more serious note, I mostly agree with @ramiroaznar note, in any case if we were restricting to only _time_ columns, I think there is a bigger issue at hand as the aggregation only says "animated" (and it makes sense in the case where it is not time-bounded), applying the restriction I don't think the aggregation title would be really representative.

**Comment by ramiroaznar** [comment]
We need to fix the responsive design anyway. This is also happening with a date column:

![screenshot_2017-10-26-12-27-14](https://user-images.githubusercontent.com/5215798/32048273-470ca452-ba49-11e7-9a03-3d299578993b.png)

**Comment by matallo** [comment]
while lacking info, if I'm not wrong that IS the expected behaviour (checked with @urbanphes when implemented the new timezone and time series changes)

**Comment by noguerol** [comment]
It is.

**Comment by ramiroaznar** [comment]
OK, don't get it. Why showing the time series widget then? There is only one bucket.

**Comment by matallo** [comment]
> OK, don't get it. Why showing the time series widget then? There is only one bucket.

wrong, open it in desktop browser and interact with the mouse, it is a fixed-heigh-with-no-separation time series (in order to make it fit in a constrained viewport)

**Comment by ramiroaznar** [comment]
Oh! Cool! That's great. Sorry mates.

**Comment by ramiroaznar** [comment]
But anyway, as commented with @matallo offline. It is not very intuitive at first sight. **IMHO** it looks like a long big button, not an interactive slider. cc @urbanphes
