### ISSUE TITLE
Date format in histograms

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#12696]
Change date formats in time-series widgets.

Coming from https://github.com/CartoDB/design/issues/925

Change formats to:
- Minutes: 12:34 - Jan 21st, 2015
- Hours: 12:34 - Jan 21st, 2015
- Days: Jan 21st, 2015
- Weeks: Jan 5th, 2015 (first day of week)
- Months: Jan 2015
- Quarters: Q1 2015
- Years: 2015

**Comment by nobuti** [comment]
In production
