### ISSUE TITLE
Consolidate drag icons in the widget list

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#12692]
As we have in layers and popup components, we should add the dot's icon when we want reorder the widgets

![image](https://user-images.githubusercontent.com/1214201/29876442-10a0424e-8d9d-11e7-9499-61de7d5d7072.png)

**Comment by noguerol** [comment]
@piensaenpixel can you provide a link to the correct design?

**Comment by josecruz** [comment]
There u go:

![widgets 02](https://user-images.githubusercontent.com/596509/30024340-9bf8c0e4-9173-11e7-8342-85c46ba4bb85.png)

**Comment by rubenmoya** [comment]
In production! 🚀

**Comment by piensaenpixel** [comment]
Thanks @rubenmoya !
