### ISSUE TITLE
Popup doesn't respect the order list

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#12694]
### Context
The first time you create a popup the field's order is the order we checked, not the order which appears in the list

### Steps to Reproduce
1. Create a new map
2. Add a new layer. The Dataset should be more than one field
3. Go to PopUp tab
4. Click on Hover tab
5. In the field's list select some random fields and after select one on the top of the layer list
6. Go to the map and do hover at some point or polygon

### Current Result
The fields which appear in the popup is not the same which we have in the layer list

### Expected result
The fields in the popup should be the same we have in the layer list.

### Additional info
![popup](https://user-images.githubusercontent.com/1214201/29876826-0b8c3122-8d9e-11e7-9300-c09285644d45.gif)

**Comment by nobuti** [comment]
Closed by ##12706
