### ISSUE TITLE
Maps with google basemap open in editor

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#12712]
Currently, editor maps with google basemaps are never migrated to builder: https://github.com/CartoDB/cartodb/blob/master/app/models/carto/visualization.rb#L534

This is a remnant  from when Builder did not support google basemaps, but that is no longer an issue. I think we can remove that check, and allow maps with google basemaps to be opened in Builder. Do you agree @noguerol?

cc @xavijam @juanignaciosl @ernesmb

**Comment by noguerol** [comment]
Yes please! Good catch.

**Comment by ramiroaznar** [comment]
Should we close this issue @ernesmb @javitonino?

**Comment by juanignaciosl** [comment]
Added this to our kanban to approach it in master.

**Comment by amartinj** [comment]
retest this please
