### ISSUE TITLE
Invalid tooltip when Layer title changes

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/cartodb#12714]
### Steps to Reproduce

1. Enter in a layer
2. Check the title's tooltip
3. Change the title

![invalid-tooltip-layer](https://user-images.githubusercontent.com/2227572/30034460-e842f734-91a1-11e7-8bc8-aa48f77b667a.gif)

### Current Result

Tooltip is not updated

### Expected result

Tooltip must be updated with the new title

**Comment by nobuti** [comment]
Worst gif ever 😂

**Comment by Jesus89** [comment]
So fast :rofl:

**Comment by Jesus89** [comment]
Updated! (something is wrong with my Peek app)

**Comment by Jesus89** [comment]
Closed by #12752
