### ISSUE TITLE
EditOverlay for features is created multiple times

### ISSUE THREAD

**Issue by nobuti** [CartoDB/cartodb#12716]
### Context
Every time you switch between map view and table view, a new EditOverlay view is created

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Switch to table view
2. Switch to map view
3. Back to one a couple of times

### Current Result

<img width="573" alt="screen shot 2017-09-04 at 16 21 34" src="https://user-images.githubusercontent.com/1366843/30030470-b61c622c-918d-11e7-97aa-7929e86c5c3b.png">

### Expected result
That view is only created when new features added.

**Comment by nobuti** [comment]
I've found a couple of issues related with this:

- [ ] The EditOverlay view doesn't allow to click on the first widget's control.
- [ ] Being in the feature edition view, if you change to another view instead of clicking on the back link (widget edition for example), the Builder breaks: https://my.trackjs.com/details/314b6da84e3844cc925bfd6a9cc5c88f

I'm going to fix them as part of this issue.

**Comment by ivanmalagon** [comment]
Works like a charm.

**Comment by ivanmalagon** [comment]
Shipped! :rocket:
