### ISSUE TITLE
Don't show "Size" tab in Legend when it's not possible to add one

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#12728]
### Context

Right now we're allowing our users to access the Size tab even when it's impossible to add a size legend. We should disable that tab and show a tooltip to explain why is it disabled. 

### Current Result

<img width="342" alt="screen shot 2017-09-05 at 13 00 21" src="https://user-images.githubusercontent.com/16247628/30061567-211bc4e0-9248-11e7-9268-616c64ace147.png">

### Expected result

![screen shot 2017-09-05 at 15 38 15](https://user-images.githubusercontent.com/16247628/30064214-5c1b6bfa-9251-11e7-95f0-9e7c82da96ba.png)

**Comment by matallo** [comment]
in production! 🚀
