### ISSUE TITLE
Allow lowercase in custom and category legends 

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#12720]
### Context

It's a strange behavior that we allow lowercase on certain text inputs in the legends (look at "people") but not on others (like "5 min walk"). We should unify it and either only show text in uppercase or give the user the flexibility of using whatever type of case they want.   

### Current Result

![screen shot 2017-09-01 at 16 58 25](https://user-images.githubusercontent.com/16247628/30034666-1b7f4926-91a3-11e7-8e5b-526113818dc6.png)

**Comment by piensaenpixel** [comment]
+1

**Comment by rubenmoya** [comment]
This change will affect to currently created legends, could that be a problem?

**Comment by alrocar** [comment]
Stale issue. Closing 👋
