### ISSUE TITLE
Error message repeated 5x in CartoCSS notification

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#12721]
### Context

I miswrote `polygon-comp-op` as `poylgon-comp-op` and when I tried to apply it, I got the error notification and as you can see in the screenshot below, the same error message is repeated five times. 

### Current Result

![screen shot 2017-09-04 at 11 44 04](https://user-images.githubusercontent.com/16247628/30034749-bcdf85ba-91a3-11e7-9e91-d1a5ae42090c.png)

**Comment by ramiroaznar** [comment]
This is already fixed.
