### ISSUE TITLE
Histogram initial range determined by filters

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/cartodb#12729]
### Context

Related to https://github.com/CartoDB/cartodb/issues/12618
See also https://github.com/CartoDB/cartodb/issues/12620

When a histogram is added, its range is initially restricted by applied filters. If the page is reload the range changes.

### Steps to Reproduce

1. Create map with some non-empty table
2. Add histogram widget by cartodb_id
3. Apply a filter in the histogram
4. Add another histogram by cartodb_id (the new histogram range is restricted by the filter as in the first image)
5. Reload the page (the range is not longer restricted by the filter)

When the widget is first added:

![screen shot 2017-09-05 at 15 40 03](https://user-images.githubusercontent.com/5909/30064098-0c6d170c-9251-11e7-9fd2-8e48be702b3b.png)

After reloading the page:

![screen shot 2017-09-05 at 15 41 13](https://user-images.githubusercontent.com/5909/30064111-138552b6-9251-11e7-9c81-d80d05107515.png)

### Current Result

New histograms have the range determined by filtered data. But changes by reloading the page.

### Expected result

I think new histogram should have the unfiltered range. This is not consistent with adding the new widget without active filters, then filtering (the range remains unfiltered).

In any case the range should not change by just reloading the page.

### Browser and version

Chrome Version 60.0.3112.113 (Official Build) (64-bit)

### Additional info

I have mixed feelings about this ticket, perhaps I'm only adding noise to this overly complicated issue of histogram ranges/filter interactions... but I hope this is at least useful to document this odd detail of the current behaviour 😛 .

**Comment by alrocar** [comment]
Stale issue. Closing 👋
