### ISSUE TITLE
Torque scrubber gets crazy after changing column

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#12738]
![crazy scrubber](https://user-images.githubusercontent.com/1078228/30068957-a4aef216-925f-11e7-8838-eb032c5b61a9.gif)

After changing the target column in a time-series widget linked to a Torque animation, the scrubber loses its reference and moves in a wrong position.

### Steps to Reproduce
1. Select a layer and style it to `animated`.
2. Go to Widgets tab.
3. Select the created time-series widget.
4. Change the column. In the example it changed from a number to a date one.

### Current Result
The scrubber moves off-screen.

### Expected result
The scrubber moves back to the first position in the widget and continues moving from there.

**Comment by alrocar** [comment]
Stale issue. Closing 👋
