### ISSUE TITLE
Change 'SHARE' button copy for 'PUBLISH'

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#12730]
Just that text change, from SHARE to PUBLISH. 

![button](https://user-images.githubusercontent.com/16247628/30064634-a39f691c-9252-11e7-8ab9-dd27cb24e4a1.png)

re: https://github.com/CartoDB/design/issues/790#issuecomment-327177632

**Comment by rubenmoya** [comment]
In production! 🚀

**Comment by csobier** [comment]
Whoops- just found this live. WIll update all the docs...  Maybe next time give me a heads up too please :-)

**Comment by piensaenpixel** [comment]
sorry @csobier you're right :(

**Comment by csobier** [comment]
No problem, I've created an issue for myself but just a reminder for going forward.

And BTW: all these recent front-end changes (while annoying to have to re-do on my end, but that's my job ;-) are actually SO much better for Ux... so good work Design team!
