### ISSUE TITLE
Change 'Map not published yet' copy

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#12731]
For 'Unpublished map'

![screen shot 2017-09-05 at 16 04 16](https://user-images.githubusercontent.com/16247628/30065028-e6b85bf4-9253-11e7-960f-94bb099b36f9.png)

re: https://github.com/CartoDB/design/issues/790#issuecomment-327177632

**Comment by Jesus89** [comment]
Related to: #12730
