### ISSUE TITLE
Import error with long and similar filenames

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#12732]
### Context
https://github.com/CartoDB/support/issues/967

### Steps to Reproduce
1. Create a file named `carto_long_filename_that_almost_matches_another_one_63chars_aaa.csv` and import it into CARTO
2. Create a file named `carto_long_filename_that_almost_matches_another_one_63chars_aab.csv` and import it into CARTO

### Current Result
Error 9999, the import log shows
```
2017-09-05 14:21:41 UTC: Exception: PG::Error: ERROR:  type "_carto_long_filename_that_almost_matches_another_one_63chars_aa" already exists in schema "xxxxx"
```

cc @juanignaciosl @rochoa

**Comment by juanignaciosl** [comment]
cc @noguerol @kevin-reilly for possible Response Team prioritization.

**Comment by kevin-reilly** [comment]
Looks like the client was able to address this by renaming the file.  This is not a response team issue.

How many characters do we support for files names?  Is this insufficient?  If so, we should prioritize in one of the product backlogs (not sure which).

**Comment by javitonino** [comment]
We support any amount of characters and automatically truncate them. This is a specific bug with this truncation process, where the filenames are exactly the same except for the 63rd character.

**Comment by kevin-reilly** [comment]
If we are truncating the 63rd character, we support file names with 62
characters.  Right?

--
*Kevin Reilly*
SVP Product
*CARTO <https://carto.com/> | kevin@carto.com <kevin@carto.com>*
(917) 375-2168

**Comment by javitonino** [comment]
Not exactly. Let me explain a bit more in depth:
- If the filename is longer than 63 chars, we truncate to 63 chars.
- If the table name is taken, we add a _1, _2, etc. suffix

So we support filenames of arbitrary length, we just convert them to something we can use on import. There is a bug (this one), where a filename is longer than 63 chars, and the first 62 chars match another table. In this case, it is expected that we import the file with no issues (they have a different name after all), but we are giving an import error instead.

This is clearly a bug, we should never throw an error on import, no matter the filename.
