### ISSUE TITLE
JS errors at /explore

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#12746]
### Context

Found on #12685 acceptance.

https://carto.com/explore fails because of CORS:

```
explore:1 XMLHttpRequest cannot load https://gistoyou.carto.com/api/v1/viz/83287235-b65f-4b5e-89c7-f07e8cdb4de5/like. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://carto.com' is therefore not allowed access. The response had HTTP status code 403.
```

cc @noguerol, @kevin-reilly  for prioritization.

**Comment by juanignaciosl** [comment]
PS: I removed "because of CORS" from title because it might not be related, after all. I get JS errors opening it in a browser where I'm logged in, but I don't get it in an anonymous window.

**Comment by javitonino** [comment]
It only happens for public unpublished visualizations (Builder visualizations without mapcap). The like button would not load for those with a 403.
