### ISSUE TITLE
Update Refresh buttons to new brand

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#12751]
### Context

Design issue: https://github.com/CartoDB/design/issues/934

When a widget fails, the refresh button that appears is not on brand. Also, the widget itself should turn into a placeholder image instead of getting a color overlay on top. 

We would also like to add an extra button to refresh them all with one click, instead of having to go one by one.

### Current Result

![29517943-ae6a2e9a-8677-11e7-9751-3eb87e4f02a6](https://user-images.githubusercontent.com/16247628/30153470-0a8427c0-93b7-11e7-9c71-c29d3b8f3346.png)

### Expected result

![errors](https://user-images.githubusercontent.com/16247628/30153886-6e0539c8-93b8-11e7-8952-24cae556e718.png)

**Comment by arianaescobar** [comment]
Also, remember [this ticket](https://github.com/CartoDB/cartodb-platform/issues/3279). If we have information about the error, the output should be one of these: 

![screen shot 2017-09-18 at 14 51 21](https://user-images.githubusercontent.com/16247628/30542755-df01e812-9c80-11e7-9e45-12eb7727afe2.png)

**Comment by matallo** [comment]
in production, already!
