### ISSUE TITLE
Loader is showing html text

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#12756]
### Context
Loader is showing html text

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Create a map
2. Upload a dataset
3. See infobox

### Current Result
![image](https://user-images.githubusercontent.com/1214201/30164916-607a20ae-93de-11e7-9b64-46a9a4279804.png)

### Expected result
Show the text without html's tags

**Comment by Jesus89** [comment]
I will pick this one!

**Comment by xavijam** [comment]
😱 , ok @Jesus89 🤗

**Comment by Jesus89** [comment]
Closed by #12761
