### ISSUE TITLE
Polygons style size/color label should be color

### ISSUE THREAD

**Issue by rubenmoya** [CartoDB/cartodb#12768]
From: https://github.com/CartoDB/cartodb/issues/12564#issuecomment-328154892

### Context

![screen shot 2017-09-08 at 10 40 56 am](https://user-images.githubusercontent.com/1566273/30221965-8217d9be-9482-11e7-8176-9f6c1b1c6880.png)

**Comment by nobuti** [comment]
Closed by #12770
