### ISSUE TITLE
html code appearing in map metadata confirmation dialog

### ISSUE THREAD

**Issue by csobier** [CartoDB/cartodb#12760]
Just noticed (as of today?), when editing the map metadata in Builder:
- Map name context menu
- Edit metadata and add or change text
- Save

The confirmation dialog is not new, that has always been there and is expected. However, the dialog is now displaying the html code in the UI; this is new/different behavior @xavijam?
`<span class='CDB-Text is-semibold'>Metadata</span> for {map name} map <span class='CDB-Text is-semibold'>was saved</span>.`

![image](https://user-images.githubusercontent.com/13319925/30172147-f15837d6-93c1-11e7-837a-095a1390c761.png)

**Comment by Jesus89** [comment]
Duplicated: https://github.com/CartoDB/cartodb/issues/12756
