### ISSUE TITLE
Timeseries widget won't load with exactly 366 days

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#12778]
## STR
1. Import [one_year.csv.txt](https://github.com/CartoDB/cartodb/files/1295496/one_year.csv.txt). It has just two dates, separated by exactly one year (leap year, 366 days)
2. Create a map, add a timeseries widget

## Result
The widget won't load.

## Info
After some investigation with @ivanmalagon and @rubenmoya, it seems Builder is calculating 366 buckets for this, but there are really 367. Windshaft correctly calculates and returns this, and the widget cannot be rendered.

## Workarounds (either one)
- Manually switch to week buckets.
- The dataset hast two dates: "2015-06-01 00:00:00" and "2016-06-01 00:00:00". Change the second one to "2016-06-01 00:00:01". Builder now stops offering the day buckets. But it still crashes upon adding the widget.

**Comment by ivanmalagon** [comment]
Found an issue that is fixed in a ticket that is on Builder acceptance stage. Blocking this until the other is merged and we can merge it here from master.

**Comment by ivanmalagon** [comment]
Shipped! 🚀
