### ISSUE TITLE
if all datasets are locked, cannot view datasets dashboards because re-direction to data library

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartodb#12775]
### Context

I have an account with a couple of datasets that I don't want to accidentally delete or edit, so I locked them. The problem is that if all of the datasets in my account are locked, then I am automatically redirected to the data library and unable to unlock my datasets or view the datasets dashboard.

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Lock all datasets from the Datasets Dashboard
2. Observe that user is forwarded to the Data Library dashboard
3. Try to click on Datasets to get back to the dataset list

### Current Result

If all datasets are locked, I am not able to find a way through the UI to see the dataset view where I can unlock my datasets.

A workaround is to search for a dataset, open it, select 'unlock it' from the modal, and then observe the dataset list with that newly-unlocked dataset. Another is to upload a new dataset so that a non-locked dataset will be in the list, but I could see a user being above storage quota not being able to do this. Either way, it is not straight forward.

![locked-datasets](https://user-images.githubusercontent.com/1041056/30289770-3349d794-96fb-11e7-856a-61e9507fba72.gif)

### Expected result

Dataset dashboard should still be accessible without a forced re-direction, and a live link to Locked Datasets should exist somewhere so a user can unlock any datasets.

### Browser and version

Chrome Version 60.0.3112.113 (Official Build) (64-bit)
macOS 10.12.5

### .carto file
N/A

### Additional info
*Please add any information of interest here below*

**Comment by rubenmoya** [comment]
What should we do in this case?

In the locked datasets view we're showing, the _No datasets message_ with a link to the datasets view, should we do the same?

![screen shot 2017-10-25 at 15 34 40](https://user-images.githubusercontent.com/905225/32004519-38eb3a98-b9a2-11e7-82bc-ec90b824b0fe.png)

**Comment by arianaescobar** [comment]
+1  @rubenmoya

**Comment by rjimenezda** [comment]
Just FYI we can't know beforehand if there are any locked datasets or not, that's another request.

We're explicitly redirecting to the shared datasets in case there are no datasets (unlocked) AND there are some shared with you.

The solution would require either:

a) Ignoring the current behaviour, and never redirecting. This would mean 'No datasets' and '0 locked datasets below'
b) Adding the number of locked to the response, so we can decide better what to do.

**Comment by ramiroaznar** [comment]
I will go with a). I was going to comment it to the issue earlier but I forgot. No datasets *or maps*!

cc @CartoDB/design @noguerol

**Comment by rjimenezda** [comment]
It's a trivial fix in that case. I'm going to quickly check how hard it is to add an extra field to the response, but I'm no rails expert

**Comment by rjimenezda** [comment]
It's pretty easy, as it turns out. So we can do either 👍

**Comment by ramiroaznar** [comment]
cc @piensaenpixel @urbanphes

**Comment by rjimenezda** [comment]
I left an approach on ded15

**Comment by ramiroaznar** [comment]
Checking.

**Comment by ramiroaznar** [comment]
:bandera: LGTM!

**Comment by arianaescobar** [comment]
+1 with going with option a. 

About this: 

> No datasets or maps!

Why? @ramiroaznar If the user is in the datasets tab, why should we reference maps there?

**Comment by rjimenezda** [comment]
I think he meant to also take into account the 'Maps' section which is affected by the same thing.

I ended up doing b, but I can switch to the other one, it's simpler and requires less changes

**Comment by arianaescobar** [comment]
Oh, I see! Then +1 

And yeah, I would recommend switching to a.

**Comment by urbanphes** [comment]
+1 to option A

**Comment by rjimenezda** [comment]
Deployed on ded15

**Comment by ramiroaznar** [comment]
LTGM!

**Comment by noguerol** [comment]
👌

**Comment by andy-esch** [comment]
+1 for option A

**Comment by rjimenezda** [comment]
On production 🚢

**Comment by ramiroaznar** [comment]
:boom:
