### ISSUE TITLE
Allow org/user to save default style colors to align with corporate branding

### ISSUE THREAD

**Issue by terrett101** [CartoDB/cartodb#12786]
Many of our enterprise customers have corporate style and brand requirements, and wish to convey those through the maps they create in CARTO for their customers. Currently they have to configure this each time via the Style UI or in CartoCSS. It would be great if an Enterprise org, or an individual user, could configure and save a default style scheme for color ramps or category colors when styling their map layers.

For instance, if it were CARTO, we'd save a default color scheme to use #F24440, #1785FB, and #162745.

**Comment by noguerol** [comment]
This is interesting and a thing that has sometimes been discussed in @CartoDB/design
