### ISSUE TITLE
Widget's bin color input is not representing the correct colors 

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#12789]
### Context

Right now the COLOR input field in the widgets settings is not representing the correct colors when you switch between widget types or when you change the color of the bins and change types. 

### Steps to Reproduce

1. Add a Histogram widget
2. Change to a Time-Series Widget
3. Change the bin colors and change back to a Histogram one
4. Take a look at the color input in all the previous steps and how it doesn't represent the correct color

### Current Result

![color](https://user-images.githubusercontent.com/16247628/30367737-59333c64-986f-11e7-84f1-81a4c42f217a.gif)

**Comment by ramiroaznar** [comment]
This is fixed.
