### ISSUE TITLE
Revert change in Autostyle label

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#12788]
### Context

When [working](https://github.com/CartoDB/cartodb/commit/cdce6a0a3a3e20a721ccb2277536e43ca45372c0) on this [issue](https://github.com/CartoDB/cartodb/issues/12564), the Autostyle's custom colors label was changed from "Custom colors" to "Autostyle". Let's revert that change, please :)

**Comment by csobier** [comment]
@noguerol , is there a time estimate on this change or should I update all the docs as they appear live for now?

**Comment by csobier** [comment]
Related issue: https://github.com/CartoDB/cartodb/issues/11301

**Comment by nobuti** [comment]
Almost there @csobier, once accepted, we can ship it.

**Comment by arianaescobar** [comment]
👌🏼
