### ISSUE TITLE
Feature edition panel disappears

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#12781]
![feature vanish](https://user-images.githubusercontent.com/1078228/30326091-a3cb6c68-97c7-11e7-9060-0e3e8b643039.gif)

### Steps to Reproduce
1. Create an empty map.
2. Enter in the layer.
3. Add a feature, a polygon, for instance.
4. Go back to the Style tab.
5. Click on the created polygon and delete it.
6. CRASH!! The tab disappears.

### Expected result
You get back to the style layer.

**Comment by Jesus89** [comment]
Comes from #12717 to prevent a crash opening the "edit widget panel" after editing a feature. I think a solution may be to revert the changes and cancel the "feature edition" before entering the "edit widget panel"

**Comment by nobuti** [comment]
Closed by #12793.
