### ISSUE TITLE
Geometry selection for postal code Georreference

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#12811]
Based in this support ticket https://github.com/CartoDB/support/issues/968 and urged by this PR https://github.com/CartoDB/camshaft/pull/329 , we need a new parameter, in the Postal codes Georreference analysis, for selecting between points and polygons.

cc @CartoDB/design to handle it first.

**Comment by ramiroaznar** [comment]
@alonsogarciapablo what do you think about this issue? Should I add it to the RT queue? There is a strong support for this feature. @juanignaciosl does it make sense with the new DO workflows that are coming?

**Comment by juanignaciosl** [comment]
This change makes total sense to me, because it's a big win for the users and the analysis is already ready to receive the `output_geometry_type` argument. DO future changes are not affecting this anytime soon.

**Comment by ramiroaznar** [comment]
Thanks! I will try to push this next shift!

**Comment by alrocar** [comment]
Stale issue. Closing 👋
