### ISSUE TITLE
Fastly CDN Caching

### ISSUE THREAD

**Issue by alexsroth** [CartoDB/cartodb#12819]
### Context
We got this ticket over in support and looks like something that may be worth a look:

[supportbee ticket](https://cartodb.supportbee.com/tickets/14056988)

The subject is on making requests for a map tile, and requests that may vary between a conflict in using "cache-control" and "age" with different values that causes multiple GET requests to occur.

I personally have not tested this, but the user has provided a good amount of detail in their correspondence. 

Information from the ticket in blocks quotes:

>I have been playing around with your tiles for a personal project using leaflet.js. I have noticed some peculiar caching behavior from your CDN. When you make a request for a tile, the browser (chrome, safari) does not seem to ever use a browser cached version despite the responses containing a "Cache-Control: max-age=3600" header. It will do a new GET each time. I believe the behavior is coming from the that fact that the responses also contain and "Age" header with a value significantly greater than the 3600 seconds specified in the "Cache-Control" header. I have encountered a similar issue at work where certain applications of ours were adding the "Cache-control" and others were adding the "Age" or some other (possibly contradictory) header(s). Judging from the response headers, my gut tells me Varnish or nginx are at odds with Fastly or something like that.

### Steps to Reproduce
>Navigate to https://carto.com/location-data-services/ with the Chrome web inspector enabled. Load the page once. The tiles for map at the top of the "CUSTOM BASEMAPS" section will load. Reload the page or navigate to another page on the site and navigate back to the original page. The same tiles should load again from browser cache, but they are loaded anew.

>You can also do the same steps on the leaflet provider page and selecting the CartoDB.Positron option: https://carto.com/location-data-services/ Other providers (notably ESRI, using ETag header as well) do indeed load cached versions on subsequent loads.

### Current Result
![image](https://user-images.githubusercontent.com/29546714/30555155-c7e8f38e-9c74-11e7-9e89-661e39dc263e.png)

### Browser

looks like they used chrome/safari

### Additional info

The user's email address is jtyuzawa@gmail.com

>Additional Request: Some of the other providers use ETag and/or Last-Modified headers in their responses. This would allow the browsers to use If-None-Match and If-Modified-Since headers in the subsequent requests to see if the content has changed. Your server (or the CDN) would return a 304 Not Modified if the content was unchanged, thus saving even more on bandwidth and CDN costs. Personally I've had more luck with ETag than Last-Modified. There may be an easy to use setting in Fastly to set up ETag, but you could also set it in your backend servers as well.

>Let me know if you need anything else to help reproduce this issue. I use a CDN at work and I know they can be expensive, so I'd like to help you out there. Hope to hear from you soon!

**Comment by jsanz** [comment]
Issue moved to [CartoDB/support #1065](https://github.com/CartoDB/support/issues/1065) via [**ZenHub**](https://www.zenhub.com/)
