### ISSUE TITLE
cache strategy for *static* public pages

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#12824]
research a cache strategy for the static public pages

current embed pages are cached with varnish mostly due to the vizjson, new approach hits `/api/v1/viz` so we should cache that and any further endpoints that hit the DB such `/me`

we could avoid hitting the DB and keep on working as normal, just be careful to prevent _expensive_ requests

**Comment by alrocar** [comment]
Stale issue. Closing 👋
