### ISSUE TITLE
Check "carto logo" disabled checkbox in map options

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#12836]
### Context
For those users unable to remove the CARTO logo we currently have a non-checked disabled checkbox in map options

![image](https://user-images.githubusercontent.com/70603/30693265-0c7c11b4-9ecf-11e7-89da-b8f753085a24.png)

But it's confusing because the option is activated.

### Steps to Reproduce

1. Go to map options and look for the "CARTO logo" checkbox

### Current Result
Checkbox is disabled but unchecked

### Expected result
Checkbox should still be disabled but checked

**Comment by nobuti** [comment]
This is a matter of styling, the checkbox is checked, but is not visible.

**Comment by noguerol** [comment]
Understood.
