### ISSUE TITLE
Fix margin of DELETE action 

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#12860]
The left margin of the DELETE action is incorrect, it should only be 24px from the blue bar. 

Design:
<img width="793" alt="screen shot 2017-09-25 at 10 47 31" src="https://user-images.githubusercontent.com/16247628/30800423-3c3fc9fe-a1e0-11e7-9d49-d9c27970756a.png">

Production: 
<img width="765" alt="screen shot 2017-09-25 at 10 51 12" src="https://user-images.githubusercontent.com/16247628/30800413-346bd272-a1e0-11e7-8b33-0a37748a44ea.png">

**Comment by rubenmoya** [comment]
In production! 🚀
