### ISSUE TITLE
remove /explore section code

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#12879]
We have removed explore section so we should remove related code, like:

- https://github.com/CartoDB/cartodb/blob/master/app/controllers/explore_controller.rb
- https://github.com/CartoDB/cartodb/blob/master/lib/tasks/explore_api.rake
- https://github.com/CartoDB/cartodb/blob/master/lib/explore_api.rb
- https://github.com/CartoDB/cartodb/tree/master/lib/assets/javascripts/cartodb/explore
- https://github.com/CartoDB/cartodb/blob/master/lib/build/files/browserify_files.js#L17

and so on

**Comment by gonzaloriestra** [comment]
Already removed.
