### ISSUE TITLE
Always present analysis in vizjson for v3 visualizations

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#12885]
From https://github.com/CartoDB/cartodb.js/issues/1754

We have some v3 visualizations without analyses. This is causing some problems in cartodb.js, because in that case, the layer has no `source` and no `sql` in the vizjson 3. No `sql` is expected (because this is a named map) but it should have a `source`.

We need to:
- Ensure the editor -> builder migration process always adds the analyses
- Fix old visualizations (v3 without analysis):
  - For non-published ones, just add analysis
    Detect with `vv = Carto::Visualization.where(version: 3, type: 'derived', privacy: 'public').select { |v| v.analyses.none? }`
    Fix with: `v.add_source_analyses`
  - For published ones, add analysis to the mapcap, without editing anything else.
    Detect with: `Carto::Visualization.where(version: 3, type: 'derived', privacy: 'public').select { |v| v.mapcapped? && v.mapcaps.first.regenerate_visualization.analyses.none? }
` (SLOW, a few minutes)
    Fix with: https://github.com/CartoDB/cartodb/issues/12881#issuecomment-333062021

**Comment by juanignaciosl** [comment]
@alonsogarciapablo @Jesus89 we're reviewing priorities. It should be fixed, shouldn't it?

**Comment by Jesus89** [comment]
Yes :smile:, thanks!

If this is fixed it will unblock this ticket: https://github.com/CartoDB/cartodb.js/issues/1791

**Comment by alonsogarciapablo** [comment]
:+1:

**Comment by javitonino** [comment]
We merged this last week and I just checked that all current visualizations are OK. So we should be good.
