### ISSUE TITLE
"Show totals" button in torque time series disappears after map zoom-in 

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/cartodb#12904]
### Steps to Reproduce

1. Create a Torque layer
2. In the Time Series select "Show totals" in the menu
3. Zoom in the map (refresh time series)

![show-totals-disappear](https://user-images.githubusercontent.com/2227572/31168788-e327837a-a8f6-11e7-8992-ad61a2db997b.gif)

### Current Result
The "Show totals" button  has disappeared

### Expected result
The "Show totals" button must be shown

**Comment by ramiroaznar** [comment]
This is not happening anymore.
