### ISSUE TITLE
Histogram not resized on parent resize

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/cartodb#12917]
### Steps to Reproduce

1. Create an histogram widget
2. Resize the main window

### Current Result
The chart is not resized

### Expected result
The chart must be resized

![resize-histogram-widget](https://user-images.githubusercontent.com/2227572/31234351-f9448f56-a9ee-11e7-86f5-31649101e705.gif)

**Comment by ramiroaznar** [comment]
This is fixed as well.
