### ISSUE TITLE
External scripts are not being added in new dashboard load

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#12914]
It is likely I'm missing something and they are already added, but I want to ask it. I haven't found any clue about Google Analytics or TrackJS (for example) scripts in the new dashboard load.

@matallo @elenatorro

**Comment by matallo** [comment]
you're not missing anything, good catch! The thing is, despite the vendor scripts view isn't rendered in the dev tools I swear they are working.

In the migration process where we had to move from .erb to js templates, there was some inline js code, so we created the backbone view and the template which is fed with the vendor IDs.

I don't quite know the reason of those scripts not appearing but sure they work, just check the network tab. We personally encountered this in the review process, thanks for reporting!

**Comment by matallo** [comment]
so, give it some time if you fancy and manage to make them appear in the elements tab, otherwise feel free to close the issue

**Comment by xavijam** [comment]
One thing, I'm receiving a message from TrackJS in my console about there is not token set :S.

**Comment by elenatorro** [comment]
I'll check that 👍

**Comment by elenatorro** [comment]
Yes @xavijam you were totally right! There was an issue with TrackJS. I just opened a PR (https://github.com/CartoDB/cartodb/pull/12919). Thanks!!
