### ISSUE TITLE
Category and Formula widgets not properly toggled (horizontal)

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/cartodb#12918]
### Steps to Reproduce

1. Add a Category widget
2. Add a Formula widget
3. Add an Histogram widget
4. Resize until the widgets are in the bottom
5. Toggle each widget

### Current Result
The Category and Formula widgets are not properly toggled. The Histogram widget is toggled correctly.

### Expected result
The Category and Formula widgets must be toggled.

**Vertical toggle OK**

![v-widgets-toggle](https://user-images.githubusercontent.com/2227572/31234608-a172eb50-a9ef-11e7-831b-a93b3f411c2e.gif)

**Horizontal toggle BUG**

![h-widgets-toggle](https://user-images.githubusercontent.com/2227572/31234620-abe3fc46-a9ef-11e7-9e50-5bbcf249c072.gif)

**Comment by ramiroaznar** [comment]
This was already reported [here](https://github.com/CartoDB/support/issues/913).

**Comment by rubenmoya** [comment]
Fixed in https://github.com/CartoDB/cartodb/pull/13686

In production! 🚀

**Comment by ramiroaznar** [comment]
:boom:
