### ISSUE TITLE
Add related canonical visualization to vis endpoint

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartodb#12910]
In order to create the static public_map view, we need to have the related_canonical_visualization information for the "Datasets in use". We have thought that the best option is to add a parameter to the request to add this data (endpoint example: http://username.localhost.lan:3000/api/v1/viz/viz-id)

![captura de pantalla 2017-10-05 a las 10 09 17](https://user-images.githubusercontent.com/3824953/31216870-57613b28-a9b5-11e7-9489-ab137a6e4cd7.png)

- Datasets in use (public_map): [https://github.com/CartoDB/cartodb/blob/master/app/views/admin/visualizations/public_map.html.erb#L182](https://github.com/CartoDB/cartodb/blob/master/app/views/admin/visualizations/public_map.html.erb#L182) 
- Visualizations Controller [https://github.com/CartoDB/cartodb/blob/master/app/controllers/admin/visualizations_controller.rb#L274](https://github.com/CartoDB/cartodb/blob/master/app/controllers/admin/visualizations_controller.rb#L274)

**Comment by juanignaciosl** [comment]
Implementation note: keep in mind that related canonical visualization list should be optional, and that the entries should probably have the same structure than the requested visualization.
