### ISSUE TITLE
Add FS events to these elements

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#12912]
Design issue: https://github.com/CartoDB/design/issues/995

**Comment by xavijam** [comment]
Closing, already done!

**Comment by arianaescobar** [comment]
Uhm... let's talk about this one tomorrow @xavijam. Either I'm misunderstanding something or you are 😅

**Comment by xavijam** [comment]
Reopening, because there are still some missing classes.

**Comment by matallo** [comment]
gentle reminder that I need to know if we are adding new tracking classes: I think the `fs-*` prefix is a good choice for them

**Comment by arianaescobar** [comment]
I'm slowly confirming the necessary events, sorry for the delay.

- [ ] For the /signup page we only need an event for the GitHub button. 
- None needed on the /confirmation page
- [ ] In the dashboard initial screen we need an event to separate this "New Map" button in the footer from dashboard's main one after the onboarding: 

![screen shot 2017-10-25 at 12 00 26](https://user-images.githubusercontent.com/16247628/31993075-65297ab4-b97c-11e7-95f1-f8978501cd91.png)

I'll keep adding more as I confirm if we need them or not. Also, let me know if you have any question.

**Comment by arianaescobar** [comment]
In the Add dataset modal: 

- [ ] An event for the list items (only for that modal). Right now is being mixed up with the list items from the Dataset tab in Dashboard.

**Comment by arianaescobar** [comment]
Note: I haven't finished reviewing the events, I might add a few more. Sorry that it has taken me a while 😥

**Comment by arianaescobar** [comment]
In the "Connect dataset" tab of the Add dataset modal:

- [ ] Event in the lock icon right next to the "Connect dataset" button 
- [ ] Event in the "Connect" button of Google Drive
- [ ] Event in the "Connect" button of Dropbox
- [ ] Event in the "Connect" button of Box

That's all!

And again, sorry for the delay!

**Comment by matallo** [comment]
moving to development until new events are added (just pushed them, I'm checking something before sharing the selectors)

don't worry, and thanks a bunch! 🤗

**Comment by rubenmoya** [comment]
@arianaescobar keep in mind that the Github signup button is also the Github login button, so I'm not sure if this will be accurate enough

**Comment by rubenmoya** [comment]
In production! 🚀
