### ISSUE TITLE
Add hubspot form newsletter id to /me endpoint request

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartodb#12932]
In public maps, we have an input to subscribe to the newsletter. This input is generated by hubspot, but it needs a token to render it.

![captura de pantalla 2017-10-10 a las 12 21 02](https://user-images.githubusercontent.com/3824953/31381765-c1fa55f6-adb5-11e7-96c3-23b0cdd7f063.png)

This is what we currently have at `/api/v3/me`:

![captura de pantalla 2017-10-10 a las 12 23 37](https://user-images.githubusercontent.com/3824953/31381847-041c47be-adb6-11e7-9244-5c9ff0fb3738.png)

* Form id in `app_config.yml`: https://github.com/CartoDB/cartodb/blob/master/config/app_config.yml.sample#L89
* Public map footer:
https://github.com/CartoDB/cartodb/blob/master/app/views/admin/shared/_public_footer.html.erb#L13
* Hubspot form helper
https://github.com/CartoDB/cartodb/blob/master/app/helpers/application_helper.rb#L113

I was thinking the endpoint should return this value in 'hubspot_ids' *stringified* json, what do you think?

**Comment by juanignaciosl** [comment]
I'm not 100% sure, but I'd keep at `/me` the current configuration structure: 

```yarn
      form_ids:
        newsletter: ''
      event_ids:
        import_failed: ''
       ...
```

`hubspot_ids` come from `event_ids`. I have mixed feelings. We could add a new `form_newsletter` event at `hubspot_ids`,  or a new attribute `hubspot_forms` at the same level than `hubspot_ids` (which should've been `hubspot_events_ids`). For structure consistency, I'd do the latter, but I'm not 100% sure.

**Comment by elenatorro** [comment]
I agree with you 👍  what do you think @matallo @javitonino?

**Comment by javitonino** [comment]
Adding `hubspot_event_ids` sounds good to me. We can probably add it directly to the frontend config helper (which is used in `/me`).

**Comment by juanignaciosl** [comment]
Ey, it's not "adding `hubspot_event_ids` but `hubspot_forms_ids`. Current `hubspot_ids` attribute comes from `event_ids`. So, the less harm that we can do is adding `hubspot_forms_ids` from `form_ids`.

**Comment by javitonino** [comment]
My head is not what it used to be 🤦‍♂️ Yeah, I meant `form_ids` (updated my previous comment)

**Comment by amartinj** [comment]
I've seen that we are json-encoding some config values, but since it's fugly I'll not do it this time :)

**Comment by elenatorro** [comment]
You mean the `hubspot_ids`?

**Comment by amartinj** [comment]
For example, yes. There are some configs that are rendered as a json string, which I strongly dislike

**Comment by elenatorro** [comment]
Me too. It's good to take this into account because we'll need to change some things in the public views if this changes. Thanks!

**Comment by amartinj** [comment]
I won't change anything, but simply add this value as a json, not as a string ;). Just commenting because I'm _breaking coherence_. But since we all agree... 😄
