### ISSUE TITLE
geocoder in builder gives less accurate results compared to editor 

### ISSUE THREAD

**Issue by rossbernet** [CartoDB/cartodb#12946]
### Context
*Please explain here below what you were doing when the issue happened*
I used to love Carto's geocoder. Incredibly fast and accurate.
On my new builder account, it has not been successful yet.

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. sample fake dataset
[test_addy.txt](https://github.com/CartoDB/cartodb/files/1380473/test_addy.txt)
(...couldnt drop a csv here...so had to convert to .txt

2. use automated georeferencer - did it in old editor and builder.
3. be frustrated builder doenst work (I want to like builder, but I just dont mainly because of this)

### Current Result
*Please describe here below the current result you got*

4 for 4 in editor
![image](https://user-images.githubusercontent.com/8103418/31515782-6d15f724-af64-11e7-8198-4fa78a6f0056.png)

2 for 4 in builder

![image](https://user-images.githubusercontent.com/8103418/31515805-82b33cc2-af64-11e7-953f-0e2e10054477.png)

### Expected result
*Please describe here below what should be the expected behaviour*
Correct geocoder - as per editor

### Browser and version
*What internet browser (Chrome, Firefox, etc) and version was you using and version*
Chrome and firefox

### .carto file
*Don't forget to rename .carto file to .zip file to be able to upload to github*
_hmm maybe im not posting this in the place?_

### Additional info
*Please add any information of interest here below*
If this is the wrong place for this im sorry. Generally love Carto. So hopefully this geocoder bug is helpful info for yall! That was one of my favorite parts about old carto

**Comment by ramiroaznar** [comment]
Hey @rossbernet, first, CARTO's geocoder depends on the account plan (it looks like you are using a paid account with Editor, do not know about BUILDER). Secondly, the BUILDER geocoder analysis is not updating your original dataset, but you can still use CARTO's API SQL for this. Third and more importantly, for more questions about how CARTO works you can send us an email to support@carto.com, we will be happy to help you. Feel free to close the issue.

**Comment by rossbernet** [comment]
@ramiroaznar thanks for the info. I will follow up in an email if I have further questions.
