### ISSUE TITLE
Export and Import in SHP cuts date cells

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#1295]
From:

![image](https://cloud.githubusercontent.com/assets/1730320/5227435/86ca6a3c-76fb-11e4-9e4a-2e3bf48f582c.png)

To: 

![image](https://cloud.githubusercontent.com/assets/1730320/5227436/8bdc0350-76fb-11e4-8f75-de2b9135fcc8.png)

**Comment by rafatower** [comment]
Not sure if this ever worked as expected. Checking steps from API export through import.

**Comment by rafatower** [comment]
According to wikipedia, datetime is not supported by SHP format:
http://en.wikipedia.org/wiki/Shapefile
> Supported field types are: floating point (13 character storage), integer (4 or 9 character storage), date (no time storage; 8 character storage), and text (maximum 254 character storage)

**Comment by rafatower** [comment]
More on this:
http://www.esri.com/library/whitepapers/pdfs/shapefile.pdf
> Attributes are held in a dBASE® format file.

With a 2-row sample table:
```
$ file untitled_table_13*
untitled_table_13.cpg: ASCII text, with no line terminators
untitled_table_13.dbf: DBase 3 data file (2 records) <---
untitled_table_13.prj: ASCII text, with no line terminators
untitled_table_13.shp: ESRI Shapefile version 1000 length 78 type Point
untitled_table_13.shx: ESRI Shapefile version 1000 length 58 type Point
untitled_table_13.zip: Zip archive data, at least v2.0 to extract
```
Seems like `DBase 3` did not support dates: http://www.fileformat.info/format/corion-dbase-iii.htm

http://www.dbase.com/KnowledgeBase/int/db7_file_fmt.htm
> D	Date	8 bytes - date stored as a string in the format YYYYMMDD.

**Comment by rafatower** [comment]
It was a 'known problem', closing this...
