### ISSUE TITLE
Question: what does this error mean? 

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#12951]
While trying to georeference a dataset by lat&long, I got this error: 

`Analysis A1 failed: function st_makepoint(text, text) does not exist`

![screen shot 2017-10-16 at 12 05 08](https://user-images.githubusercontent.com/16247628/31607150-943f5cc8-b26b-11e7-91c5-5502bc3be1e8.png)

I'm not too sure of who to ask (so let me know if I need to ask somewhere else), but, in case it is here... what does that error mean?

**Comment by ramiroaznar** [comment]
PostGIS `ST_MakePoint` (which runs behind the scenes when applying Georeference analysis with Lat/Long option)  need numeric fields as arguments. You need to convert both columns using the UI or SQL (`SELECT *, latitude::numeric, longitude::numeric from populated_places_usa`).

**Comment by arianaescobar** [comment]
Great, thanks @ramiroaznar! I will create a new ticket in our design repo to come up with a more user-friendly message for that error notification :)
