### ISSUE TITLE
Disable limits notification

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#12968]
We introduce it in [this PR](https://github.com/CartoDB/cartodb/pull/12890/files) and we have checked that we can't display the infobox each time a tile fails, without knowing the type of the problem. It could be any problem with the server, connectivity issue, limits,...

Place where the discussion started -> https://github.com/CartoDB/cartodb/pull/12890/files#diff-4c52b5000fde47e73c06414652d8ed45R43

**Comment by rjimenezda** [comment]
I'll completely remove the error for now.

We could re-enable it and change the copy to something less worrying as long as limits are not active.

In any case, we need to improve our error strategy.

**Comment by xavijam** [comment]
agree

**Comment by rjimenezda** [comment]
🚢
