### ISSUE TITLE
google_plus button not working in static account view

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#12963]
in the final migration and tests for the static account view I noticed the google_plus button integration wasn't quite working as expected becase inside the `signinCallback` there's a `parentInSameDomain` check which is returning an error

https://github.com/CartoDB/cartodb/blob/2fb78d3ad2cd5bb7c481baf22c6288392c82fc97/app/views/google_plus/google_plus.html.erb#L5-L29

the blame line is the method `parent.document` which returns the aforementioned error

```
Uncaught DOMException: Blocked a frame with origin "https://carto-staging.com" from accessing a cross-origin frame.
    at parentInSameDomain (https://carto-staging.com/google_plus:87:23)
    at signinCallback (https://carto-staging.com/google_plus:67:26)
```
because

```
'matatarui.carto-staging.com' !== 'carto-staging.com'
```

making some [research](https://stackoverflow.com/questions/25098021/securityerror-blocked-a-frame-with-origin-from-accessing-a-cross-origin-frame), it is suggested to make use of `postMessage` for inter-document communication in the window frames but due to the specifics of our view (remember we're rendering an iframe within a js template via a js script) it is not straight forward, doing some tests https://github.com/CartoDB/cartodb/pull/12749/commits/442a000bfb20ed979b3ff771eb05cd4c1614b146 wich I then reverted we stumble upon another blocker

```
Uncaught TypeError: Cannot read property 'contentWindow' of null
```

as at the moment when the template is rendered 

```
  var frame = document.getElementById('googleIframe');
  frame.contentWindow.postMessage(null, '*');
```

`frame` isn't defined.

I didn't really digged into the problem to see if I can find a workaround, and after asking @javitonino this might be the straw that break the camel's back in order to make this right.

I left the issue reproduced in ruis cloud, we might consider taking this move now, as the static account view is not as priority as others and it could wait to have this button updated.

Thoughts @juanignaciosl ?

**Comment by javitonino** [comment]
I suggested moving this to backend (such as the GH login). Makes this issue disappear completely (as JS doesn't care) and is something that I think is long overdue.

**Comment by matallo** [comment]
🙏

**Comment by juanignaciosl** [comment]
Moving it to backend is _the_ solution. It should also improve the UI interaction.

I'll add this to the kanban right now.
