### ISSUE TITLE
Selected tab style is weird

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#12978]
![screen shot 2017-10-20 at 12 32 17](https://user-images.githubusercontent.com/132146/31817069-e6837896-b592-11e7-8fd0-49813d369295.png)

Taken from my production account, using Chrome v62.0.3 in Mac OS X.

cc @CartoDB/frontend any clue?

**Comment by rubenmoya** [comment]
Not happening to me in production, using `Version 61.0.3163.100 (Official Build) (64-bit)
`

**Comment by rubenmoya** [comment]
In production! 🚀
