### ISSUE TITLE
add webpack config for Protected Public Maps static view

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartodb#12976]
### Context

Create the public page `protected_public_map`

![captura de pantalla 2017-10-20 a las 9 13 16](https://user-images.githubusercontent.com/3824953/31809233-fcb46e5c-b576-11e7-9ec1-e9560f1c93e3.png)
![captura de pantalla 2017-10-20 a las 9 13 23](https://user-images.githubusercontent.com/3824953/31809234-fce95e8c-b576-11e7-95a4-2b896e20d9a3.png)

### Steps to Reproduce
1. Create a user or use an existing one
3. Create feature flag `static_public_map` https://github.com/CartoDB/cartodb-management/wiki/Feature-Flags
4. Change user permissions:
```
$ bundle exec rails c 
$ user = User.where[username: 'username']
$ user.builder_enabled = false
$ user.account_type = [PRO]
$ user.private_maps_enabled = true
$ user.save()
```

5. Create a new map
6. Change map permissions to *password protected*

Related files:
* Controller: https://github.com/CartoDB/cartodb/blob/master/app/controllers/admin/visualizations_controller.rb#L437
* Template: https://github.com/CartoDB/cartodb/blob/master/app/views/layouts/application_password_layout.html.erb

**Comment by nobuti** [comment]
@amartinj do you know if we have any endpoint to check the password for a visualization?

**Comment by amartinj** [comment]
I'd say we don't. @javitonino do we?

**Comment by javitonino** [comment]
Sort of. We added support to the main visualizations controller in here: https://github.com/CartoDB/cartodb/issues/12908

If you pass an invalid password, you get an error. If you pass the correct password, you get the whole visualization metadata.

**Comment by amartinj** [comment]
I would not use that one, would you?

**Comment by javitonino** [comment]
Why not? We designed it for this purpose. If you put in the wrong password, you get an error. If you put the right password, you get all the info you need to draw the map without doing a second request. I'm assuming that you are going to draw the map with that same JS (i.e: you are not going to do a redirection).

**Comment by amartinj** [comment]
I was guessing they just wanted to know if the password was correct or not...

**Comment by javitonino** [comment]
In any case, there is no need to add a second controller just to check the password, if the one we have already does it. I think the single controller approach is more RESTful (as opposed to a more RPC-like approach). And nobody is going to complain about 1kb of json in the times we live in (I'm a bit sad about that :P)

**Comment by amartinj** [comment]
I was thinking more on overprocessing stuff and rendering... but okay. Tradeoffs... tradeoffs everywhere...

**Comment by nobuti** [comment]
Thanks, guys!
