### ISSUE TITLE
The average number of geometries vertex is greater than 1000

### ISSUE THREAD

**Issue by michellemho** [CartoDB/cartodb#12975]
### Context
Attempted to run Data Observatory analysis through the Builder UI. Ran into error I haven't encountered before

![image](https://user-images.githubusercontent.com/12551177/31793612-b9761ec6-b4ed-11e7-865e-3d8c050fc7ee.png)

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Use table of geometries that are US Counties
2. Apply a "Aggregate Intersection" to the counties to only select a few that intersect a separate points layer
3. Attempt to augment total population from Data Observatory (in screenshot above)

### Current Result
*Please describe here below the current result you got*
Error returned is: "The average number of geometries vertex is greater than 1000, please try to simplify them"

### Expected result
*Please describe here below what should be the expected behaviour*
Expected an additional column added to counties dataset with total population.

### Browser and version
*What internet browser (Chrome, Firefox, etc) and version was you using and version*
Chrome

**Comment by ramiroaznar** [comment]
Hey @michellechandra, this was already [reported in support](https://github.com/CartoDB/support/issues/975). You can use the workaround from the meanwhile:

Workaround to apply when a user is compaining about this issue:

1. Export AOI layer as shapefile.
2. Import it into CARTO.
3. Apply this handy query:

```sql
WITH a as (
  SELECT ST_GeometryN(the_geom, generate_series(1,ST_NumGeometries(the_geom))) as the_geom FROM influencias_combinadas)
SELECT 
  row_number() over() as cartodb_id, 
  the_geom
FROM
  a
```

4. Create a new table from query.
5. Add it again to the original BUILDER map.
6. Apply DO analysis. If it fails, try to simplify the geometries.

**Comment by michellemho** [comment]
@ramiroaznar, thanks for your response. I will read and comment on the issue in Support. By the way, this is Michelle Ho, not Michelle Chandra!

**Comment by ramiroaznar** [comment]
@michellemho autofill fault! Read carefully the issue because it is still open, you can ping Nacho if you want to reopen the debate.
