### ISSUE TITLE
Common data cache doesn't save requests

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#12987]
We have a cache for common data, but it is not very useful, since the HTTP request is done anyway, see the code: https://github.com/CartoDB/cartodb/blob/master/app/models/common_data.rb#L76-L87

Proper check would be to query the cache before doing the request.

**Comment by javitonino** [comment]
cc @juanignaciosl (probably backlog material)

**Comment by juanignaciosl** [comment]
@javitonino (sorry about asking without debugging myself) are you sure that the request is performed?

**Comment by javitonino** [comment]
Oh, `request.run` is run afterwards. Sorry for this, I'm the worst. Debugging yesterday got a bit crazy. Sorry!
