### ISSUE TITLE
F/B pages migration

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#12986]
| PHASE | VIEW| COMPLETED | MILESTONE| FEATURE FLAG|
|-------|--------|-----------|--------------|-------|
| 1     | Dashboard               |    [x]       | [Link](https://github.com/CartoDB/cartodb/milestone/144) | static_dashboard |
| 1     | Profile                 |     [x]      | [Link](https://github.com/CartoDB/cartodb/milestone/145) | static_profile |
| 1     | Account                 |     [x]     | [Link](https://github.com/CartoDB/cartodb/milestone/150) | static_account |
|       |                         |           |                                                          | |
| 2     | Public Map              |     [x]     | [Link](https://github.com/CartoDB/cartodb/milestone/146) | static_public_map |
| 2     | Password Protected Map  |    [x]    | [Link](https://github.com/CartoDB/cartodb/milestone/146)  | static_public_map |
| 2    | Editor (Dataset + Map views) |    [x]       | [Link](https://github.com/CartoDB/cartodb/milestone/152)  |static_editor |
| 2     | Embed Map               |    [x]    |  [Link](https://github.com/CartoDB/cartodb/milestone/151)                                                        | static_embed_map |
| 2     | ~Data Library~*            |           |                                                          ||
|       |                         |           |                                                          | |
| ?     | Builder                 |           |                                                          | |
| ?     | Builder dataset                |           |                                                          | |
| ?     | Builder embed           |           |                                                          | |
| ?     | Organization            |           |                                                          | |
| ?     | Public Maps             |           |                                                          | |
| ?     | Public Dataset          |           |                                                          | |
| ?     | Public Datasets         |           |                                                          | |
| ?     | Api Keys                |           |                                                          | |
| ?     | Mobile Apps             |           |                                                          | |

?: Out of scope
*: It belongs to the Dashboard view
Phase 1: 15th November
Phase 2: 15th December
Phase 3: ?
Phase 4: ?

**Comment by xavijam** [comment]
I feel those are all the views in CartoDB application. @gfiorav could you review with Buti and Elena which are the most important ones? Basically, prioritize them. And if there is any doubt, let's discuss here. Also, if we feel there is no need to "migrate" any, let us know.

**Comment by xavijam** [comment]
cc @alissarose

**Comment by alissarose** [comment]
Hi hi! Below is the priorities we signed off on w/Bloomberg based on a demo of their typical user flows. I'm not clear on some of the views and we can do a walk-through on a VM to finalize this.

I think we're getting close to wrapping up Phase 1, so we should find time to go through the remaining view+priorities to align on the timeline for Phase 2, 3, etc.

thanks!!
cc/ @xavijam @gfiorav 

## Pages migration

### Phase 1
>> We're to use the experience/timing of each of these views to then estimate turnaround for the following phases/views til complete
1. [Dashboard](https://github.com/CartoDB/cartodb/milestone/144) (editor)
2. [Profile](https://github.com/CartoDB/cartodb/milestone/145) (forms)
3. [Public Map](https://github.com/CartoDB/cartodb/milestone/146)

### Phase 2
1. Data Library (I'm not 100% clear on the views required for this piece)
2. Advanced Edit (I'm not sure what views are required here)

### TBPrioritized
- [Account]()
- [Api Keys]()
- [Mobile apps]()
- [Organization](): It has several views:
   - Organization profile
   - Auth settings
   - Users
   - Groups
   - Notifications
- [Editor]().
- [Public Maps]() -> http://xavijam.carto.com/maps
- [Public Datasets]() -> http://xavijam.carto.com/datasets
- [Public Dashboard](): It is the user-feed -> http://xavijam.carto.com/me
- [Public Dataset]().
- [Embed map]() -> Embed for editor
- [Password Protected Map](https://github.com/CartoDB/cartodb/milestone/149)
- [Builder]() -> 
- [Builder embed]() -> Embed for builder

**Comment by xavijam** [comment]
OK, I've updated the description with a table and adding the phase info. @alissarose could "advanced edit" the editor view? I feel it is that, but it would be great if you can confirm it, thanks 💋 .

**Comment by xavijam** [comment]
Also, it would be great if we can define what they mean with Data Library (there are two options there) 💋 .

**Comment by matallo** [comment]
> Also, it would be great if we can define what they mean with Data Library (there are two options there) 💋 .

Yep, they have a custom data library that is a whole new view (that we don't have, at least as they show it)

**Comment by xavijam** [comment]
Ha!, if so, we should not take care of it (per se).

**Comment by matallo** [comment]
indeed, paging @gfiorav 

the idea is to provide an example that can be replicated witht he rest of the views (in the ase at use: dashboard)

**Comment by gfiorav** [comment]
Hey guys, just for a bit of background. There're two different things:

1. "Mapsdata" which is the same as our "Common Data" for all intents and purposes of this project
2. "Sample maps" which is a gallery of created maps that the user can "copy" into its account.

The latter is an iteration of the public page. It's really just showing the public maps of a special user (sample-maps user).

For that reason, I feel we should take care of the public maps page migration, and then (as @xavijam is suggesting) it would be fair to leave them to do that migration.

**Comment by juanignaciosl** [comment]
@xavijam @elenatorro as this is a nice global picture of the project, maybe this could be closed and merged into the F/B Split epic. What do you think?

**Comment by xavijam** [comment]
Please, leave it until we explain the other "meta" issue to @alissarose. Thanks and sorry!
