### ISSUE TITLE
Move "Edit layer" to the first option of layer's contextual menu

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#12999]
### Context

While doing Usability tests, we've identified a common user behavior of accessing a layer through the "Edit layer" option of the contextual menu. We just want to streamline that flow by moving the action to the top of the list.   

### Current Result

![screen shot 2017-10-27 at 10 48 42](https://user-images.githubusercontent.com/16247628/32095877-f5b922da-bb04-11e7-91f7-e7b96ea60121.png)

### Expected result

**Edit layer** will appear on top of **Collapse**.

**Comment by rubenmoya** [comment]
In production! :rocket:

**Comment by arianaescobar** [comment]
As of today:

**Previous version:** From 20k users, 17% of interaction. 
**Current version:** From 10k users, 13% of interaction.
