### ISSUE TITLE
Signup invitation fails when the user has more than one active invitation.

### ISSUE THREAD

**Issue by dgaubert** [CartoDB/cartodb#12995]
### Context
Coming from https://github.com/CartoDB/support/issues/1042

When a user that has been invited to signup to CARTO via email has more than one active invitation then invitation's token validation fails due to Builder mismatch invitations and tries to validate token from different invitations.

### Steps to Reproduce

1. Send an invitation to a new user (unused email)
2. Repeat 1
3. Use the second invitation to signup

### Current Result
After filling required fields and clicking signup, Builder returns the following error:

![token](https://user-images.githubusercontent.com/1936888/32042789-10a2944a-ba39-11e7-8463-bf33f91d7bf1.jpeg)

### Expected result
The user should be able to signup.

### Browser and version
N/A

### .carto file
N/A

**Comment by javitonino** [comment]
I was taking a look at this and it seems to be fixed. At least I could not reproduce with the STR. Given that we have made some PRs in the last 6 months to address issues with the invitation system, it's likely that it got fixed along the way :)

**Comment by gonzaloriestra** [comment]
This is still happening.

- Recent ticket: https://github.com/CartoDB/support/issues/1750
- [Rollbar ocurrences](https://rollbar.com/carto/CartoDB/items/?activated_from=&activated_to=&assigned_user=&date_from=&date_to=&framework=&environment=production&level=critical&level=error&level=warning&level=info&level=debug&offset=0&enc_query=o5MK614XotskIrdaihHqGzcMWlxGPHRGgKt%2BR1L0%2BSw%3D&sort=last_desc&status=active)

@CartoDB/rt-managers
