### ISSUE TITLE
Consolidate carto-api-client

### ISSUE THREAD

**Issue by nobuti** [CartoDB/cartodb#12990]
Right now the lib's folder inside the base code is a bit confusing. It's different in master than a couples topic branches. Also the specs need this folder location revamp as well. We need to tackle:

- [x] consolidate carto-api-client source code folder and move it to a new repository
- [x] fix the webpack configuration with that changes above
- [x] integrate the new library in cartodb 

  
- [ ] consolidate all the specs

**Comment by alrocar** [comment]
Stale issue. Closing 👋
