### ISSUE TITLE
Wrong padding in widget list

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#12996]
If you go to a widget list there is a lot of space on the left side.

![image](https://user-images.githubusercontent.com/1214201/32045159-daeb632a-ba3f-11e7-95a1-fe1363298051.png)

![image](https://user-images.githubusercontent.com/1214201/32045210-fc18d9b0-ba3f-11e7-87b6-0b5d48ed2b57.png)

**Comment by ramiroaznar** [comment]
This can be fixed at the same time with #12860.

**Comment by piensaenpixel** [comment]
Ping!

**Comment by ramiroaznar** [comment]
Closing in favor of https://github.com/CartoDB/cartodb/issues/13200
