### ISSUE TITLE
Remove basemap's labels layer from layer list

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13000]
### Context

To avoid confusion we are going to stop showing the basemap's labels layer in the layer list altogether.  

### Current Result

![screen shot 2017-10-27 at 11 08 28](https://user-images.githubusercontent.com/16247628/32096625-4851ad4e-bb07-11e7-9a2d-02b561a19895.png)

### Expected result

"Voyager labels" layer won't appear on the list.

**Comment by rubenmoya** [comment]
In production! :rocket:

**Comment by matallo** [comment]
> Closed #13000 <https://github.com/CartoDB/cartodb/issues/13000>.

BOOM
