### ISSUE TITLE
Changes in the onboarding tours

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13003]
We've seen that people don't normally check the "Do not show me this again" thing, and then the onboarding messages keep annoying them forever when they change between tabs inside a layer. To avoid that, lets: 

- [x] Only show those messages once and never again
- [x] Remove the "Do not show me this again" check from all the onboarding messages (since we're only going to show them once, we don't need that check anymore).

**Comment by matallo** [comment]
in production! 🚀
