### ISSUE TITLE
Stop adding legends automatically when styling a layer

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13002]
Right now, certain styles make the legends appear automatically, like when changing the point size by value. We want to disable that mechanism and only add legends when the users choose to do so from the Legends tab.

**Comment by xavijam** [comment]
Really? Does it belong to the onboarding process? 🤔

**Comment by piensaenpixel** [comment]
A kind of @xavijam In the interviews people don't know why it appears without doing anything, also in FS and the interviews the problem it's that the user usually has a small screen resolution and if we show directly it hides a lot of map.

**Comment by xavijam** [comment]
What a pity, I really love that legend magic cc @nobuti :(.

**Comment by arianaescobar** [comment]
Maybe we could rethink it and show a notification asking the users if they would like to add the corresponding legend instead of just adding them without their consent. Or something like that.

**Comment by matallo** [comment]
I'm working in the tests already :(

On Nov 7, 2017 2:10 PM, "Ariana Escobar" <notifications@github.com> wrote:

Maybe we could rethink it and show a notification asking the users if they
would like to add the corresponding legend instead of just adding them
without their consent. Or something like that.

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/CartoDB/cartodb/issues/13002#issuecomment-342477501>,
or mute the thread

**Comment by arianaescobar** [comment]
Don't worry :) It was just an idea for later on, we should think it through first.

**Comment by csobier** [comment]
+1. We heavily document that styling BY VALUE auto-generates legends. We get more complaints from users about the fixed size and position of legends, more so than the automatically generated legends (that is typically an education-only issue). 

I love the idea of testing some dialog before changing the functionality of this feature. For example, "_Styling by value automatically creates legends. Manage legends from the LEGEND tab or disable legends from the Map Options._"

**Comment by arianaescobar** [comment]
I don't think we have any place in the UI to show that amount of dialog for that feature, though... 

I do understand your concern about the documentation but we shouldn't let it dictate further enhancements of the product. Solving that fixed size or position thing will require waaaay more work and time than what we can invest in it right now.

**Comment by rubenmoya** [comment]
In production! 🚀

**Comment by matallo** [comment]
BOOM

**Comment by xavijam** [comment]
I'll miss you automatic legends :(
