### ISSUE TITLE
Change "None" to "Points" in the aggregation methods

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13001]
### Current Result

![screen shot 2017-10-27 at 11 12 58](https://user-images.githubusercontent.com/16247628/32096819-e4297bf2-bb07-11e7-881e-36930106f61e.png)

### Expected result

Below Aggregation, instead of "None" it should say "Points".

**Comment by rubenmoya** [comment]
In production! :rocket:

**Comment by arianaescobar** [comment]
VAMOS!!
