### ISSUE TITLE
Line labels placement does not work

### ISSUE THREAD

**Issue by jaakla** [CartoDB/cartodb#13015]
### Context

Add Labels to a Line layer, simple layer style, try to add labels and use different placement from point. Only points works, but not others if I change it from GUI. Changing from CartoCSS works, so the issue seems to be that Builder GUI does not update CartoCSS side for this parameter. Tried with several datasets, same result.

### Steps to Reproduce

1. Add a layer with line data
2. Enable "Labels", select some field to label it. You see labels on map.
3. Change label placement type from **point** to **line** 
4. Check map  - labels do not change, even if "line" they should look different, rotated by lines
5. Check CartoCSS - it does did change `text-placement: point;` parameter. Remains always to _point_, even if I select _line_, _vertex_ or _interior_.
6. Change manually CartoCSS with `text-placement: line;` and update map - now labels on map are changed as expected.

### Current result

![image](https://user-images.githubusercontent.com/5215798/32182976-4f1e475c-bd98-11e7-992e-2a48bb3cb2a1.png)

### Expected result

![image](https://user-images.githubusercontent.com/5215798/32183001-612ab7aa-bd98-11e7-8b08-5e9d2fb8a753.png)

### Browser and version
* Mac Chrome Version 61.0.3163.100 (Official Build) (64-bit)

### .carto

* [Line labels (on 2017-10-30 at 16.31.27).carto.zip](https://github.com/CartoDB/cartodb/files/1427953/Line.labels.on.2017-10-30.at.16.31.27.carto.zip)

**Comment by ramiroaznar** [comment]
@jaakla good catch! I am going to add more details to your issue.

**Comment by ramiroaznar** [comment]
cc @makella

**Comment by xavijam** [comment]
In production, close it whenever you consider mates.

**Comment by ramiroaznar** [comment]
Vamos!
