### ISSUE TITLE
Remove geometries and rows count on public pages

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartodb#13016]
### Context

In public_maps page, there is a section where the datasets are listed ([example](https://team.carto.com/u/matallo/viz/ae2c6e74-ecce-11e4-a952-0e49835281d6/public_map)) Each dataset has, between others, an image that represents de geometry and the number of rows. We're re-building this view for the frontend/backend split, and we currently don't have this information available.

<img width="1036" alt="captura de pantalla 2017-10-30 a las 16 33 09" src="https://user-images.githubusercontent.com/3824953/32179591-19fda1ec-bd90-11e7-9b52-ad3f8b9bcc99.png">

One solution is to remove this information from the view, and we need to discuss with product if this is posible.

cc @noguerol, @javitonino, @nobuti

**Comment by javitonino** [comment]
> we currently don't have this information available.

The information is actually available. But it implies a query to the user database. This is slow and can cause problems with the platform (if the database is down for any reason), so we want to avoid it if possible.

**Comment by noguerol** [comment]
We should remove it.

**Comment by nobuti** [comment]
Done in #12928.
