### ISSUE TITLE
Show infobox for interactivity in builder

### ISSUE THREAD

**Issue by rubenmoya** [CartoDB/cartodb#13028]
When the user reaches its limits, interactivity could be affected, and CARTO.js will trigger an error. 

We should handle that error and show an infobox in Builder with the message `Looks like you are over your account limits and the interactivity of your map could be affected`

**Comment by rubenmoya** [comment]
Blocked until https://github.com/CartoDB/cartodb.js/pull/1864 is merged

**Comment by rubenmoya** [comment]
Not blocked anymore, we're not removing wax yet

**Comment by rjimenezda** [comment]
@noguerol 

Hey, so this is working pretty well. I only have a minor worry, when the error triggers (while moving the mouse around the map), the user gets the infobox on the layer list. If said user discards the infobox, it doesn't show again unless you navigate to a layer and go back to the layer list.

Is this OK? Or should we do something smarter regarding discarding / remembering the errors.

**Comment by rjimenezda** [comment]
On ded12
