### ISSUE TITLE
There's an extra left margin in the widgets list

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13048]
![screen shot 2017-11-07 at 12 37 13](https://user-images.githubusercontent.com/16247628/32502232-f040a366-c3b8-11e7-9e56-af6c8865e67d.png)

The one to the left of the illustration. It should have the same as it has on top and bottom.

**Comment by piensaenpixel** [comment]
duplicated - https://github.com/CartoDB/cartodb/issues/12996
Thanks ari!
