### ISSUE TITLE
Group Points into Polygons Analysis Produces Line Geometries, not Polygons (regression)

### ISSUE THREAD

**Issue by andrewbt** [CartoDB/cartodb#13041]
### Context
*Please explain here below what you were doing when the issue happened*

I had a point dataset, applied the "group points into polygons" analysis, and instead of producing convex hull polygons (as it has in the past, and should), the `the_geom` column is of Lines, they render as Lines and the CartoCSS has line properties (making it hard to use polygon-fill, etc). This analysis used to produce Polygons, and it should be reverted to keep doing so as that is the expected result.

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1.
2.
3.

### Current Result
*Please describe here below the current result you got*

### Expected result
*Please describe here below what should be the expected behaviour*

### Browser and version
*What internet browser (Chrome, Firefox, etc) and version was you using and version*

### .carto file
*Don't forget to rename .carto file to .zip file to be able to upload to github*

### Additional info
*Please add any information of interest here below*

**Comment by ramiroaznar** [comment]
Hey @andrewbt can you shared the .carto file of your map. I have tested with a sample dataset and it works like a charm:

![image](https://user-images.githubusercontent.com/5215798/32489477-6d219646-c3b0-11e7-9e47-b9fd7b0764fb.png)

![image](https://user-images.githubusercontent.com/5215798/32489492-7a76fa52-c3b0-11e7-91b3-c81a3731d76d.png)

My guess, your dataset has 2 points!

**Comment by ramiroaznar** [comment]
After testing Andrew's map, it looks like one of the categories has 5 points but with just two lat/longs values. Because CARTO datasets/layers can only store one type of geometry, all the rest of categories are also drawn as lines.
