### ISSUE TITLE
Change "Edit" to "Add" in panel header when adding a new geometry

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13049]
When you're manually adding a new geometry, the panel header says "**Edit point**/line/polygon". It should say "**Add point**/line/polygon" instead. 

![screen shot 2017-11-07 at 12 54 02](https://user-images.githubusercontent.com/16247628/32509415-fa24523e-c3cb-11e7-8312-e541e065a0ab.png)

**Comment by jesusbotella** [comment]
Deployed to the production environment! 👏

**Comment by arianaescobar** [comment]
Great! Thank you :)
