### ISSUE TITLE
error installing Carto on ubuntu 16.04

### ISSUE THREAD

**Issue by leyawang** [CartoDB/cartodb#13054]
I followed the document here to install Carto:
http://cartodb.readthedocs.io/en/latest/install.html

1. when doing 
"sudo add-apt-repository ppa:cartodb/gis && sudo apt-get update", 
it seems that some of links is not available
![image](https://user-images.githubusercontent.com/10204462/32652485-63e0953c-c63f-11e7-9fdb-0e2bf17dcada.png)

2. then failed when "apt-get install gdal2.1-static-bin"
![image](https://user-images.githubusercontent.com/10204462/32652515-780e071a-c63f-11e7-94d3-9f0e0156b386.png)

do you have any sugguestions for this?

**Comment by javitonino** [comment]
Hi!

This repository is for issues related to the product itself, not the installation process. I'd suggest you try the mailing list, where you can get help for this kind of issue: https://groups.google.com/forum/#!forum/cartodb

Thanks!
