### ISSUE TITLE
No error messaging in org signup when username validation fails

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#13053]
### Steps to Reproduce
1. Go to org signup
2. Write a long username (>63 chars)

### Current Result
Signup fails without error. The validation is only done in central, and messaging in that case is not very good.

![screenshot_20171110_103403](https://user-images.githubusercontent.com/7569673/32651887-b9558262-c602-11e7-8583-8483bb5b5689.png)

### Expected result
Pretty error displayed.

Related: https://github.com/CartoDB/cartodb-central/issues/1828

**Comment by AleGoiko** [comment]
also, last minute request: pretty error if user exists on central
