### ISSUE TITLE
Treat timestamps of a histogram dataview as UTC

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#13070]
### Context

In Time series dataviews, we are parsing the data coming from the API and making a translation of timestamps using the current selected offset.

Although it seems to be working, it's provoking some errors with filtering. Windshaft expects all timestamps in UTC so in order to get translated ones we need to be doing conversions in both directions in several places.

### Solution

Don't apply offsets to parsed payload and only make a conversion when showing the formatted timestamp to the user.

### Related issues

https://github.com/CartoDB/cartodb/issues/12637

### Datasets

This dataset contains two points: one at 2 Jan 1970 00:00 UTC and another one at 2 Jan 1970 01:00 UTC. Useful for seeing changes after changing timezone.

[dospuntos copy.txt](https://github.com/CartoDB/cartodb/files/1470103/dospuntos.copy.txt)

### Acceptance (how to)

Builder
- [ ] Using a dataset (the one above, for instance) create a time series widget. Test several combinations of aggregations and timezones. Check that chart changes and chart ticks and filter labels are properly formatted.
- [ ] Check also that setting the widget in `local timezone` changes ticks and labels. This is better shown in hour aggregations.
- [ ] Do the same checks in a torque widget.

Embed
- [ ] Repeat the Builder checks in an embed view.

### Known bugs

In some aggregations, filtering does not work properly. Using the attached dataset if you aggregate by day and set an UTC - 1 offset you can see it. That's provoked by how the API is making the aggregation.
Ticket: https://github.com/CartoDB/Windshaft-cartodb/issues/792

In any case, if you find something strange, please write it in this ticket.

**Comment by rubenmoya** [comment]
Using the dataset you provided with this parameters: 
![screen shot 2017-11-14 at 12 14 03](https://user-images.githubusercontent.com/905225/32777142-5739d570-c935-11e7-8892-717201e664a5.png)

It creates 2 buckets, one of them empty:
![screen shot 2017-11-14 at 12 13 55](https://user-images.githubusercontent.com/905225/32777139-57215c52-c935-11e7-84d9-f339f9586dbc.png)

Is that the expected behavior? @ivanmalagon

**Comment by ivanmalagon** [comment]
It's not but it is what it is. The API returns two buckets, one of them empty. At least in that case if filtering is consistent with the points it's good enough.

**Comment by ivanmalagon** [comment]
Related ticket to that https://github.com/CartoDB/Windshaft-cartodb/issues/732

**Comment by rubenmoya** [comment]
This is a tricky one, using
```
1970-01-01T00:00:00Z
1970-01-01T01:00:00Z
```

with this parameters

![screen shot 2017-11-14 at 12 14 03](https://user-images.githubusercontent.com/905225/32777142-5739d570-c935-11e7-8892-717201e664a5.png)

results in this, it says there are two buckets, with one point in each one, but when filtering there is none in the first bucket but two in the second one

![timeseries](https://user-images.githubusercontent.com/905225/32777336-112a516c-c936-11e7-994a-2b7852d102f5.gif)

**Comment by rubenmoya** [comment]
I can't find anything else besides the current known bug :)

**Comment by ivanmalagon** [comment]
Bug mentioned above in https://github.com/CartoDB/cartodb/issues/13070#issuecomment-344228542 fixed with the closing of [Windshaft #792](https://github.com/CartoDB/Windshaft-cartodb/issues/792)
