### ISSUE TITLE
Add trial notification to FE/BE split

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#13079]
Migrate the changes from https://github.com/CartoDB/cartodb/pull/13060 to FE/BE split. We think it's better to finish the FE/BE tasks related to private dashboard (dashboard + profile + account + maybe some others?)before doing this, to avoid conflicts with ongoing work.

There is no hurry on this, but must be done before making FE/BE generally available. 

cc @elenatorro @juanignaciosl

**Comment by elenatorro** [comment]
There's no other FE/BE split related to private dashboard right now than the ones you've already mentioned. I think we can make these changes when the **account page** is merged 👍
