### ISSUE TITLE
Add hover to UI Elements

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#13074]
### Context
![](https://user-images.githubusercontent.com/14546701/32537541-45009d48-c463-11e7-9b5c-501ada3b2409.png)

Design Ticket: https://github.com/CartoDB/design/issues/1035

**Comment by rubenmoya** [comment]
I'm guessing in the case of buttons this applies to every style right? `primary`, `error`, `alert`, etc

**Comment by urbanphes** [comment]
Question solved @rubenmoya

**Comment by rubenmoya** [comment]
Deployed to `ded10`, I'd love if you could give us some feedback @CartoDB/design ❤️

**Comment by josecruz** [comment]
Superb @rubenmoya!

Two quick things:

1. I think we forgot to add the active state to the forms 😅 . Hover is blue and active is black (`#2E3C43`)
![image](https://user-images.githubusercontent.com/596509/33263469-468f2574-d36a-11e7-9bf2-708cfd149927.png)

2. Related to the forms, something weird happens with the line when you select one of the inputs:
 - When I click on the first input and hover on the second one, there's a 2px blue line between them
 - When I click on the second input you can see an uncolored line but if you keep hovering the input it will display ok
![500](https://user-images.githubusercontent.com/596509/33263502-688922c4-d36a-11e7-9d30-d178c4a63fdb.gif)

**Comment by matallo** [comment]
back to dev!

**Comment by josecruz** [comment]
Greeeat guys! Above things are fixed but found another one:

1- When you `hover` an `active` input it turns back to `hover`. It should keep as `active`
2- When I click on a dropdown input, there's no `active` state until I close it
![501](https://user-images.githubusercontent.com/596509/33280337-ff8bdd88-d3a1-11e7-83ba-446b6ea180fb.gif)

**Comment by rubenmoya** [comment]
That's probably because we lose focus of the input when focusing on the "search" one in the dropdown
