### ISSUE TITLE
Export Image doesn't work on private maps for org users in the editor

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#13089]
### Steps to Reproduce

1. Being an org user and in the builder open a map.
2. Make the map private if it isn't already.
3. Click on Export Image
4. Export any selection of the map

### Current Result

The map instantiation fails, so does the export

### Expected result

The image exports

**Comment by ztephm** [comment]
S/B 14966014 should be notified if this is fixed please.

**Comment by gfiorav** [comment]
@ztephm , could you notify S/B 14966014? I don't have support bee access anymore. Thanks!

**Comment by ztephm** [comment]
done, thanks for fixing!
