### ISSUE TITLE
Add tooltip on Builder actions

### ISSUE THREAD

**Issue by urbanphes** [CartoDB/cartodb#13095]
### Context
Regarding this ticekt: 
https://github.com/CartoDB/design/issues/1050#issuecomment-342891295

**Comment by matallo** [comment]
I've just pushed to ded10 the new tooltips.

@urbanphes @csobier While I work on covering the code with specs, I'd be very grateful if you could double-check and update the document in the design issue, there are some pending discussions regarding the literals

thanks!

**Comment by matallo** [comment]
also, you can see the literals in the linked PR https://github.com/CartoDB/cartodb/pull/13102, feel free to edit them yourselves! I will go though the spreadsheet nevertheless

**Comment by csobier** [comment]
@matallo, looks good. The [spreadsheet](https://docs.google.com/spreadsheets/d/13055ajt2PYPUsnCdOYCmFHKzFFcg0Zxz6Xfk4xqmD5k/edit#gid=0) should be up-to-date now so you can cross-check. Thanks and let me know if I missed anything.

**Comment by rubenmoya** [comment]
Deployed to `ded12`

cc @CartoDB/design

**Comment by piensaenpixel** [comment]
Hey guys love it :)
The only thing is that in some cases tooltip doesn't appear

![image](https://user-images.githubusercontent.com/1214201/33487157-a0868190-d6ac-11e7-8f9b-11176cb62fef.png)

**Comment by piensaenpixel** [comment]
Only one very small thing, if you think we can do it know ok, if not we can do it later: 

- [] To be consistent, could we put latitude and longitude in the same order?
![image](https://user-images.githubusercontent.com/1214201/33487711-6ea030d4-d6ae-11e7-8d70-62df247856d1.png)

**Comment by matallo** [comment]
I updated the paddings of the components to make the tooltips appear in the whole target, redeployed in `ded15` and after some test it doesn't seems to break

this involved CartoAssets, too

**Comment by piensaenpixel** [comment]
thanks mata

**Comment by ramiroaznar** [comment]
I found a bug when going from the layer list panel to the layer options. The Edit analysis tooltip is not removed:

![image](https://user-images.githubusercontent.com/5215798/33882835-cf50764e-df39-11e7-8d4b-c0ab7f1e44f7.png)

Let me know if you need me to create a ticket.

**Comment by arianaescobar** [comment]
We've also run across that bug in our latest usability tests. I do think we should open one @ramiroaznar.

**Comment by urbanphes** [comment]
I reopened this ticket because we have forgotten some parts:
- Label check.
- Widget configurator.

This is the document:
https://docs.google.com/a/cartodb.com/spreadsheets/d/13055ajt2PYPUsnCdOYCmFHKzFFcg0Zxz6Xfk4xqmD5k/edit?usp=sharing

**Comment by rubenmoya** [comment]
I opened a new one so it's easier to keep track of it, you can check it in #13219 

Thank you @urbanphes!
