### ISSUE TITLE
Like button shown in public visualization even when not logged in

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#13098]
Visiting any public visualization page while not logged in, the like button is displayed, even it doesn't work if clicked.

Maybe we should hide the button, or display a login prompt.

**Comment by ramiroaznar** [comment]
Ey @javitonino should we work on this and #13097 in the RT? I know you are working on a new public page...

**Comment by javitonino** [comment]
If we want to address these two, they need to be changed in both places: the old pages and the new ones.

Not sure what is the best approach to do this, if to split the changes to the old part (RT) and the new part (Charlie) or do it all together. @elenatorro and/or @nobuti may have a better idea.

**Comment by elenatorro** [comment]
I would do it separately, we can add this fix in the branch we are currently working on once it is fixed in the old one. 👍

**Comment by elenatorro** [comment]
I am not sure this is a bug, I thought the like button redirects you to the login page if you are not registered (I tested it here: https://team.carto.com/u/matallo/viz/ae2c6e74-ecce-11e4-a952-0e49835281d6/public_map)

**Comment by nobuti** [comment]
This has been fixed in https://github.com/CartoDB/cartodb/pull/12928 for static pages. Once it is tested, I guess we could port the same solution.

**Comment by rubenmoya** [comment]
Right now, the like button is redirecting to the login page if the user is not logged in, should we keep that behavior or hide the icon? IMO we should keep it as it is.

cc @CartoDB/design

**Comment by kukukaka** [comment]
I think it's a bit weird to move the user to other screen for such type of action. It would be ok if the login was in a dialog or something that opens in place, but I guess we don't have that behaviour so my suggestion would be to make it not clickable if you're not logged in.

**Comment by rubenmoya** [comment]
I understand that, but if we make it not clickable then we'll have to add a tooltip or something explaining why it's not clickable should we do that or just hide it?

**Comment by ramiroaznar** [comment]
cc @urbanphes

**Comment by urbanphes** [comment]
I think this action had sense when CARTO it was more social since there was a community around it, but on the current status, this action isn't relevant and I would remove the icon.
