### ISSUE TITLE
Change URL of our marker's icon inside Datasets

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13111]
Right now, in the datasets screen, when you click on the marker's icon, it takes you to your public profile instead of your dashboard (like the tooltip says it will do and should do). 

![screen shot 2017-11-22 at 11 38 09](https://user-images.githubusercontent.com/16247628/33123269-06fae5d6-cf7a-11e7-8194-528ba803b728.png)

We should change that so it points correctly to the user's dashboard instead.

**Comment by rubenmoya** [comment]
I'll take this one, seems like I messed up the url when migrating the view 😅

**Comment by arianaescobar** [comment]
Thank you! :)

**Comment by rubenmoya** [comment]
In production! 🚀

**Comment by arianaescobar** [comment]
Thanks @rubenmoya!
