### ISSUE TITLE
Navigate with arrow back browser

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#13115]
In the usability tests,  we found out that most of the users use the back arrow from the browser and it takes them to the dashboard. However, we think it'd be useful to take them to their previous screen if they've navigated in builder.

Talking with @matallo we thought that we need:

- [ ] Add URL to the layer view
- [ ] Navigate with arrow back browser
- [ ] Also it could be great if it works with the modals.

**Comment by matallo** [comment]
in production! 🚀
