### ISSUE TITLE
Center bounding box automatically when new datasets are added 

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13110]
One of the main issues we've found with the usability tests is that our users expected the bounding box to center on the geometries when they add new layers to their maps. And it makes sense. Is this something feasible enough?

**Comment by matallo** [comment]
It should be feasible, or at least that's how the "Center map" button works inside a layer

/cc @ivanmalagon

**Comment by matallo** [comment]
in production 🚀
