### ISSUE TITLE
Improve Builder's wayfinding

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#13127]
**Context**
Related - https://github.com/CartoDB/design/issues/1036/

**Invision** 
https://invis.io/XZEMLONQV

**Comment by matallo** [comment]
do we have an inventory of modals where the new wayfinding should be applied? with the current modals setup we end up with some modals as you can see below

![pageshot of refugio lizara bisaurin refugio lizara tracks carto 2017-12-02-1125 34](https://user-images.githubusercontent.com/36676/33879624-55e6846a-df2f-11e7-9426-0c89a1013d13.png)

in the meantime I'm doing a workaround to keep the close button in the legacy modals, but keep in mind this is a temporary hack

@piensaenpixel @arianaescobar

**Comment by rubenmoya** [comment]
Does this issue also includes changing the color for the layers to this ones https://github.com/CartoDB/design/issues/1036#issuecomment-346604367?

@arianaescobar

**Comment by arianaescobar** [comment]
@matallo It should be applied in every modal, the thing is that we have different styles of modals, being that one you added a legacy one. That change should be applied to all the new ones that have the header left-aligned (until we update the old ones, which hopefully won't take long because having different ways of closing a modal could potentially be very confusing).  

@rubenmoya Yes, that's part of the issue :)

**Comment by matallo** [comment]
@arianaescobar as much as I don't like it, we'll do it phased as currently despite having several modals styles they all share the same code

in any case, I'm applying the breadcrumbs to the new modals 👍

**Comment by arianaescobar** [comment]
Oki! Let me know if you have any other doubt.

**Comment by matallo** [comment]
I'm leaving the close button in the modals below, too

![pageshot of untitled map carto 2017-12-02-1336 44](https://user-images.githubusercontent.com/36676/33888200-a7f4a9a4-df4c-11e7-95af-ab1cfe9d6dd7.png)

**Comment by rubenmoya** [comment]
Uploaded to `ruis` in staging, at the end we've decided not to split it, so all the changes should be there. The acceptance steps are in https://github.com/CartoDB/cartodb/pull/13185, I've been checking and I can't see anything weird, but could you take a look @CartoDB/design? If you need a user for staging tell me!

**Comment by rubenmoya** [comment]
ping @CartoDB/design

**Comment by arianaescobar** [comment]
I'm on it!

**Comment by rubenmoya** [comment]
In production! 🚀
