### ISSUE TITLE
Change "Add" buttons design (Add Layer, Add Analysis, Add Widget)

### ISSUE THREAD

**Issue by urbanphes** [CartoDB/cartodb#13122]
### Context
Design ticket: https://github.com/CartoDB/design/issues/1071
Invision project: https://invis.io/XJEKMDODE

**Comment by rubenmoya** [comment]
There is one case we didn't think about, in the widgets tab, when there is a widget we show a placeholder with a blue button, we've changed it to this:

![screen shot 2017-12-12 at 17 56 08](https://user-images.githubusercontent.com/905225/33897463-d353ddd6-df65-11e7-8883-896a68030210.png)

What do you think @CartoDB/design?

**Comment by rubenmoya** [comment]
In the analyses tab right now we have a loading state, with this changes, what do we do in that case? @CartoDB/design

**Comment by matallo** [comment]
actually we also have errors, check every different state for the analyses list

**Comment by arianaescobar** [comment]
Zero case: 

![screen shot 2017-12-13 at 11 37 23](https://user-images.githubusercontent.com/16247628/33935993-35c85170-dffe-11e7-99c1-e44b46ee1d3c.png)

Copy: Analysis allow you to build reproducible workflows for analyzing and explaining your data.

**Comment by arianaescobar** [comment]
List states: 

![screen shot 2017-12-13 at 12 24 27](https://user-images.githubusercontent.com/16247628/33936825-336f7cac-e001-11e7-9dc2-55ebff84e3d1.png)

Hover
Selected
Normal
Error
Loading

**Comment by rubenmoya** [comment]
In the analysis view, the dropdown in the redesign is showing the `nodeId` and the `layerName`:

![screen shot 2017-12-13 at 14 19 33](https://user-images.githubusercontent.com/905225/33940883-05859726-e011-11e7-821d-cd10aa2d1be4.png)

but currently we're also showing the `nodeTitle` in this case `AOI`, what should we do in the new design?

![screen shot 2017-12-13 at 14 22 43](https://user-images.githubusercontent.com/905225/33940921-2645d994-e011-11e7-90f8-1147551157e2.png)


@arianaescobar

**Comment by rubenmoya** [comment]
Also, in the widgets tab:

![screen shot 2017-12-13 at 14 38 42](https://user-images.githubusercontent.com/905225/33941563-5bc1ecaa-e013-11e7-83ac-c1b74ebf8239.png)

we're always showing "source" and the layer name, no matter if the source it's an analysis or the dataset itself.

Another thing is the button, it's in the top of the list, but when the new widget is added it appears at the bottom of the list, should we change it to be at the bottom?

**Comment by arianaescobar** [comment]
To the nodes styling questions, this is how they should always look: 

- Node is always darker
- Node is either Source or the Analysis name (simplified) 
- An analysis node is always "XX + Flash icon + Analysis name + Layer name"
- A source node is always "XX + "Source" + Dataset name"

![analysis options](https://user-images.githubusercontent.com/16247628/33942602-bcc8112a-e016-11e7-86e7-bfc00e241a2a.png)
![layers list](https://user-images.githubusercontent.com/16247628/33942605-bce6cd04-e016-11e7-8ed6-cf56ffe04075.png)
![widgets](https://user-images.githubusercontent.com/16247628/33942606-bd0655e8-e016-11e7-8a95-c387d07fa5a9.png)

To the button question: We want it at the top, always. And to solve that, we want to change the behavior so they get added on top (both in the Widgets list and the widgets themselves), just like layers do, to unify. 

Does that answer your doubts?

**Comment by rubenmoya** [comment]
Yes, thank you!

**Comment by rubenmoya** [comment]
Why did we change the blue color to the last one? 😞  I loved it 💔

**Comment by arianaescobar** [comment]
I loved it too, but it's too similar to our Builder blue and people might confuse them and think that it is interactive :(

**Comment by rubenmoya** [comment]
In production! 🚀
