### ISSUE TITLE
Explicit error on password protected visualization requests

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#13123]
Currently, requesting a password protected visualization (`http://juanignaciosl.localhost.lan:3000/api/v1/viz/79c04ef8-52ca-4a58-a026-52f2ae44891d`) returns this:

```
{
  "errors":"Visualization not viewable"
}
```

So, there's no way to know, with a user without explicit permission, whether a visualization is password protected or not.

Proposal: return a cause code explaining this:

```
{
  "errors":"Visualization not viewable",
  "errors_cause":"privacy_password"
}
```

**Comment by ethervoid** [comment]
### Acceptance

- [x] Check with a link only visualization
![captura de pantalla 2017-11-27 14 07 24](https://user-images.githubusercontent.com/741240/33268125-507512b2-d37c-11e7-8522-35c94e9fbfbc.png)

- [x] Change to password protected and check if the new error appears
![captura de pantalla 2017-11-27 14 03 23](https://user-images.githubusercontent.com/741240/33268147-673d942e-d37c-11e7-81e4-7b380b0d5720.png)

- [ ] Change to private and check what info is returned. In this case we get the same error than for password and it's wrong
![captura de pantalla 2017-11-27 14 03 23](https://user-images.githubusercontent.com/741240/33268147-673d942e-d37c-11e7-81e4-7b380b0d5720.png)

- [x] Change again to password and link and see if everything work as intended

**Comment by ethervoid** [comment]
### Acceptance

- [x] Change to private and check what info is returned. Now the cause is nil, maybe it could be something that says it's a private visualization but is ok.
