### ISSUE TITLE
Fix drag-n-drop feature in the layers list 

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13133]
Right now this feature is working a bit jumpy. From our usability tests we've seen that everyone has had problems trying to reorder when layers move to their original position when dropped in a place where they should have switched with others. 

Take a look at the recordings: 
https://drive.google.com/open?id=0B7qZP_jDgjOrVUNWWlR1VWx4a0U

Also, almost always, once they successfully reorder, the click also activates the layer and the users founds themselves inside a layer unintentionally. 

![draganddrop](https://user-images.githubusercontent.com/16247628/33275725-cc767df8-d393-11e7-8666-fa2b5713bb8c.gif)

**Comment by rubenmoya** [comment]
I've been moving a few layers around and none of that things happens to me, are there any specifics steps to reproduce it?

**Comment by arianaescobar** [comment]
Not really... 

I can't reproduce the drag-n-dropping issues right now either, but I do keep getting into the moved layer when reordering layers. That doesn't happen to you?

**Comment by rubenmoya** [comment]
No it doesn't :(

**Comment by alrocar** [comment]
Stale issue. Closing 👋
