### ISSUE TITLE
Nothing else should be interactive when a dropdown is open

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13132]
Right now, when you have a dropdown open, you can click anywhere else outside that dropdown to close it. Which is a very common behavior.

But if you happen to click on top of an interactive element, besides closing the dropdown, that element gets activated. And that is veeery confusing and annoying. 

Could we disable any other interaction when a dropdown is open?

**Comment by jesusbotella** [comment]
@arianaescobar By disabling any other interaction you mean that clicking anywhere else in the page (except the dropdown itself) should close the dropdown?

**Comment by arianaescobar** [comment]
Yes, and that already happens. The thing is, that if you happen to click on an interactive element, that click will, in fact, close the dropdown but also activate that element. We want to prevent that last part from happening.

**Comment by jesusbotella** [comment]
Ok, I just wanted to be sure about the behaviour I need to fix!

Thank you :)

**Comment by arianaescobar** [comment]
Of course! Thanks for asking :)

**Comment by rubenmoya** [comment]
In production! 🚀
