### ISSUE TITLE
Make all the widgets cards clickable in the Add widgets modal

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13134]
Just like the Analysis cards in the Add analysis modal.

Plus, add the card outline to the default style. 

<img width="1106" alt="screen shot 2017-11-27 at 16 58 16" src="https://user-images.githubusercontent.com/16247628/33275912-454f1974-d394-11e7-8025-bb0fc40daffb.png">
<img width="1049" alt="screen shot 2017-11-27 at 16 58 26" src="https://user-images.githubusercontent.com/16247628/33275913-456f1742-d394-11e7-928b-e8bc6bbb8f12.png">

**Comment by matallo** [comment]
in production! 🚀
