### ISSUE TITLE
Updated positron and dark-matter style URLs

### ISSUE THREAD

**Issue by jaakla** [CartoDB/cartodb#13148]
With basemap Nov-17 update (https://github.com/CartoDB/lbs-services/issues/11) @makella has updated positron and dark-matter styles. Now just like with voyager before there is additional "labels under" version for both styles, which has lighter texts, meant to be used as data background. This is exactly Builder case. To deploy it Builder UI should have changed style IDs in the tile URL templates as following:

* "Positron (Labels below)" - `/rastertiles/light_labels_under/` (instead of /light_all)
* "Dark Matter (Labels below)" - `/rastertiles/dark_labels_under/` (instead of /dark_all)

Visual result is that the texts will be softer and less visible.

URLs of other style variations, like "light" and "labels on top/default" do not change.

@noguerol

**Comment by makella** [comment]
@jaakla it looks like from what is loading in Builder right now, that the new tiles for `labels_under` is reading from `all`. Is this because the cache hasn't been cleared?

For example, I'm seeing this for the labels under 

In the preview app:
![screen shot 2017-11-30 at 12 19 48 pm](https://user-images.githubusercontent.com/1566273/33450425-fc5d6036-d5c8-11e7-8656-97cbf9605f51.png)

In Builder:
![screen shot 2017-11-30 at 12 19 28 pm](https://user-images.githubusercontent.com/1566273/33450432-0304a994-d5c9-11e7-9f3a-24f79c20434f.png)

**Comment by jaakla** [comment]
Builder live configuration has to be changed to new URL for this. Cache clearing does is not enough here.

**Comment by makella** [comment]
@noguerol BIG DEAL! can we get this taken care of ASAP?

**Comment by makella** [comment]
THANK YOUUUUUUU!!!!

**Comment by ramiroaznar** [comment]
@alonsogarciapablo can you help @makella and @jaakla to check what the new basemap styles are not rendering as expected?

**Comment by alonsogarciapablo** [comment]
Sure! I will take a look later.

**Comment by makella** [comment]
@alonsogarciapablo ok, so i went through and here are the places that we need to update the URLs

**Positron (labels below)**
https://github.com/CartoDB/cartodb-platform/blob/develop/cookbooks/cartodb_app/attributes/basemaps.rb#L43
- change to 
`https://cartodb-basemaps-{s}.global.ssl.fastly.net/rastertiles/light_labels_under/{z}/{x}/{y}.png`

**Dark matter (labels below)**
https://github.com/CartoDB/cartodb-platform/blob/develop/cookbooks/cartodb_app/attributes/basemaps.rb#L51
- change to
https://cartodb-basemaps-{s}.global.ssl.fastly.net/rastertiles/dark_labels_under/{z}/{x}/{y}.png

**Comment by alonsogarciapablo** [comment]
Also, we have to take into account that all the layers that we have in the DB are still pointing to previous URLs... Question: why didn't we change the existing URLs?

**Comment by makella** [comment]
@jaakla can you comment?

**Comment by jaakla** [comment]
So solution after discussions:
a) I will redirect dark_all and light_all to dark_labels_below and light_labels_below in CDN. This is how it was originally meant to be really, but accidentally _labels_below was published as separate style name. Quick technical fix is to do it in CDN/Fastly, but I need to test it carefully on Monday before touching live configs.
b) this will be transparent to end-users and Builder, so no changes needed there. We keep _light_all_ and _dark_all_ as URLs. All maps will just see "dimmed out" labels, once CDN cache will be cleared: on next Monday, or latest Tuesday early morning EU time, and we hope it is not big disturbance to them. Much bigger sudden visual change happened today already anyway.

Essentially no fix under this issue in builder needed, so closing this issue here.

**Comment by jaakla** [comment]
Note that issue - need to change URLs was a really a noise and miscommunication. The root issue was that the the main styles were taken from wrong style - from main style project, not from "_labels_below" variations, as detailed in https://github.com/CartoDB/mobile-tileserver-mbtiles/issues/27
