### ISSUE TITLE
Column selector might be confusing when columns have been filtered out

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#13142]
In https://github.com/CartoDB/cartodb/issues/7873 we removed date columns from the column list component that allow users to style a layer by a column. The result is:

![image](https://user-images.githubusercontent.com/390398/33324196-35d28920-d44f-11e7-8c67-48a85fa25fcf.png)

When no results are found the component displays a message such as `No column results found with 'postedtime'`. The problem with this behaviour is that that the column might not be found due to two different reasons:

1. The dataset/analysis might **not** have a column with the given name.
2. The dataset/analysis might have a column with the given name but it might have been filtered (because it is a date column).

In both cases (:point_up:) we display the same error message and this may be confusing for some users so we could make a better job here. Just take into a account that the column selector is used in different contexts and it uses generic custom list component that does not allow a lot of customisation in this regard. See https://github.com/CartoDB/cartodb/pull/13140 for more context.

cc: @noguerol @kevin-reilly @jorgesancha @arianaescobar @ramiroaznar

**Comment by alrocar** [comment]
Stale issue. Closing 👋
