### ISSUE TITLE
[Time-Series] Deprecate avg, max and min per bucket

### ISSUE THREAD

**Issue by Algunenano** [CartoDB/cartodb#13164]
### Context
After optimising time-series queries (https://github.com/CartoDB/Windshaft-cartodb/issues/797) I've reached a point where calculating max, min and avg values per bin takes around 30% of the time.

After checking with @ivanmalagon and @rochoa it seems that these values aren't used in the client so it doesn't make sense to keep calculating them for nothing. Be careful, I'm not talking about histograms over time columns (possible with some tricks) but for time-series widgets (which use different backend queries).

For now, I'm going to start returning the start of the bin (`timestamp`) as value for the other unused values, but it'd nice if we could update code/API/docs to stop expecting them so we can remove them completely.

**Comment by alrocar** [comment]
Stale issue. Closing 👋
