### ISSUE TITLE
dashboard: create map dialog should refresh after removing layers

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#13169]
### Context
while in the dashboard if you work with datasets and reopen the create map dialog it's not updated

### Steps to Reproduce

1. go to dahsboard
1. click on create map
1. datasets should appear in datasets tab
1. close dialog
1. go to datasets with header dropdown
1. remove all datasets and confirm
1. go back to maps with header dropdown
1. click on create map

### Current Result
the non existing datasets appear in the dialog

### Expected result
there shouldn't be any datasets, as they have been removed

**Comment by alrocar** [comment]
Stale issue. Closing 👋
