### ISSUE TITLE
Login link from public page broken (not referring customized domain)

### ISSUE THREAD

**Issue by Xatpy** [CartoDB/cartodb#1316]
In the local install version, from a public page, (if you are not logged), the LOGIN button is going to cartodb.com/login, instead of going to the customised domain.
For example, in the next image, the Login should go to https://own.cartodb.own/login (and it is going to cartodb.com/login):
![screen shot 2014-12-01 at 14 30 59](https://cloud.githubusercontent.com/assets/3958416/5246290/4562065e-7967-11e4-80be-79de46b09f1d.png)

**Comment by xavijam** [comment]
Fixed in the new public dashboard and public map.
