### ISSUE TITLE
Auth API documentation

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#13178]
Things to review:

- URLs (by key name and also /api/v3 prefix, subdomain/username stuff)
- Permissions names (`["update", "select", "trigger", "references", "truncate", "delete", "insert"]`). Might want to fix some on rails side
  - Master key permissions leak existence of analysis caches
- Token lengths
- `type` is not honoured in creation

**Comment by alrocar** [comment]
Stale issue. Closing 👋 And we already have documentation :)
