### ISSUE TITLE
Display default API info

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#13179]
API and UI for displaying public Auth token and master.

API might be done already, as a consequence of the table_permissions_from_database thingy.

**Comment by javitonino** [comment]
The API is there, but we must review if we are providing too much information. In particular:

- We show all permissions: `["update", "select", "trigger", "references", "truncate", "delete", "insert"]`. We may want to restrict to the ones actually supported by the API (CRUD-like)
- We show all granted tables, including system tables or analysis caches, which we may want to hide from output.

**Comment by javitonino** [comment]
cc @enekid to discuss

**Comment by dgaubert** [comment]
My two cents:

>  I'd restrict to the ones actually supported by the API ([select, update, delete, insert])

+1000

> We show all granted tables, including system tables or analysis caches, which we may want to hide from output. Related with #13529.

Regarding `analysis cache` and `system` tables, we must hide all of them.

> The database grants output from master keys is long (all tables) and pretty meaningless (list of everything, with all permissions). Maybe we could skip it. This also solves the previous problem.

Totally agree, we want to skip it.

> `regular keys` include the explicit grants plus everything in the public key. We may want to only show the explicit grants? (It's easy enough)

I understand `regular api-key` as something between `default_public` and `master`, so I'd show the explicit grants only.

> The list from default keys just lists all public objects in the database. This may be alright (but we might want to have an empty list for consistency if we do the previous change to regular keys?)

If we go with showing only explicit grants of `regular api-keys` then, to be consistent, we won't want to show all public objects.

In summary:
- Master: just give a message that clarifies that `master` has all perms to perform any operation.
- Regular: show explicit grants.
- Default: a message to indicate that it has `read-only` perms of all public objects.

**Comment by javitonino** [comment]
> In summary:
> - Master: just give a message that clarifies that `master` has all perms to perform any operation.
> - Regular: show explicit grants.
> - Default: a message to indicate that it has `read-only` perms of all public objects.

+1. There is something to be said about displaying all permission an API Key has, but on the other hand, having different results in the response than you requested is confusing. Both ideas have their merits, but I'm also leaning towards hiding the implicit grants, to avoid surprises (it's also easier, so there's that, hehe).

You proposed adding a message explaining the situation, not sure if you were referring to add that in the API output. I would not do that, and instead explain the expected behaviour clearly in the documentation.

**Comment by dgaubert** [comment]
> You proposed adding a message explaining the situation, not sure if you were referring to add that in the API output. I would not do that, and instead explain the expected behaviour clearly in the documentation.

Referencing to the documentation is perfect for me.
