### ISSUE TITLE
Internal release for Auth API

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#13174]
This release should provide enough functionality for usage with carto.js.

- Internal communication.

**Comment by ethervoid** [comment]
@dgaubert what is the state of this?

**Comment by enekid** [comment]
Tomorrow I plan to review the Redis output generated by the Backend ([issue](https://github.com/CartoDB/cartodb/issues/13474))

**Comment by enekid** [comment]
I've just reviewed the generated Redis keys #13474, and it LGTM!

**Comment by javitonino** [comment]
I'll put this issue back in TODO, we can consider it done once we have:
- Windshaft in production (after fallback is done https://github.com/CartoDB/Windshaft-cartodb/issues/867)
- Public/Master keys installed for `team` members
