### ISSUE TITLE
Auth API UI Release

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#13177]
This is the project at InVision: https://projects.invisionapp.com/share/P2DZ1FWUE#/screens/258570871

**Comment by inigomedina** [comment]
@ivanmalagon this part of the project could be started in parallel to the current backend development. Could there anybody from the carto.js or the frontend team available to push this?

**Comment by ivanmalagon** [comment]
Work in progress in https://github.com/CartoDB/cartodb/issues/13477
