### ISSUE TITLE
Master API key on user creation

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#13172]
Create the following keys on user creation:
- [ ] Master key.
- ~Public key~ -> see #13471

... and remove them on user deletion -> see #13470

In addition, make sure that you can't delete any of them with the DELETE endpoint.

**Comment by alrocar** [comment]
Some context [here](https://github.com/CartoDB/cartodb-management/issues/5040)

[Master API key](https://docs.google.com/document/d/1lMxxIhAd8r3QHu-DzDmjW0XzJDNBhQPC4vYpjc-xmug/edit#heading=h.v5ld2estmj0g)
[Default public API key](https://docs.google.com/document/d/1lMxxIhAd8r3QHu-DzDmjW0XzJDNBhQPC4vYpjc-xmug/edit#heading=h.gx80swbhbkw5)
