### ISSUE TITLE
Dashboard alert 

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#13175]
@juanignaciosl to give information about our basemap's changes we'd need to add an alert in the dashboard and link it to https://carto.com/blog/inside/positron-dark-matter-new-look/

![image](https://user-images.githubusercontent.com/1214201/33565274-f8b41388-d91c-11e7-8a96-596e58638ccd.png)

cc @makella, @namessanti

**Comment by juanignaciosl** [comment]
@piensaenpixel is there a hard deadline for this?

**Comment by makella** [comment]
@juanignaciosl we updated the basemaps on Friday and released a small blog post about the updates about an hour ago. 

I'd say as soon as we can especially for those who don't read our blog.

If it isn't today, we shouldn't have the word "today" in the notification.

**Comment by juanignaciosl** [comment]
There's no mechanism for this kind of message, and hardcoding it for several days is not something that we should do. We've had several really important communications, such as API Key removal that we haven't announced on the dashboard. If we do this, we should change our users communications. I would totally agree on doing it, but I wouldn't hurry up with this.

In addition, that message can't be removed. Shouldn't we provide a way to dismiss it? Related to that, what about using the current notification system (the top bell)?

**Comment by matallo** [comment]
I was going to jump in to say the same, we already have a notifications mechanism for these kind of announcements! 🙌

**Comment by makella** [comment]
@juanignaciosl thanks for clarifying this! Learning new things every day :)

The original idea was for the notification bell. 

If that is something that we can do that avoids the issues you mention, that would be great.

**Comment by piensaenpixel** [comment]
We can use the top bell, if you agree on that, but... it's something that nobody really read it.

**Comment by makella** [comment]
@piensaenpixel point taken. when santiago and devon had explained, they mentioned the notification bell and I thought what you have above shows when you click it (apparently not!)

anyway, we are 3 days into the release so whatever you guys think is most efficient. 

thanks and i'll let you all decide!

**Comment by piensaenpixel** [comment]
Ok, so if the easiest thing is the bell one, go ahead :)

**Comment by juanignaciosl** [comment]
@piensaenpixel @makella sorry, I have bad news. First of all, sorry for not saying anything in 8 days. We're swamped with urgent stuff. After talking to @matallo about the way to add bell notifications, it's not as simple as it should be (a single row insert). Currently there's no straightforward way to add a simple notification, and I guess that it's too late for this.

In addition, we've recently had huge changes that have been notified by email instead, so adding a fixed dashboard notification felt weird.

I'm really sorry about closing this. Next time that you're planning big changes, please let me know. With a little effort, we could improve some of our existing mechanisms to support a straightforward way for these kinds of notifications. Or we would code one with the existing mechanism (although needing code for a simple one is not something that we should do, IMHO).

**Comment by makella** [comment]
@juanignaciosl thanks for the note! i was going to close this today also

yes, next time we will plan better...
