### ISSUE TITLE
Change Grunt tasks to generate static pages

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartodb#13188]
### Context
We are currently building static pages with the production flag when running `grunt dev` and `grunt build`. We have to change this, so it does not change `public/static/**/index.html` files if we are developing something that is not related with the FE/BE Split, we will have a separated task for that (now called `npm-start-static`). The only problem this approach could have is that, if someone changes a file that the FE/BE Split static pages need, these changes will not be applied if we do not run `grunt build`and commit these files before pushing the branch.

We are already improving the static pages generation, so we do not have to build manually the static pages https://github.com/CartoDB/cartodb-platform/issues/3685

I will change the `Gruntfile.js`, so you do not apply changes to`public/static/**/index.html` pages when running `grunt dev`. Just take into account that this is something provisional that we will change when the deploy workflow task finishes.

**Comment by matallo** [comment]
thanks! 🤗
