### ISSUE TITLE
Geocode issue

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#13181]
After releasing the new geocode flow and following users feedback we found an issue about having the data's tab deactivated
How difficult is activate only that tab?

cc @matallo @rjimenezda

**Comment by matallo** [comment]
reopening this issue to discuss how to properly address this, that I'm aware of:

- revert previous behaviour with current `.canBeGeoreferenced` implementation, which is more accurate than before (and also has loading states)

anything that I'm missing @piensaenpixel ?

**Comment by piensaenpixel** [comment]
yes it's ok.

**Comment by matallo** [comment]
🚀
