### ISSUE TITLE
[Time Series] Invalid start and end use in some aggregations

### ISSUE THREAD

**Issue by Algunenano** [CartoDB/cartodb#13182]
### Context
No results shown in the time series histogram in some aggregations even though there is data.

### Steps to Reproduce
1. Load data (rename from txt to csv): [dospuntos.copy.txt](https://github.com/CartoDB/cartodb/files/1530453/dospuntos.copy.txt)
2. Create map.
3. Create a time-series over `fecha` and select bucket `months`.
4. **Go back to the dashboard**. If you don't do this it'll work fine.
5. Go back into the map. Change the widget from `months`to days.

### Current Result
![image](https://user-images.githubusercontent.com/664253/33599370-42fe885e-d9a6-11e7-803f-e90374fee369.png)
`offset=0&start=0&end=86399`

### Expected result
*Please describe here below what should be the expected behaviour*
![image](https://user-images.githubusercontent.com/664253/33599533-b9bbe8e2-d9a6-11e7-93f5-ecffa4259c7c.png)
`offset=0&start=86400&end=172799`

### Additional info
Performance with start and end or without it is the same, so making the requests without it could be a good solution

**Comment by ramiroaznar** [comment]
I was not able to replicate this issue on my end.

**Comment by Algunenano** [comment]
> I was not able to replicate this issue on my end.
Uhmm, I don't know why I'm unable to reproduce it too, but I did get it several times before...

Anyhow, I'm keeping this open since start and end could be removed without impact.

**Comment by ramiroaznar** [comment]
Can I move it then to the RT dashboard (instead of the 5x one) in order to fix it?

**Comment by Algunenano** [comment]
I think so. Just a heads up, it appeared while testing https://github.com/CartoDB/Windshaft-cartodb/pull/804 which is not deployed yet but it shouldn't impact this specific ticket at all.

**Comment by ivanmalagon** [comment]
Fixed in https://github.com/CartoDB/Windshaft-cartodb/issues/776

We were requesting the total data range for histograms using `start` and `end` because of them being affected by filters. After the linked PR, the total range is requested with no `start` and `end`.
