### ISSUE TITLE
Unify tooltip style

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13194]
Widgets have a tooltip style...

![screen shot 2017-12-07 at 14 15 59](https://user-images.githubusercontent.com/16247628/33717238-75915940-db59-11e7-8d36-66a83d64d855.png)

...that is different than the others:

![screen shot 2017-12-07 at 14 16 07](https://user-images.githubusercontent.com/16247628/33717244-7eab31e0-db59-11e7-9806-497835f8738d.png)

They should all look like the last one.

**Comment by jesusbotella** [comment]
I am unifying tooltip style between Builder and DI, as DI has been merged with the builder, and I am facing an issue that needs some help from @CartoDB/design.

When showing `More options` tooltip in the first widget of the row, it has overflowed and is misaligned as in this screenshot: 
![screen shot 2017-12-28 at 18 36 08](https://user-images.githubusercontent.com/4319728/34418485-abc332ee-ebfe-11e7-9bf8-2a9271b7f913.png)

It does happen the same thing in the autostyle popup:
![screen shot 2017-12-28 at 18 46 55](https://user-images.githubusercontent.com/4319728/34418681-980eadcc-ebff-11e7-9e9f-5e58aaa48ce1.png)

I think that the best option is to align it to the icon's left side, avoiding that the tooltip touches the edges of the browser. It would look like this:
![screen shot 2017-12-28 at 18 44 19](https://user-images.githubusercontent.com/4319728/34418591-2f891a08-ebff-11e7-8114-fa8e1cb69884.png)

**Comment by piensaenpixel** [comment]
hey @jesusbotella it could be great if we have a smart tooltip and it appears depending if it has enough space or if it doesn't, we can align it to the left side

**Comment by urbanphes** [comment]
+1 to @piensaenpixel comment.

But if we couldn't be done it, I would make the tooltips come out from the right to left, as a @jesusbotella  show as the last option.

**Comment by matallo** [comment]
we're already doing so for dropdowns, take your time and research how to properly do this with the tooltips @jesusbotella something like `gravity: auto`?

**Comment by jesusbotella** [comment]
Yes, it is a good idea!

**Comment by jesusbotella** [comment]
Just one quick question, I am testing the tooltip autoposition but I do not know what to do in this case.

In the second widget of the row, the tooltip could be positioned on top of the three dots shape but only if it is moved to the left. Would it be acceptable? Or is it better to position the tooltip in the center of the arrow?

Here I attach you the example: 
<img width="288" alt="screen shot 2018-01-03 at 09 26 16" src="https://user-images.githubusercontent.com/4319728/34513807-610e42be-f06a-11e7-9a61-df897d6b7a6d.png">

The pure top position doesn't fit in this case as the tooltip would be misplaced, like this:
<img width="390" alt="screen shot 2018-01-03 at 09 35 44" src="https://user-images.githubusercontent.com/4319728/34513855-a7b4d052-f06a-11e7-9747-1a9349af9513.png">

If the first option is not OK, the tooltip will be positioned to the left of the element.

**Comment by arianaescobar** [comment]
I would say 👍🏼 to the first option but let's wait for a confirmation from @urbanphes since I believe he was the one who originally designed them.

**Comment by urbanphes** [comment]
@jesusbotella Oks for the 1st option, also for the tooltips I would never use 2 lines, It's more difficult to read.

For all of us, **_Is this only affected by the tooltips place it at the border?_** 
At the beginning, these tooltips (top & bottom) was designed with the indicator in the middle ...

<img width="291" alt="captura de pantalla 2018-01-05 a las 11 58 23" src="https://user-images.githubusercontent.com/14546701/34606521-073d1d1c-f210-11e7-9603-3a6426307f11.png">

... but if we go with this solution, the top and bottom tooltips could change the indicator position. 
**_Is this correct?_**

**Comment by jesusbotella** [comment]
@urbanphes 👍.
The number of lines in the tooltip depends on the width of the text.
If it takes more than ~200px, it will break in two lines. I think we can change that if we want.
But the image I posted above with two lines tooltip was to show you what would happen in that case but it wasn't an actual tooltip, so it won't happen in any case.

I want to make clear that this is not the default behaviour for all tooltips right now. It is only applied to Widget tooltips, which are the ones that can collide with the browser edges (top, left, right and bottom).

Yes, you are right, the top and bottom tooltips can change the indicator position if the tooltip collide with the left/right edge of the browser window.

@arianaescobar @urbanphes Please let me know if you want to test it, it is deployed to `ded13` staging server.

**Comment by urbanphes** [comment]
Thanks for the info @jesusbotella 

Regarding the tooltip width, we can modify this to 260px.

Yes, I would like to test it.

**Comment by jesusbotella** [comment]
In production! 👏
