### ISSUE TITLE
Don't show the publish modal when the user clicks on the privacy button

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13192]
The dropdown to change the map privacy should appear directly below the tag instead of opening up a modal and having to click on that tag again. 

![screen shot 2017-12-07 at 14 11 26](https://user-images.githubusercontent.com/16247628/33716999-8d4ccf34-db58-11e7-9302-6e526efaf0f1.png)

![screen shot 2017-12-07 at 14 11 34](https://user-images.githubusercontent.com/16247628/33716998-8d253a28-db58-11e7-9bb5-ffebd92f49f4.png)

**Comment by matallo** [comment]
in production! 🚀
