### ISSUE TITLE
Wrong padding in widgets list

### ISSUE THREAD

**Issue by rubenmoya** [CartoDB/cartodb#13200]
### Context
It seems like the left padding is too big in the widget list

### Steps to Reproduce
1. Visit the widget list

### Current Result
![screen shot 2017-12-11 at 16 07 41](https://user-images.githubusercontent.com/905225/33837727-9814ac56-de8d-11e7-82b5-b67bc94664d0.png)

### Expected result
It has the same padding as the other sides

### Additional info
Seems to be related to `.BlockList-dragIcon` and `opacity`, changing it to `display: none` fixes it.

**Comment by jesusbotella** [comment]
Already deployed to production! 🎉

**Comment by ramiroaznar** [comment]
cc @piensaenpixel
