### ISSUE TITLE
Markdown formatting is not rendering ok in the embeds 

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13206]
### Context

In the "Edit metadata" modal we claim we support Markdown for the map description.

<img width="773" alt="screen shot 2017-12-12 at 12 04 09" src="https://user-images.githubusercontent.com/16247628/33881278-9e7cd0da-df34-11e7-853b-1cb830ad6c01.png">

But right now the rendering of that Markdown is not working too well. 

### Steps to Reproduce

1. You can use the .carto shared below to review how it's metadata markdown is behaving.
2. Make some changes to it and see how it renders. 

### Current Result

Right now, if we style the text using markdown, this is the output in the embeds:

![screen shot 2017-12-11 at 16 44 31](https://user-images.githubusercontent.com/16247628/33881299-b2335cb6-df34-11e7-885a-ac6f793b1335.png)

Tweaking it, I managed to get this: 

![screen shot 2017-12-11 at 17 53 12](https://user-images.githubusercontent.com/16247628/33881339-c6b88f6c-df34-11e7-8407-389c4db3bad9.png)

But it is still not ideal (also, look at the scroll bar, it should be fixed to the right, like inside Builder). We're only supporting H1, which looks like this (and it shouldn't):

![screen shot 2017-12-11 at 16 47 37](https://user-images.githubusercontent.com/16247628/33881374-e2206ffe-df34-11e7-978c-f888fec992c1.png)

But no H2 or H3. We're not supporting lists either and the separation between paragraphs needs some fixing too. 

### Expected result

This is in part our fault because we never designed the styles for all those possibilities, I created a [ticket](https://github.com/CartoDB/design/issues/1131) for us to define those styles and will ping you all here once we have them :)  

### .carto file

[Development around Union Station (on 2017-12-11 at 15.20.39).carto.zip](https://github.com/CartoDB/cartodb/files/1551308/Development.around.Union.Station.on.2017-12-11.at.15.20.39.carto.zip)

**Comment by rubenmoya** [comment]
Related to https://github.com/CartoDB/cartodb/issues/12126
