### ISSUE TITLE
editor => builder warning modals are not appearing anymore

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#13210]
### Context
when a map created with Editor is opened in Builder we used to show a warning modal because some attributes such as annotations are not compatible with Builder maps

this warning is not appearing anymore, causing destructive actions to the maps

### Steps to Reproduce

1. create a map with an Editor user
2. add annotation
3. in the console enable builder to that user
4. open the new map from the dashboard

### Current Result

the warning won't appear, and the annotations are removed

### Expected result

a warning should appear preventing the map to be migrated to Builder

**Comment by ramiroaznar** [comment]
Is this the expected behavior? Aren't we showing those messages anymore? @juanignaciosl @CartoDB/design

**Comment by juanignaciosl** [comment]
I performed those steps and I got the warning:

![captura de pantalla 2017-12-12 a las 17 30 30](https://user-images.githubusercontent.com/932968/33896145-617133a6-df62-11e7-95f8-3f79cb8b6d92.png)

If you want to take a look, it's https://juanignaciosl10.carto-staging.com/builder/276e23f9-6ddb-4a12-85d0-25b7e58ac356 visualization. @matallo , maybe you can compare that one with yours.

**Comment by matallo** [comment]
I confirmed this with @ramiro :thinking:

**Comment by piensaenpixel** [comment]
Uhmm yes, this modal should appear.

**Comment by juanignaciosl** [comment]
@ramiroaznar ok, we all agree that this should appear, and it looks like it actually appears, at least in some cases. Response team duty?

**Comment by ramiroaznar** [comment]
Yes! Let's investigate which cases the modal is not showing and fix them!

**Comment by alrocar** [comment]
Stale issue. Closing 👋
