### ISSUE TITLE
More tooltips on builder actions

### ISSUE THREAD

**Issue by rubenmoya** [CartoDB/cartodb#13219]
### Context
We forgot to add a few tooltips in https://github.com/CartoDB/cartodb/issues/13095, let's add them here.

Tooltips missing:
- Label check.
- Widget configurator.

### Additional info
https://docs.google.com/spreadsheets/d/13055ajt2PYPUsnCdOYCmFHKzFFcg0Zxz6Xfk4xqmD5k/edit#gid=2100067782

**Comment by arianaescobar** [comment]
Hey guys, regarding this one: there are a bunch of tooltips' messages left to be defined. We still don't have them ready for the Widget options and we're also adding a bunch of them in every Analysis option. So, we could add the ones we already have (not that many) or wait until we have them all an add them then. Your call!

**Comment by alrocar** [comment]
Stale issue. Closing 👋
