### ISSUE TITLE
Review Carto guides

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#13227]
### Context

As @jesusbotella was doing all the guides at CARTO Learn, he found several issues. This ticket is to enumerate those issues to check if they are really a bug or just a change in the functionality.

https://carto.com/learn/guides/analysis/detect-outliers-and-clusters
The autostyle drop icons were not showing up.

https://carto.com/learn/guides/styling/applying-text-labels-to-your-data
Text decoration property fails

https://carto.com/learn/guides/analysis/join-column-from-second-layer
Join type values are not correct

https://carto.com/learn/guides/analysis/enrich-from-data-observatory
Step 9 says CONFIRM instead of APPLY

https://carto.com/learn/guides/analysis/convert-text-into-city-and-admin-region-geometries
Geocoding workflow doesn't match between guide and Builder

**Comment by ramiroaznar** [comment]
cc @csobier

**Comment by csobier** [comment]
There is a huge backlog of all the new UI changes and the live guides. I'm waiting for onboarding project to end, as I have to update every single guide (the content, all images, all gifs- in addition to all our internal Wikis). (We're also restructuring the Learn code behind the scenes so I am blocked from making any updates at the moment as well).   

I'm moving this to the Learn repo and will add it to the Epic issue involving all the UI other changes required for the Guides.

**Comment by csobier** [comment]
Issue moved to [CartoDB/learn #501](https://github.com/CartoDB/learn/issues/501) via [**ZenHub**](https://www.zenhub.com/)
