### ISSUE TITLE
feature request: reverse sorting for datasets dashboard

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartodb#13229]
Sorting datasets in Builder dashboards only works in one direction (biggest, most recent, etc. on top). E.g., If I want the smallest datasets (maybe empty datasets I want to delete), I'd have to page through till the end of the pages. It'd be pretty nice to be able to sort the other direction. I could see having a little arrow that's right next to the sort icon buttons that tells how it's being sorted similar to what happens in Builder datasets view.

**Comment by arianaescobar** [comment]
Hey @andy-esch, this should be a ticket in the Design repository so we can come up with the visual solution for it.   

As a rule of thumb, request new Builder features there :)

**Comment by andy-esch** [comment]
👍 Moved to CartoDB/design#1142

**Comment by arianaescobar** [comment]
Thanks @andy-esch :)
