### ISSUE TITLE
Change layer colors

### ISSUE THREAD

**Issue by rubenmoya** [CartoDB/cartodb#13233]
### Context
We want to update the layer colors in Builder.

Design issue: https://github.com/CartoDB/design/issues/1036#issuecomment-346604367

This was already done in https://github.com/CartoDB/cartodb/pull/13185/commits/97e3433cc7ab714623fa278cb9b5f20afa457e0b, but we had to revert it because we are persisting the color so we ended up with to different colors in the layer list/analysis, more info in https://github.com/CartoDB/cartodb/pull/13215#issuecomment-351783207.

Before changing the colors we need to know why it is persisted, and if we can just rely on the node letter to choose the color.

### Aditional info
New colors:
```
COLORS: [
  '#11A579',
  '#E83f74',
  '#9F5DC8',
  '#EF8205',
  '#29B3B2',
  '#E54F3B',
  '#59BB12',
  '#EF57BA',
  '#E2AF00',
  '#12AADE'
],
```

cc @matallo @juanignaciosl

**Comment by matallo** [comment]
LGTM, we're already persisting the layer letter, and the color is deterministic 👍

**Comment by matallo** [comment]
production 🚀
