### ISSUE TITLE
Tooltip not removed when editing an analysis

### ISSUE THREAD

**Issue by rubenmoya** [CartoDB/cartodb#13235]
### Context

![tooltip](https://user-images.githubusercontent.com/905225/34040458-101e5202-e194-11e7-9900-10ae7ff7f37b.gif)

### Steps to Reproduce
1. Place the mouse on top of an analysis
2. Click on it

### Current Result
The tooltip stays there floating in the air

### Expected result
The tooltip is removed

**Comment by jesusbotella** [comment]
I saw this behaviour when adding a new geometry too.

It happens when adding a new line, or a new polygon. But it doesn't fail when adding a new point, surprisingly.

**Comment by rubenmoya** [comment]
Thank you! Let's fix it in this PR too :)

**Comment by rubenmoya** [comment]
Working like a charm! ✨  To deploy!

**Comment by rubenmoya** [comment]
In production 🚀
