### ISSUE TITLE
Refactor how we fetch category totals

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#13241]
### Context

This issue comes from https://github.com/CartoDB/cartodb/issues/13059

Now, we can retrieve widget data with no filters affecting them. This has been implemented in histograms but we need to apply it to category widgets as well.

More info in the ticket referred above.

If possible, study also the endpoint used to search categories. As expressed here https://github.com/CartoDB/Windshaft-cartodb/issues/776 it could need a `no filter` options as well. Study it in order to provide more info to Engine team.

**Comment by alrocar** [comment]
Stale issue. Closing 👋
