### ISSUE TITLE
Avoid double instantiation of the map

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#13242]
### Context

When Builder instantiate a map, it first send the map config with no filter param to fetch the total data ranges. Then, it instantiates the map again providing the filter param.

Now, Maps API provides a way to query dataviews with no filters affecting them so we can avoid this double configuration.

Histograms are already using them.

As soon as https://github.com/CartoDB/cartodb/issues/13241 is closed, we can tackle this double instantiation.

**Comment by alrocar** [comment]
Stale issue. Closing 👋
