### ISSUE TITLE
Don't show dropdowns when there is only one option available

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13251]
### Context

Across Builder, we continually show dropdowns even when there's only one option available in said input. We have to stop showing dropdowns in those scenarios. 

![unnecessary-dropdowns](https://user-images.githubusercontent.com/16247628/34162770-218ef570-e4d5-11e7-83af-ff5af0241981.gif)

### Current Result

A few examples:

<img width="712" alt="screen shot 2017-12-19 at 14 36 00" src="https://user-images.githubusercontent.com/16247628/34159560-fdaba708-e4c9-11e7-9a5f-6dc61dbd25c0.png">

<img width="643" alt="screen shot 2017-12-19 at 14 23 09" src="https://user-images.githubusercontent.com/16247628/34159562-fddc01c8-e4c9-11e7-8717-cffc3bc06ad4.png">

### Expected result

The ones with only one option have the input box in Disabled style but with dark text (unlike the actually disabled inputs where the text is light grey). 

![add widgets modal cards](https://user-images.githubusercontent.com/16247628/34159584-119856ee-e4ca-11e7-9e34-a7d09c0ede72.png)

![screen shot 2017-12-19 at 14 38 36](https://user-images.githubusercontent.com/16247628/34159670-53997bd6-e4ca-11e7-8fcc-9c999905de68.png)

**Comment by alrocar** [comment]
Stale issue. Closing 👋
