### ISSUE TITLE
Dropbox: Use a Chooser/Picker instead of showing all files

### ISSUE THREAD

**Issue by Algunenano** [CartoDB/cartodb#13259]
### Context
What we currently do to select a Dropbox file for synchronisation is to read all files from the user account and list the ones with the proper extension for the user to choose which one she wants.
The problem comes when the user has thousands of valid files. Not only listing files might timeout (2 minutes max) but the UI showing thousands of files is far from usable. See https://github.com/CartoDB/support/issues/1192 for an example.

I'm suggesting to use a [Chooser](https://www.dropbox.com/developers/chooser) instead and let the user explore all her files from Dropbox and simply selecting one using their UI, then use that file id to continue with the import.

This probably requires changes in design, front-end and backend and rethink the flow for providers. Google Drive has also a [Picker](https://developers.google.com/drive/v3/web/picker) widget and others providers might too.

**Comment by Algunenano** [comment]
It appears editor is already using the Chooser at some points, for example to pick up images:
![image](https://user-images.githubusercontent.com/664253/34200614-05d9b2dc-e572-11e7-9b80-5afa7c035896.png)

IMO this is not only way faster but also more easy to navigate once you have a lot of files in your Dropbox account.

**Comment by ramiroaznar** [comment]
This should be implemented to the other connectors: BOX ([related to this GIS SE question](https://gis.stackexchange.com/questions/287583/syncing-to-a-box-file-via-carto)) and GDrive.
