### ISSUE TITLE
Remove card's hover state when hovering the dataset/node inside

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13256]
### Context

If you hover over the dataset of a card, only that element should have a hover state. Right now both that element and the card show the hover state and is misleading. 

### Current Result

![confusing-hover](https://user-images.githubusercontent.com/16247628/34162862-78f81b34-e4d5-11e7-881d-68cd25dd003e.gif)

![confusing-hover-2](https://user-images.githubusercontent.com/16247628/34162865-7cf6949a-e4d5-11e7-8717-75ffee076301.gif)

### Expected result

![screen shot 2017-12-19 at 16 02 01](https://user-images.githubusercontent.com/16247628/34163061-fd1ac380-e4d5-11e7-82d5-d16240aba26f.png)

![screen shot 2017-12-19 at 16 00 22](https://user-images.githubusercontent.com/16247628/34163067-004f47b0-e4d6-11e7-9a8a-a70ad9f4d8fa.png)

**Comment by matallo** [comment]
in production! 🚀
