### ISSUE TITLE
AR connection timeout is not working

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/cartodb#13266]
### Context
*Please explain here below what you were doing when the issue happened*

If you try to connect to unreachable database it will be locked for some time until it gives timeout but we don't have a defined timeout for that kind of connection

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Open a rails console
2. `u = Carto::User.find_by_username('{username}')`
3. Change the `database_host` to `unreachable.db.test` and save
4. Execute u.in_database.execute('select 1')
5. Wait for a long timeout

### Current Result
*Please describe here below the current result you got*

It tooks to long to get the timeout and we should mimic the Sequel timeout

### Expected result
*Please describe here below what should be the expected behaviour*

The same timeout for Sequel and AR connections

**Comment by javitonino** [comment]
Blocking until the Rails 4.2 upgrade because Rails 3 does not support it :(
