### ISSUE TITLE
NoMethodError: undefined method `has_feature_flag?' for nil:NilClass at show_protected_embed_map

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#13260]
I don't know how to reproduce it, but you should be able to do it from the trace:

https://rollbar.com/carto/CartoDB/items/25261/?item_page=0&item_count=100&#instances

Anyway, a quick fix would be adding nil-safety to [the failing check](https://github.com/CartoDB/cartodb/blob/431f5113d0a3c137dddfbedecb64074bcad5185b/app/controllers/admin/visualizations_controller.rb#L413): 

@viewed_user.has_feature_flag?('static_public_map')

In addition, please search for calls to `has_feature_flag?` on `@viewed_user` in the whole project, because this is not the first time that we fix this.

cc @elenatorro 

cc @ramiroaznar for RT prioritization.

**Comment by ramiroaznar** [comment]
Hey @juanignaciosl is this still an issue?

**Comment by ramiroaznar** [comment]
Ping?

**Comment by juanignaciosl** [comment]
I was on vacation, sorry.

Yes, it is. If you open the linked trace, you'll see "Last seen: 3 days ago", meaning that it still happens.

**Comment by javitonino** [comment]
No longer a problem after everything got staticfied.
