### ISSUE TITLE
Remaining details for the Geocode analysis

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13262]
- [ ] Don't show layer onboarding messages if the user has come from the layer list for a layer that needs geocoding. [More info here](https://github.com/CartoDB/design/issues/1032#issuecomment-349951542).
- [ ] Finish updating terminology. Take a look at [this spreadsheet](https://docs.google.com/spreadsheets/d/1bskvfxssy7DfX_DvpWqQJN09cKg8OIqjfmatgUxHyno/edit#gid=1301810365) to see every piece of UI copy that needs to be updated.

**Comment by rubenmoya** [comment]
We're not using this button styles anymore, and the placeholder is showing the old analyses workflow, what should we do with this? @CartoDB/design 

![screen shot 2017-12-28 at 10 30 23](https://user-images.githubusercontent.com/905225/34406591-310c9818-ebba-11e7-8097-c2a3ba7e5509.png)

**Comment by matallo** [comment]
in production! 🚀
