### ISSUE TITLE
Tiny fix for the new analysis list UI

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13278]
- [x] The "Edit Analysis" tooltip shouldn't appear over the selected analysis.
- [x] The "Edit Analysis" tooltip shouldn't appear over an unapplied analysis.

![image](https://user-images.githubusercontent.com/16247628/34300757-d215bd60-e729-11e7-8071-23622f9b79db.png)

**Comment by rubenmoya** [comment]
In production! 🚀
