### ISSUE TITLE
Component consolidation between Builder and DeepInsights

### ISSUE THREAD

**Issue by jesusbotella** [CartoDB/cartodb#13271]
As we are thinking about [merging Builder and DeepInsights](https://github.com/orgs/CartoDB/teams/frontend/discussions/1) into the same codebase, there is some room for improvements here related to components, like component consolidation.

We have detected two main differences between components in Builder and DI:

- Tipsy Tooltips (https://github.com/CartoDB/cartodb/issues/13194)
- Dropdown Overlay (https://github.com/CartoDB/cartodb/issues/13351)
  - Not available in DI widgets yet

Please feel free to add anything else to this list if needed.

**Comment by matallo** [comment]
awesome! thanks @jesusbotella

**Comment by matallo** [comment]
updated the issue with the proper dropdowns reference and closing this to keep track of each separately
