### ISSUE TITLE
Renamed dataset column does not appear on the Analysis tab

### ISSUE THREAD

**Issue by csobier** [CartoDB/cartodb#13279]
Since the Geocode analysis workflow change, when renaming a column from a selected layer Data View, the renamed columns do not appear. @urbanphes 

I am forced to refresh the browser or go back to the LAYERS list; which means I have to select the layer again.

### Context
When geocoding a map layer, rename a column name from the Data View before applying the analysis.

![image](https://user-images.githubusercontent.com/13319925/34302528-52fd71b4-e6ff-11e7-980a-cf8e6d9e2309.png)

### Current Result
The renamed column does not appear on the ANALYSIS tab.

![image](https://user-images.githubusercontent.com/13319925/34302691-07f29e32-e700-11e7-9b5a-0538c1d5cbb9.png)

### Expected result

The renamed column should appear from the ANALYSIS tab parameter options.

Previously, this didn’t happen since the workflow was STYLE tab / GEOREFERENCE button / ANALYSIS so I guess it gave the browser some extra, mandatory clicks. 

Now, the renamed columns never appear (_even after any amount of time, I tested 10 minutes_) unless I refresh or go back to the LAYERS list.

**Comment by ramiroaznar** [comment]
AFAIK this is an expected behavior (not desired). In order to show the renamed field on the UI, you need to force to refresh... @alonsogarciapablo

**Comment by alonsogarciapablo** [comment]
Correct. I don't think we've implemented something for this to work as @csobier describes. It probably happens in other / most? of column selectors in Builder.
