### ISSUE TITLE
Improve API Key API

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#13288]
In order to release soon, we're going to concede some technical debt to #13199.

# Validation simplification

- fail if there's 'config'.
- fail if inheritsFromDefault (or any other attribute) is sent.

Two first issues should be easily handled by ActiveRecord validation, thanks to json schema validator. The current issue is that `Carto::TablePermissions` and `Carto::ApiKeyGrants` currently make some assumptions about the json structure, and they fix wrong incoming values. That approach has some drawbacks:
- A wrong payload for API Key creation (`POST`) should fail with a proper error message. Nevertheless, current processing hides that kind of errors.
- You must implement validations manually, not getting the most out of json schema validation.

Just going to a simpler approach, where  `Carto::TablePermissions` and `Carto::ApiKeyGrants` only care about logic and not about json structure, should fix them.

Also related to this, next lines shouldn't be needed:

```
  before_validation :serialize_grants
  serialize :grants, Carto::CartoJsonSymbolizerSerializer
```

Once "grants" is trustworthy, it doesn't have to be serialized (again).

# Other

- better error if database schema doesn't exist.
- What happens when related tables get deleted?

cc @amartinj

**Comment by amartinj** [comment]
> What happens when related tables get deleted?

I would say that That's something the database handles correctly. When accessing the api, an error would the thrown because the queried database won't exist

**Comment by amartinj** [comment]
returning errors when the request payload includes unnecessary fields complicates the design too much and it doesn't add value since what really matters is the response of what does the api key looks like. We will only validate `grants` structure

**Comment by juanignaciosl** [comment]
> > What happens when related tables get deleted?

> I would say that That's something the database handles correctly. When accessing the API, an error would the thrown because the queried database won't exist

Yes, but we'd be storing a API key with grants that points to a table that doesn't exist. That's an inconsistency. If we don't do anything, for example, the UI might try to display them. Not urgent, but I've just opened an issue about that: #13333.

> returning errors when the request payload includes unnecessary fields complicates the design too much and it doesn't add value since what really matters is the response of what does the api key looks like. We will only validate grants structure

Ferpect tradeoff!

This can be closed then, can't it?

**Comment by amartinj** [comment]
> This can be closed then, can't it?

yes!
