### ISSUE TITLE
Georeference state is not available

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#13286]
I have this map (https://team.carto.com/u/piensaenpixel/builder/73a9819a-17d8-451c-8dd7-7a45809c01ad/embed)  with a non-georeference layer (imported from a .carto) and the non-georeference state is not available

![image](https://user-images.githubusercontent.com/1214201/34321887-2a89f6ba-e819-11e7-8e52-3d33d764f31b.png)

.carto --->  [Elecciones Cataluñas 21D (on 2017-12-23 at 18.33.21).carto.zip](https://github.com/CartoDB/cartodb/files/1584365/Elecciones.Catalunas.21D.on.2017-12-23.at.18.33.21.carto.zip)

cc/ @matallo

**Comment by ramiroaznar** [comment]
![image](https://user-images.githubusercontent.com/5215798/34480247-8e5e217c-efab-11e7-8160-b8c8079cd524.png)

I was not able to replicate the issue. I found a issue (bug?), I was able to import the .carto but without the `resultados_elecciones`. I will open the issue.

**Comment by ramiroaznar** [comment]
Update. The second time you go to BUILDER main menu, the behavior reported is showed:

![image](https://user-images.githubusercontent.com/5215798/34480332-0cf214a8-efac-11e7-8373-871fc84dc93f.png)
