### ISSUE TITLE
Using back arrow after adding an analysis does nothing

### ISSUE THREAD

**Issue by rubenmoya** [CartoDB/cartodb#13298]
### Context
When clicking back after selecting a new analysis nothing happens since the last step was a modal.

### Steps to Reproduce
1. Visit a layer
2. Click on analyses tab and click on the "Add new analysis button"
3. Select any analysis in the modal and click continue
4. Hit the browser back button without adding the new analysis

### Current Result
Nothing happens

### Expected result
I'm not sure what the expected behavior should be, maybe show again the analysis modal? maybe go back to the last visited tab?

cc @alonsogarciapablo

**Comment by matallo** [comment]
While I understand the user who expects to close the modal via a back button click, I wouldn't support this, and I have yet to see an example of this in other UIs: Twitter, Slack, ... these all close the modal and go back to the previous page.
