### ISSUE TITLE
Header in export as image is broken

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#13297]
we need to add the 'Breadcumb'

![image](https://user-images.githubusercontent.com/1214201/34381836-59e4f5b4-eb0b-11e7-823f-f0ea18d49470.png)

cc @matallo

**Comment by rubenmoya** [comment]
Should it be `← Back / Export as image` with another title or `← Back` with "Export as image" as a title?

**Comment by matallo** [comment]
In order to keep consistency I'd have it in the breadcrumb with the title being the layer, as in the edit feature (see attached)

![screen shot 2017-12-28 at 11 51 45](https://user-images.githubusercontent.com/36676/34408662-92fef196-ebc5-11e7-8e73-472d9dbdfbfa.png)

**Comment by rubenmoya** [comment]
But in this case, you are not exporting a layer but the map itself, maybe
show the map name?

**Comment by matallo** [comment]
@piensaenpixel please throw some light! 😄

**Comment by piensaenpixel** [comment]
I think it should be something like this

![image](https://user-images.githubusercontent.com/1214201/34409918-27d717ce-ebcd-11e7-9fdd-73ef63578cb9.png)


does it sounds ok?

**Comment by rubenmoya** [comment]
Looks good to me :)

**Comment by jesusbotella** [comment]
In production! 🚀
