### ISSUE TITLE
"query is required" error dragging out analysis

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#13305]
### Steps to Reproduce

1. Create a new map importing [guess_latitude_longitude.csv.zip](https://github.com/CartoDB/cartodb/files/1591155/guess_latitude_longitude.csv.zip) (although I think that any other dataset would work).
2. Add a centroid analysis (default parameters).
3. Then, drag the analysis out of the layer (in order to create another layer).

### Current Result

The left layer gets stuck, and there's a JS error:

![captura de pantalla 2017-12-28 a las 13 06 11](https://user-images.githubusercontent.com/932968/34410358-f2092490-ebcf-11e7-9571-d641da8e7202.png)
![captura de pantalla 2017-12-28 a las 13 03 56](https://user-images.githubusercontent.com/932968/34410360-f39dc216-ebcf-11e7-9d74-e53422dcb479.png)

### Expected result

A new layer is created.

cc @ivanmalagon @matallo @ramiroaznar

**Comment by rubenmoya** [comment]
Seems to be related to the changes made in: https://github.com/CartoDB/cartodb/issues/13110

**Comment by ramiroaznar** [comment]
cc @jsanz 

This was reported some days ago here: https://github.com/CartoDB/support/issues/1231 This bugazo needs to be fixed.

**Comment by jesusbotella** [comment]
In production!
