### ISSUE TITLE
Alignment of 'back to dashboard' carto logo not aligned with other options in toolbar

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartodb#13301]
### Context
The alignment of 'back to dashboard' carto logo not aligned with other options in toolbar:
<img width="140" alt="screen shot 2017-12-27 at 15 01 13" src="https://user-images.githubusercontent.com/1041056/34392197-a3b2c434-eb18-11e7-90b9-94bf18665e54.png">

### Steps to Reproduce

1. Open a map and look at the toolbar on the left

### Current Result

CARTO back to dashboard logo is aligned to the left (not centered), unlike the map options and map edit selectors below)

### Expected result

It looks off to my eyes. I want it to be centered horizontally.

### Browser and version

* Chrome newest
* Firefox 57.0.1

### .carto file
Not needed

### Additional info

cc @arianaescobar

**Comment by jesusbotella** [comment]
Deploying!

**Comment by matallo** [comment]
in production! 🚀

**Comment by andy-esch** [comment]
Speed demons! Nice work :)
