### ISSUE TITLE
Column actions not working on dataset view

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#13304]
### Context
Playing around with Builder.

### Steps to Reproduce

1. Open any of the datasets in your account.
2. Open the contextual menu for any of the columns by clicking on the icon with three dots.
3. Click on any of the actions.

### Current Result
Clicking on any of the actions doesn't have the desired effect. The menu is closed and that's it.

![column-actions](https://user-images.githubusercontent.com/390398/34409552-c3184850-ebca-11e7-898b-7d24bbfefbfd.gif)

There's no error in the console.

### Expected result

I should be able to reorder, rename, change type, add and delete columns from the contextual menu.

**Comment by jesusbotella** [comment]
It should be related to https://github.com/CartoDB/cartodb/issues/13132

Let me see what happens and fix it.

**Comment by alonsogarciapablo** [comment]
I added this to the Response Team kanban and hopefully @IagoLast can take care of it. @jesusbotella you can probably give him some more context! Thanks!

**Comment by alonsogarciapablo** [comment]
cc: @CartoDB/support

**Comment by jesusbotella** [comment]
It does happen with contextual menus within table cells as well.

I am talking with @IagoLast to fix it as soon as possible.

**Comment by IagoLast** [comment]
Fixed in [4.10.156](https://github.com/CartoDB/cartodb/commit/f841c76ea482849f0615e7ad0277e19900b848f0)
