### ISSUE TITLE
hover box shows unexpected cutting-off behavior in firefox & Mac

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartodb#13300]
### Context

I have hovers enabled for a polygon layer with all fields selected:
![hover_behavior](https://user-images.githubusercontent.com/1041056/34390260-a2c0aa02-eb0c-11e7-897d-9f05f22b13ce.gif)

The hover box that shows the data shows strange / distracting clipping behavior when the mouse pointer is moved around (see GIF above). If you stop moving the pointer and wait a second or two, the full box shows. The clipping resets if the pointer hovers over a new polygon _or_ if the pointer stops moving within a polygon. Maybe some type of event listener is tripped for both of those events?

### Steps to Reproduce

1. Create a map with a polygon layer
2. Enable hovers for all fields
3. Hover over any feature and move pointer around to see how the hover box is clipped depending on placement of pointer

### Current Result

Hover box is clipping in a distracting way that sometimes obscures data

### Expected result
Hover box moves around smoothly with pointer

### Browser and version

Firefox 57.0.1, macOS 10.13.2

### .carto file
Seems to be same with all polygon sets, but here's a polygon dataset: https://team.carto.com/u/eschbacher/tables/eschbacher.cb_2016_51_tract_500k/public?redirected=true

### Additional info
*Please add any information of interest here below*

**Comment by ramiroaznar** [comment]
I was not able to replicate the issue in Firefox 57.0.3. Could you share the .carto? @andy-esch

**Comment by andy-esch** [comment]
Here you go @ramiroaznar (zipped .carto file)
[life_expectancy map (on 2018-01-02 at 14.23.58).carto.zip](https://github.com/CartoDB/cartodb/files/1597771/life_expectancy.map.on.2018-01-02.at.14.23.58.carto.zip)

**Comment by ramiroaznar** [comment]
Again, I was not able to replicate the issue in Firefox 57.0.3. (Ubuntu 16.04). Tested in BUILDER and embed:

![hover](https://user-images.githubusercontent.com/5215798/34487129-3cd9619a-efd3-11e7-9e4b-cb0ef309bd61.gif)

Could any of @CartoDB/support with Mac test it please?

**Comment by oriolbx** [comment]
The error seems to be happening on Firefox 57.0.1 (64-bit) and version 57.0.3 (64-bit) in Mac, but not in Chrome Version 63.0.3239.108 (Official Build) (64-bit) browser though.

**Comment by ramiroaznar** [comment]
Thanks, @oriolbx! Let's move it to RT queue then.

**Comment by alrocar** [comment]
Happened in old browsers. Closing
