### ISSUE TITLE
The add analysis button is wrong aligned

### ISSUE THREAD

**Issue by urbanphes** [CartoDB/cartodb#13308]
### Context
On the zero case and when there is an analysis, the add new analysis button is not aligned on the same position.

### Steps to Reproduce
![artboard](https://user-images.githubusercontent.com/14546701/34413248-7772cea8-ebe2-11e7-9cba-7a6659a1a4d1.png)

### Current Result
There are some pixels of difference. Isn't in the same place.

### Expected result
The button should be in the same position

### Browser and version
<img width="396" alt="captura de pantalla 2017-12-28 a las 15 16 29" src="https://user-images.githubusercontent.com/14546701/34413196-1bb6ed88-ebe2-11e7-8bd1-cdd0bd546a2c.png">

**Comment by matallo** [comment]
in production! 🚀

**Comment by urbanphes** [comment]
Bravo !! 👏
