### ISSUE TITLE
Data view shows empty colums

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#13317]
### Steps to Reproduce

1. Create a new map importing [guess_country_reduced.csv.zip](https://github.com/CartoDB/cartodb/files/1591784/guess_country_reduced.csv.zip) (although I think that any other one will do the same).
2. Go to the layer.
3. Enable data view.

### Current Result

An (almost) empty table is shown, data is missing:

![captura de pantalla 2017-12-28 a las 18 59 04](https://user-images.githubusercontent.com/932968/34418950-3597b4c0-ec01-11e7-9e09-f1189199dacb.png)

### Expected result

Data columns are there.

### Additional info

The importing worked (datasets view shoe the data). I think that it's related to a wrong query. If you see the network activity, this query is sent to the SQL API:

`select  from (SELECT * FROM guess_country) __wrapped`

As you see, a first `*` is missing. The response contains empty rows.

cc @ramiroaznar @ivanmalagon

**Comment by rubenmoya** [comment]
Related to https://github.com/CartoDB/support/issues/1210, there is already a PR open https://github.com/CartoDB/cartodb/pull/13289

**Comment by IagoLast** [comment]
Fixed in https://github.com/CartoDB/cartodb/pull/13289
