### ISSUE TITLE
Map View and Data View behavior is buggy

### ISSUE THREAD

**Issue by csobier** [CartoDB/cartodb#13322]
@alonsogarciapablo , when switching between the Map View and Data View in Builder, the behavior is inconsistent. I tried with a random sample of maps and it is happening for all.

Note that this is recent behavior (it did not happen a week ago, the last time I used Builder before the holidays).

![dataview_issues](https://user-images.githubusercontent.com/13319925/34487077-b2da61f6-efa0-11e7-99ba-63ee56f86a92.gif)

**Comment by ramiroaznar** [comment]
I think this should go to RT.

**Comment by ramiroaznar** [comment]
Fixed! Vamos!

**Comment by matallo** [comment]
in production! 🚀
