### ISSUE TITLE
Can't click ANALYSIS tab after applying Gecode analysis

### ISSUE THREAD

**Issue by csobier** [CartoDB/cartodb#13325]
@alonsogarciapablo , more weirdness with new analysis workflow for Geocoding.

- Apply the GEOCODE analysis. 
  The STYLE tab automatically appears.

- Click the ANALYSIS tab. You cannot. You must refresh the browser or click any other tab before selecting the ANALYSIS tab.

_Note- seems to be related to the Gecoding workflow only. When testing other analysis, I remained on the ANALYSIS tab after they were applied._

![analysis_tab](https://user-images.githubusercontent.com/13319925/34490078-9dd4ca1a-efac-11e7-9a47-5e756cf0dc90.gif)

**Comment by ramiroaznar** [comment]
:-( Another one! Good catch!

**Comment by ramiroaznar** [comment]
Fixed!
