### ISSUE TITLE
Long widget title obscures menu

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartodb#13332]
### Context
If you have a widget with a long title, the edit menu is obscured by the title. See second widget in this list:

<img width="330" alt="screen shot 2018-01-04 at 10 43 57" src="https://user-images.githubusercontent.com/1041056/34571336-3479c03e-f13c-11e7-8655-243521954798.png">

### Steps to Reproduce

1. Create a widget with a long title
2. Observe that the edit menu is obscured

### Current Result

Cannot access edit drop down menu (the vertical ellipses)

### Expected result
Edit menu should still be accessible regardless of the title, similar to what happens in the layer list:
<img width="329" alt="screen shot 2018-01-04 at 10 42 41" src="https://user-images.githubusercontent.com/1041056/34571271-0e7e5eee-f13c-11e7-8baa-b1c74a514cf1.png">

### Browser and version
Firefix 57.0.3, macOS 10.12.3

### .carto file

[life_expectancy map (on 2018-01-04 at 15.41.40).carto.zip](https://github.com/CartoDB/cartodb/files/1603790/life_expectancy.map.on.2018-01-04.at.15.41.40.carto.zip)

### Additional info

Nope

**Comment by arianaescobar** [comment]
Looks like this might have been fixed outside of this ticket: 

![screen shot 2018-01-15 at 11 19 04](https://user-images.githubusercontent.com/16247628/34937711-15a2fc72-f9e6-11e7-9f68-aca85661d48f.png)

But if I could add a few related things: 

- [ ] In the widgets, there's not enough margin between the title and the right actions. There should be 16px of separation. 

![screen shot 2018-01-15 at 11 19 10](https://user-images.githubusercontent.com/16247628/34937743-3098e1ae-f9e6-11e7-83c5-9627d6cee646.png)

- [ ] And we should show the complete title name in the `alt` attribute so users can read it all on hover and to follow proper accessibility guidelines.

**Comment by Jesus89** [comment]
Closed by CartoDB/cartodb#14140

In production! :rocket:
