### ISSUE TITLE
Line subnavigation 2px instead of 1px

### ISSUE THREAD

**Issue by urbanphes** [CartoDB/cartodb#13337]
### Context
The bottom line on the subnav looks like with 2px height instead of 1px as the top bar nav.

### Steps to Reproduce
![line_subnav](https://user-images.githubusercontent.com/14546701/34606944-983c46d4-f211-11e7-8460-6fe04f0b45af.gif)

### Current Result
2px height

### Expected result
1px height

### Browser and version
<img width="396" alt="captura de pantalla 2018-01-05 a las 12 12 34" src="https://user-images.githubusercontent.com/14546701/34606971-bdfada70-f211-11e7-886f-3505893da307.png">

**Comment by matallo** [comment]
in production! 🚀
