### ISSUE TITLE
The start of the steps should be started at the same point

### ISSUE THREAD

**Issue by urbanphes** [CartoDB/cartodb#13338]
### Context
When passing from the Pop-up to Legend tab It seems the start of the steps is not placed it at the same point. It shows like a little jump.

### Steps to Reproduce
![little_jump](https://user-images.githubusercontent.com/14546701/34607286-3a15f5f8-f213-11e7-9fba-8c2e1ec84a65.gif)

### Current Result
Now both forms start at different points

### Expected result
Both forms should start at the same point

### Browser and version
<img width="396" alt="captura de pantalla 2018-01-05 a las 12 12 34" src="https://user-images.githubusercontent.com/14546701/34607243-0b4454ae-f213-11e7-9bdf-18d9283086a8.png">

**Comment by Jesus89** [comment]
Closed by CartoDB/cartodb#14140

In production! rocket
