### ISSUE TITLE
Delete API Key entries when tables get deleted

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#13333]
An API Key contains references to tables. When a table is deleted, we should clean that. Otherwise, we must take that case into account whenever that metadata is used.

- [ ] ~Delete API key entries when tables get deleted.~
- [ ] ~Ensure that API key deletion is clean. If you run~ `spec/requests/carto/api/api_keys_controller_spec.rb`, you see this message ([context](https://github.com/CartoDB/cartodb/pull/13359#discussion_r160512387)):~

```
An error occurred in an after(:all) hook.
  Sequel::DatabaseError: PG::Error: ERROR:  role "test_cartodb_user_75c9f2ee-b568-11e7-ab5a-784f436d1355" cannot be dropped because some objects depend on it
DETAIL:  privileges for database cartodb_test_user_75c9f2ee-b568-11e7-ab5a-784f436d1355_db
3 objects in database cartodb_test_user_75c9f2ee-b568-11e7-ab5a-784f436d1355_db
```

**Comment by amartinj** [comment]
We have changed the approach. Instead of keeping metadata for the permissions of the role, we'll query the database instead, so this is automatically fixed.
