### ISSUE TITLE
Enable CORS for allowed hosts in app_config.yml

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartodb#13336]
For the FE/BE Split, it would be possible to have the backend API and the client application in different hosts. I am not sure about this issue, but I would like to discuss it.

**Comment by javitonino** [comment]
I think this is a good candidate to be solved at the nginx level. I guess it follows the convention we have with the node APIs: if you put them in different domains you have to fix this at nginx level.

What would be nice to have, it's an example nginx configuration to make all of this work in the same domain.

**Comment by alrocar** [comment]
Stale issue. Closing 👋
