### ISSUE TITLE
When editing a widget, disable the rest and focus on active one

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13342]
In an effort to make obvious which is the widget you're editing, we are disabling the rest.

![widgets - category 01](https://user-images.githubusercontent.com/16247628/34618617-9798bd74-f23f-11e7-8ece-fcc603ac0d02.png)

Also, if there are many widgets on the map, and the user accesses the widget options of one that is out of sight, the widgets pane should scroll to show said widget. 

Design issue: https://github.com/CartoDB/design/issues/1138 
InVision: https://invis.io/45F7K0863#/272048325_Widgets_-_Category_01

**Comment by matallo** [comment]
in production! 🚀

**Comment by arianaescobar** [comment]
At some point, we lost this in production... I no longer see it happening ☹️ Any idea? 

cc @ivanmalagon @alonsogarciapablo

**Comment by alonsogarciapablo** [comment]
I wasn't aware of this... I actually never saw it in production.

@ramiroaznar can the RT take a look at this 🙏 ?

**Comment by ramiroaznar** [comment]
OK. But we have a long frontend queue now...

**Comment by arianaescobar** [comment]
Thanks guys ✨

**Comment by arianaescobar** [comment]
This is back on prod!!!!

![screen shot 2018-03-09 at 18 05 07](https://user-images.githubusercontent.com/16247628/37219693-81192686-23c4-11e8-82a2-e7d3665929d2.png)

**Comment by arianaescobar** [comment]
I sang victory too fast... sometimes it works, sometimes it doesn't. And when it does, it get's stuck with the highlighted widget. But I remember doing acceptance on this and it worked great :(
