### ISSUE TITLE
The color line of the indicator on subnav should change 

### ISSUE THREAD

**Issue by urbanphes** [CartoDB/cartodb#13340]
### Context
The color line of the indicator should change from soft grey to dark grey.
The new color is `#2D3C43`

#### Current
<img width="396" alt="captura de pantalla 2018-01-05 a las 14 30 40" src="https://user-images.githubusercontent.com/14546701/34611361-7a7adaf2-f225-11e7-9ff0-84ebb9612df8.png">

#### New color
![captura de pantalla 2018-01-05 a las 14 30 27](https://user-images.githubusercontent.com/14546701/34611364-7c29946a-f225-11e7-9614-31b39d114754.png)

### Current Result
The line has a soft gray color.

### Expected result
The same color that main nav.

### Browser and version
<img width="396" alt="captura de pantalla 2018-01-05 a las 14 35 34" src="https://user-images.githubusercontent.com/14546701/34611422-b7ab3160-f225-11e7-9631-71f6e6436a11.png">

**Comment by matallo** [comment]
in production! 🚀
