### ISSUE TITLE
Slow shared_entities check

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#13353]
The `User.has_shared_entities?` check is very slow, since it implies a sequential scan of the permissions table.

Ideas:
1. Remove the check, and replace it for something that checks the `SharedEntities` model instead of the `Permissions` model. It's better optimized.
2. Index `permissions.owner_id`
3. Clean the permissions table.

**Comment by javitonino** [comment]
Stealing this for RT, since it's blocking other RT issues. cc @ramiroaznar

**Comment by ramiroaznar** [comment]
No prob, go ahead!
