### ISSUE TITLE
Add credits popup for namedplaces analysis

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/cartodb#13354]
Name places analysis is using Mapzen provider by default and we have a fallback to internal geocoder in case Mapzen fails. The problem is that we are consuming users credits without saying or consulting the user so we should provide the same credits popup we have for other analysis like isolines or street geocoding.

When this change was made we didn't charge for the use of Mapzen services but now we're charging for it and with the close of Mapzen and the use of a new provider this should be added.

**Comment by ramiroaznar** [comment]
I suppose we have already a default message for that? @CartoDB/support

**Comment by ramiroaznar** [comment]
Please @elenatorro take this one next.

**Comment by ethervoid** [comment]
AFAIK and I've created a `Cities geocoding` analysis right now we're not showing anything

**Comment by ramiroaznar** [comment]
Sorry I mentioned support instead of @CartoDB/design. I suppose we need to add this message as we are currently doing with the `address` geocoding:

![image](https://user-images.githubusercontent.com/5215798/34775254-c4a1ba7e-f612-11e7-8552-1e881849f481.png)

**Comment by ramiroaznar** [comment]
### STR

1. Create a map with a dataset with city names as columns
2. Add Geocoding analysis
3. Select `Cities`
4. Set parameters

### Current result

* There is not green popup warning the user.

### Expected result

* Sames as [here](https://github.com/CartoDB/cartodb/issues/13354#issuecomment-356602432).

**Comment by urbanphes** [comment]
Of course, if we're charging credits any analysis, we must inform our users about this. 
We have this kind of infobox (screenshot @ramiroaznar) for that purpose.

**Comment by elenatorro** [comment]
Deployed in production 🚀

**Comment by ethervoid** [comment]
👏 ❤️
