### ISSUE TITLE
Unnecessary shared_entities check when force deleting a user

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#13352]
https://github.com/CartoDB/cartodb/blob/master/app/models/user.rb#L426

That check could be inverted to avoid doing the `shared_entities` check (expensive) in the force deletion check.

**Comment by javitonino** [comment]
cc @ramiroaznar: this is a follow-up of a RT issue, so we don't get a repeat.

**Comment by ramiroaznar** [comment]
Roger that!
