### ISSUE TITLE
User mover error: raster/overlays + raster data

### ISSUE THREAD

**Issue by dgaubert** [CartoDB/cartodb#13350]
This guide describes how to resolve a migration that fails because of #12391 and #12741 at the very same time.

1. Export user database:

   - `$ RAILS_ENV=production bundle exec rake cartodb:user_migrator:export:organization[<usename|org_name>,false]`

3. Modify the generated `import_for_<export_uuid>.json` file to point to the right destination database host:

   -  Replace template placeholder `<destination db host>` by the database IP. For instance: `10.0.0.1`

4. Modify exported index:

   - Copy `exported_file` property from: `$ cat import_for_<export_uuid>.json`
   - Download the exported dump: `$ curl -v -o export.zip "<url>"`
   - `$ unzip export.zip -d ./`
   - `$ pg_restore -l org_<organization_id.dump > ./<username|org_name>.dump.index`
   - Edit generated dump index: `$ vim <username|org_name>.dump.index` comment (with ;) the lines with TABLE DATA from overviews (lines containing TABLE DATA on an overview table, which are the ones that begin with o_)

5. Modify `services/user-mover/import_user.rb`:
   - Add `-L /tmp/<temp_folder>/<username|org_name>.dump.index` to pg_restore command, line 386 (between arguments `--disable-triggers` and `-Fc`)
   - Add `sleep(60)` after line 513

6. Run import rake, we are going to alter functions after database setup and database import:

   - `$ RAILS_ENV=production bundle exec rake cartodb:user_migrator:import['/tmp/import_for_<export_uuid>.json']`
   - Right away, **from `destination_db_host`'s session**:

      - Try to connect to user's database with: `# \c <user_database>` every second or so.
      - Once you are connected, run the following _alter function_s:

```sql
ALTER FUNCTION _raster_constraint_pixel_types(raster) SET search_path=pg_catalog,public,postgis;
ALTER FUNCTION _raster_constraint_nodata_values(raster) SET search_path=pg_catalog,public,postgis;
ALTER FUNCTION _raster_constraint_out_db(raster) SET search_path=pg_catalog,public,postgis;
ALTER FUNCTION _raster_constraint_info_regular_blocking(name, name, name) SET search_path=pg_catalog,public,postgis;
ALTER FUNCTION _overview_constraint(raster, integer, name, name, name) SET search_path=pg_catalog,public,postgis;
```

7. Modify again exported index to perform commented lines:

   - Modify `<username|org_name>.dump.index` by removing everything but the commented lines and then uncomment those
   - Run pg_restore manually:
      - `$ /usr/lib/postgresql/9.5/bin/pg_restore -e --verbose --disable-triggers -L /tmp/<temp_folder>/<username|org_name>.dump.index -Fc /tmp/<temp_folder>/data/org_<organization_id>.dump -U postgres -h '10.0.224.58' -p 5432 -d <user_database>`

   - If `pg_restore` fails, list failing tablename and drop their constraints:

```sql
SELECT DropOverviewConstraints('<username>'::name, 'o_<zoom_level>_<tablename>'::name, 'the_raster_webmercator'::name);

For instance:
SELECT DropOverviewConstraints('wadus'::name, 'o_16_wadus_table'::name, 'the_raster_webmercator'::name);
```

   - Edit `<username|org_name>.dump.index` again, remove lines that were successfuly restored and run again: `$ /usr/lib/postgresql/9.5/bin/pg_restore -e --verbose --disable-triggers -L /tmp/<temp_folder>/<username|org_name>.dump.index -Fc /tmp/<temp_folder>/data/org_<organization_id>.dump -U postgres -h '10.0.0.1' -p 5432 -d <user_database>`

   - Recreate overview constraint:

```sql
SELECT AddOverviewConstraints('<username>'::name, 'o_<zoom_level>_<tablename>'::name, 'the_raster_webmercator'::name, '<username>'::name, 'o_<zoom_level>_<tablename>'::name, 'the_raster_webmercator'::name, <zoom_level>);

For instance:
SELECT AddOverviewConstraints('aprior'::name, 'o_1_wadus_table'::name, 'the_raster_webmercator'::name, 'aprior'::name, 'o_1_wadus_table'::name, 'the_raster_webmercator'::name, 1);
```

8. Update metadata and DNS configuration to redirect to the new server
   - From central's session:
      - `$ RAILS_ENV=production bundle exec rake cartodb_central:user_migrator:update_database_host[<username|org_name>,'<cloud_ip>','<user_database_ip>']`

**Comment by ramiroaznar** [comment]
Related to https://github.com/CartoDB/cartodb/issues/12391 ?

**Comment by dgaubert** [comment]
And #12741

It's dual combo issue.

**Comment by ramiroaznar** [comment]
Ah ok, thanks, I did not read the first line...

**Comment by dgaubert** [comment]
I mean, it's fixed. We can close it. 

this issue it's more a guide to fix it than a regular issue
