### ISSUE TITLE
Unify dropdowns

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#13351]
### Context

Similarly to DeepInsights tooltips consolidation in https://github.com/CartoDB/cartodb/issues/13194 we should consolidate different dropdowns we have in the application.

Find attached three different occurrences of this component, using different views for each one

![screen shot 2018-01-09 at 10 41 42](https://user-images.githubusercontent.com/36676/34716323-cf39f430-f52f-11e7-899f-f6c2d7e61a63.png)
![screen shot 2018-01-09 at 10 41 51](https://user-images.githubusercontent.com/36676/34716324-cf54e718-f52f-11e7-93fe-7231afabda96.png)
![screen shot 2018-01-09 at 10 44 31](https://user-images.githubusercontent.com/36676/34716325-cf6ffa4e-f52f-11e7-98e3-bde58a768e86.png)

**Comment by ramiroaznar** [comment]
@Jesus89 is this fixed?
