### ISSUE TITLE
On Analysis modal the cards disabled are wrong

### ISSUE THREAD

**Issue by urbanphes** [CartoDB/cartodb#13361]
### Context
The cards we show disabled are wrong:
- The color of the card
- The opacity of text and images
- The state: we allow hover state

### Steps to Reproduce
Try to add any analysis and see how it show the cards disabled

### Current Result
<img width="977" alt="captura de pantalla 2018-01-09 a las 18 09 17" src="https://user-images.githubusercontent.com/14546701/34733337-441ae97a-f568-11e7-9601-f46f0758b9ca.png">

### Expected result
<img width="1038" alt="captura de pantalla 2018-01-09 a las 18 12 20" src="https://user-images.githubusercontent.com/14546701/34733454-b8ec9348-f568-11e7-8f82-2f5986dc0f80.png">

To get this:
- Remove the card frame
- Remove the image background
- Give 24% opacity to the text.

### Browser and version
<img width="396" alt="captura de pantalla 2018-01-09 a las 18 13 19" src="https://user-images.githubusercontent.com/14546701/34733482-ce7f6f32-f568-11e7-9fb7-0bcf38d56d6e.png">

**Comment by Jesus89** [comment]
Closed by CartoDB/cartodb#14140

In production! :rocket:
