### ISSUE TITLE
Tabs not being enabled/disabled when updating an analysis

### ISSUE THREAD

**Issue by rubenmoya** [CartoDB/cartodb#13360]
### Context
With the new geocoding/routing when updating an analysis the tabs are not being re-rendered to reflect the last state.

### Steps to Reproduce
1. Add a map with points
2. Add a subsample analysis with 0%

### Current Result
The tabs still enabled and are disabled when you click in one of them.

### Expected result
The tabs are disabled automatically

**Comment by elenatorro** [comment]
We can close this because it has already been solved in v4.11.85 👍
