### ISSUE TITLE
Icon marker misalignment

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#13379]
### Steps to Reproduce
Style a map using a marker icon.

### Current Result
The icon preview is misaligned.

![image](https://user-images.githubusercontent.com/1078228/34867772-a9359a38-f781-11e7-8dee-d8833a1e142b.png)

**Comment by ramiroaznar** [comment]
Closing in favor of https://github.com/CartoDB/support/issues/1207
