### ISSUE TITLE
Make widgets appear on top v2

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#13370]
### Context
We changed the visualization order of widgets as requested in https://github.com/CartoDB/cartodb/issues/13244

More context here: https://github.com/CartoDB/support/issues/1262.

The problem is that we broke all the existing dashboards and there were multiple customer complaining about it -> https://github.com/CartoDB/support/issues/1262#issuecomment-356950503 so we had to rollback.

We need to address again the requirement of new widgets appearing on top but avoiding breaking existing dashboards. There were [a conversation in the original PR](https://github.com/CartoDB/cartodb/pull/13249#issuecomment-353096789) to achieve it but the solution was discarded. Now it doesn't seem as bad idea as before. The main issue is doing multiple requests to update every widget id. Perhaps can be done in batch, avoiding all that overhead.

**Comment by alonsogarciapablo** [comment]
@matallo I moved this to To Do because it's something that we implemented before that we had to rollback due to some issues (more context in https://github.com/CartoDB/support/issues/1262).

**Comment by elenatorro** [comment]
🚀

**Comment by alonsogarciapablo** [comment]
Great job @elenatorro 💪! Congrats! 👏👏👏
