### ISSUE TITLE
Billing unit tests fail if system time is set to timezone prior to UTC

### ISSUE THREAD

**Issue by bb-acarrera** [CartoDB/cartodb#13371]
### Context
The billing unit tests (geocoding, here, data observatory, mapzen) in ./spec/models/user_spec.rb (or more specifically ./spec/models/user_shared_examples.rb) fail if the system time of the machine is set to a timezone prior to UTC such as NY EST (UTC - 0500).  This is appears to be because the billing logic assumes that timezones are in UTC, but does not enforce it.  

This can be solved by insuring user.period_end_date always returns in UTC.  Longer term all DateTime objects within carto should take (and honor) a timezone as well to avoid these type of issues.

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Set system timezone to NY EST (UTC -0500)
2. make prepare-test-db
3. RAILS_ENV=test bundle exec rspec ./spec/models/user_spec.rb

**Comment by gfiorav** [comment]
Essentially this means that our billing system for geocodings won't work in other timezones. Not a priority, but certainly worth considering.

cc/ @ramiroaznar
