### ISSUE TITLE
Analyses names and descriptions update

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13384]
⚠️ ⚠️ ⚠️  **THIS SHOULD BE DEPLOYED TOGETHER WITH https://github.com/CartoDB/learn/issues/520** ⚠️ ⚠️ ⚠️ 

--

We are improving our analyses names and descriptions in an attempt to make them easier to understand and use.

In [this document](https://docs.google.com/spreadsheets/d/1evEdrFyJEefx2-NOHU2_kDcNkKNM0_dbvJ-l9BAg2Go/edit#gid=0), you can find all the new names, descriptions, and UI copy changes.

In this [InVision prototype](https://invis.io/WZFB8GZEV#/273204231_Analysis_-_Create_Areas_Of_Influence_02), you can see the UI with the new copy applied. But please review the second tab of the document attached above for a detailed view of the changes.

Design issue: https://github.com/CartoDB/design/issues/1128

cc @hannahblue

**Comment by rjimenezda** [comment]
Question, on the mock:

![image](https://user-images.githubusercontent.com/446970/35033708-ea7f9f14-fb6b-11e7-8ee1-b644c3fb0d3d.png)

On builder, MORE INFO is breaking into two lines, as well as the second string:

![image](https://user-images.githubusercontent.com/446970/35033784-362d6c8e-fb6c-11e7-875d-4c32821b229e.png)

Would you like it better this way?

![image](https://user-images.githubusercontent.com/446970/35033790-408ce402-fb6c-11e7-9934-67101d6c9e34.png)

**Comment by arianaescobar** [comment]
Good catch. That's because we need to relocate the "More info" link: https://github.com/CartoDB/design/issues/1169 

Let me work on that this morning and I'll let you know! (You guys are working so fast!!!)

**Comment by rjimenezda** [comment]
👍

**Comment by arianaescobar** [comment]
Done @rjimenezda! https://invis.io/DMFDJ9GXRCY#/273927554_Analysis_-_1

**Comment by rjimenezda** [comment]
🆒  thanks!

**Comment by arianaescobar** [comment]
@hannahblue Now that we've shared the news about the analysis renaming in the Product updates blog... when should we merge all the related PRs?

**Comment by hannahblue** [comment]
Yeah, let's go for it!

cc @jorgesancha for transparency

**Comment by arianaescobar** [comment]
Yay! I discussed it with Ivan and we'll merge everything tomorrow morning, Madrid time. 

cc @ivanmalagon @owayss

**Comment by ivanmalagon** [comment]
Shipped! 🚀
