### ISSUE TITLE
Time series tooltips don't show the right info

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#13381]
![tooltips bug](https://user-images.githubusercontent.com/1078228/34869204-7191ca0c-f786-11e7-8bc3-8cfa74e38a6a.gif)

Support ticket: https://github.com/CartoDB/support/issues/1269

### Steps to Reproduce
1. Create a map from a dataset that has a date column
2. Create a time-series widget
3. Hover on time-series buckets.

### Current Result
All buckets show the same tooltip text.

### Expected result
Every tooltip shows the correspondent bin frequency.

**Comment by ramiroaznar** [comment]
Fixed here https://github.com/CartoDB/cartodb/pull/13385
