### ISSUE TITLE
Table dependencies map cards broken on Editor

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#13386]
### Steps to Reproduce

0. Be on editor
1. Create a map from a private dataset
2. Go to dashboard and attempt to delete the dataset

### Current Result

The map card for the created map is broken

![screen shot 2018-01-12 at 18 07 15](https://user-images.githubusercontent.com/4222826/34886568-abeb288c-f7c3-11e7-998d-947928ae2d6f.png)

### Expected result

The map card for the created map shows up

**Comment by gfiorav** [comment]
cc/ @ramiroaznar

**Comment by ramiroaznar** [comment]
Hey @gfiorav when you said _the map card is broken_ you mean the thumbnail is not showing anything right?

**Comment by ramiroaznar** [comment]
It looks like it is happening on all cards from the maps dashboard:

![image](https://user-images.githubusercontent.com/5215798/34936147-87b7afa2-f9e0-11e7-8bb9-a46276f9b6d8.png)

Error in the console: `Failed to load resource: the server responded with a status of 404 (Not Found)`

```js
{
  errors: [
    "Template 'tpl_5e6153ae_e028_47db_9429_b5edd5f113dd' of user 'solutions-editor' not found"
  ],
  errors_with_context: [
    {
      type: "unknown",
      message: "Template 'tpl_5e6153ae_e028_47db_9429_b5edd5f113dd' of user 'solutions-editor' not 
      found"
    }
  ]
}
```

**Comment by ramiroaznar** [comment]
Please take this one first. @enekid

**Comment by javitonino** [comment]
Oki, so this is a tricky one. Basically, the auth tokens are not being sent in that request, so it fails. Fixing it is a bit convoluted:
- Add `auth_tokens` to the table presenter (backend) and check security implications.
- Read `auth_tokens` in frontend and somehow pass them to the URL generator (not trivial, as the parameters are written to DOM instead of using normal function calls).

As a note, I think this bug has been part of carto since the new dashboard (5 years or so).

**Comment by gfiorav** [comment]
Just to leave the note here, we recently fixed a similar issue (mapcards for org private maps in dashboard).

Links:

https://github.com/CartoDB/cartodb/pull/13119
https://github.com/CartoDB/cartodb.js/pull/1928

**Comment by gfiorav** [comment]
Bloomberg guys found a workaround, in case it's helpful: https://github.com/cartodb-org/cartodb/pull/272/files

**Comment by ramiroaznar** [comment]
^^ @javitonino @elenatorro

**Comment by javitonino** [comment]
Yeah, that's the fix I went for at first, but I went further and refactor it, extracting all that code to a presenter. I don't want to keep maintaining those serialize methods :)

**Comment by elenatorro** [comment]
We have already been talking about this. These changes must also be applied to the static pages we developed for the FE/BE split.

**Comment by elenatorro** [comment]
I have just checked it and @javitonino's changes are already applied to the frontend files and they work also in the static dashboard, so, it is done 🎉  

![delete_dataset](https://user-images.githubusercontent.com/3824953/34980601-556150ec-faa5-11e7-8fbe-1d07e6369eb8.gif)

**Comment by ramiroaznar** [comment]
@elenatorro let me know where can I give you the acceptance! :-)
