### ISSUE TITLE
Enrich `Downloaded layer` event

### ISSUE THREAD

**Issue by msaenzde11** [CartoDB/cartodb#13391]
@ivanmalagon noticed while correcting a bug that a new event [`Downloaded layer`](https://github.com/CartoDB/cartodb/pull/13051/files#diff-db6a5ce184e169acb566f05d9002cffe) that we're sending to Segment only contemplates de case of _exporting data_ from the principal view of Builder, while this can also be done from the layer view and the dataset view.

In that case, would it be possible adding the other cases and assigning a field `from_view` relating the source of this event (main view, layer view, dataset view)?

Thanks guys!
cc @matallo

**Comment by matallo** [comment]
for sure it is feasible

**Comment by msaenzde11** [comment]
When taking this issue, please note that fields have to be manually added in the Backend part (https://github.com/CartoDB/cartodb-central/issues/1997).

LMK with any hesitation and for help I can provide!! Thanks :)

**Comment by msaenzde11** [comment]
@matallo could you include this in you Kanban when possible please? Might not be that urgent, but would like it to be in your radar :)

Thanks!!

**Comment by ramiroaznar** [comment]
@ivanmalagon @msaenzde11 what is the status of this issue?

**Comment by msaenzde11** [comment]
it's stuacked @ramiroaznar! If we could add it to the kanban it'd ne nice!
