### ISSUE TITLE
click on privacy link on datasets view does nothing

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#13398]
### Context

when in datasets view of the dashboard, if you click the dats
asets link (PUBLIC, PRIVATE, ...) it should appear the privacy dialog, instead it does nothing

### Steps to Reproduce

1. go to dashboard
2. click on datasets in the header dropdown
3. click on shared datasets in the navbar
4. click on the privacy link of the dataset

### Current Result

no action

### Expected result

privacy dialog should appear

![screen shot 2018-01-15 at 17 32 13](https://user-images.githubusercontent.com/36676/34952606-991b17d6-fa1a-11e7-975f-a9c664a91263.png)

**Comment by matallo** [comment]
actually this is the expected behaviour for shared datasets, but we should add the tooltips to change privacy/you are not allowed to change privacy as in the dataset view

**Comment by ramiroaznar** [comment]
Yes. It is fixed.
