### ISSUE TITLE
render embed maps inside tab panes for mobile

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#13393]
### Context

as part of the embed mobile project we should start by rendering the embed map inside a tabpane for mobile viewports

link to the invision in the project issue

**Comment by rubenmoya** [comment]
We have a couple of questions regarding this issue.

Right now, in Builder you have some configuration to show the toolbar and the legends:

![screen shot 2018-01-18 at 10 02 13](https://user-images.githubusercontent.com/905225/35089270-b1555cd0-fc36-11e7-9be6-8db6785ed785.png)

What should we do in the mobile view with the legends? Show the tab disabled? Hide both tabs? And what about the toolbar? Should we hide the title?

cc @piensaenpixel

**Comment by piensaenpixel** [comment]
Talked in person
- If the user doesn't select the toolbar, we don't show the title (they are related)
- If the user hides the legends, we don't show the tabs and the map is full size.

**Comment by alonsogarciapablo** [comment]
cc: @micagm -> perhaps you could test this in our staging environment once it's ready.

**Comment by alonsogarciapablo** [comment]
I tried this in staging and it's working like a charm. Great job @rubenmoya!

I sent an email to some folks to notify them and see if they have something to say before we push the 🔴  button. Let's release this tomorrow unless we encounter any blocker.

**Comment by rubenmoya** [comment]
Thank you @alonsogarciapablo! I was lucky to pair with @jesusbotella :D

**Comment by jesusbotella** [comment]
@piensaenpixel just told me that the couple of issues that he saw yesterday are solved, so 🎉.

I also removed Rubber Band effect when scrolling which was providing a poor UX in iOS.

**Comment by matallo** [comment]
in production! 🚀

**Comment by alonsogarciapablo** [comment]
BRAVO, BRAVO! 👏 👏 👏

**Comment by jesusbotella** [comment]
VAMOS! 💪
