### ISSUE TITLE
A few errors in the DO Analysis UI

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13402]
- [ ] We shouldn't be showing this. Is this because of where the geometry is situated? 

![dropdown](https://user-images.githubusercontent.com/16247628/34979862-eb30bb42-faa2-11e7-8578-38cdc2c5e599.gif)

<img width="669" alt="screen shot 2018-01-11 at 11 00 10" src="https://user-images.githubusercontent.com/16247628/34979967-35a9ff30-faa3-11e7-82a2-a09ff5405b5a.png">

- [ ] When there are measurements available, the dropdown also behaves incorrectly. It opens on top of the following input, it adds border-radius to the options list where there shouldn't be any, and the search box appears a few pixels to the left of the options list. 

![dropdown-2](https://user-images.githubusercontent.com/16247628/34980070-93742f50-faa3-11e7-9462-264a37155308.gif)

![radius](https://user-images.githubusercontent.com/16247628/34980578-40a8e778-faa5-11e7-99be-962b8ad14b1b.png)

- [ ] There shouldn't be any more line below the "Boundaries" point. 
- [ ] There's more margin than it should be between "Measurement" and "Normalize"

![screen shot 2018-01-16 at 10 05 13](https://user-images.githubusercontent.com/16247628/34980468-f0c2d084-faa4-11e7-9a10-7936fc5aa028.png)
(Left: Mockup | Right: Production)

.carto used: 
[Demographics of the United Kingdom.zip](https://github.com/CartoDB/cartodb/files/1634257/Demographics.of.the.United.Kingdom.zip)

**Comment by ramiroaznar** [comment]
@antoniocarlon can you answer Ari's questions before pushing this to the RT kanban?

**Comment by antoniocarlon** [comment]
We are using the geometries' extent to get the available numerators. For example:

https://xxx.carto.com/api/v2/sql?q=SELECT%20numer_id%2C%20numer_name%2C%20numer_description%2C%20numer_type%2C%20numer_aggregate%2C%20numer_tags%20FROM%20_OBS_GetNumerators((SELECT%20ST_SetSRID(ST_Extent(the_geom)%2C%204326)%20FROM%20(SELECT%20*%20FROM%20<my_table>)%20q)%2C%20section_tags%20%3D%3E%20%27%7Bsection%2Ftags.au%7D%27)%20ORDER%20BY%20numer_name%20ASC&api_key=<my_api_key>

**Comment by arianaescobar** [comment]
@antoniocarlon I didn't understand that sorry.

**Comment by ramiroaznar** [comment]
@arianaescobar The answer is yes. I asked Antonio to let us know how BUILDER gets the numerators (measures) in order to understand if this is a backend issue or not. And it does. So to avoid showing those countries, we need to use the SQL API with `OBS_GetAvailableBoundaries` for example.  

@javitonino should fix this 1st part, and @elenatorro will take care of the frontend part.

**Comment by arianaescobar** [comment]
Perfect. Thanks!

**Comment by javitonino** [comment]
I would say this is a frontend task. The only thing a bit more backend would be to adjust the query, but the query itself is run from JS code (so frontend). And the rest of stuff (cosmetic) is pure frontend.

I can help the frontender with the query if necessary (but I think it's easy enough). Basically, we have to pass the bounding box to the `OBS_GetAvailableNumerators` function as Antonio mentioned. We already do that for the numerators, so it would be just a question of copying that to the region-listing query.

**Comment by alrocar** [comment]
Stale issue. Closing 👋
