### ISSUE TITLE
Similar notifications should be stacked

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13407]
For example, when adding widgets in batch, the "Adding widget.." and "Widget successfully added" notifications should be just one saying the same but in plural, for example.

![widgets](https://user-images.githubusercontent.com/16247628/34986779-2335b14e-fab9-11e7-8516-ad14c8251762.gif)

**Comment by ramiroaznar** [comment]
![image 030](https://user-images.githubusercontent.com/5215798/35107504-6b4b28e2-fc71-11e7-87a7-cd14d2a94dd2.png)

I am getting lots of notifications just adding one layer...

**Comment by ramiroaznar** [comment]
@elenatorro This is fixed.
