### ISSUE TITLE
Disable input's interactivity signifiers when there are no options available

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13404]
In the `Join columns from 2nd layer` analysis I'm seeing this: 

![join](https://user-images.githubusercontent.com/16247628/34981090-be450846-faa6-11e7-9785-ebc43051a507.gif)

If there are no options available for the "Geometry from" input (or any other input for that matter), said input shouldn't appear active with all its interactivity signifiers (hover state, focus state, cursor change...).

**Comment by alrocar** [comment]
Stale issue. Closing 👋
