### ISSUE TITLE
Persistent form's focus state

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13403]
![focus-state](https://user-images.githubusercontent.com/16247628/34980772-cd2105fa-faa5-11e7-9406-0a28ae27527b.gif)

The focus state (black outline) should only be visible _on focus_. Right now that state is not going away in some cases.

**Comment by rubenmoya** [comment]
Fixed in https://github.com/CartoDB/cartodb/pull/13625
