### ISSUE TITLE
When adding widgets in batch, don't access any widget options automatically 

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13408]
Right now when you add a widget, we take you directly to that widget options. The same happens when you add multiple widgets at the same time, but we can only show one widget's options for obvious reasons.

In this scenario, the ideal behavior would be to **not** access any and stay in the WIdgets list so the user can see all the added widgets both in that list and in the pane to the right of the map.  

![widgets](https://user-images.githubusercontent.com/16247628/34987014-03c86d3c-faba-11e7-9818-b804fa2a26c9.gif)

Also, notice the bug when I click on "Back" at the end of the gif and I'm taken to another widgets option instead of the Widgets list.

**Comment by rubenmoya** [comment]
Fixed in https://github.com/CartoDB/cartodb/pull/13867
