### ISSUE TITLE
Clicking anywhere else but the title on the Widget card do not go to edit widget

### ISSUE THREAD

**Issue by jesusbotella** [CartoDB/cartodb#13409]
### Context
Clicking anywhere else but the title on the Widget card do not go to edit widget view. 

### Steps to Reproduce

1. Go to any created map
2. Click on the Widget tab
3. Try to click on the `Source` label placed on the widget card

### Current Result
It does nothing

![widgetcardclick](https://user-images.githubusercontent.com/4319728/34987661-3a1c569e-fabc-11e7-83a6-10294591f02d.gif)

### Expected result
It should redirect me to the view where I can edit the widget I clicked

### Browser and version
Google Chrome
Version 63.0.3239.132

**Comment by ramiroaznar** [comment]
@arianaescobar this is expected, right? In doing so you can drag and order your widgets...

**Comment by arianaescobar** [comment]
Everything should be clickable, the drag and drop doesn't compete with that. 

It would similar to what we did for the layers items:
![be4f94ac-e2e0-11e6-801b-cdfcf616f821](https://user-images.githubusercontent.com/16247628/34989790-23f0ad4a-fac4-11e7-84c7-5b026136d4af.png)

**Comment by ramiroaznar** [comment]
Reviewing again all frontend issues, I think that clicking on everything else but the title *should not direct you to the editing module*...

**Comment by Jesus89** [comment]
Closed by https://github.com/CartoDB/cartodb/pull/14139

In production! :rocket:
