### ISSUE TITLE
Publish modal not working in /settings view

### ISSUE THREAD

**Issue by rubenmoya** [CartoDB/cartodb#13418]
### Context
When clicking on "publish" in the /settings view the modal appears broken
![publish modal](https://user-images.githubusercontent.com/905225/35089042-03db0dfc-fc36-11e7-84a2-70c6ff2aa61a.gif)

### Steps to Reproduce
1. Click on the settings icon
2. Click on the publish button

### Current Result
The modal appears broken, with this error in the console:
![screen shot 2018-01-18 at 09 57 05](https://user-images.githubusercontent.com/905225/35089092-2619bf76-fc36-11e7-962e-3f650c37c039.png)

### Expected result
The modal shows correctly

**Comment by ramiroaznar** [comment]
Good catch!

**Comment by ramiroaznar** [comment]
Reported by SB/15632887
