### ISSUE TITLE
copyright shows up as HTML tag in static image exports

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartodb#13411]
### Context

When a static image is exported from Builder, the attribution includes the HTML `&copy;` instead of &copy;.

![untitled map 8](https://user-images.githubusercontent.com/1041056/34999109-e17cc18e-faae-11e7-89d6-616d2ef2f17d.png)

### Steps to Reproduce

1. Export an image from a map using the 'Export image...' option in the map dropdown:
<img width="471" alt="screen shot 2018-01-16 at 11 18 44" src="https://user-images.githubusercontent.com/1041056/34999183-15119dda-faaf-11e7-8ad0-33040e9a12a9.png">

2. Download the image and open it
3. Note the attribution includes the HTML for the copyright symbol

### Current Result
HTML tag instead of symbol

### Expected result
`&copy;` should show up as &copy;

### Browser and version

Firefox 57.0.4, macOS 10.13.2

### .carto file
[Untitled Map 8 (on 2018-01-16 at 16.20.36).carto.zip](https://github.com/CartoDB/cartodb/files/1635909/Untitled.Map.8.on.2018-01-16.at.16.20.36.carto.zip)

### Additional info
None

**Comment by rubenmoya** [comment]
Unable to reproduce using `Chrome`, `Safari` and `Firefox` in `macOS Sierra 10.12.6` :(

**Comment by andy-esch** [comment]
I just did an image export and got the same result with the `&copy`:

![untitled map 10](https://user-images.githubusercontent.com/1041056/40563803-2413d27c-6034-11e8-9896-70fb2453f33e.png)

I tried two different maps made recently -- both had the `&copy;` in the image export.

Firefox 59.02, macOS 10.13.4

**Comment by Jesus89** [comment]
Hi  @andy-esch,

Could you check Export Image again with the latest version? I have obtained:
![test](https://user-images.githubusercontent.com/2227572/42047714-591b7866-7b01-11e8-8ec8-7e88e027c31f.png)

**Comment by andy-esch** [comment]
I tried Safari, Firefox, and Chrome for new maps and ones that I've had for about a week. All of them had the `&copy;` in them instead.

![untitled map 13](https://user-images.githubusercontent.com/1041056/42050586-5ecdcc8e-7ad7-11e8-9d71-41ba8eaab6e5.jpg)

**Comment by michellemho** [comment]
I am also encountering the same error.

![nyc_waze_data_jams map](https://user-images.githubusercontent.com/12551177/42060383-97f9d2d8-7af4-11e8-9ecc-07cc377b25b6.png)

**Comment by rjimenezda** [comment]
I don't know if this is a config issue (basemap attribution is defined there). Maybe some servers have &copy; in their basemap config? I'm not sure if each server has a different app_config. 

In any case, I can reproduce it. For me, the basemaps collection has &copy; instead of ©

I'll parse it client-side just to be safe.

**Comment by rjimenezda** [comment]
@ramiroaznar User on staging: `copyright-this`

I've verified that the basemaps arrive with `&copy;` and the picture has &copy;, but feel free to take a look

**Comment by ramiroaznar** [comment]
![untitled map](https://user-images.githubusercontent.com/5215798/42562211-6a37918a-84fb-11e8-9683-1314a64ad6e4.png)

@rjimenezda is this the expected result?

**Comment by rjimenezda** [comment]
Yep, it shouldn't show any `&copy;`

You can verify that it has  `&copy;`by opening the developer tools and writing `basemaps.CARTO.voyager.attribution`

**Comment by ramiroaznar** [comment]
LGTM!
`"&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors"`

**Comment by rjimenezda** [comment]
Deployed :ship:

**Comment by andy-esch** [comment]
Awesome work :) Thank you!
