### ISSUE TITLE
"relation juanignaciosl.raster_columns does not exist" error creating an API key

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#13429]
```
curl -v -X POST -H "Content-Type: application/json" -d '{ "name": "power_shortage_app", "grants": [ {"type":"apis","apis":["sql","maps"]}, {"type": "database", "tables":[{ "schema": "juanignaciosl", "name": "power_shortage", "permissions": ["select","insert"] }] } ] }' "https://team.carto.com/u/juanignaciosl/api/v3/api_keys?api_key=XXXXXXXXXXX"
```

That returned this error:

```
{"errors":"relation \"juanignaciosl.raster_columns\" does not exist","errors_cause":null}%
```

cc @amartinj

**Comment by juanignaciosl** [comment]
Yes. I think that `raster_columns` is always at `public` schema.

**Comment by juanignaciosl** [comment]
- [ ] Fix this (check that my "`raster_columns` is always at `public` schema"  assumption is true).
- [ ] Corollary: add tests for organization users and API keys.

**Comment by javitonino** [comment]
> check that my "raster_columns is always at public schema" assumption is true

It is true for the current usage we do of PostGIS. This is unlikely to change, since we would break a lot of existing use cases.

**Comment by javitonino** [comment]
After some talks, we are going to grant publicuser to all created API keys. That should get rid of this problem without us having to list all public functions/table, which is subject to error.

**Comment by javitonino** [comment]
I ran into https://github.com/CartoDB/cartodb-postgresql/issues/321 while working on this. I tried to tweak the code a little to use the same functions ad the permission giving code does, but we have this fun little issue that's been there for years :/
