### ISSUE TITLE
Analysis modal issues (Firefox)

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#13422]
For reference, this is chrome (I guess this is the desired display):
![screenshot_20180118_171854](https://user-images.githubusercontent.com/7569673/35108447-e3ed96ca-fc73-11e7-9ded-e1abfa52f04b.png)

And this is firefox:
![screenshot_20180118_171914](https://user-images.githubusercontent.com/7569673/35108456-e9d57f12-fc73-11e7-8dbd-33d590533834.png)

Notice:
- [x] There is no "back" button at the top
- [x] The "Add analysis" button at the bottom is cut with the bottom of the screen (the screenshot is not cropped)

Do it for the fox:
![sad fox](https://www.extremetech.com/wp-content/uploads/2012/02/sad-firefox.jpg)

cc @ivanmalagon @ramiroaznar

**Comment by elenatorro** [comment]
I noticed that while fixing onpremise issues for different browsers and it is already fixed ❤️ We can close it! 

<img width="1345" alt="captura de pantalla 2018-04-06 a las 9 42 31" src="https://user-images.githubusercontent.com/3824953/38408693-ec9f0f68-397e-11e8-9da7-d030d0003371.png">

**Comment by javitonino** [comment]
So you did ignore the cute fox and fixed it for the old grumpy grandpa (ie) :sadpanda:

**Comment by ivanmalagon** [comment]
The screenshot of Elena is on Firefox and it's working on production. Is it still failing on Firefox with Linux?

**Comment by javitonino** [comment]
Works perfectly fine in FF/Linux as well :heart:

**Comment by elenatorro** [comment]
✨ 
![image](https://user-images.githubusercontent.com/3824953/38409594-485c1abe-3982-11e8-9406-a4f55bcc3d22.png)
