### ISSUE TITLE
Can not edit a geometry after creating it

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartodb#13423]
### Context

When you create a new geometry, for example a new polygon, and you save it, there is no option to edit it unless you reload the page. 

### Steps to Reproduce

1. Add a new empty map.
2. Go to the table layer that has been created.
3. Click on "Add polygon" (bottom right button)
4. Create a new polygon.
5. Save it.
6. Click on the polygon to try to edit it.

### Current Result

When clicking in the geometry, the tooltip with the button to edit it does not appear.

### Expected result

When clicking in the geometry, the tooltip with the button to edit must appear (after creating the geometry without reloading the page)

### Browser and version
All

![create_polygon](https://user-images.githubusercontent.com/3824953/35141398-1c86c998-fcfb-11e7-97b1-fe1f8f2d3da0.gif)

**Comment by alrocar** [comment]
Stale issue. Closing 👋
