### ISSUE TITLE
New Synchronization records can enter error state preventing future synchronizations

### ISSUE THREAD

**Issue by bb-acarrera** [CartoDB/cartodb#13435]
### Context
A new synchronization will enter a bad state if the synchronization job either never processes or a bug leads to the importer to not set the synchronization record state to success or failure.  Future attempts to manually sync the file via the /sync_now endpoint always return a failure to enqueue the job.

### Steps to Reproduce

1. Upload a file to S3 and make the file inaccessible (ie: returns 403 error)
   a) Please note there are other ways to make a synchronization fail.  This is simply one way to reliably reproduce the issue.
2. Send a POST request to the api/v1/synchronizations endpoint to create a new synchronization and data_imports record.  
3. Send a PUT request to the api/v1/synchronizations/:id/sync_now end point to manually sync the job created in step 2.
   -> This will always return a failure to enqueue the job. 

### Current Result
A PUT request to api/v1/synchronizations/:id/sync_now end point will always fail to enqueue the job.  

### Expected result
After a reasonable amount of time users should be able to manually kick off the synchronization job.

### Browser and version
N/A

### .carto file
N/A

### Additional info
The failure to enqueue the carto job is because the synchronization record state remains in 'created' state.  The sync_now endpoint will only enqueue jobs if the state is either in 'failure', 'success', or 'queued' per https://github.com/CartoDB/cartodb/blob/c19d6fd3bd0e26106dd8dd931e6570619dd629e7/app/models/synchronization/member.rb#L148.  It appears this may be due to the fact that the synchronization state is not set to 'queued' on create requests (https://github.com/CartoDB/cartodb/blob/c19d6fd3bd0e26106dd8dd931e6570619dd629e7/app/controllers/api/json/synchronizations_controller.rb#L41) whereas is is on a sync_now request (https://github.com/CartoDB/cartodb/blob/c19d6fd3bd0e26106dd8dd931e6570619dd629e7/app/controllers/api/json/synchronizations_controller.rb#L80)

Additionally in the above example the S3 error will lead to the synchronization state to not update to failure.  This I believe is due to the fact that update_synchronization() is only called if importer.success? is true per https://github.com/CartoDB/cartodb/blob/c19d6fd3bd0e26106dd8dd931e6570619dd629e7/app/models/data_import.rb#L806.  However it should most likely be called outside of the loop since the update_synchronization() function appears to handle failure and success states.

**Comment by gfiorav** [comment]
@ramiroaznar, our Bloomberg friends found this and seems to affect our code too. Could someone from back end take a look?

Thanks!

**Comment by AleGoiko** [comment]
deployed!
