### ISSUE TITLE
Tile render timeout is showing cartofante

### ISSUE THREAD

**Issue by urbanphes** [CartoDB/cartodb#13447]
### Context
Refer to this ticket
https://github.com/CartoDB/design/issues/1179

cc/ @ramiroaznar

**Comment by ramiroaznar** [comment]
:cartofante:

**Comment by oleurud** [comment]
We have a problem with a configuration parameter in production and the task must be assigned to infra team.

We need to make changes in the `onTileErrorStrategy` config parameter of node-windshaft: 
- this parameter must be configurable by environment
- the default value must be `false`

@skgsergio told me that we need to change on --> https://github.com/CartoDB/cartodb-platform/blob/d4816e6431bf17d0b9094de255b1573881fa3698/cookbooks/node-windshaft/templates/default/environment.js.erb#L231

**Comment by ibrahimmenem** [comment]
merged https://github.com/CartoDB/cartodb-platform/pull/3951 @oleurud

**Comment by oleurud** [comment]
Looks good to me! 

When I call a tile 
`
https://oleurud10.carto-staging.com/api/v1/map/7b822a843f9ff2ba204e6ca75e7d7552:1518097062853/1/5/8/15.png?api_key=2ffdb8579f63817c095b02c7fd30e3b60bfffb85
`
we receive a 429 error and a JSON response instead of the `cartofante` image.

**Comment by oleurud** [comment]
For example:

![image](https://user-images.githubusercontent.com/421145/35977639-f2243d68-0ce3-11e8-8a01-4aec9909ab8d.png)

**Comment by ramiroaznar** [comment]
![cartofante](http://lh6.ggpht.com/-CU0nkGNKZX8/UnTejhhfzvI/AAAAAAAAHg8/PMD_pRU9Qe8/s640/elefante.jpg)

Bye! Bye!
