### ISSUE TITLE
Relocate the Delete option in the Edit {geometry} panes

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13452]
When you're adding a new geometry we show a "Cancel" option at the bottom to cancel the operation. So far so good. 

![screen shot 2018-01-30 at 16 08 35](https://user-images.githubusercontent.com/16247628/35573599-db887e6a-05d7-11e8-8d76-b97fe05ae688.png)

The thing is, that once we add the geometry and the pane goes from "Add {geometry}" to "Edit {geometry}", we still show that "Cancel" at the bottom. And it stops making sense. 

![screen shot 2018-01-30 at 16 00 35](https://user-images.githubusercontent.com/16247628/35573701-266c274c-05d8-11e8-93bf-d8c6f714d872.png)

Also, the "Delete {geometry}" option is hidden inside a contextual menu that **only** has that option. Very little sense there as well. 

![screen shot 2018-01-30 at 16 08 24](https://user-images.githubusercontent.com/16247628/35573605-def973c4-05d7-11e8-8a53-dcb3415018e9.png)

We should do the same as we do in the Analysis tab and replace the "Cancel" with the "Delete {geometry}" option. 

![screen shot 2018-01-30 at 16 01 09](https://user-images.githubusercontent.com/16247628/35573661-08ee92ae-05d8-11e8-8995-716b9da9d44f.png)

**Comment by ramiroaznar** [comment]
I should have added you to the loop on this ticket https://github.com/CartoDB/support/issues/1233 RT frontend issues are piling, but we will fix it!

**Comment by arianaescobar** [comment]
No rush! :)

**Comment by alrocar** [comment]
Stale issue. Closing 👋
