### ISSUE TITLE
Cursor inconsistencies

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13457]
There are some inconsistencies in the cursors we display in certain parts of Builder. 

![cursor](https://user-images.githubusercontent.com/16247628/35576903-8012e7b0-05e0-11e8-9f01-41aa885e49bc.gif)

Different texts prompt the **default**, **pointer**, and **text** cursor style and it could be confusing. 

As a general rule, we should show:

- **Pointer** ![screen shot 2018-01-30 at 17 12 07](https://user-images.githubusercontent.com/16247628/35576988-ba60e2fa-05e0-11e8-9b0f-8bd90c66c396.png) for every interactive element
- **Text** ![screen shot 2018-01-30 at 17 11 52](https://user-images.githubusercontent.com/16247628/35576994-c0eeed24-05e0-11e8-9858-ddd751f01f1d.png) for editable texts (like the map title in the header)
- **Crosshair** ![screen shot 2018-01-30 at 17 11 58](https://user-images.githubusercontent.com/16247628/35577002-c5f18fd4-05e0-11e8-8098-445309862862.png) for adding geometries** 
- **Move** ![screen shot 2018-01-30 at 17 12 01](https://user-images.githubusercontent.com/16247628/35577017-cb2e7f7a-05e0-11e8-9d49-030bcc6bae07.png) for draggable elements (like when reordering layers or inputs for Pop-Ups) 
- **Not-allowed** ![download](https://user-images.githubusercontent.com/16247628/37709049-3b423370-2d09-11e8-8f15-9e229dde492d.png) for disabled elements [#13735](https://github.com/CartoDB/cartodb/issues/13735)
- **Default** ![screen shot 2018-01-30 at 17 11 55](https://user-images.githubusercontent.com/16247628/35577026-cfd1a156-05e0-11e8-9faf-49323f7c8fb2.png) for everything else (every non-interactive text or element)

In that sense, in the example...

- Only the map title should show the text style
- The tabs, inputs, icons, and links should show the pointer style
- Everything else (labels, step title, description, breadcrumb...) should show the default style

_____

**We don't have this implemented right now.

**Comment by alrocar** [comment]
Stale issue. Closing 👋
