### ISSUE TITLE
Different input widths in the Edit {geometry} panes

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13453]
### Context

Right now, in the Edit {geometry} panes all the inputs have different widths 

### Current Result

![screen shot 2018-01-30 at 16 00 09](https://user-images.githubusercontent.com/16247628/35574129-3fc129e4-05d9-11e8-9870-43812a2ecd52.png)

![screen shot 2018-01-30 at 16 17 19](https://user-images.githubusercontent.com/16247628/35574133-41737ee0-05d9-11e8-96d6-c437df56f189.png)

### Expected result

They should all have the same width.

**Comment by Jesus89** [comment]
Fixed in CartoDB/cartodb#14349
