### ISSUE TITLE
Column ordering feature in the Data view is a bit buggy

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13455]
![order](https://user-images.githubusercontent.com/16247628/35574829-25e99d7e-05db-11e8-9f65-c4f16965df94.gif)

- [ ] The arrow indicating which column is ordering the table only appears on the cartodb_id column
- [ ] The arrow always points upwards, even when ordering downwards 
- [ ]  It briefly appears in a different column when you order the table by it, but it immediately disappears and goes back to the cartodb_id one
- [ ] The "ordering arrow" doesn't show as disabled in any other column but the cartodb_id one

![screen shot 2018-01-30 at 16 33 54](https://user-images.githubusercontent.com/16247628/35574996-92418194-05db-11e8-86ba-cd4550666e9f.png)
![screen shot 2018-01-30 at 16 34 08](https://user-images.githubusercontent.com/16247628/35575000-956d6194-05db-11e8-87f3-d5521825824a.png)

**Comment by alrocar** [comment]
Stale issue. Closing 👋
