### ISSUE TITLE
Remove Tangram's vector rendering support in Builder embeds

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb#13461]
This includes:
 - [x] Remove the feature flag logic from embeds to decide to use vector: https://github.com/CartoDB/cartodb/pull/13512.
 - [x] Remove the Tangram dependency: https://github.com/CartoDB/cartodb/pull/13493.
 - [x] Use a newer cartodb.js v4 version without support for Tangram vector rendering: https://github.com/CartoDB/cartodb/pull/13484.

Depends on https://github.com/CartoDB/cartodb.js/issues/2026.

**Comment by jesusbotella** [comment]
@ramiroaznar gave the thumbs up for #13493 acceptance in staging. So I'll deploy it tomorrow!

**Comment by rochoa** [comment]
@jesusbotella, now that https://github.com/CartoDB/cartodb/pull/13512 is merged, can we close this issue?

**Comment by jesusbotella** [comment]
I was waiting for the deploy of that PR, that has been failing this morning because of infrastructure issues

**Comment by jesusbotella** [comment]
Deployed to production! 🎉

**Comment by rochoa** [comment]
Thank YOU! 😄
