### ISSUE TITLE
Remove Vector feature flag 

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/cartodb#13462]
Related to https://github.com/CartoDB/cartodb/issues/13461

We need to remove the feature flag that enables vector (tangram) rendering from the backend and from the DB. We won't support tangram anymore.

What do you think about this @javitonino ?

**Comment by javitonino** [comment]
Uhm, IIRC, tangram is enabled by default, and the feature flag disables it. Has this changed?

In any case, before we remove the feature flag, cartodb.js should not reading the `vector` field from viz.json. Unless you tell me that we should hardcode that to a fixed value.

**Comment by dv343** [comment]
> Has this changed?

Not again, I think

We are working on a cartodb.js PR to disable tangram, with that PR vector is disabled even if we request vector.

**Comment by javitonino** [comment]
Shall we wait until that PR is merged before deleting the feature flag? I mean, if we go for a full removal, we are deleting even the `vector` field from vizjson, not sure if that could be problematic if we delete it before the frontend/cartodb.js is ready.

Basically, let us know if we should do this before/after cartodb.js changes to avoid breaking anything. I think this (FF removal) should be the last step, but I could be wrong.

**Comment by ramiroaznar** [comment]
Can we close this one?

**Comment by ethervoid** [comment]
I'm checking the code base and I don't see any place where `vector_vs_raster` flag is being used so I think we can remove that flag without a problem. What do you think @javitonino ?

**Comment by javitonino** [comment]
I think so :fire:

**Comment by ethervoid** [comment]
Deleted
