### ISSUE TITLE
Suggested UI/UX improvements in Builder

### ISSUE THREAD

**Issue by alexsroth** [CartoDB/cartodb#13467]
### For Dashboards

When you select a map or a dataset from your dashboard, it can be confusing regarding where to click to enter the map/dataset vs bringing up the select menu. It is far too subtle that you have selected something, the only indication being a hairline blue line around the selection, and the menu that appears is easy to miss if you don't know where to look. Both these could benefit from a more bold styling.

![select_map_menu](https://user-images.githubusercontent.com/29546714/35632244-21739ae4-0674-11e8-9502-2274e497b145.gif)

### For Builder

Recently, the Privacy button in the top left of Builder underneath the map title has been updated to a drop down menu to select privacy level. This button used to lead to the publish options for the map. This is a fine change, but is no longer a redundancy to reach the publish options. I think it would make sense to move the publish button at the bottom of the pane to the area at the top with all other sharing options, similar to how it is in the publish options page. This would also give more room to the bottom of the UI, which has quite a bit of wasted real estate taken away from the layer views. 

![ui change](https://user-images.githubusercontent.com/29546714/35632262-2ae60e0e-0674-11e8-84bb-43ad018efb14.gif)

**Comment by ramiroaznar** [comment]
Related to 1st issue, there have been three users which were not able to delete maps:
* SB/15924867
* SB/15896599
* [GIS SE](https://gis.stackexchange.com/questions/259465/deleting-map-or-dataset-using-carto-builder)

cc @alonsogarciapablo @arianaescobar

**Comment by arianaescobar** [comment]
Thank you guys for the feedback! 

@alexsroth for future suggestions of the like, it might be better to create the tickets on our Design repository https://github.com/CartoDB/design/labels/Builder

I very much agree with your first suggestion and we are planning to revamp our Dashboard at some point in the future! So, noted! 

About the second one, we also have a completely redesigned publish flow to address many different issues regarding the publishing process (some mentioned by you). 

I will link to this ticket from those two projects so we can take your suggestions into account :) 

Keep them coming!!

**Comment by alonsogarciapablo** [comment]
cc: @piensaenpixel
