### ISSUE TITLE
Add Auth layer to Maps API

### ISSUE THREAD

**Issue by enekid** [CartoDB/cartodb#13472]
Add all the required middlewares to Maps API so it can work with the new Auth System.
Also add and fix tests.

**Comment by enekid** [comment]
Middlewares completed.
Now fixing/adding the tests and final polishing.

**Comment by enekid** [comment]
After last week pair programming with @dgaubert, we can close this issue now. We have a working version of authorization in Maps API: [project-auth-api branch](https://github.com/CartoDB/Windshaft-cartodb/tree/project-auth-api). New individual issues will be created for the new developments.

**Comment by dgaubert** [comment]
CR: https://github.com/CartoDB/Windshaft-cartodb/pull/877

**Comment by dgaubert** [comment]
Done https://github.com/CartoDB/Windshaft-cartodb/pull/877
