### ISSUE TITLE
Add Auth layer to SQL API

### ISSUE THREAD

**Issue by enekid** [CartoDB/cartodb#13473]
Add all the required middlewares to SQL API so it can work with the new Auth System.
Also add and fix tests.
Use code from the Maps API integration.

**Comment by dgaubert** [comment]
PR ready for CR: https://github.com/CartoDB/CartoDB-SQL-API/pull/450

**Comment by dgaubert** [comment]
Implemented -> https://github.com/CartoDB/CartoDB-SQL-API/pull/450
