### ISSUE TITLE
Use CartoColor in input color fields

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartodb#13481]
### Context

Related issue: https://github.com/CartoDB/cartodb/issues/9002

We are currently using a hardcoded `ramps` object in Builder to display the different available color ramps in markers color input. This can be found in this [file](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/builder/components/form-components/editors/fill/input-color/input-quantitative-ramps/ramps.js). 

However, I think it is better to get the ramps from our [CartoColor](https://github.com/CartoDB/CartoColor) library in order to be more consistent. This is the approach we have followed in this [PR](https://github.com/CartoDB/cartodb/pull/13343) for qualitative values. In my opinion, we should remove this file and use CartoColor instead.

What do you think?

### Steps to Reproduce
1. Create a new / use an existing map
2. Go to `Style`
3. Click on input color
4. Click on `Style by value`

![captura de pantalla 2018-02-01 a las 14 49 28](https://user-images.githubusercontent.com/3824953/35681895-360588aa-075f-11e8-80fb-4e2309981299.png)

### Current Result
Color ramps are being taken from a hardcoded `ramps.js` file.

### Expected result
Color ramps should be taken from CartoColor.

### Additional info

In the [PR](https://github.com/CartoDB/cartodb/pull/13343) mentioned above, we have created a helper to get ramps by name and number of required colors.

**Comment by elenatorro** [comment]
I wanted to do this as a _leapfrog_, but I realized that the colors we have in [ramps.js](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/builder/components/form-components/editors/fill/input-color/input-quantitative-ramps/ramps.js) are not the same than the ones we have in https://github.com/CartoDB/CartoColor/blob/master/cartocolor.js.

I would like to know if there could be a way to integrate these custom ramps into CartoColors or if it is something we can leave like this :) cc @makella 

Thank you!

**Comment by makella** [comment]
hey @elenatorro!

so let's not use those old ones in `ramps.js`!

take a look why in this [presentation slide](https://docs.google.com/presentation/d/1BZBMK8L-polcKhA9g_OFI5CGFli5LeW1PxNLhoUy65Q/edit#slide=id.g85937f82d_0_132)

In that green palette, look at what we were doing! bad, bad... 

I have always wanted Builder to read in the [names of the schemes](https://github.com/CartoDB/CartoColor/wiki/CARTOColor-Scheme-Names) instead listing out the color values as seen here:
https://github.com/CartoDB/cartodb/issues/9528

We have to also consider the "flipping" option that we currently have and how we would read in the inverse of the scheme when that is done (gif below).

Ideas here:
https://github.com/CartoDB/turbo-carto/issues/35

![flip-ramp](https://user-images.githubusercontent.com/1566273/35926551-a9c0c630-0be5-11e8-8988-32dc77dc7769.gif)

**Comment by elenatorro** [comment]
Thank you very much! ❤️

I will take a look ASAP to this in order to discuss how can we handle it in Builder 👍

**Comment by alrocar** [comment]
Stale issue. Closing 👋
