### ISSUE TITLE
Data library page migration

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#13497]
Migration of data library page.

To be able to see this page, change `data_library:username` entry in configuration to reflect your username.

URL: http://ivan.localhost.lan:3000/data-library
Entry point: data_library/entry.js

![image](https://user-images.githubusercontent.com/1078228/35737808-17f32ff6-082d-11e8-87cc-ee610be60c87.png)

**Comment by rjimenezda** [comment]
Blocked until we merge the auth api UI
