### ISSUE TITLE
Organization page migration :XL:

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#13499]
Migration of organization page.

URL: /u/ivan/organization
Entry point: organization/entry.js

![image](https://user-images.githubusercontent.com/1078228/35738150-4a522be0-082e-11e8-9d47-2a25a17ca7ee.png)

**Comment by danicarrion** [comment]
Acceptance comments: https://docs.google.com/document/d/1tHP3SviqNgfGv9VhfSmfYZeTMR-O2wTdZWYwGxpEehc/edit?usp=sharing
