### ISSUE TITLE
Public dashboard migration

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#13494]
Migration of public dashboard page.

This page comprehends two subpages
- Maps (1): `http://grossomodo.localhost.lan:3000/u/ivan/datasets`
- Datasets (2) `http://grossomodo.localhost.lan:3000/u/ivan/datasets`

This page can be seen by an anonymous user.

(1) Maps

![image](https://user-images.githubusercontent.com/1078228/35736079-16d7441e-0827-11e8-80e4-8a6b3c5dc4c5.png)

(2) Datasets

![image](https://user-images.githubusercontent.com/1078228/35736108-22f3bb88-0827-11e8-8c03-55e330cbf0be.png)

**Comment by rjimenezda** [comment]
Wait until Auth API is merged

**Comment by jesusbotella** [comment]
We did acceptance in staging and worked successfully :)

**Comment by rjimenezda** [comment]
For a simple user:

- Editor maps no longer shown as favmaps, as long as builder and FF so 👍 
- If you're logged in, it doesn't show the top right thingie, and thus, you can't like maps. This is fixed on /me, so we probably broke something, so 👎 

For an org:
- Same as above, both 👍 and 👎

**Comment by danicarrion** [comment]
Please my acceptance comments on https://github.com/CartoDB/cartodb/issues/13632
