### ISSUE TITLE
Adjust titles in mobile view for embed maps

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#13498]
### Context

[[PROJECT] Mobile Titles and spacing in widgets](https://github.com/CartoDB/cartodb-management/issues/5098).

* [x] ~~Add Title view in mobile resolution https://github.com/CartoDB/cartodb/pull/13517~~
* [x] Make legends collapsable https://github.com/CartoDB/cartodb/pull/13531

In further iterations we should aim for differentiated public pages and embeds for Builder public maps

**Comment by alonsogarciapablo** [comment]
I deployed this to staging and I still see the map name and description inside the legends box (with a margin that doesn't seem right) 😞 

<img width="1280" alt="screen shot 2018-02-16 at 17 37 02" src="https://user-images.githubusercontent.com/390398/36320906-36ea5788-1348-11e8-9449-77f0c62bf95d.png">

**Comment by alonsogarciapablo** [comment]
cc: @jesusbotella ☝️

**Comment by jesusbotella** [comment]
Which one is the staging that you deployed this issue? It shouldn't happen ☹️
As of today, @matallo will be on the RT shift so I think he can handle it :)

**Comment by alonsogarciapablo** [comment]
I used a dynamic dedicated staging which has already expired 😞 .

**Comment by matallo** [comment]
don't hassle, I'm redeploying 🤗

**Comment by matallo** [comment]
im production! 🚀

**Comment by alonsogarciapablo** [comment]
😌  Thanks guys!

**Comment by piensaenpixel** [comment]
Thanks mata!
