### ISSUE TITLE
Mobile apps migration

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#13495]
Migration of mobile apps page

URL: http://cdb.localhost.lan:3000/your_apps/mobile
Entry point: mobile_apps/entry.js

⚠️  Something is needed to be able to render this page. According to backend code, it's enabled if...

```
  def mobile_sdk_enabled?
    mobile_max_open_users > 0 || mobile_max_private_users > 0
  end
```

![image](https://user-images.githubusercontent.com/1078228/35737546-3577e536-082c-11e8-9866-ecc3224b4efe.png)

**Comment by rubenmoya** [comment]
Blocked until https://github.com/CartoDB/cartodb/pull/13469 is merged
