### ISSUE TITLE
Signup / confirmation pages migration

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#13496]
Migration of signup and confirmation pages.

This pages are enabled only at organization level.

URL: http://team.carto.com/signup
Entry points:
- signup/entry.js
- confirmation/entry.js

Note: confirmation page it's the next page after signing up, where the user can fill up some information.

![image](https://user-images.githubusercontent.com/1078228/35737740-daab589e-082c-11e8-9389-13a8d0b9ad77.png)

**Comment by rubenmoya** [comment]
What about https://team.carto.com/login?

**Comment by rubenmoya** [comment]
In production! 🚀
