### ISSUE TITLE
Recover the "SQL" and "READ" tags

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13507]
At some point along the way, we lost the "SQL" and "READ" tags that appeared on both the Layers List and the Layers header besides the dataset node. 

![screen shot 2018-02-05 at 17 34 31](https://user-images.githubusercontent.com/16247628/35816382-da77d4e0-0a9a-11e8-93a4-471cc9560836.png)

![screen shot 2018-02-05 at 17 12 39](https://user-images.githubusercontent.com/16247628/35816319-b080b5c6-0a9a-11e8-8e50-fd4fbc60a2f5.png)

**SQL:** Indicates that a SQL query has been applied to that dataset, either by the advanced SQL editor in the DATA tab or by an analysis. 
**READ:** Indicates that it's a read-only dataset, so its data can't be transformed. Which occurs when: 

- A layer has an analysis applied
- The data comes from the Data Library
- The data comes from a Shared dataset with read-only permission. 

Just to clarify, we already had this implemented and for some reason, its no longer appearing. It's actually still present in some parts of the tool, like in the "Shared with you" tab of the Add a new layer modal: 

![screen shot 2018-02-05 at 17 47 17](https://user-images.githubusercontent.com/16247628/35817062-a0faeb92-0a9c-11e8-8918-d36c1428aa18.png)

cc @alonsogarciapablo @ramiroaznar

**Comment by ramiroaznar** [comment]
Hey @arianaescobar I am seeing the `SQL` tag when applying a query or importing a .carto file:

![image](https://user-images.githubusercontent.com/5215798/35817341-6315515e-0a9d-11e8-9945-f1fa35015bdc.png)

Regarding the other tag, I have some concerns:

* `READ` should only be shown when the data is synced and/or it is a read-only dataset shared within an organization.
* What happens when you apply a query and then add an analysis? I do not think that we should add the `READ` label in this case.
* You can change a dataset from the Data Library after deactivating the sync option.

**Comment by arianaescobar** [comment]
Uuuuh I love this synergy!
 
> I am seeing the SQL tag when applying a query or importing a .carto file
- Why are we showing the `SQL` tag when importing a .carto file? Did the file had a query applied?

> - READ should only be shown when the data is synced and/or it is a read-only dataset shared within an organization.
> - What happens when you apply a query and then add an analysis? I do not think that we should add the READ label in this case.
- Are you saying that we shouldn't show `READ` after an analysis has been applied? (The data does become read-only, tho...) I might have misunderstood. 

> - You can change a dataset from the Data Library after deactivating the sync option.
- Nice to know that! So in that case, if you change it to **never**, the `READ` tag disappears.

**Comment by ramiroaznar** [comment]
> Why are we showing the SQL tag when importing a .carto file? Did the file had a query applied?
I think it is something related to changing the postgres schema. Maybe @javitonino can give a better answer.

> Are you saying that we shouldn't show READ after an analysis has been applied? (The data does become read-only, tho...) I might have misunderstood.
Yes, I think we shouldn't because you can drag out the original node and work with the SQL panel. Something I do very often.

**Comment by arianaescobar** [comment]
> Yes, I think we shouldn't because you can drag out the original node and work with the SQL panel. Something I do very often.

But that's a different workflow... one that we should make more explicit, btw. 

If you drag the node out and it can be edited, then it definitely should have the `READ` tag. But the original layer with the analyses applied would be read-only and because of that, it requires said tag. Right?

**Comment by ramiroaznar** [comment]
> But that's a different workflow... one that we should make more explicit, btw.

Totally agree. Dragging out analysis is one of the coolest (and very useful) feature in BUILDER. Regarding the issue in hand, I suppose you are right. After dragging the original layer source out, the label can be removed (but keep it in the analysis node).

**Comment by ramiroaznar** [comment]
I will try to replicate it!

**Comment by arianaescobar** [comment]
Thank you guys :)
