### ISSUE TITLE
Keep the chosen view when switching between tabs

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13508]
Right now, if I change to the "Data" view (table) and switch between tabs inside a layer, my view selection will be reset back to the Map view. This shouldn't happen. User's view selection should be kept during UI navigation.  

![views](https://user-images.githubusercontent.com/16247628/35817337-60d83a50-0a9d-11e8-98f8-84fb21c173c7.gif)

cc @alonsogarciapablo @ramiroaznar

**Comment by ramiroaznar** [comment]
Good catch!

**Comment by alrocar** [comment]
Stale issue. Closing 👋
