### ISSUE TITLE
can't remove map description (update to blank description)

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#13514]
### Context

when trying to remove a description (update to a blank input), the UI responds successfully but the change won't effectively happen

### Steps to Reproduce

1. create an empty map from dashboard
1. update description from "Options menu > Edit metadata..." with "this is a description"
1. publish map and check embed view
1. update description again from "Options menu > Edit metadata..." and remove content in *Description* field
1. publish map and check embed view

### Current Result

Embed map has the description "this is a description"

### Expected result

Embed map should not have a description

**Comment by alrocar** [comment]
Stale issue. Closing 👋
