### ISSUE TITLE
When hovering over the sync icon only show its own tooltip 

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13523]
Right now, if you have a synced layer and you hover over the sync icon in the Layers List, two tooltips appear, one from the dataset now and one from the sync icon. Only the sync tooltip should appear when hovering the sync icon. 

![screen shot 2018-02-05 at 17 38 54](https://user-images.githubusercontent.com/16247628/35968719-f458cba4-0cc4-11e8-8f90-934a4cdb81e1.png)

Also, let's change its copy and add "Synced" as a prefix. So, in the case above it would say "Synced a few seconds ago" 

cc @ramiroaznar

**Comment by ramiroaznar** [comment]
Should this issue be fixed by the onboarding squad?

**Comment by arianaescobar** [comment]
Bravo is mostly working on the mobile embed right now, but I'm not sure. 

cc @matallo
