### ISSUE TITLE
Wrong margins in header

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13522]
We have a few wrong margins in our headers right now, take a look: 

![headers](https://user-images.githubusercontent.com/16247628/35968412-066b1226-0cc4-11e8-86fc-d3a1e8d59144.png)

The first two are our mockups and the last two are screenshots from production. 

![headersh](https://user-images.githubusercontent.com/16247628/35969379-ec741d88-0cc6-11e8-8523-6e977f6d3423.png)

The left one is the mockup and the right one is production. 

cc @ramiroaznar maybe RT can tackle it at some point

**Comment by alrocar** [comment]
Stale issue. Closing 👋
