### ISSUE TITLE
Map's description has not character limit

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartodb#13539]
### Context

When you are editing map's metadata, the description input accepts any text length. However, the user will not see the full description anywhere in the application, it is always cropped. Therefore, we should add a maximum text length.

Related Issue: https://github.com/CartoDB/cartodb/issues/13514

![captura de pantalla 2018-02-12 a las 12 33 43](https://user-images.githubusercontent.com/3824953/36095103-12469748-0ff1-11e8-9f6f-a9a8ce7475d9.png)

![captura de pantalla 2018-02-12 a las 12 34 05](https://user-images.githubusercontent.com/3824953/36095102-121b403e-0ff1-11e8-88a8-c1120ea4efd8.png)

### Steps to Reproduce

1. Create an empty map from dashboard
2. Update description from "Options menu > Edit metadata..." with a very long text.
3. Publish map and check embed view => The description is shown cropped and there is no option to see the full text.

### Expected result

There should be a maximum text length for map descriptions.

### Additional info

If we add a maximum length, we should discuss if the description content should be completely visible in the different views where it appears, or if we should keep cropping it.

**Comment by alrocar** [comment]
Stale issue. Closing 👋
