### ISSUE TITLE
database_timeout is applied at organization level

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#13533]
Each CARTO user has two timeout limits, one for logged in operations (with api key) and another for public usage (without api key). Right now, the former is applied to the database role, and the latter to the database itself.

In organization, this causes that each time the public limit is changed for a user, it is actually applied to all users in an organization. See https://github.com/CartoDB/cartodb/blob/master/app/models/user/db_service.rb#L640-L644

We should strive to make this consistent. Some options:
- Move the public timeout to the organization model, to better reflect what is currently happening.
- Apply the public limit to each public user role in the organization (`user.database_public_role`). For single users, keep applying it to the database (since `publicuser` is shared). This would make the limit per-user.

The real question to make here is if we want the users to be the same for all users in the organization or we want the possibility to make then different.

**Comment by danicarrion** [comment]
IMHO it makes sense to make them different. It's not unusual for an organization to have one "production" account and a few other for testing, particularly if they're developing apps with CARTO.

**Comment by gonzaloriestra** [comment]
Closing in favor of https://app.clubhouse.io/cartoteam/story/83541/database-timeout-is-applied-at-organization-level
