### ISSUE TITLE
Geocoding by zip limitations

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#13557]
1. Create a map importing [single_zip.csv.zip](https://github.com/CartoDB/cartodb/files/1730804/single_zip.csv.zip).
2. Try geocoding by zip:

![captura de pantalla 2018-02-16 a las 10 46 47](https://user-images.githubusercontent.com/932968/36301887-b6b07340-1306-11e8-989b-6ed57f97123a.png)

Workaround: change `zip` column type to number:

![captura de pantalla 2018-02-16 a las 10 47 59](https://user-images.githubusercontent.com/932968/36301932-e2421f68-1306-11e8-9085-b7d414c881f8.png)

I think that there are two different issues there:
1.- Zip geocoder should support number columns.
2.- If no valid column is provided, instead of showing the "No values" error, you still should be able to enter the country manually.

cc @ramiroaznar @oriolbx

**Comment by ramiroaznar** [comment]
Not sure about 1. But 2 is definitely a bug.

**Comment by andrewbt** [comment]
not sure about 1 either @ramiroaznar as they are usually "string ID's". But there are maybe some cases where allowing numbers would make sense and provide a faster UX. Hmmm...

**Comment by ramiroaznar** [comment]
This is fixed.
