### ISSUE TITLE
Disable API Keys when user is locked

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#13560]
Right now, when a user is locked we disable the api key via regeneration. We should do the same for regular keys.

Proposal:
- When the user switches from active to locked, remove api keys from redis
- When the user switches from locked to active, add the api keys back to redis

That should lock the keys at API level, while avoiding regenerating them.

**Comment by amartinj** [comment]
But that would make him lose all his tokens. What if we remove them from redis and authenticate Auth API with an active user?

**Comment by javitonino** [comment]
I think there is a misunderstanding here:
> We should do the same for regular keys
I meant, "disable", not regenerate.

> But that would make him lose all his tokens
No, they will still be in the metadata database, so we can reset them if/when reactivating the user.

**Comment by amartinj** [comment]
In that case, seems OK to me :)

**Comment by javitonino** [comment]
Also note, that we should consider doing the same for the master key (which is regenerated on user lock right now).

We must also consider when `engine_enabled` switches to false (in that case, maybe key deletion is OK).

**Comment by amartinj** [comment]
I would just simply add the condition where the owner of the api_key is enabled

**Comment by alrocar** [comment]
I understand this is done in central right?
