### ISSUE TITLE
Recover Data tab's onboarding tour

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13578]
### Context

We used to have an onboarding tour in the Data tab but after some of the recent changes, we lost it. We should recover it. 

![data](https://user-images.githubusercontent.com/16247628/36373849-b7188326-1569-11e8-8e06-5f49b8b69989.png)

More context from @ivanmalagon: 

> first, every tab in layer section has the same key for the onboarding
> that’s a result from this ticket
> https://github.com/CartoDB/cartodb/issues/11586
> (one year ago)
> then, the latest changes on tours did that once a tour has been seen, it’s discarded from the time being
> https://github.com/CartoDB/cartodb/issues/13003
> as all the tours on layer sections share the same key, once you see one, you see all
> that’s why you don’t see never the data onboarding
> we should revert the unique key for every tour on layer section

**Comment by alonsogarciapablo** [comment]
@ramiroaznar adding this to the RT project!

**Comment by ramiroaznar** [comment]
We forgot to address this when solving this https://github.com/CartoDB/cartodb/issues/13415

**Comment by rubenmoya** [comment]
It should be fixed too

**Comment by ramiroaznar** [comment]
@arianaescobar can you test in Production if this is fixed?

**Comment by arianaescobar** [comment]
sure, I'll take a look

**Comment by rubenmoya** [comment]
I'm not sure if it's going to work for old users, it should, since the name we use to store those tours are different now, but I can't assure it 100%

**Comment by ramiroaznar** [comment]
Tested in a new user:

![image](https://user-images.githubusercontent.com/5215798/37345781-f712d66e-26cd-11e8-9e9e-8e86a872c3b9.png)

**Comment by arianaescobar** [comment]
Hey guys, looks like this splash screen is appearing on old users (https://github.com/CartoDB/design/issues/1276#issuecomment-372769407). It shouldn't have. This should only appear during the onboarding process for new accounts.

**Comment by ramiroaznar** [comment]
[This](https://github.com/CartoDB/cartodb/issues/13415#issuecomment-371746086) was what we implemented.

**Comment by arianaescobar** [comment]
Right. 
`Layer content onboarding: ONCE PER USER`

We need to assume that old accounts already saw the layer content onboarding. What's the point in showing an onboarding splash screen to already on-boarded users?

**Comment by rubenmoya** [comment]
The keys we check for this have changed, before it was a generic `layer-onboarding` one, while now they are divided for each tab `layer-data-onboarding`, `layer-style-onboarding`, etc.

When we check those keys in old users they don't exist yet, so we show the onboarding.

I could've checked for `old_key OR new_key`, but I didn't think it was going to be such a problem to show it again to old users...

**Comment by ramiroaznar** [comment]
> I could've checked for old_key OR new_key, but I didn't think it was going to be such a problem to show it again to old users...

Agree.

**Comment by arianaescobar** [comment]
Thanks for the explanation @rubenmoya. 

We should discuss those assumptions before implementing them, though. Onboarding screens are usually quite annoying. Users just want to get the job done and get out. If you take a look at Fullstory you can see how users rarely stop to read the onboarding and try to close it as fast as possible. And for old users, that already know how things work (we can only hope!), is an unnecessary burden.
