### ISSUE TITLE
MIN aggregation failing in formula widgets

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb#13579]
Formula widget applied to numeric field, using MIN aggregation, will reply with NO DATA AVAILABLE if the min value is exactly zero

**Comment by ramiroaznar** [comment]
Thanks for the heads up!

![image](https://user-images.githubusercontent.com/5215798/36416928-cb493374-162a-11e8-82c6-e18731e46ee0.png)

**Comment by rubenmoya** [comment]
Fixed in https://github.com/CartoDB/cartodb/pull/13686

In production! 🚀

**Comment by ramiroaznar** [comment]
:boom:
