### ISSUE TITLE
Widgets empty message not visible when reloading the page

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartodb#13583]
### Context

If the page is reloaded in the url `/builder/map_id/widgets` when there is no widgets, the sidebar view is empty and it does not show neither the message nor the button to create a new widget.

![widgets_empty](https://user-images.githubusercontent.com/3824953/36380801-dc390800-1583-11e8-88a5-5ab83ef91353.gif)

### Steps to Reproduce

1. Create a new map
2. Go to edit the map
3. Click on "Widgets"
4. Reload the page

### Current Result

The sidebar view is empty and it does not show neither the message nor the button to create a new widget.

### Expected result

It should show both the message and the button properly.

**Comment by alonsogarciapablo** [comment]
This is working for me in production. Could you please try again in production @elenatorro? Thanks!

**Comment by alonsogarciapablo** [comment]
@elenatorro please reopen this if you are able to replicate in production. Thanks!

**Comment by elenatorro** [comment]
I tried this one again and I could not replicate it :) Thank you very much for checking it!!
