### ISSUE TITLE
Back button does not work on first click when creating a new widget

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartodb#13584]
### Context

After creating a new widget, clicking on the `<- Back` button does not work the firs time, it has to be clicked another time to work.

![back_button](https://user-images.githubusercontent.com/3824953/36381066-b474eaea-1584-11e8-897a-e46bfa5c8f27.gif)

### Steps to Reproduce

1. Create a new map / open an existing map
2. Go to edit the map
3. Add a new widget
4. Click on the back button.

### Current Result
The first time the back button is clicked, it does not work after creating a new widget.

### Expected result
It has to be possible to go back by clicking once in the back button after creating a new widget.

**Comment by alonsogarciapablo** [comment]
I tried to replicate but it's working in production. @elenatorro please reopen this if you're able to replicate in production.

**Comment by elenatorro** [comment]
It happened to me in production again :( but I am not sure if it is due the assets version

![back_button_production](https://user-images.githubusercontent.com/3824953/36385112-e571c7d2-1591-11e8-8383-d654d574ad6f.gif)
