### ISSUE TITLE
Center map on layer with 1 point and custom basemap goes to 32 zoom level

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#13599]
If i do 'center map on layer' in the points layer goes to 32 zoom level

![image](https://user-images.githubusercontent.com/1214201/36435363-c07587cc-1661-11e8-89d3-062e886539b3.png)

.carto -->  [Untitled map 10 (on 2018-02-20 at 16.19.17).carto.zip](https://github.com/CartoDB/cartodb/files/1740876/Untitled.map.10.on.2018-02-20.at.16.19.17.carto.zip)

**Comment by piensaenpixel** [comment]
More information: it happens when the basemap is a custom color
<3 you

**Comment by ramiroaznar** [comment]
So...

### STR

1. Create a map with just one point
2. Change the basemap to custom color
3. Center lo layer

### Current result

* Zoom goes up to 32.

### Expected result

* Zoom goes to 18 (as with regular basemaps).

**Comment by piensaenpixel** [comment]
Yeah. Thanks ramiramen

**Comment by erodespons** [comment]
Something similar happens if you make a search. If you use the search box and CARTO does the Leaflet fly-to, you'll be able to zoop up to 20.
![captura de pantalla 2018-03-22 a las 17 57 56](https://user-images.githubusercontent.com/7283363/37785512-a4998778-2dfa-11e8-84ec-60cd0c38d627.png)

**Comment by alrocar** [comment]
Stale issue. Closing 👋
