### ISSUE TITLE
BUG: Error decoding nil

### ISSUE THREAD

**Issue by amartinj** [CartoDB/cartodb#13609]
https://rollbar.com/carto/CartoDB/items/25894/occurrences/38355521895/

**Comment by javitonino** [comment]
This might be related with an issue we found, so I'll write it in this ticket.

We need to be able to handle the case where the user is logged in via cookies in `any_api_authorization_required`. In that case, `current_user` already exists, so no authentication strategy is invoked, so we cannot rely on that.

A quick fix might be https://github.com/CartoDB/cartodb/commit/9286ff75b1b44050cfd2ee41af2eb6901a9d77ef but it needs further review.
