### ISSUE TITLE
Error showing buttons in IE11

### ISSUE THREAD

**Issue by dppascual** [CartoDB/cartodb#13606]
### Context

When opening a dataset view using Internet Explorer 11, the 3 dot icons of the column options don't appear on the correct position and the arrow which indicates the order of the column doesn't appear.

![image](https://user-images.githubusercontent.com/10468373/36484109-7cd8c88c-1718-11e8-8095-86ece8bec60e.png)

### Steps to Reproduce

1. Go to dataset dashboard
2. Open any dataset

### Browser and version
IE11

### Additional info
 It is happening both cloud and on-premise.

**Comment by ramiroaznar** [comment]
Good catch!

**Comment by jvillarf** [comment]
@ramiroaznar we would like to include this fix in the **Onpremise 2.2.0** release. Would it be possible to prioritize it a bit? Thanks a lot.

**Comment by ramiroaznar** [comment]
Let's move this to the TODO column then.

**Comment by dppascual** [comment]
Hiroo Imaki was the client who reported that bug. It is a partner.

**Comment by Jesus89** [comment]
Closed in https://github.com/CartoDB/cartodb/pull/13634

**Comment by ramiroaznar** [comment]
cc @jvillarf

**Comment by jvillarf** [comment]
@ramiroaznar @Jesus89 thanks a lot! I will generate the bran new onpremises package now :+1:

**Comment by ramiroaznar** [comment]
@jvillarf maybe you can wait until this one is also fixed https://github.com/CartoDB/cartodb/issues/13635 ?

**Comment by Jesus89** [comment]
In production!

**Comment by jvillarf** [comment]
Hey @ramiroaznar , i've been talking with @ivanmalagon and he has recommended us to hold on until the following fixes are solved:
- https://github.com/CartoDB/cartodb/issues/13603
- https://github.com/CartoDB/cartodb/issues/13635

So yes, we will wait for them. Thanks
