### ISSUE TITLE
Unable to open Meridian Maps

### ISSUE THREAD

**Issue by surajprakash16** [CartoDB/cartodb#13629]
### Context
I am trying to open my Meridian maps and it is not opening. Only grey screen is coming up.

### Steps to Reproduce

1. Go to meridian
2. Click on the old Maps 
3. It will show grey screen

### Current Result
*Please describe here below the current result you got*

### Expected result
map should open

### Browser and version
Chrome, version 64.0.3282.167

### .carto file
*Don't forget to rename .carto file to .zip file to be able to upload to github*

### Additional info
*Please add any information of interest here below*

**Comment by alissarose** [comment]
@surajprakash16 - this is not the repo to report issues with Meridian. Please use github.com/cartodb/bcg-testing to report any issues related to meridian
