### ISSUE TITLE
Histogram widgets are not being resized in embed maps

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartodb#13624]
### Context

When you resize the viewport, histogram widgets do not resize **sometimes** in embed maps.

### Steps to Reproduce

1. Create a new map / open a map that already exists.
2. Add a histogram widget
3. Publish the map and open the embed in a large viewport.
3. Resize the window to a smaller viewport.

### Current Result

Histogram widget is not being resized sometimes.

* It is resized [here](https://team.carto.com/u/urbanphes/builder/32ec6347-91e5-4690-9fb5-8302f29c30d8/embed?state=%7B%22map%22%3A%7B%22ne%22%3A%5B39.72567292003209%2C-105.07178306579591%5D%2C%22sw%22%3A%5B39.79040176804045%2C-104.95659828186037%5D%2C%22center%22%3A%5B39.758044948511525%2C-105.01419067382814%5D%2C%22zoom%22%3A14%7D%2C%22widgets%22%3A%7B%227a5134dc-5574-4496-b0df-65db5f006818%22%3A%7B%22normalized%22%3Atrue%7D%2C%220fb76444-168d-411d-ba14-687b7a377a4a%22%3A%7B%22normalized%22%3Atrue%7D%2C%2213f5adbd-a32e-4a82-aa09-0d95d7bdce83%22%3A%7B%22acceptedCategories%22%3A%5B%22SINGLE+FAMILY%22%5D%7D%2C%2226945f5c-c97b-416a-94cb-3575691599ed%22%3A%7B%22normalized%22%3Atrue%7D%7D%7D)
* It is not resized [here](https://team.carto.com/u/elena-carto/builder/988a2ab4-e96d-483e-b602-b909fc557da8/embed?state=%7B%22map%22%3A%7B%22ne%22%3A%5B13.410994034321702%2C-38.14453125000001%5D%2C%22sw%22%3A%5B53.173119202640635%2C24.697265625000004%5D%2C%22center%22%3A%5B35.71083783530009%2C-6.723632812500001%5D%2C%22zoom%22%3A4%7D%2C%22widgets%22%3A%7B%22d2330434-7dd4-4adc-8789-9e6116c2b89c%22%3A%7B%22normalized%22%3Atrue%7D%7D%7D)

### Expected result
Histogram widgets must always be resized when changing the viewport size.

### Browser and version
All

**Comment by ramiroaznar** [comment]
Should the RT take care of this one?
