### ISSUE TITLE
Public table migration

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#13632]
Migration of public table page

URL: https://team.carto.com/u/hacheka/tables/austin_fire_stations/public
Entry point: /cartodb/public_table.js'

You can access this page by clicking on a dataset in your public datasets page.

![image](https://user-images.githubusercontent.com/1078228/36794408-8769cc14-1ca0-11e8-880c-ef307f4ac3a6.png)

**Comment by danicarrion** [comment]
Acceptance comments: https://docs.google.com/document/d/1Q7MeE0kQhVp-JhLXl9Ukp9cMi7BuHJ-j49Ge9xOBDrg/edit?usp=sharing

**Comment by danicarrion** [comment]
I didn't test with Google Maps. Is that something you were expecting me to do?
