### ISSUE TITLE
Several glitches in IE11

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#13635]
### Context

After the last changes / blunders in Builder, I've checked it IE11 and found a couple of issues.

#### Broken bubble legends

No explanation. Just create a bubble legend.

![image](https://user-images.githubusercontent.com/1078228/36835136-867f62ce-1d35-11e8-9239-c6c4e078d490.png)

#### Ghost attribution toolbar

This was happening in some other browsers and it was fixed, but it's still on IE. In the middle breakpoint, the space reserved for the bottom bar is kept but nothing shows up.

STR
- Check that the map has `show toolbar` checked.
- Publish the map.
- Go to the embed page.
- Resize the screen. The blank footer will show up.

Note: this only happens when resizing. If you refresh the page on that particular breakpoint, the footer is filled up.

![screen shot 2018-02-28 at 15 37 03](https://user-images.githubusercontent.com/1078228/36835166-9eef600c-1d35-11e8-99ae-3458f5cb4b22.png)

**Comment by ramiroaznar** [comment]
cc @ztephm @makella

**Comment by Jesus89** [comment]
This is a very weird bug. In the same windows machine and using the **same version** of assets, servers, etc, it fails when is loaded from a production or a staging server and works when is loaded from my local build. So I can not reproduce the bug in my local environment.

![ie11-bubble-legends](https://user-images.githubusercontent.com/2227572/36846934-e5231da8-1d5c-11e8-9f73-d0626f7d5aed.png)

**Comment by rjimenezda** [comment]
Minification is probably mangling something, I've encountered issues like this before with

Actually, the bubble legend did break a few months ago on IE, but it should've been fixed. Let me look it up

**Comment by rjimenezda** [comment]
@Jesus89 maybe this helps?

https://github.com/CartoDB/cartodb/pull/12602

**Comment by Jesus89** [comment]
Thanks @rjimenezda. I have replicated the issue adding the uglify in the local build (`npm run build`).

So let's check the uglify again! :muscle:

**Comment by Jesus89** [comment]
This is the last PR to fix legends in IE11: https://github.com/CartoDB/cartodb.js/pull/2019

**Comment by elenatorro** [comment]
🎉 well done!!! 🎉

**Comment by jesusbotella** [comment]
I have tested all the cases mentioned in https://github.com/CartoDB/cartodb.js/pull/2064 and all of them are fixed!

**Comment by Jesus89** [comment]
Closed in https://github.com/CartoDB/cartodb/pull/13640

**Comment by ramiroaznar** [comment]
:boom:
