### ISSUE TITLE
Wrong left border in color/size inputs in IE

### ISSUE THREAD

**Issue by rubenmoya** [CartoDB/cartodb#13648]
### Context
Wrong left border when hovering a color input

### Steps to Reproduce
1. Visit the `/style` tab in a layer
2. Hover in a color input

### Current Result
![screen shot 2018-03-05 at 10 41 06](https://user-images.githubusercontent.com/905225/36968066-bf635a44-2061-11e8-98e7-2288b1e0f8c3.png)

### Expected result
![screen shot 2018-03-05 at 10 41 24](https://user-images.githubusercontent.com/905225/36968076-c6e72886-2061-11e8-9be1-4a1bf959d04f.png)

### Browser and version
Internet Explorer `11.0.9600.18860`

**Comment by ramiroaznar** [comment]
Fixed in https://github.com/CartoDB/onpremises/issues/516
