### ISSUE TITLE
Empty legends box in desktop viewport after hiding them

### ISSUE THREAD

**Issue by rubenmoya** [CartoDB/cartodb#13649]
### Context
When hiding legends in tablet viewport and resizing the screen into desktop viewport, there is an empty box left in there

### Steps to Reproduce
1. Visit an embed map with legends
2. Resize the window into tablet viewport
3. Hide the legends by clicking on the ![screen shot 2018-03-05 at 11 08 12](https://user-images.githubusercontent.com/905225/36969361-8bc6db44-2065-11e8-9bd1-a73811d73cfd.png) icon
4. Resize the window again into desktop viewport

### Current Result
![screen shot 2018-03-05 at 11 09 18](https://user-images.githubusercontent.com/905225/36969406-ad61e6f4-2065-11e8-96f5-92656b74dad0.png)

### Expected result
![screen shot 2018-03-05 at 11 09 38](https://user-images.githubusercontent.com/905225/36969419-b8bd363e-2065-11e8-9f80-22a691e93011.png)

**Comment by ramiroaznar** [comment]
Closing in favor of https://github.com/CartoDB/cartodb/issues/13765
