### ISSUE TITLE
Polygon and Marker Stroke by Value (size and color) in Builder UI

### ISSUE THREAD

**Issue by makella** [CartoDB/cartodb#13650]
### Context
I would like to be able to color and/or size the stroke of polygons and markers based on an attribute (both numbers and categories).

For a polygon stroke example, if you are doing coastal [water lines](https://team.carto.com/u/mamataakella/builder/55cf1208-d01d-4cb9-a8d0-4b1700bb81fb/embed)  created in Builder from the Area of Influence analysis one of the styling capabilities that I would like to have is the ability to vary the line width of the polygons depending on an attribute. Similarly, I may want to do the same with color. 

You can imagine people wanting to do the same with marker outlines.

This is possible with TurboCarto, and this request is to see if we can have these capabilities inside of our forms. The logic would be the same that we have for line features by value.

#### Varying polygon line-width
![screen shot 2018-03-05 at 7 59 24 am](https://user-images.githubusercontent.com/1566273/36981806-55cfc16e-204b-11e8-864d-2b044620b36b.png)

```
#layer {
  polygon-fill: #826DBA;
  polygon-opacity: 0;
}
#layer::outline {
  line-width: ramp([data_range],0.5,3,equal);
  line-color: #383838;
  line-opacity: 0.5;
}
```
#### Varying polygon stroke color
![screen shot 2018-03-05 at 8 29 56 am](https://user-images.githubusercontent.com/1566273/36983369-6c1ad658-204f-11e8-9c16-3fae0041c77e.png)

```
#layer {
  polygon-fill: #826DBA;
  polygon-opacity: 0;
}
#layer::outline {
  line-width: 1;
  line-color: ramp([data_range],cartocolor(SunsetDark),equal);
  line-opacity: 1;
}
```

Thanks in advance for consideration!

cc @ramiroaznar

**Comment by ramiroaznar** [comment]
I think this is a (very cool) enhancement. But because @CartoDB/design is already working on revamping the STYLE BY VALUE interface, I will leave this one to them and @alonsogarciapablo.

**Comment by makella** [comment]
Ok! thanks! Will be super useful and hopefully not too much additional work (since already supported by TurboCARTO and same behavior as lines by value!)
