### ISSUE TITLE
Tooling to add arbitrary datasets to Data Library

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#13666]
Rake for adding any dataset to a user Data Library. Example usage:

`... rake load_dataset_into_data_library[target_username,source_username,source_dataset,api_key]`.

Things to keep in mind:

-  ~Ideally, a user shouldn't see the URL of the dataset that can be imported, especially to avoid API keys leaking (although Auth API makes this less of a problem).~ The user can see the SQL API request, so a custom API Key must be used.
- If the Data Library gets refreshed, the dataset must stay. Currently, [it stops because of a FK](https://github.com/CartoDB/cartodb/blob/384ea1ce8784954ce55cf60a12e18d73657e482a/app/services/visualization/common_data_service.rb#L160). Deletion will be tackled on #13667.

**Comment by danicarrion** [comment]
Don't you need API keys for both the source and target users?
