### ISSUE TITLE
GeoJSON word overflows when importing a GeoJSON dataset

### ISSUE THREAD

**Issue by jesusbotella** [CartoDB/cartodb#13663]
### Context
Import a GEOJSON format dataset in CARTO

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Go to the dataset page
2. Click on the `New Dataset` button
3. Drag and drop any GeoJSON dataset into the browser window

### Current Result
![screen shot 2018-03-08 at 09 56 52](https://user-images.githubusercontent.com/4319728/37143159-920c89ca-22ba-11e8-9743-97aad1130aef.png)

### Expected result
The word fits in the square

### Browser and version
Google Chrome
Version 64.0.3282.186 (Official Build) (64-bit)

**Comment by Jesus89** [comment]
It's not perfect, but I think it is already fixed:

![selection_196](https://user-images.githubusercontent.com/2227572/42330478-9156eb30-8073-11e8-8123-f438e50c49cf.png)

**Comment by Jesus89** [comment]
Ping @ramiroaznar. Can we close this one?
