### ISSUE TITLE
"Add a new analysis" title is misplaced in IE11

### ISSUE THREAD

**Issue by jesusbotella** [CartoDB/cartodb#13671]
### Context
I was adding a new analysis to a layer

### Steps to Reproduce
1. Go to a map in Builder
2. Click on any layer
3. Try to add an analysis

### Current Result
![screen shot 2018-03-08 at 16 16 27](https://user-images.githubusercontent.com/4319728/37162643-105da418-22f6-11e8-9968-07d76b839d57.png)

### Expected result
To be correctly aligned

### Browser and version
Internet Explorer 11.2007.14393.0 using RDP (Remote Desktop Protocol)

**Comment by ramiroaznar** [comment]
This should be fixed, right @elenatorro?

**Comment by alrocar** [comment]
Stale issue. Closing 👋
