### ISSUE TITLE
It is not possible to edit/delete a widget if no data available

### ISSUE THREAD

**Issue by enekid** [CartoDB/cartodb#13678]
If there is no data to show in the widget, the 3 dots (...) that open the widget dropdown don't appear, and therefore it isn't possible to edit the widget (you have to go to the widget list).

## No data -> No 3 dots (...)

<img width="1222" alt="screen shot 2018-03-09 at 13 41 10" src="https://user-images.githubusercontent.com/623492/37208067-453a0c9e-23a0-11e8-9710-2a5133b53f0d.png">

## Data -> 3 dots (...)

<img width="1222" alt="screen shot 2018-03-09 at 13 49 01" src="https://user-images.githubusercontent.com/623492/37208189-aab104c4-23a0-11e8-804b-0fe72826ecaa.png">

**Comment by ramiroaznar** [comment]
I think this is the expected behavior. @piensaenpixel can you confirm it? Also check this one https://github.com/CartoDB/onpremises/issues/502

**Comment by ramiroaznar** [comment]
Closing in favor of https://github.com/CartoDB/onpremises/issues/502
