### ISSUE TITLE
Not able to edit geometry after adding one feature

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#13679]
### Steps to Reproduce

1. Add an empty layer
2. Add a geometry (a polygon, for instance)
3. Try to click on the recently created feature to edit it.

### Current Result

It's impossible to select the created feature.
If your refresh the browser then you can select it.

### Expected result

It should be possible to edit the feature without having to refresh the browser.

![edit-geom-bug](https://user-images.githubusercontent.com/1078228/37240234-1fc57760-2449-11e8-9a41-7e3511c5b8cc.gif)

**Comment by ramiroaznar** [comment]
Closing in favor of https://github.com/CartoDB/cartodb/issues/13423
