### ISSUE TITLE
User migrator: do not import old postgis functions

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#13677]
We need to skip restoring old postgis functions that may be present in our database after years of upgrades.

Thankfully, we have a list here: https://github.com/postgis/postgis/blob/svn-trunk/utils/postgis_restore.pl.in#L473, so it should be easy to skip with the `-l` options of `pg_restore`.

**Comment by AleGoiko** [comment]
[in carto](https://github.com/CartoDB/cartodb/blob/master/services/user-mover/export_user.rb#L27) we dump like this and it is fine: `pg_dump -d cartodb_central_development -U postgres -T users_migrations_gce -Z0 -Fc -f file_name --serializable-deferrable -v --quote-all-identifiers`
 
[before importing](https://github.com/CartoDB/cartodb/blob/master/services/user-mover/import_user.rb#L386) you have to create a TOC file like this: `pg_restore -l file_name  --file='mytocfile.list'`

modify the toc file, removing the functions linked above, and restore as we do in carto, but adding the `--use-list` or `-L` flag as shown here: `pg_restore -e --verbose -j4 --disable-triggers -Fc blabla --use-list="mytocfile.list"`

**Comment by javitonino** [comment]
Still some cleanup pending: https://github.com/CartoDB/cartodb/issues/13861

But this is mostly done and working :tada:
