### ISSUE TITLE
[OSERV10] D.O. quota not taken into acount. 

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#13670]
### Context

Found when running Smoke Tests

Data Observatory analysis runs even when quota is not enough. 

It also doesn't show any banner or quota warning when setting up the analysis parameters. 

### Steps to Reproduce

1. Set a quota in builder server: 
```
[root@onpremise-smokes-12 ubuntu]# carto-builder-ds-quotas.sh 1 -o organization --do-general

... Currently working on < data observatory general > quota ...
[OK]: Successfully set < data observatory general > quota for organization

[root@onpremise-smokes-12 ubuntu]# carto-builder-ds-quotas.sh 1 -o organization --do-snapshot

... Currently working on < data observatory snapshot > quota ...
[OK]: Successfully set < data observatory snapshot > quota for organization
```
2. Quota is set to `1`. Trying to run an analysis on a bigger table will succeed.

### Current Result
It seems we're not checking quota for DO analyses.

### Expected result
Analysis should fail if available quota < table rows

**Comment by jvillarf** [comment]
After checking with @ernesmb this is the expected behavior: we don't check the quota for data observatory
- https://github.com/CartoDB/dataservices-api/blob/development/server/lib/python/cartodb_services/cartodb_services/metrics/quota.py#L146

Closing
