### ISSUE TITLE
Align button and pagination in the publish modal

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#13688]
![image](https://user-images.githubusercontent.com/1214201/37288409-7e3606e2-2607-11e8-9464-9e2357eaa0be.png)

RT?

cc/ @alonsogarciapablo @ramiroaznar

**Comment by alonsogarciapablo** [comment]
Ok

**Comment by Jesus89** [comment]
There is no pagination here, but a scroll. So this ticket is outdated.

Could you check this @ramiroaznar?

**Comment by Jesus89** [comment]
![share-scroll](https://user-images.githubusercontent.com/2227572/47221577-09196280-d3b5-11e8-9450-370aea73cbcb.gif)

**Comment by ramiroaznar** [comment]
Yes, you are right. Closing.
