### ISSUE TITLE
Add default point aggregation

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#13683]
### Goal

Enable [default point aggregation] in layers with more than 100K.

For that, we must instantiate the map using the already implemented server aggregation in carto.js.

### Related tickets in carto.js

- [Add aggregation options to layers](https://github.com/CartoDB/cartodb.js/issues/2005)
- [Default server aggregation validation](https://github.com/CartoDB/cartodb.js/issues/2032)

### Development
- [ ] Get a dataset with 100K and another one with 500K and measure rendering times before applying the aggregation.
- [x] Set the default aggregation and check that it renders faster.
- [ ] Check that if the map had widgets and pop-ups they don't break after applying this aggregation.
- [ ] Check widgets / pop-ups / legends work as expected

**Comment by alonsogarciapablo** [comment]
Closing this for now.
