### ISSUE TITLE
Change privacy doesn't reflect the current state in the publish infowindosw

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#13689]
![privacy](https://user-images.githubusercontent.com/1214201/37289067-0db25b12-2609-11e8-8a28-8cd747bbb6c3.gif)

cc/ @alonsogarciapablo @ramiroaznar

**Comment by ramiroaznar** [comment]
Yes, it does. But you need to wait a little bit more. Feel free to close it. ;-)

**Comment by piensaenpixel** [comment]
But i think the UX is not very good, we should reflect it in the modal for example if it's loading it should appear in the modal.

**Comment by ramiroaznar** [comment]
IMHO the Publish/Share workflow should be redesigned. But this issue is working as expected. You can see that the loading is happening...

**Comment by ramiroaznar** [comment]
Added to the RT kanban!

**Comment by ramiroaznar** [comment]
Added to the RT kanban!

**Comment by alrocar** [comment]
Stale issue. Closing 👋
