### ISSUE TITLE
Wrong size widgets in Builder

### ISSUE THREAD

**Issue by rubenmoya** [CartoDB/cartodb#13682]
### Context
With a medium viewport the widgets in builder have the wrong size

### Steps to Reproduce
1. Create a widget in builder
2. Resize the screen

### Current Result
![screen shot 2018-03-12 at 09 21 59](https://user-images.githubusercontent.com/905225/37272485-0212a01e-25d7-11e8-814a-f393f7ac2f77.png)

### Expected result
The widget has the correct size

**Comment by ramiroaznar** [comment]
@rubenmoya What's the correct size? @Jesus89 is this fixed with #13743 ?

**Comment by ivanmalagon** [comment]
Shipped! 🚀
