### ISSUE TITLE
Bad style form after creating a feature

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#13680]
### Steps to Reproduce

1. Add an empty layer
2. Add manually a new feature (whether is  a polygon or a line)

### Current Result

The style form reflects another color that the one of feature.
It happens both in polygons and lines.

### Expected result

The style form reflects the same color of the feature.

![bad color line](https://user-images.githubusercontent.com/1078228/37240329-28cdc654-244a-11e8-8e16-60eeb54d1978.gif)

![bad color polygon](https://user-images.githubusercontent.com/1078228/37240349-5da885da-244a-11e8-9c5c-25c58b5cd265.gif)

**Comment by VictorVelarde** [comment]
Fixed with #14137 and shipped to production 🚀 !!

**Comment by ramiroaznar** [comment]
Vamos!
