### ISSUE TITLE
Histogram widgets are collapsed when adding another widget

### ISSUE THREAD

**Issue by rubenmoya** [CartoDB/cartodb#13706]
### Context
Histogram widgets are collapsing when adding a new widget

### Steps to Reproduce
1. Create a map with a histogram widget
2. Add another widget

### Current Result
![add-widgets-bug](https://user-images.githubusercontent.com/2227572/37420088-3da1dccc-27b6-11e8-9faf-21391af0e8d6.gif)

### Expected result
The histogram widget keeps the same state.

**Comment by ivanmalagon** [comment]
Shipped! 🚀
