### ISSUE TITLE
Rollback metadata on success

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#13719]
If a user migration fails, the metadata is rolled back (deleted). However, if it succeeds, there is no way to delete the metadata if needed. We need a tool to manually do this.

**Comment by amartinj** [comment]
This ticket is a duplicat (i'd say) of https://github.com/CartoDB/cartodb-platform/issues/4426

**Comment by javitonino** [comment]
Kind of. This one is much older because we predicted this would be a problem. The platform one is one specific instance of when this is needed (but i'ts needed in more places).
