### ISSUE TITLE
Gather all the metrics taking into account possible provider changes

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/cartodb#13713]
Right now we're using [these methods]() to get the data services API usage metrics in order to either compute the over quota for that user or to gather those metrics for other purposes.

In [this PR](https://github.com/CartoDB/cartodb/pull/13710) I've fixed the problem we were having to gather correctly the metrics using the defined provider for the user, but @javitonino has found another corner case in which if the user changes the provider we only gather his/her metrics partially becuase we only get the currently defined provider metrics.

That said we have to take that into account and try to get the metrics for all the possible providers in order to return a Hash like this:

```
{ mapbox: 200, heremaps: 100 }
``` 

BONUS: Also, we should change all the methods from things like `remaining_mapzen_routing_quota` to something more generic even if we leave the quota column names with that kind of names

**Comment by alrocar** [comment]
Stale issue. Closing 👋
