### ISSUE TITLE
Put to_create(&:save!) in all AR factories

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#13716]
FactoryGirl/Bot uses `save` by default to save. We want it to use `save!` in AR factories to avoid hidden errors.

**Comment by javitonino** [comment]
Keep alive!

**Comment by gonzaloriestra** [comment]
Closing in favor of https://app.clubhouse.io/cartoteam/story/83525/put-to-create-save-in-all-ar-factories
