### ISSUE TITLE
Deprecated SQL Analysis Node should only expose functions that you can actually use

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#13729]
### Steps to Reproduce

Within an organization...

1. Create a function fA with user A.
2. Create a function fB with user B.
3. Create a Deprecated SQL Analysis Node with user B.

### Current Result

Both fA and fB are exposed as options. But, if you use fA, it fails with a `fA fails with Analysis A1 failed: function fA does not exist`.

### Expected result

There are two alternatives:

a) Only expose functions within your schema. In the example. only `fB`.
b) Expose all functions but use them prepending the schema. In the example, calling `fA` with `a.fA` would've worked. Nevertheless, that might not be always true (the function might need extra permissions, for example) or desired (do we want to expose functions between users?

@rochoa , is a better, according to [your comment](https://github.com/CartoDB/tech-ops/issues/468#issuecomment-374532941)?

cc @ramiroaznar @danicarrion

**Comment by rochoa** [comment]
I would go with option A, or even better, instead of checking functions within your schema, check for functions that you actually have permissions on.

**Comment by alrocar** [comment]
Stale issue. Closing 👋
