### ISSUE TITLE
Change cursor state to "not-allowed" when hovering disabled UI elements

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13735]
Design issue: https://github.com/CartoDB/design/issues/1162

![hovercursor](https://user-images.githubusercontent.com/4319728/34712154-2bf05254-f522-11e7-9b3d-66f3f8a2a8d1.gif)

**Comment by ramiroaznar** [comment]
This should be fixed with this one https://github.com/CartoDB/cartodb/issues/13457

**Comment by arianaescobar** [comment]
You're right, let me add this to that ticket and I'll close this one.

**Comment by arianaescobar** [comment]
Done
