### ISSUE TITLE
Dataset columns are not aligned

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#13738]
### Steps to Reproduce

1. Create a new dataset:

![captura de pantalla 2018-03-21 a las 12 16 19](https://user-images.githubusercontent.com/932968/37707022-d14fa3be-2d01-11e8-984b-c79e3c81c0e5.png)

Chrome Versión 65.0.3325.162 (Build oficial) (64 bits)

cc @ramiroaznar

**Comment by ramiroaznar** [comment]
Closing in favor of https://github.com/CartoDB/support/issues/1398
