### ISSUE TITLE
Activate CORS in the API for requests from carto.com

### ISSUE THREAD

**Issue by albertoac** [CartoDB/cartodb#13736]
### Context
In order to be able to get the information from a connected user (name, email address and avatar) in statics websites, we need to do a request to the API (ticket [#1055](https://github.com/CartoDB/design/issues/1055)). Sadly it looks like the CORS doesn't allow requests from carto.com domain. When trying to do a test of a request the following error appears: 

### Current Result
```
Failed to load https://albertoac.carto.com/api/v3/me: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://carto.com' is therefore not allowed access.
```

### Expected result
Get the json from https://albertoac.carto.com/api/v3/me (or from the user that does the request)

### Browser and version
Chrome 65

**Comment by javitonino** [comment]
This is blocking a design project and we are low on bandwidth on Backend. Could we move this through RT (depending on load over there)? @ramiroaznar

**Comment by piensaenpixel** [comment]
ping @ramiroaznar

**Comment by javitonino** [comment]
In prod.

**Comment by piensaenpixel** [comment]
Thanks @javitonino !
