### ISSUE TITLE
Some maps are failing in high resolution displays

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartodb#13744]
### Context

When entering [this map](https://team.carto.com/u/roman-carto/builder/6d22ac88-bea8-427f-a0a9-d8ff299ae395/embed?state=%7B%22map%22%3A%7B%22ne%22%3A%5B40.25175637172045%2C-3.9839172363281254%5D%2C%22sw%22%3A%5B40.61082491956405%2C-3.3522033691406254%5D%2C%22center%22%3A%5B40.43153030189339%2C-3.6680603027343754%5D%2C%22zoom%22%3A11%7D%7D) in a high resolution display (i.e: retina macbook) both the data and the label layer disappears. However, in other maps it works great (created after the high resolution changes). 

### Current Result
![bug_retina](https://user-images.githubusercontent.com/3824953/37730047-e92bf1e4-2d3e-11e8-9343-41580dee6a75.gif)

### Expected result
Data and label layers must not disappear.

### .carto file
[AirBNB listings madrid (on 2018-03-21 at 18.36.09).carto.zip](https://github.com/CartoDB/cartodb/files/1834745/AirBNB.listings.madrid.on.2018-03-21.at.18.36.09.carto.zip)

**Comment by javitonino** [comment]
This bug is already fixed for new basemaps, so, as a workaround, just change your basemap to a different one and back to the original and that should fix the issue. We are working in fixing this automatically for all affected users.

**Comment by javitonino** [comment]
Should be fixed now
