### ISSUE TITLE
Columns and rows offset in data view

### ISSUE THREAD

**Issue by makella** [CartoDB/cartodb#13740]
### Context
I have noticed a few different times yesterday and today, that columns and rows are offset in some (not all) tables. 

I am unable to reproduce the exact steps. If/when I encounter again, I will update the issue.

<img width="1208" alt="screen shot 2018-03-20 at 1 39 58 pm" src="https://user-images.githubusercontent.com/1566273/37678821-c6fee5b8-2c44-11e8-86a6-3f24d9309966.png">

### Browser and version
Google Chrome: Version 65.0.3325.162 (Official Build) (64-bit)

**Comment by rubenmoya** [comment]
Already reported [here](https://github.com/CartoDB/cartodb/issues/13738) and [here](https://github.com/CartoDB/support/issues/1398).

Closing in favor of https://github.com/CartoDB/support/issues/1398

**Comment by makella** [comment]
oops!
