### ISSUE TITLE
Corner case in Layer list (Analysis + SQL + Sync)

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13755]
### Context

Design issue: https://github.com/CartoDB/design/issues/1136

### Current Result

<img width="330" alt="screen shot 2017-12-19 at 10 47 19" src="https://user-images.githubusercontent.com/16247628/34153976-374064ec-e4b4-11e7-82f3-0e8a3b5abcf5.png">

### Expected result

- We'll hide the dataset name in this case
- Swap SQL tag and Sync icon order
- 4px margin between SQL tag and Sync icon

![analysis sql sync](https://user-images.githubusercontent.com/16247628/37901542-cc38c088-30f1-11e8-9922-cbd34540812e.png)

**Comment by alrocar** [comment]
Stale issue. Closing 👋
