### ISSUE TITLE
Layers list's nodes should be linked to their proper layers/analysis

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13757]
### Context

The nodes in the Layers list are meant to be used as shortcuts. The idea is that if you click on a certain analysis node, you will be taken to that analysis options or if you click on a source node you should be taken to the data tab of its layer.

Right now, some nodes are not working that way.  

#### Example 1

Clicking on this A1 analysis node should take you to said analysis options

<img width="504" alt="screen shot 2018-03-26 at 12 48 46" src="https://user-images.githubusercontent.com/16247628/37902290-43ecad36-30f4-11e8-9162-0b49c34acdc2.png">

Instead, it takes you to Layer B's last analysis node (B3). Not even B2.

<img width="440" alt="screen shot 2018-03-26 at 12 48 59" src="https://user-images.githubusercontent.com/16247628/37902300-4d4c0b60-30f4-11e8-86f5-c038f77663e4.png">
 
#### Example 2

Clicking on this C0 Source node should take you to Layer C's data tab

<img width="460" alt="screen shot 2018-03-26 at 12 49 30" src="https://user-images.githubusercontent.com/16247628/37902382-8f93e236-30f4-11e8-9794-ab1e522c9e2c.png">

Instead, it takes you to Layer B's data tab.

<img width="466" alt="screen shot 2018-03-26 at 12 49 41" src="https://user-images.githubusercontent.com/16247628/37902387-930646c0-30f4-11e8-9bf7-665c5c1008d6.png">

### Expected Result

Every node should be linked to the element they're referencing, no matter where they are on the Layers list. 

### .carto file

[World Population Data (on 2018-03-26 at 10.54.46).carto.zip](https://github.com/CartoDB/cartodb/files/1847500/World.Population.Data.on.2018-03-26.at.10.54.46.carto.zip)

**Comment by alrocar** [comment]
Stale issue. Closing 👋
