### ISSUE TITLE
New green color for PUBLIC tag

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13756]
### Context

We've been using the color `#5FCC79` for the Sync options while also having `#9BC63B` for "PUBLIC" and `#9DE0AD` for highlights. In an effort to consolidate colors we are ditching `#9BC63B` and using `#5FCC79` for "PUBLIC" too.  

It might a good moment to change the tags copy to **SemiBold** and also adjust those tags margins to the correct ones: **1px for top&bottom, 4px for left&right**. 

### Current Result

<img width="371" alt="screen shot 2018-03-26 at 12 41 17" src="https://user-images.githubusercontent.com/16247628/37901903-06129fe4-30f3-11e8-9084-84b547716744.png">

### Expected result

![screen shot 2018-03-26 at 12 37 52](https://user-images.githubusercontent.com/16247628/37901915-0c15e9fa-30f3-11e8-8b6a-dc85634a7307.png)
![screen shot 2018-03-26 at 12 38 12](https://user-images.githubusercontent.com/16247628/37901917-0c325e28-30f3-11e8-93f7-79f3d1bc4c7d.png)

**Comment by Jesus89** [comment]
Done in CartoDB/cartodb#14349

**Comment by ramiroaznar** [comment]
@andy-esch has just realized that the dimensions of the button in the PUBLISH screen looks odd:

<img width="422" alt="screen shot 2018-10-31 at 8 58 47 am" src="https://user-images.githubusercontent.com/5215798/47789752-baa18780-dd15-11e8-9d1a-2a6d9299e703.png">

We should revert the change (but the colors).
