### ISSUE TITLE
Styling incongruencies on Layers list

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13759]
### Context

We just realized there are a few styling incongruencies on production with the original design of the Layers list. 

### Current Result

![screen shot 2018-03-26 at 13 24 25](https://user-images.githubusercontent.com/16247628/37903679-0d862402-30f9-11e8-8c69-af9a7348fc5c.png)

### Expected result

![screen shot 2018-03-26 at 13 04 31](https://user-images.githubusercontent.com/16247628/37903373-f0bc0f0e-30f7-11e8-9fc4-5c315a7201cc.png)

- [ ] Analysis nodes should have the default input styling, not the disabled one. Only source nodes should have the disabled one.
- [ ] There should be 4px of separation between the layer name and the analysis/widgets info below.
- [ ] Analysis nodes should have only 8px of margin left and right inside their inputs. On production, the ellipsis is cutting the short names unnecessarily soon. 

Also, SQL tags should use the color `#747D82`, not `#282C2F` like they have on production (below), which makes them stand out too much. 

![screen shot 2018-03-26 at 13 26 07](https://user-images.githubusercontent.com/16247628/37903763-5f0ff294-30f9-11e8-904b-27436e6ed4e1.png)

**Comment by alrocar** [comment]
Stale issue. Closing 👋
