### ISSUE TITLE
Fix public page routing

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#13768]
A request to `/` goes here:

```
  get '/[(user/:user_domain)(u/:user_domain)]' => 'admin/pages#public'
  root to: 'admin/pages#index'
```

But that makes no sense. If there's no username, it should return a 404.

cc @ramiroaznar

**Comment by javitonino** [comment]
Hey, I think this route is fine, and it makes sense in the general case. It handles:
- subdomainless: carto.com -> login page or dashboard for the logged user
- domainful: sub.carto.com -> public page or dashboard for the user
- domainful: carto.com -> redirect to carto.com.carto.com which doesn't make much sense

But the last case is already a problem with all domainful URLs if you don't include a subdomain.

So what problem are you seeing here?

**Comment by juanignaciosl** [comment]
The only problem is the "If there's no username, it should return a 404." part. Currently, requesting `/` without subdomain fails with a 500. As it's not a valid request, it should fail with 404, or maybe 400.
