### ISSUE TITLE
Heatmap legend does not update after style changes

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartodb#13763]
Related issues:
* https://github.com/CartoDB/onpremises/issues/518

### Context

After the smoke tests, we discovered that when the user changes the color ramp in a heatmap layer and there is a legend, the legend is not updated with the new colors.

### Steps to Reproduce

1. Create a new map from a dataset.
2. Go to the layer and then go to the style view.
3. Change the Aggregation to "heatmap"
4. Go to the legend view.
5. Add a "Custom Chloropleth Legend"
6. Go back to the style view.
7. Change the color ramp.

### Current Result
Legend colors do not change.

### Expected result
Legend colors must update.

**Comment by VictorVelarde** [comment]
Shipped

**Comment by ramiroaznar** [comment]
@VictorVelarde @elenatorro SB/18945489 is complaining that this is not fixed:

![heatmap](https://user-images.githubusercontent.com/5215798/45763828-a146ef00-bc31-11e8-8ffb-205529a20b66.gif)

Reopening and adding this to the RT.

**Comment by VictorVelarde** [comment]
AFAIK @elenatorro wasn't involved in this one (it was not under the style project, it was a previous isolated issue related to legend updates). If this also happens with common style form, then it is a regression.

@IagoLast let me know if I can help you
