### ISSUE TITLE
Custom legends glitch

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#13775]
Two issues here.

#### The user is able to edit HTML in non-existing legend

When entering the legend menu for the first time, the `NONE` legend is selected.
The user can switch to expert edition mode.

**Current result**
![image](https://user-images.githubusercontent.com/1078228/38034961-9d382892-32a3-11e8-9a1a-96e06a366dd7.png)

**Expected result**
![image](https://user-images.githubusercontent.com/1078228/38035001-b2b943f4-32a3-11e8-8f3c-7f13e776bfa1.png)

The switch is disabled. [You can't edit a legend if there's no legend.](http://i0.kym-cdn.com/entries/icons/original/000/022/138/reece.JPG)

Indeed, if you switch to custom legends and go back the switch is disabled (as it's meant to be)

**Browsers**

Spotted in Chrome and IE, at least.

#### The user can't go back when custom legend is selected (only IE)

**STR**

1. Go to legend tab
2. Click on `custom legend`
3. Try to click on `none` again.
4. Ha ha! You can't

**Expected result**

You can use your mouse as always.

**Comment by ramiroaznar** [comment]
Good catch! You cannot edit something that does not. Clever!
