### ISSUE TITLE
Add append strategy (`collision_strategy`) for Import API

### ISSUE THREAD

**Issue by jsanz** [CartoDB/cartodb#13772]
Our current import API works in the assumption that the resources are a whole, so if the import detects the resource has changed, it downloads it and fully replaces the current dataset with the new one.

There are use cases where the resource only reflects an incremental dataset, and it's actually desirable to design resources that way in scenarios where we are only appending new records, so we avoid importing the same old records over and over.

This feature request hence is to add a new strategy for the import API that appends the resource to the current synced table. 

Afterthought, maybe a primary key should be also added as a parameter to perform an `UPSERT` operation instead of a blind `INSERT`. I realize there may be other details to take into account but hopefully, this is not a can of :bug:s 

cc. @CartoDB/solutions

**Comment by juanignaciosl** [comment]
cc @jorgesancha @danicarrion @javitonino

**Comment by stevelewis99** [comment]
VAMOS @jsanz thanks for documenting!

Other thoughts to _consider_ as ideas, but definately not to overcomplicate anything to prevent this feature from happening:

- this would be awesome for sync tables, but not only those.. a manual append request to the import API is just as useful. I'm sure that's obvious, but just to make sure
- primary key parameter could be simple options e.g.  a single column with a sequence number or timestamp. Or more custom e.g. `department, item_id` if we wanted to have that flexibility/complexity
- could consider a rolling cut-off feature based on a timestamp column, for example make it easy to have "last 14 days" of data synced automatically. This could help prevent tables filling up, or if we prefer them to fill up so they need to buy more storage, then we can omit this feature 😂

**Comment by juanignaciosl** [comment]
cc @jorgesancha @danicarrion @rochoa because I know that there's some work in progress around improving the importer and they might be interested in this feedback.

**Comment by andrewbt** [comment]
@pramsey @rafatower because of that same WIP awareness

@stevelewis99 I think you might be able to do your third bullet already through use of triggers or something...on dataset update, delete before time XXXX...maybe...

**Comment by andrewbt** [comment]
@inigomedina @alonsogarciapablo this is a feature that could really improve ETL possibilities :)
