### ISSUE TITLE
Data retention information in Builder

### ISSUE THREAD

**Issue by danicarrion** [CartoDB/cartodb#13797]
Personal data retention period is shared with user if s/he chooses to close CARTO account. Suggested text: _We’re sorry to see you go. Just so you know, closing your CARTO account will delete all the personal data that you shared with us within XX days._

This applies to free and professional users only.

**Comment by ivanmalagon** [comment]
Are we doing this already?

Or do we have to implement a process to delete the data in XX days and then implement the notification?

**Comment by danicarrion** [comment]
It's only the notification we need to worry about.

**Comment by jesusbotella** [comment]
Where would this notification be shown? Right after cancelling the user account, or in the password confirmation modal?

![screen shot 2018-04-30 at 12 14 57](https://user-images.githubusercontent.com/4319728/39422987-32112aa0-4c70-11e8-891c-b6a28fe5b069.png)

**Comment by danicarrion** [comment]
No strong feelings on my side. If no one else chimes in, I think you can go with whatever is easier for you.

**Comment by danicarrion** [comment]
@agnesgyorfi ^^

**Comment by agnesgyorfi** [comment]
@jesusbotella I had a brief conversation with Jatorre about the need to let people have the option of continuing to receive marketing emails even after they choose to delete their accounts (insert @vuxita victory dance here) , and then a longer conversation with @javitonino about a tangentially related issue: the text we send when a Personal30 account expires. Based on that I think this is what we should do: allow users to opt into marketing communications here (Eva has a Hubspot property we could insert)

Example of no opt-in
![screen shot 2018-05-03 at 14 25 50](https://user-images.githubusercontent.com/7429638/39576356-257b6632-4ede-11e8-9f4c-317614741eee.png)

Example of opt-in
![screen shot 2018-05-03 at 14 25 58](https://user-images.githubusercontent.com/7429638/39576360-2969fd62-4ede-11e8-9cc1-181a3c2f0d5d.png)

Then when the user clicks, you can just prompt for password to confirm, with the text "YES, DELETE MY ACCOUNT"

**Comment by vuxita** [comment]
as @agnesgyorfi mentioned, this is the property to use: https://app.hubspot.com/property-settings/474999/contact/marketing_explicit_consent

**Comment by jesusbotella** [comment]
So, would this new flow be applied for all users, or only for `free` and `professional` users? 

Where does the initial text where we tell users about data expiration fit into this new flow? Can we put it in above those checks, and then leave the other modal I posted above as it is right now?

**Comment by agnesgyorfi** [comment]
@jesusbotella it would be ideal to add these fields for all users

We actually don't need to add specific information about the data retention, as users are already informed that it's max 2 years (we tell them this in our privacy notice). Please let me know if that answers your question!

**Comment by danicarrion** [comment]
I agree with @javitonino when he says we should table this. I don't see this as a critical/urgent thing right now, and this project is already big enough.

**Comment by agnesgyorfi** [comment]
In that case I suggest just having the first tick box option and leaving the language I suggested

@asimcox, would you please do me the huge favor of making a note to follow up on the second tick box project (to give users the option of staying signed up for @vuxita 's marketing comms) in the next few months?

Thanks, everyone!

**Comment by agnesgyorfi** [comment]
Hey @jesusbotella many companies have a multiple-check system to make absolutely sure you want to delete your account (personally I wouldn't find it burdensome as a user to first tick the box, then have click confirm, and then have to enter my password).

However if you're all in agreement that this is overkill, you could simply keep the essence of the sentence I'm suggesting and do something like this:
![screen shot 2018-05-04 at 18 49 02](https://user-images.githubusercontent.com/7429638/39640752-4b256394-4fcc-11e8-8266-85abffa98b06.png)

When the password confirmation modal pops up, you could just have the text "Please enter your password to finalize the deletion of your CARTO account."

**Comment by alrocar** [comment]
Not sure what's the status of this, but it looks stuck, so I'm closing it.

If it's still relevant I'd suggest starting a new conversation 🙏 

Thanks!

**Comment by agnesgyorfi** [comment]
😞
