### ISSUE TITLE
Direct support for mapbox base maps in Builder

### ISSUE THREAD

**Issue by jaakla** [CartoDB/cartodb#13798]
To use mapbox base maps user has to sign up with Mapbox user account and find suitable tokens from there. There is link and guideline for it, but still it is quite cybersome and expensive. Why not include the key Mapbox styles from https://www.mapbox.com/maps/ "quick selection" styles:
* Streets
* Outdoors
* Satellite streets
* Navigation

Mapbox Dark/Light styles are probably not needed here, as they are basically same as CARTO's own similar styles.

These would use CARTO's mapbox token/account, just as it is done with HERE.

If user is not happy with one of the given styles, then he/she can add "custom mapbox URL", which is really a just a custom tile zxy URL.

p.s. note that "MAPBOX STYLE URL" what is asked in Builder UI is not really precise, user has to give **tile** URL here instead. Mapbox provides also *style URL*-s, these are used for vector maps which we don't support in Builder yet, and are in form `mapbox://styles/mapbox/outdoors-v9`, so this can be confusing

**Comment by jaakla** [comment]
@jatorre - this way we can get MB Satellite as easy "built-in" selection, so consider hiding/removing Here maps next, without major functionality loss from user perspective. Makes sense?

**Comment by ramiroaznar** [comment]
In the RT we *fix* the Mapbox connector, but it only works for XYZ basemaps.
