### ISSUE TITLE
Popups don't look good in IE

### ISSUE THREAD

**Issue by rubenmoya** [CartoDB/cartodb#13808]
### Context
While developing the popups for Airship I was using the same approach we use in Builder and I realized that the package we're using to polyfill clip-path doesn't work on IE.

### Steps to Reproduce
1. Create a popup with only an image

### Current Result
![screen shot 2018-04-05 at 16 10 06](https://user-images.githubusercontent.com/905225/38371289-55d36396-38ec-11e8-8364-d2fc2355fbbf.png)

### Expected result
![screen shot 2018-04-05 at 16 14 16](https://user-images.githubusercontent.com/905225/38371313-6ad54d86-38ec-11e8-88c9-c5878c7ca255.png)

### Browser and version
I've tested it on Internet Explorer 11, but I'm pretty sure it's happening on Edge too

**Comment by rjimenezda** [comment]
The problem with this is that css clip-path property does not really work on IE.

A certain _back leg of a pig_ wrote this using https://github.com/andrusieczko/clip-path-polygon, and did not check that there was, in fact, no support for IE.

We might be able to make this work using actual SVG, I'll give it a try.

I think at the very least, we could fall back to showing a solid color triangle. And fix the Close button z-index issue.

**Comment by VictorVelarde** [comment]
Hi, I would like some feedback on the result (see image at https://github.com/CartoDB/cartodb.js/pull/2088)

Would you please @piensaenpixel ?

**Comment by VictorVelarde** [comment]
Shipped to production 🚀
