### ISSUE TITLE
Check possible problems of Editor users using new migrated pages

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#13811]
### Context

We plan to serve all static pages from NGINX. That means that Editor users will be using our migrated static pages:
* Dashboard
* Profile
* Account

It' likely that we won't have any problem but we need to check it.

So far, the biggest problem we've faced with a similar scenario was the preview of fav maps. This isn't going to happen in these pages since we don't preview the map.

Profile and Account are already migrated so we can pass an acceptance with an Editor enabled users.
For Dashboards we can perform this check while it's being migrated since static pages serving will start on May.

Please use this ticket to write down any discovery on this topic, bad or good.

**Comment by jesusbotella** [comment]
I have checked if there can be any wrong behaviour in these pages (profile, and account) when accessed by Editor users.

In these two pages, there is nothing related to visualizations. These pages contain forms to allow the users modify its own data (email, password, website, location, description, twitter username, and disqus shortname, third party services accounts), and delete its account.

Both forms send a request to `api/v3/me` when retrieving and updating the user data, so AFAIK, there won't be any issue with these pages as long as the backend/API provides the same response to the requests made by both type of users.

**Comment by rubenmoya** [comment]
Anything left to do here? Can we move/close this card?

**Comment by jesusbotella** [comment]
I think we can close this one.
Static and non-static pages FF have been removed. So, if any problem arises, we'll know through support.
