### ISSUE TITLE
PG::Error: ERROR:  column "account_type" does not exist on enterprise_controller

### ISSUE THREAD

**Issue by AleGoiko** [CartoDB/cartodb#13826]
### Context
*Please explain here below what you were doing when the issue happened*
issue popped up on rollbar: https://rollbar.com/carto/CartoDB-Central/items/10831/

the page doesnt exist and is linked on our home page, so its pretty important to get it fixed

I think its pretty clear there ;)

**Comment by alrocar** [comment]
Dups https://github.com/CartoDB/cartodb-central/pull/2321

Thanks for reporting! :)
