### ISSUE TITLE
Category widget is broken in 'small' screens

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#13829]
![image](https://user-images.githubusercontent.com/1214201/38608548-f8e5b690-3d7b-11e8-90bc-e0d2eb087d4f.png)

cc/ @ramiroaznar @alonsogarciapablo 

could we move this one through RT?

**Comment by alonsogarciapablo** [comment]
I was able to replicate this in Builder:

![screen shot 2018-04-11 at 11 33 25](https://user-images.githubusercontent.com/390398/38608676-4e36dd72-3d7c-11e8-8509-12b4304c9900.png)

It's working fine in Embeds.

**Comment by alonsogarciapablo** [comment]
Category widgets should look like this (right @piensaenpixel?):

![screen shot 2018-04-11 at 11 35 38](https://user-images.githubusercontent.com/390398/38608748-83691834-3d7c-11e8-82a2-bbae4e5a583c.png)

**Comment by ramiroaznar** [comment]
@rjimenezda can we apply a hotfix?

**Comment by rjimenezda** [comment]
Sure, let me check what's up with it

**Comment by ramiroaznar** [comment]
![image](https://user-images.githubusercontent.com/5215798/38686629-0bf7c7e2-3e75-11e8-934d-d8fb203d7b0a.png)

LGTM

**Comment by rjimenezda** [comment]
Fixed via https://github.com/CartoDB/cartodb/pull/13837

In production 🚀 📦

**Comment by alonsogarciapablo** [comment]
Thanks @rjimenezda!

**Comment by alonsogarciapablo** [comment]
And @ramiroaznar!
