### ISSUE TITLE
Legends can not be removed after analysis without data is applied

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartodb#13846]
### Context

When a user has a legend and applies an analysis that does not return data, the legend is still visible and the user can not delete it because she the legend tab does not allow this action.

### Steps to Reproduce

1. Add a layer and add a legend for this layer.
2. Apply an analysis to this layer that does not return data.
3. Try to delete the legend.

![legends_bug](https://user-images.githubusercontent.com/3824953/38821784-d624dfc6-41a1-11e8-9c32-aabead9c839a.gif)

### Current Result

It is imposible to remove the legend of the layer.

### Expected result

The user should be able to remove the legend.

**Comment by ramiroaznar** [comment]
IMHO styles and legends (and popups) associated with should be reset (removed) when the layer schema changes after applying an analysis. What do you think? @alonsogarciapablo @piensaenpixel

**Comment by elenatorro** [comment]
I think the same, but I would also display a message explaining why it has been removed. Or maybe, I would show a modal asking the user to continue in order to prevent the user from removing the legends.

**Comment by ramiroaznar** [comment]
Well, not sure about the modal. Because right now, after applying analysis some of the things are removed without the user asking for it. We need to do a fix for everything then...
