### ISSUE TITLE
Remove Auth API FF

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#13857]
After it has been enabled for everyone:
- [x] Remove code that checks for it
- [x] Remove from superadmin
- [x] Mention the need to run the rake to create Api Keys in the NEWS (as a NOTICE)

**Comment by inigomedina** [comment]
Ready to be closed?

**Comment by javitonino** [comment]
Still pending

**Comment by amartinj** [comment]
Make sure all api keys are in sync before merging

**Comment by javitonino** [comment]
Putting this in our backlog. @amartinj started working on a PR some time ago but stopped. You might be able to revive that PR, or start a new one, depending on what feels most confortable to you.
