### ISSUE TITLE
Add configuration for organization session timeout to org settings

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#13866]
Blocked by https://github.com/CartoDB/cartodb-central/issues/2225

Add a component to configure the session timeout for organizations. It must be able to be used by the organization owner (and admins?). You can set a duration, or mark it as unlimited.

**Comment by jesusbotella** [comment]
I have just come up with a first approach to the password expiration setting UI. I attach the two possible states configuration. Let me know what you think.

When selecting the password expiration days
![screen shot 2018-05-14 at 10 31 53](https://user-images.githubusercontent.com/4319728/39987114-11827cb8-5764-11e8-814a-049a659836b4.png)

When password expiration time is unlimited
![screen shot 2018-05-14 at 10 32 12](https://user-images.githubusercontent.com/4319728/39987148-31a4401c-5764-11e8-9598-8b4c6ffa1c6a.png)

@ivanmalagon

**Comment by ivanmalagon** [comment]
Looks good!
