### ISSUE TITLE
Default API Key lists private datasets

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#13864]
The Default API Key should only be displaying public Datasets in my account:

![screen shot 2018-04-18 at 10 40 16](https://user-images.githubusercontent.com/390398/38922580-ce5831aa-42f8-11e8-8405-a87b7e037c06.png)

For some reason, sometimes the list of datasets also includes private Datasets:

![screen shot 2018-04-18 at 10 40 28](https://user-images.githubusercontent.com/390398/38922579-ce3eb932-42f8-11e8-936f-b026c3fb7ead.png)

cc: @inigomedina @amartinj @jesusbotella

**Comment by VictorVelarde** [comment]
I've checked it and it looks like don't include private maps anymore (we do include maps with links) @alonsogarciapablo 

Should we close this now?
