### ISSUE TITLE
'Export image' in builder is showing the hidden layers

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#13865]
* 'Export image' in builder is showing the hidden layers

### STR

1. Create a map with more than 1 layer
2. Hide one layer
3. Export map as image

![img-1](https://user-images.githubusercontent.com/5215798/38932531-c8dcc600-4316-11e8-88e9-b214f3b47ac2.png)

### Current result

* Hidden layers are shown on the image

![img-2](https://user-images.githubusercontent.com/5215798/38932426-6d52cc44-4316-11e8-9c4e-5f2a2e241f92.png)

### Expected result

* Hidden layers should not been shown

![img-3](https://user-images.githubusercontent.com/5215798/38932577-f2567468-4316-11e8-8b5b-24ca62770229.png)

### Browser version

* Google Chrome Versión 61.0.3163.100 (Build oficial) (64 bits)

cc/ @ramiroaznar

**Comment by ramiroaznar** [comment]
SB/17018576 is also complaining about this issue.

**Comment by rafatower** [comment]
I'd say this is builder backend...

**Comment by ramiroaznar** [comment]
@antoniocarlon can you take a quick look at this one?

SB/17318720 is also complaining about this issue.

**Comment by antoniocarlon** [comment]
The _Export as image_ functionality uses the [zoom + center](https://carto.com/docs/carto-engine/maps-api/static-maps-api/#zoom--center) feature from the Static Maps API.

Te request performed has the parameter `layer` but as the endpoint is defined as `GET /api/v1/map/static/center/{token}/{z}/{lat}/{lng}/{width}/{height}.{format}`, it seems to be unused.

I think that this is an Engine issue.

**Comment by Algunenano** [comment]
Checking this now.
* Easily reproducible, also in local environment.
* Fails both with png and jpeg, but currently the jpeg is broken. It's requesting a `.png` and renaming it instead of requesting a `.jpg`:
```
https://cartocdn-ashbu-a.global.ssl.fastly.net/rmrodriguez-carto/api/v1/map/static/center/0445ebc2456a7ede439a39c2c850055d:1528209360603/12/40.44355045055424/-3.689346313476563/300/200.png?layer=0,1&api_key=XXX
```
`png` should be `jpg` to work correctly. I'll open a different issue for that.

**Comment by Algunenano** [comment]
The issue is Windshaft-cartodb. The map-store-map-config provider is only checking for the `'layer'` option in the parameters of the request, but it should also be looking for it in the query/url (as done in the named-map provider).

I'll create a PR to fix it, with tests and documentation (since the option is undocumented in the static maps API).

**Comment by ramiroaznar** [comment]
@Algunenano let me know when is ready to test it in staging! :-)

**Comment by Algunenano** [comment]
PR (pending review): https://github.com/CartoDB/Windshaft-cartodb/pull/973

Can be tested in staging with user `export13865`

**Comment by Algunenano** [comment]
Merged and deployed into production. Working fine on my tests.
