### ISSUE TITLE
Limit concurrent imports properly

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/cartodb#13874]
Our attempts to limit the number of concurrent imports per user are not [very effective](https://github.com/CartoDB/cartodb/blob/82a23d0cac74e5aeda9cb67961ceabdc402819f1/services/platform-limits/lib/importer/user_concurrent_imports_amount.rb#L12-L13
).

We use a counter of concurrent imports in redis, but a TTL based on the db timeout is applied:
https://github.com/CartoDB/cartodb/blob/82a23d0cac74e5aeda9cb67961ceabdc402819f1/services/platform-limits/lib/importer/user_concurrent_imports_amount.rb#L53-L54

The imports can easily take more than this TTL and in that case the counter is lost (so effectively reset to zero) and new imports accepted. We have a bad case recently with long imports being queued until they filled up the disk; in that case the user db timeout was 25 s and as a result the TTL was 1.2*25 = 30 s. The imports took 5-15 min each.

I think we could either check the actual number of active imports for the user in the db or use redis-based rate limits like those we're using elsewhere.

cc @javitonino

**Comment by javitonino** [comment]
Can we put this in RT @ramiroaznar?
