### ISSUE TITLE
No option for viz.json link from builder?

### ISSUE THREAD

**Issue by willkara** [CartoDB/cartodb#13872]
### Context
Trying to create a map using carto.js but can't seem to find a way to grab the viz.json link anywhere. Does this mean I need to recreate everything from scratch using the API?

If it's not available, is there an ETA?

Thanks!

**Comment by ivanmalagon** [comment]
CARTO.js v4 has a completely different approach compared to the previous version. Now it provides a series of blocks to build your visualizations programmatically, giving you a finer grained and programmatic control. Check the documentation at https://carto.com/developers/carto-js/guides/quickstart/

That being said, we're thinking in providing something a la vizJSON. We don't know yet what format we want give the users but anyway, it won't be available in the short term. So my recommendation is, like you said, build your visualization using the API.
