### ISSUE TITLE
No feedback when applying query in dataset view

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb#13875]
### Context

![no-feedback-on-update](https://user-images.githubusercontent.com/45346/39117505-56d2b3b0-46e7-11e8-9e33-d939433c6cae.gif)

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Go to a Dataset view.
2. Write a long query, e.g. an UPDATE that takes several seconds.
3. Click "APPLY" or CMD+S keyboard shortcut.

### Current Result
No feedback about what's going on on the UI.

### Expected result
I would expect to have any kind of feedback letting me know the query is running.

### Browser and version
Google Chrome Version 66.0.3359.117 (Official Build) (64-bit)
macOS Sierra 10.12.6

**Comment by rubenmoya** [comment]
In production! 🚀
