### ISSUE TITLE
Implement disconnect from GitHub button

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#13885]
Implement a button to disconnect from GitHub (similar o Google + one).

Two parts to this:
- [ ] ~(Optional) Revoke application acces in GH. This might not be possible with our current setup (since we don't save the token)~
- [ ] (Mandatory) Forget the `github_user_id` field (set it to null).
- [ ] (Mandatory) Don't allow disconnecting if there is no other authentication method configured (password or google). Otherwise the user won't be able to log in again. Show a decent message, something like "You cannot disconnect from GitHub unless you configure a password first."

**Comment by alrocar** [comment]
Stale issue. Closing 👋
