### ISSUE TITLE
Remove cookie _cartodb_base_url when user disconnects

### ISSUE THREAD

**Issue by albertoac** [CartoDB/cartodb#13894]
### Context
When a user disconnects from a link like https://USERNAME.carto.com/logout the cookie _cartodb_base_url persist in the user computer.

### Steps to Reproduce

1. Enter in your dashboard, and click logout. 
2. Explore the cookies in your computer. _cartodb_base_url still there with the base url of the user

### Current Result

The cookie persists in the user computer

### Expected result
The cookie should not exist if there's not user connected.

### Browser and version
Chrome 66 MacOS

**Comment by javitonino** [comment]
Finally fixed :)
