### ISSUE TITLE
Google Spreadsheet Importing Problems

### ISSUE THREAD

**Issue by michellemho** [CartoDB/cartodb#13890]
### Context
*Please explain here below what you were doing when the issue happened*
I was trying to upload a dataset from a Google Drive spreadsheet to CARTO, and noticed unexpected formatting of the table in CARTO. After several attempts with different formats, I finally solved the problem by downloading the spreadsheet as a .tsv and then uploading to CARTO. Not sure why this worked! Is this a known issue? I notice that our documentation says to have string fields double-quoted, but this was still an issue with .xlsx and importing with Google Drive connector.

Note: the dataset is an export from SalesForce, and is redacted here.

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Download Google spreadsheet as .csv
2. Upload as a new dataset to CARTO builder
3. The fields are not comma-separated
4. Download Google spreadsheet as .xlsx
5. Upload as a new dataset to CARTO builder
6. Same problem, the fields are not separated properly
7. Use CARTO google drive connector to select spreadsheet
8. Same problem, spreadsheet fields are still not separated properly
9. Download Google spreadsheet as .tsv
10. Upload as a new datset to CARTO Builder
11. Success!

### Current Result
*Please describe here below the current result you got*
![screen_shot_2018-04-24_at_12_18_05_pm](https://user-images.githubusercontent.com/12551177/39200373-013d3cd0-47ba-11e8-8b42-dc6fbbc91cfe.png)

### Expected result
*Please describe here below what should be the expected behaviour*
![correct_tsv](https://user-images.githubusercontent.com/12551177/39200607-a0d2e218-47ba-11e8-914c-32deb7c68a1a.png)

### Browser and version
*What internet browser (Chrome, Firefox, etc) and version was you using and version*
Chrome Version 66.0.3359.117 (Official Build) (64-bit)

**Comment by ramiroaznar** [comment]
Hey @michellemho did you send an internal support email requesting help to solve this problem?
