### ISSUE TITLE
Map editor · Beta

### ISSUE THREAD

**Issue by carlostallon** [CartoDB/cartodb#1390]
- [x] Metadata, permissions and other ops. (Layout, Geocode, Duplicate, delete...).
     - [x] License
     - [x] Source (@piensaenpixel will send designs)
- [x] CartoCSS editor.
- [x] Data panel.
     - [x] SQL editor.
     - [x] How to view data below widget (scrolled version)
     - [x] Filters interaction.
     - [x] New submenu design for SQL / Filters
     - [x] Feedback messages
     - [ ] Design for different filters
- [x] Infowindows panel.
    - [x] New infowindow templates.
    - [x] Make it dragable.
- [x] Legends panel.
- [x] Share modal.

------

- [x] Basemap selector.
- [x] Map options.
- [x] Configure canvas (mobile, desktop or custom resolution)
- [x] Confirm map deletion modal.
- [x] Drag & drop indicator in layers and interaction.
- [x] Use actual privacy modal (dashboard)
- [x] Add feature (polygon, point, line).
- [x] Color picker or select image new design (color also for svg images)

------

- [x] Unify map options and metadata under the cog icon.
- [x] Change margins between basemap options.
- [x] Revisit style of the switcher menus
- [x] Submenu colors
- [x] Configure canvas, set resolution inside desktop and mobile
- [x] Input to the left side on the legend editor.
- [x] Indicate that a layer has a query applied on the layers list.
- [x] Indicate that a layer has an error on the applied query.
- [x] Change buttons for adding rows and columns to the blue area on the data view.
- [x] Reorder colorpicker elements to allow numeric input on opacity.
- [x] Loading indicator to the layer itself.
- [x] 2nd level menu for infowindow on hover / click.
- [x] Try share as a modal.

------

- [ ] Odyssey.
- [x] Add overlay.

**Comment by carlostallon** [comment]
Thanks for the feedback @saleiva. Take a look to the changes you propose. Makes sense to me:

![map editor - layer expanded 2](https://cloud.githubusercontent.com/assets/1712650/5649487/8e84a21e-9696-11e4-80e6-ab99845a448d.png)

**Comment by saleiva** [comment]
- Import your data -> Connect your datasets
- Since there are thousands of posibilities for the background color when doing a map, what about doing the odyssey bar bkg dark?
- "I’d not add the small spike to the overlays icons since they don't have it in reality. Ok " :trollface: ??

**Comment by carlostallon** [comment]
Import your data -> Connect your datasets
**done**
- Since there are thousands of posibilities for the background color when doing a map, what about doing the odyssey bar bkg dark?
**let’s try**
- “I’d not add the small spike to the overlays icons since they don't have it in reality. Ok "  ??
**Ups, fixed**

![map editor - widget](https://cloud.githubusercontent.com/assets/1712650/5650375/20e45ed6-969e-11e4-88d0-aea7ec5795eb.png)

**Comment by saleiva** [comment]
Cool! Close and spread! :)

**Comment by carlostallon** [comment]
:+1:
