### ISSUE TITLE
Update googlemaps api version to v3.32

### ISSUE THREAD

**Issue by VictorVelarde** [CartoDB/cartodb#13902]
There are some internal references to googlemaps api v3.30 inside the application, that should be updated (e.g. `app/views/shared/_google_maps.html.erb`).

We should upgrade to the current stable version.

As a reference, we have recently updated carto.js v4 and dealed with some related issues (see for example: https://github.com/CartoDB/carto.js/issues/2067)

**Comment by VictorVelarde** [comment]
From 2018/05/16, `v3.32` is the stable version, so that's the update to apply inside this templates

**Comment by VictorVelarde** [comment]
This should be coordinated with the update in carto.js. See https://github.com/CartoDB/carto.js/pull/2126

**Comment by VictorVelarde** [comment]
@ivanmalagon I think we should upgrade these internal hardcoded references, once carto.js is working as expected with current gmaps stable version (v.3.32)

`_google_maps.html.erb` seems now to be unused (should we delete it?), but `static.js` is being used indeed.

**Comment by ivanmalagon** [comment]
We haven't run into any problem lately with 3.32 so... go ahead!

**Comment by VictorVelarde** [comment]
@ramiroaznar  this was nearly finished some days ago, could you include it in the current RT?

**Comment by VictorVelarde** [comment]
Shipped to prod 🚀
