### ISSUE TITLE
Auth API: guide about working with views and regular API keys

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb#13920]
After several discussions around Auth API, I have detected the pattern of people trying to restrict access to partial information from datasets. E.g., I have a `clients` dataset, I just want to build an application with _clients from NYC area_.

Using PostgreSQL and Auth API, you could create a view of your dataset with —basic or geospatial— constraints and grant access to a regular API key to that view. This avoid creating a separate table that you have to keep in sync with your original clients dataset.

My view:
```sql
CREATE VIEW clients_nyc AS (SELECT * FROM clients WHERE ...);
```

My API key:
```json
{
  "name": "Clients-NYC",
  "grants": [
    {
      "type": "apis",
      "apis": [
        "maps"
      ]
    },
    {
      "type": "database",
      "tables": [
        {
          "schema": "public",
          "name": "clients_nyc",
          "permissions": [
            "select"
          ]
        }
      ]
    }
  ]
}
```

It would be nice to create a guide about how to do this.

**Comment by inigomedina** [comment]
@oriolbx @jsanz this theme is that one we discussed at the time of the Auth release. I think you have been working with some clients this way. Do you think we can start writing a draft on the staging of the developer center?

**Comment by oriolbx** [comment]
Yes, @jsanz detected this pattern some time ago with the Auth API too. :) I think that we could start the documentation draft for the usage of the Auth API.

**Comment by jsanz** [comment]
yeah, that'd be super useful

@oriolbx do you mind start rolling the ball? :smile: 

Since we (CARTO Solutions Team) should be doing this procedure more and more, it'd be great for you to have a chat with @inigomedina on the best way to tackle the guide contribution process and eventually explain to the rest of the team afterward.

**Comment by oriolbx** [comment]
Ok! :)

**Comment by oriolbx** [comment]
Already on https://carto.com/developers/auth-api/guides/Authorizaration-CARTO-views/

**Comment by jsanz** [comment]
Awesome! Now we just need to fix that url, right? 😛

--
Jorge Sanz
CARTO - Predict through location

**Comment by inigomedina** [comment]
Awesome, @oriolbx. 👏 

Let's fix the url, and then use this resource in any conversation through support related to a similar problem, so that this resource becomes the first response.

**Comment by rochoa** [comment]
@oriolbx, can you fix that URL? 🙏

**Comment by oriolbx** [comment]
Sure, what should be the correct URL?

**Comment by rochoa** [comment]
From `guides/Authorizaration-CARTO-views/` to `guides/Authorization-for-CARTO-views/`. Look at the typo in `Authorizaration`, it's also present in the left menu.

**Comment by oriolbx** [comment]
Pull request has been merged but the changes haven't been applied yet

**Comment by inigomedina** [comment]
Updated URL: https://carto.com/developers/auth-api/guides/Authorization-CARTO-views/
