### ISSUE TITLE
Request - Allow both maps and data to be categorised.

### ISSUE THREAD

**Issue by EwenH** [CartoDB/cartodb#13921]
### Context
We use Carto extensively over a large range of internal divisions. We have some maps & data as temporary, some in production and some that are no longer required. It would be useful to be able to categorise these.

### Steps to Reproduce
1. Log into Carto
2. Go to Dashboard (Maps or Data)
3. You see a large list of maps or data depending on your account.

### Current Result
The current list (Alphabetical, best performing or time) are difficult to view. Tagging works to a point however easily overlooked. This would allow us to segregate web maps from standalone maps.

### Expected result
Provide a look and feel not too dissimilar to the Google drive.google.com where there is a folder structure as well as files within route if need be. The folder structure doesn't need to be more than one deep, but would be useful to be open ended however a single folder structure is better than none.

Alternatively, provide a better tag interface, although both a folder structure and  tagging would improve the entire UX

### Browser and version
All versions and restricted to the Carto Dashboard.

**Comment by ramiroaznar** [comment]
Hey @EwenH, thanks for your feedback and feature request. cc @alonsogarciapablo

**Comment by alonsogarciapablo** [comment]
@EwenH has the new dashboard solved some of the pains you described here? Thank you!

**Comment by alrocar** [comment]
Stale issue. Closing 👋
