### ISSUE TITLE
NoMethodError: undefined method `partially_dependent_visualizations' for nil:NilClass

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#13928]
[Trace](https://rollbar.com/carto/CartoDB/items/23785/?item_page=0&#instances)

No idea about STR, but it looks like we should handle errors for some corner cases.

cc @ramiroaznar (low priority, IMHO)

**Comment by ethervoid** [comment]
https://srogers.carto.com/tables/world_cup_live/public
https://rollbar.com/carto/CartoDB/items/36330/occurrences/49723307470/

**Comment by ethervoid** [comment]
The root problem is that we have multiple visualizations for the same name in that users and only one of them has a table associated.

Talking with @javitonino we need to create a rake task to delete the old visualizations (visualizations without tables) and then add a check in the creation of the visualization to avoid this situation

**Comment by ethervoid** [comment]
I've checked using the rails console and the following script:
```
empty_vis = Carto::Visualization.join("left join user_tables ut on visualizations.map_id = ut.map_id").where("visualizations.type = 'table' and ut.id is null")
empty_vis.each do |v|
    if v.table.nil?
        num_empty += 1
    else
        num_non_empty += 1
        puts v.name + " is a non-empty vis"
    end
end
```
And the result is:
```
irb(main):024:0> num_empty
=> 89117
irb(main):025:0> num_non_empty
=> 0
irb(main):026:0> 
```

So we have **89117** visualizations without user table linked in GUSC

Next step should be to create a rake to remove those visualizations, one idea to make HTTP request to some of them in order to check if all of them returns 500 code when we try to access them

**Comment by ethervoid** [comment]
Hum we have a "problem" here. Is true that we have duplicated visualizations but the main problem is that we have legit visualizations without `user_table`. 

For example this user, [danmat](https://carto.com/superadmin/users/14960):
- has the visualization in the table
- has the table in their database:
![captura de pantalla 2018-08-20 13 00 31](https://user-images.githubusercontent.com/741240/44337394-d7e6e980-a47a-11e8-9e04-2859d5137145.png)

So for some reason some users have lost their user_table register in the metadata table

Any clue? migrations?

**Comment by javitonino** [comment]
That visualization was created in 2013, so there may be multitude of past bugs regarding that. I don't really think it's related to migrations, just that old users have a lot of stuff like that.

**Comment by ethervoid** [comment]
So we go ahead with the plan of destroying those visualizations?

**Comment by javitonino** [comment]
I'd say yes. This table is now broken. If we delete the visualization it will eventually be picked up by ghost tables and fixed, which is an improvement relative to the current situation.

**Comment by ethervoid** [comment]
This is the user accounts distribution for those broken visualizations:
```
=> {"FREE"=>88491, "CARTO for students - Annual"=>1975, "BASIC"=>63, "Academy"=>1460, "CARTO Trial Account"=>20, "INTERNAL"=>105, "BASIC LUMP-SUM"=>33, "Internal use engine - Cloud - Annual"=>34, "AMBASSADOR"=>4, "ORGANIZATION USER"=>28, "ire"=>11, "MAGELLAN"=>1, "JOHN SNOW"=>1, "PARTNER"=>2, "Magellan Academic"=>10}
```

**Comment by ethervoid** [comment]
I want to question this again, are we sure we want to execute this potentially harmful rake when we don't have any complain about this visualizations? xD

**Comment by javitonino** [comment]
Yes, we want! :psycho: Point is, canonical visualizations without user table are already broken. So there is no reason to keep them around.

The only thing that could break are maps built on top of these visualizations. But since that is deleted from the user table model, there is nothing to worry about (famous last words).

**Comment by juanignaciosl** [comment]
While reviewing this, I took a look at the data and there are some pretty new. The most recent is from May (2018): https://andrewgelinas.carto.com/tables/boston_stadiums_1/public .

The user accounts distribution seems safe :+1:

**Comment by ethervoid** [comment]
Steps to deploy and execute:

- [ ] Deploy the rake code into production
- [ ] Run the dbm backup to have a fresh copy just in case...
- [ ] Execute the rake

**Comment by ethervoid** [comment]
Done

**Comment by juanignaciosl** [comment]
:fire: :muscle: :clap: !!
