### ISSUE TITLE
Layers with long names overflow the Widget sidebar and affect it's scrolling

### ISSUE THREAD

**Issue by andrewbt** [CartoDB/cartodb#13930]
### Context
*Please explain here below what you were doing when the issue happened*

If a dataset has a long name (my_dataset_named_with_underscores_after_each_word_because_I_originally_typed_it_in_as_spaces_and_it_got_converted_when_I_hit_save), it will overflow the Widgets sidebar, and make the sidebar semi-un-scrollable - you can’t multitouch, the only way to scroll is to click and drag the scrollbar.

See gif:
![long_dataset_scrolling](https://user-images.githubusercontent.com/2013555/39769797-28cfbdc0-52bb-11e8-9779-29a1b2003b7a.gif)

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Make a dataset with a name longer than 40-50 characters
2. Make a map with that dataset
3. Add enough widgets to the sidebar so that vertical scroll is necessary to see them all
4. Try and use a multitouch trackpad or scroll wheel to scroll through the widget sidebar; observe that it does not scroll
5. Click and drag the graphical scrollbars vertically (yes, you should be able to do that) and horizontally (no, this is a bug due to the dataset name overflow and makes the sidebar look bad).

### Current Result
*Please describe here below the current result you got*

see gif above

### Expected result
*Please describe here below what should be the expected behaviour*

Ideas:
1. Widget sidebar should only be vertically scrollable and multitouch interaction should not be broken
2. Dataset name is truncated to fit available space so overflow doesn't happen?

### Browser and version
*What internet browser (Chrome, Firefox, etc) and version was you using and version*

Chrome, Mac OS. Exhibits in Internet Explorer on Windows too though.

### .carto file
*Don't forget to rename .carto file to .zip file to be able to upload to github*

[my_dataset_with_underscores_after_each_word_because_it_got_conv map (on 2018-05-08 at 16.32.36).zip](https://github.com/CartoDB/cartodb/files/1984821/my_dataset_with_underscores_after_each_word_because_it_got_conv.map.on.2018-05-08.at.16.32.36.zip)

### Additional info
*Please add any information of interest here below*

**Comment by rubenmoya** [comment]
In production! 🚀
