### ISSUE TITLE
Error when styling points by value in animated aggregation style (Torque)

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartodb#13976]
### Context

This is a weird corner case. We have this [dataset](https://team.carto.com/u/elena-carto/dataset/elena-carto.listings). We want to style by "name" column by choosing a qualitative color ramp using animated aggregation.

When we click to select the "name" column, there is a weird error that shows up:

<img width="1047" alt="captura de pantalla 2018-05-21 a las 14 40 17" src="https://user-images.githubusercontent.com/3824953/40308101-62c7f62e-5d05-11e8-974c-febe8cf86240.png">

However, if we select another qualitative color ramp, it does not show any error.

It only happens in animated aggregation, if we select the "name" column to style by value in a simple aggregation, there is no error.

### Steps to Reproduce

1. Create a new map from this [dataset](https://team.carto.com/u/elena-carto/dataset/elena-carto.listings)
2. Change aggregation type to "animated"
3. Change color style by "name" value (as it is shown in the screenshot)

**Comment by alonsogarciapablo** [comment]
This issue was detected when working in https://github.com/CartoDB/product/issues/54 and it will probably get fixed as part of that project, so let's wait until that project is completed to avoid doing the work twice.

**Comment by VictorVelarde** [comment]
This looks like a problem with carto.js underneath, not Builder itself. 

In this dataset, `name` field has some values like: "Perfect room in Madrid's Center" (note the **apostrophe** inside). The windshaft error displayed looks like a problem derived from a previously bad formated *sql_wrap* in the torque-layer

I

**Comment by enekid** [comment]
Try this:

`WHEN \"name\" = 'Perfect room in Madrid''s Center'`

double single quotes :) [String Constants Reference](https://www.postgresql.org/docs/current/static/sql-syntax-lexical.html#SQL-SYNTAX-STRINGS)

**Comment by jesusbotella** [comment]
It works. Let me do a PR, and move it to acceptance to check the fix.

**Comment by alonsogarciapablo** [comment]
Can we close this @jesusbotella?

**Comment by jesusbotella** [comment]
Yes, sorry! I forgot to close it. ;)

**Comment by alonsogarciapablo** [comment]
Thanks!
