### ISSUE TITLE
Wrong quantitative ramps in Torque aggregation ramp selector

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartodb#13975]
### Context

When selecting a quantitative column to colorize by value in an animated aggregation, qualitative color ramps are shown in the dropdown.

### Steps to Reproduce

1. Go to builder editor to style a map (style tab)
2. Select "Animated" aggregation
3. Change color input to colorize by value

### Current Result
The dropdown menu shows qualitative color ramps.

![animated-style-by-value](https://user-images.githubusercontent.com/3824953/40307840-58cb8736-5d04-11e8-90b0-e03fe8b6a32f.gif)

### Expected result
The dropdown menu must show quantitative color ramps, like this one:

<img width="259" alt="captura de pantalla 2018-05-21 a las 14 38 59" src="https://user-images.githubusercontent.com/3824953/40307947-bd0662c0-5d04-11e8-9a25-85b935f0bb59.png">

### .carto file
[Airbnb-torque-issue.carto.zip](https://github.com/CartoDB/cartodb/files/2022521/Airbnb-torque-issue.carto.zip)

**Comment by alonsogarciapablo** [comment]
This issue was detected when working in https://github.com/CartoDB/product/issues/54 and it will probably get fixed as part of that project, so let's wait until that project is completed to avoid doing the work twice.

**Comment by ramiroaznar** [comment]
@elenatorro @alonsogarciapablo AFAIK, TurboCARTO + quantitative ramps and Torque [are not compatible](https://github.com/CartoDB/cartodb/issues/10947). The workaround always has been making custom breaks. Should we close this one?
cc @makella @ztephm

**Comment by makella** [comment]
I think as the previous discussions mention, that if the functionality isn't available, we should remove from the UI as to not confuse users.

If we don't support classifying numeric attributes but do support coloring features by category in a string, then any attribute that is numeric should be hidden from the list of available ones to symbolize on.

I think it is too much to explain which makes it all the more difficult.
I do see the time when you want to symbolize on a numeric attribute, and you get category colors and then go to the CartoCSS to replace the category scheme with a sequential one but that might be asking too much fo users.

what do you all think?

**Comment by ramiroaznar** [comment]
Yes, I think so. We should definitely hide the numeric fields. I would add a guide on how to create an animated bubble and gradient color maps using the Torque hack, but that's another story.

**Comment by VictorVelarde** [comment]
I've just applied your criteria, to *hide numeric fields*, in https://github.com/CartoDB/cartodb/pull/14021

That feature will be included with the rest of the work on **split size/color** at CartoDB/cartodb#14017 (WIP)
