### ISSUE TITLE
mis-geocoding of ISO-2 country code for Bahrain/Bosnia & Herzegovina

### ISSUE THREAD

**Issue by andrewbt** [CartoDB/cartodb#1399]
I recently uploaded a spreadsheet to CartoDB (.com hosted version) with ISO country codes for each row, and geocoded them using the Administrative Boundaries feature. Worked smoothly, except my entry for Bahrain with code BH was geocoded as Bosnia and Herzegovina, which should be code BA:

http://en.wikipedia.org/wiki/ISO_3166-2:BH

http://en.wikipedia.org/wiki/ISO_3166-2:BA

**Comment by saleiva** [comment]
Hey @iriberri can you take a look at this, and if so, move to the correct repo?

**Comment by iriberri** [comment]
Bug found. Moving here: https://github.com/CartoDB/data-services/issues/112.

**Comment by iriberri** [comment]
Fixed in production.
