### ISSUE TITLE
Importing large geojson file never completes

### ISSUE THREAD

**Issue by chrowe** [CartoDB/cartodb#14014]
### Context
*Please explain here below what you were doing when the issue happened*
I am importing a 183MB (35k row) geojson file stored on Amazon S3 using a link it a self hosted cartodb install on Amazon EC2.

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*
1. Increase `import_file_size` to something larger than your file
2. [Increase timeout](https://github.com/CartoDB/cartodb/wiki/FAQ#im-importing-a-large-file-but-it-fails-with-timeout-error-whats-wrong) (not sure if this is doing anything)
3. Go to `user/dev/dashboard/datasets`, paste in file url, submit, and connect dataset.

### Current Result
*Please describe here below the current result you got*
File finishes upload but never stops "importing..."
![image](https://user-images.githubusercontent.com/240115/40670760-1168db5c-6338-11e8-9072-16103624b90e.png)

In `log/import.log` I get...
```
{  
   "user":"dev",
   "state":"pending",
   "tables":0,
   "imported_tables":0,
   "failed_tables":0,
   "error_code":null,
   "import_timestamp":"2018-05-29T15:48:33+00:00",
   "queue_server":"54.164.149.185",
   "database_host":"localhost",
   "service_name":"public_url",
   "data_                                                                                                             type":"url",
   "is_sync_import":false,
   "import_time":0.00525,
   "file_stats":{  

   },
   "resque                                                                                                             _ppid":null,
   "user_timeout":1398101,
   "error_source":null,
   "id":"9165f871-fde6-4a63-                                                                                                             bc8f-c7c66b31a015",
   "total_size":0,
   "cartodbfy_time":0.0,
   "import_throughput":0.0,
   "                                                                                                             cartodbfy_throughtput":null,
   "cartodbfy_import_ratio":0.0,
   "extra_options":{  

   },
   "ret                                                                                                             rieved_items":0
}
```

### Expected result
*Please describe here below what should be the expected behaviour*
The files should finish importing.

### Browser and version
*What internet browser (Chrome, Firefox, etc) and version was you using and version*
Windows Chrome 66

**Comment by ramiroaznar** [comment]
Hi @sonic007, I recommend posting OS installation problems [here](https://groups.google.com/forum/#!forum/cartodb).
