### ISSUE TITLE
Triggering ghost tables and common data (dashboard events)

### ISSUE THREAD

**Issue by antoniocarlon** [CartoDB/cartodb#14010]
We need to trigger ghost tables and common data when visiting the dashboard (not working since we switched to frontend static pages)

Related to https://github.com/CartoDB/support/issues/1555 and https://github.com/CartoDB/support/issues/1557

**Comment by ramiroaznar** [comment]
- [x] create, cartodbfy and drop tables
- [x] import table via Import API and UI
