### ISSUE TITLE
Metadata rollback destroys assets

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#14026]
During metadata rollback in user migration, we destroy the assets, including the remote file. So, if the migration fails, bye bye assets :scream: 

cc @amartinj since you are working on something similar.

**Comment by amartinj** [comment]
This is in the case of a user, of an org or both?

**Comment by javitonino** [comment]
Both. In organizations, it only happens for users linked to a user, but not for global organization assets.

**Comment by javitonino** [comment]
https://github.com/CartoDB/cartodb/pull/14035 also fixes this
