### ISSUE TITLE
Broken "create map" with Data Library

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#14020]
### Steps to Reproduce

1. Go to Data Library
2. Select one
3. Click "create map"

### Current Result

![captura de pantalla 2018-05-31 a las 12 21 17](https://user-images.githubusercontent.com/932968/40777138-38b04204-64cd-11e8-8e09-7a207a87447b.png)

Reproduced both in team and in a new account.

cc @ramiroaznar for RT.

**Comment by ramiroaznar** [comment]
@juanignaciosl I was not able to replicate it on my account. Could you try again?

**Comment by juanignaciosl** [comment]
Sorry, I _think_ that I had reproduced it at Datasets section, but I can't guarantee it. Nevertheless, it happens with Data Library. I've fixed the title and STR. Try it with Data Library, it has failed to me three times in a row.

**Comment by juanignaciosl** [comment]
PS: there's a disgusting "vibrating spinner" as well.

**Comment by ivanmalagon** [comment]
shipped! 🚀
