### ISSUE TITLE
Remove all references to FF 'dashboard_migration'

### ISSUE THREAD

**Issue by rjimenezda** [CartoDB/cartodb#14038]
In some cases, this will be replaced by `(viewed_user || viewed_org.owner).builder_enabled?`.

For the data library, the condition is unnecessary since common_data has had the FF for a while now without any hiccups, so we could 100% disable the check.

However there's several places in the code where we're using the FF to serve static files instead of rendering a rails view. 

Right now on production, static files are *always* being served for *everybody* (by nginx), so we should reflect this behaviour on rails by always serving the static files, or making the condition a config thing, in case we want to check the old version.

Also, on other places we renamed the static feature flags by `dashboard_migration`, but it was related to pages that have not been migrated (show, map, etc). This has to be fixed as well, although it's not urgent since these static pages are not being used at all.

**Comment by javitonino** [comment]
I created https://github.com/CartoDB/cartodb/issues/14103 for static-serving part, and other backend checks, which should be most of this ticket.

We'll tackle it as soon as we get the chance (first in backlog).
