### ISSUE TITLE
Broken CTA in the 'Connect Dataset' modal

### ISSUE THREAD

**Issue by vuxita** [CartoDB/cartodb#14036]
### STR

1. Create a new carto account
2. Click on new map on the welcome modal message

![image](https://user-images.githubusercontent.com/5215798/40924483-9dade9d4-6817-11e8-9504-6dc826b297e7.png)

### Current result

![image](https://user-images.githubusercontent.com/5215798/40924443-8c19792c-6817-11e8-9592-246a3164976b.png)

### Expected result

@urbanphes could you tell us what is the expected result?

**Comment by rubenmoya** [comment]
In production! 🚀
