### ISSUE TITLE
Prepare report 

### ISSUE THREAD

**Issue by inigomedina** [CartoDB/cartodb#14046]

**Comment by dgaubert** [comment]
Hey!

Let me shed some light here, so far the limits that we have implemented in production are database timeouts. They are based on the type of the account of the user, having defined:

- Free: 5s
- Pro: 15s
- Enterprise: 25s

When the database fires the timeout for a given query, both `tiler` and `sql-api`, will respond to the user using the HTTP Error Code 429. I don't know how Builder handles this scenario so I'm focusing on the Engine side. I've created four simple dashboards in Kibana for the last 30 days to discover some insights:

- Tiler response: http://kibana.cartodb.net/#dashboard/temp/AWPZ5AhJ8wF_20g1kwk7
- SQL-API response: http://kibana.cartodb.net/#dashboard/temp/AWPZ5Eua8wF_20g1kxbS
- Top ten users hitting timeouts (tiler): http://kibana.cartodb.net/#dashboard/temp/AWPZ5HuK8wF_20g1kyQl
- Top ten users hitting timeouts (sql-api) http://kibana.cartodb.net/#dashboard/temp/AWPZ5Lb-8wF_20g1kzSO

Furthermore, @oleurud built the following dhashboard to check database timeouts: http://kibana.cartodb.net/#/dashboard/elasticsearch/Too%20many%20requests%20(only%20database%20timeout)

For the lasts 30 days, Tiler served 412,954,200 (~413M) requests. Which 397,097,898 (~397M, 96.16%) were succesfully served, 15,706,914 (~16M, 3.81%) were served with any kind of error and 149,388 (149K, **0.04%**) reached the database timeout.

In the case of SQL-API, the service served 112,320,558 (122M) request. Which 108,375,167 (~108M, 96.49%) were successfully served, 3,918,000 (~4M, 3.62%) were served with any kind of error and 27.391 (~27K, **0.02%**) reached the database timeout.

| Program | % timeouts |
|----|----|
| Tiler | 0.04 |
| SQL-API | 0.02 |

For the Tiler service , the top ten users hitting timeouts (80,035) represents the 53,57% of the total users hitting database timeouts, a detailed list:

| Rank | Timeout hits | % of total hits | User | Type |
|-----|-----|-----|-----|----|
| 1 | 44,744 | 29,95 | fonmaps | ENTERPRISE |
| 2 | 16,391 | 10.97 | pluto | FREE |
| 3 | 2846 | 1.91 | goal16 | FREE |
| 4 | 2846 | 1.52 | betanyc | AMBASSADOR |
| 5 | 1402 | 0.94 | chd-admin | Internal use engine - Cloud - Annual |
| 6 | 1323 | 0.89 | ariellopez | AMBASSADOR |
| 7 | 1135 | 0.76 | explore-admin | Internal use engine - Cloud - Annual |
| 8 | 829 | 0.55 | playsport-admin | Internal use engine - Cloud - Annual |
| 9 | 764 | 0.51 | 4global-admin | ENTERPRISE SMALL LS AWS |
| 10 | 463 | 0.31 | simon-carto | team |

For the SQL-API service, the top ten users hitting timeouts (20,277) represents the 74.03% of the total users hitting database timeouts, a detailed list:

| Rank | Timeout hits | % of total hits | User | Type |
|-----|-----|-----|-----|----|
| 1 | 4,296 | 15.68 | wri-rw | Internal use engine - Cloud - Annual |
| 2 | 4,294 | 15.67 | wri-01 | Internal use engine - Cloud - Annual |
| 3 | 3,350 | 12.23 | icrc | BASIC LUMP-SUM ACADEMIC |
| 4 | 3,151 | 11.50 | sd-integeo2 | ENTERPRISE |
| 5 | 1,385 | 5.06 | cedus-admin | Enterprise Builder - Annual |
| 6 | 1,315 | 4.80 | shaunanoordin-zooniverse | FREE |
| 7 | 1,421 | 5.18 | urbo-production | ORGANIZATION USER |
| 8 | 662 | 2.41 | dudka | FREE |
| 9 | 208 | 0.76 | okc | FREE |
| 10 | 195 | 0.72 | saleiva2 | INTERNAL |

Let's take a closer look at entreprise users:

| User | Request | Timeout hits | % of total request|
|----|----|----|----|
| fonmaps | 7,801,209 | 44,550 | 0.57 |
| chd-admin | 1,736,896 | 1,261 | 0.07 |
| explore-admin |  512,321 | 1,170 | 0.23 |
| playsport-admin | 726,193 | 829 | 0.11 |
| 4global-admin | 433,437 | 782 | 0.18 |
| wri-rw | 1,937,100 | 469 | 0.02 |
| wri-rw | 11,555,541 | 4,338 | 0.04 |
| sd-integeo2 | 2,243,846 | 3,864 | 0.17 |
| cedus-admin | 857,965 | 188 | 0.02 |
| urbo-production | 5,109,769 | 1,422 | 0.03 |

I couldn't say that we have a problem with the current limits for database timeouts.

Hope this helps
