### ISSUE TITLE
User migrator: oauth applications

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#14044]
For each user:
- Migrate `client_applications`
- Migrate `oauth_tokens`
- Migrate redis tokens: `$api_credentials -> rails:oauth_access_tokens:*`. This is done in the `after_create` hook of saving `oauth_tokens` with the Sequel model, so we could use that.

After that, fix for existing users.

**Comment by amartinj** [comment]
Code for exporting `ClientApplication`s and `OauthToken`s:
```ruby
include UserMetadataExportServiceExporter
    File.write(
      'client_applications.json',
      ClientApplication.where('id in (select distinct client_application_id from oauth_tokens)').reduce({}) do |res, app|
        res[app.user_id] = [] unless res[app.user_id]
        res[app.user_id] <<  export_client_application(app)
        res
      end
    )
```

**Comment by amartinj** [comment]
We still need to migrate tokens and client applications from the old cloud to the new one

**Comment by amartinj** [comment]
I'll be out for two days, so I'm removing my assignment.

What we need to do is run the export code in all clouds that were source of migrations and run the import in the destination of those migrations (once per source cloud and file)

**Comment by javitonino** [comment]
The code is also not retro-compatible with older export versions :(

If the export didn't have client_application, you get this error: https://rollbar.com/carto/CartoDB/items/35927/

**Comment by AleGoiko** [comment]
:ohno: I tested that client apps and tokens were migrated but not a regular case :broken_heart:

**Comment by javitonino** [comment]
Ran the migration for existing users. I'll submit a small PR later for the retrocompatibility thingy.
