### ISSUE TITLE
'Export image' in builder with jpg is exporting a png

### ISSUE THREAD

**Issue by Algunenano** [CartoDB/cartodb#14042]
### Context
I've noticed this while working in https://github.com/CartoDB/cartodb/issues/13865. No matter what format {.png, .jpg} you choose, the same endpoint is called (.png) so you are always getting an image with that format.

### Steps to Reproduce
1. Create a map in builder
2. Export as image using `.jpg`
![image](https://user-images.githubusercontent.com/664253/40987942-2a467b36-68ea-11e8-9f1f-4a74fb138062.png)
3. Check the image format (http://checkfiletype.com/).

### Current Result
The endpoint called is `/api/v1/map/static/center/{token}/{z}/{lat}/{lng}/{width}/{height}.png` so the exported is a `png`.

### Expected result
The endpoint called is `/api/v1/map/static/center/{token}/{z}/{lat}/{lng}/{width}/{height}.jpg` to get a true `jpg` image.

cc/ @CartoDB/rt-managers

**Comment by alrocar** [comment]
Yep you're right. The file is exported as '.jpg' in the filename but the file is actually a `png`.

I've found [this](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/builder/editor/export-image-pane/export-image-pane.js#L190) in the source code, so not sure how to proceed. It seems that someone decided to force request files as `png`.

**Comment by ramiroaznar** [comment]
@dgaubert could you shed some light here?

**Comment by rubenmoya** [comment]
Sorry to jump in!

The code that @alrocar linked it's just to merge the layers in the canvas to add the attribution, CARTO logo, etc, the file is created [here](https://github.com/CartoDB/cartodb/blob/add-lockout-bundle/lib/assets/javascripts/builder/editor/export-image-pane/export-image-pane.js#L243)

**Comment by ramiroaznar** [comment]
Thanks, @rubenmoya. Assigning this to @jesusbotella then.

**Comment by jesusbotella** [comment]
The thing is that the mimetype for JPG images is `image/jpeg` instead of `image/jpg, that's why we're exporting it in a bad format. :)

I will fix it right away :)

**Comment by jesusbotella** [comment]
Deployed! 🚀
