### ISSUE TITLE
Dataset not listed when creating an API Key

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#14045]
### Context

I was creating an API Key...

### Steps to Reproduce

Not sure how to reproduce but here's what I was doing.

1. Visited to your "API Keys"
2. I was hoping to give permission to a dataset called playas, but it wasn't there:
<img width="677" alt="screen shot 2018-06-06 at 19 41 19" src="https://user-images.githubusercontent.com/390398/41055558-ec9971a2-69c1-11e8-8923-36ec9aa3143a.png">
3. I tried searching for "playas" and it was there:
<img width="721" alt="screen shot 2018-06-06 at 19 41 28" src="https://user-images.githubusercontent.com/390398/41055578-fe7d3fde-69c1-11e8-8039-35af3fc4af13.png">

### Current Result

"playas" wasn't included in the initial list of datasets and I had to search.

### Expected result

1. I didn't know why "playas" wasn't there.
2. I searched for it, and I was able to select some permissions for it, but as soon as I cleared the search, "playas" was no longer visible... I would expect it to be the there.

cc: @ramiroaznar

**Comment by ramiroaznar** [comment]
I think this is expected, right? You need to cartodbfy that table. Could you confirm? @antoniocarlon

**Comment by alonsogarciapablo** [comment]
Actually, that table was created through the UI, so it should be cartodbyfied... And when I searched for it, it actually came up.

**Comment by antoniocarlon** [comment]
The table is cartodbfied because it appears in the dataset list, but AFAIK, that view shows the latest used datasets and you need to search for the rest.

If you do something with that dataset (add rows, modify the provacy options, ...) it will be on the list and you won't need to search for it

**Comment by alonsogarciapablo** [comment]
Thanks for the explanation @antoniocarlon. I have to say it was a bit confusing for me. Perhaps it's because there's nothing that indicates that those datasets are the ones I have recently used, and I was expecting to see all of them there, and always see the ones that I'm giving some permissions to.

**Comment by ramiroaznar** [comment]
So... is anything the RT can do with this ticket?

**Comment by alonsogarciapablo** [comment]
> So... is anything the RT can do with this ticket?

No. We can revisit this when we iterate on this screen (cc: @inigomedina)

Closing it for now.
