### ISSUE TITLE
Make oauth do login or signup but not both

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#14053]
To be consistent with central, throw errors in oauth (Google / GitHub) if:
- Trying to login and the user does not exist
- Trying to signup and the user already exists

Currently, we automatically redirect the user to the other flow. No more :)

**Comment by gonzaloriestra** [comment]
Still happening.

**Comment by gonzaloriestra** [comment]
Closing in favor of https://app.clubhouse.io/cartoteam/story/83539/make-oauth-do-login-or-signup-but-not-both
