### ISSUE TITLE
Create map button stays disabled on certain cases

### ISSUE THREAD

**Issue by rjimenezda** [CartoDB/cartodb#14061]
Steps to reproduce:

1. Open the dashboard or a builder map
2. Hit the new map button / add layer button
3. On the popup, upload a fil
4. Click on the "back" arrow that's on the dialog
5. Go to GDrive, or any other type of file source
6. Go back to a regular File
7. Upload a file again
8. The button is not enabled, but it should

Note: This is likely not related to the migration, it might've been there before, but since we're prodding around these files, it's worth fixing.

**Comment by rubenmoya** [comment]
In production! 🚀
