### ISSUE TITLE
Freeze of Editor assets

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#14067]
### Context
As the final trick of the Editor Builder migration we need to freeze the Editor assets. For the experience of a Builder user those assets are not needed so we can avoid them in the building process.

These are the proposed steps after some talks with @javitonino and @jvillarf They should be tackled in order.

### Steps

**Frontend:**
**A.-** Create a new file for setting the current editor assets version. Preferably in an `.rb` file.
**B.-** Separate build processes:
    - `grunt dev`, the current one, should create the assets for a Builder user, using the folder of the assets version set in `package.json`. The takeaway here is to have one process to be able to generate / develop the whole app (statics, builder, dashboard). If we get rid of `grunt` for this, ok. If not, also ok.
    - `wadus` should generate the editor assets, using the folder with the version set in A) file. This process would allow Editor users to generate / develop with the Editor assets.

**Backend**
**C.-** Create new helper to serve editor assets. Something à la `javascript_include_tag`. The way to do this it's not clear yet. This new helper should serve the assets set in the version file A) from a local folder or the S3 bucket. Just like it is right now but pointing to a different location.

**Frontend**
**D.-** Use new helper made in C) to modify every editor asset requirement using it.

**Infra**
**E.-** Add to current Builder deployment a call to the new build process (B `wadus`) if file A) changes. This should upload the editor assets to the proper S3 route provided by the version set in A)

### Acceptance
- [ ] As a Builder user, I should be able to launch the build process having no previous assets and use the application with no problem. Editor build process should've not been launched.
- [ ] As an Editor user, I should be able to launch a build process and get all the needed assets generated.
- [ ] Change Editor version assets, deploy in staging. Enter as an Editor user. I expect to see the brand new assets.
- [ ] Don't change Editor version assets, deploy in staging. Enter as an Editor user. I expect to use the app with no problems using the frozen assets. No Editor build process should be launched.
- [ ] Same for production

**Comment by ivanmalagon** [comment]
Frontend-wise, Editor code migration has finished.

Summing the highlights up:

- All old code used for Builder users has been migrated to Builder patterns.
- Build process improved in orders of magnitude.
- ES6 enabled for all the application.
- Static pages working.
- GDPR changes and new API keys pages developed in already migrated code.
- No animal was harmed during this project (but three developers suffered a lot).

Summoning @xavijam @matallo and @nobuti who will be happy to hear this. 😄

**Comment by xavijam** [comment]
V-A-M-O-S!

Slow applause!

![](http://www.reactiongifs.us/wp-content/uploads/2013/03/slow_clap_citizen_kane.gif)

**Comment by nobuti** [comment]
RABO!
