### ISSUE TITLE
I can not insert a user with Requet sh script / create_dev_user ERROR:  could not open extension control file "/usr/share/postgresql/  9.5/extension/plproxy.control"

### ISSUE THREAD

**Issue by campoleo77** [CartoDB/cartodb#14076]
### Context
*Please explain here below what you were doing when the issue happened*
After finishing to install cartodb I can not insert a user with Requet sh script / create_dev_user  and I can't login. The database user 'cart_dev_user....' is created, user is created but data 'users', 'client_applications' ....  are not insert/saved into database 'cart_db_development'

I get this errors:

 Sequel::Postgres::Database (1.3ms)  CREATE EXTENSION IF NOT EXISTS plproxy SCHEMA public
PG::Error: ERROR:  could not open extension control file "/usr/share/postgresql/  9.5/extension/plproxy.control": No such file or directory: CREATE EXTENSION IF NOT EXISTS plproxy SCHEMA public
  Sequel::Postgres::Database (0.1ms)  ROLLBACK
(0.000194s) ROLLBACK
error: Error installing and configuring geocoder api extension..............

error: #<Sequel::DatabaseError: PG::Error: ERROR:  could not open extension cont  rol file "/usr/share/postgresql/9.5/extension/plproxy.control": No such file or   directory
>................

PG::Error: ERROR:  could not open extension control file "/usr/share/postgresql/  9.5/extension/odbc_fdw.control": No such file or directory: CREATE EXTENSION IF   NOT EXISTS odbc_fdw SCHEMA public
  Sequel::Postgres::Database (0.1ms)  ROLLBACK
(0.000187s) ROLLBACK
[pool] Not dropping connection localhost:postgres:5432:postgres:sequel
[pool] Not dropping connection localhost:cartodb_dev_user_75903026-8bc5-41e9-8aa  a-e695bf243c2b_db:5432:postgres:sequel.......

No such file or directory
### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1.
2.
3.

### Current Result
*Please describe here below the current result you got*

### Expected result
*Please describe here below what should be the expected behaviour*

### Browser and version
*What internet browser (Chrome, Firefox, etc) and version was you using and version*

### .carto file
*Don't forget to rename .carto file to .zip file to be able to upload to github*

### Additional info
*Please add any information of interest here below*

**Comment by ramiroaznar** [comment]
Hi @campoleo77, I recommend posting this same question to [`cartodb` Google group](https://groups.google.com/forum/#!forum/cartodb).
