### ISSUE TITLE
Bubble legends with 2 buckets are wrongly rendered

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#14075]
### Context
Spin-off issue created from [Steph's acceptance](https://github.com/CartoDB/cartodb/pull/14017#issuecomment-397426284).

If you only use 2 buckets for point size the lowest one doesn't show in the size Legend, but if you use 3 buckets it does

### Steps to Reproduce

1. In Point Size section select By Value & choose a column
2. Set the number of buckets to 3
3. Click on the layer's Legend tab > Click Size tab > select Bubble Legend
4. Go back to the Style tab and change the number of buckets to 2

    3 buckets:
    ![screen shot 2018-06-14 at 4 16 28 pm](https://user-images.githubusercontent.com/1779444/41435988-6e930dda-6fee-11e8-99fd-9024ff1a594f.png)

    2 buckets:
    ![screen shot 2018-06-14 at 4 16 54 pm](https://user-images.githubusercontent.com/1779444/41436001-73dae678-6fee-11e8-8c70-57ad455a09bd.png)

### Expected result

The legend shows two bubbles.

**Comment by jesusbotella** [comment]
I have been taking a look at this and seems like Windshaft response is wrong when returning the data for the legend buckets.

This is the data that we send in the request for the layer:
```json
{
            "id": "dc50c366-95e8-40b7-888c-c78e7f7ebc0d",
            "type": "mapnik",
            "options": {
                "cartocss": "#layer {\n  marker-width: ramp([price], range(5, 20), quantiles(2));\n  marker-fill: #EE4D5A;\n  marker-fill-opacity: 0.9;\n  marker-allow-overlap: true;\n  marker-line-width: 1;\n  marker-line-color: #FFFFFF;\n  marker-line-opacity: 1;\n}",
                "cartocss_version": "2.1.1",
                "source": {
                    "id": "a0"
                },
                "interactivity": [
                    "cartodb_id"
                ]
            }
        }
```

And that's what we got in the response:
```json
{
  "rules": [
    {
      "selector": "#layer",
      "prop": "marker-width",
      "column": "price",
      "mapping": ">",
      "buckets": [
        {
          "filter": {
            "type": "range",
            "start": 8,
            "end": 59
          },
          "value": 5
        },
        {
          "filter": {
            "type": "range",
            "start": 59,
            "end": 9000
          },
          "value": 5
        }
      ],
      "stats": {
        "filter_avg": 75.06926990743578
      }
    }
  ]
}
```

It is returning the same `value` for both buckets in this case.
Meanwhile, when trying with 3 buckets, we get:
```json
{
  "rules": [
    {
      "selector": "#layer",
      "prop": "marker-width",
      "column": "price",
      "mapping": ">",
      "buckets": [
        {
          "filter": {
            "type": "range",
            "start": 8,
            "end": 42
          },
          "value": 5
        },
        {
          "filter": {
            "type": "range",
            "start": 42,
            "end": 75
          },
          "value": 12.5
        },
        {
          "filter": {
            "type": "range",
            "start": 75,
            "end": 9000
          },
          "value": 20
        }
      ],
      "stats": {
        "filter_avg": 75.06926990743578
      }
    }
  ]
}
```

Shouldn't Windshaft return different `value` property for the 2 buckets in the first case?

@ramiroaznar ^^

**Comment by enekid** [comment]
I've found the error. Turbocarto doesn't handle 2 buckets properly and sets the `value` of the last/second bucket with the same value as the first.

The bug can be found in [ramp-result.js](https://github.com/CartoDB/turbo-carto/blob/9e09fc08ba55a1bb31cfda44865bec0597f3bd1c/src/model/ramp/ramp-result.js#L307)
BUG
 `var lastElementIndex = lastIndex === 0 ? 0 : (lastIndex + 1);`
FIX
`var lastElementIndex = (buckets <= 1 || lastIndex === null) ? 0 : (lastIndex + 1);`

I'll fix and test it Monday morning

**Comment by ramiroaznar** [comment]
That piece of code[ was fixed by @ethervoid](https://github.com/CartoDB/support/issues/1016). We should make sure that the new fix does not revert to the previous one.

**Comment by rafatower** [comment]
vamoss, @enekid :clap: :clap: !

**Comment by enekid** [comment]
I have made some tests to the `fix of the fix` in a _dedicated_ and it looks now as expected:

2 buckets:

<img width="463" alt="screen shot 2018-07-06 at 14 02 22" src="https://user-images.githubusercontent.com/623492/42377885-7a6d558c-8125-11e8-9730-f25255775b30.png">

3 buckets:

<img width="455" alt="screen shot 2018-07-06 at 14 02 37" src="https://user-images.githubusercontent.com/623492/42377893-804f253e-8125-11e8-839c-c1b3743e4791.png">

We'll push the patch to production probably on Monday  
PR: https://github.com/CartoDB/turbo-carto/pull/79

**Comment by ramiroaznar** [comment]
It would be great if I can have a look before.

**Comment by ramiroaznar** [comment]
@enekid LGTM

**Comment by enekid** [comment]
Pushed to production!

<img width="663" alt="screen shot 2018-07-09 at 18 02 58" src="https://user-images.githubusercontent.com/623492/42462057-71ec0ff0-83a2-11e8-9d40-32dc1592f57d.png">
<img width="655" alt="screen shot 2018-07-09 at 18 04 29" src="https://user-images.githubusercontent.com/623492/42462111-94ea2474-83a2-11e8-9f48-d70c5523aba7.png">
