### ISSUE TITLE
Setup in-product notification to all users about changes to styling UI

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#14073]
**TO BE ENABLED WHEN https://github.com/CartoDB/learn/pull/542 and https://github.com/CartoDB/cartodb/pull/14017 are merge/released**

As part of https://github.com/CartoDB/product/issues/54, we want to display an in-product notification for all Builder users with the following copy:

> We've been listening to your feedback and have made some important changes to styling in Builder! Learn about the new styling options [here](https://carto.com/learn/guides/styling/style-by-value/).

@javitonino is there some work we can start doing to prepare for this so that we can enable the notification when the code and guides are deployed? Thanks!

cc: @ivanmalagon

**Comment by alonsogarciapablo** [comment]
Thanks @javitonino!

**Comment by javitonino** [comment]
Done. Let's remember to remove this in a few days/weeks.

**Comment by alonsogarciapablo** [comment]
@javitonino I think we can remove this notification.

**Comment by javitonino** [comment]
Adding to RT (myself this week xD)
