### ISSUE TITLE
Deprecate Twitter connector in `add dataset` modal.

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#14081]
### Context

Twitter data connector was deprecated in [https://github.com/CartoDB/product/issues/49](https://github.com/CartoDB/product/issues/49)

It was modified both in Builder and Editor code, pre-migration.

According to https://github.com/CartoDB/support/issues/1589 and https://github.com/CartoDB/product/issues/49#issuecomment-397702058 it seems that the deprecation has been wiped out with the migration, in the dashboard add dataset page.

Please, add the deprecation again to the page indicated in the issue above.

**Comment by jesusbotella** [comment]
Deployed! 🚀

**Comment by ramiroaznar** [comment]
:boom:
