### ISSUE TITLE
Need help on installing CartoDB on Ubuntu 16.04 server

### ISSUE THREAD

**Issue by sonic007** [CartoDB/cartodb#14086]
### Context & Steps to Reproduce
I am trying to install CartoDB on my Ubuntu 16.04 server
**1. gcc / g++ version mismatch**
Ubuntu server 16.04 already has gcc / g++ 5.4 versions so I can't install gcc / g++ 4.9.
Can I just use gcc / g++ 5.4 instead?

$ sudo apt-get install gcc-4.9 g++-4.9

**2. I can't install gdal2.1-static-bin**

$ apt install gdal2.1-static-bin

E: Unable to locate package gdal2.1-static-bin

If I change repo to
deb http://ppa.launchpad.net/cartodb/gis/ubuntu **precise** main
I get dependency error

The following packages have unmet dependencies:
 gdal2.1-static-bin : Depends: libgif4 (>= 4.1.4) but it is not installable
                      Depends: libhdf5-serial-1.8.4 but it is not installable or

**3. Support for Ubuntu 16.04 (xenial) in repo** 
repo http://ppa.launchpad.net/cartodb/gcc/ubuntu/dists/ only supports 12.04 (precise)
Do you have plans to support 16.04?

**4. In PostGIS section, I get several errors when I try this.**
$ sudo PGUSER=postgres make installcheck 

test test/CDB_GreatCircle     ... FAILED
test test/CDB_OverviewsTest   ... FAILED

### Current Result
As you can see I can't install CartoDB properly on my Ubuntu server machine.

### Expected result

**Comment by ramiroaznar** [comment]
Hi @sonic007, I recommend posting OS installation problems [here](https://groups.google.com/forum/#!forum/cartodb).
