### ISSUE TITLE
Organization notifications not shown in migrated dashboard

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#14088]
### Steps to Reproduce
1. As org owner, go to the organization settings -> notifications -> send a notification
2. As another user, go to your dashboard

### Current Result
Nothing

### Expected result
You see the notification

### Additional info
Here is the old code:
https://github.com/CartoDB/cartodb/blob/master/app/controllers/admin/visualizations_controller.rb#L71
https://github.com/CartoDB/cartodb/blob/master/app/controllers/helpers/organization_notifications_helper.rb
https://github.com/CartoDB/cartodb/blob/master/app/views/admin/visualizations/index.html.erb#L17

Pretty sure we lost it during the dashboard migration process.

cc @ivanmalagon

**Comment by ivanmalagon** [comment]
@ramiroaznar Sneaking this in RT. We need to send a notification to all users to announce the color / size and the notifications don't work.

**Comment by ivanmalagon** [comment]
Apparently, we receive dashboard notifications through the `/me` endpoint but not the organization ones. @jesusbotella is already working on adding them to the endpoint response.

We'll merge both both notifications (dashboard and org) in the bell dropdown. We guess it's the way to go.

**Comment by ivanmalagon** [comment]
Can we make the color / size announcement through a dashboard notification so this is not a stopper?

**Comment by jesusbotella** [comment]
I have just created a PR to solve this issue. I didn't have to merge both types of notification (organization and dashboard) because I dig through the code and seems like its purpose is different.

The organization notifications are the ones in the bell, and the dashboard notifications are shown in a full-width notification in the top of the page.

So, if you can do the CR (Backend and Frontend) will be great. I will pass it to acceptance as soon as it is approved :)

**Comment by javitonino** [comment]
Yeah, dashboard notifications are hardcoded in frontend code. Backend only passes a list of boolean flags on which notifications to show. e.g: this system is used to show/hide the builder tutorial (it's directly tied to the "do not show again" tick)

**Comment by alonsogarciapablo** [comment]
I tried this and it's working. The only thing that I noticed is that, if you switch the user type from Builder to Viewer (or viceversa) the notifications don't change (even after logging out and in again). I did this and I was seeing a notification for Viewer users using a Builder user.

The first notification is for Viewer uses only:

![screen shot 2018-06-20 at 13 11 37](https://user-images.githubusercontent.com/390398/41656262-b0e70dd0-748f-11e8-8cf5-eab398f5432f.png)
![screen shot 2018-06-20 at 13 11 31](https://user-images.githubusercontent.com/390398/41656263-b10fff92-748f-11e8-98b8-a76cf0d88941.png)

![screen shot 2018-06-20 at 13 12 09](https://user-images.githubusercontent.com/390398/41656261-b0cbfee6-748f-11e8-9205-9d54f38aab77.png)

**Comment by javitonino** [comment]
Yes, that's correct. It's working as designed. The notification is sent to the category of users, and linked to each individual user. If you change types later, or if a new user signs up, he won't get the notification. Aka: it works like emails, and Builder/Viewer is just the recipient.

**Comment by alonsogarciapablo** [comment]
🚀
