### ISSUE TITLE
Icon for success notifications not displayed

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#14097]
1. As an org owner, create a notification with icon = success
2. Send it to some users
3. Look at the notification: no icon `CDB-IconFont-success` css class seems to be missing.

Super-minor, but still.

@CartoDB/rt-managers

**Comment by Jesus89** [comment]
Hi @javitonino.

Could you add more information? I don't know what do you mean by `CDB-IconFont-success`

**Comment by javitonino** [comment]
Follow the STR and you should see the issue clearly. The `CDB-IconFont-success` thingy is just a bonus tip. If you follow the STR, you will see that the notification has an `<i>` tag to display the icon with `class=CDB-IconFont-success`. However, nothing is displayed, so I think this class definition is missing from the css / scss.

**Comment by rubenmoya** [comment]
How do I create a notification with icon = success?

![screen shot 2018-08-13 at 09 53 48](https://user-images.githubusercontent.com/905225/44019356-caa891fc-9ede-11e8-8b02-cc89b1d5c4ff.png)

I cannot find anything related to icons :S

**Comment by javitonino** [comment]
You can create one and then change the icon with the console (`Carto::Notification.order(:created_at).last.update!(icon: 'success')`). I thought it was exposed (it was at some point) :/

**Comment by alrocar** [comment]
Stale issue. Closing 👋
