### ISSUE TITLE
Tooltips not hiding in color / size controls in mobile

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#14098]
### Context

In the new color / size controls, when in mobile, if you click on the different radio buttons the tooltips start to stack.

![lots of tooltips](https://user-images.githubusercontent.com/1078228/41670054-92301ee4-74b3-11e8-8cd7-e91b34e569bb.gif)

At first it seems a problem with mobile and tipsy or Backbone forms, but there are other forms that works flawlessly, like this radio buttons in `Create distance / Travel buffers`.

![tooltips working](https://user-images.githubusercontent.com/1078228/41670068-969121a4-74b3-11e8-86bc-8e2435d1304c.gif)

I'll reserve this ticket to Victor. If a customer runs into this before we can pass it to the RT.

**Comment by ztephm** [comment]
FYI client is checking in on this issue. When it's fixed please notify [this SupportBee client](https://cartodb.supportbee.com/tickets/18104326) @CartoDB/support-team

**Comment by ivanmalagon** [comment]
Hi @ztephm 
We shipped a fix for this issue. It still fails on mobile but on desktop it presents some improvement. Can you contact the customer and ask him if their particular issue is gone? Thanks

**Comment by ztephm** [comment]
Yep! asked client in [this SupportBee Ticket](https://cartodb.supportbee.com/tickets/18104326).

**Comment by ramiroaznar** [comment]
Closing this. The client did not answer. We can reopen it if needed.
