### ISSUE TITLE
Send E-mail when recieving a like

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#1410]
When receiving a like The platform should send an email to the 'affected' user to let his know. This functionality should be deactivated on the account settings page.

We can use the same email template that we use on imports.

Cc @javierarce and @piensaenpixel

**Comment by saleiva** [comment]
Reactivating this.
The metrics are my boss now

**Comment by xavijam** [comment]
It could be disabled in user profile.

**Comment by rafatower** [comment]
@matallo could we add this a part of the hubspot flows?

**Comment by ethervoid** [comment]
I'm going to need the copy for this mail, thank you :)

**Comment by ethervoid** [comment]
I'm now working on the permission part. Where are we going to put the enable/disable notifications part? Right now there is not part of notifications in the user profile. Are we going to create one?.

IMHO the better option is to put a notifications section in the user profile that let the user enable or disable notifications. Also we have to add a footer with a link to redirect him to the part where he is able to deactivate the notifications.

**Comment by Kartones** [comment]
If we want to be purist on this, the link to unsubscribe should work with just an unsubscribe hash or something similar, not requiring the user to login to do it (according to the [CAN-SPAM act](https://www.ftc.gov/tips-advice/business-center/guidance/can-spam-act-compliance-guide-business)). Maybe a `base64encode([some-db-stored-SHA1-hash, notification-type-to-disable])`.

I think I have somewhere at home a brief summary of most important CAN-SPAM points (at Tuenti I had to read a bit about mailing to improve our spam-score, bounces-catching and delivery, etc.) if you want me to search for it.

**Comment by ethervoid** [comment]
After talk with @Kartones we are going to create the notifications part for the user model.

A user is going to have all the notifications active by default and could unsubscribe from them using a link in the bottom of the email. Doing this we are going to prepare the field for other kind of existent notifications.

**Comment by Kartones** [comment]
please, add a small wiki page explaining the DB schema, etc. so we start documenting new features

**Comment by ethervoid** [comment]
:+1:

**Comment by saleiva** [comment]
For the admin options, add an issue and assign to jose!

S.

-----
@saleiva

**Comment by ethervoid** [comment]
I'm going to extract the notifications management part of this issue to just leave the notification and move all the subscribe/unsubscribe part to the issue #4592

**Comment by ethervoid** [comment]
I thought about the idea of extract only the map liked notification but if we release this without notifications management its going to be a mailing nightmare for people with a lot of likes in their maps so we have to wait until the user management is donde.

**Comment by saleiva** [comment]
sadly, we don’t get too much likes, so I’d not worry about this

S.

-----
@saleiva

**Comment by ethervoid** [comment]
Ok so I can extract the map liked part and put in production :)
