### ISSUE TITLE
Spinner issues

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#14105]
### Displaced spinner

![misplaced spinner](https://user-images.githubusercontent.com/1078228/41779669-d28df0ee-7632-11e8-8290-9df4c1bb8486.gif)

The spinner within a button is misplaced. You can reproduce it adding the class `is-loading` to a button, like the `Publish` one.

```html
<button class="Publish-modalButton CDB-Button CDB-Button--loading
CDB-Button--primary CDB-Button--small u-rSpace js-button is-loading
">
  ...
</button>

```

### Spinner intensifies

![spinner intensifies](https://user-images.githubusercontent.com/1078228/41779682-dc0dbaf0-7632-11e8-95ae-c078cc8b8802.gif)

Shaky spinner while adding rows, for instance. It appears in more places.

**Comment by ivanmalagon** [comment]
Why is it this closed? No related PR?

Please add the reference to the original issue in the PRs! We lose track if not.

**Comment by Jesus89** [comment]
Sorry, I don't know how I closed this :stuck_out_tongue:

**Comment by Jesus89** [comment]
Staging: https://spinners.carto-staging.com

**Comment by ramiroaznar** [comment]
LGTM!

**Comment by Jesus89** [comment]
OK, let's deploy

**Comment by Jesus89** [comment]
:rocket:
