### ISSUE TITLE
Dataset options menu not working

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb#14107]
![screen shot 2018-06-24 at 18 49 28 1](https://user-images.githubusercontent.com/45346/41821378-d35e4bd2-77df-11e8-9bf1-6acf8dd390fe.png)

**Comment by ramiroaznar** [comment]
Reported [here](https://github.com/CartoDB/support/issues/1614) and fixed [here](https://github.com/CartoDB/support/issues/1614).
