### ISSUE TITLE
Legends and Autostyle odd behaviour

### ISSUE THREAD

**Issue by rjimenezda** [CartoDB/cartodb#14134]
### Steps to Reproduce

1. Create a points map, with (for instance) the world airports dataset
2. Add a Category widget for location or any other suitable column
3. Click on autostyle
4. Go to legends
5. Add a category legend
6. Everything should be fine so far
7. Publish the map
8. Open the embed
9. Play with the autostyle

### Current Result
Results are not very consistent, but what I'm usually getting is the legend disappears when the autostyle is active, and returns when the autostyle is gone. Which doesn't make a lot of sense.

I've noticed that in builder the legend is removed if after step 5 you remove the autostyling.

### Expected result
Maybe we shouldn't allow adding a legend based on having a category widget if we're going to hide the legend because the widget itself *is* the legend. Especially if the legend only shows when autostyle is NOT applied, it's just confusing.

**Comment by alrocar** [comment]
Stale issue. Closing 👋
