### ISSUE TITLE
GPKG with complex layer names won't import

### ISSUE THREAD

**Issue by pramsey** [CartoDB/cartodb#14159]
A GeoPackage file with ugly layer names (spaces, sometimes has geometry types, sometimes doesn't, special characters, mixed case) won't load. 
```
INFO: Open of `test.gpkg'
      using driver `GPKG' successful.
1: LayerMixedCase (Point)
2: Layer with Spaces and 'Punctuation (Point)
3: LayerUnknownGType
4: Unknown GeomType and Spaces
5: Unknown GeomType and Spaces and $#!'@Punctuation
```
https://github.com/CartoDB/cartodb/files/2189503/test.zip

This issue was identified as a bug with https://github.com/CartoDB/cartodb/pull/14153 but should be worked separately as it's a problem that pre-exists the support for FGDB and multi-layer GPKG files.

**Comment by ethervoid** [comment]
Could you provide a more clear example? thank you!

**Comment by pramsey** [comment]
Somewhere along the way this must have gotten fixed, as the test file imports without error for me now.
