### ISSUE TITLE
Oauth flow: alternative for 100% frontend applications

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#14167]
Implement the implicit grant mechanism. https://tools.ietf.org/html/rfc6749#section-4.2

**Comment by alonsogarciapablo** [comment]
Do we really really need this? Why?

**Comment by alonsogarciapablo** [comment]
I was reading a little bit about this, and found [this](https://oauth.net/2/grant-types/implicit/): 

> It is generally not recommended to use the implicit flow (and some servers prohibit this flow entirely). In the time since the spec was originally written, the industry best practice has changed to recommend that public clients should use either the authorization code flow without the client secret, or use the PKCE extension instead.

**Comment by javitonino** [comment]
Yes, the implicit flow is not perfect. The thing is, other alternatives are not much better. If you can't have secrets in the client, you are limited to what you can do. The drawback of using other techniques is that you lose on library support for the clients, which is kind of important. We will see what's available when we implement this.
