### ISSUE TITLE
Paging at Builder visualization map view doesn't work with analyses

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#14169]
### Steps to Reproduce

1. Create a table with more than 40 rows.
2. Create a map with it, go to the data view. Table works and can be paged.
3. Add an analysis (trave distance, for example).
4. Try paging. 

{"error":["syntax error at end of input"]}

### current behavior

It won't work, buttons are disabled. It's likely related to this error:

`https://juanignaciosl-2.carto-staging.com/api/v2/sql?api_key=cad05a2079b675c4e77b93d669b913bbf96fc6de&q=select+count(*)+from+`

![image](https://user-images.githubusercontent.com/5215798/42767336-07feddcc-891d-11e8-99dc-6f982c021bf5.png)

### expected behavior

Pagination should work.

### .carto

[Untitled Map 8 (on 2018-07-16 at 15.21.23).carto.zip](https://github.com/CartoDB/cartodb/files/2198173/Untitled.Map.8.on.2018-07-16.at.15.21.23.carto.zip)

### additional info

* related to https://github.com/CartoDB/cartodb/pull/14139

cc @ramiroaznar

**Comment by rjimenezda** [comment]
This is also broken with custom SQL if you end up with a different number of rows, because it's `select count(*)` for the layers' original table.

Fix is on the way
