### ISSUE TITLE
Oauth flow: login/signup after-hook

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#14168]
Ensure that if you are not logged-in when redirected to the consent screen, you eventually get redirected to it.

- If the user opts to log in, take him to the login screen afterwards.
- If the user chooses signup, redirect him to auth after signup.

Let's focus only in organization login for now (no central involved yet).

**Comment by alonsogarciapablo** [comment]
How could someone get to the consent screen without having logged in first?

**Comment by alonsogarciapablo** [comment]
Ok, so basically this issue is about adding the option to redirect "somewhere" (eg: the consent screen in this case) after the users logs in or signs up, right?

**Comment by javitonino** [comment]
Yup

**Comment by alrocar** [comment]
Acceptance 🍏 for login redirect.

@javitonino Should I be able to test `signup` in staging?
