### ISSUE TITLE
Oauth flow: consent screen

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#14164]
Implement oauth 2.0 authentication flow. We'll go for the "standard" flow (using web redirections and the extra step to exchange the token).

This ticket is for creating an endpoint for the consent screen. This received `redirect_uri`, `scope`, `state` and displays a screen asking the user to authorize.

**Comment by alonsogarciapablo** [comment]
@javitonino perhaps we can split this issue into two issues? One to implement the endpoint and another one to implement the screen that talks to the endpoint... What do you think?

**Comment by javitonino** [comment]
Yes, we will implement a basic/ugly one for this step in backend, the bare minimum to continue working. I expect design + frontend will come up later and :lipstick: it up. Related design issue is here: https://github.com/CartoDB/design/issues/1396

**Comment by alonsogarciapablo** [comment]
Will this endpoint check if user is already logged in/has been authenticated already?

Something like this?

![untitled drawing 4](https://user-images.githubusercontent.com/390398/43080587-52aa7610-8e90-11e8-8891-f240491cd100.jpg)

**Comment by javitonino** [comment]
Kind of. If it's not logged in, it will redirect to login. In https://github.com/CartoDB/cartodb/issues/14168 we will make it so it comes back to this screen after login.
