### ISSUE TITLE
Common data cache not working

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#14178]
It fails to save the values due to some encoding error: https://rollbar.com/carto/CartoDB/items/36340/

It seemed related to Rails 4, but I reproduced in Rails 3, when the same failure occurs but is not reported to Rollbar for some reason. Another way to confirm is that our logs don't show an increased activity in `common-data` since we deployed Rails 4, i.e: the cache never worked.

Basically, the response body from the list datasets endpoint has `response.body.encoding = Encoding:ASCII-8BIT`, although the server properly includes the header `"Content-Type"=>"application/json; charset=utf-8"`. When trying to convert to JSON, it fails due to an incorrect encoding.

`force_encoding` solves this, but it looks like the wrong solution. Maybe we need to pass an option to the HTTP client to choose the right encoding.

:cowboy_hat_face:  @CartoDB/rt-managers

**Comment by ethervoid** [comment]
Looks like a known issue with typhoeus https://github.com/typhoeus/typhoeus/issues/580
