### ISSUE TITLE
Fix style change metrics events 

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartodb#14183]
### Context

We are currently sending a wrong event name to metrics endpoint when the style is changed.

### Steps to Reproduce

1. Open / create a visualization map
2. Edit the style
3. Open the console / network in devtools to see the error

### Current Result

Request fails with the error: `{"errors":"Event not found: Changed default style","errors_cause":null}`

### Expected result
*Please describe here below what should be the expected behaviour*

### Browser and version

The event must be sent correctly.

### Additional info

It would be interesting to create a list of available metric events in a separate file, to be loaded and used as constants in order to keep track of the events we have configured.

**Comment by VictorVelarde** [comment]
I introduced this little issue in the size & color project, so I've included a fix for it in #14210 (with an improvement to avoid these kind of errors in the future)

**Comment by VictorVelarde** [comment]
Shipped to prod 🚀
