### ISSUE TITLE
You can't see locked datasets or visualizations that are shared with you

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#14188]
### Context

I realized about this during CartoDB/cartodb/issues/13970 acceptance.

### Steps to Reproduce

1. With an organization user (let's say user A), create a dataset X.
2. Share X with user B.
3. Lock X.
4. Login with B.

### Current Result

At "shared with me", the dataset is counted but not listed.

### Expected result

At "shared with me", the dataset should be both counted and listed, or there should be an alternative way to view it. Currently, you just can't. Or locked and shared should be exclusive, who knows.

cc @CartoDB/rt-managers

**Comment by javitonino** [comment]
Curiously enough, there is a route for this: `https://team.carto.com/u/javitonino/dashboard/maps/shared/locked` but it's not linked anywhere that I can see.

**Comment by juanignaciosl** [comment]
Maybe the link _should_ be there. It's certainly a simple solution, and it's consistent with the owned datasets tab.

**Comment by rubenmoya** [comment]
@CartoDB/design where should we add this link?

**Comment by urbanphes** [comment]
On the tab maps/datasets, on the bottom, shown a link to see "Show your N locked dataset/maps". The same way we could do the same in the tab "Shared with you" to put this link on the bottom, the see maps/datasets shared with you but blocked.

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/14546701/43768399-8c6a0a98-9a37-11e8-8847-7e8f3d43dc87.png">
