### ISSUE TITLE
Support multiple redirect URIs

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#14198]
From https://github.com/CartoDB/cartodb/pull/14194#discussion_r205411719

For now, we have implemented support for a single redirect_uri (a lá GitHub). However, other providers allow you the option to support multiple redirect_uris (e.g: Google). Implementing multiple uris is a bit more complicated, but not hugely so. In fact, I already implemented it but rolled back (YAGNI).

We should make an informed decision about this. Some additional details:
- We are not going to support any kind of wildcard in the URI. Doing so is unsecure.
- If we support multiple URIs, we should think to limit the amount to some fair limit.
- We (as oauth users) managed to get it to work with a single URI, since you can use a `state` parameter to get back any information you require. It would have been easier for us if we could use wildcards (to go directly to the user subdomain), but a finite amount of allowed redirection uris was not useful for us (it's wildcards or single in our specific usecase).

@juanignaciosl suggested taking a look at other providers. We can also talk to our potential users (partners?) and the apps they're developing.

@alonsogarciapablo could you help with this?

**Comment by javitonino** [comment]
@alonsogarciapablo said

Did a quick search/check of 4 providers:
- Google, Facebook, and Twitter accept multiple URIs.
- Github only accepts one. 

**Twitter**

<img width="854" alt="screen shot 2018-07-26 at 13 51 27" src="https://user-images.githubusercontent.com/390398/43261169-15d809c0-90dc-11e8-8d62-4a1574ef8bb0.png">

**Google**

<img width="802" alt="screen shot 2018-07-26 at 14 00 52" src="https://user-images.githubusercontent.com/390398/43261248-5641aa52-90dc-11e8-8064-d693e3dd439e.png">

**Facebook**
![facebook](https://user-images.githubusercontent.com/390398/43261167-158c238e-90dc-11e8-831e-1919301c2d0e.png)

**Github**

<img width="616" alt="screen shot 2018-07-26 at 13 54 43" src="https://user-images.githubusercontent.com/390398/43261168-15afe6a2-90dc-11e8-9699-7827c61f837b.png">

--

Since the goal of OAuth is to serve our own solutions initially (which I'm assuming will only require one callback URI) I agree with @javitonino on following the YAGNI principle.

In which cases it would be useful to specify more than one callback URLs?

**Comment by javitonino** [comment]
Some ideas of multiple URL use cases:
- Your app is hosted in different servers/domains/etc. Maybe it's the same app with rebranding differences.
  - Workaround with single URL is to register multiple apps (which is worse for us if we want to aggregate metrics)
  - You could also have a single callback URL and redirect to the proper domain depending on the information passed to the callback (state)
- Two environments: Staging/production. Although pretty sure you should register two apps for that.
- You want to migrate your app to a new domain without downtime. You could temporarily authorize two URLs while you move.
  - Workaround with single URL is to always put the callback to the old app and redirect from there to the new domain?
- You want to add some kind of user identifier to the URL
  - As discussed, this would need wildcard URIs and won't be supported.
  - You should use `state` to pas any information you need instead.

These are some ideas, but not sure what people use it for in the wild.

**Comment by alonsogarciapablo** [comment]
>  the authorization server will redirect the user back to the application with either an authorization code or access token in the URL

How does the authorization server determine what URL it should redirect users to?

**Comment by javitonino** [comment]
The application passes it as a parameter when redirecting into the provider. The provider then checks if that URL is authorized, and if it is, it will redirect back to the specified URL.

**Comment by alonsogarciapablo** [comment]
Thanks! So the URLs users enter when they register an app is basically a whitelist.

**Comment by javitonino** [comment]
Yep in the case multiple ones are specified. If only one is specified, the `redirect_uri` in the app->carto redirection can be omitted, since we know which one to use.

**Comment by alonsogarciapablo** [comment]
I asked @danicarrion about this yesterday and we honestly have no idea if this is going to be something we will need 😞. If it's something "cheap" to implement now or we believe it's going to be a nightmare to add it in the future, we might want do it. If it's going to take more or less the same amount of effort/time to do it now/in the future, we can wait. Your call @javitonino.

**Comment by javitonino** [comment]
This is very easy to add while we can migrate the DB freely (until we have working registered applications). Then it becomes quite a bit more complicated (couple of db migrations).
