### ISSUE TITLE
Build error at 'bundle install' 

### ISSUE THREAD

**Issue by robert-claypool** [CartoDB/cartodb#14196]
### Context
Yesterday I [tried to build](https://github.com/sverhoeven/docker-cartodb/issues/49) `sverhoeven/docker-cartodb` and the bundle install step failed.
 
@javitonino, this might be related to your recent changesets. I know next to nothing about Ruby and Gems, but I wanted to give you a heads up.

### Steps to Reproduce

1. Run `bundle install` in a fresh environment using master branch.

### Current Result
```Shell
Fetching thin 1.7.0
Downloading thin-1.7.0 revealed dependencies not in the API or the lockfile
(rack (< 3, >= 1)).
Either installing with `--full-index` or running `bundle update thin` should fix
the problem.

In Gemfile:
  thin
The command /bin/bash -l -c 'bundle install' returned a non-zero code: 34
```

**Comment by javitonino** [comment]
Hey there, thanks for the report.

Unfortunately, I cannot replicate the issue in my machine, using a fresh Ubuntu 16 VM. That docker image seems to have some unsupported choices, like using ruby2.5 on Ubuntu 18, which we know can cause some issues.

Did you try using a different ruby version?

**Comment by robert-claypool** [comment]
Thanks, you're right. The issue goes away when I switch to Ruby 2.2.10.
