### ISSUE TITLE
Isolines (all?) analysis should report error

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/cartodb#14211]
Related https://github.com/CartoDB/support/issues/1651#issuecomment-409630630

When an isolines analysis fail due to a 403 error the builder doesn't report any error and should return an error to the user

// @CartoDB/design  @VictorVelarde

**Comment by urbanphes** [comment]
Here's the notification for the analysis:

![analysis - case 1](https://user-images.githubusercontent.com/14546701/43723061-0dcbd982-9997-11e8-82dd-4167b5577de9.png)

(The example is based on Enrich from Data Observatory analysis, but is applied for any analysis)

**Comment by VictorVelarde** [comment]
ping @rubenmoya at RT

**Comment by rubenmoya** [comment]
How do I reproduce this? Do I need data observatory?

**Comment by jesusbotella** [comment]
How can I reproduce this?
Is Builder is receiving 403 error status, or is it masked as a success response with an error inside?

**Comment by jesusbotella** [comment]
Ok, there'll be an error notification as long as you follow analysis error property specification. We can add a custom error message for that error if you want :)
