### ISSUE TITLE
Better OAuth error management

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#14214]
Display better errors when:
- Some parameters are missing and are required https://github.com/CartoDB/cartodb/pull/14194#discussion_r207241755
- Sending `client_secret` from JS (e.g: check Origin header)
- In case of invalid client id or redirect uri, show a better message, rather than a 404.
- Better error for mismatched uris: https://github.com/CartoDB/cartodb/pull/14194#discussion_r207261887

**Comment by alrocar** [comment]
A couple of doubts:

- _Sending client_secret from JS (e.g: check Origin header)_ <- I don't get it 😅 , could you elaborate a little bit more?
- Do you mean an error screen with a custom message or something like that? Do we have something I can reuse (that you know of)?

**Comment by javitonino** [comment]
1. Probably not important now that we don't have CORS enabled for the token endpoint. But we can do something like throw an error if a request to `authorize` has a `client_secret` param.
2. Errors are now displayed in a pretty way in https://github.com/CartoDB/cartodb/pull/14237. As long as you throw an OAuth exception, it will end up in that UI.
