### ISSUE TITLE
Add format option to `load_in_data_library`

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#14216]
### Context

See CartoDB/bigmetadata/issues/540. We should add an option to choose the format, which should default to GPKG.

cc @javitonino

**Comment by javitonino** [comment]
Sounds like a plan.We choose the format [here](https://github.com/CartoDB/cartodb/blob/master/app/models/common_data.rb#L89), from the [config][https://github.com/CartoDB/cartodb/blob/master/config/app_config.yml.sample#L133), so having an option to override the config could be enough. If this works, maybe we should consider using `gpkg` for the platform as a whole.

Also, I was going to add that you may want to test `fgdb` which was recently added to our supported file at the importer. But I don't think we support exporting those yet. I don't know how good our compatibility for `fgdb` is, but from the rest of formats `gpkg` is the least lossy of them in most circumstances.

**Comment by juanignaciosl** [comment]
cc @ethervoid @CartoDB/rt-managers RT :pray: ?
