### ISSUE TITLE
Pretty OAuth consent screen

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#14221]
Implement https://github.com/CartoDB/design/issues/1396

**Comment by alonsogarciapablo** [comment]
cc: @VictorVelarde @ivanmalagon

**Comment by javitonino** [comment]
We merged the backend into master some hours ago, so you can start from there. The view is at https://github.com/CartoDB/cartodb/blob/master/app/views/carto/oauth_provider/consent.html.erb.

The scopes thing is not yet done (we don't have any scope), so we could code some example scope block (Personal data -> Public profile information) that we can later improve.

**Comment by alonsogarciapablo** [comment]
To clarify, the goal is not to implement everything that you see in https://github.com/CartoDB/design/issues/1396#issuecomment-410634922. For this first iteration we just need "1. When the user is asked for one" and "8. Error".

**Comment by VictorVelarde** [comment]
Shipped to prod 🚀

**Comment by alonsogarciapablo** [comment]
👏 👏 👏  Great job @VictorVelarde!

**Comment by VictorVelarde** [comment]
... and the same for @javitonino  👏 👏 👏
