### ISSUE TITLE
OAuth flow for native apps

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#14242]
The recommendation here would be to use the authorization flow + PKCE + allow custom protocols in the redirect uri.

**Comment by alonsogarciapablo** [comment]
This is about the [OAuth 2.0 Implicit Grant](https://oauth.net/2/grant-types/implicit/), right?

**Comment by javitonino** [comment]
Nope.

The plan is:
- Backend web applications -> Authorization code grant (already done)
- Frontend web applications -> Implicit flow https://github.com/CartoDB/cartodb/issues/14167
- Native apps -> Authorization code grant + PKCE (this issue)

This seems to be the recommendation all around.

**Comment by alonsogarciapablo** [comment]
Understood! Thanks! 👍

**Comment by gonzaloriestra** [comment]
Closing in favor of https://app.clubhouse.io/cartoteam/story/83551/oauth-flow-for-native-apps
