### ISSUE TITLE
How to increase maximum data count for animated time-series widget

### ISSUE THREAD

**Issue by azusat** [CartoDB/cartodb#14255]
### Context
We are using the free version of CARTO. We have about 10,000 data points with years attached (yyyy-mmm-dd), and we would like to use the animated time-series widget to visualize the changes of the locations by year. We were able to do this with 1000 data points or fewer, but when we increase the number of data points, we get a "loading" icon under the widget edit menu for "buckets," not the option to select from year, month, or date.

### Steps to Reproduce

1. After adding about 10,000 data points, we created a Date-Time Series widget and selected the date column to draw data.

### Current Result
1. In the "buckets" category, no option to view year, month, or date is visible. Instead, all we are able to see is a rotating "loading" icon in the "buckets" category.

### Expected result
1. We would like to be able to select by year in the "buckets" category. This would allow us to view the animated time-series widget to visualize the changes of the locations by year with over 1,000 data points.

### Browser and version
Firefox, Chrome, IE

### .carto file
*Don't forget to rename .carto file to .zip file to be able to upload to github*

https://azusat.carto.com/builder/f9bdd433-6341-4a81-8830-a458480a5a98/embed

Please let us know if we need to provide any additional information!

**Comment by ramiroaznar** [comment]
Hi @azusat, could you send us the .carto of your map to support@carto.com?

**Comment by azusat** [comment]
Hi @ramiroaznar, thank you SO much. I have written to the support service.

**Comment by ramiroaznar** [comment]
Closing this after taking care of it in support.
