### ISSUE TITLE
Expire OAuth authorization when removing/updating the authorization for an org

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#14262]
Just leaving it as a notice for the future. If we remove an oauth_app_organization, we should probably invalidate all existing oauth_app_users related to that organization if the app is restricted. Similar checks if an app changes from normal to restricted, etc.

**Comment by javitonino** [comment]
cc @alrocar in case you are interested in pursuing this

**Comment by gonzaloriestra** [comment]
Closing in favor of https://app.clubhouse.io/cartoteam/story/83528/expire-oauth-authorization-when-removing-updating-the-authorization-for-an-org
