### ISSUE TITLE
Randomly generated role names for Auth API

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#14275]
Do not use the username as part of the API Key role name

**Comment by oleurud** [comment]
Until now: `{Username}` _ role _ `{Random Hash}`

My proposals: 
- `{timestamp}` _ role _ `{Random Hash}`
- carto_role _ `{Random Hash}`
- role _ `{Random Hash}`

I prefer the last one @javitonino @juanignaciosl @antoniocarlon

**Comment by javitonino** [comment]
I like 2 because it makes it more obvious that is one role managed by CARTO (instead of some postgres internal). But 2 or 3 should be fine.

**Comment by juanignaciosl** [comment]
I also prefer 2, or even `carto_api_role_{Random Hash}`.
