### ISSUE TITLE
Unexpected error when querying DS functions through SQL API

### ISSUE THREAD

**Issue by antoniocarlon** [CartoDB/cartodb#14283]
### Context
Querying a DS function through SQL API for a non-org user using the `default_public` API key returns an error `function XXX does not exist`

For example:
```
{"error":["function cdb_geocode_namedplace_point(unknown) does not exist"],"hint":"No function matches the given name and argument types. You might need to add explicit type casts."}
```

### Steps to Reproduce
1. Query a DS function with an organization user: `https://myorguser.carto.com/api/v2/sql?q=SELECT%cdb_geocode_namedplace_point(%27Barcelona%27)&api_key=default_public`. It returns a well-known error (OK)

2. Query a DS function with a non-organization user: `https://mynonorguser.carto.com/api/v2/sql?q=SELECT%20cdb_geocode_namedplace_point(%27Barcelona%27)&api_key=default_public`. It returns a `function XXX does not exist` error (KO) 

3. Query a DS function with a non-organization user but qualifying the function: `https://mynonorguser.carto.com/api/v2/sql?q=SELECT%20cdb_dataservices_client.cdb_geocode_namedplace_point(%27Barcelona%27)&api_key=default_public`. It returns a well-known error (OK)

### Expected result
In all the cases the returned error should be the same, and a well-known one, not `function XXX does not exist`.

### Additional info
It seems that maybe adding `cdb_dataservices_client` to the `search_path` for non-org users could do the trick.

**Comment by oleurud** [comment]
We have 2 tasks to make to solve it:
- ensure a new publicuser has the `cdb_dataservices_client` in the `search_path`. 
- change the `search_path` of every publicuser of every db

The first one could be done in this project, but really, I would prefer to make it the same place that the publicuser is created (I need to show where is created to be sure if it is the best approach)

The second one could be solved in multiple ways. Maybe a fast bash script looping every db server could be enough.

**Comment by oleurud** [comment]
Adding more context about `publicuser` (ensure a new publicuser has the cdb_dataservices_client in the search_path) from offline conversations.

First of all, in non-organization users, the `publicuser` is a unique shared user. Every new CARTO user doesn't have a public user, all the CARTO users share the same one. This user is created at the beginning, before receiving any real user. Not sure if it is created by a rake`cartodb:db:create_publicuser` or by a query `CREATE USER publicuser ...`.

I created a PR solving the problem https://github.com/CartoDB/dataservices-api/pull/525 in `dataservices-api`. But @antoniocarlon and @ethervoid told me that `cartodb` manages the db of DS. So, this task should be managed by `cartodb`. Although I do not totally agree, I accept the point.

So, my propolsal is to add the `cdb_dataservices_client` in `the search_path` when the public user is created. As I said before, I need to ensure how is created with @CartoDB/infrastructure-team, but I think we run https://github.com/CartoDB/cartodb-postgresql/blob/aeec2bbe067942e577df78f1b9348503a2b48c04/scripts-available/CDB_SearchPath.sql when the `cartodb` extension is created. My idea is also adding `cdb_dataservices_client`

How do you see it? @antoniocarlon @ethervoid @javitonino

**Comment by javitonino** [comment]
> Not sure if it is created by a rakecartodb:db:create_publicuser or by a query CREATE USER publicuser ....

I think it's done here: https://github.com/CartoDB/cartodb-platform/blob/8292f575474da69a0b66421edb0b2a3c7ce9a533/cookbooks/postgis/recipes/default.rb#L12 on DB provisioning

> when the cartodb extension is created.

This is run when any user is created. i.e: the extension is installed per-user. Why is that better than doing it in Rails code?

In my opinion, the best places to do it would be ones when we already do role search path manipulation, which is basically in user creation in Rails. Otherwise, we manage search paths from different places which seems weird.

Adding it in `cartodb` seems wrong, since it's coupling two extensions in an uneeded way.

As I said, not sure which is bets, but I'm definitely curious on why you discarded doing this in Rails.

**Comment by oleurud** [comment]
> This is run when any user is created.

I didn't know it. Really I was thinking of doing it one time.

**Comment by javitonino** [comment]
Yup, the extension is installed per-database (not per-server), so the code would run per each database (aka user) that is created.

**Comment by oleurud** [comment]
> I'm definitely curious on why you discarded doing this in Rails.

Really, in the Ruby code, we are always (in organization users) doing the query setting the search_path for the `publicuser` in each CARTO user creation. So, my point was to avoid it.

But anyway, I want to close this issue, so, removing this condition https://github.com/CartoDB/cartodb/blob/master/app/models/user/db_service.rb#L470 we could do it in the same way for every user, being orgganization or not organization users
