### ISSUE TITLE
Twitter search rate limiting is broken

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#14280]
[This comment by @javitonino ](https://github.com/CartoDB/cartodb-platform/pull/4908#issuecomment-420659006) explains it.

https://github.com/CartoDB/cartodb/blob/23ac78708cca2ab7be8dc5694c28088f4cbcd428/services/twitter-search/lib/twitter-search/search_api.rb#L96-L108

**Comment by alrocar** [comment]
Stale issue. Closing 👋
