### ISSUE TITLE
Cannot delete an API key generated through OAuth 

### ISSUE THREAD

**Issue by alrocar** [CartoDB/cartodb#14291]
See: https://rollbar.com/carto/CartoDB/items/37066/

### Context

When granting access to other artifacts (a sequence, a view, etc.) to the db role associated to an OAuth generated API key, the role is not dropped.

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Authorize a user

```
https://reveal-user1.carto.com/oauth2/authorize?client_id=8vA48VW9UwMr&response_type=token&state=9808598598718741&redirect_uri=https://localhost:8080/oauth&scope=dataservices:routing
```

2. Use the access token returned in the previous step to get the session role (in the example below `access_token=PJd8M69xWmyoV3P7OnqR3w`)

```bash
curl -X POST \
  'https://reveal-user1.carto.com/api/v2/sql?api_key=PJd8M69xWmyoV3P7OnqR3w' \
  -H 'Content-Type: application/json' \
  -d '{
    "q": "SELECT session_user"
}'

output: carto_role_c29a4102-e799-426b-80b3-dd851923f1be
```

3. GRANT SELECT to a table of another user in the same org:

```
curl -X POST \
  'https://reveal-admin.carto.com/api/v2/sql?api_key=PJd8M69xWmyoV3P7OnqR3w' \
  -H 'Content-Type: application/json' \
  -d '{
    "q": "GRANT SELECT ON \"reveal-admin\".projects TO \"carto_role_c29a4102-e799-426b-80b3-dd851923f1be\""
}'
```

4. Once the key is expired (and destroyed) the rollbar notification pops up

### Current Result

See: https://rollbar.com/carto/CartoDB/items/37066/

### Expected result

The role is dropped as expected and the key destroyed.

### Additional info

Rollbar issue fixed manually from the rails console:

```rails
oat.api_key.send(:db_run, "DROP OWNED BY #{oat.api_key.db_role}"); oat.destroy
```

We could just include the fix [here](https://github.com/CartoDB/cartodb/blob/master/app/models/carto/api_key.rb#L397)

summoning @javitonino for triage, feel free to assign it to me :)

**Comment by oleurud** [comment]
Ei @alrocar nice description! :)

After reading [the docs about DROP OWNED](https://www.postgresql.org/docs/10/static/sql-drop-owned.html):
- we could change this instead of every individual `REVOKE` of the `revoke_privileges` method

`Any privileges granted to the given roles on objects in the current database and on shared objects (databases, tablespaces) will also be revoked.`

- we could reassign everything from the role to `postgres` role to ensure we "dont lose" anything

`The REASSIGN OWNED command is an alternative that reassigns the ownership of all the database objects owned by one or more roles.`

- A question: Do our roles have privileges from several DBs? I think no, just in case.

`DROP OWNED drops all the objects within the current database`

-----------------------------------------

So, we could modify the `revoke_privileges` method with:
```
db_run("REASSIGN OWNED BY \"#{db_role}\" TO postgres")
db_run("DROP OWNED BY  \"#{db_role}\"")
```
or even remove the `revoke_privileges` method and do everything in `drop_db_role`

**Comment by alrocar** [comment]
Hey! thanks for jumping in 👍 

> A question: Do our roles have privileges from several DBs? I think no, just in case.

I'd say no. This specific case is for when a role in one schema is granted to a table in another schema in the same database.

Apart from that, it has been done manually so that's why the `revoke_privileges` method does nothing and the error is raised, since there is no api key in the database with table permissions.

Not 100% sure about this, but I'd keep the `revoke_privileges` method and maybe add your fix to the `drop_db_role` method. I don't know if REASSIGN to postgres will accumulate objects on that role, maybe you could do a manual test, and see what happens.

In any case, I guess we are adding support for api keys that grant access to tables in different schemas soon, so maybe we'll have to rethink this by then.

Let me know if I can help.

**Comment by oleurud** [comment]
>  I'd keep the revoke_privileges method and maybe add your fix to the drop_db_role method

I think it is not nedeed, I think the `DROP OWNED` is making the same (and more) as:

> In any case, I guess we are adding support for api keys that grant access to tables in different schemas soon, so maybe we'll have to rethink this by then.

`DROP OWNED` should work in this case too. It removes every permission for a specific role (in the current database)

> I don't know if REASSIGN to postgres will accumulate objects on that role

Yes, it works fine, but I am not sure if it has sense. In addition to the documentation message about it, I have read some advice in the same way, but do we need it? I don't think so. Maybe @javitonino could say something interesting about


----------------------

The PR is ready https://github.com/CartoDB/cartodb/pull/14307. I am testing it in staging, with the `REASSIGN` to know how it works

**Comment by oleurud** [comment]
All works fine from my point of view. I will remove the `REASSIGN OWNED BY` because it has no sense for me to do it now if we dont do it before. I going to create the tests

**Comment by oleurud** [comment]
Useful and related documentation: https://www.postgresql.org/docs/10/static/role-removal.html

**Comment by oleurud** [comment]
:rocket:
