### ISSUE TITLE
Allow users to switch by themselves to new dashboard

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#1429]
Something like: 

> Hey! we will be launching this new thing, it will be applied to everyone in one month. Do you want to try it already? 

This will help users who are working on CartoDB in order to adapt to the change consciously.

Don't know how have you planned this change, but I was discussing it with @xavijam and adding an option for the user to select the dashboard in the transition period would be nice. :smile:

**Comment by xavijam** [comment]
New dashboard is gonna be released so, ```go to the future and leave the past behind```
