### ISSUE TITLE
[Dashboard] [Datasets] Paginated list of datasets

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#14314]
Paginated list of datasets.

If user has datasets:

- [x] Datasets are ordered by "Last update" date descending (by default).
- [x] Datasets include the following info:
  - Icon with Geometry type
  - Name
  - Tags
  - Last updated
  - Number of rows
  - Size
  - Privacy
  - Dataset owner (unless I'm the owner / if it's a shared dataset)
- [x] Lists up to 12 datasets
- [x] Button to Create a new dataset
- [x] Pagination
- [x] Round dataset size properly (eg: 1.5 GB instead of 1 GB).

If user hasn't uploaded/connected any dataset yet:

- [x] Card with button to CONNECT YOUR FIRST DATASET.

**Comment by ramiroaznar** [comment]
It is a corner case but just in case... tables with more than 1 GB are rounded without decimals. This could be very misleading for the user. For instance, in the following screenshot, the table `tickets` is around 1.9 GB but the dashboard is only showing 1GB:

![image](https://user-images.githubusercontent.com/5215798/48075465-a06b1c00-e1e3-11e8-8a2f-ea7d07739aa7.png)

**Comment by alonsogarciapablo** [comment]
I added a task for the rounding. Thanks for the suggestion @ramiroaznar! cc: @csubira

**Comment by jesusbotella** [comment]
We've already done it 😂. It shows 2 decimals at most, but we can tell @ramiroaznar to test it :)
