### ISSUE TITLE
[Dashboard] [Maps] Quick Actions

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#14315]
Map card has quick actions.

Quick actions:

- Maps created by me:
  - [x] Edit name...
  - [x] Manage tags...
  - [x] Change privacy...
  - [x] Share with colleagues... (only for members of an org)
  - [x] Duplicate
  - [x] Lock
  - [x] Delete
- Maps shared with me:
  - [x] Quick actions are hidden
- Locked maps:
  - [x] Unlock

**Comment by alonsogarciapablo** [comment]
@kukukaka Organization users can currently Share a map (or dataset) with their colleagues.

The actions is a bit hidden:

In the PRIVACY icon:

![screenshot 2018-11-05 at 16 08 42](https://user-images.githubusercontent.com/390398/48006049-3b48f500-e115-11e8-8159-7172e4391fbf.png)

Or, inside a MAP:

![screenshot 2018-11-05 at 16 08 28](https://user-images.githubusercontent.com/390398/48006047-3b48f500-e115-11e8-8156-3493ae9fa1c6.png)

You get this modal:

![screenshot 2018-11-05 at 16 11 53](https://user-images.githubusercontent.com/390398/48006387-a09ce600-e115-11e8-9b4a-d7e4fc7b07c7.png)

Do you think we should include this as a Quick Action? It would only be available for members of an organization.

**Comment by kukukaka** [comment]
Yes, it sounds good :)

Once you share it with a colleague, and click Save Settings, would it go to the first privacy screen or can we remove that step?

**Comment by alonsogarciapablo** [comment]
Once you share it, we can just close the modal because the action is DONE.

**Comment by jesusbotella** [comment]
Yes, that option shows up because the user is inside an organization, but the organization doesn't have more users to share the map with :/

**Comment by alonsogarciapablo** [comment]
Perfect. Thanks for the clarification!

**Comment by jesusbotella** [comment]
Did you find any issue to fix in Quick Actions? :)

**Comment by alonsogarciapablo** [comment]
No more issues apart from the one I asked you about. Quick actions are working 👌 

👏 👏 👏
