### ISSUE TITLE
[Dashboard] [Navigation] Update navigation in all private pages

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#14312]
Update the navigation to the [new one](https://github.com/CartoDB/cartodb/issues/14341) in all private pages. Only users with the feature flag enabled should see the new navigation.

Find the list of pages in the comments bellow 👇.

**Comment by ivanmalagon** [comment]
#### <%= render "shared/public_dashboard_org_header" %>
#### <%= render "shared/public_dashboard_user_header" %>

![image](https://user-images.githubusercontent.com/1078228/47010661-f1857400-d13f-11e8-848d-ab0fe67442bf.png)

Appears on:
- user_feed
- public_dashboard

----

#### <%* render 'admin/shared/private_header', :breadcrumb => breadcrumb %>

Appears on:
- api_keys
- mobile_apps

![image](https://user-images.githubusercontent.com/1078228/47010580-baaf5e00-d13f-11e8-88be-5f4ea411236b.png)

----

#### <%= render 'admin/shared/public_header' %>

Appears on:
- public table

----

#### <%= render partial: 'admin/shared/data_library_header' %>

Appears on:
- data_library

----

#### dashboard/components/dashboard-header-view.js

Appears on:
- organization

![image](https://user-images.githubusercontent.com/1078228/47010580-baaf5e00-d13f-11e8-88be-5f4ea411236b.png)

----

#### dashboard/components/private-header-view.js (extends dashboard-header-view)

Appears on (with its own model each one):
- profile
- account
-c dashboard (with routing)

![image](https://user-images.githubusercontent.com/1078228/47010490-6c9a5a80-d13f-11e8-844f-2d0d367af36c.png)

**Comment by ivanmalagon** [comment]
Another way of sorting them out:

- Private navigation:
    - dashboard 
    - account
    - profile
    - organization
    - api keys (rails)
    - mobile apps (rails)

- Public navigation:
    - user feed
    - public dashboard
    - public table
    - public library

**Comment by csubira** [comment]
I've just finished the PR with the header changes in:
- Dashboard
- Account
- Profile
- Organization
- API Keys
(I'm going for the billing page in central)
All of them are private pages, so the header is the same than in the new dashboard. 
Regarding public pages, my guess is that we are not using the same header (since it includes the search and the home/maps/datasets tabs) @alonsogarciapablo Is there any specific header for these pages?

**Comment by alonsogarciapablo** [comment]
Vamos @csubira! 💪 

Question: have we managed to somehow reuse the same code in all those places or is the code duplicated?

> Regarding public pages, my guess is that we are not using the same header (since it includes the search and the home/maps/datasets tabs) @alonsogarciapablo Is there any specific header for these pages?

@kukukaka ☝️

**Comment by alonsogarciapablo** [comment]
> Regarding public pages, my guess is that we are not using the same header (since it includes the search and the home/maps/datasets tabs) @alonsogarciapablo Is there any specific header for these pages?

The navigation that currently have in the public pages is closer to the website one:

![image](https://user-images.githubusercontent.com/390398/51544899-2d2b8a80-1e61-11e9-8bef-ebaf9a2bdd34.png)

IMO we should go with something more similar to the one (or the same that) we use in the website, but that's definitely not something to worry about in this issue.

**Comment by alonsogarciapablo** [comment]
Hey! Glad to see this is already in Acceptance! 👏 How can we give it a try?

**Comment by csubira** [comment]
@alonsogarciapablo already in production under feature-flag!
