### ISSUE TITLE
Handle long username/subscription plan in settings dropdown

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#1431]
![screen shot 2014-12-15 at 12 15 30](https://cloud.githubusercontent.com/assets/978461/5434652/5347f0a6-8454-11e4-987a-b0c298d3daf9.png)
This is how the new settings dropdown is displayed at the moment, when the username and/or the subscription plan are long enough to span the minimum size. How should we handle this kind of "edge case"?

**Comment by xavijam** [comment]
Closing for the moment, account types have been shortened.
If we need to change or design other things, we will create new ones.
