### ISSUE TITLE
[Dashboard] [Maps] Ordering

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#14316]
Maps can be ordered.

There's some Backend work that needs to be done to make this work:

- [ ] Add the following ordering options to `viz` endpoint:
  - [ ] `updated_at` ascending (default).
  - [ ] `updated_at` descending.
  - [ ] `name` ascending.
  - [ ] `name` descending.

Add the following Filters:

  - [ ] Last modified (First | Last)
  - [ ] Name (A-Z | Z-A)
  - [ ] Most views first

(*) The "Favorites first" filter will be implemented in https://github.com/CartoDB/cartodb/issues/14372.

**Comment by alonsogarciapablo** [comment]
Right now we only support the following options:
- Date (udpated at) (descending)
- Number of views (descending)
- Likes (descending)

To sort maps alphabetically, we would need some backend work, right @javitonino?

**Comment by javitonino** [comment]
Yes. Backend currently supports: `[:updated_at, :size, :mapviews, :likes]`

**Comment by alonsogarciapablo** [comment]
:+1: I've added the backend label. If we don't have a dedicated backender, I guess someone else in the squad can give it a try and submit a PR for you guys to take a look.

**Comment by alonsogarciapablo** [comment]
> Yes. Backend currently supports: [:updated_at, :size, :mapviews, :likes]

Are [these criteria](https://github.com/CartoDB/cartodb/blob/master/app/controllers/carto/api/visualizations_controller.rb#L62) also the ones we support for datasets?

**Comment by javitonino** [comment]
Yes. Visualization = map or dataset

**Comment by alonsogarciapablo** [comment]
Thanks.

**Comment by alonsogarciapablo** [comment]
# Sorting by name

The [endpoint/action that returns maps/datasets](https://github.com/CartoDB/cartodb/blob/master/app/controllers/carto/api/visualizations_controller.rb#L84-L117) accepts the following [values]((https://github.com/CartoDB/cartodb/blob/master/app/controllers/carto/api/visualizations_controller.rb#L62)) for the `order` param:

`[:updated_at, :size, :mapviews, :likes]`.

In order to sort entries by name, we would just need to add `:name` to that list and `order=name` would magically work ✨.

# Specifying the sort direction

The default "sort direction" for maps and datasets is `:desc`. It's hardcoded [here](https://github.com/CartoDB/cartodb/blob/master/app/controllers/carto/api/visualizations_controller.rb#L95). We can add support for (yet) another parameter called `sort_direction` to that endpoint with two possible values:

`[:asc, :desc]`

A couple of alternatives to add support for this new parameter:

## 1. The "Quick and dirty" option

We can replace the currently harcoded `:desc` literal in the endpoint by the specified sort direction (or the default one.

```ruby
def index
  page, per_page, order = page_per_page_order_params(VALID_ORDER_PARAMS)
  ...
  # Use the provided sort_direction or :desc
  sort_direction = params.fetch('sort_direction', :desc)
  ...
  response = {
          visualizations: vqb.with_order("visualizations.#{order}", sort_direction).build_paged(page, per_page).map { |v|
          ...
  ...
end
```

**Pros:**
- Pretty easy/quick to implement.

**Cons:**
- Most of the logic related to ordering and pagination seems to be encapsulated [here](https://github.com/CartoDB/cartodb/blob/master/app/controllers/carto/api/paged_searcher.rb#L5-L15).
- Other paginated/ordered lists won't be sortable in different directions.

## 2. The "This Seems Like The Right Thing To Do:tm:" option

Most of the logic related to ordering and pagination seems to be encapsulated [here](https://github.com/CartoDB/cartodb/blob/master/app/controllers/carto/api/paged_searcher.rb#L5-L15). We could change the `page_per_page_order_params` so that it accepts and returns a sort direction.

**Pros:**
- Other clients of `PagedSearcher. page_per_page_order_params` could also benefit from this in the future (although that future might never come). For example, the endpoint to retrieve API Keys...

**Cons:**
- `page_per_page_order_params ` is used in [several controllers]( https://github.com/CartoDB/cartodb/search?utf8=%E2%9C%93&q=page_per_page_order_params&type=) so some extra work might be required to update the usage of that method everywhere.

---

@javitonino any other alternative? what do you think is The Right Thing To Do:tm:?

**Comment by javitonino** [comment]
You pretty much said all I was going to :P

I'd just name the parameter something like `order_direction` since the other parameter is called `order`. This way it's easier to see that they work together.

I'd try to go for 2. It's a bit more work, not necessarily in the code (it's just a few more occurrences to modify) but mainly testing we did not break any of the old controllers. 1 is not that bad, so if we are time constrained, we can do that (maybe adding a TODO message to maybe extract it to the helper at some point), but I think the extra effort would be worth it.

**Comment by alonsogarciapablo** [comment]
Thanks @javitonino. I'll go with 1. first so that we have something working and give 2. a try.

**Comment by jesusbotella** [comment]
I closed this issue (https://github.com/CartoDB/cartodb/issues/14385) but ordering is not ready yet, so we need to test the all the ordering cases in conjunction with filters. Just a reminder so we don't forget :)

**Comment by alonsogarciapablo** [comment]
I've been testing this. Ordering by `Date Modified` and `Alphabetically` work 👌.

This is what the filter currently looks like:

![image](https://user-images.githubusercontent.com/390398/48408723-51b90700-e73a-11e8-9735-ad64857c1656.png)

A couple of comments/questions:

1. By default `Date Modified (Last)` is selected. I feel like the copy is not very intuitive (Last and First). In theory, it means that the maps that have been recently modified should be displayed first. I personally find something like `Last Modified (First | Last)` a bit easier.
2. In the filter we use `Date Modified` but then the card shows `Updated X days ago`. Modified vs Updated. Is not consistent. Would be nice to unify?
3. We introduced the `Most Viewed First` filter that we have in the current version. It allows to display most viewed maps first. Users won't be able to change the order direction... They might want to see the maps that are getting less visits first... Should we also allow changing the direction?

Perhaps we can find a way to make it a bit more consistent (eg: all filters have the same options)? @kukukaka what do you think?

**Comment by jesusbotella** [comment]
Gonna change the copy. I'll wait for the final decision on the map views ordering :)

**Comment by jesusbotella** [comment]
Merged! 🎉 

Feel free to reopen it in case you want to say something about this.
