### ISSUE TITLE
[Dashboard] Global Search (Maps & Datasets)

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#14325]
Implement global Map and Dataset search.

We can use the existing `/viz` endpoint with the following parameters so that it returns both maps and datasets: `&types=table,derived&q=<search_term>`.

- [x] Results page shows maps and datasets.
- [x] Search by :tag.
- [x] Search suggests results as the user types.
- [x] Clicking on a tag (Map / Dataset) searches for Maps and Datasets with that tag.
- [x] Paginate results.
- [x] Order results by relevance.

**Comment by alonsogarciapablo** [comment]
Something I noticed is that suggestions are not ordered alphabetically:

![image](https://user-images.githubusercontent.com/390398/49097376-eceaca00-f26c-11e8-87f2-1bb61e057cf0.png)

@gonzaloriestra could you please clarify how is the backend ordering these results? Based on some sort of scoring?

Another thing that would be nice IMO would be to show the number of total results (eg: "VIEW ALL RESULTS (20)". @kukukaka what do you think?

**Comment by gonzaloriestra** [comment]
@alonsogarciapablo there's no order in fact. But the current `order` parameter can be used to sort by `name`, `updated_at`... 

PostgreSQL has some functions to calculate the "score", so it would be also possible to order by the quality of the results: 
https://www.postgresql.org/docs/9.1/textsearch-controls.html#TEXTSEARCH-RANKING

**Comment by kukukaka** [comment]
Score sounds a bit like magic, but I'll try it too :)

Yes, good idea @alonsogarciapablo

**Comment by alonsogarciapablo** [comment]
So, should we use the score or order by `name`?

**Comment by kukukaka** [comment]
I would say score, assuming that it has into account the name. But I think that having it at the searched string at the beginning of the name shouldn't be the only parameter to order the suggestions? My assumption is that score would count the text match, but also the times that you clicked it before, relevance, etc; so an important map that has the string in the title but not at the beginning would score better.

**Comment by gonzaloriestra** [comment]
Maybe we can start with one of the predefined ranking functions by PostgreSQL, which will give better results than random or alphabetical IMO. According to the docs:

>It takes into account lexical, proximity, and structural information; that is, they consider how often the query terms appear in the document, how close together the terms are in the document, and how important is the part of the document where they occur.

And then, if we want, we can try to build our own ranking function by adding more information: dataset likes, better score for title vs description, updated_at (we are not counting visits AFAIK)...

**Comment by alonsogarciapablo** [comment]
Sounds good @gonzaloriestra 👍

**Comment by alonsogarciapablo** [comment]
<img width="383" alt="screenshot 2018-11-29 at 15 33 04" src="https://user-images.githubusercontent.com/390398/49228793-652bc980-f3ec-11e8-8257-df977c0df9f7.png">

**Comment by alonsogarciapablo** [comment]
@gonzaloriestra @jesusbotella, quick question: does the search currently include maps / datasets shared with me? I think it would be 🔝.

**Comment by alonsogarciapablo** [comment]
@jesusbotella I was testing this in staging. I found this:

![image](https://user-images.githubusercontent.com/390398/49229272-6dd0cf80-f3ed-11e8-8af2-4c140d3323fb.png)

☝️ It says "Data" but there are no datasets... Should we display some sort of message?

**Comment by alonsogarciapablo** [comment]
The same happens when there are no Maps:

![image](https://user-images.githubusercontent.com/390398/49229509-f6e80680-f3ed-11e8-9abf-f3323d54d6d4.png)

**Comment by jesusbotella** [comment]
Yes, that's what kike was talking about earlier in Slack. He had just designed it, I need to implement them :).

Thank you for your earlier acceptance, I'll add the padding :).

**Comment by alonsogarciapablo** [comment]
👍👍👍 Looking great now! Great job @jesusbotella.

**Comment by alonsogarciapablo** [comment]
I've created a separate issue suggesting we allow navigating with the up & down keys (https://github.com/CartoDB/cartodb/issues/14507) but that's probably a `v2` type of feature.
