### ISSUE TITLE
[Dashboard] [Datasets] Ordering

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#14320]
Datasets can be ordered by clicking on any of the "column" headers.

Criteria:

  - [ ] Name
  - [ ] Last update
  - [ ] Size
  - [ ] Rows (needs backend work)
  - [ ] Privacy (needs backend work)
  - [ ] ~Usage~ (this will be implemented in https://github.com/CartoDB/cartodb/issues/14424)

**Comment by alonsogarciapablo** [comment]
@kukukaka A couple of questions:
- should users be able to order results in both ascending and descending order (eg: by clicking on the column header multiple times)?
- should users be able to sort by Privacy? How would that work?

**Comment by alonsogarciapablo** [comment]
I realised we will also need some backend work for this one (cc: @ivanmalagon @javitonino). The endpoint to retrieve the datasets doesn't support ordering by name, size, privacy. Also, if we support ordering "ascendingly" and "descendingly" we need to have that options for every ordering criteria (eg: order by last modified ascending and last modified descending).

**Comment by kukukaka** [comment]
@alonsogarciapablo yes, the idea was that if you click once you select descending, if you click a second time it changes to ascending, and the loops. 

About privacy I was thinking about order alphabetically by the name of the attribute (like Kind in Finder).

**Comment by alonsogarciapablo** [comment]
:+1:

**Comment by javitonino** [comment]
Backend-wise: although we only support descending order ATM, adding ascending order is just a minimal change (it's supported in the query part, we only need to add a parameter to the controller).

**Comment by jesusbotella** [comment]
Merged!

**Comment by alonsogarciapablo** [comment]
👏
