### ISSUE TITLE
Endpoint for ghost tables

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/cartodb#14328]
Users of the SQL API & Import API have the problem that when they create or remove tables they must visit their dashboard in order for the metadata to be updated. At least for table creation this is [documented in the SQL API](https://github.com/CartoDB/CartoDB-SQL-API/blob/master/doc/tips_and_tricks.md#why-cant-i-see-my-created-tables-in-my-carto-account).

This is inconvenient if for a example a user is creating/dropping the same table repeatedly (e.g. using it as temporary import storage) and wants to reuse the table name. 

It would be nice to have and endpoint that triggers the ghost tables sync process and that is callable with an api key, so in cases like the one described the user could programmatically update the metadata before a new import. 

/cc @javitonino what do you think? Is there already a better way to do this I'm missing?

**Comment by alrocar** [comment]
Not an issue anymore 👋
