### ISSUE TITLE
Style changes while the map is reloading are not applied 

### ISSUE THREAD

**Issue by gonzaloriestra** [CartoDB/cartodb#14329]
### Steps to Reproduce
1. Open a map with [this dataset](https://github.com/CartoDB/cartodb/files/2709722/dataset.zip)
2. Go to style tab
3. Add labels with the column `name`
3. Increase the point size and before the map is reloaded, uncheck the labels

### Current Result
The map shows the points with the increased size, but with labels, although they appear as unchecked in the form

### Expected result
It should apply both changes

### Browser and version
Chrome 69.0.3497.100 (Official Build) (64-bit)

**Comment by ramiroaznar** [comment]
@gonzaloriestra thanks for reporting but this is a corner case very difficult to replicate (I did btw!). Going to close it because of our focus now is not on Builder.
