### ISSUE TITLE
[Dashboard] [Solutions] Static page to learn about solutions

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#14323]
Introduce a new Solutions section.

https://projects.invisionapp.com/share/WMOI60SNF4Y#/screens/324779780

- [ ] Add Solutions item to the Navigation.
- [ ] Display some info about current solutions.
- [ ] Display a link / form to contact sales.

**Comment by albertoac** [comment]
The link `Talk to us` should link to the email address, to a contact form of website or somewhere else? 
cc/ @kukukaka

**Comment by kukukaka** [comment]
I would suggest to open https://carto.com/request-live-demo/ in a _blank

**Comment by alonsogarciapablo** [comment]
@albertoac It looks grrreat! 👏 👏 👏 

I didn't see your question, sorry:

> The link Talk to us should link to the email address, to a contact form of website or somewhere else?

It's a great question. I'm asking to see what's the best thing to point users to.
