### ISSUE TITLE
[Dashboard] [Map] Favorite maps

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#14332]
Ability to favorite a map. We can re-purpose the ❤️  functionality that we already have.

- [x] As the user mouses over a map, a grayed out star symbol is shown. Users can click on the star to favorite that map.
- [x] Already favorited maps display a yellow star.

**Comment by alonsogarciapablo** [comment]
@javitonino @ivanmalagon Can we re-purpose existing LIKES for this? Otherwise we will need backend work for this. If we reuse the LIKE feature, do you guys think we should remove it from the public pages as part of this?

@kukukaka should favourite maps always apear first? even if the user has ordered maps by other criteria (eg: Last updated at)? I would say favourite maps should be the ones that are featured in the "Dashboard" page and perhaps in the Your maps section, but as soon as users re-order the list, they are mixed with the rest of the maps... What do you think?

**Comment by javitonino** [comment]
Maybe. Reusing `likes` is probably a good idea if we want to allow favoriting maps from other users in the org. If you can only favorite your own maps, there are better solutions that we should consider.

**Comment by alonsogarciapablo** [comment]
I was just going to ask about that... should users be able to favorite other people's maps (eg: a map that has been shared with me)?

**Comment by kukukaka** [comment]
This is coming from the user need to better organize their maps. As the default ordering is based on when the map was added to the users dashboard the favourite was trying to give them a way of self-organizing things based on the relevance they have for him (difficult to guess by us and something more simple than tagging content).

It could be done as a hidden tag or something like that, but I think that other people favouriting your stuff breaks a bit the goal of the feature. 

@alonsogarciapablo I'm ok if we just show the favourites in the default states and don't highlight them once the user  filter or changes the order criteria. I'm curious if people would use the fav so much they would want to filter favourites too, but I guess we are quite far from there.

**Comment by javitonino** [comment]
> but I think that other people favouriting your stuff breaks a bit the goal of the feature.

I meant you favoriting other user's stuff (in the same org), e.g: a dataset that is owned by other user in the org but that you can see. And disabling the part when you can favorite arbitrary stuff (from users you don't know)

**Comment by kukukaka** [comment]
Ok. I was thinking you were talking about favouriting a shared object and
making it favourite also in other people dashboards :)

>

**Comment by alonsogarciapablo** [comment]
From what I can tell, I can now like:
1. Maps that I have created.
2. Maps that have been shared with me, no matter if they are public, private, etc.
3. Maps that are public, from any user.

So the question is... should I only be able to favorite my maps? Or also maps that been shared with me? Or public maps also? And also, if we re-purpose existing likes... will liked maps become favorites?

I think we can remove the social aspect of this (3.) but we can keep 1. and 2. Someone within your organization might share a map with you and you might want to have it at hand (eg: in the dashboard) because you use it all the time. What do you think? Thanks!

**Comment by jesusbotella** [comment]
I was going to close this issue but seems like you're still debating some things, right? Feature is done and merged :)

**Comment by alonsogarciapablo** [comment]
You should only be able to Favorite your maps or maps that have been shared with you by anyone at your organization. Feel free to close the issue @jesusbotella.
