### ISSUE TITLE
[Dashboard] [Navigation] Dashboard ONLY

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#14341]
New navigation in the new Dashboard section. Navigation will be updated in other pages (eg: account pages, etc.) in https://github.com/CartoDB/cartodb/issues/14312.

It should initially have the following menu items:

- ~Home~ (this will be added when we implement the Dashboard)
- [x] Solutions
- [x] Maps
- [x] Data
- [x] CARTO Icon
- [x] Search box
- [x] Avatar
  - [x] Your account
  - [x] Your organization (only for org admins)
  - [x] API Keys
  - [x] Public profile
  - [x] Notifications (X)

  - [x] Log out ->

**Comment by alonsogarciapablo** [comment]
@csubira unless you're already working on it... I think we can extract the new Account dropdown and the new Notification page to separate issues. Are you working on any of those? Apart from those, what's left? Thank you!

**Comment by csubira** [comment]
@alonsogarciapablo when you mention "Account dropdown", do you mean the dropdown with the user information? _(Older version in the image below)_ If that's it, it's included in this PR.

![screen shot 2018-11-15 at 15 52 08](https://user-images.githubusercontent.com/26403479/48560608-7eae1b00-e8ee-11e8-85eb-f64727c57df8.png)

However, the notification page, as you said, I assumed that was a separate issue and I haven't been working on it.

**Comment by alonsogarciapablo** [comment]
@csubira yes. I was referring to that dropdown. Happy to hear is already in progress 👏 👏 👏 

Don't worry about the notifications page. I will open a separate issue.

**Comment by jesusbotella** [comment]
Merged! 🚀

**Comment by alonsogarciapablo** [comment]
Vamos @csubira! 👏 👏 👏
