### ISSUE TITLE
[Dashboard] [Footer] Update footer in all private pages.

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#14342]
Update the footer to [the new one](https://github.com/CartoDB/cartodb/issues/14327) in all private pages. Only users with the feature flag enabled should see the new footer.

**Comment by alonsogarciapablo** [comment]
I found that we're showing the "As a paying customer..." banner on top of the footer. We should remove it 👇:

![image](https://user-images.githubusercontent.com/390398/52856643-46082280-3125-11e9-95a6-16aca874079d.png)

**Comment by jesusbotella** [comment]
Merged!

**Comment by alonsogarciapablo** [comment]
💪
