### ISSUE TITLE
Design New MU admin page

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#1434]

**Comment by carlostallon** [comment]
Here it is the administration pages to:
- Users
- Organizations
- Plans
- Features

![01 dashboard - admin - users](https://cloud.githubusercontent.com/assets/1712650/5742196/b1f07dde-9c10-11e4-9b8a-94afbd5c7196.png)
![02 dashboard - admin - organizations](https://cloud.githubusercontent.com/assets/1712650/5742198/b1f28ebc-9c10-11e4-9757-71a37fdd74f9.png)
![03 dashboard - admin - plans](https://cloud.githubusercontent.com/assets/1712650/5742197/b1f29f88-9c10-11e4-9fd5-2471231b7d9a.png)
![04 dashboard - admin - features](https://cloud.githubusercontent.com/assets/1712650/5742199/b1f49f2c-9c10-11e4-8ad5-0f4dffc596da.png)

**Comment by carlostallon** [comment]
Mockups for MU admin:
- Plan and account settings in different tabs
- Public dashboard and account settings merged in the same tab
- Pending billing info

![organization - account](https://cloud.githubusercontent.com/assets/1712650/5917360/256bc90c-a61c-11e4-973f-c2974da23403.png)
![organization - plan](https://cloud.githubusercontent.com/assets/1712650/5917361/256c073c-a61c-11e4-84a4-f3e9eb981baa.png)
![organization - seats](https://cloud.githubusercontent.com/assets/1712650/5917359/2568db16-a61c-11e4-889c-1e044d0917ea.png)

**Comment by saleiva** [comment]
Hey, just a few things!

In general I like it, and I'm pretty glad that the visual language we are creating is working so far! 

-It's just a but weird the alignment on the left that leaves the right side a bit too empty.
- Remember we need a way to specify the 'featured map' for the public profile of an org, and a user.
- Would you not put the Account Settings section the first one on the menu?
- I'd move the DELETE button to the left. And give a red tone to it... (Sorry, can't avoid!!)
- Wouldn't we use the Plan tab to suggest upgrading directly instead of adding an extra step? I can imagine the upgrade options there.
- Remember we are not using bold on the menus and I'd use the taller button that we have on the dashboard.
- The first time I looked at the seat lists I missed the "ADD NEW SEAT" square completely. Not sure why...
- Maybe we can play with a better CTA for upgrading on the user list, not sure...

Cheers!

**Comment by carlostallon** [comment]
New mockups with almost all the feedback.

![01 organization - profile](https://cloud.githubusercontent.com/assets/1712650/5940335/9805cee2-a70a-11e4-9a1a-ee0589fbfe29.png)
![02 organization - account](https://cloud.githubusercontent.com/assets/1712650/5940336/9807b8a6-a70a-11e4-99f5-5b1d940ce39b.png)
![03 organization - seats](https://cloud.githubusercontent.com/assets/1712650/5940337/98089b9a-a70a-11e4-85fb-79d7e986f912.png)
![04 organization - seat profile](https://cloud.githubusercontent.com/assets/1712650/5940339/980c4268-a70a-11e4-9d87-e94b8d98cb83.png)
![05 organization - plan](https://cloud.githubusercontent.com/assets/1712650/5940338/980bc89c-a70a-11e4-876b-465cd98f709f.png)

**Comment by saleiva** [comment]
Like it a lot.

- I personally hate that border/shadow on the icons :cry: 
- The only thing I see weird is alignement on the first and the last screens.
- I'd make the upgrade your account button more visible in the last one and maybe call it "CHANGE YOUR PLAN"

Great job!

BTW, we should reuse as much as possible for the non multi-user accounts. You have it in mind?

S.

**Comment by saleiva** [comment]
Also, I'd use the dark blue instead of the light one when configuring the user quota and design how it will be changed.

**Comment by carlostallon** [comment]
* I personally hate that border/shadow on the icons
Fixed

* The only thing I see weird is alignement on the first and the last screens.
Last one fixed, first one now with hints, not perfect yet, but helps :smile: 

![01 organization - profile](https://cloud.githubusercontent.com/assets/1712650/5942096/97cecbd0-a715-11e4-9c4c-516625e8c5f6.png)
![05 organization - plan](https://cloud.githubusercontent.com/assets/1712650/5942097/97d13366-a715-11e4-88b7-16f0b6731155.png)

**Comment by carlostallon** [comment]
* Also, I'd use the dark blue instead of the light one when configuring the user quota and design how it will be changed:

![06 organization - change user quota](https://cloud.githubusercontent.com/assets/1712650/5942497/4a31f714-a718-11e4-8863-165bc4c0fe8f.png)
