### ISSUE TITLE
[Dashboard] [Dataset] Favorite dataset

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#14357]
Ability to favorite a dataset. We can re-purpose the ❤️  functionality that we already have.

- [x] As the user mouses over a dataset, a grayed out star symbol is shown. Users can click on the star to favorite that dataset.
- [x] Already favorited datasets display a yellow star.
- [ ] Favorited datasets are always displayed at the top of the list.

**Comment by jesusbotella** [comment]
Waiting for Dataset card acceptance to check that everything works.
