### ISSUE TITLE
[Dashboard][Maps] Retrieve visualization data from store

### ISSUE THREAD

**Issue by jesusbotella** [CartoDB/cartodb#14353]
We need visualization data for Maps page, so we need to retrieve visualization data and set it to the Maps Store module.

The store will have the following structure:
```js
{
  isFetching: false,
  isFiltered: false,
  filters: {
    ...
  },
  list: {
    ...
  }	
}
```

**Comment by ivanmalagon** [comment]
LGTM

**Comment by jesusbotella** [comment]
Merged into Feature Branch!
