### ISSUE TITLE
Possible SQL Injection Risk

### ISSUE THREAD

**Issue by robatussum** [CartoDB/cartodb#14350]
### Context
*Please explain here below what you were doing when the issue happened*
Apparent SQL Injection Risk for URLs matching the following regex:

http[s]://+.carto.com/api/v*/sql?q=+

Where + is one or more characters.
Where * is zero or more characters.
Note: ? is already in use as part of a valid REST query and would be confusing to mix its use for the above regex definition.

Tested for SELECT - fortunately querying information_schema.tables is forbidden.

Unable to test INSERT, DELETE queries, as it is not my site (state government site which will remain nameless). 

**Core Issue**, _have those particular SQL queries been allowed/blocked?_

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Load website with cartodb map in your favourite browser
2. (Right click) Inspect page source
3. Navigate to Network tab in Inspector
3. Reload page
4. Watch out for: sql?q=
5. Click on row 
6. Note Url - typically https://*name-of-site*.carto.com/api/v2/sql?q=*RAW SQL HERE!!!*
7. Copy root of URL https://*name-of-site*.carto.com/api/v2/sql?q=
8. Form your own SQL using %20 for space - JQuery callback not required as part of URL
9. Paste to URL bar
10. Hit enter
11. If valid SQL and HTTP [REST] GET, requested data will return

### Current Result
*Please describe here below the current result you got*
Data will return for valid SQL, not tested for SQL Injection, i.e. INSERT or DELETE, as it is a production site under state government control.

### Expected result
*Please describe here below what should be the expected behaviour*
Raw SQL should not be transmitted from a client machine to a server

### Browser and version
*What internet browser (Chrome, Firefox, etc) and version were you using and version*
Any and all browsers

### Additional info
*Please add any information of interest here below*
[https://www.owasp.org/index.php/Testing_for_SQL_Injection_(OTG-INPVAL-005)#How_to_Test](url)

**Comment by javitonino** [comment]
This is a feature https://carto.com/developers/sql-api/support/tips-and-tricks/

**Comment by javitonino** [comment]
This is an intended feature. Using SQL API you can run arbitrary queries in your database. You need an API Key to do any write operation or sensitive read.

https://carto.com/developers/sql-api/support/tips-and-tricks/
