### ISSUE TITLE
[Dashboard] Update Help Center Entries

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#14361]
As part of the new dashboard, we have to update any existing materials in the Help and Developer centers:

https://docs.google.com/spreadsheets/d/1AY4D5Q-5AXvl21vRp87t6BiAVYqMNj4neAYPa41TWW4/edit#gid=0

**Comment by alonsogarciapablo** [comment]
There are some articles/questions that refer to the Dashboard and still haven't been migrated to the new Help and Developer Center in https://github.com/CartoDB/help/issues/130.

**Comment by ramiroaznar** [comment]
@alonsogarciapablo these old materials are already merged.

**Comment by ramiroaznar** [comment]
I have created a subcategory for the dashboard:

![image](https://user-images.githubusercontent.com/5215798/47557893-26e54b00-d912-11e8-9914-8bb480ba39d2.png)

I will add to your initial comment, the articles that refer to the Dashboard.

**Comment by ramiroaznar** [comment]
@alonsogarciapablo I have added a couple of items to the list to be updated/added

**Comment by alonsogarciapablo** [comment]
Thank you @ramiroaznar. We'll be working on this this week 💪

**Comment by ramiroaznar** [comment]
In fact, we should review these results: https://carto.com/help/search/?query=dashboard

**Comment by alonsogarciapablo** [comment]
> In fact, we should review these results: https://carto.com/help/search/?query=dashboard

I'm reviewing all these entries ☝️. Something I noticed is that we use the word "Dashboard" to refer to different concepts. For example:

![image](https://user-images.githubusercontent.com/390398/53166816-a50ee100-35d6-11e9-81d7-44c079d83953.png)

It seems we're using Dashboard here to describe a Builder "Map". This might be confusing for our users. Should we change these @CartoDB/hc-managers?

**Comment by alonsogarciapablo** [comment]
Here's an example: https://carto.com/help/building-maps/customize/#introduction-

> CARTO Builder dashboards are a holistic experience, so their elements should be balanced visually.

**Comment by inigomedina** [comment]
> Should we change these @CartoDB/hc-managers?

Absolutely. Either by removing it (`Customize Widget Colors`) or by changing it to Builder (`Customize Widget Colors in Builder`). Or if you have better ideas, just share them here. 😃

**Comment by ramiroaznar** [comment]
Yes, you are right. We used to call dashboards to Builder maps. I am ok if you want to replace those terms.

**Comment by alonsogarciapablo** [comment]
They are actually called Maps on the UI so we should unify. I've compiled a list of entries that need to be updated [here](https://docs.google.com/spreadsheets/d/1AY4D5Q-5AXvl21vRp87t6BiAVYqMNj4neAYPa41TWW4/edit#gid=0). There are quite a few.

**Comment by jsanz** [comment]
I can't access the spreadsheet @alonsogarciapablo but let me know if you need help from the Support Team on this task.

**Comment by alonsogarciapablo** [comment]
Sorry @jsanz, the file is private. You should have access now.
