### ISSUE TITLE
Let edit tags and description within the datasets/maps item

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#1437]
If there is no description or tags, that field should be an "input" that lets users add any text (description) or any tag (separated by commas). Once it happens, description or tag/s are saved, and element appears as text. The same on maps

![screen shot 2015-04-01 at 16 06 12](https://cloud.githubusercontent.com/assets/132146/6942650/541c1686-d889-11e4-85ad-a5e58b9f8d82.png)

**Comment by alonsogarciapablo** [comment]
@xavijam can you provide more info about this please? thx

**Comment by xavijam** [comment]
better description

**Comment by xavijam** [comment]
aaaand design :)

**Comment by saleiva** [comment]
edited!

**Comment by alonsogarciapablo** [comment]
thx!

**Comment by alonsogarciapablo** [comment]
I have a couple of questions on this one:

1. How does the input text / textarea should look like for both the description and tags? Should it just be a textarea that is submitted when the user hits enter? What happens with lines breaks? Should it have a submit button?
2. Tags are now displayed below the description (not as displayed in the attached mockup). I assume the mockup is wrong.

Please clarify @saleiva.

**Comment by saleiva** [comment]
1. Line breaks should be done when clicking cmd+enter - IMO.
2. Where?  You mean in the maps? In the datasets view? You forgot to attach the mockup :P

**Comment by alonsogarciapablo** [comment]
Sorry, I was referring to the screenshot you attached. But I was confusing the maps and datasets view. So let's forget about 2. and focus on 1. How do the inputs/textareas will look like? Do we have a mock for that somewhere? Thx

**Comment by saleiva** [comment]
Preparing it for you :)

**Comment by saleiva** [comment]
![dashboard - user private - maps - editing](https://cloud.githubusercontent.com/assets/132149/7028114/121a3982-dd54-11e4-9827-629e35917bda.png)

Done in the dashboard sketch file

**Comment by alonsogarciapablo** [comment]
Thanks!

**Comment by alonsogarciapablo** [comment]
@saleiva Thanks for the screenshots. I don't quite get the yellow background and horizontal lines... Are those visible or just there to help?

I almost have the editable description :). These are the things I've implemented so far:
- Clicking "Add description..." toggles the textarea.
- Hitting Esc or clicking outside of the textarea displays the link again.
- Hitting cmd+enter introduces a newline in the textarea.
- Hitting enter saves the field (only if the textarea is not empty).
- Length of the field is limited to 200 chars.
- Markdown is supported and HTML is sanitized.

This is how it's looking right now:

![editable](https://cloud.githubusercontent.com/assets/390398/7086940/93bb7ba2-df86-11e4-87b2-803848570b15.gif)

**Comment by saleiva** [comment]
Looks great.
The point of the style is to not have a square about the text that moves everything else when appearing. The idea is to give it that 'notebook' style by adding the yellow bkg and the lines.

**Comment by alonsogarciapablo** [comment]
:+1:

**Comment by alonsogarciapablo** [comment]
Everything is looking great so far. The only place where this looks a bit funky is when editing tags of a dataset:

![captura de pantalla 2015-04-14 a las 16 50 20](https://cloud.githubusercontent.com/assets/390398/7139404/70c6ee0e-e2c6-11e4-8731-b2fb44fd5f2a.png)

@saleiva @xavijam: Should we make the editable area a bit narrower? Is it okay to align the text on the right?

**Comment by xavijam** [comment]
IMHO, it should be narrower. About the direction... difficult, because it is displayed aligned to the right, but we should type them at left... Let's try with this option and then we will have time to change later.

**Comment by alonsogarciapablo** [comment]
Also, I decided not to use the tag-it plugin because it didn't add any value here... Do you guys think that we should specify that tags should be separated with commas? We could use the placeholder for this.

**Comment by alonsogarciapablo** [comment]
This is ready for CR! :sweat: 

@xavijam @viddo can you please CR? thx!

**Comment by viddo** [comment]
Where is the PR/the changes? Also, it makes it easier to test if you deploy on a staging. :)
