### ISSUE TITLE
[Dashboard] [Maps / Datasets] Order by "Favorites first"

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#14372]
- [x] Add "Order by Favorites First" option to `/viz` endpoint. It should order maps / datasets by "Favorites + Updated at first".
- [x] Your Maps:
  - [x] Add "Favorites first" ordering criteria.
  - [x] List of maps is ordered by "Favorites first" + "Last updated at" by default
- [x] Your Data:
  - [x] Add "Favorites first" ordering criteria.
  - [x] List of datasets is ordered by "Favorites first" + "Last updated at" by default
- [x] Remove "Favorited (X)" filter from dropdown.

Here's a screenshot of the new filter:

![screenshot 2018-10-29 at 16 46 25](https://user-images.githubusercontent.com/390398/47661884-324aa780-db9a-11e8-87c3-5cb01078ca9a.png)

**Comment by javitonino** [comment]
Some of the problems with this:
- We have a filter by liked by you, but not an ordering
- We have an ordering by `likes` but it is an `OffdatabaseAdapter` one, so we cannot combine it with others easily
- We have no way (at VQB nor at controller helpers) to specify multiple orderings.

So there's quite a lot to do here. The proper solution would be to use any kind of combination of orderings.

**Comment by gonzaloriestra** [comment]
I'm adding `favorited` as a new ordering option in /viz endpoint, as well as multiple ordering (CR pending).

So the way to get the favorited first and also ordered by date will be to request: `order=favorited,updated_at&order_direction=desc,desc`.

**Comment by alonsogarciapablo** [comment]
Great! Thank you @gonzaloriestra! Now we need to work on the frontend part 😅!

**Comment by jesusbotella** [comment]
I think we talked with @kukukaka to remove Favourites filtering. I think this is the appropriate PR to do it. Do you want me to do it?

**Comment by alonsogarciapablo** [comment]
I updated the list of tasks in the description but I would like @kukukaka to make sure what I wrote makes sense.

**Comment by kukukaka** [comment]
@alonsogarciapablo yes, I think it makes sense. 👌

**Comment by alonsogarciapablo** [comment]
Quick question @jesusbotella will this new default ordering also be automagically applied to "Your Maps" and "Your Datasets" modules on the homepage (ie: is the code / logic shared)? Thank you! (cc: @IagoLast)

**Comment by jesusbotella** [comment]
Yes! It should, we are sharing the same code for both ;)

**Comment by alonsogarciapablo** [comment]
Alright!

**Comment by alonsogarciapablo** [comment]
This is working as expected! 👏👏👏
