### ISSUE TITLE
[Dashboard] [Maps] "Shared with you" maps include both locked and unlocked maps

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#14386]
- [x] When users select "Shared with you", they should see all the maps that have been shared with them (both locked and unlocked maps).
  - [x] Endpoint needs to include all maps. Some new params _might_ be required.
  - [x] Frontend might need to request maps differently (eg: using new params or different values).

cc: @jesusbotella @javitonino

**Comment by gonzaloriestra** [comment]
The backend is working as expected. The problem is that the request from the UI is including the parameter `locked=false`. Removing it should fix it. cc: @jesusbotella
