### ISSUE TITLE
[Dashboard] Make Dialog tests work

### ISSUE THREAD

**Issue by jesusbotella** [CartoDB/cartodb#14399]
We're having issues while testing code which imports the Builder Dialogs in the new dashboard, because the code uses `require.context` from Webpack which is not supported in Jest.

We need to fix that in order to be able to test code concerning Builder Dialogs.

**Comment by alonsogarciapablo** [comment]
Can we close this @jesusbotella?

**Comment by jesusbotella** [comment]
Yes!
