### ISSUE TITLE
[Dashboard] Confusing UI when name is collapsed

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#14408]
Spotted in staging

When a map card is selected and the text has ellipsis, the ellipsis seems like the quick actions button.

![image](https://user-images.githubusercontent.com/1078228/48125948-3b193880-e280-11e8-8ffa-52ad8db9a653.png)

**Comment by jesusbotella** [comment]
@albertoac did a very good job on this issue and we fixed a few other things :)

![screen shot 2018-11-16 at 10 18 30](https://user-images.githubusercontent.com/4319728/48612333-05173b00-e989-11e8-88a5-31063daf7195.png)
