### ISSUE TITLE
[MFA] user management

### ISSUE THREAD

**Issue by alrocar** [CartoDB/cartodb#14403]
Same as https://github.com/CartoDB/cartodb/issues/14347 but for individual users.

- https://projects.invisionapp.com/share/M2ORG0NUZPD#/screens/327520181

**Comment by alrocar** [comment]
We are thinking on avoiding this issue -> https://github.com/CartoDB/cartodb/issues/14404

And go straight with the `enabled` attribute in this way:

We have three states:

- Nonexistent MFA: there's no record in `user_multifactor_auths`
- Existent MFA but needs setup: there's a record in `user_multifactor_auths` with `enabled=false`. This state is used to redirect the user to the `multifactor_authentication` endpoint and show the QR Code to the user to configure the Authenticator app.
- Existent MFA and is active:  there's a record in `user_multifactor_auths` with `enabled=true` (after the user enters the first verification code)

In terms of the UI:

- When the user activates the checkbox -> create a record in `user_multifactor_auths` with `enabled=false`
- When the user deactivates the checkbox -> remove the corresponding record
- When the user enters the first code -> set `enabled=true` (_this is already done_)

We may need to add a `UNIQUE` constraint to the table (user_id, type, enabled).

Thoughts?

**Comment by gonzaloriestra** [comment]
As we talked before, I can't find any problem with this strategy. I just think the code would be clearer with a status field, but I agree on avoiding it.

**Comment by alrocar** [comment]
OK, let's go with the `enabled` attribute. This way we avoid being blocked by #14404. Thanks!
