### ISSUE TITLE
Filter and search should be available for common data

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#1442]
Search by item or filter by stats, likes, updated_at...

@kartones details:
- Currently Common Data works as a facade that reads table listings from a special cartodb account (`common_data`), filtering by tags as categories, etc.
- To import, it generates an Import API call by calling the SQL API to perform a ```SELECT *``` indicating an export in SHP format.
- Recent improvements and additions to `/api/v1/viz/` endpoint allow more filters, and even lazy filtering for non base visualization orderings (e.g. order by likes). Still, all of them rely either on the metadata DB's `Visualization` model or on associated models (`Like` and `SharedEntity`).

Brainstorming (WIP):
- perform normal search + common_data search, joining upon search itself. Then paginate. Issue here is both the ORM and the "Visualizations backend" will probably get on the way and add difficulties.
- perform normal search + common data search as an "additional search source". Order results before setting up Visualization::Member items, then paginate (as currently with lazy filters) and instantiate & return.

**Comment by Kartones** [comment]
@xavijam As santana is on vacations can you confirm this is a new endpoint and not to mess up with normal endpoint? (this has a few implications)

**Comment by javisantana** [comment]
I think there is something wrong here. Basically what this ticket says is "search should show common data tables"

There are two major issues here:
- the design does not match with data model: we store user visualizations 
- this is a deep integration with a 3rd party services (provided by us) in cartodb open source product

So there are two solutions here:

- change design so each thing goes in the right place
- invest more time in doing external datasets as local ones ( @andrewxhill proposed this)

cc @saleiva @piensaenpixel @carlostallon

**Comment by saleiva** [comment]
2nd option. As data discoverage is one of the biggest issues we have with
onboarding

**Comment by javisantana** [comment]
nice, so, let's move this to a CRFC (cartodb request for comments) haha

**Comment by javisantana** [comment]
related: https://github.com/CartoDB/cartodb/issues/1424
