### ISSUE TITLE
[MFA] enable/disable MFA from EUMAPI

### ISSUE THREAD

**Issue by alrocar** [CartoDB/cartodb#14425]
We are adding support for creating/removing/reseting MFA from [EUMAPI](https://carto.com/help/your-account/enterprise-api/)

Proposal:

## Create user with MFA

Request body
```json
{
  "username": "org-user",
  "viewer": true,
  "org_admin": false,
  "email": "org-user@sample-org.com",
  "password": "secret!",
  "api_key": "1a9eda3a51e43f8aa52e1fbcb949aaddee3b1d9f",
  "multifactor_auths": [{ "type": "totp" }]
}
```

MFA is created with `enabled = false` any other attributes are ignored. Using an array in case we support more types in the future.

## Update user and create MFA

Request body
```json
{
  "username": "org-user",
  "viewer": true,
  "org_admin": false,
  "email": "org-user@sample-org.com",
  "password": "secret!",
  "api_key": "1a9eda3a51e43f8aa52e1fbcb949aaddee3b1d9f",
  "multifactor_auths": [{ "type": "totp" }]
}
```

MFA is created with `enabled = false` any other attributes are ignored. 

## Show user

Response contains the available MFAs for the user and the status

```json
{
  "id": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "username": "org-user",
  "email":"org-user@sample-org.com",
  "avatar_url":"//example.com/avatars/avatar_stars_blue.png",
  "base_url":"http://sample-org.carto.com/u/org-user",
  "quota_in_bytes":104857600,
  "db_size_in_bytes":0,
  "table_count":0,
  "public_visualization_count":0,
  "all_visualization_count":0,
  "viewer":false,
  "org_admin":false,
  "multifactor_auths": [{ "type": "totp", "enabled": false }]
}
```

## Reset MFA

A specific action for a user that resets all the available MFAs.

```
<org>.carto.com/u/<org_owner>/api/v2/organization/<org>/users/org-user/reset_multifactor_auths
```

*EDIT: Forgot how to disable MFA*

## Disable MFA

A specific action for a user that disables all the available MFAs.

```
<org>.carto.com/u/<org_owner>/api/v2/organization/<org>/users/org-user/disable_multifactor_auths
```

**Comment by alrocar** [comment]
Thoughts? ^^ @javitonino @gonzaloriestra

**Comment by javitonino** [comment]
What happens if you update a user using the request you wrote and the user already had MFA configured?

**Comment by alrocar** [comment]
Nothing, for me is the same as if you try to update the e-mail but send the same one the user has in the database.

**Comment by gonzaloriestra** [comment]
I think it would also be a bit weird to have an endpoint where you can change the enabled state, but only to false.

I slightly prefer the initial proposal.

**Comment by javitonino** [comment]
I was trying to figure out what feels weird about this approach, and it somehow that it breaks the REST model. That doesn't have to be bad, but at least we have to think about it.

The think is, you are passing an array of models (MFAs) to this endpoint. And you are having different things going into the endpoint than out of it. And finally, you need a third endpoint to reset MFA, which will change an attribute that seems like it could be set in the request.

I don't know, I think it will break many developer assumptions if they are used to working with REST, since it's kind of weird. OTOH, creating endpoints for MFA feels a bit like overkill, and it is nice to be able to fully update the user in a single request. :thinking:

**Comment by gonzaloriestra** [comment]
I'm not sure we break the REST compliance: we have the same data going in and out, but we are just ignoring one field...

But I hadn't realised that we could avoid the reset endpoint, so I think I change my vote :slightly_smiling_face:

**Comment by alrocar** [comment]
Maybe we can just use the `enabled=false` attribute to reset. So:

- if `enabled=true` we raise an unsupported parameter error or something like this.
- if `enabled=false` and there's no MFA, we create one.
- if `enabled=false` and there's MFA we reset it.

Take into account that we still need to disable completely MFA. For this case we can allow a delete on:

```
<org>.carto.com/u/<org_owner>/api/v2/organization/<org>/users/org-user/multifactor_auths/
```

**Comment by javitonino** [comment]
> Take into account that we still need to disable completely MFA. For this case we can allow a delete on:

With the current proposal, I assumed an empty array to disable MFA. Isn't that the plan?

**Comment by alrocar** [comment]
mmm it could be yes

**Comment by javitonino** [comment]
From the discussion, two suggestions:

1. Everything in the user model. PUT /user with
  - empty mfa array to disable
  - mfa with state disabled to setup
  - mfa with state enabled -> error
2. Different MFA model
  - POST /user/mfa/totp to enable
  - DELETE /user/mfa/totp to disable

These are consistent in the sense that either all MFA operations are done in the /user endpoint, or all of them are in the /mfa endpoint. 1 is maybe more comfortable to edit all the user at a time, and 2 is maybe more rest-ish. But both should work.

**Comment by alrocar** [comment]
After talking with @javitonino we decided to go with option 2 since it has less implementation implications.
