### ISSUE TITLE
[Dashboard] [Maps] Display number of views in map card

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#14430]
Maps should display the number of views:

<img width="319" alt="screenshot 2018-11-13 at 11 46 33" src="https://user-images.githubusercontent.com/390398/48408541-deaf9080-e739-11e8-9e2e-fb82bbefa7ad.png">

**Comment by alonsogarciapablo** [comment]
We will only be able to show the number of views in the last 30 days, so we might need to change the copy or adapt the design a bit (eg: adding a new "line" with the views?). @kukukaka what do you suggest? Thank you!

**Comment by kukukaka** [comment]
I would suggest to change the copy and use "xxx views (30 days)". Adding another line would make some cards to have different heights, and making the copy longer would not allow us to have at least 6 digits before having to wrap the text.

**Comment by jesusbotella** [comment]
The limit is 9999 with password protected maps 🤔

**Comment by jesusbotella** [comment]
Merged! 🎉
