### ISSUE TITLE
[Dashboard] Active order is not selected in the Data page

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#14449]
**Steps to reproduce:**

1. Visit the Data page.
2. Change the order of the datasets

**Current result:**

Datasets are ordered correctly, but the active order is not selected in the dropdown. It always have the following state:

![image](https://user-images.githubusercontent.com/390398/48619541-271ab880-e99d-11e8-907a-9ad413575dac.png)

**Expected result:**

Actual order should be "selected" in the dropdown.

cc: @jesusbotella

**Comment by jesusbotella** [comment]
Ordering is not supported yet in Data Page. We left it there but as there are not supported orderings in the API we didn't implemented the whole thing yet.

**Comment by alonsogarciapablo** [comment]
ok, closing this then. Sorry!
