### ISSUE TITLE
[Dashboard] New Notifications Page

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#14444]
- [ ] Implement new notifications page.
  - [ ] Page shows the last 20 notifications for the users.
  - [ ] As soon as the user opens the notifications page, any new notification will be marked as "read".
- [x] Link notifications item in the new account dropdown to the new page.

**Comment by csubira** [comment]
Working with @IagoLast in the implementation of the page, there are some questions that came up:

- Is there a design or a template for an empty notifications state (as we have in maps or datasets)?
- How/When are the notifications marked as read, once we open/visit the notifications page?
- The information we get about a notification is the following:
```
{
      'id': '091a04a7-28d6-4fcf-bd8a-b1c34842bdb4',
      'icon': 'alert',
      'html_body': '<p>Test notification 1</p>',
      'received_at': '2018-11-16T17:11:42.285Z',
      'read_at': '2018-11-16T19:15:42.285Z'
 }
```
There is no information to fill the origin field (_IKEA ADMIN_) in the design:
![screen shot 2018-11-20 at 18 46 24](https://user-images.githubusercontent.com/26403479/48792537-cc62c300-ecf4-11e8-8621-0443512d73dc.png)

Should we remove it? Any other option?

**Comment by kukukaka** [comment]
Yes, they should be marked as read once the user opens the notifications screen. I guess there could be the case when some unread notifications could be below the fold, but I wouldn't over complicate things right now.

Yes, we can remove the Author if we don't have it right now, and it's too much effort (I guess most organizations only have one admin, right?). 


Btw, do we show notifications for not Enterprise users or should we hide them @alonsogarciapablo?



![image](https://user-images.githubusercontent.com/8354661/48801455-b660fc80-ed0c-11e8-942f-841616003617.png)

**Comment by IagoLast** [comment]
Little comment:

Do we have to care about possible XSS injection in the notification body? we are using [v-html](https://vuejs.org/v2/guide/syntax.html#Raw-HTML) and malicious content could be injected.

A solution could be changing the API or adding a new field with only the text.

**Comment by jesusbotella** [comment]
We can use any HTML sanitizer to avoid XSS

**Comment by alonsogarciapablo** [comment]
Sorry for not having replied to this earlier.

> Btw, do we show notifications for not Enterprise users or should we hide them @alonsogarciapablo?

In the actual version. Everyone sees the notifications bell, even though I think notifications can only be sent by Organization users to anyone in their orgs:

![image](https://user-images.githubusercontent.com/390398/48952478-91ee6580-ef42-11e8-9007-a71752f65e70.png)

In the past, we've been able to manually send notifications to everyone, to announce certain things so I suggest we keep this for everyone in case we decide to start sending things like product updates.

**Comment by alonsogarciapablo** [comment]
The way it works now is that notifications can only be seen once. Once they are viewed by a user, they are "discarded" and no longer displayed.

![notifications](https://user-images.githubusercontent.com/390398/48952650-353f7a80-ef43-11e8-8002-c7bd668ada60.gif)

From what I understood, right now there's no endpoint to retrieve all user notifications (read and unread). This means users would only see notifications once, which is kind of weird... don't you think?

Should we make the necessary backend changes to retrieve all notifications?

**Comment by jesusbotella** [comment]
Yes, it is :(
I think we should, because the way that the flow was thought requires to see all notifications, whether they had been read or not.

**Comment by alonsogarciapablo** [comment]
Ok. Let's do it then! It shouldn't be that hard to change the notifications endpoint. We can always ask @gonzaloriestra for help if we get stuck or something and he can help with the CR. What do you guys think?

**Comment by alonsogarciapablo** [comment]
Talked to @kukukaka about this. Let's display the top 10 newest notifications and mark all of them as read as soon as the user opens the notifications page.

**Comment by IagoLast** [comment]
@alonsogarciapablo discussing with @gonzaloriestra this morning and the current implementation is display all unread notifications and some read notifications.

This way the view is never empty (you see old read notifications) and if you have more than 10 new notifications all of them will be visible.

**Comment by alonsogarciapablo** [comment]
To be totally honest, I have no idea how many users will have more than 10 unread notifications but IMO that means 1) that they haven't logged in in a while and 2) that many of those notifications are probably not relevant anymore... While I see the point in displaying all unread + some read ones, I think it will add more technical complexity than value to users, so I think we can go with displaying the latest 10 to keep it simple.
