### ISSUE TITLE
[Dashboard] Unify capitalisation of words in "Your Maps" and "Your Datasets" headings

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#14442]
I ❤️ how "Your Maps" and "Your Datasets" heading changes as you filter the results on the page.

The one thing I noticed is that we're not being consistent with the capitalisation of the words on those titles.

In the Maps page:

- Your Maps
- Your Favorited Maps
- Your Locked Maps
- Your public | private | link-shared | password-protected maps

In the Data page:

- Your Datasets
- Your Locked Datasets
- Your public | private | link-shared | password-protected datasets

In general, we tend to start each word in that heading with an uppercase (eg: Your Locked Maps). When maps or datasets are filtered by privacy, all words are lowercase (eg: Your private maps).

One way or the other, let's make it consistent.

**Comment by jesusbotella** [comment]
Which way is the one you prefer? 🤔 I really like capitalization in every word, but it may not be "correct" gramatically speaking.

**Comment by alonsogarciapablo** [comment]
>  I really like capitalization in every word, but it may not be "correct" grammatically speaking.

Let's go with that @jesusbotella.

**Comment by jesusbotella** [comment]
Done and merged
