### ISSUE TITLE
[Dashboard] Copy link to embed URL

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#14451]
@ramiroaznar and @jsanz suggested it would be great:

> to be able to grab the link of the map without the need of opening it 

Right now there are multiple steps required to do this. Open the map, hit "Publish", hit "Publish" again in the modal and "Get the link".

> if it is just one click, it would be fantastic

A quick action that copies the Embed URL _if the map is published_ would be great.

Slack has something similar:

![image](https://user-images.githubusercontent.com/390398/48621495-f38f5c80-e9a3-11e8-8ed0-0611d45f225a.png)

**Comment by jsanz** [comment]
Maybe moving the full publishing workflow to the dashboard is too much. If
the map has not been published yet, then that option could not be present,
and only show up once the map has been published so we still avoid the
overload of having to access BUILDER publishing modal.
