### ISSUE TITLE
[Dashboard] [Home] Welcome Skeleton

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#14464]
The scope of this issue is to implement the [Welcome section](https://projects.invisionapp.com/share/J7OPHL18HUR#/screens/329479768) in the home page.

The Welcome section shows a greeting to the user, a text with useful information and few Call to action  (CTA) links.

<img width="969" alt="screen shot 2018-12-04 at 17 01 56" src="https://user-images.githubusercontent.com/2657897/49454855-55debe80-f7e6-11e8-8b20-003f70cb2442.png">

**Comment by alonsogarciapablo** [comment]
@csubira created the skeleton for this in the `14464-home-welcome` branch.

The `/api/v3/me` endpoint includes some of the info that we can use the decide what the user should see.

**Comment by jesusbotella** [comment]
@IagoLast @alonsogarciapablo Do you want me to merge it to start with `Your Maps` section?

**Comment by alonsogarciapablo** [comment]
I'm not sure what will happen if we merge it...

**Comment by jesusbotella** [comment]
As long as the tests don't fail, any major issue won't happen 😂 
But @IagoLast, you can start your branch from this one if you want, whatever you prefer :)

**Comment by IagoLast** [comment]
I'm taking this 💪
