### ISSUE TITLE
[Dashboard] [Home] Quota & Metrics Module

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#14463]
![image](https://user-images.githubusercontent.com/390398/49877952-d0cb5900-fe26-11e8-8913-8e430f6685ef.png)

![image](https://user-images.githubusercontent.com/390398/49877961-d4f77680-fe26-11e8-9961-35b4881ac866.png)

**Comment by alonsogarciapablo** [comment]
@ramiroaznar we have the opportunity to show links to helpful resources about quotas & LDS in this modules. Are there some good entries in the Help Center that we can point to about:
- Storage quota
- Geocoding credits
- Routing credits
- Isolines credits

I found [When does geocoding cost?](https://carto.com/help/your-account/geocoding-credits/) but not much related to the rest of the topics.

What do you think about this? Should we create new entries for each of these topics? Thank you!

**Comment by ramiroaznar** [comment]
That's the best one. [Credits definition](https://carto.com/help/glossary/#credits) can also be found in the Glossary. 

Yes, I think it is a good idea to add a new entry explaining these 4 metrics.

**Comment by alonsogarciapablo** [comment]
Great! @ramiroaznar how do we do it? Should I open and issue? Open a PR myself somewhere? Thanks!

**Comment by alonsogarciapablo** [comment]
Great. Thank you!

**Comment by albertoac** [comment]
Hi @alonsogarciapablo,
in the design, we put at the top right the renewal date ("Your credits reset the 5th of each month"). Is this date always the same for every customer or it might change? If it changes, how can we get that information?

Thanks

**Comment by alonsogarciapablo** [comment]
@albertoac The `api/v3/me` has information related to the user's billing period. Not sure how you can access this from the app, but if you inspect the network requests, you will see it:

![screenshot 2018-12-13 at 16 09 27](https://user-images.githubusercontent.com/390398/49947454-9b3f7200-fef1-11e8-9eb0-cad90fd48e34.png)

**Comment by albertoac** [comment]
@alonsogarciapablo great, thanks! So the billing_period is the last time it was billed, correct? So we should suppose that it will be billed again exactly one month after that?.
For example, in the case you put, the Christmas day will be the next billing day?. And is always every month? Every 30 days?

**Comment by alonsogarciapablo** [comment]
Those are great questions @albertoac and I can't really answer them 😞. Perhaps @gonzaloriestra can help us here 🙏 . @gonzaloriestra to give you some context... we want to show users the day of the month when their Location Data Services (Geooding, Routing, Isolines) credits will renew. These are reset montly, and I was hoping we could get this information from the `api/v3/me` endpoint as I commented in https://github.com/CartoDB/cartodb/issues/14463#issuecomment-447002760. But after reading @albertoac's questions, I'm not sure we can use the billing period because some accounts are billed annually... Perhaps there's something else in the response from that endpoint that we can use or we might need to add more data... Could you please take a look? Thank you!

**Comment by gonzaloriestra** [comment]
All the Location Data Services are reset monthly, even if the account is billed annually. So we could use the `billing_period` + 30 days, as it's being calculated in other places in the UI.

But that solution is not very accurate, in fact. If the last payment was on `2018-12-01`, the next one will be on `2019-01-01`, and not on `2018-12-31` (01 + 30). Or if it was on `2018-10-31`, it should say `2018-11-30` in November or `2019-02-28` in February... The thing is that it's not possible to calculate it correctly with the `billing_period`, because we need the original billing date. So if we want to be precise, we should add a new field in the API response with the next billing period.

**Comment by albertoac** [comment]
Thanks @gonzaloriestra in that case, yes, I guess if we need to add it in the final design we should add it in the API. The other option is to remove it from the design, but I think it can be a very useful feature.
What do you think @alonsogarciapablo @kukukaka?

**Comment by alonsogarciapablo** [comment]
Yes, this is something that users are asking about. They need to know when those credits will renew, and this info needs to be accurate. +1 to adding a new field to the API endpoint. @gonzaloriestra is this something we can do relatively quickly? Thank you!

**Comment by gonzaloriestra** [comment]
@alonsogarciapablo Yes, it should be easy to include.

**Comment by alonsogarciapablo** [comment]
Thank you @gonzaloriestra. I'm adding the `Backend` label to this and let's try to do it soon so that we can finish this issue 🙏.

@albertoac in the mean time, perhaps you can hack that endpoint locally by simulating / hardcoding the new field [here](https://github.com/CartoDB/cartodb/blob/master/app/controllers/carto/api/user_presenter.rb#L195).

**Comment by gonzaloriestra** [comment]
The backend part is ready in master. Now `/me` also returns `next_billing_period`.

**Comment by alonsogarciapablo** [comment]
Thanks @gonzaloriestra!
