### ISSUE TITLE
[Dashboard] [Maps] "Public" maps only include maps that are Public and Published

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#14466]
Not really a bug, but something we should revisit.

**Steps to reproduce**

1. Visit Your Maps. Make sure you have some Public maps (that hasn't been published)

![image](https://user-images.githubusercontent.com/390398/48707270-2c773d80-ebff-11e8-9cd5-20dd8a07911a.png)

2. Filter by Privacy: Public.

**Expected results:**

I would expect to see all maps whose privacy is "Public".

**Actual results:**

- If there're some "Public" maps that have been published, only those are displayed.
- If all "Public" maps have NOT been published, the UI shows "There are no maps here".

-----

Talked to @jesusbotella about this. It turns out that the /viz endpoint only returns maps that are "Public" and "Published" when `privacy` is set to `public`. IMO it should behave as the rest of the filters (i.e: filter based on the privacy, without taking the publication status into account).

@javitonino do you know why? is there a way to include all public maps, regardless of their publication status? if not, could we change this behaviour (eg: adding (yet) another parameter like `only_published`)?

**Comment by javitonino** [comment]
This is done because this endpoint is reused in some public pages. It is confusing, but we should fix it, so `privacy` refers only to that, and not the `published` status, at least when you are logged in and checking on your maps.

**Comment by alonsogarciapablo** [comment]
👍 thanks @javitonino

**Comment by alonsogarciapablo** [comment]
Working like a charm!

**Comment by alonsogarciapablo** [comment]
@gonzaloriestra it looks like the backend PR is already merged, right? Can we move this to DONE? Thank you!

**Comment by gonzaloriestra** [comment]
Yes, it is merged. I'm moving it.

**Comment by alonsogarciapablo** [comment]
👏👏👏 Thank you!
