### ISSUE TITLE
[Dashboard] Revisit Footer

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#14470]
In https://github.com/CartoDB/cartodb/issues/14327, we implemented the first version of the footer, but we have to iterate a bit.

Basically, different types of users have different options to ask "Technical Issues" and "Other questions":

| Account Type | Technical Issue | Other Questions              |
|------------|-----------------|------------------------------|
| FREE       | Contact Support | Ask in [GIS StackExchange](http://gis.stackexchange.com/questions/tagged/carto)       |
| PRO        | Contact Support | Contact Support              |
| ENTERPRISE | Contact Support (Enterprise)| Contact Support (Enterprise) |

Also, members of an org (excluding admins) should see a link to contact the admin of their orgs. That means many users will only see 3 blocks in the footer.

![image](https://user-images.githubusercontent.com/390398/48717126-15454980-ec19-11e8-8618-578a5ec8ea7b.png)

**FREE USERS**

- Help Center
- Developers
- Contact Support
- Ask in GIS StackExchange

**PRO USERS**

- Help Center
- Developers
- Contact Support
- ?

**ENTERPRISE USERS**

Member

- Help Center
- Developers
- Contact Support
- Contact Admin

Admin

- Help Center
- Developers
- Contact Support
- ?

@kukukaka I would like to get your input on:

- For FREE users we somehow need to provide two different options: Ask in GIS StackExchange and Contact Support. Since these users don't belong to an org, we can use that extra block.
- ENTERPRISE customers have dedicated support, we might want a different copy for this?
- Some users (eg: PROFESIONAL users) will only see 3 blocks in the footer. Are you okay with that?

**Comment by ramiroaznar** [comment]
HELP subtitle should be changed to sync with its terminology and structure. Something like: `Check the most frequent asked questions and learn to build maps and work with data`. @CartoDB/support-team what do you think?

**Comment by ztephm** [comment]
IMHO since FAQ are about all topics we can make that shorter:
`Learn how to build maps, work with data, and manage your account`

Or to make it sound different from Developer Center:
`Answers to frequently asked questions about how to make Builder maps, work with data, and manage your account`

**Comment by ramiroaznar** [comment]
@ztephm much better!

**Comment by javitonino** [comment]
I'd suggest opening a new ticket, since it would be a decent sized task, and it can be worked on independently and merged to master (instead of to the dashboard branch)

**Comment by alonsogarciapablo** [comment]
>  However, none of them are accurate enough to be used for this case (i.e organization users can be identified but not all organizations have enterprise plans).

@csubira in what cases we cannot identify users correctly?

**Comment by csubira** [comment]
Currently I'm using the same method than for the support-banner of the old dashboard, (as we discussed), https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/dashboard/components/support-view.js#L32

Then,
- All organizations are considered the same.
- If the `account_type` is not **'free'**, **'internal'**, **'partner'** or **'ambassador'** all the rest are considered PRO.
(I don't know if these include all the needed type, since for example for my team account, the `account_type` is `ORGANIZATION USER` )
