### ISSUE TITLE
[New Dashboard] Adapt current dashboard's request interceptor

### ISSUE THREAD

**Issue by jesusbotella** [CartoDB/cartodb#14489]
As of GDPR and MFA changes, current dashboard has an interceptor to redirect users to `/login` or other specific routes when any AJAX request fails with 403 error.

I believe that the mechanism implemented for that wouldn't work with our new dashboard approach, but let's revisit it and make sure that the feature is working as it was thought before.

**Comment by alonsogarciapablo** [comment]
Is this still relevant @jesusbotella?

**Comment by jesusbotella** [comment]
Merged!
