### ISSUE TITLE
[Dashboard] [Datasets] "Create Map" Quick Action in Your Datasets and Datasets shared with you

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#14484]
In https://github.com/CartoDB/cartodb/issues/14319 we didn't add the "Create a map" action to the list of datasets. This is a pretty key action :). Also, I just realised that it might be interesting to "Create a map" from a dataset that has been shared with me (we currently offer this option).

- [x] Add the "Create a map" action to datasets. It should only be "hidden" if the dataset is locked.
- [x] Changes to the "Create map" bulk action:
  - [x] It should be possible to create a map from more than one datasets (the action should be visible if more than one dataset is selected).
  - [x] It should be available in the "Shared with you" page (so datasets should be selectable in there too).

**Comment by kukukaka** [comment]
Yes, I agree. We are also showing that option once you select the dataset from the checkbox, so it should be also in the secondary options.

**Comment by alonsogarciapablo** [comment]
Yes, makes sense too. The only issue there is that if more than one dataset the "Create map" option cannot be displayed so only "Deselect all" action will be displayed. But I also think it makes everything more consistent (right now we're not showing the checkboxes on that page). I'm adding a task in the description.

**Comment by kukukaka** [comment]
You can create a map when more than one dataset is selected, right :?

**Comment by alonsogarciapablo** [comment]
Yes, that's totally true. Well you can in the actual UI but not in the new one. That was totally my fault because I didn't include it in https://github.com/CartoDB/cartodb/issues/14322. Great catch @kukukaka.

**Comment by csubira** [comment]
I've split this issue in two different parts, the first one regarding **Quick Actions**, I set the options as follows:

#### Locked Dataset:
- Unlock Dataset
#### Shared With You Dataset:
- Create Map
- Duplicate Dataset
#### Rest of datasets
- Edit Info
- Manage Tags
- Create Map
- Change Privacy
- Share with colleagues
- Duplicate Dataset
- Lock Dataset
- Delete Dataset

In the second one and regarding the **Bulk actions** I made the following assumptions:

### Only **ONE** dataset is selected:
#### Locked dataset:
- Unlock Dataset
#### Shared with you dataset
- Select All
- Create Map
- Duplicate Dataset
#### Rest of dataset types
- Select All
- Create Map
- Change Privacy
- Duplicate Dataset
- Lock Dataset
- Delete Dataset

### Multiple datasets are selected:
#### All datasets are selected (it contains LOCKED datasets)
- Unlock Datasets
#### All datasets are selected (it contains SHARED datasets)
- Deselect All
- Create Map
#### All datasets are selected (it does not contain SHARED or LOCKED datasets)
- Deselect All
- Create Map
- Lock Datasets
- Delete Datasets

#### NOT all datasets are selected (it contains LOCKED datasets)
- Unlock Datasets

#### NOT all datasets are selected (it contains SHARED datasets)
- Select All
- Deselect All
- Create Map

#### NOT all datasets are selected (it does not contain SHARED or LOCKED datasets)
- Select All
- Deselect All
- Create Map
- Lock Datasets
- Delete Datasets


However there are a couple of questions that I'd like to pass through you:
1. Is there any possibility to select shared and non shared maps the same time? Then, are the _NOT all datasets are selected (it contains SHARED datasets)_ options listed above correct?
2. Following the same line, could locked and non locked be selected at the same time. Are the _NOT all datasets are selected (it contains LOCKED datasets)_ options listed above correct?
3. Is there any case where locked and shared datasets can be selected at the same time? If affirmative,  which are the actions to display?

**Comment by csubira** [comment]
I attach a summary spreadsheet, maybe easier to check:
<img width="1117" alt="screen shot 2018-11-27 at 15 48 34" src="https://user-images.githubusercontent.com/26403479/49089474-edc73000-f25b-11e8-8745-b10887028ff1.png">
https://docs.google.com/spreadsheets/d/1aXLj6CqqsF4ESqjFa-F0kDzttgO8x_WIKrqA1K6y9XE/edit?usp=sharing

**Comment by alonsogarciapablo** [comment]
What a spreadsheet @csubira! It really helps. Would you 🙏 give us comment access?

**Comment by alonsogarciapablo** [comment]
Works great @csubira 👏 

The only thing that seems a bit random to me is the order of the quick actions:

![image](https://user-images.githubusercontent.com/390398/49223129-268f1280-f3de-11e8-8f9a-58f4eabf2241.png)

It that dropdown, there are two types of actions:

1. Actions that modify the dataset (name & description, tags, privacy, who has access to it, lock, delete).
2. Actions that "use" the dataset somehow (duplicate and create map).

Perhaps we can group them or order them based on these two groups. @csubira @kukukaka what do you think?

**Comment by csubira** [comment]
Ordering them is easy to do, so just tell me how!

**Comment by kukukaka** [comment]
Sounds good @alonsogarciapablo. I guess we prefer to have the second block (actions to use the dataset) first, right?

1. Create map
2. Duplicate
3. Change with colleagues (it should be in this block?)
4. Edit name and description
5. Manage tags
6. Change privacy
7. Lock
8. Detele

If you think we need to reinforce more the split between both blocks, maybe we can work on making the line between both blocks ticker or some other visual solution.

**Comment by alonsogarciapablo** [comment]
Thanks @kukukaka. The truth is that the list is a bit too long (too many actions) and hard to navigate anyway. But let's go with your proposal.

**Comment by csubira** [comment]
Reordered!
