### ISSUE TITLE
[OAuth] Include oauth_app and friends in user migrator

### ISSUE THREAD

**Issue by alrocar** [CartoDB/cartodb#14492]
There are some user metadata related entities that need to be migrated:

- `oauth_apps`
- `oauth_app_users`
- `oauth_authorization_tokens`
- `oauth_access_tokens`
- `oauth_refresh_tokens`
- `api_keys`

We’ll make sure all the user/OAuth related metadata is migrated in our current migration service.

Some things to take into account:

- We’ll need to add a condition to some of the hooks to avoid regenerating tokens and other stuff (like role creation or ID generation). We do something similar in the api_keys migration with the `skip_role_setup`
- In `import_user`:
  - we’ll need to include the `oauth` api_keys roles and datasets scopes related roles in `create_user_api_key_roles`
  - we’ll need to grant datasets scopes roles in `grant_user_api_key_roles`

**Comment by oleurud** [comment]
Done: https://github.com/CartoDB/cartodb/pull/14521 & https://github.com/CartoDB/cartodb-central/pull/2397
