### ISSUE TITLE
[Dashboard] Loading notifications state

### ISSUE THREAD

**Issue by IagoLast** [CartoDB/cartodb#14499]
We need to implement a view to handle the `fetching notifications` state.

**Comment by alonsogarciapablo** [comment]
@kukukaka what do you think?

**Comment by kukukaka** [comment]
We can reuse (resized) the spinner we are proposing for the search flow.

I attach here the  loading and no results states (I'll update the Invision later today). What  do you think?

![image](https://user-images.githubusercontent.com/8354661/49226377-a7eaa300-f3e6-11e8-8122-e70034e036ed.png)
![image](https://user-images.githubusercontent.com/8354661/49226382-aae59380-f3e6-11e8-864a-fdc938a829e5.png)
