### ISSUE TITLE
Activating MFA doesn't redirect to login page

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#14509]
### Context

When MFA is activated, then we deactivate it and then activate it again, we don't redirect the user to the login page.

When MFA is activated for the first time, it works. It fails when switching it off and on again.

### Steps to Reproduce

1. Get MFA activated.
2. Deactivate MFA.
3. Activate MFA again.

### Current Result
The user returns to the account page, with a message of successful changes saving.

### Expected result
The user is redirected to the login page to scan a QR code.

![2fa](https://user-images.githubusercontent.com/1078228/49285591-22273000-f498-11e8-8aeb-19713f4b79c4.gif)

**Comment by alrocar** [comment]
@CartoDB/rt-managers Could we handle this issue via response team?

I guess a possible solution might be setting `warden.session(user.username)[:multifactor_authentication_performed] = false` before enabling.

**Comment by ivanmalagon** [comment]
Please wait until I merge https://github.com/CartoDB/cartodb/issues/14505 to tackle this issue.
