### ISSUE TITLE
[MFA] no request made

### ISSUE THREAD

**Issue by owayss** [CartoDB/cartodb#14505]
### Context
Trying to enable MFA functionality.

### Steps to Reproduce

1. Go to /account view
2. Try and enable MFA
3. Click "Save"
4. Introduce your password

### Current Result
No requests get made. MFA does not get enabled.

![screenshot from 2018-11-29 14-59-57](https://user-images.githubusercontent.com/15263893/49226671-95bd3480-f3e7-11e8-97a0-81093859aeee.png)

### Expected result
MFA gets enabled.

### Browser and version
Chromium Version 70.0.3538.77 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

### Additional info
If it is of any help, the feature was working in tag `4.23.0` https://github.com/CartoDB/cartodb/blob/master/NEWS.md#4230-2018-11-19

/cc @ivanmalagon @CartoDB/rt-managers

**Comment by javitonino** [comment]
Hey @ivanmalagon, to finish an off-ticket conversation. We have talked about the onprem release, and we are OK to release without this fixed. So, no special hurry on this one. Let's tackle it when we can though, since we want to be ready to release MFA soon, but no hard deadline at this moment.
