### ISSUE TITLE
Design new login page

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#1452]
please :) @saleiva

**Comment by saleiva** [comment]
cc/ @carlostallon 

Would be great to have the background image moving around a bit tho...

![dark map](https://cloud.githubusercontent.com/assets/132149/5650330/98126a8a-969d-11e4-8f53-9c520614b369.png)
![light map](https://cloud.githubusercontent.com/assets/132149/5650329/980bf92a-969d-11e4-950d-d11c53e2ed2a.png)

**Comment by carlostallon** [comment]
Love the map background idea.
Could we use this login/register modal in another pages?

**Comment by saleiva** [comment]
Pending unifying this and the signup

**Comment by carlostallon** [comment]
Sure, we need to unify both :+1:

**Comment by carlostallon** [comment]
![01 login google](https://cloud.githubusercontent.com/assets/1712650/5761398/8c09ea6c-9cdb-11e4-9d3e-9a2da1bcdac6.png)
![03 signup](https://cloud.githubusercontent.com/assets/1712650/5761399/8db02de0-9cdb-11e4-9f67-d317b083685d.png)

**Comment by saleiva** [comment]
Hey, closing this since it's already in the correct repo
