### ISSUE TITLE
[Dashboard] Logo is not centered

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#14529]
![screenshot 2018-12-12 at 15 35 27](https://user-images.githubusercontent.com/390398/49876839-7a5d1b00-fe24-11e8-9abb-76c28d20d797.png)

**Comment by jesusbotella** [comment]
This is not an actual issue 😂 

The last thing we talked with @kukukaka is that the logo should be centered within the remaining space between the section buttons and the search box. It looks weird in some cases, like this one. Maybe we should reconsider it.

**Comment by alonsogarciapablo** [comment]
It did look a bit weird to me.

**Comment by alonsogarciapablo** [comment]
@kukukaka should I close this then?

**Comment by jesusbotella** [comment]
Can we talk a bit about this now again? It is kinda disturbing now that we have four links in our navbar. 😂

**Comment by alonsogarciapablo** [comment]
Closing this as the logo seems to be perfectly centered now.
