### ISSUE TITLE
[New Dashboard] Deploy to Production

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#14537]
The New Dashboard is currently in the `new-dashboard-feature` branch and it's secured under a Feature Flag so we should be able to deploy it to production so that we can start dogfooding this internally and also run some usability tests.

**Tasks:**

- [x] Make sure the feature branch can be merged into `master` and can be released to production.
- [x] Merge the feature branch into `master` and deploy to production 🚀 .

**Comment by jesusbotella** [comment]
Deployed successfully! 🚀
