### ISSUE TITLE
[Dashboard] Revisit "Your Maps" & "Your Datasets" Placeholders

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#14534]
## Your Maps

**1. User has not created any map yet (`total_user_entries === 0`):**

![image](https://user-images.githubusercontent.com/390398/49881576-04aa7c80-fe2f-11e8-8d5c-a07e3e394940.png)

We can update the copy to:

> **Create your first map to predict key insights**
>
> Build your first Location Intelligence app and start predicting key insights from your location data with our drag and drop tool for analysts and business users. Learn about Builder [here].(https://carto.com/help/tutorials/builder/) 

**2. User has created some maps but they are all locked (`total_user_entries > 0 && total_user_entries - total_locked === 0`):**

![image](https://user-images.githubusercontent.com/390398/49881880-a16d1a00-fe2f-11e8-8644-197f12a0a0a2.png)

**3. User has not created any map yet but she/he has some maps that have been shared with her/him (`total_user_entries === 0 && total_shared > 0`):**

![image](https://user-images.githubusercontent.com/390398/49881959-d24d4f00-fe2f-11e8-8094-f3568a1227a4.png)

> There are no maps here. Check out the [maps shared with you](). 

## Your Datasets

**1. User has not created any dataset yet (`total_user_entries === 0`):**

![image](https://user-images.githubusercontent.com/390398/49939107-1c8c0a00-fedc-11e8-8ecc-be8e6476cb32.png)

We can update the copy to:

> **Upload, connect, or create your first dataset**
>
> Bring your location data to CARTO so that you can visualise it and start predicting key insights. Learn about importing your data  [here](https://carto.com/help/tutorials/import-data/).

**2. User has created some datasets but they are all locked (`total_user_entries > 0 && total_user_entries - total_locked === 0`):**

![image](https://user-images.githubusercontent.com/390398/49881880-a16d1a00-fe2f-11e8-8644-197f12a0a0a2.png)

(*) It should say datasets instead of maps.

**3. User has not created any dataset yet but she/he has some datasets that have been shared with her/him (`total_user_entries === 0 && total_shared > 0`):**

![image](https://user-images.githubusercontent.com/390398/49881959-d24d4f00-fe2f-11e8-8094-f3568a1227a4.png)

> There are no maps here. Check out the [maps shared with you](). 

(*) It should say datasets instead of maps.

--

@ramiroaznar Placeholders are pointing to https://carto.com/help/tutorials/builder/ and
https://carto.com/help/tutorials/import-data/. Are there any better resources where users can learn about Builder and Importing data? Thanks!

cc: @kukukaka @jesusbotella

**Comment by jesusbotella** [comment]
Merged!

**Comment by alonsogarciapablo** [comment]
Hey! I was testing something and I find some issues related to this:

1. The UI sometimes shows "MapsPage.emptyState", instead of the right text.

![screenshot 2019-01-29 at 12 01 39](https://user-images.githubusercontent.com/390398/51903939-b8ef6a80-23bd-11e9-90a1-1372beb0c7a7.png)

2. In "Your Datasets", when the user hasn't created any dataset, but some datasets have been shared with him, the placeholder text takes up two lines and it looks a bit funky IMO. Can we make the line a bit longer or the text a bit shorter?

![screenshot 2019-01-29 at 12 01 04](https://user-images.githubusercontent.com/390398/51903938-b856d400-23bd-11e9-90ad-1629de6caaad.png)

**Comment by alonsogarciapablo** [comment]
Kind of related with https://github.com/CartoDB/product/issues/227.

**Comment by alonsogarciapablo** [comment]
I'm also seeing "DataPage.emptyState" in the "Your Datasets" module:

![image](https://user-images.githubusercontent.com/390398/51906413-5f3e6e80-23c4-11e9-961e-662e18de7b3a.png)

**Comment by jesusbotella** [comment]
Merged!

**Comment by alonsogarciapablo** [comment]
Ole! 👏
