### ISSUE TITLE
[Dashboard] Cannot duplicate a dataset when visiting "Your Data" from the homepage

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#14541]
**Steps to reproduce:**

1. Go the HOME page.
2. Click VIEW ALL DATASETS.
3. Select on dataset.
4. Click "Duplicate dataset" in the bulk action menu.

**Current result:**

Nothing really happens:

![duplicate](https://user-images.githubusercontent.com/390398/50085828-6ede6b00-01fb-11e9-94ec-006a9cb89136.gif)

**Expected results:**

The "import" should be enqueued and I should see that the dataset is being duplicated.

**Comment by jesusbotella** [comment]
Fixed! 🎉

**Comment by alonsogarciapablo** [comment]
Thanks! 👏👏👏
