### ISSUE TITLE
[Dashboard] [Search] Link to datasets is wrong

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#14542]
**Steps to reproduce**
- Type the name of a dataset in the search box.

![image](https://user-images.githubusercontent.com/390398/50099837-4b2d1c00-021f-11e9-8a43-7376fa66f9b7.png)
- Click on a dataset in the results suggestions ☝️ 

**Current result**

I should enter the Dataset view.

**Expected results**

The links to the datasets are broken (eg: https://new-dashboard.carto-staging.com/u/new-dashboard-feature/viz/77d82f08-8c1f-4c99-bff0-78220c228950) and I see the 404 page.

**Comment by jesusbotella** [comment]
Fixed!
