### ISSUE TITLE
[Dashboard] Condensed view

### ISSUE THREAD

**Issue by IagoLast** [CartoDB/cartodb#14546]
![screen shot 2018-12-19 at 10 56 41](https://user-images.githubusercontent.com/2657897/50213043-cce68c00-037c-11e9-8447-8ce98ba199e5.png)

**Comment by jesusbotella** [comment]
Here's the final design and the switcher between condensed and non-condensed view: https://invis.io/J7OPHL18HUR#/338295582_18_Maps_Compact

**Comment by albertoac** [comment]
@kukukaka What should we use in case there's no map preview available?
If we use the same image as in the normal map card, it just look as a grey box

![image](https://user-images.githubusercontent.com/4774531/50452175-c9cd3c00-0938-11e9-8f5f-953d62f04757.png)
