### ISSUE TITLE
MFA forgets `return_to` during setup

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#14566]
MFA forgets the `return_to` URL during setup.

STR
1. Enable MFA for a user but don't setup yet
2. Logout
3. Go to /oauth2/authorize...
4. Login
5. Setup MFA

I expect to be redirected back to OAuth, but I got to dashboard

Potential patch
[redirection_after_mfa_setup.patch.txt](https://github.com/CartoDB/cartodb/files/2712954/redirection_after_mfa_setup.patch.txt)

**Comment by ernesmb** [comment]
thanks a lot javi, you're the best ✨ 

we've deployed the patch and works well :)

**Comment by javitonino** [comment]
Leaving this open to track the `master` fix. :)
