### ISSUE TITLE
Wrong next billing cycle calculation in Editor

### ISSUE THREAD

**Issue by gonzaloriestra** [CartoDB/cartodb#14577]
### Context

There's a footer in the geocoding datasets view where we show the pending days until the next billing cycle, but we are just taking the last cycle and adding 30 days, which is correct only sometimes.

![geocoding](https://user-images.githubusercontent.com/14979109/50632430-1b348700-0f48-11e9-8329-7b921e7a7aaa.png)

Instead of calculating it in the frontend, we can use the next billing cycle information we have recently added in /me endpoint (https://github.com/CartoDB/cartodb/pull/14548).

### Steps to Reproduce

1. Edit a user and change the Geocoding quota to 0, disable Builder and set the `period_end_date` to `Time.zone.parse('2018-01-01 10:00:00')`
2. Open a dataset
3. Click on Edit - Georeference
4. Go to Street Addresses tab

### Current Result
The footer is warning that you don't have enough geocoding credits and it's showing the pending days for the next billing cycle. In January it's counting the days until January 31st, and in February until March 3rd.

### Expected result
It should count the days until February 1st in January or March 1st in February.

### Additional info
We should change this:
https://github.com/CartoDB/cartodb/blob/3c0f44619e5e394c00ac88f9ac589f686978c263/lib/assets/javascripts/cartodb/common/dialogs/georeference/street_addresses/street_addresses_model.js#L70

And use the new `next_billing_period` from User instead.

**Comment by ramiroaznar** [comment]
Going to close this one. We are not going to fix Editor issues like this one. Our focus is on elsewhere. Mentioning @javitonino or @ivanmalagon for awareness.
