### ISSUE TITLE
Highlight the selected basemap in CartoDB editor

### ISSUE THREAD

**Issue by jorgeas80** [CartoDB/cartodb#1457]
I think the selected basemap should appear highlighted

![captura de pantalla 2014-12-15 a las 18 16 24](https://cloud.githubusercontent.com/assets/772448/5440182/8e6e6264-8486-11e4-9973-e0916eb45d04.png)

**Comment by xavijam** [comment]
This is gonna change with the new editor, so closing!

BTW, @jorgeas80, it is a pleasure to see your contributions :_).

**Comment by jorgeas80** [comment]
Cool! Happy to contribute ^_^
