### ISSUE TITLE
[Dashboard][Home] Update links in quota & metrics section

### ISSUE THREAD

**Issue by csubira** [CartoDB/cartodb#14574]
The quota section was added to the homepage in issue: https://github.com/CartoDB/cartodb/issues/14463

However, there was a pending issue to create new content in the Help Center to explain how quota and usage data are counted: https://github.com/CartoDB/help/issues/225

Once this issue is closed and **the urls to these articles are ready, they should be added to the question mark icon** that appears when the different quota sections are hovered:

<img width="537" alt="screen shot 2019-01-02 at 13 21 08" src="https://user-images.githubusercontent.com/26403479/50591787-853e2500-0e91-11e9-8649-cc6f9c49e0e1.png">

**Comment by alonsogarciapablo** [comment]
Here're the articles we should link to:

- [ ] Storage 👉 https://carto.com/help/your-account/your-data-services-credits/
- [ ] Geocoding 👉 https://carto.com/help/working-with-data/geocoding/
- [ ] Isolines 👉 https://carto.com/help/working-with-data/isolines/
- [ ] Routing 👉 https://carto.com/help/working-with-data/routing/

**Comment by oriolbx** [comment]
@alonsogarciapablo The disk storage section/panel shouldn't be pointing to https://carto.com/help/your-account/your-disk-storage/ instead?

**Comment by alonsogarciapablo** [comment]
Fixed already @oriolbx. Thanks for reporting!
