### ISSUE TITLE
[OAuth] Create role for table creation

### ISSUE THREAD

**Issue by alrocar** [CartoDB/cartodb#14591]
Each `oauth_app_user` creates a role to track permissions.

We are going to create a new role for tracking tables ownership. This role will be used for several purposes:

- We'll change ownership of tables created from OAuth to this role (from an event trigger) -> https://github.com/CartoDB/cartodb/issues/14594
- OAuth access token roles will be granted this role
- Eventually we could use this role to know which tables created each OAuth app (or user) and drop them when uninstalling the OAuth app -> https://github.com/CartoDB/cartodb/issues/14595

**Comment by javitonino** [comment]
The master user role should also be granted this role in order for the master key to be able to ALTER/DROP these tables.
