### ISSUE TITLE
[OAuth] Change owner of OAuth created tables

### ISSUE THREAD

**Issue by alrocar** [CartoDB/cartodb#14594]
Given an access token an OAuth app with the `schemas:c` scopes would be able to CREATE, ALTER and DROP tables in the user account.

We need to change the ownership of created objects (tables, views, etc.) to the OAuth ownership roles (which access token roles and master role inherit from). So we keep ownership in a single role, but future access tokens and master roles inherit ownership on the created objects.

The idea is to use `event triggers` + `cdb_conf` to:

- on CREATE a new object in a schema (table, view, etc.?)
- retrieve the `ownership_role_name` from `cdb_conf` (see [related issue](https://github.com/CartoDB/cartodb/issues/14593)). 
- [Change the owner](https://gist.github.com/javitonino/95bc274893f98a137edafa3d313e4ce6#file-owner_on_create_table-sql-L23
) of the newly created object from the create_role (the `api_key.db_role` to the `ownership_role_name` in `cdb_conf`.

We'll add some tests to check that make sure this works with views and other stuff:

- [x] Create the event trigger in the user database when the `schemas:c` permission is granted
- [x] Include tests:
  - [x] Event trigger tests: create, revoke, configuration
  - [x] Pending tests for refresh token with different/fewer permissions. For example, ask for `datasets:rw` and in the refresh token reduce to `datasets:r` and try to write.

**Comment by ethervoid** [comment]
Regarding change the `datasets:rw:table_name` permission for `datasets:r:table_name`:

- If we try to make in the consent screen it doesn't work, it goes back to the dashboard page
- In the `exchange!` method of the refresh token, you get an `Invalid Scope` exception

Looks like our system dont know about hierarchycal scopes
