### ISSUE TITLE
Remove LIKEs feature

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#14619]
The new Dashboard doesn't have LIKES (it has favorites instead), and the feature doesn't really make sense now, so we've decided to remove this feature from the UI. LIKES are currently in different places:

- Public pages:
  - /me ([example](https://team.carto.com/u/saleiva/me))
  - /maps ([example](https://team.carto.com/u/saleiva/maps))
  - /datasets ([example](https://team.carto.com/u/saleiva/datasets))
- Actual Dashboard: Maps (Ordering / Filtering / Liking)
![image](https://user-images.githubusercontent.com/390398/51311320-f44a7a80-1a48-11e9-913e-2755969e0248.png)
- Actual Dashboard: Datasets (Ordering / Filtering / Liking)
<img width="1001" alt="screenshot 2019-01-17 at 11 05 32" src="https://user-images.githubusercontent.com/390398/51311353-05938700-1a49-11e9-903f-bbee12799628.png">

Since we're reusing LIKES to implement FAVORITES we need to remove LIKES before we release the new Dashboard to everyone. As part of the release, we have to "reset" LIKES so that New Dashboard users don't have any favorites.

**Comment by alonsogarciapablo** [comment]
We're also sending emails to users when one of their maps or datasets has been liked. @ethervoid, we should remove those emails too. I created [this list of emails that we send to users](https://docs.google.com/spreadsheets/d/1j5Ke5UtUjKv5TmY1pwKIDnnhhIYwqoFd-E0esIYUQC8/edit#gid=0) that might help with this.

**Comment by ethervoid** [comment]
They're also removed in my branch :). Thank you for the heads up

**Comment by alonsogarciapablo** [comment]
Great @ethervoid! 👏

**Comment by alonsogarciapablo** [comment]
Hey! I deployed this to staging (user: `bye-bye-likes` and password: `bye-bye-likes123`) and tested a bit. Here're the results:

- Builder user
  - Dashboard:
    - Maps ✅
    - Datasets ✅
  - Public Profile
    - /me ✅
    - Maps ✅
    - Datasets ✅
- Editor user
  - Dashboard:
    - Maps ✅
    - Datasets ✅
  - Public Profile
    - /me ❌
    - Maps ✅
    - Datasets ✅

I could still see the ❤️  in the Public Profile of an Editor user:

![image](https://user-images.githubusercontent.com/390398/51845530-fbf70280-2317-11e9-932a-3cfd137dc982.png)

@ethervoid should I test anything else? Organization users?

**Comment by ethervoid** [comment]
@alonsogarciapablo Yes, with shared dataset/map for example. In the new dashboard you should be allowed to favorite your own datasets/maps and the shared ones too

**Comment by alonsogarciapablo** [comment]
Great, I will try that too.

**Comment by alonsogarciapablo** [comment]
Hey! I'm re-deployin to staging so that I can test with multiple org users.

**Comment by alonsogarciapablo** [comment]
Hey! I just finished testing this a bit more (and I found 3 unrelated bugs along the way).

New Dashboard:

- Favoriting my own maps ✅
- Favoriting maps shared with me ✅
- Favoriting my own datasets ✅
- Favoriting datasets shared with me ✅

**Comment by alonsogarciapablo** [comment]
To summarise, the only instance where I found something related to LIKES is when visiting a public profile (/me, [example](https://team.carto.com/u/saleiva/me)) with an Editor user. @ethervoid I can check again once that's done. Thank you! 🙇

**Comment by ethervoid** [comment]
@alonsogarciapablo Oh, great! I'll remove that and I assume we're ready to merge/deploy

**Comment by ethervoid** [comment]
@alonsogarciapablo In the current branch should be removed. We cannot find it. What use are you using to make the tests? thank you

**Comment by alonsogarciapablo** [comment]
@ethervoid I created a new dedicated server which is no longer alive. In case it helps, user was `bye-bye-likes`.

**Comment by ethervoid** [comment]
Ok, thank you to @csubira and @jesusbotella we've found that I didn't raise the version number for editor assets so now it should work. 

Also, we have to do a new acceptance test which is. Add users that share likes but they aren't from the same organization and then we test that case with these changes in order to verify that we don't have problems with the current data system.

**Comment by alonsogarciapablo** [comment]
@ethervoid @csubira, not sure if https://github.com/CartoDB/product/issues/239 is related to this or not. Other than that... is there anything else missing here? Thank you!

**Comment by ethervoid** [comment]
@alonsogarciapablo Hi again! @csubira did an amazing job and everything is :green_heart: now. I've deployed the likes branch in our staging env so you can test everything again. I know this is a bit burdensome but I want to be sure everything is backward compatible :)

Thank you

**Comment by alonsogarciapablo** [comment]
Vamos @ethervoid and @csubira! Team work! I will deploy a dedicated a give it a try again. Thank you!

**Comment by alonsogarciapablo** [comment]
@ethervoid should we `DROP * FROM likes` as part of this? Is there any point on keeping the likes given that we're removing the feature?

**Comment by ethervoid** [comment]
@alonsogarciapablo as the first part with backward compatibility and to avoid possible side effects I want to keep the data as it is and tests without touching the database. So I just want to be sure that even having those "illegal" likes the app behaves correctly. After that we are going to do the phase two which is create/run the rake to remove the likes and start from the scratch with favorites

**Comment by alonsogarciapablo** [comment]
Hola! I just deploy this to staging (http://deploy.int.cartodb.net/job/carto-deploy-to-a-new-staging-dedicated-instance/1324/) and I'm seeing the ❤️ in the actual Dashboard:

![image](https://user-images.githubusercontent.com/390398/52275713-9b3b7b80-2950-11e9-8ca7-4fc1404b2322.png)

I'm also seeing "something" in the /me public page:

![image](https://user-images.githubusercontent.com/390398/52275682-84952480-2950-11e9-95a1-488dc9640ab9.png)

**Comment by csubira** [comment]
Apparently, de assets version (`1.0.0-assets.39`) was not modified so the changes were not included. I just updated it (`1.0.0-assets.39-test`) to be tested and deployed a [new dedicated instance with it](http://deploy.int.cartodb.net/job/carto-deploy-to-a-new-staging-dedicated-instance/1325/ ). Let's check it out when ready!

**Comment by alonsogarciapablo** [comment]
Thank you @csubira!

**Comment by alonsogarciapablo** [comment]
I tried this again. I didn't see a single trace of ❤️s. 

Old Dashboard:

* Builder user
  * Dashboard:
    * Maps ✅
    * Datasets ✅
  * Public Profile
    * /me ✅
    * Maps ✅
    * Datasets ✅
* Editor user
  * Dashboard:
    * Maps ✅
    * Datasets ✅
  * Public Profile
    * /me ✅
    * Maps ✅
    * Datasets ✅

New Dashboard:

* Favoriting my own maps ✅
* Favoriting maps shared with me ✅
* Favoriting my own datasets ✅
* Favoriting datasets shared with me ✅

**Comment by ethervoid** [comment]
@alonsogarciapablo did you give a try to have users with likes from before to see if there is a problem?

**Comment by alonsogarciapablo** [comment]
No. The dedicated server already had the new code.

**Comment by ethervoid** [comment]
I've tested with likes for compatibility (having old likes in the new) and it's working. Tomorrow I'll deploy this changes

**Comment by jesusbotella** [comment]
Closing this issue as this has been merged already!

**Comment by alonsogarciapablo** [comment]
Ole! 🚀
