### ISSUE TITLE
Fix styles in invitation view

### ISSUE THREAD

**Issue by gonzaloriestra** [CartoDB/cartodb#14629]
### Steps to Reproduce
1. Go to organization settings - users (with an organization admin)
2. Click on "Add users" - "Invite user"

### Current Result
![invitation](https://user-images.githubusercontent.com/14979109/51676645-8ae1e300-1fd7-11e9-97f6-81ea2a716c6d.png)

### Expected result
The "invite users" button should be inside the grey bock from the middle, or without any background in case it's under the block.

@CartoDB/rt-managers

**Comment by jesusbotella** [comment]
AFAIK the content part should go all the way down until the button 🤔

**Comment by jesusbotella** [comment]
Merged!
