### ISSUE TITLE
Ghost tables: Error creating UserTable

### ISSUE THREAD

**Issue by oleurud** [CartoDB/cartodb#14639]
### Context
It seems when someone is creating a ghost table, sometimes, we are creating a race condition

### Steps to Reproduce
https://rollbar.com/carto/CartoDB/items/37219/

### Current Result
Error: Ghost tables: Error creating UserTable

### Expected result
Everything is fine

**Comment by javitonino** [comment]
Parking this for now since we are going to revamp Ghost Tables in the near future.
