### ISSUE TITLE
Make sure geocoder cache works as expected

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#1464]
We must be sure we're doing it right with the geocoder cache, specially for the high-res. Also consider a "negative cache" if not done yet.

**Comment by juanignaciosl** [comment]
I've checked it works (you won't trigger a second search if it's not needed). If there's no specific error or known problem I'd close it, and maybe open another one with that negative cache idea. Do you agree, @rafatower ?

**Comment by rafatower** [comment]
I do.
