### ISSUE TITLE
Review geocoding stats

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#1465]
We need a unified view of geocoding stats, including internal, high-res and guessing, in a consistent manner.

**Comment by juanignaciosl** [comment]
Task:

1. Distinguish between requested geocodings and guessed geocodings.
2. Improve current panel.

@rafatower will improve this issue.

**Comment by rafatower** [comment]
Geocoding dashboard, "as is": http://ela01.useb.cartodb.net/#/dashboard/elasticsearch/Geocoding
