### ISSUE TITLE
Shared maps issues

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#14658]
### Context

* I have found several issues related to `Share maps with you`:

a. Broken thumbnails 
b. When going back to `Home`, `Share maps with you` appears instead of `Your maps`
c. Then it is not possible to change the filters to `Your maps`

### Steps to Reproduce

1. Click on `View all maps`
2. Filter maps by `Shared with you`
3. Go back to home
4. Filter map section to `Your maps`

### Current Result

a. All thumbnails are broken. It looks like they are tyring to get the static map from a template with the wrong user (it should point to the owner, not "me"):

![shared-maps](https://user-images.githubusercontent.com/5215798/52481127-f322ee00-2bad-11e9-94a0-bbef2998732a.png)

b. Shared with you appears instead of your maps

![home](https://user-images.githubusercontent.com/5215798/52481426-cae7bf00-2bae-11e9-8be0-04c54412b883.png)

c. You cannot change the filter

### Expected result

a. Thumbnails or placeholders should appear
b. Your maps should be shown
c. It should allow you to change the filters

### Browser and version

* Ubuntu 16, Chrome 67

**Comment by jesusbotella** [comment]
Fixed!
