### ISSUE TITLE
Updating recent content when deleting datasets and maps

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#14662]
### Context

Beta testing the new dashboard.

### Steps to Reproduce

1. Go to your dashboard home
2. Delete a dataset (test also one that is used in a recent map) or map which was recently used
3. The list of maps and datasets are updated, but the recent content is not

### Current Result

![delete-map](https://user-images.githubusercontent.com/5215798/52565252-9f5f1180-2e06-11e9-915c-a226231e744f.gif)

### Expected result

* Recent content should be updated.

### Browser and version

* Ubuntu 16, Google Chrome 67

**Comment by csubira** [comment]
Acceptance done! 
Steps followed:

1. Login with new account in staging.
2. Create new map with shared dataset.
3. Duplicate new map -> check that new map appears in recent content
4. Delete new map -> check that new map does not appear in recent content anymore
5. Duplicate dataset -> check that new dataset appears in recent content
6. Delete new dataset -> check that new dataset does not appear in recent content anymore

**Comment by ramiroaznar** [comment]
@csubira is this fixed then?

**Comment by jesusbotella** [comment]
Not yet. I am waiting for the tests to pass before merging it.

**Comment by jesusbotella** [comment]
Now it is! 🎉
