### ISSUE TITLE
Error when deleting a user as an org admin

### ISSUE THREAD

**Issue by alrocar** [CartoDB/cartodb#14677]
### Context
As an org admin when I delete a user from the dashboard UI and try to create another with the same username or email, I get an error saying the username or email is taken

### Steps to Reproduce
1. Login as an org admin
2. Create a user from Your Organization > Users > Create user
3. Delete that user
4. Create another user with the same username or password

### Current Result
You get an error

### Expected result
It should work

### Additional info
I've checked that the user is removed from cartodb but not from central.

This maybe related to the recent upgrade to Rails 4.

Additional traces provided:

- https://rollbar.com/carto/CartoDB-Central/items/4006/
- https://rollbar.com/carto/CartoDB-Central/items/13209/

Summoning @ramiroaznar as RT 🤠 and @alonsogarciapablo as dashboard owner for triaging

**Comment by ramiroaznar** [comment]
@alrocar good catch! next time remember to use @CartoDB/rt-managers

**Comment by ramiroaznar** [comment]
cc @javitonino I think this is on your roof

**Comment by alrocar** [comment]
We've been taking a look at the traces and it seems an error that has been there for some weeks, so maybe the traces are unrelated.

We are going to deploy to production tomorrow morning the branch were I found that error. Let's wait for it, and I'll test it again this time in production to see if it still happens.

I'll update this issue accordingly.

**Comment by ramiroaznar** [comment]
@jgoizueta why did you move this one to Infra?

**Comment by jgoizueta** [comment]
Hey, I've checked this with current production and couldn't reproduce it.
@alrocar I followed your steps and I worked well, no error. Do you think this is OK now?

**Comment by alrocar** [comment]
It should be OK then. Closing.
