### ISSUE TITLE
Update Node & Ruby version in the documentation

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartodb#14687]
### Context

We recently updated Node to v10.15.1 and Ruby to v2.4.5, we should therefore update the documentation.

File example:

https://github.com/CartoDB/cartodb/blob/master/doc/manual/source/install.rst#nodejs

**Comment by jesusbotella** [comment]
We can leverage that issue to update precompile assets documentation command to `npm run build:dev` instead of grunt.

**Comment by javitonino** [comment]
I think everything is up to date now: https://github.com/CartoDB/cartodb/pull/14692/files

Can we close this?
