### ISSUE TITLE
[Ghost tables] Visualization backup revamp

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/cartodb#14698]
Deprecate the current visualization backups a.k.a visualization cemetery and create a new one that stores the deleted layer/maps .carto JSON in the database

**Comment by ethervoid** [comment]
I've been reviewing this part and I have some questions @javitonino:

- We have two `VisualizationBackup` services: 1 and 2. Is safe to revamp/remove version 1 and adapt to our current requirements?
- If I'm not mistaken we should use version 2 to get the visualization's JSON and store it in the `VisualizationBackup` table. Is that right?

**Comment by javitonino** [comment]
Yes and yes :rocket: 

VisualizationsExportService is the old one that creates a VisualizationBackup model with the vizjson.
VisualizationsExportService2 is the new one (.carto) that returns a JSON with all metadata (akin to mapcaps).

In fact, you can look at mapcaps since this implementation will probably be very similar to this new backup system (could we reuse some code? not sure).

**Comment by ethervoid** [comment]
Cool thank you!

**Comment by oleurud** [comment]
After looking at this issue, the doc and the code the final objective is to save a visualization with `VisualizationsExportService2Importer` without dataset into `visualizations_backup` table before ghost table deletes a visualization table.

Right now, we are saving an `export_vizjson` in the `visualizations_backup` table. Should we stop this? should we keep these records? 

A solution could be to change the current visualization backup hooked `before_destroy` in the Visualization model, using `VisualizationsExportService2Importer`. Is not it?

**Comment by javitonino** [comment]
The vizjson is almost worthless as a backup since it can't be recovered via automated means. Feel free to get rid of it and all existing data. We have never recovered one of those because it's basically impossible.

> A solution could be to change the current visualization backup hooked before_destroy in the Visualization model, using VisualizationsExportService2Importer. Is not it?

I think that should be possible, yes.

**Comment by oleurud** [comment]
These are the task I am going to implement. If you see something wrong or forgotten, ping me:

- [ ] Stop current backups disabling FF `visualizations_backup`
- [ ] Remove FF `visualizations_backup` and the code behind it
- [ ] Drops `visualizations_backup` & create again (changing the `export_vizjson` to a new one more generic like `export`). Or maybe removing data and altering the column name.
- [ ] Use `VisualizationsExportService2Importer` in `before_destroy` of the Visualization model
- [ ] Make something similar to the previous step with the Layer model.
- [ ] Deploy

**Comment by oleurud** [comment]
:rocket:
