### ISSUE TITLE
[Ghost tables] Feature flag event trigger creation

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/cartodb#14697]
Create `ghost_tables_trigger_disabled` restricted feature flag. The users with it won't have the event trigger installed.

- [x] feature flag https://github.com/CartoDB/cartodb-central/pull/2427
- [x] new user: will have the event trigger. We should call the event trigger creation (only if is an org admin or regular user)
- [x] install event trigger rake: a rake that receives a usernames list. For each user, (only if is an org admin or regular user) we will create it if it doesn't have the feature flag `ghost_tables_trigger_disabled` 
- [x] uninstall event trigger rake: a rake that receives a usernames list. For each user drops the event trigger (ensure it is not a problem if the user no longer has the trigger)
- [x] test it

As a final result of the task we will be able to:
- Add event trigger to everybody with some exceptions
  - Add feature flag to exceptions
  - Run the event trigger instalation rake (applies to users without FF)
- Remove event trigger to some users
  - Add feature flag to these users
  - Run the event trigger deletion rake (applies only to users with FF)
- Add event trigger to initil exceptions
  - Remove feature flag from exceptions
  - Run the event trigger instalation rake (applies to users without FF)

**Comment by oleurud** [comment]
After talking offline, the idea will be adding a FF to disable the trigger creation. Changing the main comment to reflect it.
