### ISSUE TITLE
Error creating an org user

### ISSUE THREAD

**Issue by oleurud** [CartoDB/cartodb#14691]
### Context
When you are creating a new user in an organization (`/user/carto/organization/users/new`), when the app requests you the admin user password, if you press the `enter` key from your keyboard, you are redirected to an unexisting route instead of sending the POST to the good one

### Steps to Reproduce
1. Create an organization or use an existing one
2. Go to the new org user form in the dashboard (`/user/carto/organization/users/new`)
3. Fill the new user data
4. When the admin user password is requested, write it and press `enter` in your keyboard

### Current Result
Error 404, route not found

### Expected result
The user is created

### Browser and version
I am using Linux and Firefox. It seems it is not happening in Chrome. We are testing with LastPass extension installed and active, this should be checked just in case.

cc/ @CartoDB/rt-managers

**Comment by ramiroaznar** [comment]
@javitonino is this a RT issue?

**Comment by javitonino** [comment]
Not really RT (a user has not complained about this yet) but I'd say it's important to review. Anyway, since I'm almost sure this is frontend, passing the melon to @VictorVelarde

**Comment by csubira** [comment]
@oleurud could you specify Firefox version?

**Comment by oleurud** [comment]
Firefox Quantum `65.0.1`

**Comment by jesusbotella** [comment]
I am pretty sure that this is not our fault :P

That view is rendered via Ruby on Rails and the only thing that is handled via JS in that view is the password validation to before submitting the form.

So, I couldn't reproduce the error, but I am almost sure that we have nothing to do with it 😁

**Comment by ethervoid** [comment]
This must be fixed in some way, I can't reproduce it.
