### ISSUE TITLE
Scroll not clickable in add datasets modal

### ISSUE THREAD

**Issue by gonzaloriestra** [CartoDB/cartodb#14704]
### Steps to Reproduce
1. Click on "Add dataset"
2. Go to "DATA LIBRARY" tab
3. Scroll down to the bottom
4. Try to click on the scroll bar

### Current Result
The bottom part of the scroll bar is not clickable because the footer overlaps it.

![footer_scroll](https://user-images.githubusercontent.com/14979109/53413083-5fce2300-39cb-11e9-976b-63c6d9d30e10.png)

### Expected result
It should let you use the scroll bar.

### Browser and version
Chrome 72.0.3626.81 (Build oficial) (64 bits), Ubuntu 18.10.

### Additional info
It happens the same with any subview including scroll, like "CONNECT DATASET", "YOUR DATASETS" or "SHARED WITH YOU".

@CartoDB/rt-managers

**Comment by ramiroaznar** [comment]
I was not able to replicate it (Chrome v67).

**Comment by gonzaloriestra** [comment]
It's also happening to me with Firefox 65.0.

@ramiroaznar Are you clicking on the scroll bar?

**Comment by ramiroaznar** [comment]
yes! replicated
