### ISSUE TITLE
[Dashboard] Unclear LDS Renewal Date

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#14724]
@micagm reported that the LDS Renewal Date is a bit confusing right now.

![image](https://user-images.githubusercontent.com/390398/53954935-effd1e00-40d7-11e9-88d1-e74374ef70f3.png)

Text always says: "Your credits will be renewed on the Xth of *next* month" but they might be renewed this month (eg: in 5 days). 

If the credits will be renewed this month, we should say something like:

Your credits will be renewed on the Xth of *this* month.

cc: @kukukaka

**Comment by jesusbotella** [comment]
Just a proposal, it'd be much easier for us to put:

`Your credits will be renewed in X days (5th of each month)`

**Comment by alonsogarciapablo** [comment]
👏 👏 👏
