### ISSUE TITLE
[Dashboard] Invite User menu missing go back icon

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartodb#14739]
### Context

When an admin account enters into "Your Organization" menu to invite new users to the organization, there is a missing X icon to leave the current menu and go back to the organization menu. On the other hand, the Users Email input placeholder of the invite user menu seems to be cut.

![Screenshot 2019-03-13 at 10 26 56](https://user-images.githubusercontent.com/11177693/54267999-9767ce00-457a-11e9-988d-00126cad0969.png)

### Steps to Reproduce

1. Open an admin account from an organziation account
2. Access to "Your Organization" menu
3. Invite user
4. Missing X to leave the `invite user` menu.
5. The `User Email` input placeholder seems to be cut

### Expected result

The placeholder should show the complete sentence and there should be some element to move from the current invite user menu to the organization menu.

### Browser and version
Chrome 72.0.3626.121

**Comment by jesusbotella** [comment]
MERGED!
