### ISSUE TITLE
[Dashboard] Share with colleagues dialog is not rendered properly

### ISSUE THREAD

**Issue by jesusbotella** [CartoDB/cartodb#14743]
### Context
The share with colleagues dialog that is used in Dashboard is not rendering properly because the scroll doesn't reach the lowest part, so there's one user who cannot be selected for sharing.

I checked if this was first introduced within the migration but it wasn't. It was already present within the Editor Dashboard.

### Steps to Reproduce
1. Go to the dashboard with an organization user
2. Try to share a dataset with a colleague
3. Profit.

### Current Result
![Screen Shot 2019-03-13 at 15 58 20](https://user-images.githubusercontent.com/4319728/54289540-a9ad3080-45a9-11e9-9a01-1d6828aa7d31.png)

### Expected result
The modal rendered properly.

### Browser and version
Chrome.

**Comment by csubira** [comment]
It will be fixed here https://github.com/CartoDB/cartodb/pull/14761 as part of other dessign issues!

**Comment by alonsogarciapablo** [comment]
Is this 🚀 ? Can we close it?

**Comment by csubira** [comment]
Not yet! @alejandraarri is now working on it!

**Comment by alonsogarciapablo** [comment]
:+1: Thank you!
