### ISSUE TITLE
viz endpoint returns error 500 when querying with without/expired credentials

### ISSUE THREAD

**Issue by jesusbotella** [CartoDB/cartodb#14759]
`/api/v1/viz` returns 500 when querying without credentials or including expired credentials.

This might not be an urgent problem but I have seen some errors caused by this behaviour in TrackJS.

**Steps to reproduce**
1. Open two different windows of dashboard in your browser
2. Log out in one of those windows
3. Go to the other one, open DevTools, and change the dashboard tab
4. Enjoy your 500 error

This might be solved from a Backend POV given that we may not be able to parse the response string and distinguish that one from any other 500 error.

If we chose to return a 401 error, the dashboard request interceptor will handle that behaviour correctly and redirect that user to the login.

**Comment by alonsogarciapablo** [comment]
cc: @javitonino

**Comment by javitonino** [comment]
Yeah, I'm aware. This is working as intended, more or less. It's one of the problems of having the same endpoint for public and internal usage. We can discuss this inside the dashboard project next cycle.
