### ISSUE TITLE
[Dashboard] Error when duplicating shared dataset

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartodb#14750]
### Context

CARTO returns the error `relation "datasetName" does not exist` when we duplicate the shared dataset.

However, if a user copies the `username.tableName` from the SQL panel of the shared dataset , opens one of their own datasets (not a shared one) and writes `SELECT * FROM username.tableName` it can query the data from the shared dataset and then create a dataset from the query to duplicate the data.

### Steps to Reproduce

1. Open the `Shared with you` menu from the Data panel
2. Duplicate any dataset
3. CARTO returns an error.

### Current Result

CARTO returns an error.

### Expected result

CARTO should be able to duplicate a shared dataset

**Comment by alonsogarciapablo** [comment]
Thanks for reporting this @oriolbx!

**Comment by jesusbotella** [comment]
Fixed and merged!
