### ISSUE TITLE
Metrics endpoint returns 404 sometimes

### ISSUE THREAD

**Issue by jesusbotella** [CartoDB/cartodb#14757]
We have identified that `/api/v3/metrics` returns 404 errors sometimes when accessing dashboard and sending `visited_private_page` metric with page variable set to `dashboard`.

This request is made every time a user enters to the dashboard.

**Comment by alonsogarciapablo** [comment]
@jesusbotella good catch. Is this a 🔥 ?

**Comment by jesusbotella** [comment]
Nope. I suppose it's been happening since forever but I saw it on TrackJS 😂

**Comment by alonsogarciapablo** [comment]
@javitonino what do you think?

**Comment by javitonino** [comment]
We talked about this. Really, the only reason for this to happen is if you are not logged in when sending the request or something along those lines. Maybe if the user has just been deleted or something like that. Without an STR, this is very hard to pinpoint and I don't think it's very common.

**Comment by jesusbotella** [comment]
I don't know how I closed this issue 🤷‍♂️ I didn't even press any buttons 😂

**Comment by gonzaloriestra** [comment]
Having a look at the backend code, it seems like it only returns 404 when there's no session or the event name is not found (not the case).

I can only reproduce it this way:
1. Log in (`/metrics` is called with `visited_private_page` and returns OK)
2. Log out
3. Go back in the browser

Maybe this is why there are 404 in the logs... The solution could be to avoid calling it from the dashboard when there's no session :ping_pong:
