### ISSUE TITLE
[Dashboard] Deleted map is still listed after deleting associated dataset

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#14753]
Reported by @skgsergio:

> If you delete a dataset that is being used in a map it warns you and if you proceed it deletes the map. Ok, deleting the dataset (and therefore the map) triggers a reload of the dataset view but not of the maps view so the map still appears and if you click on it you get a 404 error. Is a bit ugly I think we should reload the map list too.

**Comment by alonsogarciapablo** [comment]
cc: @alejandraarri

**Comment by alejandraarri** [comment]
As it is a minor bug, I've fixed it in the PR above ☝️
