### ISSUE TITLE
CartoDB - db-create 

### ISSUE THREAD

**Issue by cosdrago** [CartoDB/cartodb#14766]
### Context
*Please explain here below what you were doing when the issue happened*

I was trying to install cartodb following the steps they provide for instalation but when I get to "RAILS_ENV=development bundle exec rake db:create" I get an error:
rake aborted!
No database asociated with Sequel::Model: have you called Sequel.connect or Sequel::Model.db.

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Got a clean virtualbox ubuntu 16.04
2. Follow the steps from this page https://cartodb.readthedocs.io/en/latest/install.html
3. When you execute RAILS_ENV=development bundle exec rake db:create you get the error

### Current Result
*Please describe here below the current result you got*

rake aborted!
No database asociated with Sequel::Model: have you called Sequel.connect or Sequel::Model.db.

### Expected result
*Please describe here below what should be the expected behaviour*

The expected result should be the creation of the database for development.

### Linux version

Ubuntu 16.04

### Additional info
*Please add any information of interest here below*

I dont see what could be the real problem because I have config/database.yml and is correct because is downloaded from CartoDB and should not give problems.

Even if that should be no problem I deleted the original file and created my own database.yml with everything defined correctly and the yaml code accepted by an yaml validator.Still gives me the same problems.

I tried executing the command with DATABASE_URL=/path/to/database.yml/ and got the same problems.

I tried to delete database.yml and got the same errors, like it didnt even matter if it was there or not. This might make you think that I have the files in the wrong place but I tried to execute deleting app_config.yml and got an error that the file is missing. These two have to be in the same folder so I guess the problem is not that one either.

For last I created the database on psql with the name I needed and everything worked after (db:migrate for example). The problem is that I need to create them using the database.yml file and not on my own.

**Comment by gonzaloriestra** [comment]
@cosdrago It should be fixed now, thanks for reporting!
