### ISSUE TITLE
User cannot self-delete organization

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#14763]
The `delete_me` endpoint does not allow organization deletion. That makes deleting your own organization not possible with the front/back split.

STR:
- Create an org
- Login as the owner
- Try to delete your account

**Comment by ethervoid** [comment]
So we want to allow the user to delete her own organization?

![Screenshot from 2019-03-28 17-58-37](https://user-images.githubusercontent.com/741240/55177274-24b63f80-5183-11e9-993d-c0e47607b0ae.png)

**Comment by javitonino** [comment]
Oh, that's right. Then, we should hide the delete your account link for application owners, right?

**Comment by ethervoid** [comment]
> your account link for application owners
I think you mean organization owners

So, we remove that message and that's all?

**Comment by javitonino** [comment]
Uhm, I meant remove the deletion link. But it seems it's not there. Maybe this got fixed in the meantime, or I was blind last week (entirely possible). I think we don't have to do anything. :/
