### ISSUE TITLE
Close session -> Log out

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#14778]
This is something that @FloBroderick brought up.

The account menu in the Dashboard has a link to "Log out":

![Screenshot 2019-03-26 at 12 29 06](https://user-images.githubusercontent.com/390398/54993885-3bae3380-4fc3-11e9-9c4e-fef9ef153f8f.png)

On the public pages (website, developer and help center), that same option is called "Close session":

![Screenshot 2019-03-26 at 12 29 16](https://user-images.githubusercontent.com/390398/54993887-3bae3380-4fc3-11e9-8b99-234839ccb181.png)

We should rename "Close session" to "Log out".

@CartoDB/rt-managers

**Comment by jesusbotella** [comment]
Deployed and merged!

![Screen Shot 2019-03-29 at 11 00 32](https://user-images.githubusercontent.com/4319728/55225005-f0d62b00-5211-11e9-9842-30fccdb8b30b.png)

**Comment by alonsogarciapablo** [comment]
Thank you @jesusbotella! 💪
