### ISSUE TITLE
Make the Country column fill and freetext more intuitive 

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#1477]
This is my typical workflow 

![screen shot 2014-12-16 at 11 48 44 am](https://cloud.githubusercontent.com/assets/370259/5457581/a85fe402-8519-11e4-8c5a-324e7e6c0709.png)

You can see that instead of typing a column, I've just typed the USA, so now I'm like this,

![screen shot 2014-12-16 at 11 48 39 am](https://cloud.githubusercontent.com/assets/370259/5457615/efa3c5ea-8519-11e4-8a65-26b762b905b9.png)

Proposed fix,

1. Change the row text: **Enter the column containing country strings or enter a manual string"
2. Reduce the menu to a single text entry field that searches columns. 
3. Change the last menu thing that says "No matches found /n Free text input" to a clickable button that says, "Use literal text above as country name"

@michesteva do you think that menu wording makes sense?

cc/ @saleiva

**Comment by xavijam** [comment]
After one year and a modal redesign, let me close this. If we feel it is still not clear, let's open a new one :).
