### ISSUE TITLE
Radio buttons are not displayed correctly in connect dataset modal

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#14776]
Reported by @terrett101:

> When I try to add a synced dataset, the radio buttons that allow me to choose the frequency of updates are not centering the dot when I select them.

Here's a screenshot:

![image](https://user-images.githubusercontent.com/390398/54986260-968b5f00-4fb2-11e9-9ea3-c29dea1e5799.png)

cc: @CartoDB/rt-managers

**Comment by jesusbotella** [comment]
Merged and deployed!
