### ISSUE TITLE
 ogrDataSource.commit(); dosn't save into database in android

### ISSUE THREAD

**Issue by iceberg1369** [CartoDB/cartodb#14779]
### Context

I am trying to insert new metadata into shapefile. but when I call commit() on datasourse the changes does not get saved on the file and the the inserted element does not shown on the next time.

### Steps to Reproduce

    OGRVectorDataBase db = new OGRVectorDataBase(localDir + "/"+shpName+".shp", true);
    ogrDataSource  = new OGRVectorDataSource(proj, styleSelector, db, 0);
    vectorElementClickInfo.getVectorElement().setMetaDataElement("jjjjj", new Variant("YYYYYYYYYYYYYY"));
    ogrDataSource.commit();   <-- has no effect on actual shp file despite the file timestamp changes

### Current Result
I get the previous meta data list and the new one dosn't seems to be saved into db

### Expected result
 ogrDataSource.commit();  should persist new meta data data into file

### Additional info

    ogrDataSource.commit(); // <-- has no effect on database

**Comment by alrocar** [comment]
This issue is not related with this project sorry.
