### ISSUE TITLE
[Dashboard] Use same tag icon for cards and list views

### ISSUE THREAD

**Issue by gonzaloriestra** [CartoDB/cartodb#14773]
### Context
Cards and list views use a different tag icon (one is left oriented and the other right oriented):

![card](https://user-images.githubusercontent.com/14979109/54935408-888cfe00-4f20-11e9-84f3-ba3842933d93.png)
![list](https://user-images.githubusercontent.com/14979109/54935417-8c208500-4f20-11e9-8bea-9914c9ccb272.png)

Also, the tag from the list view doesn't seem to be horizontally centered with the label, and I'd say it needs a bit more separation.

### Steps to Reproduce
Having at least one map with a tag:
1. Go to Maps tab
2. Alternate between cards and list view
3. Look at the tag icon

### Current Result
Different tag icon and alignment.

### Expected result
Same styling.

@CartoDB/rt-managers

**Comment by jesusbotella** [comment]
The tag icon mismatching thing and the separation between the icon and the tag itself is more of a design question. Let's ask them @CartoDB/design-team.

The vertical alignment I'd say is quite good, but given the fact that the tags are lowercase it may look it as if it was not perfectly aligned. Let's ask design team as well :P

**Comment by urbanphes** [comment]
Hey, good point @gonzaloriestra 👏 

We should use the same icon with the same position to identify a concept, in this case, "Tags". The position oriented to the right, 

<img width="150" alt="image" src="https://user-images.githubusercontent.com/14546701/55156975-9084b200-515b-11e9-9dee-27a755c8592b.png">

it looks more integrated with the text and easiest to relation both elements, icon +  text.

When we changed the oriented on the card version, we can view if the vertical alignment is good or not.

**Comment by jesusbotella** [comment]
I've just changed the icon in the vertical cards! What do you think?

![Screen Shot 2019-03-28 at 16 19 43](https://user-images.githubusercontent.com/4319728/55169638-722bb000-5175-11e9-87c1-a47484d6a74f.png)

I've moved one pixel down the icon on the condensed cards. What do you think?
![Screen Shot 2019-03-28 at 16 22 14](https://user-images.githubusercontent.com/4319728/55169839-c20a7700-5175-11e9-96db-150ba0f8aed4.png)

**Comment by gonzaloriestra** [comment]
I still think the icon not perfectly centered with the text in both views... :male_detective: 

But the expert is @urbanphes

**Comment by alejandraarri** [comment]
Changed the vertical alignment of the icon in maps in condensed view, and also flipped the icon in `View your tags` button and in `Your tags` title.

**Comment by gonzaloriestra** [comment]
I don't see the new icon in production, has this been already deployed?

**Comment by alejandraarri** [comment]
Sorry for the delay. I was waiting to deploy 2 fixes at the same time but is still in CR, so deploying it now.

**Comment by gonzaloriestra** [comment]
Don't worry, there's no hurry at all. But maybe we shouldn't close issues until they are totally finished to avoid confusions. Thanks! :slightly_smiling_face:

**Comment by gonzaloriestra** [comment]
I can see the changes now, it looks perfect to me :ok_hand:

**Comment by alejandraarri** [comment]
Ok, I'll keep that in mind. You can already check new icons in production. 🚀
