### ISSUE TITLE
[Dashboard] Extra API call in global search

### ISSUE THREAD

**Issue by gonzaloriestra** [CartoDB/cartodb#14774]
### Steps to Reproduce
1. Go to the global search in the dashboard
2. Write something and press enter quickly (without waiting for the preview)

### Current Result
It makes 3 API calls:
- Map search
- Dataset search
- Map/dataset search (preview) with an empty pattern: `api/v1/viz//?types=derived%2Ctable&per_page=4&q=`

### Expected result
Only 2 API calls, for map and dataset search.

@CartoDB/rt-managers

**Comment by jesusbotella** [comment]
Merged and deployed!
