### ISSUE TITLE
CSS issues in Groups and Add groups panels

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#14786]
**Steps to reproduce:**

- Login to CARTO with an admin account.
- Go to the Organization settings.
- Click "Groups"

**Current result:**

- There are some CSS issues:

![image](https://user-images.githubusercontent.com/390398/55171846-6215cf80-5179-11e9-9367-bf8e898cddcc.png)

- If you click "Add users" there are also some CSS issues:

![image](https://user-images.githubusercontent.com/390398/55171823-57f3d100-5179-11e9-84e0-90df87b3029c.png)

cc: @CartoDB/rt-managers

**Comment by jesusbotella** [comment]
Do you consider the hovering blinking an issue?

![Kapture 2019-04-04 at 9 48 23](https://user-images.githubusercontent.com/4319728/55538518-e8bd3600-56be-11e9-88bb-c84d650ab520.gif)

Could you please describe which issues do you see so that I don't miss any of them?

**Comment by alonsogarciapablo** [comment]
I spot two things:

1. Things shouldn't move when you hover the user.
2. The maps and datasets icons are too close to the texts (0 maps and 0 datasets).

**Comment by alonsogarciapablo** [comment]
About 1., I'm not sure what the right behaviour should be. @kukukaka might know... should the padding change when user mouses over that box?

**Comment by kukukaka** [comment]
As Pablo said the objects shouldn't move. I guess the best option would be to add to the rest state a 16px padding left and right, and keep it the same at hover and selected.

Also, the icon + label at the right of the card should have some spacing to separate the text from the icon (8px).

**Comment by alejandraarri** [comment]
User cards are displaying correctly now, without blinking issues when hovering. Also corrected the header in the "Add users" dialog so that the text is not cut.
