### ISSUE TITLE
[Dashboard] Copy dataset name button

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/cartodb#14809]
### Context
This is a feature request. We have found that it is not easy to copy the name of a dataset because the element is a link.

### Current Result

![](https://user-images.githubusercontent.com/2227572/55564584-7ff2af80-56f8-11e9-845b-4ec0a175c471.png)

### Expected result

So the proposal is to add a "copy button" near the favorite action to copy the name of the dataset.

![](https://user-images.githubusercontent.com/2227572/55564677-b29ca800-56f8-11e9-8a46-699e6b6f8fac.png)

**Comment by alonsogarciapablo** [comment]
Thanks @Jesus89

**Comment by alrocar** [comment]
Already in production
