### ISSUE TITLE
Can contribute with Spanish translation

### ISSUE THREAD

**Issue by johnfelipe** [CartoDB/cartodb#14830]
Hi pal, pls tell me how contribute for Spanish translation

**Comment by alonsogarciapablo** [comment]
Hey @johnfelipe. Thanks a lot for your offering, but there isn't a way for you to contribute a translation. Sorry about that!

**Comment by johnfelipe** [comment]
Is in roadmap or next features i18n?

**Comment by alonsogarciapablo** [comment]
Not something we will be working on in the short term. Sorry!

**Comment by johnfelipe** [comment]
Then only English will be official language?

**Comment by alonsogarciapablo** [comment]
Yes, English is the official language now.
