### ISSUE TITLE
[Professional Plan] Implement limits for `table_quota`

### ISSUE THREAD

**Issue by alrocar** [CartoDB/cartodb#14860]
Most likely this is already working but:

1. Check it
2. Report proper exceptions. Rephrase the error message so that the user understand what's happening.
3. Check we are covered by tests cases

**Comment by gonzaloriestra** [comment]
It seems like backend it's already well covered (also with tests). There's no way from the dashboard to create a dataset when the limit is reached. It's returning a 400 error with `{"errors":["You have reached your table quota"]}`.

The frontend is showing a proper message (`Over account table limit, please upgrade`) most of the times:
- Import a dataset
- Import a zip with more datasets than allowed
- Import a .carto with more datasets than allowed
- Duplicate dataset
- New map importing a dataset

When you add a new layer, it's showing the error `Could not add layer`. It could be more specific.

And when you create a new empty dataset or map, it gets waiting forever. We should show a message there.

@csubira @alejandraarri

**Comment by alonsogarciapablo** [comment]
👍

**Comment by alonsogarciapablo** [comment]
Out of curiosity... what happens if I "Import a .carto with more datasets than allowed"? Are some datasets imported before the limit is reached? Thanks!

**Comment by gonzaloriestra** [comment]
It throws an error and nothing is done (and the same when importing a zip).

**Comment by alrocar** [comment]
All the cases mentioned in this issue are being solved in this [issue](https://github.com/CartoDB/cartodb/issues/14921)

Closing then
