### ISSUE TITLE
[Professional Plan] Update trial period banner for account and profile static pages

### ISSUE THREAD

**Issue by csubira** [CartoDB/cartodb#14873]
`/profile` and `/account` pages of user information in dashboard are static pages served from the rails app.
On current Personal30 plan they show a banner with the remaining days to end the trial and a link to add a payment method that links to `/update_payment`

<img width="1222" alt="Screen Shot 2019-05-09 at 13 12 07" src="https://user-images.githubusercontent.com/26403479/57453727-6698d200-7267-11e9-8351-e28597b85d14.png">

### Tasks to do:

- Set text and variables to show banner with remaining days from Professional Trial plan

**Comment by alonsogarciapablo** [comment]
We already tested this as part of #2491. Anything else that we need to test?
