### ISSUE TITLE
Embedded builder map overflows on iOS

### ISSUE THREAD

**Issue by albertoac** [CartoDB/cartodb#14877]
### Context
When open a map on Safari for iOS, if the map name is too long, it will overflow and get out of the container (even if you set the map width to 100%)

![image](https://user-images.githubusercontent.com/4774531/57524464-20f00e00-7328-11e9-8771-591ae4b5a4a1.png)

### Steps to Reproduce

Open a page with an embed builder map and a long name.

### Expected result
As in android or desktop, it should fit the container.

![image](https://user-images.githubusercontent.com/4774531/57524668-ca370400-7328-11e9-83d0-f27388949543.png)

### Browser and version
iPhone 6s with iOS 12.1
iPhone XR run on simulator with iOS 12.1

**Comment by albertoac** [comment]
@CartoDB/rt-managers

**Comment by alejandraarri** [comment]
Is this still happening? I did a quick test in my iPhone and couldn't reproduce it.

**Comment by albertoac** [comment]
Hello,
I just tested and yes, it's still happening. To be more specific, the problem was tested in this page https://carto.com/platform/data-enrichment/ changing the name in this map https://public.carto.com/builder/b15a27e6-31c4-4923-893c-f95644b09d81/settings
