### ISSUE TITLE
Config flag for `use_https` to allow it outside prod/staging

### ISSUE THREAD

**Issue by nballenger** [CartoDB/cartodb#14888]
I'm trying to test a bug that only appears while using the application in prod, over SSL. In setting up a local dev environment I discovered that post-login, all pages automatically use HTTP rather than HTTPS for redirection and URL generation.

It looks like that's because in `config/initializers/carto_db.rb`, the `use_https?` method checks for the environment being prod or staging, and won't use https unless one of those is true:

https://github.com/CartoDB/cartodb/blob/df8f60f8c5eeec464a35c700ab4ff441dbdb6310/config/initializers/carto_db.rb#L245-L247

It would be very useful to have a flag in `app_config.yml` for using https, to allow it to be turned on in dev without changing the Rails env. Something like:

```Ruby
  def self.use_https?
    Rails.env.production? || Rails.env.staging? || Cartodb.config[:use_https]
  end
```

**Comment by gonzaloriestra** [comment]
This will be fixed by https://github.com/CartoDB/cartodb/pull/15716

**Comment by owayss** [comment]
Fixed in https://github.com/CartoDB/cartodb/pull/15716.
The config flag `ssl_required` can now be used to turn on/off the HTTPS redirects that were previously tied to the Rails' environment.
https://github.com/CartoDB/cartodb/blob/master/config/app_config.yml.sample#L18-L19
