### ISSUE TITLE
Infowindow template building error

### ISSUE THREAD

**Issue by gonzaloriestra** [CartoDB/cartodb#14906]
### Context
The public profile view is not working for (at least) a user:
https://rollbar.com/carto/CartoDB/items/38129/

### Steps to Reproduce
1. Visit the request URL from the Rollbar link

### Current Result
500 error

### Expected result
It should show the public profile of the user

### Additional info
It seems like it fails here while opening the template: https://github.com/CartoDB/cartodb/blob/364b4e448dd5b1c1547c37ca2d9cbf30b64b140e/app/controllers/carto/api/infowindow_migrator.rb#L90

Maybe we can just return the fallback template if it's not found.

@CartoDB/rt-managers

**Comment by alrocar** [comment]
https://rollbar.com/carto/CartoDB/items/38279/

**Comment by gonzaloriestra** [comment]
Closing in favor of https://app.clubhouse.io/cartoteam/story/83587/infowindow-template-building-error
