### ISSUE TITLE
Embeds attribution character and OSM link error

### ISSUE THREAD

**Issue by jsanz** [CartoDB/cartodb#14914]
### Context

Using an interrogation mark for the attributions widget on embeds may be a bit confusing and it'd be probably better tu use the more standard `(C)` identifier.

### Steps to Reproduce

This is happening for all BUILDER embeds.

### Current Result

![image](https://user-images.githubusercontent.com/188264/58469562-026b7e80-8140-11e9-9ac0-c708e177e461.png)

### Expected result

* Consider changing the question mark by the :copyright: character.

### Browser and version

All browsers. ~~The user that reported this concern also experienced problems on opening the attribution control on **Firefox 67** but I haven't been able to reproduce with the same browser version.~~

### Additional info

Concern raised from this [twitter thread](https://twitter.com/xurxosanz/status/1133311008049717249).

**Comment by jsanz** [comment]
Sorry, the reported bug is not about the widget opening but about the `OpenStreetMap` link, that it's actually not working

![image](https://user-images.githubusercontent.com/188264/58470057-2b404380-8141-11e9-9afa-0a037f037860.png)

I think we can address both the enhancement and the link error on this issue, no need to open another one for the OSM link fix.

**Comment by JaumeFigueras** [comment]
Also Chrome 74 does not follow OSM link.

**Comment by JaumeFigueras** [comment]
As discussed on twtitter and on OSM-Cat Telegram group: It is useful that the attribution widget appears condensed under the copyright icon when using small devices requiring user interaction to show it in full size. Under bigger screen sizes as a laptop or desktop the behaviour should be the opposite, appear in its full size and require user interaction to be condensed.

**Comment by jsanz** [comment]
Nice! Thanks for updating the character and expanding by default the attribution, very much appreciated! 😊

**Comment by JaumeFigueras** [comment]
Thanks!!
