### ISSUE TITLE
Ghost tables fails to register a renamed table

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#14910]
Regarding ghost tables, I managed to reproduce a problem (which does not appear what affected the user directly but might be related):

```
u=Carto::User.find_by_username('worg1')
gtm=Carto::GhostTablesManager.new(u.id)

# Existing status
u.in_database.execute("CREATE TABLE abc(); SELECT CDB_CartodbfyTable('worg1', 'abc');")
gtm.link_ghost_tables_synchronously

# Replace
u.in_database.execute("CREATE TABLE abc_new(); SELECT CDB_CartodbfyTable('worg1', 'abc_new');")
gtm.link_ghost_tables_synchronously
u.in_database.execute("BEGIN; ALTER TABLE abc RENAME to abc_old; ALTER TABLE abc_new RENAME TO abc; DROP TABLE abc_old; COMMIT;")
gtm.link_ghost_tables_synchronously

# No tables are registered at this point.
```

We will take a look, but it will take time (I'm guessing weeks). In any case, this is just about the privacy.

The overloaded DB looks more like an infra task (maybe we should split the ticket?)

_Originally posted by @javitonino in https://github.com/CartoDB/support/issues/2025#issuecomment-487854616_

**Comment by ethervoid** [comment]
Is this happening with the new Ghost tables?

**Comment by javitonino** [comment]
Yes, just wait long enough between SQL commands. It seems the problem is in the ghost tables code itself (not the way it is triggered).

**Comment by gonzaloriestra** [comment]
Closing in favor of https://app.clubhouse.io/cartoteam/story/83536/ghost-tables-fails-to-register-a-renamed-table
