### ISSUE TITLE
Empty navigation bar in API keys page

### ISSUE THREAD

**Issue by gonzaloriestra** [CartoDB/cartodb#14915]
### Steps to Reproduce
1. Disable engine for a user and log in
2. Go to `/your_apps`

### Current Result
![missing-menu](https://user-images.githubusercontent.com/14979109/58473707-9726aa00-8149-11e9-83f1-3df1c20227e7.png)

### Expected result
It should show all the navigation bar options: Home, Maps, Data...

@CartoDB/rt-managers

**Comment by csubira** [comment]
Hey! I can give it a look (since we changed some stuff in that page as part of the Pro Plan project)!

**Comment by alonsogarciapablo** [comment]
Great catch @gonzaloriestra!

**Comment by csubira** [comment]
Merged and deployed!
