### ISSUE TITLE
Catch all quota errors

### ISSUE THREAD

**Issue by alrocar** [CartoDB/cartodb#14921]
🔴 change privacy from within BUILDER  (403 error console)
🔴 change privacy from modal dialog within BUILDER  (403 error console)
🔴 change privacy from dashboard  (generic modal error + 403 in console)
🔴 duplicate a dataset from dashboard (modal with unknown error and no text, can't be closed + 403 in console)
🔴 create empty dataset -> error 400 in the console
🔴 create empty map when there are no table quota -> error 400 in the console
🔴 add layer from new layer in BUILDER
💚 drag and drop .carto
💚 drag and drop table
💚 from dataset view -> duplicate
💚 from dataset view -> create from query
💚 sync from data library

**Comment by alonsogarciapablo** [comment]
Good job @alrocar! This is perfect.
