### ISSUE TITLE
[Professional Plan] Include limits metrics in quota & metrics section

### ISSUE THREAD

**Issue by alejandraarri** [CartoDB/cartodb#14923]
Now that we have a new plan that implements datasets and public maps limits, we have to add those metrics to the section to keep the user informed. This metrics will only appear in case the user's plan is the new Professional Plan. Backend has already modified the endpoint /me to provide this info in https://github.com/CartoDB/cartodb/issues/14862

![Screenshot 2019-05-30 at 16 08 40](https://user-images.githubusercontent.com/8669176/58638488-3d62e300-82f5-11e9-8ddf-56409b48c42c.png)

**Comment by alonsogarciapablo** [comment]
I'm opening a separate issue to add the links once the Help Center articles are in place.
