### ISSUE TITLE
[Professional Plan] Take trial users to /upgrade page if they click "Subscribe Now"

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#14956]
Trial users now see this when they login to their Dashboards:

![image](https://user-images.githubusercontent.com/390398/59199964-7de51b00-8b97-11e9-925f-ba269334941e.png)

The _Subscribe Now_ link takes users directly to this screen which gives little info about what the user is paying for:

![image](https://user-images.githubusercontent.com/390398/59200088-c1d82000-8b97-11e9-95cc-2a55446deabf.png)

Instead of pointing users to that form, we should point them to the /upgrade page, so they first see which "upgrade" options they have and what's included in each of the options.

![image](https://user-images.githubusercontent.com/390398/59200199-f8ae3600-8b97-11e9-9bdf-9c99d435d2fd.png)

--

This is related to https://github.com/CartoDB/cartodb-central/issues/2486.

cc: @csubira @alejandraarri

**Comment by csubira** [comment]
@CartoDB/rt-managers

**Comment by csubira** [comment]
Central part here: https://github.com/CartoDB/cartodb-central/pull/2505

**Comment by alonsogarciapablo** [comment]
It'd be great to check the lockout page and send users to /upgrade from there as well.

**Comment by csubira** [comment]
We just checked that links to /plan, so it can be left that way! Thanks for the heads up!
