### ISSUE TITLE
[Professional Plan] Duplicating and exporting/importing public maps create private maps

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#14954]
The new Professional Plan has a limit on the number of public maps you can have (10). By the default, new maps are private, but there are two circunstantes in which public maps can be created without the user explicitly specifying the privacy of the new map:

1. When a public map is duplicated, the new map is public.
2. When a public map is exported as a .carto and re-imported into the same or another account, the new map is public.

In both cases, the action will fail if the user has reached the limit of public maps, which is very limiting. It would be great if these two processes (duplicating and exporting/importing) could somehow make the maps private.

**Comment by alonsogarciapablo** [comment]
@alejandraarri and I were doing some tests with Google Drive and it works the way we're suggesting here. If you have a "public" document and "Make a copy" of it, the new copy is private.

**Comment by alrocar** [comment]
For the case of `.carto`, would it make sense saving the privacy in the `.carto` file in the first place?

**Comment by alonsogarciapablo** [comment]
Yep it might make sense, the only thing is that there're already a lot of public .carto files out there which hasn't been exported with this in mind (eg: Help Center Tutorials).

**Comment by alrocar** [comment]
yes, I know... in any case we are breaking compatibility (either in the export or in the import), not sure if anyone is using that `privacy` stuff stored in `.carto` files, for example to share maps with password or something like that.

**Comment by alonsogarciapablo** [comment]
Google Drive actually gives their users the option to "Share it with the same people":

![image](https://user-images.githubusercontent.com/390398/59195553-93087c80-8b8c-11e9-8a3f-40b4debb6008.png)

**Comment by alonsogarciapablo** [comment]
Closing for now. We'll reopen if this ends up being a problem.
