### ISSUE TITLE
Allow to receive a binary for the icon of an oauth app

### ISSUE THREAD

**Issue by cmongut** [CartoDB/cartodb#15018]
We could follow the same pattern we have when uploading the user's profile picture.

**Comment by alrocar** [comment]
I've taken a look at how the profile avatar works and it does a POST request to the `user/:id/assets` endpoint to get an absolute URL which is later sent to the user profile endpoint.

So it looks the workflow could be fully managed frontend side and the `oauth_apps` endpoint would just receive the `icon_url` in the same way as now.

**Comment by cmongut** [comment]
Ok, I close it then :)
