### ISSUE TITLE
Remove the X-Frame-Options deny for Kuviz

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/cartodb#15019]
We should remove the `X-Frame-Options: DENY` in the Kuviz controller. It should mimic the way we do for embeds for example

@CartoDB/rt-managers for priorization

**Comment by alrocar** [comment]
Is this still anything to be done?

**Comment by ethervoid** [comment]
AFAIK yes, it's needed for CARTOframes

**Comment by alrocar** [comment]
Thanks! moved to CARTOframes backlog then, since it will be better prioritized.
