### ISSUE TITLE
Trial banner appearing in Professional Plan paying accounts

### ISSUE THREAD

**Issue by alejandraarri** [CartoDB/cartodb#15046]
Trial banner is appearing in the Professional Plan paying user's dashboards saying that the trial will expire. This is because the frontend is receiving a `trial_ends_at` date with value  (I guess when they start to pay). And, although the received date is old having a value in `trial_ends_at` property means there is an active trial and so the banner appears. 

@ethervoid's quote:
>As you can see here we're returning the of `created_at` + 14 days in case the user's account is a `Professional` one but we should check if the user has an active subscription so we can return nil and identify that account as a regular one instead of a trial one.

Bug seen in issue https://github.com/CartoDB/support/issues/2163

cc @CartoDB/rt-managers

**Comment by alejandraarri** [comment]
I hadn't seen that property `show_trial_reminder ` before!! LOL 

Yes, it makes sense and simplifies a lot the logic in the frontend side. This would mean updating some frontend code that we can do in RT perfectly. So ping me when backend changes are ready so I start working on it.

**Comment by gonzaloriestra** [comment]
Fixed here: https://github.com/CartoDB/cartodb/pull/15470
