### ISSUE TITLE
bug at install on AWS

### ISSUE THREAD

**Issue by aginpatrick** [CartoDB/cartodb#15042]
I'm installing CARTO on AWS (following Michael Minn's excellent tutorial http://michaelminn.net/tutorials/carto-aws/). Did all the steps but I get an error when I try to start the processes.

Specifically, when I try to do the command :
cd cartodb && bundle exec script/resque > /dev/null &

I get the error: 
(/home/ubuntu/cartodb/config/app_config.yml): did not find expected key while parsing a block mapping at line 339 column 5

I *think* that organization should be uncommented in yaml file. I uncommented the line and reran the command. This time I get the following error:

/home/ubuntu/cartodb/app/controllers/carto/api/public/oauth_app_presenter.rb:30: syntax error, unexpected '.'
...es_by_category(oauth_app_user&.all_scopes)

Anyone can help?

**Comment by aginpatrick** [comment]
I realize that I got an error earlier in the process that I didn't catch at first. This is when I npm install in Windshaft-cartodb directory. They say in the docs that I should do sudo npm install -g yarn@0.27.5 followed by yarn install. I get the following error: 

npm ERR! Linux 4.4.0-1087-aws
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! @carto/mapnik@3.6.2-carto.16 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @carto/mapnik@3.6.2-carto.16 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @carto/mapnik package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build

**Comment by gonzaloriestra** [comment]
Hi @aginpatrick!

The tutorial you are following is a bit outdated. The syntax error from the first message points to a wrong Ruby version: we require 2.4. I recommend you to double-check the requirements here: https://cartodb.readthedocs.io/en/latest/install.html

If you find more installation issues, there is a forum for this kind of questions: https://groups.google.com/forum/#!forum/cartodb

I hope this helps. I'm closing as it doesn't look like a bug.

**Comment by jferencik** [comment]
Hello there,

i am tring ot install Windshaft  and hit the following issue:


905 verbose stack Error: @carto/mapnik@3.6.2-carto.16 install: `node-pre-gyp install --fallback-to-build`
905 verbose stack Exit status 1
905 verbose stack     at EventEmitter.<anonymous> (/data/undp/nodev14/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
905 verbose stack     at EventEmitter.emit (events.js:400:28)
905 verbose stack     at ChildProcess.<anonymous> (/data/undp/nodev14/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
905 verbose stack     at ChildProcess.emit (events.js:400:28)
905 verbose stack     at maybeClose (internal/child_process.js:1058:16)
905 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
906 verbose pkgid @carto/mapnik@3.6.2-carto.16
907 verbose cwd /work/ds/carto/Windshaft
908 verbose Linux 5.4.0-90-generic
909 verbose argv "/data/undp/nodev14/bin/node" "/data/undp/nodev14/bin/npm" "install" "@carto/mapnik"
910 verbose node v14.18.1
911 verbose npm  v6.14.15
912 error code ELIFECYCLE
913 error errno 1
914 error @carto/mapnik@3.6.2-carto.16 install: `node-pre-gyp install --fallback-to-build`
914 error Exit status 1
915 error Failed at the @carto/mapnik@3.6.2-carto.16 install script


the mapnik(nide-mapnik )  is installed. Also ruby 2.4

using node 14....could this be the issue?


thanks
