### ISSUE TITLE
Broken Link in Builder on Analysis toolbox

### ISSUE THREAD

**Issue by fberryman** [CartoDB/cartodb#15051]
### Context

There's a broken link in the Analysis view.

When going to add  a new analysis, in the "Add Columns to 2nd Dataset"  option, the "More Info" link gets a 404 error.

### Steps to Reproduce

1. Create a visualization
2. Go to add analysis
3. Click on 'more info' in the "Add Columns to 2nd Dataset" option

![Screen Shot 2019-08-12 at 11 34 33 AM](https://user-images.githubusercontent.com/3824953/62921643-93e6a600-bda9-11e9-9f23-a674759ac2ec.png)

**Comment by ztephm** [comment]
Currently that link goes here:
https://carto.com/help/building-maps/add-columns-from-second-dataset/

Here's where it should go instead:
https://carto.com/help/tutorials/add-columns-from-2nd-dataset/

**Comment by rjimenezda** [comment]
Fixed the redirection on the help center
