### ISSUE TITLE
Improve error message for datasets scopes

### ISSUE THREAD

**Issue by alrocar** [CartoDB/cartodb#15062]
### Context

See support [issue](https://github.com/CartoDB/support/issues/2170#issuecomment-522969461)

We are raising generic errors when a dataset scope is not valid, but for the case of a user not having access to an org admin dataset, we could be more specific, since this is something an application developer can solve on their own.

cc. @cmongut

**Comment by gonzaloriestra** [comment]
ClubHouse issue: https://app.clubhouse.io/cartoteam/story/83439/improve-error-message-for-datasets-scopes
