### ISSUE TITLE
Make datasets listing API to list GRANTED tables from other org users

### ISSUE THREAD

**Issue by alrocar** [CartoDB/cartodb#15065]
Related [issue](https://github.com/CartoDB/cartodb/pull/15043)

There are certain OAuth apps in which a number of datasets are managed by the org admin and then granted to the rest of the users of the organization.

Those datasets are not listed by `api/v4/datasets` thus an OAuth app does not know about them when requesting for the list of datasets of the user.

We might be able to reuse this [method](https://github.com/CartoDB/cartodb/blob/8bbe7c0325b34399bca390619bcdb19b39400a82/app/models/carto/api_key.rb#L194) to get the list of granted tables to the user.

Also it would be necessary to:
- Add the schema to the response, since not all tables might be in the user schema
- Add the grants to the table (read [r] or read/write [rw])

Related [issue](https://github.com/CartoDB/cartodb/issues/15013)

**Comment by gonzaloriestra** [comment]
Closing in favor of https://app.clubhouse.io/cartoteam/story/83456/make-datasets-listing-api-to-list-granted-tables-from-other-org-users
