### ISSUE TITLE
Bolt lock key (synchronizations / GTM)

### ISSUE THREAD

**Issue by oleurud** [CartoDB/cartodb#15074]
Coming from https://github.com/CartoDB/support/issues/2102 and the related PR https://github.com/CartoDB/cartodb/pull/15060

The problem was solved, but we think we can make some improvements to it as @gonzaloriestra explained https://github.com/CartoDB/cartodb/pull/15060#issuecomment-525238073

**Comment by gonzaloriestra** [comment]
Closing in favor of https://app.clubhouse.io/cartoteam/story/83515/bolt-lock-key-synchronizations-gtm
