### ISSUE TITLE
[DO] Rake to give access to a dataset

### ISSUE THREAD

**Issue by gonzaloriestra** [CartoDB/cartodb#15076]
Add a rake where:
- Perform validations. To be defined, but probably: DO access enabled for the user, API key permissions, dataset not purchased yet and not expired, right user plan and status...
- Save metadata in Central (see https://github.com/CartoDB/cartodb-central/issues/2559)
- Sync to redis
- Create dataset views in the Big Query user dataset ([doc](https://cloud.google.com/bigquery/docs/views), [Ruby client](https://www.rubydoc.info/github/google/google-api-ruby-client/Google%2FApis%2FBigqueryV2%2FBigqueryService:insert_table))

**Comment by alrocar** [comment]
Let's do the `index` endpoint as well. It'll be used by CF to get the list of purchased premium datasets for the user to be used directly in the enrichment method (without having to explore the catalog).

See this [issue](https://github.com/CartoDB/data-observatory/issues/170)

**Comment by alrocar** [comment]
For the POST method we decided this not to be a public API since it's not clear who is gonna call the endpoint (most likely from the dashboard).

By now we'll do a rake task for giving access to a list of datasets and the `index` method.
