### ISSUE TITLE
Too many columns or long column names can cause 414 Request-URI errors in query-rows-collection.js

### ISSUE THREAD

**Issue by lokkju** [CartoDB/cartodb#15085]
https://github.com/CartoDB/cartodb/blob/2651f112be719713ed9a58a9053ebb1c1a8bfc6d/lib/assets/javascripts/builder/data/query-rows-collection.js#L223

Because the opts.data is itself built dynamically from the provided query, checking the length of the original query isn't enough to determine if the URL length will be too long for a GET request.  For instance, the original query may be ```SELECT * from TABLE_A```, but if ```TABLE_A``` has either many columns or else columns with excessively long names, the expanded query can be quite large - easily over 1024 chars.

Perhaps the httpMethod function for this module should take a parameter of the expanded data that will actually be sent.

**Comment by alrocar** [comment]
Doesn't look like a backend issue. Moving to frontend.

**Comment by alejandraarri** [comment]
Fix deployed in production! 🚀
