### ISSUE TITLE
EUMAPI: User master api key in user resource (now only in users list)

### ISSUE THREAD

**Issue by pcaro** [CartoDB/cartodb#15102]
### Context
Using EUMAPI to create and manage users on a external app control panel.

### Steps to Reproduce

Now user api (field `api_key`) is present in user list results `<org>.carto.com/u/<org_owner>/api/v2/organization/dev/users/`  , but not in user detail `<org>.carto.com/u/<org_owner>/api/v2/organization/dev/users/<user>/`

We need to get that master key to get later other user api keys using Auth API or to fake the user to call `/me` due to #15101

We need to call `users` endpoind and search the user now, which is slow an error prone.

Please, include that field on user detail endpoint too.

**Comment by pcaro** [comment]
@alrocar We talk about this too

**Comment by alrocar** [comment]
Actually, getting the master API key from the list endpoint is a bug.

Both methods `index` and `show` should return the same data, and that data does not include the user master api key.

See [this piece of code](https://github.com/CartoDB/cartodb/blob/ebecdf12694b03bfad82ef4663f6555b3b57e197/app/controllers/carto/api/organization_users_controller.rb#L17-L20). If you look at the `show` method, both delegate to `UserPresenter` `to_eumapi_poro` method.

Looks like the iterator in `index` is returning all the users data.

cc. @gonzaloriestra

**Comment by gonzaloriestra** [comment]
Yep, that looks like a bug. 

It should be `.map` instead of `.each` here:
https://github.com/CartoDB/cartodb/blob/ebecdf12694b03bfad82ef4663f6555b3b57e197/app/controllers/carto/api/organization_users_controller.rb#L18
