### ISSUE TITLE
Info about user MFA status in Enterprise API

### ISSUE THREAD

**Issue by pcaro** [CartoDB/cartodb#15101]
### Context
Creating/updating user using EUMAPI using organization owner api_key

Related: #14425

### Steps to Reproduce
You can not know if a user has MFA enabled or not

### Current Result

The problem:
Url: `<org>.carto.com/u/<org_owner>/api/v2/organization/dev/users/<user>/mfa/totp `
- If you do a POST on a user with MFA already set, it fails
- If you do a DELETE on a user with MFA disbled if fails

But you can **not** know if the user has MFA set or not previously!

### Expected result
A good response to GET  `<org>.carto.com/u/<org_owner>/api/v2/organization/dev/users/<user>/mfa/totp ` showing mfa status (now 404)

Or a `mfa_required` field in ``<org>.carto.com/u/<org_owner>/api/v2/organization/dev/users/<user>/`

**Comment by pcaro** [comment]
The new functionality I was talking you about @alrocar

**Comment by alrocar** [comment]
I've been taking a look at the [controller](https://github.com/CartoDB/cartodb/blob/master/app/controllers/carto/api/multifactor_authentication_controller.rb) and the exceptions give you the status of MFA.

- POST fails with error 422 message `Multi-factor authentication already exists` if MFA configured
- DELETE fails with error 422 message `Multi-factor authentication does not exist` if MFA not configured

I'm adding the get method in any case, also the `mfa_required` attribute in the list of users.
