### ISSUE TITLE
[Dashboard] - Data Observatory - Check pagination & ordering with backend (SQL API)

### ISSUE THREAD

**Issue by VictorVelarde** [CartoDB/cartodb#15112]
Currently there is no specific API to access DO dataset metadata catalog. SQL API can be used. Does it have any limitation?

**Comment by csubira** [comment]
Finally, we are using the same source of information that is used in Location Data Streams website page (via SQL API with `observatory` account)
Part of https://github.com/CartoDB/cartodb/issues/15115 implemented [here](https://github.com/CartoDB/cartodb/pull/15123)!
