### ISSUE TITLE
[Dashboard] Add Data Observatory catalog (III) - INTERACTIVITY

### ISSUE THREAD

**Issue by alejandraarri** [CartoDB/cartodb#15116]
## Context
https://github.com/CartoDB/product/issues/464

## Main tasks
- [x] Implement filter by category/country interaction
~~- [ ] Add tags element to disable radio buttons in datasets table header (Fixed header)~~

**Comment by csubira** [comment]
Dropdown component including properties/methods considering:

- [ ] Open/close
- [ ] Enable/disable
- [ ] Autocomplete
- [ ] Select with click/arrowUp/arrowDown
- [ ] Reset filter and options (x close in input)
- [ ] Limit height
- [ ] Positioning
- [ ] Slot to add comment at the end of the list
- [ ] Events emitted: selected(when item is selected), reset (when input content is deleted).

Connexion between dropdowns, premises:
### Status 1 (when first entering page):
- Input categories with placeholder, not showing reset X.
- Dropdown categories enabled and open.
- Input countries with placeholder, not showing reset X.
- Dropdown countries disabled and closed.
- No datasets list

### Status 2 (click/choose category):
Sends request to get countries list.
- Input categories filled, showing reset X
- Dropdown categories closes.
- Input countries with placeholder, not showing reset X.
- Dropdown countries enabled and open when clicking in countries input.
- No dataset list.

### Status 3 (click/choose country):

- Input categories filled, showing reset X
- Dropdown categories closes.
- Input countries filled, not showing reset X.
- Dropdown countries disabled and closed.

Sends request to get datasets.

- Dataset list


### Status 4 (reset choose category) 
-> Status 1

### Status 5 (reset choose country) 
-> Status 2
