### ISSUE TITLE
[Dashboard] Add Data Observatory catalog (I) - STRUCTURE

### ISSUE THREAD

**Issue by alejandraarri** [CartoDB/cartodb#15114]
## Context
https://github.com/CartoDB/product/issues/464

## Main tasks
- [x] Create new page (`/dashboard/datasets/location_data_streams`)
- [x] Create tabs component (to switch between _Your Datasets_ and _Location Data Streams_)
- [x] Add tabs component to _Your datasets_ page

**Comment by csubira** [comment]
@cmongut @urbanphes let me know here when we have a final name for the page (Data catalog, Data Observatory catalog ...) so I can start replacing the temporary content and the URL

**Comment by urbanphes** [comment]
@cmongut, What will be the definitive name?
