### ISSUE TITLE
Clone this table: prompted me to login and then did not clone

### ISSUE THREAD

**Issue by strk** [CartoDB/cartodb#1512]
Following the "clone this table" link from a public table of a user (great addition!) while not being logged prompted me to log. After logging in I was redirected to my own dashboard but I was not notified about what happened to the clone action I requested. Looking in my tables it doesn't appear like the table was cloned.

**Comment by xavijam** [comment]
Closing since we are using one-click app for cloning :) -> https://github.com/CartoDB/cartodb/pull/3632#discussion_r30303075
