### ISSUE TITLE
Cannot import geometry-less CSV table

### ISSUE THREAD

**Issue by strk** [CartoDB/cartodb#1514]
Uploading this table to CartoDB result in an error:

 'Unable to load data (2001)'

It's a geometry-less table, if that matters:

https://treekit.cartodb.com/api/v2/sql?filename=blockface_survey_live&q=SELECT+*+FROM+public.blockface_survey_live&format=csv&api_key=&skipfields=the_geom_webmercator

The import code for my account (strk): 837e4a06-bbbf-424e-8be7-c2bbae67475a

**Comment by iriberri** [comment]
Can't reproduce. The importer doesn't require the column `the_geom` or a geometry to be successful at the moment.
