### ISSUE TITLE
[Dashboard] Sticky table header has an offset

### ISSUE THREAD

**Issue by jesusbotella** [CartoDB/cartodb#15164]
### Context
Dataset's table sticky header has an unexpected offset from where it should be while scrolling.

<img width="1440" alt="Screenshot 2019-10-24 at 12 57 33" src="https://user-images.githubusercontent.com/4319728/67479276-069fb780-f65e-11e9-9680-377906559e60.png">

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Go to dashboard 
2. Scroll down to datasets section
3. See how sticky table header is misplaced

### Current Result
The header has an offset

**Comment by csubira** [comment]
PR to be reviewed by RT here: https://github.com/CartoDB/cartodb/pull/15157
