### ISSUE TITLE
[OAuth] SQL functions are not reassigned to the app owner role

### ISSUE THREAD

**Issue by gonzaloriestra** [CartoDB/cartodb#15160]
### Context
When you create a function from SQL API with an OAuth API key, the `oauth_reassign_tables_trigger` event trigger should change the ownership of the function to the app owner role, as it does with the tables.

### Steps to Reproduce
1. Request an OAuth token with `schemas:c` scope
2. Create a function with the SQL API: `CREATE FUNCTION hello_world() RETURNS text AS $$ BEGIN RETURN 'hello world'; END; $$ LANGUAGE PLPGSQL;`
3. Check the owner of the function (from psql: `\df+`)

### Current Result
The owner is a role like `carto_role_a7c5fa41caf250d1a2f2646e0f37c6d8`

### Expected result
The owner is a role like `carto_oauth_app_o_ab573e51-6c76-4969-822c-a8df3b9912d7`

### Additional info
Possibly related to https://github.com/CartoDB/cartodb/issues/15159

**Comment by alrocar** [comment]
How does this affect the Kepler integration? Are we using functions for the Kepler use case?

cc. @jesusbotella

**Comment by VictorVelarde** [comment]
Yes, I have checked and we do. We use a function to generate uuids for our PKs in some tables. Here it is the code: https://github.com/CartoDB/toolkit/blob/d9055b86fa6836b4a23917067b49baee92409567/packages/custom-storage/src/CustomStorage.ts#L47

In the project we rely on @carto/toolkit, which provides a CustomStorage. That's our abstraction on the top of SQL API to manage visualizations and datasets. 

In the case of kepler, the namespace is 'keplergl', so we end up having this function: keplergl_create_uuid

**Comment by VictorVelarde** [comment]
After some conversations with @alrocar, it looks like we could have a fix soon, so no need to make a work-around

**Comment by VictorVelarde** [comment]
@esloho After last week deployment & acceptance with kepler, I think we can now close this issue, right?. Feel free to reopen if anything is missing.
