### ISSUE TITLE
Enable Storage API option in BigQuery Connector

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/cartodb#15168]
This will add a connector provider for BigQuery. This is basically #14790 reloaded

Initially we will use an ODBC driver as in the former implementation, but we plan to use a BQ-specific FDW and use BQ Storage API.

So, the API will made compatible with Storage API and not support arbitrary queries at the moment.

For authorization we'll use OAuth2 as other connectors (e.g. GDrive). The users will have to connect to BQ using the account page or the import data page. 
We'll add a new service `bigquery` to the `oauth` configuration in `app_config.yml`.

Import job parameters:

* `connector` parameters:
  + `project` name of the BigQuery project
* rest of parameters:
  + `dataset` name of the BQ dataset
  + `table` name of the table to import
  + `columns` (optional; all by default) columns of the table to import (array of strings)
  + `filter` (optional) filtering condition in [BQ Standard SQL](https://cloud.google.com/bigquery/docs/reference/standard-sql/enabling-standard-sql), as a string of the form `"column_name operator value"` or other expression involving a single column (see examples below)
  + `limit`(optional) maximum number of rows to import

### Filter examples:
* `“int_field > 5”`
* `
“date_field = CAST(‘2014-9-27’ as DATE)”`
* `“nullable_field is not NULL”`
* `“st_equals(geo_field, st_geofromtext(“POINT(2, 2)”))”`
* `“numeric_field BETWEEN 1.0 AND 5.0”`

I initially considering using the names `database` for `project` and `schema` for `dataset` for consitency with other import providers, but I think it will be clear for users to use the BQ terminology.

**Comment by jgoizueta** [comment]
I have a question regarding the evolution of this API.

When we introduce the new non-odbc FDW we'll have control over the BQ client API used, and I see basically two options there:
* Giving the users the flexibility of arbitrary SQL queries defining by them but using a less performant BQ API.
* Restricting the way to query their data (table, selected columns, single restriction filter) but using the more efficient Storage API.

It seems to me that we primarily provide the second option, but should we also provide the first one as an alternative? Technically I see no problem in providing it; implementation effort is not higher since the FDW already basically provides the first option, it would be a case of maintaining two different API classes in the code.

cc @alonsogarciapablo @alasarr can you give your opinion on this?

**Comment by alonsogarciapablo** [comment]
Most of the [BigQuery Connectors I've seen](https://docs.google.com/presentation/d/109bFMWMD5SfymjzqzgxUXWO3N_iaReXAWhxb_s_RzcE/edit#slide=id.p) support these 3 options:

1. Selecting a table from one of your projects.
2. Selecting a table + limiting the results.
3. Entering a custom SQL. 

Alteryx, for example, supports these 3 options:

![image](https://user-images.githubusercontent.com/390398/67670347-fea08a00-f973-11e9-92fc-df3034ccba46.png)

Right now I would focus on 1. and 2., knowing that 3. might come later. We need to understand if there's a way to limit the results with the Storage API.

**Comment by jgoizueta** [comment]
:thinking: One thing we could do to support arbitrary queries and use storage API is to save the query to a temporary table, then use storage api to transfer it.

**Comment by jgoizueta** [comment]
Regarding limit implementation for Storage API, it seems it's simply a matter of stop reading when the limit is reach, since storage API only charges by data transferred through calls to `ReadRows`: https://cloud.google.com/bigquery/pricing#storage-api

**Comment by jgoizueta** [comment]
We could add a `dry_run` parameter to our API, so users can estimate the cost of running imports ahead of time. If the FDW doesn't support dry runs we can use the standard BigQuery API from the Ruby side to dry-run a query and return the results.

The users will need to estimate costs based on the results, what API will be used (storage or standard), what pricing model they use (flat rate/on demand), etc.

Since it won't be straightforward anyway for users to compute the estimate, I wonder if we could just drop this feature and let the users work out the cost on their own (using the BQ console, CLI, a script or whatever they use).

What do you think @alasarr ?

**Comment by manmorjim** [comment]
As we decided to continue with the ODBC driver here is some info about how it works with Storage API.

There are some relevant parameters in the ODBC driver:
- UseDefaultLargeResultsDataset
- EnableHTAPI
- HTAPI_MinActivationRatio
- HTAPI_MinResultsSize
- AllowLargeResults
- LargeResultsDataSetId
- LargeResultsTempTableExpirationTime

Some of them could be setup in the ODBC configuration (chef) and others could be configured in the cartodb `app_config.yaml`.

### First approach

**Parameters in ODBC configuration (check if they can be defined in odbc.ini):**
- `EnableHTAPI` - Enable Storage API (`1` to enable it).
- `AllowLargeResults` - Driver allows query results that are larger than 128MB in size. (`1` to allow it).
- `UseDefaultLargeResultsDataset` - Using defaults anonymous dataset (`0` to use a configured dataset --> see bellow).
- `HTAPI_MinActivationRatio` - minimum ratio of total rows to rows in the first page needed to activate Storage API (`0` to use Storage API depending on the configured HTAPI_MinResultsSize only --> see bellow).

**Parameters in Builder configuration:**
- `HTAPI_MinResultsSize` - num rows threshold. When the num of rows in the query results are greater than this parameter the driver uses Storage API.
- `LargeResultsDataSetId` - name of the temporal dataset used by the driver. (set `_cartoimport_temp` as temporal dataset name with underscore at the beginning to mark the dataset as anonymous). 
- `LargeResultsTempTableExpirationTime` - live duration in milliseconds for any temporary table created. (set `3600000` to set 1h).

**Comment by alonsogarciapablo** [comment]
Could these parameters be overridden by the user (or us)? For example, if we/they want to import a table with a num of rows greather than `HTAPI_MinResultsSize` **and** they don't want to use the Storage API (because they don't have it enabled)?

**Comment by manmorjim** [comment]
The first approach will be:

**Harcoded values in BigQuery provider:**
- `AllowLargeResults` - `1` driver allows query results that are larger than 128MB in size.
- `UseDefaultLargeResultsDataset` - `0` using the provided dataset name in the parameter `LargeResultsDataSetId`.
- `HTAPI_MinActivationRatio` - 0` to use Storage API depending on the configured `HTAPI_MinResultsSize` only.

**Parameters in Builder configuration (default values) which can be overridden by the import API params:**
- `storage_api: true` --> `EnableHTAPI=1`
- `stgapi_results_limit: 100000` --> `HTAPI_MinResultsSize=5`
- `stgapi_tmp_dataset: '_cartoimport_temp'` --> `LargeResultsDataSetId=_cartoimport_temp`
- `stgapi_tmp_table_exp: 3600000` --> `LargeResultsTempTableExpirationTime=3600000`

**Comment by manmorjim** [comment]
Finally all values were hardcoded in the BQ provider:
- `AllowLargeResults` - `1` driver allows query results that are larger than 128MB in size.
- `UseDefaultLargeResultsDataset` - `0` using the provided dataset name in the parameter `LargeResultsDataSetId`.
- `HTAPI_MinActivationRatio` - 0` to use Storage API depending on the configured `HTAPI_MinResultsSize` only.
- `EnableHTAPI` - `0` (Storage API disabled by default)
- `HTAPI_MinResultsSize` - `100`
- `LargeResultsDataSetId` - `_cartoimport_temp`
- `LargeResultsTempTableExpirationTime` - `3600000` (ms)

However, the `EnableHTAPI` parameter can be overridden by the import API param `storage_api`:
- `storage_api: true` --> `EnableHTAPI=1`
- `storage_api: false` --> `EnableHTAPI=0`

**Comment by jgoizueta** [comment]
We had to make some changes; see this comment: https://github.com/CartoDB/cartodb/pull/15266#issuecomment-564621074

**Comment by jgoizueta** [comment]
Fixed via #15266
