### ISSUE TITLE
[OAuth] Error inserting into a table with references

### ISSUE THREAD

**Issue by gonzaloriestra** [CartoDB/cartodb#15161]
### Context
There seems to be a problem with OAuth roles/grants and referenced tables.

### Steps to Reproduce

1. Request an OAuth token with `schemas:c` scope
2. Create a table with SQL API: `CREATE TABLE foreign_table(id integer PRIMARY KEY)`
3. Insert a value: `INSERT INTO foreign_table(id) VALUES (1)`
4. Create another table with a reference: `CREATE TABLE final_table(id integer references foreign_table(id) ON DELETE CASCADE, name text);`
5. Insert a value: `INSERT INTO final_table(id, name) VALUES (1, 'tal')`

### Current Result
`permission denied for schema X`

### Expected result
It should insert the value

**Comment by gonzaloriestra** [comment]
I've tried to replicate it with a simpler example from psql, but it doesn't fail, so I must be forgetting something:
```
CREATE DATABASE references_issue;
\c references_issue 
CREATE ROLE parent_role;
CREATE ROLE child_role;
GRANT parent_role TO child_role;
GRANT CREATE ON SCHEMA public TO child_role;

SET ROLE child_role;
CREATE TABLE foreign_table(id integer PRIMARY KEY);
CREATE TABLE final_table(id integer references foreign_table(id) ON DELETE CASCADE, name text);

-- Change the ownership of the tables (what oauth_reassign_tables_trigger does)
SET ROLE postgres;
ALTER TABLE foreign_table OWNER TO parent_role;
GRANT ALL ON TABLE foreign_table TO parent_role;
GRANT ALL ON TABLE foreign_table TO child_role;
ALTER TABLE final_table OWNER TO parent_role;
GRANT ALL ON TABLE final_table TO parent_role;
GRANT ALL ON TABLE final_table TO child_role;

SET ROLE child_role;
INSERT INTO foreign_table(id) VALUES (1);
INSERT INTO final_table(id, name) VALUES (1, 'tal');
```

**Comment by gonzaloriestra** [comment]
Btw, if I disable the trigger that reassigns the ownership of the tables, it works fine. So it must be related to it, although the final roles and permissions look right to me.

**Comment by alrocar** [comment]
How does this affect the Kepler integration? Are we using FKs and doing JOINs in Kepler?

If our goal is be able to send a PR with our integration in Kepler I'd suggest finding a workaround (maybe not use FKs by now) to avoid blocking this project until we find a fix for the issue.

cc. @jesusbotella

**Comment by VictorVelarde** [comment]
Yes, we have FKs in some of our tables.

Kepler uses what we call *CustomStorage* (through @carto/toolkit library). That's basically an abstraction on the top of several tables, to deal with visualizations and datasets.

For public tables we have:
- **kepler_public_v0**: a table for public visualizations
- **kepler_public_v0_datasets**: public datasets (metadata)

And we have a *many to many* relation between them, in a table called **kepler_public_v0_datasets_vis**. And that's the one that references the previous two. [see here](https://github.com/CartoDB/toolkit/blob/6d217c8978aad05228a8c9af310506cf5525673a/packages/custom-storage/src/sql/SQLStorage.ts#L57). The error prevents a proper storing of them.

And we have exactly the same for private data (just replace 'public' for 'private' in the previous names).

**Comment by VictorVelarde** [comment]
Please @neokore have a look at this, removing the 'REFERENCES' in the intermediate table

**Comment by neokore** [comment]
Yes, it works! I've applied a temporary patch in toolkit (https://github.com/CartoDB/toolkit/pull/42) while this bug it's fixing.

**Comment by VictorVelarde** [comment]
We have applied the workaround and it works, so this is not urgent now for kepler.gl

@alrocar should we just keep this open or maybe open another one for the future as an improvement?

**Comment by alrocar** [comment]
Let's keep it open. It's in the backend kanban so it'll be fixed eventually.
