### ISSUE TITLE
HTTPS Documentation

### ISSUE THREAD

**Issue by mstanky** [CartoDB/cartodb#15181]
I'm trying to deploy CartoDB in a production environment and serve it over HTTPS. The application has many components, hence my trouble narrowing down which environment variables need to be configured to enable HTTPS.

I'm running the Builder application with all the services and the database on an AWS EC2 instance. Which variables in `app_config.yml` need to be modified to serve the application over HTTPS to the end user?

**Comment by gonzaloriestra** [comment]
Hi! Questions regarding custom installations should be better placed in [Stackoverflow](https://stackoverflow.com/questions/tagged/cartodb). There's also a [Google Group](https://groups.google.com/forum/#!forum/cartodb) where you can have a look.
