### ISSUE TITLE
[connectors-ui] Upload / connect split

### ISSUE THREAD

**Issue by alejandraarri** [CartoDB/cartodb#15207]
Split _Connect Dataset_ into _Upload_ and _Connect_ tabs. The first one should have the form to upload you own files and the second one will remain the same without the _Data file_ option from the connector list
- [x] New dataImportView tab
- [x] Remove dataImport from import options

### Context
https://github.com/CartoDB/cartodb/issues/15194
[Invision](https://projects.invisionapp.com/share/QUULMAVESAW#/screens/390965264_Upload)

**Comment by VictorVelarde** [comment]
Pending PR in draft mode

- Pending tests (WIP)
- Small bug on Footer

**Comment by alejandraarri** [comment]
As the acceptance is done https://github.com/CartoDB/cartodb/pull/15229#issuecomment-560486294, we can finally close this issue!
