### ISSUE TITLE
Stored XSS

### ISSUE THREAD

**Issue by achanak** [CartoDB/cartodb#15216]
**Vulnerability Description:**
Stored XSS, also known as persistent XSS, is the more damaging than non-persistent XSS. It occurs when a malicious script is injected directly into a vulnerable web application.
Reference: https://www.owasp.org/index.php/Cross-site_Scripting_(XSS)

**Vulnerable URL:**
https://carto.com/
[payload.txt](https://github.com/CartoDB/cartodb/files/3821249/payload.txt)

**Vulnerable Parameter:**
user[company]= and user[job_role]=

**Payload:**
Attached in the file 

**Steps to Reproduce:**

Tested in Firefox 70.0.1 (64-bit)

1. Browse https://carto.com/
2. Create account by clicking Try for Free
3. Fill the required details > Next > Fill the required details > Next
4. Now in Company name field enter the payload1 and in Job title field enter payload2 > Next
5. Navigate to Setting and you will see xss is successfully executed. 

To confirm its a stored xss, logout and login back, navigate to setting. XSS is successfully executed again.

Please let me know if you are unable to reproduce the issue

**Comment by achanak** [comment]
**Vulnerability Description:**
Stored XSS, also known as persistent XSS, is the more damaging than non-persistent XSS. It occurs when a malicious script is injected directly into a vulnerable web application. 
Reference: https://www.owasp.org/index.php/Cross-site_Scripting_(XSS)

**Vulnerable URL:**
 https://carto.com/

**Vulnerable Parameter:**
 user[company]= and user[job_role]=

**Payload :** 
 "><img src=x onerror=alert(document.domain)>
"><img src=x onerror=alert(document.cookie)>

**Steps to Reproduce:**

Tested in Firefox 70.0.1 (64-bit)

1. Browse https://carto.com/
2. Create account by clicking Try for Free
3. Fill the required details > Next > Fill the required details > Next 
4. Now in Company name field enter the payload "><img src=x onerror=alert(document.domain)> and in Job title field enter "><img src=x onerror=alert(document.cookie)> > Next
5. Navigate to Setting and you will see xss is successfully executed.

To confirm its a stored xss, logout and login back, navigate to setting. XSS is successfully executed again.

If you are unable to reproduce the issue please let me know.

**Comment by achanak** [comment]
[payload.txt](https://github.com/CartoDB/cartodb/files/3821255/payload.txt)

**Comment by achanak** [comment]
Can i hear any update

**Comment by gonzaloriestra** [comment]
@CartoDB/rt-managers

**Comment by oriolbx** [comment]
@alrocar

**Comment by alrocar** [comment]
Assigned to the backend project until we prioritize.

**Comment by achanak** [comment]
Any update on the issue.

**Comment by alrocar** [comment]
We've updated our security policy and from now on we'll be following it: https://github.com/CartoDB/cartodb/blob/master/SECURITY-POLICY

I'm closing this one and we'll manage it privately. 

Thanks @achanak
