### ISSUE TITLE
Geolocation data not stripped from Uploaded images

### ISSUE THREAD

**Issue by Rafid0x01** [CartoDB/cartodb#15212]
Vulnerability Name: Geolocation data not stripped from
Uploaded images
Vulnerability Discription:
When an image is taken using a smartphone or camera certain metadata fields are often attached to it.
These fields could include the model of the camera, the time it was taken, whether the flash was used,
the shutter speed, focal length, light value and even the location. In Inturn, while uploading the image as
a profile picture, the exif data is not stripped from images. The exif data in images contains sensitive
data like Geoloacation, latitude, longitude, etc. Also it contains the camera information and other
details. Tools Used: exiftool, http://exif.regex.info/exif.cgi 

Steps TO reproduce:
1)Try to find an url which have tendency to upload an image
2)Then down load sample image which contain gps information
(you can dw from here: https://github.com/ianare/exif-
samples/tree/master/jpg/gps)
3)Upload that image and try to get the url of that image
4)Now we need a tool to investigate or retrieve meta data information
http://exif.regex.info/exif.cgi
4)just upload the uploaded image url and and click on view image
data
Impact:

attacker can able to track anyone's location from the uploaded images

### Current Result
* i got The Image Data*

### Expected result
* should not betrack image data *

### Browser and version
I am Using Chrome Browser . Version 78.0.3904.87 (Official Build) (64-bit)

**Comment by gonzaloriestra** [comment]
Thanks for reporting! But I'm closing as it's duplicated: https://github.com/CartoDB/cartodb/issues/15110
