### ISSUE TITLE
Clarify `table` parameter in DB Connectors API

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/cartodb#15213]
This is to review the parameters of the BQ connector through the import API.

We should take into account we expect to support BQ Storage API in the future: #15168 

Current parameters (as of #15179 #15184):

* `provider` Must be set to *bigquery*
* `project` Define the Google Cloud project to connect to
* `table` Table to be imported (if `sql_query` present, name of the imported CARTO dataset)
* `dataset` Name of the BigQuery dataset containing the data. This is optional if sql_query is used.
* `sql_query` Allows you to import a dataset defined by a SQL query. This is optional.

Import table example: will import `xxxx-bq-project.yyyy-bq-dataset.zzzz-bq-table`as `zzzz-bq-table`:

```json
{
  "provider": "bigquery",
  "project": "xxxx-bq-project",
  "dataset": "yyyy-bq-dataset",
  "table": "zzzz-bq-table"
}
```

Import query example: will import `xxxx-bq-project.yyyy-bq-dataset.zzzz-bq-table`as `zzzz`:

```json
{
  "provider": "bigquery",
  "project": "xxxx-bq-project",
  "sql_query": "SELECT * FROM yyyy-bq-dataset.zzzz-bq-table",
  "table": "zzzz"
}
```

The main problem with this is that it can be confusing because `table` is the name of the external table in the first case (and also the local name) and it is the local named given to the imported data in the second case.

### 1. Leave it as is

We could leave it like that for consistency with other db-connectors and clarify the use of `table` in the documentation.

### 2. Add another parameter

We could add another parameter for the name of the local table, e.g. `save_as` (or `import_as`, `local_table`.

The second example would now be:

```json
{
  "provider": "bigquery",
  "project": "xxxx-bq-project",
  "sql_query": "SELECT * FROM yyyy-bq-dataset.zzzz-bq-table",
  "save_as": "zzzz"
}
```

The new parameter could be also added to the first example to save the table as a different name from the original:

```json
{
  "provider": "bigquery",
  "project": "xxxx-bq-project",
  "dataset": "yyyy-bq-dataset",
  "table": "zzzz-bq-table",
  "save_as": "zzzz"
}
```

### 2b. Add another parameter and rename table

For greater clarity we could also rename `table` to `source_table`/`from_table` in addition of the new `local_table`/`save_as` parameter.

### 3. Use subparameters

We could use mutually exclusive parameters (objects) for the two cases (table/query) with different subparameters in each case.

The name of the parameters could be `sync_query`/`sync_table`, `bq_query`/`bq_table`, `from_query/from_table`, ... 
(`sync_` could be confusing because we call _sync tables_ to the imports that contain an `interval` parameter so they are updated periodically)

The examples would now be:

```json
{
  "provider": "bigquery",
  "project": "xxxx-bq-project",
  "from_table": {
    "dataset": "yyyy-bq-dataset",
    "source_table": "zzzz-bq-table"  // source
  },
  "table": "zzzz"  // destination
}
```

```json
{
  "provider": "bigquery",
  "project": "xxxx-bq-project",
  "from_query": {
      "sql_query": "SELECT * FROM yyyy-bq-dataset.zzzz-bq-table" // source
  },
  "table": "zzzz" // destination
}
```

cc @ilbambino  @alonsogarciapablo

**Comment by ilbambino** [comment]
Really good summary of the Slack discussion. 👍 

As we use the same API in other connectors and we cannot change those I would try to improve it with the minimal changes. Hence I would go for solution 2. Adding a new parameter, either `save_as` or `local_table`. I think with that and updating the docs will improve it quite a lot. 

My 2 cents

**Comment by jgoizueta** [comment]
I also like solution 2 since it's simple and not too different from other connectors.

Any preferences on the parameter name?
- [ ] `save_as`
- [ ] `import_as`
- [ ] `rename_as`
- [ ] `local_table`
- [ ] `carto_table`
- [ ] `carto_dataset`
- [ ] ...

**Comment by alonsogarciapablo** [comment]
This is not specific to the BigQuery connector... the rest of connectors have the same issue (`table` means different things in different contexts). IMO, if we go with 2. we should also add that same parameter (as an alias) to the rest of connectors for consistency, keeping backwards compatibility.

What if we first try to make things clearer by changing the documentation? For example, right now there's a section that documents all parameters:

![image](https://user-images.githubusercontent.com/390398/68785036-d4bab900-063d-11ea-9995-d87750648743.png)

And then there're two sections: "Connect to a Table", "Connect to a SQL Query".

Perhaps we can remove that shared section and document the specific parameters for each of those options within their sections... what do you think?

**Comment by alrocar** [comment]
+1 to @alonsogarciapablo comment. There are clients already using `sql_query` + `table` as destination table.

**Comment by manmorjim** [comment]
One of the _Principles of Designing APIs_ is they have to be simple & intuitive even they aren't documented therefore I would go with 2. But, as @alonsogarciapablo pointed, we **must** keep backwards compatibility so I think we should keep them and update the documentation adding a `deprecated` tag to `table` parameter. 

So IMO we should:
1. Keep `table` parameter.
1. Add new `import_as` parameter (already done in https://github.com/CartoDB/cartodb/pull/15232 by @jgoizueta)
1. Update the doc marking `table` parameter as `deprecated`.

What do you think? @alonsogarciapablo @alrocar @ilbambino

**Comment by alrocar** [comment]
I've recently had several conversations with @agnesgyorfi about backwards compatibility, so I'm adding her to the conversation.

In this case I don't think the problem is deprecating the `table` parameter, but, in case we did it, to clearly have and communicate a deprecation plan in one of our public APIs.

If we just mark in the doc the parameter as deprecated, most likely we'll end up supporting both `table` and `import_as` and if we eventually drop `table` we might have complaints of actual users if we haven't communicate it properly.

Even when this is a minor change it might disturb current users operations or break SLAs. 

For now, my opinion is that I'm fine with the plan proposed by @manmorjim but at some point if we want to drop the `table` parameter we'd need some metrics of its usage and some plan to communicate this change in the API according to our SLAs.

**Comment by agnesgyorfi** [comment]
@alrocar oh yes, thank you for flagging me here. In the agreement I just sent back today, the customer wanted to have a right to terminate the agreement immediately if we implemented changes that were not backwards-compatible. My suggested edit (tbd if it's acceptable to them) is that they could only terminate for a non-backwards compatible change if it caused "material detriment". 

It would be helpful for me to have a very dumbed-down explanation of what the functionality limitations of the non-backwards-compatible change would be, in this case, esp. to have a "case study" example in my back pocket the next time someone wants to change this clause in our agreement.  Thanks!

CC @palrj

**Comment by manmorjim** [comment]
I agree with @alrocar we should communicate a deprecation plan. Do we have a defined deprecation plan for our public APIs?

AFAIK the current version of CARTO's _import API_ is `v1` (e.g. `/api/v1/imports`) so we can keep `table` parameter to make `v1` backwards compatible and marking this parameter as `deprecated` in doc. This means this parameter will never be dropped in this API version but will not be supported in next versions (e.g. if we publish a `v2`: `/api/v2/imports` this parameter won't work).

@agnesgyorfi I'll try to do my best to explain the functionality limitations users would get with non-backwards-compatible changes. In this case, `table` parameter is used by customers to name the CARTO table, e.g. they have a program which imports a table called _my_remote_table_ in their dashboard with the name _my_carto_table_ it would be using our _import API_ v1 with:
```json
/api/v1/imports
{
    "connector": {
        "provider": "bigquery",
        "project": "my_project",
        "sql_query": "select * from `my_project.my_dataset.my_remote_table`;",
        "table": "my_carto_table"
    }
}
```
So if we replace the `table` parameter with `import_as` to make our API simpler the call above would be:
```json
/api/v1/imports
{
    "connector": {
        "provider": "bigquery",
        "project": "my_project",
        "sql_query": "select * from `my_project.my_dataset.my_remote_table`;",
        "import_as": "my_carto_table"
    }
}
```
So in this case, the program users were using won't work unless they change their program to replace the `table` parameter with `import_as`.
To prevent that, we should mark the `table` parameter as `deprecated` in the doc to communicate future customers to avoid using this parameter in their programs and to communicate current customers this parameter is supported but it won't in next API versions so it would be nice changing it.
Depending on our _deprecation plan_ (which it should be public & documented for customers) we could provide a long sunset period to drop `v1` API and supports only `v2` and so.

[more info about best practies deprecating APIs](https://swagger.io/blog/api-strategy/best-practices-for-deprecating-apis/)

**Comment by alonsogarciapablo** [comment]
I keep thinking this ->  https://github.com/CartoDB/cartodb/issues/15213#issuecomment-553490251. Adding the new parameter is easy, but deprecating the old one is not, and we can skip all that work if we document things in a more clear way.

**Comment by alonsogarciapablo** [comment]
We discussed about this offline and @manmorjim will go with option 2. (new alias for `table` and marking `table` as depecrated` if it's not super hard.
