### ISSUE TITLE
Notify user when exceeding the max rows import limits

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#15246]
In some cases imports are limited to x max rows (1M depending on config) and if the source has more (say 2M for instance), the import is capped to max rows and the user does not get feedback about it.

This may affect generically DB connectors, and specifically the BQ connector.

Provide some feedback about max rows exceeded in the API.

**Comment by jgoizueta** [comment]
The easy way to do this would be to put a warning "rows limit reached" whenever the result has exactly the max. number of rows. Actually checking if the query/dataset is bigger (and what size) would be costly. (We are just adding a LIMIT into the SQL queries)
