### ISSUE TITLE
Host Header Injection Redirect

### ISSUE THREAD

**Issue by jagadeeshjs8895** [CartoDB/cartodb#15242]
**Vulnerability Description:**
Host Header injection open redirection

 is sometimes used as a part of phishing attacks that confuse visitors about which web site they are visiting.

**Remediation:**
If possible, the application should avoid incorporating user-controllable data into redirection targets. In many cases, this behavior can be avoided in two ways:
Remove the redirection function from the application, and replace links to it with direct links to the relevant target URLs.
Maintain a server-side list of all URLs that are permitted for redirection. Instead of passing the target URL as a parameter to the redirector, pass an index into this list.

**Vulnerable URL:**
https://jagajs.carto.com/multifactor_authentication

Payload: "Host: bing.com "

**How to reproduce this vulnerability:**
Log on into your account and enable 2FA.

Open this URL "  https://jagajs.carto.com/multifactor_authentication" and enter wrong code like 788963 send it to the repeater in burp suite.
add the payload to the header request and forward the request.

It will directly redirect to bing.com

**Impact:**
Whenever a user visits this URL, it will redirect them to site.com. It is used in phishing attacks.

**2 attachments:**
[HHI_carto.zip](https://github.com/CartoDB/cartodb/files/3854315/HHI_carto.zip)

thanks ,
Jagadeesh v
email: js080895@gmail.com

**Comment by gonzaloriestra** [comment]
@CartoDB/rt-managers

**Comment by oriolbx** [comment]
@alrocar

**Comment by alrocar** [comment]
Assigned to the backend project until we prioritize.

**Comment by jagadeeshjs8895** [comment]
Kindly let me know when the issue has been fixed

**Comment by jagadeeshjs8895** [comment]
Is there any update?

**Comment by alrocar** [comment]
@jagadeeshjs8895

We really appreciate the time you invested identifying and reporting the issue. We have added the issue to our current backlog and we'll prioritize it as soon as possible.

Thanks!

**Comment by jagadeeshjs8895** [comment]
hi team,
Is there any update?

**Comment by alrocar** [comment]
Hi @jagadeeshjs8895,

from our side, we've been able to reproduce the issue and the remediation proposed makes sense. It's in our backlog and we'll be tackled at some point but for now it has low priority.

Let us know if you have further questions. 

Thanks!

**Comment by jagadeeshjs8895** [comment]
Thanks for your response. i would to know that you will providing  any hall of fame or swag.

**Comment by jagadeeshjs8895** [comment]
Thanks for your response. i would like to know that you will providing any
hall of fame or swag.

**Comment by jagadeeshjs8895** [comment]
Thanks for your response. i would like to know that you will providing any
hall of fame or swag.

**Comment by alrocar** [comment]
We've updated our security policy and from now on we'll be following it: https://github.com/CartoDB/cartodb/blob/master/SECURITY-POLICY

I'm closing this one and we'll manage it privately. 

Thanks @jagadeeshjs8895
