### ISSUE TITLE
EXIF Geolocation Data Not Stripped From UploadedImages

### ISSUE THREAD

**Issue by jagadeeshjs8895** [CartoDB/cartodb#15241]
**Vulnerability:**
**EXIF Geolocation Data Not Stripped From UploadedImages**
**Description**:
EXIF is short for Exchangeable Image File, a format that is a standard for storing interchange information in digital photography image files using JPEG compression. Almost all new digital cameras use the EXIF annotation, storing information on the image such as shutter speed, exposure compensation, F number, what metering system was used, if a flash was used, ISO number, date and time the image was taken, white balance, auxiliary lenses that were used and resolution. Some images may even store GPS information so you can easily see where the images were taken!.Because of that there is a possibility of Security Imapct.

**Steps to reproduce:**
1) Got to Github ( https://github.com/ianare/exif-samples/tree/master/jpg)
2) Log on to your account and Go to choose image option on the url  https://jagajs.carto.com/profile
3) Upload the GPS sample image.
4) see the path of uploaded image ( Either by right click on image then copy image address OR right click, inspect the image, the URL will come in the inspect , edit it as html )
5) open it (http://exif.regex.info/exif.cgi)
6) you can See that it is still showing exif data.

[exif_Carto_final.zip](https://github.com/CartoDB/cartodb/files/3854281/exif_Carto_final.zip)

thanks ,
Jagadeesh v
email: js080895@gmail.com

**Comment by gonzaloriestra** [comment]
Thanks for reporting! But I'm closing as it's duplicated: https://github.com/CartoDB/cartodb/issues/15110
