### ISSUE TITLE
Fix 404 links in the footer and header

### ISSUE THREAD

**Issue by albertoac** [CartoDB/cartodb#15256]
Hello!
We have detected quite a few pages with links towards pages that don't exist anymore. My guess is that it would take quite a lot of time to update the footer/header design to make it consistent with the one we have in our homepage. As a temporal fix, would it be possible to remove those broken links (specially in the footer and under the solutions menu in the navbar) or replace them for the correct ones?

As an example, this is one of the affected pages https://public.carto.com/tables/world_ports/public . The same navigation issue is here https://public.carto.com/datasets . In this last page, the footer is a bit different, however we should also change the link in Guides (that sends you to /learn/guides ) and change it for a link to the help center

cc/ @CartoDB/rt-managers  @Julien-Hennico

**Comment by elenatorro** [comment]
Merged 🚀
