### ISSUE TITLE
[DO] Feature flag for instant licensing

### ISSUE THREAD

**Issue by gonzaloriestra** [CartoDB/cartodb#15254]
We are now checking if the `do-licensing` feature flag [is enabled for subscription operations](https://github.com/CartoDB/cartodb/blob/1f88767c1018d686edc89ca0b6875a62ea36821c/app/controllers/carto/api/public/data_observatory_controller.rb#L16), but we should change it to `do-instant-licensing` and:

- Always allow getting subscription info and doing normal license.
- Do normal license when the `estimated_delivery_days` is 0 but it's not enabled.
- Add the feature flag state in `do/token` and more information:
```
{
    access_token: 'xxx',
    bq_public_project: 'xxx',
    gcp_execution_project: 'xxx',
    bq_project: 'carto-do-customers',
    bq_dataset: 'xxx',
    gcs_bucket: 'xxx',
    instant_licensing: false
}
```

**Comment by alasarr** [comment]
Let's do it through a `/api/v4/me`. Let add there two flag:

"data_observatory": { "instant_licensing": true}

Feel free to change the ☝️ format is necessary

**Comment by gonzaloriestra** [comment]
Besides `instant_licensing`, we will need to send more info to decouple from CF and make DO more usable from other places:
- Service account project (for the billing)
- BigQuery project + dataset
- GCS project + bucket

As this information is related to the token, because it's required to be able to use it, @oleurud and I think that it would make sense to include it in the `do/token` endpoint.

That way, we would avoid an extra call from CF (or from any other place where people want to use the DO token). Also, we would keep the DO stuff more separated from Carto, in case we want to extract the DO API someday.

What do you think @alasarr @alrocar?

**Comment by alasarr** [comment]
I prefer the `/api/v4/me` but not a strong opinion, go for it if you want.

**Comment by Jesus89** [comment]
Closed via https://github.com/CartoDB/cartodb/pull/15315
