### ISSUE TITLE
Sync creation is not rate-limited

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/cartodb#15318]
Import creation is rate-limited:

https://github.com/CartoDB/cartodb/blob/d352e40c7edbb4dfd5987c83a028907a82427a9f/app/controllers/api/json/imports_controller.rb#L35-L36

But sync creation is not:

https://github.com/CartoDB/cartodb/blob/d352e40c7edbb4dfd5987c83a028907a82427a9f/app/controllers/api/json/synchronizations_controller.rb#L17-L72

Execution of syncs is limited to concurrent syncs per user:

https://github.com/CartoDB/cartodb/blob/4b3044913219efc499ab4813e8678459c3ae8e05/services/platform-limits/lib/importer/user_concurrent_syncs_amount.rb#L14

But creation is not, which can be a problem when some users create lots of syncs; I think we should apply the same limits for sync creation than for import creation.

**Comment by rafatower** [comment]
Superseded by https://app.clubhouse.io/cartoteam/story/93384/sync-creation-is-not-rate-limited
