### ISSUE TITLE
[BQ Connector] UI improvements and bug fixes

### ISSUE THREAD

**Issue by alejandraarri** [CartoDB/cartodb#15323]
Remaining tasks:

- [x] When the user cancels the oAouth login redirect to `Connect` page.
- [x] Handle errors so when the query is not correct we can render an error page.
- [x] Add `beta` tag in the BigQuery connector header.
- [x] Add explanation about the `Billing Project ID` field.
- [x] Change sql field explanation copy.

### Context
https://github.com/CartoDB/cartodb/issues/15194
https://github.com/CartoDB/cartodb/issues/15284
https://projects.invisionapp.com/share/QUULMAVESAW

**Comment by alejandraarri** [comment]
Hey @isapozuelo! In this issue we have included some enhancements you suggested in your review. (For now, only the easy ones.) Thank you for making the UI easier to understand! 🙌

**Comment by isapozuelo** [comment]
Great! thanks for keeping me posted @alejandraarri :)
