### ISSUE TITLE
Review placeholder texts in Catalog dropdowns

### ISSUE THREAD

**Issue by csubira** [CartoDB/cartodb#15335]
### Context
In the acceptance process of https://github.com/CartoDB/design/issues/1744 @urbanphes commented about making changes in how the placeholders for the search dropdowns behave.

Catalog dropdowns are built using the same component with different properties.
Placeholder should be changing differently in each of the two dropdowns depending on the search status as follows:

<img width="628" alt="Screenshot 2019-12-19 at 13 34 18" src="https://user-images.githubusercontent.com/26403479/71173950-4d77eb00-2264-11ea-8642-59c0a73f6f82.png">

@CartoDB/rt-managers

**Comment by jesusbotella** [comment]
It's just been released to production! 🚀
