### ISSUE TITLE
[Import API] Quota checker tries to subtract nil value when UserDataSize fail

### ISSUE THREAD

**Issue by manmorjim** [CartoDB/cartodb#15388]
The quota checker uses the method [raise_if_over_storage_quota](https://github.com/CartoDB/cartodb/blob/2c14d07fc18cf4e68cc38f445f46c0d5eba57899/services/importer/lib/helpers/quota_check_helpers.rb#L4) in order to check if the user is over storage quota:

```ruby
def raise_if_over_storage_quota(requested_quota: 0, available_quota: 0, user_id: nil)
    quota_overage = requested_quota - available_quota

    if quota_overage > 0
        report_over_quota(user_id, quota_overage: quota_overage) if user_id

        raise StorageQuotaExceededError.new
    end
end
```
However, the parameter `available_quota` could be `nil` if some error occurred while the importer is getting the user available size through the method [db_size_in_bytes](https://github.com/CartoDB/cartodb/blob/2c14d07fc18cf4e68cc38f445f46c0d5eba57899/app/models/user.rb#L1413) raising the error `TypeError: nil can't be coerced into Float`.

We should check if the parameters are not `nil` or managing the errors occurred while the function `db_size_in_bytes` was being executed.

**Comment by dgaubert** [comment]
Fixed in #15512
