### ISSUE TITLE
Prevent Sync starvation

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/cartodb#15398]
At most [3](https://github.com/CartoDB/cartodb/blob/4b3044913219efc499ab4813e8678459c3ae8e05/services/platform-limits/lib/importer/user_concurrent_syncs_amount.rb#L14) syncs from the same user can run simultaneously.
For uses that have a high number for frequent syncs (so that the number of syncs times the average sync time divided by frequency exceeds 3) it's not possible to perform all of them on time.

The problem is that due to the way they're scheduled, some of them suffer from starvation: they're never done (every time they're picked, there are other 3 already in execution).

One simple way to alleviate this problem would be to add a `ORDER BY ran_at` in [this query](https://github.com/CartoDB/cartodb/blob/de72babff0a9d791638b54259d590ebeb4b2d530/services/synchronizer/lib/synchronizer/collection.rb#L54-L63)
which is used by the [rake task](https://github.com/CartoDB/cartodb/blob/de72babff0a9d791638b54259d590ebeb4b2d530/lib/tasks/sync_tables.rake#L5) which enqueues syncs to be executed,
so that syncs are scheduled in the order of the last time they run (I'm assumming the order they are enqueued to redis is the order they're picked).

Note that by ordering by `ran_at` rather than by `run_at` we give priority to less frequent syncs.

**Comment by jgoizueta** [comment]
We must check if `ran_at` can be NULL before the first sync, because in that case we should make sort they're sorted properly

**Comment by manmorjim** [comment]
> We must check if `ran_at` can be NULL before the first sync, because in that case we should make sort they're sorted properly

I've checked `ran_at` field is filled when it is created. I think [this line](https://github.com/CartoDB/cartodb/blob/de72babff0a9d791638b54259d590ebeb4b2d530/app/models/synchronization/member.rb#L77) do it. Therefore, just adding `ORDER BY ran_at` to [the query](https://github.com/CartoDB/cartodb/blob/de72babff0a9d791638b54259d590ebeb4b2d530/services/synchronizer/lib/synchronizer/collection.rb#L54-L63) would be enough.
