### ISSUE TITLE
Dataset subscription_list_price should return the database value without modifications

### ISSUE THREAD

**Issue by cmongut** [CartoDB/cartodb#15406]
We are returning 0 in the `subscription_list_price` field when the database says is null. We need to return null instead and it will be handle by the clients.

It seems we need to change [this](https://github.com/CartoDB/cartodb/blob/715f3af81b388b6b6fc1b0675a1ab3712a8889cf/app/controllers/carto/api/public/data_observatory_controller.rb#L139).

**Comment by oleurud** [comment]
We have `0` and `null` as values in db, I understand the objective is to return the real value, right?

**Comment by cmongut** [comment]
Yeap!

**Comment by oleurud** [comment]
:rocket:
