### ISSUE TITLE
3d map showing scales issue

### ISSUE THREAD

**Issue by lasyakoechlin** [CartoDB/cartodb#15465]
### Context
*I am using 3d map polygons for my project using your latest code on Android (Carto Mobile Sdk 4.2.0). And the map is showing a lot of scales (image attached). I am seeing these lines when I use tilting. When the camera is with a tilt of 90 degrees, the lines go away.*

### Steps to Reproduce
1. Load the map for Carto Mobile Sdk 4.2.0
2. Tilt the map for viewing it in 3d
3. Weird lines/scales show up

### Current Result
*The lines or the scales seem to be some polygons/polylines plotted on the map with some alpha*

### Expected result
*3d map should be as clear as 2d map*

### SDK Version
*I am using Carto Version 4.2.0*

![3d_map_scaling_issue](https://user-images.githubusercontent.com/60749601/73957762-d7dbe300-48d4-11ea-87fb-26203988966b.jpg)

**Comment by gonzaloriestra** [comment]
@CartoDB/rt-managers

**Comment by ztephm** [comment]
Thank you for reporting this @lasyakoechlin . @gonzaloriestra Support will handle this outside of RT with the Mobile Team.

**Comment by ztephm** [comment]
Logging [internal ticket](https://carto.zendesk.com/agent/tickets/69067) here.

**Comment by lasyakoechlin** [comment]
Is there any update on this issue?

**Comment by ztephm** [comment]
@lasyakoechlin we are still in the process of getting feedback about this from our Mobile Team.

**Comment by mtehver** [comment]
@lasyakoechlin We need a sample app demonstrating the issue. It could be related to the specific indoor dataset, so without sample it is very difficult to track this. If you can share a sample, please post the sample to the Mobile SDK core repository: https://github.com/CartoDB/mobile-sdk. The mobile team can respond faster if posted there.

**Comment by alrocar** [comment]
Closing the issue in this repo since it's unrelated.

@lasyakoechlin Please could you continue the conversation in https://github.com/CartoDB/mobile-sdk?

Thanks!
