### ISSUE TITLE
[Dashboard] Home / Map section - Add keplergl maps

### ISSUE THREAD

**Issue by VictorVelarde** [CartoDB/cartodb#15487]
Integrate Kepler.gl maps into the Maps section in the dashboard's Home page.

### Design proposal
At the moment, we are just adding the navigation bar that switches between two types of maps. We are not changing the section name or the position of the toolbar
<img width="1076" alt="Screenshot 2020-03-17 at 16 36 45" src="https://user-images.githubusercontent.com/8669176/76873057-8cbad580-686d-11ea-8f1b-7654afa4069b.png">

### Related issue
https://github.com/CartoDB/product/issues/467

**Comment by alejandraarri** [comment]
Deploy into production 🚀
