### ISSUE TITLE
[Dashboard] Home - Add keplergl to Recent content

### ISSUE THREAD

**Issue by VictorVelarde** [CartoDB/cartodb#15486]
Integrate Kepler.gl maps into Recent content section in the dashboard.

### Design proposal
![Screenshot 2020-03-11 at 18 11 03](https://user-images.githubusercontent.com/8669176/76444183-d74ad680-63c3-11ea-8946-bc9bc461d89b.png)

### Related issue
https://github.com/CartoDB/product/issues/467

**Comment by alejandraarri** [comment]
Deployed into production! 🚀

**Comment by ana-md** [comment]
<img width="1389" alt="Screenshot 2020-03-12 at 11 41 57" src="https://user-images.githubusercontent.com/47864070/76513577-cd25e800-6456-11ea-907e-d7f634c9e5f6.png">

🚀😄❤️
