### ISSUE TITLE
[Dashboard] Test Kepler's Integration

### ISSUE THREAD

**Issue by MireyaD** [CartoDB/cartodb#15510]

**Comment by MireyaD** [comment]
We need to check the implementation of Kepler.gl maps in the CARTO dashboard.


### Comments

- [ ]  Change the copy of the tab: Kepler.gl instead of External.

- [ ]  Change the title copy in both cases CARTO and Kepler.gl tab. For the CARTO it should be "CARTO Maps", and for the Kepler.gl, "Kepler.gl Maps".

<img width="938" alt="Captura de pantalla 2020-03-02 a las 18 10 12" src="https://user-images.githubusercontent.com/46195278/75699646-16d13e80-5cb1-11ea-8996-2df79596a4ed.png">

- [ ] Fix the alignment in the table 

<img width="602" alt="Captura de pantalla 2020-03-02 a las 17 47 34" src="https://user-images.githubusercontent.com/46195278/75699501-e093bf00-5cb0-11ea-8766-47f98c4fc65e.png">




### Doubts

- Should we include in Usage Metrics the Kepler.gl maps too?

- Regarding the thumbnails, all the maps will generate a personalized thumbnail?

**Comment by ana-md** [comment]
Thanks for testing this @MireyaD ! I will take a look at the latest version today. 

> Should we include in Usage Metrics the Kepler.gl maps too?

I wouldn't do it for now, as I am not sure we have an easy way to count them as we do with the rest of the maps. I thing that a future improvement would be to count these maps as part of the public/private maps too instead of counting them separately.

**Comment by ana-md** [comment]
I have tested it and looks good to me, didn't find anything weird! 
Just one small thing, in the CARTO maps, the table is also a bit misaligned: 
<img width="909" alt="Screenshot 2020-03-03 at 09 58 40" src="https://user-images.githubusercontent.com/47864070/75759447-dec00f00-5d35-11ea-89c9-6bcd481ae78a.png">
