### ISSUE TITLE
[Dashboard] Remove create first map in Kepler maps section

### ISSUE THREAD

**Issue by ana-md** [CartoDB/cartodb#15523]
Similar to what reported @alejandraarri in #15522, we should remove the `create first map` section as it doesn't apply to Kepler's maps and it is confusing when someone just signs up: 

<img width="1438" alt="Screenshot 2020-03-09 at 10 39 12" src="https://user-images.githubusercontent.com/47864070/76200661-538dc000-61f2-11ea-997b-af358500b8b2.png">

**Comment by alejandraarri** [comment]
Deployed in production! 🚀

**Comment by ana-md** [comment]
Thank you!!
