### ISSUE TITLE
[Dashboard] Remove upgrade banners in Kepler maps section

### ISSUE THREAD

**Issue by alejandraarri** [CartoDB/cartodb#15522]
I entered into my `Individual` plan dashboard and banners regarding the pricing plan limits are appearing in the Kepler maps section which is confusing because these limits do not refer to kepler maps limitations, right?  Should we remove them?
![Screenshot 2020-03-06 at 17 06 47](https://user-images.githubusercontent.com/8669176/76101431-b868d080-5fce-11ea-995d-8dd24871fff6.png)

**Comment by ana-md** [comment]
Yes, please! 🙏 Thanks for checking this @alejandraarri

**Comment by alejandraarri** [comment]
Deployed in production! 🚀
