### ISSUE TITLE
not recognizing lon, lat

### ISSUE THREAD

**Issue by dandevmsc** [CartoDB/cartodb#15578]
### Context
Yesterday I imported the dataset and lon, lat was identified and so the the_geom column was populated. Today I run the same query and the the_geom column is not populated with the lon, lat.

### Steps to Reproduce

1.Create new table
2. run sql query : INSERT INTO {table name} (lat,lon,description,combined_key,confirmed,deaths,recovered) VALUES ('34.22333378','-82.46170658','location_summary','Abbeville South Carolina US','4','0.0','0.0')
3. tried also changing column names to latitude and longitude.
4. tried uploading csv directly but didn't work either. Yesterday I ran the same query and it worked.

### Current Result

<img width="762" alt="github issue" src="https://user-images.githubusercontent.com/25462840/77843430-14b9ad00-7195-11ea-9e53-068e8c328de1.PNG">
 
I created a new account and it worked.

### Expected result
I expect lat lon to be recognised

### Browser and version
chrome Version 80.0.3987.132 (Official Build) (64-bit)

**Comment by gonzaloriestra** [comment]
@CartoDB/rt-managers

**Comment by oriolbx** [comment]
@dandevmsc Running INSERT operations on a table doesn't populate the_geom column unless you explicitly insert data to that column.

If you want to populate the_geom column with an INSERT operation, then you would need to apply a query like the next one (using [ST_Point()](https://postgis.net/docs/ST_Point.html) and [ST_SetSRID()](https://postgis.net/docs/ST_SetSRID.html) PostGIS functions):

```sql
INSERT INTO {table name} (the_geom, lat,lon,description,combined_key,confirmed,deaths,recovered) 
VALUES (ST_SetSRID(ST_Point(34.22333378, -82.46170658'),4326)'34.22333378','-82.46170658','location_summary','Abbeville South Carolina US','4','0.0','0.0')
```

The column the_geom is only populated during the import process when the next conditions are met:

1. You have the import [type guessing option](https://carto.com/help/tutorials/import-data-guide/#2-import-data-from-add-datasets-menu) activated.
2. The longitude and latitude columns are number type and not text types.
3. The longitude and latitude columns have one of the next names: `longitude,lon,lng,longitudedecimal,longitud,long,decimallongitude,decimallong,point_longitude,latitude,lat,latitudedecimal,latitud,lati,decimallatitude,decimallat and point_latitude`

Please, use of the support@carto.com email address to ask technical questions or problems or if the problem remains after checking the previous steps.

**Comment by dandevmsc** [comment]
@oriolbx  thanks! that is clear now. 
 there was just a minor syntax error in the above code, this works:
```
INSERT INTO {table name} (the_geom, lat,lon,description,combined_key,confirmed,deaths,recovered) 
VALUES (ST_SetSRID(ST_Point(34.22333378, -82.46170658),4326),'34.22333378','-82.46170658','location_summary','Abbeville South Carolina US','4','0.0','0.0')
```
