### ISSUE TITLE
Wrong port in Central URLs in development

### ISSUE THREAD

**Issue by amiedes** [CartoDB/cartodb#15574]
When running CartoDB with the Docker setup in development, the billing URL has the wrong port so a routing error is raised if clicked on. It should be pointing to the Central port instead:

<img width="914" alt="Captura de pantalla 2020-03-25 a las 17 00 30" src="https://user-images.githubusercontent.com/9287468/77624023-7550ac00-6f41-11ea-9020-f31067e0bb89.png">

Notes:

- This might be happening to more URLs
- I think it's not an issue of the Docker setup itself.

**Comment by gonzaloriestra** [comment]
Closing in favor of https://app.clubhouse.io/cartoteam/story/83487/wrong-port-in-central-urls-in-development
