### ISSUE TITLE
[BUG] Cannot create and delete groups on Organizzation

### ISSUE THREAD

**Issue by nicoali** [CartoDB/cartodb#15571]
When trying to create a group an exception is thrown with the follow error:

{"error": {
"spiexceptions.ExternalRoutineException: spiexceptions.ExternalRoutineException: spiexceptions.ExternalRoutineException: TypeError: expected bytes-like object, not str"} }

Steps to Reproduce

*Please break down here below all the needed steps to reproduce the issue*

Test via rails console

irb(main):005:0>  group = @organization.create_group(display_name)
[pool] Creating a new connection for localhost:cartodb_user_e6d6f832-7528-4261-96f6-a28e4f78dd8a_db:5432:cartodb_user_e6d6f832-7528-4261-96f6-a28e4f78dd8a:ar (1)
ActiveRecord::StatementInvalid: PG::ExternalRoutineException: ERROR:  spiexceptions.ExternalRoutineException: spiexceptions.ExternalRoutineException: spiexceptions.ExternalRoutineException: TypeError: expected bytes-like object, not str
CONTEXT:  Traceback (most recent call last):
  PL/Python function "_cdb_group_creategroup_api", line 7, in <module>
    plpy.execute(query)
PL/Python function "_cdb_group_creategroup_api"
SQL statement "SELECT cartodb._CDB_Group_CreateGroup_API(group_name, group_role)"
PL/pgSQL function cdb_group_creategroup(text) line 7 at PERFORM
:  select cartodb.CDB_Group_CreateGroup('thedudes')
 from /var/lib/gems/2.4.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'

sometimes error is 
spiexceptions.InternalError: plpy.Error: Fatal Group API error: timed out

Inspecting via browser :
Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)

**Comment by gonzaloriestra** [comment]
@nicoali Thanks for reporting it, but in carto.com it's working fine and we are not able to reproduce it, so it's probably an installation/configuration issue.

**Comment by gonzaloriestra** [comment]
Related issue: https://github.com/CartoDB/cartodb/issues/15469
