### ISSUE TITLE
feature request: a shortcut to run SQL query when editing SQL in Builder table view

### ISSUE THREAD

**Issue by davidnmora** [CartoDB/cartodb#15584]
(not sure if this is the appropriate place to make feature requests, or if this is even substantial enough 😛 )
### Feature request
The SQL editor is awesome. It'd be a huuuuge workflow increase to be able to edit the SQL and then just hit something like command-enter (Mac) to run that query. Instead of having to click "Apply" each time.

![image](https://user-images.githubusercontent.com/6570507/78081872-66fdf800-7366-11ea-8890-75784e64a484.png)

**Comment by VictorVelarde** [comment]
HI @davidnmora.

Doesn't the current CMD + S (Mac) work for you?

**Comment by VictorVelarde** [comment]
Feel free to reopen it if it doesn't

**Comment by davidnmora** [comment]
Perfect, thanks! Where can I find a list of shortcuts? 😄

**Comment by VictorVelarde** [comment]
Sorry, but we don't have it. 

It looks like you didn't notice the hint at...
![image](https://user-images.githubusercontent.com/458196/80223274-5df00600-8648-11ea-96d5-a7757062973c.png)
...so we should probably improve a bit the style on that piece!
