### ISSUE TITLE
Integrate medusa within new-dashboard

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#1560]
We good way would be to have a CartoDB.js method.
@javierarce, you will implement it, won't you?

cc @javisantana

**Comment by xavijam** [comment]
@javisantana @javierarce ping, i need you for this feature.

**Comment by xavijam** [comment]
@javierarce, take into account that map preview should appear in new public dashboard and in affected maps when user is deleting a dataset :DD. @viddo will help you, don't worry.

**Comment by javierarce** [comment]
:ok_hand:
