### ISSUE TITLE
Cookie SameSite attribute

### ISSUE THREAD

**Issue by d-damien** [CartoDB/cartodb#15845]
### Context
Just connected to a CartoDB (local) install.

### Current Result
Warning message regarding `_cartodb_session` cookie :
> Cookie “_cartodb_session” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

Considering it's the session cookie, won't users be at risk of losing ability to connect ?

### Browser and version
Firefox 80.0.1

**Comment by sabman** [comment]
I assume it's not running over HTTPS? I suspect over HTTPS it will (probably) add the `Secure` attribute as per the spec:

> A Secure cookie is only sent to the server with an encrypted request over the HTTPS protocol. Note that insecure sites (http:) can't set cookies with the Secure directive.

**Comment by d-damien** [comment]
You're right, but since it's a session cookie, couldn't `SameSite` be set to `Strict` ? Apparently it's better against CSRF attacks too.
