### ISSUE TITLE
CartoDB Connect and Direct SQL Connection

### ISSUE THREAD

**Issue by Julius-ERCM** [CartoDB/cartodb#15909]
Is the CartoDB Connect and Direct SQL Connection feature not available in the open source setup?

If I go to the "Connect" tab when adding a new dataset, I see the "Database" card with a lock over it saying "Enterprise"

As for the Direct SQL Connection, I don't see any "Connections" menu in the Settings. I would really like to connect externally, if possible, to avoid having to make Carto's SQL API calls from a separate API project and just have it connected through a PSQL connector.

Thank you

**Comment by ilbambino** [comment]
it is only available in CARTO for enterprise accounts. It is not open source, sorry.
