### ISSUE TITLE
clone with inaccessible submodule fails the clone process (cartodb-private)

### ISSUE THREAD

**Issue by sabman** [CartoDB/cartodb#16051]
I am running into problems while trying out the latest `master` branch due to the `cartodb-private` submodule's inclusion. 

It breaks cloning the repository and is breaking some of our CI pipelines... could someone please enlighten me as to the purpose of having a private submodule in an open source and public repository? With an open source project you shouldn't include completely private submodules as dependencies it defeats its purpose.

**Comment by Stivens73** [comment]
Also encountered this issue from one of Dockerized carto images. Seems like this is an error, at least I hope so.

**Comment by sabman** [comment]
the PR that originally added the submodule is here:
https://github.com/CartoDB/cartodb/pull/16023 

I am wondering if there are any ideas on a better way to manage this? For now i could either clone without the `--recursive` flag and also comment out the private submodule from the `.submodule`file. 

```bash
sed -i '.bak' 's/\[submodule "private"\]/#&/' .gitmodules
sed -i '.bak' 's/^[[:space:]]*url = git@github.com:CartoDB\/cartodb-private\.git/#&/' .gitmodules
sed -i '.bak' 's/^[[:space:]]*path = private/#&/' .gitmodules
```

I'm sure there's a better way though, any suggestions?

**Comment by Stivens73** [comment]
@sabman, you can also run it with `-n` flag for a shallow copy

**Comment by sabman** [comment]
looking more closely at the PR where private submodule was added it seems its about the new CI. So it's possible that the release will be excluded.

**Comment by ilbambino** [comment]
the `private` submodule adds some things mostly for the CI as you said. For different business reasons we have decided not to release those in the open source version. 
we are sorry for any inconveniences caused, but we considered different options and the submodule was the less intrusive one.
You will have to apply any of those workarounds for the time being. We will add a note in the README to clarify it. But unfortunately we cannot remove it, or it will break our current CI setup.

**Comment by Oreilles** [comment]
In case anyone stumble into this, here's the solution:

```bash
git clone https://github.com/cartodb/cartodb.git
cd cartodb
git rm private
git submodule update --init --recursive
```

**Comment by sutanAE** [comment]
> In case anyone stumble into this, here's the solution:
> 
> ```shell
> git clone https://github.com/cartodb/cartodb.git
> cd cartodb
> git rm private
> git submodule update --init --recursive
> ```

hi @Oreilles it seems like this does not work anymore?
