### ISSUE TITLE
Error pages fail to load local assets

### ISSUE THREAD

**Issue by juanje** [CartoDB/cartodb#1608]
In a local CartoDB installation, using the local assets, the error pages (`public/403.html`, `public/404.html`, `public/422.html` and `public/500.html`) fail to load the assets and show a very ugly page.

![screen shot 2014-12-26 at 13 28 15](https://cloud.githubusercontent.com/assets/36670/5557755/457602da-8d03-11e4-872d-21c371c94188.png)

**Comment by azamorano** [comment]
The issue here is that at some point it changed the way assets are deployed and the static pages wont found them in the hardcoded link. We should probably include all the necessary assets included in the static error page.

**Comment by Xatpy** [comment]
Would also be this [ticket](https://github.com/CartoDB/cartodb-onpremise/issues/50) related to ??

**Comment by zenitraM** [comment]
It seems the error pages in public/ are hardcoded to the location of the assets that were generated before moving to Grunt.

Probably the css of those pages should be either embedded or at the public folder. Also didn't we have a new 404?

cc @matallo

**Comment by matallo** [comment]
indeed, IMO these pages in public should be self-contained (no external assets required)

**Comment by Xatpy** [comment]
Closing this issue because it was done [here](https://github.com/CartoDB/cartodb-platform/issues/257)
