### ISSUE TITLE
Can't see zoom controls in map view of a table shared with me

### ISSUE THREAD

**Issue by jorgeas80** [CartoDB/cartodb#1632]
I'm not the owner of the table, but the table is shared with me. I can't see the zoom control or the search box in map view

![screen shot 2014-12-30 at 1 31 57 pm](https://cloud.githubusercontent.com/assets/772448/5578564/450739d4-902a-11e4-984e-0a78431126d3.png)

**Comment by Xatpy** [comment]
please @jorgeas80 , one question: the owner of the table has the zoom control and the search box enabled in his viz?
Meanwhile, could you share with me one table that I can check/debug the issue? Thanks!

**Comment by Xatpy** [comment]
I've been checking it, and it's a problem of permissions. 
I've been checking the tables shared in our organization, and there's an error when trying to get the */api/v1/viz/:id/overlays* ==> **403 (Forbidden)**. 

For example, in the visualization becauseoffutbol:
![screen shot 2015-01-20 at 16 15 13](https://cloud.githubusercontent.com/assets/3958416/5819657/d049c57a-a0bf-11e4-88c9-7c9549f2c705.png)
And the same thing happens with others visualizations in our org.

@rochoa @javisantana please, could you help me a little with it? (Sincerely, I don't know who I should ask; but I'm asking you because it could be related to API).

**Comment by rochoa** [comment]
Please, could you add here the response body from that request?

On Tue, Jan 20, 2015 at 4:20 PM, Jaime <notifications@github.com> wrote:

> I've been checking it, and it's a problem of permissions.
> I've been checking the tables shared in our organization, and there's an
> error when trying to get the */api/v1/viz/:id/overlays* ==> *403
> (Forbidden)*.
>
> For example, in the visualization becauseoffutbol:
> [image: screen shot 2015-01-20 at 16 15 13]
> <https://cloud.githubusercontent.com/assets/3958416/5819657/d049c57a-a0bf-11e4-88c9-7c9549f2c705.png>
> And the same thing happens with others visualizations in our org.
>
> @rochoa <https://github.com/rochoa> @javisantana
> <https://github.com/javisantana> please, could you help me a little with
> it? (Sincerely, I don't know who I should ask; but I'm asking you because
> it could be related to API).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/1632#issuecomment-70669841>.
>



-- 
Raul Ochoa
rochoa@cartodb.com

**Comment by Xatpy** [comment]
The response tab is empty. :confused: 

I'm attaching the response header:
![screen shot 2015-01-20 at 16 48 01](https://cloud.githubusercontent.com/assets/3958416/5820285/3f185fe4-a0c4-11e4-9821-1e027240cb66.png)

I'm not sure if it's relevant, but the *Initiator* is **tracker.js:17** .

**Comment by Xatpy** [comment]
It's a permission issue. The scenario is always the same: trying to visualize a map that it's shared with you, but you're not the owner. 
I think that this could be a backend issue. Please, @Kartones || @juanignaciosl || @rafatower , could you take a look when you have a chance? Thanks!

**Comment by juanignaciosl** [comment]
Ok, it happens in the map view of a table (not a visualization) when user has write permissions (if he only can view it he's redirected to pubic page, which does display zoom controls). Took a while to reproduce but I'm on it.

**Comment by Xatpy** [comment]
thanks @juanignaciosl ! (and sorry for the confusion: map<--->visualization )
