### ISSUE TITLE
Create the simplest delete dialog action

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#1633]
![screen shot 2014-12-30 at 15 53 54](https://cloud.githubusercontent.com/assets/978461/5579506/17bb7d34-903c-11e4-90f8-faab1e0f4942.png)

- [x] New base dialog + CSS for this styles (per #1602)
- [x] Open dialog from filters-menu
- [x] Should be able to open dialog when selecting multiple items
- [x] CSS animations on show/hide
- [x] CSS animations on badge icon
- [x] Be able to delete selected items
- [x] It should work with maps or datasets.
- [x] Same action for several items (only front requests), as per discussion outcome in #1441
- [x] export dialog do not exist yet, so needs to be implemented later, for now display a cancel button and "export your datasets" as normal text.
- [x] error case, when deletion fails

**Comment by viddo** [comment]
Yes, those warning-cases are designed but will not be implemented in the scope of this issue (see the previous comments on this thread for a reference).

I was not talking about can-or-cannot-delete (permission) errors, but technical ones (server-side errors, e.g. deletion failed due to some error on the server that we cannot check/control from the client-side), but if you don't consider those cases to be a concern I leave this as it is.

Btw, I noticed another behaviour we might want to re-iterate on: since the new functionality allows to delete multiple items simultaneously there can be a significant delay until all selected items are deleted, e.g. ~10 sec to delete 20 items in my local dev env. During that period there is no indication that there are things being deleted.

**Comment by saleiva** [comment]
Cool, I'll create a loading state :)

**Comment by saleiva** [comment]
Done, we can keep this as a generic loader for operations that will happen until clicking a button. When done, the modal window should be close.

![dashboard - user private - datasets delete dataset loading](https://cloud.githubusercontent.com/assets/132149/5616251/14aeead8-9503-11e4-82db-25e5726c1ce3.png)

**Comment by viddo** [comment]
@saleiva @xavijam it's really necessary for doing batch operations that take some significant amount of time. based on yesterday's offline discussion and considering we've disabled batch operations for the time being, I'd propose to create an issue in the backlog and leave it for later. sounds reasonable to you?

**Comment by saleiva** [comment]
This will be needed on other modals like it is in the actual dashboard, like deleting (sometimes) or retrieving your tables list. Up to you guys
