### ISSUE TITLE
Design for export data dialog

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#1634]
The delete dialog should have a "export data" link according to the new design sketch:
![screen shot 2014-12-30 at 15 53 54](https://cloud.githubusercontent.com/assets/978461/5579762/21ed76aa-9040-11e4-8079-58aa8d2c1908.png)

Supposedly it should work in the same way as on the current dashboard, but have not see any new sketches for this use-case.

**Comment by saleiva** [comment]
Done!
Source available at dashboard-1.3.sketch

![dashboard - user private - datasets export datasets](https://cloud.githubusercontent.com/assets/132149/5612641/b539df6a-94d8-11e4-8b20-9d73157ad7f8.png)

**Comment by viddo** [comment]
thx mate!
