### ISSUE TITLE
Stored Cross-site scripting on Maps

### ISSUE THREAD

**Issue by geluxd** [CartoDB/cartodb#16373]
### Summary:
While creating a new map, the malicious user can rename the map into an XSS payload and it will be stored. If another user of your organization clicked the map, he/she will be executing the xss being stored in the Map. 

### Payload used:
 ` "><img src=x onerror=alert(1)> `

### Steps to Reproduce:
1. Go to your created account > Home
2. Edit the name of the created map into a malicious xss payload (I prefer to put a long name or anything so the payload will be hidden)
3. Click the map and you will see a popup alert box
![carto](https://user-images.githubusercontent.com/78854276/141711028-64efc9ac-f7b5-4702-a6ec-2f6ecd1de2da.png)

The name field is not been sanitized for XSS attacks. By this vulnerability, any user of the organization can be the victim.

### Browser:
Mozilla firefox 94.0.1

### Suggested fix/Solution:
The prevention of this attack is Input/Data validation, Filtering, and escaping. Everything that is entered by the user should be precisely validated, because the user's input may find its way to the output.

### Impact:
The main purpose of this attack is to steal the other user's identity data-cookies, session tokens and etc.

**Comment by geluxd** [comment]
Hi Team, are there any updates?

**Comment by ilbambino** [comment]
Thank you very much for the report. We are currently working on a fix

**Comment by geluxd** [comment]
Sweet! Thank you for the update.

**Comment by geluxd** [comment]
Hi, while checking on this, it's no longer reproducible.

**Comment by geluxd** [comment]
Wrong button.

**Comment by ilbambino** [comment]
yes, we deployed yesterday the fix to prevent it. 

Thank you very much for reporting it.
