### ISSUE TITLE
Incompatible with Firefox 100 

### ISSUE THREAD

**Issue by nxmndr** [CartoDB/cartodb#16416]
### Problem
Carto doesn't allow Firefox to login or even display any map, and shows the "HTML5 Browsers" message instead.
Confirmed by others : https://gis.stackexchange.com/questions/430489/carto-not-supported-in-firefox-100
Could it be a user agent problem ? https://www.bleepingcomputer.com/news/software/mozilla-warns-chrome-firefox-100-user-agents-may-break-sites
### Browser and version
Firefox 100.0 64bits on MacOS 11.5

**Comment by sabman** [comment]
addressed here https://github.com/CartoDB/cartodb/pull/16415

**Comment by nxmndr** [comment]
Thanks.
