### ISSUE TITLE
CARTO API IMPORT PROBLEMS

### ISSUE THREAD

**Issue by fsalazarcitelum** [CartoDB/cartodb#16434]
I'm trying to use the import function of the CARTO API, but I had problems trying to import a csv file from the local. I'm not sure what I have to put in the url field in the body, or there is other field different to import files.

![image](https://user-images.githubusercontent.com/110618202/182881225-5a2e0abd-7e14-493e-a7e9-60fd33b1034b.png)

**Comment by thedae** [comment]
Hi @fsalazarcitelum , thanks for your message

The `v3` import endpoint does not currently support uploading from local files, only from external URLs. If you're still interested in uploading a local file, I suggest you to use Data Explorer in your [CARTO workspace](https://app.carto.com/)
