### ISSUE TITLE
Points layer goes to the bottom when changed to cluster points layer

### ISSUE THREAD

**Issue by jorgeas80** [CartoDB/cartodb#1644]
Steps to reproduce this:

1. Create a visualization with polygon layer + single points layer. Points layer on the top, of course
2. Change points layer to cluster points layer
3. The cluster points layer always appears on the bottom.

Image attached for clarification
![cluster_points_problem](https://cloud.githubusercontent.com/assets/772448/5595974/bdac1950-9281-11e4-89ad-ae84fe3cf04d.gif)

**Comment by xavijam** [comment]
I feel it is related with Mapnik. [marker-comp-op](https://github.com/mapbox/carto/blob/master/docs/latest.md#marker-comp-op-keyword) property makes this thing happen. After comment that line in the CartoCSS, everything works like a charm.
![screen shot 2015-01-12 at 11 27 30](https://cloud.githubusercontent.com/assets/132146/5701618/1540e3fc-9a4e-11e4-8ebe-99ada296830d.png)

@rochoa do you know if this property is essential?

**Comment by xavijam** [comment]
Pull request: https://github.com/CartoDB/cartodb/pull/1702

**Comment by rochoa** [comment]
Once removed it will use the default behaviour, in this case `src-over`: https://github.com/mapbox/carto/blob/master/docs/latest.md#marker-comp-op-keyword

Check tilemill examples to understand it: https://www.mapbox.com/tilemill/docs/guides/comp-op/#alpha-blending ;-)

**Comment by xavijam** [comment]
That's what I needed, thanks!
