### ISSUE TITLE
Order available layers by user (mines first) when creating a visualization (mu accounts)

### ISSUE THREAD

**Issue by jorgeas80** [CartoDB/cartodb#1645]
Just check attached image

![screen shot 2015-01-02 at 12 54 14 pm](https://cloud.githubusercontent.com/assets/772448/5595990/5a6d1302-9282-11e4-8893-95d5eb7fc4c8.png)

**Comment by saleiva** [comment]
Mark as closed since this will be fixed with the redesign.
