### ISSUE TITLE
WMS doesn't work correctly

### ISSUE THREAD

**Issue by Xatpy** [CartoDB/cartodb#1653]
This issue has been reported from Support too.

I have tested the WMS basemap ([etopo1_hillshade](http://maps.ngdc.noaa.gov/soap/web_mercator/etopo1_hillshade/MapServer/WMSServer?request=GetCapabilities&service=WMS)) from this [tutorial](http://vimeo.com/79772252) and it's blank (image attached).
![screen shot 2015-01-05 at 13 03 57](https://cloud.githubusercontent.com/assets/3958416/5612828/5ccb37cc-94db-11e4-9422-ef425777f81a.png)

I have been checking this [**list**](http://www.ngdc.noaa.gov/wiki/index.php/WMS_Service_List) (Web Mercator section) and only [marine_geology](http://maps.ngdc.noaa.gov/soap/web_mercator/marine_geology/MapServer/WMSServer?request=GetCapabilities&service=WMS) worked.
![screen shot 2015-01-05 at 13 07 22](https://cloud.githubusercontent.com/assets/3958416/5612879/d098fe6e-94db-11e4-9593-c5c0964da8f7.png)

@juanignaciosl had problems with his [visualization](https://team.cartodb.com/u/juanignaciosl/viz/6a264960-6903-11e4-ad6b-0e018d66dc29/public_map) too.

Also, @javierarce talked about perhaps there could be a problem with WMS proxy.

**Comment by saleiva** [comment]
Hey @zenitraM, could you take a look?

**Comment by zenitraM** [comment]
This seems to be related to the WMS proxy mistranslating the URL. It tries to fetch this tile:

http://maps.ngdc.noaa.gov/arcgis/services/web_mercator/etopo1_hillshade/MapServer/WmsServer?styles=&amp;format=image%2Fpng&amp;height=512&amp;bbox=-20037507.8428,-20037508.3428,20037507.8428,20037508.3428&amp;transparent=True&amp;layers=ETOPO1+Hillshade&amp;service=WMS&amp;width=511&amp;request=GetMap&amp;srs=EPSG%3A3857&amp;version=1.1.1

which returns an error from the WMS server:
```<ServiceExceptionReport version="1.1.1">
<ServiceException code="InvalidFormat">Can't parse XML request.</ServiceException>
</ServiceExceptionReport>```

Not sure if this is an error on their side or on our MapProxy side. Contacting @olt to see if he could give us any hint

**Comment by olt** [comment]
The URL contains &amp; instead of &. Is this the actual URL from the logs or do the &amp;s come from copy&pasting?
Also the layer name contains a whitespace and if I change if from + to %20 then the following request works:

http://maps.ngdc.noaa.gov/arcgis/services/web_mercator/etopo1_hillshade/MapServer/WmsServer?styles=&format=image%2Fpng&height=512&bbox=-20037507.8428,-20037508.3428,20037507.8428,20037508.3428&transparent=True&layers=ETOPO1%20Hillshade&service=WMS&width=511&request=GetMap&srs=EPSG%3A3857&version=1.1.1

**Comment by zenitraM** [comment]
That URL is the one shown by the error when requesting the tile: 

https://cartodb-wms.global.ssl.fastly.net/mapproxy/maps_ngdc_noaa_gov_ETOPO1_Hillshade_EPSG_3857/wmts/map/webmercator/3/7/3.png

could it be that the frontend is sending + instead of %20 on sending the configuration to MapProxy? It should be %20. @xavijam @javierarce @javisantana

**Comment by xavijam** [comment]
Ok, I'll take care of it.

**Comment by zenitraM** [comment]
@olt hmm, it looks that the frontend is sending the URL correclt. What is stored on services.csv for MapProxy is:

```maps_ngdc_noaa_gov_ETOPO1_Hillshade_EPSG_3857,wms,http://maps.ngdc.noaa.gov/soap/web_mercator/etopo1_hillshade/MapServer/WMSServer?request=GetCapabilities&service=WMS,ETOPO1 Hillshade,EPSG:3857,```

with a space, not %20 or +. So the proxy is the one that is adding the + instead of the %20

**Comment by iriberri** [comment]
We are having similar issues with WMS from http://geo.nls.uk/urbhist/resources_maps.html reported in Support.

The check endpoint returns:

`````
jQuery17206231766261626035_1423232205513({
  "error": "not a valid capabilities document"
})
`````

But we're not sure if the WMS is not really supported or if there's some parameter not configured.

More details: https://github.com/CartoDB/cartodb/issues/2113

**Comment by zenitraM** [comment]
@iriberri that looks like a different issue, that URL returns an error:

```
<HTML>
<HEAD><TITLE>MapServer Message</TITLE></HEAD>
<!-- MapServer version 5.2.1 OUTPUT=GIF OUTPUT=PNG OUTPUT=JPEG OUTPUT=WBMP OUTPUT=PDF OUTPUT=SWF OUTPUT=SVG SUPPORTS=PROJ SUPPORTS=AGG SUPPORTS=FREETYPE SUPPORTS=ICONV SUPPORTS=FRIBIDI SUPPORTS=WMS_SERVER SUPPORTS=WMS_CLIENT SUPPORTS=WFS_SERVER SUPPORTS=WFS_CLIENT SUPPORTS=WCS_SERVER SUPPORTS=SOS_SERVER SUPPORTS=FASTCGI SUPPORTS=THREADS SUPPORTS=GEOS SUPPORTS=RGBA_PNG INPUT=JPEG INPUT=POSTGIS INPUT=OGR INPUT=GDAL INPUT=SHAPEFILE -->
<BODY BGCOLOR="#FFFFFF">
mapserv(): Web application error. Traditional BROWSE mode requires a TEMPLATE in the WEB section, but none was provided.
</BODY></HTML>
```

The only issue is the frontend not parsing the error response well

**Comment by iriberri** [comment]
That's why we were suggesting if maybe that URL needs some extra parameters, or if it's just that the source is not working. :smile:

**Comment by iriberri** [comment]
We're having a new issue regarding this.

A user tried to use this: http://webgisdgo4.spw.wallonie.be/ARCGIS/SERVICES/DGO4/FERRARIS/MapServer/WMSServer

which is working in QGIS and in a couple of WMS viewers I found on the internet, but in CartoDB the behaviour is:

* The WMS gets "analyzed" and the list of layer appears
* It only has a layer, called 0, select it
* The map appears totally empty as in the first image of this issue, although it contains actual data.

**Comment by saleiva** [comment]
bump!

**Comment by andrejjh** [comment]
Hi Salelva, 
About http://webgisdgo4.spw.wallonie.be/ARCGIS/SERVICES/DGO4/FERRARIS/MapServer/WMSServer

Is there a chance to get this URL working as base layer with CartoDB?
Or should I better do it outside of CartoDB?
André

**Comment by iriberri** [comment]
One more time: SB/5017849

ping @saleiva

**Comment by ztephm** [comment]
Hi, here's another that is working in other services, but it's invalid in ours (required URI parameter 'request' is missing or empty): SB/5029249

**Comment by javisantana** [comment]
fixes in:

https://github.com/mapproxy/mapproxy/commit/da0de72a321621b9bdb62cab8f8eb5f3ea3ffbc1
https://github.com/mapproxy/mapproxy/commit/9171ebe21a24c3ef71456355bd7aad6351cc48bc

more info coming

**Comment by zenitraM** [comment]
Finally fixed by upgrading mapproxy to latest master, see: http://cdb.io/1B6ZNLT
