### ISSUE TITLE
Create export data dialog

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#1658]
![screen shot 2015-01-05 at 17 38 44](https://cloud.githubusercontent.com/assets/978461/5616131/cb5a85e6-9501-11e4-9166-6cd333290910.png)
_(from dashboard-1.5.sketch)_

- [x] Visually should look like in screenshot (see above)
- [x] Add link in the edit (options) menu in the editor
- [x] User can only export a single dataset at a time

**Comment by saleiva** [comment]
Since this will be needed for the new editor, we can close this isssue for the time being, and reopen once we have this modal implemented.

**Comment by viddo** [comment]
@saleiva updated description & scope to match current situation:
 - Since [we agreed to not do batched export to start with](https://github.com/CartoDB/cartodb/issues/1660) I'll removed that from the scope, so will work the same as for current export (single dataset)
 - To reach export modal directly form delete dialog is something I consider nice-to-have so put that scope on a separate issue, see #3847
