### ISSUE TITLE
Create svg dashboard icons for table type

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#1659]
cc/ @viddo

**Comment by carlostallon** [comment]
@sergio, you mean like this ones?

https://www.dropbox.com/s/b0v0xte097882zy/Captura%20de%20pantalla%202015-01-07%2017.11.35.png?dl=0

**Comment by saleiva** [comment]
Wep, in the actual version they are kind of blurry...

**Comment by carlostallon** [comment]
Done, sent to frontend guys
