### ISSUE TITLE
Maps or Datasets dropdown CSS looks outdated 

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#1667]
Here is the final design
![screen shot 2015-01-07 at 12 47 53](https://cloud.githubusercontent.com/assets/132149/5645104/798498ae-966b-11e4-9a3c-d4487baf1a9b.png)

**Comment by xavijam** [comment]
Shared maps or datasets links are not present, is it ok?

**Comment by saleiva** [comment]
Think so

**Comment by xavijam** [comment]
https://github.com/CartoDB/cartodb/pull/1734
