### ISSUE TITLE
Be able to filter by dataset size on the new dashboard

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#1671]
- [ ] update designs 
- [ ] implementation

After design, assign to @xavijam

**Comment by carlostallon** [comment]
Filter by dataset size mockup (updated in style guide tabs section)

![captura de pantalla 2015-01-13 12 59 48](https://cloud.githubusercontent.com/assets/1712650/5720420/1d746090-9b24-11e4-9a5d-dab2b47b554f.png)

**Comment by saleiva** [comment]
ji ji ji :smile:
