### ISSUE TITLE
multiuser quota is not well calculated in multiuser dashboard

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#1685]
the percent should be multiplied by 100, in the screenshot should be 169%

![screen shot 2015-01-08 at 5 23 32 pm](https://cloud.githubusercontent.com/assets/30147/5665796/2505836a-975b-11e4-81f4-926301bba5de.png)

**Comment by Xatpy** [comment]
Also, the related problem is that the user can't change his limit quota 
![screen shot 2015-01-09 at 11 13 51](https://cloud.githubusercontent.com/assets/3958416/5678375/1cacbb56-97f2-11e4-98e4-923cb71ec23a.png)

(and he has space in his organization):
![screen shot 2015-01-09 at 11 21 16](https://cloud.githubusercontent.com/assets/3958416/5678357/cb71eb12-97f1-11e4-8cc3-e2feb9c00020.png)

**Comment by Xatpy** [comment]
I've to check [here](https://github.com/CartoDB/cartodb/blob/171026a90bd3c84e70ed6e89e92a0c683be1079b/app/views/admin/organization_users/_form.html.erb#L181)
