### ISSUE TITLE
Url rewrites

### ISSUE THREAD

**Issue by Kartones** [CartoDB/cartodb#1693]
Implement the option of not relying on usernames being always present at subdomains `xxxxx.mydomain.ext/blablabla`. They would appear always at `mydomain.ext/u/xxxxx/blablabla`.

This must be config-controlled, by default not active and totally optional, but code like `Cartodb.extract_subdomain` calls need to be rewritten to support it. 

Multiuser URLs code will probably benefit from some cleaning due to this changes.

Code also allows to setup a different base port for urls generated (`http_port` config entry, can be left empty).

Notes: 
- As discussed, organizations don't work if the `subdomains_allowed` flag is set to false.
- Changing code inside `Cartodb.extract_subdomain` and `Cartodb.base_url` fixed many scenarios and in general makes everything work (and Warden needs no changes), but there might be some issues if somewhere a url is handcrafted instead of using those.
- Full review of `routes.rb` has been done, but `/superadmin` calls haven't been tested.
- Definetly the editor needs clientside changes for some urls built there. See the internal wiki page for more details of issues found.
- **How to activate domain-less**: at `app_config.yml`, set:
```
  session_domain:     'localhost.lan'
  subdomains_allowed: false
```
Note that session domain looks the same but doesn't begins with a '.'

**Comment by javisantana** [comment]
> As discussed, organizations don't work if the subdomains_allowed flag is set to false.

that means a organization user will not work or organization urls will not work (but the user still does) ?

**Comment by Kartones** [comment]
I'll write a test to make sure is the second scenario:
> organization urls will not work (but the user still does) 

Which is what I want. Organizations should be "invisible" regarding urls if this flag is set to false, so would make no sense to have them but if present no routing should break.

**Comment by javisantana** [comment]
a new questions: 

is it possible that old urls (user.host.com) and (host.com/u/user) work at the same time?

**Comment by Kartones** [comment]
> is it possible that old urls (user.host.com) and (host.com/u/user) work at the same time?
I kill you. It is a flag that says `subdomains_allowed`, not `domainless_allowed` :P

Right now the code branches/ifs, so is either one or the other. Could be done but would introduce more logic everywhere, including on the frontend, as some urls are built there instead of passed by backend.

If you see it worth the effort, I can do it

**Comment by javisantana** [comment]
>  as some urls are built there instead of passed by backend.

That's is being fixed in the branch you are working on for the frontend

> If you see it worth the effort, I can do it

Yes, it would be really good to allow both url sets just in case we want to use this in the cloud (and we will do for sure :P)

**Comment by Kartones** [comment]
Ok, after our talk it will have support for BOTH also, not only being an exclusive flag.

Also must check compatibility with organizations, should just ignore org. check on the url if using subdomain-less, but everything should work.

**Comment by Kartones** [comment]
Must take into account changes that will be added at https://github.com/CartoDB/cartodb/pull/2588

**Comment by Kartones** [comment]
@javisantana I would need you to fix whenever you can the FE code regarding `cdb.config.get("sql_api_template")` change, as it breaks FE tests

**Comment by Kartones** [comment]
Note: First iteration will give preference tu subdomain-based urls if subdomains are allowed but optional.
A second iteration can be done that detects request url format, sets some flag and then allows to act accordingly.

**Comment by freakabcd** [comment]
I was eagerly awaiting the merge of issue-1693 into master; but I am not entirely sure if this issue has been fixed.

I just tried once more to deploy cartodb in an ubuntu 14.04 VM running on my workstation. This process is shown here https://gist.github.com/freakabcd/fd73119869ba57e16751

* Accessing http://mymaps.lan:3000 from the VirtualBox host immediately redirects to http://mymaps.lan:3000/user//maps and shows the 404 page which links back to mymaps.lan:3000 via the 'Back to the Homepage' button.
* Accessing http://mymaps.lan:3000/user/subdomain shows the user page which says there are 0 datasets and 0 visualisations. *Every* link on this page except for the "userpage / 0 datasets / 0 visualisations" points to cartodb.com, so one cannot even log in :-(

Perhaps, I have simply misconfigured everything! Please add more information to the subdomainless wiki page or perhaps a new wiki page on how to setup cartodb in a VM on local_machine / cloud.

**Comment by Kartones** [comment]
Hi @freakabcd 

Have you setup the `subdomainless_url` config attribute to "true", `http_port` to `3000` and `session_domain` to `mymaps.lan`?

It might be just that, a misconfiguration issue. Check also [the small documentation wiki page](https://github.com/CartoDB/cartodb/wiki/How-to-setup-subdomainless-URLS) and let me know if the issues persist.

**Comment by freakabcd** [comment]
As you can see from the setup gist, I am setting `subdomainless_urls` to `true` and `session_domain` to `"mymaps.lan"`. I was not setting `http_port` to `3000` and noticed you added a commit to default it to `3000`. I still have the exact same 2 issues outlined before

Here is my [app_config.yml](https://gist.github.com/freakabcd/be0832dd7369077da1a3) I've changed all instances of `localhost.lan` to `mymaps.lan` as an additional measure.
My [database.yml](https://gist.github.com/freakabcd/4f491dd506135be49cc7) is identical to the sample in the repo. The `config/environments/development.js` files in Windshaft-cartodb and CartoDB-SQL-API are simply copies of the provided `config/environments/development.js.example` files

![cartodb instance in VM](http://i.imgur.com/JefURQf.png)
The green links are local. The red ones are all pointing back to cartodb.com, so I cannot login and add tables/visualisations. I'm not 100% convinced that this is a configuration-only issue.

**Comment by javisantana** [comment]
@freakabcd yes, that's a know issue. We accept pull requests :)
