### ISSUE TITLE
Text & image overlays are badly placed when the odyssey chapter list is open

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#1694]

**Comment by javierarce** [comment]
Instead of moving the overlays (which would cause more problems), I decided to fix this issue like this:

![od](https://cloud.githubusercontent.com/assets/4933/5706517/e561a6ce-9a81-11e4-8c8f-4980a5da973c.gif)

**Comment by javierarce** [comment]
Instead of moving the overlays (which would cause more problems), I decided to fix this issue like this:

![od](https://cloud.githubusercontent.com/assets/4933/5706523/fa93f8c6-9a81-11e4-88ea-06c2d9aad14b.gif)

/cc @javisantana, @saleiva

**Comment by javisantana** [comment]
:es:

**Comment by saleiva** [comment]
Sorry guys, but this doesn't work.
the chapters bars should 'push' the map to the right. Zoom controls and most of the overlays (titles and texts) are being placed on the left side, so we cannot do the odyssey lateral bar like it is right now.

**Comment by javisantana** [comment]
@saleiva we took that decision because resizing the map implies lot of extra work. We can test with that approach and see if it works. 

Basically the problem here: resizing the map changes the map viewport and that changes the visualization (embeds and so on) and overlays position

**Comment by saleiva** [comment]
Ok to leave as it is for the tests, but we will need this ready for production.
