### ISSUE TITLE
Fix several issues in the new-dashboard

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#1697]
- [x] DB size bar is not appearing anymore in the user dropdown.
![screen shot 2015-01-11 at 12 28 34](https://cloud.githubusercontent.com/assets/132146/5695067/634b239e-998d-11e4-9858-8c62182c6238.png)
- [x] Datasets item styles are not correct:
![screen shot 2015-01-11 at 12 25 49](https://cloud.githubusercontent.com/assets/132146/5695061/08c8af54-998d-11e4-9294-408b82406db0.png)
- [x] Don't let non datasets/maps owners delete those items.
![screen shot 2015-01-12 at 19 01 02](https://cloud.githubusercontent.com/assets/132146/5707957/623ad156-9a8d-11e4-9272-5b124282f204.png)
- [x] Disable multiple selection.
- [x] Add total item figures for filter sections.
- [x] Check loading problems when filter is set (updated_at, liked,...)
- [x] Add size (floppy disk) filter
- [x] Improve Maps and datasets empty descriptions/tags behaviour
- [x] Reviewed empty states:
![screen shot 2015-01-13 at 16 55 15](https://cloud.githubusercontent.com/assets/132146/5723538/05bca784-9b45-11e4-940b-276655c8002f.png)
- [x] In shared datasets or maps, when tags or description is not defined, text should be 'No tags/description'.

cc @viddo

**Comment by viddo** [comment]
> DB size bar is not appearing anymore in the user dropdown.

Ouch! My bad :(

> Datasets item styles are not correct

Can you specify what is wrong with the datasets item styles?


Either way I'll take care of fixing these

**Comment by viddo** [comment]
@xavijam re: _Datasets item styles are not correct_ now when working on another issue, according to the sketch file those metadata items should have size of 13px and the light weight, so they are actually correct technically. @carlostallon can you confirm that this is the wanted style?

**Comment by xavijam** [comment]
https://github.com/CartoDB/cartodb/pull/1738

**Comment by carlostallon** [comment]
Can you send me an screenshot @viddo?
