### ISSUE TITLE
Error when connecting to mailchimp

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#1699]
It says that the oauth failed, but if clicking the "connect with mailchimp" button again, it just works.

**Comment by juanignaciosl** [comment]
Could you please try again? I can't reproduce (neither staging nor production).

**Comment by saleiva** [comment]
I cannot, since I don't know how to disconnect my mailchimp account :(

**Comment by juanignaciosl** [comment]
If you use incognito mode button will show up.

**Comment by saleiva** [comment]
Nope, the button is there, but the account is already connected so I don't have to do the auth process.

**Comment by juanignaciosl** [comment]
You must do it in Mailchimp: user (top right) --> account --> extras --> api keys, and there press "X" at CartoDB row.

**Comment by saleiva** [comment]
How can we change that icon?

**Comment by saleiva** [comment]
Ok, I couldn't replicate.
