### ISSUE TITLE
Add olark chat to the editor screens

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#1700]
Ask @saleiva for the credentials.

**Comment by javisantana** [comment]
ok, some requirements:

- there should be a entry in app_config.yml for olark config
- if there is no config, olark is not enabled
- olark javascript and assets are loaded async
- all the code should be isolated in a single file (if we need to write code for this)

Keep in mind: this shouldn't be in cartodb, this is a hack

**Comment by xavijam** [comment]
- there should be a entry in app_config.yml for olark config
OK
- if there is no config, olark is not enabled
OK
- olark javascript and assets are loaded async
It is loaded as GAnalytics or mixpanel, only needs the html and the app id.
- all the code should be isolated in a single file (if we need to write code for this)
No more code needed, maybe a bit of CSS.

**Comment by xavijam** [comment]
BTW @saleiva, where is the best location to place it?

![screen shot 2015-01-12 at 12 26 21](https://cloud.githubusercontent.com/assets/132146/5702175/8e65cb3c-9a56-11e4-91ee-3034c186b03f.png)

We have problems with attributions and/or non-activated layers.

**Comment by saleiva** [comment]
Id' leave it there for the time being

**Comment by xavijam** [comment]
Roger, https://github.com/CartoDB/cartodb/pull/1707
