### ISSUE TITLE
Move the number of subscribers info of the mailchimp importer to the second line

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#1701]
We're currently showing 'File size not provided', and it doesn't make sense. 

@Kartones assign me the ticket once the backend part is ready, please.

**Comment by juanignaciosl** [comment]
@javierarce now you can get subscribers from member_count field, and I've removed it from the title. Please tell me if this is not what you needed!

**Comment by saleiva** [comment]
Hey, assigning this to @Xatpy to see if he can helps there

**Comment by Xatpy** [comment]
@javierarce Should I work on **import_service_item.jst.eje** (`lib/assets/javascripts/cartodb/common/views/import/import_service_item.jst.ejs`) ? (It's the only result if I search *File size not provided* )
Please, could you tell me an example about anything related that I could check? Thanks!

**Comment by javierarce** [comment]
Yeah, that's the place. You'll probably want to add a new condition here (https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/common/views/import/import_service_item.jst.ejs#L7)
 and use the `member_count` info that @juanignaciosl added:

**Comment by Xatpy** [comment]
@javierarce @saleiva  What should be the text displayed? Member count? Members? No text?
![screen shot 2015-01-20 at 13 31 37](https://cloud.githubusercontent.com/assets/3958416/5817131/d5dcf3ac-a0a8-11e4-9e90-224bdd8ae520.png)

**Comment by saleiva** [comment]
"XXXXX members."

**Comment by Xatpy** [comment]
Changed. Thanks :)

@javierarce is there any *test* related to mailchimp stuff in frontend? I've searched, but I couldn't find anything.

**Comment by javierarce** [comment]
No, there's nothing specific, just the general tests for the dialog.

**Comment by Xatpy** [comment]
merged ([PR #1876](https://github.com/CartoDB/cartodb/pull/1876))
