### ISSUE TITLE
Error while importing from Mailchimp data

### ISSUE THREAD

**Issue by miguelarias** [CartoDB/cartodb#1711]
This is the message I get, after entering my mailchimp credentials, and before anything else happened, just after authentication.

{"errors":{"imports":"validate_callback({\"state\"=>\"__marias__mailchimp__\", \"code\"=>\"015412d0d14cefb3f1c92efd9d63e94f\", \"format\"=>:json, \"controller\"=>\"api/json/imports\", \"action\"=>\"service_oauth_callback\", \"id\"=>\"mailchimp\", \"user_domain\"=>nil}): Bad token response: \"\\x1F\\x8B\\b\\x00\\x00\\x00\\x00\\x00\\x00\\x03\\xAAVJ-*\\xCA/R\\xB2RJ\\xAD(\\xC8,JM\\x89/\\xC9\\xCFN\\xCDS\\xAA\\x05\\x00\\x00\\x00\\xFF\\xFF\\x03\\x00\\xDC\\xEE\\xC4\\xFE\\x19\\x00\\x00\\x00\" (400) @ mailchimp"}}

**Comment by saleiva** [comment]
Assigning to @juanignaciosl as @Kartones will not be able to take a look until next week.

**Comment by juanignaciosl** [comment]
@miguelarias please check again, because neither saleiva nor me have been able to replicate other Mailchimp errors that were happening days ago.

**Comment by juanignaciosl** [comment]
Working, checked by @miguelarias
