### ISSUE TITLE
Be able to have a map with 0 layers (just the basemap)

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#1713]
needed for new dashboard.
Take a look at all the collateral changes on interactions

cc/ @viddo

**Comment by viddo** [comment]
see #1687 for related context, "affected maps" means that they indeed are affected and not to be deleted as it is with current code

**Comment by Kartones** [comment]
ping! Does this even make sense?

**Comment by saleiva** [comment]
Will be needed more importantly on the new iteration for the editor, yeah.

**Comment by saleiva** [comment]
Not in a hurry tho...

**Comment by Kartones** [comment]
Closing for now, if needed reopen or recreate
