### ISSUE TITLE
row_count attribute has been disappear from visualizations endpoint

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#1718]
We have noticed that the row count for tables has been disappeared from the dashboard. I've checked the visualization endpoint and seems like we have changed the name of the necessary attribute from ```row_count``` to ```rows```, and that's why frontend can't render it.

**Comment by xavijam** [comment]
cc @iriberri

**Comment by iriberri** [comment]
Adding a comment just to subscribe here. (SB/4228939)
