### ISSUE TITLE
In safari the time selector layout on the transition pop-up is broken

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#1719]

**Comment by javierarce** [comment]
You mean this one? 

![screen shot 2015-01-13 at 12 53 17](https://cloud.githubusercontent.com/assets/4933/5720343/3b1c8fc4-9b23-11e4-8b1b-17c2adcc8b3f.png)

Give me more info about the issue, please.

**Comment by saleiva** [comment]
Yep, IMO should be better to have it left aligned in the same line.
Also I'd add an indicator saying that those are seconds!

**Comment by javierarce** [comment]
Hahaha, ok, but that's not "broken".

**Comment by saleiva** [comment]
I thought that was broken (sorry)

**Comment by javierarce** [comment]
No problem :) 

Is this fine?

![screen shot 2015-01-13 at 18 37 05](https://cloud.githubusercontent.com/assets/4933/5725455/3aaf77f6-9b53-11e4-8165-4ffe74fc7d42.png)

**Comment by javierarce** [comment]
Updated after our last conversation:

![screen shot 2015-01-14 at 12 34 13](https://cloud.githubusercontent.com/assets/4933/5738184/b49c0fac-9be9-11e4-8e87-176ff2393403.png)

**Comment by saleiva** [comment]
Ossom
