### ISSUE TITLE
Do not allow to call the SQL API with the api_key using HTTP, force use of https

### ISSUE THREAD

**Issue by jatorre** [CartoDB/cartodb#1721]
Right now it is possible to call the SQL API with the api_key using HTTP. That makes the key vulnerable. In order to avoid that mistake for users, when the api_key is added as a param to the call, we could ensure that it is being done through https and if it is not, just failed saying " You have to use https when using your api_key".

Just an idea to improve security @javisantana 

Also on documentation anywhere where we use the api key we should use https @andrewxhill and we should explain this somewhere on authentication on the APIs.

**Comment by andrewxhill** [comment]
four primary places for clarification in the docs

1. http://docs.cartodb.com/cartodb-editor.html#find-your-api-key
2. http://docs.cartodb.com/cartodb-platform/import-api.html#params-3
3. http://docs.cartodb.com/cartodb-platform/maps-api.html#named-maps-1
4. http://docs.cartodb.com/cartodb-platform/sql-api.html#authentication

**Comment by javisantana** [comment]
this should be enforced at platform level not application level. We talked about this several times and we always came to the same conclusion

**Comment by javisantana** [comment]
also at cartodb.js level we do not allow to use api_keys or auth tokens without https

**Comment by jatorre** [comment]
Dont get it. I am proposing that. That our platform forbids using http with the api_key. 

If not it will happen, like it happens on all our documentation, that we are doing it wrong. We can look at the logs and send an email to all people who are doing this without realizing of the security problem they have.

**Comment by javisantana** [comment]
@jatorre ok, so let's file it in the right repo
