### ISSUE TITLE
Map view / Data view filter in map editor

### ISSUE THREAD

**Issue by carlostallon** [CartoDB/cartodb#1725]

**Comment by carlostallon** [comment]
@saleiva @piensaenpixel guys can you review it:
![map editor - view as dataset](https://cloud.githubusercontent.com/assets/1712650/5719865/ce5c84c6-9b1c-11e4-880e-683c69e3c52a.png)
![map editor - view as map](https://cloud.githubusercontent.com/assets/1712650/5719866/ce5f6c4a-9b1c-11e4-94a7-e10d5824ca60.png)

**Comment by saleiva** [comment]
Uhm... could work.
Which view would be activated by default?

**Comment by carlostallon** [comment]
I'm not sure and depends on use, but IMO could be convenient the map view.

2015-01-13 12:44 GMT+01:00 saleiva <notifications@github.com>:

> Uhm... could work.
> Which view would be activated by default?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/1725#issuecomment-69732667>.
>



-- 
Carlos Tallón
Designer

**Comment by saleiva** [comment]
Why not to keep the actual view as the default one?

**Comment by carlostallon** [comment]
Perfect! I don't have good reasons to disagree ; )

2015-01-13 12:58 GMT+01:00 saleiva <notifications@github.com>:

> Why not to keep the actual view as the default one?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/1725#issuecomment-69734049>.
>



-- 
Carlos Tallón
Designer
