### ISSUE TITLE
When changing from one slide to another one, we should keep the lateral panel in the same state

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#1733]

**Comment by javierarce** [comment]
I don't understand the issue here. Right now when I click a slide the pane remains open. Maybe it was an old issue?

**Comment by javierarce** [comment]
?

**Comment by saleiva** [comment]
Close it then, and we will open a similar one if we find something weird :)

**Comment by javierarce** [comment]
:clap: ok :)
