### ISSUE TITLE
Create prototype with main workflows of the new editor

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#1735]
- [x] Create a map from scratch
- [x] Create a map with 2 layers and change style
- [x] Create a map with 2 layers and change SQL and go to the table view
- [x] Add a feature to a layer.
- [x] Publish a map.

**Comment by carlostallon** [comment]
you mean invision app right?

**Comment by saleiva** [comment]
edited :trollface:

**Comment by carlostallon** [comment]
:+1:

**Comment by carlostallon** [comment]
http://invis.io/UC1ZY1BT8
