### ISSUE TITLE
Problems in filter section when user has big figures

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#1737]
![screen shot 2015-01-13 at 16 01 40](https://cloud.githubusercontent.com/assets/132146/5722567/7e546a72-9b3d-11e4-87df-a6947ce85b16.png)

**Comment by saleiva** [comment]
Ok, fixed with a bit of refinning on the margins.
Let's put a 20px margin between elements, the line and the search part.
![screen shot 2015-01-13 at 16 05 20](https://cloud.githubusercontent.com/assets/132149/5722632/16ff8310-9b3e-11e4-8d57-141329ac3e0b.png)

**Comment by xavijam** [comment]
ok
