### ISSUE TITLE
In visualizations API, total entries is wrong when shared datasets is requested

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#1742]
Basically, when shared datasets/maps is requested in the call, total_entries in the response is wrong and the value is the same than total_shared.

Requesting normal datasets:
```
http://theteam.localhost.lan:3000/u/cartofante/api/v1/viz/?tag_name=&q=&page=1&type=table&exclude_shared=true&per_page=20&tags=&only_shared=false&locked=false&liked=false&order=updated_at
```
Response:
```
{
   total_entries: 43,
   total_shared: 1,
   ...
}
```

Requesting shared datasets:
```
http://theteam.localhost.lan:3000/u/cartofante/api/v1/viz/?tag_name=&q=&page=1&type=table&exclude_shared=false&per_page=20&tags=&only_shared=true&locked=false&liked=false&order=updated_at
```
Reponse:
```
{
   total_entries: 1,
   total_shared: 1,
   ...
}
```

![screen shot 2015-01-13 at 17 35 45](https://cloud.githubusercontent.com/assets/132146/5724269/cdab93e0-9b4a-11e4-94b8-dddca9a7f4ed.png)

**Comment by xavijam** [comment]
cc @javisantana

**Comment by Kartones** [comment]
Ahh my friend, then we need to add a new field. `total_entries` is not what you think, the total user visualizations count, it is instead **the total count of items based on specified filters**.

Any ideas for the naming? `total_entries_by_type`? `total_user_entries`?

**Comment by xavijam** [comment]
total_user_entries is ok

**Comment by Kartones** [comment]
Explanation of what this total means:
- Filter by `type` allowed
- Implicit filter by `unauthenticated` if proceeds
- Filter by `exclude_shared` always set to true

**Comment by Kartones** [comment]
All yours for the FE part

**Comment by xavijam** [comment]
Oh... one more thing, should we include locked items? I forgot to discuss that thing :S.

**Comment by xavijam** [comment]
https://github.com/CartoDB/cartodb/commit/25c3a4d049b7d40becfb455e825c92a53a6a4cec

**Comment by Kartones** [comment]
uhmm, I haven't taken it into account, no, for me a total is a total, no "hidden items". 

Are we going to have locked stuff? Because if so, we need to sit down, discuss at once all possible filters, orders, etc. and I need to properly refactor Visualization Collection class, it is becoming a small mess due to all this small but not trivial changes.

I need to know which filters locked should apply to and which ones not...

**Comment by saleiva** [comment]
my2 cents, keep it simple. No problem if locked items are part of the total.

**Comment by xavijam** [comment]
Ok, so let's keep as it is, thanks @saleiva.
