### ISSUE TITLE
Implement lock dialog

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#1744]
- [x] Possibility to lock or unlock any visualization (dataset/map).
- [x] Consider if it is loable to make it for several items at the same time.

**Comment by viddo** [comment]
@saleiva @carlostallon @piensaenpixel 
Current:
![screen shot 2015-01-14 at 17 54 01](https://cloud.githubusercontent.com/assets/978461/5743040/c9b4f200-9c16-11e4-9f66-9211a1dd9703.png)
![screen shot 2015-01-14 at 17 54 13](https://cloud.githubusercontent.com/assets/978461/5743041/c9b59ce6-9c16-11e4-9e65-a5304d8c4e1c.png)

New, proposal based on existing screens:
![screen shot 2015-01-14 at 17 56 50](https://cloud.githubusercontent.com/assets/978461/5743042/c9b94d46-9c16-11e4-8986-d9d78ee5a69a.png)
Icon is obviously missing like for the privacy dialog, care to make one?

(Btw, how about setting up [setup a design team](https://github.com/orgs/cartodb/teams) so we can easier ping you? :))

**Comment by saleiva** [comment]
With the correct margins that's perfect.
I propose to make the text shorter...

"Lock TABLE_NAME"
"By locking this dataset it will be hidden from the default list. To see your locked tables use the header menu or click in the link at the bottom of the list".

**Comment by carlostallon** [comment]
for the icon we can use the lock one

**Comment by viddo** [comment]
:+1: and :+1:  on it

**Comment by viddo** [comment]
merged #1816
