### ISSUE TITLE
Implement privacy dialog

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#1745]
- [x] Possibility to change visualization privacy (dataset/map) #1872 
- [x] Show privacy options depending of the account (take into account upgrade links and open source).  #1872
- [x] Possibility to change permissions (R/RW) to users* [(screenshot)](https://cloud.githubusercontent.com/assets/978461/5859100/14951d12-a258-11e4-86d4-26b828825045.png)
- ~~Show affected users for datasets before revoking permissions* [(screenshot)](https://cloud.githubusercontent.com/assets/978461/5741236/30b02d24-9c0a-11e4-8245-6675e8681e2f.png)~~ still must-to-have but needs more thought, postponed #1963
- ~~Possibility to search/filter users to give permissions~~* nice-to-have ATM, postponed #1923

_*organization environment_

**Comment by viddo** [comment]
@saleiva @carlostallon @piensaenpixel in the current dashboard there is a 2nd screen in the dialog, asking for confirmation of changing (removing) access of a colleague if the colleague have used the dataset in a visualization:
![screen shot 2015-01-14 at 16 03 53](https://cloud.githubusercontent.com/assets/978461/5740889/ef478b36-9c07-11e4-9abf-1c63ba3c0d9e.png)
I can't find any screen for this use-case, can you add it if missing, or point me to where it's located?

**Comment by saleiva** [comment]
It should be the same design that we are using on the delete window when not showing any affected maps.

**Comment by saleiva** [comment]
It should be the same window design we are using for the delete window

**Comment by viddo** [comment]
you mean something like this?
![screen shot 2015-01-14 at 16 26 47](https://cloud.githubusercontent.com/assets/978461/5741236/30b02d24-9c0a-11e4-8245-6675e8681e2f.png)

I guess at least the icon should be different, or we skip it completely?

**Comment by saleiva** [comment]
Exactly. That was design like that in purpose.
Adding an issue for @carlostallon and the icon :)

BTW, the (2) close to the icon is the number of selected tables so if no bulk actions it will be always be a (1)

**Comment by viddo** [comment]
![screen shot 2015-01-20 at 10 56 33](https://cloud.githubusercontent.com/assets/978461/5815292/bc854c10-a094-11e4-824c-beaa6f6858a2.png)
More questions.. on durrent dashboard the privacy is enabled/disable depending on account. How should this look/behave in the new dialog?

**Comment by xavijam** [comment]
Disabled options?

**Comment by saleiva** [comment]
Will prepare it for you in a while

**Comment by saleiva** [comment]
![dashboard - user private - datasets privacy upselling](https://cloud.githubusercontent.com/assets/132149/5815948/f9a26c62-a09a-11e4-988c-a8b0b41615d1.png)
Ready on dashboard-1.3

There should be two variations depending on the account type. 
When being in a paid account and not having Multi User we should change that CTA to 

"people icon + Looking forward to work collaboratively with your team mates? Upgrade your account"

**Comment by viddo** [comment]
Another question: _"Password protected - Set a password and share only with specific people"_, how should the workflow for setting that password be?

**Comment by xavijam** [comment]
A note about that last question: password protected is only available for maps, not datasets ;).

**Comment by viddo** [comment]
@xavijam @saleiva I've updated the description to match current state-of-things. There are 3 pendings tasks:
- [ ] Possibility to change permissions (R/RW) to users* [(screenshot)](https://cloud.githubusercontent.com/assets/978461/5859100/14951d12-a258-11e4-86d4-26b828825045.png)
- [ ] Show affected users for datasets before revoking permissions* [(screenshot)](https://cloud.githubusercontent.com/assets/978461/5741236/30b02d24-9c0a-11e4-8245-6675e8681e2f.png)
- [ ] Possibility to search/filter users to give permissions*

IMHO, of these 3 I only consider the 1st one to be a must-have feature, the other 2 I would create separate issues and file for the last sprint and only implement if/when we have time. What do you think?

**Comment by saleiva** [comment]
I'm ok with the 3rd one as a nice-to-have.
1,2 are must-have IMO. You can fuck up a map so easy without that.

**Comment by viddo** [comment]
Fair enough, I'll do 1-2 and create separate issue to deal with 3rd task later. Thx for the prompt answer!
