### ISSUE TITLE
400 error when connecting to dropbox

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#1751]
![image](https://cloud.githubusercontent.com/assets/1730320/5726040/8ad4c934-9b58-11e4-9974-be62b396cd8e.png)

URL of the error with a test account of mine: `https://www.dropbox.com/1/oauth2/authorize?client_id=trmxotzmevgt4sl&response_type=code&redirect_uri=https%3A%2F%2Foauth.cartodb.com%2F&state=tdD0t145%2BNMwUxlirMAJVw%3D%3D%7C__vmg__dropbox__`

Steps:

1. Use a new account which is not linked to Dropbox yet
2. Create new table from Dropbox
3. Click on the connect button and allow pop-up windows
-> A new pop-up appears with the previous 400 error.

(SB/4231390)

**Comment by saleiva** [comment]
Another user reported this on twitter. Prioritizing

**Comment by iriberri** [comment]
Reviewed by testing, working! :smile:
