### ISSUE TITLE
Fixed description option - not obvious what this does (no visible change when selected) 

### ISSUE THREAD

**Issue by michellechandra** [CartoDB/cartodb#1764]

**Comment by saleiva** [comment]
This is related to the fact of having a description on that visualization. Can you confirm that is working?

**Comment by michellechandra** [comment]
@seleiva - when add a description, it shows up when view in preview. but should it show up in the editor view as well?

**Comment by saleiva** [comment]
If it's activated, yeah...

**Comment by javierarce** [comment]
I'm closing this issue because we need to update the workflow of the Header overlay. We can continue the discussion here: https://github.com/CartoDB/cartodb/issues/1877
