### ISSUE TITLE
Can't edit/change text of the Fixed Title option 

### ISSUE THREAD

**Issue by michellechandra** [CartoDB/cartodb#1766]

**Comment by saleiva** [comment]
HI @michellechandra this is automatically linked to the visualization name and description. Doesn't it work like that?

**Comment by michellechandra** [comment]
@saleiva It is pulling from there, but doesn't automatically update when change the title. Still has old title. 

![screen shot 2015-01-14 at 12 37 35 pm](https://cloud.githubusercontent.com/assets/5423288/5743880/2374aca4-9bea-11e4-9d21-1ab050aeaeee.png)

**Comment by javierarce** [comment]
Closing, since we are discussing this issue here: https://github.com/CartoDB/cartodb/issues/1877
