### ISSUE TITLE
Map created with Torque and Mapnik layer but Torque is not the one on top

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#1778]
- Go to the create new visualization modal window on the dashboard.
- Add a layer with an static style (heatmap for example)
- Add a layer with a Torque style.
- click on create

Torque layer is rendering below the Mapnik Layer but the order cannot be changed.

**Comment by javisantana** [comment]
is this odyssey or general?

**Comment by saleiva** [comment]
Found when trying odyssey

**Comment by saleiva** [comment]
More about this.

- Changed the torque layer to a simple wizard, order got back to the correct one
- Torque wizard selected again - order was correct.
- Added a chapter - order was incorrect again
