### ISSUE TITLE
Time transition doesn't work

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#1779]
- Create an odyssey map.
- Add an slide and change the state of the map
- Set the transition to the 1 -> 2 to X seconds (I put 4)
- Go to the public view. Time transition never occurs.

Just in case it helps, I'm using a 2 layers visualization and changing the order of the layers from one slide to the other.

**Comment by javisantana** [comment]
I get this

**Comment by javisantana** [comment]
@saleiva do you have the visualization to check the viz.json?

**Comment by javisantana** [comment]
nevermind, looks like the transition options are removed on layer sorting

**Comment by javisantana** [comment]
steps to reproduce:
- create slide
- being in slide 2 change transition for slide 1
- change to slide 1

the transition options are reset
