### ISSUE TITLE
Change icon when auth Mailchimp Connector to a CartoDB logo

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#1782]
![twavatar_raw](https://cloud.githubusercontent.com/assets/132149/5737393/7ae5665e-9be0-11e4-8a71-c2a3aae465f2.png)

**Comment by matallo** [comment]
also, changed the name of the registered app => "CartoDB Mailchimp connector"

**Comment by saleiva** [comment]
You mean the Mailchimp import or what? I meant the Mailchimp import. In any case, @juanignaciosl can you change the icon too and the name of the app to "CartoDB"?

**Comment by juanignaciosl** [comment]
Ping @matallo

**Comment by matallo** [comment]
![screen shot 2015-01-22 at 17 35 12](https://cloud.githubusercontent.com/assets/36676/5859760/105ae84e-a25d-11e4-970a-046f45d0b57e.png)
