### ISSUE TITLE
Design an icon for datasets that don't have any geometry

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#1783]
![screen shot 2015-01-14 at 13 11 35](https://cloud.githubusercontent.com/assets/132146/5738640/e1f6cbd6-9bee-11e4-9fa6-7cde25139dba.png)

Dispatch it as you consider.

**Comment by carlostallon** [comment]
![captura de pantalla 2015-01-14 13 54 24](https://cloud.githubusercontent.com/assets/1712650/5739086/edffbde2-9bf4-11e4-9a3f-a5b6f31b9233.png)

**Comment by saleiva** [comment]
3rd one! :)

**Comment by carlostallon** [comment]
Agree :)

—
Enviado desde mi iPhone

**Comment by carlostallon** [comment]
Sent to @xavijam
