### ISSUE TITLE
Create icon for change privacy modal window affecting other users

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#1784]
Or we can use the same we have in the privacy window.

**Comment by saleiva** [comment]
#1745

**Comment by carlostallon** [comment]
![captura de pantalla 2015-01-14 17 27 53](https://cloud.githubusercontent.com/assets/1712650/5742471/b344ba72-9c12-11e4-8989-e1eb5b5087f4.png)

**Comment by carlostallon** [comment]
![captura de pantalla 2015-01-14 17 34 09](https://cloud.githubusercontent.com/assets/1712650/5742579/93f64496-9c13-11e4-941d-495e3932b7ef.png)

/ cc @viddo

**Comment by saleiva** [comment]
IMO 1st one.

**Comment by viddo** [comment]
I don't have a strong opinion on any of them ;) :shipit:

**Comment by carlostallon** [comment]
In that cae, 1st one :smile:
