### ISSUE TITLE
Design a lock table icon

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#1788]
Related with #1744

**Comment by saleiva** [comment]
Let's use the lock one.

**Comment by carlostallon** [comment]
![icon-lock 1x](https://cloud.githubusercontent.com/assets/1712650/5743264/7c6a4db8-9c18-11e4-9be4-56266b183e87.png)

/ cc @viddo

**Comment by carlostallon** [comment]
sending to front
