### ISSUE TITLE
When deletes a dataset, dependant maps preview should have a link to that map

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#1795]
![screen shot 2015-01-14 at 23 44 07](https://cloud.githubusercontent.com/assets/132146/5749243/72875744-9c47-11e4-94da-034e5ae32c66.png)

cc @viddo

**Comment by xavijam** [comment]
https://github.com/CartoDB/cartodb/pull/1796

**Comment by xavijam** [comment]
Please @viddo, take care of this issue.

**Comment by viddo** [comment]
okok

**Comment by saleiva** [comment]
Please, be sure that link is opened in a new tab

**Comment by xavijam** [comment]
I wouldn't force to do that action, user should decide...

**Comment by saleiva** [comment]
Basic users do not know how to open links in new tabs, and that would mean you have to go back to the previous screen, look for the dataset you were looking to delete, and perform the action again (after checking each visualization...)

**Comment by viddo** [comment]
I'm normally against opening links in new windows, but considering the dialogs are a kind of special case and the browser's back button would not lead to the delete dialog, I agree that opening in a new window is probably a better idea in this case.

**Comment by xavijam** [comment]
You guys decide, I'm not against anything..
