### ISSUE TITLE
Liked datasets/maps filter is not working properly

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#1801]
If says there is only one liked dataset but it keeps returning all datasets.

![screen shot 2015-01-15 at 00 37 55](https://cloud.githubusercontent.com/assets/132146/5750003/db9c2780-9c4e-11e4-8bf5-550b1e74ccd0.png)

**Comment by Kartones** [comment]
uhmm, yes, there is no filter to show "only liked visualizations", I implemented a "order by likes", so then this is a new feature.

But despite that it should show at the first page the vis with 1 like, then the ones without likes, does that work ok (screenshot shows that no)?

**Comment by xavijam** [comment]
The problem is we have a order by 'most liked': 
![screen shot 2015-01-19 at 11 43 34](https://cloud.githubusercontent.com/assets/132146/5799247/6e2dfb3a-9fd0-11e4-815f-d6a3bec3f88a.png)
And then a filter related with likes. That makes the list order a bit confused.

**Comment by Kartones** [comment]
Yep, that's what I meant, there's no filter for likes coded :D

I'll do it as soon as possible

**Comment by Kartones** [comment]
After a quick local hack, this is where it was at the import process when it tried to enqueue the ghost table register:

```
2015-01-19 16:00:21 UTC: Before persisting metadata 'leadership_in_homing_pigeon_flocks_columba_liv' data_import_id: b785636b-b9a0-449e-9d9c-25ddb5ca7682
```

**Comment by Kartones** [comment]
Pending internal code polishing, but filter working \o/

to use it, add a `only_liked=true` filter (I've maintained same signature style of `only_shared`)
