### ISSUE TITLE
Design indicator for common data datasets

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#1808]
Think on a way to differentiate these datasets when listing them on the dashboard and the lists

**Comment by carlostallon** [comment]
1st one IMO

![common data icons](https://cloud.githubusercontent.com/assets/1712650/5763181/a67e464c-9ce8-11e4-9196-e6fb533cdcd7.png)

/cc @piensaenpixel @xavijam

**Comment by xavijam** [comment]
So, that means we have to save the origin of the import.
cc @javisantana

**Comment by saleiva** [comment]
This is only for data library datasets BTW,
Not sure it works since each table can contain different type of geometry so I'd not remove the geom icon.

**Comment by carlostallon** [comment]
That's true... so I'm gonna explore a new way to show it

**Comment by carlostallon** [comment]
makes sense IMO

![datalibrary](https://cloud.githubusercontent.com/assets/1712650/5775393/a6de2c4c-9d79-11e4-86c7-d3ec5c6527b6.png)

**Comment by saleiva** [comment]
Fair enough. Remember this tables will have also the read-only indicator

**Comment by saleiva** [comment]
cc @xavijam @viddo

**Comment by viddo** [comment]
Looks great to me! The popups will be displayed on hover?

**Comment by carlostallon** [comment]
yep, only in hover : )

2015-01-16 12:46 GMT+01:00 Nicklas Gummesson <notifications@github.com>:

> Looks great to me! The popups will be displayed on hover?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/1808#issuecomment-70242886>.
>



-- 
Carlos Tallón
Designer
