### ISSUE TITLE
Refresh content view upon item change

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#1817]
E.g locking a dataset (#1744) do not refresh the list, nor the content footer (should show the "show your locked datasets"

**Comment by xavijam** [comment]
;)

**Comment by viddo** [comment]
Summary from offline discussion: it's not feasible to [bind to `change` event on collection](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/new_dashboard/content_controller_view.js#L24-L26) to do fine-grained checks for how list should be rendered, so to keep it simple the lock/unlock action should provide a mean to notify parent view (content controller) to re-fetch list (and thus implicitly re-render itself).

**Comment by xavijam** [comment]
https://github.com/CartoDB/cartodb/commit/4e91ad41d4e1a216ccec5d152e08f15393490a02
