### ISSUE TITLE
Allow searching visualization by url

### ISSUE THREAD

**Issue by jorgeas80** [CartoDB/cartodb#1819]
If you have a lot of visualizations and want to check one specific one used for a project using cartodb.js, you just have the viz.json url. I think it would be great to be able to get to that visualization from the url, introducing it in the search box, or something like that.

**Comment by saleiva** [comment]
Good idea as an advanced functionality!

**Comment by xavijam** [comment]
And by id?, shorter than url.

**Comment by saleiva** [comment]
Keep this as a nice to have

**Comment by xavijam** [comment]
Last sprint, nice to have.

**Comment by xavijam** [comment]
After one year and a half, I feel we should close it.
