### ISSUE TITLE
We should make something with the new onboarding map

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#1824]
I thought to center it to user location, using ip address. Unfortunately in the geocoding api, that functionality is not available yet. But in any case it wouldn't be a "awesomic" thing, I dunno.

- [ ] Default map in private dashboard.
- [ ] Default map in public dashboard.

**Comment by saleiva** [comment]
Yep, +1 on that. For the time being let's convert it on a huge CTA to create the first map

**Comment by xavijam** [comment]
Changes in the map for the private dashboard should be replicated in the public dashboard.
cc @viddo

**Comment by xavijam** [comment]
:(
