### ISSUE TITLE
Make "organization user" -> "Org. user" in the user dropdown

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#1837]
When name is long, it's a but ugly :)

![screen shot 2015-01-16 at 17 01 55](https://cloud.githubusercontent.com/assets/132149/5779238/75c95dca-9da1-11e4-8496-084dfd0c6750.png)

**Comment by viddo** [comment]
proposed ideas (write them here to remember 2w from now..): 
- shorten to "org user" (in this particular example)
- use short version of name (does it even exist?)
- set max width and ellipsis "too long" titles, only show full type of user on hover

**Comment by xavijam** [comment]
For the moment "shortened" organization, lump sum and academic names.
