### ISSUE TITLE
Add ability to re-order columns

### ISSUE THREAD

**Issue by mnquintana** [CartoDB/cartodb#1841]
**Expected:** I should be able to drag and move columns in Data View to rearrange the order in which they appear. There should also be menu items for columns to shift a column left or right.

**Actual**: There is no way to re-order columns.

It would be awesome if you could add this basic UX enhancement. We're likely going to have non-technical people maintaining the data for one of our maps, so the more intuitive and the easier it is to re-organize and re-present the data the better. :beers:

**Comment by saleiva** [comment]
Hi @mnquintana we expose the postgresql table structure, and try not to add more complexity layers on top of it. Although this would be interesting we are not planning on working on this in the short-term. Anyway, we will keep this in the backlog of ideas! Thanks!
