### ISSUE TITLE
Add slide controller for mobile

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#1852]

**Comment by javierarce** [comment]
Reopening to show a capture of the UI (disregard the position of the title & description, we have a bug in this branch with certain overlays)

![screen shot 2015-01-20 at 15 10 29](https://cloud.githubusercontent.com/assets/4933/5818526/834cded2-a0b6-11e4-94df-f022ba022337.png)

I removed the dots, because with visualizations with many slides it could be a problem… shall I add a counter instead? Like: 2/12 ?

**Comment by saleiva** [comment]
sounds great!  :)

**Comment by javierarce** [comment]
The problem with the header is fixed thanks to this: https://github.com/CartoDB/cartodb/issues/1887

**Comment by javierarce** [comment]
Added counter:

![screen shot 2015-01-20 at 18 39 08](https://cloud.githubusercontent.com/assets/4933/5822370/c333e8c0-a0d3-11e4-874a-544662d3e198.png)
