### ISSUE TITLE
Annotations are duplicated while playing with a vis

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#1859]
I'm trying to get the steps to reproduce it. I'll keep this issue updated.

![image](https://cloud.githubusercontent.com/assets/1730320/5802573/89b8f410-9ff6-11e4-9b04-1d507c8035c8.png)

**Comment by Xatpy** [comment]
Weird stuff with annotations. When you add several (>2), they're incorrectly realocated if you 'play' a little with them. Gif:
![bug_annotations](https://cloud.githubusercontent.com/assets/3958416/5803335/d43c14ca-9ffd-11e4-8cf9-a12816a25bda.gif)
I dont't know if it's significant, but when changing map (pan), the warning message appear:
> Mixed Content: The page at 'https://xatpyrui.cartodb-staging.com/viz/74b22bc2-9ff1-11e4-93cf-040111176f01/map' was loaded over HTTPS, but requested an insecure image 'http://3.basemaps.cartocdn.com/light_all/5/13/13.png'. This content should also be served over HTTPS.

**Comment by iriberri** [comment]
That's the basemap, @Xatpy, is what I mentioned that is also shown always in production :-)

**Comment by javisantana** [comment]
@javierarce take a look at the change i needed to do. I don't know why it was working before, this.extra is not being updated
