### ISSUE TITLE
Zooming/panning bounds doesn't get saved in viz.json

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#1862]
1. Create a new visualization (I created it from an empty table)
2. Zoom and pan around the map
3. If you refresh the site (or if you get the viz.json) the last position wasn't saved. You may need to repeat steps 2&3 because *sometimes* a new position is saved, but not always.

Attached gif: (shows that viz.json bounds are not being updated, each time I refresh the map it goes to the initial position)
![out](https://cloud.githubusercontent.com/assets/1730320/5802386/d339909c-9ff4-11e4-9546-b9b705a44b95.gif)
).

**Comment by javisantana** [comment]
it takes some time after the last movement and viz.json update. The problem is happening on zooming, not panning

**Comment by iriberri** [comment]
It's happening also with panning, but if it takes some time that's the issue I guess.

**Comment by javisantana** [comment]
it takes 1000 second but map is not being saved on zooming (so it does not depend on time)
