### ISSUE TITLE
Password workflow for change-privacy dialog

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#1873]
From [#1745](https://github.com/CartoDB/cartodb/issues/1745#issuecomment-70637761)
> ... _"Password protected - Set a password and share only with specific people"_, how should the workflow for setting that password be?

**Comment by saleiva** [comment]
![dashboard - user private - datasets password](https://cloud.githubusercontent.com/assets/132149/5823545/e2a58100-a0dd-11e4-915b-3a3873d44922.png)

Here we go.

**Comment by viddo** [comment]
Are there any limitations to the password (min/max length or such) that I need to be aware of?

**Comment by viddo** [comment]
Further, I assume:
- password field only appear if selected password option
- save settings should be disabled until at least one character is written in the password field

**Comment by saleiva** [comment]
Exactly.
When the pwd field is empty we will need a placeholder.

No limitations on the password

**Comment by viddo** [comment]
Perfect, thanks
