### ISSUE TITLE
Some overlays (like legends) are appearing in the public map list of a user

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#1875]

**Comment by javisantana** [comment]
arg: https://github.com/CartoDB/cartodb.js/commit/2c03910cfa9768bdf7df72ac07754ddca6b3dbc5

**Comment by javierarce** [comment]
Ha, we accidentally removed the legends: https://github.com/CartoDB/cartodb.js/commit/c76820c1c50f39250e70da1fd8bf047b9bf2e06b. They're back.

**Comment by javierarce** [comment]
We are doing something wrong: https://github.com/CartoDB/cartodb/issues/1911. I'll have a look tomorrow.
