### ISSUE TITLE
Using the mouse to view a slide doesn't store the position

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#1879]
#### How to reproduce the problem: 

1. Create a Odyssey visualization with at least 5 slides.
2. Open the public visualization.
3. Click on the fourth dot in the navigation.
4. Click the right key on the keyboard.

#### What should happen?

You should see the fifth slide

#### What actually happens

You see the second slide.

/cc @javisantana

**Comment by javisantana** [comment]
fixed in cartodb.js
