### ISSUE TITLE
Design error when input is not valid for new import panel

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#1880]
In the current one:

![screen shot 2015-01-20 at 14 40 30](https://cloud.githubusercontent.com/assets/132146/5818736/28d69112-a0b8-11e4-8c20-caa11b01cd46.png)

**Comment by Xatpy** [comment]
sorry @xavijam , but I didn't understand the issue. What should be the correct design?

Also, if you enter an URL (starting with: `http:`) it works (synced tables)

**Comment by xavijam** [comment]
lol, this is for @saleiva, not for yours... sorry mate!
:D

**Comment by saleiva** [comment]
There we go.

Please not that the desired behaviour is that when typing the URL we hide with a fade out the bottom part that was about selecting a file. To see it back, user should clear the content of the URL input.

![create - new dataset - data file url error](https://cloud.githubusercontent.com/assets/132149/5820200/95ddd008-a0c3-11e4-8e1f-33befa0f46e6.png)

**Comment by saleiva** [comment]
Sorry, correct version now uploaded

![create - new dataset - data file url error](https://cloud.githubusercontent.com/assets/132149/5820262/0597842a-a0c4-11e4-8fc1-2d766a9c8c63.png)

**Comment by xavijam** [comment]
ok deal, closing this.
