### ISSUE TITLE
Make sure mixpanel and trackJs works for dev/staging env

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#1892]
Related to #1890 we need a long-term solution for the problem with mixpanel and trackJs not being used for neither dev or staging environments, it has happened more than once that something (luckily not any important pages) fail due to these code paths are only reached in production.

Proposed solutions:
- Enable mixpanel and trackJs for staging at least, is possible to filter out dev/staging env data by some additional metadata?
- Unit test entry point, to cover cases of trackJs and Mixpanel are present.

Other ideas?

**Comment by viddo** [comment]
ping @CartoDB/frontend feedback?

**Comment by matallo** [comment]
I don't know if I understood properly but the strategy i'm following in other projects is

```
<% if CartoDB.config[:trackjs] && CartodbCentral.config[:trackjs][:token].present? %>
<!-- track.js code -->
<% end %>
```

thus is sane to have/not to have those

if you mean code breaks because a `mixpanel.function();` and the mixpanel config doesn't exist, maybe add a config js view with a:

```
var mixpanelPresent = <% if CartoDB.config[:trackjs] && CartodbCentral.config[:trackjs][:token].present? %>
```

and then `mixpanelPresent && mixpanel.function();`

does this makes sense?

**Comment by viddo** [comment]
yes, but that was not really the issue. it's related though :)

the issue is that only production env load hit some [code paths](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/new_dashboard/entry.js#L44-L48). when there are faulty code inside those if-checks and since we never reach that code in dev or staging environments they don't show up until we do a release to production.
