### ISSUE TITLE
Excel import:  undefined method `close' for 0:Fixnum

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#1896]
From error id: `59593928-8cd6-48ab-b55a-fe5490f51e43`

@juanignaciosl  says:

````
Line:

%x[in2csv #{filepath} | #{newline_remover_path} > #{converted_filepath}]

in file ./services/importer/lib/importer/excel2csv.rb

````

P.S.: I have the source file if you need it.

**Comment by rafatower** [comment]
@juanignaciosl sorry, do you have a link to the error? what's that id?

**Comment by rafatower** [comment]
PS: If that's local you have to install csvkit as stated in https://github.com/CartoDB/cartodb/blob/master/NEWS.md#380-2015-01-xx

**Comment by iriberri** [comment]
It's production, the error ID is an import error id

**Comment by rafatower** [comment]
I don't see it on any of the juanignacios* users :(

**Comment by iriberri** [comment]
Sorry for the badly written issue then:

We had this error in support. I sent it to Nacho, which told me what is said in the block code, and that this was something you changed recently.

:smile:

**Comment by rafatower** [comment]
Actually this is the trace:
```
2015-01-21 11:04:01 UTC: NoMethodError: undefined method `close' for 0:Fixnum
2015-01-21 11:04:01 UTC: ----------------------------------------------------
2015-01-21 11:04:01 UTC: ["/usr/lib/ruby/1.9.1/csv.rb:1381:in `ensure in parse'"
 "/usr/lib/ruby/1.9.1/csv.rb:1381:in `parse'"
 "/home/ubuntu/www/production.cartodb.com/releases/20150121103732/services/importer/lib/importer/csv_normalizer.rb:178:in `single_column?'"
 "/home/ubuntu/www/production.cartodb.com/releases/20150121103732/services/importer/lib/importer/csv_normalizer.rb:174:in `needs_normalization?'"
 "/home/ubuntu/www/production.cartodb.com/releases/20150121103732/services/importer/lib/importer/csv_normalizer.rb:47:in `run'"
 "/home/ubuntu/www/production.cartodb.com/releases/20150121103732/services/importer/lib/importer/excel2csv.rb:31:in `run'"
```
and the related code:
```Ruby
# File /usr/lib/ruby/1.9.1/csv.rb
1375   def self.parse(*args, &block)
1376     csv = new(*args)
1377     if block.nil?  # slurp contents, if no block is given
1378       begin
1379         csv.read
1380       ensure
1381         csv.close
1382       end
1383     else           # or pass each row to a provided block
1384       csv.each(&block)
1385     end
1386   end
```
but this happened today before we upgraded to ruby `1.9.3p547` with its core library as well.

**Comment by juanignaciosl** [comment]
@rafatower I meant [this change](https://github.com/CartoDB/cartodb/commit/8a6b87202fd6d85490b27f53bd50d5b83c115b8a). `csv.close` fails because csv file is empty. I've reproduced it locally, after installing all the needed things to make it work (I also had to upgrade xml parser).

**Comment by rafatower** [comment]
Yeah, I managed to reproduce myself locally too. Thanks and sorry for the confusion. I can take it over from here.

**Comment by rafatower** [comment]
```
$ in2csv input.xlsx
local variable 'row' referenced before assignment
$ echo $?
1
```

**Comment by rafatower** [comment]
```
$ in2csv Islington_North.xlsx 
local variable 'row' referenced before assignment
developer@cartodbv3:~/src$ echo $?
1
```

**Comment by rafatower** [comment]
This is the bug in [openpyxl](https://bitbucket.org/openpyxl/openpyxl/issue/401/unboundlocalerror-upon-empty-row-in-an) and the workaround for the moment is to downgrade to v2.1.3:
```
$ sudo -H pip install openpyxl==2.1.3
$ in2csv input.xlsx > /tmp/out.csv && echo "OK"
OK
```

**Comment by rafatower** [comment]
Fixed. Changes to be in prod around 6:30 PM MAD time.

**Comment by iriberri** [comment]
Great! Thanks :smile:

**Comment by iriberri** [comment]
This seems to be happening again. 

Import error in rollbar: https://rollbar.com/vizzuality/CartoDB/items/19/occurrences/5916939892/

No traces there besides the "Import error" item.

Files are these ones ( XLS from US Census, not private data): 
https://dl.dropboxusercontent.com/u/2879308/UScensus_county_Percent_Hispanic_or_Latino__of_any_race_%20%281%29.xls
https://dl.dropboxusercontent.com/u/2879308/UScensus_county_Percent_Some_Other_Race%20%281%29.xls

By inspecting the XLS, they seem fine: 3 columns with basic data, no merged columns (although the import crashes in "normalize single column"):

````
 23:32:43 UTC: Orig file: /tmp/imports/20150617-3733-l31zpm/uscensus_county_percent_some_other_race.xls\nTemp destination: /tmp/imports/20150617-3733-l31zpm/uscensus_county_percent_some_other_race.csv\n2015-06-17 23:32:43 UTC: Errored importing data from /tmp/imports/20150617-3733-l31zpm/uscensus_county_percent_some_other_race.xls:\n2015-06-17 23:32:43 UTC: NoMethodError: undefined method `close' for 0:Fixnum\n2015-06-17 23:32:43 UTC: ----------------------------------------------------\n2015-06-17 23:32:43 UTC: [\"/usr/lib/ruby/1.9.1/csv.rb:1381:in `ensure in parse'\", \"/usr/lib/ruby/1.9.1/csv.rb:1381:in `parse'\", \"/home/ubuntu/www/production.cartodb.com/releases/20150617144303/services/importer/lib/importer/csv_normalizer.rb:178:in `single_column?'\", \"/home/ubuntu/www/production.cartodb.com/releases/20150617144303/services/importer/lib/importer/csv_normalizer.rb:174:in `needs_normalization?'\", \"/home/ubuntu/www/production.cartodb.com/releases/20150617144303/services/importer/lib/importer/csv_normalizer.rb:47:in `run'\", \"/home/ubuntu/www/production.cartodb.com/releases/20150617144303/services/importer/lib/importer/excel2csv.rb:34:in `run'\", \"/home/ubuntu/www/production.cartodb.com/releases/20150617144303/services/importer/lib/importer/loader.rb:117:in `block (2 levels) in normalize'\", \"/home/ubuntu/www/production.cartodb.com/releases/20150617144303/services/importer/lib/importer/importer_stats.rb:33:in `block in timing'
````

**Comment by rafatower** [comment]
```
# in2csv UScensus_county_Percent_Hispanic_or_Latino__of_any_race_\ \(1\).xls 
Unsupported format, or corrupt file: BOF not workbook/worksheet: op=0x0009 vers=0x0000 strm=0x1000 build=0 year=0 -> BIFF21
# echo $?
1
```

**Comment by rafatower** [comment]
I tried upgrading some of the underlying libraries but it didn't fix the problem.

I opened the file and saved it again as xls with libreoffice, then the import worked. Chances are the file is actually corrupted. Where's the original file, @iriberri? I'd like to check the original one.
