### ISSUE TITLE
Ways to improve complex workflows: Keyboard shortcuts

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#1897]

**Comment by saleiva** [comment]
![Uploading Map editor - Shortcuts.png . . .]()
![screen shot 2015-01-21 at 14 17 15](https://cloud.githubusercontent.com/assets/132149/5836633/45edac5c-a178-11e4-914f-0c2e9573a353.png)

**Comment by saleiva** [comment]
![map editor - shortcuts](https://cloud.githubusercontent.com/assets/132149/5836654/6e36e6e2-a178-11e4-86df-2f4bf9deee67.png)

**Comment by saleiva** [comment]
Hey @jatorre @javisantana @andrewxhill @miguelarias based on yesterday's feedback session, I'm leaving this open for a while to hear your impressions.

cc/ @carlostallon @piensaenpixel

**Comment by carlostallon** [comment]
<3

**Comment by saleiva** [comment]
![map editor - shortcuts](https://cloud.githubusercontent.com/assets/132149/5838775/ed22eeae-a189-11e4-9c80-e38f140a3b9f.png)

Changing to black since contextual help will be on black panels.

**Comment by andrewxhill** [comment]
wow, pretty nice imo

On Wed, Jan 21, 2015 at 12:41 PM, saleiva <notifications@github.com> wrote:

> Closed #1897 <https://github.com/CartoDB/cartodb/issues/1897>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/1897#event-222478967>.
>



-- 

andrewxhill <http://twitter.com/andrewxhill>
http://cartodb.com
