### ISSUE TITLE
Indicate that the slide are triggering by time

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#1907]

**Comment by javierarce** [comment]
Desktop: 

![loading](https://cloud.githubusercontent.com/assets/4933/5841593/6d62687e-a19e-11e4-804b-6a1fcde934ce.gif)

Mobile: 

![loading2](https://cloud.githubusercontent.com/assets/4933/5841619/a4a1340a-a19e-11e4-904c-301bdb826819.gif)


/cc @saleiva @javisantana

**Comment by saleiva** [comment]
Fair enough
