### ISSUE TITLE
infowindow header titles show up even when null values appear

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#1913]
We should make it an option, or better, just the default, to not include headers for rows where the value is null or an empty string,

![screen shot 2015-01-21 at 3 01 42 pm](https://cloud.githubusercontent.com/assets/370259/5843967/7c5939c2-a17e-11e4-8a8d-ef84d01a5fce.png)

**Comment by cshirky** [comment]
I'm a user, not committing, but I'll suggest a default to trim trailing whitespace as well, as in https://github.com/CartoDB/cartodb/issues/1881

**Comment by javisantana** [comment]
it was showing null

**Comment by alonsogarciapablo** [comment]
This is the same as #2420. It has already been fixed. We don't display headers for fields which are empty or null, and we now display "No data available" if all fields are empty.

![captura de pantalla 2015-03-23 a las 11 05 00](https://cloud.githubusercontent.com/assets/390398/6777739/bb255098-d14c-11e4-90ed-46f1da469902.png)
