### ISSUE TITLE
Olark integration is not working with Odyssey merge

### ISSUE THREAD

**Issue by Xatpy** [CartoDB/cartodb#1921]
Since the Odyssey merge was done and released, the Olark support integration (for example in editor or documentation) is not working.

**Comment by javisantana** [comment]
olark is there, the code is not changed, looks like there is some problem with the css:

![screen shot 2015-01-23 at 10 03 54 am](https://cloud.githubusercontent.com/assets/30147/5872077/364a46e6-a2e7-11e4-927a-a62a3a5cef5d.png)

I'd send a mail to their support

**Comment by javisantana** [comment]
also: https://www.olark.com/help/stuck, specially "Accidentally having your Olark box hide when you're offline"

**Comment by Xatpy** [comment]
I close this issue because it's working:
![screen shot 2015-01-26 at 16 27 23](https://cloud.githubusercontent.com/assets/3958416/5902154/8725e00a-a578-11e4-9e24-afb3e78b315e.png)

Dunno if the problem was that there wasn't anybody connected in that moment; and because of that there were olark windows.
