### ISSUE TITLE
Add layer selector shows only 300 tables

### ISSUE THREAD

**Issue by Kartones** [CartoDB/cartodb#1922]
/cc @saleiva

**Comment by Kartones** [comment]
Uhm, I need you @saleiva to provide me with steps to reproduce, as this is already fixed:

Sample call from dev environment that populates the layer selector modal:

```
api/v1/viz/?tag_name=&q=&page=1&type=table&exclude_shared=false&per_page=100000&o%5Bupdated_at%5D=desc&exclude_raster=true
```

As you can see there's already a `per_page=100000`

**Comment by saleiva** [comment]
Enter in my account (guess the password).
go to any visualization and try to add any of the latest imported tables

**Comment by Kartones** [comment]
Ahh, nice, that seems to be a different call:
```
api/v1/viz/?tag_name=&q=&page=1&type=table&exclude_shared=false&per_page=300&table_data=false&o%5Bupdated_at%5D=desc&exclude_raster=true
```
`per_page=300` Offending code. Assign it to somebody from FE please

**Comment by Kartones** [comment]
Nah, I'm fixing it, trivial to bother anyone else

**Comment by saleiva** [comment]
Shit, deploy was not done! :(

**Comment by xavijam** [comment]
My bad, deploying...


On 22 Jan 2015 at 20:57:27, saleiva (notifications@github.com) wrote:

Shit, deploy was not done! :(

**Comment by Kartones** [comment]
I've just deployed ;)

**Comment by xavijam** [comment]
thanks buddy

**Comment by Kartones** [comment]
`per_page=100000`

Working!
