### ISSUE TITLE
Add Heatmap to the list of wizards

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#1928]
Thumnail designed at wizardsTumbnails.fw.png.

**Comment by fdansv** [comment]
Wizard content (in order):

* Marker size
* Threshold (```marker-fill-opacity```)
* Animated? If true:
>> * Duration
>> * Steps
>> * Trails
>> * Resolution

New position of Torque, Torque Category and Heatmap wizard buttons, after Bubble

**Comment by fdansv** [comment]
The wizard has now been added with a feature flag
