### ISSUE TITLE
[DESIGN] Inconsistencies before and after visualizing

### ISSUE THREAD

**Issue by cshirky** [CartoDB/cartodb#1929]
In Map view, before selecting Visualize, there is a menu in the upper-left corner that says Options, and basemap selection is a dropdown on the left, above the map.

![screen shot 2015-01-22 at 8 52 59 pm](https://cloud.githubusercontent.com/assets/226500/5869443/1ea2f30a-a2f4-11e4-9bac-2ddd9576cc7d.png)

Clicking Visualize (which is itself confusing -- from the users' perspective, Map view is already a visualization) causes the following changes in the interface:

![screen shot 2015-01-22 at 8 53 30 pm](https://cloud.githubusercontent.com/assets/226500/5869447/4dd99d04-a2f4-11e4-946e-1f4824ae3160.png)

1. A second, competing menu also called Options is added to the lower-left corner of the map. (Maybe "Map Options"?)
2. The content of the upper-right options has changed completely, from table options to visualization options, with no indication to the user that that tool now holds completely different functions. (Maybe switch the labels when the content switches?)
3. Basemap location moves from above the map to the bottom of it, and has switched from a dropdown to a popup. (Maybe always make it the popup, and recover the screen real estate above for the map?)
4. Add Element and Configure Canvas are given a considerable amount of space, far more than more important elements, like any of the Map view editing options on the right.  (Maybe move Add Element up to the main nav above, next to the other Visualization options on the right?)
5. Configure Canvas is particularly confusing, since what the user can actually see is already called Map view _and_ Visualization. There is no other visible use of the word Canvas. Canvas also has only two options. (Maybe turn it into a toggle next to Add Element, or folded into the lower-left options?)

**Comment by saleiva** [comment]
Hi @cshirky totally. The actual design is inherited from the old designs and there are several problems like this one. Good news are that we are working on a completely new version of the editor which tries to fix all this stuff. Would you be interested on a quick session for showing them to you and hear your feedback?

**Comment by cshirky** [comment]
I would be delighted.

I taught a class with Carto this January and love it, and we're showing it
to a bunch of students this spring, so I'm interested in the next
interface, and would love to help any way I can.

-c

**Comment by saleiva** [comment]
could you send me an email (saleiva@cartodb.com) to arrange it? It would be awesome!
