### ISSUE TITLE
Only locked visualizations → inaccessible

### ISSUE THREAD

**Issue by peterdesmet** [CartoDB/cartodb#1932]
When a user has only locked visualizations (either by locking the last unlocked one or by removing the last unlocked one), the link to access those (which normally appears at the bottom) disappears. Instead instructions are shown regarding how to create a visualization. Currently, the only way to get access again, is by creating a new unlocked visualization.

![screen shot 2015-01-23 at 11 06 56](https://cloud.githubusercontent.com/assets/600993/5872870/6a67a802-a2f0-11e4-97aa-be503e61749a.png)

I haven't tested, but the same problem might occur for tables.

**Comment by saleiva** [comment]
Hi @peterdesmet yep, this is a known bug.
(Closing as duplicated)

Thanks a lot for reporting!
We are looking fwd to see more maps from you!
