### ISSUE TITLE
Debug why commas are not being added sometimes between geocoding selections.

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#1935]
Whole history here: https://github.com/CartoDB/cartodb/issues/1462#issuecomment-71174736

**Comment by juanignaciosl** [comment]
I'm not sure where does that log comes from, but I've debugged the sent query and comma is there both choosing the country and setting it by hand, so I would close this.

**Comment by iriberri** [comment]
The log comes from our metadata table:

cartodb_production=# select users.username,geocodings.kind,geocodings.processable_rows,geocodings.formatter,geocodings.country_code,geocodings.created_at from users, geocodings where user_id=users.id and username='ESTE_USER';
 username |      kind       | processable_rows |            formatter             | country_code |          created_at
----------+-----------------+------------------+----------------------------------+--------------+-------------------------------
 ESTE_USER | namedplace      |              415 | {job_city}                       | 'canada'     | 2014-12-01 22:33:29.426628+00
 ESTE_USER | high-resolution |                0 | {job_address}, alberta, canada   |              | 2014-12-01 22:55:09.258996+00
 ESTE_USER | high-resolution |              152 | {job_address} {job_city}, canada |              | 2014-12-01 22:37:56.992076+00
 ESTE_USER | high-resolution |                0 | {job_address}, canada            |              | 2014-12-01 22:51:10.073905+00
 ESTE_USER | high-resolution |                1 | {job_address}, canada            |              | 2014-12-01 22:43:40.930174+00
 ESTE_USER | namedplace      |                0 | {job_city}                       | 'canada'     | 2014-12-01 22:50:48.128213+00
 ESTE_USER | high-resolution |                0 | {job_city}                       |              | 2014-12-01 22:55:25.74291+00
 ESTE_USER | high-resolution |                2 | {job_address} {job_city}         |              | 2014-12-01 22:56:44.140714+00
 ESTE_USER | high-resolution |              415 | {job_address} {job_city}, canada |              | 2014-12-01 22:59:46.633214+00
 ESTE_USER | high-resolution |              223 | {job_address} {job_city}, Canada |              | 2014-12-02 14:15:04.777442+00
 ESTE_USER | high-resolution |                4 | {job_address} {job_city}         |              | 2014-12-03 15:30:58.699777+00
 ESTE_USER | high-resolution |                1 | {job_address} {job_city}, Canada |              | 2014-12-03 15:22:42.673102+00
 ESTE_USER | high-resolution |               27 | {job_address} {job_city}         |              | 2014-12-03 15:33:31.902506+00
 ESTE_USER | high-resolution |                3 | {job_address} {job_city}         |              | 2014-12-03 15:25:58.32669+00
 ESTE_USER | high-resolution |                2 | {job_address} {job_city}         |              | 2014-12-03 15:34:26.697286+00
 ESTE_USER | high-resolution |                1 | {job_address} {job_city}         |              | 2014-12-03 15:37:30.401801+00
(16 rows)

My attempt:

 iriberri | high-resolution |                6 | {job_address}, {job_city}, canada                                                     |              | 2014-12-30 15:04:48.174391+00

**Comment by juanignaciosl** [comment]
It's logged without commas, because it's the 'formatter' front sends, but it's sent with commas to the API, so it's fine.

**Comment by iriberri** [comment]
What is what we store in geocoding-cache? What we send? What we receive back from the service?

**Comment by juanignaciosl** [comment]
Gotcha! I've found out where is the missing comma. If you geocode with the "additional data" field instead of using the right one, you get your missing comma formatter:
` {street} {province}, {country}`
![screen shot 2015-01-23 at 15 05 28](https://cloud.githubusercontent.com/assets/932968/5875814/607b1060-a311-11e4-9e35-06c5a0cc0dcb.png)

So I think this also proofs that user used the wrong column :-)
