### ISSUE TITLE
CartoDB editor: "account settings" not working in open-source version

### ISSUE THREAD

**Issue by santisaez** [CartoDB/cartodb#1956]
I have just make a fresh install of CartoDB open-source:

1. Go to "user" => "organization"
2. Click on "account settings", it's a link to `http://$domain/account/$user`
3. You will get a 404

**Comment by saleiva** [comment]
All related with the SaaS part I think that shoulnd't be visible... cc/ @javisantana

**Comment by Xatpy** [comment]
@santisaez @javisantana What should be the correct method to configure this setting? I mean: in the app_config.yml?

**Comment by javisantana** [comment]
I think that will be enabled in case we set the url for central in cartodb, disabled otherwise

**Comment by javisantana** [comment]
I  guess ``account_host`` is the one we should take into account

**Comment by Xatpy** [comment]
Closing with this [PR#2646](https://github.com/CartoDB/cartodb/pull/2646) -> Merging on next 9thMonday
