### ISSUE TITLE
CartoDB editor: "buy more seats" not working in open-source edition

### ISSUE THREAD

**Issue by santisaez** [CartoDB/cartodb#1957]
I have just make a fresh install of CartoDB open-source:

1. Go to "user" => "organization"
2. Click on "buy more seats" - it's a link to `http://$domain/account/$user/upgrade`
3. You should get a 404

**Comment by Xatpy** [comment]
Closing with this [PR#2646](https://github.com/CartoDB/cartodb/pull/2646) -> Merging on next 9thMonday
