### ISSUE TITLE
Phone numbers not correctly imported with csv type guessing

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#1961]
Phone numbers of the form +34123456789 do not get correctly imported because of an integer overflow. It seems like during guessing the internal representation of ogr2ogr is `int32` which is not enough.

Possible solutions:
- Assign `string` type for columns with leading zeroes or plus signs
- Increase internal representation of integers values to `int64`

cc/ @javisantana

**Comment by rafatower** [comment]
I personally prefer the first option. That said, they are not mutually exclusive.

**Comment by javisantana** [comment]
the internal representation is a major change in ogr2ogr so I would discard that. The first one is the best one I think

**Comment by d4weed** [comment]
Yeah, the main issue here (unless you've spotted something else) is treating zipcodes and phone numbers as integers, something that is by no means needed, so first option looks like the best. Would this also be an issue with unix timestamps though?

**Comment by rafatower** [comment]
> unix timestamps

thanks for pointing out.

I'll take a quick look at the internal representation, because it might be a quick win and both options are not mutually exclusive.

**Comment by javisantana** [comment]
we have the option of keeping the original columns as is so the user can remove them if the conversion was good. 

This is a guess and it can fail, or either we give the option for disabling it or we give the user a way to fix when guessing fails. We are not going to find the perfect thing for guessing

**Comment by rafatower** [comment]
To some extend, related to https://github.com/CartoDB/cartodb/issues/1966

In some sample input the phone numbers are quoted. I believe excel quotes strings when there's ambiguity (or when you prepend a single quote in the cell content to avoid formatting as number, e.g: `'+34...`)

**Comment by rafatower** [comment]
Regarding other options:

- I checked the `AUTODETECT_WIDTH` of ogr2ogr but it doesn't work as I expected (see http://www.gdal.org/drv_csv.html). I think it is a bug in gdal.
- I think the type of integers when importing could be changed around these lines: [ogrcsvlayer.cpp#L495-L499](https://github.com/OSGeo/gdal/blob/bbfa5b78bbb04ae7adbeffdb940fa5cca343d3a6/gdal/ogr/ogrsf_frmts/csv/ogrcsvlayer.cpp#L495-L499)
- Disabling the type guessing is possible through the API but not implemented in the UI. There's this ticket https://github.com/CartoDB/cartodb/issues/1148 for that, just a matter of prioritizing I guess.
- Keeping the original columns (`KEEP_SOURCE_COLUMNS` param) would require a bit of UI as well. But also could have other negative effects: table size, content guessing and I don't know what else.

**Comment by rafatower** [comment]
@d4weed please check that it works now well enough for you.

**Comment by d4weed** [comment]
Working perfectly, thanks guys!
