### ISSUE TITLE
Design feedback of affected users/maps when changing permissions

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#1962]
Design the feedback for "show affected users for datasets before actually revoking permissions" (organization use-case)

**Comment by saleiva** [comment]
Ok. Done!

Changing the text in advance will help also (like for kartones).
When deactivating the text should change and turn red, and the icon around the avatar should appear.

![dashboard - user private - datasets privacy share friends list](https://cloud.githubusercontent.com/assets/132149/5939989/16276f90-a708-11e4-8ca3-5250aa1d1534.png)

**Comment by viddo** [comment]
thx, will be solved in #1963 so closing this one
