### ISSUE TITLE
add oembed support for embeds

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#1965]
Basically it requires a endpoint like:

http://cartodb.com/api/v1/oembed 

and you need to call it like:

http://cartodb.com/api/v1/oembed?url=https://rambo-test.cartodb.com/viz/7017bd0a-a22d-11e4-ba88-0e018d66dc29/

that returns a json like:

{
type: 'rich',
version: '1.0',
title: 'visualization title',
html: "<iframe width='100%' height='520' frameborder='0' src='http://rambo-test.cartodb.com/viz/7017bd0a-a22d-11e4-ba88-0e018d66dc29/embed_map' allowfullscreen webkitallowfullscreen mozallowfullscreen oallowfullscreen msallowfullscreen></iframe>"
width: 800,
height: 520
}

**Comment by javisantana** [comment]
branch is 1965-oembed

**Comment by zenitraM** [comment]
huh, it seems waffle.io keeps using me to assign/deassign tickets

**Comment by danicarrion** [comment]
what are the restrictions for the url parameter (like, do we have to check the domain name? or any other considerations)?

**Comment by javisantana** [comment]
I'd say the url should match the complete domain + it's a viz url. In other words, 

http://javi.cartodb.com/api/v1/oembed?url=http://dani.cartodb.com/....

should not be allowed

**Comment by danicarrion** [comment]
also, calls to http://javi.cartodb.com/api/v1/oembed are public, aren't they?

**Comment by danicarrion** [comment]
i answer myself: yes

**Comment by danicarrion** [comment]
https://github.com/CartoDB/cartodb/pull/2006 @juanignaciosl
