### ISSUE TITLE
Adding mapbox basemap by map.id is not working any more

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#1969]
It doesn't work by URL neither...

I guess we need better tests here

cc/ @javisantana

**Comment by javierarce** [comment]
I think it's actually working, the problem seems that now Mapbox basemaps URLs require the access_token. Can you confirm it, @saleiva?

In that case I'll update the docs and have a look to the tests.

**Comment by saleiva** [comment]
Nope, it's not working. By id it doesn't work, and the URLs is with the URL they provide in the mapbox editor. Have you tried that?

**Comment by iriberri** [comment]
I've also been trying ID's and URLs with token and it's no working neither. We've had some issues about this in SB these last days.

**Comment by saleiva** [comment]
We should try to hotfix this, it shouldn't be that hard, right?

**Comment by javierarce** [comment]
We won't be able to support the mapbox id: they now require to provide an accessToken: https://www.mapbox.com/mapbox.js/api/v2.1.5/

**Comment by saleiva** [comment]
Ok, let's do 2, and ask for the mapbox id on the dialog.

**Comment by javierarce** [comment]
I've just submitted a PR. Here's the new dialog and the error message:

![screen shot 2015-02-11 at 18 56 59](https://cloud.githubusercontent.com/assets/4933/6152748/d62cfcde-b21f-11e4-99ef-4a8772472e43.png)

![screen shot 2015-02-11 at 18 57 08](https://cloud.githubusercontent.com/assets/4933/6152749/d64544a6-b21f-11e4-96c4-be0e435420e5.png)

**Comment by bolson7117** [comment]
I'm I missing something here, I see that its working but will the data on Mapbox come across as well to CartoDB. Forgive me I'm new to this ;-)
