### ISSUE TITLE
Image infowindow is buggy

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#1970]
When having an image selected, and changing one of the columns it says that the image URL is not valid, but it is.

**Comment by xavijam** [comment]
Really weird things happen when a new column is added to the layer and you play enabling and disabling the field within infowindow.

**Comment by alonsogarciapablo** [comment]
Ok, I've been able to reproduce the problem (good start):

![crazy_image_infowindow](https://cloud.githubusercontent.com/assets/390398/6827813/146f7336-d30a-11e4-8c06-f904ceeb9508.gif)
