### ISSUE TITLE
Being a org user, all privacy options are available, so upgrade message shouldn't be displayed

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#1972]
![screen shot 2015-01-28 at 15 57 08](https://cloud.githubusercontent.com/assets/132146/5939707/61f6e006-a706-11e4-9ea0-a3b129b9b29a.png)

**Comment by xavijam** [comment]
Not sure if it is a design or implementation problem, but for me, that message is not correct.

**Comment by viddo** [comment]
Yeah, the text should be "Team work is always better." and not that one obviously.
