### ISSUE TITLE
Image items in shared visualizations can only be displayed by owner, not others

### ISSUE THREAD

**Issue by Xatpy** [CartoDB/cartodb#1979]
Only the owner of a visualization can display images. The others can't see the image. 
It has been reported from support. Also, I've tested it. 
Example:
I'm the owner of the visualization:
![screen shot 2015-01-28 at 17 56 31](https://cloud.githubusercontent.com/assets/3958416/5942721/ae61928e-a719-11e4-8fc4-cc6498205c4a.png)
I share the visu with xavijam, and that's what he can see:
![screen_shot_2015-01-28_at_17 55 03_1024](https://cloud.githubusercontent.com/assets/3958416/5942765/f0170470-a719-11e4-960c-58f7c8f77bda.png)
The privacy is only with link.

**Comment by iriberri** [comment]
Related (or even the same): #2020
