### ISSUE TITLE
Design case when tweets import has finished successfully

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#1983]
A dialog showing the used tweets, georeferenced tweets, etc.

**Comment by saleiva** [comment]
![create - new dataset - twitter result charges](https://cloud.githubusercontent.com/assets/132149/5959599/d0f7bc0e-a7cf-11e4-9228-3bb383cd8ef2.jpg)
![create - new dataset - twitter result no charges](https://cloud.githubusercontent.com/assets/132149/5959598/d0f57e94-a7cf-11e4-9b9a-f792cbea83e7.jpg)

cc/ @carlostallon
