### ISSUE TITLE
Possible improvements - Torque heatmap -

### ISSUE THREAD

**Issue by ekonlab** [CartoDB/cartodb#1988]
As per my experience with heatmaps. I would suggest to include the next features as optional in the heatmap:

radius - radius of each "point" of the heatmap, 25 by default (https://github.com/Leaflet/Leaflet.heat)
blur - amount of blur, 15 by default (https://github.com/Leaflet/Leaflet.heat)
color scales: https://github.com/mbostock/d3/wiki/Ordinal-Scales & https://github.com/mbostock/d3/wiki/Quantitative-Scales
alpha

**Comment by fdansv** [comment]
Thanks, all of these features are now either implemented or ticketed, with the exception of blur.

Color scales: https://github.com/CartoDB/cartodb/issues/2166
Radius: #2001 

For more suggestions or features, let's open a ticket for each one :)
