### ISSUE TITLE
Georeference by addres with synced tables ??

### ISSUE THREAD

**Issue by Xatpy** [CartoDB/cartodb#1992]
Nowadays with sync tables, we support the following georefence systems ([reference](https://github.com/CartoDB/cartodb/blob/master/services/importer/lib/importer/georeferencer.rb#L45))

- create_the_geom_from_geometry_column  ||
- create_the_geom_from_latlon           ||
- create_the_geom_from_country_guessing ||
- create_the_geom_from_ip_guessing      ||
- create_the_geom_in(table_name)

But from support (/4351050), we've received if it could be possible to georeference by address in a sync table (because the UI option were disabled)

What do you think?

cc @saleiva @juanignaciosl

**Comment by saleiva** [comment]
It has been a common ask for a long time. It needs some analysis in order to know how hard it will be.

**Comment by ekaitzht** [comment]
+1
