### ISSUE TITLE
Latitude and longitude geocoding doesn't geocode all rows

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#1994]
Importing a big table that has latitude and longitude columns the_geom is null for some right values. Many rows have not valid data, and thus shouldn't be geocoded, but right ones should.

https://cartodb.supportbee.com/tickets/4337851

**Comment by juanignaciosl** [comment]
The problem is in [QueryBatcher stop condition](https://github.com/CartoDB/cartodb/blob/master/services/importer/lib/importer/query_batcher.rb#L82): when a batch doesn't meet where condition `affected_rows_count` is 0 and will stop. A solution to this would be moving the where condition from main query to [CTID subquery](https://github.com/CartoDB/cartodb/blob/master/services/importer/lib/importer/query_batcher.rb#L37), but it timeouts with the lat-long query of this issue, it's slower. A solution might be batching with cartodb_id.

**Comment by iriberri** [comment]
Subscribing me here.

**Comment by iriberri** [comment]
I've multiplied by 10 the timeout of an Enterprise customer and it didn't work. Looking forward to this deploy.
