### ISSUE TITLE
importing csv file results in corrupted numeric data

### ISSUE THREAD

**Issue by clhenrick** [CartoDB/cartodb#2010]
When importing a CSV file CartoDB changes the data values in the numeric bbl column to negative values that don't resemble the original:

![screen shot 2015-02-01 at 11 09 49 am](https://cloud.githubusercontent.com/assets/161748/5992717/09f75bf6-aa03-11e4-9290-cdddcd3100eb.png)

Original Data:

![screen shot 2015-02-01 at 11 11 45 am](https://cloud.githubusercontent.com/assets/161748/5992718/25206706-aa03-11e4-9a5b-4c0a82789016.png)

This does not happen when I import the data to Postgres locally.

![screen shot 2015-02-01 at 11 13 37 am](https://cloud.githubusercontent.com/assets/161748/5992724/66a3bf48-aa03-11e4-985d-25b654a7f2c8.png)

![screen shot 2015-02-01 at 11 14 06 am](https://cloud.githubusercontent.com/assets/161748/5992728/790a2e9c-aa03-11e4-8f57-247e467b335b.png)

[Here's a dropbox link to my CSV file.](https://www.dropbox.com/s/7fo7occ9z534cwb/bushwick_survey_qgis.csv?dl=0)

**Comment by juanignaciosl** [comment]
This is duplicated: #2035 

Workaround until is fixed: quote the data that gets corrupted (*"*12345688900*"*) or import it with the api disabling type guessing.
