### ISSUE TITLE
Create an icon for the export image feature

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#2015]
We need an icon for this feature. The dimensions of the icon would be 26x26 pixels.

Reference icon: 

![setup_canvas](https://cloud.githubusercontent.com/assets/4933/5999514/b9a800e4-aad2-11e4-8b0b-0a779cfa6ccc.png)

We will place the icon at the end of the toolbar: 

![screen shot 2015-02-02 at 11 44 17](https://cloud.githubusercontent.com/assets/4933/5999457/4e063ba8-aad2-11e4-88e2-d913d926f27b.png)

cc: @CartoDB/design

**Comment by saleiva** [comment]
![imageicon](https://cloud.githubusercontent.com/assets/132149/5999649/2aa3084c-aad4-11e4-8a5b-d2e265e329e3.png)

Done! All yours!

**Comment by javierarce** [comment]
:(

**Comment by saleiva** [comment]
jaja, shit! I broke the image on the export! :)
![imageicon](https://cloud.githubusercontent.com/assets/132149/5999674/6b20beaa-aad4-11e4-9b3b-3e5661099847.png)

**Comment by javierarce** [comment]
Hahaha, that's better, thanks!
