### ISSUE TITLE
Geocoder returns 'georeferenciation error' even if it went OK.

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#2028]
![image](https://cloud.githubusercontent.com/assets/1730320/6005422/7a5be54e-ab0a-11e4-9239-ac0c6feddc17.png)

This is happening always to me, as an example:

1. Add two rows
2. Fill description with "elche" and "valencia"
3. Geocode by city names. Select `description` column and left empty the second selector. (Not relevant, if happens too if you select a country).

**Comment by iriberri** [comment]
Some possible hints from a user:

https://rollbar.com/vizzuality/CartoDB/person/?environment=production&person_id=349792e8-9242-402e-909f-8a96fb5c8436

Check the items for February 3rd.

The georef errors that I'm getting continuously in my accounts don't seem to appear in Rollbar.

**Comment by iriberri** [comment]
More info:

I tried to geocode a big table 50K with USA point zipcodes. It gave geocoding errors, as this one, but some of the data was georeferenced.

I increased the timeout for the user account, and finally I was able to get what was expected:

![image](https://cloud.githubusercontent.com/assets/1730320/6041737/9f4fbd28-ac7f-11e4-8664-0dee931c8c34.png)


Could some timeout be causing this error?

**Comment by juanignaciosl** [comment]
This is not only a temporary workaround but also a great help for solving this, thank you very much, @iriberri! I still have a [pending PR](https://github.com/CartoDB/cartodb/pull/2008) to merge that makes geocoding batching lighter, hopefully it will fix some of this.

**Comment by iriberri** [comment]
I've just had new feedback:

Geocoding (by coordinates directly) is also giving this error to Enterprise customers, not all batches are being geocoded, so they have to run the process a lot of times and afterwards confirm that all the data has been geocoded. I guess this is totally related, right?

**Comment by juanignaciosl** [comment]
Maybe, but not exactly. In fact when I said _lighter_ I was not precise. Take a look at [this comment of mine](https://github.com/CartoDB/cartodb/issues/1994#issuecomment-72247177), this is also likely to be a case you'll face. If a timeout increase doesn't solve it, the PR I said will. Hopefully I'll merge it today.

**Comment by juanignaciosl** [comment]
Ok, this works-but-fails because it fails after `complete`, before `finished`. The problem is user organization had no geocoding quota and code didn't cover that. I've assigned geocoding quota to organization and also fixed the code to cover that scenario.
