### ISSUE TITLE
Add several needed info within new remote datasets

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#2036]
- [X] Geometry type
- [X] No. of rows
- [X] Database size
- [x] Source

**Comment by juanignaciosl** [comment]
- [ ] Geometry type
- [X] No. of rows
- [X] Database size
- [x] Source

There's no geometry type data available yet (we must discuss about this later), but data structure already has it: 
```
"external_source": {
        "size": 32768,
        "rows_counted": 18,
        "geometry_types": [
          
        ]
      },
```

**Comment by xavijam** [comment]
```row_count``` instead of ```rows_counted``` i hope! :D

**Comment by juanignaciosl** [comment]
Fixed. I had followed existing schema convention instead API's.
