### ISSUE TITLE
Avatar is slightly moved up on the new header

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2037]
It should be aligned with the logo.
![screen shot 2015-02-03 at 12 29 15](https://cloud.githubusercontent.com/assets/132149/6019423/9952ef4c-aba0-11e4-99b8-47977b9a0494.png)

Minor, of course

**Comment by xavijam** [comment]
https://github.com/CartoDB/cartodb/commit/f3fc403354e7e82004015cb98d0e10a37dff7b8a
