### ISSUE TITLE
Static heatmaps from mapnik

### ISSUE THREAD

**Issue by fdansv** [CartoDB/cartodb#2046]
@javisantana 

Maybe we should use a regular point layer + colorize directly from Mapnik for static heatmaps, since that allows the user to add more layers on top of it, instead of forcing them to place them below because it's considered animated.

What do you think?

**Comment by javisantana** [comment]
let see how the current one works and then we see if should change it.

**Comment by fdansv** [comment]
We can advise to use mapnik's colorise whenever a special case needs it.
