### ISSUE TITLE
Improve performance of table.geometry_types call

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#2047]
We've detected a possible performance bottleneck in that call, that is hitting the DB quite frequently. Check this [code](https://github.com/CartoDB/cartodb/blob/172ea09e4a4dc7e074f7a1c3cdd51412557c015a/app/models/table.rb#L97-L109)

**Comment by rafatower** [comment]
This "field" can go through different states:
- empty list `[]` (new table, no geometries or not georeferenced yet)
- some insert, one of `[st_point, st_polygon,...]`
- import with multiple geometry types.
- complete removal of data -> empty list

Some possibilities to improve this:
- Move the `geometry_types` to the `user_tables` and cache it. Problem: invalidations. Stalled data is specially harmful for the editor (already tested)
- Use the sql api: proper handling of caching and invalidations.

@javisantana I'd go for the later. Any views on this?

**Comment by rafatower** [comment]
There's another possibility that I think will work better:
- move the `geometry_types` to a column in the `user_tables`
- populate it lazily from the user table once the list is non-empty
- keep that value forever for that table.

That would only penalize empty tables, but I think we can live with it. It can also check for "emptyness" using the sql api instead of querying the table directly to take advantage of its cache.

**Comment by javisantana** [comment]
the second option would still make the editor fail in case the user change the geometry type, right?

**Comment by rafatower** [comment]
> the second option would still make the editor fail in case the user change the geometry type, right?

I think you are referring to using the sql api to get the list of geometries. I checked that the editor does not query the table model again after deleting all rows from there, unless reloaded.

I was thinking on something along these lines:
```ruby
  def geometry_types
    return [] unless schema.select { |key, value| key == :the_geom }.length > 0
    @sql_api ||= CartoDB::SQLApi.new({username: owner.username, api_key: owner.api_key })
    sql = %Q{
      SELECT DISTINCT ST_GeometryType(the_geom) FROM (
        SELECT the_geom
        FROM "#{self.name}"
        WHERE (the_geom is not null) LIMIT 10
      ) as foo
    }
    ret = @sql_api.fetch(sql, csv)
```

I'm seeing some strange bottleneck locally in the sql api when csv format is requested and I'm investigating it with rochoa.

**Comment by rafatower** [comment]
If we go for option c. once the geometry_types are set they won't be changed. Can we live with that?

**Comment by rafatower** [comment]
I found a performance issue while trying to go through the sql api: https://github.com/CartoDB/CartoDB-SQL-API/issues/204#issuecomment-73536934

**Comment by rafatower** [comment]
In production, will check later on impact of TTL (probably to be increased from 30 min to 24h). We have to check also usage and memory of redis. Closing this.
