### ISSUE TITLE
Finish design for basemap selector

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2052]
Right now in Map editor - Layer basemap expanded

Things missing
- Fill the thumbnails and see the visual noise
- Way to indicate on which zoom level each basemap is available
- Flow for adding a new basemap
- Flow for removing a custom basemap
- Flow for setting a background color.

**Comment by carlostallon** [comment]
The basemap selector, the :hover shows a little UI indication about the zoom level of the basemap
![basemap selector](https://cloud.githubusercontent.com/assets/1712650/6355218/a5c0e4e0-bc54-11e4-921a-5608b4c60496.png)

**Comment by carlostallon** [comment]
New version with new standard elements.
![basemap selector](https://cloud.githubusercontent.com/assets/1712650/6487283/8255210a-c290-11e4-8e8b-e9f2ea8d4bf3.png)
All the cases covered in .../Map-editor-1.2

**Comment by saleiva** [comment]
Ossom.
