### ISSUE TITLE
Overlays are not being placed when they should due to its dotted border

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#2056]
Placing overlays takes into account the dotted border around them when selected, and this causes that the distances to the borders are not computed in the same way for all of them, causing effects like:

![image](https://cloud.githubusercontent.com/assets/1730320/6025398/7c76ac7e-abd2-11e4-93be-f953defb430b.png)

Which appear "perfectly aligned" in the Editor.

**Comment by iriberri** [comment]
Not reproducible anymore :confused:. I tried with text and title overlays, as well as different styles and using markdown in them (links, bolds, italics...)

**Comment by javierarce** [comment]
Thanks, @iriberri. I wasn't able to reproduce it either, so I'm closing it.
