### ISSUE TITLE
Design placeholder image for the maps in the dashboard

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#2059]
Since we'll be loading static images for the dashboard maps, we need a placeholder or generic image that will appear when the tiler can't return a preview of the map.

**Comment by javierarce** [comment]
Please, @carlostallon, attach the picture to the ticket! :)

**Comment by carlostallon** [comment]
: )
![map_placeholder_1](https://cloud.githubusercontent.com/assets/1712650/6066089/aa5b9818-ad6a-11e4-9150-e8b36193adf4.png)
![map_placeholder_2](https://cloud.githubusercontent.com/assets/1712650/6066090/aa5fc49c-ad6a-11e4-8c8a-08eb36d5bffb.png)
![map_placeholder_3](https://cloud.githubusercontent.com/assets/1712650/6066091/aa7048da-ad6a-11e4-99d8-04131763750f.png)
![map_placeholder_4](https://cloud.githubusercontent.com/assets/1712650/6066092/aa770fa8-ad6a-11e4-8578-43be549ebf2f.png)

**Comment by javierarce** [comment]
Don't you find a bit weird that if we can't load a preview, we first show the linen texture and then replace it with one of those placeholders?
