### ISSUE TITLE
Open privacy dialog directly from an item 

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#2061]
Since there is a private indicator directly on the items, e.g. maps:
![screen shot 2015-02-04 at 09 38 03](https://cloud.githubusercontent.com/assets/978461/6037240/b3a786e4-ac51-11e4-8e95-eaa92fc74577.png)

datasets:
![image](https://cloud.githubusercontent.com/assets/1730320/6268102/56a1b064-b84a-11e4-850a-0c99826ce0b5.png)

why not simply make it clickable to open the dialog directly, instead of having to select an item and go through the filters menu?

**Comment by viddo** [comment]
ping @saleiva @xavijam

**Comment by saleiva** [comment]
Yeah, as I mentioned, we should rethink this, but for the time being, do it clickable, of course :)
