### ISSUE TITLE
Improve the loading text of the new dashboard

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#2067]
Here's and a idea: the loading screen says: `Loading… it's just a second (or two)`. I think that we should add some nice sentences *à la* Slack, instead of focusing the attention of the user on the loading time.

We could use some stuff from [this list I compiled](https://github.com/javierarce/slack-loading-messages).

**Comment by javisantana** [comment]
I would spend the time creating a local cache for table list in order to avoid that loading screen:

https://github.com/teambox/backbone.memoized_sync

**Comment by javierarce** [comment]
That would be nice, yeah. Should we close this ticket and open another one for that then?

**Comment by javisantana** [comment]
haha, no no, it was an opinion, loading is still needed for search and so on

**Comment by viddo** [comment]
another/additional idea: I think the preloader placeholders that facebook has in its newsfeed are really nice too 
![screen shot 2015-02-04 at 13 32 51](https://cloud.githubusercontent.com/assets/978461/6040457/5c6f3d2e-ac72-11e4-9cd8-c58057a868bc.png)

**Comment by javierarce** [comment]
That would be nice, yes.

**Comment by javisantana** [comment]
http://open.spotify.com/artist/6RZUqkomCmb8zCRqc9eznB

**Comment by javierarce** [comment]
Closing this since we'll we working in https://github.com/CartoDB/cartodb/issues/2396. 

@javisantana: you can keep trolling us there :heart:

**Comment by javisantana** [comment]
@javierarce you can enable my troll thing with "cached_dashboard" feature flag
