### ISSUE TITLE
Add column for geometry type in Common Data

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#2074]
It's needed to be able to classify the different datasets according to the type of geometry that they include: line, polygon or point.

name: geometry_types
contents: array of strings -> ST_GeometryType

I'll be using: array_agg(distinct(ST_GeometryType(the_geom)))
cc/ @juanignaciosl

**Comment by javisantana** [comment]
this is pretty related with the thing that @rafatower is working on

**Comment by juanignaciosl** [comment]
Ok, we'll add it for common data. When this is finished I'll add that data to #1442 .

**Comment by iriberri** [comment]
By the way, I've just seen that in some cases we could have "NULL" values for types (although always another string of the array will have a proper geometryType). So adding this here in order to not forget it.
