### ISSUE TITLE
If you don't have google config, login page raises an error

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#2080]
![screen shot 2015-02-04 at 17 55 30](https://cloud.githubusercontent.com/assets/132146/6044965/0c4c2bf2-ac97-11e4-9941-80ab012b713a.png)

Not sure who is on charge of this, please @matallo or @juanignaciosl, dispatch as you consider.

**Comment by xavijam** [comment]
Also, when login works, please consider to remove the google button if credentials are not filled in.

**Comment by juanignaciosl** [comment]
It's not a matter of having the config, but a missing require ¬¬ . Depending on the order of the load of the classes works...
