### ISSUE TITLE
Tile placeholder image for Maps API

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb#2109]
We need a placeholder image in PNG format (not so important but better if it's in PNG32) in 256x256px and if possible also in 512x512px (for upcoming retina support).

The image will be used as a fallback when a http layer type is used and the `urlTemplate` provided is not valid.

**Comment by saleiva** [comment]
![256x256](https://cloud.githubusercontent.com/assets/132149/6104042/33f7cc18-b04a-11e4-9ec8-d3ff4e0297b4.png)
![512x512](https://cloud.githubusercontent.com/assets/132149/6104041/33f6b710-b04a-11e4-8e02-e4e0ebbfe337.png)

**Comment by saleiva** [comment]
![256x256](https://cloud.githubusercontent.com/assets/132149/6104054/4d4d0930-b04a-11e4-85a5-0beca8ff0314.png)

**Comment by rochoa** [comment]
Thanks :+1:
