### ISSUE TITLE
Error creating a Torque map

### ISSUE THREAD

**Issue by Xatpy** [CartoDB/cartodb#2114]
There's an error when you create a Torque Map: TrackerJS returns a Javascript error and you can't see the map (spinner is loading):
```
Uncaught Error: TrackJS Caught: undefined is not a function         tracker.js:26
        x.wrapError                                                                               tracker.js:26 
        l.wrapAndCatch.d.util.hasFunction.a.(anonymous function)    tracker.js:4
        .d.util.hasFunction.f.(anonymous function)
```
But if you go to the dashboard, and then go to the map view again, the Torque Map is working.
Version deployed:
```
cartodb.js 3.12.00
tracker.js:10 cartodbui v3.4.4 sha1: c4d4370c80def041a25d68d7c4ee7d72c8fb72e3
```
Gif:
![bug_torque](https://cloud.githubusercontent.com/assets/3958416/6080703/02f4c61c-ae14-11e4-86fd-a32c4054f267.gif)

**Comment by fdansv** [comment]
This is fixes as of #2117
