### ISSUE TITLE
[limits] Limit the size of the imported file

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#2115]
the import api should not allow to import files greater than a max in bytes. That max should be stablished per user.

**Comment by Kartones** [comment]
Milestone? and default value for this max?

**Comment by Kartones** [comment]
Also, we should have two sizes, one for normal/geometry files, another for rasters, no?

**Comment by Kartones** [comment]
More analysis (summing up previous comments here): 
- IMO raster file sizes should be a separate value, it is always going to be bigger as is a different scenario from normal imports.
- What happens with files retrieved from datasources like ArcGIS or Twitter? The former can vary a lot in size, and we could affect existing users.
- What happens with sync tables? We let them fail if the table grows over the maximum allowed size?
- Is there any decided limit value? I think we should extract stats of average table size, and sizes and users of all above that average to decide course of actions, proper limit value, etc.

**Comment by javisantana** [comment]
arcgis, twitter and sync tables are limited by row number.

The file limit will be defined not by the current avg but for the max number of points we can render in less than 1 second

**Comment by Kartones** [comment]
That's a bit dangerous at least for geojson files, if they get big I'm not sure if they'll fit in memory even having simple geometries, but I'd have to check.

**Comment by Kartones** [comment]
Need to add new user attribute :max_import_file_size

**Comment by saleiva** [comment]
Here the error reporting is critical, we should provide alternatives or workarounds in the error we send to the user.

**Comment by Kartones** [comment]
Then think about the message or workaround provided while I finish coding it :DDD

But we already have an error code and desc for this:
```
    6666 => {
      title: 'Dataset too big',
      what_about: "The dataset you tried to import is too big and cannot be processed. If the dataset allows it, you can try splitting it into smaller files and then using the 'Merge Tables' functionality."
    },

```

**Comment by javisantana** [comment]
"... contact our sales team sales@cartodb.com"

**Comment by Kartones** [comment]
After talking with saleiva, will push live just changing the literal to mention support instead of sales.
