### ISSUE TITLE
Image render funkyness from Table -> Visualization views

### ISSUE THREAD

**Issue by auremoser** [CartoDB/cartodb#2120]
I made a quick [Rosa Parks map](https://team.cartodb.com/u/aureliamoser/viz/5f164106-a8c3-11e4-ae4a-0e018d66dc29/map) to demo to journalists; the visualization view doesn't pull the images properly, but I can see them in the edit interface. 

For context, 
* I have Odyssey enabled in my account.
* I loaded in a table and build my slides in the map view of the editor. 
* When I publish to visualization, the images render as broken grey boxes.

I'm using two tables [rosaparks here](https://team.cartodb.com/u/aureliamoser/tables/rosaparks/map) and [freedomroute points here](https://team.cartodb.com/u/aureliamoser/tables/freedomroute) and then another [freedomroute_line](https://team.cartodb.com/u/aureliamoser/tables/freedomroute_line) where ST-makeline between the points so there's a "route"; not sure if the number of layers affects anything, but maybe it does.

This is what I see in the editor:
![screen shot 2015-02-06 at 6 16 34 pm](https://cloud.githubusercontent.com/assets/1559703/6089162/7031895a-ae2c-11e4-89cd-3db282081335.jpg)
This is what the Visualization displays:
![screen shot 2015-02-06 at 6 16 57 pm](https://cloud.githubusercontent.com/assets/1559703/6089165/7a7832d8-ae2c-11e4-869a-bbda772ceda5.jpg)

**Comment by javisantana** [comment]
probably the same: https://github.com/CartoDB/cartodb/issues/2020, https://github.com/CartoDB/cartodb/issues/1979
