### ISSUE TITLE
Change default heat color scale

### ISSUE THREAD

**Issue by fdansv** [CartoDB/cartodb#2124]
As suggested by @andrewxhill, the default palette for heatmaps should be:

```blue, cyan,lightgreen, yellow, orange, red```

We should probably think about including some extra default gradients for the user to choose from.

**Comment by fdansv** [comment]
OK, one thing: I really like how it looks over a dark basemap:
![screen shot 2015-02-09 at 11 39 43](https://cloud.githubusercontent.com/assets/3707222/6104744/86497af6-b050-11e4-890a-3699cd6a3690.png)

But I'm not that sure against Positron:
![screen shot 2015-02-09 at 11 39 53](https://cloud.githubusercontent.com/assets/3707222/6104758/aae23e2a-b050-11e4-8a98-30d3c01a80cf.png)

**Comment by saleiva** [comment]
I doesn't look bad. Remember Alberto mentioned the idea of adding a selector for the color ramp

**Comment by fdansv** [comment]
Let's set it that way then :) . 

> Remember Alberto mentioned the idea of adding a selector for the color ramp

Yeah Andrew and I were talking about it the other day. Something similar to this, which is super cool:

http://old.driven-by-data.net/about/chromajs/

**Comment by saleiva** [comment]
What about reusing the component we have now for choropleth maps but with different ramps?

**Comment by fdansv** [comment]
> What about reusing the component we have now for choropleth maps but with different ramps?

Yeah let's do that, but I've just updated the default ramp with ```lightgreen``` so we're done here. Opening a new issue for a ramp picker.
