### ISSUE TITLE
Add button to import data library datasets

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#2129]
Instead of just importing the tables when selecting them.

**Comment by saleiva** [comment]
When do you mean? In which moment?

**Comment by iriberri** [comment]
In the dashboard, if you click inside the "box" of the table, (the dark blue area that appears when a dataset is hovered, picture below) the table gets imported. 

What about just importing if you click a "import button", or explicitly on the table name at least?  If not, I think that people will start downloading a bunch of tables without noticing, or at least I do it when I test the new dashboard and I navigate through Data Library.

![image](https://cloud.githubusercontent.com/assets/1730320/6246350/403e4ab8-b768-11e4-8f89-9875eeea368a.png)

**Comment by saleiva** [comment]
Uhm... that layout is broken! :)
It should get imported when clikcing on the name, not in the box. Anyway, I've an option with a button ready at create-modal-1.2.sketch

**Comment by iriberri** [comment]
Yeah, I just logged into a random staging account with Data Library to get the "blue box" image. :-) If you've changed the import to need a click in the name, that's perfect then. I'll test all this in a couple of hours.

**Comment by xavijam** [comment]
Button or name?

**Comment by xavijam** [comment]
@saleiva, where?

**Comment by xavijam** [comment]
The behaviour has changed, so closing this ticket ;)
