### ISSUE TITLE
[limits] # of imports at the same time

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#2132]
we should limit the number of imports per person at the same time (and the ones in the queue)

**Comment by xavijam** [comment]
subscribed

**Comment by saleiva** [comment]
I'd say 2, but this is tricky. Imagine an user uploads a zip with more than 5 files...

**Comment by Kartones** [comment]
No no, it is imports count, no number of files. with a limit of 2 you can import up to two zip files at once, then no more imports until at least one of them has finished.

**Comment by saleiva** [comment]
Cool, then I'd say 2 or 3 for the time being.

**Comment by Kartones** [comment]
@xavijam I'll need your FE skills once I have this finished, as there's a flow change on the imports endpoint:

In case of having reached the imports limit, POST to `/api/v1/imports`  will return:

```
Status Code: 429
{"errors":{"imports":"We're sorry but you're already using your allowed 3 import slots"}}
```
(where 3 is the current user's max imports setup)  instead of the typical:

```
Status Code 200
{ "item_queue_id": DATA_IMPORT_ID, "success": true }
```


PS: Copy/Text changes are welcome, else this one will do.

**Comment by Kartones** [comment]
@javierarce I summon you :sparkles: 

1st you need to run `bundle exec rake db:migrate` so you get the new User field.
2nd restart rails but don't start resque (if import jobs don't get processed is much easier to test the scenario).
3rd check my previous comment above, is capturing an error with HTTP code 429, and displaying to the user the message, but being performing the POST to /create is a new flow that right now only shows a generic error window.

By default a user can upload 3 files, so trying to upload the 4th one without having finished the others will trigger the rate limit error.

For any question just ask me. Thanks!
