### ISSUE TITLE
Create new visualization from the dashboard has stopped working

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#2140]
![creatviz](https://cloud.githubusercontent.com/assets/370259/6112008/21718bc2-b05b-11e4-82a8-f1e8c59c9557.gif)

cc @javisantana

**Comment by javisantana** [comment]
@andrewxhill it is taking lot of time but it's working

this is part of our performance improvement month cc @rafatower @Kartones

**Comment by Kartones** [comment]
Indeed it is very slow even on my account (I have just like a dozen tables, and not so many shared with me).
