### ISSUE TITLE
Design when an error happens after submit a form in new dashboard

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#2156]
When this form fails, what will it look like?

![screen shot 2015-02-10 at 12 13 45](https://cloud.githubusercontent.com/assets/132146/6126209/7e9f9672-b11e-11e4-80b7-9377ae8ffc2c.png)

Dispatch as you want @saleiva.

**Comment by carlostallon** [comment]
![error](https://cloud.githubusercontent.com/assets/1712650/6131262/f8ea3500-b14a-11e4-9b16-4f41748254e3.png)
