### ISSUE TITLE
Login with Google doesn't seem to work properly on existing multiuser accounts

### ISSUE THREAD

**Issue by zenitraM** [CartoDB/cartodb#2160]
How to replicate:
- Have a multiuser account with the same email as a Google account
- Login with Google

At least for me the dashboard always redirects to http://team.cartodb.com/dashboard instead of http://team.cartodb.com/u/zenitram/dashboard (so links are wrong)

**Comment by juanignaciosl** [comment]
I've checked this in local, with user "juanignaciosl6", who is admin of "juanignaciosl6-org". Signing in at Central redirects to `http://juanignaciosl6-org.localhost.lan:3000/u/juanignaciosl6/dashboard/tables`, which seems fine. At box redirects to `http://juanignaciosl6-org.localhost.lan:3000/dashboard`, which is a different URL for the same domain.

With 'juanignaciosl10', a non-admin user of the same organization, the result is the same: 'http://juanignaciosl6-org.localhost.lan:3000/u/juanignaciosl10/dashboard/tables' and 'http://juanignaciosl6-org.localhost.lan:3000/dashboard/'. 

I've done both boxes checks both with team subdomain and without it. I've also simulated this setting `google_sign_in` to false, but it also works.

I've checked my own account in production. Central redirects me to superadmin, and team.cartodb.com sends to `https://team.cartodb.com/dashboard/`. Certainly redirect URLs are not the same, but content seems ok. Is there any problem with those URLs?

Actually there [was a problem with redirections](https://github.com/CartoDB/cartodb/pull/2005#issuecomment-72223662) [and we had to fix it](https://github.com/CartoDB/cartodb/commit/b47d1b2e250d6c23d17d37b720e3e4f190248c98). Are your links not working, or are just different than what you expected?

**Comment by zenitraM** [comment]
@juanignaciosl actually `http://team.cartodb.com/dashboard` renders fine, but, for example, if you click on any table, it tries to go to `http://team.cartodb.com/tables/tablename` instead of  `http://team.cartodb.com/u/user/tables/tablename` so it fails

**Comment by zenitraM** [comment]
Also trying to manually go to `https://team.cartodb.com/u/zenitram/dashboard/` redirects me back to `https://team.cartodb.com/dashboard/`

**Comment by juanignaciosl** [comment]
Ok, now I see. If you login through Central it works (both render and links), but since we (team) are redirected to superadmin we don't see the same as other users. Login at the box renders fine but location make links not work. I'll fix box redirection then. Thanks!
