### ISSUE TITLE
Add tooltip on mouse hover to Custom HTML icon in Legends - CartoDB sidebar

### ISSUE THREAD

**Issue by michellechandra** [CartoDB/cartodb#2168]
No user feedback in Legends section of CartoDB sidebar that icon is to edit Custom HTML:

![screen shot 2015-02-10 at 11 06 51 am](https://cloud.githubusercontent.com/assets/5423288/6130739/2d7d4a36-b115-11e4-8e4b-00885f2e7e29.png)

Also no tooltip on icon to navigate away from Custom HTML window:
![screen shot 2015-02-10 at 11 07 14 am](https://cloud.githubusercontent.com/assets/5423288/6130782/72cb635c-b115-11e4-88b1-b5c517348676.png)

**Comment by saleiva** [comment]
This is a bug. This used to work...
