### ISSUE TITLE
Torque Heat - Change Threshold menu name to Opacity

### ISSUE THREAD

**Issue by michellechandra** [CartoDB/cartodb#2169]
![screen shot 2015-02-10 at 11 12 16 am](https://cloud.githubusercontent.com/assets/5423288/6130816/cd13937a-b115-11e4-932b-11dcae0789eb.png)

**Comment by fdansv** [comment]
Ha, actually the CSS property it changes is ```marker-fill-opacity```, but we thought that threshold would sound a bit more photoshop-ish and a bit more centric to heatmaps. @saleiva what do you think?

**Comment by saleiva** [comment]
Uhm... good question. Don't mind switching to Opacity in reality,...

**Comment by fdansv** [comment]
Cool, let's do that.

**Comment by fdansv** [comment]
Changed as of #2248.
