### ISSUE TITLE
Add Category Color Label to Category and Torque Category Options in Wizards

### ISSUE THREAD

**Issue by michellechandra** [CartoDB/cartodb#2171]
No label for the category marker colors section in Category and Torque Category (below Resolution). 

![screen shot 2015-02-10 at 11 21 43 am](https://cloud.githubusercontent.com/assets/5423288/6131086/8ac9b51a-b117-11e4-8292-59b44edc9d5b.png)

Not sure what the label should be, but definitely needs one! Might also be good to link to the Legends section since the user can edit the legend labels more there.

**Comment by saleiva** [comment]
Fixed in the new editor designs! :)
