### ISSUE TITLE
Multivariate visualisation wizard?

### ISSUE THREAD

**Issue by stevage** [CartoDB/cartodb#2181]
All the current wizard types are single-variable: they let you visualise a single attribute, like Bubble (radius), choropleth (colour), category (colour), Torque (time). A few don't visualise any attributes at all (simple, cluster, density etc).

As a result I usually have to write CartoCSS to combine two types. Normally I use one wizard, copy the code, then use the other wizard, and paste it. Creating a multivariate legend is a bit more messing around, but can be done:

![screenshot 2015-02-11 12 38 49](https://cloud.githubusercontent.com/assets/678344/6140378/f7391eba-b1ea-11e4-81e5-621616f51636.png)

So how about some multi-variate wizards? The most common combination would be bubble/choropleth or bubble/category.

**Comment by saleiva** [comment]
Hi @stevage thanks for your feedback. As part of a mayor redesign of the CartoDB  editor we are re-thinking a bit the wizards, and some ideas are in the same way you are proposing. Definitely good news! :)

**Comment by saleiva** [comment]
Fixed on the Builder. In your screens very soon :)
