### ISSUE TITLE
OAuth already set for service when token is nil

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#2186]
`import_controller.rb` sometimes trigger `OAuth already set for service` error because a synchronization oauth is set for a service but it has no token, so it won't allow to register service neither will be able to use it.

Not having token is probably a failed case. Can we avoid storing oauths without token? If we can't, can we check if token is not nil before throwing that error (and probably deleting the oauth if we can´t).

This has been reported for GDrive, don't know whether it happens with any other service.

cc @iriberri @Kartones

**Comment by Kartones** [comment]
Yes, it makes all sense to remove the "remainder" (oauth entry in this case) if there's no token... upon storage should have it (my bad if doesn't), upon using the OAuth connector it might indicate an expired token or similar so should be like capturing error and removing the entry.
