### ISSUE TITLE
"forgot password" not working with new login in open-source edition

### ISSUE THREAD

**Issue by santisaez** [CartoDB/cartodb#2190]
I have just make a fresh install of CartoDB open-source:

1. Go to `/login`
2. Click on "Forgot password?" - it's a link to `https://$domain/password_resets/new`
3. You should get a 404

**Comment by Xatpy** [comment]
Closing with this [PR#2646](https://github.com/CartoDB/cartodb/pull/2646) -> Merging on next 9thMonday

**Comment by Xatpy** [comment]
Closing with this [PR#2646](https://github.com/CartoDB/cartodb/pull/2646) -> Merging on next 9thMonday
