### ISSUE TITLE
"create an account" should be removed from open-source edition

### ISSUE THREAD

**Issue by santisaez** [CartoDB/cartodb#2191]
"Create an account" link points to a [signup page](https://cartodb.com/signup) in the SaaS, it should be removed or dealt differently in open-source edition.

**Comment by Xatpy** [comment]
The signup page link ('http://cartodb.com/signup') is in the following files:
- app/views/admin/shared/_new_public_header.erb
- app/views/admin/shared/_public_footer.html.erb
- app/views/admin/shared/_public_header.html.erb
- app/views/admin/visualizations/public/_public_map_footer.html.erb
- app/views/oauth/ (authorize.html || authorize_failure.html.erb || authorize_success.html.erb)
- app/views/sessions/new.html.erb [PR#2478](https://github.com/CartoDB/cartodb/pull/2478)

@javisantana ,  should I hide all that links if `( Cartodb.config[:account_host] == "cartodb.com")` ??

**Comment by Xatpy** [comment]
Closing with this [PR#2646](https://github.com/CartoDB/cartodb/pull/2646) -> Merging on next 9thMonday
