### ISSUE TITLE
Density Wizard not completely Functional

### ISSUE THREAD

**Issue by pramsey** [CartoDB/cartodb#2197]
* Changing the "Method" from hexagons to rectangles does not trigger a redraw. Changing the number of bins works though.
* The actual bin calculation seems suspect. The color ramp runs from green to red, but the bins never get a green color: surely there's a few bins with only a handful of hits?

http://cdb.io/1E1BUY2

![screenshot_142](https://cloud.githubusercontent.com/assets/113883/6155278/d2d129b8-b1e6-11e4-8044-1ae32f25f519.png)

**Comment by javisantana** [comment]
see https://github.com/CartoDB/cartodb/issues/949

**Comment by saleiva** [comment]
hi @pramsey this is being solved by @alonsogarciapablo and should be merged soon!

**Comment by alonsogarciapablo** [comment]
@pramsey released!
