### ISSUE TITLE
Can't draw ellipses with Simple wizard after choosing icon

### ISSUE THREAD

**Issue by stevage** [CartoDB/cartodb#2198]
I've noticed this problem for a long time.

1. Choose simple wizard
2. Choose an icon
3. Now try to go back to drawing ellipses.

I can't find any way to achieve this. Even editing the CartoCSS is only temporary - as soon as you make any change in the wizard, the icon comes back.

It's a real problem if you have set an icon on the map view for the datafile, because then the only solution is to delete the whole table and reimport, which kills any visualisations that depend on it.

**Comment by saleiva** [comment]
Hey @iriberri can you debug this?

**Comment by stevage** [comment]
To clarify slightly, I think there are two separate problems here:

1. There is no GUI for selecting "no icon", after you have chosen an icon. A "clear" button on the icon selector dialog might work.
2. There is some kind of stickiness that keeps re-introducing the icon even after you manually remove it by editing the CartoCSS. This may be a bug.

**Comment by iriberri** [comment]
Got it, editing the steps for reproducing this issue for the team:

**Removing images as markers is not possible permanently from CartoCSS nor UI (if you reapply a style)** AKA: CartoCSS is not synchronized totally with wizards options.

* Open a points dataset
* Use an random icon as marker in a Simple Wizard
  * Fine, I want to show points as markers again:
    * In the wizard UI, there's no option for removing the icon. Setting a new color just colorizes the icon.
    * You can go to CartoCSS to remove the `marker-file` statement and apply it, all ok. But then, if you go back to the wizards and select Bubble (for example) and then Simple wizard again, the icon appears.

The same behaviour happens with `polygon-pattern-fill`. Modifying CartoCSS code is not saved in the wizard itself in which you're working so when you reapply the wizard after using custom CartoCSS it contains your old manual styles.

This is something we already knew. It doesn't just happen with icons, but with any other manual style you apply in a wizard: although you change the CartoCSS, if you reapply the wizard again the first manual options are used.

**Comment by stevage** [comment]
This may not count as the same issue, but I notice that in the Category wizard, there is a mechanism for removing the icon. But weirdly, with the Category wizard, you can't specify a colour and an icon together.

**Comment by javisantana** [comment]
> CartoCSS is not synchronized totally with wizards options.

cartocss is never synchronized with wizards. Wizards generates cartocss, that's it.

the bug here is: there is no button (or way) to remove image from wizard as @stevage says

**Comment by iriberri** [comment]
Closing and moving here: https://github.com/CartoDB/cartodb/issues/2668
