### ISSUE TITLE
api does not update cdb_tablemedata when a column is casted

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#2203]
it only invalidates varnish: 

https://github.com/CartoDB/cartodb/blob/2182-geometry_types_frontend/app/models/table.rb#L1045

``update_cdb_tablemetadata`` should be called

**Comment by javisantana** [comment]
use cdb_touchmedata function

**Comment by alonsogarciapablo** [comment]
@javisantana the link you posted is no longer working. Are we talking about [Table#modify_column](https://github.com/CartoDB/cartodb/blob/master/app/models/table.rb#L1003-L1018)?

**Comment by javisantana** [comment]
yes, sorry

**Comment by javisantana** [comment]
also, for reference: https://github.com/CartoDB/cartodb-postgresql/blob/master/scripts-available/CDB_TableMetadata.sql#L123
