### ISSUE TITLE
Imported tables have huge filesize difference than pg_relation_size

### ISSUE THREAD

**Issue by Kartones** [CartoDB/cartodb#2204]
Imported a small XLS file:
```
CartoDB Editor dashboard:
7.39 MB
```
```
pg_size_pretty( pg_relation_size('testing') )
> 288 KB
```

Doing VACUUM and/or VACUUM FULL does nothing.

**Comment by Kartones** [comment]
@javisantana @saleiva : @iriberri tells me we have 3/4 issues **per week** lately about users complaining of this. Should I stop my current tasks and check what has changed recently regarding disk space in dashboard listing?

**Comment by saleiva** [comment]
Let's leave for after the limits.

**Comment by Kartones** [comment]
In a dev environment, without georeferencing file size is correct. Georeferencing is what triggers the big increase of space, but that shouldn't be a problem as it should go down, something is caching it.

**Comment by Kartones** [comment]
Issue found. Both at rails (`app/models/table/relator.rb` method `row_count_and_size`) and the extension (`CDB_Quota.sql` function `CDB_UserDataSize`) use `pg_total_relation_size`, which takes into account dead rows, indexes, etc., instead of `pg_relation_size` (which only counts live ones).

After talking with @javisantana we'll replace by the "live only" version.

**Comment by Kartones** [comment]
This ticket is only pending postgresql extension release to bump up rails code and push live.

**Comment by Kartones** [comment]
@iriberri I'll push the pull request tomorrow live.
