### ISSUE TITLE
change the credit of Nokia Maps

### ISSUE THREAD

**Issue by jatorre** [CartoDB/cartodb#2205]
It has to say 2015, not 2012.

![image001](https://cloud.githubusercontent.com/assets/127803/6167104/d512da7e-b2b7-11e4-9a83-d2d88616d579.png)

**Comment by xavijam** [comment]
That info comes from application config, basemaps part. @zenitraM, @azamorano or @santisaez, could you take care of it?

**Comment by santisaez** [comment]
Fixed by @zenitraM
