### ISSUE TITLE
GDrive connector is not working

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#2207]
https://:username.cartodb.com/api/v1/imports/service/gdrive/token_valid endpoint is returning 400 error :S

**Comment by Kartones** [comment]
I just revoked my token from GDrive,, then got this:
```
{"errors":{"imports":"setting token: Authorization failed.  Server message:\n{\n  \"error\" : \"invalid_grant\",\n  \"error_description\" : \"Token has been revoked.\"\n} @ gdrive"}}
```
Which is ok, and restarts the authorization flow.

After re-granting, I could import ok. And going back to the Gdrive import, now I get a nice 200:
```
{"oauth_valid":true,"success":true}
```

So.. I need further steps to reproduce it :/  And the message returned along with the 400 would help too.

**Comment by Kartones** [comment]
Ok, after more tests, it's the issue that will be solved at https://github.com/CartoDB/cartodb/issues/2186 so closing as duplicate.

For the record, tried with users who never linked Gdrive and others that did, and in both scenarios it works.
