### ISSUE TITLE
[geometry-type-cache] Can't change styles with new geometries , Cannot read property 'name' of null

### ISSUE THREAD

**Issue by Xatpy** [CartoDB/cartodb#2209]
Steps to reproduce:
1. Create an empty table.
2. Go to map view.
3. Add feature -> polygon
4. Paint a polygon

You can't change styles, and a error is returned:
> Uncaught TypeError: Cannot read property 'name' of null

![screen shot 2015-02-12 at 15 40 19](https://cloud.githubusercontent.com/assets/3958416/6169452/d9c80b28-b2cd-11e4-95c2-2de474f1fc3a.png)

**Comment by javisantana** [comment]
I can't reproduce but looking at the stacktrace the problem is in the table selector no adding a polygon
