### ISSUE TITLE
Add error icon in the dashboard previews

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#2227]

**Comment by javierarce** [comment]
![mapcard_error](https://cloud.githubusercontent.com/assets/4933/6192043/9e786766-b3ae-11e4-9150-9fa9cf14f5d7.gif)

Too subtle, @CartoDB/design?

**Comment by saleiva** [comment]
I like it!

**Comment by javierarce** [comment]
Another version: 

![map_card_error_2](https://cloud.githubusercontent.com/assets/4933/6192353/3c564294-b3b1-11e4-84a6-922b75773134.gif)

**Comment by saleiva** [comment]
I prefer the other one :(

**Comment by javierarce** [comment]
Me too, actually. 

If there's nobody against it, I'll merge it then :)
