### ISSUE TITLE
The Map{} object is no longer accessible, but the default buffer kills basic labels some times

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#2233]
And line-smooth is pointless now :(

![screen shot 2015-02-14 at 2 33 58 pm](https://cloud.githubusercontent.com/assets/370259/6200803/b5f7e846-b456-11e4-9219-c222e1ee2efb.png)

See "Washington DC"

**Comment by rochoa** [comment]
What cartocss are you using? Do you have different layers with a different Map object on each of them?

I would need a bit more of context information to see what is really happening.

Map object is working at least in some cases. See labels effect with [buffer-size: 256](https://team.cartodb.com/u/rochoa/viz/f811107a-48a6-11e4-9bd0-0e9d821ea90d/public_map) and [buffer-size: 64](https://team.cartodb.com/u/rochoa/viz/91592496-b4fb-11e4-aeda-0e9d821ea90d/public_map).

**Comment by andrewxhill** [comment]
![screen shot 2015-02-17 at 4 56 43 pm](https://cloud.githubusercontent.com/assets/370259/6238059/ff035cca-b6c5-11e4-9d5b-9f3fd7553d5d.png)

Just one layer, actually, just on the map view of a table. Just my account?
