### ISSUE TITLE
Poor sync status message in tables list

### ISSUE THREAD

**Issue by pramsey** [CartoDB/cartodb#2234]
Immediately after loading a new table with sync'ing turned on, the status after the table says "synced in a few seconds". This implies it is *going* to be synced in a few seconds, rather than that it was just recently loaded. After a short while, the message changes to a more appropriate "synced 3 minutes ago"
![screenshot_210](https://cloud.githubusercontent.com/assets/113883/6201156/747c40ea-b44e-11e4-81f0-19a1caf6f5b1.png)

**Comment by saleiva** [comment]
To fix in the new dashboard. cc @xavijam

**Comment by xavijam** [comment]
Already fixed in the new dashboard :), closing!

**Comment by xavijam** [comment]
BW, thanks for the feedback @pramsey :).
