### ISSUE TITLE
Editing HTML in the 'Image Header' Infowindow breaks the image

### ISSUE THREAD

**Issue by cshirky** [CartoDB/cartodb#2235]
In an Infowindow set to Image Header, modifying the HTML causes the image to break, even if no code changes affect the header divs.

Steps to reproduce:

<strong>1. Create an Infowindow using Image Header (including creating the imageurl column, moving it to the top of the Infowindow fields, and turning it on.)</strong>
![screen shot 2015-02-15 at 7 38 01 pm](https://cloud.githubusercontent.com/assets/226500/6203276/fef64ab2-b553-11e4-96c6-7cb7159f23f1.png)

<strong>2. Select and edit Custom HTML</strong>
![screen shot 2015-02-15 at 7 39 04 pm](https://cloud.githubusercontent.com/assets/226500/6203284/27dcb4c0-b554-11e4-8fb1-2dcc8ee504eb.png)

<strong>3. Hit Apply. Without having edited anything in the header divs or using {{imageurl}}, the image will now break.</strong>
![screen shot 2015-02-15 at 7 39 20 pm](https://cloud.githubusercontent.com/assets/226500/6203288/42140f14-b554-11e4-9af6-19a4914fc763.png)

**Comment by saleiva** [comment]
@alonsogarciapablo I guess this was fixed with your PR fixing the images infowindows. Can you confirm? If so, close this :)

**Comment by alonsogarciapablo** [comment]
@cshirky thanks for the detailed description. It looks like it's not working. Not sure if it's related to what I fixed recently. I will have to take a look.
