### ISSUE TITLE
Content and list of templates for the new onboarding

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2237]
Hey @andrewxhill we need content for the new onboarding modal window. We are planning on starting with the rollout of the new dashboard (to internal people and some selected users) by the end of this week so I guess this is quite prioritary.

![screen shot 2015-02-16 at 10 04 41](https://cloud.githubusercontent.com/assets/132149/6209211/579e67f2-b5c3-11e4-80f4-ef9085377105.png)

Right now, we just have a placeholder!

**Comment by andrewxhill** [comment]
hey... let's have a quick chat (15min) about this tomorrow @saleiva ?

**Comment by saleiva** [comment]
sure, we need to talk about this ASAP
