### ISSUE TITLE
Review texts for empty results

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#2243]
Unfortunately there are several scenarios when there isn't any item, for example:

![screen shot 2015-02-16 at 10 12 35](https://cloud.githubusercontent.com/assets/132146/6209629/19569884-b5c8-11e4-9ce5-103226606454.png)

![screen shot 2015-02-16 at 10 40 43](https://cloud.githubusercontent.com/assets/132146/6209650/4eb4532c-b5c8-11e4-897f-4803e5121a93.png)

Some nice texts will be awesome, what do you think?

cc @andrewxhill

**Comment by saleiva** [comment]
Bump!

**Comment by andrewxhill** [comment]
Let's tell them how to fill it up. Something like, "Fill this section up by
clicking the heart on CartoDB maps published on the web or on user profile
pages."

**Comment by saleiva** [comment]
Cool, thanks @andrewxhill
