### ISSUE TITLE
temporary files in repository ?

### ISSUE THREAD

**Issue by strk** [CartoDB/cartodb#2249]
Having a disk space issue I went around looking for things to drop and to my surprise cartodb repo was one of the biggest source trees I had around. The biggest directory was the "public" one. I got rid of it and then checked with "git status" what was in the sources.

Suspiciously a lot of files under a "tmp" dir were, an extract:
```
        deleted:    public/tmp/sass-cache/6e853547434e9892c87813cf8e3d9d1284d71266/_inline-block.scssc
        deleted:    public/tmp/sass-cache/6e853547434e9892c87813cf8e3d9d1284d71266/_opacity.scssc
        deleted:    public/tmp/sass-cache/6e853547434e9892c87813cf8e3d9d1284d71266/_shared.scssc
        deleted:    public/tmp/sass-cache/6e853547434e9892c87813cf8e3d9d1284d71266/_text-shadow.scssc
```

Do those files really belong there ?

**Comment by viddo** [comment]
Good catch, it seems pretty obvious that they should not be in the version control to begin with (committed +3 years ago and haven't been touched since). I'll take care of cleaning up
