### ISSUE TITLE
Sharing visualization URL fails

### ISSUE THREAD

**Issue by cshirky** [CartoDB/cartodb#2255]
This may be a bug, or just a UI issue leading the user to expect different behavior than Carto allows for. When a CartoDB user sends a URL of a visualization to an un-logged-in user, it shows the map, but Clone This fails to import the visualization. 

Steps to reproduce:

1. Give this URL to an un-logged-in user: https://cshirky.cartodb.com/viz/8900aa00-b580-11e4-b930-0e4fddd5de28/map
2. A map with a single orange line should appear, with Clone This as one of the options in the blue header bar.
3. Clicking 'Clone This' takes you to the login page. Login using Google.

The resulting dashboard will not include the nominally cloned map. If the user has no maps, the dashboard will only offer options to create your first table or visualization.

Is this expected behavior? Why would there be a non-function Clone This option shown to the user?

**Comment by saleiva** [comment]
Hi Clay,

This is a bug. That clone button shouldn't be visible. Fixing it ASAP.

**Comment by cshirky** [comment]
Thanks. 

Is there a way to allow another Carto user to clone one of my visualizations?

**Comment by javierarce** [comment]
I've removed the fake "clone this" button. I'm afraid right now there's not a direct way to clone a visualization :(
