### ISSUE TITLE
Routes and other modifications with the new dashboard

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2256]
- username.cartodb.com should redirect to the user dashboard in the maps view if the user is logged in.
- username.cartodb.com should redirect to the public user dashboard in the maps view if the user is not logged in.
- username.cartodb.com should redirect to the public user dashboard in the maps view if the username is not the user's username.

**Comment by xavijam** [comment]
That doesn't belong to the frontend code, a backend guy should take care of this.
cc @Kartones @juanignaciosl @javisantana

**Comment by Kartones** [comment]
I can take care of this, routes are my old friends. But yes, this are Rails responsabilities

**Comment by Kartones** [comment]
New path `/maps` shows your public profile's maps page, as now the index path `/` performs redirects according to specified settings above, so current menu link doesn't works:
![](http://comomonos.com/up/link_looping.png)

@viddo, @xavijam pointed me to you to change it, could you do it in this branch whenever possible? Afterwards I'll release the branch myself.

**Comment by viddo** [comment]
Since I'm changing how the URLs are created #2542 I would prefer to either do this fix there, or fix it after that is done, to avoid double work. ETA today (unless I run into unexpected trouble).

**Comment by Kartones** [comment]
Fine by me, then I'll PR this and push after lunch. is not such a big thing and if your ETA is today or tomorrow...

**Comment by viddo** [comment]
Agree, I'll adhere to the new URL in my branch and it will get fixed promptly. :+1:
