### ISSUE TITLE
Support more URLs as ArcGIS Servers

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#2300]
For example:

`/gis/rest`and not just `/arcgis/rest`

The first one is raising the following error:

````
DataImport['991f5d67-1b81-444c-88cb-ccc4a86c6c30'].log
=> #<CartoDB::Log @values={:id=>"6e0e0fdd-2f7c-4272-9b15-9d34ee85695f", :type=>"import", :user_id=>"b9f868bc-aeba-4789-8448-a4ec9eaba1da", :created_at=>2015-02-18 09:13:37 +0000, :updated_at=>2015-02-18 09:13:37 +0000, :entries=>"2015-02-18 09:13:37 UTC: Running on server que05.useb with PID: 26086\n2015-02-18 09:13:37 UTC: new_importer()\n2015-02-18 09:13:37 UTC: Fetching datasource <CartoDB::Datasources::Url::ArcGis @url= @metadata= @ids_total=0 @ids_retrieved=0 current_block_size=0> metadata for item id ********\n2015-02-18 09:13:37 UTC: Additional error info: Url doesn't looks as from ArcGIS server\n2015-02-18 09:13:37 UTC: After dispatch\n2015-02-18 09:13:37 UTC: ERROR!\n\n"}
````

**Comment by michellechandra** [comment]
Another URL example to support:

arcgis_web_adaptor/rest

Raises error: Url doesn't look as from ArcGIS server

**Comment by iriberri** [comment]
Hm, with a quick look, it seems this matches current rule: https://github.com/CartoDB/cartodb/blob/master/services/datasources/lib/datasources/url/arcgis.rb#L313

**Comment by iriberri** [comment]
I have this almost done: https://github.com/CartoDB/cartodb/pull/6217

I'm still finishing some tests, but next week (Wednesday, as it's holidays in Spain) this should be live.

**Comment by iriberri** [comment]
@michellechandra done! :)

**Comment by michellechandra** [comment]
@iriberri - thanks, will update the user! :)

**Comment by michellechandra** [comment]
hey @iriberri - there is another ArcGIS url that is throwing an error: "Url doesn't looks as from ArcGIS server", should I reopen this issue?

The form of the URL is:
http://hostname/landscope4/rest/services/blahblah/blahblah/MapServer/0

**Comment by iriberri** [comment]
Feel free to reopen!

**Comment by michellechandra** [comment]
thanks @iriberri - let me know if you need more information about the URL

URL is:
http://hostname/landscope4/rest/services/blahblah/blahblah/MapServer/0

S/B 8166234

**Comment by iriberri** [comment]
@rafatower I took a look at the complete URL that Michelle mentions and it's a legit one, but we are restricting it [here](https://github.com/CartoDB/cartodb/blob/1f3a735deda7c63f3531c7674e7722ae0b464839/services/datasources/lib/datasources/url/arcgis.rb#L17), as we're expecting for it to match with a list of "valid arcgis webservers" which we keep editing by ourselves. Do you agree with removing this restriction? If we want to be a little bit more picky we could also check in the URLs terms such as "MapServer", "FeatureServer" or "FeatureLayer".

**Comment by iriberri** [comment]
http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/Getting_started/02r3000000sq000000/


> When using the REST API, you must know the well-known endpoint, which represents a server catalog.

>For ArcGIS for Server, the default endpoint is as follows:
http://:host/:site/rest/services/:folder/:serviceName/:serviceType

>Where:

>http://:host is the ArcGIS for Server host name.

>**/:site is the site name. The default value is "/arcgis/". ArcGIS for Server accepts a site name specified in a URL as lowercase (arcgis) or camel case (ArcGIS). Using an all lower case site name is the recommended option.**

>**rest/services indicates the REST services endpoint. You'll see a list of all services in the root directory along with any folders. This part of the URL is case sensitive and should be specified in all lowercase.**
[...]

**Comment by iriberri** [comment]
@michellechandra a fix is prepared here: https://github.com/CartoDB/cartodb/pull/6706

As soon as it's reviewed and accepted we can deploy it, so keep an eye on the status of the PR: whenever it's closed it'll mean that the issue will be fixed in production.
