### ISSUE TITLE
Design visual merge modal window

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2310]

**Comment by carlostallon** [comment]
![01 merge](https://cloud.githubusercontent.com/assets/1712650/6506352/c57c6e10-c34a-11e4-973a-95ac0bc23e8b.png)
![02 merge step 1](https://cloud.githubusercontent.com/assets/1712650/6506353/c57cb014-c34a-11e4-8939-49b73f53d249.png)
![03 merge step 2](https://cloud.githubusercontent.com/assets/1712650/6506351/c57bbc86-c34a-11e4-96e1-4eb7e628b943.png)
![04 mergeg step 2b](https://cloud.githubusercontent.com/assets/1712650/6506354/c57f498c-c34a-11e4-815e-f34a6d9a2de1.png)

More mocks in .../webapp/Merge-tables/

**Comment by saleiva** [comment]
- Love the icons, dude, they are pretty good. Not sure if the spatial one is reflecting anything spatial but it works.
- The first screen looks very empty, don't you think?
- In general I think that we are loosing a beautiful opportunity to explain how a merge works.

**Comment by piensaenpixel** [comment]
+ 1 to the third point
"In general I think that we are loosing a beautiful opportunity to explain how a merge works."
 i think we need something different
