### ISSUE TITLE
Conflict with buttons in the APi keys and the oAuth pages

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2311]
![screen shot 2015-02-18 at 12 23 42](https://cloud.githubusercontent.com/assets/132149/6246422/0b0aac5a-b769-11e4-97fb-a26f2cea9b48.png)

If you are a paid user there is a conflict when scanning the page visually between the generate again and the support button.

**Comment by saleiva** [comment]
+ visual hierarchy is a bit weird when rendering on the browser

**Comment by carlostallon** [comment]
![user config - api keys 4](https://cloud.githubusercontent.com/assets/1712650/6265157/42bad27a-b82b-11e4-84e0-ffde2067b17e.png)

**Comment by saleiva** [comment]
This means redesigning that module on every screen. In the ones like the
dashboard we should try this before applying..

**Comment by saleiva** [comment]
bump!

**Comment by carlostallon** [comment]
Mixing things that we talked and worked before, two new versions for free and paid users using the same visual language, so now:
- much more clear and readable info than before
- Conflict with buttons avoided
- better integration with the general new UI
- Paid users get the Enterprise support module and free users the module with links to documentation.

![user config - api keys - free user](https://cloud.githubusercontent.com/assets/1712650/6354083/93b6796a-bc4d-11e4-94a9-0432e8c45984.png)
![user config - api keys - paid user](https://cloud.githubusercontent.com/assets/1712650/6354084/93cfcb04-bc4d-11e4-8d79-f782a5b396e5.png)

**Comment by carlostallon** [comment]
Bump!

**Comment by saleiva** [comment]
I liked so much the other version (the one that you posted first)

**Comment by carlostallon** [comment]
Ok, too noisy to me, but what do you think about this version, is the same but simpler

![user config - api keys with enterprise support](https://cloud.githubusercontent.com/assets/1712650/6488467/0dfc2ab2-c298-11e4-89aa-c1accf97c17d.png)

**Comment by saleiva** [comment]
My fav, although we should try how it looks like in the maps / datasets view

**Comment by carlostallon** [comment]
![dashboard - user private - base](https://cloud.githubusercontent.com/assets/1712650/6506253/e347b46e-c349-11e4-8e64-afa07b1c6949.png)

![dashboard - user private - maps base](https://cloud.githubusercontent.com/assets/1712650/6506254/e36032d2-c349-11e4-95a6-5c9c2ebf5afe.png)

**Comment by saleiva** [comment]
:+1:

**Comment by xavijam** [comment]
:(

**Comment by saleiva** [comment]
WHAT?

**Comment by saleiva** [comment]
hey @xavijam can @matallo start with this on the central pages, so the markup is created for the dashboard and so on?

**Comment by xavijam** [comment]
ok

**Comment by xavijam** [comment]
Please @matallo, could you take care of this thing in central and editor?

**Comment by matallo** [comment]
@xavijam if I finish with my current milestone issues, of course mate

**Comment by saleiva** [comment]
tallon, please prioritize this! we need to finish the new dashboard ASAP

**Comment by xavijam** [comment]
@matallo, I've done it, but I need you to "add" it in the plans page in central, ok?

**Comment by matallo** [comment]
sure thing

**Comment by matallo** [comment]
https://github.com/CartoDB/cartodb-central/pull/555
