### ISSUE TITLE
When being in any configuration page remove the arrow from the breadcrump

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2312]
It's weird that you can navigate using that to places where you will not be able to do the same for going back.

**Comment by viddo** [comment]
agree, but just to be clear, by "_remove the arrow_" you mean removing the dropdown menu too, right?

**Comment by viddo** [comment]
i.e. like this? ![screen shot 2015-02-19 at 12 16 26](https://cloud.githubusercontent.com/assets/978461/6265691/2f5f286a-b831-11e4-86bd-8f493b58fe31.png)

**Comment by xavijam** [comment]
It should appear as selected, more "whiter", with no underline.

**Comment by saleiva** [comment]
Yep
