### ISSUE TITLE
Review responsive version within new public dashboard

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#2315]
- [x] Don't apply responsiveness to private dashboard.
- [x] Public datasets
- [x] Public maps

**Comment by javierarce** [comment]
[] Make the empty screen responsive

**Comment by viddo** [comment]
Shouldn't the metadata be on one line in "desktop" mode?

On public:
![screen shot 2015-03-12 at 18 29 58](https://cloud.githubusercontent.com/assets/978461/6623881/023e48d2-c8e6-11e4-9e21-b67d459fea42.png)

On private:
![screen shot 2015-03-12 at 18 30 55](https://cloud.githubusercontent.com/assets/978461/6623880/023db6e2-c8e6-11e4-85ca-13797c988b0b.png)

**Comment by javierarce** [comment]
@viddo: yep, I totally broke that. I'll fix it, thanks!

**Comment by xavijam** [comment]
Merged, so, next issues, in a different one.
