### ISSUE TITLE
Using Image export on Torque maps gives an error

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#2320]
![screen shot 2015-02-18 at 11 02 14 am](https://cloud.githubusercontent.com/assets/370259/6250707/ae309842-b75d-11e4-82b9-85a59e3c17fb.png)

related https://github.com/CartoDB/cartodb/pull/2199#issuecomment-74838769

**Comment by javierarce** [comment]
@andrewxhill: can you paste or send me the link to the vizjson, please?

**Comment by andrewxhill** [comment]
http://team.cartodb.com/api/v2/viz/13062538-b129-11e4-a9f5-0e9d821ea90d/viz.json

**Comment by javierarce** [comment]
Ok, that's related with this ticket: https://github.com/CartoDB/cartodb.js/issues/354 and another bigger issue we are talking in the email.

**Comment by andrewxhill** [comment]
great thanks!


On Wed, Feb 18, 2015 at 11:50 AM, Javier Arce <notifications@github.com>
wrote:

> Ok, that's related with this ticket: CartoDB/cartodb.js#354
> <https://github.com/CartoDB/cartodb.js/issues/354> and another bigger
> issue we are talking in the email.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/2320#issuecomment-74899616>.
>



-- 

andrewxhill <http://twitter.com/andrewxhill>
http://cartodb.com

**Comment by javierarce** [comment]
I didn't notice this was a torque_heat. @rochoa, @fdansv: you were working on a fix for this, right? Is there an issue for that already?

**Comment by rochoa** [comment]
This will be sorted here: https://github.com/CartoDB/torque/issues/131

**Comment by rochoa** [comment]
Once we release https://github.com/CartoDB/Windshaft/issues/271 (today or tomorrow) at least it won't fail (although the heatmap won't be displayed).

**Comment by rochoa** [comment]
This took longer than expected but we finally solved the issue and improved torque server side by using a buffer for the queries :-)

![811](https://cloud.githubusercontent.com/assets/45346/6556246/90a69cf4-c66c-11e4-825a-f07c37dc94ec.png)

**Comment by javierarce** [comment]
\o/

**Comment by andrewxhill** [comment]
wowza

On Mon, Mar 9, 2015 at 7:20 AM, Javier Arce <notifications@github.com>
wrote:

> \o/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/2320#issuecomment-77861449>.
>



-- 

andrewxhill <http://twitter.com/andrewxhill>
http://cartodb.com
