### ISSUE TITLE
Investigate ENOENT error, CartoCSS assets

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#2322]
From SB/4548654

https://cartocdn.global.ssl.fastly.net/travelfindz/api/v1/map?stat_tag=API&lzma=3YCAiIDXkoCAgICAgIC9CAjntIUbMkyt4S6xq5e%2FtuZxRdm36Q9i%2Bh2dFl3Yj4PkbU4JSD14a4JTZxm6KJtzYEiv7YQtAwbkgxjAexaWxmJPY0ZMYjBvQ0H9FPupuVzd36r0xK9Wh3vTwNKTYhw365snxwR9uB%2BLJOEIhvixCKa0Ng3Bd7XZA1%2FipmR4E6HWH3XGDSn7FEBPZoKG56CW8mpRk%2FWTnu%2FMrE1cSe5ChAqWaLaKmyDhKS%2BaVznt%2FuF4VMzycd%2B3jgcvgWsmvDFf%2F7HUJgatVZX1tT26yjH78lLWKHz56qIcYrEPGdFcNNqdOPEj4HmH91HsFo5VZL0xzWnHzXniFcdHXG20jRZYTZn3P250MuOj9CPIQTh7u1cn1VRKfJX56mt%2BxLOBMC24uwR7hkmcE9Ow8KnakI%2BW0Fs3LwPVqTxBLyCf8Gr%2F2NGRPCrcUAb0lzLK7T2WTlmxNqGMxQw%2FF61zzchvgXfSYqljlgolJhi%2F0XBhkHyQzB%2BK8NvfvsaVLT8QlKMGONQQX%2FxiLwhYVmljyr2vYr8wjwZBbtq5U8n8o0z%2B6olljVJTmR0AbTwEP0fSqIoCkXD8%2BlXvgLglzM%2FMITOYdSr7qpGJP3eriuL9ytNV3qFJXAwfqk%2FXWBWnRfqUXeRFe6lEJ08rfjHfpWL69xmYB93QNRS9qYN4JAi692fz0smdAl1E%2FY4B9dgefjjhKuKbhEjmBuMnY7tWHMQk6Unw4zAzARsjKqeetleR6ZXuNazJetCYGGIu0pGkfOZGEHJVMNSwMSxS2d77sZ5SjvxQf4eE%2Flaoyy1QCzcTOyy7OjuK8VJ4cyap8r%2BdmJaRSfxBAh6Ha7uO6e%2FiOv09IPB3KxE9qb1nU5PtyEhMhc6iqMo1Ab1ZbJYBBWkYio43qL0Eth95i4Q9xBx1p8t%2BXl41v7ke3SWtx%2Bq005oerN0oeps0IoqIJ6lkJ3haBrXjId%2BFHbCUoSbbCGJuEPdPD395QLpMTrF5JKinyxxYO5H%2FTp2l1OKR%2F9TTOmsUfRkQCBxW2BXSwhWS7yC5eTLXB%2BDz5mAulH62ZhIUDoNUpVKQoFHEDvZvvbAcYVE5TvCQ8FcD9kY7BuhtLaZOvSajuOp4ER0xOQstOcBSHu4W7uDTgoDIuhcfJK%2Fca4nl9ldQ4gIYu%2BswOMGgiotHwLz2LV1XzbceJoZiym4rAsXdcrHoiiNPYQ0cBcnLpT2MA4KG7g5nteJLb9w2zA%2BE55ijcPVYlE%2FHs1hdF8yjFpYganUXXJxz4EX95%2FNa2XjcngC0Z%2B%2F3xMJ5ujzjvSDXvx0vpp9%2FADAjAA%3D%3D&callback=_cdbc_1291215404_1

`````
_cdbc_1291215404_1(
{
errors: [
"ENOENT, rename '/home/ubuntu/tile_assets/cache/a111f8c6-uc/a111f8c6-uc'"
]
}
)
``````

**Comment by javisantana** [comment]
a layergroup passing through the cdn?

**Comment by rochoa** [comment]
It is using `dynamic_cdn`:
```js
cartodb.createLayer(map, {
                user_name: config.user,
                type: 'cartodb',
                sublayers: [
                    {
                        sql: config.sql,
                        cartocss: config.css,
                        interactivity: 'lot_number, cdb_list'
                    }
                ],
                https: true,
                tiler_protocol: 'https',
                sql_api_protocol: 'https',
                cors: false,
                dynamic_cdn: true
            }
        )
```

**Comment by rochoa** [comment]
This should be fixed as per https://github.com/CartoDB/Windshaft/issues/274
