### ISSUE TITLE
importer API lacks of file format documentation

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#2329]
An user importing a CSV can't know what columns should use for the geometry columns, what types we guess and so on.

In general:

- add information about all the formats we support with detailed information of what we do for each one, for example
  - KML: import as many tables as layers, we don't use the styles and we expect it in wgs84
  - shp: import as many tables a shp files, we need prj file (if it lacks of it we use [WGS84](http://epsg.io/4326) )...
  - csv: there should be a the_geom column (optionally called, wkb_geometry, geojson,...) the format for that column can be geojson (a single feature), WTK or WTB

- add clear information about encodings and types. How we guess encodings and types

cc @juanignaciosl @Kartones @pramsey

**Comment by rafatower** [comment]
I've just seen the new docs in production and they look really nice ^_^

http://docs.cartodb.com/cartodb-platform/import-api/geospatial-data-formats/#supported-geospatial-data-formats

(minor comment: I'd move the "Dataset Basics" a bit up, for a future version).

Thanks @iriberri and @csobier 

closing this for the moment

**Comment by csobier** [comment]
I'll move it up right now (and move it underneath the supported format section).
