### ISSUE TITLE
Almost unreadable texts

### ISSUE THREAD

**Issue by Kartones** [CartoDB/cartodb#2335]
With Linux at least (and I could bet with Windows will be similar), light grey and light green texts are really really hard to read... not sure if because of the combo bright+small or just bright but...

![](http://www.comomonos.com/up/cant_read_02.png)

![](http://www.comomonos.com/up/cant_read_03.png)

/cc @saleiva Reassign if @carlostallon doesn't knows how to do CSS anymore :trollface:

**Comment by carlostallon** [comment]
I'm having troubles also in IE6 @kartones

**Comment by Kartones** [comment]
There I can help you: https://www.modern.ie/en-us

**Comment by carlostallon** [comment]
I'm updating the mockups removing the "light" fonts. It doesn't work well with font size > 13

**Comment by carlostallon** [comment]
Please @xavijam @viddo @matallo is possible to remove all the light fonts in the new dashboard and replace to the regular ones? This font doesn't renders well in old OS like Windows when the typography is under 13px...

**Comment by viddo** [comment]
Is it only a matter of changing the font-weight to the default one? Or do you imply something more?

**Comment by carlostallon** [comment]
Yes, I think we can solve it only changing the font-weight across the CSS

**Comment by viddo** [comment]
Not sure I'll have time to do it, but I can reassign the issue for me for now, hopefully should get to it sometime next week.
