### ISSUE TITLE
Creating map with common data

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2336]
When creating a map with data from the data library it shouldn't be imported like it is right now. The user should follow the same flow than creating a map with his own data. 

You select, data gets imported and visualization gets created. Also interaction should be the same.

**Comment by xavijam** [comment]
That's not possible, we have to import first the data library to his/her account before creating a new map.
I don't get what you want sorry.

**Comment by saleiva** [comment]
After importing you are not being redirected to the new map, you are being redirected to the table view.
You should be redirected to the map view, the same than with normal files

**Comment by xavijam** [comment]
https://github.com/CartoDB/cartodb/issues/2457 duplicated?

**Comment by saleiva** [comment]
could be yeah.

**Comment by saleiva** [comment]
you can close this one then

**Comment by xavijam** [comment]
Duplicated #2457 :dancer:
