### ISSUE TITLE
Allow changing privacy in dashboard by clicking on the actual status.

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#2337]
![image](https://cloud.githubusercontent.com/assets/1730320/6268102/56a1b064-b84a-11e4-850a-0c99826ce0b5.png)

and not just by selecting the dataset and clicking on "Change privacy" in the top toolbar.

**Comment by viddo** [comment]
duplicate of #2061, added datasets to the scope of the other issue, thx :)
