### ISSUE TITLE
A zip containing a shp and a txt only imports txt

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#2349]
If you add a .txt to the zip that contains shp files, only the txt is imported (at least, with a filename that is lexicographically before than the rest of the files).

@iriberri is this a known issue? It's strange I've spotted it.

**Comment by iriberri** [comment]
There is (or was) a similar issue about importing a file which contained a KML and another file, and only one of them was imported, but I think this is unrelated and was provoked by another issue (I think it was the bikelanes kml).

**Comment by juanignaciosl** [comment]
Bikelanes kml issue is covered by #2044 indeed, although we're beginning to experiment with different approaches for layer-intensive files // @danicarrion .

**Comment by iriberri** [comment]
We solved this with multi-file importing during the last months.
