### ISSUE TITLE
Connect dataset typo

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#2350]
Only Dropbox option contains a trailing point on the description:

![image](https://cloud.githubusercontent.com/assets/1730320/6269035/1e07d5ba-b851-11e4-90b2-de92cc0c0d80.png)

The rest doesn't :-)

**Comment by xavijam** [comment]
https://github.com/CartoDB/cartodb/commit/b9fc18efafff551366b28c8165d41fef8a567ff4
