### ISSUE TITLE
In the connect dataset modal when creating a map scrollbar is shown but not needed

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2353]
![screen shot 2015-02-19 at 16 11 20](https://cloud.githubusercontent.com/assets/132149/6269209/044f1a60-b852-11e4-8749-16693d63c84e.png)

**Comment by xavijam** [comment]
https://github.com/CartoDB/cartodb/commit/93ed4da3070b7124f1e5e605242868a242be4cfe
