### ISSUE TITLE
Scrollbar get cut

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2354]
In the create map modal window

![screen shot 2015-02-19 at 16 12 29](https://cloud.githubusercontent.com/assets/132149/6269236/2c52d2ae-b852-11e4-9df9-2407419ca22f.png)

**Comment by xavijam** [comment]
https://github.com/CartoDB/cartodb/commit/93ed4da3070b7124f1e5e605242868a242be4cfe
