### ISSUE TITLE
CartoDB version on Google Cloud should have a slightly modified logo to express that.

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2359]

**Comment by carlostallon** [comment]
![gme header](https://cloud.githubusercontent.com/assets/1712650/6483183/5cccf376-c26e-11e4-8811-bee0ee7afdb1.png)

**Comment by saleiva** [comment]
ossom.

**Comment by saleiva** [comment]
Assigning to @javisantana so we implement this

cc/ @jatorre

**Comment by iriberri** [comment]
Moved from El Soto to Baeza.

**Comment by saleiva** [comment]
@jatorre what do we do with this?

**Comment by jatorre** [comment]
What do you need from me?

**Comment by saleiva** [comment]
To know if we finally implement this and to say if with that change in the logo would be enough

**Comment by jatorre** [comment]
I would prefer something more obvious, but it is up to you. Ideally it should be really clear this is a CartoDB on Google Cloud Platform product.

My desire is that people identify without issues the fact that they are in one platform or another.

Regarding if we implement it, nothing has changed, yes definitely needed.

**Comment by saleiva** [comment]
@carlostallon , fancy iterating on this a bit more?

**Comment by saleiva** [comment]
(maybe adding google colors to the box?)

**Comment by carlostallon** [comment]
Yes, sure, i will send more iterations

**Comment by saleiva** [comment]
Bump!

**Comment by carlostallon** [comment]
Take a look
![captura de pantalla 2015-04-08 18 19 27](https://cloud.githubusercontent.com/assets/1712650/7049703/dc678506-de1b-11e4-83b9-27b1ebb27ffd.png)

**Comment by saleiva** [comment]
which sketch file is this @carlostallon ?

**Comment by carlostallon** [comment]
Projects / webapp / 09 Header for GME

2015-04-27 15:00 GMT+02:00 Sergio Álvarez Leiva <notifications@github.com>:

> which sketch file is this @carlostallon <https://github.com/carlostallon>
> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/2359#issuecomment-96641959>.
>



-- 
Carlos Tallón
Designer

Vote for CartoDB to get a Webby!
<http://pv.webbyawards.com/2015/web/general-website/web-services-applications>

**Comment by saleiva** [comment]
Done in Header-for-GME-0.2

**Comment by xavijam** [comment]
:+1:

**Comment by xavijam** [comment]
Should it be visible in the public pages?

**Comment by saleiva** [comment]
Nope
