### ISSUE TITLE
Share public map - password

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#2362]

**Comment by piensaenpixel** [comment]
Hi take a look cc/ @saleiva @carlostallon 
![password](https://cloud.githubusercontent.com/assets/1214201/6353909/4f496090-bc4c-11e4-9568-5f1edc090025.png)

**Comment by saleiva** [comment]
Is the button border grey??

**Comment by piensaenpixel** [comment]
Yes sorry it was grey :(

![password](https://cloud.githubusercontent.com/assets/1214201/6367682/083aa01c-bcd6-11e4-95ec-525eabfb9dbb.png)

**Comment by piensaenpixel** [comment]
Added in 01-Public-Maps/public-map-dataset-2.0.sketch
