### ISSUE TITLE
Fixes on Share with your colleagues modal

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2363]
There is an horizontal scrollbar that is not being used.
The grey button shouldn't have white bkg.
"Share with your XX colleages" should be something like "Select your colleagues you want to give access in the list below"

![screen shot 2015-02-19 at 17 01 55](https://cloud.githubusercontent.com/assets/132149/6270290/17885e28-b859-11e4-8628-9f8f2363f4c4.png)

**Comment by saleiva** [comment]
After thinking a bit more on this I think we should remove the "header with the arrow" and add the arrow on the modal header like it is on the create map modal for example.

**Comment by viddo** [comment]
I think that's reasonable, but if we remove that header where do we put the copy change you propose (_select your colleagues..._)? in the header subtitle?

**Comment by saleiva** [comment]
in the white header. Where it talks about open data and so on...
