### ISSUE TITLE
When having a map/dataset shared with some users we should show it on the privacy modal

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2365]
It was designed, right?
Also when not having any user, we shouldn't show the small number as it looks the number of users with access to that item.

![screen shot 2015-02-19 at 17 04 35](https://cloud.githubusercontent.com/assets/132149/6270348/8ade9298-b859-11e4-895f-253675a04460.png)

**Comment by viddo** [comment]
There is no screen for it, and it's not implemented ATM. Should it be the same as on delete items? 
![screen shot 2015-02-19 at 18 43 56](https://cloud.githubusercontent.com/assets/978461/6272364/5739f1fe-b867-11e4-95f2-f84afa15868c.png)

**Comment by viddo** [comment]
Based on what we discussed in person (can't find and summary in the previous PRs), we concluded that privacy option do not affect other users. What we did design and implement was if read/write access was revoked but inline, like this:
![screen shot 2015-02-19 at 18 43 16](https://cloud.githubusercontent.com/assets/978461/6272405/9ac5a616-b867-11e4-8cb4-a4a15a4b04ed.png)
Has this changed?

**Comment by saleiva** [comment]
1. Yes we should use that design
2. No, that didn't change!

**Comment by viddo** [comment]
Ok, so then the only thing to fix for this issue would be _when not having any user, we shouldn't show the small number as it looks the number of users with access to that item_, right?

**Comment by saleiva** [comment]
Yep
