### ISSUE TITLE
Cannot start import from ArcGIS Online

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#2369]
I'm adding the URL (https://maps.brgov.com/gis/rest/services/Governmental_Units/Police_District/MapServer/0) but there's no option to accept, or confirm. 

Pressing enter is just getting rid of the connect dataset modal.

**Comment by xavijam** [comment]
It should be fixed with https://github.com/CartoDB/cartodb/pull/2370

**Comment by iriberri** [comment]
Awesome :smiley_cat:

**Comment by xavijam** [comment]
Closing due to it is fixed thanks to https://github.com/CartoDB/cartodb/pull/2370.
