### ISSUE TITLE
Grunt fails on clinker, cartodb.js not updated (due to make[1]: Entering directory 

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#2377]
Has happened since at least a few days back, these builds failed completely:
- http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1797/console
- http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1793/console
- http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1784/console
- http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1774/console
- http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1771/console
- http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1744/console
- http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1742/console
- http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1688/console
- http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1650/console
- http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1648/console

These also have the same error but continued with the build:
- http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1645/console
- http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1644/console
- http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1641/console
- http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1640/console
- ..
- (stopped looking from here on)

```bash
...
08:57:58 Running "cdb" task
08:57:59 cartodb.js not updated (due to make[1]: Entering directory `/home/administrador/jenkins/workspace/CartoDB-PR-testing'
08:57:59 cd lib/assets/javascripts/cdb; make cartodb dist/cartodb.css
08:57:59 make[2]: Entering directory `/home/administrador/jenkins/workspace/CartoDB-PR-testing/lib/assets/javascripts/cdb'
08:57:59 mkdir -p dist
08:57:59 cat vendor/mod/carto.js vendor/mod/torque.uncompressed.js src/geo/gmaps/torque.js src/geo/leaflet/torque.js src/geo/ui/time_slider.js      vendor/mod/jquery-ui/jquery.ui.core.js vendor/mod/jquery-ui/jquery.ui.widget.js vendor/mod/jquery-ui/jquery.ui.mouse.js vendor/mod/jquery-ui/jquery.ui.slider.js     scripts/mod.torque.footer.js > dist/cartodb.mod.torque.uncompressed.js
08:57:59 grunt dist_js
08:57:59 >> Local Npm module "grunt-autoprefixer" not found. Is it installed?
08:57:59 >> Local Npm module "grunt-build-control" not found. Is it installed?
08:57:59 >> Local Npm module "grunt-concurrent" not found. Is it installed?
08:57:59 >> Local Npm module "grunt-contrib-clean" not found. Is it installed?
08:57:59 >> Local Npm module "grunt-contrib-compass" not found. Is it installed?
08:57:59 >> Local Npm module "grunt-contrib-concat" not found. Is it installed?
08:57:59 >> Local Npm module "grunt-contrib-connect" not found. Is it installed?
08:57:59 >> Local Npm module "grunt-contrib-copy" not found. Is it installed?
08:57:59 >> Local Npm module "grunt-contrib-csslint" not found. Is it installed?
08:57:59 >> Local Npm module "grunt-contrib-cssmin" not found. Is it installed?
08:57:59 >> Local Npm module "grunt-contrib-htmlmin" not found. Is it installed?
08:57:59 >> Local Npm module "grunt-contrib-imagemin" not found. Is it installed?
08:57:59 >> Local Npm module "grunt-contrib-jshint" not found. Is it installed?
08:57:59 >> Local Npm module "grunt-contrib-uglify" not found. Is it installed?
08:57:59 >> Local Npm module "grunt-replace" not found. Is it installed?
08:57:59 >> Local Npm module "grunt-contrib-watch" not found. Is it installed?
08:57:59 >> Local Npm module "grunt-contrib-jasmine" not found. Is it installed?
08:57:59 >> Local Npm module "grunt-filerev" not found. Is it installed?
08:57:59 >> Local Npm module "grunt-svgmin" not found. Is it installed?
08:57:59 >> Local Npm module "grunt-usemin" not found. Is it installed?
08:57:59 >> Local Npm module "grunt-prompt" not found. Is it installed?
08:57:59 >> Local Npm module "grunt-aws" not found. Is it installed?
08:57:59 >> Local Npm module "grunt-fastly" not found. Is it installed?
08:57:59 >> Local Npm module "grunt-gitinfo" not found. Is it installed?
08:57:59 Loading "Gruntfile.js" tasks...ERROR
08:57:59 >> Error: Cannot find module 'time-grunt'
08:57:59 Warning: Task "dist_js" not found. Use --force to continue.
08:57:59 
08:57:59 Aborted due to warnings.
08:57:59 make[2]: Leaving directory `/home/administrador/jenkins/workspace/CartoDB-PR-testing/lib/assets/javascripts/cdb'
08:57:59 make[1]: Leaving directory `/home/administrador/jenkins/workspace/CartoDB-PR-testing'
08:57:59 , make[2]: * [dist/cartodb.mod.odyssey.uncompressed.js] Error 3
08:57:59 make[1]: * [update_cdb] Error 2
08:57:59 )
08:57:59 Task 'cdb' took 635ms
```

But the [dist_js](https://github.com/CartoDB/cartodb.js/search?utf8=%E2%9C%93&q=dist_js) task do exist, seems to fail due to something failing earlier on in that cdb task.

**Comment by viddo** [comment]
@CartoDB/frontend this has been going on for at least a few days and now seem to break builds randomly. Seems to be an issue with the cdb submodule and the grunt task. Anyone has any idea on what might have changed related to this?

**Comment by viddo** [comment]
Actually this error (even if it stats "Aborted due to warnings" the task 'cdb' finishes and the rest of the build can still continue to work, e.g. see [latest working build on clinker](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/1834/console) (at this point in time). IMHO we should not have failing tasks in the build however, can someone that works regularly on cartodb.js confirm what this error might be of?

The builds that fail are due to browserify, i.e. 
```bash
...
Running "browserify:new_dashboard" (browserify) task
00:01:30.649 >> Error: Cannot find module 'new_dashboard/router' from '/home/administrador/jenkins/workspace/CartoDB-PR-testing/lib/assets/javascripts/cartodb/new_dashboard'
00:01:30.651 Warning: Error running grunt-browserify. Use --force to continue.
00:01:30.652 
00:01:30.653 Aborted due to warnings.
00:01:30.661 make: *** [check-frontend] Error 6
00:01:30.678 Build step 'Execute shell' marked build as failure
..
```

So far only @xavijam have been able to reproduce it locally, and it was fixed by removing npm_modules directory and re-run `npm install` (unfortunately don't have a backup so we could do a diff to see what changed). My guess right now is that something got changed in some browserify-related package which we have installed locally but which is not installed on clinker. I'll try to update the browserify version we have set right now and see fi I can provoke this on a PR (we'll need to update sooner or later anyway so might as well do it now).

**Comment by matallo** [comment]
I was sable to reproduce while setting the vagrant dev enviroinment; after clone the repo `grunt` tasks won't work out of the box, you have to:

- git submodule init
- git submodule update

but it'll keep failing, then `cd lib/assets/javascripts/cdb` showed cartodb.js was not in develop, but in a detached sha

- `git checkout develop`
- `git pull`

back to cartodb and `grunt` showed grunt tasks weren't installed `cd lib/assets/javascripts/cdb` again and

- `npm install`

in my case I hadn't bundler and compass installed so I had to proceed, too. After that grunt task worked like a charm.

not sure if completely related but errors prompted were the same, I hope it helps.

ps: related to this issue https://github.com/CartoDB/cartodb.js/issues/367 shouldn't we bundle a built version of cartodb.js? It doesn't quite make a lot of sense to me to build cartodb.js in a cartodb task (I understand why, though)

**Comment by javisantana** [comment]
yes, the problem is that modules inside cdb are not installed. Tried to fix this here (https://github.com/CartoDB/cartodb/commit/4127edf96542c1e92c95153709bbba27f6602a99) but I hit another problem: some compass realted thing is not installed so it's not working

The tests are passing just because we upload the cartodb.compressed.js

the fix here would be to install the stuff needed server side (in clicker)

**Comment by viddo** [comment]
Compass 0.12.3 seems to be required for the CSS build to work, as set in the Gemfile: https://github.com/CartoDB/cartodb/blob/master/Gemfile#L37-L39 but on cartodb.js there is a more recent version set: https://github.com/CartoDB/cartodb.js/blob/develop/Gemfile Perhaps needs to add bundle install as well?

**Comment by fullofcaffeine** [comment]
Why is the need to fetch git submodules not documented in the README file?

**Comment by viddo** [comment]
@fullofcaffeine Because it is not necessary to do if following [How do I install cartodb](https://github.com/CartoDB/cartodb#how-do-i-install-cartodb), not sure @matallo did that one, because I can't reproduce his scenario explained above). More specifically: `$ git clone --recursive https://github.com/CartoDB/cartodb.git`, where the `--recursive` flag is explained in the [git man pages](http://git-scm.com/docs/git-clone):

> --recursive
--recurse-submodules
After the clone is created, initialize all submodules within, using their default settings. This is equivalent to running git submodule update --init --recursive immediately after the clone is finished. This option is ignored if the cloned repository does not have a worktree/checkout (i.e. if any of --no-checkout/-n, --bare, or --mirror is given)

Feel free to send a PR if you think it needs further clarification.

**Comment by viddo** [comment]
Closing since this err finally got fixed on cartodb.js
