### ISSUE TITLE
Small quota bar is missing on the Account pages

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2381]
for you to dispatch 
![screen shot 2015-02-20 at 11 31 05](https://cloud.githubusercontent.com/assets/132149/6284749/fa135456-b8f3-11e4-9b5a-73c4169dfdb6.png)

**Comment by xavijam** [comment]
I talk about it with @carlostallon and it seemed not to be a final thing. Anyways, easy to get back.

**Comment by saleiva** [comment]
hey @carlostallon I loved that, why not?

**Comment by carlostallon** [comment]
I like it, and there are no plans to change it : ) so, ready to go IMO
