### ISSUE TITLE
Error while exporting image with Torque heat maps visualisation

### ISSUE THREAD

**Issue by miguelarias** [CartoDB/cartodb#2384]
There was an error exporting the image
TorqueRenderer: syntax error at or near ")"

**Comment by saleiva** [comment]
I think this is duplicated, @iriberri @fdansv can you confirm?

**Comment by iriberri** [comment]
This is a known bug, Torque is not working yet with Static Maps API afaik.

cc @rochoa @javierarce

**Comment by javierarce** [comment]
Yep: https://github.com/CartoDB/cartodb/issues/2320

It's fixe here: https://github.com/CartoDB/cartodb.js/issues/354 and waiting for a PR review here: https://github.com/CartoDB/cartodb.js/pull/356

**Comment by rochoa** [comment]
Torque works but, as Javi said, the integration has a pending fix :+1:

**Comment by rochoa** [comment]
What I'm not sure is if heatmaps are gonna work because of the assets it uses not being available in node.

**Comment by javierarce** [comment]
@miguelarias: could you share the URL of the map (or the vizjson URL) with us so we can confirm it was fixed, please?

**Comment by javierarce** [comment]
I'm going to close this since it's duplicated here: https://github.com/CartoDB/cartodb/issues/2320
