### ISSUE TITLE
Prepare email for inviting people to use the new dashboard

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2395]
It should be something for the first users we activate the new dashboard.

cc / @vuxita @andrewxhill @brittanymicek

**Comment by vuxita** [comment]
hey! 

Just a couple of questions:
- Can we see the features or design of the new dashboard? 
- When will this be activated?

We'd need the list of users that will have it activated imported in Mailchimp.

Thanks!
Eva

**Comment by saleiva** [comment]
hey @vuxita what is your cartodb username? I'll activate it right now

**Comment by vuxita** [comment]
it's vuxita, thanks!

**Comment by saleiva** [comment]
Done, enjoy :_)

**Comment by vuxita** [comment]
hey @brittanymicek - do you have access to the new dashboard? So you can start exploring it and we can work on the email content.

**Comment by iriberri** [comment]
Moved from El Soto to Baeza.

**Comment by saleiva** [comment]
Closing this. This will not be needed I think.
