### ISSUE TITLE
Show cool random sentences on loading screens

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2396]
@javierarce I'd kill to use the list you prepare for slack

**Comment by javierarce** [comment]
That's great, but we'll probably need to give attribution to some of the quotes.

**Comment by javierarce** [comment]
Some tests:

![sentence01](https://cloud.githubusercontent.com/assets/4933/6328211/5b263c7c-bb65-11e4-9929-f1d2015f63e7.png)
![sentence02](https://cloud.githubusercontent.com/assets/4933/6328210/5b261f9e-bb65-11e4-9fd9-665495e926c0.png)
![sentences03](https://cloud.githubusercontent.com/assets/4933/6328212/5b27d578-bb65-11e4-8213-ef85efda141c.png)

The last one is too long, we should probably split it in two lines.

**Comment by saleiva** [comment]
YEah, and we should also always split the citations

**Comment by javierarce** [comment]
Just the whole thing in two? Or you mean having the quote in one line and the author in another one?

**Comment by saleiva** [comment]
We should have the author always in a separeted line, right? No matter how long is the quote, which should be also splitted if being too long.

**Comment by javierarce** [comment]
okey-dokey :)
