### ISSUE TITLE
Add submit button near the URL input when connecting a dataset

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2398]
leave the enter thing, but add the button.
28px height, grey style.

**Comment by xavijam** [comment]
https://github.com/CartoDB/cartodb/commit/9c0a70439c589c4d890019dddebfa69df8709401

![screen shot 2015-02-20 at 15 50 14](https://cloud.githubusercontent.com/assets/132146/6288319/5466a718-b918-11e4-9384-0fd91c5e96d9.png)
