### ISSUE TITLE
Available geometries is empty (sometimes) in postal codes georef

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#2400]
**Geocoding by postal codes**

I've been doing a test with a table that contains a column with zipcodes and another column which includes the country in which they are located.

Sometimes, the response for `available geometries` is:

```
[]
```

I've been trying to check why this happens. It's reproducible by creating a new table with a random number in "name", and "Ireland" as description.

![image](https://cloud.githubusercontent.com/assets/1730320/6286990/c090c032-b90d-11e4-8d87-d6989f696a37.png)

If I just change Ireland by Spain:

![image](https://cloud.githubusercontent.com/assets/1730320/6287036/26cacd16-b90e-11e4-8ca1-4c770fa2e0e6.png)

I'm still trying to debug it.

I found this: https://github.com/CartoDB/cartodb/blob/c73390d29323e6132a4338651f07a2244221d7c8/app/controllers/api/json/geocodings_controller.rb#L88

cc @rafatower @juanignaciosl 

UPDATE: Ireland has no data. In cases of mixed countries, those without data should be just ignored, thus geocoding the rest. Also if countries have different kind of data (polygon and points), points should be picked, since we have point data for every country that has polygons.

**Comment by juanignaciosl** [comment]
It seems just a matter of data. [Ireland has not national postal codes yet](http://en.wikipedia.org/wiki/Postal_addresses_in_the_Republic_of_Ireland#Introduction_of_a_national_system) ([news](http://www.rte.ie/news/2013/1008/479116-nationwide-postcode/)). This is [documented in data-services](https://github.com/CartoDB/data-services/tree/master/geocoder/postal-codes) (Ireland code, IE, is missing).

**Comment by iriberri** [comment]
But why there's no possibility to geocode the rest of the data, which contains valid countries?

**Comment by juanignaciosl** [comment]
I haven't checked the multicountry case, reopening.

**Comment by juanignaciosl** [comment]
Ok, we're [returning the type of the geocoding (point or polygon) only if all countries involved have the same type](https://github.com/CartoDB/cartodb/blob/master/app/controllers/api/json/geocodings_controller.rb#L103). Since Ireland has not, adding Ireland will de facto disable geocoding.

We could certainly do better:
a. Do an `or` instead of an `and`. Problem: this would mix geom types.
b. Return one of the available (`polygon` > `point` > none).
c. Tell the user to choose (UI modification required).
d. Warn the user about the problem (UI modification required).

I'd do a), but I'm not sure about implications. What do you think, @iriberri , @rafatower , @xavijam ?

**Comment by iriberri** [comment]
a) In my opinion, mixing geom types is not a good idea atm :-)
b) Nope, this will provoke that every geocoding process where USA, FRA, AUS or CAN were involved (these are the only countries with polygons) won't work correctly: all the other countries would be nulled.

Think that we have points for all the world (except some weird cases), but polygons just for some countries. It makes sense (to me) to always provide the points.  I'd forget about the nulls in the points availability (if there's more than one country).

**Comment by juanignaciosl** [comment]
Crossposting.

@iriberri proposes f) then (simpler that what I thought, since we have points stored). @rafatower , @xavijam do you agree?

**Comment by rafatower** [comment]
+1 to (f) polygon centers if it is not too complex.

**Comment by iriberri** [comment]
Polygons are not important here, I think. In the countries where we have polygons we also have the points, no centroids needed. :-)

**Comment by juanignaciosl** [comment]
Ok, 3 agree, so let's do that: countries without data will be ignored, and in case of mixing polygon and points, points will be loaded.

**Comment by iriberri** [comment]
Yeah, actually, we're *only* returning polygons if all options allow polygons, which doesn't match with the changes in the code. 

It's not that we give priority to points over polygons, is that for the multicountry case, we shouldn't block the points.

````
geometries.append 'point' if points > 0 && points >= polygons
geometries.append 'polygon' if polygons > 0 && polygons >= points
````

Imagine a dataset, with data for USA (points, polygons), France (points, polygons) and Spain (points).

The option "selected" would be polygons in this case, but this will fail because Spain doesn't allow them.

In this case, the & operator works great because we need to find the intersection.


Imagine another dataset, with data for Spain, Italy and Ireland (all points, except for Ireland which is null). The option selected would be "none", because not all of them have points, but this will block totally the georeferenciation. The reasonable output would be returning points here and returning a "false" in `cartodb_georef_status` for all the Ireland rows + the non recognized rows of Spain and Italy.

Both scenarios are different: it's not about mixing geometries but about allowing the georeferenciation for some part of the dataset if the other part is not georeferenciable.

This would be equivalent to returning "false" when something cannot be geocoded meanwhile other rows in the table are geocoded. We just don't have the data for a specific thing, but we allow the rest of the table to be geocoded.

**Comment by juanignaciosl** [comment]
Either you're misunderstanding the code or the code is not doing what I want.

```

> Imagine a dataset (with the code in the commit), with data for USA (points, polygons), France (points, polygons) and Spain (points).
> The option "selected" would be polygons in this case, but this will fail because Spain doesn't allow them.

Nope. In that case `polygons == 2` and `points == 3`, so `points > polygons` and `point` will be the selected option.

> Imagine another dataset (with the old code), with data for Spain, Italy and Ireland (all points, except for Ireland which is null). The option selected would be "none", because not all of them have points, but this will block totally the georeferenciation.

Nope as well. `points == 2`, so `point`is selected.

This (new) code don't prioritise points but the type of data that is more present in the selected countries, and countries without data are no longer a problem, since they are, literally, not counted for the decision.

**Comment by iriberri** [comment]
> Nope. In that case `polygons == 2` and `points == 3`, so `points > polygons` and `point` will be the selected option.

Totally my fault. :+1:
