### ISSUE TITLE
"see all formats" not working

### ISSUE THREAD

**Issue by santisaez** [CartoDB/cartodb#2406]
![see_all_formats](https://cloud.githubusercontent.com/assets/223956/6288821/e8d1e068-b91b-11e4-85dd-b80f7388156c.png)

It's a link to:

http://developers.cartodb.com/documentation/using-cartodb.html#formats_accepted

and then it's redirected to `docs.cartodb.com`:

```bash
$ curl -I http://developers.cartodb.com/documentation/using-cartodb.html#formats_accepted
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Fri, 20 Feb 2015 15:18:23 GMT
Content-Type: text/html
Content-Length: 178
Connection: keep-alive
Location: http://docs.cartodb.com/documentation/using-cartodb.html
```

Seems that `#formats_accepted` anchor has changed to [`#supported-file-formats`](http://docs.cartodb.com/cartodb-editor.html#supported-file-formats)

**Comment by saleiva** [comment]
Hey, closing this since is being fixed in the new dashboad. Thanks!
