### ISSUE TITLE
Prepare splash screens for the new videos

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2414]
- [x] Icons and colors  (@tallon).
- [x] Short descriptions for videos (@auremoser or @andrewxhill ).
- ~~Display key points within the videos (like in attached 2 - @auremoser or @andrewxhill ).~~
- [x] What to do with the videos (@saleiva and @xavijam).
- [x] Review videos (titles, names, etc - @auremoser or @andrewxhill).

**Comment by piensaenpixel** [comment]
@andrewxhill  we need upload these videos (gdrive-onboarding) to vimeo  and pass the url to @javierarce.
Thanks :D

**Comment by andrewxhill** [comment]
crappy conference wifi. sergio has the password if you guys can do it

On Thu, Mar 12, 2015 at 10:38 AM, piensaenpixel <notifications@github.com>
wrote:

> Assigned #2414 <https://github.com/CartoDB/cartodb/issues/2414> to
> @andrewxhill <https://github.com/andrewxhill>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/2414#event-251088290>.
>



-- 

andrewxhill <http://twitter.com/andrewxhill>
http://cartodb.com

**Comment by piensaenpixel** [comment]
Take a look:

- https://vimeo.com/122308079
- https://vimeo.com/122308073
- https://vimeo.com/122308081
- https://vimeo.com/122308083
- https://vimeo.com/122308076

**Comment by andrewxhill** [comment]
@auremoser could you take a peek at these for me and just flag anything that we messed up?

**Comment by auremoser** [comment]
* @namessanti's name is spelled wrong, I believe, in the Choropleth one (https://vimeo.com/122308079).
* So the series is : Choropleth, Add Features Tutorial, Animate Point Data, tornados-torque-tutorial, map local data? Does it matter that this naming is inconsistent or are these just going in as embeds to existing tutorials?
* is @javierarce planning to embed them as iframes or do they need to have that embed enabled in vimeo? vimeo has permissions for this, I think when you enable permissions on the video you can let people share it with an embed...maybe that's not an issue though, feel free to disregard if so.

**Comment by xavijam** [comment]
Further to 2 point, change the name of the title or description is easy, so not problem in our end.
About 3, we are using Vimeo API, so don't worry about permissions and other things, we have tested them and they are working.

**Comment by xavijam** [comment]
Icons and colors done!

![screen shot 2015-03-17 at 12 04 48](https://cloud.githubusercontent.com/assets/132146/6685861/04d4b390-cc9e-11e4-83da-0b416150810d.png)

**Comment by xavijam** [comment]
One thing we have spotted, we should move all needed datasets to a common account (```example``` is ok?), and avoid hosting them in a personal account.

**Comment by xavijam** [comment]
PING!!!!

**Comment by auremoser** [comment]
**Short descriptions for videos (aurelia or andrew).**

1.  Animate Point Data Tutorial (https://vimeo.com/122308076)
**Title**: Animate Point
**Description**: Learn how to make a Torque map to animate a trajectory in under 2 minutes. This tutorial will import time-series data on a cat's movements about a city, and then illustrate how to animate this movement path with Torque via the CartoDB editor.

2. Add Features Tutorial (https://vimeo.com/122308073)
**Title**: Create Your Own Datasets
**Description**: Learn the many ways to create and add data to your maps in CartoDB. This tutorial will review both manual and automated ways to create, update, contribute and adjust datasets by adding ad hoc point, polygon, and line features to CartoDB layers.

3. Map Local Data Tutorial (https://vimeo.com/122308081)
**Title**: Map Your Local World
**Description**: Learn how to map local data using a sample set from Massachusetts GIS. This tutorial will review options for data import, basemap selection, color palette/css coordination, and UI adjustments to create, customize, annotate, and share your map in less than 3 minutes.

4. Choropleth Tutorial (https://vimeo.com/122308079)
**Title**: Create Your First Choropleth
**Description**: Learn how to make a choropleth map with point and polygon data. This tutorial will import US Polygon data from the CartoDB Data Library and Tornado centroid data, illustrating how easy it is to join datasets with column and spatial joins and customize polygons with colors weighted according to your data in about 5 minutes.

5. Tornados Torque Tutorial (https://vimeo.com/122308083)
**Title**: Create a Torque Map
**Description**: Learn how how to build an animated map with time-series data and Torque in the CartoDB editor. This tutorial will review data selection, importing, and map creation with tornado centroid data; viewers will learn how to represents their data with categorial density maps (styled with tornado density measured by magnitude) and categorical torque maps (animating by date, and styled with tornado density measured by magnitude) in less than 5 minutes.

**Comment by xavijam** [comment]
Thanks @auremoser, but those descriptions are not really short. If you check the place where it should be...

![screen shot 2015-03-18 at 17 37 56](https://cloud.githubusercontent.com/assets/132146/6713898/9c8ffba2-cd95-11e4-923e-de8d3b65865a.png)

**Comment by auremoser** [comment]
**Display key points within the videos (like in attached 2 - @auremoser or @andrewxhill ).**
does this mean:
* just the chapter list from each video (there is an "Intro" and "Other interesting data" black screen but otherwise they're not chapterized)?
* an anchor point with a minute reference: like "Create Layer, 1:25) for a jump ahead option?
* or a bullet list of key points to flesh out the Lorem Ipsum in your preview?

**Comment by auremoser** [comment]
O.k., @xavijam pass me a template that I can test, or a character limit?

**Comment by auremoser** [comment]
"Learn how to animate a trajectory in Torque (2 min)" would fit, sorry I wan't sure where the description would figure in this layout, or if you just planned to put it in the body of the vimeo page.

**Comment by auremoser** [comment]
Also, whoever has the vimeo credetials, the "Other interesting data" blackscreen has a title typo in every video: 
Should be "Click on the data library to *find*..."
![screenshot 2015-03-18 12 33 26](https://cloud.githubusercontent.com/assets/1559703/6714036/8a7ccc84-cd6c-11e4-8db3-fbe72385acf4.jpg)

**Comment by xavijam** [comment]
cc @piensaenpixel

**Comment by xavijam** [comment]
Those descriptions are only for new dashboard layout, sorry for not being descriptive :(.

**Comment by piensaenpixel** [comment]
@auremoser it's fixed :)
![image](https://cloud.githubusercontent.com/assets/1214201/6714089/d573239e-cd96-11e4-95a2-5c71fd5cf25a.png)

**Comment by andrewxhill** [comment]
Emilio has the Screenflow files to change those (I hope)

Also, with the design. I don't think it is clear at all that I'm about to
watch a video when I'm looking at that menu. Know what I mean? If I clicked
one of those icons I'd be pretty surprised it is just a video.

On Wed, Mar 18, 2015 at 12:45 PM, Aurelia Moser <notifications@github.com>
wrote:

> Also, whoever has the vimeo credetials, the "Other interesting data"
> blackscreen has a title typo in every video:
> Should be "Click on the data library to *find*..."
> [image: screenshot 2015-03-18 12 33 26]
> <https://cloud.githubusercontent.com/assets/1559703/6714036/8a7ccc84-cd6c-11e4-8db3-fbe72385acf4.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/2414#issuecomment-83053640>.
>



-- 

andrewxhill <http://twitter.com/andrewxhill>
http://cartodb.com

**Comment by xavijam** [comment]
Don't worry about the key points, not for now.
Videos are reviewed by @piensaenpixel.
And finally @iriberri is "moving" all the datasets to docs/example account (not in personal ones).
Rest is done, thanks all.

**Comment by xavijam** [comment]
@auremoser we will use your descriptions, don't worry about that anymore. :)

**Comment by auremoser** [comment]
Feel free to trim them, I don't want to f'up the design.

**Comment by iriberri** [comment]
#### Animate your data

Get the dataset
https://examples.cartodb.com/tables/tornado_centroids/

URL:
http://examples.cartodb.com/viz/960736aa-cd8c-11e4-a309-0e6e1df11cbf/embed_map


#### Create your own data

http://examples.cartodb.com/viz/eaa226aa-cd8e-11e4-893e-0e0c41326911/embed_map


#### Choropleth

1st dataset: 
https://examples.cartodb.com/tables/tornado_centroids/


2nd dataset:
https://examples.cartodb.com/tables/tornados_in_us


Map:
http://examples.cartodb.com/viz/339c7670-cd90-11e4-ab8c-0e018d66dc29/embed_map
