### ISSUE TITLE
Allow having a video "minimized"

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2415]

**Comment by saleiva** [comment]
![screen shot 2015-02-20 at 19 08 13](https://cloud.githubusercontent.com/assets/132149/6306431/d9d52f3a-b933-11e4-8441-303c1695a71d.png)

**Comment by saleiva** [comment]
![screen shot 2015-02-20 at 19 19 17](https://cloud.githubusercontent.com/assets/132149/6306644/6237d70a-b935-11e4-82d7-5f2a6893715e.png)

Research how to keep going on a different page

**Comment by javierarce** [comment]
I've been reading about the [Vimeo Javascript API](https://developer.vimeo.com/player/js-api) and I think we could use some of its methods to store the progress and play again from there on subsequent loads.

`playProgress` 

> Fired as the video is playing. Includes seconds, percentage played, and the total duration.

`seekTo(seconds:Number):void`

> Seeks to the specified point in the video. Will maintain the same playing/paused state. The Flash player will not seek past the loaded point, while the HTML player will seek to that spot regardless of how much of the video has been loaded.

I'll work on a mockup to test if this is feasible.

**Comment by javisantana** [comment]
we could use youtube that provides the same api and actually works :tmcw:

**Comment by javierarce** [comment]
Haha! I looked into vimeo first because we host the videos there, but we could use youtube instead (the buffering works [better], you're totally right there). My only concern would be: does youtube allow to embed videos without ads?

**Comment by javisantana** [comment]
And how that would work in onpremise offline?

**Comment by javierarce** [comment]
@javisantana: we would need to host the videos ourselves.

**Comment by javierarce** [comment]
Ok, some questions we need to answer: 

* Do we need to make this work offline?
* Do we want to keep hosting the videos in Vimeo or move them to Youtube?

**Comment by matallo** [comment]
I was going to reply quite with the same @javierarce answers.

First of all, shall we host the videos ourselves? thinking of the onpremise option here

Having decided this:
- rely on external provider for host and player (api) for the videos
- host player (api) and use a source list in configuration, either external or internal => http://www.jwplayer.com/

**Comment by javisantana** [comment]
for the moment just go with vimeo or whatever and just disable this in onpremise

**Comment by saleiva** [comment]
This is not needed for onpremise since its only for begineers

**Comment by javierarce** [comment]
I've tested a quick solution using local storage to save the current position and then seek to the right moment when the video is open in subsequent loads / different pages.

I have a question regarding this screen: 

![screen shot 2015-03-11 at 12 30 51](https://cloud.githubusercontent.com/assets/4933/6603189/be5c7384-c820-11e4-89a6-0eef24583739.png)

The "go for it" button that appears there is the one in charge of minimice the dialog?

**Comment by saleiva** [comment]
Yep, it should create an empty map and keep the video open there

**Comment by javierarce** [comment]
An empty map? That won't make sense for all the videos, I think.

**Comment by saleiva** [comment]
Sorry go to the dashboard

**Comment by javierarce** [comment]
Ok.

**Comment by javierarce** [comment]
Released.
