### ISSUE TITLE
Improve casting to number operations in columns with $ or €

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2419]
Right now, all columns are null after converting a column with null rows and numbers with $ before.

**Comment by rafatower** [comment]
let's talk about the use case: instead of doing magic with csv if the most common use case from the newbie and enterprise user is  to import from Excel, let's focus on importing excel with types instead of guessing from CSV.

**Comment by saleiva** [comment]
:?

**Comment by rafatower** [comment]
Forget my previous comment, I misunderstood the ticket :S

**Comment by rafatower** [comment]
Sample [data to test](https://gist.githubusercontent.com/rafatower/e2dd2aa9dd70a2fa511e/raw/d5abac77ae9f275ef15f485a2347eef6608f7974/money-table.csv)
