### ISSUE TITLE
Infowindows should not show titles for cells with null values

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2420]
in hover is happening.
Go to a table, click on infowindow choose a column with null and not null values, and try!

**Comment by alonsogarciapablo** [comment]
@saleiva. Just to clarify. We're talking about this, right?

![captura de pantalla 2015-03-11 a las 16 59 58](https://cloud.githubusercontent.com/assets/390398/6600483/2dc9db96-c810-11e4-8c52-bcaaec26d562.png)

**Comment by saleiva** [comment]
sip!

**Comment by alonsogarciapablo** [comment]
There are two different things here: infowindows and tooltips.

In a **public map**, when there're no values, tooltips look like this:

![captura de pantalla 2015-03-11 a las 18 36 20](https://cloud.githubusercontent.com/assets/390398/6602831/7f1c9e58-c81e-11e4-84ae-30f9968efaac.png)

Should we do the same in the editor?

**Comment by saleiva** [comment]
If there is no data selected, the infowindow on hover (tooltip) should not be shown on the public view.
So I guess this is part of the same issue
