### ISSUE TITLE
Fix "CartoDB is a product of Vizzuality" in the footer

### ISSUE THREAD

**Issue by santisaez** [CartoDB/cartodb#2424]
It will probably fixed with the new dashboard, but just in case I want to warn about this:

![cartodb_footer](https://cloud.githubusercontent.com/assets/223956/6325558/316049c6-bb49-11e4-8ca0-c66218655f71.png)

```bash
$ git grep 'is a product of'
app/views/admin/shared/_footer.html.erb:    <p class="right">CartoDB is a product of <%= link_to "Vizzuality", "http://vizzuality.com", :target => "blank" %></p>
```

**Comment by saleiva** [comment]
Yep, it is fixed in the new dashboard. Should I close?
