### ISSUE TITLE
No ability to like datasets in the Data Library?

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2428]

**Comment by xavijam** [comment]
Do you feel it is worth it? Only you will see those "stats", because i feel they won't be shared, won't they @juanignaciosl ?

**Comment by juanignaciosl** [comment]
Right now that search refers to private data as @xavijam says. If you think it's worthy we could do that feature by jumping to the external source, but it'd require remote querying from frontend or propagating changes when they change (which I think is much worse).

As an alternative, maybe it's more interesting displaying how many times it's been imported. We should increase a counter or something like that, not trivial with our database arquitecture, but maybe it's a better user feedback.

**Comment by saleiva** [comment]
Ok, let's keep it like it is right now
