### ISSUE TITLE
Low contrast in the lateral nav arrows.

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2429]

**Comment by carlostallon** [comment]
![captura de pantalla 2015-02-27 17 16 32](https://cloud.githubusercontent.com/assets/1712650/6416210/be9892e0-bea4-11e4-8ba8-ab85be0ab5dd.png)

**Comment by carlostallon** [comment]
Bump!
#BBB IMO

**Comment by saleiva** [comment]
cool!

**Comment by viddo** [comment]
Since we're changing the contrast on these buttons, shouldn't the cancel-buttons also be updated? Since we already unified #2222 these styles previously I figured we perhaps should do it this time too

**Comment by saleiva** [comment]
+1
