### ISSUE TITLE
Copy-edit - remove the “to”: “We recommend you export your dataset before deleting.” 

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2433]

**Comment by saleiva** [comment]
Also,  include a warning that won’t be able to retrieve the dataset after delete it - permanently deleted from CartoDB?

**Comment by viddo** [comment]
But last week we [changed the copy to _not_ say anything about exporting](https://github.com/CartoDB/cartodb/issues/2392) since it cannot be done yet. Does this change make sense?

**Comment by saleiva** [comment]
You can export datasets, not maps. This is for datasets.

**Comment by viddo** [comment]
Aha, I see, so there's a difference between datasets and maps, thanks for clarifying.  However, I don't think it makes sense to mention anything about exporting until that is implemented, [which was dropped/postponed in a earlier discussion](https://github.com/CartoDB/cartodb/issues/1660#issuecomment-69009655), we probably need to revisit this again before doing this change.

**Comment by saleiva** [comment]
Exporting datasets is already possible, not in batch, but yes one by one. Since it's a possible workaround and deleting is something very sensible from the user perspective I'd implement this change in the text now.

**Comment by viddo** [comment]
(Export dialog is not implemented for single items either yet](https://github.com/CartoDB/cartodb/issues/1658), due to the previously mentioned decision it was postponed. So in that case I propose that we should implement it and fix the copy together with those changes.

**Comment by saleiva** [comment]
Even if not being to export tables from the dashboard, it's possible from the table view.
