### ISSUE TITLE
Error - Twitter: number of terms in search

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#2434]
Creating a Twitter request with more search terms than the number allowed is raising:

````
"We couldn't import your table. There was some error while importing your table: Unknown Sorry, something went wrong and we're not sure what. Try uploading your file again, or contact us and we'll try to help you quickly."
```

And the trace says: 

````
Could not accept your search request: Too many positive clauses in rule - 31.  The maximum allowed is 30 (at position 1)
````

Could we give a better error message or even checking the number of terms from the frontend before starting the import process?

**Comment by xavijam** [comment]
We are checking the number of terms and categories user can add/edit in the twitter import, so closing! :)
https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/common/dialogs/create/listing/imports/twitter_import/twitter_categories/twitter_category_view.js#L14
