### ISSUE TITLE
Liked maps / datasets must show all liked maps / datasets by the user

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2440]
His own ones, and others ones.

**Comment by Kartones** [comment]
As talked with @javisantana, this shouldn't go through the normal `Visualization::Collection` model, but be instead a first step of the /explore API.

Also, grabbing all liked items for a given user is trivial, as the `likes` DB table has `actor` and `subject`, not needing to do Ruby logic or complex queries.

**Comment by Kartones** [comment]
Assigning to you @juanignaciosl as @javisantana told me you'll do the /explore API likely, but don't know the timeframe so just set next Milestone
