### ISSUE TITLE
Blurry icons in the new dashboard

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#2453]
![hola](https://cloud.githubusercontent.com/assets/1214201/6266159/504e6720-b836-11e4-9040-8857dce44089.png)
![](https://cloud.githubusercontent.com/assets/1214201/6266007/8cf1007c-b834-11e4-8250-1df4f9359d98.png)
![](https://cloud.githubusercontent.com/assets/1214201/6266828/859a95fe-b83e-11e4-9bae-ae7e0f99f07e.png)

**Comment by saleiva** [comment]
The one on the delete modal is blurry as well
