### ISSUE TITLE
Upgrade your plan in user configuration

### ISSUE THREAD

**Issue by carlostallon** [CartoDB/cartodb#2455]

**Comment by carlostallon** [comment]
![user config - upgrade your plan](https://cloud.githubusercontent.com/assets/1712650/6483150/ed8b2da2-c26d-11e4-9522-7a96833ac015.png)

**Comment by saleiva** [comment]
Uhm... Why do we need the "CHANGE YOUR PLAN BUTTON" then?
If you want to approach this like that, I'd change the order and show the plan selector before the invoice list, but it will compose weird.
Also we are not using circles for the icons like that anywhere else, right?

**Comment by carlostallon** [comment]
A new simpler version, now fits in all the app and launch the new upselling modal
![user config - api keys 4](https://cloud.githubusercontent.com/assets/1712650/6523407/d6424dd2-c3ef-11e4-9e71-75326e6cb742.png)

**Comment by saleiva** [comment]
I'm afraid that will be confused with the support module...
Ideas

- Make that button green (not sure)
- Move to the top of the page

**Comment by carlostallon** [comment]
![user config - upgrade](https://cloud.githubusercontent.com/assets/1712650/6556728/bc2f4698-c66f-11e4-9802-61933c2a46a9.png)

**Comment by saleiva** [comment]
hey @xavijam this is done, right?

**Comment by xavijam** [comment]
this is new for me
