### ISSUE TITLE
We're not taking into account parameters for WMS services

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#2456]
For example, checking:

`http://sitel.jalisco.gob.mx/cgi-bin/ortoamg?FORMAT=image/png&mode=24bit`

Makes the request:

``
https://cartodb-wms.global.ssl.fastly.net/api/check?url=http%3A%2F%2Fsitel.jalisco.gob.mx%2Fcgi-bin%2Fortoamg%3Frequest%3DGetCapabilities%26service%3DWMS&type=wms&callback=jQuery172016956360405310988_1424712794207&_=1424713877272``

SB/4577060

**Comment by javierarce** [comment]
Wait, but this URL doesn't seem to work:

```http://sitel.jalisco.gob.mx/cgi-bin/ortoamg?request=GetCapabilities&service=WMS&type=wms&FORMAT=image/png&mode=24bit```

While this one does:

http://sitel.jalisco.gob.mx/cgi-bin/ortoamg?request=GetCapabilities&service=WMS&type=wms

**Comment by iriberri** [comment]
I'm not able to add WMS now, it keeps in the following state:

![image](https://cloud.githubusercontent.com/assets/1730320/6410741/18be81a4-be72-11e4-9a0d-e571703f794f.png)

I'm trying with the WMS of this issue and also with others as: http://wms.geo.admin.ch/?service=WMS&request=GetCapabilities

The check request works but the add request returns:

````
jQuery17209921234685461968_1425032164372({
  "error": "Missing/unknown capabilities type"
})
````

![image](https://cloud.githubusercontent.com/assets/1730320/6410809/9d3710cc-be72-11e4-870c-c4a532099478.png)

**Comment by iriberri** [comment]
SB/4644228
