### ISSUE TITLE
Allow to specify max tweets import from the UI

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2467]

**Comment by Kartones** [comment]
New import endpoint param `twitter_credits_limit` (integer, default null to ignore)

**Comment by Kartones** [comment]
@xavijam to have the code clear, lets have a `POST /api/imports/` new field `user_defined_limits` which inside has the `twitter_credits_limit`:
```
{
  ...
  user_defined_limits: {
    twitter_credits_limit: xxxx
  }
}
```
