### ISSUE TITLE
Make the zoom level of the visualization available in the new public dashboard

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#2479]
In order to avoid using the bounding box to generate the map previews (as requested in [this issue](https://github.com/CartoDB/cartodb/issues/2462), we need to have the zoom available to request a 	identifiable image. 

My idea is to be able to have the zoom in the `vis` object of [new_public_maps.html.erb](https://github.com/CartoDB/cartodb/blob/master/app/views/admin/pages/new_public_maps.html.erb) so we can print a data attribute in the html and use it to generate the thumbnail.

@viddo, @xavijam, @javisantana… do you think that solution is ok?

**Comment by javisantana** [comment]
I think you have it in vis.map.zoom, right

**Comment by viddo** [comment]
Sounds OK to me. But since you mention that template, does this only apply to the public maps?

**Comment by javierarce** [comment]
@javisantana: I couldn't access that attribute there, but maybe is lack of knowledge of rails on my part (the error said that map is an Enumerable object, I think)

@viddo: in the private dashboard we can access that information directly from the model. For the thumbnails that appear when we remove a table, we'll need to do something similar as in the public dashboard.

**Comment by saleiva** [comment]
Is this already done? We fixed the original issue, right?

**Comment by javierarce** [comment]
Not really. I mean, we are using the zoom level there too, but is the same as in the visualization, not the +2 zoom level that we are using in the private dashboard. So if we want to have the exact same look in both places, we'll need to make the zoom level available there.

**Comment by Kartones** [comment]
Not yet, at least what Arce wants (making the zoom availabe). I'll try to tackle it today, if no more urgent tickets appear.

**Comment by Kartones** [comment]
Now exposing on each `vis` item (a Hash, that's why you couldn't do vis.map.zoom) the zoom property:
```
vis[:map_zoom]
```

Transferring to you the ticket so  you can play with it (or release if you want, as you see fit).
