### ISSUE TITLE
Google Signup: new accounts are created on login attempt

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#2500]
https://github.com/CartoDB/cartodb-central/issues/446

**Comment by juanignaciosl** [comment]
Now in case of username collision account creation must be explicit through form submission. Users that have suffered this issue can just disconnect their Google accounts or delete their undesired CartoDB accounts at "account settings" menu option in order to fix their login problems.

**Comment by iriberri** [comment]
Users informed in SB :-)
