### ISSUE TITLE
Bugs with new mamufas drag and drop import

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#2512]
- [ ] In Chrome for linux, once you drop the file, it is imported several times (experienced by @kartones).

**Comment by iriberri** [comment]
![out](https://cloud.githubusercontent.com/assets/1730320/6389464/62034e36-bda4-11e4-8183-f3f367f3ab5d.gif)

When there are finished imports in the list, adding a new file is duplicated and previous imports are taken into account too.

Result: 
![image](https://cloud.githubusercontent.com/assets/1730320/6389486/86307e46-bda4-11e4-802e-f56db8c45bf9.png)

**Comment by xavijam** [comment]
Trying some drag&drop libraries due to home-made solution is not so stable :(

**Comment by xavijam** [comment]
It should be fixed with https://github.com/CartoDB/cartodb/pull/2521
