### ISSUE TITLE
Design image/color selection for wizards

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2515]

**Comment by saleiva** [comment]
tricky one!

**Comment by carlostallon** [comment]
![wizard elements](https://cloud.githubusercontent.com/assets/1712650/6482995/565c4d0e-c26c-11e4-815f-ad1cc2e07ba6.png)

**Comment by saleiva** [comment]
Great, we should do a session tomorrow for unify this with the actual controls.
this looks great!

**Comment by saleiva** [comment]
I don't like the arrows being centered. It breaks the vertical rhythm when scanning it vertically.

**Comment by carlostallon** [comment]
Yep, I worried about it to, could work better aligned to right ; )

**Comment by carlostallon** [comment]
Fixed
![elements](https://cloud.githubusercontent.com/assets/1712650/6487655/c2139536-c292-11e4-8ecf-d81ea792ade3.png)

also added new symbols to document .../map-editor-1.2

**Comment by saleiva** [comment]
yay!
