### ISSUE TITLE
You can create an organization user without password

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#2519]
You can create an organization user without password. Is this somehow useful (bug or feature :D), @iriberri ?

**Comment by iriberri** [comment]
Wow... I'd say bug too :-)

If we're not generating a random password and sending it to the user via email or something, and then making the user change it in the first log in (very complex solution at the moment, I guess), creating a password should be mandatory.

This way we avoid subusers to go through the reset password process, which is kind of ugly for the onboarding of a new user.

**Comment by juanignaciosl** [comment]
Closed, you can't do this anymore.
