### ISSUE TITLE
design batch queries workflow

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#2522]
When an user executes a long running task (for example, update the whole table, casting a column) the query may take several minutes

The table should be able to work in that scenario, blocking some user actions and reporting to the user that the query is on progress, the same than geocoding and importing. 

cc @saleiva @carlostallon @piensaenpixel

**Comment by saleiva** [comment]
Ok, we have an element that could be reused. Assigning to me

**Comment by saleiva** [comment]
I have to say that I hate this...

![map editor - blocking loading](https://cloud.githubusercontent.com/assets/132149/6524125/a8df025c-c3f6-11e4-87b2-b7ac8a4a9cc8.png)
