### ISSUE TITLE
Update common data metadata task

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#2537]
Metadata will be updated by demand with the changes at #2661 . Remaining:
- [X] Delete remotes when they no longer exist.
- [X] Trigger update.
- [X] Front changes

Common data will be loaded/updated monthly, when a user enters his dashboard.

Maybe we should change the Data Library message to "Our elves are adding this data right now, please come back a little later and you'll enjoy their work" or something similar. What do you think?

**Comment by saleiva** [comment]
when will we launch this taslk??

**Comment by juanignaciosl** [comment]
In the description of this issue I propose not to run a rake task but trigger that on demand, since it will also solve updating the metadata. If you agree with this proposal I will do it ASAP.

**Comment by saleiva** [comment]
How much work does this need from @CartoDB/frontend ? They are a bit overloaded

**Comment by juanignaciosl** [comment]
<free-moan>Take a look at my assigned issue list :(</free-moan>

Pretty much none. Right now Data Library behaves fine with no data. I'd just change the text not to mean "There's no data" but "There will be data here in a few moments", the actual work backend: trigger a task to update the metadata every month or so.

**Comment by saleiva** [comment]
Ok, then let's do it like that...

**Comment by saleiva** [comment]
@viddo could you take care of the frontend part for this?

**Comment by juanignaciosl** [comment]
Ok, I will and then hand it to @viddo to try it and make UI consistent ^_^

**Comment by viddo** [comment]
:ok_hand: let me know when to do the changes.
