### ISSUE TITLE
Georeferenciation is not available in a visualization

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#2541]
This is something to be taken into account if we're moving to give more importance to maps than datasets in the New dashboard.

It's a bit ugly to click on GEO inside a visualization to geocode a dataset and have to go to the table because this cannot be done in a viz.

Don't know if there's any limitation for this, but as well as you can edit the dataset in a visualization, it could be great that you could geocode.

Depending on the results of this issue, I may also open another one about Creating tables from queries applied in a visualization :smile: 

cc @saleiva @xavijam

**Comment by xavijam** [comment]
@saleiva, should we enable "georeference" option in the visualization options? 
![screen shot 2015-03-09 at 14 29 04](https://cloud.githubusercontent.com/assets/132146/6555762/a75766c6-c668-11e4-8429-268c5a4d85c1.png)

**Comment by iriberri** [comment]
By the way, "Exporting layer" would be awesome also :P

**Comment by xavijam** [comment]
Step by step :P

**Comment by xavijam** [comment]
I feel iriberri, those options should be available in the layer panel, not in the "global" options. In any case, @CartoDB/design has the truth.

**Comment by iriberri** [comment]
I don't know where they need to be added, but I think they need. :smile: 

For example, in the table view, the GEO button should work directly imho.

**Comment by xavijam** [comment]
yep, it will work, that's fixed :)

**Comment by saleiva** [comment]
+1 to both options, if posible ;)

**Comment by xavijam** [comment]
Ooooook ;)
