### ISSUE TITLE
Extra elements showing up when importing

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2554]
I suspect it has something to do with the drop panel
![screen shot 2015-03-01 at 22 24 04](https://cloud.githubusercontent.com/assets/132149/6432899/bf8060de-c061-11e4-8904-49dd847ce875.p

**Comment by xavijam** [comment]
ARgasdfjñlajsdgjagladsj, yes, I know what is happening, thanks for the feedback.

**Comment by xavijam** [comment]
https://github.com/CartoDB/cartodb/commit/224c6043635a4b4942aa967b9c8446f56bc18f04
