### ISSUE TITLE
Suggestion: GeoPDF support?

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#2558]
Request from support. :smile:  SB/4652879

cc @saleiva @javisantana

**Comment by javisantana** [comment]
@iriberri could you complete this a little bit?

**Comment by iriberri** [comment]
> They would like to have the ability to define a number of layers to add 
to a map, define an area of interest, and output that map as a GeoPDF. 
I know that Cartodb can output static maps, but I did not see anything 
about GeoPDF output so contacting you here about it.
