### ISSUE TITLE
Static previews should not use CDN if not setup

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb#2567]
Static maps previews in the dashboard are trying to always use a CDN even if one is not returned in the layergroup response from the Maps API.

That ends in a redirection to cartodb.com/404

See #2458

**Comment by javierarce** [comment]
So, what is happening is that if no cdn_url is set, we use the default CDN config: https://github.com/CartoDB/cartodb.js/blob/develop/src/geo/layer_definition.js#L615

which is:

```    
cdb.CDB_HOST = {
      'http': 'api.cartocdn.com',
      'https': 'cartocdn.global.ssl.fastly.net'
    };
```

**Comment by javisantana** [comment]
we can not change the way maps work, when there is no cdn in the response the default one is used. The only way to not use CDN is set no_cdn flag.

The problem here is the tiler not properly configured

**Comment by rochoa** [comment]
Sorry, I forgot to mention this was happening in development environment
where you usually don't have a CDN.

Layergroups for tiles don't have the CDN config in the response but tiles
are not requested through the default CDN in development, that's why I
created the issue.

El martes, 3 de marzo de 2015, javi santana <notifications@github.com>
escribió:

> we can not change the way maps work, when there is no cdn in the response
> the default one is used. The only way to not use CDN is set no_cdn flag.
>
> The problem here is the tiler not properly configured
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/2567#issuecomment-76909662>.
>


-- 
Raul Ochoa
rochoa@cartodb.com

**Comment by javisantana** [comment]
we work like this since the beginning, maybe we should change the current behavior to not using cdn when the tiler does not say so

**Comment by javierarce** [comment]
@javisantana: you mean not using the default `CDB_HOST` defined [here](https://github.com/CartoDB/cartodb.js/blob/develop/src/geo/layer_definition.js#L615)?

**Comment by javisantana** [comment]
no, not using CDN if cdn_url from windshaft is empty (null or '')

**Comment by javisantana** [comment]
oh, yes, NOT using CDB_HOST

**Comment by javierarce** [comment]
Ok, fixed in cartodb.js and updated the version in cartodb, so this should be fixed.
