### ISSUE TITLE
Markdown from descriptions not rendered correctly in dashboard view

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#2572]
![screen shot 2015-03-02 at 4 44 06 pm](https://cloud.githubusercontent.com/assets/370259/6451289/87f9adba-c0fb-11e4-9433-5f1325f0fe81.png)

**Comment by xavijam** [comment]
@viddo please, could you take care of it?

**Comment by viddo** [comment]
I'll see if I have time to fix it for this sprint, otherwise for next week
