### ISSUE TITLE
Be able to select privacy for email if available for hire

### ISSUE THREAD

**Issue by Kartones** [CartoDB/cartodb#2574]
Right now, if you check the "available for hire" profile option, mailto:xxxx is always visible.

It would be good to have a combobox to select the privacy level of your email:
- Everyone
- Authenticated users (if you're logged in you see the user's email, else not)
- Nobody

/ cc @xavijam @saleiva

**Comment by juanignaciosl** [comment]
I set the wrong task id at commit comment :_)
