### ISSUE TITLE
External access to CartoDB?

### ISSUE THREAD

**Issue by AlexGorcea** [CartoDB/cartodb#2583]
By default, CartoDB allows access only on localhost. Which is kind of a no-no if you don't have a GUI.

I've tried modifying app_config.yml to point to my domain name, but CartoDB is expecting the username in the URL? Am I interpreting this right? 

It should be http://development.example.com:3000, but surely there must be another way?

**Comment by javisantana** [comment]
Hi Alex, please, use stackoverflow (don't fortget to tag with CartoDB) or our mailing list to ask general questions.

In general you should use a reverse proxy server like nginx, apache in front of cartodb services to expose them
