### ISSUE TITLE
US Geocoding Options should include City / State / Country ... Current just offers City / Country 

### ISSUE THREAD

**Issue by LoganWinston** [CartoDB/cartodb#2589]
In the US we have cities like Portland (city) Maine (state) and Portland (city) Oregon (state). The geocoder should include State as a parameter. 
![screen shot 2015-03-03 at 11 37 46 am](https://cloud.githubusercontent.com/assets/6501319/6467051/c4aab544-c199-11e4-944b-e205335b5bd5.png)

**Comment by LoganWinston** [comment]
@saleiva

**Comment by LoganWinston** [comment]
@juanignaciosl

**Comment by LoganWinston** [comment]
@rafatower

**Comment by iriberri** [comment]
Basically, right now the SQL behind just searches for cities inside a country (by ISO2 code) and retrieves the one with more population.

**Comment by iriberri** [comment]
I checked: column admin01 includes the states (abbreviated to iso2) in the USA case. In other countries like Spain, this column is not so straightforward and includes numbers for the autonomous communities.

**Comment by iriberri** [comment]
Closing. We already do this :)
