### ISSUE TITLE
Workflow issue: importing Zip file with multiple successful imports but directs to wrong one

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#2592]
In the new dashboard

If you import a shapefile say, and it contains a .txt file. It may end up taking you to the resulting visualization from the .txt. However, I am now super confused as a new user, it is empty. I delete it and go back to my dashboard. In reality, in the tables view there is probably a successful shapefile waiting for me.

**Comment by xavijam** [comment]
good one @andrewxhill, I'll take of the frontend part. @kartones, what happens in the backend part? It shouldn't create a map right?

cc @saleiva

**Comment by Kartones** [comment]
Importer is generic, it probably imports both if we support plaintext files (and I think TXTs are supported just in case contain tabular data), and I'm pretty sure it returns a list of "tables imported", but then, which one to choose? (once imported, all of them are tables, even if one is empty)

I'd have to do some tests to confirm, but what solution do you want? skip txts inside shapefiles? remove txt support? somehow provide table row count to the FE so it can decide which table to show? ...
