### ISSUE TITLE
Bubble map legends don't re-legend on Column change

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#2594]
See here,

![norelegend](https://cloud.githubusercontent.com/assets/370259/6472639/f08cef38-c1c1-11e4-8858-772ed3e287cb.gif)

**Comment by saleiva** [comment]
Maybe related with https://github.com/CartoDB/cartodb/issues/1881

**Comment by viddo** [comment]
@saleiva After fixing this issue and having a look at the referenced issue I believe that one to be another issue, so better to solve that in isolation.

**Comment by viddo** [comment]
merged & deployed in #2747
