### ISSUE TITLE
OEmbed endpoint misses '/embed' on some requests

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#2596]
Take a look here,

http://services.cartodb.com/oembed?url=https://team.cartodb.com/u/andrew/viz/fc508a2a-b058-11e4-a237-0e853d047bba/public_map

You'll see that on public_map based requests, we fail to put '/embed' at the end. So then, iframes look like this, where they contain the page header etc... 

http://embed.ly/docs/explore/oembed?url=https%3A%2F%2Fteam.cartodb.com%2Fu%2Fandrew%2Fviz%2Ffc508a2a-b058-11e4-a237-0e853d047bba%2Fpublic_map

Should be a pretty quick fix

**Comment by andrewxhill** [comment]
Confirmed it happens on team and non-team accounts

http://services.cartodb.com/oembed?url=https://osm2.cartodb.com/viz/d7a8a500-c1cd-11e4-827b-0e018d66dc29/public_map

**Comment by andrewxhill** [comment]
Same thing here, http://services.cartodb.com/oembed?url=https://team.cartodb.com/u/andrew/viz/4058c242-bf94-11e4-a164-0e9d821ea90d/map

**Comment by andrewxhill** [comment]
The last one was so that we support even when people grab the link from their authenticated session

**Comment by andrewxhill** [comment]
cc @Kartones @javisantana

**Comment by javisantana** [comment]
man, there are no quick fixs as you can see from this endpoint
