### ISSUE TITLE
The caching of geometry_types in rails is ineffective 

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#2603]
Typically a call to `Table#geometry_types` produces 3 queries to database even if the result is cached, which is pretty inefficient. E.g:
```Sql
SELECT * FROM "users" WHERE ("id" = 'fe3b850a-01c0-48f9-8a26-a82f09e9b53f') LIMIT 1

SELECT "pg_attribute"."attname" AS "name", CAST("pg_attribute"."atttypid" AS integer) AS "oid", format_type("pg_type"."oid", "pg_attribute"."atttypmod") AS "db_type", pg_get_expr("pg_attrdef"."adbin", "pg_class"."oid") AS "default", NOT "pg_attribute"."attnotnull" AS "allow_null", COALESCE(("pg_attribute"."attnum" = ANY("pg_index"."indkey")), false) AS "primary_key", "pg_namespace"."nspname" FROM "pg_class" INNER JOIN "pg_attribute" ON ("pg_attribute"."attrelid" = "pg_class"."oid") INNER JOIN "pg_type" ON ("pg_type"."oid" = "pg_attribute"."atttypid") INNER JOIN "pg_namespace" ON ("pg_namespace"."oid" = "pg_class"."relnamespace") LEFT OUTER JOIN "pg_attrdef" ON (("pg_attrdef"."adrelid" = "pg_class"."oid") AND ("pg_attrdef"."adnum" = "pg_attribute"."attnum")) LEFT OUTER JOIN "pg_index" ON (("pg_index"."indrelid" = "pg_class"."oid") AND ("pg_index"."indisprimary" IS TRUE)) WHERE (("pg_attribute"."attisdropped" IS FALSE) AND ("pg_attribute"."attnum" > 0) AND ("pg_class"."relname" = 'untitled_table_13') AND ("pg_namespace"."nspname" = 'public')) ORDER BY "pg_attribute"."attnum"

              SELECT DISTINCT ST_GeometryType(the_geom) FROM (
                SELECT the_geom
                FROM "untitled_table_13"
                WHERE (the_geom is not null) LIMIT 10
              ) as foo
```

This is due to the call to `Table#schema`, which queries the table schema and always calls `calculate_the_geom_type` if there's a column `the_geom`.

**Comment by rafatower** [comment]
There's a contradiction in the `table.rb` regarding cardinality of geometry types (whether it can be singular or plural) which results in messy code: a public method `geometry_types` that supposedly can return more than one type, another public method `calculate_the_geom_type` that can only return one and stores it in a single-valued attribute and all the mess around it.

While we should keep `geometry_types` not to break the "public interface" of `table.rb`, we should remove from the code the possibility of returning more than 1 geometry type and simplify it.

@javisantana do you agree?

**Comment by javisantana** [comment]
``geometry_types`` should return an array so let's keep this with multigeometry for the moment

schema is not needed anymore in client side, I removed that requirement, so It can be removed

**Comment by rafatower** [comment]
Ok, I will make `geometry_types` return an array of max one element.

**Comment by javisantana** [comment]
but at some point it could return more than one element, right?

**Comment by rafatower** [comment]
Right now, yes, there might be more than one: when there's more than one geometry type in the first 10 rows. Does it make sense for client code?

**Comment by javisantana** [comment]
yes but we do not use it  :D

**Comment by rafatower** [comment]
I'm closing this for the moment, we will tackle the root cause (the models, frameworks and mixup of platform and editor) rather than this detail, which will be more effective.

In staging, the table request is just 2% faster in best case scenario at the expense of risk and complexity.

**Comment by javisantana** [comment]
:es: :es::es::es::es::es::es::es::es::es::es::es::es:
