### ISSUE TITLE
Improve map.recalculate_bounds! speed

### ISSUE THREAD

**Issue by Kartones** [CartoDB/cartodb#2613]
By @javisantana :

```
# select _postgis_stats('my_table', 'the_geom')::json->'extent';
                      ?column?
-----------------------------------------------------
 {"min":[-5.52764,41.0878],"max":[-3.97387,42.3147]}
```

**Comment by javisantana** [comment]
but this only works if the stats are updated (after a vacuum) but I think we use that function only after we create a map

**Comment by Kartones** [comment]
If flow hasn't changed, we always do a VACUUM after importing, so would be valid.

**Comment by Kartones** [comment]
confirmed, after either a copy from existing table or registering a new one, a `table.optimize` is performed, which does internally a `run("VACUUM FULL #{qualified_table_name}")`, so can be used

**Comment by Kartones** [comment]
Ok, it seems not always works, at least with small datasets.

At a test, with a just created table with 5 rows:
```
VACUUM FULL public.untitled_table_1;
SELECT _postgis_stats ('public.untitled_table_1', 'the_geom')
ERROR:  stats for "untitled_table_1.the_geom" do not exist
```
So I'll implement a fallback for when there are no stats because data is small or "yet" stats aren't calculated.

**Comment by Kartones** [comment]
After some tests, it is indeed much faster, but also less accurate. Table with 62k rows, complex geoms, etcetera:
```
SELECT _postgis_stats ('public.aaa', 'the_geom')::json->'extent';
-- -141.442
-- 43.8096
-- -52.4573
-- 76.6626

SELECT
        ST_XMin(ST_Extent(the_geom)) AS minx,
        ST_YMin(ST_Extent(the_geom)) AS miny,
        ST_XMax(ST_Extent(the_geom)) AS maxx,
        ST_YMax(ST_Extent(the_geom)) AS maxy
      FROM public.aaa;
-- minx -141.002672003315
-- miny  -13.455676000376
-- maxx   30.8416667003606 
-- maxy   79.8750000004749
````

@javisantana If you're ok, we can go for it. It always fallbacks to real row calculation in case of errors so shouldn't be dangerous.

**Comment by javisantana** [comment]
go with it
