### ISSUE TITLE
Empty public dashboard design

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2615]
As @andrewxhill was mentioning would be great to have a list of popular maps taken from the gallery / website (talk to @matallo to see if this is easily doable - I don't think so) or a CTA to visit the cartodb gallery when a public dashboard of an user is empty.

**Comment by andrewxhill** [comment]
In this case, I would much prefer to supply a config file with a long list of cool maps and their profile page links / embed links. So imagine,

```
- https://team.cartodb.com/u/andrew/viz/365aa620-c273-11e4-bac7-0e018d66dc29/public_map
- https://team.cartodb.com/u/saleiva/viz/cb230d74-a22f-11e4-a2c9-0e0c41326911/public_map
- https://andye.cartodb.com/viz/445b1a6c-a1e8-11e4-9280-0e4fddd5de28/public_map
```

Then we just pick them in a set or random order and show them there. That way 

1. I can add them nice and easy
2. They will match exactly the aesthetic of the public pages since they will just be embeds

**Comment by saleiva** [comment]
That should be reviewed by @javisantana since is a bit hacky - although I've got your point. Another possibility is to wait on implementation until we have an endpoint for the explore API

**Comment by matallo** [comment]
in the meantime i'd go with @andrewxhill solution

**Comment by javisantana** [comment]
stop hacks please. if you want we chose the most viewed ones/random we do, but no hacks

in any case for me this should wait until we have the things we need

**Comment by carlostallon** [comment]
You mean something like this:

![dashboard - user public - 0 maps copy](https://cloud.githubusercontent.com/assets/1712650/6554070/aced67b8-c657-11e4-8d04-f8fe9780c255.png)

**Comment by saleiva** [comment]
Yeah, something like that but...
- I'd make it more visual
- It doesn't make so much sense that we put there some CTA's to browse others users maps, and we don't give credit to those users, right? Also, that similarity with the normal maps I think is dangerous.

**Comment by carlostallon** [comment]
![dashboard - user public - 0 maps copy](https://cloud.githubusercontent.com/assets/1712650/6572469/c46b9a84-c712-11e4-98c7-59b997b3480d.png)

**Comment by carlostallon** [comment]
bump

**Comment by saleiva** [comment]
Looks to similar to a filled dashboard to me... not sure... let's talk this in person
