### ISSUE TITLE
change order and copy on the user dropdown

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2616]
![screen shot 2015-03-04 at 17 43 59](https://cloud.githubusercontent.com/assets/132149/6488200/1cfdb49c-c296-11e4-9456-ee07d9bf1fc2.png)

to...

"View your public profile"
"Your Account" -> https://team.cartodb.com/u/`username`/profile
"Your API Keys"
"Close session"

**Comment by saleiva** [comment]
Please :)

**Comment by viddo** [comment]
Sure, but isn't a bit weird that we have a link that says: "Your account" and points to the profile settings, when there are both "Profile" and "Account" settings available? :)
![screen shot 2015-03-04 at 17 56 41](https://cloud.githubusercontent.com/assets/978461/6488439/da0c4d72-c297-11e4-8ca9-d6bf19ef0300.png)

**Comment by viddo** [comment]
Btw, for organization admins there is also another link there ("Organization"), it stays after account settings but before API keys with this change?

**Comment by saleiva** [comment]
I'd put the first one, "Your Organization"
