### ISSUE TITLE
When being logged-in and in the public page of one of your own maps you should have an "EDIT THIS MAP" button visible

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2617]
We don't have this on the designs.
Also we should organize that file properly and update some styles, as something is wrong with fonts I think...

**Comment by piensaenpixel** [comment]
Take a look, cc @carlostallon 

![public - map - logged your map](https://cloud.githubusercontent.com/assets/1214201/6637726/44dfa166-c97e-11e4-9034-5df4e239d1ad.png)

**Comment by saleiva** [comment]
Like it!
