### ISSUE TITLE
Change section order in the create map modal

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2621]
After some tests with real users the correct order should be
Connect Dataset | Datasets | Liked Datasets | Data library 

For org users should be
Connect Dataset | Datasets | Shared with you | Liked Datasets | Data library

The only thing that should change is that the selected item when having datasets already imported should be Datasets, and no Connect dataset like when you don't have any data.

Sorry!

**Comment by xavijam** [comment]
Order change -> :+1: 
About the selected item, right now:

- Opening connect dataset, default selected item, connect dataset.
- Opening new map, default selected item, datasets.

Any change?

**Comment by saleiva** [comment]
Perfect. What is the defaul one when not having datasets in your account (in the map one?)

**Comment by xavijam** [comment]
Datasets, it doesn't change "automatically" right now, but I'm implementing the same thing as we do in dashboard list, it will go to data library, sounds good?

**Comment by saleiva** [comment]
I'd show the datasets with the placeholder that we have designed for the zero case on the dashboard. Dont you?

**Comment by xavijam** [comment]
This thing with the "datasets" tab or with the "data library" tab?
![screen shot 2015-03-05 at 18 28 35](https://cloud.githubusercontent.com/assets/132146/6510301/82860b46-c365-11e4-83ff-41d9b71ab05a.png)

**Comment by saleiva** [comment]
Yep, that thing, the complete thing. The blue area + the datasets. You think it makes sense?

**Comment by xavijam** [comment]
Not sure, but let's try. To be clear. 
Being in "create dialog", when there is no datasets, we redirect to data library tab with the blue thing, agree?

**Comment by saleiva** [comment]
I have my doubts here. Due to usability issues I'm not sure if we should hide completely the "Your Datasets" link and 'redirect' the user to the Data library, or show this in the "Your Datasets" tab. 

cc @piensaenpixel @carlostallon
