### ISSUE TITLE
Search should search on all the filtered views 

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2628]
People is becoming a bit crazy on the tests when trying to search a dataset on the data library when having the Your datasets filter activated. We should add the small icon we designed (@carlostallon) to the results that come from the data library.

This applies to the create modal window and the datasets dashboard

**Comment by xavijam** [comment]
In short, we want a search that could find the "pattern" in any type (your datasets/maps, shared, data library, ...), right?

**Comment by saleiva** [comment]
yes but we will never mix datasets and maps

**Comment by xavijam** [comment]
Yeah, of course.

**Comment by xavijam** [comment]
Unfortunately, we can't search within data-library and user datasets because the type ```param``` is different. For data-library we use ```remote``` and for standard datasets we use ```table```.

@juanignaciosl @javisantana @Kartones

**Comment by juanignaciosl** [comment]
Well, we could accept a comma separated list of types and then use it wit an `OR`, isn't it? There's one single table underneath (`visualizations`) so it should be easy.

**Comment by xavijam** [comment]
Sounds a good solution to me

**Comment by xavijam** [comment]
Should I open a new ticket @juanignaciosl ?

**Comment by juanignaciosl** [comment]
Since I suppose you'll work in a branch, do the frontend part and then pass me the branch if you want.

**Comment by xavijam** [comment]
branch new-dashboard-search

**Comment by xavijam** [comment]
pushed right now, sorry buddy.

**Comment by juanignaciosl** [comment]
Please confirm me if UI is already sending the comma-separated list of types and then assign this to me.

**Comment by xavijam** [comment]
Ready for testing in staging :)
