### ISSUE TITLE
Design error modal window with upselling CTAca

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2629]
When raising an error relates with your account limitationa we should show a nice CTA on the modal window for upselling

**Comment by saleiva** [comment]
bump!

**Comment by carlostallon** [comment]
![error cta](https://cloud.githubusercontent.com/assets/1712650/6600626/0cee3ed4-c811-11e4-840f-931280fe979b.png)

**Comment by saleiva** [comment]
Why the numbers?
I think we have to rethink that part for this particular case.

"invalid import" -> "You have run out of quota (change icon?)"
"Check errors" -> "Remove some of your datasets to gain available space or upgrade your account"

Remember, copy is also part of design!

**Comment by carlostallon** [comment]
Fixed
![create - file importing error](https://cloud.githubusercontent.com/assets/1712650/6674782/6f9935c0-cc1c-11e4-8efa-cefd1de6c636.png)

**Comment by saleiva** [comment]
Like!

**Comment by xavijam** [comment]
Note for me:

- When creates a new map (importing data library).
- Adding a new file (drag and drop).
- Importing a file that takes more space than expected.
