### ISSUE TITLE
Review all upselling flows

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2630]
- ~~when raising an error on import because you don't have enough quota~~ => (#2630)
- [x] when being close to the limits
- [x] when trying to change the privacy of a table (privacy levels and collaboration)
- [x] when being exposed to a 'paid' feature (like sync tables)
- ~~when trying to connect data from a paid datasource (Twitter/ArcGIS/...)~~=> (#2910)

Anything more?

**Comment by saleiva** [comment]
Cc @iriberri I'd add this to the smoke tests

**Comment by iriberri** [comment]
Added to smokes.

**Comment by saleiva** [comment]
buuump!

**Comment by carlostallon** [comment]
![01 upselling](https://cloud.githubusercontent.com/assets/1712650/6601743/a9cb664a-c817-11e4-8090-c230f32766ef.png)
![02 upselling](https://cloud.githubusercontent.com/assets/1712650/6601745/a9cf9328-c817-11e4-8245-7fc0cea6938b.png)
![03 upselling](https://cloud.githubusercontent.com/assets/1712650/6601744/a9cf7cee-c817-11e4-9876-a64a8c4eeff8.png)
![04 upselling](https://cloud.githubusercontent.com/assets/1712650/6601747/a9df23f6-c817-11e4-8785-f4f042cbedda.png)
![05 upselling](https://cloud.githubusercontent.com/assets/1712650/6601748/a9df5ff6-c817-11e4-8da8-ebe9a979fcbd.png)
![06 upselling modal](https://cloud.githubusercontent.com/assets/1712650/6601746/a9deac6e-c817-11e4-9005-bbd813ea4235.png)

**Comment by saleiva** [comment]
Why don't you use the 'present' icon that was so lovely?
Like them all, only thing I am not sure is about the blue on the modal window (the privacy one)

**Comment by carlostallon** [comment]
I will add it again the icon and solve this color issue

2015-03-11 18:11 GMT+01:00 saleiva <notifications@github.com>:

> Why don't you use the 'present' icon that was so lovely?
> Like them all, only thing I am not sure is about the blue on the modal
> window (the privacy one)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/2630#issuecomment-78308906>.
>



-- 
Carlos Tallón
Designer

**Comment by saleiva** [comment]
Also, the last point is missing I think

**Comment by carlostallon** [comment]
"free trial" text added. The idea is not to change the layout in any case because this text is just one case, when a user never had a paid plan.

![03 upselling](https://cloud.githubusercontent.com/assets/1712650/6674450/01a7cb6e-cc1a-11e4-9634-2492e926f033.png)

**Comment by saleiva** [comment]
Cool!

**Comment by saleiva** [comment]
Still pending the UI changes. Assigning to @xavijam for the next sprint

**Comment by xavijam** [comment]
Those cases are already implemented. I only missed this one:

![screen shot 2015-03-23 at 16 54 58](https://cloud.githubusercontent.com/assets/132146/6784003/5f6d5652-d17d-11e4-9b3c-6ca0f96d9c1d.png)

Should we implement it for all pages? It "changes" the notification flow we have right now.
Also we will have to add it in plans page (cc @matallo).

**Comment by saleiva** [comment]
with the latest designs?

**Comment by matallo** [comment]
on it

**Comment by matallo** [comment]
https://github.com/CartoDB/cartodb-central/pull

**Comment by xavijam** [comment]
Really weird to see this type:
![screen shot 2015-03-25 at 15 29 20](https://cloud.githubusercontent.com/assets/132146/6826734/cecb46da-d303-11e4-854e-3c0f7af0e39d.png)

And then when a user can't upload a file due to size limitations, we show this type:
![screen shot 2015-03-25 at 15 29 32](https://cloud.githubusercontent.com/assets/132146/6826730/cc8c312c-d303-11e4-854a-5827108a8ccb.png)

Is it ok? Shouldn't we display rocket in all views? maybe in none of them?

cc @saleiva @carlostallon

**Comment by xavijam** [comment]
What about the datasource option, I haven't seen any design about that case. In fact I'm using texts from old dashboard + "no background image".

**Comment by saleiva** [comment]
The reason to not show the rocket is because it conflicts with the other icon.
About the thing with the datasource, I'll design, looks like @carlostallon forgot it :(

**Comment by saleiva** [comment]
Can you create a separated ticket for that?

**Comment by xavijam** [comment]
1) ok
2) https://github.com/CartoDB/cartodb/issues/2910
