### ISSUE TITLE
Make the upgrading component a modal window

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2631]
Due to the amount of places that we will need to open this component from, I think the best is to design this as a modal window

**Comment by carlostallon** [comment]
Makes sense.

![upgrade your plan](https://cloud.githubusercontent.com/assets/1712650/6507539/eacf7c7c-c352-11e4-81a7-80847aee8e3b.png)

**Comment by saleiva** [comment]
Ha! Love the rocket!
- Why the squares have not border radius?
- Mercator doesn't have Teams, so we might need to expose the enterprise offering here (can be secondary).
- It's weird that there is an "active" button for "YOUR PLAN", right? There is not action related with that.
- How do you mark a plan as recommending? Looks great, but what is the rationality?
- Is All features a link? I'd try to not link to external pages from here.
- If all have Unlimited tables, why should we put it?
- To me it has been weird to see these colors here since they are not being used in any other component (At least the dark grey).

**Comment by carlostallon** [comment]
working on that...
Why the squares have not border radius?
- fixed
Mercator doesn't have Teams, so we might need to expose the enterprise offering here (can be secondary).
- we can change the literal 
It's weird that there is an "active" button for "YOUR PLAN", right? There is not action related with that.
Yep, you could go to your plan tab in preferences, but we can also disable it.
How do you mark a plan as recommending? Looks great, but what is the rationality?
- Based on your quota/usage. Yep, it's easy to say :)
Is All features a link? I'd try to not link to external pages from here.
- Removing
If all have Unlimited tables, why should we put it?
It's based on comercial pages, we are showing that way there.
To me it has been weird to see these colors here since they are not being used in any other component (At least the dark grey).
- The same than above. Based on comercial pricing table, just to avoid make different styles for each section.

**Comment by saleiva** [comment]
What I meant is that we should expose the enterprise offering too, although we remove that literal.

About the aesthetics, if we follow that argument we should redesign completely wither the website or the dashboard ;). I'd try to make it more consistent with the rest of the dashboard.

**Comment by saleiva** [comment]
All the other points, +1

**Comment by carlostallon** [comment]
![user config - api keys 8](https://cloud.githubusercontent.com/assets/1712650/6508739/dfd8d414-c35a-11e4-9ee3-8a8e1e577cdb.png)

So, do you add a new column or just replace the mercator one?

**Comment by saleiva** [comment]
I'd add the enterprise information in the text you have below maybe (with a little icon maybe?).

The reason we show the unlimited tables in the commercial website is because before we had limits. I think we can remove from there too (cc/ @piensaenpixel).

I don't think we should put the recommended for you text in the same row we have other properties or it can confuse people. For me it looks like Coronelli includes Private visualizations too (in this particular case). Aesthetically it looks way more consistent IMO.

**Comment by carlostallon** [comment]
Ok, fixing it!

**Comment by carlostallon** [comment]
![user config - api keys 8](https://cloud.githubusercontent.com/assets/1712650/6510829/d0d489a0-c368-11e4-92e4-1b123485b601.png)

**Comment by saleiva** [comment]
"Are you looking for more?
Enterprise plans include team collaboration tools and unlimited resources"

And with that change... :+1:

**Comment by carlostallon** [comment]
![user config - api keys 8](https://cloud.githubusercontent.com/assets/1712650/6511037/4d299904-c36a-11e4-9195-11ab8d1d7b17.png)

**Comment by saleiva** [comment]
:+1:

**Comment by viddo** [comment]
Some doubts:
1. What is "downgrade" button suppose to do?
1. Where do "Go to enterprise" point to?
1. "Upgrade" button points to same URLs as already exist on existing `account/username/upgrade` page?

**Comment by saleiva** [comment]
1. Change your plan to a lower one.
2. Sales@cartodb.com
3. I think so, check with @xavijam

**Comment by viddo** [comment]
1. Sure, but _how_ is that expected to be done? :) AFAIK that feature do not exist right now.. do you mean that this button should change the plan of the user? If so, what about organizations?

**Comment by saleiva** [comment]
Yes this is implemented in the actual version! We do have downgrades almost every day :)

**Comment by viddo** [comment]
Aha, my bad then! I need to find where that's done, have not seen it so far..

**Comment by xavijam** [comment]
But that dialog if for "central" or for "editor"?

**Comment by saleiva** [comment]
That dialog is for everywhere...

If making this part of central, we can adapt the design to do a separated page in central.

**Comment by viddo** [comment]
AFAIK, we do not have modals on central, do we? @matallo ?

Currently the plan details and metadata (what would go in the plan properties in these mockups) is provided through a JSON, so I think it makes sense to have the modal on the editor, and render based on this data.

Also, I'll make sure to add error handling, in case the endpoint fails and/or change unexpectedly. I agree with @xavijam's proposal here (discussed offline): redirect to the upgrade URL on central so the user can carry out wanted operation, + log the error so we (developers) can be aware and fix it... sounds reasonable?

**Comment by matallo** [comment]
-1 to move it to the editor

at least at this point, we already have styles of new_dashboard in cartodb-central, and we can have a placeholder dashboard where to place the modal

**Comment by saleiva** [comment]
Linking what matallo is proposing. Is not that straightforward but we can give it a try.
cc/ @carlostallon 

In that case, @matallo I'd assign this to you.

**Comment by viddo** [comment]
@matallo what do you mean with "placeholder dashboard"? Maybe I'm misunderstanding something, but if doing this in central, how do you propose to display this in a modal in the editor?
If you agree with @saleiva and it's clear to you what needs to be done feel free to reassign the issue to yourself. If not, let me know what you guys expect from me.

**Comment by matallo** [comment]
as in http://oneclick.cartodb.com/3b75efc1-3ef2-470e-9500-1969816b0f88/?file=http://tidesandcurrents.noaa.gov/kml/coops-slt.kmz (but in cartodb-central, where we already have the assets and layout ready, i.e. plan view)

**Comment by matallo** [comment]
check PR on cartodb-central

**Comment by carlostallon** [comment]
![02](https://cloud.githubusercontent.com/assets/1712650/6644317/1a1c2956-c9b3-11e4-997f-62e2e21eaebe.png)
![03](https://cloud.githubusercontent.com/assets/1712650/6644316/1a1af374-c9b3-11e4-8e54-3962c2c9eec9.png)
![01](https://cloud.githubusercontent.com/assets/1712650/6644315/1a19aad2-c9b3-11e4-8ecc-793497429f43.png)

**Comment by iriberri** [comment]
Moved from El Soto to Baeza.

**Comment by xavijam** [comment]
But wait, this is already done, isn't this @matallo?

**Comment by matallo** [comment]
it is, just waiting to be deployed for all users

**Comment by saleiva** [comment]
Deploy, now

**Comment by saleiva** [comment]
bump!

**Comment by matallo** [comment]
this goes along with new dashboard, having it deployed next week we decided to hold for that
