### ISSUE TITLE
Workflow issue: Can't georeference a newly imported table because it goes to Visualization

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#2632]
Import a csv without any automatically recognizable location data
You get to a table full of the_geoms but there is no menu option to georeference

**Comment by saleiva** [comment]
Yep, with the new workflow we should allow datasets from the map view. I think this is duplicated but I cannot find the other issue.

**Comment by javierarce** [comment]
Well, found (although too late): https://github.com/CartoDB/cartodb/issues/2541

I'm closing this ticket.
