### ISSUE TITLE
Make search input in dashboard and modals more visible

### ISSUE THREAD

**Issue by carlostallon** [CartoDB/cartodb#2636]

**Comment by carlostallon** [comment]
IMO works adding more contrast to the link than the others. What do you think?
![search](https://cloud.githubusercontent.com/assets/1712650/6557136/0ca190b0-c673-11e4-8e40-14058aea665b.png)
![search2](https://cloud.githubusercontent.com/assets/1712650/6557137/0cb8b0c4-c673-11e4-9400-f316d6420aa3.png)

**Comment by saleiva** [comment]
3rd one for me.
What about making it blue too?

**Comment by carlostallon** [comment]
Makes sense IMO

![captura de pantalla 2015-03-10 18 43 43](https://cloud.githubusercontent.com/assets/1712650/6581150/67b85ffa-c755-11e4-9d66-fefabd4e33a1.png)

**Comment by saleiva** [comment]
Let's go with the black one and try. Assigning to myself.
