### ISSUE TITLE
Columns are no longer alphabetically ordered in the table view

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#2638]
Reporting as you just suggested me in the office. :smile:

**Comment by viddo** [comment]
The title indicate the columns were sorted alphabetically at some point in the past as well, where/how was this sorting done then? Do you know when this changed, @iriberri ?

Investing a little in the code I can see that there already is a [sort-method in the table metadata model](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/models/table.js#L778-L795), but it only sorts based on a pre-defined priority list. Would this be a appropriate place to also sort the default keys alphabetically? cc @javisantana

**Comment by iriberri** [comment]
I don't know the details, but @javisantana told me that he was aware of this so I suppose he knows which change provoked this. :-)

If my memory doesn't fail, yes, previously the columns were ordered alphabetically.

**Comment by javisantana** [comment]
the thing is I changed the way we get the schema: we were using backend provided schema and we changed to a sql api one. At some point that sortSchema is not working due that change (that's my guess)

**Comment by viddo** [comment]
Yes, I figured it was something like that, sounds reasonable. So having that in mind, do you consider this something that should be fixed/changed in the SQL API?

If not I believe the previously mentioned sort method seems like a legit place to change order of the columns (considering the fact that some columns are already re-ordered for the editor), right?

**Comment by javisantana** [comment]
i don't think we can change sql api easily, so that method is perfect to sort by name (keeping the priorities)
