### ISSUE TITLE
Type guessing is wrongly disabled by default

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#2649]
In some of the multiple refactors of params and options passing it has been broken
```
$ git log -Stype_guessing 
```
commit 9f57e19e6200733db47ff76574f6cda67909c5bd
commit c2ec8a135fcb051f338ee2d8c48b0eff9669460c
commit 9b6c519daf0e1a723e35a54bd3661fe7ae67288a
commit bf885b73b84b3ee88c4d12658ddebee7cd24ff63
commit e253fde5f35728d166a9df2adfcfe6d377a53584

cc/ @Kartones

**Comment by rafatower** [comment]
the bug is here:
```Ruby
# imports_controller.rb
type_guessing:          ["true", true].include?(params[:type_guessing]),
```
It should be true by default instead of requiring its presence. http://docs.cartodb.com/cartodb-platform/import-api.html

**Comment by Kartones** [comment]
ohh, yes. I'll fix it in a while but today.
