### ISSUE TITLE
Changing avatar does not refresh it when selecting the file

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb#2651]
## STR
 1. Go to "*Account settings*"
 1. Go to "*Profile*"
 1. "*Chose avatar*"
 1. Select a file

## Current result
There is no preview of the new avatar

## Expected result
The new avatar should have a preview (specially when you don't have an avatar yet)

![screen shot 2015-03-06 at 12 50 43](https://cloud.githubusercontent.com/assets/45346/6524994/2240d3c4-c400-11e4-96bd-07aefffd5128.png)

**Comment by xavijam** [comment]
For me this is not a bug, flow works.

**Comment by saleiva** [comment]
oki
