### ISSUE TITLE
It's not possible select a different avatar after selecting a first one

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb#2652]
## STR
 1. Go to "*Account settings*"
 1. Go to "*Profile*"
 1. "*Chose avatar*"
 1. Select a file

## Current result
It's no longer possible to select again another avatar

## Expected result
It should be possible to select another avatar before saving the change

![screen shot 2015-03-06 at 12 50 43](https://cloud.githubusercontent.com/assets/45346/6525054/f7cb424a-c400-11e4-909b-93083edb5154.png)

**Comment by xavijam** [comment]
Same as #2651

**Comment by xavijam** [comment]
Let's change in the next iteration guys, please, love you.

**Comment by rochoa** [comment]
:heart:

On Wed, Apr 1, 2015 at 5:57 PM, Javier Álvarez Medina <
notifications@github.com> wrote:

> Reopened #2652 <https://github.com/CartoDB/cartodb/issues/2652>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/2652#event-270780278>.
>



-- 
Raul Ochoa
rochoa@cartodb.com
