### ISSUE TITLE
Layout errors on the delete dataset modal window

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2654]
When having affected maps.
The card margin-top / bottom should be 28 and it's way less.
Also some scrollbars appear when they shouldn't
![screen shot 2015-03-06 at 16 20 51](https://cloud.githubusercontent.com/assets/132149/6527678/ecd60a16-c41c-11e4-8bd5-a51d42d9e2d3.png)

**Comment by viddo** [comment]
You use Safari, right?

**Comment by viddo** [comment]
Nevermind, noticed what is wrong..
