### ISSUE TITLE
Mistake

### ISSUE THREAD

**Issue by devakdo** [CartoDB/cartodb#2657]
i think i have mistakenly deleted this https://github.com/CartoDB/cartodb/wiki/Problems-faced-during-CartoDB-install-&-solutions-if-known

**Comment by viddo** [comment]
No worries, [I've restored it](https://github.com/CartoDB/cartodb/wiki/Problems-faced-during-CartoDB-install-&-solutions-if-known).

**Comment by devakdo** [comment]
hello viddo can u pls help me. im getting 404 error after installation can
u help how to resolve?

**Comment by viddo** [comment]
This issue tracker is primary for development issues, for installation or configuration help it's better if you ask on the [mailing list](https://groups.google.com/d/forum/cartodb), so other people from the community can also help and learn from this. Also, when writing there, make sure to include more information on what URL you're trying to open when you get the 404 error etc. Thanks!
