### ISSUE TITLE
split trackjs for cartodb.js and editor

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#2658]
the problem here is that cartodb.js usually throws a lot of errors due embeds and we are not able to see the editor ones properly.

My proposal here is to split in different accounts (don't know if trackjs allows to scope errors). Also I find trackjs pretty limited compared to rollbar, it seems to now allow to silent some errors for example

cc @CartoDB/frontend

**Comment by viddo** [comment]
:+1:

**Comment by javierarce** [comment]
:+1:

**Comment by matallo** [comment]
:+1:

**Comment by javisantana** [comment]
hey, I know you are agree, what are your proposals to do this?

**Comment by viddo** [comment]
Since you mentioning Rollbar, is there a reason why we are not using https://rollbar.com/docs/notifier/rollbar.js/ ? It also supports source maps that would be a nice addition (once we fix that for production).

**Comment by javisantana** [comment]
@xavijam knows the details

**Comment by xavijam** [comment]
I've said several times. TrackJS provides a timeline of actions before finding the error. Something I found great to catch errors easily. Source maps are also supported in TrackJS. But finally, if you want to go back to rollbar fine for me, no problem.

**Comment by javisantana** [comment]
for me trackjs works good enough the only problem with trackjs (which is fixeable) is split things from cartodb and cartodb.js (embed)

**Comment by viddo** [comment]
So rather than migrating to a new tool (and all the problems that comes with that), why not just start with "split things"? I think it was already mentioned, but what's stopping us from using http://docs.trackjs.com/Examples/Multiple_Applications (apart from obvious upgrade, which we most likely would need from other services too).

**Comment by alonsogarciapablo** [comment]
We've finally upgraded track.js and we're now able to create 3 apps :+1: 

Here's an initial proposal for how to split things:

- cartodb.js -> Embedded maps
- new dashboard -> New dashboard
- cartodb -> The rest

What do you guys think?

**Comment by xavijam** [comment]
CartoDB.js, editor and central.

**Comment by alonsogarciapablo** [comment]
@zenitraM are you working on this?

**Comment by alonsogarciapablo** [comment]
I guess you just added the `2 - Working` label.

**Comment by matallo** [comment]
haha, it's a bot ,it happens when issue # is on the branch name :joy:

**Comment by alonsogarciapablo** [comment]
@matallo cool!
