### ISSUE TITLE
403 forbidden error in a viz from public tables

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#2663]
Map works in editor but not in Embed. It's happening with the two public visualizations (from public tables) of the user:
http://jasoncwilson.cartodb.com/viz/6bb44e78-c342-11e4-9d1e-0e9d821ea90d/embed_map

```
_cdbc_4233557014_1(
{
errors: [
"Postgis Plugin: ERROR: permission denied for relation colorado_trailheads in executeQuery Full sql was: 'SELECT * FROM (select * from colorado_trailheads) as cdbq LIMIT 0' encountered during parsing of layer 'layer0' in Layer"
]
}
)
````

cc @Kartones @rafatower

SB/4608939

**Comment by iriberri** [comment]
bump, another one here: http://ngoaidmap.cartodb.com/viz/894fe92e-c8e2-11e4-85e0-0e9d821ea90d/embed_map

**Comment by amnesic** [comment]
We've the same problem with the getTitle API. A simple sql request as :  
sql: 'select * from mytablename'
-->  SELECT * FROM (select * from mytablename) as cdbq LIMIT 0
`
/**/ typeof _cdbc_1502644941_1 === 'function' && _cdbc_1502644941_1({"errors":["Postgis Plugin: ERROR:  relation \"ne_10m_populated_p_2\" does not exist\nLINE 1: SELECT * FROM (select * from ne_10m_populated_p_2) as cdbq L...\n                                     ^\n\nin executeQuery Full sql was: 'SELECT * FROM (select * from ne_10m_populated_p_2) as cdbq LIMIT 0'\n  encountered during parsing of layer 'layer0' in Layer"]});
`

**Comment by rafatower** [comment]
@amnesic the problem is not the same, it's not a permissions problem but presumably a missing table. Do you have a table called `ne_10m_populated_p_2`?

**Comment by amnesic** [comment]
Sorry, you're right. In my case it seems relation error not permission. 
But the table ne_10m_populated_p_2 exists (in public). I use sql_api_template and maps_api_template options like this :           
```
sql_api_template: 'https://www.mydomain.com/user/{user}',           
maps_api_template: 'https://www.mydomain.com/user/{user}',

```
(I'm using subdomainless URLs)

**Comment by amnesic** [comment]
The table was not found because my user didn't use the public schema but it own username schema.

**Comment by rafatower** [comment]
glad to see you managed to fix it :smiley:
