### ISSUE TITLE
Add button in wizards to remove an IMG icon once selected

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#2668]
From: https://github.com/CartoDB/cartodb/issues/2198

Once you select an icon in a wizard, you cannot get rid of it. Of course, you can edit CartoCSS but this is not user friendly :-)

**Comment by saleiva** [comment]
@carlostallon fixed this in the new designs  :)

**Comment by stevage** [comment]
This is still an issue on CartoDB.com. Editing CSS is not really a workaround, as it just comes straight back.

**Comment by iriberri** [comment]
Fun behaviour:

* In simple maps, the icon gets stuck.
* In category maps, this marker/color selector works in a different (maybe the desired approach) way: img lets you select the img, and the color part gets your point back. People reported this because they wanted to be able to "colour the icon" as they were able to do in simple maps... :)

cc @saleiva

**Comment by saleiva** [comment]
Assigning to @xavijam to see what we can do...

**Comment by xavijam** [comment]
Yep, agree with all of you, it is not straight forward and sometimes painful. But since it is gonna be fixed in the next "Forms" redesign, let me close this ticket for making pressure to have it as soon as possible :).

**Comment by stevage** [comment]
What's the ETA on that? This bug is pretty bad - I had to redesign one of my workshops around it. Originally I first showed people how to set colours and icons before moving onto other visualisations. But then they can never use the Simple visualisation again.

**Comment by iriberri** [comment]
@javisantana

**Comment by fdansv** [comment]
I've produced a bit of a midpoint solution: while we don't have an additional UI element, coming from the new design, what I propose in PR #3739 is:

* Changing the marker colour always switches back to default elliptical markers.
* However, switching to an icon retains the previously selected marker colour.

This allows for users to colorise their custom icon markers, while being able to switch back to the default style.

@saleiva tell me if you want to replicate this behaviour in the category wizard, and I'll open a new issue for it.

**Comment by saleiva** [comment]
yes please!
