### ISSUE TITLE
Notification user parameter: not enough obvious on new dashboard?

### ISSUE THREAD

**Issue by zenitraM** [CartoDB/cartodb#2671]
We have the notification user attribute to be able to display the user important notifications, we usually only use it for platform maintenance reasons:
 
![image](https://cloud.githubusercontent.com/assets/863975/6558186/d9131388-c67a-11e4-8fdb-928176c57d89.png)

However, on the new dashboard the user has to click on the ringbell to see the message:

![image](https://cloud.githubusercontent.com/assets/863975/6558228/3c369930-c67b-11e4-942e-68d217a9750a.png)

so the user would most probably miss it. 
Kinda defeats the purpose :(

cc @CartoDB/frontend @CartoDB/design

**Comment by saleiva** [comment]
We do have a notification element designed like this. It's a matter of using that layout for that particular type of notification I guess.
