### ISSUE TITLE
titles in error modals differ from non-error modals

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#2680]
![matallo cartodb](https://cloud.githubusercontent.com/assets/36676/6561185/872e3a1a-c68f-11e4-9433-7e223d3dadc5.png)
![matallo cartodb error](https://cloud.githubusercontent.com/assets/36676/6561186/8731ab5a-c68f-11e4-97f7-3438ffec17a3.png)

how to reproduce:
- overlap the images (or remove the error class in a modal window)

expected behaviour:
- keep same size and margins, change only color

actual behavour:
- when re-rendering the modal _jumps_ because of the change in the format

it smells to poorly extended with a `--modifier`

**Comment by viddo** [comment]
I think @xavijam is a better candidate to resolve this one, since he did these ones, reassigning

**Comment by xavijam** [comment]
Added to https://github.com/CartoDB/cartodb/issues/1786
