### ISSUE TITLE
Provide original file name (if it exists), in the import API

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#2695]
If the import api could provide that, we would avoid the problem below.

![screen shot 2015-03-10 at 15 52 53](https://cloud.githubusercontent.com/assets/132146/6577488/b3054e12-c73e-11e4-845f-ad4ef6f5afe7.png)

cc @javisantana  @saleiva

**Comment by saleiva** [comment]
minor

**Comment by rafatower** [comment]
AFAIK this is already done, closing this...

**Comment by rafatower** [comment]
The problem appears when reloading the page. Reopening this issue
