### ISSUE TITLE
Search doesn't seem to work correctly until you click on one of the 'tabs' close to it

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2701]
After clicking on your datasets, or shared with you it looks to be working fine

**Comment by viddo** [comment]
Can you clarify what you mean with "doesn't seem to work correctly"? And what "tabs" are you referring to?

**Comment by saleiva** [comment]
it doesn't give you results. 
"tabs" -> 
![screen shot 2015-03-10 at 18 40 54](https://cloud.githubusercontent.com/assets/132149/6581100/04c32bdc-c755-11e4-8640-3f69fd40a5c6.png)

**Comment by viddo** [comment]
I guess this was related to #2702, right? If still happens on production (should be fixed) re-open this issue please.

**Comment by saleiva** [comment]
uhm... looks like it's working! Thanks!
