### ISSUE TITLE
Enter button doesn't work on the searchbar

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2702]
This should be a hotfix, since there are some users already using the dashboard.

**Comment by saleiva** [comment]
cc/ @xavijam since a test might be needed for this.

**Comment by xavijam** [comment]
This is for @viddo.

**Comment by saleiva** [comment]
Also close button doesn't show up.

**Comment by xavijam** [comment]
A js error is making failed the whole component.

**Comment by viddo** [comment]
Found the issue and added tests to cover this, will merge & deploy promptly.

**Comment by viddo** [comment]
Deploying to production...

**Comment by viddo** [comment]
...done!
