### ISSUE TITLE
Invalid viz.json for visualisation with just one torque layer and private tables

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb#2705]
The viz.json for a visualisation without 

## STR
1. Create a points private table
1. Create a visualisation from it
1. Use a torque wizard

## Current result
The viz.json has two layers: `"type": "tiled"` for the basemap and `"type: torque"` for the data layer. The torque layer has a reference to its associated named map.

## Expected result
The viz.json should have three layers: `"type": "tiled"` for the basemap and `"type: torque"` for the data layer and the `"type: named"` for the named associated to the torque layer.

## More details
By adding an extra layer (a basic mapnik/cartodb one) the viz.json starts adding the expected `"type: named"`.

**Comment by rochoa** [comment]
cc @saleiva @javierarce

**Comment by Kartones** [comment]
After some local tests, this is the source of the issue:
```
if @visualization.layers(:cartodb).size == 0
```
```
layers = @visualization.layers(:cartodb)
```
Which according to the [vizjson spec](https://github.com/CartoDB/cartodb.js/blob/privacy-maps/doc/vizjson_format.md) is using the deprecated cartodb layer type, so if we only have a tiled layer + torque layer, it won't return the named map.

As far as I can remember (this code is from feb/mar 2014 when we built the Named Maps) all maps were supposed to have a `:cartodb` layer. Is it ok to add support for `:tiled` type? I see for example no `interactivity` field... 

cc @javisantana

**Comment by javisantana** [comment]
the expected result is **not** having 3 layers, is to have two layers, the tiled (for the base) and the torque.

the named map is still needed to get tiles for the torque layer.

**Comment by rochoa** [comment]
Thanks a lot for the valuable information and sorry for wasting your time :-1: 

I will create another issue to solve the problem in the client.
