### ISSUE TITLE
Design new bye-bye page when user deletes his/her account

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#2706]
cc @carlostallon @saleiva @piensaenpixel

**Comment by carlostallon** [comment]
Following design for this: https://github.com/CartoDB/cartodb/issues/4428

![bye bye](https://cloud.githubusercontent.com/assets/1712650/8674195/92944c58-2a3c-11e5-954e-2d1d012bb410.png)

**Comment by saleiva** [comment]
<3

**Comment by xavijam** [comment]
Should we place it in "website" instead of the editor? 
cc @juanignaciosl

**Comment by xavijam** [comment]
@javisantana, what do you think?

**Comment by saleiva** [comment]
Not a priority.

**Comment by javisantana** [comment]
if it's account management should be in central, right?

**Comment by juanignaciosl** [comment]
I think Central is the place, just as creation is there as well.
