### ISSUE TITLE
new filters in dashboard submenu

### ISSUE THREAD

**Issue by carlostallon** [CartoDB/cartodb#2713]
Take a look
![captura de pantalla 2015-03-11 a las 11 56 50](https://cloud.githubusercontent.com/assets/1712650/6594951/d609d9c6-c7e5-11e4-9f80-7730c0286977.png)

/cc @xavijam @saleiva @piensaenpixel

**Comment by piensaenpixel** [comment]
i think in this case we need the label "Order by:"
My 2 cents. :)

**Comment by carlostallon** [comment]
Yep, works better with "order by"

![captura de pantalla 2015-03-16 20 18 13](https://cloud.githubusercontent.com/assets/1712650/6674394/97aed28e-cc19-11e4-858b-7e0a9ddc3cc0.png)

**Comment by saleiva** [comment]
Like it. Do yo guys like this more than the icons version?

**Comment by carlostallon** [comment]
I prefer this one, less noise for the submenu IMO and in my particular case I don't need to use those filters often.

**Comment by xavijam** [comment]
I prefer the icons, but I don't have any regret to try this solution.

**Comment by xavijam** [comment]
What about this issue, is it still worth it to be implemented?

**Comment by carlostallon** [comment]
I think we can forget it by now
