### ISSUE TITLE
Clicking on the "Data library" link on the create modal removes the number on the shared datasets 

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2728]

**Comment by xavijam** [comment]
That's the number that comes from the visualization endpoint, so I guess this is a bug from the API. That means backend guys should take a look :S.

cc @juanignaciosl or @Kartones

**Comment by Kartones** [comment]
I'll take a look, but right now...
![](http://memecrunch.com/meme/DU49/i-don-t-know-what-you-re-talking-about/image.png)

**Comment by xavijam** [comment]
A request to remote data, like: 
```http://theteam.localhost.lan:3000/u/cartofante/api/v1/viz.json?tag_name=&q=&page=1&type=remote```

Returns:
```
{
  visualizations: […],
  total_entries: 66,
  total_user_entries: 62,
  total_likes: 0,
  total_shared: 0
}
``` 

Those last figures are the numbers those appear in the "new dashboard" subheader.

**Comment by Kartones** [comment]
Ok, and what does this have to do do with the Data Library? due to being "remote tables" the counters dissapear?

**Comment by juanignaciosl** [comment]
I'm not sure if this is a backend issue. This is the relevant data of the first request ('datasets' one):
```
total_entries: 24
total_likes: 0
total_shared: 24
total_user_entries: 274
```

Clicking at Data library "tab" (no need to go to the modal) returns this:
```
total_entries: 8
total_likes: 0
total_shared: 24
total_user_entries: 274
```

As you see, in spite of having `total_shared: 24` the number disappears.

**Comment by xavijam** [comment]
Uhm, you are right...
Overloaded!

**Comment by juanignaciosl** [comment]
Wow, not that fast. Clicking either "Datasets" or "Data Library" trigger 2 requests each:

Click datasets: 
1. https://team.cartodb.com/u/juanignaciosl/api/v1/viz/?tag_name=&q=&page=1&type=table&exclude_shared=true&per_page=20&tags=&only_shared=false&category=&locked=false&only_liked=false&order=updated_at
2. https://team.cartodb.com/u/juanignaciosl/api/v1/viz/?tag_name=&q=&page=1&type=table&exclude_shared=true&per_page=1&locked=true&only_shared=false&liked=false&tag=undefined

Click Data Library:
3. https://team.cartodb.com/u/juanignaciosl/api/v1/viz/?tag_name=&q=&page=1&type=remote&exclude_shared=true&per_page=20&tags=&only_shared=false&category=undefined&locked=false&only_liked=false&order=updated_at
4. https://team.cartodb.com/u/juanignaciosl/api/v1/viz/?tag_name=&q=&page=1&type=table&exclude_shared=true&per_page=1&locked=true&only_shared=false&liked=false&tag=undefined

Number 3 is the one that have 0 shared. I think first loads "unlocked" and second loads "locked". But the problem might be that `category=undefined`. Take a look. If you confirm request is ok and it's a backend issue feel free to assign it to me.

**Comment by xavijam** [comment]
I will take a look in my next available gap, don't worry.

**Comment by xavijam** [comment]
I've removed category parameter and seems like request is still returning 0, so sorry @juanignaciosl, seems like it is a backend bug, but if you find it is not, let me know please.
