### ISSUE TITLE
Replicate actual editor mockup in sketch

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2729]
We are gonna have to design some features on the actual editor, so we better have an sketch file with it.
I'd need to start designing the kepler integration monday next week, so can we prioritize this for after the tickets you have for the dashboard?

**Comment by carlostallon** [comment]
Yes, sure!

**Comment by carlostallon** [comment]
Done!
it's in .../webapp/12-classic-editor

**Comment by saleiva** [comment]
:clap: I love the name.
Thanks!
