### ISSUE TITLE
migrate pending mixpanel properties => hubspot

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#2735]
**events**
- [x] Applying CartoCSS style manually
- [x] Applying color as basemap
- [x] Applying a pattern as basemap
- [x] Applying filter
- [x] Choose a wizard
- [x] Click Publish Visualization
- [x] Common data clicked
- [x] Dashboard viewed
- [x] Dashboard viewed for the first time
- [x] Exported table data
- [x] Geocoding failed <- This should be Geocoding and save the status as metadata
- [x] Performing a query
- [x] Use visual merge
- [x] Import successful <- Save format, size and duration?
- [x] WMS layer selected
- [x] Visited Login page
- [x] Logged in
- [x] Open create table
- [x] Open create map

**Contact properties** removed, can be inferred from current events

- [ ] success_import_count
- [ ] publish_visualization_last_clicked
- [ ] table_count
- [ ] visualization_count
- [ ] failed_import_count
- [ ] last_visualization_created_at

**Tracked but not listed**

- [x] Geocoding admin
- [x] Geocoding zip
- [x] Geocoding world
- [x] Geocoding namedplace
- [x] Geocoding latlng
- [x] Geocoding ip
- [x] Geocoding address

**Discarded?**

- [x] Import started
- [x] Import failed
- [x] Marker file chosen for line-color
- [x] New color chose for marker-fill
- [x] New color chosen for polygon-fill
- [x] Pattern file chosen for polygon  fill
- [x] View byebye page
- [x] View Climate Page
- [x] Marked Spam
- [x] login_count `login_count`

**Comment by iriberri** [comment]
Moved from El Soto to Baeza.

**Comment by rafatower** [comment]
@matallo there's a js exception around these lines:

https://github.com/CartoDB/cartodb/blob/2735-hubspot/lib/assets/javascripts/cartodb/dashboard/entry.js#L124-L128

(cannot read property trigger of undefined)
