### ISSUE TITLE
Make visualization API work using several values in type attribute

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#2744]
https://github.com/CartoDB/cartodb/issues/2628#issuecomment-78289056 and also commented [here](https://github.com/CartoDB/cartodb/pull/2733)

Branch: new-dashboard-search

**Comment by juanignaciosl** [comment]
@xavijam as I've told you, I've added `types` parameter instead of overloading current `type` parameter accepting multiple types, simpler, safer and much cleaner. Please let me know if you have any problem integrating it in the frontend.

**Comment by xavijam** [comment]
perfect, don't close the issue please :)

**Comment by juanignaciosl** [comment]
@xavijam I've tested the following combinations of type and types, with a query on one word. This user has 91 tables, 3 visualizations (and +70 remotes). There's one matching table, map and remote for that word.

type | types | total_entries | user_entries
----- | -------- | ---------------- | -----------------
 | | 3 | 91
'' | | 3 | 91
 | '' | 3 | 91
'' | '' | 3 | 91
table | | 1 | 91
derived | | 1 | 3
remote | | 1 | 91
 | table | 1 | 91
 | derived | 1 | 3
 | remote | 1 | 91
 | table,derived | 2 | 3
 | table,derived,remote | 3 | 3

I'm not so sure about "shared" and "liked" counters, but I'd first want to confirm the main part (table, derived, remote) is ok and move on.
