### ISSUE TITLE
Update Editor Menu Names to Match New Dashboard

### ISSUE THREAD

**Issue by michellechandra** [CartoDB/cartodb#2748]
Change editor menu names that refer to "tables" to "datasets" and "visualizations" to "maps"

Edit Menu prior to sharing visualization:
![screen shot 2015-03-12 at 3 04 42 pm](https://cloud.githubusercontent.com/assets/5423288/6625879/421b0af2-c8c9-11e4-9920-42c6f95b8b02.png)

Edit Menu after share visualization:
![screen shot 2015-03-12 at 3 03 44 pm](https://cloud.githubusercontent.com/assets/5423288/6625892/61108e46-c8c9-11e4-9032-e42149bfe510.png)

Edit Menu after share visualization in Map View:
![screen shot 2015-03-12 at 3 14 21 pm](https://cloud.githubusercontent.com/assets/5423288/6626059/83aedd12-c8ca-11e4-857f-90e5e8554046.png)

Visualize Menu
![screen shot 2015-03-12 at 3 04 50 pm](https://cloud.githubusercontent.com/assets/5423288/6625928/9fd4f4a0-c8c9-11e4-9945-b8841de210f6.png)

Share Menu Option:
![screen shot 2015-03-12 at 3 03 20 pm](https://cloud.githubusercontent.com/assets/5423288/6625939/b7ef4d56-c8c9-11e4-8518-c0c53f506665.png)

Visualization Metadata
![screen shot 2015-03-12 at 3 03 03 pm](https://cloud.githubusercontent.com/assets/5423288/6625944/c00dbc7a-c8c9-11e4-88e2-5ab718f34487.png)

Table metadata
![screen shot 2015-03-12 at 3 11 38 pm](https://cloud.githubusercontent.com/assets/5423288/6626007/241594b8-c8ca-11e4-8dc6-2867b152ee1e.png)

**Comment by saleiva** [comment]
To be done just before releasing the new dashboard. Thanks!

**Comment by michellechandra** [comment]
@saleiva - Will "Visualization wizard" be updated to "map wizard"?

![screen shot 2015-03-12 at 3 28 22 pm](https://cloud.githubusercontent.com/assets/5423288/6626363/761cf1d2-c8cc-11e4-858e-c40c32ed0fc9.png)

**Comment by saleiva** [comment]
Yep!

**Comment by saleiva** [comment]
@xavijam is this done? If not, we should do it ASAP

**Comment by xavijam** [comment]
Text and so on, no problem. But if we want to change urls, this would be a big(problem) task...

**Comment by saleiva** [comment]
Not URLs yet. Only texts for the time being

**Comment by xavijam** [comment]
Roger!
