### ISSUE TITLE
iframe overlays are not responsive

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#2767]
Take a look at this example,

http://blog.plot.ly/post/113492277297/three-things-that-you-can-do-to-explain-your-data

I'm seeing it more and more that people combine legends with torque, or annotations with anything and our iframes can't really handle it. needs a refresh :)

**Comment by andrewxhill** [comment]
Another example also from today's news,

http://national.suntimes.com/national-politics/7/72/787276/data-divide-school-funding-rich-poor

the legends don't collide, but they do start taking up like 30% of the map

**Comment by saleiva** [comment]
Yay! Closing as duplicated :)
