### ISSUE TITLE
Better placeholder on the plans tab when being on the free one.

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2771]
In that particular scenario we can be nicer on asking for upgrade or even to talk about how cool is to be on the free plan.

**Comment by saleiva** [comment]
![user config - plan free](https://cloud.githubusercontent.com/assets/132149/7004632/a9c56fae-dc6e-11e4-8678-29131f506c36.png)
Done

**Comment by saleiva** [comment]
@matallo all yours!

**Comment by matallo** [comment]
need the literal for "Dedicated Support"

**Comment by matallo** [comment]
nevermind, from website: "Get an exclusive communication channel with our team for speedy support."

**Comment by saleiva** [comment]
lovely

**Comment by saleiva** [comment]
bump!

**Comment by matallo** [comment]
have it done, it was a matter of the icons I needed @piensaenpixel for

as in website I'll make nobody's a blocker for the icon generation https://github.com/CartoDB/website/tree/master/icon_font

**Comment by matallo** [comment]
finally went with image icons, but is ready :(
