### ISSUE TITLE
Tags overlap footer in map card

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#2773]
![captura de pantalla 2015-03-14 a las 11 36 23](https://cloud.githubusercontent.com/assets/390398/6651344/9cc09816-ca3e-11e4-9cd7-8f432365be9d.png)

**Comment by xavijam** [comment]
Woah, long tags :D

**Comment by alonsogarciapablo** [comment]
@xavijam This is how it looks with a CSS only approach. I'm basically using the same code we're using for the description. By default, we show 3 tags, and X more if there are more. And if it doesn't fit in 2 lines, we show the ellipsis. What do you think?

![captura de pantalla 2015-03-23 a las 11 57 58](https://cloud.githubusercontent.com/assets/390398/6778557/e3c8aea8-d153-11e4-9a0f-3c24bb0973ae.png)


![captura de pantalla 2015-03-23 a las 11 53 29](https://cloud.githubusercontent.com/assets/390398/6778511/73a4ce36-d153-11e4-81a8-9136f53687ba.png)

![captura de pantalla 2015-03-23 a las 11 54 23](https://cloud.githubusercontent.com/assets/390398/6778512/76078df8-d153-11e4-96a6-7f84d056e721.png)

I feel that we need some space after the tags. It looks very tight when there's a long description:

![captura de pantalla 2015-03-23 a las 11 59 04](https://cloud.githubusercontent.com/assets/390398/6778575/150e8afa-d154-11e4-9392-ededb39a601e.png)

**Comment by xavijam** [comment]
For me looks good, @saleiva?

**Comment by alonsogarciapablo** [comment]
@saleiva what do you think of this? thanks!

**Comment by saleiva** [comment]
What about leaving the tags in just one line and adding the gradient in the same way we do with the description?

**Comment by alonsogarciapablo** [comment]
We can try and see how it looks. Is it okay then to "hide" the "X more" text if everything doesn't fit in one/two lines?

**Comment by saleiva** [comment]
yeah I think so

**Comment by alonsogarciapablo** [comment]
@saleiva this is how it looks with your proposed solution:

![captura de pantalla 2015-03-24 a las 13 40 29](https://cloud.githubusercontent.com/assets/390398/6801804/723aa628-d22b-11e4-83a9-0ab0a959caca.png)

**Comment by saleiva** [comment]
+1
