### ISSUE TITLE
Lines converted to points when georeference by lon/lat without warning

### ISSUE THREAD

**Issue by Xatpy** [CartoDB/cartodb#2803]
I'm opening this issue about a little "comment" that I realised while I was testing. It's not important, but I think that it would be useful in case you (@CartoDB/Design) want to think about this in the new editor design.

The issue is that if you have a lines dataset and you click on georeference by lon/lat (for example with a new row), all the dataset is converted automatically, without any warning. And then, you can't "undo" (at least easily) and having your "clear" lines dataset.

*Steps to reproduce:*
1. Import a lines dataset.
2. Create a new row (optional).
3. Click on Georeference by lon/lat.
-> Result: All rows are points.

*Gif:*
![lines_to_points](https://cloud.githubusercontent.com/assets/3958416/6689264/5ce49e68-ccb9-11e4-854d-e5f1e8d23917.gif)

My opinion is that it's not a bug; but, **at least**, the user should be warned about the fact. 
So, my *"proposal"* is that a modal window should appear in cases like this (when your data is going to change) .

**Comment by saleiva** [comment]
Yep, you can close it, we already took care of this :) 
Thaaaanks!

**Comment by Xatpy** [comment]
Oh, great! :clap: 
thank you too!
