### ISSUE TITLE
Quota value in dropdown incorrect

### ISSUE THREAD

**Issue by Xatpy** [CartoDB/cartodb#2804]
In my configuration --> account page, I have this:
1.27 GB of 1.95 GB used
![screen shot 2015-03-17 at 16 17 45](https://cloud.githubusercontent.com/assets/3958416/6690591/c18443fc-ccc1-11e4-881a-e926620863ea.png)

But, in the dropdown I have:
1.27GB of **1GB** used
![screen shot 2015-03-17 at 16 17 53](https://cloud.githubusercontent.com/assets/3958416/6690609/db176b0a-ccc1-11e4-88eb-0e610ac71760.png)

So, I'm thinking about that it could be a problem 'fixing' the number of decimals.

**Comment by viddo** [comment]
Will be released together with #2741 (piggyback on the existing PR)
