### ISSUE TITLE
Reduce polygon stroke opacity to <1

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#2810]
Right now, if you load a ton of small polygons they

a) End up on the light basemap
b) Have 1px polygon stroke that is white and full opaque

So you end up not being able to see anything on the map unless you know the trick.

I'd say something like 0.5-0.8 could fix it, but worth experimenting

**Comment by javisantana** [comment]
I find this pretty interesting. Should the default wizard change depending on the data ?

**Comment by andrewxhill** [comment]
Would be the best, yeah.

**Comment by saleiva** [comment]
There is even a wiki page talking about that :)
Famous Map recommendation API :)

**Comment by andrewxhill** [comment]
totally, we should do that. but while we wait.... just drop the line
opacity, or change it black or something :)

On Wed, Mar 18, 2015 at 7:34 AM, saleiva <notifications@github.com> wrote:

> There is even a wiki page talking about that :)
> Famous Map recommendation API :)
>
>
> > On 18 Mar 2015, at 11:09, Andrew W. Hill <notifications@github.com>
> wrote:
> >
> > Would be the best, yeah.
> > On Mar 18, 2015 7:51 AM, "javi santana" <notifications@github.com>
> wrote:
> >
> > > I find this pretty interesting. Should the default wizard change
> depending
> > > on the data ?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/CartoDB/cartodb/issues/2810#issuecomment-82801837
> >.
> > >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/CartoDB/cartodb/issues/2810#issuecomment-82867425>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/2810#issuecomment-82917935>.
>



-- 

andrewxhill <http://twitter.com/andrewxhill>
http://cartodb.com

**Comment by saleiva** [comment]
I think that with line-width: 0.5 we fix this temporarly.

**Comment by alonsogarciapablo** [comment]
Are we talking about making 0.5 the default Polygon Stroke Opacity?

![captura de pantalla 2015-04-24 a las 11 55 41](https://cloud.githubusercontent.com/assets/390398/7316636/e99788b6-ea78-11e4-95f7-7dd9aee89412.png)

**Comment by alonsogarciapablo** [comment]
Or changing the `line-opacity` CartoCSS property?

![captura de pantalla 2015-04-24 a las 12 10 58](https://cloud.githubusercontent.com/assets/390398/7316873/09cc1118-ea7b-11e4-9468-30649143f78f.png)

**Comment by saleiva** [comment]
polygon-stroke :)

**Comment by alonsogarciapablo** [comment]
I've seen that we share that configuration with other wizards (Category and Color) too. Should we change it everywhere or just in this particular case?

**Comment by saleiva** [comment]
all defaults.
