### ISSUE TITLE
302 error downloading csv source

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#2815]
Trace: https://cartodb.com/superadmin/users/58607/data_imports/be0ece69-b82b-48b4-9617-006f69a48fa8

cc @saleiva

**Comment by Kartones** [comment]
Seems the issue is [gnutls](https://github.com/taf2/curb/issues/217).

Upgrading my dev env to use `libcurl-openssl` everything works fine. Else I get TSL errors reading the certificate

**Comment by azamorano** [comment]
Fixed installing libcurl4-openssl-dev instead.
