### ISSUE TITLE
public tables header have more columns that values

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#2816]
![screen shot 2015-03-18 at 10 34 59 am](https://cloud.githubusercontent.com/assets/30147/6706051/846a2aec-cd5a-11e4-9a1f-139d8b839519.png)

I guess is because we don't request the_geom_webmercator

**Comment by alonsogarciapablo** [comment]
@javisantana should the `the_geom_webmercator` column be there? should we populate it?

I've noticed that this column is not visible in the private view...

**Comment by alonsogarciapablo** [comment]
Also, since it's related to `the_geom`, should they be together?

**Comment by javisantana** [comment]
no, the_geom_webmercator should not be visible

**Comment by alonsogarciapablo** [comment]
The `the_geom_webmercator` column [is not being removed from the schema](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/models/table.js#L493-L496). I have to keep investigating why.

**Comment by xavijam** [comment]
I'd remote it from the view, but not sure if we should remove it from the (js) schema directly.
