### ISSUE TITLE
Add "Export layer" when a query is applied in a Map

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#2820]
### STEPS TO REPRODUCE:
- Create a map/visualization with several layers.
- Apply a query in any of those layers.
- Click on the 'edit' link (upper right).
- Export layer doesn't appear as an option.

Ideally, we should let users export the current selected query layer as we do in table view.

**Comment by alonsogarciapablo** [comment]
@iriberri this has just been deployed to production. I've been playing with it and it seems to be working as expected. Perhaps you can also play with it and make sure is :+1:

**Comment by iriberri** [comment]
Sure, I'm always in this usecase so I'll let you know when I start using it
tomorrow :-) thank you so much, it's a big usability enhancement for me!

On Wednesday, March 25, 2015, Pablo Alonso <notifications@github.com> wrote:

> @iriberri <https://github.com/iriberri> this has just been deployed to
> production. I've been playing with it and it seems to be working as
> expected. Perhaps you can also play with it and make sure is [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/2820#issuecomment-86154801>.
>


-- 

Carla Iriberri
*CartoDB*

**Comment by alonsogarciapablo** [comment]
Thanks!

**Comment by iriberri** [comment]
:+1: :smile:
