### ISSUE TITLE
 overlay was added in the Editor but it didn't appear in the embed

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#2822]
From SB/4823339:

An overlay was added in the Editor but it didn't appear in the embed. The code in the viz.json file was (yes, the annotation appeared):

````
{
id: "2ba85e90-cd5c-11e4-bb4b-7054d21a95e5",
version: "0.1.0",
title: "Vanuatu",
likes: 0,
description: null,
scrollwheel: true,
legends: false,
url: null,
map_provider: "leaflet",
bounds: [
[
-26.843677401113002,
147.65625
],
[
-9.99049080307028,
178.74755859375
]
],
center: "[-18.625424540701264, 163.201904296875]",
zoom: 6,
updated_at: "2015-03-18T10:47:58+00:00",
layers: [
{
options: {
id: "c90e54cc-46a9-4493-a048-87f5bcd3f042",
order: 0,
visible: true,
type: "Tiled",
name: "Positron",
className: "default positron_rainbow",
base_type: "positron_rainbow",
urlTemplate: "http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png",
read_only: true,
minZoom: "0",
maxZoom: "18",
attribution: "© <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors © <a href= "http://cartodb.com/attributions#basemaps">CartoDB</a>",
subdomains: "abcd",
category: "CartoDB"
},
infowindow: null,
tooltip: null,
id: "c90e54cc-46a9-4493-a048-87f5bcd3f042",
order: 0,
parent_id: null,
children: [ ],
type: "tiled"
},
{
type: "namedmap",
order: 1,
options: {
type: "namedmap",
user_name: "livsr",
tiler_protocol: "http",
tiler_domain: "cartodb.com",
tiler_port: "80",
cdn_url: {
http: "api.cartocdn.com",
https: "cartocdn.global.ssl.fastly.net"
},
dynamic_cdn: false,
named_map: {
name: "tpl_2ba85e90_cd5c_11e4_bb4b_7054d21a95e5",
stat_tag: "2ba85e90-cd5c-11e4-bb4b-7054d21a95e5",
params: {
layer0: 1
},
layers: [
{
layer_name: "vanuatu",
interactivity: "cartodb_id",
visible: true
}
]
}
}
}
],
overlays: [
{
type: "zoom",
order: 6,
options: {
display: true,
x: 20,
y: 20
},
template: "<a href="#zoom_in" class="zoom_in">+</a> <a href="#zoom_out" class="zoom_out">-</a>"
},
{
type: "loader",
order: 8,
options: {
display: true,
x: 20,
y: 150
},
template: "<div class="loader" original-title=""></div>"
},
{
type: "annotation",
order: 1,
options: {
device: "desktop",
display: true,
style: {
z-index: 4,
color: "#ffffff",
text-align: "left",
font-size: "13",
font-family-name: "Helvetica",
box-color: "#FF2900",
box-opacity: 1,
box-padding: 6,
line-color: "#FF2900",
line-width: 50,
min-zoom: 0,
max-zoom: 40
},
extra: {
latlng: [
-17.224758206624628,
168.5302734375
],
text: "**Vanuatu**",
rendered_text: "<strong>Vanuatu</strong>"
}
},
template: null
}
],
prev: null,
next: null,
transition_options: {
time: 0
}
}
````

After changing slightly the position of the annotation in the Editor, the embed was now showing the annotation. Viz.json after the change was this one (probably the same) but with different coordinates:

````
{
id: "2ba85e90-cd5c-11e4-bb4b-7054d21a95e5",
version: "0.1.0",
title: "Vanuatu",
likes: 0,
description: null,
scrollwheel: true,
legends: false,
url: null,
map_provider: "leaflet",
bounds: [
[
-26.843677401113002,
147.65625
],
[
-9.99049080307028,
178.74755859375
]
],
center: "[-18.625424540701264, 163.201904296875]",
zoom: 6,
updated_at: "2015-03-18T10:47:58+00:00",
layers: [
{
options: {
id: "c90e54cc-46a9-4493-a048-87f5bcd3f042",
order: 0,
visible: true,
type: "Tiled",
name: "Positron",
className: "default positron_rainbow",
base_type: "positron_rainbow",
urlTemplate: "http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png",
read_only: true,
minZoom: "0",
maxZoom: "18",
attribution: "© <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors © <a href= "http://cartodb.com/attributions#basemaps">CartoDB</a>",
subdomains: "abcd",
category: "CartoDB"
},
infowindow: null,
tooltip: null,
id: "c90e54cc-46a9-4493-a048-87f5bcd3f042",
order: 0,
parent_id: null,
children: [ ],
type: "tiled"
},
{
type: "namedmap",
order: 1,
options: {
type: "namedmap",
user_name: "livsr",
tiler_protocol: "http",
tiler_domain: "cartodb.com",
tiler_port: "80",
cdn_url: {
http: "api.cartocdn.com",
https: "cartocdn.global.ssl.fastly.net"
},
dynamic_cdn: false,
named_map: {
name: "tpl_2ba85e90_cd5c_11e4_bb4b_7054d21a95e5",
stat_tag: "2ba85e90-cd5c-11e4-bb4b-7054d21a95e5",
params: {
layer0: 1
},
layers: [
{
layer_name: "vanuatu",
interactivity: "cartodb_id",
visible: true
}
]
}
}
}
],
overlays: [
{
type: "zoom",
order: 6,
options: {
display: true,
x: 20,
y: 20
},
template: "<a href="#zoom_in" class="zoom_in">+</a> <a href="#zoom_out" class="zoom_out">-</a>"
},
{
type: "loader",
order: 8,
options: {
display: true,
x: 20,
y: 150
},
template: "<div class="loader" original-title=""></div>"
},
{
type: "annotation",
order: 1,
options: {
device: "desktop",
display: true,
style: {
z-index: 4,
color: "#ffffff",
text-align: "left",
font-size: "13",
font-family-name: "Helvetica",
box-color: "#FF2900",
box-opacity: 1,
box-padding: 6,
line-color: "#FF2900",
line-width: 50,
min-zoom: 0,
max-zoom: 40
},
extra: {
latlng: [
-17.26672782352052,
168.48632812499997
],
text: "**Vanuatu**",
rendered_text: "<strong>Vanuatu</strong>"
}
},
template: null
}
],
prev: null,
next: null,
transition_options: {
time: 0
}
}
````

**Probably caused for the annotation to be just in the border of a tile?**

Image after the change:
![image](https://cloud.githubusercontent.com/assets/1730320/6707816/f9434212-cd6a-11e4-9aa7-0da7ef59d744.png)

====

When working on the Editor with overlays in a pretty poor Internet connection:

1. Add an annotation
2. Customize it. It becomes a little bit crazy and the annotation starts moving and changing. Some time after it stops.
3. Go to embed: what is in the Editor is not really there, there are different things and positions in general
4. Come back to Editor: delete the overlay. More than 5 overlays with the same text (but usually the default style) have been created under the one you removed.

cc @saleiva @javierarce

**Comment by alonsogarciapablo** [comment]
I see two different issues here: the problem with the annotation in Vanuatu, and the problem of editing annotations with a very slow internet connection.

I haven't been able to reproduce the one with the annotation in Vanuatu. I've played a bit with annotations and I always see them in the embed. @iriberri have you been able to reproduce this?

![captura de pantalla 2015-03-18 a las 15 56 21](https://cloud.githubusercontent.com/assets/390398/6711628/6ef4de54-cd88-11e4-8c86-d363d21efe61.png)

As for the second problem. I've been able to somehow reproduce it by making a lot of changes to an annotation/title/text with a slow internet connection. It enters an infinite loop of PUT requests to '/api/v1/viz/XXXXX/overlays/YYYYY'.

![crazy_annotation](https://cloud.githubusercontent.com/assets/390398/6711626/6950e5c4-cd88-11e4-827d-bffed00b3171.gif)

I'm going to investigate this one a bit more.

**Comment by iriberri** [comment]
It's not the first time that we add an annotation or another overlay and it doesn't appear in the embed, but it's not reproducible easily.

The funny fact here is that in this case the annotation was saved in the viz.json, but the embed wasn't loading it. 


Yep, the second issue is totally what I mentioned. Feel free to move it to a separate ticket, I just opened this one as general feedback.

**Comment by javisantana** [comment]
> It enters an infinite loop of PUT requests to '/api/v1/viz/XXXXX/overlays/YYYYY'.

this happens not only in overlays so if you can reproduce it, could you write the steps?

**Comment by alonsogarciapablo** [comment]
@javisantana I have created #2827 with the steps to reproduce. I will take a look.

**Comment by alonsogarciapablo** [comment]
@iriberri @javisantana what should we do with this issue? I wasn't able to reproduce the problem with the annotation not being displayed in the embed... I would close this issue and reopen it if we encounter it again and we can have a bit more info...

**Comment by iriberri** [comment]
I'm not been able neither. I've tried placing annotations on the edge of the tiles but didn't provoke the issue.

**Comment by alonsogarciapablo** [comment]
Ok. Closing it then until it happens again. Thanks!
