### ISSUE TITLE
undefined method at new dashboard

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#2826]
ActionView::Template::Error: undefined method `[]' for nil:NilClass
1
File "/home/ubuntu/www/production.cartodb.com/releases/20150318142015/app/views/admin/visualizations/new-dashboard.html.erb", line 12 in block in _app_views_admin_visualizations_new_dashboard_html_erb__137368239893328608_48188100
... 4 non-project frames
6
File "/home/ubuntu/www/production.cartodb.com/releases/20150318142015/app/views/admin/visualizations/new-dashboard.html.erb", line 4 in _app_views_admin_visualizations_new_dashboard_html_erb__137368239893328608_48188100
... 30 non-project frames
37
File "/home/ubuntu/www/production.cartodb.com/releases/20150318142015/app/controllers/admin/visualizations_controller.rb", line 41 in block (2 levels) in index
... 2 non-project frames
40
File "/home/ubuntu/www/production.cartodb.com/releases/20150318142015/app/controllers/admin/visualizations_controller.rb", line 40 in index
... 6 non-project frames
47
File "/home/ubuntu/www/production.cartodb.com/releases/20150318142015/app/controllers/application_controller.rb", line 41 in wrap_in_profiler
... 67 non-project frames

cc @iriberri

https://rollbar.com/vizzuality/CartoDB/items/4943/

**Comment by xavijam** [comment]
Seems like a problem with mixpanel keys? -> https://github.com/CartoDB/cartodb/blob/master/app/views/admin/visualizations/new-dashboard.html.erb#L12

cc @viddo and @matallo

**Comment by viddo** [comment]
That file and line have not been changed since [Dec 2nd](https://github.com/CartoDB/cartodb/blame/master/app/views/admin/visualizations/new-dashboard.html.erb#L12), my bet is some config changed recently. :/

**Comment by xavijam** [comment]
I'm with you @viddo, @lbosque @zenitraM, any clue?

**Comment by santisaez** [comment]
Seems it's related with Chaleco's cloud, most probably this config key is missing in this environment, researching..

**Comment by lbosque** [comment]
It fails because of this:

13:     var defaultFallbackMapBaselayer = <%= raw Cartodb.config[:basemaps].present? ? Cartodb.config[:basemaps]['CartoDB']['positron_rainbow'].to_json : '{}' %>;

It checks that there are basemaps keys but not that there are CartoDB basemaps. In google cloud there are not cartodb basemaps. So, either we fix that line so it is like:

var defaultFallbackMapBaselayer = <%= raw Cartodb.config[:basemaps].present? && Cartodb.config[:basemaps][:CartoDB].present? ? Cartodb.config[:basemaps]['CartoDB']['positron_rainbow'].to_json : '{}' %>;

Or we change that line to query for google maps cloud depending on the install. 

In any case my suggestion should be applied. In my opinion it's a bug

/cc @javisantana

**Comment by lbosque** [comment]
Ey ey @xavijam . My message was about taking a decission.

If the decission is about just fixing that line and leaving google cloud accouns without defaultFallbackMapBaselayer I'm ok by doing it myself.

Is that what we want?

**Comment by javisantana** [comment]
https://github.com/CartoDB/cartodb/blob/master/app/views/admin/visualizations/new-dashboard.html.erb#L13

it is a bug for sure, we can not harcore the name of a basemap. Or either we have that by config or chose the first one

**Comment by lbosque** [comment]
So, besides fixing the bug of not checked nil[] what do you, guys, suggest to get the default basemap?
Do we set the default one in the app_config?

**Comment by javisantana** [comment]
yes

**Comment by lbosque** [comment]
Ok, positron for normal CartoDB "cloud" and which google maps basemap should be set as default for gce? Any suggestion?

**Comment by viddo** [comment]
To put this in perspective, the use-case for this setting is for new users who have no maps yet (for which a default map is displayed), used for both onboarding and new public pages, e.g. ![screen shot 2015-03-20 at 12 49 36](https://cloud.githubusercontent.com/assets/978461/6750924/9c04d340-ceff-11e4-89fc-9f73cc597eea.png)

This fallback basemap is used to create a [fake vis through cartodb.js with this `defaultFallbackMapBaselayer`](https://github.com/CartoDB/cartodb/blob/dc3cbba77d26c0acbcf5d70476199df76aaa5d55/lib/assets/javascripts/cartodb/new_common/views/create_default_fallback_map.js#L13-L31), could this be done through cartodb.js without having to pass a baselayer? If so we could remove this config fetch altogether.

If not, the proposal of "chose the first one" would look like:
```erb
var defaultFallbackMapBaselayer = <%= raw Cartodb.config[:basemaps].present? ? Cartodb.config[:basemaps].values.first.values.first.to_json : '{}' %>;
```
...but it's brittle and prone to err again if/when the basemaps config structure changes. Also has the downside of not being able to control what fallback basemap is used. So using a specific config entry might be preferrable. If so, what basemaps are available on gce?

**Comment by javisantana** [comment]
just fixed it in https://github.com/CartoDB/cartodb/commit/bde5e3c627cdba8c777e0a4c5ee21c9e86f85d53

**Comment by xavijam** [comment]
:dancer:

**Comment by javisantana** [comment]
not actually fixed :D

**Comment by lbosque** [comment]
This was fixed with the default basemap config
