### ISSUE TITLE
Infinite loop of PUT requests when editing a title/text/annotation item over a slow connection

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#2827]
**Steps to reproduce:**

- Open Google Chrome DevTools.
- Limit the maximum download throughput in Google Chrome ([instructions here](https://developer.chrome.com/devtools/docs/device-mode#network-conditions)).
- Add a title/text/annotation overlay to a visualization.
- Change multiple things (backgrounds, borders, text alignment) on the overlay **very quickly**.

**Current behavior:**

- An infinite number of PUT requests to update the item is made and the state is never saved, causing the overlay to flicker.

![crazy_annotation](https://cloud.githubusercontent.com/assets/390398/6713041/4817589a-cd90-11e4-89e8-317f4e95acfd.gif)

**Expected behavior:**

- Changes are persisted and item does not flicker.

cc/ @javisantana

**Comment by javisantana** [comment]
if you can reproduce it, could you add a breakpoint in Backbone.sync and paste the stacktrace ? (enable the async button in developer tools)

**Comment by alonsogarciapablo** [comment]
```
Backbone.sync (cdb.js:50952)
_.extend.save (cdb.js:909)
cdb.core.Model.Backbone.Model.extend.save (cdb.js:21556)
cdb.admin.overlays.Text.cdb.geo.ui.Text.extend._applyStyle (table.js:37652)
applyStyle (table.js:37316)
Backbone.Events.trigger (cdb.js:676)
_.extend.change (cdb.js:986)
_.extend.set (cdb.js:827)
_.extend.save.options.success (cdb.js:898)
f.Callbacks.o (cdb.js:25)
f.Callbacks.p.fireWith (cdb.js:25)
w (cdb.js:27)
f.support.ajax.f.ajaxTransport.send.d (cdb.js:27)
XMLHttpRequest.send (async)
f.support.ajax.f.ajaxTransport.send (cdb.js:27)
f.extend.ajax (cdb.js:27)
Backbone.sync (cdb.js:1872)
Backbone.sync (cdb.js:50958)
_.extend.save (cdb.js:909)
cdb.core.Model.Backbone.Model.extend.save (cdb.js:21556)
cdb.admin.overlays.Text.cdb.geo.ui.Text.extend._applyStyle (table.js:37652)
applyStyle (table.js:37316)
Backbone.Events.trigger (cdb.js:676)
_.extend.change (cdb.js:986)
_.extend.set (cdb.js:827)
_.extend.save.options.success (cdb.js:898)
f.Callbacks.o (cdb.js:25)
f.Callbacks.p.fireWith (cdb.js:25)
w (cdb.js:27)
f.support.ajax.f.ajaxTransport.send.d (cdb.js:27)
XMLHttpRequest.send (async)
f.support.ajax.f.ajaxTransport.send (cdb.js:27)
f.extend.ajax (cdb.js:27)
Backbone.sync (cdb.js:1872)
Backbone.sync (cdb.js:50958)
_.extend.save (cdb.js:909)
cdb.core.Model.Backbone.Model.extend.save (cdb.js:21556)
cdb.admin.overlays.Text.cdb.geo.ui.Text.extend._applyStyle (table.js:37652)
applyStyle (table.js:37316)
Backbone.Events.trigger (cdb.js:676)
_.extend.change (cdb.js:986)
_.extend.set (cdb.js:827)
_.extend.save.options.success (cdb.js:898)
f.Callbacks.o (cdb.js:25)
f.Callbacks.p.fireWith (cdb.js:25)
w (cdb.js:27)
f.support.ajax.f.ajaxTransport.send.d (cdb.js:27)
XMLHttpRequest.send (async)
f.support.ajax.f.ajaxTransport.send (cdb.js:27)
f.extend.ajax (cdb.js:27)
Backbone.sync (cdb.js:1872)
Backbone.sync (cdb.js:50958)
_.extend.save (cdb.js:909)
cdb.core.Model.Backbone.Model.extend.save (cdb.js:21556)
cdb.admin.overlays.Text.cdb.geo.ui.Text.extend._applyStyle (table.js:37652)
applyStyle (table.js:37316)
Backbone.Events.trigger (cdb.js:676)
_.extend.change (cdb.js:986)
_.extend.set (cdb.js:827)
_.extend.save.options.success (cdb.js:898)
f.Callbacks.o (cdb.js:25)
f.Callbacks.p.fireWith (cdb.js:25)
w (cdb.js:27)
f.support.ajax.f.ajaxTransport.send.d (cdb.js:27)
XMLHttpRequest.send (async)
f.support.ajax.f.ajaxTransport.send (cdb.js:27)
f.extend.ajax (cdb.js:27)
Backbone.sync (cdb.js:1872)
Backbone.sync (cdb.js:50958)
_.extend.save (cdb.js:909)
cdb.core.Model.Backbone.Model.extend.save (cdb.js:21556)
cdb.admin.overlays.Text.cdb.geo.ui.Text.extend._applyStyle (table.js:37652)
applyStyle (table.js:37316)
Backbone.Events.trigger (cdb.js:676)
_.extend.change (cdb.js:986)
_.extend.set (cdb.js:827)
cdb.admin.OverlayPropertiesBar.cdb.core.View.extend._setStyle (table.js:81828)
Backbone.Events.trigger (cdb.js:676)
_.extend.change (cdb.js:993)
cdb.forms.TextAlign.cdb.core.View.extend._fireChange (table.js:37193)
w.debounce.o (cdb.js:27)
```

**Comment by alonsogarciapablo** [comment]
I spent some time researching this. I initially thought it had something to do with the fact that we are using a [debounced version of `_fireChange`](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/common/forms/widgets.js#L275-L278), but I don't think that's the cause.

I think this is caused because of the way Backbone works. According to the code:
```
`model.save` sets a hash of model attributes, and syncs the model to the server.
If the server returns an attributes hash that differs, the model's state will be
`set` again.
```

This is happening when multiple changes are applied to a model and the internet connection is slow. When [Backbone runs the success callback of the `save` function, it sets the new attributes on a "dirty" model](https://github.com/CartoDB/cartodb.js/blob/b71d2223633db21d07c0ecea35326e29ccd7a201/vendor/backbone.js#L375-L391). Because the model is "dirty", [a "change" event is triggered](https://github.com/CartoDB/cartodb.js/blob/b71d2223633db21d07c0ecea35326e29ccd7a201/vendor/backbone.js#L314), and [`_applyStyle`](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/table/overlays/text.js#L365-L416) starts again.

@javisantana. I would say this could happen elsewhere if we were able to update a model so quickly on a slow internet connection. Don't you think?

**Comment by alonsogarciapablo** [comment]
Hey @javisantana, not sure if you had a chance to take a look at this. I will hand it over to you.

**Comment by javisantana** [comment]
I found the problem, basically the it's due the model breaks one of the most important rules:

Always call save as a result of user interaction, never do it from a model trigger

see https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/table/overlays/annotation.js#L102-L110

style saves the model, so what is happening here:

1) user changes something -> the style is changed (value: 1)-> save
2) user changes something -> the style is changed (value: 2)-> save
3) first save arrives (value != current value, 1 != 2) -> save
4) second save arribes (2 != 1) -> save
then 3 and 4 are repeated to the infinite

I fixed it using [syncAbort](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/app.js#L172) which  cancels a request if a new one arrives, but that's not the way to fix it

**Comment by javisantana** [comment]
@CartoDB/frontend please, take a look since it's important

**Comment by xavijam** [comment]
We should review annotation view

**Comment by viddo** [comment]
thanks for heads up, good catch :+1:
