### ISSUE TITLE
when I search I want to see only my tables

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#2830]
- go to new dashboard
- search for world

if you have tables with that name the ones from common data are listed first. How do I see my tables?

cc @carlostallon @piensaenpixel

**Comment by xavijam** [comment]
In that case, we could order results, first yours, then shared and finally shared ones...

**Comment by javisantana** [comment]
I think a way to remove 3rd party tables would be good. Specially for enterprise accounts

**Comment by saleiva** [comment]
Let's not add more complexity right now to this. I'll assign to design and we will revisit this in a week or so..

**Comment by xavijam** [comment]
Duplicated -> https://github.com/CartoDB/cartodb/issues/2830
