### ISSUE TITLE
Twitter access: Enable geo-enrichment (on/off) option for the search and historic APIs

### ISSUE THREAD

**Issue by miguelarias** [CartoDB/cartodb#2837]
Together with adding an initial "count" of the estimated tweets that a particular query will return.

Once the user gets the estimation, he will be able to chose in the interface if he wants to deactivate the geo-enrichment feature, to gather less results (only for geo-referenced tweets). 

This will be avaialable for all users with the twitter feature. Only with the new dashboard.

**Comment by saleiva** [comment]
This plus the other stuff that I talked with @Kartones make me think that we need to sit down on monday and re-think the whole usecase one more time

**Comment by Kartones** [comment]
Relates to https://github.com/CartoDB/cartodb/issues/2840
