### ISSUE TITLE
polygon-fill galleruy

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2839]
http://riccardoscalco.github.io/textures/

**Comment by saleiva** [comment]
Done in 08-map-patterns/patt.sketch

**Comment by saleiva** [comment]
Ready to implement :)

**Comment by saleiva** [comment]
@viddo we should put these there at the same time we rebuild the modal to select this

**Comment by viddo** [comment]
Which modal is this for?

**Comment by saleiva** [comment]
Image selector for polygon fiill

**Comment by viddo** [comment]
Reassigned to @javierarce then, since he started on this modal :)

**Comment by javierarce** [comment]
Some previews:

![screen shot 2015-05-13 at 12 14 42](https://cloud.githubusercontent.com/assets/4933/7608450/f3e634e8-f969-11e4-913b-9f8185831d27.png)
![screen shot 2015-05-13 at 12 15 00](https://cloud.githubusercontent.com/assets/4933/7608451/f4061a60-f969-11e4-8354-c6fc4e6cc01b.png)
![screen shot 2015-05-13 at 12 15 11](https://cloud.githubusercontent.com/assets/4933/7608452/f40800a0-f969-11e4-916e-727f212f8e47.png)
![screen shot 2015-05-13 at 12 15 24](https://cloud.githubusercontent.com/assets/4933/7608453/f408e61e-f969-11e4-9eee-7452c6b7d9f5.png)

**Comment by xavijam** [comment]
super nice

**Comment by saleiva** [comment]
+1 :)

**Comment by javierarce** [comment]
Reviewing [this comment](https://github.com/CartoDB/cartodb/issues/2839#issuecomment-99567378), I have a doubt… should this patterns be available for the old modal too?

**Comment by javierarce** [comment]
Hey, one doubt. When we select the category wizard we are currently showing just markers (so the assets we decided that are `markers`). But in that case I think it makes sense to show both. In general, I don't know if the distinction of patterns and markers make actual sense… what do you think?

**Comment by saleiva** [comment]
yes it does, right? It depends on the type of data
