### ISSUE TITLE
Implement GNIP count query to avoid hitting platform limits

### ISSUE THREAD

**Issue by Kartones** [CartoDB/cartodb#2840]
I've tried GNIP's [/search/:stream/counts](http://support.gnip.com/apis/search_api/api_reference.html#CountRequests) endpoint and it works quite good, so is a very valid solution to avoid hitting platform limits. Before doing the real search Twitter Datasource can query for the count, and if would surpass the File Size [1] or Row Count limits, return an error before searching.

This also needs a **config change** to remove all the `.json` postfix on all Twitter account configs, as that's not part of the search url but the return format.

[1]: An average tweet, with all fields etc. properly setup weights 2KB in the CSV that will be imported.

**Comment by miguelarias** [comment]
BUT, we had already discussed that Twitter maps service customers (flagged in superadmin) could have up to 1.5 GB of import file size. Which actually represents around 1 milllion tweets. If the table row limit is 500K that is not coherent. Can we bump table size limit to these users to 1million rows too?. 

I agree with the rest of the workflow.

**Comment by Kartones** [comment]
yes, that can be bumped up and should be bumped to 1M. But that's part of a Central task to integrate platform limits at plans so all this is done automatically. Manually can be done now.

What I want is to avoid hitting the platform limit while importing tweets, no matter if is not searching, capping search or whatever other idea we come up with.
