### ISSUE TITLE
No way to create a map from empty dataset from dashboard

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb#2843]
## STR
 1. Go to dashboard
 2. Click on "NEW MAP"
 3. Click on "New Map: Create a new map with CartoDB from scratch"
 4. Select "Connect dataset"
 5. Select "Empty dataset"

## Current result

No "Create Map" option anymore, just "CREATE DATASET", when clicking "CREATE DATASET" it creates a new table and redirects you to the new table.

## Expected result

It should display a "Create Map" as in the rest of the options. Create the table in background, create a map with that new table and redirect to that new visualisation.

**Comment by xavijam** [comment]
@rochoa, it is implemented here -> https://github.com/CartoDB/cartodb/pull/2786. But it is not in production yet. I'll let you know when it happens :dancer:

**Comment by rochoa** [comment]
:es: :heart:
