### ISSUE TITLE
Suggestion: add tooltip with map creator username for liked maps

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#2844]
Right now an alt appears but it takes seconds

![image](https://cloud.githubusercontent.com/assets/1730320/6754417/b3ac5f00-cf1c-11e4-9578-3e3400bf3b87.png)

cc @xavijam @saleiva

**Comment by saleiva** [comment]
A tipsy! :)

**Comment by xavijam** [comment]
YAY! finally :DDD

**Comment by xavijam** [comment]
with pleasure
