### ISSUE TITLE
Don't concatenate new numbers on "Untitled Map"

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#2846]
Right now:

![image](https://cloud.githubusercontent.com/assets/1730320/6755097/17496432-cf21-11e4-9990-60649d0ed875.png)

This is something that happened months ago too with table names, if I'm not confused: `untitled_table_1_2_3``

@kartones @juanignaciosl

**Comment by saleiva** [comment]
yes please, I hate this one
