### ISSUE TITLE
Change Mailchimp import to use campaigns

### ISSUE THREAD

**Issue by Kartones** [CartoDB/cartodb#2849]
[Branch](https://github.com/CartoDB/cartodb/tree/issue-2849)

### 1st round
- [x] Show users who have opened a campaign
- [x] anonimize data returned (emails)
- [x] Replace old code that used lists

### 2nd round
- [x] Remove campaigns who have tracking disabled
- [x] Change flow to:
  - retrieve campaign list
  - retrieve then subscriber activity
  - set `opened` field of campaign data with subscriber activity data
  - anonymize emails and other personal data (except ip)

### 3rd round
- [x] Try to apply some CartoCSS to color differently `opened=true` emails

cc @saleiva

**Comment by Kartones** [comment]
@saleiva  If you want to customize the CartoCSS, [edit here](https://github.com/CartoDB/cartodb/compare/issue-2849#diff-366aacc0d592f14ffe19beb52dda4172R29).

**Comment by saleiva** [comment]
Assigning to @xavijam to update the texts

**Comment by xavijam** [comment]
Texts changed, but if we need to change them, let's open a new ticket, but it is really easy

https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/new_common/views/create/listing/import_mailchimp_fallback.jst.ejs
