### ISSUE TITLE
Importing from google drive will not detect floats

### ISSUE THREAD

**Issue by danicarrion** [CartoDB/cartodb#2850]
A value of "3,12" which is recognized by google spreadsheet as a number in Spanish locale, is imported as a string in CartoDB.

**Comment by iriberri** [comment]
I've been reviewing this issue and it seems that although the locale is set to Spain and Google Drive shows the cells as numbers, it's still it exporting it as a text. You can try for example to try to download it as a CSV: no matter which locale you use, "3,12" will be double quoted as a string when exported, but "3.12" will be exported as a float. This is not something that we could fix as it's the way we receive the file, so I'm closing the issue.
