### ISSUE TITLE
Design call to action for a user to upgrade when try to connect more than one dataset at the same time

### ISSUE THREAD

**Issue by lbosque** [CartoDB/cartodb#2856]

**Comment by saleiva** [comment]
![screen shot 2015-04-06 at 12 05 03](https://cloud.githubusercontent.com/assets/132149/7003097/2cedf3c0-dc55-11e4-9fec-75a4de8cdfa1.png)

@lbosque is this what you would be expecting?

**Comment by lbosque** [comment]
It looks pretty fine.
In that case, what will happen if the user tries to import a new one? Will the import actions be disabled?
