### ISSUE TITLE
Horizontal scroll is not working on public tables

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#2860]
**Steps to reproduce:**

1. Open a table with a lot of columns on the new public dashboard. You can try with [this one](https://alonsogarciapablo.cartodb.com/tables/gnis_nm_airpt09/public).
2. Try to scroll horizontally to view the columns that are hidden on the right.

**Current behavior:**

- Scroll doesn't work.

**Comment by viddo** [comment]
Removed the label because individual table/vis views are not in the scope of new dashboard (they still have the styles/code from current). :)

Btw I think you mean vertical scroll (y-axis), right?

**Comment by viddo** [comment]
horizontal works for me but not the vertical (I assume there are more rows than visible?): ![horizontal scroll](https://cloud.githubusercontent.com/assets/978461/6779105/ce001e12-d158-11e4-885c-df37995701c9.gif)

**Comment by alonsogarciapablo** [comment]
I mean the x-axis:

![broken_scroll](https://cloud.githubusercontent.com/assets/390398/6779265/af20614e-d15a-11e4-9aef-af628c10371f.gif)

**Comment by alonsogarciapablo** [comment]
@viddo, but I think vertical scroll is not working either cause that table has several pages of rows...

**Comment by alonsogarciapablo** [comment]
This seems to be working after #2882.
