### ISSUE TITLE
Button Upload->'Select a file' doesn't appear in Firefox and low screen resolution

### ISSUE THREAD

**Issue by Xatpy** [CartoDB/cartodb#2862]
Using Firefox 36.0.1 and OS X Yosemite 10.10. 
Screen resolution:**1280x800** (laptop default)

Steps to reproduce:
1. Go to your datasets dashboard.
2. Click on *Connect dataset*

Problem: 
1. You can't scroll down and select Upload a file **Select a file**

Screenshot:
![screen shot 2015-03-23 at 13 53 01](https://cloud.githubusercontent.com/assets/3958416/6780352/a00ee702-d164-11e4-8218-f58813ddb8a8.png)

Gif:
![firefox_connect_dataset](https://cloud.githubusercontent.com/assets/3958416/6780366/d3bfaac8-d164-11e4-86e6-41c88cd46015.gif)

**Note**: It's working correctly with Chrome and Safari. Also it works OK if you open Firefox with a higher ( >1280x800 ) resolution

**Comment by xavijam** [comment]
Fixed @Xatpy, thanks buddy.
