### ISSUE TITLE
Show an alert when someone shares a dataset with you

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#2866]

**Comment by saleiva** [comment]
lovely

**Comment by saleiva** [comment]
the same when someone stops sharing a dataset with you

**Comment by piensaenpixel** [comment]
and the same when a new common data is available

**Comment by piensaenpixel** [comment]
what do you think also if we add when someone likes your map?

**Comment by xavijam** [comment]
I like it, but those notifications should come from the backend. @ethervoid with the new notifications stuff you are developing, could we do this?

**Comment by ethervoid** [comment]
Right now the notification manager is oriented to mailing. I should take a look how the notification part work and see how easy is to integrate into the notification manager

**Comment by ethervoid** [comment]
After checking how this part works in the front, conclusion is that right now is a ["static" part](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/common/views/dashboard_header/notifications/view.js#L75) that don't receive notifications from backend.

To implement this we should store, for example in Redis, all the notifications a user receive and then the front could retrieve it from there.

**Comment by xavijam** [comment]
Closing, if we have time to do it, we will open a new one ❤️
