### ISSUE TITLE
Don't open the non-georefence data on empty datasets views

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2873]

**Comment by xavijam** [comment]
And the oscar goes to.... @alonsogarciapablo!! :D. Please ask @saleiva for more details.

**Comment by alonsogarciapablo** [comment]
@saleiva, can you please elaborate a bit more on this? thx.

**Comment by saleiva** [comment]
When creating a empty dataset or adding an empty dataset to a map we shouldn'd open the "georeference this data" modal window, since there is no data in that dataset. We hope people to create it from the map.

**Comment by alonsogarciapablo** [comment]
Clear as water.

**Comment by alonsogarciapablo** [comment]
When there's no data, the dialog is displayed and the text explains that there's no data:

![captura de pantalla 2015-03-27 a las 13 45 56](https://cloud.githubusercontent.com/assets/390398/6869255/f7847a8e-d492-11e4-87ba-ebbc31b3255f.png)

I'm going to get rid of it in this case.

**Comment by javisantana** [comment]
And why don't we add a dialog that says: you don't have any data, start adding a [point] [line] [polygon] ?

**Comment by saleiva** [comment]
Can you fill me a ticket for that? I'd remove it for the time being and
design that dialog with the new style. Good idea
