### ISSUE TITLE
private tables inaccessible after apikey update

### ISSUE THREAD

**Issue by freakabcd** [CartoDB/cartodb#2874]
I have a locally hosted CartoDB instance with only a single user. There are both private and public tables.
Today, a new api key was requested from the /your_apps page. Now, all the private tables are inaccessible to this single user! As expected, the visualisations using the private tables are also not available.

How would I fix this problem?

**Comment by javisantana** [comment]
this is a installation problem, please use stackoverflow or the mailing list for these questions
