### ISSUE TITLE
Conflict between CSS of infowindows in public pages

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#2876]
The H2 tag styles from the infowindow are being overwritten in the public profiles.

Screenshot in "public_map":
![image](https://cloud.githubusercontent.com/assets/1730320/6800340/da61dea0-d21d-11e4-9883-20a9a0bc74cb.png)

Screenshot in "embed_map" (looks like in the Editor): 
![image](https://cloud.githubusercontent.com/assets/1730320/6800348/eb428c9c-d21d-11e4-994c-b7dc29e20bff.png)

**Comment by javierarce** [comment]
Ok, I'll update all the title tags: 

![screen shot 2015-04-08 at 15 56 50](https://cloud.githubusercontent.com/assets/4933/7046733/319d24ae-de08-11e4-885e-76a094d01faa.png)
![screen shot 2015-04-08 at 15 56 43](https://cloud.githubusercontent.com/assets/4933/7046734/31ae1372-de08-11e4-856f-ec27442d38b2.png)

/cc @CartoDB/design

**Comment by javierarce** [comment]
@saleiva @piensaenpixel @carlostallon: is it ok for you?

**Comment by javierarce** [comment]
Fixed.
