### ISSUE TITLE
Add onboarding overlay for the first time the create map window is opened

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2883]
The same for the connect data modal

**Comment by xavijam** [comment]
@andrewxhill what do you think?

For dataset creation:
![screen shot 2015-03-30 at 19 16 44](https://cloud.githubusercontent.com/assets/132146/6902007/5a1d80d4-d711-11e4-865d-efd4d662913a.png)

For map creation:
![screen shot 2015-03-30 at 19 17 38](https://cloud.githubusercontent.com/assets/132146/6902018/735900f0-d711-11e4-9ee5-40af31722a1d.png)

**Comment by saleiva** [comment]
Hey @andrewxhill just a bit of context. This will apear only the first time that the connect dataset / create map modal window is opened. 

S.
