### ISSUE TITLE
public pages: pagination first item goes to org. profile instead of user 

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#2909]
when user is part of an organization, if you go to next pages, i.e.
https://team.cartodb.com/u/matallo/page/2

and then want to come back to first page, the href in the link goes to org. profile instead of user (find attached)

![screen shot 2015-03-25 at 14 56 48](https://cloud.githubusercontent.com/assets/36676/6826069/46ad8b86-d2ff-11e4-8c6b-652b23cfa193.png)

**Comment by saleiva** [comment]
I think this is duplicated :)

**Comment by matallo** [comment]
oop, sorry then
