### ISSUE TITLE
Missing link

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2913]
![screen shot 2015-03-25 at 16 40 59](https://cloud.githubusercontent.com/assets/132149/6828379/c7674c72-d30d-11e4-800a-49ebca9e769c.png)

That should open the connect data modal and have link style

**Comment by xavijam** [comment]
no please :(

**Comment by saleiva** [comment]
why?

**Comment by alonsogarciapablo** [comment]
Since "Connect your data" is now a link, "with a click" sounds kind of
redundant to me. We could simplify that sentence:

*Connect your data* or start with one of the following datasets from the
> data library.

**Comment by xavijam** [comment]
Uhm... @saleiva ?

**Comment by saleiva** [comment]
super +1

**Comment by xavijam** [comment]
Changed in other pull ;)
