### ISSUE TITLE
If not having locked tables, this links should be disabled

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2914]
![screen shot 2015-03-25 at 16 45 24](https://cloud.githubusercontent.com/assets/132149/6828485/64f365ac-d30e-11e4-95eb-ed5dc78cf19d.png)

**Comment by xavijam** [comment]
Really difficult to know in that view, because we need to make a new request to know that "count" as we do in the content footer...

cc @viddo

**Comment by viddo** [comment]
Hmm, yes, I guess the one way would be to extract that logic elsewhere and reuse for both these cases, since they both rely on knowing that result. How that should be done is something to figure out

**Comment by xavijam** [comment]
This is not necessary right now and being here for too long, closing!
