### ISSUE TITLE
Avoid leaving stale cdb_importer tables

### ISSUE THREAD

**Issue by Kartones** [CartoDB/cartodb#2917]
Approaches:
- Cron/Job to sweep all DBs and DROP tables older than X hours (gather metrics of longest imports)
- Better capture errors, removing involved tables in the process (see [importer Runner class](https://github.com/CartoDB/cartodb/blob/master/services/importer/lib/importer/runner.rb#L190)). 
  - Must take into account scenario of single compressed file [spawning multiple files to import](https://github.com/CartoDB/cartodb/blob/master/services/importer/lib/importer/runner.rb#L306), out of quota erros and the like.
  - Must take into account non-S3 uploads to '/public/uploads' 

Second approach is better and the most appropiate. 1st approach can be done as a mere old data cleaning after implementing 2nd.

**Goal**: Leave no traces of files 'and cdb_importer.' tables in case of failed/errored imports.

**Comment by rafatower** [comment]
@zenitraM what was the approach taken when you did a "manual" clean-up on the user DB's?

Exception handling in the importer deserves a review.

**Comment by zenitraM** [comment]
It was quite crude, I went and dropped all `cdb_importer` tables for all users which didn't have an active connection on `pg_stat_activity` (so no importer activity, well, there could actually be in some point between ogr2ogr and ruby but it would be very uncommon)

**Comment by iriberri** [comment]
Just a reminder to myself: we noticed at https://github.com/CartoDB/cartodb/issues/6276 that we are leaving files in there.

**Comment by rafatower** [comment]
The log id of one of the stale tables: `328b6ff1-0491-42a3-9011-f11309f96902` (thanks to @zenitraM)

**Comment by rafatower** [comment]
More debugging info: it is a sync table: `synchronization_id: abb7afc2-b3ee-11e5-b0e0-0e787de82d45`

Some interesting exception:
```
true: Renaming column wkb_geometry TO the_geom
true: Enabling autovacuum for "cdb_importer"."importer_057fb3beb61b11e5a2780ef7f98ade21_1"
true: Georeferenced
true: Errored importing data from /tmp/imports/20160108-22765-19ltbrq/building_1015.shp:
false: CartoDB::Importer2::TooManyTableRowsError: importer_057fb3beb61b11e5a2780ef7f98ade21_1
```

and the beautified backtrace:
```
services/importer/lib/importer/runner.rb:184:in `block in import'
lib/cartodb/stats/aggregator.rb:45:in `block in timing'
lib/cartodb/stats/aggregator.rb:43:in `timing'
services/importer/lib/importer/runner.rb:182:in `import'
services/importer/lib/importer/runner.rb:332:in `execute_import'
services/importer/lib/importer/runner.rb:261:in `block (3 levels) in single_resource_import'
services/importer/lib/importer/runner.rb:255:in `each'
services/importer/lib/importer/runner.rb:255:in `each_with_index'
services/importer/lib/importer/runner.rb:255:in `block (2 levels) in single_resource_import'
lib/cartodb/stats/aggregator.rb:45:in `block in timing'
lib/cartodb/stats/aggregator.rb:43:in `timing'
services/importer/lib/importer/runner.rb:250:in `block in single_resource_import'
lib/cartodb/stats/aggregator.rb:45:in `block in timing'
lib/cartodb/stats/aggregator.rb:43:in `timing'
services/importer/lib/importer/runner.rb:228:in `single_resource_import'
services/importer/lib/importer/runner.rb:97:in `run_import'
services/importer/lib/importer/runner.rb:90:in `block in run'
lib/cartodb/stats/aggregator.rb:45:in `block in timing'
lib/cartodb/stats/aggregator.rb:43:in `timing'
services/importer/lib/importer/runner.rb:89:in `run'
app/models/synchronization/adapter.rb:19:in `run'
app/models/synchronization/member.rb:220:in `run'
lib/resque/synchronization_jobs.rb:13:in `block in perform'
lib/resque/base_job.rb:21:in `call'
lib/resque/base_job.rb:21:in `run_action'
lib/resque/synchronization_jobs.rb:10:in `perform'
```

**Comment by iriberri** [comment]
https://github.com/CartoDB/cartodb-platform/issues/1364

**Comment by rafatower** [comment]
Fixed here https://github.com/CartoDB/cartodb/pull/6395
