### ISSUE TITLE
Export image fails with password protected visualizations

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#2920]
````
_cdbc_2745832283_1({"errors":["Unauthorized 'tpl_8752e6cc_d1ce_11e4_80b9_0e0c41326911' template instantiation"]});
````

Clicking on "Export image" from a password protected visualization raises an error like the previous one as the frontend is not adding oauth_tokens.

The editor keeps spinning or raises an error:

![image](https://cloud.githubusercontent.com/assets/1730320/6830782/69d20566-d31c-11e4-9d22-a62c942a6d15.png)

![image](https://cloud.githubusercontent.com/assets/1730320/6830796/796fa870-d31c-11e4-91e1-dc91e43f091a.png)

SB/4889278

**Comment by javierarce** [comment]
Fixed.
