### ISSUE TITLE
After deleting some maps, the dashboard stop giving me thumbnails

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2921]
and it displays this error
![screen shot 2015-03-25 at 18 48 31](https://cloud.githubusercontent.com/assets/132149/6831275/9d47ce6e-d31f-11e4-8176-ffe79d281c85.png)

**Comment by saleiva** [comment]
This was the request https://team.cartodb.com/u/saleiva/api/v2/viz/d1eb2a42-214d-11e3-afed-3085a9a9563c/viz.json?callback=vizjson Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by javierarce** [comment]
Is this something that happens consistently all the time?

**Comment by saleiva** [comment]
In my production account I'd say yes

**Comment by javierarce** [comment]
I wasn't able to reproduce this problem deleting one visualization at a time, but when I removed at least two at the same time, it happens the problem you described.

**Comment by javierarce** [comment]
This should work fine now.
