### ISSUE TITLE
Improve create empty map

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#2926]
Hi guys, one thing. @carlostallon @saleiva @xavijam 
![image](https://cloud.githubusercontent.com/assets/1214201/6849888/03b43564-d3d6-11e4-9cee-87648c42dbbe.png)

In create empty map, what do you think about change the link for a button and go directly to a empty map. Removing this view ( i thinks it's no necessary)

![image](https://cloud.githubusercontent.com/assets/1214201/6849924/319abdae-d3d6-11e4-9ee4-08e944fb5ad1.png)

**Comment by andrewxhill** [comment]
And after I create one, I'm seeing this,

![screen shot 2015-03-28 at 9 11 45 am](https://cloud.githubusercontent.com/assets/370259/6881173/93d6d4e4-d52a-11e4-999a-02c5705acdc0.png)

which isn't functional (can't add points etc)

**Comment by saleiva** [comment]
Hey @andrewxhill I cannot replicate your issue :(

@piensaenpixel the thing here is that then a link styled as a tab, would act as a button...

**Comment by saleiva** [comment]
@xavijam fancy doing the behaviour change? Let's give it a try

**Comment by xavijam** [comment]
So, it should be a button?

**Comment by saleiva** [comment]
Leave it as the label, and I'll revisit the styling.

**Comment by xavijam** [comment]
![create-empty](https://cloud.githubusercontent.com/assets/132146/7181323/1c689d28-e44a-11e4-9bda-1fc5af641abb.gif)

Opinions?

**Comment by xavijam** [comment]
With button style:
![create-empty-2](https://cloud.githubusercontent.com/assets/132146/7182057/2fa17a5e-e44f-11e4-9ae6-3bc36c9c2444.gif)

**Comment by viddo** [comment]
For reference, this will affect the [add layer modal](https://github.com/CartoDB/cartodb/issues/3161), let's sync later to avoid merge issues :**

**Comment by xavijam** [comment]
:+1:

**Comment by saleiva** [comment]
+1 to the button

**Comment by saleiva** [comment]
bump!

**Comment by xavijam** [comment]
Until we release new add layer dialog we shouldn't release this.

**Comment by saleiva** [comment]
:/
