### ISSUE TITLE
Delete dataset dialog is closed when clicking anywhere on the window

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#2935]
**Steps to reproduce:**

1. Select multiple datasets on the new dashboard.
2. Click "Delete datassets"
3. You will see the "Delete dataset dialog"
4. Click anywhere (that is not meant to be clicked)

**Current behavior:**

- Dialog is closed.

**Expected behavior:**

- I'd expect the dialog to be closed when clicking "CANCEL", "OK, DELETE", or the X sign on the top left. 

This might be an issue that affects other dialogs as well.

**Comment by alonsogarciapablo** [comment]
![captura de pantalla 2015-03-27 a las 12 40 10](https://cloud.githubusercontent.com/assets/390398/6867090/c138883a-d47e-11e4-9143-c213c15435ef.png)

**Comment by viddo** [comment]
There is an event listener on the body tag that closes dialogs, as a default behavior. The base dialog should stop propagation of events clicked inside the dialog, AFAIK this was the behaviour previously, perhaps was removed at some point (it's inherited from cartodb.js).

Either way, one solution would be to add `'click': 'killEvent'` to the events property in the [base dialog](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/new_common/views/base_dialog/view.js). Other ideas?

**Comment by viddo** [comment]
There is an event listener on the body tag that closes dialogs, as a default behavior. The base dialog should stop propagation of events clicked inside the dialog, AFAIK this was the behaviour previously, perhaps was removed at some point (it's inherited from cartodb.js).

Either way, one solution would be to add `'click': 'killEvent'` to the events property in the [base dialog](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/new_common/views/base_dialog/view.js). Other ideas?

**Comment by xavijam** [comment]
Fixed [here](https://github.com/CartoDB/cartodb/pull/2946)
