### ISSUE TITLE
Migrate visualizations.id type from text to uuid

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#2937]
Having different types makes joins much harder (specially if we want to take full advantage of ORM features), we should try to change the type.

cc @lbosque @Kartones @rafatower

**Comment by lbosque** [comment]
+1

ALTER TABLE visualizations ALTER COLUMN id type uuid USING (id::uuid);

It will work either if the all the fields match a uuid or if the field is empty. However it will fail if there is any other kind of string in any row.

There should not be any field in this corrupt case so I believe that just handling the exception in the migration and warn about having manual modified fields should be enough

No idea about if this affects the app in other ways. Notice that all our ids use these default values:
not null default uuid_generate_v4()

In the case of vizualitation it's the model who generates de uuid when it writes the info in the DB. Probably we can continue doing it in that way if we don't want to change more things. The way to set a uuid in postgresq is the same to set a string, so probable will continue working the same way. Just wanted to comment this fact

**Comment by Kartones** [comment]
+1

I would go ahead and fix this, as you're going to do a refactor of Visualization model(s), if you need help testing ping me.

**Comment by rafatower** [comment]
+1 to this change
