### ISSUE TITLE
Create a New Map after a video in New Dashboard

### ISSUE THREAD

**Issue by vuxita** [CartoDB/cartodb#2938]
Hey,

In the new dashboard - if you select one of the videos as a start point, when clicking on the 'Go for it' button, wouldn't it be better to redirect the user to the importing data screen (screenshot below)? 

Currently it takes you to the dashboard again and you have to click again on 'Create Map' and in 'New Map' before you can create a map. I think it will be a better user experience as they won't have to do two more clicks.

![screen shot 2015-03-27 at 09 49 29](https://cloud.githubusercontent.com/assets/9880992/6869190/9615e6a4-d468-11e4-98e1-f9aa789153fc.png)

cc @saleiva

**Comment by xavijam** [comment]
This is gonna change eva, we will show you on monday, won't we @javierarce? :D
