### ISSUE TITLE
Guessing on import can get stuck in sql_api connections

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#2942]
We've seen that today in some resque jobs stuck in sql_api connections to geocoding acount. Probably need to modify `services/sql-api/sql_api.rb`, used in `services/importer/lib/importer/content_guesser.rb`

See https://github.com/typhoeus/typhoeus#timeouts

**Comment by juanignaciosl** [comment]
Watching this.

**Comment by Kartones** [comment]
Checked stats, will setup a 45 secs geocoding timeout, although a 25 secs one would already be in the 0.1% of SQL API v2 calls range
