### ISSUE TITLE
Hard to tell I'm about to watch a video with the menu items on the right

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#2945]
![screen shot 2015-03-27 at 5 07 12 pm](https://cloud.githubusercontent.com/assets/370259/6877130/7353aebc-d4a4-11e4-9695-a876c07db4ed.png)

**Comment by xavijam** [comment]
I feel this problem will be solved (more or less) with the onboarding mamufas in this dialog (#2883).

**Comment by saleiva** [comment]
Plus what @xavijam is mentioning, I think this new layout can work better.

![create - template selector hover video copy](https://cloud.githubusercontent.com/assets/132149/6886084/c13d1912-d632-11e4-8143-00975fc6c371.png)

**Comment by saleiva** [comment]
![create - template selector hover video copy](https://cloud.githubusercontent.com/assets/132149/6886130/160dc5bc-d634-11e4-8796-eb5b28e3e6d7.png)

**Comment by xavijam** [comment]
Like it, it's likely I'll need help to tag the difficulty, @iriberri, could you help me?

**Comment by iriberri** [comment]
Sure! :-) Although all of them are pretty basic as you're given the data and everything:

Create your own datasets - EASY
Create animated maps - EASY
Create GPS data maps - EASY
Map your local world - EASY
Join datasets - MEDIUM

I'm seeing that in the saleiva image there are a lot of different ones. Not sure if random examples or something to add in the future :-)

**Comment by xavijam** [comment]
they are random, don’t worry :D


On 30 Mar 2015 at 13:08:08, Carla (notifications@github.com) wrote:

Sure! :-) Although all of them are pretty basic as you're given the data and everything:

Create your own datasets - EASY
Create animated maps - EASY
Create GPS data maps - EASY
Map your local world - EASY
Join datasets - MEDIUM

I'm seeing that in the saleiva image there are a lot of different ones. Not sure if random examples or something to add in the future :-)

**Comment by iriberri** [comment]
They look awesome, so sad they're not real.

**Comment by andrewxhill** [comment]
Really nice! 

The ooooonly issue still is, that this,

![screen shot 2015-03-30 at 9 05 56 am](https://cloud.githubusercontent.com/assets/370259/6896687/0531776a-d6bc-11e4-9cbc-0edba8dee920.png)

is misleading or confusing and i'm not sure text changes alone can fix it. 
In reality, when you click that button you are talking about

"Upload new dataset", "Link to file online", "Create an empty table" 

and maybe others that i'm not recognizing. So maybe it will be hard with just a single button "new map"

**Comment by xavijam** [comment]
It is true that it is difficult to explain what user can do in a few words, but this solution could work, maybe we should try with other message.
In any case I've implemented the new layout.

**Comment by saleiva** [comment]
hey @andrewxhill, the thing is that those 3 things are creating a new map, although in the process you  have different options. I mean, creating a map in the actual dashboard means those 3 things too. I don't see a simple solution that doesn't mean to change the whole thing... :(

Happy to try this and iterate later, once we analyze this design.

**Comment by xavijam** [comment]
Don't forget we have the onboarding-help in the first opening.

**Comment by andrewxhill** [comment]
Whatever you guys decide is best. But for me, even a knowledgable user, it is a bit confusing to 
Click a button to create a new visualization
Then have to Click a button to get a new map
Then have to Click a button to decide if it is a blank map, map of Twitter, upload a dataset...

**Comment by saleiva** [comment]
What would you propose? Just trying to be sure I understand you
