### ISSUE TITLE
Improve feedback in imports in non-accessible datasources 

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#2952]
Specially when people try MapServer URLs, this week is being common the following error:

```
2015-03-27 21:30:29 UTC: DOWNLOAD ERROR: Code:0 Body:
```

Example: `739cf84b-8540-4f73-9a5d-3cc015523775`

The issue here uses to be that URLs are private (or may need some authentication).

cc @Kartones @juanignaciosl

**Comment by saleiva** [comment]
Yep, a proper error code would be awesome here.

**Comment by juanignaciosl** [comment]
@iriberri I'll add a explicit message for 404 and 401 errors. Could you confirm that url returned 401 (log doesn't exist anymore)?

**Comment by iriberri** [comment]
URL in SB/4924794. It's doing redirects to a weird site

**Comment by juanignaciosl** [comment]
That's not a valid Internet URL, I'll improve user message.
