### ISSUE TITLE
User logged in with Google doesn't have "Disconnect G+ account" in settings

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#2956]
Flag `google_sign_in` is set up to **false**.

User doesn't use new dashboard neither belongs to an organisation.

SB/4934473

**Comment by saleiva** [comment]
I think this is gonna be fixed in the new dashboard. If so, this is duplicated.

**Comment by iriberri** [comment]
Not sure... @juanignaciosl?

**Comment by juanignaciosl** [comment]
Yep, it's a WIP from #1720, now user account page is in the box same code should work for orgs and non-orgs. I've added a remainder in that issue just in case we don't realise it.
