### ISSUE TITLE
Too many "empty" messages in the dataset view

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#2957]
I got to this screen after deleting all my datasets. The message in the bottom stays there and the spinner spins forever, which is a bit confusing. I think we shouldn't display that message.

![captura de pantalla 2015-03-30 a las 12 14 09](https://cloud.githubusercontent.com/assets/390398/6894495/af21e4e8-d6d6-11e4-871b-e0bef0f2dd5f.png)

**Comment by saleiva** [comment]
this should show the data library

**Comment by xavijam** [comment]
That appears when the data library is being loaded into user schema.

**Comment by saleiva** [comment]
I propose that we change that title to something like "Your Data Library is being stocked up". and then the  text below it "Please wait while we load the list of Datasets in the Data Library for you".

**Comment by xavijam** [comment]
@alonsogarciapablo all yours :)

**Comment by alonsogarciapablo** [comment]
Working on this. I assume only the first message (You have not connected any dataset yet) should be displayed.

**Comment by saleiva** [comment]
Yeah, on the loader that shows up on the button we can add a text like the one I'm proposing or anything you think could be better. Your chance :P

**Comment by alonsogarciapablo** [comment]
I'll see what I can do with that text :-)

**Comment by alonsogarciapablo** [comment]
I just realized this is perfectly fine in staging and production. It's only locally where I see both messages and the one at the bottom never disappears (probably because my environment is not setup properly):

![captura de pantalla 2015-04-07 a las 17 26 12](https://cloud.githubusercontent.com/assets/390398/7026759/f01a0270-dd4b-11e4-83f7-f244c9268993.png)

I will open a PR with the new text.
