### ISSUE TITLE
Video template enhancements

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#2958]
- [x] When video starts to run in background (being minified), background should be black (and not transparent), avoiding to see what is behind.
- [x] Buttons in minified state are green in hovered state.

cc @piensaenpixel @saleiva

**Comment by javierarce** [comment]
Regarding the second point: the decision comes from design

![screen shot 2015-03-30 at 14 40 08](https://cloud.githubusercontent.com/assets/4933/6897044/0ff87d30-d6f1-11e4-81a2-27f7d362290a.png)

**Comment by saleiva** [comment]
But thats a different button style, not an state

**Comment by javierarce** [comment]
Yes, as I said I thought it was a hover state. I'll remove it.
