### ISSUE TITLE
Single Locked VIZ UI Issue

### ISSUE THREAD

**Issue by mikegiddens** [CartoDB/cartodb#2965]
If you only have visualization and you lock that table the splash image shows up and does not show the view locked tables html stuff.  If I add another viz it shows the non locked viz with the correct click to view locked viz.   So there is no other way to click to locked viz if you do not have at least one showing that is not locked.  Hope this helps get you to the situation.  Never tested on tables to see if it does the same thing but would QA that as well.

**Comment by saleiva** [comment]
This is being fixed in the new dashboard. U wanna try it, @mikegiddens?

**Comment by mikegiddens** [comment]
I can wait for the next UI unless you want me to beta test the new UI.  Just wanted to report this since I saw it today. Account "crestonedigital" would work.

**Comment by saleiva** [comment]
Activated. Any feedback would be more than welcome :) Enjoy!
