### ISSUE TITLE
Export image with zoom level 0-1 returns 400

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#2971]
### STR:
- Open map vis
- Zoom out to level 0-1
- Click export image -> export image
- Get a error message:
```json
{
"error": "Unable to fetch http tile",
"url": "https://1.maps.nlp.nokia.com/maptile/2.1/maptile/newest/normal.day/1/-1/1/256/png8?lg=eng&token=█████████████&app_id=███████████",
"statusCode": 400
}
```

### Expected result:
- An image

**Comment by rochoa** [comment]
Now we are wrapping the `x` coordinate as per https://github.com/CartoDB/Windshaft/pull/316

However we will have this same scenario if an static map requires a `y` coordinate bigger than the range supported by the zoom level.

cc @javisantana what do you think is better keep the error (improving the message about why it's failing) or support somehow a background for tiles out or range (as leaflet does)?

**Comment by javisantana** [comment]
I'd go with leaflet way because I think is what I'd expect as a map developer. You find something against it?

**Comment by rochoa** [comment]
nothing, i think it is OK. it will make a bit complex the logic to provide the getTile functions to abaculus but it makes sense to support this scenario.
