### ISSUE TITLE
CDB_TableMetadataTouch wrong parameter?

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#2973]
This [table code](https://github.com/CartoDB/cartodb/blob/master/app/models/table.rb#L1438) seems to be invoking `CDB_TableMetadataTouch` with an id instead of [a name](https://github.com/CartoDB/cartodb-postgresql/blob/master/scripts-available/CDB_TableMetadata.sql#L123):

```
  def update_cdb_tablemetadata
    owner.in_database(as: :superuser).run(%Q{
      SELECT CDB_TableMetadataTouch('#{@user_table.table_id}')
    })
  end
```

I'm assigning this to you, @rafatower , because I think you have a better view on this, and maybe you can tell what this might imply (performance? invalidation?, and if it's wrong at all), but please let me know if you want me to fix it.

PD: spotted with [this staging error](https://rollbar.com/vizzuality/CartoDB/items/5094/), although, since number is inside quotes, it looks more like a DB extension problem than the problem of being an id instead of a name. cc @zenitraM

**Comment by javisantana** [comment]
dunno if table_id is an oid, but if that is the case the conversion is right:

```
select 'tm_world_borders_s_11'::regclass::oid::regclass
-[ RECORD 1 ]-------------------
regclass | tm_world_borders_s_11
```

**Comment by juanignaciosl** [comment]
Closing after talking to @rochoa about this.

**Comment by rochoa** [comment]
Just in case I added some tests in https://github.com/CartoDB/cartodb-postgresql/commit/7f58e1f690bdb2e83a58662338ed6a685fae1c17
