### ISSUE TITLE
Thumbnails of new maps are always centered in Morocco

### ISSUE THREAD

**Issue by luisbosque** [CartoDB/cartodb#2974]
When I create a map (tested with existing datasets and new datasets) it takes me to the map view where the center is ok where the data is located. However when I go to the map list view they are all centered in Morocco (more or less). 

In order to have the thumbnail modified I have to go to the map view and pan through the map.

Maybe related to https://github.com/CartoDB/cartodb/issues/2462?

/cc @saleiva @xavijam @javisantana

**Comment by javierarce** [comment]
This is happening because when you create a map (let's say by importing a CSV dataset of points in NY), the default center of the vizjson is:

```center": "[30, 0]```

and it only gets refreshed when you pan the map /cc @Kartones

**Comment by Kartones** [comment]
I can, as I changed the bounds calculation recently. You want me just to set it to the center of the bounding box set, right?

**Comment by javierarce** [comment]
Yeah.

**Comment by javierarce** [comment]
@Kartones: can we give priority to this and https://github.com/CartoDB/cartodb/issues/5307 issues? It's needed for the new user page.

**Comment by Kartones** [comment]
Assigning to this milestone but I need to discuss with @javisantana about the milestone

**Comment by javierarce** [comment]
Ok, thanks!

**Comment by javisantana** [comment]
what do you need?

**Comment by xavijam** [comment]
:clap
