### ISSUE TITLE
Allow users to select their banner map

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2986]
Possibility to change/set feature map for the public dashboard.

##### Organizations:
  - Possibility to select any public map from any organization member.
  - If it is not set, we should set the most viewed one (public of course).
  - If the selected one turns into private/link/password, we should set the most viewed one (public of course). 

##### Users:
  - Possibility to select any of your public maps.
  - If it is not set, we should set the most viewed one (public of course).
  - If the selected one turns into private/link/password, we should set the most viewed one (public of course).

Right now, in the public dashboard, feature map is defined with:
https://github.com/CartoDB/cartodb/blob/master/app/controllers/admin/pages_controller.rb#L245

To be done by @kartones and @xavijam.

Branch: [highlighted-map](http://github.com/cartodb/cartodb/tree/highlighted-map)

**Comment by xavijam** [comment]
We have to decide the interaction for this

**Comment by saleiva** [comment]
Easy, for the time being, I'd just add an option on the options dropdown on the map editor

**Comment by xavijam** [comment]
@CartoDB/design so, option within cartodb editor?

**Comment by xavijam** [comment]
A preview map in profile page would be easy to be implemented.

**Comment by javisantana** [comment]
@xavijam what is your plan for api and model changes for this?

**Comment by xavijam** [comment]
@kartones decides, I need him for this. But we talked yesterday to have (another) attribute in user/organization data, storing a map_id.

**Comment by javisantana** [comment]
before start, define first:

- changes in frontend model
- changes in backend model
- changes in the api

how it should behave

**Comment by Kartones** [comment]
my idea is to just add a new `User` model field to store that map. Changes in the back I think it will need are:
- setting it manually (access via the property)
- resetting it manually to nil if affected visualization's privacy changes to anything other than `public`. This requires small code digging to see from where we trigger privacy changes to vis.

**Comment by Kartones** [comment]
Ok, org stuff adds a bit more of complexity but the main point remains the same... Detecting all points from when a Visualization changes privacy OR adding logic to priv change of the vis so it grabs its owner and gets most viewed.

Doesn't looks complex, but we're just starting the Visualization refactor and we already are going to break the rule of "no new functionality" exactly with the classes being refactored :trollface: 
Is not a big deal as only reads are being changed ATM but this should really be the last new feature at least regarding visualizations. @javisantana confirm please

**Comment by Kartones** [comment]
uff, reverting to the most visited one I don't like it, because [checking the code that does it currently at public dashboard](https://github.com/CartoDB/cartodb/blob/master/app/controllers/admin/pages_controller.rb#L245), it's Visualization collection call, and Visualization Members shouldn't be aware of their parent Collections (control should be the inverse, Collections handle and know about Members), but handling privacy changes is done always inside the Member.

Can we not default to the most visited one? just "null the field" and make the frontend (or Rails template logic) render the default one? That way we keep logic minimal inside the new field and leave to the "presentation" acting if the field is empty or not

**Comment by xavijam** [comment]
For me :+1:

**Comment by javisantana** [comment]
if this takes changes in core model we need to wait

**Comment by Kartones** [comment]
requires changes in both `User` and `Visualization Member` models, yes... not big, but at both. Is a small task (few hours and as I said would touch a not-yet-refactored-part), so you decide and tell me...
