### ISSUE TITLE
Add URL to the BAD url issue

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2994]
The remote URL returned an error. Please verify your file is available at that URL.  Might be good to show the BAD url used so that can check it since right now they might not know what was used.

**Comment by Kartones** [comment]
ping! as I don't understand exactly what this means about BAD urls

**Comment by iriberri** [comment]
This was already done in: https://github.com/CartoDB/cartodb/issues/5778


![image](https://cloud.githubusercontent.com/assets/1730320/11423815/0cfa46bc-9448-11e5-84a7-1592132601ce.png)
