### ISSUE TITLE
Create animation for the dashboard

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#3001]
The purpose is to invite the users to drag&drop data in this screen:

![screen_shot_2015-04-01_at_12 19 10_1024](https://cloud.githubusercontent.com/assets/4933/6946542/5dbacfb2-d8a1-11e4-899d-dc91ecac86c6.png)

**Comment by xavijam** [comment]
Oh...

**Comment by javierarce** [comment]
![web](https://cloud.githubusercontent.com/assets/4933/7156586/fcdc441a-e367-11e4-8f3d-a7f91106ba32.gif)

**Comment by javierarce** [comment]
![animation_export](https://cloud.githubusercontent.com/assets/4933/7178182/25742a30-e42d-11e4-9153-0a1117f2208d.png)

**Comment by saleiva** [comment]
Aloha XXX!

Welcome to the CartoDB Editor.
Drag your data file to your dashboard to create your first map.

From here, your Dashboard, you will be able to create new maps (A) as well as finding the ones you've liked(b)
