### ISSUE TITLE
Sync Table properties modal

### ISSUE THREAD

**Issue by andrewbt** [CartoDB/cartodb#3007]
Clicking the radio buttons doesn't change the option, but clicking the text does. See the GIF below:

![sync_table_radio_bug](https://cloud.githubusercontent.com/assets/2013555/6949592/497f67f6-d883-11e4-8cfa-d1718d4dbc83.gif)

**Comment by saleiva** [comment]
Changing this issue in order to redesign this with the new modals style. Then we will fix this :)

**Comment by saleiva** [comment]
Done! 
![map editor - sync options modal](https://cloud.githubusercontent.com/assets/132149/7002836/59bb0d06-dc51-11e4-8e52-0da010b03009.png)

Hey @andrewbt as you reported this, could you give me your feedback on the redesign? :)

**Comment by andrewbt** [comment]
@saleiva not seeing this in production (even with new dashboard), but just based on your screenshot I'd say it looks good. I would add an "every month" option though because that is one of the current production choices.

Also, if the user selects "never" do we explain to them as the current modal does that this converts their table back to a regular table? We call this "Disconnecting" a table from source now, so the docs will need to be changed. But never is a simpler/better word, I agree!

**Comment by saleiva** [comment]
It’s just a mockup. It will get implemented during next sprints! :)

Yeah, for that step there will be a another state :)

**Comment by andrewbt** [comment]
Great, looks good and very in line with the new dashboard style!

On Mon, Apr 6, 2015 at 11:26 AM, saleiva <notifications@github.com> wrote:

> It’s just a mockup. It will get implemented during next sprints! :)
>
> Yeah, for that step there will be a another state :)
>
>
> > On 06 Apr 2015, at 17:17, Andrew Thompson <notifications@github.com>
> wrote:
> >
> > @saleiva <https://github.com/saleiva> not seeing this in production
> (even with new dashboard), but just based on your screenshot I'd say it
> looks good. I would add an "every month" option though because that is one
> of the current production choices.
> >
> > Also, if the user selects "never" do we explain to them as the current
> modal does that this converts their table back to a regular table? We call
> this "Disconnecting" a table from source now, so the docs will need to be
> changed. But never is a simpler/better word, I agree!
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/CartoDB/cartodb/issues/3007#issuecomment-90100114>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/3007#issuecomment-90104027>.
>



-- 
Andrew Thompson, Sales Engineer

*CartoDB* | 143 Roebling St, 2A, New York, NY 11211
athompson@cartodb.com | T +1 508.333.7265 <+15083337265>
Web cartodb.com | Twitter @cartodb <http://twitter.com/cartodb>
Map, analyze and build applications with your data
