### ISSUE TITLE
Connect Data still doesn't click

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#3009]
I've been working with the new dash for some weeks now, but still the phrase "Connect Data" doesn't click when I'm looking to start something new. 

![screen shot 2015-04-02 at 9 15 07 am](https://cloud.githubusercontent.com/assets/370259/6964610/e728ee38-d918-11e4-9abb-241be4885564.png)

can we change it to just, "New Data" or "New Layer"

**Comment by saleiva** [comment]
You were the one proposing to use the concept of Connecting Data instead of Adding it. I actually like "Connect" a lot, but  I'm not a native english person so...

What about "New Dataset?"

**Comment by andrewxhill** [comment]
Hmm, since it includes 'blank table" etc, I don't know if connect works, so yeah, New Dataset works for me
