### ISSUE TITLE
Redesign static map export (add message about pop-up blocker)

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/cartodb#3029]
I've seen some comments on twitter and in the support channels where people don't get the new tab once they click "Export Image". I think they don't realize that their browser's pop-up blocker is preventing it from happening.

Should a message be added to the export menu that says, "Your pop-up blocker may prevent a new window from opening."?

![pop-up-blocker](https://cloud.githubusercontent.com/assets/1041056/7005366/60eb8d6e-dc45-11e4-9f21-8e7a17320a1e.gif)

**Comment by saleiva** [comment]
Sure, but let's keep this for the new modal design. Assigning to me

**Comment by saleiva** [comment]
![map editor - export image modal](https://cloud.githubusercontent.com/assets/132149/7073603/e4081efe-def4-11e4-9c1f-2b61600d4be1.png)
