### ISSUE TITLE
Syntax error when using "location" as alias in a SQL result

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#3031]
Example:

`SELECT the_geom as location FROM line_data_sample`

![image](https://cloud.githubusercontent.com/assets/1730320/7006429/5faf980a-dc81-11e4-9c46-c5fe3f10fbbe.png)

Query [here](https://iriberri.cartodb.com/api/v2/sql?rows_per_page=40&page=0&sort_order=asc&order_by=&filter_column=&filter_value=&sql_source=null&api_key=sd&q=select%20st_astext(%22location%22)%20location%20from%20(SELECT%20the_geom%20as%20location%20FROM%20line_data_sample)%20__wrapped). 

Result: 
````
{
error: [
"syntax error at or near "location""
]
}
`````

**Comment by fdansv** [comment]
We probably just need a better error from the API if this is a reserved word. @rochoa what do you think?

**Comment by rochoa** [comment]
Is it a reserved word? Look:

```
$ psql cartodb_dev_user_359a4d9f-a063-4130-9674-799e90960886_db
psql (9.3.5)
Type "help" for help.

cartodb_dev_user_359a4d9f-a063-4130-9674-799e90960886_db=# select the_geom as location from cartodb_query_10 limit 1;
                      location
----------------------------------------------------
 0101000020E6100000FD1A96F4BEEE0AC0942404410DE04740
(1 row)
```

**Comment by fdansv** [comment]
So why doesn't it like ```location```?

**Comment by javisantana** [comment]
it's a global varibale in javascript, maybe is because of that

**Comment by fdansv** [comment]
The query is malformed. When in the editor we submit:

```sql
SELECT the_geom as location FROM snow
```

... the editor is actually asking for:

```sql
SELECT ST_ASTEXT("LOCATION") LOCATION FROM (SELECT THE_GEOM AS LOCATION FROM SNOW) __WRAPPED
```

The second occurrence of "LOCATION" shouldn't be there, right?

**Comment by fdansv** [comment]
Actually, the request that fails is something on the lines of the following, as it needs to convert the SRID values to latlon:
```sql
SELECT ST_ASTEXT("LOCATION") LOCATION FROM (SELECT THE_GEOM AS LOCATION FROM SNOW) __WRAPPED;
```
Which renders the same error returned by the API:

```
cartodb_dev_user_76d16a05-7159-43bb-a2b9-ff5e45937c65_db=# SELECT ST_ASTEXT("LOCATION") LOCATION FROM (SELECT THE_GEOM AS LOCATION FROM SNOW) __WRAPPED;
ERROR:  syntax error at or near "LOCATION"
LINE 1: SELECT ST_ASTEXT("LOCATION") LOCATION FROM (SELECT THE_GEOM ...
                                     ^
```

Which does work with other names other than "location". @pramsey, any hints? :)

**Comment by pramsey** [comment]
Seems like missing the "AS" after the column definition is pretty important. You can skip it when aliasing tables, but not so sure you can skip it aliasing columns.

**Comment by fdansv** [comment]
Well, that works! The mystery of it not working specifically with ```location```, however, remains...

**Comment by pramsey** [comment]
Yep, it’s also an old reserved word, for the equivalent of tablespaces,

                else if (strcmp(defel->defname, "location") == 0)
                {
                        ereport(WARNING,
                                        (errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
                                         errmsg("LOCATION is not supported anymore"),
                                         errhint("Consider using tablespaces instead.")));

 and it’s still used in the tablespace SQL commands.

    CREATE TABLESPACE %s [ OWNER %s ] LOCATION '%s'

**Comment by javisantana** [comment]
owned by legacy
