### ISSUE TITLE
Create mockups for missing modals for new map editor

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#3034]
From the planning issue:

> The sketch file also indicates that there are some "blocking" modals, e.g. creating column, but there is no mockup for that use-case

- [x] Add column, #3836 
![screen shot 2015-04-06 at 18 28 49](https://cloud.githubusercontent.com/assets/978461/7007516/ec45bebc-dc8a-11e4-89fb-fd3bc4491229.png)

- [x] Merge datasets, #3819
![screen shot 2015-04-06 at 18 29 01](https://cloud.githubusercontent.com/assets/978461/7007517/eddfdfb4-dc8a-11e4-9f9f-c43e8a4a24bb.png)

- [ ] georeference column, #3828
![screen shot 2015-04-07 at 14 10 28](https://cloud.githubusercontent.com/assets/978461/7022801/fb78548a-dd2f-11e4-9a67-40a842846b60.png)

- [x] edit (vis) metadata, #3854
![screen shot 2015-05-28 at 17 59 47](https://cloud.githubusercontent.com/assets/978461/7864587/5d39d6b6-0563-11e5-9fd6-1d5d5b6e77f2.png)

**Comment by saleiva** [comment]
Can you start adding them as part of the description so I work on them ASAP?

**Comment by viddo** [comment]
Now I only see one case (the create/add column dialog). There's also a dialog for "merge with another dataset", but perhaps is going to be deleted in the new design (i.e. out of scope?)? If so then just remove it from the description

**Comment by saleiva** [comment]
Merge datasets needs to be redesigned, yeah.
About the first one, that one too. How would you feel if in case of naming the column there, we create another one that says "Unnamed" as a new column on the table? Too advanced?

**Comment by viddo** [comment]
No, I don't think it's too advanced per se, but in that case we also need to add some visual cue upon creating the column, so the user can rename and change column type of it, right?

**Comment by josecruz** [comment]
Here's my take for 'Merge datasets': 
![georeference by latlong 2 copy 2](https://cloud.githubusercontent.com/assets/596509/7808244/1dbb23a0-0392-11e5-8f3b-1cd04f80af0c.png)

![dashboard - user private - datasets privacy share friends list](https://cloud.githubusercontent.com/assets/596509/7808247/26679f6a-0392-11e5-980b-91d917df899d.png)

![dashboard - user private - datasets privacy share friends list](https://cloud.githubusercontent.com/assets/596509/7808312/918b8482-0392-11e5-99fc-8248c24c2730.png)

![long 2 copy 4](https://cloud.githubusercontent.com/assets/596509/7808252/31790f6a-0392-11e5-93e1-189b41dca291.png)

![long 2 copy 6](https://cloud.githubusercontent.com/assets/596509/7808255/357deb62-0392-11e5-82d4-862ee40713e4.png)

![long 2 copy 7](https://cloud.githubusercontent.com/assets/596509/7808261/3b2027c4-0392-11e5-8f57-6f40d1ecc4a1.png)

Space Join:

![dashboard - user private - datasets privacy share friends list](https://cloud.githubusercontent.com/assets/596509/7808335/c242036c-0392-11e5-9822-8cdcbdddb43a.png)

![dashboard - user private - datasets privacy share friends list11](https://cloud.githubusercontent.com/assets/596509/7808336/c24e7e08-0392-11e5-846d-8926f2b62893.png)

**Comment by josecruz** [comment]
2nd version with steps. 

Spatial join
![1st step](https://cloud.githubusercontent.com/assets/596509/7833012/a069b6f0-0463-11e5-8ece-3a1702a8254b.png)
![2nd step](https://cloud.githubusercontent.com/assets/596509/7833013/a079c48c-0463-11e5-8416-13aea55a47c7.png)

Column Join
![1st step](https://cloud.githubusercontent.com/assets/596509/7833028/c04d418a-0463-11e5-9352-98dc959bdc0d.png)
![2nd step](https://cloud.githubusercontent.com/assets/596509/7833029/c05b1df0-0463-11e5-968f-519c98af613c.png)

**Comment by josecruz** [comment]
So here what does not happen on that step, shows unavailable:

![1st step](https://cloud.githubusercontent.com/assets/596509/7834169/05522b5c-046d-11e5-90cd-c5622d54baf2.png)
![2nd step](https://cloud.githubusercontent.com/assets/596509/7834170/056de202-046d-11e5-8611-4f686e38097a.png)

**Comment by saleiva** [comment]
Already provided feedback in person. @josecruz you can summarize it here if you want

**Comment by josecruz** [comment]
I've just uploaded the changes on spatial join after your feedback.

-Continuity 
-Increased text contrast to better read readability
-Flow and elements revised
-Radio buttons topline-aligned

![2nd step copy](https://cloud.githubusercontent.com/assets/596509/7838404/05f03b10-048d-11e5-8862-356dc68bcd95.png)
