### ISSUE TITLE
Fixes on the video tutorial player

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#3039]
![screen shot 2015-04-06 at 19 00 10](https://cloud.githubusercontent.com/assets/132149/7008030/53bd6244-dc8f-11e4-9633-1caa1f29e7b4.png)

- The gradient is so weird (see screenshot)
- There are some issues with the alignement of the buttons (see screenshot)
- It doesn't work on the table view

**Comment by javierarce** [comment]
What does it means "it doesn't work in the table view"? I have just tested it with Chrome and Safari.

**Comment by saleiva** [comment]
When being in a table view, not on a map.
Table view as table view, not as table view of a map :)

**Comment by javierarce** [comment]
Mmmm… were you inside the editor or in the public pages?

Here's what I've tested: 

1. I've created a new map and started watching a tutorial.
2. Clicked "Start guided tutorial"
3. Clicked on "Your datasets"
4. Clicked on a dataset

Now I'm in "tables/name_of_my_table" and I can see the video.

**Comment by saleiva** [comment]
Uhm... now it works.
BUT, the video gets to the first frame always and I have to manually click on play. Is that expected?

**Comment by javierarce** [comment]
It should maintain the state, so for example if you started watching it before clicking on "Start guiding tutorial" and then visit or reload the page, it should play (after it seeks to the stored position). Similarly, if the video is stopped and reload the page, it should remain stopped.

**Comment by saleiva** [comment]
:/ Now it works...
Weird weird...

**Comment by javierarce** [comment]
I'm closing this ticket. Let's be aware of the problem and see if next time we can catch it.
