### ISSUE TITLE
Twitter import time irregularities

### ISSUE THREAD

**Issue by andrewbt** [CartoDB/cartodb#3042]
SCENARIO:
- the user is in the Eastern daylight savings time zone (EDT), which is GMT-4:00
- The current time is 10:30pm EDT on the 6th day of the month / 2:30am GMT on the 7th day of the month
- The user wants to make a table of Tweets from a recent event that spanned from 6:00pm EDT to 10pm EDT, or 10:00pm GMT to 2:00am GMT (the next day)

Because the Twitter import dialog (in the [old?] dashboard) goes off the system time/clock, which is still on 10:30pm EDT on the 6th day, so this is the latest possible time and date that can be selected in the dialog. **However**, times in the dialog are expressed in GMT, and 2am GMT on the 7th day __has already happened__, and thus we should be able to query Tweets from that time, but the dialog will not let us select the 7th day because it is in the "future". We cannot query a few hours of Tweets that already exist.

This bug is only a problem in hours just before midnight, when a user's system clock is in a time zone behind GMT, when trying to query for events spanning two "GMT days".

Workaround:
Reset user's clock to the next day / after midnight, and reload the dashboard/dialog. Then the user can query the hours that they want.

**Comment by andrewbt** [comment]
Possible resolution: Express times/dates in the Twitter import dialog in user's system timezone, and convert the time/date to GMT queries on the backend.

**Comment by saleiva** [comment]
Related with https://github.com/CartoDB/cartodb/issues/3043

**Comment by andrewbt** [comment]
oh, yeah it's the same as @andrewxhill 's ...but I beat him to the bug tracker by an hour!

**Comment by andrewxhill** [comment]
Not by the Twitter search calendar you didn't! :)
