### ISSUE TITLE
Twitter harvester calendar not to true limits of time!

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#3043]
![screen shot 2015-04-06 at 11 28 46 pm](https://cloud.githubusercontent.com/assets/370259/7016581/3491ca56-dcb5-11e4-8ba6-0c4e6f69eee9.png)

See, it is GMT. I am GMT -4. In my time it is 23:30, which means that in GMT it is tomorrow. But the calendar only let's me select up to April 6th, not April 7th which is tomorrow... 

![screen shot 2015-04-06 at 11 38 04 pm](https://cloud.githubusercontent.com/assets/370259/7016618/06d4edfe-dcb6-11e4-84c3-c8ea0de4e572.png)

**Comment by saleiva** [comment]
I'm pretty sure @Kartones will also have to work on this...

**Comment by Kartones** [comment]
Backend initially receives user GMT and standarizes to UTC, but once this is changed let me know if backend is not replying correctly.

**Comment by xavijam** [comment]
It happens in the old create dialog
