### ISSUE TITLE
Duplicated maps in the Delete warning dialog

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#3047]
**Steps to reproduce**
- Create multiple datasets.
- Use them in several visualizations, and make sure that at least one dataset is used in more than one map.
- In the dashboard, select all of the datasets and click the "Delete" button.
- You should see the following warning dialog:

![captura de pantalla 2015-04-07 a las 11 31 25](https://cloud.githubusercontent.com/assets/390398/7020539/16b92d5c-dd1a-11e4-8cae-56cd0c9a5b7a.png)

**Current behavior**
- Dialog shows the same map multiple times and the number in "X affected maps" is incorrect.

**Expected behavior**
- In the example above, it should only display 2 maps, and the text should say "2 affected maps".

**Comment by saleiva** [comment]
Good catch!

**Comment by saleiva** [comment]
Fancy working on it? :)

**Comment by xavijam** [comment]
Go man go!

**Comment by alonsogarciapablo** [comment]
Sure!
