### ISSUE TITLE
first item in breadcrumb has margin unless it belongs to an org

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#3052]
![screen shot 2015-04-07 at 12 59 13](https://cloud.githubusercontent.com/assets/36676/7021849/385392e8-dd26-11e4-9833-447267e5c025.png)

after discussion with @xavijam

**Comment by saleiva** [comment]
Love this issue :tmwc:

**Comment by saleiva** [comment]
https://github.com/CartoDB/cartodb/commit/48e1e32fa24b3a74796952cccd53f3d28e2062db
