### ISSUE TITLE
Visualization 'password protected' loses its privacy if you add/remove a layer

### ISSUE THREAD

**Issue by Xatpy** [CartoDB/cartodb#3057]
How to reproduce:
1. Create a new visualization.
2. Add a new layer.
3. Change its visualization to **Password protected**
4. Set a password and click on *Save settings*
5. Check the embed map (Share->Embed it; Get a simple URL->Enter password)
6. Go back to the editor. Add (or remove) a new layer
7. Go to the last tag (where the protected visualization is), and reload the page.

What happenend:
- You can't view the visualization (or enter password). **404**
- Visualization has changed its privacy. From protected with password to protected with link.

Expected:
- Visualization continues with **protected password** privacy.

Gif:
![bug_password_viz](https://cloud.githubusercontent.com/assets/3958416/7023309/8763d0ce-dd34-11e4-81bc-2d9195749479.gif)

**Comment by rafatower** [comment]
This is a frontend issue: when adding or removing a layer it is sending a request with the privacy field set to `LINK`:

```
Request URL:https://team.cartodb.com/u/rtorre/api/v1/viz/b771a352-038d-11e5-8c6e-0e4fddd5de28
Request Method:PUT
