### ISSUE TITLE
Review and clean new dashboard code

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#3065]
- [x] Remove feature flag conditionals within controllers (RELEASED)
- [x] Remove unnecessary and old views (erb, jst and js) (May 6th, 2015)
- [x] Central https://github.com/CartoDB/cartodb-central/issues/585

cc @javisantana @saleiva @Kartones

**Comment by Kartones** [comment]
Yeah! after [this ticket](https://github.com/CartoDB/cartodb/issues/3045 ) I'm 200% in for the serverside code cleanup!

**Comment by rafatower** [comment]
We need this for on-premise so at least I'd try to get the conditionals removed from controllers asap.

**Comment by xavijam** [comment]
Closing since it has been released :)
