### ISSUE TITLE
Non-org public map URLs aren't redirecting to the right URL

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#3072]
An URL like this

https://saleiva.cartodb.com/viz/295aadec-1e24-11e4-a850-0edbca4b5057/public_map

shows an error, instead of redirecting to:

https://team.cartodb.com/u/saleiva/viz/295aadec-1e24-11e4-a850-0edbca4b5057/public_map

### How to reproduce this bug

1. Go to the dashboard of a organization account
2. Click on the "Shared with you" option in the map tab.
3. Click on a map.

**Comment by Kartones** [comment]
Hotfixed: https://github.com/CartoDB/cartodb/commit/2d1e5314e03e7446d61fa4948816bdf4fbfa7ef5

This is what happens when you use non-compiled languages... syntax error not properly failing :_)
