### ISSUE TITLE
Invoke refactor endpoint from frontend with a different url

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#3083]
Use a different url from frontend if `active_record_vis_endpoint` feature flag is present instead of using a constraint at `routes.rb`.

**Comment by javisantana** [comment]
what endpoint?

**Comment by juanignaciosl** [comment]
Since this is an endpoint that is going to be removed @rafatower suggests using a name that is _obviously_ temporal, such as a place name. Thus we could use `/api/v_brasilia/viz` (a city designed to be the new capital from scratch). If you think this is bullshit `/api/v1_1/viz` would also be fine :-)
