### ISSUE TITLE
All tabs redirected to successfully imported table

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#3087]
Recreate

1. Import a larger file (>10mb maybe)
2. Open a second tab and navigate to your dashboard a second time
3. In the second tab, open an existing visualization and wait

When the upload finishes, both tabs will redirect to your new upload

**Comment by saleiva** [comment]
Ha, love this!

**Comment by xavijam** [comment]
Yep, if you are importing a dataset, it redirects you to that dataset/map. I feel we shouldn't control user browser tabs to know if there are several cartodb tabs opened...

**Comment by xavijam** [comment]
In fact we can't control other tabs... So I propose that if the tab is not focused, don't redirect to the dataset/map, sounds good?

**Comment by saleiva** [comment]
nope, the typical thing is to import, do anything else, and come back once it is imported, so without redirection it will be harder to notice...

I'd leave as it is then.

**Comment by andrewxhill** [comment]
waiiiiit i think maybe you haven't understood what i mentioned,

![screen shot 2015-04-08 at 12 23 51 pm](https://cloud.githubusercontent.com/assets/370259/7049763/48329b72-ddea-11e4-8a83-c32e00936199.png)

After the upload in Tab 1 finishes,

![screen shot 2015-04-08 at 12 23 51 pm](https://cloud.githubusercontent.com/assets/370259/7049774/616b8f36-ddea-11e4-95d9-dba651f48c20.png)
