### ISSUE TITLE
"Show" button on Twitter import doesn't work

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#3089]
If I import some tweets, I get this,

![screen shot 2015-04-08 at 4 42 58 pm](https://cloud.githubusercontent.com/assets/370259/7055001/5e989b5e-de0e-11e4-93c6-4730f5262469.png)

If I click "show" I get this,

![screen shot 2015-04-08 at 4 43 32 pm](https://cloud.githubusercontent.com/assets/370259/7055009/6b81b9e0-de0e-11e4-9f95-1e50c6845f8b.png)

I only have an option to close the overlay. No way to navigate to my new dataset.

**Comment by saleiva** [comment]
Uhm, also that layout seems uncorrect.

**Comment by saleiva** [comment]
xavijam, that button should say "view table" and go to the table view.
To close, there is already the show button.
