### ISSUE TITLE
Hidden layers make the embed to fail 

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#3090]
While in the editor the map is rendered correctly, in the embed nothing is shown and the map requests give an error (https://hopaholli.cartodb.com/api/v1/map?stat_tag=86f88d40-dd62-11e4-bf6e-0e018d66dc29) -> {"errors":["column \"mssa_id\" does not exist"]}

If you put that layer visible by default the map gets rendered correctly.

**Comment by saleiva** [comment]
cc/ @javisantana

**Comment by saleiva** [comment]
It looks that no matters if the infowindow is activated, hidden layers gives error on embed maps.

**Comment by rochoa** [comment]
The `butte_fqhcs` table does not have any `mssa_id` column so the Maps API is reporting a correct error.

I guess this is related to the changes made to request the info windows through the Maps API attributes service so I'm reassigning this to @javisantana.

**Comment by javisantana** [comment]
fixed here https://github.com/CartoDB/cartodb.js/pull/434

**Comment by rochoa** [comment]
:es:
