### ISSUE TITLE
SVG code in infowindows issue

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#3095]
Original HTML code [here](https://gist.github.com/iriberri/0e70c34a9e7c9ef1ea10).

Result:

![image](https://cloud.githubusercontent.com/assets/1730320/7063983/adf135ce-deab-11e4-985e-02008c92f746.png)

https://ekaitzht.cartodb.com/viz/ac7ed3aa-a34a-11e4-8f25-0e4fddd5de28/embed_map

SB/5028255

**Comment by javisantana** [comment]
that would be a security issue
