### ISSUE TITLE
Organization public dashboard takes ages to load

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#3097]
http://team.cartodb.com/maps

**Comment by Kartones** [comment]
For me this is an easy solution: Public org dashboard doesn't needs to have "realtime" tables/vis listing, so why not simply caching them for a few hours? 1st load would still take time, but afterwards would run faster, and if is a frequently accessed dashboard would keep hitting the cache.

The proper solution isn't easy, as this listing will check all schemas from all organization users (around 50 at ours, for example) and then grab all public tables or vis. So backend refactor will probably not solve this issue (just reduce it's wait time).

Other solution would be maybe using varnish so full pages are cached? but invalidation won't be as easy...

Other solutions or ideas? 

/cc @saleiva @javisantana @rafatower

**Comment by saleiva** [comment]
Let's wait until the refactor finishes and then we revisit!
