### ISSUE TITLE
Better error reporting when having technical issues

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#3098]
For example, when running out of space in that server, instead a 9999 we should give a more comprehensive text saying that there are technical issues right now, try again please. (something like that)

**Comment by Kartones** [comment]
This is not as easy as it sounds... The operating system reports simply that it couldn't create "a lock file", nothing else.

This also can happen in multiple steps: When creating lock, when creating file, transforming...

This **really is an internal technical issue** and not a standard error, if you really think is worth spending time on it ok, but I really don't see why improving feedback in case of an internal severe error would add value to the user :/  (we have or should have alerts instead and that's all)

/cc @zenitraM @javisantana
