### ISSUE TITLE
Add missing FKs

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#3100]
Convenient for refactor, but also needed for other platform stuff.

* #3499: Add FK from visualizations to maps
* #3508: Add FK from visualizations to users
* #3176: Add FK from synchronizations to user_tables
* #3802: Add FKs from user_tables
* #3803: Add FKs from users
* #3781: Add FK from assets to users
* #3782: Add FK from automatic_geocodings to tables
* #3783: Add FK from client_applications to users
* #3784: Add FKs from data_imports
* #3785: Add FK from geocodings
* #3786: Add FK from layers to layers
* #3787: Add FKs from layers_maps
* #3788: Add FKs from layers_user_tables
* #3789: Add FKs from layers_users
* #3791: Add FKs from maps
* #3792: Add FKs from oauth_tokens
* #3794: Add FKs from organizations
* #3796: Add FKs from overlays
* #3797: Add FKs from permissions
* #3798: Add FKs from search_tweets
* #3799: Add FKs from shared_entities
* #3800: Add FKs from synchronization_oauth
* #3801: Add FKs from tags

**Comment by zenitraM** [comment]
Ping, is this still on our near plans? was waiting for it for some user-mover thing

**Comment by juanignaciosl** [comment]
This is scheduled at [editor backend refactor sprint 2](https://github.com/CartoDB/cartodb-management/wiki/Editor-backend-refactor#sprint-2), so expect news in a week or so.

**Comment by juanignaciosl** [comment]
See:
* #3499
* #3176
* #3508

**Comment by lbosque** [comment]
Putting it in the nex milestone because of the comment: https://github.com/CartoDB/cartodb/issues/3100#issuecomment-98676180

Feel free to move milestone if necessary

**Comment by juanignaciosl** [comment]
FYI our current roadmap is finishing endpoint refactor during the first week of Alcobendas and do bugfixing and add FKs on the second. I'll remove the assignment because any of the backend team can take it.

**Comment by lbosque** [comment]
Great. Thanks for the info :)

**Comment by juanignaciosl** [comment]
We're rescheduling this. Backend team will plan at least one FK per milestone, since data cleaning is not trivial. We can use this meta-issue for the plan.

I had grouped FKs based on tables but that's too big for some cases. For example, `visualizations` FKs should probably be added one by one.

I think @rafatower had an opinion on what FK begin with. We'll schedule the one we agree for next milestone, assigned to @rafatower , @Kartones or me.
