### ISSUE TITLE
Pre-configure style and infowindow on twitter search

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#3101]
we should show by default a category type with the category terms column and actiate in the infowindow on click :
- Actor displayname.
- Object posted time.
- Object summary.
- Retweet Count.

**Comment by Kartones** [comment]
@saleiva Does this make sense anymore since Pecan?

**Comment by saleiva** [comment]
I'd say yes, since the limits on pecan are so low that most of the times doesn't appear. @javisantana can we get the limits higher?

**Comment by Kartones** [comment]
Also closing for now as is old ticket that doesn't looks will be attacked somewhere near in time
