### ISSUE TITLE
Move outside metadata DB DataImport/Synchronization Log model & data

### ISSUE THREAD

**Issue by Kartones** [CartoDB/cartodb#3104]
## Definition - Ruby model improvements
- [x] Limit log line size to 256 chars (could be extended in the future if worth it)
- [x] Limit to 1000 entries per log max
- [x] 1st 500 entries fixed, wrote once and not overriden
- [x] 2nd half (remaining 500 entries) to be implemented as a circular buffer, to always contain last 500 lines
- [x] tests
- [x] Migration for current logs? <- **not needed, code compatible with current DB table and data**
- [x] provide a friendly `to_s` override to return all lines
- [x] Migrate carto/log class too <- **Out of scope (wasn't present when started the ticket), just made changes to make it compatible**

## [Deprecated] Definition - SQL version

- Normalize Log table to have a `log_entries` FK'ed with a single row per log "line"
- Limit log line size to 256 chars (could be extended in the future if worth it)
- Limit to 1000 entries per log max
- 1st 500 entries fixed, wrote once and not overriden
-  2nd half (remaining 500 entries) to be implemented as a circular buffer, to always contain last 500 lines
- provide a friendly `to_s` override to return all lines
- Migration for current logs? <- probably just better to leave old field and after a few days just purge old logs and remove the field.

## Log_entries table
```sql
id bigserial (pk)
log_id uuid (fk logs.id)
content varchar(256)
created_at timestamp without time zone DEFAULT now()
```

## Circular buffer simulation with SQL

check if already on the circular buffer "area":
```
SELECT log_entries.id FROM logs WHERE log_id = xxxx
    ORDER BY created_at ASC LIMIT 1 OFFSET 500
```

If returns result, count to see if under 1k rows
```
SELECT COUNT(1) FROM log_entries
  WHERE log_id = xxxx
```

update if already 1k:
```
UPDATE log_entries SET content = yyyy, created_at = NOW() WHERE id = aaaa
```

else(or if SELECT returned no result), just insert:
```
INSERT INTO log_entries (log_id, content) VALUES (xxxx, yyyy)
```

## Old stuff

It hurts quite noticeably the DB upon big imports (or at least really verbose ones). Quick solution would be to setup another DB just for logs.

Also trying to remove warnings from ogr2ogr would be helpful, reducing the logs size.

/cc @lbosque @javisantana

**Comment by javisantana** [comment]
I think it would improve not writting each change, just do at the end with a simple insert

**Comment by Kartones** [comment]
but if the import breaks half-done.,... we get no log. That's what happened in the past with the Redis-based log (plus the too quick expiration)

**Comment by Kartones** [comment]
- Only log upon ending
- cut if more than X in size to 0.5K first rows and 0.5K last rows

**Comment by Kartones** [comment]
[Sample code](https://github.com/bbcrd/CBuffer/blob/master/lib/cbuffer.rb) provided by @rafatower 
- Also truncate each line (e.g. to 256 chars)

**Comment by Kartones** [comment]
@zenitraM Does this proposal look good to you?

**Comment by zenitraM** [comment]
Looks good to me for now.. how does it hurt the DB?

**Comment by zenitraM** [comment]
but summoning @pramsey and his postgres-fu :)

**Comment by Kartones** [comment]
Summoning also @javisantana: Alternative is we trust the importer won't fail and we keep in memory the log, dumping only at the end.

I'm going to see some last import logs to see in general if could be dangerous or not. 

IMHO: better to store as they events happen and then if needed optimize to do a single dump.

**Comment by javisantana** [comment]
If the process crash in the middle something really really bad happened so it's a risk we can take.

**Comment by Kartones** [comment]
ok, then going for a Ruby approach and just dumping either manually or when going to do a `to_s` (just in case we forget to flush before, and only if has new content)

**Comment by Kartones** [comment]
Note to self: Instead of using pipes and `\n` as separators, just split by `\n` and when rehydrating instead of grabbing first X + next X, grab first X and **last** X so if a log gets truncated it does so in the middle
