### ISSUE TITLE
Visualization's number of map views not appearing on graph hover in Maps dashboard 

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#3110]
...or is this FAQ just outdated? http://docs.cartodb.com/faqs.html#how-can-i-know-how-many-map-views-has-a-specific-visualization

Support Bee user is asking: http://docs.cartodb.com/faqs.html#how-can-i-know-how-many-map-views-has-a-specific-visualization

I'm not seeing it either in Chrome 41.0.2272.118 on Yosemite 10.10.2

**Comment by saleiva** [comment]
hi @ztephm we decided to take it out in the new dashboard redesign but it seems that some users (included you) are missing this, so we will reevaluate and try to add it in next releases.

Sounds that good?
Thanks for reporting!

**Comment by ztephm** [comment]
Thanks @saleiva ! Sounds good, I just updated the FAQ (pull request).

**Comment by iriberri** [comment]
Asked in SB/5116263. Writing to keep the record.
