### ISSUE TITLE
Design CTA + Check for creating private tables on import

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#3111]
and inform users that tables are public by default.

**Comment by saleiva** [comment]
![screen shot 2015-04-10 at 11 36 48](https://cloud.githubusercontent.com/assets/132149/7085322/ed2ab39e-df75-11e4-8779-0891aa816877.png)

Ok, this button would show a tipsy saying "You are going to create a public table</br>Click to change"
Clicking on the button will open the privacy window and allow to select the privacy level.

On free plans this will serve as a CTA.

**Comment by xavijam** [comment]
@CartoDB/backend, is it possible to change privacy of a dataset/map from an import?
cc @javisantana

**Comment by Kartones** [comment]
It will be very very soon, but only for tables: https://github.com/CartoDB/cartodb/pull/5022  @gfiorav is your man regarding this

**Comment by xavijam** [comment]
ok, waiting for #5022 then.

**Comment by gfiorav** [comment]
Hey @xavijam 

You can very simply make this work from the editor, since you only have to set the new param "privacy" in the "DataImport" model!

If you want, I'll help you do it as soon as #5022 is deployed

**Comment by xavijam** [comment]
yep, when #5022 is deployed I'll make the necessary changes, your help will be appreciated :)

**Comment by saleiva** [comment]
@josecruz assigning to you to design the dropdown that will let you select the type of privacy

**Comment by saleiva** [comment]
WAIT. another idea. Clicking on it, will make it private, clicking again will make it public.

**Comment by xavijam** [comment]
Nice one!

For users who can change privacy -> toggle privacy when click over the icon.
For users who can change the privacy -> clicking will redirect to upgrade page.
For users who can't change the privacy (open-source) -> no upgrade page redirect.

**Comment by gfiorav** [comment]
FYI, Backend-wise this only requires a new optional param to be passed to the DataImport model. Also, there is a new valid_privacy?(privacy) method in the user model that makes it easy to check if the user is liable to give privacy option. Should be trivial to do :)

Like I said I'm available for collaboration I this on demand!
