### ISSUE TITLE
Problem connecting to Google Drive

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#3119]
![screen shot 2015-04-10 at 11 29 00](https://cloud.githubusercontent.com/assets/132149/7085241/05e7ec90-df75-11e4-9a96-a47a21e77884.png)

Got this on the popup when trying to connect to my personal email account.

**Comment by juanignaciosl** [comment]
Could you confirm it's not happening again?

**Comment by saleiva** [comment]
Looks very slow to me, but not sure if we can improve this

**Comment by saleiva** [comment]
Sono this particular issue. Closing
