### ISSUE TITLE
Require ssl with a condition preventing test errors

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#3121]
Basically we have a condition in the organization controller, which tries to prevent errors in the superadmin tests.

https://github.com/CartoDB/cartodb/blob/master/app/controllers/superadmin/organizations_controller.rb#L4

**Comment by Kartones** [comment]
Relates to https://github.com/CartoDB/cartodb/issues/5080

**Comment by Kartones** [comment]
Covered at https://github.com/CartoDB/cartodb/issues/5080 so closing
