### ISSUE TITLE
Deep linking datasets

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#3127]
This kind of links used to work: https://juanignaciosl.cartodb.com/tables/import_201504101613665

But now page loads but API endpoint call fails:
```
https://team.cartodb.com/u/juanignaciosl/api/v1/users/154a13e3-3842-4174-bd70-1af459c9840d/layers
Failed to load resource: the server responded with a status of 401 (Unauthorized)
```

... all this, logged in. I'd hope to see the dataset table.

**Comment by Kartones** [comment]
Same happens with:
https://kartones.cartodb.com/viz/xxxx/table (being a MU user)

**Comment by Kartones** [comment]
Uhm, it's not rewriting on purpose: ` defaults: { dont_rewrite: true }`. Will check why

**Comment by Kartones** [comment]
Alternative we discussed, as the don't rewrite flag is set because if not would break old visualizations published: 
Add a flag for the import allowing to change the imported table privacy (needs to store it at DataImport model). People requests this a lot.

**Comment by juanignaciosl** [comment]
I'm taking a look at this again. Both working url (https://team.cartodb.com/u/juanignaciosl/tables/import_201504101613665) and non working url (https://juanignaciosl.cartodb.com/tables/import_201504101613665) trigger the same GET to https://team.cartodb.com/u/juanignaciosl/api/v1_1/users/154a13e3-3842-4174-bd70-1af459c9840d/layers. The only noticeable difference is the session cookie: working's sending it but not working one is not. I _think_ this might be related either with some JS not sending a cookie it should, or subdomains not allowing cookie reading. @xavijam could you shine some light on this, please?

**Comment by juanignaciosl** [comment]
@zenitraM , I'm talkling to @Kartones about this and a related issue (#3817, see my comments) and he's told me you might've done something with session rewriting.

**Comment by zenitraM** [comment]
Is this endpoint cached by Varnish? (check if there's a `X-Varnish` header)

**Comment by juanignaciosl** [comment]
Nope (neither using the working URL nor the nonworking one).

The problem seems to be the cookie. Although it _looks_ like Chrome is storing the cookie without the subdomain (screenshot) [thanks to Rails configuration](https://github.com/CartoDB/cartodb/blob/master/config/initializers/session_store.rb#L3)

![screen shot 2015-07-06 at 17 11 07](https://cloud.githubusercontent.com/assets/932968/8525581/0911d0b2-2402-11e5-82c2-f9ac17d76076.png)

... JS request won't send it, most probably because of subdomain, so authentication is not performed because current session is not retrieved.

**Comment by Kartones** [comment]
Are you sure? because this is what I get at live acording to Chrome:

![image](https://cloud.githubusercontent.com/assets/2085449/8540479/8b16a2d4-2486-11e5-8950-ad531c952b14.png)

**Comment by juanignaciosl** [comment]
Take a look at the "Domain" column. I think Chrome displays that under "team.cartodb.com" because it was the page you had opened, but domain has not subdomain. I was puzzled when you told it to me yesterday, but it made no sense, since opening it with right click --> view page info --> cookies said something different.

**Comment by Kartones** [comment]
mm you're right! as was so small I didn't noticed that column, indeed then the cookie domain is properly set :/

**Comment by zenitraM** [comment]
Could it be related to this?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Requests_with_credentials

It seems CORS-done requests have to include a client-side flag to use cookies

**Comment by juanignaciosl** [comment]
It _might_ be a way to solve this. In fact some minutes ago @viddo helped me finding where should I add that to Backbone after adding `Access-Control-Allow-Credentials` server side. I'm taking a look modifying or doing something similar to [existing `allow_cross_domain_access` method](https://github.com/CartoDB/cartodb/blob/master/app/controllers/application_controller.rb#L64). Why is is enabled for development? Just for allowing development "shortcuts" and quick tests? If so, I'm worried about having a development environment different than production :-\

**Comment by juanignaciosl** [comment]
Setting `options.xhrFields = {withCredentials:true};` in Backbone and disabling CORS in Rails for development ([I don't know why is it enabled right now](https://github.com/CartoDB/cartodb/blob/master/app/controllers/application_controller.rb#L64)) makes Rails requests work, since cookies are sent... but makes SQL API requests fail, since "["*" cannot be used for a resource that supports credentials.](http://www.w3.org/TR/cors/)". I'll try to set it in a finer-grained way.
