### ISSUE TITLE
Public map creation on import API

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#3131]
It'd be really useful (and requested, as @Kartones said) being able to create a _public_ map straight away with the import api. Probably a `privacy` parameter with `public` and `private` options at least. Of course user plan should be checked before assigning private privacy.

My use case is the extension, since I need to provide a link from the popup and #3126 makes it impossible for some users.

**Comment by javisantana** [comment]
@gfiorav didn't you fix this?

**Comment by gfiorav** [comment]
@javisantana Yes, solved in PR [#304](https://github.com/CartoDB/docs/pull/304).

Thanks for pointing it out :smile:
