### ISSUE TITLE
Type Guessing on import doesn't work with this geojson file

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#3134]
when importing directly by dropping the file in the maps view
https://team.cartodb.com/u/saleiva/tables/non_geolocated_libya_body_count_281_29

**Comment by rafatower** [comment]
@saleiva I assume you're talking about content guessing (the_geom through automatic geocoding), rather than type guessing (string, int, date...), otherwise would like to peek into original file.

**Comment by javisantana** [comment]
more info needed

**Comment by saleiva** [comment]
Close, I dont find the file ;(
