### ISSUE TITLE
Rethink how to show map activity

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#3135]

**Comment by saleiva** [comment]
hey @lbosque which data can we get with the actual API apart from number of mapviews?

**Comment by lbosque** [comment]
Immediately, not cached (in CDN) calls to the tiler in general.
With minimum effort tasks (1 hour): NOT CACHED -> png requests, requests per zoom, etc.. All the requests to the tiler are now tagged by type
With much more effort (4 days): Tagged requests to the CDN

**Comment by saleiva** [comment]
Done! Adding @xavijam 

The one on the bottom left is the over (full opacity to the bars) the others are 50%. I know the blue is missing on hover, I forgot to add.

![screen shot 2015-04-14 at 18 35 57](https://cloud.githubusercontent.com/assets/132149/7141942/21fb7114-e2d5-11e4-9a09-703a3fc459fc.png)

**Comment by saleiva** [comment]
Hey, can you prioritize this? Lot's of support complains...

**Comment by xavijam** [comment]
Yes, after oauth services is the next one, promise.
