### ISSUE TITLE
Annotations not showing content in public view of map

### ISSUE THREAD

**Issue by pramsey** [CartoDB/cartodb#3138]
Create a blank map, add an annotation element, put some text into it. Go to the "share" panel, get the public link, open it. Your text isn't there, the default text is.

![screenshot_170](https://cloud.githubusercontent.com/assets/113883/7112042/f7c1d07e-e1c5-11e4-92f0-30265eaf15d1.png)

![screenshot_171](https://cloud.githubusercontent.com/assets/113883/7112040/f6bdea46-e1c5-11e4-920a-448a2d4dd546.png)

**Comment by pramsey** [comment]
Is this live? I'm still seeing the issue.

**Comment by javierarce** [comment]
Yes, this should be fixed by now. I've just tested with Chrome and it works. The cartodbui version is v3.9.8 (2ad7f8756e74925d8e1225614d6319c35ec571c5)
