### ISSUE TITLE
Text boxes behaving strangely 

### ISSUE THREAD

**Issue by Hayleyr** [CartoDB/cartodb#3150]
Text boxes sometimes disappear or behave erratically when you attempt to select the filler text in them. 
![screen shot 2015-04-13 at 9 36 37 am](https://cloud.githubusercontent.com/assets/938865/7116596/b76a8bd8-e1c0-11e4-8e2c-e38854962bbd.png)

**Comment by xavijam** [comment]
This is already fixed, closing.
