### ISSUE TITLE
Conflict in Torque with column named "d"

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#3160]
Trying to use any torque wizard in a points visualization was giving:

````
_cdbct_3104562887_1(
{
errors: [
"TorqueRenderer: column "i.cartodb_id" must appear in the GROUP BY clause or be used in an aggregate function"
]
}
)
````

[Exampje](https://iriberri.cartodb.com/api/v1/map?config=%7B%22version%22%3A%221.0.1%22%2C%22stat_tag%22%3A%22a0e702e2-e1f7-11e4-901e-0e43f3deba5a%22%2C%22layers%22%3A%5B%7B%22type%22%3A%22torque%22%2C%22options%22%3A%7B%22cartocss_version%22%3A%221.0.0%22%2C%22cartocss%22%3A%22Map%7B-torque-frame-count%3A512%3B-torque-resolution%3A2%3B-torque-aggregation-function%3A%27count(cartodb_id)%27%3B-torque-time-attribute%3A%27cartodb_id%27%3B-torque-data-aggregation%3Alinear%3B%7D%22%2C%22sql%22%3A%22select%20*%20from%20copy_table_wfwefrre%22%7D%7D%5D%7D&callback=_cdbct_3104562887_1&stat_tag=a0e702e2-e1f7-11e4-901e-0e43f3deba5a&map_key=8872bc77d6f1dbbef0277504d2a58d8ad197f078)

This only happened with a specific dataset, so digging a bit:

The dataset contained a column called "d" of type number. Deleting it solved the issue.

How to replicate:
1. Create a new dataset
2. Draw a couple of points
3. Add a column called d of type number
4. Go to wizards, select Torque

Not sure if this is something to fix in the API, in Torque, or in CDB.
cc @fdansv @javisantana @rochoa

**Comment by rochoa** [comment]
https://github.com/CartoDB/Windshaft/blob/master/lib/windshaft/renderers/torque/renderer.js#L128-L132

I will move to a less prone to conflict naming (but it can happen).
