### ISSUE TITLE
Create new add layer modal

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#3161]
![screen shot 2015-04-13 at 18 51 11](https://cloud.githubusercontent.com/assets/978461/7120535/18f1919c-e20e-11e4-8e18-36e89c7c2ca6.png)

Will reuse code from the create map/dataset-dialog, but it will require some refactoring since it's very coupled to those use-cases.

**Comment by alonsogarciapablo** [comment]
@viddo @saleiva I was testing the PR and found something a bit weird/inconsistent. In the context of creating a map, clicking on a dataset means selecting it. Here, clicking on a dataset means that you will "add the layer directly"... Yes, there's a warning message at the bottom, but it's not very visible. People might see the warning after they've made that mistake once... (at least that's what I did) Don't you think?

Wouldn't it make sense to have a "Add layer"  button in the bottom right part of the dialog for consistency? We would have to avoid multiple selection in this case.

**Comment by saleiva** [comment]
@viddo wanted to keep multiple selection for later, but after your review I
think you made a good point. We should let people to add more than one so
this behaves in the same way it does in the dashboard.

**Comment by viddo** [comment]
Sounds reasonable, I'm fine changing to multiple selection here, but keep in mind that means more changes to accommodate this, which probably means more delay on the other dialogs for this sprint. OK?

**Comment by alonsogarciapablo** [comment]
Also, since the PR is already huge, it would be worth doing it as a separate PR.

**Comment by alonsogarciapablo** [comment]
:clap: great job @viddo!
