### ISSUE TITLE
Can't open shared with me datasets

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#3167]
Clicking on a dataset shared with me doesn't work. It uses this URL:

`https://team.cartodb.com/u/juanignaciosl/tables/pueblos_alicante`

This is the trace (simulated in local):
```
Sequel::DatabaseError (PG::Error: ERROR:  invalid input syntax for uuid: "untitled_table"
LINE 1: ...) AS "count" FROM "visualizations" WHERE (("id" = 'untitled_...
                                                             ^
):
  app/models/visualization/collection.rb:88:in `fetch'
  app/models/visualization/locator.rb:54:in `get_by_id'
  app/models/visualization/locator.rb:34:in `visualization_from'
  app/models/visualization/locator.rb:17:in `get'
  app/controllers/admin/visualizations_controller.rb:432:in `resolve_visualization_and_table'
  app/controllers/admin/visualizations_controller.rb:64:in `show'
  app/controllers/application_controller.rb:50:in `wrap_in_profiler'
```

These are the offending lines:

```
 33         visualization = get_by_name(id_or_name, user, filters) if user
 34         visualization = get_by_id(id_or_name, filters) if visualization.nil?
```

I guess `get_by_name` should work, but it does not, so it attempts using the name as id.

cc @kartones @jmedina

**Comment by Kartones** [comment]
I'll check the get_by_name, yes, I'll push soon to live a fix for avoiding the error going inside the get_by_id if id is not in valid uuid format.

**Comment by Kartones** [comment]
uhmm, without checking the code yet, there's one weird thing: Dashboard should list (and for me it lists) shared tables as:
```
https://team.cartodb.com/u/kartones/tables/carlostallon.pueblos_alicante
```
(note the qualified table name at the URL)

Initially tables not yours need this qualification, but I'll check if we were doing some redirects (I think we were) when schema name was not present.

**Comment by Kartones** [comment]
Now works fine, maybe was a FE issue with the new urls but cannot reproduce.
