### ISSUE TITLE
Go to shared datasets instead of Data Library if user hasn't created datasets

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#3179]
Just an scenario I saw right now:

A user has no datasets yet, but it's an organisation user and has 4 shared datasets from other person in the same team.

The dashboard goes automatically to Data Library, instead of to "shared datasets".

It's just a small detail, but wouldn't it be more interesting to guide the user to the shared datasets of his/her organisation? :-)

@saleiva 

![image](https://cloud.githubusercontent.com/assets/1730320/7134883/84de2526-e2a1-11e4-843d-13321f0e4f86.png)

**Comment by saleiva** [comment]
Like it :)

**Comment by xavijam** [comment]
Good idea :)

**Comment by iriberri** [comment]
Editing the name then :)
