### ISSUE TITLE
"Create table from query" not available from maps

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#3192]
Highly useful, as well as when we added "Export layer" in vizs. :-)

Steps (just in case it's not clear):
1. Create a map (viz)
2. In some of the layers, apply a query

You can clear the query and export the results, but not to create a table from that

**Comment by iriberri** [comment]
:heart: :heart: :heart_decoration: :heart: :heart:

**Comment by alonsogarciapablo** [comment]
Deployed! :smile:
