### ISSUE TITLE
Common datasets with sizes >50mb are displayed as importable on free accounts

### ISSUE THREAD

**Issue by zenitraM** [CartoDB/cartodb#3195]
...but they shouldn't. The 285mb is on red but there's a 85mb one in blue

![image](https://cloud.githubusercontent.com/assets/863975/7155883/7aa4873c-e362-11e4-98ea-b9682859ce4f.png)

looks like a @CartoDB/frontend issue

**Comment by zenitraM** [comment]
It seems the backend won't allow to import anything >2x the remaining quota but the frontend displays datasets of up to 3x the remaining quota. So a 110mb dataset will display as importable but won't actually import

Both the front and the back should have the same multiplier...

cc @javisantana @saleiva

**Comment by xavijam** [comment]
We have checked that the MAGIC NUMBER is the same number in front and in back.

**Comment by xavijam** [comment]
My proposal here is we should reduce the magic number to x2 instead of x3 and pass that number from backend to frontend. User decorator should be a good place to send that value.
cc @Kartones @rafatower

**Comment by Kartones** [comment]
:+1:

**Comment by xavijam** [comment]
It checks now the ```max_import_file_size``` attribute from backend.
