### ISSUE TITLE
importing this file didn't open the non-georeferenced data when being on the dataset editor

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#3198]
http://spatialkeydocs.s3.amazonaws.com/FL_insurance_sample.csv.zip

**Comment by alonsogarciapablo** [comment]
Hey @saleiva. I tried to import the file, and everything seems to be working fine to me. I was able to import and georeference the table. I checked and all the columns where there.

What do you mean exactly with `didn't open the non-georeferenced data` ? Thanks!

**Comment by saleiva** [comment]
That that modal didn't show up by default. The one saying that you have to georeference your data.

**Comment by alonsogarciapablo** [comment]
I see what you mean.

**Comment by alonsogarciapablo** [comment]
From what I see in the code, we are currently only displaying this dialog in the map view. I guess this is the right thing to do, unless some datasets are automagically georeferenced during or right after they are imported. Otherwise, we would need to always display that dialog after an import...

**Comment by saleiva** [comment]
But I meant in the map view. Did it show to you?

**Comment by alonsogarciapablo** [comment]
I know what's happening. It's only working the first time. We store a key in the localStorage to know if we should or shouldn't display that dialog. If you had a table with that same name (you probably had imported that same table before) and you saw that dialog, then you won't see it again.

We're using the following key:
```js
localStorage["georefNoContentWarningShowedfl_insurance_sample"] // Returns true
```

We need to add something else to the key, to make sure it uniquely identifies the dataset. Fixing it.

Good catch!

**Comment by saleiva** [comment]
:)
