### ISSUE TITLE
Deprecate /stats endpoint

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#3204]
According to [this search](http://ela01.useb.cartodb.net/#/dashboard/elasticsearch/stats%20no%20longer%20used) /stats endpoint is no longer used, so we should deprecate it. @zenitraM could you please confirm it?

cc @javisantana @rafatower @Kartones

**Comment by Kartones** [comment]
:fire: !!!

**Comment by zenitraM** [comment]
:+1: :fire:
