### ISSUE TITLE
Exporting a shared table names it as username

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#3205]
I was exporting some tables that danicarrion shared with me:

dcarrion.provincias, dcarrion.votos, dcarrion.partidos...

Exporting those tables result in "dcarrion.format" files, instead of taking the table name or at least the combination of both.  "provincias.format" or "dcarrion-provincias.format"

The SQL API allows the parameter `filename` for data exporting, so I guess that the Editor could just fill it with the name of the table.

**Comment by iriberri** [comment]
Related: https://github.com/CartoDB/CartoDB-SQL-API/issues/271

**Comment by xavijam** [comment]
Taking care of it with the new builder, closing! :)
