### ISSUE TITLE
Visualization with named map even though layers are public

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#3215]
https://trainings.cartodb.com/api/v2/viz/a3435d52-e38b-11e4-be06-0e4fddd5de28/viz.json

Account: trainings
Source table: recuento

**Comment by rafatower** [comment]
maybe related to #2407

**Comment by iriberri** [comment]
Only duplicating the visualization removed the named map, we struggled (kartones + santana + me) some minutes changing the privacy of the table

**Comment by rafatower** [comment]
Fixed in https://github.com/CartoDB/cartodb/commit/9c90b874202e3e0d6b99a02378dc17f4e74de281

That corrects invalidation of cache when changing privacy.
