### ISSUE TITLE
Possible sync table timestamp guessing bug

### ISSUE THREAD

**Issue by Kartones** [CartoDB/cartodb#3229]
A remote CSV gets properly imported and guessed the first time, but then after syncing a certain column, which has [a valid timestamp](http://gdal.org/1.11/ogr/drv_csv.html) (just without TZ offset) stays with type string.

Checked that it is not an issue with deactivating [guessing options](http://docs.cartodb.com/cartodb-platform/import-api.html#definition-4).

Ask me for the offending dataset URL. 
Small sample:
```
tweet_text,timestamp,lat,long,trending
"123","2015-04-16 08:00:01",2,2,0
"456","2015-04-16 08:00:01",1,1,0

```

**Comment by Kartones** [comment]
Confirmed that normal imports do guess the field but syncs don't

**Comment by Kartones** [comment]
Ok, found the issue:
Sync imports by default have BOTH guessings to true:
```
-oo AUTODETECT_TYPE=YES -oo QUOTED_FIELDS_AS_STRING=YES
```

While UI imports have ONLY standard import to true:
```
-oo AUTODETECT_TYPE=YES -oo QUOTED_FIELDS_AS_STRING=NO
```

Combined with the user dataset, which has quoted the datetime, that's why works with imports but not syncs.

The UI is not sending at all the required field to specify the quoted fields guessing on imports at least (will confirm tomorrow with syncs):
```

------WebKitFormBoundarykCWfdmOAcoECz27Y
Content-Disposition: form-data; name="content_guessing"

true
------WebKitFormBoundarykCWfdmOAcoECz27Y
Content-Disposition: form-data; name="type_guessing"

```

**Comment by Kartones** [comment]
Found the issue and discussed with @rafatower . We both had out of sync doc and default endpoint values, and [a previous commit](https://github.com/CartoDB/cartodb/pull/3298) inverted ogr2ogr value for the quoting.

Left everything with "proper" endpoint values (the same from the doc, whenever they make more or less sense).

The change will do quoted field guessing also on syncs by default **for new syncs** (so no current syncs will break) as the documentation specifies (default true).

This means that phone numbers of new syncs might get screwed by trying to get parsed into numbers. The only really good solution for this is allowing in the GUI/CartoDB Editor some advanced mode or similar to check/uncheck each of the three guessing options (/cc @saleiva @xavijam):
- type_guessing
- quoted_fields_guessing
- content_guessing

Everything else is obscuring the import/syncs and causing issues... We have a single checkbox that misleads people to think will enable or disable everything, while does only with one option.

Also, if the phone numbers or similar issues are worrying, should be the GUI the one that sends a different value, as we have an API endpoint with documentation and that should be "written in stone", never change except when versioning/publishing new endpoints.

**Comment by saleiva** [comment]
The checkbox should deactivate or activate every step

**Comment by Kartones** [comment]
But that's not a proper solution... what happens then if you want to guess countries but not numbers/dates? or when you want guessing of normal fields but not those having double quotes (double quotes here act as "excluding filter")?

we can change currnet checkbox to "enable general guessing" (and send either all guessings to true or to false) and then have an advanced mode which instead allows to set each kind of guessing.

**Comment by saleiva** [comment]
Exactly but that general Mode is for the future.
