### ISSUE TITLE
Setting a interval value lower than 3600 in a sync table removes the sync info from the table view

### ISSUE THREAD

**Issue by luisbosque** [CartoDB/cartodb#3233]
I tried to set a interval value lower than 3600 in a sync table. When the value was 3600 everything worked fine. After changed, for example to 60 , or 300 or any other, some things happen:
* The synchronization id is not sent to the front. It's a empty field
* The info about the sync table doesn't appear in the table view of the sync table
* The info about the sync table still appears in the datasets view

**Comment by Kartones** [comment]
Already fixed
