### ISSUE TITLE
Renaming datasets doesn't update the layers on the maps affected 

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#3239]

**Comment by Kartones** [comment]
Checking this too as might be related with #2881

**Comment by Kartones** [comment]
Can you elaborate further? I cannot reproduce this, both in dev and in production renaming layers present at a visualization which is not the canonical one get renamed as expected.

**Comment by saleiva** [comment]
:/

**Comment by Kartones** [comment]
Renaming also works fine if table is referenced in SQL query. And I'm using private tables that have named maps (and thus more logic regarding privacy).

And deleting one layer doesn't breaks any vis.
