### ISSUE TITLE
Type guessing forced in sync tables created from UI

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#3264]
When creating a sync table from the UI, **even though you choose that the system should not guess the types**, it's guessed.

Request:

![image](https://cloud.githubusercontent.com/assets/1730320/7202289/32217ab4-e511-11e4-8f0e-d45f5d7e8f54.png)

**Comment by viddo** [comment]
With the disclaimer of never seen/worked with the synchronization parts, looking at the request variables it seems like it does what it's supposed to do (both `type_guessing` and `content_guessing` are set to true). 

Can you give some more clues, e.g. steps-to-reproduce (to know where you trigger this, e.g. is it new or old dashboard? editor?

Either way, sounds/[look](https://github.com/CartoDB/cartodb/search?l=javascript&q=content_guessing&utf8=%E2%9C%93) like an issue with the frontend more than the backend, right? If so, then should probably reassign to someone in frontend

**Comment by Kartones** [comment]
Precisely, @iriberri de-selected guessing and a true is still being sent for both fields.

**Comment by iriberri** [comment]
Added some bold text in the issue :D. Exactly, I disabled type guessing from the UI, but the parameter is not being passed to the request. In regular tables it works, but not for sync.

**Comment by xavijam** [comment]
Silly and unpredictable bug, fixed in https://github.com/CartoDB/cartodb/pull/3308.
