### ISSUE TITLE
Shapefiles encoding is not being detected

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#3266]
and weird characters appear instead.

Example:

http://www.gis.scb.se/how/PXmap1/SCB_PXmap2007.zip

![image](https://cloud.githubusercontent.com/assets/1730320/7205860/9ed987b2-e52c-11e4-9039-ecb8a863d3be.png)

**Comment by juanignaciosl** [comment]
@ethervoid Could you check if the improvements you're testing fix this as well, please?
