### ISSUE TITLE
Add Open in CartoDB to the dataset public pages

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#3271]

**Comment by saleiva** [comment]
Let's add a button close to the likes with the same style that says, OPEN IN CARTODB.

**Comment by xavijam** [comment]
grey one right?

**Comment by saleiva** [comment]
yep

**Comment by saleiva** [comment]
but with our style, not the one on the one click website.

**Comment by xavijam** [comment]
:+1:

**Comment by xavijam** [comment]
Developing this feature and checking with @matallo, we found we have a bug with the importer (#3626).
So one-click won't work with SQL API urls until we fix that :(.
