### ISSUE TITLE
Some HTTP connections at import/syncs not having tiemouts set

### ISSUE THREAD

**Issue by Kartones** [CartoDB/cartodb#3273]
It seems some resque workes hang on open HTTP connections to remote addresses. Check that every HTTP connection has a timeout.

**Comment by Kartones** [comment]
After checking, probably due to legacy reasons (and fear of breaking imports), import HTTP connections have absolutely no timeout, so they can hang forever.

My proposal is:
- a) Setup a reasonable connection timeout, counting with shitty servers. I'd say 60 seconds (already **a lot** but to play safe)
- b) Setup a normal timeout also for all http calls inside imports/syncs. Choices:
  - b.1) General, unique, config-based maximum timeout, gentle to allow big imports.
  - b.2) Per-account timeout, I'd say calculated based on the user disk quota *

@juanignaciosl @lbosque @zenitraM @javisantana @rafatower Suggestions, votes, values...?

. * But even with that we'd have to make some assumptions, like an average of *XX* KB transfered per second

**Comment by javisantana** [comment]
I'd start setting a max timeout, this is not only a matter of user limit is a platform limit since we have a fixed number of workers. 

30 minutes for me sounds like a lot (you can download 1gb with a regular connection/server) and does not make any sense to have 1gb files sync (for the moment)

**Comment by Kartones** [comment]
But we do have at least 1GB syncs already... at least from one account

**Comment by Kartones** [comment]
To be handled internally as it is a platform issue
