### ISSUE TITLE
Move GET API requests api/v1/tables

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#3280]
- [x] tables
- [x] records
- [x] columns
- [x] TableLocator to be able to do the `get_by_id_or_name` calls supporting both models
- [x] new feature flag `active_record_table_vis_endpoint` (currently using `active_record_vis_endpoint`) so visualizations can go unrestricted without affecting this one
- [x] shared specs for all three models: <del>table</del>, record, column

See `spec/requests/api/tables_spec.rb`

**Comment by Kartones** [comment]
new working branch to keep working with remaining tasks: `new-tables-endpoint-gets`
