### ISSUE TITLE
Document missing imports error codes

### ISSUE THREAD

**Issue by lbosque** [CartoDB/cartodb#3287]
As noticed in ES there are some import error codes that are not documented in the docs:

2003, 8003, 8004, 2002, 2005

**Comment by lbosque** [comment]
Related to:
https://github.com/CartoDB/cartodb/issues/3325

**Comment by Kartones** [comment]
Added all mentioned and a few more 200x ones: http://docs.cartodb.com/cartodb-editor.html#error-codes-and-solutions
