### ISSUE TITLE
Order by size doesn't work as expected on the data library

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#3295]
Look at the sizes and the order
![screen shot 2015-04-21 at 00 39 14](https://cloud.githubusercontent.com/assets/132149/7242015/f0108cea-e7be-11e4-9c9a-29e8e8f37f74.png)

**Comment by xavijam** [comment]
Checked that request is correct, so seems like it is a problem from backend :S.

Tested:
```http://team.cartodb.com/u/:myusername/api/v1/viz.json?tag_name=&q=&page=1&type=&exclude_shared=false&per_page=20&tags=&shared=no&locked=false&only_liked=false&order=size&types=remote```

**Comment by juanignaciosl** [comment]
Right now everything that's not a table is assumed to have 0 size because it doesn't count for the quota, but I can change it for data libraries.
