### ISSUE TITLE
Infowindows are not shown at refactor-based visualization pages

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#3313]
Known bug at #3278 branch.

If you set the infowindows it won't show.

**Comment by Kartones** [comment]
Fixed at commits https://github.com/CartoDB/cartodb/commit/5d83a29bdb26b72f7cd8d8128dc72a3d7df0526e & https://github.com/CartoDB/cartodb/commit/e36804b6486f9b5d86c51610baa0ae18225eafaf
