### ISSUE TITLE
Why is the Rails assets pipeline not being used?

### ISSUE THREAD

**Issue by fullofcaffeine** [CartoDB/cartodb#3314]
I'm just curious on why you guys decided moving to Grunt, any specific reasons?

**Comment by javisantana** [comment]
because:
- it was slow as hell in the way we wanted to use it
- cartodb frontend is big enough to have its own build/deploy/management
- I don't like rails

**Comment by fullofcaffeine** [comment]
@javisantana Thanks

**Comment by javisantana** [comment]
said that it worked pretty well while we used it
