### ISSUE TITLE
Having  active_record_vis_endpoint feature flag enabled, sync datasets appear as regular datasets

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#3319]
![screen shot 2015-04-22 at 11 37 45](https://cloud.githubusercontent.com/assets/132146/7271489/0360726c-e8e4-11e4-83eb-c48b4aa3a783.png)
![screen shot 2015-04-22 at 11 37 28](https://cloud.githubusercontent.com/assets/132146/7271488/035d920e-e8e4-11e4-9045-75c401d9d9c3.png)

cc @juanignaciosl @Kartones @rafatower

**Comment by juanignaciosl** [comment]
@Kartones I've assigned this to you because it's likely to be related with the table model, feel free to assign it back to me (or unnasigning it) if not.

**Comment by Kartones** [comment]
perfect, will take a look at it
