### ISSUE TITLE
Pricing plans slider is confusing

### ISSUE THREAD

**Issue by chriswhong** [CartoDB/cartodb#3331]
On our pricing page there is a slider where the user can click on the left or right to slide over a tile with plan details.  

A customer informed me that this was not clear and that arrows or some other UI device is necessary to prompt the user to click on the sides.

![unnamed](https://cloud.githubusercontent.com/assets/1833820/7279495/6b8e5416-e8ea-11e4-986d-0b4e3e38b42d.png)

**Comment by saleiva** [comment]
being fixed in the redesign. Thanks for pointing this out!

**Comment by saleiva** [comment]
BTW, this issues normally go to /website

**Comment by chriswhong** [comment]
Got it.  Thanks!
