### ISSUE TITLE
New duplication modal

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#3332]
The scope of this is to implement the duplicate map/dataset (vis/table using "old" nomenclature) using the new modal:

The only real difference (from an end-user perspective) is that is that the map/dataset is duplicated using the same name as current item + a suffix (e.g. " copy") directly, so there's no "confirm" step.

Tasks:
- [x] edit menu duplicate map dataset
- [x] open new dialog for other contexts (map/table view, "duplicate dataset from query")
- [x] test duplicate logic properly
- [ ] [error dialog](https://github.com/CartoDB/cartodb/compare/3332-new-duplicate-modal#commitcomment-10888811) (?)

**Comment by viddo** [comment]
@javisantana @xavijam, even if the changes from end-user perspective are minor, I have some doubts regarding what to do about some parts of the code related to this:

[Duplicating a map it seems like it's handled server-side](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/table/header/duplicate_visualization_dialog.js#L122-L134), so the client-side is trivial and straight-forward.  However, [duplicating a table](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/table/header/duplicate_table_dialog.js#L123-L170) looks more complicated, because it seems to involve doing a lot of stuff client-side to wire things up. 

My initial suggestion to solve this would be to handle it server-side, have some better endpoint (perhaps on the vis one like done for the [map copy](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/models/vis.js#L328-L340)). What's the reason for why this is done like this client-side?

If it's not possible to change this and we need to continue handle it client-side, at least I think this should be better encapsulated better than in a view. For me it would make sense to encapsulate this behind `vis.copy()` as well, since based on vis' type we know whether it's a map or dataset and the model has all the details it needs to make its calls. From the UI perspective the only interesting information would be to know when it succeeds/fails really.

Thoughts?

**Comment by javisantana** [comment]
- we are doing it client side because in the past we did a lot of things client side to speed up, but you are right it should be server side

- I'd say "let's move to backend side" but you know we are doing the refactor so let's keep this client side.  I'm totally agree with your "vis.copy" proposal

**Comment by viddo** [comment]
Ok, I start with the 2nd approach, at least that way it should only be an internal change to move it server-side at some point. Thanks for prompt answer!

**Comment by saleiva** [comment]
Just in case this helps
![screen shot 2015-04-22 at 17 11 19](https://cloud.githubusercontent.com/assets/132149/7285452/9f4d1dd2-e912-11e4-8984-33219f69f6ff.png)

**Comment by viddo** [comment]
@saleiva "_It's just a second (or two)_" or should it be the random quote we typically use?

**Comment by saleiva** [comment]
up to you :)

**Comment by viddo** [comment]
@javisantana @xavijam I initially tried to take the agreed path of encapsulate the dataset duplication inside the vis model, but run into a roadblock, I suppose you have more insights than me:

As it turns out the dataset requires the specific instance of `cdb.admin.CartoDBTableMetadata`, the one that is used in the editor (typically named `table`), because it depends on the state of the `table.sqlView` to [know how the table should be created (copy or from current SQL)](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/table/header/duplicate_table_dialog.js#L127-L133). The thing is that this `table` object is not available in the vis object, it's completely detached. I suppose there is some reason behind this?

So, in the end, if encapsulating it in vis.copy one would still have to know which kind of vis it is give the correct params depending on the use-case. Thus for now I don't see any benefits of encapsulating it, and instead took the similar approach as current dialog (separate code paths). At least encapsulating some of the internal details related to the table metadata and the importer flow, but not sure we can do more. 

There's still some work to do (e.g. change the duplicate dataset from the query view) but have a look at the [https://github.com/CartoDB/cartodb/compare/3332-new-duplicate-modal](current changes) in case you have some early feedback regarding this.
