### ISSUE TITLE
Add option "Import Dataset" in Data Library search

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#3343]
Right now, when you **search** for a Data Library dataset you only have "Create map".

Usually, I just want to import the dataset to use it in other map which already exists, but by following the workflow I need to click on "create map", delete the created visualization, and then go to datasets and work with both datasets from there.

@saleiva

**Comment by saleiva** [comment]
Uhm...  Not true :)
![screen shot 2015-04-23 at 09 22 04](https://cloud.githubusercontent.com/assets/132149/7297959/4ee99ec8-e99a-11e4-999f-8ea8a71ad5e9.png)

**Comment by iriberri** [comment]
Ok, my fault. Is in search:

![image](https://cloud.githubusercontent.com/assets/1730320/7297983/dd389350-e9cc-11e4-9a52-5d3298464122.png)

**Comment by saleiva** [comment]
Interesting bug :)
Assigning to @xavijam (sorry dude)

**Comment by xavijam** [comment]
Not bug, it is a feature ;).
