### ISSUE TITLE
Clicking "Upgrade" from Maps dashboard user account pulldown links to missing page

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#3347]
![screen shot 2015-04-23 at 10 55 32 am](https://cloud.githubusercontent.com/assets/1779444/7300602/13b9ab70-e9ab-11e4-9b15-6cc3f8f9867c.png)

**Comment by xavijam** [comment]
Thanks for the report @ztephm.

**Comment by ztephm** [comment]
super FAST @xavijam thanks!! making support bee users happy.
