### ISSUE TITLE
Torque legend not disappearing when layer is off in Layer Selector

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#3351]
Related to this? https://github.com/CartoDB/cartodb/issues/2767

Support Bee ticket w/the problem: https://cartodb.supportbee.com/tickets/4654508

...also here's my quick test: https://team.cartodb.com/u/stephaniemongon/viz/7b46d61c-e9ee-11e4-a924-0e018d66dc29/public_map

**Comment by alonsogarciapablo** [comment]
Also, I'd expect the time slider to go away...

**Comment by saleiva** [comment]
totally @alonsogarciapablo
