### ISSUE TITLE
Send email when having activity in a map

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#3366]

**Comment by saleiva** [comment]
As we will not have the simple URL image in medusa yet, we will have to use the same layout than the one we use when somebody shares a map with you.
Assigning to @javierarce to prepare the texts. 

This email should be sent whenever you have a map with more than 100 mapviews in the last 30 mins.

**Comment by javierarce** [comment]
First idea:

Subject: Recent activity on one of your maps
Body: Hooray! Your [name of the map] map got some activity. [image of the map / placeholder]

*Alternative*:

Body: Hooray! Your [name of the map] map has received some attention lately.

It would be cool to use different exclamations depending on the number of mapviews, so for example: 

* Nice! >= 100 mapviews
* Cool! >= 500 mapviews
* Awesome! >= 1,000 mapviews
* Hooray! >= 5,000 mapviews

**Comment by saleiva** [comment]
Love it. Assigning to @Kartones then :P

**Comment by javierarce** [comment]
Cool :smile: 

On a second thought, I think we should add a couple of things:

1. The name of the user.
2. A link to unsubscribe.

```Hooray! Your [name of the map] map got some activity. 

[image of the map / placeholder]

Keep up the good work, [name of the user]!

Unsubscribe from these emails 
```

**Comment by saleiva** [comment]
I'd remove the image for the time being

**Comment by javierarce** [comment]
Ok.

**Comment by Kartones** [comment]
This is going to require a new systems cron job that checks each X minutes for deltas of mapviews and if so, queue sending the email.

I love the idea to increase engagement of people and notify of trending maps, but is not a matter of 5 minutes backend coding, beware :P

**Comment by saleiva** [comment]
BEWARED

**Comment by Kartones** [comment]
Logic draft for the backend (assuming hourly stats, more on this below):

- Async job (Rake) to be called from a cron. Checks each 60 minutes for conditions
  - If met, enqueue job that sends the email
  - else does nothing

```Ruby
if vis_visits_over_time_period > threshold && previous_block < threshold  # or previous X blocks
    true
```
Having one block per hour of the day is easy to detect spikes (when the spike starts) and when they finish (when threshold is lower or has been "cold" for X blocks), but for this we need first to implement https://github.com/CartoDB/cartodb-platform/issues/1071

- Would need also the mentioned unsubscribe system, page, etc.

------------

So, for now I'm removing the milestone to leave this task on hold until we have mentioned dependant issue done.

**Comment by Kartones** [comment]
Actually same as #4751 which is already done so closing
