### ISSUE TITLE
Add "Copy Icon URL" to image icon dropdown menu

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#3367]
User requested feature from these Support Bee tix:
https://cartodb.supportbee.com/tickets/5170751
https://cartodb.supportbee.com/tickets/5170842

Related to: https://github.com/CartoDB/cartodb/issues/2668

**Comment by saleiva** [comment]
Nice idea!

**Comment by xavijam** [comment]
Duplicated -> https://github.com/CartoDB/cartodb/issues/5512
