### ISSUE TITLE
Column names get somewhere cached when selecting category wizard

### ISSUE THREAD

**Issue by luisbosque** [CartoDB/cartodb#3369]
It happened to me with a empty lines dataset

Steps:

1. Create empty dataset
2. Go to map view
3. Draw a line
4. Go to wizards
5. Select category
6. Select Simple back
7. Go to data view
8. Delete description column
9. Go to map view
10. Go to wizard
11. Select category. It will work since it's cached, however CartoCSS is marked as invalid because it's using description column
12. Change the color of category. Layergroup post will fail because description column does not exist
13. Try to fix cartocss manually by removing the "category" section. It will work
14. Go back to simple
15. Reload the page
16. Changing wizards now works fine

Please, try to reproduce it. Let me know if you don't succeed

**Comment by xavijam** [comment]
Closing, let's check if new builder has fixed that problem ;).
