### ISSUE TITLE
New CartoDB font face is not being rendering properly under Android devices

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#3371]
![saleiva profile under android device](https://slack-files.com/files-tmb/T024FUQQ8-F04HSQMC2-debf6e3382/screenshot_2015-04-25-22-56-50_1024.png)

**Comment by matallo** [comment]
![unnamed](https://cloud.githubusercontent.com/assets/36676/7343396/7507bee4-ecc1-11e4-92c2-60bcdebfe41a.png)

**Comment by matallo** [comment]
![screenshot_2015-04-27-12-02-51](https://cloud.githubusercontent.com/assets/36676/7345511/9a14c402-ecd5-11e4-8397-2538d8271e38.png)

**Comment by saleiva** [comment]
Why aren't we showing the cartofant instead of the text on this views¿

**Comment by xavijam** [comment]
That change is already included in the upcoming 'new public page'.
https://github.com/CartoDB/cartodb/pull/3278

**Comment by xavijam** [comment]
Tested in different devices, seems like it was a temporal glitch.

![img_201504118_115438_1024](https://cloud.githubusercontent.com/assets/132146/7367136/806ffd8c-ed9d-11e4-9e7c-3feebce82ffb.png)
