### ISSUE TITLE
Import slots remain unaccessible when an import gets stuck

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#3376]
*How to reproduce:*

* Try to import this file 3 times (or the max import slots you have in your account): https://dl.dropboxusercontent.com/u/2879308/asd.zip

In my case, this Shapefile (which doesn't contain a .shp file) "failed" as follows:

````
2015-04-27 08:27:48 UTC: Before importer run 
2015-04-27 08:27:48 UTC: Starting import for asd.zip 
2015-04-27 08:27:48 UTC: Unpacking asd.zip 
2015-04-27 08:27:48 UTC: Proceeding to register 
2015-04-27 08:27:48 UTC: After importer run 
2015-04-27 08:27:48 UTC: After dispatch
`````

Log ID: `2afbe5c5-acee-45df-88c8-fd4caa3e49ac`

Then, when trying to import a new file (a GeoJSON exported from a CartoDB table) I get the error:

![image](https://cloud.githubusercontent.com/assets/1730320/7344456/cb39c3e8-eccb-11e4-807e-a9e184bb0b09.png)

After some minutes (~20 mins), the old broken imports seem to stop and the slots get free'd. After that, I'm able to import again. 

The new imports get basically blocked by the "stuck" imports for 20 minutes.

cc @rafatower

**Comment by juanignaciosl** [comment]
This involves [importer limits](https://github.com/CartoDB/cartodb/blob/master/services/platform-limits/lib/importer/user_concurrent_imports_amount.rb) and [abstract limit](https://github.com/CartoDB/cartodb/blob/master/services/platform-limits/lib/abstract_limit.rb).

[It's related to user statement timeout](https://github.com/CartoDB/cartodb/blob/master/services/platform-limits/lib/importer/user_concurrent_imports_amount.rb#L53). I think Redis expiration timeout is proportional to it, so a user with a huge timeout (such as @iriberri) might have a huge limit count TTL as well. Iriberri `database_timeout` is `2500000`, so `@expire_ttl` is 500. If I get how limit uses Redis that would make your limit not to be cleaned in almost 10 minutes. @Kartones , am I right? I'm not sure about this, and I don't get why checking over limit (`is_over_limit`) [triggers an increase](https://github.com/CartoDB/cartodb/blob/master/services/platform-limits/lib/abstract_limit.rb#L133). This might be related to [rate limits](https://github.com/CartoDB/cartodb-management/wiki/Platform-Limits) you speak about.

**Comment by Kartones** [comment]
Yes, almost that.

`is_over_limit!` [increases upon call](https://github.com/CartoDB/cartodb/blob/master/services/platform-limits/lib/abstract_limit.rb#L45), but `is_over_limit?` doesn't. That's a standard practice when building rate limits (to have a method that peeks and another that directly increases upon each hit), and importer only increases upon import of a file.

This behaviour is expected as the rate limit is agnostic, we must protect from abuse of imports (hitting the limit) but also must set a big timeout to help with long imports, so we decided to use database tiemout with a multiplier. And if the import gets stuck, killed by monit or any other external source that we cannot control, it simply must wait until the TTL expires.

Detecting this scenario of stuck imports might not be easy, but I wouldn't touch how the import sets the limits, I'd instead try to detect stuck imports to gracefully stop them (and this way, [make the rate limit go down](https://github.com/CartoDB/cartodb/blob/master/app/controllers/api/json/imports_controller.rb#L105)).
