### ISSUE TITLE
Pressing enter in the privacy modal just closes the modal

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#3388]
A user would expect that the enter key applies the change, at least for the case of "password-protected" maps where a keyboard input is expected.

In the other cases, a privacy option can be selected but pressing enter doesn't apply them.

![image](https://cloud.githubusercontent.com/assets/1730320/7348890/7fc7d830-ecf5-11e4-8bc6-b727e2412759.png)

Not sure if this is an expected behaviour :smile:  cc @viddo @xavijam @saleiva 

Edit: the behaviour happens in dataset privacy modal and map privacy modal.

**Comment by saleiva** [comment]
Good catch. @viddo add to this milestone or the next one depending when you wanna approach this modal for the new editor and the dashboard :)

**Comment by viddo** [comment]
Thanks for reporting!
I'll add to next sprint. I'll have a look this sprint if I get time over.
