### ISSUE TITLE
Switch order of Lon / Lat

### ISSUE THREAD

**Issue by mnquintana** [CartoDB/cartodb#3390]
CartoDB displays latitude and longitude in `the_geom` as `Lon, Lat`, instead of `Lat, Lon`, which is actually quite disorienting since the standard for mapping libraries is the [`Lat, Lon` order](http://leafletjs.com/reference.html#latlng). Please change the display order of longitude and latitude, as well as the editing order (ie. the latitude input should display before the longitude input).

**Comment by javisantana** [comment]
haha, that's a very good topic but I think we are a lon, lat company mainly because:

- it's matematically correct
- postgis is lon,lat

In any case if you find any places we don't respect that, please file a ticket
