### ISSUE TITLE
No way to style marker icon in legend

### ISSUE THREAD

**Issue by chriswhong** [CartoDB/cartodb#3403]
When using the wizard to show an SVG icon as a marker, there is no legend entry created on the map.  When using the editor to manually make a legend entry, there is no way to style the marker to make the color match the markers on the map.

https://www.evernote.com/shard/s288/sh/03234266-6438-47e5-b371-a3bfdf9fe71a/9bf4866f383cf00a713d941d9e3156fa

**Comment by hamhands** [comment]
+1 to this

**Comment by alonsogarciapablo** [comment]
> When using the wizard to show an SVG icon as a marker, there is no legend entry created on the map.

I tried this and I could see the image in the legend correctly:

![wizard](https://cloud.githubusercontent.com/assets/390398/9464213/69edb0c6-4b22-11e5-9883-a5b8afc21383.gif)

> When using the editor to manually make a legend entry, there is no way to style the marker to make the color match the markers on the map.

Yes, this is not possible currently. We're planning to revisit legends soon and will try to take this into account.
