### ISSUE TITLE
Errors on imports with several tables

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#3414]
Some imports get just one table imported correctly and many others fail. They are logged as one success event in kibana.

Investigate common causes and get them fixed, starting with compressed and shp files.

**Comment by rafatower** [comment]
http://ela01.useb.cartodb.net/#/dashboard/elasticsearch/rtorre%20imports%20debug

**Comment by rafatower** [comment]
When importing a zip with N importable files, I'm getting this error N-1 times:
```
FAILED: Layer cdb_importer.importer_794c7f3aee7e11e4b5a20242ac110001
```

It is relatively easy to reproduce.

**Comment by rafatower** [comment]
Design issue, will have to extend DataImport job structure to fix it. Also from a product standpoint we need to think what's the exact semantics of a sync table referencing a compressed file source containing several importable files

**Comment by ethervoid** [comment]
Right now the reported import failure doesn't happen because of this [PR](https://github.com/CartoDB/cartodb/pull/4498) that fix it.

This could be an improvement for the data import but I think this issue refers to the failed case to import multiples tables.
