### ISSUE TITLE
Export as SHP on andrew. fails for all datasets

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#3418]
At least right now.

1. https://team.cartodb.com/u/andrew/tables/ne_50m_admin_1_states/public
2. Export as Shp
3. "Your query was not able to finish. Either you have too many queries running or the one you are trying to run is too expensive. Try again."

**Comment by javisantana** [comment]
duplicated https://github.com/CartoDB/CartoDB-SQL-API/issues/204
