### ISSUE TITLE
Embed author link points to faulty URL

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#3419]
![screen shot 2015-04-29 at 15 08 23](https://cloud.githubusercontent.com/assets/978461/7391452/98bbb310-ee81-11e4-971c-6f95666e7ee5.png)
_from article here: http://pejl.svt.se/stora-skillnader-i-ambulanssjukvarden/_

Expected result: The maps page of that user
Actual result: Redirected to either login page (if not logged in) or my own public page (if logged in).

I guess it's because the URL points to `username.cartodb.com/` when it probably should be `username.cartodb.com/maps` nowadays (due to the recent URL changes)

**Comment by viddo** [comment]
ping @Kartones @xavijam not sure but could be related to the public maps release?

**Comment by xavijam** [comment]
Not related with public maps release, I feel it is related with urls change, but in any case, on it.
