### ISSUE TITLE
Geocoding available_geometries "not working" with table names that start by "_"

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#3428]
The `available_geometries` function is returning `[ ]` when a table name starts by "_". This is blocking some geocoding methods as "postal code" that use the function to check the availability of the data.

Renaming a table from the dashboard to "_tablename" doesn't seem possible, the request sends the error

````
Request Method:PUT
Status Code:400 Bad Request
{"errors":["Error saving data"]}
````

but importing a table with that name is possible. (Get one [here](https://gist.githubusercontent.com/iriberri/f274ff12bfea3c93a7a2/raw/17522d6359daec359bd6fa9992afa9ba0c38a861/_untitled_table_324.csv))

Steps:

* Import [previous dataset](https://gist.githubusercontent.com/iriberri/f274ff12bfea3c93a7a2/raw/17522d6359daec359bd6fa9992afa9ba0c38a861/_untitled_table_324.csv)
* Georeference > Zipcodes 
* Choose the first selector and the second one (selecting a column in both)
* Check the available_geometries response
![image](https://cloud.githubusercontent.com/assets/1730320/7395416/08f2abc6-ee9a-11e4-9e27-fd5518ba8bd6.png)
![image](https://cloud.githubusercontent.com/assets/1730320/7395445/38e77654-ee9a-11e4-8645-31bb6b8ec0d6.png)

I'm guessing that maybe some other parts of the platform may be affected by this, but only catched this one atm.

**Comment by gfiorav** [comment]
PG gem is not supporting renaming tables to anything starting with '_'

```
rename_table('foo','_bar')
```
 fails with exception ```PG::Error: ERROR:  type "_bar" already exists```

I'm looking into the gem's source code to report the bug since standard postgres *does* allow renaming tables with '_' prefix.

**Comment by iriberri** [comment]
Nice to know :)

**Comment by gfiorav** [comment]
The first part of this ticket concerning table renames with '_' prefix has been solved in PR [#4752](https://github.com/CartoDB/cartodb/pull/4752)

The part about geocoding '_' prefixed tables can now be properly tested.

**Comment by gfiorav** [comment]
Identified Resque error on for geo referencing tables starting with ('_'):

```** [14:11:30 2015-07-29] 6139: (Job{geocodings} | Resque::GeocoderJobs | [{"job_id"=>"xxxx"}]) failed: #<Sequel::DatabaseError: PG::Error: ERROR:  relation "public" does not exist
LINE 1: UPDATE "public" AS "untitled_table" SET "cartodb_georef_stat...```

Working on it

**Comment by gfiorav** [comment]
PR #4752 now allows geocoding tables begging with an ```_```

Other ```sequel_qualified_table_name``` instances and queries have removed and rewritten as to not to depend of the gem's bad behavior. 

When the PR gets merged I'll close this issue.

cc @iriberri
