### ISSUE TITLE
The desktop zoom is not maintained between changes of preview modes (mobile/desktop)

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#3431]
The problem seems to be that switching back an forth between mobile/desktop preview modifies the zoom level.

**Comment by javierarce** [comment]
@saleiva: I can't reproduce this issue now. Can you check again, please?

**Comment by saleiva** [comment]
going to

**Comment by saleiva** [comment]
Magic!

**Comment by javierarce** [comment]
:dancer:
