### ISSUE TITLE
'Edit in cartodb' link visiting a public dataset goes to a wrong url

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#3432]
After rewritting urls thing, we 'deprecated' cdb.config.prefixUrl in frontend. Unfortunately we still use it in table metadata.
https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/models/table.js#L661

And this is used in the "old" public table view,
https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/public/public_header.js#L30
although it is referencing to a vis variable, vis is a table metadata object.

cc @CartoDB/frontend

**Comment by xavijam** [comment]
cc @saleiva

**Comment by saleiva** [comment]
remove the button for the time being then, until we refactor that page.

**Comment by saleiva** [comment]
But, what happened with that button on the public map view?
It was designed I think

**Comment by xavijam** [comment]
Edit in CartoDB button in https://github.com/CartoDB/cartodb/pull/3435/files.
