### ISSUE TITLE
Original import url should be added at least to the import log

### ISSUE THREAD

**Issue by lbosque** [CartoDB/cartodb#3439]
Now, when a file is uploaded or the import url is fetched from the original source, it is either uploaded to a temporal place or kept in local. Problem is that, after that, the file_uri field keeps been updated and the original source url is lost in the process.

Either we create a new field in the data import model to store the original url or we can write in the log the original source when it's being downloaded

**Comment by Kartones** [comment]
Initially assigning rafa, if you see won't fit reassign or unassign

**Comment by rafatower** [comment]
related to https://github.com/CartoDB/cartodb/issues/2695

**Comment by Kartones** [comment]
I have opted for a new `original_url` attribute that gets stored to the DB and only written once, so it captures always the source url:
- If is a local file, it will either hold the local server path (long uploads, first gets stored at a folder) or the AWS S3 bucket (small uploads, directly done by Unicorn to S3 from the server)
- if is a remote url, is always the url, being a sync or normal import
