### ISSUE TITLE
Viz.json with 3 layers only shows 1 layer in the Editor

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#3445]
From SB/5209502

Behaviour when you open the visualization in the Editor:

* The toolbar appears just with the number "1", the map is empty
![image](https://cloud.githubusercontent.com/assets/1730320/7412517/fbbecef8-ef43-11e4-8478-6d0d718a5acf.png)

* Clicking on that "1" renders the map and shows the option for the first layer
* The map with the three layers is shown, although the toolbar only shows one layer

Details of the visualization can be found in the ticket.

In Rollbar: https://rollbar.com/vizzuality/CartoDB/person/?environment=production&person_id=f20f7695-2831-48fb-bb2c-f032a66463ba

Errors: 

````
CartoDB::NamedMapsWrapper::HTTPResponseError: GET:503 http://10.0.1.254:80/api/v1/map/named/tpl_e91020a8_dc70_11e4_aa0b_0e0c41326911?api_key=e9018ef2851128099fb1067f5bbe9bd527993557 <?xml version="1.0" encoding="utf-8"?> <!DOCTYPE html PUBLIC "-//W3C//DT
`````

and

`````
ActionView::Template::Error: could not connect to server: Connection refused Is the server running on host "10.0.128.22" and accepting TCP/IP connections on port 5432?
`````

cc @javisantana

**Comment by javisantana** [comment]
nice report

**Comment by iriberri** [comment]
cc @Hayleyr @ztephm , keep informed here! :)

**Comment by viddo** [comment]
how prio is this? for next week/sprint?

**Comment by rafatower** [comment]
did you do any further investigation? I remember a similar case that seemed to be a javascript problem

**Comment by rafatower** [comment]
IIRC, fixed at the time.
