### ISSUE TITLE
Incorrect georef By Admin Region when more than one region has same name

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#3453]
Similar to this: https://github.com/CartoDB/cartodb/issues/1088

When users goeref By Admin Region with county region names and USA entered in "If your column isn't country data, where's it?", if there is more than one state with same name for county or region how does the user choose which one to use?

Example: User has "county" dataset column containing "Schuyler" and "Delaware". They want geometry for those counties in New York State, and dataset does include a "state" column containing "New York". They georef By Admin Region, but geometry appears for Schuyler city in Colfax county, Nebraska, and for Delaware County in Ohio State.

Can there be an option for them similar to By City Name's 2nd pulldown: "Admin. Region where city's located, if known"?

**Comment by iriberri** [comment]
There's a confusion here I guess... We don't geocode counties at the moment.

By geocoding  "Schuyler" and "Delaware", you get null and the Delaware state, accordingly.

As the admin1 geocoder doesn't contain advanced data (as counties) yet, the option for "admin. region" is not available here. We should first improve the geocoder to add administrative areas of level 2 and then allow that "nested" options.

Also, the ticket https://github.com/CartoDB/cartodb/issues/1088 refers to the "By street addresses" option, right? which was the only one specified on that tutorial before you upgraded it! :smile: 

Let me know if there's something else I'm missing here, please :)

**Comment by ztephm** [comment]
Nope, you're not missing anything...sorry, my confusion! Yes re: ticket #1088, that was just to reference how you could have 3 pulldowns. Thanks!
