### ISSUE TITLE
Georef status = true but polygons not appearing

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#3454]
Test dataset: https://team.cartodb.com/u/stephaniemongon/tables/georef_test_iso3

Georef happened automatically upon upload when dataset contained ISO3 codes. cartodb_georef_status is true for all, but not all appear in vis. or @ least not in correct place. Happening especially for small islands.

![screen shot 2015-05-01 at 11 44 05 am](https://cloud.githubusercontent.com/assets/1779444/7432584/7198da34-eff7-11e4-8b04-bcba9d05817a.png)

**Comment by rafatower** [comment]
do you have the source file, please?

**Comment by ztephm** [comment]
hi @rafatower actually i just saw this is related to this user-reported issue, & he supplied his dataset there: https://github.com/CartoDB/cartodb/issues/3455

...also @iriberri self-assigned that issue. Thanks!

**Comment by iriberri** [comment]
In the table you're attaching the geometry for the Cocos Islands appears, attached to that CCK ISO3 code. :-)

Notice the difference between the Territory of the Cocos (Keeling) Islands, considered an administrative region of level 0 (like countries) and Cocos Island "(Spanish: Isla del Coco) is an island designated as a National Park off the shore of Costa Rica," which seems the territory that you're looking at in the map.

**Comment by ztephm** [comment]
Aha! Thanks @iriberri
