### ISSUE TITLE
Geocoder fails to provide geometry for several national islands for 

### ISSUE THREAD

**Issue by jwishnie** [CartoDB/cartodb#3455]
Following country codes fail to geocode:
BV
GP
BQ
CX
GF
MQ
RE
SJ
TK
YT

From this dataset:
https://jwishnie.cartodb.com/tables/iso_alpha_2

**Comment by iriberri** [comment]
Actually, the list also includes CC. Working on it.

BV
GP
BQ
CX
GF
MQ
RE
SJ
TK
YT
CC

**Comment by iriberri** [comment]
Fixed! :) It should be working now for all of them.
