### ISSUE TITLE
Add option to disable geocoding guessing in the UI

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#3456]
cc @saleiva 

It should be deactivated with the check for guessing types.

SB/5222685

**Comment by xavijam** [comment]
@iriberri, same check for both guessings?

**Comment by iriberri** [comment]
Hmm... I'd add independent ones, but maybe for design is not too nice. One is not a bad idea :) @saleiva decides!

**Comment by saleiva** [comment]
Same check for both! :)

**Comment by saleiva** [comment]
For the non experience users, not guessing is not guessing no matter what

**Comment by xavijam** [comment]
:+1:

**Comment by iriberri** [comment]
:+1:
