### ISSUE TITLE
Weird description effect on public dashboard

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#3457]
![screen shot 2015-05-04 at 10 19 16](https://cloud.githubusercontent.com/assets/132149/7450601/177bab6a-f247-11e4-9b1c-6a7862e29ed5.png)

marias.cartodb.com

**Comment by xavijam** [comment]
He has a <h1> element inside of it (done with markdown). Should we "override" the styles of any element?

cc @viddo @alonsogarciapablo

**Comment by alonsogarciapablo** [comment]
@xavijam, we could do that. Every <h*> inside of .DefaultDescription gets the same font-size...

**Comment by xavijam** [comment]
But only in the "preview" descriptions? Because I don't know if we should do that, for example, in the public map preview.
