### ISSUE TITLE
Twitter imports should return a meaningful error message when gnip is down

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#3458]
See import with id `30fd3832-a12b-43f0-8daa-cf77f395da6e`

gnip was down and returning 503 errors at the time of the import.

Branch: `3458-detect-gnip-server-errors`

**Comment by Kartones** [comment]
Currently it reports a `Error connecting to datasource (1012). There was an error trying to connect to the datasource. This might be caused due to a configuration problem, server being unavaliable, revoked access token or similar cause.` error, but I'll build a specific one for Twitter connector.

**Comment by saleiva** [comment]
I'm afraid we will need a more generic text. No way we can tell the cloud based users that this might be caused to a config problem. What about something like:

"Error connecting to datasource (1012). There was an error trying to connect to the datasource. If this problem stays, please contact support@cartodb.com".

**Comment by Kartones** [comment]
@saleiva done, also set this text for GNIP:

```
Twitter GNIP Server Error (1009)
There was an error connecting to Twitter's GNIP service to retrieve your tweets. The server might be temporally unavaliable, please try again later.
```

**Comment by saleiva** [comment]
can you put just twitter (not GNIP)?
Awesome mate!

**Comment by Kartones** [comment]
done too!
