### ISSUE TITLE
Unify public map designs on the sketch file and fix responsive view of the metadata.

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#3470]
![screen shot 2015-05-04 at 12 46 38](https://cloud.githubusercontent.com/assets/132149/7452302/394fd774-f25c-11e4-97d1-756de4559542.png)

**Comment by piensaenpixel** [comment]
Unify the sketch and take a look the responsive view.

![public map - mobile - logged](https://cloud.githubusercontent.com/assets/1214201/7537689/057c1966-f59b-11e4-8ece-da7a0d786834.png)
![public map - mobile - more show](https://cloud.githubusercontent.com/assets/1214201/7537690/0594b584-f59b-11e4-9ad6-7e507b510d82.png)
![public map - mobile - not logged](https://cloud.githubusercontent.com/assets/1214201/7537691/05999e6e-f59b-11e4-86aa-a871615646b1.png)
![public map - mobile - scroll](https://cloud.githubusercontent.com/assets/1214201/7537692/05a157bc-f59b-11e4-8a71-3be644f760b6.png)

**Comment by saleiva** [comment]
is this done?

**Comment by piensaenpixel** [comment]
Yes
