### ISSUE TITLE
connect_timeout parameter is not respected by sequel/pg

### ISSUE THREAD

**Issue by zenitraM** [CartoDB/cartodb#3477]
Steps to reproduce:
- have a database.yml with 
```
- connect_timeout: 2.5
``` 
- set the database_host of an user to a host with a non-responding IP (ask me if you need one, or one like 10.0.0.1)
- try any view or run any query on that user:
```
irb(main):010:0> User.find(username:'clustertest2').in_database
=> #<Sequel::Postgres::Database: {"adapter"=>"postgres", "encoding"=>"unicode", "host"=>"...", "database"=>"...", "username"=>"...", "password"=>"...", "port"=>6432, "connect_timeout"=>2.5, :logger=>nil, :after_connect=>#<Proc:0x00000006dea868@/home/ubuntu/www/production.cartodb.com/releases/20150504132009/app/models/user.rb:563>}>
irb(main):012:0> User.find(username:'clustertest2').in_database['SELECT 1'].first
```

It just hangs there, even though connect_timeout is set to 2.5.

**Comment by rafatower** [comment]
@Kartones the problem is that `in_database` resets the timeout to postgres `DEFAULT` before returning the db/connection object, instead of taking into account config values.

**Comment by zenitraM** [comment]
note, this is not the statement timeout but the connect timeout

**Comment by Kartones** [comment]
can't reproduce in local, gonna test at staging. in local the `connect_timeout` is honored and after ~2 secs I get the expected `Sequel::DatabaseConnectionError: PG::Error: timeout expired` error and doesn't gets stuck.

**Comment by Kartones** [comment]
Same at staging, I changed (from DB) a user's database_host to 10.0.0.1, and I get 500 error at the webpage, timeout error from a console.
