### ISSUE TITLE
Showing a hidden heatmap layer doesn't refresh the map until you zoom in/out

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#3494]

**Comment by fdansv** [comment]
This seems to happen with static torque maps, regardless of whether they are heatmaps or not. Animated heatmaps work as expected. I suspect this is related to https://github.com/CartoDB/torque/pull/138 . Will confirm now, and take the issue to torque.

**Comment by fdansv** [comment]
Confirmed, `torqueLayer.show()` does not effectively unhide a torque layer with a single step. Tracking from #194.
