### ISSUE TITLE
Add automatic backups / versioning of datasets

### ISSUE THREAD

**Issue by mnquintana** [CartoDB/cartodb#3495]
As far as I can tell, there is no automatic backup or versioning of tables in CartoDB, which means that if someone makes a mistake with data entry, for instance, there is no easy way to rollback to a previous working version of a table. This is actually a fairly serious issue for a production app using CartoDB as a backend. Right now I'm planning on writing a cron job to periodically duplicate production tables and lock them, but it would be really really helpful to have a backup / versioning feature baked into CartoDB.

Thanks!

**Comment by javisantana** [comment]
You can add it by yourself adding database triggers and so on. The dump is already filed in https://github.com/CartoDB/CartoDB-SQL-API/issues/55

**Comment by mnquintana** [comment]
Right, but I'm asking for it to be built into the CartoDB UI / dashboard, and to add a workflow for managing backups, instead of having to manually write a script for the purpose of backing up data. So that's really not the same thing.

**Comment by easherma** [comment]
+1 That is an issue/needs to be more clear for users. If you corrupt your data in a table, there is no easy 'undo' button. Normally, you'd keep backups yourself, but the whole point of cartodb is that they are doing the admin work for you. With an 'undo' button on the editor page, its an easy assumption to make that there is a history or backup being saved somewhere. Just made a dumb error with an UPDATE query and there appears to be no way to roll it back.
