### ISSUE TITLE
Suggestion: Send an email to user when sync has reached max_retries

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#3501]
Feedback from @d4weed

When a sync table fails to be synced and it gets to "max retries", it's never synced again. We could warn the users through an email that this is happening so that they're aware that their data will be no longer updated.

cc @saleiva

**Comment by saleiva** [comment]
Like it

Forcing the sync manually gets the sync table back, right?

**Comment by iriberri** [comment]
If you force it, it gets synced if the datasource is still ok.

But: A doubt I have is that the retries are not going back to 0 when you force one (I think), as far as i've seen by investigating the logs. 

(Check retried times with values 11 & 12, when maximum is 10 if [i'm not wrong](https://github.com/CartoDB/cartodb/blob/974565944a76f38f3f4b0476399dce844f4f4b5f/app/models/synchronization/member.rb#L26))

![image](https://cloud.githubusercontent.com/assets/1730320/7471964/9e61fbb6-f32d-11e4-9515-465b98c7396e.png)

**Comment by d4weed** [comment]
oh, this could be what's causing our issues. If the retry count doesn't get
reset that would mean just one import failure leaves the table unconnected
again. Maybe treating a manual sync as a re-setter would be better, as
otherwise older tables will always have more chances to fail than newer
ones.

A retry count of 10 can easily be met in a few months of syncing just due
to network failures

On Tue, May 5, 2015 at 1:52 PM, Carla <notifications@github.com> wrote:

> If you force it, it gets synced if the datasource is still ok.
>
> But: A doubt I have is that the retries are not going back to 0 when you
> force one (I think), as far as i've seen by investigating the logs.
>
> (Check retried times with values 11 & 12, when maximum is 10 if i'm not
> wrong
> <https://github.com/CartoDB/cartodb/blob/974565944a76f38f3f4b0476399dce844f4f4b5f/app/models/synchronization/member.rb#L26>
> )
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/1730320/7471964/9e61fbb6-f32d-11e4-9515-465b98c7396e.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/3501#issuecomment-99057969>.
>



-- 
David González
*Vizzuality*
C/. Eloy Gonzalo, 27 2º Puerta 7 - 28010 MADRID
M. +34 609125183
skype: david.gonzalez.camara
www.vizzuality.com

**Comment by iriberri** [comment]
I really don't know how it works really, it was just guessing after what I've read in the code, so we'd need an expert adding the details here :)

**Comment by ethervoid** [comment]
@saleiva I'm going to need the mail body for this :)

**Comment by ethervoid** [comment]
I have this by now:

![captura de pantalla 2015-09-07 14 22 29](https://cloud.githubusercontent.com/assets/741240/9716629/ea86b8ba-556b-11e5-9f2a-aed5752e13d5.png)

**Comment by ethervoid** [comment]
Due @saleiva is on vacation @carlostallon @piensaenpixel please give some feedback here to close this :)

**Comment by piensaenpixel** [comment]
take a look

![image](https://cloud.githubusercontent.com/assets/1214201/9718730/b9daa92a-557e-11e5-9c6f-b908d95ebc0e.png)

**Comment by ethervoid** [comment]
Cool!

I have two questions:
* I've put "There was some problem while syncying your dataset" as subject. What do you think?
* Where is the "click here" link goes (url)?

**Comment by piensaenpixel** [comment]
+1 the first point ok.

The link goes here, http://docs.cartodb.com/cartodb-editor.html#error-codes-and-solutions

**Comment by ethervoid** [comment]
Ok, thank you :)))

**Comment by piensaenpixel** [comment]
@ethervoid  this copy better, sorry

The automatic synchronization of dataset “XXXX”  has reached the maximum number of synchronization attempts—and is still failing to synch. If you'd like to continue trying, log in to your account and manually reactivate synching by clicking “Sync now.”

**Comment by ethervoid** [comment]
@piensaenpixel what do you think?

![captura de pantalla 2015-09-07 17 42 17](https://cloud.githubusercontent.com/assets/741240/9719741/e6ef266c-5587-11e5-9ae4-70964ab38851.png)
