### ISSUE TITLE
Public embeds of Odyssey maps are failing

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#3502]
#### Steps to reproduce it

1. Create a visualization.
2. Add a couple of slides.
3. Share the map (so you can see the embed).

#### Expected result

A beautiful Odyssey map :+1: 

#### Actual result

A nasty error :-1: 

The problematic line seems to be:

https://github.com/CartoDB/cartodb/blob/master/app/models/carto/visualization.rb#L73

Error log: 

```
undefined method `to_vizjson' for nil:NilClass
Extracted source (around line #35):

32: 
33:       <a href="#like" class="like js-like">
34:         <span class="icon"></span>
35:         <span class="counter"><%= @visualization.to_vizjson[:likes] %></span>
36:       </a>
37: 
38:     </div>
Rails.root: /vagrant

Application Trace | Framework Trace | Full Trace
app/models/visualization/vizjson.rb:147:in `block in children_for'
```

**Comment by juanignaciosl** [comment]
Actually it's the same than #3464.
