### ISSUE TITLE
do not use api key to fetch public datasets if it's not present

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#3506]
in app_config.yml api_key for common data is needed. It should not be mandatory specially if `common-data` account is used.

In order to do that the public visualizations endpoint should be used instead of the private one. **they are the same** so no changes would be needed

**Comment by rafatower** [comment]
I assume the intent of this is to just read the metadata from https://common-data.cartodb.com/api/v1/viz and still use the sql api without api key to import the external data sources, correct?

But, shouldn't isolated instances not depend on external accounts?

**Comment by rafatower** [comment]
After a brief chat and for the reference: for the moment the idea is to make it work for online instances w/o api key.

**Comment by rafatower** [comment]
After reviewing the code and the `api/v1/viz` endpoint for non-auth requests:
- the fields needed are `["name", "tabname", "description", "source", "license", "geometry_types", "rows", "size", "created_at", "updated_at", "category", "category_image_url"]`
- most of them are in the tables `meta_dataset` and `meta_category`
- `rows` and `size` fields are using `pg_*` system tables/views.

The proposal is to create a view for rows and size and grant permissions to public_user so we minimize modifications to the code.
