### ISSUE TITLE
Editing a map is not centering it in the "initial map"

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#3507]
If you have a table with geometries and you move the world a couple of times to any side, clicking on "add feature" should move the map to the center (according to @javisantana).

This is not happening, so when you add a feature:
1. It's appearing in the table as a new record, with coordinates out of bounds (+-180)
2. It's not appearing in the map because the_geom_webmercator is generated as null

**Comment by iriberri** [comment]
SB/5249751

**Comment by fdansv** [comment]
We should probably both:

* Wrap the view's coordinates/zoom to an inbounds value (what @iriberri says).
* Also wrap the coordinates sent when the geometry is finished.
