### ISSUE TITLE
dragging text or images in dashboard triggers importer

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/cartodb#3513]
When you select and drag text or images in the dashboard, you are prompted to drop the dragged content as if it were importing a file.

![drag](https://cloud.githubusercontent.com/assets/1041056/7481366/67fe339a-f33d-11e4-9c46-31c153fd9c87.gif)

**Comment by saleiva** [comment]
Not sure if this is easy to fix. Closing and moving this to a ticket with enhanvecements for the new dashboard. Thanks!
