### ISSUE TITLE
Ambassador account without private tables or private maps option has private map set

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#3514]
For Ambassador accounts (example: adelgado) 
- Superadmin has "private tables' and "private maps" boxes un-checked.
- In Maps dashboard some maps are marked private
- In Data View and Map View of one of those private maps, when you click the lock icon Map privacy settings = private, but when you click the pulldown menu it shows option for "Private/Enabled for paid accounts" grayed out with an Upgrade button. So is "Only for people with the link", but user has option to keep it password protected.

![unnamed](https://cloud.githubusercontent.com/assets/1779444/7482077/d6a27a36-f342-11e4-9092-2de07687767e.png)

**Comment by ztephm** [comment]
Hi @rafatower @iriberri sorry if I opened this in the wrong place! If u want me to report again in cartodb-central let me know...

**Comment by xavijam** [comment]
Moved to the proper place
