### ISSUE TITLE
Can't scroll to infowindow bottom on first open, but can when it's opened 2nd time

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#3515]
RE: S/B ticket 5153336
http://cdb.io/1EOxJBK

If you click on purple marker to open infowindow, you can scroll downward but not all the way to the bottom of the content. Scrollbar indicates you're at the bottom, when you aren't:
![screen shot 2015-05-05 at 6 36 58 pm](https://cloud.githubusercontent.com/assets/1779444/7484520/a783ba84-f357-11e4-8bc9-c310828bf62b.png)

If you close infowindow and open same one again, you're able to scroll all the way down.

**Comment by iriberri** [comment]
ping @xavijam @saleiva 

Steph could you try to reproduce it in your own account? :smile: thanks!

**Comment by ztephm** [comment]
Yep! Tested mine w/huge header images instead of txt & having same problem: http://cdb.io/1dNeFtN

**Comment by alonsogarciapablo** [comment]
The problem was that the height of the scroll was calculated before the image was loaded. That's why it was only failing the first time. The next time the infowindow was opened, the image was already loaded and the scroll was calculated correctly.
