### ISSUE TITLE
Modal inconsistency for polygon wizards image selector

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#3519]
In a polygon table, if you select in the IMG selector for the **SIMPLE** wizard a modal for patterns is shown:
![image](https://cloud.githubusercontent.com/assets/1730320/7490320/87f5c3e6-f3df-11e4-902c-f60cca13b801.png)

If you do it in **CATEGORY** wizard a modal for markers is shown:
![image](https://cloud.githubusercontent.com/assets/1730320/7490316/79c571ea-f3df-11e4-8f11-b97d8a4850b0.png)

Also, inside this modal, if you select some of the icons it says "upload image" instead of "set image":

![image](https://cloud.githubusercontent.com/assets/1730320/7490342/b170dbac-f3df-11e4-9f1b-802754183b86.png)

cc @viddo @xavijam

**Comment by viddo** [comment]
Most likely will be resolved with new modal, the new ones replacing these are planned for this sprint.

**Comment by iriberri** [comment]
By the way, I think we should design some patterns for the polygons as well as we're offering some icons for markers. Stripped/dotted svgs would be nice :)

**Comment by saleiva** [comment]
Closing since this will be fixed with the redesign :)
