### ISSUE TITLE
Suggestion: create marker wizard for polygons dataset

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#3522]
Adding a new wizard for polygons that applies CartoCSS for points so that polygons are represented as their centroids, for example.

cc @javisantana @saleiva

**Comment by saleiva** [comment]
This is the bubble map, right? It's there!

**Comment by jwishnie** [comment]
More specifically, a wizard equivalent to the one that shows for Point geometries with support for image markers. Like this: 
![poppoints___cartodb](https://cloud.githubusercontent.com/assets/62867/7496057/c895a89e-f3c6-11e4-8316-15fcfafcd210.png)
