### ISSUE TITLE
fix backbone cache now caching empty responses

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#3532]
Right now the cache caches empty responses, that does not make much sense and breaks some new dashboard onboarding.

In order to tests the issue:
- enable cached_dashboard feature flag
- create new user and go to the dashboard
- go to data library (it enters in a infinite loop)

This is actually a dashboard problem and the main ticket is not fix this bug but it shows that caching empty lists ``[]`` or objects ``{}`` does not make much sense

to fix the problem we should check here:
https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/app.js#L175

cc @viddo @javierarce @alonsogarciapablo

**Comment by viddo** [comment]
After investigating it seems like that scenario is actually not a infinite loop, and (as far as we know) there isn't any issue with the caching (since even an empty result would be updated after a fetch if diff'ing).
