### ISSUE TITLE
Quota trigger re-creation not done correctly when promoting user to org

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#3534]
See SB/5253608

I tried this on the console:
```ruby
> u = User[username: 'someusername']
> u.rebuild_quota_trigger
Setting user quota in db 'cartodb_user_someuuid_db' (someusername)
NOTICE:  function public._cdb_userquotainbytes() does not exist, skipping
=> nil
```
but still the table gives problems of type `Missing "public"._CDB_UserQuotaInBytes()`

I think the problem is that the table was in `public` schema then moved to `someorg` schema but its triggers still reference `public`. I don't know how special this case might be.

**Comment by rafatower** [comment]
I fixed this particular case by regenerating the triggers:
```sql
SELECT CDB_CartodbfyTable('orgschema', 'orgschema.broken_table_name');
```

**Comment by juanignaciosl** [comment]
This workaround has been enough in my case:

```
SELECT cartodb._CDB_drop_triggers('brokentable'::REGCLASS);
SELECT cartodb._CDB_create_triggers('schema'::TEXT, 'brokentable'::REGCLASS);
```
