### ISSUE TITLE
CDB_Math_Mode(torque_category) fails on embeds

### ISSUE THREAD

**Issue by fdansv** [CartoDB/cartodb#3538]
Today a torque cat map that worked correctly on the editor wasn't displaying any points on embeds and public pages. The error returned by windshaft was:

```
"TorqueRenderer: column reference "torque_category" is ambiguous"
```
For the record, there wasn't a column called torque_category on the table.

Once the ```-torque-aggregation-function``` was changed to ```count(cartodb_id)``` it went back to rendering points publicly, but obviously that's not the solution to the problem

@rochoa @xavijam @javisantana

**Comment by javisantana** [comment]
https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/models/carto/torque_cat.js#L32

**Comment by javisantana** [comment]
the problem is torque wrapping a wrapped query:

```
select *, (CASE WHEN "hour" = '04:00' THEN 1 WHEN "hour" = '21:00' THEN 2 WHEN "hour" = '01:00' THEN 3 WHEN "hour" = '03:00' THEN 4 WHEN "hour" = '00:00' THEN 5 WHEN "hour" = '02:00' THEN 6 WHEN "hour" = '22:00' THEN 7 WHEN "hour" = '23:00' THEN 8 WHEN "hour" = '20:00' THEN 9 ELSE 10 END) as torque_category FROM (select *, (CASE WHEN "hour" = '04:00' THEN 1 WHEN "hour" = '21:00' THEN 2 WHEN "hour" = '01:00' THEN 3 WHEN "hour" = '03:00' THEN 4 WHEN "hour" = '00:00' THEN 5 WHEN "hour" = '02:00' THEN 6 WHEN "hour" = '22:00' THEN 7 WHEN "hour" = '23:00' THEN 8 WHEN "hour" = '20:00' THEN 9 ELSE 10 END) as torque_category FROM (select * from parts7a) _cdb_wrap) _cdb_wrap
```

**Comment by javisantana** [comment]
this is backend, the query is being wrapped twice

**Comment by Kartones** [comment]
Being hotfixed with changeset 3cb74e11c4d49bed2d3f1913421ca1b3e318fe4b

Doesn't fixes the source of multiple calls but at least doesn't modifies state of `layer` and should avoid the double wrapping.

**Comment by Kartones** [comment]
ok, hotfix worked, I had to perform a "vizjson touch" to regenerate it but now the wrapped query is ok for the failing user
