### ISSUE TITLE
Fix orphans

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#3545]
![image](https://cloud.githubusercontent.com/assets/1214201/7500592/d7abb27a-f42e-11e4-9273-33d91cd5200c.png)

**Comment by saleiva** [comment]
Please :)

**Comment by viddo** [comment]
I noticed this today too, I have already fixed it in #3540 (re-introducing the max-width the cards had previously), see: ![screen shot 2015-05-06 at 18 53 19](https://cloud.githubusercontent.com/assets/978461/7498475/5287b60a-f421-11e4-9cc3-9f0fd0b7be05.png)

**Comment by viddo** [comment]
..closing since getting fixed, if you want it fixed differently let me know and I'll fix it in the PR

**Comment by javierarce** [comment]
Ok! We are using "table", "data" & "dataset" to say the same thing. I think we should use just one. I'll come up with a suggestion.
