### ISSUE TITLE
Overlays in the back go to front in the Editor when you edit them (but are back in viz.json)

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#3554]
This happens with all overlays: annotations, text...

Steps:

* Create a new empty map
* Add an image overlay (no worries about adding an actual image)
* Create an annotation. Bring it to the back (move it below the image)
* Edit the style of the annotation: change the color of the box for example.
* The annotation goes to front.

In the embed map, the overlay remains in the back. If you refresh the page, the overlay goes to the back too.

It seems that after editing it the editor is bringing up to the front and until you refresh the page it remains that way.

Not sure if a bug or a feature :stuck_out_tongue:

**Comment by javierarce** [comment]
This should be fixed now.
