### ISSUE TITLE
Tile generation seems to mix layers in some cases

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#3559]
@iriberri found this while QA testing #3493.

A public map page (`https://ded01testorg.cartodb-staging.com/u/ded01orguser/viz/ded01orguser.b5d48472-ee4a-11e4-b92a-040120e0c101/public_map?redirected=true`) _sometimes_ doesn't render the map data because of errors at tile url generation.

The requested tile contains `undefined` instead of the map_id

After speaking to @rambo he's found the error query: `https://ded01orguser.cartodb-staging.com/api/v1/map/named/tpl_b5d48472_ee4a_11e4_b92a_040120e0c101/jsonp?stat_tag=b5d48472-ee4a-11e4-b92a-040120e0c101&config=%7B%22layer0%22%3A1%2C%22layer1%22%3A1%2C%22layer2%22%3A1%2C%22layer3%22%3A1%7D&callback=_cdbc_2055364275_1`

Aometimes it returns an error:

```
error: "Error: Postgis Plugin: ERROR:  column "scalerank" does not exist↵LINE 1: ..., 6.74483e-06)) AS geom,"cartodb_id","featurecla","scalerank...↵                                                             ^↵↵in executeQuery Full sql was: 'SELECT ST_AsBinary(ST_Simplify("the_geom_webmercator", 6.74483e-06)) AS geom,"cartodb_id","featurecla","scalerank" FROM (SELECT * FROM (select * from ne_50m_land) AS wrapped_query WHERE 1=1) as cdbq WHERE "the_geom_webmercator" && ST_SetSRID('BOX3D(-20037508.3 20037508.29613578,-20037508.29613578 20037508.3)'::box3d, 3857)'↵"
```

`scalerank` column doesn't belong to `ne_50m_land` but to `ne_50m_ocean `. In the editor that column is configured to be displayed in the infowindow. _It looks like_ the named map query "mixes layers".

PD: since it's under v1/map it seems unrelated to refactor.

cc @Kartones @rafatower @javisantana

**Comment by javisantana** [comment]
I think this was a problem with named map generation cc @Kartones

**Comment by Kartones** [comment]
mm yes, looks like something related to layers, but layers always have an order and this order is kept (fixing a bug in the v1.1 endpoint I noticed how they work, they have an implicit `order by "order"`).

In any case I can research this after the refactor
