### ISSUE TITLE
Add support for importing Darwin Core Archives

### ISSUE THREAD

**Issue by peterdesmet** [CartoDB/cartodb#357]
The files I import the most in CartoDB are [Darwin Core Archives](http://en.wikipedia.org/wiki/Darwin_Core_Archive) (DwC-A). It would be awesome if I could just drag and drop these on CartoDB or synchronize directly with a remotely published Darwin Core Archive. This is almost supported, but not entirely

## Tab-delimited files

The majority of DwC-A's (including those produced by IPT or the GBIF portal) format the data as tab-delimited files. This is now supported by CartoDB: #275.

## Support file selection

A DwC-A is a zip containing multiple files, including multiple data files (e.g. core + extensions). The user should be able to choose which file to import: described in #270.

## Support compression format

When I drag and drop a DwC-A, I currently get the following error:

    Error 1003: Decompression error
    What about...: The archive you uploaded didn't seem to unpack properly. 
    Try recreating it from the original files again and uploading the new version.

You can test with: http://data.inbo.be/ipt/archive.do?r=kevers-grensmaas-occurrences

## Support synchronization

When I try to upload and synchronize via URL, I currently get the following error:

    Error 2001: Unable to load data
    What about...:  We couldn't load data from your file into the database. 
    Please contact us and we will help you to load your data.

You can test with: http://data.inbo.be/ipt/archive.do?r=kevers-grensmaas-occurrences

## Detect the_geom

Already supported: uses fields `decimallatitude` and `decimallongitude`. It ignores http://rs.tdwg.org/dwc/terms/index.htm#geodeticDatum, which could be something other than `WGS84`.

## Real DwC-A understanding

A full Darwin Core Archive reader would allow extensions to be read, understand files without headers or find other file names.

**Comment by ethervoid** [comment]
After check all the mentioned cases (import, sync, etc), it seems like it's working now. I'll close this ticket, if there is any comment, feel free to open it
