### ISSUE TITLE
Can't import multiple files

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#3572]
Something's broken with multiple files import, [I've just tried importing a zip with two csv and got an error for the second file](https://cartodb.com/superadmin/users/58607/data_imports/e5cad369-7ad1-4f10-80b1-da603c03ced2). The second file import fails because of this error:

```
2015-05-08 12:36:17 UTC: ogr2ogr output:    FAILED: Layer cdb_importer.importer_c68ce5f8f57e11e483b00e43f3deba5a already exists, and -append not specified.
```

It looks like there was no test covering this :disappointed: 

cc @lbosque @rafatower @Kartones

**Comment by lbosque** [comment]
Duplicated?
https://github.com/CartoDB/cartodb/issues/3414

**Comment by rafatower** [comment]
Indeed, duplicated (we've already talked about this one in a BE meeting BTW)

**Comment by juanignaciosl** [comment]
Uhm :-\ I didn't spot it as duplicated because I'm sure it did work before (`DataImport` redesign might not be mandatory) and it didn't contain stack trace or log import error, but if you confirm it's because of the same problem feel free to close this one. For the record, I tested it while solving #1086.

**Comment by rafatower** [comment]
It finishes the import and reports it as ok but only the first table is correctly imported. It is/was pretty easy to miss this one.
