### ISSUE TITLE
Importer creating spare index on cartodb_id

### ISSUE THREAD

**Issue by pramsey** [CartoDB/cartodb#3602]
@chriswhong reported and I verified on a randomly selected table of my own, two indices! 
In my case, on `nyc_homicides` I get `nyc_homicides_cartodb_id_key` and also `nyc_homicides_pkey`.

The last one is probably the one that is implicitly created when the table is given a UNIQUE PRIMARY KEY constraint. The first one is probably created by hand. Since they are on the same thing, it's double the storage for no advantage at all.

**Comment by Kartones** [comment]
Might not apply with new cartodbfication

**Comment by rafatower** [comment]
Solved in new cartodbfy'ation indeed. Deploying latest fixes to all users' DB's
