### ISSUE TITLE
PG::Error: ERROR: column visualizations.mapviews does not exist

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#3608]
Steps to reproduce:

1. Go to dashboard
1. Order by "visits"

Expected results: List ordered by map views
Actual results: 500 server-side error (see title)

E.g. https://rollbar.com/vizzuality/CartoDB/items/5816/ for more info etc.

**Comment by Kartones** [comment]
Branch is `3616-off-db-queries`
