### ISSUE TITLE
Dates are not appearing on infowindows on hover

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#3614]
Steps:

* Create an empty table
* Add a point, include a date in one of its columns (type date).
* Enable click and hover infowindows

![image](https://cloud.githubusercontent.com/assets/1730320/7592039/83644e5a-f8d1-11e4-98f4-9d4a485638fa.png)

![image](https://cloud.githubusercontent.com/assets/1730320/7592047/8a1835ae-f8d1-11e4-93e1-3bcfc8eb2c72.png)

(Screenshots from the editor) 
See it live: https://team.cartodb.com/u/iriberri/viz/cc860a58-f8c0-11e4-baf4-0e018d66dc29/embed_map

PS: No errors in the embed, the data is obtained with a "200 OK" but the response is empty.

cc @xavijam @javisantana

**Comment by javisantana** [comment]
duplicated: https://github.com/CartoDB/Windshaft/issues/103

the workaround is cast to string using sql

**Comment by chuycepeda** [comment]
Also dates are not working in the custom infowindow, I've tried using something like "<p>{{exec_date}}</p>", where 'exec_date' is the name of my column containing the date...

Typically after "onFeatureClick" I do something like:

var qry = "SELECT exec_date FROM " + city_table_name + " WHERE cartodb_id = " + data.cartodb_id;
city_sql.execute(qry).done(function(data) {
	$('#report_date').html(data.rows[0].exec_date);
});
