### ISSUE TITLE
Disappear custom infowindow

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#3621]
Steps:
1. Create visualization with private dataset
2. Create custom infowindow, for example only change the fields in the html
3. Change the privacy of dataset from private to public
4. Disappear infowindow :(

**Comment by rafatower** [comment]
What I'm seeing is all kinds of strange behavior when changing table's privacy: 403's when requesting tiles, can edit again the infowindo, the embed works again when saving again the infowindow.

@javisantana do you have any clue about this other than it is easy to reproduce?

**Comment by rafatower** [comment]
Also requests like `api/v1/map/undefined/3/3/2.png -> 400` when changing from private to public

**Comment by javisantana** [comment]
we can take a look tomorrow

**Comment by rafatower** [comment]
No worries, I'm decided to take a look at this and some related issues. I took a look on Friday but did not have enough time to draw conclusions.

**Comment by rafatower** [comment]
The problem is cache invalidation around these lines:

https://github.com/CartoDB/cartodb/blob/master/app/models/visualization/member.rb#L707-L709

and

https://github.com/CartoDB/cartodb/blob/master/app/models/visualization/member.rb#L313-L317

I'm working on a fix right now.

cc/ @azamorano

**Comment by rafatower** [comment]
Related to this commit: https://github.com/CartoDB/cartodb/commit/cfcf6f51
It was needed in order to invalidate all the visualizations from the public dashboard, but forgot about redis cache.
