### ISSUE TITLE
I cant modify a value in a dataset (logged as superadmin)

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#3622]
user: realmadridweb
dataset: https://realmadrid.cartodb.com/u/realmadridweb/tables/final_four

errors: ["PG::Error: ERROR: Missing "public"._CDB_UserQuotaInBytes()"]
0: "PG::Error: ERROR:  Missing "public"._CDB_UserQuotaInBytes()"

**Comment by rafatower** [comment]
Related to https://github.com/CartoDB/cartodb/issues/3534

**Comment by rafatower** [comment]
fixed for this case, need to look into the related issue
