### ISSUE TITLE
Implement new add-custom-basemap modal

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#3633]
Replace the existing basemap chooser modal:
![screen shot 2015-05-13 at 16 58 52](https://cloud.githubusercontent.com/assets/978461/7613519/7c7feb88-f991-11e4-8a66-f6fb2dd003b0.png)

With something on the lines of:
![screen shot 2015-05-13 at 16 58 16](https://cloud.githubusercontent.com/assets/978461/7613535/8fd3d42e-f991-11e4-9c57-31f7c218d052.png)

I'll implement it in steps to minimize the amount of code to review at once:
- [x] Base view + XYZ tab #3685 
- [x] WMS/WMTS tab #3731
- [x] NASA tab #3763
- [x] Mapbox tab #3807
- [x] TileJSON tab #3844

**Comment by xavijam** [comment]
Uhm, @javierarce, didn't you start with this modal?

**Comment by viddo** [comment]
Nope, image assets :)

**Comment by jatorre** [comment]
Yeah, please wher eit says WMS say WMS/WMTS and please add another category for TileJSON.

**Comment by viddo** [comment]
Okidoki, added it to the list

**Comment by viddo** [comment]
@jatorre so started looking into the TileJSON category, could you outline what the expectations/requirements are here? E.g. there's obviously [Mapbox API](https://www.mapbox.com/developers/api/maps/#tilejson), but are there others that should be supported too? cc @saleiva

**Comment by jatorre** [comment]
I did not know there were multiple TileJSON specifications.

I think there is only one which is

https://github.com/mapbox/tilejson-spec/ <https://github.com/mapbox/tilejson-spec/>

https://github.com/mapbox/tilejson-spec/blob/master/2.1.0/example/osm.layer <https://github.com/mapbox/tilejson-spec/blob/master/2.1.0/example/osm.layer>

The expectations is after specifying this TileJSON the map will:

-Load the tilset
-Zoom in to the bounds specified
-Limit the zooms as specified in the document
-Add the attribution to the attribution 
-Set the name on the layer selector to the name on the doc and maybe the description as hover info


We only need to support xyz schemes, so if the value there is not xyz we should return an error saying we only support xyz.

**Comment by viddo** [comment]
Thanks for clarifying! No, (AFAIK) there are not multiple TIleJSON specifications. I was asking to know whether we need to support different kind of providers of TileJSON URLs, since the URLs prerequisities to get a valid TileJSON result may differ. E.g. Mapbox requires an _access_token_ param to be provided on the URL to get a (valid) result, which is something that is not defined in the standard. 

It's not a problem with TileJSON per se, but how we implement the UX/UI on our end in terms of what kind of input we (need to) ask the user for. I'll discuss it with @saleiva on how we solve this.

**Comment by jatorre** [comment]
Uhm. I don't see the issue here. The tilejson format is an standard, you enter the url and the expected output format is this. If the url includes params like access token that should be transparent to us. 

There are several products implementing tilejson so definetly nothing should be mapbox specific on support for tilejson.

**Comment by viddo** [comment]
Yes, you're right.
Closing this since there's no more work to be done here (last category/TileJSON implemented in #3844).
