### ISSUE TITLE
Legend text cut off in mobile

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#3636]
re: S/B 5339386

Bubble map legend labels are cut off or stacking improperly when label text is over a certain length. 

My test: http://cdb.io/1cUW3b1 shown below too:

![screen shot 2015-05-13 at 5 23 32 pm](https://cloud.githubusercontent.com/assets/1779444/7621427/ce49116c-f994-11e4-910c-562f93544517.png)

Don't see character limit in docs. If we need to add I can, let me know.

**Comment by xavijam** [comment]
Legends are gonna change completely in the near future, so closing this one :).
Thanks @ ztephm.
