### ISSUE TITLE
Add search by email and email item to the users list

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#3641]
talk to @juanignaciosl for the backend part

**Comment by saleiva** [comment]
I'd attach the mockup soon :)

**Comment by juanignaciosl** [comment]
I'd just search by email if input text contains an '@', there's no need for UI changes.

**Comment by saleiva** [comment]
Assigning to you since this is related with the 5K thing in MU

**Comment by xavijam** [comment]
:+1:

**Comment by xavijam** [comment]
Done in https://github.com/CartoDB/cartodb/issues/3888
