### ISSUE TITLE
Broken infowindows using Layers endpoint v1.1

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#3648]
- Create custom infowindow
- Add new layer
- Change order of layers (the layer with the infowindow is the first one)
- Missing infowindows

![bugazo](https://cloud.githubusercontent.com/assets/1214201/7635212/f066c1b0-fa5f-11e4-9cb0-4eb463260b94.gif)

**Comment by Kartones** [comment]
Ok, got the flow breaking things up:
- Update call works ok and PUT stores properly the infowindow changes
- Upon page reload or something similar, new endpoint is not feching ok the infowindow so comes with `nil`
- Upon page reload, and after loading the model, seems that the UI sends a PUT, so as the infowindow hasn't been properly loaded, it gets reset to `nil` with that update.

**Comment by Kartones** [comment]
GET request comes with proper infowindow data, so is something I probably broke [here](https://github.com/CartoDB/cartodb/pull/3568) but not missing data from the backend.
