### ISSUE TITLE
Map becomes private (was public with link) after enabling infowindows

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#3658]
I have a map of two layers, I enabled infowindows in the top one, the embed worked.

I wanted to enable the infowindows in the second layers, so I deactivated the infow. in the top layer and activated them in the second. The privacy was set to private.

Will research on Monday. 

https://team.cartodb.com/u/iriberri/viz/fc04adb0-fa42-11e4-9a4f-0e5e07bb5d8a/map

**Comment by xavijam** [comment]
I checked this bug and seems like it is not happening anymore, probably it could be related with:
https://github.com/CartoDB/cartodb/pull/4867

So closing then and if happens again, let's reopen or create a new one.
