### ISSUE TITLE
Title is not appearing in a public visualisation

### ISSUE THREAD

**Issue by miguelarias** [CartoDB/cartodb#3667]
Under my team account /marias . Y created a map, changed the title and also added the fixed title in the visualisation. None of this is displayed in the public page. 
![screenshot 2015-05-16 19 35 00](https://cloud.githubusercontent.com/assets/7315954/7668373/c0772856-fc02-11e4-8018-433de19d23df.png)

**Comment by javisantana** [comment]
I guess it's the font's problem @xavijam  ?

**Comment by xavijam** [comment]
Looks like fonts (not only the title one, check the logo) are failing to load, were you @marias in a place with bad internet connection?

**Comment by iriberri** [comment]
The fixed title shouldn't appear in the public page, right?

**Comment by xavijam** [comment]
Nope, the title and the description over the map won't appear in the public page.
