### ISSUE TITLE
Refactor /api/v1/org/ and /api/v1/org/users

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#3676]
@Kartones , @rafatower , @xavijam same question than #3662, [this looks like it's not used anymore](http://ela02.useb.cartodb.net/#/dashboard/elasticsearch/org%20endpoint).

**Comment by Kartones** [comment]
Not even from central?

**Comment by juanignaciosl** [comment]
Uhm, doesn't Kibana logs Central requests as well? cc @zenitraM

**Comment by rafatower** [comment]
only used by 3 people

**Comment by zenitraM** [comment]
We don't log on Kibana requests done to Central, but we should be logging
calls done to UI from Central

On Tue, May 19, 2015 at 11:00 AM, Rafa de la Torre <notifications@github.com

**Comment by juanignaciosl** [comment]
@rafatower I've updated [Kibana query](http://ela02.useb.cartodb.net/#/dashboard/elasticsearch/org%20endpoint) removing those queries that _look like org endpoints query_ but they're not. There's been only one valid request in 2015, without referrer.

I can't find any usage of this. Central seems to use `/superadmin/` routes. If you take a look at [the controller](https://github.com/CartoDB/cartodb/blob/master/app/controllers/api/json/organizations_controller.rb) it looks like it was done thinking in JS API (see `current_user` usage), and it has not changed since [the first commit](https://github.com/CartoDB/cartodb/commit/8113e8ec9e091ab4220cd8da691f919a1c98fa08#diff-ca06d20ba628beb8a9ef4018818c22fd) (June, 12). I'd delete it unless @Kartones or @xavijam see something I don't.

**Comment by juanignaciosl** [comment]
@xavijam [JS organization model](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/models/organization.js#L14) uses that endpoint, but I can't trigger them, are they actually used?

**Comment by xavijam** [comment]
Yes and no -> https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/models/organization.js#L28

**Comment by juanignaciosl** [comment]
:-\

I guess I should keep those endpoints then, since JS code points to them (although they're currently "disabled"), isn't it?

**Comment by xavijam** [comment]
It is disabled, yep.

**Comment by juanignaciosl** [comment]
Sorry, I haven't explained well. I was asking about keeping them or deleting them. We're refactoring all API endpoints: all of them will use the new `v1_1` requests, and we're deleting the unused ones. My question was not whether it's disabled but whether I should keep (and refactor) it or deleting them.

If there's a good reason for keeping that JS code, even if currently disabled, I will create the new endpoint and controller. If it's not, I'll delete the endpoints and controller (and maybe I should delete JS code as well).

**Comment by juanignaciosl** [comment]
Closing because there's no point in refactoring unused code.
