### ISSUE TITLE
oneclick doesn't works in my account at least

### ISSUE THREAD

**Issue by Kartones** [CartoDB/cartodb#3684]
Checking another issue, I've found that the oneclick option doesn't work, at least when creating a map from the button navigating other users maps

```
http://oneclick.cartodb.com/.../?file=http://trainings.cartodb.com:80/api/v2/sql?q=SELECT%20*%20FROM%20public.partidos&format=shp&provider=trainings&logo=https://s3.amazonaws.com/com.cartodb.users-assets.production/production/trainings/assets/20150415134817Screen%20Shot%202015-04-15%20at%2015.48.00.png
```

## steps to reproduce
- Being logged in, navigate for example to one dataset of account trainings.cartodb.com (e.g. https://trainings.cartodb.com/tables/partidos/public)
- Click on "Create Map"

## Expected behaviour
- You get your map "cloned"

## Error
- It stays forever loading, and if I enter the dashboard the import is `pending`

## Notes
Tried both with normal user (`trainings`) and an organization user (`xavijam`), same results.

**Comment by matallo** [comment]
I don't know the source for this issue, it fails with `shp`, it works with `geojson`

you can try here:
http://oneclick.cartodb.com/?file=http%3A%2F%2Ftrainings.cartodb.com%3A80%2Fapi%2Fv2%2Fsql%3Fq%3DSELECT%2520%2A%2520FROM%2520public.partidos%26format%3Dgeojson&provider=trainings&logo=https://s3.amazonaws.com/com.cartodb.users-assets.production/production/trainings/assets/20150415134817Screen%2520Shot%25202015-04-15%2520at%252015.48.00.png

maybe @xavijam can throw some light here

**Comment by xavijam** [comment]
https://github.com/CartoDB/cartodb/issues/3645
