### ISSUE TITLE
window.URL to validate URL not working in IE

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#3692]
I saw [this piece of code](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/app.js#L40-L46) in app.js, that defines the `prefixUrlPathname`. This `window.URL` [is experimental and not supported in IE](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL#Browser_compatibility), so this won't probably work as expected. 

Luckily, don't seem to be used for anything [critical](https://github.com/CartoDB/cartodb/search?utf8=%E2%9C%93&q=prefixUrlPathname), but most likely it will lead to weird bug reports eventually so we should probably fix it anyway.

**Comment by javisantana** [comment]
good catch

**Comment by viddo** [comment]
I did this [minimal check](https://github.com/CartoDB/cartodb/commit/46a9cf0bfce956e610a5df6705650436572e3ccd) here, to not overcomplicate it, I guess we could do something similar there? LTM if you want it to be done differently.

**Comment by fdansv** [comment]
Do we need to use URL at all? Why not use the ```a``` element?
```javascript
var a = document.createElement('a');
a.href = this.prefixUrl();
var url = a.pathname;
// remove trailing slash
return url.replace(/\/$/, '');
```

**Comment by javisantana** [comment]
because that is a hack

**Comment by fdansv** [comment]
Yeah also, as discussed IRL with @viddo it isn't really a check for real URLs at it won't throw an exception with malformed URLs.
