### ISSUE TITLE
Add TMS option for XYZ URL add custom basemap modal

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#3694]
The TMS option indicate that the values of the Y-values should be inverted. It's an optional setting to be provided together with a XYZ url.

I proposed something on the lines of (since it was lacking in the mockup)
![screen shot 2015-05-19 at 12 58 29](https://cloud.githubusercontent.com/assets/978461/7701491/eaea878c-fe27-11e4-90ba-8727cf878d7a.png)
however, @saleiva rejected it with the motivation that you'd do a better one.. ;)

See #3685 for previous PR/context

**Comment by josecruz** [comment]
@
![map editor - layer basemap add basemap wms copy](https://cloud.githubusercontent.com/assets/596509/7707744/a3cc10ee-fe51-11e4-98dc-9dd1631b960f.png)
@saleiva Here's my take, I've moved the placeholder to the "description" so there will be always visible the sample format. I made a line-break for improve the url legibility (we could even remove "http://").

**Comment by saleiva** [comment]
HA!

+ Nobody reads the descriptions I think, that was the reason of making this he placeholder... or then I'd relate visually with the input

**Comment by josecruz** [comment]
Second take. As @viddo and Javi explained to me the TMS just invert Y coordinates so I've just added a small hint on the checkbox. I remove "description" text then?
![screen shot 2015-05-19 at 18 52 13](https://cloud.githubusercontent.com/assets/596509/7708805/a52b1898-fe58-11e4-94d6-daee933f0644.png)

**Comment by saleiva** [comment]
Don't like it tho.
I'll go back to the placeholder. It's closer from when you validate which is better (fitts law :P)
TMS shouldn't have so much entity on this modal. I'd think on something more integrated as part of the input?

**Comment by josecruz** [comment]
Second take, now closer to the input. I made a color separation as well to avoid input confusion.
![map editor - layer basemap add basemap wms copy](https://cloud.githubusercontent.com/assets/596509/7721643/84799fbc-fed9-11e4-8150-5daed28b7af6.png)

**Comment by saleiva** [comment]
Liking much more. Wondering if having the check on the right would give us
more space without breaking the composition to explain that TMS thing a bit
more.

2015-05-20 9:20 GMT+01:00 josecruz <notifications@github.com>:

> Second take, now closer to the input. I made a color separation as well to
> avoid input confusion.
> [image: map editor - layer basemap add basemap wms copy]
> <https://cloud.githubusercontent.com/assets/596509/7721643/84799fbc-fed9-11e4-8150-5daed28b7af6.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/3694#issuecomment-103805823>.
>



-- 
Sergio Alvarez Leiva

**Comment by josecruz** [comment]
That was my first try but it's kinda weird. We could use something like this instead

![screen shot 2015-05-20 at 10 29 25](https://cloud.githubusercontent.com/assets/596509/7721842/43b95290-fedb-11e4-894e-18be1b04b389.png)

**Comment by saleiva** [comment]
Nah, too much visual noise IMO. Why was it weird?

2015-05-20 9:31 GMT+01:00 josecruz <notifications@github.com>:

> That was my first try but it's kinda weird. We could use something like
> this instead
>
> [image: screen shot 2015-05-20 at 10 29 25]
> <https://cloud.githubusercontent.com/assets/596509/7721842/43b95290-fedb-11e4-894e-18be1b04b389.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/3694#issuecomment-103807738>.
>



-- 
Sergio Alvarez Leiva

**Comment by josecruz** [comment]
It's like misaligned with everything else. I made this one without any explanation of what TMS is
![screen shot 2015-05-20 at 10 42 58](https://cloud.githubusercontent.com/assets/596509/7722104/649be8fe-fedd-11e4-830a-7dccc0bb4a85.png)

**Comment by saleiva** [comment]
on hold until I come back :)
Remind me the next time I pass by the office.



2015-05-20 9:46 GMT+01:00 josecruz <notifications@github.com>:

> It's like misaligned with everything else. I made this one without any
> explanation of what TMS is
> [image: screen shot 2015-05-20 at 10 42 58]
> <https://cloud.githubusercontent.com/assets/596509/7722104/649be8fe-fedd-11e4-830a-7dccc0bb4a85.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/3694#issuecomment-103813001>.
>



-- 
Sergio Alvarez Leiva

**Comment by javisantana** [comment]
Why the options for the modals in basemaps are in a different place than other modals, for example, connect dataset (I don't like the placement, buts that's another issue)
![screen shot 2015-05-20 at 10 56 10 am](https://cloud.githubusercontent.com/assets/30147/7722272/f43ccab8-fede-11e4-93a0-8df5e157cabc.png)

**Comment by saleiva** [comment]
That's that I wanted to talk with him. Spoiler.

2015-05-20 9:57 GMT+01:00 javi santana <notifications@github.com>:

> Why the options for the modals in basemaps are in a different place than
> other modals, for example, connect dataset (I don't like the placement,
> buts that's another issue)
> [image: screen shot 2015-05-20 at 10 56 10 am]
> <https://cloud.githubusercontent.com/assets/30147/7722272/f43ccab8-fede-11e4-93a0-8df5e157cabc.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/3694#issuecomment-103815307>.
>



-- 
Sergio Alvarez Leiva

**Comment by josecruz** [comment]
Checkbox inside the input version. I like this way. Maybe we can show a tooltip when hover TMS.
![map editor - layer basemap add basemap xyz](https://cloud.githubusercontent.com/assets/596509/7807746/62c6dede-038e-11e5-98ea-0e5313f81296.png)
![map editor - layer basemap add basemap xyzasf](https://cloud.githubusercontent.com/assets/596509/7807747/62d14586-038e-11e5-9ecb-add3fb00378e.png)

**Comment by saleiva** [comment]
+1. Pass it no nicklas

**Comment by viddo** [comment]
However, at the moment there's already an icon at that location, indicating current state, i.e.

idle:
![screen shot 2015-05-26 at 10 11 20](https://cloud.githubusercontent.com/assets/978461/7807958/b67fdb38-038f-11e5-8ed6-a0c70cbead44.png)
validating input:
![screen shot 2015-05-26 at 10 11 57](https://cloud.githubusercontent.com/assets/978461/7807959/b688c342-038f-11e5-90de-bc7c10b1ff94.png)

so what to do about those then?

**Comment by saleiva** [comment]
Lets move the icon to the left or remove it on those inputs (on the import
URL one I think de removed it)

**Comment by xavijam** [comment]
![tms-example](https://cloud.githubusercontent.com/assets/132146/7816230/50270e40-03cd-11e5-8be2-53edea2b98d5.gif)
