### ISSUE TITLE
Order by size failing on new viz list new endpoint

### ISSUE THREAD

**Issue by Kartones** [CartoDB/cartodb#3701]
Trace: https://rollbar.com/vizzuality/CartoDB/items/6724/occurrences/5452240404/

## Description
Ordering field gets stored (don't know where exactly) in the editor and breaks if you order datasets by size and go to your maps (which don't have that option).

## How to reproduce
- Login into your account (new endpoint must be activated)
- Go to your datasets and order by size
- Go to your maps, the list will break

## Expected results
- As maps has no order by size, I guess the filter should default to other ordering. Or maybe have store different settings (filters) for Maps and Datasets. That's not my call so just suggesting.

----
Backend note: I'll make the backend smarter to allow to order by size, but Maps will return size 0 as they don't eat any DB space (being just metadata).

**Comment by Kartones** [comment]
@chriswhong it looks you have one visualization broken, either that or the code is thinking so and then is a bug.

I'm disabling you the v1.1 endpoint so your dashboard works again, can you check if all your Maps are ok and get back to me?

**Comment by Kartones** [comment]
ohh, actually found the real issue!

Updating the description and assigning to a frontend guy, I'll reactivate your v1.1 endpoint, reordering your maps fixes the issue for you @chriswhong

**Comment by chriswhong** [comment]
Thanks!  What's the "real issue"?

**Comment by Kartones** [comment]
It's in the ticket description (open it in github and you'll see it)

**Comment by xavijam** [comment]
My question here is, what we should do in the maps section then?
Should we set the "order" attribute as "updated_at" in this page and respect size order in the datasets section?
