### ISSUE TITLE
suggestion: removing disqus from X public pages with an option 

### ISSUE THREAD

**Issue by yasharora73** [CartoDB/cartodb#3721]
@xavijam @saleiva 

Hi guys,

Spoke to @iriberri  about this already. We had a query from a user.

Thanks for reaching out. I was concerned about one feature of CartoDB... Comments from random public maps appear at the bottom of my map screen and one of them uses profanity. I plan to use my maps for a professional purpose so this is highly inappropriate and this feature seriously deters me from using it. Is there anything I can do to remove those comments from my map link all together?

We do moderate comments but removing disqus from X sites with a layer could be a good idea
(for professional environments)

Thanks :)

**Comment by saleiva** [comment]
Happy  to add a toggle on the enterpise admin
