### ISSUE TITLE
Embeds and vizjson caching in redis

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#3722]
In order to be able to cope with a failure in varnish:
- Cache both embeds and vizjson
- Cache only those that are public and private with link
- Version both cache keys

This will be roughly the caching schema:
```
request -> varnish -> redis I -> rails -> redis II (vizjson) -> rails (if not cached)
```

**Comment by Kartones** [comment]
I'd add an additional task (maybe for Devops): Add a Jenkins deploy checkbox to invalidate this new cache (to avoid having to increment version each time we change something in the vizjson signature).
