### ISSUE TITLE
allow management sql queries form the editor

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#3727]
Some queries can be executed form the editor, like reindex, it would be nice to be able to do so.

The problem is here: 
https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/models/table.js#L882

Some of the queries we may want to add support:

- REINDEX
- GRANT
- CLUSTER (hmm, I thought I saw that work)
- REFRESH MATERIALIZED VIEW
- COPY

**Comment by pramsey** [comment]
This is resolved at a081ddaa1c484add4d8f94a5b7bf5a21dbb0e562
