### ISSUE TITLE
Implement search for new add-custom-WMS-basemap modal

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#3738]
Implement the search of WMS/WMTS layers to easier find the wanted layer to add as a basemap:
![screen shot 2015-05-22 at 10 38 12](https://cloud.githubusercontent.com/assets/978461/7768820/2ea5ac96-007f-11e5-878e-15aea91bd1bf.png)

**Comment by javierarce** [comment]
How does the search work here? Is the list filtered on keydown?
