### ISSUE TITLE
Geocoding don't geocode all rows

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#3746]
I've imported [this table](http://15mpedia.org/wiki/Lista_de_casos_de_corrupci%C3%B3n) into [this one](https://team.cartodb.com/u/juanignaciosl/tables/corrupcion_espana/public) and geocoding doesn't work as expected. Many rows are not geocoded in spite of having the same value. I've geocoded with "ambito" column in "Spain" country, and, for example, Baleares is geocoded in row 65 but not in row 77.

**Comment by iriberri** [comment]
I have detected this behaviour too

**Comment by iriberri** [comment]
Cannot reproduce anymore. Closing. :-)
