### ISSUE TITLE
Ghost tables breaks when renaming to a long name

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#3747]
How to reproduce:
rename a table to a name with 60 chars through the sql api:
```
create table my_table();
select cdb_cartodbfytable('my_table');
alter table my_table rename to this_is_my_table_with_a_long_name_f6mnr990vl8t732bztip0s43hk;
```

Expected:
Table is renamed correctly, after a few seconds it is shown in the dashboard and does not lose any capability

Actual:
Table renamed in the dashboard but cannot be accessed anymore. Inconsistent metadata and name in user DB. ghost tables stuck trying to rename and register it.

There must be some limitation in length of table names.

**Comment by rafatower** [comment]
The name seems limited to 53 chars, don't ask me why:
```
(rdb:1) e
#<CartoDB::InvalidMember: PG::Error: ERROR:  relation "public.this_is_my_table_with_a_long_name_f6mnr990vl8t" does not exist

(rdb:1) puts e.backtrace
/home/developer/src/cartodb/app/models/visualization/member.rb:807:in `rescue in propagate_name_to'
/home/developer/src/cartodb/app/models/visualization/member.rb:796:in `propagate_name_to'
/home/developer/src/cartodb/app/models/visualization/member.rb:782:in `propagate_privacy_and_name_to'
/home/developer/src/cartodb/app/models/visualization/member.rb:722:in `do_store'
/home/developer/src/cartodb/app/models/visualization/member.rb:155:in `store'
/home/developer/src/cartodb/app/models/user.rb:1164:in `block in link_renamed_tables'
/home/developer/src/cartodb/app/models/user.rb:1154:in `each'
/home/developer/src/cartodb/app/models/user.rb:1154:in `link_renamed_tables'
/home/developer/src/cartodb/app/models/user.rb:1095:in `link_ghost_tables'
/home/developer/src/cartodb/lib/resque/user_jobs.rb:16:in `perform'
/var/lib/gems/1.9.1/gems/resque-1.25.2/lib/resque/job.rb:240:in `block (3 levels) in perform'
```

**Comment by pramsey** [comment]
53, or 63? I just tried a big name and got

    NOTICE:  identifier "foofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoo" 
    will be truncated to "foofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoo"
    CREATE TABLE

**Comment by rafatower** [comment]
We're talking about different limits but I guess the effective one will be `min(limit_a, limit_b)`

**Comment by rafatower** [comment]
@pramsey this is the limit you're referring to: http://www.postgresql.org/docs/9.3/static/sql-syntax-lexical.html
> The system uses no more than NAMEDATALEN-1 bytes of an identifier; longer names can be written in commands, but they will be truncated. By default, NAMEDATALEN is 64 so the maximum identifier length is 63 bytes. If this limit is problematic, it can be raised by changing the NAMEDATALEN constant in src/include/pg_config_manual.h.

The one I'm currently investigating must be in how we load rails metadata. Apparently it is correctly persisted:
```
carto_db_development=# select id, type, name from visualizations where user_id = (select id from users where username='development') and name like 'this_is%';
                  id                  | type  |                             name                             
--------------------------------------+-------+--------------------------------------------------------------
 8274ca18-02f6-11e5-bca3-0242ac110001 | table | this_is_my_table_with_a_long_name_f6mnr990vl8t732bztip0s43hk
(1 row)
```
so it must be a problem with the legacy orm.

**Comment by rafatower** [comment]
Finally found the line to "blame" in the ruby code:
https://github.com/CartoDB/cartodb/blob/master/app/models/table.rb#L1502

We need to figure out how to gracefully deal with these cases. In the meantime the workaround is to use table names shorter than 46 chars.

**Comment by saleiva** [comment]
Can we create a new issue for the backend so we don't let people to create / update tables with names longer than 63 chars?
