### ISSUE TITLE
404 petition editing shared writeable tables

### ISSUE THREAD

**Issue by Kartones** [CartoDB/cartodb#3751]
## Description
Checking Chrome dev tools I've noticed a 404 upon editing a table, although all the editor seems to work fine.

## Steps to reproduce
- Have USERB share a dataset TABLENAME with USERA, with write permissions.
- Navigate with USERA to `https://ORG.cartodb.com/u/USERA/tables/USERB.TABLENAME` having Chrome network tab open.
- A 404 GET request to `https://ORG.cartodb.com/u/USERA/api/v1_1/tables/TABLENAME` will appear.[1] 

## Expected result
- 20 GET request to `https://ORG.cartodb.com/u/USERA/api/v1_1/tables/USERB.TABLENAME`

[1]: There's also a call to `https://ORG.cartodb.com/u/USERA/api/v1_1/tables/USERB.TABLENAME` afterwards so I'm guessing here the FE might be retrying correctly or something as everything is fine.

**Comment by xavijam** [comment]
I feel this is already fixed in the new builder, if happens, we will open a new one @kartones, we miss you :).
