### ISSUE TITLE
Redesign privacy modal window CTA upselling

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#3753]
![screen shot 2015-05-25 at 15 20 38](https://cloud.githubusercontent.com/assets/132149/7797808/abb78316-02f1-11e5-8180-ee6dbc81263d.png)

When being on an Free Account. Also try when being on a paid with no MU account.
Too much blue plus some missalignement issues.

**Comment by saleiva** [comment]
![screen shot 2015-05-25 at 15 25 16](https://cloud.githubusercontent.com/assets/132149/7797854/487c1b80-02f2-11e5-9cf9-f8e39c9a8629.png)
Here, things are more aligned

**Comment by josecruz** [comment]
So I made this version with alignment changes plus a color change:
![map editor - privacy modal free](https://cloud.githubusercontent.com/assets/596509/7938901/4f9cfd1a-0948-11e5-888d-faf888089b76.png)

PD: How can I try *being on a paid with no MU account*?

**Comment by saleiva** [comment]
I like it. 
Talk to @zenitraM on how to become a paid user :)

**Comment by saleiva** [comment]
BTW, the mockup you prepared is with 4 options, but in the screenshot it has 3, be sure you take that into consideration

**Comment by josecruz** [comment]
@saleiva okay, with 3 options it would look like this:
![map editor - privacy modal free copy](https://cloud.githubusercontent.com/assets/596509/7940016/7e5b8274-094e-11e5-9680-bd20e23740aa.png)

And I suggest:
![map editor - privacy modal free copy 2](https://cloud.githubusercontent.com/assets/596509/7940087/ed93e2ee-094e-11e5-87b7-8b43240ee6af.png)
That keeps respecting the grid and is more symetrical.

**Comment by josecruz** [comment]
Password protected 
![map editor - privacy modal free](https://cloud.githubusercontent.com/assets/596509/7963680/43e3d486-0a14-11e5-9dea-7dd93b1a59c1.png)

I would keep the rest of the flow as it is right now

**Comment by saleiva** [comment]
Like. What about when not having trial? We just remove the small text, right?

**Comment by saleiva** [comment]
Also, as an improvement, I¡d leave this out of this milestone (for the next one)

**Comment by javierarce** [comment]
:ok_hand:
