### ISSUE TITLE
Can't geocode a table shared with me

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#3775]
If I try to geocode a table shared with me (write permissions) [it fails](https://rollbar.com/vizzuality/CartoDB/items/7041/). Not sure if this is actually the desired behaviour.

Happens in both old and new endpoints.

cc @Kartones @rafatower @iriberri

**Comment by Kartones** [comment]
really, I don't recall having tested that ever... probably is missing the schema name somewhere, but maybe the whole geocoder is missing it :/

**Comment by saleiva** [comment]
This should work.

**Comment by rafatower** [comment]
Relevant backtrace from local:
```
#<Sequel::DatabaseError: PG::Error: ERROR:  must be owner of relation guess_ip
/home/developer/src/cartodb/services/table-geocoder/lib/abstract_table_geocoder.rb:64:in `ensure_georef_status_colummn_valid'
/home/developer/src/cartodb/services/table-geocoder/lib/abstract_table_geocoder.rb:56:in `mark_rows_to_geocode'
/home/developer/src/cartodb/app/models/geocoding.rb:112:in `run!'
/home/developer/src/cartodb/lib/resque/geocoder_jobs.rb:9:in `block in perform'
/home/developer/src/cartodb/lib/resque/base_job.rb:21:in `call'
/home/developer/src/cartodb/lib/resque/base_job.rb:21:in `run_action'
/home/developer/src/cartodb/lib/resque/geocoder_jobs.rb:9:in `perform'
```

**Comment by rafatower** [comment]
Related to https://github.com/CartoDB/CartoDB-SQL-API/issues/230, thanks @juanignaciosl for pointing out. Will try to fix in [CDB_Organization_Add_Table_Read_Write_Permission](https://github.com/CartoDB/cartodb-postgresql/blob/master/scripts-available/CDB_Organizations.sql#L52)

**Comment by rafatower** [comment]
From http://www.postgresql.org/docs/current/static/sql-altertable.html
> You must own the table to use ALTER TABLE

so for this very case we may have to use the owner...

**Comment by juanignaciosl** [comment]
Oh, [it's not grantable at all](http://www.postgresql.org/docs/9.0/static/sql-grant.html): "The right to drop an object, or to alter its definition in any way, is not treated as a grantable privilege; it is inherent in the owner, and cannot be granted or revoked. (However, a similar effect can be obtained by granting or revoking membership in the role that owns the object; see below.)".

It looks like in order to support this without using the owner we should move to a per-table-role permission management.
