### ISSUE TITLE
Error executing update query on editor

### ISSUE THREAD

**Issue by jsanz** [CartoDB/cartodb#3804]
In editor I try to run an update

```sql
update venue set venuecity = 'USA'
```

but the editor replaces the table and column names and fails

```sql
update jsanz.venue set jsanz.venuecountry = 'USA'
```

Running the query from the SQL API works as expected though.

**Comment by saleiva** [comment]
I'm afraid this could have something to do with the refactor cc @Kartones

**Comment by Kartones** [comment]
the editor also does some table qualification... while might be, I checked recently LayerPresenter code and we only qualify if you're operating with layers from other users.

In any case, can be checked by applying the query and checking if the FE sends to the backend a PUT with `jsanz.venue` or doesn't and is the backend the one returning schema-qualified table names

**Comment by jsanz** [comment]
I've tried again and the editor is sending the wrong SQL

![screenshot](http://i.imgur.com/bNr4m6z.png)

**Comment by fdansv** [comment]
@jsanz I'm not able to replicate this at the moment, the query is being sent to the api as is. Is this still happening to you?

**Comment by jsanz** [comment]
nope, tried again this update and it's working fine, now the sql api call is correct.

**Comment by fdansv** [comment]
aw yisssss
