### ISSUE TITLE
URL with params is not importing

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#3810]
Hi please check url here: Support Bee ticket #5457198

User wants to pass parameters with his dataset url that he can use for a SQL query on his end with Open In CartoDB, but our importer is throwing DOWNLOAD ERROR: Code:400

**Comment by iriberri** [comment]
One more in SB/5533191

**Comment by Kartones** [comment]
I've checked the url from SB 5457198 and the issue there is that user is not properly URL-encoding the parameters `$where` and `$order`. Will check the other ticket.

**Comment by Kartones** [comment]
The other issue is a SQL API timeout due to expensive query:
```
{
error: [
"Your query was not able to finish. Either you have too many queries running or the one you are trying to run is too expensive. Try again."
]
}
```
