### ISSUE TITLE
Follow redirects on URL imports (yes, again!)

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#3811]
@Kartones thought we already did, but in this case the URL is failing.

If we use the URL that makes the redirect, the import fails:
http://water.weather.gov/ahps/download.php?data=kmz_obs

If we use the direct URL, it works:
http://water.weather.gov/ahps2/worldfiles/ahps_national_obs.kmz

Same happens for the zipped version of the URL:
http://water.weather.gov/ahps/download.php?data=tgz_obs

**Comment by Kartones** [comment]
The issue is not a redirect, but a missing `Content-Disposition` header + `download.php` "file name" causing a wrong download of the content into a temporal `download.php` file, thus breaking the import.

I'm going to think about an alternative to try to capture this scenarios.
