### ISSUE TITLE
New map editor modals (Table Merge)

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#3819]
@saleiva I'll upload it here the spatial join that I was working on:

- Empty state:
![2nd step copy 2](https://cloud.githubusercontent.com/assets/596509/7844660/586ccb86-04b2-11e5-97fc-370cbedab095.png)

- Dataset selected:
![2nd step copy 3](https://cloud.githubusercontent.com/assets/596509/7844685/68c8838a-04b2-11e5-8222-872174e0ef43.png)

- Operation selected:
![2nd step copy](https://cloud.githubusercontent.com/assets/596509/7844693/7a41b8a2-04b2-11e5-9e87-133553b5ac40.png)

- Error:
![2nd step copy 31](https://cloud.githubusercontent.com/assets/596509/7844707/93c9060e-04b2-11e5-83b3-60e7ce00d7ae.png)
![2nd step copy 32](https://cloud.githubusercontent.com/assets/596509/7844708/93cae776-04b2-11e5-8c89-07818ccc18ab.png)
![2nd step copy 33](https://cloud.githubusercontent.com/assets/596509/7844709/93d267d0-04b2-11e5-9d7f-e74b551ddbf6.png)

**Comment by josecruz** [comment]
Updated version with hints on footer and aligned *merge all columns* slider :

![2nd step copy3](https://cloud.githubusercontent.com/assets/596509/7846203/7ac54ef6-04bc-11e5-9ab7-fcab62b53fe2.png)

+ count

![2nd step copy](https://cloud.githubusercontent.com/assets/596509/7846223/97a90418-04bc-11e5-9b2a-e150c68f024f.png)

**Comment by saleiva** [comment]
That illustration... HAHA

Any idea to relate visual the hint with the button?

**Comment by saleiva** [comment]
BTW, the second one is lacking the line, right?

**Comment by josecruz** [comment]
Haha I need to improve my illustration skills. 
*BTW, the second one is lacking the line, right?*
Mm not at the moment. Maybe instead of that yellow, the same blue as the selected one on the segmented control

**Comment by saleiva** [comment]
No no, it should be the line, since the_geoms are connected anyway, rihgt?

**Comment by josecruz** [comment]
Damn, quoted wrong message :\ 
Yes, got it!

**Comment by josecruz** [comment]
So, what about an arrow to reinforce that right column will make the operation.
![2nd step copy](https://cloud.githubusercontent.com/assets/596509/7865587/279ab67c-056a-11e5-8bfe-4ff8d6722b94.png)

**Comment by saleiva** [comment]
Looking good. Only thing I'm concerned about is the legibility of the text on the top. It's there in such an small area and can be missed easily IMO

**Comment by josecruz** [comment]
@saleiva Yay! Well, about the legibility, I think that if we place all messages/extra info/help always on the same place we don't have anything to worry about, do we?

**Comment by viddo** [comment]
So I started looking at this one to start working on it but have some doubts:
- The current merge modal has two different kind of merges, _columns_ or _spatial_, is the columns one going to be removed with the new modal? Or how is that one going to be integrated with these sketches?
- An observation re: the disabled list items (it's not unique to this use-case BTW): there's no explanation to _why_ they're disabled which is confusing for an user. What's the reason for not giving some explanation for this? A tooltip on hover or similar would be very helpful.

**Comment by saleiva** [comment]
Hey, I think you are getting the designs wrong.
You might want to talk with @josecruz.

About your second point, we should change the text on the type to something like “String.incompatible type”
S,

**Comment by viddo** [comment]
:+1:

**Comment by viddo** [comment]
@xavijam @javisantana regarding technical solution for this: from what I can see on the new sketches this is not that different from existing modal. It's mostly visual enhancements, so under the circumstances (basically only have this milestone to finish this one + a bunch of other modals), I'm considering taking the same approach as I did for the  export modal (i.e. duplicate existing view/tests and massage existing code into working with new styles/functionality). Do you have any opinion regarding this approach? Is there anything else I should be aware of or anything you think should be taken care of while working on this modal?

**Comment by javisantana** [comment]
It's ok for me

**Comment by xavijam** [comment]
As you may know, we have a problem in this dialog when a user with a lot of tables has to choose one. Haven't we thought about this issue?

**Comment by saleiva** [comment]
@viddo there are a few differences. We should check if types are compatible in order to disable them or not when selecting the columns. @xavijam I thought we fixed that issue with your last commit, isn't it fixed?

**Comment by saleiva** [comment]
@josecruz design of opened selector should be also attached

**Comment by josecruz** [comment]
Yup, I designed one for the geocode stuff and here's one for the column. @carlostallon do you like it?

![1st step_dropdown](https://cloud.githubusercontent.com/assets/596509/8007169/54d1a430-0b9a-11e5-875a-f69dda4afecc.png)
![1st step_dropdown_selected](https://cloud.githubusercontent.com/assets/596509/8007231/bc69c94c-0b9a-11e5-85d2-026f37c74325.png)

**Comment by saleiva** [comment]
Don't like it. I think there are a few of them designed. I'd make them floating so we can make the list wither than the selector when needed.

**Comment by josecruz** [comment]
Okay so what about this one?
![1st step_dropdown_selected](https://cloud.githubusercontent.com/assets/596509/8009474/590617fc-0ba9-11e5-8b75-336f63f6cb0f.png)

**Comment by saleiva** [comment]
Why should it be so big? Is there any metadata that might be of interest to show apart from the table name?

**Comment by josecruz** [comment]
What size should it be? Showing some information could be really nice, but what kind of info? Rows, size, metadata, description... (?)

**Comment by josecruz** [comment]
I made this alternative: 
![1st step_dropdown_selected_2](https://cloud.githubusercontent.com/assets/596509/8063665/6db716ee-0ed6-11e5-9b0e-4dd71692a1cd.png)
![1st step_dropdown_selected](https://cloud.githubusercontent.com/assets/596509/8063666/6dc34e00-0ed6-11e5-8f35-d01c6cac7b88.png)

(thanks to emilio for the help)

**Comment by saleiva** [comment]
I'd prefer the icons one (we will have to simplify them).
Another interesting metadata could be the modification date.

Could you also make it less width so it doesn't look to have the same size?
I'd explain you why once I'll be back

**Comment by josecruz** [comment]
Something like this?
![1st step_dropdown_selected_2](https://cloud.githubusercontent.com/assets/596509/8063961/fb6849e4-0ed7-11e5-817c-7c4dad34571d.png)

**Comment by viddo** [comment]
Regarding this kind of dropdown menu... why no focus more on usability than the visuals? End of the day, the purpose of the dropdown is to not display all items at once and make it easy to find the wanted item for the user, right? So why not use something similar to what Github does? i.e.:
![screen shot 2015-06-09 at 18 44 53](https://cloud.githubusercontent.com/assets/978461/8063935/d6cce158-0ed7-11e5-9b48-724a50f9434e.png)
 
Btw, AFAIK we already load [select2 lib](https://select2.github.io/) so I guess we want to continue to use that one, and we might as well take advantage of it. That way we don't have to load all of the tables of the user up front either, e.g. the use-case where an user has hundreds or even thousands of tables.

**Comment by saleiva** [comment]
@viddo right, I was expecting @josecruz to do that exact comment (bastard).
@josecruz please align it to the right!

**Comment by josecruz** [comment]
Okay, search box integrated with the dropdown
![1st step_dropdown_selected_2](https://cloud.githubusercontent.com/assets/596509/8080272/4588d956-0f6b-11e5-8983-fe6b48cd6d72.png)

**Comment by saleiva** [comment]
What about using a similar style to the one we have on the actual geocoder dropdowns? less noisy I thnk

**Comment by josecruz** [comment]
Done
![1st step_dropdown_selected_2](https://cloud.githubusercontent.com/assets/596509/8084597/2a645a1c-0f8c-11e5-8cc1-aadea7ecfff7.png)

**Comment by saleiva** [comment]
![screen shot 2015-06-11 at 11 42 45](https://cloud.githubusercontent.com/assets/132149/8104184/009a22ae-102f-11e5-841b-dd1857958e62.png)

Why?

- Keep the common pattern on the dashboard when search icon is on the left.
- Gives more air to the list so it gets less noisy
- Removes borders within borders on the search module, so it becomes more lightweight.
- Adds the metadata that I was asking for. User (only if MU) - this is the only case you can have 2 datasets with the same name, and modified date, it helps you to differentiate when you don't remember the exact name.
- Adapted the icons so they work in small formats (we could still improve there)
