### ISSUE TITLE
After stoping syncing a dataset the view is refreshed but the type of columns cannot be changed

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#3820]

**Comment by alonsogarciapablo** [comment]
@saleiva, I tried this and I was actually able to edit the type of columns:

![synced](https://cloud.githubusercontent.com/assets/390398/8058722/99c70084-0ebb-11e5-84a8-14953ba34adf.gif)

Can you provide some steps to reproduce it? Thanks!

**Comment by saleiva** [comment]
I cannot reproduce this neither. Closing! :)

**Comment by alonsogarciapablo** [comment]
self healing issues FTW! Thanks!
