### ISSUE TITLE
No data available on hover being shown even with everything disable in the hover infowindow

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#3823]
https://team.cartodb.com/u/saleiva/viz/ff2dddfa-03bf-11e5-a4d8-0e43f3deba5a/public_map

**Comment by saleiva** [comment]
The layer with the white points doesn't have any infowindow.
If this is happening broadly I think we should hotfix this

**Comment by saleiva** [comment]
Any ideas on this? @javisantana @alonsogarciapablo

**Comment by alonsogarciapablo** [comment]
It should be fixed by [this](https://github.com/CartoDB/cartodb.js/pull/486). We still have to release it.

**Comment by alonsogarciapablo** [comment]
Released and working :+1:
