### ISSUE TITLE
Mailchimp decorator doesn't apply the styles on the category and it should

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#3826]
Right now the wizard seems broken after connecting mailchimp data.

**Comment by javisantana** [comment]
mailchimp basically does not create a category wizard, it just sets custom cartocss so this ticket is actually two:

- a new feature: make mailchimp connector to create a category wizard for the layer. This is a backend tasks but @alonsogarciapablo will take care
- a bug: sometimes the wizards appear empty. This is a frontend bug and it's totally unrelated to mailchimp

**Comment by alonsogarciapablo** [comment]
@saleiva FYI: I just released this :+1:
