### ISSUE TITLE
New map editor modals (Geolocalize column)

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#3828]
I made this for geolocalize column:
![1](https://cloud.githubusercontent.com/assets/596509/7849709/a501180a-04d8-11e5-8fe4-c2223f5f3b2e.png)

![2](https://cloud.githubusercontent.com/assets/596509/7849711/a9f8342e-04d8-11e5-9fb9-504d79b8b88a.png)

![3](https://cloud.githubusercontent.com/assets/596509/7849713/ad770f4e-04d8-11e5-9feb-1b838642d6ea.png)

Maybe in the one that cost money, we could add a confirm step before the function.
(quick mockup)

![4](https://cloud.githubusercontent.com/assets/596509/7849727/dec2b6d4-04d8-11e5-96df-483630966116.png)

**Comment by josecruz** [comment]
Updated centering elements and changing labels to the top of the dropdown. 
![2](https://cloud.githubusercontent.com/assets/596509/7857466/d7a364d6-0530-11e5-9c29-ad8df48aa2b0.png)
![2 copy](https://cloud.githubusercontent.com/assets/596509/7857469/d9d4423e-0530-11e5-8fb3-239592713eed.png)
![3](https://cloud.githubusercontent.com/assets/596509/7857471/db6e4306-0530-11e5-8ab6-88bcae52c661.png)

**Comment by saleiva** [comment]
Still visual design is weak IMO.

**Comment by josecruz** [comment]
Okay, I made this. Maybe we could add color to the icons

![2](https://cloud.githubusercontent.com/assets/596509/7865075/7908e8d4-0566-11e5-976b-b7cf63654097.png)
![2 copy](https://cloud.githubusercontent.com/assets/596509/7865079/7b79fdba-0566-11e5-886a-1f969eb813ca.png)
![3](https://cloud.githubusercontent.com/assets/596509/7865080/7b928fb0-0566-11e5-9393-f88db7bc5645.png)

**Comment by josecruz** [comment]
More consistent version :P 

![lonlat columns](https://cloud.githubusercontent.com/assets/596509/7913523/e7780220-0870-11e5-9380-908fdeedd271.png)
![bycitynames](https://cloud.githubusercontent.com/assets/596509/7913525/ee360c06-0870-11e5-9497-aa4b2756ee07.png)
![dropdown](https://cloud.githubusercontent.com/assets/596509/7913527/f0f1dfce-0870-11e5-89ae-4658284fd582.png)
![streetaddresses](https://cloud.githubusercontent.com/assets/596509/7913531/fafd0cfa-0870-11e5-83a7-72bed66df28f.png)
![select](https://cloud.githubusercontent.com/assets/596509/7913534/fee27ef4-0870-11e5-8673-f8aad5805a34.png)

**Comment by saleiva** [comment]
Not liking the forms.
@carlostallon could you have a quick chat with @josecruz?

**Comment by carlostallon** [comment]
Sure

**Comment by josecruz** [comment]
Some changes adjusting it to the grid (thanks to @carlostallon for the help!)

![bycitynames](https://cloud.githubusercontent.com/assets/596509/7934581/35ba44da-0929-11e5-8e14-5f2195351bac.png)
![select](https://cloud.githubusercontent.com/assets/596509/7934583/35bef32c-0929-11e5-97e8-633067c7f48d.png)
![streetaddresses copy](https://cloud.githubusercontent.com/assets/596509/7934607/7c768a14-0929-11e5-9e6a-1d0ee372f34e.png)

**Comment by xavijam** [comment]
I really like it and it follows the layout we have in the different modal views, so :+1:. But IMHO form is not following the same design we have in the other views.

New map/dataset form:

![screen shot 2015-06-02 at 19 10 46](https://cloud.githubusercontent.com/assets/132146/7949380/4fbf3a0c-095b-11e5-80b9-342112cef655.png)

Could we put questions in two lines avoiding that label size?

cc @viddo @saleiva

**Comment by josecruz** [comment]
New alignment and splitted labels 
![streetaddresses copy](https://cloud.githubusercontent.com/assets/596509/7966275/55773440-0a23-11e5-875d-28f402f83792.png)
![streetaddresses desplegado](https://cloud.githubusercontent.com/assets/596509/7966276/55856164-0a23-11e5-9d4f-cf4c09355544.png)

When you select the column on the first dropdown it would appear the *add an aditional column/text* (maybe we could consider another style for that button)

**Comment by carlostallon** [comment]
why not to put the "add layer" button in the right of the input, and I
agree with try with another style

2015-06-03 19:08 GMT+02:00 josecruz <notifications@github.com>:

> New alignment and splitted labels
> [image: streetaddresses copy]
> <https://cloud.githubusercontent.com/assets/596509/7966275/55773440-0a23-11e5-875d-28f402f83792.png>
> [image: streetaddresses desplegado]
> <https://cloud.githubusercontent.com/assets/596509/7966276/55856164-0a23-11e5-9d4f-cf4c09355544.png>
>
> When you select the column on the first dropdown it would appear the *add
> an aditional column/text* (maybe we could consider another style for that
> button)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/3828#issuecomment-108526323>.
>



-- 
Carlos Tallón
Designer & Baker

**Comment by saleiva** [comment]
Also think on https://github.com/CartoDB/cartodb/issues/3958

**Comment by xavijam** [comment]
Hey guys, it would be great if i can start with this, do you need anything from frontend feedback?

**Comment by xavijam** [comment]
If you need anything from frontend side, please let me know, i'll help you.

**Comment by xavijam** [comment]
Where is the sketch file @josecruz ?

**Comment by josecruz** [comment]
@xavijam I'll send you dropbox link via slack

**Comment by josecruz** [comment]
I modified the tabs:

![lonlat columns](https://cloud.githubusercontent.com/assets/596509/8191011/ed55cdbe-145d-11e5-9449-23f905c33c5e.png)
![streetaddresses copy](https://cloud.githubusercontent.com/assets/596509/8191012/ed7d1252-145d-11e5-955f-30a19bf5ea83.png)

I've tried to change everything up but i don't know what can I change on the forms to make them look less *soso* :(

**Comment by josecruz** [comment]
Hey guys!

I upload a better version with @saleiva's help. I modified the spaces between elements (28px) to fit styleguide recomendations.

![lonlat columns](https://cloud.githubusercontent.com/assets/596509/8221764/5da7bf8a-155a-11e5-9de7-d3f83bb83da2.png)
![postalcode](https://cloud.githubusercontent.com/assets/596509/8221765/5dacdd30-155a-11e5-80c9-1faf4d8f7908.png)
![select](https://cloud.githubusercontent.com/assets/596509/8221766/5db122c8-155a-11e5-813a-d37d00a321ea.png)
![streetaddresses_maxcost](https://cloud.githubusercontent.com/assets/596509/8221767/5db6013a-155a-11e5-8f92-5a5031d7c3ca.png)
![streetaddresses](https://cloud.githubusercontent.com/assets/596509/8221768/5dbd2ece-155a-11e5-842f-ca0f5a1fdd8d.png)
![error](https://cloud.githubusercontent.com/assets/596509/8221772/675c9f8c-155a-11e5-9f07-0ca6f8cb3a0f.png)

**Comment by saleiva** [comment]
Still not right...

**Comment by viddo** [comment]
Even if closed, I have an observation for the future: in the merge-datasets modal it's using the design that has a start view where a merge option is selected, and where the next header/content/footer changes slightly depending in what state/state the user is in.

This modal basically has a similar pattern, why are the options here displayed as a tab bar instead? Some options (e.g. city names) also have involve multiple steps just like the merge modal but this is not indicated in the header. Also the navigation to "go back" button is located in a different place (inline with the content, below the tab bar).

While I don't have a strong opinion on which one to use, I'd definitely prefer if we would be a bit more consistent across different contexts, it help both in terms of implementing the styles and the application code.
