### ISSUE TITLE
Improve data library updating

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#3832]
Right now user data library is updated in a monthly basis, but @iriberri says it's not enough, since they update metadata much more frequently. I propose:
- [ ] Clear `last_common_data_update_date` for all users when common data metadata changes (don't know whether we can automate this or provide a rake at least).
- [ ] Don't update if query returns an empty set (just in case there is a problem with common data metadata).

Agree? cc @saleiva @lbosque

**Comment by iriberri** [comment]
In the old dashboard it was immediate, but I know the process is totally different now. That was perfect :)
