### ISSUE TITLE
New map editor modals (Add column)

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#3836]
- How it works:
When you add a new column, it'll show the new column on the table with a 3-5sec color animation, from green to default. It'll let you write the coulmn name on the input and select column type from there.

![add new row](https://cloud.githubusercontent.com/assets/596509/7857542/674db794-0531-11e5-9e7e-247dc826ecc6.png)

**Comment by saleiva** [comment]
@xavijam assigning to you since you did originally this part :)

**Comment by javierarce** [comment]
I've been talking with @xavijam and we think that the design for this feature is very difficult to implement right now. We'd need to create a temporary column (which is by itself complicated to do) that would have to behave like an existing one (in terms of editing the cells, paginating, etc.). 

We could go for a less flashy solution (but don't get me wrong, I like the design): create a real column with a temporary name, change the column style to resemble the one in the mockup and open the dropdown. The default column type could be `string`. 

The downside of this approach is that there will be a page refresh. The upside, that is feasible :)

**Comment by saleiva** [comment]
Go for it dude :)
