### ISSUE TITLE
Deleting Column Uses More Space

### ISSUE THREAD

**Issue by mikegiddens** [CartoDB/cartodb#384]
I loaded in a simplified zipcode file and wanted to reduce the amount of storage space since I did not need a lot of the columns.  I deleted one string column and it went from 55MB to 65MB. WHAT! it got bigger.  I then deleted another column (30k rows each time) and it went from 65 to 64MB.  After deleting 6 columns of string data I am still at 63MB.  So somehow this seems to be eating up more space and is not good.

Part 2 - I used CDB to export as SHP file and then loaded it back into CDB and the total file size is 53MB. ~20 Characters per string column * 30k rows = ~500-600KB so removing 4-5 columns is = 3-4MB so that seems right.

**Comment by javisantana** [comment]
Did you execute a vacumm ?

**Comment by mikegiddens** [comment]
I did not run any SQL command this was only done via the GUI editor for removing columns.  This was a while ago and have not done any testing since then but I think it would be good to test to see if you guys can reproduce this.
