### ISSUE TITLE
New map editor modals (Edit Metadata)

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#3854]
Empty state:

![georeference by latlong 2 copy 2](https://cloud.githubusercontent.com/assets/596509/7879990/a7a7fe70-05f5-11e5-9b67-1de3cad416df.png)

Add metadata:
![georeference by latlong 2 copy 3](https://cloud.githubusercontent.com/assets/596509/7879993/aa25df8c-05f5-11e5-92a0-767c2a99e91c.png)

Duplicated metadata: 
![georeference by latlong 2 copy 4](https://cloud.githubusercontent.com/assets/596509/7879999/b6c18dd6-05f5-11e5-8106-28351842f0b1.png)

I made a green version as well (blue seems a bit monotone to me):

![georeference by latlong 2 copy 3](https://cloud.githubusercontent.com/assets/596509/7880004/d09df8e8-05f5-11e5-845d-2ca2542a3f57.png)
![georeference by latlong 2 copy 4](https://cloud.githubusercontent.com/assets/596509/7880005/d0a4b2be-05f5-11e5-9460-d310da72f07e.png)

**Comment by josecruz** [comment]
@saleiva any thoughts on this?

**Comment by josecruz** [comment]
Updated version with non-centered elements and tag-color change.

*Public* link will redirect to privacy modal.
Idea: when hover *markdown supported* we could place a tooltip with some hints.

![main](https://cloud.githubusercontent.com/assets/596509/7915617/10f0dc90-087f-11e5-83c6-fe66bdf93276.png)
![tags error](https://cloud.githubusercontent.com/assets/596509/7915618/10f2cc80-087f-11e5-8f9a-cbdd1f93a8d9.png)
![tags](https://cloud.githubusercontent.com/assets/596509/7915619/10fe2274-087f-11e5-83e8-82f2634427f3.png)

**Comment by saleiva** [comment]
Labels are too rounded. that style should be only for buttons.
Align of the ‘public’ label is weirdly aligned

**Comment by josecruz** [comment]
K.
Updated (and left aligned public label):
![main](https://cloud.githubusercontent.com/assets/596509/7917228/ed3672ce-0888-11e5-87bd-0c49c14d23b4.png)
![tags error](https://cloud.githubusercontent.com/assets/596509/7917229/ed3d1b10-0888-11e5-8ac8-51c8fbd4eeba.png)
![tags](https://cloud.githubusercontent.com/assets/596509/7917230/ed40ee66-0888-11e5-83a9-d09d6e75605f.png)

**Comment by saleiva** [comment]
Brown?
Nah

**Comment by josecruz** [comment]
Error color (way much better):
![tags error](https://cloud.githubusercontent.com/assets/596509/7917674/471f3746-088c-11e5-9f50-ede29b283b00.png)

**Comment by xavijam** [comment]
@josecruz @saleiva, I've check that this dialog is "similar" to this [one](https://github.com/CartoDB/cartodb/pull/3896). I wonder if we could set the same width for both forms (620px), only for unifying things.

**Comment by saleiva** [comment]
Sure

**Comment by xavijam** [comment]
Start with your templates info (at the bottom of the dialog) is something that we provide in the "Create map" dialog, but it is only available in the dashboard. Shouldn't we change it for other message/option?

**Comment by xavijam** [comment]
ping!

**Comment by xavijam** [comment]
Removed that text for the moment, if you want to take a look, it will be in RUI.

**Comment by xavijam** [comment]
Done in https://github.com/CartoDB/cartodb/issues/4002.
