### ISSUE TITLE
"Manage your seats" should be paged and searchable

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#3860]
Manage your seats organization page is unmanageable and slow with many users. It should be paged and searchable. Probably a page size ~50/100 can be enough.

- [X] Backend: @juanignaciosl
- [X] Backend: return number of users or pages in the new organization users api.
- [x] Frontend: @xavijam

**Comment by xavijam** [comment]
50 per page should be good. We will need pagination and search endpoints.

**Comment by xavijam** [comment]
50% of the ticket for you nacho and the other 50% for me :)

**Comment by xavijam** [comment]
@saleiva, should organization users search work as dashboard lists do?. It means, working with backbone, router urls, etc.

**Comment by saleiva** [comment]
I think in this case we can afford going with a simpler one, like the one we have on the user lists that @alonsogarciapablo  did.

**Comment by xavijam** [comment]
Not sure if we can use that, because what @alonsogarciapablo did was using a JS filter, didn't you?.
In fact I have to change that view for this 5k-org feature (https://github.com/CartoDB/cartodb/issues/3864).

**Comment by alonsogarciapablo** [comment]
@xavijam you're right. In the share dialog, we're [filtering users on the client](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/common/dialogs/change_privacy/share/share_model.js#L55-L65).

**Comment by xavijam** [comment]
Done in https://github.com/CartoDB/cartodb/issues/3888
