### ISSUE TITLE
"Dataset privacy settings" should be searchable?

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#3864]
Sharing modal is slow and unconfortable for that many users.

**Comment by javisantana** [comment]
the new modal has a search, it will be finished by this milestone. 

The problem here: despite the search is there the api still downloads data for all the users from the API

cc @viddo

**Comment by xavijam** [comment]
Done in https://github.com/CartoDB/cartodb/issues/3888
