### ISSUE TITLE
Different radio button styles

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#3868]
![screen shot 2015-05-29 at 15 52 05](https://cloud.githubusercontent.com/assets/132146/7883954/b2e0f808-061a-11e5-9c57-e8884b38ea8b.png)
![screen shot 2015-05-29 at 15 51 46](https://cloud.githubusercontent.com/assets/132146/7883955/b2f41276-061a-11e5-81b0-65b4b43d208b.png)

cc @saleiva @viddo

**Comment by xavijam** [comment]
Done in https://github.com/CartoDB/cartodb/pull/3896.
I've added a tooltip when we disable the date picker due to the fact that night value is selected. Looks ok @saleiva @viddo ?
![nasa-search](https://cloud.githubusercontent.com/assets/132146/8041565/20b7cbbc-0de7-11e5-9951-594504cde79b.gif)

**Comment by viddo** [comment]
:+1:

**Comment by xavijam** [comment]
Done in https://github.com/CartoDB/cartodb/issues/3896.
