### ISSUE TITLE
Longer PG Toster Delay

### ISSUE THREAD

**Issue by mikegiddens** [CartoDB/cartodb#387]
I am trying to change my date column to a date.

```
changing column type: PG::Error: 
ERROR: current transaction is aborted, 
commands ignored until end of transaction block
```
This error I think was flashed for about 1 sec which is a really short time to read this error and I had to throw the error a few times just to be able to copy/paste to see what it said.  I suggest that you increase the popup settimeout to at least 5 seconds.

As for the error it seems that when I loaded the CSV file it has NULL and did not get treated as null value and so the conversion does not work.  I have to update that field then do the convert to make it work but normal people might not know what to do.

**Comment by javisantana** [comment]
do you have a csv to reproduce the problem?

**Comment by mikegiddens** [comment]
This issue might be kinda solved.  If I create a new table and have a string column like "name" then enter for one row 2015-01-32 (this should fail but now just gets erased) and one as 2014-01-01 it will get converted correctly.  So in an older UI this was throwing an error and now it just erases the bad values so I think it is okay since you have the warning now.
