### ISSUE TITLE
Indexes are not dropped in sync tables

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#3876]
Reported in SB/5512478

Synced table: 25MB of size (after vacuum full) - 128 indexes -> checked in user db
Brand new table: 1MB - 5 indexes -> checked in user db (one of them is importer_X)

All repeated indexes in Synced table are of the form:

"importer_X_wkb_geometry_geom_idx" gist (the_geom)

              name              |          created_at
              ------------------+---------------------------
              new table         | 2015-06-01 12:45:28.845651+00
              old table         | 2015-05-27 03:45:49.755592+00

**Comment by iriberri** [comment]
cc @Kartones

**Comment by iriberri** [comment]
Update: All indexes from both tables have been removed. (15:30PM)

**Comment by iriberri** [comment]
Dropping the indexes made the 25MB table turn to 1MB

**Comment by Kartones** [comment]
And if the user now syncs the table, does it appear again? (to narrow the issue to "replicating indexes")

**Comment by iriberri** [comment]
Yes, it has been regenerated:

    "importer_ca7c0a4a086611e5b62c0e5e07bb5d8a_wkb_geometry_geom_idx" gist (the_geom)

**Comment by jsanz** [comment]
SB/ 5831712

I've tried this on my account and it's creating new indexes on `the_geom` field.

http://www.srh.noaa.gov/ridge2/Precip/qpehourlyshape/latest/last_72_hours.tar.gz

**Comment by jsanz** [comment]
I left the whole weekend my sinc table activated and it grew from 46MB table to 400MB and it has now 28 indexes on the geom field.

![](http://i.imgur.com/Z9J9YMN.png)

**Comment by iriberri** [comment]
I found a new example in which only 4 importer indexes were saved although the dataset is being synced hourly. I checked the logs for the sync and there are exactly the same traces in the import logs for which the index was being saved and for which wasn't.

**Comment by jsanz** [comment]
My synced dataset now has 44 indexes on the geom field and takes 580MB, I'm removing it from my account.

**Comment by rylincoln** [comment]
@iriberri Just to put a note here - if you were looking at my account the reason there were only 4 indexes was because I deleted the original table and then made a new one exactly the same source and name.    Cheers and thanks!

-Ry

**Comment by Kartones** [comment]
It must be inside https://github.com/CartoDB/cartodb-postgresql/blob/master/scripts-available/CDB_CartodbfyTable.sql#L342 because there's no other place where the indexes are created. Hunting why it doesn't detects properly, as if I run this in live (I have also a table with +1100 indexes) I get them so should be detected.

**Comment by Kartones** [comment]
Branch is `3876-no-self-replicating-indexes` (fix in progress, once live will work and "fix" automatically upon next table sync)

**Comment by Kartones** [comment]
Ok, fix is live and looking good (I had a table with the issue and is fixed now).

Just trigger a sync (or wait until next one), afterwards a `SELECT * FROM pg_indexes WHERE tablename='YOURTABLENAME' AND schemaname='YOURSCHEMA'` should show only 4 standard ones. For non-organization accounts `YOURSCHEMA` = `public`

**Comment by iriberri** [comment]
Users notified :-)
