### ISSUE TITLE
Extra tweets switch displayed in organizations without Twitter datasource

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#3878]
![screen shot 2015-06-01 at 16 02 48](https://cloud.githubusercontent.com/assets/932968/7914495/b2fc11f6-0877-11e5-9ed1-d56582ffd3a2.png)

In organizations without Twitter datasource "Extra tweets" switch is displayed at "new user" page, I think it shouldn't.

@xavijam please confirm this is not on purpose and I'll fix it.

**Comment by xavijam** [comment]
Not in purpose, fix it :)
