### ISSUE TITLE
User grouping

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#3905]
Organizations might need some kind of hierarchical user management.

@saleiva @javisantana @andrewxhill @xavijam

**Comment by saleiva** [comment]
Wouldn't focus on this at this time. Too much I think.

**Comment by juanignaciosl** [comment]
It's marked as `enhancement` and not assigned to a milestone because of that.

**Comment by jaimecartodb** [comment]
@saleiva @javisantana this is something more and more Gov clients are asking for. In Australia having groups inside an organization was a hard requirement for at least 3 clients ($50-$200K).

**Comment by ohasselblad** [comment]
jumping on thread to follow this issue

**Comment by juanignaciosl** [comment]
@ohasselblad: this is specified at [Groups wiki page](https://github.com/CartoDB/cartodb-management/wiki/Groups), where you can track the progress.
