### ISSUE TITLE
Query hangs when it should just fail

### ISSUE THREAD

**Issue by amandabee** [CartoDB/cartodb#391]
I ran this query from the table view for a different table (not 'us_states'):

`SELECT the_geom, iso, 0 as damage FROM us_states WHERE the_geom IS NOT NULL` 

there's no 'iso' column in 'us_states'. I was actually looking for the error so I could show a student how to read the error and see what the problem is.  I expected an error like `column "iso" does not exist` but instead I got "Loading Results ..." that hummed along until I got bored and went back to my dash. When I go back from the dash to the table again, I see that there's a problem with the query and the error is shown when I open the SQL pane. 

If I run the query while I'm looking at the 'us_states' table, the error turns up fine. But if I run it from any other table, I have to go back to the dash and then re-enter the table view to see the error. 

Low priority, but buggy nonetheless.

**Comment by saleiva** [comment]
I could not replicate. Closing.

Thanks!
