### ISSUE TITLE
URL on API CALL modal and exports doesn't work on public dataset pages 

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#3913]
(maybe an issue with orgs, but an important one)

On
https://inbo.cartodb.com/u/lifewatch/tables/bird_tracking_devices/public
(Also export buttons doesn't work)

This is the one that we suggest: 
http://inbo.cartodb.com/api/v2/sql?q=SELECT%20*%20FROM%20lifewatch.bird_tracking_devices

This is the correct one:
http://lifewatch.cartodb.com/api/v2/sql?q=SELECT%20*%20FROM%20bird_tracking_devices

**Comment by xavijam** [comment]
Uncaught Error: TrackJS Caught: Cannot read property 'email' of undefined
cc @viddo
