### ISSUE TITLE
Instagram connector fails in endpoint 1_1

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#3917]
(Team org, the following flags enabled):

* "active_record_asset_endpoint"
*  "active_record_geocoding_endpoint"
* **"active_record_imports_service_endpoint"**
* "active_record_synchronization_endpoint"
*  "active_record_table_vis_endpoint"

![image](https://cloud.githubusercontent.com/assets/1730320/7969432/d2454fd0-0a04-11e5-90d9-9547edfc7459.png)
![image](https://cloud.githubusercontent.com/assets/1730320/7969441/db823ac2-0a04-11e5-9c73-db7bf5a9bfdc.png)

====
![image](https://cloud.githubusercontent.com/assets/1730320/7969444/e0258f84-0a04-11e5-97e5-155df32b7ed6.png)

My OAuth tokens table is empty:

 type | client_application_id_old | token | secret | callback_url | verifier | scope | authorized_at | invalidated_at | valid_to | created_at | updated_at | id | user_id | client_application_id
------+---------------------------+-------+--------+--------------+----------+-------+---------------+----------------+----------+------------+------------+----+---------+-----------------------
(0 rows)

@juanignaciosl

**Comment by juanignaciosl** [comment]
Does it work without active_record_imports_service_endpoint flag enabled?

**Comment by iriberri** [comment]
Yes! Just checked.
