### ISSUE TITLE
shp file importing with no geometry

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#3919]
- get this file https://s3.amazonaws.com/metro-extracts.mapzen.com/madrid_spain.osm2pgsql-shapefiles.zip
- uncompress it and get the line files compressed in a single file
- import it in cartodb

You get no rows

**Comment by Kartones** [comment]
Reason of the empty import. All individual rows end up failing at ogr2ogr due to encoding errors:
```
2015-06-29 07:16:35 UTC: ogr2ogr output:    ERROR 1: COPY statement failed.
ERROR:  character with byte sequence 0x81 in encoding "WIN1252" has no equivalent in encoding "UTF8"
```

**Comment by Kartones** [comment]
Opening with QGIS and saving as with UTF-8 encoding works as expected:

![image](https://cloud.githubusercontent.com/assets/2085449/8403422/cee9aa08-1e44-11e5-8b01-5c453b63a90c.png)
