### ISSUE TITLE
Using HTTPS some HTTP calls are still made that will block the browsing if HTTP is not available

### ISSUE THREAD

**Issue by azamorano** [CartoDB/cartodb#3927]
In a cartodb installation that only exposes HTTPS interface to the world some requests are still made through HTTP when they shouldn't.

Two points of failure have been identified, but there can be more.

* When you connect to: https://\<yourusername\>.cartodb.com
There is a request to http://\<yourusername\>.cartodb.com that responds with a 302 to https://\<yourusername\>.cartodb.com/dashboard or login.

* If you go to https://\<orgadmin\>.cartodb.com/u/\<orgadmin\>/organization you end up in http://\<orgadmin\>.cartodb.com/u/\<orgadmin\>/organization
<hr>
Branch `3927-check-all-ssl-required` ([PR](https://github.com/CartoDB/cartodb/pull/4011))

**Comment by javisantana** [comment]
cc @Kartones @juanignaciosl The redirection is done server side

**Comment by Kartones** [comment]
Uhm, this is going to be a fun one, as @rafatower has struggled with "the login redirection logic" before (I recall discussing with him how to proceed).

Will take a look although if I have to setup https etc. on my local might slip out of this sprint

**Comment by azamorano** [comment]
Let me know if I can help with the setup of the environment to reproduce it.

**Comment by Kartones** [comment]
Thanks, but I already moved it to next sprint as we're having issues with one ticket and it will definetly not be ready for today. But I'll ask for help for the https setup, thanks!

**Comment by rafatower** [comment]
One of the issues is that at least our current version of rails can specify an `https_required: true` but routes generation does a first request to http then a redirect to https.
