### ISSUE TITLE
Add blue circle button to the over on the cards

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#3942]
As an experiment and and aux item for the templates. Same action than clicking on the title.

![screen shot 2015-06-05 at 16 41 21](https://cloud.githubusercontent.com/assets/132149/8014812/c8b4504e-0ba1-11e5-9756-be4158de8312.png)

**Comment by javierarce** [comment]
I added the button in the dashboard, but I'm not sure about adding it to the modal that appears when removing a dataset. What do you think?

**Comment by saleiva** [comment]
Nope, I'd not add it there. This indicates that by clicking you can edit so...
