### ISSUE TITLE
torque steps calculation is wrong

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#3951]
- create a table with two points
- create a torque wizard (time: cartodb_id)
- you will see the time slider has 2 steps (ok)
- change marker-fill using the wizard

the time slider changes to 512 steps when it should remain with 2

**Comment by fdansv** [comment]
I'm unable to replicate this. As far as I can see there's no variation in the number of steps when changing marker-fill. 

I mean I've seen the timeslider play with the default number of steps before. Doesn't this happen while waiting for the tiler to respond?

**Comment by javisantana** [comment]
I just reproduced it following those steps
