### ISSUE TITLE
Offer an easy way to get last hour(s) tweets in the twitter connector

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#3952]
Like: Gimme last 10 hours

**Comment by saleiva** [comment]
![screen shot 2015-06-08 at 17 54 13](https://cloud.githubusercontent.com/assets/132149/8046252/6636e068-0e07-11e5-9903-4c44ff747309.png)

Also, my proposal is that we change the annotation and we calculate the GMT difference with the time of the browser.

cc @javisantana

**Comment by javisantana** [comment]
the GMT difference is when you do not use the "last 4 hours", right?

**Comment by xavijam** [comment]
We have a problem with the height of the date range component.

![screen shot 2015-08-04 at 18 26 55](https://cloud.githubusercontent.com/assets/132146/9066194/6ea44758-3ad6-11e5-9b44-c738bdc58fb3.png)

@saleiva
