### ISSUE TITLE
Edit message error for dataset too big

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#3956]
![image](https://cloud.githubusercontent.com/assets/1730320/8025735/b1a6ab2a-0d2e-11e5-9d64-353e6e958595.png)

**Comment by saleiva** [comment]
@iriberri adding a milestone, so you can focus :)

**Comment by iriberri** [comment]
:+1:

**Comment by asiletto** [comment]
subscribing, I got the same error importing a 200Mb geojson file

**Comment by iriberri** [comment]
Hi @asiletto, this issue was not really about the import error itself but for editing the text on it. Free accounts have a maximum file size limit of 150MB, so your case could be because of that. If you are working in a bigger account, feel free to contact support@cartodb.com so that the CartoDB team can check if your account config is okay.
