### ISSUE TITLE
Respect columns order in data view

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#3957]
It is being rendering like:
cartodb_id, the_geom, [rest of columns in alphabetical order], updated_at, created_at
And it should respect database order in the middle.

**Comment by viddo** [comment]
This reminded me of an issue I did a while ago, #2638, where the wanted behavior was to order alphabetically… issue #2638 / PR #2825

**Comment by saleiva** [comment]
Yeah, this is tricky. Not sure what the best solution is as alphabetically helps for looking in tables with lots of tables

**Comment by rms-mquinlan** [comment]
Could we have a toggle option in data view to respect the uploaded column ordering OR view in alphabetical order? I don't see why it has to be fixed as the one view. Alphabetical order makes it especially hard to sanity check data where you want to columns co-located. e.g. 'start_date' and 'end_date'.

Ideally custom ordering of columns in the data-view should be the goal.

**Comment by xavijam** [comment]
Already achieved in the builder, so closing :).

**Comment by allthesignals** [comment]
@xavijam how can we test this in Builder? Thanks!
