### ISSUE TITLE
Improve 2nd time georeferenciation when some rows doesn't get georef correctly

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#3958]
edit: TBD, after discussion below and in-person, /@viddo

- Backend
  - [x] update geocodings to accept a boolean param (`force_all_rows`) to redo geocodings for all rows
  - [x] update `/table` API to accept the `force_all_rows` param on PUT (when `latitude_column` and `longitude_column` are present I guess) - NOT NEEDED
  - [x] change to geocode all null or false (as opposed to just null as it is done right now)
  - [x] update `/geocodings/estimation` endpoint 
    - to take into account the change for null/false values above
    - to accept `force_all_rows` param, since it will affect estimated cost
- Frontend:
  - [x] add checkbox in footer of georeference modal, to toggle `force_all_rows` param (+ the regular state handling etc.)
  - [x] send `force_all_rows` param to `/geocoding/estimation` API to get accurate estimation cost/rows
  - [x] refactor [`table.geocodeLatAndLng `](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/models/table.js#L667-L693) to send `force_all_rows` param

---

Screenshot for the UI change:
![2nd try](https://cloud.githubusercontent.com/assets/132149/8354381/f781e598-1b47-11e5-8f3e-87d7762604e2.png)

**Comment by saleiva** [comment]
Maybe a check saying "Retry all columns with no geometry" or something like that which would georeference georef_status = false && those that are null

**Comment by saleiva** [comment]
Please note that small checkbox on the bottom left that will appear only when having some rows already geocoded.

![2nd try](https://cloud.githubusercontent.com/assets/132149/8354381/f781e598-1b47-11e5-8f3e-87d7762604e2.png)

**Comment by viddo** [comment]
@rafatower is it possible to override values? Looking at the docs/code I could not see any param for doing such thing

**Comment by viddo** [comment]
@saleiva Should it appear for all tabs/geocoding kinds? Or only lon/lat?

**Comment by saleiva** [comment]
all

**Comment by rafatower** [comment]
@viddo what values do you need to override?

**Comment by viddo** [comment]
As it says in the screenshot, "_Override all values, this will geocode all your rows, even those  with geometry data._", but @saleiva can probably clarify what is the expected/desired behavior.

**Comment by rafatower** [comment]
Clarified to me. Currently this is how georef_status is used:
- true -> the row could be geocoded
- false -> there was a miss trying to locate the row
- null -> either not processed yet or failure

What's expected from this ticket:
- geocode all null or false (as opposed to just null as it is done right now)
- if the check box is marked, wipe out the georef_status and start all over the table.

There's a dirty hack without BE changes: use the sql api to reset the values before georeferencing

But I guess we'll go through the BE changes way

**Comment by viddo** [comment]
IMHO, we already have too many hacks in the frontend, it's better to try to do things the proper way unless there is a very good motivation for not to. 

So I'd say the tasks are:
- [ ] BE: change to _geocode all null or false (as opposed to just null as it is done right now)_
- [ ] BE: provide a boolean param to redo geocodings for all rows
- [ ] FE: add checkbox to set the boolean param for user

sounds reasonable?

If we agree on a param name I can implement the UI for now, and the backend could be done separately. 

In terms of timeline I understand that this is prio for this milestone(?), so in that case it should be prioritized over something else. I could take care of the BE side too with a little help perhaps maybe, if you don't have time.

**Comment by rafatower** [comment]
> BE: change to geocode all null or false (as opposed to just null as it is done right now)

ok with it

> BE: provide a boolean param to redo geocodings for all rows

fine by me. `force_all_rows`?

@Kartones do you see any problem with it? (just double-checking with you)

**Comment by Kartones** [comment]
Point 2 (forcing) really fine by me.

Point 1, if I remember correctly how geocoder works (I have almost not touched it), a false means "I didn't found any match", so if I geocode with a $$$ geocoder do I get charged of all rows sent? because then if I send again the same rows and only 4 out of 1k  were geocoded, the other 996 would be sent (and charged) again, no?

If I'm wrong then perfect/go ahead

**Comment by viddo** [comment]
Regarding point 1 then, it means that this new feature could have some negative implications… basically, for the street addr. we would need to also re-estimate the costs taking this param into account and present the new information clearly. So I guess that this expands the scope to also fix the estimation endpoint, right?

**Comment by rafatower** [comment]
right

**Comment by viddo** [comment]
I know @saleiva wants this badly, but considering this is a new feature that came up in the middle of the sprint and it obviously have these issues discussed above, I don't think it's reasonable to expect it to be finished in time for this milestone (with only two days left). 

IMHO, I'd say we schedule it for next milestone and don't rush and break things. 

Btw, I'm fine with the param name suggested above btw, updated the issue desc with the tasks and this info.

**Comment by saleiva** [comment]
Hi guys, is the 3rd time we discuss this. This is important, so I'd feel very happy if you go for it. Please

**Comment by viddo** [comment]
Frontend in [3958-force-all-rows-geocode-frontend](https://github.com/CartoDB/cartodb/tree/3958-force-all-rows-geocode-frontend) for now

**Comment by rafatower** [comment]
For BE part I think it is easier to tackle phase 1 & 2 at once.

**Comment by rafatower** [comment]
The `LatitudeLongitude` always operates on all rows, which for me makes all the sense, therefore removing the need of passing the param `force_all_rows`. Let me know if anyone disagrees.

**Comment by rafatower** [comment]
@viddo let's setup a meeting to discuss how to proceed. After diving into BE changes, I think it is easier to do it in one shot. Nevertheless I appreciate having this split into manageable tasks.

**Comment by viddo** [comment]
Fine by me! I split up because at that point I wrote the list it seemed like the most reasonable step (mostly due to not knowing if we needed to do any UX changes). The frontend changes were also done in one go. Ping me to talk and let's finish this one off then.
