### ISSUE TITLE
Make torque slider depending on the Timezone of the user

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#3971]

**Comment by saleiva** [comment]
Hey @javisantana there have been a few requests about this. Could we make the Torque bar time to show the time according to the timezone of the user? We would need to add the timezone information to the UI when entering date fields, right?

Are we forcing GMT 0 to all dates in the backend?

S.

**Comment by javisantana** [comment]
AFAIK we show the date according to the user timezone (Date object does that). I tested it and

```
new Date(0)
Thu Jan 01 1970 01:00:00 GMT+0100 (CET)
// I changed there the timezone in my laptop
new Date(0)
Wed Dec 31 1969 19:00:00 GMT-0500 (EST)
```

**Comment by saleiva** [comment]
So then this is easier! We just not need to do anything.
@miguelarias ?

**Comment by miguelarias** [comment]
That is awesome!, then no need on that end. Only the usability issue while
calculating time-zones, maybe that was an old request by Twitter then!.


*Miguel Arias*@mike_arias

COO

*CartoDB*143 ROEBLING STREET
SECOND FLOOR
BROOKLYN NY 11211

+1 917 463 3232

*Mob US: +1 3478240358*
*Mob SP: +34 607654697*
*marias@cartodb.com <marias@cartodb.com>*

www.cartodb.com
Live webinars to learn CartoDB - Register here
<http://cartodb.com/webinars/>.
