### ISSUE TITLE
Improve torque bar 

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#3972]
I've been playing around with this two versions (nothing serious yet, just mockups)

![ti de li to le ii copy 18](https://cloud.githubusercontent.com/assets/596509/8040699/c32a7450-0e12-11e5-8cdd-f0fb9ca2fcb8.png)
![ti de li to le ii copy 19](https://cloud.githubusercontent.com/assets/596509/8040702/c915fb14-0e12-11e5-90c6-033fd6237f98.png)

Doc: https://github.com/CartoDB/cartodb-management/wiki/Embeds-revamp

**Comment by saleiva** [comment]
Like the 2nd one a log.. Can you try with the barchart with gaps?

**Comment by saleiva** [comment]
Also vertical alignement needs some fixes though...

**Comment by saleiva** [comment]
Also looks like the components on the map were moved up...

**Comment by fdansv** [comment]
Wow this is top, looking forward to implementing it :)

**Comment by josecruz** [comment]
@saleiva @fdansv thanks guys! and oops, fail... yes, I had to increase the white background 20px and move the elements. I'll finish it tomorrow :+1: 

_Do you think that would be interesting to mark those bars that have passed already?_
Yup, maybe with a darker grey.

**Comment by javisantana** [comment]
test also with some edge cases like when there is only few steps (3, 4) or too many (2048 is the max). Also take into account the graph needs time to load the data. 

Another questions: does the graph show the global activity or the activity of the area currently watching?

**Comment by saleiva** [comment]
For the time being, global activity

**Comment by josecruz** [comment]
@javisantana Okay! 

It shows the global activity

**Comment by josecruz** [comment]
After trying different versions with color variaton, I think that we could variate color depending on the basemap. If it's dark, white bar chart. If not, black.

(I had to move and increase size of some elements)

![ti de le li copy 2](https://cloud.githubusercontent.com/assets/596509/8058522/50e5a7ae-0eba-11e5-807e-9b4e99648602.png)
![mobile](https://cloud.githubusercontent.com/assets/596509/8058550/775b8502-0eba-11e5-86ca-b15e35569651.png)

full frame:
![torque legend](https://cloud.githubusercontent.com/assets/596509/8058554/8022d7d0-0eba-11e5-9001-f88a5bb0abbe.png)

Gaps:
![ti de li to le ii copy 20](https://cloud.githubusercontent.com/assets/596509/8058595/c11e7992-0eba-11e5-8bd5-c1469b4976bd.png)

We can't fit 2048 bars there :( any idea?

**Comment by javisantana** [comment]
global activity could kill the performance since it needs to fetch the 0,0,0 tile so I'd think about how to avoid that in some cases

**Comment by fdansv** [comment]
Why not display local activity? It'd be cool to have that graph change with viewport changes.

**Comment by fdansv** [comment]
Re 2048 bars what's the maximum number of bars that you can display? From some value onwards we'll have to aggregate them.

**Comment by saleiva** [comment]
We are not doing anything contextual yet so better to show global activity until we swicth all components

**Comment by josecruz** [comment]
@fdansv It depends on the map size, but on those designs: 101 desktop. 60 mobile.

**Comment by josecruz** [comment]
I aligned some things:
![screen shot 2015-06-10 at 19 36 07](https://cloud.githubusercontent.com/assets/596509/8089491/7c7c942e-0fa8-11e5-9980-19d882f125a9.png)

![ti de li to le ii copy 21](https://cloud.githubusercontent.com/assets/596509/8089543/cc153180-0fa8-11e5-8c99-6456f0dd0a0c.png)

I've tried a variation as well (with less visual noise)
![ti de li to le ii copy 19](https://cloud.githubusercontent.com/assets/596509/8089632/5173740e-0fa9-11e5-8390-6c3207c0e258.png)

**Comment by saleiva** [comment]
I prefer the bars, but still don't like the weight unbalance on the vertical alignement...

**Comment by josecruz** [comment]
Updated version by: @saleiva 
![desktop-620 ti de li to le ii](https://cloud.githubusercontent.com/assets/596509/8159124/b4a06c16-135b-11e5-8181-0d5ea4d9a352.png)

I would paint the passed ones blue

**Comment by saleiva** [comment]
cc @andrewxhill

**Comment by andrewxhill** [comment]
whhhhhaaaaat? deployed?

**Comment by saleiva** [comment]
no no, part of the new embed :)
