### ISSUE TITLE
Visualize modal opens Share modal too

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#3973]
Steps:

* Go to your tables dashboard, open a table
* Click on visualize
* The warning for creating a new map shows, when you accept, it sends you to the map but it opens the "share" modal automatically

cc @xavijam @viddo

**Comment by iriberri** [comment]
After talking with @xavijam, not sure if this is a new expected behaviour. @saleiva?

**Comment by saleiva** [comment]
Yep, after testing this I'd not open that modal automatically...
