### ISSUE TITLE
Discrepancy in number of max tables in postgres

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#3975]
I was checking this file https://github.com/CartoDB/cartodb/blob/dc3cbba77d26c0acbcf5d70476199df76aaa5d55/services/importer/lib/importer/loader.rb#L240 and found things like:

```
raise TooManyColumnsError.new(job.logger) if ogr2ogr.command_output =~ /tables can have at most 1600 columns/
```

This explained error (and others) isn't being raised appropriately because Postgres [has a lower limit](http://www.postgresql.org/about/) which seems to depend on column type:

`Maximum Columns per Table    250 - 1600 depending on column types``

Also, the error is being raised by Postgres and not by ogr2ogr, so as we're using `ogr2ogr.command_output` we're not seeing some errors that are being caused after the ogr2ogr processing part.

@Kartones suggested that this may be caused by us using an old Postgres driver 

@pramsey any tricks? :-)

cc @javisantana

=====

PS:
Another example is for example the `DuplicatedColumnError`: when we detect columns with repeated names we rename them, but the following use case fails:
  * User has long column names, which are detected as different
  * We trim the column names 
  * In some cases, the beginning of the names are equal, so we're creating in our end columns with the same name. This import fails but the DuplicatedColumnError is not show.

**Comment by pramsey** [comment]
I think it really might be 1600…

https://github.com/postgres/postgres/blob/master/src/include/access/htup_details.h#L47

**Comment by iriberri** [comment]
Actually forgot to copy something important: the import log from a test:

2015-06-08 18:56:09 UTC: Disabling autovacuum for "cdb_importer"."importer_0221ef4c0e1011e5bebf0e8dde98a187"
2015-06-08 18:56:09 UTC: Errored importing data from /tmp/imports/20150608-15131-13gw6hr/carla.csv:
2015-06-08 18:56:09 UTC: RangeError: more than 256 columns in query
2015-06-08 18:56:09 UTC: --------------------------------------------

**Comment by Kartones** [comment]
I see strange that if the limit is variable we hit exactly at 256 when you used simple columns (string? empty values right?). 

I raised the number in the past, I think that when we updated to PG 9.3, so I'm starting to "bet" that the issue is either our old Rails 3, or PostgreSQL Ruby gem or the ORM.

We use the following gem versions:
```
gem 'pg',                      '0.13.2'
gem 'sequel',                  '3.42.0'
gem 'sequel_pg',               '1.6.3'
```

Current versions are:
```
pg: 0.18.2 
sequel: 4.23.0 
sequel_pg: 1.6.11
```

Aaaand a quick GH search on sequel_pg displays [this interesting changelog entry](https://github.com/jeremyevans/sequel_pg/blob/79c768d9508c55f55db3f20331b9631b85ff97f0/CHANGELOG#L19):
`* Allow overriding maximum allowed columns in a result set via -- --with-cflags=\"-DSPG_MAX_FIELDS=1600\" (jeremyevans) (#12)
`

**Comment by Kartones** [comment]
Yes, is limited right now to 256 [by default](https://github.com/jeremyevans/sequel_pg/blob/79c768d9508c55f55db3f20331b9631b85ff97f0/ext/sequel_pg/sequel_pg.c#L16):
```
#ifndef SPG_MAX_FIELDS
#define SPG_MAX_FIELDS 256
#endif
```

**Comment by iriberri** [comment]
related: https://github.com/CartoDB/cartodb/issues/6251

**Comment by iriberri** [comment]
I'm going to edit the import error messages we're throwing and documenting.

**Comment by iriberri** [comment]
cdb
