### ISSUE TITLE
Organization twitter enabled setting not taking precedence over user one

### ISSUE THREAD

**Issue by Kartones** [CartoDB/cartodb#3984]
## Description

Organizations have their twitter flag setting. If it is on, it should take precedence over the organization user specific value, so the whole organization can use twitter not needing to set it up for each member.

## How to reproduce

Being inside an organization, have twitter activated for it, USER A with twitter not activated and USER B with twitter activated.

## Expected results

Both USER A and USER B should be able to import tweets

## Current results

USER A's import fails and the log shows `Service disabled @ twitter_search User: xxxx`, while USER B import works.

So my guess is that on the refactor this "value override" has been lost somehow (haven't checked the code, is just blind guessing)

**Comment by juanignaciosl** [comment]
[Previously it was handled `before_save`](https://github.com/CartoDB/cartodb/blob/master/app/models/user.rb#L133). I think it's better getting it either from the organization or from the user himself on the fly when you evaluate whether datasource is enabled.

**Comment by juanignaciosl** [comment]
Unless @saleiva or @Kartones think different, I will change the current behaviour making user Twitter datasource switch be "on sync" with their organization (if org has it, user has it as well).

**Comment by saleiva** [comment]
sounds good to me

**Comment by Kartones** [comment]
Yes please, probably was done to allow fine-grain control (like allowing only to certain users) but so far orgs are not in need of so much control and it is giving problems instead... so go ahead!
