### ISSUE TITLE
Start by points, polygons,.. dialog is appearing in all my maps when I visit them

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#3985]
No matter if they have or not geometry, is it on purpose @javierarce?

In this map, there are two layers with geometry info, you can distinguish them in the background.

![screen shot 2015-06-09 at 14 30 48](https://cloud.githubusercontent.com/assets/132146/8066263/b0ce0694-0eb4-11e5-9a9b-937cc710873c.png)

**Comment by javierarce** [comment]
Damn. Maybe it was the last change I did. I'll release a hotfix.

**Comment by xavijam** [comment]
Leave it for tomorrow, 'new_modals' aren't enabled for everybody so it is ok.

**Comment by javierarce** [comment]
I prefer to release it now. I feel bad, I should have spotted the problem.

**Comment by xavijam** [comment]
up to you
