### ISSUE TITLE
Oembed call doesn't wrap response (JSONP)

### ISSUE THREAD

**Issue by dersteppenwolf** [CartoDB/cartodb#3987]
For JSONP, Oembed service should wrap function around the JSON object.  

Example from wordpress: 
https://public-api.wordpress.com/rest/v1/sites/wtmpeachtest.wordpress.com/posts?callback=jsonp_callback

Related: 
http://stackoverflow.com/questions/26262235/jsonp-returning-uncaught-syntaxerror-unexpected-token-angularjs-routingnu

Example angular app calling Cartodb's oembed service :
http://jsfiddle.net/c0hgye4g/2/

**Comment by rafatower** [comment]
My commit referenced an issue of another repo (sorry), this one should be fixed so closing it
