### ISSUE TITLE
Liked maps are not displayed as liked in embeds

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#3988]
**Steps to reproduce:**

- "Like" one of your maps in your dashboard.
- Go to the embed_map page for that map.

**Expected behaviour:**
- You should see something like:
![screen shot 2015-06-10 at 11 15 28](https://cloud.githubusercontent.com/assets/390398/8079007/14e283f0-0f62-11e5-9e3e-f6e0ce36f017.png)
- If you click the heart, it should unlike the map.

**Current behaviour:**
-  Number of likes is right, but heart is not red.
![screen shot 2015-06-10 at 11 17 33](https://cloud.githubusercontent.com/assets/390398/8079029/57116eb2-0f62-11e5-8463-ce3fd49f8e0e.png)
- If you click the heart again, request returns a 400 and nothing happens.

**Comment by alonsogarciapablo** [comment]
I investigated this a bit more. The problem is that we would need to fetch the information about the visualization in order to know if the embed has been liked by the logged in user. This is easy to do but it would increase the load of our backends, especially for very popular embeds.

**Comment by Kartones** [comment]
yeps, IIRC we decided to let this stay this way (not checking/reflecting current user's liked status) to not do an extra request on every embed.

**Comment by alonsogarciapablo** [comment]
Thanks for your clarification @Kartones!
