### ISSUE TITLE
Layer toggle not working properly in IE 9 

### ISSUE THREAD

**Issue by Hayleyr** [CartoDB/cartodb#3995]
on this page http://builds.dogstaging.com/scottishparliament/ 

after using the toggle layer function evidently the constituencies layer (.sublayer(0)) only loads the legend, the rest of the layer fails to load. 

this is only occurring in IE9, it "works great" in other browsers.

**Comment by xavijam** [comment]
Duplicated -> https://github.com/CartoDB/cartodb/issues/3996
