### ISSUE TITLE
Proper params for geocoding formatter

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#4010]
We should change the internal API definition of the params for geocoding so that we avoid unneeded parsing, transformations and **guessing** in both front and back ends.

There are limitations in the format of the `formatter` itself because it is impossible to tell apart what is what from the order of the "atoms" of the formatter string (street, state/province, country, additional information) despite the user is providing that information explicitly.

Proposal:
```json
{
  "input": {
    "address": {
      "type": "column",
      "value": "direccion"
    },
    "province": {
      "type": "column",
      "value": "provincia"
    },
    "state": {
      "type": "freetext",
      "value": "es"
    },
    "additional": null
  }
}
```
(we can keep the current formatter for backwards compatibility)

cc/ @javisantana

**Comment by javisantana** [comment]
is this blocker for gmaps geocoding or is a good to have?

**Comment by rafatower** [comment]
No, it is not. It will improve accuracy.

**Comment by rafatower** [comment]
Let's remove it from the next sprint and revisit later. I realized it would require more effort on both street-level geocoders to make a difference, apart from passing/transforming parameters.

**Comment by rafatower** [comment]
bump! just in case you want to prioritize this. I'll add it to my list of "things I would do"

**Comment by xavijam** [comment]
@viddo is "redoing" the geocoding dialog, I encourage you to talk with him, or if you need help we could fix a meeting.

**Comment by viddo** [comment]
FYI, for now I'm implementing the existing behavior

**Comment by xavijam** [comment]
Let me close this ticket, geocoding is now an analysis in the new builder, so probably it doesn't make any sense now :).

**Comment by rafatower** [comment]
okey dokey :+1:
