### ISSUE TITLE
Revamp map page

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#4013]
As you can see, on the public map page we use a modified version of the embed map. We need to prepare this taking in consideration the new embeds design. Is the only variation that is missing.

**Comment by josecruz** [comment]
I made this version after your improvement on the embed one.

Changelog: 
- Swapped "©Creative Commons" position with "Full page map" (previous):
![screen shot 2015-06-15 at 12 32 41](https://cloud.githubusercontent.com/assets/596509/8159066/3fb004d4-135b-11e5-83af-e64e11eca454.png)
- Changed zoom buttons orientation and full page + search position (for more symmetry with zoom buttons)
- Added a small dark gradient (same as mobile one)

Same version with different basemaps:
![v2 copy 2](https://cloud.githubusercontent.com/assets/596509/8159165/f03f7000-135b-11e5-9e11-f3d54c662ba0.png)
![v2 copy](https://cloud.githubusercontent.com/assets/596509/8159166/f0467986-135b-11e5-8284-6a25dd755eb8.png)
![v2](https://cloud.githubusercontent.com/assets/596509/8159167/f047f6c6-135b-11e5-875b-ebfb17111aff.png)

**Comment by saleiva** [comment]
Not sure about the changes tho...

The orientation on the buttons and the alignement is weird. They look lost in the middle.
In the wiki page I make a very strong point about having the lower number of things over the map, so I'd not put the bar there but in the white area (just above the title).

**Comment by saleiva** [comment]
bump!

**Comment by josecruz** [comment]
I made this provisional version (while @carlostallon's works on the new one)
![public - map not logged](https://cloud.githubusercontent.com/assets/596509/8286933/e73e2a94-190c-11e5-9198-a61a36d95311.png)

**Comment by josecruz** [comment]
Last design update by @carlostallon with the feedback provided by @saleiva 

![public - map disqus copy](https://cloud.githubusercontent.com/assets/596509/8436363/16569900-1f58-11e5-99ff-19d706c9ecb1.png)

And when it's your map:
![public - map -- when its your map](https://cloud.githubusercontent.com/assets/596509/8436326/c66f4a36-1f57-11e5-820e-b98a7fad0ee8.png)

**Comment by saleiva** [comment]
Like it. I think we should try how this look like and how we should resize the map on different resolutions

**Comment by carlostallon** [comment]
Wow, looking good!

2015-06-30 18:59 GMT+02:00 Sergio Álvarez Leiva <notifications@github.com>:

> Like it. I think we should try how this look like and how we should resize
> the map on different resolutions
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/4013#issuecomment-117256296>.
>



-- 
Carlos Tallón
Designer & Baker

**Comment by josecruz** [comment]
I don't know exactly what to do with the social icons but the idea is to show a "share icon" and when you tap it, with a lateral animation it'll appear the social icons:

![public map - mobile - logged](https://cloud.githubusercontent.com/assets/596509/8460456/0bd3cfd4-2025-11e5-862c-e7feb61ff0d0.png)
![public map - mobile - logged copy](https://cloud.githubusercontent.com/assets/596509/8460457/0bd5a6d8-2025-11e5-9219-c21333652619.png)

I made some changes on the spacings and normalized the font sizes here

**Comment by saleiva** [comment]
@josecruz LOVE IT

**Comment by josecruz** [comment]
So, here's the last version with all the sizes and spaces normalized:

![public map - mobile - logged](https://cloud.githubusercontent.com/assets/596509/8502293/40ca07d2-21ae-11e5-8bf7-7448f69279e5.png)
![public map - mobile - more show](https://cloud.githubusercontent.com/assets/596509/8502309/7734e440-21ae-11e5-8398-e020c65d5e26.png)
![public map - mobile - logged copy](https://cloud.githubusercontent.com/assets/596509/8502311/7a734e76-21ae-11e5-8dce-a3a05497160f.png)

**Comment by saleiva** [comment]
Something to fix is the different corner radius in the different occurences of the user avatar and in the logo!

**Comment by carlostallon** [comment]
Yep, in the logo the border radius is a 10% of his size. So we can apply
this norm also to the avatars.

2015-07-06 9:47 GMT+02:00 Sergio Álvarez Leiva <notifications@github.com>:

> Something to fix is the different corner radius in the different
> occurences of the user avatar and in the logo!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/4013#issuecomment-118761476>.
>



-- 
Carlos Tallón
Designer & Baker

**Comment by josecruz** [comment]
Updated all corner radius on the sketch file.
![public map - mobile - logged](https://cloud.githubusercontent.com/assets/596509/8527177/8f14f460-240b-11e5-8b24-4a588bcbc2d1.png)

**Comment by carlostallon** [comment]
what happen with this one? [image: Imágenes integradas 1]

; )

2015-07-06 18:19 GMT+02:00 josecruz <notifications@github.com>:

> Updated all corner radius on the sketch file.
> [image: public map - mobile - logged]
> <https://cloud.githubusercontent.com/assets/596509/8527177/8f14f460-240b-11e5-8b24-4a588bcbc2d1.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/4013#issuecomment-118915263>.
>



-- 
Carlos Tallón
Designer & Baker

**Comment by josecruz** [comment]
Can't see your image but I know what you've found :P
![public map - mobile - logged](https://cloud.githubusercontent.com/assets/596509/8541545/70e49016-248f-11e5-817e-30acd90b8542.png)

**Comment by carlostallon** [comment]
hahaha, YES!

2015-07-07 10:03 GMT+02:00 josecruz <notifications@github.com>:

> Can't see your image but I know what you've found :P
> [image: public map - mobile - logged]
> <https://cloud.githubusercontent.com/assets/596509/8541545/70e49016-248f-11e5-817e-30acd90b8542.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/4013#issuecomment-119111960>.
>



-- 
Carlos Tallón
Designer & Baker
