### ISSUE TITLE
design export image with preview + select zone control

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#4014]
the export dialog needs to allow the user to control the zone is going to be exported

**Comment by vishalya** [comment]
The selection should be user friendly, so that user can select, by mouse the following aspects of the image being exported
(1) the size of the image, 
(2) zoom 
(3) center the image to a desired point

This could be a part of the export dialog or some selection right from the main map and the export dialog can preview this image.

**Comment by josecruz** [comment]
Following @saleiva's template I made this one with:

Proportions lock to proportionally increase *screenshot* size
Possibility to increase size draggin horizontally when click over the *w* (width) or *h* (height) *(see 2nd design)*:
![resize](https://cloud.githubusercontent.com/assets/596509/8178479/49c0239a-1406-11e5-92ce-905aa27d20a0.png)


![classic editor - v1](https://cloud.githubusercontent.com/assets/596509/8178378/5a4695d8-1405-11e5-986c-3491d96e43cc.png)
![classic editor - v1 copy](https://cloud.githubusercontent.com/assets/596509/8178377/5a44f868-1405-11e5-8efa-8dfc5a484ebc.png)

**Comment by javisantana** [comment]
I miss a cancel button (I guess escape will do the thing).

@xavijam I don't know if there will be problems in safari with pointer-events

**Comment by xavijam** [comment]
I don't think so http://caniuse.com/#search=pointer-events.

**Comment by vishalya** [comment]
I agree with javisantana on the cancel button, we will need it.

**Comment by josecruz** [comment]
v2:
![classic editor - v2](https://cloud.githubusercontent.com/assets/596509/8208619/760619fa-1500-11e5-826c-00ccbd0564bd.png)
The "back" button will work as a cancel button.

**Comment by saleiva** [comment]
![export image](https://cloud.githubusercontent.com/assets/132149/8227048/24b9624c-15a4-11e5-946a-07700160e8b7.png)

**Comment by saleiva** [comment]
![map editor - export image b](https://cloud.githubusercontent.com/assets/132149/8227227/b2f88c6c-15a5-11e5-81e2-10f45b092525.png)
![map editor - export image](https://cloud.githubusercontent.com/assets/132149/8227228/b2f98f9a-15a5-11e5-94bd-f7c10b8583b1.png)

Available in map-editor-1.5.sketch

cc/ @javisantana

**Comment by vishalya** [comment]
How does user cancel and go back to the regular mode?

**Comment by javierarce** [comment]
Right now pressing the esc key will close the selection tool and go back to the regular mode, but I agree we should add a close button somewhere.

**Comment by josecruz** [comment]
Cancel button:
![export image](https://cloud.githubusercontent.com/assets/596509/8311712/4a533ec8-19d8-11e5-9efe-d69dbf9f4120.png)
(in the same file: take-image-04.sketch)

**Comment by javisantana** [comment]
from @vishalya 
```
(1) For the image selection, would you be able to change the UI so that, we have a 'X' image at the right top corner, like the windows dialog, which would server as a cancel operation.
(2) The Cancel button can be moved to the bottom next to the export button.

This will look more in line (consitent) with the a regular dialog for the users.
```
cc @josecruz @saleiva

**Comment by josecruz** [comment]
Thanks for the feedback @vishalya! 

We've updated it with the element we use on the new modals:
![export image](https://cloud.githubusercontent.com/assets/596509/8499945/02a4f964-2198-11e5-94d6-4667ba7060df.png)

**Comment by vishalya** [comment]
Let me get some more feedback from the users here, so let's not close this one.
In general, we always have 'cancel' buttons along side the 'Export' or 'OK' buttons, so please wait till I demo it to all the stake holders.

**Comment by javisantana** [comment]
@vishalya do you have that feedback?

**Comment by vishalya** [comment]
This can be closed.
