### ISSUE TITLE
Torque Categories wizard: Something is not working ok

### ISSUE THREAD

**Issue by miguelarias** [CartoDB/cartodb#4025]
It might be related to issues with the gnip connector, BUT, when you create a torque categories visualisation, it is taking the style for the default value which is not category 1 or category 2. Hence the visualisation makes no sense. Somehow, it is adding a different value to the category, so that it displays value 3 for the mode. 

This happened already last weekend, but I thought it was GNIPs data, now it seems that GNIPs data is ok, and it is still happening (see my dataset with jack and dickc data) here.

https://team.cartodb.com/u/marias/datasets

**Comment by miguelarias** [comment]
I think it has to do with the " " which are added if you search for two terms together instead of 1 single word. But I would fell this was not the case before. This is pretty important.

**Comment by saleiva** [comment]
@kartones, assigning to you so you can also research on this

**Comment by Kartones** [comment]
Checking as I do the other ticket, but space added in multiple words in the same term (e.g. `cartodb sotmus` vs `cartodb, sotmus`) it's been this way since the beginning of the connector/datasource, this logic hasn't changed.

**Comment by Kartones** [comment]
I need further clarification about what is wrong here, @miguelarias or @javisantana , as doing a local test with a search term composed of two words works ok from what I see:

![image](https://cloud.githubusercontent.com/assets/2085449/8130613/1b9ed104-1114-11e5-86b2-c39866667f62.png)

**Comment by javisantana** [comment]
This problem was related to a category including some quotes. For some reason when a category includes double quotes, the query we use to generate that value was not working so ``value`` was 3 (so the colors was the default).

Not sure what were the search terms maybe @miguelarias can post them here.

**Comment by Kartones** [comment]
Ahh, ok, will try with quotes, I need to escape terms if they're not usual alphanumeric:
```ruby
if sanitized.gsub(/[a-z0-9@#]/i,'') != ''
  sanitized = '"' + sanitized + '"'
end
```

**Comment by Kartones** [comment]
Ok, clarified with @miguelarias via chat, he was using `category_terms` which with simple 1 term searches works but with multiple ones doesn't and is not the intended one. Using `category_names` is the proper way (as they are `1`, `2`, etc.)
