### ISSUE TITLE
Organization user login

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#4026]
- [X] Check whether user is login at public or organization page. @juanignaciosl
- [X] Org color column. @juanignaciosl
- [X] Load "current organization". @juanignaciosl
- [x] Look & feel. @xavijam

**Comment by xavijam** [comment]
@saleiva, are we adding the name of the organization on purpose (in the top of the page)? or you added as part as the logo?

![screen shot 2015-06-15 at 15 45 55](https://cloud.githubusercontent.com/assets/132146/8161652/c757fd66-1378-11e5-9f6e-b93fbc8b5c35.png)

**Comment by saleiva** [comment]
Is part of the logo

**Comment by saleiva** [comment]
I'm thinking that the logo should be over white anyway... so I might need to adapt the design a bit...

**Comment by xavijam** [comment]
I added a text-shadow, just in case background color is light

**Comment by saleiva** [comment]
That will not work since most of the logos will be pngs or even jpgs. Go ahed with the actual design but we will likely have to change it soon

**Comment by xavijam** [comment]
:+1:

**Comment by xavijam** [comment]
No, but I thought in the design we had:

Logo (image) + organization name (text with shadow) + CartoDB logo (image)

**Comment by saleiva** [comment]
Nope. It's only a logo plus an small log

**Comment by xavijam** [comment]
@juanignaciosl, a bug I found, maybe my bad, in that case sorry :S.

### STR:
1. Go to login page.
2. Click login button (yes, leave the password field empty).
3. Error -> 

```ruby
undefined local variable or method `login_org_avatar' for #<#<Class:0x000000075cec28>:0x00000009c5d128>
```

**Comment by xavijam** [comment]
Look and feel added, but a review together @saleiva would be appreciated.

**Comment by juanignaciosl** [comment]
@xavijam can't reproduce the error, could you give me more details?
- Which url are you using?
- What username do you set?
- Full error stack trace.
- Have you reproduced it in staging?

**Comment by xavijam** [comment]
Ha! Restarted my development server and working like a charm, so done! :)

**Comment by juanignaciosl** [comment]
Great, @xavijam , so some testing & merge? :-)

**Comment by xavijam** [comment]
Yes and no, I have to take a look with @saleiva and then ready to go.
