### ISSUE TITLE
Upselling when users can't add more layers to a map

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#4028]
Right now we remove "+" button from the right panel.

**Comment by saleiva** [comment]
Dude, we need a modal window talking about the number of layers supported on each paid plan and a CTA for upgrading.

**Comment by josecruz** [comment]
I think it would be a bit weird showing the layers limit here and not in ` /account/username/upgrade/`
![map editor - layer limit](https://cloud.githubusercontent.com/assets/596509/8452873/ea059f3a-1fee-11e5-8c44-2a4a49e7f205.png)

**Comment by saleiva** [comment]
I think this would be a good possibility to show also the other benefits of upgrading although we highlight the number of layers. Also a ticket should be open in central to add the number of layers in every place we talk about the pricing

**Comment by josecruz** [comment]
Okay, something like this?

![map editor - layer limit](https://cloud.githubusercontent.com/assets/596509/8455552/db4d6a1a-2005-11e5-862b-af922faaa167.png)

**Comment by saleiva** [comment]
Same than in central, the naming here is understandable, but a deep thought on it would be worth.
'Close' button on the right? And... there is a recent issue where we talked about the 'close' buttons, and we agreed to discard them based on the fact that 'esc' key and the button on the top-right corner already close the modal.

**Comment by josecruz** [comment]
So, no close button is better :P
![map editor - layer limit](https://cloud.githubusercontent.com/assets/596509/8482190/4069c62c-20e8-11e5-8c51-1f3d74fa1401.png)

Still waiting response from sales team on this issue CartoDB/cartodb-central#692

**Comment by xavijam** [comment]
Reminder: https://:domain/account/:username.json

**Comment by xavijam** [comment]
@jose, does it make sense to have Free thing in that list?

**Comment by xavijam** [comment]
Several scenarios:

- Regular user: we have covered it :+1: .
- Organization admin: if this kind of user open this dialog, we should say something like: contact us if you to have more layers...
- Organization user: in this case, dialog should say: contact your administrator in order to get more capabilities.
- Open source user:  last case, we should say, hey, your user doesn't have more layers, just check your User model and change 'max_layers' attribute, for example.

This is important and we haven't covered all these scenarios.

@josecruz @saleiva

**Comment by saleiva** [comment]
for organization users, as we are already in the maximum I’d remove the button.
S.

-----
@saleiva

**Comment by xavijam** [comment]
I'll do for both, open source and org users.

**Comment by josecruz** [comment]
So, open source and org users solved? I suggest a button on the org-users to get in touch with the org-admin

For org admin I made this two versions:
![map editor - layer limit - org user](https://cloud.githubusercontent.com/assets/596509/9099792/abf3cd4a-3bcb-11e5-9da4-41fdcda6d66a.png)


And a simpler one based on the export image one:
![map editor - layer limit - org user copy](https://cloud.githubusercontent.com/assets/596509/9099794/af428b1c-3bcb-11e5-9f6a-dee95168ca7e.png)

Q: not sure if they have to contact support or sales

**Comment by xavijam** [comment]
They will contact a dedicated email for enterprise users.

**Comment by xavijam** [comment]
Any of those could work, @saleiva?

**Comment by saleiva** [comment]
Users under enterprise account will have an admin email so what Jose
proposes is good too
