### ISSUE TITLE
Offer the option to try lat/lon 4326 projection when not finding the .prj file

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#4031]
Great feedback from one of our users. Would increase number of imports from shp for sure.

For this particular case we should open another modal before the error one where we ask if we should add that projection automatically. This error is the 2nd most popular in shp files

cc/ @javisantana @Kartones

**Comment by javisantana** [comment]
One of the problems I found is normally when there is no prj is not that common that it is 4326, normally those shp are from country open portals and they use different datums so even the coordinates looks like 4326 they are not. Other common issue is those coordinates are in UTM, kind of easy to guess, but in that case we would need to know things like the UTM zone.

Having an extra window after an error means a lot of work in the importer, it's not a simple task. In any case, if you show that to the user, they will click anyways, better to have bad data than no data, so why not just try to see if it looks like 4326 (or other) and do it in any case (some warning would be nice)

also, for the record, I proposed this years ago.

**Comment by saleiva** [comment]
+1 to your proposal as well. As easier, the better.

**Comment by Kartones** [comment]
Branch is `4031-try-projecting-shps-without-prj`

**Comment by javisantana** [comment]
Hey @Kartones could you explain a little bit what logic will you use to guess the projection?

**Comment by saleiva** [comment]
Yeah, an summarize how this works. Too many comments on this :)

**Comment by Kartones** [comment]
I'm just fighting with SHP import to see if I can attack the first solution provided by @javisantana:
- "*when there is no prj is not that common that it is 4326 [...] so why not just try to see if it looks like 4326 (or other) and do it in any case*"

If I achieve that (current import seems very tied to having always all 4 files) I'll try to attack the UTM one

**Comment by Kartones** [comment]
I prefer to only fight one battle at once, so I've fixed the `no .prj present` issue. If you can provide me a sample of the UTM one and/or file me a ticket... @javisantana
