### ISSUE TITLE
Geocoding credits number not correct on the UI

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#4033]
It says I have 9K aprox available but the in requests it says
`remaining_quota: 99961`

**Comment by xavijam** [comment]
Due to the fact that you are taking care of the geocoding dialog, let me reassign this ticket to you :).

**Comment by viddo** [comment]
Could any of you give some hints of where this "xK approx" text is displayed exactly? 

The only [direct reference](https://github.com/CartoDB/cartodb/blob/bd99eac31dce8c063f602567cb8b08530c1240ad/lib/assets/javascripts/cartodb/common/background_polling/views/geocodings/geocoding_result_details_view.js#L73) to the mentioned attribute I find is running the number through `cdb.Utils.formatNumber` which yields `99,961`, and all other usages just render the value as it is, so must be some other property that is rounded down wrongly.

**Comment by saleiva** [comment]
in the geocoding modal is where the text is rendered.

**Comment by viddo** [comment]
I keep asking because just searching through the code I have not been able to pinpoint where the issue could be. So far:

> in the geocoding modal is where the text is rendered.

Is this context you're referring to? <img width="640" alt="screen shot 2015-07-07 at 14 12 27" src="https://cloud.githubusercontent.com/assets/978461/8545796/5be29352-24b2-11e5-9e43-6e55198ac32e.png">

If yes, there's no approximation being done (e.g. rounding down), but the value displayed is the [monthly quota - monthly usage](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/table/views/geocoding_dialog/geocoding_dialog_pane_address.jst.ejs#L25) which would explain why you don't see the full quota, perhaps. But there's no `remaining_quota` property being used or received/sent in this context.

There's also the geocoding result window, where the [`remaining_quota`](https://github.com/CartoDB/cartodb/search?l=javascript&q=remaining_quota&utf8=%E2%9C%93) prop is being used, but there is no approximation (e.g. rounding done), like I mentioned before. :/

**Comment by saleiva** [comment]
that calculation is weird, right? we just should show the remaining_quota

**Comment by viddo** [comment]
Well, it is the remaining quota, it's just not pre-calculated and given from the server-side why it's it's done here on the client-side, I guess. Was this the place you're were talking about?

**Comment by saleiva** [comment]
yep!

**Comment by viddo** [comment]
Ok, but in that case:

> …but the in requests it says `remaining_quota: 99961`

What request was this?

**Comment by saleiva** [comment]
if you open the inspector (network tab), it gives you values or remainning quota as part of the partial responses

**Comment by viddo** [comment]
Looking more into this I have a theory on what is going on; As I stated previously, there is no logic or calculation that rounds down and the calculation for the quota left looks legit, which makes me suspect that data is inconsistent between server- and client-side. 

For one thing, after a geocoding is done, the user object would need to be updated. In the [old code of backgroundview](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/table/backgroundview.js#L33) this is done, but for the new code user is only updated [on imports](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/table/table.js#L255-L259) so I suspect that we're missing a `user.fetch()` call on [`geocodingCompleted` events too](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/table/table.js#L235). Can you confirm @xavijam ?

Even if it would be updated I found several irregularities in the code server-side that could also explain the differences in numbers:
- current quota is derived from [`user.geocoding` object](https://github.com/CartoDB/cartodb/blob/master/app/models/user/user_decorator.rb#L31-L36) which takes the organization use-case into account, but estimation cost is calculated from [`user.remaining_quota`](https://github.com/CartoDB/cartodb/blob/master/app/controllers/api/json/geocodings_controller.rb#L118-L127) so it's not taking the organization quota/usage into account.
- the `remaining_quota` prop that @saleiva pointed out, is fetched through [geocoding model](https://github.com/CartoDB/cartodb/blob/c7639a04597bd14d079b57b9982d21d85543c670/app/models/geocoding.rb#L207-L209), but depending on if the user object is the db model or the decorator you'll get different results it seems, see [`user.remaining_quota` (decorator)](https://github.com/CartoDB/cartodb/blob/c7639a04597bd14d079b57b9982d21d85543c670/app/models/carto/user.rb#L198-L200) vs. [`user.remaining_quota` (model)](https://github.com/CartoDB/cartodb/blob/51c227df9517a174e778bfd30abb5ca24912d6ad/app/models/user.rb#L973-L980)

It could be that I misunderstand the code paths here, I have not worked enough with the server-side to have a clear understanding how things are glued together, perhaps you @rafatower can verify if my findings are correct?

**Comment by xavijam** [comment]
Yep, we need to update user model after a geocoding is completed, you are right.

**Comment by rafatower** [comment]
The bug comes from the refactor, in the old model the organization it is taken into account while in the new one it is not.

See https://github.com/CartoDB/cartodb/blob/master/app/models/user.rb#L973-L980

vs https://github.com/CartoDB/cartodb/blob/master/app/models/carto/user.rb#L198-L200

**Comment by viddo** [comment]
Aha, updated the comment to reflect this (sequel/active-record instead of model/decorator).

So, from my current understanding, fixing that inconsistency + the already merged fix for the frontend should close this issue finally. Reassigning to Rafa, since he'll take care of fixing the model.
