### ISSUE TITLE
sometimes legend values are integers and they should be strings

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#4038]
it breaks just here: 

https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/table/menu_modules/legend_editor.js#L223

So either we cast or just not save integers to the server

**Comment by javisantana** [comment]
it happens when the legend is customized in html

**Comment by javierarce** [comment]
Fix in a PR. Do you have an example that make this failed?

**Comment by javierarce** [comment]
bump
