### ISSUE TITLE
Remove "Map" from the default name of visualizations

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#4041]
Of course it's a map! :)

![screen shot 2015-06-12 at 11 35 57 am](https://cloud.githubusercontent.com/assets/370259/8137368/c9a4b524-10f7-11e5-8c94-d9f0aaafbcf8.png)

**Comment by xavijam** [comment]
Agree buddy :+1:

**Comment by xavijam** [comment]
I feel this coming from the backend side, I checked and probably it comes from [here](https://github.com/CartoDB/cartodb/blob/master/app/models/table.rb#L646).
Could you @juanignaciosl or @rafatower confirm it?

**Comment by juanignaciosl** [comment]
Sure, [it's been like this since Feb.](https://github.com/CartoDB/cartodb/commit/d831f6462fe0990e95b7d95c6a879a7d7de618f1).
