### ISSUE TITLE
feature request: add option to change default subdomains in the editor

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/cartodb#4062]
Right now, as far as I know, it's not possible to configure the Editor to have subdomains for the {s} field other than 'abcd'. There are several basemaps that need '0123' instead. Could this be added to the UI under advanced options or something like that?

**Comment by saleiva** [comment]
Hey @ohasselblad could you elaborate on the usecase for this? Where the request comes from?

**Comment by ohasselblad** [comment]
Some xyz templates only accept '0123' as the subdomain like [here](http://wiki.openstreetmap.org/wiki/Slippy_map_tilenames#Tile_servers). I was also playing with Planet's API and [their tiles](https://www.planet.com/docs/v0/mosaics/#mosaic-tiles) only allow 0,1,2,3.
