### ISSUE TITLE
Create a map from a dataset new modal dialog is throwing an error

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#4067]
## STP
- Enable 'new_modals' feature flag.
- Go to a dataset view.
- Click over "visualize" button (to create a map from this dataset).
- Error in console appears.

Uncaught Error: TrackJS Caught: success callback is required

I feel this is related with https://github.com/CartoDB/cartodb/pull/4052

cc @viddo

**Comment by viddo** [comment]
Yeah, seems to be due to https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/common/dialogs/create_vis_first/create_vis_first_view.js#L18

**Comment by javierarce** [comment]
Sorry for that, I didn't notice it:( I'll fix it.

**Comment by xavijam** [comment]
No prob buddy, mate, pal, fella...
