### ISSUE TITLE
help options in the wizard

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/cartodb#4072]
I met someone today who suggested these things, which I think are great ideas: 

1. information hover overs next to tools (such as quantification, composite operations, etc.) to help users know which is the best fit for them
1. a little help box to lead the user to resources when they open a tray, such as leading them to the new lesson on CartoCSS when they open the css tray, or same with sql

He said don't go the clippy direction: 
![clippy](https://cloud.githubusercontent.com/assets/1041056/8195581/8f1f96e6-1438-11e5-999e-25516c0eb342.jpeg)

**Comment by saleiva** [comment]
Working on this on the new editor!
