### ISSUE TITLE
It would be extremely nice to be able to go to a dataset view from a map view

### ISSUE THREAD

**Issue by lbosque** [CartoDB/cartodb#4078]
I find myself a lot of times wanting to click in a layer name in order to go to the dataset view.
That would be very useful

**Comment by saleiva** [comment]
@josecruz let's make your brain work

**Comment by josecruz** [comment]
I would make the dataset name of the uncollapsed right sidebar clickable, but just in case that we want to keep that to change dataset name, I made a small link below dataset name:

![artboard](https://cloud.githubusercontent.com/assets/596509/9379544/5da46ac2-472a-11e5-9c30-35eb1bd55e2a.png)

**Comment by saleiva** [comment]
Then why not making the name of the source dataset clickeable?

**Comment by josecruz** [comment]
Because you won't be able to change that dataset name. Is probable to change your dataset name from there? If it's not, then i would make that clickable

**Comment by saleiva** [comment]
You don't change the dataset name, you change the layer name (the bold text).

**Comment by josecruz** [comment]
Okay, then let's make the name as an action to go to the dataset and a link below to change layer name.
![artboard](https://cloud.githubusercontent.com/assets/596509/9383529/3497d068-474a-11e5-824e-15cfb99da660.png)

**Comment by saleiva** [comment]
Cannot, cause the bold text is the layer name and the other one the dataset_name. It's important that the bold text is the identifier in this map since, for example, you could have two layers that are different views of the same dataset.

**Comment by josecruz** [comment]
Okay so something like this could work?
![artboard](https://cloud.githubusercontent.com/assets/596509/9384677/592c0f18-4752-11e5-8264-e46fa4a5235b.png)

**Comment by saleiva** [comment]
And what would do you with long names?
Dude, cannot you just make a link on the dataset name?

**Comment by josecruz** [comment]
Yeah, didn't figured it out
![artboard](https://cloud.githubusercontent.com/assets/596509/9389688/a51b12f6-476c-11e5-9fb0-6a37791b1963.png)

**Comment by saleiva** [comment]
Looks good to me!

**Comment by xavijam** [comment]
Hey, one of those tickets I'll do with pleasure.

**Comment by lbosque** [comment]
+1

On Thu, Aug 20, 2015 at 10:10 PM, Javier Álvarez Medina <
notifications@github.com> wrote:

> Hey, one of those tickets I'll do with pleasure.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/4078#issuecomment-133157452>.
>



-- 
Luis Bosque
@luisico

www.cartodb.com
Map, analyze and build applications with your data
