### ISSUE TITLE
Error uploading assets (using dropbox or URL)

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#4079]
#### Steps to reproduce it

1. Create a map with a geometry (a polygon, for example)
2. Go to the wizards panel
3. Select the simple wizard 
4. Add a new image as background (using dropbox or a URL)

#### Expected result

The polygon should show the image as background.

#### Actual result

There's a JavaSCript error in this line https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/common/dialogs/map/image_picker/upload_model.js#L15 and no further action is done.

The console shows: ```Uncaught ReferenceError: method is not defined```

Tested in Chrome Version 43.0.2357.124 (64-bit) for mac.

**Comment by xavijam** [comment]
I'll take care of it

**Comment by javierarce** [comment]
Thanks! :heart:

**Comment by Kartones** [comment]
ouch, the thing is I tried this in local and seemed to work, but probably I missed a grunt js or something. my bad :(
