### ISSUE TITLE
There's no way to create a visualization from inside a shared with you read-only dataset

### ISSUE THREAD

**Issue by zenitraM** [CartoDB/cartodb#4082]
Steps to reproduce:
- User A shares a private table with user B
- User B goes into that table -> it shows him the public view of the table:
![image](https://cloud.githubusercontent.com/assets/863975/8204611/26d8147a-14ea-11e5-921f-1f512aebfe36.png)

Two issues here:
- There is a "Create map" button that goes to one-click (and fails as the dataset is really private). 
- There's no way for B to create a visualization from inside this view (he must use New visualization from the dashboard).

**Comment by saleiva** [comment]
related with #4123.
we should have an option under the options menu to create a map with this on the read-only view of the dataset.

**Comment by xavijam** [comment]
Related with https://github.com/CartoDB/cartodb/issues/4123, yes.

**Comment by xavijam** [comment]
@saleiva if it worked as expected, you will be able to create a visualization being in the table view (in read only mode). I feel if we fix #4123, we will make the process easier.

**Comment by saleiva** [comment]
yep

**Comment by xavijam** [comment]
Closing then and pointing to #4123.
