### ISSUE TITLE
"undefined rows affected" when running an UPDATE query from the UI

### ISSUE THREAD

**Issue by zenitraM** [CartoDB/cartodb#4083]
![image](https://cloud.githubusercontent.com/assets/863975/8204682/a92887a2-14ea-11e5-8c8f-722fe5b88de8.png)

If it helps, this was done from a visualization on a MU account whose only layer is a shared table from another user (ask me for link), but might be reproducible anyway with an ordinary account

**Comment by juanignaciosl** [comment]
Duplicated: #2014
