### ISSUE TITLE
Tables dropped using the SQL API aren't removed from the editor anymore

### ISSUE THREAD

**Issue by danicarrion** [CartoDB/cartodb#4088]
I regularly (every 15 min) create and drop a table using the Import API (creation) and SQL API (deletion). Starting a few days ago, I've noticed those deleted tables remain on the editor's table list. Currently, my editor says I have +1100 tables (and growing), but in reality I have 78-79.

It used to work perfect just a few days ago.

**Comment by javisantana** [comment]
@rafatower @juanignaciosl @Kartones do you know if we changed something related lately?
@danicarrion could you send us what is the first table not removed so we can identify a deploy?

**Comment by danicarrion** [comment]
The first table seems to be pepsicoca_zlqclrgqggkppbkcrvlapfeom 8 days ago

**Comment by juanignaciosl** [comment]
[this](https://github.com/CartoDB/cartodb/commit/e6ec43b76e3c37aed671410bc6a03cdc3669e199#diff-4676c008b11a5480d73d4a6de01e45b9) is the most recent change I recall. Anyway I'd also check in metatable `visualizations` that table is there and with what dates.

**Comment by javisantana** [comment]
Ok, it's a problem with recent named maps change. I tried to remove manually one of those tables and I get

```
CartoDB::NamedMapsWrapper::HTTPResponseError: PUT:400 http://useb.ep.cartodb.com:80/api/v1/map/named/tpl_134d7592_0f47_11e5_b74a_0e8dde98a187?api_key=27a4f4e9243f32031caf8225a7b29632ce80ff7a {"error":"Error: Missing or empty layers array from layergroup config"}
	from /home/ubuntu/www/production.cartodb.com/releases/20150617103521/services/named-maps-api-wrapper/lib/named-maps-wrapper/named_map.rb:81:in `update'
	from /home/ubuntu/www/production.cartodb.com/releases/20150617103521/app/models/visualization/member.rb:762:in `update_named_map'
	from /home/ubuntu/www/production.cartodb.com/releases/20150617103521/app/models/visualization/member.rb:750:in `save_named_map'
	from /home/ubuntu/www/production.cartodb.com/releases/20150617103521/app/models/visualization/member.rb:427:in `invalidate_cache'
	from /home/ubuntu/www/production.cartodb.com/releases/20150617103521/app/models/map.rb:97:in `block in invalidate_vizjson_varnish_cache'
	from /home/ubuntu/www/production.cartodb.com/releases/20150617103521/app/models/map.rb:96:in `each'
	from /home/ubuntu/www/production.cartodb.com/releases/20150617103521/app/models/map.rb:96:in `invalidate_vizjson_varnish_cache'
	from /home/ubuntu/www/production.cartodb.com/releases/20150617103521/app/models/map.rb:69:in `before_destroy'
```

**Comment by Kartones** [comment]
@danicarrion can you try again now? I think that was a temporal issue and already bugfixed.  I'm trying locally and live and works fine.

**Comment by Kartones** [comment]
Yep, indeed works fine now without erros from my tests, so closing. Feel free to reopen if happens to you still.

**Comment by danicarrion** [comment]
I can confirm it works alright for me too. Thanks!
