### ISSUE TITLE
Design the loading, success and error steps after a new signup within an organization

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#4090]
The flow would be:

1. Go to new organization signup page.
2. Fill up the form and send it.
3. Page or state saying we are creating your user. (loading)
4. Once finished, show everything was ok and you have to check your email. (success)
5. Or it could fail :( (error)

cc @juanignaciosl

**Comment by saleiva** [comment]
Done in signup-0.6.
Look at how much I love your loading logo that I've added it here too...

![04 loading copy](https://cloud.githubusercontent.com/assets/132149/8208648/fc86a17c-1508-11e5-8bf3-c86fe0cf79b3.png)
![04 loading_mu](https://cloud.githubusercontent.com/assets/132149/8208650/fcd1a942-1508-11e5-82b7-59601fd75ddd.png)
![04 loading](https://cloud.githubusercontent.com/assets/132149/8208649/fcb0a9cc-1508-11e5-8f50-e432733b3688.png)

**Comment by saleiva** [comment]
("Your account ready" => "Your account is ready")

**Comment by xavijam** [comment]
:D :heart:


On 17 Jun 2015 at 15:59:51, Sergio Álvarez Leiva (notifications@github.com) wrote:

Done in signup-0.6.
Look at how much I love your loading logo that I've added it here too...

**Comment by juanignaciosl** [comment]
Design is as lovely as loading logo :-) Just one complain (sorry, guys): industry/role is a Central-only concept, and probably it doesn't makes much sense within an organization. I wouldn't include it for organization user signups, what do you think?

**Comment by saleiva** [comment]
Yep, thats the idea

**Comment by xavijam** [comment]
Sign up background color should be the organization background color, shouldn't it?

**Comment by xavijam** [comment]
Also, if the process fails, should we change the layout? I'm changing the text but not sure if we want that or we miss that state.

**Comment by xavijam** [comment]
Closing since it is done, let's take care of the details in the pull request -> https://github.com/CartoDB/cartodb/pull/4138/files.
