### ISSUE TITLE
"undefined rows affected" message appears although the updates work

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#4097]
This is been like this for a while, but I thought that is worthy to report as for a user it seems like "nobody changed" or "there was an error".

**Steps:**
* Create an empty table
* Open DevTools/Network, clear history
* Apply the query `UPDATE tablename SET name = 'whatever'`
* The editor says:
![image](https://cloud.githubusercontent.com/assets/1730320/8209180/de4d0810-150b-11e5-9c34-9d61d9301d20.png)

* The API SQL says:
![image](https://cloud.githubusercontent.com/assets/1730320/8209176/d770a36c-150b-11e5-8660-a416a35c69b2.png)

cc @javisantana @saleiva

**Comment by juanignaciosl** [comment]
Duplicated #2014
