### ISSUE TITLE
Apply header image bkg to all the templates screens that should have it

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#4100]
Try also with dark, medium and light maps to find the best solution. It's only applied now in one screen. It's on create-map-1.5

**Comment by josecruz** [comment]
I tried different styles and when it's a dark basemap it looks a bit weird. Anyway I made a couple of gradients to make it look less weird:

![template 1 - step 1 - dark copy 1](https://cloud.githubusercontent.com/assets/596509/8251513/77ef8200-167d-11e5-8ea4-dc6e811ce7e8.png)
![template 1 - step 1 - dark copy](https://cloud.githubusercontent.com/assets/596509/8251518/77fe5d3e-167d-11e5-93eb-dd382b2b66f3.png)
![template 1 - step 1 - dark copy 2 1](https://cloud.githubusercontent.com/assets/596509/8251514/77f189d8-167d-11e5-8289-6155328cff22.png)
![template 1 - step 1 - dark copy 2](https://cloud.githubusercontent.com/assets/596509/8251517/77fd5f56-167d-11e5-9c60-fd970d8f3962.png)
![template 1 - step 1 - dark copy 3 1](https://cloud.githubusercontent.com/assets/596509/8251516/77fbc6a0-167d-11e5-87f7-921acd98d50a.png)
![template 1 - step 1 - dark copy 4](https://cloud.githubusercontent.com/assets/596509/8251515/77f97832-167d-11e5-80d2-7f3d47eb93a8.png)

**Comment by josecruz** [comment]
Last update:
![template 1 - step 1 - dark copy 3](https://cloud.githubusercontent.com/assets/596509/8281862/4964ab38-18ec-11e5-8fd4-b8e90ef1a4e2.png)
![template 1 - step 1 - dark copy 5](https://cloud.githubusercontent.com/assets/596509/8281863/496778ae-18ec-11e5-9dd4-1fa88945ccfc.png)
![template 1 - step 1 - dark copy](https://cloud.githubusercontent.com/assets/596509/8281864/49683730-18ec-11e5-8359-433f6dbb1064.png)

**Comment by saleiva** [comment]
Closing since we think is good.
