### ISSUE TITLE
Refine new create-map window for those cases where there are custom templates

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#4101]
Decide if we want same-height cards or nope, and refine the aesthetics.

**Comment by josecruz** [comment]
I would use different height cards when proportions are not always the same (like pinterest board) but here the sizes are going to be always the same so using different height would look a bit disordered:

![create - template selector](https://cloud.githubusercontent.com/assets/596509/8251701/12918d3e-167f-11e5-9acc-3418235225e1.png)

**Comment by saleiva** [comment]
Also we should try to unify this screen and the next one that appears when clicking on EMPTY map so we remove an extra click. Worth think on it and how to fit this there.

**Comment by josecruz** [comment]
So this is the layout I made with different widths instead of different heights:
![create - template selector copy](https://cloud.githubusercontent.com/assets/596509/8311979/500a55b6-19da-11e5-8138-d2dd72dd9432.png)
I think I'll need some help to unify the next step.

**Comment by saleiva** [comment]
Like the layout. Now I just think on how to unify

**Comment by josecruz** [comment]
So here's the last version. The idea here is:

When you click on **Create new map** it'll redirect you directly to the connect dataset modal with a new tab called **Map templates**.
![create - template selector - empty map - datasets copy 4](https://cloud.githubusercontent.com/assets/596509/8437434/2fc9ed90-1f5f-11e5-9464-fca42386dac9.png)

For the video tutorials, I've included a link on the footer that will open this modal:
![create - template selector - empty map - datasets copy 3](https://cloud.githubusercontent.com/assets/596509/8437450/4357fd98-1f5f-11e5-9d0f-a37c5726837a.png)

**Comment by saleiva** [comment]
Like it.

**Comment by saleiva** [comment]
Hey @xavijam keep this as the last thing if possible

**Comment by xavijam** [comment]
Good decision, best location to place 'Maps template' option :+1:.

**Comment by xavijam** [comment]
Or not, because that part is related with datasets, not maps, not sure.

**Comment by xavijam** [comment]
1. That dialog with the videos, @josecruz, is this one:
![screen shot 2015-07-01 at 17 40 46](https://cloud.githubusercontent.com/assets/132146/8458614/5fe6e5aa-2018-11e5-9f30-97533f701f45.png)

I don't see the benefit of create a new dialog with the same content. Would it be better to just show that step instead of the "create new map" step?

2. Does the 'EMPTY MAP' do the same as "CREATE EMPTY MAP" button does?

**Comment by josecruz** [comment]
@xavijam the idea is to remove that screen and go directly to the connect dataset one.

**Comment by josecruz** [comment]
Any updates on this? /cc @saleiva @xavijam

**Comment by saleiva** [comment]
Can you work also son the zero cases? Not having datasets (do we go to the data library? or to the templates?)

**Comment by xavijam** [comment]
Closing since we have already have it there. We will follow the designs from now on :D. Thanks both!
