### ISSUE TITLE
Edit metadata modal is creating a new row instead of persisting changes

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#4109]
**Steps to reproduce:**

- Open the new Edit Metadata modal on any feature.
- Edit some metadata.
- Click "Save"

**Expected behaviour:**

- Changes are persisted and you can see them if you open the dialog again.

**Current behaviour:**

- Changes are not persisted. Instead, a new row is created.

![editmetadata](https://cloud.githubusercontent.com/assets/390398/8227792/3e285606-15aa-11e5-8fbf-05b6013b0e1d.gif)

cc/ @viddo @xavijam

**Comment by xavijam** [comment]
Yes, this is duplicated, already fixed in https://github.com/CartoDB/cartodb/pull/4102

**Comment by xavijam** [comment]
thanks pablo!

**Comment by alonsogarciapablo** [comment]
Perfect! Thanks!
