### ISSUE TITLE
Design sticky header for when scrolling down

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#4115]
…by request after the in-person review. Currently we have this:
![screen shot 2015-06-18 at 12 47 43](https://cloud.githubusercontent.com/assets/978461/8229549/54f994c2-15b8-11e5-9350-f74fe435ddc9.png)

So if understood right, make a sticky sub-header with the selected tables+key columns "collapsed" when scrolling further down.

**Comment by josecruz** [comment]
Not sure about alignment but here's a first approach
![sticked header](https://cloud.githubusercontent.com/assets/596509/8285532/3c79f014-1904-11e5-8704-b00ddddce58b.png)

Here's a second (and better) approach: 
![sticked header](https://cloud.githubusercontent.com/assets/596509/8285977/2b9e2366-1907-11e5-84f7-80986c5642e0.png)

**Comment by saleiva** [comment]
Done, right?

**Comment by viddo** [comment]
There's no sticky header implemented yet, but I think I saw some design proposals somewhere but can't find it now. :/

**Comment by saleiva** [comment]
@josecruz
