### ISSUE TITLE
Implement new dropdown selector

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#4116]
From https://github.com/CartoDB/cartodb/issues/3819#issuecomment-111069016

![screen shot 2015-06-11 at 11 42 45](https://cloud.githubusercontent.com/assets/132149/8104184/009a22ae-102f-11e5-841b-dd1857958e62.png)

> Why?

> - Keep the common pattern on the dashboard when search icon is on the left.
> - Gives more air to the list so it gets less noisy
> - Removes borders within borders on the search module, so it becomes more lightweight.
> - Adds the metadata that I was asking for. User (only if MU) - this is the only case you can have 2 datasets with the same name, and modified date, it helps you to differentiate when you don't remember the exact name.
> - Adapted the icons so they work in small formats (we could still improve there)

Places to update:
- Merge datasets modal #3819
- Georeference modal #4158

**Comment by viddo** [comment]
cc @saleiva, @xavijam , can you append the list with what places that needs to be updated to have this new dropdown?

**Comment by viddo** [comment]
One problem I don't see is solved with this new dropdown after today's discussions: how to handle large datasets, e.g. 5ks user in the merge modal - how should "large" sets of data be handled in this dropdown? It would be useful if best/avg/worst scenarios are considered before I start to implement this.

**Comment by saleiva** [comment]
To be honest I don't see any easy solution for this than paginating and doing the search on the backend which would end in a very negative UX.

What I'd say is that we start with this one, and just in case we feel is needed, we prepare one ad-hoc for those cases where there are so much items to handle. 

We shouldn't break the UX for the other 99% of our users :)

**Comment by saleiva** [comment]
adding @josecruz so he can follow this task.
We need to make sure we have all existing versions designed ASAP.

**Comment by saleiva** [comment]
@josecruz ping! :)

**Comment by josecruz** [comment]
I designed this versions, which is missing?

![1st step_dropdown_selected_2](https://cloud.githubusercontent.com/assets/596509/9183244/f1377a04-3fa5-11e5-991e-70786def4584.png)
![map editor - metadata editor add field](https://cloud.githubusercontent.com/assets/596509/9183245/f13c0632-3fa5-11e5-8c50-7984e02c8c04.png)
![filters](https://cloud.githubusercontent.com/assets/596509/9183246/f1436080-3fa5-11e5-87fc-17121ec32b56.png)
![streetaddresses_maxcost copy](https://cloud.githubusercontent.com/assets/596509/9183247/f1474984-3fa5-11e5-9f2d-e5ee29534dcc.png)
![sql](https://cloud.githubusercontent.com/assets/596509/9183248/f14f11e6-3fa5-11e5-9f3c-262103ae16ea.png)

**Comment by saleiva** [comment]
Yes, there is one that s missing. The one on the geocoding modal, where you can also enter a text.
Also not sure if sizes and margins are correct on the types one.

**Comment by saleiva** [comment]
Also, not sure about the alignement when the rows doesn't have icon and there is an input search

**Comment by josecruz** [comment]
Search input list margins updated:

![filters](https://cloud.githubusercontent.com/assets/596509/9223332/139f9864-40f1-11e5-9162-7684db0717c1.png)

Missed state:
![streetaddresses_maxcost copy](https://cloud.githubusercontent.com/assets/596509/9223343/1f800ef2-40f1-11e5-8f0f-e37264a05ccc.png)

**Comment by saleiva** [comment]
Not sure I like the icon in the last state, the box doesn't mean anything, right?

**Comment by josecruz** [comment]
It's a textbox :(

![streetaddresses_maxcost copy](https://cloud.githubusercontent.com/assets/596509/9228933/ab1bc958-4112-11e5-823a-e58a3162d592.png)

**Comment by saleiva** [comment]
I prefer this one :)

**Comment by saleiva** [comment]
One idea is to try to play with the types indicator on the left so you can align the texts

**Comment by josecruz** [comment]
Updated all margins and icons position:

![map editor - metadata editor add field](https://cloud.githubusercontent.com/assets/596509/9231681/61b62588-4121-11e5-8590-46e3f01c3ce4.png)
![filters](https://cloud.githubusercontent.com/assets/596509/9231682/61bd2ac2-4121-11e5-82d7-df4d48030d34.png)
![streetaddresses_maxcost copy](https://cloud.githubusercontent.com/assets/596509/9231683/61c14c60-4121-11e5-8dd1-781e764509d0.png)
![1st step_dropdown_selected_2](https://cloud.githubusercontent.com/assets/596509/9231684/61c362e8-4121-11e5-9232-926c6f6b15af.png)
![sql](https://cloud.githubusercontent.com/assets/596509/9231685/61c75826-4121-11e5-9f4f-3aa00f2b56e9.png)

**Comment by saleiva** [comment]
Like!!

**Comment by josecruz** [comment]
Yay! Assigning it back to @viddo ^^

**Comment by josecruz** [comment]
What's left?
