### ISSUE TITLE
Design how to handle non-happy-cases for new merge modal

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#4117]
Related to new merge modal, the mockup basically only included the "happy cases" (error cases provided are not needed since they would never happen in the first place), need to go through them to decide how to handle them:

- [x] tables and columns are fetched async
  - how to indicate that is fetching on slower connections?
  - how to handle when a fetch fails for whatever reason?
- [x] user only has one table, so would have no table to merge from
- [x] user selects a right table that don't have any non-excluded columns, so no right-table columns are available
- [x] spatial merge: no allowed right-table column can be used to do a SUM or AVG merge

**Comment by josecruz** [comment]
_tables and columns are fetched async_
![fetching data](https://cloud.githubusercontent.com/assets/596509/8277798/7ba45ad8-18c6-11e5-960a-ce01d3f33da6.png)
![fetching data error](https://cloud.githubusercontent.com/assets/596509/8277797/7ba2bed0-18c6-11e5-9755-244dbff177f3.png)

_spatial merge: no allowed right-table column can be used to do a SUM or AVG merge_
![count - not available options](https://cloud.githubusercontent.com/assets/596509/8277837/ce9ffefe-18c6-11e5-994d-0ee6d79f1e5b.png)

_user only has one table, so would have no table to merge from_
This modal will appear right when you click on the merge columns button from the editor.
![one table error](https://cloud.githubusercontent.com/assets/596509/8284425/2229c308-18fd-11e5-9037-bba18eee805d.png)

_user selects a right table that don't have any non-excluded columns, so no right-table columns are available_
![right columns not available](https://cloud.githubusercontent.com/assets/596509/8284520/91cd14a8-18fd-11e5-90bc-883d7ec61bb0.png)

**Comment by viddo** [comment]
Regarding the first two screenshots:
- [fetching data](https://cloud.githubusercontent.com/assets/596509/8277798/7ba45ad8-18c6-11e5-960a-ce01d3f33da6.png) - everything is data in some sense, why not name it more specifically? I.e. "_fetching tables_" (while fetching tables) and "_fetching columns_" (when selecting a table)? 
- [fetching data error](https://cloud.githubusercontent.com/assets/596509/8277797/7ba2bed0-18c6-11e5-9755-244dbff177f3.png) - where should the "_go back_" button go? start of modal or the editor?

**Comment by josecruz** [comment]
**1st point:** agree
**2nd point**: I think it could redirect to the previous step (step 2 of 3)

**Comment by josecruz** [comment]
_user selects a right table that don't have any non-excluded columns, so no right-table columns are available_
Final version:
![right columns not available](https://cloud.githubusercontent.com/assets/596509/8314110/9f0510b8-19e7-11e5-94b1-f0820301b351.png)

**Comment by saleiva** [comment]
I'm also thinking on not showing the column selectors on the spatial merge, and just always select all columns. Does that make sense?

**Comment by saleiva** [comment]
@josecruz please remember to do some tests on the actual version prior to closing this.

**Comment by viddo** [comment]
+1 @saleiva said, and "close" as in create another issue (or simply update this title/desc) with a list of what and how you expect to change.

**Comment by josecruz** [comment]
I'll create a new issue with all the fixes that @saleiva and I talked yesterday

**Comment by viddo** [comment]
Weren't the proposed design solutions already done in #4277?

**Comment by josecruz** [comment]
@viddo Huh, right, I'll use that issue! We've found a few more fixes :(

**Comment by viddo** [comment]
Ok, just update the list and I'll attend it ASAP

**Comment by saleiva** [comment]
is this ready to be closed?

**Comment by viddo** [comment]
There's that edge-case that @josecruz created an issue for, apart from that they're all solved so I'll close it yeah
