### ISSUE TITLE
New "no georeferenced data" dialog

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#4131]
![screen shot 2015-06-19 at 13 18 42](https://cloud.githubusercontent.com/assets/132146/8252441/680f643c-1686-11e5-89f1-6490e8440d2d.png)

**Comment by viddo** [comment]
@saleiva @josecruz is there a sketch file for this one? Is it going to work in the same way as the current modal or do you have some other things in mind?

**Comment by saleiva** [comment]
Se could try to open the geocoding modal directly but with a small variation

**Comment by viddo** [comment]
Sure, you have something like this in mind? ![e7780220-0870-11e5-9380-908fdeedd271](https://cloud.githubusercontent.com/assets/978461/8302003/4554ba72-1993-11e5-8a5b-53b55564f63c.png) where "continue" would take the user to the standard [normal start](https://cloud.githubusercontent.com/assets/596509/7913523/e7780220-0870-11e5-9380-908fdeedd271.png)?
(sorry for the 30-sec design that do not fit with current styles ;))

**Comment by josecruz** [comment]
what do you think?
![no georeference data](https://cloud.githubusercontent.com/assets/596509/8304078/591a896e-19a3-11e5-84bd-274c5b32d745.png)

**Comment by josecruz** [comment]
About the alignment: Sketch column layout bug :(

Updated version: 
![no georeference data](https://cloud.githubusercontent.com/assets/596509/8304263/b896a098-19a4-11e5-8e04-40dd37de5bad.png)

**Comment by saleiva** [comment]
Like it tho. What about... 
- Changing the style of the button to the grey one.
- Making the text more uniform to remove some noise.

**Comment by josecruz** [comment]
Kind of:
![no georeference data](https://cloud.githubusercontent.com/assets/596509/8304469/67e70e74-19a6-11e5-87ee-b4e121a9606b.png)

**Comment by josecruz** [comment]
Updated with secondary buttons color:
![no georeference data](https://cloud.githubusercontent.com/assets/596509/8304495/9424d75a-19a6-11e5-9411-54c844693bd3.png)

**Comment by josecruz** [comment]
Final version by @saleiva 
![no georeference data](https://cloud.githubusercontent.com/assets/596509/8304650/3455e254-19a8-11e5-915b-845b41df764e.png)

**Comment by viddo** [comment]
Two questions:
1. For how long should this message be displayed? Until modal is closed? Or some interaction?
2. Should the modal work like the current one, i.e. be opened in this state when opening map?

**Comment by saleiva** [comment]
1. Whenever the table has non geo data.
2. Yep!
