### ISSUE TITLE
Torque time is not reflecting the browser datetime on the scrubbar

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#4135]
It seems to be GMT 0

**Comment by saleiva** [comment]
cc/ @javisantana so you can assign to whoever you want :)

**Comment by fdansv** [comment]
This is a cartodb.js issue. Will PR there.

**Comment by javisantana** [comment]
this is causing a lot of trouble for a lot of people, I'd think about reverting it cc @iriberri @saleiva @andrewxhill

**Comment by iriberri** [comment]
We're using UTC as the timezone for the imports, which means that we're not taking into account the timezone of the data itself (unless it comes from the Twitter datasource or it is specified) and we're adding an "uncontrolled" shift -- uncontroled in the sense that CartoDB is not taking care about the timezone in which the column data was created. 

Unless the data was actually in UTC values, all the rest of the cases will experience incorrect shifts.

**Comment by saleiva** [comment]
Can we have a meeting and talk about this? @miguelarias @Kartones. This is driving me crazy...

**Comment by saleiva** [comment]
@javisantana how many are a 'lot of people'?

**Comment by andrewxhill** [comment]
simon rogers and me are the ones i knew about.
here is the issue.
On a map of the world, it sort of makes sense that it would be in the
viewer's timezone.
In a map of London, wouldn't you imagine the time would be localized to
London?

Not that we are going to handle that automatically, but it puts us in a
strange spot. I think the easiest fix is to just show the timezone! :)

On Wed, Jul 1, 2015 at 7:13 AM, Sergio Álvarez Leiva <
notifications@github.com> wrote:

> @javisantana <https://github.com/javisantana> how many are a 'lot of
> people'?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/4135#issuecomment-117611977>.
>



-- 

andrewxhill <http://twitter.com/andrewxhill>
http://cartodb.com

**Comment by Kartones** [comment]
What has this to do with imports (I guess Twitter ones)? I don't understand, all imports act the same and have been always the same regarding datetime usage...

But if Torque now shows a different timezone (the browsers? one chosen by the user?), there's the issue, no? Why not allow a slider or something similar to choose a different timezone than the data's if that's what you tried to accomplish and made things more complex, wrong or whatever is happening?

**Comment by fdansv** [comment]
Without any knowledge on how the importer works, I'd say the default timezone shouldn't be UTC, but the importing user's local time. We can of course revert the changes related to this issue, but to me the underlying problem is the timezone set when data is uploaded.

**Comment by Kartones** [comment]
The importer has always been agnostic of timezone, importing all with UTC (except if you do SQL-based imports, the only ones supporting datetime with TZ). Even in the case of twitter imports, we "force" the user to calc. the diff between his timezone and UTC and assume UTC.

To force the importer to require a timezone it is a significant change for the users, we'd need a new endpoint and:
- Make the UI send via JS the browser timezone
- Force import API to have a `timezone` param
- What happens with sync tables? Do they store user's timezone first time and assume is always the same?
- How do we show in the editor the timezone? Just changing table data view to show datetime fields as with tz?
- Fallback for all existing data is keeping UTC right?


I don't think we're seeing the implications of changing the homogeneity we currently have of stored data (so becomes the "representation's responsability" to decide if to change from a uniform UTC TZ to another one). But if you think this change is the way to go and is worth the effort, plan a sprint for me to properly assest the implications and do it.

**Comment by miguelarias** [comment]
Totally agree with kartones and others that the data should always be in one single consistent time zone (let's assume gmt) it is the representation we are discussing.

I don't agree with Andrew (while I see he has a point ;)) on the hyper local visualization said having to be in local time (regardless of the time zone of the viewer). Elaine (twitter) asked the opposite as Simon.

I think that options would be;

1. Always show time zone that is being displayed in the slider. (Keeping the current behavior for time zone display in viewers end)

2. As second iteration give the map creator control, decide if you want to freeze the time zone in X or if you want it to be adapting to the viewers.

My 2 cents

**Comment by andrewxhill** [comment]
Here is the workflow that gets broken

* Import date with timestamp in EST but converted to UTC
* Create visualization, now timeslider shows UTC
* Slider not "viewer centric": Map maker wants to indicate a start time
(say of the Boston marathon) of 8AM, but the map shows 1PM.
* Slider is "viewer centric": Map makers talks about the start time in
narrative or other surrounding content, but the slider indicates whatever
timezone the map viewer is looking at it from

In the first option, Simon used to just do update timezone = timezone - x
hours, to fix it to whatever he intended to tell.
In the second, he has few options. If we go with the second, we need to
show the timezone at the least, but I think it is more restrictive.

Now, this map doesn't have a time slider, but look at the references to
timestamps in the content, this is where issues arise if you imagine the
map being torque instead

http://www.nytimes.com/interactive/2013/04/19/us/boston-marathon-manhunt.html


On Thu, Jul 2, 2015 at 3:13 AM, Miguel <notifications@github.com> wrote:

> Totally agree with kartones and others that the data should always be in
> one single consistent time zone (let's assume gmt) it is the representation
> we are discussing.
>
> I don't agree with Andrew (while I see he has a point ;)) on the hyper
> local visualization said having to be in local time (regardless of the time
> zone of the viewer). Elaine (twitter) asked the opposite as Simon.
>
> I think that options would be;
>
> 1. Always show time zone that is being displayed in the slider. (Keeping
> the current behavior for time zone display in viewers end)
>
> 2. As second iteration give the map creator control, decide if you want to
> freeze the time zone in X or if you want it to be adapting to the viewers.
>
> My 2 cents
>
> Sent from my iPhone
>
> > On Jul 1, 2015, at 2:34 PM, Kartones <notifications@github.com> wrote:
> >
> > What has this to do with imports (I guess Twitter ones)? I don't
> understand, all imports act the same and have been always the same
> regarding datetime usage...
> >
> > But if Torque now shows a different timezone (the browsers? one chosen
> by the user?), there's the issue, no? Why not allow a slider or something
> similar to choose a different timezone than the data's if that's what you
> tried to accomplish and made things more complex, wrong or whatever is
> happening?
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/4135#issuecomment-117937880>.
>



-- 

andrewxhill <http://twitter.com/andrewxhill>
http://cartodb.com
