### ISSUE TITLE
Redesign this step

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#4137]
Composition is weird, and is incorrect in the sequence. First select the column, then the operation depeding on that (sum or avg can only be done with Numeric columns)

![2nd step copy 2](https://cloud.githubusercontent.com/assets/132149/8256795/953e98d8-16a9-11e5-824a-65b30eb14123.png)

**Comment by josecruz** [comment]
so, if I understood correctly, you mean something like this:

1st state:
![2nd step copy 3](https://cloud.githubusercontent.com/assets/596509/8260772/0c265ef6-16c6-11e5-8f1a-1c9f957e0ba7.png)
2nd state:
![2nd step copy](https://cloud.githubusercontent.com/assets/596509/8260774/10a1844c-16c6-11e5-98e0-eca2bd98b1af.png)

**Comment by saleiva** [comment]
Yep

**Comment by saleiva** [comment]
hey @josecruz be sure everything is in place, and that @viddo know the changes
