### ISSUE TITLE
Add labels sandwich option to the editor

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#4148]
See [this (internal) wiki page](https://github.com/CartoDB/cartodb-management/wiki/BLT-labels) for more info.

**Comment by saleiva** [comment]
Based on my tests, labels work great 90% of the cases. 
The cases were they don't work that good is where having maps with just a few features (99% points) so the label itself covers the points... So based on this I'd propose to...

- We keep layers on top by default in our basemaps (Positron and Dark Matter) on those maps with more than XX(30?) points.
- We keep the `no_labels` option in the basemap selector.
- We add a new option `labels_below` on the basemaps selector.

If we play, we play :P

cc/ @andrewxhill @jatorre @javisantana

**Comment by andrewxhill** [comment]
pretty exciting man

**Comment by jatorre** [comment]
Good with me.

**Comment by saleiva** [comment]
Sumarizing after talking to @javisantana 

In the basemaps selector we will have the same plus
- Positron / Dark Matter_labels_ontop
- Positron / Dark Matter_light_nolabels
- Postron / Dark Matter default.

So only new maps will have the labels_ontop option selected by default following the rules explained before.

**Comment by saleiva** [comment]
And, the same with stamen tonner

**Comment by alonsogarciapablo** [comment]
Have you guys discussed how maps with a basemap with labels on top + torque layer should be rendered? Should labels be displayed on top of the torque layer in this case?

**Comment by javisantana** [comment]
in that case rendering should be done client side :)

**Comment by alonsogarciapablo** [comment]
I've updated the description of this issue with some of the work that needs to be done.

@saleiva we need some icons/thumbnails for these basemaps.

**Comment by saleiva** [comment]
Adding @mariodelvalle to the topic. Awesome.
@mariodelvalle what about adding an small letter to the already existing thumbnails?

**Comment by alonsogarciapablo** [comment]
:+1: I've moved the tasks [here](https://github.com/CartoDB/cartodb-management/wiki/BLT-labels#planning).

**Comment by mariodelvalle** [comment]
Hi guys today I'm going to do it. 
I have a doubt. Do thumbnails for basemaps of Stamen are the same as for CartoDB?

**Comment by alonsogarciapablo** [comment]
@mariodelvalle. They are different:

<img width="422" alt="screen shot 2015-07-03 at 10 30 06" src="https://cloud.githubusercontent.com/assets/390398/8495521/8609cc32-216e-11e5-81cf-add9668ff8ee.png">

@saleiva I'm not sure what combinations are we going to have there. We provide the following Stamen basemaps:

- Toner
- Toner Background
- Toner Lite
- Toner Lines
- Toner Hybrid
- Watercolor

**Comment by saleiva** [comment]
Toner also have a only labels layer, so we can add toner background + toner labels for that option :)

**Comment by alonsogarciapablo** [comment]
Closed by #4286.
