### ISSUE TITLE
New static map is not being instantiated when CartoCSS changes

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#4161]
**Steps**:

* Create any map, export its image:
![image](https://cloud.githubusercontent.com/assets/1730320/8302658/81c91c8c-1998-11e5-8923-87d24264db2b.png)
* Edit CartoCSS:
````
/** simple visualization */

#ne_admin0_v3_2{
  polygon-fill: #F84F40;
  polygon-opacity: 0.7;
  line-color: #000000;
  line-width: 0.5;
  line-opacity: 1;
}
``````
* Export image again, it doesn't reflect CartoCSS changes:
![image](https://cloud.githubusercontent.com/assets/1730320/8302668/98a3ae72-1998-11e5-98d0-03709396ff38.png)

**More:**
* Refreshing the page doesn't updates the export image map
* Changing the privacy of the map seems to be forcing the update
![image](https://cloud.githubusercontent.com/assets/1730320/8302693/b68c22ca-1998-11e5-8646-c1c85c63290e.png)

**Expected behaviour:** 
When the styles of a Map are edited, clicking on Export Image renders an updated map

**Current behaviour:**
When the styles of a Map are edited, those changes are not forced immediately

**Comment by iriberri** [comment]
SB/5722385

**Comment by iriberri** [comment]
cc @javisantana

**Comment by javisantana** [comment]
@javierarce I don't remember if the image is instanciated client side.

Looks like a cache invalidation problem but that wouldn't make any sense if the map is instanciated every export

**Comment by javierarce** [comment]
Yes, I ask for a new image every time. I follow the @iriberri's steps + reload the page, and the exported image was the original one, so I guess it could be cache invalidation.

**Comment by javierarce** [comment]
Another test I did: if you change the basemap and the CartoCSS and request a static map, the image will have the new basemap but the old CartoCSS.

**Comment by javisantana** [comment]
but the cartocss we send is the new or the old one?

**Comment by javierarce** [comment]
Oh, wait, I know what's happening. It's failing with namedmaps. With a public map/table it works for me.

**Comment by javisantana** [comment]
ok, looks like a cache issue @rochoa

**Comment by rochoa** [comment]
@javierarce I would give you my :heart: if you can give me the STR :smile:

**Comment by rochoa** [comment]
@Kartones was this finally related to https://github.com/CartoDB/cartodb/issues/4167 ?

**Comment by Kartones** [comment]
Indeed it was. I've just tried in live and it works correctly now, so closing issue.

**Comment by rochoa** [comment]
thanks :smile:
