### ISSUE TITLE
shapefile with non 4326 projection is being imported as empty

### ISSUE THREAD

**Issue by Hayleyr** [CartoDB/cartodb#4170]
A user attempted to import a shapefile with appropriate projections (they were portugese, but were recognized by GIS software). However in CartoDB it is being uploaded as a blank table. 

After converting the file from the portuguese projection to EPSG 4326 in QGIS the table was correctly created.

[check out the file here](http://gisbuild.sytes.net/labs/cont_concelhos_caop2014.zip)

![screen shot 2015-06-23 at 9 19 34 am](https://cloud.githubusercontent.com/assets/938865/8306839/016fdcc4-1989-11e5-88e7-9256b0ab3d99.png)

**Comment by Kartones** [comment]
File is no longer available so I cannot test that specific case :(

Were the file attributes/data in UTF-8? because a common issue is to have a different encoding than UTF-8

**Comment by ethervoid** [comment]
We are fixing this problem to provide more info in the error and don't let an empty table if we could import the file properly.

The main problem here is that the file is encoded using `WIN1252` and that doesn't work by now. The solution is to open the DBF file with `Openoffice` or `QGIS` and recoding to UTF8.
