### ISSUE TITLE
Notify owner of organization on signup errors

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#4179]
If user creation fails (because of quota, for example) it would be nice notifying to the owner of the organization. It should also give user better feedback, because quota errors just reload the page without any further information.

@saleiva what do you think about "notifying owner"? I'm, at least, giving better feedback to the user ASAP, since today @gfiorav and me have lost some time because an unnoticed quota error, but maybe you have an idea in mind for this kind of situations.

cc @xavijam

**Comment by saleiva** [comment]
Uhm... we could use the bell indicator on the header for this, right?

**Comment by juanignaciosl** [comment]
@saleiva it's probably the best place, but currently we have no actual notification support. In order to do this we need:
- Backend:
  - A Notification model and table.
  - Notification endpoint.
- Frontend:
  - Request notifications.
  - Open/discard notifications UI.

I'll assign this to you since this implies product design and prioritization. I've created a simpler #4915 for the straightforward error message, which should be done asap.

**Comment by saleiva** [comment]
hey @juanignaciosl long time
