### ISSUE TITLE
Google signup auto login after completion

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#4180]
When a user signs up in a organization with Google button he should be automatically logged in when user creation ends.

**Comment by juanignaciosl** [comment]
cc @Kartones I'll work on this propagation, I can also take a look at LDAP as well

**Comment by Kartones** [comment]
Well, any can work, either you or me doing both, but nice! /cc @saleiva

**Comment by saleiva** [comment]
thanks! :)
