### ISSUE TITLE
No display 'Delete datasets' button

### ISSUE THREAD

**Issue by dcedena** [CartoDB/cartodb#4185]
Where is the Delete button?

Info Browser: Chrome Versión 43.0.2357.130 m

![my_datasets](https://cloud.githubusercontent.com/assets/1241094/8328322/22a4d9ca-1a70-11e5-9f13-34cbc8214f63.png)

**Comment by juanignaciosl** [comment]
@dcedena that's not the dashboard but the new map modal screen. Close that modal (top right X) and then go to your datasets with the top dropdown of the screenshot.


![screen shot 2015-06-24 at 12 58 14](https://cloud.githubusercontent.com/assets/932968/8328399/b7b94d70-1a70-11e5-8c5a-245165adad82.png)

You'll be able to delete datasets there.
