### ISSUE TITLE
dashboard: immediately after deleting datasets quota isn't freed and can't import

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#4188]
**steps to reproduce**

- upload datasets untill ran out of quota
- delete datasets in the dashboard
- refresh
- try to upload dataset

**expected behaviour**

- upload dataset

**actual behaviour**

- quota error

![screen shot 2015-06-24 at 15 36 43](https://cloud.githubusercontent.com/assets/36676/8331128/e1934afe-1a86-11e5-8389-f02e904f09ca.png)

**Comment by Kartones** [comment]
Did you free enough space?

Quota before dataset duplication: 152.43MB
Quota just after dataset duplication: 160.71MB
Quota just after deleting the newly created duplicate dataset: 152.43MB

Each time a table gets deleted the quota trigger updates user quota instantly, and we don't cache that value...

**Comment by matallo** [comment]
I was just removing the maps

closing, then
