### ISSUE TITLE
Long-name dataset imports but polygons don't show up

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#4194]
To replicate: name a csv something over 63 characters...polygons don't show as expected:
https://team.cartodb.com/u/stephaniemongon/viz/a8cd461a-1abe-11e5-b158-0e853d047bba/public_map

see errors:
![ghtest_longnamepolys_1_err](https://cloud.githubusercontent.com/assets/1779444/8343026/3b714482-1a9f-11e5-9ef3-550b5c604506.png)

When you change the name of same csv to something shorter it imports and polygons show:
https://team.cartodb.com/u/stephaniemongon/viz/95b9f298-1abf-11e5-af42-0e018d66dc29/public_map

This one has errors too tho for comparison:
![ghtest_longnamepolys_2_err](https://cloud.githubusercontent.com/assets/1779444/8343031/47192430-1a9f-11e5-89c0-9a091202532a.png)

**Comment by iriberri** [comment]
Duplicated https://github.com/CartoDB/cartodb/issues/3808
