### ISSUE TITLE
Unify copys and/or buttons in new modals

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#4196]
![01](https://cloud.githubusercontent.com/assets/1214201/8350341/17e3a736-1b25-11e5-94c9-7b089afb7007.png)
![02](https://cloud.githubusercontent.com/assets/1214201/8350342/17e42c92-1b25-11e5-9dfc-9fc86a12f00c.png)
![03](https://cloud.githubusercontent.com/assets/1214201/8350343/17e69ff4-1b25-11e5-8df1-b3a1967bce6e.png)

**Comment by saleiva** [comment]
So...
- 'CLOSE' should never be present in the bottom left.
- Not sure if removing the CLOSE button when being the only action.

**Comment by saleiva** [comment]
@josecruz can you take a look at the actual UI to start unifying this?

**Comment by josecruz** [comment]
We only keep the button on the bottom area when is the only action. I'll create a new issue with the list of modal that we need to modify.

**Comment by josecruz** [comment]
Created new issue here #4378
