### ISSUE TITLE
Wrong ArcGIS connector name & copy

### ISSUE THREAD

**Issue by Kartones** [CartoDB/cartodb#4204]
![image](https://cloud.githubusercontent.com/assets/2085449/8356217/4fb051f8-1b54-11e5-8a31-d0c5c2baa411.png)

This is wrong because what we support is **ArcGis Server**, not ArcGis Online, AO won't ever work, so we're misleading our users. This probably has been like this since the redesign but... anyway should be fixed.

/cc @javisantana

**Comment by vhamer** [comment]
thanks for making this issue @Kartones - i've submitted a pull request to change the language in our Docs as well.

**Comment by chriswhong** [comment]
What difference does it make whether it is ArcGIS online or ArcGIS server?  Isn't a web-accessible FeatureService the same no matter where it is being served from?

**Comment by Kartones** [comment]
There seems to be some API changes or configuration parameters different because we tried with one ArcGIS Online and didn't worked, but there hasn't been assigned time to research on why doesn't and how hard is to provide support for both.

Probably the data is indeed the same, but the "handshake", the steps before seem to differ.

**Comment by Kartones** [comment]
As nobody else changes it, I'll inmediately fix the website copy, because we still have it wrong in **production** :disappointed:
