### ISSUE TITLE
Legend is broken 

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#4206]
In this public map https://pq-clm.cartodb.com/viz/899b7abc-1926-11e5-bc17-0e43f3deba5a/public_map the legend is broken

![image](https://cloud.githubusercontent.com/assets/1214201/8357931/c7f0ef16-1b5d-11e5-94d3-39c0b9ef6849.png)

**Comment by xavijam** [comment]
We will revisit this with the new editor. Closing :).
