### ISSUE TITLE
Design UI to normalize maps in pecan

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#4208]
@ohasselblad & @andrewxhill talked about adding an interface to normalize the maps by a column or by area (if the map contains polygons).

**Comment by saleiva** [comment]
this has implications on the wizards. If we add this step now we would need to; a) create a new column and therefore change the data structure, b) apply and wrap a query on the SQL panel but that would be removed as soon as a filter or another query is done.

I'd prefer to prepare for this the new editor

**Comment by andrewxhill** [comment]
we might get a little but laughed at i'm afraid if we are suggesting
polygons choropleths without any normalization...

On Fri, Jun 26, 2015 at 9:17 AM, Sergio Álvarez Leiva <
notifications@github.com> wrote:

> this has implications on the wizards. If we add this step now we would
> need to; a) create a new column and therefore change the data structure, b)
> apply and wrap a query on the SQL panel but that would be removed as soon
> as a filter or another query is done.
>
> I'd prefer to prepare for this the new editor
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/4208#issuecomment-115679133>.
>



-- 

andrewxhill <http://twitter.com/andrewxhill>
http://cartodb.com

**Comment by saleiva** [comment]
ha! that's what we suggest now with the wizard mate... The thing is that adapting the editor for this might take 2 to 3 months now...
