### ISSUE TITLE
Missing tables in dashboard when they're added from ogr2ogr

### ISSUE THREAD

**Issue by alasarr** [CartoDB/cartodb#4210]
I've tried to import a table to CartoDB from a Postgis database using ogr2ogr.

```ogr2ogr -t_srs EPSG:4326 --config CARTODB_API_KEY XXX -f CartoDB "CartoDB:alasarr" PG:"host=192.168.59.103 user=postgres dbname=test port=5433" "countries_world"```

After that I go to CartoDB dashboard-> datasets and the layer is not there:
![captura de pantalla 2015-06-26 a las 13 11 14](https://cloud.githubusercontent.com/assets/1161870/8376268/6823c51a-1c05-11e5-99ec-d9b377317813.png)

But the layer is really there and it's drawn in a visualization:

![captura de pantalla 2015-06-26 a las 13 09 50](https://cloud.githubusercontent.com/assets/1161870/8376274/846b2d1c-1c05-11e5-93be-eb7c1bd5698c.png)

**Comment by iriberri** [comment]
You might need to CartoDBfy your tables: 

https://github.com/CartoDB/cartodb/wiki/creating-tables-though-the-SQL-API

**Comment by alasarr** [comment]
Thanks a lot for the help.

It's odd because the table already has a cartodb_id. I've also tried to CartoDBfy the table but still missing at datasets section:
```select cdb_cartodbfytable('alasarr', 'countries_world');``` 

According to http://www.gdal.org/drv_cartodb.html ogr2ogr CartoDBfy the tables by default.

**Comment by padawannn** [comment]
I tried to import a shape file and works well using ogr2ogr.

 ogr2ogr \
  --config CARTODB_API_KEY XXX \
  -t_srs EPSG:4326 \
  -f CartoDB \
  "CartoDB:javieraragon" \
 file.shp -nln table_name

**Comment by alasarr** [comment]
it works now. I think it could be removed.
