### ISSUE TITLE
ON/OFF switch jump

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#4215]
Reproduce:
Switch off the *merge all columns toggle* and then switch on the individual toggles:

![untitled](https://cloud.githubusercontent.com/assets/596509/8404480/a9fa485c-1e4d-11e5-8eb1-ae5456357582.gif)

**Comment by viddo** [comment]
Thx for reporting that one :+1:

**Comment by josecruz** [comment]
Np! :+1:
