### ISSUE TITLE
Non-retina icons when creating a new empty map

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#4216]
Reproduce:
**On retina**
New map > Create Empty Map
![pasted_image_at_2015_06_29_10_55_am_720](https://cloud.githubusercontent.com/assets/596509/8404581/657d5074-1e4e-11e5-8498-70d75588f2f5.png)

- [ ] Icons ready to export in svg in `map-editor-1.5.sketch` artboard: `Map editor - Start adding features`
- [ ] Change blue header icon to `#666666`

**Comment by saleiva** [comment]
arce
