### ISSUE TITLE
Improve the way we set space quota in the "organization admin"

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#4227]
![screen shot 2015-06-29 at 15 37 34](https://cloud.githubusercontent.com/assets/132146/8409005/c800d362-1e74-11e5-8b5f-7ee6895d86b6.png)

**Comment by josecruz** [comment]
My idea is to move the slider directly to the user quota, kind of:
![screen shot 2015-07-02 at 7 15 14 pm](https://cloud.githubusercontent.com/assets/596509/8483129/d0549be4-20ee-11e5-9604-f86b0dd5753c.png)

and then when it's active (the popup will show on hover as well):
![screen shot 2015-07-02 at 7 14 56 pm](https://cloud.githubusercontent.com/assets/596509/8483134/e038c710-20ee-11e5-916c-8a2391f080e1.png)

Also, I made a small separation between the two colors, what do you think?

**Comment by saleiva** [comment]
Not valid. Did you talk with @xavijam before working on this? We need an input for entering the quota on MB, and we need to show the quota on MB as well

**Comment by josecruz** [comment]
Kind of this?

![screen shot 2015-07-03 at 11 28 03 am](https://cloud.githubusercontent.com/assets/596509/8496585/a218b124-2176-11e5-9b1a-1c624ea09c1a.png)

**Comment by saleiva** [comment]
Uhm... it's not a bad solution. @xavijam ?

**Comment by xavijam** [comment]
I told him I like it, bad part is I have to add some validations (not valid characters or input bigger than available quota) but for me :+1:.

**Comment by josecruz** [comment]
Perfect. 

Any state missing here?

**Comment by saleiva** [comment]
@xavijam what about not allowing to type anything that is not a number?

**Comment by xavijam** [comment]
Yet, that's one, another (as jose suggested) would be to change input to quota limit if user types a value bigger than the allowed one.

**Comment by saleiva** [comment]
Yep

**Comment by josecruz** [comment]
This design is on `multiuser-0.3.sketch`

I also suggest a small change on the `Allow geocoding` switch:
Change label color when it's allowed and when it's not:
![screen shot 2015-07-03 at 6 17 52 pm](https://cloud.githubusercontent.com/assets/596509/8502409/e7c235c2-21af-11e5-8281-43ead40cd5b7.png)
![screen shot 2015-07-03 at 6 17 58 pm](https://cloud.githubusercontent.com/assets/596509/8502411/e93174c2-21af-11e5-8e7f-17b0dda86f51.png)

**Comment by xavijam** [comment]
Ticket for @MariaCheca who is in charge of the new account redesign.  cc @viddo

**Comment by viddo** [comment]
re: Geocoder switch, should be able to use [`.Toggle`](https://github.com/CartoDB/cartodb/blame/master/app/assets/stylesheets/common/forms/toggler.css.scss#L18) as-is that already have this visual states defined

**Comment by xavijam** [comment]
Closing since there is an issue to implement it -> https://github.com/CartoDB/cartodb/issues/5363
