### ISSUE TITLE
Change "Manage your seats" text into "XX/XX users"

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#4228]
No color change, just text.

**Comment by xavijam** [comment]
@saleiva, I feel it looks weird, doesn't it?
![screen shot 2015-06-29 at 16 38 38](https://cloud.githubusercontent.com/assets/132146/8410262/540dbb2e-1e7d-11e5-8eb4-1d58b13f9697.png)

**Comment by xavijam** [comment]
In any case, if this is changed, @matallo I'll need you to change it in central as well.

**Comment by saleiva** [comment]
Is perfect ;)
