### ISSUE TITLE
Visualization search + likes

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#4232]
During some unrelated QA check @rochoa found that "Search in liked view: results are restricted to liked" did not work as expected.

1.- Search box should also search in your liked datasets/maps (currently it only searches on datasets/maps you own).
2.- If you're in "Liked" tab search should be restricted to liked.

Do you agree, @saleiva?

**Comment by juanignaciosl** [comment]
This happens because of sent URL:

http://central-user-1.localhost.lan:3000/api/v1/viz/?tag_name=&q=Gues&page=1&type=&exclude_shared=false&per_page=9&tags=&shared=yes&locked=null&only_liked=null&order=updated_at&types=derived

Which should sent `only_liked=true`.

http://central-user-1.localhost.lan:3000/api/v1/viz/?tag_name=&q=Gues&page=1&type=&exclude_shared=false&per_page=9&tags=&shared=yes&locked=null&only_liked=true&order=updated_at&types=derived

**Comment by xavijam** [comment]
No no, search is generic, it searches everywhere, not in the context the user is. And if we want to include liked datasets/maps we will need a new parameter, not ```only_liked```. It should be ```liked``` with 3 options, ```yes```, ```no``` or ```only```, as we do with ```shared``` parameter, for example.

**Comment by juanignaciosl** [comment]
Ok, I'll fix smoke test templates then.
