### ISSUE TITLE
Wrong layout/icons on new georeference results modal

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#4236]
use new icons and layout:

- [x] no georeferenced data (points)
<img width="711" alt="screen shot 2015-07-17 at 15 57 22" src="https://cloud.githubusercontent.com/assets/978461/8748759/f2692d58-2c9c-11e5-80b1-806ceed6aab5.png">

- [x] no georeferenced data (polygons)
<img width="705" alt="screen shot 2015-07-17 at 15 57 28" src="https://cloud.githubusercontent.com/assets/978461/8748712/b08d4374-2c9c-11e5-82bc-5fe5875ecd55.png">

- [x] geocoding succesful - default
<img width="603" alt="screen shot 2015-07-17 at 15 57 53" src="https://cloud.githubusercontent.com/assets/978461/8748709/b08af5ce-2c9c-11e5-92d8-0b0a51fe226c.png">

- [x] geocoding successful - no cost
<img width="708" alt="screen shot 2015-07-17 at 15 57 41" src="https://cloud.githubusercontent.com/assets/978461/8748760/f269f65c-2c9c-11e5-894c-d0c953c784c8.png">

- [x] geocoding successful - cost
<img width="769" alt="screen shot 2015-07-17 at 15 57 47" src="https://cloud.githubusercontent.com/assets/978461/8748713/b08e530e-2c9c-11e5-8706-8e386e61a66f.png">

**Comment by saleiva** [comment]
Remember it depends if they are points or polygons

**Comment by viddo** [comment]
![screen shot 2015-06-30 at 16 36 50](https://cloud.githubusercontent.com/assets/978461/8433481/582a2fac-1f46-11e5-9524-832ede3c1df9.png) looks like this one doesn't match either

**Comment by josecruz** [comment]
We have a similar version on the last file version that I sent to slack
![screen shot 2015-06-30 at 4 57 15 pm](https://cloud.githubusercontent.com/assets/596509/8433968/1a9f0d8a-1f49-11e5-8d36-94680de4fd31.png)

**Comment by viddo** [comment]
Yep, I saw it, just added the screenshot above to remember fixing it when updating this

**Comment by xavijam** [comment]
Please, @viddo, take care of this plural bug.
![screen shot 2015-07-02 at 11 21 01](https://cloud.githubusercontent.com/assets/132146/8473833/a01cc20e-20ac-11e5-85e0-4a4e0a3c0035.png)

Thanks

**Comment by viddo** [comment]
@josecruz updated the description with the new screens I found in the sketch file, are there screens missing or other things that are expected to be fixed here that is not already listed?

**Comment by viddo** [comment]
To avoid having redo things again: I'm observing that the margins are not consistent with existing modals
- the icon + title are varying between 16px and 11px, in the existing modals it's always 20px.
- the title is 16px, in existing modals they're all 18px
- the description text is 14px, in the existing modals they're all 15px
- the go back button text has color `#666`, in existing modals they're all `#bbb`

I find it weird that we are not consistent in the existing styles. I'm all for changing but shouldn't we update all places then?

**Comment by josecruz** [comment]
Okay, so changing it on the sketch file. Probably the rest of the modals on the sketch files aren't updated as well (I just copy/pasted them from another sketch file). Thanks for spotting this! Let's use production styles

**Comment by viddo** [comment]
merged in #4567
