### ISSUE TITLE
Error sorting layers

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#4241]
This error was detected while doing the QA for #4138, but it's unrelated and has been reproduced with current master.

1.- Create a new empty public map.
2.- Add one orange polygon by hand.
3.- Create a new empty layer.
4.- Add one polygon by hand, overlapping partially the first one and change color to blue.
5.- Open the public map in an incognito window. Everything's ok.
6.- Change the order of the layers in the editor.
7.- Reload the public map. Layer order hasn't changed.

cc @xavijam @alonsogarciapablo 

It might not happen the first time. If you change the order and it seems to work, change it again, reload, change it again and reload again, it happens.

@javisantana : what I've seen is that triggered PUT requests are not ok: there're two PUTs to the same id, although it looks like when it works PUTs should be to different ids. So, the backend doesn't update the order, and the three layers (tiled, cartodb, cartodb) of the map get 0, 2, 2.

Making tables public make no difference.

No, when the map is wrong header is `X-Cache:MISS`.

**Comment by javisantana** [comment]
what is the order of the layers saved in backend? 
are the tables public?
is the map cached the second time?

**Comment by xavijam** [comment]
So finally this issue is gonna be solved with https://github.com/CartoDB/cartodb/issues/4016.
