### ISSUE TITLE
Maps should be able to have a `tiled` layer on top of the stack of layers

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#4256]
Right now, [we're limiting the number of `tiled` layers in maps to 1](https://github.com/CartoDB/cartodb/blob/18da90b2e58d4d45b0edf7949abd3d9a912dde4a/app/models/map.rb#L270-L272). For some basemaps, we're going to add a `tiled` layer on top with labels (see #4148 for more info). The backend needs to support only one base layer ('tiled', 'background', 'gmapsbase', 'wms'), but it should also support a `tiled` layer at the top of the stack of layers. The backend could check that this layer is being added at the top and not between any layers.

cc// @kartones @javisantana

**Comment by Kartones** [comment]
Branch: `4256-tiled-layer-on-top` (parent is `layers-on-top`)
