### ISSUE TITLE
viz.json presenter should handle layers with labels

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#4257]
In #4148, we are adding a `tiled` layer with labels to some maps. This layer will always be at the top, but the backend should decide how `cartodb.js` must render a map with labels on top. There are two different scenarios **for maps that have a layer of labels at the top**:

**1. Map has a torque layer**

In this scenario, `cartodb.js` will need to render the labels on top of the torque layers. **The backend shouldn't do anything special with the layers**.

**2. Map doesn't have a torque layer**

When no torque layers are present, labels can be merged/blended with mapnik layers so that the tiler can render all layers together (mapnik layers + http layer with labels). In this case **the backend must include the `tiled layer` with the labels in the/a `named_map` or `layer_group` with the `mapnik` layers.

cc// @javisantana @Kartones

**Comment by Kartones** [comment]
Branch `4257-vizjson-labels-on-top` (created from `labels-on-top`)

**Comment by Kartones** [comment]
Closed for the time being, until a decision is made of how to handle named maps + labels on top
