### ISSUE TITLE
importer doesn't work via url but it does downloading and dragging the file

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#4271]
**str**

- go to dashboard
- click "New map"
- choose "connect"
- paste http://londondatastore-upload.s3.amazonaws.com/dataset/recorded-crime-summary-data-london-borough-level/boro.csv

**expected behaviour**

- import file

**actual behaviour**

- error: Unknown (99999)

it works if you download and drag the file to the dashboard

**Comment by iriberri** [comment]
The file is being downloaded as a XLS file in CartoDB, as its Content Type is "application/vnd.ms-excel" (both in HEAD and GET requests). When CartoDB tries to open the Excel, as it's not actually an excel but a CSV it gives a formatting error. (the typical: 2015-07-07 14:59:37 UTC: NoMethodError: undefined method `close' for 0:Fixnum)
