### ISSUE TITLE
geocoder doesn't work for London boroughs

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#4274]
**str**

- go to dashboard
- import dataset with boroughs [0]
- geocode
- adm. regions
- select "boroughs column" and London in Free text
- select polygons

**expected behaviour**

- geocode by borough

**actual behaviour**

![screen shot 2015-07-02 at 15 07 25](https://cloud.githubusercontent.com/assets/36676/8477698/709d7472-20cc-11e5-96ad-8f992a48d42b.png)

it works if you select address, though (georeferenced points)

[0] http://data.london.gov.uk/dataset/recorded-crime-summary-data-london-borough-level/resource/0fd26d03-fc68-4063-8822-3698a40d4333

**Comment by iriberri** [comment]
Sorry, but only administrative level 1 regions are supported. Visually, it's something like this:

![image](https://cloud.githubusercontent.com/assets/1730320/8478044/168b9330-20cf-11e5-8f44-7e550a8f9ecd.png)

which corresponds to the Adm1 table from Natural Earth Data.
