### ISSUE TITLE
Geocode checkbox

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#4275]
![screen_shot_2015-07-02_at_12 49 53_360](https://cloud.githubusercontent.com/assets/596509/8478419/8d3c3bd6-20d1-11e5-902a-37fb785fa718.png)

**Comment by josecruz** [comment]
I followed @viddo's suggestion and placed that on the footer (I was trying different positions and this one is the one which looks best). 

The only thing is that if your task is gonna to have some cost, we could disable the continue button until the user set the checkbox.

![streetaddresses_maxcost copy](https://cloud.githubusercontent.com/assets/596509/8497659/44cfd728-217f-11e5-8c1b-5ce2996edd39.png)

Or, we could show a confirmation modal instead.
![charges copy 2](https://cloud.githubusercontent.com/assets/596509/8497842/c26c43b4-2180-11e5-9c91-5b56c4bd0ba5.jpg)

**Comment by viddo** [comment]
re: disabling/enabling continue button is already accounted for (each tab has its own prerequisites)

btw, having the agree-to-tos checkbox will clash with the other issue I have to fix for this modal, see #3958 :+1: 

![2nd try](https://cloud.githubusercontent.com/assets/132149/8354381/f781e598-1b47-11e5-8f3e-87d7762604e2.png)

**Comment by saleiva** [comment]
@josecruz I propose we remove the check here since we will have a extra step for that

**Comment by viddo** [comment]
@saleiva so, I'll implement the 2nd proposal or do you have something else in mind?

**Comment by saleiva** [comment]
Yep, is my fav. :)

**Comment by viddo** [comment]
Okidoki, but does it makes sense to duplicate the footer info then?

**Comment by viddo** [comment]
edit: ok, but then does it make sense to display the cost info in the footer? or should that still be rendered there?

**Comment by josecruz** [comment]
I think it should stay there because that modal is just a confirmation step. You agree @saleiva ?

**Comment by saleiva** [comment]
+1 on what Jose says

**Comment by viddo** [comment]
okidoki :+1:

**Comment by viddo** [comment]
FYI, implemented this confirm-terms-of-service modal as part of the #4158, so no need to create another issue

**Comment by saleiva** [comment]
@viddo can we  close this then?

**Comment by viddo** [comment]
sure
