### ISSUE TITLE
Collect stats to measure the use of pecan

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#4276]

**Comment by andrewxhill** [comment]
Hey guys. Here is what I need

Store the complete profile for each column, it should include

* stas: stddiv, mean, extents, and others returned
* shape calculated
* number rows
* number of nulls
* row type
* geom type
* density
* column name
* run id (so i can associate different profiles back together)
* was it chosen by the user (1,2)

Ideally I'd like to get two profiles from each map (or a sample of maps). I'd like the profile that the user chose and a random second profile. 

From this, we should be able to test whether we can train a better model than our weighting pretty quickly.

**Comment by javierarce** [comment]
Ok! 

@javisantana's idea was to store a flag in the layer that contained an active pecan. We'll be doing both things, but I guess that we'll need to store the info in two different places (@matallo: do you think we can store Andrew's data in HubSpot?)

**Comment by matallo** [comment]
Indeed, we can discuss it tomorrow if that's fine to you, but in order to store properties maybe we'll have to implement an endpoint, only events can be shared with js

**Comment by andrewxhill** [comment]
that'd be perf!

**Comment by javierarce** [comment]
Ok, so for this to work we'll need to make some changes in the backend to store that information. We'll use the same approach as with the importer stats.

Are we all OK with the list of stats that Andrew proposes? 

/cc @saleiva @javisantana

**Comment by ohasselblad** [comment]
adding myself to track this

**Comment by andrewxhill** [comment]
Can we create a set of "style ids" or something... so that we know what style was chosen by the user? What i'm thinking is that, let's say users never select heatmaps ever. We should fix them or remove them from all suggested maps. Just as an example.

**Comment by andrewxhill** [comment]
there is another stat we would like that probably don't belong in the same data object, well, i don't mind where they end up but we need to monitor these from our internal dash

1. number of pecan maps created (so number of times a map is selected from pecan)
2. number of pecan maps that are published directly (so no changes to the wizard)

**Comment by javierarce** [comment]
I have a question, @andrewxhill regarding these two params:

```
- run id (so i can associate different profiles back together)
- was it chosen by the user (1,2)
```

What would be a run id? A random number? Or something like table_name + username?
What does it mean the second param?

**Comment by andrewxhill** [comment]
Run id actually could just be map_id actually. Just so that if a user ever chooses pecan twice we know, but we aren't letting a user do that right now. so scrap it.

'was it chose by the user...' what i mean here is, which of the pecan choices was chosen, our first pick, second, pick or third pick map. Our goal will be to slowly move closer to first pick always being chosen.

A

**Comment by javierarce** [comment]
Ok, I think we can store the map_id even if not make sense right now.

Regarding the order of the choices… we show the pecan cards in a random order (we put the torque and heatmap first, but the following cards appear in different positions depending on when the async call is finished)

**Comment by andrewxhill** [comment]
right, so let's collect it because when we release new versions it wont be
random anymore. it will be a good baseline to see if we can beat random ;)

On Thu, Aug 13, 2015 at 10:50 AM, Javier Arce <notifications@github.com>
wrote:

> Ok, I think we can store the map_id even if not make sense right now.
>
> Regarding the order of the choices… we show the pecan cards in a random
> order (we put the torque and heatmap first, but the following cards appear
> in different positions depending on when the async call is finished)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/4276#issuecomment-130717361>.
>



-- 

andrewxhill <http://twitter.com/andrewxhill>
http://cartodb.com
