### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by dhthong92** [CartoDB/cartodb#4285]
Dear sir,
I have followed the install instruction in your github, step by step and everything's okay, no error has occurred. But when I connect to my domain (here is development.localhost.lan), nothing displayed. I've attached the screenshot below. Seem like the dashboard did not loaded correctly. I've try the solution in Common problem session too by reinstall cdb.js but nothing changed. My OS is Ubuntu 14.04 x64. Any idea?
![screenshot from 2015-07-03 15 48 37](https://cloud.githubusercontent.com/assets/8455407/8496105/d59296a2-219c-11e5-85ea-73380d01bc0a.png)

**Comment by javisantana** [comment]
looks like you want to go to http://development.localhost.lan:3000/dashboard

this repo is not for installation problems, you can use our mailing list for this: https://groups.google.com/forum/#!forum/cartodb

**Comment by dhthong92** [comment]
Thanks for your help! Because when I connecto to  http://development.localhost.lan:3000/, it redirect to  http://development.localhost.lan:3000/maps and in server console, I saw it was authenticated automacally. So I didn't think I have to go to the dashboard and login again. My fault, sorry for my invalid post. Thanks for your help again!

**Comment by javisantana** [comment]
it redirects to /maps in case of not being auth so looks like there was some problem
