### ISSUE TITLE
Wrong number of selected maps when you have maps of other users in the selection

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/cartodb#4288]
@xavijam @juanignaciosl 

Wrong number of selected maps when you have maps of other users in the selection

## Process

1. You should have liked maps from other users and your own maps
2. Select one of your maps (other user maps can't be selected)
3. Click on select all option

## Expected result

The count of selected maps should show only de selected maps, your maps

## Current result

The counter is including the maps from other users too

## Screenshot

<img width="1280" alt="bug_maps_selection" src="https://cloud.githubusercontent.com/assets/741240/8497164/4316e646-217b-11e5-9a2e-12abbc0e08a0.png">

**Comment by xavijam** [comment]
Much appreciated ;)
