### ISSUE TITLE
Trying to filter by tag the data library in the new dataset view if the page is higher than first it fails

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/cartodb#4291]
@xavijam @juanignaciosl

Trying to filter by tag the data library in the new dataset view if the page is higher than first it fails

## Context

When you are in the dataset view and try to sort the data library using the tags there isn't problem if you are in the first page but if you change for example to the page 2 and try to sort, you get and empty list.

## Process

1. Go to `New Dataset`
2. Go to `Data Library`
3. Go down the page and go to page 2
4. Try to filter by tag

## Expected result

Should show all the datasets fot that tag paginated

## Current result

Empty list

## Screenshot

<img width="1280" alt="captura de pantalla 2015-07-03 a las 13 44 03" src="https://cloud.githubusercontent.com/assets/741240/8498775/3201e8dc-218b-11e5-80ee-86858ba9a2a4.png">

**Comment by juanignaciosl** [comment]
Ok, it's requesting "current page" instead of reseting (like Dataset or Maps view do): `https://team.cartodb.com/u/juanignaciosl/api/v1/viz/?tag_name=&q=&page=2&type=&exclude_shared=false&per_page=20&locked=&tags=US%20Census&shared=no&only_liked=false&order=updated_at&types=remote`.
