### ISSUE TITLE
Add a visual tip to indicate the search box for when not having datasets and being prompted to the 'data library list'

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#4292]

**Comment by saleiva** [comment]
<img width="1232" alt="screen shot 2015-07-03 at 14 47 59" src="https://cloud.githubusercontent.com/assets/132149/8499389/866638c2-2192-11e5-8b1f-f3a99605907e.png">

**Comment by saleiva** [comment]
<img width="1232" alt="screen shot 2015-07-03 at 14 47 59" src="https://cloud.githubusercontent.com/assets/132149/8499393/936f128c-2192-11e5-9ae8-5aa68963d844.png">

**Comment by josecruz** [comment]
Okay so I just applied @saleiva and @carlostallon 's feedback.

![dashboard copy](https://cloud.githubusercontent.com/assets/596509/8526406/e0afd2d6-2406-11e5-8b90-65dc320ecffc.png)

I've modified browser's shadow in `y-coord` and added a border as well. We could use a png or update 1 css class.

**Comment by saleiva** [comment]
Just a couple of things:
- We don't say connect data, we always say connect dataset.
- I'd highlight the search link but I'd not change the color, it can be even more confusing.

**Comment by saleiva** [comment]
Also, this is shown too on the connect-dataset modal.

**Comment by carlostallon** [comment]
Like it!

2015-07-06 18:06 GMT+02:00 Sergio Álvarez Leiva <notifications@github.com>:

> Also, this is shown too on the connect-dataset modal.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/4292#issuecomment-118910800>.
>



-- 
Carlos Tallón
Designer & Baker

**Comment by josecruz** [comment]
Uhmm should we change the browser image here?
![create - new dataset - dropbox file list copy](https://cloud.githubusercontent.com/assets/596509/8544774/835a251c-24a8-11e5-8b04-ba85cf1e115f.png)

**Comment by josecruz** [comment]
Last version after @saleiva's feedback:

![dashboard copy](https://cloud.githubusercontent.com/assets/596509/8571528/b21318a2-2587-11e5-8346-87ca6d3ccf07.png)
![create - new dataset - dropbox file list copy](https://cloud.githubusercontent.com/assets/596509/8571531/b3d93f5e-2587-11e5-8005-72e225eb895b.png)

**Comment by saleiva** [comment]
:heart:

**Comment by carlostallon** [comment]
qué chulo!

2015-07-08 15:52 GMT+02:00 Sergio Álvarez Leiva <notifications@github.com>:

> [image: :heart:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/4292#issuecomment-119586445>.
>



-- 
Carlos Tallón
Designer & Baker

**Comment by javierarce** [comment]
Where's the file with this design?

**Comment by josecruz** [comment]
@javierarce If you have acces to dropbox, the file is called `create-map-1.7`

**Comment by javierarce** [comment]
Thanks!

**Comment by josecruz** [comment]
np! :+1:

**Comment by saleiva** [comment]
@josecruz would be great to modify this a bit with the feedback in https://github.com/CartoDB/cartodb/issues/4735 (point 4). Add a CTA to the connect dataset and to the drag and drop functionality (in the one that we can)

**Comment by saleiva** [comment]
bump! @josecruz.

**Comment by josecruz** [comment]
So I made a different version to when you're in `connect dataset`

![empty dashboard - connect dataset data library](https://cloud.githubusercontent.com/assets/596509/9228743/bee4fa82-4111-11e5-865a-f8054c7bea83.png)

**Comment by saleiva** [comment]
come on! a visual tip for the drag&drop would be killer!

**Comment by josecruz** [comment]
Something like this?

![empty dashboard - connect dataset data library copy](https://cloud.githubusercontent.com/assets/596509/9229563/9a587b68-4115-11e5-83a2-0e1efe01c8bf.png)

**Comment by saleiva** [comment]
Getting better, but still room ti improve, I think...

**Comment by josecruz** [comment]
Better?

![empty dashboard - connect dataset data library copy 2](https://cloud.githubusercontent.com/assets/596509/9230075/3d37424a-4118-11e5-97c6-e7174e9ac01c.png)

**Comment by saleiva** [comment]
Is too subtle and being so close to the border makes it so small

**Comment by josecruz** [comment]
Okay, updated contrast and browser position to make the box bigger
![empty dashboard - connect dataset data library copy 2](https://cloud.githubusercontent.com/assets/596509/9249087/af915f64-41b9-11e5-823f-d3f511e72f5e.png)

**Comment by saleiva** [comment]
Don't you think the file icon is still too small?

**Comment by saleiva** [comment]
(do we want to animate this?)

**Comment by josecruz** [comment]
Uhmm probably yep, updated icon:

![empty dashboard - connect dataset data library copy 2](https://cloud.githubusercontent.com/assets/596509/9256634/90df9642-41e8-11e5-936b-a0263e607357.png)

IMHO I think that an animation wouldn't be necessary and could distract the user

**Comment by saleiva** [comment]
Ok, I'd remove then the 'You can drag and drop your dataset as well text", since it's already on the animation. Once you've modified assign to @javierarce please! :)

**Comment by josecruz** [comment]
So finally there will be an animation?

Last version:
![empty dashboard - connect dataset data library copy 2](https://cloud.githubusercontent.com/assets/596509/9301735/0335ae08-44d1-11e5-89d6-3eeaef67ceef.png)
