### ISSUE TITLE
After applying a query changing the geometry type, nothing is rendered

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#4293]
until you click on a wizard of the wizard panel to regenerate the cartocss

**Comment by javierarce** [comment]
How can I reproduce this?

**Comment by saleiva** [comment]
do an ST_makeline in a points dataset for example

**Comment by javierarce** [comment]
I applied `SELECT ST_MakeLine(the_geom_webmercator) AS the_geom_webmercator FROM my_point_table` and obtained a map with lines right away.

**Comment by saleiva** [comment]
:/

**Comment by javierarce** [comment]
https://open.spotify.com/track/4EnkwZd0UJAuHpNMMemQaA ?
