### ISSUE TITLE
Infowindow on hover doesn't show timestamp type fields

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#4298]
It always appear empty, but it shows the content on the infowindow on click

**Comment by alonsogarciapablo** [comment]
I've looked at this briefly and it looks like the grid.json is not returning `date` columns in the `data` key. Is there such limitation @rochoa?

**Comment by alonsogarciapablo** [comment]
Ping @rochoa! What do you think about this? Is there something in the tiler that's preventing `date` fields from being included in the `grid.json`? Thanks!

**Comment by rochoa** [comment]
Hey,

Hover and on click follow different access. The on click uses the cartodb_id to retrieve the infowindow data through the attributes service: http://docs.cartodb.com/cartodb-platform/maps-api.html#retrieve-resources-from-the-layergroup

The hover uses the interactivity to return all the required values but there is a bug with date and timestamps, see https://github.com/CartoDB/Windshaft/issues/103

Closing as duplicate.

**Comment by alonsogarciapablo** [comment]
Thanks!
