### ISSUE TITLE
Tests depend on old layer options

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#4302]
[Some layer configuration was deleted](https://github.com/CartoDB/cartodb/commit/0a9f6cc797d210041f4a7c56429da3b53f820b62), but [some tests still depend on it](https://github.com/CartoDB/cartodb/blob/master/spec/models/layer_spec.rb#L37). That dependency should be removed.

cc @javisantana

**Comment by javisantana** [comment]
why wasn't it failing?

**Comment by ethervoid** [comment]
@juanignaciosl we should check your configuration, probably wasn't updated properly and have this fields in it

**Comment by juanignaciosl** [comment]
Mine's not important (I've already deleted it), but [it should be removed from the cookbooks](https://github.com/CartoDB/cartodb-platform/blob/31e90c1ba2d7f94cb5b22d1050916cd16764fade/cookbooks/cartodb_app/templates/default/app_config.yml.erb#L231).
