### ISSUE TITLE
If you add a point, polygon or line the maps type keeps setted even if you delete the feature

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/cartodb#4306]
Once you have add a feature (point, polygon or line) even if you delete it you can't add other type than the selected one.

Steps to reproduce:

1- Create empty map
2- Add new feature: point
3- Delete point
4- Try to add a line but you can't because it only allows you yo create points

If you exit the map view and return, the map lets you add any feature you wants

**Comment by saleiva** [comment]
it is actually a feature, not a bug :)
