### ISSUE TITLE
avoid analyzing the_geom columns

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#4318]
Looks like we are analyzing it but it doesn't make sense, right?

**Comment by javisantana** [comment]
It would make sense to get the bbox but I noticed we not using it to show the previews because it shows the current visualization viewport. 

In a perfect world we would use that analysis to show the important part of the vis

**Comment by javierarce** [comment]
@saleiva did you see a card for the_geom? 

We're currently analyzing `the_geom` here https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/common/dialogs/pecan/pecan_view.js#L355 to get data about the table (like the geometry type and the bbox), but that column is excluded from the general analysis (https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/common/dialogs/pecan/pecan_view.js#L12).

**Comment by javierarce** [comment]
@javisantana if I'm not mistaken, we are using this bbox: https://github.com/CartoDB/cartodb.js/blob/develop/src/api/sql.js#L450
