### ISSUE TITLE
Review text of finished geocoding modal

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#4321]
**Steps to make it appear:**

* Create a new table
* Add two rows
* In one of the rows, write "Madrid" in the name column. Leave the other empty
* Geocode by city names

![image](https://cloud.githubusercontent.com/assets/1730320/8541926/f466b78c-2491-11e5-9511-bc48237ccb39.png)

Not sure if this is still a draft, but just for you to know :smile: 

cc @xavijam @viddo

**Comment by xavijam** [comment]
This is the text we had in the previous dialog... but in any case, create a pull request with a better feedback please @iriberri!

**Comment by iriberri** [comment]
Oh, perfect. I thought it was new and someone had written a draft or something. Assigning to me then ;)

**Comment by viddo** [comment]
talk to @josecruz since he did the new designs for these modals

If something is planned to change on these (geocoding results) modals either make it clear what changes are expected or close it and reference the issue where the expected changes are already stated if such an issue already exists.

**Comment by iriberri** [comment]
I don't think something is planned to change, is just that there's a repeated sentence in the text :) I'll check with Jose though

**Comment by josecruz** [comment]
Thank you @iriberri!
