### ISSUE TITLE
Geocode missing quota info

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#4324]
![d1269ac6-240f-11e5-8e39-7d9d690b26cb](https://cloud.githubusercontent.com/assets/596509/8542320/21e5a6ac-2495-11e5-97ba-a08796deb655.png)

**Comment by josecruz** [comment]
@saleiva what do you think?
![streetaddresses_maxcost copy](https://cloud.githubusercontent.com/assets/596509/8542497/6a9a8876-2496-11e5-8614-69e277d4c073.png)

**Comment by saleiva** [comment]
To many different places to tell similar messages. Can we try to adapt the text and integrate that as part of the text close to the icon?

**Comment by viddo** [comment]
Also, that space can't be used since it will clash with the planned design for [#3958 (Improve 2nd time georeferenciation when some rows doesn't get georef correctly)](https://github.com/CartoDB/cartodb/issues/3958)

**Comment by josecruz** [comment]
Kind of: 
![streetaddresses](https://cloud.githubusercontent.com/assets/596509/8543660/ac2a87e8-249e-11e5-8ed3-3ff04e28acce.png)

This message will only show when the geocode have no cost, right?

**Comment by saleiva** [comment]
Nope, you didn't get it. let's talk later about this. and... visually it's not very nice

**Comment by viddo** [comment]
Any update on this? Don't forget to reassign when ready

**Comment by saleiva** [comment]
@josecruz you got this, right?

**Comment by viddo** [comment]
Bump, any update on this? Is this is a show-stopper to open of the new modals? Got reminded when looking at the feedback on #4446
