### ISSUE TITLE
"Let CartoDB automatically guess data types and content on import." shouldn't be disabled although user can't create the dataset

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#4344]
User should be able to change it in any case.

![screen shot 2015-07-08 at 11 42 29](https://cloud.githubusercontent.com/assets/132146/8567544/74c98a74-2566-11e5-92ee-cc6f8b8ff308.png)

cc @saleiva @viddo

**Comment by viddo** [comment]
Ok
