### ISSUE TITLE
viz.json can be fetch by tablename and the user is not taken into account

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#4360]
so:

these two endpoints return the same:

```
https://vmg.cartodb.com/api/v2/viz/83d70bd6-24e4-11e5-9be3-0e43f3deba5a/viz.json
https://rambo-test.cartodb.com/api/v2/viz/83d70bd6-24e4-11e5-9be3-0e43f3deba5a/viz.json
```

same using table names

```
https://rambo-test.cartodb.com/api/v2/viz/sensor_log_2015_07_07_21_08/viz.json
https://vmg.cartodb.com/api/v2/viz/sensor_log_2015_07_07_21_08/viz.json
```

cc @CartoDB/backend

**Comment by Kartones** [comment]
well, privacy will still be checked, it is just taht being public, they are probably first feched and then compared like "can be seen by xxxx?" instead of checking actual ownershinp of the vis id.

So is a bug but not severe

**Comment by juanignaciosl** [comment]
Another url that "works but shouldn't", because of the same reason, is using organization name as subdomain. Will be fixed as well.
