### ISSUE TITLE
Missing postedtime with oneclick

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#4363]
If i create a map from a public dataset (create map button) https://team.cartodb.com/u/piensaenpixel/tables/carlostallon.bye_bye_iker/public/map?redirected=true

I miss the postedtime info
![image](https://cloud.githubusercontent.com/assets/1214201/8576430/4fbd4914-25a2-11e5-84c9-4ef7ec347b79.png)

**Comment by juanignaciosl** [comment]
I can't reproduce exactly this. I've imported it twice and `postedtime` is there. I've seen columns get trimmed to 10 characters, and since two are trimmed to the same name there's a collision and one's overriden. Exporting to CVS works as well (and column names are kept).
