### ISSUE TITLE
Remove close button in footer of some modals

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#4378]
So, we're keeping "close" button when it's the only action. So we're going to remove from this modals:

- [x] Dataset metadata:
![screen shot 2015-07-09 at 10 57 31 am](https://cloud.githubusercontent.com/assets/596509/8595578/c8a994fc-2649-11e5-97f0-bb757bba618c.png)

- [x] Point metadata
![screen shot 2015-07-09 at 12 24 02 pm](https://cloud.githubusercontent.com/assets/596509/8595561/b65c73e6-2649-11e5-9ac6-a735ee20579f.png)

- [x] Also, we could change the header icons color to `#666` as well

Thanks to @piensaenpixel for spot this!

**Comment by viddo** [comment]
> Also, we could change the header icons color to #666 as well

Let's keep this issue focused on the buttons, add header fixes to the existing issue --> #4175

**Comment by saleiva** [comment]
Hey @josecruz we agreed to keep the button on the export and the publish modal

**Comment by josecruz** [comment]
@saleiva Okay so I delete the export one. Okay will do it @viddo ty!

**Comment by saleiva** [comment]
What if we put those buttons (and the others) aligned to the center?

**Comment by josecruz** [comment]
@saleiva Mm I don't know, on this type of modals we always align right
