### ISSUE TITLE
Change lon/lat georeferencing to use the background importer

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#4381]
Extracted from #4262

> @josecruz wrote:
instead of this:
![screen shot 2015-07-07 at 6 30 25 pm](https://cloud.githubusercontent.com/assets/596509/8551714/882c78f8-24d8-11e5-95fb-7b64fcf92649.png)
- Geocoding status:
We should use this:
![screen shot 2015-07-07 at 4 10 54 pm](https://cloud.githubusercontent.com/assets/596509/8551462/08495292-24d7-11e5-9e58-ff26d662f344.png)
* Regarding this format:
- The copy should be: Geocoding datasets...
- Should be the same icon as the geocoding modal one

--- 
(edit: added TODOs)

tasks:
- [x] remove current loading indicator at the top
- [x] display geocoding progress in the background importer
- [x] remove cancel-button since can't abort a lon/lat geocoding
- when background importer only have geocoding processes should
  - [x] show "geocoding dataset(s)…" instead
  - [x] show the same icon as for georef modal

**Comment by viddo** [comment]
Created a separate issue because this is not a bug, but a feature request. I'm not sure it makes sense to do this change from a technical point-of-view. AFAIK, the lon/lat is not a request that is done _async_ which is the reason why it's not going through the background importer like the rest. 

@xavijam @javisantana does it make sense to "fake" the lon/lat geocoding to go through the background importer? If so, how hard would it be to make that change (since you know the code better than I do).

**Comment by saleiva** [comment]
We should fake at least UX wise.

**Comment by xavijam** [comment]
Uhm... we could do it for sure, and the process would look better having all "geocoding" process using the same behaviour, but you would need to trick a little bit how background polling works, but hey, totally possible. Right now, for geocoding lat and lng, you only need:

```js
    table.save({
        latitude_column: lat_column,
        longitude_column: lon_column
      }, {
        success: function(r) {
          // whatever
        },
        error: function(msg, resp) {
          // whatever
        },
        wait: true
      });
```

**Comment by xavijam** [comment]
Or, being more strict, create a batch geocoding process for this purpose :dancer:. But not sure if it makes sense and if @rafatower is very happy with that :D.

**Comment by rafatower** [comment]
@xavijam it makes some sense. After all it is invoking something that can potentially take a while on big tables so it is better done async. That reminds me of the api definition :(

**Comment by xavijam** [comment]
For me it would be the winner, but not sure how it fits in your "roadmap".

**Comment by xavijam** [comment]
For me it would be the winner, but not sure how it fits in your "roadmap".

**Comment by viddo** [comment]
Ok, great! Thanks for the input, then I know who to talk to when I get to implement this (ETA early next week)

**Comment by rafatower** [comment]
Let's summon @javisantana for the BE part

**Comment by rafatower** [comment]
After talking with Santana: let's stick to the current endpoints and fake in the UI if needed and we will accommodate the lat/long geocodes into the "Geocoding API v1" whenever we can push it back into the roadmap
