### ISSUE TITLE
Allow back imports generating more than one dataset

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#4393]
We've lost the capability of importing OSM data from OSM and some imports like a GPX file wich would generate several datasets after limiting the import to just creating one dataset.

I propose we get back to the point that we allow more than 1 dataset with the same import, and add a limit for extreme cases (100?)

Adding @javisantana  to the conversation.

-----------

- [x] limit to 10 spawned tables max (except ArcGIS)
- [x] ArcGIS MapServer all layers import
- [x] Zips containing > 1 files import
- [x] KML containing > 1 layers import
- [x]  <del>GPX multi-track import</del>
- [x] SHP with README/VERSION/etc. importing ok
- [x] tests

**Comment by javisantana** [comment]
@Kartones why did we remove this? I'm sure it was because a reason.

100 is too many in my opinion and those cases should be managed in a different way (for example, KML), 10 is enough (OSM generate 3, GPX generate about the same)

**Comment by Kartones** [comment]
Must take into account:
- Not creating then a default Map, as there will be N tables from a single import
- Templated workflows integration (at least have it in mind)
- Decide the limit: I'd go for something like 20 or even less, we don't allow so many layers by default so if someone wishes to see all of them won't be able. But is not my call and I don't know which would be ok, I just want a "firm" number.
- [this issue](https://github.com/CartoDB/cartodb/issues/2858) becomes then a pre-requisite/blocker for attacking this ticket, as else we'll always try to import TXT and other text file and cause errors.

**Comment by Kartones** [comment]
@javisantana no idea, I'm 90% confident I didn't removed it, so probably was due to some bug, or maybe the ticket/issue I mentioned at previous comment.

**Comment by saleiva** [comment]
I'm sure @iriberri has more info.

**Comment by saleiva** [comment]
+1 on the @javisantana number, I added 100 as a placeholder. 10 sounds feasible

**Comment by iriberri** [comment]
Notify SB/5908207

**Comment by Kartones** [comment]
This is also blocking #4450 from importing all ArcGIS MapServer layers.

**Comment by Kartones** [comment]
Note to self: Testing ArcGIS MapServer full import with `http://gis.phila.gov/arcgis/rest/services/Police/Police_Boundaries/MapServer`

**Comment by Kartones** [comment]
For the record, GPX hasn't had multi-layer support since 2013-10-14 (git blamed because I didn't recall anybody touching some related lines).

I'm going to move that to a separate ticket as that requires maybe a specific Importer Loader class to fetch [all different feature types](http://www.gdal.org/drv_gpx.html)

**Comment by Kartones** [comment]
Branch is `4393-importer-fixes`
