### ISSUE TITLE
There should be a per-user platform limit of concurrent syncs

### ISSUE THREAD

**Issue by Kartones** [CartoDB/cartodb#4395]
@danicarrion raised an issue we have: There is a limit of concurrent imports per user, but there is no limit of concurrent syncs per user. So I can create 50 syncs almost at once, and they would eat all cloud workers for themselves, not allowing anybody to import until they finish.

We should implement a platform limit so only up to X (I'd say 3, separate from the imports limit), so only up to X get enqueued, and when one finishes next sweep will have available slots again (now sweeps are done each 2-3 mins so is not problematic).

I estimate ~4h of time to build and (mostly manually) test it, as the PlatfomLimits system is already there and easy to extend.

@saleiva @javisantana

**Comment by Kartones** [comment]
Branch: `4395-rate-limit-syncs`

**Comment by Kartones** [comment]
@javisantana To avoid complexity I'm not going to setup any user attribute, and directly for now limit to 3 concurrent syncs per user. Keys expire at redis, etc. but as the sync check script runs each 2-3 minutes only stale syncs could cause issues, and they cause them anyway now (and all keys have TTL)

**Comment by Kartones** [comment]
Also, TTL will be 2h (being very generous)

**Comment by javisantana** [comment]
ok, sounds good, we can change it we find problems
