### ISSUE TITLE
Add deactivated input to the admin panel of a MU with the signup URL for that org

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#4396]
Right now there is no easy way to tell the admin which URL he should direct the new users.

**Comment by xavijam** [comment]
What about:

· Sign up disabled
![screen shot 2015-08-03 at 17 09 37](https://cloud.githubusercontent.com/assets/132146/9040429/702c730e-3a02-11e5-9f6f-2ca2101c5604.png)

· Sign up enabled
![screen shot 2015-08-03 at 16 53 09](https://cloud.githubusercontent.com/assets/132146/9040430/702cd9ac-3a02-11e5-9632-b3043e55a9db.png)

What do you think?
