### ISSUE TITLE
Choose organization avatar link lets you choose it but doesn't load it

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#4399]

**Comment by juanignaciosl** [comment]
I've checked staging and production, normal and multiuser accounts, and it works. Maybe you didn't press "Save"?

**Comment by juanignaciosl** [comment]
When you send the form you see field parameter naming is wrong:

![screen shot 2015-07-13 at 14 19 01](https://cloud.githubusercontent.com/assets/932968/8649394/2816b74e-296a-11e5-8a35-0596f1f93f85.png)

Looks like this page is reusing [avatar_selector_view.jst.ejs, which refers user model](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/common/views/avatar_selector_view.jst.ejs#L15).
