### ISSUE TITLE
Layer reordering breaks if done twice

### ISSUE THREAD

**Issue by Kartones** [CartoDB/cartodb#4408]
layer_order Layer_name

EXPECTED equals "what you see at the editor"
ACTUAL equals "what public_map shows"

INITIAL
3 polygon
2 bigpoints
1 smallpoints

> I move polygon layer to bottom

EXPECTED & ACTUAL
3 bigpoints
2 smallpoints
1 polygon

> I move polygon again topmost

EXPECTED:
3 polygon
2 bigpoints
1 smallpoints

ACTUAL:
3 polygon
2 smallpoints
1 bigpoints

Editor displays EXPECTED order, but upon reload is also at ACTUAL state

**Comment by alonsogarciapablo** [comment]
This might be related to #4251.

**Comment by alonsogarciapablo** [comment]
I have [committed this](https://github.com/CartoDB/cartodb/commit/be7ceb776e7bc392360b480819eb23cbbce66348) so that the order or layers is recalculated correctly after drag&dropping. However, this won't be working properly until #4251 gets merged.

**Comment by xavijam** [comment]
:+1:

**Comment by alonsogarciapablo** [comment]
Reopening this issue since it wasn't fixed.
