### ISSUE TITLE
Layer visibility gets borked if map has no named map

### ISSUE THREAD

**Issue by Kartones** [CartoDB/cartodb#4409]
*layer_order layer_name (visibility)*

*EXPECTED means "what the editor shows"*
*ACTUAL means "what the public_map shows"*

**All datasets are public (if you make any private it works, so with named maps works)**

EXPECTED:
3 torque (visible)
2 points (visible)
1 polygon (hidden)

ACTUAL:
torque (visible)
points (hidden)
polygon (visible)

If I change torque layer to anything else also keeps broken, but then I see:

notorque (hidden)
points (visible)
polygon (visible)

**Comment by alonsogarciapablo** [comment]
Should be fixed by [this commit](https://github.com/CartoDB/cartodb.js/commit/58dd6d98fd55d9e98e99d48c3bd9ceb7d67bcd2a).
