### ISSUE TITLE
Labels not properly rendered on dashboard/public maps

### ISSUE THREAD

**Issue by Kartones** [CartoDB/cartodb#4410]
At the dashboard, I have a map and a clone of it that shows no labels:
![image](https://cloud.githubusercontent.com/assets/2085449/8620043/3c712fca-271d-11e5-824b-57c081d3cab0.png)

At the public map page, apart from previous ones failing, the other map that shows ok is also wrong:
![image](https://cloud.githubusercontent.com/assets/2085449/8620058/50bc7ac0-271d-11e5-99a3-f8516f174012.png)

"Green maps" have 3 layers all visible

**Comment by alonsogarciapablo** [comment]
This was happening only when the map wasn't a named map (that is: map and all datasets are public).

It should have been fixed by [this commit](https://github.com/CartoDB/cartodb.js/commit/7dee94bfe94ec26397418b24fb3ab4f49a2acb98).
