### ISSUE TITLE
Tricky multiselect that isn't

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#4413]
In the modal to add a second layer, if you click one layer, you can't change your mind without deselecting it. it behaves like a multiselect but it isn't

![add second layer](https://cloud.githubusercontent.com/assets/370259/8625645/2135fa9c-270e-11e5-9e9f-f14e677d6489.gif)

cc/ @saleiva

**Comment by viddo** [comment]
Duplicate of #3845
