### ISSUE TITLE
update 404

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#4428]

**Comment by matallo** [comment]
btw, there are some static pages still with the former design such https://matallo.cartodb.com/maintenance.html

/cc @carlostallon

**Comment by carlostallon** [comment]
Yep, I think we can design it quickly with new design patterns ; )

2015-07-14 11:41 GMT+02:00 Carlos Matallín <notifications@github.com>:

> btw, there are some static pages still with the former design such
> https://matallo.cartodb.com/maintenance.html
>
> /cc @carlostallon <https://github.com/carlostallon>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/4428#issuecomment-121181303>.
>



-- 
Carlos Tallón
Designer & Baker

**Comment by carlostallon** [comment]
Both designs:
![error 404](https://cloud.githubusercontent.com/assets/1712650/8674081/c29d7a38-2a3b-11e5-96fb-7d91151304fe.png)
![upgrading](https://cloud.githubusercontent.com/assets/1712650/8674082/c29f9d04-2a3b-11e5-939e-10d8d5e2ae29.png)
