### ISSUE TITLE
remove ArcGIS logo from our data import page

### ISSUE THREAD

**Issue by vhamer** [CartoDB/cartodb#4429]
@saleiva would you please reassign this issue?

--

We don't want to get in trouble with Esri for _anything_ and our lawyer has advised us to remove their logo from inside our application. We can use the term ArcGIS, but it should look like these

ArcGIS Server(tm)
ArcGIS(tm)

So capitalize Server and add &trade; to each mention of ArcGIS

I've attached a screenshot to show where changes are needed.

thanks!

![vhamer___cartodb-3](https://cloud.githubusercontent.com/assets/850589/8661809/65ab7e78-2988-11e5-8d15-aa2178803bf4.png)

**Comment by josecruz** [comment]
Thanks @vhamer! Created a new issue (#4458) for the next milestone so closing this.
