### ISSUE TITLE
Annotations in embeds are showing Times font over Google Maps

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#4440]
In the embed_map annotations are being shown with Times font:

![image](https://cloud.githubusercontent.com/assets/1730320/8672371/e17e9206-2a2d-11e5-8e03-0633044cf2c0.png)

In public_map, they're appearing as set in the viz.json

![image](https://cloud.githubusercontent.com/assets/1730320/8672379/ef8f8724-2a2d-11e5-91b1-bba5f4e314b4.png)

While testing with `cartodb.uncompressed.js`, the fontFamily variable (line of code [here](https://github.com/CartoDB/cartodb.js/blob/develop/src/geo/ui/annotation.js#L230)) is storing `undefined`, although other properties as the boxColor are set up correctly:

![image](https://cloud.githubusercontent.com/assets/1730320/8672397/2e526c6a-2a2e-11e5-87f2-ddc5cd3c7854.png)

cc @javisantana @javierarce

**Comment by javierarce** [comment]
This should be fixed now!
