### ISSUE TITLE
Rename the "Share" icon to something else

### ISSUE THREAD

**Issue by zenitraM** [CartoDB/cartodb#4448]
uBlock filters filter that image out as it's named "share.png"

https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=en

![image](https://cloud.githubusercontent.com/assets/863975/8675846/61d18acc-2a46-11e5-95d5-6f086416df01.png)

![image](https://cloud.githubusercontent.com/assets/863975/8675832/5003cdbe-2a46-11e5-948f-e176c5bb35a7.png)

**Comment by xavijam** [comment]
Moved to https://github.com/CartoDB/cartodb.js/issues/634 because that image and those components belong to cartodb.js.
