### ISSUE TITLE
Improve decission tree to show more bubble maps on points dataset and not so much choropleth maps

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#4455]
Bubble maps should be the thematic map option by default on point datasets
cc/ @andrewxhill 

Try with this dataset to understand better this issue. https://team.cartodb.com/u/saleiva/tables/alojamientos#/options

**Comment by saleiva** [comment]
In scge_migration we should use bubble maps for speed_2d and too, for example

**Comment by ohasselblad** [comment]
currently the bubble maps are chosen for datasets with fewer than 200 points. We could raise this threshold but also do something like balance clustering with the number of points in a cluster.
