### ISSUE TITLE
Change 'Connect Dataset' header icon color

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#4457]
We're using `#666` for all header icons:
In prod:
![screen shot 2015-07-15 at 11 50 22 am](https://cloud.githubusercontent.com/assets/596509/8695796/cb9252e2-2ae7-11e5-9df2-5a3cd13d7fd3.png)

Designs: 
![screen shot 2015-07-15 at 11 48 44 am](https://cloud.githubusercontent.com/assets/596509/8695800/d1ef0db0-2ae7-11e5-96a1-647bfc8edee2.png)

The sketch file is `create-map-1.7.sketch`

**Comment by javierarce** [comment]
Closing since this is already fixed.
