### ISSUE TITLE
ArcGIS fixes on the Import Dataset modal

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#4458]
So we're adding (tm) to all ArcGIS and ArcGIS Server texts:

ArcGIS Server(tm)
ArcGIS(tm)
Change logo

![65ab7e78-2988-11e5-8d15-aa2178803bf4](https://cloud.githubusercontent.com/assets/596509/8695934/c21e336a-2ae8-11e5-8856-a88f3a8fef10.png)
to
![screen shot 2015-07-15 at 12 12 41 pm](https://cloud.githubusercontent.com/assets/596509/8696223/d84f4654-2aea-11e5-9751-b149cecc9816.png)

and on the empty state:

![screen shot 2015-07-15 at 11 56 09 am](https://cloud.githubusercontent.com/assets/596509/8696164/62689f1c-2aea-11e5-859c-16dc4286ce20.png)
to
![screen shot 2015-07-15 at 12 10 06 pm](https://cloud.githubusercontent.com/assets/596509/8696178/78e61a26-2aea-11e5-9fb0-ea4932a577aa.png)

**Comment by javierarce** [comment]
Where's the new icon?

**Comment by josecruz** [comment]
talked via slack :+1:
