### ISSUE TITLE
Add import error percentage to data import

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/cartodb#4461]
Now we have the import error percentage, only for SHP files, and we want to have it in the data import info.

**Comment by ethervoid** [comment]
I've been using Postgres statistics data (`pg_stat_user_tables`) to avoid the expensive use of count but I'm afraid that the rows count gathered is not reliable.

My concern is if I can trust that the data is going to be collected when I finish the import process to gather it. 

Is there any way (that don't imply explicitly call the collector) to asure the data is collected?. the collected data could be partially updated? (for example while I'm in the middle of the importing process, the statistics collector gather data)  

I'd like to discuss this with people like @pramsey or @javisantana that knows more about Postgres :)

**Comment by pramsey** [comment]
Running `ANALYZE mytable` should force a stats refresh.

**Comment by ethervoid** [comment]
Thank you Paul. Finally I'm going to use COUNT and check for performance.

**Comment by pramsey** [comment]
It's a full table scan every time. reltuples not doing it for you?

**Comment by ethervoid** [comment]
yep is a full table scan but I need the exact number because I'm planning to use it to calculate the import error between rows imported and the number of rows of the file to be imported.

I've been using `n_live_tup` but in staging sometimes the value wasn't be calculated so I'm afraid I can't get real values :S

**Comment by pramsey** [comment]
Maybe only run the process every 10th import, to keep the load down?

**Comment by ethervoid** [comment]
Hum that could be a solution. I'll take a look to it. Thank you very much Paul :))
