### ISSUE TITLE
Geocode small visual fixes

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#4470]
Just found 3 small visual things

- [x] The `Form-row` div has a 10px padding and it sums to the title div. So in total it's 50px instead of 40px, and it should be 40px
![screen shot 2015-07-15 at 4 40 00 pm](https://cloud.githubusercontent.com/assets/596509/8701251/eedba8ec-2b10-11e5-9e46-0538bff5c89c.png)

- [x] This text should be `16px` and `#666:
![screen shot 2015-07-15 at 4 36 55 pm](https://cloud.githubusercontent.com/assets/596509/8701334/6edd9c4e-2b11-11e5-911f-5e9afc3da327.png)
to
![screen shot 2015-07-15 at 4 48 46 pm](https://cloud.githubusercontent.com/assets/596509/8701336/73304b34-2b11-11e5-95f1-894ad8d85c6e.png)

- [x] The icon is not centered at all. I've tried with a `padding-top:9px;` and it seems to be centered:
![screen shot 2015-07-15 at 4 32 05 pm](https://cloud.githubusercontent.com/assets/596509/8701344/843c925c-2b11-11e5-8496-e47c904b8731.png)

PD: Kudos to @viddo for the awesome work :+1:

**Comment by viddo** [comment]
Solved as part of existing PR #4460 since already working on that one and kind-of related
