### ISSUE TITLE
Docx supported or not?

### ISSUE THREAD

**Issue by stevage** [CartoDB/cartodb#4482]
When you drag and drop a file onto the  main screen, at the bottom it says "formats like DOCX, CSV, GPX, XLS and many more are supported".

However:

1. The clickable link "many more" is not clickable, because as soon as you release the mouse, it goes away.
2. In the [list of supported formats](http://docs.cartodb.com/cartodb-editor.html#supported-file-formats), .docx isn't mentioned
3. When you try to drop a .docx, `Unfortunately this file extension is not allowed`

(Not that I want to import a .docx, I was just curious.)

**Comment by javierarce** [comment]
Hi, @stevage. The documentation and the error message are right, we don't currently support .docx. We'll fix the UI. Thanks for reporting this!
