### ISSUE TITLE
Broken date format in CSV causes whole file to fail

### ISSUE THREAD

**Issue by stevage** [CartoDB/cartodb#4483]
Just had a CSV fail with error 9999 due to a column like this:

```
date
2000-01-01
2000-1-NA
```

IMHO it should never fail to import just because of some data values which don't fit the type that CartoDB has assigned.

**Comment by saleiva** [comment]
@stevage what do you propose for the failing cells? Set them to null?

**Comment by stevage** [comment]
Either that or convert the whole column back to string. (I don't know anything about how this is implemented.)

**Comment by saleiva** [comment]
If we set the column back to string, we will just have the problem when converting later. So better to do at import time IMO

**Comment by stevage** [comment]
If by "later" you mean, when the user explicitly converts the column type to date, that's better in two ways:

1. You know that they really wanted a date. (Currently you're not that sure - you see one value that looks like a date, and another one that definitely isn't a date.)
2. You're in a better position to give specific error feedback. (As opposed to just aborting with a generic error message.)

**Comment by ethervoid** [comment]
Deployed a change that fixes this
