### ISSUE TITLE
[Suggestion] Add line removal option for annotations

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#4485]
Annotations are a very good resource because they allow you to place text exactly where you want. For some use cases, having a line that attaches the annotation to a specific location is not a nice approach to add an information box in a specific area, but the text boxes element are not explicitly staying in a location but moving within the map.

I created [this JS example](http://bl.ocks.org/iriberri/9eb142037aae525c50e7) that hides line of the annotation by reducing the width of the ball (the line length can't be set to 0, minimum seems to be 5 px but still the ball doesn't disappear).

Is there any easy approach that we could use to make the annotations usable in cases where you want to "label an area"?

![image](https://cloud.githubusercontent.com/assets/1730320/8718155/3ed2a454-2ba2-11e5-8fc7-6c76149f9ae4.png)

cc @saleiva

**Comment by MarkWS** [comment]
I too would love to see this feature added to the Editor. I can think of many instances where we would have implemented this and it would be a great value add.
Thanks, Mark

**Comment by saleiva** [comment]
Hey @MarkWS, getting this to the backlog. Thanks for your feedback!

**Comment by saleiva** [comment]
I @MarkWS Could you provide some more use cases for this?

**Comment by MarkWS** [comment]
we just came across this as well. It was an Oil/Gas map and the client wanted the main basins labeled, not with a pointer but with just the annotated box in the 'general area'. If we were to have had a line, the end users could make the mistake that the indicated point is the oil production basin, when it's actually thousands of sq miles.
Also for the Fodor's maps we are working on, we had the designers ask for 'geographic areas' to be labeled with the annotated boxes. Like "National Parks of the South West" or "Great Basins National Parks". These are just a few examples and the removal of the line and pointer ball would be very helpful and we would use that quite often. ~ Mark
