### ISSUE TITLE
Avoid using color ramps with basemap-like color

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#4493]
![screen shot 2015-07-16 at 7 34 02 am](https://cloud.githubusercontent.com/assets/370259/8721949/78084bc6-2b8d-11e5-8553-5a1cf3070ad9.png)

**Comment by javierarce** [comment]
This requires to change the basemap depending on the selected ramp.

**Comment by andrewxhill** [comment]
Well.... We know in pecan it will always be lite to start. So what not only
use lite safe pallettes only

**Comment by saleiva** [comment]
It depends on the size of the polygons. Big polygons work on any ramp, smaller ones don't. It's not that easy :(

**Comment by andrewxhill** [comment]
Uhm... there are only two options

1. Get better at knowing from the polygon coverage what ramps we could use
2. Go with ramps that work in all cases. "polygon size safe ramps"

We are only really prepared for 2 at the moment.


On Sunday, July 19, 2015, Sergio Álvarez Leiva <notifications@github.com>
wrote:

> It depends on the size of the polygons. Big polygons work on any ramp,
> smaller ones don't. It's not that easy :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/4493#issuecomment-122638184>.
>


-- 

andrewxhill <http://twitter.com/andrewxhill>
http://cartodb.com

**Comment by saleiva** [comment]
We dont have Any that works for small polygons right now

**Comment by javisantana** [comment]
this will require to add information about color to all of the basemaps we are using and have a clear logic on how to change the ramps depending on them (if we want to do this real)

**Comment by javisantana** [comment]
for pecan just removing the ones who collide with positron is ok, right?

**Comment by andrewxhill** [comment]
Yes

**Comment by javierarce** [comment]
Ok, I think these are the safe color ramps:

![screen shot 2015-07-28 at 14 26 39](https://cloud.githubusercontent.com/assets/4933/8931210/d59a8546-3534-11e5-985f-e32d2f18d002.png)
![screen shot 2015-07-28 at 14 26 52](https://cloud.githubusercontent.com/assets/4933/8931212/d59c65b4-3534-11e5-8bb4-16bbb82ff613.png)
![screen shot 2015-07-28 at 14 27 00](https://cloud.githubusercontent.com/assets/4933/8931211/d59afdbe-3534-11e5-835b-b81ad78af85d.png)
![screen shot 2015-07-28 at 14 27 10](https://cloud.githubusercontent.com/assets/4933/8931213/d59ebe18-3534-11e5-9d8b-d559a5bf8da7.png)
![screen shot 2015-07-28 at 14 28 16](https://cloud.githubusercontent.com/assets/4933/8931231/ecbc826a-3534-11e5-97e8-f5e581899aec.png)
![screen shot 2015-07-28 at 14 28 23](https://cloud.githubusercontent.com/assets/4933/8931230/ecbb7bea-3534-11e5-8a2a-df45e65d6f85.png)

**Comment by javierarce** [comment]
Ok, I talked with @saleiva and we'll use the blue ramp for the time being. Closing this issue.
