### ISSUE TITLE
Error importing a CSV with carriage returns inside file columns

### ISSUE THREAD

**Issue by jsanz** [CartoDB/cartodb#4497]
On importing CSV files with return carriages inside text columns the process fails and the whole batch of records is discarded because of the rollback. Probably when importing CSV we should sanitize the records before passing it to ogr2ogr (my guess, after discusing with @ethervoid )

**Comment by ethervoid** [comment]
In this case the problem is that the CSV has return carriage inside the string of the column. This leads to ogr2ogr making a wrong importation. We should "sanitize" the string columns.

**Comment by ethervoid** [comment]
After reviewing this issue it seems that the python script used to export the twitter search to csv is not sanitizing properly.

Take a look to [this sanitizer](https://github.com/CartoDB/cartodb/blob/master/services/twitter-search/lib/twitter-search/json_to_csv_converter.rb#L187) that we have in the exporter and replicate it in the script

**Comment by ethervoid** [comment]
I've added a dataset with 13k rows with a portion of the same twits. I've used the editor, the import works fine. I've exported the dataset as csv and reimport again.

All worked fine so I assume the problem is with your import script.
