### ISSUE TITLE
Upgrade link inconsistency for organization owners

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#4501]
Upgrade link for organization owner appears in the dashboard menu

![screen shot 2015-07-13 at 09 25 13](https://cloud.githubusercontent.com/assets/932968/8725970/8bfe04a0-2bd7-11e5-8ce7-c934b0038452.png)

but disappears at organization settings page

![screen shot 2015-07-16 at 16 28 21](https://cloud.githubusercontent.com/assets/932968/8725998/b8dacd46-2bd7-11e5-8ac1-637866fe14a8.png)

Since we're redesigning that link (see CartoDB/cartodb/issues/4402) we should always display it.

cc @saleiva

**Comment by juanignaciosl** [comment]
@MariaCheca assigning this to you, since it's part of the redesign #4884

**Comment by xavijam** [comment]
Related -> https://github.com/CartoDB/cartodb/issues/5478
