### ISSUE TITLE
Failed georeferenced table with polygons shows as empty

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#4503]
**Steps to reproduce:**
1: Import this US Counties, 1779-1829 from the data library
2. Go to the dataset and open the georeference dialog
3. select “IP address” pane
4. In the dropdown select “fips” column
~~5. Check “override values” and proceed with the geocoding~~ happens regardless if this is checked or not
6. Let it finish and check that no rows were geocoded

**Actual results:**
but then it opens again the georeference dialog saying, there are no geometry data but in the map the polygons appear

**Expected results:**
Not showing this banner or state that there's no geometry data when there clearly is

<img width="839" alt="screen shot 2015-07-16 at 17 24 22" src="https://cloud.githubusercontent.com/assets/978461/8727359/8b88a360-2bdf-11e5-97b2-2c908f851eee.png">
<img width="869" alt="screen shot 2015-07-16 at 17 24 28" src="https://cloud.githubusercontent.com/assets/978461/8727358/8b861f96-2bdf-11e5-9039-709e013e3ec9.png">

**Comment by viddo** [comment]
And the logic is the same as for the [old modals](https://github.com/CartoDB/cartodb/blob/4378-remove-close-buttons/lib/assets/javascripts/cartodb/table/mapview.js#L647-L656): https://cloud.githubusercontent.com/assets/132146/8252441/680f643c-1686-11e5-89f1-6490e8440d2d.png
…which is apparently wrong then. It is shown because `table.isGeocoded()` returns `false` even though the geocoding has run (although no rows were processed). Obviously that doesn't check if there's any actual geometry on the table though…

So, regardless of old/new modals, from what I understand here the wanted behavior is that this message should only be displayed if the table don't have any geometry then? How can I acquire that information? @xavijam @javierarce @rafatower do you have any idea?

**Comment by rafatower** [comment]
> although no rows were processed

rows were processed but no geometry gotten from geocoding, that leaves `the_geom` (and `the_geom_webmercator`) untouched, right?

**Comment by viddo** [comment]
I compared the results of the two tables (i.e. before and after a geocoding), and it seems like some data is inconsistent. `the_geom` is not untouched, and it seems to mostly have null values after the geocoding is done:
<img width="519" alt="screen shot 2015-07-17 at 10 03 30" src="https://cloud.githubusercontent.com/assets/978461/8742991/332baabe-2c6b-11e5-8e45-fb200b2f536c.png">

Also, [`table.isGeoreference`](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/models/table.js#L754-L769) calls some internal stuff to decide whether the table has geocoded data:

```js
var geoColumns = this.geomColumnTypes();
      if(geoColumns && geoColumns.length > 0) {
        return true;
      } else {
        if (!this.isInSQLView()) {
          // sometimes the columns are changed in the frontend site
          // and the geocolumns are not updated.
          // check the columns in local
          return this._data.any(function(row) {
            return row.hasGeometry();
          });
        }
      }
      return false;
```

Through the dev console I'll get these values _before_ doing a geocoding:
```js
t = table.table // the table object
t.isGeoreferenced() // => true
t.geomColumnTypes() // => ['polygon']
t._data.any(function(row) { return row.hasGeometry() }); // => true
```

And I'll get these values _after_ doing a geocoding (like the one outlined in the desc):
```js
t = table.table // the table object
t.isGeoreferenced() // => false
t.geomColumnTypes() // => []
t._data.any(function(row) { return row.hasGeometry() }); // => false
```

So it seems like the geocoding is removing the metadata regarding the polygons, but the polygons themselves are located somewhere else since they're still rendered on the map?

**Comment by viddo** [comment]
edit: the polygons rendered are probably the ones that weren't deleted by the geocoding process I'd guess. But still, the method calls above indicate that there's no such data at all. :/

**Comment by viddo** [comment]
Ok, been playing around a bit more so happens the same on the old modals, so seems like the backend screws up existing polygons on geocoding. 

Before gecoding all polygons are present:
<img width="1679" alt="screen shot 2015-07-17 at 11 00 07" src="https://cloud.githubusercontent.com/assets/978461/8743930/599dad0c-2c73-11e5-950d-a8e731770936.png">

After geocoding some rows have had their polygons removed, and the no-georeferenced-data message is displayed (only displayed once, clear localstorage to see it again):
<img width="1317" alt="screen shot 2015-07-17 at 10 59 32" src="https://cloud.githubusercontent.com/assets/978461/8743934/5edb0ff8-2c73-11e5-8727-50433e65b32a.png">
<img width="1680" alt="screen shot 2015-07-17 at 11 00 11" src="https://cloud.githubusercontent.com/assets/978461/8743935/5ef2e33a-2c73-11e5-80ac-ac3bb4990230.png">

Reassigning to @rafatower since need to look into what's going on the geocoder

**Comment by rafatower** [comment]
There are a couple of minor issues with this particular case:
- Geometries are overwritten with `NULL` when the geocoder is not able to geocode. I'm fixing that in https://github.com/CartoDB/cartodb/pull/4630
- After that, the backend returns the `geometry_types` of the table as `[]` since it is a guess based on the first N rows, coincidentally set to `NULL`. See [query_geometry_types](https://github.com/CartoDB/cartodb/blob/c627721763d856e9249cecb39f6dcb18497408d2/app/models/table.rb#L1467)
