### ISSUE TITLE
Add some terms to the exclude list

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#4512]
i'm sure some are new here, 
'cartodb_id','longitudenumber','latitudenumber','lat','lon','lng','long','latitude','longitude','shape_length','shape_area','objectid', 'id', 'country', 'state','scalerank', 'strokweig', 'area_sqkm', 'region', 'subregion', 'funcstat','classfp','county_fip','county','aland10'

![screen shot 2015-07-16 at 7 06 42 pm](https://cloud.githubusercontent.com/assets/370259/8737257/2c979e4c-2bee-11e5-8ebc-aee169fe806e.png)

**Comment by andrewxhill** [comment]
'shape_leng' actually didn't make it, so maybe just that one

**Comment by javierarce** [comment]
Only ```shape_leng```, then?

**Comment by andrewxhill** [comment]
Any that you are missing here, but shape_leng is definitely missing

On Fri, Jul 17, 2015 at 11:55 AM, Javier Arce <notifications@github.com>
wrote:

> Only shape_leng, then?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/4512#issuecomment-122324010>.
>



-- 

andrewxhill <http://twitter.com/andrewxhill>
http://cartodb.com

**Comment by javierarce** [comment]
:ok_hand:
