### ISSUE TITLE
Importer is "too smart" for leading 0 US zipcodes

### ISSUE THREAD

**Issue by andrewbt** [CartoDB/cartodb#4513]
I have a CSV file, as below:

zip code,zip string,state,city
01569,"01569",MA,Uxbridge

When imported, both the "zip code" and the "zip string" columns are converted to number type, and the leading 0 is removed from both. (so they become "1569" instead of "01569"). Additionally, I wrapped the "zip string" column in quotes with the expectation that these would preserve it as a string and not convert it to a number, but the importer did anyway.

Another "problem": The "MA" (which is the US state abbreviation for "Massachusetts", where all zip codes come with leading zeros) was interpreted to be the country code of "Morocco", and was so geocoded as a Morocco polygon upon import. __Is this just because__ I only had one record and there was a coincidence?

EXPECTED BEHAVIOR:
1. Quoted numbers should remain strings after import.
2. Don't automatically georeference things unless user tells CartoDB to.

**Comment by andrewbt** [comment]
@ztephm informed me that there's a "don't guess types on import" checkbox that will fix the georeferencing part, which I missed because I'm so used to doing drag-and-drop imports. Still, I think quoted numbers in CSVs should remain strings.

**Comment by iriberri** [comment]
Related: https://github.com/CartoDB/cartodb/issues/5559

Old issue, but the "don't guess types or content" on import does actually a couple of things from the editor:

* It disables quoted fields guessing
* It disables type guessing
* It disables automatic georeferenciation


With the Import API the three cases can be independently enabled: http://docs.cartodb.com/cartodb-platform/import-api/standard-tables/#upload-file
