### ISSUE TITLE
Wrong like endpoint called from public pages

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#4522]
Pages like this one, https://team.cartodb.com/u/matallo?paco, are calling endpoints without username, https://team.cartodb.com/api/v1/viz/c31d168e-f88c-11e4-9baa-0e4fddd5de28/like. It should be https://team.cartodb.com/u/matallo/api/v1/viz/c31d168e-f88c-11e4-9baa-0e4fddd5de28/like .

cc @xavijam

**Comment by xavijam** [comment]
I'll take care of it
