### ISSUE TITLE
Geocode footer quotes

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#4523]
------
![21e5a6ac-2495-11e5-97ba-a08796deb655](https://cloud.githubusercontent.com/assets/596509/8745352/5ec2f5c4-2c7f-11e5-89f7-265dacd09bcf.png)
to
![screen shot 2015-07-17 at 12 19 43 pm](https://cloud.githubusercontent.com/assets/596509/8745354/661bbefa-2c7f-11e5-81f8-842bd41b219d.png)

-----------

![07ef24ae-2b06-11e5-9bc3-9784d7a166f6](https://cloud.githubusercontent.com/assets/596509/8745439/3da41f7a-2c80-11e5-89af-7aa91c47e187.png)
to
![screen shot 2015-07-17 at 12 38 36 pm](https://cloud.githubusercontent.com/assets/596509/8745514/f684371e-2c80-11e5-874f-825bd58568b5.png)

-----------

![screen shot 2015-07-17 at 12 26 57 pm](https://cloud.githubusercontent.com/assets/596509/8745693/b4444662-2c82-11e5-9de5-8e0b72188983.png)
to
![screen shot 2015-07-17 at 12 34 33 pm](https://cloud.githubusercontent.com/assets/596509/8745696/bbf8cc5c-2c82-11e5-9ce9-da430f35a5e4.png)

-----------

Any state missing? 
@saleiva you agree with copies?

**Comment by viddo** [comment]
this solves #4324 right?
there are more states missing, see the if-else cases here: https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/table/views/geocoding_dialog/geocoding_dialog_pane_address.jst.ejs#L30-L40

**Comment by josecruz** [comment]
Missing state
`After available credits, each <%= block_size %> new geocodings will cost $<%= block_price/100 %>.`
![screen shot 2015-07-20 at 10 39 59 am](https://cloud.githubusercontent.com/assets/596509/8772344/cbb20ae6-2ecb-11e5-86c0-3f16caa98f5c.png)

_this closes #4324 right?_
Yup, clossed.

**Comment by viddo** [comment]
Is there anything more for you to do here? Otherwise reassign to me please
