### ISSUE TITLE
Like in embed_map is not working if you belong to an organization

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#4533]
Due to this [change](https://github.com/CartoDB/cartodb/issues/4360), requests like ```http://:orgname.cartodb.com/api/v1/:viz_id/...``` are not working anymore (you need to specify the username and the viz_id, both). We found an issue with likes view (over public pages) trying to work with those urls, and we fixed [here](https://github.com/CartoDB/cartodb/issues/4522).

Unfortunately it doesn't fix the problem under embed_map page because what we do internally to inject "prefix url" in cdb.core.Model.prototype.sync is in [app.js](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/app.js#L41), file that is not included in that page.

Should we add only this override in the embed part? -> Do this affect rest of models within cartodb.js?

What is your opinion @CartoDB/frontend?

**Comment by xavijam** [comment]
Please, this is important, i need you to take a look with me :)

**Comment by alonsogarciapablo** [comment]
I'd say all the Backbone overrides should also be included in `embed.js`, cause files like `public_like.js` depend on them to work correctly.

Also, would it make sense to include this:
```
cdb.config.set('url_prefix', window.base_url);
```
In the [config.js](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/config.js) file?

**Comment by viddo** [comment]
Is there some argument for not always include the app for all bundles? It's not that big so should not really have any negative impact on page load, and in terms of maintenance and expected behavior on the models it would be easier if they behave in the same way consistently.

**Comment by xavijam** [comment]
@alonsogarciapablo: further to config change, yes, agree.
About adding app.js... yes, we could do it, but we suffer a problem in the past (1-2 months ago) with a change in that file and failing silently in the embed_map. No sure.

**Comment by javisantana** [comment]
I do prefer to have the embeds as clean as possible but in this case @viddo is right, app.js is really small.

**Comment by alonsogarciapablo** [comment]
`embed.js` was created [here](https://github.com/CartoDB/cartodb/commit/835006e68b151d92800880ccfcfc27d97e049ba4). The argument for this change was that `app.js` included some code related to the editor which wasn't needed in embeds. But it's true that it doesn't include so much extra stuff... Should we revert that change?

**Comment by xavijam** [comment]
We could add it again yes, and run some tests in staging.
