### ISSUE TITLE
After interacting with the editor, the table gets stuck

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#4542]
I've seen this in my browser. Restarted browser, replicated. Also replicated on someone elses account

![unscrol](https://cloud.githubusercontent.com/assets/370259/8756086/884cebac-2c9d-11e5-8fa3-5023dab3c9de.gif)

**Comment by saleiva** [comment]
@xavijam did a fix for this

**Comment by xavijam** [comment]
No no, I made a fix after deleting a column, but @andrewxhill is showing us the editor without scroll from the beginning. In any case, I need more details:

- Is the new_modals flag enabled?
- Is it still happening?
- Could you share your dataset to reproduce the same environment in my local?
