### ISSUE TITLE
Full screen button does not work in Google Chrome

### ISSUE THREAD

**Issue by jatorre** [CartoDB/cartodb#4543]
Checkout this page:

http://mashable.com/2015/07/17/schumer-thrones-google-emmys/

Chlick on the fullscreen button of the map and nothing happens.

Looking the error console I can see this.

Which says "requestFullscreen() is deprecated on insecure origins, and support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details."

![screen shot 2015-07-17 at 3 30 32 pm](https://cloud.githubusercontent.com/assets/127803/8756569/e9b1bc2e-2c98-11e5-82ac-894e5aabdbef.png)

**Comment by xavijam** [comment]
Basically fullscreen feature is not working under http protocols anymore. I'm looking for a way to know if we could "hide" the fullscreen button when origin is http.

**Comment by xavijam** [comment]
This bug has to be fixed in CartoDB.js -> https://github.com/CartoDB/cartodb.js/pull/674
