### ISSUE TITLE
Map on New edit metadata modal doesn't work with small polygons datasets

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#4552]
It never renders anthing to me, plus there is a white gradient overlapping it.
<img width="1392" alt="screen shot 2015-07-19 at 12 55 57" src="https://cloud.githubusercontent.com/assets/132149/8765641/9d4b9264-2e15-11e5-8863-0d43d400d7be.png">

**Comment by saleiva** [comment]
Try with https://team.cartodb.com/u/saleiva/tables/sf_building_footprints_1/map

**Comment by viddo** [comment]
The visual bug is already fixed (not deployed yet though), the other was due to a bug in cartodb.js, fixed in https://github.com/CartoDB/cartodb.js/pull/610, will have to update cartodb once it's merge there to fix this.

**Comment by viddo** [comment]
w/ fix :+1: <img width="1677" alt="screen shot 2015-07-20 at 17 56 33" src="https://cloud.githubusercontent.com/assets/978461/8780347/b4a6b0b2-2f08-11e5-8957-81713cd8add7.png">

**Comment by saleiva** [comment]
<3
