### ISSUE TITLE
Some texts are almost not visible in safari

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#4553]
This is important for pecan

<img width="1037" alt="screen shot 2015-07-19 at 13 11 05" src="https://cloud.githubusercontent.com/assets/132149/8765663/affcec3a-2e17-11e5-8b2e-91baa8af8786.png">

**Comment by xavijam** [comment]
![screen shot 2015-07-20 at 12 37 17](https://cloud.githubusercontent.com/assets/132146/8774307/02315d22-2edd-11e5-81e1-a292d1e08160.png)
