### ISSUE TITLE
Creating a new map with an URL that retrieves more than one file should add all layers to the map and not to different maps

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#4556]
Like an osm export

**Comment by Kartones** [comment]
uhmm, this is a non-trivial change, the whole platform works by adding stuff as tables, not layers inside a single table. Are we sure we want to attack this? /cc @javisantana 

BTW, OSM imports also create multiple tables:
![image](https://cloud.githubusercontent.com/assets/2085449/8771227/eaad6c72-2ebe-11e5-972b-4b916779b6e0.png)

**Comment by saleiva** [comment]
Is a map, with the tables. Not layers in a table

**Comment by javisantana** [comment]
this needs to be designed internally, not an easy change

**Comment by Kartones** [comment]
If is only for the map I can reuse stuff I've done for Instagram import (the "after import decorator") but it requires a few changes, is still not trivial.

For example we're currently not creating a map if import generates N tables (and I think this logic is handled frontend-side). Also only doing this on url-based imports but not the rest (e.g. why not ArcGIS? Why not an OSM or KML import?) is going to be weird, no? 
Can be done as a "test", but if we then left applying this to other sources/formats until later it will behave differently depending on the import source.

Anyway, I'm glad to improve the Importer, just warning that is a quick change so we all have it into account and plan accordingly

**Comment by javisantana** [comment]
No quick changes, we need a clear strategy here on what the importer creates (tables, layers and styles) based on imported files. This is a full feature and needs a wiki page

Think that with pecan we already started to analyze datasets to create wizards that match the dataset, that should be part of the import process.

**Comment by saleiva** [comment]
Yep, no problem on creating a wiki page.
