### ISSUE TITLE
Background importer remains visible after finishing an import and says "connecting data..."

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#4558]
I think this is due to the use of the component on pecan. We shouldn't keep it on the imports.

**Comment by javierarce** [comment]
I dragged a dataset from the dashboard, the file was imported and I was redirected to the map.

**Comment by saleiva** [comment]
and in datasets?

**Comment by javierarce** [comment]
Same correct behaviour.

**Comment by saleiva** [comment]
ok, close then. I cannot replicate this neither
