### ISSUE TITLE
A zip of raster files should import all the files as tables

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/cartodb#4562]
As you can import multiples files for SHP, KML, etc, you should be able to import multiples raster files inside a zip or compressed file.

**Comment by Kartones** [comment]
They do work... so probably you hit a platform limit or similar, but I can in live right now import multiple geotiffs inside a zip:

![image](https://cloud.githubusercontent.com/assets/2085449/8907622/7f751d9c-3477-11e5-9ce9-dc618b05c3f0.png)
