### ISSUE TITLE
Templating infowindows modal

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#4570]
![screen_shot_2015-07-20_at_14 35 31_720](https://cloud.githubusercontent.com/assets/596509/8776131/1a65592c-2eef-11e5-877f-b89f516d0269.png)

**Comment by josecruz** [comment]
@saleiva what do you think?
![screen shot 2015-07-22 at 12 27 33 pm](https://cloud.githubusercontent.com/assets/596509/8823449/21bc8a5e-306d-11e5-8172-d096786569c8.png)

**Comment by josecruz** [comment]
Last update after talk with @saleiva 
![map editor - infowindow modal](https://cloud.githubusercontent.com/assets/596509/8827606/ef30d2ea-308d-11e5-91ec-a4eb03d552f9.png)

**Comment by saleiva** [comment]
:green_heart:

**Comment by josecruz** [comment]
:+1:
