### ISSUE TITLE
Add templates tab on actual create map modal window

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#4585]
so we remove the extra click that we want to remove on the redesign anyway

**Comment by xavijam** [comment]
Sorry dude, I don't get what you say, could you elaborate a bit more? Please :).

**Comment by saleiva** [comment]
Please, prioritize this when being back from holidays.
In those cases we don't have templates, we will put the boxes with the videos there...

**Comment by xavijam** [comment]
Stuff:

1. Create a new modal for only videos.
2. Open that window when user clicks over "suggested maps".
3. Check create map or dataset is working properly.

**Comment by xavijam** [comment]
@josecruz @saleiva Don't we created a single modal window only for this videos functionality? Or should this stuff be inside that section and not a new modal?

**Comment by josecruz** [comment]
@xavijam I think you're talking about this screens right?

![create - template selector - empty map - datasets copy 3](https://cloud.githubusercontent.com/assets/596509/9327846/3319f380-45a4-11e5-99ce-4dbf6f1a335f.png)
![create - template selector - empty map - datasets copy 5](https://cloud.githubusercontent.com/assets/596509/9327847/331e709a-45a4-11e5-8047-acf28a884cd2.png)

**Comment by xavijam** [comment]
Yep.

**Comment by josecruz** [comment]
So yep, it's done, do you need anything more?

**Comment by xavijam** [comment]
I need to know if this should be in a new modal window or if it should be under a section in the create modal window.

**Comment by xavijam** [comment]
@alonsogarciapablo, we will need to review these changes, this is gonna be a fun party for workflow-templates :dancer:

**Comment by josecruz** [comment]
@saleiva what do you think about the alignment of this buttons?
<img width="666" alt="screen shot 2015-08-20 at 18 02 48" src="https://cloud.githubusercontent.com/assets/596509/9388448/c3930484-4765-11e5-8daa-5527f554dc06.png">

**Comment by saleiva** [comment]
I'd not add the arrow one since we never use it on those modals. Closing in this case should do the same.

**Comment by xavijam** [comment]
But it could let you to visit the map templates list. But there is no problem to remove if we agree, super easy dizzy.

**Comment by saleiva** [comment]
What?

**Comment by xavijam** [comment]
That arrow will show the videos list again:

![905e6bd4-4743-11e5-9926-2b5db1f1c122](https://cloud.githubusercontent.com/assets/132146/9394768/a1040ce0-478a-11e5-9f84-4da9df58f51b.png)

**Comment by saleiva** [comment]
Wich arrow dude? Im lost

**Comment by saleiva** [comment]
So the text on the nodal footer opens this modal, closing removes this
modal. That's it. If having templates this modal disappear and the
templates tab appear

**Comment by xavijam** [comment]
https://github.com/CartoDB/cartodb/pull/5144
