### ISSUE TITLE
Notifications part in user profile page

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/cartodb#4592]
When I started working on the issue #1410 one of the required features was "provide the possibility to unsubscribe the user from the notification". 

This feature involves either the possibility to unsubscribe from a notifications using a link in the received email and the possibility to manage all the notifications from a tab in the user profile.

Apart from this we need to have active all the emails we want (maps liked, popular maps, etc)

**Comment by ethervoid** [comment]
This new part will be a new tab in the user profile or we are going to add notification options to an existent tab?

**Comment by ethervoid** [comment]
Another thing that I need is the response to the unsubscribe link that its in the email

**Comment by saleiva** [comment]
In order to have this we will need the following notifications implemented (Feel free to open related issues @ethervoid)
- [x] Long import finishes.
- [ ] Long geocoding finishes.
- [ ] Liked received on maps and datasets
- [ ] Popular map
- [ ] Maps shared / stop shared with you.

Promotional module
- [ ] Newsletter (should send unsubscribe to hubspot)

**Comment by ethervoid** [comment]
Could you give more info about the newsletter notification to put as an issue?

**Comment by saleiva** [comment]
Is a mail sent from hubspot. @matallo can help you there

**Comment by saleiva** [comment]
Designed in the new settings area. I guess we will add it there when we start with that.

**Comment by juanignaciosl** [comment]
Design ([source](https://projects.invisionapp.com/share/P43R5D79K#/screens/93103195)):

![screen shot 2015-08-05 at 11 23 27](https://cloud.githubusercontent.com/assets/932968/9082454/6b65bcc8-3b64-11e5-92ae-ce5484e28ab6.png)

**Comment by MariaCheca** [comment]
Hi, in case the texts in the redesign differ from the current ones, is ok to update them?

cc/ @brittanymicek @csobier

**Comment by juanignaciosl** [comment]
Texts at the design seem fine, use design ones. @brittanymicek @csobier will suggest any change to them if there's something wrong.

**Comment by MariaCheca** [comment]
Copy that :+1:

**Comment by csobier** [comment]
Suggested revised,Configuration UI dialog, as follows. I used any references to the actual product interface whenever possible. Note that I have some writer comments below.  Also, note that email is one word.

Select your email notification preferences

**Import confirmation**
Receive a confirmation email after a large import completes (longer than three minutes).

**Georeference confirmation**
Receive a confirmation email after georeferencing a dataset (longer than five minutes).

**Liked maps and datasets**
Receive a notification when any of your public maps or datasets are "Liked"
*writer note: maybe add an image of the Like icon at the end of this description?*

**Popular maps**
Receive a notification when any of your public maps or datasets are "visited" more than ## times, making it a popular map
*writer note: maybe add an image of the visit icon at the end of this description?  And I don't know how many visits makes it popular? @josecruz *

Subscribe to our promotional emails

*Monthly newsletter*
Subscribe to our monthly newsletter to receive all of the latest news from CartoDB

**Comment by josecruz** [comment]
Uhmm not sure if we should add an icon there, @saleiva what do you think?

**Comment by brittanymicek** [comment]
When something important happens we want to let you know. Please select your email notification preferences.

**Import complete**
Receive a confirmation email when an import that takes more than 3 minutes finishes.

**Geocoding complete**
Receive a confirmation email when a geocoding process of more than 5 minutes finishes.

**Liked maps and datasets**
Receive an email when any of your public maps or datasets are “liked.”

**Popular maps**
Receive an email when any of your maps become popular.

**Subscribe to our promotional emails**

**Monthly Newsletter**
Receive all of the latest news from CartoDB.

**Comment by MariaCheca** [comment]
Needed texts to connect to 3rd party services in user account preferences.

The services are **Dropbox, GDrive, Instagram and Mailchimp** (GDrive and Mailchimp appear in the designs as you can see in the image below, but would be nice revise them anyway):

![screen_shot_2015-08-20_at_1_14_01_pm](https://cloud.githubusercontent.com/assets/2141690/9382228/18ff201e-473f-11e5-960f-e15f1704a242.png)

cc/ @brittanymicek @csobier

**Comment by csobier** [comment]
Note the following context, and spelling, changes.

Account and 3rd party services connected, change to "Connect to external data sources"

Google Drive 
MailChimp

(For Google Drive and MailChimp, I would suggest mirroring the current Account page for Google Drive format to be consistent, see example screenshot below)

![image](https://cloud.githubusercontent.com/assets/13319925/9382834/10bb8bea-4712-11e5-80ae-1bade9dae156.png)

**Comment by saleiva** [comment]
What I'm blocking here?

**Comment by ethervoid** [comment]
Not blocking, I don't know the current status of this issue

* It seems like @MariaCheca is making the redesign
* I have to:
  * create the trending map notification
  * manage the subscription / unsubscription agains hubspot
  * Create the logic to act agains the new user notifications screen
