### ISSUE TITLE
Share button doesn't work from inside the Editor

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#4599]
Hey there,

Not a bug report but actually a discussion thread. What's the behaviour that you would expect when clicking in the "share" overlay inside the Editor?

Right now, it doesn't have any effect, while in an embed map a sharing modal window appears.

cc @saleiva @xavijam

**Comment by xavijam** [comment]
It was done on purpose, it appears as static, becuase it doesn't make any sense share your private map. In any case we will revisit this behaviour with the new editor. Closing guapita :)!
