### ISSUE TITLE
Send e-mail when a long geocoding it's finished

### ISSUE THREAD

**Issue by jsanz** [CartoDB/cartodb#4604]
When a long geocoding process is finished, it'd be nice to receive an email with statistics of the results and so on.

This is related with #4019

**Comment by ethervoid** [comment]
To clarify you want to add more statistics to the import finish email? What kind of statistics?

**Comment by jsanz** [comment]
There is no email at all, yesterday I had to run very long geocoding
processes and having to look on the screen to see if it was finished or not
(and it took hours) was a bit inconvenient.

Having statistics on the number of geocodings, success and fails and timing
would be just an enhancement, the mail is the main thing :)

On Wed, Jul 22, 2015 at 3:23 PM, Mario de Frutos <notifications@github.com>
wrote:

> To clarify you want to add more statistics to the import finish email?
> What kind of statistics?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/4604#issuecomment-123717876>.
>



-- 
Jorge Sanz
Solutions Engineer
CartoDB · Map Your World's Data

**Comment by ethervoid** [comment]
There is a notification configured to send the email when the data import finish with all the next conditions:
* The import time ellapsed was 300 seconds or more
* It's not a sync table

If you don't received that email could be a bug in that part

**Comment by jsanz** [comment]
On Wed, Jul 22, 2015 at 3:40 PM, Mario de Frutos <notifications@github.com>
wrote:

> There is a notification configured to send the email when the data import
> finish with all the next conditions:
>
>    - The import time ellapsed was 300 seconds or more
>    - It's not a sync table
>
> If you don't received that email could be a bug in that part
>
>
Well we're not talking about imports here but about *geocoding*, they're
different processes.

Sorry I didn't realised that in your previous comment.

**Comment by ethervoid** [comment]
Ah! Ok you're absolutely right, I was talking about the importer. My bad
