### ISSUE TITLE
Broken doc links on https://github.com/CartoDB/cartodb/blob/master/doc/frontend/README.md

### ISSUE THREAD

**Issue by vishalya** [CartoDB/cartodb#4605]
The links on the page https://github.com/CartoDB/cartodb/blob/master/doc/frontend/README.md are broken for any of the documents.

**Comment by saleiva** [comment]
hey @iriberri can you talk to whoever could work on this?

**Comment by saleiva** [comment]
hey @iriberri can you talk to whoever could work on this?
