### ISSUE TITLE
http instead of https is used in api key page example urls

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#4611]
https urls should be used 

![screen shot 2015-07-22 at 8 47 51 am](https://cloud.githubusercontent.com/assets/30147/8819663/6d7465b2-304e-11e5-8a94-fbfe24b44727.png)

**Comment by saleiva** [comment]
Alignement is wrong also. @josecruz could you help @juanignaciosl with this?

**Comment by juanignaciosl** [comment]
@saleiva left labels are vertically aligned in the middle. The problem at the previous screenshot is that Santana has hacked his api key to `RAMBO`, but with a valid api key design looks right:

![screen shot 2015-07-22 at 13 47 45](https://cloud.githubusercontent.com/assets/932968/8824671/48b85da8-3078-11e5-90e5-f626345c208e.png)

**Comment by javisantana** [comment]
hey, try to leave "easy" issues for the people is starting with cartodb development

**Comment by juanignaciosl** [comment]
Ok, I was just editing that page for #4404 when you sent the issue.

**Comment by saleiva** [comment]
Even tho, is wrong IMO. texts should be aligned on the baseline of the first line

**Comment by josecruz** [comment]
Agree with @saleiva about the alignment

**Comment by juanignaciosl** [comment]
This way then, ok?

![screen shot 2015-07-22 at 16 45 33](https://cloud.githubusercontent.com/assets/932968/8828187/2e474d26-3091-11e5-9635-aa0bf5bcf2f2.png)

**Comment by josecruz** [comment]
Yup! :+1:
