### ISSUE TITLE
Update Multiuser mockups with the production version

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#4632]
Please, high priority as we need to start working on this next sprint. Let's do this on 0.4 version. Don't forget any page

**Comment by josecruz** [comment]
@saleiva this file name is `Multiuser-0.4.sketch` could you please review it and tell me if there's something missing?

I removed a folder called `04-Configuration` because all changes I made about user settings are under Multiuser folder.

I still having a local copy of that folder, JIC

**Comment by josecruz** [comment]
Talked about this in slack and updated missing details, closing it
