### ISSUE TITLE
Style for the unsubscribe links in mails

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/cartodb#4638]
In need to give style this unsubscribe link. For example:

https://github.com/CartoDB/cartodb/pull/4620/files#diff-05350410eae9880577a48ada7f2297b3R55

If you could help me, i could apply that style to all the links that need it :)

**Comment by matallo** [comment]
![screen shot 2015-07-23 at 14 18 02](https://cloud.githubusercontent.com/assets/36676/8850133/a8cdeafa-3145-11e5-8700-bca1742a1967.png)

**Comment by ethervoid** [comment]
Beautiful, thank you @matallo
