### ISSUE TITLE
Screen that the user see when he clicks in the unsubscribe link

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/cartodb#4640]
When a user receives a notification email, he could unsubscribe clicking in a link at the bottom. That link redirects the user to a screen where he's informed that has been successfully unsubscribed.

I need a design for that.

Thank you!

// @saleiva

**Comment by carlostallon** [comment]
Copy is just a placeholder:
![successfully unsuscribed](https://cloud.githubusercontent.com/assets/1712650/8849782/b894853c-3142-11e5-975b-070150ec03ae.png)

**Comment by ethervoid** [comment]
Great work!

Just to clarify, just in case, I have to say, my bad, that the unsubscribe is by type of notification. For example shared table, shared viz, data import, maps likes, etc. I think is the same screen but with different text.

**Comment by carlostallon** [comment]
Yep, we should keep the same design and just change the text ; )

**Comment by ethervoid** [comment]
Where are the resources to layout this? thx

**Comment by carlostallon** [comment]
Hi @ethervoid close this issue if you consider. Do you need help for the ui development?

**Comment by carlostallon** [comment]
I will send you by email, do you have sketch?

**Comment by matallo** [comment]
would be great to have one too for subscribed (currently redirected to cartodb.com)

**Comment by carlostallon** [comment]
Hi @matallo. I assign it to you because this is one of the "feedback pages" collection. So maybe we need to consider how to make an standard UI Development for all. I will send to you an email with the sketch with all the cases that we should implement at any point.

@mariodelvalle can help us with this

**Comment by carlostallon** [comment]
@matallo we also have it :)

**Comment by matallo** [comment]
+1000

On Fri, Jul 31, 2015 at 12:06 PM, Carlos Tallón <notifications@github.com>
wrote:

> Hi @matallo <https://github.com/matallo>. I assign it to you because this
> is one of the "feedback pages" collection. So maybe we need to consider how
> to make an standard UI Development for all. I will send to you an email
> with the sketch with all the cases that we should implement at any point.
>
> @mariodelvalle <https://github.com/mariodelvalle> can help us with this
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/4640#issuecomment-126632361>.
>



-- 
*Carlos Matallín*
UI developer

*CartoDB—Map Your World's Data*
C/ Eloy Gonzalo, 27, 3, 28010, Madrid, Spain
T: +34911165823
W: www.cartodb.com

Live sessions to learn CartoDB <http://cartodb.com/webinars/>

**Comment by carlostallon** [comment]
![successfully suscribed](https://cloud.githubusercontent.com/assets/1712650/9005304/608ad3f0-377d-11e5-8bdf-dffe63599bd8.png)

**Comment by mariodelvalle** [comment]
Of course :+1:

**Comment by mariodelvalle** [comment]
In the unsubscription could be interesting to give the user the opportunity to give us feedback of why unsubscription to improve service in the future through a link that will send a mail to support. What do you think?

**Comment by saleiva** [comment]
Like what @mariodelvalle proposes!

**Comment by ethervoid** [comment]
Were are the resources for the unsubscribe screen to do it?

**Comment by matallo** [comment]
I moved this to the next milestone

**Comment by ethervoid** [comment]
Ok, so I put that on hold

**Comment by matallo** [comment]
done
