### ISSUE TITLE
Should we run Pecan analysis when a query is applied?

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#4660]
I feel we should not do it. Also I've found there is a JS bug running the analysis when a dataset has a query applied.

cc @javierarce @ohasselblad

**Comment by javierarce** [comment]
We could disable it, yes, since the idea of Pecan is to offer suggestions for the less cartographically inclined. 

What do you think, @saleiva and @javisantana?

**Comment by iriberri** [comment]
I have just found: 
```
2tracker.js:4 Uncaught Error: TrackJS Caught: Cannot read property 'bbox' of undefined
````

Also, Pecan is stuck in column 3/5 but there are actually 3 possible columns to check (the rest are the timestamps, cdb_id and the geoms)

This map was also affected by the bounding box issue and centered in Null Island

**Comment by javierarce** [comment]
@iriberri: did the query excluded the geometry column by any chance?

**Comment by iriberri** [comment]
This is the query (with anonymous data now :):

````
SELECT 
      b.cartodb_id,
      b.the_geom,
      b.the_geom_webmercator,
      pcodes_city,
      ev_count,
      postal_code
FROM b, a
WHERE true
      and a.zip = b.postal_code
````

**Comment by javierarce** [comment]
Excellent, thanks!

**Comment by ohasselblad** [comment]
I think it would be wonderful to offer the ability to trigger pecan when a custom query is applied. I vote for someone triggering it themselves (not automatic), or it showing in the banner that also says 'create dataset from query'.. something like that.
