### ISSUE TITLE
[Export Image] When you get out the canvas, the black background breaks

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#4666]
#### Steps to reproduce

1. Click export image
2. Get outta canvas with the image cropper.

(can't record a gif, licecap is broken :disappointed: ) but I talked in person with Javier Arce.

**Comment by javierarce** [comment]
I'm closing this, since this has already been fixed in this issue: https://github.com/CartoDB/cartodb/issues/4685
