### ISSUE TITLE
Remove old modal code

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#4673]
Clean up the code that got replaced by the new modals:

- [x] `new_modals` feature flag usage
- old modals:
  - [x] adhoc-BaseDialog extended modals - old_common/views/confirm_dialog
  - [x] cdb.admin.AssetManager
  - [x] cdb.admin.GeocoderWorking
  - [x] cdb.admin.BaseMapAdder
  - [x] cdb.admin.CreateErrorDialog
  - [x] cdb.admin.CreateLayerDialog
  - [x] cdb.admin.CreateVizDialog
  - [x] cdb.admin.DeleteVisualizationDialog
  - [x] cdb.admin.DuplicateTableDialog
  - [x] cdb.admin.DuplicateVisDialog
  - [x] cdb.admin.DeleteDialogItem
  - [x] cdb.admin.EditFeatureFields
  - [x] cdb.admin.ExportTableDialog
  - [x] cdb.admin.FilterColumnDialog
  - [x] cdb.admin.GeocodingDialog
  - [x] cdb.admin.NoGeoRefDataDialog
  - [x] cdb.admin.LockVisualizationDialog
  - [x] cdb.admin.MergeTablesDialog
  - [x] cdb.admin.MetadataDialog
  - [x] cdb.admin.NewColumnDialog
  - [x] cdb.admin.NewGeometryDropdown
  - [x] cdb.admin.PrivacyDialog
  - [x] cdb.admin.ShareController
  - [x] cdb.admin.ShareDialog
  - [x] cdb.admin.SyncNowModal
  - [x] cdb.admin.SyncSettings
  - [x] cdb.admin.UpgradeDialog
  - [x] cdb.common.CreateDialog
  - [x] cdb.admin.Import*
  - [x] cdb.admin.TableBigLoader
  - [x] export options, API modal - done in [#4967](https://github.com/CartoDB/cartodb/pull/4967)
  - [x] infowindows help modal
- implicit stuff that now can be removed due to the above:
  - [x] cdb.admin.BackgroundTab
  - [x] cdb.admin.GeocodingResult
  - [x] geocodeLatAndLng
  - [x] pecan modal, refs to old modal
  - [x] cdb.admin.BaseDialog
  - [x] old, now unused, CSS
  - [x] old, now unused assets (images)
  - [x] old, now unused vendor libs (jquery.fileupload*)
  - [x] old export modal, replaced by [new one](https://github.com/CartoDB/cartodb/pull/4809)

**Comment by viddo** [comment]
cc @gfiorav

**Comment by viddo** [comment]
> look what old/potentially unused libs there are that can be removed
jquery.fileupload-fp.js
jquery.fileupload.js
jquery.fileupload-ui.js
...

**Comment by gfiorav** [comment]
Thanks for pointing this out! I'll sort the feature flag business out :)
