### ISSUE TITLE
Reduce the amount of columns imported on the twitter connector

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#4674]

**Comment by danicarrion** [comment]
Please let me know when you decide which ones to import so that I can update our powertrack script accordingly.

**Comment by saleiva** [comment]
I'd keep the following ones
 link
 body
 objecttype
 postedtime
 favoritescount
 twitter_lang
 retweetcount
 actor_id
 actor_displayname
 actor_image
 actor_summary
 actor_postedtime
 actor_location
 actor_utcoffset
 actor_preferredusername
 actor_friendscount
 actor_followerscount
 actor_listedcount
 actor_statusescount
 actor_verified
 inreplyto_link
 geo
 twitter_entities
 location_geo
 location_name
 category_name
 category_terms

**Comment by saleiva** [comment]
@CartoDB/solutions please take a look to be sure that I'm not removing any popular column

**Comment by danicarrion** [comment]
looks good to me, although @jsanz is the one who's been working with this lately

we're adding a way for the user to select which columns to upload to cartodb, so this list will act as the superset for us

**Comment by jsanz** [comment]
Reviewed, looks good to me, so these are then the columns to be removed

```
actor_languages
actor_link
actor_links
actor_objecttype
actor_twittertimezone
generator_displayname
generator_link
gnip
id
location_displayname
location_link
location_objecttype
location_streetaddress
object_id
object_link
object_objecttype
object_postedtime
object_summary
provider_displayname
provider_link
provider_objecttype
twitter_filter_level
verb
```
