### ISSUE TITLE
add a rake tasks to manage feature flags

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#4677]
- add a new feature flag
- enable/disable for everybody/an user/an organization

**Comment by gfiorav** [comment]
On it

**Comment by gfiorav** [comment]
Still working on organizations.

Follow this ["PR"](https://github.com/CartoDB/cartodb/pull/4701)

**Comment by gfiorav** [comment]
It turns out that this effort is partially replicated here: https://github.com/CartoDB/cartodb-management/wiki/Feature-Flags

Nevertheless I'll add tasks to add and delete to all organization since these tasks also provide delete functionality.

**Comment by gfiorav** [comment]
All functionality has been implemented and the code is waiting for revision in [PR](https://github.com/CartoDB/cartodb/pull/4701)

cc @javisantana

**Comment by saleiva** [comment]
Can we also try to remove those feature flags that are not longer needed?

**Comment by gfiorav** [comment]
Sure thing!

I'll tackle it tomorrow morning.

**Comment by gfiorav** [comment]
PR #4701 merged
