### ISSUE TITLE
Replace old missed modals with new ones

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#4683]
While working on replacing what I thought was the last modals (#4682) I found a few others that all of us missed (so can't be commonly used). They need to be migrated though to be able to remove the old code planned for next/upcoming milestone:

**deletion:**
- [x] confirm delete slide (odyssey) in [table/slides/panel.js#L301-L313](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/table/slides/panel.js#L301-L313)
<img width="587" alt="screen shot 2015-07-24 at 15 40 18" src="https://cloud.githubusercontent.com/assets/978461/8875545/4e6e817a-321a-11e5-8ca1-6a965af845ed.png">

**warnings:**
- [x] show Gmaps deprecation in [table/mapview.js#L356-L369](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/table/mapview.js#L356-L369)
<img width="823" alt="screen shot 2015-07-24 at 15 35 18" src="https://cloud.githubusercontent.com/assets/978461/8875460/a3a1e20a-3219-11e5-8187-651a81347eb0.png">

- [x] confirm edit geom in [table/geom_editor.js#L167-L179](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/table/geom_editor.js#L167-L179)
<img width="657" alt="screen shot 2015-07-24 at 15 39 03" src="https://cloud.githubusercontent.com/assets/978461/8875528/23ade28c-321a-11e5-953c-ba3b910460d7.png">

**Comment by xavijam** [comment]
go man go!
