### ISSUE TITLE
Edit metadata window is trimming the last character of a text when overriding

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#4687]
**Steps:**
* Go to an existent table (small enough so that you can see the data for all rows)
* Go to the map view and try to edit the metadata of a feature that already contains some text:

![image](https://cloud.githubusercontent.com/assets/1730320/8878458/49f0f7f2-322b-11e5-8cda-ec7260754441.png)

I wrote: " oh yeah", and the result was: 

![image](https://cloud.githubusercontent.com/assets/1730320/8878481/74aef89a-322b-11e5-8bea-b3b1408fc103.png)

The last character of the text does seem to be skipped.

**More info:**
* It doesn't seem to happen always, my first time doing the steps spotted the issue but the next times it was hard to replicate again. 
* It doesn't happen with empty boxes -  Users are removing all the content and writing again in order to workaround the issue

**Comment by iriberri** [comment]
cc @xavijam @javierarce

**Comment by iriberri** [comment]
SB/6059853

**Comment by xavijam** [comment]
on it
