### ISSUE TITLE
Field values destructively converted without warning (NASTY)

### ISSUE THREAD

**Issue by stevage** [CartoDB/cartodb#4689]
I just imported a file with a `FileName` column that looks like this:

<img width="365" alt="screenshot 2015-07-26 20 13 58" src="https://cloud.githubusercontent.com/assets/678344/8893422/ea5e6780-33d2-11e5-8f17-714ee505e03a.png">

That is, each `sourcefile` value is a JPEG in `YYYY-MM-DD hh.mm.ss.jpg` format. This isn't contrived data, this is as provided by a client.

## Bug 1

First, the import gets messed up:

![screenshot 2015-07-26 20 15 43](https://cloud.githubusercontent.com/assets/678344/8893429/1e8f6536-33d3-11e5-87c9-e4fd6ecc66ab.png)

That's really bad. It ignored the '.jpg' and decided that my field values were "close enough" to dates, and destructively coerced them into being `date`s. If there's any way to undo this, I'm not aware of it. (I guess you have to reimport and unselect 'guess types')

It gets worse.

Let's go into the map view and edit a point.

## Bug 2

![screenshot 2015-07-26 20 18 17](https://cloud.githubusercontent.com/assets/678344/8893448/b02eaa38-33d3-11e5-8695-49aa62ebc329.png)

What's that drop down on the right hand side do?

It's not intuitive (to me) that changing the value of this drop down changes the type of the entire column. I thought I was just selecting a different editor to edit the current value with. So out of curiosity I picked `Number`.

## Bug 3

![screenshot 2015-07-26 20 18 23](https://cloud.githubusercontent.com/assets/678344/8893450/bcaf8642-33d3-11e5-94a2-684cf8eb5621.png)

Wait, what?? It just destructively replaced every value in my column with a number, with no warning?

![screenshot 2015-07-26 20 18 38](https://cloud.githubusercontent.com/assets/678344/8893453/db2622ca-33d3-11e5-8d76-bbd5f7735fc3.png)

## Bug 4

Moving on, check out the drop down now:

![screenshot 2015-07-26 20 18 53](https://cloud.githubusercontent.com/assets/678344/8893456/f521b644-33d3-11e5-8528-115dc5abb8b3.png)

Our options for (destructive, warning-less) conversion now are "string, string, boolean". 

## Bug 5

Let's go with boolean.

![screenshot 2015-07-26 20 18 58](https://cloud.githubusercontent.com/assets/678344/8893460/1a564038-33d4-11e5-8e64-691667d97250.png)

Yep, it will happily replace every value in a column with `true`s and `false`s with no warning. And for a finale, you can convert back to `date` and get this nonsense result (I assume it's the current time plus 1 second or something):

![screenshot 2015-07-26 20 19 12](https://cloud.githubusercontent.com/assets/678344/8893466/3ef4bc4e-33d4-11e5-988d-48c07563c3bc.png)

Converting boolean to date is probably not an option that needs to be provided...

## Bug 6

And the end result of all that...

![screenshot 2015-07-26 20 25 00](https://cloud.githubusercontent.com/assets/678344/8893471/6fb526c0-33d4-11e5-8185-8251780c2cd7.png)

A column full of `null`s.

**Comment by ohasselblad** [comment]
@stevage, on bug 1, have you tried importing without type-guessing? There's a checkbox you can de-select so that data types are not guessed.

**Comment by stevage** [comment]
Yeah, I have since discovered that. So at least there is a workaround to Bug 1. But one major problem is you don't necessarily know that this problem has occurred, so you could be deep into map creation before you discover that one or more of your columns are broken...

**Comment by saleiva** [comment]
@rafatower can you check bug 1 so we try to make the guesser more intelligent?
