### ISSUE TITLE
Can't select file after pressing <--

### ISSUE THREAD

**Issue by stevage** [CartoDB/cartodb#4690]
1. "Connect a dataset"
2. Select a local file
3. Press the left arrow in a circle to undo the selection
4. Select another local file

![screenshot 2015-07-26 20 38 05](https://cloud.githubusercontent.com/assets/678344/8893523/7998fa2a-33d6-11e5-9c58-0d1f6a41ab61.png)

**Comment by javierarce** [comment]
Hi, @stevage. We've fixed the issue. Thanks for reporting it!
