### ISSUE TITLE
Submenu for column info is out of frame

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#4695]
To reproduce this problem

1. Open table view with browser in fullscreen
2. Click on arrow to display the leftmost column's info

![screen shot 2015-07-27 at 08 24 08](https://cloud.githubusercontent.com/assets/4222826/8903488/ca5ae95a-3458-11e5-9339-5c7823a1901c.png)

Using: Chrome on Mac OSX

**Comment by xavijam** [comment]
Fortunately It will change with the new editor, so closing :).
