### ISSUE TITLE
Hide legend if layer is hidden

### ISSUE THREAD

**Issue by Kartones** [CartoDB/cartodb#4696]
Relates to https://github.com/CartoDB/cartodb.js/issues/609

Branch `4696-hide-legend-if-layer-hidden`

**Comment by Kartones** [comment]
JS code is not honouring `options->legend->visibility` if the items inside are marked as visible:
```
...
visible: false,
legend: {
  visible: false,
  items: [
    {
      ...
      visible: true,
      ...
    }
  ]
...
},
```

@alonsogarciapablo I'm going to check named maps, but without them at least, with two public layers, even if I hide one in this branch (which propagates hidden visibility to the legend if present), it still shows at public map & embed map.
I am not sure going also inside the list of items and hiding each via backend is the proper way to go... @javisantana what do you think?

**Comment by javisantana** [comment]
not sure i understand this but:

- if the layer is not shown the legend is also not shown
- if a layer has no legend it should not be sent

visibility attribute in legend should not exists

**Comment by Kartones** [comment]
Let me properly show an example:

Scenario: 2 layers, visible both, each with a legend.
- You make layer A hidden:
  - In current code `layerA.visibility = false`, `layerA.legend.visibility = true`, `layerA.legend.items[ {...visibility = true}]`
  - At this branch `layerA.visibility = false`, `layerA.legend.visibility = false`, `layerA.legend.items[ {...visibility = true}]`

So, IMO there is a bug because nor Rails app nor editor's JS code should have to toggle of each individual item's visibility if he parent legend is not visible. I've already fixed making the legend visibility "inherit" parent visibility when the later is false (so if you disable the layer, legend goes off too, but if layer is visible legend dictates its own visibility), but the items bug remains.

This is current scenario and my fix one. If you in your last line say "visibility attribute in legend should not exists" then that's another separate issue, and the Editor UI is wrongly sending to the backend a legend when it has become hidden (probably is not touching it, when it should be destroyed, right?).

I'm going to stop changing anything until we decide which is the proper fix.
