### ISSUE TITLE
vis.table.service.rows_counted vs vis.table.row_count

### ISSUE THREAD

**Issue by Kartones** [CartoDB/cartodb#4700]
While fixing https://github.com/CartoDB/cartodb/compare/d7c2f0807266...cb200fd454d7 I found we have two ways of querying the table count:

`vis.table.service.rows_counted` (PG tables query) and `vis.table.row_count` (a Sequel count)

Which one is the intended one to use? because at that code `vis.table.rows_counted` was zero (which is weird, as calling through the service also queries PG classes but returns proper values)

**Comment by juanignaciosl** [comment]
Wow. It's even worse than that: [`::Table` has a `rows_counted` that is a sequel count](https://github.com/CartoDB/cartodb/blob/master/app/models/table.rb#L741), but exposes a [`rows_counted` public method that is an alias to `rows_estimated`](https://github.com/CartoDB/cartodb/blob/master/app/models/table.rb#L45), which probably explains the behaviour you detected.

There're two complementary behaviours that we want to keep: estimation and actual count. I'll take a look at both and set a proper naming.

**Comment by Kartones** [comment]
oh, if aliases to rows_estimated then it does make sense to return a zero. I didn't digged much, thanks for checking... and yes, an appropiate naming would be better so others (or me again :stuck_out_tongue: ) don't get confused. Thanks!
