### ISSUE TITLE
Geocoder support for Admin2 districts

### ISSUE THREAD

**Issue by auremoser** [CartoDB/cartodb#4707]
This issue was originally logged in @stuartlynn 's geocoder repo ([#1] (https://github.com/CartoDB/Geocoding_Analysis/issues/1#issuecomment-125107139)<- wow)

But it is perhaps better here per @iriberri 's recommendation:
Our GDELT partner wrote about what levels of administrative districts to support and I thought this might be a good place to register the concern:

> Your georeferencing option says it supports "administrative regions", but the documentation never actually goes into any detail as whether you define that as an ADM1 and what countries you support? I couldn't find anything more and digging around on the CartoDB GitHub repository I couldn't find the master list of regions you support? I would assume ADM2s are not supported, since GAUL is really the only global dataset I've found that has substantial coverage for all countries, and it has many restrictions on its use and redistribution, but there are a lot of ADM1 shapefiles out there, so wasn't sure what precisely your administrative region georeferencer handles?

> Yeah, I can always go find some ADM1 layers, but was just curious what CartoDB supports natively, since I want to make it easy for others to repeat my maps and make their own... :-)

**Comment by iriberri** [comment]
I'm closing the issue as now this is becoming more a Data Observatory / Data Services task that is already issued. Previously we were providing geocoding in the Editor, but with the new Builder and the analyses the geocoding responsibilities are no longer in the Carto project.
