### ISSUE TITLE
Spatial join tooltip appears in a weird position

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#4709]
When hovering "sum" or "avg":

![image](https://cloud.githubusercontent.com/assets/1730320/8909059/c425948c-347f-11e5-8987-db4448ac7b9e.png)

The tooltip seems to be appearing correctly in other screens. I'm working from a MacBook Air 11" and the window is 1400x658 approx.

cc @viddo

**Comment by viddo** [comment]
It happens consistently? Or can you try deduce to some minimal steps of how to reproduce it? I've been trying on my computer (13", trying various resolutions) and have not been able to reproduce just yet :/

**Comment by iriberri** [comment]
In @oriolbx computer works like a charm too, in my computer it happens always, let me investigate a bit more about it but is the behaviour I experience in all cases

**Comment by xavijam** [comment]
Checked with @iriberri and seems like it is working now :clap: .
