### ISSUE TITLE
No translation for Mercator_Auxiliary_Sphere to PROJ.4 format is known

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#4710]
Very commonly this error appears when importing Shapefiles. I'll updated with a test file.

**Comment by iriberri** [comment]
http://gis.stackexchange.com/questions/61823/ogr-projection-transformation-error

**Comment by rafatower** [comment]
is it happening yet? otherwise, any example to reproduce it? (if possible, a public dataset)

**Comment by iriberri** [comment]
Finally got the time to test some more files that got reported time ago. Everything is working like a charm now, and taking a look at the data the reprojection seems fine. 

Closing :-)

**Comment by rafatower** [comment]
You made my day :smile: @iriberri
