### ISSUE TITLE
First map UX is confusing

### ISSUE THREAD

**Issue by stevage** [CartoDB/cartodb#4735]
I've now taught three CartoDB workshops since the new wizard-like interface for new users has been implemented. Unfortunately it seems to be really confusing to users.

## 1

![screenshot 2015-07-28 23 48 15](https://cloud.githubusercontent.com/assets/678344/8932982/c27f2440-3583-11e5-9a7f-15c4d4e52f08.png)

This small wall of text is well intentioned but has some issues:

1. They don't know what "your dashboard is" (the thing underneath doesn't say "dashboard" anywhere, and the fact that it has a big scrolling map is super confusing)
2. Once this text is gone, it never comes back.
3. Letters in circles are not intuitive - especially the other message which has a C in a circle (which looks like a copyright symbol).

Suggestion: shorten this text and make it permanently sit in the place where the map is, as long as you don't have any maps. It should basically just say "Drag a spreadsheet here."

## 2

![screenshot 2015-07-28 23 58 51](https://cloud.githubusercontent.com/assets/678344/8933163/9f960e34-3584-11e5-93f7-85bdf5b338f6.png)

The next screen is confusing again:

1. They just clicked "new map", why do they need to click "create new map"? This seems pointless and mildly annoying.
2. It's really easy to think that the six boxes at the bottom are specialised wizards - the "or start with a video tutorial" is too subtle. I still accidentally go for one of the boxes sometimes. They should *look* like videos, not wizards.

## 3

![screenshot 2015-07-29 00 12 53](https://cloud.githubusercontent.com/assets/678344/8933521/9e42c20a-3586-11e5-92ce-47ec06bcd934.png)

Now, this is the worst. The most likely thing (IMHO) a user wants to do here (at least, my users) is upload a spreadsheet. And yet that target is so hard to find: it's the non-button "Connect dataset" link towards the left. So:

1. The really tempting "Create empty map" link takes you to, well, an empty map - and then it's really hard to know what to do.
2. Also, they've just clicked "new map", then "create new map", so "create empty map" feels pretty much like the right thing to do. "empty" doesn't sound too different from "new".
3. Where's the friendly "drag a dataset here" right when they need it?
4. It also just flows badly. So far they clicked bottom right, then top right, and now the have to go left? Ugh.

## 4

![screenshot 2015-07-29 00 05 41](https://cloud.githubusercontent.com/assets/678344/8933346/9c87e554-3585-11e5-9bbd-430bbe1c3b0c.png)

At the next screen, they're a bit confused again. The "Data file" thing at the top looks very clickable, but it's not. Then there's a big inviting text box, which isn't what they want either. And eventually they see "Select a file". 

## 5

![screenshot 2015-07-29 00 07 28](https://cloud.githubusercontent.com/assets/678344/8933384/d20677b8-3585-11e5-86cb-a4e920261285.png)

Then finally, a couple of users got completely stuck here. They'd selected their dataset file, and they just waited. One thought the computer was broken. 

1.It's not obvious why they need to click "Connect dataset". 
2. And remember, "Connect dataset" was the exact phrase they clicked on previously to start the process of choosing a file to upload - it doesn't feel right to click that same phrase to finish the procedure. 
3. It's a long distance from the filename they just uploaded, and doesn't seem connected at all.

Suggest labelling the button "Finish" or "Done" if it needs to be there at all.

**Comment by saleiva** [comment]
Hi @stevage thanks so much for your feedback. So valuable.

**Comment by javierarce** [comment]
Thanks for the sharing your concerns, @stevage. 

Besides the feedback UX related feedback, I was wondering which browser and OS did you use when you took the first capture? The font is wrong and I'm not sure if it's a bug or just that it wasn't fully loaded when you took the image.

**Comment by stevage** [comment]
Sorry, I was just playing around with an extension that changes default fonts on web pages. I disabled it for the rest of the screenshots. Sorry for the confusion.

I'm on OSX/Chrome. Workshop participants vary quite a lot.

**Comment by stevage** [comment]
![screenshot 2015-07-29 09 48 43](https://cloud.githubusercontent.com/assets/678344/8946787/0862a722-35d7-11e5-87c0-4ad9a1d30d22.png)

For completeness I'll also criticise this page that comes up between step 2 and 3 above.

1. First, the copywriting just isn't good enough. Some very non-idiomatic English here ("on the Data Library", "Thinking on"). Also, what's with the comma at the top ("Create a new map,")?
2. Here's the confusing copyright symbol.
3. Overall, this page is not helpful. Having text flash up that tells you what will happen in the future, or options that are about to be available to you - and then disappears, never to return - only helps the rare user that actually reads and absorbs text the first time they see it. The line "You can also start from scratch" without a decent explanation of *how* you do that is a bit useless.

Overall, it looks like the purpose of this page is to explain three ways to get started. So I just just having those three ways much easier to find in the next page. Currently that page has the perfect placeholder:

>You have not connected any datasets yet
 Start with one of the following datasets from the data library.

It would be an instant improvement, IMHO, to get rid of this screen, and replace the text on the following one:

> **Creating your first map**
> If you have a spreadsheet, drag it here.
> To create data from scratch, click "Create empty map"
> Or choose a dataset from the Data Library below.

**Comment by saleiva** [comment]
Hi @stevage Fixing all this stuff in different issues. Thanks so much for reporting! :) This is very valuable. Do you have cartodb tshirts already? :)

cc/ @iriberri

**Comment by saleiva** [comment]
Also @csobier so you are aware
