### ISSUE TITLE
Create empty map / Create empty links dataset styling 

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#4739]
I'd try to remove the button style and to keep it as a link :)

**Comment by saleiva** [comment]
cc/ @josecruz

**Comment by javierarce** [comment]
Something like that?

![screen shot 2015-07-29 at 11 02 09](https://cloud.githubusercontent.com/assets/4933/8953776/4bfdeee2-35e1-11e5-95a0-b5eb4f3fa251.png)

**Comment by saleiva** [comment]
Same style than the others. Lowercase, no underline.
