### ISSUE TITLE
Selected option on the create map or connect dataset modal should be dark grey instead of blue

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#4740]
cc/ @josecruz

**Comment by javierarce** [comment]
A screen capture, please, I don't know what you mean.

**Comment by javierarce** [comment]
Something like this? (the border color is #666) 

![icons](https://cloud.githubusercontent.com/assets/4933/8960656/516ee856-3611-11e5-9edb-4be6add80d90.gif)

**Comment by saleiva** [comment]
annd the icon please!

**Comment by saleiva** [comment]
well, no, the icon no :) Leave it as it is.
sorry

**Comment by javierarce** [comment]
It's ok. I did a test and the screen looked a bit sad

![new_import_icons](https://cloud.githubusercontent.com/assets/4933/8960848/39de28d6-3612-11e5-854f-c03395884714.png)

**Comment by saleiva** [comment]
Yep, I like more your proposal

**Comment by josecruz** [comment]
Should we change the border color on hover as well?

**Comment by javierarce** [comment]
I'd say to leave them as they are now, to maintain the same behaviour we have with the regular links.

**Comment by saleiva** [comment]
The color in grey, right?

**Comment by javierarce** [comment]
No, hover is light blue. The non-selected state is light grey.

**Comment by saleiva** [comment]
hover leave it, yeah, selected dark grey

**Comment by josecruz** [comment]
:+1:
