### ISSUE TITLE
Remove extra step when not having sync tables when connecting a dataset

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#4741]
<img src="https://cloud.githubusercontent.com/assets/678344/8933384/d20677b8-3585-11e5-86cb-a4e920261285.png"></img>

**Comment by saleiva** [comment]
This only applies to the flow when you select a file, not when adding an URL (for clarification)

**Comment by xavijam** [comment]
Doing it in create-view-fixes branch.
