### ISSUE TITLE
Remove some options from the org. admin list of 'features'

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#4743]
Related with https://github.com/CartoDB/cartodb/issues/4466

Remove private maps, private datasets and sync tables, since those things are inherited from the plan. I don't see why you shouldn't avoid people to have privacy or sync tables in a corporate environment. The simpler, the better.

**Comment by saleiva** [comment]
cc/ @andrewxhill let me know why you would like to add this. More features, more mainteinance and more things to teach / explain

**Comment by juanignaciosl** [comment]
Since we've not added anything yet, let's discuss what _should_ be added at #4466.

**Comment by andrewxhill** [comment]
nope, i agree here, good closed
