### ISSUE TITLE
Uninvited tick at wizard dropdown sliders.

### ISSUE THREAD

**Issue by fdansv** [CartoDB/cartodb#4747]
For some reason, the dropdown sliders that we use in the wizards have a static white tick on their top:

![screen shot 2015-07-28 at 17 32 09](https://cloud.githubusercontent.com/assets/3707222/8935800/e2638efc-354e-11e5-92ca-33b0c9dc9d72.png)

cc @javierarce

**Comment by javisantana** [comment]
this is only with the cartodb.js with updated plugins, right?

**Comment by fdansv** [comment]
No, it's happening in production. It's just that I found out about it while testing the plugins.

**Comment by javisantana** [comment]
Ok, could you describe what you changed? If someone reads this ticket is going to be hard they know how to reproduce

**Comment by fdansv** [comment]
Haven't changed anything, don't you get the same when editing something like the marker fill opacity? @javierarce has seconded this problem.

**Comment by xavijam** [comment]
I feel it was solved, but in any case those controls will change with the new editor. Closing! :)
