### ISSUE TITLE
First row top margin on the maps screen is wrong

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#4754]
![screen shot 2015-07-28 at 19 45 38](https://cloud.githubusercontent.com/assets/132149/8938842/47e3da54-3561-11e5-9986-b0fc48c66358.png)

Between the line and the cards.

**Comment by xavijam** [comment]
Datasets and maps lists have the same space at the top, 10px, but if you want maps list with a bit more no problem.

![screen shot 2015-08-03 at 12 32 57](https://cloud.githubusercontent.com/assets/132146/9035818/c88a3b0c-39db-11e5-9ff6-49a8f0b37e3d.png)

**Comment by saleiva** [comment]
Give it 20px on maps!
