### ISSUE TITLE
reduce fonts load at the dashboard?

### ISSUE THREAD

**Issue by Kartones** [CartoDB/cartodb#4755]
Loading the home performs 9 calls to retrieve woff2 fonts. While the cartoicon one I guess can't be, couldn't we at least combine the others? isn't a way to just ask for the whole family?

Is not in the screenshot but Chrome reports an average of 386ms waiting each woff2 request, so combining them we could probably squeeze something (as IIRC a browser can do a max of 6 concurrent requests to the same domain), plus the fewer requests the better.

![image](https://cloud.githubusercontent.com/assets/2085449/8951857/c16eaee2-35d1-11e5-875d-9e65315d8e80.png)

My two cents

**Comment by zenitraM** [comment]
A hacky workaround (as we do with tiles) could be fetching the fonts from a different domain
