### ISSUE TITLE
Duplicating annotations is not saving them

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#4763]
**Steps:**

* Create a new empty map
* Add an annotation
* Open the viz.json file, see it's there
* Come back to the Editor tab and duplicate the old annotation -- it appears in the Editor
* Move this new annotation a bit if you want (not required, it was to try to force it to be saved)
* Update the viz.json, the new annotation is not there
* Refresh the Editor tab: the new annotation disappears

**Comment by iriberri** [comment]
6102958

**Comment by javierarce** [comment]
It seems it's a problem with the overlays in general regarding this fix: https://github.com/CartoDB/cartodb/commit/be5a0ebd7469b96b52823b8f99beaf4bdb6734b1

**Comment by javierarce** [comment]
This should be fixed now.
