### ISSUE TITLE
Design email that arrives when a long geocoding finish

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/cartodb#4765]
I need the design for the geocoding email. (issue #4604)

<img width="496" alt="captura de pantalla 2015-07-29 12 30 34" src="https://cloud.githubusercontent.com/assets/741240/8955827/6b7b65c4-35f0-11e5-9177-ce829b413565.png">

<img width="499" alt="captura de pantalla 2015-07-29 12 30 59" src="https://cloud.githubusercontent.com/assets/741240/8955831/6f3010c0-35f0-11e5-8e35-e7a1ffe322f6.png">

**Comment by saleiva** [comment]
@josecruz talk to matallo if you have any doubts.

**Comment by josecruz** [comment]
What do you think @saleiva?

<img width="1379" alt="screen shot 2015-07-29 at 18 16 34" src="https://cloud.githubusercontent.com/assets/596509/8963013/19010c26-361e-11e5-8339-902a047341cc.png">

**Comment by saleiva** [comment]
In the yellow one, I'd put the first text withing the yellow area, and the
second one outside

**Comment by josecruz** [comment]
Yep, you're right!

<img width="1405" alt="screen shot 2015-07-29 at 18 42 46" src="https://cloud.githubusercontent.com/assets/596509/8963675/a666ddf4-3621-11e5-937e-1450f3bbb286.png">

Also, just an idea: We could show here the credits left/credits used or opperation cost

**Comment by saleiva** [comment]
Dude, but respect the order of the texts. IN that order they doesn't make any sense. First the yellow area with the text summarizing the results. After it, the other text (without the bullet point, please)

**Comment by josecruz** [comment]
Okay, you mean this right?
<img width="648" alt="screen shot 2015-07-29 at 19 02 53" src="https://cloud.githubusercontent.com/assets/596509/8964208/89e09870-3624-11e5-9892-e6c06e9791da.png">
Q: Why the border radius are not the same? Should I update that?

**Comment by saleiva** [comment]
ossom. Yep update those to the non rounded ones as @matallo prefered those

**Comment by matallo** [comment]
BOOM, I can have them very soon

**Comment by josecruz** [comment]
@ethervoid I'll share the sketch file via slack :+1:

**Comment by ethervoid** [comment]
Thank you @josecruz :)

**Comment by josecruz** [comment]
to you! :D

*Jose Cruz*
Junior Designer

*CartoDB—Map Your World's Data*
C/ Eloy Gonzalo, 27, 3, 28010, Madrid, Spain
W: www.cartodb.com
