### ISSUE TITLE
Fix local execution of test suite

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#4770]
After upgrading to Rails 3.2.20 some tests are broken for local execution. Just run `make check` and individual `make check-X`.

cc @CartoDB/backend @jesusvazquez

**Comment by jesusvazquez** [comment]
Hi,

**Comment by jesusvazquez** [comment]
Hi,

I ran all the tests and here is the report:

bundle exec make check-1 OK
bundle exec make check-2 OK
bundle exec make check-4 181 examples, 12 failures, 1 pending [Check4.log] (https://gist.github.com/jesusvazquez/4d1e130a433e9c8ab1e7#file-check4-log)
bundle exec make check-5 OK
bundle exec make check-7 OK
bundle exec make check-9 166 examples, 2 failures, 24 pending [Check9.log] (https://gist.github.com/jesusvazquez/4d1e130a433e9c8ab1e7#file-check-9)

Let me know if you know how to fix this.

**Comment by jesusvazquez** [comment]
Think tests are now running ok. Maybe @juanignaciosl wants to give it a try?
