### ISSUE TITLE
Allow for permanent dismissal of Pecan modal

### ISSUE THREAD

**Issue by chriswhong** [CartoDB/cartodb#4779]
The modal for Pecan appears each time the user enters map view, and I find myself wishing I could dismiss it permanently for a dataset or map.

![stormpath](https://cloud.githubusercontent.com/assets/1833820/8970423/a4d9115a-3617-11e5-8b59-511fd639434d.gif)

**Comment by jatorre** [comment]
Yes, a lot! Will not consider it an enhacement, it is more like a bug! Even if you dismiss it, it always come back. Even if you have selected the columns you want to use. Do a change on any column or move from table view to map view and you always get it there. So you end up having to close this continuosly.

**Comment by javierarce** [comment]
This should be fixed now. Sorry for the hassle!
