### ISSUE TITLE
Using the OneClick service, doesn't detect a logged in user

### ISSUE THREAD

**Issue by mejackreed** [CartoDB/cartodb#4780]
When using the OneClick (https://cartodb.com/open-in-cartodb/) service for an external dataset, OneClick does not detect an already authenticated CartoDB user. This forces the user to log in to CartoDB a second time.

Discussion here:
https://github.com/geoblacklight/geoblacklight/pull/341#issuecomment-126110096

**Comment by saleiva** [comment]
@Kartones @juanignaciosl  can you take a look at this? This might have something to do with warden

**Comment by juanignaciosl** [comment]
Ok, I've reproduced it importing [a data.gov dataset](http://catalog.data.gov/dataset/waofm-april-1-population-by-state-county-and-city-1990-to-present-22a1f): it works for organization users, but won't work for normal ones.

**Comment by Kartones** [comment]
I have no idea how OneClick works, nor how does it authenticate, I'd have to stop current tasks + assigned milestone stuff, so if you feel important @saleiva reassign to me, else I guess @juanignaciosl will have to take a look.

Warden stuff has initially nothing to do with external services, only affects login/logout/change password scenarios (and other internals like cookie expiration), but as I said I haven't coded nor read OneClick code :/

**Comment by saleiva** [comment]
Yeah, I think this is important… cc/ @javisantana

S.

-----
@saleiva

**Comment by juanignaciosl** [comment]
Ok. Problem is broader: https://cartodb.com/login won't remember normal (non-org) user sessions. https://username.cartodb.com/login do, but https://cartodb.com/login don't.

**Comment by saleiva** [comment]
For me this should be top priority

S.

-----
@saleiva

**Comment by juanignaciosl** [comment]
@mejackreed thank you for reporting, it's fixed now. You'll need to close your session first, but then, after your next login, it will work. Sorry for the inconvenience!

**Comment by mejackreed** [comment]
Thanks for the quick fix :+1:
