### ISSUE TITLE
Public map issues

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#4781]
- [x] Dropdown arrows are weird (Device: desktop).
![screen shot 2015-07-30 at 09 36 14](https://cloud.githubusercontent.com/assets/132146/8978027/b7490f70-369e-11e5-9de5-1c96859d022c.png)

---

- [x] Review user name arrow (too light?) and hover style (Device: desktop).

![screen shot 2015-07-30 at 09 51 52](https://cloud.githubusercontent.com/assets/132146/8978247/a0838a66-36a0-11e5-81ec-eeebb704ba23.png)

---

- [ ] Disqus doesn't take up all the available space (Device: desktop).
![screen shot 2015-07-30 at 09 39 54](https://cloud.githubusercontent.com/assets/132146/8978064/f3838f42-369e-11e5-816e-cf03ffb04360.png)

---

- [x] Some fonts in footer are not loaded (Device: desktop).
![screen shot 2015-07-30 at 09 34 53](https://cloud.githubusercontent.com/assets/132146/8978070/02cd8aa2-369f-11e5-841c-6956a3c2036d.png)

---

- [x] Social logos in footer location seems to not be correctly aligned (Device: desktop).
![screen shot 2015-07-30 at 09 36 03](https://cloud.githubusercontent.com/assets/132146/8978082/17367166-369f-11e5-90d5-7e40cf6768a4.png)

---

- [x] When user clicks over 'More info button', more info is showed (:+1:) but button still says "More info" (Device: mobile).
![screen shot 2015-07-30 at 09 47 06](https://cloud.githubusercontent.com/assets/132146/8978183/f7a73cf8-369f-11e5-884c-44818309bb56.png)

---

- [x] Share icons, below the map, appear with different margins (maybe we missed a vertical separator?).

![screen shot 2015-07-30 at 09 48 15](https://cloud.githubusercontent.com/assets/132146/8978218/47e0a808-36a0-11e5-8275-d2ab5832469a.png)

---

cc @matallo @saleiva

**Comment by matallo** [comment]
fixed these and https://github.com/CartoDB/cartodb/issues/4724 issues

- dropdowns, colors, disqus size are as in the mockup (already darkened arrow color, though), to be discussed with @CartoDB/design 

I wasn't aware of iphone issues as I was using device emulator in devtools :(

**Comment by saleiva** [comment]
ping!

**Comment by matallo** [comment]
duplicated, the only pending is the disqus width, which is covered in the other issue

closing, then
