### ISSUE TITLE
User groups feature scope and design

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#4785]
During [LDAP integration](https://github.com/CartoDB/cartodb-platform/wiki/SAML,-LDAP-and-related-integrations) and [5k organizations](https://github.com/CartoDB/cartodb-management/wiki/5k-user-organizations) analysis and development the need for user groups arised, we need the product design on this before beginning implementation.

This is the list of concerns to date that should be taken into account. They mostly come from both for requirement requests:
- Group CRUD: group management: creation, search, edition and deletion.
- Permission assignment: probably quite similar to organizations: R/W permission on groups.
- User visibility: users inside groups can only see users within the group?
- Group administrator role? Example: class teacher. What can he do?
- Group quotas: like organization quotas?
- Default user quotas inside groups?
- Group hierarchy? Can a group contain groups?
- LDAP mapping?

**Comment by javisantana** [comment]
- only model stuff, no focus on REST API changes (the groups api needs to be public probably)
- groups should be in the first iteration as simple as possible:
   - no groups inside groups
   - no group quotas, no default stuff for users
   - no ldap mapping
   - no adm role inside the group

*Focus on*:

- what API from extension the editor needs taking into account the permissions for a group are the same than for an user. So R/W for tables, R for visualizations.
- is the database layout compatible ?
- all the possible stuff that could happen having that, for example, if a group has R access for a visualization, could a single user within the group have no access at all?

**Comment by juanignaciosl** [comment]
Group features have already begun. Progress & additional info can be tracked at https://github.com/CartoDB/cartodb-management/wiki/Groups.
