### ISSUE TITLE
check-in countries table as part of source

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#4796]
thinking in on-premises here, we should have the countries dataset as part of the source code, so we can use it in data-library header https://github.com/CartoDB/cartodb/issues/4795

**Comment by ethervoid** [comment]
This should not be necessary because frontend is going to send the bbox of the country to filter

**Comment by matallo** [comment]
in any case I need the table for the header, don't I?

**Comment by ethervoid** [comment]
We should put that into a file with iso_code - bounding box. I could create that file and put where are going to need it to use it

**Comment by ethervoid** [comment]
Here are a CSV with the data https://data.hdx.rwlabs.org/dataset/bounding-boxes-for-countries

**Comment by ethervoid** [comment]
I get the data from this file [http://wiki.openstreetmap.org/wiki/User:Ewmjc/Country_bounds](http://wiki.openstreetmap.org/wiki/User:Ewmjc/Country_bounds) . We should add license attribution and share it with the same license. 

The last update is from 2009 but I think we could use it

I'm going to transform into a YAML file to be used by the frontend and add the license header.

// @rambo

**Comment by matallo** [comment]
self-reminder I'd probably to add it to the grunt:copy

**Comment by ethervoid** [comment]
I thought that we only need the bbox. This situation leads us to two options:

* Add the_geom to the file (I don't like this option)
* Create a migration and add country world borders table in the metadata DB. This way all the users, once the migration is applied, could use that table.

My suggestion is to let this file this way to be used to send the bbox of a country and add the migration option

// @rambo

**Comment by matallo** [comment]
as you prefer, I'd like to access the_geoms from the api-sql, so...

ps: let's comment on the PR (https://github.com/CartoDB/cartodb/pull/4881) or the issue, but jumping from one to the other gets me crazy, ha

**Comment by javisantana** [comment]
This is a frontend resource file, we will include world borders as topojson, nothing to do in backend here

**Comment by matallo** [comment]
finally the geometries in the header come from a query to common-data account, we can always check-in the file in the source code (tried to put in in /public, but is not that straight forward)

anyways, it won't make external calls https://github.com/CartoDB/cartodb/blob/4795-data_library_markup/lib/assets/javascripts/cartodb/data_library/header/view.js#L38-L40

if the solution doesn't fit the task feel free to comment
