### ISSUE TITLE
cover data-library backend api for frontend support

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#4797]
* [x] Filter datasets for `source` field
  * endpoint (api/v1/viz?params...&source=xxxx)
* [x] Filter datasets for `country` field
  * endpoint (api/v1/viz?params...&types=table&bbox=min_lon,min_lat,max_lon,max_lat)

**Comment by ethervoid** [comment]
Example for `country` endpoint call:

```http://user.localhost.lan:3000/api/v1/viz?types=table&bounding_box=-18.166667,27.633333,4.333333,43.916667&api_key=APIKEY```

Its important to filter by type `table` because only the canonical tables store the bounding box. Is that a problem?

// @javisantana

**Comment by javisantana** [comment]
the api key should not needed, it's a public thing.

in this case the type should be table but is up to the caller.

Please, use `bbox` as name for the parameter, it's shorter and more "standard"

**Comment by ethervoid** [comment]
Ok, but if the caller try to filter by bounding box in other visualization type than table is not going to work because we only store the bounding box for visualizations of type table

**Comment by javisantana** [comment]
so the backend should raise a 400, right?

**Comment by ethervoid** [comment]
Yes, this should be the expected behaviour for me. I'm going to sanitize the input too

**Comment by ethervoid** [comment]
What about the `source` endpoint? Are we going to do it? bbox filter is done and deployed

**Comment by javisantana** [comment]
@matallo is that source filter needed?

**Comment by matallo** [comment]
it is, as per design proposal, isn't it?

![screen shot 2015-09-07 at 16 16 36](https://cloud.githubusercontent.com/assets/36676/9718429/d975916c-557b-11e5-9eba-cecaa3455a28.png)

maybe we can iterate and add it afterwise

**Comment by ethervoid** [comment]
The main problem for this was that the source field is a text field that could have markdown. If we are going to use this, we have to create a full search text index for it but the last time we talk about this I thought that we are not going to use it

**Comment by matallo** [comment]
source search is working but the current design doesn't cover the source search, which is free text, not a closed set of options, so we would better need a search box here

/cc @xavijam @carlostallon
