### ISSUE TITLE
data-library detail page

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#4799]
will probably need some help understanding models for the split table/map view in the header, as well as the export with the bounding box

<img width="686" alt="screen shot 2015-07-30 at 12 41 51" src="https://cloud.githubusercontent.com/assets/36676/8981410/61e7d772-36b8-11e5-9166-6db51a58b510.png">

/cc @CartoDB/frontend

**Comment by viddo** [comment]
What feedback do you expect from _frontend_ here? I feel I lack context information to really comment anything else :)

**Comment by matallo** [comment]
sure, It was more how table and model works so we can do the bounding box filter

not arrived there, yet, so I'll ping you when needed
