### ISSUE TITLE
Create dataset from query shows duplication modal

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#4801]
When creating a dataset from query, the modal of dataset duplication appears:
![image](https://cloud.githubusercontent.com/assets/1730320/8981825/9cdb8d30-36bb-11e5-8328-9411bc8ec8d4.png)

I think that before we were using a more specific text in this case. Is this new behaviour expected?

@viddo @saleiva

**Comment by saleiva** [comment]
Good catch. It should be "Creating dataset from your query"
