### ISSUE TITLE
Can't edit dataset metadata when custom SQL query is applied

### ISSUE THREAD

**Issue by mnquintana** [CartoDB/cartodb#4810]
Steps to reproduce:

1. Open a dataset on which you have admin rights
1. Link under table name should read `Edit metadata`
1. Clicking `Edit metadata` should work as expected
1. Apply a custom SQL query / view
1. Link under table name should read `View metadata`
1. Clicking that link will open a modal with greyed out fields and a message that says `You can't edit the dataset attributes.`

**Comment by saleiva** [comment]
good catch! Thanks!

**Comment by xavijam** [comment]
Yes, this is done on purpose. We did in the past trying to avoid problems in the case of the user was querying against other tables and not the current one.

**Comment by xavijam** [comment]
About the text change, totally agree @mnquintana.

**Comment by alonsogarciapablo** [comment]
What @mnquintana is describing here is exactly the current behaviour:

![metadata](https://cloud.githubusercontent.com/assets/390398/9360726/3f6aa694-4698-11e5-9d97-a7e6593b2489.gif)

As @xavijam explained, this was implemented this way for some reason. I'm not sure why metadata shouldn't be editable when a custom query has been applied (which I'm assuming is what @mnquintana is asking for). @xavijam thoughts? do you think we can let users edit metadata even if a query has been applied?

**Comment by xavijam** [comment]
Some points:
- The button for opening metadata dialog should say: 'View metadata' (because you can't edit anything there).
- Source placeholder in this case should say: 'Empy source'.
- License placeholder in this case should say: 'Empty license'.

**Comment by alonsogarciapablo** [comment]
It does say "View metadata..."...

**Comment by mnquintana** [comment]
@alonsogarciapablo That's right, I was expecting metadata to still be editable even when a custom query is applied.

**Comment by xavijam** [comment]
@alonsogarciapablo, if it says "view metadata" === :dancer:.
