### ISSUE TITLE
Potential bug with refresh in IE 8/9 at zoom level 10 or higher 

### ISSUE THREAD

**Issue by Hayleyr** [CartoDB/cartodb#4812]
User has CartoDB.JS map with 4 SQL sublayers

He writes "when zoom level is higher than 10 the map does not refresh after I set the sql using thelayer.getSubLayer(0).setSQL method."

He is not experiencing these issues in any other browsers, only IE. 
He also has indicated that when he removes the 4th sublayer the map behaves perfectly. 

Let me know if having his code would help and I can send it. I haven't IE so I can't reproduce the issue, and a screenshot from the user wouldn't really illustrate anything except the map staying the same.

**Comment by iriberri** [comment]
It seems this is due to browsers like 8-10 blocking long get requests
