### ISSUE TITLE
when data_library feature flag show new datasets index

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#4816]
they'll just replace the old public `/datasets`, discuss if necessary

/cc @javisantana @saleiva

**Comment by javisantana** [comment]
@saleiva @carlostallon not sure about your opinion here, at the beginning this was a single page for the whole domain but finally we will be doing for everybody (only enabled for common data for the moment) so we need to discuss if this page replaces the /datasets endpoint

**Comment by saleiva** [comment]
Uhm... Don't think so...
Can we add one that says /data?

By that we will have optionality in the future

**Comment by javisantana** [comment]
technically is not a problem, but we will have /data and /datasets showing more or less the same
