### ISSUE TITLE
dropbox connector says you can connect GPX, it's not true

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#4818]
## str

1. go to new map > connectors
1. click on dropbox

<img width="971" alt="screen shot 2015-07-31 at 10 56 18" src="https://cloud.githubusercontent.com/assets/36676/9004046/2e92934c-3773-11e5-88c2-8c5e2c41b95b.png">

1. connect dropbox where there's a .gpx file

**expected behaviour:**

gpx file to appear in the list

**actual behaviour**

gpx file won't appear in the list

<img width="971" alt="screen shot 2015-07-31 at 10 57 54" src="https://cloud.githubusercontent.com/assets/36676/9004082/6afd9fd4-3773-11e5-8e09-43c8a56cfd01.png">

**Comment by ztephm** [comment]
Also not working for .geojson

Ref S/B 6176339

Replicated following same steps as above with a geojson that was exported from a dataset already in my team account & then uploaded to dropbox

When I export same dataset as CSV and upload to dropbox it appears in the CartoDB list.

**Comment by Kartones** [comment]
- Geojson doesn't appears in the list of Dropbox supported files
- Removing KML and GPX as they are not supported from dropbox, indeed
- We should probably change that text to not say "and many other formats" going to the full list, for something like "and some of this formats" in scenarios like Dropbox that limits the allowed extensions. But that's out of my scope... so I'll change what I can easily, feel free to create another ticket and assign to somebody from Frontend.
