### ISSUE TITLE
Show a better user import error for: ERROR Parseing kml Style: No id

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#4822]
It's being common these days the import error `ERROR Parseing kml Style: No id`. After taking a look at the KML Style specification (https://developers.google.com/kml/documentation/kmlreference?hl=en#style) it seems that style tags must have an ID, but we're receiving some files that haven't.

cc @ethervoid

**Comment by ethervoid** [comment]
I've put this copy for the error:

```
title: 'KML without style ID',
what_about: "The KML file you tried to import failed due some Style element don't have ID attribute. To fix this, open the file and add Id to all the Style tags.",
```

Good @saleiva ?

**Comment by iriberri** [comment]
Please, ask help for this to any native speaker. @agnesATcartoDB or @ericbean12 could help you in Madrid.

**Comment by ethervoid** [comment]
More than possible typos, is the copy of the exception to be more human and less developerish hehehe

**Comment by agnesATcartoDB** [comment]
"The KML file you tried to import failed because a style element doesn't have an ID attribution. To fix this error, please open the file and add an ID to all the style tags."

**Comment by ethervoid** [comment]
Thank you very much @agnesATcartoDB you rock :)

**Comment by agnesATcartoDB** [comment]
You're welcome!  Thanks for including me!
