### ISSUE TITLE
User groups backend analysis

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#4824]
From CartoDB/cartodb#4785:

- what API from extension the editor needs taking into account the permissions for a group are the same - than for an user. So R/W for tables, R for visualizations.
- is the database layout compatible ?
- all the possible stuff that could happen having that, for example, if a group has R access for a visualization, could a single user within the group have no access at all?

**Comment by juanignaciosl** [comment]
- Extension new API: mostly a duplication of [organizations API](https://github.com/CartoDB/cartodb-postgresql/blob/master/scripts-available/CDB_Organizations.sql).
  - `CDB_Group_Member_Group_Role_Member_Name(group_id)`. Returns a role member name for the group, namespaced under the org. Something like `CDB_Organization_Member_Group_Role_Member_Name() || group_id`
  - `CDB_Group_Create_Member(group_id text, role_name text)`
  - `CDB_Group_Add_Table_Read_Permission(group_id text, from_schema text, table_name text, to_role_name text)`
  - `CDB_Group_Add_Table_Group_Read_Permission(group_id text, from_schema text, table_name text)`
  - `CDB_Group_Add_Table_Read_Write_Permission(group_id text, from_schema text, table_name text, to_role_name text)`
  - `CDB_Group_Add_Table_Organization_Read_Write_Permission(group_id text, from_schema text, table_name text)`
  - `CDB_Group_Remove_Access_Permission(group_id text, from_schema text, table_name text, to_role_name text)`
  - `CDB_Organization_Remove_Organization_Access_Permission(group_id text, from_schema text, table_name text)`
- Current database layout (every user has its schema) is compatible:
  - Allows group-grained permissions through group roles.
  - Group has not schema, so no new namespace issues.
- PostgreSQL permission schema is grants a permission as soon as a role has it, so no, you can't grant a permission to a group of users and then revoke it to one of them.

When an (empty) group is created editor should invoke the extension, which should create group role.

When a user is assigned to a group extension should grant group role to user role.

Granting/revoking to users doesn't change.

Granting/revoking to organizations is done with previous methods.

cc @javisantana I think this is quite straightforward, do you think I'm missing anything?

**Comment by javisantana** [comment]
cc @rochoa @Kartones @rafatower

**Comment by Kartones** [comment]
I like it, and the limitation of not being to individually revoke an individual permission of the group has it is fine by me (not so common scenario, you can always decompose a group into smaller ones to fine-tune permissions if you want).

Also I like that we delegate on PG this, so ruby should mostly just wrap SQL calls. MU permissions stuff was done in a hurry and use both, so this is much cleaner.

**Comment by javisantana** [comment]
My questions:

- how do I create/drop a new group? 
- I don't understand what  ``CDB_Group_Add_Table_Organization_Read_Write_Permission`` exactly does. 

Could you write an example usage for that API with all the workflow?


Other things we need to think about (for the following months):

- How do we sync database created groups with rails app?
- How do we sync permissions with rails app?

**Comment by juanignaciosl** [comment]
- Group creation: organization creation is done when you request the name with `CDB_Organization_Member_Group_Role_Member_Name`, I followed the same schema. It's not a frequent operation, and name can be cached, so I'd keep the same convention.
- "CDB_Group_Add_Table_Organization_Read_Write_Permission": given a table, grants read and write permission to a group role, so every user at the group has those permissions as well (since they're granted that role).
- Sync database created groups: if that's something we're allowing we could trigger a sync looking for roles and grants when org owner enters org setting page, similar to ghost tables. Since we're prepending the group roles with the same prefix we can query PG catalog. Nevertheless, I'm not sure that's something that will be needed. I'd wait for users to ask for it. Massive groups are likely to be managed with LDAP or similar, not by scripting.
- Permissions: similarly, although I think people would use native PG granting functions instead of CDB's.

Example usage:
- An administrator creates a new group at org settings. It will trigger a `CDB_Group_Member_Group_Role_Member_Name(<group_id>)` to store the database role name at `groups` table. We can do it generating UUID at Ruby, requesting the role name and doing an insert.
- Adds users to the group, triggering `CDB_Group_Create_Member` with group id and user database username (which is calculated at `User#database_username`.
- A user opens permission dialog for a table and grants r/w for a group (listed from `groups` table). It triggers `CDB_Group_Add_Table_Group_Read_Write_Permission`.
- Any user of that org has r/w access, since they have that role.
- Owner user then revokes r/w permission, triggering `CDB_Group_Remove_Group_Access_Permission`.

**Comment by javisantana** [comment]
- what is the difference between CDB_Group_Add_Table_Organization_Read_Write_Permission and CDB_Group_Add_Table_Group_Read_Write_Permission ?


In my opinion we should revisit the extension API. We didn't publish it yet so it will be less painfull to change it now.

I'd prefer something like

```sql
select CDB_Group_Create('groupname'); -- creates a group, that's it, a role in the database 
select CDB_Group_AddMember('username') -- ideally the username is transformed to database user
select CDB_Group_GrantPermission('groupname', 'schema.table', 'r')
select CDB_Group_RevokePermission('groupname', 'schema.table', 'r')
select CDB_Group_Drop('groupname')
```

what do you think?

**Comment by juanignaciosl** [comment]
That function was wrong, I had already removed it from the listing but forgot to remove it from the the comment. That function (and others) came from organization api, which has some functions duplicated, some receiving organization explicit role and others that doesn't. I guess that's because organizations can be managed from a connection outside the org. Since groups are only managed by users inside the org that's not needed (at least not from the moment.

I prefer keeping two different methods for r/w rather than adding a parameter, but that's a matter of personal taste. My revisited proposal if we move away from org api:
- `CDB_Group_RoleName(group_id)`: returns a role member name for the group and creates it if it doesn't exist.
- `CDB_Group_Table_GrantRead(group_id text, from_schema text, table_name text)`.
- `CDB_Group_Table_GrantReadWrite(group_id text, from_schema text, table_name text)`.
- `CDB_Group_Table_RevokeAll(group_id text, from_schema text, table_name text)`.
- `CDB_Group_Drop(group_id text)`.

**Comment by javisantana** [comment]
Sounds good for me. I'd also try to:

- rename the methods for org (there will be a two phase deploy for this)
- use groups methods in org methods (makes sense to use groups to manage orgs, at the end they are a role, right?)

@rochoa I miss your opinion here

**Comment by rochoa** [comment]
Sorry this slipped through the cracks.

## About the organizations
I don't see any duplication. There are some methods to manage permissions at organization level and others to manage permissions at user level. That's why in some there is a role parameter and others don't have it. Probably the naming is not perfect, thus the confusion, sorry.

## About the new API
The latest methods proposed from @juanignaciosl look good to me. Things I'm not fully sure:
 - I would like to have CDB_Group_RoleName as an idempotent function. I would prefer to have another function to create groups.
 - What about having a `CDB_Group_Table_RevokeWrite(group_id text, from_schema text, table_name text)`?
 - What about having a `CDB_Group_Members(group_id text)`?
 - :+1: to `CDB_Group_AddMember` instead of `CDB_Group_Create_Member`.

I still prefer `CDB_Group_Table_GrantRead(group_id text, from_schema text, table_name text)` over `CDB_Group_GrantPermission('groupname', 'schema.table', 'r')`.

About naming: why `group_id`?

## About migrating organizations
And yes, thinking about this, and although it is gonna be a bit of a PITA, it totally make sense to manage organizations as groups so internally it should use these new groups permissions.

**Comment by juanignaciosl** [comment]
About *duplications*: oh, ok, I misread it. After reading more carefully ([example](https://github.com/CartoDB/cartodb-postgresql/blob/master/scripts-available/CDB_Organizations.sql#L33)) there's no organization-specific code inside functions receiving roles ("user level"), isn't it? Those functions doesn't need to have a "group replica".

About *api*:
- I don't have a strong opinion about the `CDB_Group_RoleName`. *Create if it doesn't exist* is something I only done on weird cases. Since it was done like that on organizations I guessed it was convenient (I have almost not worked with the extension yet). I'll split it then.
- Permission management is usually done by "wipe existing and set new on change", if I do more fine-grained methods they're not going to be used from the editor. If it's useful for other scenarios I can add it.
- If we do sync from database to editor we're needing `CDB_Group_Members`. Until then I think it's not needed.
- Added `AddMember`, but receiving `role_name` (pg role) instead of `username`, since [user <-> role_name is now at Ruby](https://github.com/CartoDB/cartodb/blob/master/app/models/user.rb#L569), depending on the environment.
- `group_id` refers to `groups.id` column. Organization names are unique, but groups are not (same name of a group in two different organitions, group hierarchy in the future...). I prefer ids, which are simple, rather than combinations with organization names or parent name hierarchy. Maybe roles can be created hierarchically (pseudo: `orgname_g_groupid` or similar) for the sake of clarity, but I think ids are better for the interface.

Updated proposal:
- **`CDB_Group_RoleName(group_id)`**
- **`CDB_Group_CreateGroup(group_id)`**
- `CDB_Group_AddMember(role_name)`
- `CDB_Group_Table_GrantRead(group_id text, from_schema text, table_name text)`
- `CDB_Group_Table_GrantReadWrite(group_id text, from_schema text, table_name text)`
- `CDB_Group_Table_RevokeAll(group_id text, from_schema text, table_name text)`
- `CDB_Group_Drop(group_id text)`

**Comment by javisantana** [comment]
A common complain from people using extension methods: having to pass the user role is a pain because there is not a easy way to get rolename from username.

It also exposes implementation details: I don't want to know if you are using a role and what is the role name, i just want to add permissions to an user in the organization

Using id's is simpler for you but is not useful for users

**Comment by rochoa** [comment]
_Create if it doesn't exist_ does not exist in Organizations. The organization user/role is created when the extension is installed https://github.com/CartoDB/cartodb-postgresql/blob/master/scripts-available/CDB_Organizations.sql#L7-L17 But the groups use case is different that's why I was proposing having two method to have a clear API.

I was proposing some of those methods because I think in terms of API without considering the editor it makes sense.

Actually I think this conversation should be happening in https://github.com/cartodb/cartodb-postgresql because we are talking about a new API in the extension, and yes, we have to have in mind the editor use case, anyway. To add more on this topic:

 - @javisantana making the extension knowing about editor usernames is a problem because it shouldn't know as @juanignaciosl said. We can workaround that by giving some context on extension installation so the extension can know what is the username format relative to the environment. So there is a function like `CDB_Role_Name(cartodb_username text)` that internally uses that context and is able to return the role name based on environment et al.

 - @juanignaciosl same applies to group_id, we are making the extension to know about editor features. When I think about the extension API I see a `group_name` and I don't care if the editor uses id or any other thing. The implementation should handle the internals to avoid problems with role names clashes.

None of those things are trivial, and I'm not even being coherent with myself about leaking implementation details in both directions. But, with table `rochoa.nurburgring_laps` and users `rochoa` and `delarosa` I would like to have an API like:

```
CDB_Group_CreateGroup('web_editors')
CDB_Group_AddMember('web_editors', 'delarosa')
CDB_Group_Table_GrantRead('web_editors', 'rochoa', 'nurburgring_laps')
CDB_Group_Table_GrantReadWrite('web_editors', 'rochoa', 'nurburgring_laps')
CDB_Group_RemoveMember('web_editors', 'delarosa')
```

**Comment by javisantana** [comment]
we can know the user from the rolename becase the username === schema name and the schema has an owner

```
select schema_owner from information_schema.schemata where schema_name = 'username';
```

Am i missing something?

**Comment by rochoa** [comment]
You are missing my stupidity.

**Comment by juanignaciosl** [comment]
- @javisantana: Passing ids vs. passing usernames: `select schema_owner from information_schema.schemata where schema_name = 'username';` is valid for org users, not for normal users, I guess it was done with role_names because it was straightforward using existing non-org users code. But we can't do the same with groups, since they have no schema. More on this later.
- @rochoa : those new functions make sense, but every time I work on advance I end up overengineering or doing code nobody actually needs :sweat_smile: . If you think they should be there from the very beginning I can add them, anyway.
- @rochoa I created this in this repo because it should cover more than the extension (although it's what needs more detail.

Conversation on api parameters is complex:

**Pros of using group ids and role names instead of group names and usernames**:
- Passing `group_id` is nice not because of the implementation detail of being an id in a table but because a client _identifier_, _unique_ and without encoding issues. I don't *feel* like we're leaking anything downstream.
- Sometimes we might need to go the other way around: if we want usernames instead of role names we need to know `schema_name` from a `username` (to grant a permission on a user table, for example), but you can't, since a role might be owner of several schemas, isn't it?
- It imposes group name unicity need.

**Cons of using group ids and role names instead of group names and usernames**:
- Not straightforward.

**Comment by javisantana** [comment]
if you call group roles like group names you don't need ids, it will just work

For me creating an API only editor can use is not useful, it should work using the api concepts (username in this case)

**Comment by rochoa** [comment]
> if you call group roles like group names you don't need ids, it will just work

Probably I'm missing something but:

```
$ psql
psql (9.3.5)
Type "help" for help.

postgres=# \c cartodb_dev_user_2d4cf4a0-8a5a-4ee5-a7fa-0c5da361d3b7_db
You are now connected to database "cartodb_dev_user_2d4cf4a0-8a5a-4ee5-a7fa-0c5da361d3b7_db" as user "postgres".
cartodb_dev_user_2d4cf4a0-8a5a-4ee5-a7fa-0c5da361d3b7_db=# create role web_editors;
CREATE ROLE
cartodb_dev_user_2d4cf4a0-8a5a-4ee5-a7fa-0c5da361d3b7_db=# \c cartodb_dev_user_359a4d9f-a063-4130-9674-799e90960886_db
You are now connected to database "cartodb_dev_user_359a4d9f-a063-4130-9674-799e90960886_db" as user "postgres".
cartodb_dev_user_359a4d9f-a063-4130-9674-799e90960886_db=# create role web_editors;
ERROR:  role "web_editors" already exists
```

**Comment by javisantana** [comment]
oh, wtf, I forgot the lovely fact that the users are shared :D 

ok, so db_name + group_name, easy to use with current_database() + group_name

**Comment by rochoa** [comment]
I'm not trying to impose / convince any of you about any of my ideas, I'm just trying to talk about the problems I see :smile:

About not implementing what's not needed right now: it depends if we see this as an API in the extension or an ad-hoc solution for the editor.

About the uniqueness of the group name I was to propose the same: "I think we could workaround it internally by prepending with the database name or something similar so group names (roles internally) within same server can be clash on external name representation but not internally."

**Comment by juanignaciosl** [comment]
That group role is valid as long as we keep group name uniqueness. I guess that's something we can enforce, and if anytime appears the need of same group name inside an org we can create a "display name" for the UI.

What about username vs user role? Am I missing something or can't we move away from role?

**Comment by javisantana** [comment]
> What about username vs user role? Am I missing something or can't we move away from role?

what do you mean?

**Comment by juanignaciosl** [comment]
You said:

> we can know the user from the rolename becase the username === schema name and the schema has an owner
> `select schema_owner from information_schema.schemata where schema_name = 'username';
Am i missing something?`

And I said:

> Sometimes we might need to go the other way around: if we want usernames instead of role names we need to know schema_name from a username (to grant a permission on a user table, for example), but you can't, since a role might be owner of several schemas, isn't it?

You proposed an api based on usernames instead of useroles and gave the sql as a bridge. I think it can't be done, but it can be because of my *stupidity* as well :)

**Comment by javisantana** [comment]
> since a role might be owner of several schemas, isn't it?

totally right, so we have 3 options:

- having an api is impossible to use but from the editor
- having a problem of collision if an user is owner of two schemas
- having a mapping in the extension

**Comment by juanignaciosl** [comment]
IMHO the right way is the last one: all database-coupled stuff (such as naming roles) should be in the extension. Existing code at Ruby side is determinstic: given a user id and an environment it will always return the same role name, maybe it should've always been in the extension, just like organization role is.

Shall I plan a transition to extension-backed while doing groups api?

**Comment by javisantana** [comment]
for me the last one is adding too much complexity, the price you need to pay is too high and there are other collision problems not solved. For example. what happens if you change the search_path to your user? everything will fail so that's a limitation. 

So my question, why don't add a limitation instead of complexity?

**Comment by juanignaciosl** [comment]
Your proposal is forcing users to be owners of two schemas?

**Comment by javisantana** [comment]
no no, I would just live with that problem and documenting it. In the extension there are some things you can't do, for example:

- changing the search path
- change permissions to the roles
- remove cdb_tablemedata 

So we'd add another one

- a user can be only owner of one schema

creating an schema with a cartodb user as a owner is not that common (and we can drop permissions anyways)

**Comment by juanignaciosl** [comment]
Oh, sorry, I just miswrote it, I meant "owners of only one schema", of course :-\ I was thinking on the problem and my brain short circuited.

If you think that restriction is ok we can have this api:

*CDB_Group_RoleName(group_id) is no longer needed*

```
CDB_Group_CreateGroup(group_name)
CDB_Group_AddMember(group_name, username)
CDB_Group_Table_GrantRead(group_name, username, table_name)
CDB_Group_Table_GrantReadWrite(group_name, username, table_name)
CDB_Group_Table_RevokeAll(group_name, username, table_name)
CDB_Group_RemoveMember(group_name, username)
CDB_Group_Drop(group_name)
```

**Comment by javisantana** [comment]
I think that constraint is a tradeoff we can take, what do you think @rochoa @Kartones @pramsey

**Comment by rochoa** [comment]
I'm OK with the suggested approach :+1:

**Comment by Kartones** [comment]
+10 Indeed that restriction is a small price and instead those methods look nice and are easier to use with names instead of ids so... great!

**Comment by javisantana** [comment]
I'm not so ok, thinking about the possible problems when renaming a group. We suffered this with table rename and sync with redis keys so imagine you have group rename and you have a race condition. You'd need looks and so on but with the uuid approach you are safe since the role names are immutable

**Comment by Kartones** [comment]
if the only problem is group renaming, easy solution: don't allow to rename groups :trollface: 
Force to create a new one, assign to same people, etc. and destroy the old -> no problem

**Comment by rochoa** [comment]
But the UUID can be a name for the group and the editor can manage a name as a property associated to the UUID so in the editor you can change the name and keep the UUID as the group role name.

**Comment by javisantana** [comment]
but how do you change the name with the sql api?

**Comment by Kartones** [comment]
@javisantana with a function to change names? (that internally recreates stuff)

**Comment by rochoa** [comment]
It happens the same with the named maps, the editor sets a name that has nothing to do with its name. That doesn't mean it's a good idea. But as an API user I don't want to use UUID for group names.

**Comment by juanignaciosl** [comment]
I wouldn't allow sql api to rename groups, and editor can duplicate and then remove the old one behind the curtain.

**Comment by rochoa** [comment]
But renaming with the remove+add approach means you have to take care of all granted permissions. You can rename with:

```sql
ALTER ROLE name RENAME TO new_name;
```

**Comment by juanignaciosl** [comment]
Ok, a new renaming method then?

**Comment by rochoa** [comment]
If the use case exists I would go with that approach.

**Comment by juanignaciosl** [comment]
```
CDB_Group_CreateGroup(group_name)
CDB_Group_RenameGroup(old_group_name, new_group_name)
CDB_Group_Drop(group_name)

CDB_Group_AddMember(group_name, username)
CDB_Group_RemoveMember(group_name, username)

CDB_Group_Table_GrantRead(group_name, username, table_name)
CDB_Group_Table_GrantReadWrite(group_name, username, table_name)
CDB_Group_Table_RevokeAll(group_name, username, table_name)
```

**Comment by rochoa** [comment]
`CDB_Group_Drop(group_name)` -> `CDB_Group_DropGroup(group_name)`? To be consistent with the rest of the naming?

**Comment by juanignaciosl** [comment]
Oh, sure, fixed.

Now I doubt about adding or not `Group` to the other functions: `CDB_Group_AddMember` or `CDB_Group_AddGroupMember`? `CDB_Group_Table_GrantRead` or `CDB_Group_Table_GrantGroupRead`?

**Comment by juanignaciosl** [comment]
I'll begin with latest keeping latest proposal. Additional note: editor will use extension functions to change groups; database will trigger an editor api endpoint request to sync metadata.
