### ISSUE TITLE
Add needed fields to `visualizations` such as attributions, license, etc

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/cartodb#4826]
For the new data-library feature we need to add more fields to improve the `Edit metadata` option in the dataset view.

* [X] Add new fields to the `visualizations` table:
    * License
    * Attributions
    * Source

**Comment by ethervoid** [comment]
We have to add all the licenses we want to show in the dropdown o autocomplete...

**Comment by saleiva** [comment]
Hey @javisantana you had a candidate list of licenses, right?
@ethervoid what about the UI part?

**Comment by javisantana** [comment]
no, @iriberri was going to send it.

The UI part ticket should be filed by @matallo

**Comment by ethervoid** [comment]
The UI part is in this issue #4803

**Comment by iriberri** [comment]
The licenses list task is here, FYI: https://github.com/CartoDB/cartodb-management/issues/4043
