### ISSUE TITLE
WMS endpoint fails to load when trying to import basemap

### ISSUE THREAD

**Issue by danicarrion** [CartoDB/cartodb#4829]
This is the URL: http://maps.six.nsw.gov.au/arcgis/services/public/NSW_Imagery/MapServer/WMSServer?request=GetCapabilities&service=WMS

The editor says: The URL is either invalid or contains unsupported projections

The request contains the following error too: not a valid capabilities document

I'm sorry my local installation of CartoDB is broken so I can't give you more details yet.

**Comment by jsanz** [comment]
This issue was added to another WMS ticket #4057 and @viddo added it to the backlog and next milestone
