### ISSUE TITLE
Public map page fixes

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#4833]
- [x] Use dropdown style in public pages like commercial 

<img width="276" alt="screen shot 2015-08-05 at 17 36 01" src="https://cloud.githubusercontent.com/assets/36676/9090035/804dea8c-3b98-11e5-9e94-3aca63dce909.png">
<img width="278" alt="screen shot 2015-08-05 at 17 36 08" src="https://cloud.githubusercontent.com/assets/36676/9090036/805030d0-3b98-11e5-9d40-c78183e9b9f0.png">

---

- [x] User thumbnail alignment

![screen shot 2015-08-03 at 10 31 41](https://cloud.githubusercontent.com/assets/132146/9033845/43bc7878-39cb-11e5-878b-8c63841361b0.png)

---

- [x] Edit in CartoDB button alignment

![screen shot 2015-08-03 at 10 33 14](https://cloud.githubusercontent.com/assets/132146/9033852/52211ff4-39cb-11e5-89c6-faa08e0a1363.png)

---

- [x] In my opinion breadcrumb separator is too light

![screen shot 2015-08-03 at 10 33 21](https://cloud.githubusercontent.com/assets/132146/9033860/65ab6656-39cb-11e5-9c28-d4c244c94bf3.png)

---
 
- [x] Fix Vertical align

![image](https://cloud.githubusercontent.com/assets/1214201/9039203/33c1d9ac-39fa-11e5-8324-b83dc0704d26.png)

---

- [x] Disqus block should take up all the available space (PLEASE) :)

---

- [x] Footer styles appear weird (device: mobile)

![screen shot 2015-08-05 at 10 23 57](https://cloud.githubusercontent.com/assets/132146/9081405/5c95837a-3b5c-11e5-93b9-5b3451cb2d9d.png)

---

- [x] Hide module when dataset not used in any map
![screen_shot_2015-08-17_at_19 43 32](https://cloud.githubusercontent.com/assets/1712650/9311723/79dd3494-4518-11e5-9cd0-c49ea3e55e10.png)

---

- [x] margins between heart "vertical line" and "api call" should be 28px, text should be semibold (400 in lato) -> Issue created #5072
![screen_shot_2015-08-17_at_19 39 49](https://cloud.githubusercontent.com/assets/1712650/9311785/f9392acc-4518-11e5-9e98-80275e7031f1.png)

---

- [x] Only 3 elements in "maps using this dataset"
![captura de pantalla 2015-08-17 19 53 30](https://cloud.githubusercontent.com/assets/1712650/9311895/ad9b3906-4519-11e5-9c39-d05f36a069c6.png)

---

- [x] ~~Login is pointing to this team url, should point to cartodb.com/login~~
_This is another issue_
---

- [x] margin of this elements on the map should be always 20px to the edge
![captura de pantalla 2015-08-17 20 01 48](https://cloud.githubusercontent.com/assets/1712650/9312087/d510beb0-451a-11e5-805d-520bb57dc8ae.png)

---

- [x] Color for CTA button and links should be: #3AA9E3
![screen_shot_2015-08-17_at_19 39 49](https://cloud.githubusercontent.com/assets/1712650/9312259/eb2426f0-451b-11e5-9546-ae9a33eec033.png)

**Comment by carlostallon** [comment]
- [ ] Hide module when dataset not used in any map
![screen_shot_2015-08-17_at_19 43 32](https://cloud.githubusercontent.com/assets/1712650/9311723/79dd3494-4518-11e5-9cd0-c49ea3e55e10.png)

- [ ] margins between heart "vertical line" and "api call" should be 28px
![screen_shot_2015-08-17_at_19 39 49](https://cloud.githubusercontent.com/assets/1712650/9311785/f9392acc-4518-11e5-9e98-80275e7031f1.png)

- [ ]

**Comment by xavijam** [comment]
@carlostallon, your enquiries moved to the description ;)

**Comment by xavijam** [comment]
And, about colors, @carlostallon, there is another ticket: https://github.com/CartoDB/cartodb/issues/5054, could we discuss there?

**Comment by carlostallon** [comment]
done! :)
