### ISSUE TITLE
JS error in new merge modal dialog 

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#4843]
this.model.selectedItemFor is not a function

https://my.trackjs.com/messages/filtered?message=this.model.selectedItemFor+is+not+a+function

**Comment by viddo** [comment]
I released a fix ~10 days ago, #4691, and looking in TrackJS the last message was from 8 days ago, which matches when this fix was deployed. So I close this one and keep an eye out if this is something new. Thanks for taking the time to open the issue though :)
