### ISSUE TITLE
be able to disable cartodb auth for an organization

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#4845]
Some organizations don't want to enable cartodb auth, just the google one. This makes sense when you want to have 2FA.

cc @saleiva @juanignaciosl

**Comment by juanignaciosl** [comment]
Assigned to saleiva before beginning coding since this involves product design ;-). This is part of what we spoke about authentication configuration indeed.

**Comment by saleiva** [comment]
It was already designed. Adding to the new design on the admin
