### ISSUE TITLE
Design invitation to org email

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#4852]

**Comment by saleiva** [comment]
![email](https://cloud.githubusercontent.com/assets/132149/9063875/06e467f8-3aca-11e5-82eb-acac874fbef1.png)

**Comment by saleiva** [comment]
Designed in emails-template-1.1.
Talk to @matallo if help needed with the layout.

**Comment by matallo** [comment]
@juanignaciosl just leave the template tags in the view and reassign it to me :)

**Comment by juanignaciosl** [comment]
Hi, @brittanymicek and @csobier, could any of you review the final text? The "I'd like to invite you..." sentence is the default value for the free text field at invitation creation (see #4882 "Welcome text" field).

![screen shot 2015-10-02 at 10 42 28](https://cloud.githubusercontent.com/assets/932968/10242609/5242f128-68f2-11e5-978d-59051cfece35.png)

Thanks!

**Comment by brittanymicek** [comment]
*You are invited to join the Central B organization at CartoDB*

Please join the Central B organization account at CartoDB:

Welcome to Central B! Please click on the button below to create your
account.

Happy data mapping!

On Fri, Oct 2, 2015 at 4:43 AM, Juan Ignacio Sánchez Lara <
notifications@github.com> wrote:

> Hi, @brittanymicek <https://github.com/brittanymicek> and @csobier
> <https://github.com/csobier>, could any of you review the final text? The
> "I'd like to invite you..." sentence is the default value for the free text
> field at invitation creation (see #4882
> <https://github.com/CartoDB/cartodb/issues/4882> "Welcome text" field).
>
> [image: screen shot 2015-10-02 at 10 42 28]
> <https://cloud.githubusercontent.com/assets/932968/10242609/5242f128-68f2-11e5-978d-59051cfece35.png>
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/4852#issuecomment-144961224>.
>



-- 
*Brittany Micek*
Content Writer

*CartoDB—Map Your World's Data*
143 Roebling St 2A, New York, 11211, USA
T: + <%2B34695497365>19174633232
W: www.cartodb.com

Live sessions to learn CartoDB <http://cartodb.com/webinars/>

**Comment by juanignaciosl** [comment]
Merged at CartoDB/cartodb#5852.
