### ISSUE TITLE
Allow admin to toggle of Signup form or Google Signin

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#4854]
I would propose a checkbox

=====

- [ ] Allow users to signup with their own username & email submission
- [ ] Allow users to signin with Google Apps administered email address (asterisk)

(asterisk) Many university email addresses use Google Apps, in these cases you can use only Google Apps signin.

=====

Then I would also include the ability to change the "Sign in with Google" button's text. 

New text: Sign in with ```enter text here```

And then let the user enter things like, "@nyu.edu" or things like that so it becomes more clear.

**Comment by saleiva** [comment]
Done in the new designs :)

**Comment by andrewxhill** [comment]
love yuou
