### ISSUE TITLE
when signin up with google and going to remove account, the user is asked about the password and he hasn't one yet

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#4856]
the delete account button works ok, though

<img width="967" alt="screen shot 2015-08-03 at 17 38 34" src="https://cloud.githubusercontent.com/assets/36676/9042132/00686400-3a0d-11e5-83dc-70cd0d338b21.png">

/cc @juanignaciosl @xavijam @viddo

**Comment by saleiva** [comment]
Good catch!

**Comment by juanignaciosl** [comment]
This has changed with the redesign. I think previously we forced user to disconnect from Google before deleting, isn't it? Or should we not ask for password?

**Comment by matallo** [comment]
yep, this is a regression from new_modals

**Comment by juanignaciosl** [comment]
Ok, won't ask for password then.
