### ISSUE TITLE
Design map liked email

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/cartodb#4859]
I've been extracting the map liked functionality and I need feedback or design for the email. I'm going to put here alternatives based on @matallo's layout:

<img width="508" alt="captura de pantalla 2015-08-03 18 25 47" src="https://cloud.githubusercontent.com/assets/741240/9046023/15075338-3a28-11e5-9977-eb5eebc9700e.png">
<img width="532" alt="captura de pantalla 2015-08-03 18 33 37" src="https://cloud.githubusercontent.com/assets/741240/9046024/15079122-3a28-11e5-8d4c-5f45f8782132.png">
<img width="513" alt="captura de pantalla 2015-08-03 18 39 19" src="https://cloud.githubusercontent.com/assets/741240/9046025/150bb8d8-3a28-11e5-97c6-8e429f9f35a4.png">

**Comment by matallo** [comment]
"your map has received a like" cheer up! maybe we can use some image, here? like the preview of the map and definitely the-one-giving-the-like should appear somewhere

**Comment by javierarce** [comment]
Also, the title and description are basically the same. I'd use a catchy phrase in the title like "Your map got some love!" or something similar.

**Comment by ethervoid** [comment]
In the first versions I put "Some has fall in love with your map" or "<user name> has fall in love with you map <map name>"

**Comment by javierarce** [comment]
And another suggestion. I'd randomise the "congratulations" at the end of the sentence and put it in the beginning. We could use:

* Congrats
* Congratulations
* Cool
* Awesome
* Hooray
* Nice
* Rad
* etc.

```[greeting], your [name of the map] has received a like from [username]!```

**Comment by javierarce** [comment]
@ethervoid: that's nice too, although maybe a bit long for my taste.

**Comment by saleiva** [comment]
Javier, come up with the text!

**Comment by javierarce** [comment]
*Title: `Your map got some love!`
*Text: `[greeting], your map [name of the map] was liked by [username]!`

`greetings`: congrats, congratulations, cool, awesome, hooray, nice, wow, rad, bravo, yay.

**Comment by javierarce** [comment]
From a conversation with @ethervoid in slack, we thought that title of the email could be: 

* `Your map [name of the map] got some love!``

This way we are consistent with the title inside of the email and the user can identify the map easily looking at the subjects.

**Comment by ethervoid** [comment]
The unsubscribe part is going to be added in the notifications management PR

**Comment by ethervoid** [comment]
Final version :)

![Uploading Captura de pantalla 2015-08-04 16.56.28.png…]()

**Comment by matallo** [comment]
tried with several basemaps, I'm keeping the same layout than public page

![artboard 1](https://cloud.githubusercontent.com/assets/36676/9065656/47886ed6-3ad3-11e5-8fbf-0842bca3fefc.png)
![artboard 2](https://cloud.githubusercontent.com/assets/36676/9065655/4786621c-3ad3-11e5-918a-30f5de696494.png)
![artboard 3](https://cloud.githubusercontent.com/assets/36676/9065657/478b8bac-3ad3-11e5-8a2e-c488331328bb.png)

**Comment by ethervoid** [comment]
Oh then that is the final version XD

**Comment by saleiva** [comment]
but remove the user name and the avatar since it's always the same! :)

**Comment by matallo** [comment]
ook
