### ISSUE TITLE
Rename "ASK FOR A DEMO" button when enabling Twitter

### ISSUE THREAD

**Issue by csobier** [CartoDB/cartodb#4868]
When selecting Twitter as the external dataset to connect to, the following dialog appears:
![image](https://cloud.githubusercontent.com/assets/13319925/9060739/99b4a7f0-3a84-11e5-9f7b-3d1fe2d8c158.png)

Selecting Twitter as your external service indicates that you must enable the Twitter Connector before connecting your dataset. This requires that you contact CartoDB for assistance, as only a sales representative can do this for you.  The ASK FOR A DEMO button only prompts you to send an email and does not indicate what the next steps are.  

The button "ASK FOR A DEMO" is not intuitive of the actual action and should be renamed.  I would suggest replacing it with *ENABLE TWITTER CONNECTOR* or something more reflective of the actual next step.  I am updating the Twitter procedure in the documentation with step-by-step details.

Please milestone for a future release and tag me when the UI changes so that I can recapture any related screenshots in sync with the release.  (This is also a good test of including documentation updates as part of the release cycle).

**Comment by javierarce** [comment]
I think "ask for a demo" is a good hint for the next step, which is filling the email that allows users to… ask for a demo :), but here's my proposal:

1. Keep the text as it is now
2. Prepopulate the email with a subject and a body:

* **Subject**: I'd like to test the Twitter connector
* **Body**: `I'm interested in testing the Twitter connector. Please, contact me to schedule a demo of this feature.`

**Comment by javierarce** [comment]
bump

**Comment by saleiva** [comment]
+1 @javierarce
