### ISSUE TITLE
PPA does not contain packages for Ubuntu 14.04 LTS Trusty Tahr

### ISSUE THREAD

**Issue by joetric** [CartoDB/cartodb#487]
This results in errors when running apt-get update, e.g.

W: Failed to fetch http://ppa.launchpad.net/cartodb/base/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/cartodb/base/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found

and so on.

**Comment by bpavie** [comment]
If you go to http://ppa.launchpad.net/cartodb/base/ubuntu/dists/ , you will see that the only distribution supported are Ubuntu LTS Precise (12.04) and Lucid (10.04) , so NOT Trusty (14.04)

**Comment by zenitraM** [comment]
We don't officially support anything other than Precise (12.04) yet. It might work if you change the config at /etc/apt/sources.list.d/... to point to "precise" instead of "trusty", it might work but we don't warantee it will (as we only test and run on Precise for now).
