### ISSUE TITLE
User account redesign

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#4878]
No new functionality, just a redesign ([source](https://projects.invisionapp.com/share/P43R5D79K#/screens/93103201)):

![screen shot 2015-08-05 at 11 13 49](https://cloud.githubusercontent.com/assets/932968/9082265/1fa5db2a-3b63-11e5-8a69-b26a8f8c6b7b.png)

![screen shot 2015-08-05 at 11 19 29](https://cloud.githubusercontent.com/assets/932968/9082376/e2f2b31e-3b63-11e5-8d47-e052a5af70b1.png)

![screen shot 2015-08-05 at 11 20 09](https://cloud.githubusercontent.com/assets/932968/9082389/f68b901c-3b63-11e5-97e4-c6382af9a2b1.png)

![screen shot 2015-08-05 at 11 20 30](https://cloud.githubusercontent.com/assets/932968/9082395/02cfab10-3b64-11e5-9d38-0af6ef819ac4.png)

![screen shot 2015-08-05 at 11 20 58](https://cloud.githubusercontent.com/assets/932968/9082408/14ec1f0e-3b64-11e5-874a-39e50d3435b7.png)

Notifications: CartoDB/cartodb#4592

Groups: CartoDB/cartodb#4883

*Differences between single user and [org owner user](https://projects.invisionapp.com/share/P43R5D79K#/screens/93103201)*: none.

*Differences between single user and [non-owner, org user](https://projects.invisionapp.com/share/P43R5D79K#/screens/93104547)*:
- Profile:
  - No Disqus shortname.
- Account:
  - No billing plan.
  - Can't delete the account.
- No Billing.
- When a contact email is displayed, it should display `admin_email ` (see CartoDB/cartodb#4403).

------------------------------------------

Redesign parts waiting for backend features to be fully implemented:
- **Single user**:
  - [ ] Notifications view
  - [ ] Monthly newsletter (notifications view section)

- **Organization owner**
  - [ ] Notifications view
  - [ ] Monthly newsletter (notifications view section)
  - [ ] New org user defaults and quotas (pending from #4466)
  - [ ] Groups

cc @saleiva

**Comment by MariaCheca** [comment]
Question here: should I change current texts for the ones in the redesign?
For example, in `/profile` "Edit your profile settings" -> "Your profile information"

cc/ @brittanymicek @csobier

**Comment by juanignaciosl** [comment]
Texts at the design seem fine, use design ones. @brittanymicek @csobier will suggest any change to them if there's something wrong.

**Comment by MariaCheca** [comment]
Copy that :+1:

**Comment by brittanymicek** [comment]
Notes on text:

_For **profile** tab:_

Under Choose Image
Recommended images should be 128x128 of size **change to “128x128 pixels”***

Other users can search and contact you by your public name

_For **account** tab:_

Why is there copy “Delete your account”? Is that supposed to be a button or a hyperlink?
underneath it says: “You sure? Delete my account and all my data”

**Suggestion:**
make “Delete your account” a button or hyperlink
and have “You sure? Yes, delete my account and all my data.” as a pop-up window when they click “Delete your account”

**Comment by juanignaciosl** [comment]
@saleiva that design has a problem that went unnoticed to me the account type section:

![screen shot 2015-08-14 at 16 49 02](https://cloud.githubusercontent.com/assets/932968/9276784/49c4d448-42a6-11e5-8ab6-530afe024fef.png)

Box doesn't know about _plans_ or prices. So we're doing an small modification:
1.- Don't display the price.
2.- The text of the button comes out from the `account_type` column at `users`.
3.- It links Central.

Please also note that should be only displayed at SaaS, not open source or onpremise.

cc @MariaCheca , this should clear all doubts, isn't it?

**Comment by saleiva** [comment]
Ok, so the only thing that we will miss is the price?

**Comment by juanignaciosl** [comment]
Yep, and account type is not exactly the same than price plan name, although I can't find a case where there's a mismatch on that right now. Not a big deal, but I wanted you to know.

**Comment by saleiva** [comment]
Ok

**Comment by MariaCheca** [comment]
Currently there's no reference in the redesign mockups for the organization users API keys. If it's ok I'll preserve these parts as they are in the current design, waiting for an update:

* At org owner panel:
![screen shot 2015-08-17 at 3 02 24 pm](https://cloud.githubusercontent.com/assets/2141690/9305365/26b076cc-44f1-11e5-88f1-fe02573668d5.png)

* At organization user details (owner view):
![screen shot 2015-08-17 at 3 02 10 pm](https://cloud.githubusercontent.com/assets/2141690/9305366/2a187ff8-44f1-11e5-879c-dae285848cf6.png)

cc/ @saleiva

**Comment by saleiva** [comment]
cc'ing @josecruz so he is aware.

**Comment by xavijam** [comment]
Closing since it is done, for pending behaviour or functionality, new tickets please.
