### ISSUE TITLE
Invite users to your organization

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#4882]
This invitation mechanism is the main way ldap-powered organizations (although it could be used from other organizations as well) ([source](https://projects.invisionapp.com/share/P43R5D79K#/screens/93103186)):

![screen shot 2015-08-05 at 12 43 19](https://cloud.githubusercontent.com/assets/932968/9084020/938e1a78-3b6f-11e5-9e79-e32c5de440b9.png)

When you create an invitation, CartoDB user is created inactive until user accepts invitation with the invitation email.

Group support is extracted to #5504

- [X] Invitation creation.
- [X] Invitation sending.
- [X] Signup invitation support (a user with invitation can always sign up with the token he receives at the email, even if email is not in the whitelisted domain).
- [X] Error on invitation creation if user already exists. UI: #5821
- [X] "Spend" the invitation after its use.
- [X] Edit existing invitation email, some texts about password are no longer valid.
- [X] Prefill email

cc @saleiva @javisantana

**Comment by juanignaciosl** [comment]
cc @MariaCheca don't do anything related to invitations as part of redesign (#4884).

**Comment by juanignaciosl** [comment]
Are we allowing this for non-ldap organizations, @saleiva ?

cc @Kartones

**Comment by juanignaciosl** [comment]
@saleiva for non-ldap users I miss username and password information. We could fix this by linking organization signup page in the invitation email, what do you think? User won't be actually created until signup is done.

**Comment by saleiva** [comment]
exactly, that was the idea. We link the signup prefilled with the email (if possible)

**Comment by juanignaciosl** [comment]
:sparkles: , thanks
