### ISSUE TITLE
Organization settings redesign

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#4884]
[Source](https://projects.invisionapp.com/share/P43R5D79K#/screens/93103187):

![screen shot 2015-08-05 at 12 24 54](https://cloud.githubusercontent.com/assets/932968/9083726/03b70a2e-3b6d-11e5-9f23-23b4d473fa6d.png)

![screen shot 2015-08-05 at 12 40 24](https://cloud.githubusercontent.com/assets/932968/9083987/2bc137d6-3b6f-11e5-833c-56f44d141d3d.png)

![screen shot 2015-08-05 at 12 41 02](https://cloud.githubusercontent.com/assets/932968/9083995/47106854-3b6f-11e5-8d00-7b48dc6f1342.png)

![screen shot 2015-08-05 at 12 33 52](https://cloud.githubusercontent.com/assets/932968/9083889/42ae6690-3b6e-11e5-89ca-87b885afe59d.png)

![screen shot 2015-08-05 at 12 39 19](https://cloud.githubusercontent.com/assets/932968/9083976/06d33ba4-3b6f-11e5-995f-9256b6ca6ea6.png)

Non-cosmetic changes:
- Organization profile:
  - Geocoding and Twitter credits and soft limits. Related to CartoDB/cartodb#3901. Talk to @juanignaciosl when needed.
- Auth settings. See CartoDB/cartodb#4880.
- Invitation mechanism. See CartoDB/cartodb#4882 
- User edition:
  - Geocoding and Twitter credits at user edition.
- Groups: CartoDB/cartodb#4883

cc @saleiva

**Comment by xavijam** [comment]
Let's review with small ticket what is pending.
