### ISSUE TITLE
Budge Pecan window to reveal Basemaps

### ISSUE THREAD

**Issue by auremoser** [CartoDB/cartodb#4894]
## Related Issues
When  #4305 is fixed, this probably won't be an issue

## Context
Pecan finds many maps, I like the suggestions, I don't want to close the window just to keep the suggestions open as a viewing option, but there is no way to collapse them so I can change my basemap.

## Process

1. (in my case) Import Twitter data with 2 hashtags
2. Pecan finds 17 maps! <- great
3. I test one of the suggested maps ( torque)
4. I can't change my basemap :(

## Expected result

I would like a way to re-trigger the pecan suggestions, so that I can collapse the "17 maps found!" modal and change my (now obscured) basemap picker tool without losing those suggestions.

## Current result

I have to forfeit basemap experiments until I'm willing to close Pecan Cookies.

## Possible Fix

* have a 'minimize pecan' modal option (next to the "X" to close)
* move pecan modal window slightly above the basemap picker, so both are accessible at the same time
* fix the related issue listed below to allow for re-triggering pecan

## `budge-pecan` screenshot

![budge-pecan](https://cloud.githubusercontent.com/assets/1559703/9095014/0f96f032-3b83-11e5-80ed-70969d961571.jpg)

**Comment by saleiva** [comment]
Thanks @auremoser. This will be fixed in the new editor layout. :)
