### ISSUE TITLE
Allow to edit the dimensions of the selected area in the export image dialog

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#4898]
Original ticket: https://github.com/CartoDB/cartodb/issues/4685

**Comment by saleiva** [comment]
There has been an user asking for this on supportbee to let him export bigger images that the area he can see.

**Comment by javierarce** [comment]
I don't think that we can do that and maintain the canvas export we are using to flatten the overlays :/

**Comment by saleiva** [comment]
what?

**Comment by javierarce** [comment]
In order to add the overlays in the exported image, we generate an image (using a third party plugin,  html2canvas) from the visible view. To my knowledge we can't export images bigger than the viewport. @javisantana you know more about this… am I wrong?

**Comment by javisantana** [comment]
I think it could be possible but not sure how hard it will be. We are also not ready to scale sizes so I'd say no unless we remove the overlays

**Comment by javierarce** [comment]
Ok. @chriswhong you were going to create an issue to have an export option without the overlays, right? Could you point the issue to this one, please?

**Comment by chriswhong** [comment]
My issue was not with overlays, it was with exporting an area larger than the current viewport AND including the basemap.  (I showed a customer how to use the static maps API using the layergroupid currently in use in the UI, but it only gets them their data layers with no basemaps)
