### ISSUE TITLE
Attach the floating elements of the export image dialog to the selected area

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#4899]
Original ticket: https://github.com/CartoDB/cartodb/issues/4685

**Comment by javierarce** [comment]
When the export window is very small, I've decided to move the close button to one side instead of keeping it in the same line. Not sure if it's the right solution. What do you think, @saleiva?

![anim2](https://cloud.githubusercontent.com/assets/4933/9383411/2701c720-4749-11e5-838d-1cb3f87680f9.gif)

**Comment by saleiva** [comment]
Loooove, looooooove, loooove
