### ISSUE TITLE
staging public pages are being indexed

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#4906]
https://www.google.es/search?q=cartodb-staging.com&oq=cartodb-staging.com&aqs=chrome..69i58j69i60l3j69i57.2974j0j4&sourceid=chrome&es_sm=91&ie=UTF-8

**Comment by xavijam** [comment]
![screen shot 2015-08-06 at 12 45 08](https://cloud.githubusercontent.com/assets/132146/9109827/04af5e8c-3c39-11e5-8c23-0824c3b5ca53.png)

**Comment by matallo** [comment]
bump!

**Comment by matallo** [comment]
@CartoDB/systems is working on this, removed milestone and left open for tracking

**Comment by xavijam** [comment]
What about this guys?

**Comment by matallo** [comment]
left it on @CartoDB/systems side and forgot about it :(

**Comment by matallo** [comment]
reassigning to @beloneys

**Comment by beloneys** [comment]
Hi,

I'm seeing that now. Regarding this issue you need to include a no follow tag please.
Could you please add it?

https://support.google.com/webmasters/answer/96569?hl=en

Who should be the owner for this @xavijam please? Maybe María?

Thx

**Comment by javitonino** [comment]
What if we just create a robots.txt disallowing indexing for everything under "*.carto-staging.com"? I think it's easier to implement and we do not have to touch the application.

Is this doable? @CartoDB/systems

**Comment by xavijam** [comment]
For me it is a very good solution so...

**Comment by beloneys** [comment]
Yes it is, thanks!

**Comment by luisbosque** [comment]
I will probably just set user/pass

**Comment by luisbosque** [comment]
Done, I've enabled authentication in staging
