### ISSUE TITLE
'new_modals' not warning user when out of geocoding credits

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#4908]
When a user runs out of geocoding credits, 'Street Addresses' geocoding is still available and fails with a generic error.

To reproduce this problem:
1. Create user
2. Consume al geocoding credits (or create user with none)
3. Georeference by "Street Addresses"
4. Geocoder fails with generic error

It would be nice we could:

+ Show the user a warning or upgrade link when geocoding credits run out
+ Disable 'Street Addresses' tab
+ If somehow the users is able to request georefencing without credits, the error is descriptive of the situation 

cc @viddo @juanignaciosl

**Comment by viddo** [comment]
> Disable 'Street Addresses' tab

It was decided not to in the [last feature change](https://github.com/CartoDB/cartodb/pull/4600) to not disable the tab and instead display a CTA to upgrade account. However, there is a bug that the footer is not displayed if the user has no quota set - @saleiva I suppose we should display the footer w/ the upgrade link in this case? But we probably need to change the wording, e.g. _You need to upgrade to get geocoding credits_ or something on those lines (cc @csobier @brittanymicek )

Also, there's that notion of "soft" vs "hard" limit, where soft limit allows the user to georeference data even if the current quota is depleted (with the side-effect that the user is billed according to the estimated price), ATM we only show the CTA if the user has run out of quota and have hard limit set, so even if the user goes ahead and try to georeference something can still fail, but the error message is derived from the returned error details, so then the backend need to provide more info regarding what went wrong.

**Comment by saleiva** [comment]
Yep!

**Comment by csobier** [comment]
Original footer: 
"Sorry you've reached your maximum geocode operations for this month. Upgrade your account to get more geocoding credits. **16 days left until your billing cycle is renewed.**"

Suggested UI text for footer:
"You have reached the maximum number of geocode operations allotted for this month. Contact [Sales](mailto:sales@cartodb.com) if you need to increase the number of your geocoding credits before your next billing cycle starts, **in 16 days.**"

**Comment by saleiva** [comment]
Hi csobier, is there anyway we can keep this as short as it was? (Aprox?)

**Comment by viddo** [comment]
@saleiva re: the length of the text I guess you want it to fit the space in the footer? I think the text is fine, but we would have to give the container some more space to fit nicely on two lines e.g.:
![screen shot 2015-08-07 at 10 50 11](https://cloud.githubusercontent.com/assets/978461/9132212/1b232856-3cf2-11e5-9b5c-1020989d9779.png)

**Comment by viddo** [comment]
Deployed on ded03 for testing 
@gfiorav the [msg above](https://cloud.githubusercontent.com/assets/978461/9132212/1b232856-3cf2-11e5-9b5c-1020989d9779.png) should be displayed now, but if your user has soft limit set (`table.user.get('geocoding').hard_limit` is false) then you can still geocode and something might still fail (because of some other err). I have not been able to reproduce this "generic error" you mentioned, can you try again, and this time check what details are returned from the actual requests (in the network tab in the dev tools)?

**Comment by brittanymicek** [comment]
Original footer:
"Sorry you've reached your maximum geocode operations for this month.
Upgrade your account to get more geocoding credits. *16 days left until
your billing cycle is renewed.*"

Suggested UI text for footer:
"You have reached the maximum number of geocode operations allotted for
this month. Contact Sales <sales@cartodb.com> if you need to increase the
number of your geocoding credits before your next billing cycle starts, *in
16 days.*"


*Brit's suggestion*

"Oh no! You have reached the maximum geocode operations for this month.
Please contact Sales for more geocoding credits, before your next billing
cycle in *16 days*."

*You can take out "Oh no!" if you think it is too dramatic. I kind of like
it.*

On Fri, Aug 7, 2015 at 5:21 AM, Nicklas Gummesson <notifications@github.com>
wrote:

> Deployed on ded03 for testing
> @gfiorav <https://github.com/gfiorav> the msg above
> <https://cloud.githubusercontent.com/assets/978461/9132212/1b232856-3cf2-11e5-9b5c-1020989d9779.png>
> should be displayed now, but if your user has soft limit set (
> table.user.get('geocoding').hard_limit is false) then you can still
> geocode and something might still fail (because of some other err). I have
> not been able to reproduce this "generic error" you mentioned, can you try
> again, and this time check what details are returned from the actual
> requests (in the network tab in the dev tools)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/4908#issuecomment-128650758>.
>



-- 
*Brittany Micek*
Content Writer

*CartoDB—Map Your World's Data*
143 Roebling St 2A, New York, 11211, USA
T: + <%2B34695497365>19174633232
W: www.cartodb.com

Live sessions to learn CartoDB <http://cartodb.com/webinars/>

**Comment by viddo** [comment]
bump @gfiorav

**Comment by gfiorav** [comment]
Sorry for the delayed reply, @viddo!

The user was created in a local environment with soft limit disabled, no extra geocodings and 0 geocoding quota.

If you have this fix deployed in staging I can test it out again if you like

**Comment by viddo** [comment]
> The user was created in a local environment with soft limit disabled, no extra geocodings and 0 geocoding quota.

Yeah, under those circumstances it shows the CTA correctly now, with the new copy.

**Comment by viddo** [comment]
…(verified locally), so no need to test on staging I think.

**Comment by gfiorav** [comment]
Nice! Like discussed: I'll test soft-limit situations and try to find errors. If I find any I'll open new issues.

Thanks!

**Comment by viddo** [comment]
<3
