### ISSUE TITLE
Add "resend verification email" button to the "You must validate your email account" screen

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#4910]
It would be nice to have a "resend verification email" when this screen shows up!

<img width="674" alt="screen shot 2015-08-06 at 13 13 13" src="https://cloud.githubusercontent.com/assets/4222826/9110354/4d7409f2-3c3d-11e5-9b2a-fdbbc2aa8017.png">

cc @josecruz

**Comment by juanignaciosl** [comment]
We already have this. When you try to login before validating your email you're displayed this:

![screen shot 2015-08-07 at 10 25 28](https://cloud.githubusercontent.com/assets/932968/9131758/c1312418-3cee-11e5-88b1-012aa5883b39.png)

And clicking `here` triggers the new email and sends you here:

![screen shot 2015-08-07 at 10 25 57](https://cloud.githubusercontent.com/assets/932968/9131770/d00a2340-3cee-11e5-80c0-d4f9f965a9be.png)

I'm not closing this just in case you want to do something fancier ;-)

**Comment by gfiorav** [comment]
After a short chat with @juanignaciosl I'm deploying master to a staging server and retesting this thoroughly.

The reason I never saw the resend link could be a bug, so I'll track it down to be sure.

**Comment by saleiva** [comment]
Can we also avoid orphans?

**Comment by juanignaciosl** [comment]
Since that text has not dynamic parts I can change it.
