### ISSUE TITLE
Release templated workflows in a test account

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#4911]
(EDITED by @alonsogarciapablo)

For this milestone, the goal is to release the WIP on templated workflows and upload the existing test template to a test account ~~under the CartoDB organization~~ on staging so that anyone within the company can check it out and demo it.

~~After having available 'template' endpoint (thanks to @kartones), we need some things:~~

~~- Create a script/whatever to generate new templates.~~
~~- Warn the user when a dataset deletion affects a template (backend done).~~
~~- Check how to warn the user when a map deletion affects a template (backend done).~~

cc @javisantana @Kartones

**Comment by alonsogarciapablo** [comment]
I've renamed and updated the description of this issue after a conversation with @javisantana. Basically, the goal for this milestone is to release the WIP and upload the templated workflow we have to a test account.
