### ISSUE TITLE
Enable cumulative option in torque cat wizard

### ISSUE THREAD

**Issue by stuartlynn** [CartoDB/cartodb#4922]
In the regular Torque wizard there is checkbox for cumulative markers:

<img width="391" alt="screen shot 2015-08-06 at 9 43 21 am" src="https://cloud.githubusercontent.com/assets/209838/9114505/e0386f94-3c1f-11e5-9ebe-9f932612867f.png">

but there is no such slider in Torque Cat:

<img width="389" alt="screen shot 2015-08-06 at 9 43 31 am" src="https://cloud.githubusercontent.com/assets/209838/9114510/eb02e012-3c1f-11e5-98ff-7406cd946e3e.png">

You can enable it by altering the cartocss: 
    -torque-data-aggregation:cumulative; 

but it would be good to have the option in the UI.

**Comment by javisantana** [comment]
this is not possible in the way torque category works, it will be possible when we have multi-channel torque.

Right now it works with the mode and if we accumulate the mode just does not work.

**Comment by davidpiles** [comment]
mmm... I was trying the same
