### ISSUE TITLE
Google deprecation dialog is not working

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#4926]
Seems like it appears but the the "ok, proceed" button is not working and the dialog doesn't disappear.

![image001-1 jpg 01d0d069 d3334340](https://cloud.githubusercontent.com/assets/132146/9117424/595f91c8-3c6a-11e5-8a06-9df9ad343d13.jpeg)

**Comment by viddo** [comment]
any error in the dev console?

**Comment by xavijam** [comment]
Ticket in support bee, it seems to be important, let me link it.
