### ISSUE TITLE
Public profile page index should have the logo box white instead of transparent

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#4929]
<img width="171" alt="screen shot 2015-08-06 at 19 47 43" src="https://cloud.githubusercontent.com/assets/132149/9118934/134c2430-3c74-11e5-9f86-e918d58d6de6.png">

**Comment by xavijam** [comment]
It will be fixed with https://github.com/CartoDB/cartodb/issues/5500#event-408800436.
