### ISSUE TITLE
Incorrect link on the like button on this page

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#4930]
https://googledataorg.cartodb.com/u/googledata/viz/8c3f94c0-3a22-11e5-b525-42010a14cb63/public_map?zoom=4&center_lat=38.7572747&center_lon=-94.1797144

If you try to like it, it takes you to the login :/

**Comment by matallo** [comment]
actually, it doesn't even authenticate me (same random authentication errors reported earlier)

steps to reproduce:
- brand new incognito window, login at http://cartodb.com/login (user: jacathon-huracan)

authenticated in jacathon-huracan public page
<img width="1264" alt="screen shot 2015-08-06 at 20 18 30" src="https://cloud.githubusercontent.com/assets/36676/9119755/baf8e87c-3c78-11e5-87ed-abbdb76f1b76.png">

not authenticated in this url
<img width="1214" alt="screen shot 2015-08-06 at 20 18 21" src="https://cloud.githubusercontent.com/assets/36676/9119759/be7b0f70-3c78-11e5-8eec-bf47a5d8fc50.png">

it should replace the link with the good one
https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/common/views/likes/view.js#L18-L41

but the returned `authenticatedUser` is empty
https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/public_map/entry.js#L62

<img width="713" alt="screen shot 2015-08-06 at 20 26 33" src="https://cloud.githubusercontent.com/assets/36676/9119897/7deadbd8-3c79-11e5-92ea-2343cd4e095a.png">

/cc @juanignaciosl @Kartones

**Comment by Kartones** [comment]
uhmmm that's a good one, because other orgs work nicely, example:
https://team.cartodb.com/u/saleiva/viz/58926788-2bdb-11e5-bd1e-0e0c41326911/public_map?zoom=4&center_lat=38.7572747&center_lon=-94.1797144

Checking other orgs

**Comment by Kartones** [comment]
that account has something wrong, static map preview is broken: https://googledataorg.cartodb.com/u/googledata

**Comment by Kartones** [comment]
Moved to https://github.com/CartoDB/cartodb-management/issues/4102
