### ISSUE TITLE
Remove "many more formats" text/link from DropBox connector

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#4931]
@csobier 
cc: @Kartones 

ref https://github.com/CartoDB/cartodb/issues/4818

Please remove "and many more formats" text and link from Connect dataset/DropBox page,
because DropBox connector doesn't support the formats that links to.

**Comment by Kartones** [comment]
cc @CartoDB/frontend

**Comment by xavijam** [comment]
Doing it in create-view-fixes branch.
