### ISSUE TITLE
Remove synchronizations v1_1 endpoint

### ISSUE THREAD

**Issue by Kartones** [CartoDB/cartodb#4935]
Feature flag is `active_record_synchronization_endpoint`

Must be done in two steps for having no downtime:

### Step 1

- [x] Reroute v1 calls to new controller (but leave v1_1 calls too!)
- [x]  Remove JS url patching, so it reroutes again to v1
-  Branch: `4805-remove_synchronizations_v1_1_endpoint`

### Step 2

- [x] Move tests to new controller suite
- [x] Delete old controller no longer used methods
- [x] Delete v1_1 routes
- Branch: `4935-remove-v1_1-synchronizations-endpoint-step2`

**Comment by Kartones** [comment]
I'm going to :fire: this two endpoints as we have absolutely no calls logged:
```
    get    '(/user/:user_domain)(/u/:user_domain)/api/v1_1/synchronizations'              => 'synchronizations#index',    as: :api_v1_1_synchronizations_index
    get    '(/user/:user_domain)(/u/:user_domain)/api/v1/synchronizations'              => 'synchronizations#index',    as: :api_v1_synchronizations_index    
```

**Comment by javisantana** [comment]
\o/
