### ISSUE TITLE
geocoding checks freeze the editor

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#4939]
When you have some geocodings pending (lets say 3) there are checks every second for all of them so if the editor takes some time to answer the requests are queued and every action you try to do in the editor takes a lot of time because there are no slots to send the requests

Geocoding and other batch process requests should not be raised if the previous check didn't arrive
 
cc @xavijam 

<img width="585" alt="screen shot 2015-08-07 at 11 05 20 am" src="https://cloud.githubusercontent.com/assets/30147/9132518/60ebcc60-3cf4-11e5-9e91-25ceb07c7f25.png">

**Comment by xavijam** [comment]
Geocodings and imports
