### ISSUE TITLE
when user select plain color basemap the embed does not go further than zoom level 20

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#4940]
- create a map and add a point
- zoom to level 24
- go to embed map

it shows level 20. If you force with zoom=24 if shows level 20 and it should be unlimited (or something like 32)

**Comment by gfiorav** [comment]
Found this snooping around the JS:

``` js
activate: function(color) {
    var lyr = new cdb.admin.PlainLayer({
      color: color,
      image: '',
      maxZoom: 28 //allow the user to zoom to the atom
    });

    this.model = lyr;

    this.map.changeProvider('leaflet', lyr);

    return false;
  },
```

**Comment by xavijam** [comment]
One year and a half ago... do you want me to remember that? :DDD.

**Comment by gfiorav** [comment]
@xavijam lol! 

Just asking what you think about increasing the zoom level to 32. You're the expert :smiley: in this part

**Comment by xavijam** [comment]
Nah, no expert of anything. I encourage you to try with 32, it doesn't sound so risky, so go ahead.

**Comment by gfiorav** [comment]
It turns out that the fix only works inside the editor. Looking into embedded maps fix

@javisantana

**Comment by gfiorav** [comment]
@javisantana I've tested it in every case but it works for me.

Take [this](https://team.cartodb.com/u/gfiorav/viz/0eaa923a-4b43-11e5-b442-0e018d66dc29/embed_map?zoom=29) embedded map for instance: you can now zoom up to 32 without any problem.

Please confirm you can as well so I can re-close this issue.
