### ISSUE TITLE
Account links are wrong for org users

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#4946]
After account pages redesign, all sidebar links are subdomain-based instead of `/u/username`-based for organization users. For example, profile link is

http://central-org-b-admin.localhost.lan:3000/profile

instead of

http://central-org-b.localhost.lan:3000/u/central-org-b-admin/profile

Normal users are fine: http://central-user-1.localhost.lan:3000/profile

URLs should be generated with `CartoDB.url(self, 'profile_user', {}, current_user)` instead of  `CartoDB.url(self, 'profile_user')`.

Also, [subdomainless url documentation](http://cartodb.readthedocs.org/en/latest/configuration.html#domainless-urls) should be improved to make clear that you should always use the right notation if you have `current_user`.

cc @Kartones

**Comment by xavijam** [comment]
I feel it is working properly now, at least in the editor part, isn't it?

**Comment by juanignaciosl** [comment]
No it isn't. Just checked both local and production. This is my account link: `https://juanignaciosl.cartodb.com/account`.

**Comment by xavijam** [comment]
But I haven't found that link in the UI, you mean it is a problem in the backend?

**Comment by juanignaciosl** [comment]
![screen shot 2015-10-02 at 11 54 30](https://cloud.githubusercontent.com/assets/932968/10243959/61767e26-68fc-11e5-8a60-c91efd6a1b31.png)

I mean that those links are wrong, even though they work.

**Comment by xavijam** [comment]
In which page are you seeing that error?

**Comment by juanignaciosl** [comment]
As I enter https://team.cartodb.com/u/juanignaciosl/profile .

**Comment by xavijam** [comment]
@MariaCheca, could you check if this problem is fixed or still happening?

**Comment by MariaCheca** [comment]
I'll be with it ASAP.
