### ISSUE TITLE
Allow to export the description and attribution of the map

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#4959]
If the map has a description and title enabled, they should be included in the export. Same thing with the attribution.

**Comment by javierarce** [comment]
First approach: 
![screen shot 2015-08-10 at 14 34 03](https://cloud.githubusercontent.com/assets/4933/9171560/d99019da-3f6c-11e5-8b6c-6ed7c894e996.png)

**Comment by saleiva** [comment]
Can we make the opacity of the overlay different to the one on the title & desc canvas?

**Comment by javierarce** [comment]
Sure!

**Comment by javierarce** [comment]
And this is an example of a real export: 

![download](https://cloud.githubusercontent.com/assets/4933/9178482/c2c1d18c-3f97-11e5-83f5-54167b755b27.png)

**Comment by javierarce** [comment]
![desktop](https://cloud.githubusercontent.com/assets/4933/9195593/3adff37e-4024-11e5-9977-e6d449c78e90.gif)

cc: @javisantana

**Comment by javierarce** [comment]
Here's a little preview on how it works (I still need to add the attribution)

![desktop](https://cloud.githubusercontent.com/assets/4933/9195593/3adff37e-4024-11e5-9977-e6d449c78e90.gif)

cc: @javisantana & @mbforr
