### ISSUE TITLE
Change pricing table button color

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#4961]
Change current `#397EB9` button on pricing table to `#0090D7 `:

<img width="996" alt="screen shot 2015-08-10 at 11 01 35" src="https://cloud.githubusercontent.com/assets/596509/9168651/6d8ba41e-3f50-11e5-9b08-6e2841560851.png">

<img width="977" alt="screen shot 2015-08-10 at 11 01 41" src="https://cloud.githubusercontent.com/assets/596509/9168653/6ec8d310-3f50-11e5-836a-09db8174a4fa.png">

**Comment by xavijam** [comment]
Moved to correct repo -> https://github.com/CartoDB/cartodb-central/issues/849
