### ISSUE TITLE
Deploy the new CDB_CartodbfyTable2 to production

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#4962]
Some remarks about this:
- Extension code in this PR: https://github.com/CartoDB/cartodb-postgresql/pull/78
- Name to be `CDB_CartodbfyTable` and backwards compatible. This will force a 2-step deploy since there's a dependency between editor and extension.
- No need to `move_to_schema` but probably check error scenarios
- Columns `created_at` and `updated_at` will be no longer present, this might impact editor's FE (unlikely) and BE (probably)

cc/ @pramsey

**Comment by rafatower** [comment]
@Kartones a couple of questions about [cartodbfy](https://github.com/CartoDB/cartodb/blob/582dcc957bf7f997b6c3ba04862f39c628ed21a0/app/models/table.rb#L1155-L1214) method:
- Why not calling `SELECT cartodb.CDB_CartodbfyTable('#{schema_name}','#{table_name}')` directly?
- Can we get rid of the workaround for ver < 0.5.0? I guess so...

**Comment by saleiva** [comment]
Soooo looking fwd to this

**Comment by rafatower** [comment]
Darn, we are calling `cartodbfy` twice:
```
# 1st call
(rdb:1) puts Kernel.caller.grep(%r{/src/cartodb/})                                                                                                                                                                                             
/home/developer/src/cartodb/app/models/table.rb:1157:in `cartodbfy'
/home/developer/src/cartodb/app/models/table.rb:344:in `block in import_cleanup'
/home/developer/src/cartodb/app/models/user.rb:616:in `in_database'
/home/developer/src/cartodb/app/models/table.rb:287:in `import_cleanup'
/home/developer/src/cartodb/app/models/table.rb:374:in `before_create'
/home/developer/src/cartodb/app/models/table/user_table.rb:184:in `before_create'
/home/developer/src/cartodb/app/models/table.rb:81:in `save'
/home/developer/src/cartodb/app/models/table_registrar.rb:18:in `register'
/home/developer/src/cartodb/app/connectors/importer.rb:174:in `persist_metadata'
/home/developer/src/cartodb/app/connectors/importer.rb:64:in `register'
/home/developer/src/cartodb/app/connectors/importer.rb:49:in `block in run'
/home/developer/src/cartodb/app/connectors/importer.rb:48:in `each'
/home/developer/src/cartodb/app/connectors/importer.rb:48:in `run'
/home/developer/src/cartodb/app/models/data_import.rb:617:in `new_importer'
/home/developer/src/cartodb/app/models/data_import.rb:350:in `dispatch'
/home/developer/src/cartodb/app/models/data_import.rb:161:in `run_import!'
```

```
# 2nd call
(rdb:1) puts Kernel.caller.grep(%r{/src/cartodb/})
/home/developer/src/cartodb/app/models/table.rb:1157:in `cartodbfy'
/home/developer/src/cartodb/app/models/table.rb:425:in `after_create'
/home/developer/src/cartodb/app/models/table/user_table.rb:189:in `after_create'
/home/developer/src/cartodb/app/models/table.rb:81:in `save'
/home/developer/src/cartodb/app/models/table_registrar.rb:18:in `register'
/home/developer/src/cartodb/app/connectors/importer.rb:174:in `persist_metadata'
/home/developer/src/cartodb/app/connectors/importer.rb:64:in `register'
/home/developer/src/cartodb/app/connectors/importer.rb:49:in `block in run'
/home/developer/src/cartodb/app/connectors/importer.rb:48:in `each'
/home/developer/src/cartodb/app/connectors/importer.rb:48:in `run'
/home/developer/src/cartodb/app/models/data_import.rb:617:in `new_importer'
/home/developer/src/cartodb/app/models/data_import.rb:350:in `dispatch'
/home/developer/src/cartodb/app/models/data_import.rb:161:in `run_import!'
/home/developer/src/cartodb/lib/resque/importer_jobs.rb:9:in `block in perform'
/home/developer/src/cartodb/lib/resque/base_job.rb:21:in `call'
/home/developer/src/cartodb/lib/resque/base_job.rb:21:in `run_action'
/home/developer/src/cartodb/lib/resque/importer_jobs.rb:9:in `perform'
```

**Comment by pramsey** [comment]
Only "good" news is that the expensive things (even in current code) just no-op if the table is already a "good" cartodb table. So it's wasteful, but not nearly as wasteful as you might think.

**Comment by Kartones** [comment]
- The one parameter call was legacy support, for before multiuser (it calls using the `public` schema), we can probably kill that one and use the two parameters version everywhere
- I'm not sure about our policy with breaking compatibility, but we can do something quite simple... bump to 1.0 and we've properly signaled things might change. Else if below 1.0 we assume things can break on a 0.X change... fine also by me
- Yep, it gets called twice because table might come from the importer or from other place, but when importing we do some "post/import tasks" like fixing geometries, etc. that assume table is already cartodbfied. But as Paul mentions cartodbfication function skips already present fields so it should be quick the second time.

**Comment by rafatower** [comment]
## Strategy for deployment
### Changes in the extension that can break compatibility:
- Function's signature and order of arguments:
```
CDB_CartodbfyTable(schema_name TEXT, reloid REGCLASS)
CDB_CartodbfyTable2(reloid REGCLASS, destschema TEXT DEFAULT NULL)
```
- timestamp columns are not added
- `reloid.schema` can be different from `destschema`. See `_CDB_Rewrite_Table`

@pramsey: any other thing worth considering?

### The deploy plan
- [ ] Stick to `CDB_CartodbfyTable()` public functions in the editor. This can be tested & released asap.
- [ ] Check any usage of timestamp columns in our code
- [ ] Make sure there's no compatibility problem. Especially with schemas. There shouldn't be because the relocation is done in the editor in some particular cases, not used from ogr2ogr.
- [ ] Rewrite`CDB_CartodbfyTable` in terms of `CDB_CartodbfyTable2` and make the later private.
- [ ] Bump version and test in CI and staging (from user's perspective the important interface is "you should call cartodbfy on your table" but the expected result also changes bc of timestamps).
- [ ] Deploy new extension version
- [ ] Upgrade all DB's extension version.
- [ ] Remove calls in the editor to `move_to_schema` from within the editor (importer.rb and synchronizatoin/adapter.rb). @Kartones, what do you think? what was the reason of `cdb_importer` temporary schema?

**Comment by Kartones** [comment]
about timestamp columns, I think that the editor uses metadata db updated_at instead of the table ones for listing most recent edited tables,etc. but that might be the only point of errors I can initially think about.

About cdb_importer, it is I think used  to have a separate space from the main user schema in which to import, prepare table, etc. before moving to the user one. Like avoiding touching his "production schema" until everything is ready. At least is the way I see it, else if we import directly to his schema, he might see or delete the table before, it could be treated as a ghost table and linked before importer does, etc. etc.

**Comment by rafatower** [comment]
Review of places where `created_at` and `updated_at` are used:
- In backend, I created a branch for it: [4962-cleanup-timestamp-columns](https://github.com/CartoDB/cartodb/compare/4962-cleanup-timestamp-columns?expand=1)
- Those columns cannot be deleted in existing user tables without dropping the related trigger. Taken into account in branch above.
- There are places in javascript code where they are used:
```
lib/assets/javascripts/cartodb/models/table.js
lib/assets/javascripts/cartodb/models/wizard.js
lib/assets/javascripts/cartodb/old_common/table_column_selector.js
lib/assets/javascripts/cartodb/table/geocoding_dialog/panes/geocoding_dialog_pane.js
lib/assets/javascripts/cartodb/table/header/merge_tables_dialog.js
```
I'll create a ticket for it once we have the extension available for testing.

cc/ @javisantana

**Comment by rafatower** [comment]
Kind of test plan:
- Normal user
  - import table: csv, shp
  - sync tables
  - ogr2ogr -overwrite
  - ogr2ogr -append
  - cartodbfy from sql api / ghost tables
- Org user:
  - import table
  - sync table
  - ogr2ogr -overwrite
  - ogr2ogr -append
  - cartodbfy from sql api / ghost tables

**Comment by Kartones** [comment]
@rafatower and raster import? at least that a basic geotiff imports and creates the overlays should be checked no?

**Comment by rafatower** [comment]
true, thanks for pointing out
