### ISSUE TITLE
Bad url in upload modal 

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#4969]
The text of 'supported formats' the link should be http://docs.cartodb.com/cartodb-editor.html#supported-file-formats

**Comment by viddo** [comment]
Related to #4482 , @javierarce could you take care of that one if you get to this one first?

**Comment by javierarce** [comment]
Sure, I'll take it.

**Comment by javierarce** [comment]
I'm closing this ticket since I took care of that in #4482.
