### ISSUE TITLE
Sort datasets by name

### ISSUE THREAD

**Issue by auremoser** [CartoDB/cartodb#4973]
This is a feature request, not a bug really, I tagged it for the data library because I think it would be really useful there too. No pressure though, feel free to remove my labels if they're bad.

## Context

I was talking to one of our users, and he complained about not being able to sort his datasets by name. He built his own index script mainly to leapfrog this missing taxonomy feature. 

## Current Issue

Even if you keep your datasets properly named, it's not possible to get value from that organizational schema in the current dataset index because you can't sort them by name - only order by date, visits, likes and size. Are those four criteria really more important than dataset name? Probably for some accounts, but sort by name would also be great. 

## Requested Feature

Sort by name, alphabetically (A-Z), reverse alphabetically (Z-A)

^ this is probably a non-trivial request and I totally respect that so no rush

## Screenshot

![sort](https://cloud.githubusercontent.com/assets/1559703/9177571/e91eaf4a-3f5f-11e5-8d04-bd1cabbdf39c.png)

**Comment by saleiva** [comment]
@auremoser isn't this easy to fix by searching the dataset? just asking...
Why the use case is different?

**Comment by auremoser** [comment]
Not exactly, the contextual situation is that sometimes you have a lot of datasets and you want them to be organized in a meaningful way based on a naming convention.

Like say I have bike data for nyc but I also have bike and building footprint data for a bunch of cities, and upload them out of order, so they will always be out of order even if I label them well:

- madrid-parking
- la-bike
- madrid-citybike
- nyc-bike
- madrid-bike

A lack of sorting means that if my datasets exceed one page, I have to remember what they were called to search for them, or I have to page through and find them. It's a pain. An A-Z sorting would be great, because then I could keep my own data library tidy. 

I actually have users who have asked me about this, and one group of users who built their own external dataset tool to sort because ours was insufficient for managing a bunch of datasets.

This is another issue, but I think the same would be nice for our Data Library (and I imagine that will be taken care of in the re-design); there is no way to sort, so users have to know what datasets we have so they can search effectively, and how could they know that unless they work here? There's no table of contents or index that gives order to those datasets, and even the tags are not very useful because there's no way to sort by administrative datasets vs cultural datasets etcet.

**Comment by saleiva** [comment]
Closing this since we are starting to think on global changes on the dashboard. @auremoser we will take care of this :P

**Comment by auremoser** [comment]
;)
