### ISSUE TITLE
Fix typo on Connect dataset / Twitter trends screen

### ISSUE THREAD

**Issue by csobier** [CartoDB/cartodb#4984]
"Differentiate" is misspelled on the Connect Dataset screen.  Fix typo.  
![image](https://cloud.githubusercontent.com/assets/13319925/9122992/99142dc0-3c5a-11e5-8ff1-91b88aa43a20.png)

Also, while I have your attention about this screen. I would suggest the following revision. Feel free to add to a future milestone and assign accordingly...

original copy: "Twitter trends
Enter search terms split in up to 4 categories to differenciate them with an extra column. The terms will match exactly."

Suggested revised copy: 
"Twitter trends
Enter up to four search requests using the Category fields." 

![image](https://cloud.githubusercontent.com/assets/13319925/9198477/6334fc58-400a-11e5-9aab-ed8869677a09.png)

http://docs.cartodb.com/cartodb-editor.html#tips-and-tricks-for-using-twitter-data

**Comment by xavijam** [comment]
Hey @csobier, thanks a lot for reporting it, i like your proposal and I'm adding it, but do you like:

"Enter up to four search *terms* using the Category fields" instead of "requests"

**Comment by csobier** [comment]
@xavijam Sure, "terms" works.
