### ISSUE TITLE
Delete map dialog?

### ISSUE THREAD

**Issue by csobier** [CartoDB/cartodb#4987]
Similar to issue  ([#4986](https://github.com/CartoDB/cartodb/issues/4986)), I was going to submit a wordsmith revision for the UI but I noticed that the dialog has changed since I updated it a week ago.

Creating this issue so that you tag it to a milestone and notify documentation.  It is really important that product changes how they think before changing anything in the UI.  

Current doc image that I captured a week or so ago. I have wordsmith suggestions but will hold off until we can enforce a workflow where all content/UI changes are communicated:
![image](https://cloud.githubusercontent.com/assets/13319925/9199653/9ddf2aca-4011-11e5-8648-a6ddedf1db29.png)

**Comment by saleiva** [comment]
This shouldn't have change. What changes are you refering to?
This is not the delete map dialog, your screenshot is from the delete dataset dialog.
So feel free to suggest the changes, there are no changes here

**Comment by csobier** [comment]
Apologies- typo, I meant Delete Dataset (and corrected the title).  Am I seeing different content based on my account type?  See the attached Delete Dataset dialog as it appears today, notice the different in content from the original image above.

![image](https://cloud.githubusercontent.com/assets/13319925/9223854/edd80582-40cb-11e5-9a08-2a322d729413.png)

**Comment by saleiva** [comment]
Again, this is because you have an affected map, so we need to inform you. But the dialog is the same with different variations.

**Comment by saleiva** [comment]
but... @javierarce I spotted two minor things that we could tackle
- [ ] Buttons doesn't keep centered when resizing the window
- [ ] We shouldn'd add <br>'s in the text since it makes the hyerarchy to looks very weird.

**Comment by csobier** [comment]
Okay, I haven't changed anything in my datasets or maps so I am just
looking for consistency, weird.  Is there a spreadsheet, or repository, of
all of these dialogs and the rules of when different dialogs are applied?
Also, it the text varies by account type, I should know as well.  I am just
trying to capture a representation of what the end-user sees.  Let me know
if I am doing something wrong.

On Wed, Aug 12, 2015 at 8:30 AM, Sergio Álvarez Leiva <
notifications@github.com> wrote:

> Again, this is because you have an affected map, so we need to inform you.
> But the dialog is the same with different variations.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/4987#issuecomment-130283072>.
>



-- 
*Christa Sobier*
Technical Writer

*CartoDB—Map Your World's Data*
143 Roebling St 2A, Brooklyn, New York, 11211, USA
T: +1.917.463.3232
W: www.cartodb.com

Live sessions to learn CartoDB <http://cartodb.com/webinars/>

**Comment by saleiva** [comment]
Nope, there isn’t.
If you try to delete a dataset that is not being used on any map, you will get the dialog you want.

S.

-----
@saleiva
