### ISSUE TITLE
CartoDB CSV exported to XLSX has incorrect column values in Excel

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#4991]
Please ref S/B 6249234

Test dataset: 
https://team.cartodb.com/u/stephaniemongon/tables/csv_to_excel_test_1/table

To replicate:
1. Export a CSV from a CartoDB dataset that has polygon geometry
2. Open the CSV in Excel

Expected behavior:
CSV export will open in Excel with same column field values as in the original CartoDB dataset's Data View

What's happening:
![screen shot 2015-08-11 at 2 24 51 pm](https://cloud.githubusercontent.com/assets/1779444/9206297/e57a1a16-4034-11e5-90cd-7b448dd553d6.png)

Client is unable to edit dataset in Excel. Is this just a display issue in Excel because the_geom is too long, so client would be unable to click on a field to edit b/c long geom looks like it's pushing values into incorrect column? Or is it error b/c of Excel character limit?

**Comment by rafatower** [comment]
Regarding excel limits, googling a little:
https://support.office.com/en-nz/article/Excel-specifications-and-limits-16c69c74-3d6a-4aaf-ba35-e6eb276e8eaa
http://superuser.com/questions/182721/excel-cell-length-limit

The sample file has some ~120K so most likely not supported by excel.

Regardless the display issue (very wide column) I'm pretty sure the rightmost cells can be browsed with the cursor keys. Also, most likely the order of the columns can be decided at import time.

I use Linux and don't have a copy of excel to test that. Anyway, this is not a cartodb platform issue so I'm closing it.
