### ISSUE TITLE
named map sent in viz.json instead of layergroup

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#4992]
I can't reproduce this error all the times but It happens very often in production:

- you change the table privacy from private to public
- you get the viz.json for a visualization using that table and a named map is sent when all the tables are public
- checking the database the canonical visualization privacy is public but the associated user table is private

```
irb(main):019:0> r
=> #<Carto::UserTable name: "roads", privacy: 0, updated_at: "2015-08-04 07:57:27", tags: nil, geometry_columns: nil, rows_counted: 0, rows_estimated: 0, indexes: nil, database_name: nil, description: nil, table_id: 632161, id: "f0dc2556-4e5a-490d-8b89-7d40b3fc1001", user_id: "b7861beb-21d4-46bc-ae00-5f09f77701a6", map_id: "b7d567fe-f091-42be-8980-917122af4027", data_import_id: "5284e386-01fd-4112-91e8-433df5b81990">
irb(main):020:0> r.visualization
  Carto::Visualization Load (0.9ms)  SELECT "visualizations".* FROM "visualizations" WHERE "visualizations"."map_id" = 'b7d567fe-f091-42be-8980-917122af4027' AND "visualizations"."type" = 'table' LIMIT 1
=> #<Carto::Visualization id: "af713c78-3a6d-11e5-abf3-60f81db078a6", name: "roads", description: nil, type: "table", tags: nil, privacy: "public", created_at: "2015-08-04 07:57:27", updated_at: "2015-08-11 20:32:04", encrypted_password: nil, password_salt: nil, map_id: "b7d567fe-f091-42be-8980-917122af4027", active_layer_id: "d2cbf54e-71e6-46b9-a13d-dacdc757234e", url_options: "title=true&description=true&search=false&shareable=...", user_id: "b7861beb-21d4-46bc-ae00-5f09f77701a6", permission_id: "2abf7295-7d5b-4bf5-81a8-e601f16bcdfb", source: nil, locked: false, license: nil, title: nil, kind: "geom", parent_id: nil, prev_id: nil, next_id: nil, slide_transition_options: "{\"time\":0}", active_child: nil>
```

It would be nice to check what's going on on privacy change that makes the user table does not change privacy.

I think it could be related with #2407

**Comment by Kartones** [comment]
This is a good testing scenario to capture a communication error so using it as the basis for trying to recover from tiler communication errors when staving table privacy. 

Also I've seen some 503s so this actually happens (although might not be doing a privacy change) so good to have it covered.

**Comment by Kartones** [comment]
Branch: `4992-recover-from-tiler-errors-saving-privacy`

**Comment by Kartones** [comment]
:( Debugging, because I found an issue here, we're calling a premature `.do_store` before having fetched the `attributes` so all privacy modification checks seem to get overriden

**Comment by Kartones** [comment]
Found at error logs this other scenario:
```
File "services/named-maps-api-wrapper/lib/named-maps-wrapper/named_maps.rb", line 67 in get
File "app/models/visualization/member.rb", line 461 in get_named_map
File "app/models/visualization/member.rb", line 630 in save_named_map
File "app/models/map.rb", line 109 in block in update_related_named_maps
File "app/models/map.rb", line 108 in each
File "app/models/map.rb", line 108 in update_related_named_maps
File "app/models/map.rb", line 68 in after_save
... non-project frames
File "app/models/table.rb", line 456 in after_save
File "app/models/table/user_table.rb", line 199 in after_save
... non-project frames
File "app/models/table.rb", line 84 in save
```

**Comment by Kartones** [comment]
ok, researched this one. The scenario is safe because if something fails saving the map, privacy hasn't been propagated yet (and map doesn't stores it). We can get some related visualizations with stale data and others updated, but that's not the scope of this ticket.

Will see another possible scenario related with the importer and then close the ticket.

**Comment by Kartones** [comment]
Another (trickier) scenario found to cover (see `specs/model/table_spec:2286`).
Idea is to try-catch calls to `privacy_manager.set_from_table_privacy`, `privacy_manager.propagate_to` and `notify_privacy_affected_entities` and using:
```ruby
if @user_table.previous_changes.keys.include?(:privacy)
        old_privacy = @user_table.previous_changes[:privacy]
      end
```
Be able to revert changes on the own table and related ones. To take into account: Avoiding recursion and maybe keeping a list of modified items to only revert on those.
