### ISSUE TITLE
Create 'Organization over quota' email 

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#5001]
When a multiuser organization is over MB quota, we need to send an email to the ORG admin

**Comment by josecruz** [comment]
Do we have copy for this?

**Comment by andrewxhill** [comment]
cc @brittanymicek just an email to Organization owners if the entire org goes over quota

**Comment by brittanymicek** [comment]
got it!

On Wed, Aug 12, 2015 at 1:42 PM, Andrew W. Hill <notifications@github.com>
wrote:

> cc @brittanymicek <https://github.com/brittanymicek> just an email to
> Organization owners if the entire org goes over quota
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/5001#issuecomment-130386842>.
>



-- 
*Brittany Micek*
Content Writer

*CartoDB—Map Your World's Data*
143 Roebling St 2A, New York, 11211, USA
T: + <%2B34695497365>19174633232
W: www.cartodb.com

Live sessions to learn CartoDB <http://cartodb.com/webinars/>

**Comment by brittanymicek** [comment]
Hey there,

It looks like your team is growing fast and you’ve run out of space.

This is a friendly reminder that your organization is *over quota*. You can upgrade your account and/or purchase more space to continue working at the capacity you need.

Upgrading your account is really simple just contact one of our *account experts* or *manage your account settings*.

In the meantime, take a look at some of the amazing things we’ve been up to at *cartodb.com*.

Thanks and Happy Mapping,

XXXXX
xxxxxxxxxxxxx


Hey,

You’ve been busy and that’s great but your team has run out of space!

Your organization is *over its quota*. It's time to upgrade your account and get more space. Upgrading is really simple:
1. Login to your CartoDB account and upgrade your settings OR;
2. Contact one of our account specialists - we’d be more than happy to help.

For now, check out amazing maps over at *cartodb.com*.

Happy Mapping,

Xxxxx Xxxxxx
Xxxxxxxxxxxxxxx

**Comment by josecruz** [comment]
I'm not sure if it's an individual user email but:
![org](https://cloud.githubusercontent.com/assets/596509/9256251/6343a46e-41e6-11e5-83d3-4eda200f9b1d.png)

**Comment by saleiva** [comment]
Not sure about the user @saleiva. Also I'd add a bit of space between 1.
And 2.

**Comment by josecruz** [comment]
Updated:

![org](https://cloud.githubusercontent.com/assets/596509/9256800/a965b65a-41e9-11e5-8fa8-1c887b84c282.png)

I would show the username that runned out of MB's on the title.

**Comment by saleiva** [comment]
Then not the username, just the org name although I also think is not
needed since you just can have an org

**Comment by saleiva** [comment]
Also, Not whe numbered list looks too much separated :)

**Comment by josecruz** [comment]
Better? 
![org](https://cloud.githubusercontent.com/assets/596509/9305284/7c57df12-44f0-11e5-9206-90267a62cd87.png)

**Comment by saleiva** [comment]
I'd remove the quotes, and for me is ok

**Comment by josecruz** [comment]
Done!
![org](https://cloud.githubusercontent.com/assets/596509/9305428/af03c736-44f1-11e5-8167-70fc864af1c7.png)

**Comment by juanignaciosl** [comment]
Related suggestions:

About features:
- We should also warn if organization runs out of seats. What do you think, @andrewxhill, @saleiva?

About text (@brittanymicek, @csobier?):
- Subject and title should be "Your organization #{@organization.name} is over its quota"
- Current text doesn't say the actual problem: "No more users will be able to sign up until you get more space."

**Comment by juanignaciosl** [comment]
@andrewxhill @saleiva just realized a more relevant detail: if you're an organization owner you can't upgrade on your own, so email text should not say anything about login but just contact (an email link), isn't it? So, suggestion:


Hey,

You’ve been busy and that’s great but your team has run out of space!

Your organization is over its quota. It's time to upgrade your account and get more space. Upgrading is really simple: contact one of our account specialists - we’d be more than happy to help.

For now, check out amazing maps over at cartodb.com.

Happy Mapping,

**Comment by csobier** [comment]
Please wordsmith to Brittanys' suggestion above, I would also not use "over its quota".  Typically, the terminology is that you have reached your quota.  I'm sure she can help with the final copy when you the dialogs are ready.

**Comment by juanignaciosl** [comment]
@csobier I copied the wrong part of @brittanymicek comment. I've updated my previous comment with the right text, and my doubt about the need for login is done. I will continue with that and wait for the subject until my final submission.

Seat question is still open but I can open a new issue later.
