### ISSUE TITLE
Seems like importer is using the user queries timeout

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#5009]
See import id `41c250a6-3d4a-49d6-a963-8130e144560b`
```
2015-08-12 16:33:55 UTC: Finished importing data from /tmp/imports/20150812-19901-nasszk/twitter_alfabet_alphabet_abcxyz_google.csv
2015-08-12 16:33:56 UTC: Proceeding to register
2015-08-12 16:33:56 UTC: Before renaming from importer_6cab8642410111e5a8420e6e1df11cbf to twitter_alfabet_alphabet_abcxyz_google
2015-08-12 16:33:56 UTC: Before moving schema 'twitter_alfabet_alphabet_abcxyz_google' from cdb_importer to piensaenpixel
2015-08-12 16:33:56 UTC: Before persisting metadata 'twitter_alfabet_alphabet_abcxyz_google' data_import_id: 41c250a6-3d4a-49d6-a963-8130e144560b
2015-08-12 16:39:34 UTC: Exception: PG::Error: ERROR:  canceling statement due to statement timeout
CONTEXT:  SQL statement "UPDATE twitter_alfabet_alphabet_abcxyz_google SET the_geom_webmercator = cartodb.CDB_TransformToWebmercator(the_geom) "
PL/pgSQL function _cdb_populate_the_g
```

The stacktrace beautified:
```
app/connectors/importer.rb:71:in `rescue in register'
app/connectors/importer.rb:57:in `register'
app/connectors/importer.rb:49:in `block in run'
app/connectors/importer.rb:48:in `each'
app/connectors/importer.rb:48:in `run'
app/models/data_import.rb:617:in `new_importer'
app/models/data_import.rb:350:in `dispatch'
app/models/data_import.rb:161:in `run_import!'
lib/resque/importer_jobs.rb:9:in `block in perform'
lib/resque/base_job.rb:21:in `call'
lib/resque/base_job.rb:21:in `run_action'
lib/resque/importer_jobs.rb:9:in `perform'
```

The user `piensaenpixel` had the "Timeout for user queries" set to `300000` which should be in ms. That roughly corresponds to 5 min before crashing with db statement timeout error.

**Comment by rafatower** [comment]
Note: I raised the timeout as a temporary workaround.

**Comment by zenitraM** [comment]
ogr2ogr connects with the proper user and does not override the statement_timeout so this is expected

**Comment by ethervoid** [comment]
yeah but that users are getting timeout because the import spent more then 5 minutes in the import so they get a timeout

**Comment by rafatower** [comment]
Another issue is that those imports are not getting logged in metrics cc/ @ethervoid

**Comment by rafatower** [comment]
Reopening this, I had to revert the changes because it is troublesome. We need to take into account a couple of scenarios:
- direct connection wiht DB
- connection through pgbouncer -> this was failing with this error:
```
2015-09-01 13:19:59 UTC: ogr2ogr output:          ERROR 1: PQconnectdb failed: ERROR:  Unsupported startup parameter: options
```

**Comment by iriberri** [comment]
Uops, I'm starting to see users with this last import error. @rafatower should I tell them just to try again?

**Comment by rafatower** [comment]
yes, please. I rolled back and deployed again.

**Comment by javisantana** [comment]
If i recall correctly we changed were doing connections to the database without any pgbouncer in the middle to allow rails to setup the desied timeout.

cc @Kartones @zenitraM

**Comment by Kartones** [comment]
In the jobs/queues servers I think so too...

**Comment by rafatower** [comment]
@javisantana et al: there are different setups where that's not true: staging, dedicated servers, on-premises.

**Comment by rafatower** [comment]
@rochoa this somehow involves platform and dataservices. Let's discuss possible solutions. I'm pretty sure that most import errors are related to this and that we're not seeing them all https://github.com/CartoDB/cartodb/issues/5790

**Comment by javisantana** [comment]
I think this is a systems configuration problem right?

**Comment by rafatower** [comment]
it depends on how you want to see the issue, but yes.

**Comment by rochoa** [comment]
@rafatower let me know how I can help because I'm not aware of how this is related. :see_no_evil:

**Comment by rafatower** [comment]
@zenitraM is the one who knows the problem better.

**Comment by javisantana** [comment]
I know the problem:

- we had a problem with statement timeout on imports
- we decided to use direct postgres connections to avoid pg_bouncer (it does not allow to change the statement timeout)
- we *in theory* changed the ruby code to set the desired statement_timeout for an user (@kartones did it)

So either the code is not working or resque machines are not connection directly to postgres

**Comment by Kartones** [comment]
Yeap, but the order is a bit switched:
- 1) found issue with statement timeouts
- 2) Changed code to set accordingly
- 3) Found that pg_bouncer made this changes not work always, switched to direct connections at queues, etc.

**Comment by rafatower** [comment]
@javisantana all places that I know are using the tweaked statement_timeout in ruby code **but** ogr2ogr is not using those connections. In some setups we use pg_bouncer and in some we don't 

See https://github.com/CartoDB/cartodb/commit/a1b064f772455a87a31b4b8b3db8477ac8d644b1 (a possible workaround I had to revert for those cases going through pg_bouncer).

and https://github.com/CartoDB/cartodb/issues/5009#issuecomment-136733965

**Comment by javisantana** [comment]
is "UPDATE twitter_alfabet_alphabet_abcxyz_google SET the_geom_webmercator = cartodb.CDB_TransformToWebmercator(the_geom)" being launched by ogr2ogr ?

Why are we launching that query, the new cartodbfication should not do that

**Comment by rafatower** [comment]
No, nope, sorry. We're mixing two issues here.
- ruby timeouts: fixed
- ogr2ogr timeouts: open

I'll close this ticket and create a new one in platform to avoid confusion.
