### ISSUE TITLE
Wrong Configuration/Account link in Configuration/Plan view

### ISSUE THREAD

**Issue by MariaCheca** [CartoDB/cartodb#5013]
Following this route as logged in user: `https://cartodb.com/account/[username]/plan`, clicking in the "Account" link should lead to `https://[username].cartodb.com/account`, but instead leads to `https://cartodb.com/account/mariacheca`. That returns a 500 status.

![screen shot 2015-08-13 at 3 35 19 pm copy](https://cloud.githubusercontent.com/assets/2141690/9250992/1e6e826a-41d1-11e5-94e8-302cdeed9f5e.png)

**Comment by MariaCheca** [comment]
Will need help @matallo or @juanignaciosl because central is involved.

**Comment by matallo** [comment]
Totally, I'll give you the hint to fix it, well spotted!

**Comment by MariaCheca** [comment]
Wrong repo
