### ISSUE TITLE
Configuration section footer not sticked to page bottom

### ISSUE THREAD

**Issue by MariaCheca** [CartoDB/cartodb#5018]
When the browser window has more height than the content itself the footer takes "its bottom" from the content dimensions.

![screen shot 2015-08-13 at 5 22 25 pm copy](https://cloud.githubusercontent.com/assets/2141690/9253891/cc3a9078-41e0-11e5-900b-4103c45d8847.png)

**Comment by xavijam** [comment]
Super minor, closing.
