### ISSUE TITLE
Remove zclip completely

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#5023]
On Settings --> Your OAuth credentials (URI `/u/user/your_apps/oauth`)

<img width="690" alt="screen shot 2015-08-13 at 19 42 48" src="https://cloud.githubusercontent.com/assets/978461/9257016/9475d216-41f3-11e5-9674-18f802935350.png">

It's essentially the same issue as on #4486 (publish modal), where we decided to remove it, so we should probably do the same here, right? This way we could remove the zclip lib completely (this is the only place left where it's used!):
 - vendor/assets/javascripts/ZeroClipboard.js
 - app/assets/flash/ZeroClipboard.swf

**Comment by saleiva** [comment]
Since @MariaCheca is working on those pages, I'd assign to her

**Comment by xavijam** [comment]
http://zenorocha.github.io/clipboard.js/

**Comment by viddo** [comment]
:+1:

**Comment by zenorocha** [comment]
+1 for clipboard.js ;)

**Comment by MariaCheca** [comment]
Zclip removed months ago. Closing!
