### ISSUE TITLE
UX Disconnect to Mailchimp: Change copy

### ISSUE THREAD

**Issue by mariodelvalle** [CartoDB/cartodb#5026]
Change copy

"... on your MailChimp settings page" for "... on your Mailchimp extras page section Authorized applications"

**Comment by xavijam** [comment]
I don't think it sounds very well, could you help us here @csobier please? Thanks.
_You can revoke the CartoDB access from your account by clicking the button below and doing it manually on your Mailchimp extras page section Authorized applications._

**Comment by csobier** [comment]
@xavijam See my suggested wordsmith (based on the Instagram dialog you shared as a reference). You can decide whether or not you want to use "For your own security", it can be omitted and still describe the action.

Disconnect your MailChimp account
Revoke access to CartoDB

For your own security, we are unable to disconnect your MailChimp account from CartoDB. You can revoke access yourself by manually editing your MailChimp authorized applications.

button: GO TO MAILCHIMP

**Comment by xavijam** [comment]
For me looks great!
