### ISSUE TITLE
Added new field 'display name' for modal when edit a dataset

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/cartodb#5033]
Add a new modal field to support the "pretty" name for **datasets only for datasets**. 

We need this new field because we are working to deprecate the common-data's `meta_dataset` table and use the canonical visualizations for this purpose so we are going to use this name when we want to display the name of the dataset in the `data library` section

![image](https://cloud.githubusercontent.com/assets/1730320/8983387/4fb52c00-36ca-11e5-95a4-a79af52797e0.png)

Add one new fields:

* source
   free text input

cc @saleiva @viddo

**Comment by viddo** [comment]
So, basically something like this?
```
Dataset name:[ the_alphanumeric_name ]
Pretty name: [ Some other text that do no require any resemblance to the actual name of the table ]
```

**Comment by ethervoid** [comment]
Yes that's the idea

**Comment by saleiva** [comment]
Ufff, this will be available for all users? I dont see it guys... We should
generatw it automatically

**Comment by ethervoid** [comment]
Automatically from the `the_alphanumeric_name` to `Alpha numeric name`? What about tables like ne01_lala

// @javisantana

**Comment by saleiva** [comment]
Yep

**Comment by ethervoid** [comment]
Just to write it down, we are going to block this feature to be only used by users with the `data-library` flag enabled

**Comment by iriberri** [comment]
Bump! Could we do something here? Right now is impossible to publish a common dataset without manually editing the metadata table, which is dangerous.

**Comment by saleiva** [comment]
it should be only appear on the common data ones, right?

**Comment by ethervoid** [comment]
In the user with the `data_library` feature flag activated so yes in our case in common-data

**Comment by matallo** [comment]
hey @xavijam who should take this one?
