### ISSUE TITLE
[Suggestion] Add a "whole window" button for export image option

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#5041]
With the new functionality we have "lost" the quick flow to get a picture of everything in a couple of clicks. Do you think it would be interesting/useful to have a small button/option that selects the whole region instead of making the user select it?

cc @saleiva @javierarce

**Comment by javierarce** [comment]
Sounds good to me. Maybe we could add a button (like the classic fullscreen button) that would maximice the area to the whole mapview.

**Comment by iriberri** [comment]
I'd like that :)

**Comment by marianoju** [comment]
The (possible) button should maximize the selection to include all data point (possibly with a padding). I would like that. :+1:

**Comment by javierarce** [comment]
I'm closing this ticket, since we have it implemented here: https://github.com/CartoDB/cartodb/issues/5162

**Comment by marianoju** [comment]
@javierarce The new export function does *not* by default include all data points. I don't see a button (or other function) to include the “whole window” for export. User still has to adjust the export selection manually to include all (desired) data points.
