### ISSUE TITLE
Redesign connect data screen to make it fit without scrolling

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#5049]
Right now, the select a file button is hidden under the scroll

**Comment by saleiva** [comment]
cc/ @mariodelvalle

**Comment by josecruz** [comment]
I made this version with a small "dashed-box" that illustrates also the drag and drop action. Also, updated all margins to `28px` but on the footer, that the spacings are `20px`.

It works good in 11" MBA (lowest res.):
![create - new dataset - data file copy 4](https://cloud.githubusercontent.com/assets/596509/9632317/be0b4118-5186-11e5-8627-d9e25c36551d.png)

![create - new dataset - data file copy 5](https://cloud.githubusercontent.com/assets/596509/9632320/bfcc3a84-5186-11e5-8966-20787dd81b3b.png)
(Maybe on bigger screens we could add some space back)

**Comment by saleiva** [comment]
An idea. We leave this to just one input which says "_Enter an URL_ or _Select a file_". Clicking on "Enter an URL" will put the focus on the input, let you write and show the SUBMIT Button. Clicking on the "Select a file" would let the user to select the file.

**Comment by josecruz** [comment]
Here's the final version after your magic (thank to my magic):

* Bigger Screens
![create - new dataset - data file copy 8](https://cloud.githubusercontent.com/assets/596509/9684845/834a0eb6-531a-11e5-8fa6-7edd49f7930b.png)

* Smaller screens (lowest 11" res.)
![create - new dataset - data file final version](https://cloud.githubusercontent.com/assets/596509/9684863/a39c3c2a-531a-11e5-9540-029ada2287e9.png)

**Comment by xavijam** [comment]
Looks awesome :+1:

**Comment by xavijam** [comment]
I'll replace this section too

<img width="1037" alt="screen shot 2015-09-09 at 14 19 06" src="https://cloud.githubusercontent.com/assets/132146/9761561/c9b52980-56fd-11e5-9b77-eb19cd901309.png">

cc @javierarce

**Comment by xavijam** [comment]
@josecruz, could we use the same design we already have for the submit button?

**Comment by josecruz** [comment]
@xavijam yep! Also, let me change the "icons" style to make them "universal" (without zip, csv, xls thing)

**Comment by javierarce** [comment]
I like the new design, but I think the title or the icons should be reversed. [Right now it says](https://cloud.githubusercontent.com/assets/596509/9684863/a39c3c2a-531a-11e5-9540-029ada2287e9.png): "Connect from URL or upload your files" and then the input fields are 1) drag&drop/browse 2) URL

**Comment by josecruz** [comment]
Yep, I think you're right so I already updated that on designs + updated icons:
<img width="1433" alt="screen shot 2015-09-09 at 16 44 03" src="https://cloud.githubusercontent.com/assets/596509/9764948/0512d248-5712-11e5-8951-8188bb324cb9.png">

This version is in the last updated `dashboard-1.9.sketch`
