### ISSUE TITLE
Make a proposal of a dedicated learn screen within the dashboard that would link to the docs / academy

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#5053]
Would this make sense?

![screen shot 2015-08-17 at 14 54 18](https://cloud.githubusercontent.com/assets/132149/9305226/db3a261c-44ef-11e5-8d4b-ab215b1c6756.png)

cc/ @ohasselblad @andrewxhill @mariodelvalle

**Comment by ohasselblad** [comment]
:+1: for me. It's on my draft roadmap to integrate education resources with the rest of the site/product more!

**Comment by ohasselblad** [comment]
Speaking with @josecruz, it makes sense to me to have a few of the top-level academy courses listed there. We'll be merging the tutorials into academy soon, so they'll be in the fold as well. 

The three courses that make the most sense to expose through the editor are: Intro to CartoDB, Design Course, and SQL/PostGIS. 

A new course called Academy Lite will have shorter lessons (and lots of the tutorials) and cover things like CartoCSS in a few minutes, Essential SQL, etc.

FTR, acadmey roadmap is here: https://github.com/CartoDB/cartodb-management/wiki/Academy-Roadmap

**Comment by josecruz** [comment]
Okay so after the talk with Andye I made this modal that will appear after clicking on a "Learn" link on the header. I don't know if we're going to show the documentation/map academy tutorials inside this modal,  but it would be nice to have a small *thingy* to resume the read of your doc. (so you can enter the modal and read the doc and got back to your task)

![learn](https://cloud.githubusercontent.com/assets/596509/9637971/095b0cbc-51a4-11e5-9b6e-1ed7e35f50de.png)
![screen shot 2015-09-02 at 18 54 34](https://cloud.githubusercontent.com/assets/596509/9637979/1359251e-51a4-11e5-9e9a-5fe5094bbbb9.png)
