### ISSUE TITLE
Unify blues

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#5054]
![screen shot 2015-08-17 at 15 00 30](https://cloud.githubusercontent.com/assets/132149/9305319/c2839ff8-44f0-11e5-950a-687c18cda285.png)

The good one is the one on the description and tags, so we should use that on Maps | Shared with you | ... menu and the pagination, etc...

**Comment by xavijam** [comment]
They have the same color, the difference is one text has antialiased property and the other doesn't.

![antialiased](https://cloud.githubusercontent.com/assets/132146/9325625/062f35ac-4594-11e5-8b53-3b6ab97208cf.gif)

cc @viddo

**Comment by carlostallon** [comment]
Please, blue should be always *#3AA9E3*

![image](https://cloud.githubusercontent.com/assets/1712650/9326200/6f2b65fe-4598-11e5-9759-2350833b6992.png)

**Comment by carlostallon** [comment]
if we are using antialias we shouldn't use font-weight < 300

**Comment by xavijam** [comment]
@viddo, what do you propose?

**Comment by viddo** [comment]
About what? Are we choosing between correct color but no antialias, or slightly-different colors and antialias?

**Comment by carlostallon** [comment]
We only need to change the font-weight to fix the problem, IMO

**Comment by viddo** [comment]
@carlostallon Yeah, I don't question that, your call. :) 
but I think @xavijam had some concerns related to that (care to elaborate?)

**Comment by carlostallon** [comment]
Let's talk tomorrow quickly in the office about that, ok?

**Comment by xavijam** [comment]
Yep @carlostallon, but take into account if we have to check all the links with that font weight and how they look like it could take us some time, not as easy as change only a font-weight :).

**Comment by carlostallon** [comment]
Agree, let's talk tomorrow about the best way to deal with it :)

2015-08-19 19:25 GMT+02:00 Javier Álvarez Medina <notifications@github.com>:

> Yep @carlostallon <https://github.com/carlostallon>, but take into
> account if we have to check all the links with that font weight and how
> they look like it could take us some time, not as easy as change only a
> font-weight :).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/5054#issuecomment-132703422>.
>



-- 
Carlos Tallón
Designer & Baker

**Comment by xavijam** [comment]
Ping!
