### ISSUE TITLE
Clicking on user's profile picture while in their maps view leads to own dashboard

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#5055]
To reproduce this problem:

1. Sign in to your account
2. Visit some users public maps view (i.e. user.cartodb.com/maps)
3. Click on the user's profile picture

You are now redirected to your own dashboard, which should only happen when clicking on your own profile picture.

( Assigned to @matallo as per @saleiva indication :smile: )

**Comment by matallo** [comment]
this is not happening anymore, closing then
