### ISSUE TITLE
Errors with notification integrations should not be fatal

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#5062]
If, for example, Hubspot constructor is broken, some methods fail:

- https://github.com/CartoDB/cartodb/blob/master/app/models/data_import.rb#L731 ([error](https://rollbar.com/vizzuality/CartoDB/items/426/occurrences/7158397655/)).
- https://github.com/CartoDB/cartodb/blob/master/app/helpers/application_helper.rb#L160 ([error](https://rollbar.com/vizzuality/CartoDB/items/8692/).
- https://github.com/CartoDB/cartodb/blob/master/app/helpers/application_helper.rb#L169 ([error](https://rollbar.com/vizzuality/CartoDB/items/8690/)).

Methods depending on non-critical APIs should not trigger critical errors.

cc @javisantana @xavijam @matallo

**Comment by matallo** [comment]
agree, tell me how I can help

**Comment by javisantana** [comment]
I guess:

- try to see what are the problems
- fix them
- make the hubspot code not critical

**Comment by matallo** [comment]
there are some breaking workflows to review, indeed

the most common issue is when property doesn't exist / or the type sent is not the same than the one set in hubs / or when sending the date in a different format

also, from all the error types (`critical, error, warning, info, or debug`) we are not using critical but the others, maybe worth setting some critical (at least until we change workflows?)

**Comment by juanignaciosl** [comment]
Some context here: "breaking flows" (as @matallo said) are already well covered: we record debug information in Rollbar but everything goes unnoticed. This is not the problem the issue is about. The issue is about harder problems, not currently covered, such as a programming error in metrics code that makes editor stop working.

There're no "existing problems" not covered, AFAIK, so we should focus on making Hubspot code not critical, maybe with a "failure-safe wrapping" (that we can reuse for other non critical integrations), maybe making this an asynchronous task outside the request thread.

**Comment by juanignaciosl** [comment]
While having a talk with @jmartinter about integrating _more_ metrics services in CartoDB I thought maybe we should think about having an event bus for this kind of things. The same way we're decoupling  cache invalidation, there're events everywhere in CartoDB and many reactions to them could be done externally (metrics services, debug traces...). Just a though for an open discussion.
