### ISSUE TITLE
Check the need for ssl_required

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#5080]
There's some confusion about the need for `ssl_required` checks. Some controllers add it for all methods and all environments but some others exclude test and development environments. This should be unified (and probably `ssl_allowed` as well).

**Comment by Kartones** [comment]
Branch: `5080-remove-environment-based-ssl-checks`

**Comment by juanignaciosl** [comment]
FYI I recently [disabled ssl checks for development](https://github.com/CartoDB/cartodb/blob/master/config/environments/development.rb#L77), it was needed for groups [because of X-Forwarded-Proto header](https://github.com/CartoDB/cartodb-postgresql/blob/master/scripts-available/CDB_Groups_API.sql#L170).

**Comment by Kartones** [comment]
Uhm, interesting, I've migrated the approach that we had with `ApplicationController` to `SuperadminController`, let's see if is enough, but good to know there's a simple flag/option else to apply to environments.
