### ISSUE TITLE
CartoDB on Google: Geocoder Limits should not apply

### ISSUE THREAD

**Issue by andrewbt** [CartoDB/cartodb#5086]
Our superadmin settings for Google Cloud Platform accounts are restricting geocoding to 15,000/month (or whatever the settings are set to per Enterprise account).

Because GCP-CartoDB customers need their own Google Maps for Work license, CartoDB should simply act as a pass-through to the client's Google geocoder account without placing any of our own limits on how many geocodes the customer can perform per month. The client will be billed separately by Google on their own terms for however many geocodes they perform.

cc @javisantana

**Comment by andrewbt** [comment]
@javisantana @saleiva any news here?

**Comment by saleiva** [comment]
I let you prioritizing it @javisantana

**Comment by andrewbt** [comment]
If we at least can confirm whether or not it is a real problem (and if it's _our_ problem and not google's problem) then a potential client will be very happy!

**Comment by javisantana** [comment]
so you are proposing to remove geocoding limits for google maps for work clients, right?

**Comment by andrewbt** [comment]
Yes. More specifically, Google MfW clients already pay google for a limit
of 100,000 geocodes a month. The worry here is that CartoDB is
"accidentally" putting our 15,000 geocodes a month limit on them like we do
for regular AWS Enterprises. That means they can't access 85,000 geocodes
they already pay for unless we fiddle with our superadmin for them.

If that is true (we have evidence but I don't know for sure, that's my
first question to you, is this actually happening?), then it is a bug.
CartoDB should just be a pass-thru to Google and whatever limits or
conditions Google sets. Or the Enterprise admin should set the geocode
limits, _not_ in our internal superadmin.

Make sense @bradsonger ?

On Fri, Aug 21, 2015 at 7:05 AM, javi santana <notifications@github.com>
wrote:

> so you are proposing to remove geocoding limits for google maps for work
> clients, right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/5086#issuecomment-133373573>.
>



-- 
Andrew Thompson, Solutions Engineer

*CartoDB* | 143 Roebling St, 2A, Brooklyn, NY 11211
athompson@cartodb.com | T +1 508.333.7265 <+15083337265>
Web cartodb.com | Twitter @cartodb <http://twitter.com/cartodb>
Map Your World's Data

Live sessions to learn CartoDB <http://cartodb.com/webinars/>

**Comment by iriberri** [comment]
This is to be closed, right @rafatower?
