### ISSUE TITLE
CartoDB on Google: Places API integration

### ISSUE THREAD

**Issue by andrewbt** [CartoDB/cartodb#5089]
Feature requested by our partner CloudSherpas:

The Google Places API (which gives address/location name autocomplete) could be integrated in the "geocoding search box" on editor/public/embedded maps. The Places API involves a separate API key than the GMaps for Work client-id/crypto key we already have.

**Comment by saleiva** [comment]
So this is only for when looking for place names instead of addresses?

**Comment by andrewbt** [comment]
As far as I'm aware it'll do addresses too, but I don't think it does the
geocoding (could be wrong). It's an "autocomplete" API, so as you're typing
into the search box it gives you a list of places/addresses that
fuzzy-search match what you typed so far.

Our partner suggested adding it because it's a separate API but a lot of
Google customers already benefit from it. Could go with the geocoding
search pin/box redesign that's happening :-)

On Tuesday, September 1, 2015, Sergio Álvarez Leiva <
notifications@github.com> wrote:

> So this is only for when looking for place names instead of addresses?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/5089#issuecomment-136673937>.
>


-- 
Andrew Thompson, Solutions Engineer

*CartoDB* | 143 Roebling St, 2A, Brooklyn, NY 11211
athompson@cartodb.com | T +1 508.333.7265 <+15083337265>
Web cartodb.com | Twitter @cartodb <http://twitter.com/cartodb>
Map Your World's Data

Live sessions to learn CartoDB <http://cartodb.com/webinars/>
