### ISSUE TITLE
New widgets on actual editor UI

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#5114]

**Comment by saleiva** [comment]
https://github.com/CartoDB/cartodb-management/wiki/Embeds-revamp

**Comment by josecruz** [comment]
I'll upload here the principal versions of this:

![classic editor - 1 title - 1 visible layer](https://cloud.githubusercontent.com/assets/596509/9527287/6f8b8e5e-4cee-11e5-80ec-0f0524a9ae07.png)
![classic editor - 1 title - 1 visible layer copy 2](https://cloud.githubusercontent.com/assets/596509/9527299/83ada3fe-4cee-11e5-9c62-38a7ddbfbb74.png)

Also the one that allows to "sync" the legend with the vizualization (copies are not definitive, I'm gonna need help here)
![classic editor - 1 title - 1 visible layer copy 2](https://cloud.githubusercontent.com/assets/596509/9527393/2c420460-4cef-11e5-935c-43ffcf55bcd9.png)
_(the `(?)` icon will show a tooltip explaining that option)_


Also I made a small tweak to the white bottom bar that allows you to collapse it (for smaller screens e.g):
![classic editor - 1 title - 1 visible layer](https://cloud.githubusercontent.com/assets/596509/9527340/d924c326-4cee-11e5-9895-c52f268e52eb.png)

/cc @carlostallon and @piensaenpixel if you guys have time to give some feedback would appreciate it!

**Comment by carlostallon** [comment]
- In the new footer sidebar, It's weird to me have the same element in different places. I would think a solution where elements are always in the same place.
- the anchor to show/hide seems to small to me.
- We can make this design much more simple
![image](https://cloud.githubusercontent.com/assets/1712650/9544446/1abb9bce-4d81-11e5-900b-519f04478d4f.png)

**Comment by josecruz** [comment]
Okay so, updated margins all over the map view and I'll upload some of the most "general" screenshots (due there are like 12)

Tooltip:
![classic editor - 1 title - 1 visible layer options tooltip](https://cloud.githubusercontent.com/assets/596509/9634602/cf044bf2-5192-11e5-985a-6d6b079a597c.png)

White bar + Title:
![classic editor - 1 title - 1 visible layer](https://cloud.githubusercontent.com/assets/596509/9634660/136badda-5193-11e5-8c67-62090f41cdbb.png)

Torque bar + Legend + Description + Title
![classic editor - 1 title legend](https://cloud.githubusercontent.com/assets/596509/9634698/3fefeb96-5193-11e5-966f-fd06fc813637.png)

Collapsed white bar:
![classic editor - 1 title - 1 visible layer - expanded search](https://cloud.githubusercontent.com/assets/596509/9634694/3bc26b66-5193-11e5-98b9-e288da37afb4.png)

Low res. + Sync legends:
![classic editor legend sync -- low res -- mba11](https://cloud.githubusercontent.com/assets/596509/9634713/52366aaa-5193-11e5-8f7a-19b3ffe14150.png)

**Comment by josecruz** [comment]
I updated the white bar size to the one on embeds (the smallest one, without torque bar `42px`):
![classic editor - 1 title - 1 visible layer](https://cloud.githubusercontent.com/assets/596509/9680090/99b4c798-52f4-11e5-9401-be9c17940e60.png)
![classic editor legend sync](https://cloud.githubusercontent.com/assets/596509/9680092/9bbc601e-52f4-11e5-8fbb-91fbe29e377a.png)

**Comment by josecruz** [comment]
I updated all margins on the map elements to 10px (we still maintaining the 5px margin in embed)
e.g:
![classic editor - no title legend](https://cloud.githubusercontent.com/assets/596509/9715540/817634ea-5561-11e5-984e-f71507badb43.png)

Btw: So, we're going to mantain the fullscreen and share icons there? I tried a version without labels:
![classic editor - no title legend](https://cloud.githubusercontent.com/assets/596509/9715866/e1c769d8-5564-11e5-8610-14bf812e143f.png)

**Comment by josecruz** [comment]
I made a version that match the embed version on web:
![classic editor - 1 title - 1 visible layer copy 6](https://cloud.githubusercontent.com/assets/596509/9795373/78fd311a-57f0-11e5-8ec9-67eb3b72b971.png)

Also a version with floating elements.
![classic editor - 1 title - 1 visible layer copy](https://cloud.githubusercontent.com/assets/596509/9795407/b4c04c3c-57f0-11e5-9bc7-7eb50e7b70e2.png)

I was trying to think something different to the editor but not sure how to make it:
![classic editor - 1 title - 1 visible layer copy](https://cloud.githubusercontent.com/assets/596509/9795471/2be3a61a-57f1-11e5-98db-bf22fba31aa2.png)

**Comment by josecruz** [comment]
I designed 2 more different versions.

### V1: recreating embed on editor.
I made some small visual tweaks and move "outside" the map all controls:
![classic editor - 1 title - 1 visible layer copy 8](https://cloud.githubusercontent.com/assets/596509/9815562/55b0e66e-5897-11e5-9185-f9c7679056e7.png)

### V2: minimum needed elements with preview.
So the idea with this version is to mantain the "desktop view" as simple as posible and make an option over "Preview Map" called embed view with something like this:
![classic editor - 1 title - 1 visible layer copy](https://cloud.githubusercontent.com/assets/596509/9815624/deaae82a-5897-11e5-9837-81c8f91586b2.png)
![classic editor - 1 title - 1 visible layer copy 9](https://cloud.githubusercontent.com/assets/596509/9815636/f06d9cf6-5897-11e5-8ae1-19965961b72f.png)

**Comment by josecruz** [comment]
up!

**Comment by josecruz** [comment]
After talk in person yesterday I upload the latest changes.
- Outside map options buttons
- Improved visual style
- Maintaining the idea of an "embed preview" modal

Without torque bar:
![classic editor - 1 title preview embed copy](https://cloud.githubusercontent.com/assets/596509/9879347/4b05fc44-5bc7-11e5-809e-0ab2592e8209.png)

With torque bar:
![classic editor - 1 title preview embed copy](https://cloud.githubusercontent.com/assets/596509/9879355/569a663a-5bc7-11e5-8176-e36ae54a84a9.png)

Embed preview modal:
![classic editor - 1 title - 1 visible layer copy 9](https://cloud.githubusercontent.com/assets/596509/9879364/6207e308-5bc7-11e5-8311-d0bb0d084666.png)

**Comment by josecruz** [comment]
Okay so that is the final version, already updated and named as `Classic-Editor-0.2-Embed.sketch` on Dropbox folder.
