### ISSUE TITLE
Wrong URL on "from more X user" link

### ISSUE THREAD

**Issue by santisaez** [CartoDB/cartodb#5115]
Steps to reproduce the issue:

1. Log into CartoDB with your account
1. Go to a [public visualization](https://team.cartodb.com/u/saleiva/viz/saleiva.2245663e-2713-11e5-aa10-0e9d821ea90d/public_map?redirected=true)
1. Scroll down to "More from X user"
1. Click on any map - you will get a 404 error since the URL is formed with your logged username instead of the map owner, `https://team.cartodb.com/u/santisaez/viz/..` in my case

This feature works without problems if you're not logged into CartoDB.

**Comment by xavijam** [comment]
Well spotted @santisaez @saleiva

**Comment by santisaez** [comment]
Re-opening this issue since I have found a similar issue, steps to reproduce it:

1. You must be logged in CartoDB
1. Go to a [public visualization](https://team.cartodb.com/u/saleiva/viz/9395c832-ea0b-11e4-9dfc-0e9d821ea90d/public_map)
1. Scroll down to "datasets in use"
1. Click on any dataset, [example](https://team.cartodb.com/u/saleiva/tables/policestationsdec2012/public)
1. You will get a 302 redirection to an URL like `https://team.cartodb.com/u/<your-user>/tables/`
1. Then click on "maps using this dataset", it will return a 404 error since it doesn't exists, [example](https://team.cartodb.com/u/santisaez/viz/9395c832-ea0b-11e4-9dfc-0e9d821ea90d/public_map)

Example:

<img width="680" alt="screen shot 2015-09-30 at 10 37 38" src="https://cloud.githubusercontent.com/assets/223956/10188401/5402e610-675f-11e5-8bd9-22debff2fc4d.png">

**Comment by xavijam** [comment]
hey @santisaez, for me it is working, could you check it again?

**Comment by santisaez** [comment]
I have just tested again, following the same steps, and I confirm you that the error is still present.

**Comment by xavijam** [comment]
If it happens yet, we will take care of it with the new public pages, closing.
