### ISSUE TITLE
Changing import type resets changes guessing checkbox state

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#5122]
STR:
1. Open "connect dataset" modal
1. Click on "Dropbox" tab (or any other)

Expected result:
Checkbox remains unchecked.

Actual result:
Checkbox is checked again

**Comment by viddo** [comment]
@xavijam assigned you since you know these parts best

**Comment by xavijam** [comment]
Doing it in create-view-fixes branch.
