### ISSUE TITLE
feature request: click on legend items to filter map

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/cartodb#5129]
Plotly has a nice feature that when click on items in a legend it filters the data. 

For instance, in this map, you can toggle the data on or off:
https://plot.ly/~Dreamshot/547/access-to-paid-vacation-by-occupation-private-industry-2010-2014/

I've spoken to lots of people who want ways to filter data on their maps from the editor. This seems like a natural way to incorporate that.

**Comment by saleiva** [comment]
Already planned! :)
Look at this! :) -> https://github.com/CartoDB/cartodb-management/wiki/Embeds-revamp

**Comment by ohasselblad** [comment]
nice! you're steps ahead of me :)
