### ISSUE TITLE
If you try to import from data-library and fails, disappear from the list

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/cartodb#5132]
**Problem**

I've trying to import a dataset from data-library without connection and failed. After that I don't have the datasets imported and has disappear from the data-library list

**Solution**

If there is an import error we should not add to `external_data_import` so we could re-import the dataset

**Comment by Kartones** [comment]
Note to self: Fix at #https://github.com/CartoDB/cartodb/blob/master/app/models/data_import.rb#L646
