### ISSUE TITLE
Improve named_maps_spec test to use the sql_api_config instead of literal

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/cartodb#5139]
We need to check what is the appropriate config for the endpoint of this tests and change the expected for the config value

1) CartoDB::NamedMapsWrapper::NamedMaps only_torque_layer checks returned viz.json given a named map with only a torque layer
     Failure/Error: vizjson[:layers][1][:options][:sql_api_endpoint].should eq '/api/v1/sql'

       expected: "/api/v1/sql"
            got: "/api/v2/sql"

       (compared using ==)
     # ./spec/models/named_maps_spec.rb:378:in `block (3 levels) in <top (required)>'

  2) CartoDB::NamedMapsWrapper::NamedMaps torque_and_normal_layers checks returned viz.json given a named map with a normal layer and a torque one
     Failure/Error: vizjson[:layers][2][:options][:sql_api_endpoint].should eq '/api/v1/sql'

       expected: "/api/v1/sql"
            got: "/api/v2/sql"

       (compared using ==)
     # ./spec/models/named_maps_spec.rb:547:in `block (3 levels) in <top (required)>'

// @Kartones

**Comment by iriberri** [comment]
I think we can close this one, right? The NamedMapsWrapper does no longer exist. See https://github.com/CartoDB/cartodb/blob/29bfb34ea70d8f77f1876cd124dbcf6d9fb6b7be/spec/lib/carto/named_maps/template_spec.rb now.
