### ISSUE TITLE
Disk quota validation error doesn't prompt user message

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#5148]
1. Set quota_in_bytes = 10 (bytes) for a user in the database.
2. Go to his account page.
3. Save button displays "Error updating your account details" without displaying anything specific.

cc @iriberri

**Comment by MariaCheca** [comment]
Unable to reproduce the steps, it's possible that the problem is not happening anymore due to its age.

**Comment by juanignaciosl** [comment]
Yes, I can't reproduce it either.
