### ISSUE TITLE
Adapt torque bar in embed designs

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#5149]
- [ ] Embed
Embed mobile
Public page
Embed full screen

**Comment by josecruz** [comment]
![artboard](https://cloud.githubusercontent.com/assets/596509/9637419/e9cfbb98-51a0-11e5-8a22-b25954623e55.png)
![ti de le li copy 2](https://cloud.githubusercontent.com/assets/596509/9637420/ee54681c-51a0-11e5-876d-437dc200669f.png)
![torque legend](https://cloud.githubusercontent.com/assets/596509/9637426/f69ffc48-51a0-11e5-818c-bf96bd66b82f.png)

**Comment by saleiva** [comment]
Not liking the mobile view of the embed. It looks too compressed and the date is completely discconected from the bar now. Needs to keep working on it.

**Comment by josecruz** [comment]
Okay so on the embed one I updated colors + sizes and made a similar version to the one we designed a while ago:

![ti de le li copy 3](https://cloud.githubusercontent.com/assets/596509/9656078/debc788c-5235-11e5-9ac0-9fa273886054.png)
![ti de le li copy 2](https://cloud.githubusercontent.com/assets/596509/9656079/ded9b726-5235-11e5-8eff-48b3a07ab09c.png)

**Comment by saleiva** [comment]
better, although weird that the margins of the attribution button are not the same now...

**Comment by josecruz** [comment]
Talked in person:
We're going to perform some user testing over the mobile embed ones.
