### ISSUE TITLE
Add sync with map and filter legend config panel

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#5153]

**Comment by josecruz** [comment]
The (?) button will show a tooltip explaining that feature
![classic editor legend sync selected 2](https://cloud.githubusercontent.com/assets/596509/9636657/e8331df6-519c-11e5-9def-4d07c37ad32c.png)

**Comment by saleiva** [comment]
two different options? u sure?

**Comment by josecruz** [comment]
Okay I'll let just one if you can always pick what you want to show on the legend, right?

**Comment by josecruz** [comment]
closing this due final version here #5114
