### ISSUE TITLE
Make "Export Image" export image elements too

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#5155]
Example uses [this map](http://cdb.io/1TZEwfZ).

Map is:
<img width="1280" alt="screen shot 2015-08-20 at 16 56 47" src="https://cloud.githubusercontent.com/assets/4222826/9386609/9a3b7430-475c-11e5-8ca3-44dd6ccd54a8.png">

Selected "Export Image" like this:
<img width="1280" alt="screen shot 2015-08-20 at 16 57 09" src="https://cloud.githubusercontent.com/assets/4222826/9386623/ad1360ea-475c-11e5-96b7-0d77d2b2bb78.png">

Obtained result:
![download](https://cloud.githubusercontent.com/assets/4222826/9386639/b48bb9b2-475c-11e5-8b18-a5a8d6ac5cac.png)

**Comment by saleiva** [comment]
AFAK images are not yet implemented, so this is a feature :)

**Comment by gfiorav** [comment]
Rectified :) @saleiva

**Comment by javisantana** [comment]
I did it but looks like it was removed in the last change of that modal cc @javierarce 

here is where the image should be rendered https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/common/dialogs/static_image/export_image_result_view.js#L125

**Comment by javierarce** [comment]
Weird, the default image is exported but a custom one is not :| 

![export_image](https://cloud.githubusercontent.com/assets/4933/9403373/cce96d62-47e6-11e5-85d4-043c008bb468.png)

**Comment by javierarce** [comment]
Ok, it seems that the canvas export is not rendering images that are in a different domain.

I uploaded an image to a dropbox public folder and didn't work. I then moved it to our assets folder and it was correctly rendered.

**Comment by javisantana** [comment]
I created a proxy for that, take a look at html2canvas config: https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/common/dialogs/static_image/export_image_result_view.js#L114

It should be using that proxy that avoids the CORS problem

**Comment by javierarce** [comment]
Oh, ok, it's giving a routing error.

**Comment by javisantana** [comment]
oh wait, did I merge it?

**Comment by javisantana** [comment]
Oh forgot to push the routes.rb I think https://github.com/CartoDB/cartodb/commit/381f3ecb4ca93052c861fde0984b61e5f5a8d11b

**Comment by javierarce** [comment]
I'm not sure, maybe it was my fault. Should it be here? https://github.com/CartoDB/cartodb/blob/export_image_revamp/config/routes.rb

**Comment by javisantana** [comment]
no, it was my fault, could you add the controller routes.rb to fix this?

**Comment by javisantana** [comment]
better @gfiorav
