### ISSUE TITLE
"No rows geocoded" reported after georeferencing points from lat/lon columns

### ISSUE THREAD

**Issue by chriswhong** [CartoDB/cartodb#5163]
It shows the little modal with "no rows geocoded", but the_geom is indeed populated with points.

**Comment by viddo** [comment]
Could you share the dataset used, so we can reproduce this?

**Comment by iriberri** [comment]
Or even the account name/dataset name so that we're able to check the geocoding logs :-)

**Comment by chriswhong** [comment]
This demo was done on my team account, 'chriswhong'

**Comment by chriswhong** [comment]
Dataset used was NYC taxi data, so the lat and Lon columns were not picked
up by the importer.  Will share the file with you via email.

**Comment by chriswhong** [comment]
Sample data is attached

**Comment by iriberri** [comment]
... nope? :-)

**Comment by iriberri** [comment]
Ok, this seems to happen for any process, it doesn't mind which data you have. Any lat/long geocoding process is returning that output for me @viddo.

![image](https://cloud.githubusercontent.com/assets/1730320/9469022/138b3f14-4b45-11e5-8593-07a04127f236.png)

**Comment by xavijam** [comment]
My proposal:
- All rows were geocoded, or just the_geom is set.
- A results window is not needed.

<img width="973" alt="screen shot 2015-08-25 at 18 14 22" src="https://cloud.githubusercontent.com/assets/132146/9472400/58357fac-4b55-11e5-969d-19a729abf217.png">

**Comment by iriberri** [comment]
Sorry to bug you with this again, but how's error management done know? I just geocoded this way a point with latitude = 229, which is not valid.

![image](https://cloud.githubusercontent.com/assets/1730320/9492853/8c5be05e-4bfb-11e5-844d-0a63ded5ce50.png)

**Comment by xavijam** [comment]
It works as it used to. The thing is there is no API behind this task, it only set the latitude and longitude you provide as the_geom. So:

1. There is no feedback if any row does not have the correct latitude/longitude.
2. There is no feedback if all rows are set correctly either.
