### ISSUE TITLE
"Export Image" downloaded file has generic name

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#5172]
It would be nice for the downloaded image to have a sensible name like "#{table_name} - #{current_time}.png".

**Comment by javierarce** [comment]
I was unsure about this change because we were offering to download a datastream (and by default it doesn't have a name), but it turns out there's a `download` property for the links we could maybe use:

> Can be used with blob: URLs and data: URLs, to make it easy for users to download content that is generated programmatically using JavaScript (e.g. a picture created using an online drawing Web app).

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#Attributes

**Comment by gfiorav** [comment]
I'm assigning this to you @javierarce since I'm out of time :smile: 

The state I leave it in is: Tests passing so CR needed

Thanks!

**Comment by saleiva** [comment]
Also, the button should take you to the image, but the link should download it.

**Comment by javierarce** [comment]
:ok_hand:, we didn't changed that.

I reviewed @gfiorav's work and also added the name of the file in the dialog:

![screen shot 2015-09-02 at 18 26 38](https://cloud.githubusercontent.com/assets/4933/9637265/250c8692-51a0-11e5-879a-182e7dff9460.png)

I'll deploy this tomorrow.
