### ISSUE TITLE
Background polling element in table view blocks scrolling after appearing

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#5175]
**Steps**:

* Import a table long enough so that scrolling is possible. [Sample link here](https://gist.githubusercontent.com/iriberri/61e5f94f7d39e3f15a33/raw/4536ee28c772209f5a5843a53906d3ddcb5bb802/example.csv)
* Georeference by city names, for example. Not specific options are needed.
* Once the process finishes (or meanwhile), the table is no longer scrollable. Closing the small window with the geocoding result doesn't enable scrolling neither. Open and closing the export modal window seems to help.

It's required to refresh the page to scroll the table view each time one of these polling windows appear. I think it happens also with the Pecan message if I'm not wrong.

cc @xavijam

**Comment by xavijam** [comment]
cc @viddo

**Comment by viddo** [comment]
It's because of the georeference modal, it's hidden (instead of closed), which has the unwanted side-effect of leaving `<body class="is-inDialog">` in the body (which is used to control the scrolling inside the fixed modal window). Easy to fix, I'll send a PR in a little bit…
