### ISSUE TITLE
Update Maps/Edit menu for consistency

### ISSUE THREAD

**Issue by csobier** [CartoDB/cartodb#5178]
Minor enhancement for consistency. 

 - Add the 'Change Privacy' option to the Edit menu for a selected map
 - Add the 'Duplicate Map' option to the dashboard shortcuts for a selected map

**Note:** The Change Privacy option is available from the dashboard shortcuts when a map is selected from the Maps dashboard. This is not consistent with how the options appear compared to the Datasets dashboard.  Is this by design?  If not, fix for consistency (not that doc will need to be reflected if changed).

See example screen capture for Maps dashboard shortcuts and Edit menu:
![image](https://cloud.githubusercontent.com/assets/13319925/9409808/e66da984-47ea-11e5-83b2-34d94782fd93.png)

Note the difference for the Datasets dashboard shortcuts and Edit menu:
![image](https://cloud.githubusercontent.com/assets/13319925/9409875/56fa83de-47eb-11e5-91ad-9065aa3b3e0d.png)

**Comment by saleiva** [comment]
Sure thing, good catch. There is already a ticket for the duplicate thingy. But adding this to a milestone to prioritize. Thanks!
