### ISSUE TITLE
Clicking on the public dataset icon generates a tooltip that doesn't get hidden

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#5179]
1. Go to the Data Library (or to the dashboard, if you imported a dataset from the library)
2. Put the cursor over the book icon.

A tooltip appears, but it won't get hidden after clicking outside or moving the mouse.

![screen shot 2015-08-21 at 16 29 59](https://cloud.githubusercontent.com/assets/4933/9410688/d826dea4-4821-11e5-9379-eae8e3e17908.png)

**Comment by viddo** [comment]
had a similar issue on the private dashboard, where the view didn't call `this.clearSubViews()` on the render call. Same issue?

**Comment by javierarce** [comment]
It looks it could be the same problem, yes, but I haven't had a look yet.
