### ISSUE TITLE
Share maps with groups backend

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#5185]

**Comment by juanignaciosl** [comment]
Dataset support for groups also covers maps requirements, a map can be granted with permission API, and it's listed in group members dashboard, who can open it as well. cc @viddo

**Comment by viddo** [comment]
Does this mean that I should change scope of #5184 to include share-with-maps-too again?

**Comment by juanignaciosl** [comment]
Maybe it's worth a try. If it doesn't mean more work on your side we can probably get this "for free". If it's more work for you we can make it incrementally.

**Comment by viddo** [comment]
Okie doki, should not be any extra work, I perceived it as it was a restriction in the backend. :+1:

**Comment by juanignaciosl** [comment]
That was my guess, but after some tests I think it should work straight out of the box.
