### ISSUE TITLE
Add subdomainless checks to diagnosis page

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#5186]
Subdomainless URL support configuration is tricky to check, adding it to the diagnosis page would help support.

**Comment by Kartones** [comment]
I think it'll be enough providing:
- Sample editor call (e.g. your maps page)
- Sample REST APIs call (e.g. your visualizations listing)
- Sample SQL API call (e.g. simple SELECT, like at your account, API Keys)
- Sample Tiler API call (e.g. fake tile request) <- @rochoa do we have any "ping" url at the tiler so we could place a URL that can be navigated to confirm it works fine?

**Comment by rochoa** [comment]
About Windshaft-cartodb: *health* endpoints don't require a user, to the path is the same no matter if it's host or subdomainless:
 - `http://{user}.localhost.lan:8181/` => `http://localhost:8181/`
 - `http://{user}.localhost.lan:8181/health` => `http://localhost:8181/health`

**Comment by Kartones** [comment]
Yes but I want to list them so people can provide as much info as possible when they have an issue, and I thought about having clicklable urls so they can realize "they just forgot to launch the tiler" and similar mistakes

**Comment by rochoa** [comment]
I wouldn't rely on the user having to interact, understand, and report things manually, then I see no sense to have a diagnosis page if you have to do all that by yourself.

**Comment by Kartones** [comment]
Then we can do an ajax call to query those endpoints (if Ruby doesn't already, I don't remember without taking a look at the code)... but was just an idea to "teach" users which urls they have. It sounds stupid let's just forget about it and I'll add only the two Ruby related ones, which can give more headaches.

**Comment by rochoa** [comment]
Don't misunderstand me, I'm ok on adding new checks for subdomainless, I'm
not OK with delegating the check to the user.

On Mon, Aug 24, 2015 at 11:42 AM, Kartones <notifications@github.com> wrote:

> Then we can do an ajax call to query those endpoints (if Ruby doesn't
> already, I don't remember without taking a look at the code)... but was
> just an idea to "teach" users which urls they have. It sounds stupid let's
> just forget about it and I'll add only the two Ruby related ones, which can
> give more headaches.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/5186#issuecomment-134114121>.
>



-- 
Raul Ochoa
rochoa@cartodb.com

**Comment by juanignaciosl** [comment]
I've already added requests from the backend in order to keep things simple for diagnosis page. Diagnosis controller could send the requests.
