### ISSUE TITLE
Fix background polling title when an analysis and an import are present in the element

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#5196]
![screen shot 2015-08-24 at 14 21 02](https://cloud.githubusercontent.com/assets/132146/9439907/749d3f12-4a6b-11e5-84f4-e04139f75721.png)

**Comment by javierarce** [comment]
What does "review" mean?

**Comment by xavijam** [comment]
Fix? :D. Connecting analyzing dataset... doesn't sound so good.

**Comment by javierarce** [comment]
Haha, sorry, I read to fast and missed the key word "table" :shame:

**Comment by xavijam** [comment]
:dancer:
