### ISSUE TITLE
[Suggestion] Add legends to export functionality

### ISSUE THREAD

**Issue by marianoju** [CartoDB/cartodb#5206]
As visible in this screenshot this map displays one absolute value by bubble size (as with layer wizard: bubble) and one relative value by color (as with layer wizard: chloropleth): 

![screenshot from 2015-08-24 17 57 01](https://cloud.githubusercontent.com/assets/6254428/9445063/70e3cc82-4a8a-11e5-8108-3655ecf00b8b.png) 

The export function however offers no option to include this legend: 
![export function no legend](https://cloud.githubusercontent.com/assets/6254428/9445203/2a85cb86-4a8b-11e5-8438-36353b2c0ef6.png)

The exported image displays no legend: 
![ejd3sgdl](https://cloud.githubusercontent.com/assets/6254428/9445256/7c886d44-4a8b-11e5-99e9-9105d01f3c95.png)

**Comment by iriberri** [comment]
Hi Mariano! I think we coincided at GIS SE too :-) Unfortunately this is the expected behaviour right now. In the last weeks we've added some changes in the feature and now overlays can be exported (which wasn't possible before neither) but legends are still out of the imported image. We'll continue improving the feature.

**Comment by marianoju** [comment]
I would very much welcome that. It is a key feature as is a scale. A map without a legend is poor practice and, in many cases, pointless.

**Comment by xavijam** [comment]
@javisantana @javierarce limitations with CORS won't let load external images, any advise?

<img width="308" alt="screen shot 2015-10-13 at 20 41 58" src="https://cloud.githubusercontent.com/assets/132146/10464832/f92cc7e6-71eb-11e5-8528-0b9b3cc18691.png">
<img width="741" alt="screen shot 2015-10-13 at 20 44 24" src="https://cloud.githubusercontent.com/assets/132146/10464833/f92d6980-71eb-11e5-9bdd-153b36f3d279.png">

**Comment by javisantana** [comment]
we have a image proxy for that, html2canvas supports it: https://github.com/CartoDB/cartodb/blob/a553b23670d008663ef18dd5e325e8d396d5f632/lib/assets/javascripts/cartodb/common/dialogs/static_image/export_image_result_view.js#L142

**Comment by javierarce** [comment]
It seems to be some problems with the proxy. I'm going to be working on that here: https://github.com/CartoDB/cartodb/issues/5935

**Comment by xavijam** [comment]
Changes done in issue-5206 branch
