### ISSUE TITLE
Add stats to measure performance of cartodbfy

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#5208]
What I think we need:
- [x] `import_time` (already present)
- [x] `total_size` (already present but within `file_stats` in json sent to metrics)
- [x] `cartodbfy_time`: to be added
- [x] `import_throughput = (total_size / import_time)` (derived, not present)
- [x] `cartodbfy_throughtput = (total_size / cartodbfy_time)` (derived)
- [x] `cartodbfy_import_ratio = (cartodbfy_time / import_time)`

After discussion with @rochoa and for simplicity, I'd add the new metrics, including the derived ones, to the json payload here:

https://github.com/CartoDB/cartodb/blob/master/app/models/data_import.rb#L736-L761

cc/ @luisbosque do you see any problem with that?

**Comment by luisbosque** [comment]
No problem at all. The more stats, the better :dancer:

**Comment by rafatower** [comment]
already there... preparing the dashboards. :smile:
