### ISSUE TITLE
Set a user agent for URL downloader different than Typhoeus'

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#5218]
It seems that Typhoeus UA is regularly blocked by some sources -- today we found a URL of a customer in which their server was blocking the request due to this UA.

Would it make sense to assign a different one?

cc @ethervoid

**Comment by ethervoid** [comment]
What do you think we should put here (just to reflect all the opinions)

// @Kartones @juanignaciosl @lbosque

**Comment by Kartones** [comment]
Firefox one + CartoDB.

Like `User Agent: Mozilla/5.0 (CartoDB) Gecko/20100101 Firefox/40.0`

**Comment by juanignaciosl** [comment]
:+1:
