### ISSUE TITLE
Make a list of datasets and maps available in the user profile feed

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#5222]
For the page created in https://github.com/CartoDB/cartodb/issues/5220 we need an object that contains the maps and datasets of a given user (see `User Profile Feed` page in the design file) ordered by updated_at date (newest on top). 

Since we are going to have an infinite scroll pagination, we'll also need an endpoint to ask for a page.

![screen shot 2015-08-25 at 16 51 40](https://cloud.githubusercontent.com/assets/4933/9469844/76928bea-4b49-11e5-857c-9fc505f6c57e.png)

**Comment by ethervoid** [comment]
You have to query using the visualizations API:

```http://user_to_query.cartodb.com/api/v1/viz?types=table,derived&page=1&per_page=16&privacy=public&order=updated_at```

**Comment by javierarce** [comment]
I've made a couple of tests and the `privacy` param doesn't seem to work. 

I requested a list of tables and maps of my own account and set the privacy param to `public` and the endpoint returned me `linked` datasets. If I use `link` I get `password` tables as well.

**Comment by ethervoid** [comment]
Are you using an api_key? If you don't use an api_key we could remove the `privacy` param

**Comment by javierarce** [comment]
No, I didn't use the query but I still got private items.
