### ISSUE TITLE
Write the query to search for users, datasets and maps

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#5224]
We need to query the Explore API table to search for users, datasets and maps. The query should retrieve the necessary information in order to render the different cards (and the result pages). 

A different smaller version of the query would be used to feed the dropdown.

**Comment by javierarce** [comment]
*Users*: 
> SELECT user_username,
sum(case when visualization_type = 'derived' then 1 end) as derived,
sum(case when visualization_type = 'table' then 1 end) as table       
FROM visualizations WHERE user_username ILIKE 'javier%25' 
GROUP BY user_username

*Maps & datasets*:
> SELECT visualization_type, visualization_title 
FROM visualizations 
WHERE visualization_title ILIKE 'name%25'
ORDER BY visualization_title

**Comment by javierarce** [comment]
The user query will return 

```json
{
  "rows": [
    {
      "user_username": "user_a",
      "maps": null,
      "tables": 2
    },
    {
      "user_username": "user_b",
      "maps": 2,
      "tables": 3
    },
    {
      "user_username": "user_c",
      "maps": 1,
      "tables": 1
    }
  ],
    "time": 0.234,
    "fields": {
      "user_username": {
        "type": "string"
      },
      "maps": {
        "type": "number"
      },
      "tables": {
        "type": "number"
      }
    },
    "total_rows": 3
  }
```

**Comment by javierarce** [comment]
cc @javisantana

**Comment by javisantana** [comment]
I think user_username and visualization_title have some text search indices and you could optimize the queries a lot. If you do that is like you get full scans in a table with more than half million records. I'd also add some limits, right?

cc @juanignaciosl @ethervoid

**Comment by ethervoid** [comment]
This columns `visualization_name,visualization_description,visualization_title` have full text index

**Comment by javierarce** [comment]
Yes, I'll add some limits. For example, for the dropdown we just need to show 3 elements per block. And the results views will be paginated so a limit will be needed.

**Comment by javisantana** [comment]
FYI, there is a nice postgres feature from 9.4 where you can do (not available in 9.3)

```
select 
 count(1) filter (where visualization_type = 'derived' ) as vis,
 count(1) filter (where visualization_type = 'table' ) as tables
...
```

**Comment by juanignaciosl** [comment]
Since username is just a lowercase word we could add a b-tree index if we're filtering with left-matching (`like 'juani%'`). More on this: http://www.postgresql.org/docs/9.0/static/indexes-types.html

Or use `text_pattern_ops` if we want both sides pattern matching (`ilike '%juan%'`). More on this: http://www.postgresql.org/docs/9.0/static/indexes-opclass.html

**Comment by javierarce** [comment]
Ok, @juanignaciosl, I removed the `ilike` from the users query.
Nice feature, @javisantana.
