### ISSUE TITLE
I received an "import finished" email that was announcing an error instead

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#5225]
![image](https://cloud.githubusercontent.com/assets/1730320/9470049/66ee3738-4b4a-11e5-96ee-cfdc198a67bd.png)

Import ID: `df9594dd-8c9e-4421-af5a-8c7b5e3f96fc`
Username: `geocoding-test`

I [took a look at the code](https://github.com/CartoDB/cartodb/blob/bee244aecd9c25c80563f3f38d79574b6cd3f47a/app/mailers/import_mailer.rb) and I'm not sure if this import has something special. I'm copying the DataImport (anonymised) data here in case it helps:

````
=> #<DataImport @values={:data_source=>"X", :data_type=>"url", 
:table_name=>nil, :state=>"failure", :success=>false, :logger=>"X", 
:updated_at=>2015-08-25 14:11:14 +0000, :created_at=>2015-08-25 14:06:20 +0000,
 :error_code=>6668, :queue_id=>nil, :tables_created_count=>nil, 
:table_names=>nil, :append=>false, :migrate_table=>nil, 
:table_copy=>nil, :from_query=>nil, :synchronization_id=>nil, :id=>"X", 
:table_id=>nil, :user_id=>"X", :service_name=>"public_url", :service_item_id=>"X",
 :stats=>"[{\"type\":\".shp\",\"size\":47221596,\"file_rows\":1686482,
\"imported_rows\":1686482,\"error_percent\":0.0,\"fallback_executed\":null}]", 
:type_guessing=>true, :quoted_fields_guessing=>true, :content_guessing=>true,
 :server=>"X", :host=>"X", :resque_ppid=>X, :upload_host=>"X",
 :create_visualization=>false, :visualization_id=>nil, 
:user_defined_limits=>"{\"twitter_credits_limit\":0}", :import_extra_options=>nil, 
:original_url=>"/X", :privacy=>nil}>
````

**Comment by iriberri** [comment]
By the way, don't know if this is valid but:

````
DataImport['df9594dd-8c9e-4421-af5a-8c7b5e3f96fc'].errors                                                                
=> {}
````

**Comment by ethervoid** [comment]
I think is a correct response:

`irb(main):002:0> d.state`
`=> "failure"`
`irb(main):003:0> d.errors`
`=> {}`
`irb(main):004:0> d.get_error_text`
`=> {:title=>"Too many table rows", :what_about=>"The resulting table would contain too many rows. Contact our support team at <a href='mailto:support@cartodb.com?subject=Dataset%20too%20many%20table%20rows%20import%20error'>support@cartodb.com</a>.", :source=>"user"}`

**Comment by iriberri** [comment]
But... does it make sense that the subject says that my import is finished (which to me implies a positive thing) and then inside I see the error? According to the code, the subject expected for errors is "There was some error while importing your datasets", which would make more sense.
