### ISSUE TITLE
Filter pane filters duplicate and persist

### ISSUE THREAD

**Issue by andrewbt** [CartoDB/cartodb#5226]
cc @xavijam @javierarce this is what I reported in technology channel last night.

This happens on both tables and [multilayer] visualizations.

Steps to Reproduce Bug:

1. Open a table or visualization in CartoDB Editor, Data View
2. Open the sidebar pane
3. Select filters
4. Choose a column to filter by with the drop down. (no need to actually apply options for the filter but you can)
5. Close the sidebar pane
6. Re-open the sidebar pane
7. Note that the column filter you chose in step 4 has duplicated itself in the filter pane at least 3 times. I _think_ all three of these are active/working filter UIs, but once you click the X to close one, the other two will persist and the "Start filtering your data by selecting a column to filter by" UI will be back up and overlayed on top of them.

Chrome browser version 44. No errors in the JS console that I can see.

**Comment by ztephm** [comment]
S/B 8203822

Tested in latest versions of Chrome, IE & Firefox on Windows 7 & Windows 8.1 (VirtualBox)

Happens when we close panel by clicking on layer's number. Doesn't happen if we close via clicking on Filters button.

**Comment by andrewbt** [comment]
@saleiva this is a bug that came up in a current Sales conversation. Could we easily prioritize this?
