### ISSUE TITLE
Feature request: provide feedback about current progress of geocoding to user

### ISSUE THREAD

**Issue by andrewbt** [CartoDB/cartodb#5228]
From an email:

"It would be great to see some sort of "counter" feedback in the CartoDb interface, when I choose to manually geocode. (An updating number of "successful" and "failed" geocodes for the user to see... On the failed ones, it might be nice to flash the line number that failed, or send that to some sort of log...  As you know, I was popping open the JS console in the browser to monitor progress through my file."

I think the "cartodb_georef_status" boolean column we add could already fulfill the "log" request, but maybe there is a better way.

**Comment by saleiva** [comment]
duplicated!
