### ISSUE TITLE
Dashboard link generation

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#5250]
Extracted from #5184.

In the example I’ll speak about, “central-org-b-1” user has shared “untitled_table_3” with a group.

“central-org-b-3” user belongs to that group, he can see the table at “shared with you” list (after CartoDB/cartodb#5249), and he can load the table view with the right link: http://central-org-b.localhost.lan:3000/u/central-org-b-3/tables/central-org-b-1.untitled_table_3.

Nevertheless the “shared with you” dashboard list has a wrong link: http://central-org-b.localhost.lan:3000/u/central-org-b-1/tables/central-org-b-1.untitled_table_3

As you see, the user_domain of the link is table owner username instead of current user username. This is because client url generation needs to support groups.

After talking to @viddo we think that link might be better generated server-side.

cc @Kartones

**Comment by Kartones** [comment]
To be sincere I don't remember, I know I exposed certain permission properties in the visualization items JSON, like `visualizations[0].table.name`, `visualizations[0].permission.owner.url`,`visualizations[0].permission.owner.username`, etc.

I am pretty sure we're not generating the url serverside as what comes in the XHR request is all we have, so probably JS is building the url using either `visualizations[0].table.name` or something similar.

Let me know if that helps

**Comment by juanignaciosl** [comment]
We know for certain that currently those links are generated client side. We doubt about moving it server side or not. In order to generate it client side we should send user groups within json user data and add support for groups at permission JS model. It's not a tough problem, but it _feels_ like we're duplicating the logic in both sides.

cc @javisantana

**Comment by Kartones** [comment]
I'd avoid duplicating logic as historically (since MU) it has only given headaches but is not my feature nor my call to make, as might be more work for FE. But +1 from me to having the logic only at Rails (where lives the MVC so where it should go IMHO).

**Comment by javisantana** [comment]
up to you, makes sense to generate in rails and send it to frontend

**Comment by viddo** [comment]
ATM we do a bunch of checks to decide what URL to generate (based on current user's permissions). The failing case @juanignaciosl describes is most likely because the permission ACL don't handle the new group type as expected. 

+1 to move this client-side because it would help a lot to remove complexity on the client-side code :+1:

**Comment by viddo** [comment]
edited my previous post, I meant to write _"move this server-side…"_ ofc

**Comment by juanignaciosl** [comment]
Merged into #4924 branch.
