### ISSUE TITLE
Create asset for maps without basemap with the new map card dimensions

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#5254]
Current map cards have a `300x170` asset that indicate the map has no basemap. We'd need a bigger  asset with the new dimensions (`300x220`).

![default-map-bkg](https://cloud.githubusercontent.com/assets/4933/9498671/428597a2-4c1b-11e5-91d2-a7f4cb414024.png)

**Comment by carlostallon** [comment]
Sure

**Comment by carlostallon** [comment]
![isobaras4](https://cloud.githubusercontent.com/assets/1712650/9519264/7e922a4c-4cbd-11e5-9a92-505a423a6aec.png)
![isobaras2](https://cloud.githubusercontent.com/assets/1712650/9519265/7e9cda96-4cbd-11e5-9c94-0cb2c8ed5884.png)
![isobaras3](https://cloud.githubusercontent.com/assets/1712650/9519266/7e9f68d8-4cbd-11e5-93c5-dba22f570123.png)
![isobaras](https://cloud.githubusercontent.com/assets/1712650/9519267/7ea78478-4cbd-11e5-9fc0-45899c7e53b9.png)

**Comment by javierarce** [comment]
Thanks!
