### ISSUE TITLE
API Call and Download buttons not working on public datasets

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/cartodb#5260]
When I click on the API Call or Download buttons on [this public data page](https://team.cartodb.com/u/eschbacher/tables/nyc_bikelanes/public), I only get the # added to the URL with no action happening (no modals pop up, no data downloaded, etc.)

I get the same behavior on [other public data pages](https://team.cartodb.com/u/andrew/tables/tesla_locations/public). I've tried Chrome and Safari -- same thing. @auremoser experienced the same problems.

**Comment by auremoser** [comment]
+1

**Comment by viddo** [comment]
:bow: thx for reporting, should be fixed now
