### ISSUE TITLE
Add new view for the Explore page

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#5283]
We need to have a view for the new Explore page under the `/explore` path.

**Comment by ethervoid** [comment]
This view where should be? in the editor? if you come here from `cartodb.com` its going and `nginx` redirection to a public endpoint in the editor?

**Comment by ethervoid** [comment]
You have it https://github.com/CartoDB/cartodb/pull/5256/files#diff-21497849d8f00507c9c8dcaf6288b136R29
