### ISSUE TITLE
In the user creation there is a missing method

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/cartodb#5294]
When te process fail, try to reach a method called `fail_user_creation` but it seems that don't exists.

https://github.com/CartoDB/cartodb/blob/master/app/models/carto/user_creation.rb#L154

**Comment by juanignaciosl** [comment]
It exists, it's not a method but a [state_machine](https://github.com/pluginaweek/state_machine) event that [triggers a transition](https://github.com/CartoDB/cartodb/blob/master/app/models/carto/user_creation.rb#L53). Has it triggered an error or something?

**Comment by ethervoid** [comment]
I've been adding a new transition for the common load and there were two errors:

* One the rescue => e should be rescue Exception => e
* When I have an error, I get no_method `fail_user_creation` error (before I change to rescue Exception => e)

**Comment by juanignaciosl** [comment]
- Why "One the rescue => e should be rescue Exception => e"? [Rescuing Exception is dangerous (search for "Avoid rescuing the Exception class")](https://github.com/Vizzuality/ruby-style-guide).
- state_machine performs some metaprogramming on the model, maybe it's failing before that method is created (but I'm just guessing, I don't know its internals). I have faced some similar issues in the past trying to add Rails validations. If you give me more context (the whole code) I might take a look.

**Comment by ethervoid** [comment]
For the `fail_user_creation` I've added the load_common_data method, and when it fails, the error appears. Put a `raise Exception.new('lala')` or whatever in the method and you'll see

**Comment by juanignaciosl** [comment]
Yes, but _you should never `raise Exception`_, it's explained in the guide. Not only a matter of style this time. Raise `StandardError` instead.
