### ISSUE TITLE
Add location field for the users

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#5298]
The new user profile pages include a new field to let users indicate their location.

![screen shot 2015-08-31 at 10 54 33](https://cloud.githubusercontent.com/assets/4933/9575273/9424d03a-4fce-11e5-96b6-dcd16e162de2.png)

**Comment by ethervoid** [comment]
We are going to need the field in the user profile screen too

**Comment by javierarce** [comment]
Yes, I added a ticket for that: https://github.com/CartoDB/cartodb-central/issues/785

**Comment by ethervoid** [comment]
Are we going to also add it for organizations?

**Comment by javierarce** [comment]
Oh, good question. I'd say yes… what do you think, @saleiva, @carlostallon?

**Comment by carlostallon** [comment]
I think so, too

**Comment by ethervoid** [comment]
One question, are we really going to need the location field in central?

**Comment by javierarce** [comment]
Yes, that's where the edit form is located.
