### ISSUE TITLE
Account pages fixes

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#5300]
- [x] Connect service error

<img width="723" alt="screen shot 2015-08-31 at 11 31 48" src="https://cloud.githubusercontent.com/assets/132146/9575948/e6f6906e-4fd3-11e5-8562-c12864cf061a.png">

---

- [x] Text when your account can't be deleted. Text should not be under the icon.

<img width="484" alt="screen shot 2015-08-31 at 11 32 14" src="https://cloud.githubusercontent.com/assets/132146/9575957/f8670fcc-4fd3-11e5-8b01-c11d6e517792.png">

---

- [x] Header user breadcrumb is incorrect. It should be ( :org-name / name / Whatever )

<img width="1007" alt="screen shot 2015-08-31 at 11 34 17" src="https://cloud.githubusercontent.com/assets/132146/9576025/6a95340c-4fd4-11e5-89f6-8cd253e2c1f9.png">

---

- [x] IMHO, space between content and footer should be bigger

<img width="1027" alt="screen shot 2015-08-31 at 11 36 24" src="https://cloud.githubusercontent.com/assets/132146/9576053/a3a3c75e-4fd4-11e5-8190-6364b56e4a19.png">

-- 

- [x] In the api keys page, there are lot of space between title and first element. If you check rest of the pages, that space is smaller.

<img width="658" alt="screen shot 2015-08-31 at 11 38 14" src="https://cloud.githubusercontent.com/assets/132146/9576088/ec5143f0-4fd4-11e5-8bf7-4c3117e1d511.png">

---

- [x]  Clean search button should not appear when there is no search defined... (Org page)

<img width="710" alt="screen shot 2015-08-31 at 11 40 34" src="https://cloud.githubusercontent.com/assets/132146/9576107/256d6ace-4fd5-11e5-9921-a20b0d684cdc.png">

---

- [x] Last user item should have a bottom border, shouldn't it? (? not sure, but i think so)

<img width="778" alt="screen shot 2015-08-31 at 11 41 16" src="https://cloud.githubusercontent.com/assets/132146/9576133/4e94ec7e-4fd5-11e5-91fc-d6a2df7d5532.png">

--- 

cc @saleiva

**Comment by xavijam** [comment]
And cc @viddo

**Comment by saleiva** [comment]
Added this other ticket as well -> https://github.com/CartoDB/cartodb/issues/5313

**Comment by MariaCheca** [comment]
About "Last user item should have a bottom border, shouldn't it? (? not sure, but i think so)": in the design mockups last child doesn't have border-bottom, in any case @saleiva confirm this please.

**Comment by saleiva** [comment]
nope!

**Comment by MariaCheca** [comment]
:+1:
