### ISSUE TITLE
Data Library Imports error

### ISSUE THREAD

**Issue by micagm** [CartoDB/cartodb#5317]
We are having problem importing datasets from the Data Library, we've tried a few none is working. Error: 7e2b532d-8e2f-4ce7-ba00-5af640f75766

**Comment by iriberri** [comment]
This https://github.com/CartoDB/cartodb/issues/5009 should have fixed it. Could you check?

**Comment by iriberri** [comment]
We have done a rollback on #5009, so this is not yet fixed, but you can follow the status there.
