### ISSUE TITLE
Create general asset for maps without basemap

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#5321]
We now have several sizes for the asset that appears when the static map didn't load. I think it's time to have a general asset so we don't need to generate a new one every time we produce a new card size.

Could you design a 600x600 asset similar to:

![default-map-bkg](https://cloud.githubusercontent.com/assets/4933/9498671/428597a2-4c1b-11e5-91d2-a7f4cb414024.png)

We'll be using the current small one for the small map cards and the new size for the rest.

**Comment by carlostallon** [comment]
sure, i will attach later

**Comment by javierarce** [comment]
bump

**Comment by carlostallon** [comment]
here it is ;)
![nobasemap](https://cloud.githubusercontent.com/assets/1712650/9747969/819f014c-5681-11e5-879c-abb8a7e15830.png)
