### ISSUE TITLE
Filtering by 'actor_objecttype', a string "&hellip;:" appears

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#5323]
### STR

1. Create a twitter dataset (I encourage to use and old one, it works too).
2. Filter by a column called 'actor_objecttype'.
3. Check image:
<img width="452" alt="screen shot 2015-09-01 at 14 56 11" src="https://cloud.githubusercontent.com/assets/132146/9604823/feb7a8e6-50b9-11e5-95da-0facdf9ed33f.png">

**Comment by xavijam** [comment]
Closed by [this one](https://github.com/CartoDB/cartodb/pull/5590) right?

**Comment by javierarce** [comment]
Yes
