### ISSUE TITLE
[Suggestion] Improve usability on Twitter slider for quota

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#5327]
Similarly to: https://github.com/CartoDB/cartodb/issues/5325

When setting up the Twitter datasource, the slider of the Twitter credits allows to select explicit percentages but it doesn't show how many credits are actually going to be used. It would be useful for the users to see the results of the calculation instead of just "16% of your 1.234.240 credits will be used". 

cc @saleiva @josecruz

**Comment by carlostallon** [comment]
![image](https://cloud.githubusercontent.com/assets/1712650/18200351/aed86f1a-7104-11e6-9d1f-713db24639ec.png)
