### ISSUE TITLE
Make attribution available in the metadata window for maps

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#5330]
So it can be exported as well.

**Comment by xavijam** [comment]
@alonsogarciapablo is working on https://github.com/CartoDB/cartodb/issues/5216. Is that ok?

**Comment by viddo** [comment]
So #5043 don't apply anymore? cc @ethervoid

**Comment by ethervoid** [comment]
We have the attributions in the datasets for every data source (retrieve using the layers), why we need to add attributions for the map?

**Comment by alonsogarciapablo** [comment]
Closing this for now.
