### ISSUE TITLE
Data library modal in Add Layer option is bad layered

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/cartodb#5332]
![captura de pantalla 2015-09-01 16 21 27 2](https://cloud.githubusercontent.com/assets/741240/9606798/d6454510-50c5-11e5-8fac-51ca61fb9395.png)

To reproduce:

* Create a user in an organization
* Share with him/her one dataset
* Enter in that user and create a map using that shared dataset
* Try to add a new layer and go to the `Data library` tab

**Comment by saleiva** [comment]
Is this happening in production? If so this is a hotfix

**Comment by ethervoid** [comment]
Yes is happening in production but is very contained (I've been checking how to reproduce the casa). It only affects to organization users, that have only shared datasets from other members, create a map with one of the shared datasets and try to add a new layer
