### ISSUE TITLE
Allow for extra params in GMaps API calls

### ISSUE THREAD

**Issue by danicarrion** [CartoDB/cartodb#5337]
Apart from client id, users sometimes need other params, like "channel".

My proposal is to add a new DB field that allows you to enter a comma-separated list of parameters.

**Comment by saleiva** [comment]
use cases?

**Comment by danicarrion** [comment]
Requested by a GME partner. For instance, with channel=whatever they can see how many times they are calling the js api (useful for quota checking, monitoring, etc.)
