### ISSUE TITLE
Fixes on account settings 

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#5339]
----
- [x] Green box color on acc type should be `#6BB72E`
<img width="332" alt="screen shot 2015-09-01 at 17 36 52" src="https://cloud.githubusercontent.com/assets/596509/9608827/9fa62528-50d0-11e5-89e1-b6de26557174.png">
----
- [x] No feedback when adding an unvalid domain to whitelisted domains:
![1](https://cloud.githubusercontent.com/assets/596509/9609062/e01fdfa8-50d1-11e5-8cbb-d4149955cde5.gif)
----
- [x] When clicking out of the box, the value overlaps the text:
![2](https://cloud.githubusercontent.com/assets/596509/9609117/2a70e4e4-50d2-11e5-96dc-499834446b56.gif)
----
- [x] Duplicated `FlashMessage` when saving changes on **org. admin users**:
<img width="958" alt="screen shot 2015-09-01 at 18 01 00" src="https://cloud.githubusercontent.com/assets/596509/9609359/902f0f94-50d3-11e5-8d02-5c5e32754310.png">
----
- [x] Text box width of `FormAccount-rowInfoText` should be `162px`
<img width="484" alt="screen shot 2015-09-01 at 16 56 07" src="https://cloud.githubusercontent.com/assets/596509/9609436/faa75d40-50d3-11e5-8577-ad709f243ea0.png">
----
- [x] User Quota needs to be a slider itself with a small input to introduce text (only number).
  - Designs:
![screen shot 2015-09-02 at 10 19 42](https://cloud.githubusercontent.com/assets/596509/9626331/1938c5ee-515d-11e5-82a5-3739c4bfe27b.png)
  - Staging:
![screen shot 2015-09-02 at 10 27 20](https://cloud.githubusercontent.com/assets/596509/9626348/3bc4d62a-515d-11e5-8473-67226a377f87.png)
----
- [x] Too long `Header-navigationBreadcrumbLink` username

![screen shot 2015-09-07 at 18 17 01](https://cloud.githubusercontent.com/assets/2141690/9720253/ad4ff422-558c-11e5-9186-fdc3fc634d8f.png)
----
- [x] Too long organization username in users list

![screen shot 2015-09-07 at 18 17 54](https://cloud.githubusercontent.com/assets/2141690/9720260/c9af4910-558c-11e5-9844-48a48af5bc25.png)

**Comment by MariaCheca** [comment]
User quota slider will remain as it is for now. Just in case @xavijam could you please confirm it?

**Comment by MariaCheca** [comment]
About the duplicated flash message in org. owner, those flashes appear when a user has assigned a custom notification, so it's not a bug just a feature :stuck_out_tongue:
