### ISSUE TITLE
Filter by tag is showing weird layers

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#5357]
Weird info next to "close search"

![image](https://cloud.githubusercontent.com/assets/1214201/9643079/ffc64f38-51bf-11e5-942c-b2eaa8a8d946.png)

**Comment by xavijam** [comment]
Problem related with this change -> https://github.com/CartoDB/cartodb/commit/8df7583c283421747affe7af8fa8ddd2478a2d3a#diff-9eb09f24fcd61780eb56874f60092483R437
