### ISSUE TITLE
Arrow is broken

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#5358]
Arrow is broken in tooltip 

![image](https://cloud.githubusercontent.com/assets/1214201/9643395/01aee3c6-51c2-11e5-9d40-1752db87d47a.png)

**Comment by javierarce** [comment]
That seem like an element (a bullet point?) overlapping the circle :/

**Comment by saleiva** [comment]
Is the arrow itself. I propose we remove it definitely

**Comment by javierarce** [comment]
Oh, true, I didn't notice that!
