### ISSUE TITLE
Elements disappearing when resizing crop box

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#5362]
When you resize the _crop viewport_ the elements disappears 
Explaining gif:
![3](https://cloud.githubusercontent.com/assets/596509/9656667/3be06bd2-523a-11e5-9e53-4184970e0dfc.gif)

**Comment by javierarce** [comment]
Here's my proposed solution:

![export_image](https://cloud.githubusercontent.com/assets/4933/10195124/64f36d5a-678c-11e5-90a2-cbd434eaec9e.gif)

The only problem I see is the text above: it's a bit difficult to read it.

Note: the cancel button won't be there anymore after we release the new export option.
