### ISSUE TITLE
Organization user quotas

### ISSUE THREAD

**Issue by MariaCheca** [CartoDB/cartodb#5363]
Related https://github.com/CartoDB/cartodb/issues/4884

![](https://cloud.githubusercontent.com/assets/932968/9083889/42ae6690-3b6e-11e5-89ca-87b885afe59d.png)

Possible new feature: add custom twitter credits to user (until now credits limit is the same for all users).

cc/ @saleiva @javisantana @Kartones @juanignaciosl

**Comment by saleiva** [comment]
Margin between the legend on the bar and the bar itself is incorrect

**Comment by MariaCheca** [comment]
That capture is from the design file, so maybe that should be revised for the implementation?

**Comment by saleiva** [comment]
Yep will modify in a minute

**Comment by iriberri** [comment]
Related:

https://github.com/CartoDB/cartodb/issues/5327
https://github.com/CartoDB/cartodb/issues/5325
