### ISSUE TITLE
Choropleth wizard ramp shows just two colors per ramp

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#5368]
How to reproduce it: 

1. Go to the choropleth wizard.
2. Select a ramp in the ramp selector.

![screen shot 2015-09-03 at 16 53 01](https://cloud.githubusercontent.com/assets/4933/9661689/1eef00ac-525c-11e5-8b68-4a0f933d8f39.png)

This happens in Chrome but not in Firefox or Safari.

**Comment by javierarce** [comment]
After some help from the team, we discovered it's related to the latest version of Chrome (45.0.2454.85)

**Comment by javierarce** [comment]
This browser bug could be related: https://code.google.com/p/chromium/issues/detail?id=527343&q=table&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified

**Comment by xavijam** [comment]
Fixed!
