### ISSUE TITLE
Retrieve the number of mapviews in the vis endpoint

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#5369]
The design of the user feed page shows the number of views for both tables and maps, but currently the visualization endpoint doesn't return this number (it also appears in the design for the revamped public map and dataset list.)
![screen shot 2015-09-03 at 17 05 21](https://cloud.githubusercontent.com/assets/4933/9662096/41ea8a20-525e-11e5-9de8-33229d4797d5.png)

@ethervoid told me that we might not want to make this number public. **Should we retrieve these counter or are they private**?

/cc @carlostallon @saleiva

**Comment by ethervoid** [comment]
Related https://github.com/CartoDB/cartodb-platform/issues/475

// @javisantana

**Comment by carlostallon** [comment]
Ouch, as we have it in the dashboard I thought we also have it here. But we can go without it IMO

**Comment by saleiva** [comment]
Hey, not sure about this. Tons of users use that info to measure traffic tho... @javisantana can we talk about this prior to do this?

**Comment by javisantana** [comment]
I think users use mapviews in private dashboard, not public ones, right?

**Comment by saleiva** [comment]
In dashboard we don't provide the total number, just the last days

**Comment by javisantana** [comment]
so why don't we show the total there (where it it's important fort them?)

**Comment by ethervoid** [comment]
Bump! We should talk about this :)

**Comment by javisantana** [comment]
for me we should not show the map views count in *public pages* but @andrewxhill was who raised the issue.
cc @saleiva

**Comment by andrewxhill** [comment]
I was mostly concerned about including it in an api where it could be easily monitored. Showing it by individual pages, while extractable, is less a concern. However, the "popularity metric" we are devising could be a better way. What if we had a score like, "Peak popularity" for each map?

**Comment by javisantana** [comment]
hey, we really need to take a decision about this, for the moment we will go showing the mapviews so we don't block the release

**Comment by javierarce** [comment]
Closing since the Explore page was released.
