### ISSUE TITLE
Sharing a dataset with a group for a second time doesn't work

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#5370]
If you grant a group permission to a table it works: you can check that a user of that group can access the table. Nevertheless, if you revoke it and grant it again, table won't appear.

**Comment by juanignaciosl** [comment]
Can't reproduce. @viddo , let me know if you find anything strange during development. Maybe there was a connection issue or I just granted something wrong and panicked instead of checking my instructions.

**Comment by viddo** [comment]
:+1:

**Comment by juanignaciosl** [comment]
This is really liked to be related to #5678, so closing.
