### ISSUE TITLE
Viz.json needs to be "invalidated" when the attributions of a layer are edited

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#5375]
We're currently including the custom dataset attributions in the viz.json. When a user edits the attribution of a dataset, we should invalidate the viz.json so that embedded maps pick up this change. Somehow, when the metadata of a dataset is modified, the viz.json of all the maps that use that dataset has to be "invalidated".

cc// @saleiva @javisantana -> please prioritize/assign this issue to the right person.

Branch: `update-cartodbjs`

**Comment by Kartones** [comment]
Like a charm also in local, both for public map and embed_map
