### ISSUE TITLE
_CDB_Add_Indexes is becoming a common Import Error

### ISSUE THREAD

**Issue by Hayleyr** [CartoDB/cartodb#5378]
ERROR: CDB(_CDB_Add_Indexes:23502:column "cartodb_id" contains null values):  

We haven't been seeing this error message, and now it is happening frequently (twice in one day). 

## Steps to reproduce: 

Import a dataset that has been exported from CartoDB from a "create table from query" in which the cartodb_id column contains null values.

Dataset will not import, import logs will show the ERROR: CDB(_CDB_Add_Indexes:23502:column "cartodb_id" contains null values):

**Comment by iriberri** [comment]
Some more spotted this morning

**Comment by rafatower** [comment]
this is fixed in extension repo. closing it
