### ISSUE TITLE
Great Britain Postal Codes Not Trimming Correctly, Geocoding Fails 

### ISSUE THREAD

**Issue by Hayleyr** [CartoDB/cartodb#5380]
## Steps to Reproduce 

Upload dataset containing GB postal codes 
All of the rows will not be geocoded. However, if you manually "trim" the inward part of the postal code the entire dataset will import. This is something that CartoDB should do automatically upon import.

**Comment by iriberri** [comment]
This goes in data-services. Moving :-)
