### ISSUE TITLE
New common import error in XLS files: "SSCS size is 0 but SSAT size is non-zero"

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#5384]
Hey there,

In the last week I've seen a lot of errors for Excel files with the message:

````
grep -v "WARNING \*\*\* OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero" | grep -v "\*\*\* No CODEPAGE record, no encoding_override: will use 'ascii'" | /h
````

I'm aware that this could just mean that the file is somehow corrupt, but when trying to import the same files that the users had trouble with, they work without any problem in our end. In other terms: I'm not able to replicate the issue from my end.

Could we have added some issue with the new ogr2ogr changes?

@rafatower

**Comment by rafatower** [comment]
that's not an error message but just a log message that always appears in traces:

https://github.com/CartoDB/cartodb/blob/master/services/importer/lib/importer/excel2csv.rb#L14-L15
https://github.com/CartoDB/cartodb/blob/master/services/importer/lib/importer/excel2csv.rb#L69-L71

```
true: Converting XLSX to CSV
true: About to execute in2csv: in2csv /tmp/imports/20150928-22646-1dqa5kd/states.xlsx  | grep -v "WARNING \*\*\* OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero" | grep -v "\*\*\* No CODEPAGE record, no encoding_override: will use 'ascii'" | /home/ubuntu/www/production.cartodb.com/releases/20150928093042/lib/importer/misc/csv_remove_newlines.py > /tmp/imports/20150928-22646-1dqa5kd/states.csv
true: done executing in2csv.
```
