### ISSUE TITLE
It's not possible to edit the name of a layer under Firefox or IE

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#5390]
While fixing https://github.com/CartoDB/cartodb/issues/5373 I noticed that it's not possible to double click the name of the layer in order to edit it.

How to reproduce it:

0. Make sure you are under IE or Firefox.
1. Open the layer pane of a map.
2. Double click on the name of the layer.

#### Expected result

An input field should appear.

#### Actual result 

The pane is closed.

**Comment by iriberri** [comment]
Oh, I just found this. One user reported this last week but it was still in my task list to reproduce it. Glad it's already "diagnosed". :-)
