### ISSUE TITLE
Maps search bar displaces other elements

### ISSUE THREAD

**Issue by MariaCheca** [CartoDB/cartodb#5420]
When user clicks "Search" the form container displaces the rest of the elements in the bar.

![untitled](https://cloud.githubusercontent.com/assets/2141690/9719217/a2104760-5582-11e5-8c1d-3a427dc089b9.gif)

cc/ @matallo

**Comment by piensaenpixel** [comment]
duplicated https://github.com/CartoDB/cartodb/issues/5357

**Comment by MariaCheca** [comment]
:+1:
