### ISSUE TITLE
Define the query for the 'Map of the Moment'

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#5422]
We need to write an SQL query to show the 'Map of the Moment' in the new Explore section. This query will make use of the explore api.

![screen shot 2015-09-08 at 10 11 28](https://cloud.githubusercontent.com/assets/4933/9729744/d2ec9d4a-5611-11e5-8476-a800d9a3ba75.png)

The query only needs to return: the id (`visualization_id`) and name (`visualization_name`) of the visualization.

/cc @javisantana

**Comment by ohasselblad** [comment]
So these are popular maps across CartoDB? Kind of like trending topics in Twitter?

**Comment by javierarce** [comment]
Yes.

I'll make use of the query you pointed, so I'm closing this ticket.
