### ISSUE TITLE
Define a query to populate the feed of the Explore page

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#5423]
We need to write an SQL query to populate the feed in the new Explore section. This query will make use of the Explore API.

We need to be able to show visualizations and datasets. 

![screen shot 2015-09-08 at 10 14 50](https://cloud.githubusercontent.com/assets/4933/9729789/4560606e-5612-11e5-866e-59785214b7c5.png)

Related ticket: https://github.com/CartoDB/cartodb/issues/5422

/cc @javisantana

**Comment by ohasselblad** [comment]
+1
Should they be ordered by the last activity? Or will the query be configurable based on how the user chooses to sort the page?

**Comment by javierarce** [comment]
We'll order by number of likes, but also let the users choose mapviews and date.

**Comment by andrewxhill** [comment]
Hey guys, I love the design and concept. I have one comment though, we should leave datasets out of the feed for now. The reasons are multiple,

1. Very few people engage around datasets still, we should add them when we see engagement go up
2. We don't have independent metrics for datasets (number of downloads, likes, views, forks, etc) that could populate the dataset card
3. Nobody but free accounts create public datasets anymore. It is the curse of our current dashboard, if I upload a dataset it becomes private and part of a private visualization. If I turn it the visualization public the dataset doesn't become public. So, our feed is going to look sparser than it shoudl be for now. 
4. Without the metrics for datasets, they are going to be in the exact same order as visualzations. So if my visualization shows up in the feed, the very next thing in the feed would be all the pulblic datasets in my visualization. Meaning my avatar would appear 2-5 times in a row

I'd add datasets into the feed as a future enhancement

**Comment by ohasselblad** [comment]
@javierarce what would you like me to do based on @andrewxhill's comment :point_up: ?

**Comment by javisantana** [comment]
cc @saleiva ^^

**Comment by saleiva** [comment]
@andrewxhill for going faster, could we release to staging the complete version and see the datasets thing there?

**Comment by ohasselblad** [comment]
I'll throw this together.

**Comment by javierarce** [comment]
I'm closing this ticket now since the Explore page has been released, but feel free to reopen it or open a new one to discuss the inclusion/exclusion of the dataset.

**Comment by ohasselblad** [comment]
Yeah, I'd like to revisit our goals for the feed contents at some point soon.
