### ISSUE TITLE
Cropped number of datasets filtered

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#5434]
When filtering datasets by tags/category it shows a cropped number:
<img width="963" alt="screen shot 2015-09-08 at 17 32 35" src="https://cloud.githubusercontent.com/assets/596509/9739384/cbc5cbb6-564f-11e5-8e34-6f5414bd5b42.png">
<img width="696" alt="screen shot 2015-09-08 at 17 35 46" src="https://cloud.githubusercontent.com/assets/596509/9739459/16fd7598-5650-11e5-84e6-93d88993910e.png">

**Comment by xavijam** [comment]
Duplicated https://github.com/CartoDB/cartodb/issues/5357
