### ISSUE TITLE
Geocoding block quota computed incorrectly in the front

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#5435]
The attribute block price of a user is set in dollars (as far as I know). Nevertheless, [this code](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/common/dialogs/georeference/user_geocoding_model.js#L41) is trying to convert it from cents to dollars.

The ceil is provoking the value to be 1, so users are seeing:

![image](https://cloud.githubusercontent.com/assets/1730320/9739469/24e5488e-5650-11e5-9670-5b45d86bc749.png)

When the cost per a 1K geocoding block is 10$: https://cartodb.com/terms/#geocodings

**Comment by saleiva** [comment]
this is important, and should be easy to fix, right?

**Comment by iriberri** [comment]
I've done a quick search and a distinct(block_price) in the platform and it doesn't seem to be very consistent.

Anonymising a little bit:
```
 geocoding_block_price | count  
-----------------------+--------
                 10000 |      6
                     0 |    261
                       |      4
                  1000 |    297
                  2000 |      1
                  1500 | (a lot)
                    10 |      6
````

After investigating a bit it seems that the problem is in the user settings, and not in the code, as this should work in cents.

**Comment by saleiva** [comment]
so it's not a dev thing? good to hear. Confirm and I'll mail to sales

**Comment by iriberri** [comment]
I'd say so. Most of our users are using 1500, which is 15$, which is exactly what is stated here: https://cartodb.com/terms/#geocodings

I'm not sure if this is due to manual errors or to a bad default value for some specific plans, but in any case I don't think this is an issue to be treated in cartodb/cartodb anymore.

(By the way, I'm going to add some extra anonymization above, tell them to ask me specific details if needed, I can get them the lists).
