### ISSUE TITLE
Sync tables generating invalid_the_geom with valid geometry

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#5438]
ping @saleiva for who this goes to

Expected: Logs showing "successful" syncs will generate geometry from dataset's valid latitude column & longitude column values

Happening: Logs show "successful" sync but "invalid_the_geom" column is being generated.

Test: I imported user's original source dataset and it generated the_geom column & plotted properly.

Keeping datasets private but posting here so users can follow the issue, let me know if u want me to report in private repo tho.

Datasets are in: 
S/B 6554173 -> 6554520

Also happening here:
S/B 6516794

**Comment by Kartones** [comment]
Uhm... Assigning @rafatower because I think this relates to the issues he's finding with the latest SQL extension version (feel free to reassign if doesn't)

**Comment by iriberri** [comment]
Updated with the actual ID where the dataset lives

**Comment by iriberri** [comment]
The error that the dataset throws when importing is:  CDB(_CDB_Rewrite_Table:XX000:Input geometry has unknown (0) SRID)

But it has also several warnings on:

Warning 1: Value '.' of field file_name.Water Temperature? (degrees Celsius) parsed incompletely to real 0.

I suspect that as the table was synced before it doesn't crash directly, but now we can't know the SRID, this is just written as invalid the geom (with "valid values").

**Comment by rafatower** [comment]
I'll investigate this silent failure where the column is renamed:
```
   72            end
   73          rescue => e
   74            # if no SRID or invalid the_geom, we need to remove it from the table
   75            begin
   76              debugger
=> 77              @db_connection.run("ALTER TABLE #{@suggested_name} RENAME COLUMN the_geom TO invalid_the_geom")
   78              column_names.delete("the_geom")
   79            rescue => exception
   80            end
   81          end
   82        end
   83  
   84        @table_created = true
   85        rows_imported = @db_connection["SELECT count(*) as count from #{@suggested_name}"].first[:count]
   86  
   87        payload = OpenStruct.new({
   88                                :name => @suggested_name,
   89                                :rows_imported => rows_imported,
(rdb:1) e
#<NoMethodError: undefined method `err' for nil:NilClass>
(rdb:1) @runlog
```
