### ISSUE TITLE
[DESIGN] Add map attribution field for maps

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#546]
There are a couple of options here.

1. Include at the time a user adds a new basemap to their account

2. Include it in the Visualization "Share" menu

They both have clear values. Adding it to the basemap is easy/ one time solution per basemap. Adding it to the Share menu allows a lot more flexibility where they can actually attribute data in their data layers appropriately also.

If we do it #2 we could have free text input and also some auto generated ones (such as OSM) to make it quicker

**Comment by saleiva** [comment]
Added to the new editor. yay!
