### ISSUE TITLE
CartoDB Editor: Color Picker and Font Options

### ISSUE THREAD

**Issue by makella** [CartoDB/cartodb#5461]
## Color Picker
We need an enhanced color picker! Having more control over colors on the map and not always needing a HEX value(!).
__Concerns with the current one__:
 * The default palette is pretty limited
 * When the option for "Show more colors" is selected the behavior isn't consistent
    * Some times just clicking on a new color refreshes the map but other times it doesn't. If the color doesn't update automatically, you have to highlight the HEX value and hit Enter to get the new color. 
    * When the color picker is clicked too often, the map and selected color are out of sync: 
![screen shot 2015-09-09 at 10 53 59 am](https://cloud.githubusercontent.com/assets/1566273/9768588/d75cec74-56e1-11e5-8762-10eae8ff637f.png)  

### Suggestions
* __New Color Picker__: it would be a great enhancement to have the options for not only HEX but RGB, HSV, transparency, etc.  A really nice example [here](http://blog.uxpin.com/4852/new-uxpin-color-picker/):
![uxpin-color-picker-feature-4-modules-preview](https://cloud.githubusercontent.com/assets/1566273/9768924/1eb3562e-56e4-11e5-8787-2cdb2476a92e.png)  
* __Color Ramping__:  it is really nice to be able to ramp between colors and then assign those colors to values in your dataset especially when a color ramp you want is different or more complex than what's available in the defaults.
  * [This tool](http://www.zonums.com/online/color_ramp/) is a good example of ramping between single or even multiple hues at different steps.  This gives the user more options than the default ramps.  
  * It also minimizes the amount a user needs to leave CartoDB, figure something out somewhere else, and then come back.
* __Save Colors__: when working on a series of maps, with the same or very similar colors, it is extremely helpful to be able to save colors that can be used multiple times.  This is similar to declaring color variables in your CartoCSS. 
   * The example color picker above has a "Favourites" component.  
   * ArcMap adds any saved custom colors to the top of your color picker and you can hover over to see the name:  
![custom-color](https://cloud.githubusercontent.com/assets/1566273/9769371/049206ac-56e7-11e5-964a-f748bb44f7de.jpg)
* __No Color Option__: right now the only way to assign no color is setting opacity to 0, setting line width to 0, or defining `transparent` for a color in CartoCSS.  A No Color option would make this a lot easier and the CartoCSS could populate as `transparent`.  

## Fonts
* My first question: what fonts are available to use? 
* In the Editor, it is really difficult to see the complete names of fonts that are available because the full name gets cut-off in the drop-down, particularly for fonts with longer names.
![screen shot 2015-09-09 at 12 47 58 pm](https://cloud.githubusercontent.com/assets/1566273/9771503/db9a2128-56f3-11e5-84e5-7adcdbacbe4d.png)
* In the Editor drop-down, all of the fonts that can be used aren't listed.  For example, we have `Open Sans Regular` in the drop-down, but `Open Sans Italic` can be used if written out in CartoCSS.

### Suggestions
* __Evaluate font options:__ fonts make or break a map!
 * a good first step would be to evaluate what fonts we have available and come up with a good selection of both serif and sans serif options.  [This list](https://github.com/CartoDB/mapnik/tree/master/fonts/dejavu-fonts-ttf-2.34) doesn't seem complete given what I'm seeing in the Wizard.
  * if a bold, italic, semibold, regular, etc. options are available for a font, can that be added to the Wizard as a bold, italic button option and then populated in the CartoCSS?  
* __Standardize (to some degree) fonts for Elements and fonts for map labels__:
 * There is one set of fonts for "Elements" and another set for map labels.  There are common fonts, but not all fonts that are available for Elements are available for map labeling.
    * At a minimum, we should make sure that there is consistency between the two lists. 
* __New ways of presenting font options__:
 * If we implement a new color picker design maybe some of the UI concepts can be brought to fonts as well.
 * it is really helpful to have a list of fonts where you can see what they look like.  Since fonts can be used in the Wizard, in CartoCSS and in Elements, it would be useful to have a visual list somewhere in the Editor. 
  * In Mapbox Studio there is a list of supported fonts available to look at with each font style and weight listed beneath. To use a font, you simply copy and then paste into CartoCSS. Super helpful!  
![screen shot 2015-09-09 at 2 24 34 pm](https://cloud.githubusercontent.com/assets/1566273/9773380/19484300-56ff-11e5-8c2a-5d0160b9ac12.png)

### Other  
* I [agree with @ztephm first three points](https://github.com/CartoDB/cartodb-management/issues/4214) about the default font and halo styling.  A couple of thoughts here that I will elaborate on more in an issue specific to labeling. Our default (and really all suggested fonts) should:
 * have a good amount of space between each character
 * have a good amount of whitespace within each glyph (related to its x-height)
 * if there is enough spacing between characters and the character itself, a halo will not look as bad. We can also apply some default transparency to text halos so they are more inline with the labels on our basemaps.  
![screen shot 2015-09-09 at 2 10 37 pm](https://cloud.githubusercontent.com/assets/1566273/9773011/077b10be-56fd-11e5-870e-1a04d8132d3b.png)
* __When we support the latest version of CartoCSS__ there is a cool new property for halos (`text-halo-transform: translate();`) that can be used to offset halos so you get more of a drop-shadow effect than a halo effect.  
* If labels are being designed using CartoCSS and you want to try out a different font (because it isn't clear what's available for use) and you change the font in the Wizard, you lose your CartoCSS :(
- Do all of the fonts that we support support all characters?  Or if a user chooses a particular font do we need to ensure that we are adding a backup font that does support all characters?

**Comment by iriberri** [comment]
Related to the label fonts :-) https://github.com/CartoDB/cartodb/issues/5341

**Comment by makella** [comment]
147 color names available to use with CartoCSS: http://www.colors.commutercreative.com/grid/

**Comment by saleiva** [comment]
Lovely. Working on it. Ideas for the ramp editor?

**Comment by makella** [comment]
@saleiva let me think on the ramp editor more... will post some ideas. thanks!

**Comment by chubbuch** [comment]
Additional color ramps, a la [colorbrewer] (http://colorbrewer2.org/), would be great. Especially need more options for divergent color schemes. Even just reversed options of the current choices.
