### ISSUE TITLE
Fix form container display

### ISSUE THREAD

**Issue by MariaCheca** [CartoDB/cartodb#5462]
Delete `.FormAccount-Section` property `overflow: hidden`, it makes some of its children displaying half content.

cc/ @viddo

**Comment by viddo** [comment]
Also required for the `.is-selected`/`.is-selectable:hover` state (since that overflows the container on the sides, see: https://github.com/CartoDB/cartodb/commit/b387646be5deb8b428eb667769c423387a650b04

**Comment by MariaCheca** [comment]
Solved, see: https://github.com/CartoDB/cartodb/blob/master/app/assets/stylesheets/common/account_forms.css.scss#L10
