### ISSUE TITLE
register in geocoding log what geocoder is being used

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#5463]
We support many geocoders (here and gmaps so far), we should keep record of what is being used in a geocoding process.

cc @rafatower

**Comment by rafatower** [comment]
Related to https://github.com/CartoDB/cartodb/issues/6099

**Comment by rafatower** [comment]
https://github.com/CartoDB/cartodb/blob/master/services/table-geocoder/lib/table_geocoder_factory.rb#L41-L58

**Comment by rafatower** [comment]
this should be persisted:
- [ ] in database
- [ ] in logs

for later processing

**Comment by ethervoid** [comment]
We have to take into account the with the geocoder API this info is not stored
