### ISSUE TITLE
Error assigning as owner a user with non-cartodbfied tables

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#5477]
While fixing CartoDB/cartodb-platform#1072 we saw that users with tables that are not cartodbfied can't be set as organization owners. When a user is set as owner his tables are moved from `public` to his username schema with this code taken from `User`:

```
1661   def move_tables_to_schema(old_schema, new_schema)
1662     self.real_tables(old_schema).each do |t|
1663       self.in_database(as: :superuser) do |database|
1664         old_name = "#{old_schema}.#{t[:relname]}"
1665         new_name = "#{new_schema}.#{t[:relname]}"
1666         database.run(%Q{ SELECT cartodb._CDB_drop_triggers('#{old_name}'::REGCLASS) })
1667         database.run(%Q{ ALTER TABLE #{old_name} SET SCHEMA "#{new_schema}" })
1668         database.run(%Q{ SELECT cartodb._CDB_create_triggers('#{new_schema}'::TEXT, '#{new_name}'::REGCLASS) })
1669       end
1670     end
1671   end
```

[`cartodb._CDB_create_triggers` fails](https://github.com/CartoDB/cartodb-postgresql/blob/c12ae7f4a893eebecdcb09fe3f80698cb3adb6e6/scripts-available/CDB_CartodbfyTable.sql#L42) for tables not cartodbfied because of `Sequel::DatabaseError: PG::Error: ERROR:  column "the_geom" of relation "<table name>" does not exist`

Alternative fixes:
a) `move_tables_to_schema` should not run trigger lines (1666 and 1668 at previous code) for non-cartodbfied tables.
b) `_CDB_drop_triggers` and `_CDB_create_triggers` should not fail for non-cartodbfied tables.

cc @CartoDB/backend

**Comment by rafatower** [comment]
Those _CDB methods are not part of the public API of the extension, so I wouldn't go for (b)

**Comment by Kartones** [comment]
I'd go for a) too, as it is the logical solution IMHO.

Also /cc @zenitraM as this affects the UserMover :tm:

**Comment by javisantana** [comment]
@juanignaciosl hey, this ticket is blocker for sales, could we work on that?

**Comment by iriberri** [comment]
@yasharora73 please, keep updated here.

**Comment by juanignaciosl** [comment]
@javisantana I'd like to finish [what I'm doing now](https://github.com/issues?q=is%3Aissue+milestone%3ATorrelodones+sort%3Aupdated-desc+assignee%3Ajuanignaciosl+is%3Aopen) (invitations and other multiuser fixes/enhancements), but if this is blocker assign it to me as urgent and I'll switch to it.

**Comment by juanignaciosl** [comment]
@iriberri @yasharora73 this is being deployed right now, so assigning owners to organizations should be considered safe again in ~30 minutes. Next time you have _any_ problem around this please contact both @iriberri and me ASAP without retries or login into dashboard, since we've changed this to be safer and other side-effects might occur.

**Comment by yasharora73** [comment]
Thanks @juanignaciosl Much appreciated. I will keep you and @iriberri posted if it happens again!

**Comment by iriberri** [comment]
An extra explanation for non-product people: 

"without retries or **login into dashboard**" -> this is super important, because accessing to the dashboard is running a script to check that the data is there, and if it isn't, maps could be deleted. This process doesn't run until you access the dashboard.

**Comment by yasharora73** [comment]
Gotcha. So I have problems creating it the first time, I will inform you guys without taking any further steps.

**Comment by juanignaciosl** [comment]
@iriberri thanks for the clarification :-)

**Comment by juanignaciosl** [comment]
Reopened because a wrong revert has reverted this fix. @yasharora73 @iriberri , I'll close this when I fix it again, hopefully today or tomorrow :(
