### ISSUE TITLE
Redundant message at georeference modal makes it huge

### ISSUE THREAD

**Issue by Kartones** [CartoDB/cartodb#5481]
## Description

Upon entering the georeference window from a map with no data georeferenced yet, I see a yellow banner that looks redundant (I already know I have no data when I'm entering here), and that makes the modal so huge that you need to scroll just to fill the 3 "Street addresses" geocoding.

## Steps to reproduce
- Setup a browser window with height 768 or less (viewport height)
- Create new empty dataset
- Enter some rows
- Click on Georeference
- Select street addresses

![image](https://cloud.githubusercontent.com/assets/2085449/9811108/7ad84b0c-5875-11e5-87b8-0d421e4460a3.png)

It might be on purpose but it is really annoying to have to scroll to fill 3 fields...

**Comment by josecruz** [comment]
I've been showing different versions to Eduardo (just to know what he finds weird) and he liked way much more the 5s animation from orange to black on header (also design team likes this version).

The only thing I don't like is the massive text width. Maybe we could improve the copy. What do you think?
![no georeference data](https://cloud.githubusercontent.com/assets/596509/9880434/e6806854-5bcb-11e5-9de5-d671204628d9.png)

**Comment by saleiva** [comment]
I don't like, as we never show errors on the header of the modals...

**Comment by josecruz** [comment]
Okay so I suggest this 2nd option with a flashmessage close button:

![no georeference data copy 2](https://cloud.githubusercontent.com/assets/596509/9900440/1d4789b8-5c61-11e5-8471-709db17128af.png)
