### ISSUE TITLE
Legend label custom Simple and Pin icons not displaying well

### ISSUE THREAD

**Issue by MariaCheca** [CartoDB/cartodb#5486]
There are three icon sets for displaying with the legend labels, Simple, Pin and Maki. Maki works fine, but the first two doesnt.

That's because the icon image (set in the CSS as `background-image`) is bigger than the container. Adding a `background-repeat: no-repeat` property would be nice too to avoid concatenation of the image if it doesn't fit 100% the limits of the container.

![screen shot 2015-09-10 at 11 40 24](https://cloud.githubusercontent.com/assets/2141690/9785212/e0b05f0c-57b0-11e5-831b-6c1dce945350.png)

**Comment by xavijam** [comment]
Legends are gonna be redisigned and reimplemented, so closing it.
