### ISSUE TITLE
sync info overlaps ui features in multilayer map

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/cartodb#5496]
Steps to re-create:

+ Create a multilayer map with one layer a sync'd table, the other a static one
+ Change between layers to see the sync ui info overlap with some of the other editor info

<img width="537" alt="screen shot 2015-09-10 at 14 27 08" src="https://cloud.githubusercontent.com/assets/1041056/9839420/de0de7a4-5ab4-11e5-96bd-b90f41765d81.png">

**Comment by xavijam** [comment]
This is gonna change with new editor designs, so let me close it :).
