### ISSUE TITLE
Skip null street data rows at high resolution geocoding

### ISSUE THREAD

**Issue by Kartones** [CartoDB/cartodb#5497]
**UPDATE**: Info about the real issue down at the comments.

Really weird scenario, after creating a table from scratch, adding 2 new rows, setting the description of one to a real Madrid street and geocoding (Street geocoding, Street -> description field, City -> "Madrid", Country -> "Spain"), I got this:
![image](https://cloud.githubusercontent.com/assets/2085449/9844886/38cdb3ce-5ac7-11e5-818c-e3125ee92c98.png)
![image](https://cloud.githubusercontent.com/assets/2085449/9844898/46b53ebc-5ac7-11e5-8817-2bc8634b2095.png)

That null description point should have been skipped, but is also very curious that returned point is quite near to the other one.

PS: Assigning to you @iriberri because I don't know if you want to do any extra triaging before sending it to backend.

**Comment by iriberri** [comment]
If you set by hand in the geocoding settings "Madrid", and "Spain", all rows are going to include that, even the ones will null description.

At this moment we're not skipping null values, so the behaviour you're experiencing makes total sense according to the workflow -- you're just geocoding ", Madrid, Spain".

Probably we want to convert this issue into a "skip null data" in geocoding one.

**Comment by Kartones** [comment]
Ohh, then yes, beause makes no sense to get a random Madrid point if there's no street level info, right?

**Comment by Kartones** [comment]
@saleiva assign to whom it proceeds when it proceeds :stuck_out_tongue:

**Comment by iriberri** [comment]
Yes, I think it makes sense that if the first selector points to a column with empty information, that row is not taken into account. I think this was discussed some weeks ago and we thought it would be a good idea to save money.
