### ISSUE TITLE
Set white background to header avatar

### ISSUE THREAD

**Issue by MariaCheca** [CartoDB/cartodb#5500]
In order to avoid blank spaces in PNG or GIF images, we should add a white background to the container of the avatar shown on the header:

![screen shot 2015-09-14 at 15 41 59](https://cloud.githubusercontent.com/assets/2141690/9851421/d2557532-5af8-11e5-8a40-1efa0fce0dd1.png)

**Comment by xavijam** [comment]
@josecruz what do you think about this? I feel we shouldn't apply any background to it because it could break some logos, imagine a PNG with only a white color.

**Comment by josecruz** [comment]
I agree with Maria, it's weird to have no background avatars in a blue bg.

**Comment by MariaCheca** [comment]
In fact, I've changed my mind about it talking with @xavijam: what if the user wants those transparent pixels to be displayed? The appearance the user wants for its own account and public profile would pass through update an avatar with blank space, right? So maybe we are restricting that for the user setting that white background... If the avatar is more or less pretty is the user's decision :)

**Comment by josecruz** [comment]
It's not a good idea to let the user upload a transparent avatar because of the contrast with blue. Imagine a blue transparent Telefonica logo.

**Comment by xavijam** [comment]
Yeah, but take into account that in the public profile, that avatar, could look pretty nice (with transparent background).

**Comment by MariaCheca** [comment]
After discussing in person this issue, we'll update all the avatar containers with a white background.
