### ISSUE TITLE
Minor user account enhancements

### ISSUE THREAD

**Issue by MariaCheca** [CartoDB/cartodb#5507]
In order to have all the UI unified, I propose some changes for the user account:

- [ ] ~~Add `min-width: 3px;` to the used quota progress bar on the side menu, so even if the user has no quota used, there's always a minimum colored bar exposed.~~
- [x] Delete `min-width: 3px;` from the used quota progress bar on the side menu.
![screen shot 2015-09-14 at 17 59 16](https://cloud.githubusercontent.com/assets/2141690/9854712/7e4f5748-5b0a-11e5-968d-c07ab2058507.png)

- [x] Set `width: 260px` to the side menu bar to avoid leaps while the page is loading.
![screen shot 2015-09-14 at 18 01 37](https://cloud.githubusercontent.com/assets/2141690/9854752/ab57c068-5b0a-11e5-870c-7adc20394ec5.png)

- [x] Show only 2 decimals when displaying a float value for the quotas data and avoid a blank space between the value and the scale ("100MB" instead "100 MB"), as it is set in the header downmenu.
![screen shot 2015-09-14 at 18 04 27](https://cloud.githubusercontent.com/assets/2141690/9854819/10579b8c-5b0b-11e5-8024-d3f7d3da7eba.png)

cc/ @xavijam

**Comment by xavijam** [comment]
1. Not sure, @josecruz ?
2. ok
3. :+1:

**Comment by josecruz** [comment]
1. Agree with @xavijam. For me it doesn't makes sense to have 0bytes and show a small blue progress bar.

**Comment by MariaCheca** [comment]
1. Ok, so I just noticed that I actually changed that here: https://github.com/CartoDB/cartodb/commit/df2a469623f079e4fc5c2608f930a06a179661d7, so I'll rephrase the suggestion: delete `min-with: 3px;` for progress bar with 0 bytes consumed.
