### ISSUE TITLE
Add generated URL in marker image

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#5512]
In the dropdown should be lovely if we can copy the generated URL

![image](https://cloud.githubusercontent.com/assets/1214201/9857440/c2f5cd04-5b1a-11e5-80f4-00bda703b1ca.png)

cc/ @xavijam  @josecruz

**Comment by xavijam** [comment]
@josecruz @piensaenpixel what do you think if we add a new row with url in a input (getting rid of the copy this url flash button)

**Comment by xavijam** [comment]
Yep, it will happen in the new builder. Closing this one in the meantime :).
