### ISSUE TITLE
Column modifications not visible on a new empty dataset

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#5515]
Steps-to-reproduce:

1. Create a new empty dataset from dashboard
1. Add a new column
1. Rename a column

Actual Result:
- New column doesn't appear
- Renamed column still shows old name after rename

Expected result:
- New column to appear
- Renamed column to get new name

Reloading the browser makes things work. Seems to be related to the state of the new table.

cc @jmartinter

**Comment by jmartinter** [comment]
It might be significant: it only happened to me when using a organization account. While using my personal one, everything worked fine.

**Comment by viddo** [comment]
@javisantana @gfiorav This happened @jmartinter today again. While looking at I noticed that the column creation actually works, but the return table columns returns a cached result from the Varnish. Renaming the table provokes the SQL API to return the expected result (i.e. contain the recently created columns). 

I have not been able to reproduce this myself again but there's definitely some issue with the varnish cache and tables that is not working like it should, so it's not only the delete endpoint (as in #5516) that needs investigation.

**Comment by javisantana** [comment]
it's probably the same race condition

**Comment by rafatower** [comment]
I think we're having more of those "glitches", see S/B: 6661713

**Comment by viddo** [comment]
Reassigned since confirmed it's related to the Varnish issue that's already investigated in #5516, once that is fixed this should work properly.

**Comment by rafatower** [comment]
It is a problem with varnish invalidations that only affects organizations with a dash in the name:

t is the table and `t.varnish_key` is the key used for invalidation:
```ruby
irb(main):035:0> puts t.varnish_key
^cartodb_user_b3ab0740-9d0d-42bf-8899-90b8d63c5f14_db:(.*metrics-user\.test_bug_varnish.*)|(table)$
```

and this is the keys used to cache the queries from the frontend:
```
TxHeader     c X-Cache-Channel: cartodb_user_b3ab0740-9d0d-42bf-8899-90b8d63c5f14_db:"\"metrics-user\".test_bug_varnish"
```
Mind the quotes. I'm hotfixing this.

cc/ @rochoa @viddo @javisantana

**Comment by rafatower** [comment]
This works by adding a `.*` to the regexp:
```
CartoDB::Varnish.new.purge('^cartodb_user_b3ab0740-9d0d-42bf-8899-90b8d63c5f14_db:(.*metrics-user.*\.test_bug_varnish.*)|(table)$')
```

**Comment by rafatower** [comment]
Mm to have a more specific regexp, I need to match 2 characters: `\"'. I tried with just adding `"?` and it did not work. Really hating tricky quoting...

**Comment by rafatower** [comment]
This made the trick:
```
CartoDB::Varnish.new.purge '^cartodb_user_b3ab0740-9d0d-42bf-8899-90b8d63c5f14_db:(.*metrics-user(\\\")?\.test_bug_varnish.*)|(table)$'
```
