### ISSUE TITLE
'Organization over seats' email

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#5518]
Related to #5001, should we warn the organization owner if organization runs out of seats?

cc @andrewxhill @saleiva

**Comment by andrewxhill** [comment]
+1

On Tue, Sep 15, 2015 at 5:14 AM, Juan Ignacio Sánchez Lara <
notifications@github.com> wrote:

> Related to #5001 <https://github.com/CartoDB/cartodb/issues/5001>, should
> we warn the organization owner if organization runs out of seats?
>
> cc @andrewxhill <https://github.com/andrewxhill> @saleiva
> <https://github.com/saleiva>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/5518>.
>



-- 

andrewxhill <http://twitter.com/andrewxhill>
http://cartodb.com
