### ISSUE TITLE
Design proposal for new permissions UI to handle additive permissions

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#5521]
This is related to #4851 which surfaces the problems with current UI.

cc @javisantana @juanignaciosl @josecruz since we discussed this in-person. Please correct me if I got anything wrong here.

Current UI behavior:
- Organization has RW permissions set
- Revoking an individual user `RW` permission actually removes the organization permissions, and sets individual `RW` permissions for _all_ users except the one that was revoked (that only gets `R`).

This is already a problem. It does not scale, since it puts too much load on backend (which should have a limit of individual privileges that can be set). Also, technically the permission system is _additive_, i.e. permissions may be added on top of each other (e.g. a user having `R` and organization may have `RW` which should give user `RW` permission by proxy).

Currently the frontend code does not match this model and thus is already broken. But fixing this also means we can't support exceptions/black-list permissions, like the scenario above. Now introducing groups in #4851 this becomes even more obvious. Thus, we need to have a way for the UI that adheres to how the permissions are supposed to work.

The most sensible approach I can think of is to limit revoking access in the UI, so if there's a organization or group permissions set, the affected users (everyone, or group members) would only allow have _additional_ additional permissions but not remove any. E.g. with some group permissions set:
![screen shot 2015-09-15 at 12 31 55](https://cloud.githubusercontent.com/assets/978461/9874411/20e49bd0-5ba6-11e5-8c42-45649cef64ab.png)
Example with organization `R` set:
![screen shot 2015-09-15 at 12 33 55](https://cloud.githubusercontent.com/assets/978461/9874412/20e5dfae-5ba6-11e5-88fa-68bbc78a4a38.png)

It also probably makes sense to display some tooltip on the disabled togglers explaining why they can't be changed, .e.g `read-only given through organization`.

Other proposals/ideas?

_(RW = read+write, R = read-only)_

**Comment by juanignaciosl** [comment]
Agree :+1: I guess the most conflicting point of this is, as you say, "blacklisting", but since now we have groups that scenario is supported with a "writers group".

**Comment by saleiva** [comment]
The thing is that then, is so hard to select all but one user, right?

**Comment by javisantana** [comment]
Imagine this case: 1 organization with 3000 users, you select everyone but one. We'd need to store and manage permissions for 2999 users which does not scale.

Actually we need to set a max number of ACL entries, if not it will be really slow.

I don't think anyone can manage more than 20, 25 individual items

**Comment by saleiva** [comment]
I understand the complexity. On the other hand groups are kind of fixing this so let's proceed.

**Comment by viddo** [comment]
:ok_woman: closing since there's no more work TBD here, will be implemented as part of #4851 
Thx for the feedback!
