### ISSUE TITLE
Add "application/vnd.ms-excel;charset=UTF-8" as a valid downloader content type

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#5524]

**Comment by javisantana** [comment]
where?

**Comment by iriberri** [comment]
In the URL downloader: https://github.com/CartoDB/cartodb/edit/master/services/importer/lib/importer/downloader.rb

@Kartones told me to add it directly, so I'm right now adding it to the XLS format array, if that's okay.

**Comment by iriberri** [comment]
For more info:

If the content-type doesn't match completely (which doesn't in the case of charsets), the format guessing is based in the name of the resource according to the URL. In the specific scenario that failed, the URL is not explanative enough to make it work and the format ".do" is being guessed from it.
