### ISSUE TITLE
CartoDB Editor: Bubble map > Unclassed option

### ISSUE THREAD

**Issue by makella** [CartoDB/cartodb#5535]
In addition to the [classed option](https://github.com/CartoDB/cartodb/issues/5505) for bubble maps, we should also add an unclassed option.  
Unclassed bubble maps, also known as proportional symbol maps, scale the size of symbols proportionally to the data value found at that location.  
There are calculations that need to happen in order to get the correct symbol size for each data value.  

#### Workflow 
* user selects the field that holds the values to be mapped
* the square root for each value is calculated
* based on the square root calculation and a user defined maximum symbol size (used for the largest data value) the sizes for all other symbols are determined using the following equation:  
`symbol size = (maximum symbol size) * (value/maximum value)`  
where:  
`maximum symbol size` = largest symbol used for the highest data value  
`value` = values from the square root field  
`maximum value` = largest square root value  
* the resulting field that holds the values are used in the CartoCSS    

#### CartoCSS
For example, if a field `symbol_size` is calculated, a user would simply do the following: 
* select the Bubble > Unclassed option
* set `marker-width:[symbol_size];` all of the symbols would draw accordingly  
 * this step to me is important because I can't imagine what the CartoCSS would look like if every value and its associated symbol size was written out! Getting a calculated field makes this process really easy.
* the user would then choose to order the data ascending or descending for visual clarity  

#### Legend
We'll need to render legends that round the data values nicely and also, interpret legend shape sizes similar to how the symbol sizes are calculated for the map.  [This is a nice tool](http://cartography.oregonstate.edu/legend/).

#### Considerations/Questions:  
* maximum symbol size
 * we should have a default but the user should also be able to change that and the associated calculations would update and so would the map
  * d3 uses [d3.scale.sqrt](https://github.com/mbostock/d3/wiki/Quantitative-Scales#sqrt) to calculate symbol size
  * in ArcMap, all symbol sizes are calculated up from a [minimum symbol size](https://desktop.arcgis.com/en/desktop/latest/map/working-with-layers/using-proportional-symbols.htm)
* symbol size through scale
 * for both classed and unclassed bubble maps can we scale symbols based on zoom level?  
  * OpenLayers has styling capabilities where symbols are automatically scaled to keep their relative size

#### Example workflow  
I went through the process of recreating a [d3 tutorial on proportional symbol mapping](http://bost.ocks.org/mike/bubble-map/) in CartoDB.  
My complete process is outlined here:  http://maps.github.io/#ad331eadf355f042c0bc

**Comment by DuncanASmith** [comment]
Thanks for adding this feature! It's very useful to have this included in CartoDB.

There is another related improvement that could be considered. When it comes to labelling proportional circle maps it is common to displace labels according to the size of the circle to avoid overlap. In CartoCSS this would mean using a field expression in the properties text-dx & text-dy, e.g. "text-dx: [SymbolWidthField]". This is not currently possible.
