### ISSUE TITLE
Add menu item in data view to show row on map if it has geometry

### ISSUE THREAD

**Issue by mnquintana** [CartoDB/cartodb#5536]
Just had an idea for an enhancement - let me know what you think!

When editing a row, sometimes its data isn't enough to uniquely identify it from other rows (ie. if you're editing a building, and the building doesn't have an address or name yet, how do you know which building you're editing?). It would be incredibly helpful to be able to jump to a row's location in Map View from Data View (if and only if it actually has geometry of course). I'm thinking it would be another menu item in the row context menu. When the Map View is opened, it would center that geometry and display its popup.

**Comment by xavijam** [comment]
I like the idea a lot, what do you think @saleiva?

**Comment by saleiva** [comment]
Not sure if it will make sense in the new editor... but we will take in consideration for sure! Thanks for your feedback!
