### ISSUE TITLE
Move host and port for groups API inside org_metadata_api config section

### ISSUE THREAD

**Issue by azamorano** [CartoDB/cartodb#5537]
Host and port variables when configuring the org_metadata_api_endpoint collide with the the ones used for central.

https://github.com/CartoDB/cartodb/blob/4924-Group_metadata_API_endpoints/app/models/user.rb#L2613-L2615

We should move those inside org_metadata_api like username and password.

**Comment by juanignaciosl** [comment]
Merged into #4924 branch.
