### ISSUE TITLE
Data library searches are giving duplicates

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#5538]
Part of the results when looking for 'USA'

<img width="1082" alt="screen shot 2015-09-15 at 21 55 19" src="https://cloud.githubusercontent.com/assets/132149/9888320/a26fead0-5bf4-11e5-8944-ba626fdd0bea.png">

**Comment by ethervoid** [comment]
Related #5097

**Comment by iriberri** [comment]
Moving to https://github.com/CartoDB/cartodb/issues/5097
