### ISSUE TITLE
[Suggestion] Allow users to disable long processes emails (imports, geocodings)

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#5540]
Hey there,

When there's a very long import process and the user leaves the platform, they are notified with an email.

One of our users asked if there was a way to disable these emails in the account settings or something. Not sure if this is something that we have already think about, but just in case I'm reporting it.

cc @saleiva

**Comment by saleiva** [comment]
Discarding for the time being... I wouldn't consider this intrusive

**Comment by ethervoid** [comment]
We are working on that with the notifications manager #4592

**Comment by iriberri** [comment]
Thanks guys!

@ethervoid, I actually was reading your worklog when it reminded me to open this. Thanks!
