### ISSUE TITLE
Invite users button

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#5544]
From #5523 and #4882. Since "invite users" is now global and not only ldap-only, "create user" and "invite user" is no longer alternative but complimentary: we need both. [Original design](https://projects.invisionapp.com/share/P43R5D79K#/screens/93103186) doesn't cover this, it has one only "Create user" button that opens one modal or another depending on authentication type. But since we need both, we need to combine forms or two buttons for the two different actions an owner can do: inviting and creating new.

cc @xavijam

**Comment by saleiva** [comment]
@josecruz, all yours, should be easy, but be sure you contemplate all the different cases (LDAP vs NON-LDAP and so on...). I'd make this :top: priority (ie done during monday) since @juanignaciosl is about to be able to release this,

**Comment by josecruz** [comment]
Correct me if I'm wrong: Do do you need it in this screen?
![organization - users](https://cloud.githubusercontent.com/assets/596509/10133279/54960b0e-65dc-11e5-81b5-cffeb7776790.png)

**Comment by juanignaciosl** [comment]
@josecruz yes, that's it.

**Comment by josecruz** [comment]
Q: So could we merge both forms on this modal?
![organization - users](https://cloud.githubusercontent.com/assets/596509/10172298/e72b1c36-66de-11e5-9b45-08c9067724bb.png)
![organization - users - new user](https://cloud.githubusercontent.com/assets/596509/10172323/014c64b2-66df-11e5-97e1-9cc372c6513d.png)

**Comment by juanignaciosl** [comment]
I don't think so, but @xavijam should say something here. For example, I really doubt "Create user" would fit the modal without an inner scroll.

**Comment by josecruz** [comment]
Okay so I would fit everything on the next step of clicking "create or invite new user":
![organization - user profile - settings copy](https://cloud.githubusercontent.com/assets/596509/10198137/03b1acc8-679b-11e5-9b64-a362f654f958.png)

**Comment by josecruz** [comment]
ping @saleiva

**Comment by saleiva** [comment]
Can you draft the other tab as well?

**Comment by josecruz** [comment]
Yep!
![organization - user profile - settings copy 2](https://cloud.githubusercontent.com/assets/596509/10224173/0a929ac6-685d-11e5-83a3-cdddb7714764.png)

I don't know if we could make a list of the groups you've already created, or show a dropdown with current groups.

**Comment by saleiva** [comment]
groups should be a dropdown when writting. I don't thing we are using those long fields anywhere else, right? Not for single things like the groups one. Remember that more than one user can be invited at a time and that Invite should be the default option when clicking on that button

**Comment by juanignaciosl** [comment]
@xavijam you can branch `4882-Invite_users_to_your_organization` in order to change the form design if needed. I added a second "Invite user" button that opens the modal for development purposes. Everything else at #4882 is done, when you finish this and it gets merged into `4882-Invite_users_to_your_organization` I'll request the CR and do the staging testing.

**Comment by juanignaciosl** [comment]
@saleiva FYI group field was delayed to #5504 because this development begun before Groups were available. I'd release this first but if @xavijam can do the group picker I'll add group support right now at `4882-Invite_users_to_your_organization` branch.

**Comment by josecruz** [comment]
After talk with @saleiva we made this button with a dropdown

- **Create User** would link to the current screen
- **Invite User** would link to the modal.

![organization - users](https://cloud.githubusercontent.com/assets/596509/10245128/0dbbd5ac-6905-11e5-9479-23607eaabb0e.png)

**Comment by xavijam** [comment]
Great, thanks for making it easier for us :heart: @saleiva @josecruz.

**Comment by xavijam** [comment]
Implemented, should I close this issue?

![hello-invites](https://cloud.githubusercontent.com/assets/132146/10250917/e3915cf6-692d-11e5-8227-9d942be2be47.gif)
