### ISSUE TITLE
explore UI fixes

### ISSUE THREAD

**Issue by carlostallon** [CartoDB/cartodb#5545]
Hi Javi, some little UI fixes for those pages:
**General**
- [ ] We should add a new dropdown menu in the header:
  - Explore\/
    - Explore
    - Gallery
    - Data Library (not visible yet)
![image](https://cloud.githubusercontent.com/assets/1712650/9904756/961050ea-5c80-11e5-9729-4d4b503df011.png)

**Explore**
- [x] Load 8 elements by default (if possible) 
- [x] margin between elements should be 20px
- [x] all icons should have the same color: #CBCED0

![image](https://cloud.githubusercontent.com/assets/1712650/9904809/19e2ce20-5c81-11e5-8886-cc227a1c438a.png)

- [ ] This margin should be 20px

![image](https://cloud.githubusercontent.com/assets/1712650/9904903/bf9ede8a-5c81-11e5-9c1d-07174f634004.png)

- [x] padding in the card should be 20px too

![image](https://cloud.githubusercontent.com/assets/1712650/9904954/0b7eed54-5c82-11e5-8b08-1525bda95fb3.png)

- [x] margin in filters should be 20px

![image](https://cloud.githubusercontent.com/assets/1712650/9905086/fa4edfac-5c82-11e5-9d0f-33c314bce639.png)

**User Profile**
- [x] Margin between avatar and first link should be 40px

![image](https://cloud.githubusercontent.com/assets/1712650/9905195/c253faf0-5c83-11e5-93bb-1f738508e9a2.png)

- [x] Cards in profile should be wider (7 columns, 540px)
![image](https://cloud.githubusercontent.com/assets/1712650/9905222/fa94ecbc-5c83-11e5-8b8f-ec6a88607b9d.png)

- [x] User profile map should be 450px height

![image](https://cloud.githubusercontent.com/assets/1712650/9905339/b73154dc-5c84-11e5-98ab-afd1db414f5e.png)

**Comment by matallo** [comment]
one interaction I love in auto load content sites when scroll is just having to click "load more" button once, then when you hit the bottom you don't have to do it, it loads the content right away

**Comment by javierarce** [comment]
@carlostallon: regarding the 'Margin between avatar and first link should be 40px', we are using a 20px margin in the public map page. Do you think is a good idea to have a different margin here?

**Comment by carlostallon** [comment]
Nope, should be 40px in both :)

**Comment by javierarce** [comment]
Oh, ok, easier then.

**Comment by javierarce** [comment]
Let's wait to have the Data Library ready before adding the dropdown.

**Comment by carlostallon** [comment]
Ok @javierarce
