### ISSUE TITLE
Add users' groups to grantables user items

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#5556]
While working on the new permissions on #4851 I realized that we also would need to return the groups of a each user returned on the grantables API, to be able to tell if a given user is part of a group that's located in the permission ACL, e.g.:
```js
permission.grantAccess(groupX, 'rw');
permission.access(memberOfGroupX); // => rw
```

The other way around, i.e. return the users of each group on the permissions ACL, would technically work, but the data return on the permission objects are kept to a minimal so I guess the approach above is preferable, right?

**Comment by juanignaciosl** [comment]
Merged into #4924 branch.
