### ISSUE TITLE
Composite operation option vs. Blend Mode option?

### ISSUE THREAD

**Issue by csobier** [CartoDB/cartodb#5557]
I am rewriting the composite operation description in the doc when the Map Wizard / *Composite operation* option appears when the map type is *Simple, Choropleth, Bubble, Density*.

However, when the map type is *Torque or Torque Category*, this option appears as "Blend Mode".  Even though the underlying CartoCSS code is `comp-op` for both.  See example image below....

Can you rename the *Blend Mode* options to *Composite operation* for consistency? (If there is a design reason for the difference, please let me know and I will document).

![image](https://cloud.githubusercontent.com/assets/13319925/9911163/caf3a59e-5c6e-11e5-9968-0c0b5bef66cc.png)

**Comment by csobier** [comment]
@saleiva , I should have tagged you to assign accordingly. Apologies.

**Comment by saleiva** [comment]
Fixed on the builder
