### ISSUE TITLE
Layer disappears from map on Visualize click if layer was added via "OK, Create Map" button

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#5562]
ping @saleiva for assignment

Expected:
"Publish" button should appear after you've clicked "OK, Create Map" when trying to add a second layer to a dataset.

Happening:
"Visualize" button appears instead of "Publish". If you hit "Visualize" you're prompted to create a map again. If you do, the layer you just added disappears.

To replicate:
1. From within a dataset click the plus button
2. On "A map is required to add layers" page click "OK, Create Map" button
3. From next "Add a new layer" page select a dataset and click "Add Layer" button 
[both layers are in map but "Visualize" button is visible instead of "Publish" button
4. Click "Visualize"
5. Click "OK, Create Map" button again b/c you've been taken to "A map is required to add layers" page
[Layer you just added has disappeared but now "Publish" button is visible]

**Comment by viddo** [comment]
:point_right: #5563, and fix in #5566 it seems
