### ISSUE TITLE
The big avatar in the home of an organization links to the logged in account of an user

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#5564]
### How to reproduce this issue

1. Log in CartoDB with a regular user that doesn't belong to an organization.
2. Open the public map page of an organization (say team.cartodb.com/maps)
3. Click on the big avatar of the organization.

#### What happens? 

1. You are redirected to your dashboard (https://username.cartodb.com/dashboard)

#### What should happen?

1. Probably nothing? (ie: the avatar shouldn't have a link?)

![screen shot 2015-09-17 at 09 45 16](https://cloud.githubusercontent.com/assets/4933/9927630/944edac4-5d20-11e5-8859-90e4d71a7978.png)

**Comment by xavijam** [comment]
Yeah, that's a bug, because we wanted to do that only when the logged user and the visited user were the same.

**Comment by javierarce** [comment]
Are we planning to change this layout and remove the big icon from there, @carlostallon? Since this is a small bug, maybe it doesn't make sense to fix it.

**Comment by carlostallon** [comment]
Yep, we are also going to use the small one. So It is not worth it

**Comment by javierarce** [comment]
Cool, I'm closing this ticket then, thanks!
