### ISSUE TITLE
Avoid automated metadata deletion

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#5578]
Actual deletion should be avoided on automated actions such as ghost tables or cascades.

- [ ] Find places where CartoDB performs actual deletion.
- [ ] Build up a "soft deletion" / "bin trash" / something system that makes those deletions safe.

@CartoDB/backend @javisantana 

_@kartones, I've assigned this to you because you've been commented as the one who will do it, but please feel free to move it to other if you're not._

**Comment by javisantana** [comment]
take this feature as the one for this milestone @Kartones cc @xavijam

**Comment by xavijam** [comment]
:+1:

**Comment by Kartones** [comment]
I'm gathering all types and places where deletion happens, but I need to know the scope of this... it is not the same implementing application wide soft deletion than protecting Visualizations data, etc.

**Comment by Kartones** [comment]
Scoped:
`As a user I want a way to recover user visualizations and tables with a rake or similar method`

**Comment by Kartones** [comment]
Rescoped as https://github.com/CartoDB/cartodb/issues/5710
