### ISSUE TITLE
Labeling Features in CartoDB.JS prevents layer from rendering

### ISSUE THREAD

**Issue by clhenrick** [CartoDB/cartodb#5586]
When adding data layers to a Leafet map using the `cartodb.createLayer` method I've noticed that a layer will not render if I add CartoCSS to properly label the data. The same CartoCSS works when I use it in the dashboard. [Here is a gist with code demonstrating the problem](https://gist.github.com/clhenrick/201661ff9c61d591d6d3)

**Comment by xavijam** [comment]
Hey @clhenrick, let me move this ticket to CartoDB.js, due to it is a problem related with the library. Thanks for your feedback! :)
https://github.com/CartoDB/cartodb.js/issues/685

**Comment by clhenrick** [comment]
:+1:
