### ISSUE TITLE
Cached vizjson behind wrong URL

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#5591]
Since #4360 vizjson urls must have the username, otherwise [visualizations controller returns 404](https://github.com/CartoDB/cartodb/pull/4394/files#diff-b6f9b42614afc35530e3525a33a64b4eR147). Nevertheless, there's at least one wrong url working: `https://team.cartodb.com/api/v2/viz/b903bb8e-255b-11e5-abcd-0e4fddd5de28/viz.json`. It's cached (appending `?wadus` displays the right error response), but it shouldn't have been generated. 

Just discovered it's related to sessions.

Example:
- Right url: https://team.cartodb.com/u/juanignaciosl/api/v2/viz/d0df01de-4917-11e5-92da-0e9d821ea90d/viz.json
- Wrong url: https://team.cartodb.com/api/v2/viz/d0df01de-4917-11e5-92da-0e9d821ea90d/viz.json

The wrong url won't work in a browser window without authenticated user, but works if you open it with an authenticated user.

cc @CartoDB/backend @javisantana

**Comment by Kartones** [comment]
maybe the caching header should wait until all access checks? (blind hint not having looked at the code)
