### ISSUE TITLE
full-screen button doesn't appear in embed map

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartodb#5597]
When you publish map as an embed map, and the full-screen option/button is enabled in the editor. The embed map doesn't show any full-screen button in the published map and it appears this error in the console:

![screen shot 2015-09-18 at 15 49 15](https://cloud.githubusercontent.com/assets/11177693/9960867/7f85b9a2-5e1d-11e5-8002-6a887aa3e258.png)

**Comment by ztephm** [comment]
S/B 6674135 needs notification when this is fixed b/c their site is waiting to go live for this update.

**Comment by alonsogarciapablo** [comment]
@xavijam you worked on this recently right?

**Comment by xavijam** [comment]
@oriolbx url?

**Comment by xavijam** [comment]
For example, full screen enabled -> https://team.cartodb.com/u/xavijam/viz/bc4e200e-5d4b-11e5-8273-0ec6f7c8b2b9/embed_map

**Comment by xavijam** [comment]
About what I did several days ago:
https://github.com/CartoDB/cartodb.js/pull/674

**Comment by oriolbx** [comment]
@xavijam The problem now appears when the iframe code from the  embed option is used inside a HTML file. When you click  "go to your map" from the embed option, it shows the map with the full-screen button, but when you use the iframe code inside a HTML file, it doesn't work.

Html code:
![screen shot 2015-09-20 at 11 17 31](https://cloud.githubusercontent.com/assets/11177693/9980026/73c96600-5f89-11e5-9657-68fb83766799.png)
Map:
![screen shot 2015-09-20 at 11 19 47](https://cloud.githubusercontent.com/assets/11177693/9980031/922390bc-5f89-11e5-8358-8e901ea02745.png)

**Comment by xavijam** [comment]
https://github.com/CartoDB/cartodb.js/pull/686

**Comment by ztephm** [comment]
Notified S/B 6674135 it was fixed.
