### ISSUE TITLE
Create an "embed" button for public maps

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#5598]
I was talking to @saleiva about adding an embed button. The idea is for other people other than the owner to be able to embed a map. We want to stop people from embedding the whole public map page.

The button should be visible somewhere in this view:

<img width="1280" alt="screen shot 2015-09-18 at 16 18 26" src="https://cloud.githubusercontent.com/assets/4222826/9961504/2907af64-5e21-11e5-8b83-ef763bdc34e1.png">

Could you design it @josecruz ?

Thanks! :smiley:

**Comment by saleiva** [comment]
@cc/matallo

I guess this would involve a modal window, similar to the API one on the dataset page.

**Comment by gfiorav** [comment]
So if this functionality is already in the "Share" button this ticket can be closed? @saleiva

**Comment by josecruz** [comment]
I designed 2 versions:
### Maintain full screen button
----
![public - map disqus](https://cloud.githubusercontent.com/assets/596509/10278506/1eacbf06-6b5e-11e5-8c12-ae6ca09c4617.png)
![public - map embed modal - no fs](https://cloud.githubusercontent.com/assets/596509/10278507/22b4f6e0-6b5e-11e5-917d-fc06133f8809.png)

### No full screen button with full screen link in the modal
----
![public - map disqus](https://cloud.githubusercontent.com/assets/596509/10278529/43de9592-6b5e-11e5-84f1-909f0750e5bb.png)
![public - map embed modal](https://cloud.githubusercontent.com/assets/596509/10278530/48596692-6b5e-11e5-98e9-69f02d989a28.png)

**Comment by josecruz** [comment]
### With full screen button:
![public - map disqus](https://cloud.githubusercontent.com/assets/596509/10334780/c4969b96-6cec-11e5-9845-cbbb8e564d72.png)
![public - map embed modal - no fs](https://cloud.githubusercontent.com/assets/596509/10334781/c71817c8-6cec-11e5-94fc-e7c32be81a3c.png)
### Full screen in the modal
![public - map disqus](https://cloud.githubusercontent.com/assets/596509/10334787/d28cfc22-6cec-11e5-984e-9570fdd24abb.png)
![public - map embed modal](https://cloud.githubusercontent.com/assets/596509/10334789/d42e481a-6cec-11e5-8d8d-d251fcbfccb3.png)

**Comment by josecruz** [comment]
Any thoughts @saleiva ?

**Comment by saleiva** [comment]
Doesn't make sense, These functionalities doesn't make sense together. Can you focus in what I told you about keeping this modal about Embeding the map? Fullscreen should be separated

**Comment by josecruz** [comment]
First version is just the embed modal

**Comment by saleiva** [comment]
?

**Comment by josecruz** [comment]
Thoughts? 
![public - map embed modal - no fs](https://cloud.githubusercontent.com/assets/596509/10511183/d0c9c478-7337-11e5-9c3e-8cc864bc14d0.png)

**Comment by saleiva** [comment]
Blocked and sent to the backlog, this is taking too much
