### ISSUE TITLE
Sync tables to a single Dropbox folder rather than full account

### ISSUE THREAD

**Issue by arielkennan** [CartoDB/cartodb#5605]
It would be helpful grant Dropbox access to a single folder rather than entire Dropbox account for sync tables, that way work colleagues would not be able to access my personal Dropbox. I created a new Dropbox account to host my sync table.

**Comment by xavijam** [comment]
Hi Ariel!

I feel there is no way to select only a folder in Dropbox using their API. There is a possible use case only using the app folder related with the application, but I think that doesn't fit with CartoDB behaviour.
If you don't want to have your dropbox account "opened", in your account page, under the connections block, you can enable/disable your services.

<img width="705" alt="screen shot 2015-09-21 at 12 18 57" src="https://cloud.githubusercontent.com/assets/132146/9989686/0248c368-605b-11e5-9bdc-fe7cdfcd36d5.png">

But the good thing is you could have several accounts and share your work with your colleagues in the same [organization](https://cartodb.com/enterprise).
