### ISSUE TITLE
In search results, "Duplicate dataset" appears for Data Library sources

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#5616]
**Steps**:

* Go to your tables dashboard
* Search for "populated"
* In the results, click the one that comes from Data Library. Notice that the "Duplicate dataset" option appears.

**Expected behaviour**: 
* The duplicate dataset option doesn't appear for Data Libray entries. It doesn't appear if you go to the Data Library section and click on any of the sources, but it does through the search.

cc @xavijam

**Comment by xavijam** [comment]
:fearful:
