### ISSUE TITLE
Warning about disconnecting a Sync Table no longer appearing

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#5617]
Not sure what happened here, but I expect that when a Sync Table is going to be added, there's a message about "are you sure? you won't be able to connect this table anymore!".

It does't appear now when you select "never" in the Sync Table options. Not sure if this is a design decision or if we missed something. 

![image](https://cloud.githubusercontent.com/assets/1730320/9991802/7cdfbf48-606d-11e5-86da-62ae035189d8.png)

**Steps**:
* Go to a Sync table
* Click on "view options"
* Select "never" and apply. The table is disconnected but the warning doesn't appear.

@xavijam

**Comment by saleiva** [comment]
I don't think a warning is needed, tho...

**Comment by iriberri** [comment]
Then we can close. It was appearing before, so I wondered if we removed it on purpose or not.

**Comment by xavijam** [comment]
Closing then
