### ISSUE TITLE
close privacy shuldn't close metadata when editing dataset metadata

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#5621]
after filled all the information in the metadata modal, then opening the privacy modal, when clicking cancel it closed both modals, so frustrating

**str**

- go to map
- click edit metadata
- click privacy at the bottom
- click cancel

**expected behaviour**

- close privacy, keep metadata

**actual behaviour**

- closed everything :(

**Comment by xavijam** [comment]
Closing due to new builder ;).
