### ISSUE TITLE
datasets card differs from map card

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#5623]
from the datasets mockup the card is different, which should we stick with?

<img width="310" alt="screen shot 2015-09-21 at 16 40 37" src="https://cloud.githubusercontent.com/assets/36676/9995087/91dfa1ca-6080-11e5-9e30-5fe12f13804f.png">
<img width="309" alt="screen shot 2015-09-21 at 16 40 47" src="https://cloud.githubusercontent.com/assets/36676/9995088/91e0cd70-6080-11e5-9e0b-50e2999780b5.png">

in the meantime I'm leaving current card for consistency

**Comment by xavijam** [comment]
I encourage you to follow what we have already done with the new datasets page, because it was reviewed with @carlostallon.

**Comment by matallo** [comment]
:bow:
