### ISSUE TITLE
User feed alignement issues

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#5633]
<img width="960" alt="screen shot 2015-09-21 at 19 05 48" src="https://cloud.githubusercontent.com/assets/132149/9998912/e740ccee-6093-11e5-862d-f8529e839b5f.png">

- [x] Name is not aligned with the beginning of the list.

---

- [x] Texts on left column icons are displaced 1 or 2 pxs down.

---

- [x] Space between likes text and icon is wrong (comparing to the other icons + texts)

**Comment by saleiva** [comment]
cc/ @xavijam

**Comment by javierarce** [comment]
Ok, I'll show 9 per page.

**Comment by javierarce** [comment]
I'm moving the dataset ticket to here since it requires some backend work: https://github.com/CartoDB/cartodb/issues/5633

**Comment by xavijam** [comment]
Added again the fake cards bullet.

**Comment by javierarce** [comment]
¿?

**Comment by xavijam** [comment]
:+1:
