### ISSUE TITLE
MapCard previews by ID are not using the CDN url

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#5637]

**Comment by xavijam** [comment]
So, options here:

- Put CDN url in the html template and use it wherever we need (half completed).
- Add maps_template_api within config variable in html template, and use it wherever it is needed (prefered).
- Pass the url through the viz endpoint (not desired).

cc @rambo @ethervoid

**Comment by javierarce** [comment]
And the temporal solution could be use the classic method with the vizjson.
