### ISSUE TITLE
Geocoding France gives polygons for French Guiana and Corsica also

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#5639]
@rafatower @iriberri

Ref S/B 6703448

Expected: Only France polygon will appear when georef by Admin Region with country column containing string "France"

Happening: 
![screen shot 2015-09-21 at 3 44 58 pm](https://cloud.githubusercontent.com/assets/1779444/10002907/bd6c9158-6077-11e5-8a24-cb23fcf3c3de.png)

Steps:
* Create empty dataset with country column, and add row containing "France"
* Edit > Georeference > Admin. Regions
* In Which Column Are Your Region Names Stored? = country; leave 2nd pulldown blank
(I also tried writing in "France" in 2nd pulldown but that caused no rows to be geocoded)

My test: http://cdb.io/1Ls1ZpO

**Comment by rafatower** [comment]
Arguably that's not an issue. I'd say we should also include [Nouvelle-Calédonie](https://fr.wikipedia.org/wiki/Nouvelle-Cal%C3%A9donie) if not done.

> How can I get rid of French Guiana?

that's the real issue we should solve (not in the platfor nor in the geocoder datasets) and I'm afraid this is not the place to fix.

**Comment by iriberri** [comment]
Indeed, we have this: https://github.com/CartoDB/data-services/blob/master/geocoder/admin0/sql/subdivide_polygons.sql

That don't know why is not applied anymore :/

I'll manage.

**Comment by iriberri** [comment]
Fixed :-)
