### ISSUE TITLE
Margin between name and likes and the icon is wrong

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#5645]
Margin between name and likes and the icon is wrong. It should be the same than between the icon and the card border.

<img width="334" alt="screen shot 2015-09-21 at 19 06 04" src="https://cloud.githubusercontent.com/assets/132149/9998913/e75e1b82-6093-11e5-9d8f-d8c3ab5da2b7.png">

From here: https://github.com/CartoDB/cartodb/issues/5633

**Comment by xavijam** [comment]
Closing because it is ok as it is right now.
