### ISSUE TITLE
Trials are 14 days long, not 15 - Incorrect information in some views

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#5649]
https://github.com/CartoDB/cartodb/search?utf8=%E2%9C%93&q=15+days+free+trial

A user just reported this. For example, in the account settings, the "You are close to your limits" message shows 15 days, but trials are 14 days long.

**Comment by iriberri** [comment]
Not sure who would manage this. @xavijam? @matallo?

**Comment by matallo** [comment]
@xavijam is your man here, there are some cases in central, too

ps: I went through the commercial website, and all occurences are "14 days", thanks for spotting these

**Comment by xavijam** [comment]
:+1:, thanks @iriberri
