### ISSUE TITLE
Show empty-message when there are no groups

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#5650]
<img width="998" alt="screen shot 2015-09-22 at 11 35 17" src="https://cloud.githubusercontent.com/assets/132146/10015064/325bfb92-611e-11e5-8d95-500298a2e265.png">

cc @viddo

**Comment by saleiva** [comment]
@josecruz this is for after finishing the stuff we are working on right now

**Comment by josecruz** [comment]
So I made this version that also solves the use of the same icon for org + groups:

![organization - groups copy](https://cloud.githubusercontent.com/assets/596509/10106829/3a25d4a6-63b7-11e5-9a61-12e42e47b190.png)

**Comment by saleiva** [comment]
That's sad. Not too much thought on that one...
What about giving some ideas on why groups are cool?

**Comment by josecruz** [comment]
kind of this?
![organization - groups copy](https://cloud.githubusercontent.com/assets/596509/10160835/628c2922-66a0-11e5-8d4d-b2e79899e2d9.png)

**Comment by saleiva** [comment]
I meant visually!

**Comment by josecruz** [comment]
Design file is called: `Multiuser-0.7`
