### ISSUE TITLE
What does this "settings" tab mean?

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#5653]
<img width="716" alt="screen shot 2015-09-22 at 11 38 27" src="https://cloud.githubusercontent.com/assets/132146/10015115/86ea7bb6-611e-11e5-9a2b-054f7e91df0d.png">

**Comment by saleiva** [comment]
You need a tab to edit the group properties, right?

**Comment by xavijam** [comment]
Yeah true, something that it surprised me at the beginning.
