### ISSUE TITLE
Not possible to add myself (organization owner) to a new group

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#5655]
Not sure about this behaviour, so let's discuss about it:

- I've created the organization with several users.
- Then I've created a group within the organization, 'awesome' is the name of the group.
- And I tried to add new users to the group, but owner was not included in the list of possible users.

Does it make sense?

cc @viddo @urbanphes @saleiva 

<img width="793" alt="screen shot 2015-09-22 at 12 07 47" src="https://cloud.githubusercontent.com/assets/132146/10015820/dc0f7994-6122-11e5-9541-5adad554f19a.png">

**Comment by viddo** [comment]
My bad, followed the same approach as for organization users where the current user is filtered out (client-side). I believe the current user should be included in the listing, to be able to oneself to a group.

**Comment by juanignaciosl** [comment]
I agree with viddo :+1:

**Comment by saleiva** [comment]
+1

**Comment by viddo** [comment]
Correction to my comment above: Organization users collection do not include current user by default (this was like this from before), in the case of grantables collection however I did the same (since no there's no point in sharing with oneself).

**Comment by xavijam** [comment]
For sharing purposes it makes sense, yep.

**Comment by viddo** [comment]
Done in #5672
