### ISSUE TITLE
Clean search button appears out of the block

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#5656]
<img width="1196" alt="screen shot 2015-09-22 at 12 10 24" src="https://cloud.githubusercontent.com/assets/132146/10015843/fd07d4fc-6122-11e5-97ff-8b5d854a41cc.png">

**Comment by viddo** [comment]
Closing since fixed in f2c86d7 as part of refactoring done in #5781
![screen shot 2015-09-28 at 17 08 24](https://cloud.githubusercontent.com/assets/978461/10139534/92933f90-6603-11e5-8578-c185b5dc34b3.png)
