### ISSUE TITLE
Users list search doesn't work under privacy options

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#5658]
### STR:
- After creating a user within an organization.
- I decided to create a map.
- Then I wanted to share it with my colleagues.
- In the users list within privacy options, I tried to search a user but it didn't work.

Bug found under _Safari_ browser.

<img width="922" alt="screen shot 2015-09-22 at 12 19 08" src="https://cloud.githubusercontent.com/assets/132146/10016009/399cae96-6124-11e5-8cb1-5ded78561e0a.png">

**JS error:**
_submitSearch  paged_search_view.js:185

TypeError: this.collection.setParameters is not a function. (In 'this.collection.setParameters({q:g.stripHTML(b),page:1})', 'this.collection.setParameters' is undefined)
_submitSearchedit_field_model.js:2
_onKeyDowntime_input_view.js:51
(anonymous function)
dispatchcartodb.uncompressed.js:26:4968
hcartodb.uncompressed.js:26:860

**Comment by viddo** [comment]
Looking at the trace it looks like you've hit a code path in some old/cached code. :/ Anyway, should not happen since refactoring done in #5672
