### ISSUE TITLE
When an item is shared with a group, it is not defined or specified in the privacy options dialog

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#5663]
### STR:

- Create an organization and groups.
- Try to share a dataset or a map with only a group.
- When you select the group to go back to the privacy options, but we don't have any info about what I selected in the sharing options.

![hello](https://cloud.githubusercontent.com/assets/132146/10016607/87392f9a-6128-11e5-8a99-d629e85ddabc.gif)

**Comment by viddo** [comment]
Duplicate of #5534 :wink:
