### ISSUE TITLE
It would be great to have tooltips with the name over the members of a group

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#5664]
<img width="681" alt="screen shot 2015-09-22 at 12 52 42" src="https://cloud.githubusercontent.com/assets/132146/10016655/def4a0e8-6128-11e5-9759-25237ba4fa47.png">

**Comment by saleiva** [comment]
I'd say this is a pretty enhancement but since not all users will be shown on that list, I'd leave it out of scope

**Comment by xavijam** [comment]
next milestone?

**Comment by saleiva** [comment]
nah

**Comment by xavijam** [comment]
:+1:
