### ISSUE TITLE
Wouldn't you include a new icon explaining that the dataset is shared?

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#5665]
cc @saleiva @viddo @juanignaciosl 

<img width="1018" alt="screen shot 2015-09-22 at 12 59 41" src="https://cloud.githubusercontent.com/assets/132146/10016828/ef79e1d4-6129-11e5-9bb9-bcdca6994a72.png">

**Comment by saleiva** [comment]
Not a priority I'd say...
