### ISSUE TITLE
Privacy change causes dataset to not show meta indicators in listing

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#5667]
![dataset-properties](https://cloud.githubusercontent.com/assets/132146/10017516/542acd5a-612f-11e5-8bd8-ea22a29a8286.gif)

**Comment by viddo** [comment]
Not sure I understand what you mean, what properties have changed exactly?

**Comment by xavijam** [comment]
If you check the dataset item at the beginning, it has the sync and shared icons, but when the privacy is changed, those icons have disappeared...

**Comment by viddo** [comment]
Aha, thx for clarifying. 

But then that's nog a bug with groups, but with the privacy save (they're separate requests) don't contain the necessary metadata I'd imagine.

**Comment by xavijam** [comment]
Seems like there is a problem in the returning of the PUT, comparing:

This is the response of the visualizations controller:
<img width="484" alt="screen shot 2015-12-09 at 14 53 33" src="https://cloud.githubusercontent.com/assets/132146/11687044/cf5c9020-9e84-11e5-8553-4e079062b691.png">

If we check the dataset, it has synchronization data, for example. But after changing privacy of that dataset, the PUT returns:

<img width="686" alt="screen shot 2015-12-09 at 14 54 02" src="https://cloud.githubusercontent.com/assets/132146/11687068/ec8f5d80-9e84-11e5-87ce-f62672cce2df.png">

There is no sync data related.
