### ISSUE TITLE
Different numbers of rows

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#5670]
37 rows
![image](https://cloud.githubusercontent.com/assets/1214201/10019028/38bb42c8-613b-11e5-97aa-c9cb4a1f7317.png)

- Detail view (33 rows)
http://blandinieres.cartodb.com/tables/dataset_3/public

**Comment by ethervoid** [comment]
This data is not realtime right now (updated every 3 hours) so we could have difference in this field, likes and mapviews
