### ISSUE TITLE
Set privacy for dataset in the Data View

### ISSUE THREAD

**Issue by auremoser** [CartoDB/cartodb#5674]
## Context
I can set privacy for my dataset in the dataset list, I'd also like to set it in the map view. 

## Process

1. Create table, drag/drop dataset
2. Create map from table
3. Can set the privacy of the map in the upperleft map view.
4. Attempt to toggle to the "data" view from the map view and the privacy setting is still for the map, not the data I'm seeing. 

When you toggle to the dataset view, you can't set the privacy of the dataset there, it just sets the privacy of the map, which to me is not intuitive, since I'm looking at the data there. 

## Expected result
I would expect that you could set the dataset privacy when you're in the data view:
![screen shot 2015-09-22 at 10 32 40 am](https://cloud.githubusercontent.com/assets/1559703/10021409/d4e0c216-6115-11e5-86ab-9c99552c5c59.jpg)

## Current result
What you set in that view seems to be the map privacy.
![screen shot 2015-09-22 at 10 38 33 am](https://cloud.githubusercontent.com/assets/1559703/10021467/23989230-6116-11e5-9e3e-45b70f660921.jpg)

## Thoughts

* Maybe this was already intended and it doesn't work
* Maybe that isn't intuitive to everyone like it is to me; I just make the mistake a lot of thinking that I'm creating a public map, when actually it's a named map because the data is private event though the "lock" icon in the data view is green.

## `privacy` screenshot

Shows private data table, toggle to data/map view, resetting privacy to public, but the data is still private.
![private](https://cloud.githubusercontent.com/assets/1559703/10021385/b7944d72-6115-11e5-8d70-5e20a29456a1.gif)

**Comment by viddo** [comment]
> When you toggle to the dataset view, you can't set the privacy of the dataset there, it just sets the privacy of the map, which to me is not intuitive, since I'm looking at the data there.

I'd say it's intuitive (or not) depending on what mental model one has. Either way, I think this is something that should be addressed in the new designs, right @saleiva ?

**Comment by xavijam** [comment]
Yeah, I feel this is something we are taking care of for the new designs.

**Comment by xavijam** [comment]
Definitely, it will be managed in the new designs. Closing!
