### ISSUE TITLE
small fixes on upgrade screen

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#5682]
Should be a line below the tabs like in everywhere else, and when changing the tab, the footer gets displaced top so the page looks a bit weird.
![screen shot 2015-09-22 at 19 21 33](https://cloud.githubusercontent.com/assets/132149/10025954/4c796df2-615f-11e5-8f1a-3cabdb5878bb.png)
![screen shot 2015-09-22 at 19 22 50](https://cloud.githubusercontent.com/assets/132149/10025959/54a03bdc-615f-11e5-93ae-157792c4d4f2.png)

**Comment by xavijam** [comment]
Moved to the correct repo -> https://github.com/CartoDB/cartodb-central/issues/818
