### ISSUE TITLE
Organization invite email- rewrite

### ISSUE THREAD

**Issue by csobier** [CartoDB/cartodb#5686]
I was testing CREATE NEW  USER with the new organization account settings and received the following confirmation dialog. It has quite a few grammar errors, please edit.  (I have added a suggestion underneath the sample image, I hope this helps!) @MariaCheca 

![image](https://cloud.githubusercontent.com/assets/13319925/10034383/059dc564-615e-11e5-9883-35854f4d43e9.png)

"If you have not received your password, contact your administrator at 'name'.

"You have been invited to CartoDB as part of the 'name' organization. Please login to your dashboard with your organization username (name) and the password provided by your administrator."

**Comment by MariaCheca** [comment]
Closed here https://github.com/CartoDB/cartodb/pull/5788
