### ISSUE TITLE
[User feedback] Add more information into failed import emails

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#5693]
We just received a suggestion in which the user was asking for the email to contain:

- Name of the file :heavy_check_mark: 
- Name of the user: which I personally think it's a good idea in terms of user communication (and in case someone works in more than 1 account...)
- Format of the file: In this case, the error was due to an invalid support format which we didn't detected (a error HTML file), but wondering if in other cases we could detect it and add it to the email to make it more useful and for it to feel less "automatic".

Low priority, but nice idea for user care.

@ethervoid 
@rafatower

**Comment by ethervoid** [comment]
One file:

![captura de pantalla 2015-09-28 13 12 46](https://cloud.githubusercontent.com/assets/741240/10134009/9f85d7ba-65e2-11e5-8fbd-3080c74b0bf5.png)

Multi file with one successful and one erroneous:

![captura de pantalla 2015-09-28 13 22 11](https://cloud.githubusercontent.com/assets/741240/10134138/fa278fe6-65e3-11e5-8156-dac0c6f32c4c.png)

// @piensaenpixel @csobier

**Comment by csobier** [comment]
The title of the notification could be improved:
"Import confirmation, your dataset has imported successfully"
or 
"Import failed, there was an error while importing your dataset"

This line sounds weird:  "there was some error while importing your dataset"
Change to:  "there was an error while importing your dataset"

**Comment by ethervoid** [comment]
Bump @piensaenpixel

**Comment by ethervoid** [comment]
Bump @carlostallon to review the design

**Comment by carlostallon** [comment]
It's ok to me, but please can you add the same padding than above here:
![image](https://cloud.githubusercontent.com/assets/1712650/10947312/8f3ed430-8327-11e5-828e-a48fb5e0339f.png)
