### ISSUE TITLE
Add BCC support for the notify trending mail

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/cartodb#5706]

**Comment by ethervoid** [comment]
Finally I've made a daily report for the trending maps thing

![captura de pantalla 2015-09-25 13 18 13](https://cloud.githubusercontent.com/assets/741240/10099230/ffbf7562-6387-11e5-8e09-59dd781c8a84.png)

Feedback // @saleiva @jmartinter

**Comment by saleiva** [comment]
As is internal is fair enough!

**Comment by ethervoid** [comment]
Ok so please @Kartones check this PR pls
