### ISSUE TITLE
Renaming a dataset doesn’t reflect the change in the CartoCSS code

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartodb#5711]
I've create a new dataset with only 1 row from a SQL query from other dataset. Then, I've changed the name of this new dataset from **random_point_copy** to **almeria_point**. Everything seems ok, but in the map view of the dataset something strange happens. The CSS option from the wizard doesn't show the new name of the dataset, it shows the "old" name instead. Here is a screenshot of the problem:

![screen shot 2015-09-23 at 16 04 17](https://cloud.githubusercontent.com/assets/11177693/10047103/c8ec94e2-620c-11e5-8fec-4698a4e5cc6f.png)

I've tried to refresh the browser and change privacy to see if the CSS wizard change the name, but it doesn't work.

**Comment by xavijam** [comment]
This problem can't happen anymore, dataset view doesn't contain cartocss editor. In any case, if someone renames a dataset used in a map, we will show up the error in the map. So closing! :)
