### ISSUE TITLE
New dataset privacy setting has undefined text

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#5713]
![screen shot 2015-09-23 at 16 27 05](https://cloud.githubusercontent.com/assets/978461/10047776/05c25458-6210-11e5-8edc-6367b402baf0.png)
Original PR #5340

Happened while smoke testing on staging (rui).

**Comment by xavijam** [comment]
I found the same :(

**Comment by xavijam** [comment]
It was introduced here, https://github.com/CartoDB/cartodb/commit/45a0a7940cb2ce6103c52cf12fc632725d9686f4.

We changed the data attribute to data-html but the tooltip was rendered with the data-title content...

cc @javierarce @viddo.

**Comment by javierarce** [comment]
:(
