### ISSUE TITLE
Imported .csv file w/ columns named latitude and longitude are converted to number even if type/content guessing is disabled

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#5718]
:point_up: happened while smoke testing on rui, works as expected in production.
Note that it's only those two columns that are converted, the rest are left as expected.

ex connect by URL using https://gist.github.com/viddo/cc7a6c7c259279b96755/raw/70edce8663797dfced2b0b300ba6e6ca5ad509b7/top5.csv

**Comment by juanignaciosl** [comment]
This was closed by @rafatower at #5612 just a moment after the last master merge into #4924 branch :sweat_smile: Just merged and pushed the merge.

**Comment by viddo** [comment]
:+1:
