### ISSUE TITLE
token is not present error on Drive connection

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#5721]
Currently if I attempt to bind my CartoDB mail account at staging it will fail displaying `{"errors":{"imports":"token is not present"}}` error message inside the popup. I get this 400 error at Chrome console (the response body is previous message):

```
https://juanignaciosl-rui-groups-smokes-admin.cartodb-staging.com/api/v1/imports/service/gdrive/oauth_callback/?state=__juanignaciosl-rui-groups-smokes-admin__gdrive__&code=4/evWqgjPxlwrZ3wYQCTwBO65lmsHO596BulwijRwWu0d#
```
Nevertheless another GMail test account works. This doesn't seem related to Google Apps vs GMail accounts, but I haven't managed to get any more insight.

cc @rafatower

**Comment by rafatower** [comment]
have you tested in production?

**Comment by juanignaciosl** [comment]
Yep, although the example I've written down here is from staging I checked in production before issuing this.

**Comment by juanignaciosl** [comment]
(I deleted previous comment because I mixed this #5721 similar error).

No, I haven't been able to reproduce it in production but it's an error I see at Rollbar from time to time and it might be a corner case for whatever reason. I don't use to write down bugs I can't deterministically reproduce, but this one, involving external services and so on, looked important to me. Close it if you think it doesn't deserve losing time.

**Comment by rafatower** [comment]
Today I read this in the support channel:
> that’s because you’re using your google account in other cartodb account
> google only gives one token per app
> you’ll need to disconnect the other

can this be your case?

**Comment by juanignaciosl** [comment]
Nop, I tried with an anonymous window.

**Comment by rafatower** [comment]
I mean, can you have 1-google-N-cartodb accounts association, regardless of incognito? I don't think so, but I might be wrong.

**Comment by juanignaciosl** [comment]
I think you should, but I might be wrong. Assigning this to me in order to check.

**Comment by Kartones** [comment]
Ok, confirmed it is reproducible and an issue of having already an account linked to a certain Google Drive App-key.

### Steps to reproduce
- Have user A connect his account to GDrive on the connect dataset flow
- Switch to user B (incognito window is fine), try to connect same google account
- Callback returns:
```
http://y.localhost.lan:3000/api/v1/imports/service/gdrive/oauth_callback/?state=__y__gdrive__&code=4/qYGVkheu_U0fgXLjDEpnqYEFHIv5ty7iW3cwHJ69DBc#

{
  errors: {
    imports: "token is not present"
  }
}
```

So I guess here the correct course of action is returning a specific error and notifying the user that the specified google account is already linked and cannot be reused until the other permission revoked.

**Comment by Kartones** [comment]
Branch: `5721-capture-already-linked-gdrive-accounts`

**Comment by Kartones** [comment]
New message reflects correctly the scenario... but is still dumped as raw json:
```
{
  errors: {
    imports: "Error validating auth token. Is this Google account linked to another CartoDB account? @ gdrive"
  }
}
```
