### ISSUE TITLE
Support box touches the footer at billing page

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#5723]
![screen shot 2015-09-23 at 18 05 34](https://cloud.githubusercontent.com/assets/932968/10050668/d1b8c256-621d-11e5-8720-f161c2f5d81e.png)

cc @matallo @MariaCheca

**Comment by matallo** [comment]
wat, I remember fixing this for @juanignaciosl (can't point to the specific commit now)

**Comment by xavijam** [comment]
Moved to central -> https://github.com/CartoDB/cartodb-central/issues/821
