### ISSUE TITLE
Total number of rows doesn't get reflected on the dataset page for the newly added or deleted features in the table.

### ISSUE THREAD

**Issue by UtkarshGIS** [CartoDB/cartodb#5731]
Steps to reproduce
- Take a point shapefile and upload it to your account 
- check the total number of rows uploaded it will display correct for the first time ( in my case its 3 )
![1](https://cloud.githubusercontent.com/assets/10266131/10068659/c2ea6454-62c3-11e5-8ae2-9860ebe5fd1f.png)

- go to map view and add a feature 
![2](https://cloud.githubusercontent.com/assets/10266131/10068665/cc65ce74-62c3-11e5-98bd-750a1f90d22e.png)

- the row count on the table should be 4 but it still says 3
![3](https://cloud.githubusercontent.com/assets/10266131/10068667/d686c840-62c3-11e5-9437-d6ff2a6c9b0e.png)

- count query from the table displays correct result 
![4](https://cloud.githubusercontent.com/assets/10266131/10068676/df2b54ac-62c3-11e5-94f3-a81cb9b513bc.png)

- but on the dataset page its not reflected 
- the rows on the datasets page only get displayed after running  ```VACUUM FULL ANALYZE table_name ```

**Comment by xavijam** [comment]
Hi there!

Yeah, we use internal [postgresql stats](http://www.postgresql.org/docs/9.2/static/view-pg-stats.html) queries for row count, so it is an estimation. After a _non-deterministic time frame_, they get updated, so recent data might not be reflected instantly of course.

Cheers!
