### ISSUE TITLE
Change the Explore API frequency to 40 minutes

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/cartodb#5733]
Right now Explore API spent ~ 20 minutes in the execution and is launched every 3 hours. We want to reduce this time to 40 minutes but we have to check with systems if its possible

**Comment by xavijam** [comment]
No 20? We have that for trendmap, is it too much?

**Comment by ethervoid** [comment]
The task spent 20 minutes so we should give other 20 minutes because the machine is used by other heavy tasks

**Comment by ethervoid** [comment]
Changed to 40 minutes. There will be people monitoring the performance.

**Comment by ethervoid** [comment]
After some checks by @santisaez  the conclusion is that launch this task every 40 minutes is not an option right now due the high CPU load so we are going to put every 1,5 hour (We are trying to do it in Jenkins) or put every 2 hours (in case we could put 1,5 hour in jenkins).

With this change we pass to update every 1,5 or 2 instead of every 3 hours.

If its high priority we should check for performance improvements and try to improve the CPU load to an acceptable point. 

// @saleiva

**Comment by saleiva** [comment]
not a high priority right now
