### ISSUE TITLE
update footer as per website

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#5735]
<img width="969" alt="screen shot 2015-09-23 at 16 18 35" src="https://cloud.githubusercontent.com/assets/36676/10069410/72bf86ce-62ac-11e5-9392-65e8c2156b13.png">

vs

<img width="1438" alt="screen shot 2015-09-24 at 11 07 43" src="https://cloud.githubusercontent.com/assets/36676/10069425/88209d50-62ac-11e5-8b5b-cd0e8d6ab896.png">

**Comment by xavijam** [comment]
It is already implemented right?

**Comment by matallo** [comment]
not really, as last version is the one in http://docs.cartodb.com/ (it's being updated in website now from that)

**Comment by xavijam** [comment]
:+1:

**Comment by matallo** [comment]
finally!
