### ISSUE TITLE
Error message for password too short in organisations is "not present, not confirmed"

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#5736]
Should be something like "Min 6. characters", like it is in the normal signup.

<img width="663" alt="screen shot 2015-09-24 at 11 12 35" src="https://cloud.githubusercontent.com/assets/4222826/10069577/585ddd5c-62ad-11e5-88d8-b3e2d2361e6b.png">

**Comment by xavijam** [comment]
This is an error that comes from server side, so @gfiorav all yours :).

**Comment by gfiorav** [comment]
@xavijam The problem with this one is that validation does not happen all at once like it should, but rather o different stages depending on what you update (password update triggers it's own validation, for example) so the original good message "Password too short" gets overwritten (or shadowed) with another validation that happens afterwards when the field has been deleted (so the password is empty, hence throwing "not present, not confirmed". 

This requires a validation refactor that is set to be delicate. We're contemplating refactoring this model completely. So:

a) We refractor and this gets solved via that 
b) We don't and there is no simple solution to this.

I'll come back and update when one of the above happens.

**Comment by xavijam** [comment]
:+1:

**Comment by javitonino** [comment]
Closing via https://github.com/CartoDB/cartodb/pull/7563 (same numbers as this ticket, just in a different order :1234:)
