### ISSUE TITLE
JSFiddles linked from CartoDB docu don't show anything

### ISSUE THREAD

**Issue by raquel-ucl** [CartoDB/cartodb#5738]
Hi,

I was trying to show some colleagues how to use CartoDB.js with the JSFiddle examples I used some time ago to learn, and they don't seem to work anymore. [This is the doc site that links to them](http://academy.cartodb.com/courses/03-cartodbjs-ground-up/lesson-2.html), and this is the list of links that once showed some data, but don't anymore:

* http://jsfiddle.net/gh/get/library/pure/CartoDB/academy/tree/master/t/03-cartodbjs-ground-up/lesson-2/jsfiddle_demo_ondone
* http://jsfiddle.net/gh/get/library/pure/CartoDB/academy/tree/master/t/03-cartodbjs-ground-up/lesson-2/jsfiddle_demo_multilayer

Maybe something on the documentation user has changed. The [vis.json](http://documentation.cartodb.com/api/v2/viz/23f2abd6-481b-11e4-8fb1-0e4fddd5de28/viz.json) looks OK to me, but nothing is being plotted. 

Cheers,
Raquel

**Comment by xavijam** [comment]
Hi Rachel!
First of all, thanks for your feedback. Let me move this discussion to the correct repository, ok?

https://github.com/CartoDB/docs/issues/384

Cheers!
