### ISSUE TITLE
ArcGIS import error - Missing data: key not found

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#5741]
From https://github.com/CartoDB/cartodb/issues/5612

SB/7228233

This happens regularly for the following keys:

`fields` at SB/7228233

`geometryType` at SB/7294060

````
true: ogr2ogr output:          
true: ogr2ogr exit code:       0
true: Errored importing data from /tmp/imports/aaa-aaaa-173ylbw/otras_categor_as_sinap.json:
false: CartoDB::Datasources::ResponseError: Missing data: key not found: "fields" http://mapas.parquesnacionales.gov.co/arcgis/rest/services/IGAC/SINAP/FeatureServer/1/query ["/home/ubuntu/www/production.cartodb.com/releases/aaa/services/datasources/lib/datasources/url/arcgis.rb:443:in `fetch'", "/home/ubuntu/www/production.cartodb.com/releases/aaa/services/datasources/lib/datasources/url/arcgis.rb:443:in `get_by_ids'", "/home/ubuntu/www/production.cartodb.com/releases/aaa/services/datasources/lib/datasources/url/arcgis.rb:145:in `stream_resource'", 

````

I'd say this seems something in our end. The two URLs failing are available in SB/6671042, but you can just ask me for them in private to make the check faster.

The error for the `geometryType` key is as follows:

````

2015-11-13 10:40:33 UTC: Before importer run
2015-11-13 10:40:34 UTC: Errored importing data:
2015-11-13 10:40:34 UTC: CartoDB::Datasources::ResponseError: Missing data: key not found: "geometryType" URL_here ["/home/ubuntu/www/production.cartodb.com/releases/20151112173200/services/datasources/lib/datasources/url/arcgis.rb:444:in `fetch'", 
````

Related comment: 
I'm seeing that the system tries to retrieve the data from the `/query` endpoint. I notice there exists a `?f=pjson` parameter from which the data can be retrieved as JSON.

**Comment by tpcolson** [comment]
Experiencing same error.

**Comment by tpcolson** [comment]
The problem may be with the ESRI-supplied column "GlobalID", which is its unique identifier that is added to all editable geodata services. By removing the GlobalID, I was able to sync http://services1.arcgis.com/fBc8EJBxQRMcHlei/ArcGIS/rest/services/GRSM_SPECIES_OBSERVATIONS_MAXENT/FeatureServer to CartoDB. Not a work-around though, as folks generally need to be able to edit their feature services, and can't without the GlobalD. From https://github.com/CartoDB/cartodb/issues/5612 I see that there errors on duplicate keys but there is a) no index on GlobalID, and b) it definitely is unique....


Another untested solution/work-around is to get rid of the ESRI ObjectID during the import and sync all together: only ESRI software needs this, any use via CartoDB sync tables could, in most cases, safely ignore it. OR.....don't treat the ObjectID as a PK.....

**Comment by iriberri** [comment]
cc @michellechandra

**Comment by jgoizueta** [comment]
This seems to fix it: c68d7d

The problem was the code expected the objectIds returned by the ArcGIS service to be ordered, and in some cases they're not.

I'll look into preparing some tests to check for this.

**Comment by rafatower** [comment]
Fixed and confirmed in production. Have a nice Friday! :dancer: :)
