### ISSUE TITLE
CartoDB Editor: Font Selector

### ISSUE THREAD

**Issue by makella** [CartoDB/cartodb#5751]
As referenced [here](https://github.com/CartoDB/cartodb/issues/5461) it is hard to tell what fonts are available to use for map labels.  
The way Illustrator does it is nice with the font family in one drop-down, the available font weights in another, and then the font size option:
![screen shot 2015-09-24 at 2 29 58 pm](https://cloud.githubusercontent.com/assets/1566273/10085928/db8f63c4-62c8-11e5-8dd4-71d9783779c6.png)  
This could transfer to CartoCSS pretty easily:  
```
#layer {
 text-name: [name];
 text-face-name: "Open Sans Extrabold Italic";
 text-size: 18;
 .....
}
```

**Comment by makella** [comment]
are there plans to add more font options to the editor? if so, is there a resource to look at to see which ones we can add?

this will be helpful in determining a good variety of fonts that we can make available and also choosing a good font for the default labels that draw.

**Comment by saleiva** [comment]
hey @makella tell us which fonts do you want! :)

**Comment by makella** [comment]
@saleiva ok!

I am waiting for someone to help me test the ones that I am interested in testing. I have cartodb local running so I can put them on my instance and make sure they are all good. 

Here is my list:
https://github.com/CartoDB/cartodb/issues/8768
