### ISSUE TITLE
View a public dataset and the message is shown "This dataset is empty"

### ISSUE THREAD

**Issue by urbanphes** [CartoDB/cartodb#5761]
- Go to [saleiva's feed](http://team.cartodb.com/u/saleiva).
- Click in any map.
- See the associated datasets.
- Choose a public dataset and click it.
- It goes to the dataset but the message on the screen is: "This dataset is empty", when it is not.

![captura de pantalla 2015-09-25 a las 14 57 02](https://cloud.githubusercontent.com/assets/14546701/10101159/1ea7a760-6397-11e5-8a26-81a77edc838f.png)

**Comment by xavijam** [comment]
@kartones @juanignaciosl do you know why we use this:

https://github.com/CartoDB/cartodb/blob/master/app/views/admin/visualizations/public_map.html.erb#L183

Instead of 

```rails
<a href="<%= CartoDB.url(self, 'public_table', {id: vis.table.name}, vis.table.user) %>" title="<%= vis.table.name %>" class="DefaultTitle-link u-ellipsLongText"><%= vis.table.name %></a>
```

**Comment by Kartones** [comment]
See https://github.com/CartoDB/cartodb/blob/master/app/controllers/admin/visualizations_controller.rb#L243

```ruby
 if table_owner.nil?
          # strange scenario, as user has been deleted but his table still exists
          @related_tables_owners[table.user_id] = nil
        else
          @related_tables_owners[table.user_id] = table_owner
        end
```

Safety measure to not fully break a user map if there's a related table that is broken somehow

**Comment by xavijam** [comment]
ok so:

<a href="<%= CartoDB.url(self, 'public_table', {id: vis.table.name}, @related_tables_owners[vis.table.user_id]) %>" title="<%= vis.table.name %>" class="DefaultTitle-link u-ellipsLongText">
   <%= vis.table.name %>
</a>

**Comment by xavijam** [comment]
If not the weird behaviour @urbanphes is describing will happen.

**Comment by Kartones** [comment]
Clarification: The real issue is that the source url is wrong, it is missing `/u/{USERNAME}` so then associated dataset fails. If properly setup works.

@xavijam confirmed me the source it is the user feed so that's where the bug relies :(

**Comment by xavijam** [comment]
Turns out the problem comes from the new user feed. If you check an organization user feed, and clicks over any visualization, it doesn't add the /u/whatever, that's the origin of the bug.

**Comment by viddo** [comment]
also duplicated logic client-side, e.g. in https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/explore/map_item_template.jst.ejs#L7 (possibly in more places?), could/should be simplified a lot by using `vis.viewUrl(currentUser)` that encapsulated the logic to generate a proper base url for the vis depending on its state
