### ISSUE TITLE
Error qualifying table names when a sql is applied

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#5782]
##### STR
1. Create a user called "cdb".
2. Create an organization with cdb user as owner.
3. Create a table called "cdb" and another one "aaaa".
4. Create a map with that "aaaa" layer.
5. Go to the map and open the SQL.
6. Run this query:
```sql
SELECT 
ST_Transform(the_geom, 4326) 
AS         
 the_geom_webmercator,
 cartodb_id,
 description,
 name
FROM 
aaaa
WHERE
 cartodb_id>=1
ORDER BY cartodb_id ASC
```

#### Happening
A qualified sql is being applied, but username is repeated two times.
```sql
SELECT 
ST_Transform(the_geom, 4326) 
AS         
 the_geom_webmercator,
 cartodb_id,
 description,
 name
FROM 
cdb.cdb.aaaa
WHERE
 cartodb_id>=1
ORDER BY cartodb_id ASC
```

#### Expected behaviour
This sql should be applied:
```sql
SELECT 
ST_Transform(the_geom, 4326) 
AS         
 the_geom_webmercator,
 cartodb_id,
 description,
 name
FROM 
cdb.aaaa
WHERE
 cartodb_id>=1
ORDER BY cartodb_id ASC
```

---

This problem comes from a function we apply over the sql trying to add the username before the table_name, only when a user belongs to an organization. This is the function:

https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/table/menu_modules/sql.js#L389
```js
   ...
    // transform from select * from table to
    // select * from user.table
    qualifyTables: function(sql) {
      var username = this.user.get('username');
      return _.reduce(this.user.tables, function(sql, t) {
        var re = new RegExp("([^\\.\\'a-zA-Z0-9\_])(\"?)" + t + "(\"?)", "gi");
        var replace_str;
        if (username.indexOf('-') !== -1) {
          replace_str = "$1\"" + username + "\".$2" + t + "$3";
        } else {
          replace_str = "$1" + username + ".$2" + t + "$3";
        }
        return sql.replace(re,  replace_str);
      }, sql);
    },
   ...
```

The problem is that user tables are ['aaaa', 'cdb']. So when this function is in the second loop, the sql already has the table name qualified 'cdb.aaaa', but cdb is interpretated as dataset and it add again the username, so the resultant sql has 'cdb.cdb.aaaa'.

cc @javisantana @makella

**Comment by xavijam** [comment]
We should check in the reduce if table_name is already qualified or belongs to the qualified name.

**Comment by iriberri** [comment]
SB/7678494

**Comment by xavijam** [comment]
We will take care in the new builder sql editor :).
