### ISSUE TITLE
Hover infowindow appears far from line geometry when choropleth wizard is used

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#5787]
@xavijam
Ref S/B 6783021

Expected: 
When mouse rolls over blank map area in choropleth map with Line geometry and hover infowindows enabled, window will not show.

Happening:
![lines_hover_test](https://cloud.githubusercontent.com/assets/1779444/10148283/9e120200-6600-11e5-8f28-d750aae3bbee.gif)

My test: https://team.cartodb.com/u/stephaniemongon/viz/0f1ece74-65fc-11e5-88e6-0e76aec36da9/public_map

It's happening in the areas that are "inside" a line angle (or curve in S/B client's map) for Choropleth. Not happening for Simple Wizard with same geometry. BTW the Choropleth CartoCSS shows a parameter for polygons even though the_geom is Line:

#ticket_lines_hover{
  polygon-opacity: 0;
  line-color: #FFFFB2;
  line-width: 5;
  line-opacity: 0.8;
}

**Comment by xavijam** [comment]
The bug is due to that property, checking if the wizard adds that property.

**Comment by saleiva** [comment]
Old bug, not a priority I'd say

**Comment by stevesong** [comment]
@saleiva not minor for me as it breaks my map at https://afterfibre.cartodb.com/tables/auc/map  Is there a workaround?

**Comment by xavijam** [comment]
Hey @stevesong, remove ```polygon-opacity: 0;``` from your CartoCSS and it should do the trick.

**Comment by stevesong** [comment]
Thanks @xavijam!  That worked like a charm. :)

**Comment by xavijam** [comment]
yay :)

**Comment by xavijam** [comment]
Fixed in the new builder, so closing :).
