### ISSUE TITLE
Import errors not being reported in stats in all cases

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#5790]
Particularly, I'm pretty sure those errors coming from ogr2ogr failures are not being recorded properly.

**Comment by rafatower** [comment]
### Description of the problem
When an import finishes, it logs a line in `log/imports.log`. Those lines look like the following:
```
{"user":"jgoizueta-ded04-4","state":"complete","tables":1,"imported_tables":1,"failed_tables":0,"error_code":null,"import_timestamp":"2015-11-27T16:39:38+00:00","queue_server":"ded04-st.dia2.cartodb.net","database_host":"127.0.0.1","service_name":"public_url","data_type":"url","is_sync_import":false,"import_time":5.397816589,"file_stats":[{"type":".csv","size":167,"file_rows":null,"imported_rows":5,"error_percent":null,"fallback_executed":null}],"resque_ppid":31148,"user_timeout":3413,"error_source":null,"id":"2f0c6996-1fc8-4c0d-bc3f-eaea8647720c","total_size":167,"cartodbfy_time":0.05673836,"import_throughput":30.938435429674065,"cartodbfy_throughtput":2943.334985360874,"cartodbfy_import_ratio":0.010511353815841928,"extra_options":{},"retrieved_items":0}
```

Those lines are used for several purposes: performance metrics, debugging and daily metrics.

The problem is that we suspect that sometimes those metrics are not being stored. There should be some cases in which an import leaves no trace in that log.

Refer to `DataImport#notify`:
https://github.com/CartoDB/cartodb/blob/master/app/models/data_import.rb#L764

### Possible root cause
Not-so-good exception handling can cause this kind of trouble. In the importer case, exception handling is used for error feedback to the user (casting and rethrowing). Sometimes an exception could bubble-up the whole stack and get lost in the resque job.

### Proposed course of action
- [ ] (a) Try to **confirm** the issue by either reproducing some of the suspected problems (e.g: timeouts in ogr2ogr) or just inject an exception in the code and check whether it spits a trace `log/imports.log`, or
- [ ] (b) Add fire-and-forget metrics when an import starts. Conciliate those metrics, **confirm** whether we are "losing" imports or not: the total number of imports started must match the total number of imports finished.
- [ ] If there's an inconsistency in the metrics: fix the root cause (exception handling).

They are not exclusive, but I'd start with (a) and upon confirmation start working on the exception handling part.

**Comment by rafatower** [comment]
about the metrics, some quick ideas: aside from logs we have the data_imports table itself. We could just use the log file as well, adding a state created. But we need to check how daily metrics are generated from kibana/logs.

**Comment by rafatower** [comment]
Some related issues:
- https://github.com/CartoDB/cartodb/issues/5468
- https://github.com/CartoDB/cartodb/issues/6212

**Comment by iriberri** [comment]
For the record: 

> inject an exception in the code and check whether it spits a trace log/imports.log

We saw this morning that raising an exception on the `run` method of ogr2ogr was not reproducing the issue.

**Comment by iriberri** [comment]
After we introduced the `pending` label last week, we should have enough data to take a look here and see if the number of `pending` and the number of "finished" imports matches.

**Comment by iriberri** [comment]
I'd say we have a success here. I created the following script:

```ruby
require 'json'
require 'curb'
require 'time'

imports = []
success = 0
unfinished = 0
unfinished_imports = []
root_url = "http://XXXXX/logstash-2015.12."
extra_url = "/_search?q=id:"

IO.foreach('/Users/Iriberri/imports.log') do |line|
  imports << JSON.parse(line)
end

imports.each do |import|
  day = Date.parse(import["import_timestamp"]).day
  c = Curl::Easy.perform("#{root_url}#{day}#{extra_url}#{import["id"]}")
  body = JSON.parse(c.body_str)
  if body["hits"]["total"] > 0
  	success += 1
    #puts "Status: " + body["hits"]["hits"][0]["_source"]["state"].to_s
  else
  	unfinished += 1
  	unfinished_imports << import["id"]
  	puts "=== IMPORT NOT FOUND: #{import["id"]}  -- #{root_url}#{import["id"]} ==="
  end
end
puts "CHECK FINISHED: #{success} Success, #{unfinished} unfinished"
```

Output is: 

````
~/dev/scripts $ ruby check_imports.rb
CHECK FINISHED: 106 Success, 0 unfinished
```
