### ISSUE TITLE
Map not created after importing dataset from synced URL dataset

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#5806]
This problem is reproduced:

1. From maps view in dashboard click "New map"
2. Click "Connect dataset"
3. Import from URL (for example: http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/physical/ne_110m_coastline.zip)
4. Choose to sync every hour

The dataset is imported but the map is not created.

cc @xavijam

**Comment by xavijam** [comment]
I feel this is due to a problem with the synchronization model. It doesn't allow to speficy if you want to create a vis or not, right @kartones?

**Comment by Kartones** [comment]
It should work: https://github.com/CartoDB/cartodb/blob/master/app/controllers/api/json/synchronizations_controller.rb#L189

But please, provide more details, like:
- Have you checked what payload is sent from the frontend to the backend? (if there is no `create_vis` param then might be indeed FE-related)
- If `create_vis` is sent, have you tried debugging if the backend ignores the field when creating a synchronization?


PS: Might be worth to add to the imports/syncs log a line like... `Will create visualization?true/false`

**Comment by Kartones** [comment]
This are the parameters sent to the backend (what I asked for details and didn't got an answer, anyway it's a minute to check):
```
{
   content_guessing: true
   interval: 3600
   type_guessing: true
   url: "http://..."
}
```

Plus what I said before [about the backend supporting it](https://github.com/CartoDB/cartodb/blob/master/app/controllers/api/json/synchronizations_controller.rb#L189) this means that it really is a FE "issue".

By definition a Sync table is a dataset, and datasets do not have visualizations. Now we've added this option of creating a vis, but as they are created as new datasets, combined with my lack of Backbone knowledge I don't see where to plug the `create_vis: true` if it is a sync and I want a map... But I'll check where and play/learn a bit of Backbone

**Comment by Kartones** [comment]
Branch `5806-create-sync-map-from-maps-page`
