### ISSUE TITLE
Locking Legend Labels

### ISSUE THREAD

**Issue by csobier** [CartoDB/cartodb#5807]
From the *Legend* options of the CartoDB sidebar, there are "lock" checkboxes that appear for Bubble, Intensity, and Density maps only.  

What is this option supposed to do?  I thought maybe resizing/zooming the map would lock the legend label in place or something, but so far, I’m not seeing any change in behavior.  (Tech Support is stumped too).  Please advise.

![image](https://cloud.githubusercontent.com/assets/13319925/10192741/79c53582-674c-11e5-9f82-28a3ee3ebc2e.png)

@saleiva, I am tagging you so that you can assign accordingly.

**Comment by xavijam** [comment]
If there is any data change (imagine min or max has changed), label doesn't change and it shows what the user selected at the beginning.
