### ISSUE TITLE
share map component and share button in public page are not consistent

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#5811]
steps to reproduce

- go to https://googledataorg.cartodb.com/u/googledata/viz/cf9d50ba-24fe-11e5-ae83-42010a14cb63/public_map

when sharing options are enabled, the share text for twitter icon is not the same than the share text when clicking in twitter button of dialog

also, most of the options are duplicated (but embed)

![screen shot 2015-09-30 at 16 00 01](https://cloud.githubusercontent.com/assets/36676/10195184/a2fc7d26-678c-11e5-8d7e-d7f5a54fccf3.png)

**Comment by xavijam** [comment]
What could we do to offer iframe option directly in the options navbar?

**Comment by xavijam** [comment]
This is gonna change with the new dashboard/editor thing, closing!.
But in any case this ticket were supposed to be in cartodb.js, for the records! :)
