### ISSUE TITLE
Duplicate shared dataset from a subuser with a dash (-) in the username fails

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#5813]
**STR:**

* Inside an organization, create a subuser with a dash in its username
* Log in and create a sample table, share it with other member of the org
* Log into the account of the other member, access to the table, and try to duplicate it
* The process fails after some timeout, I guess, and this error appears:

  `````
2015-09-29 15:11:06 UTC: Going to set merge error with code 8003 
2015-09-29 15:11:06 UTC: Additional error info: PG::Error: ERROR: syntax error at or near "-"
   LINE 1: ...E TABLE stores_101_29_copy AS SELECT * FROM crb-subuser.sto... ^ 
2015-09-29 15:11:06 UTC: After dispatch 
2015-09-29 15:11:06 UTC: ERROR! 
===LOG END===
`````

**Expected behaviour:**
* A table shared with you inside an org environment can be duplicated

  It seems that the username is not being double quoted and the select query that is done in the back to retrieve the data fails due to a syntax error.

**More:**
* The issue doesn't seem to be happening in the creation of tables through SQL queries, as there the UI doublequotes the username if it contains a dash. The first time I followed these steps, the duplication got totally stuck. The second time it worked.

These are the details of the import ID for the failed attempt. (b01403ed-9e84-4bda-8421-832741f6b7e6). I anonymized it a little but, but the format of the names with dashes has been respected.

````
{
data_source: "",
data_type: "query",
table_name: "tablename_copy",
state: "failure",
success: false,
logger: "a48499be-171c-4c15-a250-b96c322c269b",
updated_at: "2015-09-29T15:11:06+00:00",
created_at: "2015-09-29T15:11:06+00:00",
error_code: 8003,
queue_id: null,
tables_created_count: null,
table_names: null,
append: false,
migrate_table: null,
table_copy: "user-name.tablename",
from_query: null,
synchronization_id: null,
id: "b01403ed-9e84-4bda-8421-832741f6b7e6",
table_id: null,
user_id: "xxxxx",
service_name: "public_url",
service_item_id: null,
stats: "{}",
type_guessing: true,
quoted_fields_guessing: true,
content_guessing: true,
server: "quxxxet",
host: null,
resque_ppid: 17649,
upload_host: "xxxxx",
create_visualization: false,
visualization_id: null,
user_defined_limits: "{"twitter_credits_limit":0}",
import_extra_options: null,
original_url: "",
privacy: null,
cartodbfy_time: 0
`````

**Comment by rafatower** [comment]
I also made some tests and was not able to reproduce from UI. Please contact the user just in case he used the API directly.

**Comment by iriberri** [comment]
Already asked for more info :)

**Comment by iriberri** [comment]
The user just let us know that using the same duplicate button is now working as expected. :/ Have we done any temporal change there?

**Comment by rafatower** [comment]
not that I know

**Comment by iriberri** [comment]
I think I'm closing. I'll keep an eye on this, but not even the same user is able to do this know... My attempts didn't work neither. Reopen if you think the opposite.
