### ISSUE TITLE
Update link from the "Advanced map styling with CartoCSS" dialog

### ISSUE THREAD

**Issue by csobier** [CartoDB/cartodb#5817]
From the CartoCSS Editor (accessible from the CartoDB sidebar of the Map View), there is a tooltip in the "Advanced map styling with CartoCSS" dialog, that opens a github page to Mapbox Carto documentation.

Please re-direct the link to our own, internal documentation for CartoCSS  "[Customizing Maps with CartoCSS](http://docs.cartodb.com/cartodb-editor.html#customizing-maps-with-cartocss)". We describe the CartoCSS properties and values from our own Docs site now.

![image](https://cloud.githubusercontent.com/assets/13319925/10200042/1027038c-6772-11e5-92a3-58dc9c438661.png)

@saleiva , I am tagging you so that you can assign accordingly.
@axh, also tagging Andrew since he is excited about all things CartoCSS :-)

**Comment by viddo** [comment]
Solved by #5928
