### ISSUE TITLE
Fill in the table_name option for (sub)layers of "layergroup" layers

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#5819]
CartoDB.js needs to start using the SQL API (to change the way layers are visualized) and we need to know the name of the table to generate some queries.

For some reason the `table_name` option of (sub)layers inside a `layergroup` layer is empty:

```
{
  "type": "layergroup",
  "options": {
    "user_name": "pabloalonso",
    "maps_api_template": "https://{user}.cartodb.com:443",
    "sql_api_template": "https://{user}.cartodb.com:443",
    "tiler_protocol": "http",
    "tiler_domain": "cartodb.com",
    "tiler_port": "80",
    "sql_api_protocol": "http",
    "sql_api_domain": "cartodb.com",
    "sql_api_endpoint": "/api/v2/sql",
    "sql_api_port": 80,
    "filter": "mapnik",
    "layer_definition": {
      "stat_tag": "d29f9a84-5546-11e5-815b-0e9d821ea90d",
      "version": "1.0.1",
      "layers": [
        {
          "id": "1d306046-69ce-44a5-ad10-7ebd0cb6e2ec",
          "parent_id": null,
          "children": [],
          "type": "CartoDB",
          "infowindow": {},
          "tooltip": { ... }
          "legend": {},
          "order": 1,
          "visible": true,
          "options": {
            "sql": "select * from untitled_table_7",
            "layer_name": "waduslayer",
            "cartocss": "...",
            "cartocss_version": "2.1.1",
            "interactivity": "cartodb_id",
            "table_name": "\"\"."
          }
        }
      ]
    },
    "attribution": "attribution11"
  }
}
```

cc// @javisantana @rochoa

**Comment by javisantana** [comment]
Why do you need it? isn't the source the sql (query attribute) ?

**Comment by alonsogarciapablo** [comment]
True!

**Comment by alonsogarciapablo** [comment]
The problem with that attribute (`sql`) is that it might contain some sql that was generated by a wizard (eg: cluster). In these circumstances it doesn't make sense to use that `sql` as the source :(. The tiler needs the whole thing, but perhaps we could split it into two attributes in the viz.json (like `sql_wrapper` and `sql`)... What do you think?

**Comment by alonsogarciapablo** [comment]
It might not make sense once we move all the logic related to wizards to CartoDB.js, but in the meantime I think we need to differentiate the `sql` from the `sql_wrapper`.
