### ISSUE TITLE
Display error if there's an existing user with an invitation email

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#5821]
Current code at `4882-Invite_users_to_your_organization` triggers a 400 error with this body if invitation contains existing user emails:
`{"errors":{"users_emails":["Existing user for central-user-1@nonono.com"]}}`

UI displays a generic error, but should inform the user about the problem.

Response can be changed if needed.

**Comment by xavijam** [comment]
Already implemented
