### ISSUE TITLE
URL importer download: TypeError: can't convert nil into String 

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#5822]
https://github.com/CartoDB/cartodb/blob/master/services/importer/lib/importer/downloader.rb#L387

GDELT API Syncs are failing due to this error, their URL has the shape:

`http://api.domain.org/api/v1/gkg_geojson?QUERY=Some%20Name&TIMESPAN=1440&OUTPUTFIELDS=url,name,sharingimage`

**Comment by iriberri** [comment]
SB/6818881 & SB/6818787

**Comment by iriberri** [comment]
In the import error, it's throwing the exception from https://github.com/CartoDB/cartodb/blob/master/services/importer/lib/importer/downloader.rb#L306

````
["/home/ubuntu/www/production.cartodb.com/releases/20151001103137/services/importer/lib/importer/downloader.rb:306:in `extname'", "/home/ubuntu/www/production.cartodb.com/releases/20151001103137/services/importer/lib/importer/downloader.rb:306:in `name_with_extension'", "/home/ubuntu/www/production.cartodb.com/releases/20151001103137/services/importer/lib/importer/downloader.rb:285:in `name_from'", "/home/ubuntu/www/production.cartodb.com/releases/20151001103137/services/importer/lib/importer/downloader.rb:250:in `block in download_and_store'"
````

**Comment by ztephm** [comment]
Happening for S/B 6810994 for sync table.

**Comment by gfiorav** [comment]
@ztephm Thanks for helping!

We are now deploying a fix for this issue :smile:

**Comment by iriberri** [comment]
SB/6818881 & SB/6818787 notified, @ztephm please manage the 6809972 & 6810994 :-) :revolving_hearts:

**Comment by ztephm** [comment]
Notified 6809972 & 6810994 @iriberri , thanks for the fast work @gfiorav !
