### ISSUE TITLE
Release CartoDB Core API as npm package?

### ISSUE THREAD

**Issue by ericsoco** [CartoDB/cartodb#5828]
npm and browserify/webpack is an increasingly powerful and convenient way to build web applications, both for client and server-side. It would be great to see CartoDB Core released as an npm package.

That would allow developers to maintain dependencies in a cleaner way than having to add scripts to index.html. Perhaps more importantly to CartoDB, it would make it possible to write other npm packages that leverage CartoDB. For example, [this PR](https://github.com/PaulLeCam/react-leaflet/pull/78) to `react-leaflet` can't really be pulled into the repo very easily without a simple way to add the CartoDB dependency, nor can it be easily distributed on its own (for the same reason).

Ideally, application developers using CartoDB Core as an npm package could do this:

`npm install cartodb-core`

and then in `fileThatNeedsCarto.js`:

`var cartoDBCore = require(‘cartodb-core’);`
`var Tiles = cartoDBCore.Tiles;`

or, ES6-style:
`import { Tiles } from ‘cartodb-core’`

**Comment by srhise** [comment]
+1

**Comment by javisantana** [comment]
are you talking about cartodb.js? We are working on it for the next version v4, this is the right repository https://github.com/cartodb/cartodb.js
