### ISSUE TITLE
Add copy and paste functionality for the annotations

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#5829]
For windows and mac.

1. Select annotation
2. Copy
3. Paste

The result should be a new copy of the overlay, so it's basically a shortcut for the duplication functionality.

**Comment by xavijam** [comment]
Closed right?

**Comment by mbforr** [comment]
@javierarce is this merged?

**Comment by javierarce** [comment]
@mbforr: yes :)

**Comment by mbforr** [comment]
Fantastic!

On Wed, Oct 14, 2015 at 9:41 AM, Javier Arce <notifications@github.com>
wrote:

> @mbforr <https://github.com/mbforr>: yes :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/5829#issuecomment-148052420>.
>



-- 
*Matt Forrest*
Account Manager

*CartoDB*
201 Moore St, Brooklyn, NY, 11206, USA
T: (612) 325-8470 Skype: mbforr
W: www.cartodb.com

Live sessions to learn CartoDB <http://cartodb.com/webinars/>
