### ISSUE TITLE
Closing the search on Data Library redirects you to "Your Dataset"

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#5841]
### Steps to reproduce:
1. Go to your dashboard
2. Go to Data Library tab
3. Search something
4. Click "x" button on the right side.

![test](https://cloud.githubusercontent.com/assets/596509/10243751/049d040a-68fb-11e5-94a5-876336cc01f0.gif)

That button should redirect to the previous state, **"Data Library"** instead of **"Your Datasets"**

**Comment by xavijam** [comment]
The search is generic, it doesn't search only in one section, that's the reason why it doens't go back to data library.
