### ISSUE TITLE
Upgrade gdal extension in python_requirements.txt

### ISSUE THREAD

**Issue by hsato42** [CartoDB/cartodb#5847]
I am seeing the following error while trying to run `pip install -r python_requirements.txt`

```bash
extensions/osr_wrap.cpp:3727:59: error: cannot convert ‘const char*’ to ‘const char* const*’ for argument ‘2’ to ‘OGRErr OSRImportFromOzi(OGRSpatialReferenceH, const char* const*)’
        return OSRImportFromOzi( self, datum, proj, projParms );
                                                              ^
   extensions/osr_wrap.cpp:3728:3: warning: control reaches end of non-void function [-Wreturn-type]
      }
```

it goes away after I change the python extension to [gdal 2.0.1](https://pypi.python.org/pypi/GDAL/2.0.1)

please, fix-it.

**Comment by hsato42** [comment]
here is the build code https://github.com/CartoDB/omnibus-cartodb/blob/cdb/config/software/cartodb-python-requirements.rb

**Comment by hsato42** [comment]
spoke with @rafatower and will try compiling statically ogr2ogr2 from github/cartodb/gdal#upstream branch and use gdal 1.11 for runtime and devel otherwise. /cc

**Comment by rafatower** [comment]
For the record, some RH source packages that can be useful:
- http://rpm.cartodb.net.s3.amazonaws.com/el6/gdal-1.11.1-1.el6.src.rpm
- http://rpm.cartodb.net.s3.amazonaws.com/el6/ogr2ogr2-2.1.0%2Bsvn.29639-1.el6.src.rpm
