### ISSUE TITLE
fixed title not showing when custom sql is applied

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/cartodb#5850]
Steps to recreate:

1. build a map
2. apply custom query (then the `create dataset from query or clear view` appears)
3. click 'fixed title' in the options doodad
4. See a title below the sql query box:

<img width="648" alt="screen shot 2015-10-02 at 14 56 41" src="https://cloud.githubusercontent.com/assets/1041056/10258759/d0d89b46-6915-11e5-841f-257484eb098a.png">

**Comment by xavijam** [comment]
It will be fixed in new editor, so closing :).
