### ISSUE TITLE
"Looks like this map no longer exists"

### ISSUE THREAD

**Issue by auremoser** [CartoDB/cartodb#5851]
### Context
Checking in on this for one of our ambassadors who is teaching a class next week. He created a demo account for the workshop and now when he hits "publish" to get the short link, his maps don't render because of an issue that seems to be incorrect.
For reference, his account is `gijc15`, a free account.

### Procedure

1. Create map - 2 layers
2. Set privacy to public (free account)
3. Select "Publish"
4. Copy short link "http://cdb.io/1OaBrtI"
5. Try to render map

![error](https://cloud.githubusercontent.com/assets/1559703/10271052/090287da-6ad2-11e5-8508-b426ba8adaaa.gif)

### Expected Result

Map renders (changes to "https://gijc15.cartodb.com/viz/cea576ac-699a-11e5-8a8b-0ea31932ec1d/public_map" in a new tab).

### Current Result

Map gives this error:
`Looks like this map no longer exists or is set as private`
Though, it is not set to private and it definitely exists.

Not sure how to fix this for him, it only works this way on one of his maps and I've never seen this error before.

Thanks for reading!

**Comment by saleiva** [comment]
Pretty weird one... @Kartones any idea?

**Comment by Kartones** [comment]
Well, something causes an error each time you try to enter the map. I'd have to debug more in depth, but maybe support or solutions have seen this error (as I think I've seen this error message before...). @iriberri any clue?

```
ActionView::Template::Error: PG::Error: ERROR: relation "public" does not exist
LINE 1: SELECT COUNT(*) AS "count" FROM "public" AS "besucher_alle" ...
^

... 23 non-project frames
24
File "new_privacyapp/models/table.rb", line 1361 in actual_row_count
25
File "new_privacyapp/models/table.rb", line 743 in rows_counted
26
File "new_privacyapp/views/admin/visualizations/public_map.html.erb", line 192 in block (2 levels) in _app_views_admin_visualizations_public_map_html_erb___2075232611371725626_75233040
27
File "new_privacyapp/views/admin/visualizations/public_map.html.erb", line 165 in each
28
File "new_privacyapp/views/admin/visualizations/public_map.html.erb", line 165 in block in _app_views_admin_visualizations_public_map_html_erb___2075232611371725626_75233040
... 4 non-project frames
33
File "new_privacyapp/views/admin/visualizations/public_map.html.erb", line 14 in _app_views_admin_visualizations_public_map_html_erb___2075232611371725626_75233040
... 30 non-project frames
64
File "new_privacyapp/controllers/admin/visualizations_controller.rb", line 255 in block (2 levels) in public_map
... 2 non-project frames
67
File "new_privacyapp/controllers/admin/visualizations_controller.rb", line 254 in public_map
```

**Comment by iriberri** [comment]
This happened last week during the redis downtime we had. Basically, the privacy of the table was stuck incorrectly and the permissions were incorrect, so the map was showing that error when you shared it.

Re-setting the table privacy made everything work again correctly. Not sure if this is the same issue, though. We could review by checking the permissions of the tables/map.

**Comment by saleiva** [comment]
last week? The issue is open 15 hours ago... so...

**Comment by iriberri** [comment]
The map could have been blocked since Friday independently of when this issue was created, but just reviewed that the user doesn't even have private tables.

This is caused by the table name starting by an underscore: https://github.com/CartoDB/cartodb/issues/5843

It is provoking the SQL query to behave incorrectly using an alias:

`SELECT COUNT(*) AS "count" FROM "public" AS "besucher_alle"`

Notice that the table is called _besucher_alle. As the table loses the link with the real table from which the data comes due to the "_" issue, the map does no longer make sense for the system.
