### ISSUE TITLE
Organization display name

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#5853]
Organizations have both `name` (identifier) and `display_name`, but currently you can't change it. I think `name`, the identifier, used for subdomains, should be read-only, but an owner should be able to change the display name, probably at current `name` field at organization settings page.

That display name should also be used for user-faced information, such as signup pages or emails.

What do you think, @saleiva ?

cc @xavijam

**Comment by xavijam** [comment]
@juanignaciosl, I feel it is available right now.

<img width="550" alt="screen shot 2015-10-06 at 19 15 22" src="https://cloud.githubusercontent.com/assets/132146/10316252/a7d62fdc-6c5e-11e5-9c1e-1307aab9c8bd.png">

**Comment by xavijam** [comment]
Ah wait, the input is there but it is not being saved, ok, bug.
