### ISSUE TITLE
Set up name for custom basemaps

### ISSUE THREAD

**Issue by jsanz** [CartoDB/cartodb#5855]
It'd be great to be able to rename the custom basemaps defined on the editor, as the thumbnail is not enough and sometimes the name guessed by CartoDB is not meaninful enoguh leaving it as `Custom basemap XX`.

![2015-10-05_12 45 19_selection](https://cloud.githubusercontent.com/assets/188264/10278627/012e77ca-6b5f-11e5-95c2-357ef1fdb4f8.png)

**Comment by xavijam** [comment]
We will try to manage this enhancement in the new editor :).
