### ISSUE TITLE
[Metrics] Track map creation with Segment

### ISSUE THREAD

**Issue by jmartinter** [CartoDB/cartodb#5870]
Track the following events on Cartodb and send this information to segment.com:
 - Created new dataset
 - Created new map

In order to identify each user, will use his user_id from the box. No user identify is required from Cartodb, as it will managed exclusively from Central.

Event tracking is managed as a separate task launched from resque.

At this time, we are not limiting the integration from segment.

cc'ed @xavijam

**Comment by xavijam** [comment]
\o/
