### ISSUE TITLE
[Metrics] Track 'Scored trending map' event on segment

### ISSUE THREAD

**Issue by jmartinter** [CartoDB/cartodb#5871]
Track the event 'Scored trending map' every time user appears on trendy map list and send this information to segment.com.

In order to identify each user, will use his user_id from the box. No user identify is required from Cartodb, as it will managed exclusively from Central.

Event tracking is managed as a separate task launched from resque.

Required event custom properties:
- map id
- map name
- number of mapviews

At this time, we are not limiting the integration from segment.

cc'ed @ethervoid  @xavijam 
At present I adding the segment libraries to cartodb. When done, they can be used to deliver this event.

**Comment by jmartinter** [comment]
Done by https://github.com/CartoDB/cartodb/pull/6063

**Comment by xavijam** [comment]
\o/
