### ISSUE TITLE
Multilayer formats should create a multilayer map at the end of the importation

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/cartodb#5880]
Multilayer formats or compressed files (zip, kml, etc) should create a multilayer map once the import ends.

For example: If we have a KML with 5 different layers we should and a user wants to create a map with that file we should create a multilayer map at the end of the import process.

* [ ] Create multilayered map from multilayer file
* [ ] Create multilayered map from multilayer datasource source

//cc @rafatower

**Comment by ethervoid** [comment]
One question: We have to put a "pretty" name for the map but we have multiple layers. What should we put?

**Comment by rafatower** [comment]
the name of the url/file?

**Comment by rafatower** [comment]
Assigning to @gfiorav as he is taking care of this.
