### ISSUE TITLE
Map thumbnails are not generated due to GMaps basemaps lack of urlTemplate

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#5881]
**Description:** 
  In a map created with Google Maps and a Google basemap, the thumbnail generation is failing because of the error: `Missing mandatory "urlTemplate" option`. An example can be found here: https://carlatest.cartodb.com/api/v1/map/static/named/tpl_1b539d26_638d_11e5_8406_42010a14cb63/300/170.png

In the [viz.json here](https://carlatest.cartodb.com/api/v2/viz/2ab88a1e-6c2b-11e5-850e-42010a14cb63/viz.json) you can see that GMaps basemaps don't have a urlTemplate parameter and we are expecting it, so the request fails with a 400 error:

![image](https://cloud.githubusercontent.com/assets/1730320/10310474/6599df54-6c42-11e5-898f-f7f84bfed855.png)

**Comment by iriberri** [comment]
@rochoa @Kartones @zenitraM

**Comment by iriberri** [comment]
By the way, if you want to play, you can use the `carlatest` account.

**Comment by Kartones** [comment]
Ok, so the tastk is to just skip the basemap layer for gmaps ones, right?

**Comment by rochoa** [comment]
In general for any http layer that does not have `urlTemplate`.

**Comment by Kartones** [comment]
:+1:

**Comment by Kartones** [comment]
@iriberri Working fine now. People that have a broken static map preview will have to refresh their named map (just enter it, zoom in + out or something like that), but afterwards the new one is generated just skipping the http layer without urlTemplate

**Comment by iriberri** [comment]
Thank you so much, @Kartones! I'm going to notify the users.
