### ISSUE TITLE
Add option to set min/max zoom in CartoDB Editor

### ISSUE THREAD

**Issue by makella** [CartoDB/cartodb#5891]
It would be nice if there was the option to set the min and max zoom levels of a map via the Editor.  Right now inside the Editor the only way to do it is on a layer's CartoCSS.  Outside the Editor using cartodb.js. Both of these options are slightly more advanced so an easy to set option in the Editor would be awesome!

In the Editor even if a user sets a min/max zoom using CartoCSS, but chooses one of the predefined basemaps, the map will still zoom with no data showing. For example, in the map below I set the symbology to stop drawing at zoom 5 but you can still zoom into the map:
http://cdb.io/1KYg1gU

From a cartographic perspective, if a user hasn't done zoom dependent styling on their map, the map will start to break down at zoom levels that styling hasn't been applied.

**Comment by fnorf** [comment]
Has this been implemented?
