### ISSUE TITLE
Search on organization users page broken

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#5897]
STR:
- Go to organization users page
- Search something
- Click (x) to remove the search

Expected results:
- Users filtered by search
- (x) to remove search filtering

Actual results:
- No filtering applied
- Close throws a JS error, `Uncaught TypeError: this._cleanSearch is not a function`

Something must have changed recently, last time (~1,5w ago) I checked this worked. :disappointed:

**Comment by viddo** [comment]
Like I wrote on #5781 this should be solved by removing this duplicated code in favor of the new generic search view:
> Note that with these changes and the PagedSearchView we could/should DRY the organization users view too, and thus remove the redundant .OrganizationSearch and view code that's already solved, although I'd like to that in an isolated PR

@xavijam but considering the fix was [quite simple](214514cc96163603fe0b464392bd6ab853e01151) (will be fixed once #5781 is merged), I'd say we leave that for the future/next time we touch these parts, OK with you?

**Comment by xavijam** [comment]
:+1:
