### ISSUE TITLE
use more distinctive colors for small numbers of categories

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/cartodb#5912]
Category maps with two categories should have 'opposite' colors instead of similar colors to highlight the difference. Right now if we have two categories, we get light blue and dark blue, which don't seem very different visually. 

We should have similarly 'different' colors for each additional new category... should be something like:

* two categories: [red,blue](http://colorbrewer2.org/?type=qualitative&scheme=Set1&n=2)
* three: [rgb](http://colorbrewer2.org/?type=qualitative&scheme=Set1&n=3),
* four: [rgbp](http://colorbrewer2.org/?type=qualitative&scheme=Set1&n=4)
* five: ...

ColorBrewer's pastels don't natural order like that, but [these do](http://colorbrewer2.org/?type=qualitative&scheme=Set1&n=9) but don't offer 11 categories like we currently offer.

cc @andrewbt @makella

**Comment by saleiva** [comment]
Closing since this is being fixed in the new version of the editor. Thanks! :)
