### ISSUE TITLE
"No data available" for published map's infowindow when editor map's infowindows show data

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#5917]
@xavijam cc: @andrewbt 

please ref: https://narberthborough.cartodb.com/viz/75366f14-1f61-11e5-8318-0e9d821ea90d/map

User has enabled click infowindows for the second layer down from top of layer stack. Infowindows for top layer are not enabled.

EXPECTED:
Infowindows will show data in published map.

HAPPENING:
Editor shows:
![screen shot 2015-10-09 at 4 42 26 pm](https://cloud.githubusercontent.com/assets/1779444/10405093/c061193e-6ea4-11e5-8198-7261cecb80b9.png)

Published map shows:
![screen shot 2015-10-09 at 4 43 24 pm](https://cloud.githubusercontent.com/assets/1779444/10405125/e809023a-6ea4-11e5-8b03-5d2c0324a24e.png)

Sorry if I'm misunderstanding expected behavior...my test shows information from click infowindows enabled on second layer from top in both published and editor versions:
http://cdb.io/1Zm8FLI

**Comment by xavijam** [comment]
It is a bug in CartoDB.js, I'll link this one to the CartoDB.js ticket.

**Comment by xavijam** [comment]
Possibly related -> https://github.com/CartoDB/cartodb/issues/5858

**Comment by smetrick** [comment]
got it thanks. Seems to be working now. Didn't realize I was doing something wrong.

**Comment by andrewbt** [comment]
@smetrick Hey Sean! Good to see you here :) I think the "at fault" still rests with us though, not you! Looks like we're making progress so hopefully we'll have some of these fixes deployed to CartoDB.com soon!

**Comment by whanco** [comment]
Hello 
This Bug has been solved?
I'm with the same problem.

**Comment by jsanz** [comment]
@whanco it should, can you please provide more details?
