### ISSUE TITLE
When interacting with a map it randomly zooms out to z32

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#5918]
This was reported by Simon. Will try to collect more information.

**Comment by iriberri** [comment]
It seems that he's not able to reproduce the issue anymore but he suspects this happened when adding a new layer. He's using a blank color basemap.

I have tried to reproduce the issue by adding a layer whose bounding box is really small (to see if the map was recentered after its addition) but couldn't reproduce.
