### ISSUE TITLE
Allow duplicate emails in user accounts

### ISSUE THREAD

**Issue by mnquintana** [CartoDB/cartodb#5919]
### Use case 

We have a lot of CartoDB accounts with different levels of permissions / access for managing different tables for the same project. However, the unique email address requirement when creating new accounts has turned out to be a real hindrance - in our case, we have only one person managing all these accounts, and we've had to set up a lot of "shell" email addresses to even be able to create these accounts at all. We want to be able to use one master email for all of these accounts.

### Proposal

Don't validate uniqueness for email addresses - allow there to be duplicate emails to prevent email management headaches like we've had when dealing with multiple user accounts for the same project.

The one notable consequence of this is that this would mean that users would have to login with their username, rather than their email.

:bow:

**Comment by viddo** [comment]
Internally we use a lot of `name+tag@mail.com` (aka [sub-addressing](https://en.wikipedia.org/wiki/Email_address#Sub-addressing)) to have multiple accounts tied to a single email, is there some reason why you can't use that?

**Comment by xavijam** [comment]
Yep, that would be a good workaround because for the moment we can't provide any other solution. Right now it is impossible to use the same email for several accounts and I feel we don't have this in our roadmap right now. Thanks for your feedback!

**Comment by mnquintana** [comment]
@viddo Ah thanks! I forgot about that trick - works well enough for us. :smile:

**Comment by viddo** [comment]
great to hear! ^_^
