### ISSUE TITLE
when changing value of id column it is always saves as cartodb_id

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#5921]
steps to reproduce:

- create a table
- add an "id" column
- change value in a row for "id" column

expected behaviour:

- save value as introduced

actual behaviour

- value changes to value in "cartodb_id" and saves after

![viet](https://cloud.githubusercontent.com/assets/36676/10449269/c509314c-7192-11e5-9e1c-bbee488e3861.gif)

**Comment by michellechandra** [comment]
S/B 8402821

**Comment by xavijam** [comment]
It is a backend bug :|

**Comment by xavijam** [comment]
cc @CartoDB/backend

**Comment by javitonino** [comment]
Fixed in #8419 some days ago, but forgot to close the ticket.

**Comment by xavijam** [comment]
\o/

On Jul 11 2016, at 10:24 am, Javier Torres &lt;notifications@github.com&gt;
wrote:  

> Fixed in
[#8419](https://github.com/CartoDB/cartodb/pull/8419&r=cmVwbHkrMDAwMjA0MzJkMGE4ODRmNzNjNzkyMTgxZDRlMTQzMDE1OTc0OThhMmIzZmFjYzE3OTJjZjAwMDAwMDAxMTM5YjE5YzM5MmExNjljZTA2OWZiMDI2QHJlcGx5LmdpdGh1Yi5jb20=)
some days ago, but forgot to close the ticket.

>

> —  
> You are receiving this because you were assigned.  
> Reply to this email directly, [view it on
GitHub](https://github.com/CartoDB/cartodb/issues/5921#issuecomment-231671140&r=cmVwbHkrMDAwMjA0MzJkMGE4ODRmNzNjNzkyMTgxZDRlMTQzMDE1OTc0OThhMmIzZmFjYzE3OTJjZjAwMDAwMDAxMTM5YjE5YzM5MmExNjljZTA2OWZiMDI2QHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the
thread](https://github.com/notifications/unsubscribe/AAIEMjFQf1HMkUxzDx1hNHQ0hL5UrE1qks5qUf3DgaJpZM4GNqx2&r=cmVwbHkrMDAwMjA0MzJkMGE4ODRmNzNjNzkyMTgxZDRlMTQzMDE1OTc0OThhMmIzZmFjYzE3OTJjZjAwMDAwMDAxMTM5YjE5YzM5MmExNjljZTA2OWZiMDI2QHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notifications/beacon/AAIEMrqcbyuKJpAwRm8t_ESk4Gc887IDks5qUf3DgaJpZM4GNqx2.gif)
