### ISSUE TITLE
Dashboard/Twitter cards previews not using CDN

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb#5926]
I found some places using previews with named maps fixed URLs that are not using a CDN to request the images:

 1. `https://{user}.cartodb.com/dashboard` previews are using fixed URLs but not CDN ones.
 1. `https://{user}.cartodb.com/viz/{viz_id}/public_map` twitter card `meta name="twitter:image"` URL is using fixed URL but not CDN one.

Related to https://github.com/CartoDB/cartodb/issues/5637

**Comment by Kartones** [comment]
2) is a config issue, I don't know why but I was asked to implement config `maps_api_cdn_template` value [for cdn'ing those calls](https://github.com/CartoDB/cartodb/blob/master/lib/static_maps_url_helper.rb#L38) but then it isn't used (just checked live config).
If I set something in local twitter cards on public/embeded/etc. maps get CDN-provided url.

/cc @javisantana @luisbosque as this falls under their umbrella, just add the proper CDN path (with `{protocol}` and `{user}` placeholders and it'll work.


(checking 1) now)

**Comment by Kartones** [comment]
Branch: `5926-cdn-dashboard-map-previews`

**Comment by Kartones** [comment]
[PR](https://github.com/CartoDB/cartodb/pull/6025) fixes scenario 1) , although I really dislike that seems we created a config param for nothing, and the logic to generate the static map urls is replicated at [frontend](https://github.com/CartoDB/cartodb/pull/5651/files#diff-53f7257bfbad7653283994917c16e2b2R13) and [backend](https://github.com/CartoDB/cartodb/blob/master/lib/static_maps_url_helper.rb)

**Comment by xavijam** [comment]
In frontend we need it because items are not rendered in a standard rails template, so we have to create the url ourselves.

**Comment by xavijam** [comment]
And of course, backend logic is needed for those static cases, like in the meta tags of the public pages. :S

**Comment by Kartones** [comment]
Assigning to @luisbosque for the `maps_api_cdn_template` configuration as my CDN knowledge is nearing `nil`

**Comment by Kartones** [comment]
After talking with @luisbosque doesn't makes sense the `maps_api_cdn_template` config param (that was never used) so I will rewrite code to use `cdn_url` instead for twitter cards stuff too.
