### ISSUE TITLE
CartoCSS color picker doesn't appear in Safari v9.0 (10601.1.56.2)

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#5934]
@xavijam
Ref: S/B 6955389

EXPECTED:
When you click on a hex number in Editor's CartoCSS, the color picker panel will open.

HAPPENING:
The hex number shows a hand icon, but when you click on it cursor turns into text cursor instead of color picker panel opening.

I tested for polygon-fill, marker-fill, marker-line-color, all have same text-cursor behavior.

A test: http://cdb.io/1zpBpdb

**Comment by xavijam** [comment]
I'll take a look
