### ISSUE TITLE
data-library: implement endpoint for dynamic tags filter

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#5946]
<img width="284" alt="screen shot 2015-10-15 at 10 58 53" src="https://cloud.githubusercontent.com/assets/36676/10509868/0517f4f0-7330-11e5-925e-5a4bcc5edd5e.png">

**Comment by ethervoid** [comment]
Here you need an endpoint that give you a list of unique tags extract from all the common-data visualizations?

**Comment by matallo** [comment]
yeppers

**Comment by ethervoid** [comment]
No endpoint need using the explore api you could get the tags. Here is the request

http://common-data.cartodb.com/api/v2/sql?q=SELECT%20unnest(visualization_tags)%20as%20tags%20FROM%20visualizations%20WHERE%20user_id%20=%20%27891c95dc-b1f3-47d2-ace0-12651259b811%27%20AND%20visualization_tags%20IS%20NOT%20NULL%20and%20visualization_type%20=%20%27table%27%20group%20by%20tags

**Comment by matallo** [comment]
BOOM

On Fri, Oct 23, 2015 at 12:26 PM, Mario de Frutos <notifications@github.com>
wrote:

> Reopened #5946 <https://github.com/CartoDB/cartodb/issues/5946>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/5946#event-443665170>.
>



-- 
*Carlos Matallín*
UI developer

*CartoDB—Map Your World's Data*
C/ Eloy Gonzalo, 27, 3, 28010, Madrid, Spain
T: +34911165823
W: www.cartodb.com

Live sessions to learn CartoDB <http://cartodb.com/webinars/>
