### ISSUE TITLE
Multilayer import warning

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#5947]
Related PR: https://github.com/CartoDB/cartodb/pull/5933

![create - file importing warning](https://cloud.githubusercontent.com/assets/596509/10510486/9a496754-7333-11e5-9f42-88a0cb279a3b.png)

@saleiva u like it?
/cc @gfiorav

**Comment by gfiorav** [comment]
Looks great @josecruz!

Just a few things:

* The max layers change with the account type, so the message should tell you that _you_ have a limit of 4 (or whatever) layers
* We do import the datasets, it's just that we don't add them as layers. So the title shouldn't say "Unable to import"
* Id change the message to some thing like "Since you have a limit of 4 layers per map, the following layers were not added to the map:..."

**Comment by saleiva** [comment]
That list... Can you try different methods for showing the affected data?

**Comment by josecruz** [comment]
Idk if we can use this template (because the limit of files that can appear on that list):
![create - file importing warning](https://cloud.githubusercontent.com/assets/596509/10548289/cf59c964-7439-11e5-9a06-06eadef56dce.png)


For copy maybe @CartoDB/copywriters can bring us some help.

**Comment by csobier** [comment]
Suggested edits: 
original: "We have 4 layers limit for each map"
edited: "There is a 4 Layer limit for each map"

original:  "Due you can only add 4 layers per map, the following layers were imported as datasets:"
edited:  "You have reached the maximum number of Layers allowed for this map. The following Layers were imported as datasets."

**Comment by saleiva** [comment]
Doesnt work I think.... Lets see this on monday

**Comment by josecruz** [comment]
Thanks @csobier for the copy!! Tried to reuse in this version:
![create - file importing warning](https://cloud.githubusercontent.com/assets/596509/10573944/42a505da-7653-11e5-8b81-6aaba7ed66e8.png)

Better?

**Comment by csobier** [comment]
Sure, that works.

**Comment by saleiva** [comment]
Forget this approach. Doesn't make sense.

**Comment by saleiva** [comment]
![create - file importing copy 2](https://cloud.githubusercontent.com/assets/132149/10580379/959b6f48-767d-11e5-9041-870c205ba643.png)

**Comment by saleiva** [comment]
dunno who should help with the markup. It's easy enough to do it yourself I guess

**Comment by gfiorav** [comment]
@saleiva Ok. I'm not an expert in Backbone to say the least... I hope I'm not messing models up too much. It would help if someone could review it as soon as I'm done with it.

**Comment by rafatower** [comment]
@gfiorav we can get someone with more FE experience to review it when done.

Thank you guys!

**Comment by gfiorav** [comment]
OK @saleiva this is how it looks:

<img width="1280" alt="screen shot 2015-10-19 at 17 46 25" src="https://cloud.githubusercontent.com/assets/4222826/10582728/8b83c1fc-7689-11e5-9e12-6154c359acc1.png">

There are two different things from your proposal:
1. The continue button text is lighter (the default color in the error pages)
2. Our pricing info is linked to "Upgrade your account"

If you like it were done here. So, please, DR.
