### ISSUE TITLE
Number column doesn't show green numbers on sync

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#5951]
Styling issue for you @xavijam 
S/B 6981503

Number column shows green numbers when imported from local. On sync it shows gray numbers. This is misleading some clients to think that type-guessing is incorrect.

## Context
When I imported [this test](https://team.cartodb.com/u/stephaniemongon/tables/test3) from local the "test3" number-type column green styling looks proper. 

When I imported [this same test file](https://team.cartodb.com/u/stephaniemongon/tables/test3_1) as a sync table from GDrive, the "test3" column is number type, but is styled gray like it's a string. 

## Process

1. Save CSV containing a column with numbers in Google Drive
2. In CartoDB Datasets page click New dataset
3. Click Google Drive button & import test file, making sure type-guessing checkbox is checked.

## Expected result

Number-type column values will be styled green

## Current result

![screen shot 2015-10-16 at 11 58 19 am](https://cloud.githubusercontent.com/assets/1779444/10546642/38e50ffc-73fd-11e5-8663-e044efd2e5e0.png)

**Comment by xavijam** [comment]
We will review this in the next Editor iteration, so let me close it :).
