### ISSUE TITLE
Change generic error when importing more than 10 files

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#5957]
Right now, if a user imports a compressed file with more than 10 datasets, the importer fails generically. It would be nice if we could add an error with a specific error, specially now that we are adding the functionality of creating multilayered maps from a zip file.

Relevant code:
https://github.com/CartoDB/cartodb/blob/master/services/importer/lib/importer/runner.rb#L27
https://github.com/CartoDB/cartodb/blob/master/services/importer/lib/importer/runner.rb#L249-L261

```ruby
@importer_stats.timing('import') do
  unpacker.source_files.each_with_index { |source_file, index|

    next if (index >= MAX_TABLES_PER_IMPORT)
    @job.new_table_name if (index > 0)

    log.store   # Checkpoint-save
    log.append "Filename: #{source_file.fullpath} Size (bytes): #{source_file.size}"
    import_stats = execute_import(source_file, @downloader)
    @stats << import_stats

  }
end
```

**Comment by Kartones** [comment]
Sorry for the intrusion, but that's not 100% accurate. If more than 10 datasets are sent, it will only import the first 10 reported by the filesystem after unpacking the compressed file (this means it is not deterministic on which 10 out of N will import).

But at least when I coded this "multi-table import" it was importing successfully those 10 datasets and just skipping the rest, without any error...

**Comment by gfiorav** [comment]
@Kartones Thanks for the insight. We're discovering this as part of a smoke test session and we're trying to be fast, hence the lack of accuracy :stuck_out_tongue: 

We might try to use the new warnings in AMC v1.0 (imminent deploy) to notify this. It seems perfect since it doesn't stop the execution but the user has to know that some things weren't imported.

**Comment by Kartones** [comment]
Warnings upon import was inded the idea to "finish" this feature of uploading N tables but with a hard limit, but as required FE work was left undone. Any similar approach will be lovely
