### ISSUE TITLE
NoMethodError: undefined method `http_response_code' for DatasourceDownloader

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#5958]
Happens on Arcgis import

https://rollbar.com/vizzuality/CartoDB/items/8/occurrences/8327530991/

cc/ @rafatower @ethervoid

**Comment by rafatower** [comment]
Related to  https://github.com/CartoDB/cartodb/issues/5959

**Comment by ethervoid** [comment]
Fixed in https://github.com/CartoDB/cartodb/pull/5933
