### ISSUE TITLE
Arcgis connector broken when layer ID specified

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#5959]
Try to import this URL: https://maps.brgov.com/gis/rest/services/Governmental_Units/Police_District/MapServer/0

(where `/0` at the end represents "layer with ID = 0" afaik).

It fails with the following trace:
```
true: ogr2ogr output:          FAILURE:
Unable to open datasource `/tmp/imports/20151019-5524-1mqy3zy/6902800726' with the following drivers.
  -> PCIDSK
  -> JPEG2000
...
```

**Comment by rafatower** [comment]
See import with id: `e8040893-ab69-411f-8a7c-204563cafd64`

**Comment by ethervoid** [comment]
It was fixed in https://github.com/CartoDB/cartodb/pull/5933

![fixed_arcgis_2](https://cloud.githubusercontent.com/assets/741240/10607063/2a5246de-7737-11e5-9dd6-691fe4864381.png)

**Comment by rafatower** [comment]
thanks!
