### ISSUE TITLE
Buggy map remains if all of it's layer's datasets are removed at once

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#5967]
If you delete all the datasets forming the layers of a multilayered map at once, the map they belonged to is not deleted and can be accessed.

Steps to reproduce this:

1. Create a multilayered map with imported datasets
2. Delete all datasets making the layers of the map in one go (multiple selection)
3. Go to Maps and see a "phantom" map with no layers

<img width="1025" alt="screen shot 2015-10-20 at 12 32 31" src="https://cloud.githubusercontent.com/assets/4222826/10604904/fd7d276e-7727-11e5-9a08-0a7731816d6e.png">

**Comment by xavijam** [comment]
2. Delete all datasets making the layers of the map in one go (multiple selection)

From the dashboard you mean?

**Comment by xavijam** [comment]
cc @CartoDB/backend

**Comment by ethervoid** [comment]
Yes in the dashboard, but don't happen all the times. I'm going to check what is the common scenario.

**Comment by ethervoid** [comment]
After some search I've found the root cause of this problem. There aren't dependent-visualizations for that map when we are performing multilayer deletion so at the end of the delete process the "derived" visualization is not destroyed.

We don't have this problem when we delete the layers one by one, only when the user deletes all the layers at the same time.

We have to force the reload of the "dependant" and "non-dependant" visualizations in every deletion.

**Comment by ethervoid** [comment]
Ok I fix it reducing the number of parallel batch process to 1. 

Now is slower to delete the datasets (~2 seconds slower for 5 datasets) but I don't think the time to delete datasets here will be critical. The other solution implied to create a multipart deletion endpoint and it seems that in this [issue](https://github.com/CartoDB/cartodb/issues/1441) @javisantana said that we have to define this kind of work for all the endpoints in the platform so this change is to avoid the bug and is not a final solution. 

5 in parallel:

![captura de pantalla 2015-10-21 15 19 54](https://cloud.githubusercontent.com/assets/741240/10637697/4b540d56-7807-11e5-9392-7ced424bc27a.png)

1 in parallel:

![captura de pantalla 2015-10-21 14 09 25](https://cloud.githubusercontent.com/assets/741240/10637703/52f38366-7807-11e5-9f9a-128b27a712cc.png)

**Comment by xavijam** [comment]
cc @viddo

**Comment by xavijam** [comment]
Thanks @viddo \o/

**Comment by xavijam** [comment]
Thanks @viddo \o/
