### ISSUE TITLE
Search is toggled on in Mobile Preview Options but is not appearing

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#5969]
@xavijam

S/B 7020530

## Context
Search box doesn't appear in mobile map versions but users are able to toggle Search on in Options.

## Process

1. Create an Editor map in regular Desktop preview, with Search box toggled on in Options.
2. Click 'Preview Map' button, then click 'Mobile'
3. Click Options & you'll see Search box is still active & toggled on.

## Expected result

In Mobile Preview Search box option should be grayed out & inactive, like Share Options & Zoom Control are grayed out.

## Current result

Search box toggle is still active & on in Mobile Preview but Search box is not appearing on map, or  in expanded menu.

My test: http://cdb.io/1PhbgCp

![screen shot 2015-10-20 at 10 48 32 am](https://cloud.githubusercontent.com/assets/1779444/10611073/7a8845aa-7718-11e5-8196-ab7c87229060.png)

![screen shot 2015-10-20 at 10 48 21 am](https://cloud.githubusercontent.com/assets/1779444/10611079/7debc320-7718-11e5-8466-559bc82927c5.png)

**Comment by iriberri** [comment]
Just reviewed in my phone and indeed, the searchbox is not there. The option seems to be correctly set up at least in the viz.json:

https://team.cartodb.com/u/stephaniemongon/api/v2/viz/d9443318-62cf-11e5-be6c-0e853d047bba/viz.json
![image](https://cloud.githubusercontent.com/assets/1730320/10815487/b9eb94fc-7e2c-11e5-8777-b899e865e622.png)

**Comment by michellechandra** [comment]
S/B 7604251

**Comment by michellechandra** [comment]
S/B 7020530
S/B 7085259

**Comment by xavijam** [comment]
This is gonna change with the new cartodb.js components, so closing for now :).

**Comment by michellechandra** [comment]
hey @xavijam - another user is reporting this issue, do we have an update on this one? 

S/B: 9518753
