### ISSUE TITLE
source and attribution metadata from data library datasets are not copied when imported

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartodb#5970]
When a dataset from the data library is imported into user account, the metadata source and attribution is not imported with the table. The user has to add the source and attribution metadata manually and then refresh to see the attribution on the map.
**Steps:**

1- Import dataset from data library:

![data library](https://cloud.githubusercontent.com/assets/11177693/10613730/bc35c548-7756-11e5-8f74-e4f0bdc055df.png)

2- When the dataset is opened, the attributions and source metadata from the dataset are not copied on the map:

![screen shot 2015-10-20 at 17 58 14](https://cloud.githubusercontent.com/assets/11177693/10613563/0445fbf6-7756-11e5-8000-5cf70df2d7eb.png)

![no attribution on map](https://cloud.githubusercontent.com/assets/11177693/10613567/078c6e62-7756-11e5-86b1-50c733b2d44b.png)

3- The user have to add the attribution and source metadata manually with the "Edit metadata" option form the dataset, and once is added you have to refresh the dataset to see the attribution on the map:

![screen shot 2015-10-20 at 18 06 26](https://cloud.githubusercontent.com/assets/11177693/10613794/08586764-7757-11e5-8e1a-764ad6e33341.png)

![map with attribution](https://cloud.githubusercontent.com/assets/11177693/10613690/828b2e32-7756-11e5-9db4-1ef55adb3cf3.png)

I've been checking the CartoDB metadata and I have realised that the **user_tables** schema doesn't have the attributes source and attribution.

**Comment by iriberri** [comment]
cc @ethervoid

**Comment by ethervoid** [comment]
I'll take a look to it. Assign it to me

**Comment by iriberri** [comment]
The attribution and source parameters are stored in the canonical visualization of the Data Library sources. I don't know how this works, but if we're just recreating the user_table there's where we are missing it. :-) Not super urgent, but I think this is important because of the focus to data and attributions we are doing (now CartoDB.js adds data attributions directly to the maps).

**Comment by juanignaciosl** [comment]
Fixed: #6897.
