### ISSUE TITLE
Georeferencing English text

### ISSUE THREAD

**Issue by stevage** [CartoDB/cartodb#5971]
These two labels shouldn't be capitalised like this, and the second is poor English:

>In Which Column Are Your Region Names Stored?

--> Which column contains region names?

> If Your Column Isn't Country Data, Where's It?

--> Which column contains country names (if applicable)?

or 

--> If those regions aren't countries, which country are they in?

(At very least change "Where's it?" to "Where is it?" - the former is very un-idiomatic)

> Select column or type it

--> Select column or type country name

**Comment by stevage** [comment]
Heh, I tried to find an explanation of why "Where's it" is not good English, then this happened: http://english.stackexchange.com/questions/281461/why-is-wheres-it-grammatically-incorrect

**Comment by viddo** [comment]
Thx for reporting! Will fix this eventually
cc @CartoDB/copywriters

**Comment by csobier** [comment]
I know we recently edited the *Georeference /  Lon/Lat Columns* text, I'm trying to find that issue for you as a reference...  Please edit the *Georeference / Admin Regions*  text as follows:

original: "Select the column that has Administrative Regions
Georeference your data by country’s, state's, province's or municipality’s"
**edited**: "Select the column that has Administrative Regions
Georeference your data by country, state, province or municipality"

original: "1. In Which Column Are Your Region Names Stored? Select column"
**edited**: " Select Your Region Name, Select column"

original: 2. If Your Column Isn't Country Data, Where's It? Select column or type it"
**edited**: "Select Your Country Data, Select column or type it"

**Comment by saleiva** [comment]
fixed on new designs! Thanks!
