### ISSUE TITLE
/spec/requests/carto/api/layers_controller_spec.rb

### ISSUE THREAD

**Issue by jesusvazquez** [CartoDB/cartodb#5973]
This test is giving errors randomly from time to time. At first I thought it was related with the parallelization but yesterday [this master PR execution](https://ci.cartodb.net/job/CartoDB-master-testing/14/console) failed in sequential mode.

Disabling or rewriting the test could be the solution. It is actually disabled on parallel mode.

**Comment by jesusvazquez** [comment]
cc/ @iriberri

**Comment by gfiorav** [comment]
@jesusvazquez I think the link went 404, could you provide another instance of this issue?

Thanks!

**Comment by xavijam** [comment]
ping!

**Comment by jesusvazquez** [comment]
Sorry guys, I can't find logs for this test because we dropped the old ci instance. Right now this test seems to be OK because no one complains about it. 

I think we can safely close this issue and if someone has a problem with it reopen and check the new logs.

**Comment by gfiorav** [comment]
Ok, @jesusvazquez, thanks for the insight! :smile:
