### ISSUE TITLE
Box integration

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#5975]
- [X] Configuration: CartoDB/cartodb-platform#1276.
- [X] Replace Boxr (which requires Ruby 2) with homemade api wrapper.
- [X] Box authentication.
  - [X] Refresh token.
  - ~~Handle deny~~ #6036
  - [X] Handle expired authorization code?
- [X] Support imports from Box.
- [X] Support syncs from Box.
- [X] Box icon.
- [X] Revoking auth.
- [X] Add `box_import` feature flag.
- [X] Clean code & test.
- [X] Tell marketing? about release and "Information for listing in the Box App Gallery"

**Comment by colinreilly** [comment]
Awesome. Thanks for jumping on this so quickly.
