### ISSUE TITLE
Legend style not showing properly on IE

### ISSUE THREAD

**Issue by jsanz** [CartoDB/cartodb#5976]
Legend icons are not appearing on the editor on visualizations on Internet Explorer with a custom legend. I tried in IE9 and IE11 with same results.

[Example viz that fails](https://itconsultores.cartodb.com/viz/59cb921e-f508-11e4-afd9-0e018d66dc29/embed_map)
[Other viz that is not working](http://www.trcimplan.gob.mx/sig-mapas-torreon/centros-educativos.html)

Screenshots on Chrome and then IE with the editor and visualization

![chrome](https://cloud.githubusercontent.com/assets/188264/10634059/57827576-77ef-11e5-8af6-cc286202be36.png)

![ie11_editor](https://cloud.githubusercontent.com/assets/188264/10634035/33c80074-77ef-11e5-90f4-78355d7b1a61.png)

![ie11](https://cloud.githubusercontent.com/assets/188264/10634050/452ec924-77ef-11e5-9f6a-a2ff954d3c1a.png)

The user is working with a legend like this, not sure if this is generated by

```html
<div class='cartodb-legend custom'>	
<div class="legend-title">Grifos</div>
<ul>
	<li class="bkg">
		<div class="bullet" style="background:url(http://com.cartodb.users-assets.production.s3.amazonaws.com/pin-maps/petrol.svg)"></div>
		Grifos
	</li>
</ul>
</div>
```

I'm inclined to think there's a problem on that template because I created [another map](https://team.cartodb.com/u/jsanz/viz/d37a5438-77df-11e5-ae82-0e674067d321/public_map) with icons and the default legend and it's working on IE but it's like the `style` attribute is being removed but I'm not sure.

**Comment by jsanz** [comment]
OK [reposted](https://github.com/CartoDB/cartodb.js/issues/726) at CartoDB.js repo

**Comment by xavijam** [comment]
Thanks man :heart:

**Comment by acanimal** [comment]
Similar issue: https://github.com/CartoDB/cartodb/issues/3068

**Comment by acanimal** [comment]
See https://github.com/CartoDB/cartodb/issues/3068

**Comment by acanimal** [comment]
Close due duplication, see #3068
