### ISSUE TITLE
Add config option to disable SQL+CartoCSS UI

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#5989]
:point_up: 

cc @mbforr @javisantana @xavijam

**Comment by viddo** [comment]
Based on the sparse information I've got so far I was planning to do this by adding a `app_config.yml` entry, or is there some requirement for exceptions (i.e. allow access but only for some users)?

**Comment by mbforr** [comment]
I think that would work well. Just across the board right now.

On Thu, Oct 22, 2015 at 10:40 AM, Nicklas Gummesson <
notifications@github.com> wrote:

> Based on the sparse information I've got so far I was planning to do this
> by adding a app_config.yml entry, or is there some requirement for
> exceptions (i.e. allow access but only for some users)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/5989#issuecomment-150244975>.
>



-- 
*Matt Forrest*
Account Manager

*CartoDB*
201 Moore St, Brooklyn, NY, 11206, USA
T: (612) 325-8470 Skype: mbforr
W: www.cartodb.com

Live sessions to learn CartoDB <http://cartodb.com/webinars/>

**Comment by viddo** [comment]
Looking more into this, rather than adding yet more entries in the app_config.yml itself, is there some reason for why we can't use the existing "feature flags"-feature for this? The difference would be that the limitation would have to be set (once) through the the ruby API, e.g. through the Rails console:
```ruby
ff = FeatureFlag.new(name: 'disabled_ui_sql', restricted: true)
ff.id=109
ff.save

ff = FeatureFlag.new(name: 'disabled_ui_cartocss', restricted: true)
ff.id=110
ff.save
```

…which would restrict access for everyone.

This would give us the benefit of not having to redo code again when/if more granular access is wanted.

**Comment by javisantana** [comment]
yes, feature flags sound like the right way.
BTW you can add FF with rake tasks http://cartodb.readthedocs.org/en/latest/operations/change_feature_flags.html

**Comment by viddo** [comment]
Great then, thx! Done in PR #5992

**Comment by viddo** [comment]
done in #5992

**Comment by viddo** [comment]
@mbforr following the docs at http://cartodb.readthedocs.org/en/latest/operations/change_feature_flags.html one would need to run the following command in the terminal:
```sh
bundle exec rake cartodb:features:add_feature flag[disabled_ui_cartocss]
bundle exec rake cartodb:features:enable_feature_for_all_users[disabled_ui_cartocss]

bundle exec rake cartodb:features:add_feature flag[disabled_ui_sql]
bundle exec rake cartodb:features:enable_feature_for_all_users[disabled_ui_sql]
```
