### ISSUE TITLE
Disable map panning when scrollwheel and zoom "controls" are not enabled

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#5995]
Basically, map will turn into a static map, because we should disable double click/tap zoom behaviour too.
If we have time, we should check highlighted maps (in public pages, me, explore,...) and set those properties in those maps too, turning them into "_static_".

**Comment by xavijam** [comment]
cc @mbforr, working on it.

**Comment by mbforr** [comment]
Perfect!

On Tue, Nov 10, 2015 at 12:36 PM, Javier Álvarez Medina <
notifications@github.com> wrote:

> cc @mbforr <https://github.com/mbforr>, working on it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/5995#issuecomment-155502610>.
>



-- 
*Matt Forrest*
Account Manager

*CartoDB*
201 Moore St, Brooklyn, NY, 11206, USA
T: (612) 325-8470 Skype: mbforr
W: www.cartodb.com

Live sessions to learn CartoDB <http://cartodb.com/webinars/>

**Comment by DavidLemayian** [comment]
I'm supposing this doesn't work for timeline maps though? Unless of course it went GIF mode. 🤔
