### ISSUE TITLE
When a table is shared (only READ) with an organization mate, when you try to visit it, it goes to public view and not private view

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#6002]
### STR
1. Having two users (A and B) inside an organization.
2. Being logged with A, shared a dataset (with READ limits) with user B.
3. Log in with user B, check your datasets.
4. Click over the dataset that A shared with B.
5. You are redirected to the private view.

It should go to private view with disabled state.

**Comment by ethervoid** [comment]
Yep but it wasn't with the share option IIRC

**Comment by Kartones** [comment]
What do you mean with the share option?

**Comment by ethervoid** [comment]
Yes this is the same ticket that one we discuss about 3 months ago. There were two options:
* Go to the private option: This could lead to unexpected behaviour becuase there were some corner cases where the user could appear as the owner of the dataset (@kartones know more about this)
* Or leave it public

We decided to leave it public at the moment and I discarded the changes I've made.

I can't find that ticket :(

**Comment by Kartones** [comment]
I guess this is then no bug

**Comment by xavijam** [comment]
Not sure again about this behaviour, I'd like to have this thing working and checking if it can work.

**Comment by xavijam** [comment]
Please, take a look and check that things are working as expected in the read only mode, thanks :).

**Comment by Kartones** [comment]
Branch: `6002-enable-readonly-shared-tables`

**Comment by Kartones** [comment]
Adding to the main description the errors found, will notify when I'm finishing building the list.

**Comment by Kartones** [comment]
@xavijam added all things I've found, branch is indicated also there

**Comment by xavijam** [comment]
Finally it is going to be fixed in the new dataset view, so the description bullets are not necessary. Thanks @javitonino! \o/.
