### ISSUE TITLE
Import fail when try to import again a file with user-custom-types that exists

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/cartodb#6007]
When a user try to import a again a file that contains user-define-type that exists, the importer returns an error:

```2015-10-26 10:46:52 UTC: Exception: PG::Error: ERROR:  "user-defined-type name" already exists in schema "public"```

**Comment by gfiorav** [comment]
@ethervoid Could you provide the such file to ease reenacting the bug? Thanks! :smiley:

**Comment by rafatower** [comment]
duplicate and working on the fix, @iriberri can you please reference the issue you're working on? thanks

**Comment by iriberri** [comment]
https://github.com/CartoDB/cartodb/issues/6622

PR: https://github.com/CartoDB/cartodb/pull/6623

**Comment by rafatower** [comment]
closing as duplicate
