### ISSUE TITLE
Public user profile header menu issues on Safari

### ISSUE THREAD

**Issue by acanimal** [CartoDB/cartodb#6010]
Hi,
after creating a user and looking at his public profile I saw Safari has some issue rendering the menu at header. See the difference:

`safari 9.0.1`
![screen shot 2015-10-26 at 14 30 29](https://cloud.githubusercontent.com/assets/732033/10730182/b91d29d6-7bee-11e5-910e-e9a81c948f39.png)

`Chrome 46.0.2490.80 (64-bit)`
![screen shot 2015-10-26 at 14 31 06](https://cloud.githubusercontent.com/assets/732033/10730184/b9524170-7bee-11e5-9db5-750ab975f121.png)

**Comment by xavijam** [comment]
Not happening anymore due to the fact that the menu has changed and there are not so many items, screenshot:

![screen shot 2016-01-11 at 15 45 16](https://cloud.githubusercontent.com/assets/132146/12236475/5b53d962-b87a-11e5-8cf3-0507f31bc780.png)

cc @matallo
