### ISSUE TITLE
data type selection not working on PCs

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/cartodb#6015]
While giving a workshop, several people with PCs are unable to change their data type. On my Mac, when I hover over a data type it changes to a darker grey and the triangle shows up, but on PCs the color does not change and clicking on the data type only triggers the ASC/DESC sorting options for the column, everything else does _not_ show up.

Sorry for the brief report.. in workshop and can't screenshot from their computers right now.

**Comment by ohasselblad** [comment]
Here you go:
![bug](https://cloud.githubusercontent.com/assets/1041056/10731162/09fccfd2-7bc2-11e5-8349-e3adf7d1a915.jpg)

**Comment by xavijam** [comment]
Hey Andy, that "dataset" looks disabled, I mean, could it be a sync/read-only dataset?

**Comment by ohasselblad** [comment]
Ooops! You're right, not a bug :) I wonder if there should be a 'cannot change datatype for sync tables' tip when hovering over the data type?

**Comment by xavijam** [comment]
We should add a better info yeah, totally :).

**Comment by ohasselblad** [comment]
want me to create an issue for it?

**Comment by xavijam** [comment]
Please :)
