### ISSUE TITLE
Make read only in sync'd tables more explicit

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/cartodb#6017]
When working with a sync table, it is not obvious that the data type cannot be changed like in other tables. When clicking on the data type, the column editing information appears instead. 

It'd be great to have a little info hover that says 'data types cannot be changed for tables that are sync'd' or something like that.

ref #6015

**Comment by xavijam** [comment]
For design team, I feel it would be great for new dataset view.

**Comment by saleiva** [comment]
We propose adding that "(read-only)" text close to the datasource name and changing the color of the column names so they truly look deactivated

![screen shot 2016-07-11 at 16 43 13](https://cloud.githubusercontent.com/assets/132149/16734651/96c9c6c8-4786-11e6-84fc-f5154419a81e.png)
