### ISSUE TITLE
Named maps interactivity update takes around 5-10 minutes

### ISSUE THREAD

**Issue by alasarr** [CartoDB/cartodb#6022]
In the following scenario:

1) Create a named maps.
2) Instantiate a named maps.

Everything works fine until here and I see the interactivity fields in cartodb-js. I'm using something like this:

```javascript
sublayer.on('featureClick', function(e, latlng, pos, data) {
      console.log(data); 
})
```
3) Change interactivity fields in the named maps.
4) Update the named maps.
5) Instantiate the named maps again.

Interactivity fields are not updated in cartodb-js for a while. If I do a get of the named maps everything is right, so the updated has been requested successfully. I've also tried to delete and create the named maps again but still I get the old interactivity fields.

After 5-10 minutes everything works fine.

I know it's not a critical issue, but I felt very frustated and I'd like to comment it... Just to let other people with the same issue to know about it.

**Comment by xavijam** [comment]
Hi Alberto!

Thanks for your feedback. Let me move this issue to the correct repo.
https://github.com/CartoDB/cartodb.js/issues/730
Thanks!
