### ISSUE TITLE
Sync tables generate duplicated cartodb_id index

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#6031]
After a couple of failed owner assignments because of CartoDB/cartodb-postgresql#174 I checked my own tables and I think sync tables have duplicated indexes on `cartodb_id`:

```
    "guess_country_sync_pkey" PRIMARY KEY, btree (cartodb_id)
    "guess_country_sync_cartodb_id_key" UNIQUE, btree (cartodb_id)
```

I have checked this in my own sync tables. Normal imports do not have this.

cc @rafatower @Kartones @ethervoid

**Comment by Kartones** [comment]
Yep, IIRC this was happening... smells like the ticket got closed in some old tickets wipe, but I'm prety sure this can be happening.

self-assigning the issue

**Comment by Kartones** [comment]
Branch `6031-remove-duplicate-cartodb_id-indexes-upon-sync`

**Comment by Kartones** [comment]
Reopening, as current query causes statement timeouts in live at least in some DBs (due to way more users per machine than staging or local)
