### ISSUE TITLE
Minor CartoDB CSS error on zoom buttons

### ISSUE THREAD

**Issue by mbforr** [CartoDB/cartodb#6035]
Noticed this on a few maps but the divider between the zoom buttons seems to be overflowing a bit. 
![screen shot 2015-10-27 at 1 41 12 pm](https://cloud.githubusercontent.com/assets/4828460/10767087/e09e34d8-7cb0-11e5-94f4-87b40a46dc86.png)

**Comment by xavijam** [comment]
It is fixed in the new cartodb.js version, so closing, thanks @mbforr for the feedback!
