### ISSUE TITLE
Document Box integration

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#6047]
- Add Box integration to documentation.
  - Document that [Box API index is sometimes slow and adding files takes time](http://stackoverflow.com/questions/24270427/is-there-a-delay-when-using-the-box-com-search-api).

cc @xavijam

**Comment by xavijam** [comment]
Why not add this ticket here -> https://github.com/CartoDB/docs?

**Comment by juanignaciosl** [comment]
Moved to CartoDB/docs#465
