### ISSUE TITLE
Nav buttons misaligned in Safari

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#6058]
For example in www.cartodb.com/explore

<img width="1025" alt="screen shot 2015-10-29 at 16 55 00" src="https://cloud.githubusercontent.com/assets/4222826/10823875/fe3cca6e-7e5d-11e5-8f3d-e6b81af09631.png">

**Comment by xavijam** [comment]
Duplicated :)

https://github.com/CartoDB/cartodb/issues/6010
