### ISSUE TITLE
Duplication of attributions

### ISSUE THREAD

**Issue by vishalya** [CartoDB/cartodb#6059]
Open a map and change the base map from positron to stamen or for that matter any other base map.
The attributions keep on appending.
Only the last base maps attributions should be available on the map.

**Comment by acanimal** [comment]
hi @vishalya,
I'm not able to reproduce the issue. Could please check it again? If it persists let me know the exact steps you make to reproduce.

**Comment by vishalya** [comment]
Steps:
(1) Create an empty map, don't add any data/points etc. It came up with 'positron'
(2) Change the base map to 'Dark Matter', notice that the attributions are duplicated.

**Comment by vishalya** [comment]
remove

**Comment by vishalya** [comment]
closed accidently.. reopening.

**Comment by vishalya** [comment]
remoge the '.png' extension and run the webcasting, I have recorded the chrome interaction.
![untitled screencast webm](https://cloud.githubusercontent.com/assets/12156243/10982293/7171332c-83da-11e5-9792-5ca308ef4221.png)

**Comment by vishalya** [comment]
download the file and change the extension to '.webm' and you will be able to run it using vlc media player.

**Comment by vishalya** [comment]
or Chrome would also play it.

**Comment by acanimal** [comment]
hi @vishalya , we have finally found the issue. We'll try to fixe it ASAP.
