### ISSUE TITLE
Edit content on "Georeference your dataset" dialog box

### ISSUE THREAD

**Issue by csobier** [CartoDB/cartodb#6060]
@viddo , please assign accordingly and prioritize.  *I know that there are several duplicate issues about this text*.  The purpose of this issue is a task list to ensure that each section of the "Georeference your dataset" dialog box is addressed (no pun intended).  

- [ ] **Prerequisite**:  Please confirm if the name of this dialog box should change to "Geocoding your dataset"?  [See Website issue#2197](https://github.com/CartoDB/website/issues/2197).  The existing UI uses both georeference and geocoding for these options.

Once the prerequisite is determined, please let me know so that I can supply text for all options. Let me know if a wireframe of each section is more helpful?

- [ ] **Lon/Lat Columns**

 "Select the columns containing your Lon/Lat data"
The selected columns are transformed into georeference coordinates."
 
  Select your Longitude ---- Select column
  Select your latitude ---- Select column"

*You do not have to capitalize pronouns*.

- [ ] **City Names**

- [ ] **Admin. Regions**.  Content edits from issue #5971.

- [ ] **Postal Codes**

- [ ] **IP Addresses**

- [ ] **Street Addresses**, note the typo in the description (as reported by @vhamer) 

  "Select the columns containing your street address
 Choose this option for high resolution geocoding of your street address data.

  Select your Street Address  --- Select column
  Select the State/Province of your Street Address (optional) ------ Select column
  Select the Country where the Street Address is located (optional)  -----   Select column"

- [ ] Lastly, once any UI text changes are applied, create an issue in the Docs repo to ensure that related screenshots and/or references to these options are updated.

**Comment by csobier** [comment]
As per @saleiva , the pre-req to change all terminology in the Product from georeference to geocoding (Editor options, dialog boxes, etc.) **WILL** happen.  They are busy with other issues.   (I will bump all releated issues to a future milestone until this is done).

**Comment by iriberri** [comment]
I don't know if someone made a change here, but I think there's been a change:

![image](https://cloud.githubusercontent.com/assets/1730320/11839193/3165dd5a-a3ec-11e5-806e-7df0e5bce154.png)

**Comment by viddo** [comment]
Yes, looks like #5980, we need some better way of verifying changes are OK before merging

**Comment by csobier** [comment]
Any idea when these product changes will be applied? (So that I can update the doc)

**Comment by xavijam** [comment]
Taking into account for the new geocoding analysis UI, cc @javierarce.

**Comment by saleiva** [comment]
Hey, closing this since this is already reflected on the new designs :^
