### ISSUE TITLE
Error installing CartoDB’s Windshaft on RHEL 6

### ISSUE THREAD

**Issue by Worvast** [CartoDB/cartodb#6076]
Hi, we tryto install CartoDB in RHEL 6 and when we try to install Windshaft we receive this log/error:

	[root@x  Windshaft-master]# npm install
	npm WARN engine abaculus@1.1.0-cdb3: wanted: {"node":"~0.10.x"} (current: {"node":"0.8.24","npm":"3.3.9"})
	npm WARN engine tilelive-bridge@1.3.0-cdb3: wanted: {"node":"0.10.x"} (current: {"node":"0.8.24","npm":"3.3.9"})

	> mapnik@1.4.15-cdb5 install /opt/CartoDB/software/Windshaft-master/node_modules/mapnik
	> node-pre-gyp install --fallback-to-build

	make: Entering directory `/opt/CartoDB/software/Windshaft-master/node_modules/mapnik/build'
	make: *** No rule to make target `../node_modules/mapnik-vector-tile/proto', needed by `Release/obj/gen/vector_tile.pb.cc'.  Stop.
	make: Leaving directory `/opt/CartoDB/software/Windshaft-master/node_modules/mapnik/build'
	gyp ERR! build error 
	gyp ERR! stack Error: `make` failed with exit code: 2
	gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
	…

	gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:99:17)
	gyp ERR! stack     at Process._handle.onexit (child_process.js:680:10)
	gyp ERR! System Linux 2.6.32-504.12.2.el6.x86_64
	gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=mapnik" "--configuration=Release" "--module_name=mapnik" "--version=1.4.15-cdb5" "--prerelease=cdb5" "--major=1" "--minor=4" "--patch=15" "--runtime=node" "--node_abi=v8-3.11" "--platform=linux" "--target_platform=linux" "--arch=x64" "--target_arch=x64" "--module_main=./lib/mapnik.js" "--host=https://cartodb-node-binary.s3.amazonaws.com/" "--module_path=/opt/CartoDB/software/Windshaft-master/node_modules/mapnik/lib/binding/v8-3.11-linux-x64" "--module=/opt/CartoDB/software/Windshaft-master/node_modules/mapnik/lib/binding/v8-3.11-linux-x64/mapnik.node" "--remote_path=./mapnik/v1.4.15-cdb5/" "--package_name=v8-3.11-linux-x64.tar.gz" "--staged_tarball=build/stage/mapnik/v1.4.15-cdb5/v8-3.11-linux-x64.tar.gz" "--hosted_path=https://cartodb-node-binary.s3.amazonaws.com/mapnik/v1.4.15-cdb5/" "--hosted_tarball=https://cartodb-node-binary.s3.amazonaws.com/mapnik/v1.4.15-cdb5/v8-3.11-linux-x64.tar.gz"
	gyp ERR! cwd /opt/CartoDB/software/Windshaft-master/node_modules/mapnik
	gyp ERR! node -v v0.8.24
	gyp ERR! node-gyp -v v3.0.3
	gyp ERR! not ok 
	node-pre-gyp ERR! build error 
	node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node rebuild --name=mapnik --configuration=Release --module_name=mapnik --version=1.4.15-cdb5 --prerelease=cdb5 --major=1 --minor=4 --patch=15 --runtime=node --node_abi=v8-3.11 --platform=linux --target_platform=linux --arch=x64 --target_arch=x64 --module_main=./lib/mapnik.js --host=https://cartodb-node-binary.s3.amazonaws.com/ --module_path=/opt/CartoDB/software/Windshaft-master/node_modules/mapnik/lib/binding/v8-3.11-linux-x64 --module=/opt/CartoDB/software/Windshaft-master/node_modules/mapnik/lib/binding/v8-3.11-linux-x64/mapnik.node --remote_path=./mapnik/v1.4.15-cdb5/ --package_name=v8-3.11-linux-x64.tar.gz --staged_tarball=build/stage/mapnik/v1.4.15-cdb5/v8-3.11-linux-x64.tar.gz --hosted_path=https://cartodb-node-binary.s3.amazonaws.com/mapnik/v1.4.15-cdb5/ --hosted_tarball=https://cartodb-node-binary.s3.amazonaws.com/mapnik/v1.4.15-cdb5/v8-3.11-linux-x64.tar.gz' (1)
	node-pre-gyp ERR! stack     at ChildProcess.module.exports.run_gyp (/opt/CartoDB/software/Windshaft-master/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
	node-pre-gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:99:17)
	node-pre-gyp ERR! stack     at maybeClose (child_process.js:640:16)
	node-pre-gyp ERR! stack     at Process._handle.onexit (child_process.js:682:5)
	node-pre-gyp ERR! System Linux 2.6.32-504.12.2.el6.x86_64
	node-pre-gyp ERR! command "node" "/opt/CartoDB/software/Windshaft-master/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
	node-pre-gyp ERR! cwd /opt/CartoDB/software/Windshaft-master/node_modules/mapnik
	node-pre-gyp ERR! node -v v0.8.24
	node-pre-gyp ERR! node-pre-gyp -v v0.5.25
	node-pre-gyp ERR! not ok 
	Failed to execute '/usr/local/bin/node rebuild --name=mapnik --configuration=Release --module_name=mapnik --version=1.4.15-cdb5 --prerelease=cdb5 --major=1 --minor=4 --patch=15 --runtime=node --node_abi=v8-3.11 --platform=linux --target_platform=linux --arch=x64 --target_arch=x64 --module_main=./lib/mapnik.js --host=https://cartodb-node-binary.s3.amazonaws.com/ --module_path=/opt/CartoDB/software/Windshaft-master/node_modules/mapnik/lib/binding/v8-3.11-linux-x64 --module=/opt/CartoDB/software/Windshaft-master/node_modules/mapnik/lib/binding/v8-3.11-linux-x64/mapnik.node --remote_path=./mapnik/v1.4.15-cdb5/ --package_name=v8-3.11-linux-x64.tar.gz --staged_tarball=build/stage/mapnik/v1.4.15-cdb5/v8-3.11-linux-x64.tar.gz --hosted_path=https://cartodb-node-binary.s3.amazonaws.com/mapnik/v1.4.15-cdb5/ --hosted_tarball=https://cartodb-node-binary.s3.amazonaws.com/mapnik/v1.4.15-cdb5/v8-3.11-linux-x64.tar.gz' (1)
	- core-util-is@1.0.1 node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/readable-stream/node_modules/core-util-is
	- inherits@2.0.1 node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/readable-stream/node_modules/inherits
	- isarray@0.0.1 node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/readable-stream/node_modules/isarray
	- string_decoder@0.10.25-1 node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/readable-stream/node_modules/string_decoder
	windshaft@1.5.1 /opt/CartoDB/software/Windshaft-master
	├─┬ grainstore@1.1.0
	│ └─┬ millstone@0.6.14
	│   ├─┬ sqlite3@2.2.7
	│   │ └─┬ node-pre-gyp@0.5.22
	│   │   └─┬ tar-pack@2.0.0
	│   │     └── readable-stream@1.0.33 
	│   ├─┬ srs@0.4.9
	│   │ └─┬ node-pre-gyp@0.6.9
	│   │   └─┬ tar-pack@2.0.0
	│   │     └── readable-stream@1.0.33 
	│   └─┬ zipfile@0.5.7
	│     └─┬ node-pre-gyp@0.6.2
	│       ├─┬ request@2.51.0
	│       │ └─┬ bl@0.9.3
	│       │   └── readable-stream@1.0.33 
	│       └─┬ tar-pack@2.0.0
	│         └── readable-stream@1.0.33 
	└─┬ redis-mpool@0.4.0
	  ├── generic-pool@2.1.1 
	  └── redis@0.12.1 

	npm WARN EPACKAGEJSON windshaft@1.5.1 No license field.
	…

	npm ERR! Linux 2.6.32-504.12.2.el6.x86_64
	npm ERR! argv "node" "/usr/local/bin/npm" "install"
	npm ERR! node v0.8.24
	npm ERR! npm  v3.3.9
	npm ERR! code ELIFECYCLE

	npm ERR! mapnik@1.4.15-cdb5 install: `node-pre-gyp install --fallback-to-build`
	npm ERR! Exit status 1
	npm ERR! 
	npm ERR! Failed at the mapnik@1.4.15-cdb5 install script 'node-pre-gyp install --fallback-to-build'.
	npm ERR! This is most likely a problem with the mapnik package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     node-pre-gyp install --fallback-to-build
	npm ERR! You can get their info via:
	npm ERR!     npm owner ls mapnik
	npm ERR! There is likely additional logging output above.
	…

	npm ERR! Please include the following file with any support request:
	npm ERR!     /opt/CartoDB/software/Windshaft-master/npm-debug.log

I guess the particular error is this:

    mapnik@1.4.15-cdb5 install `node-install pre-gyp --fallback-to-build`

Any idea that we should look to find the specific problem or how to fix this?
Thank you.

**Comment by rochoa** [comment]
The main issue I see here is that there is no precompiled binary for the RHEL and node 0.8.x pair. I recommend you to check [Installing Mapnik section at Windshaft's readme](https://github.com/CartoDB/Windshaft#installing-mapnik). You might need to compile and package Mapnik and node-mapnik from source for your OS / architecture/ node version combination.

I also recommend you to use `npm@<2.0.0` instead of 3.x versions.

**Comment by Worvast** [comment]
Thans you, they finally finish to solve this step with you info.
