### ISSUE TITLE
maps: basemap preview in control isn't working

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#6087]
![screen shot 2015-11-04 at 11 27 05](https://cloud.githubusercontent.com/assets/36676/10935550/1fb228aa-82e7-11e5-94b3-52b05781cfd1.png)

vs

![change_basemap_options](https://cloud.githubusercontent.com/assets/36676/10935557/28212da6-82e7-11e5-9c65-3d849f2f95cf.png)

happened in "documentation" account, no relevant errors in console

feel free to reassigning, not assigning any milestone, though

**Comment by xavijam** [comment]
New map, old map?

**Comment by matallo** [comment]
I didn't created it => https://documentation.cartodb.com/viz/9f645d04-da1b-11e4-9cd9-0e0c41326911/map

**Comment by xavijam** [comment]
Seems like it had the old positron basemap (not labels on top), after changing it, all good.
