### ISSUE TITLE
Missing Fixed Title+Description - Misplaced text overlay on Public map view

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#6088]
Maps not showing Fixed Title/Description on the Public map view. Overlays are also misplaced

## Context
A map composed with the editor will not show Fixed Title nor Fixed Description. Also, text-overlays are displaced from its position (they appear in the position they would if there was no Fixed Title/Description (see screenshot). 
Only happens on the Public map view, when opening fullscreen, the map will show all its elements correctly placed.

## Process
- Log into your account and create a map or open a previously existing one
- Click on Options and enable Fixed Title and/or Fixed Description
- Click on Add Element and place a text overlay or a title element on the map
- Click Publish, grab the URL on 'Get the link'
- Open it on a 'Incognito Window', see displaced elements and check Fixed Title/Description is not showing

## Expected result
The map should show Fixed Title and Description and well-placed overlays. 

## Current result
Fixed Title/Description is not showing but its position is not used by other overlays, producing another layout than expected when seeing the map from the Public map view

## Screenshots
![captura de pantalla 2015-11-04 a las 12 58 00](https://cloud.githubusercontent.com/assets/10940006/10937893/68403f58-82f6-11e5-9ed1-062acad9b3cd.png)
![captura de pantalla 2015-11-04 a las 12 58 16](https://cloud.githubusercontent.com/assets/10940006/10937897/6fa9b8e6-82f6-11e5-9d80-1aaa3fe7242e.png)
![captura de pantalla 2015-11-04 a las 13 03 54](https://cloud.githubusercontent.com/assets/10940006/10937901/77a7a9a4-82f6-11e5-8164-b2462bf6c0d5.png)

**Comment by xavijam** [comment]
Let me close it because we will manage the problem with new editor :).
