### ISSUE TITLE
Make sure geocoder processed_rows are ALWAYS logged in DB

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#6099]
It can be set to default 0 due to bad exception management.

**Comment by rafatower** [comment]
Not sure if this is a bug or a feature. I think we shall split the `processed_rows` into requested to 3rd party and actually to be charged.

**Comment by ethervoid** [comment]
What you are suggesting is to create a new column to store the requested rows to a payment geocoder to store it independently if the geocoding task fails or not?

**Comment by rafatower** [comment]
Is this still an issue worth tracking, @ethervoid ?

**Comment by ethervoid** [comment]
Nope, processed_rows are set to 0 in the DB but we are storing in Redis all the needed info
