### ISSUE TITLE
In geocoding modal you can scroll "outside the content"

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#6103]
Even though the content fits in the screen you can scroll "further than expected", and this hides the title/description and instructions for the process.

A little bit difficult to explain, so I hope this video helps:
https://dl.dropboxusercontent.com/u/2879308/scrollgeo.mov

![image](https://cloud.githubusercontent.com/assets/1730320/11060455/a2af4900-87a0-11e5-84ea-c68f8893cb10.png)

More scroll than expected here:

![image](https://cloud.githubusercontent.com/assets/1730320/11060458/acb0787a-87a0-11e5-8200-2fa6f55c9a39.png)

**Comment by xavijam** [comment]
As I've just checked, only there is an ugly scroll in the street address panel, but rest are working properly (no scroll content), checked in 15" display. Could you confirm it @iriberri ? pretty please. And if so, I'd close the ticket since it is minor, what do you think?

**Comment by iriberri** [comment]
It happens for me in all of them, just checked. 13" display. :-)

![image](https://cloud.githubusercontent.com/assets/1730320/12020555/05d66632-ad7e-11e5-9ed8-448f4e1a2c8f.png)

We can close anyway if you think we should handle this directly in the new editor.
