### ISSUE TITLE
Remove CartoDB logo within private views using feature flags

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#6108]
Let, with a feature flag, remove the logo within the private map view (in map and dataset views).

Following what @viddo did in [this PR](https://github.com/CartoDB/cartodb/pull/5992).

**Comment by acanimal** [comment]
I have made required changes on frontend editor so we can completely hide "cartodb logo" link (within overlay dropdown) and logo overlay when the FeatureFlag `disabled_cartodb_logo` is set.

@juanignaciosl We need to change ruby code too so initial overlays for a map (with a user that has the FF set) does not contains the logo overlay.

**Comment by acanimal** [comment]
@mbforr The important point is the use has configured a `disabled_cartodb_logo` feature flag.
