### ISSUE TITLE
CSV normalization doesn't support in-cell linebreaks

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/cartodb#6116]
A CSV row may be split in multiple lines when quoted fields contain lines breaks. This is correctly supported by `ogr2ogr` (and, I assume, by Ruby's `CSV` module).

Handling such rows is checked by the specs ('imports records with cell line breaks') but the test is perfomed with a CSV file that doesn't require normalization, so this problem hasn't been detected so far.

CSV files are *normalized* when either:

* The encoding is different from UTF-8, ISO-8859-1/2
* The delimiter is not the comma
* It contains a single column (single-column rows are omitted during normalization)

In these cases Ruby CSV normalization is performed changing the  encoding to UTF-8 and the separator to `','` (and likely slowing noticeably the process along the way).

This Ruby normalization process reads each *line* and parses it with `CSV.parse_line`, silently ignoring anything that causes errors, which causes multiline rows to be dropped (an possibly other evil things).

**Comment by jgoizueta** [comment]
I've added a test in branch csv_normalization_6116 to detect this: dd1e0834

**Comment by ethervoid** [comment]
Make a PR and after a code review you will be able to merge it to master :). Good catch!

**Comment by jgoizueta** [comment]
Currently normalization causes any line with invalid CSV syntax to be dropped from the result.

What should we do with them? let `MalformedCSVError` exceptions be handled by the calling code (`CartoDB::Importer2::Loader´) and fail the import process? drop the lines but make the user aware some data was ignored?

**Comment by jgoizueta** [comment]
The existing code has this particularity:

Reverse feed characters (`0x8D`) are removed, but only for files in Windows-1252 encoding.

Is this some legacy hack for some very specific case? Do we need to preserve this behaviour?

**Comment by jgoizueta** [comment]
@rafatower

**Comment by jgoizueta** [comment]
Now the behaviour with the current PR is this regarding empty lines:

* Lines without content (just a line-break) and malformed lines are ignore and omitted from the output
* Whitespace-only lines are kept with null values in all fields

Should we omit blank (only whitespace) lines? and all-null rows? (the latter could contain column separators in addition to whitespace)

**Comment by rafatower** [comment]
Both cases are "malformed lines" from the point of view of CSV's, right? I'd prefer to treat them alike.

Is it hard to change that?

**Comment by jgoizueta** [comment]
Don't think so. Just drop the row if `row.all?(&:nil?)`

Counting malformed lines which are not "empty" may be harder (depends of whether the exception raised carries the information about the source text, which I'll check).

Anyway, we'll be releasing these features (ignore all-null rows, report ignored nonblank rows) separately.
