### ISSUE TITLE
update navigation in public pages

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#6120]
as per latest changes in commercial site, the new lineup would be:

- product
- industries
- discover
- learn
- pricing

**Comment by xavijam** [comment]
What is this?

**Comment by matallo** [comment]
to update both the header and the footer of the public pages so they are aligned with the latest changes (check http://docs.cartodb.com/)

**Comment by xavijam** [comment]
Ok, could you add that to the description of this ticket? Also, when you take care of it, please, take into account this one -> https://github.com/CartoDB/cartodb/issues/6010
:angel:

**Comment by matallo** [comment]
okie dokie
