### ISSUE TITLE
Issue with accessing cloudsherpasgeo "plan."

### ISSUE THREAD

**Issue by soshel** [CartoDB/cartodb#6121]
_edited because description contained customer information_

**Comment by juanignaciosl** [comment]
We've seen that error and @MariaCheca is currently fixing it: CartoDB/cartodb-central#924 . ETA: 2 hours

**Comment by juanignaciosl** [comment]
PS: I've removed the description to avoid displaying customer and partner information, you can contact me (juanignaciosl@cartodb.com) if you need the original text. We're on it, we'll fix it in a couple of hours, sorry.

**Comment by soshel** [comment]
Thank you for the speedy resolution. Also thank you for anonymizing the
request. (No need for original text.)

On Thu, Nov 12, 2015 at 9:12 AM, Juan Ignacio Sánchez Lara <
notifications@github.com> wrote:

> PS: I've removed the description to avoid displaying customer and partner
> information, you can contact me (juanignaciosl@cartodb.com) if you need
> the original text. We're on it, we'll fix it in a couple of hours, sorry.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/6121#issuecomment-156111644>.
>



-- 
[image: Cloud Sherpas]

Shel Davis    Senior Sales Engineer

shel.davis@cloudsherpas.com
direct: 404-478-6358
mobile: 404-293-9321
[image: Cloud Sherpas] <https://www.cloudsherpas.com/accenture>

Cloud Sherpas is now part of Accenture.
Learn More. <https://www.cloudsherpas.com/accenture>

**Comment by juanignaciosl** [comment]
It's fixed now, could you check, please?

Sorry for the inconvenience,

On Thu, Nov 12, 2015 at 3:18 PM, Shel Davis <notifications@github.com>
wrote:

> Thank you for the speedy resolution. Also thank you for anonymizing the
> request. (No need for original text.)
>
> On Thu, Nov 12, 2015 at 9:12 AM, Juan Ignacio Sánchez Lara <
> notifications@github.com> wrote:
>
> > PS: I've removed the description to avoid displaying customer and partner
> > information, you can contact me (juanignaciosl@cartodb.com) if you need
> > the original text. We're on it, we'll fix it in a couple of hours, sorry.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/CartoDB/cartodb/issues/6121#issuecomment-156111644>.
> >
>
>
>
> --
> [image: Cloud Sherpas]
>
> Shel Davis Senior Sales Engineer
>
> shel.davis@cloudsherpas.com
> direct: 404-478-6358
> mobile: 404-293-9321
> [image: Cloud Sherpas] <https://www.cloudsherpas.com/accenture>
>
> Cloud Sherpas is now part of Accenture.
> Learn More. <https://www.cloudsherpas.com/accenture>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/6121#issuecomment-156113460>.
>



-- 
*Juan Ignacio Sánchez Lara*
CartoDB Backend Engineer

*CartoDB—Map Your World's Data*
Twitter: @juanignaciosl <https://twitter.com/juanignaciosl>
www.cartodb.com

Live sessions to learn CartoDB <http://cartodb.com/webinars/>

**Comment by soshel** [comment]
Yes. This is working now. Thank you!

On Thu, Nov 12, 2015 at 9:46 AM, Juan Ignacio Sánchez Lara <
notifications@github.com> wrote:

> It's fixed now, could you check, please?
>
> Sorry for the inconvenience,
>
> On Thu, Nov 12, 2015 at 3:18 PM, Shel Davis <notifications@github.com>
> wrote:
>
> > Thank you for the speedy resolution. Also thank you for anonymizing the
> > request. (No need for original text.)
> >
> > On Thu, Nov 12, 2015 at 9:12 AM, Juan Ignacio Sánchez Lara <
> > notifications@github.com> wrote:
> >
> > > PS: I've removed the description to avoid displaying customer and
> partner
> > > information, you can contact me (juanignaciosl@cartodb.com) if you
> need
> > > the original text. We're on it, we'll fix it in a couple of hours,
> sorry.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/CartoDB/cartodb/issues/6121#issuecomment-156111644
> >.
> > >
> >
> >
> >
> > --
> > [image: Cloud Sherpas]
> >
> > Shel Davis Senior Sales Engineer
> >
> > shel.davis@cloudsherpas.com
> > direct: 404-478-6358
> > mobile: 404-293-9321
> > [image: Cloud Sherpas] <https://www.cloudsherpas.com/accenture>
> >
> > Cloud Sherpas is now part of Accenture.
> > Learn More. <https://www.cloudsherpas.com/accenture>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/CartoDB/cartodb/issues/6121#issuecomment-156113460>.
> >
>
>
>
> --
> *Juan Ignacio Sánchez Lara*
> CartoDB Backend Engineer
>
> *CartoDB—Map Your World's Data*
> Twitter: @juanignaciosl <https://twitter.com/juanignaciosl>
> www.cartodb.com
>
> Live sessions to learn CartoDB <http://cartodb.com/webinars/>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/6121#issuecomment-156122976>.
>



-- 
[image: Cloud Sherpas]

Shel Davis    Senior Sales Engineer

shel.davis@cloudsherpas.com
direct: 404-478-6358
mobile: 404-293-9321
[image: Cloud Sherpas] <https://www.cloudsherpas.com/accenture>

Cloud Sherpas is now part of Accenture.
Learn More. <https://www.cloudsherpas.com/accenture>

**Comment by juanignaciosl** [comment]
Great, thanks!
