### ISSUE TITLE
publish map error on maps that have dataset name that start with an underscore

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartodb#6138]
When you publish a map that has a dataset with a name that starts with an underscore, you get an error message: **Failed to load resource: the server responded with a status of 403 (Forbidden)**.

Steps:

1- Import a dataset with a name that starts with an underscore, for example "_dataset"
2- Create a map from dataset
3- Select "Publish" from map
4- Copy url from "Get the link" option
5- Paste the url in a new tab
Get this error message:
![screen shot 2015-11-16 at 16 57 07](https://cloud.githubusercontent.com/assets/11177693/11186685/1fdfcc56-8c83-11e5-829d-d2d783237288.png)

**If the dataset is renamed and  the underscore is removed from the beginning of the name  ("dataset") and you repeat the previous steps you get the map correctly published:**
![screen shot 2015-11-16 at 16 59 26](https://cloud.githubusercontent.com/assets/11177693/11186739/754de3d0-8c83-11e5-9b0f-4f9dcd6b9b92.png)

**Comment by rafatower** [comment]
Hey @gfiorav this is a priority and at first glance seems to fall between dataservices and editor. Can you please take a look when you have a chance?

cc/ @juanignaciosl

**Comment by gfiorav** [comment]
@rafatower sure thing. I tried to deal with this in the past. Take 2.

**Comment by gfiorav** [comment]
I found that these conditions produce the described error:
Any map with PUBLIC (strictly public) dataset.

investigation on course.
