### ISSUE TITLE
POST likes in embed maps return 400 (Bad Request)

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#6142]
**steps to reproduce**

- log in
- go to http://www.swgalaxymap.com/
- click <3

**expected behaviour**

- map is liked and <3 increases by 1

**actual behaviour**

- console returns error 400 on POST

**Comment by xavijam** [comment]
Right now we don't provide the necessary feedback to know if you have already liked the visualization in the embed view, trying to avoid a new request to the server. That means, if you try to like a map which it was liked in the past, request throws a 400 error (```You've already liked this visualization```), so it is correct. For now we will leave it as it is @matallo :).
