### ISSUE TITLE
Do we support new Mapbox URLs?

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#6157]
The new Mapbox URLs are used for styles created with the new Studio. When trying to use them as basemaps on CartoDB Editor, it does not admit them. 

### Steps to reproduce

1. Open CartoDB Editor. Change basemap. Click on yours and Mapbox tab. 
2. Paste a new Mapbox style ID. and API key. You can use the following: 
  API key: `pk.eyJ1IjoiZXJuZXN0b21iIiwiYSI6ImNpaDY3Y2trYTAwMHl2eW0xaWhuazJtMTYifQ.nedFBiYzaJeqkeelroMKLw`
  
  URL/ID: ` mapbox://styles/ernestomb/cih67aq2j005wbtlypfm3fia3 ` 

  Sharing Link:
 `https://api.mapbox.com/styles/v1/ernestomb/cih67aq2j005wbtlypfm3fia3.html?title=true&access_token=pk.eyJ1IjoiZXJuZXN0b21iIiwiYSI6ImNpaDY3YWFtMzA4aGtzd20yZnNtY2FsZmcifQ.JugPLZR5qyXbnntB3xipOg#0/0/0/0`

  **Feel free to use the API Key, it was created just for the sake of this Issue.**

3. You should see the message 'This URL is not valid'

please, @javisantana review

**Comment by iriberri** [comment]
@michellechandra SB/7426764

**Comment by ztephm** [comment]
S/B 7573132

**Comment by ztephm** [comment]
S/B 5486430

**Comment by ztephm** [comment]
S/B 7529393

**Comment by ztephm** [comment]
S/B 7485886

**Comment by ztephm** [comment]
S/B 7477169

**Comment by ztephm** [comment]
S/B 7500660

**Comment by xavijam** [comment]
Right now, AFAIK Mapbox doesn't provide a way to transform their vector tiles to image tiles, so we can't use their new maps.
