### ISSUE TITLE
Can't type into embedded map search box on iPad

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#6158]
cc @iriberri in case this is the wrong person to tag!

S/B 7351128

User can see search box on iPad but can't type into it, for CartoDB map embedded into site. 

## Context
User says search box does work when looking at a CartoDB map in full-screen mode though. 

Also you can type into search box properly when you're looking at a map via the Publish/Get the url link.

## Process

1. Open default Safari browser on iPad
2. Go to a site that uses CartoDB map embedded with Publish button's iframe code (see example below).
3. Try typing into map's default CartoDB search box.

## Expected result

Search box will work as it does in desktop version

## Current result

Can't type a value into the embedded map's search box. 

Tried in:
Apple iPad 3rd Gen
- default Safari for iOS 7.0.2
- Chrome v 35.0.1916.38

----

## Examples

* http://michellechandra.github.io/synchronicity.html

**Comment by iriberri** [comment]
cc @xavijam

**Comment by xavijam** [comment]
Moved to right repository, that element belongs to CartoDB.js lib. -> https://github.com/CartoDB/cartodb.js/issues/881
