### ISSUE TITLE
Points in the_geom get replaced by new multipoint geometry from lat/long columns on import

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#6163]
**STR:**

1. Generate a new dataset
2. Create two numeric columns for lat/long values
3. Fill in manually a row with a point in (1,1). Set the lat long columns to "5" both
4. Export as CSV
5. Import to CartoDB with **guessing enabled**

**Detected behavior:**

1. The old the_geom has been replaced by a new geometry in coordinates (5,5)
2. The geometry type is no longer a `point` but a `multipoint`

**Expected behavior:**

Downloading a CSV from a CartoDB dataset already geocoded (with the_geom) should generate exactly the same table that was exported. 

Edited: please, read https://github.com/CartoDB/cartodb/issues/6163#issuecomment-193178693

**Other notes:**

This issue does not happen with other formats such as GeoJSON.

**Comment by rafatower** [comment]
Related to this revert: https://github.com/CartoDB/cartodb/pull/5965

I'd remove the PROMOTE_TO_MULTI param, test everything and add back the geom_possible_names param.

**Comment by rafatower** [comment]
From @javisantana:
> if you export a points table as csv and you reimport it torque does not work because the_geom is imported as multipoint

I'd write some specs for export and re-import cases we want to cover, perform the changes suggested above and smoke-test the resulting branch

**Comment by iriberri** [comment]
Some conclusions here:

**Detected behavior:**

The old the_geom has been replaced by a new geometry in coordinates (5,5)
  * This is an expected behaviour. If import guessing is enabled, why wouldn't the system geocode it? We will not take care of inconsistent data in a table. **Disable guessing** if you don't want this to happen.

The geometry type is no longer a point but a multipoint
  * This is the issue. Any point generated by Ogr2ogr should not be a multipoint but a point.
