### ISSUE TITLE
400 error in import/sync endpoint not correctly managed in UI

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#6168]
### Steps to reproduce
1. Connect dataset. Use a URL that shall not be imported. E.g: `http://scanme.nmap.org:8080/foo.csv`
2. The imports endpoint returns a 400 error.

(bear in mind that check is disabled in development/testing as a convenience)

### Expected result
The UI hints the user about a failure (in this case `{"errors":{"imports":"Invalid URL, cannot connect dataset: http://scanme.nmap.org:8080/foo.csv"}}`)

### Actual
The UI remains stuck on that error. Same happens with new synchronizations.

![image](https://cloud.githubusercontent.com/assets/1914276/11339314/4bb841e8-91f9-11e5-9d71-00d52476dac2.png)

cc/ @xavijam

**Comment by xavijam** [comment]
First changes in issue-6248 branch.
