### ISSUE TITLE
text input for quota management in admin console

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/cartodb#6171]
Right now, the admin tools for an organization allow the admin to change user storage quota by dragging a slider which only goes on 1% increments of the total (or total remaining?) storage. A more precise control, such as defining quota through text input, would be much handier for many admins.

cc @kgjenkins

**Comment by andrewbt** [comment]
see

#5363 
#4227 

and

#5327

**Comment by xavijam** [comment]
Yeah, we have this issue already reported so let me move it to the top :).

**Comment by ohasselblad** [comment]
haha, nice finds @andrewbt :)
