### ISSUE TITLE
Video edit for YouTube refresh

### ISSUE THREAD

**Issue by skyone01** [CartoDB/cartodb#6172]
Hello @sandra-ku, Can you kindly add back in the title slide (I don't know where it came from), screen shot here: 
![screen shot 2015-11-23 at 3 56 08 pm](https://cloud.githubusercontent.com/assets/13969480/11349840/5061a952-91fc-11e5-9765-15bd6c99c608.png)

Copy for end slide:
To register for cartoDB monthly webinars on various topics: https://cartodb.com/webinars/

I was planning on uploading the new edited version via Vimeo but I don't have enough room in my personal account and don't yet have the company account login details.. so I will send that tomorrow.

**Comment by skyone01** [comment]
Hi again @sandra-ku I think I just changed my mind about the copy for the end slide.
Copy for end slide:
Register for cartoDB monthly webinars on various topics here: https://cartodb.com/webinars/

**Comment by xavijam** [comment]
Hey @skyone01, let me move it to the right repository :).
