### ISSUE TITLE
Timeout error when importing

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#6181]
Importing a .csv file fails with 
```2015-11-25 01:50:52 UTC: Exception: PG::Error: ERROR: canceling statement due to statement timeout``` 

**file_size:** 43MB
**rows:** 1041009

SB/7386187
error log code: 08753241-a61a-4002-8692-9512210a889e

please, @iriberri review

**Comment by ethervoid** [comment]
The file is in SB isn't it?

**Comment by rafatower** [comment]
Probably relevant to this issue:
https://github.com/CartoDB/cartodb/issues/1683
https://github.com/CartoDB/cartodb/issues/5009

**Comment by rafatower** [comment]
Relevant traces

```
true: Georeferenced
true: Finished importing data from /tmp/imports/***/***.csv
2015-11-25 01:49:33 UTC: Proceeding to register
2015-11-25 01:49:33 UTC: Before renaming from importer_**** to ****
2015-11-25 01:49:33 UTC: Before moving schema '****' from cdb_importer to **
2015-11-25 01:49:33 UTC: Before persisting metadata '***' data_import_id: 08753241-a61a-4002-8692-9512210a889e

Exception: PG::Error: ERROR:  canceling statement due to statement timeout

app/connectors/importer.rb:82:in `rescue in register'
app/connectors/importer.rb:64:in `register'
app/connectors/importer.rb:52:in `block in run'
app/connectors/importer.rb:51:in `each'
app/connectors/importer.rb:51:in `run'
app/models/data_import.rb:632:in `new_importer'
app/models/data_import.rb:366:in `dispatch'
app/models/data_import.rb:166:in `run_import!'
lib/resque/importer_jobs.rb:9:in `block in perform'
lib/resque/base_job.rb:21:in `call'
lib/resque/base_job.rb:21:in `run_action'
lib/resque/importer_jobs.rb:9:in `perform'
```

**Comment by jgoizueta** [comment]
Just a little clarification (I've checked this in the local environment)

The Ruby backtrace is altered by the re-raising of the exception. In this snippet from `importer.rb`(lines 74...):

```ruby
        runner.log.append("Before persisting metadata '#{name}' data_import_id: #{data_import_id}")
        persist_metadata(result, name, data_import_id)
        runner.log.append("Table '#{name}' registered")
      rescue => exception
        if true || exception.message =~ /canceling statement due to statement timeout/i
          raise CartoDB::Importer2::StatementTimeoutError.new(           # <----- A
            exception.message,
            CartoDB::Importer2::ERRORS_MAP[CartoDB::Importer2::StatementTimeoutError]
          )
        else
          raise exception             # <----- B
        end
      end
```

When an exception happens within the call to `persist_metadata` if the exception is re-raised in branch "B" the resulting trace is alright, but if it goes through "A" the trace is incorrect as shown above (in the original error instance).

So this confirms the exception (identified as a PG timeout) happens in the call to `persist_metadata`.

**Comment by rafatower** [comment]
The exception system is a bit of a mess... used also for UI feedback (hence the ERRORS_MAP)

I wouldn't touch that, just in case, but I'd add the following at the right place:
```
CartoDB.notify_exception(...)
```

you can find some examples throughout the code, and the wrapper is defined here:

https://github.com/CartoDB/cartodb/blob/master/config/initializers/error_notifier.rb#L17

**Comment by jgoizueta** [comment]
I managed to reproduce this problem in a local environment.

The timeout occurs when accessing the user database in the `set_the_geom_column` method of `Table`.

This method, among other things, converts multipoint geometry to point and the timeout occurs during the application of `ST_GeometryN(the_geom,1)` to do this.

There are to user parameters that may affect this: `database_timeout` (applied to the DATABASE connection) and `user_timeout` (applied to the ROLE). If any of them is too low the timeout will occur.

**Comment by jgoizueta** [comment]
Why doesn't the problem occurs when the CSV encoding has been changed? Maybe in this case multipoints are not generated in the first place due to normalization/different parameters to ogr2ogr ?

**Comment by jgoizueta** [comment]
We could adjust the timeout for cartodbfication based on the size of the dataset to be cartodbfied

**Comment by jgoizueta** [comment]
Check if #6975 fixes this

**Comment by iriberri** [comment]
I am no longer able to reproduce this in production anymore with the original file.
