### ISSUE TITLE
Likes (actor, subject) index should be (subject, actor)

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#6189]
I think we never need "likes an actor has received", but, for example, at the dashboard, we count the likes for each visualization. Since `actor` is the leftmost column at the `actor_subject_unique` constraint (index) counting visualization likes doesn't benefits from that index:

```
cartodb_production=# explain analyze select count(1) from likes where subject = '209b00de-83bf-11e4-94b8-0e853d047bba';
                                              QUERY PLAN
------------------------------------------------------------------------------------------------------
 Aggregate  (cost=62.09..62.09 rows=1 width=0) (actual time=0.467..0.468 rows=1 loops=1)
   ->  Seq Scan on likes  (cost=0.00..62.09 rows=1 width=0) (actual time=0.010..0.462 rows=1 loops=1)
         Filter: (subject = '209b00de-83bf-11e4-94b8-0e853d047bba'::uuid)
         Rows Removed by Filter: 4321
 Total runtime: 0.502 ms
(5 rows)
```

```
cartodb_production=# explain analyze select count(1) from likes where subject = '209b00de-83bf-11e4-94b8-0e853d047bba' and actor ='58ce99bb-cd8e-4176-8ee7-f4a7fa527ce9';
                                                                QUERY PLAN
-------------------------------------------------------------------------------------------------------------------------------------------
 Aggregate  (cost=8.06..8.06 rows=1 width=0) (actual time=0.100..0.101 rows=1 loops=1)
   ->  Index Only Scan using actor_subject_unique on likes  (cost=0.06..8.06 rows=1 width=0) (actual time=0.092..0.094 rows=1 loops=1)
         Index Cond: ((actor = '58ce99bb-cd8e-4176-8ee7-f4a7fa527ce9'::uuid) AND (subject = '209b00de-83bf-11e4-94b8-0e853d047bba'::uuid))
         Heap Fetches: 1
 Total runtime: 0.133 ms
(5 rows)
```

It'd make counting not using Seq Scan but Index Only Scan.

This is related to dashboard performance and CartoDB/cartodb-management#4338.

Do you agree, @rafatower , @ethervoid , @luisbosque ?

**Comment by ethervoid** [comment]
Seems legit to me.

On Fri, Nov 27, 2015 at 9:44 AM, Juan Ignacio Sánchez Lara <
notifications@github.com> wrote:

> I think we never need "likes an actor has received", but, for example, at
> the dashboard, we count the likes for each visualization. Since actor is
> the leftmost column at the actor_subject_unique constraint (index)
> counting visualization likes doesn't benefits from that index:
>
> cartodb_production=# explain analyze select count(1) from likes where subject = '209b00de-83bf-11e4-94b8-0e853d047bba';
>                                               QUERY PLAN
> ------------------------------------------------------------------------------------------------------
>  Aggregate  (cost=62.09..62.09 rows=1 width=0) (actual time=0.467..0.468 rows=1 loops=1)
>    ->  Seq Scan on likes  (cost=0.00..62.09 rows=1 width=0) (actual time=0.010..0.462 rows=1 loops=1)
>          Filter: (subject = '209b00de-83bf-11e4-94b8-0e853d047bba'::uuid)
>          Rows Removed by Filter: 4321
>  Total runtime: 0.502 ms
> (5 rows)
>
> cartodb_production=# explain analyze select count(1) from likes where subject = '209b00de-83bf-11e4-94b8-0e853d047bba' and actor ='58ce99bb-cd8e-4176-8ee7-f4a7fa527ce9';
>                                                                 QUERY PLAN
> -------------------------------------------------------------------------------------------------------------------------------------------
>  Aggregate  (cost=8.06..8.06 rows=1 width=0) (actual time=0.100..0.101 rows=1 loops=1)
>    ->  Index Only Scan using actor_subject_unique on likes  (cost=0.06..8.06 rows=1 width=0) (actual time=0.092..0.094 rows=1 loops=1)
>          Index Cond: ((actor = '58ce99bb-cd8e-4176-8ee7-f4a7fa527ce9'::uuid) AND (subject = '209b00de-83bf-11e4-94b8-0e853d047bba'::uuid))
>          Heap Fetches: 1
>  Total runtime: 0.133 ms
> (5 rows)
>
> It'd make counting not using Seq Scan but Index Only Scan.
>
> This is related to dashboard performance and
> CartoDB/cartodb-management#4338
> <https://github.com/CartoDB/cartodb-management/issues/4338>.
>
> Do you agree, @rafatower <https://github.com/rafatower> , @ethervoid
> <https://github.com/ethervoid> , @luisbosque
> <https://github.com/luisbosque> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/6189>.
>



-- 
*Mario de Frutos Díeguez*
Software Developer

*CartoDB—Map Your World's Data*
C/ Eloy Gonzalo, 27, 3, 28010, Madrid, Spain
T: : +34.911.165.823
W: www.cartodb.com

Live sessions to learn CartoDB <http://cartodb.com/webinars/>

**Comment by rafatower** [comment]
agree, good catch, man!
