### ISSUE TITLE
Raster tables can be accessed by hardcoding the URL and are available in write-mode

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#6191]
While debugging: https://github.com/CartoDB/cartodb/issues/1232

I noticed that although raster tables are listed as "non-accessible" in the dashboard, you can just make up the URL to see them.

Once the table view is open, these tables are not set as in read-only mode and their fields are editable or even you can force a georeferenciation process on them.

**Comment by xavijam** [comment]
We should respond with a 404 for this urls, so backend more than frontend :).
