### ISSUE TITLE
Move the geocoder soft limit to organization level

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/cartodb#6198]
Right now the geocoder soft limit (for Here maps right now) is defined at user level even in an organization context:

![captura_de_pantalla_2015-11-30_12_43_19](https://cloud.githubusercontent.com/assets/741240/11470747/8d48a8c0-9760-11e5-803a-0da0b4ddd738.png)

In the Geocoder API configuration we have defined the configuration in the `cdb_conf` table that is for all the database. In the organization case, this database is shared for all the organization users so we have to decide:

1. Move the `geocoder_soft_limit` to the organization and we have the same behaviour for all the organization users
2. Adapt the config to this situation adding the flag for every user in the organization: `'{"street_geocoder_provider": "nokia","nokia_monthly_quota": 100, "nokia_soft_geocoder_limit": {"ethervoid-1": false, "ethervoid-2": true….}}'`

// @javisantana @rafatower @juanignaciosl what do you think?

**Comment by juanignaciosl** [comment]
3. Use each user `cdb_conf` instead of organization owner `cdb_conf`.

**Comment by ethervoid** [comment]
Afaik organization users don't have database so they don't have cdb_conf
table

**Comment by juanignaciosl** [comment]
They don't have a database instance, but they have a database schema. Every user has `cdb_conf` in his schema. Normal users have it in `public` schema, org users have it in `<username>` schema.

**Comment by ethervoid** [comment]
We come back to have 2 options after discard the use of username.cdb_conf that don't exists for security reasons.

In one hand the easiest option is to include the username -> boolean option but in organizations with 5k users is not an option on the other hand I don't know if its mandatory to have a separate soft limit for every user in the organization

**Comment by juanignaciosl** [comment]
That's something that was requested time ago although still not done: #4466.

In order to reduce the number of parameters but also allow fine-grained assignment, you could do a default value + exception users: `{ "users_nokia_soft_geocoder_limit" : "true", "users_nokia_soft_geocoder_limit_exceptions": "['ethervoid-1', 'ethervoid-3']" }`.

And/or group support.

Keep in mind we're growing towards big organizations, I think this is needed.

**Comment by ethervoid** [comment]
Could be a good solution to just store the exception, I like that solution and I think that fine grained soft limit is going to be needed in big organizations.

What do you think @rafatower ?

**Comment by rafatower** [comment]
Is the fine-grained settings a business requirement? or  are they the result of code evolution? (I guess they are a requirement but prefer to get explicit confirmation)

If we are to store stuff per-user I prefer:
- Not to encode that info as: org + overrides but per-user. Simplify both representation and logic when possible.
- Store it in redis instead of in organization database. Yes, I know it, this is a late change. In the initial proposal the assumption was that `org-user-config = org-config` but if that doesn't stand true, then changing it to user-config in redis will simplify configuration changes, deploys, etc.

I'm all ears

**Comment by juanignaciosl** [comment]
It's business requirement (#4466). I don't know if it's a limitation we can "negotiate" now, but I'm quite confident about the need. Big organizations are nearer.

**Comment by rafatower** [comment]
there's a problem with @ethervoid's proposal: it needs the `username` which we lack in SQL-land space.

**Comment by rafatower** [comment]
Hey @juanignaciosl I have a proposal to deal with this in general, seeing this from the Geocoder SQL API point of view:

- Let the rails app manage org, groups and individual quota concerns. We don't want to implement that logic in several places.
- Use redis to store the _effective values_ for each individual user, after applying whatever business logic we want on them. E.g:
```
redis> HMSET rails:users:<username>:geocoder_service \
  street_geocoder_provider “[nokia|google]” \
  nokia_monthtly_quota "12345" \
  nokia_soft_geocoder_limit "[true|false]"
```
- Let other services read those _effective values_

The redis data would be overwritten upon changes in quota, for instance, only from rails app. Writes are expected to be infrequent compared to reads. This approach should be generic enough to cover other services in the future.

Do you think it fits both needs and technical aspects? Thanks

**Comment by juanignaciosl** [comment]
I'm missing some pieces here, probably not your fault but my context switching: if you can geocode outside the Editor the geocoder should also update the Redis quotas, isn't it?

**Comment by rafatower** [comment]
Yes and no. These quotas are _configuration_. The _usage_ will be updated in separate redis keys, both from editor and sql api.

Usage update (proposal from feature doc)
```
# single user
INCR user:<username>:<service>:used_quota_month:year_month
INCR user:<username>:<service>:used_quota_day:year_month_day

# organization user
INCR org:<orgname>:<service>:used_quota_month:year_month
INCR org:<orgname>:<service>:<uuid>:used_quota_day:year_month_day
```

**Comment by juanignaciosl** [comment]
LGTM :+1:

**Comment by ethervoid** [comment]
Some points here:

- We could get the username from the organization user schema (is the username).
- My main concern is about the update part. We have to update all the users every time the organization quota changes :S

**Comment by rafatower** [comment]
Closing this FTM, feel free to reopen if you think we're gonna need such changes

(I don't think so unless we tackle the biz rules part. We'd need to invest some time in improving config changes speed but that's something apart)
