### ISSUE TITLE
Double click zoom not working with GMaps Basemaps

### ISSUE THREAD

**Issue by michellechandra** [CartoDB/cartodb#6216]
S/B 7529393
Please, @xavijam @alonsogarciapablo review

## Context
Mouse double-click zoom does not work (also mobile pinch and zoom) using any GMaps basemap. 

## Process
Create any map in the Editor
Choose any GMaps basemap
View map using public link
Double click zoom will not work
Zoom controls work in zooming the map as expected

## Expected Result
Double click zoom should work

## Current Result
Can only zoom in on the map using the zoom control interface

Link to example map: http://bit.ly/1XFOM3W

**Comment by acanimal** [comment]
It could be related with https://github.com/CartoDB/cartodb.js/pull/792/files#diff-191a9aa663864ba77b72a7bfbadf8b60R52
