### ISSUE TITLE
Remove number of layers intelligence in tests

### ISSUE THREAD

**Issue by luisbosque** [CartoDB/cartodb#6219]
There are some tests related to layers that assume that once a visualization is created it should contain, for example, 3 layers. 1 no label basemaps, 1 data and 1 labels. This, however, depends on the app_config and the list of basemaps configured.

Tests should not assume that some specific basemaps are written in the config.

Thanks to @gfiorav for the research

**Comment by gfiorav** [comment]
Closed via #6218
