### ISSUE TITLE
Positron(labels below) & Dark Matter labels are cut off at tile edges in Firefox & Chrome

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#6225]
@xavijam 

S/B 7574208

## Context
These basemaps have "Indian Ocean" and/or "South Atlantic Ocean" labels cut off at tile edges @zoom level 2: 
[in Chrome 47.0.2526.73 and Firefox 42.0]

* Dark Matter
* Positron (labels below)

## Process
1. Open any map in CartoDB Editor
2. Zoom to level 2
3. Change basemap > Positron(labels below)
4. Change basemap > Dark Matter

## Expected result
Labels won't be cut off at tile edges

## Current result
![chrome_positronbelow](https://cloud.githubusercontent.com/assets/1779444/11669240/b5bfd5e8-9dc9-11e5-954a-5cfe35b6055c.png)

![chrome_darkmatter](https://cloud.githubusercontent.com/assets/1779444/11669243/bab9d30a-9dc9-11e5-8b32-df0cd9142f4e.png)

Maybe CartoCSS buffer has to be increased?

**Comment by xavijam** [comment]
@zenitraM any clue?

**Comment by javisantana** [comment]
this issue should to do https://github.com/cartodb/cartodb-basemaps

**Comment by ztephm** [comment]
[moved it](https://github.com/CartoDB/CartoDB-basemaps/issues/38), thanks
