### ISSUE TITLE
named maps: reached limit on number of templates

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartodb#6226]
An error code appears when trying to duplicate or import datasets to the CartoDB account. The account hasn't reach the quota limit and the logs of the errors are showing this message:

```
{"errors":["User 'XXXX' reached limit on number of templates (4096/4096)"]}
```

**Comment by rafatower** [comment]
this is platform, the tiler limits.

**Comment by iriberri** [comment]
Closing this. In the Editor (Data Services) side we are going to handle the explicit error for the user here: https://github.com/CartoDB/cartodb/issues/6275
