### ISSUE TITLE
Subdomainless urls don't work with IPs

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#6229]
Enabling [subdomainless URLs](http://cartodb.readthedocs.org/en/latest/configuration.html?highlight=subdomainless#domainless-urls) works if you login at `localhost.lan:3000/login`, redirecting you to `http://localhost.lan:3000/user/USERNAME/dashboard/`, but if you login at the IP (`192.168.33.10:3000/login`), you get redirected to `http://192.168.33.10.localhost.lan:3000/user/USERNAME/dashboard/`.

cc @javisantana

**Comment by lucasgao** [comment]
+1

**Comment by juanignaciosl** [comment]
Because of session handling, `session_domain` might need to be set to the IP. Is that a viable constraint, @javisantana ?

**Comment by javisantana** [comment]
the thing is that ip can change and at some moment the machine can be accessed through 1.2.3.4 and be changed to 4.3.2.1 without restarting or changing configuration.

Is this viable?

**Comment by juanignaciosl** [comment]
Ok, I'll work harder on this, then. The key here is the methods that handle URLs (https://github.com/CartoDB/cartodb/blob/master/config/initializers/carto_db.rb#L38 and next lines), they do request url searches, replacements and so on. I'll probably improve them to "do nothing" if request is an url and subdomainless urls are enabled, but it's tricky.
