### ISSUE TITLE
AWS EC2

### ISSUE THREAD

**Issue by lucasgao** [CartoDB/cartodb#6240]
I searched online for a complete and correct way to setup the cartodb on an AWS ec2 instances.
but I don't find a complete one.

Can you guys provide detailed information about how to set app_config.yml and /etc/hosts/ on aws ec2. so I can use this remove serve from my local browser?

Like if the ec2 ip address is 57.xxx.xxx.xxx     and the ec2 domain name is cartomaps.xxx.com
How to change the domain from localhost.lan to another one?

I have CartoDB up and running, but like some others I'm unable to log in using either the $subdomain. I can see the 57.xxx.xxx.xxx /login or cartomaps.xxx.com/login from my local browser, but When I tried to it redirect to login 57.xxx.xxx.xxx/user/dev/dashboard  or cartomaps.xxx.com/user/dev/dashboard  or  57.xxx.xxx.xxx.localhost.lan/user/dev/dashboard

will have 
```
NoMethodError in Admin/visualizations#index

Showing /cartodb/app/views/admin/visualizations/index.html.erb where line #12 raised:

undefined method `[]' for nil:NilClass

Extracted source (around line #12):

9:   <% end %>
10:   <script type="text/javascript">
11:     var username = "<%= current_user.username %>";
12:     var user_data = <%= safe_js_object current_user.data.to_json %>;
13:     var config = <%= safe_js_object frontend_config %>;
14:     var upgrade_url = config.upgrade_url;
15:     var isFirstTimeViewingDashboard = <%= (!!@first_time).to_s %>;
```

**Comment by javisantana** [comment]
Hey, this is for cartodb issues, for questions about how to configure you can use stackschange or cartodb mailing list
