### ISSUE TITLE
description is blank in user public feed

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#6245]
i.e.: https://francetelevisions.cartodb.com/u/francetvinfo/me

**Comment by matallo** [comment]
please @brittanymicek @beloneys suggest a description for these public pages, this is a hotfix

**Comment by beloneys** [comment]
Hi Matallo,

As @brittanymicek suggested for this specific profile:

Francetvinfo is a digital news platform, dedicated to providing news in real time with brief reports on timely topics.

Is that Ok for you?

**Comment by brittanymicek** [comment]
Also for general profiles:

This is [Username] profile. CartoDB transforms location intelligence into
dynamic renderings enabling discovery of trends and patterns.

On Fri, Dec 11, 2015 at 9:32 AM, Carlos Matallín <notifications@github.com>
wrote:

> please @brittanymicek <https://github.com/brittanymicek> @beloneys
> <https://github.com/beloneys> suggest a description for these public
> pages, this is a hotfix
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/6245#issuecomment-163949373>.
>



-- 
*Brittany Micek*
Content Writer

*CartoDB—Map Your World's Data*
201 Moore Street, Brooklyn, NY 11206
T: + <%2B34695497365>19174633232
W: www.cartodb.com

Live sessions to learn CartoDB <http://cartodb.com/webinars/>

**Comment by matallo** [comment]
we just need the generic description, thanks a lot!
