### ISSUE TITLE
review all meta tags for public pages

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#6246]
i.e. https://francetelevisions.cartodb.com/u/francetvinfo/me

user feed description is blank and shows a not optimal default text

**Comment by beloneys** [comment]
Hi @matallo,

As @brittanymicek wrote in the other issue #6245 we'd suggest to use a standard default text for every public user profile. Could you set this configuration for all the accounts please?

This is [Username] profile. CartoDB transforms location intelligence into dynamic renderings enabling discovery of trends and patterns.

Thanks

**Comment by matallo** [comment]
please, review @saleiva comment before moving forward with this https://github.com/CartoDB/cartodb/pull/6247#discussion_r47367691

**Comment by xavijam** [comment]
ping @beloneys!

**Comment by beloneys** [comment]
Hi! Sorry, forgot to close. Brittany created this text many days ago (check #6245 & #6247 ).

Cheers!

B

**Comment by matallo** [comment]
reopening, we decided to use an automated tool to review all public pages, do we have a report yet?

**Comment by beloneys** [comment]
Hi, of course, we are working on it. More than a tool, it is a global solution for both commercial and editor areas. This is a task that we have scheduled for Q1. I'm going to create specific issues for each internal link (as I already did with some of them). Moving then the Milestone. I'll keep you updated. :)

Belén

**Comment by beloneys** [comment]
Hi,

What we have is an automated way to see which errors have been discovered/crawled by Google.

Now we have a list of:
* Pages with duplicate meta descriptions
* Pages with short meta descriptions
* Pages with duplicate title tags
* Pages with missing title tags

According to Google Search Console, seems like we don't have those problems:
* Non-informative title tags
* Non-indexable content
It says "We didn't detect any issues with non-indexable content on your site."

As part of my SEO road map, I continue working with duplicated content with Google's feedback and the tool I was using before, so adding this to my to-do list. I'll create specific issues to update each link with Brittany's help.

Thanks!

B

**Comment by matallo** [comment]
alright, just forwarded an email with most of the SEO guidelines we already had
https://github.com/CartoDB/cartodb-management/wiki/SEO-guidelines

**Comment by beloneys** [comment]
Thanks, integrating Screaming Frog as a new tool
