### ISSUE TITLE
import error with no encoded URL

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartodb#6248]
When a new dataset is imported to CartoDB from a URL, if the URL doesn't have the URL encode applied, the import process fails without giving any error message. 

Steps:

1- Import a new dataset from a URL.
2- The "connect dataset" process it stays "frozen" and CartoDB doesn't give any error.
3- The dev tools is showing a 400 bad request error.
4- In the Import logs, CartoDB it doesn't give any error

If the URL is encoded, then the Import process works correctly.

**Comment by oriolbx** [comment]
@iriberri

**Comment by rafatower** [comment]
this is an editor issue

**Comment by xavijam** [comment]
@oriolbx could you provide a real url example in the description please?

**Comment by rafatower** [comment]
Related to this one: https://github.com/CartoDB/cartodb/issues/6168

**Comment by xavijam** [comment]
I feel it is a different error @rafatower.

About this issue, we shouldn't change anything from the url, if they need to "encode" the url/params, it should be done from the user perspective. We can't encode one parameter and rest leave as they are.

**Comment by rafatower** [comment]
@xavijam mmm, you're right, sorry about the confusion.

**Comment by xavijam** [comment]
Closing!
