### ISSUE TITLE
Update Importer Error Code 2004, number of columns

### ISSUE THREAD

**Issue by csobier** [CartoDB/cartodb#6251]
Related to [Docs issue#548](https://github.com/CartoDB/docs/issues/578), I have updated the number of columns to be **256** and updated the description.

Please apply to the actual code as well.

**Comment by iriberri** [comment]
This is getting more complex than expected: the limit is not 256, but if the file has the guessing enabled, the geocoding guessing query fails because the system only allows to add 256 columns in a query.

**Comment by iriberri** [comment]
We are not going to edit the 1600 rows import message, because it's real.

The 256 comes from other issue as I said above, so I have created a new exception (thus import error) for it. I will add the new one into the docs as soon as my code is in production.
