### ISSUE TITLE
Data Library: add pretty name form in metadata 

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#6257]
Publishing a data library request implies editing the metadata of the canonical visualization to set up a "pretty name" (`display_name`).

Can we add a new text input in the options for dataset metadata (only for Data Library accounts) so that the process of publishing does not require manual changes in the database?

cc @saleiva @rafatower

**Comment by ethervoid** [comment]
Related #5033

**Comment by xavijam** [comment]
Closing since it exists.

**Comment by iriberri** [comment]
Thanks @ethervoid, I've been looking for your issue but I didn't find it. I was sure there was already one. Thanks!
