### ISSUE TITLE
Wrong plural labels on selected maps

### ISSUE THREAD

**Issue by jsanz** [CartoDB/cartodb#6272]
This happens when you select more than one map on the dashboard :smile: 

![2015-12-15-09 56 32-selection](https://cloud.githubusercontent.com/assets/188264/11806307/6be1a732-a312-11e5-9d83-c7aec698404b.png)

**Comment by xavijam** [comment]
Arg! Thanks @jsanz.

**Comment by jsanz** [comment]
No prob @xavijam, BTW It happens also with datasets
