### ISSUE TITLE
Image preview is not working for standard users with subdomainless and no CDN

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#6274]
cc @javisantana

**Comment by xavijam** [comment]
Local instance, no organization:

<img width="1100" alt="screen shot 2015-12-15 at 11 12 25" src="https://cloud.githubusercontent.com/assets/132146/11807832/be48b006-a31c-11e5-89a3-e8f7bc864a08.png">

cc @javisantana

**Comment by xavijam** [comment]
http://cartodb.readthedocs.org/en/latest/configuration.html#domainless-urls

**Comment by vishalya** [comment]
so here's how it looks on my side, we don't have the cdn, so the image url comes out directly.
incorrect link
```
http://vishal.http:&/#x2F;&#x2F;njclduinctbct10.addev.bloomberg.com:80&#x2F;user&#x2F;{user}/api/v1/map/static/named/tpl_ba128130_a28e_11e5_a652_005056a11f1b/300/170.png
```
Correct link:
```
http://njclduinctbct10.addev.bloomberg.com/user/vishal/api/v1/map/static/named/tpl_ba128130_a28e_11e5_a652_005056a11f1b/300/170.png
```
the app_config section for our urls is like below:
```
  session_domain:     'nyclpuinctbct03.addmz.bloomberg.com'
  # If activated, urls will use usernames in format //SESSION_DOMAIN/user/USERNAME and ignore subdomains if present
  subdomainless_urls: true

```

**Comment by xavijam** [comment]
Yep @vishalya, I'm taking care of it right now :). Stay tuned!

**Comment by xavijam** [comment]
It should be fixed on https://github.com/CartoDB/cartodb/issues/6282, waiting to be reviewed.
