### ISSUE TITLE
Recognize and report appropriately unsupported Excel formats 

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#6278]
````
"WARNING \\*\\*\\* OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero\" | grep -v \"\\*\\*\\*" 
[...]
NoMethodError: undefined method `close' for 0:Fixnum
```

**Comment by iriberri** [comment]
PR https://github.com/CartoDB/cartodb/issues/6361 fixed this. Closing.

**Comment by ernesmb** [comment]
This error is reproducing again today: https://github.com/CartoDB/support/issues/145 We have had three cases so far. Should we open this issue again?

cc @rafatower

**Comment by rafatower** [comment]
No, that's a different issue. Look for it in the repo, iriberri was already working on it.
