### ISSUE TITLE
No Hubspot tracking code in /Explore

### ISSUE THREAD

**Issue by vuxita** [CartoDB/cartodb#6287]
Hey @xavijam  (not sure if this is for you, so feel free to reassign but matallo told me to open this issue here) - I've just noticed that the Hubspot tracking code is not in the /explore page. Could you please add it as below? 

In all pages we create we have to install the HS tracking code :-) .

  <script type="text/javascript">
    (function(d,s,i,r) {
      if (d.getElementById(i)){return;}
      var n=d.createElement(s),e=d.getElementsByTagName(s)[0];
      n.id=i;n.src='//js.hs-analytics.net/analytics/'+(Math.ceil(new Date()/r)*r)+'/474999.js';
      e.parentNode.insertBefore(n, e);
    })(document,"script","hs-analytics",300000);
  </script>

cc @javisantana 

Thanks!
Eva

**Comment by javisantana** [comment]
same for https://cartodb.com/data-library

**Comment by matallo** [comment]
duplicated https://github.com/CartoDB/cartodb/issues/6288

closing, then
