### ISSUE TITLE
Cartodb with 'length' column name keeps infowindow in loading state

### ISSUE THREAD

**Issue by vishalya** [CartoDB/cartodb#6291]
Load a simple data into a map as below and enable the info window, with a couple of fields. Now, click on a point to observe that the infowindow, just waiting with 'loading' state.

[length-issue.csv.txt](https://github.com/CartoDB/cartodb/files/64558/length-issue.csv.txt)

**Comment by vishalya** [comment]
I have debugged the issue, the issue is in infowindow::renderInfo method.
It uses the _.map function, which doesn't respect any field with name 'length'.
The details are as http://underscorejs.org/#each

**Comment by iriberri** [comment]
Duplicated: https://github.com/CartoDB/cartodb/issues/1117

**Comment by iriberri** [comment]
cc @xavijam
