### ISSUE TITLE
Enterprise user management API doesn't allow emails with +

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#6310]
Enterprise user management API doesn't allow emails with +, fails with `"email is not a valid address"` error.

**Comment by gfiorav** [comment]
Hi!

I tried and everything seems ok! I'm closing it. If you can come up with an example that breaks email validation please reopen! Have in mind that this uses the normal user validation so anything that works with normal singup will be the same here.

Thanks for reporting!

**Comment by juanignaciosl** [comment]
Oh, maybe it failed previously because of url encoding, and now it works because of JSON. Whatever the reason is, not important. :dancer:
