### ISSUE TITLE
Enterprise user management API users need email verification

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#6311]
Currently, when you create a user through the API it requires email verification for it to work. Is this actually needed?

**Comment by juanignaciosl** [comment]
cc @gfiorav @xavijam

**Comment by gfiorav** [comment]
This is discussable right? I think it should be needed. 

Can we ping someone to leverage it out?

**Comment by juanignaciosl** [comment]
Sure, this is arguable.

My point is that email confirmation is needed in form signup because it's initiated by the user and we need to be sure that he has an account with a organization whitelisted email domain.

Nevertheless, the API usage is initiated by the organization owner, so there's no need for the validation, and only the welcome email should be sent.

cc @xavijam @javisantana

**Comment by javisantana** [comment]
I don't think this is needed, if you think about the usecase this API is going to be called by an script so what people are doing to do is:

```
request('email=%{email}s&email_confirmation=%{email}s' % { 'email': 'rambo@amo.es' })
```

In the other hand, the confirmation is something to avoid human errors. You are not going to avoid developer errors.

Same applies for passwords

**Comment by javisantana** [comment]
oh, i got it wrong, thanks @gfiorav for pointing it. 

No email confirmation needed, same logic applies there

**Comment by juanignaciosl** [comment]
We're not speaking about the `email_confirmation` _field_ but the verification email which is sent to a user when he signs up in a organization. For example, if ABC University has "abc-university.org" in his whitelisted domain list and Alice signups with alice@abc-univerity.org, she can't use her account until she confirms the email we send to her, to avoid bob@whatever.com being able to sign up in ABC University.

**Comment by juanignaciosl** [comment]
Crossposted, ok :+1:

**Comment by gfiorav** [comment]
Ok, I'll see this is done.
