### ISSUE TITLE
plproxy.control error

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#6312]
Running the tests throw this error:

```
error: Error installing and configuring geocoder api extension
{:error=>"#<Sequel::DatabaseError: PG::Error: ERROR:  could not open extension control file \"/usr/share/postgresql/9.3/extension/plproxy.control\": No such file or directory\n>"
```

I guess it's related to latest changes, could you document what should I do, please?

cc @rafatower @ethervoid

**Comment by ethervoid** [comment]
You have to install plproxy through `sudo apt-get update && apt-get install postgresql-9.3-plproxy` but if you execute `vagrant reload --provision` all should be installed

**Comment by juanignaciosl** [comment]
I've tried `sudo apt-get update && sudo apt-get install postgresql-9.3-plproxy` (note the second `sudo`, it's needed), but even after a PostgreSQL restart and `make check` for test database cleanup it keeps failing :cry:

**Comment by rafatower** [comment]
same error or does it complain about a different version?

**Comment by ethervoid** [comment]
Could be the cdb_geocoder_client extension. Working on it...

**Comment by ethervoid** [comment]
Solved, we should add these steps to the NEWS and the installation process:

- sudo apt-get update && apt-get install postgresql-9.3-plproxy
- Install the [geocoder-api client](https://github.com/CartoDB/geocoder-api/tree/master/client) in your machine
- Add and config [app_config geocoder-api](https://github.com/CartoDB/cartodb/blob/master/config/app_config.yml.sample#L171-L175) part
