### ISSUE TITLE
Check how to implement a data-library within any instance

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#6316]
It should be documented in sphinx after implementation is done.

**Comment by ethervoid** [comment]
I make doc for common_data -> https://github.com/CartoDB/cartodb/blob/master/doc/manual/source/configuration.rst (search for common_data) maybe is what are you looking for?

**Comment by xavijam** [comment]
Yeah, it can do the trick, but in any case we should move them to sphinx.

**Comment by gfiorav** [comment]
@xavijam what @ethervoid is proposing is already in http://cartodb.readthedocs.org/en/latest/configuration.html#common-data

The thing is that the build was broken, so it wasn't showing up. Made a few POST to the web hook and it's fixed. Is this enough?
