### ISSUE TITLE
Enterprise User Management API redesign

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#6318]
After reviewing the API and the docs I have some concerns I'd like to _discuss_ (meaning I'm open to suggestions, I might not be right).

1. Original design seemed to have the organization id in the URL: `org.cartodb.com/u/org-owner/api/v1/organization/abcdefgh-1234-4321-abcd-1234567890ab/users`. Nevertheless it got lost during development, since I need to remove it to make calls work: `org.cartodb.com/u/org-owner/api/v1/organization/users`. I think keeping the id is better:
  - It's consistent with [existing URLs](https://github.com/CartoDB/cartodb/blob/master/config/routes.rb#L394).
  - It's _explicit_ and coherent with usual REST API design guidelines.
  - It's flexible and robust: what if a user could own or belong to several organizations and we had subdomainless urls?

2. It's an API. APIs are done with JSON (I don't know if there's any exception for that), so I think the payload should be JSON instead of parameters.

3. For [updates and deletions you select the user with the "username" or "email" parameter in the payload](http://docs.cartodb.com/cartodb-enterprise/enterprise-api/#modify-users-with-the-enterprise-api). This is not too "REST-y". Since a user is a resource you should be able to identify it with the URI: `org.cartodb.com/u/org-owner/api/v1/organization/abcdefgh-1234-4321-abcd-1234567890ab/users/abcdefgh-1234-4321-abcd-1234567890ab`. Payload should not be used to identify.

4. Related to previous one, `new_email` is actually an smell. There's no `new_email` attribute, I guess it's needed to avoid `email` collision.

Additional note: you might rise a concern about those ids (both user and organization) in the URLs: they're cryptic, not user-friendly and sometimes not even available.I think we should support the three "identifier attributes": `id`, `username` (users) / `name` (organizations) and `email`. Example: `myorg.cartodb.com/u/org-owner/api/v1/organization/myorg/users/theuser`.

What do you think, @ethervoid , @gfiorav, @xavijam ?

**Comment by gfiorav** [comment]
It boils down to the urls. I like your idea of myorg and theuser (maybe identify by name and username). If we change that convention +1 to everything. If we don’t, we can’t be full rest and need the smells.

--
Guido Fioravantti
Telecomm. Engineer
CartoDB—Map Your World's Data
C/ Eloy Gonzalo, 27, 3, 28010, Madrid, Spain
W: www.cartodb.com <http://www.cartodb.com/> · who.guido.is <http://who.guido.is/>
Live sessions to learn CartoDB <http://cartodb.com/webinars/>

**Comment by xavijam** [comment]
Adding @javisantana to this thread because some of those points were discussed last week.

**Comment by xavijam** [comment]
1. One user owner should belong to only one organization, so that means organization-id should not be necessary, doesn't it?.
2. Makes sense, JSON for the win.
3. :+1:

**Comment by javisantana** [comment]
agree with all of this except the uuid, there is no way to know the uuid of an organization for an user, only the name is known. We don't use uuids in our API except when we provide the urls and in this case (an API which is not for general use case) does not make any sense to expose the urls.

for the record I took that decision

**Comment by juanignaciosl** [comment]
@javisantana ok, no need for uuid id support, but you agree on using `myorg.cartodb.com/u/org-owner/api/v1/organization/myorg/users/username` routes with organization and user names, isn't it?

**Comment by javisantana** [comment]
I don't have a strong opinion there, my feeling is we are repeating "myorg" twice but ok.

How would be that url in onpremise with subdomainless urls?

**Comment by juanignaciosl** [comment]
In fact those URL examples are subdomainless-friendly. Subdomainless URLs require the `/u/username` fragment.

Without that fragment, a normal URL would be `myorg.cartodb.com/api/v1/organization/myorg/users/username`.

**Comment by xavijam** [comment]
Please @gfiorav review all suggestions in the next milestone with @juanignaciosl :).

**Comment by gfiorav** [comment]
@juanignaciosl see if it meets your requirements now!
