### ISSUE TITLE
User can't import data library dataset even with enough data storage space & import limit

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#6340]
@rafatower 

S/B 7574555

With over 1GB of data storage available and just over 1GB import limit, a 1GB Data Library dataset appears in red so that user is unable to connect it.

## Context

data storage = 1.5GB total
data storage currently used = .2GB
max import row limit = 5,000,000
max import file size = 1073741824 bytes

Data Library dataset to be connected = US Block Groups (tl_2014_block_groups)

## Process

1. Set test account to the above limits in SuperAdmin 
2. Log into test account
3. Go to Datasets page & click on Data Library
4. Search for US Block Groups 

## Expected result

When US Block Groups is found in Data Library search results, it should be able to be connected instead of showing red/unable to be connected.

## Current result

![screen shot 2015-12-29 at 2 58 57 pm](https://cloud.githubusercontent.com/assets/1779444/12041158/bbc425d8-ae3c-11e5-820e-3bafd24e405e.png)

----
The dataset can be connected when I increase my team account's max import size limit to 1.5GB (with over 1GB data storage available, and 7,500,000 rows max). 

If the dataset is actually larger than 1GB, can we change the UI to show that?

[not sure if [this](https://github.com/CartoDB/cartodb/issues/5315) is related]

**Comment by iriberri** [comment]
You can download this dataset directly through https://common-data.cartodb.com/tables/tl_2014_block_groups. It's public so it can be downloaded and updated.

**Comment by rafatower** [comment]
I think the problem is the max import file size because the size of the dataset is rounded to 1GB but probably a bit larger than that 1073741824 (1024 * 1024 * 1024) bytes.

From my dev env (updated on Dec 22th):
```
# select size from external_sources where visualization_id = (select id from visualizations where name like 'tl_2014_block_groups');
    size    
------------
 1407975424
```

and google says that `1407975424` bytes ~ 1.31 Gibibytes

I'd change the UI to round to 2 decimal places.

**Comment by xavijam** [comment]
The problem is frontend is rounding all numbers. Fixing it!
