### ISSUE TITLE
available_geometries_for_postalcode not honoring configuration

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#6349]
I tend to jump from prod/staging to local geocoder setups. When testing I had the config pointing to `geocoding.cartodb.com` but it insisted on using `geocoding.localhost.lan` when trying to geocode by postal codes.

After taking a closer look, I located the problem here: https://github.com/CartoDB/cartodb/blob/master/app/controllers/carto/api/geocodings_controller.rb#L74

**Comment by iriberri** [comment]
This was fixed at: https://github.com/CartoDB/cartodb/pull/6350, but the issue was never closed. Closing.
