### ISSUE TITLE
Subuser deletion gets rid of organization_id although delete fails

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#6363]
https://github.com/CartoDB/cartodb-management/issues/4379

https://github.com/CartoDB/cartodb/blob/0418ccd6bc640b92291c7a035e97b721bdca50db/app/models/user.rb#L302

According to @juanignaciosl, lines 301 and 302 are a possible source of this problem, as we empty the `organization_id` inside a `begin .. rescue` that will continue in case of failure.

When this happens, destroying the user is raising a:

````
irb(main):008:0> u.destroy
CartoDB::BaseCartoDBError: Tried to delete an organization user without org id
````

**Comment by michellechandra** [comment]
@iriberri - an organization user is unable to delete a subuser, is it related to this issue? S/B 9015535

**Comment by iriberri** [comment]
@michellechandra you can check if the User object in the Rails console has a valid `organization_id`.

**Comment by michellechandra** [comment]
hey @iriberri - I am having trouble accessing the user object following directions listed in Support repo

**Comment by michellechandra** [comment]
@iriberri - nevermind, doesn't seem to be related, thanks!
