### ISSUE TITLE
[META] Visualization import/export

### ISSUE THREAD

**Issue by andrewbt** [CartoDB/cartodb#6365]
cc @andrewxhill 

A semi-regularly requested feature is the ability to import and export visualization definitions, and create visualizations visible in the Editor dashboard via an API. This is _not_ the same as creating a named map through the Maps API because (currently) those will not appear in the dashboard.

This feature comes up often in the context of storing/archiving viz definitions (w/ SQL, cartocss, infowindows, the whole nine yards of a viz.json) locally and then uploading the definition file to re-create it on the same or another user's account. Example workflow:
- User creates a visualization with the Editor, and saves and archives the resulting viz.json file locally. (Or, a machine could use a hypothetical API to list the available Editor-created viz.json's and download one/many to store locally.)
- Time passes (days/weeks/etc), the original visualization could be deleted or modified in the Editor, etc
- To restore a deleted or prior-version visualization, or to share/export a viz definition to a coworker, a user/machine uploads a locally-saved viz.json definition to the same or different CartoDB account than the definition was created on. (This could even be a zipped "package file" with say a CSV table and a viz.json together - all inclusive) Once uploaded, this visualization should be visible in the account's dashboard and editable with the Editor from there, which is currently _not_ the case with named map template.json definitions or the API that supports them.

Andrew H discovered the QGIS plugin uploads visualizations through the non-public/documented API: https://github.com/gkudos/qgis-cartodb/blob/master/cartodb/cartodbapi.py#L164 , so this could even be as simple as making this API public/documented.

Other benefits/analogs:
- provides a "workaround" to the 4096 named maps limit by allowing users to store definitions locally, delete, and re-import later
- provides some level of manual "version control" for visualizations by keeping a local archive of prior versions/changes
- Esri "Layer package" files which include a FileGDB with data and ".lyr" files with styling and symbology. Emailing this to a coworker to use in ArcMap or ArcGIS Online is an "all inclusive" file that depends on nothing else

**Comment by juanignaciosl** [comment]
This is something we've done some development lately. There's even a (limited) tool that you can use to export/import a visualization to JSON:

http://cartodb.readthedocs.org/en/latest/operations/exporting_importing_visualizations.html

It's based on an existing internal backup functionality, and currently it fits the use case of having two "CartoDB environments", one used by developers to make the visualizations, and a "production" one with actual data. With this tools developers can do a visualization, export it to JSON, and importing it at the other editor, which should have tables with the same name and structure.

We've also spoken about exporting data as well, but there's nothing about it in the roadmap yet.

**Comment by andrewbt** [comment]
Oh interesting @juanignaciosl , thanks for the link! Though it seems there is no way to run this tool without SSH access to the server? Still, could be something useful to discuss with on-premises clients.

**Comment by juanignaciosl** [comment]
Yes, currently this is only for onpremises and opensource. From a technical point of view making this available through an API would be easy, but you know we must be careful about creating new APIs.

Summoning @javisantana to the discussion.

**Comment by juanignaciosl** [comment]
Feature doc: https://docs.google.com/document/d/13g0n3HZMmQyjOcg_G0-p4zMQf1UzOHT3Hy2IGDHpBNc/edit#

**Comment by saleiva** [comment]
<3!

2016-03-29 12:24 GMT+02:00 Juan Ignacio Sánchez Lara <
notifications@github.com>:

> Feature doc:
> https://docs.google.com/document/d/13g0n3HZMmQyjOcg_G0-p4zMQf1UzOHT3Hy2IGDHpBNc/edit#
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/6365#issuecomment-202823520>
>



-- 
Sergio Alvarez Leiva

**Comment by juanignaciosl** [comment]
Current status: I've just deployed the metadata import/export (#7114). As long as target user has the needed tables, you can export all metadata from one visualization to JSON with this lines:

```ruby
v_id = '3bf3a072-013e-11e6-a2e1-04013fc66a01'
u1 = Carto::User.where(username: 'juanignaciosl-ded02').first
require_relative './app/services/carto/visualizations_export_service_2'
exported_string = Carto::VisualizationsExportService2.new.export_visualization_json_string(v_id)
```

and then import it with

```ruby
u2 = Carto::User.where(username: 'juanignaciosl-ded-02-admin').first
imported_visualization = Carto::VisualizationsExportService2.new.build_visualization_from_json_export(exported_string)
saved_visualization = Carto::VisualizationsExportPersistenceService.new.save_import(u2, imported_visualization)
```

This will obviously be automated afterwards but maybe it can be useful right now for you.

Next steps: export/import data (#7057) and add export/import feature to Import API (#7125).

**Comment by juanignaciosl** [comment]
Current status: you can now export the full visualization to a `.carto` file and import it (even in production).

Export: `bundle exec rake cartodb:vizs:export_full_visualization['abf4e96e-11db-11e6-9808-040120e0c101']`.
Import: drop the file at the dashboard as usual. The map and the datasets will be imported.

**Comment by juanignaciosl** [comment]
Current status: we'll deploy this as soon as we manage to workaround a resque reloading limitation, probably today, both API and UI 💃 

@javisantana , do you think that exposing a public, documented API for this would be interesting? Example requests (POST + 2 polling GETs):

```bash
$ curl -H 'Content-Type: application/json' http://juanignaciosl.localhost.lan:3000/api/v3/visualization_exports\?api_key\=f5fe77ab2416fd66d4a6032d985b256fd411dd4e -X POST --data '{"visualization_id":"fde71536-bdc5-4530-8a95-8bf3cf9fdc07"}'

$ curl -H 'Content-Type: application/json' http://juanignaciosl.localhost.lan:3000/api/v3/visualization_exports\?api_key\=f5fe77ab2416fd66d4a6032d985b256fd411dd4e -X POST --data '{"visualization_id":"fde71536-bdc5-4530-8a95-8bf3cf9fdc07"}'
{"id":"b94c26f3-fa16-4f13-b672-45ebbd5a9c95","visualization_id":"fde71536-bdc5-4530-8a95-8bf3cf9fdc07","user_id":"35b78090-6a49-475a-8470-0a9032272af2","state":"pending","url":null,"created_at":"2016-05-05T09:36:09+00:00","updated_at":"2016-05-05T09:36:09+00:00"}

$ curl -H 'Content-Type: application/json' http://juanignaciosl.localhost.lan:3000/api/v3/visualization_exports/b94c26f3-fa16-4f13-b672-45ebbd5a9c95\?api_key\=f5fe77ab2416fd66d4a6032d985b256fd411dd4e
{"id":"b94c26f3-fa16-4f13-b672-45ebbd5a9c95","visualization_id":"fde71536-bdc5-4530-8a95-8bf3cf9fdc07","user_id":"35b78090-6a49-475a-8470-0a9032272af2","state":"complete","url":"/uploads/6a2b6fbd86e2c750160a/fde71536-bdc5-4530-8a95-8bf3cf9fdc07.carto","created_at":"2016-05-05T09:36:09+00:00","updated_at":"2016-05-05T09:36:13+00:00"}%
```

**Comment by saleiva** [comment]
Hey about the UI, did you check it with @urbanphes?

2016-05-05 14:40 GMT+02:00 Juan Ignacio Sánchez Lara <
notifications@github.com>:

> Current status: we'll deploy this as soon as we manage to workaround a
> resque reloading limitation, probably today, both API and UI 💃
>
> @javisantana <https://github.com/javisantana> , do you think that
> exposing a public, documented API for this would be interesting? Example
> requests (POST + 2 polling GETs):
>
> $ curl -H 'Content-Type: application/json' http://juanignaciosl.localhost.lan:3000/api/v3/visualization_exports\?api_key\=f5fe77ab2416fd66d4a6032d985b256fd411dd4e -X POST --data '{"visualization_id":"fde71536-bdc5-4530-8a95-8bf3cf9fdc07"}'
>
> $ curl -H 'Content-Type: application/json' http://juanignaciosl.localhost.lan:3000/api/v3/visualization_exports\?api_key\=f5fe77ab2416fd66d4a6032d985b256fd411dd4e -X POST --data '{"visualization_id":"fde71536-bdc5-4530-8a95-8bf3cf9fdc07"}'
> {"id":"b94c26f3-fa16-4f13-b672-45ebbd5a9c95","visualization_id":"fde71536-bdc5-4530-8a95-8bf3cf9fdc07","user_id":"35b78090-6a49-475a-8470-0a9032272af2","state":"pending","url":null,"created_at":"2016-05-05T09:36:09+00:00","updated_at":"2016-05-05T09:36:09+00:00"}
>
> $ curl -H 'Content-Type: application/json' http://juanignaciosl.localhost.lan:3000/api/v3/visualization_exports/b94c26f3-fa16-4f13-b672-45ebbd5a9c95\?api_key\=f5fe77ab2416fd66d4a6032d985b256fd411dd4e
> {"id":"b94c26f3-fa16-4f13-b672-45ebbd5a9c95","visualization_id":"fde71536-bdc5-4530-8a95-8bf3cf9fdc07","user_id":"35b78090-6a49-475a-8470-0a9032272af2","state":"complete","url":"/uploads/6a2b6fbd86e2c750160a/fde71536-bdc5-4530-8a95-8bf3cf9fdc07.carto","created_at":"2016-05-05T09:36:09+00:00","updated_at":"2016-05-05T09:36:13+00:00"}%
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/6365#issuecomment-217142645>
>



-- 
Sergio Alvarez Leiva

**Comment by gfiorav** [comment]
Yes, @urbanphes provided the export modal, @saleiva

**Comment by javisantana** [comment]
Why don't try to follow the current api?

like:

```
curl -X POST http://user.cartodb.com/api/v2/viz/:uuid/export
{"id":"b94c26f3-fa16-4f13-b672-45ebbd5a9c95","visualization_id":"fde71536-bdc5-4530-8a95-8bf3cf9fdc07","user_id":"35b78090-6a49-475a-8470-0a9032272af2","state":"pending","url":null,"created_at":"2016-05-05T09:36:09+00:00","updated_at":"2016-05-05T09:36:09+00:00"}
```

the status

```
curl -X POST http://user.cartodb.com/api/v2/viz/:uuid/export/b94c26f3-fa16-4f13-b672-45ebbd5a9c95
{status json
```

**Comment by javisantana** [comment]
and actually, do we want to have more than one export at a time?

**Comment by juanignaciosl** [comment]
@javisantana I followed the current _import_ API, I thought that focusing on the export itself made sense, it's quite similar. I can change it to be "visualization-centric" instead if you wish.

**Comment by javisantana** [comment]
(and yes, let's document and expose it :es:)

**Comment by juanignaciosl** [comment]
About the "more than one at a time", it's enqueued because exporting a large dataset might take time and we don't want to block unicorn workers because of this.

**Comment by javisantana** [comment]
I'm fine with the current one, that was just a comment. good work guys :crying:

**Comment by juanignaciosl** [comment]
Ok, we'll document this. I promise I try to follow current API 😅

**Comment by juanignaciosl** [comment]
Closing this as the bulk of the task is done and the UI (#7056) will be merged to master in the next hours.

**Comment by chrowe** [comment]
Is this functionality still available? Maybe via https://github.com/CartoDB/cartodb/pull/14745 ?

We are looking for the export/backup from one user/server and import/restore on another user/server functionality, where both locations already have the same datasets (so .carto will not work)

**Comment by andrewbt** [comment]
I can't speak to the internal server functionality as that's beyond my own knowledge, but obviously .carto export is still present today.

FWIW, .carto file import should still work if both users have the same datasets, it takes into account naming conflicts. But also, you might try just importing the embedded .json file itself solo if you know the account already has the referenced datasets and you don't want them to be duplicated/renamed copies. The .carto file is just a zip file with the .json and geopackages of the datasets inside it.
