### ISSUE TITLE
HTTP Header authentication

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#6367]
CartoDB should be able to authenticate users based on a (trusted) HTTP header, for Kerberos and other in-house authentication system interaction.

Implementation: we could create a `HttpHeaderAuthenticator` strategy for `Warden` that catches the parameter and uses it for authentication.

Requirements/restrictions:
- [X] Configure the http header name (presumedly at app_conf.yml).
- [X] Header value must be able to identify a user, thus mapping the value to a field (id, email, username) is needed (presumedly at app_conf.yml as well).
- [X] If authenticator doesn't find a matching user we could trigger the creation if the header field allows generation of a valid username and email, which are the strong requirements for user creation. Password is not needed, since that user would always use http header authentication. Optional. Default: no.

cc @javisantana

**Comment by javisantana** [comment]
thanks! cc @danicarrion

**Comment by danicarrion** [comment]
@juanignaciosl please ping me if you need help with testing and/or gathering specific requirements from an actual customer

**Comment by juanignaciosl** [comment]
Ok. I'm working on autocreation now. Creation requires email, user and password and I can generate all of them from the email, so email authentication will be mandatory if user wants autocreation, ok? The "authentication field" is configurable (email, username, id or auto).

**Comment by juanignaciosl** [comment]
@danicarrion, @javisantana I have an important question regarding automatic user creation: should it only be for organizations? Since CartoDB currently hasn't signup outside organizations having it async outside is harder. I can easily create the user in the first request with a trusted header for an unknown user in sync mode, but if we want the user to be redirected to a waiting page and this must work outside organizations I should first allow signup outside organizations.

**Comment by danicarrion** [comment]
IMHO this feature should be for organizations only, but I didn't write the specs

**Comment by juanignaciosl** [comment]
Well, I wrote the specs based on a @javisantana conversation :_).

I will try to support both scenarios.

**Comment by javisantana** [comment]
@danicarrion I'd say organizations is the target here but if we can do for everyone would be nice.

**Comment by danicarrion** [comment]
I can't think of a use case where this can be useful outside an organization. I mean, this is not the kind of stuff individuals set up for their own use only. But yeah, I guess I won't complain as long as organizations are supported ;-)
