### ISSUE TITLE
the_geom column values are replaced by NULL if latitude and longitude columns have NULL values

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartodb#6372]
If a table have latitude and longitude columns with  NULL values and the_geom column has a valid geometry, when the file is imported to CartoDB, CartoDB set the values of the_geom column to NULL and a new column appears (invalid_the_geom column).

Steps:

1- Create a table with valid coordinates in the_geom column and columns lat and long with NULL values.

![screen shot 2016-01-11 at 12 06 54](https://cloud.githubusercontent.com/assets/11177693/12232127/e7233ece-b85c-11e5-80b3-45cd6715729b.png)
2- Export table 
3- Import table to CartoDB: the_geom column value is set to NULL and the invalid_the_geom column appears
![screen shot 2016-01-11 at 12 09 28](https://cloud.githubusercontent.com/assets/11177693/12232141/fcc91afa-b85c-11e5-9550-57cad8d26efb.png)

**Comment by iriberri** [comment]
Related: https://github.com/CartoDB/cartodb-postgresql/issues/192

Closing bc of duplication.
