### ISSUE TITLE
data-library description

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#6388]
/cc @brittanymicek

**Comment by beloneys** [comment]
Brittany, please, Could you proof read the following description please?

This is the data library of CartoDB. Here you will find open resources to help you populate your maps.

kw: location intelligence, dataset, big data, location services, cartodb

Thanks!

**Comment by matallo** [comment]
did this as a hotfix, but still needs to be reviewed, will leave the issue open for tracking https://github.com/CartoDB/cartodb/commit/626ad79c17fc515571aa7bdebe3ab7d601543e85

**Comment by brittanymicek** [comment]
@beloneys does this work?

Discover trending datasets and visualizations made by mappers like you. Learn how to use location intelligence and big data to empower your insights.

**Comment by beloneys** [comment]
:+1:

**Comment by beloneys** [comment]
Hi!

Sorry but I see different kw in the page than here. I'm missing location intelligence please :)

**Comment by matallo** [comment]
this should be updated here https://github.com/CartoDB/cartodb/blob/7dcb1f962e2b60ec3ce5c22a3741e50f190ad9b1/app/views/layouts/data_library.html.erb

however the keywords might have changed (for sure the CartoDB changed), shall we review this @beloneys ?
