### ISSUE TITLE
Improvements organization user quota slider UI

### ISSUE THREAD

**Issue by MariaCheca** [CartoDB/cartodb#6404]
![screen shot 2016-01-15 at 12 02 37](https://cloud.githubusercontent.com/assets/2141690/12351704/eef6e062-bb7f-11e5-99ed-fcf1334f8c5a.png)

- Avoid calculations in the views using model attributes. Instead add methods to the own model to return them directly to the view. (See [feature envy](https://sourcemaking.com/refactoring/smells/feature-envy))
- Return flash message if the user sends the form with an invalid value in the quota input.

cc @viddo @xavijam

**Comment by viddo** [comment]
:+1:
