### ISSUE TITLE
Entry point for the new editor

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#6425]
A new url should take to an empty erb so frontend can begin working.
- [x] Choosing URL schema.
- [x] Protect it behind a feature flag (suggestion: "editor3", but feel free to change it).
- [ ] Add code for new entry point #6429

**Comment by gfiorav** [comment]
@juanignaciosl I'm working on the routing, everything else is ready. 

The feature flag is created in staging and production and it's called `new_editor` (I know you hate it but it's temporal, still in time to change it though :stuck_out_tongue: )

The url scheme is `org.cartodb.com/u/org-user/editor/visualizations/:id`

Does that seem right to you?

**Comment by juanignaciosl** [comment]
"editor-3" like the label, might be a better choice :P

I think you should remove `visualizations` part from the url, since only one "thing" will be opened with the editor, but @xavijam might have a better big picture. I know this is not important at all now, but it helps to establish some common knowledge (in this case, whether we can open several "things" or not). Proposal: `org.cartodb.com/u/org-user/editor/:id`

**Comment by xavijam** [comment]
Yep, as @juanignaciosl has said: 
```
org.cartodb.com/u/org-user/editor/:id
```

**Comment by gfiorav** [comment]
OK, changing the FF to 'editor-3` and removing `visualization from the URL scheme.
