### ISSUE TITLE
Provide a link to a visualization editor-3

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#6426]
Users having the feature flag (#6425) could have a new link in the dashboard linking the editor3 page.

**Comment by gfiorav** [comment]
@xavijam Would you like me to provide this link form the backend? Through what end point should it be?

**Comment by xavijam** [comment]
We will take care of this task in the frontend. But as the label describes, minor.

**Comment by gfiorav** [comment]
Ok, @xavijam thanks!

**Comment by xavijam** [comment]
We are going to postpone this issue for the moment.

**Comment by xavijam** [comment]
It was the PR -> https://github.com/CartoDB/cartodb/pull/6476
