### ISSUE TITLE
Update "Create a new map" tip dialog

### ISSUE THREAD

**Issue by csobier** [CartoDB/cartodb#6431]
Update the "Create a new map" tip dialog. @saleiva , please assign issue accordingly.
- The grammar is incorrect
- The numbers (A,B,C) are not intuitive (we already removed these from the "Welcome" tip dialog, so we should be consistent

https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/common/views/create/create_onboarding.jst.ejs. Update text as follows:
```
Create a new map,

A map shows one or more data layers that are connected to your datasets.

Connect your own data, or use a public dataset from the Data Library, to create your first map.

Thinking of starting from scratch? You can also create an empty map.
```

![newmap_createmapfromstratch_newmapdialog](https://cloud.githubusercontent.com/assets/13319925/9413701/910d48e8-4801-11e5-8645-520a7d9abf00.png)

[Related to Docs issue#326](https://github.com/CartoDB/docs/issues/326)

**Comment by saleiva** [comment]
Thanks! :)

**Comment by csobier** [comment]
Does not apply with the Builder. Closing this, and the related Docs issue!
