### ISSUE TITLE
Editor GUI can not be used if the display has too many layers

### ISSUE THREAD

**Issue by dersteppenwolf** [CartoDB/cartodb#6440]
Editor GUI can not be used if the display has too many layers

![screenshot-gkudos cartodb com 2016-01-21 12-30-57](https://cloud.githubusercontent.com/assets/110606/12488823/72117ee8-c03b-11e5-984f-9f712e71cd35.png)

**Comment by xavijam** [comment]
Totally agree @dersteppenwolf. In the next version of the editor this problem will be solved for sure (WIP), so stay tuned :).
