### ISSUE TITLE
Replace temporary solution for CSS for new entry point

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#6459]
In #6458 we added the bundle generated by deep-insights to the `vendor/stylesheets` dir, AFAIK we should really use the https://github.com/CartoDB/CartoAssets once it's ready, so as part of integrating that this temporary CSS should be :fire:

**Comment by viddo** [comment]
Reopening because we still need to :fire: the temporary files as parto f adding cartoassets https://github.com/CartoDB/cartodb/commit/76d3f19072f3d50f5ca6dc4b4d848e4c676e471b 
cc @xavijam

**Comment by javierarce** [comment]
:ok_hand:

**Comment by xavijam** [comment]
It should be covered in branch: ```issue-6455```.
