### ISSUE TITLE
Inconsistent attrs for widget API and vizJSON

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#6497]
In vizjson the widget defintion have `layerId` (camelCased), but when retrieved through a GET on the REST API it returns the prop as `layer_id` (snake_case) instead. 

For consistency it would probably be best to use the snake_case since that's what's used for other attrs, right?

**Comment by juanignaciosl** [comment]
Sure, `layerId` was kept for consistency with some examples, but it should really be `layerId`.
