### ISSUE TITLE
Implement table model, needed for new form inputs

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#6516]
Provide means to access a user's tables, and their schema (columns, types etc.)
Will be used for #6508 

My initial idea is to port the minimal things necessary from old models, i.e.:
```js
// setup root model in entry file (e.g. user)
var user = new User({…})
var tables = user.tablesCollection // => Backbone.Collection
var columns = tables.columnsCollection // => Backbone.Collection
console.log(columns.chain().pluck('name')) // => ['id', 'cartodb_id', 'homes', 'some_text', …]
```

cc @xavijam @javierarce makes sense? something missing that you need?

--- 

TODOs
- [x] implement `User` model (the root model that owns a `tables` collection) 
- [x] implement `Table` model + collection
- [x] implement `Column` model + collection

**Comment by xavijam** [comment]
Yep, I feel those are the minimal things we need to keep up with the widgets form :).
