### ISSUE TITLE
connect dataset icon missing in "new map" modal

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#6518]
<img width="996" alt="screen shot 2016-02-04 at 09 05 34" src="https://cloud.githubusercontent.com/assets/36676/12809344/8c9aaed6-cb1e-11e5-869e-172bab3fc9bf.png">

steps to reproduce:

- go to dashboard
- click on new map
- go to connect dataset tab

not assigning any milestone, feel free to reassign

**Comment by xavijam** [comment]
Thanks @matallo, fixing it right now :heart:.

**Comment by juanignaciosl** [comment]
Missing organization signup icons, probably related:

![screen shot 2016-02-02 at 17 15 58](https://cloud.githubusercontent.com/assets/932968/12810200/ee6caad2-cb24-11e5-8a22-50c7645c1d9c.png)

![screen shot 2016-02-04 at 09 50 49](https://cloud.githubusercontent.com/assets/932968/12810202/f12908ba-cb24-11e5-96d2-4c15bf859f8b.png)

**Comment by juanignaciosl** [comment]
![screen shot 2016-02-04 at 09 52 26](https://cloud.githubusercontent.com/assets/932968/12810214/04486e40-cb25-11e5-9e18-72221946b7b4.png)
