### ISSUE TITLE
Setup travis for frontend tests

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#6522]
@zenitraM like I mentioned the other day, there's really no special needs for the frontend tests to be maintained by a custom CI of ours, we only need a `npm install && grunt dev` basically. Since #6458 was merged to master a few days back, which include a new travis cfg it could work now (essentially the same we have for https://github.com/CartoDB/deep-insights.js).

I have planned to wait until early next week (Feb ~8-9th), so all (active) PRs have to time to update with master so we avoid creating unnecessary jobs that runs forever and break (since there were an outdated configuration already existing on master since over a year back.

I suggest we run it in parallel with our normal CI for some time to make sure it works fine before removing the grunt test as part of our own CI.

Sounds reasonable? Have I overlooked anything?

**Comment by zenitraM** [comment]
Looks good to me, if it runs in parallel and both statuses don't overlap and get reported separately let's enable it

**Comment by viddo** [comment]
FYI enabled as of this morning, but only on PRs, so all commits on PRs from now on should yield a test result from Travis too.

**Comment by viddo** [comment]
Disabled now, since it was causing trouble on https://github.com/CartoDB/cartodb/pull/6547

For some reason the CI was trying `bundle install` even if it was not mentioned in the travis cfg, see https://travis-ci.org/CartoDB/cartodb/builds/108069202 My best guess right now, due to some implicit hook of having a Gemfile in the same dir… I'll look into this some time later when I have time, it's not top-prio right now.

**Comment by viddo** [comment]
As it turned out, the problem was that the branch was not up-to-date and had an old travis config, so was trying to install things from +1 year ago… see [travis log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/108069203/log.txt) for the travis log corresponding to the previously mentioned build above.

Have a PR in progress at #6930 for fixing eventual stuff (e.g. git submodule).

**Comment by viddo** [comment]
The Travis CI have been running in parallel for soon 2 weeks. With the exception of some occasional network timeouts on npm install it seems to work fine. 

I close this issue as "done" for now, considering this way we'll have the fast feedback on frontend tests as we wanted. We can decide if it makes sense to maintain the frontend tests from our own CI or not at some later point .
