### ISSUE TITLE
Organisation users can't rename a dataset as another member's existing dataset

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/cartodb#6533]
A user from an organization can import a table with the same name as another existing table from another member of the organization, but cannot rename a table like that.

The reason is that Visualization names must be unique per organization (db): https://github.com/CartoDB/cartodb/blob/251a7cf648155a1354b4d2717a6bf4a3e0c22b8f/app/models/visualization/member.rb#L198

But Table names are only unique per user (schema) and organisation (db): https://github.com/CartoDB/cartodb/blob/251a7cf648155a1354b4d2717a6bf4a3e0c22b8f/app/models/table/user_table.rb#L158

This is an inconsistency between importing tables and renaming tables, and a limitation for the users. In addition the user is told that the 'name is taken' but it may not be easy for him to discover that the name is actually taken by another user of the organisation's data.

On the other hand, forcing table names to always be unique inside an organisation would
simplify some issues related to changes in map configs due to table renaming,
overviews, etc. So we could consider always forcing this, but It would probably
be too restrictive for organiaation users.

**Comment by juanignaciosl** [comment]
I also think that we should allow a user to rename a dataset to a name used by other user. Agree, @javisantana ?

**Comment by javisantana** [comment]
yes
