### ISSUE TITLE
onpremise versions show upgrade dialog on layer limit

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#6534]
- create a map
- add 4 layers
- when you add the 5th one it shows this dialog and should not show the upgrade (raises an error as well)
<img width="1207" alt="screen shot 2016-02-08 at 6 51 24 pm" src="https://cloud.githubusercontent.com/assets/30147/12894084/0badc946-ce95-11e5-8a6f-f9519fc75dbb.png">

**Comment by juanignaciosl** [comment]
Ok, this one is similar: #6536
