### ISSUE TITLE
upgrade link goes to 404 error

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#6536]
Hi! I'm doing smoke tests and while doing "Check that upgrade link goes to upgrade" on the editor it sent me to this 404 page. 

![screenshot 2016-02-09 10 37 44](https://cloud.githubusercontent.com/assets/16247628/12912516/69dd31e4-cf19-11e5-8701-50ca88d0e14b.png)

**Comment by juanignaciosl** [comment]
I think that the actual problem is that onpremise shouldn’t display any “upgrade” link.

**Comment by arianaescobar** [comment]
Oh! 😬 If that's the real problem, it does display it, everywhere...
