### ISSUE TITLE
Missing lock icon Add Dataset modal

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#6537]
On-premises:
The Privacy "lock" icon is missing on the modal:

<img width="1140" alt="screen shot 2016-02-09 at 10 55 42" src="https://cloud.githubusercontent.com/assets/596509/12912955/2a95f586-cf1c-11e5-82c9-7f8ba3bfafad.png">

**Comment by xavijam** [comment]
That was fixed here -> https://github.com/CartoDB/cartodb/pull/6519
Already cherry picked that commit for on-premises version.
Thanks @josecruz for the feedback.
