### ISSUE TITLE
Searching by tag always says '0 maps found'

### ISSUE THREAD

**Issue by sandra-ku** [CartoDB/cartodb#6538]
On dashboard, when I search for a specific tag that I know exists, won't show the map with that tag:
![screen shot 2016-02-09 at 11 32 22](https://cloud.githubusercontent.com/assets/15849615/12913837/4d25ee08-cf21-11e5-84a1-5a2ad2cfb3cb.png)
![screen shot 2016-02-09 at 11 32 34](https://cloud.githubusercontent.com/assets/15849615/12913836/4d223c36-cf21-11e5-942f-648822d8bd64.png)

**Comment by juanignaciosl** [comment]
Search by tag currently requires a colon before. If you type `:lol` instead it will show up. @xavijam , bug or feature?

**Comment by xavijam** [comment]
An image should explain it :)
![screen shot 2016-02-10 at 11 02 11](https://cloud.githubusercontent.com/assets/132146/12944177/c201077a-cfe5-11e5-8990-9dc47aa5f858.png)
