### ISSUE TITLE
Make layer data available on editor first load

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#6564]
Since layers data isn't available when the page is loaded we need to do an extra round-trip to the API to get the associated layers of the visualization; would it be possible to have this information available...

a) as part of the [visualizationData](https://github.com/CartoDB/cartodb/blob/master/app/views/carto/editor/visualizations/show.html.erb#L11)?
b) as a new layerData variable?

Which output is needed, @viddo? (detailed, vizjson...). It'd be great having a needed output example if you have one.

**Comment by viddo** [comment]
I guess it would be what you refer to as _detailed_, what's returned from a GET call to  `/v1/maps/:map_id/layers`

**Comment by juanignaciosl** [comment]
Ok, after a quick talk, I'll add a new JS variable `layersData` containing an array of the outputs of the layer api for that visualization :+1:
