### ISSUE TITLE
Add new CSS for widgets forms

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#6571]
Implement styles for widgets tab pane [Data | Style] pane:
<img width="481" alt="screen shot 2016-02-11 at 17 57 35" src="https://cloud.githubusercontent.com/assets/978461/12983297/fb02c4a6-d0e8-11e5-91f7-3d3c4dca0e51.png">
<img width="485" alt="screen shot 2016-02-11 at 17 57 39" src="https://cloud.githubusercontent.com/assets/978461/12983298/fb085088-d0e8-11e5-8e0d-4423c4882b83.png">

(Tentative scope)

---

TODOs
- [ ] figure out how to apply styles to the backbone forms
- [ ] …
- [ ] implement styles for category data form
- [ ] implement styles for histogram data form
- [ ] implement styles for formula data form
- [ ] implement styles for time-series data form
- [ ] implement styles for style tab (same for all widgets)

**Comment by viddo** [comment]
@piensaenpixel please coordinate with @xavijam and @javierarce before starting on this one. Added the tentative scope for now

**Comment by viddo** [comment]
bump, can this be closed?

**Comment by piensaenpixel** [comment]
i think you can close it
