### ISSUE TITLE
Renaming a dataset from creates incosistent validation of queries

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/cartodb#6576]
This has been observed occasionally when renaming a dataset from the editor, and usually the problem is self-corrected after some time. (but not always, see SB8115312)

After renaming the dataset, in the dataset view, the sql query has not been correctly changed with the new table name so it shows no results; if changed manually with the new table name it works, but it is detected as altered query and the message "No results rows for this query, clear this sql view" appears. If the sql is cleared it reverts to the incorrect state with the old table name.

**Comment by jgoizueta** [comment]
Although I've not be able to reproduce this in a development environment I've traced the problem of SB8115312 to be that it had visualisations where the old table name had not been replaced in the `options` field of the `visualizations` table, wich provokes the problem when the `table_name` key retains the old table name.

**Comment by juanignaciosl** [comment]
@oriolbx you said "Our developers have solved the problem that was affecting your datasets." to the customer. What did "our developers" do? Maybe fix the `table_name` field?

**Comment by juanignaciosl** [comment]
@jgoizueta could you confirm that you just fixed `table_name` at `layers` table, please?

**Comment by javitonino** [comment]
Added logging information, waiting for the bug to pop up again to debug

**Comment by javitonino** [comment]
We have made a lot of improvements in this area and the error hasn't presented itself since the logging was added. Closing.
