### ISSUE TITLE
Editor always uses http widget url from tiler

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#6607]
Editor always uses http widget url from tiler, instead of picking https if it's being requested at https, which triggers a content not valid error:

![screen shot 2016-02-17 at 15 49 15](https://cloud.githubusercontent.com/assets/932968/13116469/5c5899d0-d59c-11e5-96fc-4cecb8aef89d.png)

This error can be reproduced at `6448-Send_widgets_to_tiler` branch in staging. Opening a new editor visualization with widgets will trigger the screenshot errors.

Please fix this at `6448-Send_widgets_to_tiler` branch.

cc @gfiorav

**Comment by xavijam** [comment]
https://github.com/CartoDB/cartodb.js/commit/6330d3d4a90258965fa92c429caf739df56f073c
