### ISSUE TITLE
Try to open named maps log file should no return a 500

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/cartodb#6612]
If the named_maps.log file is not reachable or writable here https://github.com/CartoDB/cartodb/blob/master/services/named-maps-api-wrapper/lib/named-maps-wrapper/named_maps.rb#L30 the platform gets a 500.

This error could be related to some errors that users get when the deploy process switch the folder from one to another.

Is not a high priority bug but will help in the OSS installations

**Comment by iriberri** [comment]
I'm going to close this one as the named maps wrapper does no longer exist, everything was rewritten by @gfiorav.
