### ISSUE TITLE
Remove unnecessary calls to Varnish

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#6621]
Given our current architecture, we can go by touching metadata instead of doing a full call to Varnish. This will work for any table-related invalidation.

cc/ @zenitraM @juanignaciosl

**Comment by juanignaciosl** [comment]
@gfiorav could you write down a summary with what are you going to do about this, please?

**Comment by xavijam** [comment]
+1 to ^^^

**Comment by gfiorav** [comment]
Hey @juanignaciosl @xavijam sorry for the lazzy description. I'll do my best:

We're trying to implement Varnish invalidation with tags in the backend. To do so we need to change the invalidation sentences to use other than current regex. However, it has come to our attention that some of the invalidation calls currently present in the code are redundant.

More precisely, it's table-related cache invalidation that is redundant. We already have a demon called TIS that is fired by database triggers every time the metadata table is updated. So, instead of calling an invalidation, we can call to update cdb metadata and invalidation will happen by itself (we prefer RAILS-fired invalidation be kept at the minimum).

Hence, we split the Varnish tag-invalidation preparation process into two parts:

1. Remove unnecessary invalidations (this ticket)
2. Change necessary invalidation to use tags (future ticket)

**Comment by zenitraM** [comment]
Also ensure that everything that the Rails generates with an `X-Cache-Channel` also has proper tags (`Surrogate-Key`).
