### ISSUE TITLE
Add styles for the icon editor menu

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#6624]
![screen shot 2016-02-22 at 17 05 59](https://cloud.githubusercontent.com/assets/4933/13223921/91be4460-d986-11e5-9ed3-6bce317286b0.png)

**Comment by javierarce** [comment]
Needs: https://github.com/CartoDB/CartoAssets/pull/72

**Comment by piensaenpixel** [comment]
ready @javierarce
