### ISSUE TITLE
Tests stuck after visualizations_controller_spec.rb

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#6638]
Tests sometime stuck after visualizations_controller_spec.rb. [Example trace](https://ci.cartodb.net/job/CartoDB-PR-testing/395/console):

```
09:32:47 Finished: spec/requests/superadmin/users_spec.rb Port: 6003
09:33:17 Finished: spec/models/carto/user_spec.rb Port: 6015
09:38:56 Finished: spec/requests/carto/api/visualizations_controller_spec.rb Port: 6010
12:01:48 Build was aborted
12:01:48 Aborted by viddo
```

[Healthy trace](https://ci.cartodb.net/job/CartoDB-PR-testing/399/consoleFull):
```
11:42:28 Finished: spec/models/organization_spec.rb Port: 6009
11:42:30 Finished: spec/connectors/importer_spec.rb Port: 6012
11:42:34 Finished: spec/models/carto/user_service_spec.rb Port: 6004
11:42:37 Finished: spec/models/carto/user_table_spec.rb Port: 6002
11:42:39 Finished: spec/models/carto/invitation_spec.rb Port: 6002
11:42:40 Finished: services/geocoder/spec/hires_batch_geocoder_spec.rb Port: 6007
11:42:51 Finished: spec/models/user_organization_spec.rb Port: 6013
11:42:55 Finished: spec/models/carto/organization_spec.rb Port: 6010
11:43:09 Finished: spec/requests/superadmin/organizations_spec.rb Port: 6007
11:43:15 Finished: spec/models/carto/user_creation_spec.rb Port: 6011
11:43:33 Finished: spec/requests/superadmin/users_spec.rb Port: 6006
11:44:03 Finished: spec/models/carto/user_spec.rb Port: 6001
11:49:17 Finished: spec/requests/carto/api/visualizations_controller_spec.rb Port: 6013
11:49:17 
11:49:17 real	17m15.048s
11:49:17 user	42m43.326s
11:49:17 sys	7m10.639s
11:49:17 + sh secondTry.sh
11:49:17 Giving a second try to the next specs
11:49:17 spec/models/visualization/table_blender_spec.rb
11:49:17 services/user-mover/spec/user_mover_spec.rb
11:49:17 spec/models/asset_spec.rb
11:49:17 spec/requests/carto/api/presenter_cache_spec.rb
11:49:17 spec/lib/carto/users_metadata_redis_cache_spec.rb
11:49:17 services/importer/spec/acceptance/kml_spec.rb
11:49:17 services/importer/spec/acceptance/raster2pgsql_spec.rb
11:49:17 services/importer/spec/unit/downloader_spec.rb
11:49:17 services/importer/spec/acceptance/zip_spec.rb
```

**Comment by viddo** [comment]
Another job that's also stuck: https://ci.cartodb.net/job/CartoDB-PR-testing/397/console

**Comment by viddo** [comment]
@zenitraM would it be possible to add a timeout on the CI jobs? From what I can see most successful jobs finish within an hour (~45 min typically). Until the root issue is solved it would help to not have some jobs sit around for hours, blocking PRs from passing.

**Comment by javitonino** [comment]
All stuck jobs have in common that the organization_users_controller_spec doesn't finish. Looking into that spec...

**Comment by zenitraM** [comment]
cc @CartoDB/systems (https://github.com/CartoDB/cartodb/issues/6638#issuecomment-188181127)

**Comment by viddo** [comment]
More jobs today:
- https://ci.cartodb.net/job/CartoDB-PR-testing/489/
- https://ci.cartodb.net/job/CartoDB-PR-testing/491/

**Comment by luisbosque** [comment]
Ey @gfiorav, have you changed anything to the tests recently?

**Comment by gfiorav** [comment]
You bet! https://github.com/CartoDB/cartodb/pull/6552/files

**Comment by javitonino** [comment]
Also: https://github.com/CartoDB/cartodb/pull/6641

**Comment by javitonino** [comment]
Maybe solved by https://github.com/CartoDB/cartodb/issues/6881

**Comment by juanignaciosl** [comment]
Let's close this if this doesn't happen anymore.

**Comment by javitonino** [comment]
I'll monitor for a week and close it if no more jobs get stuck.

**Comment by javitonino** [comment]
We have gone a week without tests getting stuck \o/. Closing this. Hail @juanignaciosl !
