### ISSUE TITLE
Check sync behaviour if sync table has a materialized view

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#6640]
Postgres might not allow to drop the table if a view exists from it

**Comment by d4weed** [comment]
I've spotted a behavior that could confirm this.

I have some synced tables that appear to be syncing correctly, but the data inside doesn't actually update to the source's. All of them happen to have materialized views created from them

**Comment by iriberri** [comment]
@d4weed and you're getting a Sync status of "success", right? Do the same status show if you force manually the sync or does this one show any error?

**Comment by d4weed** [comment]
Yes, always success. Actually once the first sync happens, the table seems to be marked as "updated" with the new timestamp and subsequent syncs just do nothing until the source file changes again.

**Comment by iriberri** [comment]
I was checking some related issues and I actually found out what is happening here.

This [piece of code](https://github.com/CartoDB/cartodb/blob/9b496fee7beac79c8d5f47570da8e505902a5b64/app/models/synchronization/adapter.rb#L143-L147) is silently failing, so what happens here is:

* A table gets downloaded and imported from the source
* The old table is renamed to be replaced by the new one
* The old table is dropped: in this case, this drop is failing silently

  ````
  materialized view prueba_3_3_mymatview depends on table importer_591b0768054811e680c20e98b61680bf_to_be_deleted
  Re HINT:  Use DROP ... CASCADE to drop the dependent objects too.
  ```
* The exception is being rescued but ignored, so the table never gets dropped. As it occurs inside a transaction, the table doesn't get renamed either
* The sync is marked as success because no exception happened (it was silenced) but the data is not updated

I am going to report this silent drop crash in another issue, as this is a source of tables that get imported into the database but remain stuck as those are never moved to the user schema neither deleted.
