### ISSUE TITLE
Missing/changed data for torque layers in vizJSON v3?

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#6643]
Found out when I was finalizing #6632, adding a time-series widget for a date column of a torque layer, the call to re-instantiate the map in Windshaft fails with 400 err: `{errors: ["cartocss can't be undefined"]}`.
```
curl 'http://localhost.lan:8181/user/orgowner/api/v1/map?stat_tag=2019bb74-c0e9-11e5-8e1a-080027880ca6' -H 'Pragma: no-cache' -H 'Origin: http://localhost.lan:3000' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-US,en;q=0.8,es;q=0.6,sv;q=0.4' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36' -H 'Content-Type: application/json' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Cache-Control: no-cache' -H 'Referer: http://localhost.lan:3000/user/orgowner/editor/2019bb74-c0e9-11e5-8e1a-080027880ca6/' -H 'Connection: keep-alive' -H 'DNT: 1' --data-binary '{"layers":[{"type":"cartodb","options":{"sql":"select * from districtes_barcelona","cartocss":"/** simple visualization */\n\n#districtes_barcelona{\n  polygon-fill: #5CA2D1;\n  polygon-opacity: 0.7;\n  line-color: #FFF;\n  line-width: 0.5;\n  line-opacity: 1;\n}","cartocss_version":"2.1.1","interactivity":["cartodb_id"],"widgets":{}}},{"type":"cartodb","options":{"sql":"select * from arboles","cartocss":"/** simple visualization */\n\n#arboles{\n  marker-fill-opacity: 0.9;\n  marker-line-color: #FFF;\n  marker-line-width: 1;\n  marker-line-opacity: 1;\n  marker-placement: point;\n  marker-type: ellipse;\n  marker-width: 10;\n  marker-fill: #229A00;\n  marker-allow-overlap: true;\n}","cartocss_version":"2.1.1","interactivity":["cartodb_id"],"widgets":{}}},{"type":"cartodb","options":{"sql":"SELECT 1 as fixed_from_query, * FROM orgowner.districtes_barcelona LIMIT 5","cartocss":"/** simple visualization */\n\n#districtes_barcelona{\n  polygon-fill: #7B00B4;\n  polygon-opacity: 0.2;\n  polygon-comp-op: multiply;\n  line-color: #FFF;\n  line-width: 0.5;\n  line-opacity: 1;\n}","cartocss_version":"2.1.1","interactivity":["cartodb_id"],"widgets":{}}},{"type":"torque","options":{"interactivity":[],"widgets":{"3ad066e4-cfb2-4577-b618-9f2293ae0741":{"type":"histogram","options":{"column":"end_at","bins":255}}}}}]}' --compressed
```

The options data of the torque layer [in the torque time-series example on Deep-Insights](https://github.com/CartoDB/deep-insights.js/blob/0ab01280406c546f5c8a4d53b8433273fa7ce8c5/examples/torque-time-series-widget.html#L123-L152) is different than what's returned by the vizJSON here, (at least) `cartocss`, `cartocss_version`, `sql`, and `sql_api_template` seems to be missing. @javisantana and @rochoa can hopefully give more info on what's needed/changed.

**Comment by juanignaciosl** [comment]
Vizjson v3 [is the old vizjson with widgets addition](https://github.com/CartoDB/cartodb/blob/master/app/controllers/carto/api/vizjson3_presenter.rb#L14), nothing has been removed from the old one. I think that the problem is that DI options at that example are different than the options at the ("old") vizjson as well. [This is a working vizjson](https://team.cartodb.com/u/juanignaciosl/api/v2/viz/aaa2d944-4969-11e5-b416-0e0c41326911/viz.json). It has `sql_api_template` but it hasn't `cartocss`, `cartocss_version` or `sql`.

**Comment by rochoa** [comment]
Well... I don't know what to say because this seems something vizjson/di.js/cartodb.js related. Windshaft is doing nothing but just failing because of a missing required property in the torque layer:

```json
{
    "options": {
        "interactivity": [],
        "widgets": {
            "3ad066e4-cfb2-4577-b618-9f2293ae0741": {
                "options": {
                    "bins": 255,
                    "column": "end_at"
                },
                "type": "histogram"
            }
        }
    },
    "type": "torque"
}
```

**Comment by viddo** [comment]
Then there must be something required in cartodb.js (because DI doesn't need it). I guess it must have been something that changed in the v4 branch at least?@alonsogarciapablo could this related to how the dataviews are serialized or something by chance?

**Comment by javisantana** [comment]
the problem is with a naming change we decided to do, we changed `tile_style` to `cartocss` some time ago. We decided that everything was going to work only with `cartocss` for the new version. 

We have 2 ways to fix this:

1) send `cartocss` instead of `tile_style` for all the layers in the viz.json
2) fix the naming here https://github.com/CartoDB/cartodb.js/blob/v4/src/vis/layers.js#L90 

I do prefer the 1 because it's the way it should work

**Comment by juanignaciosl** [comment]
Some questions:
- Your suggestion covers `cartocss`, but there're two more missing attributes, do you need them? Those are: `cartocss_version` and `sql`.
- `tile_style` is stored inside `options`. I think this involves some backend but I'm pretty sure frontend also sends it.
- I guess that `tile_style` -> `cartocss` transformation should be done only for vizjson v3, isn't it?

**Comment by javisantana** [comment]
1) yes, `query` should be `sql` and cartocss_version should be included
2) we will change if needed
3) yes, only v3

**Comment by juanignaciosl** [comment]
Great, on it :+1:
