### ISSUE TITLE
Geocoding dialog has wrong "search" icon in corner when should be "X"

### ISSUE THREAD

**Issue by andrewbt** [CartoDB/cartodb#6676]
<img width="1136" alt="screen shot 2016-02-24 at 11 18 17 am" src="https://cloud.githubusercontent.com/assets/2013555/13292107/8101eeac-dae8-11e5-9ea0-c38d849aa96d.png">

Again, account is on Google Europe cloud

**Comment by xavijam** [comment]
It was due to a font-icon problem, but it is fixed now, doesn't matter the user type.
