### ISSUE TITLE
Named maps are not working in the new editor anymore

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#6691]
Basically the request after the map instantiation is giving a 404 error. Tested in production.

I'd like to review it with @juanignaciosl and @rochoa.

**Comment by juanignaciosl** [comment]
Uhm, I just realized that in my current development branch named map is instantiated but widgets are not returned :'(.

**Comment by rochoa** [comment]
Can you share some examples? A named map definition (json) will do.
