### ISSUE TITLE
When opens add-widget modal, it silently fails but window doesn't say anything

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#6697]
## STR

- Create or use a map with a private dataset on it.
- Go to the new editor url.
- Open the "new widget" modal.
- It loads forever.
- Check browser console, it returned a 401 error (Unauthorized). 

Looks like we have forgotten the `api_key` in those requests. But in any case we should provide an error state, shouldn't we?

**Comment by viddo** [comment]
cc @urbanphes one example of those error cases that may happen, which could be due to a programmatic fault (like it seems in this case), or the system denying access for whatever reason.
