### ISSUE TITLE
Time-series options appear with radio and checkbox inputs

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#6698]
![screen shot 2016-02-25 at 19 17 12](https://cloud.githubusercontent.com/assets/132146/13329493/77acbfc8-dbf4-11e5-8b86-9d7f682b23ca.png)

cc @viddo

**Comment by viddo** [comment]
Fixed in https://github.com/CartoDB/cartodb/commit/81086ea292f74777492fe4ec1a76a61c5809dd96, will merge tomorrow
