### ISSUE TITLE
Fix http authentication autocreation with organizations in subdomainless URLs

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#6710]
Testing Kerberos integration @danicarrion found out that users are not being created inside organizations for subdomainless URLs.

The patch is replacing

```
subdomain = CartoDB.subdomain_from_request(request)
```

with

```
subdomain = CartoDB.subdomainless_urls? ? request.host.to_s.gsub(".#{CartoDB.session_domain}", '') : CartoDB.subdomain_from_request(request)`
```

in `app/controllers/signup_controller.rb`.

**Comment by juanignaciosl** [comment]
cc @javisantana

**Comment by javisantana** [comment]
we should merge this to the 3.12.X branch in order to release a new onpremise version (maybe we don't need to do the OVA, but at least tag and create new NEWS file) 
cc @azamorano @santisaez

**Comment by danicarrion** [comment]
I can patch the source code manually and create the .deb from there, but of course having a tagged release would be perfect
