### ISSUE TITLE
Image annotations not shown in new editor

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#6716]
The element is added but the css is not there.

**Expected:**

something like
<img width="1280" alt="screen shot 2016-02-26 at 18 49 04" src="https://cloud.githubusercontent.com/assets/4222826/13360490/d71b8820-dcb9-11e5-86d6-4fa0a813c8cc.png">

**Actual result:**

<img width="1280" alt="screen shot 2016-02-26 at 18 48 23" src="https://cloud.githubusercontent.com/assets/4222826/13360514/e645ba64-dcb9-11e5-9e55-9e18d867564a.png">

cc/ @xavijam

**Comment by javisantana** [comment]
we are not expecting to see them
