### ISSUE TITLE
Weird style in tag

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#6734]
Missing style in list tables (READ)
![image](https://cloud.githubusercontent.com/assets/1214201/13410161/89a5397c-df36-11e5-927e-802870f3df44.png)

**Comment by MariaCheca** [comment]
After testing it, everything is ok with this tag, so closing! :)

![screen shot 2016-03-03 at 12 06 07](https://cloud.githubusercontent.com/assets/2141690/13492457/618983ae-e138-11e5-9b78-b9742a6637c7.png)
