### ISSUE TITLE
No error code after georeferencing using the Lon/Lat columns option

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartodb#6736]
If an error happens in a dataset after georefercing using the Georeference Lon/Lat columns option, CartoDB is not showing the error code, but it shows the error ```Failed to load resource: net::ERR_EMPTY_RESPONSE``` in the console of the browser.

See the image:

![screen shot 2016-03-01 at 10 28 20](https://cloud.githubusercontent.com/assets/11177693/13423773/369ff714-df9d-11e5-9e5c-bfc40bc9b1d7.png)

**Comment by jgoizueta** [comment]
In this case it seems there was some network problem that prevented the front end getting the response of the geocoding call (PUT to `https:/team.cartodb.com/u/:user/api/v1/tables/:table`). So the UI couldn't have an error code I don't think that it could do anything better than the generic message.

But in genera,l if an error occurs during geocoding (most likely while [executing SQL](https://github.com/CartoDB/cartodb/blob/66c3c8aa92695ad5f541c565ed9d5061ef01cf93/services/table-geocoder/lib/internal-geocoder/latitude_longitude.rb#L36))
the front end will get a 400 (from [here](https://github.com/CartoDB/cartodb/blob/66c3c8aa92695ad5f541c565ed9d5061ef01cf93/app/controllers/api/json/tables_controller.rb#L114)) and there will also be a generic error message in the UI.

I'll leave this information here, but I'll close this now, as. Please @oriolbx reopen this if you have some additional information or think this is actually a problem we should consider (having only a generic error message for failed geocodings).
