### ISSUE TITLE
Infowindow and tooltip templates are not including the newest version

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#6740]
CartoDB.js `v4` includes new markup (examples: [infowindow](https://github.com/CartoDB/deep-insights.js/blob/master/examples/airbnb_and_closest_metro.html#L319) and [tooltip](https://github.com/CartoDB/deep-insights.js/blob/master/examples/airbnb_and_closest_metro.html#L379)) and styling for infowindows and tooltips but viz.json files are providing the templates that are coming from the current version of the editor:

<img width="157" alt="screen shot 2016-03-01 at 16 48 33" src="https://cloud.githubusercontent.com/assets/390398/13432354/79756d46-dfcd-11e5-817d-4f38a4531375.png">

I'm not sure how we can fix this because infowindows and tooltips should still work in the current version of the editor but at the same time we want new templates in the viz.json.

cc: @xavijam @juanignaciosl @javisantana

**Comment by javisantana** [comment]
this should change in viz.json v3.

**Comment by xavijam** [comment]
Yes, and we decided to start something from scratch, so old maps should not work with new things. That covers infowindows, tooltips, overlays, etc.

**Comment by saleiva** [comment]
Hi guys, could we try to prioritize this? We are building some PoCs with the new editor and this would gives us some air :)
