### ISSUE TITLE
Fix new embed protected maps

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#6743]
We need to add `auth_token` to CartoDB.js in https://github.com/CartoDB/cartodb/blob/add-csrf-autheticity-token-verification/vendor/assets/javascripts/cartod1b/cartod1b.uncompressed.js#L47977 and prepare the embed code to pass this to the tiler request. So, basically:

- [] front stuff (@alonsogarciapablo)
- [] back stuff (@gfiorav)

Not urgent but it would be nice to share new editor stuff with password to control unwanted spreading :).

cc/ @xavijam

**Comment by alonsogarciapablo** [comment]
This is a duplicate of CartoDB/cartodb.js#1226. I don't think there is any backend work to be done since we get a list of tokens in the viz.json.... Thoughts @gfiorav? Can I close this?

**Comment by gfiorav** [comment]
Sure @alonsogarciapablo !
