### ISSUE TITLE
Base analysis layer endpoint

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#6786]
`Analysis` base model required attributes: `id: UUID`, `visualization_id: UUID`, `params: JSON`.

Endpoint: `/api/v3/viz/:visualization_id/analysis(/:id)`.

JSON format example:
```javascript
{
  id: ‘a1’,
  type: ‘trade-area’,
  params: {
    id: ‘a0’,
    type: 'source',
    params: {
      query: 'select * from subway_stops'
    }
}
```

cc @viddo @gfiorav @javitonino @xavijam

**Comment by juanignaciosl** [comment]
@viddo I'm adding an `analysis.id` `UUID` surrogate column as usual for convenience. The `:id` in the url will accept both that "internal" UUID and _the first level `params.id`_. Does it sound ok for you?

**Comment by viddo** [comment]
If I understand you correctly you mean _first level id_" (not what's inside params), right? I.e. _/api/v3/viz/:visualization_id/analysis/**a1**_ and _/api/v3/viz/:visualization_id/analysis/**generated-uuid-for-a1**_ would yield the same result?

**Comment by juanignaciosl** [comment]
No with "first level id" I meant "first level id _inside the json". Since analysis is scoped to the visualization, it's enough, and I guess you'll use it as a "natural id".

**Comment by juanignaciosl** [comment]
PD: and yes, those urls will return the same result.

**Comment by viddo** [comment]
:ok: :+1:
