### ISSUE TITLE
Georeference UI Admin Regions: 2nd Question is Irrelevant with Country Data

### ISSUE THREAD

**Issue by michellechandra** [CartoDB/cartodb#6788]
### Context
When geocoding based on country names, the second question in the UI is irrelevant ("Select Your Country Data"). If the user inputs their country column in answer to that 2nd question in the form, the georeferencing will fail. By leaving that 2nd question blank, the georeferencing succeeds. 

### Process
Import a dataset with a column of country names that need to be georeferenced
Choose the "Admin Regions" georeferencing option in the UI
Select the country column for both form questions ("Select Your Region Name" and "Select Your Country Data")
The georeferencing will fail
**If you have country names, you only need to input your column in answer to the first question "Select Your Region Name" and you must leave the second form field blank otherwise the georeferencing will fail.**
![screen shot 2016-03-04 at 4 33 31 pm](https://cloud.githubusercontent.com/assets/5423288/13540937/5460ab2c-e227-11e5-9f4c-64608317cbe5.png)

**Comment by ztephm** [comment]
S/B 9099020

Client only has 'country' column and is trying to georef by admin region - if you only choose second pulldown the 'Continue' button is inactive:

![screen shot 2016-06-03 at 3 34 36 pm](https://cloud.githubusercontent.com/assets/1779444/15790691/b6f92262-29a0-11e6-8e73-b9df8235a927.png)

**Comment by saleiva** [comment]
To apply on the analysis UI.
Also, we should rethink the labels on the fields. Right now they are hard to understand.

**Comment by saleiva** [comment]
Dupe!
