### ISSUE TITLE
enforce complex passwords for organization users

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#6790]
Some organizations require their user to setup complex passwords, we need a way to configure an organization so their users need to set complex ones.

Specifically, the passwords must include:
 - 8+ characters
 - both letters and numbers
 - at least one 'symbol' ($&@# etc)

**Comment by javisantana** [comment]
cc @saleiva @xavijam @juanignaciosl

**Comment by juanignaciosl** [comment]
This is required only for signup page, or for organization user creation (performed by organization owner) as well?

**Comment by javisantana** [comment]
I'd say for every single way to create an user

**Comment by javisantana** [comment]
cc @vhamer

**Comment by gfiorav** [comment]
Hey, @javisantana, it gets tricky to distinguish letters and symbols when you get to non US ascii characters. 

Would `2Patrañas` count as having 1 symbol?

**Comment by javisantana** [comment]
I'd say no.

Why don't we define "symbol" as the symbols defined in ascii table?

**Comment by gfiorav** [comment]
Ok, @javisantana no problem with that.

How we define letter according to the ascii table is what i'm asking. Is Å a letter?

**Comment by vhamer** [comment]
hi @gfiorav , @javisantana -

thanks for working on this issue. the customer who needs it is ny state, and you can see their password requirements here: http://www1.nyc.gov/assets/doitt/downloads/pdf/external_id_mgmt_and_password_policy.pdf

as you can see on page 2, they have a very specific list of non-alphanumeric symbols that count: { } [ ] , . < > ; : ‘ “ ? / | \ ` ~ ! @ # $ % ^ & * ( ) _ - + =

this list is consistent with what i've seen elsewhere, so can we simply use this list?

**Comment by gfiorav** [comment]
Thanks @vhamer, that is extremely useful! 

I'll definitely use that list, but let's make sure we keep it international :)

Having a look now.

**Comment by gfiorav** [comment]
Closed via #6907

**Comment by xavijam** [comment]
:clap: :clap: :clap:
