### ISSUE TITLE
Explain query returns empty rows

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb#6812]
Performing an explain return empty rows: 

![selection_001](https://cloud.githubusercontent.com/assets/9017165/13601007/19abb284-e52d-11e5-86ef-dc8059c461ad.png)

 Maybe due to parsing.  And forcing an allowed format (http://www.postgresql.org/docs/current/static/sql-explain.html ) lead to query parsing error:

![selection_002](https://cloud.githubusercontent.com/assets/9017165/13601040/5cf051e4-e52d-11e5-9d5c-7d7c11ea4eff.png)

**Comment by iriberri** [comment]
https://github.com/CartoDB/cartodb/issues/2756

**Comment by AbelVM** [comment]
duplicated
