### ISSUE TITLE
Fix CSRF error for database groups API

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#6813]
A recent change in CSRF protection is making database groups api fail (`app/controllers/carto/api/database_groups_controller.rb`).

Error trace: 

```
Filter chain halted as :verify_authenticity_token rendered or redirected
Completed 403 Forbidden in 1.3ms
```

cc @jvillarf

**Comment by gfiorav** [comment]
Thanks for writing the issue out, @juanignaciosl
