### ISSUE TITLE
add noindex to public pages

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#6816]

**Comment by beloneys** [comment]
Hey @matallo, could you please hold on with this issue?
Thanks :)

B

**Comment by javisantana** [comment]
Adding @saleiva to the loop, I though we actually wanted google index this.

**Comment by saleiva** [comment]
What is the reason for this? +1 and -1?

**Comment by beloneys** [comment]
Hey,

Sending an email with +1 -1 and including @noguerol on it :)

**Comment by matallo** [comment]
how shall we finally proceed with this @beloneys ?

**Comment by beloneys** [comment]
Assigning to me as I'm studying the way to make a new project possible in terms of SEO.

Thanks Matallo!
