### ISSUE TITLE
geometry type mixing after geocoding by different type

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/cartodb#6817]
I had a dataset which was automatically geocoded to points (based on city names) but I needed it to be polygons off of a zip code column, so I re-geocoded by postal code admin areas, and got the following response (partially successful):

<img width="418" alt="screen shot 2016-03-08 at 08 37 02" src="https://cloud.githubusercontent.com/assets/1041056/13603188/63f3dbc4-e509-11e5-9317-406f4fd7c0e4.png">

Obviously there are mixed types, but the UI sets the `MultiPolygon` to `Point`.

Steps to reproduce:

1. Import [this dataset](http://files.zillowstatic.com/research/public/Zip/Zip_Zhvi_SingleFamilyResidence.csv)
2. Make sure 'guess types' is selected
3. Notice that the_geom is filled with lat/longs (points)
4. Geocode (orange geo button) by `regionid` as Postal Code, 'United States' as Country
5. Select administrative area to get polygons
6. Get a table of mixed geometry types, and the UI only choosing one

IMO, there should be a warning in the Geocoding that the user is attempting to get back a different geometry than is already in the table. If the user accepts this risk, either:

1. The old geometries which are not geocoded should go to nulls, or
2. The old geometries, if lines or polygons, should go to points if the new geometry is points

**Comment by iriberri** [comment]
I'd say the way to go here would be to disable guessing (which will disable geocoding by default) and then geocode your table as you wish.

The code is not restricting different geocoding results that might give different geometric types that the ones available in the dataset, but you probably know already that multigeometry layers are not supported. Interesting issue to take into account for usability improvements. :-)

**Comment by iriberri** [comment]
Gonna close this as we have a previous issue where we can keep working: https://github.com/CartoDB/cartodb/issues/1002

**Comment by ohasselblad** [comment]
Thanks!
