### ISSUE TITLE
map URL not working on the new editor

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#6833]
https://team.cartodb.com/u/saleiva/viz/56f0a9a6-f93a-11e2-8a7e-3085a9a9563c/map it gives a js error

**Comment by javisantana** [comment]
works for me, please, report it the concrete error if continue failing

**Comment by saleiva** [comment]
Uncaught TypeError: Cannot convert undefined or null to object
editor.js:37Uncaught TypeError: Cannot convert undefined

**Comment by saleiva** [comment]
LMK how can I give you more info

**Comment by xavijam** [comment]
After checking today, both, old and new embed, are working. Could you check it again please?

**Comment by xavijam** [comment]
After checking with @saleiva, he is right and it is not working in the new editor, private part.
Note: https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb3/editor.js#L37
