### ISSUE TITLE
importing a geojson with relative url values detects them as dates

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#6853]
this one is _funny_

**steps to reproduce**

- go to dashboard
- import geojson from url

**expected behaviour**

- values such relative urls (i.e. `//images.contentful.com/xts27qnup0jr/47Yq6W7PgAKQKGQ4cSG6oa/7c8d8296ffa3481efd93b2bb2cefc86c/stamen.png`) should import as strings

**actual behaviour**

- ogr2ogr tries to import it as date, despite unchecking guess types

```
true: Fallback: Disabling autoguessing because there are wrong dates in the source file
...
true: ogr2ogr output:          ERROR 1: COPY statement failed.
ERROR:  date/time field value out of range: "2000/00/00"
HINT:  Perhaps you need a different "datestyle" setting.
CONTEXT:  COPY importer_511ec88ce77b11e592e30ef24382571b, line 1, column logo: "2000/00/00"
```

**Comment by iriberri** [comment]
Thanks for reporting! <3

**Comment by ethervoid** [comment]
It seems a bug in the GeoJSON driver for ogr2ogr. I've reported it and I'm waiting for an answer https://trac.osgeo.org/gdal/ticket/6452#ticket

**Comment by ethervoid** [comment]
The issue was fixed in ogr2ogr, this should be fixed as soon as a new ogr2ogr binary is deployed

**Comment by matallo** [comment]
BOOM

**Comment by rafatower** [comment]
do you have any file to test and confirm?

**Comment by ethervoid** [comment]
Here it is
[untitled_table_1.geojson.zip](https://github.com/CartoDB/cartodb/files/254924/untitled_table_1.geojson.zip)

**Comment by rafatower** [comment]
it is still failing :(

**Comment by ethervoid** [comment]
Have we updated the ogr2ogr to that version? AFAIK we deploy a version prior to that fixes

**Comment by rafatower** [comment]
Nope, that fix is in [33956](https://trac.osgeo.org/gdal/changeset/33956) and we're on r33718 :/

**Comment by rafatower** [comment]
We have to release a new gdal-static-bin package. And I'd like someone else to be able to do so, so I added this issue to myself to be tackled in order to have this one fixed:

https://github.com/CartoDB/gdal/issues/1

Also releasing gdal-static-bin which is a pretty core package for the importer requires good testing.

Sorry but not top priority, unless it is a blocker for the new builder @matallo

**Comment by iriberri** [comment]
I have a couple ogr2ogr more in mind -- still unreported to them, as I'm unable to use their tracker from any of my browsers, that would be nice to add if we do a new release. I'll try to report them at my windows computer at home to see if we can include them too.

**Comment by rafatower** [comment]
FIxed in `gdal2.1-static (2.1.1-precise1)`. We need to regression test it and deploy it: https://launchpad.net/~cartodb/+archive/ubuntu/gis-testing/+packages

**Comment by iriberri** [comment]
We just released the new ogr2ogr version. This is fixed. :-)

**Comment by matallo** [comment]
:_)
