### ISSUE TITLE
Invitations => signup enabled

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#6872]
For organization invitations to work you need to enable the signup page by adding a whitelisted email. Currently this is not explicit, and owners can send invitations. We should prompt the owner to enable the signup page when he tries to send an invitation.

cc @xavijam @michellechandra @yasharora73

**Comment by MariaCheca** [comment]
@josecruz you're in charge of the design part :) If you have any question ask @xavijam or me.

**Comment by juanignaciosl** [comment]
Have you already come up with a solution proposal?

**Comment by xavijam** [comment]
We need changes in the design part and they will be tackled next week (@josecruz is on charge).
We will implement it at that time.

cc @saleiva

**Comment by MariaCheca** [comment]
@juanignaciosl the design team will take care of the solution. What we've come up with is to prevent the org owner from inviting users if the premises discussed are not set, disabling the button and informing him/her in some way about what to do to enable the feature :)

**Comment by juanignaciosl** [comment]
Ok, great :-)

**Comment by josecruz** [comment]
Hey! Last design update, what do you think?
https://invis.io/YF6L22LT2

cc @saleiva for review

**Comment by saleiva** [comment]
very well done @josecruz, the only thing is the colors and the blue of the button on the warning. Apart from that, I like it!

**Comment by josecruz** [comment]
Already updated :) 
Same link: https://invis.io/YF6L22LT2

**Comment by MariaCheca** [comment]
I like your proposal a lot @josecruz, but we're missing the second premise to invite: enabling the organization signup page. In your solution the owner can add an email domain to the whitelist, but it still needs to enable the signup switch.

I would simply add that second step in the user message, something like:
 "If you want to invite "@whatever.com" users you need to add this domain to your whitelist **and enable your organization' signup page** to proceed the invitation".

What do you think? cc/ @saleiva

**Comment by juanignaciosl** [comment]
@MariaCheca no, that should be enough (I guess slide 5 should actually be before 4). Whitelisting is enough for enabling signups, there's no "signup switch":

![screen shot 2016-03-28 at 11 52 13](https://cloud.githubusercontent.com/assets/932968/14075712/a9dd490e-f4db-11e5-807c-fc694fc5938c.png)

**Comment by xavijam** [comment]
As @juanignaciosl has pointed out, there is no need to enable anything if you want to invite someone to the organization. It would be interesting if we try this feature before implementing any update/addition, please.

**Comment by MariaCheca** [comment]
If there's any whitelisted email domain but the signup switch is not enabled, the user will se something like:

![screen shot 2016-03-28 at 12 19 08](https://cloud.githubusercontent.com/assets/2141690/14076142/57161968-f4df-11e5-83ad-778010ddca80.png)

Without a form to create an account, we are at the same point :)

If there are no whitelisted domains, even if signup is enabled or not, the link included in the invitation email leads to a 404. That's why I insisted in the necessity of checking those two steps for a proper flow.

cc/ @xavijam @juanignaciosl

**Comment by xavijam** [comment]
Which is the URL that is receiving the invited user?

**Comment by MariaCheca** [comment]
This one: `https://[ORGANIZATION_NAME]/.cartodb-staging.com/signup?email=[INVITED_USER_EMAIL]&invitation_token=[INVITATION_TOKEN]`

**Comment by xavijam** [comment]
In that case, it is likely there is a bug, because form should appear and let that user signup with that "invitation token", shouldn't it @juanignaciosl?

**Comment by juanignaciosl** [comment]
First of all, my first statement is still true: there's no sign **up** switch, only sign **in** switches.

It's not a *bug* but a missing configuration check. If you don't allow username+password sign ins, sign up page won't display it (it makes no sense). If you don't allow Google sign in, sign up won't display Google sign up button. _And if you don't enable any of them, none will be displayed_. That's a situation that we should also validate: if the user add domains to whitelist he should enable at least one sign in option.

**Comment by juanignaciosl** [comment]
PS: having an "invitation token" is not enough to display it, since he will need to be able to login later as well.

**Comment by MariaCheca** [comment]
Hum, I was wrong :sweat_smile: I was confused with the functionality of the "Username/password" switch. So I'm going to fix that missing check to render the forms.

**Comment by juanignaciosl** [comment]
Oh, just to be 100% clear, with "check" I didn't mean "checkbox/toggle/whatever UI field" but *validation*. I meant that `Organization` modelo should validate that some login option is enabled if whitelist is not empty.

**Comment by MariaCheca** [comment]
All clear :+1:

**Comment by MariaCheca** [comment]
About the way to send the request to add the email domain to the whitelist, there are two options discussed:

1. Send the request in the form submission, making the "Add to whitelist" button only allow to enable the submit button. Then, once in the controller it will first add the domain to the whitelist and then send the invitation.

2. The "Add to whitelist" button will send the request, and if it's done it will return _something_ allowing the owner to send the invitation.

What do you think @juanignaciosl? cc @xavijam

**Comment by juanignaciosl** [comment]
Uhm. On one hand, from an API point, of view option 2 is cleaner because it keeps both concerns (adding to whitelist and sending the invitation) separated. But on the other you can implement 1 with a single request, and making the invitation endpoint (which btw is safe, since it's owner-only) add the domain automatically if the user has requested it with a flag is not crazy either. Since adding a domain can't fail for any valid email address it can work.

I haven't a clear winner here. If you can add the "add domains to whitelist if needed" flag in a clean way, I'd choose 1, because it only requires one request and first adding the domain but then not sending the invitation might not be 100% clear for the user. Nevertheless 2 is not wrong at all, if you think it's better or easier, go for it.

**Comment by MariaCheca** [comment]
I agree with you, plus I was concerned about the safe thing. I can implement the first option making the two steps (first add the domain to the whitelist and second invite the user(s)) making the difference between the parts as clear as possible, so if it's ok with you I'll go for it :)

**Comment by juanignaciosl** [comment]
A better redesign has come to mi mind, I've talked to @MariaCheca about it and we agree that it's simpler and more accurate for the user. She'll try to implement it to verify that it's feasible but makes a lot of sense.

In the issue I did an inaccurate problem statement:
> For organization invitations to work you need to enable the signup page by adding a whitelisted email. Currently this is not explicit, and owners can send invitations. We should prompt the owner to enable the signup page when he tries to send an invitation.

This is not 100% accurate, since it mixes problem and solution. A better problem statement would be:
> A user **with a valid invitation** can't signup in the organization.

That being said, a much better proposal for the signup issue is obvious:
> **Organization signup page should work for valid invitations even if the organization hasn't whitelisted domains**.

This is better for the organization owner because he doesn't need to whitelist a full domain just to invite a single user. And from a technical point of view, since token is in the GET request we know in advance that the signup request comes from a legit invitation.

Previous effort is not thrown away, though, since there's still one need that can be addressed with @josecruz design and @MariaCheca WIP: if the organization user sends an invitation, some sign **in** mechanism (either user/password or Google Login) must be enabled. So, instead of requesting confirmation for whitelisting domain, the invitation modal should request confirmation for enabling sign in if there's no sign in mechanism enabled.

/shrug I'm sorry about not working out this solution from the very beginning :_)

**Comment by MariaCheca** [comment]
I agree with you, this solution is more accurate and easy for the user. There shouldn't be any problem with the design as far as we can keep the error message design to notify the org owner in case there's no sign in method enabled, changing the texts of course.

**Comment by xavijam** [comment]
There is no problem @juanignaciosl if we finally find the best way to do it ;).
