### ISSUE TITLE
CDB_TouchMetadataTable fails increasing recently.

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#6879]
Context: https://rollbar.com/vizzuality/CartoDB/items/15607/

I'm starting this thread to gather info and hopefully a way to reproduce this.

Deleting a table with the sql api and running ghost tables _does not_ reproduce this problem. I have found two things researching a bit:

1. Current ghost table code avoids unlinking deleted sync tables (so current code does not support unlinking sql-api-deleted sync tables). Anyway it does not cause this error trace (it does cause an "the schema parse returned no rows... table probably doesn't exist" and the ghost table fails when trying to be deleted through the UI).
2. When we started metadata touching based on oids, I overlooked a piece of code related to syncs, so that still invalidates based on the full qualified name (https://github.com/CartoDB/cartodb/blob/master/app/models/synchronization/adapter.rb#L98). I was hoping to be able to link this to our problem but I’m not sure this code will run in a situation other that after editor-fired cartodbyfication

@rafatower proposes this should be fixed at extension level.

cc/ @rafatower @zenitraM @juanignaciosl

**Comment by jgoizueta** [comment]
In the failiing cases It seems either rec.nspname or rec,proname or schema_name or table_name is NULL here:

https://github.com/CartoDB/cartodb-postgresql/blob/2e186c856553b26b313a45c3149069635034311b/scripts-available/CDB_TableMetadata.sql#L109-L111

**Comment by rafatower** [comment]
to give a bit more context, this is the full trace from pg:
```
Sequel::DatabaseError: PG::Error: ERROR: query string argument of EXECUTE is null
CONTEXT: PL/pgSQL function _cdb_tablemetadata_updated() line 43 at EXECUTE statement
SQL statement "WITH upsert AS (
UPDATE cartodb.cdb_tablemetadata
SET updated_at = NOW()
WHERE tabname = tablename
RETURNING *
)
INSERT INTO cartodb.cdb_tablemetadata (tabname, updated_at)
SELECT tablename, NOW()
WHERE NOT EXISTS (SELECT * FROM upsert)"
PL/pgSQL function cdb_tablemetadatatouch(regclass) line 3 at SQL statement

**Comment by rafatower** [comment]
After talking with Alex and Raúl, I'll implement a trade-off solution.

**Comment by gfiorav** [comment]
Hey @rafatower I can implement a flag for the destroy method easily. If you wan't I can avoid touching when deleting from ghost tables. 

It's always safer to invalidate just in case though. Please ping me on whatever thread you implement the solution.

Thanks!

**Comment by rafatower** [comment]
question: what is the sense of stubbing `update_cdb_tablemetadata` here? 08874f242

I can reproduce the issue with a test but not stubbing that of course. I don't think we should stub it, especially taking into account all the `link_ghost_table` tests are there.

**Comment by gfiorav** [comment]
@rafatower feel free to improve on it!

Bare in mind that there is an upcoming ghost table refactor that includes proper tests https://github.com/CartoDB/cartodb/pull/6883

**Comment by rafatower** [comment]
I was wrong about the failure scenario: the code intentionally ignores sync tables (good):

https://github.com/CartoDB/cartodb/blob/af4575774369065175805dcc7d0748669aee4902/app/models/user.rb#L1178-L1188

Adding a `rescue` can be worse than doing nothing so I just dropped that option. We know yet race conditions may happen but I don't think we should put any more effort on this until the DDL triggers arrive.

I'd close this issue for the moment and reopen it if after the refactor you deem it necessary.

**Comment by gfiorav** [comment]
Hey @rafatower thanks for investigating.

I'm sorry if our conversation didn't come completely clear. Ghost tables avoids sync tables, indeed. I thought that your concern was that ghost tables might fire when a table is being renamed during the sync process.

One race condition that is certainly bound to happen is when ghost tables are launched as a resque job and synchronously at the same time (that can happen in current code). New Ghost tables that will be released next week blocks ghost tables from happening at the same time with a lock stored in the users metadata redis database. I've also added monitoring to detect the duplicate tables problem, so we'll know when it happens.

I'll follow the evolution of this problem, thanks again :)

**Comment by gfiorav** [comment]
Passing ST for concurrent ghost tables, @oriolbx tried syncing a table, waiting for a force sync and then changing sync options to "never". The error produces the trace in this ticket. I'm still confirming why.

cc/ @juanignaciosl

**Comment by gfiorav** [comment]
From further investigation: It seems as the code for `fix_oid` is not running after a sync is removed: https://github.com/CartoDB/cartodb/blame/master/app/models/synchronization/adapter.rb#L68.

That explains the failures related to setting a sync to "never".

I wish this would explain all the issues but I don't think that all the eventualities we're seeing in Rollbar are all for formerly synced tables. 

I'm going to add check and update `table_id` to the real `oid` of the table in the `after_destroy`, but it's ugly and we should seriously consider revamping syncs at this point.

**Comment by gfiorav** [comment]
Ok, so I think I know what's wrong. I've found that the code for `fix_oid` isn't updating the `table_id` as it should. The typo seems to be from May, but it has been become important ever since we invalidate touching cdb_tablemetadata rather than performing a varnish call.

The code is https://github.com/CartoDB/cartodb/blame/master/app/models/synchronization/adapter.rb#L71.
```ruby
def fix_oid(table_name)
    actual_oid_from_user_database = database.fetch(%Q{SELECT '#{table_name}'::regclass::oid}).first[:oid]
    table = ::Table.new(:user_table => ::UserTable.where(name: table_name, user_id: user.id).first)
    table.table_id = actual_oid_from_user_database.to_i
    table.save
end
```

The thing is that you can't change `Table`'s `table_id` and have it propagate to `UserTable`. You must either perform the update on the `UserTable` object itself or use `Table`'s `.set_table_id` which takes no argument and fetches the appropriate oid from `pg_class`.

I'm changing it now and also adding some code to detect this issue and report it to Rollbar, in case it happens in another scenario I haven't debugged. 

cc/ @rafatower

**Comment by javisantana** [comment]
One thing guys, ghost table code is the one that cause most of the problems we had (data removal and so on) so please, take special care, test as crazy before going to prod

**Comment by gfiorav** [comment]
Hey @javisantana , don't worry. I've come to solve this before releasing concurrent ghost tables update since this came up again during smoke tests. 

I'm coordinating ST with support people since they have dealt with all the different issues regarding ghost tables and it has been very productive, this is the second bug were ironing out.

**Comment by javisantana** [comment]
thanks for paying special attention :*

**Comment by gfiorav** [comment]
New discovery:

`fix_oid` is now fixed, but the `cartodbfy` method seems to change the `oid` of the table again. Since `fix_oid` is called before this change happens, `UserTable.table_id` will never be correct after first sync happens.

Investigating and fixing some more!

**Comment by javisantana** [comment]
cartdbfy basically creates a new table from the old one in order to speedup the process

**Comment by gfiorav** [comment]
Ok @javisantana , so that explains the `oid` change. I've added `fix_oid` code after cartodbfy that was missing. Now it should be ok.

**Comment by gfiorav** [comment]
Alleviated through https://github.com/CartoDB/cartodb/pull/7045, reason for this is UserTable's `table_id` being out of sync with physical table `oid`. Happens everytime a sync runs, as no oid sync is run after cartodbfy. Will be dealt with in upcoming sync refactor effort.

This will do for now, thanks!

**Comment by rafatower** [comment]
:clap: :clap:
