### ISSUE TITLE
Deep linking organization tables

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#6884]
@javitonino and me have been taking a look at some strange, slow queries (#6865), and have realized about an unexpected (at least for me) behaviour related to this query:

```sql
SELECT "visualizations".* FROM "visualizations"  WHERE "visualizations"."name" = <TABLE NAME>
```

This is related to links like "organization.cartodb.com/tables/table_name/public". In this case the table name is used for the search, instead of the id, but since it lacks the  user in the url, it takes ages.

This is not a security issue, since security checks still apply, but it raises a question that we've talked about recently (see #6533): can two datasets of different users inside a same organization have the same name?
a) yes, they can: those links are not valid, since they don't identify the dataset. We could still return "the first one" anyway.
b) no, they can't: we should add the validations everywhere instead of removing them (that's what we decided at #6533) and those links are valid.

I'd vote a), since you can always provide the right, user-scoped, link instead of the wrong, organization-based one.

What do you think, @javisantana ?

**Comment by javisantana** [comment]
I don't have a strong opinion here so whatever you think is best

**Comment by javitonino** [comment]
Proposed solution:
- For non-organization users, query using user_id and name.
- For organization users:
  - If username/schema is given, no problem, query as before
  - If no username/schema is given, query by name and users in the organization (join). Return a redirect to the correct link to encourage use of new links.

Additionally add a log message to the query builder to warn us when one of these queries is being run, to be able to track and fix it.

**Comment by juanignaciosl** [comment]
LGTM.

**Comment by javitonino** [comment]
Fixed in pull https://github.com/CartoDB/cartodb/pull/6921
