### ISSUE TITLE
Duplicating a multilayer map does not respect layer order

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#6889]
**STR**:

* Create a map with two layers, I used NY fire companies and NY fire divisions from Data Library
* The layers will have a certain order:
  ![image](https://cloud.githubusercontent.com/assets/1730320/13781613/36beee9e-eac4-11e5-8c99-ade81e89c412.png)
* Click on "duplicate map"
* The resulting map has the layers in the reverse order:
  ![image](https://cloud.githubusercontent.com/assets/1730320/13781641/4e1807b0-eac4-11e5-820d-855e9a15b4c3.png)

**Expected behavior**
The order of the layers in the map to be duplicated is respected in the output.

**Current behavior**
Layer 1 becomes layer 2 and viceversa. 

My data, in case it's useful:
user: `vmg`
map id: `ad1a9862-eabb-11e5-861e-0e31c9be1b51`
duplicated map id: `e30fa624-eabb-11e5-abf1-0ecfd53eb7d3`

**Comment by xavijam** [comment]
I'll take a look, but it could be related with the backend code. In any case, it should be easy to fix :).

**Comment by javitonino** [comment]
Most likely will be solved with changes in https://github.com/CartoDB/cartodb/pull/8045

**Comment by xavijam** [comment]
ole!, working then?

**Comment by javitonino** [comment]
I tested it and worked fine, so I'd say close it!
