### ISSUE TITLE
Geojson name on file listing does not fit in the format box

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#6890]
![image](https://cloud.githubusercontent.com/assets/1730320/13782238/a1f90198-eac6-11e5-90e7-991295b03f94.png)

(When using the Box connector, which is the only one right now that can retrieve GeoJSON files)

Probably not worthy, but at least to take into account if a similar file listing is to be implemented/is implemented.

cc @xavijam

**Comment by xavijam** [comment]
it is worth it, thanks @iriberri :).
