### ISSUE TITLE
table created/cartodbfied via SQL API does not appear in the Editor

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#6896]
A specific table created and cartodbfied via SQL API does not appear in the Editor.

## Steps to reproduce: 

* Create table
```
CREATE TABLE _chg_lds_parcel_primary (
    cartodb_id integer,
    the_geom geometry(Geometry,4326),
    the_geom_webmercator geometry(Geometry,3857),
    parcel_id double precision,
    land_district_id double precision,
    img_id double precision,
    fen_id double precision,
    toc_code character varying,
    alt_id double precision,
    area double precision,
    nonsurvey_def character varying,
    appellation_date character varying,
    parcel_intent character varying,
    status character varying,
    total_area double precision,
    calculated_area double precision,
    _calculated_area_m2 double precision,
    _calculated_area_ha double precision,
    se_row_id double precision,
    audit_id double precision,
    _geohash_centroid character varying,
    _db_operation character varying
);
``` 
* Cartodbfy the table
```
select cdb_cartodbfytable({{USER}},'_chg_lds_parcel_primary');
```
## Expected result
The table should appear in the Editor

## Current result
The table does not appear in the dashboard even after being populated

## Context 
Other tables with similar origin, name and structure does appear in the dashboard after being cartodbfied, as expected

cc/ @rafatower @xavijam Not sure if this is a Cartodbfy problem or an Editor one

**Comment by xavijam** [comment]
Adding @gfiorav, just in case.

**Comment by rafatower** [comment]
cc/ @iriberri are we supporting names of tables starting with underscore?

**Comment by iriberri** [comment]
Officially, from the import flow, we're not allowing tables names to start with an underscore anymore. `table_` gets prepended to it (and public documentation about this is in the oven ;-))

The CartoDBfication process itself seems fine (tested in prod & local directly from DB), and no warnings are appearing in Rollbar.

**Comment by rafatower** [comment]
Then I think we shall document that as part of the requirements for a table to be cartodbfy'ed and the user shall be notified of it. They just need to rename it in order to get around this problem cc/ @ernesmb

**Comment by ernesmb** [comment]
user confirmed the workaround, closing

thank you all
