### ISSUE TITLE
Improve importing named map saves and widget fetching

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#6901]
- [ ] Importing a file displays many widget searches like

  Carto::Widget Load (0.6ms)  SELECT "widgets".* FROM "widgets" WHERE "widgets"."layer_id" = '94ebf4eb-3622-4aad-934b-c2a971234aba'

This is because `/Users/juanignaciosl/Development/vagrant-160203/cartodb/services/named-maps-api-wrapper/lib/named-maps-wrapper/named_map.rb`, at `widgets_data_for_layer` method, fetches layer widgets manually. Layer and widget use different ORMs right now and it's not currently cached. The search can probably be cached.

- [x] Also, it looks like during _one_ import there're many (around 13!) calls to `Visualization::Member#save_named_map`, which makes the problem even worse. Reducing this to the strictly needed saves might make widget searches caching unnecessary.

- [x] Finally, `widgets.layer_id` should be indexed.

cc @gfiorav @javitonino

**Comment by javitonino** [comment]
Waiting on #7566 (named map refactor) as it will probably change how this works.

**Comment by juanignaciosl** [comment]
Well, yes and no. The class that will send the named map will be different, but the problem is the same: importing datasets trigger multiple times the model callbacks responsible of keeping named maps up to date.

**Comment by javitonino** [comment]
Agree on that, but widget fetching should be better as it will use the new models (which should implement caching correctly). But still, the number of calls to the named map generation code will need to be improved regardless. Still, I prefer waiting a bit for named maps to avoid conflicts when merging the new named map code.
