### ISSUE TITLE
Torque map not rendering with "custom" markers within mobile Twitter browser

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#6903]
S/B 8411737

## Context
Map looks fine on desktop and via publish link viewed in mobile Safari, but markers don't appear when viewed on mobile within Twitter browser.

Checked in iOS 9.2.1.

## Process
1. Create a public torque category map in CartoDB that uses a **png image** for the marker.
2. Click it's Publish button and copy the 'Get the link' url.
4. Tweet the map.
5. Open Twitter app on iPhone and click the map's link from inside the tweet.
 
## Expected result
Torque map will autoplay & you will see markers with custom image:

![img_2630](https://cloud.githubusercontent.com/assets/1779444/13822998/37f83a3a-eb7e-11e5-931c-325ba2600c3b.PNG)

## Current result
![img_2631](https://cloud.githubusercontent.com/assets/1779444/13823072/87f19bbc-eb7e-11e5-8561-73d3a5bfc421.PNG)

If you want my test is in [this Tweet.](https://twitter.com/ztephm/status/710151600401158145)

**Comment by xavijam** [comment]
Looks like for any reason Twitter iOS in-app browser doesn't render torque maps with custom markers properly. After checking other torque maps without custom image markers, they are working properly in that described in-app browser.
