### ISSUE TITLE
Mixed content warnings for embedded maps - avatar url

### ISSUE THREAD

**Issue by alexkrolick** [CartoDB/cartodb#6904]
The iframe for published map embeds loads the user's avatar over HTTP, causing mixed content warnings on HTTPS sites

**Comment by javitonino** [comment]
This should be fixed now, although it could take up to a day to propagate due to caching. If more than 24h passed and you still see some embeds with mixed contents, feel free to reopen this issue including a link, so we can check what we missed. Thanks for reporting!
