### ISSUE TITLE
Buggy caching between editors and embeds

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#6920]
1. Edit the visualization in editor v2 (for example, the type of the infowindow)
2. reload the new embed. The templates of the infowindow in the vizjson are outdated.
3. in a second try, with a new reload, correct templates appear in the map.

cc @xavijam

**Comment by xavijam** [comment]
cc @saleiva @AbelVM, add as many details as you have pretty please.

**Comment by juanignaciosl** [comment]
Fix oncoming. In affected infowindows and tooltips, they where not regenerated in the first load.
