### ISSUE TITLE
Add not-null constraint to `layers.kind`

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#6922]
That's a mandatory value and [it's validated by Sequel](https://github.com/CartoDB/cartodb/blob/9a4ad5492500ec75a251e99229deb2aa2a740278/app/models/layer.rb#L49) (there's no empty column in production), so it should be safe.

cc @gfiorav @javitonino

**Comment by gfiorav** [comment]
Grabbing this one!

**Comment by gfiorav** [comment]
Closed via https://github.com/CartoDB/cartodb/pull/6956
