### ISSUE TITLE
Add moran analysis

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#6948]
- [ ] Add necessary analysis for models.
- [ ] Create proper analyses form templates.
- [ ] Check how to provide list of available nodes for `moran` analysis.
- [ ] add to add-analysis modal; 
  - need to be able to know the source's schema, and validate & pick two valid columns, if not valid should not display it as an option

**Comment by xavijam** [comment]
@javierarce, you are taking care of this one right? If you already have a ticket, please destroy it 🚨

**Comment by javierarce** [comment]
Yes, I'm on in right now :)
