### ISSUE TITLE
Add some warning when adding a layer over the limit

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#6958]
In the editor, map view, when you try to add a layer and you are already at the maximum number allowed by the plan, the button does nothing. It should display a warning saying that the maximum number of layers has been reached (maybe upselling?). Alternatively, maybe we could permanently display a layer counter (3/4 layers in use).

cc @urbanphes @xavijam

**Comment by xavijam** [comment]
JS error: Uncaught ReferenceError: orgagnizationAdminEmail is not defined
