### ISSUE TITLE
A CartoDB format

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#6962]
I propose a file format with `.carto` extension.

Requirements:

+ A "map" must be completely contained in it: datasets, vizjsons, basemaps even.
+ Once re-imported it must produce an exact copy of the map it was made from.

WIP

**Comment by juanignaciosl** [comment]
Ha! I hadn't see this. It's _almost_ a duplicate of #6365 ;-)

**Comment by gfiorav** [comment]
Ah! That one is older, I'll close this and follow that one :)
