### ISSUE TITLE
Make CartoDB labels layer appears with basemap style

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#6968]
- No possibility to move it.
- Same style as true basemap.

![screen shot 2016-03-28 at 12 16 57](https://cloud.githubusercontent.com/assets/132146/14076097/fc136124-f4de-11e5-93b3-7fec18c44e6c.png)

**Comment by xavijam** [comment]
After a talk with @piensaenpixel (and with @saleiva indirectly), let's leave the layer where it is, but it should be disabled, and we couldn't move it.

**Comment by javierarce** [comment]
:ok_hand: by disabled you mean having no click event and… a distinctive style?

**Comment by xavijam** [comment]
Yep, no click and probably same style than the "real" basemap.

**Comment by javierarce** [comment]
Yeah, but I mean, a disabled state too?

**Comment by xavijam** [comment]
do we have that state right now?

**Comment by javierarce** [comment]
I don't think so, no.

**Comment by xavijam** [comment]
Done by @alonsogarciapablo, closing.
