### ISSUE TITLE
Running postgres on different host

### ISSUE THREAD

**Issue by sabala12** [CartoDB/cartodb#6994]
Hello, Is it possible to configure CartoDB to work with a remote postgres host?

I have tried to modify ./config/database.yml, and the following Ruby variable was effected ::Rails::sequel::configuration. environment_for(Rails.env)['host']

However in some places the scripts still search postgres on localhost.

**Comment by javitonino** [comment]
Yep, it should run fine. That should change the database configuration for the metadata database, and for new users. For existing users, check the `database_host` column in the `users` table.
