### ISSUE TITLE
Destroy all objects in an schema/db when deleting users

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#6995]
When deleting an user, only objects known by CartoDB (i.e.: cartodbified tables) are deleted from the user db. If the user has created tables/views via the SQL API, they won't get deleted.

- For normal users, that means that the database is not completely deleted (we leak databases).
- For organizational users, the user cannot be deleted:
  - First time clicking the delete button: the user is deleted from central, credential are deleted from redis and the know objects are dropped. An error message (flash) is shown indicating that the users schema could not be deleted.
  - From here on, it gives a 500 error with no information. The user cannot access any API's to delete the objects (credentials deleted), so only solution is manual deletion from the db (via support ticket).

**Comment by gfiorav** [comment]
It might be worth it to create a `lib/carto/user_database_manager.rb` that would deal with all operations related to the user database. Then refactor other code to avoid the `in_database` stuff. Benefits would be:

+ Less fat user model
+ Centralised, one point of failure code for database stuff
+ clean?

Summoning @juanignaciosl

**Comment by juanignaciosl** [comment]
There' already 2 classes that handle that: `DBQueries` and `DBService`, both at `app/models/user`.

**Comment by gfiorav** [comment]
Still subject to some refactor, but ok, too verbose!
