### ISSUE TITLE
bubble legend is not correctly displayed after export image

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartodb#7012]
The bubble legend appears as a rectangle after you export the map from the CartoDB Editor.

Steps:

1- Create map from point geometry dataset 
2- Select bubble wizard
3- Select ``Export image`` option 
4- Define area to export and click ``Export``
5- The legend of the exported image is a rectangle instead of bubble legend

Map created in the editor:

![map](https://cloud.githubusercontent.com/assets/11177693/14203247/33c96e8a-f7fd-11e5-9a3d-e5a40d675bb3.png)

Exported image from map

![bubblelegendimage](https://cloud.githubusercontent.com/assets/11177693/14203274/5dc2036e-f7fd-11e5-94af-c16fd9d2f37a.png)

**Comment by vdisawar** [comment]
Why did this get closed? I'm also having the same issue with exporting. Is there a fix or way around in the mean time?

**Comment by ztephm** [comment]
Hi there @xavijam @oriolbx I'm seeing it again also, can we re-open?

Here's my test Bubble Wizard map: https://team.cartodb.com/u/stephaniemongon/viz/fc1261a4-0ca6-11e6-96ed-0e31c9be1b51/map

From Editor's Map View I clicked Export Image then clicked Export with these settings:
![screen shot 2016-05-02 at 12 33 57 pm](https://cloud.githubusercontent.com/assets/1779444/14960336/2c0524a0-1062-11e6-843d-80a5b2cadbf4.png)

I'm getting:
![download](https://cloud.githubusercontent.com/assets/1779444/14960368/5549b4d4-1062-11e6-82f2-65b89fc7e45e.png)

**Comment by kstealth25** [comment]
I'm having the same problem.

**Comment by saleiva** [comment]
As we are working on new legends, we will fix it then.
Thanks!
