### ISSUE TITLE
Confusing timezone information in Twitter connector

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#7025]
![image](https://cloud.githubusercontent.com/assets/1730320/14247914/c988ac1c-fa71-11e5-8769-3887fd14d968.png)

In the selector, it says: `"Date will be converted to GMT +0"`

In the description, it sayds: `"Time is in GMT+0  (you are in GMT+02:00)"`

The "Date will be converted" text makes people (or me) think that whatever you input is, it will be corrected to GMT. This thought can even be supported by the fact that the frontend is telling you which is your timezone.

The reality is that the user input will be treated as GMT directly, without any time conversion, so "it will not be converted", but "the user has to convert it" in advance and input it there.

@csobier could you help with some sentences here? (If you think this is actually an issue, if not feel free to close)

**Comment by csobier** [comment]
Agree, it's confusing. How about... 

"The requested data must be the same format as your default timezone."

**Comment by iriberri** [comment]
It's the other way around, users must input GMT

**Comment by csobier** [comment]
(This is confusing :-)  How about this?

"Twitter data must be requested using the GMT format."
