### ISSUE TITLE
Replace cdb.god component or way of use

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#7044]
https://github.com/CartoDB/cartodb/blob/7d5940954dc9b9009024687ee41b57bc7f233841/lib/assets/javascripts/cartodb3/editor.js#L90 and its usages

cc @viddo @javierarce

**Comment by xavijam** [comment]
Not being used thanks to @nobuti, removing it.

**Comment by viddo** [comment]
![screen shot 2016-07-01 at 12 35 04](https://cloud.githubusercontent.com/assets/978461/16519316/4dfd9d62-3f88-11e6-8d5a-7253d6572e58.png)

I think we can 🔥  that final listener, right?

**Comment by xavijam** [comment]
Not sure how to proceed with the metrics thing... any idea?

**Comment by viddo** [comment]
The metrics should be solve separately, the KISS solution would be to just call `metricObject.doWhatever`, or pass it as an explicit dependency where used like any other.
