### ISSUE TITLE
Display layer of labels differently

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#7046]
Right now, the labels layer is being displayed on top of the rest of layers and is being considered a regular CartoDB layer:

<img width="651" alt="screen shot 2016-04-05 at 16 02 08" src="https://cloud.githubusercontent.com/assets/390398/14284486/0d59f758-fb48-11e5-8b67-c74b15810dca.png">

It should have a different icon and users shouldn't be able to Add Analysis to those layers... Even selecting/removing/hidding them should be disabled?

**Comment by xavijam** [comment]
Duplicated -> https://github.com/CartoDB/cartodb/issues/6968

**Comment by alonsogarciapablo** [comment]
:+1:
