### ISSUE TITLE
All connections for sync operations should go through the same port

### ISSUE THREAD

**Issue by luisbosque** [CartoDB/cartodb#7047]
For some async operations (resque) we are able to send queries to the DB through a different port.
All the queries sent through the editor (sync) are supposed to go through the same port. 
Otherwise is difficult perform some maintenance operations

/cc @rafatower

**Comment by rafatower** [comment]
Please check R/B 17316 @iriberri

**Comment by iriberri** [comment]
The current occurrences are coming from:

````
/app/models/table.rb:1048:in `georeference_from!
````

I'm going to move this one to a transaction too.

**Comment by iriberri** [comment]
The change in table.rb#georeference_from! is already in production, so occurrences should be reduced (and, fortunately, don't exist) from now on. I'll keep an eye on it to see if there's still something we're missing.

**Comment by iriberri** [comment]
![image](https://cloud.githubusercontent.com/assets/1730320/14486246/207cf55a-015c-11e6-86bc-674f00f1240a.png)

No more occurrences. :-)

**Comment by iriberri** [comment]
@luisbosque I think you can close these connections now :)
