### ISSUE TITLE
New embed always set vector parameter as true

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#7050]
## STR
- Just check any new embed url.
- Open the source code and check at the end of the html that `vector` is true, no matter if the param is defined or not in the url.

Maybe related with https://github.com/CartoDB/cartodb/pull/7017.

**Comment by juanignaciosl** [comment]
I'm checking (in local) with master, both with old and new visualizations and I can't reproduce it, embed (http://juanignaciosl.localhost.lan:3000/editor/577394ca-fb66-11e5-b236-080027880ca6/embed) has vector: false :-\. Could you give more detail, please?

![Uploading Screen Shot 2016-04-05 at 21.43.31.png…]()

**Comment by juanignaciosl** [comment]
@xavijam: ok, I spotted the problem. The caching is not working properly. You were seeing a cached version, with `vector: true`. Just opening the map cleared the cache and worked. I'll dig deeper to avoid this though.
