### ISSUE TITLE
no superclass method `google_maps_private_key'

### ISSUE THREAD

**Issue by sabala12** [CartoDB/cartodb#7054]
Hello, when running ./scripts/create_dev_user I get the following error: "no superclass method `google_maps_private_key' for #<User:0x007f194fd1ab18>". However the error disappeared  after running the script again.

What is the source of the problem?

**Comment by gfiorav** [comment]
Hey @sabala12 make sure you have migrated your database before running the script.

Make sure you've run migrations at least up to `db/migrate/20150609083856_add_google_maps_private_key_to_users_and_orgs.rb` without any errors.

**Comment by sabala12** [comment]
Thanks

**Comment by gfiorav** [comment]
Np! open this issue again if you have further questions
