### ISSUE TITLE
Visualization import/export frontend

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#7056]
Frontend work after design (#7055).

Details and full discussion at [feature doc](https://docs.google.com/document/d/13g0n3HZMmQyjOcg_G0-p4zMQf1UzOHT3Hy2IGDHpBNc/edit#).

cc @xavijam

**Comment by gfiorav** [comment]
Closed via https://github.com/CartoDB/cartodb/pull/7296
