### ISSUE TITLE
Creating an empty table fails

### ISSUE THREAD

**Issue by mojodna** [CartoDB/cartodb#708]
(As the first action "start from scratch" of an organization user.)

![image](https://cloud.githubusercontent.com/assets/45/3912316/c2ac4a1e-2329-11e4-91f3-2ec7b827ead0.png)

![image](https://cloud.githubusercontent.com/assets/45/3912294/90c7a9a8-2329-11e4-8bf2-0a571ab08697.png)

**Comment by xavijam** [comment]
Can I close this ticket then?
