### ISSUE TITLE
Remove drop permission from sync tables

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#7091]
The idea here is to avoid users dropping sync tables via SQL API. This not only breaks the sync but also is a no benefit use that is probably a misunderstanding of the CartoDB workflow.

A sync is not pure sql, it`s:

+ An SQL table.
+ An Editor process to maintain it's contents.
+ A cron task that makes sure it's updated on due time.

So dropping the table of a sync is dropping one component of the sync. If we would like to programatically allow to do this, we should have a public Syncs API.

I propose removing the DROP permission of the give table for the user once it's becomes a sync table (add it back again if it's unsynced) and have the editor process remove the table if needed. The only way to remove sync tables will be the UI.

cc/ @juanignaciosl @javitonino

**Comment by javitonino** [comment]
Organizational users are the owners of their own schema an tables inside, so they can change permissions. We would have to change ownership of the table as well (don't know if this breaks anything).

**Comment by gfiorav** [comment]
Yep, just realised that when researching around.

We could have another user-level user called syncs and have that user be the owner while the sync is a sync… all other permissions would be granted to original users.

You’re right that not having a REVOKE DROP complicates things quite a bit.

**Comment by juanignaciosl** [comment]
Schema ownership would also be a problem with a "sync user". Creating a schema for syncs (which was the original guido proposal) might solve it, but maybe it's an overkill.

**Comment by gfiorav** [comment]
Maybe creating a user for each user db is not such a hassle. This user would gain the ownership of synced tables and give it back whenever necessary. In orgs, the only difference is that there would be one sync user per entire org. 

I don't think it should collision with sharing stuff since that is mostly controlled at rails level.

**Comment by juanignaciosl** [comment]
It's not a user for each user db but for each user, since organization users should have separated sync schemas. The biggest problem is that it breaks the convention of tables being at username/public schemas, and moving from that is far from trivial.

**Comment by gfiorav** [comment]
Wait, I think we're talking about different things:

I propose to create a user-db specific role to which sync tables' ownership is transferred. So there would be a role per org and per non-org user. I think we could have this role own a table on a users schema, so no naming would have to change.

**Comment by juanignaciosl** [comment]
I thought that @javitonino comment exposed that since users are owners of the schema they could get the table ownership anyway.

**Comment by gfiorav** [comment]
So the thing is that the owner of the schema can't not be owner of a table inside a schema right?

Still experimenting in local

**Comment by juanignaciosl** [comment]
[Indeed](http://www.postgresql.org/docs/9.3/static/sql-droptable.html): "Only the table owner, the schema owner, and superuser can drop a table". Definitely a new schema doesn't look like the best idea here.

**Comment by gfiorav** [comment]
Ok, then I'll do this in two parts:

+ Make UserTable's `table_id` just a forward of a fetch to the actual oid (maybe even remove the value from the user_tables table) to make sure it's always synced
+ Find a way of making Ghost Table Manager smart enough to detect broken (sql api dropped) sync tables and fix them.

**Comment by javitonino** [comment]
I did some tests before and I think you can have tables owned by a different user than the schema and the schema owner does not automatically have permissions (at least SELECT) on those tables. So I think that creating a sync user and transferring ownership of the table to him might work (although we should be careful with permissions for the actual user, sharing, etc).

An alternative solution would be to create a sync schema per user an using [`SET search_path TO user_schema, user_sync_schema;`](http://www.postgresql.org/docs/9.5/static/ddl-schemas.html#DDL-SCHEMAS-PATH). There is already some of this in the code:
- https://github.com/CartoDB/cartodb/blob/master/app/models/user.rb#L619
- https://github.com/CartoDB/cartodb/blob/master/app/models/user/db_service.rb#L197

P.S: First idea dropped after @juanignaciosl comment, I did not test dropping tables.

**Comment by juanignaciosl** [comment]
> Make UserTable's table_id just a forward of a fetch to the actual oid (maybe even remove the value from the user_tables table) to make sure it's always synced

You can't do that without further analysis. Reading current `table_id` is just a column from the metadata row that is fetched, so it has cost 0. Nevertheless reading it would mean a new connection to a different database (user's) and a new query. _Maybe_ you can do it and it might be great, but please be _extra_ careful with this.

**Comment by gfiorav** [comment]
I see your point... I haven't come up with any other way of guaranteeing table_id is sync'd though :/

**Comment by juanignaciosl** [comment]
You just can't. Reducing the amount of metadata stored, if feasible, is a Good Thing™, but it's not always possible. I doubt that it can be done right now because of traceability need. _Maybe_ making the assumption about unique table name at user schema, but even in that case I don't know if being able to realize a table oid change is needed.

**Comment by gfiorav** [comment]
New ghost table manager is able to take care of this, so there isin't really a need.

When you delete a sync table physical table, the user table get's dropped and the sync as well.

Closing!
