### ISSUE TITLE
Add lat_long as geocoder kind for async internal geocoder API

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#7110]
Things to do to avoid potentially long calls made synchronously from the UI:
- [ ] modify the internal API to allow a new `kind` of geocoding, `lat_long` [here](https://github.com/CartoDB/cartodb/blob/3632a997d1298ce8f4cd3a5d770cdd818f21183a/app/models/geocoding.rb#L14)
- [ ] remove the sync call from this [controller](https://github.com/CartoDB/cartodb/blob/3632a997d1298ce8f4cd3a5d770cdd818f21183a/app/controllers/api/json/tables_controller.rb#L96)
- [ ] modify the frontend code to make usage of that new async kind `lat_long` (poll status as in any other geocoder kind)

**Comment by rafatower** [comment]
related to https://github.com/CartoDB/cartodb/pull/7109

**Comment by iriberri** [comment]
I think this does no longer make sense with the current analyses, right?

**Comment by rafatower** [comment]
For me the point is to make it async. I don't know how it is done in the builder to be honest. If it is async in the builder, let's close this ticket

**Comment by iriberri** [comment]
At the builder right now lat/long is running a query on runtime over the dataset over the SQL Batch API. The internal geocoder doesn't seem to be used anymore. Not sure if this is likely to change in the near future but at the moment there's no usage except in the Import flow, for which latitude and longitude columns are directly generated through ogr2ogr.
