### ISSUE TITLE
Use viz.json for anonymous map in the new editor

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#7150]
Similar to what we did in #7093, but forcing usage of viz.json for the anonymous map [here?](https://github.com/CartoDB/cartodb/blob/master/app/controllers/carto/editor/visualizations_controller.rb#L24).

@juanignaciosl, we discussed this offline. Comment here if you have any questions.

cc: @xavijam @javierarce @javisantana @viddo

**Comment by juanignaciosl** [comment]
Closed by #7116.
