### ISSUE TITLE
Create UI for creating mobile apps and SDK keys

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#7178]
After designs are done, create the UI to allow users to register mobile SDK apps.

**Comment by MariaCheca** [comment]
🌈

**Comment by MariaCheca** [comment]
I suggest a change in the routes semantic for this.

Currently, there's only one route that leads to the page where the user can see and manage its API keys, `/your_apps`. Now we have CartoDB and mobile API keys, and a good practice could be create a new parent path with its to descendants, that is:

- `/api_keys/cartodb` or `/api_keys/platform`
![screen shot 2016-04-28 at 18 27 34](https://cloud.githubusercontent.com/assets/2141690/14893297/11c2f338-0d6f-11e6-9e0d-02ab9851df9c.png)

- `/api_keys/mobile`
![screen shot 2016-04-28 at 18 28 27](https://cloud.githubusercontent.com/assets/2141690/14893305/182c9080-0d6f-11e6-832e-9197e5d21c2b.png)

What do you think? @javitonino @juanignaciosl @xavijam

**Comment by juanignaciosl** [comment]
Personally I like url paths fragments to be valid. Since that change doesn't make `/api_keys` a valid url I'd prefer two paths at the same level. Depending on frontend criteria, `/your_apps` and `/your_mobile_apps`, `/cartodb_api_keys` and `/mobile_api_keys`...).

Nevertheless I don't have an strong opinion on this, and since there's a visual hierarchy because of the tabs my proposal is far from perfect.

My two cents.

**Comment by MariaCheca** [comment]
Thank you @juanignaciosl!

I forgot to add that the "main link" would be the one for the CartoDB API keys, so maybe your option is better than my proposal, as there's no intermediate level. That way, the API keys > CartoDB flow would be accesible from the side menu and the subheader, while API keys > Mobile apps would be only accesible once you're _inside_ the APIs section.

**Comment by javitonino** [comment]
Just for reference, my plan for Central URL's is to use a CRUD `/mobile_apps` created with Rails' `resources`. I don't necessarily think that works too well for top-level URL's in the editor, and I think I prefer it to be under a sub-path.

Maybe `api_keys` for platform keys and `api_keys/mobile_apps` for mobile sdk keys? Or `your_apps` and `your_apps/mobile`?

Anyway, I would not change the existing URL's because you would have to sync changes in the editor and central (because that UI is duplicated) and you know you will break someone's crawler :stuck_out_tongue: but maybe I am being too cautious.

**Comment by xavijam** [comment]
Personally, same opinion as @javitonino:

api_keys
api_keys/mobile
your_apps
your_apps/mobile

In any case, don't spend too much time in this decision because it could change easily.

**Comment by MariaCheca** [comment]
I see. In that case, I'll go for `your_apps/mobile`, that way the existing routes are not changed :) Thank you!
