### ISSUE TITLE
Store sourceId for widgets

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#7200]
Since we are supporting dataviews having an analysis as a type of source (https://github.com/CartoDB/cartodb.js/issues/1212), we now need to store the `sourceId`  (the id of the analysis) whenever we create a widget.

/cc @alonsogarciapablo

**Comment by alonsogarciapablo** [comment]
Also, it should be included in the viz.json so that we can set up dataviews correctly when we load them from the viz.json.

**Comment by juanignaciosl** [comment]
After talking to @rochoa he confirmed that this should send this to Maps API.

**Comment by rochoa** [comment]
Actually it should `"source": {"id": id}` as we do in the layers. Check this example: https://github.com/CartoDB/Windshaft-cartodb/commit/146d494cae7c58f20e12c8b3b7abdb3da32f5818

HTH 😄

**Comment by juanignaciosl** [comment]
True (not the first time I must do this ;-) ). Updated example.

**Comment by alonsogarciapablo** [comment]
Just for the record, for layers, the `source: { id: 'something' }` is inside of the options key in the viz.json.... I don't have any preference but just saying...

Also, FYI, deep-insights.js will need to convert whatever we go with when parsing the viz.json cause CartoDB.js works with `sourceId` internally (which is then converted to `source: { id: 'something' }` when talking to the Maps API)

**Comment by juanignaciosl** [comment]
Frontend currently send `source` outside `options`. I might understand having it both inside and outside options. Is there a good reason for editor to send it _outside_ options and cartodb.js expecting it _inside_ options in the vizjson? I don't mind, but having to move it at the backend _really_ smells wrong.

**Comment by juanignaciosl** [comment]
@javierarce frontend currently sends `source_id: id` (current status of branch at #7217). It's not a problem for me, but maybe you'd like to send `source: { id: id }` instead so you handle it the same way for requests and responses. That will be the format used at vizjson and named map template as well.

**Comment by javierarce** [comment]
Thanks, @juanignaciosl, I'll do the change.

**Comment by juanignaciosl** [comment]
Merged into `7118-attach-widget-to-analysis`.
