### ISSUE TITLE
Add analyses and layer's source to viz.json for named maps

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#7215]
Right now we're not including any information about existing analyses for in the viz.json for named maps (by design).

In order for the polling to work, CartoDB.js needs to set up some models before the request to the Maps API is done, so we would need some basic info about analyses. We shouldn't expose any SQL in the viz.json, so my suggestion is to remove `params` from the nodes of type `source`:

```
{
  ...
  analyses: [
    {
     "id": "a1",
     "type": "trade-area",
     "params": {
       "source": {
         "id": "a0",
         "type": "source"
       },
       "kind": "drive",
       "time": 300
     }
   }
  ]
  ...
}
```

Also, CartoDB.js needs to know if an analysis is the source of a layer, so we can include a `source` attribute:

```
{
  "id": "52600120-b25b-4bd1-b7c1-09c50bc1cd50",
  "layer_name": "arboles",
  "interactivity": "cartodb_id",
  "visible": true
  "source": "a1"
}
```

**NOTE:** We are already adding `options.source` for layers inside of a layergroup, so we just have to do something similar for named maps. The difference is that there is currently no `options` key in the attributes of a layer inside of a named map, so my proposal is a bit inconsistent. It's really not a big deal for CartoDB.js. Since "source" will actually be optional... perhaps it makes sense to include them in the options here?

cc: @xavijam @juanignaciosl

**Comment by juanignaciosl** [comment]
@xavijam any strong opinion on `source` location? Since layers in a layergroup had it inside `options` I'd do it inside `options` as well for layers, but I don't really care.

**Comment by xavijam** [comment]
Up to you guys :).
