### ISSUE TITLE
Analysis window doesn't work if the selected layer has a SQL applied.

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#7229]

**Comment by viddo** [comment]
What analysis window? Can you give some more details on what the behavior should be?

**Comment by saleiva** [comment]
The modal where you chose the analysis.
It should show the analysis. Now it just shows up an error.

2016-04-26 11:00 GMT+02:00 Nicklas Gummesson <notifications@github.com>:

> What analysis window? Can you give some more details on what the behavior
> should be?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/7229#issuecomment-214675338>
>



-- 
Sergio Alvarez Leiva

**Comment by viddo** [comment]
Ok, thx for clarifying, but I can't get it to fail locally, so I need more to go on. What kind of error do you see? What is your query?

Technically we check the output geometry type (through the SQL API) of the source node (i.e. the output of the custom SQL, in this case), to know it's compatible with the available node types, can you check what the error/response of this request(s) done when the modal is opened?

**Comment by saleiva** [comment]
Test in on production. It's happening every time I try.
Any query makes it fail, for example a WHERE X = Y

Attaching the error screenshot

[image: Imágenes integradas 1]

2016-04-26 12:27 GMT+02:00 Nicklas Gummesson <notifications@github.com>:

> Ok, thx for clarifying, but I can't get it to fail locally, so I need more
> to go on. What kind of error do you see? What is your query?
>
> Technically we check the output geometry type (through the SQL API) of the
> source node (i.e. the output of the custom SQL, in this case), to know it's
> compatible with the available node types, can you check what the
> error/response of this request(s) done when the modal is opened?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/7229#issuecomment-214696014>
>



-- 
Sergio Alvarez Leiva

**Comment by viddo** [comment]
@rochoa mentioned on Slack that it might be due to double-escaping being done somewhere on the custom query
