### ISSUE TITLE
Rewrite visualization queries on import table rename

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#7258]
If you import a full visualization with existing layers import works but the new visualization uses the existing tables instead of the new ones. For example, importing twice a visualization using a table `X` creates two visualizations using both `X`.

If during import table names are not kept, visualization metadata should rewrite the queries.

**Comment by juanignaciosl** [comment]
This is becoming more important. As more people uses the import of full maps more collisions happen, and the errors that this raises are not obvious. I've talked to @javisantana and he has suggested that failing if there's another table with that name and prompt the user is also an option.

IMHO we could give SQL rewrite a try, as we can probably fix most of the cases in a safe manner, and if it turns really complicated, prompt the error message. @javitonino @gfiorav, what do you think?

**Comment by javitonino** [comment]
Fixed in #8862. Still some kinks to iron, follow-up: https://github.com/CartoDB/cartodb/issues/8903
