### ISSUE TITLE
Add timeouts to rollbar calls

### ISSUE THREAD

**Issue by luisbosque** [CartoDB/cartodb#7266]
If there is any connectivity problem with rollbar and there is no timeout the workers of the app can be stuck waiting to rollbar request.

A request to rollbar should be cancelled after a reasonable time (maybe one or two seconds).

Also, to guarantee consistency between calls, there should be a wrapper to rollbar requests

/cc @juanignaciosl @xavijam

**Comment by javitonino** [comment]
There is actually a timeout option in Rollbar that defaults to 3s: https://github.com/rollbar/rollbar-gem/blob/master/docs/configuration.md#request_timeout. But it doesn't work, as it only sets `read_timeout` but not `open_timeout`, so the timeout for opening the connection is the default 60s. Given that there are some retries, it takes 5 min (5 retries x 60s) for a request to timeout.

Some ideas:
- Send a patch upstream to make the timeout work
- Use async rollbar handlers. There are some options to use threads or even resque to send error reports
- Add timeouts to our wrapper

**Comment by javitonino** [comment]
Timeout added on rollbar-gem 2.11. Looking at upgrading.
