### ISSUE TITLE
Publish page for mobile SDK

### ISSUE THREAD

**Issue by jaakla** [CartoDB/cartodb#7278]
In Map Publish page indicate that viz.json URL can be used not only in cartodb.js, but also in CartoDB Mobile SDK. Add a forth button/icon for mobile publishing, with code sample. Something like following:

(icon with mobile)
**CartoDB Mobile SDK**
Add your map to your native mobile applications by using this line of code. _Read more_
_(selector for mobile platform/language: Android Java, iOS ObjC, iOS Swift, Xamarin C#)_
`mapView.loadCartoDbMap("6823d7c0-0bca-11e6-bc90-0e5db1731f59");` (field for copypaste)

**Comment by javisantana** [comment]
cc @saleiva

**Comment by urbanphes** [comment]
Hi Jaak, 
Here is the mockup
<br>
![- 04 settings - 02-00](https://cloud.githubusercontent.com/assets/14546701/16304118/4fc15e98-3954-11e6-8827-3175ea10ac8b.png)

**Comment by saleiva** [comment]
Remember to assign to @xavijam when approved

2016-06-23 15:08 GMT+02:00 Juanma <notifications@github.com>:

> Hi Jaak,
> Here is the mockup
>
>
> [image: - 04 settings - 02-00]
> <https://cloud.githubusercontent.com/assets/14546701/16304118/4fc15e98-3954-11e6-8827-3175ea10ac8b.png>
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/7278#issuecomment-228044267>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAIENWuQqhANtXlRy21Yn0gkaCl9BvItks5qOoVigaJpZM4IS3Vb>
> .
>



-- 
Sergio Alvarez Leiva

**Comment by xavijam** [comment]
Oh, didn't know about this, cc @nobuti :)

**Comment by jaakla** [comment]
Maybe we can even reduce number of buttons to 3. Literally the third one covers mostly also mobile, it is also about adding map to an app and the code snippet has same viz.json URL. 

Could title fit something like "Web and Mobile apps"? So text would be 'Add your map to your "js web" (doc link) or "native mobile" (link) apps using this URL'. 

Buttons would be also in logical order: easy, harder, most advanced.

**Comment by saleiva** [comment]
hey @jaakla having separated options create awareness of the whole platform so I'd try like this, nope?

**Comment by jaakla** [comment]
Yes, that's advantage of separate item and that's why I suggested initially it as separate item. But now I see that most of the data is exactly the same, so it looks a bit redundant. One more detail: for full mobile coverage we would need up to 4 slightly different code samples there (Android Java, iOS ObjC and Swift, Xamarin C#), so it would grow more. In the other hand, URL is same for all and we can live with cleaner UX.

**Comment by xavijam** [comment]
Closing this one because Mobile SDK block will not be available in the share modal for the moment.
