### ISSUE TITLE
cartodb attributions url should be https

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#7284]
despite I replaced most of http://cartodb.com/ occurrences to make use of https ([PR](https://github.com/CartoDB/cartodb/pull/7281)), I had to restore some to make tests pass

https://github.com/CartoDB/cartodb/pull/7281/commits/1a2e6402f2addb22fc3c259d07c3d57cd5ba283c
https://github.com/CartoDB/cartodb/pull/7281/commits/3d227705349053b18376014dd11bd49c5299df25

config should be changed so attributions url is https

**Comment by xavijam** [comment]
Closing since it should be fixed in the new Builder. 💋
