### ISSUE TITLE
ogr2ogr2.1 ignores overwrite option

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/cartodb#7297]
When the `-overwrite` option is added for ogr2ogr retries it is ignored. But it works if we place it at the end of the command line.

Happens with ogr2ogr2.1 and not with ogr2ogr2.

**Comment by iriberri** [comment]
Overwrite is **only** being used from  `loader.rb` in the retry fallbacks, so I think it's totally safe to move it for regular imports.

We're already seeing a lot of issues with fallbacks right now, basically:

````
OSM_USE_CUSTOM_INDEXING=NO 
PG_USE_COPY=YES 
PGCLIENTENCODING=ISO-8859-1
 /usr/bin/ogr2ogr2.1 -f PostgreSQL 
-oo AUTODETECT_TYPE=YES 
-oo QUOTED_FIELDS_AS_STRING=NO 
-oo X_POSSIBLE_NAMES=longitude,lon,l.....
-oo Y_POSSIBLE_NAMES=latitude,lat,l.....
-s_srs EPSG:4326 
-t_srs EPSG:4326 PG:"host=xxxx port=5432 user=xxxx dbname=xxxx password=xxxx" 
-lco DIM=2 -lco PRECISION=NO /tmp/imports/201xx/xxx.csv 
-nln cdb_importer.importer_xxxxx 
-doo PRELUDE_STATEMENTS="SET statement_timeout TO '1h'" 
-doo CLOSING_STATEMENTS='SET statement_timeout TO DEFAULT' 
-update 

2016-06-02 20:51:55 UTC: ogr2ogr.command_output = ERROR 1: Layer cdb_importer.importer_xxxxxx already exists, and -append not specified. Consider using -append, or -overwrite. 
ERROR 1: Terminating translation prematurely after failed translation of layer XXXX (use -skipfailures to skip errors)
````

**Comment by iriberri** [comment]
Hey @rafatower, pinging you as we added the  `-update` option at the end of the command when we updated ogr2ogr. I'm gonna give this some extra tests, but do you think it makes sense? As far as I've been investigating I think this would make more stable the current import situation. The PR that @jgoizueta prepared is here: https://github.com/CartoDB/cartodb/pull/7298
