### ISSUE TITLE
viz.json infowindow migration

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#7304]
as requested by @javisantana, creating the issue for cartodb3 viz.json migration

i.e. this will affect infowindows template, which currently are paths then they will be just a template name

**Comment by juanignaciosl** [comment]
Could you give more details about what is needed, please?

**Comment by matallo** [comment]
I think @javisantana can

In my specific case, for current users which have created maps with infowindows, the current infowindow template names are something like `table/views/infowindow_light`

new infowindow template names are just `infowindow_light`

so, when trying to open an infowindow, an error

```table/views/infowindow_light not found```

is returned

@javisantana can shed some light on the rest of attributes

**Comment by javisantana** [comment]
Yes, that's it, the viz.json v3 should have a different template route so:

1) viz.json v2 the template is sent as html, I guess the viz.json v3 (cartodb.js v4) needs the template as well. Right now we are reading from rails and including it in the viz.json (https://github.com/CartoDB/cartodb/blob/master/app/controllers/carto/api/layer_presenter.rb#L154). We should change the routes and read the right templates

2) fix the template routes as matallo says table/views/infowindow_light -> infowindow_light

3) we should include a new property `type` that would be "simple", "image", "whatever". It will be sent from the frontend and be whitelisted on backend (https://github.com/CartoDB/cartodb/blob/master/app/controllers/carto/api/layer_presenter.rb#L290) @alonsogarciapablo should define the types and matallo should include them

**Comment by alonsogarciapablo** [comment]
Actually @matallo and I have chatted briefly about changing this so that the editor sends the raw HTML template to CartoDB.js (instead of having a "registered" template and passing the template name). This way, for templates with header/image header, the editor will compose the right HTML and CartoDB.js will not need anything about template types, colors, image columns, etc... Thoughts @javisantana?

**Comment by javisantana** [comment]
1) You need the template because of the html customized templates, so it's not an option
2) You need the type because depending on the infowindow the logic in the view is different

**Comment by juanignaciosl** [comment]
@matallo can you reproduce the error in master, production, or is it happening in a development branch? Although we will have to change the vizjson logic if the template names change, the infowindow generation is supported in both. Example: [public map](https://team.cartodb.com/u/juanignaciosl/viz/e94eaba2-e912-11e5-8a32-0e3a376473ab/public_map) vs [public new embed](https://team.cartodb.com/u/juanignaciosl/editor/e94eaba2-e912-11e5-8a32-0e3a376473ab/embed), vizjson [v2](https://team.cartodb.com/u/juanignaciosl/api/v2/viz/e94eaba2-e912-11e5-8a32-0e3a376473ab/viz.json) vs [v3](https://team.cartodb.com/u/juanignaciosl/api/v3/viz/e94eaba2-e912-11e5-8a32-0e3a376473ab/viz.json).

**Comment by javisantana** [comment]
could you test it @matallo ?

**Comment by matallo** [comment]
this is not happening anymore, despite we are still sending the template names and changes are saved and work in editor3 and previuos map

keeping the issue open for tracking with the vizjson mirgation

**Comment by juanignaciosl** [comment]
@matallo this issue is specific to infowindows. You can track the mapping at #7316 and the implementation at #7391. Is there any other migration related to infowindows?

**Comment by matallo** [comment]
not that I can think of right now, closing then, thanks and sorry for the hassle!
