### ISSUE TITLE
add/remove indices when add/remove a widget

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#7306]
When adding a widget we should try to add an index to the column being used.

There are some circunstances where that's not possible:

- when the source is not a table but a complex SQL query
- when does not make any sense to add a index (for example a category with 2 columns or in general columns with low cardinality)

We should check what happens with analysis tables
cc @rochoa

**Comment by javisantana** [comment]
this is harder than it looks, do you have an approach for this?

**Comment by juanignaciosl** [comment]
I haven't thought about this yet. This is obviously hard to do right. Aside from the brute force approach (add it if you can) we could check the query plan.
