### ISSUE TITLE
send vector flag = true in the editor when number of features is less than 10k

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#7307]
Wnen the number of features is less than 10k (sum of all layers) we should switch to vector rendering

**Comment by juanignaciosl** [comment]
@xavijam has raised a couple of concerns about this. 

## A Increasing features

Example scenario:
1. Open a map in the editor with less than 10k features.
2. Add a new layer including 1M features --> tiler burns.

Alternatives:
a) Not using vector in the editor at all, use it only for embed. This is what I'd choose.
b) Reload the vizjson when something can increase the number of features (adding layers at least). @xavijam is really against this.

## B Speed

Counting in big tables is potentially slow. If it's done in short-circuit mode (count table rows one after another, and stop counting when you reach the limit) and we can rely on cache it might not be an issue though. Also related to embed-only usage.

About this, we might not need the _actual_ row count, and getting it from `pg_class` (current technique for dashboard sizes, for example) is fast.

@javisantana ideas?

**Comment by javisantana** [comment]
A)

that scenario can be managed by frontend switching to raster

B) use stats as you propose, in case there are no stats go raster

Another thing, the flag in the url should have precedence over the backend decision

**Comment by juanignaciosl** [comment]
👍 

Using the stats has another known issue: if the table grows a lot quickly there is a moment, until statistics get updated, where we might request vector tiles.
