### ISSUE TITLE
get undefined error because of poll

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#7319]
_Note: this' been reproduced in staging after deploying master of both the Tiler and CartoDB._

1. Import attached datasets: [datasets.zip](https://github.com/CartoDB/cartodb/files/252149/datasets.zip)
2. Create a map with those datasets.
3. Switch to the new editor.
4. Add a category widget on country column. You get this error in the console:

![screen shot 2016-05-06 at 14 21 55](https://cloud.githubusercontent.com/assets/932968/15072824/ef03246c-1395-11e6-8d76-06d4d707aa4a.png)

cc @alonsogarciapablo @xavijam @viddo

**Comment by xavijam** [comment]
After checking the problem, seems like CartoDB.js analysis poller try to start when that new widget is added and map is instantiated, could you check it @alonsogarciapablo please?

**Comment by alonsogarciapablo** [comment]
Taking a look.
