### ISSUE TITLE
New custom select doesn't go up/down correctly with keys

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#7327]
![screen shot 2016-05-09 at 11 28 56](https://cloud.githubusercontent.com/assets/132146/15108971/3e288c5e-15d9-11e6-805c-6aa840b34688.png)

### STR: 

- Go to new editor.
- Try any of the new forms with a new select on it (try to use one with several items and search enabled).
- Search for something that returns several results.
- Go down with the key.
- Selection doesn't work properly.

**Comment by nobuti** [comment]
Closed by #7341
