### ISSUE TITLE
Custom carousel doesn't move scroll to selected item

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#7328]
![screen shot 2016-05-09 at 11 31 23](https://cloud.githubusercontent.com/assets/132146/15109026/93c3cc8c-15d9-11e6-9ae8-6d0fdfcc2e19.png)

### STR:

- Go to new editor.
- Open or go to a form where a carousel is used (like widgets).
- Try selecting an option.
- Carousel doesn't move the scroll to see the whole selected item.

cc @matallo

**Comment by xavijam** [comment]
One more thing :): shadows behaviour is not working properly.

**Comment by nobuti** [comment]
Closed by #7348.

**Comment by matallo** [comment]
el puto amo
