### ISSUE TITLE
When a trade areas analysis is dissolved (aggregated data), layer interactivity should be refreshed

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#7333]
cc @rochoa @saleiva @javisantana

**Comment by javisantana** [comment]
From my point of view the analysis should have it's own interactivity

If as a result of an aggregation we pass from 1000 to 10 columns, that's fine we will have 10 features to interact with.

**Comment by xavijam** [comment]
I like your approach, let's leave then the current flow. Reset values and offer those who are available.

**Comment by javisantana** [comment]
yes, that's it, it's easier
