### ISSUE TITLE
Improve Geocoding Error Messages 

### ISSUE THREAD

**Issue by michellechandra** [CartoDB/cartodb#7338]
@iriberri 

Users email us frequently in Support when they encounter a general georeferencing error message that has no additional details.

These tickets are usually about two common geocoding issues:

1) There isn't enough storage space in their account to complete the georeferencing and they need to free up space 

2) They failed to delete the cartodb_georef_status column prior to geocoding which cause the geocoding to fail.

Improve the general error message so users don't need to email Support for help and can continue to use the Product.

**Comment by iriberri** [comment]
related https://github.com/CartoDB/cartodb/issues/5230

**Comment by iriberri** [comment]
I'm going to close this issue, at least temporarily, as I closed my PR to solve this. With the Builder the scenario is different, so let's see what challenges we have in there.
