### ISSUE TITLE
infowindow issues

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#7373]
- when trying to access a layer with no infowindows
https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb3/editor/layers/layer-content-views/infowindow-view.js#L9

(torque)
`Uncaught Error: layerInfowindowModel is required`

(labels)
`Uncaught TypeError: Cannot read property 'querySchemaModel' of undefined`

- when clicking in another template
https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb3/editor.js#L49
`Uncaught TypeError: Cannot read property 'update' of undefined`

- when hover and there's no template selected
https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb3/editor/layers/layer-content-views/infowindow/infowindow-style-view.js
`Uncaught TypeError: Cannot read property 'getName' of undefined`

also, as discussed with @saleiva, I'd need the visuals for the next cases (I can create a separate issue for each of these):
- when an analysis is being performed, we need the case where no fields are rendered
- select all/none link besides the show items title
![screen shot 2016-05-11 at 19 03 25](https://cloud.githubusercontent.com/assets/36676/15189449/15268db4-17ab-11e6-908a-dc0df6627a40.png)
- when "none" infowindow is selected, we will hide the fields and show an empty state

/cc @urbanphes 

I can provide example maps for these errors

/cc @alonsogarciapablo

**Comment by urbanphes** [comment]
>when "none" infowindow is selected, we will hide the fields and show an empty state

https://projects.invisionapp.com/share/5G4TKZHEJ#/screens/113084343
On click only we show the edit option.


>select all/none link besides the show items title

https://projects.invisionapp.com/share/5G4TKZHEJ#/screens/113084458
In this screen there is a module with number of selected and possibility to choose ALL. In the following screen we resolve when we have all options selected. The word "ALL" change to "NONE"

**Comment by matallo** [comment]
duplicated, keeping track in https://github.com/CartoDB/cartodb/issues/7418

closing then
