### ISSUE TITLE
Save layer definition when user done explicit change on infowindow form

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#7375]
https://github.com/CartoDB/cartodb/blob/4454ae443d9c06c127075edf3d8caceb8bb78b86/lib/assets/javascripts/cartodb3/data/layer-definition-model.js#L63-L65

Any persist change should be initiated by an explicit user action, since implicit state changes like these might cause unwanted changes when editor is opened. 

In this particular case, move this binding to be done when any input is modified (by the user) on the infowindow form view.

**Comment by matallo** [comment]
Thanks for reporting!
