### ISSUE TITLE
map export kept database user name in sql query

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/cartodb#7380]
When exporting a map from one account and importing into another account, everything worked perfectly except for the SQL applied. I had a custom sql statement which included my user name and table name (`eschbacher.table_name`) which CartoDB had auto-completed for me before I exported the map. Once the map was imported to my other private account, the SQL failed since user `eschbacher` doesn't exist.

<img width="533" alt="screen shot 2016-05-11 at 15 44 22" src="https://cloud.githubusercontent.com/assets/1041056/15194122/45bf2e52-178f-11e6-90c4-c85041380fdd.png">

Removing the `eschbacher.` portion of the query produced the map perfectly.

**Comment by juanignaciosl** [comment]
cc @gfiorav @javitonino

**Comment by iriberri** [comment]
Related? https://github.com/CartoDB/cartodb/issues/3205

**Comment by juanignaciosl** [comment]
_Maybe_, although the scope of this is bigger, since we might have to manipulate custom sql as well.

**Comment by javisantana** [comment]
the replacement client side is done using a pretty naive way: with the list of tables we do a replace of each table by name.table.

The reverse way would be really easy. It might fail and it will for sure, but it will work on 99% of the cases.

(during the import process we should check if the user is an organization user and do the same replacement BTW)
