### ISSUE TITLE
Enterprise user gets 404 error message if their email has already been used

### ISSUE THREAD

**Issue by csobier** [CartoDB/cartodb#7402]
Michelle and I were testing some Enterprise workflows, Note the following bug:
- As an Enterprise owner, I invited her to my organization by sending an invite to her work email.
She got the email invite but got a 404 error when trying to login
- When I tried to add  her manually, we realized that her email has already been taken

Michelle was able to confirm that the actual rollbar stated: `
CartoDB::CentralCommunicationFailure: Application server responded with http 422: {"errors":["Email has already been taken"]}`

Can we perhaps enhance the 404 error message to be indicative of the actual error?

@gfiorav @juanignaciosl

**Comment by juanignaciosl** [comment]
cc @javitonino @xavijam

**Comment by javitonino** [comment]
Note: this appears to only happen when the existing user and the organization are in different clouds. There is already a check in place to avoid inviting users when the email already exists, but is checked only locally.
