### ISSUE TITLE
Dashboard requests mapviews for all maps in an organization while loading public view

### ISSUE THREAD

**Issue by zenitraM** [CartoDB/cartodb#7410]
Steps to reproduce:
- View an organization public page with a lot of users and a lot of visualizations -> takes a long time
- See `redis-cli monitor` meanwhile

It seems that it is loading mapviews for all visualizations of all users to render the page. It is also doing four `ZSCANs` per user which according to @luisbosque it should not be doing:

```
1463498750.816189 [5 10.0.130.4:38613] "zscan" "user:[USER]:mapviews:stat_tag:[VIZ_ID]" "0" "MATCH" "201604*"
1463498750.816825 [5 10.0.130.4:38613] "zscan" "user:[USER]:mapviews:stat_tag:[VIZ_ID]" "0" "MATCH" "201605*"
1463498750.817808 [5 10.0.130.4:38613] "zscan" "user:[USER]:mapviews_es:stat_tag:[VIZ_ID]" "0" "MATCH" "201604*"
1463498750.818642 [5 10.0.130.4:38613] "zscan" "user:[USER]:mapviews_es:stat_tag:[VIZ_ID]" "0" "MATCH" "201605*"
```

cc @xavijam

**Comment by xavijam** [comment]
cc @CartoDB/backend

**Comment by ethervoid** [comment]
This could be to show the histrogram of mapviews for the maps in the maps thumbnails?

**Comment by xavijam** [comment]
Yep, all of that is for the maps stats.

**Comment by juanignaciosl** [comment]
Those zscans come from [stat checking](https://github.com/CartoDB/cartodb/blob/ebfb0e62bfdb6bd941408b4d2f0826b3195318fb/lib/cartodb/stats/api_calls.rb#L113). Anyway it should only query as many as displayed in the page.

Unassigning this (after adding `backend` and `Editor` tags) so any other @CartoDB/backend can take it (we've had some "issue assignment internal fragmentation issues" debate today).

**Comment by javitonino** [comment]
This is not done for display purposes, but to sort maps by the number of views. That is why it slows down when you add more maps, as it has to retrieve stats for all maps in the list, even those in other pages. Fun fact: it doesn't even memoize the stats for each map, so it is doing `O(n*log(n))` queries where it could be doing `O(n)`.

I'll first try and memoize stats results first and see if that's enough. If not, we can discuss another ordering or a more efficient way to cache map views.

**Comment by javitonino** [comment]
After merging #7443 the load is more reasonable-ish. It still runs 4 zscan per visualization (O(n)), but it is an order of magnitude better than before. team.cartodb.com now loads in 3-4s.

Keeping this in backlog for further improvement, but holding for now.

**Comment by xavijam** [comment]
:+1:

**Comment by xavijam** [comment]
great achievement!

**Comment by juanignaciosl** [comment]
Closing automatically because of inactivity. If anybody considers that this still important, please reopen and it'll be prioritized.
