### ISSUE TITLE
Code disable state for popup tab

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#7414]
A clear example is:

If an aggregation style type is selected (like squares) and the infowindow is enabled with any column, map request fails. So from now on we reset infowindow fields. But popup tab or block should appear as disabled of with a custom message, because we can't enable it.

cc @javisantana @saleiva @matallo

**Comment by saleiva** [comment]
We should use the yellow box below like in other places to warn about this.
Dont you think?

**Comment by xavijam** [comment]
:+1:

**Comment by xavijam** [comment]
Placeholder state + infobox saying "Popup is disabled due to..."
