### ISSUE TITLE
Reduce Rollbar usage

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#7415]
We're using too much Rollbar and going overquota. We should reduce it ASAP.

cc @CartoDB/backend @xavijam

**Comment by javitonino** [comment]
Top items (1-18 may):
- [KeyError: KeyError](https://rollbar.com/vizzuality/CartoDB/items/17130) (peak from a single user)
- [Dropping temp table](https://rollbar.com/vizzuality/CartoDB/items/13664/) (debugging, we can probably kill this)
- [Error geocoding using GME](https://rollbar.com/vizzuality/CartoDB/items/16331)
- [Failed import](https://rollbar.com/vizzuality/CartoDB/items/19/)
- [ghost tables](https://rollbar.com/vizzuality/CartoDB/items/3942/)

Nothing too excessive, we should be fine after fixing the problem in staging.

**Comment by juanignaciosl** [comment]
Right. Sorry about the rush.
