### ISSUE TITLE
Visualization export takes the wrong id

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#7417]
In some cases the export is requested with a id that doesn't match the actual visualization id. In this log you have the full information: https://rollbar.com/vizzuality/CartoDB/items/18411/occurrences/13360110358/ . As you can see, the referral visualization id doesn't match the requested id

**Comment by juanignaciosl** [comment]
New occurrences: https://rollbar.com/vizzuality/CartoDB/items/18411/?item_page=0&#instances

**Comment by javitonino** [comment]
STR:
 - Go to a dataset
 - Create a map from the dataset (click visualize)
 - Export the map
 - :bomb: The `vis_data` has the id from the dataset until you reload the page
