### ISSUE TITLE
New popup block issues

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#7418]
- [x] 'None' type is confusing, I'd get rid of it ( @urbanphes @saleiva ).
- [x] If popup is opened and user unselects all fields, it should close the popup (related -> #7414).
- [x] Select/unselect all behaviour.
- [x] Choose popup width is not added.
- [x] When color popup is selected, color picker is not added (possible right now with new fill component).
- [x] Common elements in both click and hover carrousel should be in the same order (ex: Light, Dark,...)
- [x] If schema query model changes, popup view should show the "loading" state, and when it finishes, show the current available fields.
- [x] Tooltip popup is not showing up after selecting any column.
- ~~Add possibility to edit the click/hover popups~~ (cc @nobuti).

cc @matallo @alonsogarciapablo @javisantana

**Comment by xavijam** [comment]
Those are the things I miss from the popup block. There are 2 things we should check from the design part @saleiva @urbanphes.

**Comment by matallo** [comment]
>  'None' type is confusing, I'd get rid of it ( @urbanphes @saleiva ).

Agree, right now I have to do _tricky_ things like set an empty template + unselect all the fields

**Comment by saleiva** [comment]
About point one, I do think you guys are biased by the actual editor. I feel pretty good about adding that option actually. Do you mind if we test it?

**Comment by matallo** [comment]
Indeed :P I'm more biased because of the current implementation than any other thing. Actually, I had working the none option, and in that case the fields weren't showing. However, in order to effectively disable the infowindows I had to unselect all the fields, or change how it works in cartodb.js (if I'm not wrong).

**Comment by matallo** [comment]
after discussing with @javisantana we're unselecting all fields when changing to "None"

**Comment by saleiva** [comment]
There is another thing (feel free to add to the list).
When changing fields on the click editor, the whole map is reloaded and it shouldn't since we are using the grid.json.
On the other hand, when changing the over infowindow fields the map doesn't get reloaded, and it should.

**Comment by matallo** [comment]
indeed, for that we need to work with `compileTemplate` and pass cartodb.js the `template` already instead of the `template_name`, and I'm already working on that

this needs to be reviewed and merged first, though https://github.com/CartoDB/cartodb/pull/7419

**Comment by matallo** [comment]
>  Common elements in both click and hover carrousel should be in the same order (ex: Light, Dark,...)

fixed in https://github.com/CartoDB/cartodb/pull/7532

>  Popup image selector is not present, it should provide a way to select the column image (as it appears in the designs).

nice to have as per @javisantana, right now it works with the first column

> If schema query model changes, popup view should show the "loading" state, and when it finishes, show the current available fields.

wip

> Tooltip popup is not showing up after selecting any column.

@alonsogarciapablo will take a look
