### ISSUE TITLE
Infowindows migration to new embed is not working

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#7421]
- Open the map below.
- Open chrome developer tools.
- Click over an infowindow.

https://team.cartodb.com/u/mamataakella/editor/23e4d71c-1bba-11e6-a69e-0e3ff518bd15/embed

**Comment by juanignaciosl** [comment]
It works for other maps. Check, for example, this [old embed](https://team.cartodb.com/u/juanignaciosl/viz/1e00e2c4-1ce5-11e6-bf28-0e787de82d45/public_map) vs the [new one](https://team.cartodb.com/u/juanignaciosl/editor/1e00e2c4-1ce5-11e6-bf28-0e787de82d45/embed). Both have the same `template_name`: `table/views/infowindow_light`. @xavijam have you got any clue about the reason for the JS error? :-\

**Comment by xavijam** [comment]
Nope, I figured out that it was a problem related with the infowindow migration, sorry.

**Comment by juanignaciosl** [comment]
Ok, reproduced. it fails for visualizations with severals layers, having one with infowindows and other, before it (layer 1 without infowindows, layer 2 with them).

cc @alonsogarciapablo @AbelVM @makella

**Comment by AbelVM** [comment]
Mine is failing with just one layer 

https://team.cartodb.com/u/abel/editor/a9c1c1c2-1da1-11e6-ac1d-0e674067d321/embed

**Comment by alonsogarciapablo** [comment]
Taking a look! (@AbelVM nice map BTW!)

**Comment by juanignaciosl** [comment]
Oh, I see, @AbelVM. I don't know why yet, but it's relevant for us.

**Comment by juanignaciosl** [comment]
It's related to cartodb.js, as it searches for `infowindow_light` when there's no template. @alonsogarciapablo is on it.

**Comment by alonsogarciapablo** [comment]
Solved in CartoDB/cartodb.js#1270.
