### ISSUE TITLE
Map with Torque and non-Torque layer won't load in new embed

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#7422]
To reproduce:
 1. Create a map in the old editor
 2. Make the 1st layer of type Torque
 3. Create a new non-Torque layers
 4. You should have a map with layer 1 = Torque, layer 2 = non-Torque
 5. Load the map in the new embed.

The Torque layer will be shown, but not the normal layer. Console log:
```
Error creating the map instance on Windshaft: style0:4:0 Rule -torque-frame-count not allowed for Map.
style0:4:0 Unrecognized rule: -torque-frame-count
style0:5:0 Rule -torque-animation-duration not allowed for Map.
style0:5:0 Unrecognized rule: -torque-animation-duration
style0:6:0 Rule -torque-time-attribute not allowed for Map.
style0:6:0 Unrecognized rule: -torque-time-attribute
style0:7:0 Rule -torque-aggregation-function not allowed for Map.
style0:7:0 Unrecognized rule: -torque-aggregation-function
style0:8:0 Rule -torque-resolution not allowed for Map.
style0:8:0 Unrecognized rule: -torque-resolution
style0:9:0 Rule -torque-data-aggregation not allowed for Map.
style0:9:0 Unrecognized rule: -torque-data-aggregation
```

Seems like a problem with vizjson v3 generation and/or named maps.

**Comment by javitonino** [comment]
Only happens for embed, not if exporting json to cartodb.js. The problem only occurs in layer generation with `forced_privacy_version: :force_named`. So probably, a conflict between torque and analysis in named map usage.

**Comment by javitonino** [comment]
Ok, so what is happening here, for a map with two layers (one plain choropleth, one Torque):

 1. The generated [vizJSON](https://gist.github.com/javitonino/80c716edf6c4591feb2ecbd1c352d4aa) includes a namedmap layer and a Torque layer. There are some problems with `order` (always 1 for named maps, so both layers hace the same order) and `layer_index` generation. I guess `layer_index` is the index in the named map, correct me if I'm wrong.
 2. The following instantiation request is send to named maps API `{ "layer0": 1, "layer1": 1, "styles": { "1": "/** torque visualization ..." } }`. Even when fixing order and index in the vizJSON, cartodb.js is taking the wrong index for the layers, it is based [solely in order](https://github.com/CartoDB/cartodb.js/blob/v4/src/windshaft/named-map.js)
 3. Windshaft returns an error, as the style is applied to the choropleth layer (1) instead of the torque layer (3). See the [named map template](https://gist.github.com/javitonino/e51d3eda2ddf45090c5159e13d8ed9cc).

**Comment by javitonino** [comment]
It seems the core problem is `layer_index`. The editor doesn't generate it correctly, and cartodb.js doesn't use it (using internal layer order instead). cc @alonsogarciapablo

**Comment by javitonino** [comment]
I got this working with the following changes:
 - Use the correct `layer_index` for Torque layers.
 - Add `layer_index` to all other layers in named maps (was only generated for Torque before), in the same format as the Torque ones (`layer[:options][:named_map][:layer_index]`).
 - Modify cartodb.js to read `layer_index` instead of using indexes, in `named-map.js`. Probably needs a bit more logic to fallback to indexes if we want to be able to load vizjson v2 with cartodb.js v4.

Does this make sense?

**Comment by javitonino** [comment]
I have candidate PR's for this here:
 - https://github.com/CartoDB/cartodb/pull/7454 (editor: add `layer_index`)
 - https://github.com/CartoDB/cartodb.js/pull/1269 (use `layer_index` instead of layer ordering)

Talking with @alonsogarciapablo, maybe it's finally time to flatten the vizjson structure for named maps (and make sure it is ordered the same as in the named maps, i.e: torque layers on top) so we can avoid adding the layer index. We now have three layer orderings: the order on which the layers appear in the vizjson, the `order` field (order in the editor) and, with this change, `layer_index` (order in the named map template).

cc @juanignaciosl @xavijam

**Comment by alonsogarciapablo** [comment]
I'm working on a fix for this at the CartoDB.js level. I think it will be enough :)

**Comment by alonsogarciapablo** [comment]
Fixed in CartoDB/cartodb.js#1272.
