### ISSUE TITLE
Exporting a private map shared with me fails

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#7423]
1. Share a private map with a user.
2. Open the public view of that map with that user.
3. Try to export it. It will fail with 403: `User Must be viewable by the user`

cc @andrewbt @gfiorav

**Comment by gfiorav** [comment]
Share a **private** map with a user. `public` and `link` work fine

**Comment by juanignaciosl** [comment]
Assigning to @gfiorav because the problem is the request URL. Please continue at `7423-Exporting_a_private_map_shared_with_me_fails` and merge the changes there (test and improved message).

**Comment by gfiorav** [comment]
Closed via https://github.com/CartoDB/cartodb/pull/7433
