### ISSUE TITLE
Can't change selected dataset on add-layer modal

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#7426]
STR:
1. open add-layer modal
1. click a dataset (gets selected)
1. click another dataset

Expected result:
- Changes selection to the last clicked dataset

Actual result::
- The previously selected dataset remains selected

Clicking the selected dataset deselects it, allowing to selected another… not very intuitive.
cc @xavijam

**Comment by xavijam** [comment]
I feel I copied the behaviour from the current editor, but in any case, I'll change it 👍 .

**Comment by xavijam** [comment]
It will change with the new "add-dataset-modal".
