### ISSUE TITLE
Adding a second layer from the new editor uses first layer columns for interactivity

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/cartodb#7427]
If I enter the new editor with a map that has a single dataset layer with table `cities_subset`(and base map), then, from the new editor add a layer with other table `educacion`, an error occurs when instantiating the map, because the second table is using the first table's columns for interactivity.

Here's the (abbreviated) MapConfig that the editor tries to instantiate:

```json
{
  "layers": [
    {
      "type": "cartodb",
      "options": {
        "cartocss": "...",
        "cartocss_version": "2.1.1",
        "interactivity": [ "cartodb_id", "_feature_count", "iso2", "name", "population" ],
        "sql": "select * from cities_subset"
      }
    },
    {
      "type": "cartodb",
      "options": {
        "cartocss": "...",
        "cartocss_version": "2.1.0",
        "interactivity": [ "cartodb_id", "_feature_count", "iso2", "name", "population" ],
        "sql": "SELECT * FROM educacion"
      }
    }
  ],
  "dataviews": { },
  "analyses": [ ]
}
```

Notice the interactivity columns are the same for both maps (and are those of `cities_subset`.

**Comment by xavijam** [comment]
I feel this doesn't happen anymore, does it @alonsogarciapablo?

**Comment by alonsogarciapablo** [comment]
I don't think so. I'm closing it. Let's reopen it if we encounter this again.
