### ISSUE TITLE
CORS support for Import API

### ISSUE THREAD

**Issue by alasarr** [CartoDB/cartodb#7441]
Right now it's not possible to call import API from Javascript Browser. As work around I'm using a proxy but that feature would be really nice.

I know it could sound strange but at some use cases when you have the API_KEY at the client (without hard coding it at the app code) it's useful.

For example, we've an HTML application which create datasets at CartoDB.

**Comment by javisantana** [comment]
I think this is duplicated: https://github.com/CartoDB/cartodb/issues/2546

**Comment by alasarr** [comment]
Yes!

**Comment by javisantana** [comment]
thanks!
