### ISSUE TITLE
Widget won't filter because named map template hasn't source

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#7449]
There's [a map whose widgets won't filter](https://team.cartodb.com/u/juanignaciosl/editor/e541adb0-204a-11e6-99ce-0e31c9be1b51/embed). It's caused by the layer template: it has `sql` instead of `source`. As widgets filter source analyses and the tiles are computed on the sql instead, they display everything.

Hint: it might be related to a dataset privacy change, as the table was originally private (but it might be not).

cc @javitonino @gfiorav @alonsogarciapablo

**Comment by javitonino** [comment]
When exporting/importing the map, the problem goes away. The difference is that in the original there are no widgets for the template of that map. The problem appears to be that the original widgets have `source_id` set to `a0`, and the query to determine which widgets appear on each layer filters by `source_id IS NULL`. They are generated as `dataviews` instead.

The copied map has `source_id` set to NULL and appear as widgets in the named map template and filtering works.

**Comment by juanignaciosl** [comment]
This is no longer happening, and changing the privacy doesn't break it.
