### ISSUE TITLE
[Fill component] Possibility to change/select categories

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#7451]
With the previous category wizard, something like this appeared:

![screen shot 2016-05-23 at 11 22 11](https://cloud.githubusercontent.com/assets/132146/15466222/acade9c6-20d8-11e6-8252-7300905899cd.png)

We have doubts how to achieve that with the new fill component.

cc @javisantana @javierarce

**Comment by javierarce** [comment]
Talking with @xavijam we think we could use this solution:

![screen shot 2016-05-23 at 18 18 31](https://cloud.githubusercontent.com/assets/4933/15477111/47ff4534-2113-11e6-929a-78ad8b284307.png)

**Comment by saleiva** [comment]
That was the one that was designed :)

2016-05-23 18:22 GMT+02:00 Javier Arce <notifications@github.com>:

> Talking with @xavijam <https://github.com/xavijam> we think we could use
> this solution:
>
> [image: screen shot 2016-05-23 at 18 18 31]
> <https://cloud.githubusercontent.com/assets/4933/15477111/47ff4534-2113-11e6-929a-78ad8b284307.png>
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/7451#issuecomment-221022348>
>



-- 
Sergio Alvarez Leiva

**Comment by xavijam** [comment]
We will need to add a new property in order to store the categories, so:

```js
{
  fill:  {
    size: …,
    color: {
      attribute: 'countries',
      ramp: ['#CCC', 'red', 'blue', 'purple'],
      domain: ['_', 'Albania', 'Andorra', 'Luxemburg'], // Remember first value will be 'Others'/rest
      …
    }
  }
}
```
@juanignaciosl (_editing migragion wiki right now_).
cc @rochoa & @javisantana

**Comment by javisantana** [comment]
Ok', i'll add support in the style generation
