### ISSUE TITLE
Uncaught TypeError: Cannot read property 'ownerDocument' of undefined (context-menu-view:55) 

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#7457]
Saw this exception in the dev console in production env:

```
jquery:1430 Uncaught TypeError: Cannot read property 'ownerDocument' of undefined
b.contains @ jquery:1430
b.exports.f.core.View.extend._onDocumentElementClicked @ context-menu-view.js:55
_.event.dispatch @ jquery:4435q.handle @ jquery:4121
```

[content-menu-view:55](https://github.com/CartoDB/cartodb/blob/350f182802ad10d32cfce4b24a88b52e1fb621dd/lib/assets/javascripts/cartodb3/components/context-menu/context-menu-view.js#L55)

**Comment by alonsogarciapablo** [comment]
@xavijam is working on it.
