### ISSUE TITLE
Some Editor maps use Positron labels below and labels only at same time

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#7471]
S/B 9007187

Hi @juanignaciosl if this needs to go to someone else would you please re-assign? Thanks!

## Context/Process
I can't replicate in team account Editor with different data, but example's [here.](https://nycdoittpublicdata.cartodb.com/u/nycpublicdata/viz/be21c8c2-def6-11e5-b40b-0e787de82d45/public_map) FYI being used in [this blog post's](https://blog.cartodb.com/import-export-with-cartodb/) 'NYC subway network' link.

[viz.json](https://nycdoittpublicdata.cartodb.com/u/nycpublicdata/api/v2/viz/be21c8c2-def6-11e5-b40b-0e787de82d45/viz.json) is showing "Positron (labels below)" on bottom layer and "Positron Labels" on top of data layers.

## Current result
At zoom level 13:
![screen shot 2016-05-23 at 6 05 06 pm](https://cloud.githubusercontent.com/assets/1779444/15486060/ec56ae18-2110-11e6-965a-c7788f524e7b.png)

## Expected result
Only Positron or Positron labels below will show, not labels only.

**Comment by juanignaciosl** [comment]
It's stored wrong in the database, just like vizjson shows:

```ruby
irb(main):003:0> v.layers[0]
=> #<Carto::Layer options: {"visible"=>true, "type"=>"Tiled", "name"=>"Positron (labels below)",

=> #<Carto::Layer options: {"visible"=>true, "type"=>"Tiled", "default"=>"true", "url"=>"http://{s}.basemaps.cartocdn.com/light_only_labels/{z}/{x}/{y}.png",  ... "name"=>"Positron Labels",
```

When a user changes the basemap from labels on top Positron to labels below Positron there's a DELETE to remove the labels layer and then a PUT changing the base layer. I guess that the DELETE failed for a random reason and only bottom basemap was changed.

@ztephm: has the user tried to change the basemap to labels on top and labels on bottom? could we do it on his behalf? that will probably clean the layer configuration. If it does not, I can delete the wrong layer.

cc @xavijam

**Comment by ztephm** [comment]
thanks @juanignaciosl - don't know if user did that BUT we do have permission to change that map in the nycpublicdata account.

**Comment by juanignaciosl** [comment]
Changing the basemap cleaned the inconsistency.
