### ISSUE TITLE
.carto export of multi-geometry table takes only one geometry

### ISSUE THREAD

**Issue by jaakla** [CartoDB/cartodb#7472]
It looks it takes just first geometry, so after exporting this map I get only Points for one of the tables (_table_3625612593_), which should have a lot of polygons as main element: https://cartomobile-team.cartodb.com/u/nutiteq/viz/597dc568-1bf7-11e6-af41-0ecd1babdde5/map 
@juanignaciosl @rafatower

**Comment by rafatower** [comment]
Actually cartodbfy'ed tables are meant to have just one column `the_geom` with just one geometry type (just points, lines or polygons, but not points and polygons). The fact that you got imported multiple geometry types is indeed a bug.

**Comment by javisantana** [comment]
we allow to have multiple geometry types in a cartodbfied table if you do a query like `update table set the_geom = 'POLYGON....' where cartodb_id < 10`

So I think this something we'd need to fix
