### ISSUE TITLE
Changing style to region type doesn't indicate faulty property

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#7476]
Changing to region style [sets at least one faulty default, e.g. _admin0_ as the dataset](https://github.com/CartoDB/cartodb/blob/522d57488bfc883c5e5991866cf9a73c3d5c0b8e/lib/assets/javascripts/cartodb3/editor/style/style-defaults/regions-aggregation-style-defaults.js#L12).

Expected result:
- Indicate missing/faulty data in the form

Actual result:
- No visual cue that something is wrong:
  - ![screen shot 2016-05-24 at 11 23 39](https://cloud.githubusercontent.com/assets/978461/15498951/feb995e8-21a1-11e6-95df-c58fa0df8801.png)
- looking in the dev console there's a failing `map?stat=`-request with 404 _relation "admin0" does not exist_ error.

**Comment by xavijam** [comment]
Yes, we know that it is not working. Tracked here:
https://github.com/CartoDB/cartodb/issues/7329
https://github.com/CartoDB/cartodb/issues/7413

**Comment by xavijam** [comment]
Already working in production (https://github.com/CartoDB/cartodb/pull/7559), it will be improved with more datasets.
