### ISSUE TITLE
Font on zero-case is incorrect

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#7480]
![screen shot 2016-05-24 at 14 54 43](https://cloud.githubusercontent.com/assets/132149/15504516/a98a0d5a-21bf-11e6-8e16-fdff932ff1bf.png)

It should be way thinner

**Comment by piensaenpixel** [comment]
uhmm this is production
![image](https://cloud.githubusercontent.com/assets/1214201/15505071/2ca677d0-21c2-11e6-8c0b-dfca42aa4841.png)

**Comment by saleiva** [comment]
Happening on the macbook Air, Latest Chrome version

**Comment by saleiva** [comment]
Also you can see in @nobuti's computer happens the same
https://github.com/CartoDB/cartodb/pull/7496
