### ISSUE TITLE
popup components z-index seems wrong

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#7481]
It gets cut with the white area in the bottom of the screen

![screen shot 2016-05-24 at 14 56 46](https://cloud.githubusercontent.com/assets/132149/15504550/cc1cb4f8-21bf-11e6-844f-6d5f8562bb18.png)

**Comment by xavijam** [comment]
It is related with view scroll, already fixed by @nobuti in https://github.com/CartoDB/cartodb/issues/7463.
