### ISSUE TITLE
Migrated components assume font to be set globally

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#7482]
With migrated components I'm referring to certain styles that now are shared with the Dashboard, that have a different set and approach to setting default styles.

E.g.
![screen shot 2016-05-24 at 12 40 53](https://cloud.githubusercontent.com/assets/978461/15504908/6ccf9220-21c1-11e6-92dc-d916b64d56ce.png)

On the dashboard the font is set on the generic/default HTML elements, https://github.com/CartoDB/cartodb/blob/ebfb0e62bfdb6bd941408b4d2f0826b3195318fb/app/assets/stylesheets/common/default.css.scss

**Comment by viddo** [comment]
@xavijam @piensaenpixel not sure how you want to go around solving this?

**Comment by xavijam** [comment]
Closing right now because we can't provide a global font until we have all our views migrated (pending dashboard, public views, etc).
