### ISSUE TITLE
buffer analysis not enabled for lines data sources

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#7483]
1) go to a visualization with a layer with lines
2) add analysis

buffer analysis is not enabled.

Looks like a simple issue but it's not. Buffer analysis is going to be integrated with the trade areas but trade areas does not make any sense with lines, so what do we do?

Maybe just keep it disabled is better 

cc @saleiva @viddo

**Comment by saleiva** [comment]
I'd keep the time option disabled and keep just the distance one

2016-05-24 15:53 GMT+02:00 javi santana <notifications@github.com>:

> 1) go to a visualization with a layer with lines
> 2) add analysis
>
> buffer analysis is not enabled.
>
> Looks like a simple issue but it's not. Buffer analysis is going to be
> integrated with the trade areas but trade areas does not make any sense
> with lines, so what do we do?
>
> Maybe just keep it disabled is better
>
> cc @saleiva <https://github.com/saleiva> @viddo <https://github.com/viddo>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/7483>
>



-- 
Sergio Alvarez Leiva

**Comment by viddo** [comment]
Solved in 	05ce3d0 as part of PR #7578, so closing 🎉
