### ISSUE TITLE
Moving the map on the new editor doesn't persist the position after reloading

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#7484]
Enter to a map, move it, reload. The position is the original one instead of the new one

**Comment by viddo** [comment]
Whoever fixes this, please make sure that the editor only saves position when the map position is moved _by the user_, not due to a window resize (e.g. opening the dev console). There should not be any POST /PUT requests when the user enters the editor.

**Comment by saleiva** [comment]
+1

2016-05-24 16:18 GMT+02:00 Nicklas Gummesson <notifications@github.com>:

> Whoever fixes this, please make sure that the editor only saves position
> when the map position is moved *by the user*, not due to a window resize
> (e.g. opening the dev console). There should not be any POST /PUT requests
> when the user enters the editor.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/7484#issuecomment-221285546>
>



-- 
Sergio Alvarez Leiva

**Comment by xavijam** [comment]
That's not possible right now, because we would need an event or something like that which notifies map view that native map has been changed by the user, like, `dragend` or something like that. Take into account that thing is not implemented in CartoDB.js.
cc @alonsogarciapablo.

**Comment by xavijam** [comment]
Work started in branch `issue-7484`, need to update CartoDB.js with https://github.com/CartoDB/cartodb.js/pull/1282.

**Comment by saleiva** [comment]
ping :P

**Comment by saleiva** [comment]
Should this be working?

**Comment by xavijam** [comment]
Nope, I'll open the PR today and try to merge as soon as possible.

**Comment by xavijam** [comment]
https://github.com/CartoDB/cartodb/pull/8182
