### ISSUE TITLE
Polygon datasets are rendered as points in new editor when using "by value" styling

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb#7485]
Steps:
* Get a dataset with polygons
* Make a map with the old editor
* Switch to the new editor, everything looks ok
* Go to the styling and change the fill from "solid" to "by value"
* Bang! Now you have points

Note: the styling menus in the new editor displays the options for points from start, even when displaying polygons the right way

cc @xavijam

**Comment by xavijam** [comment]
We have found the reason. The query we use to retrieve or guess the geometry type is giving us some headaches. We have agreed to use the same query we have in the current editor (first 20 rows, order by cartodb_id).

@AbelVM @javisantana @viddo
