### ISSUE TITLE
Change how analysis types are decided to eligible for add-analysis workflow

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#7486]
Currently we're using [the camshaft wrapper's `getValidInputGeometriesForType `](https://github.com/CartoDB/cartodb/blob/e8d709f0253f20af08004a83a5a008ee953813f3/lib/assets/javascripts/cartodb3/data/camshaft-reference.js#L74-L90) to check if an analysis can be created for a given source node. This was the quick'n'dirty implementation while @rochoa was on vacation, but we missed to keep track of it afterwards…

@rochoa How could/should we solve this properly? Could the expected geometry types be defined statically directly on the camshaft reference instead to avoid duplicating data (types)? Or will we need something more dynamic to be checked at runtime (e.g. geometry types to vary depending on params)?

Kind of related to #7483 where I might have to change the expected type for a buffer analysis for example…. cc @javisantana

**Comment by rochoa** [comment]
I had a proposal for this: https://github.com/CartoDB/camshaft/pull/5. I forgot to cc you.

Some input nodes might support more than one geometry type, that's why it is an array instead of string/type. What do you think? Could that work for you?

**Comment by viddo** [comment]
> Some input nodes might support more than one geometry type, that's why it is an array instead of string/type. What do you think? 

👍 

It looks like should do the trick. 

Related to the other #7483 though, according to that PR the buffer analysis would only work with points, so what @saleiva asks for there (to work for lines but disable time param) would not work then?

Also, I guess this PR would have to be updated and released as 0.8.0 to be available on the editor, right?

**Comment by rochoa** [comment]
Oh, sorry about the misleading buffer example over there, it should work with other geometry types as well. I will take care of that 😈 .

**Comment by viddo** [comment]
🙆

**Comment by javisantana** [comment]
One interesting thing that could help is provide a mapping, like

```js
input: {
'point': 'polygon',
'polygon': 'polygon'
'line': 'line'
}
```

this means the node accepts point, polygon and lines and what is the output for each one

**Comment by rochoa** [comment]
In some cases an analysis might return different geometries based on some params. So ... what about:

```
input: {
  'point': ['point', 'polygon']
  'polygon': ['polygon']
  'line': ['line']
}
```

**Comment by javisantana** [comment]
then i don't know if that's going to be so useful, @viddo ?

**Comment by rochoa** [comment]
And also ... probably we need to support unknown output types:

```
input: {
  '*': ['*']
}
```

For instance a _filter_ analysis will return the same geometry type but we don't know which one it's at reference level.

**Comment by viddo** [comment]
> In some cases an analysis might return different geometries based on some params.

> then i don't know if that's going to be so useful

> probably we need to support unknown output types: …

I'm not sure having _possible output geometries_ would be practically useful (especially for unknown ones). Right now we fetch the geometry type based on a node's result to know the output type, which I think is more better since with that we can guarantee that the new node will work (at the time of creation at least).

To not complicate things right now I'd say a list of _accepted input_ geometry types is sufficient.

**Comment by rochoa** [comment]
OK, just accepted geometries.

Anyway in the future we could add "output" property with the map we were proposing:

```
ouput: {
  'point': ['point', 'polygon'],
  'polygon': ['polygon'],
  'line': ['line']
}
```
