### ISSUE TITLE
Event tracking anonymous exports error

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#7493]
Event tracking logs an error for anonymous exports: https://rollbar.com/vizzuality/CartoDB/items/18573/?item_page=0&#instances

So, `EventTracker` should allow `nil` users (or, at least, don't track it as an error, because it's not).

**Comment by jmartinter** [comment]
I'll change the rollbar log level to 'warning' to avoid tracking false errors.
