### ISSUE TITLE
column without title is ignored when importing a CSV

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#7497]
a csv like

```
t1;t2;;t4
1;2;3;4
```

will import only columns `t1`, `t2` and `t4`

**Comment by iriberri** [comment]
@javisantana are you able to reproduce the issue in production? I just tried, and it's working as I would expect: generating a name for the column with "empty" name (field_3) and adding the third column of data on it.

Input columns names with unsupported identifiers are renamed.

Here's my result:

![image](https://cloud.githubusercontent.com/assets/1730320/15534364/beee80d2-2268-11e6-93b5-7bcb61d544d8.png)

**Comment by javisantana** [comment]
cc @MarkVillacampa

**Comment by MarkVillacampa** [comment]
Interestingly, this only seems to happen in tables with 2 columns, and only if the 2nd column title is empty:

This fails:
```csv
t1,
t1,t2
```

This works fine:
```
,t2
t1,t2
```

**Comment by iriberri** [comment]
Thanks for the info @MarkVillacampa 💞.

I took a quick look and it seems to be an issue of Ogr2Ogr.

We go through two potential manipulations to the CSV to get a Postgres table: the CSV Normalizer and ogr2ogr.

I've checked the CSV normalizer output and it's correctly recognising the columns:

````
(byebug) columns.first
["t1", nil]
(byebug) columns.first.length
2
```

The output CSV for the CSV normalizer is exactly the same as I'm importing, so there are no edits performed here (encoding and delimiters are good and the table is not single column).

But the table that Ogr2ogr is returning as an output has just one column. See examples below with (our) Ogr2ogr versions 2.0 and 2.1:

````
 ogc_fid | t1 
---------+----
       1 | t1
(1 row)
````

I would need to review if this behaviour could be provoked by any option that we are passing to Ogr2ogr, although at first sight I think it's an internal issue of the library.

**Comment by javisantana** [comment]
i'd consider it minor, too many changes to fix a minor issue

**Comment by mejine** [comment]
if this behaviour could be provoked by any option that we are passing to Ogr2ogr, although at first sight I think it's ? the CSV normalizer is exactly the same as I'm importing, so there are no edits performed here (encoding and delimiters are good and the table is not single column).

But the table that Ogr2ogr is returning as an output has just one column. See examples below with (our) Ogr2ogr versions 2.0 and 2.1,,  if this behaviour could be provoked by any option that we are passing to Ogr2ogr, although at first sight I think it's an internal issue of the library.??

**Comment by iriberri** [comment]
I'll be reporting this in the GDAL tracker whenever I can, because their ticketing system crashes for most browsers. I also have this one pending: https://github.com/CartoDB/cartodb/issues/7196 so hopefully we can eventually upgrade the ogr2ogr version when the bugs are resolved and we can close without further work ;-).
