### ISSUE TITLE
[MAP] Searching doesn't center the map on the resulting point.

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#7498]
open a map, search for "San Francisco". It gets centered way west from SF.

Minor thing.

**Comment by xavijam** [comment]
This is the result from Here service, and we take the bounding box that it returns. In any case, if there is a bug, it should be placed in CartoDB.js.

**Comment by xavijam** [comment]
Btw, if you try with `San Francisco city`, it is centered in the bay area.
