### ISSUE TITLE
[ANALYSIS] Area of Influence numeric inputs parameters improvement

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#7501]
edit: updated numbers based on new numbers given in #8166

**By Distance (buffer)**
~~-> m: min: 10, max: 1500, step: 1~~
~~-> km&mi: min: 1, max: 5, step: 0.5~~

new values:
- m (10-1000)
- km (0.5-100)
- mi (0.5-100)

**By Time (trade-area)**
-> walking: min: 60s, max: 3600, step: 1
-> driving: min: 60s, max: 14400, step: 10

On the future we should think how to change the unit when reaching high values

**Comment by viddo** [comment]
Not "easy" as in "trivial", since the backbone forms we're using doesn't easily allow to change the schema (and its validators/min/max restrictions) dynamically, whoever will work on this need to look into this.

**Comment by saleiva** [comment]
prioritize since this is getting important with the demos

**Comment by viddo** [comment]
ok, I've [bumped it up the pending list](https://github.com/CartoDB/cartodb#boards?repos=4909355,4871551,47708079&milestone=Vamosnenos%20-%20editor%203-2016-07-14&assignee=viddo)

**Comment by viddo** [comment]
From #8870 by @AbelVM:

> Allow negative values for buffering (areas of influence).
In some cases you need that kind of analysis. v.G.: find the people living close to the coast

@saleiva, @rochoa would this work? What should be the range then?

**Comment by saleiva** [comment]
I'd not add that for the time being, We might want to add a separate analysis
for that :)

On Jul 14 2016, at 4:00 pm, Nicklas Gummesson &lt;notifications@github.com&gt;
wrote:  

> From [#8870](https://github.com/CartoDB/cartodb/issues/8870) by
[@AbelVM](https://github.com/AbelVM):

>

>> Allow negative values for buffering (areas of influence).  
>  In some cases you need that kind of analysis. v.G.: find the people living
close to the coast

>

> [@saleiva](https://github.com/saleiva), [@rochoa](https://github.com/rochoa)
would this work? What should be the range then?

>

> —  
> You are receiving this because you were mentioned.  
> Reply to this email directly, [view it on
GitHub](https://github.com/CartoDB/cartodb/issues/7501#issuecomment-232673902),
or [mute the
thread](https://github.com/notifications/unsubscribe/AAIENWcoC8AsBltor3gFSAfqi4xUrNNdks5qVkESgaJpZM4Il0Nq).![](https://github.com/notifications/beacon/AAIENW34yvjfyrzl0Ssdz4GQ2L7wAB0bks5qVkESgaJpZM4Il0Nq.gif)
