### ISSUE TITLE
[ANALYSIS] Intact & Dissolve should be also present when doing a buffer and not only an area of influence

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#7502]
Attaching screenshot. That boundaries options should also appear when doing by distance and not only by time

![screen shot 2016-05-24 at 21 03 05](https://cloud.githubusercontent.com/assets/132149/15516399/f4bf3e7a-21f2-11e6-98b8-2f4ce9ef4410.png)

cc/ @xavijam

**Comment by viddo** [comment]
[By distance option does not support those values atm](https://github.com/CartoDB/camshaft/blob/master/reference/versions/0.7.0/reference.json#L27-L36), so would have to be changed on the camshaft reference and the maps API first, would this be doable @rochoa ?

**Comment by rochoa** [comment]
It should be changed in camshaft.

**Comment by javisantana** [comment]
I don't get the "by" when pick "distance"


![screen shot 2016-05-25 at 7 34 51 pm](https://cloud.githubusercontent.com/assets/30147/15550035/d34e719e-22af-11e6-8949-6e331e25a464.png)


Which opens a different question. How do we differentiate between linear and routing distance (since the buffer is going to disappear)?  cc @saleiva

**Comment by javisantana** [comment]
forget about it

**Comment by viddo** [comment]
Seemed easy enough to implement (just adding the field definitions basically) but notices some issues related to this:

1. According to the [camshaft reference v0.10.0 buffer type should support `dissolved` as an _optional_ param](https://github.com/CartoDB/camshaft/blob/master/reference/versions/0.10.0/reference.json#L44-L51), but when its set it actually _implicitly requires_ the `isolines` param (also indicated as _optional_) to also be present (the maps API throws _Dissolved mode requires a number > 1 for "isolines" param_). 
These restrictions are not captured by the reference, so would have to implement custom validation logic to avoid the faulty/inconsistent state then. cc @rochoa 
1. Furthermore, being _optional_ params, shouldn't the UI allow to deselect/reset these values?

How do you want to proceed?

**Comment by rochoa** [comment]
I make it that way because for me it didn't make that much sense to `dissolve` when there are no isolines. For now I will remove that restriction.

Have in mind this could happen: having an optional param depending on other optional param. In the future we can do something like:

```
"dissolved": {
  "type": "boolean",
  "optional": true,
  "requires": ["isolines"]
}
```

**Comment by viddo** [comment]
Yeah, I figured but wasn't sure we wanted to complicate the reference more right now. Anyway, I think the 2nd point should be attended either way, so I await a reply on that before doing anything. 😘

**Comment by rochoa** [comment]
BTW https://github.com/CartoDB/camshaft/pull/46 just got merged, next release will remove the issue with _Dissolved mode requires a number > 1 for "isolines" param_.
