### ISSUE TITLE
Visual fixes on new infowindows

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#7519]
- Font seems too small in the click infowindow compared to the hover one.
- Loading state on click infowindow is wrong.

**Comment by matallo** [comment]
I added the toggle from the widgets, must be adapted for the description

![screen shot 2016-05-27 at 09 47 06](https://cloud.githubusercontent.com/assets/36676/15601504/036b55a4-23f0-11e6-9ac7-47f1930fe1f9.png)

**Comment by matallo** [comment]
BOOM
