### ISSUE TITLE
geojson tiles giving errors when trying to see a map in vectors

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#7520]
https://team.cartodb.com/u/saleiva/editor/07ae2e5a-22a3-11e6-a0cb-0e674067d321/embed?vector=true doesn't work but https://team.cartodb.com/u/saleiva/editor/07ae2e5a-22a3-11e6-a0cb-0e674067d321/embed works like a charm!

**Comment by rochoa** [comment]
Associated named map is not well formed, aggregation column is set to null in some cases, for instance: 
```js
"...": {
            "options": {
                "aggregationColumn": null,
                "column": "exp_job_loss_fraction",
                "operation": "avg",
                "prefix": "",
                "schema": {},
                "suffix": "",
                "sync_on_bbox_change": true,
                "sync_on_data_change": true
            },
            "source": {
                "id": "a0"
            },
            "type": "formula"
        }
```

**Comment by rochoa** [comment]
This was fixed as per https://github.com/CartoDB/Windshaft-cartodb/issues/476.
