### ISSUE TITLE
[WIDGETS] Colors by value are being recalculated when filtering an histogram but we said no

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#7521]
We agreed to only recalculate the ranges and colors when clicking on zoom, or changing the zoomed area but it's recalculating always right now.

**Comment by javisantana** [comment]
could you provide steps?

**Comment by saleiva** [comment]
Go to https://team.cartodb.com/u/saleiva/editor/07ae2e5a-22a3-11e6-a0cb-0e674067d321/embed for example, filter the histogram, take a look at the points.
