### ISSUE TITLE
[WIDGETS] Finish styling of add widget modal

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#7522]

**Comment by piensaenpixel** [comment]
@nobuti one small thing, if the select only have one option, we should avoid the dropdown, and should has the class "is-disabled", is it possible? Then branch is  7522-fix_modal_window
![Uploading image.png…]()

**Comment by nobuti** [comment]
@piensaenpixel sure thing!

**Comment by nobuti** [comment]
@piensaenpixel done!
