### ISSUE TITLE
[analysis] use case multiple fail

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#7523]
The analysis is: "look for metro stops at less than 1km than the L1"

steps:

1) load this dataset https://rambo-test.cartodb.com/tables/paradas_metro_madrid/public/map 
2) add a category widget 
3) add an analysis (trade areas), 1km distance
4) add a point in polygin analysis (input source the metro stops dataset)

The editor enters in a infinite loop doing map instanciations

Expected: it should show in the map stops at less than 1km from the filtered line in the widget

cc @xavijam @rochoa @viddo

**Comment by viddo** [comment]
Thx for the clear steps 👍 

The loop is solely due to internals of cartodb.js (nothing from the editor that provokes it), so created https://github.com/CartoDB/cartodb.js/issues/1283 to continue investigating it there.

**Comment by viddo** [comment]
…once that's fixed we should just need to update the deps to close this issue

**Comment by alonsogarciapablo** [comment]
Taking a look at this!

**Comment by alonsogarciapablo** [comment]
This should be fixed by https://github.com/CartoDB/Windshaft-cartodb/pull/477. Thanks @rochoa!

There's still an issue open in CartoDB.js to prevent infinite map instantiation loops from occurring in the future. I'll get to it sometime soon.
