### ISSUE TITLE
[Suggestion] Improve text in organization invitation mail

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#7524]
The current file is here: https://github.com/CartoDB/cartodb/blob/ebfb0e62bfdb6bd941408b4d2f0826b3195318fb/app/views/user_mailer/new_organization_user.html.erb

**Subject**: 

> You have been invited to **CartoDB organization 'team'**(a)

**Content**:

> You have been invited to CartoDB
> 
> If you have not received your password, **contact your administrator at cartofante**(b).
> 
> You have been invited to CartoDB **as part of the organization**(c). Please login to your dashboard with your organization username (carlatesting) and the password provided by your administrator.
> 
> Go to your dashboard

(b) Would it be better to use the email of the administrator? How would someone contact a CartoDB user?

(c) Sounds a bit incomplete, similar case in (a) :-)

**Comment by iriberri** [comment]
cc @MariaCheca @juanignaciosl

**Comment by MariaCheca** [comment]
Thanks for the suggestion @iriberri! Perhaps we should ask @brittanymicek to help improving that email content :)

**Comment by brittanymicek** [comment]
happy to help! @iriberri @MariaCheca

**Comment by ramiroaznar** [comment]
We can close this. This is now managed by CS. Big hugs!
