### ISSUE TITLE
Custom select doesn't toggle list if we click on the selected item.

### ISSUE THREAD

**Issue by nobuti** [CartoDB/cartodb#7526]
Steps to reproduce:
- Create a custom select with one element
- Select the element.
- Try to select the element again. 💥

**Comment by ramiroaznar** [comment]
Ey @nobuti can you elaborate more? Are you talking about category widgets? Is this still happening?

**Comment by nobuti** [comment]
It's a minor issue, from the ux point of view, it's confusing that clicking in one item doesn't close the dropdown. I feel that always the user clicks on an item, the dropdown should close.

**Comment by ramiroaznar** [comment]
![custom-select](https://user-images.githubusercontent.com/5215798/33430038-5cb201f2-d5cf-11e7-9b50-176eaed94098.gif)

**Comment by Jesus89** [comment]
IMO clicking at the same value should not close the popup because you are not doing anything (maybe a fail click). Maybe @arianaescobar can share her opinion here :smile: 

Btw, the histogram issue should be fixed after all.

**Comment by arianaescobar** [comment]
I don't have a very strong opinion here, but if I had to choose, I'd close the dropdown too.

**Comment by alrocar** [comment]
Stale issue. Closing 👋
