### ISSUE TITLE
[Fill component] Add border & checkered background to the chosen color 

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#7541]
If a user picks a high opacity, the input element shows a white space. This could be fixed adding a checkered background and a border around the color:

![screen shot 2016-05-27 at 10 43 46](https://cloud.githubusercontent.com/assets/4933/15602880/f19cc9c2-23f7-11e6-96ee-9a2d3e84b152.png)

![screen shot 2016-05-27 at 10 45 48](https://cloud.githubusercontent.com/assets/4933/15602885/f83a164a-23f7-11e6-8e83-67f84e15f3f8.png)

**Comment by piensaenpixel** [comment]
fixed ! :)
