### ISSUE TITLE
Duplicate .carto map is not referencing duplicate datasets

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#7553]
@juanignaciosl cc @zingbot 

S/B 9007900

Hi, wondering how we should handle duplicate maps and datasets when a user exports .carto and imports it back to same account? Datasets are re-importing but duplicate map's query is not referencing duplicated datasets. 

## Context
If you export .carto from a map with SQL query applied in it's layer, then drag/drop it back into your account, it's datasets are duplicated - but the SQL query in duplicate map layer queries the original dataset instead of dupe dataset.

## Process
1. In one of your account maps apply a SQL query to one of its layers.
2. Click Edit > Export Map, then OK Export button 
3. Drag the .carto file you just exported back to your account's Maps page & drop

## Result
1. The datasets used in the exported map are re-imported when the .carto file is & get version number appended automatically
![export_reimport_datasets](https://cloud.githubusercontent.com/assets/1779444/15618985/310414b8-241f-11e6-8013-dc1c76b52787.png)

2. The original map .carto was exported from has query like this:
![export_test_sql](https://cloud.githubusercontent.com/assets/1779444/15618996/4867a836-241f-11e6-90a0-0bd38d43ba4e.png)

Dupe map has this:
![export_test_dupe_sql](https://cloud.githubusercontent.com/assets/1779444/15619018/71ce5eea-241f-11e6-9dab-b6e29b6389b5.png)

**Comment by juanignaciosl** [comment]
Duplicated: CartoDB/cartodb#7258.
