### ISSUE TITLE
Named maps dataviews with invalid options

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb#7555]
Most of the dataviews created in named maps contain non-required options and sometimes invalid options. Example from https://github.com/CartoDB/cartodb/issues/7520:

```
"ebc0653f-3581-469c-8b31-c969e440a865": {
            "options": {
                "aggregationColumn": null,
                "column": "exp_job_loss_fraction",
                "operation": "avg",
                "prefix": "",
                "schema": {},
                "suffix": "",
                "sync_on_bbox_change": true,
                "sync_on_data_change": true
            },
            "source": {
                "id": "a0"
            },
            "type": "formula"
        }
```

`aggregationColumn` exists as an option but doesn't apply to a `formula` type, just for `aggregation` type.  And `prefix`, `schema`, `suffix`, `sync_on_bbox_change`, and `sync_on_data_change` have nothing to do with Maps API, probaby they are frontend related so we should not send them in the named maps.

cc @xavijam

**Comment by xavijam** [comment]
Yeah, after checking it, in the private editor we are sending them correctly to the Maps API (already filtered by cartodb.js), but in public embeds we should do the same from the backend. That will require work from you @juanignaciosl or @javitonino, as you wish.

**Comment by xavijam** [comment]
BTW, for further reference, what we send to Maps API for each dataview:

- Formula: https://github.com/CartoDB/cartodb.js/blob/v4/src/dataviews/formula-dataview-model.js#L25
- Category: https://github.com/CartoDB/cartodb.js/blob/v4/src/dataviews/category-dataview-model.js#L261
- Histogram: https://github.com/CartoDB/cartodb.js/blob/v4/src/dataviews/histogram-dataview-model.js#L173

**Comment by xavijam** [comment]
And also, after doing this one, please check that https://github.com/CartoDB/cartodb/issues/7520, and if it is ok, close it 💃 .

**Comment by gfiorav** [comment]
New named maps template generation in backend fix this. Can't give an estimate but soon. Follow #7508

**Comment by xavijam** [comment]
@gfiorav how come? did you follow what we have done in CartoDB.js?

**Comment by gfiorav** [comment]
@xavijam nope, I followed the windshaft docs

**Comment by xavijam** [comment]
How good you are man! 👍

**Comment by juanignaciosl** [comment]
@gfiorav don't you think that this should be fixed in old code as well?

PS: I **_hate_** multiple assignment feature. @guido, will you take care of this, also for old code? Remove other assignments if you will, please.

**Comment by gfiorav** [comment]
@juanignaciosl there will be no old code. I'm redoing it from scratch.

**Comment by juanignaciosl** [comment]
Yes, but I think that old `NamedMap` class won't be deprecated yet, isn't it?

**Comment by gfiorav** [comment]
@juanignaciosl I really don't see why not. I've rewritten the connectors of both viz model to use the new named maps and so far so good. If something big comes up, I'll keep em, but right now it doesn't seem necessary 😁

**Comment by juanignaciosl** [comment]
Ok, assigning this to you then. From now on let's try to keep single assignments.

**Comment by gfiorav** [comment]
This should be closed via https://github.com/CartoDB/cartodb/pull/7566
