### ISSUE TITLE
`Carto::Organization.where(name:'demo').first.destroy` does not remove dependencies in cascade

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#7576]
The following command, removes an organization from the `cartodb_production` database, with all its dependencies: 
* users
* organizations
* user_datasets

`::Organization[name: 'org_name'].destroy_cascade`

However, the equivalent command in the new model does not remove the dependencies or the org database itself, only the organization entry from `cartodb_production.organizations`

`Carto::Organization.where(name:'org2').first.destroy` 

```
cartodb_production=# select u.username,o.name,u.database_name from users u left join organizations o on o.id = u.organization_id;
  username  | name |                    database_name                     
------------+------+------------------------------------------------------
 testimport | demo | cartodb_user_961e2567-be8e-4135-bd10-df6c89d82a36_db
 demo-admin | demo | cartodb_user_961e2567-be8e-4135-bd10-df6c89d82a36_db
 apiuser    | demo | cartodb_user_961e2567-be8e-4135-bd10-df6c89d82a36_db
 org2-admin |      | cartodb_user_dd1eba58-480a-433b-8053-e8a24e0b2b18_db
 org2-user  |      | cartodb_user_dd1eba58-480a-433b-8053-e8a24e0b2b18_db
``` 

`org2-admin` and `org2-user` should have been deleted along with the `org2` organization

This was tested in an On-premise v1.2.1 instance.

cc/ @gfiorav

**Comment by juanignaciosl** [comment]
@ernesmb this is a known limitation. As a rule of thumb, you shouldn't use the new models for write operations.

**Comment by ernesmb** [comment]
Oh, thanks for the clarification @juanignaciosl 

I was reporting just in case this was not the expected behaviour. I guess this could be closed now :)
