### ISSUE TITLE
Creating a map with mixed datasets sharing alternatives generates wrong sql

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#7583]
1. Share a user A dataset X with user B.
2. Create with user B a map with previous X shared dataset and a dataset B owns.
3. Both layer sql are rewritten to `select * from A.table`

cc @javitonino @gfiorav @xavijam

**Comment by juanignaciosl** [comment]
Setting assignee because of worklog update ;-)

**Comment by javitonino** [comment]
Thanks, totally forgot.
