### ISSUE TITLE
[Wizards migration] any style migration is "enabling" labels

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#7594]
Looks like `labels -> enabled` is set as true always, no matter if labels was enabled in the old editor or not.

**Comment by juanignaciosl** [comment]
@xavijam wizard migration specification seems wrong then. [It says](https://github.com/CartoDB/cartodb/wiki/Wizard-to-style-migration#labels) "if any text-* property is found there should be a labels entry in the style, the mapping is (old properties in the comment)"

Nevertheless, this is an example of wizard properties without labels yet:

```{"type"=>"polygon",
 "properties"=>
  {"marker-width"=>11,
   "marker-fill"=>"#FF6600",
   "marker-opacity"=>0.9,
   "marker-allow-overlap"=>true,
   "marker-placement"=>"point",
   "marker-type"=>"ellipse",
   "marker-line-width"=>1,
   "marker-line-color"=>"#FFF",
   "marker-line-opacity"=>1,
   "marker-comp-op"=>"none",
   "text-name"=>"None",
   "text-face-name"=>"DejaVu Sans Book",
   "text-size"=>10,
   "text-fill"=>"#000",
   "text-halo-fill"=>"#FFF",
   "text-halo-radius"=>1,
   "text-dy"=>-11,
   "text-allow-overlap"=>true,
   "text-placement-type"=>"simple",
   "text-label-position-tolerance"=>10,
   "text-placement"=>"point",
   "zoom"=>7,
   "geometry_type"=>"point"}}
```

What can I take to decide enabling it or not?

**Comment by xavijam** [comment]
If `text-name` is "none", labels -> enabled should be false.

**Comment by juanignaciosl** [comment]
Always `None`, capital `N`, hopefully

**Comment by xavijam** [comment]
😂
