### ISSUE TITLE
Named map tile URL {layer} does not filter layer

### ISSUE THREAD

**Issue by jaakla** [CartoDB/cartodb#7595]
Layer = 0 - shows base map, ok:
![ok](https://nutiteq.cartodb.com/api/v1/map/named/tpl_8336e3ee_267e_11e6_8410_0e787de82d45/0/16/39130/26489.png)

Layer = 1, or 2, or 3 - shows "all layers", just as next case. Expected to show only specified layer id according to [doc](https://docs.cartodb.com/cartodb-platform/maps-api/named-maps/#fetching-xyz-tiles-for-named-maps), so **not ok**:
![nok](https://nutiteq.cartodb.com/api/v1/map/named/tpl_8336e3ee_267e_11e6_8410_0e787de82d45/1/16/39130/26489.png)

Layer = all - ok:
![ok](https://nutiteq.cartodb.com/api/v1/map/named/tpl_8336e3ee_267e_11e6_8410_0e787de82d45/all/16/39130/26489.png)

Sample named map ID: tpl_8336e3ee_267e_11e6_8410_0e787de82d45

**Comment by rochoa** [comment]
From: https://github.com/CartoDB/Windshaft-cartodb/blob/5eda4888edf665eeb060647ade2c734f55cbf914/docs/anonymous_maps.md#blending-and-layer-selection

> Once a Mapnik layer is selected, all Mapnik layers will get blended. As this may change in the future it is recommended to always select all Mapnik layers if you want to select at least one so you will get a consistent behavior in the future.

**Comment by saleiva** [comment]
hey, closing this for the time being.
