### ISSUE TITLE
Category widget not filtering on source layer

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#7605]
STR:

1. create a layer A of lines (e.g. paradas de metro madrid)
1. add category widget to source layer A's source (a0)
1. add an buffer analysis for layer A (a1)
1. add an point-in-polygon analysis for layer A (a2)
1. filter by a category, e.g. line 1/blue

Expected result:
- only rendered relevant data around the selected line

Actual result: 
- just re-rendering

Having a quick look the dataview sent to the tiler is using _a2_ instead of the expected a0… need to investigate further.

cc @javisantana feel free to update the desc here if I wrote something wrong, will attend this in a little while…

**Comment by javisantana** [comment]
to complete the description:

```
widgetDefinitionsCollection.at(0).attributes.source_id
"a0"
```

but the information sent to the maps api is:

```
"dataviews":{
"55abd3ee-60ce-403c-8a78-e7c517593e61": {
"type":"aggregation",
"source": {"id":"a2"},
"options":{...}
}}
```

**Comment by alonsogarciapablo** [comment]
FYI: this seems to be working on the embed. It seems that the dataview in CartoDB.js doesn't have a `sourceId` attribute, so it's using the id of the layer as a fallback.

**Comment by alonsogarciapablo** [comment]
Closed in https://github.com/CartoDB/cartodb.js/pull/1294
