### ISSUE TITLE
Dropping a layer causes layers to shake a bit

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#7612]
This is not vey cool and I'm not sure why it's happening:

![layers-shaking](https://cloud.githubusercontent.com/assets/390398/15713965/f4b704e0-2818-11e6-9787-09990d4e159c.gif)

@javierarce do you have any idea of why this can be hapenning? would you please take a look? Not very important, but would be nice to fix it...

cc: @xavijam

**Comment by xavijam** [comment]
Adding to editor 3 milestone, super minor ;).
