### ISSUE TITLE
Simple wizard migration is not setting fill size

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#7627]
### STR

1. Create a map of points (1 layer).
2. It will redirect you to the map, and simple wizard will set by default (our orange color will appear).
3. Go to new editor.
4. Being there, click over the data layer and go to the `style` tab.
5. Check that fill size is not present and it should be there.

**Comment by juanignaciosl** [comment]
It's not at the specs:

```ruby
{
 type: 'simple'
 properties: {
   fill: {
      color: {
        fixed: '...', // marker-fill or polygon-fill
        opacity: 1
      }
   }
 }
}
```

I guess that I should take `fill.size` from `marker-width`, isn't it?

**Comment by xavijam** [comment]
yes, sorry to not be specified in the specs :(.

**Comment by juanignaciosl** [comment]
@xavijam not a problem, I'm not blaming, I just wanted to know why it isn't done and what should I do :-) Thanks!
