### ISSUE TITLE
'Share options' button isn't working on the current editor 

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#7634]
I was doing smoke tests for On-Premises Omnibus 1.3.0 and found that the 'Share options' on the editor is not working. When I click on it, nothing happens. 

![screen shot 2016-06-02 at 18 05 23](https://cloud.githubusercontent.com/assets/16247628/15752266/a4db9a8c-28ed-11e6-878f-148bd9c8adaf.png)

Buti, apparently you're the man for the job 😅

**Comment by xavijam** [comment]
In the private editor it doesn't work, it is just fake. Try in the embed part, it should work. It is not a bug, it is a feature (famous last words).

**Comment by arianaescobar** [comment]
Oh ok! I didn't know that :)  
Nevermind then!
