### ISSUE TITLE
Generate analysis options by camshaft reference

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#7635]
The [latest version of the camshaft reference](https://github.com/CartoDB/camshaft/blob/master/reference/versions/0.10.0/reference.json) is good enough to generate "automatic" (parameterized) analysis options, 

edit: for _development/testing_ purposes, i.e. not end-users, so changed scope below:

There's a few things that needs to be done for it to work though:

**Scope:**
- Add config flag to generate analysis from camshaft reference definitions instead of [default analysis options](https://github.com/CartoDB/cartodb/blob/3fb48ec8222b1d031a85fc565e0d56f1915559a2/lib/assets/javascripts/cartodb3/components/modals/add-analysis/default-analysis-options.js)
- The defaults should be treated as overrides if flag is enabled
- Generate form from analysis definition's params

@andrewxhill @javisantana opinions? anything I missed or overlooked?
cc @rochoa anything else I should consider?

**Comment by javisantana** [comment]
I think we don't know enough to know if we can roll out autogenerated analysis. I'd do this for development in a quick'n'dirty way but not something for production

**Comment by viddo** [comment]
Fair enough, I'll update the scope to reflect this (in a bit) 👍
