### ISSUE TITLE
"Request to Maps API failed: Missing required param "query"" when opening a .carto imported map with anlyses

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#7637]
_edit: changed STR since the original err was fixed previously  /@viddo_

**STR**

- all the components are updated as per _master_, Windshaft point to https://github.com/CartoDB/Windshaft-cartodb/commit/050d33ff140aaf9b1b4975f0ac0bbc650dd04a4a
- imported paradas_metro_madrid 
[paradas_metro_madrid (on 2016-06-02 at 15.26.52).carto.zip](https://github.com/CartoDB/cartodb/files/296105/paradas_metro_madrid.on.2016-06-02.at.15.26.52.carto.zip)
- open resulting map

**expected behavior**

- perform analysis
- working

**actual behavior**

- `common_editor3.js:49060 Request to Maps API failed: Missing required param "query"`

**Comment by viddo** [comment]
@alonsogarciapablo related to https://github.com/CartoDB/cartodb.js/issues/1283 ?

**Comment by viddo** [comment]
Windshaft+SQL API up-to-date, so not same error as the [previous one](https://github.com/CartoDB/cartodb/issues/7523)

**Comment by viddo** [comment]
I can't reproduce it, but get another error instead: `Request to Maps API failed: Missing required param "query"` on the editor. And if I open the embed I get yet another error: `Request to Maps API failed: column "fid" does not exist`. @rochoa related to what we talked about last night? Have Windshaft up-to-date as of this morning.

**Comment by viddo** [comment]
> Windshaft+SQL API up-to-date, so not same error as the previous one #7523 ([analysis] use case multiple fail )

^^^ wasn't completely true, was missing a `make clean all` to have the latest dependencies installed. So that resolves the infinite loop, but with latest changes https://github.com/CartoDB/Windshaft-cartodb/commit/050d33ff140aaf9b1b4975f0ac0bbc650dd04a4a there is another error instead: `common_editor3.js:49060 Request to Maps API failed: Missing required param "query"`

**Comment by matallo** [comment]
it fails because there is an analysis without query praram, indeed

![screen shot 2016-06-09 at 18 31 01](https://cloud.githubusercontent.com/assets/36676/15937768/83123414-2e70-11e6-9dfc-e1864db0fb58.png)

as you @javisantana are reproducing the analyses, can you replicate this again?it looks like the following paradas de metro .carto file is borked

[paradas_metro_madrid (on 2016-06-02 at 15.26.52).carto.zip](https://github.com/CartoDB/cartodb/files/307407/paradas_metro_madrid.on.2016-06-02.at.15.26.52.carto.zip)

thanks!

**Comment by xavijam** [comment]
map already working, but there is a JS error and I've just fixed so 💃
