### ISSUE TITLE
infowindows: create "none" template

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#7644]
instead of disabling all the fields then not showing the popup on click, we'll still need to show a template BUT one telling "no fields are selected > go activate them" similar to

![screen shot 2016-06-03 at 10 39 40](https://cloud.githubusercontent.com/assets/36676/15773596/15586e4a-2978-11e6-8d2e-602243be1465.png)

I expect to tackle this so not many changes are needed in cartodb.js or migrations, by the next approach:

- if no template is sent and no fields are selected, popup won't appear
- if a template is passed, still no fields are selected, popup with the template will appear

this would involve making some changes in cartodb.js, but still worth it to prevent destructive migrations, also this covers the default no fields, `""` template case

however, I don't know how can we solve this _just_ for the editor, what to do outside when the template is set?

/cc @piensaenpixel @urbanphes @alonsogarciapablo

**Comment by urbanphes** [comment]
We need to emphasize the message, and opted for the warning color in the popup
![image](https://cloud.githubusercontent.com/assets/14546701/15818329/1c4d998e-2bdd-11e6-9b55-3121660235af.png)

**Comment by matallo** [comment]
this is already implemented, reassigning to @piensaenpixel for the styles
