### ISSUE TITLE
[Fill component] add selected state for the color ramps.

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#7650]
- [X] Add selected state for the color ramps
- [x] Implement designed state 

![screen shot 2016-06-03 at 13 19 31](https://cloud.githubusercontent.com/assets/4933/15829213/0f1a2ed6-2c13-11e6-9f78-e472a21e18c5.png)

**Comment by javierarce** [comment]
@piensaenpixel: asigned to you so you can do your magic.

**Comment by piensaenpixel** [comment]
![image](https://cloud.githubusercontent.com/assets/1214201/15852223/b02bea8e-2ca0-11e6-91ac-42d324b49190.png)
ready @javierarce take a look because selected doesnt change :(

**Comment by piensaenpixel** [comment]
also tests are changed
