### ISSUE TITLE
When a layer is set as animated (torque), we should add the time-series widget or other player...

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#7656]
There would be two possibilities:
1. Add the widget automatically if there isn't any time-series.
2. In case there is a time-series widget, we should change that widget and set the new layer/node + the column.

cc @alonsogarciapablo @viddo @javisantana

**Comment by javisantana** [comment]
I think this is done, right?

**Comment by matallo** [comment]
this is not happening anymore, closing then!
