### ISSUE TITLE
duplicate map of a map with analyses fails

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#7657]
**str**

- import a map with analyses (classic paradas de metro)
- open map
- duplicate map
- open duplicate map in builder

**expected behaviour**

- panels and map load

**actual behaviour**

- panels and map fail, find attached the developer tools trace

```
editor3.js:21147 Uncaught Error: layerAnalysisDefinitionNodeModel is required
common_editor3.js:62620 Uncaught TypeError: Cannot read property 'toJSON' of undefined
```

**Comment by viddo** [comment]
Exact same STR?

**Comment by gfiorav** [comment]
yes, that's why I didn't specify a new one :D

**Comment by javitonino** [comment]
Analyses and widgets don't get duplicated on the backend, so no wonder it doesn't work. On it.

**Comment by viddo** [comment]
Had not gotten to investigate this yet, thx for being so proactive, @javitonino ! 💋
