### ISSUE TITLE
Importing large CSV file results in erroneous NULL values

### ISSUE THREAD

**Issue by clhenrick** [CartoDB/cartodb#766]
I recently imported a CSV file of twitter data I collected that contains over 120,000 rows. When I inspected this data in CartoDB's table view I find many NULL values for rows towards the bottom of the table. I do not have this problem when viewing the CSV in Open Office or QGIS. [Here](https://www.dropbox.com/s/br11pry37ib9tsn/tweets.csv?dl=0) is a link to the CSV file, and [Here](https://chenrick.cartodb.com/tables/tweets/) is where the imported table is in my account.

Using Chrome, Mac OS X 10.9.4

**Comment by iriberri** [comment]
Not reproducible anymore, neither the CSV or the CartoDB table are live anymore. Chris feel free to reopen if you have some clues that we could use. We have been working in some improvements for CSV lately.
