### ISSUE TITLE
French Character Import of SHP files does not load accent characters correctly.

### ISSUE THREAD

**Issue by StephenOTT** [CartoDB/cartodb#7665]
Download the following ShapeFile: http://donnees.ville.montreal.qc.ca/dataset/polygones-arrondissements/resource/62f7ce10-36ce-4bbd-b419-8f0a10d3b280

Load it into CartoDB through the UI with Connect to Dataset.

When it loads and you look at the Table of Data you see data such as this:

![screen shot 2016-06-04 at 6 22 47 pm](https://cloud.githubusercontent.com/assets/1994838/15802458/5bdf6b8e-2a81-11e6-9a39-5c89b97f1a00.png)
![screen shot 2016-06-04 at 6 22 44 pm](https://cloud.githubusercontent.com/assets/1994838/15802460/5bef536e-2a81-11e6-9c74-b29c99034ab5.png)
![screen shot 2016-06-04 at 6 22 40 pm](https://cloud.githubusercontent.com/assets/1994838/15802461/5bef4fc2-2a81-11e6-9127-de924200c393.png)
![screen shot 2016-06-04 at 6 22 36 pm](https://cloud.githubusercontent.com/assets/1994838/15802463/5bf1e674-2a81-11e6-954e-5160a7bf3907.png)
![screen shot 2016-06-04 at 6 22 33 pm](https://cloud.githubusercontent.com/assets/1994838/15802462/5bf0a12e-2a81-11e6-86d0-b126ba1ff6af.png)
![screen shot 2016-06-04 at 6 22 29 pm](https://cloud.githubusercontent.com/assets/1994838/15802459/5bef24a2-2a81-11e6-9777-a33ad19dce95.png)

But if you retype the data manually the UI accepts and displays the characters.

**Comment by matallo** [comment]
when downloading this from the kml resource, exporting to shp, and re-importing as shp this is not happening anymore, which leads me to think this has something to do with the encoding

closing then, feel free to reopen if you find this happening with other sources

thanks!
