### ISSUE TITLE
Category wizard migration is not working properly

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#7668]
#### STR

- Easy as create a map of points (for example, NY metro stops).
- Apply a category wizard.
- Go to new editor and check that style is not working properly.

![screen shot 2016-06-06 at 10 12 44](https://cloud.githubusercontent.com/assets/132146/15815727/44059836-2bcf-11e6-8d4f-a829f9799679.png)

After a deep look into the transformation, this is what the migration returns:

<img width="353" alt="screen shot 2016-06-06 at 10 08 18" src="https://cloud.githubusercontent.com/assets/132146/15815663/e5149a48-2bce-11e6-8943-3794cefd1dbe.png">

- Domain is correct 👌 .
- Range is incorrect, it doesn't contain any color, and it should have 10, same size as domain.
- Fixed shouldn't be included.

cc @javierarce

**Comment by juanignaciosl** [comment]
I'm trying to reproduce.

Style is wrong:

![screen shot 2016-06-06 at 12 34 16](https://cloud.githubusercontent.com/assets/932968/15819359/0802a446-2be3-11e6-8779-5cbeffadddb8.png)

But migration looks fine:

![screen shot 2016-06-06 at 12 33 15](https://cloud.githubusercontent.com/assets/932968/15819347/f8fb74aa-2be2-11e6-9984-b2cffe5200a1.png)

**Comment by xavijam** [comment]
@javierarce, could you take a look?

**Comment by juanignaciosl** [comment]
I'll keep trying, because your screenshot is clear: something is wrong _sometimes_ with categories.

**Comment by javierarce** [comment]
I'll have a look too, yes.

**Comment by juanignaciosl** [comment]
@xavijam that screenshot has `quantification`, which is only present in bubble and choropleth, are you sure that you were using categories?

**Comment by xavijam** [comment]
Yes, but I guess I chose Bubbles before Categories... does it help?

**Comment by juanignaciosl** [comment]
It would if wizard properties had a mix of both configurations afterwards, but it doesn't seem the case, I can't reproduce it either with bubbles and categories afterwards.

**Comment by javierarce** [comment]
In my test the range comes with colors, but the number of bins is 11 instead of 10, like in the issue:

![screen shot 2016-06-06 at 14 51 22](https://cloud.githubusercontent.com/assets/4933/15822418/f0cd69a6-2bf5-11e6-97e7-7706c6a91ac7.png)

**Comment by juanignaciosl** [comment]
@javierarce yes, bins is 10 because it's not a count of the colors but the used method. From [wizards migration spec](https://github.com/CartoDB/cartodb/wiki/Wizard-to-style-migration): `bins: 6, // method, '3 buckets', '5 buckets'`

**Comment by juanignaciosl** [comment]
While I was trying to reproduce this I realized there was a problem with stroke. I'll fix it, but I can't reproduce original @xavijam issue (can you now?), and I think that bins should be 10, not 11, @javierarce , but I might be wrong.

**Comment by javierarce** [comment]
> @javierarce yes, bins is 10 because it's not a count of the colors but the used method. From wizards migration spec: bins: 6, // method, '3 buckets', '5 buckets'

Sorry, @juanignaciosl, I don't understand what you mean with "the used method". 

By the way, what's the reason of having a bins param for categories when we already have two arrays with the exact information we want to display?

**Comment by juanignaciosl** [comment]
"method" is the nomenclature used in the [wizard migration spec](https://github.com/CartoDB/cartodb/wiki/Wizard-to-style-migration) for the selection of the bucket number. For choropleth is more visible:

![screen shot 2016-06-07 at 11 09 42](https://cloud.githubusercontent.com/assets/932968/15852151/7082646c-2ca0-11e6-91cb-b7b7f5722b11.png)

For categories it's "hidden", fixed to 10. It looks like it takes 10 and groups remaining under "others". I guess that `bins` parameter can be useful to remember user pick, since grouping can return arrays with a number that is not the same (for example, this "others" extra group, or setting it to 10 but only with 3 categories).

**Comment by javierarce** [comment]
Oh, ok! I'll have a look and see if I'm setting the bin count incorrectly for the categories. Thanks for the explanation!
