### ISSUE TITLE
[Fill component] When the input color list is rendered first, it looks bad

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#7683]
![screen shot 2016-06-06 at 16 00 09](https://cloud.githubusercontent.com/assets/4933/15824486/b96b6c1a-2bff-11e6-9b12-516d799e11fd.png)

**Comment by javierarce** [comment]
@piensaenpixel: can you have a look? If the number should always appear before the color list I could do that instead of fixing the CSS.

**Comment by piensaenpixel** [comment]
always first the value

**Comment by javierarce** [comment]
👌
