### ISSUE TITLE
A new avatar is not properly loaded

### ISSUE THREAD

**Issue by luisbosque** [CartoDB/cartodb#7694]
The asset is correctly uploaded to CartoDB and stored but the new avatar url is not updated in metadata. The new avatar appears in the account page right after the operation has finished but a refresh will show again the old one.

/cc @xavijam @javitonino

**Comment by juanignaciosl** [comment]
@luisbosque it works for me. Did you press "save" afterwards? Changes are not persisted after setting the new avatar unless you press save.

**Comment by luisbosque** [comment]
My bad
