### ISSUE TITLE
Switch vector flag off when new layers are added

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#7695]
From now on `vector` flag will be `true` at the new editor and embed for maps with less than 10k features. That is a potential issue when you add a new layer, since it might have more than 10k features thus compromising tiler.

Needed by #7307.
Backend side ready at #7658 (`7307-send_vector_flag_true_in_the_editor_when_number_of_features_is_less_than_10k` branch).

cc @xavijam

**Comment by xavijam** [comment]
@alonsogarciapablo, could you add this thing in your layer-management epic issue? :)

**Comment by alonsogarciapablo** [comment]
So the idea is to disable `vector` in the builder?

**Comment by xavijam** [comment]
Yep, when a new layer is added, if vector was enabled before.

**Comment by rochoa** [comment]
For now, we are no longer developing anything regarding Tangram or vector rendering in Builder. Feel free to open a new issue if in the feature we come to this again.
