### ISSUE TITLE
[autogeneration] reject filters not working

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#7705]
1) aggregate a filter analysis
2) select a column (with at least two unique values) and reject one of the values

Nothing is renderered but it should render at the non rejected properties.

Not sure if this a UI problem or a backend one

**Comment by viddo** [comment]
It doesn't seem to matter if rejecting one or multiple ones, or nothing, it does't render either way. 

However, if the accept param has a value it works however, e.g. using _"paradas madrid"_ dataset, and accept "L1,L2,L3" and reject "L2" renders the expected points of L1 and L3.

Looking at the requests I think it's related to the query: 
<img width="1204" alt="screen shot 2016-06-17 at 09 06 54" src="https://cloud.githubusercontent.com/assets/978461/16143571/e51bfb74-346d-11e6-9c76-a54da5a3b2e7.png">
Probably it should not add the `IN ($escape_0$$escape_0$)` if there's no accept value(s), right? @rochoa I guess this should be moved to Windshaft?

**Comment by rochoa** [comment]
It adds the `IN ()` if you provide an empty `accept: []` array, as a way to "reject all" without having to send the whole list of categories to reject: https://github.com/CartoDB/Windshaft-cartodb/blob/bff082e5771566497f6bb304512f492341740d28/test/acceptance/widgets/ported/aggregation.js#L165

The client should not send an empty array for accept.

**Comment by viddo** [comment]
Ok, fixed in 2a169c2

**Comment by viddo** [comment]
Although… does it make sense to "reject all" by sending an empty array and at the same time send a list of reject values? Couldn't the server identity that and just use the reject value? Sounds a bit weird to me that the accept-all is also a reject filter.

**Comment by rochoa** [comment]
IIRC this was related to a previous version of DI.js that allowed to select "None" in category widgets. That meant that you had to knew all categories in advance to reject all, which is not a problem when there a few categories but it's a problem when you have 1000 categories. But I don't find it that weird: it's kind of *set theory* applied: if I give you `A={1,2,3}` and `B={3,4,5}` and ask you to give me the intersection of both (`A∩B`) you will get `{3}`, but if, with `C={}`, I ask for the intersection `A∩C` you will get `{}` as there are no members shared among A and C.

**Comment by viddo** [comment]
Fair enough, thx for the rationale 👍
