### ISSUE TITLE
Remove UI write components for viewer users

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#7715]
Remove the followings UI elements for viewer users:

- [X] Onboarding message and new map button.
- [X] New map and new dataset buttons.
- [X] "Data Library" tab (other remains, since a builder user can become a viewer and his datasets are still available).

cc @xavijam

**Comment by xavijam** [comment]
So, only shared datasets and maps, that's it?

**Comment by juanignaciosl** [comment]
Also _liked_.

**Comment by xavijam** [comment]
:+1:

**Comment by juanignaciosl** [comment]
@urbanphes , @saleiva : currently, when a user can't create a new dataset (because he hasn't quota, for example), the button is greyed out and disabled. I guess that's the best choice because he can carry out actions that enable it (delete big datasets, for example). Should those buttons fully dissappear for viewer users, or just keep the buttons disabled?

Same question for "own tabs" (see description).

**Comment by juanignaciosl** [comment]
Update: since a user can be turned into a viewer, map and datasets tabs make sense, I'll only remove data library.

**Comment by juanignaciosl** [comment]
Onboarding capture. Let me know if you want a replacement text instead of just removing it.

![screen shot 2016-06-28 at 18 32 05](https://cloud.githubusercontent.com/assets/932968/16424012/a9ebb720-3d5e-11e6-8a28-879e0d4088aa.png)

**Comment by saleiva** [comment]
hey @urbanphes can you check everything related to this?

2016-06-28 18:33 GMT+02:00 Juan Ignacio Sánchez Lara <
notifications@github.com>:

> Onboarding capture. Let me know if you want a replacement text instead of
> just removing it.
>
> [image: screen shot 2016-06-28 at 18 32 05]
> <https://cloud.githubusercontent.com/assets/932968/16424012/a9ebb720-3d5e-11e6-8a28-879e0d4088aa.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/7715#issuecomment-229105482>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAIENYTq1PIkVl8mOXIZgNjp2YGXWE7Lks5qQUzFgaJpZM4IwAnN>
> .
>



-- 
Sergio Alvarez Leiva

**Comment by juanignaciosl** [comment]
@urbanphes also, maybe a way to tell the user whether he's a viewer or a builder might be interesting.

I expect deploying this tomorrow, if your design suggestions come first I'll do it, otherwise we'll improve later.

**Comment by juanignaciosl** [comment]
For the benefit of mr urbanphes :-)

- [ ] Should the "New Map" and "New Datasets" buttons be _removed_ ? The alternative is _disabling_ it, but since the user can't do anything to enable it I don't like it.
- [ ] Should the "Data Library" option be _removed_? Same argument, same opinion.
- [ ] I've finally decided to keep "Maps" and "Datasets" tabs (the first option at Maps or Datasets sections of the dashboard), because a viewer user can have tables or maps if he was previously a builder (a user can be changed from builder to viewer and viceversa).
- [ ] The onboarding screen had some text about creating a map and a new map button that I've removed (see the screenshot). Let me know if you want to replace the text instead of just removing it.
- [ ] It'd probably be interesting that the user knew somehow that he's a viewer (maybe at his settings page, I don't know).

**Comment by urbanphes** [comment]
1) Yes
2) Yes
3) We re-think this page.
4) I would prefer replace the text.
5) It´s interesting, We’ll think about this module

**Comment by juanignaciosl** [comment]
1. Ok, great.
2. Ok, great.
3. Ok, but we can probably deploy this first approach before, is it ok for you?
4. Ok, can you take care of a suitable text?
5. Ok. Probably not a "module" needed. At least some kind of information about it from the beginning would be nice.
