### ISSUE TITLE
CDB_UserTables() returns deleted tables as existings

### ISSUE THREAD

**Issue by neokore** [CartoDB/cartodb#7721]
When checking tables using CDB_UserTables() I found that it returns deleted tables, even when adding an extra parameter to avoid cache.

This are the SQL sentences I followed to reproduce:
**`> http://raulyeguas.cartodb.com/api/v2/sql?q=drop%20table%20cdb_geoproctool&api_key=[my_key]&_=nocache1`**
`< {"error":["table \"cdb_geoproctool\" does not exist"]}`

**`> http://raulyeguas.cartodb.com/api/v2/sql?q=select * from CDB_UserTables() as name where name='cdb_geoproctool'&api_key=[my_key]&_=nocache2`**
`< {"rows":[{"name":"cdb_geoproctool"}],"time":0.001,"fields":{"name":{"type":"name"}},"total_rows":1}`

**Comment by ramiroaznar** [comment]
This is already fixed.
