### ISSUE TITLE
Create viewer user UI

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#7727]
This is the current "new user" page:

![screen shot 2016-06-08 at 16 06 14](https://cloud.githubusercontent.com/assets/932968/15897343/69571788-2d94-11e6-8a1b-a3f31473389c.png)

For #7716 (and #7711) we need to be able to set the new user as "Viewer". If the user is meant to be viewer it hasn't quotas, so everything at "User quotas" section becomes useless.

**Comment by urbanphes** [comment]
We add an input to select type of user


![image](https://cloud.githubusercontent.com/assets/14546701/16075159/09050a0c-32ee-11e6-809f-0b3d91cc0984.png)

**Comment by juanignaciosl** [comment]
1.- What's the behaviour of "User quotas" section for "viewer" users? From a technical point of view it makes no sense, so I can set quota to 0, soft limits disabled and disable interaction, or I can hide everything.
2.- "Normal" instead of "Builder"?

**Comment by urbanphes** [comment]
1.- In my opinion "viewer" user wouldn't have quota. 
2.- This selection must be same that pricing

**Comment by saleiva** [comment]
Builder is the final name. We should add the number of available seats of each type, don't you think=

**Comment by juanignaciosl** [comment]
@urbanphes 
1.- yes, a viewer won't have quota, but I want to know the UI interaction.
2.- I don't understand what you mean.

@saleiva 

Yes, it will need some redesign for top tabs as well:

![screen shot 2016-06-15 at 12 55 29](https://cloud.githubusercontent.com/assets/932968/16077343/85e8e7d2-32f8-11e6-8e96-5b0c70d220a4.png)

**Comment by urbanphes** [comment]
@juanignaciosl 
I have changed the name "Normal" to "Builder" in the mockup.
![image](https://cloud.githubusercontent.com/assets/14546701/16143380/add2d1f2-346c-11e6-9012-d138e7ceb3ab.png)

1.- Oks, If you select a "Builder" show it the quotas below and if you select a "Viewer" don't show the quotas below. This have works like a tabs with and without content. 

2.-This was about the name "Builder" or "Normal" but it is already solved

**Comment by juanignaciosl** [comment]
@urbanphes we still need to show the organization seats quota. Currently it's at the users tab (see screenshot before) but having two different quotas should probably change this.

**Comment by xavijam** [comment]
@piensaenpixel @MariaCheca ^^^ ?

**Comment by urbanphes** [comment]
@juanignaciosl this is the visual design of how to make the list of users.

![organization - users](https://cloud.githubusercontent.com/assets/14546701/16268297/1e2abe36-388e-11e6-8c05-74364bd0d4a5.png)

**Comment by juanignaciosl** [comment]
@urbanphes a little suggestion: what do you think about keeping the tab account, with the sum of viewers and builders? It looks like this:

![screen shot 2016-06-23 at 20 54 54](https://cloud.githubusercontent.com/assets/932968/16316115/2f3bb746-3985-11e6-98bf-7b1ada02c180.png)

I can easily remove it, but after giving it a try I think that it's informative.

**Comment by urbanphes** [comment]
@juanignaciosl It seems perfect
