### ISSUE TITLE
Error when trying to add an analysis

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#7728]
**STR:**

1. Create a new map from an existing dataset (I tried with points).
2. Click "Add analysis", select "Buffer" / "Trade areas" and click "Add analysis".

**Expected result:**

- Analysis is added, modal is closed.

**Actual result:**

- JS error in the console:
`Uncaught Error: TrackJS Caught: simpleGeometryTypeInput is required`
- Modal is not closed and analysis is not created.

NOTE: I observed that it's possible to add Buffer / Trade Areas analyses after having added a Point in Polygon analysis first.

cc: @viddo

**Comment by viddo** [comment]
From offline conversation, looks like one node is in a invalid state:

```
 analysisDefinitionNodesCollection.at(0).querySchemaModel.attributes
Object {query: "SELECT * FROM twitter_t3chfest_reduced", status: "unfetched", may_have_rows: false}
> analysisDefinitionNodesCollection.at(1).querySchemaModel.attributes
Object {query: "", status: "unavailable", may_have_rows: false}
```
(missing query)

Need to investigate dataset and try to reproduce the scenario to really tell what's wrong
