### ISSUE TITLE
Lateral scroll difficult with mouse

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#7733]
<img width="344" alt="screen shot 2016-06-08 at 18 28 01" src="https://cloud.githubusercontent.com/assets/4222826/15902142/ca335992-2da6-11e6-99eb-d687b40ffb70.png">

This is very difficult to laterally scroll with a mouse.

I propose:
- Translate vertical scroll to lateral when hovering on top
- Adding floating lateral scroll button like in the old editor

cc/ @xavijam

**Comment by xavijam** [comment]
Could you check also that the selected item is not visible if it is at the end of the list.

**Comment by xavijam** [comment]
Already fixed some time ago.
