### ISSUE TITLE
Heatmap color change not having effect

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#7734]
<img width="818" alt="screen shot 2016-06-08 at 18 32 41" src="https://cloud.githubusercontent.com/assets/4222826/15902269/6ad12c1c-2da7-11e6-8a2a-5b3ec018bca8.png">

1. Create map
2. Add dataset
3. Change aggregation to Heatmap
4. Change color pallete to solid and try to change it from default black color

It's not applying the color from the selector. The selector does retain the selected color once collapsed.

cc/ @xavijam

**Comment by xavijam** [comment]
Could you check it @javisantana please?

**Comment by javisantana** [comment]
I fixed the issue but this opens for me a new question about heatmap.

There should not be a fixed value for heatmap, it should be always a ramp of colors. So the question, is there a way to setup a form to always show ramps and no fixed values ? @xavijam  I don't know if latest @javierarce work fixes that problem

**Comment by javisantana** [comment]
when I said I fixed I meant I fixed the javascript exception

**Comment by xavijam** [comment]
Yes, as far as I know we can "hide" fixed panel in the fill component. But I wanted @javierarce to confirm it.

**Comment by xavijam** [comment]
branch?

**Comment by javierarce** [comment]
Yes, the component should allow hiding the pane. I can have a look too.

**Comment by xavijam** [comment]
Don't worry mate, we have it :). But one thing, we are suffering the problem of having one column to select, although it is clicked, it doesn't go to the ramps list, similar to the reported one right?

**Comment by javierarce** [comment]
👌 . I'm having a look to that, will report later.

**Comment by xavijam** [comment]
❤️

**Comment by xavijam** [comment]
When https://github.com/CartoDB/cartodb/pull/7772 is merged, issue selecting 'points_agg' is solved, thanks to @javierarce ;).

**Comment by javisantana** [comment]
ok, let me rebase and test again

**Comment by javisantana** [comment]
like a charm
![arce](https://cloud.githubusercontent.com/assets/30147/16004566/95808c28-3162-11e6-83d8-9e5489538184.gif)
