### ISSUE TITLE
Hexabin and Square aggreagations won't color ramp

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#7735]
1. Create Map
2. Add dataset with points
3. Choose Hexabins or Square in aggreagation style
4. Choose color by value

Maps API complains that the wrong number of arguments is being passed.

<img width="1280" alt="screen shot 2016-06-08 at 18 51 44" src="https://cloud.githubusercontent.com/assets/4222826/15902853/570a8e46-2daa-11e6-8d41-e78ac8b1290b.png">

**Comment by xavijam** [comment]
Already added column type for `points_count` and `points_densitry`. Branch `issue-7735`.
