### ISSUE TITLE
Add close button to predefined infowindow templates

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#7737]
In https://github.com/CartoDB/cartodb.js/pull/1302 we added support for .js-close element in infowindows. We need to add the following markup to the [predefined templates](https://github.com/CartoDB/cartodb/tree/f94e26135f894a33e99d0b2a6a75cf3e038cd723/lib/assets/javascripts/cartodb3/mustache-templates/infowindows):

```
<div class="CDB-infowindow CDB-infowindow--light js-infowindow" style="max-width: 200px;">
  <div class="CDB-infowindow-close js-close"></div>
  ...
</div>
```

@matallo will existing layers use :point_up: markup as the infowindow template after we change it? thx

cc: @piensaenpixel

**Comment by matallo** [comment]
Assigning this myself, consider it done, man!
