### ISSUE TITLE
Only include number and data type columns in the Column selector for animated layers

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#7738]
1. Create Map
2. Add dataset with points
3. Choose a Simple style and animated (by cartodb_id for example)

The editor view works but the embed won't. In local, the request to the Map API is done incorrectly, using subdomain 'undefined' (probably JS error).

```
http://undefined.localhost.lan:8181/api/v1/map/named/tpl_90960058_2d93_11e6…callback=_cdbct_2235715396_1&stat_tag=90960058-2d93-11e6-a596-a0999b0ba531 
```
<img width="1280" alt="screen shot 2016-06-08 at 19 32 30" src="https://cloud.githubusercontent.com/assets/4222826/15904121/0dfaa2f8-2db0-11e6-9c2a-1d36cc298d8d.png">

cc/ @xavijam

**Comment by xavijam** [comment]
@javisantana @alonsogarciapablo, is this ticket the one we commented?

**Comment by javisantana** [comment]
yep

**Comment by alonsogarciapablo** [comment]
Taking a look.

**Comment by alonsogarciapablo** [comment]
@gfiorav I just tried to reproduce this issue, and it's working 👌  for me, both locally and in production.

Could you please make sure you're running the latest of the latest and try again locally? Could you please try to reproduce it production? Thx!

**Comment by gfiorav** [comment]
hey @alonsogarciapablo I was doing it in prod when I reported. Trying again, hang tight.

**Comment by gfiorav** [comment]
It's broken for me: https://team.cartodb.com/u/gfiorav/editor/8f7dffa8-2d9e-11e6-ac77-0e5db1731f59/embed

**Comment by gfiorav** [comment]
Actually, I deleted that map, sorry if you didd't have time to check it. 

Now I can't even create an animated layer to begin with:

![screen shot 2016-06-10 at 11 55 43](https://cloud.githubusercontent.com/assets/4222826/15960901/4ff8cc04-2f02-11e6-8c13-8325f104ba48.png)

**Comment by alonsogarciapablo** [comment]
Ok, I don't think what we're seeing in this last comment is related to the original description of this issue. What I discovered is that it does work as long as you select a numeric or date column... We should only show number / date type columns in the Column dropdown. This is what we're doing now in the current version of the editor (cc: @xavijam).

**Comment by alonsogarciapablo** [comment]
@gfiorav could you please try again and select a numeric/date column (cartodb_id, created_at...) and confirm that it works both on the editor and the embed? Thx

**Comment by xavijam** [comment]
If that's the problem, assign it to me and change the title please :).
