### ISSUE TITLE
Going to analyses panel doesn't select by default the first available analysis

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#7741]
### STR

- Create a map of points.
- Visualize it in the new builder.
- Apply a buffer analysis.
- After that go to the layer > style panel.
- Then go back to analysis and then first analysis doesn't appear selected.

![screen shot 2016-06-09 at 11 28 23](https://cloud.githubusercontent.com/assets/132146/15924968/5765b43e-2e35-11e6-90cf-720d9038a119.png)

But form from first analysis is rendered.

**Comment by viddo** [comment]
What were the steps/state before you reached this?

**Comment by xavijam** [comment]
Added them in the description.

**Comment by viddo** [comment]
The "analysis false" that appears int he screenshot indicate some kind of inconsistent state. Anyway, have not been able to reproduce this, so closing it… re-open if you manage to reproduce it again.

**Comment by viddo** [comment]
By coincidence I managed to reproduce it, but through other steps… easy fix though
