### ISSUE TITLE
disable basemaps panel when changing basemaps until savingLayersFinish

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#7743]
in current editor we disable basemaps dropdown while changing them until `savingLayersFinish` is fired to prevent unintended effects like several layers on top

we should disable this panel in the new editor, too

/cc @urbanphes in case it needs a design proposal

**Comment by urbanphes** [comment]
We use the same behavior that actual editor but leaving each selection to 24% opacity.

**Comment by matallo** [comment]
duplicated https://github.com/CartoDB/cartodb/issues/9193, closing then
