### ISSUE TITLE
Upgrade Mailchimp

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#7744]
Mailchimp will deprecate API 2.0 (the one we currently use) by the end of 2016: http://devs.mailchimp.com/blog/sunsetting-previous-mailchimp-api-versions/

cc @CartoDB/backend

**Comment by rafatower** [comment]
LOL

**Comment by javisantana** [comment]
I'd just remove mailchimp, the usage is really low

cc @saleiva

**Comment by ramiroaznar** [comment]
Closing this because we do not have MailChimp connector anymore.
