### ISSUE TITLE
Changing halo/text color in labels fails

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#7748]
1. Create a map
2. Add a dataset with points
3. Choose any style that allows for labels
4. Change color/halo color

The error reads: 
```
input-color-dialog-content.js:10Uncaught Error: configModel param is required
```
A result is thrown through the JS console like so:

<img width="1280" alt="screen shot 2016-06-09 at 15 40 23" src="https://cloud.githubusercontent.com/assets/4222826/15931598/b7426b18-2e58-11e6-9982-50d4af0aeb15.png">

Note that you can change de the text size with any problems.

**Comment by xavijam** [comment]
Already working with last changes, thanks to @matallo.

https://github.com/CartoDB/cartodb/commit/82341e5ccfa2029dca6f369ec4ed0cc0716ed804
