### ISSUE TITLE
Show previous analysis id+name on input form field for an analysis

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#7775]
All "input" fields in the analyses forms currently only display the id (e.g. "a0"), it should display the input with more visual cues, like this:

![screen shot 2016-06-13 at 12 40 46](https://cloud.githubusercontent.com/assets/978461/16004796/1f223836-3164-11e6-8415-363edf0aa0bc.png)

Should be implemented in such a way that's it's reusable for all the different kind of forms that have a source.

In the case it's a secondary source it should not be disabled and slightly different styling too:
![screen shot 2016-06-13 at 12 43 23](https://cloud.githubusercontent.com/assets/978461/16004850/76f0f43a-3164-11e6-93de-c7e3ad027a7d.png)

**Comment by saleiva** [comment]
yep, important on UX
