### ISSUE TITLE
Unable to select a different dataset after selecting one when adding a layer

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#7777]
**STR:**

1. Open a map using the new editor.
2. Click "Add" button on the Layers section.
3. Select one of the datasets under the "Dataset" tab.
4. Try to select a different dataset.

**Expected result:**

- I can click and select datasets as many times as I want.

**Actual result:**

- After clicking on one dataset, clicking on other datasets has no effect and I can't select a different dataset.

Here's a GIF where I click on a dataset and then click on others:

![add_layer](https://cloud.githubusercontent.com/assets/390398/16007679/470d251c-3174-11e6-9499-bcabf9c18405.gif)

cc: @xavijam

**Comment by xavijam** [comment]
Duplicated -> https://github.com/CartoDB/cartodb/issues/7426
