### ISSUE TITLE
feature request: ability for admins to delegate group management to users

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartodb#7779]
Currently groups can only be managed by the organization admin. For larger accounts such as those at universities, this puts a large burden on the admin if multiple professors want groups to be managed for classes. To relieve this burden, a new feature for the admin to delegate management of groups to some users would be killer. 

The workflow I see is: 
1. professors ask for a group creation from the admin, 
2. admin creates group, 
3. professor adds his/her students to group, 
4. students/professor share maps, 
5. professor limits dataset/map access after class has ended

cc @juanignaciosl @mapninja

**Comment by juanignaciosl** [comment]
cc @xavijam @javisantana
