### ISSUE TITLE
popup performance

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#7782]
when i try click, scroll or do something in poup view i've a bit of delay.

**Comment by matallo** [comment]
taking  alook with @nobuti, seems to be related to codemirror tabpane

**Comment by matallo** [comment]
spotted, removing the `ScrollView` in https://github.com/CartoDB/cartodb/blob/7736-popup/lib/assets/javascripts/cartodb3/editor/layers/layer-content-views/infowindow/infowindow-view.js#L52 and https://github.com/CartoDB/cartodb/blob/7736-popup/lib/assets/javascripts/cartodb3/editor/layers/layer-content-views/infowindow/infowindow-view.js#L61 really makes a difference

(also, it can be a good opportunity to fix the html toggle)

reassigning to @nobuti then

**Comment by nobuti** [comment]
I could not take a deeper look but I implemented some changes in https://github.com/CartoDB/cartodb/pull/7955/commits/37065a61360ef5461de7d631d3748a53f7903551.

**Comment by xavijam** [comment]
I feel it is working properly now, so let's close it and check in the future.
