### ISSUE TITLE
Duplicating a map previously edited with the new editor and opening the copy in the new editor fails

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#7784]
It gives an error on the maps api saying that SQL is missing.

Create a map using the new editor.
Open the map on the actual editor.
Duplicate the map.
Go to the new map in the new editor. 
(ERROR)

If you clear view on actual editor, and go back to the new editor it works

**Comment by javitonino** [comment]
Duplicated -> #7657
