### ISSUE TITLE
Clicking on the number on a combined selector should let you edit the number without making extra clicks

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#7787]
![screen shot 2016-06-13 at 19 38 25](https://cloud.githubusercontent.com/assets/132149/16017060/78138c08-319e-11e6-8269-4ec52dd3191f.png)

Either we edit the number directly on the popup component (and put the focus on the text input when opening) or we do it directly on the combined component (top solution)

**Comment by piensaenpixel** [comment]
Related - https://github.com/CartoDB/design/issues/1082
