### ISSUE TITLE
We need better color-scales for heatmaps

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#7794]
We need a better set of ramps instead of the ones by default that we have for choropleth maps.

cc/ @xavijam

**Comment by makella** [comment]
👍

**Comment by makella** [comment]
@saleiva 

thought: heat map ramp, yes.

I was also thinking that for the other "Aggregation" map types that we might want to think of default ramps also, specifically hexbins and squares.

So not a color ramp that necessarily goes from light to dark with varying lightness but more of a spectral type ramp.

Example:

![screen shot 2016-06-23 at 5 11 16 pm](https://cloud.githubusercontent.com/assets/1566273/16308520/96b977ca-3965-11e6-9a50-8d000b03e8fb.png)

**Comment by saleiva** [comment]
Love

2016-06-23 17:12 GMT+02:00 Mamata Akella <notifications@github.com>:

> @saleiva <https://github.com/saleiva>
>
> thought: heat map ramp, yes.
>
> I was also thinking that for the other "Aggregation" map types that we
> might want to think of default ramps also, specifically hexbins and squares.
>
> So not a color ramp that necessarily goes from light to dark with varying
> lightness but more of a spectral type ramp.
>
> Example:
>
> [image: screen shot 2016-06-23 at 5 11 16 pm]
> <https://cloud.githubusercontent.com/assets/1566273/16308520/96b977ca-3965-11e6-9a50-8d000b03e8fb.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/7794#issuecomment-228082022>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAIENXkypPlFegRdfMFArL8n8OHf1f1Nks5qOqJMgaJpZM4I0k7I>
> .
>



-- 
Sergio Alvarez Leiva

**Comment by makella** [comment]
@saleiva are we at the capacity to have a set of default styles for positron vs. dark matter? if no, no problem just want to check. and i guess it would apply to all the default symbology.

**Comment by saleiva** [comment]
yes, but on the future. We can create those counting with that functionality, but taking in consideration that it will take so time to implement

**Comment by makella** [comment]
ok sounds good. for now then we'll have defaults that work across both.
thanks!

**Comment by makella** [comment]
@saleiva 

added two new color ramps for hexbins and squares. also can be used for heatmap. santana and i have added the green colored variation as the default for hexbins and squares and the purple > yellow ramp for the heatmap.

we still need to figure out the cartography better for the heatmap but as requested we now have a ramp at a minimum.

examples:

hexbins:
![screen shot 2016-07-05 at 10 20 06 am](https://cloud.githubusercontent.com/assets/1566273/16578336/2c3bb0aa-429a-11e6-9dd1-56001ae94cb8.png)

![screen shot 2016-07-05 at 10 20 34 am](https://cloud.githubusercontent.com/assets/1566273/16578339/32ba1dc2-429a-11e6-90fa-46ed07b48983.png)

squares:
![screen shot 2016-07-05 at 10 22 34 am](https://cloud.githubusercontent.com/assets/1566273/16578378/753c6f24-429a-11e6-8025-a8a98bcae3be.png)

![screen shot 2016-07-05 at 10 22 23 am](https://cloud.githubusercontent.com/assets/1566273/16578381/7b390df6-429a-11e6-9e85-3594dfb65e16.png)

heatmap:
<img width="510" alt="screen shot 2016-07-05 at 10 29 10 am" src="https://cloud.githubusercontent.com/assets/1566273/16578539/687045bc-429b-11e6-94b1-74ab79c77932.png">

<img width="498" alt="screen shot 2016-07-05 at 10 29 30 am" src="https://cloud.githubusercontent.com/assets/1566273/16578558/78b76fd6-429b-11e6-9f3a-ffee50c186e5.png">

**Comment by saleiva** [comment]
Lovely, lovely!

2016-07-05 10:31 GMT+02:00 Mamata Akella <notifications@github.com>:

> @saleiva <https://github.com/saleiva>
>
> added two new color ramps for hexbins and squares. also can be used for
> heatmap. santana and i have added the green colored variation as the
> default for hexbins and squares and the purple > yellow ramp for the
> heatmap.
>
> we still need to figure out the cartography better for the heatmap but as
> requested we now have a ramp at a minimum.
>
> examples:
>
> hexbins:
> [image: screen shot 2016-07-05 at 10 20 06 am]
> <https://cloud.githubusercontent.com/assets/1566273/16578336/2c3bb0aa-429a-11e6-9dd1-56001ae94cb8.png>
>
> [image: screen shot 2016-07-05 at 10 20 34 am]
> <https://cloud.githubusercontent.com/assets/1566273/16578339/32ba1dc2-429a-11e6-90fa-46ed07b48983.png>
>
> squares:
> [image: screen shot 2016-07-05 at 10 22 34 am]
> <https://cloud.githubusercontent.com/assets/1566273/16578378/753c6f24-429a-11e6-8025-a8a98bcae3be.png>
>
> [image: screen shot 2016-07-05 at 10 22 23 am]
> <https://cloud.githubusercontent.com/assets/1566273/16578381/7b390df6-429a-11e6-9e85-3594dfb65e16.png>
>
> heatmap:
> [image: screen shot 2016-07-05 at 10 29 10 am]
> <https://cloud.githubusercontent.com/assets/1566273/16578539/687045bc-429b-11e6-94b1-74ab79c77932.png>
>
> [image: screen shot 2016-07-05 at 10 29 30 am]
> <https://cloud.githubusercontent.com/assets/1566273/16578558/78b76fd6-429b-11e6-9f3a-ffee50c186e5.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/7794#issuecomment-230417781>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAIENSvaFg2I4370U_y95Wif8oAXXrLYks5qShZJgaJpZM4I0k7I>
> .
>



-- 
Sergio Alvarez Leiva
