### ISSUE TITLE
Clicking on undo after animated=true breaks the form area 

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#7800]
Create a point map
Change the point color
Click on "animated"
Click on undo.

The form area gets empty forever

**Comment by xavijam** [comment]
Not happening to me in local, let me try in production.

**Comment by xavijam** [comment]
_reproduced_

**Comment by xavijam** [comment]
It is like "broken" because query-schema-model status attribute is resetted to 'unfetched' when the analysis is saved. I feel after @viddo finishes his work in the ticket about analysis persistence we can't fix it.

**Comment by xavijam** [comment]
Already fixed by @viddo with https://github.com/CartoDB/cartodb/pull/8232 👏
