### ISSUE TITLE
[POPUPS] Popup fields order gets changed after clicking a new field

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#7801]
Create a point map
Go to popup
Select a field
Move that field to the first position
Click on another field
>>> The order of fields get changed.

**Comment by saleiva** [comment]
It didn't happen to me on hover, but happened to me on click. Not sure if this is a normal rule

**Comment by matallo** [comment]
submitted the PR https://github.com/CartoDB/cartodb/pull/8192 and reported a bug in the current editor https://github.com/CartoDB/cartodb/issues/8191

**Comment by saleiva** [comment]
should we close this @matallo ?
