### ISSUE TITLE
Disabled combo selector shouldn't be clickeable

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#7806]
![screen shot 2016-06-13 at 20 12 35](https://cloud.githubusercontent.com/assets/132149/16018103/362b0bae-31a3-11e6-9ca7-2c0e98fd9a06.png)

In the add widget modal you can still click on them

**Comment by piensaenpixel** [comment]
working in this issue - https://github.com/CartoDB/cartodb/issues/7522
