### ISSUE TITLE
Widgets scroll gradient is visible even when not having scroll

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#7810]
![screen shot 2016-06-13 at 20 18 01](https://cloud.githubusercontent.com/assets/132149/16018255/ff2f6d4c-31a3-11e6-9726-2a58f3c24575.png)

**Comment by piensaenpixel** [comment]
move to deep insights' repo

https://github.com/CartoDB/deep-insights.js/issues/370
