### ISSUE TITLE
[WIDGETS] Delete widget option not present on the Widget options list

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#7811]
It should be only visible within the editor, of course

**Comment by xavijam** [comment]
Sorry, I don't get you

**Comment by saleiva** [comment]
The widgets have a contextual menu under the 3 dots icons. Within that
menú, we should add that option.

**Comment by xavijam** [comment]
Issue moved to [CartoDB/deep-insights.js #452](https://github.com/CartoDB/deep-insights.js/issues/452) via [**ZenHub**](https://www.zenhub.com/)
