### ISSUE TITLE
[WIDGETS] After deleting a widget that is filtering the data, the filter gets not removed

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#7812]
Go to a point dataset for example
Add a widget
Filter using the widget
Remove the widget

Data displayed on the map is the filtered data and not all the data.

**Comment by xavijam** [comment]
A bug in CartoDB.js -> https://github.com/CartoDB/cartodb.js/pull/1321.

**Comment by xavijam** [comment]
Merged!
