### ISSUE TITLE
[STYLES] Clear and Continue do the same action

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#7823]
cc/ @urbanphes 

![screen shot 2016-06-14 at 12 41 02](https://cloud.githubusercontent.com/assets/132149/16039984/55c57f00-322d-11e6-83de-7b82d13d6fba.png)

I believe those options are not the ones proposed on the designs.

**Comment by urbanphes** [comment]
@saleiva When we have a CSS applied and return to values this is the message we have

[https://projects.invisionapp.com/share/5G4TKZHEJ#/screens/128070251](url)

**Comment by saleiva** [comment]
yep but I mean the functionality. Both actions do the same thing right now, but it shouldn't be like that right?

**Comment by urbanphes** [comment]
Ah oks. 
The actions have to do:

- **a) Clear:** Clean/Delete the code CSS you has been writing.
- **b) Continue:** Leave the code CSS you has been writing.

**Comment by saleiva** [comment]
with b) we would go back to the css editor, right?

**Comment by ernesmb** [comment]
Hey I've reopened this because I think the buttons' actions are switched, currently: 

- **CLEAR** returns to the CartoCSS editor without clearing the style
- **CONTINUE** clears the custom CartoCSS and resets the style

**Comment by nobuti** [comment]
Same issue as https://github.com/CartoDB/cartodb/issues/10345

**Comment by saleiva** [comment]
so its closed already?

**Comment by nobuti** [comment]
No, the actions are inverted, we need to fix it. But the reason is that.
