### ISSUE TITLE
After applying an analysis, it offers you to create it instead of apply changes

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#7826]
## STR

1. Create a map with a layer of points (layer A).
2. Go to the builder.
3. Apply a simple style to the layer A.
4. Add a buffer analysis over that layer A.
5. Apply a radius 40 meters.
6. Go to style again, style should be reseted.
7. Apply a simple one and change the color.
8. Go to the CartoCSS panel and change the `polygon-fill` to `red`, for example, apply changes.
9. Go back to analyses tab and check that the analysis already applied is offering `Create` instead of  `Apply`.

![screen shot 2016-06-14 at 12 43 55](https://cloud.githubusercontent.com/assets/132146/16040054/ae5518d8-322d-11e6-89c3-7534df994992.png)

Reported by @saleiva

**Comment by xavijam** [comment]
After testing with @makella a little bit, we have discovered that this happens when a new analysis is added. I feel this is pretty important.

**Comment by viddo** [comment]
I'll look into it next

**Comment by saleiva** [comment]
Not only then, It's also happening if you...
Create a dataset with points
Apply a cluster analysis
Go to Style
Style by value 
go back to analysis.

It says CREATE instead of APPLY, and the parameters are reset to defaults.
