### ISSUE TITLE
Source layer parameter is missing from the widget config panel

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#7837]
This is important @xavijam 

right now you need to delete the widget and add it again for changing the source layer

**Comment by xavijam** [comment]
Take into account that's not an easy task because having a column selected, if we let the user change the source, we should force the user to select a new column before applying changes.

**Comment by saleiva** [comment]
Thats not a problem at all. As an extra ball, we could select the same column if its present and if not, ask for the column (Having the same columns is very common). This means a big usability issue as we've detected with users.

**Comment by xavijam** [comment]
Roger!
