### ISSUE TITLE
[ANALYSIS] After changing the parameters of an analysis forcing widgets recalculation

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#7838]
the map gets refreshed but the widgets don't

**Comment by saleiva** [comment]
it should do the same when a query is being applied

**Comment by viddo** [comment]
Issue moved to [CartoDB/cartodb.js #1322](https://github.com/CartoDB/cartodb.js/issues/1322) via [**ZenHub**](https://www.zenhub.com/)
