### ISSUE TITLE
Units are missing on time input

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#7840]
![screen shot 2016-06-14 at 14 01 09](https://cloud.githubusercontent.com/assets/132149/16041943/83b713c8-3238-11e6-9a10-8e675db1d18f.png)

**Comment by javisantana** [comment]
It should have the same thing than distance:
![screen shot 2016-06-14 at 7 07 31 pm](https://cloud.githubusercontent.com/assets/30147/16052219/828d144a-3263-11e6-8700-28f3b2d9646b.png)

**Comment by saleiva** [comment]
We can try with that... @urbanphes

2016-06-14 19:09 GMT+02:00 javi santana <notifications@github.com>:

> It should have the same thing than distance:
> [image: screen shot 2016-06-14 at 7 07 31 pm]
> <https://cloud.githubusercontent.com/assets/30147/16052219/828d144a-3263-11e6-8700-28f3b2d9646b.png>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/7840#issuecomment-225949435>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAIENcqupGr85woIZmavr-gVxr6kUGSaks5qLuBJgaJpZM4I1Pt->
> .
>



-- 
Sergio Alvarez Leiva

**Comment by urbanphes** [comment]
but in the beginning this component was designed another way.

![image](https://cloud.githubusercontent.com/assets/14546701/16072376/d19b5c36-32e0-11e6-9028-ceafed173abc.png)

**Comment by saleiva** [comment]
for the time being we will need to do the simpler approach :(

**Comment by matallo** [comment]
<img width="280" alt="screen shot 2016-11-16 at 16 50 40" src="https://cloud.githubusercontent.com/assets/36676/20353960/e0156e90-ac1c-11e6-95dc-0c9247f87d80.png">

there are already units in the label, for sure this would be better exposed with that component, but closing the issue for now

feel free to reopen with the radius component
