### ISSUE TITLE
maxwidth for inputs is missing

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#7841]
![screen shot 2016-06-14 at 14 04 33](https://cloud.githubusercontent.com/assets/132149/16042039/efe56298-3238-11e6-8a90-0eea9b67fa30.png)

**Comment by piensaenpixel** [comment]
hahaha i love easy tag @javisantana

**Comment by javisantana** [comment]
@piensaenpixel easy for you i meant
