### ISSUE TITLE
html editor for infowindows is broken

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#7851]
1. create a visualization with a layer
1. go to infowindow and enable light style, select some fields
1. go to html editor, it does not show up, this is shown instead

![screen shot 2016-06-14 at 7 15 20 pm](https://cloud.githubusercontent.com/assets/30147/16052422/82629fac-3264-11e6-999d-e0094e276feb.png)

**Comment by xavijam** [comment]
This is not a bug, we have to implement it.
