### ISSUE TITLE
change order of import guessing 

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartodb#7854]
Context:
When you import a file with city column and a country column to CartoDB, it looks like that the order for the import guessing is first guessing by IP address, then by country and last by city name.

When CartoDB founds a column to georeference during the import guessing process, it stops searching for more columns to guess and it georeference the data with the column that finds first.

In the case of a table with city and country columns, it will georeference the data with country names but it won't use the city column to georeference the data, because the order of the import guessing first is to check by country name and then by city.  

Steps:

1- If you have a dataset with two columns, a column of cities and a column of countries like this table:

![screen shot 2016-06-15 at 10 28 23](https://cloud.githubusercontent.com/assets/11177693/16072956/ed5b5b1c-32e3-11e6-9d20-011f3f3272ef.png)

2 -When you import the dataset to CartoDB with the guessing option enabled, CartoDB georeference only the polygons. 

![screen shot 2016-06-15 at 10 38 47](https://cloud.githubusercontent.com/assets/11177693/16073266/629f7ab0-32e5-11e6-9296-b1be77f6a44b.png)

The import log shows this:

```json
 Trying ip guessing... true: Trying country guessing... true: country_proportion(city) = 0.0 true: 
country_proportion(country) = 1.0 true: Found country column: country true: Creating the_geom column true: 
Geocoding countries... true: Creating the_geom column true: Geocoding finished
```

3 - If I delete the country column to the table and import it to CartoDB

![screen shot 2016-06-15 at 10 31 25](https://cloud.githubusercontent.com/assets/11177693/16073059/5db5c406-32e4-11e6-8c47-505ca63b30b2.png)

4- CartoDB georeference by city name:

![screen shot 2016-06-15 at 10 37 12](https://cloud.githubusercontent.com/assets/11177693/16073287/84d9eade-32e5-11e6-8471-54ef5eb0c067.png)

 The import logs show this:

```json
Trying ip guessing... true: Trying country guessing... true: country_proportion(city) = 0.0 true:
 Trying namedplaces guessing... true: country_proportion(city) = 0.0 true: 
Found namedplace column: {:column_name=>"city", :data_type=>"character varying"} true: Creating the_geom column true: Geocoding namedplaces... true: Creating the_geom column true: Geocoding finished 
```

**Comment by rafatower** [comment]
https://github.com/CartoDB/cartodb/blob/dc79403c52d7a3e42d68cb5a6bf9b2178cb843e4/services/importer/lib/importer/georeferencer.rb#L45-L49

Fairly easy to change, @iriberri , for next milestone, we can change it and leave it for testing in a staging.

@oriolbx you'll have to help us a little smoke testing it in the look out for undesired side effects (an unexpected guessing that disappoints some user?)

**Comment by iriberri** [comment]
:+1:

**Comment by rafatower** [comment]
BTW the main reason for that ordering was performance. And normally only happens with small tables cause otherwise you have repeated countries.

**Comment by oriolbx** [comment]
@rafatower I will be happy to help with the smoke testing :) The problem is that this also happens with sync tables, and because the sync tables don't allow manual geocoding, the users can't change the geometries from countries to cities manually.

**Comment by michellechandra** [comment]
S/B: 9172630

**Comment by rafatower** [comment]
I'm deploying it to `ded05-st`. You can regression test it as soon as it is deployed.

**Comment by rafatower** [comment]
Tested locally with this file:

https://gist.githubusercontent.com/rafatower/310eb9a4b08f6c5a7f2cf6cbb5ba7d56/raw/f44a073ca431ffe79440f67d88167c575c633e10/city_country_guessing.csv

I couldn't test it in `ded05-st` yet.

**Comment by rafatower** [comment]
I think we shall create a directory of patches to build the version `0.0.2` out of the base dumps in `0.0.1` plus the patches (just a few inserts and/or updates). What do you think?

**Comment by iriberri** [comment]
It's looking good. While testing I realized we're not computing the entropy of a possible column containing IP addresses, so even if these IPs are completelyt repeated in the table, IP guessing is going to be performed.

**Comment by oriolbx** [comment]
I've finished with the tests and it seems to work correctly. It looks good :)

**Comment by iriberri** [comment]
Okay, so let's put it in production then. @rafatower do I take care of the deploy too? I'm assuming so but just in case. -> https://github.com/CartoDB/cartodb/pull/8026#issuecomment-227672714

**Comment by rafatower** [comment]
yep, please

**Comment by iriberri** [comment]
Fixed in https://github.com/CartoDB/cartodb/pull/8026
