### ISSUE TITLE
Hexabin/Square styles don't work on old viz with infowindows migrated to builder

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#7857]
STR:

1. Create Map in old editor
2. Add datasets with points
3. Add click and hover infowindows
4. Open viz in builder
5. Apply style with aggregation (hexabins, squares)

An error ir shown where the Maps API can't find an interactivity column. The problem is worked around by reapplying infowindow (popup) styles in the builder.

```
log.js:27 Request to Maps API failed: Postgis Plugin: ERROR:  column "hu_site_limit" does not exist
LINE 1: ... 3.37241e-06), 6.74483e-06)) AS geom,"cartodb_id","hu_site_l...
                                                             ^

in executeQuery Full sql was: 'SELECT ST_AsBinary(ST_Simplify(ST_SnapToGrid("the_geom_webmercator", 3.37241e-06), 6.74483e-06)) AS geom,"cartodb_id","hu_site_limit" FROM (WITH hgrid AS (SELECT CDB_RectangleGrid ( ST_Expand(ST_MakeEnvelope(-20037508.3,20037508.29613578,-20037508.29613578,20037508.3,3857), greatest(0.000134897,0.000134897) * 100), greatest(0.000134897,0.000134897) * 100, greatest(0.000134897,0.000134897) * 100) as cell) SELECT hgrid.cell as the_geom_webmercator, count(1) as points_count, count(1)/power( 100 * CDB_XYZ_Resolution(CDB_ZoomFromScale(0.520686)), 2 ) as points_density, 1 as cartodb_id FROM hgrid, (SELECT * FROM fl_insurance_sample) i where ST_Intersects(i.the_geom_webmercator, hgrid.cell) GROUP BY hgrid.cell) as cdbq LIMIT 65535'
```

**Comment by javisantana** [comment]
infowindows should be disabled when style is hexagons or rectangles (torque based ones as well)

cc @matallo

**Comment by matallo** [comment]
doing so in https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb3/data/layer-definition-model.js#L94-L101

shall we do the same with tooltips?

**Comment by xavijam** [comment]
Already disabled tooltip and infowindow fields when a style aggregated or animated is enabled.

Branch: issue-7857
