### ISSUE TITLE
Category widgets' aggregation functions

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb#7858]
The builder is offering a lot of different aggregation functions for category widgets, but only SUM and COUNT are allowed

**Comment by xavijam** [comment]
@MariaCheca, could you take a look please?
- Remove all the operations we included in https://github.com/CartoDB/cartodb/pull/7685.
- Please, `SUM` and `COUNT` should appear uppercase in the selectors.

**Comment by saleiva** [comment]
even avg?

**Comment by xavijam** [comment]
I think so, do we have any other operation available there @rochoa or @dgaubert?

**Comment by AbelVM** [comment]
In my tests, only SUM and COUNT work

**Comment by MariaCheca** [comment]
On my way!

**Comment by AbelVM** [comment]
(it would be great if all the other agg functions work with categories)

**Comment by saleiva** [comment]
totally. Specially avg

2016-06-20 15:06 GMT+02:00 Abel Vázquez Montoro <notifications@github.com>:

> (it would be great if all the other agg functions work with categories)
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/7858#issuecomment-227136434>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAIENa971-wc1HPtyYqO4xlEHOlpz-X3ks5qNpBWgaJpZM4I2M-8>
> .
>



-- 
Sergio Alvarez Leiva

**Comment by rochoa** [comment]
Why are we removing them?

I will add support in dataviews soon: https://github.com/CartoDB/Windshaft-cartodb/issues/513

**Comment by xavijam** [comment]
Because they are throwing an error. Let me create a ticket to add them when yours is done, deal?

**Comment by AbelVM** [comment]
:clap:
