### ISSUE TITLE
New editor doesn't save the position of the map

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#7863]
Create a map,
Move around
Refresth the page
AND
The last position of the map is not saved.

**Comment by viddo** [comment]
Isn't this a dupe of #7484 ? 😄

**Comment by saleiva** [comment]
amazing speed. Thanks mate. Closing!

**Comment by juanignaciosl** [comment]
Blink and you'll miss it! Thanks, @viddo !
