### ISSUE TITLE
Varnish invalidations triggers should escape special regex symbols

### ISSUE THREAD

**Issue by zenitraM** [CartoDB/cartodb#7868]
Steps to reproduce:
- have a table that ends with a surrogate key containing a `+` with an environmnet configured with 
- invalidate that table

The `+` on the [Varnish HTTP trigger](https://github.com/CartoDB/cartodb/blob/master/app/models/user/db_service.rb#L1311) is sent unescaped; causing the regex to incorrectly match.

We should make the script replace at least `+` by `\+` and any other base64 characters that match special regex chars.

**Comment by javisantana** [comment]
should we do this at platform level as well ? cc @rochoa

**Comment by zenitraM** [comment]
this is being handled correctly on the platform, only affects OSS users that use direct Varnish HTTP invalidations
