### ISSUE TITLE
Only persist models/collections on explicit user-actions

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#7881]
There are still some occasions where models/collection are saved on implicit changes. I've experienced some race-conditions due to this while working on the drag-node-to-create-layer feature #7878. These are the places 

I've found these, so far, by having a quick check (there might be more):

- [ ] widget-definitions-collection; sync => layerDef.save
- [ ] layer-definitions-collection; sync => create/update analysis
- [ ] analysis-definitions; change => save analysis

This is probably related to what you noticed @xavijam, that there are some unnecessary requests being done on some occasions.

cc @javisantana @alonsogarciapablo

**Comment by alonsogarciapablo** [comment]
Just noticed something that could be addressed as part of this issue. When an analysis node is dragged and dropped outside of the layer, the map is being instantiated twice:

1. when the source of the layer that contained the analysis is updated.
2. when the new layer with the analysis is added.

If we want to solve this with the current implementation, we'd need to do 1. silently.

**Comment by javisantana** [comment]
an idea, what if we add a debug method to the base model like:

```
setActiveId: function(i) {
this._aid = i;
}
```

so when we open a view we do:

```
model.setActiveId(view.cid)
```

so we could check on save method:

```
save: function() {
 if(this._aid && !cdb.view.Views.byCid(this._aid).isShowing()) ´
    // warn!!!
 } else {
   // error: implicit save
 } 
}
```
