### ISSUE TITLE
Wrong search icon

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#7883]
I just noticed the search icon in the Maps page is wrong:

![screen shot 2016-06-16 at 12 22 58](https://cloud.githubusercontent.com/assets/390398/16113581/28b3550a-33bd-11e6-837c-b3843decedf5.png)
 
cc: @xavijam @piensaenpixel

**Comment by alonsogarciapablo** [comment]
Seems to be a local issue. Closing for now.

**Comment by xavijam** [comment]
👍 , yep, update your internals and grunt again.
