### ISSUE TITLE
When layer is hidden, we have to show an infobox with message and the opaque view

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#7895]
But before we need this ![PR](https://github.com/CartoDB/cartodb/pull/7848/files) merged :).

**Comment by xavijam** [comment]
As we discussed, close button is useless, because it doesn't do anything.

**Comment by nobuti** [comment]
For all panes, right?

**Comment by xavijam** [comment]
I feel those should be analysis, style and popup.

**Comment by saleiva** [comment]
+1

**Comment by saleiva** [comment]
well not analysis, think that a layer can be used as an intermediate node on an analysis.

**Comment by xavijam** [comment]
Oh, you are right, so style and popup :). Thanks @saleiva for that.
