### ISSUE TITLE
vizjson uses http even when loaded over https (mixed content error)

### ISSUE THREAD

**Issue by juw177** [CartoDB/cartodb#7900]
**Intended behaviour:**

The vizjson contains urls for loading map tiles. When loading vizjson over https it should have:
```
maps_api_template: "https://{user}.cartodb.com:443",
sql_api_template: "https://{user}.cartodb.com:443",
```

When loading over http it should have:
```
maps_api_template: "http://{user}.cartodb.com:80",
sql_api_template: "http://{user}.cartodb.com:80",
```

**The bug:**
Background: I have a paid account with a few public maps using google map tiles. I load the map using cartodb.js api's createVis function I have found that under certain conditions, this causes the response to contain map urls in the incorrect http protocol.

1. Modify a map on cartodb editor and get its vizjson url

2. Paste the viz json url into browser as a **http** url. Append "?callback=vizjson" to the end to emulate the way createVis function loads the file.
eg, http://USER.cartodb.com/u/USER/api/v2/viz/xxx-xxxx-xxx/viz.json?callback=vizjson

3. The viz json file shows. Search for the **maps_api_template** attribute to see that it is using http

4. Change the url from http to https and reload the vizjson

5. The "maps_api_template" will still say http. This will cause mixed content errors on any https page trying to load the map.

Through trial and error, I have found that it is caused by the first hit of the vizjson after the map has been modified. If the first hit is via http, it will remain http even when I hit it subsequently with https. To "fix" this, I had to modify the map again and reload the vizjson via https.

The other weird thing is that it only occurs when ?callback=vizjson is in the url. If the callback is changed or removed the bug goes away.

**Comment by javitonino** [comment]
Seems like a caching issue with vizjson and organization users. We are only caching one version(http/https) of the vizjson for urls with the `/u/user` part. The `?callback` parameter does not seem to be important here, but the problem is more obvious with it.

Can you take a look @luisbosque?

**Comment by juw177** [comment]
Hi, I agree this is a cache issue, can we put this as a bug?

It is causing our organization big problems because the layers on our https site will randomly disappear and an admin must manually refresh the cache again to get the https version.

**Comment by zenitraM** [comment]
@juw177 this was actually related to a configuration issue in our internal Varnish that was considering the http vizjson the same object as the https one. We just applied a fix, could you check if it works as it should now?

**Comment by juw177** [comment]
Thanks for doing the fix. Seems to be working!
