### ISSUE TITLE
Choropleth styles migration is not working anymore

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#7902]
## STR
- Create a map of points.
- Go to the editor and apply the choropleth wizard.
- Go to the new builder, and check style panel.
- Screenshot below:

![screen shot 2016-06-17 at 10 19 38](https://cloud.githubusercontent.com/assets/132146/16144710/0c09d254-3475-11e6-8e18-92fed7744992.png)

The problem basically is that we set the range with the `wizards-properties` value, that only represents the color, we should "convert" it in the fill component @javierarce.
![screen shot 2016-06-17 at 10 13 32](https://cloud.githubusercontent.com/assets/132146/16144591/4bf8ca1a-3474-11e6-9aca-91d83546dd25.png)

**Comment by javierarce** [comment]
Also, the quantification needs to be migrated too.

**Comment by xavijam** [comment]
true :(
