### ISSUE TITLE
Display errors on analysis not tied to a specific form field

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#7904]
We show the red indicator "dot", but there's no explanation to _why_:
Probably we should display some generic error somewhere/somehow.

E.g.:
![screen shot 2016-06-17 at 10 51 23](https://cloud.githubusercontent.com/assets/978461/16145552/8e119800-3479-11e6-8634-319eabca6f75.png)

In this particular case any of the fields must have a value but since this form is automatically generated and the values are indicated as _optional_ they're not marked as required. There could be other errors which are not anticipated.

cc @urbanphes

**Comment by viddo** [comment]
![image](https://cloud.githubusercontent.com/assets/978461/16145930/b1864068-347b-11e6-82ef-35114e5a2fad.png)

Display a generic error message like the one in the example (w/o the dark styling ofc)

**Comment by urbanphes** [comment]
Yeah! It could be a good place for a generic errors.

**Comment by ramiroaznar** [comment]
Hey @urbanphes can we close this issue? AFAIK, we have those errors implemented.
