### ISSUE TITLE
Vector tile very big buffer

### ISSUE THREAD

**Issue by jaakla** [CartoDB/cartodb#7905]
Vector tile seems to have very big buffer, so here 90% of data in tile is outside requested tile boundaries. The screenshot has raster (orange tile) compared to mvt tile - all the blue dots, as only green tile area was requested.

Sample tile URL is : https://cartocdn-ashbu.global.ssl.fastly.net/nutiteq/api/v1/map/ca93814598be95ce17ceea2013dfee98:1465810731584/3/4/3.mvt?map_key=XXX&api_key=XXX&cache_policy=persist , attached is same vector tile as it is in MVT and as converted to geojson for easier preview.

Buffer would be good, but small one, just few pixels. This one creates huge duplicate data download.

![screenshot 2016-06-13 14 54 25](https://cloud.githubusercontent.com/assets/5609650/16146258/d025fffe-3485-11e6-836c-07ae8b3527a1.png)

[cities_3_4_3.geojson.zip](https://github.com/CartoDB/cartodb/files/320158/cities_3_4_3.geojson.zip)
[cities_3_4_3.mvt.zip](https://github.com/CartoDB/cartodb/files/320161/cities_3_4_3.mvt.zip)

**Comment by javisantana** [comment]
hey @rochoa could you point @jaakla to the place we generate MVT so he can take a look and try to debug the problem?

**Comment by rochoa** [comment]
The buffer size is hardcoded at tilelive-bridge, set to 256: https://github.com/mapbox/tilelive-bridge/blob/15e4501e49d436aeb57837be63a5effffa59c7ff/index.js#L105

We use our own fork to use our custom mapnik build, it uses the same hardcoded value: https://github.com/CartoDB/tilelive-bridge/blob/c32aa3c93052b7191f5659174c40a4a1e9d693a2/index.js#L79. We could modify it to use a lower buffer-size by default or even pick the buffer-size from the Map property defined in cartocss.

**Comment by cellum** [comment]
Buffer size has to be changed in line 195. (https://github.com/CartoDB/tilelive-bridge/blob/c32aa3c93052b7191f5659174c40a4a1e9d693a2/index.js#L195) Because buffer size=256 is good for rastertiles, 16 is enough for vectortiles.

Attached tile has buffer size 16
[3-buf16.geojson.zip](https://github.com/CartoDB/cartodb/files/417930/3-buf16.geojson.zip)
[3-buf16.mvt.zip](https://github.com/CartoDB/cartodb/files/417931/3-buf16.mvt.zip)

**Comment by jaakla** [comment]
We have pending issue with major customer https://cartodb.supportbee.com/tickets/13751161 (too much traffic for endusers, they claim 100MB sessions), where the root issue seems to be too big vector tiles. As workaround they now change vector-based client to raster ones (+utfgrid for interactions), but this does not look visually good with intermediate zoom levels. Maybe this is reasonable final solution, but I’d like to try to understand why there is so much traffic first.

Attached is screenshot of the biggest vector tile I got, with added tile boundaries, so you see the buffer. It seems that buffer (which is not really used of needed at least for mobile) contributes to the tile size a lot. Probably tile would be significantly smaller (and also faster) with 0-buffer. 
![vectortile-lgi-6-33-21](https://user-images.githubusercontent.com/5609650/30309147-5ad04d24-9792-11e7-82e6-1440863a34ab.png)

What is current state in Engine/Maps API with this: is there still buffer, just 64 pix? Is there plan to remove it altogether, or make it configurable?

Traffic saving with Charles proxy: https://drive.google.com/open?id=0B3Rm1qU6KnySWXM0b3BTd2M0OUE for details. I created small session and got about 13MB traffic from this map: 8MB from user data and 5MB from basemaps. I would wild guess no more than ~10% added traffic for overlays, as basemap should be always much richer than user data?

Also they seem to have too many attributes in vector tiles, and this creates bloat. I guess I cannot fix this with custom SQL, as overviews which are needed for the dataset (over 10M points) would not work then, right?

**Comment by rochoa** [comment]
@jaakla, are you instantiating the maps or are you using fixed URLs of named maps?

Two or three months ago we released a new version of Maps API that allows you to tune the buffer-size per format, see https://github.com/CartoDB/Windshaft-cartodb/issues/673.

An example with a Named Map:

```shell
curl -s -X POST -H 'Content-Type: application/json' -d '{}' https://rochoa.carto.com/api/v1/map/named/tpl_bd4c9677_b500_47a2_8a94_a325b9658cd7 | jq '@text "http://rochoa.carto.com/api/v1/map/\(.layergroupid)/1/2/1/0.mvt"' | xargs curl -s | wc -c
   26321
```

vs

```shell
curl -s -X POST -H 'Content-Type: application/json' -d '{"buffersize": {"mvt": 0}}' https://rochoa.carto.com/api/v1/map/named/tpl_bd4c9677_b500_47a2_8a94_a325b9658cd7 | jq '@text "http://rochoa.carto.com/api/v1/map/\(.layergroupid)/1/2/1/0.mvt"' | xargs curl -s | wc -c
    3848
```

**Comment by jaakla** [comment]
Yep, this seems to work and fix it for most cases. In some cases map may need different buffers based on layers or object types (bigger for roads, smaller for points etc), but in most cases there is one key data layer. Thank you!
