### ISSUE TITLE
Fill component improvements

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#7910]
- [x] For the panel `color` > `By value` we shouldn't show several columns like: the_geom, the_geom_webmercator,...
- [x] Only show number columns in the `size` > `By value` panel.
- [x] When user selects `Size` > `By value`, it should not go to quantification panel, it should select one by default (or leave what it was selected) and go to `MIN-MAX` state/panel.

cc @javisantana because I don't know if you have done any of those.

🇪🇸

**Comment by javierarce** [comment]
Another improvement related to this component: https://github.com/CartoDB/cartodb/issues/7850 (but since it's a bigger ticket, I'll do it in another branch)

**Comment by javierarce** [comment]
- [x] Fixes capitalization of the quantification name in the value dialog.
