### ISSUE TITLE
When an analysis is removed or added, infowindow and tooltip models should clear their fields

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#7915]
cc @javierarce @matallo

**Comment by viddo** [comment]
This is related to #7881, layer changes should be persisted together with the node, need to investigate a little bit…

**Comment by ramiroaznar** [comment]
I think we can close this issue. The fields are clear, but the infowindow is maintained.

**Comment by alrocar** [comment]
Stale issue. Closing 👋
