### ISSUE TITLE
If you hide a layer in the builder, it is showed in the public embed

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#7918]
Also, eye icon is not centered @piensaenpixel.

**Comment by alonsogarciapablo** [comment]
This seems like an issue in Windshaft-cartodb. See https://github.com/CartoDB/Windshaft-cartodb/issues/524

**Comment by rochoa** [comment]
This is most likely due the fact that the layer no longer has a `sql` but a `source.id` and it is not using the `WHERE 1 = <%= layer0 %>` template item.

**Comment by alonsogarciapablo** [comment]
@rochoa That was my guessing... How can we solve it then? Can we implement something in Windshaft-CartoDB to specify the visibility of a layer properly instead of using the `WHERE 1 = <%= layer0 %>` hack?

**Comment by rochoa** [comment]
The best way I know to hide a layer is to not send the layer in the first place 😈 .

For anonymous maps is quite straightforward, for named maps I guess the builder could save the internal models for the layers but send in the named map just the visible layers.

cc @javisantana

**Comment by alonsogarciapablo** [comment]
> for named maps I guess the builder could save the internal models for the layers but send in the named map just the visible layers.

That could work but then it would be impossible to show/hide layers from an standalone CartoDB.js app...

**Comment by rochoa** [comment]
That's why I went 😈 .

To be able to hide layers we will need to address this limitation https://github.com/CartoDB/Windshaft/issues/477. So layer filtering works as expected for mapnik layers.

**Comment by gfiorav** [comment]
I'm all ears for changing what is needed in the backend. Keep me posted

**Comment by xavijam** [comment]
@alonsogarciapablo already fixed?

**Comment by alonsogarciapablo** [comment]
No, we decided to postpone this... remember? This requires some changes in Windshaft-CartoDB first...

**Comment by xavijam** [comment]
True!

**Comment by xavijam** [comment]
It will be tackle when https://github.com/CartoDB/Windshaft-cartodb/issues/550 is done.

**Comment by alonsogarciapablo** [comment]
Done!
