### ISSUE TITLE
Error tooltip appears in a wrong place in the analysis form

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#7923]
![image](https://cloud.githubusercontent.com/assets/1214201/16372019/8b87ca90-3c4a-11e6-9e6d-818fe69f727b.png)

CC: @xavijam

**Comment by xavijam** [comment]
yay! thanks for reporting 👏

**Comment by javierarce** [comment]
This problem seems to be related to the radio button fields.
