### ISSUE TITLE
When deleting layer should move the layer's analyses to another layer that belongs on them

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#7926]
E.g. if having layer A with analyses A1->A0 and a layer B with analyses B1->A1, and deleting layer A should _not_ delete analyses A1 and A0 but move them (change ids) to be owned by layer B instead.

Right now all dependent analyses and layers are just deleted, which could lead to the inconsistent state of _all_ layers being removed.

Related to [earlier conversation on #7878](https://github.com/CartoDB/cartodb/pull/7878#issuecomment-226741582)

cc @alonsogarciapablo

**Comment by saleiva** [comment]
Right now it's removing all the related layers which is very destructive.

**Comment by viddo** [comment]
This bill resolved by #7881, in the way that if nodes can be folded under another they will (typically if they're primary source). Layers' with dependent secondary sources (for analysis that have those, e.g. intersection, point-in-polygon etc.) that can't be represented will still be deleted in cascade.

**Comment by viddo** [comment]
Related to #8253 though, the user won't be able/allowed to delete a layer that all layers depends on in some way.

**Comment by viddo** [comment]
Closing, since solved in #8042
