### ISSUE TITLE
I miss "CLEAR QUERY/VIEW" button in the new sql editor

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#7941]
Like we do in the current one:

<img width="263" alt="screen shot 2016-06-20 at 10 28 55" src="https://cloud.githubusercontent.com/assets/132146/16187654/d6a1141a-36d1-11e6-8f23-9e8ef61569fd.png">

Don't you @nobuti @urbanphes @saleiva ?

**Comment by saleiva** [comment]
AFAIK this is on the main loader, right?

2016-06-20 10:29 GMT+02:00 Javier Álvarez Medina <notifications@github.com>:

> Like we do in the current one:
>
> [image: screen shot 2016-06-20 at 10 28 55]
> <https://cloud.githubusercontent.com/assets/132146/16187654/d6a1141a-36d1-11e6-8f23-9e8ef61569fd.png>
>
> Don't you @nobuti <https://github.com/nobuti> @urbanphes
> <https://github.com/urbanphes> @saleiva <https://github.com/saleiva> ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/7941>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAIENa-gEAFNfnQM29zkxLrS2LHe6emUks5qNk98gaJpZM4I5d9X>
> .
>



-- 
Sergio Alvarez Leiva

**Comment by urbanphes** [comment]
When we have a query applied we have the button to clear.

![image](https://cloud.githubusercontent.com/assets/14546701/16192952/7c6afe46-36ec-11e6-8398-2fc3e8efa1cf.png)

**Comment by xavijam** [comment]
Ok, then I guess undo-redo buttons are close to the clear button ;). @nobuti could you take care of this?

**Comment by saleiva** [comment]
@urbanphes but then the undo/redo?

**Comment by urbanphes** [comment]
I thought that this version we couldn't integrate the undo/redo buttons. In that case the clear button disappears and show the undo/redo.

![image](https://cloud.githubusercontent.com/assets/14546701/16196104/d8d3e1f6-36fc-11e6-8ec0-35dd7fdf4fc3.png)

**Comment by saleiva** [comment]
But them the clear is simply pressing in undo?

2016-06-20 15:38 GMT+02:00 Juanma <notifications@github.com>:

> I thought that this version we couldn't integrate the undo/redo buttons.
> In that case the clear button disappears and show the undo/redo.
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/14546701/16196104/d8d3e1f6-36fc-11e6-8ec0-35dd7fdf4fc3.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/7941#issuecomment-227144246>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAIENXRvfkf2ie5XpAH4AsCV_FiX3DZcks5qNpfZgaJpZM4I5d9X>
> .
>



-- 
Sergio Alvarez Leiva

**Comment by urbanphes** [comment]
Yes it is, in my opinion

**Comment by saleiva** [comment]
Than that would imply that you apply a query automatically without pressing
the button,... and that's dangerous IMHO. Imagine clicking 10 times on undo.

2016-06-20 15:48 GMT+02:00 Juanma <notifications@github.com>:

> Yes it is, in my opinion
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/7941#issuecomment-227146995>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAIENQ9IEKSdkdteyQ8iST8RtwEqtrEzks5qNpo_gaJpZM4I5d9X>
> .
>



-- 
Sergio Alvarez Leiva

**Comment by xavijam** [comment]
Agree with @saleiva, a bit dangerous. Let's add the clear button, is there any problem with that?

**Comment by urbanphes** [comment]
No problem but only 2 buttons. "Clear" and "Apply"

**Comment by xavijam** [comment]
Undo, redo, clear and apply, come on @urbanphes!

**Comment by urbanphes** [comment]
Here the footer bar <br>
![image](https://cloud.githubusercontent.com/assets/14546701/16297717/4c289d72-3932-11e6-91c7-44c245bc5670.png)
