### ISSUE TITLE
[TABLE] Widgets get below the table

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#7943]

**Comment by xavijam** [comment]
It is due the way we have to show the table, not about a css problem.

**Comment by xavijam** [comment]
And the question is, should it be close to the widgets? or should we remove map and widgets and show only the map? Because widgets belong to the map...

**Comment by saleiva** [comment]
The thing is that sometimes could be useful, but not always. Ill need a bit
more time to think on it
