### ISSUE TITLE
[STYLE] Category configuration popup modal is not being refreshed when changing the number of categories

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#7945]
Create a map with point data.
Apply a cluster analysis with 3 clusters.
Apply style by cluster_no.
Go back to the analysis view and change the number of clusters
Go back to styling. 

There should change the number of catetories but it's not changing right now.

**Comment by xavijam** [comment]
Right now, style changes if number of clusters changes, but it is not possible to change automatically the buckets chosen in the style tab. Not sure if I've understood what you propose @saleiva.
