### ISSUE TITLE
New editor data tab not scrolling in Firefox

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#7946]
The data tab doesn't display scroll in Firefox (works fine on chromium), instead, it overflows and shows both horizontal and vertical scrollbars:

![screenshot_20160620_120307](https://cloud.githubusercontent.com/assets/7569673/16190401/66a68ed4-36df-11e6-9193-18b236bd7692.png)

No errors on JS console.

cc @xavijam

**Comment by xavijam** [comment]
cc @nobuti :|
