### ISSUE TITLE
wrong labels

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#7947]
If i change the basemaps, labels don't change.

![image](https://cloud.githubusercontent.com/assets/1214201/16190809/7c70741c-36e1-11e6-85d8-8546ec0221b4.png)

**Comment by matallo** [comment]
can't reproduce

![basemapsbug](https://cloud.githubusercontent.com/assets/36676/16191151/1f8e8200-36e3-11e6-9b05-ec74b05dc697.gif)
