### ISSUE TITLE
strange behavior in basemaps

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#7949]
if you change sometimes between differents basemaps, this doesn't work very well

![basemap](https://cloud.githubusercontent.com/assets/1214201/16191590/4d03fd4e-36e5-11e6-8000-83c8fd2724f3.gif)

![image](https://cloud.githubusercontent.com/assets/1214201/16191621/7e2a78f8-36e5-11e6-835b-4136776a17f8.png)

**Comment by matallo** [comment]
this has already been discussed in https://github.com/CartoDB/cartodb/pull/7722#issuecomment-224697176 and created the corresponding issue https://github.com/CartoDB/cartodb/issues/7743

we'll disable the basemaps panel until the labels layer is saved to prevent that behaviour

wip in the next PR https://github.com/CartoDB/cartodb/pull/7836

duplicated, closing then
