### ISSUE TITLE
Country Name Geocoding: Add Additional Name, Republic of the Congo

### ISSUE THREAD

**Issue by michellechandra** [CartoDB/cartodb#7960]
## Context
A user with government datasets is having difficulties manually geocoding a dataset by country names as the dataset uses "Republic of **the** Congo" while the geocoder recognizes: 

_Democratic Republic of the Congo,COD,Dem. Rep. Congo,CD
Republic of Congo,COG,Congo,CG_

Would it be possible to add an additional alias to the geocoder to also recognize "Republic of the Congo" as a valid country name option for Congo?

S/B: 9219427

**Comment by rafatower** [comment]
Issue moved to [CartoDB/data-services #216](https://github.com/CartoDB/data-services/issues/216) via [**ZenHub**](https://www.zenhub.com/)
