### ISSUE TITLE
Layers are not ordered correctly after adding a new layer and reloading the page :(

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#7970]
**Steps to reproduce:**
- Create a map with one layer.
- Click the Add button.
- Select one dataset and add it as a layer.
- Everything should look fine at this point (new layer is below the Labels layer).
- Reload the map.

**Expected results**
- Order of layers is persisted correctly and doesn't change when reloading the page.

**Actual results:**
- New layer appears above the labels layers.

cc: @xavijam @viddo

**Comment by alonsogarciapablo** [comment]
The problem here is that the new order of the layer that was on top (labels) is not being persisted. [This code](https://github.com/CartoDB/cartodb/blob/66a6726c7611728c9bed977255b4f9dbcd308273/lib/assets/javascripts/cartodb3/data/layer-definitions-collection.js#L183-L185) should supposedly save that layer. But right after the new layer model is created, [orders are being reset](https://github.com/CartoDB/cartodb/blob/66a6726c7611728c9bed977255b4f9dbcd308273/lib/assets/javascripts/cartodb3/data/layer-definitions-collection.js#L65-L67) and layer on top has no changes cause "orders" were right before re-setting them.

**Comment by viddo** [comment]
Good catch… it's yet another issue of these implicit side-effects, I'm tacking this in #7881 (reassigning to myself)

**Comment by viddo** [comment]
Reassigning since @alonsogarciapablo is working on this, we have talked offline and identified the problem

**Comment by alonsogarciapablo** [comment]
I'm happy to work on this, but it's not the same as https://github.com/CartoDB/cartodb/issues/8245 @viddo

**Comment by viddo** [comment]
Oh, my bad then, reassigning back…
