### ISSUE TITLE
Add Intersection analysis

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#7979]
![screen shot 2016-06-21 at 09 59 56](https://cloud.githubusercontent.com/assets/4933/16222093/a91d309e-3796-11e6-9968-ec39f73ecf90.png)

![screen shot 2016-06-21 at 10 00 09](https://cloud.githubusercontent.com/assets/4933/16222094/a9230eba-3796-11e6-831b-ce1c07ab9f32.png)

**Comment by saleiva** [comment]
:_)))
