### ISSUE TITLE
Infowindow attributes don't show properly with a hidden layer

### ISSUE THREAD

**Issue by zenitraM** [CartoDB/cartodb#7983]
Steps to reproduce:
- Have a viz with two layers with different datasets / column names
- Enable infowindows on both layers
- Hide layer 1
- Try to see the infowindow of the enabled layer 2 on the embed map

It shows "No data available", however the attributes call to the map api fetches the attributes, it seems like it is using the fields from the hidden layer.

(see related issue)

**Comment by ramiroaznar** [comment]
This has already been fixed!
