### ISSUE TITLE
Notifier missing events

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#7985]
Above you can find a first batch of events that should be happening on the Notifier:

- [ ] Appliying query (progress indicator)
- [x] Query applied (check)
- [x] Error in query (error)
- [x] CartoCSS applied (check 10s)
- [x] Error in CartoCSS (error)
- [x] Layer added (check 10s)
- [x] Layer deleted (check 10s)
- [x] Importing file (progress)
- [x] First time add some widget (loader)

- [x] Map instantiation error.
- [x] Analysis enqued
- [x] Analysis in progress (progress)
- [x] Analysis finished
- [x] Analysis error (error)
- [x] TurboCartoCSS error. <- These are displayed in the cartocss editor

@urbanphes missing anyone else?

cc/ @xavijam

**Comment by xavijam** [comment]
Commenting:

- Applying query: not possible to know progress right now, and I don't know if we provide progress with batch API, for the future (@dgaubert @rochoa).
- Query applied: 🆗 
- Error in query: 🆗 
- Analysis in progress: we already have the analysis loader, do we need anything else?

**Comment by rochoa** [comment]
> Applying query: not possible to know progress right now, and I don't know if we provide progress with batch API, for the future (@dgaubert @rochoa).
How is that related to Batch API?

**Comment by xavijam** [comment]
1. In case we decide to apply queries with batch api from the builder in the future (no idea if makes sense or not).
2. Yeah yeah, but we have those errors over the nodes in the UI, not sure if we need to show them in the notifier.

**Comment by dgaubert** [comment]
From Batch API side, it isn't possible to return a progress status, at least, at query level. We can know, how many queries are done and how many are left for any job, but we don't know the cost of each query.

**Comment by saleiva** [comment]
status feedback is never too much, let's add it also to the analysis
progress @xavijam

2016-07-04 11:45 GMT+02:00 Daniel <notifications@github.com>:

> From Batch API side, it isn't possible to return a progress status, at
> least, at query level. We can know, how many queries are done and how many
> are left for any job, but we don't know the cost of each query.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/7985#issuecomment-230250441>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAIENQtVZM4ThLYFUghlRBIwxviebqkTks5qSNYxgaJpZM4I6k2v>
> .
>



-- 
Sergio Alvarez Leiva

**Comment by alonsogarciapablo** [comment]
There's only one item missing in this issue:

- [ ] Appliying query (progress indicator)

AFAIK, we can't do this right now, as Windshaft doesn't give us any progress while the query is being applied...

**Comment by rochoa** [comment]
What "Applying query" does mean?

**Comment by alonsogarciapablo** [comment]
> What "Applying query" does mean?

I don't know!

Closing this issue for now. @saleiva feel free to re-open it if you think ☝️ is important.

**Comment by saleiva** [comment]
In the editor, when a query is loading, we show that. It's just that. Some queries can last seconds or even minutes, we should say somewhere that we are processing it.

**Comment by alonsogarciapablo** [comment]
So it should just show a "loading" notification when the sql of a layer has been changed and remove that notification when the map has been finally refreshed? Something like "Your query is being applied"? Thx

**Comment by xavijam** [comment]
Yeah
