### ISSUE TITLE
Check import behaviour when a user reaches the limit on named map templates

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#7986]
Previously, we were detecting the `409` error which was explicitly returned from the Maps API when the limit on named map templates was reached.

See:
- https://github.com/CartoDB/cartodb/pull/6315
- https://github.com/CartoDB/Windshaft-cartodb/pull/356

With the current changes in `cartodb/cartodb` regarding Named Maps, the treatment of the exception that was setting an appropriate import error was removed. See import code error documentation [here (look for 6670)](https://docs.cartodb.com/cartodb-platform/import-api/import-errors/).

I'm opening this issue to review/discuss the current status of an import process whenever the user reaches the maximum of named map templates.

cc @gfiorav

**Comment by gfiorav** [comment]
I completely missed the part where we had a specific code for this! 

Let's convey a specific raise for this and I'll make the api throw it up to you :)

**Comment by iriberri** [comment]
I created previously `CartoDB::NamedMapsWrapper::TooManyTemplatesError`, so if you want you can use something similar :-) I don't really mind!

**Comment by gfiorav** [comment]
Yup, I remember `CartoDB::NamedMapsWrapper::TooManyTemplatesError` :)

I might bring it back, shouldn't have killed it. My bad!
