### ISSUE TITLE
[STYLE] Buckets are always 3 by default and they shouldn't

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#7990]
If we are not able to calculate the correct number of buckets, I'd suggest we start with at least 5 by default. 3 are too little.

**Comment by xavijam** [comment]
In the fill component?

**Comment by saleiva** [comment]
in everyone

**Comment by ramiroaznar** [comment]
AFAIK, BUILDER has 5 buckets as default. Should we close it then?
