### ISSUE TITLE
Maps API error when aggregating points in squares

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#7992]
Create a maps with a point dataset.
Aggregate by squares.
Color by value with point_density

tracker.js:10 Request to Maps API failed: Unknown error

**Comment by rochoa** [comment]
Can you check again. We did release some improvements for those queries.

**Comment by saleiva** [comment]
works like a :charm:. the UI is just a bit slow reacting but I think we are already trying to fix that. Thanks!
