### ISSUE TITLE
Aggregated value column is not generated when aggregating by squares, hexabins or admin region

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#7993]
Create a map with a point dataset
Aggregate the points with any option
Change COUNT to SUM(value)

The resulting column doesn't appear on the column dropdown

**Comment by javisantana** [comment]
this is actually a design/naming issue: when we do an aggregation there are two outputs:

points_count: contains the count, sum or whatever 
points_density: it's the points_count/area

so should he change to points_agg and points_agg_density instead of points_count?

**Comment by saleiva** [comment]
uhm... would it be very difficult to get then the column name and attach _sum/_avg/_etc?
then when calculating the amount of population within a country for example we would have pop_max_sum and pop_max_sum_density

**Comment by javisantana** [comment]
maybe not, let me try. The problem is to have a consistent cartocss no matter what the aggregation is

**Comment by saleiva** [comment]
that is true but at the same time it's not explanatory.
Let me know if we cannot do that in that way, so we think on better
literals.

2016-06-21 14:01 GMT+02:00 javi santana <notifications@github.com>:

> maybe not, let me try. The problem is to have a consistent cartocss no
> matter what the aggregation is
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/7993#issuecomment-227419114>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAIENfoqMTF_avfsDj5_lEhvkbKW5GPXks5qN9KjgaJpZM4I6m1u>
> .
>



-- 
Sergio Alvarez Leiva

**Comment by javisantana** [comment]
Aggregations were not working but the name is hard to change right now? should we keep points_agg  and points_agg_density for the moment?

**Comment by saleiva** [comment]
shit...

Then could we go with

agg_value
agg_value_density?

**Comment by javisantana** [comment]
yes
