### ISSUE TITLE
[POPUP] When selecting a light color on the color header popup text over that area should be in positive.

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#7999]

**Comment by matallo** [comment]
hey hey, where should I find the designs for this? /cc @piensaenpixel

**Comment by piensaenpixel** [comment]
@alonsogarciapablo i think this can be very useful
cc @ramiroaznar

**Comment by ramiroaznar** [comment]
Can I get a mockup? I don't understand the issue.

**Comment by piensaenpixel** [comment]
really we don't need a mockup, the idea is that if the background-color that the user selects is soft we should change the text to dark.

But it's something like this

![image](https://user-images.githubusercontent.com/1214201/36537269-ed901b68-17cf-11e8-9405-796ee3fd3421.png)

**Comment by alonsogarciapablo** [comment]
How would you implement this @piensaenpixel? Is this something that you guys (design) would be able to change?

**Comment by piensaenpixel** [comment]
What do you mean @alonsogarciapablo ?

**Comment by alonsogarciapablo** [comment]
Given that users can select any color as a background for the popup... how can we know when to use a light or dark font color?

**Comment by piensaenpixel** [comment]
We need to detect the luminance/brightness of the background-color in js and then change it.

**Comment by piensaenpixel** [comment]
Take a look, you can change the bg color, that's the idea.

' <div class="subject-icon" style="background-color: rgb(0, 0, 0);"> ' 

[test.html.zip](https://github.com/CartoDB/cartodb/files/1751689/test.html.zip)

**Comment by alonsogarciapablo** [comment]
Something like that might work, yep.

**Comment by alrocar** [comment]
Stale issue. Closing 👋
