### ISSUE TITLE
[WIDGETS] Add option for editing a widget on the ... menu,

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8003]
When clicking on it, the left panel should switch to the editing state of that widget.
#SMOKE_WD07 #SMOKE_WD30 #SMOKE_WD18

**Comment by javisantana** [comment]
hey, there are plenty of issues where the widgets should act as another piece of the editor (not just in the map) so I will try to work on all of them at the same time. 

as far as I can remember:
- this one
- https://github.com/CartoDB/cartodb/issues/9872
- https://github.com/CartoDB/deep-insights.js/issues/452

This is the clear (and one of the worse) examples of lack of comunication between design and tech teams
