### ISSUE TITLE
[STYLE] Resolution for heatmaps is wrong

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8005]
It is 16px by default.
For heatmaps I'd put 4 or even 2 by default.

Also the resolution parameter should be outside the animated option on this aggregation mode.

**Comment by saleiva** [comment]
Prioritizing since heatmaps are barely usable without this.

**Comment by javisantana** [comment]
there is still a bunch of fixed to do for every single style so I'll merge all of them together

**Comment by saleiva** [comment]
Ok, let me know if I can help
