### ISSUE TITLE
[STYLES] Values generated when changing the size by value have too many decimals

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8011]
like for example when styling the portland clients dataset by customer_value

**Comment by xavijam** [comment]
I feel it is an easy one 💋

**Comment by javierarce** [comment]
Shall I go with 2 decimals? 4?

**Comment by javierarce** [comment]
Or maybe just zero, since once you touch the handle of the component you only get rounded numbers.

![screen shot 2016-10-25 at 17 58 37](https://cloud.githubusercontent.com/assets/4933/19693687/b59e6c08-9adc-11e6-8716-2130ee1fd044.png)

**Comment by saleiva** [comment]
ZERO!
