### ISSUE TITLE
don't show download .carto files for maps with all private datasets

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartodb#8014]
For instance, this map has all private datasets but the download .carto image is there. https://datanews.cartodb.com/viz/95e7c398-3702-11e6-bdff-0e8c56e2ffdb/public_map

**Comment by andy-esch** [comment]
I just downloaded that .carto file and imported it into my account. The data didn't go along:

<img width="329" alt="screen shot 2017-10-31 at 08 28 09" src="https://user-images.githubusercontent.com/1041056/32223844-73c532aa-be15-11e7-8044-88e9d8660583.png">

**Comment by ramiroaznar** [comment]
Hey @andy-esch, this is only happening when you download the .carto from the map public page (Editor legacy). If you donwload the map from your account, the dataset is included. I think this is a expected behaviour, what do you think?

**Comment by andy-esch** [comment]
Won't Builder have public pages too?

The behavior I expect is:
If you download a .carto file, you get the complete package (data included). The behavior I'm seeing is that you only get the datasets that aren't set to private. When I download that .carto file and import it into my account, I don't get the data layer -- only the basemap.

**Comment by ramiroaznar** [comment]
Yes, but AFAIK if you are using a private dataset, you do not want viewers to have access to the data... So that's what I was saying that is an expected behavior...

**Comment by andy-esch** [comment]
But we should let the viewer know what they're getting into. Otherwise it's not expected behavior. In the case above there is only one dataset and it is set to private. So why would we offer a download if they won't really get anything other than a base map and some metadata about the original map?

**Comment by ramiroaznar** [comment]
Yes, totally agree. I realize that's the point of your issue. :-)

**Comment by noguerol** [comment]
Certainly a bug, but not to be fixed because user pages are not a priority and will probably be deprecated soon.
