### ISSUE TITLE
hotspot, coldspot, and anomaly analysis

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/cartodb#8016]
## Hotspots -- areas with consistently high values

__Use [CDB_GetSpatialHotspot()](https://github.com/CartoDB/crankshaft/blob/develop/src/pg/sql/10_moran.sql#L54-L70) function__

Description: Find clusters with consistently high values. These are areas that are spatially correlated with the places around it. The smaller the significance value, the more robust the correlation.

## Anomalies -- places with values that stand out from those around them

__Use [CDB_GetSpatialOutliers()](https://github.com/CartoDB/crankshaft/blob/01fc2c1dd1087e58679cc2728ee88a0df5702ea6/src/pg/sql/10_moran.sql#L92-L108) function__

Description: Find areas which stand out compared to their neighbors. These are places that are spatially anti-correlated with the places around it. Anomalies are hotspots situated next to cold spots, or vice versa.

## Coldspots -- areas with consistently low values

__Use [CDB_GetSpatialColdspots()](https://github.com/CartoDB/crankshaft/blob/01fc2c1dd1087e58679cc2728ee88a0df5702ea6/src/pg/sql/10_moran.sql#L73-L89) function__

Description: Find clusters with consistently low values. These are areas that are spatially correlated with the places around it. The smaller the significance value, the more robust the correlation.

cc @andrewxhill

**Comment by saleiva** [comment]
Very interesting one for making morans more accesible. cc/ @rochoa @javisantana

**Comment by andrewxhill** [comment]
Looking good. In the Builder Interface, I would suggest we add the verbal
nouns,

Hotspot Detection
Coldspot Detection
Anomaly Detection

**Comment by ohasselblad** [comment]
Btw, each of the functions above has a `...Local()` version (e.g., [this one](CDB_GetSpatialColdspotsRate)) that accepts a denominator as well as a numerator.

**Comment by saleiva** [comment]
Duplicated! Already being implemented!
