### ISSUE TITLE
[STYLE] Aggregation by country column result is missleading

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8028]
Aggregate by country a point dataset
Click on coloring by value

There is only a resulting column called point_agg that looks to be normalized even tho the name doesn't says that. 

The resulting columns should be like in the other wizards
- not normalized
- normalized by area

**Comment by javisantana** [comment]
I think this is fixed using the two variables (normalized and not)

**Comment by ramiroaznar** [comment]
Fixed. The Adm. Regions aggregation method now returns `agg_value_density` (default) and `agg_value`.
