### ISSUE TITLE
hold down shift to select multiple datasets in the dashboard

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartodb#8032]
Just like in os x's finder or gmail, clicking an item, holding down shift, and clicking another item will select all items between the two.

it'd be a nice usability add :)

**Comment by andy-esch** [comment]
cc @CartoDB/design to me this is a nice UX / speed gain.

**Comment by piensaenpixel** [comment]
Same here, totally agree! We'll think about it.
Thanks!
