### ISSUE TITLE
stats issues

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#8038]
* [x] histograms should be normalized
* [x] boolean should not show "100.00% IN TOP 10 CAT" since there are only 3 possible values
* [x] histogram does not match somtimes (see bathroms in image, check accommodates as well), the dataset is here https://team.cartodb.com/u/saleiva/tables/
* [x] some columns are duplicated, for example `number_of_reviews` appears twice in the data panel

![screen shot 2016-06-22 at 11 43 24 am](https://cloud.githubusercontent.com/assets/30147/16262187/dbe98350-386e-11e6-9e1c-10260bbe62d3.png)

cc @nobuti

**Comment by nobuti** [comment]
Last item is fixed in https://github.com/CartoDB/cartodb/pull/8044
