### ISSUE TITLE
[POPUPS] Hover popups doesn't work on embed map

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8040]
Create a map with hover popups
Test it in an incognito window.

**Comment by saleiva** [comment]
still happening 
https://team.cartodb.com/u/saleiva/builder/a6a1bc2e-385c-11e6-8e79-0e3ff518bd15/embed

**Comment by matallo** [comment]
this is likely a backend issue related to named maps, reassigning to @gfiorav
