### ISSUE TITLE
Allow selecting category colors from a predefined list

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8041]
Looks like there is no place to select a default color set

cc/ @javierarce

**Comment by urbanphes** [comment]
This is the flow 

![image](https://cloud.githubusercontent.com/assets/14546701/16301603/7875b77a-3946-11e6-8581-913e0f66f25d.png)

and this is the custom

![image](https://cloud.githubusercontent.com/assets/14546701/16301632/a67229e2-3946-11e6-9ca3-35eb16e50411.png)

**Comment by saleiva** [comment]
remmember the change from the switch to category as an item in the quantificatino dropdown

**Comment by urbanphes** [comment]
I'm going to update the mockups

![image](https://cloud.githubusercontent.com/assets/14546701/16445890/30c5d196-3de5-11e6-8947-141cc9184da8.png)

![image](https://cloud.githubusercontent.com/assets/14546701/16445917/4f961f54-3de5-11e6-94d2-16cd7ab90f05.png)

**Comment by xavijam** [comment]
Ha!, I didn't know about this, looks cool.
