### ISSUE TITLE
Review connect with lines analysis

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb#8043]
Use case:

1. Calculate kmeans.
1. Calculate weighted-centroid for those kmeans.
1. Connect with lines the kmeans points with calculated centroids by cluster number.

**Comment by saleiva** [comment]
Updated in invision, ping me whenever you wanna take a look

cc/ @javierarce @javisantana

**Comment by saleiva** [comment]
also, updated the calculate paths GUI

**Comment by javisantana** [comment]
what is "mode" in the design?

**Comment by saleiva** [comment]
That's being updated. It's only present on the calculate paths GUI (which
is almost the same) so you can switch between driving and walking for
example

2016-06-22 14:08 GMT+02:00 javi santana <notifications@github.com>:

> what is "mode" in the design?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/8043#issuecomment-227723606>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAIENbVN8SWVLObkfAyoEBudDsqCngCPks5qOSWggaJpZM4I7otq>
> .
>



-- 
Sergio Alvarez Leiva
