### ISSUE TITLE
[popup] integration not working when checking hover fields

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#8048]
**str**

- create map
- add points
- go to popup
- check fields in "hover"

**expected behaviour**

- tooltip should work with fields checked

**actual behaviour**

- tooltip won't work

this seems related to cartodb.js, as it doesn't happen with popup "click"; actually if I changed tab and checked/unchecked "click" fields, interactivity starts working so does tooltips

it would also work when having some field checked in popup "hover" on window load

/cc @alonsogarciapablo

**Comment by saleiva** [comment]
After refreshing the page, you can hide fields but new ones are not added dynamically.

**Comment by matallo** [comment]
can't reproduce

![hoverpopups](https://cloud.githubusercontent.com/assets/36676/16446096/2fb89c24-3de6-11e6-952b-96c391e080b2.gif)
