### ISSUE TITLE
Be able to stop an analysis that is taking too long

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8052]
From the notifier, we should be able to stop an analysis that is taking too long.
This is more and more important since I'm loading more and more my account :)

cc/ @javisantana @nobuti @xavijam

**Comment by xavijam** [comment]
First we should ask @rochoa and @dgaubert if that is possible in the Maps API.

**Comment by javisantana** [comment]
cada_de_pandora.gif

**Comment by ramiroaznar** [comment]
This is already implemented (DELETE button), right? @noguerol

**Comment by xavijam** [comment]
Not really. One thing is remove the analysis, but it doesn't stop it behind the scenes. I'd not close it.

**Comment by ramiroaznar** [comment]
I see. Thanks!

**Comment by noguerol** [comment]
This is a thing to handle with the  more in depth analysis changes that have been already been discussed. Blocked until those are prioritized.

**Comment by alrocar** [comment]
Stale issue. Closing 👋
