### ISSUE TITLE
[WIDGETS] Should  be possible to add category widgets using numeric columns with a few values

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8059]
As a workaround, you can switch the widget type on the builder, but...
To replicate

Connect this dataset -> https://team.cartodb.com/u/saleiva/tables/customer_home_locations/public
Do a Cluster
Try to add a widget by cluster_no

**Comment by xavijam** [comment]
That would force us to use style wrap query in the query schema model, what do you think @javisantana ?

**Comment by javisantana** [comment]
the thing is, how do we know we can do it without crashing the database?

As we don't have a way to do it I'd enable for all of the values, then we could play a little bit with the stats when possible.

**Comment by javisantana** [comment]
(and the end the user can choose, right?)

**Comment by saleiva** [comment]
We could enable this only when having >70% in TOP 10 categories, for example.

**Comment by javisantana** [comment]
Yes we could but:

- in some cases stats are not there
- stats are a view only thing right now and totally async, doing that would require some days of work so I'd say let's enable for every single column and then use the stats when we have more time

**Comment by saleiva** [comment]
well, that would make category widgets very hard to add since we will have tons of columns on the modal... but if it's an easy change, I'm happy to try

**Comment by inigomedina** [comment]
I'm closing this issue because it has been inactive for a long time. This probably means that it is not reproducible or it has been fixed in a newer version. If it's an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue.

Thank you!
