### ISSUE TITLE
[DESIGN] Hidden layer

### ISSUE THREAD

**Issue by urbanphes** [CartoDB/cartodb#8064]
Make a reference (visual) when a layer is hidden

**Comment by urbanphes** [comment]
When the layer is hidden we show infobox and the rest of the content disabled.

![01 layers - 02-23 style](https://cloud.githubusercontent.com/assets/14546701/16274733/2a096360-38a7-11e6-8070-c6fff60fd1bb.png)

cc @saleiva

**Comment by xavijam** [comment]
Already opened -> https://github.com/CartoDB/cartodb/issues/7895. Closing.

**Comment by nobuti** [comment]
@saleiva @urbanphes does the infobox remain when the user changes to the cartocss editor?

**Comment by saleiva** [comment]
Nope
