### ISSUE TITLE
Change the way Builder feature flag works

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8070]
Since we are enabling this to the whole org now, we should make the feature flag to change the URL linked from the dashboard, so we avoid people to have to change the URL by hand.

**Comment by xavijam** [comment]
- Add a user switch (migration needed, let's called it as @javitonino has suggested *builder_enabled*) if the feature flag is enabled ( @urbanphes, where should it be placed? ).
- If the switch is enabled (new builder yes):
  - viz (map) should go to bulider.
  - table should go to *dataset*, no matter if it is emptied for now.
- If an organization owner has the feature flag enabled, option chosen will be enabled for the rest of the organization.

**Comment by javitonino** [comment]
Finally, we are changing the behaviour so it is user-based, not organization based, so different users in the organization can use different editors. This is motivated by the `team` organization, where we will want different settings for different users (specially for devs).

We will keep the feature flag at the organization level, so it is easier to enable it.
