### ISSUE TITLE
builder notifier: queued importing maps appearing in map view

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#8073]
**str**

- import `.carto`
- go to whatever map

**expected behaviour**

- queued imports should only appear in dashboard

**actual behaviour**

- queued imports appear in mapview

![screen shot 2016-06-22 at 18 39 16](https://cloud.githubusercontent.com/assets/36676/16275082/c7793746-38a8-11e6-8857-d8a9524eaeed.png)

**Comment by nobuti** [comment]
Closed by #8538
