### ISSUE TITLE
Implement centroid analysis

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8074]
![screen shot 2016-06-22 at 18 56 00](https://cloud.githubusercontent.com/assets/132149/16275627/1bbd5bf0-38ab-11e6-859a-952f022b9312.png)

rel: https://github.com/CartoDB/camshaft/issues/77

**Comment by javierarce** [comment]
I've changed the description of this issue, since the centroid form wasn't implemented. 
I'll also address here this bug: https://github.com/CartoDB/cartodb/issues/8243
