### ISSUE TITLE
Allow specifying field separator for CSV/TXT imports

### ISSUE THREAD

**Issue by strk** [CartoDB/cartodb#8097]
I have CSV files using ``|`` as separator, but cartodb importer doesn't ask me anything about that and always assumes comma as a separator (even if the file is renamed to .txt, for example).

It would be useful to be able to specify more about interpretation of uploads (like when opening a txt file in a spreadshit, for example)

**Comment by iriberri** [comment]
Adding here a reference to the code for myself:

https://github.com/CartoDB/cartodb/blob/119a277c366e5054a8802307ac36eb67d4b12433/services/importer/lib/importer/csv_normalizer.rb#L17

**Comment by strk** [comment]
Well, technically the commit does not allow to specify a field separator. But yes, it fixes my specific case.
