### ISSUE TITLE
Allow using date column for chorophlet, bubbles and other numeric-based styles

### ISSUE THREAD

**Issue by strk** [CartoDB/cartodb#8099]
I wanted to show points thematized with their age, but the map editor doesn't let me pick a date column for a bubble or chorophlet field, it would be useful to allow that. The field could be dynamically converted to numeric (an epoch?).

**Comment by iriberri** [comment]
That bar stands for the monthly geocoding quota you have (left) for the paid geocoding option (street addresses).

**Comment by strk** [comment]
Wrong ticket :)

**Comment by strk** [comment]
Your comment https://github.com/CartoDB/cartodb/issues/8099#issuecomment-228036919 was likely for #8101

**Comment by ramiroaznar** [comment]
Sorry, but [we decided to remove the date columns from style by value options](https://github.com/CartoDB/cartodb/issues/7873).
