### ISSUE TITLE
Editing a date field drops the 00:00:00Z suffix

### ISSUE THREAD

**Issue by strk** [CartoDB/cartodb#8100]
The CSV importer figured out a field was a date (2015-05-03) and created the table accordingly.
When viewing the data, that value is shown as `2015-05-03T00:00:00Z`.
On double-clicking on the value I get prompted to edit the value, but even if I don't touch anything but only hit "Save" I end up with something rendered as `2015-05-03`.

I'm actually happy with the reduced display as my data doesn't really have seconds resolution, but it's funny to see some values printed with seconds resolution and some w/out, in the same table (as I go editing them all).

What determines how the value is printed ? I tried setting a value different from 00:00:00 in the time field but things didn't change (using the GUI to change value)

**Comment by saleiva** [comment]
hey @xavijam now that you are working on editing fields, could you take a look? I'd not prioritize if not an easy fix right now

**Comment by xavijam** [comment]
:+1:

**Comment by strk** [comment]
Hey, it is actually worst than I thought, editing doesn't only change the output format, but also starts with NOW as the date, so my doubleclick-save process ended up changing all the dates to _right_now_ ! :'(

**Comment by strk** [comment]
NOTE: on switching to map view and back the TZ prefix is back.
And, this is Firefox 45.2.0 here
