### ISSUE TITLE
Georeference menu item looks like telling me some records are not georeferenced yet

### ISSUE THREAD

**Issue by strk** [CartoDB/cartodb#8101]
I noticed that the menu "Georeference" in DataView->Edit has an icon showing a partially filled progress bar. It did make sense while not all records were georeferenced, but the icon doesn't change when all the records are. Is that intentional or a bug ?

**Comment by iriberri** [comment]
That bar stands for the monthly geocoding quota you have (left) for the paid geocoding option (street addresses).

**Comment by strk** [comment]
Ah, then it makes sense. Which side of the bar is the quota left ? I guess it would be more intuitive if it was an actual count (it's a number of geocoding you can make, right?) as the progress-bar is very familiar widget with a completely different meaning...

**Comment by iriberri** [comment]
Blue region represents used quota, grey region represents quota left. When you've exceeded/reached the limit, then it appears in red. :-)

Thank you very much for your feedback @strk! I hope that my previous comments help understandin how it's currently working.  There's a similar slider in the geocoding modal itself:

![image](https://cloud.githubusercontent.com/assets/1730320/16334232/fe7691d2-39ff-11e6-84df-a9b3958e1192.png)

**Comment by strk** [comment]
Your comment was very clear about how it works, thanks. 
Feel free to close this ticket

**Comment by iriberri** [comment]
We'll keep the feedback in mind! Thank you very much again for the time you spent in letting us know. :-)
