### ISSUE TITLE
[ANALYSIS] Finalize Sampling form

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8102]
![screen shot 2016-06-23 at 14 48 12](https://cloud.githubusercontent.com/assets/132149/16303558/8df76b60-3951-11e6-8e83-ce547d9bfb16.png)

@xavijam is there is anybody else going to work on analysis forms, assign :)

**Comment by javisantana** [comment]
hey, if there is an examplo on how to do a slider I could take it (it's simple enough and arce could work in a harder one)

**Comment by javisantana** [comment]
@saleiva what is type?

**Comment by saleiva** [comment]
It was on the original form. I thought you were envisioning new types in
the future

2016-06-23 14:51 GMT+02:00 javi santana <notifications@github.com>:

> @saleiva <https://github.com/saleiva> what is type?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/8102#issuecomment-228039939>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAIENYISF7Qm1CqcGC7UDHtzerJPH_zYks5qOoE7gaJpZM4I8xdo>
> .
>



-- 
Sergio Alvarez Leiva
