### ISSUE TITLE
Polygons aggregation options shouldn't exist

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8105]
since it's just a simple mode right now
![screen shot 2016-06-23 at 14 53 48](https://cloud.githubusercontent.com/assets/132149/16303706/6ad61928-3952-11e6-8473-4039400a10cf.png)

**Comment by xavijam** [comment]
What should we display then?

**Comment by xavijam** [comment]
What about the text?

**Comment by saleiva** [comment]
-> "Polygons"

**Comment by saleiva** [comment]
Hey, this is happening also with lines.
