### ISSUE TITLE
Adding an AOI analysis executes it before clicking on APPLY

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8109]
Default is Trade Areas so this is important or we will overload the data-services API :)

To replicate just apply an AOI analysis to a point layer.

**Comment by viddo** [comment]
It saves _any_ analysis upon creation if the default values is sufficient to create the node, so should it just leave it unsaved until the user explicitly clicks create then?

**Comment by saleiva** [comment]
Yes, so we unify the behaviours

**Comment by saleiva** [comment]
Hey @viddo this is quite urgent since our provider is charging us for the trade areas requests (a lot)-

**Comment by saleiva** [comment]
THANKS! :)
