### ISSUE TITLE
Editor (current one) breaks when creating map from dataset

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#8125]
A client has just reported this, and it is reproducing both in team and free accounts.
When clicking on `VISUALIZE` from a dataset (either data or map view) the Editor shows an error and the map is not created

## STR

* Go to Datasets dashboard and open a dataset
* Click on `VISUALIZE` and confirm
* This happens
![screen shot 2016-06-23 at 17 45 33](https://cloud.githubusercontent.com/assets/10940006/16309800/50fdc966-396a-11e6-8de3-f29959e38e34.png)

In the console we can see this:

```
cartodb.uncompressed.js:28 POST https://ernesmb.cartodb.com/api/v1/viz 403 (Forbidden)
````

**Comment by javitonino** [comment]
We are aware of this and a fix is underway:
https://github.com/CartoDB/cartodb/pull/8118

**Comment by javitonino** [comment]
Just started deploying, should be fixed in ~20 minutes.

Thanks for reporting!
