### ISSUE TITLE
Change the icon/illustration carrousel aggregation when selected none

### ISSUE THREAD

**Issue by urbanphes** [CartoDB/cartodb#8134]
Now we have selected none the icon/illustration is 
<br>
![image](https://cloud.githubusercontent.com/assets/14546701/16312913/2b126f38-3977-11e6-996c-01560c8838ff.png)

... and must be this
<br>
![image](https://cloud.githubusercontent.com/assets/14546701/16312941/3ebb140e-3977-11e6-9599-f205aad7af8a.png)

**Comment by xavijam** [comment]
totally minor
