### ISSUE TITLE
[Analysis] Filter fields should be validated against max/min values of columns

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8137]
hey @urbanphes the design is a bit weak since it's very easy to input values that doesn't exist. It lacks of context when setting the values.

@javierarce one solution would be to add dynamic validation... or change the numeric inputs to numeric sliders...

**Comment by urbanphes** [comment]
Here the visual design. 

We add extra info on input hint.

![01 layers - 06-149 analysis - filter number](https://cloud.githubusercontent.com/assets/14546701/16919322/7ab25f08-4d09-11e6-979a-dc3b94624a0b.png)

**Comment by saleiva** [comment]
The issue then is that as soon as you type once, you forget the limit, right? I understand it's also a contextual help, so if it's easy I'd impement it.

**Comment by saleiva** [comment]
Javier, note the alignement of the labels

**Comment by xavijam** [comment]
Already working by the way! and nicely working! :)

**Comment by xavijam** [comment]
![screen shot 2016-10-04 at 17 26 11](https://cloud.githubusercontent.com/assets/132146/19080533/a8d431c8-8a57-11e6-8401-dc089386ac5a.png)

**Comment by xavijam** [comment]
But it is true that labels alignment is not totally right. Leaving opened but super minor 💋

**Comment by alrocar** [comment]
Stale issue. Closing 👋
