### ISSUE TITLE
[Analysis]  Filter analysis fixes

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8138]
- [x] Show 3rd form only when selecting a column above.
- [x] 3rd should have "show" activated by default
- [x] Update description on analysis modal.
- [x] Is greater than / Is less than input label should be "value" in both cases.
- [x] Input text for string values should show a list when having less than XXX different values.

**Comment by javierarce** [comment]
@saleiva: I couldn't find a valid description for this analysis in the designs (there we just have `Transform your data into coordinates` and also `Calculate area o influence of a layer determined by walking or driving time or just by distance`), so what about something like: "Filter the data based on the data of a column"

**Comment by saleiva** [comment]
Sounds good,

"Filter your rows depending on the values of a column" ?

**Comment by javierarce** [comment]
Great!
