### ISSUE TITLE
Possibility to add general opacity if user styles by value (category or ramp)

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#8142]

**Comment by xavijam** [comment]
The same behaviour we already had in the previous editor, no designs for that. I'd not change it for now, and if you need to add an opacity, we should use cartocss.

**Comment by urbanphes** [comment]
We had been working on this module. You can see how to:
<br>
![image](https://cloud.githubusercontent.com/assets/14546701/16371765/e45baf44-3c48-11e6-84f3-ddef97ba165f.png)

**Comment by saleiva** [comment]
Getting more support requests about this

**Comment by michellechandra** [comment]
S/B: 10626773

**Comment by michellechandra** [comment]
S/B: 10656996

**Comment by hacheka** [comment]
Passed to `code review`

**Comment by xavijam** [comment]
Things added:
- Added preview for opacity.
- Fixed problem changing color from "by value" to "fixed" \o/ 💃 .

cc @ivanmalagon
