### ISSUE TITLE
Update data table source in slug when SQL changed

### ISSUE THREAD

**Issue by danrademacher** [CartoDB/cartodb#816]
I originally added this layer and styled it with one table, then needed to rebuild the table in a different way (but with the same schema). The SQL section was great in allowing me to pull the data from a new table and keep all my hover styling, etc.

But the little gray copy should update too (note the "_2" in the label vs. the "_3" in the query:
![image](https://cloud.githubusercontent.com/assets/1423200/4381836/85992e62-437c-11e4-89df-194a37913200.png)

(I admit this is not a major problem!)

**Comment by saleiva** [comment]
Ok, closing and moving this to the new editor improvements! Thanks!
