### ISSUE TITLE
Clicking on an infowindow type that is not one of the first set, moves the horizontal scroll to the beginning

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8161]
like for example, selecting the color infowindow

**Comment by saleiva** [comment]
Not happening anymore :)

**Comment by matallo** [comment]
uhm, I was still keeping it open as we'd need somwthing for the case when selecting a carousel item from the end, then you go back to the layers panel, then go forth to the basemap layer, the carousel won't scroll to the selected item (see attached, I feel this as an enhancement, though)

![screen shot 2016-07-14 at 12 53 34](https://cloud.githubusercontent.com/assets/36676/16837183/0755597e-49c2-11e6-8e92-853aaefa71f0.png)

/cc @xavijam

**Comment by saleiva** [comment]
yeah, enhancement. I'd say we open a new issue with that if we want :)

**Comment by matallo** [comment]
\o/
