### ISSUE TITLE
Apply default styles when performing analysis

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8162]
blocked by: https://github.com/CartoDB/camshaft/issues/86

cc/ @makella

**Comment by makella** [comment]
@saleiva update here. I am going to walk through the analysis methods with the rest of the research team and get a better sense of exactly what we expect to see on the map when an analysis is run. Once I have that information figured out a little more, I can move forward with applying better defaults.

**Comment by noguerol** [comment]
@makella let's pick up this project again!

**Comment by makella** [comment]
YES! i'm in

**Comment by makella** [comment]
preliminary work here (last page)
https://docs.google.com/document/d/1giofZY-sbFgqeTYw3uEa4cyOFiad_ps49obdnSyjo6Q/edit

**Comment by piensaenpixel** [comment]
Hey @makella do you think this could still be interesting?

**Comment by makella** [comment]
YES and something I really, really want us to have! I've started work on this project a few times... if it becomes a priority, I am totally up for working on it

**Comment by piensaenpixel** [comment]
yeah!

**Comment by alrocar** [comment]
Stale issue. Closing 👋
