### ISSUE TITLE
Create simple set of default styles

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8163]
Defaults por points / polygons and lines

When done, please talk to @xavijam

**Comment by makella** [comment]
@saleiva in progress.

@javisantana and I are working through.

we will put some in for now, definitely can be changed as we start to use more.

for now, thinking something like this:

![screen shot 2016-07-11 at 11 07 19 am](https://cloud.githubusercontent.com/assets/1566273/16739498/adfa0120-4757-11e6-835a-1531660d247e.png)

**Comment by xavijam** [comment]
Already implemented and being used, a very good start.
