### ISSUE TITLE
[STYLES] Controls not working for lines datasets

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8164]
After changing a color or something lines get rendered as points.

**Comment by xavijam** [comment]
steps?

**Comment by saleiva** [comment]
It doesn't happen always. Trying to replicate

**Comment by saleiva** [comment]
Looks like after changing the cartcss manually, changes on controls are correctly reflected

**Comment by saleiva** [comment]
Also, when doing an analysis such as filter on a lines dataset, the style tab doesn't work. You cannot select anything.

**Comment by xavijam** [comment]
Working for me after the fix @viddo has done in https://github.com/CartoDB/cartodb/pull/8232.
