### ISSUE TITLE
.carto import won't work with analyses on layers

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#8170]
**str**
- import dataset

[paradas_metro_madrid (on 2016-06-02 at 15.26.52).carto.zip](https://github.com/CartoDB/cartodb/files/331637/paradas_metro_madrid.on.2016-06-02.at.15.26.52.carto.zip)

**Comment by javitonino** [comment]
We weren't exporting `source_id` on widgets until last week. Can you try re-exporting and trying to import again. The `.carto.json` should have version 2.0.1.

**Comment by saleiva** [comment]
gonna try

**Comment by saleiva** [comment]
Hey how can I export this from the builder UI?

**Comment by gfiorav** [comment]
You can't, it's not implemented yet @saleiva

**Comment by javitonino** [comment]
I tried this yesterday with a complex map with analyses, widgets, etc and worked perfectly.

**Comment by matallo** [comment]
closing, feel free to create a new issue for the builder UI
