### ISSUE TITLE
Remove blue link for showing all columns, and show all the columns by default

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8172]
![screen shot 2016-06-24 at 13 20 46](https://cloud.githubusercontent.com/assets/132149/16336525/87fb9df4-3a0e-11e6-8f5b-7283c98184c3.png)

**Comment by piensaenpixel** [comment]
@saleiva really if we show all the columns, we need to remove all the paragraph, doesn't it?

**Comment by saleiva** [comment]
Which one?

**Comment by piensaenpixel** [comment]
"20 colums more"

**Comment by piensaenpixel** [comment]
ah ok... sorry is the same i thought you mean change the color, forget it 💃

**Comment by saleiva** [comment]
yep yep
