### ISSUE TITLE
[analysis] geometry type population should skip null geometries

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb#8181]
When you try to add an analysis a query to the SQL API is performed in order to know the geometry type, the query might return null geometries.

We should filter `where the_geom is not null` so we get some geometry types and avoid getting nulls.

P.S.: My guesstimation about this is: this is happening since we started adding on the fly indexes for the widgets, making the returning order to change. What do you think about it? 😈 .

**Comment by xavijam** [comment]
cc @viddo

**Comment by viddo** [comment]
Sounds reasonable to me, should be easy enough 👍

**Comment by saleiva** [comment]
It's hard to replicate as it doesn't happen always, but we experienced this yesterday
