### ISSUE TITLE
change behavior style (data panel)

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#8183]
If you click on the style's link, should go to the style panel (not to the widget).
Also some things:
- Maybe we could add another button to customize the widget. If we add this one, the arrow back should be back to data panel

**Comment by xavijam** [comment]
I don't get that, why do we need to go to the style panel? For me what @nobuti has done makes sense, probably the name of the button is not the correct one.
cc @saleiva @urbanphes

**Comment by piensaenpixel** [comment]
yes if we change the name it has sense, but if we use "style" should go to style panel, maybe both, one for style layer and other one for edit widget

**Comment by saleiva** [comment]
+1

**Comment by nobuti** [comment]
So? Two buttons then? One button with different label?

**Comment by saleiva** [comment]
I'd say yes. What about? CUSTOMIZE and STYLE?
cc/ @urbanphes

**Comment by urbanphes** [comment]
But it makes no sense to do that. Have a button (custom) without a selection previous, why¿? If I don't click the checkbox why the interface show it me the custom button¿? I don´t understand this behaviour. At the begining this module was thinking: Checkbox selected add like a widget; Style link, to make style by this column. IMO we must think we really want to do with this component.
