### ISSUE TITLE
Changing basemap to one with labels causes left sidebar not to load

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#8188]
STR:

Both times it happened, I was using an aggregation (squares in this case) and then changed the basemap.

The lateral left bar fails to load and a js error is shown:
```
Uncaught TypeError: Cannot read property 'querySchemaModel' of undefined
```

It can be fixed going back to the old editor and changing the basemap to one **without** labels. Then go back to the builder and everything is back to normal.

I can't attach it, but I have a .carto file that reproduces this problem.

**Comment by gfiorav** [comment]
Hey @xavijam it seems that @matallo knows what's up with this one and has asked me to assign this to him!

**Comment by xavijam** [comment]
:+1:
