### ISSUE TITLE
editor infowidow and map infowindow are inconsistent

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#8191]
**str**
- create map
- add point
- create several columns
- add infowindow
- select all fields
- reload
- deselect several fields
- reload
- select several fields from the former deselected

**expected behaviour**
- fields order in infowindow and panel to be the same

**actual behaviour**
- fields order in infowindow and panel are different

![screen shot 2016-06-24 at 21 41 42](https://cloud.githubusercontent.com/assets/36676/16348762/ce550ee8-3a54-11e6-98b9-292b4c8c5d52.png)

[Untitled map 50 (on 2016-06-24 at 19.41.59).carto.zip](https://github.com/CartoDB/cartodb/files/332480/Untitled.map.50.on.2016-06-24.at.19.41.59.carto.zip)

they will get randomnly ordered in the infowindow (sometimes with proper order, some others not), as the pos stored in the fields array will be `Number.MAX_VALUE` for both at the time of save, thus it can't be properly sorted

**Comment by ramiroaznar** [comment]
@matallo should we close this issue ?

**Comment by matallo** [comment]
no work has been done in this, so i wouldn't close it
