### ISSUE TITLE
Error when adding or deleting a widget

### ISSUE THREAD

**Issue by nobuti** [CartoDB/cartodb#8197]
`Uncaught TypeError: this._vis(...).invalidateSize is not a function`
at `F._invalidateSize	@deep-insights-integrations.js:253`

The widget is correctly deleted or added though.

cc @alonsogarciapablo @xavijam

**Comment by xavijam** [comment]
Not happening to me, do you have last cartodb.js changes?

**Comment by nobuti** [comment]
👍
