### ISSUE TITLE
Improve Cluster description

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8203]
"Group points so they are more similar to each other in that group than to those in other groups."

**Comment by javierarce** [comment]
Much better than the previous description, but couldn't we just say "Group points by proximity" instead?

**Comment by saleiva** [comment]
Do it.

2016-06-29 18:42 GMT+02:00 Javier Arce <notifications@github.com>:

> Much better than the previous description, but couldn't we just say "Group
> points by proximity" instead?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/8203#issuecomment-229415538>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAIENZKhNI6bWbzjPqt--GDPOzT_BEgRks5qQqCEgaJpZM4I-VS5>
> .
>



-- 
Sergio Alvarez Leiva
