### ISSUE TITLE
Fix required position

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#8205]
![image](https://cloud.githubusercontent.com/assets/1214201/16372019/8b87ca90-3c4a-11e6-9e6d-818fe69f727b.png)

**Comment by xavijam** [comment]
That bug is already reported. It is not related with CSS, it is related with how backbone forms validate non visible forms.

**Comment by piensaenpixel** [comment]
chachi @xavijam

**Comment by xavijam** [comment]
❤️

**Comment by xavijam** [comment]
cc @viddo and @javierarce, because I know you have seen that ticket, right?

**Comment by viddo** [comment]
Can't remember, if you can't find it I'd say we should re-open this one

**Comment by javierarce** [comment]
It's here: https://github.com/CartoDB/cartodb/issues/7923
