### ISSUE TITLE
Export dataset selection

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#8211]
Adding this issue so we don't forget pending features:
- [ ] [Select datasets](https://docs.google.com/document/d/13g0n3HZMmQyjOcg_G0-p4zMQf1UzOHT3Hy2IGDHpBNc).
- ~~Export only the metadata.~~ #11388

cc @gfiorav @xavijam

**Comment by mbforr** [comment]
hey @juanignaciosl we got this request from a client so could we possibly push this up a bit?

**Comment by juanignaciosl** [comment]
Editor 3 is the priority now. Depending on the evolution of the week we might be able to do it soon. Stay tuned.

**Comment by mbforr** [comment]
Okay sounds good!

On Mon, Jun 27, 2016 at 10:29 AM, Juan Ignacio Sánchez Lara <
notifications@github.com> wrote:

> Editor 3 is the priority now. Depending on the evolution of the week we
> might be able to do it soon. Stay tuned.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/8211#issuecomment-228762077>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEmtLNJxJiDN1Vmkrp7Mno2WtiY-CHLpks5qP944gaJpZM4I-269>
> .
>



-- 
*Matt Forrest*
Client Success Manager

*CartoDB*
201 Moore St, Brooklyn, NY, 11206, USA
T: (612) 325-8470 Skype: mbforr
W: www.cartodb.com

Live sessions to learn CartoDB <http://cartodb.com/webinars/>

**Comment by andrewxhill** [comment]
Is this ticket talking about Exporting the results of widget filters?

**Comment by juanignaciosl** [comment]
@andrewxhill no, and I haven't heard about that feature. It might be interesting, but that should be discussed, so open a new issue or feature request, please.

**Comment by ramiroaznar** [comment]
@juanignaciosl can we close this?

**Comment by juanignaciosl** [comment]
I certainly think that selecting datasets on map export might be useful, but it's certainly not a priority, so let's close this. It will eventually come back if it's actually useful.
