### ISSUE TITLE
Review invite user to an org email 

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8214]
Text and design are very weak
![em](https://cloud.githubusercontent.com/assets/132149/16374018/ec4993ae-3c54-11e6-9f2c-203665486033.png)

**Comment by urbanphes** [comment]
@juanignaciosl I would need a list of type of emails we send (and if it is with screenshot better)

**Comment by urbanphes** [comment]
Here the mockup to this type of mail

![01 mailing - 01-01 invite](https://cloud.githubusercontent.com/assets/14546701/16386431/0ba49654-3c91-11e6-834e-cac3f9d1825b.png)

**Comment by urbanphes** [comment]
Here the mockup
<br>
![01 mailing - 01-01 invite](https://cloud.githubusercontent.com/assets/14546701/16756392/049d6140-4805-11e6-9b98-2259f74d20ea.png)

**Comment by saleiva** [comment]
I don't get the text. It's too redundant IMO.

Also the asset seems a bit missleading, since if I've been invited to an org, I'd expect to see the logo of my org at least (and the colors configured on the settings).

**Comment by urbanphes** [comment]
Here the visual design
<br>
![01 mailing - 01-01 invite](https://cloud.githubusercontent.com/assets/14546701/16845268/9c82d24e-49e8-11e6-963b-f3352c9ff9fa.png)
<br>
cc/ @saleiva

**Comment by juanignaciosl** [comment]
@urbanphes as you see the task about complete email redesign has been created, expect the list to be done, including screenshots, in the next days. Sorry about the delay.

**Comment by urbanphes** [comment]
@juanignaciosl Oks

**Comment by juanignaciosl** [comment]
@urbanphes I've finished all listings and cc-ed you. Is this one the final design for invitations? Should we do it right now then?

**Comment by urbanphes** [comment]
@juanignaciosl Yes it's the final design for invitations
