### ISSUE TITLE
Refreshing the builder leads to 500 error with no chance to go back

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb#8220]
Steps to reproduce:
* create a map with at least 2 layers
* extract the datasource from one of the layers as a new layer
* refresh the builder

cc @xavijam cc @rochoa

**Comment by AbelVM** [comment]
https://github.com/CartoDB/cartodb/issues/8223

cc @matallo

**Comment by AbelVM** [comment]
cc @saleiva

**Comment by xavijam** [comment]
Taking a look!

**Comment by xavijam** [comment]
Already fixed thanks to @juanignaciosl in https://github.com/CartoDB/cartodb/issues/8223.
