### ISSUE TITLE
[popups] drag analysis as layer returns error500

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#8223]
**str**

- create map
- add analysis (area of influence: default values)
- drag analysis as new layer

**expected behaviour**

- create new layer with the analysis

**actual behaviour**

- reload and error500

to blame: https://github.com/CartoDB/cartodb/blob/master/app/controllers/carto/api/vizjson3_presenter.rb#L468

/cc @AbelVM 

[Rollbar](https://rollbar.com/vizzuality/CartoDB/items/19196/occurrences/14204518657/).

**Comment by juanignaciosl** [comment]
@matallo fix in progress. FYI tooltips also have to be migrated, the fix just excludes "none".

**Comment by AbelVM** [comment]
cc @saleiva
