### ISSUE TITLE
Filters stored as URL params are acting weird

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb#8227]
Steps to reproduce:

Open an embed, for example
https://team.cartodb.com/u/solutions/builder/16ab12f6-3c57-11e6-bee9-0e674067d321/embed

Zoom to the place with a high concentration of green markers and do not touch anything else. **Total stores: 14,973**
Refresh the window --> **Total Stores: 165**, but (visually at least) there is no filtering applied to any widget.

Refresh again -> no change

**Comment by saleiva** [comment]
possibly duplicated by https://github.com/CartoDB/cartodb/issues/8227

**Comment by AbelVM** [comment]
by this very issue? :joy:

**Comment by AbelVM** [comment]
Fixed long time ago
