### ISSUE TITLE
Coloring by value on category maps is not generating the correct CartoCSS

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8237]
when switching from ramp to categories.

It sounds to me that this was duplicated but I cannot find the other ticket

**Comment by xavijam** [comment]
It should be working properly now, but not sure, do you remember @saleiva what was the problem? 💋

**Comment by xavijam** [comment]
Let me close it for the moment and we find any other issue let's open a new one, love you guys.
