### ISSUE TITLE
Deactivating auto-styling on a points dataset within the builder resets that layer marker-radious to default

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8239]
It respects correctly the radius when setting the colors, but it overrides it when deactivating the auto-styling

**Comment by fdansv** [comment]
Sorry, the DI pr closed this issue. Closing when I can see this in the editor

**Comment by fdansv** [comment]
Fixed in https://github.com/CartoDB/cartodb/pull/8425
