### ISSUE TITLE
[POPUPS] Empty lateral panel when entering to hover infowindow after refreshing

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8244]
After selecting one field (customer value) on the hover infowindow and refreshing the page to see the changes (related bug) I cannot longer enter to the hover infowindow panel on this layer.

Uncaught Error: TrackJS Caught: Cannot read property 'customer_value' of undefinedwrapError @ tracker.js:26d.util.hasFunction.f.(anonymous function) @ tracker.js:4

**Comment by matallo** [comment]
can't reproduce, do you have the source dataset?

**Comment by saleiva** [comment]
Closing then, it might be related with the fixes that we've done in the cache

**Comment by matallo** [comment]
🙌
