### ISSUE TITLE
Need to change the name of the layers

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8246]

**Comment by saleiva** [comment]
cc/ @urbanphes to provide the UI

**Comment by nobuti** [comment]
@urbanphes @saleiva I'm taking https://projects.invisionapp.com/share/5G4TKZHEJ#/screens/129054376 as reference for now.

**Comment by saleiva** [comment]
ok, that's great.

**Comment by saleiva** [comment]
Just to clarify that's 2 different things.
those mockups shows the name change on the map, which we need, yeah.
This ticket is about changing the name of the layers. UX can be the same indeed.

**Comment by nobuti** [comment]
Yes, I'm entering the thing in two places:
- the list of layers
- inside a layer, when editing the layer

**Comment by saleiva** [comment]
ok, cool :)

2016-06-28 13:45 GMT+02:00 Buti <notifications@github.com>:

> Yes, I'm entering the thing in two places:
>
>    - the list of layers
>    - inside a layer, when editing the layer
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/8246#issuecomment-229025897>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAIENTgSksPdsRg9kvhfvWJd_tbI9bckks5qQQlKgaJpZM4I_OpO>
> .
>



-- 
Sergio Alvarez Leiva

**Comment by urbanphes** [comment]
Here the mockups

Select menu:
![01 layers - 02-20 style](https://cloud.githubusercontent.com/assets/14546701/16445146/9ba99db6-3de1-11e6-836c-c46ddc78c987.png)


How to change the name:
![01 layers - 02-22 style](https://cloud.githubusercontent.com/assets/14546701/16445169/b034362e-3de1-11e6-9311-f5e95a4efa98.png)
