### ISSUE TITLE
Funny Export with Invalid Geoms... 

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#8259]
The geoms in this table, https://mappingmashups.cartodb.com/tables/geotheory_uk_2016_eu_referendum_with_ni/public/map
- Seem to not have any issues while inside of CartoDB. 
- You can export GeoJSON, but it drops the geoms in N.I. 
- You can export as SHP and they are all contained. 

not sure where the validity issue should be raised, but it was confusing for sure

**Comment by iriberri** [comment]
Oh, I remember this issue! It's an old one if I'm not wrong. :-) I think this was mentioned/discussed in the past but I'm not able to find it now here neither in the SQL API repo. I'll take a look, thanks for reporting!
