### ISSUE TITLE
Adjusting

### ISSUE THREAD

**Issue by azvoleff** [CartoDB/cartodb#8260]
Would you accept a pull request to make the minimum time between manual syncs (SYNC_NOW_TIMESPAN  - see https://github.com/CartoDB/cartodb/blob/e6a193ddec6055e4f01c20980e615ea3f50ef31d/app/models/synchronization/member.rb#L30) configurable in app_config.yml? Would be nice for custom installs to be able to shorten it on a machine with a limited number of users when prototyping things.

**Comment by javisantana** [comment]
yes, sure, please do it
