### ISSUE TITLE
Aggregation Method Polygon Sizes

### ISSUE THREAD

**Issue by makella** [CartoDB/cartodb#8268]
Is there a specific reason that with the hexbin and square aggregation methods that the minimum symbol size is 15? Just wondering because in the Editor we used to be able to select sizes manually that could be below this fixed 15 that we now have.

It would be awesome if we could go to smaller sizes like we used to (if its possible).

**Comment by ramiroaznar** [comment]
Now the minimum size is 10. @makella do you want smaller sizes?

**Comment by makella** [comment]
this might have changed since i wrote this... not sure
