### ISSUE TITLE
Table view pending issues

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#8269]
- [x] Disabled state.
- [x] ~~Add sync info if it exists~~.
- [ ] Edition behaviour tests.
- [ ] Table body tests.
- [x] When a table is empty, show special view for adding the first one.
- [ ] Geometry edition.
- [x] Date edition is not styled (@piensaenpixel).
- [x] When a cell doesn't have value, row style appears weird (@piensaenpixel).
- [ ]  If you click the "options menu" of a cell in the bottom of the screen, it goes out of the view

**Comment by xavijam** [comment]
But if you check the table (not being in the map), how do you know if it is synced or not?

**Comment by saleiva** [comment]
The information is over the map title. 
![screen shot 2016-06-28 at 12 38 30](https://cloud.githubusercontent.com/assets/132149/16412588/48d40248-3d2d-11e6-86b2-3a612e8da8fc.png)

**Comment by xavijam** [comment]
ok! That's new, let me open a ticket for that.

**Comment by xavijam** [comment]
Moved table style problems to @piensaenpixel in https://github.com/CartoDB/cartodb/issues/7950.

**Comment by piensaenpixel** [comment]
Done - https://github.com/CartoDB/cartodb/issues/7950
