### ISSUE TITLE
Protect with password page is not correctly styled

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#8276]
I'd keep the same one we have right now, but with new font and so on.

<img width="1433" alt="screen shot 2016-09-20 at 15 42 31" src="https://cloud.githubusercontent.com/assets/2141690/18672558/e26bcdfc-7f48-11e6-82a0-82c3817d264b.png">

@saleiva @urbanphes

**Comment by saleiva** [comment]
I think we had it designed

**Comment by urbanphes** [comment]
It's ready. 
If you need the visuals, ask me.

**Comment by saleiva** [comment]
Hey @xavijam could @MariaCheca take care of this as well? It's very similar to the login one.

**Comment by piensaenpixel** [comment]
I'll take tomorrow

**Comment by MariaCheca** [comment]
Hi, do we have the redesign ready? If yes please show me where it is so I can start with this :)

**Comment by urbanphes** [comment]
Here the visual designs for this part:

![1440 - 04-00 - password](https://cloud.githubusercontent.com/assets/14546701/18701668/2b232758-7fde-11e6-8d39-254ab731812e.png)

![1440 - 04-01 - password](https://cloud.githubusercontent.com/assets/14546701/18701678/316baf72-7fde-11e6-8bcb-a08623cee018.png)

![1440 - 04-02 - password](https://cloud.githubusercontent.com/assets/14546701/18701681/36b18b32-7fde-11e6-8b3c-30b2f5193c4a.png)

**Comment by xavijam** [comment]
@MariaCheca, all yours :)

**Comment by MariaCheca** [comment]
👏
