### ISSUE TITLE
when creating a layer form a node it raises an exception

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#8289]
<img width="617" alt="screen shot 2016-06-28 at 3 36 35 pm" src="https://cloud.githubusercontent.com/assets/30147/16417439/2308272e-3d46-11e6-807c-7d2fdabbbd8f.png">

**Comment by alonsogarciapablo** [comment]
Could you please be more explicit about the steps to reproduce? Thanks!

**Comment by javisantana** [comment]
yes, 

1) add a points layer
2) add a cluster analysis
3) add a wieght centroid analysus
4) drag the cluster node (kmeans) to create a new layer

the exception is raised
