### ISSUE TITLE
node used by widgets not sent in the analysis list

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#8290]
steps:

1) replicate this 
<img width="328" alt="screen shot 2016-06-28 at 4 04 19 pm" src="https://cloud.githubusercontent.com/assets/30147/16418422/0b3db9ca-3d4a-11e6-8aaa-1bf5c571b2c9.png">

(notice the intersection is done with clients table not B0)

2) add a histogram to customer_value on B0

Maps api raises an exception:

```
Request to Maps API failed: Node with `source.id="b0"` not found in analyses for dataview "5e683703-bf1f-415b-8aaf-ca3bd920348f"
```

**Comment by rochoa** [comment]
This is fixed at Maps API level. Ref https://github.com/CartoDB/Windshaft-cartodb/issues/528.
