### ISSUE TITLE
Unable to access maps API for analyses in new builder

### ISSUE THREAD

**Issue by rohshar** [CartoDB/cartodb#8293]
I tried adding an area of influence analysis but I always get the following error:

![screen shot 2016-06-28 at 11 34 22 am](https://cloud.githubusercontent.com/assets/19723718/16421908/8730ad2e-3d24-11e6-84a0-ba46f7dbaf46.png)

**Comment by rochoa** [comment]
Can you try again, your user was missing a permission setting.

**Comment by rohshar** [comment]
worked thanks

**Comment by rohshar** [comment]
can you also give access to the other intern ethan lampert. cartodb username: elampert
