### ISSUE TITLE
Implement quota bar on paid analysis (For the time being it will be only in AOIs when walking/driving)

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8299]
The analysis ends, but nothing is rendered on the result
Also, it takes a lot of time.

After doing the analysis, if you check the data on the table view, it's still points.

**Comment by saleiva** [comment]
cc/ @dgaubert @rochoa

**Comment by xavijam** [comment]
<img width="376" alt="screen shot 2016-06-28 at 22 31 15" src="https://cloud.githubusercontent.com/assets/132146/16431361/8777ccac-3d80-11e6-8109-553635a486a3.png">

Checked and seems like params are sent properly, but Maps API returns an error. Could you take a look @rochoa or @dgaubert ?

**Comment by dgaubert** [comment]
Seems like you have reached your limit of the quota:
```js
{
query: "BEGIN;DELETE FROM analysis_trade_area_f595e8bc04b76cf03ed9474211b3615245ccd588;INSERT INTO analysis_trade_area_f595e8bc04b76cf03ed9474211b3615245ccd588 WITH _cdb_analysis_source_points AS ( select * from analysis_weighted_centroid_3119a145a5fa68c88edb48868150cd27d0996136 ), _cdb_analysis_isochrones AS ( SELECT cdb_isochrone( _cdb_analysis_source_points.the_geom, 'walk', ARRAY[600]::integer[] ) as isochrone, cartodb_id, category, value FROM _cdb_analysis_source_points ) SELECT (isochrone).center, (isochrone).data_range, (isochrone).the_geom, cartodb_id, category, value FROM _cdb_analysis_isochrones ;COMMIT;",
onsuccess: "UPDATE cdb_analysis_catalog SET status = 'ready', updated_at = NOW() WHERE node_id = 'f595e8bc04b76cf03ed9474211b3615245ccd588'",
onerror: "UPDATE cdb_analysis_catalog SET status = 'failed', updated_at = NOW() WHERE node_id = 'f595e8bc04b76cf03ed9474211b3615245ccd588'",
status: "failed",
fallback_status: "done",
failed_reason: "cdb_dataservices_client._cdb_isochrone(6): [cartodb_user_a6f0d0fe-4f4f-4217-8150-22b0010fe409_db] REMOTE ERROR: spiexceptions.ExternalRoutineException: plpy.Error: You have reached the limit of your quota, quota = 60000.0"
}
```

**Comment by saleiva** [comment]
We need better error repoeting then

**Comment by rochoa** [comment]
Error reporting will be addressed at https://github.com/CartoDB/cartodb-postgresql/issues/265 and https://github.com/CartoDB/camshaft/issues/98.

**Comment by saleiva** [comment]
Updating issue name

**Comment by xavijam** [comment]
Closing since we won't need it right?

**Comment by saleiva** [comment]
Not before announcing date

2016-07-05 13:30 GMT+02:00 Javier Álvarez Medina <notifications@github.com>:

> Closing since we won't need it right?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/8299#issuecomment-230454020>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAIENZ6wolee9VhfKo_DPHrsJwViYF7iks5qSkBwgaJpZM4JAba5>
> .
>



-- 
Sergio Alvarez Leiva

**Comment by xavijam** [comment]
Already implemented!
