### ISSUE TITLE
Setting a "none" infowindow in builder breaks editor

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#8312]
Reproduced testing #8309, which fixes the embed error for a related problem.

1. Create a map with the builder.
2. Set light infowindow.
3. Set none infowindow (2 + 3 enforces storing "none" as template).
4. Open the map in the editor. You get this JS error:

```
tracker.js:10 cartodb/table/views/tooltip/custom_templates/none not founda.(anonymous function) @ tracker.js:10
infowindow_html_pane.js:202Uncaught TypeError: cdb.templates.getTemplate(...) is not a function
```

cc @xavijam @matallo

**Comment by matallo** [comment]
on it!
