### ISSUE TITLE
timeslider fixes

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#8320]
- [x] enable numeric columns on widget add modal for timeslider (and make them work)
- [x] reduced version misses histogram
- [x] when a torque layer is added animation controls should be shown
- [ ] when filtering by a histogram widget timeslider is updated but torque renders the same map (and should be rendering the filtered data)

**Comment by ramiroaznar** [comment]
AFAIK this is fixed. Can we close it @javisantana ?

**Comment by matallo** [comment]
can't reproduce, this is not happening anymore, closing then!
