### ISSUE TITLE
Small issues in the share dialog

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#8322]
- [x] Remove the fake number about the shared people.
- [x] Privacy css class is not being set.

![screen shot 2016-06-29 at 15 09 52](https://cloud.githubusercontent.com/assets/132146/16453044/adc378b2-3e0b-11e6-9474-4910477b0a72.png)

- [x] Embed url is missing `/builder/` part (https://github.com/CartoDB/cartodb/issues/8370#event-709125429).
- [x] Date should appear as 24 hours.

![screen shot 2016-06-30 at 15 45 43](https://cloud.githubusercontent.com/assets/132146/16490413/d426b072-3ed9-11e6-8d89-00e1fada9ca6.png)

- [x] Although the map is public, it says it is private.

![screen shot 2016-06-29 at 15 11 31](https://cloud.githubusercontent.com/assets/132146/16453086/d8fa3782-3e0b-11e6-93dc-299d128e66b6.png)

- [x] Replace 'change your privacy' link by a button, if possible, and will get rid of the '#' in the url.
- [x] SDK thing has nobutilon text :joy:. `mapView.loadCartoDbMap("6823d7c0-0bca-11e6-bc90-0e5db1731f59");`
- [x] Share button should be bigger (https://github.com/CartoDB/cartodb/issues/8337).

**Comment by xavijam** [comment]
Before you open another ticket @saleiva, here we go.
@gfiorav, here we go! map caps closer than ever :).

**Comment by saleiva** [comment]
HAHAHA

**Comment by ohasselblad** [comment]
Are there plans to make the `update` button more accessible instead of only in the share dialog? I can imagine making some changes to my map and forgetting to hit `update` if it's more than a click away.

**Comment by xavijam** [comment]
Good question @ohasselblad, lets @CartoDB/design team answer :).
