### ISSUE TITLE
Layer vizjson with tooltip has no fields

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#8330]
trace: https://rollbar.com/vizzuality/CartoDB/items/19248/ and https://rollbar.com/vizzuality/CartoDB/items/19223/ 

A tooltip (or infowindow for that purpose) with no fields (not empty: no fields key at all) is malformed AFAIK. I have no clue how to reproduce it.

@matallo can you think of a scenario were this could happen?

cc/ @juanignaciosl

**Comment by matallo** [comment]
🤔 no idea
