### ISSUE TITLE
The share button must be bigger

### ISSUE THREAD

**Issue by urbanphes** [CartoDB/cartodb#8337]
![image](https://cloud.githubusercontent.com/assets/14546701/16459375/e4fd1808-3e22-11e6-8360-9552758695ad.png)

like this
![image](https://cloud.githubusercontent.com/assets/14546701/16459455/194cf358-3e23-11e6-92f1-e63346de356e.png)

**Comment by xavijam** [comment]
Moved here -> https://github.com/CartoDB/cartodb/issues/8322
