### ISSUE TITLE
Add layer id to named map template and bump Map Config version to 1.5.0

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#8339]
This is required for https://github.com/CartoDB/cartodb/issues/7574 and https://github.com/CartoDB/Windshaft-cartodb/pull/525.

Things to do for future named map templates:

- [x] Add ID of the layer as an attribute of "cartodb" layers. (https://github.com/CartoDB/cartodb/pull/8340)
- [x] Bump version of Map Config to 1.5.0. (https://github.com/CartoDB/cartodb/pull/8340)

```
...
  "layergroup": {
    "version": "1.5.0",
    "layers": [
      {
        "type": "cartodb",
        "id": "THE_LAYER_ID",
        "options": {
          "cartocss_version": "2.1.1",
          "cartocss": "#layer { polygon-fill: <%= color %>; }",
          "sql": "select * from european_countries_e WHERE cartodb_id = <%= cartodb_id %>"
        }
      }
    ]
  },
...
```

cc: @xavijam @rochoa

**Comment by gfiorav** [comment]
Closed via https://github.com/CartoDB/cartodb/pull/8340
