### ISSUE TITLE
Cluster Analysis tool Runs, then layer does not show

### ISSUE THREAD

**Issue by cartodave** [CartoDB/cartodb#8342]
Smoke test: 
- Use case 2
- Step 2 

Add analysis to 'Customers Layer' > Selected 6 clusters > Analysis completed but not layer shown

**Comment by saleiva** [comment]
Hi Dave, do you have any error in your dev. console? Can you share with us the link to that map?

**Comment by javisantana** [comment]
we were debugging it yesterday, it happens sometimes cc @rochoa

**Comment by saleiva** [comment]
Fixed!
