### ISSUE TITLE
Areas of Influence across date line

### ISSUE THREAD

**Issue by rohshar** [CartoDB/cartodb#8344]
I am getting a weird visualization when I try to use the area of influence analysis on a specific earthquakes data set that can be found here: https://rodolfo8.cartodb.com/tables/earthquakes_cdbjs_lesson3/public/map

I am pretty sure it has something to do with errors across the international date line. Here is a screenshot:

![screen shot 2016-06-29 at 5 26 24 pm](https://cloud.githubusercontent.com/assets/19723718/16469947/a0cab7d6-3e21-11e6-9767-713ecc65cc6b.png)

**Comment by saleiva** [comment]
Exactly, this is a known issue. I'm afraid this has not an easy way to fix but mentioning here @CartoDB/research just in case

**Comment by ohasselblad** [comment]
Maybe we should add a verification step that
1. checks whether any elements go below -180 or above +180  
2. if 1 is true, chops the geoms and re-pastes them together

I could see this being a general feature that a lot of analyses could use.

**Comment by stuartlynn** [comment]
There is a good example of this in the great circle function

**Comment by makella** [comment]
we should keep open
