### ISSUE TITLE
Red "required" tooltip will get stuck in the top-left corner after filter analysis

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#8354]
I hope it's not dup, I couldn't find it in other issues.

**STR**:

* Create a new map from a (points) table
* In your layer, go to ADD ANALYSIS
* Select FILTER
* In the analysis configuration, select any of your columns in the `column` selector
* The red required tooltip will appear at the top-left corner and won't leave (even though all the fields are filled and the analysis is applied/created)

![image](https://cloud.githubusercontent.com/assets/1730320/16482939/788cdd9e-3eb2-11e6-9b2f-c9e6deb11198.png)

Here are the devtools in case it's helpful:

![image](https://cloud.githubusercontent.com/assets/1730320/16482998/aef5c3b4-3eb2-11e6-9848-a0d29ff41351.png)

**Comment by xavijam** [comment]
Yep, we are on it @iriberri, already reported in other issue, @javierarce could you point to that previous issue and close this one?

**Comment by iriberri** [comment]
Found it, sorry: https://github.com/CartoDB/cartodb/issues/7923

**Comment by xavijam** [comment]
❤️
