### ISSUE TITLE
Remove map lock in dashboard

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#8358]
Show this dialog when user visits the builder and the map is locked.

**Comment by csobier** [comment]
@xavijam , not sure if this is a separate issue but I am able to edit locked maps, even if no dialog appears. I probably should not be allowed to unless I unlock it.

**Comment by xavijam** [comment]
yes, same issue.

**Comment by noguerol** [comment]
This feature shows very low usage and is was thought for the always updated Editor maps, so there is no need to maintain it. We should remove it and default all the previously locked maps.

**Comment by csobier** [comment]
I really love the feature of maintaining my published maps in separate, "Locked" folder (especially on my team account so people know the "locked" maps are off limits).  I understand you want to remove this feature but will there be an alternative for storing select maps in another area of the dashboard?

**Comment by noguerol** [comment]
While I undertsand you, that is using the feature for a non intended purpose. We know we need a way to group maps and will be solved with the next version of the dashboard.
