### ISSUE TITLE
source layer name reverts after dragging an analysis

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#8360]
### STR
- Add a layer `A`
- Rename layer `A` to something like 'Metro Stations'
- Add Area of Influence analysis
- Drag the analysis node `A1` to create a new layer `B`
- The new layer `B` gets the name of the source layer `A`. The source layer reverts to its original name

### Expected result

The source layer `A` should keep its name. 
The new layer `B` should get a default name related to the analysis it comes from: `area_of_influence` or something like that

**Comment by saleiva** [comment]
very good report!
