### ISSUE TITLE
Zoom does not work when scrolling

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#8361]
### STR
- Scrolling in & out with the mouse.

### Expected result
- Map visualization should zoom in or out.

**Comment by xavijam** [comment]
That's due to the map options, it is disabled by default in all maps, like in the old editor.
When map options is done in the new builder, we will be able to change it.

**Comment by xavijam** [comment]
https://github.com/CartoDB/cartodb/issues/8302
