### ISSUE TITLE
Color entry field doesn't take the HEX input

### ISSUE THREAD

**Issue by fernando-carto** [CartoDB/cartodb#8363]
In Style tab, when trying to input an HEX color, it doesn't take it, even after clicking on other fields

1- Step #1 of smoke test
2- In step #2, I go to style and I try to add this HEX color f815f8 but the color remains the same. Even after going back and forth or changing the focus.
![captura de pantalla 2016-06-30 a las 12 46 25](https://cloud.githubusercontent.com/assets/19906145/16485728/c3372814-3ec0-11e6-83a6-5aec1e458b74.png)

**Comment by saleiva** [comment]
Thanks for reporting! :)

**Comment by javierarce** [comment]
This is a duplicate of https://github.com/CartoDB/cartodb/issues/7676

**Comment by saleiva** [comment]
It doesn't take the alpha neither the rgb values.
