### ISSUE TITLE
Infowindows or pop-ups

### ISSUE THREAD

**Issue by fernando-carto** [CartoDB/cartodb#8368]
Small detail (at all critical): now infowindows are called pop-ups, right?
It's little misleading when you see "infowindow" mentioned in this message
![captura de pantalla 2016-06-30 a las 13 22 51](https://cloud.githubusercontent.com/assets/19906145/16486615/2f024560-3ec6-11e6-9667-7e8ff2602d34.png)

**Comment by saleiva** [comment]
Well spotted! Thanks!
