### ISSUE TITLE
Update button does nothing

### ISSUE THREAD

**Issue by fernando-carto** [CartoDB/cartodb#8369]
1 - Click on "Share Map"
2 - I click on "Update" but the UI doesn't nothing.
3- Also I can't guess what "Update" is. Maybe some info-tip would help

**Comment by saleiva** [comment]
hey @urbanphes this could have something to do with the way the modal is designed. Can you check it with @nobuti?

**Comment by xavijam** [comment]
It will be available with the Snapshots/MapCap thing. We have to finish it basically :).
@nobuti @gfiorav

**Comment by gfiorav** [comment]
Deploy of this is minutes away!

**Comment by nobuti** [comment]
Actually it is already in the `mapcaps` branch.

**Comment by xavijam** [comment]
OOOOOOOOH YEAH, close it when it is working ;).

**Comment by gfiorav** [comment]
Deploy is underway, I'm closing this because it will be in prod in about 30 minutes.
