### ISSUE TITLE
Shareable map not accesible from outside

### ISSUE THREAD

**Issue by fernando-carto** [CartoDB/cartodb#8370]
- Map shareable by link is not accessible:

![captura de pantalla 2016-06-30 a las 13 31 32](https://cloud.githubusercontent.com/assets/19906145/16486746/01443f56-3ec7-11e6-8a5b-b53c6621707f.png)
https://team.cartodb.com/u/fernando-carto/8d4ca5bc-3eac-11e6-99ef-0ef7f98ade21/embed

**Comment by xavijam** [comment]
Could you take a look @juanignaciosl or @javitonino or @gfiorav?

**Comment by javitonino** [comment]
URL should be either of: 
https://team.cartodb.com/u/fernando-carto/viz/8d4ca5bc-3eac-11e6-99ef-0ef7f98ade21/embed_map
https://team.cartodb.com/u/fernando-carto/builder/8d4ca5bc-3eac-11e6-99ef-0ef7f98ade21/embed

Where did you take the URL from? Was it auto-generated?

**Comment by saleiva** [comment]
I think that URL is now on the share modal. @nobuti ?

**Comment by xavijam** [comment]
It is true, it is the url of the share dialog. Moved to https://github.com/CartoDB/cartodb/issues/8322.

**Comment by xavijam** [comment]
Thanks @fernando-carto.
