### ISSUE TITLE
Symbolizing by value > category reuses color for first two values

### ISSUE THREAD

**Issue by makella** [CartoDB/cartodb#8371]
In the store locator smoke test example, the step after creating 6 clusters is to color each cluster by `cluster_no` using categorical colors.

Even though six unique colors are shown in the style properties:

![screen shot 2016-06-30 at 1 23 54 pm](https://cloud.githubusercontent.com/assets/1566273/16486577/f88c219a-3ec5-11e6-9a3b-e7901c43f6a2.png)

And in TurboCarto:
```
marker-fill: 
ramp([cluster_no], 
(#A6CEE3, #1F78B4, #B2DF8A, #33A02C, #FB9A99, #E31A1C), 
("0", "1", "2", "3", "4", "5")
);
```
The last color (#E31A1C -- red) isn't getting applied. Instead, the first color, (#A6CEE3 -- light blue) is being applied to `cluster_no = 0` and `cluster_no = 1`:

![screen shot 2016-06-30 at 1 33 26 pm](https://cloud.githubusercontent.com/assets/1566273/16486803/456040e0-3ec7-11e6-89b7-6576dc25f13c.png)

**Comment by saleiva** [comment]
I think this is related with the issue on the way we generate category with turbo-carto. @javierarce, should this be fixed now that you fixed the other related issue?

**Comment by javierarce** [comment]
I think this issue is related to https://github.com/CartoDB/turbo-carto/issues/40

**Comment by saleiva** [comment]
Ok, after further research, the issue is that when the selected column contains numbers we still send the values as string (using "").

**Comment by javierarce** [comment]
@makella: I think this is working fine now. After I applied the style to the cluster analysis I obtained the following CartoCSS: 

``` marker-fill: ramp([cluster_no], (#ffc6c4, #f29ca3, #da7489, #b95073, #93345d, #672044), quantiles);```

Could you confirm it's working fine and in that case close this issue, please?

**Comment by makella** [comment]
@javierarce i did the same and got this.

`  marker-fill: ramp([cluster_no], (#5B3F95, #1D6996, #129C63, #73AF48, #EDAD08, #E17C05), (0, 1, 2, 3, 4, 5), category);`

Looks good to me!
