### ISSUE TITLE
pop-up window size parameter allow too small values

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#8375]
## Store locator smoke test. STEP 7

The pop-up configuration parameter `window size` allows the user to set too small values. 

## STR
- select a layer and go to pop-up settngs
- set a small value for `window size`, like `6`
- this happens

![screen shot 2016-06-30 at 15 20 05](https://cloud.githubusercontent.com/assets/10940006/16489798/5b660b76-3ed7-11e6-8132-a3cc0ab4734b.png)

## what's expected

the `window size` parameter could have a minimum permitted value that allows the popup to be correctly rendered

**Comment by saleiva** [comment]
Very good catch mate :)
@piensaenpixel suggest a min value for this.

**Comment by piensaenpixel** [comment]
sorry! 200px :)
