### ISSUE TITLE
Alignment on head elements

### ISSUE THREAD

**Issue by urbanphes** [CartoDB/cartodb#8381]
Both arrows aren't aligned and the size of arrow right must be smaller

Now 
![image](https://cloud.githubusercontent.com/assets/14546701/16493795/1ba27e1a-3ee7-11e6-82b3-51c76830804b.png)

to change by
![image](https://cloud.githubusercontent.com/assets/14546701/16493817/2f962584-3ee7-11e6-8eb0-2af459d47366.png)

**Comment by saleiva** [comment]
detalles, detalles, detalles
