### ISSUE TITLE
Cluster analysis in smoke-test doesn't seem to work

### ISSUE THREAD

**Issue by fernando-carto** [CartoDB/cartodb#8385]
As soon as I click "create" in the dialog of "Cluster" analysis, all the points disappear (there is no cluster column in the table view either)

**Comment by vuxita** [comment]
related: https://github.com/CartoDB/cartodb/issues/8397

**Comment by michellechandra** [comment]
I am also getting this error, nothing is loading when I apply the Cluster analysis (step 2).

**Comment by xavijam** [comment]
Right, there is something failing, but there is no error message. I've checked the definition that is sent to the Maps API and looks correct, could you take a look @rochoa or @dgaubert ?

<img width="394" alt="screen shot 2016-07-02 at 12 38 06" src="https://cloud.githubusercontent.com/assets/132146/16539923/f90f41dc-4051-11e6-95fa-cd47a48e9a26.png">

**Comment by rochoa** [comment]
Can you share a link to any of the problematic visualisations?
