### ISSUE TITLE
Input Parameter for Area Of Influence tool

### ISSUE THREAD

**Issue by cartodave** [CartoDB/cartodb#8394]
The inputs for walk/drive time now are in seconds. This means that a user would have to know, or rather, google, how many seconds are in 15 minutes and so on. Would it be possible to make the input be minutes instead? Might be easier for users to understand. 

![enhancement2](https://cloud.githubusercontent.com/assets/15348234/16506268/80b48b9e-3ede-11e6-84af-c052b70b70df.JPG)

**Comment by saleiva** [comment]
dupe! Thanks!
