### ISSUE TITLE
Link Layers analysis in smoke-test doesn't work

### ISSUE THREAD

**Issue by vuxita** [CartoDB/cartodb#8397]
When trying to create a 'link layers' analysis and clicking the 'Apply' button, there is nothing happening - the loading icon doesn't appear neither an error message (not even in the console).

![image](https://cloud.githubusercontent.com/assets/1730320/16517665/048a832e-3f7f-11e6-9ba5-00d0678c4840.png)

**Comment by xavijam** [comment]
Closing this one due to the fact that we have one reporting the same problem. 💋 
https://github.com/CartoDB/cartodb/issues/8385
