### ISSUE TITLE
Pop-ups

### ISSUE THREAD

**Issue by erodespons** [CartoDB/cartodb#8400]
**Step 4 of Metro Madrid use case smoketest**

Tried to restyle the first layer and when creating the pop-up clicked on Hover and found this:

![screenshot 2016-07-01 12 23 01](https://cloud.githubusercontent.com/assets/7283363/16519095/0b9b45ce-3f87-11e6-8dd7-8635c98aecbd.png)

Moreover, click pop-ups are not working either. After selecting the style and parameters nothing happens when I click on a point.

**Comment by saleiva** [comment]
Hey @erodespons this was fixed yesterday. Can you try?
