### ISSUE TITLE
Consolidate delete elements

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#8403]
Think about the way we can consolidate how we delete elements
![image](https://cloud.githubusercontent.com/assets/1214201/16521982/f1aa3292-3f9a-11e6-8b28-aff102b319e2.png)

cc/ @urbanphes @saleiva

**Comment by urbanphes** [comment]
Let's do it like the layers module. With eye icon and dotted icon on the right side. 
The options will be: 

- Rename
- Delete widget...

![image](https://cloud.githubusercontent.com/assets/14546701/16525644/ac956d6c-3fad-11e6-9473-f66ce112732b.png)

cc/ @piensaenpixel @saleiva

**Comment by piensaenpixel** [comment]
This is fixed
