### ISSUE TITLE
Input text element font color in dark background

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#8405]
When on a dark background (like writing custom SQL) input text field have a white font color, making it unreadable

### STR
1 - Open a map
2 - Click on a layer and go to 'DATA'
3 - Click on the toggle at the bottom to activate the SQL editor, the background should turn to black
4 - Try and rename the layer: The font color is white, as the background is, so there is no way to see what we are writing **(1)**  unless we make a selection **(2)**

**(1)** ![screen shot 2016-07-01 at 16 17 32](https://cloud.githubusercontent.com/assets/10940006/16524187/6a0158ae-3fa7-11e6-94db-b6a1fed50c02.png)

**(2)** ![screen shot 2016-07-01 at 16 17 41](https://cloud.githubusercontent.com/assets/10940006/16524183/65ee7c56-3fa7-11e6-8ab8-f77791bf08fb.png)

### what's expected
the font color should be dark

**Comment by xavijam** [comment]
Well spotted man :)
