### ISSUE TITLE
If map instantiation fails, createDashboard method doesn't throw error state 

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#8414]
If we update our internal dependencies (cartodb.js, deep-insights.js,...), we have checked that deep-insights-integration specs are not passing. After a deep check, looks like that if we make fail the map instantiation, nothing is rendered in the builder, so looks like that the error callback is not arriving correctly.

**Comment by xavijam** [comment]
Please, let's take a look as soon as possible on Monday :).

**Comment by alonsogarciapablo** [comment]
Should be fixed now!
