### ISSUE TITLE
Design map options block

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#8415]
We haven't found any design about the image below in the builder.

![](https://cloud.githubusercontent.com/assets/132146/16431972/4d37150e-3d83-11e6-9cfc-133191486d09.png)

@nobuti has implemented it but we need some better looking :).

**Comment by saleiva** [comment]
Its on the white lateral panel when clicking the settings icon in the blue
bar. I'll attach the mock-up in a while.

**Comment by saleiva** [comment]
![screen shot 2016-07-03 at 00 26 25](https://cloud.githubusercontent.com/assets/132149/16542729/d7cea2fc-40b4-11e6-9104-48ed1687d05c.png)

But let's remove the 1st step for the time being :)

**Comment by xavijam** [comment]
Widgets column option is not ready, we can't add it right now, @nobuti, create a ticket for that please.
Also, i guess there is a map title above this panel right?

**Comment by xavijam** [comment]
Closing, it is being implemented.
