### ISSUE TITLE
code turbocartocss

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#8423]
I love turbocartocss but when i try editing advanced cartocss I'm a bit lost. I don't know which color is assigned to each category. Maybe we could add it as a comment at the top of the code, something like this:

/*
    building: #dddd;
    whatever: #A6CEE3
*/
# layer {

  polygon-fill: ramp([type], (#DDDDDD, #A6CEE3, #1F78B4, #B2DF8A, #33A02C, #FB9A99, #E31A1C, #FDBF6F, #FF7F00, #CAB2D6), ("Others", "apartments", "farm", "house", "industrial", "residential", "roof", "school", "terrace", "yes"));
  line-width: 0;
  line-color: #3b0505;
  line-opacity: 1;
}

cc/ @saleiva @urbanphes

**Comment by javisantana** [comment]
what about use a monospace font and have

```
polygon-fill: ramp([type], 
     (#DDDDDD, #A6CEE3     ,red      ), 
     ("Others"    , "apartments", "farm")
);
```

**Comment by makella** [comment]
nice idea @piensaenpixel! i suggested changing the syntax which might help with this also where the attributes are listed first, and then the colors. see: https://github.com/CartoDB/turbo-carto/issues/48
