### ISSUE TITLE
Explore a way to explain the results of analysis that generate several columns

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8426]
Analysis such as Morans I or Spatial Markov generate a few columna a the result that might need to be explained.

**Comment by saleiva** [comment]
Cc/ @urbanphes

**Comment by javisantana** [comment]
from my point of view we should do many things here:

- find names for the columns so they explain what they mean
- split the analysis in different ones, for example for moran we could split it in hotspots, coldspots and outliers
- using the default styling for the analysis so it's self explanatory

> one map worth more than thousand words

**Comment by saleiva** [comment]
All that + an state of the analysis panel when the analysis ends
explainning the results for it. In some cases it might be very simple but
in other scenarios we will need a longer and better structured text.

**Comment by rochoa** [comment]
This is related to: https://github.com/CartoDB/cartodb/issues/8016.

**Comment by urbanphes** [comment]
Maybe we could use a info-box to explain that.

Something like this: <br>
![image](https://cloud.githubusercontent.com/assets/14546701/16556035/fed518bc-41d7-11e6-9db1-c7043b9d8f10.png)

cc/ @saleiva

**Comment by rochoa** [comment]
In some cases it might be really useful to add some widgets by default associated to those columns. We could make them temporal with a help text explaining why the user should add it and why the that column/widget matters. Then the user can decide to keep it or to remove it.

**Comment by urbanphes** [comment]
@javisantana ask me for the visual designs.

**Comment by saleiva** [comment]
Hey @urbanphes can you update here?

**Comment by urbanphes** [comment]
Here some examples of visual designs after apply analysis
<br>
**Message 1**<br>
![01 layers - 06-09 analysis - finished message 1](https://cloud.githubusercontent.com/assets/14546701/16756997/678ded98-4809-11e6-9b8a-eac4a6609681.png)
<br>
**Message 2**<br>
![01 layers - 06-10 analysis - finished message 2](https://cloud.githubusercontent.com/assets/14546701/16757016/8ca5018e-4809-11e6-88a0-f7d060ef467c.png)
<br>
**Message 3**<br>
![01 layers - 06-11 analysis - finished message 3](https://cloud.githubusercontent.com/assets/14546701/16757022/970085fe-4809-11e6-8e58-dbfae37981d6.png)

**Comment by saleiva** [comment]
Yep that's in a separate issue.

On Jul 4 2016, at 11:36 am, Raul Ochoa &lt;notifications@github.com&gt; wrote:  

> In some cases it might be really useful to add some widgets by default
associated to those columns. We could make them temporal with a help text
explaining why the user should add it and why the that column/widget matters.
Then the user can decide to keep it or to remove it.

>

> —  
> You are receiving this because you were mentioned.  
> Reply to this email directly, [view it on
GitHub](https://github.com/CartoDB/cartodb/issues/8426#issuecomment-230248702&r=cmVwbHkrMDAwMjA0MzUyMzAzOGI0ODk2NGY3ODc1NWRiMGJjMDBlNWI4YmU3ZmFkY2U0ZTkxOTJjZjAwMDAwMDAxMTM5MWYwMzE5MmExNjljZTA5YmZlZDM0QHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the
thread](https://github.com/notifications/unsubscribe/AAIENUlCrnFjj79D6mwP2X6iAqtnhJ24ks5qSNQxgaJpZM4JD6th&r=cmVwbHkrMDAwMjA0MzUyMzAzOGI0ODk2NGY3ODc1NWRiMGJjMDBlNWI4YmU3ZmFkY2U0ZTkxOTJjZjAwMDAwMDAxMTM5MWYwMzE5MmExNjljZTA5YmZlZDM0QHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notifications/beacon/AAIENVvXuaHe3iHgDd7gS_AYjx4WV_SUks5qSNQxgaJpZM4JD6th.gif)
