### ISSUE TITLE
New embed lacks of Google Analytics code

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb#8433]
cc @beloneys

**Comment by beloneys** [comment]
The current property where the embeds are being tracked is (UA-20934186-10).
Once we have https I'll do the set up for the new domain so I'll keep you updated.

Thxs!

B

**Comment by saleiva** [comment]
dont forget this please guys!

**Comment by xavijam** [comment]
![](images/composer-emoji/apple/1f44d.png)  

On Jul 7 2016, at 11:35 am, Sergio Álvarez Leiva
&lt;notifications@github.com&gt; wrote:  

> dont forget this please guys!

>

> —  
> You are receiving this because you were assigned.  
> Reply to this email directly, [view it on
GitHub](https://github.com/CartoDB/cartodb/issues/8433#issuecomment-231030458&r=cmVwbHkrMDAwMjA0MzI1MDUzYWNhNmE5OTQ3NWZkMzY4NzQ1YzUyYTZiMzA0NjQxMDczNWMwOTJjZjAwMDAwMDAxMTM5NWU0NjE5MmExNjljZTA5YzBkY2RlQHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the
thread](https://github.com/notifications/unsubscribe/AAIEMjHAErBIHqo22LZBnKcRXGoQuxp3ks5qTMhhgaJpZM4JEL7q&r=cmVwbHkrMDAwMjA0MzI1MDUzYWNhNmE5OTQ3NWZkMzY4NzQ1YzUyYTZiMzA0NjQxMDczNWMwOTJjZjAwMDAwMDAxMTM5NWU0NjE5MmExNjljZTA5YzBkY2RlQHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notifications/beacon
/AAIEMh6GCOd9UGt6XRP7PMa2Ezhfs-Bqks5qTMhhgaJpZM4JEL7q.gif)
