### ISSUE TITLE
Builder Redis performance

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#8439]
- [X] Find suitable limits.
- [X] Refactor redis.rb and load_resque.rb, which contain duplicated code for Redis. (#8535)
- [X] Change configuration file to enable 3 different timeouts.

cc @xavijam @javitonino

**Comment by juanignaciosl** [comment]
It's likely to be a general problem. I just created a map and the `imports` request (the polling for importing status) took 20s.

@luisbosque , @zenitraM , we've seen this "20s timeout" in several different requests, is that a default timeout that you remember?

**Comment by luisbosque** [comment]
The only thing I can think of is the statement timeout of public queries to the DB. Not sure how much is the timeout but it should be around that. It should not be related with imports though

**Comment by juanignaciosl** [comment]
DB timeout would probably trigger an error. Nevertheless those requests take 20 but they work.

Running `bundle exec rbtrace --ps "unicorn worker" --slow=5000` displays traces stuck on Hiredis methods, so we thing that it should be related to Redis.

**Comment by juanignaciosl** [comment]
It seems related to Redis. Running `$ bundle exec rbtrace --ps "unicorn worker" --slow=5000` leads to a bunch of threads stuck at

```
Hiredis::Ext::Connection#_read <20.096236>
                                                                                                                                                                          Hiredis::Ext::Connection#read <20.096279>
                                                                                                                                                                        Redis::Connection::Hiredis#read <20.096336>
```

Our current Redis timeout is 20s, which matches the symptoms (slow queries take slightly more than 20s). We're trying to split and lower the timeouts at #8466 so we can know if it's a connection or read timeout and improve. In addition, since requests seem to work it looks like there's a retry, so lowering the timeouts should mitigate the issue.

cc @javitonino @rochoa

**Comment by juanignaciosl** [comment]
@rochoa @luisbosque after changing from 20s to 2 (connection), 10 (read) and 15 (writes) clusters around 10s appear, so there's a problem with reads. Nevertheless requests doesn't fail but retry, so this patch is not too terrible.

Yesterday both slowlogs and latency checks were fine, so maybe we can lower the timeouts. What do you think about 2, 3, 5?

**Comment by rochoa** [comment]
Do we have any number on this?

To determine how frequent that situation is. I mean: is something that happens randomly, and we need to determine the cause, or is associated to some specific command?

If it's random I would go with more aggressive timeouts, otherwise I would try to narrow what the problem is because we might end having commands failing because of a more aggressive timeout.

**Comment by juanignaciosl** [comment]
Currently we have no actual hint about the reason. It might be related to CPU peaks because of `redis-rdb-bgsave` (see CartoDB/cartodb-platform/issues/1215) or chef client, but we haven't been able to find actual correlation. It happens quite frequently (>150/h).

We're going to review the connection usage, because we might need to close them, for example, on deployments. @javitonino has reported a big number of old, idle connections at Redis that might be related with this. I'd use 2, 3, 5 while we find the actual reason, is this ok for you?

**Comment by juanignaciosl** [comment]
FYI reducing the timeouts has led to a great reduction of requests beyond 5s:

![screen shot 2016-07-05 at 13 50 01](https://cloud.githubusercontent.com/assets/932968/16587507/3eab2ed8-42cb-11e6-91fa-3ac0084e1f08.png)
