### ISSUE TITLE
Public dataset view is not working with the new URLs

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8440]
It has to be exactly like the actual one, but with the new URLs
cc/ @xavijam 

https://team.cartodb.com/u/saleiva/dataset/scge_migration_2

**Comment by javitonino** [comment]
This is a redirect to the old URL (/tables/wadus/public), right?

Also /builder/id gives a 403 when not logged in. Should it also redirect to the embed?

**Comment by saleiva** [comment]
exactly, redirect to the old URL, but not to the embed, to the public view of the dataset

**Comment by javitonino** [comment]
:+1:
