### ISSUE TITLE
Updated "INVALID DATE" on embed

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8444]
![screen shot 2016-07-04 at 13 37 42](https://cloud.githubusercontent.com/assets/132149/16559326/8c5fe072-41ec-11e6-97db-e2bb72adbc5c.png)

https://team.cartodb.com/u/saleiva/builder/3b931d98-41ca-11e6-b9ba-0ecd1babdde5/embed

**Comment by gfiorav** [comment]
Thanks for reporting @saleiva, I know exactly what it is. Expect a fix in a couple of hours
