### ISSUE TITLE
Mapcap should save also states of the widgets 

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8463]

**Comment by gfiorav** [comment]
Isn't this what url state is for?

**Comment by saleiva** [comment]
Yep, but...

Imagine you create a map, use widgets for filtering the results. And then
send the link.
Without this, we are disconnecting the builder and viewer experience.

2016-07-04 18:13 GMT+02:00 Guido Fioravantti <notifications@github.com>:

> Isn't this what url state is for?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/8463#issuecomment-230321480>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAIENfCjV-z1PL7bUTq1YQ0z2pNTYf9Kks5qSTE5gaJpZM4JEfj9>
> .
>



-- 
Sergio Alvarez Leiva
