### ISSUE TITLE
State of the widgets is not 'persisted' on the builder.

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8464]
STR

Create a map
Add a widget histogram
Filter
Go to the dashboard
Go back to the map.

The widget should be filtering but it's not.

**Comment by gfiorav** [comment]
There is no API designed to persist the state of the embed. AFAIK you just get it were you want it and share that link, isn't that supposed to be like that?

**Comment by saleiva** [comment]
I'm talking about the editor. The map should remain the same. Imagine I
filter by 10 widgets, go to have lunch, and when I come back there is no
filter applied.

2016-07-04 18:14 GMT+02:00 Guido Fioravantti <notifications@github.com>:

> There is no API designed to persist the state of the embed. AFAIK you just
> get it were you want it and share that link, isn't that supposed to be like
> that?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/8464#issuecomment-230321668>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAIENXP02xVLF8kqtUZXHzw9YIJyPktqks5qSTF_gaJpZM4JEfmv>
> .
>



-- 
Sergio Alvarez Leiva
