### ISSUE TITLE
Auto-styling on widgets shoulnd't be available when having a point dataset aggregated by hexabins, squares or admin regions.

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8468]

**Comment by saleiva** [comment]
Looks like this could be happening again
https://www.fullstory.com/ui/2A7A7/session/5402923928387584:(5676081478631424!5629499534213120(5707702298738688(763015)))

**Comment by saleiva** [comment]
Yep I can replicate it. After aggregating in the style panel, if you go to the data panel of the layer, and select one of the columns, when adding the widget, the auto-style button will still be there.

**Comment by saleiva** [comment]
Would love to prioritize this, but leaving this to you guys :)

**Comment by xavijam** [comment]
Deploying to ded04 for testing purposes.
