### ISSUE TITLE
Smoke test: Link to layer analysis

### ISSUE THREAD

**Issue by fernando-carto** [CartoDB/cartodb#8477]
Although I managed to do the link to layer analysis, today I accessed the link to layer section and I found a "no values" in LINKED LAYER COL. I cannot even choose any column.

![captura de pantalla 2016-07-04 a las 20 36 30](https://cloud.githubusercontent.com/assets/19906145/16568186/68ad87c0-4227-11e6-873f-333a968974ae.png)

**Comment by saleiva** [comment]
but does the loading ever finish?

**Comment by fernando-carto** [comment]
I'm attaching screenshots (in reverse order) of the three steps:
1- The link to layer analysis is configured and working well.
2- I leave the link to layer analysis section. It's still working well.
3- I get back to link to layer analysis, but I get a "no values" in the field where I had chosen "line"
![captura de pantalla 2016-07-05 a las 16 29 20](https://cloud.githubusercontent.com/assets/19906145/16588217/75693868-42ce-11e6-983b-36ab10f1bbc3.png)
![captura de pantalla 2016-07-05 a las 16 29 12](https://cloud.githubusercontent.com/assets/19906145/16588218/757bf2be-42ce-11e6-95f9-d011ac704624.png)
![captura de pantalla 2016-07-05 a las 16 29 04](https://cloud.githubusercontent.com/assets/19906145/16588219/757d9dee-42ce-11e6-80c6-2e3666f337cb.png)
