### ISSUE TITLE
Commenting out lines in CartoCSS Editor with // Does not work

### ISSUE THREAD

**Issue by makella** [CartoDB/cartodb#8480]
In the CartoCSS editor, you can comment lines out using `/* ... */` but if you comment a line out with `//...` your changes do not apply. You aren't provided an error so it can be confusing why you aren't seeing the changes on your map.

**Comment by nobuti** [comment]
@makella not sure if I understand the issue, but I can see both types of comments working:

![comments](https://cloud.githubusercontent.com/assets/1366843/16727422/4a906368-4761-11e6-85ad-4c392d0999c3.gif)

Could you give me some more details?

**Comment by makella** [comment]
hi @nobuti! 

I will try and reproduce. I thought maybe it was fixed towards the end of last week because I wasn't running into so many issues with commenting out.

What I was noticing is that if I had commented a line out using `//` that the CartoCSS was not refreshing. 

If I notice it again, I will paste the specific syntax here so you can see.

thanks!

**Comment by nobuti** [comment]
Closing this for now, feel free to reopen it
