### ISSUE TITLE
turbo-carto error after exporting image of cluster or density map

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartodb#8485]
### Summary:

When a user set the map wizard as Cluster or Density map, the  "Export image" option doesn't work and return a turbo-carto message error. The other wizard options work correctly.

However, if the privacy of the dataset is set as "public" or "with link", the problem doesn't happen and CartoDB generates the image.
#### Steps:
1. Import a file with point geometries to CartoDB.
2. Once the file has been imported and the dataset created, create a map from the dataset. (The dataset created is set with private privacy)
3. Without changing anything else, choose the cluster or density map of the CartoDB wizards.
4. Click on the Export image option and then `Export` .
5. CartoDB returns an error with this message **`turbo-carto: permission denied for relation table_29`** Where table_29 is the name of the dataset.

If the privacy of the dataset is changed to "public" or "with link", when we apply the steps 3 and 4, CartoDB generates correctly the image.

**Comment by xavijam** [comment]
Taking it into account for new Builder implementation 💋 .
