### ISSUE TITLE
Review DataImport.running_import_ids

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#8488]
This queries Redis for all enqueued jobs (a somewhat of heavyweight query). It is used to determine which jobs are stuck, but it is actually being run on each /imports requests, which seems unnecessary. Review usage, and see if this can be improved.

cc/ @gfiorav @juanignaciosl

**Comment by javitonino** [comment]
Correction: this actually lists the running job in each of the resque workers (`Resque::Worker.all`). But still, I think it is called multiple times and could be improved. But is not as bad as I initially thought.

**Comment by juanignaciosl** [comment]
Closing automatically because of inactivity. If anybody considers that this still important, please reopen and it'll be prioritized.
