### ISSUE TITLE
Animated maps: Trails limits

### ISSUE THREAD

**Issue by miguelarias** [CartoDB/cartodb#8490]
ANIMATED Maps: Trails is set to be between 0 and 10, and in many cases it is great to be able to add another value numerically in the box (like 20-30) for a nicer visual effect. Twitter uses this a lot. 

I propose you take out that limitation, as was the behavior in the Editor.

BTW, when applying trails after the limit error message appears, with a new value between 0 and 10, I get no visible effect when applying a different number there, and the CartoCSS code is not changing from the default Torque code.

**Comment by saleiva** [comment]
We need a limit anyway. We can change it to 30.

**Comment by miguelarias** [comment]
Can you keep the limit in the interface? but do not limit or make it quite
big for the numerical entry? Like 50?

On Tue, Jul 5, 2016 at 12:13 PM, Sergio Álvarez Leiva <
notifications@github.com> wrote:

> We need a limit anyway. We can change it to 30.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/8490#issuecomment-230440031>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AG-h8jLDSNsDpiy0rMJHJc_gUXW6eKb0ks5qSi48gaJpZM4JE8if>
> .
>



-- 
*Miguel Arias*
COO

*CartoDB—Map Your World's Data*
201 Moore Street, 11206, Brooklyn
T Sp: *+34 607654697* T US: *+1 3478240358*
T Office:
*+1 9174633232*Skype: miguel.arias
W: www.cartodb.com

Live sessions to learn CartoDB <http://cartodb.com/webinars/>

Please consider the environment before printing this email

**Comment by xavijam** [comment]
0-50, 👍

**Comment by saleiva** [comment]
yes please

**Comment by saleiva** [comment]
no no 50
it's a mess. and it could not work correctly. 30

**Comment by xavijam** [comment]
👍
