### ISSUE TITLE
[pop-up] Picture Header pop-up interface has no holder to add the picture-URL

### ISSUE THREAD

**Issue by miguelarias** [CartoDB/cartodb#8493]
It states that the picture URL is not valid, but it is not clear where the picture url should be selected and in which order. Either a checkbox to select it on that interface or a little explanation on the workflow will be needed

**Comment by saleiva** [comment]
Agreed. We missed that @urbanphes

**Comment by urbanphes** [comment]
This module is not finished. Both "pop-up color" as in "pop-up image" missing fields but I think we need re-think this module in both cases. Doesn´t works.

cc/ @saleiva

**Comment by urbanphes** [comment]
We maintain the same behavior that current editor. 
<br>
The text "NON-VALID PICTURE URL" works like a link and ... <br>
![image](https://cloud.githubusercontent.com/assets/14546701/16610790/ccfdfe3a-435d-11e6-86a5-5d74e9c17eb1.png)
<br><br>
... shows a window modal with some tips.<br>
![image](https://cloud.githubusercontent.com/assets/14546701/16610809/f0efb018-435d-11e6-9572-e8d155e7c4ba.png)

cc/ @saleiva
