### ISSUE TITLE
[FILL COMPONENT] Category styling doesn't work with more than 10 categories

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8496]

**Comment by saleiva** [comment]
It doesn't work with 2 categories neither

**Comment by javierarce** [comment]
Besides the problem with the 10 categories, I'll fix a bug that prevented choosing boolean columns.

However, when I choose a boolean column, this is the CartoCSS that is generated:

```
#layer {
  line-width: 0.5;
  line-color: #FFF;
  line-opacity: 1;
  polygon-fill: ramp([adm_bool], (#0fa0ec, #b4a51f), ("false", "true"));
}
```

The result is a monochromatic map:

![screen shot 2016-07-12 at 17 07 59](https://cloud.githubusercontent.com/assets/4933/16772128/3956e6a6-4853-11e6-8f74-17c0e00255fa.png)

**Comment by javierarce** [comment]
Although if the column is cast to strings, it seems to work fine:

 
```
#layer {
  line-width: 0.5;
  line-color: #FFF;
  line-opacity: 1;
  polygon-fill: ramp([adm_str], (#A6CEE3, #1F78B4), ("false", "true"));
}
```
![screen shot 2016-07-12 at 17 16 59](https://cloud.githubusercontent.com/assets/4933/16772421/83343d4a-4854-11e6-8c07-cced56172258.png)

What was exactly your problem, @saleiva?

**Comment by saleiva** [comment]
Sorry, I was talking about numeric columns

**Comment by rochoa** [comment]
Quick update: I'm working on a revamp of turbo-carto that addresses some of the issues described in this issue. Most of them related to category ramps and column type casting.

**Comment by javierarce** [comment]
Great, @rochoa. My fixes are still necessary, so I'll create a PR.
