### ISSUE TITLE
Visualization import should redirect to the map

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#8509]
Importing the visualization should redirect to the map. Currently it causes a glitch if dashboard was empty:

![screen shot 2016-07-05 at 16 37 34](https://cloud.githubusercontent.com/assets/932968/16589171/32220310-42d2-11e6-82ff-5c61bad4dbb9.png)

cc @gfiorav @xavijam

**Comment by gfiorav** [comment]
What are we supposed to see in the image? I'm seeing a part of a PR, is this intended?

**Comment by juanignaciosl** [comment]
Fixed 😅

**Comment by juanignaciosl** [comment]
I don't know what happened previously but I can't reproduce, it redirects.
