### ISSUE TITLE
Dark popups display a white close button

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#8514]
When adding popups to a map, it will always display an scrollbar in Firefox, even when there is enough room for all the selected fields. The scrollbar only scrolls 1 pixel.

![screenshot_20160705_173050](https://cloud.githubusercontent.com/assets/7569673/16590206/e2a08b54-42d6-11e6-93e3-f9b01b9332ad.png)

Bonus track: the close button is using a light background even with the dark theme.

**Comment by javitonino** [comment]
Moved to #8609

**Comment by javitonino** [comment]
Reopening because of bonus track, which I think should also be addressed (white close button on dark background)

**Comment by javitonino** [comment]
Just noticed, scrollbars are back on Firefox

**Comment by matallo** [comment]
I think this is a better addressed discussion to @CartoDB/design 

closing then

/cc @piensaenpixel
