### ISSUE TITLE
Incorrect integer parsing from XLS files

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#8517]
When importing a XLS file with mixed content in one column (e.g.: integer and strings), the integers get parsed as strings with a `.0` adding at the end. 

XLSX files got parsed as expected.

We can expect the numbers to be parsed as strings, since there is a row with text in the same column. The issue is the `.0` that is added to the value.

This is reproducing both in production and onpremise (tested in v1.2.1 and v1.3.0)

Sample data:
[test.zip](https://github.com/CartoDB/cartodb/files/348140/test.zip)

### 1
- Import `dummy_dataset.xls` from the sample data
- Integers from column `d` get parsed as `456.0` (string)

### 2
- Import `dummy_dataset.xslx` from the sample data
- Integers from column `d` get parsed as `456`

## Expected result
The numbers should get imported as strings, since there is a row with text, but shouldn't have the `.0` ending

**Comment by ethervoid** [comment]
This problem comes from csvkit, we use in2csv to parse xls or xlsx files to csv in the import process.

Seems like in2csv behaves differently for xls and xlsx:

```
ubuntu@cdb-dev:/tmp$ in2csv dummy_dataset.xls
a, b, c,lat,lon,d
1.4326,true,thisIsText,37.34,-2.78,234.0
2.3857,false,soIsThis,40.34,-1.94,567.0
,,,,,text
ubuntu@cdb-dev:/tmp$ in2csv dummy_dataset.xlsx
a, b, c,lat,lon,d
1.4326,true,thisIsText,37.34,-2.78,245
2.3857,false,soIsThis,40.34,-1.94,567
,,,,,text
```

I'll ask the owner of the project about this

**Comment by ethervoid** [comment]
https://github.com/wireservice/csvkit/issues/639#issuecomment-232382999

**Comment by pavanvamsi3** [comment]
You can use this small script to get over the issue:
https://github.com/pavanvamsi3/random-scripts/blob/master/dot_scripy.py
