### ISSUE TITLE
Make sure URL for mobile SDK on share window is correct

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8520]
AFAIK it was the same than the vizjson, right @jaakla ?

**Comment by nobuti** [comment]
According to this issue https://github.com/CartoDB/cartodb/issues/7278, it should be `mapView.loadCartoDbMap("6823d7c0-0bca-11e6-bc90-0e5db1731f59");`

**Comment by saleiva** [comment]
ok!

**Comment by jaakla** [comment]
This `mapView.loadCartoDbMap("6823d7c0-0bca-11e6-bc90-0e5db1731f59");` was a placeholder, not final command the real line is different in different languages (mobile SDK supports Java, ObjC, Swift, C#, JS in future). We can only put same viz.json URL as in CartoDB.JS window, and actual line comes from manuals. Also this URL approach would work in on-premises cases.

**Comment by saleiva** [comment]
@nobuti hey hey hey
