### ISSUE TITLE
[basemaps] wms select layer modal

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#8537]
I couldn't find the select layer modal designed in the wms tab for basemaps (find attached)

I'll leave this out in the meantime

![screen shot 2016-07-06 at 09 56 20](https://cloud.githubusercontent.com/assets/36676/16611195/1096d98a-4360-11e6-942d-318eea5e04b6.png)

/cc @javisantana

**Comment by urbanphes** [comment]
The same structure is maintained but with the new visual appearance.
