### ISSUE TITLE
Histogram expects `column` in widget options error

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#8541]
STR

1. Create a map with a point dataset.
2. Set layer style aggregation: pixel. There's a 400 error:

Request:

GET `/api/v1/map/babae0a4123ae995ce8fb66eba5f6f89:1464964413734/dataview/51101a3e-577f-440e-af88-598048432d1c?bins=256&api_key=<api_key>'

Response:

```
{
  "errors": ["Histogram expects `column` in widget options"],
  "errors_with_context":[{"type":"unknown","message":"Histogram expects `column` in widget options"}]
}
```

A timeseries widget is added to the dashboard but it's greyed out, won't work.

The previous request had been a POST containing this for `dataviews`:

```
"dataviews": {
  "51101a3e-577f-440e-af88-598048432d1c": {
    "type":"histogram","source":{"id":"a0"},"options":{"column":null,"bins":256}
  }
}
```

I guess that the `column: null` can be related.

cc @xavijam @alonsogarciapablo @rochoa

**Comment by xavijam** [comment]
@fdansv, could you check it please?

**Comment by fdansv** [comment]
This should be fixed as soon as we merge https://github.com/CartoDB/cartodb/pull/8503 , where we add a column chack before asking for the histogram.

**Comment by fdansv** [comment]
As far as I can see this is not happening anymore.
