### ISSUE TITLE
Aggregation column in a category widget

### ISSUE THREAD

**Issue by fernando-carto** [CartoDB/cartodb#8542]
Hi guys,
After seeing on of the video, I decided to run a Moran Analysis on the customer data of the smoke test. It's pretty cool!!
After that, I added a category widget with aggregation column "quad" and value "SUM of customer value". I would expect the aggregation of the four categories (LL, HL, LH and HH), but I get an aggregation  by customer value (100, 80, ...)
Bottom line, I think the fields Value and Aggregation column are swapped in the UI.
Am I wrong or is there a bug?
![captura de pantalla 2016-07-06 a las 10 14 59](https://cloud.githubusercontent.com/assets/19906145/16611851/3a1c264e-4364-11e6-851c-b95c12f9f41d.png)

**Comment by saleiva** [comment]
You need to change the COUNT to SUM, right?

**Comment by fernando-carto** [comment]
COUNT and SUM both work well.
But I think that the UI label "VALUE" should be changed by "AGGREGATION COLUMN" and the "AGGREGATION COLUMN" for "VALUE".

**Comment by javisantana** [comment]
I think changing "VALUE" by "CATEGORY COLUMN" is better right?

**Comment by fernando-carto** [comment]
Exactly. Or "CATEGORY BY"... 
Thanks guys
