### ISSUE TITLE
Error adding layer importing a file

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#8548]
STR

1. Open a map.
2. Add new layer by dropping a dataset file within the add layer modal.
3. Layer gets imported, but a JS error appears at the console on the rerendering:

```
tracker.js:26
Uncaught Error: TrackJS Caught: Cannot read property 'remove' of undefined
wrapError @ tracker.js:26
d.util.hasFunction.f.(anonymous function) @ tracker.js:4
```

cc @xavijam

**Comment by xavijam** [comment]
Yes, that happens to me, it is related with the Notifier, I'll take a look later.
cc @nobuti
