### ISSUE TITLE
Commerce & Economy data observatory option rendering wrong

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#8554]
![screen shot 2016-07-06 at 12 05 37](https://cloud.githubusercontent.com/assets/932968/16614992/124c6cea-4374-11e6-9730-7fb1f1caa612.png)

cc @xavijam

**Comment by xavijam** [comment]
Already checked in production and seems like it is fixed:

![screen shot 2016-07-15 at 10 56 46](https://cloud.githubusercontent.com/assets/132146/16868990/e8bb2ffc-4a7a-11e6-903e-e895add48ad1.png)
