### ISSUE TITLE
Importing percentage gets splitted

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#8555]
Minor style issue: importing % gets splitted in lines.

![screen shot 2016-07-06 at 12 34 21](https://cloud.githubusercontent.com/assets/932968/16615303/09bb8d48-4376-11e6-8166-28d8ad01c206.png)

cc @xavijam

**Comment by xavijam** [comment]
I don't know why we decided to wrap the words, @nobuti?

**Comment by nobuti** [comment]
Some times the table name are concatenated with underscores, and it gets too long, we need to force breaks, not sure how to avoid it.

**Comment by saleiva** [comment]
BTW, let's round the number to 0 decimals :) and lets put the % at the beginning of the sentence
