### ISSUE TITLE
Infowindow for layers created from analysis not working

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#8558]
This was spotted during "Store locator based on customer data" smoke test, playing with infowindows after step 8, but I've reproduced it with a simpler example.

STR

1. Import a point dataset ([example](https://raw.githubusercontent.com/juanignaciosl/test-data-repository/master/twitter_t3chfest_reduced.csv)).
2. Add a weighted centroid analysis (weighed by retweetcou, for example).
3. Drag & drop analysis node so it creates a new column.
4. Add a popup.

In the builder it won't work at all (you can't click). Opening the embed displays this:

![screen shot 2016-07-06 at 12 43 39](https://cloud.githubusercontent.com/assets/932968/16615486/4a4cc3c6-4377-11e6-9b93-1b6143647f8e.png)

cc @matallo @xavijam

**Comment by saleiva** [comment]
hey @matallo whenever you can, don't forget abou this

**Comment by matallo** [comment]
as just discussed, this might be related to an issue @viddo is working, waiting for updates on that front

**Comment by viddo** [comment]
@matallo see #8749, the cachebust will make sure the query-schema model will side-step the cached requests (try locally, not deployed just yet)

**Comment by matallo** [comment]
not sure if related, but after updating I'm able to reproduce a different bug:
- it won't open the popup *just after* creating the analysis, once you reload (even if no fields are selected) it would work fine
- embed issue still happening, I think I can debug it myself

who shall I be talking to for this @xavijam?

**Comment by matallo** [comment]
templates fixed https://github.com/CartoDB/cartodb/pull/8801

**Comment by alonsogarciapablo** [comment]
This should be fixed now.
