### ISSUE TITLE
Notifier is not showing progress when adding a layer from a file

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8564]

**Comment by xavijam** [comment]
I feel it does, but in any case, @nobuti, could you check it?

**Comment by nobuti** [comment]
I can see the progress, I simulated it on low speed connection using the throttle network on dev tools panel and it's there.

**Comment by saleiva** [comment]
Is it on production?

**Comment by nobuti** [comment]
Nope, only master. There are some changes to be test before to deploy them.

![percentage](https://cloud.githubusercontent.com/assets/1366843/16636366/f5b18930-43d7-11e6-9815-086daf31ffca.gif)

**Comment by saleiva** [comment]
Looks good. Let's see! Are the design changes also in that branch?
@piensaenpixel?

2016-07-07 0:16 GMT+02:00 Buti <notifications@github.com>:

> Nope, only master. There are some changes to be test before to deploy them.
>
> [image: percentage]
> <https://cloud.githubusercontent.com/assets/1366843/16636366/f5b18930-43d7-11e6-9815-086daf31ffca.gif>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/8564#issuecomment-230923827>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAIENXLLcNu08Wh8mpK3NhR49jXr5iiwks5qTCk0gaJpZM4JGCb4>
> .
>



-- 
Sergio Alvarez Leiva

**Comment by nobuti** [comment]
Closing this, fine tune styles on #8555.
