### ISSUE TITLE
Add Added Columns options to Intersection -> Filter Analysis

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8569]
![screen shot 2016-07-06 at 15 50 56](https://cloud.githubusercontent.com/assets/132149/16620136/8fcf6696-4391-11e6-96c8-8cde76ffafb9.png)

So those from the polygons get on the points.

**Comment by javierarce** [comment]
Is this already supported by the API, @rochoa?

**Comment by saleiva** [comment]
Hey, good news. All columns are being added by default so closing this.
