### ISSUE TITLE
Wrong style when changing geometry type on an analysis

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8571]
STR

- Create an intersection analysis between polygons and points, selecting the Filter option.
- This will render a map with points.
- Edit the analysis parameters to make an aggregation analysis.
- This will render a map with polygons.
- Edit the analysis parameters (again) to make a filter analysis.
- This will render a map with points.
- Edit the analysis parameters (again) to make an aggregation analysis.
- This will render a map with points - ERRR!

**Comment by javisantana** [comment]
this is because the frontend fetchs a cached query which is not invalidated and it can't know the geometry type (it defaults to points)

it will be fixed in maps api

cc @rochoa

**Comment by javisantana** [comment]
hey, we are having several issues frontend side because of this so, I'd add a cache buster in queryschemamodel in the meantime.
