### ISSUE TITLE
Super silly thing: order of coloring by value

### ISSUE THREAD

**Issue by fernando-carto** [CartoDB/cartodb#8583]
Is there a way to reverse the order of the colors in the color scales (brewers and stuff) for coloring by value? It would be useful in the future.

In case you want to keep it simple, I'd pick light colors to low values if the field. Now fields with the low value get intense colors, which for me me in counter-intuitive. See attachment: cluster with value 0 gets the darkest color.

Sorry guys if I'm being a pain in the ass, specially these days :) 

![captura de pantalla 2016-07-06 a las 19 15 30](https://cloud.githubusercontent.com/assets/19906145/16627717/cb543666-43ae-11e6-8b8b-f6afb652838c.png)

**Comment by saleiva** [comment]
You are doing great, don't worry ;)

**Comment by saleiva** [comment]
It's a dupe BTW :)
