### ISSUE TITLE
Column Ordering 

### ISSUE THREAD

**Issue by michellechandra** [CartoDB/cartodb#8593]
Column ordering while in Data View of a new map appears to be random. Should column ordering be alphabetical so users can quickly find columns by scrolling to select a column (for users who prefer to scroll over text search)?

Appears in several places in UI:
-Data View list of columns when in Map View
-Style by Value list of columns
-Data View of a table (not when in Map View)

**Comment by xavijam** [comment]
All of them appear as it is received from the query. If you want them in an specific order, you can do it applying a different query. There were lot of requests about this, respecting the query column order. So for me it is a great addition, I must say. Also, if you want to find a column in the style tab, dropdown has a search box.
