### ISSUE TITLE
No stroke properties available when using a color ramp

### ISSUE THREAD

**Issue by makella** [CartoDB/cartodb#8595]
If you apply a color ramp to a polygon dataset, the stroke properties are disabled and you get the always funny looking gaps in between each polygon (which can be accounted for by adjusting `polygon-gamma`):

<img width="463" alt="screen shot 2016-07-06 at 11 05 36 pm" src="https://cloud.githubusercontent.com/assets/1566273/16634516/64fe8a9a-43ce-11e6-8fab-6b01b5fc2bc1.png">

The only way to add an outline is to go to the CartoCSS and add it there same with opacity.

I have defaults to add when ready!

**Comment by saleiva** [comment]
Hey @makella I can configure the stroke with no problems...

**Comment by makella** [comment]
can we do it as default cartocss? there are a couple of properties to set that are outside of the options available in the form... or only form?

**Comment by saleiva** [comment]
We should either use only form ooptions or extend the form options if we
think is the best

2016-07-06 23:13 GMT+02:00 Mamata Akella <notifications@github.com>:

> can we do it as default cartocss? there are a couple of properties to set
> that are outside of the options available in the form... or only form?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/8595#issuecomment-230908633>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAIENUQk5y0zjLhXjLoGuNSRuTIWG3gfks5qTBpxgaJpZM4JGgPX>
> .
>



-- 
Sergio Alvarez Leiva

**Comment by makella** [comment]
ok then for now, let's use this

```
 polygon-opacity: 0.9;
  line-color: #fff;
  line-width: 0.5;
  line-opacity: 0.8;
```
that is all form ready.

**Comment by saleiva** [comment]
which color?

2016-07-06 23:18 GMT+02:00 Mamata Akella <notifications@github.com>:

> ok then for now, let's use this
>
>  polygon-opacity: 0.9;
>   line-color: #fff;
>   line-width: 0.5;
>   line-opacity: 0.8;
>
> that is all form ready.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/8595#issuecomment-230910030>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAIENTlqfd3Wahe1WfBSij1Fcjx-02iKks5qTBuvgaJpZM4JGgPX>
> .
>



-- 
Sergio Alvarez Leiva

**Comment by makella** [comment]
oh sorry... so this is when you symbolize by numeric value on polygons (choropleth) the line options don't exist. So we can put in the defaults above for color value by polygon. The fill color will come from the ramp. Also, if we could add the 0.9 polygon opacity, that would be awesome.

**Comment by saleiva** [comment]
They exist! Or am I getting this wrong?

**Comment by makella** [comment]
weird. this is what i was seeing. let me try a new map or something.

<img width="325" alt="screen shot 2016-07-06 at 11 03 21 pm" src="https://cloud.githubusercontent.com/assets/1566273/16644947/c51d6e4e-4420-11e6-83f7-fb81205e3b90.png">

**Comment by makella** [comment]
@saleiva ok, its there now. but clearly looks horrible 

![screen shot 2016-07-07 at 8 58 40 am](https://cloud.githubusercontent.com/assets/1566273/16645014/1ce2edfc-4421-11e6-996c-409b7443a0bf.png)
