### ISSUE TITLE
Intersection analysis needs to be split

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#8602]
Right now it is "Filter" and "Aggregate". Those need to be discoverable in two separate locations, so we should just split.

https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb3/editor/layers/layer-content-views/analyses/analysis-form-models/intersection-form-model.js

cc @javierarce

**Comment by xavijam** [comment]
Already done! 💃
