### ISSUE TITLE
The CartoDB logo is still showing up even when I unmark the option on the Builder settings

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#8611]
@arianaescobar

- I unmarked the "CartoDB logo" option on the Settings tab
- The logo is still showing up on the map and on the builder

**Comment by xavijam** [comment]
Although I think it is a problem from CartoDB.js. Let's take a look together later @nobuti

**Comment by nobuti** [comment]
I can reproduce it locally, not sure if the problem is the dependency declared in the package.json.

**Comment by nobuti** [comment]
_can't_
