### ISSUE TITLE
Dataset view horizontall scroll do not respond to mouse

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb#8612]
When the columns don't fit in the window, the horizontal scroll bar responds to shift + scroll wheel, but not to mouse events as drag or clicking the arrows on both ends.

**Comment by danicarrion** [comment]
I can reproduce, Chrome on Linux

**Comment by javitonino** [comment]
There is a div (`.Dataset-options::before`) covering the scrollbar, which makes it not to work. It appears to be used to fade the last rows of data, but covers the scrollbar instead when it appears.
