### ISSUE TITLE
Write explanations for intact and dissolved 

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#8619]
In the area of influence analysis we should explain what `intact` and `dissolved` means. I'll be adding a way to include help tooltips inside the radio button options… in the meantime, could you write a short explanation for each of those concepts?

**Comment by saleiva** [comment]
Wow, can we do them way shorter? This is for an small tooltip that appears when hovering...

**Comment by ohasselblad** [comment]
Here ya go:
Dissolved: Combine polygons tracts with equal ranges
Intact: Keep all polygon tracts as individual polygons

**Comment by saleiva** [comment]
awesome :)

**Comment by javierarce** [comment]
Thanks, @ohasselblad! Here's the PR for this change: https://github.com/CartoDB/cartodb/issues/9416
