### ISSUE TITLE
Select placeholder should be customizable (instead of showing the param attribute)

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#8625]
This fix would solve the problem of having a label saying one thing and the placeholder another:

![untitled_map_3__ cartodb](https://cloud.githubusercontent.com/assets/4933/16649404/1c0e1a42-4439-11e6-9301-243e15289209.png)

**Comment by ramiroaznar** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/5215798/32222838-1ba1039e-be3b-11e7-8a37-1bea61a424c0.png)
