### ISSUE TITLE
Missing reference to input node on the analysis layers

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8626]
![screen shot 2016-07-07 at 12 00 51](https://cloud.githubusercontent.com/assets/132149/16649709/81364402-443a-11e6-9c1a-a29dc452d3f0.png)

We should add a reference below the title to the first node (input node) even if it's not clickeable.

**Comment by xavijam** [comment]
To the previous one or to the first one?

On Jul 7 2016, at 12:01 pm, Sergio Álvarez Leiva
&lt;notifications@github.com&gt; wrote:  

> Assigned
[#8626](https://github.com/CartoDB/cartodb/issues/8626&r=cmVwbHkrMDAwMjA0MzI0MjkxNjkwMzc3YzdlZDAxYjE4Zjc5ZTM3MTgyOWRiYjY1MzdmYzYzOTJjZjAwMDAwMDAxMTM5NWVhODk5MmExNjljZTA5Y2E5YzlkQHJlcGx5LmdpdGh1Yi5jb20=)
to
[@xavijam](https://github.com/xavijam&r=cmVwbHkrMDAwMjA0MzI0MjkxNjkwMzc3YzdlZDAxYjE4Zjc5ZTM3MTgyOWRiYjY1MzdmYzYzOTJjZjAwMDAwMDAxMTM5NWVhODk5MmExNjljZTA5Y2E5YzlkQHJlcGx5LmdpdGh1Yi5jb20=).

>

> —  
> You are receiving this because you were mentioned.  
> Reply to this email directly, [view it on
GitHub](https://github.com/CartoDB/cartodb/issues/8626#event-715503258&r=cmVwbHkrMDAwMjA0MzI0MjkxNjkwMzc3YzdlZDAxYjE4Zjc5ZTM3MTgyOWRiYjY1MzdmYzYzOTJjZjAwMDAwMDAxMTM5NWVhODk5MmExNjljZTA5Y2E5YzlkQHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the
thread](https://github.com/notifications/unsubscribe/AAIEMrksowhTVRiYQEaVfdy_yvrpYypmks5qTM6JgaJpZM4JG7LC&r=cmVwbHkrMDAwMjA0MzI0MjkxNjkwMzc3YzdlZDAxYjE4Zjc5ZTM3MTgyOWRiYjY1MzdmYzYzOTJjZjAwMDAwMDAxMTM5NWVhODk5MmExNjljZTA5Y2E5YzlkQHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notifications/beacon/AAIEMoJaqR9e9XLGRE7DYTFLwIY1OCZBks5qTM6JgaJpZM4JG7LC.gif)

**Comment by saleiva** [comment]
To the first one of the layer.

**Comment by xavijam** [comment]
:+1:

On Jul 7 2016, at 12:04 pm, Sergio Álvarez Leiva
&lt;notifications@github.com&gt; wrote:  

> To the first one of the layer.

>

> —  
> You are receiving this because you were mentioned.  
> Reply to this email directly, [view it on
GitHub](https://github.com/CartoDB/cartodb/issues/8626#issuecomment-231036868&r=cmVwbHkrMDAwMjA0MzI2MjY4ZmIwMDM0NDJlOTkyNzg4ODVkYTc1OWE0OWM2OTI5NWM3NGYyOTJjZjAwMDAwMDAxMTM5NWViMzg5MmExNjljZTA5Y2E5YzlkQHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the
thread](https://github.com/notifications/unsubscribe/AAIEMgj9-OA4rdxbcJxatz2UgUso3E08ks5qTM84gaJpZM4JG7LC&r=cmVwbHkrMDAwMjA0MzI2MjY4ZmIwMDM0NDJlOTkyNzg4ODVkYTc1OWE0OWM2OTI5NWM3NGYyOTJjZjAwMDAwMDAxMTM5NWViMzg5MmExNjljZTA5Y2E5YzlkQHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notifications/beacon
/AAIEMsRQonMm-xgwFc0JjFL-OIX3JzpSks5qTM84gaJpZM4JG7LC.gif)

**Comment by xavijam** [comment]
Also, I should take into account:

https://github.com/CartoDB/cartodb/issues/8269#issuecomment-229013821

**Comment by ramiroaznar** [comment]
This is already implemented, right @xavijam? 

![image](https://user-images.githubusercontent.com/5215798/32222775-eb64c9ea-be3a-11e7-8d9a-2bee0f42cbb8.png)

**Comment by xavijam** [comment]
I think so.
