### ISSUE TITLE
Fixing the wording when geocoding postal codes

### ISSUE THREAD

**Issue by stephenhstreich** [CartoDB/cartodb#863]
![screen shot 2014-10-08 at 12 10 33 pm](https://cloud.githubusercontent.com/assets/8423305/4562593/c3f913ea-4f05-11e4-979d-8eba92230797.png)

The second selection column of selecting a "place where the postal code is located" is confusing. It doesn't lead you to understand that it is asking for the country/state/etc.

**Comment by Xatpy** [comment]
Nowadays, it has that text ( *Country where postal codes are located, if known* ) in production:
![screen shot 2015-02-11 at 12 33 53](https://cloud.githubusercontent.com/assets/3958416/6146215/9a19376a-b1ea-11e4-85fb-f3414b46f5e8.png)
I close this issue. :)
