### ISSUE TITLE
Exporting .carto smoke test #99

### ISSUE THREAD

**Issue by makella** [CartoDB/cartodb#8635]
smoke test task #99 asks to Export a Full Map. The dialogue that comes up, has the "Ok, Export" option greyed out. If I click anywhere on the page other than the greyed out button, I get the option to download. 

In short, the export is possible, but the dialogue seems to be broken.

![screen shot 2016-07-07 at 12 58 38 pm](https://cloud.githubusercontent.com/assets/1566273/16651477/5cdbeb20-4444-11e6-9411-f1a93f7f1d53.png)

**Comment by makella** [comment]
Tried it again and if I click on the greyed out button it downloads but the "Ok, Export" button is always greyed out.

**Comment by gfiorav** [comment]
I've tried in prod with several maps and it all seems good :(
