### ISSUE TITLE
Common data fails when creating Viewer

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#8636]
I guess that common data should attempt to load for a viewer, but it does and [this](https://rollbar.com/vizzuality/CartoDB/items/19319/?item_page=0&#instances) happens.

No hurry! :)

cc/ @javitonino

**Comment by juanignaciosl** [comment]
Oh, this only happens when the user is created at superadmin. The normal user creation, the one within organization settings, works as expected (it doesn't populate data library). I'll fix this, but the main case was ok.

cc @ramiroaznar @javitonino

**Comment by saleiva** [comment]
Shouldn't we disable Data library on viewers account?

**Comment by juanignaciosl** [comment]
Yep, viewers doesn't have Data Library.

The problem is that the creation through superadmin didn't take that into account.
