### ISSUE TITLE
"cannot cast type geometry to geography" when aggregating by provinces/countries

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#8644]
**STR**:
- Create a map from a points table (I used some points in Spain)
- In STYLE, select the "administrative regions" aggregation
- Choose admin. level "provinces" or "countries", operation "count"

The map doesn't get updated and the Maps API returns the following error:

```
errors_with_context:
[{type: "unknown", message: "cannot cast type geometry to geography", name: "error", length: 93,…}]
0:{type: "unknown", message: "cannot cast type geometry to geography", name: "error", length: 93,…}
code:"P0001"
file:"pl_exec.c"
length:93
line:"3216"
message:"cannot cast type geometry to geography"
name:"error"
routine:"exec_stmt_raise"
severity:"ERROR"
type:"unknown"
```
- The data I'm using is available [here](https://team.carto.com/u/iriberri/dataset/twitter_catalansvote9n25) -- a tweets dataset.

**Comment by iriberri** [comment]
Sorry for the vague description. I'm trying to reproduce the error further. I was able to make it work in another account with another table. I'll keep updating the issue.

**Comment by iriberri** [comment]
Running a 

````
SELECT distinct(st_geometrytype(the_geom)) FROM twitter_catalansvote9n25 limit 10
````

is returning `ST_Point` and `null`.

**Comment by saleiva** [comment]
Hey @javisantana any clue?

**Comment by javisantana** [comment]
no idea, this is the query: https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb3/editor/style/style-converter.js#L436
