### ISSUE TITLE
Here basemaps thumbnail using incorrect subdomain (letters) do not render an image

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#8645]
![image](https://cloud.githubusercontent.com/assets/1730320/16656607/9adca30e-445f-11e6-9def-6932d1584b74.png)

The URL of the thumbnail **in the layers list** is going to:

`https://a.maps.nlp.nokia.com/maptile/2.1/maptile/newest/normal.day/6/30/24/256/png8?lg=eng&token=xxx&app_id=xxx`

but the `a` subdomain is not working. We should be using numbers instead:

`https://1.maps.nlp.nokia.com/maptile/2.1/maptile/newest/normal.day/6/30/24/256/png8?lg=eng&token=xxx&app_id=xxx`

Note: This is not happening in the basemaps selectors.

**Comment by matallo** [comment]
copying @alonsogarciapablo

**Comment by alonsogarciapablo** [comment]
Working on it!

**Comment by matallo** [comment]
🙌
