### ISSUE TITLE
hover pane is broken

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#8646]
Steps:
- create a map and try to add a hover infowindow

![screen shot 2016-07-07 at 4 27 54 pm](https://cloud.githubusercontent.com/assets/30147/16656648/cc61f686-445f-11e6-9274-e149e02b6c68.png)

**Comment by saleiva** [comment]
It's working for us, can you export the .carto for us?

**Comment by javisantana** [comment]
umh, looks like only happen when is the first time you enable it

**Comment by javisantana** [comment]
not able to reproduce anymore, maybe cache, will reopen if needed
