### ISSUE TITLE
Change CARTO on disqus module

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#8648]
AFAIK this module is on the map public page:

<img width="1042" alt="screen shot 2016-07-07 at 16 29 27" src="https://cloud.githubusercontent.com/assets/596509/16656786/4e1f24c8-4460-11e6-96d8-d50fcd60b3e4.png">

**Comment by ramiroaznar** [comment]
Hey @josecruz I think we do not have disquss module anymore, right? Can you close this issue then?

**Comment by josecruz** [comment]
Hey @ramiroaznar nice catch, closing.

Thanks!
