### ISSUE TITLE
Protected embeds are not working

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#8649]
STR:

1. Create a map.
2. Set privacy to password protected.
3. Click Share, Publish the map.
4. Go to the embed (click "Get a simple URL.").
5. Type the password that you used in 2.

Expected result:

- A nice embed is in front of you!

Actual result:

- Map is not displayed and there's a JS error in the console:

`Uncaught Error: no element found with selector #dashboard`.

**Comment by alonsogarciapablo** [comment]
It seems that the viz.json that we're using in the embed page for protected maps is not including the `auth_tokens` and that's why the request to the Maps API is not being authorised correctly.

**Comment by gfiorav** [comment]
Closed via https://github.com/CartoDB/cartodb/pull/8660
