### ISSUE TITLE
Wrong style on 'Export map' modal 

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#8650]
From the Editor, with a non-team account.
 
![screen shot 2016-07-07 at 16 46 20](https://cloud.githubusercontent.com/assets/16247628/16657356/8392a22c-4462-11e6-9617-a084cb9dc4a7.png)

**Comment by gfiorav** [comment]
I'm not sure if this was already solved @MariaCheca ?

**Comment by MariaCheca** [comment]
Yep, already solved here https://github.com/CartoDB/cartodb/pull/8685
