### ISSUE TITLE
Number columns are displayed with thousand separators in dataset view

### ISSUE THREAD

**Issue by danicarrion** [CartoDB/cartodb#8651]
![image](https://cloud.githubusercontent.com/assets/498023/16657654/8912fac0-4463-11e6-8813-af485166a6cc.png)

**Comment by xavijam** [comment]
Yes, it is on purpose.

**Comment by saleiva** [comment]
Hey @danicarrion why would you consider this a bug?

**Comment by danicarrion** [comment]
Thousand separators are ok for money, for instance. But not for ids. Now I can't copy and paste an id into my sql query, i need to delete the separator manually.

**Comment by xavijam** [comment]
So... no thousands separator?

**Comment by saleiva** [comment]
I guess so, yeah. The most generic.

**Comment by MariaCheca** [comment]
Hey, what about those Times New Roman column type texts?

**Comment by xavijam** [comment]
It is likely @danicarrion had limited connectivity (or nothing) and fonts were not loaded, nothing else.

**Comment by MariaCheca** [comment]
👍
