### ISSUE TITLE
Distance Isolines missing

### ISSUE THREAD

**Issue by stuartlynn** [CartoDB/cartodb#8652]
In the Area of Influence analysis you can request isolines for time but not for distance. Distance only seems to allow a simple buffer.

<img width="326" alt="screen shot 2016-07-07 at 10 53 35 am" src="https://cloud.githubusercontent.com/assets/209838/16657694/60a39b12-4431-11e6-9824-5ea4f9922f09.png">

<img width="310" alt="screen shot 2016-07-07 at 10 53 38 am" src="https://cloud.githubusercontent.com/assets/209838/16657700/65787ab8-4431-11e6-9e96-765358862ce4.png">

**Comment by xavijam** [comment]
Moved to design, let me close it and then reopen a new one for implementation. Thanks @stuartlynn 💋

**Comment by saleiva** [comment]
Hey @xavijam it looks like something we miss in implementation. The radio button is already there!

**Comment by ramiroaznar** [comment]
Hey @stuartlynn can you tell me what a distance isoline is?
