### ISSUE TITLE
centroid analysis should have option for individual geometry or entire dataset

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/cartodb#8653]
A common operation in analysis is to find the centroid of all polygons in a dataset, row by row. Currently this is possible though the `centroid from geometries` analysis, but a user has to know to select the `cartodb_id` as the category, which is not obvious.

This analysis should have an option that allows the user to produce centroids without having to choose the categorize options.. maybe a tick box that is just `for each geometry individually` which then greys out the categorize option?

also camshaft repo: https://github.com/CartoDB/camshaft/issues/127

cc @saleiva @rochoa

**Comment by xavijam** [comment]
Moved to design, let me close this one :kiss: thanks Andye!
