### ISSUE TITLE
Adding more than one row to a table only updates the pagination tooltip value once

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#8658]
**STR**:

* Create a new empty dataset
* Click on "add row" several times:

  ![image](https://cloud.githubusercontent.com/assets/1730320/16658682/8c3c04d6-4467-11e6-86c9-38952ceb2419.png)

**Current behavior**:
  The "pagination tooltip" updates to "0 to 1" after 5 new added rows. It requires a page refresh for it to show "0 to 5".

**Expected behavior**:
  Each row added to the table would update the pagination tooltip value.

After a refresh this is the result:

  ![image](https://cloud.githubusercontent.com/assets/1730320/16658759/cdd7efd6-4467-11e6-8ebb-9270bc8840cc.png)

**Comment by xavijam** [comment]
:kiss:
