### ISSUE TITLE
Confusing warning when deleting a layer from a map: "Maps will be affected"

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#8659]
**STR**:
- Create (or go to) a map with several layers
- Try to delete any of them
- The warning modal says:

> You are about to delete layer untitled_table_216
> **Maps will be affected**, are you sure you want to delete it?

That "Maps will be affected" message sounds a bit scary/confusing :-) I guess that the {{name}} map will be affected -- and the widgets related to the layer?

![image](https://cloud.githubusercontent.com/assets/1730320/16658952/8e6cdcde-4468-11e6-8a8b-8c270e99540d.png)

**Comment by saleiva** [comment]
hey @urbanphes let's take a look at this. After fixing let's assign to @alonsogarciapablo

**Comment by urbanphes** [comment]
Oks @saleiva , I'll work on this

**Comment by urbanphes** [comment]
Here the visual design:
<br>
![image](https://cloud.githubusercontent.com/assets/14546701/16682739/4977369e-44fc-11e6-9247-974b32b1a1dd.png)

CC/ @iriberri @saleiva

**Comment by saleiva** [comment]
I don't think we need to add the name of the map since you are on that map
when deleting the layer. Maybe we could show how many widgets will be
affected.

2016-07-08 11:09 GMT+02:00 Juanma <notifications@github.com>:

> Here the visual design:
>
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/14546701/16682739/4977369e-44fc-11e6-9247-974b32b1a1dd.png>
>
> CC/ @iriberri <https://github.com/iriberri> @saleiva
> <https://github.com/saleiva>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/8659#issuecomment-231312089>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAIENWiKNWq_oMp0B6PoPpzx4BuDoi_kks5qThOxgaJpZM4JHNIh>
> .
>



-- 
Sergio Alvarez Leiva

**Comment by urbanphes** [comment]
Here a list of widgets will be affected
<br>
![image](https://cloud.githubusercontent.com/assets/14546701/16685100/0a03afe4-4509-11e6-919d-10b573f227ce.png)

**Comment by viddo** [comment]
Hey, it's not only widgets, also dependent analysis, and in turn their layers, could be deleted.

There's also the detail that if a layer and its nodes can be folded under another layer the nodes ids would be changed, so even if nothing is deleted the sources would changed which is probably not that obvious either.

**Comment by urbanphes** [comment]
I'll work in this cases @saleiva

**Comment by urbanphes** [comment]
In this visual design appears the areas will be affected when delete the layer.

- Analysis
- Widgets
- Layers


![- 904 mod error](https://cloud.githubusercontent.com/assets/14546701/16844545/db1b5a7e-49e5-11e6-86b2-9f9b541833fb.png)

**Comment by urbanphes** [comment]
This version is more compact and could grow.
<br>

**3 affected (ANALYSIS, WIDGETS, LAYERS)** 
![- 904 mod error](https://cloud.githubusercontent.com/assets/14546701/16867275/3d7b01a2-4a71-11e6-853e-78b8e45204bd.png)
<br>

**2 affected (ANALYSIS, WIDGETS )** 
![- 904 mod error](https://cloud.githubusercontent.com/assets/14546701/16867278/47863f22-4a71-11e6-8b1d-f0e989342731.png)

<br>

**1 affected (WIDGETS )**
![- 904 mod error](https://cloud.githubusercontent.com/assets/14546701/16867287/4e7c2788-4a71-11e6-9ca9-3a899fd9263d.png)

<br>

**Extreme case**
![- 904 mod error](https://cloud.githubusercontent.com/assets/14546701/16867290/5467382c-4a71-11e6-85ce-2254e8db837d.png)

<br>

cc/ @saleiva

**Comment by viddo** [comment]
What would "layer affected" mean if not being deleted?

Btw, due to the layer<->analysis association, when deleting a layer that have nodes the primary nodes under that layer will be moved to another layer if possible, should that be indicated? E.g. having a layer `A` with nodes `[a1, a0]` and a layer `B` with nodes `['b1', 'a1']`, when deleting layer `A` the nodes of `A` would be folded under `B` as `[b2, b1, b0])`. Perhaps that should be indicated in this modal too?

**Comment by viddo** [comment]
Btw 2, deleting a node could also have this kind repercussions, so probably we want (dependent layers and nodes being deleted) so probably we want to show this kind of modal there too.

**Comment by saleiva** [comment]
Also, not having the visual clue with the letter and the color is very missleading

**Comment by josecruz** [comment]
Hey guys! I upload a simplified version of the delete modal:
![image](https://cloud.githubusercontent.com/assets/596509/17251474/43cd0f08-55a9-11e6-9ecd-16a20503660d.png)

Basically a first information about where this layer affects and another one with an option for exporting that map as .CARTO file.
