### ISSUE TITLE
Importing issues after docker install

### ISSUE THREAD

**Issue by cheribhai** [CartoDB/cartodb#866]
I am trying to build a docker container for cartodb (following the git hub instructions and other corrections) and have managed to get it up and running (almost).
After starting up , when loading a csv file with lat/ long columns I see the following error in the postgres log file,
<pre><code>
2014-10-11 14:35:09 UTC STATEMENT:  
                  SELECT CDB_StringToDate(postedtime)
                  FROM "cdb_importer"."importer_cce4dff2515311e4b3e51a7bcf04548a"
                  AS convertible
                
2014-10-11 14:35:09 UTC ERROR:  relation "cdb_importer.importer_cce4dff2515311e4b3e51a7bcf04548a_geom_idx" does not exist
2014-10-11 14:35:09 UTC STATEMENT:  
                  ALTER INDEX "cdb_importer"."importer_cce4dff2515311e4b3e51a7bcf04548a_geom_idx"
                  RENAME TO "the_geom_cd2a041a_5153_11e4_b3e5_1a7bcf04548a"
                
2014-10-11 14:35:09 UTC ERROR:  duplicate key value violates unique constraint "cdb_tablemetadata_pkey"
2014-10-11 14:35:09 UTC DETAIL:  Key (tabname)=(19034) already exists.
2014-10-11 14:35:09 UTC STATEMENT:  
              INSERT INTO cartodb.cdb_tablemetadata (tabname, updated_at)
              VALUES ('19034', NOW())
</code></pre>
following which the table does not get georeferenced even though the lat / long columns are recognised automatically. Trying to delete the table after this blocks the ui.

All the other services i.e redis, cartodb-sql, windshaft, resque seem to be running fine.

I have created the user in the standard way, using the 'script/create_dev_user' and my postgres version is PostgreSQL 9.3.4.

Please advise

**Comment by Kartones** [comment]
I'd try:
- uploading the same file with a different name
- exporting an existing (working) map in CSV and trying to upload it
- converting the map to other format (SHP, KML...) and trying to upload it in that format

To better triage where the problem relies... because from that error sounds like a name collision so just renaming should work.
