### ISSUE TITLE
Arrow icon without any behaviour on add dataset modal

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#8662]
- From a non-team account
- Chrome v47 

From the datasets page on the Dashboard I opened up the New Dataset modal. The navigated through the different connectors. The right arrow at the end doesn't have any behaviour. 

I'm guessing that the expected behaviour should be to slide back to the beginning of the connectors or not showing the arrow at all. 

![screen shot 2016-07-07 at 17 05 02](https://cloud.githubusercontent.com/assets/16247628/16659644/51e11502-446b-11e6-8dc9-9df4c936b84d.png)

**Comment by xavijam** [comment]
This is gonna change with the new "add dataset modal", so... closing lady! thanks! 💋
