### ISSUE TITLE
CartoDB icon showing up on the dashboard's notifications dropdown 

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#8663]
![screen shot 2016-07-07 at 17 55 52](https://cloud.githubusercontent.com/assets/16247628/16659850/27abd4ba-446c-11e6-941c-fa19b3d6f780.png)

**Comment by xavijam** [comment]
@piensaenpixel, could you take care of it?

**Comment by piensaenpixel** [comment]
@MariaCheca change icon to a gift for example :) dont update cartoassets
