### ISSUE TITLE
Rename CartoDB to CARTO in basemap attributions

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#8667]
- [x] Rename attributions
   - [x] cartodb.js
   - [x] Frontend tests @ cartodb
 - [X] Rake to update attributions in old layers (@juanignaciosl, CartoDB/cartodb/pull/8738)

**Comment by juanignaciosl** [comment]
@alonsogarciapablo ping here when you merge cartodb.js and frontend tests, please.

**Comment by alonsogarciapablo** [comment]
@juanignaciosl done already!

**Comment by juanignaciosl** [comment]
@xavijam , @javitonino , any opinion about running the migration for old attributions?

**Comment by javitonino** [comment]
I'd say run it tomorrow morning, so we can monitor it through the process, mostly in case there are a lot of errors (I suspect we will have a few layers without map/visualization) and we want to change the task to avoid them. But I don't have any strong opinion on this, it is pretty innocuous.

**Comment by juanignaciosl** [comment]
@javitonino agree. Anyway, you never know when a weird side effect will appear 😅

**Comment by juanignaciosl** [comment]
Planned with @luisbosque tomorrow at 10am so he can schedule an extra backup.
