### ISSUE TITLE
the_geom and the_geom_webmercator appear as possible values for labels

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#8668]
**STR**

* In a map, try to add labels to one of your layers
* `the_geom` and `the_geom_webmercator` can be chosen among the rest of columns in the table (although nothing seems to be rendered)

  ![image](https://cloud.githubusercontent.com/assets/1730320/16660822/4ee0dcac-4470-11e6-82fa-b72321d95b3e.png)

**Expected behavior**: 

 `the_geom` and `the_geom_webmercator` should not be options to be used as a label in a map.

**Comment by xavijam** [comment]
Also excluding date columns, they are not rendered with current mapnik version.
