### ISSUE TITLE
Remove the ambiguous 'Connection error'

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#8676]
I'd like to get rid of this error completely, 'Unfortunately, there was a connection error'

https://github.com/CartoDB/cartodb/blob/master/lib/assets/locale/en.json#L128

If we can't get rid of it completely for more informative versions, I'd propose we change it to something that actually lets the user know how to respond. Like,

“There was a temporary connection error, please try again."

cc @csobier @ztephm

**Comment by xavijam** [comment]
Hey, we don't have that error anymore, so perfect for closing!
