### ISSUE TITLE
Add datasets module contains links to out-of-date-content

### ISSUE THREAD

**Issue by csobier** [CartoDB/cartodb#8679]
From the Editor and Builder,
- From _Your maps_ dashboard
- Click NEW MAP button

The "Add datasets" module contains a link at the bottom to , which opens "Or you can start with a video tutorial". These are old and out-of-date. Suggestion is to match the "Connect Dataset" module for consistency.

![image](https://cloud.githubusercontent.com/assets/13319925/16667772/27cb89d2-445c-11e6-9573-d9ca9b5f3f74.png)

**Comment by saleiva** [comment]
Lets remove that for the time being

**Comment by xavijam** [comment]
This is gonna change with the new "add dataset modal", so... closing lady! thanks! 💋
