### ISSUE TITLE
Dashboard - Widgets Naming

### ISSUE THREAD

**Issue by michellechandra** [CartoDB/cartodb#8681]
When using the new editor, I often need to remind myself what adding a "widget" adds to my map (i.e. a chart or graph). I believe new users might be unclear on what a "widget" is when first using the new editor as the word "widget" doesn't bring to mind the right visual intuitively. Should the widgets section be renamed to Charts or Graphs or maybe a hover tooltip should be added to describe that section to help new users?

**Comment by saleiva** [comment]
Hey @michellechandra we though about this but since there are not only charts and that we need something generic in order to scale that set of components we decided to keep it like that.

We should do an internal brainstorming about this!
