### ISSUE TITLE
Time defined AOIs fail.

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8683]

**Comment by javierarce** [comment]
What's wrong exactly?

**Comment by saleiva** [comment]
The notifier gives an error, but no more info is provided and nothing is
rendered

2016-07-08 10:39 GMT+02:00 Javier Arce <notifications@github.com>:

> What's wrong exactly?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/8683#issuecomment-231306283>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAIENURHgMnCsHutyJJViFebuL1t1gHuks5qTgzYgaJpZM4JH0mm>
> .
>



-- 
Sergio Alvarez Leiva

**Comment by saleiva** [comment]
It could be related with the last version of camshaft?

2016-07-08 10:40 GMT+02:00 Sergio Alvarez Leiva <saleiva@gmail.com>:

> The notifier gives an error, but no more info is provided and nothing is
> rendered
>
> 2016-07-08 10:39 GMT+02:00 Javier Arce <notifications@github.com>:
>
>> What's wrong exactly?
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/CartoDB/cartodb/issues/8683#issuecomment-231306283>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AAIENURHgMnCsHutyJJViFebuL1t1gHuks5qTgzYgaJpZM4JH0mm>
>> .
>>
>
>
>
> --
> Sergio Alvarez Leiva
>
>


-- 
Sergio Alvarez Leiva

**Comment by javierarce** [comment]
I'm not sure, but I'll have a look.

**Comment by saleiva** [comment]
@erodespons is having the same problem

**Comment by javierarce** [comment]
I'm not sure what's exactly the problem. I was able to make it work  with points inside Madrid and these settings:

![screen shot 2016-07-08 at 12 51 30](https://cloud.githubusercontent.com/assets/4933/16685327/c9c2ec86-450a-11e6-8ef3-4ae0b15a90fa.png)


Adding random points in other places (outside cities, for example or mixing points in cities with points outside them) produced a silent errors in the analysis. 

Walking tends to fail all the time, while driving seems to work ok in my tests. Could this be a problem with the Mapzen provider, @rafatower?

**Comment by rafatower** [comment]
I'd need a bit more info.

@javierarce Is it completely silent? @rochoa was looking into a caching issue, don't know if it is related. 

OTOH if it only fails for walking, it can be a problem with mapzen provider. I know in some cases it cannot simply calculate the distance/time matrix because of unconnected graphs and that's definitely on their side, but the dataservices API throws an exception in those cases that shall be dealt in camshaft or the upper layers.

**Comment by saleiva** [comment]
It fails driving as well.

**Comment by javierarce** [comment]
@rafatower: yes, when it fails nothing happens… no data is returned and, at least in the frontend side, there's no indication of something wrong (except for the analysis showing a red dot).

**Comment by rafatower** [comment]
Pass me a table or a set of points, but anyway you can test directly with the API. E.g:
```
https://rtorre.carto.com/api/v2/sql?q=SELECT%20iso.the_geom,%20iso.data_range%20FROM%20cdb_mapzen_isochrone(%27POINT(-3.70568%2040.42028)%27::geometry,%20%27car%27,%20ARRAY[1200]::integer[])%20iso;&api_key=my_api_key
```

(I just tested it and worked ok)

**Comment by javierarce** [comment]
Sure: 

- Add a couple of points in Madrid.
- Add an "Areas of Influence" analysis
- Fill the form with the values that appear in the image and click apply.

Here's a compressed file with the .carto of the map:
[ao.carto.zip](https://github.com/CartoDB/cartodb/files/356701/ao.carto.zip)

**Comment by rafatower** [comment]
I reproduced it and found this error:
```
cdb_dataservices_client._cdb_mapzen_isochrone(6): [cartodb_user_<my_uuid>_db] REMOTE ERROR: spiexceptions.ExternalRoutineException: IndexError: list index out of range
```

That error is visible in the last GET request to the analysis api when the UI polls for the status of the analysis node:
```
GET api/v1/map/[layergroup_id]/analysis/node/[node_id]?api_key=[your_api_key]
```

I'm going to debug and fix that one, but to my understanding there might be a couple more issues worth their own tickets:
- weird shapes generated (mostly related to routing info, out of the scope of the api itself)
- how errors are handled at UI level.

**Comment by javierarce** [comment]
Thanks, @rafatower.

The UI should be ready to reflect the errors and, if I'm not mistaken, @alonsogarciapablo was taking care of the errors in the analysis (although I'm not sure how different is this particular case).

**Comment by rafatower** [comment]
The problem can be reproduced with this query:
```sql
SELECT cdb_mapzen_isochrone('POINT(-3.7056799999999996 40.41971999999999)'::geometry, 'walk', ARRAY[100]::integer[]);
```

which in turns executes this on mazen:
```
https://matrix.mapzen.com/one_to_many?json=%7B%22locations%22%3A+%5B%7B%22lat%22%3A+40.41971999999999%2C+%22lon%22%3A+-3.7056799999999996%7D%2C+%7B%22lat%22%3A+40.42121970639553%2C+%22lon%22%3A+-3.7056799999999996%7D%2C+%7B%22lat%22%3A+40.42116860401952%2C+%22lon%22%3A+-3.7051701442414076%7D%2C+%7B%22lat%22%3A+40.421018779657686%2C+%22lon%22%3A+-3.7046950365038036%7D%2C+%7B%22lat%22%3A+40.42078044420399%2C+%22lon%22%3A+-3.704287056200143%7D%2C+%7B%22lat%22%3A+40.420469840660736%2C+%22lon%22%3A+-3.7039740071015688%7D%2C+%7B%22lat%22%3A+40.42010813698107%2C+%22lon%22%3A+-3.703777222398915%7D%2C+%7B%22lat%22%3A+40.41971998328423%2C+%22lon%22%3A+-3.7037101110385824%7D%2C+%7B%22lat%22%3A+40.419331831826874%2C+%22lon%22%3A+-3.7037772443553485%7D%2C+%7B%22lat%22%3A+40.41897013426561%2C+%22lon%22%3A+-3.7039740451312264%7D%2C+%7B%22lat%22%3A+40.41865953908023%2C+%22lon%22%3A+-3.7042871001130098%7D%2C+%7B%22lat%22%3A+40.41842121198442%2C+%22lon%22%3A+-3.704695074533462%7D%2C+%7B%22lat%22%3A+40.41827139374099%2C+%22lon%22%3A+-3.7051701661978402%7D%2C+%7B%22lat%22%3A+40.41822029360446%2C+%22lon%22%3A+-3.7056799999999996%7D%2C+%7B%22lat%22%3A+40.41827139374099%2C+%22lon%22%3A+-3.706189833802159%7D%2C+%7B%22lat%22%3A+40.41842121198442%2C+%22lon%22%3A+-3.706664925466537%7D%2C+%7B%22lat%22%3A+40.41865953908023%2C+%22lon%22%3A+-3.7070728998869895%7D%2C+%7B%22lat%22%3A+40.41897013426561%2C+%22lon%22%3A+-3.707385954868773%7D%2C+%7B%22lat%22%3A+40.419331831826874%2C+%22lon%22%3A+-3.707582755644651%7D%2C+%7B%22lat%22%3A+40.41971998328423%2C+%22lon%22%3A+-3.707649888961417%7D%2C+%7B%22lat%22%3A+40.42010813698107%2C+%22lon%22%3A+-3.7075827776010843%7D%2C+%7B%22lat%22%3A+40.420469840660736%2C+%22lon%22%3A+-3.7073859928984305%7D%2C+%7B%22lat%22%3A+40.42078044420399%2C+%22lon%22%3A+-3.707072943799856%7D%2C+%7B%22lat%22%3A+40.421018779657686%2C+%22lon%22%3A+-3.7066649634961957%7D%2C+%7B%22lat%22%3A+40.42116860401952%2C+%22lon%22%3A+-3.706189855758592%7D%5D%7D&api_key=[our_api_key]&costing=pedestrian
```

which returns the following:
```js
{"one_to_many":[[{"distance":0.000,"time":0,"to_index":0,"from_index":0},{"distance":null,"time":null,"to_index":1,"from_index":0},{"distance":null,"time":null,"to_index":2,"from_ijavascriptndex":0},{"distance":null,"time":null,"to_index":3,"from_index":0},{"distance":null,"time":null,"to_index":4,"from_index":0},{"distance":null,"time":null,"to_index":5,"from_index":0},{"distance":null,"time":null,"to_index":6,"from_index":0},{"distance":null,"time":null,"to_index":7,"from_index":0},{"distance":null,"time":null,"to_index":8,"from_index":0},{"distance":null,"time":null,"to_index":9,"from_index":0},{"distance":null,"time":null,"to_index":10,"from_index":0},{"distance":null,"time":null,"to_index":11,"from_index":0},{"distance":null,"time":null,"to_index":12,"from_index":0},{"distance":null,"time":null,"to_index":13,"from_index":0},{"distance":null,"time":null,"to_index":14,"from_index":0},{"distance":null,"time":null,"to_index":15,"from_index":0},{"distance":null,"time":null,"to_index":16,"from_index":0},{"distance":null,"time":null,"to_index":17,"from_index":0},{"distance":null,"time":null,"to_index":18,"from_index":0},{"distance":null,"time":null,"to_index":19,"from_index":0},{"distance":null,"time":null,"to_index":20,"from_index":0},{"distance":null,"time":null,"to_index":21,"from_index":0},{"distance":null,"time":null,"to_index":22,"from_index":0},{"distance":null,"time":null,"to_index":23,"from_index":0},{"distance":null,"time":null,"to_index":24,"from_index":0}]],"units":"km","locations":[[{"lon":-3.705680,"lat":40.419720},{"lon":-3.705680,"lat":40.421219},{"lon":-3.705170,"lat":40.421169},{"lon":-3.704695,"lat":40.421021},{"lon":-3.704287,"lat":40.420780},{"lon":-3.703974,"lat":40.420471},{"lon":-3.703777,"lat":40.420109},{"lon":-3.703710,"lat":40.419720},{"lon":-3.703777,"lat":40.419331},{"lon":-3.703974,"lat":40.418972},{"lon":-3.704287,"lat":40.418659},{"lon":-3.704695,"lat":40.418423},{"lon":-3.705170,"lat":40.418270},{"lon":-3.705680,"lat":40.418221},{"lon":-3.706190,"lat":40.418270},{"lon":-3.706665,"lat":40.418423},{"lon":-3.707073,"lat":40.418659},{"lon":-3.707386,"lat":40.418972},{"lon":-3.707583,"lat":40.419331},{"lon":-3.707650,"lat":40.419720},{"lon":-3.707583,"lat":40.420109},{"lon":-3.707386,"lat":40.420471},{"lon":-3.707073,"lat":40.420780},{"lon":-3.706665,"lat":40.421021},{"lon":-3.706190,"lat":40.421169}]]}
```

Note that all the costs returned (distance and time) are set to `null`.

We basically discard those points so the problem is that we hit there a "corner" case as it ends up with no points to generate the pollygon cc/ @jsantana

**Comment by rafatower** [comment]
dataservices api fixed here: https://github.com/CartoDB/dataservices-api/pull/221

will expedite the fix into production. Will also contact our provider for the root cause of this.

**Comment by rafatower** [comment]
`cdb_mapzen_[isochorne|isodistance]` functions fixed.
