### ISSUE TITLE
Do not filter out values for moran's i functions

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb#8686]
@ohasselblad prefers not to filter by significance but to style by the `significance` value.

For accomplishing that, we should not allow the user to tweak the significance value in the form.

cc @saleiva @javierarce 

Reference: https://github.com/CartoDB/camshaft/issues/97.

**Comment by saleiva** [comment]
Sounds good to me.

2016-07-08 11:22 GMT+02:00 Raul Ochoa <notifications@github.com>:

> @ohasselblad <https://github.com/ohasselblad> prefers not to filter by
> significance but to style by the significance value.
>
> For accomplishing that, we should not allow the user to tweak the
> significance value in the form.
>
> cc @saleiva <https://github.com/saleiva> @javierarce
> <https://github.com/javierarce>
>
> Reference: CartoDB/camshaft#97
> <https://github.com/CartoDB/camshaft/issues/97>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/8686>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAIENeANpmKxJhu-4NTwmSMPMYrNWeBnks5qTha7gaJpZM4JH3H2>
> .
>



-- 
Sergio Alvarez Leiva

**Comment by javierarce** [comment]
Not sure if this is the best solution to solve this [suggestion](https://github.com/CartoDB/camshaft/issues/97#issuecomment-230168444): 
> **ohasselblad** commented on Jul 3:

> Having option to do either sounds great. Maybe a checkbox 'only show significant values' would be perfect :) best of both worlds.

![screen shot 2016-08-30 at 16 09 08](https://cloud.githubusercontent.com/assets/4933/18092294/1807a162-6ecc-11e6-8f07-6677940797d4.png)

What do you think?

**Comment by ohasselblad** [comment]
👍 
In general, users will want the complete analysis (moran classification (HH,LL,...), significance rating (0.0 - 1.0)) for all geometries, and then later want to filter. There are cases where the user will want to filter out values below a certain threshold so I think it is good to keep the option to filter by significance here.

**Comment by rochoa** [comment]
We already solved this.
