### ISSUE TITLE
Add the possibility to share a visualization with the rest of your organization

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#8688]
- Add share info below the dataset and map title.
- Add the possibility to share that dataset and map with the rest of the organization from the privacy modal.

**Comment by xavijam** [comment]
cc @javisantana

**Comment by nobuti** [comment]
I'm adding the map part to this issue, updating the description.

**Comment by nobuti** [comment]
New design for this https://projects.invisionapp.com/share/5G4TKZHEJ#/screens/174674656

**Comment by xavijam** [comment]
Closing in favor of https://github.com/CartoDB/cartodb/issues/8701.
