### ISSUE TITLE
Analyses (definitions, not nodes) are sometimes duplicated

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#8690]
I have no STR (yet) but observed this symptoms when helping people… 
I have my suspects though and will refactor the internals to make sure there's only one analysis definition per layer as intended.

**Comment by juanignaciosl** [comment]
This is happening to me as soon as "animated" is set in `styles`. Builder triggers two POSTs:

![screen shot 2016-07-11 at 17 49 59](https://cloud.githubusercontent.com/assets/932968/16737086/09c4bc06-4790-11e6-82ec-02583db3b689.png)

And records become duplicated:

```
-[ RECORD 1 ]-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------
id                  | 863e1d25-b70a-4d12-9919-c330b52d49eb
visualization_id    | 01cd9e34-477f-11e6-9e36-080027880ca6
user_id             | 35b78090-6a49-475a-8470-0a9032272af2
analysis_definition | {"id":"a0","type":"source","params":{"query":"SELECT * FROM crime_incidents_2016"},"options":{"table_name":"crime_incidents_2016"}}
created_at          | 2016-07-11 15:50:00.651818
updated_at          | 2016-07-11 15:50:00.651818
-[ RECORD 2 ]-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------
id                  | fee9245f-7a67-4c20-8f40-65d2e75409a3
visualization_id    | 01cd9e34-477f-11e6-9e36-080027880ca6
user_id             | 35b78090-6a49-475a-8470-0a9032272af2
analysis_definition | {"id":"a0","type":"source","params":{"query":"SELECT * FROM crime_incidents_2016"},"options":{"table_name":"crime_incidents_2016"}}
created_at          | 2016-07-11 15:49:57.762944
updated_at          | 2016-07-11 15:49:57.762944
```



Now that this API should be more stable we could begin adding validations (#6856), but I think that we should first stop triggering this twice.

**Comment by viddo** [comment]
@juanignaciosl thanks for reporting! I discovered this myself too just now… you're right, I'll look into how to mitigate that from happening.

**Comment by viddo** [comment]
@juanignaciosl meanwhile… wouldn't it make sense to return a 200-response and update the data of the data of the existing analysis (last-win…) in this scenario? I don't think it makes sense to persist duplicate analysis of the same node_id.

**Comment by juanignaciosl** [comment]
@viddo agree. It makes sense and it's something that we'll eventually have to do to fix duplicated analysis.
