### ISSUE TITLE
Logo aligment in embeds

### ISSUE THREAD

**Issue by carlostallon** [CartoDB/cartodb#8694]
![image](https://cloud.githubusercontent.com/assets/1712650/16684286/8de269e0-4504-11e6-9ea4-7f2a5b045ca1.png)

Hi guys, can you move down 8px the logo?

**Comment by xavijam** [comment]
This is for CartoDB.js

**Comment by xavijam** [comment]
Issue moved to [CartoDB/cartodb.js #1342](https://github.com/CartoDB/cartodb.js/issues/1342) via [**ZenHub**](https://www.zenhub.com/)
