### ISSUE TITLE
Improve visibility of the loader indicator in the analysis node

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8698]
![screen shot 2016-07-08 at 12 19 52](https://cloud.githubusercontent.com/assets/132149/16684611/5303e2c0-4506-11e6-8738-e6241e915708.png)

I'd propose make it 88 opacity.

**Comment by piensaenpixel** [comment]
Fixed - https://github.com/CartoDB/CartoAssets/pull/142
