### ISSUE TITLE
Make the logo bigger

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8700]
I always wanted to say that. Logo on maps is too small IMO.

**Comment by urbanphes** [comment]
Here a test between 2 sizes (Top: current size , Bottom: new size)
<br>
![image](https://cloud.githubusercontent.com/assets/14546701/16685746/74758006-450d-11e6-88b5-987f01d9bb21.png)

cc/ @saleiva

**Comment by saleiva** [comment]
Cooleo.

**Comment by saleiva** [comment]
Assigning to @alonsogarciapablo, he might need the asset

**Comment by xavijam** [comment]
New SVG logo coming in https://github.com/CartoDB/cartodb/pull/8716. But already updated in CartoDB.js, just in case.
