### ISSUE TITLE
Reimplement share modal

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8701]
![screen shot 2016-07-08 at 12 31 32](https://cloud.githubusercontent.com/assets/132149/16684918/f42fe9a4-4507-11e6-8aac-cb4d65c3a8d9.png)

We could change the icons of the unavailable options or something, right? Also the line-height of the text looks weird

**Comment by josecruz** [comment]
Hey, I suggest this changes making the unavailable options more evident. What do you think @saleiva ?
<img width="977" alt="screen shot 2016-07-13 at 11 12 28" src="https://cloud.githubusercontent.com/assets/596509/16798109/c3ad15a4-48ea-11e6-8411-3adf7e9cf075.png">

**Comment by saleiva** [comment]
Too much text IMO. Also, there is missing the highlight for sharing internally within the org since it's the only action that can be done

**Comment by josecruz** [comment]
Hey, I upload here the WIP, I'll see some things tomorrow with @noguerol (specially the get links section). Also about the header: not final, we need to ensure that this new "layout" works on all cases.

![-05 publish - 00-05 copy 2](https://cloud.githubusercontent.com/assets/596509/16848908/4ee54f20-49f8-11e6-9367-ab47a40942c1.png)
![-05 publish - 00-05 copy 6](https://cloud.githubusercontent.com/assets/596509/16848911/51948268-49f8-11e6-9cea-f08b2af80c52.png)

**Comment by saleiva** [comment]
@josecruz feels weird that the most common actions are the same size than the more expert ones. It might be worth to change how they visually look like. If not, I'd go with the same organization that we had before (4 in a row, horizontally distributed).

- Also, it's very weird to have the buttons so far from the other actionable items.
- I'd take the search within the list so we can relate to the results. It make no sense to have the searchbox at that level since you can only search users.
- We need to prepare the case that the user is not in an organization account.
- We need the case where the map is private and the options are disabled.

**Comment by josecruz** [comment]
> Also, it's very weird to have the buttons so far from the other actionable items. 

I made a more vertical-ish version of the get links cards giving it more whitespace (better to read) and making it close to the publish buttons:
![-05 publish - 00-02 - no org](https://cloud.githubusercontent.com/assets/596509/16880539/0d0f503c-4ab6-11e6-952d-c3a291e1a290.png)

> I'd take the search within the list so we can relate to the results. It make no sense to have the searchbox at that level since you can only search users.

Yep agree, I was just testing different positions for the search. Also, regarding to the invite users list, I removed the buttons on that part to make it "auto-save" (frontend ppl gonna hate me)
![-05 publish - 00-00 - org](https://cloud.githubusercontent.com/assets/596509/16880713/cfa99f6c-4ab6-11e6-9e71-9f8288cb5d86.png)

> We need to prepare the case that the user is not in an organization account.

We just remove one tab:
![image](https://cloud.githubusercontent.com/assets/596509/16880723/e38fa878-4ab6-11e6-83b5-726302df378f.png)

> We need the case where the map is private and the options are disabled. 

![image](https://cloud.githubusercontent.com/assets/596509/16880732/effc0c96-4ab6-11e6-840d-7e57baef599a.png)

**Comment by noguerol** [comment]
1. I think "Privacy" should be the first tab, as is the starting point of the workflow. This doesn't mean is the the default one. It will be nice to add some logic to open "share" by dafault once privacy has been setted.
2. Under privacy passwd needs explanation
3. Under privavy ill rather order the boxes from "private" to "public", as private is the default state
4. Ill prefer "Publish" instead of "get links"
5. Ill prefer "OK" instead of "Publish" for the main cta and thus no "done" button
6. I prefer shorter texts under "Get links" cards
7. Can't we have "edit" as a general option for the whole organization?

**Comment by josecruz** [comment]
## 1. Org. Users

* As you can see we separated this into 2 tabs for org. users.
![-05 publish - 00-00 - org copy](https://cloud.githubusercontent.com/assets/596509/16884741/5ac74e82-4acb-11e6-9df7-7652f6cdfeb1.png)


* "Publish" tab will have the same elements for links that we have now but with some UI Changes:
![-05 publish - 00-02 - no org copy](https://cloud.githubusercontent.com/assets/596509/16884616/bac30002-4aca-11e6-9017-68b16947fed8.png)


* Also we made some changes for privacy (dropdown still WIP) but the main idea is to make actionable that tag to show a dropdown: 
![image](https://cloud.githubusercontent.com/assets/596509/16884630/c1e5e0a2-4aca-11e6-98b2-cb2c7e303571.png)

## 2. Regular users

* The difference is that in this version we don't use tabs (but same header behaviour):

![-05 publish - 00-02 - no org](https://cloud.githubusercontent.com/assets/596509/16884654/d5d12a04-4aca-11e6-8b0a-20fd80953eda.png)

Ping @nobuti due he's working on related stuff on the #8915

**Comment by josecruz** [comment]
Hey @saleiva and @nobuti I uploaded a link to invision with more cases: https://invis.io/5G4TKZHEJ#/174674656_05_Publish_-_00-00

**Comment by nobuti** [comment]
Does the `Share` button remain in the UI?

**Comment by josecruz** [comment]
@nobuti Yep

**Comment by saleiva** [comment]
Hey @josecruz some pending stuff
- We are lacking the design of the process when selecting a password protected privacy type.
- We should decide what happens with the datasets so we unify. I propose we just open the privacy dropdown when clicking on the privacy tag.
- We should decide what happens when clicking on the privacy tag on the dashboard for maps and  datasets. For maps at least we should open the shame share modal (without the UPDATE option) but what to do with the datasets?

**Comment by josecruz** [comment]
Hey @saleiva:

> We are lacking the design of the process when selecting a password protected privacy type.

I think this is already designed: https://invis.io/64800HMTN#/174678414_05_Publish_-_00-04_-_Password

> We should decide what happens with the datasets so we unify. I propose we just open the privacy dropdown when clicking on the privacy tag.


> We should decide what happens when clicking on the privacy tag on the dashboard for maps and datasets. For maps at least we should open the shame share modal (without the UPDATE option) but what to do with the datasets?


I would just use the dropdown solution on this case and keep the modal on the rest of the UI until we have time to replace it with the dropdown everywhere (so we can test if the dropdown solution really works)

**Comment by saleiva** [comment]
Sounds good as an intermediate solution, but I'd try to implement the drop down there from the beginning if it's not too hard

**Comment by nobuti** [comment]
@saleiva @josecruz I've found some issues integrating the current behaviour, mostly related with errors:

- When updating, how any possible error is shown? 
- Right now when sharing inside the organisation, all changes are sent when the user press "Save settings", because if the user press "Escape" all the changes are gone, like the rest of modals. We can make it the same way using the "Done" button, but again, errors could happen. Not sure if we should change the label at least. For me, "Done" has an immediate result, closer to "Close". What worries me if that the "Done" button has not the same behaviour in both tabs. When publishing, it just closes the modal. When sharing, it has to wait to save the data, and, if nothing happens, then close the modal. Not sure if I'm too fussy here.

**Comment by josecruz** [comment]
> When updating, how any possible error is shown?

Working on it

> Right now when sharing inside the organisation, all changes are sent when the user press "Save settings", because if the user press "Escape" all the changes are gone, like the rest of modals. We can make it the same way using the "Done" button, but again, errors could happen. Not sure if we should change the label at least. For me, "Done" has an immediate result, closer to "Close". What worries me if that the "Done" button has not the same behaviour in both tabs. When publishing, it just closes the modal. When sharing, it has to wait to save the data, and, if nothing happens, then close the modal. Not sure if I'm too fussy here.

So, the idea here is to auto-save the changes so you don't need a button for saving changes when sharing.

Anyway can we try it on staging so we can test it? TY!

**Comment by xavijam** [comment]
Hey @josecruz, @saleiva, we have two pending things about design, could you take care of them as soon as possible pretty please? Those are:

- Groups: AFAIK, we haven't taken into account this stuff. If a group has been changed its permission, how should appear in the info close to map/dataset privacy?. Also, group icon in the shared list should appear different than the organization one, right?
- Organization: similar to the previous one, but with the whole organization.

Take into account at that point we don't have the info about how many users there are in the organization or within a group.

Take into

**Comment by josecruz** [comment]
Hey @xavijam!

For the info close to map/dataset privacy I would just update the number with the total shared people (included groups and so on).

Also for groups, I would just maintain the current design that we have but changing the copy of the number of members for this (just as we have it on the user group settings):

![image](https://cloud.githubusercontent.com/assets/596509/17248832/3a138b60-559d-11e6-9346-e8134e52700b.png)
![image](https://cloud.githubusercontent.com/assets/596509/17248801/116921ca-559d-11e6-94f6-d346646b8cf2.png)
