### ISSUE TITLE
Widgets using output of an analysis doesn't get refreshed when filtering in another widget

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8710]
But they get refreshed after panning the map.
Test in the map above in the formula widget
https://team.carto.com/u/ernestomb/builder/a89de72e-3fa4-11e6-80c4-0e674067d321/embed?state=%7B%22map%22%3A%7B%22center%22%3A%5B40.419769381446194%2C-3.6927795410156246%5D%2C%22zoom%22%3A12%7D%2C%22widgets%22%3A%7B%22c7ea4ffc-82b0-4cc7-8e4e-abc9fa9ab63f%22%3A%7B%22acceptedCategories%22%3A%5B%22L5%22%5D%7D%7D%7D

**Comment by viddo** [comment]
I believe this is something that should be handled further down, in cartodb.js

**Comment by viddo** [comment]
Issue moved to [CartoDB/cartodb.js #1345](https://github.com/CartoDB/cartodb.js/issues/1345) via [**ZenHub**](https://www.zenhub.com/)
