### ISSUE TITLE
Remove layer limit for builder

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#8712]
Currently set to 4. This shouldn't be a limiting factor anymore. We'll just set the limit to the max always (10).

cc/ @saleiva @xavijam

**Comment by javisantana** [comment]
the UI does not limit but each layer means a pretty big impact at maps api level

**Comment by gfiorav** [comment]
The UI prevents you from selecting more than the max layer limit for your account type (basic is 4) and if you add them one by one you get a an error when trying to add the limit + 1 layer.

I understand it's a good idea to leave this behaviour as is then?

**Comment by viddo** [comment]
There is no such limit checked on the builder yet (AFAIK), so then we need to add it. Especially for the drag'n'drop analysis nodes. How should this be indicated to the user?

**Comment by urbanphes** [comment]
@saleiva we need think on these cases

**Comment by saleiva** [comment]
10 layers

**Comment by saleiva** [comment]
enterprise users will have 10 as limit

**Comment by gfiorav** [comment]
Makes total sense!

Can we forward think this now? Every time we update this we have to run some heavy queries on central and that triggers syncing with the boxes and so on. It's a delicate moment for the platform. It's better if we do it in one go! :)

As of now:

+ Everybody: 8 layers
+ Enterprise: 10 layers

I had this ready but I won't get to deploy it before going on vacation. Maybe @javitonino can take over it? 

Central PR https://github.com/CartoDB/cartodb-central/pull/1325
Box PR https://github.com/CartoDB/cartodb/pull/8921

**Comment by saleiva** [comment]
ok cool!

**Comment by javitonino** [comment]
Update task is running, will take a few days to complete (until friday most likely).

**Comment by javitonino** [comment]
All done!
