### ISSUE TITLE
forgot password option is not appearing at username.carto.com/login page

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartodb#8717]
When you access to the ```https://username.carto.com/login``` page, the  ```Forgot?``` option that sends an email to regenerate the password of the account is not being displayed.

In the ```https://carto.com/login``` page, the "Forgot?" option appears correctly.

**Comment by juanignaciosl** [comment]
Carto itself has never had that feature. In order to do it without duplicating the code we could just add the link to `/password_resets/new` when `unless Cartodb.config[:cartodb_com_hosted]` (we only want that link to appear in the Saas).
