### ISSUE TITLE
Default image header height has changed for existing Editor infowindows

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#8720]
Hi @matallo would you please reassign if needed? Thank you!

S/B 9372329
S/B 9366273

Default image height has changed in Editor infowindows for client's existing maps.

## Context
Default image height was taller in previous default Editor image headers.

## Process
1. Prepend your dataset's image column with a _ so it alphabetically comes before other columns
2. Open infowindow panel to the Click tab, & make sure the _image column is at top of column name stack
3. Choose image header from the pulldown menu
4. Toggle on the _image column & any others

## Expected result

When you click to open infowindow the image height will be larger than ~35px
(sorry, can't get old default height b/c all image infowindows are shorter now for me)

## Current result

![screen shot 2016-07-08 at 10 45 21 am](https://cloud.githubusercontent.com/assets/1779444/16691081/19669da8-44f9-11e6-84b3-2662f18de7b5.png)

----

## Example

https://team.carto.com/u/stephaniemongon/viz/0ebc5590-448c-11e6-bcc5-0ecd1babdde5/public_map

## Work-around:
1. In Editor click on </> button in map menu's infowindow panel to expose HTML
2. Add min-height style inline for the .cartodb-popup header with-image v2, .cartodb-popup-header, and . cover divs

----

Clients are noticing this in their Editor maps, can we reset to old default height?

**Comment by ztephm** [comment]
S/B 9373251 also.

**Comment by michellechandra** [comment]
S/B 9372455

**Comment by matallo** [comment]
can't reproduce, is this still happening?

![screen shot 2016-07-11 at 15 14 30](https://cloud.githubusercontent.com/assets/36676/16731785/3d160634-477a-11e6-98d9-1eec8a9c9f75.png)
![screen shot 2016-07-11 at 15 14 34](https://cloud.githubusercontent.com/assets/36676/16731784/3d0f352a-477a-11e6-8f86-3876f2bc5cef.png)

/cc @xavijam

**Comment by ztephm** [comment]
All good now in my test map, thanks!
