### ISSUE TITLE
Feature Request: Give users ability to add more auto-styled categories via widget

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#8722]
Right now if you create a Formula Category Widget based on a string-type column and autostyle it there are 5 default categories and rest are grouped into "Other". 

Can we give users the ability to add more categories via the Widget, like they can via Layer Styles tab?

## Context
You can create more categories by **not** using the widget. Instead you can:
* click on the Layer's name
* click it's Style tab
* in the Style tab's Style section click on the Fill number
* in the Fill popup click the By Value tab and choose the name of your string column that contains the categories you need
* click the Fill popup's Fixed tab and slide the Value higher (or enter number of categories in the input field)

## Process 
To enable the Category widget with autostyling:
1. From Maps page click into the map you want
2. Click Widgets tab
3. Click Add Widget
4. In the Add new widgets page click Category button and check the box for the string-type column that contains your categories & click Continue
5. In the widget that appears on right side of the page click the teardrop icon to auto-style

## Current result

![screen shot 2016-07-08 at 5 18 18 pm](https://cloud.githubusercontent.com/assets/1779444/16701768/ffe85ca4-452f-11e6-868e-097e6f57e08e.png)

----
https://stephaniemongon.carto.com/builder/42f58d7a-454c-11e6-9ec5-0e05a8b3e3d7/embed?state=%7B%22map%22%3A%7B%22center%22%3A%5B40.420553506787094%2C-3.7164688110351562%5D%2C%22zoom%22%3A11%7D%2C%22widgets%22%3A%7B%224b1c8d59-dc34-44b0-9281-449bacbf30de%22%3A%7B%22autoStyle%22%3Atrue%7D%7D%7D

Well 276 categories in this example is def too much but can we give users the ability to at least add up to 10 or 12? AFAIK over 10-12 means you'll be using colors that are harder to differentiate from each other, but maybe @makella has a better idea about it?

**Comment by makella** [comment]
@ztephm we have 10 colors available with the 11th color as 'other' (grayish) for all of our category palettes. So we can support up to 11 different categories.

We should add a ticket to deepinsights because in the example above, gray should be applied to 'other' not to the third category in the list. Let me test it a little more and I will add a ticket there.

Like you mention, greater than that will be too many so if we can keep within that range, I feel like it would be best.

**Comment by saleiva** [comment]
Designed in https://github.com/CartoDB/deep-insights.js/issues/442
