### ISSUE TITLE
How do I enable the builder?

### ISSUE THREAD

**Issue by snario** [CartoDB/cartodb#8723]
I have cloned the repo and gone through all set up correctly. I am now trying to figure out how to enable Builder. I've been scanning this repo for traces of the term `builder_enabled` but I cannot figure out how to actually start working with it! Please any help is appreciated.

What I have tried:

```bash
$ bundle exec rake cartodb:features:add_feature_flag["builder_enabled"]
$ bundle exec rake cartodb:features:enable_feature_for_all_users["builder_enabled"]
```

**Comment by javisantana** [comment]
just replace /viz/ by /builder/ when you are in a visualization. Remember to remove the /map at the end.

Anyways, you'll need much more than that to get it working but you'll get something

**Comment by snario** [comment]
@javisantana Thank you I hadn't tried to remove the /map part.

>  you'll need much more than that to get it working 

Could you point me in the right direction please?

**Comment by javisantana** [comment]
@snario we will release official installation documentation when it's ready

**Comment by snario** [comment]
Okay thank you
