### ISSUE TITLE
"delete layer" modal is confusing

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/cartodb#8724]
When removing a layer from the layers list users are presented with the following dialog:
<img width="328" alt="screen shot 2016-07-10 at 22 03 31" src="https://cloud.githubusercontent.com/assets/1041056/16718086/4bb33b5c-46ea-11e6-871a-fe00d397a31a.png">

If I would like to not have the layer in this map, I can choose "Delete Layer", which will remove the layer from the current map, but not delete the data associated with the layer. Maybe clearer language would be "Remove Layer from map". Clearer language should be used with the confirmation dialog as well:

<img width="500" alt="screen shot 2016-07-10 at 22 07 06" src="https://cloud.githubusercontent.com/assets/1041056/16718118/b6024188-46ea-11e6-8c57-abb8b3e3eb4b.png">

**Comment by saleiva** [comment]
duplicated! https://github.com/CartoDB/cartodb/issues/8659
