### ISSUE TITLE
Help elements are not styled correctly

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#8734]
![screen shot 2016-07-11 at 12 13 45](https://cloud.githubusercontent.com/assets/132146/16727367/0cb7718a-4761-11e6-99b9-5b28a1f91809.png)

**Comment by javierarce** [comment]
Duplicated here: https://github.com/CartoDB/cartodb/issues/8616.

**Comment by xavijam** [comment]
Thanks @javierarce
