### ISSUE TITLE
tablestats should use user schema name

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb#8744]
Table stats component should use schema to retrieve information: https://github.com/CartoDB/cartodb/blob/6c8b9369e339e9c070475beb6b433f98fab67793/lib/assets/javascripts/cartodb3/components/modals/add-widgets/tablestats.js#L38

Now it returns information for any table matching the name, in multi-user accounts two users with the same table name will get stats for both tables.

Example queries that will work with schema name:

```sql
SELECT c.reltuples
FROM pg_class c, pg_catalog.pg_namespace n
WHERE n.nspname = 'schema_name'
  AND c.relname = 'table_name';
```

```sql
SELECT *
FROM pg_stats
WHERE schemaname = 'schema_name'
  AND tablename = 'table_name';
```

cc @saleiva

**Comment by fdansv** [comment]
This was fixed in https://github.com/CartoDB/cartodb/pull/8825
