### ISSUE TITLE
Custom value is missing from the dropdown and needed for example in geocoding analysis

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8759]
![screen shot 2016-07-11 at 17 40 36](https://cloud.githubusercontent.com/assets/132149/16736751/a7f88f58-478e-11e6-8a66-ed19ef662215.png)

**Comment by javierarce** [comment]
Cool! But why is this a bug?

**Comment by saleiva** [comment]
Because it doesn't let me to geocode my data like in the prev. version

**Comment by javierarce** [comment]
👌

**Comment by javierarce** [comment]
Ok, the component is in the master branch. I'm waiting for https://github.com/CartoDB/camshaft/issues/137 to close the ticket.

**Comment by saleiva** [comment]
Done! yay!
