### ISSUE TITLE
Remove the 'Dataset copy is not defined' error

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#8765]
cc @andrewxhill @csobier 
similar: https://github.com/CartoDB/cartodb/issues/8676

The **Dataset copy is not defined error** occurs in the upload model here:
https://github.com/CartoDB/cartodb/blob/master/lib/assets/locale/en.json#L133

I was unable to generate the error by:
* importing a duplicate of a dataset already in my account via Builder UI
* importing a duplicate of a dataset already in my account via Import API
* Clicking on the dataset to select it in Datasets page & clicking Duplicate dataset

Can we delete this error, or am I missing how it's generated?

**Comment by xavijam** [comment]
If there is a duplication where the value is not defined we show this error. It is something we use internally and basically preventing import errors. Let me close it and if the error appears and it is too visible, let's open a new one and we will take care of it.
