### ISSUE TITLE
Implement confirmation module for paid analysis

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8766]
@urbanphes can you attach the designs?

**Comment by xavijam** [comment]
Yes please, I'll implement it tomorrow 🙏  💋  ❤️

**Comment by urbanphes** [comment]
Hi @xavijam here the mockup

<br>
![01 layers - 06-55 analysis - calculate paths - no extra payment](https://cloud.githubusercontent.com/assets/14546701/16756874/61f5cfc8-4808-11e6-9275-3da89e9b6419.png)

**Comment by saleiva** [comment]
Hey @urbanphes, we had also other states for being close to the limit and
so on, dont you think?
On Jul 12, 2016 8:12 AM, "Juanma" <notifications@github.com> wrote:

Hi @xavijam <https://github.com/xavijam> here the mockup



[image: 01 layers - 06-55 analysis - calculate paths - no extra payment]
<https://cloud.githubusercontent.com/assets/14546701/16756874/61f5cfc8-4808-11e6-9275-3da89e9b6419.png>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/CartoDB/cartodb/issues/8766#issuecomment-231946611>,
or mute
the thread
<https://github.com/notifications/unsubscribe/AAIENVjiU_sBL3YciP9kBYqmvo77834Uks5qUzBdgaJpZM4JJkoo>
.

**Comment by urbanphes** [comment]
@saleiva you mean this?
<br>
![01 layers - 06-54 analysis - calculate paths - extra payment](https://cloud.githubusercontent.com/assets/14546701/16757537/0018f4d8-480d-11e6-8dac-3f14eae00008.png)

**Comment by xavijam** [comment]
Should we allow users without credits choose those analysis in the "add-analysis" modal?

**Comment by saleiva** [comment]
Yes, it's a good CTA, don't you think? And also, all analysis have a free
variation right now

On Jul 13 2016, at 3:27 pm, Javier Álvarez Medina
&lt;notifications@github.com&gt; wrote:  

> Should we allow users without credits choose those analysis in the "add-
analysis" modal?

>

> —  
> You are receiving this because you were mentioned.  
> Reply to this email directly, [view it on
GitHub](https://github.com/CartoDB/cartodb/issues/8766#issuecomment-232354138),
or [mute the
thread](https://github.com/notifications/unsubscribe/AAIENYS-G-9mdsp6IMbuVPOSsmcnMl4Bks5qVOebgaJpZM4JJkoo).![](https://github.com/notifications/beacon
/AAIENVq0R9YcLpJVhB-bI1YLVtNI4laeks5qVOebgaJpZM4JJkoo.gif)
