### ISSUE TITLE
feature request: communicate new information added as a result of the analysis

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/cartodb#8770]
Right now, a user is not aware of how the dataset is transformed without manually inspecting the table after the analysis is applied. To help a user make decisions about the next steps to be taken with a dataset (cartography, more analysis, etc.), it would be very useful to have some type of dialog which communicates the transformations that have happened to a dataset, like:

1. "these new columns were added to your data" --> with links to documentation if the user needs more information
2. "This is the new schema" if a reductive operation was applied such as a convex hull

cc @CartoDB/research

**Comment by saleiva** [comment]
Yep, we have something already designed but its missing implementation. @urbanphes can you share here the mockups?

**Comment by urbanphes** [comment]
Here some examples of visual designs after apply analysis
<br>
**Message 1**<br>
![01 layers - 06-09 analysis - finished message 1](https://cloud.githubusercontent.com/assets/14546701/16756997/678ded98-4809-11e6-9b8a-eac4a6609681.png)
<br>
**Message 2**<br>
![01 layers - 06-10 analysis - finished message 2](https://cloud.githubusercontent.com/assets/14546701/16757016/8ca5018e-4809-11e6-88a0-f7d060ef467c.png)
<br>
**Message 3**<br>
![01 layers - 06-11 analysis - finished message 3](https://cloud.githubusercontent.com/assets/14546701/16757022/970085fe-4809-11e6-8e58-dbfae37981d6.png)

**Comment by stuartlynn** [comment]
@saleiva Can we have a placeholder within those interfaces where a widget could inject some details of the result of the analysis, like stats or perhaps even a plot or just some text about what it is producing

**Comment by andrewxhill** [comment]
would be amaz to actually show the Widget with a button-- "Add THIS widget"

**Comment by andrewxhill** [comment]
A challenge I'm curious about with those interfaces... is for longer running analyses. We actually know before they start the analysis how we plan to style the output and what kind of widget would be available. So for a longer running analysis, we are actually making them wait for something we already know about. On top of that, it makes the pop-up a pain for anyone trying to move quickly through the interface.

I'd much rather see this as an immediate interface after clicking, Run Analysis.... that you decide on even while the analysis is waiting to finish

**Comment by saleiva** [comment]
hey @andrewxhill that's true and not true at the same time. There are several situations that could happen like errors, that would make the analysis not running, so the frustration will be even higher if the user performs more actions (I know Carto never fails, yeah).

BUT, love the idea about the widget.

**Comment by andrewxhill** [comment]
Awesome. So widget we go!!

Re. the interface bit. To clarify. I'm not saying we show the widgets/change the maps before the analysis completes. I'm saying we show the user all options related to the output before it completes. IF it doesn't complete, obviously those options are scratched. So, 

1. I run Clusters
2. I click apply
3. It runs
4. At the same time it shows me whatever interface letting me know about the styles/widgets and new columns available. I select any options I want from those
5. It finishes.
* If it succeeds it applies options from 4
* If it fails it just gracefully stays the same and notifies of the issue

**Comment by saleiva** [comment]
Gotcha, yeah... but that would require to block the UI somehow (in terms of
layout) and we are trying to avoid that at that stage, but it's worth to think
on a way that is not so invasive

On Jul 13 2016, at 4:12 pm, Andrew W. Hill &lt;notifications@github.com&gt;
wrote:  

> Awesome. So widget we go!!

>

> Re. the interface bit. To clarify. I'm not saying we show the widgets/change
the maps before the analysis completes. I'm saying we show the user all
options related to the output before it completes. IF it doesn't complete,
obviously those options are scratched. So,

>

>   1. I run Clusters

>   2. I click apply

>   3. It runs

>   4. At the same time it shows me whatever interface letting me know about
the styles/widgets and new columns available. I select any options I want from
those

>   5. It finishes.

>   6. If it succeeds it applies options from 4

>   7. If it fails it just gracefully stays the same and notifies of the issue

>

>

> —  
> You are receiving this because you were mentioned.  
> Reply to this email directly, [view it on
GitHub](https://github.com/CartoDB/cartodb/issues/8770#issuecomment-232367409),
or [mute the thread](https://github.com/notifications/unsubscribe/AAIENZy--
SMVI6xptnHlwQWsRshzoqHwks5qVPJJgaJpZM4JJo6b).![](https://github.com/notifications/beacon/AAIENYHfMGMseCqToHLC3rrOl_3akkGRks5qVPJJgaJpZM4JJo6b.gif)

**Comment by saleiva** [comment]
Already being done at https://github.com/CartoDB/cartodb/issues/8866
