### ISSUE TITLE
ability to clear denominator for moran analysis

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/cartodb#8771]
Right now, if I choose a denominator in moran there is no way to get rid of it it i change my mind and only want to use numerator. Having a way to clear the values in a field would be great because right now I have to delete and then create the analysis again.

**Comment by javierarce** [comment]
@urbanphes: I'm assigning you this ticket because first, we need to design a way to unselect items in a combo box (I haven't seen it in the designs.) Once it's done assign me the ticket and I'll finish the implementation :)

**Comment by urbanphes** [comment]
oks @javierarce I'm going to work on this

**Comment by urbanphes** [comment]
Here the visual design for this case.
<br>
**Unselect**<br>
![01 layers - 06-210 analysis - moran cluster](https://cloud.githubusercontent.com/assets/14546701/16766317/acd30020-4839-11e6-861d-88b57fc5d2d7.png)
<br>
<br>
**Select**<br>
![01 layers - 06-211 analysis - moran cluster](https://cloud.githubusercontent.com/assets/14546701/16766323/c06879ee-4839-11e6-8132-78ce9d8c0516.png)
