### ISSUE TITLE
Dataset not connecting properly via URL

### ISSUE THREAD

**Issue by asimcox** [CartoDB/cartodb#8773]
## Context
When I was executing the [smoke test 1](https://docs.google.com/spreadsheets/d/1P8FQSvHJMojKhsygR7AMafQKYhybEJYS7W45-sgGnuk/edit#gid=1195336423), I copied the dataset URL in step 8 and it didn't upload via our UI, but I was able to download the file (to finder) and then import it via drag and drop in my dataset page.

## Process
1. On step 8 of Smoke Test 1, copy the dataset URL.
2. I went into my Builder account, and clicked on create a new map --> Connect Dataset
3. I pasted the URL into the field and pressed 'submit'
4. It would not connect the dataset.  I was able to download the file (in my browser) and then upload it by dragging and dropping it into my dataset page.

![screen shot 2016-07-11 at 2 42 54 pm](https://cloud.githubusercontent.com/assets/16105514/16742931/01c02b8e-4778-11e6-9f27-07bad669db0b.png)

## Expected result
I expected the file to import the same way via either import method. 

## Current result
![screen shot 2016-07-11 at 2 40 52 pm](https://cloud.githubusercontent.com/assets/16105514/16742958/1912ad34-4778-11e6-8538-12ea14a600c2.png)

**Comment by javitonino** [comment]
This has been solved for now. An stale table was created by another import process that made this one to fail. Thanks @iriberri for her help investigating this. She is investigating the root cause here: https://github.com/CartoDB/cartodb/issues/8785
