### ISSUE TITLE
Allow Category Widget to be applied to Numeric columns

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#8774]
To recreate.

1. Import or create a map from any Point dataset
2. Do a cluster analysis with 3 clusters
3. Try to create a Category Widget from the newly derived column, category_no 

you can't, but it would make sense

**Comment by saleiva** [comment]
There is a workaround for the time being which is changing the type of the builder once you add it as a histogram.

**Comment by saleiva** [comment]
For showing this within the category widget list we should make sure that at least top X% are withing the top 10 categories.

**Comment by xavijam** [comment]
I feel it is an easy one.

**Comment by saleiva** [comment]
This is already working Id say.
