### ISSUE TITLE
Change default basemap ordering based on datatype: E.g. Point Dataset => Positron labels beneath

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#8775]
When a user is presented the map the first time, it makes sense that 
1. If the dataset is Polygons, 80% of the time it will be a helpful starting point to put the labels on top
2. If the dataset is Points, 80% of the time it will be more helpful to have the labels beneath
3. Lines are a toss-up

**Comment by makella** [comment]
@javisantana is this possible?
