### ISSUE TITLE
Proposed Analysis to Styling workflow via Widgets

### ISSUE THREAD

**Issue by makella** [CartoDB/cartodb#8776]
We have a suggestion on a proposed workflow that combines widgets and default styling in the map view when running through analysis methods.

As pointed out [here](https://mail.google.com/mail/u/0/#label/GitHub_Notifications/155db31aa795cc91) it is difficult to know what fields have been created as a result of an analysis method. It is also difficult to know what styling should be applied to best visualize the results of the analysis. 

We have a proposed workflow that we think will more easily guide users through both steps.

**1. Automatically Add Widgets from Derived Column(s)** 

Have a Widget output on the right-hand panel derived from the new fields that have been added as a result of an analysis method   
- For example, if someone ran Moran’s i, when the analysis is finished, two widgets would show in the right hand panel: quads and significance

<img width="1274" alt="screen shot 2016-07-11 at 2 31 51 pm" src="https://cloud.githubusercontent.com/assets/1566273/16745702/42a3e522-4774-11e6-8868-d72fc7cb470f.png">

**2. Styling**  
The styling defaults we define for each analysis output would be tied to a type of auto styling that is only inside of the map view.
- If a user clicks on the tear drop icon on a Widget inside of the map view, the styling on the map will default to our predefined styling for that analysis method
  - These styles would be based off defaults that we think are most appropriate to display the analysis results.  
- The user could choose to keep the ‘map view auto style’ or they could choose their own
  - This would be different than the embed map auto styling
- When adding a second, third or Nth analysis, it would override the set Style if selected to do so by the user

cc: @andrewxhill @stuartlynn @ohasselblad @talos

**Comment by makella** [comment]
An addendum to step 1. We wouldn't want to add widgets for every new column added to the data, only the ones that are most relevant to the analysis. 

Using the same example, Moran's i produces more than just the `quads` and `significance` attributes, but those are the only two that we would want added as widgets.

We can help formulate a list of columns that should become widgets based on analysis method.

cc @stuartlynn

**Comment by saleiva** [comment]
I really think we need also a default styling that is not depending on the drop button of the widgets.

**Comment by makella** [comment]
i do too... I'm trying to figure out how we can do both.

One idea:
We have default styling that is the same styling as if you clicked on the inside map view tear drop on the widget. When the widget is added, the teardrop is on by default. If you uncheck the widget teardrop, you go back to default default.

Basically, the workflow here would be:
- run analysis
- widgets added to the view tied to new column(s)
- by default, the teardrop would be activated and the default styling for that analysis is there
- turn the teardrop off, and the default styling for that analysis goes back to default
- user can select their own style or select the default style from the teardrop

But this raises some questions:
- if multiple analysis are run, and the user selects default styling, how do we make all the combinations of possible analysis look good together? f
- when more than one widget is added as a result of an analysis, which widget should be on by default?

Any other ideas on a workflow here for the styling piece?

**Comment by andrewxhill** [comment]
My proposal was that we change the behavior of the teardrop slightly

1. Teardrop symbology probably would need to change
2. The teardrop is an informed best style based on what is showcased in the widget (aka, autostyle).
3. When the user clicks it, the teardrop derived style becomes the NEW base style for that map
4. The teardrop isn't published publically with the map, it is just a shortcut to applying a new Style to the layer

**Comment by makella** [comment]
@andrewxhill so what do you see the default map style being when the analysis is finished? I was interpreting what @saleiva was saying as that. 

That's why I was thinking that maybe the teardrop derived style should just be on after the analysis is finished which means that the teardrop would be on by default? And then the user can choose to use the teardrop style for their public map if they want or create their own.

**Comment by andrewxhill** [comment]
Sorry, yes, that is the end of my thought. When a new analysis is applied, there should be two options inside the analysis.

- [x] AutoWidget
- [x] AutoStyle

So when a user applies that new analysis, it will,

* Based off the first checkbox, add a new widget
* Based off the second checkbox, apply that autostyle of that Widget, so Teardrop will appear activated for that new widget

The user can then avoid overwriting any of their custom styles by just unchecking the autostyle option.

**Comment by makella** [comment]
@piensaenpixel this issue should also be considered with the default analysis styling (https://github.com/CartoDB/cartodb/issues/8162#issuecomment-366651813)

**Comment by piensaenpixel** [comment]
+1 @makella
