### ISSUE TITLE
Analysis Output Column Naming Suggestions

### ISSUE THREAD

**Issue by makella** [CartoDB/cartodb#8777]
Below are two proposals for column names produced by analysis methods. The goal with both suggestions is to make column names more descriptive and less ambiguous.
1. Keep column names connected to the field they were derived from
   - Example workflow
     - augment a point dataset with “Population” from the Data Observatory function
     - set the column name to `population` 
     - if we run the Moran’s i function on the augmented point dataset, the default column names will be `quads` and `significance` instead, we think it would be better if they were named something closer to their origin like `population_quads` and `population_significance`
2. Make output column names less ambiguous (related to point 1)
   - Example
     - with Cluster Analysis, if you aggregate by some method (sum, count, avg...), the output is written into a column `value`. We think it would make more sense for the output column name to be more descriptive of the aggregation, like `value_sum`, `value_count`, etc.

cc @andrewxhill @stuartlynn @ohasselblad @talos

**Comment by saleiva** [comment]
Can you create separate tickets for these? All looks pretty good to me :)

**Comment by makella** [comment]
@salveia just to be clear, you mean add a separate ticket for each analysis method and what we would like the column names to be?

**Comment by saleiva** [comment]
Yep, I think that will work better

**Comment by makella** [comment]
ok, cool.

@andrewxhill @stuartlynn @ohasselblad @talos will need your help with this!

**Comment by makella** [comment]
@andrewxhill @stuartlynn @ohasselblad @talos

also related to which columns should be output as widgets as a result of each analysis. definitely think step one of the ticket below and this are related...
https://github.com/CartoDB/cartodb/issues/8776

**Comment by makella** [comment]
@hannahblue tagging you here to look over and decide if we should keep open.

**Comment by hannahblue** [comment]
Thanks @makella. We'll keep this open, and look into it.
