### ISSUE TITLE
Improve Aesthetics of the read only SQL panel

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8779]
When being read only (for example in an analysis layer) It doesnt look deactivated and the module on the button looks weird.
When being default the syntax coloring is weird as well

**Comment by urbanphes** [comment]
Here the visual design.

![01 layers - 01-12 data](https://cloud.githubusercontent.com/assets/14546701/16774872/3ac033de-485e-11e6-88f2-fd3dc69abdb1.png)
<br>
- All links in this type of screen (darker) should be on white.
- Info-Box with 24% opacity in black and the text inseide the box en yellow except the link is white.
- The code color should be #979EA1.
<br>
<br>
How do you see this? @saleiva

**Comment by saleiva** [comment]
Better but still weird.

  * Why don't we keep the coloring on the text and add opacity?
  * The band on the bottom is what I dislike the most.

But getting better :)

  

On Jul 12 2016, at 6:28 pm, Juanma &lt;notifications@github.com&gt; wrote:  

> Here the visual design.

>

> [![01 layers - 01-12
data](https://cloud.githubusercontent.com/assets/14546701/16774872/3ac033de-
485e-
11e6-88f2-fd3dc69abdb1.png)](https://cloud.githubusercontent.com/assets/14546701/16774872
/3ac033de-485e-11e6-88f2-fd3dc69abdb1.png)  
>  
>

>

>   * All links in this type of screen (darker) should be on white.

>   * Info-Box with 24% opacity in black and the text inseide the box en
yellow except the link is white.

>   * The code color should be #979EA1.  
>  
>  How do you see this? [@saleiva](https://github.com/saleiva)

>

>

> —  
> You are receiving this because you were mentioned.  
> Reply to this email directly, [view it on
GitHub](https://github.com/CartoDB/cartodb/issues/8779#issuecomment-232101186),
or [mute the
thread](https://github.com/notifications/unsubscribe/AAIENdhWfvXu6-wx0wRrbtVwGdygRKQOks5qU8DAgaJpZM4JKIUB).![](https://github.com/notifications/beacon/AAIENRMJgkh8L_cI0X3Q8nvFMSCHFPx3ks5qU8DAgaJpZM4JKIUB.gif)

**Comment by urbanphes** [comment]
In this case I'll try tu put the code with the same colors but with opacity (48%) and the info-box on the original color. Is a normal info not a warning info.
<br>
![01 layers - 01-12 data](https://cloud.githubusercontent.com/assets/14546701/16776726/025f0a5c-4867-11e6-869d-9adb987dccd1.png)

**Comment by saleiva** [comment]
But that infobox is even weirder...

**Comment by urbanphes** [comment]
I test with info-box background opacity 8% white

![01 layers - 01-12 data](https://cloud.githubusercontent.com/assets/14546701/16797498/27855da0-48e8-11e6-9955-420133d6176c.png)

**Comment by urbanphes** [comment]
This approach has a info-box background color #000 (32%). Title and subtitle #979EA1 and text link #fff

![01 layers - 01-12 data](https://cloud.githubusercontent.com/assets/14546701/16865331/313708a8-4a64-11e6-9fc4-36505379a514.png)
