### ISSUE TITLE
Review stale tables process for cartodb_query tables

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#8785]
Related: https://github.com/CartoDB/cartodb/issues/8773

id: `0bad4fec-a098-4cd5-b39b-d0acd6c869a1`
index: `importer_2fd28d5cff6411e5a5e70ef24382571b`

**Comment by iriberri** [comment]
With the issue related above we started getting rid of the tables in the `cdb_importer` schema which were causing the colision. Ideally, for a clean `cdb_importer` without stale tables, name conflicts should not be happening anymore.

**Comment by javitonino** [comment]
I had an issue with this today #10392. Just a quick question, did you delete the stale tables in cdb_importer for dbd-team?
