### ISSUE TITLE
Missing image in basemap tab

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#8789]
![image](https://cloud.githubusercontent.com/assets/1214201/16762920/e2c1c3fa-4826-11e6-96bc-df40cb7be95d.png)

**Comment by matallo** [comment]
I'll take a look, this comes after changing cartodb => carto in the categories

**Comment by matallo** [comment]
may it be replacing the name in https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb3/editor/layers/basemap-content-views/basemap-icons/basemap-cartodb.tpl ?
