### ISSUE TITLE
Auto indexing timeouts

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#8791]
We are getting timeouts while indexing large tables. We should increase the timeout a bit for this use case.

**Comment by javitonino** [comment]
After some investigation, it appears due to random slowdowns/connectivity issues (maybe deploys). It doesn't make sense for it to timeout (5 min) in tables with 50k rows. Leaving for now, but I'll keep monitoring this.

**Comment by juanignaciosl** [comment]
Any news on this? If this is not a problem we might close it.

**Comment by javitonino** [comment]
It appears to be fine, I haven't seen it pop up too much. I guess I'll close it for now, we can always reopen if it's problematic. It can sometimes create an invalid index: #9537
