### ISSUE TITLE
Notifier messages gets badly wrapped

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#8798]
![screen shot 2016-07-12 at 11 02 09](https://cloud.githubusercontent.com/assets/978461/16766548/2bef45a2-483b-11e6-859c-ec7c182c2c8c.png)
![screen shot 2016-07-12 at 14 15 22](https://cloud.githubusercontent.com/assets/978461/16766549/2bf7c286-483b-11e6-990c-f88e86b98242.png)

Appears on both Chrome and Firefox

**Comment by xavijam** [comment]
cc @nobuti, because we changed on purpose.
