### ISSUE TITLE
Provide visual layer cue on layer-content view

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#8805]
Compare:
<img src="https://cloud.githubusercontent.com/assets/978461/16770772/6ba07c8a-484e-11e6-92cb-dc8657178f5e.png" alt="screen shot 2016-07-12 at 16 29 08" width="40%"> vs: <img src="https://cloud.githubusercontent.com/assets/978461/16770771/6b63c4ac-484e-11e6-84de-edc4d06a7b9f.png" alt="screen shot 2016-07-12 at 16 29 08" width="40%">

When editing layer I quickly forget what layer I was actually editing, why not be consistent and provide the letter+color+head node id next to the layer name like we do in other places (e.g. layer dropdown)?

cc @saleiva

**Comment by urbanphes** [comment]
In this case only shows the letter because is the id of layer.
I've trying put the id beside the title. 
<br>
Here the visual design:
![image](https://cloud.githubusercontent.com/assets/14546701/16776466/c14f8a1a-4865-11e6-8c67-e82ae51fffbe.png)



cc/ @saleiva

**Comment by saleiva** [comment]
Don't you see a little alignement issue with the datasource icon?

**Comment by urbanphes** [comment]
This icon (letter) had 8px of marging-right and the datasource icon had 4px. I had done so by the difference in text size. 
<br>Here you can see with the same margin-right (4px).
![image](https://cloud.githubusercontent.com/assets/14546701/16778024/5bbc9af6-486c-11e6-8006-e1c2976b2a11.png)


The vertical aligment is the same.

**Comment by saleiva** [comment]
Why don't we align the icons ant the texts?

**Comment by urbanphes** [comment]
Adjusting vertical alignments

![image](https://cloud.githubusercontent.com/assets/14546701/16799527/81c90812-48f1-11e6-9852-26c8c3c58cb3.png)

**Comment by urbanphes** [comment]
This is the final version.

![01 layers - 01-01 data](https://cloud.githubusercontent.com/assets/14546701/17021565/1d094e42-4f49-11e6-858d-fd79f9961310.png)

**Comment by saleiva** [comment]
:love:
