### ISSUE TITLE
Tooltip required missaligned

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#8806]
In Join columns from 2nd layer analysis

![image](https://cloud.githubusercontent.com/assets/1214201/16771598/62c897f2-4851-11e6-89a3-0fc90970409d.png)

**Comment by javierarce** [comment]
Argh :(

**Comment by piensaenpixel** [comment]
sorry @javierarce  :(

**Comment by xavijam** [comment]
Not happening right now with that analysis. Let me close it and if it appears again let's open a new one 💋 ❤️ .
