### ISSUE TITLE
Missing "Password" tag on Privacy Modal and small enhancement 

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#8807]
- [ ]  Add missing tag:

Prod:
![screen shot 2016-07-12 at 15 41 16](https://cloud.githubusercontent.com/assets/596509/16771878/5f052fb2-4852-11e6-8600-10f22f5e6c19.png)

Expected:
<img width="192" alt="screen shot 2016-07-12 at 17 03 51" src="https://cloud.githubusercontent.com/assets/596509/16771958/a1bfcb1e-4852-11e6-9c5e-262fa82c2bb2.png">

- [ ] Also as an small improvement it would be awesome if we could add more weight to the tag's texts. `font-weight:600;` works for me.

- [ ] Also for the title, I would add an 400 of font weight, it looks really light right now.

THX!

**Comment by xavijam** [comment]
Please @nobuti

**Comment by nobuti** [comment]
👍

**Comment by nobuti** [comment]
New design, closing.
