### ISSUE TITLE
Alpha value in the builder styles does not work

### ISSUE THREAD

**Issue by mbforr** [CartoDB/cartodb#8817]
If you set Alpha to 0 that won't work, but 0.01 works. See below.
![alpha](https://cloud.githubusercontent.com/assets/4828460/16782570/2ef4e4c4-484e-11e6-9713-45b0d289e419.gif)

**Comment by javierarce** [comment]
Thanks for the nice report! 

It looks like [we are not sending the opacity when the value is zero](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb3/editor/style/style-converter.js#L96). Curiously, we are doing the right thing [when it comes down to polygons](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb3/editor/style/style-converter.js#L118) :)

**Comment by saleiva** [comment]
BOOM
