### ISSUE TITLE
Point styles not carrying over to the embed

### ISSUE THREAD

**Issue by mbforr** [CartoDB/cartodb#8818]
![embed](https://cloud.githubusercontent.com/assets/4828460/16782639/75b56b0e-484e-11e6-85a2-e3f14f294e85.gif)

**Comment by saleiva** [comment]
Looks like a cache issue. @mbforr can you provide us access to the map so we can debug it? cc/ @rochoa @javisantana

**Comment by mbforr** [comment]
Just need a public link?

On Tue, Jul 12, 2016 at 7:22 PM, Sergio Álvarez Leiva <
notifications@github.com> wrote:

> Looks like a cache issue. @mbforr <https://github.com/mbforr> can you
> provide us access to the map so we can debug it? cc/ @rochoa
> <https://github.com/rochoa> @javisantana <https://github.com/javisantana>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/8818#issuecomment-232211244>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEmtLHLWsa6iwgkgEEo7vtrJG9MQBsoRks5qVCG-gaJpZM4JKzCE>
> .
>



-- 
*Matt Forrest*
Client Success Manager

*CARTO*
201 Moore St, Brooklyn, NY, 11206
P: (917) 463-3232 x7508
C: (612) 325-8470
carto.com <http://www.carto.com/>

**Comment by saleiva** [comment]
An we might need to access to the builder one

On Jul 13 2016, at 1:29 am, Matt Forrest &lt;notifications@github.com&gt;
wrote:  

> Just need a public link?  
>  
>  On Tue, Jul 12, 2016 at 7:22 PM, Sergio Álvarez Leiva &lt;  
>  notifications@github.com&gt; wrote:  
>  
>  &gt; Looks like a cache issue. @mbforr &lt;https://github.com/mbforr&gt;
can you  
>  &gt; provide us access to the map so we can debug it? cc/ @rochoa  
>  &gt; &lt;https://github.com/rochoa&gt; @javisantana
&lt;https://github.com/javisantana&gt;  
>  &gt;  
>  &gt; —  
>  &gt; You are receiving this because you were mentioned.  
>  &gt; Reply to this email directly, view it on GitHub  
>  &gt;
&lt;https://github.com/CartoDB/cartodb/issues/8818#issuecomment-232211244&gt;,  
>  &gt; or mute the thread  
>  &gt; &lt;https://github.com/notifications/unsubscribe
/AEmtLHLWsa6iwgkgEEo7vtrJG9MQBsoRks5qVCG-gaJpZM4JKzCE&gt;  
>  &gt; .  
>  &gt;  
>  
>  
>  
>  \--  
>  *Matt Forrest*  
>  Client Success Manager  
>  
>  *CARTO*  
>  201 Moore St, Brooklyn, NY, 11206  
>  P: (917) 463-3232 x7508  
>  C: (612) 325-8470  
>  carto.com &lt;http://www.carto.com/&gt;  
>

>

> —  
> You are receiving this because you commented.  
> Reply to this email directly, [view it on
GitHub](https://github.com/CartoDB/cartodb/issues/8818#issuecomment-232212389),
or [mute the thread](https://github.com/notifications/unsubscribe
/AAIENa4AWilUV-
vFS5-2Zm8rGn6ZrGMnks5qVCNqgaJpZM4JKzCE).![](https://github.com/notifications/beacon
/AAIENVmTieN8KX3MDZCtr-gMCCvtUWCbks5qVCNqgaJpZM4JKzCE.gif)

**Comment by mbforr** [comment]
https://team.carto.com/u/mforrest/builder/52fbecce-4852-11e6-baf9-0e8c56e2ffdb

On Tue, Jul 12, 2016 at 7:32 PM, Sergio Álvarez Leiva <
notifications@github.com> wrote:

> An we might need to access to the builder one
>
> On Jul 13 2016, at 1:29 am, Matt Forrest &lt;notifications@github.com&gt;
> wrote:
>
> > Just need a public link?
> >
> > On Tue, Jul 12, 2016 at 7:22 PM, Sergio Álvarez Leiva &lt;
> > notifications@github.com&gt; wrote:
> >
> > &gt; Looks like a cache issue. @mbforr &lt;https://github.com/mbforr&gt;
> can you
> > &gt; provide us access to the map so we can debug it? cc/ @rochoa
> > &gt; &lt;https://github.com/rochoa&gt; @javisantana
> &lt;https://github.com/javisantana&gt;
> > &gt;
> > &gt; —
> > &gt; You are receiving this because you were mentioned.
> > &gt; Reply to this email directly, view it on GitHub
> > &gt;
> &lt;
> https://github.com/CartoDB/cartodb/issues/8818#issuecomment-232211244&gt;,
>
> > &gt; or mute the thread
> > &gt; &lt;https://github.com/notifications/unsubscribe
> /AEmtLHLWsa6iwgkgEEo7vtrJG9MQBsoRks5qVCG-gaJpZM4JKzCE&gt;
> > &gt; .
> > &gt;
> >
> >
> >
> > \--
> > *Matt Forrest*
> > Client Success Manager
> >
> > *CARTO*
> > 201 Moore St, Brooklyn, NY, 11206
> > P: (917) 463-3232 x7508
> > C: (612) 325-8470
> > carto.com &lt;http://www.carto.com/&gt;
> >
>
> >
>
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, [view it on
> GitHub](
> https://github.com/CartoDB/cartodb/issues/8818#issuecomment-232212389),
> or [mute the thread](https://github.com/notifications/unsubscribe
> /AAIENa4AWilUV-
> vFS5-2Zm8rGn6ZrGMnks5qVCNqgaJpZM4JKzCE).![](
> https://github.com/notifications/beacon
> /AAIENVmTieN8KX3MDZCtr-gMCCvtUWCbks5qVCNqgaJpZM4JKzCE.gif)
>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/8818#issuecomment-232212723>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEmtLN2wHTsAdd1yaeO-KhGmp75qyQC8ks5qVCPxgaJpZM4JKzCE>
> .
>



-- 
*Matt Forrest*
Client Success Manager

*CARTO*
201 Moore St, Brooklyn, NY, 11206
P: (917) 463-3232 x7508
C: (612) 325-8470
carto.com <http://www.carto.com/>

**Comment by saleiva** [comment]
@rochoa this is similar to what happened before.

**Comment by rochoa** [comment]
The top layer is hidden in the builder, but we don't have support yet in the embed to hide layers. So you are seeing that layer when you visit the embed page.

I checked the named map and everything apart from the extra, supposedly hidden, the layer is the same as in the builder. The only option, until we have support for hiding layers, is to remove that top layer.

BTW: isn't a bit weird that you can place the labels layer between different data layers?

**Comment by xavijam** [comment]
It should be working now that we have the visibility feature ready and fully working 💃
