### ISSUE TITLE
Simple Default Styling: Point, Line, Polygon 

### ISSUE THREAD

**Issue by makella** [CartoDB/cartodb#8819]
@javisantana @saleiva 

Here is the basic point, line, and polygon styling. Once we can test across more datasets and scenarios, I have no problem adjusting.

### Points
```
#points {
   marker-width: 8;
   marker-fill: #FFB927;
   marker-fill-opacity: 0.9;
   marker-line-color: #ffda8d;
   marker-line-width: 1.5;
   marker-line-opacity: 1;
   marker-placement: point;
   marker-type: ellipse;
   marker-allow-overlap: true;
}
```

### Lines
```
#lines {
  line-color: #3EBCAE;
  line-width: 1.5;
  line-opacity: 1;
}
```

### Polygons 
**Note: there are some cartography specific cartocss properties for polygons please keep it**
```
#polygons {
   polygon-fill:#374c70;
   polygon-opacity: 0.9;
   polygon-gamma: 0.5;
   line-color: #fff;
   line-width: 1;
   line-opacity: 0.5;
   line-comp-op: soft-light;
}
```

### Example:
**with something of a worst case scenario**

![screen shot 2016-07-12 at 2 37 36 pm](https://cloud.githubusercontent.com/assets/1566273/16782782/627211ce-483e-11e6-9739-46e0417f6da6.png)

![screen shot 2016-07-12 at 2 38 34 pm](https://cloud.githubusercontent.com/assets/1566273/16782783/67cf6f90-483e-11e6-8549-402a4ae8a038.png)

**Comment by javisantana** [comment]
hey @makella, take a look at this https://github.com/CartoDB/cartodb/issues/7723

do you think we could do

```
#polygons {
   polygon-fill:#374c70;
   polygon-opacity: 0.9;
   polygon-gamma: 0.5;
::outline {
   line-color: #fff;
   line-width: 1;
   line-opacity: 0.5;
   line-comp-op: soft-light;
}
}
```

**Comment by javisantana** [comment]
another question:   `polygon-gamma: 0.5;` is something we want always or only for default styling?

In the other hand we can't control `line-comp-op: soft-light;` yet, is there any alternative in the meantime?

**Comment by makella** [comment]
@javisantana i'll try with the attachment as you describe above to see what the difference is visually (if anything). Thanks for sharing, I wasn't aware of that.

The combination of `line-comp-op: soft-light` and `polygon-gamma: 0.5;` make for noticeably better output cartography especially for choropleth maps.

Let me see if there is an alternative. There might be but it might not look as good. I think it is safe to say that we could set all default `polygon-gamma: 0.5` but I need to make sure that's right first.

Just to know, can you tell me why we can't use `soft-light`? Are there other limitations like that that I should be aware of?

To help you see what the combination does, check out the images below. We can kind of do a trick that allows the line color of a polygon to take a similar effect of the polygon fill versus a straight white outline. This makes the maps look so much better. In the past, I would choose a line color that was slightly lighter to achieve something similar. Then I figured this out and it is way less cartocss and really helps to get a smoother, more polished look for your maps.

No gamma or comp-op:

![screen shot 2016-07-13 at 8 05 25 am](https://cloud.githubusercontent.com/assets/1566273/16806171/aa742556-48d0-11e6-87d1-fb000d6858de.png)


With gamma and comp-op:

![screen shot 2016-07-13 at 8 00 27 am](https://cloud.githubusercontent.com/assets/1566273/16806053/21bca12a-48d0-11e6-8437-4feaff596d96.png)

**Comment by javisantana** [comment]
> Just to know, can you tell me why we can't use soft-light? Are there other limitations like that that I should be aware of?

we didn't implement mixed comp-op operations for geometries so for polygons it needs to be polygon-comp-op

We also does not support that in the forms so even if we use it the user couldn't change it using forms

**Comment by saleiva** [comment]
We could add the polygon-comp-op to the form, but I'm not sure it's worth...
@makella?

On Jul 13 2016, at 4:17 pm, javi santana &lt;notifications@github.com&gt;
wrote:  

> > Just to know, can you tell me why we can't use soft-light? Are there other
limitations like that that I should be aware of?

>

> we didn't implement mixed comp-op operations for geometries so for polygons
it needs to be polygon-comp-op

>

> We also does not support that in the forms so even if we use it the user
couldn't change it using forms

>

> —  
> You are receiving this because you were mentioned.  
> Reply to this email directly, [view it on
GitHub](https://github.com/CartoDB/cartodb/issues/8819#issuecomment-232368986),
or [mute the
thread](https://github.com/notifications/unsubscribe/AAIENR5F8GN1tklPslxmDdnqrtksYJpqks5qVPN_gaJpZM4JKzfe).![](https://github.com/notifications/beacon
/AAIENQZJVsl_7_7fVmFOG2NEs-yZ78mhks5qVPN_gaJpZM4JKzfe.gif)

**Comment by makella** [comment]
In this case, it's the `line-comp-op` that is helping.... so if we could add that as an option, that would be great.

But let me find a workaround if I can.

The `polygon-gamma` is not a comp-op so we can use that by default, right?

Let me spend some time finding a happy medium. But you guys see the noticeable difference in the two maps above, right?

**Comment by javisantana** [comment]
to be clear we cab NOT  use `polygon-gamma` or `line-comp-op` when styling polygons

Why don't work with what we have and then iterate ?

**Comment by makella** [comment]
ok. well, i'll try.

i'll get back to you here when i find something. sorry, i didn't know that until this morning.

**Comment by makella** [comment]
@javisantana here

```
#polygons {
   polygon-fill:#374c70;
   polygon-opacity: 0.9;
 ::outline{
   line-color: #4d6b9e;
   line-width: 1;
   line-opacity: 0.5;
  }
}
```

**Comment by javisantana** [comment]
so what would be the final styles?

**Comment by makella** [comment]
what you have in there is ok for now.

After testing these past few days, I need to change the styling for the point symbols. But for right now, if you want to move on to other things, we can go with this as is. Really, I just need more people to start playing with the defaults and use them myself before I can make better recommendations.

thanks!

**Comment by makella** [comment]
Oh, and if we could assign the category defaults as defined above, that would be great. I changed the ramp for polygons from prism to vivid because it is working better (I think).

**Comment by javisantana** [comment]
if we need to change colors, let's open a different ticket
