### ISSUE TITLE
Wrong typhography on organization account deletion

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#8822]
![screen shot 2016-07-13 at 09 41 55](https://cloud.githubusercontent.com/assets/932968/16795537/1cac89bc-48de-11e6-9fe2-fde9acac5c4f.png)

cc @xavijam

**Comment by xavijam** [comment]
Already spotted, I feel it is duplicated.

**Comment by MariaCheca** [comment]
Yep, it was reported here https://github.com/CartoDB/cartodb/issues/8666 and is already solved here https://github.com/CartoDB/cartodb/pull/8685

Thank you anyway @juanignaciosl :)
