### ISSUE TITLE
Improve form error messages

### ISSUE THREAD

**Issue by MariaCheca** [CartoDB/cartodb#8835]
Current error messages aren't descriptive and users may be confused.

![screen shot 2016-07-13 at 15 02 48](https://cloud.githubusercontent.com/assets/2141690/16804261/2f4c2d52-490b-11e6-9226-3f13596093b5.png)

**Comment by saleiva** [comment]
Also note that the bar style and the border style are wrong.

**Comment by MariaCheca** [comment]
IE magic ✨  Will try to fix that too
