### ISSUE TITLE
How to use builder Carto ? 

### ISSUE THREAD

**Issue by alerteratp** [CartoDB/cartodb#8837]
Hello,

I was wondering how to use builder mode in Carto.
I already pull the last version on origin master.

Sorry for my newbie question.. 

Thank you.

**Comment by javitonino** [comment]
You need to enable the `editor-3` feature flag.

`bundle exec rake cartodb:features:add_feature_flag[editor-3,false]`

This should let you see the builder, but you won't have access to much of the functionality, as further dependencies (postgresql 9.5, some of our extension, updated version of the tiler, etc) are needed to run analyses and more advanced functionality. We don't have documentation on these for now, so you will have to investigate a bit to get everything running.
