### ISSUE TITLE
Zoom behavior on Histogram is backwards... showing fewer categories 

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#8838]
![screen shot 2016-07-13 at 10 34 28 am](https://cloud.githubusercontent.com/assets/370259/16807185/7698c36c-48e5-11e6-9249-93a4b9714e99.png)

If you look at the above, there were actually more bins in the first view of the data. On applying the zoom, it dropped down to only 6, making my data even less interactable

**Comment by saleiva** [comment]
That goes to deep-insights.js repo!

**Comment by andrewxhill** [comment]
do'h realized right after submit

https://github.com/CartoDB/deep-insights.js/issues/420
