### ISSUE TITLE
Add option for switching data-source of a layer

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8839]
@urbanphes can you attach an screenshot of where that option is so we can use it as a reference?

About how it should work.
- If the schema is the same, it should work with no errors.
- If the schema is different but the columns used on the analysis / Styling / widgets are present on the new data-source, it should work with no errors.
- If the schema is different and there are 1..n columns used in Analysis / Styling / widgets, we should warn on the UI and delete those affected steps.

cc/ @javisantana @rochoa @xavijam

**Comment by urbanphes** [comment]
Here te visual designs
<br>
**From**
<br>
![01 layers - 02-20 style](https://cloud.githubusercontent.com/assets/14546701/16810109/099fd0aa-4923-11e6-98b6-06de64968cee.png)
<br><br>
**To**<br>
![531 mod change dataset](https://cloud.githubusercontent.com/assets/14546701/16810121/152a3c94-4923-11e6-8ac2-32b73cb469e4.png)
