### ISSUE TITLE
After changing the time-series widget name, buckets are set 

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#8840]
### STEPS

1-Create a map from the railroad accidents dataset (@cartodave's demo), you can download the csv file from this url: https://ramirocartodb.cartodb.com:443/api/v2/sql?q=select%20*%20from%20ramirocartodb.dot_rail_safety_data&format=csv

2-After changing style and adding a couple of widgets, add a time-series widget using the "date" column.

![1](https://cloud.githubusercontent.com/assets/5215798/16807355/58387772-4918-11e6-826f-97e893a2e550.png)

3-And after renaming time-series widget, the title is not shown above the widget (I suppose this is expected) but the thing is that it shows this bucket related error:

![2](https://cloud.githubusercontent.com/assets/5215798/16807430/a5473788-4918-11e6-8e0b-93119e331e6d.png)

4-Then, varying the buckets modify in a very ugly way the time-series widget:

![3](https://cloud.githubusercontent.com/assets/5215798/16807486/ea941360-4918-11e6-9f6c-8cf20650b71f.png)

@AbelVM points to me that maybe the time-series widget is replicating the histogram widget behaviour.

**Comment by xavijam** [comment]
Not happening anymore, @CartoDB/frontend guys rocks :kiss:.
