### ISSUE TITLE
some characters are being removed from column names

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8843]
such as "%". If we need to sanitize those, I'd create a dictionary for the most common ones, so % -> percentage, & -> and, etc...

**Comment by ethervoid** [comment]
Where are we removing that characters?

**Comment by saleiva** [comment]
Dunno, they don't appear on column headers

On Jul 13 2016, at 5:09 pm, Mario de Frutos &lt;notifications@github.com&gt;
wrote:  

> Where are we removing that characters?

>

> —  
> You are receiving this because you authored the thread.  
> Reply to this email directly, [view it on
GitHub](https://github.com/CartoDB/cartodb/issues/8843#issuecomment-232385928),
or [mute the thread](https://github.com/notifications/unsubscribe
/AAIENR3uHoFjggno_JzhvRzZ0vGk8Ghiks5qVP-
_gaJpZM4JLhMR).![](https://github.com/notifications/beacon
/AAIENe85YR5aAq2tpQk9aPSEPBTar7LUks5qVP-_gaJpZM4JLhMR.gif)

**Comment by ethervoid** [comment]
Ok thanks for the clarification :)

**Comment by iriberri** [comment]
Wouldn't this be a dangerous fix/improvement? I think we could break some maps (queries and infowindows) that are relying on sanitized column names if we change the way that we sanitize them.
