### ISSUE TITLE
Implement flatten layer functionality

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8844]
Flatten layer would get the final result of the analysis workflow and create a dataset with that (which will be plugged as data source to the layer). This would have to cartodby the dataset so it appears on the user's datasets list.

@urbanphes can you attach an image of the UI for reference?

This is very important since some analysis need to be persisted very often, such as georeference.
# SMOKE_AN14

**Comment by urbanphes** [comment]
Here the visual designs
<br><br>
**From**
<br>
![01 layers - 00-02](https://cloud.githubusercontent.com/assets/14546701/16813104/71dc2120-4930-11e6-95a4-2734fa1768c2.png)
<br>

**To**
<br>
![611 mod confirmation flatten](https://cloud.githubusercontent.com/assets/14546701/16813122/8348111c-4930-11e6-8694-a5db107ad5df.png)

**Comment by saleiva** [comment]
@urbanphes just thinking on a tweak for this. Flattering a layer means merging all analysis steps into a single dataset. When doing so, sometimes you want to create a copy of the data, but sometimes you would just like to override the actual dataset with the processed one (like in most ETL workflows). What about adding that option to the modal?

**Comment by urbanphes** [comment]
We can give this possibility before flattening the layer, here you can the visual:

![57 - flaten layer](https://cloud.githubusercontent.com/assets/14546701/20170971/e20b22fa-a72e-11e6-9d87-ffca8f530c62.png)

**Comment by saleiva** [comment]
uhm... that seems wrong. .CARTO doesn´t make sense here. I was expecting two options.

**Comment by saleiva** [comment]
@javierarce you know what I mean?

**Comment by javierarce** [comment]
I imagine that we want to have two options:

* Flatten and replace layer
* Flatten into a new layer

Using the screenshot as an example, in the first case we'll have layers A and B (except B will be the result of the flatten operation), while in the second case we'll have layers A, B and C (with C being the result of the operation).

**Comment by saleiva** [comment]
yep
exactly

**Comment by urbanphes** [comment]
Hey, the visual the screen modal. The user have two options to choose as a radio buttons. In this way we have only one button for main action.

![57 - flaten layer](https://cloud.githubusercontent.com/assets/14546701/20184535/439a8652-a769-11e6-91e0-6e2dc9984c9d.png)

**Comment by saleiva** [comment]
Like the solution, but remember the difference between layers (representación of dataset on maps) and datasets.

**Comment by urbanphes** [comment]
Modify the copy. 

![57 - flaten layer](https://cloud.githubusercontent.com/assets/14546701/20208842/12c0a290-a7f1-11e6-8f13-35923d5f75e1.png)

**Comment by saleiva** [comment]
You did the opposite way.
When you flatten a layer this is what happens behind the scenes:

A. Replace dataset
The original dataset gets overrided with the result of all the analysis worklfow. The analysis nodes dissapear and the layer is just the datasource.

A. Create new dataset
The original dataset keeps intact. The result of the analysis workflow gets materialized as a new dataset. The analysis nodes dissapear and the layer is just the NEW datasource.

**Comment by urbanphes** [comment]
Here the visual taking into account the feedback. Using the tooltip component (as a analysis configuration) we can give some of the explanation about each method.

### Modal
![57 - flaten layer](https://cloud.githubusercontent.com/assets/14546701/20212801/773bd05a-a805-11e6-8c46-476888cc6a36.png)


### Modal + tooltip
![58 - flaten layer](https://cloud.githubusercontent.com/assets/14546701/20212802/7d34296c-a805-11e6-9d2b-8db8c90dc0f1.png)

**Comment by saleiva** [comment]
Like it!

**Comment by xavijam** [comment]
Hey @javierarce, do you mind if we pass this issue to @MariaCheca in order to unblock you with "style by icon" thing? 💋

**Comment by javierarce** [comment]
Yeah, no problem 👍

**Comment by xavijam** [comment]
Moved to Salardú, because the previous one @MariaCheca should support Style-with-icons feature with @gfiorav and @javierarce.

**Comment by noguerol** [comment]
Pushing again this one

**Comment by alrocar** [comment]
Stale issue. Closing 👋
