### ISSUE TITLE
Add the option to choose number of buckets for points > sized by value

### ISSUE THREAD

**Issue by makella** [CartoDB/cartodb#8852]
We need to have the option to select the number of classes (in addition to classification method) for points that are sized by value. We are doing classed proportional symbols wrong if we don't offer this option.  Once a user selects a classification method and number of classes, the min/max symbol sizes should ramp by those two variables. For example, if they choose 7 classes, we would get 7 different symbol sizes.

@javisantana noted this down, just want to create an issue too. Basically, in the dialogue below, we also need the drop-down for number of buckets.

![screen shot 2016-07-13 at 12 55 49 pm](https://cloud.githubusercontent.com/assets/1566273/16816094/d4af8cec-48f9-11e6-9ab8-1e1f21bd9fa6.png)

**Comment by saleiva** [comment]
cc/ @urbanphes

**Comment by xavijam** [comment]
Moved in design, closing for the moment. Design team will open a new one when they finish, so closing 💋 .
