### ISSUE TITLE
Point Default: Style By Value > Size

### ISSUE THREAD

**Issue by makella** [CartoDB/cartodb#8856]
@javisantana @saleiva 
#### Sized by Value
- Default Classification: quantiles
- Default Classes: 5
- Default Min Symbol Size: 5
  - **note on minimum size**: https://github.com/CartoDB/cartodb/issues/8853
- Default Styling:

```
#layer {
  marker-width: ramp([customer_value], 5.xxxx, X.xxx, quantiles);
  marker-fill:#A37EF2;
  marker-fill-opacity: 0.9;
  marker-line-width: 0.5;
  marker-line-color: #333;
  marker-line-opacity: 1;
  marker-allow-overlap: true;
}
```
- Examples:

![screen shot 2016-07-13 at 4 08 04 pm](https://cloud.githubusercontent.com/assets/1566273/16821546/1cbcf3c0-4914-11e6-96e1-dfe38ac6050a.png)
![screen shot 2016-07-13 at 4 08 27 pm](https://cloud.githubusercontent.com/assets/1566273/16821560/24f27eb6-4914-11e6-8c93-6ffe1f625b52.png)

**Comment by javisantana** [comment]
the question here, when we style by value we can't change the color at the same time. If the user picked a value for color and stroke we have to keep them. It's fine to change size.

So, it's that fine?

**Comment by makella** [comment]
Ok. So in this scenario, the default color and stroke of sized by value symbols would be the same as the default color and stroke for simple points, correct?
