### ISSUE TITLE
Point Default: Style by Value > Color > Categories // Quantities

### ISSUE THREAD

**Issue by makella** [CartoDB/cartodb#8857]
@javisantana @saleiva 
#### Categories
- Default Ramp: `Vivid`
- Default Styling:

```
#layer {
  marker-width: 8;
  marker-fill: ramp([cluster_no], (#E58606, #5D69B1, #52BCA3, #99C945, #2F8AC4, #24796C, #cc2d7f, #764e9f, #ed645a), ("0", "1", "2", "3", "4", "5", "6", "7", "8"), category); 
  marker-fill:#A37EF2;
  marker-fill-opacity: 0.9;
  marker-line-width: 0.5;
  marker-line-color: #333;
  marker-line-opacity: 1;
  marker-allow-overlap: true;
}
```
#### Quantities
- Default Classification: quantiles
- Default Classes: 5
- Default Ramp: `PurpOr`
- Default Styling:

```
#layer {
  marker-width: 8;
  marker-fill: ramp([customer_value], (#573b88, #9955a8, #ce78b3, #eda8bd, #f9ddda), quantiles);
  marker-line-color: #333;
  marker-line-width: 0.5;
  marker-line-opacity: 1;
  marker-allow-overlap: true;
}
```
- Examples:
  **Categories**
  ![screen shot 2016-07-13 at 4 34 38 pm](https://cloud.githubusercontent.com/assets/1566273/16822151/d22798a2-4917-11e6-9b89-b5e0f2c4b030.png)

![screen shot 2016-07-13 at 4 34 52 pm](https://cloud.githubusercontent.com/assets/1566273/16822155/d7635450-4917-11e6-88a4-84cabb23d4ec.png)

**Quantities**
![screen shot 2016-07-13 at 4 25 34 pm](https://cloud.githubusercontent.com/assets/1566273/16822060/419ae9c4-4917-11e6-9153-be59a52bba6f.png)

![screen shot 2016-07-13 at 4 25 00 pm](https://cloud.githubusercontent.com/assets/1566273/16822064/475ba704-4917-11e6-82ef-5fcf0853dc27.png)

**Comment by makella** [comment]
@gfiorav

**Comment by makella** [comment]
during the icon demo in today's product meeting @saleiva showed the importance of having more differentiation between colors when you are displaying two categories on a map with the added complexity of a choropleth map underneath.

the default for style by value > category that I defined above uses `cartocolor(Vivid)` which has more contrast than `Prism`. `Prism` was a really quick decision a long time ago. A scheme like `Vivid` would be better suited when showing something like two categories.

What would also be really great is if there were the option to choose another category palette when symbolizing qualitative data. Right now, 'Prism' is the only one users can see/access when symbolizing by category.

**Comment by saleiva** [comment]
Absolutely

**Comment by ramiroaznar** [comment]
@makella can we close this one?

**Comment by makella** [comment]
yep!
