### ISSUE TITLE
Separate intersection in two separate analysis

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#8867]
Because depending on params it will output different kind of geometries, by separating them we'll make sure that a created analysis always returns the same kind of analysis.

Once done there should be two analysis types:
- Update option `Intersection`
  - Update desc: _"Aggregate data in a second layer as a new column."_
  - Remove measure type radio buttons
- Add option `Filter points in polygon`
  - Update desc: _Filter rows based intersection or _
  - Add form model, same as intersection but w/o any filter section (filter param should be fixed)

Considering there will be no way to change between the two once one i created, I think it's best to have separate form models and let them develop separately. Shared UI things could/should be extracted and made reusable.

**Comment by viddo** [comment]
Reassigned as agreed from offline discussion. 🙇

**Comment by xavijam** [comment]
Har!, I miss the description for the "Filter points in polygon", it appears uncompleted. Do you remember it @saleiva?

**Comment by saleiva** [comment]
Filter points intersecting your polygon layer, and augment those with your polygons columns

**Comment by saleiva** [comment]
@stuartlynn, we might need a better text ;)
