### ISSUE TITLE
Fix modals text

### ISSUE THREAD

**Issue by MariaCheca** [CartoDB/cartodb#8869]
In some modals the `CDB-Text` is missing.

**Comment by piensaenpixel** [comment]
@MariaCheca please a bit more information? :)

**Comment by xavijam** [comment]
@MariaCheca ^^^ :)

**Comment by MariaCheca** [comment]
After our recent rebranding, we've used `CDB-Text` selector in most of the modules to apply the new typography properties to the elements. Some of them, mainly modals which are more _hidden_ don't have that selector so they're displayed with an annoying Times New Roman, so we have to review all of them to make sure they're all updated and fix those that aren't.

**Comment by xavijam** [comment]
Yeah, agree, but we don't have any of those located right? We are planning to review all modals, something I feel you will involved, so closing this one and working in the new one, ok?
