### ISSUE TITLE
Map card text doesn't have line spacing

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#8877]
In the dashboard of the user, when there is no enough maps for a complete line.

![screen shot 2016-07-14 at 16 27 35](https://cloud.githubusercontent.com/assets/132146/16843059/070d8752-49e0-11e6-82b7-d0fc31fa795f.png)

**Comment by piensaenpixel** [comment]
uhm is the right size and line-height 12/16 :(
