### ISSUE TITLE
Basemaps picker window is not showing

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#8879]
OS: mac OS El Capitán 10.11.5
Browser: Version 51.0.2704.106 (64-bit)
CARTO Account used when this happened: maps-for-all

## Issue

When I try to access the Basemaps layer, the correct Basemaps screen doesn't load and I get a blank/white screen instead with nothing on it. Here, a recording of the issue:  

![bug](https://cloud.githubusercontent.com/assets/16247628/16848851/0c942812-49f8-11e6-87c8-eb918eab3930.gif)

## Steps taken when it happened 

1. I logged in into the maps-for-all account
2. I duplicated the "Stores prediction map"
3. Once in the builder on the duplicated version I first zoomed in one level and moved the map around a bit. 
4. Then I clicked on the Basemap layer (not on the image of the basemap) several times and nothing happened. 
5. Then I clicked on the image of the Basemap layer and the whole column/sidebar went blank, as shown here (it also happens when I click on the title of the basemap layer):

<img width="1658" alt="screen shot 2016-07-14 at 19 06 16" src="https://cloud.githubusercontent.com/assets/16247628/16848421/1066615a-49f6-11e6-8f93-e3e9cc9e4af7.png">

The only way I could go back to the layer screen was clicking first on the Map Options button on the blue bar and then on the pencil icon.

## Expected behaviour 

When I click anywhere on the basemap layer (not only image or title), the screen with the basemaps selector should appear.     

## Console errors

When I look at the console, this error appears:
**tracker.js:4 Uncaught Error: TrackJS Caught: selectedCategoryVal is required**

## Reproduction 

On this map I can reproduce it always. I can also reproduce it on every map on that account. But when I created a new map on the account, it worked fine, the basemap screen loaded.

On my personal account within the Team organisation, I could only reproduce it in one out of six maps. In this one: https://team.carto.com/u/arianaescobar/builder/e4c86eb2-a4d2-11e5-8c95-0ea31932ec1d/embed I created a new map on this account, and it worked perfectly as expected, the basemaps screen loaded fine. 

I would like to try to reproduce it on my other personal account, outside the Team organisation, but I don't have the builder activated on that one.

If there's any other information or context I can give to help reproduce the issue, just let me know, I'll be happy to :)

**Comment by matallo** [comment]
on it, thanks for the thorough report!
