### ISSUE TITLE
Ramp picker not showing because of palettes lacking tags

### ISSUE THREAD

**Issue by fdansv** [CartoDB/cartodb#8880]
When creating a choropleth map, if you try and re-set the color ramp according to the value, the color picker won't reopen, and the console throws the following:

```
Uncaught TypeError: Cannot read property '0' of undefined - input-ramp-list-view.js:67
```

It seems that some of the color palettes that were recently added are being loaded without a `tags` property.

@javisantana @makella

**Comment by makella** [comment]
I noticed the same thing this morning. I will double check that every ramp has a tag.

**Comment by saleiva** [comment]
Please, this is important for the builder.

**Comment by makella** [comment]
I checked and the latest carto colors has tags for every palette. The only thing I see (maybe) is that we are missing the tag `aggregation`?
https://github.com/CartoDB/cartodb/blob/aedde3736188f33494916cf8e47a8697623a9bc2/lib/assets/javascripts/cartodb3/components/form-components/editors/fill/input-color/input-ramps/input-ramp-list-view.js#L60-L62

There are two `aggregation` palettes for hexbins, squares, and heat map.

https://github.com/CartoDB/CartoColor/blob/master/cartocolor.js#L174-L181
https://github.com/CartoDB/CartoColor/blob/master/cartocolor.js#L94-L101
