### ISSUE TITLE
Add Connect with lines Analysis

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8884]

**Comment by javierarce** [comment]
These are the analyses that are part of the 'Connect with lines' analysis: 

* routing-to-single-point
* routing-to-layer-all-to-all
* routing-sequential

After having a look to the designs, I find they are lacking some of available features that appear on the reference.

For example, this is the design for the `routing-sequential` analysis:

![screen shot 2016-08-08 at 14 15 52](https://cloud.githubusercontent.com/assets/4933/17480086/77526cb8-5d76-11e6-9271-3e273babb89d.png)

It only allows to specify `order column` but the reference allows doing much more:

```
 "routing-sequential": {
        …
                "column_target": {
                    "type": "string"
                },
                "units": {
                    "type": "enum",
                    "values": [
                        "kilometers",
                        "miles"
                    ],
                    "optional": true,
                    "default-value": "kilometers"
                },
                "order_column": {
                    "type": "string",
                    "optional": true,
                    "default-value": "cartodb_id"
                },
                "order_type": {
                    "type": "enum",
                    "values": [
                        "asc",
                        "desc"
                    ],
                    "optional": true,
                    "default-value": "asc"
                }
            }
        }
```

I'll implement the missing fields that don't appear in the design and upload some screenshots so you can all review them.

**Comment by saleiva** [comment]
Hey @javierarce that shouldn't be the design for the all to all.

**Comment by javierarce** [comment]
That's what the invision doc has right now. Maybe is not updated?

**Comment by javierarce** [comment]
Oh, no, sorry, maybe is this one, right? 

![screen shot 2016-08-08 at 15 29 48](https://cloud.githubusercontent.com/assets/4933/17481318/d603afa0-5d7c-11e6-93d9-715708ec36a0.png)

**Comment by javierarce** [comment]
But then the 'To closest' radio is a reference to the "closest" element in the reference for `routing-to-layer-all-to-all`?

**Comment by javierarce** [comment]
![screen shot 2016-08-08 at 17 05 39](https://cloud.githubusercontent.com/assets/4933/17484457/37b53b58-5d8a-11e6-83cc-724de05e5326.png)

@saleiva: we don't have this component. Should I replace it with two fields in the meantime or do you prefer to design something for it?

**Comment by saleiva** [comment]
That example implies having the geometry editable from the map, which I'm afraid that will not be ready yet. I'd create a ticket for that particular scenario and try to tackle for whenever we work on geometry edition. sounds that good?

**Comment by javierarce** [comment]
Sorry, I didn't explain myself well :/ I was referring to the lat/long field.

**Comment by javierarce** [comment]
@dgaubert: in the `routing-to-layer-all-to-all` analysis we have a ['closest' boolean param](https://github.com/CartoDB/camshaft/blob/master/reference/versions/0.38.0/reference.json#L670). Then, in the UI, we have a radio button with to values: "to closest" and "all to all"… do they correspond to true and false respectively?

![screen shot 2016-08-09 at 10 03 34](https://cloud.githubusercontent.com/assets/4933/17509087/8819a316-5e18-11e6-9f2f-cb4588af7a47.png)

**Comment by dgaubert** [comment]
Basically `closest` option is the top one order by duration of the result of `all to all` analysis. So, yes, I'd say they correspond to `true` and `false` (or undefined) respectively.

HTH.

**Comment by javierarce** [comment]
Another question regarding the analysis.

The analysis `routing-to-layer-all-to-all` (which is called `To Layer` in the UI) shows a `Group by` checkbox plus a way to select an input column and a target column (see image below) whereas in the [reference](https://github.com/CartoDB/camshaft/blob/master/reference/versions/0.38.0/reference.json#L632) we have `target`, `source_column` and `target_column` (which correspond, I think, to "Target Layer", "Input Col" and "Target col" in the design, respectively). 

![screen shot 2016-08-09 at 12 04 42](https://cloud.githubusercontent.com/assets/4933/17512713/7e098b0a-5e29-11e6-98bc-fb778049ced9.png)

My question for you, @saleiva, is… does the "group by" checkbox makes sense?

**Comment by saleiva** [comment]
yep it does. Imagine you wanna relate clients to the closest store, and clients have a column called store_id, and stores a column called id.

BOOM

**Comment by javierarce** [comment]
Ok, so the analysis will need to support that ☝️ … can you take charge of that, , @dgaubert?

**Comment by javierarce** [comment]
There's also a disagreement with what's "mode". In the design "mode" refers to the three kinds of analyses "connect with lines" is composed of (`routing-to-single-point`, `routing-to-layer-all-to-all`, and `routing-sequential`), while in the reference mode is an enum param with four possible values ("car", "walk", "bicycle", and "public_transport"). I'll follow the reference and use mode as it's specified there and add a "type" combo to change between analyses.

**Comment by saleiva** [comment]
ok, but on the connect with lines analysis, mode shouldn't be present as
they are straight lines :)

**Comment by javierarce** [comment]
I'm getting very lost. The `mode` param appears in the reference for the three analyses and is required in all those cases. 

https://github.com/CartoDB/camshaft/blob/master/reference/versions/0.38.0/reference.json#L683 https://github.com/CartoDB/camshaft/blob/master/reference/versions/0.38.0/reference.json#L652 https://github.com/CartoDB/camshaft/blob/master/reference/versions/0.38.0/reference.json#L595

cc: @andrewxhill @dgaubert

**Comment by dgaubert** [comment]
> ok, but on the connect with lines analysis, mode shouldn't be present as
they are straight lines :)

I will change everything is needed, but isn't a bit weird to have a `routing` analysis that renders simple lines? So, there is no need to use our routing provider, right?

**Comment by dgaubert** [comment]
> Ok, so the analysis will need to support that ☝️ … can you take charge of that, , @dgaubert?

it's already supported. The join between those tables will be done using `input_col` (`source_column` in camshaft) and `target_col` (`target_column` in camshaft).

**Comment by javierarce** [comment]
Yes, but I meant the "group by" option.

**Comment by dgaubert** [comment]
I think that `group by` in UI doesn't mean the same thing as in SQL. Does it?

**Comment by javierarce** [comment]
I'm adding here the PR for this analysis for reference: 

- [ ] [WIP: Implemented analysis line_this-layer-column](https://github.com/CartoDB/camshaft/pull/170)
- [ ] [Implemented analysis line-sequential](https://github.com/CartoDB/camshaft/pull/168)
- [ ] [Implemented analysis line-to-layer-all-to-all](https://github.com/CartoDB/camshaft/pull/167)
- [ ] [Implemented line-to-single-point analysis](https://github.com/CartoDB/camshaft/pull/166)

**Comment by dgaubert** [comment]
Cool! Analysis `line-this-layer-column` is ready to CR (no longer WIP).

**Comment by javierarce** [comment]
@saleiva, @urbanphes: whenever a user wants to use the `line-to-column` analysis and doesn't have a second geometry in the dataset, it won't be able to apply the analysis. What should we do in that case? Do we have an error message we could show in the form? 

Another option I think we could do is not show the `line-to-column` option in the select view.

**Comment by saleiva** [comment]
Show an error on the field, with the error saying that there is not any
other the_geom type column on their data

**Comment by javierarce** [comment]
Thanks. And sorry, it was a dumb question.

**Comment by xavijam** [comment]
Hey, is it already done?

**Comment by dgaubert** [comment]
I'd say YES:

https://team.carto.com/u/dgaubert/builder/fc087c42-6c1d-461f-bf45-1780d8a3facf/embed

\o/
