### ISSUE TITLE
Implement builder onboarding

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#8887]

**Comment by javierarce** [comment]
First approach (without animation) & using the keyboard to move between the steps:

![onboarding](https://cloud.githubusercontent.com/assets/4933/17210824/8e2fd10a-54c5-11e6-8c8f-391b4143f8f9.gif)

**Comment by javierarce** [comment]
We need to write 4 texts to explain the UI elements of each step. Here's one idea. Please, feel free to improve it:

1. **Toolbar**: Access to your dashboard, editing options, and configuration of your map.
2. **Configurator**: From here you can manage layers, analyses, and widgets.
3. **Map**: Your map will reflect your changes instantly [not very fond of this line]
4. **Widgets bar**: Your map's widgets will appear here.

I don't like the name "Configurator" of the second screen that appeared in the design. Maybe "Editing pane" or "Map pane" would be better?
And instead of "Widgets bar" I rather say "Widgets pane".

cc: @andrewxhill, @urbanphes, @saleiva.

**Comment by saleiva** [comment]
Javier, texts are placeholders. Feel free to do you magic

**Comment by javierarce** [comment]
Sneak peek of the animation (sorry for the crappy gif):
![onboarding](https://cloud.githubusercontent.com/assets/4933/17295627/625b2d46-57fd-11e6-8d2c-d427c9376543.gif)

**Comment by saleiva** [comment]
Ooooooooooooh

**Comment by javierarce** [comment]
@csobier: could you please proofread these texts: https://github.com/CartoDB/cartodb/issues/8887#issuecomment-236520512?

**Comment by csobier** [comment]
Sure, here are some minor edits, reworded using active voice, fixed some spelling, etc. Removed "left" or "right" as the animation shows that (for Widgets, time-series can appear on the bottom too):

1. Welcome to the Builder, XXX! Let us show you all the new and exciting things that you can do with CARTO
2. **Toolbar**: The toolbar provides options to access to your dashboard, edit your map, and configure its settings
3.  **Editing**: Manage all the components of your map: add layers and widgets, import datasets, customize analyses, and change styles
4. **Map**: Your map reflects changes instantly
5. **Widgets**: Add interactive widgets to your visualization

**Comment by javierarce** [comment]
Thanks ❤️ !

**Comment by javierarce** [comment]
@csobier: oh, wait, the text for the widgets should be similar to the one I provided, because the intent of the UI is to show the list of widgets.

![screen shot 2016-08-02 at 17 17 28](https://cloud.githubusercontent.com/assets/4933/17334012/f89a705a-58d4-11e6-9d81-a5dcf41390e8.png)

**Comment by csobier** [comment]
Okay, how about:

5. **Widgets**: The widgets you add to your map appear directly on your visualization.

**Comment by javierarce** [comment]
👍  perfect, thanks!
