### ISSUE TITLE
The widgets lost the order and there is no way to sort them out

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb#8892]
Sample: https://team.carto.com/u/abel/builder/44999f04-49ca-11e6-89ee-0e233c30368f/embed?

Once the order is lost, you can't get the order back and the consequent changes are not reflected in the embed. There is no matter if you reorder and publish several times, the embed is frozen in an unordered state.

cc @saleiva

**Comment by AbelVM** [comment]
Looks like the builder doesn't detect the changes when you move a widget, so there's nothing new to publish.

When adding or deleting a new widget, it works, but the order ot the other widgets remain the same.

**Comment by nobuti** [comment]
@AbelVM could you indicate some steps to reproduce it?

**Comment by AbelVM** [comment]
I'd love to, but looks like it's a bit random :(

**Comment by ernesmb** [comment]
I have found a similar case, some details: 

- The viz.json is correctly updated according to the given widgets order. 
- The order in which widgets are referenced in the `viz.json` is different than the order set in `order` property. It usually writes down the widgets following the sequence: `0,1,5,6,3,4`.
`order` property in widget definition is correct, but not the order in which the widgets are listed in the `viz.json`
- The embed version does not respect the viz.json order. It rather uses a 'random' order 

more info: https://github.com/CartoDB/cartodb-management/issues/4529

**Comment by AbelVM** [comment]
I have redone my map from scratch, 

https://team.carto.com/u/abel/builder/81335b53-10a6-466e-8c8c-5625ea4df4f8/embed

Same issue. The order is ok in the builder but not in the embed

Steps to reproduce:
* I have 2 layers
* If I add several widgets for one layer, everything is ok
* The moment I add a widget for the 2nd layer, the order is lost and there's no way to get it back.

I've also tried to export .carto, and then import it: same behaviour

**Comment by AbelVM** [comment]
Más majos que las pesetas, coño

**Comment by ernesmb** [comment]
This is reproducing again :( 

The `.carto` file below will help to reproduce it: 

- Import the .carto file
- Open an embed
- Change the widget order & update the map through the sharing options
- Refresh the embed map page ==> the widgets do not re-order

[DEMO 22_09_2016 (on 2016-09-22 at 09.24.33).carto.zip](https://github.com/CartoDB/cartodb/files/486984/DEMO.22_09_2016.on.2016-09-22.at.09.24.33.carto.zip)

**Comment by javitonino** [comment]
Ok, this is the thing: we export the widgets per layer (`layer: { widgets: [] }`) with no order field (we use the position in the array). So we cannot recreate the global widget order.

We need to either add the order field to the exports, or to extract the widget to top level so ordering is global. The second idea seems more complicated as we would need to somehow reference the layer anyway (widgets are part of a layer but have an independent global ordering). I don't like adding the order as a number too much (better to rely on array ordering) but I cannot think of a better way to do it as we need the reference to layer too.

cc @CartoDB/builder-backend

**Comment by juanignaciosl** [comment]
As this is a "implicit id" (nesting) vs "implicit order" (top level) tradeoff, I'd keep nesting and add a order field for widget export (your first idea).

Sorry about having overlooked this 😓

**Comment by ernesmb** [comment]
💪
