### ISSUE TITLE
[pop-ups] When creating a pop up over a polygon layer and adding Hover actions it changes the interface to grey color

### ISSUE THREAD

**Issue by miguelarias** [CartoDB/cartodb#8893]
And it doesnt let you define the parameters or anything else. It works again if you click on the Click tab, but not on hover. See screenshot.
![screenshot 2016-07-14 15 50 44](https://cloud.githubusercontent.com/assets/7315954/16853557/d87b2b92-49da-11e6-94f1-5c9d663b019c.png)

**Comment by saleiva** [comment]
This doesn't happen always. Hard to replicate, but assigning to @matallo .
@miguelarias can you confirm that you didn't had custom hover infowindows on the original dataset?

**Comment by miguelarias** [comment]
Hi, nope, the dataset was newly uploaded and I had no previous hover infowindows. What I did is add the click infowindows first, and then tried to add the hover ones.

**Comment by matallo** [comment]
couldn't reproduce, please ping me if this is still happening or happen again

closing then
