### ISSUE TITLE
Vertical alignment the buttons over map

### ISSUE THREAD

**Issue by urbanphes** [CartoDB/cartodb#8894]
The zoom control buttons and the change view buttons don't have the same vertical alignment. We should lower 7px the change view buttons.

![image](https://cloud.githubusercontent.com/assets/14546701/16865086/80d16d88-4a62-11e6-9cd7-aeb00a11cd3d.png)

**Comment by xavijam** [comment]
After the change @MariaCheca, check if it looks ok in the table view too, please.
