### ISSUE TITLE
Heatmap layers get duplicated when reordering them on the layer list - below another layer

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8896]
STR:

1. Add a points layer (a)
2. Add another points layer (b)
3. Style layer (a) to create a heatmap
4. Drag the layer (a) below the layer (b)
5. Drag the layer (b) below the layer (a)
6. Drag the layer (a) below the layer (b)
7. Keep going. You will see the heatmap layer being duplicated.
8. If you refresh the map it will show just one heatmap layer and one point layer.

**Comment by ramiroaznar** [comment]
@miguelginer found the same issue today:

![captura de pantalla 2016-07-19 a las 16 49 39](https://cloud.githubusercontent.com/assets/5215798/16955564/63a91c3a-4dd5-11e6-9e72-7a18039a114a.png)

After disabling the view of all the layers, the Heatmap is still there.

**Comment by xavijam** [comment]
Taking care of it with the redesign of the torque styles form.

**Comment by xavijam** [comment]
Fixed with these changes, heatmap or animated layers will not be able to be moved anymore.

https://github.com/CartoDB/cartodb/commit/98d4c87ded1faf3abaea0a8578e6170d9f0a20e9
