### ISSUE TITLE
SQL keywords for column names glitch

### ISSUE THREAD

**Issue by michesteva** [CartoDB/cartodb#890]
Using SQL keywords for column names (i.e. "when" and "where") causes the columns to automatically rename themselves to include an underscore (i.e. "_when" and "_where"), which makes infowindows, wizard, and editing geometries non-responsive when a user tries to revert to the non underscore column names.

**Comment by xavijam** [comment]
It is not possible to change that behaviour becuase is how postgres works. But if you check infowindows, a good thing, you can change the title for any attribute, so you could get rid of that underscores, for example :).
