### ISSUE TITLE
Export map modal problems in Firefox

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#8902]
When exporting a map, in Firefox, with popups blocked, we do not show the "ready to download" window:
 - In the builder, it gets stuck in the uploading status (spinner)
 - In the editor, it leaves the modal blank.

Can you check it @gfiorav?

**Comment by gfiorav** [comment]
Yup, thanks for assigning!

I'll check it out soon

**Comment by gfiorav** [comment]
Closed via https://github.com/CartoDB/cartodb/pull/9379
