### ISSUE TITLE
Tables referenced via analyses are not exported

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#8903]
Tables referenced directly from an analyses (e.g: the second parameter of Intersect second layer) are not included on the map export.

**Comment by javitonino** [comment]
This is harder than it looks, for example, this also affects dataset deletions. Maps which use the dataset via analyses don't trigger the "Deleting this dataset will delete this maps" modal.

Options: 
 - Check the analyses definition each time in `Visualization.related_tables` and `Table.affected_visualizations`, but probably more.
 - Modify `affected_tables` in the `Layer` model to take into account the analysis. This would also imply triggering Layer refreshes when updating analyses. If we go for this, we should consider indexing `Layer.options[:source]`.

This may also be affected by the pending API rewrite for analyses.

cc @juanignaciosl @gfiorav

**Comment by gfiorav** [comment]
We could do 2) using an index like the one in `analysis_definition[:id]`
