### ISSUE TITLE
 Cannot edit custom color palettes in Firefox

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#8905]
Clicking on a color doesn't do anything:

![](https://cloud.githubusercontent.com/assets/7569673/16868655/2b819882-4a79-11e6-8f89-bce02d5fee06.png).

**Comment by javitonino** [comment]
Also did have this: https://github.com/CartoDB/cartodb/issues/8898 but moved it to the main ticket.

Sorry for the confusion.

**Comment by xavijam** [comment]
No problem man
