### ISSUE TITLE
Separate models for different layers

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#8906]
Right now we basically have at least three different kind of layers (in the builder context, not to be confused with the layer types in the map!), each with their own kind of view and behavior:

There are various [kinds/types that defines a layer](https://github.com/CartoDB/cartodb/blob/f3d7f4be2af99974f2bfb0c71aa3eefbcc1614b0/lib/assets/javascripts/cartodb3/data/layer-types-and-kinds.js#L1-L17), but they can basically be put in three distinct categories:
- layer-on-top (tiled)
- data layers (cartodb, torque)
- basemaps - (tiled, wms etc.)

Right now we only have [one model](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb3/data/layer-definition-model.js) that represents them all, even if their behavior and data varies vastly.

Just like we have done with some other models I think it would make sense to have separate implementations for these three categories.

This way we can extract some business logic related to basemaps out from the views (see #8901 for an example), as well as for basemaps not having to know anything about analysis.

cc @xavijam @matallo @alonsogarciapablo

**Comment by matallo** [comment]
totally agree on isolating concerns for every layer in its own model!
