### ISSUE TITLE
In Torque data disappears if the whole tile is not on viewport

### ISSUE THREAD

**Issue by jatorre** [CartoDB/cartodb#8907]
Check out this visualization

https://jatorre-datacamp.carto.com/viz/a412e348-46df-11e6-b2ee-0ee66e2c9693/embed_map

When you pan, and data gets out of the viewport it dissapears, when you pan to view it again, you dont see the data unless the whole tile somehow get visible on the viewport. I think the video explains it better.

![crimes_torque_data_not_loaded](https://cloud.githubusercontent.com/assets/127803/16871553/d77a1732-4a87-11e6-810d-4209d1cc3e13.gif)

@javisantana

**Comment by saleiva** [comment]
Wrong repo, already reported on Torque repo
