### ISSUE TITLE
Map description text is wrapped

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb#8908]
This:

![selection_006](https://cloud.githubusercontent.com/assets/9017165/16871919/f2f0bfe6-4a89-11e6-9769-c80746245dc8.png)

Is rendered this way:

![selection_005](https://cloud.githubusercontent.com/assets/9017165/16871925/fdcb0430-4a89-11e6-85d7-a25e3334b65a.png)

**Comment by xavijam** [comment]
Let's fix it in the public map view.

**Comment by MariaCheca** [comment]
Issue moved to [CartoDB/deep-insights.js #428](https://github.com/CartoDB/deep-insights.js/issues/428) via [**ZenHub**](https://www.zenhub.com/)
