### ISSUE TITLE
Layer attribution is not displayed

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb#8909]
The dataset metadata is OK:

![selection_004](https://cloud.githubusercontent.com/assets/9017165/16872024/964591b2-4a8a-11e6-8382-ba0a84b4a7c2.png)

But the map only displays the CARTO attribution

![selection_007](https://cloud.githubusercontent.com/assets/9017165/16872041/b1e8bc3c-4a8a-11e6-8b5c-c66fd428aef3.png)

**Comment by alonsogarciapablo** [comment]
This should be fixed once we finish https://github.com/CartoDB/cartodb/issues/8957.

**Comment by alonsogarciapablo** [comment]
Closed via https://github.com/CartoDB/cartodb/issues/8957
