### ISSUE TITLE
PostGIS error in the analysis "Join columns from 2nd layer"

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartodb#8911]
### Summary:

The analysis ``Join columns from 2nd layer`` is not be working correctly. If you apply the analysis, Carto returns a failed request with the next error message:

```
Postgis Plugin: ERROR:  transform: couldn't project point (180 -90 0): tolerance condition error (-20)
```

The builder returns also an error in the dev tools console:

```
POST oboix.carto.com/api/v1/map?stat_tag=a08269b2-4a84-11e6-ae2d-
0ecd1babdde5&api_key=API_Key:1 POST https://oboix.carto.com/api/v1/map?
stat_tag=a08269b2-4a84-11e6-ae2d-0ecd1babdde5&api_key=API_Key 400 (Bad Request)
```

The analysis is never applied and the builder is showing a spin that never stops.
![screen shot 2016-07-15 at 14 34 20](https://cloud.githubusercontent.com/assets/11177693/16874374/3f724a24-4a99-11e6-934c-c99853ff0eb1.png)

### Steps:

1. Create a map with the world_borders dataset
2. Add analysis ``Join columns from 2nd layer``
3. Inside the analysis menu, choose as ``INPUT #1`` the ``world_borders`` layer and the ``populated_places`` layer as the ``INPUT #2`` and the join type ``Inner``
4. In the ``Foreign keys`` option, select ``iso2`` (world_borders layer) and adm0_a3 (for populated_places layer)
5. Select the geometry from the ``world_borders`` layer and the columns that we want to keep. For world_borders (area,fips,iso2,iso3) and the columns for populates_places (adm0_a3, adm0_cap, adm0_name and adm1_name)
6. Click on the ``Apply`` button.
7. The builder returns an error.
![screen shot 2016-07-15 at 13 22 57](https://cloud.githubusercontent.com/assets/11177693/16874673/ebc1eaa4-4a9a-11e6-9706-d4ae1619ab54.png)

8. If you open the dev tools of the browser it's shown a bad request error. In the network tab of the dev tools, if you click on the failed request (displayed in red), the ``Preview`` tab of this request returns an error:
```
Postgis Plugin: ERROR:  transform: couldn't project point (180 -90 0): tolerance condition error (-20)

in executeQuery Full sql was: 'SELECT ST_AsTWKB(ST_Simplify(ST_RemoveRepeatedPoints("the_geom_webmercator",1e-05),1e-05,true),5) AS geom FROM (SELECT ST_Transform(the_geom, 3857) the_geom_webmercator, fips, iso2, iso3, area, right_adm0cap, right_adm0name, right_adm0_a3, right_adm1name
FROM (SELECT _cdb_analysis_left_source.the_geom as the_geom, _cdb_analysis_left_source.fips, _cdb_analysis_left_source.iso2, _cdb_analysis_left_source.iso3, _cdb_analysis_left_source.area, _cdb_analysis_right_source.adm0cap as right_adm0cap, _cdb_analysis_right_source.adm0name as right_adm0name, _cdb_analysis_right_source.adm0_a3 as right_adm0_a3, _cdb_analysis_right_source.adm1name as right_adm1name
FROM
  (SELECT * FROM world_borders_4_copy) AS _cdb_analysis_left_source
  INNER JOIN
  (SELECT * FROM populated_places) AS _cdb_analysis_right_source
ON _cdb_analysis_left_source.iso2 = _cdb_analysis_right_source.adm0_a3) _cdb_analysis_query) as cdbq WHERE "the_geom_webmercator" && ST_MakeEnvelope(-20037508.3,20037508.25881302,-20037508.25881302,20037508.3,3857)'
```

![screen shot 2016-07-15 at 14 16 58](https://cloud.githubusercontent.com/assets/11177693/16874760/7e0c96fc-4a9b-11e6-819c-f5d062660277.png)

**Comment by saleiva** [comment]
This is a dupe! It's a known bug. It's only happening with that dataset, right?

**Comment by oriolbx** [comment]
@saleiva sorry i didn't realize that it was duplicated. Yes, at the moment this kind of error is only happening with that dataset.

**Comment by saleiva** [comment]
No prob!

On Jul 15 2016, at 6:01 pm, oriolbx &lt;notifications@github.com&gt; wrote:  

> [@saleiva](https://github.com/saleiva) sorry i didn't realize that it was
duplicated. Yes, at the moment this kind of error is only happening with that
dataset.

>

> —  
> You are receiving this because you were mentioned.  
> Reply to this email directly, [view it on
GitHub](https://github.com/CartoDB/cartodb/issues/8911#issuecomment-232993243),
or [mute the thread](https://github.com/notifications/unsubscribe-
auth/AAIENSBEC0DE2vEEbdIFDixEs5_otozEks5qV66egaJpZM4JNXv2).![](https://github.com/notifications/beacon
/AAIENSsjWr5l5LEZ4K-2IeZ4SgojWs27ks5qV66egaJpZM4JNXv2.gif)
