### ISSUE TITLE
The "Geometry from" option automatically changes after applying the  "Join columns from 2nd layer" analysis

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartodb#8912]
### Summary:

After configuring the options of the "Join columns from 2nd layer" and applying the analysis, in the `Columns` section of the analysis options, the `GEOMETRY FROM` option changes the selected option to the layer that we haven't select to get the geometries.

Nevertheless, in the requests can be seen that the builder uses the geometries from the layer that we have selected.
### Steps:
1. Configure then options of the `Join columns from 2nd layer` analysis so that we can get the geometries from the `world_borders` layer (country polygons) and we do the join with the `populated_places` layer.
   ![screen shot 2016-07-15 at 14 59 22](https://cloud.githubusercontent.com/assets/11177693/16875157/2e6744a0-4a9e-11e6-8cb0-9a9472a95f9b.png)
2. Apply the analysis, the option `GEOMETRY FROM` option, automatically changes to the `populated_places` layer:
   ![screen shot 2016-07-15 at 14 59 53](https://cloud.githubusercontent.com/assets/11177693/16875177/4f520aec-4a9e-11e6-844e-3ffe0f26a008.png)
3. Carto is doing the request correctly.The requests done after the analysis show this preview:
   ![screen shot 2016-07-15 at 15 00 08](https://cloud.githubusercontent.com/assets/11177693/16875213/829ff9b8-4a9e-11e6-9c19-f9b990986f73.png) where  the parameter `source_geometry_selector` is `a0` (the geometry from the world_borders layer)

**Comment by saleiva** [comment]
Looks like not happening anymore
