### ISSUE TITLE
Set error tooltip when a node has failed

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#8918]
![screen shot 2016-07-18 at 10 12 45](https://cloud.githubusercontent.com/assets/132146/16909040/301d149e-4cd0-11e6-810d-8d2a96517fdd.png)

There could be an error in a node within a layer, so error notification is great, but is disappear after some seconds, so it would be great to have the tooltip providing the error at any time.

**Comment by viddo** [comment]
Some pointers, I think changing:
- https://github.com/CartoDB/cartodb/blob/b3a813d97db1b71b4ca7de6c288f6d787dd90ac4/lib/assets/javascripts/cartodb3/editor/layers/layer-content-views/analyses/analyses-workflow-item-view.js
- https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb3/editor/layers/analysis-views/default-layer-analysis-view.js

…and just get `this._analysisNode.get('error');` and display that in a tooltip should do the trick.
