### ISSUE TITLE
Analysis should suggest next analysis step when complete

### ISSUE THREAD

**Issue by stuartlynn** [CartoDB/cartodb#8919]
For lots of the analysis we know the next most likely step to add in the chain. For example if you run : "Find n clusters" you probably want to then find the centroids of those clusters. 

It would be great if somewhere in the analysis specification we could provide a list of the 3 next most likely steps after the current one has run that the user could then click on and instantly add to their analysis chain. 

Would facilitate a really nice flow I think. What do you think @andrewxhill @saleiva

**Comment by xavijam** [comment]
That's the thing we have already with the "analysis" info after it is finished. And, add analysis modal is going to have a better look and feel + description so, it is gonna be legen-dary!
