### ISSUE TITLE
MailChimp Connector 404 oauth error

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#8920]
@rafatower 
cc @yasharora73 

S/B 9400264

Client recently had MailChimp Connector enabled for his account. He gets 404 oauth error in popup window that appears when he clicks MailChimp button from CARTO Connect dataset page.

## Context
I was able to replicate client's error - but also I reset my MailChimp password before trying to connect from CARTO.

## Process
(I already had MailChimp connected to CartoDB app)
1. Log into MailChimp
2. Click on your avatar & choose Account
3. Click on Extras & API Keys
4. In Authorized applications section click the x button next to CartoDB to un-authorize it 
From CARTO Datasets page click New Dataset
5. Log into CARTO account from incognito window
6. Nav to Datasets page & click New Dataset
7. On next Connect dataset page click MailChimp button, then Connect button
(window pops up where you are supposed to be able to log into MailChimp)

also:
8. In CARTO Editor click on avatar & Your account
9. Click Account from left vertical menu
10. In Connect to external data sources section click Connect next to MailChimp.
(window pops up where you are supposed to be able to log into MailChimp)

## Expected result
After logging into MailChimp via popup window list of connectable datasets will appear in CARTO ui & you can click/import one. 

## Current result
![screen shot 2016-07-15 at 11 30 10 am](https://cloud.githubusercontent.com/assets/1779444/16880190/0c668652-4a82-11e6-87e7-a9c3431b05c0.png)

![screen shot 2016-07-15 at 11 35 22 am](https://cloud.githubusercontent.com/assets/1779444/16880193/0eef7320-4a82-11e6-80b7-b8224008c2ae.png)

ROLLBAR ERROR:
Gibbon::MailChimpError: Invalid MailChimp API key: {api key #}

------------------------------------------------------------------------------------------------
Related: in cartodb-platform 1987

**Comment by nilssonlg** [comment]
Im the client.  Feel free to ask if I can help
