### ISSUE TITLE
Add new analysis category for layer linking helpers

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#8922]
<img width="492" alt="screen shot 2016-07-15 at 1 37 50 pm" src="https://cloud.githubusercontent.com/assets/370259/16883339/6df21d8c-4a91-11e6-9210-9e0a7260ed5c.png">

The top level interface needs a new Category of analysis types for those that *don't* perform any analysis, but change the way widgets work. The "Filter by layer" is an example of one of those. 

cc @stuartlynn

**Comment by stuartlynn** [comment]
It's not clear to me that the linking of layers this way is even an analysis step. It feels like its something that should live more in the widget interface?

**Comment by andrewxhill** [comment]
agreed. actually for me this ticket was a way of getting it _more right_ for now, but i agree with @stuartlynn over the long term

**Comment by xavijam** [comment]
Modal is being redesigned, I feel @CartoDB/design will take care of it there.
cc @javierarce @piensaenpixel
