### ISSUE TITLE
Hide analyses that aren't meant for the current geometry type

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#8923]
IT would be ideal if every analysis in the Editor was linked to some input constraints. The most obvious would be 

required_geom_type: Polygon

or something along those lines. From there we could hide any that weren't relevant to the current layer. 

even more, it would allow us to easily change the language for a single analysis backend if it is going to operate on different inputs differently (e.g. centroid, morans, etc)

cc @stuartlynn

**Comment by saleiva** [comment]
Already working!
