### ISSUE TITLE
Add expert crumbs to the interface

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#8924]
This is an idea to not frustrate Experts by sugar coating the interface too much. 

We are trying hard to make analysis methods more explanatory that assuming the user already knows them in depth. However, an expert at times might just be looking exactly for "Moran's I". 

What about adding an expert tag to the interface?

<img width="449" alt="screen shot 2016-07-15 at 1 43 18 pm" src="https://cloud.githubusercontent.com/assets/370259/16883520/61663b9c-4a92-11e6-969f-49bcc47df098.png">

the "+" was to indicate that the user could likely interact with that tag to learn more about the analysis right away

@stuartlynn

**Comment by stuartlynn** [comment]
I think this is really important. In conversations with Julia and academics I think they will really want this. I know they are not necessarily our core audience but if we give them access to the full powerful underlying methods then they would do pretty awesome things with them.

**Comment by saleiva** [comment]
Being tracked on the new modal.
