### ISSUE TITLE
Remove odyssey.js related stuff from viz.json

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#8947]
Actual vizjsons include the following keys that are related to odyssey.js:

```
  ...
  "prev": null,
  "next": null,
  "transition_options": {
    "time": 0
  },
  ...
```

They could be removed, since they are not used right now.

cc: @javisantana @xavijam @juanignaciosl

**Comment by xavijam** [comment]
I feel there was a ticket about that, right @javitonino?

**Comment by javitonino** [comment]
Yup, this one: https://github.com/CartoDB/cartodb/issues/7677

**Comment by alonsogarciapablo** [comment]
👍
