### ISSUE TITLE
in Builder, attributions are incomplete

### ISSUE THREAD

**Issue by vhamer** [CartoDB/cartodb#8959]
(This may be a duplicate! I wasn't able to find the original)

Attribution on _all_ maps must include at minimum:
- Basemap source, ex: © [OpenStreetMap](http://www.openstreetmap.org/about/) contributors
- CARTO Attribution:   © [CARTO](carto.com/attributions)

Of course the user also has to add any other necessary attributions.

I noticed that, for example, on this map, the attribution shown is incorrect + incomplete:

![ign_spanish_adm3_municipalities_map](https://cloud.githubusercontent.com/assets/850589/16923507/a34ab2a6-4ce8-11e6-9deb-e4ed7f262db6.png)

**Comment by alonsogarciapablo** [comment]
Fixed in https://github.com/CartoDB/cartodb.js/pull/1361.
