### ISSUE TITLE
Color picker won't accept hex number

### ISSUE THREAD

**Issue by sandra-ku** [CartoDB/cartodb#8960]
![image](https://cloud.githubusercontent.com/assets/15849615/16923530/0039ae5e-4d1b-11e6-8a5e-f5fb9309510a.png)

Tried to create a map choosing navy blue, the color picker won't let me manually introduce the hex number, but still works if I chose it directly from the palette. Doesn't work on any color pickers (color as basemap or layer color).

cc/ @matallo @javierarce

**Comment by javierarce** [comment]
Thanks for the bug report, but this has been already submited before (#8363 & #7676).

**Comment by matallo** [comment]
oop, thanks and sorry for the inconvenience

**Comment by sandra-ku** [comment]
sorry for the noise then, guys!
