### ISSUE TITLE
[Metrics] Add new segment event 'Exceeded quota'

### ISSUE THREAD

**Issue by jmartinter** [CartoDB/cartodb#8963]
Track a new event 'Exceeded quota' into Segment.com every time a new dataset import fails due to not enough available space in disk:

The event will be identified by user id (box id) and include the following attributes:
- username: (user.username)
- email: (user.email)
- plan: (user.account_type)
- organization: (user.organization_user? ? user.organization.name : nil)
- event_origin: 'Editor'
- creation_time: (Time.now.utc)
- import_size: (size of dataset to be imported)

@gfiorav Is it possible to get the last attribute?

**Comment by gfiorav** [comment]
> import_size: (size of dataset to be imported)

I'd skip that one for now!
