### ISSUE TITLE
[Metrics] Add attribute to 'Created dataset' event

### ISSUE THREAD

**Issue by jmartinter** [CartoDB/cartodb#8965]
Include a new attribute in 'Created dataset' segment events:
 - ~~import_type: (type of file (csv, shp, geojson, ...) or connection (twitter, common data))~~

@gfiorav

**Comment by jmartinter** [comment]
Let's add two attributes intead the prior one:
 - import_type: file, twitter,  url, ...
 - file_type: csv,  shp, ... (if import_type = 'file' or import_type = 'url', null otherwise)

**Comment by jmartinter** [comment]
And another new attribute:
 - sync: true / false if import_type = 'url', null otherwise

Thanks!

**Comment by gfiorav** [comment]
As we agreed via Slack:

```
data_type --> data_from
datasource type --> imported_from
file_type
```

**Comment by jmartinter** [comment]
Wish list: would be possible to know the time required to import each dataset?

**Comment by gfiorav** [comment]
This was implemented in https://github.com/CartoDB/cartodb/pull/9304 at import level.

As we discussed: format is inherente to an import, not a dataset. All datasets have the same forma once in CARTO, the format is historical data. You can only have 2 types of datasets: _normal_ and raster. For example, if you create an empty dataset in CARTO, what format does it have? It really doesn't, it's a db table, not a file.

i.e, file type, data source and service name are in `Completed connection` events that precede the actual dataset creeation.
