### ISSUE TITLE
Create map with shared dataset doesn't work

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#8974]
STR

1. Share a dataset with user.
2. Create a map with that user and that dataset.

The map should display the data. Nevertheless there're errors on SQL API requests and map won't show data. It seems to be a problem generating the SQL.

cc @gfiorav @javitonino 

PS: adding layers with shared datasets works.

**Comment by gfiorav** [comment]
Hey @juanignaciosl does it happen with shared public/link datasets?

**Comment by juanignaciosl** [comment]
@gfiorav yes, creating maps with shared datasets with public or link privacy fail as well.

**Comment by juanignaciosl** [comment]
For future reference, this is caused by [this change](https://github.com/CartoDB/cartodb/commit/ab913a9c08f5780cde5071737e367f1ea1dd3e5a#diff-5998d420b31d480b34ff1b701377bd27L17). That change fixed #7583 by assigning the right map user. Previously the map assignment was wrong but [layer controller took advantage of that](https://github.com/CartoDB/cartodb/blob/3836ecef61e7849ad5ed2b7894bf0a104d411087/app/controllers/carto/api/layers_controller.rb#L18) in order to get the table owner.

I'll try to fix this at `LayerPresenter`, where it generates `table_name`, improving the way that it detects whether it needs to add the schema or not, in a backwards-compatible manner.

**Comment by juanignaciosl** [comment]
After a hangout with @alonsogarciapablo and @xavijam , as this ball of mud kept growing and spreading, we've agreed upon splitting it. First separated issue: Torque problems with shared datasets #9017.
