### ISSUE TITLE
Point symbology erroneously attached to polygon layer

### ISSUE THREAD

**Issue by talos** [CartoDB/cartodb#8983]
The layer `obs_9ee9d74ff21d3da9784fcd516b20b22ba928c6c4` is showing the point symbology in the "Style" tab, even though it's a polygon layer.  In the builder:

https://team.carto.com/u/jkrauss/builder/048c3c7a-49eb-11e6-9716-0ee66e2c9693

**Comment by saleiva** [comment]
Can you attach an screenshot? I believe it's a known bug

**Comment by talos** [comment]
@saleiva here's a screenshot:

<img width="918" alt="screen shot 2016-07-19 at 4 55 41 pm" src="https://cloud.githubusercontent.com/assets/415831/16966251/b67fb30a-4dd1-11e6-8992-043e27db157a.png">

**Comment by saleiva** [comment]
Duplicated! Thanks!
