### ISSUE TITLE
Duplicated CARTO attribution?

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#8984]
Somehow related to https://github.com/CartoDB/cartodb/issues/8959.

I'm wondering why we're showing the CARTO attribution twice (different copy, but same links):

<img width="431" alt="screen shot 2016-07-19 at 15 56 05" src="https://cloud.githubusercontent.com/assets/390398/16952453/88e6ab7c-4dc9-11e6-8e0f-3a31b8b87f66.png">

On one hand, basemap layers get [this attribution](https://github.com/CartoDB/cartodb-platform/blob/58527645c4b34b4416d6ae748d6267d1a6f54a7d/cookbooks/cartodb_app/attributes/basemaps.rb#L13) (@ OpenStreeMaps contributors © CARTO) by default.

On the other hand, CartoDB.js also [sets a default attribution](https://github.com/CartoDB/cartodb.js/blob/v4/src/geo/map.js#L13) (CARTO attribution)...

Couldn't we "merge" both CARTO attributions? 

cc: @javisantana @saleiva @xavijam

**Comment by javisantana** [comment]
we should from my point of view, @vhamer any issue with that?

**Comment by saleiva** [comment]
Let's do that, I think is a problem we inherited because of iterating wrong at some point

**Comment by vhamer** [comment]
thanks for looping me in! yes, i think you just need to remove the "@ CARTO attributions" at the end. no need to include the word 'attribution' in the attribution, or to repeat CARTO. so the result is:


@ [OpenStreetMap](http://www.openstreetmap.org/about/) contributors @ [CARTO](carto.com/attributions)

hope this helps. thanks for fixing it!

**Comment by alonsogarciapablo** [comment]
Ok, I'm going to change the default attribution in CartoDB.js to "© [CARTO](carto.com/attributions)". But, we'd also need to:

1. Remove the "© CARTO" part of our [basemap attributions](https://github.com/CartoDB/cartodb-platform/blob/58527645c4b34b4416d6ae748d6267d1a6f54a7d/cookbooks/cartodb_app/attributes/basemaps.rb#L13).
2. Run a migration to update the remove the "© CARTO" attribution from all existing base and labels layers whose attribution is "@ [OpenStreetMap](http://www.openstreetmap.org/about/) contributors @ [CARTO](carto.com/attributions)".

It that ok with you @javisantana?

**Comment by alonsogarciapablo** [comment]
After latest changes in cdb.js, this is the state of things:

Old maps:

<img width="301" alt="screen shot 2016-07-21 at 11 05 15" src="https://cloud.githubusercontent.com/assets/390398/17058559/4b561158-5021-11e6-8df1-7030456763bb.png">

New maps:

<img width="354" alt="screen shot 2016-07-20 at 15 39 09" src="https://cloud.githubusercontent.com/assets/390398/17058560/4b5c61a2-5021-11e6-9ded-d5d9d496bf65.png">

@javisantana are you ok with my previous comment? should we prioritise this?

**Comment by javitonino** [comment]
Config updated, new maps should start using the new attributions in ~30 min

**Comment by alonsogarciapablo** [comment]
@javitonino are we also migrating attribution of existing layers as part of this? (as described [in this comment](https://github.com/CartoDB/cartodb/issues/8984#issuecomment-233896131))

**Comment by javitonino** [comment]
On it, but waiting for config changes to apply first.

**Comment by alonsogarciapablo** [comment]
Grrreat! Thanks!

**Comment by javitonino** [comment]
Update running, ETA this afternoon
