### ISSUE TITLE
New Builder layer defaulted to old orange style for polygons

### ISSUE THREAD

**Issue by talos** [CartoDB/cartodb#8986]
The layer is `nyc_car_households_tract` in https://team.carto.com/u/jkrauss/builder/f83b7162-4c82-11e6-97e9-0e3ebc282e83/

**Comment by saleiva** [comment]
Hey talos, can you provide STR?

**Comment by talos** [comment]
No problem @saleiva !

1. Create a new map in the Builder
2. Add `nyc_car_households_tract` (from jkrauss.cartodb.com) as a dataset and press "Create Map"
3. Style applied is old-school orangey orange:

<img width="1267" alt="screen shot 2016-07-19 at 5 04 39 pm" src="https://cloud.githubusercontent.com/assets/415831/16966531/f6f0be10-4dd2-11e6-9bbd-ca34d20d178a.png">

**Comment by talos** [comment]
BTW that dataset is one I uploaded from a CSV on disk using the Import API.

**Comment by xavijam** [comment]
Related to https://github.com/CartoDB/cartodb/issues/9339, and [important comment](https://github.com/CartoDB/cartodb/issues/9339#issuecomment-240753672) there.

**Comment by xavijam** [comment]
BTW, this is already fixed, when you add a new layer in the builder, that layer is added with the default cartography colors. The problem or the non-desired behaviour is happening in #9339, so closing this one because it is fixed 🎉 .
