### ISSUE TITLE
Basemap dependent styling 

### ISSUE THREAD

**Issue by makella** [CartoDB/cartodb#8997]
As a future request/enhancement:

It would be great if we could have two sets of default styles: one for Positron and one for Dark Matter. This would include things like:
- flipping quantitative ramps 
- using a dark outline on points for Dark Matter, light outline for Positron
- choosing the best default ramps depending on the basemap, etc.

We did start some of this thinking with deep insights and have good examples and the beginnings of implementation there.

cc: @saleiva @javisantana

**Comment by makella** [comment]
In deep insights we also did a classification of our basemaps as to which we would consider light and which would be considered dark. So this idea would cover more than just Carto's basemaps.

See discussion here: https://github.com/CartoDB/deep-insights.js/issues/333

**Comment by xavijam** [comment]
That's a good one, but a difficult one too.

**Comment by makella** [comment]
Well, we are part way there now that we can flip ramps!! :)

**Comment by makella** [comment]
closing for the 'flip ramp' portion... the other points i'll open in a different issue
