### ISSUE TITLE
Include Data Observatory Quota remaining and estimates in Builder

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#8998]
Upon clicking here, the user should get some information about available/remaining quota and what sort of quota would be used

<img width="287" alt="screen shot 2016-07-19 at 2 06 54 pm" src="https://cloud.githubusercontent.com/assets/370259/16961119/22ef015c-4dba-11e6-8c04-ed5a96767ee2.png">

**Comment by saleiva** [comment]
I'm afraid that that will not be possible with every "paid" analysis since sometimes it depends on the parameters of it (AOI with tracts)
