### ISSUE TITLE
category widget: show percentage of total each category represnts

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartodb#8999]
Category widgets can aggregate in some fancy ways, but getting a fuller picture like: of the current view, what percentage of the total does this category represent? 

In this map: http://www.fastcodesign.com/3061143/infographic-of-the-day/where-san-francisco-residents-are-getting-evicted

I want an easy way to know the percentage of 'high rise dense urbanites' as well as the count. I don't see an easy way to do this with the widget/analysis framework since the view changes the values in the widgets and this calculation is `(num of category in current view) / (total num in current view)`

**Comment by urbanphes** [comment]
Relate to https://github.com/CartoDB/design/issues/52

**Comment by xavijam** [comment]
Moving it to design

**Comment by xavijam** [comment]
Issue moved to [CartoDB/design #258](https://github.com/CartoDB/design/issues/258) via [**ZenHub**](https://www.zenhub.com/)

**Comment by saleiva** [comment]
But wait, design is ready. This ticket should be here since it needs to be implemented.

**Comment by andy-esch** [comment]
I'd still reallllllyyyy love for this to be a thing!!
