### ISSUE TITLE
Option to choose another category ramp

### ISSUE THREAD

**Issue by makella** [CartoDB/cartodb#9002]
We will need the option to change the category ramp from default to another one in our list.

Right now, I don't see a way to access the color ramps once I've made the selection of Category on a non-numeric field.

![screen shot 2016-07-19 at 1 55 37 pm](https://cloud.githubusercontent.com/assets/1566273/16964427/a42a9a30-4db8-11e6-8685-41cc06c212c1.png)
# SMOKE_MG17
# SMOKE_MG21

**Comment by saleiva** [comment]
Cc/ @urbanphes

**Comment by josecruz** [comment]
Hey! I upload here the complete flow for category ramp selection. 

Basically the idea is to replicate the behaviour of the others ramp selection:

1. You select column
2. You select color ramp
3. You need to adjust colors? Then go to custom color set.
4. Edit

<img width="1174" alt="screen shot 2016-07-27 at 12 04 47" src="https://cloud.githubusercontent.com/assets/596509/17171813/93d87ce8-53f2-11e6-9c8d-ede13829b632.png">

To go back you have the back arrow on the column name. I also added a "Category" distribution but disabled due you cannot change it

**Comment by josecruz** [comment]
Updated back label ^

**Comment by saleiva** [comment]
VAMOS NENO.

**Comment by makella** [comment]
nice, @josecruz!

**Comment by makella** [comment]
This was a common question/request at the Builder training last week in NYC. Just a heads-up. Think it is really important!

**Comment by xavijam** [comment]
It is already implemented and working.

**Comment by makella** [comment]
it is? I'm not able to see the other category ramps. Am I missing something?

![screen shot 2016-10-04 at 10 00 16 am](https://cloud.githubusercontent.com/assets/1566273/19081980/74ecfdc4-8a19-11e6-8dcb-4c4f586f40be.png)

**Comment by xavijam** [comment]
Ahh, wait, you can change the color of any category, and that "ramp" will be stored until you changed to any other column. But yes, definitely not the thing you were requesting.

**Comment by ramiroaznar** [comment]
Ey @CartoDB/design if I push this to RT, are the assets ready to add the other category ramps to BUILDER?

**Comment by piensaenpixel** [comment]
nop, push it :)

**Comment by IagoLast** [comment]
@ramiroaznar  do we have a ramp list?

**Comment by ramiroaznar** [comment]
Yes, you can find a wiki [here](https://github.com/CartoDB/research/wiki/Qualitative-Palettes). But I suppose, there will be another one in [cartocolors repo](https://github.com/CartoDB/CartoColor). [Here](https://github.com/CartoDB/CartoColor/blob/master/cartocolor.js), for instance.

**Comment by ramiroaznar** [comment]
adding @arianaescobar to the loop in case you need a hand from design

**Comment by ramiroaznar** [comment]
Hey @matallo can any of Bravo team give a hand to @IagoLast?

**Comment by IagoLast** [comment]
Fist working version: 

[![https://gyazo.com/272e055f9ca23eafe1a2d4d4cb1f218b](https://i.gyazo.com/272e055f9ca23eafe1a2d4d4cb1f218b.gif)](https://gyazo.com/272e055f9ca23eafe1a2d4d4cb1f218b)

**Comment by ramiroaznar** [comment]
@makella please tell us which color ramp is the new default one.

**Comment by ramiroaznar** [comment]
Got the defaults!

@IagoLast please can you change the defaults:
* For numbers: `PurpOr` [BONUS]
* For categories: `Vivid`

As explained in this issue https://github.com/CartoDB/cartodb/issues/8857

@arianaescobar can you confirm that `PurpOr` color ramp for gradient/choropleth maps still works for Voyager?

**Comment by arianaescobar** [comment]
It does :)

**Comment by arianaescobar** [comment]
Oops, I might have spoken too soon. The lightest color of that ramp is quite similar to Voyager's land color so the contrast is not ideal. Could we put this one on hold until @makella returns so she can review it first? 

By the way, we are also applying this change to lines and polygons, right?

**Comment by ramiroaznar** [comment]
The defaults can wait until Mamata is back (today). :-)

**Comment by makella** [comment]
hello all this is so great and a big step forward :)

before I go into the default selections, I am wondering if it is a global default for all geometries (points,lines,polys) or if we have the option to modify the default color scheme based on geometry type.

the old issues that are referenced here (with default selections) are specific to geometry/map types.

let me know that and then i'll provide answers depending on what we are doing.

thanks!

**Comment by ramiroaznar** [comment]
hi @makella! :-) :heart: 

We can use this issue to implement the right default ramps by geometry. So please can you tell us the default cartocolors schemes for this cases?

### Quantitative ramps:
a. Points
b. Lines
c. Polygons

### Qualitative ramps:
a. Points
b. Lines
c. Polygons

?

Looping @alonsogarciapablo

**Comment by ramiroaznar** [comment]
After talking with @makella these are the default color ramps:

### Quantitative ramps:
a. Points: `Burg`
b. Lines: `Magenta`
c. Polygons: `Purp`

### Qualitative ramps:
a. Points: `Prism`
b. Lines: `Prism`
c. Polygons: `Prism`

The logic behind these changes was:
* We needed to adapt the default ramps to the new default basemap (Voyager).
* They needed to work also on topo of Positron and Dark Matter basemaps.
* (Secondary) Points and lines should work on top of polygons.

Mamata selected the default ramps for points and polys. I took the decision on lines because Steph is on vacations. 

@dv343 @elenatorro you can go ahead! Let me know when the acceptance is ready.

**Comment by IagoLast** [comment]
@dv343 @elenatorro ping me if you need help :)

**Comment by ramiroaznar** [comment]
![image 008](https://user-images.githubusercontent.com/5215798/36389281-dabfcf34-159e-11e8-9115-9a073c3f47d6.png)

![image 007](https://user-images.githubusercontent.com/5215798/36389288-e29261c2-159e-11e8-9663-30fc7afc35e8.png)

VAMOS!!!! @IagoLast @elenatorro @davidmanzanares @jesusbotella @matallo

**Comment by elenatorro** [comment]
VAMOS!! Well done, team! ❤️❤️❤️

**Comment by IagoLast** [comment]
non era sen tempo 😂

**Comment by matallo** [comment]
in production! 🚀

**Comment by makella** [comment]
HUGE and been waiting a long time for this!!

thanks to all!!!
