### ISSUE TITLE
Mobile api keys design review

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#9005]
@javitonino commented on [Fri Jul 15 2016](https://github.com/CartoDB/cartodb-central/issues/1320)

 - [ ] Api key nested too deep
 - [x] Remove user key (mobile SDK is going to stop using it)
 - [x] Allow update dev -> open/closed (done in Central/backend, missing UI and Box controller changes)

Hey @josecruz:
After meeting with @jaakla to prepare the launch of the CartoSDK, he proposed some changes to the design. Let's meet when you are available and I'll give you the details, please :pray: 

---

@jaakla commented on [Fri Jul 15 2016](https://github.com/CartoDB/cartodb-central/issues/1320#issuecomment-232953405)

Also please remove Carto apiKey from this screen, as we cannot use it in mobile at all due to security reasons.

---

@josecruz commented on [Wed Jul 20 2016](https://github.com/CartoDB/cartodb-central/issues/1320#issuecomment-233909678)

Hey! I upload here last changes:
![api keys - 00 - 02 - edit form](https://cloud.githubusercontent.com/assets/596509/16989204/95829cf4-4e93-11e6-9770-15417a112393.png)

**Comment by javitonino** [comment]
A bit confusing, but moved the issue to this repo where it made more sense. We want to have this ready for this milestone. Basically:
 - Move API key to the main mobile app tab and remove the license keys tab. Drop the user key.
 - Allow updating the app_type from dev to open/closed but nothing else.

@MariaCheca This implies a minor controller change in the backend, ping me if you need help to do the change, or you prefer for me to do it.

**Comment by jaakla** [comment]
Suggestion on design - do not use term "API Key" in this page at all, otherwise it would be confused by general CARTO API Key, which is different value and cannot be used in mobile. Mobile SDK has only "License Key".

**Comment by saleiva** [comment]
+1 to that @jaakla cc/ @josecruz

**Comment by josecruz** [comment]
Cool, updated that on the first comment!
