### ISSUE TITLE
Styling by category does not work

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#9011]
### Steps

1. Create a map.
2. Style by Value. Select a categoric field.
3. Styling does not work. This is the error that shows in the Builder and console:

![category](https://cloud.githubusercontent.com/assets/5215798/16990366/1104a5e4-4e98-11e6-8699-88b479e211d8.png)

**Comment by ernesmb** [comment]
This is the error returned by the Maps API call: 
```
style0:34:2 L7 is not a valid keyword in a filter expression↵style0:34:2 Cannot use operator ">" with value L7
```
there is one of those lines for each category value.

**Comment by saleiva** [comment]
hotfixing it

**Comment by rochoa** [comment]
Fixed at https://github.com/CartoDB/Windshaft-cartodb/releases/tag/2.66.2.
