### ISSUE TITLE
Cannot read property 'getSchemaName' of undefined

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#9015]
I get an error when I open a layer in the builder.

STR:

1. Go to the dashboard --> dataset.
2. Select a dataset that you own.
3. Click "create map".
4. Click at the layer. This error appears:

![screen shot 2016-07-20 at 17 24 17](https://cloud.githubusercontent.com/assets/932968/16992236/d3197dd4-4e9e-11e6-801f-4dbcb39425ec.png)

cc @xavijam @fdansv

**Comment by ramiroaznar** [comment]
Similar. The whole panel is getting blank after going to layer, styling and back to layer:

![1](https://cloud.githubusercontent.com/assets/5215798/16992707/b3f696b0-4ea0-11e6-9437-5aa5957e6553.png)
