### ISSUE TITLE
Torque doesn't work with shared datasets

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#9017]
STR

Disable builder in order to try with the Editor (I haven't been able to test this in the Builder because of a bug but I think that the problem is exactly the same).

1. Go to Dashboard -> Datasets -> Shared with you.
2. Select a private one and click "Create map".
3. Open the map in an incognito window. It works (this helps to see that problem is at torque).
4. Set Torque style in the wizard. There's a GET to the tiler that fails with this error:

```
{type: "unknown", message: "TorqueRenderer: permission denied for relation twitter_t3chfest_reduced",…}
```

That request is done to `https://TABLE_OWNER_USERNAME.carto.com/api/v1/map?config=...`, which I think that is wrong, as it should be done to the subdomain of the owner of the visualization.

5. If you open the embed the request to the tiler fails with `"Template 'tpl_9b364c98_4e90_11e6_937a_0e3ebc282e83' of user 'TABLE_OWNER_USERNAME' not found"`, because of the same reason.

6. If you reload the editor the Torque animation works, as the request is now done with the right user subdomain (the owner of the visualization). Nevertheless the embed seems broken again.

It looks like Torque is creating the url with the username that it finds at `layer.options['user_name']`. That's wrong, as that user is not the visualization owner but the `layer.options['table_name']` owner.

This has appeared while testing the fix for #8974.

cc @xavijam @alonsogarciapablo @fdansv @javisantana

**Comment by javisantana** [comment]
could you share the viz.json?

**Comment by javisantana** [comment]
I did the same with the builder and the viz.json is not being generated correctly and indeed we are using `layer.options.user_name` instead of `datasource.username` to generate the url

**Comment by juanignaciosl** [comment]
1. Vizjson [v2](https://team.carto.com/u/juanignaciosl/api/v2/viz/e3778c76-4e98-11e6-a95f-0ecd1babdde5/viz.json) and [v3](https://team.carto.com/u/juanignaciosl/api/v3/viz/e3778c76-4e98-11e6-a95f-0ecd1babdde5/viz.json). What's wrong with them?

2. Using `datasource.username` would fix it with v3, but would keep v2 broken. Is that good enough now that we're moving forward?

**Comment by javisantana** [comment]
yep, the v3 would be fixed using dataset.userneme, for v2 I think we might have a problem because if we change user_name to the real one it could break other things

**Comment by javisantana** [comment]
I checked v3 viz.json with cartodb.js v4 and works as expected (so does the embed https://team.carto.com/u/juanignaciosl/builder/e3778c76-4e98-11e6-a95f-0ecd1babdde5/embed)

For v2 it needs to be a fix done server side

**Comment by juanignaciosl** [comment]
@javisantana the embed doesn't work for me, it's "frozen" at the beginning. In spite of being a 200, the named map jsonp response contains an error: `"Template 'tpl_e3778c76_4e98_11e6_a95f_0ecd1babdde5' of user 'xavijam' not found"`.

**Comment by javisantana** [comment]
- that jsonp call is fine, it's a legacy call we should remove ,the good one is the named map one
- timeslider not working is another issue @fdansv 

If you check the torque tiles they are fine

**Comment by juanignaciosl** [comment]
@javisantana I've tried adding the `datasource` at vizjson v2 and Torque won't use it. What's the server side fix that you suggested?

**Comment by javisantana** [comment]
v2 does not use datasource, that's a new thing in v3. 

In v2 we'd need to fix layer `user_name` so it's the table owner and not the logged user

**Comment by juanignaciosl** [comment]
No, the current problem is that layer `user_name` _is_ the table owner (it's related to `table_name` option). And the opposite, making `user_name` the visualization owner, won't work because it's currently needed to compose the query.

**Comment by javisantana** [comment]
so it's an issue we can't fix just tweaking user_name. The only way I know is replacing backend side the {{user}} in maps_api_template

**Comment by javisantana** [comment]
the code: https://github.com/CartoDB/torque/blob/master/lib/torque/provider/windshaft.js#L361

**Comment by juanignaciosl** [comment]
Ok, the last tests of #8991 integrating all fixes revealed a last issue in staging: Torque still generates the wrong CDN request. [Example](https://juanignaciosl-ded-01.carto-staging.com/u/juanignaciosl-ded-01-1/viz/a667cde8-533c-11e6-a354-040120e0c101/map). It requests [a url based on the table owner](https://cdb-staging-1.global.ssl.fastly.net/juanignaciosl-ded-01-admin/api/v1/map/juanignaciosl-ded-01-1@03b6ae62@975860cc57a80183e1c8e4924a51839a:1469014073378/2/4/7/5.json.torque) instead of [the visualization owner](https://cdb-staging-1.global.ssl.fastly.net/juanignaciosl-ded-01-1/api/v1/map/juanignaciosl-ded-01-1@03b6ae62@975860cc57a80183e1c8e4924a51839a:1469014073378/2/4/7/5.json.torque).

It's probably because of [these lines](https://github.com/CartoDB/torque/blob/31a81e760b249e76b159c9966c219ae570f9acb3/lib/torque/provider/windshaft.js#L364-L389). The [backend patch that works without CDN](https://github.com/CartoDB/cartodb/pull/9112/commits/03d55781a20ca21a8feabbc8e494191d2df30a59#diff-5b802705d1b0026242a3fa27f9659720R144) can't be applied here.
