### ISSUE TITLE
Privacy changes to private

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#9018]
With the builder enabled.

1. Go to dashboard --> new map and select a public dataset. The map is created with link privacy.
2. Add a private dataset. Privacy changes to private.

Bug or feature, @xavijam ?

cc @javitonino @gfiorav

**Comment by gfiorav** [comment]
This was a feature for sure, but I think that @xavijam changed it.

**Comment by xavijam** [comment]
Feature, it doesn't change by its own, just refresh visualization data and it returns PRIVATE.

**Comment by juanignaciosl** [comment]
Closing then....
