### ISSUE TITLE
Write on boarding text for "Georeference" analysis

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#9021]

**Comment by ohasselblad** [comment]
{Georeference} has finished.

{The geometries in your table were updated.}

* {the_geom}
  {This column, which stores the geographic information in your dataset, has been updated to reflect the boundaries or locations from the inputs specified.}

{Georeferencing data is a service that uses information from many sources to get the geographical information associated with latitude/longitude columns, city names, postal codes, administrative boundaries, IP addresses, or street addresses.}

{Read more in [documentation](https://carto.com/docs/carto-engine/dataservices-api/geocoding-functions/)}

**Comment by saleiva** [comment]
I'd add a pharagraph to show success vs error ratio. Something like

{XXX (Z%) of your YYYY rows have been successfully georeferenced.} instead of the first pharagraph

**Comment by javierarce** [comment]
I open a ticket for the last part: https://github.com/CartoDB/cartodb/issues/9150
