### ISSUE TITLE
Write on boarding text for "Enrich from Data Observatory" analysis

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#9022]

**Comment by ohasselblad** [comment]
{Enrich from the Data Observatory}

{A new column has} been included with your original data.

* {custom column name from user}
  {This column contains the data requested from the Data Observatory}

{The Data Observatory enrichment is the result of the geometry location and the measure requested.}

Read more in [documentation](https://carto.com/docs/carto-engine/data/).
