### ISSUE TITLE
Write on boarding text for "Filter by layer" analysis

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#9024]

**Comment by ohasselblad** [comment]
actually, i'm having trouble finding the camshaft node for this and figuring how to explain it.. @saleiva who could we rely on for this one?

**Comment by saleiva** [comment]
{Filter by layer} has finished.

{Filter by layer allows you to filter the data in your layer by propagating the filters in the {name_of_the_layer} layer. Now if you filter on widgets added to the attached layer, the results in this layer would be also filtered}

{link to documentation}

Something like that?

**Comment by javierarce** [comment]
@ohasselblad: Filter by layer is [filter-by-node-column](https://github.com/CartoDB/camshaft/blob/master/reference/versions/0.38.0/reference.json#L113)

I took the analyses titles from the UI (from the "Add a new analysis" modal).

**Comment by javierarce** [comment]
Shall I use @saleiva's suggestion then? Also, do we have a documentation for this analysis somewhere?
