### ISSUE TITLE
Write on boarding text for "Find centroid of geometries" analysis

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#9025]

**Comment by andrewxhill** [comment]
{Calculating centroids from geometries} has finished.

New columns have been {created as a new dataset}.

* {the_geom}
  {Point geometries representing the centroid(s) of your input data.}
* {value}
  {If Aggregate is selected, this will store the aggregate value for each centroid. If not, it will contain the count of features considered for each centroid.}
* {category}
  {If Categorize is selected, this column will store the category value for each centroid from the source dataset}

{Centroids are calculated from all, groups, or singular geometries. Using the optional parameters of Category, Aggregate, and Weight you can change how they are calculated and what information the result will contain.}

{link to documentation}

**Comment by javierarce** [comment]
Ok, I propose the following changes:

For `category` since we now if the user selected a column, we could show the list item only when the user categorices by a column and say: 

`{category}: {This column stores the category value for each centroid from the source dataset}`

For value we would have these two versions:

* {value} {This column stores the aggregate value for each centroid.}
* {value} {This column contains the count of features considered for each centroid.}

**Comment by saleiva** [comment]
❤️
