### ISSUE TITLE
Write on boarding text for "Intersect second layer" analysis

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#9027]

**Comment by ohasselblad** [comment]
```
{Intersect second layer} has finished.

{A new column has} been included with your original data. {It is one of:}

* {count_vals_density}
  {This column is added if COUNT was chosen as the aggregation operation}
* {{operation_type}_{column_name}}
  {This column is added if {operation_type} is chosen with column {column_name}}

{This operation performs a spatial intersection and aggregates the geometry values from the target layer that intersect with the geometry of the source layer.}
```

**Comment by javierarce** [comment]
I think this analysis also adds a `count_vals` column if COUNT is selected, right?

Also, in my opinion the descriptions are going to sound a bit weird and not very useful:

For example, if a user picks AVG and the column size, they'll see:

`{avg_size}:  {This column is added if avg is chosen with column size}`

Something similar happens with `count_vals_density`. 

Maybe in this case we don't need to add the descriptions? 

/cc @saleiva

**Comment by saleiva** [comment]
+1
