### ISSUE TITLE
Write on boarding text for "Predict trends and volatility" analysis

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#9033]

**Comment by ohasselblad** [comment]
{Predict trends and volatility} has finished.

{New columns have} been included with your original data.

* {trend}
  {The normalized trend for each geometry}
* {trend_up}
  {The probability that a geometry's value will move to a higher class}
* {trend_down}
  {The probability that a geometry's value will move to a lower class}
* {volatility}
  {A measure of the potential for a geometry to possess values in other classes}

{Trends and volatility are calculated based on the time series data input. Trends calculated from inputs with a longer history are more precise. Inputs for the time column should equally spaced (e.g., all one week/month/year apart).}

{Read more in [documentation](https://github.com/CartoDB/crankshaft/blob/develop/doc/04_markov.md)}
