### ISSUE TITLE
Design new legends

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#9051]

**Comment by saleiva** [comment]
One of the key drivers is that we should reuse part of the functionality of the widgets for the new legends.

## New "color by value" legend

The idea of this legend is to provide an overview on how the data is distributed among the different buckets. Also, as an actionable value I propose we add AVG/MEDIAN. This legend would change then the data changes.

![screen shot 2016-07-21 at 13 50 49](https://cloud.githubusercontent.com/assets/132149/17021747/4967e696-4f4a-11e6-9ad7-8a250efffb87.png)
![screen shot 2016-07-21 at 13 50 56](https://cloud.githubusercontent.com/assets/132149/17021746/496719dc-4f4a-11e6-8b21-4ba65ad04938.png)

## New "size by value" legend (only points)

This legend is a tricky one since we need legends to be very compact to fit within a dynamic and elastic UI like the one in our builder and embeds. This would show the different ranges of the data associated with the different sizes (circle size would be simulated here).

![screen shot 2016-07-21 at 13 50 36](https://cloud.githubusercontent.com/assets/132149/17021799/96871e06-4f4a-11e6-968b-6b19f7b58270.png)

## New "category" legend 

Pretty similar to the one we had before but showing the distribution of the data in the different categories. I'm thinking on adding percentages and so on, but since you can also add widgets I'd prefer to keep the legends clean (in this image you can see how it looks like when being with a histogram legend).

![screen shot 2016-07-21 at 13 51 03](https://cloud.githubusercontent.com/assets/132149/17021832/cc18cfec-4f4a-11e6-944c-7f0a3d37bac7.png)

**Comment by saleiva** [comment]
cc/ @CartoDB/research @urbanphes @makella @josecruz @piensaenpixel @javisantana

**Comment by javisantana** [comment]
so to have it clear:

- histogram bin count === quantification buckets
- histogra bin width === quantificaion buckets width
- histogram bin height === count of rows inside each bucket

So when data changes we should change the histogram height, right?

**Comment by ohasselblad** [comment]
One additional thing that would be nice: show the ranges on hover. Like hovering over the legend to get '17k - 34k' for a specific class. Hovering over a class and then dimming all geometries but those in the class would be killer :)

So much better than ours: https://github.com/CartoDB/research/issues/6

**Comment by ohasselblad** [comment]
Another thing that could be really important is the ability to change the scale and allow semi-log/log-log for data that has an exponential decay. There are other scales that we could suggest, too. I mentioned this previously in a deep-insights ticket: https://github.com/CartoDB/deep-insights.js/issues/71

**Comment by talos** [comment]
👍 to @ohasselblad about log-log/semi-log options.  Since it'll be tricky to automate, I think it would be amazing to have it as an advanced option for the time being.  We definitely would use it here.

The legends look great!  One comment on on "size by value" is that it's hard to make the horizontal connection between the points on the left and the top of each overlapping circle on the right.  By swapping the circle to the left, I think we get a clearer indication of which bucket goes to which circle:

![legend-modified](https://cloud.githubusercontent.com/assets/415831/17025420/c6bfcefe-4f29-11e6-9b3b-eda98d0a252b.png)

**Comment by makella** [comment]
These are very nice and aesthetically pleasing. My only comment is with the color by value legend that you can't see the class breaks like you can with the "size by value". I think that is something people will want. Can these values possibly fit under each bar in the legend?

**Comment by saleiva** [comment]
Since the bars sizes can be very different I don't think we will be able to do so... We might need to go to hover there... :(

**Comment by xavijam** [comment]
Closing since legends are ready now! 💋
