### ISSUE TITLE
group creation errors not shown

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/cartodb#9055]
@rgdonohue was trying to create a new group with a space in the name, but the new group wasn't created (or at least listed in the UI), and no error was thrown.

Steps to reproduce (:

1. Click "Create new Group"
2. Name the group something like "Fancy new group"
3. Click create group
4. The UI puts you back to the group screen without the new group being listed

It seems that either there should be an error about having a space in the new group, or groups should allow spaces in their names. I support the second option.

cc @juanignaciosl

**Comment by juanignaciosl** [comment]
I've seen an error because of the size: ["Group name must be shorter. It can't have more than 28 characters, but it is longer (30)"](https://rollbar.com/vizzuality/CartoDB/items/19503/). Spaces should be supported. Could you please check that a shorter name works?

cc @javitonino @gfiorav

**Comment by juanignaciosl** [comment]
@ohasselblad I've just checked that spaces are allowed. Nevertheless there should've been a meaningful error message, so, even though using a shorter name works, don't close this issue, because we should fix the error feedback.

cc @rgdonohue

**Comment by rgdonohue** [comment]
Yes, issue seems to be with character limit. Didn't get an error message, however.

**Comment by ohasselblad** [comment]
thanks @juanignaciosl!
