### ISSUE TITLE
Loading bar is not longer appearing on the map

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#9064]
cc/ @alonsogarciapablo

**Comment by xavijam** [comment]
It belongs to CartoDB.js not to the Builder.

**Comment by saleiva** [comment]
VAMOS NENO!

**Comment by alonsogarciapablo** [comment]
Somebody stole the BLUE BAR 😠!

**Comment by saleiva** [comment]
it's appearing when changing a filter, but now when changing just the style

**Comment by saleiva** [comment]
LONG LIVE TO THE BLUE BAR

**Comment by alonsogarciapablo** [comment]
Yes, it looks like BLUE BAR is not being displayed while tiles are being loaded.

**Comment by saleiva** [comment]
should this be fixed @alonsogarciapablo

**Comment by alonsogarciapablo** [comment]
I'm about to release it, so the BLUE BAR will be back very soon! :)

**Comment by saleiva** [comment]
yay! :_____
LONG LIFE TO THE BLUE BAR

**Comment by alonsogarciapablo** [comment]
BLUE BAR is back from vacation 🌅!
