### ISSUE TITLE
Layer style is lost after adding a 2nd and dragging the 1st on top

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#9065]
### Steps

* Add one layer (`layer1`).
* Add a category widget and click on "autostyling". 

![1](https://cloud.githubusercontent.com/assets/5215798/17030803/8c46710e-4f71-11e6-8437-b74f1a6d2ce6.png)

* Add a second layer (`layer2`). I have disabled for a moment `layer2` to check the styles are OK on `layer1`.

![2](https://cloud.githubusercontent.com/assets/5215798/17030876/db14621e-4f71-11e6-843c-5168f381a3ae.png)

* Drag `layer1` on top of `layer2`. The style of `layer1` is lost:

![3](https://cloud.githubusercontent.com/assets/5215798/17030908/f407a9b6-4f71-11e6-8404-d0d9b2dee478.png)

* If you refresh the page, the widget is again without autostyling. And works fine.

**Comment by xavijam** [comment]
Yeah, until we can't do this https://github.com/CartoDB/cartodb/issues/8551, it will happen.
Sorry @ramiroaznar
