### ISSUE TITLE
Chaging from one georeference type to another keeps values on some inputs

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#9066]
STR

Apply georeference by city names
Apply it
Go and apply georeference by Street Adresses
Some inputs are filled but they shouldn't

**Comment by javierarce** [comment]
Maybe I'm missing something, but why shouldn't be filled? Isn't that useful for the user? 

In my test I created this analysis: 

![screen shot 2016-07-27 at 11 49 56](https://cloud.githubusercontent.com/assets/4933/17171267/37f3b8f4-53f0-11e6-94f0-6bf163052a39.png)

And then when I changed to "Street Addresses" got: 

![screen shot 2016-07-27 at 11 50 00]
(https://cloud.githubusercontent.com/assets/4933/17171268/3901c646-53f0-11e6-9d54-2ef7998da1d3.png)

**Comment by javierarce** [comment]
We've decided to close it, since the current behaviour seems to make sense and couldn't find a case where changing the type mixed the entered values. 

Feel free to reopen it if you find an issue with this.
