### ISSUE TITLE
Mail rebranding designs

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#9068]
Hey!

Basically, we designed 4 "templates" that fits all of the email list here #8889 

## Basic text
![08 mailing - 051](https://cloud.githubusercontent.com/assets/596509/17031728/e71590fc-4f75-11e6-8390-43b514219c44.png)

## Social Notifications
![08 mailing - 040 img](https://cloud.githubusercontent.com/assets/596509/17031746/f8d81e18-4f75-11e6-8930-fd13a579c61e.png)

## Warnings
![08 mailing - 021](https://cloud.githubusercontent.com/assets/596509/17031765/0d6009b8-4f76-11e6-9d0e-2ccede96e639.png)

## Successful actions
![image](https://cloud.githubusercontent.com/assets/596509/17031779/2133b5a2-4f76-11e6-906c-dab3e725dd9c.png)

## 🎁  Welcome email
![08 mailing - 001](https://cloud.githubusercontent.com/assets/596509/17031810/42544ed6-4f76-11e6-9d67-b763056167b6.png)

For the full list of email check the invision here: https://invis.io/RF81APW7X

/cc for review @saleiva @urbanphes @juanignaciosl

**Comment by saleiva** [comment]
They look good!

**Comment by saleiva** [comment]
Who is going to do the markup?

**Comment by urbanphes** [comment]
They look great. I think it's very good basis to develop the system.

**Comment by juanignaciosl** [comment]
@saleiva: I spoke to @MariaCheca was assigned the first of the redesigns (#8214) some days ago and she was going to take care of them, unless anybody has a different opinion.
