### ISSUE TITLE
Blank map from "Create Map" button

### ISSUE THREAD

**Issue by talos** [CartoDB/cartodb#9073]
When I try to "Create Map" from a builder interface table (private: https://team.carto.com/u/jkrauss/dataset/customer_home_locations):

<img width="1393" alt="screen shot 2016-07-21 at 3 00 27 pm" src="https://cloud.githubusercontent.com/assets/415831/17035234/2de2cc88-4f54-11e6-9aa4-74d8df1cfb7c.png">

I get a loading screen,

<img width="1052" alt="screen shot 2016-07-21 at 3 00 45 pm" src="https://cloud.githubusercontent.com/assets/415831/17035248/428d6346-4f54-11e6-9cb8-2df36b6c14c3.png">

then a blank map.

<img width="1389" alt="screen shot 2016-07-21 at 3 00 19 pm" src="https://cloud.githubusercontent.com/assets/415831/17035261/536d24b2-4f54-11e6-8e42-bf072b0c00c0.png">

Reloading does not help.

The maps appear in my maps dashboard but yield the same blank page if I click on them.

<img width="1028" alt="screen shot 2016-07-21 at 3 01 51 pm" src="https://cloud.githubusercontent.com/assets/415831/17035220/1d00e1de-4f54-11e6-86bd-25e4289cc5a6.png">

**Comment by saleiva** [comment]
is there any error on the console?

**Comment by talos** [comment]
Bad cache. Closing.
