### ISSUE TITLE
Map Privacy module shows wrong description text

### ISSUE THREAD

**Issue by csobier** [CartoDB/cartodb#9083]
- Open a map in the Builder
- Open the privacy settings

The following module appears- note that the description should say "map", not "table" (this is how it appeared in the Editor). I would have changed the text myself but it looked like the source was coming from somewhere else.

![image](https://cloud.githubusercontent.com/assets/13319925/17056042/d5ec5bf8-4fde-11e6-9121-648bcb5edfc2.png)

**Comment by saleiva** [comment]
Good catch. Since this modal is changing completely with the new design I will keep this closed but mention @nobuti just in case he is not aware. Thanks @csobier !!!: :)
