### ISSUE TITLE
[Torque] Builder layers don't match embed layers

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb#9085]
When there is a torque layer the Builder layer order doesn't match in the embed (named map).

Torque layer in the Builder is placed bellow the labels layer:

![Builder layers](https://cloud.githubusercontent.com/assets/45346/17057803/d9895656-501c-11e6-8a29-4f38ea23320e.png)

However, the named map has the torque layer on top of the labels:

![Embed-Named-map](https://cloud.githubusercontent.com/assets/45346/17057822/00594ea8-501d-11e6-9c65-cc05d552186e.png)

**Comment by saleiva** [comment]
Not happening anymore
