### ISSUE TITLE
Use map exporter for visualization backup

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#9087]
The current visualization backup exports the vizjson on visualization deletion. How about changing it so it saves the map export instead? This includes a lot more information and opens the possibility for restorations (albeit with different ids).

What do you think? @juanignaciosl @gfiorav

**Comment by juanignaciosl** [comment]
I'd certainly go for it, but the ids might be an issue. Exporter removed ids on purpose, _but_ for a plain backup keeping them might make sense.

**Comment by juanignaciosl** [comment]
Closing automatically because of inactivity. If anybody considers that this still important, please reopen and it'll be prioritized.
