### ISSUE TITLE
basemaps: saving existing custom basemap with empty attributes (name)

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#9090]
**str**
- add custom xyz basemap
- change basemap
- add same custom xyz basemap via introducing the same url

the layer will be saved with an empty name, despite it will show properly in the old editor, in the new builder we rely in this name for the basemap title (see attached)

![screen shot 2016-07-22 at 18 04 53](https://cloud.githubusercontent.com/assets/36676/17063339/04c4b300-5037-11e6-8d57-89cd70f42189.png)

we'll tackle this in the add new basemap modal in the builder, and workaround this case by setting a `DEFAULT_NAME = 'Custom basemap'`

if you select the basemap via clicking the existing map in the dropdown it will be saved just fine

/cc @alonsogarciapablo

**Comment by inigomedina** [comment]
Hey @matallo, is this issue ready to be closed?

**Comment by matallo** [comment]
I don't think this has been fixed yet
