### ISSUE TITLE
Offer default column name from DO analysis

### ISSUE THREAD

**Issue by talos** [CartoDB/cartodb#9102]
We store nice, human readable & sanitized column names in metadata, and could easily offer a default after selections have been made.  If the user still wants to change, they could edit the default.

One easy UX solution would be to have the input box for column name moved to after the selectors, and by default disabled and populated with the default.  When they check a "custom" box, they can then modify it.

We should also throw an error if they try to use a column name that already exists in their table, and if the default column name overlaps (say, they already had a `total_pop` column in their table) we should default to `total_pop_2`, `total_pop_3`, etc.

**Comment by talos** [comment]
CC @saleiva your thoughts?

**Comment by saleiva** [comment]
Sounds good! Sure thing!

**Comment by talos** [comment]
Great! The colname will be made available through this in-progress API call: https://github.com/CartoDB/observatory-extension/issues/133

**Comment by matallo** [comment]
this is being tracked in https://github.com/CartoDB/cartodb/issues/9991

closing then!
