### ISSUE TITLE
Windows 8 Add Dataset layers error: No Pagination Shown

### ISSUE THREAD

**Issue by michellechandra** [CartoDB/cartodb#9104]
## Context
A user is unable to add an additional dataset layer to a map visualization if the dataset is not listed on the first page of results from the "add a new layer" screen. The pagination UI does not appear in order to select a dataset not listed on the first page of results.

## STR
Using a Windows 8 machine and either Internet Explorer 11 or Firefox, login to a CARTO account. 

Create a multilayer map visualization. Select to add a second layer: 
![screen shot 2016-07-25 at 14 47 37](https://cloud.githubusercontent.com/assets/5423288/17118727/d24008e8-5276-11e6-9df4-4feaefa99da1.png)

From the "add a new layer" screen that opens, select to add a new layer from stored datasets, scroll to the bottom of results in order to select a dataset that is on page 2 of the dataset list screen. No pagination UI will show and you will be unable to select a dataset if not on the first page of results:
![screen shot 2016-07-25 at 14 29 45](https://cloud.githubusercontent.com/assets/5423288/17118669/7d7cf870-5276-11e6-83a8-00dba0b865ce.png)

## Expected Result
Currently, a pagination UI interface is shown when the dataset does not appear on the first page of results when using CARTO on the latest Mac OS, Chrome browser:
![screen shot 2016-07-22 at 15 29 42](https://cloud.githubusercontent.com/assets/5423288/17118690/9324bb4a-5276-11e6-91d2-25e9ea601ac4.png)

## Current Result
No pagination UI is shown if accessing CARTO account from a Windows 8 machine.

**Comment by michellechandra** [comment]
@MariaCheca - the user is asking for an update to this issue, and it appears to be urgent for him.

**Comment by MariaCheca** [comment]
on my way.

**Comment by xavijam** [comment]
Thanks 💋

**Comment by MariaCheca** [comment]
@michellechandra fixed!

**Comment by xavijam** [comment]
Not working for the new builder 'add layer' modal.

**Comment by xavijam** [comment]
Let's take a look together tomorrow @piensaenpixel, important.

**Comment by ramiroaznar** [comment]
Hey guys, is this ticket solved then?

**Comment by xavijam** [comment]
Looks like so, right @piensaenpixel?

**Comment by ramiroaznar** [comment]
The user continues having problems.

**Comment by piensaenpixel** [comment]
IE:
![image](https://cloud.githubusercontent.com/assets/1214201/17849727/728f2010-685a-11e6-871d-48fda3a04943.png)


FF
![image](https://cloud.githubusercontent.com/assets/1214201/17849731/7a92ebc0-685a-11e6-9cd7-aa5a64a325ff.png)

**Comment by xavijam** [comment]
Hey @ramiroaznar, important to check if the problem persists or not, plase.

**Comment by piensaenpixel** [comment]
in my account in share datasets
![image](https://cloud.githubusercontent.com/assets/1214201/17850302/e3ab2166-685c-11e6-8a1d-4823722f7bc6.png)

**Comment by ramiroaznar** [comment]
In addition to @piensaenpixel, @jsanz and I have tested with different users using IE and Firefox in W8 and W10. Pagination works fine.

**Comment by ramiroaznar** [comment]
Ok, it was solved. Thanks @piensaenpixel & @xavijam.
