### ISSUE TITLE
Installation failed with db:setup_user

### ISSUE THREAD

**Issue by GISlator** [CartoDB/cartodb#9105]
Hi,

Installation failed in the step:
RAILS_ENV=development bundle exec rake db:setup_user

It says that does not know how to do db:setup_user.

Letter, when I try do create development user it revokes.

Any help?

**Comment by juanignaciosl** [comment]
It should be `RAILS_ENV=development bundle exec rake cartodb:db:setup_user`. I've just fixed the documentation (b1a2aef0e293adf767f9438a566cb0cd94b0d714), sorry.
