### ISSUE TITLE
Show more specific error message when importing unsupported types of ArcGIS layers

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/cartodb#9108]
As noticed by @julianamori in #9013, unsupported layers types (e.g. Raster) are simply ignored when importing a multi-layer resource, but cause an import error when importing a single layer. 

In this case we log this error message internally:

> 2016-07-25 16:25:44 UTC: Additional error info: Invalid layer type: 'Raster Layer'

But the error the user gets is a generic one, which might be misleading:

> Error retrieving data from datasource (1011)
> There was an error retrieving data from the datasource. Check that the file/data is still present.

We can map the error to mor appropriate error code or add a new one for this case.

The error shown when a multilayer resource consisting only of unsupported layers should also be reviewed.

**Comment by saleiva** [comment]
@jgoizueta is this still happening?

**Comment by jgoizueta** [comment]
Yes, still happening. Can be reproduced with this layer:
https://raster.nationalmap.gov/arcgis/rest/services/LandCover/USGS_EROS_LandCover_NLCD/MapServer/21

Internally we log this:

```
2016-11-22 14:33:47 UTC: Additional error info: Invalid layer type: 'Raster Layer'
```

But the users sees only this:

![image](https://cloud.githubusercontent.com/assets/5909/20527701/a4315cd4-b0c9-11e6-9abb-291940c5a36a.png)

**Comment by rafatower** [comment]
@saleiva I'd move this straight to the next sprint, unless this takes precedence on what was planned (I don't think so, the rest affects way more builder stability)
