### ISSUE TITLE
Maps from shared tables don't use table schema for instantiation 

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#9129]
In the **EDITOR** 

Maps created from a shared dataset don't use the schema in the default query. This prevents the map from working since the dataset cannot be found the user database.

## STR

1 - **user_1:** share a dataset with a colleague in the same org. 
2 - **user_2:** create a map from the shared dataset --> The map won't load and you will see an `error loading rows. Check your SQL query` message. Also `There is a problem with your connection` afterwards.
3 - Use the SQL editor to write: `SELECT * FROM user_1.table_name` (note that the schema was not present before) --> The map should load as usual

## Context

The request payload sent to the Maps API does not include the schema either

``` 
{version: "1.0.1", layers: [{type: "cartodb", options: {sql: "select * from world_borders_2",…}}]}
```

so the map instantiation returns an error: 

```
{"errors":["relation \"world_borders_2\" does not exist"] ...
```

**Comment by saleiva** [comment]
cc/ @juanignaciosl

**Comment by juanignaciosl** [comment]
Duplicated: #8974. Fix will be deployed today.
