### ISSUE TITLE
Use mapzen instead of our own geocoder for City Names option

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#9131]
Hey how does this sound? Doing this we can simplify our own geocoder and leverage on the synonims from mapzen. There have been several cases that I ended up using mapzen instead of our own geocoder because of this.

If sounds good, this would require changes on camshaft as well, but not on the UI.

**Comment by andrewxhill** [comment]
very nice, yeah

**Comment by AbelVM** [comment]
**Cool!!!**

Mapzen geocoder works great with [this list](https://github.com/CartoDB/data-services/files/415584/ALC_muni.csv.txt) of Alicante municipalities!! Current CARTO geocoder is not able to geocode more than a couple of them.

**Comment by ethervoid** [comment]
If I'm not wrong this is just for the Builder right?

**Comment by saleiva** [comment]
at every level I'd do it.

**Comment by saleiva** [comment]
open question, why do you thikn we shouldn't to this at the engine level?

**Comment by rafatower** [comment]
It'll be in the dataservices api so that it is available in the engine and for the builder via analysis layer (camshaft & friends)

**Comment by ethervoid** [comment]
Ok synced, that is what I'm doing. I have a bit of confusion with names. hehehe

**Comment by ethervoid** [comment]
This is test using list of official names of municipalities in Alicante province in Spain provided by @AbelVM 

![captura de pantalla 2016-08-26 15 57 22](https://cloud.githubusercontent.com/assets/741240/18007809/d82d08d0-6ba5-11e6-919c-bb1adf315e70.png)

Looks like we have some outliers with small towns but I've reported Mapzen about it.

**Comment by AbelVM** [comment]
Maybe places with the same name there. Did you test them like "WhateverName, Alicante, Spain" and failed anyway?

**Comment by ethervoid** [comment]
Yes they failed anyway, at least that which I tested.

**Comment by ethervoid** [comment]
Some numbers using staging ded04 server

Number of rows 141

### Internal

Time to execute the analysis: 623 milliseconds

Empty results 29:

```
 cartodb_id | code |                      name                       | country | the_geom
------------+------+-------------------------------------------------+---------+----------
          8 | 3008 | Alcoleja                                        | España  |
          9 | 3009 | Alcoy/Alcoi                                     | España  |
         11 | 3011 | Alfàs del Pi, l'                                | España  |
         14 | 3014 | Alicante/Alacant                                | España  |
         17 | 3017 | Alqueria d'Asnar, l'                            | España  |
         42 | 3042 | Benitachell/Poble Nou de Benitatxell, el        | España  |
         50 | 3050 | Campello, el                                    | España  |
         51 | 3051 | Campo de Mirra/Camp de Mirra, el                | España  |
         55 | 3075 | Castell de Guadalest, el                        | España  |
         65 | 3065 | Elche/Elx                                       | España  |
         70 | 3077 | Fondó de les Neus, el/Hondón de las Nieves      | España  |
         80 | 3082 | Jávea/Xàbia                                     | España  |
         81 | 3083 | Jijona/Xixona                                   | España  |
         82 | 3085 | Llíber                                          | España  |
         83 | 3084 | Lorcha/Orxa, l'                                 | España  |
         86 | 3089 | Monóvar/Monòver                                 | España  |
         87 | 3903 | Montesinos, Los                                 | España  |
         92 | 3094 | Nucia, la                                       | España  |
        104 | 3105 | Pinós, el/Pinoso                                | España  |
        106 | 3901 | Poblets, els                                    | España  |
        110 | 3110 | Ràfol d'Almúnia, el                             | España  |
        114 | 3114 | Romana, la                                      | España  |
        120 | 3122 | San Vicente del Raspeig/Sant Vicent del Raspeig | España  |
        132 | 3132 | Torremanzanas/Torre de les Maçanes, la          | España  |
        134 | 3134 | Vall d'Alcalà, la                               | España  |
        136 | 3137 | Vall de Laguar, la                              | España  |
        137 | 3135 | Vall d'Ebo, la                                  | España  |
        138 | 3138 | Verger, el                                      | España  |
        139 | 3139 | Villajoyosa/Vila Joiosa, la                     | España  |
(29 rows)
```

Result:

![captura de pantalla 2016-08-26 17 54 45](https://cloud.githubusercontent.com/assets/741240/18012025/e4052ba8-6bb7-11e6-9c38-5bc4cbdd9e3f.png)


### Mapzen

Time to execute the analysis: 26.324

Empty results 5:

```
cartodb_staging_user_fada02b1-a188-460d-a95c-c6b4e4cd9d83_db=# select * from analysis_d5b2dd1672_031e1717e130530bfbb45a2e977efb85f522f5d4 where the_geom is null;
 cartodb_id | code |     name      | country | the_geom
------------+------+---------------+---------+----------
          8 | 3008 | Alcoleja      | España  |
         33 | 3029 | Benigembla    | España  |
         72 | 3072 | Gaianes       | España  |
         97 | 3098 | Orxeta        | España  |
        108 | 3060 | Quatretondeta | España  |
(5 rows)
```

Result

![captura de pantalla 2016-08-26 17 55 57](https://cloud.githubusercontent.com/assets/741240/18012037/f12fe9da-6bb7-11e6-9f0a-2fb0208b972b.png)

**Comment by AbelVM** [comment]
Fast.
Accurate. 
Cheap.

But you can only have two of them  ¯\_(ツ)_/¯

**Comment by ethervoid** [comment]
I'm ready to release this change. @vhamer is there any update of terms or something that should be done related to this change?

**Comment by ethervoid** [comment]
Deployed.

**Comment by AbelVM** [comment]
BOOM

**Comment by rafatower** [comment]
https://github.com/CartoDB/dataservices-api/pull/265

**Comment by rafatower** [comment]
re: https://github.com/CartoDB/cartodb/issues/13354
