### ISSUE TITLE
Torque CDN URL composition doesn't work for shared tables

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#9134]
_Extracted from #9017, as a partial fix was deployed at #8991_.

The last tests of #8991 integrating all fixes revealed a last issue in staging: Torque still generates the wrong CDN request. [Example](https://juanignaciosl-ded-01.carto-staging.com/u/juanignaciosl-ded-01-1/viz/a667cde8-533c-11e6-a354-040120e0c101/map). It requests [a url based on the table owner](https://cdb-staging-1.global.ssl.fastly.net/juanignaciosl-ded-01-admin/api/v1/map/juanignaciosl-ded-01-1@03b6ae62@975860cc57a80183e1c8e4924a51839a:1469014073378/2/4/7/5.json.torque) instead of [the visualization owner](https://cdb-staging-1.global.ssl.fastly.net/juanignaciosl-ded-01-1/api/v1/map/juanignaciosl-ded-01-1@03b6ae62@975860cc57a80183e1c8e4924a51839a:1469014073378/2/4/7/5.json.torque).

It's probably because of [these lines](https://github.com/CartoDB/torque/blob/31a81e760b249e76b159c9966c219ae570f9acb3/lib/torque/provider/windshaft.js#L364-L389). The [backend patch that works without CDN](https://github.com/CartoDB/cartodb/pull/9112/commits/03d55781a20ca21a8feabbc8e494191d2df30a59#diff-5b802705d1b0026242a3fa27f9659720R144) can't be applied here.

PS: this only happens with named maps.

cc @javisantana

**Comment by juanignaciosl** [comment]
We'll add a `layer.options['visualization_user_name']` attribute to the v2 vizjson to be used by Torque.

**Comment by xavijam** [comment]
That's already working right?

**Comment by juanignaciosl** [comment]
No, it's not. Backend side was ready (CartoDB/cartodb/pull/9136), but Torque side was still missing.

**Comment by donflopez** [comment]
I've made @CartoDB/cartodb.js#1435 PR to fix this issue.

**Comment by xavijam** [comment]
With that fix it will be done @donflopez?

**Comment by donflopez** [comment]
I hope @xavijam! I need to try it with a real cdn.

**Comment by xavijam** [comment]
staging!

**Comment by inigomedina** [comment]
I'm closing this issue because it has been inactive for a long time. This probably means that it is not reproducible or it has been fixed in a newer version. If it's an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue.

Thank you!
