### ISSUE TITLE
Active state doesn't work (inputs)

### ISSUE THREAD

**Issue by urbanphes** [CartoDB/cartodb#9137]
When the input is active, the border should be blue 

Now it looks like

![image](https://cloud.githubusercontent.com/assets/14546701/17171826/a24d2684-53f2-11e6-9749-9962e00abdcf.png)
<br><br>
and should show:

![image](https://cloud.githubusercontent.com/assets/14546701/17171858/c004279a-53f2-11e6-9dd9-5de5571e80df.png)

**Comment by piensaenpixel** [comment]
@urbanphes this is working for me :(
![active](https://cloud.githubusercontent.com/assets/1214201/17320825/c75a260a-5895-11e6-9120-f740a5b0acd2.gif)
