### ISSUE TITLE
Cannot read property '0' of null bug

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#9155]
### STR

- Create a map with a dataset of polygons.
- Add a "Filter points in polygons" analysis.
- Select a `target layer`, any is fine.
- Don't apply the analysis.
- Go back to layers list.
- Try to add a new analysis, you can try with the same one.
- JS error should appear in the console: Cannot read property '0' of null

Seems like we are not removing target layers from analyses node collection.
We could check that and also be sure we take the proper letter from the nodes.

**Comment by viddo** [comment]
> Seems like we are not removing target layers from analyses node collection.

That should be fine, and in fact it was intended like that (to avoid duplicate nodes for the same secondary sources).

I'll fix the letter get to work as expected.
