### ISSUE TITLE
Implement endpoint to store the builder onboarding seen status

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#9157]
For the new builder onboarding (see https://github.com/CartoDB/cartodb/issues/8887) we need a new endpoint to store the seen status of the screen. This way, if the user checks the `Never show me this message` option we'll set certain flag to true in the user model, and we won't disturb he or her again.

**Comment by xavijam** [comment]
Backend?

**Comment by javierarce** [comment]
Yes, I was going to ask you to whom could I assign the ticket?

**Comment by xavijam** [comment]
hi @javitonino! :)

**Comment by xavijam** [comment]
Give him details in the description please :)

**Comment by xavijam** [comment]
I feel we should extend this functionality for other purposes, not only for builder thing, so take a moment for the implementation @javitonino.

**Comment by javitonino** [comment]
So current idea for implementing this is as follows:
- Create a new model, `UserNotification` which consists basically of a 1:1 reference to `User` and a JSON field to store notifications.
- Create new API to store notifications. This will be a PUT of the complete notifications JSON. Does it makes more sense for this to replace the data, or to merge it? Merging allows to include just the data that changed (the notification that was marked as do not show again), while replacing allows to delete keys.
- Include the notifications JSON in the builder .erb so it is available to the JS. Only needed in the builder view, right?

To be able to support different use cases (onboarding vs notification messages) without having to always set and retrieve the whole notification object, the plan is to separate the notifications in different categories, such as `builder` or `messages`. That way, the backend can pass only the necessary notifications for each view and the api calls only apply to the relevant category. The API's will have category as part of the URL.

```
PUT /api/v1/users/:id/notifications/builder
{
  "onboarding": {
    "import": {"show": false }
  }
}

---

PUT /api/v1/users/:id/notifications/messages
{
  "welcome_dashboard": { "read": true }
}
```

The database will store:
```
"builder": {
  "onboarding": {
    "import": {"show": false }
  }
},
"messages": {
  "welcome_dashboard": { "read": true }
}
```

When displaying a page, all of them will include `messages` (when that is implemented), but only the builder view will include `builder`, as that is only relevant there.

I think that covers everything that was needed. Thoughts?

**Comment by xavijam** [comment]
Oh, I like the idea of categorize the notifications, so :+1:

**Comment by xavijam** [comment]
Could this thing cover your expectations @javierarce?

**Comment by javierarce** [comment]
I think this is great.

Regarding your first question: for this particular case, merge and replace are both ok. I don't have any preference for the broad use of this feature right now, so pick whichever you want.

Regarding your second question, yes, currently we just need this in the builder view.

**Comment by javitonino** [comment]
Merged!

You should be getting the notifications in a `builderNotifications` variable. The API to update them is:
```
PUT (/u/user)/api/v3/notifications/builder
{ "notifications": {[...]} }
```

Let's try to agree on the format of the data that's stored inside. Although the backend won't be doing anything with it now, it would be good to have an extensible an easily parseable format in case we need to start doing so in the future (thinking of statistics gathering). I propose something like this, but you know the needs better than anyone:
```
{
  "onboarding": {
    "import": {"show": false },
    "add_layer": {"show": false }
  },
  "analyses": {
    "georeference": { "show": false },
    "point-in-polygon": {"show" : false }
  }
}
```

We have a categorization to easily separate onboarding from analyses, and inside each key we store if we want to show the message or not. It is inside a dictionary to allow expansion, which I thunk could be useful (but maybe I'm overengineering this).

**Comment by javierarce** [comment]
👍
