### ISSUE TITLE
Public pages refactor table/vis forking

### ISSUE THREAD

**Issue by Kartones** [CartoDB/cartodb#916]
Logic and when to clone/fork and when can't do it.

Current logic for cloning tables will ONLY work with organization users:
Processing by Api::Json::ImportsController#create as JSON
  Parameters: {"table_name"=>"public.xxxxx_copy", "sql"=>"select * from public.xxxxx"}
If we want to allow this in general, we need to use the SQL API, either directly or from the importer

**Comment by xavijam** [comment]
It will be fixed in the next iteration, and also with -> https://github.com/CartoDB/cartodb/pull/3632#discussion_r30303075
