### ISSUE TITLE
Cannot delete layers or add widgets under certain circumstances

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#9168]
Not sure about the STR, but I have a .carto (remember to rename the .zip to .carto before)
[Untitled Map (on 2016-07-28 at 15.19.17).zip](https://github.com/CartoDB/cartodb/files/388719/Untitled.Map.on.2016-07-28.at.15.19.17.zip)

![screen shot 2016-07-28 at 17 20 59](https://cloud.githubusercontent.com/assets/132149/17218336/ace36aa4-54e7-11e6-8369-287723b74066.png)

**Comment by viddo** [comment]
STR would be to delete layer C,

Expected result would be to fold its node (c2) under layer B, actual result is the error you're seeing.
I've managed to reproduce it locally in an isolated test case (thx for the .carto file!), from investigating so far I think the error is related to nodes not being renamed properly (created a node that references itself, hence the infinite loop). WIP 🚧

**Comment by viddo** [comment]
> or add widgets under certain circumstances

Do you have any more information about this? Nodes might not be available if they're not compatible with the widget type (or the geometry is unknown).
