### ISSUE TITLE
Auth tokens in vizjson3 present in privately shared visualizations

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#9174]
A bit of context. Auth tokens are used to authenticate calls to the tiler, and are used in two cases:
 - Password-protected visualizations
 - Private visualizations shared within the organization

In vizjson2, the password protected visualizations include the necessary tokens in the vizjson, and the shared visualizations include it in the embed/public view like so:
```
map_options.auth_token = [];
map_options.auth_token.push('Fv7Wi4BsA6tCNaN7r2qGtg');
map_options.auth_token.push('XVQSox-kPIvk77kJh6ph-g');
map_options.https = true; // when auth_token is used tiles should be fetch using https
```

However, in vizjson3 and the new embed, both cases are handled by including the tokens in the vizjson. This has a serious implication, all the auth tokens allowed for the visualization are included, so you can see the auth tokens for the whole organization in the vizjson.

This was introduced here as a hotfix for password protected embed: #8660 that produces auth tokens in the vizjson for privately shared visualizations. Reverting this (well, without breaking what it was fixing) is not enough, as that leaves no way to pass the auth tokens for privately shared visualizations to cartodb.js.

I don't know exactly how cartodb.js v4 handles this, but there is probably an option to the `createVis` call. We would need to write the tokens to the page and modify the public js to pass it to cartodb.js.

Maybe we can do this entirely in backend, including the tokens from the viewer user in the vizjson, but that makes little conceptual sense to me, and we must be careful with caching in that case. I'd avoid this.

cc @alonsogarciapablo @xavijam @juanignaciosl

**Comment by alonsogarciapablo** [comment]
At the CartoDB.js level, [we're currently using the first authToken that is included in the viz.json](https://github.com/CartoDB/cartodb.js/blob/v4/src/api/create-vis.js#L36). It wouldn't be hard to add an option to `createVis`... We could even remove authTokens from viz.json and make the `createVis` option required in these cases...

**Comment by javitonino** [comment]
Removing `auth_tokens` from the vizjson, would also imply for password protected visualizations, we would have to include the auth tokens in the embed (could be done).

Also, we have to think about how all the changes proposed here affect cartodb.js applications created by the users, as they would have to add the auth token manually (and we don't have it displayed anywhere in the UI). I think doing the changes only for vizjson v3 and new embeds should be safe enough.

With the changes I proposed in #9175, the fact that cartodb.js uses only the first token can be a problem, as we need to be able to send the user or org token depending on what the visualization has applied permission to. We can try to detect in the backend which is the more adequate token, or maybe even modify the tiler to accept multiple tokens and check if any of them matches.

**Comment by alonsogarciapablo** [comment]
cc: @javisantana @rochoa

**Comment by javisantana** [comment]
> This has a serious implication, all the auth tokens allowed for the visualization are included, so you can see the auth tokens for the whole organization in the vizjson.

why this is a serious problem? the organizations tokens are for stuff that is share for all the organization and that viz.json can only be seen if you have the password or you are authenticated.

**Comment by javitonino** [comment]
You can see the tokens for all the users this visualization has been shared with, so you can potentially see visualization which have been shared with other users but not with you.

Maybe it was exaggerating to say serious, as permissions are checked by the backend before showing the embed. But it makes the auth token system almost worthless in organizations (specially when combined with #9175), as you can easily get tokens for other users.

**Comment by javisantana** [comment]
> You can see the tokens for all the users this visualization has been shared with 

so that's the real problem, why do we send those?

**Comment by javitonino** [comment]
It looks like a behaviour change, I think it is pretty safe to roll it back. They should not be sent in the vizjson, but rather sent independently in the embed, with the tokens specific to the logged in user. We would have then to pass the auth tokens in the embed itself, in the `createVis` call to cartodb.js. We need cartodb.js support for passing that as options in the creation call. I talked with @alonsogarciapablo, it was removed from v3 to v4, but should be easy to add back.

We can even think about passing the tokens for password protected maps the same way: as a separate object in the embed, instead of including them in the vizjson. This forces all cartodb.js app creators to specify the token on the `createVis` call instead of inside the vizjson, which I think makes more sense. But all that is optional, not really needed to solve the issue.

**Comment by javitonino** [comment]
Talkes with @javisantana. We should also move the auth tokens for password protected visualizations to the embed. So no more auth tokens in the vizjson (v3 at least),

**Comment by alonsogarciapablo** [comment]
I too think/agree that adding an `authToken` option to `createVis` is a good way to proceed 👍

**Comment by javitonino** [comment]
@alonsogarciapablo I am going to start working on this. Can you prepare (or help me prepare) a cartodb.js v4 branch that takes the tokens from the options to test this with?

**Comment by alonsogarciapablo** [comment]
@javitonino, I opened https://github.com/CartoDB/cartodb.js/pull/1377. Branch is `auth-token-as-option`.
