### ISSUE TITLE
Join notifications

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#9177]
if you add some widgets together there are many notifications

![adding-widgets](https://cloud.githubusercontent.com/assets/1214201/17254090/a1ed22ee-55b3-11e6-931e-ef07399c9c84.gif)

**Comment by urbanphes** [comment]
I think we should notify similar to:

1. Adding widgets ...
2. Widgets were been added successfully

... and leave one notification.

**Comment by nobuti** [comment]
Closing in favor of https://github.com/CartoDB/cartodb/issues/9581
