### ISSUE TITLE
[dataservices] Areas of interest - HERE taking very long to be uploaded

### ISSUE THREAD

**Issue by miguelarias** [CartoDB/cartodb#9180]
I am trying to do the following: 

1. Upload a set of 150 starbucks in Oregon
2. Create AOI (time 600 secs - walk) for those points
3. Upload a set of potential customers in Oregon
4. Intersect those AOIs with the customers to see how many of those are covered by each AOI
5. Add some widgets to the dashboard with more info (customer value, etc)

When I run the AOIs, it takes hours with the 150 and it doest finished (the wheel keeps spinning). If I use a sample of 15 location, it takes around 4 minutes, and then it finally displays the poligones. 

Isn't this too slow?, is this working as expected?. If you could check if nothing is wrong, we could maybe add a message to the analysis saying that the estimate finish time of the analysis is X minutes, to control expectations. 

And the notification with the: 

CONFIRM YOUR ANALYSIS

This might incur into an extra cost. Extra credits will be charged at $20/1000

Is not going away, no matter how many times I click on apply, see screenshot.

Thanks team!
miguel
![screenshot 2016-07-31 09 11 36](https://cloud.githubusercontent.com/assets/7315954/17276808/54e955ea-5701-11e6-95d3-fd91abe26c93.png)
[Starbucks_in_the_Portland.zip](https://github.com/CartoDB/cartodb/files/392423/Starbucks_in_the_Portland.zip)
[customer_home_locations.geojson.zip](https://github.com/CartoDB/cartodb/files/392424/customer_home_locations.geojson.zip)

**Comment by ethervoid** [comment]
Until today our org was using mapzen as isolines provider and it takes a huge amount of time, we're working on it. This morning I've changed to heremaps so if you redo the analysis should work without problems using heremaps

**Comment by xavijam** [comment]
Yeah, also this credits info will be shown only when HERE is selected/enabled, taking care of that in -> https://github.com/CartoDB/cartodb/issues/9190.
