### ISSUE TITLE
Search for TAG only works if you include a colon(:) in front of search term

### ISSUE THREAD

**Issue by csobier** [CartoDB/cartodb#9181]
This comes from a Support reported issue about searching by TAGS...

When using the Datasets or Maps dashboard to SEARCH by TAGS, you have to enter a colon in front of the text, (Example, `:text`), otherwise no search results appear. This is not intuitive. Is this intentional by design, or a bug?

![image](https://cloud.githubusercontent.com/assets/13319925/17279565/4d41d968-5745-11e6-8155-3c431b7e3462.png)

**Comment by xavijam** [comment]
This is on purpose, we have worked with that since first version of cartodb.

**Comment by csobier** [comment]
Okay, thanks for confirming. I'll doc this as the intended behavior.
