### ISSUE TITLE
[publish] Styles for a layer in the builder are not kept in the public viz

### ISSUE THREAD

**Issue by miguelarias** [CartoDB/cartodb#9182]
I finished an actionable dashboard with a few layers and analysis, and I am trying to publish the results. I made the data public and got the public link. But when I share it, it is not including the style I defined for one of the layers. See screenshots below to see the difference between builder and public viz.

Thanks!
Miguel
![screenshot 2016-07-31 19 46 52](https://cloud.githubusercontent.com/assets/7315954/17280190/da2a2a80-5757-11e6-9b24-56662db1c576.png)
![screenshot 2016-07-31 19 49 22](https://cloud.githubusercontent.com/assets/7315954/17280194/e643ac42-5757-11e6-88b5-a1975c1e2c63.png)

**Comment by miguelarias** [comment]
Actually, looking in detail, it is displaying the customer_home_location layer in the public view, which I made not visible in the first place.

**Comment by xavijam** [comment]
@miguelarias, take into account we have the new share functionality, until you don't click over PUBLISH button in the share view, your public embed will not be refreshed with your last changes.

**Comment by saleiva** [comment]
@miguelarias it's a known bug. Hidden layers are shown on the embeds. As a workaround you can make the points transparent
