### ISSUE TITLE
points cropped with map view

### ISSUE THREAD

**Issue by alexhsieh-handy** [CartoDB/cartodb#9183]
![screen shot 2016-08-01 at 2 33 42 pm](https://cloud.githubusercontent.com/assets/18277947/17285420/2990e116-57f5-11e6-827b-731dbcb43f95.png)

![screen shot 2016-08-01 at 2 34 07 pm](https://cloud.githubusercontent.com/assets/18277947/17285456/5ba5cf22-57f5-11e6-80f5-5acc68190fca.png)

points cropped as screencap, any advise?

**Comment by rochoa** [comment]
Is that a local installation or carto.com hosted version?

**Comment by alexhsieh-handy** [comment]
local installation

**Comment by rochoa** [comment]
Can you check you don't have a low row limit: https://github.com/CartoDB/Windshaft-cartodb/blob/6597851b480ceb3712d7751c5092a300daac64f7/config/environments/development.js.example#L65 ?

**Comment by alexhsieh-handy** [comment]
row_limit: 65535,
but my dataset contains 17m rows
will this cause the problem?

**Comment by rochoa** [comment]
That configuration value limits the number of features that can be rendered by [meta]tile. That's, probably, why you are having some points missing in one of the tiles because that tile is already rendering 65535 features.

If you want to render all of them (I don't encourage that if you have 17M rows), simply use row_limit: 0.

I just added a comment to the configuration examples to clarify that config parameter: https://github.com/CartoDB/Windshaft-cartodb/commit/25de018f7dd024800c3ecd869ad9d6b818163f56.

HTH.

**Comment by alexhsieh-handy** [comment]
i still getting the same result even row_limit: 655350000000

**Comment by alexhsieh-handy** [comment]
i have turned row_limit to 0,
but the point cannot be rendered , some error shown from my browser console
Failed to load resource: the server responded with a status of 502 (Bad Gateway) http://xxxxxxxxx/user/dev/api/v1/map/adb5b045fb8840f6ef5e2f281e906878:147…c0f5&api_key=xxxxxxxxx&cache_policy=persist 

i have tried to set the timeout in config.socket_timeout and renderer.http.timeout to a very big value, but still no luck

**Comment by rochoa** [comment]
About the 502 error: are you running it behind a reverse proxy?

Have in mind that point rendering takes linear time, if you have a lot of points behind a tile it will take a lot of time to render it.

**Comment by alexhsieh-handy** [comment]
ya, i am running with nginx and already set the timeout to an hour, is there any timeout setting i may missed? i am actually using https://hub.docker.com/r/sverhoeven/cartodb/

**Comment by alexhsieh-handy** [comment]
@rochoa 
i have tried to config the map api serve from 8181 directly instead of nginx, 
some png still cannot load Failed to load resource: net::ERR_EMPTY_RESPONSE

**Comment by rochoa** [comment]
You are probably hitting other limits, like database statement timeout. Do you know how many points are in those tiles? Do you really need to render all of them?

**Comment by alexhsieh-handy** [comment]
still cannot works with my dataset, checked no statement timeout, and no error log generated from  postgresql

**Comment by rochoa** [comment]
I encourage you to try to isolate the debugging on of the failing requests. I usually do it by using "Copy as cURL": https://daniel.haxx.se/blog/2015/11/23/copy-as-curl/.

**Comment by alexhsieh-handy** [comment]
![screen shot 2016-08-05 at 6 03 01 pm](https://cloud.githubusercontent.com/assets/18277947/17433477/78a47f0c-5b37-11e6-8e45-7ec4040f54bd.png)
seems there are a 2 mins timeout , do you have any idea? thanks a lot!

**Comment by rochoa** [comment]
That's most likely a Google Chrome client timeout. That's why I suggested using cURL to replay the requests.
