### ISSUE TITLE
"Applying query" message gets stuck after applying SELECT * query

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#9184]
### STEPS

* Add a `layer` to a map.
* Apply `SELECT * FROM layer`.
* The "Applying query" message gets stuck, as shown in the following screenshot:

![applyingquery](https://cloud.githubusercontent.com/assets/5215798/17287919/adce0184-57d2-11e6-9fd2-d07ba3768abc.png)

### CONTEXT

* With some queries, the notification area shows `SQL query applied` and then disappear as expected. **This only happens sometimes**, and we couldn't find a clear pattern. Examples: 
  * queries with `WHERE` clauses
  * queries with `LIMIT n`

**Comment by ernesmb** [comment]
In case it helps to identify the problem:

adding a `WHERE` clause to the query makes the notification behave as expected (shows `SQL query applied` and disappear)

**Comment by ramiroaznar** [comment]
@ernesmb I am not quite sure. Look at this screenshot (the query was applied 1 minute ago):

![where](https://cloud.githubusercontent.com/assets/5215798/17288265/72cbae4a-57d4-11e6-83ca-20fcfce516aa.png)
