### ISSUE TITLE
Centroid analysis fails if the layer was previously styled with a ramp

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#9185]
STR:
 - Create a map
 - Style the layer with a ramp on a number (it will fail first time due to #9179)
 - Create a centroid analysis
 - Apply, it will fail with `point.fill.size is undefined` (more info on track.js)

![output](https://cloud.githubusercontent.com/assets/7569673/17288057/4d9030f2-57d3-11e6-976c-439552cd7a4e.gif)

cc @xavijam @viddo

**Comment by viddo** [comment]
> Apply, it will fail with point.fill.size is undefined (more info on track.js)

I have a fix for this err in #9178, I'll review this.

**Comment by viddo** [comment]
Confirmed working on #9178 🎉 
Thx for the report btw! 🙇

**Comment by javitonino** [comment]
Great news, closing it then as that branch has just been merge. Talk about quick response times :smile:
