### ISSUE TITLE
[Metrics] Add 'age' attribute to deletion-related events

### ISSUE THREAD

**Issue by jmartinter** [CartoDB/cartodb#9191]
Add new attribute 'age' (calculated as 'deletion time' - 'creation time', in days) for following events:
 - Deleted dataset
 - Deleted map

This shouldn't be difficult as both maps and datasets have a created_at property.

**Comment by saleiva** [comment]
No, no. Age is the age of the user

**Comment by jmartinter** [comment]
Maybe 'lifetime'?

**Comment by saleiva** [comment]
Ok

**Comment by gfiorav** [comment]
Hey @jmartinter,

What if I just include a `created_at` property for dataset/visualizations? Then you could compute the lifetime easily with a query right? 

Would that do?

**Comment by jmartinter** [comment]
@gfiorav: I'm afraid the API we use for querying events is quite limiting and it doesn't allow to compute fields on-the-fly. We can only filter by existing fields : (

**Comment by saleiva** [comment]
hey @jmartinter remember that the interesting data here is the lifetime of the user

**Comment by jmartinter** [comment]
hey @saleiva
 
No, this attribute states how long a map or dataset has existed in the system. I'm interested in identifying when a customer removes old data (maybe he's out of space or, worse, he's cleaning before churning)

If you feel the 'lifetime' of the user can be useful to segment the events, we can add it as well, as another  attribute.

**Comment by gfiorav** [comment]
Hey @jmartinter,

I just noticed you want the lifetime in days. Are you sure? Don't we want minutes at least?

I defaulted to seconds, although that is too much granularity probably. If you want me to change it, it's a commit and then to prod on https://github.com/CartoDB/cartodb/issues/9244

**Comment by saleiva** [comment]
ok!

**Comment by saleiva** [comment]
but we need the lifetime of the user for all the mockups I prepared @jmartinter
