### ISSUE TITLE
Do not use table cartocss when creating a visualisation

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb#9192]
When creating a new visualisation from a table we should not use the cartocss associated to it as it might depend on some wizard, at the table level, from the old editor.

Reference: https://github.com/CartoDB/cartodb/issues/8390#issuecomment-236555653.

cc @AbelVM

**Comment by saleiva** [comment]
We should use it, its a feature, but we might need migrations for old styles.

The idea here is to have canonical styles for the layers so when added they are always styled in the same way. This is a request also by some clients

**Comment by rochoa** [comment]
The problem is that it's not possible to change the cartocss/wizards from a table view with the new builder, so if your wizard/cartocss is not compatible you cannot use that table, neither you can modify its cartocss/wizard to make it compatible.

**Comment by saleiva** [comment]
It will be. That workflow is still to be implemented. Some clients have pre-styled layers already

**Comment by rochoa** [comment]
Oh, then I'm sorry, but I didn't know we were adding support for that.
