### ISSUE TITLE
Switching the basemap very quickly creates multiple labels layers

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#9193]
**Steps to reproduce:**

- Enable network throttling in your inspector:
  <img width="416" alt="screen shot 2016-08-01 at 13 15 54" src="https://cloud.githubusercontent.com/assets/390398/17292425/353937da-57ea-11e6-9143-03fc6bec4c01.png">
- Open a map.
- Click on the base layer.
- Switch quickly, and multiple times, between a basemap with labels and a basemap with no labels on top.
- Refresh the page.

**Expected result:**
- There is a single layer with labels.

**Actual result:**
- There are multiple labels layers:
<img width="433" alt="screen shot 2016-08-01 at 13 14 48" src="https://cloud.githubusercontent.com/assets/390398/17292491/bc5b9a1e-57ea-11e6-8b08-459a5143f2b5.png">

I think the problem is the following:

1. A basemap with labels is selected -> A request to create the labels is triggered.
2 A basemap with no labels is selected -> [We try to destroy the labels layer](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb3/data/layer-definitions-collection.js#L207).
3. The request from 1. finishes and the labels layer is there.

In the past, we talked about disabling the "basemap" selector while basemap is begin changed (i.e: requests are still running). I think that's how we solved this in the "old" editor.

Also, this might be why the map in https://github.com/CartoDB/cartodb/issues/9111 got screwed up.

cc: @matallo @xavijam

**Comment by matallo** [comment]
on it

**Comment by xavijam** [comment]
Important in order to prevent those kind of issues, already discussed with master @matallo.
