### ISSUE TITLE
Infowindow hint template rendered wrongly

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#9199]
STR
- Create a new map for a point dataset
- Enable pop-up (which style doesn't matter)
- Click a point

Actual result: 
- ![screen shot 2016-08-01 at 16 14 29](https://cloud.githubusercontent.com/assets/978461/17296863/80984c8e-5803-11e6-9b33-662d5ea28099.png)

Expected result:
- A popup with some hint text

**Comment by viddo** [comment]
@matallo didn't find any existing issues so not sure if it's a known or not, if there is one feel free to close it.
Looks like a typical double-escaping done somewhere.

**Comment by xavijam** [comment]
Taking care of it -> https://github.com/CartoDB/cartodb/pull/9201
