### ISSUE TITLE
Improve geometry discovery in query-schema-model?

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb#9207]
Is there any reason we have to keep requesting for the full geometry and parse it client side? Could we wrap the query to ask just for the geometry type?

https://github.com/CartoDB/cartodb/blob/51f3113f293b56a748a70a0a71d3e4a37ec7bae9/lib/assets/javascripts/cartodb3/data/query-schema-model.js

**Comment by xavijam** [comment]
we use this model to get the schema and the geometry type in only one request. Any better idea?

**Comment by viddo** [comment]
Also there's #8827 in the pipeline, to persist the geometry once known.

**Comment by xavijam** [comment]
Already fixed getting in another way https://github.com/CartoDB/cartodb/pull/9472.
I love you guys! closing

**Comment by viddo** [comment]
:ok_man:
