### ISSUE TITLE
Clicking zoom control buttons does not show unpublished changes dialog

### ISSUE THREAD

**Issue by csobier** [CartoDB/cartodb#9208]
Once you make any change that modifies your original map, the Builder indicates that there are unpublished changes. Exception applies when using the zoom control increase (+) /decrease (-) buttons.

![image](https://cloud.githubusercontent.com/assets/13319925/17302198/1907c672-57e9-11e6-8480-085b986b75c0.png)
- I know that I can change the zoom level and republish my map if I want to display a new default zoom level
- However, no confirmation dialog appears when changing the zoom level? It might be helpful to show that there are unpublished changes, as I wasn't sure and had to test my published output. (It works! But the dialog would have reminded me to republish)

**Comment by saleiva** [comment]
Neither is updated with moving the map
