### ISSUE TITLE
Reset styles when changing analysis parameters affecting style by value

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#9215]
STR:
- Create an intersection between 2 layers aggregating by count
- Style the polygon layer with by value with the count_vals_density for example
- Change the parameters of the analysis to do the avg(another_column)
- Analysis will fail.

It shouldn't fail, it should reset the styles on the polygon layer ONLY when the columns that are being use are not present anymore.

**Comment by xavijam** [comment]
Hum..., pandora box.

**Comment by xavijam** [comment]
This is already fixed https://github.com/CartoDB/cartodb/pull/10462. 💃
