### ISSUE TITLE
Add publishing option for hiding lateral(blue) bar

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#9223]

**Comment by saleiva** [comment]
@xavijam can we prioritize this?

**Comment by saleiva** [comment]
moved, just in case.

**Comment by xavijam** [comment]
@nobuti will make his magic adding it in the current PR about legends config too, so...

**Comment by saleiva** [comment]
OMG

**Comment by nobuti** [comment]
This is going to be shipped with #9911

**Comment by saleiva** [comment]
@noguerol is going to be soooooo happy.

**Comment by nobuti** [comment]
Already in production.
