### ISSUE TITLE
Check for ready state before requesting data for table view?

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#9225]
From https://github.com/CartoDB/cartodb/issues/9042#issuecomment-236865380
On doing the STR of that issue, it were noticed that the [table-view](https://github.com/CartoDB/cartodb/blob/58a1651afa6fded50426b0b1e53ffbf013344a87/lib/assets/javascripts/cartodb3/components/table/table-view.js#L116-L121) does a possible "pre-mature" request to get data for the analysis. 

It should wait until there's data available, by checking `querySchemaModel.get('ready')` to be `true`. If it just needs the schema (columns) it's not necessary though.

**Comment by saleiva** [comment]
Already done!
