### ISSUE TITLE
[Usability] Saving a stage of a dashboard before hitting the "back" button

### ISSUE THREAD

**Issue by miguelarias** [CartoDB/cartodb#9230]
I am not sure if this is a feature request or a bug, let me explain for you. 
You may inadvertently hit "back" in the browser (or do it by using 2 fingers in the touchpad) and when you go back to your visualisation, it is not stored as expected. It might have stored a previous step or nothing at all.

This is causing some issues in real time demos, where you are in the middle of the DEMO and suddenly you have lost all your previous steps (by hitting back) and need to start over again.

Cheers
Miguel

**Comment by xavijam** [comment]
Which kind of steps have you missed? We (hopefully) release a new feature, that take care of the state of the widgets, for example, if you filter over a histogram, once you reload the browser or get back to the map, that widget will appear with the previous state. (https://github.com/CartoDB/cartodb/pull/8584)

**Comment by miguelarias** [comment]
Most of the visualisation I was working on is lost. Some of the previous analysis are not there in the workflow anymore, widgets I added, or styles I added are gone.  (this has happened almost everytime, so I can reproduce it for you if you want!)
