### ISSUE TITLE
"nodeTitle is not defined" error when adding "Join columns from 2nd layer" analysis

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#9240]
How to reproduce it:

1. Create a map with one layer.
2. Add a `Join columns from 2nd layer` analysis

The dev console will show the error `nodeTitle is not defined`

**Comment by viddo** [comment]
Ouch, related to #9173 for sure, I'll take this one

**Comment by javierarce** [comment]
@viddo: 👌  thanks!
