### ISSUE TITLE
sql queries in the builder do not allow semi colons

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/cartodb#9245]
Semicolons (`;`) are a [common character](https://www.postgresql.org/docs/9.5/static/sql-syntax-lexical.html) in chained SQL queries. Currently the builder does not allow a query if the semi colon (`;`) is present, though:

```
SELECT * FROM vonnegut_books;
```

Results in: `Syntax error: syntax error at or near ";"`

The Editor did not complain about the `;`, although [Kurt Vonnegut did](http://www.goodreads.com/quotes/17178-here-is-a-lesson-in-creative-writing-first-rule-do).

**Comment by saleiva** [comment]
I think this is dupe! cc/ @xavijam

**Comment by xavijam** [comment]
Duplicated -> https://github.com/CartoDB/cartodb/issues/9071
