### ISSUE TITLE
Map onboarding wrong timing

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#9251]
STR

1. Click "New map"
2. Click "Connect dataset"
3. Click "Dropbox". An onboarding modal is shown:

![screen shot 2016-08-03 at 09 26 30](https://cloud.githubusercontent.com/assets/932968/17357377/99a0b6da-595c-11e6-9095-7786bb4dc0a7.png)

Nevertheless I think that it should've appeared at 1.

cc @xavijam

**Comment by saleiva** [comment]
I propose we just remove all this, since we will implement new onboarding methods soon

**Comment by xavijam** [comment]
But @juanignaciosl, this appears in the dashboard window or in the builder window.

**Comment by xavijam** [comment]
For me it appears correctly in the dashboard:

<img width="1440" alt="screen shot 2016-08-03 at 10 08 35" src="https://cloud.githubusercontent.com/assets/132146/17358429/4ab1b690-5962-11e6-9686-1ff26b59930e.png">

**Comment by juanignaciosl** [comment]
@xavijam at the dashboard, reproduced in production.

**Comment by xavijam** [comment]
Ok, I'll take a look with @piensaenpixel then, thanks @juanignaciosl :kiss:

**Comment by saleiva** [comment]
Seriously, remove this!

**Comment by xavijam** [comment]
:+1:
