### ISSUE TITLE
Hover pop-up is not updating changes

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#9256]
When creating a hover pop-up reordering items or changing their name wont update them in the info window.

1. Activate hover pop-ups
2. Select items
3. Reorder items / change their names
4. Bad news: they won't update

![captura de pantalla 2016-08-03 a las 10 52 44 2](https://cloud.githubusercontent.com/assets/70603/17359950/4962b490-5969-11e6-97a7-34eef5a83d03.png)

**Comment by matallo** [comment]
can't reproduce, is this still happening?
