### ISSUE TITLE
Make state changes atomic

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#9257]
See #7608 where this was discussed earlier. As mentioned there, the current implementation could leave a viz in a inconsistent/faulty state.
I've already received some reports on this and seen issues on TrackJS, but due to lacking STR most of them don't have any issue created. For examples of reported issues see:
- #9168 Cannot delete layers or add widgets under certain circumstances 
- #9148 Layers lost and map stop working when creating a layer when dragging an analysis node
- #9246 Dragging out a analysis to make a new layer and then deleting that layer makes map unloadable
- #9450 Could not delete node, because widget had a undefined source (a widget should always have a source, or be deleted when its source is deleted)

The solution would be to make sure this kind of operations can't lead to a invalid viz state, i.e. we need some way of doing this in a transactional way and have some error handling.

Would also make some issues obsolete/close #8846 and #8783 

cc @xavijam @gfiorav @alonsogarciapablo

**Comment by alonsogarciapablo** [comment]
+1
