### ISSUE TITLE
[Metrics] Add new 'Added analysis' event

### ISSUE THREAD

**Issue by jmartinter** [CartoDB/cartodb#9264]
Generate an event each time a user adds an analysis to one of his maps in the Builder.

Event attributes:
- normal user properties (id, username, email, plan, ...)
- Type of Analysis
- Id of analysis (A1, ...)
- Time it took (great if we can get it)

**Comment by gfiorav** [comment]
As we spoke:

Let's leave this for when analyses logic lives in the back (next milestone).

**Comment by gfiorav** [comment]
Hi!

We're doing this now. 

> normal user properties (id, username, email, plan, ...)

Consider it done.

> Type of Analysis 

Yep!

> Id of analysis (A1, ...)

Sure!

> Time it took (great if we can get it)

I'm afraid not ATM.


How about visualization? don't you want those properties as well?

**Comment by jmartinter** [comment]
Sure, good point!

**Comment by gfiorav** [comment]
As we discussed offline: I'm implementing 3: 

- Created analysis
- Modified analysis
- Deleted analysis

**Comment by gfiorav** [comment]
Closed via https://github.com/CartoDB/cartodb/pull/9617
