### ISSUE TITLE
[Metrics] Add new 'Published map' event

### ISSUE THREAD

**Issue by jmartinter** [CartoDB/cartodb#9265]
Generate a new event each time a user generates a new version of the map.

Event properties to track:
 - Usual user properties (id, email, username, plan, ...)
 - Version number (I don't know if we store this)
 - Type of publish (link, embed, carto.js, mobile... I don't know if we can have this)

If the last two properties are costly to get, we can continue without them at this moment.

@gfiorav

**Comment by gfiorav** [comment]
> Usual user properties (id, email, username, plan, ...)

Ok.

> Version number (I don't know if we store this)
> Type of publish (link, embed, carto.js, mobile... I don't know if we can have this)

Version number is just counting this events (event 3 is version 3 published) and the type (like we discussed) it going to be just when maps are freezed.
