### ISSUE TITLE
custom html infowindows are not displaying the values of the changed field

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartodb#9268]
### Summary

When you create an infowindow using the menu and then you open the html view of the infowindow to edit one of the fields, the values of the changed field are not being displayed on the map.
### Steps

1- Create an infowindow with one or two fields enabled.

![screen shot 2016-08-03 at 13 49 34](https://cloud.githubusercontent.com/assets/11177693/17364597/53ad2418-5981-11e6-86e2-8efb6e17680d.png)

2- Go to HTML view of the infowindow to see the HTML code of the infowindow created in step 1

![screen shot 2016-08-03 at 13 49 52](https://cloud.githubusercontent.com/assets/11177693/17364600/5a6174e4-5981-11e6-8017-18065c152967.png)

3- Change the name of one of the fields for another field of the layer (we have changed the field "iso2" to "name" field, both fields belong to the world_borders layer)

![screen shot 2016-08-03 at 13 56 27](https://cloud.githubusercontent.com/assets/11177693/17364719/23f0e51a-5982-11e6-99a7-26c6861004c8.png)

The infowindow is not showing the values of the changed field.

**Comment by saleiva** [comment]
Already fixed!
