### ISSUE TITLE
Exclude users already in group from add user modal

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#9272]
In the modal to add users to an existing groups, all users in the organization are listed. It would be nice to exclude users already in the group.

The filtering could be done on frontend, or added as a parameter to the organization users controller.

**Comment by saleiva** [comment]
But them you could not share a map with a user that is within a group without sharing it to the whole group. Part of the issue cleanning session

**Comment by javitonino** [comment]
Not talking about the map sharing window, but the window to add users to an existing group.

**Comment by juanignaciosl** [comment]
Closing automatically because of inactivity. If anybody considers that this still important, please reopen and it'll be prioritized.
