### ISSUE TITLE
Add predominant value as aggregation method on the popup component

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#9277]
Useful for intersections for example where we want to calculate the most popular category within a polygon from a point dataset.

For the time being I'd only add to the intersection analysis and to the admin aggregation wizard.
This would enable in the UI the use case of using formula widgets with string columns.

cc/ @rochoa @stuartlynn

**Comment by stuartlynn** [comment]
👍 Sounds great to me. I think this is something that will be really useful. Something related would be the % of a given class that occurs within the polygon. So basically a count for each unique label in a column divided by the total number of points.
