### ISSUE TITLE
If query results are the same than the previous one, query notification does not disappear

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#9279]
## STR
- Create a map with a dataset of points (twitter_t3chfest_reduced, from the data library, for example).
- Go to the builder.
- Open the SQL editor.
- Apply this query: SELECT * FROM twitter_t3chfest_reduced WHERE cartodb_id is NOT null
- Check that query doesn't disappear.

I don't know why we are taking into account the vis for hiding the notification, why don't we check just the query applied? Because right now map is being rendered all the time, but if we remove the map when table is displayed, what will we do?

cc @alonsogarciapablo @nobuti

**Comment by nobuti** [comment]
Because of this comment https://github.com/CartoDB/cartodb/issues/7985#issuecomment-232717616, I didn't take into the account the dataset part.
