### ISSUE TITLE
Cannot read property 'fixed' of undefined

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#9285]
STR:
- Create a new map from a dataset that have polygons
- Go to style tab
- Add an analysis that outputs polygons (e.g. area-of-influence)

Expected result:
- All working as expected

Actual result:
- Exception thrown, `Cannot read property 'fixed' of undefined`

**Comment by xavijam** [comment]
Yeah, this is trending in TrackJS, hope we find the steps to reproduce consistently.
