### ISSUE TITLE
DEFAULT_SELECT in Carto::User

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#9291]
Follow up from: https://github.com/CartoDB/cartodb/pull/9274/files/d2f647894deaf6a13188269d506a8f8bfbc22abc#r73366547

There, I proposed getting rid of `DEFAULT_SELECT` in `Carto::User`, as it is only used when following two associations: vis->user (DEFAULT_SELECT) and permission->user (SELECT_WITH_DATABASE). It makes reasoning about the code harder, because the model will have different fields loaded depending on where it comes from.

It is also the likely culprit of this issue: https://rollbar.com/vizzuality/CartoDB/items/19657/occurrences/14987729788/
You can see in the JSON for `person` that the fields included there match the fields in `DEFAULT_SELECT`. It should not happen though, because in that branch of the code, the user is extracted following layer->map->user, which should load the full user model. I don't know why it sometimes, it only loads the default fields. AR caching maybe? I haven't been able to consistently reproduce, it seems random.

This was originally introduced for security/performance. IMHO, performance should not be a problem (the DB has to load the entire disk page anyway) and security (regarding exposing private information) should not be handled here (it is the job of the controller/presenter). It only affected some associations anyway, so I feel the point is moot.

I think we should remove it as I don't feel it is adding much, but makes the code harder to read and may be causing some issues.

cc @juanignaciosl @gfiorav

**Comment by juanignaciosl** [comment]
I could agree on removing it. But there's many columns that we know that will never be used in a user coming from an association: `crypted_password`, `salt`, `invite_token`, `invite_token_date`, `period_end_date`, `dashboard_viewed_at`... My concern is that `users` is _really_ big and this might not be a _micro_ optimization, we might be able to get rid of ~50% of the columns, probably. 

Nevertheless I have mixed feelings, as I fully agree with your argument. Removing it is also fine. Let's @gfiorav vote decide :-)

**Comment by javitonino** [comment]
If this is really a performance problem, then we should really be adding `DEFAULT_SELECT` to all associations, and I would say adding the `SELECT_WITH_DATABASE` ones plus `auth_token` that I can think of right now. At least the database thing I would say it is important, as many times you get an user from another object is to run a query on the dataset.

I would feel more comfortable with that approach if we knew for sure why that rollbar error is happening.

**Comment by juanignaciosl** [comment]
I recall adding it as a performance boost for visualization related paging, as it is really heavy and every little improvement helped. No other association has such impact.

**Comment by gfiorav** [comment]
I guess the question is: Is the `DEFAULT_SELECT` really necessary? AFAIK we're guessing it is. Do we have any stats?

Anyway, 2 statements are facts:
a) We should `DEFAULT_SELECT` consistently across all associations of user if we choose to do so.
b) We should remove unnecessary columns in the users table.

Maybe we could roadmap b), benchmark a) after b) is completed, and decide if a) is necessary or not.

**Comment by juanignaciosl** [comment]
I  don't agree on a). It's a not big optimization that makes reasoning with code harder, so the tradeoff might pay at the most important associations but not at others. b) is true but we can't remove many columns. There's a lot of them that are only used in specific scenarios (that's why we can select a projection for most of them), but only a couple are actually deprecated.

Removing columns is not a short term goal. I'd...

1. Check whether that error can be fixed by adding some columns to the select or just removing it.
2. Do whatever 1 output fits better (add columns / remove `DEFAULT_SELECT`).
3. Roadmap removing columns.

**Comment by javitonino** [comment]
I created PR #9303 to add `database_host` to the default select. I'll test that nothing breaks (unlikely given the change), but I think we will have to check in production if it does solve that rollbar issue (as this is random, and I haven't seen it in staging).

**Comment by javitonino** [comment]
Some new. I merged #9303 and we don't have the same error anymore. Instead it is complaining about another field: `crypted_password`: https://rollbar.com/vizzuality/CartoDB/items/19783/

I think that's the last field, so I'm going to try to add it and see if it solves it for good.

Maybe we can remove the select from the associations and put it into the controller/presenter where the performance problems lie?

**Comment by juanignaciosl** [comment]
Good to know!

Moving _the decision of selecting the columns_ to the presenter might be great, with the best of both worlds once we've agreed that doing it everywhere is harder. It looks like you can do it with [association extensions](http://guides.rubyonrails.org/v3.2.20/association_basics.html#association-extensions) or with a second association. Nevertheless I've been trying for a while with association extensions, which is far more elegant, but I haven't been able to make it work. More details about this at [`belongs_to` documentation _comments_](http://apidock.com/rails/ActiveRecord/Associations/ClassMethods/belongs_to#277-Can-be-extended-but-only-with-a-module) (check notation issues). Ping me if you manage to do it!

**Comment by javitonino** [comment]
I think I can confirm there are no extensions to `belongs_to`. A look at the [source for ActiveRecord](https://github.com/rails/rails/blob/3-2-stable/activerecord/lib/active_record/associations/builder/belongs_to.rb) (search for `options`) shows no extension option in `belongs_to` associations.

That makes some sense, as the association returns the target object (`Carto::User`), not an intermediate AR object (such as `has_many` does).

Creating two relations is a bit ugly, but may be the right solution here.

**Comment by javitonino** [comment]
Since the friday deploy, there have been no more issues with this; adding the needed columns to it worked. Still not sure on why it failed, as the relation was being loaded from map which has no `DEFAULT_SELECT`.

**Comment by javitonino** [comment]
This happened again today, after merging https://github.com/CartoDB/cartodb/pull/10013
https://rollbar.com/vizzuality/CartoDB/items/20556/

**Comment by javitonino** [comment]
During my work on https://github.com/CartoDB/cartodb/pull/11290 I found another reason why we should remove this. The user is not  actually loaded using the default select in the visualizations index controller (which IIRC was the main reason to add this), as there is an eager load for user in the VQB. So with proper `inverse_of` and caching, the `DEFAULT_SELECT` is not used at all.

**Comment by juanignaciosl** [comment]
Closing automatically because of inactivity. If anybody considers that this still important, please reopen and it'll be prioritized.
