### ISSUE TITLE
Animated layers are not working on embeds

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#9295]
**STR:**

- In production or any environment served over HTTPs, login to the BUILDER and create a map from any dataset.
- Animate one of the layers.
- Go to the embed.

**Expected result:**

- Map is rendered correctly and you can see an animated layer.

**Actual result:**
- Map is animated correctly in the BUILDER, but animation doesn't work in the embed.
- JS error similar to:

   ```request.js:42 Mixed Content: The page at 'https://team.carto.com/u/pabloalonso/builder/81fc59d0-595c-11e6-840d-0e3ff518bd15/embed' was loaded over HTTPS, but requested an insecure script 'http://pabloalonso.cartodb.com/api/v1/map?config=%7B%22version%22%3A%221.0.…15_listings_with_closest_metro%22%7D%7D%5D%7D&callback=_cdbct_1188061590_1'. This request has been blocked; the content must be served over HTTPS.```

cc: @javisantana @xavijam

**Comment by alonsogarciapablo** [comment]
It looks like we removed the `maps_api_template` from "torque" layers in https://github.com/CartoDB/cartodb/pull/9118/, and it's actually being used by torque layers [here](https://github.com/CartoDB/cartodb.js/blob/v4/src/geo/torque-layer-view-base.js#L27) (cc: @javitonino). We probably can fix this in cdb.js instead of bringing that option back.

**Comment by javitonino** [comment]
The change should be possible to do in cartodb.js. Datasource templates are generated with the same code that the ones inside the Torque layers were, so it should be a matter of reading from a different key.

There is a minor difference in the handling of protected embeds loaded via HTTP, but as we now force HTTPS for all builder embeds, it is not relevant.

**Comment by alonsogarciapablo** [comment]
Thanks @javitonino. I opened an issue (:point_up:) and will fix it now.
