### ISSUE TITLE
Login redirects to /your_apps/api_key/regenerate

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#930]
After login at https://cartodb.com/sessions/new I'm redirected to https://juanignaciosl.cartodb.com/your_apps/api_key/regenerate. I'd expect being redirected to my dashboard (or, maybe, last page used, but not api key regeneration).
Redirection is caused by a 302 response with header "Location:https://juanignaciosl.cartodb.com/your_apps/api_key/regenerate".
I followed smoke test guide yesterday, and I requested api key regeneration. I had some connection issues due to mobile coverage. It looks like I lost connection and that regeneration request is the remembered one.
As a workaround, changing url by hand works as expected.

https://cartodb.atlassian.net/browse/CDB-4371

**Comment by xavijam** [comment]
This is not happening anymore, closing.
