### ISSUE TITLE
Timeseries option does not show in the carousel

### ISSUE THREAD

**Issue by nobuti** [CartoDB/cartodb#9300]
If you add an animated torque layer, the time series widget is created properly. But when you want to edit the widget, no time series option exists in the carousel.

![time-series](https://cloud.githubusercontent.com/assets/1366843/17399948/6ce4938e-5a45-11e6-9ba9-07ed5965593b.gif)

**Comment by xavijam** [comment]
Yeah, we are not giving the chance to add time-series with number columns from the carousel.

**Comment by saleiva** [comment]
Well, it appears when it's not a time.series one curously
