### ISSUE TITLE
Redesign pagination for lists on modals

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#9315]
![screen shot 2016-08-04 at 18 58 26](https://cloud.githubusercontent.com/assets/132149/17410768/756ca034-5a75-11e6-9031-99a3848b35d5.png)

And implement it.

**Comment by piensaenpixel** [comment]
![pagination](https://cloud.githubusercontent.com/assets/1214201/17550635/34eda780-5ef6-11e6-9488-8c98895271b3.png)

**Comment by saleiva** [comment]
Check the bottom separation of the lines

**Comment by xavijam** [comment]
@piensaenpixel, so?
