### ISSUE TITLE
Color picker input display is broken

### ISSUE THREAD

**Issue by MariaCheca** [CartoDB/cartodb#9319]
![screen shot 2016-07-26 at 12 50 12](https://cloud.githubusercontent.com/assets/2141690/17431028/04bd7f74-5af8-11e6-83a9-6d8510714775.png)

**Comment by saleiva** [comment]
To be done only if happening always.

**Comment by piensaenpixel** [comment]
@MariaCheca where does this happen?

**Comment by MariaCheca** [comment]
@piensaenpixel this happens in the organization account settings, in the picker for the brand color.

**Comment by ramiroaznar** [comment]
Closing this because of this [PR](https://github.com/CartoDB/cartodb/pull/12785).
