### ISSUE TITLE
Write on boarding text for "Connect with Lines" analysis

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#9330]
We are working on the "Connect with Lines" analysis (#8884) and would need some information for the screen that appears after an analysis is finished.

The information should cover these analyses:

- line-sequential
- line-source-to-target
- line-to-column
- line-to-single-point

**Comment by javierarce** [comment]
@ohasselblad: we had a little misunderstanding regarding this analysis and @dgaubert is going to update the camshaft reference with some changes for the connect with lines family of analyses, so those three names that appear in the original description will probably change soon.

**Comment by ohasselblad** [comment]
Ok, np!

**Comment by javierarce** [comment]
@ohasselblad, here are the connect-with-lines analyses we need the texts for:

- line-sequential
- line-source-to-target
- line-to-column
- line-to-single-point

I'm finishing the UI for them and testing them in staging.

We are using this reference: https://github.com/CartoDB/camshaft/blob/master/reference/versions/0.41.0/reference.json

**Comment by javierarce** [comment]
We'd also need a description for the card that appears in the modal window:

![screen shot 2016-08-24 at 16 47 09](https://cloud.githubusercontent.com/assets/4933/17935014/36c20482-6a1a-11e6-8a94-623abef92a60.png)

**Comment by ohasselblad** [comment]
_the mystery analysis_. I support having a mystery analysis, by the way.

No, but 👍 on this. For the onboarding, will there be if/thens on which analysis was chosen so that different descriptions are shown depending on that option?

**Comment by javierarce** [comment]
> the mystery analysis. I support having a mystery analysis, by the way.

Haha, that would be a great easter egg!

> For the onboarding, will there be if/thens on which analysis was chosen so that different descriptions are shown depending on that option?

Yes, we can print different information depending on which the analysis the user chose. So if you want to write 4 different descriptions it would be ok.

**Comment by ohasselblad** [comment]
Cool, on it right now.

**Comment by ohasselblad** [comment]
I feel like this needs a bit of work still. For instance, the columns output vary depending on the methods.

```
{Connect with lines} has finished.

{The geometries in your table were updated.}

* {the_geom}
   {This column was updated to be lines according to the method chosen.}

{Description -- see one of below}

{Read more in [documentation](we need docs for each of these methods)}


line-sequential
* This analysis creates a line by connecting all points in the dataset in a specified order
line-source-to-target
* Link a source point to a target point based on a shared attribute
line-to-column
* Create lines from a point to to a geometry stored in another column
line-to-single-point
* Connect the coordinate from latitude and longitude columns to the point geometry (`the_geom`) in your dataset.
```

**Comment by javierarce** [comment]
Thanks! What about the text for [the card](https://github.com/CartoDB/cartodb/issues/9330#issuecomment-242090154)?

Something like: `Connect the points in your dataset using different methods`?

**Comment by ohasselblad** [comment]
How about this:

Create lines from point datasets using a variety of methods

**Comment by xavijam** [comment]
Already merged so 💃
