### ISSUE TITLE
Export dataset in dropdown?

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#9331]
What do you think about moving "Export dataset" inside the dropdown?
@saleiva @urbanphes 

![image](https://cloud.githubusercontent.com/assets/1214201/17439005/1e9784d4-5b26-11e6-926a-17dc13315732.png)

**Comment by saleiva** [comment]
+1

**Comment by urbanphes** [comment]
+1

**Comment by saleiva** [comment]
Also, I'd remove "dataset" from Duplicate, Lock and Rename options. It's obvious that you are talking about a dataset

**Comment by urbanphes** [comment]
Here attached the visual design:
- Add a new item: Export.
- Editing the texts: Delete dataset word.


![01 dataset - 00-07 data - production](https://cloud.githubusercontent.com/assets/14546701/17885484/b60c2ca2-691d-11e6-9fcf-efad2dccc996.png)

**Comment by saleiva** [comment]
As a convention I'd add "..." affer each option that has a second step. 
Also, Wouldn't you remove the EXPORT button on the grey bar then?

**Comment by saleiva** [comment]
I propose we attack this when finishing the dataset view. If we don't remember, is that we will not needed. Done as part of the issue cleanning.
