### ISSUE TITLE
Bounding box calculation seems wrong sometimes

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#9338]
With some datasets, the map gets centered in a place with no data, so it looks like an error, while f you go to a place with data it renders correctly.

With the attached kml, if you import it an create a map with the only two layers that are georeferenced, it gets centered in the middle of nowhere.

[Unofficial Pokémon Go Map  San Francisco Bay Area.kml.zip](https://github.com/CartoDB/cartodb/files/406599/Unofficial.Pokemon.Go.Map.San.Francisco.Bay.Area.kml.zip)

**Comment by saleiva** [comment]
cc @xavijam to prioritize

**Comment by xavijam** [comment]
The bounding box when a new dataset is added takes place in the importation process, could you help us with this @rafatower ?

**Comment by rafatower** [comment]
Ohhh! the bbox issue striking again! I'll take a look cc/ @ethervoid

**Comment by rafatower** [comment]
At first sight I thought it could be related to crossing the dateline (+/- 180 degrees lon) but it is not. It seems like the problem lies on the choice of the zoom level and that those datasets have a few points just in the corners of the calculated bbox.

**Comment by ethervoid** [comment]
I think this issue is related to the view box more than the bounding box of the dataset

**Comment by xavijam** [comment]
Not related with the Builder

**Comment by ethervoid** [comment]
I've imported the KML and this is what I get when entering the map. Which is the wrong part? Thx!

![captura de pantalla 2016-10-06 11 16 01](https://cloud.githubusercontent.com/assets/741240/19146986/482f3db2-8bb6-11e6-9bb9-0aa1f0c919ab.png)

**Comment by saleiva** [comment]
ok, closing since it doesnt happen to me for a long time now... thanks!
