### ISSUE TITLE
Non-square avatars displayed at original proportion in share with users modal

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#9340]
In the modal to share the map with organization users (inside the builder), non-square avatars are not correctly sized.

![screenshot_20160808_124401](https://cloud.githubusercontent.com/assets/7569673/17477484/d2d85432-5d65-11e6-86f7-6b77e057af4e.png)

cc @xavijam @nobuti

**Comment by xavijam** [comment]
@josecruz do we want them rounded or as they appear?

**Comment by josecruz** [comment]
We need it rounded, having the same appearance as the big ones
