### ISSUE TITLE
Remove Mailchimp connector

### ISSUE THREAD

**Issue by yasharora73** [CartoDB/cartodb#9343]
Hey @xavijam 

Since we don't support Mail chimp anymore, could you remove it from under connect new dataset?

Thanks

**Comment by xavijam** [comment]
Remove the whole option?

**Comment by yasharora73** [comment]
Yes please. We don't offer support for it anymore.

**Comment by yasharora73** [comment]
Hey @xavijam Any update on this? I noticed that the option is still available under new dataset.

**Comment by ramiroaznar** [comment]
Mailchimp was deleted from the Connect Dataset options.
