### ISSUE TITLE
Change Link to "People with Link"

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#9364]
![screen shot 2016-08-08 at 19 03 57](https://cloud.githubusercontent.com/assets/132149/17488693/da08786a-5d9a-11e6-81a8-5a2f4bdc57c1.png)

In all occurrences when is not a tag.

**Comment by csobier** [comment]
Hi guys, I just noticed this in the UI...  So before I redo all the Docs and images, can I make a suggestion to rewrite it?  'People' sounds a little weird.  How about "Only accessible with link"

**Comment by saleiva** [comment]
+1
