### ISSUE TITLE
Do not add empty strings as category

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb#9366]
If there are empty strings in a column, treat them as nulls in category widget to avoid UI weirdness

**Comment by xavijam** [comment]
I feel it is already fixed or at least managed, could you confirm @javierarce? 💋

**Comment by javierarce** [comment]
I haven't spot any weirdness (?) (not sure what was exactly the issue) with empty strings, but I've seen that the category widget doesn't show the null count:

![screen shot 2016-10-07 at 11 13 05](https://cloud.githubusercontent.com/assets/4933/19184837/3cc17fb6-8c7f-11e6-8a1e-f7d0b2cebf5b.png)

**Comment by AbelVM** [comment]
From my point of view, both NULL values and empty strings shouldn't be taking into account for the categories widget, and they should be both treated as nulls in the stats line.

So we shouldn't have a NULL category or a "" one

**Comment by javierarce** [comment]
But if there are NULL values and we don't show them in a category, users won't be able to select them, will they? Not sure if that's something we want to avoid.

**Comment by AbelVM** [comment]
:thinking: ...that'd makes sense...

**Comment by javierarce** [comment]
Closing this then :) 🎈

**Comment by AbelVM** [comment]
But no empty strings, please
