### ISSUE TITLE
"Exactly overlapping geometries with Infowindows" problem

### ISSUE THREAD

**Issue by andrewbt** [CartoDB/cartodb#9367]
Take a dataset with many rows/records with exactly the same geometry - could be point/polygon/line. Enable click or hover infowindows on the layer. User will only be able to select and click/hover the infowindow for the record that was rendered topmost, and not any of the geometries rendered "below" it.

We did a few CartoD1B.js demos that had "paginated" infowindows for this problem (1 of 40, 2 of 40, etc etc). Would love to see this solution to this longstanding, often customer requested issue make its way into the Builder.

**Comment by andrewbt** [comment]
See https://carto.com/blog/stacking-chips-a-map-hack/ - cool hack but exactly a hack around this limitation

**Comment by saleiva** [comment]
Duplicated! Thanks for the report!
