### ISSUE TITLE
when adding a new dataset/table/layer, reset the sql

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/cartodb#9368]
If a layer is added in the Builder, it pulls in the SQL that was last applied to the table/dataset that is being added. This can cause some hard to diagnose problems because the layer inherits the table name, but the underlying SQL may be something entirely different.

I propose, when adding a layer, set the default SQL to `select * from layer_name` instead of what was previously applied. Even better, there could be a screen which asks "Use previously applied SQL or use default dataset?"

cc @saleiva

**Comment by saleiva** [comment]
Spotted a few weeks ago, absolutely right.

**Comment by saleiva** [comment]
This is already fixed by improving the visibility of the SQL indicator. Lets test this behaviour and reopen this if it still feels weird
