### ISSUE TITLE
Add CDB_Mode to all accounts

### ISSUE THREAD

**Issue by Kartones** [CartoDB/cartodb#937]
We are starting to need Mode for all our twitter maps. It is silly to have to explain to people how to deploy a mode function. Can we get this function added to the SQL and deployed to all users?

https://github.com/CartoDB/cartodb/wiki/CDB_Mode

Requested by @andrewxhill

**Comment by xavijam** [comment]
ping

**Comment by Kartones** [comment]
@andrewxhill If you think is still interesintg, create the issue at https://github.com/CartoDB/cartodb-postgresql please

**Comment by javisantana** [comment]
is there since months ago: https://github.com/CartoDB/cartodb-postgresql/blob/master/scripts-available/CDB_Math.sql#L20

**Comment by andrewxhill** [comment]
yeah... this ticket predates that repo i think... all good :)
