### ISSUE TITLE
New organization user email redesign

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#9371]
STR:

1. Enable signup for an organization.
2. Signup in that organization with a valid domain, without Google authentication.
3. You'll receive this email:

![screen shot 2016-08-09 at 09 22 48](https://cloud.githubusercontent.com/assets/932968/17507998/000f52ae-5e13-11e6-8040-dfb5e8c65b7f.png)

This email wasn't in the main list #8889 because it shares design with #8214.

You'll need the fix for #9369 first to be able to test this.

**Comment by MariaCheca** [comment]
This is already solved after merging all emails rebranding with master
