### ISSUE TITLE
Torque layers are not working in embeds

### ISSUE THREAD

**Issue by dgaubert** [CartoDB/cartodb#9372]
Steps to reproduce it:
1. Create a map with one layer and using populated places dataset.
2. Style with `animated` option (in builder is working)
3. Click `share` and choose `embed` option.

It seems like first step is rendered but it gets freeze and no error is shown in the console.

**Comment by javitonino** [comment]
Maybe related to https://github.com/CartoDB/cartodb/issues/9295 https://github.com/CartoDB/cartodb.js/pull/1383 ?

**Comment by saleiva** [comment]
Dupe!

**Comment by javitonino** [comment]
Maybe not dupe to those ones, as those are closed! Unless it's dupe to a different one.

**Comment by saleiva** [comment]
I tried to close another issue - P

**Comment by michellechandra** [comment]
User is reporting issue with sharing Torque map (does not render when shared)

S/B: 9663779

**Comment by nobuti** [comment]
Related and likely the same issue https://github.com/CartoDB/cartodb/issues/9548

**Comment by saleiva** [comment]
Not happening anymore
