### ISSUE TITLE
add an option to disable pan 

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#938]
in mobile the users have problems if the map gets the drag event, we should add a sharing option to not allow drag.

A question: Should the option be: "disable drag on mobile?"

**Comment by iriberri** [comment]
We've been asked about this again: blocking the panning of an interactive map published in online newspapers so that the users don't get lost panning infinitely our map when trying to scroll around the website. What do you think?

**Comment by xavijam** [comment]
Finally -> https://github.com/CartoDB/cartodb/issues/5995 \o/.
