### ISSUE TITLE
Cannot use numeric keypad to input numbers in analyses forms

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#9385]
When trying to input a number into one of the analyses form (e.g: distance for AoI), it works by dragging the slider and inputting the number with the keyboard using the top row of numbers. But pressing numbers on the numpad does nothing.

**Comment by ramiroaznar** [comment]
I was not able to replicate the issue. Are you still having this problem? @javitonino

**Comment by javitonino** [comment]
Not an issue anymore ✨
