### ISSUE TITLE
Basemap mixed content issues

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#9388]
We have a couple of issues regarding secure basemap loading in the builder. The embeds are fine.

 - [ ] On every builder load, there is an http request to "http://a.basemaps.cartocdn.com/dark_nolabels/6/30/24.png" just after instantiation. The basemap changes but the coordinates doesn't, it is always that tile (south-west Spain/Portugal).

 - [ ] When changing the basemap, the new basemap will be requested by http. Refreshing makes it start requesting by https again.

cc @xavijam @matallo

**Comment by matallo** [comment]
this is related to the config basemaps, some of them might be setup with `http://` instead of HTTPS, thus the mixing content issues

https://github.com/CartoDB/cartodb/blob/master/config/app_config.yml.sample#L351

this affetcs both the basemap and the thumbnails, in the thumbnials case it has already been reported too https://github.com/CartoDB/cartodb/issues/9445

**Comment by rochoa** [comment]
Why don't we make that an application asset as any other UI related image?

**Comment by javitonino** [comment]
Was looking at this and just found out that the config for prod still has the old category (CartoDB instead of CARTO). Staging is ok, though :confused:. We can fix it at the same time as the https changes. We will need to rerun the layer update rake.

**Comment by luisbosque** [comment]
Why don't we just use always https for basemaps?

**Comment by javisantana** [comment]
we should send the right config depending on the protocol used:

- if we are in the builder -> https 
- if we are sending viz.json:
   - send https urls if the viz.json is requested though https
   - http urls if the viz.json is requested though http

all the basemaps have a https url so let's start using it

Some background: we haven been doing that client side for years (https://github.com/CartoDB/cartodb.js/blob/develop/src/vis/layers.js#L11) so i guess is time to move it to the place it belongs

**Comment by zenitraM** [comment]
why don't we always send https urls on the vizjson?

**Comment by javisantana** [comment]
why we would want to use https always? I understand there are some improvements if we use http2 but there should be a reason why adding such an overhead to render maps embedded in a newspaper

**Comment by zenitraM** [comment]
consistency and support for http2 when it gets enabled (our CDN already supports it on early preview, we haven't gotten to enable it yet)

**Comment by javisantana** [comment]
ok, let's go for it

**Comment by javisantana** [comment]
ENTERPRISE READY

**Comment by javitonino** [comment]
Updated basemap config to use https. Only positron and dark matter with labels on top were affected by the change. The rest of the basemaps already used https.

Leaving open as we should also update existing layers.

**Comment by javitonino** [comment]
Ok, rake is running to fix the category and attributions URL. This is not updating the source of the basemaps layers to https. I think the best option is not to touch that, and start using https only on new maps (which is already happening). I don't trust updating all layer sources with a rake, too many potential for problems for little gain.

Please reopen, if you feel that this is an important thing.

**Comment by matallo** [comment]
👏 thanks mate!
