### ISSUE TITLE
Torque category is not working

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#9389]
As @javisantana mentioned [here](https://github.com/CartoDB/cartodb/issues/9010):

When style is set as animated some things needs to happen:

- if the style applied does not use any variable it should work like it's working with now
- if we have one style using "by value" 
    - if it's a category attribute: torque style should use `cdb_mode([attribute])` as aggregation and use the turbocarto for the category
    - if it's a ramp attribute: torque style should use `avg([attribute])` as aggregation and use the turbocarto for ramps

- if we have more than one style attribute using "by value" -> we can't do anything with torque here since we don't have multivariable torque <- cc @saleiva. One solution would be to disable animated when this happen but not sure how hard is to explain that limitation to the user.

**Comment by rochoa** [comment]
Some notes after reviewing this thing with @xavijam:

To have the different categories we need to wrap the user query with a torque category query (use `value`as alias for the column, after that, we have to set torque aggregation property with `"cdb_math_mode(value)"`, with those changes we can use turbo-carto to generate the categories using `value` as the column.

**Comment by xavijam** [comment]
Adding real pending things.

### Pending things:

- [ ] Instantiate map when a new ramp value is selected.
- [ ] Check problems with `Others` value.
- [ ] Problem in public embed (it is likely related with sql_wrap not included).
- [ ]Add tests for new things added.

**Comment by saleiva** [comment]
:tada:
