### ISSUE TITLE
Merge Mapbox basemaps inputs into one

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#9392]
Right now we have 2 inputs, one for the map url and another one for the access token. Would be awesome if we can just use 1 input for it:
![screen shot 2016-08-10 at 15 15 19](https://cloud.githubusercontent.com/assets/596509/17554861/469c95a6-5f0d-11e6-967d-ac91818a9cd1.png)

It's not needed anymore because Mapbox gives you a link with your access token:

![screen shot 2016-08-10 at 15 10 22](https://cloud.githubusercontent.com/assets/596509/17554830/1d1a34ea-5f0d-11e6-8fd9-3e02d24f8815.png)

**Comment by matallo** [comment]
dat old logo
