### ISSUE TITLE
basemaps: custom: xyz (tms) changing basemap

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#9398]
**str**

when changing basemap (not adding a new one) from non-tms to tms xyz (or the other way around) the map is not set well (see attached)

![screen shot 2016-08-10 at 16 40 01](https://cloud.githubusercontent.com/assets/36676/17557886/2a027c88-5f19-11e6-9c8c-a3bc01a411e8.png)

however when adding a _new_ basemap in the modal, it works flawlessly

**Comment by xavijam** [comment]
Happening in the current editor?

**Comment by matallo** [comment]
yeppers, sope, so it must be some layer management issue, I'll dig into it

**Comment by matallo** [comment]
seems like a CARTO.js issue
