### ISSUE TITLE
basemaps: custom: already existing basemap makes loader spin indefinitely

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#9399]
**str**

when adding a new basemap in the modal, if that basemap already exists it makes the "Saving basemap" notifier to spin indefinitely (see attached)

![screen shot 2016-08-10 at 16 38 04](https://cloud.githubusercontent.com/assets/36676/17558013/8d6dd718-5f19-11e6-92b1-c352657695ed.png)

**Comment by xavijam** [comment]
I feel we have talked about that, but we should not do anything, just select the basemap and that's it, right?

**Comment by matallo** [comment]
👍
