### ISSUE TITLE
Can't change point opacity on animated layer

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#9404]
Changing opacity doesn't works when having an animated map. I can change it on the color picker but it doesn't update it on the map:

![bug4](https://cloud.githubusercontent.com/assets/596509/17559506/c36088f2-5f1e-11e6-9352-983ac811af5c.gif)

**Comment by nobuti** [comment]
It changes the opacity, but not the trails' opacity.

**Comment by xavijam** [comment]
Aaaanananananangela María, ok. Let me check it in the animated-delete PR.

**Comment by xavijam** [comment]
Thanks both! Fixed here -> https://github.com/CartoDB/cartodb/commit/cf677c07490dfc8a167aa1f99390ce6450ff1992
