### ISSUE TITLE
Disable Auto-style button whenever the aggregation method doesn't support it

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#9405]
STR:

- Import a point dataset
- Add a histogram or category widget
- Change the aggregation method to Hexabins

- If you try to style with the widgets it will fail. We should disable the auto-style.

**Comment by xavijam** [comment]
@jmartinter, that was the problem you had on Friday.

**Comment by xavijam** [comment]
Duplicated https://github.com/CartoDB/cartodb/issues/8468
