### ISSUE TITLE
Trying to use the import API to local Carto instance

### ISSUE THREAD

**Issue by Kimsing-007** [CartoDB/cartodb#9406]
I'd like to find out if the Import API works for the Local Carto Instance. I have managed to install the Carto instance succesfully and am able to import datasets using the GUI. I want to be able to run the Import API from the CLI to import files stored in a specific folder

**Comment by iriberri** [comment]
To use the Import API make sure that you use the correct account host (check your app_config.yml for this in case you're doubting, but it's the same in which you access the GUI) in your request and it will work. You can also examine the Builder/Editor network requests when you import a file, as the frontend performs a call to the Import API.

For example, in my environment, I can run:

`curl -v -F file=@my_test_file.csv "http://{username}.localhost.lan:3000/api/v1/imports/?api_key={api_key}"`

**Comment by Kimsing-007** [comment]
Thanks for the response, I checked my app_config.yml and the account host default is set to localhost.lan.
I took you example and attempted to run it on the server, replacing {username}.localhost.lan with the server IP address. the error returned is:

Started POST "/api/v1/imports/?api_key={API KEY}" for {IP ADDRESS} at 2016-08-24 04:22:49 +0000
Processing by Api::Json::ImportsController#create as JSON
  Parameters: {"file"=>#<ActionDispatch::Http::UploadedFile:0x007f69fc0ecbb8 @original_filename="ImportAPITest.csv", @content_type="application/octet-stream", @headers="Content-Disposition: form-data; name=\"file\"; filename=\"ImportAPITest.csv\"\r\nContent-Type: application/octet-stream\r\n", @tempfile=#<Tempfile:/tmp/RackMultipart20160824-4370-vwdmqb>>, "api_key"=>"{API Key}"}
Completed   in 1.2ms
Processing by SessionsController#unauthenticated as JSON
  Parameters: {"file"=>#<ActionDispatch::Http::UploadedFile:0x007f69fc0ecbb8 @original_filename="ImportAPITest.csv", @content_type="application/octet-stream", @headers="Content-Disposition: form-data; name=\"file\"; filename=\"ImportAPITest.csv\"\r\nContent-Type: application/octet-stream\r\n", @tempfile=#<Tempfile:/tmp/RackMultipart20160824-4370-vwdmqb>>, "api_key"=>"{API Key}"}
WARNING: Can't verify CSRF token authenticity
Filter chain halted as :verify_authenticity_token rendered or redirected
Completed 403 Forbidden in 1.1ms

Any ideas on how to resolve this?

**Comment by iriberri** [comment]
We pushed some fixes for a similar issue around the first week of July. Just to be sure and discard that scenario: is your local environment branch updated with the `master` branch here?

**Comment by Kimsing-007** [comment]
CartoDB was downloaded using:

git clone --recursive https://github.com/CartoDB/cartodb.git

Which I assume downloaded the master branch. I re-ran the clone process just to make sure and ran the import curl statement:

curl -v -F file=@/home/ubuntu/ImportFolder/ImportAPITest.csv "http://{IP Address}:3000/api/v1/imports/?api_key=6028e793ac28bfcf138f1bc7fdda273a421249bb" this is being run from the ubuntu server console.

**Comment by iriberri** [comment]
Hey @Kimsing-007, I think I know what's happening :-)

Previously you said you were using your username + the account host in the request, but here you're using the IP of your server. This will not work, Import API requests need to be authenticated so you need to perform the request to your specific user (your API key will correspond to this user).

From your curl response, I'm seeing:
````
Host: 10.228.177.96:3000
````
and the application cannot authenticate the request against that as it doesn't know about the user.

If you want to work with IPs, make sure you add a Host header in your curl request with your username so that the request can work. Example:

````
curl -v -F file=@test.csv -H 'Host: cdb' "http://10.0.2.2:3000/api/v1/imports/?api_key=485d4973fd37a9d9f77231fa6f6e6d33c5ba48fc"
````

**Comment by Kimsing-007** [comment]
Eureka!!!! That's the solution! Thanks for that @iriberri. You have been a great help!!
