### ISSUE TITLE
Remove "deleted widget" notification when changing column on animated layers

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#9407]
When you change the column, a message appear saying that we deleted your widget. This is actually true because we remove it from the UI but I'd rather not show that notification due you're not removing anything. 

![bug2](https://cloud.githubusercontent.com/assets/596509/17561109/dfd998c4-5f24-11e6-9538-aab0268a94d2.gif)

**Comment by saleiva** [comment]
+1

**Comment by nobuti** [comment]
Fixed in https://github.com/CartoDB/cartodb/pull/9239/commits/9d537faa2969cf62e369aa4a471d6942438e4a6b
