### ISSUE TITLE
oauth authorize endpoint raises 500

### ISSUE THREAD

**Issue by Kartones** [CartoDB/cartodb#941]
steps:

1) login in cartodb with the account you are going to test

2) request tokens

~~~
curl -d '' -H 'Authorization: OAuth oauth_consumer_key="CONSUMER_KEY", oauth_nonce="yyy", oauth_signature="xxx%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1405405788"' https://javi.cartodb.com/oauth/request_token
~~~

you get: 

~~~
 oauth_token=qnAcHhggvWHgaqS4cgLDPBRZaQYAQgqwlhh8c9xo&oauth_token_secret=xxx&oauth_callback_confirmed=true
~~~

3) enter in the authorize url

https://javi.cartodb.com/oauth/authorize?oauth_callback=file%3A%2F%2Flocalhost%2FUsers%2Fjavi%2Fwrk%2Fviz%2Fcartodb%2Fclients%2Fjs%2Fohauth%2Findex.html&oauth_token=XXX

mark "authorize" and click on the button

it raises a 500 (after some time). There is a rollbar error related: https://rollbar.com/vizzuality/CartoDB/items/2913/ but that's not the real problem I think (that happens on GET), I couldn't find the rollbar item for my 500 

cc @lbosque

**Comment by xavijam** [comment]
Closing since it is gonna be deprecated.
