### ISSUE TITLE
Improve error reporting on Analysis errors.

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#9415]
Right now it just says Analysis failed, but we have a more comprehensive error on the response of the request. Can we add that text to the error?

high priority

**Comment by nobuti** [comment]
Fixed in https://github.com/CartoDB/cartodb.js/pull/1386

**Comment by saleiva** [comment]
\o/

**Comment by xavijam** [comment]
:clap:

**Comment by nobuti** [comment]
This should be :shipit: once the dependencies are updated.
