### ISSUE TITLE
Error when selecting a date column for colouring by value

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#9421]
We should support this BTW

cc/ @rochoa

**Comment by xavijam** [comment]
Already discussing the approach with https://github.com/CartoDB/cartodb/issues/9389.

**Comment by xavijam** [comment]
Closing here and discussing there.

**Comment by saleiva** [comment]
Hey this is not only about torque maps, it's on every map actually. Should I reopen?

**Comment by xavijam** [comment]
-> "Failed to process "marker-fill" property: unable to compute ramp, cannot cast type date to numeric"

**Comment by xavijam** [comment]
Basically we should not offer date columns right now in the fill component by value.

**Comment by saleiva** [comment]
:_( Why don't we try to fix it?

**Comment by rochoa** [comment]
We need to define what do you expect when the column is a date/datetime one.

Do you expect to have ranges? Or categories? Like in:

 - Ranges: apply equal quantification over the min/max interval.
 - Categories: group by hour, day, month, or year.

**Comment by saleiva** [comment]
Ranges, or categories if there is a bunch of values that can be handled. Like we do with numbers...

**Comment by ramiroaznar** [comment]
We decided to get rid of data column from the style by value options here https://github.com/CartoDB/cartodb/issues/7873
