### ISSUE TITLE
feedback on basemaps view

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartodb#9427]
Looking at the basemaps view, I see a couple of ways to improve the user experience.
<img width="327" alt="screen shot 2016-08-11 at 11 55 40" src="https://cloud.githubusercontent.com/assets/1041056/17595328/9974ddf8-5fba-11e6-93ec-bc646c553d56.png">
1. It would be helpful for users to know more information about the source of the basemaps. For example, a small description about what STAMEN means (and links to their page) and the licenses that apply to these maps would be really helpful.
2. I find it a little confusing that it says "Positron by CARTO" at the top of the page. I know it's my current basemap choice, but maybe we could add "**Current basemap:** Positron by CARTO" 
3. This seems like a good place to link to documentation and other things about basemaps. Pages like these pages
   - https://carto.com/location-data-services/basemaps/
   - https://carto.com/docs/carto-builder/basemaps-for-map-backgrounds/
   - etc.

cc @saleiva @matallo

**Comment by arianaescobar** [comment]
pinging @CartoDB/design for visibility
