### ISSUE TITLE
basemap labels UX

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/cartodb#9430]
Having the ability to click on a layer and get options for changing that layer makes me think that I should be able to do the same for the labels layer which is listed at the top of the layers list. 

At the very least, it would be great if clicking on the "positron labels" chip would take the user to the basemaps window. Currently there is no interaction feedback.

**Comment by saleiva** [comment]
Leaving for the future after testing. Closed as part of the issue cleanning sesion!
