### ISSUE TITLE
Category widget: option to list all values?

### ISSUE THREAD

**Issue by peterdesmet** [CartoDB/cartodb#9432]
Just tested the new CARTO builder and the widgets add a lot of new interactivity to published maps! One of the maps we often publish is a species map, but until now we had to build a custom website to allow the user to select the species of his choice:

http://inbo.github.io/alien-macroinvertebrates/

This functionality can now *almost* be replaced by the category widget:

https://lifewatch.carto.com/builder/33404524-6071-11e6-81a5-0e3ebc282e83/embed

But that widget currently only shows the top 5 values and lumps the rest in `other`. The user can search for other values, but has no way to access those if he/she does not know the name. Would it be possible to add an option in the widget, in which the map builder can choose to show all values (maybe limited by an upper bound)?

**Comment by saleiva** [comment]
Hi @peterdesmet we are currently exploring possibilities for paginating on that widget which I believe will help. Can't wait to see more things coming from you guys using the builde 👏

**Comment by peterdesmet** [comment]
Awesome!

**Comment by xavijam** [comment]
Closing since it is being redesigned by our great design team. We will open a new ticket for implementation and mention this ticket.
