### ISSUE TITLE
feature request: group public pages

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/cartodb#9435]
Right now there are organization public pages and personal public pages. I've gotten several requests from universities specifically which are interested in have department pages. The easiest way I see of achieving this is having pages for groups -- which would be _awesome_ :)

This way, professors could have class pages, university departments could have department pages, all based on the flexibility of groups.

cc @juanignaciosl

**Comment by juanignaciosl** [comment]
cc @xavijam

**Comment by saleiva** [comment]
Closing, dupe! Already taking care of a general rethink of this!
