### ISSUE TITLE
Add UI for "Find closest feature" analysis

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb#9437]
Feature request, description: https://github.com/CartoDB/crankshaft/issues/85 
Camshaft node: https://github.com/CartoDB/camshaft/blob/master/lib/node/nodes/closest.js

Open to title/description discussion.

**Comment by saleiva** [comment]
It's already done, and with steroids.

![01 layers - 06-20 analysis - find near - 15 walking](https://cloud.githubusercontent.com/assets/132149/17695316/3dfeece2-63a8-11e6-92b7-a7a68d05339e.png)
![01 layers - 06-21 analysis - find near - nearest](https://cloud.githubusercontent.com/assets/132149/17695317/3e00f79e-63a8-11e6-8b43-7f2fe7cd01fa.png)

**Comment by AbelVM** [comment]
Hmmm... That's a filtering analysis, isn't it? Mine is an "enrich" one. It gives you back your source dataset enriched with the cartodb_id of the closest feature in the target dataset and the distance to that feature

**Comment by saleiva** [comment]
this is not filtering, the result is exactly what you say.

**Comment by AbelVM** [comment]
What are the "RANGE" options? I may extend my function to add the different range methods. Right now it uses only linear distance.

**Comment by saleiva** [comment]
Find nearest only gets the closest feature
IF you select distance|time walking|time driving it will let you a max number of features ordered by distance up to a max (# nearest)

**Comment by AbelVM** [comment]
Then, this analysis only cover the 1st case

**Comment by AbelVM** [comment]
**Find Closest** analysis enhanced: https://github.com/CartoDB/camshaft/issues/256
* Categorized
* N closest features per category
