### ISSUE TITLE
REDIS_PORT under linked Docker images "lo peta"

### ISSUE THREAD

**Issue by jjmata** [CartoDB/cartodb#9438]
I just wasted a few hours to this, so figured I'd let you fine gentlemen know:

Setup:
- You use Docker, because it is what all the cool kids are doing
- You use the `link` directive to host an external Redis image and point the CartoDB app to it
- Things blow up nicely with an incoherent `Error connecting to Redis on 127.0.0.1:0 (Errno::ECONNREFUSED)` message ...

Why?

Because Docker creates a shit-load of ENV variables like so:

>  root@95333d92850f:/dronedb# env | grep REDIS_PORT
>   REDIS_PORT_6379_TCP_PROTO=tcp
>   REDIS_PORT_6379_TCP_ADDR=172.17.0.4
>   REDIS_PORT_6379_TCP_PORT=6379
>   REDIS_PORT_6379_TCP=tcp://172.17.0.4:6379
>   REDIS_PORT=tcp://172.17.0.4:6379

And our friend [redis_factory.rb](https://github.com/CartoDB/cartodb/blob/master/lib/redis_factory.rb#L16) gets all confused and cannot parse that fully-qualifed port number and dies leaving the port at 0.

There, not much I can suggest since you fine folks don't use Docker.  But I guarantee this will come back to bite many in the ass.

/cc @zenitraM and @javisantana for my free t-shirt! :trollface:

**Comment by jjmata** [comment]
I guess @juanignaciosl is the one who might be interested here.  Not that there is much to be done ... but just a heads up in case you run into it.

**Comment by juanignaciosl** [comment]
Thanks for the heads up, @jjmata :-) When this becomes a problem we can improve the environment configuration parsing 👍 

cc @javitonino @gfiorav

**Comment by alrocar** [comment]
BTW `--link` has been [deprecated](https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/)

The way to go now is attaching the containers to the same [Docker network](https://docs.docker.com/engine/userguide/networking/)

my 2 cents :)

**Comment by jjmata** [comment]
You are right, @alrocar!  I've been moving things to Swarm and stopped using `--link` a while ago, so this can be closed.  I was actually just testing deploying a stack to a Swarm for testing just now ... ;-)  Once `secrets` got implemented it convinced me to move on with it.

You guys starting to use Docker now?

PS.  I know, I know .. the cool kids are all doing Kubernetes and not Swarm now.  I will never be a cool kid, and I know it.

**Comment by alrocar** [comment]
Yep, as you know we try not to depend on the `cool` technologies out there, but some of our clients are running CARTO on top of K8s and Docker :)
