### ISSUE TITLE
feature request: some buttons for centering maps

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartodb#9439]
Centering a map can be tricky, so having some helper functionality to "center map on bounding box", etc. etc. would be super helpful to users.

**Comment by makella** [comment]
Also the option to 'zoom to layer' or something similar. I know this was a request by @ramiroaznar as well.

**Comment by ramiroaznar** [comment]
Yeah, both would be great!

**Comment by javisantana** [comment]
I can't be more agree

**Comment by arianaescobar** [comment]
Done here: https://github.com/CartoDB/cartodb/issues/10116
