### ISSUE TITLE
if time bins value is too large, show the proper error

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartodb#9440]
Right now, if the number of time bins is too large it defaults to a "Required" error tooltip instead of one that says "Number of bins must be from 1 to 256".

<img width="429" alt="screen shot 2016-08-15 at 15 02 58" src="https://cloud.githubusercontent.com/assets/1041056/17679956/cf557c94-630b-11e6-9c1d-0f421228afb5.png">

**Comment by xavijam** [comment]
That¡s a good one, thanks @ohasselblad.

**Comment by saleiva** [comment]
As part of the error, we should show something like "Insert a value between X and Y"

**Comment by ramiroaznar** [comment]
This is already fixed. Histogram widgets displayed a "Value must be between..." and time series widget has a new design.
