### ISSUE TITLE
Select views show a big empty space at the end of the list

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#9441]
I don't know if this was already reported or is already known, but select views are showing a big empty space at the end of the list (spotted in Chrome and Firefox):

![select](https://cloud.githubusercontent.com/assets/4933/17692467/3639bfc2-639a-11e6-8c6e-231a5a3e148d.gif)

**Comment by javierarce** [comment]
cc: @piensaenpixel @xavijam

**Comment by xavijam** [comment]
Could you take a look @piensaenpixel please?

**Comment by piensaenpixel** [comment]
sure

**Comment by piensaenpixel** [comment]
uhm i cant reproduce :( that's production. But i'm checking.
![scroll-custom](https://cloud.githubusercontent.com/assets/1214201/17728933/03f42048-6462-11e6-954f-2ca63a4d67ad.gif)

**Comment by javierarce** [comment]
Could you try to reproduce it with these instructions:  https://github.com/CartoDB/cartodb/issues/9247

**Comment by piensaenpixel** [comment]
Na, dont worry I've just found the problem.
