### ISSUE TITLE
The search field in a select view should automatically get focus on opening

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#9442]
Currently if you want to add a custom value in a select view or search for an element, you need to click on the search field. This change would make those actions a little bit less annoying. 

![screen shot 2016-08-16 at 11 04 49](https://cloud.githubusercontent.com/assets/4933/17693801/1bb93e64-63a1-11e6-87c8-980ee729f231.png)

**Comment by javierarce** [comment]
This seems to be actually implemented [here](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb3/components/custom-list/custom-view.js#L87), but it doesn't work for me

**Comment by viddo** [comment]
Could be that the view's element is not present in the document DOM at that point of the method call, or that the view is being re-rendered directly after the initial render (e.g. due to some event).

**Comment by saleiva** [comment]
It worked for me some time ago
