### ISSUE TITLE
HTTPS mixed-content due basemaps previews

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb#9445]
We should use HTTPS or as fallback protocol relative URL.

Example:
![mixed-content-displayed](https://cloud.githubusercontent.com/assets/45346/17697171/7771a4d2-63b3-11e6-8e96-10d8e4d4efb3.png)

**Comment by matallo** [comment]
duplicated https://github.com/CartoDB/cartodb/issues/9388
