### ISSUE TITLE
add 'aggregations where ...' to "aggregation intersection"

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/cartodb#9447]
Right now "Aggregation intersection" allows for aggregation. To make it more powerful, it'd be awesome to add **where conditions optionally**. Like if I want to count all car crashes where the weather was cloudy. Right now I would have to combine some different analysis steps instead, but adding the where condition would allow me to keep the original columns and rows while allowing for a more granular analysis of the data.

cc @saleiva @rochoa

**Comment by saleiva** [comment]
understood but since this works right now by chainning, I'd not consider this high priority, right?

**Comment by rochoa** [comment]
Isn't that adding a widget?
