### ISSUE TITLE
Dropbox connection gives error when picking pointer img

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#9448]
## Steps to reproduce:
1. Create a map
2. Add a points layer
3. Change Marker Fill to custom img
4. Upload from dropbox

## Error:
![screen shot 2016-08-16 at 16 42 42](https://cloud.githubusercontent.com/assets/596509/17703917/917e42ca-63d3-11e6-8ed2-9b0f08dd1380.png)

**Comment by juanignaciosl** [comment]
@rporres `dropbox_api_key` configuration is wrong. It's used by the Dropbox picker and it has an api key that is not any of the ones that we've updated after the rebranding.

**Comment by rporres** [comment]
Fixed!
