### ISSUE TITLE
Automatically adding attribution for DO data to map metadata

### ISSUE THREAD

**Issue by stuartlynn** [CartoDB/cartodb#9452]
As we expand the Data Observatory we are going to getting a lot of data from a lot of different places. For some of the providers of this data, attribution is going to be important. We already have an attribution field in the metadata for datasets, could we add one for maps/dashboards as well which would automatically be populated by the attribution for Data Observatory sources a user uses in analysis. The attribution should probably be shown in a few places but at minimum in the attribution line in leaflet.

@talos is already recoding this in the metadata for each column, we could pull it from there when a user runs an analysis that uses DO data.

@saleiva

**Comment by talos** [comment]
👍  My preference would be a new text array field in the map/dashboard metadata, which we can populate with however many attributions are required by the metadata.

There will be many cases where there will be several necessary attributions, and handling them concatenated in a single string would be messy.

**Comment by saleiva** [comment]
Sounds good to me. Adding to the backlog
