### ISSUE TITLE
POST to enterprise API user will not return the id for the new user

### ISSUE THREAD

**Issue by danicarrion** [CartoDB/cartodb#9455]
$ curl -H 'Content-Type: application/json' https://solutionscdb.carto.com/u/cdbsol-admin/api/v1/organization/solutionscdb/users -X POST --data '{"username":"testuserapicreation123", "email":"testuserapicreation123@test.com", "password":"secret!", "api_key":"HIDDEN"}'

{"id":null,"username":"testuserapicreation123","email":"testuserapicreation123@test.com","avatar_url":null,"base_url":"https://solutionscdb.carto.com/u/testuserapicreation123","quota_in_bytes":104857600,"db_size_in_bytes":0,"table_count":97,"viewer":null,"public_visualization_count":2,"all_visualization_count":42}

Notice the "id":null, compared to what is described in the docs, and expected in regular RESTful practice.

Also, this is a new user, so I don't understand these values. "table_count":97,"public_visualization_count":2,"all_visualization_count":42

Finally, as a suggestion, POST request returns a 200 OK, but it should actually return 201 CREATED if we want to be more RESTful.

**Comment by gfiorav** [comment]
An org admin has no way of grabbing a users' id, so the decision was made to use the users' username instead. This has _some_ technical implication, as user creations are queued and the user's id is not immediately accessible. 

Any solution for this involving the return of an id will require a two step process (job creation, job polling) API.

If you think the benefits of grabbing the id are worth it, we can implement this 2 step API.

For me, it's not, since you are in either one of 2 scenarios:
a) A machine uses the API, so it doesn't really matter what value it grabs as an id
b) A human uses this API, to whom it's friendlier to use a short string than an uuid.

This was the basis on which the decision was made. If you have any better ideas we should totally implement them 😄

**Comment by danicarrion** [comment]
For me, in order to remain consistent with the rest of APIs, the user endpoint should rely on ids instead of usernames. If you don't know the id of the user, you should be able to look for it: https://.../users?username=johndoe

Regarding the fact that creating a user is a 2-step, in my opinion there are two ways of handling this:

1) Not hide this fact, and make the final API consumer poll for the user object until they get it.
2) Hide it. But in this case the API needs to wait until the user is fully created before returning the response so that it can contain the whole user object.

What happens now is the API hides the fact that user creation is a 2-step process, but it's returning an incomplete object (id is missing). This goes against REST principles, and it can be problematic (what if user creation fails for some reason?).

**Comment by gfiorav** [comment]
> If you don't know the id of the user, you should be able to look for it: https://.../users?username=johndoe

Is this RESTy? I'd rather make the controller accept ids or usernames transparently. Do you agree?

**Comment by javisantana** [comment]
Having to look for id means a new request and in CARTO usernames are actually id's (are unique across the whole platform)

**Comment by danicarrion** [comment]
@gfiorav: that's perfectly restful, yes.

@javisantana: I can buy that, but then we should get rid of the id parameter, why do we need it?

**Comment by javisantana** [comment]
yes yes, you are totally right about the id

**Comment by gfiorav** [comment]
Ok so removing the id param is good enough?

**Comment by gfiorav** [comment]
Idless responses proposed in https://github.com/CartoDB/cartodb/pull/9490

**Comment by danicarrion** [comment]
sounds good, now, what do you think about the rest?

> Also, this is a new user, so I don't understand these values. "table_count":97,"public_visualization_count":2,"all_visualization_count":42

> Finally, as a suggestion, POST request returns a 200 OK, but it should actually return 201 CREATED if we want to be more RESTful.

or should I open separate tickets for this?

**Comment by javisantana** [comment]
We should not change 200 to 201, it's a public API and changing the interface would require to have a new version. Imagine something with

```
if response.code == 200
```
