### ISSUE TITLE
URL for enterprise user API includes the organization name as part of the FQDN

### ISSUE THREAD

**Issue by danicarrion** [CartoDB/cartodb#9456]
Shouldn't something like https://carto.com/u/cdbsol-admin/api/v1/organization/solutionscdb/users be enough, rather than https://solutionscdb.carto.com/u/cdbsol-admin/api/v1/organization/solutionscdb/users?

Having the organization name as part of the FQDN requires onprem customers to set up a DNS record for each or their organizations, and in general suffers from the same problems we tried to avoid when we introduced our domainless URLs (http://cartodb.readthedocs.io/en/latest/configuration.html#domainless-urls). And we already have the organization name in the path anyway.

**Comment by gfiorav** [comment]
Just to be clear: you're saying that omitting the subdomain from the url doesn't already work? If so, it's a bug. 

The API should work the same wether you provide a subdomain or not, provided you specify the orgname in the path of course.

**Comment by danicarrion** [comment]
ok, so then yes, it's a bug ;-)

**Comment by gfiorav** [comment]
Interesting! Thanks for reporting, I'll have a look soon.

**Comment by gfiorav** [comment]
Ok, so If I understood correctly from my chat with systems: this can't be done without major implications. You might wan't to have a chat with someone over there as this is off-limits to the EUMAPI concern 🙈 

Close this issue if you have no further questions!

**Comment by danicarrion** [comment]
Not critical, so I'm closing
