### ISSUE TITLE
Improve query-schema-model usage

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#9460]
We are currently (ab)using query-schema-model for _two_ purposes (breaking single-responsibility-principle for the trade-off and benefit of avoiding extra API calls/roundtrips), to get:
 1. The query schema, i.e. the column names and their types
 2. The geometry of the dataset

The problem is, to get both results in one request we do a full `SELECT *` query, which while returns all columns available(1), also includes _all_ data even if we only need the simple type of a geom(2), which if the dataset contains huge `the_geom` or blobs (in magnitude of MBs) doesn't make sense to return to the frontend. Waste of bandwidth and could make the browser (tab) crash. This wasn't seen until last week, so luckily not a urgent problem (yet).

Also, different parts of the UI don't require _both_ these data points, typically it's only `the_geom` that's needed up front, the dataset schema is usually only needed when editing a layer/analysis/widget, so that can be postponed to be fetched on-demand (this is already how it works, so no changes necessary for this).

Considering the common use-cases don't contain huge `the_geom`/blobs I think we could/should tackle this in the following steps:

1. Cast `the_geom` to a the simple type literal consumed by the views (`point`, `polygon`, `line`)
2. Separate query-schema-model in two:
  - `geometry-model`: new model to represent the simple geom ([persisted on/restored per node definition already](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb3/data/analysis-definition-node-model.js#L16-L18))
  - `query-schema-model`: only representing the schema, so can add a `limit 0` to the query, effectively avoiding to get any unnecessary data
  - These changes should only require changes minimal change to the UI, to use the new geometry-model to get the geometry, there's [only a handful](https://github.com/CartoDB/cartodb/search?utf8=%E2%9C%93&q=simple_geom), and the use-cases are simple, so should not be that severe.

Thoughts, @gfiorav @xavijam @rochoa  ?

**Comment by xavijam** [comment]
Fine by me for both things.
