### ISSUE TITLE
Add transitions to stack-layout-view

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#9463]
Basically we should add the option to animate the transitions between views. But the option should be disabled by default, because we are using this "view" in several places where the transition is not needed. Also we should support in both sides, up/down and right/left.

With the invaluable help of @piensaenpixel.

cc @saleiva.

**Comment by xavijam** [comment]
I feel we can't handle it this milestone, we will tackle it when @piensaenpixel arrive there, right @javierarce ?

**Comment by javierarce** [comment]
Yes

**Comment by piensaenpixel** [comment]
i think this is something we can't attack now. it was so difficult. So closing then
