### ISSUE TITLE
Change dataset privacy is not working for "standard" users

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#9465]
Checking the problem, we have realized that, for a user that doesn't belong to an organization, the dialog is useless because only the header (for changing the privacy) would appear.

This publish dialog belongs to "standard" user in a map:

![screen shot 2016-08-17 at 15 32 50](https://cloud.githubusercontent.com/assets/132146/17738036/e423d014-648f-11e6-92af-4fcfb3e4230a.png)

For a dataset we remove the "central" part, so...

Possibilities:

1. Open a dropdown (not a modal), just for changing the privacy. Bad part is CTA, where to include it?.
2. Open a totally different dialog (with the new design) and only offering the privacy change.

cc @saleiva @urbanphes @piensaenpixel

**Comment by saleiva** [comment]
I'd go with the dropdown option since we already have it. the CTA, can we mimic the one on the header of the modal?

**Comment by xavijam** [comment]
How is that one? Because the only CTA I've seen in that view appears in the footer, thanks.

**Comment by josecruz** [comment]
Hey I upload here the last version, maybe @saleiva can help with the copy. Thank you @xavijam for spotting this!
![-01 dataset - 00-01 data - no info copy](https://cloud.githubusercontent.com/assets/596509/17776082/5d0044d8-655b-11e6-9124-3e7eb2f3ee68.png)

**Comment by xavijam** [comment]
Thanks @josecruz, one more thing. Trial could be possible or not, because the user tried it and then go back to the FREE plan, just in case, :kiss:.
