### ISSUE TITLE
Image style for Infowindows show the url

### ISSUE THREAD

**Issue by jsanz** [CartoDB/cartodb#9469]
## STR

1. Create a new map with a dataset that contains a field with an image url
2. Apply the popup style with an image on the header
3. Put the image field as the first one to be used on the header

![2016-08-17_15 49 15_selection](https://cloud.githubusercontent.com/assets/188264/17744402/d22d84fa-64a7-11e6-8155-531f3871fcb3.png)

## Expected result

The image is used on the header and the next field on the list is used as a title

## Current result

The image url is used as a title

![2016-08-17_15 55 12_selection](https://cloud.githubusercontent.com/assets/188264/17744342/9e0e6342-64a7-11e6-8c92-5984bb7cba20.png)

**Comment by matallo** [comment]
if I'm not wrong this belongs to carto.js

**Comment by jsanz** [comment]
OK, sorry! :innocent:

**Comment by matallo** [comment]
noo prob, I'll discuss with @xavijam how to proceed with this, thanks for reporting!
