### ISSUE TITLE
inconsistent data tab in editor panel when sql error, error when change from analysis tab

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#9475]
first of all sorry for the long title, I didn't know how to best write it

1. this is a series of issues that while related, they can be taken apart separately, first of all I find it weird when applying an error SQL query I can go to the data in the map and see the error

however, when I disable the sql the data tab still shows data from before appying the query, so if we show an error in one side I think we should be consistent at least not showing the data

---

2. besides this, if instead of directly disable sql you go to "analysis" and then back to "data" instead of showing the sql panel it shows the data panel indeed now with no data but an infinite load

![sqlerror](https://cloud.githubusercontent.com/assets/36676/17772681/763286b6-654a-11e6-8f72-fe347d38b6db.gif)

/cc @nobuti for the sql panel
/cc @saleiva for inconsistency issue
/cc @xavijam  for general awareness

not sure who to assign tho, maybe this can be tackled at the same time idk

**Comment by nobuti** [comment]
Closed by #9563.
