### ISSUE TITLE
Losing base CartoCSS properties when going between different aggregation types for points

### ISSUE THREAD

**Issue by makella** [CartoDB/cartodb#9476]
If you have a point dataset, symbolize it using Aggregation>Animation (for example) and then decide to go back to Aggregation>None, I've noticed that `marker-allow-overlap: true` disappears. 

So unless a user knows to add that in the CartoCSS pane, they are not seeing the full view of their point data:

![styling-3](https://cloud.githubusercontent.com/assets/1566273/17776356/2e54f51a-652a-11e6-8e86-2f6b84964394.gif)

**Comment by xavijam** [comment]
Seems like we have fixed that problem 💃  yay!

**Comment by xavijam** [comment]
Thanks for your feedback @makella 💋

**Comment by makella** [comment]
awesome!
