### ISSUE TITLE
option for a 'keep all geometries' for "intersect second layer"

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartodb#9480]
Currently there is an inner join (actually a WHERE condition) on the "intersect second layer" analysis. This is fine for some cases, but often someone wants to do the aggregation (counts, for example) of the number of points in a polygon. If there is no intersection, the polygon is filtered out instead of filling the count column with ZERO.

Instead, having an option for LEFT or RIGHT JOINs is needed to allow users more control on the outputs, and then something like `coalesce(count(*), 0)` to take care of the proper counting, summing, averaging, etc. etc.

cc @stuartlynn @rochoa

**Comment by noguerol** [comment]
@dgaubert is engine supporting this?

**Comment by dgaubert** [comment]
Hey!

I've just checked it: no, we are NOT supporting this for `intersect second layer`. We need to add an option in the same way as we do with `merge` analysis in order to perform `right`, `left` or `inner` joins.

**Comment by alrocar** [comment]
Stale issue. Closing 👋
