### ISSUE TITLE
There's no way of adding rows on a dataset from the Builder

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#9487]
OS: mac OS El Capitán 10.11.5
Browser: Chrome Version 51.0.2704.106 (64-bit)
CARTO Account used when this happened: arianaescobar
## Issue

On the builder, when I go into a dataset layer and then I select the table view **I have no way of adding rows**. Although I can add columns: 

<img width="1680" alt="screen shot 2016-08-19 at 16 52 00" src="https://cloud.githubusercontent.com/assets/16247628/17813841/47d309ec-662d-11e6-8508-7f65b039bf5c.png">
## Expected behaviour

I should be able to add rows from the Builder. I know there's a button on the mockups to do it (add rows). 

<img width="365" alt="screen shot 2016-08-19 at 17 00 23" src="https://cloud.githubusercontent.com/assets/16247628/17814132/9e922190-662e-11e6-8e06-fd4e8ce2cede.png">
### Note

As a sidenote, If I go into the dataset (outside the map), where I can add rows:

<img width="1680" alt="screen shot 2016-08-19 at 16 57 06" src="https://cloud.githubusercontent.com/assets/16247628/17813992/fe35387c-662d-11e6-8d42-3df811ecd907.png">

 and then come back to the map and follow those same steps, it does let me add more rows: 

<img width="1676" alt="screen shot 2016-08-19 at 16 57 56" src="https://cloud.githubusercontent.com/assets/16247628/17814010/1b4a637e-662e-11e6-9ad1-4d6142845301.png">

**Comment by saleiva** [comment]
Closing, its a dupe! https://github.com/CartoDB/cartodb/issues/9487
