### ISSUE TITLE
"duplicate query" option somehow hidden

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#9488]
_Disclaimer: just an opinion._

When you apply a query to a dataset, in order to create a new one based on the results of the query you have to go to the three dots top menu, and there click "Duplicate query". IMHO that's a little hidden, and naming is not too clear (I don't want to _duplicate_ any query but _create_ a dataset). Maybe I'm too biased with previous design, but there's plenty of room at the bottom to add a "Create dataset from query" button if a query is applied.

cc @saleiva

**Comment by saleiva** [comment]
Super +1.

For the time being I'd change the text to "Duplicate dataset from query"
And assigining to @urbanphes to improve this

**Comment by urbanphes** [comment]
Related to https://github.com/CartoDB/design/issues/42

**Comment by ramiroaznar** [comment]
+1 cc @stevelewis99 

We should make "Create new dataset from query..." to stand out, it would be great to move this option as the "Create map" showed here https://github.com/CartoDB/cartodb/issues/8981

@CartoDB/design are you asking users about the dataset UI?

**Comment by urbanphes** [comment]
@ramiroaznar But is not the same. 
On the Table View, the main action is "Create a Map" independently if there is or not a query applied. The final step after watching the data is create a map. But inside Builder, and more specifically when you are on an Advance Mode (SQL) there are another actions possibles and "Create a Map" it would take you out of the flow in which you are.

**Comment by ramiroaznar** [comment]
I am only talking about the DATASET VIEW (outside BUILDER). As you said, the main action is Create a map, but IMHO (and from my BUILDER user experience), after applying a query, if not the main action, creating a dataset is the second option...

**Comment by piensaenpixel** [comment]
we are not asking about it, @ramiroaznar.

But @ramiroaznar we have that option in the drop-down, you mean this one right?

![image](https://user-images.githubusercontent.com/1214201/33475320-44da76ea-d67e-11e7-9155-d2958294fdd2.png)

**Comment by ramiroaznar** [comment]
Yes, as mentioned in person, I think it is quite hidden.

**Comment by piensaenpixel** [comment]
ok, we'll take a look :) thanks a lot.

**Comment by alrocar** [comment]
Stale issue. Closing 👋
