### ISSUE TITLE
At time series column picker I can't scroll until the end

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#9489]
![screen shot 2016-08-19 at 17 36 21](https://cloud.githubusercontent.com/assets/932968/17815210/8f6f050c-6633-11e6-922c-d931af7af35d.png)

As you see I can't pick the two last columns. There're 47 columns

cc @xavijam

**Comment by xavijam** [comment]
We have to review that problem with the new modals @piensaenpixel

**Comment by piensaenpixel** [comment]
i take a look

**Comment by saleiva** [comment]
It happens on every widget type tab
