### ISSUE TITLE
Privacy dropdown breaks on publish modal

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#9495]
When you select "Share with Password", header content moves:
![image](https://cloud.githubusercontent.com/assets/596509/17849784/b2a813be-685a-11e6-899e-fe65d9429501.png)

**Comment by xavijam** [comment]
BTW, the "share" permissions dialog being in a dataset view (and of course, belonging to an organization), says "published xxxxx ago". And it should say: "updated xxx ago".

![screen shot 2016-08-22 at 12 51 06](https://cloud.githubusercontent.com/assets/132146/17852359/3c74f74a-6867-11e6-8802-b2cb64a3f530.png)
