### ISSUE TITLE
Data panel doesn't change its state when sql query fails

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#9497]
I've checked that problem before, but I don't remember how to make it fail so, I've decided to reproduce it like:

## STR
1. Create a map with any layer, and go to the builder.
2. Once there, go to your dev environment and stop the SQL API (fast and easy instead of looking for a new way of making it fail).
3. Go back to the builder UI.
4. Click over one layer, and check that panel doesn't change its state. It should show an error message and the loading should be hidden.

![screen shot 2016-08-22 at 11 41 30](https://cloud.githubusercontent.com/assets/132146/17850511/cc1f7d52-685d-11e6-8183-4e7b5bb7bd0c.png)

**Comment by saleiva** [comment]
Let's add text with "Errors found in your SQL query. Fix them before continuing."
