### ISSUE TITLE
Create an endpoint displaying the last&current changes in the map

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#9498]
Something like WordPross has with drafts...
@rochoa's idea.

cc @saleiva @gfiorav @javisantana

**Comment by gfiorav** [comment]
Perfectly doable. This just involves 2 different vizjsons to be handle side by side.

What's the priority on this?

**Comment by xavijam** [comment]
Not priority, @rochoa's mentioned and I liked it, what do you think?

**Comment by gfiorav** [comment]
Pretty cool. We can do this with no efforts using mapcaps and it shows off the product capabilities nicely. I'd go for it ASAP!
