### ISSUE TITLE
Analysis first step title is not completely right

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#9508]
The original designs says "Your Workflow (X)" while X is the number of steps already applied.

![screen shot 2016-08-22 at 17 43 26](https://cloud.githubusercontent.com/assets/132149/17861061/e4be7c28-688f-11e6-9061-bde9b66c4b8d.png)

**Comment by xavijam** [comment]
@MariaCheca, could you take a look? If you need help, let me know and we will check it together.
