### ISSUE TITLE
Create table from query option yields error having selected lat/lon columns as number types

### ISSUE THREAD

**Issue by Kartones** [CartoDB/cartodb#951]
Steps to reproduce:
1. Import table attached to this ticket.
2. Apply the following SQL query: SELECT geoid10 AS zip, intptlat10 AS lat, intptlon10 AS lon FROM test_wrong_query
3. Click on "Create table from query" and click on "Create table" (leave the suggested table name as it is)
4. A 8003 error message appears
5. Convert the "intptlat10" and "intptlon10" columns to number type from the CartoDB GUI.
6. Apply the SQL query again.
7. Click on the "Create table from query" link and click on "Create table" (leave the suggested table name as it is)
8. A 8004 error message appears.

Log message for 8003 error:
"2014-09-29 14:26:00 UTC: Going to set merge error with code 8003\n2014-09-29 14:26:00 UTC: Additional error info: PG::Error: ERROR:  parse error - invalid geometry\nHINT:  \"POINT(-118.0148791 +4\" <-- parse error at position 21 within geometry\n\n2014-09-29 14:26:00 UTC: After dispatch\n2014-09-29 14:26:00 UTC: ERROR!\n\n"}"

Log message for 8004 error:
"Going to set merge error with code 8004\n2014-09-29 14:36:15 UTC: Additional error info: PG::Error: ERROR:  function pg_catalog.btrim(double precision) does not exist\nLINE 4:                 'POINT(' || trim(\"lon\") || ' ' || trim(\"lat\"...\n                                    ^\nHINT:  No function matches the given name and argument types. You might need to add explicit type casts.\n\n2014-09-29 14:36:16 UTC: After dispatch\n2014-09-29 14:36:16 UTC: ERROR!\n\n"}"

Another error message: when running the SQL command "SELECT trim(intptlat10) FROM test_wrong_query" the following error message appears: "function pg_catalog.btrim(double precision) does not exist"
   {
      "attributes": {
        "OBJECTID": 1,
        "WDPAID": 991,
        "NAME": "Name of object 1"
      },
      "geometry": {
        "fake": "geom"
      }
    }
 
After printing some debug messages on the code, I arrived at the following code section which may have something to do with this issue: https://github.com/CartoDB/cartodb/blob/b81562bfbd42930e933316fe569d619ba971f630/lib/importer/lib/cartodb-migrator/migrator.rb#L110

Sample data to reproduce:
```
cartodb_id,intptlon10,intptlat10,created_at,updated_at,the_geom,random1,random2,geoid10
1,+44.2468051,-117.6469773,2014-09-29 14:43:09.734281+00,2014-09-29 14:45:00.684565+00,,jkfdjfksdjfl,randomness,07003
2,+14.2468051,+44.2468051,2014-09-29 14:43:13.247619+00,2014-09-29 14:53:17.046889+00,,fdsfdsf,aloha,10992
3,+6.2468051,+117.6469773,2014-09-29 14:43:36.266303+00,2014-09-29 14:53:21.595758+00,,fdsfsd,blabla,45672
4,+44.2468051,+90.2324343,2014-09-29 14:43:38.720015+00,2014-09-29 14:53:24.925953+00,,djfsldf,something,28932
```

**Comment by ethervoid** [comment]
This error don't happens anymore. Closing
