### ISSUE TITLE
Change DO fields order

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#9510]
New column name should be at the end of the analysis
![01 layers - 06-100 analysis - enrich from do](https://cloud.githubusercontent.com/assets/132149/17861192/550c8146-6890-11e6-9cbc-b7fe45459744.png)

The last component should be a dropdown but would let you add a new column by typing an string

**Comment by saleiva** [comment]
Prioritizing sice it's potentialy easy and it's important on usability. Let me know if not possible.

**Comment by saleiva** [comment]
cc/ @xavijam

**Comment by javierarce** [comment]
> The last component should be a dropdown but would let you add a new column by typing an string

@saleiva: A dropdown filled with the names of the dataset columns?

**Comment by javierarce** [comment]
> The last component should be a dropdown but would let you add a new column by typing an string
@saleiva: A dropdown filled with the names of the dataset columns?
@dgaubert: If that's the case, is the analysis ready to accept an existing column in the `final_column` field?

**Comment by dgaubert** [comment]
In that case it's going to fail, DO creates always a new column and if the column name is present we get the following error: 

```
{
    "errors": ["column \"name\" specified more than once"],
    "errors_with_context": [{
        "type": "analysis",
        "message": "column \"name\" specified more than once",
        "analysis": {
            "id": "a2",
            "type": "data-observatory-measure"
        }
    }]
}
```

If we want to override the column content we have to be careful because the column type could not be the same.

**Comment by saleiva** [comment]
depending on the measurement and segment we can know which types are compatible right? and therefore which colums we could use...

**Comment by javierarce** [comment]
Yes, I guess that if I was able to extract the type from the measurement and segment I could filter the combo.

**Comment by javierarce** [comment]
> Prioritizing sice it's potentialy easy and it's important on usability. Let me know if not possible.

This is not true anymore. Should we split the ticket or update the title?
