### ISSUE TITLE
Make layer from node more accesible

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#9513]
Although I love the drag and drop interaction, It's really hard to discover

**Comment by urbanphes** [comment]
The visual design is on https://github.com/CartoDB/design/issues/69

**Comment by piensaenpixel** [comment]
hey @nobuti i've just uploaded the dropdowns (also the translations) and the three points buttons, but... we now is your turn, we need detect if we open the dropdown to the right or to the left, or up or down. And also remember we need open only one dropdown :( sorry!

**Comment by nobuti** [comment]
@piensaenpixel branch? So things to be done:

- [ ] Dropdown position
- [ ] Dropdown opening weirdos when nested
- [ ] Layer creation logic

Right?

**Comment by nobuti** [comment]
> 9513-add-layer-dropdown

**Comment by ramiroaznar** [comment]
This is really cool and necessary if we want to show BUILDER as a drag and drop tool. cc @noguerol

**Comment by piensaenpixel** [comment]
+1

**Comment by alrocar** [comment]
Stale issue. Closing 👋
