### ISSUE TITLE
Add new methods for service usage

### ISSUE THREAD

**Issue by jmartinter** [CartoDB/cartodb#9515]
We are interested in tracking user activity (I mean number of requests to each of the available services done by the user) As this info is already stored in Redis, we just need to add some new methods to collect it:
- get geocodings requested by user
- get isolines requested by user
- get DO snapshots requested by user
- get DO obs general requested by user

As existing methods, these new ones should allow to provide a time range as parameter.
If we could get this info by service provider, it would be great (a different method per provider is ok) 

cc'ed @rafatower

**Comment by rafatower** [comment]
Just to clarify: the new methods should be similar to `User#get_here_isolines_calls` and friends but get it per user, regardless of whether they are org or individual users:

https://github.com/CartoDB/cartodb/blob/c34cc1fa45b8dec79fe02ebb052db3dce3288500/app/models/user.rb#L974

https://github.com/CartoDB/cartodb/blob/7853e8bb05738cba49de6e0ede9c7060d238c5ab/app/helpers/data_services_metrics_helper.rb#L68

https://github.com/CartoDB/cartodb/blob/ebfb0e62bfdb6bd941408b4d2f0826b3195318fb/services/dataservices-metrics/lib/service_usage_metrics.rb#L28-L36

**Comment by rafatower** [comment]
Also note existing methods and quota logic should not be modified.

**Comment by jmartinter** [comment]
One idea. Instead of creating a new method for service, why don't code a generic method to retrieve metrics from redis we can pass 'service' and 'metric' as parameter (besides time range)? It would be easier to maintain
@iriberri

**Comment by iriberri** [comment]
See: https://github.com/CartoDB/cartodb/pull/9668. This PR adds some missing services and providers (Routing, +mapzen Isolines/Geocoder) that are required to have full metrics on the services.

What is requested here is already possible with our current code. I wrote it up in our internal documentation, check the usage_metrics file (`cartodb-internals/source/platform/internal_architecture/services/platform/dataservices-api/usage_metrics.rst`) for code samples and instructions.
