### ISSUE TITLE
Prefix sql query with user when the dataset is shared inside org

### ISSUE THREAD

**Issue by nobuti** [CartoDB/cartodb#9516]
If an owner is working with a dataset, the default query (or custom) doesn't include the user prefix for tables' names. If this user shares the dataset with another user, the data visualisation fails because `the relation doesn't exist`. It's necessary to prefix the table's name with the owner's name in order to work properly.

~~Also, there is an inconsistency between the view when the dataset is shared with read permission and write and read permission. In the first scenario, the user is redirected to the public view.~~

**Comment by xavijam** [comment]
About the second paragraph, @javitonino is going to fix it.

**Comment by javitonino** [comment]
Second part fixed!
