### ISSUE TITLE
Metrics tracker for Builder

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#9522]
Create frontend tracker to send events in the builder to the back.

- [x] Created analysis
- [x] Modified analysis
- [x] Removed analysis
- [x] Created map
- [x] Deleted map
- [x] Exported map
- [x] Published map
- [x] Created dataset
- [x] Deleted dataset

**Branch**: frontend-metrics

**Comment by xavijam** [comment]
cc @gfiorav

**Comment by xavijam** [comment]
Related with https://github.com/CartoDB/cartodb/pull/9521.

**Comment by MariaCheca** [comment]
👍
