### ISSUE TITLE
Named maps JSONP instantiation

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb#9523]
Previous public pages use JSONP endpoint for intantiation:
https://documentation.cartodb.com/viz/2a1b745a-e219-11e4-a4f2-0e018d66dc29/public_map

New embeds use a POST to instantiate:
https://documentation.cartodb.com/builder/2a1b745a-e219-11e4-a4f2-0e018d66dc29/embed

JSONP endpoints are more cache friendly and we should try to use them when the params fit into the URL, and in case the payload is too big, then fallback to POST/CORS.

cc @xavijam

**Comment by xavijam** [comment]
Well, map instantiation happens in CartoDB.js, but I really like to see the track here too :)

**Comment by alonsogarciapablo** [comment]
Closed via https://github.com/CartoDB/cartodb.js/pull/1398
