### ISSUE TITLE
Add color ramp names to Turbo Carto output

### ISSUE THREAD

**Issue by makella** [CartoDB/cartodb#9528]
There is a really practical reason for adding either `colorbrewer( )` or `cartocolor( )` ramp names to write by default to Turbo Carto properties. This is already part of Turbo Carto so it seems to be a matter of implementing it into Builder defaults.

If you make a choropleth map through Builder form with 5 classes using quantile, and one of our available ramps, the Turbo Carto output is like this:

```
#layer {
    polygon-fill: ramp([masters_degree], (#f3cbd3, #e498b4, #ca699d, #a24186, #6c2167), quantiles);
  ....
}
```

What if you want to change the number of classes to <5 or even >5? You run into a big problem.

Let's say, I wanted 3 classes instead:

```
#layer {
  polygon-fill: ramp([masters_degree], (#f3cbd3, #e498b4, #ca699d, #a24186, #6c2167), quantiles(3));
  ....
}
```

The way Turbo Carto works is that it takes the first 3 colors (`#f3cbd3, #e498b4, #ca699d`) and assigns to each bin. 

The problems with this:
- we don't get the variation in color that we would expect for fewer classes
- the actual 3 class version of the palette (`#f9ddda,#ce78b3,#573b88`) is not assigned 

Similarly, if we increase the number of classes manually, the colors we do have, are somehow (?) assigned to the 7 buckets -- not good!

In order to fully take advantage of ColorBrewer and CartoColor palettes, we need them to automatically update the colors on the map as class breaks are changed manually using Turbo Carto.

For example, if the above choropleth was written like:

```
#layer {
  polygon-fill: ramp([masters_degree], cartocolor(PurpOr), quantiles(5));
  ....
}
```

and then for 3 classes,

```
#layer {
  polygon-fill: ramp([masters_degree], cartocolor(PurpOr), quantiles(3));
  ....
}
```

We get the right version of the ramp for that number of classes. Right now, this is very manual and takes some expert knowledge to figure out.

cc @saleiva @rochoa

**Comment by ramiroaznar** [comment]
This is already implemented, right @makella?

**Comment by makella** [comment]
@ramiroaznar not yet

**Comment by alrocar** [comment]
Stale issue. Closing 👋
