### ISSUE TITLE
Exporting a dataset from shared dataset view has wrong filename

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#9529]
1. Go to the builder read-only view of a dataset that has been shared with you 
2. Export the dataset
3. The downloaded file has the name of the dataset owner. The download link is:
   `https://<your_user>.carto.com/api/v2/sql?filename=<dataset_owner>.<dataset_name>&q=SELECT+*+FROM...`

It should have the name of the dataset. It appears the SQL API drops everything after the dot in the filename parameter.

**Comment by javitonino** [comment]
Still an issue. cc @ivanmalagon @ramiroaznar 

It can be annoying for some big organizations which use dataset sharing a lot, since the downlaoded files all have the name of the owner of the dataset, which makes it very confusing.

**Comment by alrocar** [comment]
Stale issue. Closing 👋
