### ISSUE TITLE
Widgets/dataviews auto [invalid] index

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb#9537]
I was reading [Problems with concurrent Postgres indexes (and how to solve them)](https://medium.com/carwow-product-engineering/problems-with-concurrent-postgres-indexes-and-how-to-solve-them-c57f7656c852) from [Postgres Weekly](http://postgresweekly.com/) and decided to see if I had invalid indexes in my installation.

I have some with the [`_auto_idx_` prefix](https://github.com/CartoDB/cartodb/blob/0e6d2c502931baffbdbf227ea773747030cd2045/app/services/carto/user_table_index_service.rb#L4). That's why I went with that title for the issue. But it could happen with anything using [Table.create_index with concurrent=true param](https://github.com/CartoDB/cartodb/blob/0e6d2c502931baffbdbf227ea773747030cd2045/app/models/table.rb#L1124).

I don't think this is critical but I wanted to report it just in case you think it's possible to improve it.

cc @javitonino

**Comment by javitonino** [comment]
Right now, only auto indexing uses concurrent index creation, so correct on the title. Will look at deleting invalid indexes, probably before autoindexing tries to run. Right now, this is ignored, but if we are seeing invalid indices, a fix will be in order. Taking it.

**Comment by rochoa** [comment]
❤️  Thank you!
