### ISSUE TITLE
remove parent_id from layer model

### ISSUE THREAD

**Issue by Kartones** [CartoDB/cartodb#954]
It's no longer needed,and it is slowing down Layer write operations by searching for non-existing parent/children.

Check also `chldren` as probably isn't used either.

Branches: 
`954-remove_layer_parent_id`
To release after the code/previous one:
`954-remove-db-parent_id-field`
and then frontend part removal (and remaining traces):
`954-FE-layer-parent_id-removal`

**Comment by Kartones** [comment]
Based on the performance improvement graphs, if this is not used it consumes time for nothing, so taking it for implementing ASAP

**Comment by Kartones** [comment]
@javisantana @xavijam Are there plans of removing frontend code after I release the two related branches that cover this ticket? Because I have had to kept empty fields for JS compatibility, and if we're not using the fields, would be nice to remove every trace...

**Comment by javisantana** [comment]
I don't think they are being used, don't you remember we finally used a different approach?

**Comment by Kartones** [comment]
Yep, indeed they aren't used, the thing is if you want me to remove this from JS too, someone else will do, etc. as this ticket was refering only to the backend part.

**Comment by Kartones** [comment]
I'm going to assume then a "yes, remove them" and create a ticket for it after releasing all backend-related ones.
