### ISSUE TITLE
Issues with letters on layers

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#9545]
There have been some feedback from users about the way we asign letters to layers. Right now, letters that are attached to layers that are deleted are occupied again by new layers which is a weird behaviour.

What I propose is that when deleting a layer, we re-assign the letters of the other layers to cover always the first letters of the "abcdary".

So if you have layer A, B and C, and you delete layer B, you will end up having A and B.
If you have A,B and C and you create a layer out of a node, it becomes layer D

cc/ @xavijam @javisantana @urbanphes

**Comment by donflopez** [comment]
#9732

**Comment by saleiva** [comment]
getting important prior to the general rollout
