### ISSUE TITLE
Time-Series Widget does not work if dataset doesn't have geometry

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#9546]
Hi @alonsogarciapablo  I see you were working on [this](https://github.com/CartoDB/cartodb/issues/7365) - maybe related?
  
cc @zingbot @saleiva 

## Context
Not sure if this is a bug or something we're going to add in the future - what if a client wants to use widgets to filter non-geospatial data? If we want to support that, right now the Time Series widget isn't loading for datasets with null the_geom.

For example, what if we have a dataset without geometry and we want to use Formula widget to calculate the sum of a numeric column, but only for values filtered by Time-Series widget?

## Process
1. Import a dataset that doesn't contain geometry & create a map from it in Builder.
2. From main map pane click Widgets tab, then Add
3. Choose Time-series & a select a date-type column. Click Continue. Leave the default widget settings.

https://team.carto.com/u/stephaniemongon/builder/3a19e660-6a27-11e6-aec1-0ee66e2c9693/embed

[time_series_null_geom map (on 2016-08-24 at 19.25.30).zip](https://github.com/CartoDB/cartodb/files/435510/time_series_null_geom.map.on.2016-08-24.at.19.25.30.zip)

## Expected result
Filterable time-series widget will appear at bottom of the map.

## Current result

![screen shot 2016-08-24 at 3 21 12 pm](https://cloud.githubusercontent.com/assets/1779444/17944597/79b99ec8-6a0e-11e6-96f6-de069f0a70f8.png)

error: 'the tiler does not support non-torque layers just yet…'

also 400/Bad Request error:

![screen shot 2016-08-24 at 3 22 20 pm](https://cloud.githubusercontent.com/assets/1779444/17944632/96315abe-6a0e-11e6-8f78-3bdcb7f48626.png)

**Comment by saleiva** [comment]
We will not support that. We shouldn't let add widgets if there is no geom on the data, as nothing will work.
