### ISSUE TITLE
Inconsistent hanging analysis & map instantiation failure

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#9547]
hi @luisbosque not sure if i'm assigning correctly here, would you please re-assign if needed?

## Context
@JeretJ & I are performing same analysis w/same datasets/privacy settings. His analysis does not finish but mine completes properly within a few seconds.

Not sure if there's a difference between our accounts that would cause this?

## Process
1. Connect [police precincts dataset](https://team.carto.com/u/stephaniemongon/dataset/ny_policeprecints_copy) & make sure privacy = Private. Create a map from it
2. Connect [liquor authority dataset](https://team.carto.com/u/stephaniemongon/dataset/liquor_authority_quarterly_list_of_active_licenses_20150720_cop) to your account, make sure it's Private, & add it as a layer in the police precinct map above
3. Click ADD ANALYSIS in police precinct map layer
4. Use these analysis settings & click Apply:

![screen shot 2016-08-24 at 6 47 12 pm](https://cloud.githubusercontent.com/assets/1779444/17950761/3cf6e906-6a2b-11e6-8437-2bb4ae99c0fa.png)

## Expected result

Analysis completes:

![screen shot 2016-08-24 at 6 48 47 pm](https://cloud.githubusercontent.com/assets/1779444/17950782/6f0792f6-6a2b-11e6-9d6c-c05bacd15c17.png)

## Current result

[Jeret's version](https://team.carto.com/u/jjenkins-carto/builder/71d01fa2-6a45-11e6-aa49-0e05a8b3e3d7) is hanging:

![screen shot 2016-08-24 at 6 33 31 pm](https://cloud.githubusercontent.com/assets/1779444/17950793/7f75e408-6a2b-11e6-8fc3-27cffe51adf1.png)

![screen shot 2016-08-24 at 6 30 20 pm](https://cloud.githubusercontent.com/assets/1779444/17950796/83f0386c-6a2b-11e6-993c-66eb896b01b1.png)

**Comment by ztephm** [comment]
more info:

![screen shot 2016-08-25 at 10 19 15 am](https://cloud.githubusercontent.com/assets/1779444/17972812/15205092-6aae-11e6-9e62-913173ec248e.png)

{"errors":["Analysis requires authentication with API key: permission denied."],"errors_with_context":[{"type":"analysis","message":"Analysis requires authentication with API key: permission denied.","analysis":{"id":"a1","type":"aggregate-intersection"}}]}

@ramiroaznar just gave me a heads up that it could be related to [this](https://github.com/CartoDB/cartodb-management/issues/4551)

**Comment by xavijam** [comment]
Yes, same problem.
cc @rochoa

**Comment by ztephm** [comment]
these analyses are working now in jeret's account, thanks!
