### ISSUE TITLE
Logo appears on top of pop-ups on embeds

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#9549]
Not sure if a 🐛  or a ✨  😄 

**STR**:

* Create a map with infowindows
* Open the embed and try to position the pop-ups over the logo at the bottom

On hover:

  ![image](https://cloud.githubusercontent.com/assets/1730320/17961387/a99c9daa-6aab-11e6-9447-ef19c2a3c1eb.png)

Click:

  ![image](https://cloud.githubusercontent.com/assets/1730320/17961396/c57d9178-6aab-11e6-8c7d-6da17e9a248c.png)

**Comment by xavijam** [comment]
Issue moved to [CartoDB/cartodb.js #1404](https://github.com/CartoDB/cartodb.js/issues/1404) via [**ZenHub**](https://www.zenhub.com/)
