### ISSUE TITLE
Maps without the_geom or the_geom_webmercator

### ISSUE THREAD

**Issue by nobuti** [CartoDB/cartodb#9552]
Maps without these columns will fail on instantiation, and I think in this case we should improve the notification we are showing right now: `This map couldn't be rendered. Please refresh the page and contact us if the error persists.` .

Not sure if we need to tackle this scenario, so feel free to close the issue if not.

What do you think @saleiva @urbanphes @xavijam?

**Comment by saleiva** [comment]
please, I'd say. 

"There is no geometry data in your dataset. Add a Georeference analysis to it in order to get started"

**Comment by saleiva** [comment]
BTW, well spotted!

**Comment by nobuti** [comment]
credits to @xavijam, my part was only to freak out trying to spot the error

**Comment by ramiroaznar** [comment]
@piensaenpixel this is going to take care thanks to the onboarding fixes, right?

**Comment by ramiroaznar** [comment]
Close in favor of https://github.com/CartoDB/cartodb/issues/9734
