### ISSUE TITLE
Data imported from .carto (gpkg) includes a fid column

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#9559]
It looks like importing dpkg datasets -- which occurs when importing a .carto file -- is generating a `fid` column. Not sure if this is a problem in the export (perhaps there's a way to tell the format to use `cartodb_id` as ID column) or perhaps it's in the import.

Note: This `fid` column is of course not in the origin table. It gets created during the export/import process.

cc @juanignaciosl FYI, I'll take a look when I can

**Comment by juanignaciosl** [comment]
Yes, [it's a column added by GeoPackage format](http://www.gdal.org/drv_geopackage.html). In fact it's a problem if the user table already has a `fid` column (this happened once), which could be avoided with a parameter on export (it could be renamed to carto_fid or any other namespaced alternative so it doesn't generate collisions).

 _Maybe_ we could drop the column on GeoPackage import, as we know that the `fid` column is not actually needed. Not sure whether this is needed or even convenient though.

**Comment by iriberri** [comment]
Is the gpkg built directly from the SQL API?

**Comment by iriberri** [comment]
Okay, I found it: https://github.com/CartoDB/CartoDB-SQL-API/blob/master/app/models/formats/ogr/geopackage.js

Wondering if we can add the `FID = cartodb_id` option there, as in http://www.gdal.org/drv_geopackage.html

**Comment by juanignaciosl** [comment]
I thought about that fid <-> cartodb_id, but felt risky 😅

**Comment by juanignaciosl** [comment]
Corollary: exporting a table with a `fid` column fails. cc @oriolbx

**Comment by iriberri** [comment]
Does that `fid` column follow the properties of a primary key? (numeric, unique, not-null)

**Comment by juanignaciosl** [comment]
Yes. Using it for `cartodb_id` worths a try.

**Comment by juanignaciosl** [comment]
This is happening quite often, I'd suggest to give this a thought and fix it. Map export/import implementation is shared between builder and dataservices team, so I don't know who should add if to the roadmap if you agree (and it's feasible, of course!) cc @rafatower @xavijam

**Comment by javitonino** [comment]
Did a quick check using ogr2ogr manually and adding `-lco FID=cartodb_id` on the export seems to fix this issue, no changes needed in the importer. It properly keeps the same id's as it uses cartodb_id for a primary key instead of having to invent a new one.

**Comment by rafatower** [comment]
that's very good news, as changing the guessing logic is way trickier than that.

**Comment by rafatower** [comment]
Assigning to @javitonino Get it back to me if you don't agree. Thanks!

**Comment by javitonino** [comment]
Fixed via https://github.com/CartoDB/CartoDB-SQL-API/pull/404
