### ISSUE TITLE
After georeferencing a table w/ x, y cols you cannot modify table field type, etc. 

### ISSUE THREAD

**Issue by nygeog** [CartoDB/cartodb#9564]
@joepringle found this error while importing  this Vision Zero data from DC open data: http://opendata.dc.gov/datasets/3f28bc3ad77f49079efee0ac05d8464c_0

If you download as spreadsheet, the lat/lng col's are named as y/x (resp.,). So if you import the dataset, then hit create map, no geometry, so then you Georeference using the y/x fields as Analysis. 

@joepringle said he was having some trouble generating widgets, but also once the data was Analysis/Georeference(d) the ability to change the field data types no longer shows up. 

![screen shot 2016-08-25 at 11 35 34 am](https://cloud.githubusercontent.com/assets/2790599/17975550/2497aa98-6ab8-11e6-82f0-9e6250b2292d.png)

Our workaround in the meantime was to simply rename the columns to latitute, longitude before the import so the platform recognizes that and assigns geometry automatically.

**Comment by saleiva** [comment]
When you add an analysis to a layer it becomes read-only, this is why you cannot change the schema of the dataset.

**Comment by xavijam** [comment]
That's true as @saleiva has pointed out, but we will provide the option to "merge" all analysis to one layer and add it to the map in order to provide more options over your new data. Stay tuned!
