### ISSUE TITLE
Feature Request: scatterplot widget

### ISSUE THREAD

**Issue by nygeog** [CartoDB/cartodb#9565]
It'd be cool to have widgets with a scatterplot. 

![scatter](http://www.stat.yale.edu/Courses/1997-98/101/scatex.gif)

**Comment by xavijam** [comment]
Moving it to deep-insights, where widgets belong.

**Comment by xavijam** [comment]
Issue moved to [CartoDB/deep-insights.js #451](https://github.com/CartoDB/deep-insights.js/issues/451) via [**ZenHub**](https://www.zenhub.com/)
