### ISSUE TITLE
Fix button opacity in the on-boarding

### ISSUE THREAD

**Issue by carlostallon** [CartoDB/cartodb#9571]
should this button in the new on-boarding have opacity?

![image](https://cloud.githubusercontent.com/assets/1712650/18002146/7b19c9b8-6b86-11e6-98d0-b46e3fe4d036.png)

**Comment by xavijam** [comment]
I don't know, but it has. Shouldn't it have?

**Comment by carlostallon** [comment]
@josecruz told me not
