### ISSUE TITLE
Frontend issue when creating too many widgets at once 

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#9581]
I created around 12 category widgets at once and...

![image](https://cloud.githubusercontent.com/assets/1730320/18013639/4d627f9a-6bbf-11e6-8ed9-55f9b3be5062.png)

cc @xavijam

**Comment by xavijam** [comment]
This is a good one, we should aggregate notifications, but not an easy task.

cc @nobuti @saleiva @urbanphes

**Comment by saleiva** [comment]
There are several tickets about aggregating notifications I think...

**Comment by urbanphes** [comment]
Reference https://github.com/CartoDB/design/issues/53

**Comment by ramiroaznar** [comment]
Tested. This is fixed.
