### ISSUE TITLE
Delete Functionality of Uploaded Marker Asset Does Not Work

### ISSUE THREAD

**Issue by michellechandra** [CartoDB/cartodb#9583]
## Context
It is not possible to delete a custom marker image that has been uploaded to a user account.

## STR
Create a map of points. Set the visualization style to "Simple". Click on the "img" option for the marker to set the marker style to an image icon. 
![screen shot 2016-08-26 at 10 13 29](https://cloud.githubusercontent.com/assets/5423288/18014014/cad844fe-6b75-11e6-8b1f-e32c37fdc5d4.png)

In the panel that opens, you will see uploaded marker images. Click on the lower right hand side of the uploaded markers to delete the marker image. Nothing will happen.
![screen shot 2016-08-26 at 10 09 34](https://cloud.githubusercontent.com/assets/5423288/18014027/d3286fbc-6b75-11e6-8759-82964e03ec8a.png)

Click out of the upload marker screen by selecting the "X" button in the upper right hand side.

On the map, a popup window with "Delete this" will appear.
![screen shot 2016-08-26 at 10 09 45](https://cloud.githubusercontent.com/assets/5423288/18014034/e0b75ce2-6b75-11e6-9dda-babad5c2df53.png)

## Current Result
Nothing happens when clicking on the delete option of the uploaded marker.

After selecting out of the window, a popup window with "Delete this" appears briefly on the map.
![screen shot 2016-08-26 at 10 09 45](https://cloud.githubusercontent.com/assets/5423288/18014039/ebd7954c-6b75-11e6-85a4-618ce6a82b6d.png)

## Expected Result
Some sort of functionality/option/menu to delete the uploaded marker should appear and marker should be deleted from user's account.

**Comment by michellechandra** [comment]
S/B: 9778672

**Comment by saleiva** [comment]
Will be fixed on the builder. Thanks!!
