### ISSUE TITLE
Disabling the scroll wheel zoom does not work

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#9585]
### STEPS (in the old Editor)

* Create a map (with the `scroll wheel zoom` option disabled)
* Embed the map within a web or mobile app.
* Scroll down the web/mobile page. When you get to the embed map, the page scrolling stops and the zooming starts.

A couple of users has reported this behaviour in GIS SE ([here](http://gis.stackexchange.com/questions/208424/turning-off-the-scroll-to-zoom-functionality-in-cartodb#comment317055_208460) and [here](http://gis.stackexchange.com/questions/207440/css-trick-to-add-margin-on-cartos-embedded-iframe-for-mobile#comment316196_207894)), you can check the behaviour [here](http://www.the10and3.com/how-people-in-calgary-get-to-work/).

**Comment by ramiroaznar** [comment]
cc @matallo

**Comment by matallo** [comment]
AFAIK we're not moving forward with old editor issues unless something is really broken, I'd take this into account for new builder though

**Comment by ramiroaznar** [comment]
Ok, I understand. I will communicate the users.
