### ISSUE TITLE
Import timeouts are happening from the import_cleanup process at Table model

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#9588]
This part of the code is using connections to the database "as superuser". Perhaps we should switch it by the new methods (direct connections or transactions with timeout) we've been using lately.

https://github.com/CartoDB/cartodb/blob/6f060448fb68288d7f9695906df4b556c213b6fc/app/models/table.rb#L302

**Comment by iriberri** [comment]
cc @oriolbx

**Comment by iriberri** [comment]
Started to check this. The import_cleanup process is actually flagged as potential code to be removed because the CartoDBfication already manages similar issues at `_CDB_Has_Usable_Primary_ID`. I'm gonna study it to see if it can be completely dropped, or otherwise treat better the timeout.

**Comment by iriberri** [comment]
There's a difference between this code and CartoDBfy: the ruby part gets rid of other known columns, generated usually by Ogr2ogr which are used as PK, but CartoDBfication doesn't. Removing the code without changing the PK name in ogr2ogr would provoke that exporting and importing a table (with cartodb_id) would add an extra gid column on each import, because this extra column wouldn't be dropped.

**Comment by rafatower** [comment]
Already solved in the mentioned PR, thus closing this.
