### ISSUE TITLE
Centroid Analysis UI should have aggregation in a separated step

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#9589]
![screen shot 2016-08-29 at 12 07 14](https://cloud.githubusercontent.com/assets/132149/18048210/2ef825fe-6de1-11e6-94f8-fe7cf2fdfbe9.png)

**Comment by javierarce** [comment]
Perfect, but that design is the old one for centroids, isn't it?

![screen shot 2016-08-29 at 14 45 54](https://cloud.githubusercontent.com/assets/4933/18051862/60a3d2ae-6df7-11e6-8418-6c27567c6aef.png)

**Comment by saleiva** [comment]
Nope, the original design has been always like the one I attached.

**Comment by javierarce** [comment]
Oh, ok. I was confused with the operation field that appears in the image you uploaded. The reference uses not only the operation for the aggregation, but also the column name.
