### ISSUE TITLE
Custom HTML code breaks Popups

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#9596]
# STR

1 - In **builder** go create a popup and open the HTML code editor: 

![screen shot 2016-08-29 at 14 54 23](https://cloud.githubusercontent.com/assets/10940006/18052052/83f15992-6df8-11e6-90c8-029d71c7e266.png)

2 - Edit HTML code to add some text. Usually, people want to add a unit or percentage or any other symbol after the `{{column}}` moustache placeholder. After applying changes, the text added appears in place of the value: 

![screen shot 2016-08-29 at 14 59 32](https://cloud.githubusercontent.com/assets/10940006/18052228/5455413e-6df9-11e6-9321-5dafd2df55c8.png)

3 - Manually restoring the template removes the new text, but does not restore the value.
 
![screen shot 2016-08-29 at 15 02 17](https://cloud.githubusercontent.com/assets/10940006/18052268/9aba6d7a-6df9-11e6-9355-32a47983b826.png)

4 - Popup is broken until the custom HTML is discarded and the popup reconfigured using the wizard.

# Context

There are other opened issues that may be related: 

- https://github.com/CartoDB/cartodb/issues/9268
- https://github.com/CartoDB/cartodb/issues/8772

cc/ @matallo

**Comment by gfiorav** [comment]
As it is I consider this low-priority. If someone knows better, please say so! Let's leave this for when @matallo comes back!

**Comment by matallo** [comment]
on it, this is happening with fileds with underscore 👀 

/cc @oriolbx

**Comment by matallo** [comment]
it was working locally for me, because I already had this applied https://github.com/CartoDB/cartodb.js/pull/1389

pending review

**Comment by ernesmb** [comment]
Great! we still need to notify the client about the fix, so the sooner we can have this merged the better :) 

Thanks a lot @matallo

**Comment by matallo** [comment]
closed via https://github.com/CartoDB/cartodb/pull/9935

**Comment by ernesmb** [comment]
🚀
