### ISSUE TITLE
2nd (data) layer can't be moved below the 1st (data) layer

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#9598]
**STR:**
- Create a map with 2 or more layers.
- Click on the 2nd data layer (counting from the bottom and not including the basemap) and start dragging it.

**Expected result:**
- You should see a placeholder right above the basemap layer and you should be able to drop the layer there.

**Actual result:**
- Placeholder is not displayed and it's impossible to move the layer to the bottom.
  
![moving](https://cloud.githubusercontent.com/assets/390398/18053656/dabd3e96-6e00-11e6-8e49-6f77ad2b6f11.gif)

cc: @xavijam @CartoDB/frontend

**Comment by xavijam** [comment]
That's happily working right now (tested with 2 layers in production).
