### ISSUE TITLE
Boundary enrichment option available through the UI

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#9604]
# STR

`.carto` file to reproduce the issue: 
[Boundaries (on 2016-08-29 at 14.51.35).carto.zip](https://github.com/CartoDB/cartodb/files/442654/Boundaries.on.2016-08-29.at.14.51.35.carto.zip)

1 - Add a layer
2 - Add an analysis and select `Enrich from Data Observatory`
3 - Analysis parameters allow to select `Boundaries` as the measure, although that feature is still not working from UI
![screen shot 2016-08-29 at 16 52 50](https://cloud.githubusercontent.com/assets/10940006/18055695/27065730-6e09-11e6-82b9-82c188321d26.png)
4 - Analysis fails, as expected. 

# What's expected

Boundary enrichment should not be available through the UI. 

cc/ @saleiva

**Comment by saleiva** [comment]
I believe for this we should implement a new analysis called Get boundaries, or something like that cc/ @talos

**Comment by gfiorav** [comment]
Hey, @javierarce, do you think you could remove those boundaries options from the form for the "Enrich from data observatory" analysis? For me this is low-pri.

Thanks!

**Comment by talos** [comment]
Yep, this is a feature we should support in the Builder -- @saleiva we should talk about this when we talk tomorrow.

What we need to think through is the different entry points to this analysis:

1. Someone wants boundaries for a certain area, sans data. I'm not sure the Analysis API is the right place for those people at all.  We're working on an interface that could handle this with https://github.com/CartoDB/design/issues/104, but it's currently not being surfaced as such.  Perhaps we need to tie it in another place.
2. Someone wants boundaries that encompass their points.  This is a use case that fits OK with our existing API, which supports getting the boundary a point is within.  However, it might have some shortcomings in actual usage (let's say someone wants zip code areas for their points, but doing point-in-poly exclusively would leave gaps.
3. Someone wants boundaries that encompass address or other coded data.

Both (2) and (3) begin to overlap with functions dataservices already handles, so we need to make sure we're leveraging the appropriate resources.

**Comment by javierarce** [comment]
Should I procede and hide the `Boundaries` option from the UI? 

Also: would it make sense to remove it from the `obs_tag` table instead?

**Comment by saleiva** [comment]
This should be fixed at the camshaft or DO level I believe cc/ @javisantana

**Comment by javierarce** [comment]
Bump

**Comment by javisantana** [comment]
Boundaries should be removed from the UI.

We do that with some options that come from DO and UI level
