### ISSUE TITLE
Ambiguous style aggregation

### ISSUE THREAD

**Issue by erodespons** [CartoDB/cartodb#9606]
I have a dataset with different points and each point has different attributes.

I make a subset of the first dataset by using a filter by value analysis.

With the first layer on I see this:

![screenshot 2016-08-29 17 25 03](https://cloud.githubusercontent.com/assets/7283363/18057014/954d626a-6e0e-11e6-8849-7979cbade13f.png)

Right, everything is normal.

I hide the original layer and turn on the one with the analysis. I make a cluster analysis and style by value of the new column that has been created by the second analysis:

![screenshot 2016-08-29 17 25 51](https://cloud.githubusercontent.com/assets/7283363/18057090/dcfe84d6-6e0e-11e6-87b0-12960333b233.png)

Ops, one of the records has disappeared!

I zoom out and...

![screenshot 2016-08-29 17 26 05](https://cloud.githubusercontent.com/assets/7283363/18057114/f3067234-6e0e-11e6-9e44-d96204adef07.png)

Ahá! It's back.

I add an infowindow:

![screenshot 2016-08-29 17 27 05](https://cloud.githubusercontent.com/assets/7283363/18057147/118fcb38-6e0f-11e6-8758-873a65ccafda.png)

I zoom out:

![screenshot 2016-08-29 17 27 29](https://cloud.githubusercontent.com/assets/7283363/18057153/19bdb50e-6e0f-11e6-9fa6-a05e80331546.png)

...Adding labels 😎 

![screenshot 2016-08-29 17 27 29](https://cloud.githubusercontent.com/assets/7283363/18057175/2b231d2a-6e0f-11e6-8215-a6645774cc67.png)

Phantom labels OMG!

I zoom in again, click on the record that disappears when you zoom out and zoom out again:

![screenshot 2016-08-29 17 27 42](https://cloud.githubusercontent.com/assets/7283363/18057230/552a7514-6e0f-11e6-9ece-e30254b63e8c.png)

**Comment by matallo** [comment]
going through the str it's not clear for me which is the issue at hand, please extend the description with expected behaviour and actual behaviour, thanks!

**Comment by xavijam** [comment]
Weird thing, not happened to me for some time. It is likely a problem with tiles cache (already solved some problems we found thanks to @rochoa and @dgaubert), but in any case, weird. Could you share with us your dataset @erodespons?

**Comment by rochoa** [comment]
My bet is on missing CartoCSS property `marker-allow-overlap`, its default value is false, so if the CartoCSS for that layer is not including `marker-allow-overlap: true;` it will drop points based on their collisions.

**Comment by xavijam** [comment]
Yeah, that could be a reason, but I've just checked that category form is adding that property.
Could you still reproduce it @erodespons?

**Comment by erodespons** [comment]
Yup, https://team.carto.com/u/eduardorodes/dataset/transactions_sample_builder_demo

**Comment by erodespons** [comment]
I can't reproduce it any more @xavijam. I've tried and it seems to work as it is expected to work!

Thanks guys.

**Comment by xavijam** [comment]
😱 , let's close it and open again if it is back.
