### ISSUE TITLE
Torn up rainbow in the Brooklyn CARTO Office

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#9608]
Rainbow outline not rendering correctly when you search for "201 Moore St, Brooklyn" in a map.

![image](https://cloud.githubusercontent.com/assets/70603/18078516/404a1b7c-6e8c-11e6-9bb9-54df727b0974.png)

**Comment by iriberri** [comment]
Hey @noguerol, I moved the issue to our basemaps repo :)


https://github.com/CartoDB/CartoDB-basemaps/issues/79
