### ISSUE TITLE
The "Style by this analysis" option in the onboarding should apply a default style

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#9609]
It currently just shows the users the style tab.

**Comment by xavijam** [comment]
The default style is already applied when a new analysis has finished, it is likely I'm missing something, @javierarce could you help me?

**Comment by saleiva** [comment]
but it should apply a custom style for that particular analysis. Clearly not for the next sprint but we should tackle this soon cc/ @makella

**Comment by xavijam** [comment]
Ahhhh, the custom style for each analysis, got it!

**Comment by makella** [comment]
YES! I have this going working through each one.
