### ISSUE TITLE
Problems with timeout when dealing with big datasets

### ISSUE THREAD

**Issue by Kartones** [CartoDB/cartodb#961]
I've been experimenting some problems with a CSV dataset containing ~ 8 million points. The CSV file weights 800MB. The problems are:

- I couldn't import the file using cdb_import.sh. The job id return by the script was always empty, and the process never ended
- I could import the file using GUI (drag&drop), but I got an error from the web interface, even when the file was correctly imported (at least I can see it in the editor and work with it)
- I couldn't perform single operations over the table using editor, like changing a column type (from integer to boolean). The operation never ends.
- Some SQL queries raised from the editor thrown an error, complaining about SQL syntax. The real error was a timeout (directly checked with psql console, from the vm).

**Comment by xavijam** [comment]
Are those problems still appearing?

**Comment by Kartones** [comment]
Also for @CartoDB/data-services-admin-team to handle I guess

**Comment by rafatower** [comment]
Kind of duplicated.
https://github.com/CartoDB/cartodb/issues/1683
https://github.com/CartoDB/cartodb/issues/5009
