### ISSUE TITLE
Z (and M) coordinates are lost from imported objects

### ISSUE THREAD

**Issue by jaakla** [CartoDB/cartodb#9613]
@jaakla commented on [Fri Aug 26 2016](https://github.com/CartoDB/mobile-sdk/issues/28)

Sample data: http://www-static.bouldercolorado.gov/docs/opendata/OSMPTrails.zip . The trails have 3D lines for coordinates, and you can see them with ogrinfo:

```
INFO: Open of `/Users/jaak/Downloads/OSMPTrails/OSMPTrails.shp'
      using driver `ESRI Shapefile' successful.

Layer name: OSMPTrails
Geometry: 3D Line String
Feature Count: 296
...
```

But after I imported this to CARTO then the_geom has only XY coordinates. The importer should preserve Z and M dimensions, even if this is not really used for rendering. Other API-s (e.g. SQL API for mobile, vector tiles) could then use it for special rendering.

**Comment by javisantana** [comment]
the importer is designed to do that so I guess is a documentation problem cc @rafatower

**Comment by rafatower** [comment]
yes, that behavior is done on purpose and is probably not properly documented.
