### ISSUE TITLE
Connect with Dropbox, Buttons bad aligment in data list

### ISSUE THREAD

**Issue by carlostallon** [CartoDB/cartodb#9620]
OS X El Capitan 10.11.6
Chrome 51

![image](https://cloud.githubusercontent.com/assets/1712650/18134434/ad18d230-6f9e-11e6-9979-e02c43f87ee3.png)

**Comment by piensaenpixel** [comment]
puf i cant reproduce it :(

**Comment by xavijam** [comment]
Where tallon, dashboard? builder? editor?

**Comment by xavijam** [comment]
I've just checked those 3 environments and I can't reproduce it, closing mate 💋 .

**Comment by carlostallon** [comment]
In the builder and it's still happening

![image](https://cloud.githubusercontent.com/assets/1712650/18275898/3808f4b6-7449-11e6-986f-45f908a18399.png)
