### ISSUE TITLE
feature request: export data from specific analysis node

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartodb#9621]
Right now, exporting data from a layer only lets you export the result of the last analysis node. Sometimes you want to extract from a different node in the chain and don't want to pull out that node into a separate layer as the workaround for exporting it.

<img width="326" alt="screen shot 2016-08-31 at 11 41 25" src="https://cloud.githubusercontent.com/assets/1041056/18135608/6cbb5308-6f70-11e6-8400-e03fa20926f3.png">

**Comment by andrewbt** [comment]
relatedly, exporting data should respect the current widget filter states and only export the data that has been filtered in

**Comment by noguerol** [comment]
cc @CartoDB/design
