### ISSUE TITLE
[BUG] exporting images of maps with mapbox basemaps are incorrect

### ISSUE THREAD

**Issue by ryanyun** [CartoDB/cartodb#9625]
When exporting a map that uses a default basemap (here/stamen/CARTO), the image seems fine:

![untitled_map_1_by_ryanyun_08_31_2016_12_39_20](https://cloud.githubusercontent.com/assets/11324678/18137790/df260382-6f77-11e6-933b-abbc5670d793.png)

However, when exporting a map that utilizes a custom basemap that was created in Mapbox Studio, the generated image is incorrect. Here are some examples:

![untitled_map_1_by_ryanyun_08_31_2016_12_41_41](https://cloud.githubusercontent.com/assets/11324678/18137864/345ca05e-6f78-11e6-8742-4b15e92a8f32.png)

![untitled_map_1_by_ryanyun_08_31_2016_12_43_04](https://cloud.githubusercontent.com/assets/11324678/18137907/65bb8df4-6f78-11e6-9155-244021b2aae4.png)

Some additional notes:
- I am importing the custom basemaps from Mapbox Studio using an XYZ URL with a token
- This issue can also be seen from the thumbnail images generated when sharing the map
- The interactive map itself is perfectly fine, the issue is only in exporting the image:

![screen shot 2016-08-31 at 12 44 28 pm](https://cloud.githubusercontent.com/assets/11324678/18137965/a48f065a-6f78-11e6-8157-314c2c8d1891.png)

**Comment by michellechandra** [comment]
This issue is a duplicate of an issue reported in a private CARTO repo. 

The workaround to this issue at this time is to use the older Mapbox Studio Classic basemap styles created using Mapbox Studio Classic desktop software if you need to export an image of your CARTO map with the basemap.

https://github.com/CartoDB/cartodb-management/issues/4501

**Comment by ryanyun** [comment]
Ah, that did the trick! Thanks @michellechandra :smile:

**Comment by nictait** [comment]
Is there another solution without using Mapbox Studio Classic - we have a number of custom Mapbox Studio styles which we use in CARTO maps ?

**Comment by michellechandra** [comment]
@nictait - unfortunately, at this time, the workaround is to use Mapbox Studio Classic basemaps. Apologies for the inconvenience.

**Comment by nictait** [comment]
@michellechandra thanks for the update
