### ISSUE TITLE
Renaming a dataset doesnt get propagated to maps using it

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#9633]
so all maps get broken.

To reproduce,
- Create a map using a dataset,
- go to the dataset view and rename it
- Go back to the map.

#SMOKE_DT32

**Comment by gfiorav** [comment]
Oh, smokes.

On it.

**Comment by ramiroaznar** [comment]
Reopening this issue. #SMOKE_DT32

After renaming a dataset, I go to a map that contains that dataset and this is the error I am getting:

![renamedataset](https://cloud.githubusercontent.com/assets/5215798/19651517/7ac1016a-9a0d-11e6-89b1-574c1a339ca8.png)

In addition, clicking to "Fix them" does not redirect to any kind of resource or documentation.

**Comment by gfiorav** [comment]
After checking, it seems the issue is having the dataset and map opened in different windows, updating one without refreshing the other.

We'd like to support simultaneous working but we're not that cool yet!! Thanks for reporting.

**Comment by javisantana** [comment]
so @ramiroaznar should we set that test as OK?
