### ISSUE TITLE
"There's a problem with your connection"

### ISSUE THREAD

**Issue by strk** [CartoDB/cartodb#9636]
I get a "There's a problem with your connection" error message while editing this map:
https://strk.carto.com/viz/031cbca8-7055-11e6-94c1-0e3ebc282e83/map

But I clearly have no connection problems as I can file this ticket.

Firebug has an hint about it, being a response from a POST
to https://strk.carto.com/api/v1/map:

```
{"errors":["column f.cartodb_id does not exist"],"errors_with_context":[{"type":"unknown","message":"column
 f.cartodb_id does not exist","name":"error","length":89,"severity":"ERROR","code":"P0001","file":"pl_exec
.c","line":"3216","routine":"exec_stmt_raise"}]}
```

**Comment by strk** [comment]
NOTE: when I failed to provide a "the_geom_webmercator" field, the UI nicely told me about it being a requirement, I suggest the same is done for "cartodb_id"...

**Comment by saleiva** [comment]
Hi @strk, closing this as we are focusing on the Builder UI. Did you tried it?
