### ISSUE TITLE
Implement Dot Density Analysis

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#9641]
Design in https://github.com/CartoDB/design/issues/115

**Comment by saleiva** [comment]
This is very useful when calculating dummy datasets for usecases. @javisantana @rochoa could we try to prioritize this?

**Comment by javisantana** [comment]
what are the usecases that this "analysis" covers?

**Comment by saleiva** [comment]
creating dummy data based on population - or any other column- distribution as an internal tool is the first one as commented above.

**Comment by saleiva** [comment]
Dont be troll

**Comment by javisantana** [comment]
Ok, let's discuss this one a little bit. As I understand the analysis creates a random set of points within a polygon based on column, some questions:

- how do we avoid going too far with the number of points (the UI sets 1 points per XX of that attribute)

- If we don't have a mínimum amount of points the sampling is not useful and results *totally* misleading, so how do we avoid that? 

- I think the sampling function has some issues:
   - the sampling being done by the function is linear but it should not be (we are using non projected geometry) 
   - not sure if that works with polygons with holes check `select st_makeline(st_linemerge('MULTILINESTRING((0 0, 1 1), (2 2, 3 3))'));`

- does not make more sense to have this analysis when we have more than one column? with one single column a choropleth should be more effective.

**Comment by stuartlynn** [comment]
_how do we avoid going too far with the number of points (the UI sets 1 points per XX of that attribute)_

I think that we can do this in one of two ways.  In camshaft we can do a quick summation over the geometries and counts to check to see if its under a given threshold. Or we can do it on a per geometry basis. No geometry can have more than x number of points.

 _if we don't have a mínimum amount of points the sampling is not useful and results totally misleading, so how do we avoid that?_

I think we take care of that in the messaging around the method. Many of the analysis we are producing will need some awareness by the user to use them correctly (Moran I for example) so I think we  make it as clear as possible that this method is primarily for visualization and works best when there is a large number of points form different categories. 

Though with dasymetric dot density I think there is a good case for using this as real analysis to resample on different overlapping geometries but thats a separate thread.

_the sampling being done by the function is linear but it should not be (we are using non projected geometry as we use 4326)_

Yeah we should fix this. For small geometries like we have been using up to now this hasn't been too much of an issue but it should be easy enough to fix.

_not sure if that works with polygons with holes check select st_makeline(st_linemerge('MULTILINESTRING((0 0, 1 1), (2 2, 3 3))')); fails_

That makes sense, this version was an attempt by me to make this faster than the original version which just generates a random point on the polygons bounding box and then rejects it if its out with the original polygon and accepts it if not. Happy to go back to that way of doing things and apply a few other optimizations to it that Paul Ramsey suggested.

**Comment by javisantana** [comment]
let's tackle those issues right now (specially the holes thing) because that's going to hit very soon

**Comment by stuartlynn** [comment]
Will take a look first thing tomorrow morning, should be a quick fix.
