### ISSUE TITLE
Enrich by Data Observatory should be smart about how it enriches

### ISSUE THREAD

**Issue by stuartlynn** [CartoDB/cartodb#9642]
Currently if you try to Enrich by Data Observatory using a large polygon, like a county, the DO will try to sum together all the values from the block groups within that polygon which is slow. 

We should be smarter about how we do that. One way would be to find the boundary level which has the smallest number of boundaries that fit within the target polygon and use that to do the aggregation. That would mean that we don't get as accurate results from the edge contributions (as we are using area weighted binning for the fractional areas) so perhaps a hybrid  approach is needed where take most of the value from the largest intact polygon then use smaller areas to calculate the parts that overlap.

@talos Lets talk about this when you get back! 

cc @saleiva

**Comment by javisantana** [comment]
should it be at DO level? 

From my point of view a quick bbox comparison is enough, if the area of the polygon trying to augment is X times the avg of the level we are going to use it should use a level with less granularity.

my 2 cents

**Comment by stuartlynn** [comment]
Yeah that would work and I think we should implement that, my only concern is that some of the larger geometries vary in size quite a bit. Might want to use the median instead of the average. 

It might also be worth doing some research here and testing a few different approaches to see how inaccurate they are. We can calculate the interpolated population using a few of the DO geometry levels and compare how the result changes, that should give us an idea of how to do this optimally. I know that John has been playing with using rasters to quickly estimate the best geometry to use at a given zoom level. I think we can adapt that for this  as well.

**Comment by talos** [comment]
Yep, I see rasters as the way forward on this.  Let's talk about it in person tomorrow.

**Comment by saleiva** [comment]
any other info on this?

**Comment by talos** [comment]
Yes!  I made some great progress last week:

https://github.com/CartoDB/bigmetadata/blob/master/tasks/util.py#L233

This means we now have raster summaries for all our Observatory geometries.  These raster summaries can very quickly (~1 sec for the whole world, about a twentieth of a second for a country-sized portion) tell us for any shape approximating to 50sq km rectangles:

1. Approximately how many of each boundary type are within it
2. On average how big each boundary type within it is, and thus extrapolate how many there would be if that shape was entirely filled with them
3. Approximately what percentage of that shape is filled with each sort of boundary

Respectively on bands 1, 2 and 3 of the raster.  The 50 sq km grid is a bit loose, but I think good enough as it still provides enough information to make sub-50 sq km decisions.

What remains is to write Observatory functions that actually use this data.  The plan for the first iteration is to be transparent with them, in other words to replace the existing use-the-smallest functionality with a use-the-most-appropriate functionality.  This will involve writing a ranking function of some kind, which will also need to be exposed for the next-gen Observatory interface, which will have a slider built off of it.

The first iteration Observatory function is scheduled on this sprint, so should be completed by Thursday after next -- and hopefully sooner.

**Comment by talos** [comment]
We for some time have been generating raster summaries of all geometries, and using them to select the best boundary when the user does not choose one.
