### ISSUE TITLE
Having problems with sharing maps the first time you publish them

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#9643]
Lately we are having problems when sharing maps. After publishing them for the first time (if you change the privacy before) It gives an instantiation error on the public view. You have to move the map on the builder, click on update and then it works.

**Comment by gfiorav** [comment]
We don't support certain privacy changes for Mapcaps. 

So if you have a private map, mapcap it, and then change the privacy to public it won't work until you update the mapcap. 

This is in the future to come (not trivial) but not road mapped. 

I think it's important, maybe we should rethink the milestone?

**Comment by saleiva** [comment]
wait, but this fails even when you dont have any mapcap.

adding @javisantana so he is aware, just in case we need to reprioritize

**Comment by gfiorav** [comment]
Ok, @saleiva I misunderstood then.

Can you STR it out? I feel I'm missing something.

**Comment by saleiva** [comment]
- Create a map which is private.
- Click on publish
- Change map privacy
- Get the link and open in incognito (it fails)
- Move the map slightly
- Click on update
- Open the prev public link (it works)

**Comment by gfiorav** [comment]
> Click on publish

This creates a mapcap 

I think it's the problem I was talking about, map caps vs privacy when tokens are involved (mostly orgs)
