### ISSUE TITLE
Problem load job and data to cartodb

### ISSUE THREAD

**Issue by hhryw** [CartoDB/cartodb#9650]
Hi, Ive installed carto on my local server, it works correctly but i cant load any data or job. 

If I load a job, the error is: 
Ouch! Error connecting 
Unable to load data (2001)
 

and the terminal show:
`NOTICE:  identifier "resque-1.25.2: Processing imports since 1472816077 [Resque::ImporterJobs]" will be truncated to "resque-1.25.2: Processing imports since 1472816077 [Resque::Imp"
NOTICE:  identifier "resque-1.25.2: Processing imports since 1472816077 [Resque::ImporterJobs]" will be truncated to "resque-1.25.2: Processing imports since 1472816077 [Resque::Imp"
NOTICE:  identifier "resque-1.25.2: Processing imports since 1472816077 [Resque::ImporterJobs]" will be truncated to "resque-1.25.2: Processing imports since 1472816077 [Resque::Imp"
NOTICE:  identifier "resque-1.25.2: Processing imports since 1472816077 [Resque::ImporterJobs]" will be truncated to "resque-1.25.2: Processing imports since 1472816077 [Resque::Imp"
NOTICE:  identifier "resque-1.25.2: Processing imports since 1472816077 [Resque::ImporterJobs]" will be truncated to "resque-1.25.2: Processing imports since 1472816077 [Resque::Imp"`

The log of request:
`** [13:27:22 2016-09-02] 1594: Starting worker IDI:1594:imports,exports,users,user_dbs,geocodings,synchronizations,tracker,user_migrations
** [13:27:22 2016-09-02] 1594: Registered signals
** [13:27:22 2016-09-02] 1594: Pruning dead worker: IDI:1549:imports,exports,users,user_dbs,geocodings,synchronizations,tracker,user_migrations
** [13:27:22 2016-09-02] 1594: Running before_first_fork hooks
** [13:27:22 2016-09-02] 1594: Checking imports
** [13:27:22 2016-09-02] 1594: Checking exports
** [13:27:22 2016-09-02] 1594: Checking users
** [13:27:22 2016-09-02] 1594: Checking user_dbs
** [13:27:22 2016-09-02] 1594: Checking geocodings
** [13:27:22 2016-09-02] 1594: Checking synchronizations
** [13:27:22 2016-09-02] 1594: Checking tracker
** [13:27:22 2016-09-02] 1594: Checking user_migrations
** [13:27:22 2016-09-02] 1594: Sleeping for 5.0 seconds
** [13:27:22 2016-09-02] 1594: resque-1.25.2: Waiting for imports,exports,users,user_dbs,geocodings,synchronizations,tracker,user_migrations`

PS: The job loaded correctly to official cartodb. I tried .kml .csv and .zip with SHP,SHX,prj, DBF.

On the other hand, if i try load a logo for my profile information, the error is "There was an error uploading your avatar. Check the height and size (max 1MB) of the image", but the logo has a size of 100KB.

The terminal show: 

`Digest::Digest is deprecated; use Digest`

Any ideas? Thanks!!

**Comment by icetorm** [comment]
I got the same issue, i achieve in the past to install cartodb , but now if i try to install CARTO from the begining i can't load any dataset.

**Comment by iriberri** [comment]
Hey there @icetorm and @hhryw!

When you get these import errors, you get also an ID for the import itself. Save one of these ID and, do as follow:


1. Go into the Rails console: `bundle exec rails c development`
2. Look for the import log:

  ````
   di = DataImport['your_id_here']
   di.log
  ````
3. If you share the log here, we will be able to check what's happening. You should be able to find a more explanative error in there.

At first sight, error 2001 means that it comes from Ogr2ogr. My guess is that the ogr2ogr version could be the problem here, so another question for you is, in your `app_config.yml` file, what do your file say at [this line](https://github.com/CartoDB/cartodb/blob/0eca30125c465d118dd9167d32b7e55589ddc721/config/app_config.yml.sample#L8) (ogr2ogr binary name). Make sure you have ogr2ogr2.1 installed by running:

````
sudo apt-get update
sudo apt-get install gdal2.1-static-bin
````

as explained in the NEWS.md file: https://github.com/CartoDB/cartodb/blob/master/NEWS.md#3140-2016-xx-xx

**Comment by hhryw** [comment]
Firsly, thanks for your answer. 

I've checked my `app_config.yml` and it was correct. 

`ogr2ogr:
    binary:           'which ogr2ogr2.1'
    csv_guessing:     true`

ogr2ogr2.1 was correct too:

`sudo apt-get install gdal2.1-static-bin
Reading package lists... Done
Building dependency tree
Reading state information... Done
gdal2.1-static-bin is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.`

Then, I've made the log of the error import and I've get:

 `irb(main):001:0> di = DataImport['ef9b3232-93b7-4074-a349-5730b209a557']
(0.000749s) SELECT * FROM "data_imports" WHERE "id" = 'ef9b3232-93b7-4074-a349-5730b209a557'
(0.000382s) SELECT * FROM "logs" WHERE ("id" = '972cb577-ec6e-4eb2-806c-ed73257cf1b6') LIMIT 1
=> #<DataImport @values={:data_source=>"/home/afronta/cartodb/public/uploads/d3a80ce74f9bbbd3dc7a/CAPA_ZONA.kml", :data_type
success=>false, :logger=>"972cb577-ec6e-4eb2-806c-ed73257cf1b6", :updated_at=>2016-09-01 12:33:58 +0200, :created_at=>2016-0
d=>nil, :tables_created_count=>nil, :table_names=>nil, :append=>false, :migrate_table=>nil, :table_copy=>nil, :from_query=>n
7-4074-a349-5730b209a557", :user_id=>"465be2ad-34b9-48b9-8bd0-3454b7d0d7f6", :table_id=>nil, :service_name=>"public_url", :s
loads/d3a80ce74f9bbbd3dc7a/CAPA_ZONA.kml", :stats=>"[{\"filename\":\"capa_zona.kml\",\"type\":\".kml\",\"size\":2652,\"file_
nt\":null,\"fallback_executed\":null}]", :type_guessing=>true, :quoted_fields_guessing=>true, :content_guessing=>true, :serv
I", :resque_ppid=>4044, :create_visualization=>true, :visualization_id=>nil, :user_defined_limits=>"{\"twitter_credits_limit
l=>"/home/afronta/cartodb/public/uploads/d3a80ce74f9bbbd3dc7a/CAPA_ZONA.kml", :privacy=>0, :cartodbfy_time=>0.0, :http_respo
rnings=>nil}>

irb(main):002:0> di.log
=> #<CartoDB::Log @values={:id=>"972cb577-ec6e-4eb2-806c-ed73257cf1b6", :type=>"import", :user_id=>"465be2ad-34b9-48b9-8bd0-
+0200, :updated_at=>2016-09-01 12:33:58 +0200, :entries=>"2016-09-01 10:33:58 UTC: Running on server IDI with PID: 9986\n201
 10:33:58 UTC: Fetching datasource public_url metadata for item id /home/afronta/cartodb/public/uploads/d3a80ce74f9bbbd3dc7a
ll be downloaded from /home/afronta/cartodb/public/uploads/d3a80ce74f9bbbd3dc7a/CAPA_ZONA.kml\n2016-09-01 10:33:58 UTC: Befo
ng import for /home/afronta/cartodb/public/uploads/d3a80ce74f9bbbd3dc7a/CAPA_ZONA.kml\n2016-09-01 10:33:58 UTC: Unpacking /h
bd3dc7a/CAPA_ZONA.kml\n2016-09-01 10:33:58 UTC: Filename: /tmp/imports/20160901-9986-mvb6o4/capa_zona.kml Size (bytes): 2652
1-9986-mvb6o4/capa_zona.kml\ntrue: File-based import load\ntrue: Detected encoding UTF-8\ntrue: Using database connection wi
\", :host=>\"localhost\", :port=>5432, :direct_port=>5432, :database=>\"cartodb_dev_user_465be2ad-34b9-48b9-8bd0-3454b7d0d7f
5be2ad-34b9-48b9-8bd0-3454b7d0d7f6\", :conn_validator_timeout=>900, :pool=>50}\nfalse: ogr2ogr call:            OSM_USE_CUST
UTF-8  /usr/bin/ogr2ogr2.1 -f PostgreSQL  PG:\"host=localhost port=5432 user=development_cartodb_user_465be2ad-34b9-48b9-8bd
34b9-48b9-8bd0-3454b7d0d7f6_db password=8b33b285c0505665d3c1f5e6c5ecde005c75cb8fdevelopment_cartodb_user_465be2ad-34b9-48b9-
 -lco PRECISION=NO /tmp/imports/20160901-9986-mvb6o4/capa_zona.kml  -nln cdb_importer.importer_974d5ac0702f11e68139000c295d0
TS=\"SET statement_timeout TO '1h'\" -doo CLOSING_STATEMENTS='SET statement_timeout TO DEFAULT' -update \ntrue: ogr2ogr outp
t file gcs.csv.\nTry setting the GDAL_DATA environment variable to point to the\ndirectory containing EPSG csv files.\nERROR
n\ntrue: ogr2ogr exit code:       256\n2016-09-01 10:33:58 UTC: Ogr2ogr FAILED!\n2016-09-01 10:33:58 UTC: ogr2ogr.exit_code
= OSM_USE_CUSTOM_INDEXING=NO PG_USE_COPY=YES PGCLIENTENCODING=UTF-8  /usr/bin/ogr2ogr2.1 -f PostgreSQL  PG:\"host=localhost
-34b9-48b9-8bd0-3454b7d0d7f6 dbname=cartodb_dev_user_465be2ad-34b9-48b9-8bd0-3454b7d0d7f6_db password=8b33b285c0505665d3c1f5
2ad-34b9-48b9-8bd0-3454b7d0d7f6\" -t_srs EPSG:4326  -lco DIM=2 -lco PRECISION=NO /tmp/imports/20160901-9986-mvb6o4/capa_zona
68139000c295d0d4c -nlt PROMOTE_TO_MULTI  -doo PRELUDE_STATEMENTS=\"SET statement_timeout TO '1h'\" -doo CLOSING_STATEMENTS='
-09-01 10:33:58 UTC: ogr2ogr.command_output = ERROR 4: Unable to open EPSG support file gcs.csv.\nTry setting the GDAL_DATA
containing EPSG csv files.\nERROR 1: Failed to process SRS definition: EPSG:4326\n\ntrue: Errored importing data from /tmp/i
e: CartoDB::Importer2::LoadError: 2016-09-01 10:33:58 UTC: Running on server IDI with PID: 9986\n2016-09-01 10:33:58 UTC: ne
datasource public_url metadata for item id /home/afronta/cartodb/public/uploads/d3a80ce74f9bbbd3dc7a/CAPA_ZONA.kml\n2016-09-
ome/afronta/cartodb/public/uploads/d3a80ce74f9bbbd3dc7a/CAPA_ZONA.kml\n2016-09-01 10:33:58 UTC: Before importer run\n2016-09
nta/cartodb/public/uploads/d3a80ce74f9bbbd3dc7a/CAPA_ZONA.kml\n2016-09-01 10:33:58 UTC: Unpacking /home/afronta/cartodb/publ
016-09-01 10:33:58 UTC: Filename: /tmp/imports/20160901-9986-mvb6o4/capa_zona.kml Size (bytes): 2652\ntrue: Importing data f
kml\ntrue: File-based import load\ntrue: Detected encoding UTF-8\ntrue: Using database connection with {:adapter=>\"postgres
, :port=>5432, :direct_port=>5432, :database=>\"cartodb_dev_user_465be2ad-34b9-48b9-8bd0-3454b7d0d7f6_db\", :username=>\"dev
54b7d0d7f6\", :conn_validator_timeout=>900, :pool=>50}\nfalse: ogr2ogr call:            OSM_USE_CUSTOM_INDEXING=NO PG_USE_CO
.1 -f PostgreSQL  PG:\"host=localhost port=5432 user=development_cartodb_user_465be2ad-34b9-48b9-8bd0-3454b7d0d7f6 dbname=ca
7f6_db password=8b33b285c0505665d3c1f5e6c5ecde005c75cb8fdevelopment_cartodb_user_465be2ad-34b9-48b9-8bd0-3454b7d0d7f6\" -t_s
imports/20160901-9986-mvb6o4/capa_zona.kml  -nln cdb_importer.importer_974d5ac0702f11e68139000c295d0d4c -nlt PROMOTE_TO_MULT
ut TO '1h'\" -doo CLOSING_STATEMENTS='SET statement_timeout TO DEFAULT' -update \ntrue: ogr2ogr output:          ERROR 4: Un
ting the GDAL_DATA environment variable to point to the\ndirectory containing EPSG csv files.\nERROR 1: Failed to process SR
de:       256\n2016-09-01 10:33:58 UTC: Ogr2ogr FAILED!\n2016-09-01 10:33:58 UTC: ogr2ogr.exit_code = 256\n2016-09-01 10:33:
G=NO PG_USE_COPY=YES PGCLIENTENCODING=UTF-8  /usr/bin/ogr2ogr2.1 -f PostgreSQL  PG:\"host=localhost port=5432 user=developme
d7f6 dbname=cartodb_dev_user_465be2ad-34b9-48b9-8bd0-3454b7d0d7f6_db password=8b33b285c0505665d3c1f5e6c5ecde005c75cb8fdevelo
7d0d7f6\" -t_srs EPSG:4326  -lco DIM=2 -lco PRECISION=NO /tmp/imports/20160901-9986-mvb6o4/capa_zona.kml  -nln cdb_importer.
ROMOTE_TO_MULTI  -doo PRELUDE_STATEMENTS=\"SET statement_timeout TO '1h'\" -doo CLOSING_STATEMENTS='SET statement_timeout TO
2ogr.command_output = ERROR 4: Unable to open EPSG support file gcs.csv.\nTry setting the GDAL_DATA environment variable to
s.\nERROR 1: Failed to process SRS definition: EPSG:4326\n\ntrue: Errored importing data from /tmp/imports/20160901-9986-mvb
---------------------------------------------\nfalse: [\"/home/afronta/cartodb/services/importer/lib/importer/loader.rb:335:
cartodb/services/importer/lib/importer/loader.rb:268:in `run_ogr2ogr'\", \"/home/afronta/cartodb/services/importer/lib/impor
 \"/home/afronta/cartodb/lib/cartodb/stats/aggregator.rb:97:in `method_missing'\", \"/home/afronta/cartodb/services/importer
\"/home/afronta/cartodb/lib/cartodb/stats/aggregator.rb:97:in `method_missing'\", \"/home/afronta/cartodb/services/importer/
ronta/cartodb/services/importer/lib/importer/runner.rb:243:in `file_based_loader_run'\", \"/home/afronta/cartodb/services/im
 \"/home/afronta/cartodb/services/importer/lib/importer/runner.rb:384:in `execute_import'\", \"/home/afronta/cartodb/service
(3 levels) in single_resource_import'\", \"/home/afronta/cartodb/services/importer/lib/importer/runner.rb:277:in `each'\", \
orter/runner.rb:277:in `each_with_index'\", \"/home/afronta/cartodb/services/importer/lib/importer/runner.rb:277:in `block (
afronta/cartodb/lib/cartodb/stats/aggregator.rb:97:in `method_missing'\", \"/home/afronta/cartodb/services/importer/lib/impo
import'\", \"/home/afronta/cartodb/lib/cartodb/stats/aggregator.rb:97:in `method_missing'\", \"/home/afronta/cartodb/service
_resource_import'\", \"/home/afronta/cartodb/services/importer/lib/importer/runner.rb:101:in `run_import'\", \"/home/afronta
b:94:in `block in run'\", \"/home/afronta/cartodb/lib/cartodb/stats/aggregator.rb:97:in `method_missing'\", \"/home/afronta/
:93:in `run'\", \"/home/afronta/cartodb/app/connectors/importer.rb:43:in `run'\", \"/home/afronta/cartodb/app/models/data_im
onta/cartodb/app/models/data_import.rb:407:in `dispatch'\", \"/home/afronta/cartodb/app/models/data_import.rb:180:in `run_im
orter_jobs.rb:9:in `block in perform'\", \"/home/afronta/cartodb/lib/resque/base_job.rb:21:in `call'\", \"/home/afronta/cart
 \"/home/afronta/cartodb/lib/resque/importer_jobs.rb:9:in `perform'\", \"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/res
vels) in perform'\", \"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/resque-metrics-0.1.1/lib/resque/metrics.rb:353:in `ar
3/lib/ruby/gems/2.2.0/gems/resque-1.25.2/lib/resque/job.rb:239:in `block (2 levels) in perform'\", \"/opt/rubies/ruby-2.2.3/
e/job.rb:247:in `call'\", \"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/resque-1.25.2/lib/resque/job.rb:247:in `perform'
/gems/resque-1.25.2/lib/resque/worker.rb:250:in `perform'\", \"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/resque-1.25.2
\"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `loop'\", \"/opt/rubies/ruby-2.2
sque/worker.rb:166:in `work'\", \"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/resque-1.25.2/lib/resque/tasks.rb:41:in `b
ubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'\", \"/opt/rubies/ruby-2.2.3/lib/ruby/g
:in `block in execute'\", \"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'\", \
/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'\", \"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/t
", \"/opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'\", \"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2
voke_with_call_chain'\", \"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'\",
s/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'\", \"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.9.2.
) in top_level'\", \"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'\", \"
rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'\", \"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.
xception_handling'\", \"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_leve
.0/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'\", \"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-
_exception_handling'\", \"/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'\"
ems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'\", \"/opt/rubies/ruby-2.2.3/bin/rake:23:in `load'\", \"/opt/rubies/ruby-2
-------------------------------------------\n2016-09-01 10:33:58 UTC: Proceeding to register\n2016-09-01 10:33:58 UTC: After
spatch\n2016-09-01 10:33:58 UTC: ERROR!\n\n"}>`

**Comment by iriberri** [comment]
@hhryw:

````
ogr2ogr.command_output = ERROR 4: Unable to open EPSG support file gcs.csv.
Try setting the GDAL_DATA containing EPSG csv files.
ERROR 1: Failed to process SRS definition: EPSG:4326: Errored importing data from /tmp/i..
```

It looks like you need to set `GDAL_DATA`. Try with `export GDAL_DATA=/usr/share/gdal/2.1`.

**Comment by hhryw** [comment]
@iriberri 
Thank you very much!! It works!!!! Fantastic!!! :)

**Comment by hhryw** [comment]
One thing more....

And the logo problem? Any idea?

**Comment by iriberri** [comment]
Oh sorry, I didn't see that question. Could you please open a new issue for that one? This way this issue remains just an import problem and perhaps someone else can help, because I'm not that familiar with how we manage the assets.

**Comment by iriberri** [comment]
By the way, glad it worked! :) You're welcome!

**Comment by hhryw** [comment]
Ok thanks you again!!! I will open a new issue.
