### ISSUE TITLE
Wrong "lacks of geometry data" message at widgets pane

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#9653]
STR

1. Create a map with a points dataset.
2. Add a count formula widget.
3. Open the map again (clicking at the browser bar is enough).
4. Go to widgets pane. You're wrongly prompt with "Your dataset lacks of geometry data and it's not possible to add a widget." message:

![screen shot 2016-09-02 at 16 42 39](https://cloud.githubusercontent.com/assets/932968/18207663/59aadc76-712c-11e6-94f5-26fb56ccbc1d.png)

There's a workaround. After step 4...

5. Go to layers pane.
6. Open the layer.
7. Close the layer and go to widgets pane again. Now it's right:

![screen shot 2016-09-02 at 16 44 44](https://cloud.githubusercontent.com/assets/932968/18207716/9547f318-712c-11e6-8f08-8f968a86b716.png)

cc @xavijam @nobuti

**Comment by juanignaciosl** [comment]
cc @jsanz

**Comment by jsanz** [comment]
cc. @CartoDB/support for awareness

**Comment by nobuti** [comment]
Mine, already fixed in topic branch.

**Comment by saleiva** [comment]
so is it close?

**Comment by nobuti** [comment]
Nope, I'll close it when I merge that branch. I'll do asap.
