### ISSUE TITLE
Analyses explanation overlay appears over SQL pane in the data section of a layer

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#9655]
The explanations that appear after an analysis, if not closed, continue in the right part of the builder. This is nice because most of the time the screen is split with the same dimensions and it fits. But:

**STR**:

* Perform an analysis (subsample, for example)
* After the overlay appears, go to your layer and click on Data
* Click on the SQL button (in the values/sql switch). The SQL pane is bigger than the rest of panes in the app.

**Result**: The explanation overlay appears on top of the SQL pane, partially:

![image](https://cloud.githubusercontent.com/assets/1730320/18208927/d10c128a-7131-11e6-8929-2464ec2eeba4.png)

**Comment by piensaenpixel** [comment]
fixed
