### ISSUE TITLE
I can't load a logo profile.

### ISSUE THREAD

**Issue by hhryw** [CartoDB/cartodb#9657]
Hi all, 

I am trying to load a logo for my profile , the error is "There was an error uploading your avatar. Check the height and size (max 1MB) of the image", but the logo has a size of 100KB.

The terminal show:

Digest::Digest is deprecated; use Digest

Any ideas? Thanks!!

**Comment by iriberri** [comment]
Hi again @hhryw! As I told you I'm not very familiar with this part of the platform, but what is the height of the image? Wondering if any limit besides the size itself could be affecting you.

**Comment by MariaCheca** [comment]
Hi @hhryw! It seems that you're trying to upload a picture with more than 1024x1024 pixels. Try to upload another one with less dimension and a maximum size of 1MB and that should be enough to upload it :)

**Comment by hhryw** [comment]
Hi @MariaCheca , 

no no, that is the problem, the image is a .png with 200x200 pixels and 100KB.

**Comment by MariaCheca** [comment]
Hello again @hhryw!

If you're running CARTO in your local environment, maybe you're using our sample configuration, which has [sample credentials to access AWS](https://github.com/CartoDB/cartodb/blob/master/config/app_config.yml.sample#L262), where we keep the avatar files in our production environment. You can both use your own AWS credentials or leave those fields empty to let the application save the file in your own environment.

Also there's [this topic](https://groups.google.com/d/topic/cartodb/EPmPEBduNO0/discussion) in our Google Forums where another user asked about the same issue, maybe it can help you :)

**Comment by hhryw** [comment]
Thanks you!!! @MariaCheca The problem was the sample credential to access AWS. I put:

 ` aws:
    s3:
      access_key_id: 
      secret_access_key: 
  assets:
    s3_bucket_name: 
    max_file_size: 5242880 # 5.megabytes`

and Its work!!!!!!

Thank you again!!! :)

**Comment by MariaCheca** [comment]
Nice @hhryw! Happy to help :)
