### ISSUE TITLE
Color choice in editor window makes below-scroll fields hard to see

### ISSUE THREAD

**Issue by cshirky** [CartoDB/cartodb#9660]
Problem: The gray-on-gray color scheme of the data editor window makes it hard for users to understand that fields are hidden below scroll.

Proposed solution: Make fixed part of editing window a different color than the scrolling part; Give scrolling background a color treatment or background that makes users think the page continues.

STR: 
1. Create a point with more than 4 editable columns.
2. Go to map view and click on that point.
3. In the Infowindow, click Edit.

You will see the first 4 fields listed, followed by enough gray space below to make users think these are the only fields listed.

<img width="645" alt="screen shot 2016-09-03 at 11 38 56 am" src="https://cloud.githubusercontent.com/assets/226500/18222497/a71c24ac-71cb-11e6-8ede-6194ae6e9e96.png">

(This point actually has 6 editable fields.)
1. Go to the right-hand scroll bar. Scroll down to reveal additional fields.

<img width="610" alt="screen shot 2016-09-03 at 11 39 05 am" src="https://cloud.githubusercontent.com/assets/226500/18222501/c692d2b8-71cb-11e6-862d-a62acbb0c62d.png">

This is a perceptual issue -- scrolling works fine, but the trend towards flat design hides the clues users might have to know when a part of a page is showing everything, vs. only a part of a larger, mostly hidden set of fields or other content.

**Comment by saleiva** [comment]
Agree @cshirky, Some of those things are being fixed directly on the Builder. Would you be interested in getting access to i?

**Comment by cshirky** [comment]
Thanks. I already have access through NYU, but we're teaching a class with Carto this week, and don't have enough time to work up new materials featuring Builder yet. We'll just warn them about this, and switch over to Builder later.

**Comment by saleiva** [comment]
Perfect, let me know if I can help you with some tricks and tips! I would love to!

**Comment by saleiva** [comment]
Already fixed in the Builder UI. Closing
