### ISSUE TITLE
Map preview not working after importing a dataset 

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#9672]
### STR
1. Create a dataset, for example using one from Data library (I used `ny_policeprecints` dataset).
2. Go to the dataset view (if you are not there yet).
3. Open chrome console.
4. Click over preview button.
5. Dataset features are not rendered, check console.

**Comment by xavijam** [comment]
It throws a 403 error in the template instantiation, please @gfiorav take a look later 💋 .

**Comment by xavijam** [comment]
Added steps to reproduce it.
