### ISSUE TITLE
cartocss: warning suggests marker-type: rectangle but it's not supported

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#9690]
when writing an invalid `marker-type`, warning suggests `marker-type: rectangle` but it's not really supported

after discussion with @rochoa this happens because torque do support `marker-type: rectangle`

![screen shot 2016-09-07 at 12 16 30](https://cloud.githubusercontent.com/assets/36676/18308904/db214e2a-74f6-11e6-93ab-9fdd932add09.png)

we should at least control the literal not appearing in non-torque maps

**Comment by rochoa** [comment]
We are using [torque-reference.js from carto](https://github.com/CartoDB/carto/blob/f17aea8657ea27f2a660db15dd13b57127e823f9/lib/carto/torque-reference.js) for all kind of layers, which is mapnik-reference 2.1.0 + torque extensions.

We need to split both references and [upgrade mapnik-reference to 2.3.0](https://github.com/CartoDB/cartodb/issues/6711), which is the version supported by the backend.

**Comment by inigomedina** [comment]
Hey @rochoa, does this issue still make sense?

**Comment by rochoa** [comment]
It does. My bet is that this should be fixed when we merge https://github.com/CartoDB/cartodb/pull/13147.
