### ISSUE TITLE
Problem adding widgets after the 'time bar'

### ISSUE THREAD

**Issue by miguelginer** [CartoDB/cartodb#9694]
When adding a widget of categories after a time bar widget has been added, it doesn’t appear in the screen in Builder (it’s on the right, but out the visible area).

![captura de pantalla 2016-09-07 a las 13 04 23](https://cloud.githubusercontent.com/assets/14316272/18309937/2dc6c182-74fc-11e6-8d61-62aa7986dce5.png)

Don’t know if related with the same combination of widgets, the time bar doesn’t move properly when showing the final map (in Builder it works):

https://team.carto.com/u/miguelginer/builder/d587811a-74e6-11e6-90d6-0ef24382571b/embed

**Comment by juanignaciosl** [comment]
Reproduced. It happens even reloading the page after adding timeseries widget. Reloading the page after adding all widgets fixes the position though.

**Comment by saleiva** [comment]
Is this still happening?¿
