### ISSUE TITLE
Provide sample init scripts

### ISSUE THREAD

**Issue by juanmaquijada** [CartoDB/cartodb#9695]
Hi, 

I use this script for start all service of cartodb:
# !/bin/bash

export CPLUS_INCLUDE_PATH=/usr/include/gdal
export C_INCLUDE_PATH=/usr/include/gdal
export PATH=$PATH:/usr/include/gdal
export PATH=$PATH:$PWD/node_modules/grunt-cli/bin
export GDAL_DATA=/usr/share/gdal/2.1
export PATH=$PATH:/opt/rubies/ruby-2.2.3/bin
redis-server &
cd ~/cartodb
bundle exec script/resque & 
bundle exec thin start --threaded -p 3000 --threadpool-size 5 &
cd ../CartoDB-SQL-API/
node app.js development  &
cd ../Windshaft-cartodb/
node app.js development  &
cd ../cartodb

but I turn off the terminal, Carto turn off. I want permanent execution.

If I try run the script from rc.local, it run as a root, but the script should be executed by my user non root.

What can I do??? Thanks!!

**Comment by zenitraM** [comment]
You can use an init script to start everything using a non-root user - either for upstart or systemd, depending on the distribution.

**Comment by hhryw** [comment]
Hi @zenitraM , 

but... init script run as root, and I need to run as non-root user. My distribution is Ubuntu Server 12.04.
