### ISSUE TITLE
Allow sequential connect with lines analysis to group by

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#9702]
Like it does on the To Source.

cc? @dgaubert

**Comment by dgaubert** [comment]
we must add a new param, right?

![image](https://cloud.githubusercontent.com/assets/1936888/18342173/bd7303e8-75ad-11e6-932d-bd068a34981e.png)

`group_by` ¿?

**Comment by dgaubert** [comment]
`category_column` is used for grouping in other [analysis](https://github.com/CartoDB/camshaft/blob/master/lib/node/nodes/bounding-box.js#L8). I'm going to use `category_column` instead of `group_by`. 

@xavijam do you agree?

**Comment by saleiva** [comment]
yes, in the same way exactly that we have in To Source option

**Comment by dgaubert** [comment]
If you need to check something in Builder you can use this [branch](https://github.com/CartoDB/camshaft/tree/190-add-category-column) that implements the analysis/camshaft part.

**Comment by xavijam** [comment]
Please @javierarce, could you take a look in the Builder side?
