### ISSUE TITLE
I can't load custom basemap from Geoserver

### ISSUE THREAD

**Issue by icetorm** [CartoDB/cartodb#9705]
Hi everyone,
CARTO got a limit of 8 layers max for each map, but i need like 20. 
So i tried to create my own basemap in Geoserver so i could import it in CARTO and then insert 8 layers with great interactivity. 
My problem is that CARTO give me this loop message: "fetching layers..." and never show me the layers that i created for the basemap, however if i use public WMS , it show me instantly all the layers from it.

Qgis loads me perfectly my wms basemap, so i don't know what it could be.
This is the url that i introduce in QGIS:
http://171.25.10.2:8080/geoserver/wms?version=1.3.0&request=GetCapabilities

Please i need your help, because it's something very helpfull to create your own custom basemaps without using mapbox and integrate it with CARTO.

**Comment by iriberri** [comment]
Hey @icetorm, thanks for your participation!

It looks like the server is not responding from my end, and CARTO is also incapable of connecting to it, so my guess is that it's not reachable from the Internet, just inside your network. That's the reason why it'd be working with QGIS (as your computer is able to reach the server) but not with CARTO.

These are the errors showing for me in my account when I try your URL, just in case it's helpful:

````
- The URL is either invalid or contains unsupported projections (see docs)


jQuery172024558129290822617_1473326740101({
  "error": "Opening given capabilities url failed."
})

````

**Comment by zenitraM** [comment]
As we use a proxy to translate WMS to TMS/XYZ URLs, the proxy needs access to your WMS server, so it is not enough that you can access the GeoServer from your browser, it has to be open to the internet.

As an alternative, you can try looking if you can serve directly TMS/XYZ from your server, as they are only checked from the browser they might work.

**Comment by icetorm** [comment]
Thanks for your answer and for helping me understand how CARTO works with WMS. I will serve directly TMS/XYZ  from GeoServer. This was very helpfull
