### ISSUE TITLE
Set maximun number of layers.

### ISSUE THREAD

**Issue by hhryw** [CartoDB/cartodb#9707]
Hello everyone,

I have installed Carto on a local machine. The maximum number of layers that a user can upload is 8. I need to increase the number of layers of a user , I'm using this:

`cd cartodb`
`bundle exec rake user:change: max_layers[ usuario, 20]`

 It does not work. I read that if you step ENTERPRISE to BUILDER to the limit is 10.

I would be grateful if you help me .

Greetings.

**Comment by iriberri** [comment]
Hey @hhryw,

try editing the user directly from the Rails console:

```ruby

u = User.find(username:'username')
u.max_layers = 15
u.save
```

**Comment by hhryw** [comment]
Hi @iriberri 

It works!!!! Thank you very much again!!!  You are the best!!!! :)
