### ISSUE TITLE
Legend backend API

### ISSUE THREAD

**Issue by nobuti** [CartoDB/cartodb#9710]
For #9584, we need an API in order to get, edit and update all legend data. Until now, only one legend per layer was allowed, but from now on, we can have up to two legends per layer. It would be nice to make it ready for more than two though.

We have five types of layers: `html`, `category`, `bubble`, `choropleth` and `custom`. The type of data we are going to save is:
- For all types, title: it could be optional
- For all types, two fields for raw html. The user can add custom html before or/and after the html of the legend, that it can't be changed by the user.
- For html type, one field with html raw. This html type is created to migrate the old legends to the builder.
- For category and custom, a collection of pairs of title and color or color and icon.
- For bubble, a fill color
- For gradient, a prefix and suffix (text)

At vizjson level, every layer node will have a legends node of type array.

If you need access to mockups in order to check the UI, ping me.

**Comment by nobuti** [comment]
Related to https://github.com/CartoDB/cartodb.js/pull/1401 for details in the vizJSON.

**Comment by nobuti** [comment]
In order to make more understandable the part of the custom html before and after the legend's code, I made a quick demo for the UI: http://codepen.io/nobuti/pen/BLoVzz. In it you will see the user can add code before and after some line marked as readonly.
👆 @alonsogarciapablo @piensaenpixel

**Comment by alonsogarciapablo** [comment]
@nobuti nice! Thanks for the demo!

**Comment by gfiorav** [comment]
Hey Buti, thanks for the ticket, it's very complete!

Some questions:

a) In categories, do you mean `cloropeth` instead `choropleth`?
b) How do you call the pre and post html in front? Let's have a consistente naming. Same goes for the others, if you've picked out names, map them out!

Thanks again 💋

**Comment by nobuti** [comment]
@gfiorav here https://github.com/CartoDB/cartodb/pull/9738/files#r78395473 you can see the naming, it follows cartodb.js' convention

**Comment by gfiorav** [comment]
Closed via https://github.com/CartoDB/cartodb/pull/9809
