### ISSUE TITLE
Can't connect local Carto instance with QGIS Carto plugin

### ISSUE THREAD

**Issue by icetorm** [CartoDB/cartodb#9715]
Good morning,

This is the SQL request that show me as example my custom CARTO to read private: (fake api-key)
https://172.30.30.11:3000/user/icetorm/api/v2/sql?q=SELECT%20*%20FROM%20viales&api_key=1231324532132132132135432132132123

This is the SQL request that show me as example your CARTO to read private: (fake api-key)
https://icetorm.carto.com/api/v2/sql?q=SELECT \* FROM viales&api_key=121151132121243123123151231321232132

The first one doesn't load, but the second one as normal it works perfectly. Could it be an error installing CARTO? I need it to configure QGIS cartodb plugin to comunicate with my carto domain.

Thanks for your help and your time.

**Comment by iriberri** [comment]
Hey again @icetorm!

Throwing some ideas here:

* Have you started the SQL API? You can find all the commands you need to get all the CARTO components running here: http://cartodb.readthedocs.io/en/latest/run.html#running-all-the-processes

* If it is started, can you access your datasets from the CARTO Editor? If you can, you might want to check the developer tools of your browser, specially the Network tab, while you load the dataset. You'll see there the request that the application does to the SQL API to retrieve your data. It could be useful for you to take a look at how the request is performed, although the sample request you're using looks good to me at first sight.

**Comment by icetorm** [comment]
Hi again @iriberri ^^

Well i think that i explained wrong my issue.  I want to connect QGIS to a local CARTO, thats why i'm using QGIS plugin (QGISCARTODB). Carto can supply requests to SQL API  because he loads and shows the dataset perfectly. The problem is that when i issue request of reading/writing from outside with the API KEY.

If you can throw me more ideas to help me detect the source of this issue, i would greatly appreciate it.

Thanks for your time and help.

**Comment by iriberri** [comment]
Oh, thanks for the clarification!

While looking at the plugin docs, I saw that you already opened an issue in the plugin project: https://github.com/gkudos/qgis-cartodb/issues/46. Unfortunately we can't help you much from here because the pulgin wasn't developed by us, but by our partners at GKudos.
