### ISSUE TITLE
Add lenght to Connect with lines analysis result

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#9719]
Now its giving also the length of each line so we should add that to the explanation of the analysis.

**Comment by dgaubert** [comment]
I've changed camshaft to return `length` in km and also returns a new column called `length_mile`. PR ready, not deployed yet.

**Comment by dgaubert** [comment]
After discuss with @rochoa I removed the a new column `length_mile`. We are going to apply a common strategy to have both metric and imperial system.

**Comment by saleiva** [comment]
so what did we do finally?

**Comment by dgaubert** [comment]
For now, we have a column `lenght` in Kilometers.

**Comment by saleiva** [comment]
ok closing then! Thanks @dgaubert!
