### ISSUE TITLE
Time-Series Widget filterable in Builder but not in Published map

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#9721]
hi @xavijam i see fran & viddo helpled w/some other time-series issues, do you know who sh/be assigned now?

S/B 9890080

## Context
Time Series widget with Torque can be filtered inside Builder but not in published map.

[Here's my test](https://team.carto.com/u/stephaniemongon/builder/3252ee68-75f3-11e6-91fa-0e233c30368f/embed)

## Process
1. Create map from dataset with date-type column
2. Set layer STYLE Aggregation to Animated, with these default settings:

  ![screen shot 2016-09-08 at 3 11 59 pm](https://cloud.githubusercontent.com/assets/1779444/18363095/9cf75834-75d6-11e6-8c55-6a802a64ef94.png)

3. From WIDGETS tab add a time-series widget based on your dataset's date-type column. Leave the widget's default settings.
4. Play the timeline animation in the widget, then click and drag on the timeline to test creating a filter (anim stops). 
5. Clear the timeline filter then Publish the map.
6. Open the Publish panel's Get the Link url in a new browser tab, and try to drag a filter in the time-series widget.

## Expected result

Time-Series widget can be filtered from Publish/Get the url map

## Current result

![time-series](https://cloud.githubusercontent.com/assets/1779444/18363366/d2527c24-75d7-11e6-8c0a-92a9f778f823.gif)

**Comment by nobuti** [comment]
Likely related to https://github.com/CartoDB/cartodb/issues/9548

**Comment by ztephm** [comment]
More details in case it helps: [Danny's map](https://team.carto.com/u/sheehan-carto/builder/f2b8d95a-7b3f-11e6-9c07-0e3ebc282e83)

Same draggable-filter issue as above, + vertical line doesn't move altho map is animating:

![torque](https://cloud.githubusercontent.com/assets/1779444/18597953/738a36b2-7c1e-11e6-9037-34d43816decb.gif)

**Comment by xavijam** [comment]
Already fixed thanks to @alonsogarciapablo 💋
