### ISSUE TITLE
Sorting a dataset seems not working in builder

### ISSUE THREAD

**Issue by jmartinter** [CartoDB/cartodb#9724]
I'm unable to display my dataset sorted by a certain column. Running a sql including 'order by <column>' or clicking on the arrows on the column header don't produce any effect in new builder dataset view.

Sorting works fine in old editor

**Comment by xavijam** [comment]
Hey @jmartinter, working for me in both, dataset page and dataset view in the Builder page, could you check if it is working now for you? thanks! 💋

**Comment by jmartinter** [comment]
@xavijam Now I was able to order the dataset by the arrows in the column header. 
But using 'Order by' in sql doesn't produce any sorting. I tested sorting by date column and sorting by numerical column, none of them worked : (
