### ISSUE TITLE
Improve AD group authorization

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#9725]
Currently, we support LDAP authentication only. We can restrict users based on branches of the LDAP tree, but we don't support proper group-based authorization.

cc @xavijam @danicarrion @javitonino @gfiorav

**Comment by danicarrion** [comment]
In the patch, I've abused the `username_field` attribute. We should create a separate attribute for this (something like `additional_search_filter` maybe?). Migration shouldn't be difficult (meaning, it can be one-off, manual) as there are only 2 customers currently using this.

**Comment by javitonino** [comment]
Do we prefer to add a custom filter or filter by group membership? I think the filter should be enough, as if you are configuring LDAP you are likely to know how those work, and I don't see a point in restricting options here.

**Comment by danicarrion** [comment]
I prefer a generic filter too, yes

**Comment by juanignaciosl** [comment]
Generic filter 👍
