### ISSUE TITLE
AOI Radial Buffer Dissolve Parameter allow for Single Part Features (disallow multipart features)

### ISSUE THREAD

**Issue by nygeog** [CartoDB/cartodb#9727]
When I select the Dissolved parameter on the AOI Radial Buffer, my assumption would be that it would dissolve features that were coincidental (have shared boundaries), not dissolve all the features into one multipart polygon. Perhaps we could add that as a parameter like in Esri’s Dissolve tool `Specifies whether multipart features are allowed in the output feature class. MULTI_PART—Specifies multipart features are allowed. This is the default. SINGLE_PART—Specifies multipart features are not allowed. Instead of creating multipart features an individual features will be created for each part.`

**Comment by saleiva** [comment]
hi! Can you complement this with an use case?

**Comment by nygeog** [comment]
Sorry for the delay didn't see this. Let's say you were counting features within buffers with a shared attribute or a features that are expected to be close to one another. So for example, I'm trying to count the number of features (such as pizza shops) within a AOI Radial Buffer of 1 km from Subway Entrance Points (Subway Stations being 1 feature, Entrance Points being multiple features around a Subway Station). I may want to Dissolve (GroupBy) by a common attribute such as Subway Station ID or I may want to Dissolve by Buffers that share coincidental space (and perhaps generate a new ID for this blob of buffers) and then do a Spatial Join Summarize Count of Features. 

If I do this w/ out Dissolve, I'll attribute the point features to each Buffer and will be double counting those features, this could be remedied by those features having a unique ID to GroupBy or Frequency on, but that's an additional few steps. If I run a Dissolve on the whole Buffer Feature Class to get a single feature I'll get an accurate total count but will be unable to disaggregate the counts to each blob of coincidental features or Station ID. 

There are always other workarounds, could use a Near Function (from point Pizza layer to Subway Entrances) instead of a buffer and drop those that have no Subway Entrance points equal to or within 1 km and aggregate by Station ID to get a count. My advocacy for this is that from a demo I was giving, regarding subway entrance points, I wanted to calc. population within 1 km of subway entrances (the current workflow double counted coincidental regions shared by the Buffers) and the current behavior would require me to write SQL in the Builder to do this correctly. Another options is an individual Dissolve tool that can be used prior to a Spatial Join or Intersect function.

**Comment by saleiva** [comment]
uhm... understood! Thanks!!
