### ISSUE TITLE
Opening Editor map at Builder creates analysis

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#9730]
Opening an Editor-created map with the Builder adds this to layer `options`:

```
    "source": "a0",
    "letter": "a"
```

… and it creates an analysis.

Probably this shouldn't happen, as there hasn't been any user interaction.

cc @xavijam @gfiorav @javitonino

**Comment by gfiorav** [comment]
This is expected behaviour! 

If you open any map on the builder, source analysis are created automagically: if it's a new map it happens in the backend and if it's an existent map it happens in the frontend.

Is this what you reporting?

**Comment by juanignaciosl** [comment]
@xavijam and @gfiorav say that this is expected. Closing then.
