### ISSUE TITLE
Remove the compatibility dialog that appears in the Editor

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#9731]
Although we display a "WAIT! This map contains new Builder features that are not supported in the Editor” warning opening a map “backwards”, there’s a `POST` to map endpoint that might break something.

Probably that POST should be avoided.

cc @xavijam @gfiorav @javitonino

**Comment by xavijam** [comment]
We have to remove that dialog because we will not provide backwards compatibility, so let me move this one to the next sprint.

**Comment by xavijam** [comment]
So, the new title should be: Remove the compatibility dialog that appears in the Editor.

**Comment by MariaCheca** [comment]
Not needed anymore, we just have to change the message in the dialog.
