### ISSUE TITLE
When a node has a query without the_geom/the_geom_webmercator, builder displays a message saying map is failing

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#9734]
It is true, but not really, because if the user is not requesting any geometry, that layer can't be rendered, shouldn't we change the message, and probably render the map empty?

![screen shot 2016-09-12 at 11 50 23](https://cloud.githubusercontent.com/assets/132146/18431833/1c82b066-78df-11e6-9b32-67a0e9d6d6ec.png)

cc @rochoa @javisantana

**Comment by rochoa** [comment]
If the user is applying a custom SQL in the layer and it's not providing the_geom_webmercator column it's an error.

IMO we need to inform the [advanced] user what the error is.

**Comment by alonsogarciapablo** [comment]
The thing here is that Windshaft is returning an `unknown` error to CartoDB.js, and we show a generic "This map couldn't be rendered..." message in those circumstances. I talked to @rochoa about this yesterday, and we agreed that the Maps API should return more human-readable error messages (checkout [this issue](https://github.com/CartoDB/Windshaft-cartodb/issues/571)).

But still, we are not displaying error messages for unknown errors... And, with the information that we're getting, we can't currently know that it's a `sql` error for layer XXX (and set the error on a layer model for example...

@xavijam what do you suggest? Should we replace that generic message with the error message that we get from Windshaft (we can make it more human readable in CartoDB.js before [this issue](https://github.com/CartoDB/Windshaft-cartodb/issues/571) is done).
