### ISSUE TITLE
Always store items appended to Log

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/cartodb#9736]
When using `CartoDB::Log` we sometimes call `#append` while other times we use `#append_and_store`.

The latter has the benefit (and overhead) of re-reading the log items from the db (so that items stored from other processed are not overwritten). But it will lose items appended (via `#append`) since the last `#store` call.

Since we are not systematically calling `#store` after having appended new items and before calling `#append_and_store` we may be losing log items. When a piece of code needs to append items to a `Log` we have now this alternatives:
- Use `append`s and, before yielding control to other code, call `store` (possibly overwriting items from other processes).
- Use  `append_and_store` (and overwrite appends which weren't stored).

I propose to always use `#append_and_store` (renamed as `#append`) to avoid missing any log items.

For example:

``` diff
--- a/app/models/log.rb
+++ b/app/models/log.rb
@@ -103,13 +103,6 @@ module CartoDB
       end
     end

-    # INFO: Does not store log, only appends in-memory
-    def append(content, truncate = true, timestamp = Time.now.utc)
-      @dirty = true
-      content.slice!(MAX_ENTRY_LENGTH..-1) if truncate
-      add_to_entries(ENTRY_FORMAT % [ timestamp, content ])
-    end
-
     def append_and_store(content, truncate = true, timestamp = Time.now.utc)
       refresh
       # Sync content from other processes. Ie. geocoding cancel
@@ -118,8 +111,18 @@ module CartoDB
       store
     end

+    alias :append :append_and_store
+
     private

+    # INFO: Does not store log, only appends in-memory
+    def _append(content, truncate = true, timestamp = Time.now.utc)
+      @dirty = true
+      content.slice!(MAX_ENTRY_LENGTH..-1) if truncate
+      add_to_entries(ENTRY_FORMAT % [ timestamp, content ])
+    end
+
+
     def add_to_entries(content)
       if @fixed_entries_half.length < half_max_size
         @fixed_entries_half << content
```

This will have the overhead of re-reading the `Log` record from the database each time an item is appended. I think this should not significantly affect any processes, since we shouldn't be using `Log#append` in inner loops or performance-critical situations.

We could add a parameter to `append` to choose ignoring other processes' items and avoiding so the overhead where it might matter.

What do you think? /cc @ethervoid @rafatower

**Comment by rafatower** [comment]
Maybe. I wouldn't strive for improving this too much cause we know that logger is not the panacea. IIRC it is only used in imports and syncs and there should be no concurrency. OTOH reads shall be faster than writes and as you said it should never be added in any performance critical situation.

The important thing if that change is carried out is to make sure the users of that logger understand those conditions so it is not misused.

Unless this is a real problem right now I'd leave it as-is and tackle it more fully when there's room for it. 

How I'd do it: have 1 row of log = 1 row in db instead of reading/writing. Limit the length of the rows and limit the number of rows so instead of having that magic in buffers (that sometimes fail) have a real persistent circular buffer (not that much work when it's clear but requires at least one DB migration).

Leapfrog I heard? :)

**Comment by jgoizueta** [comment]
Set aside for leapfrog 😁

**Comment by jgoizueta** [comment]
More sensible fix:

```diff
@@ -102,26 +102,29 @@ module CartoDB
         end
       end
     end
 
-    # INFO: Does not store log, only appends in-memory
-    def append(content, truncate = true, timestamp = Time.now.utc)
-      @dirty = true
-      content.slice!(MAX_ENTRY_LENGTH..-1) if truncate
-      add_to_entries(ENTRY_FORMAT % [ timestamp, content ])
+    def append(content, truncate = true, timestamp = Time.now.utc, store_log = false, refresh_log = false)
+      refresh if refresh_log
+      _append content, truncate, timestamp
+      store if store_log
     end
 
-    def append_and_store(content, truncate = true, timestamp = Time.now.utc)
-      refresh
-      # Sync content from other processes. Ie. geocoding cancel
-      rehydrate_entries_from_string(entries)
-      append(content, truncate, timestamp)
-      store
+    def append_and_store(content, truncate = true, timestamp = Time.now.utc, refresh_log = false)
+      append content, truncate, timestamp, true, refresh_log
     end
 
     private
 
+    def _append(content, truncate = true, timestamp = Time.now.utc)
+      @dirty = true
+      content.slice!(MAX_ENTRY_LENGTH..-1) if truncate
+      add_to_entries(ENTRY_FORMAT % [ timestamp, content ])
+    end
+
+
     def add_to_entries(content)
       if @fixed_entries_half.length < half_max_size
         @fixed_entries_half << content
       else
         @circular_entries_half[@circular_index] = content
```
