### ISSUE TITLE
Enabled Viewer user

### ISSUE THREAD

**Issue by hhryw** [CartoDB/cartodb#9745]
Hi all, 

I install Carto on local machine. 

Can I enable Viewer users by terminal? 
Can I enable Viewer users by web interface, "organization settings"? 

Thanks!

**Comment by xavijam** [comment]
Hi @hhryw, questions about how CARTO works, please post your doubts in this google group: https://groups.google.com/forum/#!forum/cartodb. We try to use this issues for problems found in the application.

Cheers!
