### ISSUE TITLE
Time-series widget displays more bins than date data  

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#9746]
### STR
- Create a map from a dataset with a `date` column. This column has a range of values between `2015-12-18T00:00:00Z` and `2016-09-08T00:00:00Z`.
- Add a time series widget and a formula widget (in order to count rows).
- Filter from `15:52 09/22/2016`  to  `00:00 10/01/2016`. The expected result would be just one data point, but instead, you get 571 rows (see screenshot below):

![timeseries](https://cloud.githubusercontent.com/assets/5215798/18474422/33a7e52a-79c2-11e6-87f2-2de067e62687.png)
- This behaviour is also described happening with Deep Insights.

**Comment by saleiva** [comment]
It looks like very often it is setting way too much bins

**Comment by xavijam** [comment]
This problem will be tackled in #12088.

**Comment by matallo** [comment]
this has already been pushed as part of https://github.com/CartoDB/cartodb/pull/12464

shall we close the issue then @ramiroaznar ?

**Comment by ramiroaznar** [comment]
Yes! Thanks mates!
