### ISSUE TITLE
remove viz.json link in sharing options for the builder

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#9750]
hey, as we don't have a way to change thins using the api we should remove the viz.json link in sharing window 

cc @xavijam @saleiva @CartoDB/design

**Comment by saleiva** [comment]
@urbanphes did you review the share modal finally? Can you take care of this?

**Comment by xavijam** [comment]
Oh, design changes? makes sense, because that step without options looks weird, so +1 to review it and then I'll take care of it.

**Comment by urbanphes** [comment]
By the moment for adapt it the actual design we remove the option viz.json and leave on 3 modules like a widget screen modal.

You can see the result here:

![05 publish - 00-02](https://cloud.githubusercontent.com/assets/14546701/18911388/18761260-857d-11e6-852b-8b0b6d0c2a7f.png)

![05 publish regular user - 01-02](https://cloud.githubusercontent.com/assets/14546701/18911390/1d1681a6-857d-11e6-91b1-0389dbb6e29d.png)





We're working on that screen to have the best solution.

**Comment by xavijam** [comment]
@MariaCheca please, could you take care of it?, this is quite important for the release.

**Comment by MariaCheca** [comment]
👍

**Comment by MariaCheca** [comment]
@xavijam @javisantana the viz.json link is present in both CARTO.js and Mobile SDK sharing options, does that mean we should also remove the Mobile from that list?

**Comment by saleiva** [comment]
wait, mobile sdk would dissapear as well. Then I think we need to rethinkg the window a bit

**Comment by saleiva** [comment]
@urbanphes please take care!

**Comment by arianaescobar** [comment]
This is a wonderful opportunity for moving it to the sidebar with the other sharing settings as we talked about @urbanphes

**Comment by urbanphes** [comment]
@saleiva are you agree with @arianaescobar says?
Perhaps is the moment to think on that and do it.

**Comment by arianaescobar** [comment]
(He said in the office that he agrees)

**Comment by urbanphes** [comment]
@xavijam and @MariaCheca we will working on this (design).

**Comment by MariaCheca** [comment]
thanks @urbanphes! keep us updated :)

**Comment by javisantana** [comment]
Think that at some point in the following months the viz.json will be there again so please, "look to the future"

**Comment by arianaescobar** [comment]
Will do, boss @javisantana :P

**Comment by urbanphes** [comment]
Oks @javisantana we will take into account

**Comment by xavijam** [comment]
How is it going in the design laboratory mates?

**Comment by arianaescobar** [comment]
We aaaalmost got it.

**Comment by javitonino** [comment]
Just a comment for when we do this change: We should mark the textboxes as `readonly` (they are not right now, and you can write on top of them).

**Comment by saleiva** [comment]
\o/
