### ISSUE TITLE
Layer hidden infobox button is too big

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#9752]
![screen shot 2016-09-14 at 12 53 02](https://cloud.githubusercontent.com/assets/132146/18509696/404e3faa-7a7a-11e6-9355-a5dae703fa3d.png)

Don't you think @piensaenpixel @urbanphes @josecruz ?

cc @nobuti

**Comment by xavijam** [comment]
In my opinion should be smaller and aligned to the right.

**Comment by MariaCheca** [comment]
Actually the last design files I have access to are slightly different:
<img width="339" alt="screen shot 2016-09-14 at 16 18 52" src="https://cloud.githubusercontent.com/assets/2141690/18515818/fb0f4048-7a96-11e6-8142-45876d53e51b.png">

Maybe we should change the button style to a small secondary one and align it to the right.

**Comment by xavijam** [comment]
I feel you can do it with the options of the infobox so \o/

**Comment by urbanphes** [comment]
Thanks @MariaCheca that's

**Comment by MariaCheca** [comment]
Not closed yet, buttons design issue is still pending ;)
