### ISSUE TITLE
Removing a dataset linked to various layers of a map results in broken map

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#9759]
# STR

1. Create a dataset
2. Create a map with 2 layers referencing that dataset
3. Remove dataset (user warned)

# Expected result

The map is deleted

# Actual result

The map isn't deleted and is left like an (accessible) _"empty shell"_, a map with no layers

Related to https://github.com/CartoDB/cartodb/issues/9758

cc/ @javitonino @juanignaciosl

**Comment by juanignaciosl** [comment]
@gfiorav is the user warned about the deletion on step 3?

**Comment by gfiorav** [comment]
Yes!

**Comment by javitonino** [comment]
Uhm, cannot reproduce this anymore :disappointed:

**Comment by juanignaciosl** [comment]
This is fixed now (checked both editor and builder) ✨
