### ISSUE TITLE
Aggregation by Hexbin or Hexabin? (spelling)

### ISSUE THREAD

**Issue by nygeog** [CartoDB/cartodb#9764]
Matplotlib and R and other packages refer to hexagon binning as hexbin, our platform refers to it as hexabin. 

![screen shot 2016-09-14 at 2 00 56 pm](https://cloud.githubusercontent.com/assets/2790599/18523772/b915bc5c-7a83-11e6-9a9c-dfbb6b566884.png)

**Comment by xavijam** [comment]
Yeah @nygeog, it is a typo, I have no idea why we started to call it as hexabin, but it is wrong.
Thanks for the feedback and if you can create a pull request would be appreciate it :).

**Comment by saleiva** [comment]
Hexbin everywhere, please

**Comment by saleiva** [comment]
cc/ @CartoDB/design

**Comment by xavijam** [comment]
Label change already ready in production.

**Comment by arianaescobar** [comment]
Already done on design mockups as well.

**Comment by csobier** [comment]
Good to know, updating all doc and images for the next Sprint. Thanks
