### ISSUE TITLE
Transitioning from portrait to landscape mode on mobile layout, the layers menu reduces its scroll region

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#977]
From @nick13jaremek:

Had 4 layers in a visualisation, one legend per layer.

Test layer: https://team.cartodb.com/u/nickjaremek/viz/9bfc944a-4878-11e4-94f2-0e9d821ea90d/map

Steps to reproduce on Android: 
1. Open a visualisation on a mobile device (make sure the mobile layout appears) on PORTRAIT mode
2. Open the layer selector menu (top-right corner)
3. Rotate the device to move to the landscape mode (keep the layer selector menu open)
4. Scroll down the layer selector list: part of some legends are unreachable
5. Rotate the device to portrait mode again having the layer selector option open
6. The layer selector scroll region has been reduced (shifted upwards)

Steps to reproduce on iOS:
1. Open a visualisation on a mobile device (make sure the mobile layout appears) on PORTRAIT mode
2. Open the layer selector menu (top-right corner)
3. Rotate the device to move to the landscape mode (keep the layer selector menu open)
4. Scroll down the layer selector list: part of the legends is unreachable (quite less than in the Android case)
5. Rotate the device to portrait mode again having the layer selector option open
6. The layer selector scroll does not reach part of the last layer's legend

**Comment by xavijam** [comment]
We will manage this issue within new editor, closing!
