### ISSUE TITLE
Correct style for some layer elements when its hidden

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#9771]
Hi guys! 

This is an enhancement of the style of a layer when it's hidden so it's more clear that it is.  

The layer title should be in #CBCED0 and the icon in 24% transparency. 

![artboard](https://cloud.githubusercontent.com/assets/16247628/18546740/dfa38004-7b3f-11e6-936f-bfe92afc1828.jpg)

Let me know if you have any question :) 
and thanks!

**Comment by xavijam** [comment]
Easy peasy, @MariaCheca will do it in a minute 💋 .
