### ISSUE TITLE
Add flip action to color ramps 

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#9774]
Hi!

We want to add the ability of flipping de direction of the color ramps. Below you can see the design and interaction:

![ramp flip](https://cloud.githubusercontent.com/assets/16247628/18556575/f7dc3afe-7b6b-11e6-95cb-c538c68c8c3f.jpg)

- It will look and work the same on tablet.
- When you flip a color ramp, the icon also flips. 
- Custom colors won't have that action.

Let me know if you have any doubt! 

_______________________

Related issue in /design: https://github.com/CartoDB/design/issues/215

**Comment by xavijam** [comment]
Hey, @javierarce already created a PR with this change :S.

https://github.com/CartoDB/cartodb/pull/9687

**Comment by arianaescobar** [comment]
@xavijam oh! 

Well, the interaction it's the same. The only difference is that the width of the color ramps it's always the same and a new icon. 

Could we update that PR with those two new changes? 

(Sorry for re-doing work, Juanma wasn't aware of this PR and he wasn't too happy with the current design so he asked me to work a bit more on it).

**Comment by xavijam** [comment]
Passing to @javierarce in order to change the PR 💋 .

**Comment by AbelVM** [comment]
Call me blind, but I think that the flipped icon should be (somehow) bolded to highlight that it is actually flipped.
