### ISSUE TITLE
Builder dataset view "duplicate dataset from query" errors out

### ISSUE THREAD

**Issue by andrewbt** [CartoDB/cartodb#9775]
Steps to Reproduce:

1. Open random dataset in new "/dataset/" viewer. (The dataset's not important, I'm trying to create a new table using Data Observatory so just need a SQL pane that works)

2. Type in SQL:
```
INSERT INTO nj_boundary (the_geom, name)
SELECT *
FROM OBS_GetBoundariesByGeometry(
 ST_MakeEnvelope(-76.04736328125,38.764256548069305,-73.10302734375,41.6169823542308),
 'us.census.tiger.state'
) As m(the_geom, geoid)
```

Or, you could try this SQL which should also work (but currently also errors):

```
SELECT *
FROM OBS_GetBoundariesByGeometry(
 ST_MakeEnvelope(-76.04736328125,38.764256548069305,-73.10302734375,41.6169823542308),
 'us.census.tiger.state'
) As m(the_geom, geoid)
```

(I would additionally like to add `; select cdb_cartodbfytable('athompson','nj_boundary')` but multiple SQL instructions with a semicolon is also currently rejected by new Builder SQL editor)

2. The Dataset refreshes to have a "the_geom" and "geoid" columns in the table view, though oddly these are greyed out and there are no _rows/results_ below them.

3. Try "Duplicate dataset from query" button

4. See "red bug" error screen that says "There was an error duplicating applied query: Error creating table from SQL query"

**Comment by xavijam** [comment]
Hey @andrewbt, that 
```
SELECT *
FROM OBS_GetBoundariesByGeometry(
 ST_MakeEnvelope(-76.04736328125,38.764256548069305,-73.10302734375,41.6169823542308),
 'us.census.tiger.state'
) As m(the_geom, geoid)
```

fails for me, works for you?

**Comment by xavijam** [comment]
Woah, this is a really weird use case, but the query applied worked (retreiving the query schema) but then trying to get rows data, it fails 😱 . Fixing it right now!

**Comment by xavijam** [comment]
The behaviour with the duplication is correct, because there is an error duplicating it, so the problem is related with the data fetching.
