### ISSUE TITLE
Builder SQL pane semicolons edge case bug

### ISSUE THREAD

**Issue by andrewbt** [CartoDB/cartodb#9777]
see former issues #9071 and #9245 , and merged PR #9283 which may have fixed some but left edge case:

Try two (or more) SQL statements in Builder SQL pane like

```
select 1;
select 2;
select 3
```

A syntax error "near ;" is thrown, despite this should be a valid query

**Comment by xavijam** [comment]
Hey @andrewbt, this is not an error included in the Builder, it is related with the SQL API, I've tried the same in the old editor and it fails too:

![screen shot 2016-09-16 at 11 45 10](https://cloud.githubusercontent.com/assets/132146/18581978/38b969f6-7c03-11e6-958a-41f8072a465d.png)

I encourage you to try that query with the SQL (no UI) and check that fails too.
Probably we should create a new ticket in SQL API repository?

**Comment by xavijam** [comment]
Closing it since it is not due to anything related with the builder :kiss:

**Comment by andrewbt** [comment]
@ohasselblad what say thee to this? I remember you had opened the original issue #9245 . I swear I've used semi colons in Editor before too....

**Comment by ohasselblad** [comment]
Weird, it doesn't fail in the SQL API for me: http://eschbacher.cartodb.com/api/v2/sql?q=select%201;%20select%202;%20select%203

**Comment by andrewbt** [comment]
Yep, I also just ran a double alter table statement in the Editor that worked well @xavijam !

<img width="621" alt="screen shot 2016-09-21 at 4 48 16 pm" src="https://cloud.githubusercontent.com/assets/2013555/18728497/5c61f956-801b-11e6-90e5-eef5e7e8e07a.png">

**Comment by xavijam** [comment]
That alter table query will work in the Builder too, because "update" and "select" queries are managed differently.
