### ISSUE TITLE
Warn organization owner if signup is enabled but not valid

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#9778]
If organization signup is enabled (authentication enabled and whitelisting emails) but not valid (because seat or quota limit has been reached) organization settings page should display an error.

Some design magic is needed (@josecruz ?).

cc @yasharora73 @gfiorav @javitonino @xavijam

**Comment by juanignaciosl** [comment]
@urbanphes, @josecruz  I've added this to "To be designed". Could you please take a look? Ping me if you can't, please.

**Comment by saleiva** [comment]
Prioritized in the design kanban

**Comment by arianaescobar** [comment]
Is this what you're looking for @juanignaciosl? Also, @urbanphes would this be ok, framework wise?

![organization - auth settings - warning2](https://cloud.githubusercontent.com/assets/16247628/22062145/9a178ef4-dd78-11e6-9414-bffd52f681ea.png)

![organization - auth settings - warning](https://cloud.githubusercontent.com/assets/16247628/22062093/57fdd226-dd78-11e6-9b3f-3c93d4b166c3.png)

**Comment by juanignaciosl** [comment]
It seems a great solution to the issue :-) It's different from "flash errors", so the user can know just seeing it that "the current configuration/organization state is somehow invalid". We can customize the texts depending on the case.

Nevertheless, I want to make a comment: what do you think about moving it over the tabs?

![57fdd226-dd78-11e6-9b3f-3c93d4b166c3](https://cloud.githubusercontent.com/assets/932968/22063697/72d03fdc-dd80-11e6-9382-23c0f1219025.png)

I suggest that because of this:
- The comment might not _only_ be related to "Auth settings" but general (for example, running out of seats). If you display it inside a tab it seems related. Nevertheless, if you display it outside, it's obviously global.
- The discoverability of the problem is easier, as you don't have to go through every tab.

**Comment by arianaescobar** [comment]
That's certainly interesting, being an account-wise big issue and not a tiny one related to certain  settings. But again, summoning @urbanphes since from what I've seen on the mockups, that element it's always shown below the tabs...

**Comment by urbanphes** [comment]
Is interesting this approach. As @juanignaciosl  says if we put this module over the tabs is something more generic that affect to all tabs. In this moment I don't have reference all dashboard UI but I think we could do it this. It sense. Perhaps @carlostallon and @josecruz can give us more context

In the other hand, in the future, we should think re-design the dashboard.

**Comment by carlostallon** [comment]
The problem that I see with this approach is that it seems like the header of all that section instead of an alert/error. Maybe it's a matter to change the background-color to fix it.

Shouldn't it be visually related with the info-box we have in the sidebar? Also I would use a different icon due it's a different message.

**Comment by xavijam** [comment]
Nobody is on charge of this one?

**Comment by arianaescobar** [comment]
@xavijam I'm planning on picking this one up after applying feedback [on this one](https://github.com/CartoDB/design/issues/442) if nobody else picks it first :)

**Comment by urbanphes** [comment]
I found another example (on the dashboard) to notify something and I thought it could be interesting use it.

This kind of notification can be present about all navigation through the "configuration" section and are independent of the tab that user stay. 

I think these notifications should be permanent through the navigation, in this way we force to admin to make it something.

The look and feel aren't than aggressive and it saves the relationship with the alert color on Builder.

Here the visual:

![organization - auth settings - warning opt 3](https://cloud.githubusercontent.com/assets/14546701/22146729/e9ef62d8-df05-11e6-8576-10b4b1c52b97.png)

**Comment by arianaescobar** [comment]
Love that!

**Comment by carlostallon** [comment]
Yep, it solves the problem I mentioned yesterday, +1

**Comment by piensaenpixel** [comment]
+1

**Comment by saleiva** [comment]
Close and promote please!

**Comment by arianaescobar** [comment]
It's kind of already promoted, since this ticket it's in cartodb's repo 🙃

**Comment by juanignaciosl** [comment]
Moved to TODO in Builder kanban, thanks! ✨

**Comment by ivanmalagon** [comment]
All signup flow tested and working but a minimal issue. The warning banner doesn't appear in `Groups` tab. It shows up in the rest of tabs `Profile, Auth y Users`.

Apart from that, all the use cases work properly.

**Comment by ivanmalagon** [comment]
All cases tested. Now working also in `Groups` tab.

Passing this to deployment.
