### ISSUE TITLE
Firefox - Builder Infowindow Titles Not Editable

### ISSUE THREAD

**Issue by michellechandra** [CartoDB/cartodb#9780]
## STR
Using Firefox Browser (48.0.2) on Mac OS, create a map with pop-ups. When editing the names of the columns shown in the pop-up, the form field is not editable and no changes can be made:

![screen shot 2016-09-15 at 09 46 00](https://cloud.githubusercontent.com/assets/5423288/18565938/adecab10-7b46-11e6-9913-a9a2448fcbc8.png)

No errors in the developer console. 

S/B: 9949849

cc @CartoDB/support for awareness

**Comment by xavijam** [comment]
Could you take a look @matallo?

**Comment by matallo** [comment]
sure thing
