### ISSUE TITLE
Analysis: Connect with lines - Type: Sequential ; feature request, GroupBy

### ISSUE THREAD

**Issue by nygeog** [CartoDB/cartodb#9781]
This dataset for example is GPS tracks for WaiveCar, a car sharing service in Santa Monica. The cars each have a unique ID and a datetime stamp. The Connect with Lines tool, type: sequential is awesome. And it'd be really awesome to also allow the ability to connect with lines sequentially, but yet also GroupBy'ed each car's unique id. In this example its just taking any GPS point and connecting the next one with the next closest timestamp (ascending.)

![screen shot 2016-09-15 at 7 14 39 pm](https://cloud.githubusercontent.com/assets/2790599/18570516/afe42ac4-7b78-11e6-8b2e-6935596796ef.png)

**Comment by saleiva** [comment]
@nygeog this is being tackled right now in https://github.com/CartoDB/cartodb/pull/9839
