### ISSUE TITLE
Wrong label text on edit widget form 'behaviour' step

### ISSUE THREAD

**Issue by MariaCheca** [CartoDB/cartodb#9784]
In the edit view for a widget, the label `DEFINE HOW YOUR WIDGET INTERACTS WITH THE DATA` is not the good one, it should say 'Description'.

<img width="333" alt="screen shot 2016-09-16 at 10 15 54" src="https://cloud.githubusercontent.com/assets/2141690/18579579/e1ee4c74-7bf6-11e6-846c-c299749bd6c9.png">

**Comment by xavijam** [comment]
cc @piensaenpixel

**Comment by saleiva** [comment]
But its not a problem of the overflow. Its a problem of the text. It should say just "DESCRIPTION"

**Comment by xavijam** [comment]
yeah, agree with @saleiva

**Comment by MariaCheca** [comment]
Hum, you're right, so the issue title must be redefined :) Thanks!

**Comment by piensaenpixel** [comment]
uhm but the problem is not only the ellipsis... it's also the label position, @MariaCheca let me check this one.

**Comment by MariaCheca** [comment]
All yours!
