### ISSUE TITLE
Incorrect execution of db queries

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/cartodb#9786]
I've spotted a number of places where we're misusing the Sequel database connection method `execute` when we expect to handle the result rows. Some are probably dead code, but we should check and either fix or remove the code.

When the result rows of a SELECT are to be handled, the `fetch` method must be used instead of `execute` which only returns the number of rows affected. This is confusing because the ActiveRecord connection method   `execute` behaves like Sequel's `fetch`. (so we have valid cases of using `execute` to fetch SELECT results in the code).

These are the suspects:
- [UPDATE: this is fine: user class is and ActiveRecord]
  https://github.com/CartoDB/cartodb/blob/0bf4e743bd9eef7fee5a6c2f3649a4aa2713a9c0/app/models/carto/layer.rb#L244
- [UPDATE: this is fine: ActiveRecord classes]
   https://github.com/CartoDB/cartodb/blob/0bf4e743bd9eef7fee5a6c2f3649a4aa2713a9c0/app/models/carto/user_service.rb#L69
- [UPDATE: this is fine: ActiveRecord classes]
  https://github.com/CartoDB/cartodb/blob/0bf4e743bd9eef7fee5a6c2f3649a4aa2713a9c0/app/models/carto/user_service.rb#L126
- [UPDATE: this is fine: not using results]
  https://github.com/CartoDB/cartodb/blob/0bf4e743bd9eef7fee5a6c2f3649a4aa2713a9c0/app/models/synchronization/adapter.rb#L340-L350
- https://github.com/CartoDB/cartodb/blob/0bf4e743bd9eef7fee5a6c2f3649a4aa2713a9c0/app/models/table/column_typecaster.rb#L207-L209

The last one depends on what type of database connection it is passed as argument to the `ColumnTypecaster` constructor, and at least from here we're passing the wrong one:
https://github.com/CartoDB/cartodb/blob/0bf4e743bd9eef7fee5a6c2f3649a4aa2713a9c0/app/models/table.rb#L902

Update: I've realized that `Carto::User#in_database` returns a `ActiveRecord::ConnectionAdapters::PostgreSQLAdapter` while `User#in_database` is a `Sequel::Postgres::Database`, so some of the cases above are probably right.

Update: the last example is always executed with a Sequel database, but note that the block passed to `execute` (the ` &:to_a` argument) makes it return the result rows, so it is correct.

**Comment by jgoizueta** [comment]
Example:

```ruby
ActiveRecord::Base.connection.execute("SELECT version()").to_a
# => [{"version"=>"PostgreSQL 9.5.2 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu/Linaro 

User.first.in_database.execute("SELECT version()")
# => 1

User.first.in_database.fetch("SELECT version()").to_a
# => [{:version=>"PostgreSQL 9.5.2 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu/Linaro ```

**Comment by jgoizueta** [comment]
Note also that `ActiveRecord::ConnectionAdapters::PostgreSQLAdapter#execute` returns hashes indexed by strings (`{"version" => ...}`) while `Sequel::Postgres::Database` returns hashes indexed by symbols (`{:version => ...}`)

**Comment by inigomedina** [comment]
Hey, @jgoizueta, is this issue ready to be closed?

**Comment by jgoizueta** [comment]
Sorry for the delay @inigomedina. I've finally checked this and I'm closing it since it's working well.
