### ISSUE TITLE
Support groups on Enterprise API (EUMAPI)

### ISSUE THREAD

**Issue by jsanz** [CartoDB/cartodb#9789]
Supporting groups creation/modification at API level and afterwards allowing to assign users to them.

**Comment by juanignaciosl** [comment]
@danicarrion , @andrewbt , is this convenient for migration?

cc @javisantana @CartoDB/builder-backend

**Comment by gfiorav** [comment]
Maybe we could add this to [EUMAPIv3](https://github.com/CartoDB/cartodb/issues/9789) specification

**Comment by juanignaciosl** [comment]
v3 should support groups, but maybe we should add groups support at v2 before the v3 rewrite.

**Comment by gfiorav** [comment]
I had to try 😂

**Comment by javisantana** [comment]
I'd really need to see some data here. The numbers for this feature in production are really really low,  do you have some stats from onpremise usage?

**Comment by juanignaciosl** [comment]
I don't. Maybe @andrewbt or @danicarrion . @oriolbx said months ago that some huge installations were using groups, but I have little detail.

**Comment by andrewbt** [comment]
If I had to take a wild guess (and I mean really wild, by the gut), I would say onpremise usage of groups (and even moreover the EUMAPI) is probably low. The one exception to that might be anyone who's using LDAP integration onpremises, where I bet groups are more useful. But then LDAP users could "migrate" by just re-importing the LDAP groups on Onprem v2.0 install.

@oriolbx or @ernesmb might have better intelligence from onpremise support requests.

**Comment by ernesmb** [comment]
hey we don't really have numbers or even a hint about whether people is using groups or not. 

I don't think we've had support requests related to this feature, so I'd say it's usage is low as well, but that's just a **guess**

**Comment by juanignaciosl** [comment]
Closing automatically because of inactivity. If anybody considers that this still important, please reopen and it'll be prioritized.

**Comment by juanignaciosl** [comment]
Reopening, we're using this as a test.
