### ISSUE TITLE
Lost selection on adding users to a group 

### ISSUE THREAD

**Issue by jsanz** [CartoDB/cartodb#9790]
### STR

Choose an enterprise account with many users so we have more than one page on the assign to group interface. I want to assign several users across different pages to that group.

My use case was on an Org with ~30 seats,  I wanted to add all of them except the owner to a general group.
### Expected result

When selecting users of a page and then changing the page I want the selection to be retained or at least to be asked for saving before moving to a different page.
### Current result

I move to a different page and the selection of the previous page is removed.

**Comment by inigomedina** [comment]
@jsanz does this issue still make sense? Can we close it now?

**Comment by jsanz** [comment]
It's ok to close, not a big deal.
