### ISSUE TITLE
feature request: add multiple datasets in import modal

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartodb#9792]
The ability to add more than one dataset at a time would be killer :) 

I could see a couple of workflows here:
1. After connecting one dataset, the modal remains open,  the file starts importing, and there is an option to 'add another dataset' so they appear as a list of imports in progress
2. When clicking connect dataset, a user could select multiple files on their computer and all of them would then be selected to import
3. From this modal, the user would have the option to bundle datasets into a map once imports are successful 

cc @xavijam

**Comment by andy-esch** [comment]
cc @CartoDB/design this is a UX / speed gain for me. Being able to upload multiple datasets in one go -- without having to repeat the process of uploading one at a time -- would save time.

**Comment by piensaenpixel** [comment]
totally agree @andy-esch. We'll think about it :). Thanks dude.
