### ISSUE TITLE
Background color changing in Builder with certain basemaps in Style > CartoCSS view

### ISSUE THREAD

**Issue by makella** [CartoDB/cartodb#9797]
Hello,

When using basemaps like Toner Hybrid or Toner Lines, the background color of the map is an off white color. This is the same color that remains on the published map. 

The issue is that if you are using one of these basemaps and switch to Style > CartoCSS, the background color of the map changes to the same background color as the CartoCSS editor. 

This is difficult for design purposes if the background of the map is not the same color as the published version when writing out CartoCSS.

Of course people may put a background of their own behind these basemaps, but I am working on a map where I want no background and only the Toner Lines linework.

Here is a demonstration of what is happening:

![styling-basemap](https://cloud.githubusercontent.com/assets/1566273/18594029/4b2b12b8-7bfb-11e6-9fc8-88800dbfc710.gif)

**Comment by xavijam** [comment]
Oh!, that's a good one, that is basically due to the fact those tiles are transparent and there is no solid background behind. When we change to an advance mode (sql or cartocss editors for example) we apply that dark mode, and looks like the reason. cc @matallo @alonsogarciapablo

**Comment by alonsogarciapablo** [comment]
Good catch @makella! I guess this is something we should change in cartodb.js... Should we set it to white?

**Comment by matallo** [comment]
uhm 🤔 shall we really manage this in carto.js? this is specific to the frame those tiles are, I'd apply this change in the builder CSS itself

**Comment by xavijam** [comment]
Yeah, it has to be managed in Carto.js @matallo, because how tiles/basemap layer is managed/styled/whatever should be defined there. Take into account if we decide to add the same dark frame in the embed page, the bug would appear due to we don't use anything from the Builder there, only Carto.js stuff.

**Comment by xavijam** [comment]
Issue moved to [CartoDB/cartodb.js #1424](https://github.com/CartoDB/cartodb.js/issues/1424) via [**ZenHub**](https://www.zenhub.com/)
