### ISSUE TITLE
"Enrich from Data Observatory" should be disabled for > 1000 rows

### ISSUE THREAD

**Issue by talos** [CartoDB/cartodb#9798]
Right now, it's way too easy for a naive user to attempt a very long running OBS query which will eat their entire quota.

With the current API, 1000 rows takes about 30 seconds.  While we have a 50x better solution coming down the pipeline, this is a real issue for users now.  Power users who know how to run batch queries can still use the API via SQL to augment more rows.

**Comment by javierarce** [comment]
@urbanphes: I'm not sure where it would make more sense to disable the analysis.

We could do it in the "Add a new analysis" window, but we would need to add an explanation somewhere (plus make an extra request to obtain the number of rows… which at that point would delay things a bit for the users).

On the other hand, if we want to disable it after the user chose the analysis (in the form), we'd need to figure out a good way to do it (I don't remember if we are doing something similar already).

cc: @xavijam @saleiva

**Comment by talos** [comment]
We're already doing a little look-see into the table to disable the option in "Add a new analysis" if the user's table contains lines.  Perhaps we already have access to the number of rows there?

Was just thinking of relatively quick ways to check whether a user table has over 1000 rows... probably `SELECT COUNT(*) FROM (SELECT cartodb_id FROM <usertable> LIMIT 1001) > 1000` would be faster than a naive `SELECT COUNT(*)` ?

**Comment by javierarce** [comment]
> We're already doing a little look-see into the table to disable the option in "Add a new analysis" if the user's table contains lines. Perhaps we already have access to the number of rows there?

Oh, true… and we change the description of the analysis with an explanation of why it's disabled. I had forgotten that :) 

> Was just thinking of relatively quick ways to check whether a user table has over 1000 rows... probably SELECT COUNT(*) FROM (SELECT cartodb_id FROM <usertable> LIMIT 1001) > 1000 would be faster than a naive SELECT COUNT(*) ?

👌  yes, that query will be perfect.

**Comment by urbanphes** [comment]
I totally agree with the idea to add on a description the reason that you can't make the analysis. We use the same position when an analysis can't be done because the geometry of layer.

**Comment by saleiva** [comment]
IMO we shouldn't disable the analysis. We should make more explicit the quota indication. that would also fix the problem but will be still possible to do DO operations on bigger datasets.

**Comment by talos** [comment]
@saleiva I agree with you for the future, but at the moment an analysis of over 1000 rows takes so long that it might time out, or the user might just give up on it.  Then, it still eats up their quota.

In the future, definitely we should let people run through their quota as much as they want, but with the speed limits we have right now this has already burned someone.

**Comment by saleiva** [comment]
But then is a different problem on how we set expectations and how we show progress IMO.

**Comment by saleiva** [comment]
Id be more explicit saying that this can take a while and improve the progress indicators...
