### ISSUE TITLE
Explanatory text for why an Analysis is disabled

### ISSUE THREAD

**Issue by talos** [CartoDB/cartodb#9799]
Thought of this with regards to https://github.com/CartoDB/cartodb/issues/9798.  Would be great to surface "This analysis is disabled since your table has more than 1000 rows."  Observatory Analysis is also disabled when the users' table has non point/poly geoms in it, and another message for that would be very informative.

As far as I know, there is no interface built to expose this sort of information.

**Comment by xavijam** [comment]
Yeah, that's a good one, cc @CartoDB/design team.

**Comment by saleiva** [comment]
@urbanphes this should be done together with the modal redesign, right?
