### ISSUE TITLE
Change copy "Published a few seconds ago" on layer view

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#9804]
Hi!

Whenever you publish changes, the message "Published a few seconds ago", creates two lines.   

<img width="340" alt="screen shot 2016-09-19 at 11 08 46" src="https://cloud.githubusercontent.com/assets/16247628/18627535/c16fe3ba-7e5b-11e6-83b7-48434e1fcf1e.png">

Can you change it to "Published seconds ago" to keep it in one line? 

<img width="340" alt="screen shot 2016-09-19 at 11 09 11" src="https://cloud.githubusercontent.com/assets/16247628/18627568/f783d434-7e5b-11e6-81f7-e20571b6f87b.png">

Thank you!

**Comment by xavijam** [comment]
That's a good one, we could add … at the end of the published text.

what do you think @MariaCheca=

**Comment by arianaescobar** [comment]
That too :)  although changing the literal to "Published seconds ago" fits the space correctly and that way we don't cut the message.

**Comment by MariaCheca** [comment]
Good one @arianaescobar :)

We could add those `...` in the end of the line or try to align the elements to the top, in that case the sentence "Updated a few seconds ago" would break the line but without taking the other buttons with it.
