### ISSUE TITLE
Incorrect email template when import fails without error_code

### ISSUE THREAD

**Issue by MariaCheca** [CartoDB/cartodb#9805]
When an import fails without error_code, the template rendered is the one for successful or partially successful (in cases when the user as uploaded more than one files), when it should be the warning one.

![screen shot 2016-09-19 at 11 44 24](https://cloud.githubusercontent.com/assets/2141690/18628038/8bbc14a2-7e5e-11e6-9d3a-28a79d04c5b6.png)

Thank you for reporting it @iriberri :*

**Comment by iriberri** [comment]
> (in cases when the user as uploaded more than one files)

I didn't tell, but I'm uploading a Shapefile with a single layer :)

**Comment by MariaCheca** [comment]
I supposed, that's why it shouldn't show that "x out of x were blahblah" :/

**Comment by iriberri** [comment]
Deploying the empty results fix!

**Comment by iriberri** [comment]
Deployed. Unless there is any other scenario which I haven't noticed, you should not receive empty results anymore. Anyway, I think it'd be good to check it just in case.
