### ISSUE TITLE
Some date columns get null values when converted from string to date

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#981]
[from jira: https://cartodb.atlassian.net/browse/CDB-3409]

In order to reproduce the error, use a CSV file called ONE_YEAR_OF_BEERS_-_Geodata and change the date column from string to date.

**Comment by rafatower** [comment]
The function involved in DB side: `cartodb.CDB_StringToDate`

**Comment by iriberri** [comment]
Example:

These dates don't get converted to date (they're nulled):

````
10/12/2007 0:00:00
8/07/2007 0:00:00
9/07/2006 0:00:00
25/10/2011 0:00:00
28/05/2013 0:00:00
4/08/2009 0:00:00
30/05/2006 0:00:00
23/02/2006 0:00:00
22/12/2012 0:00:00
26/10/2006 0:00:00
31/07/2012 0:00:00
24/05/2006 0:00:00
29/11/2010 0:00:00
14/02/2007 0:00:00
20/09/2012 0:00:00
24/03/2006 0:00:00
`````
But this does:
````
8/11/2012 0:00:00
````

**Comment by rafatower** [comment]
When not using iso dates (YYYY-MM-DD), there can be ambiguity in the format (is it MM/DD/YYYY or DD/MM/YYYY). So that 31/07/2012 might be considered invalid under the first assumption.

Tested again and got them correctly converted when compliant with MM/DD/YYYY for 1 <= MM <= 12

The conversion is ultimately done in postgres without extra information, which is good enough IMHO. I wouldn't consider a further improvement on that unless explicitly requested by a customer.
