### ISSUE TITLE
Importer results are not being propagated to DataImport in case of uncontrolled exception

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#9812]
https://github.com/CartoDB/cartodb/blob/e63431259cad23152007185a3eae4f87c5bfff81/app/models/data_import.rb#L713-L725

If an exception is raised here, `store_results` never occurs and the DataImport finishes with results = `[]`.

This is affecting the MailNotifier: https://github.com/CartoDB/cartodb/issues/9805

As the `importer` (and therefore its results) do only make sense inside the `execute_importer` method, we should rescue exceptions there to store the importer results and then raise the exception to continue with the normal behaviour.

**Comment by iriberri** [comment]
I'm not going through the `store_results` scenario because it might store false positives if the state of the importer wasn't set to false. I'll call `set_error` which will setup the default 99999 (missing until now) and build a results array out of this. Unfortunately, this won't provide the table name though, but will return a:

````
[<CartoDB::Importer2::Result @name=, @schema=, @extension=, @tables=, @success=false, @error_code=99999, @support_tables=, @original_name=>]
````

**Comment by MariaCheca** [comment]
Related to https://github.com/CartoDB/cartodb/issues/9805
