### ISSUE TITLE
Sidebar widgets not showing when adding them after a Time-Series one

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#9817]
OS: mac OS El Capitán 10.11.5
Browser in which this issue happens (**this doesn't happen on Safari Version 9.1.1**): 

- Chrome Version 53.0.2785.116 (64-bit)
- Firefox 47.0

CARTO Account used when this happened: arianaescobar

## Issue

From having no widgets added on a map, if I first add a Time-Series widget and then I try to add any other kind of widgets (the ones that go on the side), I do add them (they appear on my widgets list on the left sidebar) but the actual widgets don't appear on the right side. They only appear if I reload the window.  

![issue](https://cloud.githubusercontent.com/assets/16247628/18666652/48cdce7c-7f2d-11e6-8fd3-f82a37e5f8f8.gif)

Although if I first add a widget on the left sidebar and then I add a Time-series one, it will get added and shown on the builder perfectly.

![other way around](https://cloud.githubusercontent.com/assets/16247628/18666683/756ea4d8-7f2d-11e6-99a1-104ecc68b7be.gif)

## Expected behaviour

I should be able to see the widgets I add, not only on the widgets list but also the proper widgets in whichever order I decide to add them.

**Comment by xavijam** [comment]
Already reported @arianaescobar https://github.com/CartoDB/cartodb/issues/9694.

**Comment by arianaescobar** [comment]
Great 👍🏼  sorry for the duplicate!
