### ISSUE TITLE
Time bar not working in the map (just in Builder)

### ISSUE THREAD

**Issue by miguelginer** [CartoDB/cartodb#9825]
Hi:

I have created some maps (always animated, with widgets and time bar) where the time bar is not moving in the map (it works in builder):

Example:

https://team.carto.com/u/miguelginer/builder/5ffa1332-75a3-11e6-b6c7-0e98b61680bf/embed

**Comment by xavijam** [comment]
Could you check if everything works if you select a basemap without labels on top please?

**Comment by miguelginer** [comment]
Yes, I've changed the basemap and now it works...

**Comment by xavijam** [comment]
Ok, so it is due to the same as described here: 

https://github.com/CartoDB/cartodb/issues/9548

Thanks for the feedback @miguelginer.

cc @alonsogarciapablo
