### ISSUE TITLE
Login + logout link issues on a open-source setup

### ISSUE THREAD

**Issue by santisaez** [CartoDB/cartodb#9827]
Steps:

1) Login as `<% user %>` user
2) Logout, you will be redirected to `https://<% domain %>/user/<% user %>`
3) Click on "Login"
4) You will be redirected to `https://<% domain %>/user/<% user %>/login` and you will get a 404 error

**Comment by santisaez** [comment]
@xavijam can you manage this? thanks!

**Comment by xavijam** [comment]
It is related with the backend redirection after logout, I feel, could you check it please @javitonino?

**Comment by javitonino** [comment]
The URL itself makes some sense (for organization login/signup in subdomainless). That URL used to work but was removed in #5885. I'm taking a look at making this work in subdomainless, so we can have org signup there.

**Comment by santisaez** [comment]
Re-opening this issues until we make sure it's fixed.

**Comment by santisaez** [comment]
Fixed:

1) Login as `<% user %>`, you will be redirected to `https://<% domain %>/user/<% user %>/dashboard/`
2) Logout, you will be redirected to `https://<% domain %>/user/<% user %>`
3) Click on "Login" again => `https://<% domain %>/user/<% user %>/login`.

Now, both `/login` and `/user/<% user %>/login` URLs works for the login process :)

Thanks @javitonino!
