### ISSUE TITLE
Username auto fill in shared datasets within an org

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb#9829]
When opening a shared dataset within an org, the dataset owner name is not prefixed to the dataset name, so the dataset view does not work.

The query is like 

```sql
SELECT * FROM dataset
```

Instead of

```sql
SELECT * FROM owner.dataset
```
 It's working ok when using the dataset on a map.

cc @jsanz

**Comment by AbelVM** [comment]
Edited

**Comment by jsanz** [comment]
Just to be clear, this is only on the dataset view, maps work super.

**Comment by xavijam** [comment]
Yeah, we are aware of the issue, already reported [here](https://github.com/CartoDB/cartodb/issues/9779). We need to discuss how to manage the problem, thanks for the feedback guys! 💋 
cc @juanignaciosl @gfiorav @nobuti

**Comment by jsanz** [comment]
If it's already reported let's close this one
