### ISSUE TITLE
Remove content character from :after

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#9833]
![screen shot 2016-09-21 at 13 16 46](https://cloud.githubusercontent.com/assets/132146/18708938/bb619204-7ffd-11e6-881a-890c66ac51cb.png)

😂  please.

cc @piensaenpixel @MariaCheca

**Comment by MariaCheca** [comment]
Issue moved to [CartoDB/CartoAssets #148](https://github.com/CartoDB/CartoAssets/issues/148) via [**ZenHub**](https://www.zenhub.com/)
