### ISSUE TITLE
Update internal Connectors support

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/cartodb#9834]
First we need to upgrade the Connector backend with new functionality for listing tables, per-user configuration and some bug fixes:

- [x] re-review and deploy #9748 
- [x] PR & review branches [tmp_connector_config_migration](https://github.com/CartoDB/cartodb/tree/tmp_connector_config_migration) and [tmp_connector_config](https://github.com/CartoDB/cartodb/tree/tmp_connector_config)
- [x] deploy migration
- [x] deploy config, execute `rake cartodb:connectors:create_providers`

Default connectors configuration should now be added to `app_config.yml` via chef.

Then the UI should be updated to handle the new `:max_rows_per_connection` warnings.
Similarly to what is done for `:max_tables_per_impor` in:
* assets/javascripts/cartodb/common/views/partial_import_details.jst.ejs
* assets/javascripts/cartodb/common/views/warnings_details_view.js
* assets/javascripts/cartodb/components/background-importer/views/warnings-details-view.js

**Comment by ethervoid** [comment]
- [ ] Frontend integration #9862 (in testing process)
