### ISSUE TITLE
Add missing FK legends.layer_id -> layers

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#9835]
cc/ @juanignaciosl @javitonino

**Comment by javitonino** [comment]
Catching up, Why wasn't this added when creating the legends table?

**Comment by gfiorav** [comment]
Because we're extremely coward 😁

**Comment by juanignaciosl** [comment]
Closing automatically because of inactivity. If anybody considers that this still important, please reopen and it'll be prioritized.
