### ISSUE TITLE
Duplicated logs when trying to instantiate a data import invalid logger

### ISSUE THREAD

**Issue by luisbosque** [CartoDB/cartodb#9848]
When you try to instantiate a logger from the data import, if the logger value is not a UUID rails will create a new empty log with the data import user id. 
It won't rewrite the logger value of the data import with the new log id though.

**Comment by juanignaciosl** [comment]
This is the wrong method: https://github.com/CartoDB/cartodb/blob/master/app/models/data_import.rb#L439

It not only creates a new log entry but also it doesn't link the data import to it through the FK, so every instantiation of that DataImport will lead to a new line.

STR:
- Alter an existing `data_imports.logger`, setting a non-uuid value.
- Fetch the `DataImport` at the Rails console. Every instantiation will trigger an insert.

cc @javitonino

**Comment by juanignaciosl** [comment]
PS: this only involves OLD data imports. @luisbosque, maybe we could just avoid the creation and nullify `data_imports.logger` for non-uuids, what do you think?

**Comment by juanignaciosl** [comment]
No, the ORM can deal with null values without problem. The problem is having ids that don't match any existing row, as it assumes that if there's an id the associated entry must exist.
