### ISSUE TITLE
Simple styling does not applied after setting squares or other aggregation

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#9851]
### STR

* Create a map with a points dataset.
* Set style by `squares` aggregation.
* Go back to `none` aggregation. As shown in the screenshot below, the change is not applied. The `marker-width` parameter (a number) is not shown.

![bug](https://cloud.githubusercontent.com/assets/5215798/18749709/68e93a50-80d8-11e6-961f-660cb6364f46.png)

**Comment by ramiroaznar** [comment]
Maybe it is related to this issue https://github.com/CartoDB/cartodb/issues/9420

**Comment by xavijam** [comment]
Fix here: https://github.com/CartoDB/cartodb/pull/9843/commits/b9fa47942dda5143dcc519f445800102dc977f51

**Comment by xavijam** [comment]
No, it is not related with the other thing, that is related with auto-style code :(.

**Comment by ramiroaznar** [comment]
@xavijam so it is not fixed, right? should we open it again?

@CartoDB/support for awareness

**Comment by xavijam** [comment]
The problem you have just reported is fixed in https://github.com/CartoDB/cartodb/pull/9843/commits/b9fa47942dda5143dcc519f445800102dc977f51. About the other problem is reported in https://github.com/CartoDB/cartodb/issues/9420.
