### ISSUE TITLE
Don't let polygon datasets to be exported as CSV

### ISSUE THREAD

**Issue by michellechandra** [CartoDB/cartodb#9855]
## Context

When using the CARTO Builder and creating an AOI analysis layer, exporting that layer returns a dataset of points rather than polygon data.
## STR

Create a CARTO Builder map with an area of influence layer.

In the layer panel, select the AOI node layer and choose to "export data".
![marketinganalysis](https://cloud.githubusercontent.com/assets/5423288/18767690/8ea1da84-80d5-11e6-944a-5d0f7574eb16.png)

Import the layer to CARTO and it will show points when viewed in the Builder or Editor rather than polygons. Data itself shows it is polygon data but renders as points.
![screen shot 2016-09-22 at 15 04 50](https://cloud.githubusercontent.com/assets/5423288/18767838/5c012368-80d6-11e6-8d8c-245236924fad.png)

![screen shot 2016-09-22 at 15 04 57](https://cloud.githubusercontent.com/assets/5423288/18767841/5f99f46e-80d6-11e6-9549-e5bc8c7ad8ff.png)

Map in my "chandra" team account is called "Marketing Analysis Demo": https://team.carto.com/u/chandra/viz/24f951c6-980a-44ff-91f8-35ffafeb3ae2/map

Exported dataset re-imported to my "chandra" CARTO is called Station Areas: https://team.carto.com/u/chandra/tables/stationareas

S/B: 10014082

cc @CartoDB/support for awareness

**Comment by saleiva** [comment]
Updating the name of the issue. Like in the editor, we shouldn't let export polygon/line datasets to csv files

**Comment by csobier** [comment]
+1 @xavijam , I'm still able to export a polygon dataset using .csv, regardless of whether of not an analysis is applied.

**Comment by saleiva** [comment]
@noguerol cc

**Comment by ztephm** [comment]
S/B 14142227
