### ISSUE TITLE
CARTO map sharing

### ISSUE THREAD

**Issue by icetorm** [CartoDB/cartodb#9858]
Hi everyone,
I got CARTO builded in my server, and it works smoothly. Now im focus on sharing maps and it's giving me plenty of issues. First of all , to share a map with another user, datasets has to been set as public privacy, and is not of my pleasure because i got important data that need to be kept as private. However, my  priority is that need to emb a map on joomla, but when i insert the code it don't work, i only achieve to get the basemap, the layers doesn't show.

Any ideas?

**Comment by xavijam** [comment]
Hi there!
I encourage you to post your doubts about open-source install in https://groups.google.com/forum/#!forum/cartodb, we will help you there.
