### ISSUE TITLE
Analysis window won't scroll in Firefox

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#9859]
### STR

Issue discovered during this training https://github.com/CartoDB/solutions/issues/540#issuecomment-248969728

* Open CARTO in Mozilla Firefox (`v48.0`).
* Add an analysis to a layer
* Scrolling does not work in the "Add a new analysis" modal.

cc @CartoDB/support for awareness

**Comment by xavijam** [comment]
Already tested, true that, take a look when possible @piensaenpixel :Kiss:.
