### ISSUE TITLE
Widgets should reload when changing columns

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#9860]
OS: mac OS El Capitán 10.11.5
Browser: 
- Chrome Version 52.0.2743.116 (64-bit)
- Safari Version 9.0 (11601.1.56)

CARTO Account used when this happened: arianaescobar
## Issue

When I change between columns in a Category widget, the widget keeps the value range of the first column. 

![widget](https://cloud.githubusercontent.com/assets/16247628/18784036/ae36d7e0-818f-11e6-8236-531f1141ea8c.gif)
### Steps

I created a Category widget from the cartodb_id column of [this dataset](https://team.carto.com/u/noguerol/dataset/table_50k_global_customer_value). On the edit options of that widget, I changed the column to the customer_v column. The widget kept the same value range. 

When I switch to another widget and came back to the category one, the widget obviously reloaded and the value range was updated to fit the values of the customer_v column.
## Expected behaviour

The widget should reload whenever the column it's changed to update the value range.

**Comment by ramiroaznar** [comment]
I was not able to replicate the issue. It looks like it is fixed. Please @arianaescobar reopen it if needed.
