### ISSUE TITLE
The public page of the datasets has the old style and it's showing Disqus ads

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#9861]
(Sorry if this is a duplicate, couldn't find any issue about it) 

In the public page of a dataset, [this one for example](https://team.carto.com/u/arianaescobar/tables/twitter_theforceawakens/public), there's still elements of the old website style, like buttons, colors, fonts, or the old footer.

Also, Disqus is displaying it's ads. 

![screen shot 2016-09-23 at 13 29 55](https://cloud.githubusercontent.com/assets/16247628/18784354/dc15cc96-8191-11e6-87ad-7b833a44efac.png)

**Comment by vuxita** [comment]
@ariana, it is a duplicate, already opened it here https://github.com/CartoDB/cartodb-central/issues/1497

**Comment by arianaescobar** [comment]
@vuxita @xavijam ok! Although that issue it's only related to disqus and not the old website style on that page.

**Comment by xavijam** [comment]
Of course it has the old style, we haven't thought about public pages. It's coming!.

**Comment by arianaescobar** [comment]
ok ok! 😶
