### ISSUE TITLE
Table view shows no data after applying an analysis

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#9863]
### STR
- Add an analysis to a layer
- After applying the analysis, click on "Table view".
- It looks like that `There is no data`, but when you go back to the main menu and click again to the layer, and select "Table view" the data will display correctly.

**Comment by saleiva** [comment]
Checked, this doesnt happen always. Can you doble check @ramiroaznar ?

**Comment by ramiroaznar** [comment]
I have replicated the steps using the "Risk Analysis Demo" [script](https://gist.github.com/ramiroaznar/fe040984ac788bbedf07bec6c75c5bfc). And this happens when applying `Intersect with 2nd layer` and `Detect outliers and clusters`.

**Comment by ramiroaznar** [comment]
So far I could replicate this behaviour with the following analysis:
* `Intersect with 2nd layer`
* `Detect outliers and clusters`
* `Calculate clusters of points`

**Comment by noguerol** [comment]
Also after clustering and applying Moran's I.

**Comment by saleiva** [comment]
Happening to me also after doing an Enrich Analysis

**Comment by ohasselblad** [comment]
Same thing for me with Enrich from data observatory

**Comment by ramiroaznar** [comment]
Hey @xavijam @javisantana, so this should be in the new smoke tests.

**Comment by saleiva** [comment]
This seems to be fixed
