### ISSUE TITLE
Export map selecting layers modal

### ISSUE THREAD

**Issue by MariaCheca** [CartoDB/cartodb#9867]
Change export map modal to let choose the datasets to export.

![screen shot 2016-09-23 at 17 35 34](https://cloud.githubusercontent.com/assets/2141690/18791816/7933e8ce-81b4-11e6-9bc4-af25a36f9874.png)

cc @xavijam

**Comment by saleiva** [comment]
IMO, we should not prioritize this one, since as a workaround you can always unzip the file, and delete the data there.

Also this design is an old one.

**Comment by saleiva** [comment]
cc/ @xavijam
