### ISSUE TITLE
Pagination overlay in dataset view not showing correct numbers after deleting a row

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#9868]
**STR**:
- Go into a dataset (more than 40 rows, please!)
- Delete a row
- Now the pagination overlay only shows up to 39, instead of loading for the whole table, and doesn't allow to navigate to the next page

**Before:**
![image](https://cloud.githubusercontent.com/assets/1730320/18792378/93d0d640-81b6-11e6-85fe-d086c5c55ec8.png)

**After:** 

![image](https://cloud.githubusercontent.com/assets/1730320/18792421/c117ff3e-81b6-11e6-8c5c-5c7333226244.png)

**Comment by Jesus89** [comment]
Closed by https://github.com/CartoDB/cartodb/pull/14139

In production! :rocket:
