### ISSUE TITLE
Autostyle color picker on widgets options

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#9872]
@saleiva commented on [Thu Sep 01 2016](https://github.com/CartoDB/design/issues/176)

We had this originally, we removed, but is a common request now...

---

@arianaescobar commented on [Wed Sep 14 2016](https://github.com/CartoDB/design/issues/176#issuecomment-247079486)

Here's the UI proposal for this: https://invis.io/7D8LN1VEQ @urbanphes @saleiva 

The idea is to allow the users to specify which particular colors or color ramp they want to see when applying the widget autostyle from that particular widget settings.  

---

@urbanphes commented on [Thu Sep 15 2016](https://github.com/CartoDB/design/issues/176#issuecomment-247275741)

I think is good approach. 

---

@saleiva commented on [Mon Sep 26 2016](https://github.com/CartoDB/design/issues/176#issuecomment-249532460)

Love it, close and promote, please!
# SMOKE_WD16

**Comment by saleiva** [comment]
This is blocking some very interesting use cases on tools for location analysis on cities with some clients. cc/ @mbforr @zingbot
