### ISSUE TITLE
It's difficult to identify columns with long column names in the dataset view

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#9880]
In the Editor, as we had horizontal scroll in the Dataset View, column names were rendered totally even if long:

![image](https://cloud.githubusercontent.com/assets/1730320/18841797/25b86538-8413-11e6-85bf-c0d1c8efe96e.png)

In the Builder, long column names get trimmed (with no alt message):

![image](https://cloud.githubusercontent.com/assets/1730320/18842023/f7c4064a-8413-11e6-8e67-d43122da452a.png)

and it looks like if you click over them, they "expand", but the name is still not visible:

![image](https://cloud.githubusercontent.com/assets/1730320/18842033/03a47c6a-8414-11e6-8110-9c8f846eb0cb.png)

I noticed about this while working with @talos in the Data Observatory use case, where columns usually have long names so the navigation could be a bit difficult.

**Comment by talos** [comment]
We definitely (for accessibility if nothing else) should have `alt` declared for those headers.

I'd also be inclined to be a bit more aggressive showing longer names -- maybe making the font a little smaller, and wrapping lines.  Maybe not for everything all the time, but at the least when the user has clicked and gone out of their way to try to view the whole header.

Outside of the DO, it's pretty common to bring in spreadsheets or other datasets that have pretty long column names.  We should make life as easy as possible for those people. :)

**Comment by xavijam** [comment]
For the moment I'll add the "alt" to those components, but it is a good idea to have the possibility to expand the text doing any action, cc @CartoDB/design.

**Comment by saleiva** [comment]
alt is enough for the time being.

**Comment by talos** [comment]
Cool @saleiva should we file a new ticket to capture expanding the column separately from adding `alt`?

**Comment by xavijam** [comment]
Please @MariaCheca, add the alt to the name of the columns.

**Comment by MariaCheca** [comment]
👍
