### ISSUE TITLE
Scrolling menus that extend beyond the bottom of a window in the builder layer panel

### ISSUE THREAD

**Issue by mbforr** [CartoDB/cartodb#9883]
In a number of different views in the Builder layer panel, the menu will extend beyond the bottom of the div so you cannot access all the options.
![screen shot 2016-09-26 at 2 59 24 pm](https://cloud.githubusercontent.com/assets/4828460/18847913/09b9776e-83fa-11e6-8d53-595936da81ba.png)

**Comment by xavijam** [comment]
Yeah, totally agree, we have discussed about that and we are planing to move those "sub" menus on top of the action instead of having them below. Let me close this one because it is duplicated several times (cleaning tickets time!).
