### ISSUE TITLE
Add an option to add opacity to choropleth maps in the UI

### ISSUE THREAD

**Issue by mbforr** [CartoDB/cartodb#9884]
Currently, apart from CartoCSS, there is no way to add an opacity to a map that has a choropleth styling option.

![screen shot 2016-09-26 at 3 01 36 pm](https://cloud.githubusercontent.com/assets/4828460/18847978/436cfaee-83fa-11e6-96a8-54d050039451.png)

**Comment by xavijam** [comment]
That's a difficult one, not sure how we could manage it, moving to design.

**Comment by xavijam** [comment]
Issue moved to [CartoDB/design #241](https://github.com/CartoDB/design/issues/241) via [**ZenHub**](https://www.zenhub.com/)

**Comment by urbanphes** [comment]
Related to https://github.com/CartoDB/design/issues/241

**Comment by saleiva** [comment]
Design is done.

**Comment by xavijam** [comment]
@javierarce, please, take care of it ❤️ .

**Comment by saleiva** [comment]
Id say its not a priority BTW, so if its not easy, Id focus on bugfixing until we release

**Comment by xavijam** [comment]
Duplicated -> https://github.com/CartoDB/cartodb/issues/8142
