### ISSUE TITLE
Cannot connect two datasets with lines

### ISSUE THREAD

**Issue by mbforr** [CartoDB/cartodb#9886]
In the connect with lines analysis there is no way to connect two different datasets with lines based on a common shared value. Tried doing this with a joined data set analysis and it also did not work. Had this use case pop up a few times. cc: @cartodave

**Comment by saleiva** [comment]
You should be able to do it 

![screen shot 2016-09-28 at 16 50 43](https://cloud.githubusercontent.com/assets/132149/18918638/c03edec8-859b-11e6-91cd-0a8faa179315.png)

**Comment by mbforr** [comment]
I tried that but it connected every point to another point. Lets say I wanted to connect Table A (10K values) to Table B (100 values) based on a shared column (Place_ID) would I have to plug in Source Column and Target Column as 'Place_ID'?

**Comment by saleiva** [comment]
yep, exactly.

**Comment by xavijam** [comment]
Closing since it is possible, thanks for all your feedback and questions Matt! :)
