### ISSUE TITLE
Dissolved AOI analyses don't stack up properly

### ISSUE THREAD

**Issue by mbforr** [CartoDB/cartodb#9887]
When using dissolved AOIs the smallest area only appears on top of the rest about 50% of the time. Below is an example of where this is taking place:

https://team.carto.com/u/mforrest/builder/bd65a69c-4a8f-11e6-8e5d-0ecd1babdde5/embed

**Comment by xavijam** [comment]
Hey mbforr, that analysis doesn't have dissolved enabled...

**Comment by mbforr** [comment]
Yes I was playing with that last week in a demo. Here is the original.

https://team.carto.com/u/mforrest/builder/bd65a69c-4a8f-11e6-8e5d-0ecd1babdde5/embed

**Comment by saleiva** [comment]
Fixed!
