### ISSUE TITLE
Support .TAB in the importer

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#989]
This was a request from an XS user and is a quick win hopefully. Support the .tab extension and knowingly use the \t delimeter

https://cartodb.atlassian.net/browse/CDB-3219

**Comment by ztephm** [comment]
ref s/b 6437022

User is trying to sync .gz that is a zipped .tab file. FYI saving as .tsv (unzipped) imports from local.

**Comment by ethervoid** [comment]
I think we should not include .tab extension for this because there is a GIS format .tab https://en.wikipedia.org/wiki/MapInfo_TAB_format.
