### ISSUE TITLE
Filter range is not well exposed in the time widget

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#9895]
![screen shot 2016-09-27 at 12 08 31](https://cloud.githubusercontent.com/assets/132149/18869116/2d3d4a74-84ab-11e6-8a13-864e52308b21.png)

Look at those billions instead of timestamps

**Comment by saleiva** [comment]
Also the clear button doesnt show up.-

**Comment by xavijam** [comment]
I'll take care of it
