### ISSUE TITLE
Error 500 page has the old brand

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#9897]
![screen shot 2016-09-27 at 12 19 16](https://cloud.githubusercontent.com/assets/132149/18869440/a7a180a4-84ac-11e6-8323-364291f87cc6.png)

cc/ @xavijam

**Comment by xavijam** [comment]
😱

**Comment by xavijam** [comment]
@MariaCheca :)

**Comment by MariaCheca** [comment]
Hi, that template is not present anymore in the project, could it be from one of our external services?

**Comment by MariaCheca** [comment]
Issue moved to [CartoDB/cartodb-platform #2480](https://github.com/CartoDB/cartodb-platform/issues/2480) via [**ZenHub**](https://www.zenhub.com/)
