### ISSUE TITLE
UNIX timestamps converted to a date column loses time

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#990]
see https://github.com/CartoDB/cartodb/issues/290#event-131175854

https://cartodb.atlassian.net/browse/CDB-3224

**Comment by iriberri** [comment]
up.

**Comment by rafatower** [comment]
Just testing, this patch from Lorenzo fixes the issue: 26a3936b05f35e9dccd8111f3596a7069687d5cd but the right implementation is in the cartodb extension.

**Comment by javisantana** [comment]
you mean we need to release a new version of the extension? :D

**Comment by rafatower** [comment]
we *should* release a new version of the extension, but it is not required :p

**Comment by rafatower** [comment]
Fixed in cdb extension and waiting for deployment.
