### ISSUE TITLE
Issue with the category widget

### ISSUE THREAD

**Issue by mbforr** [CartoDB/cartodb#9901]
Running into an issue with a category widget tied to a string. It shows that over 90% of the values are "*" but there are not items with that value.

https://youtu.be/1E7UJaZq98k

**Comment by xavijam** [comment]
Moving to deep-insights, it is a bit weird but @matallo and I will take a look before promoting to the API.

**Comment by xavijam** [comment]
Issue moved to [CartoDB/deep-insights.js #450](https://github.com/CartoDB/deep-insights.js/issues/450) via [**ZenHub**](https://www.zenhub.com/)
