### ISSUE TITLE
"Publish" tab offer links to the raw version, not to the published one

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb#9907]
So you can't access the vis.json of the published version of your dashboard.

Same issue with .carto export: you get the version in the builder, not the published one.

cc @gfiorav

**Comment by xavijam** [comment]
viz.json option is gonna be removed as you know, so closing this one -> https://github.com/CartoDB/cartodb/issues/9750

**Comment by AbelVM** [comment]
What about the .carto file?
