### ISSUE TITLE
Access Style tab in one click

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#9922]
Design issue: https://github.com/CartoDB/design/issues/106
InVision: https://invis.io/FE8R959P2#/188897866_Layers_01

Hi! We wan't to improve the UX of the layer view by giving a way of accessing the style tab of each layer in one click. In order to do that we propose adding an icon on the layer that will take you there. It will replace the hide/show layer icon and that action will be moved to the dropdown settings of the layer.

That way we'll prioritise styling and we won't overcrowd each layer with too many icons.

For the style icon we'll use the slider icon we've been using on the blue sidebar and for the sidebar we'll use the generic share icon instead. 

![97b89806-84c7-11e6-95a8-56a168f125fc](https://cloud.githubusercontent.com/assets/16247628/18910689/6a508b96-8579-11e6-8234-a6b8982af1d7.png)

Let me know if there's any question :) 
& thanksss!

**Comment by xavijam** [comment]
IMHO I would not remove the visibility icon, because it could be a bit confusing displaying a layer with opacity but not having any clue why it is in that state...

**Comment by arianaescobar** [comment]
Personally, I don't think that it will be a problem... but we can try it and see, with time, if it's too confusing and do something about it, like a tiny tag that says "Hidden layer" or something like that.

**Comment by xavijam** [comment]
Whatever you decide is fine 😄 , but that is my opinion. If you want we can try and then decide :kiss:.

**Comment by arianaescobar** [comment]
Sounds good 🙂
