### ISSUE TITLE
Cannot delete sync from dataset view

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#9927]
Using the new dataset view from the builder, if you try to delete a synchronization (set interval to "never") it sets the interval to 0 instead of deleting it.

 1. Create a sync table (e.g: import from the data library)
 2. Open in the builder's dataset view
 3. In the sync bar, select "View options", select "Never" and save

Expected behaviour: DELETE to synchronizations endpoint (same as editor).
Actual behaviour: PUT to synchronizations endpoint setting interval to 0. The dataset still shows as synced in the dashboard, and actually syncs from time to time.

**Comment by xavijam** [comment]
👍
