### ISSUE TITLE
Layer selector should be deactivated by default

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#9929]

**Comment by nobuti** [comment]
Do you mean in the map options?

**Comment by saleiva** [comment]
yes, so if there is no legends, the box doesnt appear.

**Comment by nobuti** [comment]
So both options legends and layer selector should appear and respond independently, right? We talked about this [here](https://github.com/CartoDB/cartodb/pull/9911) and as you can see in the screengif, in the first place we had both, but at the end, we left only one option. I'll recover the two options there.

**Comment by saleiva** [comment]
no no
wait wait

Ill call you

**Comment by gfiorav** [comment]
@nobuti I'm setting the layer selector embed option to false by default FYI

**Comment by xavijam** [comment]
Thanks @gfiorav 🤗
