### ISSUE TITLE
Cannot edit datasets write-shared with the organization

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#9933]
STR
1. Create a dataset
2. Share with write permissions with the whole organization (but not with any user)
3. Open the dataset with any other user, it cannot edit the dataset

What happens is that in `dataset-content-view`, the following returns false:
`var hasWriteAccess = permissionModel.isOwner(this._userModel) || permissionModel.hasWriteAccess(this._userModel);` if the user doesn't have explicit permissions.

cc @xavijam 

P.S: Check that you can edit cells, but also that you can add rows/columns, as it seems the permissions are not exactly the same.

**Comment by saleiva** [comment]
Is this still happening?

**Comment by javitonino** [comment]
Yes, it is.

**Comment by juanignaciosl** [comment]
@xavijam consider prioritizing this (I guess that this was forgotten).

**Comment by xavijam** [comment]
:+1:

**Comment by juanignaciosl** [comment]
I just stumbled upon this while testing #12089.

This snippet is likely to be redundant but, FYI, here's the loaded permission JSON (C&P from the page source):

```
\"permission\":{... \"acl\":[{\"type\":\"org\",\"entity\":{\"id\":\"c1e14432-eed5-4b2f-a7e1-ac89e2da2151\",\"name\":\"team\",\"avatar_url\":\"https://s3.amazonaws.com/com.cartodb.users-assets.production/production/cartofante/assets/20160711085940nYDKmRx1.jpg\"},\"access\":\"rw\"}]
```

**Comment by xavijam** [comment]
Hey, it was already fixed by @matallo in https://github.com/CartoDB/cartodb/pull/12393.

**Comment by matallo** [comment]
BOOM
