### ISSUE TITLE
Problem with URL icon in user public profiles

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#9934]
- Google Chrome Version 55.0.2868.3 dev (64-bit)
- Browser size 1276 x 703 (doesn't happen with responsive design for smaller windows sizes)
- OS X 10.10.5

The URL icon looks like split by half and it gets rendered two times, on its place and below the whole description: 

![image](https://cloud.githubusercontent.com/assets/1730320/18919539/deffdb02-859e-11e6-9442-24f50327a0fc.png)

**STR**:
- Check https://team.carto.com/u/javi/me

**Comment by ivanmalagon** [comment]
Fixed.
