### ISSUE TITLE
Quota consumed due to analyses applied

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#9940]
I'm wondering what we should do (or not) when a user consumes all its quota when it has applied several "hard" analyses that consumes all the user quota. Should we show any info? Should we just warn the user that quota is (table data + analyses applied)? Shouldn't we anything for the moment?. Just opening this for discussion, if it is not prior, let's close it.

cc @rochoa @javisantana @saleiva

**Comment by saleiva** [comment]
There are some things that I think we should do as the min.
- Delete analysis tables when deleting the original dataset.
- Analysis layers shouldnt count.

**Comment by alrocar** [comment]
Stale issue. Closing 👋
