### ISSUE TITLE
Add node/analysis reference to widgets

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#9956]
@urbanphes commented on [Thu Sep 29 2016](https://github.com/CartoDB/design/issues/248)

Now in widgets we don't have any reference to know which is the layer or step. 

![image](https://cloud.githubusercontent.com/assets/14546701/18950036/39c2e8aa-863e-11e6-97b5-215d81b82a24.png)

And when we add a widget on the dropdown selected this kind of parameters don't appears when add the widget in a right bar.

![image](https://cloud.githubusercontent.com/assets/14546701/18950063/4fb06f66-863e-11e6-8364-740a68cd4019.png)

The idea is to have this parameters on the widgets sidebar.

---

@arianaescobar commented on [Thu Sep 29 2016](https://github.com/CartoDB/design/issues/248#issuecomment-250449312)

Reference to the node (Builder view)

![03 widgets - 01-00 histogram](https://cloud.githubusercontent.com/assets/16247628/18953442/c955d58a-864e-11e6-9a16-ed4b65064314.png)

Reference to an analysis (Builder view)

![03 widgets - 01-00 histogram copy](https://cloud.githubusercontent.com/assets/16247628/18953443/c95dd0b4-864e-11e6-8e59-85030b0fc4d7.png)

No reference (Embed)

![03 widgets - 01-00 histogram copy 2](https://cloud.githubusercontent.com/assets/16247628/18953449/ceaa0146-864e-11e6-8597-31333b602a48.png)

---

@saleiva commented on [Thu Sep 29 2016](https://github.com/CartoDB/design/issues/248#issuecomment-250477086)

Close, promote, and assign to @piensaenpixel :)

**Comment by saleiva** [comment]
Prioritizing this, having lots of feedback. We should get this for the first bathc.

**Comment by xavijam** [comment]
CARTO.js and DI.js don't know about layer colors cc @alonsogarciapablo. But we could do it from now on and add the info, what do you think @alonsogarciapablo @donflopez?

**Comment by alonsogarciapablo** [comment]
Yes... widgets could have a `source_color` attr or something along those lines...

**Comment by xavijam** [comment]
Widgets or layers? I would not pass the color to the widgets due to it is not related to them.

**Comment by alonsogarciapablo** [comment]
Yes, you're right @xavijam. It makes more sense to associate colors with the analysis node... The only problem is that we don't have analysis nodes in DI.js/CARTO.js....

**Comment by xavijam** [comment]
Nodes don't know anything about color either, we should "propagate" that to the layer-model, not to any other thing, IMHO.

**Comment by piensaenpixel** [comment]
@xavijam when we'll have the color thing ready please assign it to me :)

**Comment by xavijam** [comment]
Deployed thanks to @matallo
