### ISSUE TITLE
Manage cartodb_georef_status column from geocoder UI

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#996]
[from jira: https://cartodb.atlassian.net/browse/CDB-4114]

Right now, when a user geocodes the data, the cartodb_georef_status column appears.

The thing is that this boolean column is avoiding further geocodings unless the user deletes it (and this is not documented or explained anywhere).

Suggestion:
When a table has this column, and the user clicks in GEO again.

1. (If one or more rows are 'true'). Two cases:
You already have georeferenced data. Do you want to overwrite it? -> Delete all column.
Do you want JUST to change the 'null' and 'false' values? -> Set null and false rows to null, maintain true values.

2. (If all rows are 'false'): Delete column without asking.

3. (If all rows are 'true'): Do you want to geocode all your data again? -> Delete entire column.

**Comment by iriberri** [comment]
Closing, right? ;) Our UI already does this.

**Comment by rafatower** [comment]
right
