### ISSUE TITLE
HTML code of the infowindow image header is not displaying the activated fields

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartodb#9964]
The HTML code of the image header infowindow option, is not showing the activated fields of the interface menu.

Steps:

* Select the fields of the dataset that you want to display in the image header infowindow:

![screen shot 2016-09-30 at 13 12 36](https://cloud.githubusercontent.com/assets/11177693/18990196/a9603c1c-8710-11e6-8c4b-beec0456f8f5.png)

* Click in the HTML button, the infowindow HTML code is not showing the activated fields or the correct code:

![screen shot 2016-09-30 at 13 12 44](https://cloud.githubusercontent.com/assets/11177693/18990227/cb7cdfda-8710-11e6-849b-bb0c40fd9652.png)

If we do the same operation with selecting the `light` infowindow template, the fields are displayed in the HTML code:

![screen shot 2016-09-30 at 13 13 09](https://cloud.githubusercontent.com/assets/11177693/18990281/237576c0-8711-11e6-8371-402284635e78.png)

**Comment by xavijam** [comment]
Only happening with the image type or with the colored header too?

**Comment by matallo** [comment]
this is working as expected, needs to be implemented the option in the fields to select the header image and the title

- first field is the image
- second field is the title
- third field and on are the fields in the popup content

closing then
