### ISSUE TITLE
Error granting SELECT to tiler user

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/cartodb#9966]
I've spotted this exception

```
PG::Error: ERROR: syntax error at or near ".2016"
LINE 1: GRANT SELECT ON public.2016damagestest TO tileuser;
```

Error comes from [here](https://github.com/CartoDB/cartodb/blob/master/app/models/table.rb#L479)

I looks like comes from `Ghost tables: Error creating UserTable`

// @CartoDB/backend

**Comment by javitonino** [comment]
Most likely, we need to escape table names that start by anything other than `[a-zA-Z_]`

From [the docs](https://www.postgresql.org/docs/9.5/static/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS):

> SQL identifiers and key words must begin with a letter (a-z, but also letters with diacritical marks and non-Latin letters) or an underscore (_). Subsequent characters in an identifier or key word can be letters, underscores, digits (0-9), or dollar signs ($). Note that dollar signs are not allowed in identifiers according to the letter of the SQL standard, so their use might render applications less portable. The SQL standard will not define a key word that contains digits or starts or ends with an underscore, so identifiers of this form are safe against possible conflict with future extensions of the standard.

**Comment by gfiorav** [comment]
We've been here before!

The docs say (a bit further down):

> There is a second kind of identifier: the delimited identifier or quoted identifier. It is formed by enclosing an arbitrary sequence of characters in double-quotes (")

But table names are in the first category I think. I'm just pointing out this is the reason we might have (wrongly) accepted such table names.

**Comment by ethervoid** [comment]
Or escape always to avoid this kind of problems, IIRC there is no drawback escaping the name of the table always 

```
cartodb_dev_user_23c39318-a446-4c62-ab2c-32e78757ba19_db=# CREATE TABLE 2016distributors (did integer, name varchar(40) UNIQUE);
ERROR:  42601: syntax error at or near "2016"
LINE 1: CREATE TABLE 2016distributors (did integer, name varchar(40)...
                     ^
LOCATION:  scanner_yyerror, scan.l:1081
Time: 0.319 ms
cartodb_dev_user_23c39318-a446-4c62-ab2c-32e78757ba19_db=# CREATE TABLE "2016distributors" (did integer, name varchar(40) UNIQUE);
CREATE TABLE
Time: 5.017 ms
```

**Comment by javitonino** [comment]
We used to fail when trying to add a table created via SQL api that had any special characters. @juanignaciosl recently made some progress, both backend and frontend to support this, and now we support tables, e.g: with dashes in the name. 

The reason we don't want to escape always is that queries presented to the user look clunky with the quoting, and it isn't needed in all tables that can be created from the dashboard/importer. It just affects SQL API tables.

Anyway, we should escape this in [table_utils](https://github.com/CartoDB/cartodb/blob/38b3647a82281154628cf31555e68601cc95cb32/lib/carto/table_utils.rb#L22) but we have to double check if frontend changes are needed, which they most likely are, to generate the correct default query for this.

**Comment by ethervoid** [comment]
I've missed a lot of that changes so I'm not in the best position to propose but I'm refering to the "internal" queries like grants for example.

Maybe I've totally missed the point and what I'm saying doesn't have sense at all.

**Comment by javitonino** [comment]
Yes, we can always quote the internal queries such as the grants, but without changes to the user query, the table would be unusable in the dataset view, so there is little point in having the table correctly registered.

And I think there is value in having the same code for our internal queries than for the ones generated for the user, we catch errors faster. We probably wouldn't have caught this one if our internal queries succeeded, but the user wouldn't be able to access the dataset view.

**Comment by ethervoid** [comment]
Ok, now I see your point. So if I've understood it correctly, we could escape in the internal part and change the [table_utils](https://github.com/CartoDB/cartodb/blob/38b3647a82281154628cf31555e68601cc95cb32/lib/carto/table_utils.rb#L22) in order to take into account that tables that start with number should be quoted right?

**Comment by javitonino** [comment]
Changing `table_utils` should be enough as that gets used for both internal and user queries (or at least, we try for all queries to go though that). We would need to change the frontend too, I think this function is enough: https://github.com/CartoDB/cartodb/blame/master/lib/assets/javascripts/cartodb3/helpers/utils.js#L184

**Comment by ethervoid** [comment]
I see that is a module included everywhere that have queries for example: https://github.com/CartoDB/cartodb/blob/16ee1aa941addd8b3531fef4507371dccaee8422/app/models/table.rb#L26

Great :)
