### ISSUE TITLE
Null values breaking style by value -> category symbology

### ISSUE THREAD

**Issue by makella** [CartoDB/cartodb#9968]
Working on a table:
- I added a new field `democrat_winner` (type `string`) using the +ADD COLUMN option from data view 
- Next, I updated the column with two conditional statements 
 - `UPDATE primary_results SET democrat_winner = 'bernie' WHERE bernie_votes > hillary_votes` and the opposite for `democrat_winner = hillary` all other values are `null`
- Next, I chose the option to CREATE MAP
- When I went to symbolize the `democrat_winner` field by value, I got this dialogue
 - 
![screen shot 2016-09-30 at 2 06 48 pm](https://cloud.githubusercontent.com/assets/1566273/19007225/0bde7042-8721-11e6-8ee9-5114b3e26810.png)

- After some trial and error with @ohasselblad we realized that in order for the column values to be detected, we had to exclude the `null` values 
 - `SELECT * FROM primary_results 
WHERE democrat_winner is not null`

I also tried duplicating the dataset and exporting the dataset and adding it fresh to my account to see if that would fix the symbology issue but was getting the same result.

The table I did this on is here: 
https://team.carto.com/u/mamataakella/dataset/primary_results_transposed_simplified

**Comment by saleiva** [comment]
cc / @xavijam
