### ISSUE TITLE
public pages: wrong url for datasets in team member account

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#9973]
- when accessing a dataset from the datasets index view in a organization member account, and the current logged in user is member of the same organization, the visitor is redirected to a wrong URL
- also, the exact same page exists with several urls, which is penalising in terms of SEO /cc @beloneys 

**str**
- login with "team" organization user (i.e. matallo)
- go to other org. member datasets index view (i.e. https://team.carto.com/u/javi/datasets)
- go to a dataset
- the expected url is https://team.carto.com/u/javi/tables/mercadona/public/map?redirected=true
- the actual url is https://team.carto.com/u/matallo/tables/javi.mercadona/public/map?redirected=true

**seo comments**

@beloneys didn't we have these duplicated pages detected during the audit? They don't seem to be indexing, nor original user nor the wrong url (see attached)

<img width="873" alt="screen shot 2016-10-03 at 11 53 33" src="https://cloud.githubusercontent.com/assets/36676/19033841/d823e60a-8960-11e6-921c-9a41f2d4a243.png">

/cc @gfiorav @javitonino (for builder public pages)

**Comment by javitonino** [comment]
That redirection is actually done on purpose and is necessary for private datasets shared within the organization to work. The URL with `/u/dataset_owner` does not work for those.

The redirection system is a mess, specially regarding organizations, and now with editor/builder urls. We can change this if it is needed, and maybe it makes sense that public visualizations have a different url that privately shared ones (after all, they load different views atm).

This to say: we could change it for public visualizations if it's important for SEO, but it's not a trivial change. Also I would not consider this a bug, but rather an improvement, as this is working as designed (even if we don't like it).

**Comment by matallo** [comment]
whoa, I wouldn't prioritize this at all, but from the visitor perspective:

- I'd expect the url to reflect the structure of the site, that could lead to think that map is from the visitor instead of the creator

in any case, the following scenario is definitely not desired:

- duplicated urls for the same dataset
  https://team.carto.com/u/javi/tables/mercadona/public/map?redirected=true
  https://team.carto.com/u/matallo/tables/javi.mercadona/public/map?redirected=true
- public pages not being indexed

/cc @xavijam @saleiva thoughts?

**Comment by inigomedina** [comment]
Hey @matallo, does this issue still make sense?
