### ISSUE TITLE
Filtering on widgets when having "ñ" fails

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#9976]
underscore:172 Uncaught TypeError: Cannot read property 'toString' of null

**Comment by xavijam** [comment]
Potentially a deep-insights bug, taking a look.

**Comment by xavijam** [comment]
Issue moved to [CartoDB/deep-insights.js #462](https://github.com/CartoDB/deep-insights.js/issues/462) via [**ZenHub**](https://www.zenhub.com/)
