### ISSUE TITLE
Remove builder toggle from the user account

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#9977]
![screen shot 2016-10-03 at 14 59 20](https://cloud.githubusercontent.com/assets/132146/19038061/0a2b8b44-897a-11e6-95d7-219e640b5753.png)

Related to https://github.com/CartoDB/cartodb-central/issues/1506.

**Comment by asimcox** [comment]
@csobier FYI - when this change gets pushed to production, you'll need to update the Builder FAQs :https://carto.com/docs/carto-builder/faqs/#can-i-use-carto-editor-and-carto-builder-at-the-same-time
