### ISSUE TITLE
`display: none` yields unrecognized rule: display

### ISSUE THREAD

**Issue by duhaime** [CartoDB/cartodb#9979]
Hi All,

Thanks for this awesome application. I'm working with a team that wants to hide the footer on a Carto iframe. When I add:

```
.cartodb-text {
  display: none;
}
```

to the map's CartoCSS field, however, I get `unrecognized rule: display`. A similar error springs if I try using other common css properties (float, position, etc). Do you know how I can l use these CSS rules in the CartoCSS input box? Any help you can offer would be greatly appreciated!

**Comment by duhaime** [comment]
In case others end up here, I realized it's easier to just hide the footer from the page in which the iframe is being embedded, by placing a wrapper around the iframe and setting the height of the iframe to 100% + the height of the Carto footer (30px):

```
.iframe-container {
  width: 100%;
  height: calc(30px + 100%);
  position: absolute;
  overflow: hidden;
  z-index: 1;
}
```

**Comment by ramiroaznar** [comment]
Regarding your first comment, correct me if I am wrong but it looks like you are mixing CSS with [CartoCSS](https://carto.com/docs/carto-engine/cartocss/). Should I close this then?

**Comment by duhaime** [comment]
@ramiroaznar Is it only possible to use "cartocss" in Carto? Can one not use regular css?

**Comment by ramiroaznar** [comment]
Yes, it is only possible to use CartoCSS for styling map layers. You can use CSS to style your whole application when using CARTO.js, [as I did with this layer selector in this block](http://bl.ocks.org/ramiroaznar/64c12eae1cd33433b05eba972a992e62).

**Comment by duhaime** [comment]
Amen, thanks very much @ramiroaznar!
