### ISSUE TITLE
Builder and dataset redirections

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#9981]
So:

- If a user has viz.json v2 visualizations, they should be opened with the Editor. Public maps should be opened with the public editor map, and builder map can't be reached.
- If a user has "migrated" its map to Builder, public or embed Editor map should redirect to Builder public map.

What about the table/dataset view?
- If a user has Builder enabled, dataset view.
- If a user has Editor enabled, table view (GME users for example).
- For public viewers, table view

Take into account this [premise](https://github.com/CartoDB/cartodb/issues/9978).

**Comment by xavijam** [comment]
cc @MariaCheca

**Comment by javitonino** [comment]
Are we going to also redirect the old public map view to the new embed? What about the dataset view?

**Comment by xavijam** [comment]
Further to dataset question, answered (hopefully) in the description. About the redirection, if the user has the Builder enabled, public map view should redirect to Builder embed, yes.

**Comment by javitonino** [comment]
:+1: Have we ever tested the dataset view as a public (not logged in) view? Right now we are still redirecting public views of builder datasets to the old dataset view.

**Comment by xavijam** [comment]
There is no problem with the dataset redirect, it is ok in the meantime.
