### ISSUE TITLE
Add r/w permission label in dataset view

### ISSUE THREAD

**Issue by MariaCheca** [CartoDB/cartodb#9982]
This element is present in the designs but hasn't been implemented yet.

<img width="320" alt="screen shot 2016-10-03 at 16 16 17" src="https://cloud.githubusercontent.com/assets/2141690/19040531/cec5706e-8984-11e6-9c8d-c3a6b58dfe9d.png">

cc @xavijam

**Comment by xavijam** [comment]
Thanks for spotting it @MariaCheca 🤗

**Comment by saleiva** [comment]
Good spot! HA!
