### ISSUE TITLE
Named maps should use preview_layers to show/hide layers

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb#9984]
As per https://github.com/CartoDB/Windshaft-cartodb/pull/568, using preview_layers in named map it is possible to show/hide specific layers in Static Maps (image previews), without having to apply any hacky solution like `where 1=0` thingy.

So when the user hides a layer from the builder we should consider that when generating the named map.

cc @xavijam @dgaubert @gfiorav

**Comment by gfiorav** [comment]
Great! All for it, I can take care of this. One thing: I asked @dgaubert if we could deprecate the placeholder hack when this came out. IIRC, the fact was that the editor visualisations (vs Builder visualizations) still relied on this. Has this situation changed?

**Comment by rochoa** [comment]
We can't, as cartodb.js v3 does not have support for new show/hide features.

**Comment by gfiorav** [comment]
👌 should I assign this then? Or is it still WIP?

**Comment by rochoa** [comment]
The `preview_layers` feature is already done, so you can start using it :).
