### ISSUE TITLE
Heatmap's style crashes my map sometimes 

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#9988]
Looks like it might be an error with this image http://s3.amazonaws.com/com.cartodb.assets.static/alphamarker.png that sometimes loads as a **http** and sometimes as a **https**. When it loads as a http, the map doesn't load and an error notification appears:

**"This map couldn't be rendered. Please refresh the page and contact us if the error persists."**

with this on the console: 

`Mixed Content: The page at 'https://team.carto.com/u/arianaescobar/builder/27052f5c-80cb-11e6-bba4-0e98b61680bf' was loaded over HTTPS, but requested an insecure script 'http://arianaescobar.cartodb.com/api/v1/map?config=%7B%22version%22%3A%221.…lback=_cdbct_1962125114_5&map_key=b44e20e1cf8d0ebf7c9ff1d34d3a67522107f7c9'. This request has been blocked; the content must be served over HTTPS.`

Video with error: https://www.dropbox.com/s/76dkhz827kwjptu/gif.webm?dl=0

Let me know if you need anymore information or context :)

**Comment by ramiroaznar** [comment]
Hey @arianaescobar do you have STR, .carto? If not, we can close this issue.

**Comment by ramiroaznar** [comment]
Closing this then.
