### ISSUE TITLE
Error deleting user: FK geocoding to dataimport

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#9992]
We ran into some problems deleting organization users with geocodings. During `before_destroy` the data imports are destroyed, which results in an error about the FK from geocodings to data imports failing.

In theory, this should not be a problem, as earlier in the process `assign_geocodings_to_organization_owner` is called, which should nullify those references so the data imports can be deleted.

The main reason this can happen if there are geocodings from one user pointing to data imports with a different user. I don't know if that is supposed to be allowed. Other reasons are possible, but that seems the most likely looking at the code.

E.g.
- Geocoding G1 has user A and DataImport D1
- DataImport D2 has user B
- Deleting user B won't touch G1, and fail deleting D2 due to the FK

cc @CartoDB/backend

**Comment by juanignaciosl** [comment]
Oh, geocoding tabes from other users wasn't possible time ago (see CartoDB/cartodb/issues/3775) but it looks like recent changes made it work.

Nevertheless, geocoding a table from other user sets `geocodings.data_import_id` to `NULL` (which makes sense, as this is not a data import geocoding).

@javitonino is `assign_geocodings_to_organization_owner` done in the same transaction than the failing destroying query is?

**Comment by javitonino** [comment]
Yes, it is. No problems with transactions/ORM here, it appears to be a pure DB issue. Note these are old users, it may very well be a problem that isn't there anymore.

**Comment by juanignaciosl** [comment]
Closing automatically because of inactivity. If anybody considers that this still important, please reopen and it'll be prioritized.
