### ISSUE TITLE
popup show info when we don't have any selected

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#9993]
**str**

- go to hover > select fields > apply custom
- disable sql, confirm

**expected behaviour**

- custom hover goes away

**actual behaviour**

- custom hover remains

solving this at the same time when changing between click/hover the "values | html" toggle is disabled with the fields view selected, instead of the html (you can't edit further)

also, fixed the popup type when changing from click/hover, and loading the page

---

![infowindow](https://cloud.githubusercontent.com/assets/1214201/19066238/8fe466e0-8a18-11e6-82c9-7fc4bdffc543.gif)

**Comment by xavijam** [comment]
@matallo, all yours man!

**Comment by xavijam** [comment]
Please @piensaenpixel, could you ellaborate the steps to reproduce it please?

**Comment by matallo** [comment]
can't reproduce, I need more info or steps to reproduce indeed

**Comment by piensaenpixel** [comment]
ok, let me see how i can reproduce it, it's happening in one map, but i could try reproduce it :) if i can't i'll close it.

**Comment by matallo** [comment]
I managed to replicate it, writing the str in the description
