### ISSUE TITLE
Color popup show white space when we only have header

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#9995]
![image](https://cloud.githubusercontent.com/assets/1214201/19066313/fb26fe68-8a18-11e6-9212-0f1ca5968e87.png)

Take a look cartodb.js

![image](https://cloud.githubusercontent.com/assets/1214201/19066348/2781a7ce-8a19-11e6-84e8-442b9b1cc481.png)

**Comment by xavijam** [comment]
That's true, @matallo take care of it please 💋

**Comment by matallo** [comment]
on it

**Comment by inigomedina** [comment]
Hey @matallo, does this issue still make sense?

**Comment by matallo** [comment]
just checked and it does

**Comment by alrocar** [comment]
Stale issue. Closing 👋
