### ISSUE TITLE
Deleting organization fails if owner has shared entities

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#9996]
In https://github.com/CartoDB/cartodb/pull/9395 we made it so deleting an organization doesn't care about shared entities. However, this patch was only applied for non-owner user. If the owner has shared entities, the deletion still fails.

Also points out to a potential problem, what happens with shared entities when the user it is shared with is destroyed?

**Comment by juanignaciosl** [comment]
Closing automatically because of inactivity. If anybody considers that this still important, please reopen and it'll be prioritized.
